### PR TITLE
Set Salamander round restart time to 5 minutes

### PR DESCRIPTION
**Pull request by JIPDawg**
## About the PR

Changed the round restart time to 5 minutes for the Salamander server.

## Why / Balance

As an MRP server I fully believe that 2 minutes is much to short for any kind of end of shift RP, 5 minutes allows for a little bit of extra time to discuss the events of the station 

## Technical details

totally not a web edit. 
I did test.

## Media

image

## Requirements

- [ x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: On Salamander the round will now restart after 5 minutes from when the Evac shuttle arrives at CentCom.

### CODE REVIEW

**Comment by Golinth** [comment]
I swear at some point it _was_ 5 minutes, but it got changed because EOR RP is pretty boring and samey

**Comment by JIPDawg** [comment]
> I swear at some point it _was_ 5 minutes, but it got changed because EOR RP is pretty boring and samey

I just checked the blame on Salamander.toml and it doesn't look like it was ever set to 5.

**Review by IProduceWidgets — APPROVED** [review]
I know some admins will change it to 5min but they have to do it manually. Not sure if its worth having the extra two minutes at the end of the round, but I also don't see any big reason we can't try it and see if people complain about it being boring. 

As long as it doesnt lead to more ahelps about EORG Idrc.

**Comment by Golinth** [comment]
> > I swear at some point it _was_ 5 minutes, but it got changed because EOR RP is pretty boring and samey
> 
> I just checked the blame on Salamander.toml and it doesn't look like it was ever set to 5.

#19374

Turns out it was only for a day or two. And reverted for entirely different reasons. Dunno why I thought it was longer.

**Comment by JIPDawg** [comment]
> > > I swear at some point it _was_ 5 minutes, but it got changed because EOR RP is pretty boring and samey
> > 
> > 
> > I just checked the blame on Salamander.toml and it doesn't look like it was ever set to 5.
> 
> #19374
> 
> Turns out it was only for a day or two. And reverted for entirely different reasons. Dunno why I thought it was longer.

#19462 Looks like it was reverted because something was bugging out the round restart to go past 5 minutes and in some cases not restart at all? Certainly odd, hopefully whatever caused it has been fixed? I'm fairly certain on other forks some MRP servers have it set to 5 minutes with no issue.

**Comment by lzk228** [comment]
you can hate me but i will say that there are not too much real rp on salamander, so these 5 minutes won't be any better, and anyone who still plays some rp will play it despite the available time on cc

**Comment by ArtisticRoomba** [comment]
I'd argue that there are still some good RP moments at the end of CC and giving players more time here might be more of an incentive to give their story an end.

I remember when I first started playing on Salamander admins would give players more time at CC to roleplay and finish their stories. Things may be different now but they may change in the future.

Also lowpop hours roleplay more, so this would be good for them.

**Comment by JIPDawg** [comment]
> you can hate me but i will say that there are not too much real rp on salamander, so these 5 minutes won't be any better, and anyone who still plays some rp will play it despite the available time on cc

I can't say I fully disagree, players have noticed a decline in RP on salamander but as others have said low|medium pop are a bitt better in this regard. Also some days are better than others I'm terms of RP quality.

**Review by slarticodefast — APPROVED** [review]
I confirmed that this works for Harmony and CD, so the problems we had with the cvar seem to be fixed now.

**Comment by superjj18** [comment]
> you can hate me but i will say that there are not too much real rp on salamander, so these 5 minutes won't be any better, and anyone who still plays some rp will play it despite the available time on cc

The longer round end time will make the tiders get bored and cause them to get baited into EORG for easier dewhitelisting :trollface:

**Comment by Everturning** [comment]
just because salamander is declining in RP doesn't mean there's no RP

**Review by chromiumboy — APPROVED** [review]
This was approved by the other maints on Discord. @slarticodefast, do you want to merge this to stable?

**Comment by slarticodefast** [comment]
Yeah, I'm collecting a bunch of hotfixes

**Pull request merged**
