### PR TITLE
Swimsuits clothing

### PR DESCRIPTION
**Pull request by Awlod**
Adding "swimsuit" clothing
The author of the sprite: KBAS5
The author of the code for sprites: Sergan_31

## About the PR
 Bringing new clothes into the game, namely a swimsuit

## Why / Balance
 I think it's cool.

## Media
swimsuits

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
 adding swimsuits

### CODE REVIEW

**Comment by Sergan31** [comment]
oh yes, that my code

**Comment by TheShuEd** [comment]
Cl is broken

**Comment by Sergan31** [comment]
i know
my code is shit

**Comment by Sergan31** [comment]
i make its again later

**Comment by TheShuEd** [comment]
CL = 
image

**Comment by EmoGarbage404** [comment]
I don't think that these swimsuits really have a place in the game as is. Furthermore, these aren't obtainable in any way & there isn't really a setting where these are appropriate. As such, I'll be closing this PR.

**Pull request closed without merging**
