### PR TITLE
Job Distribution Error event

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Adds new type of event, that will add some new specific roles to late join.

## Why / Balance

for more fun and round variety

## Technical details

The rule picks jobs and all other variables from component and then adds it to late join

## Media

https://github.com/user-attachments/assets/cb7f42eb-326e-4741-994e-57b2a9800d04

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

nope

**Changelog**

:cl:
- add: Added new Job Distribution Error event. Some specific jobs will be available for late join that are not found on Space Station 14 under normal circumstances.

### CODE REVIEW

**Comment by lzk228** [comment]
> Return of CC job role?

what do you mean by that?

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
Security clown is real!

**Comment by thebadman4662** [comment]
Brigchem role is so back.

**Comment by Yousifb26** [comment]
I highly recommend removing the super synth from the party planner since those don’t respect MIDI limits, in the wrong hands it can possibly crash a server.

**Comment by beck-thompson** [comment]
I love this idea!

**Comment by lzk228** [comment]
basically, it's done, but i have a bug, these roles spawn without survival box, really don't know how to fix that

**Comment by Dutch-VanDerLinde** [comment]
> basically, it's done, but i have a bug, these roles spawn without survival box, really don't know how to fix that

they need the survival box loadout

**Comment by lzk228** [comment]
> > basically, it's done, but i have a bug, these roles spawn without survival box, really don't know how to fix that
> 
> they need the survival box loadout

yeah, that's what i did
image

**Comment by Dutch-VanDerLinde** [comment]
probably since those jobs arent in the character customization screen, the loadout isnt set, so you'd need to make the loadout set somehow (maybe like how ghost roles do it)

**Comment by GoldenCan** [comment]
Incredible PR.

... but i have a minor nitpick.
I would personaly prefer if the security clown required security playtime instead of 10 hours of playtime with any job. I don't think the security playtime requirement for security clown needs to be as high as the one for security officer (10 hours security). I think 2 hours of security would work well.


Also, i believe i spotted a mistake? This PR adds a playtime tracker for a "JobFloraInspector", but it does not add a Flora Inspector job.

Again, incredible PR!

**Comment by lzk228** [comment]
> I would personaly prefer if the security clown required security playtime instead of 10 hours of playtime with any job.

i took the same time as cadet needs, i adhere the policy of "don't timegate fun"
image



> Also, i believe i spotted a mistake? This PR adds a playtime tracker for a "JobFloraInspector", but it does not add a Flora Inspector job.

oh, thanks, i replaced it with party maker

**Comment by superjj18** [comment]
I very much would love to see a rare CentComm Official/visitor role in this.

Has the benefit of nullifying the metagaming of "is this CentComm person on station an admin or an antag, because I know it's has to be one or the other"

Would be especially good for mrp.  Definitely needs to be rare, and possibly gated behind Captain time requirements

**Comment by lzk228** [comment]
stale, couldn't fix the issue i was talking before

**Comment by empty0set** [comment]
2024-12-31-145645_1920x1080_scrot

Hi!  I believe the bug was due to the role loadout spawning before the starting gear, so the survival box was trying to spawn before the container, and when that wasn't found just not doing it.

Fixed by removing the backpack from Roles/Jobs/Wildscard/ .yml files & adding CommonBackpack / ClownBackpack to their respective groups in role_loadouts.yml

@lzk228 If you're still interested I can push the changes.

**Pull request closed without merging**
