### PR TITLE
Medic hardsuit stats ss14

### PR DESCRIPTION
**Pull request by Kukutis96513**
## About the PR

Changed the syndicate medic hardsuit's stats to be like the elite hardsuit's (the previous hardsuit for the nuclear operative medic)
## Why / Balance

https://discord.com/channels/310555209753690112/1158344927575539753 <- discussion
This was changed because it was pretty much a nerf to the syndicate medic's hardsuit due to them receiving the medic one instead of the elite.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Shouldn't have broken anything fairly sure.
**Changelog**

- tweak: Changed the syndicate medic's hardsuit armor stats to be like they were before.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I'd like to see a better discussion regarding *why* the increased armor is the best change for the role. Simply saying that it was reduced isn't really a complete juatification for why it should be undone.

I'm aware of some of the arguments for why it was preferred, but I feel like there are better alternatives that emphasize the unique nature of the medic role.

**Comment by JoeHammad1844** [comment]
just make the elite hardsuit purchasable

i think 10TC is the best price because in ss13 the elite hardsuit was 8TC and they only had 30TC, so we have 1.33x ss13 nukies so 1.33x 8 = 10 (rounding down)

**Comment by Emisse** [comment]
i would be fine with syringe gun exclusively for nukie medic

**Comment by JoeHammad1844** [comment]
> i would be fine with syringe gun exclusively for nukie medic

or have syringes not pierce hardsuits

also, on TG station there is one syringe gun round start that has to be worn on the back to be stored and only loads one syringe

and reagent gun would be cool for chemist syndies

**Pull request closed without merging**
