### PR TITLE
remove toolbox turret from core

### PR DESCRIPTION
**Pull request by MisterMecky**
## About the PR

Core had a syndicate turret toolbox mapped by accident, replaced it with a regular electrical toolbox.
## Why / Balance

An oopsie
## Technical details

N/A
## Media

Turret in question.
coreturrettoolbox

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by MisterMecky** [comment]
if they're working on an update I'll just close this

**Comment by UbaserB** [comment]
Thank you. There really needs to be some way to communicate that there should be no PRs for core right now, but I’m not sure what should be done.

**Comment by lzk228** [comment]
> Thank you. There really needs to be some way to communicate that there should be no PRs for core right now, but I’m not sure what should be done.

you should finally end your work with core and make the pr :trollface:

**Comment by UbaserB** [comment]
> you should finally end your work with core and make the pr :trollface:

It would be easier if i didn’t have tests after tests with cramming every night. Anyway, expect the PR on the weekends.

**Pull request closed without merging**
