### PR TITLE
Makes the Nuke require Central Command or Nuclear Operative access to toggle Nuke Anchor

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Make the nuke require Central Command or Nuclear Operative to toggle anchor
## Why / Balance

Having the crew hide the station nuke during nukies shifts is the worst thing and ultimately leads to the nukies just murderboning the entire crew in the search. This will prevent the crew from removing the nuke from the vault while still allowing the people who should be moving it (central command officials, death squad, and nukies) to be able to move it.
## Technical details

Makes a check for the access level on the id, and adds that check to the anchoring code.
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/9711852b-a866-4949-9b26-cb940c12cf25

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Now only IDs with Central Command or Nuclear Operative can toggle the anchor on the nuke.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
If you dont want people hiding the station anchor then just make it unable to be unanchored. Hardcoding it to nukeops only is just nonsensical and heavy handed

**Comment by Plykiya** [comment]
> If you dont want people hiding the station anchor then just make it unable to be unanchored. Hardcoding it to nukeops only is just nonsensical and heavy handed

some stations have a nuke too close to space by default which causes the nuke be unable to be triggered, and that'd be easily abusable


The most fair "don't let random crew members move this nuke around" option would be letting the nuke be unanchored only if the nuke disk is in it, and only giving the nuke disk back if the nuke is anchored. It lets the nukies track the nuke if the nuke is moving around

**Comment by metalgearsloth** [comment]
Make it unanchorable without disk or add a pinpointer, either is good.

**Comment by EmoGarbage404** [comment]
> Some stations have a nuke too close to space by default which causes the nuke to be unable to be triggered, and that'd be easily abusable. There's a dozen possibilities that would cause lockout that aren't really anyone's faults.

you could just disable the requirement for nukes locked in place. i dont think that's particularly hard to do.

> This is in addition to letting nukies freely move the nuke around... because their own nuke needs to be unanchored and anchored as well

i mean the most reasonable thing (which some ss13 servers do) is just have 2 distinct nukes. One is the mobile one that can just be dragged around (the one the nukies spawn with) and the second is the fixed station nuke. They have different sprites IIRC. i think that would be the best of both worlds.

**Comment by Plykiya** [comment]
> Make it unanchorable without disk or add a pinpointer, either is good.

Would every nukie have the pinpointer? Do you just want it to be one combined pinpointer that can swap between nuke disk and intended nuke or two different pinpointers?

**Comment by Cojoke-dot** [comment]
hah, plutonium core merge conflict. 

I think I like the unanchorable without nuke disk most. Having a stationary nuke sounds like fewer options for the nukies when on station.

**Pull request closed without merging**
