### PR TITLE
Stripped free agent from SDV and a few vermin

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

Stripped free agent from SDV and a few vermin
## Why / Balance

These roles are problematic, the admin issues I've seen with them involve complaining about how since they are free agents they should be allowed to murder or do other shit
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- remove: Removed Free Agent Status From Syndicate Disaster Victims and Mothroaches

### CODE REVIEW

**Comment by slarticodefast** [comment]
Mothroaches no longer deal melee damage since #32221
So I don't really get why they should be different from mice, which are free agents.
Same with snoths, how are they different from snails?

**Comment by thebadman4662** [comment]
Syndies being non-antags will be weird at very least, NT aligned crew have IC reasons to not entirely trust them and free agent status plays into that while still not forcing them to be antagonistic and giving them more freedom for how they want to interact with crew.

Non-antag victims already had a lot of trouble and there isn't IC precedent for accepting them yet, [though certain someone is making effort to add it to space law even for enemies of NT.](https://wiki.spacestation14.com/wiki/User:BRINGit34/Space_Law#Vessels) By losing wildcard status, they become kind of punching bags should they get denied, rightfully or not, they are also as close as it gets for "hostile boarders" event should they choose to be one as lowpop chinalake nukie is the next step and can absolutely wipe out whole station on their own.

**Comment by superjj18** [comment]
I’d say give SDV a % chance of being a proper syndicate antag

**Comment by FungiFellow** [comment]
SDV get treated like budget Nukies too often. They shouldn't be an antag

**Comment by UncaughtEx** [comment]
Not a fan of this PR

**Comment by lanse12** [comment]
back to the good old days of robbing sdvs for free syndie comms

**Comment by slarticodefast** [comment]
Hey, I brought this up for discussion with the maintainers and admins.
Making mothroaches and snoths no longer free agents is inconsistent for the reasons already mentioned above. Also they need it because they steal consumables.
According to the admins the syndicate disaster victims being non-free agents caused a similar amount of issues before, possibly even more, since having a syndicate non-antagonist is confusing to players. They were recently changed to be free agents exactly for that reason.
As such I will be closing this PR. Thank you for your contribution.

**Pull request closed without merging**
