### PR TITLE
Added welding gas mask!

### PR DESCRIPTION
**Pull request by Stanislav4ix**
## About the PR
Added a gas welding mask for working mostly in space. Unless, of course, you don't have special glasses. You can get it from Engi-Vend, hacked (not by EMAG) YouTool, and robotics vending machines.

## Why / Balance
Made mainly for miners, because this mask is easier to get than glasses, plus you can leave space for security/sun glasses.

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Stanislav4ix
- add: Added welding gas mask!

### CODE REVIEW

**Comment by Partmedia** [comment]
I'm concerned that having simultaneous welding and flash protection is too powerful. Can you please discuss balance concerns and why this is necessary for miners?

**Comment by deltanedas** [comment]
salv dont need sunglasses, they just get goggles roundstart no issues

for syndies they can just get syndie gas mask

**Comment by Kadeo64** [comment]
holy shit, finally, welding mask for roboticists. it's perfect.

**Comment by Aisu9** [comment]
welding protection, internal, hide face and provide 5% damage reduction from physical and heat damage, i think thats a bit too much for something that is mainly supposed to be another tool, considering hardsuit headpieces will allow for internal soon-ish. everyone will just hack these vend to get powergamer protection loot

**Comment by Stanislav4ix** [comment]
> welding protection, internal, hide face and provide 5% damage reduction from physical and heat damage, i think thats a bit too much for something that is mainly supposed to be another tool, considering hardsuit headpieces will allow for internal soon-ish. everyone will just hack these vend to get powergamer protection loot

the damage system is already being reworked, so the 5% doesn't play a big role.  Moreover, if we think from the side of RP, then the mask must be solid so that the glass does not fall out

**Comment by LankLTE** [comment]
As stated earlier, this needs justification as to why it's necessary to miners, and that simultaneous flash and welding protection won't be too strong. Hardsuits now also allow internals without a gas mask which may make this unnecessary.

**Comment by UbaserB** [comment]
the sprite looks like it probably needs improvements

**Comment by Stanislav4ix** [comment]
> As stated earlier, this needs justification as to why it's necessary to miners, and that simultaneous flash and welding protection won't be too strong. Hardsuits now also allow internals without a gas mask which may make this unnecessary. 

As you say "flash protection", I think it's normal considering that a normal welding mask has protection against flash and welding.  Although now you can breathe without a mask, but only wearing hard suits.  For example, I want to fly on an expedition and instead of wearing a hard suit that has little protection, I can wear a welding gas mask and very good armor, for example riot.  This mask is also important for roboticists.

**Comment by Stanislav4ix** [comment]
I'm pretty sure you want to wear eye protection and a hat, but welding masks don't let you do that

**Comment by Partmedia** [comment]
Thank you for your PR. Unfortunately, I'm opting to close this because:

1. This makes eye protection too easily obtainable
2. The armor values, combined with the protections, make this item too strong

If you have more questions, please feel free to continue discussing here or on Discord.

**Pull request closed without merging**
