### PR TITLE
Simplifying Machine Upgrading

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

tl;dr
Machine upgrading isn't very intuitive, so let's standardize the names and remove some of the part types to make it more sensible.
this includes map changes for which i will die.
this also standardizes a bunch of the boards to not use parts for no reason.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Removed the laser and scanning module machine parts.
- tweak: Adjusted recipes for many machine boards.

### CODE REVIEW

**Comment by Emisse** [comment]
map changes are going to goncflict with clusters current pr

**Comment by EmoGarbage404** [comment]
> map changes are going to goncflict with clusters current pr

the only thing they have to do is remove lasers and scanning modules

**Comment by Emisse** [comment]
this pr is holding further map updates hostage im gonna smash my computer

**Comment by LordEclipse** [comment]
what the hell is a "matter bin" and "manipulator"

**Comment by DummeHytteOst** [comment]
> what the hell is a "matter bin" and "manipulator"

both are items used to make and upgrade machines, just like the lasers, capacitators and scanning modules

**Comment by deltanedas** [comment]
forgot the /s :trollface:

**Comment by Emisse** [comment]
you need to update this for the new cluster update that was merged

**Comment by EmoGarbage404** [comment]
This has been updated to master

**Pull request merged**
