### PR TITLE
Refactored RoundEndSystem 

### PR DESCRIPTION
**Pull request by wrexbe**
Fixes this
https://github.com/space-wizards/space-station-14/issues/5874

### CODE REVIEW

**Comment by ShadowCommander** [comment]
This should probably just check if it's already ending round at the beginning of the EndRound method.

**Comment by wrexbe** [comment]
I'm not sure it's centralized enough for that to work, without changing a lot more. That section looked messy, but I could be wrong.

**Review by PaulRitter — CHANGES_REQUESTED** [review]
timer.spawn has a cancellationtoken. just have a global cancellationtoken for it & cancel it whenever someone calls either command

**Review by ShadowCommander — APPROVED** [review]

**Review by moonheart08 — APPROVED** [review]

**Comment by ike709** [comment]
The issue wasn't autoclosed because the PR desc isn't formatted properly to autoclose it.

**Pull request merged**
