### PR TITLE
remove rat king from MouseMigration event. adding RatKingSpawn event

### PR DESCRIPTION
**Pull request by NazrinNya**
## About the PR
This PR separates removes ratking spawn from MouseMigration, leading to new RatKingSpawn event
## Why / Balance
This prevents rat king from spawning on barely empty (<15 players) servers, which is leading to rat king killing everyone.

## Breaking changes
No.

**Changelog**
:cl:
- tweak: Rat king spawn is now separated from MouseMigration event (RatKingSpawn)

### CODE REVIEW

**Comment by lzk228** [comment]
ratking should be separated from mousemigration event

**Comment by UbaserB** [comment]
yeah, what lzk said

**Comment by NazrinNya** [comment]
> ratking should be separated from mousemigration event

I know, but it require some testing, probably will do once im free

**Comment by NazrinNya** [comment]
done

**Comment by deltanedas** [comment]
#28872 :trollface:

**Pull request closed without merging**
