### PR TITLE
 Add steak and steak cutlet recipes to microwave

### PR DESCRIPTION
**Pull request by pewter-wiz**
- Adds recipes for already existing Cooked versions of FoodMeat items
- Adds recipe for filet migrawr (flaming bear steak)
- Adds recipes for Cooked Cutlet versions of FoodMeat Cutlet items.
- Adds recipe for Cooked bacon (is bacon a cutlet??)
- Adds commented recipes with TODOs where they would make sense but aren't programmed or sprited.

## About the PR
This PR adds existing steak and cooked cutlet recipes to the microwave!

## Why / Balance
Playing as the chef, I had a customer request steak. I happily agreed, walking over to the microwave with meat in hand. I popped it in for 15 seconds... nothing! 5? 10? 20? 25? 30? Nothing...

We can cook burgers, meatballs, and all kinds of other cooked meat dishes in the microwave but not the simple steak.

Looking to the code, I sought to remedy this issue and to my delight, most meats and cutlets already have cooked varieties sprited and fully coded: just not hooked up to the microwave recipe system.

After digging into the code more, it seems a more complex cooking system exists there, based on temperature, and state graphs, indended for a versitle array of chefs tools to be used (ovens, stoves, campfires, etc) with the microwave acting as a stand-in for now. I propose we add these recipes to the microwave, as they seem a gaping hole in the chefs current capabilities, and it does not hinder any future implemetation of the more complex cooking system.

I have arbitrarily chosen 15 seconds for full steaks and 10 seconds for cutlets (though 5 seconds could make sense also, since meat -> 3 cutlets ergo cutlet 1/3 of a steak)

For filet migrawr, the sprite has animated fire so I chose 5 units of vodka as a reagent in the recipe to differentiate it from the regular bear steak, and since vodka is both flammable and relates to the bear motif via USSR/Russian iconography.

And so I say... LET THEM EAT STEAK!

## Technical details
This is not a code change, only .yml content hooking up existing sprited and coded items.

## Media

Below is depicted all the cookable steak recipes I have added, plus the ones I have TODO'd that don't work due to lack of sprite/coded item to use.
Steak Update
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Microwave recipes for most varieties of steak, as well as their cutlets, including additional recipes for Microwaving bacon, and filet migrawr (flaming bear steak).

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Instead of adding them back into the microwave, we just need to create an oven / grill to use for cooking steak more efficiently

**Comment by EmoGarbage404** [comment]
Considering you can already cook steaks slowly in the microwave using the more advanced method, im not really getting the purpose of the recipe

**Comment by pewter-wiz** [comment]
I wasn't aware that the microwave actually had heating ability, I figured it just worked off of recipes

If it takes 120 seconds of microwave to make a single steak, I still think the balance of that is off vs burgers, meatballs, kebabs, and other meat based meals, to the point where it's not obvious how to make it and even once you know is prohibitively slow

It sounds like increasing the microwave's heating would speed this up, would it have any negative consequences to other things that are microwaved?
If not, I'm happy to remove the recipes and adjust the microwave to cook meat in a reasonable amount of time

**Comment by deltanedas** [comment]
> would it have any negative consequences to other things that are microwaved?

meth would basically instantly cook if you made it say 8x speed for ~30s for a steak

**Comment by Partmedia** [comment]
I'm okay with adding these recipes as-is. It is up to someone else to "just" "create an oven / grill".

Please revise your Changelog length per the [Changelog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog).

**Comment by EmoGarbage404** [comment]
> I'm okay with adding these recipes as-is. It is up to someone else to "just" "create an oven / grill".

Considering that these recipes were removed in the past *specifically* in favor of the new temperature-based system (which is part of the long-proposed cooking rework), i would be hesitant to reintroduce them. If anything, more recipes should be moved out of the microwave.

**Comment by EmoGarbage404** [comment]
> I'm okay with adding these recipes as-is. It is up to someone else to "just" "create an oven / grill".

Considering that these recipes were removed in the past *specifically* in favor of the new temperature-based system (which is part of the long-proposed cooking rework), i would be hesitant to reintroduce them. If anything, more recipes should be moved out of the microwave.

**Comment by Partmedia** [comment]
> Considering that these recipes were removed in the past _specifically_ in favor of the new temperature-based system (which is part of the long-proposed cooking rework), i would be hesitant to reintroduce them. If anything, more recipes should be moved out of the microwave.

Making more things cookable now reduces unused content bloat. If you're offering to help the submitter convert these to temperature-based recipes, then that's fine too.

**Comment by EmoGarbage404** [comment]
They should simply use temperature based recipes instead of microwave based recipes.

**Comment by deltanedas** [comment]
this would mean adding recipe for spider leg and the cutlets, everything else is cookable in a fire/slowly in a microwave

**Comment by pewter-wiz** [comment]
> I'm okay with adding these recipes as-is. It is up to someone else to "just" "create an oven / grill".
> 
> Please revise your Changelog length per the [Changelog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog).

I have adjusted the Changelog to a single concise entry

**Comment by pewter-wiz** [comment]
What's the consensus here?

I see this as my start into PRs and contributing to SS14, and I'm happy to set my sights on making sure these items all have construction node based recipes in a future, MR, then adding a stove/oven as I feel out the codebase and learn the systems.

IMO it's better to have recipes while the alternative is effectively unsused, and circle back to remove them as other effective means of producing them exist. But I'm new here so happy for this to be merged/closed accordingly.

**Comment by deltanedas** [comment]
for meats there are recipes, 120s of microwaving or put it in a fire
adding recipes and a faster way to heat up ingredients (like how hotplate was made for chems) should be separate imo

**Comment by pewter-wiz** [comment]
The recipes exist, but with the tools at a chef's disposal, 120s of microwaving is unrealistic as it takes many many real time seconds vs 15s for a burger or kebab or meatballs.

It sounds like the consensus is to forgo adding these recipes now and instead ensurethey all have construction node based recipes, and add an item which utilises that instead of fixed recipes.

Fair enough, I'll come back with a new PR if any of the FoodMeats don't have construction node support and see what I can learn from the hotplate (thanks for the example) and how to map

**Comment by pewter-wiz** [comment]
For discussion around oven design, see here:
https://github.com/space-wizards/space-station-14/discussions/20410

**Pull request closed without merging**
