### PR TITLE
Cleans up some entity-related spawnmenu stuff

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds DO NOT MAP to the ship cannons & their machine boards (with the exception of the pirate cannon.) Moves their machine boards out of the production.yml MegaFile:tm: as well.
Adds nospawn to the ore crab spawners.

## Why / Balance
Ship guns are basically placeholder & not in a good enough state to be mapped yet. The station is completely helpless against anyone using them & basically their only balancing factor is their rarity. We already didn't want people mapping ship guns, so this just makes the game actually say it.
The orecrab spawners appear at the top of the spawn menu and were making me irrationally angry. There also isn't really a good situation I can imagine them being used in other then an admin spawning ore crabs... at which rate, you should just spawn the mob directly.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by ElectroJr** [comment]
> The orecrab spawners appear at the top of the spawn menu and were making me irrationally angry. There also isn't really a good situation I can imagine them being used in other then an admin spawning ore crabs... at which rate, you should just spawn the mob directly.

If the prototype shouldn't exist, just remove it. But don't just mark it as no spawn because it annoys you.

**Comment by TheShuEd** [comment]
Crab spawner prototypes are needed, they are used for the rock anomaly.

**Comment by TheShuEd** [comment]
But I'm against removing rocks and spawners from the menu.

**Comment by Flareguy** [comment]
> But I'm against removing rocks and spawners from the menu.

Why? There's no reason you couldn't just spawn an ore crab. The prototypes are completely unnamed and evidently probably not even meant to be used as a result, I'd think.

**Comment by TheShuEd** [comment]
I often like to use crab spawners when running events with this funny animation, it works as a good telegraph of impending danger, and is much nicer than a crab appearing out of thin air

**Pull request merged**
