### PR TITLE
Fix cooking sizzle noise

### PR DESCRIPTION
**Pull request by themias**
## About the PR

I noticed the sizzle noise when cooking meat wasn't playing. This PR fixes that.

## Technical details

We were trying to play a sound based on an entity about to be deleted (raw meat -> cooked meat). This uses the same solution from PlaySoundBehavior for DestructibleSystem where we use the current location rather than the entity which might be deleted soon.

Since construction graphs regularly replace one entity with another (and don't tend to move while being constructed), it made sense to use this new behavior in all cases, but I could also create a new IGraphAction for this case if that is better.

## Media

https://github.com/user-attachments/assets/9257236c-b81b-4f54-891b-c3a0baf8217c

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

cl not needed

### CODE REVIEW

**Comment by themias** [comment]
Test failure looks unrelated?

**Comment by slarticodefast** [comment]
>Test failure looks unrelated?

Yeah, that one randomly fails sometimes. I will re-run them for you.

**Comment by ps3moira** [comment]
Why not have it so it plays that sound whenever there's meat on it?

**Comment by themias** [comment]
> Why not have it so it plays that sound whenever there's meat on it?

That's a nice idea for an improvement. I had just been thinking about fixing the existing behavior. I can look into this too.

**Pull request merged**
