### PR TITLE
Recycler Overhaul

### LINKED ISSUE #30500: N/S/W recylcer sprites are missing
## Description
Rotating the recycler any direction other than East is bad.

**Reproduction**
Rotate the recycler any direction other than East

**Screenshots**
Wha!? 
image

**Additional context**
I'm not a great spriter. Just hoping someone will make proper sprites for all directions

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

does a bunch of things
- Adds new directional sprites for the recycler
- Makes the recycler invincible to prevent permanent removal
- the recycler now returns the full amount of materials when recycling objects.
- Properly implements breakage, allowing it to be repaired and adding custom sprites
- Allows the emag to be undone when breaking a recycler
- Removes the material reclaimer
- Fixes bug where the recycler could extract solutions it wasn't meant to (fiber from clothing, etc)

fixes #30500 

## Why / Balance

These changes are primarily to facilitate salvage's usage of the recycler in the future. The material reclaimer was really underwhelming and, though it was meant for salvaging originally, just came off as a far less flavorful version of the regular recycler. On top of that, a smaller version that is better for shuttles isn't going to be necessary once the shuttle is removed in the future.

The changes to making it invincible and the emag repairable largely just serve to not let it get trivially griefed. As its now the sole way of extracting materials, you shouldn't just be able to smack it until it breaks and gimp salvage.

## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Removed material reclaimer and related circuitboard and recipe. Should be replaced with a recycler in relevant places.

**Changelog**

:cl:
- add: The recycler can now be broken down and repaired.
- add: Breaking the recycler now removes the EMAG effect.
- tweak: The material-reclaiming efficiency of the recycler has been increased.
- fix: Fixed a bug where inaccessible solutions could be extracted from entities via the recycler.
- remove: Removed the material reclaimer.

### CODE REVIEW

**Comment by UbaserB** [comment]
based!! Finally janitors have proper reason to use the janitor other than ocd

**Comment by LordEclipse** [comment]
I think that emagged recycler being instant gib is awful all around. If you'd bother to change that!

**Comment by HelpTheSteak** [comment]
It's a easily avoided instant gib (just don't go down disposals)

**Comment by UbaserB** [comment]
> I think that emagged recycler being instant gib is awful all around. If you'd bother to change that!

after the first gib or so people pretty quickly realise it's emagged, + it takes tc for syndie to buy emag

**Comment by Flareguy** [comment]
The material reclaimer getting removed probably facilitates a breaking changes entry. There's a chance that some downstreams might use it as an important part of their gameplay loop.

**Comment by Moomoobeef** [comment]
agreed. Recycler being actually useful now is pog but removing the recycler could break things downstream.

**Comment by Golinth** [comment]
Not to mention the reclaimer is pretty helpful for extracting reagents from certain items. Is there anything that mimics that function upstream?

**Comment by lzk228** [comment]
> It kinda makes cargos job more annoying and forces QM to disposals to reclaim said materials? I dunno if I agree with the removal of the material reclaimer.

it's more a janitor's job
to reclaim junk and give materials to those who need them

**Comment by EmoGarbage404** [comment]
the recycler should be mapped into salvage at some point. I'll probably put out a mapping ping once this is done just to get things rolling.

**Comment by UbaserB** [comment]
> the recycler should be mapped into salvage at some point. I'll probably put out a mapping ping once this is done just to get things rolling.

replacing disposals or?

**Comment by EmoGarbage404** [comment]
> replacing disposals or?

i imagine you could either put disposals next to salv and make it a combo or just have a second recycler inside of salvage itself

**Comment by Hanzdegloker** [comment]
> > replacing disposals or?
> 
> i imagine you could either put disposals next to salv and make it a combo or just have a second recycler inside of salvage itself

Damn, I love being the guardian of disposals as a Jani, always saw it as apart of service.

**Comment by UbaserB** [comment]
> i imagine you could either put disposals next to salv and make it a combo or just have a second recycler inside of salvage itself

for some maps like core its not feasible to entirely move dispo near salv unless causing many more major issues, so i might as well add a second one then, thanks!

**Comment by whateverusername0** [comment]
what if an emagged recycler, instead of gibbing the target, dealt 500 slash damage and made the target scream? would be funny

**Comment by lzk228** [comment]
> what if an emagged recycler, instead of gibbing the target, dealt 500 slash damage and made the target scream? would be funny and also somewhat recoverable

out of this pr scope

**Comment by Emisse** [comment]
material reclaimer removal needs breaking change section filled out

**Pull request merged**
