### PR TITLE
Security Bola Crate

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR

Added a bola crate with 5 bolas that can be mapped or ordered from cargo for 1300 spesos.

(I was originally going to PR energy bolas but I don't really know how to work with RSIs and code a bunch of weapon stuff, especially right before PR freeze.)

## Why / Balance

Security doesn't have good access to bolas - people often point their advantages to sec, but I only remember one map that might've stocked bolas for sec. Plus crafting them takes a while and it doesn't come up often in the security gameplay loop.

Crates are priced at $1300 for 5 bolas, which is slightly expensive in both price and stock. Personally I reckon the crate should be more expensive to prevent validhunting by cargo, but I need opinions honestly.

## Technical details

yaml changes only

## Media

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes

N/A

**Changelog**

:cl: Damn Feds
- add: security can now order bola crates from cargo

### CODE REVIEW

**Comment by K-Dynamic** [comment]
No idea what this test failure is about wtf

**Comment by deltanedas** [comment]
cargo can still buy lv and steel to make their own bolas to validhunt with

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by K-Dynamic** [comment]
PR to remain closed, I'm submitting a sec crate overhaul PR tomorrow which includes bolas

**Pull request closed without merging**
