### PR TITLE
small salvages update

### PR DESCRIPTION
**Pull request by Emisse**
this updates five of the small salvages, i plan to get through them all but will eventually. for the small bar salvage i replaced the sawed off double barrel with the non lethal double barrel. here are screenshots of the redone salvages
image
image
image
image

### CODE REVIEW

**Comment by Myakot** [comment]
Last one reminded me of Outer Worlds.

**Comment by metalgearsloth** [comment]
> Last one reminded me of Outer Worlds.

do you mean outer wilds

**Comment by Myakot** [comment]
> > Last one reminded me of Outer Worlds.
> 
> do you mean outer wilds

A dangerous combination of needing more sleep and being dumb on a frequent occassion.

**Comment by spectralSpices** [comment]
Hoy DAMN, Emisse, these looks GREAT!!

**Comment by mirrorcult** [comment]
the salvage enjoyer has logged on

**Pull request merged**
