### PR TITLE
secglasses have sechud

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

secglasses now show job icons, like in ss13

sadly, sechud has a bug where if you dont have anything in your active hands it becomes night vision, please do not merge until fixed
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- add: Security glasses have been installed with heads-up-display technology, fancy!

### CODE REVIEW

**Comment by dmnct** [comment]
So literally just make SecHuds redundant and pointless?

**Comment by Partmedia** [comment]
> So this literally just makes SecHuds redundant and pointless?

Weren't security glasses already redundant and useless compared to sunglasses? I think this is an easy way to equip security officers with the new SecHuds, without changing all of the maps, lockers, and vendors. If, of course, we decide that we actually want to equip all security officers with the new SecHuds by default.

**Comment by Emisse** [comment]
we can just put sechud in lockers

**Comment by dmnct** [comment]
If we ever get criminal records, SecGlasses could show ARREST THIS PERSON icons, but not any other info that a SecHud provides?

**Comment by deltanedas** [comment]
this would make sechuds pointless
currently you have the tradeoff of using flashes vs seeing job hud which might be worth it for some

**Comment by JoeHammad1844** [comment]
in ss13 you could have both

> this would make sechuds pointless currently you have the tradeoff of using flashes vs seeing job hud which might be worth it for some

**Comment by JoeHammad1844** [comment]
and seeing job icons isn't that strong

**Comment by deltanedas** [comment]
then just remove sechud if theres no reason to give up flash resistance

**Comment by JoeHammad1844** [comment]
isnt sechud kindof hard to find

**Comment by Partmedia** [comment]
> isnt sechud kindof hard to find

Yes, but folks have chimed in and the discussion is now trying to answer:

1. Do we want SecHuds to also protect against flash or no
2. Do we want to give them SecHuds by mapping them in lockers, if so do we keep sunglasses
3. Or do we just go with this PR and add them to security glasses

**Comment by JoeHammad1844** [comment]
you can only really find mapped sechuds, you cant make or dispense more

**Comment by HoidC** [comment]
> you can only really find mapped sechuds, you cant make or dispense more

yes and emisse said they’d put some in lockers

**Comment by JoeHammad1844** [comment]
seeing job icons isnt THAT powerful, although right now they are BUGGED and are basically night vision, this was also how it worked in ss13, which I dont think anyone had a problem with

**Comment by JoeHammad1844** [comment]
there really doesn't need to be a separation of utility here

**Comment by JoeHammad1844** [comment]
why not give it a test? at least when the night vision bug is solved

**Comment by Emisse** [comment]
um id rather just have them separate for now and we can just put sechud in the security officer locker catalog fill

**Comment by dmnct** [comment]
> seeing job icons isnt THAT powerful, although right now they are BUGGED and are basically night vision, this was also how it worked in ss13, which I dont think anyone had a problem with

We already decided this is a problem with interact outlines, and that was fixed. Do this is probably a bug here but (someone) already worked out how to fix this sort of issue

**Comment by JoeHammad1844** [comment]
> um id rather just have them separate for now and we can just put sechud in the security officer locker catalog fill

I think if it worked in ss13 it would work here

**Comment by metalgearsloth** [comment]
agree with emisse, lockers

**Comment by JoeHammad1844** [comment]
mimeteen eighty four

**Pull request closed without merging**
