### PR TITLE
Allow people to change their character's height

### PR DESCRIPTION
**Pull request by Veritius**
## About the PR 
Adds a new slider to the character customisation menu for height. This directly alters the SpriteComponent's scale value. So uh... yeah, you can't set values in prototypes. You should do it in the SpeciesPrototype instead.

**Screenshots**

image

**Changelog**

:cl:
- add: You can now change your character's height.

### CODE REVIEW

**Comment by Veritius** [comment]
fails tests because efcore refuses to make a proper migration. if someone could figure out why while i sleep, that'd be lovely.

**Comment by Level10Cybermancer** [comment]
Might be good if height affected your mass so that there's at least _some_ downside to having a smaller sprite.

**Comment by ike709** [comment]
Give shorter people a slower movespeed or all of the powergamers are just going to go minimum size.

**Comment by Emisse** [comment]
dwarf height when..,

**Comment by Elijahrane** [comment]
> Might be good if height affected your mass so that there's at least _some_ downside to having a smaller sprite.

this, more and more stuff is calculated using mass

**Comment by metalgearsloth** [comment]
All of the markings are similar enough that one lizard has virtually the same hitbox as another for example but allowing people to directly make their hitbox smaller is a no from me, at least outside of HRP.

**Comment by Veritius** [comment]
This was intended to be a small little character customisation thing, but as hitboxes are tied to sprite, this can only be a mechanic.

**Pull request closed without merging**
