### PR TITLE
fix missing circuitboard recipes

### PR DESCRIPTION
**Pull request by slarticodefast**
## About the PR
Fixes this:
grafik
chemmaster and microwave are missing

## Why / Balance
bugfix

## Technical details
delta goofed in #31524 :trollface: 

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
none

**Changelog**
nah

### CODE REVIEW

**Comment by deltanedas** [comment]
me when theres no test for having either result or reagents

**Comment by slarticodefast** [comment]
>me when theres no test for having either result or reagents

Yeah, there should really be one

**Comment by metalgearsloth** [comment]
> me when theres no test for having either result or reagents

The prototype marks it as nullable which indicates it is not required.

If it is required then it should be marked as such and be made non-nullable.

**Comment by Everturning** [comment]
if you remove               AND                 then you're gonna have to remove the rest of the ss14 community too, we will not stand for                   's removal.

**Comment by deltanedas** [comment]
> required then it should be marked as such

it was, until reagent recipes were added

**Comment by deltanedas** [comment]
test has confirmed only these 3 were missing them

**Pull request merged**
