### PR TITLE
Re-organizing the prototypes folder

### PR DESCRIPTION
**Pull request by AJCM-git**
- Moving some files around to make a better layout
- Tiny cleanup to match our guidelines in some files

I also updated the code guidelines

### CODE REVIEW

**Comment by RemieRichards** [comment]
>Removes skirts from existing (i dont know why i bothered doing this if swept will probably re-add them but whatever)

not atomic, pls close pr

**Comment by Zumorica** [comment]
> * Removes skirts from existing (i dont know why i bothered doing this if swept will probably re-add them but whatever)

that's not very good boy of you

**Comment by AJCM-git** [comment]
i thought we agreed in not adding fetish content
I want my good boy points for even mentioning the change! i could had simply not mentioned it at all and get a clean merge

**Comment by PJB3005** [comment]
> i could had simply not mentioned it at all and get a clean merge

Yes, and then somebody else would go "hey where'd the skirts go" and we'd trace it right back down to you immediately and that'd be a very poor mark on your record.

Mentioning changes like this is *expected*. And yes, please undo them. If you want to have a discussion about whether they should be in-game make a separate PR.

**Comment by AJCM-git** [comment]
okay, i will make an issue for that then (the last part of the comment was in a joking tone)

**Comment by AJCM-git** [comment]
Done. 
Skirts dont work, but they dont work in master either so that one isnt on me.

**Comment by SweptWasTaken** [comment]
It's ok, my pr fixes skirts it just needs to be merged.

**Pull request merged**
