### PR TITLE
Changed Cargo Tech Sprites

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

This branch just changes the color of the cargo tech jumpsuits, drobe, and their storage such as satchels and backpacks, from yellow to the cargo brownish yellow

## Why / Balance

Me and some other users in the Alternative cargo colored uniform forum on the wizden discord came to the conclusion that the current cargo technician sprites had some major flaws when it comes to their color.
first being that because it is yellow in color it doesn't stand out from engi and that it is sometimes hard to distinguish a cargo tech and a engi just by looking at them at first glance
second: unlike alot of other departments cargo seems to sometimes mix their color palette, using yellow even though cargo's color is brown. Cargo also lacks its own personality with these yellow colors that could be better with this recolor.
therefor I decided to try and make some adjustments to them to make their sprite better.
even though this is just a simple recolor me and the other users on the forum agreed that this is a better looking sprite than cargo currently has

## Media

here are a snip showing the changes
cargotech recolor
here is another showing the tech compare to the current qm
image

## Breaking changes

**Changelog**

🆑 
- tweak: Recolored cargo sprites

### CODE REVIEW

**Comment by UbaserB** [comment]
I enjoy this much more

**Comment by beck-thompson** [comment]
Yeah I agree these are sweet sprites. I agree the old ones didn't stand out enough from engi and these look better

**Comment by Hanzdegloker** [comment]
how does this recoloured softcap compare to the QM softcap, they appear to be very close in colour now

**Comment by InfinityPandaRed** [comment]
> how does this recoloured softcap compare to the QM softcap, they appear to be very close in colour now

unfortunately this does make the cap more similar to qms cap but i think in totality qm still stands out enough to be easily distinguishable

**Comment by EmoGarbage404** [comment]
> > how does this recoloured softcap compare to the QM softcap, they appear to be very close in colour now
> 
> unfortunately this does make the cap more similar to qms cap but i think in totality qm still stands out enough to be easily distinguishable

Could you add side-by-side comparisons of the QM and the new cargo tech sprites?

**Comment by InfinityPandaRed** [comment]
> > > how does this recoloured softcap compare to the QM softcap, they appear to be very close in colour now
> > 
> > 
> > unfortunately this does make the cap more similar to qms cap but i think in totality qm still stands out enough to be easily distinguishable
> 
> Could you add side-by-side comparisons of the QM and the new cargo tech sprite
added new image

**Comment by InfinityPandaRed** [comment]
> > > how does this recoloured softcap compare to the QM softcap, they appear to be very close in colour now
> > 
> > 
> > unfortunately this does make the cap more similar to qms cap but i think in totality qm still stands out enough to be easily distinguishable
> 
> Could you add side-by-side comparisons of the QM and the new cargo tech sprites?

added new image showing comparison

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
The visual design of the Cargo Tech is far too close to the QM. In many situations, the two roles are virtually indistinguishable by appearance. The two need to look unquestionably distinct side-by-side.

The color is nice but it needs to be done in a way where it isn't conflicting with the visual style of the QM.

**Pull request closed without merging**
