### PR TITLE
Make APC UI work correctly with multiple users

### LINKED ISSUE #15563: APC access is toggled whenever the UI is opened
Looks like this PR https://github.com/space-wizards/space-station-14/pull/14258 does some cursed things. If person A opens the APC UI and then person B opens it it only considers person B's access which should not be handled like this. Ideally the access is only shown visually on the client and all the server does is validate the input.

### LINKED ISSUE #32312: If the AI has an APC UI open, nobody else can toggle the APC on
## Description

Saw a round where the AI was holding people hostage in a room by bolting all the doors and then toggling the APC off while keeping the UI open so that they couldn't turn on power to unbolt the doors

**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by eoineoineoin**
## About the PR

Made APC user interface work correctly with multiple users.
Fixes #15563. Fixes #32312. Obsoletes #32356.

## Technical details

ApcComponent previously stored a 'HasAccess' on the component, updating it whenever a user opened the APC UI and sending that flag in the state to all users. This was per-user state being stored globally.

Now, no longer stores that state and instead sends a message to each user of the UI individually to inform them if they have access.

## Media

https://github.com/user-attachments/assets/16f1b291-4fb3-4127-9868-27527383541f

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by hyphenationc** [comment]
Well, at least now AI hostage situations will probably get fixed.

**Comment by deltanedas** [comment]
you can use use IsAllowed in the ui as well to properly predict access

**Comment by eoineoineoin** [comment]
> you can use use IsAllowed in the ui as well to properly predict access

You mean put a [Dependency] on AccessReaderSystem in the APC BoundUserInterface? Interesting, didn't realize that was allowed. Will try that out tomorrow.

**Comment by eoineoineoin** [comment]
> > you can use use IsAllowed in the ui as well to properly predict access
> 
> You mean put a [Dependency] on AccessReaderSystem in the APC BoundUserInterface? Interesting, didn't realize that was allowed. Will try that out tomorrow.

Turns out it _isn't_ allowed, as it hits an UnregisteredDependencyException when constructing the BUI. It can be retrieved via the entity manager, though.

**Comment by metalgearsloth** [comment]
System dependencies only work on other systems due to lifetime.

**Comment by deltanedas** [comment]
you can use EntityManager.System to get the system

**Comment by lzk228** [comment]
you missed cl for this pr

**Comment by scrivoy** [comment]
hi, nice PR!
could that code also be used for looking at the power, solar, atmos or other consoles like crew monitor or something with multiple users? for me as an almost all time engineer it would be really helpful to have a look at the power with more people.
cheers!

**Comment by eoineoineoin** [comment]
> you missed cl for this pr

Didn't think it was worth it. Players won't notice a difference - you can't tell that someone else has the UI open, so you had to try to open it anyway. Now, it'll JustWork™ whenever they open the UI.

> hi, nice PR! could that code also be used for looking at the power, solar, atmos or other consoles like crew monitor or something with multiple users? for me as an almost all time engineer it would be really helpful to have a look at the power with more people. cheers!

Took a quick look at the atmospheric alerts computer and that has the same fundamental problem in that it stores per-user state in a shared component. The code in this PR isn't really reusable - handling multiple users will differ depending on exactly what the UI wants to do. If you want to log a bug, I (or maybe somebody else) will get to it eventually.

**Pull request merged**
