### PR TITLE
Spawn Gear Overrides

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Job spawn gear can now be modified by the species prototype (or any other prototype, if someone adds the necessary datafield there and reads it in StationSpawningSystem)

## How it works

Species prototypes (can) now have a spawngearOverride datafield. It's not mandatory so all existing prototypes will still work. Any number of SpawnGearOverridePrototypes can be added to it. These consist of a value that determines what type of operation will be used on the starting gear, and a gear template using the StartingGearPrototype format.

image

There are (currently) three options for overrideType:
Add: Entries specified in GearTemplate will check if their target slot is empty, and be added only if they don't overwrite existing starting gear.
Force: Entries specified in GearTemplate will be added to their target slots, overwriting existing items.
Remove: If an item, any item, is specified in a slot on GearTemplate then ANY item in the target slot will be deleted. I don't know why anyone would need this, but it exists now.

(Note that just like on StartingGearPrototype, the Duffelbag, Satchel and Jumpskirt entries have separate fields outside of `equipment`, so these are entered slightly differently, if anyone ever wants to override those based on species)

An override template can include a list of Roles that it will be applied to. If this is omitted from the template then it will apply to every member of the species.

Multiple templates can be applied one after the other, so for example you can:
Force a Captain's Gas Mask on Vox Captains, then
Force a Security Gas Mask on Vox Security Officers, then
Add a Breathing Mask to Every Vox, then
Force a Surgical Mask on Vox Clowns (so they die)

After the overrides finish, the modified startingGear list is handed to SharedStationSpawningSystem as before to spawn the items.

## Why / Balance
For a very long time we have been talking about species specific spawn rules, such as for giving Slimepeople emergency nitrogen. This change doesn't actually do that, for overriding the contents of containers, see #24684. However, since that system was not intended for adding equipment to empty slots, or easily overwriting _anything_ in a slot with your item of choice, I think we need both of these tools

### CODE REVIEW

**Comment by Errant-4** [comment]
Local maintainer says draft, pushes active. Moren news at 11

**Comment by lzk228** [comment]
YEEESSSS

btw, would it work for slimepeople and their emergency tank? would it work nice with department emergency boxes?

**Comment by Errant-4** [comment]
I'm leaving the override prototype on vox but setting them disabled as they were, if that's okay?

**Comment by Errant-4** [comment]
Role-specific overrides are now supported

**Comment by Errant-4** [comment]
Parking this while I wait for/observe #17517 as that would be a better place to integrate this functionality and when that pr is done it might be able to do all this already

**Pull request closed without merging**
