### PR TITLE
Add test for containers with nonexistant items

### PR DESCRIPTION
**Pull request by ShadowCommander**
## About the PR 
Adds a test to check that containers work when containing items that do not exist on the client.

Requires space-wizards/RobustToolbox#1892

### CODE REVIEW

**Comment by mirrorcult** [comment]
can this be a robust integration test?

**Comment by ShadowCommander** [comment]
Maybe. I couldn't find how to do server client stuff in Robust.IntegrationTests. They're all server only stuff.

**Comment by metalgearsloth** [comment]
They should just work as client but I haven't tried. They were only fixed very recently by Vera so the only person that's ever used them is me.

**Comment by Zumorica** [comment]
> I couldn't find how to do server client stuff in Robust.IntegrationTests. They're all server only stuff.

Check `EngineIntegrationTest_Test`

**Comment by ShadowCommander** [comment]
Moved to RobustIntegrationTest space-wizards/RobustToolbox#1892

**Pull request closed without merging**
