### PR TITLE
Open Books

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

image
image
image

Adds books that can be written in.

## Why / Balance

For decor, for guestbooks, for a little pizazz. They add a lot of life to a library which looks a little weird with only the existing closed book sprite. Otherwise, just a resprite of paper.

## Technical details

They're parented from paper so they're fairly similar, can be eaten, burned, etc. I did have to edit the PaperSystem and PaperComponent to add an IsStampable datafield, because god I am not making 50 stamp sprites. Someone else can do that if they want. For now, books are unstampable.

The colors are as follows:

image

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: Added decorative books that can also be written in.

### CODE REVIEW

**Comment by lzk228** [comment]
weird

**Comment by rosieposieeee** [comment]
> weird

why :(

**Comment by Aisu9** [comment]
personally love how they look

**Comment by Beridot** [comment]
One step closer to better books™

**Comment by TheShuEd** [comment]
Yes, we need regular books to open when someone reads their contents. The way cigarette cases or toolboxes are made.

**Comment by rosieposieeee** [comment]
> Wouldn't it be better for regular books to be openable rather than adding a plethora of new prototypes?

these are basically just reskinned paper. i could make regular books open this way (though i'd have to make some more custom sprites to account for the colors), but these would still be separate objects. i can look into trying it though!

**Comment by rosieposieeee** [comment]
yeah i can't figure out how to get existing books to close like cigar cases or anything. that stuff seems to rely on them being storages. i'd have to make my own visualsystem and i have tried and failed to do that already so i'm just gonna leave that open to someone else if they want to do it.

**Comment by UbaserB** [comment]
> i'd have to make my own visualsystem and i have tried and failed to do that already so i'm just gonna leave that open to someone else if they want to do it.

fair, just post an issue afterwards asking someone to implement it once this gets merged; it’s what i do anyway.

**Comment by TheShuEd** [comment]
you definitely have to make the color of the book through a layer with a random color, as is done for example with a screwdriver.  making a dozen sprites of different colors is bad

**Pull request closed without merging**
