### PR TITLE
Adds a meteor gun and rod gun for admeme use

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
So I've often felt we should be able to fire meteors at specific parts of the station for events etc, and increasingly now to get rid of "bugs" on the "windscreen" of the shuttle.

I wanted to make one for the null rod and a micro meteor pistol for hitting individuals but kept getting errors and couldn't find the null rod so here it is.
**Screenshots**

Content Client_9ZSBKDZhey

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
it is possible to make a null rod gun, I've done it with VV before

**Comment by Peptide90** [comment]
> it is possible to make a null rod gun, I've done it with VV before

Couldn't find the prototype in the files and couldn't really be fussed to look too hard haha. If it's requested though I can look again. Little meteor gun was giving unknown prototype which was stupid.

**Comment by Peptide90** [comment]
Gains component containercontainer...what? Surely the ammo provider comp doesn't inherit.

**Comment by mirrorcult** [comment]
> > it is possible to make a null rod gun, I've done it with VV before
> 
> Couldn't find the prototype in the files and couldn't really be fussed to look too hard haha. If it's requested though I can look again. Little meteor gun was giving unknown prototype which was stupid.

its called the immovable rod. it'd be nice to have one as well

**Comment by mirrorcult** [comment]
> Gains component containercontainer...what? Surely the ammo provider comp doesn't inherit.

yaml needs to specify the container, check how other guns do it

**Comment by Peptide90** [comment]
> > Gains component containercontainer...what? Surely the ammo provider comp doesn't inherit.
> 
> yaml needs to specify the container, check how other guns do it

I'm curious since I just copied the launchers above, how they don't error. Oh well, let's see if tests pass and I'll see if I can find the immovable rod (it's not a projectile apparently).

**Comment by Peptide90** [comment]
Content Client_QHzo0I81eP
Eh I wanted to make it a pistol to bring back my gmod memories. Guess not. Still failing but if I add containercontainer to it it doesn't work. Will check it out another time, although as mentioned, the regular launcher doesn't have it. shrug.

**Pull request merged**
