### PR TITLE
Pets cleanup

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
Clean up pets and animals yml

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
conflicts

**Comment by ZeroDayDaemon** [comment]
will fix rq

**Comment by ZeroDayDaemon** [comment]
bruh codeowners moment

**Comment by ZeroDayDaemon** [comment]
I think ive fucked this so im just gonna close it

**Pull request closed without merging**
