### PR TITLE
Fix lemon's juice

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 

**Screenshots**

**Changelog**

:cl:
- fix: Lemons now have lemon juice instead of lime juice.

### CODE REVIEW

**Review by Mervill — APPROVED** [review]
🍋

**Comment by Kromabae** [comment]
but but but
how will i make lime cakes now?

**Comment by EmoGarbage404** [comment]
> but but but how will i make lime cakes now?

probably get some limes.

**Comment by Mervill** [comment]
we dont ... have any ... limes?

**Comment by EmoGarbage404** [comment]
on a less shitpost-y note, isn't lime juice available in one of the bar drink dispensers? i believe it's in the soda machine.

**Comment by asperger-sind** [comment]
> on a less shitpost-y note, isn't lime juice available in one of the bar drink dispensers? i believe it's in the soda machine.

It is infact available there.

**Comment by Mervill** [comment]
Looks like it's in both of them

**Comment by EmoGarbage404** [comment]
when is someone gonna do a bartending 1984 and force bartenders to source organic juice from botany /s

**Comment by CormosLemming** [comment]
Thanks, was actually talking to someone about this in discord about half an hour before you added this.

**Comment by EmoGarbage404** [comment]
> Thanks, was actually talking to someone about this in discord about half an hour before you added this.

I see all

**Comment by Kromabae** [comment]
> when is someone gonna do a bartending 1984 and force bartenders to source organic juice from botany /s

wyci? :D
also a lot of the juices cant even be planted right now....
but this is also one of those things then, why plant sugar cane when you can just get infinite sugar from chemist or bartender

**Pull request merged**
