### PR TITLE
Add the wieldable\unwieldable action instead UseInHandEvent()

### PR DESCRIPTION
**Pull request by Arteben**
## About the PR
Instead of using "Z" to toggle between single-handed and two-handed weapon modes, it now uses the new action "One-hand/two-hand wielding"

## Why/Balance

Many weapons use actions on "Z" for bolt closure or magazine discharge. These actions conflict with switching between wieldable/unwieldable modes, hindering the use of this feature. Additionally, I plan to further add autowieldable, which requires resolving conflicts with the "Z" key.

## Media

image

https://github.com/space-wizards/space-station-14/assets/2144635/240bbaed-ea96-4e1c-ab2d-0c3624dccd82

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added new action for wieldable\unwieldable weapon

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i feel like adding an action is a really inelegant solution to wielding and bolting conflicting when you could instead simply only bolt the gun if its already wielded. It's a decent amount of redundancy and UI bloat for something that already has a perfectly functional interaction for 90% of instances.

**Comment by metalgearsloth** [comment]
I'm a fan of the "just mark the event as handled" party.

**Comment by Arteben** [comment]
Alright, I understand this solution doesn't suitable

**Comment by Arteben** [comment]
Alright, I understand this solution doesn't suitable

**Pull request closed without merging**
