### PR TITLE
Added a new cryogenics chemical - Doxarubixadone!

### PR DESCRIPTION
**Pull request by Dynexust**
## About the PR

Seeing as Slimes have become more widespread on the Nanotrasen brand stations, Nanotrasen has decided to purchase the recipe for Doxarubixadone to treat genetical damages done by said Slimes.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dynexust
- add: Interdyne Pharmaceutics has pushed a new chemical on the market, Doxarubixadone, which cryogenically heals cellular damage.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
1. Slimes deal cellular damage?
2. I dont think cellular damage should be so easily healable.

**Comment by Dynexust** [comment]
> 

Slimes do as a matter of fact deal cellular damage! However, as a matter of fact I do not consider this easily curable given that a cryopod is necessary for healing it as an alternative to Phalanximine, which already cures cellular damage with a small drawback of radiation. I felt as if the cryopods could use some flavour besides being solely used for Cryoxadone.

**Comment by EmoGarbage404** [comment]
I feel like this is just sidestepping that a random ai mob does cellular damage?

**Comment by Dynexust** [comment]
> I feel like this is just sidestepping that a random ai mob does cellular damage?

Was that not intended?

**Comment by Interrobang01** [comment]
Simply creating this chem is harder than both creating and applying phanalaxamine, which, for one thing, doesn't need a plasma catalyst. That's not even including the cryo pod.

If phanalaxamine is balanced, this chem is balanced.

**Comment by Emisse** [comment]
cryo chems are based, sounds good to me

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
actually now that i think about it, we could really convert a lot of problematic chems to cryo triggers

**Comment by Aisu9** [comment]
we already have phalanx that turn 2 cellular into 2 rad damage

**Comment by Just-a-Unity-Dev** [comment]
> we already have phalanx that turn 2 cellular into 2 rad damage

ok but this requires you to put them into cryo

**Comment by Aisu9** [comment]
> > we already have phalanx that turn 2 cellular into 2 rad damage
> 
> ok but this requires you to put them into cryo

yeah... what prevent more from making 10u phalanx/Hyro pills? this will treat the cellular damage at the same rate, no tedious setup, no cryo needed, no "waste" of cryoxadone

**Pull request merged**
