### PR TITLE
more expedition changes

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
address some of liltens reviews
time for you to redo video :)))))

added temperature mod for certain biomes

made difficulty 2^n -1 so at extreme you get 15 not 7, will make extreme heat or cold common (and make rolling volatile atmosphere actually possible now, oops)

rewrote all the biome specific mods to use new GetBiomeMod and IBiomeSpecificMod much better

added biomass reclaimer as reward yes

lava brig also has a few more goodies since experiment has a lot of useful machines and stuff:
- a kammerer is in the firing range
- clusterbang where the secway used to be, along with a remote to open the shutters
- added stimkit back
- moved gatfruit from reward back to the showers, didnt make much sense as a reward from nanotrasen

500-10000 spacebucks can show up as rewards for minor to extreme missions

removed some funny rewards

**Media**
temperatures, rewards:

welder on volatile atmos doesnt kill server sadly:

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Hazardous and Extreme expeditions can have more dangerous modifiers, of which temperature has been added.
- tweak: Hazardous and Extreme expeditions give 4 and 5 rewards respectively.

### CODE REVIEW

**Comment by Anzarot121** [comment]
Is it possible that with the modification of the high temperature and the oxygen-plasma atmosphere, the spontaneous synthesis of tritium will begin? If not, then you need to increase the maximum possible temperature.

**Comment by deltanedas** [comment]
- reactions dont happen with planet atmos so not possible sadly
21% oxygen wont make trit :trollface:

**Comment by Anzarot121** [comment]
> * реакции не происходят с атмосферой планеты, так что, к сожалению, это невозможно
Not funny (

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Bump the crates to say 8 each to reflect the loot reduction and also dupes should say like "x2" next to them like the old loot did.

**Comment by deltanedas** [comment]
up to 8 reward lines might be too much for the ui tho

**Comment by metalgearsloth** [comment]
I'll have a think on it

**Comment by deltanedas** [comment]
for now, grouped rewards like loot used to be

**Comment by deltanedas** [comment]
@metalgearsloth is there anything else i should do or is it ok to merge, a lot of changes waiting

**Comment by metalgearsloth** [comment]
> @metalgearsloth is there anything else i should do or is it ok to merge, a lot of changes waiting

been busy playin wow will check it soonTM.

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
