### PR TITLE
combine licence files for StationEvents audio

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
I don't think there was any particular reason these were in two separate files, just legacy clutter

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by Errant-4** [comment]
Ah. I see. I did not realise we were playing the "do not volunteer yourself to go URL hunting" game

**Comment by Errant-4** [comment]
The commit hash was changed because, it turns out, the one we had on file was for an unrelated change

**Comment by slarticodefast** [comment]
Yep, I checked both hashes and the new one seems to be the correct one.

**Comment by slarticodefast** [comment]
Damn, Ed sniped my merge while I was typing my message.

**Pull request merged**
