### PR TITLE
Marathon Station: Added air alarms to CMO, Surgery, Security Checkpoint

### LINKED ISSUE #33211: Marathon air alarm issues.
**Screenshots**
Marathon
Security checkpoint lacks any kind of air alarm.
Marathon2
CMO rooms and western surgery likewise lack any air alarms.

### PR DESCRIPTION
**Pull request by scrivoy**
## About the PR

This PR adds air alarms to the following locations:
- CMO office (including an extra air sensor in the bedroom)
- Hallway in front of the CMO office.
- Surgery next to CMO Office
- Security checkpoint (Arrivals/EVAC)

## Why / Balance

These areas lacked air alarms, which could lead to delayed responses to atmospheric issues. This change improves safety and functionality in critical locations.

Fixes #33211

## Technical details

Added air alarms in the specified areas and linked them to the corresponding scrubbers and vents.
The CMO's office received a separate air sensor in the bedroom, placed below the table.

## Media

Checkpoint

CMO

Hallway

Surgery 1

Surgery 2

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by scrivoy** [comment]
The Air Alarm position in the surgery rooms is not perfectly accessible, but there is no room on the other walls.

**Comment by scrivoy** [comment]
okay, check failed, i'll have another look at the data.

**Comment by thebadman4662** [comment]
> The Air Alarm position in the surgery rooms is not perfectly accessible, but there is no room on the other walls.

One could be put near console, same with other if you moved fire alarm to disposal bin I guess? Otherwise people have to break table or their legs to access air alarm. 🤣

**Comment by scrivoy** [comment]
> One could be put near console, same with other if you moved fire alarm to disposal bin I guess?

Yes, you're right, I hadn't thought of that. Thanks for the reminder! I will change that.

**Comment by Emisse** [comment]
remove the invalid configurator from your map file

**Comment by scrivoy** [comment]
> remove the invalid configurator from your map file

ah okay, i was wondering where that came from, i'm on it.

**Comment by scrivoy** [comment]
ok i have updated the position of the air alarm (new pictures in the PR overview).
i thought it would be nicer if the fire switch stayed in the middle of the hallway, so i moved the defi one tile up and put the waste bin on the other side.
To move the "yellow box decal" I had to remove everything on that tile, now it looks different, the outline of the "blue corner decal" looks lighter than the others but i used the "Medical Color" from the palette.
any idea how i can recreate this?

**Comment by Emisse** [comment]
off the top of my head looks like its a similar decal but not the same one

**Comment by scrivoy** [comment]
> off the top of my head looks like its a similar decal but not the same one

I found it. I searched the map .yml for my changes and saw what was deleted.
So to archive this colour you put down the BrickTileWhiteCornerNw without a custom colour, so in this case its just white (#FFFFFFFF or 255/255/255). and then you put down the same decal but with the custom department colour medical (#52B4E996 or 82/180/233).

In the code it looks like this
grafik

I'll finish my work and push the changes.

**Comment by scrivoy** [comment]
I forgot to tell you, I finished my work on this PR.

**Pull request merged**
