### PR TITLE
Edit labels behaviour

### PR DESCRIPTION
**Pull request by Fahasor**
## About the PR

Now labels can be deleted if they added to entity by prototype field
Now labels text don't shown in name of entity (but they still shown in description, it already coded by someone)
Labels don't shown in name field, but they shown in vendomates.
Also some small fixes like adding suffix to jugs and making label text lowercase.
Changes of UI can have some problems in place of calculating longest entry.

**Media**

https://github.com/space-wizards/space-station-14/assets/70820551/73ab51dc-ecec-4dea-926b-347472b08fbd

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Special medical check of Nanotrasen workers find out that they all have small eye disease. Now labels don't shown in name of objects.
- fix: Labels now can be deleted from chemVend jugs.

### CODE REVIEW

**Comment by Fahasor** [comment]
Forget to edit comments, i will reopen PR

**Comment by juliangiebel** [comment]
You can just push to your changes. The open pull request will automatically be updated. You don't need to close it.
Also please change the change log
https://docs.spacestation14.io/en/getting-started/pr-guideline#changelog

**Comment by Fahasor** [comment]
> You can just push to your changes. The open pull request will automatically be updated, You don't need to close it.
I close it because i forgot push changes, but i need push with --force flag. I was readed, that i must avoid force pushing, that's why i closed it. In this case i can just force push?

**Comment by juliangiebel** [comment]
Just merge master before pushing
Don't force push! wth
srsly

**Comment by juliangiebel** [comment]
https://docs.spacestation14.io/en/getting-started/git#h-4-branching-commits

**Pull request closed without merging**
