### PR TITLE
Swordcane able to shoot fireballs when Cane is wielded 

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

Renamed Sword Cane to Wizard's Cane

I made the Swordcane able to shoot fireballs when wielded in Cane Form, these fireballs do 20 Heat and can ignite targets (A bit over 2 heat damage total). Cane Fireballs have a purely cosmetic explosion equal to a snap pop. Cane Sword Price has been adjusted to 8TC. I merged white_cane.yml into cane.yml since they are both canes and there's not really a reason for it to be a seperate file. The Cane can now fit on the Belt or Exosuit slot.
## Why / Balance

The Sword Cane was overpriced and a worse choice to the E-Pen or Cybersun Pen.

It was discussed here https://discord.com/channels/310555209753690112/1234653039894204487
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Swordcane can shoot fireballs when wielded in Cane form
- tweak: Renamed Sword Cane to Wizard's Cane

### CODE REVIEW

**Comment by FungiFellow** [comment]
Unfinished, meant to merge to my own master

**Comment by Plykiya** [comment]
can we get a video on what this looks like in action?

**Comment by FungiFellow** [comment]
> can we get a video on what this looks like in action?

Sure, just editing it a bit more to hide the fire rate and selected mode

**Comment by FungiFellow** [comment]
> ... hide the fire rate and selected mode

There does not seem to be a component for this, I could make the Cane unexaminable though. The decription doesnt have all too much in it anyways

**Comment by Hmeister-real** [comment]
> > ... hide the fire rate and selected mode
> 
> There does not seem to be a component for this, I could make the Cane unexaminable though. The decription doesn't have all too much in it anyways

has to have a description, it's a stealth item

**Comment by TurboTrackerss14** [comment]
This feels way to far of a swing in the other direction to go from "its over priced" to "lets give it a 20 heat fireball shot" 
Also maybe don't make it a "wizard" item when wizards are likely to become an antag in the future.
its a cane not a wand..

**Comment by FungiFellow** [comment]
> This feels way to far of a swing in the other direction to go from "its over priced" to "lets give it a 20 heat fireball shot" 

I upped the price accordingly, it's currently on par with a PKA+Knife. It's also a boring weapon that could use greater flavor than mid stealth item

**Comment by EmoGarbage404** [comment]
This doesnt really match the theme or other syndicate items. This is by all intents and purposes a wizard item  and i dont really think it fits in the uplink.

Furthermore, don't use web editting for completing large PRs. It's explicitly against the contributor guidelines the lack of media or verification of being tested is a concern.

**Comment by FungiFellow** [comment]
> the lack of media or verification of being tested is a concern.

That is why I had it as draft. I had tested it previously and was going to add Screenshots/Video later before requesting review

**Pull request closed without merging**
