### PR TITLE
Arachnid RE-REWORK

### PR DESCRIPTION
**Pull request by PixelTheKermit**
# ARACHNIDS V3 WOOOOOO

## About the PR

Reworks arachnids, again.
Also adds a bit more web structures and makes silk edible by moths.

### Why / Details
---

## Arachnids
First off, no more 4 hands.
Extra hands was apparently really strong, and any drastic nerfs to balance it out would make arachnids not fun to play as. It also made them a combat orientated race which is a bit icky, and also made them unfun to play against aswell. For this they are removed, however they might make a return after woundmed comes out (although don't bet on it).

Anyways here's what Arachnids V3 have:

- Sericulture: Arachnids can still make silk and create structures/crafts out of them. No difference here.
- Slow metabolism: Hunger and metabolism are still slower than your average human.
- O2: Arachnids will still take 1.5 asphyxiation and recover .5 asphyx. No changes there.

And that's it! If you were expecting a bit more you were mistaken.
Maybe in the future there could be an extra negative but right now this feels balanced enough.

## Web crafts
A few more web crafts were added, These include:
- Web Crates
- Web Chair
- Web Bed
- Web Jumpsuit
- Web Jumpskirt
- Web Winter Coat
- Cloth

<details>
<summary>Media</summary>
<br>

### Structures and Clothing
image 

### Cloth
image

### Winter coat
image
image
image

</details>

## Silk
Now an edible resource by moths, tastes like cobwebs.

<details>
<summary>Media</summary>
<br>

image

</details>

## Misc
Arachnids now have new creampie sprites!

<details>
<summary>Media</summary>
<br>

image

</details>

---

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

:cl: PixelTK
- remove: Arachnids no longer have two additional hands as well as their damage modifiers.
- add: Arachnids can now craft more structures, unique clothes, and cloth using their webs.
- tweak: Arachnids now get more hungry when spinning webs.
- tweak: Moths can now eat silk.

### CODE REVIEW

**Comment by PixelTheKermit** [comment]
Ok it's probably done now unless I change my mind again

**Comment by PixelTheKermit** [comment]
Okay fuck, I guess this is just part two (2) of the rework

**Comment by PixelTheKermit** [comment]
Well fuck I guess I'm drafting this again!

**Comment by PixelTheKermit** [comment]
Ready for the 50 billionth time.

**Comment by PixelTheKermit** [comment]
I guess this is going to be an arachnid re-rework? Fun.

**Comment by PixelTheKermit** [comment]
Flip a coin and decide if that was the final time I drafted the PR.

**Comment by PixelTheKermit** [comment]
OKAY FUCK WE DRAFTING THIS BITCH AGAIN

**Comment by PixelTheKermit** [comment]
Feel like I've done enough. If I want to add more stuff I will do so in the future:tm:

**Comment by PixelTheKermit** [comment]
Merge conflicts should be resolved hopefully.

**Review by LankLTE — APPROVED** [review]
webber don't starve

**Pull request merged**
