### PR TITLE
Fix the addrole command

### PR DESCRIPTION
**Pull request by wrexbe**
## About the PR 

Fixed the addrole command, and added another check to prevent adding an existing role.

### CODE REVIEW

**Comment by Zumorica** [comment]
> * fix: fix the addrole command

As a quick note, the changelog is exclusively for player-facing changes, not admin or dev facing ones.

**Comment by wrexbe** [comment]
@Zumorica Okay, I removed the change log

**Comment by wrexbe** [comment]
@Zumorica I need to fix it differently after this huh? https://github.com/space-wizards/RobustToolbox/pull/2264

**Comment by Zumorica** [comment]
> @Zumorica I need to fix it differently after this huh? [space-wizards/RobustToolbox#2264](https://github.com/space-wizards/RobustToolbox/pull/2264)

Given there hasn't been a submodule update yet, no need to fix your PR

**Review by DrSmugleaf — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
