### PR TITLE
Miscellaneous syndicate bomb tweaks & fixes

### LINKED ISSUE #20067: Syndicate bomb missing name and description in uplink.
## Description
New Syndicate bomb is missing name and description in uplink. from this PR: #15380

**Reproduction**
Just open uplink and have a look.

**Screenshots**
image

**Additional context**
Potentially related to this post from DrSmugleaf: https://discord.com/channels/310555209753690112/928056457117696020/1150898771278962808

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Changes a whole bunch of misc. stuff about the syndicate bomb:

- Training bombs now have their full wireset (they do not mirror the syndicate bomb's wires anymore, if you've seen this PR before)
- Timer has been nerfed to 120s
- The bomb now beeps with the same sound it has in /tg/
- Fixes the fucked up uplink description and name

Fixes #20067

## Why / Balance
Defusable wires: It's a training bomb and should have the full wireset instead of a trimmed-down one. This didn't make a lot of sense.

Timer nerf: Gives people a little more leniency to defuse the bomb, which is important if the training bomb isn't going to mirror the real deal's wires anymore. Also technically compensates for pixel movement and byond lag and all that jazz (though obviously 30 extra seconds is overkill in that regard.)

Timer sound: It being the same as C4 was both confusing and lame. Not much to say here.

Uplink description was extremely barebones so that also probably speaks for itself.

## Med
[Content.Client_3CwSfyUWBR.webm](https://github.com/space-wizards/space-station-14/assets/78941145/ee228e6c-4ead-4302-992f-fc2c11726a07)

As per-usual the audio is hilariously out-of-sync with the video, but the audio is the only thing that matters here so it should be fine,

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The syndicate bomb now has a unique beeping sound.
- tweak: The training bomb now has the same amount of wires as the real deal.
- tweak: The syndicate bomb's minimum timer setting is now 120 seconds (30 seconds longer then before.)
- fix: Fixed the syndicate bomb's name & description in the uplink showing up incorrectly.

### CODE REVIEW

**Comment by LankLTE** [comment]
There was already support for making the wires the same??? Bro what was rain on

Might end up making syndicate bomb near-useless if someone defuses the training bomb since all of sec will suddenly know what wire to cut, but apparently it works fine in 13 so whatever

**Comment by LankLTE** [comment]
Also are training bombs even obtainable atm

**Comment by Flareguy** [comment]
> > especially considering security may have forgotten about the bomb's correct wire
> 
> Sec must have an astronomical skill issue for literally all of them to forget the right wire, because I guarantee you the second the wire is found that's going on the sec radio and the second a bomb is found they're saying "remember it's X wire" on the sec radio

You might think that, but sec will likely have much more on their mind later on and probably have forgotten about the insignifigcant wire. And time is limited so it's not like you can just scroll back chat either.

> Also are training bombs even obtainable atm
No, they're supposed to be mapped. This isn't something I can fix myself but it should be pretty trivial to do in theory (I'm pretty sure some SS13 maps just shove the bomb off into the firing range.)

**Comment by HoidC** [comment]
> > > especially considering security may have forgotten about the bomb's correct wire
> > 
> > 
> > Sec must have an astronomical skill issue for literally all of them to forget the right wire, because I guarantee you the second the wire is found that's going on the sec radio and the second a bomb is found they're saying "remember it's X wire" on the sec radio
> 
> You might think that, but sec will likely have much more on their mind later on and probably have forgotten about the insignifigcant wire. And time is limited so it's not like you can just scroll back chat either.
> 
> > Also are training bombs even obtainable atm
> 
> No, they're supposed to be mapped. This isn't something I can fix myself but it should be pretty trivial to do in theory (I'm pretty sure some SS13 maps just shove the bomb off into the firing range.)

you forget that one can record in an external program the wire colour (and they will, you know what people are like)

**Comment by deltanedas** [comment]
> Training bombs now have their full wireset and mirror the wires of the syndicate bomb. If security memorizes the wire layout, they will be able to defuse the bomb without any hassle.

yes this will get metad like the times where tiders say the bolt/power wires on common
or on nyano tiders saying the acc wire before it got fully randomized

**Comment by LankLTE** [comment]
Anyways memes about it being useless aside (because it does work like this in 13), can you add “canCreateVacuum: false” to the training bomb because I thought it already had it and really should

**Comment by LankLTE** [comment]
Nevermind I’ll PR that myself later

**Comment by CrigCrag** [comment]
training bombs having the same wires will definitely be powergamed

**Comment by deltanedas** [comment]
yeah then if a syndicate bomb has more than 5 seconds its wasted tc since everyone will find out the live wire roundstart

**Comment by Flareguy** [comment]
Okay, bomb wire mirroring has been removed but the timer has been changed to 120s to compensate.
I'll try bomb wire mirroring later if the bomb is still regarded as OP, but for now this should do.

**Comment by LankLTE** [comment]
Fix changelog dummy (and tests if that’s related)

**Comment by Flareguy** [comment]
Test fails look unrelated, CL is now fixed.

**Pull request merged**
