### PR TITLE
baby proof the terminal

### LINKED ISSUE #28163: Arivals telecomms is vulnerable to shitters.
## Description

The AA Telecomms server is not locked, at all. 
**Reproduction**

Late join or load the arrivals map. The maints door in arrivals is unlocked. Smash the Telecoms server. get AA radio.
**Screenshots**

image

**Additional context**

Not a big issue, just worried about people being shitters and powergaming with AA radio.

### PR DESCRIPTION
**Pull request by IProduceWidgets**
fixes #28163

## About the PR

All entities on the terminal have god mode
All entities on the terminal cannot be deconstructed
All entities on the terminal cannot be deconstructed with a RCD
All entities on the terminal cannot be destructed
All entities on the terminal cannot be unanchored

The comms server cannot eject the keycards
APCs infinitely recharge

Cables have an uncuttable variant since the cable system has a snowflake construction method.

## Why / Balance

Make rules become mechanics 
The terminal is generally a "do not tamper" zone, and the wizden server rules are such that you might be banned for doing so. This makes it much less possible to break that rule.

## Technical details

Needs #32009 later to not be annoying, but this works for now.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: The terminal is more tamper proof.

### CODE REVIEW

**Review by keronshb — CHANGES_REQUESTED** [review]
Same comments from #33284
There's probably a better way to do this, plus desc is too memey.

**Comment by IProduceWidgets** [comment]
> Same comments from #33284 There's probably a better way to do this, plus desc is too memey.

Is the better way to do this in the room with us right now?

**Review by keronshb — CHANGES_REQUESTED** [review]
These two vending machines can be unanchored/destroyed (they're destroyed in the image. This is on the right side under the poker area.

image

chairs here are indestructable but can be unanchored
image

Same for these chairs
image

this vending machine can also be unanchored and destroyed
image

Also try to make the doors unhackable too. As an engineer i can bolt the ones leading out.

**Comment by IProduceWidgets** [comment]
Woops, thought I fixed the chairs.

I can fix the vending machines but they wont be random spawned any more. I suppose that's a fine compromise though.

**Comment by IProduceWidgets** [comment]
Feexed.
I think the arrivals PR is still gucci, it didnt have these kinda of chairs or spawner-vendors.

**Comment by IProduceWidgets** [comment]
Test eroneous

**Comment by IProduceWidgets** [comment]
Me when the tests Guh

**Review by Emisse — APPROVED** [review]

**Review by keronshb — APPROVED** [review]

**Review by VasilisThePikachu — APPROVED** [review]

**Review by Errant-4 — DISMISSED** [review]
Minibombs and holy hand grenade somehow still ruin the terminal

**Pull request merged**
