### PR TITLE
Salami Lid

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
the salami lid (the salami lid) aint gon fit (wont fit) so the salami lid aint gon fit (the salami lid (lid)) the salami lid aint gonna fit like that so the salami lid (the salami lid) and its the salami-
**Screenshots**

image

**Changelog**

:cl: Daemon
- add: Added the salami lid (won't fit)

### CODE REVIEW

**Comment by mirrorcult** [comment]
time to add bags of holding

**Comment by ZeroDayDaemon** [comment]
gromit mug next pr

**Comment by ZeroDayDaemon** [comment]
Need progress report major tag thx

**Comment by metalgearsloth** [comment]
> Need progress report major tag thx

PR ain't gon fit.

**Pull request merged**
