### PR TITLE
flora.yml cleanup

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

Cleaned up trees in flora.yml:
- Moved names from tree variants to parent entities.
- Moved parent entities closer to variant entities.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by beck-thompson** [comment]
Negative diff ymal beast 💪

**Review by slarticodefast — APPROVED** [review]
Looks good to me.
Thanks for the cleanup!

**Comment by TheShuEd** [comment]
wait wtf #33839 
we almost simultaneously decided to clean out that file

**Comment by Tunguso4ka** [comment]
> wait wtf #33839 we almost simultaneously decided to clean out that file

great minds think alike.

**Comment by slarticodefast** [comment]
I merged #33839 instead because that PR also makes trees use random sprites instead of having lots of hardcoded prototypes, so this PR is now redundant. Thank you for contributing anyways!

**Pull request closed without merging**
