### PR TITLE
law & order headset, spesslaw book

### PR DESCRIPTION
**Pull request by randy10122**
## About the PR

silly little adjustments to lawyer for RP purposes - a copy of spesslaw in your pocket (text essentially copied from the wiki with small clarity and formatting adjustments. the book is as dense as it should be) and a fresh new headset that has the service key

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image

**Changelog**

:cl: randy
- add: the law & order headset and space law written in a book to add more flavour to lawyering

### CODE REVIEW

**Comment by moonheart08** [comment]
The space law book should likely be a guidebook entry instead and the book simply a shortcut into the guidebook.

**Comment by randy10122** [comment]
> The space law book should likely be a guidebook entry instead and the book simply a shortcut into the guidebook.

methinks having a physical book is better for roleplay

**Comment by Emisse** [comment]
theres good precedent for space law book i think its also a useful item in game since guidebook can get a bit bloated

**Comment by Emisse** [comment]
both would be ideal tho add a guidebook entry

**Comment by randy10122** [comment]
> both would be ideal tho add a guidebook entry

should i just use the text frmo the book as it is in the guidebook

**Comment by moonheart08** [comment]
> > The space law book should likely be a guidebook entry instead and the book simply a shortcut into the guidebook.
> 
> methinks having a physical book is better for roleplay

You can keep the physical book, it should just open the guidebook to the space law page.

**Comment by randy10122** [comment]
> You can keep the physical book, it should just open the guidebook to the space law page. Don't dupe the text.

consider: i have no idea how i would go about doing that

**Comment by AJCM-git** [comment]
> > You can keep the physical book, it should just open the guidebook to the space law page. Don't dupe the text.
> 
> consider: i have no idea how i would go about doing that

There are many guidebook examples in the codebase that you can use as reference, if you dont think you can do it consider closing this for the time being

**Comment by AJCM-git** [comment]
@randy10122 you coming back to this?

**Comment by randy10122** [comment]
> @randy10122 you coming back to this?

probably not

**Pull request closed without merging**
