### PR TITLE
Add the Syndicate Instigator Shuttle

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Adds a shuttle that takes a spin at LoneOps by having a 3 man team, but providing them mostly random resources to work with via two surplus bundles. They're provided 4 rounds of explosive shuttle-grenades, 4 rounds of emp shuttle-grenades, then a few essentials for getting on the station including hardsuits and a couple cobras. They have 25 TC to share between them, which are in the possession of their team leader to encourage a hierarchy.
ship
ship2
role

A note / todo: They do not currently have the objective ui you may be familiar with from the nukeops mode or the loneops ghost role. This is something I have been back and forth on, as I think we should have some syndicate roles that can be placed on shuttles which don't have this specific intent. However, I am willing to concede that in this particular instance, its probably warranted. My suggested/intended solution to this will be to have two sets of these roles, one with the nuke objectives and one where they are more free-form, at least until we get an objectives rework and this issue can be handled in a more encompassing way. i.e. It should be possible to map something like a 'syndicate negotiator' shuttle without giving all the roles the nuke objective.

## Why / Balance

Adds more shuttle variety which is a good thing. Also provides a lot of replay value and encourages creativity by having a shuttle of this type which provides random resources.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- add: The Instigator, a 3 man syndicate shuttle.

### CODE REVIEW

**Comment by spanky-spanky** [comment]
IMO any antagonist with this level of potential firepower needs an explicit objective. Just showing up and killing everyone doesn’t lead to much fun especially if the round end condition is still the evac shuttle.

**Comment by Cojoke-dot** [comment]
Killer looking ship and looks super fun to play. My biggest issue is a mix of luck and the cannons. Blowing into the armory  at range with a couple blast nades feels kinda crazy... Top that with the chance to roll a Holo from the crates. 25 tc diverted to missing noslip, suits, and agent id and now you just have nukies with a friendship and holopara.

**Comment by Golinth** [comment]
> IMO any antagonist with this level of potential firepower needs an explicit objective. Just showing up and killing everyone doesn’t lead to much fun especially if the round end condition is still the evac shuttle.

nuke the station, that is their objective.

**Comment by Kadeo64** [comment]
incredibly hot take but I don't think randomly spawning 3 nukies to murderbone is very fun or interesting for stationgoers during a normal round

**Comment by DrakonTLGND** [comment]
Ship looks dope, and in my opinion the 3 nukies should have the common nukie objective, it being a rare ghost role makes rounds more varied.

**Comment by IProduceWidgets** [comment]
> Killer looking ship and looks super fun to play. My biggest issue is a mix of luck and the cannons. Blowing into the armory at range with a couple blast nades feels kinda crazy... Top that with the chance to roll a Holo from the crates. 25 tc diverted to missing noslip, suits, and agent id and now you just have nukies with a friendship and holopara.

The cannons I would describe as *mostly* underwhelming. At base they only have 4 explosive rounds to fire (thought hey could get more by purchasing a chinalake or getting one from surplus). When I tested it, they mostly served to alert the station of their presence.

**Comment by spanky-spanky** [comment]
Might be more interesting if there was an extra condition, such as mechanically requiring them to announce themselves before FTL is available, or (perhaps outside the scope of this PR) having them aim to steal something or kidnap someone.

**Comment by IProduceWidgets** [comment]
> incredibly hot take but I don't think randomly spawning 3 nukies to murderbone is very fun or interesting for stationgoers during a normal round

No I think you have a point. To that point, they are pretty rare, and we could make them rarer. 

I do believe we should have some shuttles that are a more RP focused syndicate role. The syndicate evac pod does this in some ways, but I don't think we have yet found a way to walk the narrow tightrope of them being able to defend themselves, while not becoming antags in full.

**Comment by Kadeo64** [comment]
> No I think you have a point. To that point, they are pretty rare, and we could make them rarer.

Ideally I think it should be a 1/50 round chance. It's basically half a nukie team, even with random equipment that's still an oppressive force, especially with the shuttle guns


> I do believe we should have some shuttles that are a more RP focused syndicate role. The syndicate evac pod does this in some ways, but I don't think we have yet found a way to walk the narrow tightrope of them being able to defend themselves, while not becoming antags in full.

I think the easiest way to do this is the Python revolver. It shuts down any single opponent without an automatic weapon while being hard to use against a group

**Comment by GroggleG** [comment]
This would be great if Dynamic existed, sadly it doesnt.

**Comment by Everturning** [comment]
I don't like them having TC, kinda against the idea of them only having random gear

**Comment by KaiserMaus** [comment]
Two pairs of cat ears will definitely be in my random surplus!

**Comment by EthanQix** [comment]
Honestly it would be funnier if they were an infiltration team with a "capture [Head of Department] alive" objective or something. We already have several midround antags whose role is to destroy the station/crew in one way or another.

**Comment by YehatRebel** [comment]
I think having them as an infiltration team that was sent to capture a certain individual sounds fun. My spin on this would be to have something like a Security shuttle spawn in as well, with a Head of Department and two bodyguards, and make capturing that Head of Department alive the team's objective.

**Comment by Ilya246** [comment]
other idea to make this less broken: NT-owned shuttle sent to retrieve a specific person alive for a funny crime like for example tax evasion they did 15 years ago

**Comment by spanky-spanky** [comment]
> other idea to make this less broken: NT-owned shuttle sent to retrieve a specific person alive for a funny crime like for example tax evasion they did 15 years ago

> Honestly it would be funnier if they were an infiltration team with a "capture [Head of Department] alive" objective or something. We already have several midround antags whose role is to destroy the station/crew in one way or another.

> I think having them as an infiltration team that was sent to capture a certain individual sounds fun. My spin on this would be to have something like a Security shuttle spawn in as well, with a Head of Department and two bodyguards, and make capturing that Head of Department alive the team's objective.

Getting into the territory of contractors from SS13 which I hope happens here eventually.

**Comment by ps3moira** [comment]
without a direct way for crew to deal with space ships with death machines mounted on them, they shouldn't be added

**Comment by wraith811** [comment]
I think the main issue would be that once they complete their main objective, they could easily just get bored and start murder hoboing. I suggest bounty style objectives where the syndicate team act as kind of a reverse cargo, stealing semi valuable items and rather than being paid in money, they get paid in TC

**Comment by Kadeo64** [comment]
hm.. here's my take on an objective for them.

They get a "Kidnap person" objective and a second, "Hold person for ransom" objective

The ransom person and item are defined in the objective though, and the items could be a bag of bananas, could be a live animal. Who knows. Has to be something that might be hard to procure without crew facilities like cargo or botany, or else they can just steal it. Unique food would be perfect for this. Once they get the ransom, they release the hostage.

To make the objectives turn green it would just detect if they touched the grid. The ransom person needs to step on the grid for like, 30 seconds, and then the objective turns green permanently, and the ransom item objective turns green when it's detected on the grid.

**Comment by IProduceWidgets** [comment]
I feel like people are missing that the rarity of these events is rather prohibitive to extensive unique mechanics. We're talking 1/100 rounds or so here.

**Comment by nymhole** [comment]
ive played this role, its fucking awesome. you are a team of 3 syndies with random gear and random names, it could be shit or it could be good. you get cobras garenteed so stealth is encouraged and you get nuke codes. this is not a "murderbone" role, and if this is then so is loneop. its a good role that introduces diversity to midround antags.

**Comment by Kadeo64** [comment]
> ive played this role, its fucking awesome. you are a team of 3 syndies with random gear and random names, it could be shit or it could be good. you get cobras garenteed so stealth is encouraged and you get nuke codes. this is not a "murderbone" role, and if this is then so is loneop. its a good role that introduces diversity to midround antags.

loneop is a murderbone role :trollface:

**Comment by ps3moira** [comment]
I just fail to see this as anything other than another lone op or randomized nukies. Why should there be more murder bone antags with nothing new to bring to the table in terms of gameplay other than having a ship that can blast the station (which the crew has no way of directly dealing with unless they've pre-emptively spent the whole round trying to build a shuttle.)

**Comment by Kadeo64** [comment]
> (which the crew has no way of directly dealing with unless they've pre-emptively spent the whole round trying to build a shuttle.)

ESPECIALLY now that crew only has one round-start shuttle instead of two for emergency boarding maneuvers.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
from what i can gather, they are budget nukies

**Comment by Djungelskog2** [comment]
> from what i can gather, they are budget nukies

Don't we already have loneops
I also thought these were supposed to NOT murderbone

**Comment by ps3moira** [comment]
Almost none of the issues brought up were answered it was just merged as is 🚬

**Comment by Kadeo64** [comment]
> Almost none of the issues brought up were answered it was just merged as is 🚬

can't wait for "Remove Syndicate Instigator Shuttle pending rules rework" PR in the next two weeks

**Comment by deltanedas** [comment]
it doesnt even work because its not in the gamerule table

**Pull request merged**
