### PR TITLE
Telepad revival

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

emisse said it would be a good t3

**Media**

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Advanced Spray is now a tier 2 tech and Advanced Entertainment is a tier 1 tech.
- add: Added Bluespace Cargo Transport as a new tier 3 civilian services technology.
- fix: Fixed cargo telepads working without being linked to a console.

### CODE REVIEW

**Comment by Kromabae** [comment]
but would you still sell with the shuttle?

**Comment by deltanedas** [comment]
yes especially since in the future when trade station is real, moving stuff onto sale pallets and using the console probably still needs shuttle rather than teleporter (even tho rd hand teleporter could troll this)

**Comment by OctoRocket** [comment]
Hand teleported should probably not be able to teleport between FTL destinations.

**Comment by Cheackraze** [comment]
Are you able to link multiple pallets to one console still?

**Pull request merged**
