### PR TITLE
Make slimes scream upon feeling the burn of water.

### PR DESCRIPTION
**Pull request by Adrian16199**
TO-DO:

-[ ] Well, make it actualy work.

Not sure how this will go but hey, better to try and learn than not to.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Slimes now scream in pain upon being sprayed.

### CODE REVIEW

**Comment by deltanedas** [comment]
cant you just add emote effect to slimes water reaction

**Comment by Adrian16199** [comment]
> cant you just add emote effect to slimes water reaction

This is what happens so the answer is *No*

Uploading Space Station 14 2024-02-01 21-42-19.mp4…

Giving a probability makes it incosistent, especially if you take into account the difference between spray bottle particles and a fire extinguisher.

**Comment by deltanedas** [comment]
add a cooldown field to the emote effect then

**Comment by Adrian16199** [comment]
> add a cooldown field to the emote effect then

So if i were only keeping the current slime.yml as its currently published, 

- !type:Emote
        emote: Scream
        cooldown: 2
        
 It results in the fact that it simply doesnt care for the cooldown.
 If you would tell me that i forgot a space or it should be somewhere else, cool, nice.
 Otherwise, this doesnt work. There is nothin for reagant effects/reactions to care for the cooldown part without a cooldown being mentioned. So I need to make a mention in the code itself for a cooldown for it to even be like: Oh wait, I need to care for a cooldown~!

**Comment by deltanedas** [comment]
> It needs to be in C# mentioned in somesort of form.

you need to actually implement it too yes

```
[DataField]
TimeSpan? Cooldown;

[DataField(customTypeSerializer: typeof(TimeOffsetSerializer))]
TimeSpan NextEmote = TimeSpan.Zero;
```

then actually use it and handle unpausing

**Comment by Adrian16199** [comment]
Thank you.

**Pull request closed without merging**
