### PR TITLE
Combat wrench

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

The combat wrench is a wrench that interacts 1.2x faster and does 12 damage on hit, only available in the syndicate toolbox

the syndicate toolbox now also comes with a syndicate tool belt instead of an engineering one
## Why / Balance

the point is to have a portable weapon that is worse than other options in the uplink, such as the energy pen or the toolbox itself while still being a good tool that youll want to keep on you

it does 12 damage instead of 10 so that you cant just grab a fire extinguisher off the wall and have the same thing

it also has the same in hand and on belt sprite as the wrench so unless someone looks closely and/or you dont work fast you'll get outed, increasing tension
## Media

icon

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: JoeHammad
- add: Combat wrenches are now being supplied to syndicate toolboxes

### CODE REVIEW

**Comment by LankLTE** [comment]
Why..? The epen already exists if you want a cheap weapon and the toolbox itself is a really good weapon too. This just seems like you’re powercreeping an already really good syndie item with a completely unnecessary change.

**Comment by JoeHammad1844** [comment]
image
i said why right there and i'm not opposed to increasing the toolbox price to 3TC

**Comment by LankLTE** [comment]
> image
> 
> i said why right there and i'm not opposed to increasing the toolbox price to 3TC or decrease the damage to 11

What's the point in having an uplink item that's intentionally a worse version of other uplink items? The cybersun pen already fills the niche of "tool + weapon". I'd also rather you don't nerf the sus toolbox to add an item most people won't need or use ever.

**Comment by JoeHammad1844** [comment]
> What's the point in having an uplink item that's intentionally a worse version of other uplink items?

so the toolbox can still be 2TC and not make other uplink items useless

**Comment by LankLTE** [comment]
> so the toolbox can still be 2TC and not make other uplink items useless

You still haven't answered my question of why the toolbox actually needs this. If you want a tool that works as a weapon, the cybersun pen already exists and the sus toolbox already contains a weapon in the toolbox itself.

**Comment by JoeHammad1844** [comment]
image
damn

**Comment by retequizzle** [comment]
man imagine if you put some of this energy towards PRing ideas for non-syndicate gameplay instead of powercreeping traitors/nukies to the nauseating degree that maintainers have to look at every PR of yours and ask "why"

**Comment by mirrorcult** [comment]
this PR is entirely web-edited and contains no ingame showcase, please reread the PR guidelines and furthermore please stop making these pointless bloat powercreep PRs or they are just going to be closed outright with no discussion

**Pull request closed without merging**
