### PR TITLE
PDA opening as a toggle.

### PR DESCRIPTION
**Pull request by sentient-ai**
Code's prettier this time since it's constrained to useEntity and iActivate instead of hijacking and renaming an existing Open function. Something about QoL and it feeling more natural to use.

edit: Trying to figure out git / dealing with nulls so this un-breaks.

### CODE REVIEW

**Comment by sentient-ai** [comment]
I'm not sure if I dealt with the possible dereference of a null in a proper way, but it builds now.

**Comment by ShadowCommander** [comment]
I think it'd be better to add a new method to `BoundUserInterface` called `Toggle` which toggles and then replace usages of `Open` with `Toggle`.

**Comment by sentient-ai** [comment]
Hm, I'll give that a go and resubmit later.

**Comment by sentient-ai** [comment]
So BoundUserInterface is inside RobustServer, so would I just push something there first, then toggle the toggles for the various handhelds that would benefit from it?

**Comment by ShadowCommander** [comment]
Yeah, you'll need to fork `RobustToolbox`, but it shouldn't be much more complicated code wise than you've been doing here. Then after that you'll be able to change the stuff on `space-station-14` to use the Toggle method you implemented instead of Open.

**Pull request closed without merging**
