### PR TITLE
Remove rads from bananium

### PR DESCRIPTION
**Pull request by DogZeroX**
webedit ops

## About the PR

This allows people to power the station infinitely with rad absortion with absolutely no drawbacks.
Also it's annoying to deal with. (I'm surprised bananium has it but not literal uranium, wouldn't want that anyways, not yet at least)
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Bananium no longer emit rads

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
fill in the pr description dork

**Comment by deltanedas** [comment]
sci needs it for radiation noob

**Comment by DogZeroX** [comment]
Kid called uranium shiv:

**Comment by Clone0401** [comment]
I don’t see a problem with it as it’s a fairly rare material from salv, and it requires salv to pretty much look for bananium specifically to have a chance to get enough.
Plus I think it’s just a clever interaction players could use

**Comment by Admiral-Obvious-001** [comment]
I used this effect recently as an II but it should probably go. It doesn't really do anything practical except "for the funny" of permadeath when salvage prints a stack.

**Comment by slarticodefast** [comment]
Isn't the radioactivity of bananium the main reason making it a fun gimmick? Without it is just another building material.

> This allows people to power the station infinitely with rad absortion with absolutely no drawbacks.

This is only possible with a lot of work being done to set this up and only sometimes seen later in a round. Salvage has to mine, engineering has to set up and maintain the rad collectors. You need a lot of bananium to power a whole station. Also they get irradiated when handling the bananium which is a drawback. The bananium could also get stolen and weaponized.

> Kid called uranium shiv:

This feels more like a bug. The artifact requires radiation, but directly taking radiation damage triggers it, too.

**Comment by Iamgoofball** [comment]
just make bananium slippery?

**Comment by lzk228** [comment]
and bananium became useless...

**Comment by Thurtik** [comment]
What if bananium just had an upper rads limit when stacked together instead of removing it altogether?

**Comment by Moomoobeef** [comment]
rename bananium clownium and make it the only thing clowns can eat to sustain themselves

**Pull request merged**
