### PR TITLE
Arachnid rework

### PR DESCRIPTION
**Pull request by PixelTheKermit**
### This is meant to change arachnids (no surprises there). Changes include:

- extra hands
- ability to produce silk
- changed damage modifiers
- 1.5 oxy damage instead of 1 (or when compared to old arachnids, instead of 2)
- slower hunger drain
- 5 slash damage claws
- removal of bloat

### Other changes include:

- web structures (for fun!)
- tarantulas now drop silk

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/85175107/9855dad0-afb8-4333-b000-f87c1abe7d8e

https://github.com/space-wizards/space-station-14/assets/85175107/389b89f3-cddf-4a8b-bc3b-a76bcc8f7d5f

**Changelog**

:cl: PixelTK
tweak: Arachnids have received several changes. Check your local PR station for more details.

### CODE REVIEW

**Comment by PixelTheKermit** [comment]
PR should be fine now. Let me know if it's not.

**Comment by PixelTheKermit** [comment]
For your information, it was not ok. I forgot to commit like 10 things

**Comment by Emisse** [comment]
i trust that youll keep up on balance with this, sericulture all being defined in prototype is good, LG2M

**Comment by OctoRocket** [comment]
Can moths eat silk?

**Comment by Anzarot121** [comment]
Lol, they were already incredibly broken, but you decided to go all the way.

**Comment by DogZeroX** [comment]
Great feedback.

**Pull request merged**
