### PR TITLE
Remove vehicles

### PR DESCRIPTION
**Pull request by metalgearsloth**
Vehicle code is dogwater and wheelchairs just keeps exposing edgecases. If someone wants it brought it back they can do vehicle refactor.

:cl:
- remove: Removed vehicles pending rework (the code is bad I was told to make this more obvious).

### CODE REVIEW

**Comment by Aisu9** [comment]
does this also disable the wheelchair bound trait?

**Comment by Dutch-VanDerLinde** [comment]
> does this also disable the wheelchair bound trait?

yes

**Comment by Kadeo64** [comment]
wheelchair warriors unite we gotta refactor vehicle code

**Comment by SonicHDC** [comment]
Maybe don't delete it, just remove trait and seat ability or just refactor without deleting all?

**Comment by brainfood1183** [comment]
some maps have wheelchair spawners i believe.

**Comment by TsjipTsjip** [comment]
The wheelchair spawners being present are addressed by the migration that this PR adds. Outright removing the wheelchairs is very restrictive for servers that still wish to use it and are on an upstream codebase, I would opt for merely disabling the wheelchairbound trait, the wheelchair recipe and keeping the currently proposed migration to ensure wheelchairs are an admin-only thing.

**Comment by potato1234x** [comment]
why tho ive never seen any problems with the wheelchairs specifically, if it was that bad wouldnt removing every vehicle be necessary

**Comment by metalgearsloth** [comment]
> why tho ive never seen any problems with the wheelchairs specifically, if it was that bad wouldnt removing every vehicle be necessary

Removing all vehicles is also an option I'm also open to, it's just wheelchairs get far more complaints.

**Comment by Kadeo64** [comment]
> Removing all vehicles is also an option I'm also open to, it's just wheelchairs get far more complaints.

wheelchairs are the only constantly encountered vehicle and frankly, wheelchairs are the only vehicle with no practical gameplay purpose besides roleplay
Secways and Ripleys (and to a lesser extent cardboard boxes) all have actual practical use, especially secways.

**Comment by TsjipTsjip** [comment]
I must request that the vehicles themselves are not removed, only any means of accessing them through normal means. (i.e. The vehicle spawners, any mapped prototypes, crafting recipes, lathe recipes, ...) This way other servers on this codebase can still work around this change without having to fork from it.

**Comment by metalgearsloth** [comment]
> I must request that the vehicles themselves are not removed, only any means of accessing them through normal means. (i.e. The vehicle spawners, any mapped prototypes, crafting recipes, lathe recipes, ...) This way other servers on this codebase can still work around this change without having to fork from it.

If forks want to adopt rane's code they can move it into their own folder and avoid conflicts, buckle rarely gets touched anyway.

**Comment by TsjipTsjip** [comment]
> If forks want to adopt rane's code they can move it into their own folder and avoid conflicts, buckle rarely gets touched anyway.

Unfortunately this answer is not satisfactory, as I specifically made this comment with regards to servers that do not have the ability to fork from this codebase.

**Comment by Kadeo64** [comment]
few notes:
1: secway was an important part of security as it gave security noslips at the cost of only one hand, good against traitors and nukies and such
2: supplybot couldn't be buckled to, and was literally just for hauling cargo (keep supplybot please)
3: cardboard box wasn't touched (as far as I know it's still a vehicle, it suffers from the same rotation bug)

**Comment by metalgearsloth** [comment]
> few notes: 3: cardboard box wasn't touched (as far as I know it's still a vehicle, it suffers from the same rotation bug)

Cardboard boxes are not vehicles, hence the shitcode.

**Comment by 0x6273** [comment]
Changelog needs update. Also why remove the rsi?

**Comment by metalgearsloth** [comment]
Sprites being left in.

**Comment by Ilya246** [comment]
why does this remove supplybots and taxibots? neither are really vehicles and even though taxibots are rideable i don't see how they would have any more issues than chairs do, as they're not controllable

**Comment by Kadeo64** [comment]
> why does this remove supplybots and taxibots? neither are really vehicles and even though taxibots are rideable i don't see how they would have any more issues than chairs do, as they're not controllable

Taxibots are literally just ATVs but the player riding it and the player driving it are separate. They're still weird and wonky and if the other vehicles are being removed I can see taxibots being removed too. However, supplybots have actual utility outside of the vehicle part so I don't see why they're getting axed too. #justiceforsupplybots

**Comment by Emisse** [comment]
Ok just remake it without the vehicle code then that's not what this pr is about

**Pull request merged**
