### PR TITLE
ID Change to Dinnerware Vending Machine

### PR DESCRIPTION
**Pull request by erohrs2**
## About the PR

Dinnerware Vending Machine ID requirement changed to require Kitchen Access.

## Why / Balance

To discourage players without Kitchen access from invading the Kitchen (usually by jumping the counter) to grab equipment from the machine (usually knives).

## Technical details

Dinnerware Vending Machine's Access Reader component changed from `Service` to `Kitchen`.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Dinnerware Vending Machine access changed from "Service" to "Kitchen".

### CODE REVIEW

**Comment by slarticodefast** [comment]
I thought it was like this so botany can use the beakers?

**Comment by erohrs2** [comment]
> I thought it was like this so botany can use the beakers?

This is a good point. However, there are very few instances where the Chef is not in the Kitchen (especially at the start of the round, when someone is most likely to ask for equipment). This isn't to discourage other service workers from using Kitchen equipment, but to instead have players ask the Chef for the equipment instead.

**Comment by thetolbean** [comment]
Additionally, in the botany/kitchen environment, the kitchen should be asking botany for crops throughout the game. I think it wouldn't be egregious to have botany ask for beakers in exchange if needed. This just encourages roleplaying, a core aspect of ss14

**Comment by IamVelcroboy** [comment]
Just put beakers in the hydro vend.

**Comment by JoelZimmerman** [comment]
> > I thought it was like this so botany can use the beakers?
> 
> This is a good point. However, there are very few instances where the Chef is not in the Kitchen (especially at the start of the round, when someone is most likely to ask for equipment). This isn't to discourage other service workers from using Kitchen equipment, but to instead have players ask the Chef for the equipment instead.

But there are often rounds where there is no chef, and then it's just an annoyance.

**Comment by erohrs2** [comment]
> > > I thought it was like this so botany can use the beakers?
> > 
> > 
> > This is a good point. However, there are very few instances where the Chef is not in the Kitchen (especially at the start of the round, when someone is most likely to ask for equipment). This isn't to discourage other service workers from using Kitchen equipment, but to instead have players ask the Chef for the equipment instead.
> 
> But there are often rounds where there is no chef, and then it's just an annoyance.

I believe the Nutrimax Vending machine, the one that dispenses Botanist tools, has Hydroponics level access. If a botanist isn't present, it can be quite a bit more annoying for a Chef to do their job, and it is difficult to replace the botanist as you don't have easy access to their tools. But I don't think that you should really get the advantages of a job that isn't present. Granted, if beakers are this necessary for Botanists and things like buckets or glasses won't do, then they should probably start with them in the first place.

**Comment by erohrs2** [comment]
> It may be worth considering who realistically has [service access](https://github.com/space-wizards/space-station-14/tree/master/Resources/Prototypes/Roles/Jobs/Civilian) and kitchen access.
> 
> 1. Is the absence of knifes that much of a hindrance to chefs/service workers? To my understanding most grab their knifes and keep them on their person or atleast in sight.
> 2. Are knifes a "critical" component of syndicate gameplay as an easier source of weapons?
> 
> it is worth noting that service workers, have kitchen access by default, not just service. They will not be losing access to their knifes or the ability to distribute beakers to botany.

Thank you for pointing out who has what access, I wasn't aware of some of these.

1. As pointed out in previous comments and the PR reasoning, this isn't to discourage other players with Service access and not Kitchen access from not getting a knife, it is for discouraging players who aren't supposed to be in Kitchen invading Kitchen. Kitchen is unique in that it is very easy to trespass by jumping the counter. 
2. They aren't really what this PR is for. This PR is just to encourage a more realistic (and lawful) environment. If someone wants a knife, they can ask for it without doing something illegal. Even if someone isn't a Syndicate, it is still illegal to be in Kitchen without Kitchen access.

**Comment by slarticodefast** [comment]
I brought this up for discussion with the other maintainers. Restricting others from stealing the knives makes sense and botany can simply ask for a beaker. On lowpop servers they can get kitchen access from the HOP or captain when there is no chef. Thank you for your contribution.

**Pull request merged**
