### PR TITLE
Gas canisters HP buffed and now spawn broken version

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Buffed the HP of the gas canisters a little and they now spawn their busted counterpart when destroyed. This can then be broken more into some plasteel.

**Screenshots**

**Changelog**

:cl: Swept
- add: Destroyed state for canisters
- tweak: Buffed canister HP from 100 to 300

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Review by Zumorica — COMMENTED** [review]
The gas inside those canisters just gets deleted this way...

**Comment by SweptWasTaken** [comment]
> 
> 
> The gas inside those canisters just gets deleted this way...

This is how it is on master.

**Comment by Zumorica** [comment]
> > The gas inside those canisters just gets deleted this way...
> 
> This is how it is on master.

You could have coded a destruction behavior for canisters so their gas leaks into whatever tile they're in

**Comment by SweptWasTaken** [comment]
> 
> 
> > > The gas inside those canisters just gets deleted this way...
> > 
> > 
> > This is how it is on master.
> 
> You could have coded a destruction behavior for canisters so their gas leaks into whatever tile they're in

That's out of scope for this PR.

**Comment by SweptWasTaken** [comment]
I committed submodule and broke this PR trying to fix it so i'm closing and remaking on master.

**Pull request closed without merging**
