### PR TITLE
Unique Hardsuit Light Colors

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Changes the light colors on most hardsuits to make them more stylish.
Suits effected; Atmos, Engineer, CE, CMO, RD, Security, HoS, Wizard, and every ERT suit.

It could cause some problem with identifying syndicate from crew, colorblindness and just generally being able to see with more obtrusive colors like purple and blue.

I am very open to feedback on this due to it's rather unnecessary nature and the problems it might cause.

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.
image
image
image

The last three shown are for reference reasons. Left to right being the syndicate bloodred, syndicate elite and original light color.

**Changelog**
:cl:
- tweak: Changed most hardsuit light colors to be unique.

### CODE REVIEW

**Comment by AJCM-git** [comment]
I think it would look better if they were the default color but also very **slightly** their color if you know what i mean

**Comment by EmoGarbage404** [comment]
to clarify AJCM, the saturation is really high. Make it more of a tint instead.

**Comment by arealbeba** [comment]
i don't like it. why light's color would always match hardsuit main color?

**Comment by mirrorcult** [comment]
i think these should be toned down a little bit but otherwise good

**Comment by PixelTheKermit** [comment]
A bit too saturated, but yeah it's good.

**Comment by Nairodian** [comment]
All toned down heavily.
image
image
image

**Comment by mirrorcult** [comment]
yeah those are pretty great

**Review by mirrorcult — APPROVED** [review]

**Review by PixelTheKermit — APPROVED** [review]
Mhm, like these a lot more

**Pull request merged**
