### PR TITLE
Adds a Pii flag to the Admin flags

### LINKED ISSUE #6859: Restricting access to user PII behind a +CHECKUSER admin permission.
This would mean obscuring the IP and HWID of the user in some non-reversible manner or just hiding it outright, and not allowing non-checkuser staff to apply IP bans (and simply presenting a "sticky ban" button that does so but with the details obscured).
This requires changes to SS14.Admin as well.

### PR DESCRIPTION
**Pull request by Geekyhobo**
## About the PR

Add a Pii Flag to Admin Flags, Closes #6859 

## Why / Balance

Helpful for restricting Pii behind permission, not everyone should have access to that type of sensitive info, also this has much greater use on SS14.Admin where there is PII all over the place, with a flag I can now hide that Pii (Coming SoonTM)

## Technical details

For IPs its censored them like this 123.123.123:2222 to ***.***.***:****,
And for HWIDs it just replaces the entire thing with ******************************

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot 2024-01-08 002829

## Breaking changes

**Changelog**

No Outward facing changes to the player, if they could see Pii we might have some other problems, Admin Changelog update though.

### CODE REVIEW

**Comment by Geekyhobo** [comment]
Also Tell me if there are any instances that I missed

**Comment by Geekyhobo** [comment]
> I didn't check for any missing cases, and I didn't verify this, but I'm pretty sure vv can leak hwid and maybe IP through a reference to the player session in player minds. Genuinely good luck censoring that 💀

💀 fuck, I was trying to find it thru vv last night but lemme take another look this gonna be much harder if you can leak it thru VV :/

**Comment by AJCM-git** [comment]
@Geekyhobo You coming back to this?

**Comment by Geekyhobo** [comment]
> @Geekyhobo You coming back to this?

Yes, its being a massive pain in the ass to figure out a way to censor vv

**Comment by ShadowCommander** [comment]
@Geekyhobo Are you still working on this?

**Comment by Geekyhobo** [comment]
I fucked my diff and branch so gonna close this and just open a new one

**Pull request closed without merging**
