### PR TITLE
Adding embedding function to 23 melee weapons.

### PR DESCRIPTION
**Pull request by marboww**
## About the PR
This PR added the ability to embedding 23 melee weapons.

All weapons that have been given the function will be listed below:

- swords (captain's sabre, katana, energy katana, machete, claymore, cutlass)
- crushers (all 3 weapons)
- knives (kitchen, butcher's cleaver)
- shiv (all 5 weapons)
- fireaxe
- cult weapons (all 3 weapons)
- scalpels (all 3 weapons)

## Why / Balance
Before this, only spears, combat knives and PEN could be stuck in. If we even have a pen stuck in, then why not give the same function to other bladed weapons?

Like a combat knife, each of the listed melee weapons deals ~85% damage when thrown

## Media
image
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
No CL

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
you're gonna need to have actual reasoning considering half of these weapons don't even have a hard point + letting them embed can lead to non-trivial bleed spam via throwing a ton of them.

**Comment by metalgearsloth** [comment]
I think remove pen embedding yeah.

**Comment by marboww** [comment]
> you're gonna need to have actual reasoning considering half of these weapons don't even have a hard point + letting them embed can lead to non-trivial bleed spam via throwing a ton of them.

but spam is just a bug

**Comment by potato1234x** [comment]
> I think remove pen embedding yeah.

please no

**Comment by marboww** [comment]
ok, I'll close the PR for not being realistic

**Pull request closed without merging**
