### PR TITLE
Add backrooms

### PR DESCRIPTION
**Pull request by metalgearsloth**
shitty

image

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
now make it spawn rouny

**Comment by Mannybrado** [comment]
liminal

**Comment by mirrorcult** [comment]
lamprey 14 when

**Comment by Luxzhv** [comment]
Hell yeah, Lamprey 14

**Comment by AtnerNT** [comment]
Would have to be adapted to ss14, however I worked on a backrooms gateway location for unitystation awhile back where I used a maze generation algorithm to create procedual maintenance shafts.
If you want some inspiration you can find the script for it here:
https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Systems/MaintGenerator.cs

**Comment by metalgearsloth** [comment]
later

**Pull request closed without merging**
