### PR TITLE
Transit: NEW Evacuation shuttle

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This is a brand new small-scale shuttle for the station Cluster. It features a bridge, security, medical and engineering departmental room. Unlike the normal evac shuttle, it only has two ports on either side and 29 seats. Ideal for a player base of around 30-50.

The shuttle is saved through **savegrid** and has gone through **variantize**. The main tile used is steel and includes a security holding cell.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

transit_evac

**Changelog**

:cl: Ubaser
- add: Added a new evacuation shuttle for Cluster

### CODE REVIEW

**Comment by stopka-html** [comment]
There is no bar(

**Comment by OctoRocket** [comment]
It should probably dock with both docking port sections.

**Comment by Scribbles0** [comment]
heyo, found a couple of things that should probably be addressed:

- save as a grid not a map file so that it can dock to the station
- LED lights are pretty bright, better to use the normal ones imo
- as octo said, bit weird with only 2 docking ports
- medbay could probably use a bit more supplies + a defib
- engi probably shouldn't have a glass door
- engi and medbay doors have plating underneath (missing a tile)
- should probably use shuttle glass for the sec cell as well (+ put grilles under them)

- main "hallway" feels a bit empty, maybe could use a few more chairs or something

image

- could also probably but chairs here too

image

**Comment by Emisse** [comment]
Agree with scribbles, ask them questions if you have any in cartography since cluster is their map

**Comment by deltanedas** [comment]
could fit a nice bar in the hallway since its so empty

**Comment by UbaserB** [comment]
> heyo, found a couple of things that should probably be addressed:
> 
> * missing tiny fans under the airlocks
> * LED lights are pretty bright, better to use the normal ones imo
> * as octo said, bit weird with only 2 docking ports
> * medbay could probably use a bit more supplies + a defib
> * engi probably shouldn't have a glass door
> * engi and medbay doors have plating underneath (missing a tile)
> * should probably use shuttle glass for the sec cell as well (+ put grilles under them)
> * main "hallway" feels a bit empty, maybe could use a few more chairs or something
> 
> image
> 
> * could also probably but chairs here too
> 
> image

fans underneath the airlocks? Do you mean scrubbers or vents?

**Comment by UbaserB** [comment]
> could fit a nice bar in the hallway since its so empty

i was thinking about that but with the layout there's no good location for it unless blocking access

**Comment by UbaserB** [comment]
> It should probably dock with both docking port sections.

ill keep that in mind for if i try to make another evac shuttle in the future :)

**Review by Scribbles0 — APPROVED** [review]
lgtm @Emisse can merg now

**Comment by OctoRocket** [comment]
Is the picture updated?

**Comment by UbaserB** [comment]
> Is the picture updated?

yeah

**Pull request merged**
