### PR TITLE
Paramedic loses external access

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

~~CMO now has external access.~~
Paramed no longer has external access.

## Why / Balance

~~Due to the recent effort in giving heads more control of their apartments via ID Card Computers, CMO has been left lacking an access that allows them to promote paramedics. Giving the CMO access doesn't really have any drawbacks.~~
Unused permission, also would require CMO to have external in order for CMO to hire one.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Paramed no longer has external access.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/21677

?

**Comment by Aexxie** [comment]
> #21677
> 
> ?

I can't find anything saying CMO shouldn't have access. Seems reasonable imo, doesnt't really hurt anything, and parameds do need externals to do their job. If we are going for heads being able to manage their departments more on their own without requiring the HoP or Captain, then this is probably required assuming paras dont get bwoinked entirely

**Comment by Emisse** [comment]
most 13 servers paramed doesnt have externals anyway

**Comment by Aexxie** [comment]
> paramed being a shit fucking job aside, do they even need external access to function effectively? Hardsuits make sense for rescuing people from bombings and such, but is there really a scenario where they're going off-station enough on their own to warrant external access? It's not like people spend a ton of time out in the middle of space.

there's been times where a para finds me in space because of that. I play para sometimes, too. Yeah its a bit infrequent but idk

**Comment by Aexxie** [comment]
> change pr to remove paramed externals access

sure.

**Comment by PokkeTigrex** [comment]
While infrequent, outside rescuing around the edge of the station are still certainly needed for salvies, engis, and purposefully hidden bodies. We would sometimes have the paras do a perimeter sweep in case we think that a body is hidden outside, often around solars or exterior singulo chamber. This is just another access that para's will now have to ask HoP for, on top of whatever else they usually ask for, and makes them more of a reskinned doctor otherwise.

**Comment by CrigCrag** [comment]
if you really need to go outside, medical can team up with someone who does have external access

**Comment by MagnusCrowe** [comment]
> paramed being a shit fucking job aside

No need to be rude about it.

**Pull request merged**
