### PR TITLE
Fixes/removes borg spawnpoint from Oasis Engineering, added one to Robotics

### PR DESCRIPTION
**Pull request by august-sun**
## About the PR
Removed borg spawnpoint from Oasis Engineering, added one to Robotics

## Why / Balance
Fixes https://github.com/space-wizards/space-station-14/issues/33895.

## Technical details
Removed mapped spawnpoint for borgs in the Oasis engineering containment area, added to Robotics.

## Media
Oasis-0

Oasis-1

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by Emisse** [comment]
diff got me acting unwise

**Comment by august-sun** [comment]
> diff got me acting unwise

WHY IS IT LIKE THAT what did I do wrong

**Comment by Emisse** [comment]
i had to open rider but seems fine

**Comment by ArtisticRoomba** [comment]
cant wait for the hotfix PR referencing this PR when something secretly breaks

**Pull request merged**
