### PR TITLE
Balaclava Face Mask

### PR DESCRIPTION
**Pull request by VulfiMoon**
## About the PR
A balaclava mask will protect the identity of the person on whom it is worn
The balaclava can be purchased at uplink for 2 TC, as well as at the cinema vending machine and syndiedrobe using emag
Redone https://github.com/space-wizards/space-station-14/pull/19561
## Why / Balance
Will help the antagonist hide his identity and looks super 

## Media
image

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: VulfiMoon
- add: Gorlex found a huge box with balaclavas in space USSP and distributes it to agents as a means of protecting the face from identity disclosure

### CODE REVIEW

**Comment by TheShuEd** [comment]
Yeah, sprite is bad

**Comment by VulfiMoon** [comment]
> Кажется, что спрайт нуждается в улучшении, например, в правильном затенении и тому подобном.

The sprite was taken from another PR author https://github.com/space-wizards/space-station-14/pull/19561. I just redesigned the prototype and added a sprite for the reptile.

**Comment by TheShuEd** [comment]
everything is in order, this is a closed and unaccepted pr, which you may not be guided by by design

**Comment by VulfiMoon** [comment]
I'll redo the sprite now, don't worry

**Comment by HoidC** [comment]
I think this should be one telecrystal instead of two. It’s literally just a black face mask. Gas masks are available everywhere and do the same thing.

**Comment by VulfiMoon** [comment]
> I think this should be one telecrystal instead of two. It’s literally just a black face mask. Gas masks are available everywhere and do the same thing.

2 TC for style and to protect your face from revealing your identity

**Comment by TheShuEd** [comment]
I think it shouldn’t be in the uplink at all, since it’s just a sock with holes.  I'd rather just add it to the crafting menu

**Comment by VulfiMoon** [comment]
I'll replace the sprite soon

**Comment by BolloTea** [comment]
Please replace Russia in CL with USSP, lore moment

**Comment by BolloTea** [comment]
Thank you, (Spacibo, comrade)

**Comment by VulfiMoon** [comment]
> I think this should be one telecrystal instead of two. It’s literally just a black face mask. Gas masks are available everywhere and do the same thing.

I still decided, I will remove it from the uplink and add it to the craft menu

**Comment by Errant-4** [comment]
I see no reason why it would be bad if the crew could fashion masks from cloth. This is a bit speculative but would this still be worth 2 tc then?

**Comment by VulfiMoon** [comment]
I already wrote above. I will make a craft, you will need fabric and in return you will receive an ugly version of a balaclava

**Comment by VulfiMoon** [comment]
I'll close PR for now, then I'll rework it

**Comment by CatMagic1** [comment]
So... this blocks identity even if you have an id equipped?

**Comment by deltanedas** [comment]
no it works like other masks

this should not be 2 tc (price of an entire fish /!\) for what can be gotten all over maints for free

**Comment by Hmeister-fake** [comment]
> this should not be 2 tc (price of an entire fish /!\) for what can be gotten all over maints for free

it could be in a kit? E.g. "Thieving kit" Balaclava, thieving gloves, rag/syndicate soap and a smoke bomb for 5/6 TC?

**Pull request closed without merging**
