### PR TITLE
Update headsets_alt.yml

### PR DESCRIPTION
**Pull request by justdie12**
## Why / Balance
it seemed to me that this would be logical from the side of the headset size, and it will not have a global impact

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by MureixloI** [comment]
I think since they increase the slots for alternative headsets, it is better to increase for the syndicate and freelancers

**Comment by Cojoke-dot** [comment]
Why... I thought the item was meant to be a cosmetic choice between the left and right ear?

**Comment by justdie12** [comment]
> Why... I thought the item was meant to be a cosmetic choice between the left and right ear?

but look on size, it's way bigger than normal.

**Comment by Cojoke-dot** [comment]
It kinda just feels like power creep for uh... a sprite that goes further out?
Screenshot 2024-06-29 211254Screenshot 2024-06-29 211258

**Comment by metalgearsloth** [comment]
1. Unnecessary creep with not a good reason.
2. The freelancer key count already doesn't match the alt key count.

**Pull request closed without merging**
