### PR TITLE
Antique laser gun is now size 25

### LINKED ISSUE #11491: Captain's antique laser size needs bumping
Right now it's 10 but should be the standard of 50. If someone wants to haul it around it should be a choice to do so (plus slots exist).

### PR DESCRIPTION
**Pull request by FunkySphere**
## About the PR 

**Changelog**

closes #11491

:cl:
- tweak: Captain's antique laser gun has now the size of 25

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Should be 30 like other guns.

**Comment by FunkySphere** [comment]
Heavy grade assistant leather makes the gun even heavier

**Review by FunkySphere — COMMENTED** [review]
Now it's changed to 30

**Comment by GoodWheatley** [comment]
@metalgearsloth wasnt there a conversation about how it’s a bad idea to change the size of the captains items?

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
