### PR TITLE
Senior physician sleeve symmetry

### PR DESCRIPTION
**Pull request by Kukutis96513**
## About the PR

Made the senior physician uniforms have symmetrical sleeves.
## Why / Balance

Symmetry = cool

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Screenshot_320

also git acts weird and shows unrelated commits, i'm fairly sure they're not doing anything though so it should be fine?

### CODE REVIEW

**Comment by Kukutis96513** [comment]
yeah honestly i'm considering deleting my local repository, maybe it'll make those unrelated commits stop appearing

**Comment by Cojoke-dot** [comment]
Oh, I like the asymmetry of the senior stuff, it makes it more unique

**Comment by beck-thompson** [comment]
I was about to say the same thing! I think the asymmetry looks better than symmetric

**Comment by Hanzdegloker** [comment]
I am a huge fan of the asymmetry, ngl

**Comment by Kukutis96513** [comment]
Screenshot_312
personally its kind of weird how one sleeve is blue but the other one is white.

though i guess i can just make the sleeves blue and not do anything with the arm bands and see if that looks any better?

Screenshot_313

**Comment by Hanzdegloker** [comment]
make it two armbands, one orange one blue each on their respective side. Thats how the labcoat is right? The senior physician labcoat iirc looks like that and it should probably match it

**Comment by beck-thompson** [comment]
I'm a big fan of the new design!

**Comment by Kukutis96513** [comment]
Alright i'll make the sleeves blue and just leave the armbands as is!

**Comment by GNF54** [comment]
honestly the orange should be removed since the SP's don't get Chemistry access

**Comment by Cojoke-dot** [comment]
> honestly the orange should be removed since the SP's don't get Chemistry access

Think of it like a mastery of the job, its showing you have the experience in med to run chem if needed based of your experience in the field

**Comment by GNF54** [comment]
> > honestly the orange should be removed since the SP's don't get Chemistry access
> 
> Think of it like a mastery of the job, its showing you have the experience in med to run chem if needed based of your experience in the field

yeah but like, they don't have access... Why would they have chemistry orange if they don't have chem access

**Comment by thebadman4662** [comment]
Because you do not need access to teach, or so was the reasoning for removal of senior roles.

**Comment by Golinth** [comment]
> yeah but like, they don't have access... Why would they have chemistry orange if they don't have chem access

Because they have the knowledge of chemistry. A chemist may see someone in the senior clothing (with the chem orange) and ask them how to do something. I'd imagine Green will be added to the other sleeve if virology every becomes a thing again, so that virologists know they may ask a SP questions as well.

**Comment by Hanzdegloker** [comment]
> I'd imagine Green will be added to the other sleeve if virology every becomes a thing again, so that virologists know they may ask a SP questions as well.

I unironically want to be a senior virologist

**Pull request merged**
