### PR TITLE
Remove sunglasses from ClothesMate.

### PR DESCRIPTION
**Pull request by Holinka4ever**
## About the PR

Removing sunglasses from ClothesMate.

## Why / Balance

A feedback from discord server: https://discord.com/channels/310555209753690112/1206896736920936489

As told in discussion, sunglasses got into ClothesMate due of early metagaming from security against head revolutionaires, so there first iteration were like... fake.

So story in short: one of contributors added same sunglasses, with same sprite, with same name, but diffrent description and functionality, one of them is sunglasses with flash immunity, and another doesnt got it.

And after two weeks, one of head devs saw that theres is two same item, that have a lot of similarities in sprite and name, but not in description and functions, so them after terminated fake sunglasses from game. And returned normal sunglasses to barthender and musician... and into clothesmate.

Main reason that they stayed in clothesmate is because to defend head revs from metagaming from security. These main reason is no longer active part of a game, and went into refractoring/else.

Due of discussion that having security items in a public places, and giving a lot of people(that might be evil) flash immunity is very wrong in balance purpose.

## Media

Before:
image-63
After
image-56

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Sunglasses were removed from ClothesMate

### CODE REVIEW

**Comment by lzk228** [comment]
its the only way to get the sunglasses for tiders and other crew, so it's better to keep them

**Comment by Holinka4ever** [comment]
> its the only way to get the sunglasses for tiders and other crew, so it's better to keep them

I dont think though that we should think about tiders as something good on station, but if a crew wish to have cool sunglasses, what about to ask security? It will encourage social part of the game!

**Comment by Admiral-Obvious-001** [comment]
I've seen sunglasses either fully taken from or completely left alone in the clothesmates on the arrivals shuttle not counting whatever happens on the dorm mapped clothes vendor. Completely removing them from the vendors will return the issue of metagaming sunglasses. You could do the thing where you split the sunglasses out too like we had 3 weeks ago, but that'd also cause metagaming. I just don't think this PR actually solves an issue and will introduce more issues down the line.

**Comment by Holinka4ever** [comment]
> I've seen sunglasses either fully taken from or completely left alone in the clothesmates on the arrivals shuttle not counting whatever happens on the dorm mapped clothes vendor.

It actually depends on situation, though, people still use it because free flash immunity. Someone that know or dont know. Or you are an agent, that can have use help from flash immunity, or get into metagame trap from having sunglasses.

> Completely removing them from the vendors will return the issue of metagaming sunglasses.

If i remember well, there is wasnt any metagamey situation with sunglasses before adding revolutionaires. Still, giving head rev sunglasses is looks like rigged trap from a begining.

>You could do the thing where you split the sunglasses out too like we had 3 weeks ago, but that'd also cause metagaming. 

And that was, i remember were in that pr that splitting sunglasses, and it was wrong in my opinion.

>I just don't think this PR actually solves an issue and will introduce more issues down the line.

I just riping off sunglasses from clothesmate, because its doesnt feel very balanced against security. Even though, they shouldnt be there all along, they were buffer against head rev metagamey, but revs are gone, and having for public use flash immunity is wrong.

**Comment by deltanedas** [comment]
revs are disabled so thered no metagaming to be had

sec will never give flash protection to a tider

**Comment by notquitehadouken** [comment]
revs don't exist any more ergo this basically just removes drip from clothesmate

**Comment by Holinka4ever** [comment]
> sec will never give flash protection to a tider

Cause it will give significant defence against their non-lethal methods of stoping crewmember. But also you can be nice with security to ask sunglasses from their secfab (kinda funny that item that exists in secfab, is in free for use in clothesmate)

> this basically just removes drip from clothesmate
 
I mean, i understand that sunglasses look cool and anything with it, but if a pep that loving drip, gonna hide own face under gas mask with sunglasses, isnt it gonna turn some tides?


> revs don't exist any more 


> revs are disabled so thered no metagaming to be had

I am using this argument about head rev, because thats all point why sunglasses put into clothesmate. But revs are gone, and sunglasses have no point to be in clothesmate. From balance prespective, that civil jobs having one of notable defence from security for free and without being part of security, doesnt seems right at all.

**Comment by Krunklehorn** [comment]
There was a time a few months ago when security sunglasses were shaded a different color and regular sunglasses didn't have flash protection. Just make a PR to revert to that.

**Comment by thebadman4662** [comment]
Secglassess are now tier 2 sunglassess/sechud so it will take bit more effort than just reverting a PR...

**Comment by Admiral-Obvious-001** [comment]
There are other ways to acquire sunglasses though, notably through specific antag bundles such as the bribery kit and likely other places I'm forgetting at the moment.

**Comment by asperger-sind** [comment]
I think it's good that there are free and available sunglasses on-board, especially with our current (ridiculously overpowered) flashes and flashbangs. Antags shouldn't be quite literally forced to buy or procure flash resistance to even stand a chance against one sec officer, and trivialization of sec gameplay by using flashes isn't very good either.

**Comment by deltanedas** [comment]
in the engivend instead of clothesmate

**Comment by Partmedia** [comment]
Thanks for your investigation and context. The PR that folded cosmetic sunglasses into regular sunglasses is here: https://github.com/space-wizards/space-station-14/pull/23232

That PR's author writes:

> This just replaces the previously cosmetic sunglasses with normal ones (along with reducing the amount in the clothesmate). I don't really think it's an issue that a few crewmembers can get their hands on sunglasses.

The current PR's author writes:

> Due of discussion that having security items in a public places, and giving a lot of people(that might be evil) flash immunity is very wrong in balance purpose.

But there are only two sunglasses in the ClothesMate which is certainly not "a lot of people", unless of course there are lots of ClothesMates being mapped. Unless someone has evidence otherwise, I concur that giving out two sunglasses is not too big of a concern, as long as other sunglasses spawns are limited.

**Comment by Holinka4ever** [comment]
> 
> That PR's author writes:
> 
> > This just replaces the previously cosmetic sunglasses with normal ones (along with reducing the amount in the clothesmate). I don't really think it's an issue that a few crewmembers can get their hands on sunglasses.

Right.. he has points of not remiving them.

> The current PR's author writes:
> 
> > Due of discussion that having security items in a public places, and giving a lot of people(that might be evil) flash immunity is very wrong in balance purpose.
>
> But there are only two sunglasses in the ClothesMate which is certainly not "a lot of people", unless of course there are lots of ClothesMates being mapped. Unless someone has evidence otherwise, I concur that giving out two sunglasses is not too big of a concern, as long as other sunglasses spawns are limited.

I mean, right, pair sunglasses are not changing weather, cause its pair and limited due of machine.
But clothesmat is diffrent due that:

1) Its (clothesmat) pretty common on stations, so you can get more than one pair of sunglasses, also arrival shuttle has one clothesmat besides.

2) Its not limited, if you have restock box for clothesmat, that can give you sunglasses. 

3} Not a really an argument, but sunglasses can be made on secfab, also secvendor have sunglasses too. That might rise some questions, why civils has access for sec items. Even sunglasses.

P.S.
Besides, sunglasses in clothesmat can lead to powergamey snowball, that can end poorly, like spacepen.

**Comment by SlamBamActionman** [comment]
By default all maps have 4 free sunglasses maps, 2 from arrivals shuttle and 2 from on-station vending machine. Depending on population and player distribution, this can actually make up a not insignificant number of crew.

My issue with the sunglasses being in the ClothesMate is twofold: 
- It provides a very easy and formuleic counter to flashes; roll antag, go to ClothesMate, grab sunglasses. There is nothing interesting with this choice other than the occasional situation where all sunglasses are already taken, at which point the antag will have to actually make some decisions.
- It's inconsistent with all other items in the ClothesMate. Sunglasses are the only item that provide a direct, unique and strong defense in the ClothesMate. My understanding of the ClothesMate's design is that it's meant to provide clothing alternatives for aesthetic purposes. Flash-safe sunglasses have no business being in it.

I do understand the need for drip though; personally I would've rather seen a replacement pair of sunglasses that are visually distinct rather than a complete removal. The beer goggles stand out good enough from normal sunglasses, so I'm sure it can be done.

**Comment by Emisse** [comment]
sure idc

**Comment by africalimedrop** [comment]
is discord where low iq people congregate or something? all the dumb shit i'm seeing is due to discussion had there.

**Comment by deltanedas** [comment]
most on topic "discussion"

**Pull request merged**
