### PR TITLE
Fixes compile warnings

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About the PR 
Fixes all of the compile warnings.

### TODO:
- [ ] Fix the last 300 compile warnings. (25 Shared, 29 Client, 246 Server)
- [ ] Fix any runtime bugs caused by the fixes for the compile warnings.

**Screenshots**

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Bold.

**Comment by Just-a-Unity-Dev** [comment]
CL isn't playerfacing and can be removed

**Comment by Just-a-Unity-Dev** [comment]
:salute: otherwise

**Comment by ElectroJr** [comment]
>  Fix the last 300 compile warnings. (25 Shared, 29 Client, 246 Server)

>\> space-wizards/RobustToolbox/pull/3373

So close, yet so far.

**Comment by TemporalOroboros** [comment]
> > Fix the last 300 compile warnings. (25 Shared, 29 Client, 246 Server)
> 
> > > [space-wizards/RobustToolbox/pull/3373](https://github.com/space-wizards/RobustToolbox/pull/3373)
> 
> So close, yet so far.

:pain:

**Comment by ElectroJr** [comment]
Also for reviewability its better to create a separate PR for each warning/obsolete type, because otherwise this is going to be a giant PR.

**Comment by TemporalOroboros** [comment]
So it begins.

**Comment by ElectroJr** [comment]
Yeah another good reason to split this into several smaller PRs.

**Comment by metalgearsloth** [comment]
Good PR but do it like 50-100 files at a time next time.

**Pull request closed without merging**
