### PR TITLE
Separate Certain Walls

### PR DESCRIPTION
**Pull request by ps3moira**
## About the PR

Made it so brick walls, wood walls and web walls doesn't conjoin with other walls.

## Why / Balance

To make the walls look less visually jarring when right next to different walls.

## Media
Screenshot 2024-02-28 005823
Screenshot 2024-02-28 004408
Screenshot 2024-02-28 004644

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl:
- tweak: Changed brick, wood, and web walls to be unable to conjoin with different walls.

### CODE REVIEW

**Comment by UbaserB** [comment]
pretty :o

**Comment by ps3moira** [comment]
> pretty :o

I have mad mapping skillz B)

**Comment by EmoGarbage404** [comment]
this is going to break icon smoothing with a ton of other stuff that typically smooths with walls, like foam, asteroids, etc.

**Comment by ps3moira** [comment]
> this is going to break icon smoothing with a ton of other stuff that typically smooths with walls, like foam, asteroids, etc.

image

Doesn't look that bad?

**Comment by metalgearsloth** [comment]
Looks fine to me nerd also @ps3moira you don't need to resolve conflicts on your pr unless a maintainer asks for it.

**Pull request merged**
