### PR TITLE
Revert "FTL + AI fixes (#31952)"

### PR DESCRIPTION
**Pull request by slarticodefast**
This reverts commit f7a87b5f32818b291f80acd8534a847e5e78971e.

The arrivals shuttle was eating everything around it.
The engine change does not have to be reverted since it only added new functions.

Screenshot (279)

### CODE REVIEW

**Comment by deltanedas** [comment]
arrivaloose

**Comment by slarticodefast** [comment]
> I think this reintroduces https://github.com/space-wizards/space-station-14/issues/31683 and https://github.com/space-wizards/space-station-14/issues/31860 ?

Yes, but it makes the game playable at least. Every single docking port on the station was removed by the shuttle. The servers have been reverted a few commits in the meantime.
Sloth is coming up with a fix, so I hope this PR won't be needed.

**Comment by 0x6273** [comment]
> > I think this reintroduces #31683 and #31860 ?
> 
> Yes, but it makes the game playable at least. Every single docking port on the station was removed by the shuttle. The servers have been reverted a few commits in the meantime. Sloth is coming up with a fix, so I hope this PR won't be needed.

Yeah I agree with you that reverting is better than doing nothing. But those issues I linked should be reopened in case this revert PR does get merged.

**Comment by VasilisThePikachu** [comment]
Merging so that no downstreams get bugged

**Pull request merged**
