### PR TITLE
Add Galoshes slowdown over slippery surfaces

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR adds a slowdown to Galoshes when walking over slippery surfaces and items, and a slowdown cap when walking over sticky surfaces. 

Walking over a slippery surface slows you down 30%. Walking over a surface that slows you down (glue, kudzu) limits the slowdown to 30% max.

## Why / Balance

Galoshes are seen as one of if not _the_ best possible combat equipment crew has access to. They are so sought after that they can only be provided to janitors round-start, as otherwise Command will go pick up any spare (or Tiders will break in and steal them as soon as possible). The reason is the no-slips, and during a combat scenario (especially against an antag who has prepared slippery objects or lube) they allow you to move full speed without worrying about slipping. 

This PR changes the galoshes with the goal to not slow down Janitor gameplay while making them a suboptimal choice when fighting on slippery surfaces. They are still good shoes and preferrable over normal shoes with this PR, but they no longer give extreme value when fighting on slippery surfaces compared to magboots. This could with some other changes (like the jackboots buff #30586) eventually allow galoshes to no longer be spawn-only.

Janitor gameplay largely involves traversing the station from point to point; it's definitely a contender for being the most mobile job on the station. As such, any default slowdown to the galoshes would significantly impact the time spent walking. Once a janitor is at a location where clean-up is necessary, they instead move slower and more methodically to clean up spills, so movement speed is no longer a significant factor. 

The slowdown the galoshes provide is 30%. This can be compared to magboots (20% slowdown) and walking (50% slowdown). This slowdown is applied automatically when moving over a slippery surface, effectively acting like magboots with an "auto-toggle".  The slowdown is small enough that it doesn't impact a janitor performing their job duties, but it's significant enough that combat on slippery surfaces favors magboots/no-slips.

The cap on slowdown makes it more comfortable for the janitor to clean glue spills and other sticky surfaces. No-Slips are still effected by sticky surfaces, so antags rarely use glue for combat, making fighting on sticky surfaces rarer.

## Technical details

The PR implements two components `SlowedOverSlippery` and `SlowdownModifierContactCapClothing`. This enables making shoes that have a slowdown cap but no no-slip, or slowing down over slippery surfaces while still slipping. 

`SlipAttemptEvent` is no longer a cancellable event since it checks for both slipping and slowdown, and cancelling the event would risk skipping the slowdown.

I'm a bit unsure if the methods are in the correct classes (there's an argument that `SubscribeLocalEvent<SlipperyComponent, EndCollideEvent>(OnEntityExit);` should be in `SpeedModifierContactSystem`); give your thoughts in the review.

## Media

https://github.com/user-attachments/assets/c50d1dd8-e2ea-4518-8e42-d6a4adc738aa

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Janitor's galoshes now apply slowdown over slippery surfaces, and has a max slowdown cap over sticky surfaces.

### CODE REVIEW

**Comment by lzk228** [comment]
then maybe we can add them back to the JaniDrobe?

**Comment by SlamBamActionman** [comment]
> then maybe we can add them back to the JaniDrobe?

This would be the goal. I think there needs to be at least the jackboots buff since galoshes are still better than normal shoes and having variety in viable options would make them less desirable as steal targets. But I guess HoP going in to grab them roundstart will be pretty much equivalent to grabbing magboots now.

**Comment by TurboTrackerss14** [comment]
> > then maybe we can add them back to the JaniDrobe?
> 
> This would be the goal. 

I am still gunna say I am strongly against noslips of this level being available mapped/vended in such a way. 
Magboots have a persistent slowdown affect when enabled, these apply it automatically. 
Its a nice QoL change to move them away from the grabby hands of tiders and powergamers. 
But having them be attainable without theft/murder/whatever actions, will just lead to them being used by the same group we are trying to push them away from.

**Comment by TurboTrackerss14** [comment]
Reference from one of the linked prs. 
https://github.com/space-wizards/space-station-14/pull/25484#issuecomment-1974917284

**Comment by SlamBamActionman** [comment]
I agree that in its current state they should still remain round-start only. Once there is more variation in viable footwear? Then we might be able to go for it.

I did consider reducing the slowdown to walking speed (so that galoshes are essentially an auto-walk, making them more of a nice-to-have than anything strictly combat viable) but I figured it might be too much of a nerf on its own.

**Comment by TurboTrackerss14** [comment]
>Once there is more variation in viable footwear? Then we might be able to go for it.

People who are desperate for no slips can break into somewhere more high risk than a janitors closet. Like EVA. 
No mater how you affect this change, janitorial closet is one of the least defended rooms with it being enterable with just a crowbar on most every map. 

I really don't see this opinion changing no matter what changes are made, they are one of the very few footwear items that are true noslips. They should be VERY limited.

**Comment by Hanzdegloker** [comment]
> I really don't see this opinion changing no matter what changes are made, they are one of the very few footwear items that are true noslips. They should be VERY limited.

I concur, I will say this, it would be nice if we had soft stuns. Say you slip, but now you can crawl out of the lube puddle and get back up, or crawl thru a lube puddle instead of slipping hell. It would mean a fully lubed Armory isn't the end of the world, it'd still be a massive advantage to whomever has noslips but you could at least crawl and shoot.

**Review by metalgearsloth — APPROVED** [review]

**Review by metalgearsloth — APPROVED** [review]
Actually access attribute but I always forget to mention it.

**Comment by Minigold07** [comment]
That could also mean that people using galoshes in combat could also utilize glue more effective. I have not seen glue used in combat so far so that could be interesting.

**Pull request merged**
