### PR TITLE
Changing 'centcom' to 'centcomm'

### PR DESCRIPTION
**Pull request by ThatGuyUSA**
## About the PR
It changes all instances of 'centcom' to 'centcomm' in all files, comments, descriptions, prototype IDs, and textures!

## Why / Balance
This was to standardize the way Central Command was referred by, it is to the specifications of issue #9807.

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

### CODE REVIEW

**Comment by ThatGuyUSA** [comment]
Oops I guess I missed a step huh... please hold!!!!

**Comment by UbaserB** [comment]
holy

**Comment by ThatGuyUSA** [comment]
Built the game with 0 errors, launched the game with 0 errors,
I think I might've missed a step in the whole creating and merging the branch part, this is my first time using github so it might take a while. Oops!

**Comment by ThatGuyUSA** [comment]
Yeaaa I screwed up badly I think.
My SS14 master clone on my system was a few pull requests out of date, I proceeded to update the one on my github but not the one on my system. Then only after making all of these changes on my system, I made a new branch doing all of the pulling and merging, I was a bit confused why it said robust toolbox was touched! Oh what a disaster...

**Comment by Golinth** [comment]
Why are we even using Centcomm, in every other circumstance IRL Central Command is shortened to CentCom

**Comment by slarticodefast** [comment]
This will completely break the game for forks and they will have to rename them everywhere these items are used.
For maps this is automatically done using migration.yml, so you should add the renamed prototypes there instead of renaming the old entries (which will make the old migration stop working!).

**Comment by ThatGuyUSA** [comment]
> This will completely break the game for forks and they will have to rename them everywhere these items are used. For maps this is automatically done using migration.yml, so you should add the renamed prototypes there instead of renaming the old entries (which will make the old migration stop working!). But I still think it would be better to just leave the prototype names the way they are since you don't even see them in-game.

Breaking all in dev forks would be terrible, 
I already went this far, might as well go the extra mile and do the migrations thingy. I mean in that old thread (#9807) seemed really intent on making it 'centcomm' (not sure why), I just had an evening to kill so I just did it.

But if I do this, do I revert the prototypes back to their old names and put the prototypes in migrations.yml, or do I just put them in migrations.yml as they are right now?

**Comment by slarticodefast** [comment]
First you have to revert the change you made in migration.yml, since it breaks the old migration.
Then you would add a new entry on the bottom to migrate all the prototype name changes.

**Comment by ThatGuyUSA** [comment]
don't look at me

**Comment by SlamBamActionman** [comment]
Hello! Thank you for your contribution.

This was discussed internally and due to concerns about downstream forks, merge conflicts and migration issues we're not interested in large-scale entity ID refactors at the moment. For now, we ask players to consider both CentCom and CentComm as valid ways to shorten Central Command.

**Pull request closed without merging**
