### PR TITLE
Remove skub sound

### PR DESCRIPTION
**Pull request by metalgearsloth**
:cl:
- fix: Fixed skub sound existing.

### CODE REVIEW

**Comment by potato1234x** [comment]
why though

**Comment by metalgearsloth** [comment]
> why though

Not interested in keeping transphobes around.

**Comment by unusualcrow** [comment]
seems a little unnecessary to do this to an iconic item. I'm happy to record a new version of the sound if you want.

**Comment by potato1234x** [comment]
> seems a little unnecessary to do this to an iconic item. I'm happy to record a new version of the sound if you want.

this

**Comment by unusualcrow** [comment]
here you go

https://files.catbox.moe/u0hwn7.ogg

**Comment by metalgearsloth** [comment]
Already organising an alternate recording from the person who did weh who is not banned from the community.

**Pull request merged**
