### PR TITLE
Splitstation

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
50 odd round start jobs with many more late joins. Can be balanced once we have some opinions but it is a rather mid to large station still when you consider it's in two halves.

I recognise there's some polish to be done and some changes that need made but I want to get it out in the hands of the people before I do anything so I can do any changes in one go.

**Screenshots**

Map renderer no likey

**Changelog**

:cl:
- add: Split Station map! A new medium to large map that's split in half!

### CODE REVIEW

**Comment by Peptide90** [comment]
Emisse has given some great feedback. Might involve quite a bit of structural changes so will get to work on that tomorrow and Thursday should be ready if all goes to plan. Hopefully map renderer will work then too.

**Comment by moonheart08** [comment]
- [ ] Main station is split a bit _too_ well and probably needs another 1-2 corridors connecting it together.
- [ ] The halls are pretty devoid of decoration (vendors, disposals, little tables). You need to keep in mind how much time people spend in them
- [ ] Almost of the rooms are square. From a design perspective this isn't a huge deal but it's definitely very boring to look at.
- [ ] We don't have an SM and probably won't for quite a bit. Room needs repurposed and a singulo added. (Yes this is an issue with Pillar too)
- [ ] Armory is entirely undefended, take down 1 r-wall from the main hall and you're in. This is a big no-no
- [ ] Northern part of sec is normal walls while the rest is reinforced?
- [ ] The gravity generator is overlapping with walls. Move it one down. (Also an issue on Pillar)
- [ ] The maint at the top left of the map is only usable for medical personnel, this needs fixed (try connecting it to more places).
- [ ] The airlocks for docking are useless as there's no gap between the doors, also the docking nub is not oriented correctly.
image
- [ ] RD's office is unfurnished
image
- [ ] Triple doors in cargo?
image
- [ ] Sec shouldn't have maint running straight through it, massive vulnerability in a department meant to be secure.
image
- [ ] The rainbows are a bit much, sorry. Tone it down maybe?
- [ ] The bridge needs rethought. It's an impenetrable fortress and also boring simultaneously.
- [ ] Vault needs reinforced.
- [ ] What?
image
- [ ] This is extraordinarily large for a room with a guitar in it.
image
- [ ] Can we have these more organic room shapes in the entire rest of the station? It'd look better
image
- [ ] Avoid running cables and pipes under walls unless absolutely necessary, it's a huge pain to repair otherwise.

All in all, needs changes. Sorry for the long, long list of shit.
splitstation-0

**Comment by ike709** [comment]
I don't know if mass drivers are in yet but I think it'd be funnier to launch disposals across via mass driver than to run a really long pipe.

**Comment by Peptide90** [comment]
> I don't know if mass drivers are in yet but I think it'd be funnier to launch disposals across via mass driver than to run a really long pipe.

Really long pipe is just disposals rollercoaster for the fun of it otherwise I’d of just given top half their own disposals.

**Comment by moonheart08** [comment]
> I don't know if mass drivers are in yet but I think it'd be funnier to launch disposals across via mass driver than to run a really long pipe.

they're not, unfortunately

**Comment by PJB3005** [comment]
Holy shit it's Berlin station

**Comment by Peptide90** [comment]
> * [ ]  Main station is split a bit _too_ well and probably needs another 1-2 corridors connecting it together.

This is the purpose of the map imo. I want there to be situations where you have to launch yourself across a space gap fast if sh*t hits the fan and you want to get to the shuttle otherwise use one of the other paths. Space walk path on the far right is an option.
>     * [ ]  The halls are pretty devoid of decoration (vendors, disposals, little tables). You need to keep in mind how much time people spend in them

Are they? I think there's a decent sprinkling of them without them being obnoxiously placed blocking hallways but I'll take another look. There's also not a big variety of vendors for it to not just look the same but I'll try.

>     * [ ]  Almost of the rooms are square. From a design perspective this isn't a huge deal but it's definitely very boring to look at.
Eh they're spacious enough but I'll see if there's something I can do.

>     * [ ]  We don't have an SM and probably won't for quite a bit. Room needs repurposed and a singulo added. (Yes this is an issue with Pillar too)
SM be in production hell but I hate singulo with a passion. It's boring and AME currently provides enough power. The room can also be repurposed slightly with a damaged RTG or artefact.

>     * [ ]  Armory is entirely undefended, take down 1 r-wall from the main hall and you're in. This is a big no-no
I got confused originally because I don't class that as the armory. It's like a loadout room designed specifically so you can push barriers out quickly into the corridor.

If we want to change the sec barrier into a grenade then sure this becomes redundant but otherwise the only thing in that room of use is a bunch of tasers which will be taken on roundstart. I can rejig this around with the evidence room but yeah, this is the issue with rooms that are in the center of the station when you want to make them bigger to have windoor cupboards.

>     * [ ]  Northern part of sec is normal walls while the rest is reinforced?
Oversight, will fix.

>     * [ ]  The gravity generator is overlapping with walls. Move it one down. (Also an issue on Pillar)
Did not know this, will fix.
>     * [ ]  The maint at the top left of the map is only usable for medical personnel, this needs fixed (try connecting it to more places).
The age old question of maint. Will come onto this again further down but unless you want a maint corridor going through the center of medbay, or ruining the arrivals emergency waiting area then you can't connect it more. I agree it needs more love with the escape pods but that's my thoughts unless someone wants to suggest how.
>     * [ ]  The airlocks for docking are useless as there's no gap between the doors, also the docking nub is not oriented correctly.
More an arrivals specific dock than an airlock, if only they would only open when docked but yes, I'll redo them. 

>     * [ ]  RD's office is unfurnished
oversight, will fix.

>     * [ ]  Triple doors in cargo?
matching aesthetic of corridor door and it's atmos so eventually will have atmos devices to drag out. Can shrink to 1 wide since my OCD will hurt if I do a 2 width.

>     * [ ]  Sec shouldn't have maint running straight through it, massive vulnerability in a department meant to be secure.
The other section is perma so not a problem. Same thing on Pillar, people want more maint and the only way to do that is to cut off anything that needs to be external facing like docks.
 
>     * [ ]  The rainbows are a bit much, sorry. Tone it down maybe?
I asked for feedback but sure, will remove. 
>     * [ ]  The bridge needs rethought. It's an impenetrable fortress and also boring simultaneously.
Never been a problem on box? If people can't shoot out two windows to get in then they don't deserve to get in. 
>     * [ ]  Vault needs reinforced.
Simulatiously a fortness and needs reinforced?
>     * [ ]  What?
Was originally an L shape but then I stuck drone spawners in and they need mats so *shrug*
> 
>     * [ ]  This is extraordinarily large for a room with a guitar in it.
secret cult room to give maint some flavor and a random instrument spawner. 
>     * [ ]  Can we have these more organic room shapes in the entire rest of the station? It'd look better
Can see what I can do but unless people are factoring in extra space for maint to eat into this means redoing a lot of sh*t.
>     * [ ]  Avoid running cables and pipes under walls unless absolutely necessary, it's a huge pain to repair otherwise.
Not sure what to say on this one. For the most part they follow hallways but when people want tighter maint and corridors it starts to get impossible. Yes there will be areas it's possible but I'll have to check.
>     * [ ]  Sci is entirely hallways?
Least there's ground work for adding in xenobio or whatever on that bottom corridor. I didn't anticipate virology so soon so have to redo a chunk of med to make it nicer which means deleting everything around med to make space.
>     * [ ]  Permabrig is inescapable.
skill issue. If you have competent people doing a break out it shouldn't be too hard. I get all of my experience from paradise and all prison breaks involved bringing a locker with a space suit, telling them to get in the toilet then doing a quick smash and grab. But yes, I'll connect it more to the asteroid / station.
>       All in all, needs changes. Sorry for the long, long list of shit.

Thanks for the feedback overall, I've got a long list of little changes to make from Emisse anyway which is good. I realise this map wasn't ready for PR but when you're stwhen you mapinit and fly through or walk through.

For future mappers we should make a checklist for each department and just in general for spaces so people cover all of the content and can do a self checklist before a PR to ensure things don't slip through.

**Comment by Peptide90** [comment]
Ready for review again after implementing a butt load of feedback from Emisse and Moony and after a short break.

Not sure why my map renderer is still scuffed locally so yah.

**Comment by moonheart08** [comment]
splitstation-0

**Comment by mirrorcult** [comment]
where did the gay hallway go

**Comment by moonheart08** [comment]
> where did the gay hallway go

too gay. 😔

**Comment by mirrorcult** [comment]
!1984

**Review by moonheart08 — APPROVED** [review]

**Pull request merged**
