### PR TITLE
Traitor flavor (take 2)

### PR DESCRIPTION
**Pull request by whateverusername0**
unable to reopen #28140 , so i uhh "reopened" it

## About the PR

added even more traitor variation. all the copypastas are graciously "borrowed" from /tg :trollface: 
also did sum slight changes to antag selection locales.
[design doc](https://github.com/space-wizards/docs/pull/241)

## Why / Balance

more text, more lore, more rp

## Technical details

changed objectiveIssuer to work more like an intermediate thing for locales
added factions to ObjectivesTextGetInfoEvent. this will be useful if blood brothers ever get added.
and please don't look in ObjectivesSystem, the summaries are god awful.

## Media

sum examples
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: More traitor variation.

### CODE REVIEW

**Comment by ElPidor** [comment]
LETS GOOOOOOOOOOOOOOO
MUST HAVE PR FOR MRP SERVERS

**Comment by ElPidor** [comment]
> The first example image highlights my main problem with this implementation: an agent working for the Animal Rights Consortium being tasked with butchering Ian.
> 
> I really like the idea of creating more variety in the traitor game mode, and I like the depth this adds to the world, but this really needs to be reflected in gameplay.
> 
> Instead of just being a randomly chosen name with some flavor text, these organizations should actually be prototypes that get used in the antag/objective selection systems. The selected organization should affect the likelihood of certain objectives being selected in a way that emphasizes their character - the ARC would never assign the corgi meat objective, but might prioritize stealing a live animal. Some organizations might oppose having their agents "die a glorious death" while others might be all about that. Organizations with grudges against other orgs should prioritize kill objectives targeting agents working for those orgs.
> 
> I like this idea a lot, but I want to see it implemented mechanically and not as fluff.

That's one small step for a traitor, one giant leap for future antags :trollface:

**Comment by whateverusername0** [comment]
> I like this idea a lot, but I want to see it implemented mechanically and not as fluff.

i can think of some kind of objective chance overrides for specific employers

also an ARC activist neesing premium corgi meat or a dude dying a glorious death fro donk pockets is hilarious :trollface:

**Comment by ps3moira** [comment]
two animal rights activists but no Interdyne Pharmaceutics?

**Comment by Futuristic-OK** [comment]
> two animal rights activists but no Interdyne Pharmaceutics?

This cannot be done. They would not have a distinctive feature in their actions

**Comment by MACMAN2003** [comment]
interdyne would probably want the hypospray

**Comment by Futuristic-OK** [comment]
> interdyne would probably want the hypospray

All of them want a hypospray, but Gorlax bomb the med, corporate climber become a CMO, and Mi13 stole it quietly. 
How will interdyne do this? Just like in vanilla or by hiring other agents. Why do we need this?

**Comment by ElPidor** [comment]
> two animal rights activists but no Interdyne Pharmaceutics?

You forgot S,E,L,F
At current state of the game these fractons kinda do nothing because no ai and only some borgs and no viruses with genes so what would interdyne agent :0

**Comment by metalgearsloth** [comment]
This is still pending a design doc.

**Comment by whateverusername0** [comment]
> This is still pending a design doc.

🤨

**Comment by mirrorcult** [comment]
i feel like its worth pointing out im pretty sure objectives already support having different "issuers", why doesnt this just use that

**Comment by ElPidor** [comment]
> > This is still pending a design doc.
> 
> 🤨

I BELIEVE IN YOU DUDE!!!

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> > interdyne would probably want the hypospray
> 
> All of them want a hypospray, but Gorlax bomb the med, corporate climber become a CMO, and Mi13 stole it quietly. How will interdyne do this? Just like in vanilla or by hiring other agents. Why do we need this?

I would assume interdyne would 1, want the hypo/crew monitor and 2, would mainly have "keep ___ alive" objectives

**Comment by TokenStyle** [comment]
> > This is still pending a design doc.
> 
> 🤨

Write design docs here (open space-wizards account and watch docs repository)
https://github.com/space-wizards/docs/pulls
Read more about design docs/feature proposal here:
https://docs.spacestation14.com/en/general-development/feature-proposals.html

And github template link:
https://github.com/space-wizards/docs/blob/master/src/en/templates/proposal.md

Keep it up! We all believe in you!

**Comment by whateverusername0** [comment]
after a lot of thinking i've decided to stop working on this
basically i stopped liking the idea of tator variety for no reason at all.
sorry wewalds 😔, you can use the branch of you wanna add it yourself i'm not completely deleting it

**Comment by TokenStyle** [comment]
takin'

**Pull request closed without merging**
