### PR TITLE
Give every job sad trombone implant (april fools)

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

title

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by CatMagic1** [comment]
why yall try to act like "april fools" changes shouldn't be used all year?

**Comment by metalgearsloth** [comment]
Please test your prs.

**Comment by Slava0135** [comment]
use `april-fools-2024` branch as base

**Comment by lzk228** [comment]
@Slava0135 reopen the pr please

**Comment by lzk228** [comment]
> make new PR with correct base branch (and make sure to merge into `april-fools-2024` too

my branch is updated reopen the pr please

**Comment by 0x6273** [comment]
> > make new PR with correct base branch (and make sure to merge into `april-fools-2024` too
> 
> my branch is updated reopen the pr please

There are like 23 unrelated commits in your pr. You probably need to rebase this on the april fools branch and force-push.

**Comment by lzk228** [comment]
> > > make new PR with correct base branch (and make sure to merge into `april-fools-2024` too
> > 
> > 
> > my branch is updated reopen the pr please
> 
> There are like 23 unrelated commits in your pr. You probably need to rebase this on the april fools branch and force-push.

they are not updating till pr is closed
anyway, i already opened a new pr

**Pull request closed without merging**
