### PR TITLE
shorten short raffle

### PR DESCRIPTION
**Pull request by HolySSSS**
## About the PR
Title says it

## Why / Balance

Solves #27751 

## Technical details

From 30 max seconds to 15 seconds
Increase raffle time by joining a raffle from 5 seconds to 2 seconds.
Initial time left as is, 10 seconds

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Short Raffle is now much shorter.

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
You're going in the opposite direction with this.

**Comment by Brandon-Huu** [comment]
Honestly should be 3-5 minute timer.
Ghost roles shouldn't be given out to people just because they compulsively check the ghost role menu

**Comment by mirrorcult** [comment]
ok, this is for the short raffle, so not valuable ghost roles. do you seriously want people to wait 5 minutes to be able to join as a mouse

**Comment by MerrytheManokit** [comment]
> Honestly should be 3-5 minute timer. "Valuable" Ghost roles shouldn't be given out to people just because they compulsively check the ghost role menu

I am not waiting 5 minutes for a slime :godo:

**Comment by UbaserB** [comment]
i dont think ERT should be short since admins dont ALWAYS spawn them in bulk

**Comment by HolySSSS** [comment]
Deathsquad and Centcom too afaik

**Comment by Brandon-Huu** [comment]
> ok, this is for the short raffle, so not valuable ghost roles. do you seriously want people to wait 5 minutes to be able to join as a mouse

In my 54 years on this planet I have never thought that a mouse would be selected through raffles

**Comment by ElectroJr** [comment]
Is 30 seconds really too long?

> In my 54 years on this planet I have never thought that a mouse would be selected through raffles

It only really matters if for whatever reason there are far more ghosts than there are roles available

**Comment by TheOneWhoIsManyFrame** [comment]
I feel like raffle is a problem, a stupid change and unfair against someone who been ghost for a long time, people whos been ghost and aiming for certain ghost role should have more weight/higher chance in the raffle.

**Comment by Brandon-Huu** [comment]
> I feel like raffle is a problem, a stupid change and unfair against someone who been ghost for a long time, people whos been ghost and aiming for certain ghost role should have more weight/higher chance in the raffle.

Raffles were implemented so that people like that don't get the roles.

**Comment by Brandon-Huu** [comment]
Are there any set criteria for a ghost role to be short vs default raffle?

**Comment by HolySSSS** [comment]
> Are there any set criteria for a ghost role to be short vs default raffle?

Well, I'll just list what can be a critera in my opinion and let you be the judge:
- how dangerous or destructive to the crew this role is
- how quickly it can die while being not controlled
- how many players want this role (e.g. Nukie, Spider, Death Squad, Slime, ERT, Revenant)
- how quickly this role is supposed to get into action (e.g. ERT and Deathsquad)

Most of short raffle roles quickly die from players or need to be picked ASAP to end the round quicker.

**Comment by metalgearsloth** [comment]
too much bikesheddin

**Pull request merged**
