### PR TITLE
Add "Skelly Versus The Rev" as lobby art

### PR DESCRIPTION
**Pull request by FairlySadPanda**
## About the PR
I don't draw much but had the idea to take the Bane-and-man-in-a-pink-lycra-bodysuit-posing meme and make something out of it. After three drawing programs and a dozen hours...

Note that this has had some fixes since posting on Discord (some background lines are coloured and cleaned, some fixes to stray pixels that were on the wrong side of the colouring war and an application of the Clip Studio smoothing filter to make it a bit less violent on the eyes (especially scaled)

## Why / Balance
A few more lobby pieces is always good and the 'mogus one needs a friend in the 2024 art camp.

This might cause a few more people to want to make a skelly sec officer, but tbh I think closet skeletons are mostly there to be quirky chaotic people, _and_ skeletons make amazing sec officers, so I think it's fine and uniquely Space Station.

## Media
skellyvstherev

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: A new piece of lobby art.

### CODE REVIEW

**Comment by deltanedas** [comment]
> skeletons make amazing sec officers

fake, a single explosions gibs them

**Comment by FairlySadPanda** [comment]
> > skeletons make amazing sec officers
> 
> fake, a single explosions gibs them

They don't need to breathe and have higher base speed.

**Comment by deltanedas** [comment]
internals + just use security brand meth

**Comment by MACMAN2003** [comment]
this pic goes hard, feel free to ACK ACK!

**Comment by nikthechampiongr** [comment]
I still can't believe you said that you started this as a shitpost. This goes unbelievably hard.

**Comment by EmoGarbage404** [comment]
i'm not biased

**Comment by Aexxie** [comment]
is this based off of the salamander round where skeleton 47 killed the headrevs after everyone was converted

**Pull request merged**
