### PR TITLE
Revert "seperate Stealth and StealthOnMove"

### PR DESCRIPTION
**Pull request by Emisse**
Reverts space-wizards/space-station-14#12035

### CODE REVIEW

**Comment by mirrorcult** [comment]
or just fix the bugs in a system that isnt even used yet

**Comment by Emisse** [comment]
idk how to fix these and id prefer having a working component then leaving in a broken system?

**Comment by metalgearsloth** [comment]
Is there even a github issue, all I see is https://github.com/space-wizards/space-station-14/issues/12197

**Comment by Emisse** [comment]
ill write an issue but what im saying is, it worked perfectly before and now it does not work at all

**Comment by Elijahrane** [comment]
Recorded on latest master

https://user-images.githubusercontent.com/60792108/197665298-a2e7bbc8-9939-4d5d-a47e-0873b06b6cfd.mp4

**Comment by Emisse** [comment]
you put the components on an entity, one or the other or both and they dont do anything now, as opposed to doing something before

**Comment by Emisse** [comment]
to get stealth to apply now you have to add both, move for a second, stop moving, delete the on move component really fast

**Comment by Emisse** [comment]
when before hand all you had to do was add the stealth component to any entity and it would just work

**Comment by Elijahrane** [comment]
yeah it just needs networking, stealthonmove only predicts when the proto has it

**Comment by Elijahrane** [comment]
I can make a PR real quick, the two datafields are readonly so does it actually need the comp state too if they can't be written to?

**Comment by Emisse** [comment]
they should be writeable to allow for editing of the component midround, stealth has been used frequently by admins

**Comment by Elijahrane** [comment]
> they should be writeable to allow for editing of the component midround, stealth has been used frequently by admins

changing something in VV doesn't seem to raise component state events so this is a bit above my expertise.
after https://github.com/space-wizards/space-station-14/pull/12203 the only regression (that's been reported) is fixed

**Comment by ElectroJr** [comment]
> they should be writeable to allow for editing of the component midround, stealth has been used frequently by admins

The fields were never writable in the first place (though that should be updated). Part of the point of splitting them was so that they could eventually be made writeable. The only bug the PR added was the lack of a `[NetworkedComponent]` attribute which is just a one line fix and not worth reverting over, especially as yaml prototype entities still work fine. 

Imma close this in favour of just fixing the issue.

> changing something in VV doesn't seem to raise component state events either way so this is a bit above my expertise.

The VV gui doesn't result in `Dirty()` being called. The entity needs to be dirtied separately using the `/dirty` command. I don't know much about the new VV stuff, maybe there is a way to automatically set & dirty now?

**Pull request closed without merging**
