### PR TITLE
Box Station - Connected Recycler, rerouted power for Singlo Substation, added law boards to AI upload room

### PR DESCRIPTION
**Pull request by southbridge-fur**
## About the PR

Addresses #32443, #30375 and #32581

### For #32443 
The Recycler just needed to be connected.

### For #30375 
I realized that the substation powering the PA and Containment field was on the same HV network as the power generation. This mean that if power generation ever stopped, the substation would drain before the station SMESes and could cause a _loose_. 

This changes it to where that substation is now running off of the same HV network as the rest of the station, thereby ensuring that the SMESes are used to power the substation which in turn powers the PA and Containment Field. Most other maps are wired this way.

### For #32581 
Added the 10 AI lawboards to the AI upload room. 

image

From top left going counter-clockwise:
- NT Default
- Paladin
- Ten Commandments
- Corporate
- Station Efficiency
- Left Glass Case: Artist
- Right Glass Case: Robocop
- Dungeon Master
- Crewsimov
- Nutimov

## Why / Balance

Addresses issues with the map. 

## Technical details

For the substation, I rerouted the power from the TEG through a new reinforced window between the power generation area and the TEG room. I also added a HV cable under the glass going to the PA to link those networks together. 

### Before
image

### After 
image

## Media

See above.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None that I know of.

**Changelog**

:cl: Southbridge
- fix: Box station's recycler has been properly connected.
- tweak: Box station's singlo substation has been rewired to the station-wide HV network. 
- add: Box station now has AI law boards in the upload room.

### CODE REVIEW

**Comment by southbridge-fur** [comment]
Will also address #32581 and fix those merge conflicts.

**Comment by Emisse** [comment]
test fail real

**Comment by southbridge-fur** [comment]
I see what's wrong and will fix it

**Comment by southbridge-fur** [comment]
Another similar issue, I will fix

**Comment by southbridge-fur** [comment]
Well I can't find where the entity with a uid of 0 is. Not really sure what I need to do to fix this.

**Comment by southbridge-fur** [comment]
> Well I can't find where the entity with a uid of 0 is. Not really sure what I need to do to fix this.

Looks like I may have had a UI element open while saving which caused there to be an invalid UID. It's been removed.

**Pull request merged**
