### PR TITLE
Add NT-Destroyer Shuttle

### PR DESCRIPTION
**Pull request by Scruq445**
Adds a specialized shuttle for NT Deathsquad Admeme event.

Features:
- Advanced Armory with extra pulse weaponry, advanced laser pistols, liberation vendor, secfab with preloaded materials, and a security vending machine.
- Medbay with full cryo, chemistry, and surgery setup. comes with extra damage kits, combat kits, and a bluespace beaker. Comes with a medfab with preloaded materials.
- Engineering bay with EngiVend, Atmospheric setup, and four (4) 15kW generators.
- Full Cloning setup
- Lounge area with Soda and Booze dispenser, Getmore Chocolate Vendor, Microwave, and a Complimentary Pizza for joining the NT Deathsquad taskforceas as stated by contract.
- Bridge comes with a IFF Console to toggle stealth capabilities, and has Nuke codes.

Images:
meow camera_4291094747934800009_1711991005854

### CODE REVIEW

**Comment by Reese1243** [comment]
this looks super cool. not sure how often itll get used but it looks cool!

**Comment by LittleNorthStar** [comment]
Should probably put a extra door between the external airlock and the weapons out in the armoury because anyone could connect to that side and get instant access to death squad weapons, apart from that it looks great

**Comment by Scruq445** [comment]
> Should probably put a extra door between the external airlock and the weapons out in the armoury because anyone could connect to that side and get instant access to death squad weapons, apart from that it looks great

I tried adding blast doors on the inside of the docking hatches but whenever I load the grid the wall buttons don't seem to open them.

**Comment by IProduceWidgets** [comment]
Please consider merging #29320 first.

(Also it would be nice to get some roles standardized by #28098 but I'm waiting on the aforementioned PR to flesh it out. 28098 has about 20 shuttles associated with it, but they got removed in an attempt to break the PR up... and then the half of the PR that was left got merged in a day by someone else, so... just please tell me what I need to do to get these damn shuttles organized in a way thats acceptable so we stop getting 3 PRs a week that exacerbate the problem and make my life worse trying to work on it.)

**Comment by IProduceWidgets** [comment]
My apologies. I just reading comprehended and realized this is not for shuttle events, but for admin events. I also have one of these, but uh, admin upload go brrrr. I almost want to say we probably shouldn't add a deathsquad shuttle because 
a) It will inspire admins to use deathsquad which we do not want.
b) It should never get enough play time to catch any issues it has

**Comment by Scruq445** [comment]
> a) It will inspire admins to use deathsquad which we do not want.

I see. It doesn't have to be used by the deathsquad solely it can be used as transport for VIP CentComm personnel and have some guards as export.

**Comment by slarticodefast** [comment]
The test fail seems to be real. Are you still working on this? If yes, I will bring it up for maintainer discussion.

**Pull request closed without merging**
