### PR TITLE
Change handcuff and handcuff box size

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR
Makes handcuffs smaller and handcuff box the same size as other sec boxes, keeps cable cuffs at size 5 to nerf and separate from regular cuffs

Fixes: #5317
**Changelog**

:cl: Daemon
- fix: Handcuff box has too little of a storing size

### CODE REVIEW

**Comment by mirrorcult** [comment]
this is good, the handcuff box should probably also have a whitelist for just handcuffs though

**Comment by ZeroDayDaemon** [comment]
That adds the slippery slope of adding a whitelist for every other kind of unique box doesn't it?

**Comment by mirrorcult** [comment]
only if you'd like

**Comment by ZeroDayDaemon** [comment]
I'll check out some ss13 codebases and see how they handle it

**Comment by mirrorcult** [comment]
if you mean the actual 'whitelist' part we already have that, `whitelist` field on StorageComponent

**Comment by ZeroDayDaemon** [comment]
referring to the concept of having a box whitelisted, not sure about the inherent value of having the items place-able in them be whitelisted, since, well its a box

**Review by PaulRitter — APPROVED** [review]

**Pull request merged**
