### PR TITLE
remove unsafe presents from present tree.

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Removed unsafe presents from the present tree.
Added the random coal present to the tree.
Changed the unsafe present prefix to be more clear.

## Why / Balance

- Insane presents can be any entity in the game
  - This is what results in signs, walls, singularities, etc, appearing in presents
- unsafe presents can be any entity in the game with item component
  - This is what results in debug items and round ending items from being given to random players
- (Possibly bad actor) Players take this as a opportunity to self antag with round ending items. (It's just a winter event who cares! Once a year thing! etc etc)
  - when not used for this, are used to powergame against antagonists
- Admins endlessly on the conflict of having to ban people for using debug items then recieving numerous complaints about being banned for using debug weapons
- Admins endlessly on the conflict of being told they shouldn't be banning people for using debug weapons and reciving complaints from players about the round being ended by said items

Going forward, presents should be further filtered (we have component filtering technology! See the randompresent system.) to exclude problem items like weapons and explosives.

If that is not reasonable, items will otherwise need to be handpicked and added to the whitelist, like the safe present.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Did we not already discuss this like a few weeks ago and decide not to do this?

**Comment by QuietlyWhisper** [comment]
@EmoGarbage404 It's still a reoccurring issue and I'm sick of seeing complaints from all sides

**Comment by EmoGarbage404** [comment]
i feel like we could probably just make presents only spawn on christmas day, rather than all month long. Yeah, you could still have issues, but it'd be a lot more limited than dealing with it for literally all month.

**Comment by QuietlyWhisper** [comment]
> i feel like we could probably just make presents only spawn on christmas day, rather than all month long. Yeah, you could still have issues, but it'd be a lot more limited than dealing with it for literally all month.

If so, are game admins expected to make exceptions to rules? 
...or are all players expected to behave with round ending presents?

**Comment by metalgearsloth** [comment]
Ultimately it's a headmin decision on what to do.

**Comment by EmoGarbage404** [comment]
i mean they are basically just meant to be a little bit of goofy fun for christmas. Tbh, I don't even know why they're available all month long. I feel like the main issue is just overexposure and being present in the game for so long that relatively rare things (singulo, debug items, etc) appear frequently.

**Comment by QuietlyWhisper** [comment]
> i mean they are basically just meant to be a little bit of goofy fun for christmas. Tbh, I don't even know why they're available all month long. I feel like the main issue is just overexposure and being present in the game for so long that relatively rare things (singulo, debug items, etc) appear frequently.

That's probably the case when you have 80 players and at minimum 20 rounds per server per day

**Comment by Hmeister-fake** [comment]
There should be an admin only christmas tree with only Insane presents and infinite uses per person for goofy admeme :godo:

**Comment by Emisse** [comment]
i already removed all the trees

**Pull request merged**
