### PR TITLE
Change Social Anxiety ----> Stutter

### PR DESCRIPTION
**Pull request by PixeltheAertistContrib**
## About the PR

The constant stuttering in the Social Anxiety trait is not Social Anxiety, but a stutter. Social Anxiety is a very different thing that does not directly link to constant stuttering like it does in media. So I simply changed the .ftl to replace the name displayed.

(sorry about the first PR i forgot to make a new branch since it was so quick)
## Why / Balance

We discussed it for a bit in the discord and decided that it's really not Social Anxiety and rather odd that the name of the trait was so.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: PixelTheAertist
- tweak: The Social Anxiety trait is now renamed to "Stutter"

### CODE REVIEW

**Comment by Plykiya** [comment]
Would it be more "social anxiety"-like if the stutter only occurs if the user is in a group of three or more people?

**Comment by PixeltheAertistContrib** [comment]
> Would it be more "social anxiety"-like if the stutter only occurs if the user is in a group of three or more people?

Not really, Social Anxiety relating to constant uncontrollable stuttering is a bit of a stereotype form mostly anime and cinema. It’s sometimes related but the way it in Ingame is much much more a stutter than full on social anxiety

**Comment by Cojoke-dot** [comment]
> Not really, Social Anxiety relating to constant uncontrollable stuttering is a bit of a stereotype from mostly anime and cinema. It’s sometimes related but the way it in Ingame is much much more a stutter than full on social anxiety.

Are most of the accents in game not stereotypes?

**Comment by PixeltheAertistContrib** [comment]
> > Not really, Social Anxiety relating to constant uncontrollable stuttering is a bit of a stereotype from mostly anime and cinema. It’s sometimes related but the way it in Ingame is much much more a stutter than full on social anxiety.
> 
> Are most of the accents in game not stereotypes?

I suppose, but this one is really just completely incorrect, stutter is the correct way to describe what this trait does. Social Anxiety really doesn’t have a big link with constant suttering and is a separate thing

**Pull request merged**
