### PR TITLE
Do-afters belonging to other players are now shaded

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Changed it so that do-afters belonging to other players end up being shaded.

## Why / Balance

Since sechuds and medhuds no longer act as night vision goggles, this change aligns with that gameplay vision. The do-after bar being completely visible by everyone in pitch-black darkness is the biggest giveaway to any kind of stealth gameplay.

I still made do-afters belonging to your own player unshaded so that you could actually see when your action is done rather than needing to guess when it is based on sound cues or something like that.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/d6664500-a8d8-43a7-8340-3a6ca7567a0a

**Changelog**

:cl:
- tweak: Do-after bars of other players are now shaded and harder to see in the dark.

### CODE REVIEW

**Comment by lzk228** [comment]
finally, less metagaming

**Comment by EpicJoston** [comment]
all my favorite changes have been yours plykiya <3

**Comment by mirrorcult** [comment]
great change

**Review by mirrorcult — APPROVED** [review]

**Comment by VektorZ1** [comment]
Brilliant

**Comment by deepdarkdepths** [comment]
Would having doafters that are being applied to you by another player make sense? You're supposed to feel what's happening to you after all

**Comment by Plykiya** [comment]
> Would having doafters that are being applied to you by another player be visible make sense? You're supposed to feel what's happening to you after all

consider making an issue or discussion thread for that, it will basically end up requiring all code that uses a do-after to be combed through and changed to make it more visible

**Pull request merged**
