### PR TITLE
Cauterize rework

### PR DESCRIPTION
**Pull request by Killerqu00**
## About the PR
Cauterize is reworked. Heat damage no longer cauterizes your wounds, instead you can use a verb action.

## Why / Balance
There is a difference between focused and unfocused heat. Cauterizing is not something you can do on accident; you have to specifically aim to do that, not just apply heat damage. 
Also, lightbulb cauterizing is evil.

## Technical details
CauterizerComponent handles everything related to cauterizing. If you need to make it work only when the item is active, it must have BOTH ItemToggle and ItemToggleHot.

## Media
https://youtu.be/kPjwPL_MyO4 (please ignore the doubling audio)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: You can now cauterize your wounds with a verb action (right click on the person with the tool for cauterizing).
- remove: Heat damage no longer cauterizes wounds.

### CODE REVIEW

**Comment by lzk228** [comment]
can i cauterize just with left-clicking on a person?

**Comment by Killerqu00** [comment]
> can i cauterize just with left-clicking on a person?

no, should it be added?

**Comment by Killerqu00** [comment]
okay, epic linter fail, got it

**Comment by lzk228** [comment]
imo it would be a big qol, like you can heal with brutepacks/ointment just with clicking, and when you need to cauterize you need to right-click then wait for server and only then click

**Comment by Plykiya** [comment]
stealth esword buff, now it actually causes lasting bleeding
it's in need of a buff anyways

**Comment by Plykiya** [comment]
> INSANE e-sword buff!!

the e-sword is getting the cauterization component, so unfortunately not

**Comment by Killerqu00** [comment]
okay. i am not exactly sure how to do the click interaction, but everything else is done

**Comment by lzk228** [comment]
> okay. i am not exactly sure how to do the click interaction, but everything else is done

you can check HealingSystem

**Comment by Killerqu00** [comment]
> > okay. i am not exactly sure how to do the click interaction, but everything else is done
> 
> you can check HealingSystem

it uses AfterInteractEvent, which does not seem to fire when I click people with a welder

**Pull request closed without merging**
