### PR TITLE
Nun Robes And Nurse Hat

### PR DESCRIPTION
**Pull request by KaiShibaa**
-Adds Nurse hat/To Medical Vendrobe
-Adds Nun Robes/To Chapel Vendrobe

### CODE REVIEW

**Comment by moonheart08** [comment]
I'm vetoing the nurse costume that's literally just erp spritework

**Comment by moonheart08** [comment]
fuck wrong button

**Review by moonheart08 — CHANGES_REQUESTED** [review]
No nurse costume for the love of god

**Comment by EmoGarbage404** [comment]
Very unepic

**Comment by KaiShibaa** [comment]
A shame. I used it a bit in a ss13 server just to see how it looks like and I personally didn't see an issue with it being much on ERP (aside from the descriptions which I did change) I'll edit them. Would the hat be fine to stay in at least?

**Comment by Just-a-Unity-Dev** [comment]
> I'm vetoing the nurse costume that's literally just erp spritework

rip [nurse](https://youtube.com/c/NurseVO)

**Comment by Kromabae** [comment]
that moment when i have been roleplaying a nun as chaplain >_>

**Pull request merged**
