### PR TITLE
the brainslug

### PR DESCRIPTION
**Pull request by kxvvv**
### todo:
- [x] jump action
- [x] infest
- [x] assume control
- [x] release control
- [x] dominate victim
- [ ] genes
- [ ] ui injection system
- [x] realease host
- [x] torment host
- [x] reproduce
- [x] shared chat between all slugs
- [ ] general chat between slug and carrier
- [ ] movement through vent
### other:
- [ ] surgical removal the slug
- [x] upload sprite better
- [ ] fix 🪲
- [ ] delete garbage
- [ ] touch the grass

**Media**

https://hackmd.io/@jBJBjkLqRFm0J5YsuURBbw/thebrainslug

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by moonheart08** [comment]
Design document needed.

**Comment by kxvvv** [comment]
> Design document needed.

after it's ready

**Comment by moonheart08** [comment]
> > Design document needed.
> 
> after it's ready

Yea, this is a bad idea considering as is the entire concept could in theory be rejected (as is I highly doubt we want borers unmodified from ss13). Write a design doc.

**Comment by kxvvv** [comment]
> > > Design document needed.
> > 
> > 
> > after it's ready
> 
> Yea, this is a bad idea considering as is the entire concept could in theory be rejected (as is I highly doubt we want borers unmodified from ss13). Write a design doc.

I'm doing this for the first time, is that right?
https://hackmd.io/@jBJBjkLqRFm0J5YsuURBbw/thebrainslug

**Comment by Interrobang01** [comment]
> I'm doing this for the first time, is that right?

Your design doc should also explore both the broad strokes behind the idea, and more importantly justification for adding this in the first place.

Keep the stuff that's already in there, it's good.

This guide to writing design docs should be helpful https://hackmd.io/@emogarbage404/rk0YvWo6o

**Comment by metalgearsloth** [comment]
How does someone remove the brain slug without surgery?

**Comment by Tynobeard** [comment]
> How does someone remove the brain slug without surgery?

It says on the very bottom of this, https://hackmd.io/@jBJBjkLqRFm0J5YsuURBbw/thebrainslug
That you just click on the carrier with a scalpel

**Pull request closed without merging**
