### PR TITLE
Atmos wallmount fix

### LINKED ISSUE #9468: Air Alarms are not recieving power from any source
Constructing air alarms, they are always 'unpowered' now and are not working.  Ran LV, MV, and HV wires under the wall piece to test and still no power.

Steps to Reproduce: Build an Air Alarm anywhere.

Tried to screenshot to save, will reproduce and update with a screenshot asap

### LINKED ISSUE #9664: Fire alarms showing as "unpowered" in examine menu, whilst having wires connected.
## Description

The title, but yeah, if you slap down an fire alarm and wire it with LVs it still shows as "unpowered" and doesn't do anything.
**Reproduction**

1. Make an fire alarm
2. Wire it with LVs
3. Watch as it doesn't alarm fire about it's non-existing demise

### PR DESCRIPTION
**Pull request by jproads**
## About the PR 
this bug is the sole reason I decided to contribute please give me mapped air alarms thx much love

Fixed numerous bugs regarding air alarms and fire alarms. They can now be placed on the map and constructed as intended: without them teleporting into the floor. Also now accepts power from APCs and extension cables as intended, closes #9468, closes #9664.
Added a threshold to Nitrous Oxide due to the update where slimepeople breathe it. Same level as CO2 thresholds, around 0.1 mol at atmospheric pressure.

Note: Fire alarms control all firelocks in the entire map, so they're still unusable right now.

**Screenshots**

Screen Shot 2022-08-01 at 2 32 12 AM

**Changelog**

:cl: Anthemic
- fix: Fixed air alarm and fire alarm crash.

### CODE REVIEW

**Comment by Mirino97** [comment]
Fix #10202

**Comment by jproads** [comment]
Merge conflict caused by #10279, reverted that change in this PR now.

**Comment by metalgearsloth** [comment]
Air alarms + fire alarms still aren't mappable because they have multiple bugs that need fixing (e.g. firelocks being global device network receivers as mentioned, air alarms not sensing correctly), this will just fix the crash until we delete the offset code and fix the internals. Adjust the changelog to say the crash is fixed rather than saying air alarms are fixed.

**Comment by jproads** [comment]
Changelog adjusted

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Needs updating since Enum pr

**Comment by mirrorcult** [comment]
this is superseded by flipp PR i believe

**Comment by metalgearsloth** [comment]
Superceded

**Pull request closed without merging**
