### PR TITLE
Make delay incurred from additional syringe contents modifiable + tiny syringe buff/fix

### PR DESCRIPTION
**Pull request by osjarw**
## Why / Balance
My next PR requires my new syringes to have both short doafter and a high transfer amount. 
With this change, the new prototype can be told not to do any delay scaling according to the transfer amount.

Also this PR contains a small fix/buff for syringes. 
According to #12173, the intent was to have each additional 5u cause a delay increase of 1 second. 
However, due to some bad math in #14441, and the fix for that calculation in #25890, the equation got left in a state where each 5u of the transfer amount was affected by the doafter delay increase, instead of only the additional doses being affected. 
Here's an illustration of the delays over those PRs:

|dose| 12173 | 14441 | 25890 | this pr|
|-----| ------------- | ------------- |--|--|
|5u| 0s | 0.5s |0.5s|0s|
|10u| 1s | 1.5s |1.0s|0.5s|
|15u| 2s | 2.5s |1.5s|1.0s|

## Technical details

Added `DelayPerVolume` datafield to the injectorComponent, which tells how the injection doAfter increases with the transfer amount.
Also moved the minimum delay check so negative `DelayPerVolume` can't get the delay under 1 second.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Syringes are now 0.5 seconds faster.

### CODE REVIEW

**Comment by Plykiya** [comment]
kind of strange to make an exception in the math for units under 5, feels like it'd be more simple to just adjust the do-after time to line up with the goal

**Comment by osjarw** [comment]
Yeah, kinda forgot about the possibility of transfer amount being < 5u... I guess I'll go and try to fix it then

**Comment by Plykiya** [comment]
> Yeah, kinda forgot about the possibility of transfer amount being < 5u... I guess I'll go and try to fix it then

the only reason I think about the non-standard values is because I'm a freak of a janitor that uses a syringe and a dead mouse body to clean up puddle spills, so I end up with weird units and decimals all the time, that's why I PR'd so many fixes the syringes lol

**Comment by osjarw** [comment]
Actually I don't really think it needs to be changed for amounts < 5u, since 5u is/was supposed to be the point for minimum amount of chems injected/drawn, and with this exception 5u matches exactly `Delay`.

**Review by ShadowCommander — CHANGES_REQUESTED** [review]
Should be fine. The default time is still 5 seconds. So 6 seconds with 15u.

Incapacitated would be 2 seconds and 2.4 seconds.

**Review by ShadowCommander — APPROVED** [review]

**Comment by Plykiya** [comment]
syringes my beloved

**Pull request merged**
