### PR TITLE
U-Shape Rails

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Adds U-shaped rails to the crafting menu and as a mapping option

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- add: Added U-shaped rails

### CODE REVIEW

**Comment by deltanedas** [comment]
sun microsystems

**Comment by metalgearsloth** [comment]
Anyone else have thoughts on 3 fixtures vs 1.

**Comment by Partmedia** [comment]
> Anyone else have thoughts on 3 fixtures vs 1.

Multiple fixtures would probably be better, but I don't think it's important enough to be blocking.

**Comment by metalgearsloth** [comment]
> > Anyone else have thoughts on 3 fixtures vs 1.
> 
> Multiple fixtures would probably be better, but I don't think it's important enough to be blocking.

I can write it out if we want it, should only take a few minutes.

**Comment by Alekshhh** [comment]
fixture hort my braon

**Pull request merged**
