### PR TITLE
Departmental ERT shuttles

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

- Adds 13 new shuttles to be used at admin's discretion. (Made with help of @luckyshotpictures )
  - NT-Ash (Base small-sized shuttle, to be populated in-round to fit the situation.) Base for:
    - NT-Penance (Sec shuttle, with one cell for two inmates and an inmate suppression system)
    - NT-Denobula (Med shuttle, if cloning is required the top three beds can be replaced on the fly)
    - NT-Hestia (Jani shuttle)
    - NT-Demiurge (Engineering shuttle, has basic repair materials)
    - NT-Achlys (CBURN shuttle, pretty basic, has two CBURN suits and two CBURN bags on board)
    - NT-Ares (DS shuttle, has an IFF computer that can enable full stealth)
  - NT-Phoenix (Base medium-sized general-purpose shuttle, to be populated in-round to fit the situation.) Base for:
    - NT-Hephaestus (Engineering shuttle with a jani compartment. Essentially cleanup crew.)
    - NT-Asclepius (Medical medium-sized shuttle, has a cloning setup and dedicated chemistry)
    - NT-Salus (Security shuttle, basically a flying brig)
  - NT-Chimaera (Large-sized shuttle, to be populated.) Base for:
    - NT-Hygieia (Combines the NT-Asclepius and the NT-Salus into one big shuttle.)

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

NT-Ash (left) and NT-Hestia (right):
image

NT-Denobula (left) and NT-Penance (right):
image

NT-Ares (left) and NT-Achlys (right):
image

NT-Demiurge:
image

NT-Phoenix:
image

NT-Hephaestus:
image

NT-Asclepius:
image

NT-Salus:
image

NT-Chimaera:
image

NT-Hygieia:
image

**Changelog**

admin-only change, no cl

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
Currently atmos on most of these shuttles is fucked. We forgot to run `fixgridatmos`. This will come soon.

**Comment by UbaserB** [comment]
why is the NT phoenix so empty

**Comment by TsjipTsjip** [comment]
> why is the NT phoenix so empty

It is a base shuttle to be populated in-round by the admin spawning it to fit a specific situation, just like the NT Ash.

**Comment by UbaserB** [comment]
> > why is the NT phoenix so empty
> 
> It is a base shuttle to be populated in-round by the admin spawning it to fit a specific situation, just like the NT Ash.

ok

**Comment by LankLTE** [comment]
Admin-only changes like this don’t need a CL.

**Comment by TsjipTsjip** [comment]
> Admin-only changes like this don’t need a CL.

Updated to match requested change.

**Comment by Endecc** [comment]
Any interest for an Engineering ERT shuttle, as well? I can imagine a version pre-stocked with construction materials, air scrubbers, and some large atmos tanks being useful for emergency repairs and atmos patching.

**Comment by TsjipTsjip** [comment]
> Any interest for an Engineering ERT shuttle, as well? I can imagine a version pre-stocked with construction materials, air scrubbers, and some large atmos tanks being useful for emergency repairs and atmos patching.

We were planning to do this using the NT Phoenix as a base, it would be called the NT Hephaestus. This shuttle would also include a small janitor compartment, as these are often sent together after a repelled nukies attack, ... . That sort of thing.

**Comment by TsjipTsjip** [comment]
Pull request is now ready for full review.

**Comment by TsjipTsjip** [comment]
DS loadout lockers may need to be updated in line with #21230 .

**Comment by TsjipTsjip** [comment]
DS loadout lockers likely got broken by the test-merge of slot-based storage. Investigating as per usual, if found to be broken, a fix will be applied soon.

**Comment by Suggestedone9** [comment]
The Denobula could potentially do with having a cell recharger for the defib should the defib run out and the station doesn't have any readily available

**Comment by TsjipTsjip** [comment]
Revival, couple new shuttles added.


> The Denobula could potentially do with having a cell recharger for the defib should the defib run out and the station doesn't have any readily available

The NT-Denobula has received a cell recharger.

**Comment by TsjipTsjip** [comment]
Closing in favor of moving this PR to the admin repo, as discussed (here)[https://discord.com/channels/310555209753690112/771041304108072961/1170281507332571237]

**Comment by IProduceWidgets** [comment]
I know this was closed, but as a note, the shuttles don't have waste gas which will lead to deaths.

**Comment by TsjipTsjip** [comment]
> I know this was closed, but as a note, the shuttles don't have waste gas which will lead to deaths.
> 
> Its usually more of an issue on the small shuttles than the big ones. Small rooms can cause this problem too however.
> 
> The normal cargo shuttle doesn't have have waste gas, but this is because its funny to make cargo have to deal with gas buildup. As for the salv shuttle, well...

It is not required for shuttles to have waste gas systems as per the mapping guidelines for shuttles. This is as one would consider "extra". No evac shuttles have this either. Nevertheless, the large class shuttles do have their own waste disposal system.

**Comment by IProduceWidgets** [comment]
Yeah, I don't think its listed because some shuttles don't need them, but the sec shuttle with the NO2 system for instance, would be a hard time without one I think.

Do you mind if I use these? I'll probably make some minor adjustments.

**Comment by TsjipTsjip** [comment]
Go ahead! They're open-source contributions!

**Pull request closed without merging**
