### PR TITLE
vehicles cannot be shot anymore

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
1. doesnt make any sense
2. wheelchair/atv/unicycle should never block shots from lasers smgs disablers etc

addresses disabler part of #18874, they can actually hit the rider now

**Media**
they still collide with walls dunno if any other behaviour is required

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by mirrorcult** [comment]
feel like this should only be the case if there's a person on the vehicle

**Comment by deltanedas** [comment]
then you can get off a vehicle and use it as a shield which is also shitty, you arent somehow hiding under it so it doesnt make sense that you cant get shot

**Comment by mirrorcult** [comment]
yeah fair enough

**Comment by metalgearsloth** [comment]
If someone's on a vehicle they can still be hit though right?

**Comment by deltanedas** [comment]
yes thats the whole point, vehicles were tanking disabler and laser shots to and from the user

**Pull request merged**
