### PR TITLE
Goon floor pack 1

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Started porting some more floors. Have approximately 35 to do in total and that's without all the variations once placementmanager is refactored.

Going to do it piecemeal so maintainers have an option to reject and also because my time is few and far between and it'll be awhile before I can get through them all. So without further ado...This pack contains:

- Clown Carpet
- Metal diamond embossed tiles
- Office Carpet
- Gym matt
- Boxing Ring
- Blue Arcade alternative tile

These names aren't exactly how they are in game but are a good descriptor for Github.

**Screenshots**

flooring

Now includes tile variants for boxing and gym.

flooring 2

**Changelog**

:cl:
- add: Added 6 new floor tiles ported from Goon! Look out for clown carpet, boxing ring, gym mat, office carpet, metal diamond and alternate blue arcade.

### CODE REVIEW

**Comment by moonheart08** [comment]
Gym and boxing could do with having variant textures made if possible (see how the major floortiles work)

**Comment by Peptide90** [comment]
> Gym and boxing could do with having variant textures made if possible (see how the major floortiles work)

Will look to do that when I next get a chance to look at this, same for the office carpet.

Will do it in future for the other floors too.

**Comment by Peptide90** [comment]
> Gym and boxing could do with having variant textures made if possible (see how the major floortiles work)

Done, attached screenshot above. Was going to go for a more flat colour than it looking like a 4 square tile (as they do by default) but backed off and went back to that look.

**Comment by ZeWaka** [comment]
you could've at least asked

**Pull request merged**
