### PR TITLE
ya realno frik

### PR DESCRIPTION
**Pull request by ogg1t**
ya frik.. eto ne rofl

### CODE REVIEW

**Comment by metalgearsloth** [comment]
What are these words sorcerer

**Comment by deltanedas** [comment]
terrorist deletes the readme demanding a helicopter and $50 cash

**Comment by ogg1t** [comment]
da.

**Comment by NoElkaTheGod** [comment]
> What are these words sorcerer

Not sure why would you need this information, but this translates to "I am really a freak" and "i am a freak... this is not a joke".

**Pull request closed without merging**
