### PR TITLE
Let Lizards Weh

### PR DESCRIPTION
**Pull request by noctyrnal**
## About the PR

gives lizards the ability to weh

## Why / Balance

it is absolutely vital to the game balance that lizards can weh

## Technical details

N/A

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/99278536/5b61fc1d-29d0-4f4e-ac0a-22c6e14c1a27

## Breaking changes

N/A

**Changelog**

🆑
- add: Lizards can now Weh

### CODE REVIEW

**Comment by Simyon264** [comment]
While this is great, people WILL spam it. There needs to be some kind of cooldown.

**Comment by noctyrnal** [comment]
> While this is great, people WILL spam it. There needs to be some kind of cooldown.

Would that require a general implementation of emote cooldowns or is there already a pre-existing system used by other emotes?

**Comment by Hmeister-real** [comment]
> > While this is great, people WILL spam it. There needs to be some kind of cooldown.
> 
> Would that require a general implementation of emote cooldowns or is there already a pre-existing system used by other emotes?

You could either implement it as an emote command, like tail wagging and screaming, or you could implement a whole new system that forces cooldowns on spoken emotes to prevent spam of all emotes.

**Comment by K-Dynamic** [comment]
> While this is great, people WILL spam it. There needs to be some kind of cooldown.

You can spam scream or cough but I've personally only seen that a few times

**Comment by noctyrnal** [comment]
Ill leave it as is, considering you can spam every emote already, so a seperate PR with an emote cooldown system on a whole would be better for that.

**Comment by QuietlyWhisper** [comment]
Leave it on weh juice only it's funnier...

**Comment by QuietlyWhisper** [comment]
Also if you wanted to do this, add on to the existing weh; no need to make a new one just add the chat triggers

**Comment by noctyrnal** [comment]
Ah right, I originally did that but I assumed it existed for weh juice so I didnt want to remove it in fear it'd ruin weh juice my beloved.

**Comment by AlexUmAndXGabriel08X** [comment]
i worked on lizard weh thing kind of a lot, and what i can see there that other species will not be able to weh with weh juice. In the commit called "reduce wehs" author removed all wehs from all species, so the juice will not work. It sure has to be fixed in one or other way. You can see my solution to this in this pr: https://github.com/space-wizards/space-station-14/pull/26415 (it is closed)

**Comment by noctyrnal** [comment]
> i worked on lizard weh thing kind of a lot, and what i can see there that other species will not be able to weh with weh juice. In the commit called "reduce wehs" author removed all wehs from all species, so the juice will not work. It sure has to be fixed in one or other way. You can see my solution to this in this pr: #26415 (it is closed)

Yah, thats why I originally made them seperate emotes, though Whisper said to add onto the existing weh so I did it like that. I can revert the commit if it actually prevents weh juice from working.

**Comment by AlexUmAndXGabriel08X** [comment]
i don't see real solution how you can make it in one collection when you want to keep juice working on everyone and let lizards weh with chat. Metalgearsloth told me the same thing, it was the reason my first pr with wehs was closed. I guess it's just us (sorry for honesty) being slightly dumb and missing one particular thing, or them misunderstanding our intentions with these prs.

**Comment by noctyrnal** [comment]
The age old classic of it is what it is.

**Pull request closed without merging**
