### PR TITLE
Fixes gravity wells

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

I don't know why it works, god bless matrixes
Apparently it was an issue with order of arguments

## Why / Balance

Fixes https://github.com/space-wizards/space-station-14/issues/29610 and https://github.com/space-wizards/space-station-14/issues/28608

## Technical details

https://github.com/space-wizards/space-station-14/pull/27443 this PR changed the formula from
```
         => GravPulse(mapPos, maxRange, minRange, new Matrix3(
            baseRadialDeltaV, +baseTangentialDeltaV, 0.0f,
            -baseTangentialDeltaV, baseRadialDeltaV, 0.0f,
            0.0f, 0.0f, 1.0f
```

to

```
       => GravPulse(mapPos, maxRange, minRange, new Matrix3x2(
            baseRadialDeltaV, -baseTangentialDeltaV, 0.0f,
            +baseTangentialDeltaV, baseRadialDeltaV, 0.0f
```

and then thanks to @slarticodefast this formula actually works...

```
=> GravPulse(mapPos, maxRange, minRange, new Matrix3x2(
baseRadialDeltaV, -baseTangentialDeltaV, baseTangentialDeltaV,
baseRadialDeltaV, 0.0f, 0.0f));
```

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/2db655b5-c371-4c12-a5e5-e3918c33071d

**Changelog**

:cl:
- fix: Gravity wells, like the supermatter grenade, now function properly again.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
it seems like this calculation broke on the switch to `System.Numerics.Matrix3x2`. I think the cause of that was that the previous Matrix3 had some broken calculations. You should look into what was broken and just reverse engineer from there. Just removing the calculation altogether seems silly since it's obviously important to how the gravity well works.

**Comment by Plykiya** [comment]
> it seems like this calculation broke on the switch to `System.Numerics.Matrix3x2`. I think the cause of that was that the previous Matrix3 had some broken calculations. You should look into what was broken and just reverse engineer from there. Just removing the calculation altogether seems silly since it's obviously important to how the gravity well works.

I mean, I didn't erase the calculation entirely but...
there are only two possible functions in Vector2 that make use of a Vector and a Matrix
Transform, and TransformNormal
I tried both, both were broken

**Comment by Plykiya** [comment]
so this is the old calculation

```
       public static void Transform(in Vector2 vector, in Matrix3 matrix, out Vector2 result)
        {
            result.X = (vector.X * matrix.R0C0) + (vector.Y * matrix.R1C0) + (matrix.R2C0);
            result.Y = (vector.X * matrix.R0C1) + (vector.Y * matrix.R1C1) + (matrix.R2C1);
        }
```

and this is the new calculation
```
         [MethodImpl(MethodImplOptions.AggressiveInlining)]
         internal static Vector2 Transform(Vector2 position, in Matrix3x2.Impl matrix)
         {
             Vector2 result = matrix.X * position.X;
 
             result += matrix.Y * position.Y;
             result += matrix.Z;
 
             return result;
         }
```
the main difference is that it seems to be assigning the same value to the X and the Y rather than having them as separate things
but like

how do I even... address that without just adding the calculation in as it was before

**Comment by Plykiya** [comment]
maybe @eoineoineoin can chime in if they're still around

**Comment by slarticodefast** [comment]
>the main difference is that it seems to be assigning the same value to the X and the Y in the new calculation rather than having them as separate things

Both of these are doing exactly the same thing. Doing a linear transformation by multiplying with a 2x2 matrix, then a translation. Did the gravity well break with the matrix change or before? If you can point me to the PR where it broke I can have a look at the math.

**Comment by Plykiya** [comment]
@slarticodefast I used git blame to check the history of updates to GravityWell
GravityWell broke a month ago, the only PR that has touched GravityWells in like an entire year was the switch from Matrix3 to Matrix3x2

**Comment by slarticodefast** [comment]
grafik

I think this part is at fault, not the transform. The constructor calls has the matrix elements in the wrong order. Give me a moment to make a code suggestion. Would be great if you could test for me if that works.

**Comment by slarticodefast** [comment]
Ok, seems like GitHub does not let me comment on lines you did not change. In line 222 please try out
`GravPulse(mapPos, maxRange, minRange, new Matrix3x2(
            baseRadialDeltaV, -baseTangentialDeltaV,
            baseTangentialDeltaV, baseRadialDeltaV,
            0.0f, 0.0f
        ));`

Undo your change in line 209.

**Comment by Plykiya** [comment]
> Ok, seems like GitHub does not let me comment on lines you did not change. In line 222 please try out `GravPulse(mapPos, maxRange, minRange, new Matrix3x2( baseRadialDeltaV, -baseTangentialDeltaV, baseTangentialDeltaV, baseRadialDeltaV, 0.0f, 0.0f ));`
> 
> Undo your change in line 209.

oh that totally fixed it

**Comment by eoineoineoin** [comment]
I can try to take a look this evening or tomorrow evening if it's still a problem, but it sounds like you've got it. Looks like I just made a mistake when transposing the matrix ctor arguments.

Also minor nit that the ApplyLinearImpulse() input should probably use Vector2.TransformNormal(), since it doesn't a homogeneous coordinate (though, it doesn't make a difference in this case since the matrix has zero translation.)

**Comment by slarticodefast** [comment]
Yeah, the entries for the rotation/scaling matrix got mixed up with the translation entries in the constructor. The translation entries are supposed to be zero. Should be fixed now. The distance scaling is done in the scaling factor by dividing with scaling2. Like you said, this could be done by normalizing the vector instead, but does not really make a difference.

**Comment by Plykiya** [comment]
> Also minor nit that the ApplyLinearImpulse() input should probably use Vector2.TransformNormal(), since it doesn't transform a homogeneous coordinate (though, it doesn't make a difference in this case since the matrix has zero translation.)

done, all good

**Comment by slarticodefast** [comment]
>done, all good
 Wait, now you have changed how it scales with the distance from the well.

**Comment by slarticodefast** [comment]
Oh nevermind, I am stupid. I thought it would normalize the vector. The nitpick was correct, the translation is zero and therefore not needed. My bad, please reapply the nitpick change.

**Comment by Plykiya** [comment]
oh it's so joever, I committed the robust toolbox file on accident

**Pull request merged**
