### PR TITLE
Cheaper borgs

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

borg parts are cheaper
MMIs and positron brains no longer need silver (might make them cost some plasma)

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- tweak: Science no longer needs to beg salvage for THA FAKN SEEELLLVVAAAAHHH

### CODE REVIEW

**Comment by Emisse** [comment]
i dont like this, posi brains are supposed to be hard to build

**Comment by JoeHammad1844** [comment]
ill increase it then

**Comment by JoeHammad1844** [comment]
more plasma?

**Comment by LankLTE** [comment]
honestly i wouldn't touch it, borgs being so expensive is only a problem rn because there are no roundstart borgs and people want to make 30 of them because they're new

**Comment by JoeHammad1844** [comment]
thats a good point, but just one borg just sucks up so many materials

**Comment by coolmankid12345** [comment]
Tell Sci to upgrade their machines, would probably help a lot

**Comment by JoeHammad1844** [comment]
hmm ill make the limbs 200

**Comment by LankLTE** [comment]
> Tell Sci to upgrade their machines, would probably help a lot

Bold of you to assume sci is getting any amount of research before printing 10 Borgs

**Comment by coolmankid12345** [comment]
> Bold of you to assume sci is getting any amount of research before printing 10 Borgs

One could hope

**Comment by JoeHammad1844** [comment]
the limbs should not cost glass

**Comment by JoeHammad1844** [comment]
hm

**Comment by JoeHammad1844** [comment]
image
hm

**Comment by metalgearsloth** [comment]
I'm also not a fan, making this only cost steel / glass just makes them spammable via cargo and gas selling.

**Comment by JoeHammad1844** [comment]
its been 45 minutes, I dont think enough discussion has been had for it to be closed

**Comment by metalgearsloth** [comment]
2 maintainers weighed in, I wouldn't think we need 3+ for something that's been in for 12 hours.

**Comment by JoeHammad1844** [comment]
two isn't a crowd. and emisse was specifically talking about positron brains

**Comment by JoeHammad1844** [comment]
> I'm also not a fan, making this only cost steel / glass just makes them spammable via cargo and gas selling.

you can't buy silver, it has to be mined

**Comment by Emisse** [comment]
yes thats the point

**Pull request closed without merging**
