### PR TITLE
make morgues only beep with living bodies

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

previously, a fully dead body with a ghost occupying it would beep in a morgue.
This was very inconsistent, as the player going into a ghost would stop the behavior.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Morgues will no longer sometimes beep when dead bodies are placed inside of them.

### CODE REVIEW

**Comment by deltanedas** [comment]
you cant place a living person in a morgue so this is extremely niche when going from dead->living inside the morgue

**Comment by EmoGarbage404** [comment]
> you cant place a living person in a morgue so this is extremely niche when going from dead->living inside the morgue

you can place a crit person inside a morgue.

**Comment by Aisu9** [comment]
i mean this give MDs a hint that a body may be recoverable if someone with lack of knowledge/traitor try to stash them in

**Comment by Arendian** [comment]
I think the alert was there to alert people that the person inside could still be cloned, with round start cloning gone maybe it should only beep if a person that can still be defibbed is inside.

**Comment by EmoGarbage404** [comment]
> I think the alert was there to alert people that the person inside could still be cloned, with round start cloning gone maybe it should only beep if a person that can still be defibbed is inside.

i mean, if that was the intent, then it didn't work properly. It makes more sense that the flashing green light with a beep means "oh shit the dude in here is alive," Just because someone can theoretically be cloned doesn't mean it should be actively beeping at me.

**Comment by Arendian** [comment]
> i mean, if that was the intent, then it didn't work properly. It makes more sense that the flashing green light with a beep means "oh shit the dude in here is alive," Just because someone can theoretically be cloned doesn't mean it should be actively beeping at me.

From what I remember  it was added because too many new doctors were just putting dead bodies into the morgue instead of cloning them. 
Why it only beeped if there was a ghost inside was so it wouldn't just infinitely beep if for example the cloners were destroyed or power was out and the bodies were put into the morgue so they wouldn't accumulate cellular damage.
The ghosted people would then return to the body once they saw that cloning got fixed to remind the doctors that they were still cloneable.

**Comment by EmoGarbage404** [comment]
That seems pretty damn hard to understand and conceptualize rather than simply "green means alive"

**Comment by Arendian** [comment]
> That seems pretty damn hard to understand and conceptualize rather than simply "green means alive"

Just making it beep if a corpse is not rotting and still has a ghost floating around(not specifically inside the body) could make it: "green means fresh body with soul detected". 
I think the  biomass reclaimer already checks for the soul thing by not allowing you to grind people that are still in the game as a ghost.

**Comment by deltanedas** [comment]
> Just making it beep if a corpse is not rotting and still has a ghost floating around

doesnt account for say 200 poison that cant be healed without cloner, beeping would incentivise players to at best put them in bodybags and at worst let them rot

**Comment by deltanedas** [comment]
> Just making it beep if a corpse is not rotting and still has a ghost floating around

doesnt account for say 200 poison that cant be healed without cloner, beeping would incentivise players to at best put them in bodybags and at worst let them rot

**Comment by SEMoslaw** [comment]
It was the same in SS13 when green beeping meant there is a person waiting to be cloned. I never seen anyone placing the live person into the morgue, I'm not even sure if you can. I don't think it really is confusing the way it is right now but might be a bit annoying when we cannot clone someone but the alarm is going off. Changing this feature would really be a downgrade in my humble opinion from what we have right now.

If anything I would add option to manually "silence" the alarm if someone cannot be cloned at the moment.

**Comment by NateF1** [comment]
Make the beep quieter or a different sound that's less annoying but still noticable so that players who _want_ to be cloned will still be remembered.  Keep in mind that they couldn't be ghosted and had to sit there and look at their dead body while they wait.  Most people just give up and take a ghost role after a while anyway.

**Comment by potato1234x** [comment]
ive been saved by the beeping when i was mistakenly put into morgue when my body was rotted 10% and the meds just stopped trying. without it i wouldnt've been cloned

**Comment by UbaserB** [comment]
> ive been saved by the beeping when i was mistakenly put into morgue when my body was rotted 10% and the meds just stopped trying. without it i wouldnt've been cloned

rotted 10%..?

**Comment by potato1234x** [comment]
> > ive been saved by the beeping when i was mistakenly put into morgue when my body was rotted 10% and the meds just stopped trying. without it i wouldnt've been cloned
> 
> rotted 10%..?

yeah they tried to clone me once and gave up

**Comment by keronshb** [comment]
> That seems pretty damn hard to understand and conceptualize rather than simply "green means alive"

In SS13 the beep & colorchange was put there to show that the mind is occupied. So revival should be attempted or something similar.

**Pull request closed without merging**
