### PR TITLE
Make pills require biomass to produce

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

ChemMaster now requires biomass to produce pills (1 biomass per pill).
Why: to stop chems from making unhealthy amount of pills and instead use bottles and other solutions to heal people.

~~realism~~
image

**Media**

Peek 2023-01-30 12-00

**Changelog**

:cl:
- tweak: Pills require biomass to produce (1 to 1) in ChemMaster.

### CODE REVIEW

**Comment by Emisse** [comment]
hardcore mode

**Comment by Emisse** [comment]
also realistically biomass might need a secondary source of being obtained for this to reasonably go through due to player skissue

**Comment by Slava0135** [comment]
> also realistically biomass might need a secondary source of being obtained for this to reasonably go through due to player skissue

Maybe plant source even? Like compost.

**Comment by Slava0135** [comment]
image

**Comment by metalgearsloth** [comment]
Is there a design doc for all the changes you intend to make.

**Comment by Emisse** [comment]
please make a design doc smiley face emoji exclamation point

**Comment by Slava0135** [comment]
> please make a design doc smiley face emoji exclamation point

Do we use hackmd.io for this? I don't have access tho.

**Comment by AlexMorgan3817** [comment]
Add in UI meter of biomass, it will be more fancy

**Comment by arealbeba** [comment]
why. this sucks.

**Comment by EmoGarbage404** [comment]
This is basically a poor solution to the widespread ghetto chem rework that is planned. As outlined in various issues, chems should be obtainable by various means through different departments. This implementation has quite a few core issues with how it works.

1. Biomass isn't something that can be acquired from multiple places. The only way to get biomass is from reclaiming bodies, which departments can't actually supply (besides cargo, but cargo can supply anything). This means that chems becomes like cloning: linked directly to the amount of death on station. This doesn't work for cloning though, because chemicals are meant to be for living players, and thus shouldn't be tied to the amount of dead ones.

2. All chemicals are equal in supply. This doesn't solve the issue of chemical supply other than putting a hard limit. Individual chemicals are still of equal rarity, which makes recipes difficult to balance.

3. This exacerbates the nullification of body management. Current cloning and biomass gameplay already makes morgue and body storage irrelevant; this only makes it worse.

**Comment by metalgearsloth** [comment]
Maybe making a separate replenishable resource, e.g. a box of 50 pill capsules from cargo, would be good to prevent pill spam but not actively discouraging any pill use.

**Comment by Slava0135** [comment]
I guess you made good points I will wait until rework.

**Comment by Emisse** [comment]
not entirely opposed to this, i just think it needs to be bundled with more biomass options/pill options to not be horrifically punishing to the playerbase atm. please dont abandon the idea because of response to initial pr i think its got a good direction

**Comment by Slava0135** [comment]
> not entirely opposed to this, i just think it needs to be bundled with more biomass options/pill options to not be horrifically punishing to the playerbase atm. please dont abandon the idea because of response to initial pr i think its got a good direction

Yeah we need Biogenerator first as other source of biomass

**Comment by Slava0135** [comment]
The most insane thing about pills for me is that you can put up to 50u of chems. Note that a cup holds 20u so average pill should be the size of cup???

**Comment by metalgearsloth** [comment]
In this case it's just the pills so the delivery method of chems, without touching the chems themselves.

**Comment by EmoGarbage404** [comment]
> In this case it's just the pills so the delivery method of chems, without touching the chems themselves.

What? What's even the point then? You're just locking a basic convenience feature behind a material requirement. People are just going to leave the chemicals out on the counter. If pills are too strong right now, just make them hold less chems.

**Comment by Cheackraze** [comment]
> > In this case it's just the pills so the delivery method of chems, without touching the chems themselves.
> 
> What? What's even the point then? You're just locking a basic convenience feature behind a material requirement. People are just going to leave the chemicals out on the counter. If pills are too strong right now, just make them hold less chems.

Then can we remove the glass requirement to make bottles please for the love of God I want to play doctor again but it's impossible with pill meta of 500 pills made for free sitting on the chemist counter

**Comment by mirrorcult** [comment]
i think this is a good concept if we have 1 or 2 more sources of biomass

**Comment by Slava0135** [comment]
> > Then can we remove the glass requirement to make bottles please for the love of God I want to play doctor again but it's impossible with pill meta of 500 pills made for free sitting on the chemist counter
> 
> Second this, whenever I play CMO my hypospray is effectively useless because my chemists will either ignore or outright deny my requests for bottled chems, and I don’t blame them since most chem labs only are stocked with a total of _twelve_ glass bottles

You can make chems by yourself but I feel the same.

Also bottles have only 30u outclassed by drinking glass with 50u (and you can get 30 from bar). Imo they should have more capacity.

**Pull request closed without merging**
