### PR TITLE
Meta Station

### PR DESCRIPTION
**Pull request by Emisse**
You knew it was coming. Midpop map featuring similar design language as box/delta. Taken inspiration from many forms of Meta over the years for this with a lot of my own ideas as well. I hope you enjoy. Here's some screenshots. Using singulo setup instead of SME because SME is not implemented yet and tesla is on the horizon. 
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
she actually did it

**Comment by metalgearsloth** [comment]
Rotate another map out too?

**Comment by Emisse** [comment]
Barratry was rotated out today

**Comment by metalgearsloth** [comment]
Yeah but was anything rotated out for box

**Comment by Emisse** [comment]
Waystation went out and Box went in

**Comment by mirrorcult** [comment]
i'm planning on maintaning barratry and eventually rotating that back in

**Comment by Emisse** [comment]
id make the argument to rotate out delta then, since its meant for a much larger amount of players we rarely hit and meta is generally more liked

**Comment by mirrorcult** [comment]
i'm okay with that

**Comment by moonheart08** [comment]
Rotating out Delta sgtm.

**Comment by ike709** [comment]
best map time

**Comment by moonheart08** [comment]
metastation-0

**Comment by metalgearsloth** [comment]
Shuttle should have like 2 thrusters, also I didn't see a gyroscope.

**Comment by Emisse** [comment]
thats the arrivals shuttle its not real

**Pull request merged**
