### PR TITLE
Altars add

### PR DESCRIPTION
**Pull request by Deahaka**
## About the PR 
No more wooden table in chapel!!!

(
Q: Why no mechanic?
A: Roleplay ̿̿ ̿̿ ̿'̿'\\з= ( ▀ ͜͞ʖ▀) =ε//’̿’̿ ̿ ̿̿ ̿̿ ̿̿
Q: literally who?
A: [Theta Community](https://github.com/ThetaStation/ThetaStation).
)
**Screenshots**

**Changelog**

:cl: Deahaka
- add: Altars added

### CODE REVIEW

**Comment by Deahaka** [comment]
oh i forgot something
Look:

**Review by mirrorcult — CHANGES_REQUESTED** [review]
- imperium & neotheology altars need removed
- nanotransen should be renamed to nanotrasen
- lowercase all the names of the altars ("nanotrasen altar" -> "nanotrasen altar")
- add a random spawner for altars that picks one of the ones here, so that mappers can use them immediately

otherwise these all look good and polished

**Comment by lapatison** [comment]
Could you also localize altar names?

**Comment by Deahaka** [comment]
> Could you also localize altar names?

show what you mean, please.

**Comment by mirrorcult** [comment]
these dont need to be localized

**Comment by lapatison** [comment]
Got it, my bad. Comment deleted.

**Comment by Deahaka** [comment]
* Done

**Review by mirrorcult — CHANGES_REQUESTED** [review]
should have reviewed earlier but IMO all of the ones which share the same 'lightning' effect (the wood altars, yellow one) at the very least should all be in the same RSI so that sprite doesn't have to be duplicated multiple times

**Comment by moonheart08** [comment]
> should have reviewed earlier but IMO all of the ones which share the same 'lightning' effect (the wood altars, yellow one) at the very least should all be in the same RSI so that sprite doesn't have to be duplicated multiple times

I'll note the duplication has next to no cost due to manifests, but yes this needs to be fixed.

**Comment by Deahaka** [comment]
Reorganize complete. Duplacation are gone.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
