### PR TITLE
remove IDCARD dependency on jumpsuit

### PR DESCRIPTION
**Pull request by justinbrick**
## About the PR

In the YAML files for all creatures that can hold a PDA, I removed IDCARD slots' dependency on the jumpsuit slot.

## Why / Balance

as mentioned in issue #28604, one potential noob-trap mechanic is losing your PDA when you switch your jumpsuit. this causes the PDA to be unequipped, and might be forgotten & left behind. this aims to resolve the issue by removing the need for a jumpsuit to carry your PDA

## Technical details

YAML file changes

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- tweak: Players no longer drop their PDA upon unequipping their jumpsuit.

### CODE REVIEW

**Comment by beck-thompson** [comment]
Baby tiders rejoice! No more forgetting your PDA in the middle of the hallway 😆

**Comment by lzk228** [comment]
its not the best solution...

**Comment by EmoGarbage404** [comment]
This doesnt really fix the problem. The issue is that swapping clothing still raises the events for unequipping, causing your items to drop. This technically resolves that for IDs but the behavior still happens with pockets and any other slot dependencies that may exist in the future.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
^

**Comment by ShadowCommander** [comment]
The other thing is that the item dropping gives a downside to using disguises. I'm not completely sure that's needed, but that's the effect that items dropping on uniform change has.

**Comment by ElPidor** [comment]
de fak, 
Noobs must learn and overcome their mistakes, its kinda lazy solution 
If you REALLY into "solving" this _problem_ just make +1 slot for pda special, or... 
just make a guide for beginers?
Anyway its not a problem and it doesnt require solution because its just 
SKILL ISSUE

**Comment by SlamBamActionman** [comment]
> de fak, Noobs must learn and overcome their mistakes, its kinda lazy solution If you REALLY into "solving" this _problem_ just make +1 slot for pda special, or... just make a guide for beginers? Anyway its not a problem and it doesnt require solution because its just SKILL ISSUE

Knowing that your PDA drops when changing clothes is a skill? That sure has a high skill ceiling...

I agree that for experienced players the real hindrance is that you can't quick-swap jumpsuit while running, which is good to prevent instant disguises. The issue for new players is knowing it drops to begin with.

**Comment by Plykiya** [comment]
as discussed on discord, ideally there'll be a do-after when swapping between clothing with content in its specific storage slots

**Comment by PJB3005** [comment]
Sticking the ID card pin directly into my flesh now that I can wear it without a jumpsuit.

**Comment by deltanedas** [comment]
> Sticking the ID card pin directly into my flesh now that I can wear it without a jumpsuit.


you can do this with belt slot it just doesnt provide access

**Comment by mirrorcult** [comment]
bro have you ever worn a belt before

**Comment by mirrorcult** [comment]
you dont stick the belt into your flesh

**Comment by deltanedas** [comment]
you can wear pda completely naked as a belt on belt slot

**Comment by mirrorcult** [comment]
spaceman technique

**Comment by BolloTea** [comment]
This is really not a problem and does not require fixing.  If a player doesn’t keep track of his things, it’s his fault, such is life.  What if next time he doesn’t keep track of the singularity?  Will you send her too so she doesn’t run away?  Sorry for the surprise, but this is roughly how it looks from the outside.

**Comment by ElPidor** [comment]
Side note, why not to spawn pda in belt slot so if people change their clothes nothing would drop down? 
Or seperate PDA anad ID card so if a person left an id card they can go to hop and get a new one.

**Comment by superjj18** [comment]
Based change.  SS14’s advantage over SS13 is being new player friendly, and this is a noob friendly change with pretty much zero genuine reasons to be against it other than old players wanting to spite normies which is cringe.  This ain’t skill issue, your characters should be smart enough to switch the contents of their clothing.

It it were up to me id make it so all pockets, jackets, and other such clothing dependent item slots autoswitch to new clothing

**Comment by metalgearsloth** [comment]
Discussed internally and thoughts remain the same.

**Comment by justinbrick** [comment]
> Based change. SS14’s advantage over SS13 is being new player friendly, and this is a noob friendly change with pretty much zero genuine reasons to be against it other than old players wanting to spite normies which is cringe. This ain’t skill issue, your characters should be smart enough to switch the contents of their clothing.
> 
> It it were up to me id make it so all pockets, jackets, and other such clothing dependent item slots autoswitch to new clothing

There are some potential flaws with the change that broke general flow of gameplay - a lot of times the simplest option is likely the wrong one. There were some efforts to create a swapping system, which I had planned to take, but due to a lack of personal time, I had to drop it. It is likely there will be something underway in the near future which will make this more beginner friendly, but I agree with the sentiment that this particular change is not the right one.

I did, however, create PR #28722 which does somewhat address the issue, however it only does it by creating a notification. This has fallen under the radar I believe, or it is still under review, which one it is, I am uncertain, as I really have not had time to hop in discord and check either. If you want to pursue that, I'd recommend mentioning it in discord.

**Pull request closed without merging**
