### PR TITLE
Space damage now causes heat along with blunt

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Space burns your skin from the ionizing radiation and intense light. Also, your blood boils. Radiation would be too difficult to implement and generally not a good idea, so i decided to just do burn. The reason why it's under barotrauma instead of general space damage is because even if you're not in space your blood still boils from lack of pressure (aka barotrauma)

Makes space a tiny teensy little bit more dangerous by 0.5 damage increase per second along with making treatment more complex considering there is another added damage type.

image

**Changelog**

:cl: Ubaser
- tweak: Unpressurized areas now deal heat damage along with blunt.

### CODE REVIEW

**Comment by asperger-sind** [comment]
The different damage type is fine, but I really don't think space needs more damage as it's already stupidly strong for how easy it is to space areas and take advantage of it.

**Comment by K-Dynamic** [comment]
https://www.washingtonpost.com/national/health-science/your-body-in-a-vacuum-and-the-philosophy-of-chemistry/2012/01/31/gIQArw83BR_story.html 

https://youtu.be/GXAOT8UUN3A?si=Ly61c9TxAmDijQUg

Blood boiling inside body isn't really a thing

Even if blood boiling idea is implemented, heat damaged would need to be capped since all the liquids would turn to gas and leave

**Comment by Kadeo64** [comment]
space damage buffed someone bring up space pens again

**Comment by EmoGarbage404** [comment]
@Kadeo64 if you're not going to meaningfully contribute to discussions, save yourself looking like a fool and stop vomiting words that carry the depth of a shallow puddle.

Thank you.

**Comment by Anzarot121** [comment]
If the blood is boiling, shouldn't this cause direct damage from blood loss or reduce the blood level?
Well, I must add that I see too many PRs that are hateful towards slimes. Now they die in space in 20 seconds. With this PR, they will die in 15.

**Comment by MACMAN2003** [comment]
space is already dangerous enough why does it need to be even worse

**Comment by FairlySadPanda** [comment]
From memory (i.e. from what happens in _Artemis_ when the MC is exposed to space on the Moon) the main problems space causes are:

1. You suffocate and die
2. You get microwaved and die if a nearby star has LOS to you

The "ideal" for spacing would be the following process:

-- AIRLOSS --
If you have air supply, nothing happens.

You start suffocating after some short time of losing access to breathable air. Airloss damage is a log scale, not linear, as air loss is more of an oh fuck moment once you're out too long rather than a normal DOT.

--BURN--
The server does a LOS check of a low rate (once a second?) from you to a point some arbitrary distance away from you decided by the vector representing the direction the star is ion. If you fail the LOS check, you get burned.

---
Space is really not that deadly. It's not pleasant, but a human getting spaced is probably going suffocate rather than anything else. The important thing atm is getting rid of cold damage, which makes literally no sense.

**Comment by Ilya246** [comment]
> From memory (i.e. from what happens in _Artemis_ when the MC is exposed to space on the Moon) the main problems space causes are:
> 
>     1. You suffocate and die
> 
>     2. You get microwaved and die if a nearby star has LOS to you
> 
> 
> The "ideal" for spacing would be the following process:
> 
> -- AIRLOSS -- If you have air supply, nothing happens.
> 
> You start suffocating after some short time of losing access to breathable air. Airloss damage is a log scale, not linear, as air loss is more of an oh fuck moment once you're out too long rather than a normal DOT.
> 
> --BURN-- If you have shielding, nothing happens.
> 
> The server does a LOS check of a low rate (once a second?) from you to a point some arbitrary distance away from you decided by the vector representing the direction the star is ion. If you fail the LOS check, you get burned.
> 
> The problem here is that by necessity to do this ideally you'd want to check every mob every second for LOS, which is stupidly wasteful.
> 
> Space is really not that deadly. It's not pleasant, but a human getting spaced is probably going suffocate rather than anything else. The important thing atm is getting rid of cold damage, which makes literally no sense.

those aren't the only things that kill you, the lack of atmospheric pressure makes your blood (and all the other liquids in your body) boil and evaporate

**Comment by metalgearsloth** [comment]
What damage does it do in ss13

**Comment by UbaserB** [comment]
> What damage does it do in ss13

On Goon it deals burn and oxygen damage.
On Paradise it deals brute, burn and oxygen damage.
On /tg/ it deals brute, burn and oxygen damage.

**Comment by Hemomancer** [comment]
0-0 Is it cool to get more damage, if this pr is accepted, will the cosmomedipens be returned?

Translated via Yandex Translator.

**Comment by UbaserB** [comment]
> 0-0 Is it cool to get more damage, if this pr is accepted, will the cosmomedipens be returned?
> 
> Translated via Yandex Translator.

It’s only a very minor buff, an extra 0.05 damage per second, and space pens aren’t coming back.

**Comment by Welldzhik** [comment]
Okay, I've never raised this topic anywhere, so I wrote off taking damage from space as just a game convention, but since this discussion exists, I'll allow myself to speak out.

   You won't freeze in space. Because there is no matter in space. You will just slowly radiate heat.

   You won't explode. Your skin is excellent at keeping you in one piece. For the same reason, you will not boil, because the water is not capable of expansion.

   In space, you will have only 3 problems: A vacuum that will literally squeeze all the oxygen out of you in about 20 seconds. A star that will roast your corpse for hours. And the huge radiation from the gas giant, which everyone probably forgot about.

   Only the first point and the third really threaten the little astronauts. According to the first search engine link, 20 seconds is not even the time of death. This is how long you can stay conscious. I'm just asking you not to look at reality as the desired result. Reality is boring. Just make everything logical enough. The current system is quite logical.

**Comment by K-Dynamic** [comment]
> Okay, I've never raised this topic anywhere, so I wrote off taking damage from space as just a game convention, but since this discussion exists, I'll allow myself to speak out.
> 
> You won't freeze in space. Because there is no matter in space. You will just slowly radiate heat.
> 
> You won't explode. Your skin is excellent at keeping you in one piece. For the same reason, you will not boil, because the water is not capable of expansion.
> 
> In space, you will have only 3 problems: A vacuum that will literally squeeze all the oxygen out of you in about 20 seconds. A star that will roast your corpse for hours. And the huge radiation from the gas giant, which everyone probably forgot about.
> 
> Only the first point and the third really threaten the little astronauts. According to the first search engine link, 20 seconds is not even the time of death. This is how long you can stay conscious. I'm just asking you not to look at reality as the desired result. Reality is boring. Just make everything logical enough. The current system is quite logical.

I'm fine with a slower form of realistic space damage considering how lethal it would normally be

**Pull request merged**
