### PR TITLE
RD suit recolor

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR

michelin man more inline with his own department, edit by noctyrnal
## Why / Balance

its shiney
## Technical details

sadly doesnt make the suit better at sustaining bomba
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

**Changelog**

:cl: noctyrnal
- tweak: RD's suit got a new paint job.

### CODE REVIEW

**Comment by noctyrnal** [comment]
awesome sauce now rd looks like they're actually from sci

**Comment by EmoGarbage404** [comment]
i think the shininess is visually kinda distracting and makes the suit look really high-contrast. I also think the old color is just more unique looking in general, especially for a department as monochrome as Sci.

**Comment by Terraspark4941** [comment]
> sadly doesnt make the suit better at sustaining bomba

blud its literally the most bomb resistant suit on the station, what do you mean lmfao
(also i validate this new suit change, wanna see in-game for a full opinion)

**Comment by UbaserB** [comment]
i love the new palette

**Comment by snebl** [comment]
I really like the design. It makes sense that something that's 'experimental' would be shiny like that. Also it's the suit of a head so it also makes sense that it pops out more.

**Comment by Golinth** [comment]
I love the new colors and how shiny it looks. It activates the "ooh shiny" neurons for me. Plus I think it fits the sci pallet a bit more than the old one

**Pull request merged**
