### PR TITLE
delete arachid

### PR DESCRIPTION
**Pull request by MHSPlay**
## About the PR

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This is lame af, especially if you're not going to justify it at all.

**Comment by Just-a-Unity-Dev** [comment]
@PixelTheKermit

**Comment by PixelTheKermit** [comment]
minor spelling mistake, I win.

**Comment by DogZeroX** [comment]
Nice first PR (I stole the joke)

**Comment by Ilya246** [comment]
- remove: Removed fun!

**Comment by retequizzle** [comment]
not even going to pretend to be nice here

shit PR, take the bullshit elsewhere

**Comment by lzk228** [comment]
yes
who tf cares about arachnids?
you guys didn't want new races waiting for surgery and now there are dwarves and arachnids

**Comment by Eden077** [comment]
> yes
> who tf cares about arachnids?
> you guys didn't want new races waiting for surgery and now there are dwarves and arachnids

Well... Considering how much work contribs have put into arachnids and the fact they're a relatively popular race removing them is just a bad idea in general, I don't see a good reason for removing them at all

**Comment by deltanedas** [comment]
shitter pr or meant to be for downstream idk

**Comment by Dynexust** [comment]
spite pr

**Pull request closed without merging**
