### PR TITLE
Freelance Radio Channel and Encryption Key

### PR DESCRIPTION
**Pull request by LordEclipse**
## About the PR

I am adding a new channel Freelance, its for events involving third parties that aren't NT/Syndicate affiliated.
## Why / Balance

For event purposes involving non-Nanotrasen and non-Syndicate entities. (Traders, diplomats, mercenaries, etc)
## Media
Channel preview:
image
Encryption Key:
image
Headset:
image

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i was under the impression that admin prototypes were typically just uploaded live instead of PR'd.

**Comment by LordEclipse** [comment]
> i was under the impression that admin prototypes were typically just uploaded live instead of PR'd.

I'm honestly not sure how I would even live upload this at all.

**Comment by LankLTE** [comment]
Pretty sure you can live upload prototypes through yaml, but regardless expecting admins to know how to do that is (evidently) unrealistic and they shouldn’t have to so I’m fine with it

**Comment by crazybrain23** [comment]
> Pretty sure you can live upload prototypes through yaml, but regardless expecting admins to know how to do that is (evidently) unrealistic and they shouldn’t have to so I’m fine with it

If you prototype upload a radio channel, how do you make sure all the observers can hear it?

**Comment by LordEclipse** [comment]
Actually, is it even possible to prototype upload a radio channel? I needed to edit a few pre-existing files, so I don't actually know.

**Comment by LankLTE** [comment]
Pretty sure you *could* but let’s be real, nobody will. I don’t have an issue with this regardless.

**Comment by lzk228** [comment]
> If you prototype upload a radio channel, how do you make sure all the observers can hear it?

rewrite observer prototype with new channel lol

**Pull request merged**
