### PR TITLE
Radiation collector component and system file scoped namespaces

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

Added file scoped name spaces to the radiation collector component and system, and remove some unnecessary references

## Why / Balance

To meet coding conventions

## Technical details

None

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

### CODE REVIEW

**Comment by Partmedia** [comment]
In the future, please separate content change commits from refactoring commits.

**Comment by chromiumboy** [comment]
OK, figured it wouldn't be an issue because the file scoping wasn't in any files with content changes

**Comment by chromiumboy** [comment]
Now that #19830 is merged, there's no worries about emptying the tanks, so radiation collectors can produce tritium safely again. I'll be reworking this PR to be a refactor only

**Comment by Partmedia** [comment]
Thank you for your contribution. Your commit organization made this very difficult to review, even though at the end I realize that this PR is now only whitespace changes. In the future, please separate refactoring/whitespace commits from content ones.

**Pull request merged**
