### PR TITLE
SS-28662 Add cvars to support forcing people to departures and making those at departures invincible

### PR DESCRIPTION
**Pull request by FairlySadPanda**
## About the PR
A cvar that means everyone must spawn at departures. This could be handy for an admin event? But mostly it's so the tutorial departures terminal can be seen by all newbies on gateway servers.

A cvar that grants everyone who spawns at departures godmode. This is handy for admin events and tutorials.

## Why / Balance
For gateway servers.

## Technical details
Thankfully turned out to be quite simple.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
you get no cl, you are cringe, nay-nay and should take a shower

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
Thansk to @VasilisThePikachu for help on this PR

**Comment by FairlySadPanda** [comment]
https://github.com/space-wizards/space-station-14/issues/28662

**Comment by VasilisThePikachu** [comment]
> Thanks to @VasilisThePikachu for help on this PR

I just told you cvars but you are welcome ;3

**Comment by Simyon264** [comment]
I would remove the changelog as it's not really player facing.

**Comment by Jezithyr** [comment]
Lgtm!

**Pull request merged**
