### PR TITLE
Added EVA Supply Crate to the cargo catalog

### PR DESCRIPTION
**Pull request by Captain-Wet-Beard**
## About the PR 
Added EVA Supply Crate to the cargo catalog.
This crate contains entities which are available in the EVA room.
The crate is a command crate to match the security of the EVA room.

**Screenshots**

EVA Supply Crate 1
EVA Supply Crate 2

**Changelog**

:cl:
- add: Added EVA Supply Crate to the cargo catalog.
- remove: Removed frustration with lack of jetpacks.

### CODE REVIEW

**Comment by mirrorcult** [comment]
jetpack crate was added in #11350

**Comment by Captain-Wet-Beard** [comment]
With there being another crate with jetpacks added, I'm tempted to close the request.
This adds EVA stuff as well though, so I'm not sure. I'll leave it up to the maintainers.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Remove the jetpacks and drop the price.

**Review by Captain-Wet-Beard — COMMENTED** [review]
Updated the pull as requested

**Pull request closed without merging**
