### PR TITLE
try something

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

maybe fix it??

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
who writes lerp that can throw an error what

**Comment by EmoGarbage404** [comment]
> who writes lerp that can throw an error what

my pet theory is that lerp is overflowing float and causing a negative value to get set for the time which could potentially cause problems for when the mission is supposed to end.

**Comment by metalgearsloth** [comment]
would rather know for sure what it is so someone please give more info.

**Comment by EmoGarbage404** [comment]
ok this isn't it we all go to hell ig

**Pull request closed without merging**
