### PR TITLE
Syndie elite uplink

### PR DESCRIPTION
**Pull request by Emisse**
balacned and put in uplink bntu

### CODE REVIEW

**Comment by Ilya246** [comment]
yeah i think the elite suit should just be the suit you use for things that are not necessarily combat, such as sabotaging singulo or punching substations or being (china-lake) fire support

**Comment by Emisse** [comment]
sure big dawg you got the plans i got the cash lets get this bread

**Comment by Emisse** [comment]
its same as uh m the actmos suit actually

**Comment by Emisse** [comment]
yea its good its good

**Comment by Ilya246** [comment]
then i guess it's fine since you should probably leave the area if it's at the point where it overwhelms atmos suits

**Pull request merged**
