### PR TITLE
Return deleted lobby music in jukebox

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

taken right from https://github.com/space-wizards/space-station-14/pull/24480

## Why / Balance

more music

## Technical details

no 

## Media

no

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added some new old music in jukebox.

### CODE REVIEW

**Comment by slarticodefast** [comment]
We still have atomic amnesia as lobby music I think? No need to add the file a second time.

**Comment by Doctor-Cpu** [comment]
its a good song regardless
we also have tin tin on the moon twice

**Comment by slarticodefast** [comment]
Yes, but you can just change the link in the yaml to the other folder instead of *literally* having the same file twice in different folders.

**Comment by lzk228** [comment]
@slarticodefast title3 is also dublicated, then should i remove dublication for both amnesia and title3?

**Comment by slarticodefast** [comment]
I guess? If it's exactly the same file we can just reuse it to reduce the game's file size. Except if anyone can tell me a reason why we are not doing that.

**Comment by Doctor-Cpu** [comment]
the jukebox songs are all mono while the lobby are stereo
image

**Comment by lzk228** [comment]
ok, dupe stays as it is
i tested all ingame and everything works fine

**Comment by slarticodefast** [comment]
>the jukebox songs are all mono while the lobby are stereo

Ah, that explains it! Make sure the songs you uploaded are mono as well then.

**Pull request closed without merging**
