### PR TITLE
Allow drag-and-drop insertion of reagents into the ChemMaster

### PR DESCRIPTION
**Pull request by JustTNE**
## About the PR

Separates out the component from "DrainComponent" that allows one to drag a bucket/any reagent container onto a drain/sink/toilet to empty it and allows other reagent containers to reuse the code effortlessly. Additionally, adds this component to the ChemMaster 4000.

## Why / Balance

Because it is something that has annoyed me personally when having to deal with jug-only chemistry and reduces some of the clutter around chemistry if it's not necessary, up to the chemist's discretion of course.

## Technical details

Rips out the existing logic for drag dropping things onto drains and replaces it with a new universal component that then handles this for any solution.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/38938720/c7e489bf-9776-4a08-9559-99340fb0d6a2

**Changelog**

:cl:
- tweak: The ChemMaster 4000 has been upgraded to allow drag-and-drop insertion of reagents!

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]
this probably needs guidebook/examine text/description somewhere since imo the drag drop behavior is pretty unintuitive in general but code looks fine

**Comment by JustTNE** [comment]
Can ya give me a pointer on where you'd like it?

**Comment by mirrorcult** [comment]
IMO `DumpableSolutionComponent` should subscribe to `ExaminedEvent` and add text saying that you can dump reagent containers into it with drag drop

**Comment by mirrorcult** [comment]
drag drops are generally unintuitive interactions but thats better than nothing

**Comment by Slava0135** [comment]
whatever

**Pull request merged**
