### PR TITLE
Updates aspid

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Aspid update; adds each head's dresser to their rooms, as well as their respective mantles. Also tidied up some of the head rooms. Finally, adds a tracking implant crate in the armory.

## Why / Balance

Got fed up with running around the station devoid of clothes as captain, and was too stubborn to ask some to be printed. I also didn't have my cloak!! How dare they!

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by MrToofters** [comment]
Thank god someones adding those clothes to the dressers

**Comment by Emisse** [comment]
no changelog for mapping prs

**Comment by Emisse** [comment]
also just add the mantles in a separate pr to the catalog fill, that way the map wont brick if the storage overflows

**Comment by Aexxie** [comment]
> also just add the mantles in a separate pr to the catalog fill, that way the map wont brick if the storage overflows

Shit, okay. Give me a second, I just shut down my computer.

**Comment by Aexxie** [comment]
> > also just add the mantles in a separate pr to the catalog fill, that way the map wont brick if the storage overflows
> 
> Shit, okay. Give me a second, I just shut down my computer.

Oh I misunderstood. They aren't in the dressers, they are in the head rooms.

**Pull request merged**
