### PR TITLE
Stealthier whispers

### PR DESCRIPTION
**Pull request by dmnct**
## About the PR
Gone are the days of "Operator Foxtrott whispers: - -a-- t-- --cl--- --sk" being heard through 3 walls causing a red alert, or your holoparasite instantly outing you in a similar way. And why should Security have such super-hearing when you are mockingly impersonating them as they walk away from the scene of your latest clown escapades?

* Whispers in the muffled range check Line of Sight, and if it does not exist, the whisperer is only identified as "Someone"
* Muffled whisper range reduced from 10 to 5. That's still the length of a small room

**Issues**
* ~~LoS-based identification of the muffled whisperer should use face/card identity, not voice~~

* ~~Whispering into your radio from a closet/crate will give your name away to everyone who is in "line of sight"~~

* LoS check is imperfect, erring on the site of False compared to what the player would expect (another person or non-opaque entity getting in the way blocks the check, but does not black out the area, leading the player to rightly think they should "see" that area. -- This is the best I could do with the current collision groups

* Being under a cardboard box, even an invisible Stealth cardboard box passes the LoS check in both directions, when ideally it should pass the check out, but fail the check in. Although in a Stealth Box even an unidentifiable muffled whisper would be a big problem since it revealed your position. The whisper range reduction there helps a lot.  -- as above, this needs a new collision group/check that is out of the scope of this PR 

* Handheld radios respect the new reduced whisper range but always send the name of a muffled whisperer, when logically they never should.  -- seems like a minor issue, to be fixed on a later PR

**Media**
whisper_range

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: Indistinct whispers heard through walls or from behind other objects/people no longer reveal the whisperer's identity, you need to be able to clearly see them.
- tweak: If you can see the distant whisperer clearly, their identity is determined by appearance/ID-card rather than their voice.
- tweak: The range at which indistinct whispers can still be heard has been reduced.

### CODE REVIEW

**Comment by lzk228** [comment]
I think the problem here is that you can generally hear through the walls, but it shouldn't be like that

**Comment by dmnct** [comment]
> I think the problem here is that you can generally hear through the walls, but it shouldn't be like that
If someone wants to recode WhisperMuffledRange to be dynamically calculated based on the actual propagation of sound waves I won't stop them, but until then, I think this is a reasonable solution. Not a lot of room for people to hear you from behind walls at 5 tiles anyway

**Comment by lzk228** [comment]
the issue is walls is literally nothing to sounds and speaking

**Comment by asperger-sind** [comment]
> the issue is walls is literally nothing to sounds and speaking

Yea basically, walls should muffle sound much more, I'd say as far as going for LoS-muffle checks on basic speech as well.

**Comment by deltanedas** [comment]
this is good since you wouldn't be able to recognize someones voice if you can barely make out what theyre saying to begin with, los check is smart
i think a fix to closet/susbox would be to check if only 1 person is in a container, not 0 or both (!=)

**Comment by moonheart08** [comment]
You screwed up your rebase.

**Comment by dmnct** [comment]
Okay, git shenanigans out of the way, I think I got everything back to where it was. 

Issue 1 fixed, there is a problem with issues 2 and 4 - without creating an entire new CollisionGroup that more closely aligns with player expectations of vision than Opaque, the two options are:
1. Don't use Opaque collisiongroup: Players in containers can determine the visual identity of nearby whisperers and vice versa, despite obviously not seeing each other. It will be slightly unintuitive that being in a locker does not hide your identity, but seems like an edge case with a range of 5 tiles on whispers
2. 2. Use Opaque: Lockers, closets, crates, and potentially other things block the LoS check. A player whispering in a closet will thus not be identified by name, but neither will a player standing on the other side of a crate (or many large machines), despite being visible to the observing player - this is also somewhat unintuitive
This will result in probably somewhat frequent occasions where listeners see someone whispering, know it's them, but the chat will refer to the whisperer as Someone in the chat. Is this realistic? Should they have been paying attention in the moment of whisper, to be able to catch who it was? (You can see the float text over the whisperer after all)

**Comment by dmnct** [comment]
I think the check with the Opaque group is better, it errs more on the side of failing the check which leads to better stealth and more interesting social potential (for example, you can whisper in a crowd and the other end of the crowd will not know who whispered, since the people block LoS around you). 

I have updated the outstanding issues, but I consider all of them out of scope or minor enough to be their own later PR. Let's gooooo

**Comment by Slava0135** [comment]
lets try this

**Pull request merged**
