### PR TITLE
Syndicate traitors can now purchase nuke codes

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

Syndicate traitors can now purchase the authentication codes for a (random) nearby nuclear fission explosive device! Each purchase costs 2 TC

It cannot be purchased by nuclear operatives or found in surplus bundles

## Why / Balance

April fools!

## Technical details

N/A

## Media

stolen-codes

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
why is this on april fools

**Comment by chromiumboy** [comment]
> why is this on april fools

I figured that traitors probably shouldn't be trying to blow up the whole station :P

But hey, if you think it would work on master...

**Comment by muburu** [comment]
this would also be pretty cool for traitors on normal non april fools games, but also super counterintuitive because you instantly kill all your fellow traitors and yourself if the nuke detonates...

actually who cares, syndies bomb the shuttle killing 90% of the people on it, whose to say they shouldn't try and nuke the station too?? ADD THIS TO MASTER!!!!

**Comment by Erisfiregamer1** [comment]
IMO if this was ever merged to master there should probably be some warning that someone has purchased the nuke codes, and it should be more expensive.

Being able to potentially remove everyone from the round for **2 TC** doesn't seem fair.

**Comment by chromiumboy** [comment]
> IMO if this was ever merged to master there should probably be some warning that someone has purchased the nuke codes, and it should be more expensive.
> 
> Being able to potentially remove everyone from the round for **2 TC** doesn't seem fair.

The traitor who buys the codes still has to get their hands on the nuke authentication disk, break into the vault, and then secure the armed nuke for 5 mins before the station is destroyed. And they have to accomplish this with far fewer resources than nukies have access to. It will likely need a collaboration between multiple traitors to even have a chance of this succeeding. The only issue I really see is on low pop servers with a robust traitor on board. 

If it were going on master, I'd probably put a delay of 30 mins before it can be purchased

**Comment by deltanedas** [comment]
also a minimum crew requirement being added, being able to nuke it on 5p doesnt make sense maybe 20p minimum

**Comment by chromiumboy** [comment]
Is there an option to restrict uplinkpurchases based on player count?

**Pull request merged**
