### PR TITLE
Remove lean.

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
I think that's more than enough of that.

**Changelog**
:cl: moony
- remove: Removed fun! No more lean, don't do drugs kids.

### CODE REVIEW

**Comment by Mith-randalf** [comment]
Game's got meth, murder and you can put mice in blenders. If the issue is that the content is inappropriate this seems like a weird place to start.

**Comment by mirrorcult** [comment]
i think the issue is mostly that it's really fucking annoying

**Comment by moonheart08** [comment]
yea uh people are obsessed with doing nothing but making lean. yeet.

**Comment by ZeroDayDaemon** [comment]
> yea uh people are obsessed with doing nothing but making lean. yeet.

Wow, it's almost like, when something new is added, people are gonna overuse the shit out of it until everyone is bored of the joke.

**Pull request merged**
