### PR TITLE
Added Black Jumpsuit and various colorful gloves to the Clothesmate

### PR DESCRIPTION
**Pull request by GNF54**
## About the PR

Added Black Jumpsuits and Jumpskirts to the Clothes-Mates along with a rainbow of gloves. 
## Why / Balance

Since gloves are now available in the Clothesmate, it makes sense to add the barely used colorful gloves.
## Media

Screenshot 2024-01-03 185900

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by GNF54** [comment]
> don't add the black gloves in there, those are security's.

I didn't add them, they have been in the Clothesmate for a while.

**Comment by TheShuEd** [comment]
test fail is real, you need to fix this

**Comment by GreyMario** [comment]
> don't add the black gloves in there, those are security's.

black gloves are black gloves, they're not security specific items

**Comment by GNF54** [comment]
> test fail is real, you need to fix this
> 
> ```
> Failed NoCargoOrderArbitrage [2 s]
>   Error Message:
>      Found arbitrage on CrateVendingMachineRestockClothes cargo product! Cost is 4350 but sell is 4610!
>   Expected: less than or equal to 4350
>   But was:  4610.0d
> ```

Changed the cost of a restock crate to 4650

**Pull request merged**
