### PR TITLE
Add new chemical Valoderm

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This chemical is the summation of two changes i feel would either add some more uniqueness to what a chemist can create, along with adding more interactions to some chemicals that i feel are way too simple for their effects. This is my personal opinion as someone who is a crackhead at chem and absolutely love the job gameplay.

For an example, even though alcohol and space drugs are all great for making for a trippy experience; there is still ONE effect that can hardly be recreated.. jittering! Your only choice for jittering is overdose or space medipen, which is way too little. In short, this is just cryptobiolin v2.

## Technical details

It requires a 1:1:1 ratio of hydrogen, water and mercury to create, and produces 3 Valoderm. I have tweaked the recipes of Leporazine, Impedredizine and Synaptizine to require Valoderm. Causes Jittering and slower movement on consumption, at a minimum of 5u.

**Changelog**

:cl: Ubaser
- add: Added a new "filler" chemical, Valoderm.

### CODE REVIEW

**Comment by moonheart08** [comment]
This feels very pointless.

**Comment by UbaserB** [comment]
It's main purpose is to make chem more complicated

**Comment by moonheart08** [comment]
Yea this is just pointless, chemistry is already just a button clicking game and I don't feel like encouraging that.

**Comment by UbaserB** [comment]
> Yea this is just pointless, chemistry is already just a button clicking game and I don't feel like encouraging that.

ok

**Comment by CatMagic1** [comment]
Just don't put it in those recipes! This will greatly improve my drug addict gameplay. Pls add

**Comment by UbaserB** [comment]
@moonheart08 will you merge if i remove the recipes

**Pull request closed without merging**
