### PR TITLE
Disable bioluminescence plant mutations because it breaks the engine

### PR DESCRIPTION
**Pull request by PJB3005**
No fun allowed

:cl:
- remove: Removed bioluminescence plant mutations due to it breaking the rendering engine.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/32489

though I did tell em

**Comment by PJB3005** [comment]
> #32489
> 
> though I did tell em

Yes, this PR was quite handy for figuring out how plant mutations work so I can nuke this feature.

**Comment by Plykiya** [comment]
people have been spamming flares and flare shells to do the same thing as well lately, quite annoying

**Comment by slarticodefast** [comment]
> people have been spamming flares and flare shotgun shells to do the same thing as well lately, quite annoying

Yeah, flares should probably be removed being a lathe recipe again
grafik

**Comment by insoPL** [comment]
Good idea, at least until next part of botany update drops. Then we can just make glowing plants and not produce. Which makes more sense.

**Pull request merged**
