### PR TITLE
Revert "Disposal Unit Tweak (#23067)"

### PR DESCRIPTION
**Pull request by Ratyyy**
## About the PR

This reverts commit b1c3158e017308ac4b81856370143164c3f76155.
## Why / Balance

the new sprites of the disposal unit are definitely worse than the old ones and don't fit in with the space station 14 style
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
> don't fit in with the space station 14 style

> swapping them for sprites that are even more out of style

we are not interested in having the old sprites again. if you want to do another resprite, you are free, but we're not going to accept the old ones.

**Comment by Hmeister-fake** [comment]
The new one looks so bad, very sad

**Comment by Ratyyy** [comment]
> > don't fit in with the space station 14 style
> 
> > swapping them for sprites that are even more out of style
> 
> we are not interested in having the old sprites again. if you want to do another resprite, you are free, but we're not going to accept the old ones.
So you added the ugly sprite because you just don't want the old one?

**Comment by EmoGarbage404** [comment]
> So you added the ugly sprite because you just don't want the old one?

no i just think this sprite is even uglier.

**Pull request closed without merging**
