### PR TITLE
Substation resprite

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Too ERIS-ey. Fixed it up and resprited it inspired by IRL substations.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- tweak: Resprited substations.

### CODE REVIEW

**Review by TheShuEd — APPROVED** [review]

**Comment by KashRas2** [comment]
Yo. You need update meta.json.

**Comment by Emisse** [comment]
update meta.json

**Comment by EmoGarbage404** [comment]
i have some mild feelings which i'm gonna post in #art

**Comment by EmoGarbage404** [comment]
image

made some small tweaks that i think better clarify the form and simplify it a bit more. just ping me in discord and i can yeet the sprites over.

**Comment by chromiumboy** [comment]
Pretty sure the substation screen is shared with the wall mounted substation, you may need to update that as well

**Review by chromiumboy — CHANGES_REQUESTED** [review]
Yup, you'll need to update the wall mounted substation due to the changes to the substation screen

As please update the substation static sprites for the power monitor console

**Comment by UbaserB** [comment]
> update meta.json

i actually just realised i never even pushed the new changes hence why the meta didnt update either lol

**Pull request merged**
