### PR TITLE
Add UI click sounds

### PR DESCRIPTION
**Pull request by metalgearsloth**
Requires https://github.com/space-wizards/RobustToolbox/pull/4705

Final video pending but this is the idea:

https://github.com/space-wizards/space-station-14/assets/31366439/a08b2cc7-e490-4295-9bdc-85c36b36e597

Another draft:

https://github.com/space-wizards/space-station-14/assets/31366439/df1ae295-b165-434e-b555-ce0608c33e32

TODO:
- [x] Fix all the ways to press UIs.
- [x] Make SetXSound a cvar instead probably.

:cl:
- add: Added sounds to UI clicking and hovering.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
would be cool if you could upload your own custom sounds to be used locally for this, the closest example i can think of is having custom crit sounds in tf2

**Comment by UbaserB** [comment]
i feel like the hovering click noises should be muted a little, right now its a bit jarring

**Comment by metalgearsloth** [comment]
> i feel like the hovering click noises should be muted a little, right now its a bit jarring

There's an audio slider and I decreased the default from the video posted to roughly half.

**Comment by metalgearsloth** [comment]
Might remove the context menu hover sounds as it might be too much audio spam.

**Comment by arimah** [comment]
Overall, I am not a huge fan of introducing these sounds into such a UI-heavy game, especially as the station around you is likely to be bathed in a cacophony of random noises already. Many, many games have sounds for UI interactions, but not all need it. I would find it distracting and unpleasant and it would do nothing to increase my engagement with anything.

To my mind the two most important considerations are:

1. Whatever sounds are selected, they must be short, gentle and subtle. In your videos, the first example sounds like a message notification from Discord or something, extremely confusing. The second example feels shrill to me.
2. There _must_ be a way to disable or turn down these sounds in isolation. Some people, such as yours truly, have auditory filtering difficulties - basically, my brain struggles sometimes to immediately distinguish between audio sources and can't easily filter out specific sounds. Having to deal with UI sounds on top of all the other space station chaos, I might cry.

**Comment by deathride58** [comment]
@arimah 
The first example appears to be more a shitpost than anything else, aye. The second video contains the sounds currently in the PR.

The PR also already contains an audio slider! When/if this PR is merged, it'll be straight-forward to slide the interface volume slider wherever you please

**Comment by AJCM-git** [comment]
> Might remove the context menu hover sounds as it might be too much audio spam.

Idk about having inconsistencies like that, maybe make the sound slightly longer and make it only play one or two sounds at a time? That way there is no overlap

**Review by AJCM-git — APPROVED** [review]
Straight to master (Please i need this in my life)

**Comment by mirrorcult** [comment]
i dont super love the keyboard click sound but the hover sound is wonderful

**Comment by mirrorcult** [comment]
click sound was changed, sounds better imo and good to merge i thinke

**Comment by mirrorcult** [comment]
with engine update

**Comment by UbaserB** [comment]
wooo

**Pull request merged**
