### PR TITLE
Reduces the captain's sabre reflect chance to 10%

### PR DESCRIPTION
**Pull request by deepdarkdepths**
## About the PR
Captain's sabre reflect was reduced from 50% to 10% for balance. This WILL need discussion to come to a proper consensus if this is the right choice or not. It might be better to remove it entirely.

## Why / Balance
The reflect chance of 50% is too powerful. While this is good in the hands of the captain who can use it well, the moment an antagonist gets their hands on this, if they are remotely good at combat, they will effectively be immune to ranged stun weaponry. Balance teeters on player skill, and when a good, capable player gets their hands on a sabre, it is basically game over for any forces that try to stop them. This should not happen if the sabre was properly balanced.
I will also state that it is not a challenge to obtain this item. The viper, a 3TC purchase, 4TC if you buy an extra mag to secure a kill, can take down the captain with one magdump, but this is assuming you landed all shots. If not, you can slap that extra mag in and finish the job. 
Melee weapons have the distinct disadvantage that they are well, melee. Therefore, extra values are added to them so they are worth using, namely reflect chance. In the [PR](https://github.com/space-wizards/space-station-14/pull/18133) that buffed the reflect chance, it made a comparison to the DESWORD, which is now removed from uplinks entirely due to how broken it was. This reflect chance is from an era where 50% seemed "weaker," when it is in fact not.
We already have systems for damage reduction called armor. We do not need 50% reflect chance on the sword of a person who boasts arguably the best roundstart armor in the game, and in the hands of an antag, it makes them virtually invulnerable. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by asperger-sind** [comment]
I'll note there was a pretty lengthy discussion in the Discord "captains validhunting" bugs-feedback thread, along with a smaller one in design-discussion. Overall, both discussions have the majority agree(1) that the reflect chance is a bit too much.

(1). Based on my perspective, so, anecdotal.

**Comment by UbaserB** [comment]
nerfing is fine but this is a bit excessive

**Comment by Dutch-VanDerLinde** [comment]
this is not excessive 50% reflect chance is busted

**Comment by Golinth** [comment]
maybe 25% at minimum. 10% is a major major nerf to captains, and doesnt even compare to e-swords. The sword is MEANT to be a juice loot item for traitors to get, like his laser.

**Comment by superjj18** [comment]
> I'll note there was a pretty lengthy discussion in the Discord "captains validhunting" bugs-feedback thread, along with a smaller one in design-discussion. Overall, both discussions have the majority agree(1) that the reflect chance is a bit too much.
> 
> (1). Based on my perspective, so, anecdotal.

the opinions of roughly five people do not count as a "majority" in a community of thousands, discord polls alone are not a reliable way to gauge design decisions.  Captain is already without a doubt one of the most stressful and anxiety inducing roles in the entire game, and reflect is only one a very small group of defensive tools he gets in order to defend himself, the station, AA, all comm keys, not to mention his defensive tools themselves.  Captain should be a challenging target given taking him down results in more rewards for an antag than any other target, and for nukies is an actual win condition.  

Captain will always be able to be killed in a 1v1 if the traitor has the element of surprise, and the reflect rarely comes into play and even less so actually makes a difference, to say he is OP is ridiculous compared to the absolute nightmare of equipment he has to fight against.  A captain must have the tools to defend and control his station, and this removes one of them.

Frankly if this change is to go through, it absolutely should apply to all swords that give a reflect chance.  Some recommended that it break should it reflect too much, while it definitely shouldn't break maybe the defensive aspect should break similar to a shield(explain it as cap running out of "focus" or "luck"), leaving the saber still as an effective weapon but allow for its defenses to be brute-forced, or we could also put the reflect on a 5 second cooldown per reflect.  

antags are already perfectly strong enough as is.

**Comment by deepdarkdepths** [comment]
> nerfing is fine but this is a bit excessive

I was considering making it 20%, but I didn't for one reason:
Bleeding rework.
As a comparison, the e-sword has a 25% reflect(IIRC), at the cost of never being able to hurt your target long-term. Any slash it does is automatically cauterized by the fact it does heat damage.
The captain's sabre does great damage, which is mainly slash damage. Enough hits and your target WILL bleed out if they don't stop it in time. This means you can just walk up to someone who has a gun, potentially absorb all of the damage they output from the reflect chance while hitting them a few times, walk away, and let them bleed out. They cant engage with you anymore because they're risking their own life more than you're risking yours.

**Comment by YippeeeGoober** [comment]
imo some command have deadly weapons/items that are horrible if they fall into the wrong hands, like a syndie, that doesn't mean it should be nerfed.

**Comment by KingOnBudget** [comment]
At last somebody is making this. Captain's sword has no right being strong as it is. Just having your sword out makes every gun fight one sided.

**Comment by BramvanZijp** [comment]
Just a random idea I had, what if by default the reflect is 20-25%, and if you wield it with both hands, it goes back to being 50.
If not, I think the reflect should be 25-33% in this pr, and based on how that goes we decide what to do next, but 50 > 10 is too much of a drastic nerf to do all at once.

**Comment by ImWeax** [comment]
I think 33% is a fair reflect chance - brings it closer in line with the esword while still retaining the value of the (one of a kind, you will not get multiple of these) item for traitors to steal/loot. 10% is nothing and you may as well take the reflect chance away at that point.

**Comment by Killerqu00** [comment]
nerfing it to 20% of original value is too big of a change

**Comment by deepdarkdepths** [comment]
How are we feeling about 25% to reach a midpoint? I'm getting either 20% or 33% as suggestions.

**Comment by superjj18** [comment]
> How are we feeling about 25% to reach a midpoint? I'm getting either 20% or 33% as suggestions.

As the person who has been staunchly against this nerf throughout the discussion, even I think 33% would be a fair and reasonable compromise.

(Although I actually really do like the idea of giving the saber a wield that only buffs its defense, as that cant be enabled purely by simply pressing shift+e and limits their combat ability in favor of defense making it a deliberate decision to prioritize defense)

**Comment by TurboTrackerss14** [comment]
image
Reposting my entirely correct opinion here. 
Changing the flat % will result in eternal back and forth as to what is and isn't a balanced amount due to RNG making "10%" not really 10%. 
A sliding scale works best ™️

**Comment by FairlySadPanda** [comment]
A sliding number feels about right fwiw. The ultimate "sabre blocking blasters" moment in sci-fi is probably that bit in Episode 1 right at the start - you see both of the jedi blocking by concentrating and standing still

**Comment by IProduceWidgets** [comment]
I think a nerf is good. Going from 1 in 2 to 1 in 10 seems like too much. I think melee is too strong in general, but somewhere between 1 in 5 and 1 in 3 seems right to me given where melees and guns are right now. 

I think 25% is about right. I would be interested in seeing wielding play into the balance though, that sounds neat.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I think the nerf doesn’t go far enough, bring that deflect down to 0%, OR make the angle that the bullet will go flying off in larger

**Comment by Golinth** [comment]
>“Needs discussion”

>Overwhelming consensus from said discussion is that the nerf goes too far

>Merged anyway

Why even add the need discussion tag if anything said just gets entirely ignored?

**Comment by metalgearsloth** [comment]
> Why even add the need discussion tag if anything said just gets entirely ignored?

I read the discussion but instead of asking for thoughts you just started whining so.

**Comment by Golinth** [comment]
Ah fair enough. Whining is a bit much, but it does feel like the discussion was ignored, especially when so many people agreed that it was too far. My bad for sounding like that, just frustrated.

I am curious, why merge it now, and not set it to a 20%, or even the sliding scale idea

**Comment by deltanedas** [comment]
> why merge it now, and not [...] the sliding scale idea

wyci

**Comment by HelpTheSteak** [comment]
Worse reflect then a epen its so over

**Comment by HelpTheSteak** [comment]
Epen does more damage too jesus

**Pull request merged**
