### PR TITLE
Clipping a harvestable plant yields undamaged seeds

### PR DESCRIPTION
**Pull request by botanySupremist**
## About the PR
When you clip a harvestable plant, the seeds will be at full health instead of being damaged.

## Why / Balance
Mostly a bandaid patch to make Botany slightly more tolerable (specifically, less of a waiting game) while a rework/refactor is figured out. Clipping a plant in any condition currently causes it and its clippings to be damaged, and this is quite bothersome.
The plant you harvest from is still damaged. Don't be overzealous!

## Technical details
~~Added a new variable, nullHealthOverride, that the clipper's SpawnSeedPacket checks instead of component.Health. It's null if the plant is harvestable, causing healthOverride to get null and not override the seed's health.
(Please inform me if this is hacky- it feels like it, but I'm new to C# and largely coding as a whole, and would love to learn more effective means.)~~ declares healthOverride in the plant holder system and uses it in the function as opposed to component.Health, setting it to null if the plant is harvestable and thus causing the resulting plant's health to be drawn from endurance

## Media
https://github.com/space-wizards/space-station-14/assets/160211017/3fd78d6d-705f-4ac6-8ba4-11e5f43a6483

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None to my knowledge. This is my first time interacting with the code directly, but it is an extremely simple change.

**Changelog**
:cl:
- add: Clipping harvestable plants now yields undamaged seeds.

### CODE REVIEW

**Comment by potato1234x** [comment]
they didnt do this before?? why??

**Comment by PolterTzi** [comment]
> they didnt do this before?? why??

~~Because the dude that coded the damage transfer is an idiot.~~

**Comment by Partmedia** [comment]
Thank you for your (first!) PR.

The clippings ("seeds") inheriting the reduced damage seemed very much intentional, since the PR description from https://github.com/space-wizards/space-station-14/pull/25326 reads:

> Makes changes to seeds and plant holders so now clipped seeds keep the modified health of the sampled plant

This is because:

> It doesn't revert back to the previous state of effectively free sampling, while still allowing taking samples without needing to wait for growth.

So I would appreciate if you could spend some time explaining why and the balance implications of "a bandaid patch to make Botany slightly more tolerable" is needed, and what about the current behavior is "quite bothersome". The behavior is intentionally designed to make clipping less desirable compared to using the seed extractor.

Happy to work with you on the code changes, but let's make sure that this is something we want to do first. Without more explanation about why this is needed or why this is better for balance, I feel that the current behavior is better for the balancing reasons that have been explained in previous PRs.

**Comment by botanySupremist** [comment]
> So I would appreciate if you could spend some time explaining why and the balance implications of "a bandaid patch to make Botany slightly more tolerable" is needed, and what about the current behavior is "quite bothersome". The behavior is intentionally designed to make clipping less desirable compared to using the seed extractor.

In my opinion, the issue with prioritizing the use of the seed extractor is that plants tend to become seedless when you mutate them, hybridize them, or their potency becomes high enough. The former is largely fine, as it prevents you from supplying entire departments with insanely powerful chemical plants in the first 20 minutes of the game, but in combination with other mutated aspects like tolerances being changed (which is really annoying to support, especially with the current lack of plant analyzers) or the dying gene, it can be mind-numbingly annoying/slow to get an actually usable plant. Healing chemicals make the process take even longer. Not having to wait for new seeds to heal/grow enough to have chemicals used would lessen the wait a good amount without leading to botany being overpowered.

About the latter- an oversight on my part. High potency is somewhat of a trademark for Botany, considering robust harvest is the only plant-beneficial chemical they start with. I can agree that having unlimited access to a seed extractor regardless of plant strength would be crossing the line, but at the moment I don't believe that the speeding up the process of obtaining 50-potency plants with the clipping change would be overpowered. Especially with the "already sampled" behavior in the game.

Let's say you avoided going over 30 potency to avoid the high-potency seedless behavior in order to make use of the extractor- botany becomes a bit more boring than before, and you either have to take up more space with plants or wait longer to get the same effect. The seed extractor is indeed an option for botanists, but it rarely is later into shifts when you actually go for strong or wacky plants. It's sort of not in line with botany's identity to have to hold back that much on the wacky stuff.

In the end I think this would make botany more tolerable by reducing the wait on getting more viable plants. The cool/fun stuff to use is rarely _not_ seedless and clipping is left as the only, and slow, option.

(Can't believe my English classes actually came in handy for once. Probably a flawed argument, but I'm trying regardless.)

**Comment by botanySupremist** [comment]
Also, does git automatically mention PartMedia? I don't wanna unnecessarily bother people

**Comment by Partmedia** [comment]
Thanks for your thoughtful response.

The main objective seems to be to "make botany more tolerable by _reducing the wait on getting more viable plants_" (emphasis mine). **Would having more botany trays available to botany resolve this problem?** Imagine having a large "experimental botany room" where you can try to create mutations and cross them en-masse. That would provide botanists something to do and reduce the amortized wait time.

> the issue... is that plants tend to become seedless when... their potency becomes high enough

The purpose of this is to prevent you from dumping one small bottle of robust harvest and having 100 potency plants for the rest of the game. **How do you propose to address this?** Currently, in order to have 100 potency plants, you either:

1. Take the easy way and dump robust harvest, and need a steady supply from chemistry
2. Take the hard way and get close to 100 potency through mutations

It is possible that (2) is too tedious and or too hard, but I think having an experimental botany room, or decreasing the chance of hitting the viable gene, would address the root cause of the problem instead of using a "bandaid".

> in combination with other mutated aspects like tolerances being changed (which is really annoying to support, especially with the current lack of plant analyzers)

Does this imply that you think this should be reverted once plant analyzers are available? I would really prefer that we do not go back and forth on mechanics, especially since players are already saying that botany is obtuse and hard to learn. Changing mechanics every week would make this worse.

> you either have to take up more space with plants

Which, more space can be made with an "experimental botany room".

**Comment by deltanedas** [comment]
> Imagine having a large "experimental botany room" where you can try to create mutations and cross them en-masse

with serious botanists this is usually all or most of the botany tray count, but this is harder on smaller stations. maybe a bonzai thing where you can grow lots of plants in a smaller footprint would be good for this use case

> Take the easy way and dump robust harvest

this isnt possible, robust only goes to 50u

**Comment by botanySupremist** [comment]
> Would having more botany trays available to botany resolve this problem?
This is an interesting one. It's a good idea, especially if more controlled mutations/swabbing become available in the future. It would also make the main botany room less messy, since it'd be used for ideal plants. I'm not sure if it would resolve the annoyance with waiting, but having more trays means you could do other experiments in the meantime.
At the moment plant's max yield is quite high and metalgearsloth finds it ideal for yields to be nerfed, I'm wondering if this could have any negative consequence on the server.

> Currently, in order to have 100 potency plants, you either [take the easy way and dump robust harvest...]
Robust Harvest reaches 50 potency at most. Reaching 100 potency through mutations is very risky for the plant. and 50 potency is a lot more tame compared to 100.

> Does this imply that you think this should be reverted once plant analyzers are available?
No, adjusting to specific mutated plant's tolerances is going to be annoying regardless of plant analyzers existing.

**Comment by Stealthbomber16** [comment]
> Would having more botany trays available to botany resolve this problem?

Not possible on maps like saltern where botany is just a 5x5 square room.

This PR solves the primary issue with botany at the moment following the clipping rework that creating fun plants is just not practical anymore since you can only use them a small handful of times.

**Comment by botanySupremist** [comment]
"...not practical anymore since you can only use them a small handful of times." Growing plants do regenerate health over time and chemicals exist, but both are yet another factor to add to the wait.

**Comment by Partmedia** [comment]
@Stealthbomber16 says this is probably fine, so let's go with it.

Please fix your comments to match our code conventions.

Additionally, please partially revert dab2c4884928 (#25326) which added `HealthOverride` which is now no longer being used.

**Comment by Partmedia** [comment]
Sorry, I misunderstood what the PR does. You are right that there is no need to remove `HealthOverride`.

**Comment by botanySupremist** [comment]
> Sorry, I misunderstood what the PR does. You are right that there is no need to remove `HealthOverride`.

I'm going to try to find a cleaner way to do this that does not implement a new variable and post that for feedback/merging if possible, otherwise I'll just clean up the comments on the current rendition and submit it

**Comment by botanySupremist** [comment]
@Partmedia It works exactly the same as before and no longer uses nullHealthOverride so it looks a lot nicer. Thanks PolterTzi for the help

**Comment by Partmedia** [comment]
Thanks for your contribution!

**Comment by PolterTzi** [comment]
I did not notice this got merged.
Nice that it did.

**Pull request merged**
