### PR TITLE
handheld atmos monitor

### PR DESCRIPTION
**Pull request by averystarbits**
## About the PR
Added a handheld version of the atmos alarm (also an antag objective)

## Why / Balance
-As an engineer main the atmos compuer is often underutilized. It's locked behind atmos (iirc) so most engineers can't access it.

-Not to mention that an engineer might be chained for multiple repairs and not have any time at all to go back to engineering and check the alarms computer.

## Technical details
-Added handheld_atmos_computer.yml and giving it the necessary sprites in Objects/Specific/Atmos/handheldatmoscomputer.rsi
-Handheld atmospherics computer is a syndicate steal objective
-Guidebook properly reflects these new additions

## Media
https://github.com/user-attachments/assets/61be6ded-7e5f-4257-b3b2-f7370f9814fe

## Requirements

- [/ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [/ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
- add: Handheld Atmospheric Computer! Allows for remote use of the atmospherics computer. It is also a syndicate objective so - be careful!

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Power alarm too expensive to have handheld

**Comment by averystarbits** [comment]
> Power alarm too expensive to have handheld

Too expensive, like too op? I could get that out and just make the atmos alarm instead

**Comment by Golinth** [comment]
> Too expensive, like too op?

too expensive, like performance-wise

**Comment by averystarbits** [comment]
GOT it, atmos only then :)

**Comment by Golinth** [comment]
> I changed the directions on "scanner" to 4 and it seems to just make the sprite... vanish

keep the direction amount the same, and add more delays I think. so like 
```
"states": [
        {
            "name": "scanner",
            "directions": 1,
            "delays": [
                [
                    0.4,
                    0.4,
                    0.4,
                    0.4
                ]
            ]
        },

**Comment by averystarbits** [comment]
Might make this a CE exclusive item + an antag objective purely because the CMO monitor is and unlocking an item like this through science just leaves a useful tool at luck.

https://github.com/user-attachments/assets/61be6ded-7e5f-4257-b3b2-f7370f9814fe



Here is a closer look at the sprites and their stages:
image

Final thoughts before I get ready for review?

**Comment by averystarbits** [comment]
Added it as a syndie objective 

https://github.com/user-attachments/assets/9e16ec51-0512-4651-a2c3-c31192845a62

image

Texture was missing in the video, that is now fixed.

**Comment by slarticodefast** [comment]
Thank you for taking the time to put this together. However, this was discussed among maintainers and the consensus was not to merge this for the following reasons:
- Consoles should stay stationary in order to encourage cooperation between crew members. A portable version would make the console redundant and could not be sabotaged.
- Antagonists have no use for the portable atmos monitor. Unlike the crewmonitor, which can be used to track the location of your targets.
- The high performance impact of navmap BUIs.

We will make sure to include these thoughts in a future design document as we had to close similar PRs for the same reasons.

**Pull request closed without merging**
