### PR TITLE
Barratry update

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

adds one chem dispenser board to chemistry
adds mindshield crate to armory
adds ninja bombing spots in engi, botany, bridge, armory, sec, hop, med, cargo and evac
## Why / Balance

1. chemists are in pain
2. pretty sure ss13 has that and #20795
3. it wasnt there before

## Media

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: JoeHammad
- add: chem dispensers to barratry, you can stop crying now

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Please fix your IDE so the diff isn't massive.

**Comment by JoeHammad1844** [comment]
uhhhh i dont know hwo to do that or what that means

**Review by TsjipTsjip — APPROVED** [review]
This is an approval to indicate that this mapping change runs on the latest server version available, and that as far as I can see it does what is listed.

I am not a maintainer, this is not indicative of this needing to be merged balance-wise.

**Comment by Emisse** [comment]
I am fine with the changes I just do not like the entire map diff, I need to find out why it did that

**Comment by deltanedas** [comment]
crlf

**Comment by NancokPS2** [comment]
detroit gets something!? WOOO

**Pull request merged**
