### PR TITLE
New Lobbyscreen Art

### PR DESCRIPTION
**Pull request by Alekshhh**
it's a bit lazily done I'll admit

## Media

image

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Hmeister-fake** [comment]
Amogus

**Comment by deltanedas** [comment]
SUS!

**Comment by MrGreen006** [comment]
I do enjoy this but is this.. legal?? Like will innersloth come knocking at the door for this lmao.

**Comment by deltanedas** [comment]
among has a fan creation license thing on their website somewhere

**Comment by EmoGarbage404** [comment]
quality of the art aside, I'm not sure it's a good fit for the server as a whole.

**Comment by Emisse** [comment]
amog

**Comment by metalgearsloth** [comment]
> amog

needs license you spud.

**Comment by GreyMario** [comment]
> I do enjoy this but is this.. legal?? Like will innersloth come knocking at the door for this lmao.

for the record we do currently have among pequenos

**Pull request merged**
