### PR TITLE
Reactions to make most chemicals in system

### PR DESCRIPTION
**Pull request by Soundwavesghost**
Based on the reagents/chemicals.yml list I recreated most of the recipes to create the chemicals therein. Instances of Acetone have been replaced with Silicon and Sugar to Glucose. Also, there is currently no heating, and plasma would be lost in the process of creating chems that normally use it as a catalyst.

### CODE REVIEW

**Comment by PJB3005** [comment]
Which chemistry system is this based on?

**Comment by Soundwavesghost** [comment]
OH! I used VG and Baystation as the basic idea for the completely imaginary drugs.

**Comment by Moneyl** [comment]
Several of these reactions already exist in [reactions/medicine.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Reactions/medicine.yml)

Just a few examples: [Inaprovaline](https://github.com/space-wizards/space-station-14/blob/f8a64bcd5cdeb846d2ab1382f3896ed2b0e59354/Resources/Prototypes/Reactions/medicine.yml#L185), [Bicaridine](https://github.com/space-wizards/space-station-14/blob/f8a64bcd5cdeb846d2ab1382f3896ed2b0e59354/Resources/Prototypes/Reactions/medicine.yml#L47), and [Dylovene](https://github.com/space-wizards/space-station-14/blob/f8a64bcd5cdeb846d2ab1382f3896ed2b0e59354/Resources/Prototypes/Reactions/medicine.yml#L25).

**Comment by Soundwavesghost** [comment]
Yeah I skipped those when I started going down the list. It shouldn't be repeated within the medicine.yml versionI made.

**Comment by Moneyl** [comment]
Correct me if I'm wrong, but in this PR you've added reactions to `reactions/chemicals.yml` and left `reactions/medicine.yml` unchanged. What I'm saying is that many of the reactions you added to `reactions/chemicals.yml` already reside in `reactions/medicine.yml`. The examples I provided are the first 3 reactions you added to `reactions/chemicals.yml`. They are in `reactions/medicine.yml` already. The links are to their positions in `reactions/medicine.yml` on master.

**Comment by Soundwavesghost** [comment]
Ah I see what you are saying. I was just going down a list made via the reagents/medicine.yml and since those were in the reactions/medicine.yml I added them.

**Comment by Moneyl** [comment]
I went through them and they're all present in `reactions/medicine.yml` on master. Sorry I didn't notice this when you were working on this on discord. I thought you were adding new chemicals. Don't let this discourage you from contributing more. Check with us again next time you're working on something and we'll make sure it's not something that's already done / in progress. You're able to close the PR with the "Close pull request" button at the bottom of the chatbox.

firefox_72rvxOnTwB

**Comment by Soundwavesghost** [comment]
I did these before you started doing it. But its okay.

**Pull request closed without merging**
