### PR TITLE
Adjust character name validation

### PR DESCRIPTION
**Pull request by Samsterious**
## About the PR
This is a reflection up from [Delta-V #14](https://www.github.com/DeltaV-Station/Delta-v/pull/14), which was also merged with [Nyanotrasen #1566](https://www.github.com/Nyanotrasen/Nyanotrasen/pull/1566). It was recommended I throw this up here too, so here we are! Here is a brief summary of what this does:

- Numeric digits are no longer permitted in character names
- The following Unicode subheadings have been added to the list of permitted characters:
  -  Latin-1 Supplement: Letters I
  - Latin-1 Supplement: Letters II
  - Latin-1 Supplement: Letters III
  - Latin Extended A: European Latin

### Media
Untitled

### Changelog
:cl: Fireheart
- tweak: Adjusted character name validation

### CODE REVIEW

**Review by AJCM-git — CHANGES_REQUESTED** [review]
We want to allow numbers in names for certain situations so i think the best solution here would be making `CCVars.RestrictedNames` have "levels" that restrict more and more the higher it is

**Comment by Samsterious** [comment]
I'm thinking about backwards compatibility. Ideally, I'd coerce `True` and `False` into `1` and `0` restriction levels, respectively, but `CVarsDef` does not seem suitable for this approach seeing as its instances are strictly typed.

Creating a breaking change seems inappropriate; perhaps a better approach is to add `IC.numeric_names`?

**Comment by metalgearsloth** [comment]
@Samsterious are you coming back to this

**Comment by Samsterious** [comment]
Sorry, I've been out of town and will be for some time. I will probably not be able to work on this until I've gotten back or at least established a routine.

**Pull request closed without merging**
