### PR TITLE
Fix rounds restarting in the next round

### PR DESCRIPTION
**Pull request by metalgearsloth**
Doesn't fix them restarting in lobby I think but should fix most of it.

### CODE REVIEW

**Comment by deltanedas** [comment]
could just add that to RoundRestartCleanup too no

**Comment by metalgearsloth** [comment]
> could just add that to RoundRestartCleanup too no

Yeah prolly my rider was taking a shit.

**Comment by deltanedas** [comment]
mike alpha tango romeo india xray

**Comment by lzk228** [comment]
i remember like there was an opened issue for that

**Pull request merged**
