### PR TITLE
add high value loot spawner

### PR DESCRIPTION
**Pull request by MisterMecky**
## About the PR

Adds a high value loot spawner, to be used to replace a number of guaranteed high value loot spawns on maps.

Draft until its figured out what we want it to spawn.
## Why / Balance

Reduce powergaming potential (Why was a web vest even mapped?)

Discord discussion at:
https://discord.com/channels/310555209753690112/1227276757069992049

## Technical details

N/A
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
could spawn low TC cost handpicked syndie items, as well as improvised weapons, maybe even a packet of donk pockets :D

**Comment by rosieposieeee** [comment]
i think a larger issue is players metagaming the positions rather than the loot itself. it would be nice to have like a bazillion possible loot spawners but only, say, three are chosen at mapinit

**Comment by SlamBamActionman** [comment]
It should be fairly easy to do with a component system. 

- Check for all entities with the component
- (Optional) Sort the components based on a group property (e.g. a string like "NorthSpawn", "EastSpawn", so that high value loot can be spread out around the station)
- Select # number of entities based on a set value (could be overriden by a component probably)
- Run spawn logic

**Comment by deltanedas** [comment]
> i think a larger issue is players metagaming the positions rather than the loot itself. it would be nice to have like a bazillion possible loot spawners but only, say, three are chosen at mapinit

theres an idea to have dungeon mapgen used for certain areas in maints to have random rooms generated, this would result in less metagamability of gamer loot

**Comment by MisterMecky** [comment]
I agree that having a large number of spawning locations with only set number of spawns would be better.

**Comment by FungiFellow** [comment]
I still see mapped in gamer loot rushed roundstart. This is a much needed fix to introduce a chance of some random joe getting it instead of _{Insert Powergamer Name}_ getting it for the umpteenth time letting them have a distinct combat advantage

**Pull request closed without merging**
