### PR TITLE
Container light occlusion

### PR DESCRIPTION
**Pull request by unusualcrow**
#515 
Requires https://github.com/space-wizards/RobustToolbox/pull/967

Allows containers to be defined as light occluding or not.

Current issue is I have no idea how to implement this for inventory slots with the way they're currently defined and container code is a big shitty mess.

### CODE REVIEW

**Comment by unusualcrow** [comment]
will check when I'm home

**Comment by SweptWasTaken** [comment]
This gonna get updated? Seems [this engine pr](https://github.com/space-wizards/RobustToolbox/pull/967) hasn't been worked on for a while...

**Comment by unusualcrow** [comment]
nope but it needs to be fixed eventually, there's just weird recursion shit that i don't know a solution for in the engine PR

**Comment by FL-OZ** [comment]
I took a stab at this. It's tricky. From my understanding, the best route is to have a StorageComponent check its Parent if any, and if its parent occludes light, it should too. *circumstances permitting ofc, if closet and door closed etc.)

**Comment by PJB3005** [comment]
I basically implemented the exact same system in-engine for sprites now because it was necessary to optimize sprite rendering. Probably good for inspiration/hooking into.

https://github.com/space-wizards/RobustToolbox/blob/99933499b787a7607d217ceaadfb0dfd384ae750/Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs#L67

**Comment by unusualcrow** [comment]
tried it again and still don't know how to solve this, it's beyond my knowledge

**Pull request merged**
