### PR TITLE
Remove manual localization from action entity prototypes

### PR DESCRIPTION
**Pull request by DrSmugleaf**
## About the PR
This is done automatically by EntityPrototype already, and now that actions are entities they should use that.

## Technical details
The only changes should be replacing localized names and descriptions with the direct string, and deleting the now unused (if not used anywhere else in the code) localized name and description from .ftl files.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
All actions now support localization by default for their name and description, with the already existing EntityPrototype localization pattern.
Any existing localizations with the old keys will break for downstreams until they update them to the existing EntityPrototype pattern (ent-id, ent-id.desc, ent-id.suffix)

### CODE REVIEW

**Comment by rbertoche** [comment]
Have you considered how this makes the job of maintaining other locales a lot harder?

What are we supposed to do as a workflow for merge now? Manually check for every upstream prototype description change every time we merge? What about when you change an ID, which is often. We need to manually check for that too?

What about new entities? We need to manually collect the names and description strings added, translate them as usual, and then also manually write up the FTLs from scratch? Just so english names and descriptions are marginally easier to add? Without even having a similar file in english to proof check if any strings are missing? How are we supposed to review our translations? Also manually visiting every pertinent prototype file?

Keep in mind there more than 700 FTL files in en-US already, which is a lot. But prototypes are more than double, more than 1500! So technically we will have to check for changes in 3 times the amount of files as usual, but also files which change way more often than FTL strings. This is humongously larger than the amount of FTL files or strings any contributor has to touch to add prototypes in english only.

Usually the person doing the translation of a merge has to read a diff of about 1000 lines long every time we merge. The merge we're planning for instance gives out a 923 lines long diff for Resources/Locale/en-US. Now, if I look at the same diff but on Resources/Prototypes, that 6592 lines, so 7 times more work than the usual not that short 1000 lines, plus also being way harder since it's an entirely different syntax which doesn't even use the same case. And that's for a mere 8 days long merge.

Compare that work to just replicating all the changes you do to Resources/Locale/en-US directory, which is not little work either, but is what we've been doing for more than a year. This is an insanely higher barrier for us to keep existing.

Having strings separated from yml prototypes can even reduce merge conflicts within you people, since when someone only changes a string it won't conflict with someone renaming a component or changing a stat.

I'm not sure how much my opinion counts but since I assume you don't deliberately want to make supporting languages other than english so harder they might not exist I ask you please to reconsider this and also not do further changes of this nature, since clearly the more FTL strings your code has, the more inclusive it is.

Also even if it were a lot of work to have to edit 2 files instead of 1 for prototype descriptions and names wasn't a marginal difference, that's only done once for each new prototype, while the extra work we'll need to do to at every merge keeps adding up and if changes like this are kept and go on we will never be done with it unless we just stop getting your new content, which would be really lame.

Cheers

**Comment by rbertoche** [comment]
Why not using cases like this as the convention instead of just removing names and descriptions from ftl?

en-US/prototypes/catalog/fills/crates/botany-crates.ftl
```
ent-CratePlantBGone = Bulk Plant-B-Gone crate
    .desc = From Monstano. "Unwanted Weeds, Meet Your Celestial Roundup!"
```

Resources/Prototypes/Catalog/Cargo/cargo_botany.yml
```
- type: entity
  id: CratePlantBGone
  parent: CrateGenericSteel
  components:
    - type: StorageFill
      contents:
        - id: JugPlantBGone
          amount: 5
```

**Comment by mirrorcult** [comment]
im confused what the complaint is with how this changes workflow? what does your guys workflow for translating currently look like?

**Comment by mirrorcult** [comment]
because this seems like something perfectly solvable with just tooling/workflow changes, we're aware of tooling for this made by the RU community (https://github.com/space-syndicate/space-station-14/tree/master/Tools/ss14_ru). is it worth upstreaming/genericizing this?

**Comment by DrSmugleaf** [comment]
> Have you considered how this makes the job of maintaining other locales a lot harder?

Yes, that is why the breaking changes explicitly mention other locales, as I am also developing my own fork.
As noted this makes it easier for downstreams to localize without worrying about what upstream does as before actions wouldn't have been localizable at all if they didn't have a fluent id.
See here for some examples of other contributors previously having to fix such errors: https://github.com/space-wizards/space-station-14/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Amorb0+is%3Aclosed++loc

> What are we supposed to do as a workflow for merge now? Manually check for every upstream prototype description change every time we merge? What about when you change an ID, which is often. We need to manually check for that too?
> What about new entities? We need to manually collect the names and description strings added, translate them as usual, and then also manually write up the FTLs from scratch? Just so english names and descriptions are marginally easier to add? Without even having a similar file in english to proof check if any strings are missing? How are we supposed to review our translations? Also manually visiting every pertinent prototype file?

Russian downstreams have some tooling for localization changes here https://github.com/space-syndicate/space-station-14/tree/master/Tools/ss14_ru
I don't know if they currently use a CI workflow to check for missing entity localization, if not here's sample integration test code to check if names, descs and suffixes in entity prototype names, descs and suffixes are the same in yaml and your locale in your codebase:
```csharp
var settings = new PoolSettings { Dirty = true };
await using var pair = await PoolManager.GetServerClient(settings);
var server = pair.Server;

var entityMan = server.ResolveDependency<IEntityManager>();
var prototypeMan = server.ResolveDependency<IPrototypeManager>();
var localization = server.ResolveDependency<ILocalizationManager>();

await server.WaitPost(() =>
{
	foreach (var entity in prototypeMan.EnumeratePrototypes<EntityPrototype>())
	{
		if (entity.Abstract)
			continue;

		var locData = localization.GetEntityData(entity.ID);
		if (entity.SetName != null && entity.SetName == locData.Name)
		{
			// name is not localized differently
		}

		if (entity.SetDesc != null && entity.SetDesc == locData.Desc)
		{
			// desc is not localized differently
		}

		if (entity.SetSuffix != null && entity.SetSuffix == locData.Suffix)
		{
			// suffix is not localized differently
		}
	}
});
```

Here's another sample integration tests cript to automatically create .ftl files for all entity prototypes that need one:
```csharp
var settings = new PoolSettings { Dirty = true };
await using var pair = await PoolManager.GetServerClient(settings);
var server = pair.Server;

var entityMan = server.ResolveDependency<IEntityManager>();
var mapManager = server.ResolveDependency<IMapManager>();
var prototypeMan = server.ResolveDependency<IPrototypeManager>();

var folderPath = "C:\\Projects\\space-station-14\\Resources\\Locale\\nl-NL"; // TODO change this to match your project and locale path
var writes = new List<Task>();
await server.WaitPost(() =>
{
	foreach (var entity in prototypeMan.EnumeratePrototypes<EntityPrototype>())
	{
		if (entity.Abstract)
			continue;

		var fluentId = $"ent-{entity.ID}";
		var lines = string.Empty;

		if (entity.SetName != null)
		{
			lines += $"{fluentId} = {entity.Name}";
		}

		if (entity.SetDesc != null)
		{
			lines += $"\n    .desc = {entity.Description}";
		}

		if (entity.SetSuffix != null)
		{
			lines += $"\n    .suffix = {entity.SetSuffix}";
		}

		if (!string.IsNullOrWhiteSpace(lines))
		{
			lines = $"# TODO Fluent\n{lines}";
		}

		var filePath = $"{folderPath}\\{entity.ID}.ftl";
		if (File.Exists(filePath))
			continue;

		writes.Add(File.WriteAllTextAsync(filePath, lines));
	}
});

await Task.WhenAll(writes);
```

> Keep in mind there more than 700 FTL files in en-US already, which is a lot. But prototypes are more than double, more than 1500! So technically we will have to check for changes in 3 times the amount of files as usual, but also files which change way more often than FTL strings. This is humongously larger than the amount of FTL files or strings any contributor has to touch to add prototypes in english only.
> Usually the person doing the translation of a merge has to read a diff of about 1000 lines long every time we merge. The merge we're planning for instance gives out a 923 lines long diff for Resources/Locale/en-US. Now, if I look at the same diff but on Resources/Prototypes, that's 6592 lines, so 7 times more work than the usual not that short 1000 lines, plus also being way harder since it's an entirely different syntax. And that's for a mere 8 days long merge.
> Compare that work to just replicating all the changes you do to Resources/Locale/en-US directory, which is not little work either, but is what we've been doing for more than a year. This is an insanely higher barrier for us to keep existing.

To do this see the scripts above and run them on the commit before and commit after, and either diff them or (easier) have another integration test that would print which ones changed.

> Having strings separated from yml prototypes can even reduce merge conflicts within you people, since when someone only changes a string it won't conflict with someone renaming a component or changing a stat.

The overhead of merge conflicts is not worth it, as changing a name, description or suffix upstream usually comes with more than changing just that. It often conflicts regardless if the change is in the same file.
This is also supported for other codebases or games that would prefer to localize their prototypes directly, with no relation to this codebase, or space station 14 in general.

> I'm not sure how much my opinion counts but since I assume you don't deliberately want to make supporting languages other than english so harder they might not exist I ask you please to reconsider this and also not do further changes of this nature, since clearly the more FTL strings your code has, the more inclusive it is.
> Also even if it were a lot of work to have to edit 2 files instead of 1 for prototype descriptions and names wasn't a marginal difference, that's only done once for each new prototype, while the extra work we'll need to do to at every merge keeps adding up and if changes like this are kept and go on we will never be done with it unless we just stop getting your new content, which would be really lame.

We regularly have Morty (russian contributor downstream) open PRs upstream for localization-related things and ask them about it too.
FTL strings don't make it any more inclusive with the tools given above as not only us, but other codebases you pull code from, would need to remember to always localize everything without mistakes or cause a breaking change for any downstreams.
This has already happened many times, which is why we do it automatically, reducing the work for both upstreams and downstreams, where upstream doesn't include only us.

As for other tools that would help with the maintainability of FTL, that would be a language server or plugin for .yml and .ftl files that lets you navigate between used fluent loc ids and their declarations.
Work for that was started in https://github.com/DrSmugleaf/intellij-fluent-support-plugin but never finished, as we opted for a language server instead.
Here's some documentation for that in VS: https://learn.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol?view=vs-2022
And VSCode: https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

**Pull request merged**
