### PR TITLE
File scoped namespaces

### PR DESCRIPTION
**Pull request by Visne**
Do I spend my maintainer role to selfmerge this beauty?

Edit: HackMD to help contributors with open PRs: https://hackmd.io/CPAD0qpkTdm5kMe6b9NC5Q, can be linked in the Discord server with the `!namespace` bot command.

### CODE REVIEW

**Comment by mirrorcult** [comment]
visne farming diff on the contributors graph

**Comment by Visne** [comment]
> 
> 
> visne farming diff on the contributors graph

Smug has to share...

**Comment by 20kdc** [comment]
...excuse me but won't this break, like, *every* PR

**Comment by 20kdc** [comment]
Answer: Yes

```
Removing Resources/Locale/en-US/administration/verbs/explode-verb.ftl
Removing Resources/Locale/en-US/administration/verbs/delete-verb.ftl
Removing Resources/Locale/en-US/administration/verbs/admin-add-reagent-verb.ftl
Removing Resources/Locale/en-US/administration/ui/admin-add-reagent-eui.ftl
Removing Content.Shared/MobState/IMobStateComponent.cs
Removing Content.Shared/Hands/Components/ISharedHandsComponent.cs
Removing Content.Shared/Botany/IPlantMetabolizable.cs
Removing Content.Shared/Administration/AdminAddReagentEuiState.cs
Auto-merging Content.Server/Solar/EntitySystems/PowerSolarControlConsoleSystem.cs
CONFLICT (content): Merge conflict in Content.Server/Solar/EntitySystems/PowerSolarControlConsoleSystem.cs
Auto-merging Content.Server/Solar/Components/SolarControlConsoleComponent.cs
CONFLICT (content): Merge conflict in Content.Server/Solar/Components/SolarControlConsoleComponent.cs
Auto-merging Content.Server/Objectives/Conditions/StealCondition.cs
Auto-merging Content.Server/Instruments/InstrumentSystem.cs
CONFLICT (content): Merge conflict in Content.Server/Instruments/InstrumentSystem.cs
Auto-merging Content.Server/Instruments/InstrumentComponent.cs
CONFLICT (content): Merge conflict in Content.Server/Instruments/InstrumentComponent.cs
Removing Content.Server/Hands/Components/IHandsComponent.cs
Removing Content.Server/Explosion/TriggerSystem.cs
Removing Content.Server/Explosion/ExplosionHelper.cs
Auto-merging Content.Server/Construction/Conditions/WirePanel.cs
CONFLICT (modify/delete): Content.Server/Computer/ComputerUIActivatorSystem.cs deleted in HEAD and modified in 9dd7a6ec5. Version 9dd7a6ec5 of Content.Server/Computer/ComputerUIActivatorSystem.cs left in tree.
Auto-merging Content.Server/Communications/CommunicationsConsoleComponent.cs
CONFLICT (content): Merge conflict in Content.Server/Communications/CommunicationsConsoleComponent.cs
Auto-merging Content.Server/Chemistry/TileReactions/CleanTileReaction.cs
Removing Content.Server/Chemistry/PlantMetabolism/RobustHarvest.cs
Removing Content.Server/Chemistry/PlantMetabolism/Diethylamine.cs
Removing Content.Server/Chemistry/PlantMetabolism/Clonexadone.cs
Removing Content.Server/Chemistry/PlantMetabolism/AffectGrowth.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustWeeds.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustWater.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustToxins.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustPests.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustNutrition.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustMutationMod.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustMutationLevel.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustHealth.cs
Removing Content.Server/Chemistry/PlantMetabolism/AdjustAttribute.cs
Auto-merging Content.Server/Cargo/Components/CargoConsoleComponent.cs
CONFLICT (content): Merge conflict in Content.Server/Cargo/Components/CargoConsoleComponent.cs
Removing Content.Server/Body/BodyManagerHealthChangeParams.cs
CONFLICT (modify/delete): Content.Server/Atmos/Components/BaseComputerUserInterfaceComponent.cs deleted in HEAD and modified in 9dd7a6ec5. Version 9dd7a6ec5 of Content.Server/Atmos/Components/BaseComputerUserInterfaceComponent.cs left in tree.
Removing Content.Server/Administration/UI/AdminAddReagentEui.cs
Auto-merging Content.Server/Access/Components/IdCardConsoleComponent.cs
CONFLICT (content): Merge conflict in Content.Server/Access/Components/IdCardConsoleComponent.cs
Auto-merging Content.Client/Entry/IgnoredComponents.cs
CONFLICT (content): Merge conflict in Content.Client/Entry/IgnoredComponents.cs
Removing Content.Client/Administration/UI/AdminAddReagentUI.cs
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by Visne** [comment]
> 
> 
> Answer: Yes
> 

You could probably have guessed that without running anything.

If you use Rider, then go to `namespace`, press Alt+Enter and press `To File-scoped namespace` for every file in your PR, then merge master into your PR. If you have a lot of files, just do solution wide and then merge master into your PR.

image

If you use VS2022, I'm sure they have something similar.

If you use VS2019, you should upgrade.

If you use vim/emacs/something else cursed, you can probably figure out what to do yourself.

**Comment by PJB3005** [comment]
The conflicts are still a pain to deal with, sorry.

**Pull request closed without merging**
