### PR TITLE
dragon antag refactor

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
made dragon use antag refactor stuff and remove all mention of GenericAntag

depends on #28216

## Why / Balance
copypasta bad

## Technical details
- added AntagRandomSpawn for rules to create antag spawners at random tiles on a station
- added AntagSpawner for rules to shrimply spawn a mob for the spawned entity
  dont know if this is already possible somehow but whatever

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Errant-4** [comment]
Consider that admins might want to spawn a dragon specifically for being a dragon, without the game rules. 
Like a John Nanotrasen visit to the station or something

**Comment by QuietlyWhisper** [comment]
> Consider that admins might want to spawn a dragon specifically for being a dragon, without the game rules. Like a John Nanotrasen visit to the station or something

For the second purpose a custom prototype is uploaded anyways, but being able to just spawn a mob dragon anywhere would be appreciated in some cases

**Comment by Kadeo64** [comment]
does this fix dragon devour bug

**Comment by deltanedas** [comment]
no see dead dragon rework pr

**Pull request merged**
