### PR TITLE
Arachnid plushie

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
added arachnid plushie
plushie sprite made by girthquake

## Why / Balance
we have plushie of lizard, moth, and diona so why not arachnid?

## Technical details
3

## Media
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Is plushie

**Changelog**
:cl: Dutch-VanDerLinde, girthquake
- add: Added an arachnid plushie!

### CODE REVIEW

**Comment by PoorMansDreams** [comment]
Cant go wrong with more plushi

**Comment by K-Dynamic** [comment]
The fumos grow

**Comment by TheShuEd** [comment]
When plushie naked human

**Comment by lzk228** [comment]
> When plushie naked human urist

Soon™

**Comment by MACMAN2003** [comment]
the naked Urist McPlushie and his activation sound: screaming

**Comment by TheShuEd** [comment]
#23518 
@MACMAN2003

**Comment by Emisse** [comment]
goncflict

**Comment by Dutch-VanDerLinde** [comment]
Aaaaaaa

**Comment by Dutch-VanDerLinde** [comment]
conflict fixed

**Comment by Dutch-VanDerLinde** [comment]
turns out the name of the bee plushie is "plushie_h" and i deleted it cause i thought it wasnt supposed to be there

**Pull request merged**
