### PR TITLE
Omnidirectional Character Sprite Preview

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
## About the PR

- Adds all four sprite directions to the character setup UI.
- Makes the right lobby panel character preview a bit larger

## Why

Easier to customize the character if you can see the character..
[Also someone in the discord wanted it](https://discord.com/channels/310555209753690112/346743671787356160/1143096027533021285)

## Media

FFuJ3rMonZ

### CODE REVIEW

**Comment by potato1234x** [comment]
why not make them smaller and put them in a 2x2 box to save space

**Comment by UbaserB** [comment]
or that, there are multiple different approaches to this. i personally like it vertical

**Comment by metalgearsloth** [comment]
Wouldn't it be better to just rotate the sprite like borgs do?

**Comment by DEATHB4DEFEAT** [comment]
> Wouldn't it be better to just rotate the sprite like borgs do?

what?

**Comment by Morb0** [comment]
> > Wouldn't it be better to just rotate the sprite like borgs do?
> 
> what?

preview

**Comment by Partmedia** [comment]
Thank you for your contribution. While it sounds like there may be ways to do this better, it does seem to me that this is an improvement over what exists.

**Comment by metalgearsloth** [comment]
Morty's going to wrap this into https://github.com/space-wizards/space-station-14/pull/19741 and credit you.

**Comment by DEATHB4DEFEAT** [comment]
> Morty's going to wrap this into https://github.com/space-wizards/space-station-14/pull/19741 and credit you.

oh cool

**Pull request closed without merging**
