### PR TITLE
Changes various tool shapes and makes the utility/sec belt accommodate them.

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
The wrench, welder, crowbar, and baton now have unique sizes rather than the generic normal/small sizes.
The wrench is 1x3
the welder is the gun shape
the crowbar/baton are 1x4 and normal sized.

## Why / Balance
How is a crowbar the same size as a screwdriver?
Now it's harder for non-engineers to carry an entire set of tools on them since most people don't have access to a utility belt.

## Media
image
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Crowbars and stun batons are now long in the inventory grid
- tweak: Welding tools and wrenches are now uniquely shaped
- tweak: Toolbelts and security belts now accommodate crowbars and security batons specifically

### CODE REVIEW

**Comment by mirrorcult** [comment]
i dont think this is very interesting

**Comment by Krunklehorn** [comment]
I think it's cool we're playing around with the grid system, but if the primary purpose is to dissuade non-engineers from carrying a full set of tools...well...utility belts can be printed at lathes.

As for security... you're gonna wanna make the same change to chest rigs, too.

**Comment by K-Dynamic** [comment]
Wrench and welder feels cursed but I'm intriuged by the crowbar and baton

**Comment by musicmanvr** [comment]
All this pr will do is just make the lives of anyone who regularly carries these items more miserable, the only thing that's maybe passable is the welder, but making making these items take up more space without any kind of compromise is silly. This'd be more understandable if this wasn't explicitly an objectively bad change.

**Comment by musicmanvr** [comment]
> > I think it's cool we're playing around with the grid system, but if the primary purpose is to dissuade non-engineers from carrying a full set of tools...well...utility belts can be printed at lathes. Even if I'm a passenger, I can spend a few minutes getting cloth and just toss it at cargo. 9/10 players will make me a belt if I give them the resource.
> 
> > 
> 
> > As for security... you're gonna wanna make the same change to chest rigs, too.
> 
> 
> 
> still gives several extra steps required to efficiently carry them around.

This doesn't make sense. Given what you use each tool for, the wrench should not be changed, and the crowbar at MOST should be 3 tiles. A wrench, wire cutter, and screwdriver should stay as they are, and the welder and crowbar are passable. The baton at most should be 3 as well. 4 long is an incredibly inconvenient shape for practically anyone.

**Comment by musicmanvr** [comment]
> It makes zero sense for a crowbar to be the same size as a screwdriver, and the screwdriver/wirecutters shouldn't be tiny items. Not everyone needs to be carrying a full set of tools around at all times, so making them harder to carry around without a toolbelt is what I'm trying to do here.
>

The crowbar bit is understandable, but the wrench change isn't. If we wanna bring up the "makes sense" argument then changing the crowbar (a one handed item) and the baton (a one handed item) to be comically large is silly. They fit in belts. The wrench is a small item, there's no need to modify it.

**Comment by musicmanvr** [comment]
I understand what you're trying to do here, but this just seems like a solution to an issue that doesn't exist imho.

**Comment by Hmeister-real** [comment]
There needs to be an empty 4x4 grid on the utility belt so you can fit an RTG or a stack of Cabling while carrying every tool as an engineer, also the wrench being bigger makes no sense, its not a monkey wrench its a normal wrench for nuts and bolts

**Comment by Ilya246** [comment]
i think this is overall bad for the game, it just makes toolbelts even more of a necessity
this change will pretty much only be bad for people who don't go and loot a toolbelt while not affecting true powergamers that loot/make a belt as well as the other tools

**Comment by UbaserB** [comment]
i love it, makes the belt more dynamic and actually kind of fits the sprite now. The people complaining about this change are probably the kinds of people that store their giant tools in their duffle bag and want to optimise gameplay speed. They're tools, not meant to be super fast unlike a gun. For secbelt, it's probably faster now since there's a designated place for the baton and its bigger (reducing chance of misclicking) and the other objects are standard 1x2

**Comment by MACMAN2003** [comment]
I don't feel like this is a good addition

**Comment by potato1234x** [comment]
pretty sure it was explicitly stated by a maintainer at one point (i may be misremembering) that the tools and toolbelts were to remain normalised shapes

**Comment by K-Dynamic** [comment]
> > There needs to be an empty 4x4 grid on the utility belt so you can fit an RTG or a stack of Cabling while carrying every tool as an engineer
> 
> image does this look good? It's a 2x2 by the way.

It's funny because toolbelts have items literally hanging off them on their sprites (batons on sec belts are quite long)

But overall I don't really get what this pr is trying to solve; it's gonna be rather hell to investigate every sprite and making it conform to a shape, which would call into question standardised item sizes rework

**Comment by IProduceWidgets** [comment]
I think this might be more okay with #25834

**Comment by rosieposieeee** [comment]
i think this is fine. welding tool makes the most sense. i believe the grey crowbar used to be larger than the emergency red one, so maybe that should be brought back, making it only 1x3 or something. i guess the wrench is dubious, but i could definitely see most wrenches being larger and heavier than a screwdriver. i agree the belts being a weird shape is... unusual... but i dunno, its kinda fun, and it *does* fit the sprite.

**Comment by metalgearsloth** [comment]
Overall maintainer opinion is dislike so going to reject it at this time.

**Pull request closed without merging**
