### PR TITLE
Adds A Water Reaction

### PR DESCRIPTION
**Pull request by Geekyhobo**
## About the PR

Adds a water reaction, 2 H : 1 O = 3H2O, 
It's really just for the chemist who likes to optimize their chems, and for when the chem department has no sink.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: NT put its best chemists into developing a reaction for creating water

### CODE REVIEW

**Comment by Geekyhobo** [comment]
fucked up my git stuff closing

**Comment by lzk228** [comment]
i think infinity water is vetoed or smth

**Comment by DogZeroX** [comment]
yeah it is.

**Comment by Geekyhobo** [comment]
> i think infinity water is vetoed or smth

Reason #2 to keep this closed

**Comment by Aisu9** [comment]
chemistry already come mapped with a sink for infinite water anyway

**Comment by LankLTE** [comment]
> chemistry already come mapped with a sink for infinite water anyway

a lot of chems dont have one, but yeah i think this is a bad idea for other reasons

**Comment by Emisse** [comment]
i thought sinks had limited amounts with very slowly generating water

**Comment by LankLTE** [comment]
> i thought sinks had limited amounts with very slowly generating water

yeah but they infinitely generate it

**Comment by deltanedas** [comment]
plumbing just a week away

**Pull request closed without merging**
