### PR TITLE
Service workers antagonist fix.

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Despite not being an intern role, you could not be a traitor or thief when rolling the role. This fixes that.
Hosted an internal poll in the staff channel, with the general consensus being to allow antagonism for the job.
https://discord.com/channels/310555209753690112/1193403928096821358/1294898153346301993

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ubaser
- fix: Service workers can now be antagonists.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Damn, no more picking Service Worker on low pop so I could bartend, cook food, and handle botany at the same time. Also the service requirements are already so low for chef+bartend+botany I feel like fellas would never really choose em, the role is in a very strange spot.

**Comment by mierdapovareshka** [comment]
бля чё это за говно ебаное

**Comment by Golinth** [comment]
Dunno how I feel about this. Despite how it was originally envisioned, Service Worker has grown to be the “do-it-all” of the service department, and are practically the senior role that never got removed.

**Comment by Iamgoofball** [comment]
Why does this job even exist?

**Comment by Golinth** [comment]
> Why does this job even exist?

To allow new players to learn about most service roles, without being dedicated to a specific one.

**Comment by Iamgoofball** [comment]
That seems like a solution in search of a problem, they can just learn the jobs as an Assistant if they don't want to commit.

**Comment by Iamgoofball** [comment]
Why does Service need its' own Assistant role? Assistant already exists.

**Comment by UbaserB** [comment]
> Why does Service need its' own Assistant role? Assistant already exists. New players are either going to be
> 
> 1. reading the wiki, which tells them about the HoP
> 2. asking for help on radio, at which point a crewmember can point them to the HoP
> 3. asking for help in person, at which point a crewmember can point them to the HoP

We know, its undergoing discussion as to what should be done with the role but this is a fine QoL fix in the meanwhile.

**Comment by Sarahon** [comment]
Why are any of the intern roles locked out anyway?

**Comment by UbaserB** [comment]
Going to draft this temporarily while reworking it to be a proper role without locking you out of being antag, as per a poll I hosted internally

**Comment by superjj18** [comment]
> Why are any of the intern roles locked out anyway? 

I think in the past they were used as greytide but with department access

**Comment by Sarahon** [comment]
> > Why are any of the intern roles locked out anyway?
> 
> I think in the past they were used as greytide but with department access

Honestly this is an issue with how department job role abandonment is viewed also really. Part of me wanted them punished more, but the other issue is that, you could be a returning player and not have access to the intern role and literally be shit on for being a "bad xyz" at whatever department because you dared take a break.

**Comment by superjj18** [comment]
> > > Why are any of the intern roles locked out anyway?
> 
> > 
> 
> > I think in the past they were used as greytide but with department access
> 
> 
> 
> Honestly this is an issue with how department job role abandonment is viewed also really. Part of me wanted them punished more, but the other issue is that, you could be a returning player and not have access to the intern role and literally be shit on for being a "bad xyz" at whatever department because you dared take a break. 

The only reason you'd truly be shit on is if you went straight into command without relearning as the standard job role.  Command members are required by the rules to understand their department.(unless your an engineer and the entire station is pissed off about not having power lol)

**Comment by Djungelskog2** [comment]
Shouldn't be an intern because it's a completely unique role and isn't just "X role but with an A for its job logo"
Even has unique access and clothes

**Pull request merged**
