### PR TITLE
tweak(Radiation Suits): Increase damage taken by 1000%

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Reduced the resistance from 99.9% to 99% a 1000% or 10x increase in damage taken from radiation.
(it doesn't even matter)

## Why / Balance

Resolves https://github.com/space-wizards/space-station-14/issues/30387

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by TheDoctor1977** [comment]
Why can’t it just be 100%? I’m pretty sure CE hardsuit has that, so it’s not impossible.

**Comment by IProduceWidgets** [comment]
hmm, yeah that is a little odd. Should also [change this to 0.01](https://github.com/space-wizards/space-station-14/blob/5485ae25e05b43979db25e053e720fee9c2663f7/Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml#L333)

**Comment by Ilya246** [comment]
i think radsuits giving you full or near-full protection is fine since they give you radiation protection and nothing else, not even space protection

**Comment by Brandon-Huu** [comment]
> Why can’t it just be 100%? I’m pretty sure CE hardsuit has that, so it’s not impossible.

So that you can still die from radiation if you spend 10 years cooking in the chamber.
Only god king is CE

**Pull request merged**
