### PR TITLE
Sprites for drinks without sprite (attempt 2)

### PR DESCRIPTION
**Pull request by RumiTiger**
In my past PR, I broke something, so I had to create a new PR.

## About the PR
I added sprites in a metamorph glass for drinks such as:
• Coffee
• Cola
• Dr Gibb
• Green tea
• Ice
• Iced green tea
• Lemon juice
• Moonshine
• Orange juice
• Space mountain wind
• Space-up
• Sugar
• Tea
• Tequilla
• Tonic
• Watermelon juice

## Why / Balance
Why not?

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
IMG_20240421_221206_639

• Coffee
photo_2024-03-11_19-13-21

• Cola
image

• Dr Gibb
photo_2024-03-11_19-13-20

• Green tea
photo_2024-03-11_19-13-21 (3)

• Ice
photo_2024-03-11_20-11-06

• Iced green tea
photo_2024-03-11_19-13-20 (2)

• Lemon juice
photo_2024-03-11_19-13-20 (3)

• Moonshine
image

• Orange juice
photo_2024-03-11_19-13-21 (5)

• Space mountain wind
photo_2024-03-11_19-13-20 (4)

• Space-up
photo_2024-03-11_19-13-21 (6)

• Sugar
photo_2024-03-12_14-17-22

• Tea
image

• Tequilla
photo_2024-03-11_19-13-21 (8)

• Tonic
photo_2024-03-11_19-13-21 (9)

• Watermelon juice
photo_2024-03-12_12-18-29

**Changelog**
🆑
• add: Added sprites for some drinks without their own sprite and changed the sprites of some drinks

### CODE REVIEW

**Comment by UbaserB** [comment]
you broke this one too

**Comment by RumiTiger** [comment]
> you broke this one too

Yeah…

**Comment by RumiTiger** [comment]
> you broke this one too

I did it!!!

**Comment by metalgearsloth** [comment]
Oh my lord that commit history.

**Pull request merged**
