### PR TITLE
Makes security a bit brighter

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Changes the uniform color of sec from a desaturated carmine-ish color, in to a red colorpicked from baystation.

Also fixes the vox warden winter coat being on the incorrect warden's winter coat.

## Why / Balance
I feel like the carmine is kind of odd-looking ingame and doesn't fit security very well. This is what I was *originally* going to go with, before I decided last-minute to change it to what it is ingame currently.

This is pretty close to the cadet red uniform, of course, but so are most of the intern uniforms. It's a problem with them, and not this color for security.

## Media
Content Client_Bicx0t4MUw

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- tweak: Security are now a bit brighter visually.

### CODE REVIEW

**Comment by DieselMohawk** [comment]
It would be nice if there was a side by side comparison of the sprites.

**Comment by DieselMohawk** [comment]
Oh, before I forget, do you plan to alter the color of the senior officer uniform or the sec beret?

**Comment by Flareguy** [comment]
> Oh, before I forget, do you plan to alter the color of the senior officer uniform or the sec beret?

The beret was altered, I just chose not to show it since I didn't want to detract from the rest of security's wardrobe appearance.

As for the senior officer's clothes, I'm not touching any senior outfits until they're removed / redesigned. All of them have really bad designs that are either just plain uninspired, or really hard to differentiate between other jobs, due to all of them being entirely comprised of recolored parts.
If someone else wants to update them, they're free to, though.

**Comment by AlexUm418** [comment]
So only difference between officer and a cadet is that officers have a black thing on their right shoulder?

**Pull request merged**
