### PR TITLE
Craftable TIles (2.0)

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Adds certain floor tiles as craftable. This has a lot less item bloat than the last one and is on a proper master now.
The eight steel, white and dark tile variants along with the shuttle tiles are left as comments for future use.
It also renames a few tiles and stacks to use "tile" instead of "floor" for consistency

adds:
- clown, lino and arcade carpets
- mosaic wood tile
- two circuit tiles
- four maint tiles
- gold and silver tiles

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- add: Added some existing floor tiles as craftable. Go nuts!

### CODE REVIEW

**Comment by moonheart08** [comment]
No, not even as comments for future use. This is still just needlessly bloating the files.
Remove the 8 variant tiles.

**Comment by deltanedas** [comment]
i really like the idea of being able to change tiles in-hand or with a screwdriver etc. as it means you can easily redecorate places and random tiles on wrecks can be stacked easily

**Comment by Alekshhh** [comment]
yeah I want to do that but I am not a coder so someone else would have to try it

**Comment by metalgearsloth** [comment]
You can just add the basic ones and leave variant modifying for later.

**Comment by Alekshhh** [comment]
I removed the 8 variant comments and shuttle comments so it's just the tiles stated in the description

**Pull request closed without merging**
