### PR TITLE
put flashes in all head of staff backpacks

### PR DESCRIPTION
**Pull request by randy10122**
## About the PR
also gives all heads their own bags in backpack.yml 
gives flashes to every head of staff as a means of self defence - also set up for when i (or someone else) ends up doing the telebaton
not set up for hos because i forgot
they don't need sunglasses because you can use flashes as a melee :)

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:randy
- tweak: All of the Heads of Staff have been issued flashes for self defence. Fun fact: You can flash single targets by hitting people with them in combat mode!

### CODE REVIEW

**Comment by randy10122** [comment]
wait no i forgot something i need to fix that tomorrow

**Review by moonheart08 — APPROVED** [review]

**Comment by deltanedas** [comment]
only 1 has sunglasses though...

**Comment by randy10122** [comment]
> only 1 has sunglasses though...

you can hit people with flashes to only flash them and not yourself :3

**Comment by randy10122** [comment]
whoops i fucked it

**Comment by randy10122** [comment]
okay this should be ready to merged. changed the changelog a little too

**Comment by GoodWheatley** [comment]
> only 1 has sunglasses though...

using a flash doesn't flash you, only the people in front of you/the person you clicked on

**Comment by randy10122** [comment]
> > only 1 has sunglasses though...
> 
> using a flash doesn't flash you, only the people in front of you/the person you clicked on

it flashes you if you dont have correct eye protection

**Comment by randy10122** [comment]
ill reopen this once i redo it. i fucked that repo so hard

**Pull request closed without merging**
