### PR TITLE
Lathe Categories

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds categories for filtering lathe recipes.
this isn't all-encompassing i just wanted some baseline stuff for other projects.

also sorts lathe recipes alphabetically & fixes some small issues with tooltips

## Why / Balance

We need it.

## Technical details

Adds a new nullable field to lathe recipe prototype plus a new LatheCategoryPrototype.

## Media

image
image
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: You can now sort lathe recipes by category.
- add: Recipes in lathes are now sorted alphabetically.

### CODE REVIEW

**Comment by TheShuEd** [comment]
what happens to an item that is not categorized? Will it generate check errors? Will it only show without a filter?

**Comment by EmoGarbage404** [comment]
> what happens to an item that is not categorized? Will it generate check errors? Will it only show without a filter?

items with no categories show up only under the "all" tab. They don't cause any errors.

**Comment by Ilya246** [comment]
why not just copy barotrauma for the UI

**Comment by EmoGarbage404** [comment]
> why not just copy barotrauma for the UI

because i don't feel like redoing the UI to add a small QOL feature.

**Comment by VektorZ1** [comment]
The expandable list of categories looks bad

**Review by mirrorcult — APPROVED** [review]

**Comment by CrigCrag** [comment]
should the parts button be a different shape from like every other button in the game

**Pull request merged**
