### PR TITLE
Added the makeshift laser carbine recipe

### PR DESCRIPTION
**Pull request by Vaaankas**
**Description**
Added the crafting recipe for the makeshift laser carbine

**Media**
https://i.imgur.com/HbNZwR2.png

- [+] I have added screenshots/videos to this PR showcasing its changes ingame

:cl: vanx
- add: Added the makeshift laser carbine crafting recipe

### CODE REVIEW

**Comment by mirrorcult** [comment]
this was deliberately removed

**Comment by mirrorcult** [comment]
although saying that im fine w/ this coming back with a better recipe than it used to have

**Comment by Vaaankas** [comment]
> although saying that im fine w/ this coming back with a better recipe than it used to have

do you think this recipe is good? it should only be available to RnD later into the round

**Review by EmoGarbage404 — COMMENTED** [review]
Pretty sure you can just use the power cell component instead of having a tag. Additionally, you dont need tags for every level of the machine parts. Also the unused ones don't need them, either.

**Comment by Vaaankas** [comment]
> Pretty sure you can just use the power cell component instead of having a tag. Additionally, you dont need tags for every level of the machine parts. Also the unused ones don't need them, either.

I was told it was wrong to use components for this purpose

**Comment by EmoGarbage404** [comment]
i mean, using components in crafting is used in places. Mechs use it for inserting a power cell during the construction graph. That seems like a better option than just making tags for every single entity, which really is quite strange.

**Comment by Vaaankas** [comment]
fair enough, will maybe come back to this later

**Pull request closed without merging**
