### PR TITLE
Adds "secoff --> security officer" and "secoffs --> security officers" to chat sanitizer

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Adds secoff --> security officer
Adds secoffs -> security officers

## Why / Balance

secoff is annoying to see in chat.

## Technical details

I don't think there are any.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

none
**Changelog**

:cl:
- add: secoff and secoffs are properly sanitized in chat.

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Is this valid?

**Comment by asperger-sind** [comment]
> Is this valid?

I would guess it is but it's encroaching on the territory of iconic slang

**Comment by TemporalOroboros** [comment]
Honestly, this is so entrenched it feels like sanitizing CentCom -> Central Command.

**Comment by LankLTE** [comment]
Secoff is something that people could reasonably say irl. This feels like saying “cop > police officer” to me.

**Comment by forgotmyotheraccount** [comment]
Yeah I agree I like sec/secoff as station slang, it's something I can see someone saying in real life, similar to 'FYI'.

**Comment by keronshb** [comment]
I think it's fine that secoff exists.

**Pull request closed without merging**
