### PR TITLE
PackedStation: More markers

### PR DESCRIPTION
**Pull request by 20kdc**
## About the PR

Janitor tries to sweep everything, but there's nothing for them to clean up.
Give them something to do by adding more messes.

I also added some TraitorDM PDA redemption machine markers while I was at it, since I needed to add them anyway.

**Changelog**

:cl:
- add: The litterbugs have been summoned to PackedStation to give the Janitor something to do. If they like it is not under consideration.
- fix: The delivery delay causing welding tanks in PackedStation to not be fuelled has been solved.
- fix: A light in PackedStation no longer occupies the interior of a wall.

### CODE REVIEW

**Comment by 20kdc** [comment]
oh, right: @TimrodDX ping for this since it touches PackedStation

**Comment by 20kdc** [comment]
do not merge this PR, I'll fix up the UIDs tomorrow after Timrod's PR gets through

**Comment by TimrodDX** [comment]
Sorry about that! Glad to see someone else putting spawners in.

**Comment by 20kdc** [comment]
Not a problem - I knew I should have asked about the mapping tepig...

**Comment by 20kdc** [comment]
So the mapping merge driver actually worked, but Timrod gave me a few other things to do while I'm here

**Comment by mirrorcult** [comment]
are all the changes you wanted to implement in?

**Comment by 20kdc** [comment]
Yup

**Comment by 20kdc** [comment]
so this PR is in the state where EFR is actually basing their branch off of it before this has even been merged, so I'd recommend merging at some point

**Pull request merged**
