### PR TITLE
Kettle updates

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

- Remove maintscalibur
- Leave a note in maintscalibur's place
- Remove mercenary gear from AI satellite
- Replace med's directional rwindows in the ward with regular directional windows
- Add camera outside the brig and outside the armoury
- Name a couple of unnamed cameras (Sec's shooting range hallway and engineering's reception)
- Move some wiring in the PA room away from the cable terminal in the PA room
- Move one of the gravitational singularity generators from the storeroom to the containment chamber to further encourage singulo use
- Radiation collectors start with filled tanks to decrease singulo setup time

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

No media required.

**Changelog**

no cl

### CODE REVIEW

**Comment by CatMagic1** [comment]
but why

**Comment by TsjipTsjip** [comment]
> but why

What change are you requesting additional reasoning on? I will happily clarify.

**Comment by CatMagic1** [comment]
> > but why
> 
> What change are you requesting additional reasoning on? I will happily clarify.

Sorry, maintscalibur

**Comment by TsjipTsjip** [comment]
> > > but why
> > 
> > 
> > What change are you requesting additional reasoning on? I will happily clarify.
> 
> Sorry, maintscalibur

Requested to be removed by mapping maintainers as it's been used as "gamer gear" too often. (Metagaming with map knowledge)

See related discussions [here](https://discord.com/channels/310555209753690112/771041304108072961/1165345668718673991) and [here](https://discord.com/channels/310555209753690112/771041304108072961/1165563214310948874).

**Comment by CatMagic1** [comment]
Sad, I've never even seen it

**Pull request merged**
