### PR TITLE
tweak(mime): clarify mime writing boring

### PR DESCRIPTION
**Pull request by lizelive**
we give them a white crayon for a reason. this pr is small nudge to get players into the right mimeset for the job.

## About the PR
update job-description-mime

## Why / Balance
mimes writing is boring. while this doesn't stop them from doing so, it gives them a little nudge to try miming out what they want. this will help players get into the mime mindset.

## Technical details
it's just a text change

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: mimes job description.
- tweak: give mime a poppy instead of a piece of paper.

### CODE REVIEW

**Comment by lzk228** [comment]
doesnt deserve a cl

**Comment by lizelive** [comment]
Nonverbally entertain the crew through body motions and imagination. Engage with light rivalry with the clown.

**Comment by lizelive** [comment]
> doesnt deserve a cl

can remove it but rather remind people stop writing.

**Comment by Ghagliiarghii** [comment]
"Tweak:     "

**Review by UbaserB — CHANGES_REQUESTED** [review]
It's been decided that the poppy spawn should be removed.

**Comment by slarticodefast** [comment]
Are you coming back to this?

**Comment by slarticodefast** [comment]
If you intend to continue working on this, please leave a comment here and I'll reopen the PR for you.

**Pull request closed without merging**
