### PR TITLE
Adds a new AME sound effect!

### PR DESCRIPTION
**Pull request by AftrLite**
## About the PR
As the title states, it adds an all-new sound effect for the AME Controller's Injection, so the engineering department - and myself (mostly myself) - no longer have the kneejerk thought that someone's bashing their skull against a maints wall a few rooms away just because the AME span up another injection.

Also resolves: #27758

## Why / Balance
Because the AME controller was pulling from the default MetalThud collection, and it's woefully confusing because that sound is used plentifully elsewhere. Also because it's supposed to be fuel injection, and it really didn't sound like fuel injection.

## Technical details
Changes this line of code, and adds an equivalently named .ogg file in the respective directory.
image

## Media

https://github.com/user-attachments/assets/eef24f37-c694-448f-8e75-3653fd0dfeec
^ AUDIO PREVIEW
EDIT: Preview updated to be representative of current commit. I don't have time to re-record a video preview rn, so only an audio one for now

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: The AME now has a new sound effect for fuel injection!

### CODE REVIEW

**Review by deathride58 — CHANGES_REQUESTED** [review]
The audio needs attribution and licensing info

**Comment by thebadman4662** [comment]
Finally sec will stop breaking into AME screaming that someone is getting gibbed.

**Review by deathride58 — APPROVED** [review]

**Comment by SlamBamActionman** [comment]
It feels a bit too... Sharp? Like there's some very high pitch going on in the first second that makes my ears sting a bit.

I'm not a sound engineer but maybe it's possible to run it through a low-pass filter just to tune out the sharpest peaks? Otherwise I think the sound is good and its use appropriate.

**Comment by cohanna** [comment]
the real question is how tf did your demo display 3 cores on a 2 core ame

**Comment by chromiumboy** [comment]
Sounds

> It feels a bit too... Sharp? Like there's some very high pitch going on in the first second that makes my ears sting a bit.
> 
> I'm not a sound engineer but maybe it's possible to run it through a low-pass filter just to tune out the sharpest peaks? Otherwise I think the sound is good and its use appropriate.

Sounds fine to me. @AftrLite, did you want to try out the low pass filter and see what you think? Otherwise, I'm happy to merge it as is

**Comment by SlamBamActionman** [comment]
I could still hear the little pitch thing so I decided to go into audacity and see what the problem was for me. 

I ended up learning about notch filters (cool!) and after removing frequencies around 15k Hz I can no longer hear the noise that was bothering me. I'll provide the updated file, see if it works for you.

[ame_fuelinjection.zip](https://github.com/user-attachments/files/17606312/ame_fuelinjection.zip)

**Comment by psykana** [comment]
Thanks! That default bonk drilled a hole in my engi head. 🤕

**Pull request merged**
