### PR TITLE
Update Core (#26791)

### PR DESCRIPTION
**Pull request by alexbalah**
* add

* invalid

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by UbaserB** [comment]
lol what?

**Comment by deltanedas** [comment]
has ai gone too far

**Comment by deepdarkdepths** [comment]
> "Update core"

atlas.yml

**Comment by potato1234x** [comment]
> > "Update core"
> 
> atlas.yml

Branch name "smart-fridge"

**Pull request closed without merging**
