### PR TITLE
Updated (most) medipen sprites

### PR DESCRIPTION
**Pull request by joshepvodka**
## About the PR
This PR updates the sprites for nearly all medipens in the game and changes their color for improved visibility.
- chemical medipen - not used in game
- emergency medipen - green band and light cyan tip
- poison auto-injector - purple band and injector
- brute auto-injector - red band and injector
- burn auto-injector - muted blue band and injector
- rad auto-injector - orange band and injector
- space medipen - magenta band and injector
- stimulant injector - red body with muted blue band
- combat medipen - cyan band and injector

## Why / Balance

After gridinv changes we can no longer read the name of the medipens as soon as we open inventory, also the sprites were so tiny that it was hard to identify what each them were at a glance (also auto-injectors are used in combat, so quickly knowing which one you need to use is very important).

## Technical details

about all medipens are color coded to the chemical they contain. Orange for arith, blue for derma, etc.
I didn't use the chemical color on them when it would make readability worst. the nearly white cyan epi basically disappears against the white surface of the emergency medipen, so I kept the green band and only colored the needle cover part.

Same thing for the yellow color of bicaridine, it is too light, so I used red instead of it.

The poison auto-injector doesn't use dylovene, instead it uses ultravasculine, but as most people associate poison damage to the purple color of dylo I used it instead.

For the combat medipen: omnizine is white, but that wont look right, so instead I used the cyan color of trico, as it's supposed to heal most kinds of damage.

space medipen is color coded magenta because barozine looks too much like arith, so I took some artistic liberty and used magenta, as it is very distinguishable from the other colors.

Finally for the stimulant injectors, I kept them looking _blood red_ but changed the band color, as it was giving me major "graphic design is my passion" vibes. For the microinjector I just updated colors on the old sprite, instead of changing it to the new one. (as it's supposed to be smaller and all)

## Media

All the medipens and their used sprites.

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: NanoTrasen updated the designs for their emergency medipens. Space medipens are now magenta colored and epi pens have a green band on them.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
they look out of style and the poison one should be green

**Comment by deltanedas** [comment]
dylo is purple

**Comment by JoeHammad1844** [comment]
> dylo is purple

the poison pen doesnt use dylo

**Comment by JoeHammad1844** [comment]
these are going to look massive in the inventory

**Comment by Rainbeon** [comment]
> dylo is purple

Poison Medipen uses Ultravasc not Dylo

But that's also purple so, it seems fine to me

**Comment by JoeHammad1844** [comment]
the green is more recognizable

**Comment by Emisse** [comment]
fuck it we ball

**Pull request merged**
