### PR TITLE
Improved solution container visuals

### PR DESCRIPTION
**Pull request by adamsong**
## About the PR

Adjusted how the icon selection works for a solution container, now the empty and full sprites will only show if the container is completely empty or completely full respectively. The only exception is if there is only the empty and the full states, then full will be used for all non-empty. The remaining fill levels are re-scaled.
Fixed water cups being only empty.
**Media**

https://user-images.githubusercontent.com/4607006/215368084-bce5a055-8d7d-4d6f-9600-19c7aa712d11.mp4

https://user-images.githubusercontent.com/4607006/215368098-c802f7ca-2fcd-4280-a2bd-790ab931a205.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: adamsogm
- tweak: Changed how full solution containers appear based on their actual fill level.
- fix: Fixed water cup being perpetually empty.

### CODE REVIEW

**Comment by AJCM-git** [comment]
@adamsong solution visuals got improved by another PR, can you make this only fix the water cups?

**Comment by adamsong** [comment]
> solution visuals got improved by another PR, can you make this only fix the water cups?

The fixes in that PR are different from the fixes in this one, what I am trying to do here is ensure, as much as possible, that the empty and full sprites are only used at 0% and 100% respectively. Currently a container can render empty even while not fully empty.

**Comment by metalgearsloth** [comment]
We have contenthelpers.RoundTolevels for this I think.

**Comment by adamsong** [comment]
I'll implement that then

**Pull request merged**
