### PR TITLE
Added bunny suit

### PR DESCRIPTION
**Pull request by NotSoDana**
OwO
Yes, we REALLY need this.

## About the PR

Adding a bunny-girl costume, what you can find in maintenance closets with 5% chance.

## Why / Balance

For RP situations in library, perfomances, or just for have fun. With it you can find your Rascal, that doesn't dream about you.

## Technical details

Nothing special.

## Media

bunsuit

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dezzzix
- add: Added bunnysuit outfit, which spawns in maintenance closets.

### CODE REVIEW

**Comment by UbaserB** [comment]
uhhhhhhhhh

**Comment by PJB3005** [comment]
Yeah I don't think this one's fit for upstream.

**Comment by MACMAN2003** [comment]
this does not belong on a space station

**Comment by metalgearsloth** [comment]
is this an emisse alt.

**Comment by deltanedas** [comment]
epic role play

**Pull request closed without merging**
