### PR TITLE
New Eden

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
The first map is a fully functional research station set at the edges of current space travel limitations.

>Welcome to New Eden. This research station developed at the edge of our current space travel limits is a symbol of the new frontier, the hope, and the qualities of our lives brought about by the advancements developed and curated here at Nanotrassen.

>Here, at New Eden, we will break the barriers of future space travel and all that we will encounter in the infinitum.   

The second map is the same map after an “incident” has occurred. The goal of this map is not to go about daily business as usual. Instead, the team of NT employees has arrived to investigate what happened after communications from New Eden have abruptly ceased. They will need to recon, salvage, and work together to get the station back up and running again. There will need to be a whole new level of cooperation and interaction to succeed here. 

**Obligatory caveats** 

The Freeze!!!, Yes, I know. I expect nothing but want to at least make them available in case something changes. 

You already have a map in PR limbo!!! Yes, I know and it is being rather majorly overhauled to address some feedback. In the meantime, I believe these maps are much more readily playable. 

I need Map Renders, please?

### CODE REVIEW

**Comment by moonheart08** [comment]
Empty PR?

**Comment by ChilbroBaggins** [comment]
> Empty PR?

Try again

**Comment by metalgearsloth** [comment]
> The Freeze!!!, Yes, I know. I expect nothing but want to at least make them available in case something changes.

The reason for the freeze is because we can't put them in the repo without having to actively maintain them, even if they aren't in rotation.

**Comment by ChilbroBaggins** [comment]
> Fair enough. I am willing to commit to maintaining my own maps if it helps.

**Comment by moonheart08** [comment]
We are not accepting new maps at this time.

**Comment by ChilbroBaggins** [comment]
So, there's not even a discussion for holding these for if/when maps are rotated out? As I mentioned, I just want them to be made available.

**Comment by metalgearsloth** [comment]
If you want to get it merged:
1. Wait until migrations are coded OR ask a mapper to rotate out existing maps.
2. Get it through the review process. This would probably only entail the 1 original map.

Maintenance is a no-go from me. The issue is we have like 40 maps and it takes more time pinging people to update their maps on your branch than it does doing it manually as slow as it is.

**Comment by ChilbroBaggins** [comment]
1. I will wait then. I doubt any other mapper wants to drop their maps. 
2. I kinda thought this was the review process. 

Thanks for the response/time though. I see your points. I do still think this will be an interesting gameplay twist if/when you are ready for more.

**Pull request closed without merging**
