### PR TITLE
Update emergency_rod atmos

### PR DESCRIPTION
**Pull request by lzk228**
added scrubbers and firelocks

Screenshot_20240709_225103

### CODE REVIEW

**Comment by UbaserB** [comment]
firelocks were removed on purpose, emisse wanted it.

**Comment by lzk228** [comment]
> firelocks were removed on purpose, emisse wanted it.

why tho? had a round yesterday, explosion on evac and whole evac got spaced because of lack of firelocks

**Comment by UbaserB** [comment]
> > firelocks were removed on purpose, emisse wanted it.
> 
> why tho? had a round yesterday, explosion on evac and whole evac got spaced because of lack of firelocks

I can probably find the conversation, hold on.

**Comment by lzk228** [comment]
closing because loosing fun
image

**Pull request closed without merging**
