### PR TITLE
Nicotine now does damage

### PR DESCRIPTION
**Pull request by Genkail**
Nicotine damage added

## About the PR

Smoking cigarettes has ceased to be harmless. 1 cigarette deals 1 damage

**Media**

- [х] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Nicotine does damage

### CODE REVIEW

**Comment by crazybrain23** [comment]
This makes syndie cigs even worse, maybe consider removing the nicotine from them or having omnizine cancel the nicotine harm?

**Comment by Genkail** [comment]
> This makes syndie cigs even worse, maybe consider removing the nicotine from them or having omnizine cancel the nicotine harm? Ask a maintainer about this.

Given the duration of syndie cigarette smoking, I don't think it will be a problem, even a full pack of cigarettes will cause only 5 damage

**Comment by fidso** [comment]
WHY

**Comment by deltanedas** [comment]
smoking kills, from scratch

**Comment by GoodWheatley** [comment]
I know this is technically realistic, but this feels like it’s just detrimental for no real reason beyond “realism”. Also if cigarettes *have* to do damage, make them do Poison instead of Cellular damage.

**Comment by Emisse** [comment]
id maybe wait for bobby to be more advanced so they do lung damage properly, might need another opinion

**Comment by EmoGarbage404** [comment]
This is kinda just annoying imo. Cigarettes don't kill even remotely this fast anyways. I don't get the purpose.

**Comment by deltanedas** [comment]
funnier is instead give smoking a cigar a 1 in 36000 or whatever chance of instantly exploding and killing you like that xkcd or something

**Comment by Interrobang01** [comment]
I think this PR is good. Small gameplay effect, opens up minor roleplay possibilities, adds depth to nicotine which previously did literally nothing...

Either way, there is at some point a cellular damage rate that will please the people who have expressed their concerns, whether it be at 0.05 or 0.0005. If people don't like 0.05, maybe they'll like it if it's 0.01.

anyways uhh add secondhand smoking next

**Comment by Emisse** [comment]
I LOVE SMOKING MIDS

**Comment by themias** [comment]
My only concern is will the damage cause DoAfters to intermittently get cancelled?

**Comment by Genkail** [comment]
> My only concern is will the damage cause DoAfters to intermittently get cancelled?

checked just now, everything is fine

**Comment by TemporalOroboros** [comment]
Probably should be replaced with lung damage after surgery is added.

**Comment by asperger-sind** [comment]
I tried to find the amount of ciggaretes it takes to kill someone and got directed to a suicide line :heck:
but yea i agree with emisse just wait till bobby is strong and then consider adding this

**Comment by DawBla** [comment]
> This is kinda just annoying imo. Cigarettes don't kill even remotely this fast anyways. I don't get the purpose.

What is even more annoying is that vape deals even more damage right now

**Comment by AJCM-git** [comment]
i like this as a concept but this should just use body system and cause damage to lungs

**Pull request closed without merging**
