### PR TITLE
Barratry V2

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR

A new version of Barratry with some modern additions.
Original map credit goes to @EmoGarbage404.

Tell me if I need to make any changes (like rotating a map out, although I heard we had a slot open).
**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Barratry-0

**Changelog**

:cl:
- add: Added Barratry back into the game, with a remastered new look.

### CODE REVIEW

**Comment by Jackrost** [comment]
I know that rusty and wrecked satiation is a point of this map but maybe add tabs for atmos gas storages to help distinguish them?

**Comment by Scribbles0** [comment]
> I know that rusty and wrecked station is a point of this map but maybe add tabs for atmos gas storages to help distinguish them?

thought i was forgetting something important
probably to redesign engi/sec/med (requested) though so i'll write it down

**Comment by Jackrost** [comment]
Two more thing:
1) Do engi have stack of glass?
2) There are no grille shields anywhere in space. Meteors will just destroy this station.

**Comment by Scribbles0** [comment]
> Two more things:
> 
> 1. Do engi have stack of glass?
> 2. There are no grille shields anywhere in space. Meteors will just destroy this station.
> 
> UPD: Telecoms and maps are missing.

telecoms exist, its near cargo
map as in like, the thing that has a layout of the station? p sure a barratry one doesn't exist
ik directional signs are missing, got that down on the list

**Comment by Jackrost** [comment]
> telecoms exist, its near cargo map as in like, the thing that has a layout of the station? p sure a barratry one doesn't exist ik directional signs are missing, got that down on the list

Sorry, I name them wrong. I talking about intercoms.

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
reviewed on discord seems good for playtesting

**Comment by Jackrost** [comment]
It's looks fine, but I think you over do it with grille shields. You can remove few of them from non vital places.

**Comment by OmerF-afk** [comment]
why its so uhm dirty?

**Comment by mirrorcult** [comment]
because that is the theme of the map

**Pull request merged**
