### PR TITLE
[Sprite] Diagonal walls

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

I think everything is clear here, why it needs to be explained is not required.

**Media**

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added diagonal walls made of plasttitanium and solid wall!

### CODE REVIEW

**Comment by ChilbroBaggins** [comment]
Ha, I just started doing these recently too. Are you going to do the reinforced solid wall too?

**Comment by PuroSlavKing** [comment]
> Ha, I just started doing these recently too. Are you going to do the reinforced solid wall too?



> Ha, I just started doing these recently too. Are you going to do the reinforced solid wall too?

I almost died while trying to draw the perfect diagonal texture for solid wall 💀 I made 2 types of diagonal walls, I don't want do any more.

**Comment by ChilbroBaggins** [comment]
This is what I had going for the diagonal rwall. Obviously, I missed the mark a little bit and need to adjust the alignment. But you get the idea. Let me know if it's something you want to work with, I can clean it up or pass it off. Either way

image

**Comment by PuroSlavKing** [comment]
> This is what I had going for the diagonal rwall. Obviously, I missed the mark a little bit and need to adjust the alignment. But you get the idea. Let me know if it's something you want to work with, I can clean it up or pass it off. Either way
> 
> image

I don't want to make diagonal walls anymore, you have already found out for what reasons in your experience.

**Comment by ChilbroBaggins** [comment]
Ok, that's fair. I don't think it should be too hard to get these fixed up. So, I'll work on it separately.

**Comment by ChilbroBaggins** [comment]
Here we go, how's this? 
image

**Comment by ChilbroBaggins** [comment]
I need to do the state1 sprite yet. It just errors now. I just wanted to show the base so far.

**Comment by ChilbroBaggins** [comment]
I guess it kinda looks like this then...I played with a few variants. I might need to thicken the shading so it blends with the base rwall better, maybe add some more darkness to the ring part...


image

**Comment by PuroSlavKing** [comment]
> I guess it kinda looks like this then...I played with a few variants. I might need to thicken the shading so it blends with the base rwall better, maybe add some more darkness to the ring part...
> 
> image

it looks sus, the smoothness of the transition from diagonal to just wall is not too refined.

**Comment by ChilbroBaggins** [comment]
> the smoothness of the transition from diagonal to just wall is not too refined.

Yeah, that was my point. Might actually have to try giving it 4 directions because of the way wall is unevenly shaded from north to south
image

**Comment by PuroSlavKing** [comment]
> > the smoothness of the transition from diagonal to just wall is not too refined.
> 
> Yeah, that was my point. Might actually have to try giving it 4 directions because of the way wall is unevenly shaded from north to south

meh... there should be 2 sprites, the direction is selected through the middle mouse button, take what I have already uploaded, and re-sprite as you think is beautiful.

**Comment by metalgearsloth** [comment]
@PuroSlavKing are you coming back to this or is it also being closed?

**Comment by keronshb** [comment]
Added review tag. If it's not reviewed by today I'll get to it tomorrow.

**Comment by ChilbroBaggins** [comment]
wrt the rwalls, I will open a separate PR when they are done. A little busy irl to finish them at this time any way.

**Comment by keronshb** [comment]
image

how do I actually build a diagonal wall in game? I've only been able to find the build mode variant

**Comment by PuroSlavKing** [comment]
> image
> 
> how do I actually build a diagonal wall in game? I've only been able to find the build mode variant

I don't know who originally came up with this, but diagonal walls are created only for mapping.
In the same way, I add them for mapping (as original shuttle wall). On the example of the same syndicate shuttle in SS13 and SS14 - it lacks volume thanks to these walls, it looks more like a flying square.

**Comment by keronshb** [comment]
> > image
> > how do I actually build a diagonal wall in game? I've only been able to find the build mode variant
> 
> I don't know who originally came up with this, but diagonal walls are created only for mapping. In the same way, I add them for mapping (as original diagonal shuttle wall). On the example of the same syndicate shuttle in SS13 and SS14 - it lacks volume thanks to these walls, it looks more like a flying square.

In SS13 there's a way where some walls are programmed to automatically corner. Shuttle walls and Plastitanum walls do this on Citadel if I'm remembering correctly. But if this is for mapping for now this will be a good pathway into that.

How do you rotate it for mapping by the way?

**Comment by PuroSlavKing** [comment]
> > > image
> > > how do I actually build a diagonal wall in game? I've only been able to find the build mode variant
> > 
> > 
> > I don't know who originally came up with this, but diagonal walls are created only for mapping. In the same way, I add them for mapping (as original diagonal shuttle wall). On the example of the same syndicate shuttle in SS13 and SS14 - it lacks volume thanks to these walls, it looks more like a flying square.
> 
> In SS13 there's a way where some walls are programmed to automatically corner. Shuttle walls and Plastitanum walls do this on Citadel if I'm remembering correctly. But if this is for mapping for now this will be a good pathway into that.
> 
> How do you rotate it for mapping by the way?

Everything is exactly the same as the diagonal wall of the shuttle, I didn't invent anything new, I just pulled on other textures. Rotates through the middle mouse button, I showed how it will look in the screenshots, and for comparison I put an identical shape from an already existing diagonal wall next to it.

**Comment by ChilbroBaggins** [comment]
You can construct them on Nyano. Could upstream the PR. There's also a fix for 1 of the walls visualizer that needs to be converted from the obsolete method.

**Comment by ChilbroBaggins** [comment]
Keep in mind this issue still exists and affects all diagonal walls

[3753](https://github.com/space-wizards/RobustToolbox/issues/3753)

**Comment by PuroSlavKing** [comment]
> You can construct/deconstruct them on Nyano. Could upstream the PR. There's also a fix for 1 of the walls visualizer that needs to be converted from the obsolete method.

My walls have a parent part from the diagonal wall of the shuttle, once it is repaired, mine will be repaired too.

**Pull request merged**
