### PR TITLE
Compare Role with name instead of reference by default

### PR DESCRIPTION
**Pull request by ZelteHonor**
Is this an acceptable solution?

### CODE REVIEW

**Comment by PJB3005** [comment]
Uh, what was the problem this was trying to solve again?

**Comment by ZelteHonor** [comment]
When you try to add a new role in the ISet it uses the default object implementation which only check references. So you could add two Assistant Job even if they were identical. Using the Name instead of the reference solve this.

**Comment by PJB3005** [comment]
Well, yes. That's kind of the point.

Distinguishing roles based on their `Name` seems like a bad idea. If you want to do this you should use some separate check to check whether something in the set is a "conflicting" role. Don't base it off `GetType()` either because I feel that won't end up great either.

**Comment by PJB3005** [comment]
I think I didn't realize this was pushed to after my last review, sorry about that.

Anyways, I don't think overriding `IEquatable` is a good idea for this since "conflicting" and "equal" have two different meanings here I'd say.

**Comment by Zumorica** [comment]
Closing this PR since it seems to be stale. Feel free to reopen it or make another PR if you're going to keep working on it though.

**Pull request closed without merging**
