### PR TITLE
Slimes Walk under the doors

### PR DESCRIPTION
**Pull request by IlyaElDunaev**
## About the PR

Slimes have learned to walk under doors.

## Why / Balance

 1. The Slimes have to break objects for a long time to get out of the room (Clicker simulator).
 1.1 7 hits per window, about 100 per armored window, 50 hits on the grille.
 2. Slimes are liquid creatures, so logically they are capable of doing this.
 3. Slimes are now hard to run from and harder to catch up with.

## Technical details

In slimes.yml MobMask is replaced by SmallMobMask, and MobLayer by SmallMobLayer. The cockroach, mouse, and space tick were used as examples from animals.yml.

## Media

https://github.com/space-wizards/space-station-14/assets/154531074/9f884939-78fe-4451-b0d4-ef453af9ee5d

https://github.com/space-wizards/space-station-14/assets/154531074/96fb07c3-eae2-45c6-9110-cbf912080fb2

https://github.com/space-wizards/space-station-14/assets/154531074/f746d652-9f11-4b86-a7ee-c1e453709046

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: IlyaElDunaev
- add: The Slimes have learned to walk under doors.

### CODE REVIEW

**Comment by Peptide90** [comment]
Seems overpowered. Slimes are meant to be contained in cells. Moving through doors at that speed is OP. Even slime people can only vent crawl in 13 so I think that's the behaviour they should have here. Doors are also airtight...so no sliming through. 

Then not being able to break walls and windows is also fine. I wouldn't expect something made of water to damage walls.

**Comment by deathride58** [comment]
Considering the ability to walk through airlocks is something that has no good counter, this will end up making hostile slimes *absurdly* oppressive. Either a doafter to climb through (which honestly would make sense to apply to non-electrified grilles as well) or ventcrawl would be good alternatives for this.

**Comment by deltanedas** [comment]
grilles faster than door since holes

terminator 2

**Comment by IlyaElDunaev** [comment]
I agree, the idea that slimes can easily get under doors and harm players really bothers me, so I'll probably shut this PR down....

**Comment by IlyaElDunaev** [comment]
Making changes requires interaction with cs files. Since I don't have the experience and time, I'm closing this project.

**Pull request closed without merging**
