### PR TITLE
makes reinforced crates/walls/windows actually reinforced

### LINKED ISSUE #3174: Stuff like reinforced crates and reinforced walls shouldn't take damage from fists

### PR DESCRIPTION
**Pull request by PaulRitter**
fixes #3174

### CODE REVIEW

**Comment by tmtmtl30** [comment]
Flat resistances of 20 or 30 seem pretty high to me, surely fists don't deal that much damage.

**Comment by PaulRitter** [comment]
agreed, will fix soon

**Comment by Peptide90** [comment]
Would it not be better it have it invincible to fists regardless of resistance?

**Comment by SweptWasTaken** [comment]
> 
> 
> agreed, will fix soon

soon:tm:

**Comment by SweptWasTaken** [comment]
Dead. Closing.

**Pull request closed without merging**
