### PR TITLE
You shit when you die.

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Just a big 'ol final bowel movement.

## Why / Balance

This PR is specially crafted to make it more difficult to murderbone. Its got huge balance implications, because people will try their best now to avoid being shit. Also added: the ability to slip in the shit, thus getting shit on.

## Technical details

Added some fields in the mobstate component to so you can make different species shit differently if you want you freaks.

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: post-mortem bowel release

### CODE REVIEW

**Comment by deathride58** [comment]
what

**Comment by EmoGarbage404** [comment]
for the love of christ please properly disclaim that this is for April 1st

**Comment by EmoGarbage404** [comment]
also no shitting in game bro ew

**Comment by potato1234x** [comment]
lol

**Comment by deltanedas** [comment]
they closed the shitting pr its joever

**Comment by K-Dynamic** [comment]
no shit

**Comment by FairlySadPanda** [comment]
can't have shit in ~~detroit~~ space

**Pull request closed without merging**
