### PR TITLE
Adds substation maintenance

### PR DESCRIPTION
**Pull request by joshepvodka**
## About the PR

Substations will now require periodic maintenance to work properly throughout the round. As the substation is used, and proportionally to how much power it consumes, it's integrity will decay. Engineers need to swap or refill the gas conduit that sits inside the wire panel to get it back to working order.

If substation integrity reaches zero they will malfunction. In that state they simply stop outputting power until someone fixes them by swapping the conduit.
If one goes malfunctioning the SubstationSystem disables substation decay for 5 minutes, so no two substations can malfunction at the same time. There will always be at the very least 5 minutes between outages.

Adds the gasconduit, a gas tank that should be filled with a 1:1 mix of plasma and nitrogen and slotted into a substation to have it work. The substation's integrity is tied to how much plasma and nitrogen is in it's conduit. As it is used the gases are converted to N2O.

Substations can have their DecayEnabled datafield turned to false in VV to make them last forever without supervision.
Substations can be upgraded with better capacitors to make their conduits last longer. The upgrades max out at T3 where they no longer require any maintenance. 

Below 70% integrity the substation's screen will turn yellow, and below 30% it will turn red. It will also be red if there is no conduit.

## Why / Balance

Give engineers more to do during downtime. More uses for gaseous plasma. Gives engineers a reason to upgrade machines that aren't just their lathes. Also Emisse said the old pr should be revived.

## Technical details

I know upgrades will be reworked soon, if you have any suggestions on how to make substation lifetime longer without them please tell me.

## Media

image

image

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Substations now need maintenance. Swap or refill their gas conduits with plasma and N2 to get them back working again.

### CODE REVIEW

**Comment by logical094** [comment]
achei massa

**Comment by chromiumboy** [comment]
A couple of questions

- A plasma / nitrogen mix seems an odd choice, what happens when the mix is off?
- Does it state a requirement for these gases on the substation anywhere? 
- What happens when you hit 0% integrity?

Also the name choice of 'power conduit' for its internal gas container doesn't make much sense, as it doesn't thematically relate to gas at all

**Comment by joshepvodka** [comment]
> A plasma / nitrogen mix seems an odd choice, what happens when the mix is off?

I just wanted to make the repair involve requesting something from atmos, but didn't want to add any new gases. I chose plasma + N2 for no reason in particular. I accept suggestions.
The substation will only consume equal parts of plasma and nitrogen, if there is another gas along with it then integrity goes down.
Examples:
50% plasma and 50% nitrogen is 100% integrity.
30% plasma, 30% nitro and 40% anything else is 60% integrity
60% plasma and 40% nitro is 80% integrity

>Does it state a requirement for these gases on the substation anywhere?

Guess I should add something that talks about it somewhere.

>What happens when you hit 0% integrity?

The substation just stops working, the battery stops charging or discharging and the area goes into a blackout.

> Also the name choice of 'power conduit' for its internal gas container doesn't make much sense, as it doesn't thematically relate to gas at all

That's true, I should change it.

**Comment by GreyMario** [comment]
\>Something for Engineering to do
\>Forces Atmos' involvement

My first thought on processing this information is "wow, everything is going to break down at exactly the time the station starts getting really fucked up, and literally no one is going to be available to handle the consequences". What's the time to kill for an unupgraded substation, especially in a critical department like Medical or a hungry department like Science?

**Comment by joshepvodka** [comment]
It takes around 10 or so minutes for science to go out usually, and 20 minutes for anywhere else. So after about 25 minutes all departments are gonna have blackouts within around 5 to 10 minutes of each other.

**Comment by Nimfar11** [comment]
Will the substations fail too quickly? On large maps this could be a problem, plus don't forget isolated areas like AI satellites. 
There's also the problem of maps being created for events, will they all need to be maintained as well? Maybe we should make a separate substation that does not need such maintenance? It could even be a technology, not just for mappers.

**Comment by joshepvodka** [comment]
> Will the substations fail too quickly? On large maps this could be a problem, plus don't forget isolated areas like AI satellites. There's also the problem of maps being created for events, will they all need to be maintained as well? Maybe we should make a separate substation that does not need such maintenance? It could even be a technology, not just for mappers.

Mappers can disable substation decay in shuttles, centcom, AI satelites and any other important or isolated areas. That can also be done in game by upgrading the substation's capacitors.

**Comment by IProduceWidgets** [comment]
My initial reactions are 
* everything will fail at the same time
* substations are often in rooms with no atmos pipework so having them offgas is problematic, and I don't really see the point of making closets require gas piping when they need to be both small and infrequently opened. 
* I would prefer the breaking be a random event rather than a slow exhausting of the fuel gases. You could still make it need plasma (or another gas) and have it simply break open the gas tank thats in the substation storage to vent it for the event making the closet full of plasma / badgas.

**Comment by joshepvodka** [comment]
> everything will fail at the same time

Would increasing the time substation decay is disabled to 10 minutes fix that?
> substations are often in rooms with no atmos pipework so having them offgas is problematic, and I don't really see the point of making closets require gas piping when they need to be both small and infrequently opened.

So far i see engies carrying spare conduits to perform maintenance, and giving the used ones to atmos so they can empty and refill them.

**Comment by Ilya246** [comment]
i would recommend:
1) halve the decay speed
2) change the repair to instead require some wire and maybe 1 steel

i don't like that it relies on atmos, what happens if atmos is not present or does their job badly?

**Comment by arimah** [comment]
> Below 70% integrity the substation's screen will turn yellow, and below 30% it will turn red. It will also be red if there is no conduit.

As far as I can tell, it is _only_ the colour that changes. Accessibility guidelines are to never use colour alone to deliver information. Please consider also changing the content of the screen at different levels, in a similar vein to how APCs work, or adding a secondary indicator that isn't colour-based.

**Comment by Peptide90** [comment]
I'm fully in favour of this mechanic and have been for some time. My comments are similar to others if not more suggestive:

- Just make it nitrogen gas, it's what's used in capacitors in circuit breakers IRL. It can be our magic interrupting / insulating gas in the absence of a one in game like SF6. Makes no sense using something high value or harder to obtain for gameplay reasons.

- If not already in, make the decay rate slightly random (dice roll each interval, anything less than 3 = no change or something) see how that goes. Afterlight / OR had decaying mechanics for stuff, maybe see how that is.

**Comment by mirrorcult** [comment]
agree with peptide that it should just use nitrogen. im a fan of the concept but that will make it easier for people to replace them without atmos, though atmos still is the easiest way to go about it. decay rate should definitely be more random--i.e. a substation can fail ~15 minutes into the round or it can fail ~40 minutes into the round

**Comment by K-Dynamic** [comment]
Or you just fix it with steel/replacement capacitors, since getting nitrogen is surprisingly hard

Least we end up with engineering making jank scrubber filter setups to extract nitrogen beside substations

**Comment by Peptide90** [comment]
> Or you just fix it with steel/replacement capacitors, since getting nitrogen is surprisingly hard
> 
> Lest we end up with engineering making jank scrubber filter setups to extract nitrogen beside substations
> 
> Also, I'd hate to be the only engi alive when all the substations go dark around the station and force an evac

Sounds like a mapping issue tbh. There's generally a minimum of 2 N2 cans on a map in atmos alone. Could be a fun thing for atmos techs to figure out, a filter loop that takes out excess N2 but keeps the station at 80%. Making it just need steel would be too simple and not worth doing. Sounds like you have bigger problems if every sub dies.

**Comment by Peptide90** [comment]
Is this still being worked on?

**Comment by joshepvodka** [comment]
> Is this still being worked on? Anyone got their discord to ping? Should be part of the PR template.

I won't be working on this anymore, you're free to take it over if you like.

**Comment by IamVelcroboy** [comment]
Hopefully this gets picked up again. Seems like it would add a lot of value to engie-play

**Comment by Peptide90** [comment]
I might revive it with some of the proposed changes:

- Rename the gas conduit to "Nitrogen Booster" and make it require only nitrogen, no plasma. Realistically this can be a refill for the nitrogen filled capacitors while minimally changing the PR (sprite etc). Nitrogen filled capacitors are used in HV circuit breakers.
- Halve the decay speed and test in game to see if that resolves issues.
- Change the icon for the substation screen from red to a flashing warning symbol to indicate missing or empty.
- Maybe look to change the green and yellow icons to either a sine wave or bar chart so its visually different when at green state and at a yellow state (smaller bar, higher frequency of wave or lower amplitude to signify losses). Red could equally be a flat line.
- Make sure substation description references the need for a nitrogen booster.
- Add the non decay version for use by mappers in sensitive areas. E.g. one for AI sat, one for engineering or bridge. Maybe I can change the sprite too to be a beefy "engineering" orange coloured substation so it's easy to tell.

C# changes are above me so if anyone wants to contribute to the decay rate being randomised more. Any other suggestions or comments welcome.

**Pull request closed without merging**
