### PR TITLE
Adds 3 new types of bottles to the medifab

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

I added three new types of bottles, for visual variety. These sprites were already in the game, yet have gone unused. 
## Why / Balance

Visual variety mainly. Might be fun for RP, dunno.
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

## Breaking changes

**Changelog**

:cl: Boaz1111
- add: Added three new bottle varieties to the medifab.

### CODE REVIEW

**Comment by baddiePRO** [comment]
time to unlock chem and label all my meds as Minecraft potions :deranged:

**Comment by TheShuEd** [comment]
meh

**Comment by UbaserB** [comment]
The maintainer team has come to a consensus that currently it's unnecessary bloat in the way it is implemented, but could still potentially have some use in the future (eg wizard hideout).

**Comment by Boaz1111** [comment]
yeah no that's fair

**Pull request closed without merging**
