### PR TITLE
Adds draconic horns marking for lizards

### PR DESCRIPTION
**Pull request by deepdarkdepths**
## About the PR
Added a new horn marking.
There was some discussion about how the front/back view perspective should look in the art channel of the discord, so if this current iteration does not suffice, any feedback would be appreciated.
~~No idea what's up with the random whitespace in the ftl file. I did try to fix it~~

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: deepdarkdepths
- add: Added a new lizard head marking, the draconic horns.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i feel like the side angle doesn't actually match the front/back perspective very well? especially with the way they come up at a point, the front/back directions don't communicate the actual dip in the shape of the horn.

**Comment by deepdarkdepths** [comment]
> i feel like the side angle doesn't actually match the front/back perspective very well? especially with the way they come up at a point, the front/back directions don't communicate the actual dip in the shape of the horn.

These were my attempts at changing up the front/back view. I figured they might've not communicated the shape well to the average player so I didnt go with them
image
image

**Comment by deepdarkdepths** [comment]
I'll redo this after the freeze, don't have time

**Comment by UbaserB** [comment]
the freeze is in 10 days

**Pull request closed without merging**
