### PR TITLE
Adds a new "medchem hud" for CMOs

### PR DESCRIPTION
**Pull request by Thurtik**
## About the PR

This PR replaces the medical hud in chief medical officer's lockers with a unique "medchem hud", which combines the functionality of the medical hud and chemical analysis goggles into one fancy gadget.

## Why / Balance

This is a QoL addition for chief medical officers who don't want to have to swap between two items just to be able to see what their chemists are making. It would also be especially handy for CMOs on lowpop servers, who might have to juggle making medicine and treating patients more often.

## Media

[]https://www.youtube.com/watch?v=kBFxFV_gqwM&ab_channel=Thurtik
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Added a new unique "medchem hud" for chief medical officers", which acts as a medhud and chemical analysis goggles in one item!

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
2 things:
1. Content freeze
2. I would make the proto a child of medhud and chemhud so if a change is made to either, it would affect this Hud to + it would be cleaner

**Comment by mirrorcult** [comment]
closed for the freeze

**Comment by Thurtik** [comment]
Hello, could this pr get reopened please?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
This should just be a research item, also if you're buffing stuff don't just call it QOL.

**Pull request closed without merging**
