### PR TITLE
Basic rate limiting for chat messages

### PR DESCRIPTION
**Pull request by PJB3005**
awwawawawawaw

### CODE REVIEW

**Comment by UbaserB** [comment]
TRUE, i wonder if this would also apply to the medibot? Their spam is terrifying 💀

**Comment by PJB3005** [comment]
I figured log flood from the admin logs wasn't a severe issue because it'll be preceded by 10 other logs.

**Comment by PJB3005** [comment]
If their intent was to flood admin logs there's other ways to do that. I fixed this bug just because chat spam actually can cause the client's network connection to get clogged, which makes banning them much more annoying as admin.

**Comment by DebugOk** [comment]
> If their intent was to flood admin logs there's other ways to do that. I fixed this bug just because chat spam actually can cause the client's network connection to get clogged, which makes banning them much more annoying as admin.

Oh nice, exactly what I was looking for. I dunno why they even bother with doing stuff like this. I don't see what's so funny about flooding the chat of a silly roleplaying game

**Pull request merged**
