### PR TITLE
blacklisted throwing knifes from pneumatic cannon

### PR DESCRIPTION
**Pull request by Zealith-Gamer**
## About the PR

Disallowed throwing knifes from cannon

## Why / Balance

[#26610]

## Technical details

No code, only YML

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

I'm not fully sure the reach of the tag "CannonRestrict". Should not be an issue.

**Changelog**

:cl: tweak: Throwing knives can no longer be placed in pneumatic cannon.

### CODE REVIEW

**Comment by superjj18** [comment]
Can we nerf it rather than blacklist it?

**Comment by Zealith-Gamer** [comment]
nerf it all around? or nerf just the cannon?

**Comment by superjj18** [comment]
> nerf it all around? or nerf just the cannon?

It just seems like a knife would be a reasonable thing to shove into a cannon if you intend to harm someone.

**Comment by ARMOKS** [comment]
I agree with this one, throwing knifes are the first real high skill syndie item imo and the cannon trick feels cheap.

**Comment by Zealith-Gamer** [comment]
I'll let the powers that be decide to merge or close this. It was super easy toblacklist.

to nerf it for just the cannon would take, me personally, a lot. If it closes without being merged i'll look into a nerf.

**Pull request merged**
