### PR TITLE
Add discord button in escape menu

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Title

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Discord button in escape menu.

### CODE REVIEW

**Review by AJCM-git — CHANGES_REQUESTED** [review]
This is pretty specific, it would be better if summoning the escape menu spawned below it a control that lists all the important links related to the server, and then use that same control in the lobby

**Comment by lzk228** [comment]
i do not know how to do that

**Comment by AJCM-git** [comment]
> i do not know how to do that

Does it help if i tell you that we already have that control and its called LinkBanner (should have named it before but forgot the name), all you need to do is spawn it when you open the escape menu, adjust its position and ensure it closes with the escape menu

**Comment by lzk228** [comment]
have no idea
IMG_20240529_065813_107

**Comment by metalgearsloth** [comment]
Re-open if you do the review.

**Pull request closed without merging**
