### PR TITLE
Telescopic baton

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

Telescopic baton instead of flash for <s>heads (except captain and HoS),</s> detective and ERT officers. 
## Why / Balance

Heads will have a better chance to defend themselves, and punish the attacker. 

## Media

https://github.com/space-wizards/space-station-14/assets/128169402/ea21a1e4-6b0a-41ae-8bd5-31561d94943b

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11

- add: Added telescopic baton detective and ERT officers.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
but why? #25730 was merged

**Comment by Nimfar11** [comment]
> but why? #25730 was merged

In that sense, I'm open to suggestions as I don't know what would be best. Keep the heads a flash with a telescoping baton? Or give the telescoping dub only to the detective and ERT?

**Comment by Bugfinder1** [comment]
The Heads should have Both the flash and the telebaton.
Now that flashes are useful keep them for heads, the baton should be considered the last resort option for heads, other than i love it, 6 hits to stun seems fine especially if it has a okay swing speed.
as a final note, Give it to cap too, as we all know cap isn't supposed to have a stun baton on them 24/7, especially on green alert.

**Comment by chromiumboy** [comment]
I'm of the complete opposite opinion. Non-security department heads shouldn't have round start access to weapons. It only encourages valid hunting. Heads should be generally looking to escape dangerous situations, not fighting. So if heads really need a tool to help protect themselves, it should be to facilitate escape

**Comment by superjj18** [comment]
> but why? #25730 was merged

Honestly that’s less of a buff and more of a bugfix

**Comment by Dutch-VanDerLinde** [comment]
> I'm of the complete opposite opinion. Non-security department heads shouldn't have round start access to weapons. It only encourages valid hunting. Heads should be generally looking to escape dangerous situations, not fighting. So if heads really need a tool to help protect themselves, it should be to facilitate escape

yeah which is what the flash does, you can stun a dude and run away

**Comment by Catdere** [comment]
I both like and hate this. Telebatons in SS13 aren't replacements to batons and are a quick instant knockdown, How i would do this have this stun someone for a really short amount of time while having a cooldown between it being deployed and being able to be used. Furthermore i wouldn't let it have a swing for it being an overpowered mess would just suck.

**Comment by chromiumboy** [comment]
> yeah which is what the flash does, you can stun a dude and run away

Flashes are fine, but batons and other weapons are not a good idea for dept heads

**Comment by Emisse** [comment]
fyi we denied this the last time it was pred

**Comment by Nairodian** [comment]
I feel like this should just become a security side-grade. Giving head's a type of weapon, (as stated by a people already) is a slippery slope.

This has merit (I think at least) however to be in security, you trade battery life for longer time to stun and damage dealt.

**Comment by Catdere** [comment]
> fyi we denied this the last time it was pred

everything about this pr feels like a jumbled mess to me. Like Captain should get a telebaton, ERT should have normal batons. 
I like telebatons but they need to be done in a different way that doesn't make them make OP

**Comment by keronshb** [comment]
T Batons will require more discussion in the future. There's balance and gameplay discussions that would take awhile to figure out.

**Comment by Catdere** [comment]
> The captain has enough weapons, there's a disabler for stun. For the ERT it is needed to be able to fight if the EMP is used. I understand the majority are in favour of not giving telescopic batons to heads.

I think this is the entire issue with this pr. You're treating the Telescopic Baton like a better baton when it shouldn't be like that at all. Lets give a example

 lets say I'm a traitor and I have one of the many hand to hand options for killing If i deployed and Esword to Kill a head they could properly hit me 3 times before i could swing once and at that point i would be slowed down. Making it possible for this head to get my esword and kill me 
 
 With a flash it would be. Ouch my eyes hurt and they get away.

**Comment by QuietlyWhisper** [comment]
> With a flash it would be. Ouch my eyes hurt and they get away.

It's not particularly hard to get low level if not full flash protection either

**Comment by Nimfar11** [comment]
Then I'll take the telebaton away from the heads, giving only Detective and ERT, and then we can see how she performs.

**Comment by Catdere** [comment]
> It's not particularly hard to get low level if not full flash protection either

Indeed. it has counter play and isn't just a free win

**Comment by Catdere** [comment]
> Then I'll take the telebaton away from the heads, giving only Detective and ERT, and then we can see how she performs.

I would rather see det get a wooden baton :3

**Comment by asperger-sind** [comment]
My idea for better™️  telebatons was for them to be knockback sticks that push the target (has to be a humanoid) around 2.5 tiles per hit running modified GORILLA gauntlet code. No stamina damage, just around 10 blunt.
Potentially a brief stun on wall contacts but that was in the balancing grey area.

Didn't finish it because I couldn't get the implementation working correctly, but that sounded better than "stamina damage on hit stick" and "you're instantly knocked down on-hit lmao stick".

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
In the off chance this may actually be merged, the code is extremely copy-pasted and needs to be redone. It looks like it was copied from stun batons instead of using existing code / making existing code reuseable.

**Comment by mirrorcult** [comment]
as emisse said this was PR'd before and denied, I don't really see the situation changing at all since last time especially with flashes. just ends up being powercreep for heads and subtly pushes them to validhunt more, opting to close this

**Pull request closed without merging**
