### PR TITLE
Cog update fix

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR

emisse merged my previous PR before i was able to update it so yeah
- added a note detailing tesla overlooks
- added two more grounding rods
- added another stack of plasteel to PA
- added missing beacons
- added more plasma sheets in engi 20 -> 30
- added more uranium sheets in engi 10 -> 15
- added missing cameras outside AI and engi
- fixed engi power flickering
- added (basic) cooling loop to teg
- other minor fixes i forgot

## Media

See bot

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

no changelog

### CODE REVIEW

**Comment by Spessmann** [comment]
what is this error

**Comment by slarticodefast** [comment]
Random unrelated test fail, happens sometimes.
I'm re-running it for you.

**Comment by ArtisticRoomba** [comment]
Awesome, but the general equipment room before the PA (the one with the machines and mats) needs a visible air scrubber. Good changes all around though, thanks for listening to my suggestions.

The two air vents in the station anchor room looks odd... what's up with that?

**Comment by Spessmann** [comment]
both of those 

> Awesome, but the general equipment room before the PA (the one with the machines and mats) needs a visible air scrubber. Good changes all around though, thanks for listening to my suggestions.
> 
> The two air vents in the station anchor room looks odd... what's up with that?

Both of those were added in a previous version and just not really changed as I updated the map. Not a big issue, ill fix it in a future pr.

**Comment by Sarahon** [comment]
truthfully I really think you should add the outline for tesla or singulo just for times sake. It still takes too long for 1 or 2 people if you account for the fact that you have to not only build it, but pull at least 4 rods, all the coils and then place the emitters and wires.

**Pull request merged**
