### PR TITLE
Allow more items to be recycled

### PR DESCRIPTION
**Pull request by Nopey**
## About the PR

Allow the following items to be recycled (NOTE: list is best-effort, please check the actual commit when reviewing):
- sterile mask (0.25 plastic sheet)
- fire extinguisher (1 steel sheets)
- all medkits (1.5 plastic sheets)
- LV/MV/HV cables (0.15 steel sheet)
- t-ray scanner (4 steel, 1.5 glass)
- mop, the basic one (0.5 plastic)
- large beaker (1 glass, 0.5 for small)
- geiger counter (1 plastic)
- appraisal tool (3 steel)
- stun baton (1 steel, 1 plastic)
- global positioning system (4 steel, 1.5 glass)
- baseball bat (2.5 wood)

Resolves issue #24372 
Does not address the issue where recyclable containers like the "survival box" will delete their contents.

## Why / Balance

These prices are rough guesses. None exceed their crafting price (on the lathe), and some of the more expensive ones to make are roughly half their crafting price (medkits, t-ray scanner, large beaker, stun baton).

> It’s useful for cargo and salvage because they always have empty medkits and trash from salvage missions and disposals room with trash for recycling where’s have a lot plastic for station requests. Also it useful for all crew who don’t have resource for working on autolat they found or requested make in RnD they can recycle trash for materials for they needs like botanist have more option for recycling plastic for sterile swab or antag for making ammo in emag autolat.
\- gordod3 on issue #24372

## Technical details

Adding a PhysicalComposition component to an item allows it to be recycled and material-reclaimer'd.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

:cl:
- tweak: Many more items can now be recycled, including mops, medkits, and stun batons.

### CODE REVIEW

**Comment by gordod3** [comment]
For making medkit need 3 plastic, for sterile mask 1 plastic but when recycler - they both drop 1 plastic, it doesn't make sense. Make sterile mask drop at least 0.5 plastic and for all other items when recycler make drop 50% material, rounded down like LV/MV/HV cables drop 0.1 steel for making recyclering not very fine.

**Comment by Nopey** [comment]
Reduced all the amounts I got from the lathe to 50% yield, as apparently lathes can be upgraded to use less materials?

Bless whoever wrote the economy-breaking tests!

**Comment by metalgearsloth** [comment]
Is it possible to just have the system / a new component determine the lathe cost and apply a modifier? That way it doesn't require manual tracking.

**Comment by gordod3** [comment]
Good, I love it! And I find problem with buckets - they give 0.5 plastic when recycling but to make them need steel....

**Comment by gordod3** [comment]
Nevermind I find you just change price for bucket.

**Comment by gordod3** [comment]
Something wrong with sterile masks, again.... To make them need now 0.5 plastic but then recycling in material reclaimer give 1 plastic. What sense to changeing price for sterile mask?

**Comment by Nopey** [comment]
See CI pipeline run https://github.com/space-wizards/space-station-14/actions/runs/7747848329/job/21129225031?pr=24435
```
  2)   The physical composition of ClothingMaskSterile has more Plastic than required to produce via an (upgraded) lathe.
Assert.That(numSpawned, Is.LessThanOrEqualTo(actualAmount))
  Expected: less than or equal to 62
  But was:  100
  ```
  Apparently, sterile masks can be made from 0.62 plastic.

**Comment by Nopey** [comment]
lowered sterile mask and janitor's walk sign reclaim value even further

**Comment by gordod3** [comment]
Good work! Now just waiting for commit in main or make even more items be recyclable like medical breath mask(need make 100 steel and 50 plastic like all other breath mask)? https://github.com/space-wizards/space-station-14/blob/303805b20644361088861740dd47237d48251846/Resources/Prototypes/Entities/Clothing/Masks/masks.yml#L119-L136

**Comment by Nopey** [comment]
gordod3, I think I'm gonna keep the changes more minimal for now-- especially as Sloth's suggestion of calculating (most) recycling prices from lathe prices would certainly change what needs to be done.

<hr>

Been thinking about automatic pricing for few days, here are my notes:

<details>
<summary><b>When it comes to automatic pricing, I think adding the PhysicalComposition to entities as they are created seems best.</b></summary>
Attempting to deduce an item's id/prototype as it enters the recycler seems unwise/fragile, especially as admins and unforeseen gameplay systems may change an item.
<hr>
</details>

Should the origin of an object effect its PhysicalComposition? For example, a baseline lathe and fully-upgraded lathe both create a bucket (recipe calls for 100u plastic); should the baseline lathes' bucket recycle into more plastic?

This allows more systems to more easily ensure the items they create don't contain too much material. For example, Let's say that the cargo techs order a crate of buckets for 100 spesos. The supply system can calculate the total recycling-value of the crate, and then decide to reduce the amount of Plastic in the buckets' PhysicalComposition.
A major downside to this approach is that it adds hidden-state to items and contradicts the assumption that MaterialArbitrageTest has that all items of a certain id have the same PhysicalComposition.

I see two alternatives to this origin-specific-composition approach:
1. Manual-corrections approach. Continue to use the MaterialArbitrageTest to ensure items' materials are not breaking cargo's economy, and manually adding PhysicalCompositions to the .yml where needed to correct overgenerous automatic recycling values.
2. Consult-all-the-systems-when-spawning-the-item approach: When spawning an item whose PhysicalComposition is unspecified, consult every relevant system (Cargo, Lathes, construction graph..) to figure out what the maximum amount of materials can be per system, then take the minimum of all these maximums. I do not want to code this, it sounds like a nightmare.

Any opinions on whether I should pursue the origin-specific approach or the manual-corrections approach? esp. @metalgearsloth :smiley:

**Comment by gordod3** [comment]
I see. Alright, let's take it easy and go for the 1st variant for now, you've resolved my issue with medkits and I am thankful, all the other changes are a good bonus for me. About what I am thinking - no need to overthink the recycling price system now. All the changes can be made in the future and recycling could just be deleted someone else by someday. Better just make it more valuable in game for now so manual corrections look better than ones from a system, that always needs supporting and updating.
If you want to, I can make calculations and update my list - add prices for all items.

**Comment by gordod3** [comment]
I suppose PR never get merge. . . .

**Comment by metalgearsloth** [comment]
If you really want to do this manually then a test is required as the chance of arbitrage is too high.

**Comment by Nopey** [comment]
Fixed merge conflicts. Magic material-cost-calculator-system is beyond my means / [above my pay grade](https://github.com/space-wizards/space-station-14/raw/master/Resources/Audio/Announcements/RoundEnd/notevenpaidforthis.ogg)

>  a test is required as the chance of arbitrage is too high.

[MaterialArbitrageTest.cs](https://github.com/space-wizards/space-station-14/blob/master/Content.IntegrationTests/Tests/MaterialArbitrageTest.cs) already tests that arbitrage is not possible.

**Review by mirrorcult — APPROVED** [review]

**Comment by gordod3** [comment]
Thanks Nopey for PR!

**Pull request merged**
