### PR TITLE
Make the cloning pod and medical scanner fit through verical doors

### LINKED ISSUE #18479: Medical scanners are a bit too tall and thicc to pass through airlocks and firedoors
## Description

dunno about the other stuff
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Finally, salvage (may) bring cloning back!

Closes #18479

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/34938708/604a01ce-b884-4dba-8833-c244986984e0

**Changelog**

:cl: Vasilis
- fix: The cloning pod and medical scanner can now fit through vertical doors.

### CODE REVIEW

**Comment by CatMagic1** [comment]
Salvage is not gonna bring cloning back

**Comment by UbaserB** [comment]
i remember emisse saying they were trying to phase cloning out from normal gameplay.

**Comment by VasilisThePikachu** [comment]
> i remember emisse saying they were trying to phase cloning out from normal gameplay.

It is already not in normal gameplay. Salvage has to bring it.

**Comment by EmoGarbage404** [comment]
arguments about cloning's place in the game are irrelevant as this is literally just a tweak to the size of the collision.

**Comment by VasilisThePikachu** [comment]
Removing the Fixtures just makes it work better then just modifying those numbers. Before it *kinda* got stuck in doors. Now thats gone.

**Pull request merged**
