### PR TITLE
Monkey jumpsuits, Monkey soft EVA suits, monkey creampie, monkey handcuff.

### PR DESCRIPTION
**Pull request by brainfood1183**
Monkey can now wear jumpsuits and this pr includes over 100 jumpsuit and jumpskirt sprites for monkeys. Any uniform in the game can now be worn by monkeys and has the appropriate sprite. A monkey wearing a jumpsuit does NOT gain pockets but does get a pda slot for equipping a pda. Monkeys can now also wear EVA, prisoner EVA and Syndicate EVA suits. They CANNOT wear Hardsuits. These come with a storage slot for oxy tanks. Monkeys can now be handcuffed and also cream pied.

untitled-218

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Monkeys can now wear jumpsuits and jumpskirts (no pockets only pda slot).
- add: security are now authorized to handcuff monkeys.
- add: clowns are encouraged to creampie monkeys.
- add: Monkeys may now wear soft EVA suits.

### CODE REVIEW

**Comment by deltanedas** [comment]
did you do all the suit sprites by hand or with script

**Comment by brainfood1183** [comment]
> did you do all the suit sprites by hand or with script

by hand

**Comment by brainfood1183** [comment]
> did you do all the suit sprites by hand or with script

erm i managed to screw up as with billion files in pr. halp

**Comment by potato1234x** [comment]
this looks promising

**Comment by brainfood1183** [comment]
> this looks promising

unfortunately my repositroy got screwed and i had to delete it which also deleted all my branches, i hopefuly have all the images saved and can redo it.

**Comment by brainfood1183** [comment]
this should be working now.

**Review by Emisse — APPROVED** [review]

**Pull request merged**
