### PR TITLE
Rate-limit interactions

### PR DESCRIPTION
**Pull request by metalgearsloth**

### CODE REVIEW

**Comment by Jezithyr** [comment]
LGTM! Multiple interactions shouldn't be getting raised in a single tick anyways, so I doubt this has a risk of breaking anything. 👍

**Review by ElectroJr — CHANGES_REQUESTED** [review]
> LGTM! Multiple interactions shouldn't be getting raised in a single tick anyways, so I doubt this has a risk of breaking anything.

It's still possible that the server will receive multiple interactions on the same tick because of networking issues (i.e., if one message just happens to arrive a bit late). Limiting it to one interaction per tick will probably make the game feel worse for poor connections as it will just start dropping inputs, so I'd rather have a more generous limit. E.g., you should be able to consistently use `q` then `e` in quick succession to drop a pda and open the ui without the second input sometimes being dropped because of networking issues.

Also, it's probably cleaner to re-use the `PlayerRateLimitManager` that was added for rate-limiting chat messages, to avoid re-implementing rate limits in multiple different places. Though it'd need some kind of a dummy `SharedPlayerRateLimitManager` to be used from shared code.

**Comment by metalgearsloth** [comment]
> Also, it's probably cleaner to re-use the PlayerRateLimitManager that was added for rate-limiting chat messages, to avoid re-implementing rate limits in multiple different places. Though it'd need some kind of a dummy SharedPlayerRateLimitManager to be used from shared code.

It's not really about rate-limiting, it's getting multiple of the same event in the same tick skirting around queuedel. We can just add the terminatingordeleted check but that just leaves the door open for abuse in other areas.

**Comment by ElectroJr** [comment]
If the concern is specifically about qdel'd entities, then the interaction system should check that user/used/target entities aren't queued for deletion before being raised

**Pull request closed without merging**
