### PR TITLE
Remove the Scream Action

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Why / Balance

We have a proper emote system and I dislike how much people scream at nothing because of the convenient button's encouragement.

# Changelog

:cl:
- remove: Removed the scream action

### CODE REVIEW

**Comment by Errant-4** [comment]
Counterpoint, scream serves an important function. If you are jumped by a carp or reagent slime out of nowhere, you don't have TIME to stop and emote a scream. Yet immediately calling the attention of anyone nearby would be a great idea

**Comment by Pangogie** [comment]
In my opinion, the other vocal emotes should be added as actions.
However they should be optional and the hotbar should save if you have the added or now.

**Comment by UbaserB** [comment]
Screaming is funny and part of our culture, i would hate to make it more difficult to do if people are going to set it as a keybind anyway.

**Comment by lzk228** [comment]
even if there was no scream action in ss13, there was a emote panel where you could quickly click and scream
imagine like traitor trying kill you and youre standing and typing `screams`

**Comment by Hmeister-fake** [comment]
Screams here are the equivilant of farting on 13, necessary

**Comment by foboscheshir** [comment]
screaming is funny

**Comment by Aisu9** [comment]
the screaming action is quick to use (a single button press) and have a cooldown
the emote require that we stop moving and enter the proper command in the text box

**Comment by Ilya246** [comment]
*screams\*

**Comment by TheShuEd** [comment]
image

I don't think it's a good idea to cut a feature from a game that everyone is comfortable with and not offer anything in return (like the emotion menu).

If you offer an option that gives players easy access to the emotion system, you can always reopen this PR.

**Comment by DEATHB4DEFEAT** [comment]
> image
> 
> I don't think it's a good idea to cut a feature from a game that everyone is comfortable with and not offer anything in return (like the emotion menu).
> 
> If you offer an option that gives players easy access to the emotion system, you can always reopen this PR.

You've always been able to bind emotes to a key

**Comment by deltanedas** [comment]
stop to say something in the emote channel when the 10 hungry fish are barreling towards you

**Comment by lzk228** [comment]
well what are you guys thinking about this now with the emote radial menu in the game?

**Comment by deltanedas** [comment]
2

**Comment by Djungelskog2** [comment]
> Screams here are the equivilant of farting on 13, necessary

we really need to add farting

**Pull request closed without merging**
