### PR TITLE
More user friendly crew monitor UI

### LINKED ISSUE #13732: Crew monitors are missing a "No server" message
## Description

Crew monitors should display a no server message when they aren't connected to a crew monitoring server.

### PR DESCRIPTION
**Pull request by Ahion**
## About the PR

I made the names of the crew members a button. This way you can track the crew on the map.
Also, the location of the crew monitoring console is indicated by a pink dot on the map.
Fix #13732
Added a message "Server not found" if the console does not receive data.

**Media**

https://github.com/space-wizards/space-station-14/assets/58528255/7d5fbf3e-396b-46a6-8777-c5e718c69eb3

server_not_found

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Using the crew monitoring console, it has become more convenient to track the position of the crew on the map.

### CODE REVIEW

**Comment by Ahion** [comment]
In ss13 this console has the same functionality, never had such a problem.  I think it's more a matter of server rules.

**Comment by metalgearsloth** [comment]
> i really like the ui but this singlehandedly makes it the most powerful surveillance device on the station. Alongside the fact that it can be printed in sci, i feel like this will make the issue of "turn on sensors or you're an antag" even more profound.

It's only in CMOs office traditionally (also why this should not ever be re-added as a handheld device again) and is pretty much unique, and the odds of the CMO being around to use it are slim (and as for AI just make their windows exclusive so it can't leave a map of the station open at all times).

**Comment by EmoGarbage404** [comment]
i guess that's fine if it's only in CMO's office. I'd at least want to keep the handheld one, so if it could be made to not have the map, that'd be good.

**Comment by metalgearsloth** [comment]
SGTM. If someone's really sweaty they'd know all co-ords off by heart though it does mean they need to still parse who is near who.

**Pull request merged**
