### PR TITLE
Fix Reagent Description for Bananium

### PR DESCRIPTION
**Pull request by scrivoy**
## About the PR

- ~~Fix Reagent Description for Bananium~~
- Remove Reagent Name and Description for Bananium
- Fixes: #32784 

## Why / Balance

- ~~It's not radioactive anymore~~.
- It doesn't exist, gets juiced into honk instead. 

## Technical details

- ~~Changed to `A yellow organic solid.`~~
- deleted ftl strings

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by scrivoy** [comment]
Can't provide a Screenshot.
Maybe im just too new to find the matching Prototype in the Code or its really not there yet?
For my understanding it must be in this File, right?
https://github.com/space-wizards/space-station-14/blob/f5ab4f5cb6c6f6edef3232f4b0ec1bf2b5b5b345/Resources/Prototypes/Reagents/elements.yml#L1

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
Oh, wait, looks like you are right. That ftl string is not used anywhere it seems since bananium does not have its own reagent but gets juiced into honk instead.
In that case, could you simply remove the name and description string?

**Comment by scrivoy** [comment]
> could you simply remove the name and description string?

okay its removed

**Review by slarticodefast — APPROVED** [review]

**Comment by chromiumboy** [comment]
Thank you for your contribution. I had a look and it doesn't seem like the removed strings are needed anymore

**Pull request merged**
