### PR TITLE
Minor items in paramedic locker

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Adds a basic first aid kit and emergency crowbar to the paramedic locker

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- add: Paramedics now get a basic first aid kit and crowbar in their lockers

### CODE REVIEW

**Comment by potato1234x** [comment]
why the crowbar they can just find one

**Comment by JoeHammad1844** [comment]
An emergency crowbar is kindof on brand for a paramedic

**Comment by metalgearsloth** [comment]
Don't powercreep their locker, they can find it.

**Comment by JoeHammad1844** [comment]
you dont even give me a chance to change it?

**Comment by metalgearsloth** [comment]
> you dont even give me a chance to change it?

Both of these items are roundstart in medical so would require a new pr if you wanted to substitute other items.

**Comment by JoeHammad1844** [comment]
> would require a new pr if you wanted to substitute other items.

im a little confused on what you mean by this

**Pull request closed without merging**
