### PR TITLE
New crops: Berries and Bungo

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

The PR adds two new crops for botanists to work with: Berries and, of course, the bungo fruit.
Berries are available directly from the MegaSeed Servitor, while bungo can only be found in the exotic seed crate.
The bungo fruit also leaves behind a poisonous pit after being eaten. The toxin can be extracted and used for... various purposes. Or you can replant it, if you really want to.
Another relatively minor fix is dialing back the cocoa plant's water consumption to a normal level, since it was over 10 times faster than the default which made it nigh impossible to grow.
## Why / Balance

I decided to add berries mainly because berry juice, and several other berry-related foods were already in the game but unobtainable outside of rare random spawns, due to the lack of actual berries.

For the bungo fruit, there are two main reasons:
- It provides a way to farm enzyme in decent quantities (While it can be made from corn, that is very slow and cannot be boosted by potency)
- Bungotoxin acts as a middle ground between lead and regular toxins in terms of speed, taking almost a minute to crit a player.

And also, bungo donuts and bungo soup are already a thing, so canonically it has to exist too
## Media
crops

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Berry seeds are now available from the MegaSeed Servitor.
- add: Seeds for the bungo fruit are included in the exotic seed crate.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
based and bungopilled

**Comment by Doru991** [comment]
real

**Comment by mirrorcult** [comment]
bungo................

**Comment by mirrorcult** [comment]
good PR

**Comment by CrigCrag** [comment]
cocoa can be used to give plants a yield of 6 so maybe have it use like 2-3x as much water as a downside

**Comment by UbaserB** [comment]
BUNGO

**Comment by Doru991** [comment]
> cocoa can be used to give plants a yield of 6 so maybe have it use like 2-3x as much water as a downside

Good idea, changed it so the water consumption is unusually high but still doable

**Comment by Partmedia** [comment]
Please take a look at reducing the Changelog line count and only highlighting the most important changes, per the [Changelog guidelines](https://docs.spacestation14.io/en/getting-started/pr-guideline#changelog).

**Pull request merged**
