### PR TITLE
add windings and armwrap

### PR DESCRIPTION
**Pull request by 21Melkuu**
## About the PR

add new clothing windings and armwrap
## Why / Balance

variety in clothing
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: 21Melkuu, gabova
- add: Add new clothing windings and armwrap.

### CODE REVIEW

**Comment by 21Melkuu** [comment]
Now the check is broken because of the price, I'll fix it

**Comment by deltanedas** [comment]
> # DO NOT ADD MORE, USE UNIFORM DYING

**Comment by 21Melkuu** [comment]
> > # DO NOT ADD MORE, USE UNIFORM DYING

I still don't understand what this means

**Comment by Partmedia** [comment]
Thank you for your PR. Unfortunately, I'm closing it for two main reasons:

1. There is insufficient justification for why these changes are needed in the PR description, especially since we are currently considering reducing the number of non-essential clothing items (see https://github.com/space-wizards/space-station-14/pull/26748).
2. Separate sprites for each different color of clothing add a lot of unnecessary RSIs and YAML entries when it could be better handled by automatically recoloring clothing (see https://github.com/space-wizards/space-station-14/pull/26125).

We welcome you to re-open this if you have better justification for why this change is necessary or if you choose to bring in the new clothing with automatic recoloring ("uniform dying").

**Comment by 21Melkuu** [comment]
> Thank you for your PR. Unfortunately, I'm closing it for two main reasons:
> 
> 1. There is insufficient justification for why these changes are needed in the PR description, especially since we are currently considering reducing the number of non-essential clothing items (see [Removes a LOT of bloat clothing #26748](https://github.com/space-wizards/space-station-14/pull/26748)).
> 2. Separate sprites for each different color of clothing add a lot of unnecessary RSIs and YAML entries when it could be better handled by automatically recoloring clothing (see [Freeze clothesmate #26125](https://github.com/space-wizards/space-station-14/pull/26125)).
> 
> We welcome you to re-open this if you have better justification for why this change is necessary or if you choose to bring in the new clothing with automatic recoloring ("uniform dying").


Now it became clear. 

Question, do I understand correctly that the repainting system is not ready yet?

**Comment by 21Melkuu** [comment]
And the second question, if the color changing system is not implemented. Can I hope for an approved PR where I will only add one headband of the white version, which is obtained by crafting on g

**Comment by chromiumboy** [comment]
Can you provide some justification for its inclusion? Why do we need this headband?

**Comment by 21Melkuu** [comment]
> Can you provide some justification for its inclusion? Why do we need this headband?

I think this is a stupid question. We are talking about a style that the player can choose himself.

I can say with the same logic. Why do we need all these different things if they carry meaning?

Every player, even in a pixel game, wants to visually stand out from the crowd. More things, more choice.

And yes, I do not support the idea of ​​PR. We will remove many things - because there is more work for the voxes.

**Comment by chromiumboy** [comment]
All clothing adds customization options for players, so that's not compelling argument 

If it would fill a clothing niche that other options doesn't, or it would complete / complement an existing clothing set, for example, that would be a stronger justification

**Comment by Partmedia** [comment]
> Question, do I understand correctly that the repainting system is not ready yet?

It is not currently available.

> And the second question, if the color changing system is not implemented. Can I hope for an approved PR where I will only add one headband of the white version, which is obtained by crafting on g

With a "repainting" system, you would only need to provide sprites for the white version, and the rest would be automatically recolored for you.

I do think "more in-game customization" is good enough for most clothing items provided that they are sufficiently distinct from existing clothing options. Right now it's just that coloring every variety is a bit high in terms of maintenance (and initial PR) cost. Let's revisit this when we have a coloring system?

**Pull request closed without merging**
