### PR TITLE
Adds a very basic perpetual background ambient hum.

### PR DESCRIPTION
**Pull request by tmtmtl30**
## About the PR

Adds a quiet ambient hum that plays at all times. Very simple, but I felt like we needed _something_ to fill the dead air.

**Screenshots**
It sounds like this.
https://user-images.githubusercontent.com/53132901/107681226-a5856400-6c53-11eb-89d5-935d028dbaeb.mp4

### CODE REVIEW

**Comment by ike709** [comment]
I absolutely _despise_ this in SS13. Please add an option to disable it.

**Comment by metalgearsloth** [comment]
TBH I don't see the point of playing it just to remove dead air given it'll be torn out in a couple of months anyway?

**Comment by tmtmtl30** [comment]
My impression wasn't that this would be torn out, and rather used as the basis for a more detailed system, though that's up in the air. Regardless, it's lightweight enough that it didn't take much time to add and it wouldn't take much time to remove.

**Comment by metalgearsloth** [comment]
Yeah just make it a cvar that defaults off.

**Comment by tmtmtl30** [comment]
Added the cvar, although I set it to default to on (i.e., the ambience plays by default), since otherwise I'm not sure anybody would actually ever hear the damn thing. Who looks in options?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
1. Attribution on audio
2. Ambience is too loud IMO.
Rest LGTM.

**Comment by tmtmtl30** [comment]
Handled.

**Pull request merged**
