### PR TITLE
Remove Omnizine slime from ghost role pool

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR
Reagent slimes are considered minor antagonists, but the omnizine slime essentially can't kill anyone. So fairly frequently players would take the omni slime and try to be friendly which causes extra admin work.

## Why / Balance
More potential to harvest from the omni slime if it's not player controlled, plus it doesn't really have the capability of being a minor antagonist so I'd rather not keep running into the same admin issue over something so small. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by lzk228** [comment]
reagent slimes shouldnt have ghost roles at all #24155

**Comment by deltanedas** [comment]
it still has omni its just not player controlled

**Comment by EmoGarbage404** [comment]
probably best to just remove them all like Izk and ShuEd have suggested. Also maybe just not having an omnizine slime to begin with? It's weird for a negative hostile antagonist to just be an infinite healing source.

**Comment by Golinth** [comment]
> probably best to just remove them all like Izk and ShuEd have suggested. Also maybe just not having an omnizine slime to begin with? It's weird for a negative hostile antagonist to just be an infinite healing source.

I think at most the probability of it spawning should be reduced. As it is now, pretty much any chem can spawn, including other meds like Bicardine, so it’d be odd to completely remove Omni without removing the rest of the medicines

**Comment by superjj18** [comment]
> Is there another reagent we can swap omnizine for instead of just removing a potential reagent selection?

Cog, make it super rare and the only slime that gets to be a ghost role :trollface:

**Comment by Tynobeard** [comment]
> Cog

Cogchamp?

**Pull request closed without merging**
