### PR TITLE
Make suit storage only available for hardsuits, softsuits, and armor

### LINKED ISSUE #8028: Labcoats have suit storage
## Description

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Fixes #8028 
Made using suit storage require a hardsuit or softsuit to be equipped, instead of just any outerclothing.

## Why / Balance

So that you cannot put air tanks or weapons into suit storage while wearing just a winter coat or poncho

## Technical details

Adds the AllowSuitStorage component, which is given to all hardsuits and softsuits

Adds the DependsOnComponents field to inventory slot definitions, which specifies a list of components the entity in the item slot given by the DependsOn field must have in order to it to be usable

## Media

https://github.com/space-wizards/space-station-14/assets/45953835/9d82c5bf-02f1-4781-ab9c-bb865a29d210

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: You can now only use suit storage with hardsuits, softsuits, and armor instead of all outer clothing

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
that slot is not only for tanks and not being able to wear a gun in that slot does not make much sense. I often see handguns placed in that slot, like the captain's pistol. I like to put my emergency o2 tank there so I activate it quickly as a secoff for smoke nades. I can totally see restricting tanks to only suits, but not weapons.

**Comment by Hanzdegloker** [comment]
I use that slot for my disabler, I use it for my sidearm pistol as warden. I use that slot during combat for my rifle. I use that slot as a poor musician for my spear as I run from zombies.

That slot is used for allot of stuff, I don't see any reason for this change and it will only hamper current gameplay. Even restriction of air tanks to hard/soft suits seems un-needed. Unrealistic maybe, but we have space clowns, we shall survive.

**Comment by EmoGarbage404** [comment]
Me when content from ss13 is ported incorrectly and then people get mad when its fixed.

If you were meant to get extra storage when wearing literally any outclothing, you might as well have a 3rd pocket with a mild whitelist. Its called suit storage for a reason.

**Comment by LordEclipse** [comment]
> Me when content from ss13 is ported incorrectly and then people get mad when its fixed.
> 
> If you were meant to get extra storage when wearing literally any outclothing, you might as well have a 3rd pocket with a mild whitelist. Its called suit storage for a reason.

I'm fairly certain this was brought up before and it was intended to allow usage of the exoslot beyond void suits.

**Comment by LordEclipse** [comment]
> > Me when content from ss13 is ported incorrectly and then people get mad when its fixed.
> > If you were meant to get extra storage when wearing literally any outclothing, you might as well have a 3rd pocket with a mild whitelist. Its called suit storage for a reason.
> 
> I'm fairly certain this was brought up before and it was intended to allow usage of the exoslot beyond void suits.

Correction: Suit Storage/Exo Slot whitelist. Like being able to store a gun in armor but not lab coats, or large oxy tanks on hardsuits but not jackets

**Comment by LankLTE** [comment]
Yeah I think stuff like letting guns be held in armor is fine. It may be ported “incorrectly” from 13, but also this is a different games and features can be changed if people like it better.

**Comment by notquitehadouken** [comment]
fine i'll give armor the component

**Comment by Plykiya** [comment]
can you add a summary description to the component?

**Comment by IProduceWidgets** [comment]
I still don't see the point in beating around the bush. Just make it a backslot that can't hold a backpack and call it a day.

**Comment by Lamrr** [comment]
> Me when content from ss13 is ported incorrectly and then people get mad when its fixed.
> 
> If you were meant to get extra storage when wearing literally any outclothing, you might as well have a 3rd pocket with a mild whitelist. Its called suit storage for a reason.

This wasn't the case in SS13, you could store emergency oxygen tanks in hazard vests and winter coats. Likewise armour could store weapons like stun batons, disablers, etc. as others pointed out.

I think LordEclispes' proposal for a storage whitelist depending on the type of suit would best replicate this behaviour (and work well for gameplay).

**Comment by Hmeister-real** [comment]
does this remove inventory from coats and aprons and such?

**Comment by Thurtik** [comment]
I see the logic behind this change but nobody asked for this and it will just make the game more unfun tbh

**Comment by Doctor-Cpu** [comment]
This just makes it more clunky to handle makeshift weapons incase of nukies or whatever. Majority of departments had outerclothing or had ways to obtain it easily and it seems pretty unintuitive that some clothing allows weapons and others don't even though they would need straps to be worn like that in real life.

**Comment by notquitehadouken** [comment]
it gets funnier the more dislikes it has

**Comment by QuietlyWhisper** [comment]
> Me when content from ss13 is ported incorrectly and then people get mad when its fixed.
> If you were meant to get extra storage when wearing literally any outclothing, you might as well have a 3rd pocket with a mild whitelist. Its called suit storage for a reason.

And yet this is still ported incorrectly in this pr so it's not wrong to be upset that it's imported incorrectly again, no?

Here's a winter coat **in ss13, as other people have already mentioned** holding the emergency tank in the suit storage. Suit storage uses a whitelist on items per clothing, not disabling the entire function if you're not wearing a hardsuit.
image

**Comment by Djungelskog2** [comment]
> Me when content from ss13 is ported incorrectly and then people get mad when its fixed.
> 
> If you were meant to get extra storage when wearing literally any outclothing, you might as well have a 3rd pocket with a mild whitelist. Its called suit storage for a reason.

it wasnt fixed, the implementation is still incorrect, but in a way that actively makes the experience worse than both the first failed implementation and the SS13 Intended implementation

**Comment by UbaserB** [comment]
I mean, personally i like it the “wrong way” so its not the whole playerbase

**Comment by Welldzhik** [comment]
This should apply only to air tanks. In a good way, a weapon should not require outerwear at all, it has a strap on all sprites.

**Comment by notquitehadouken** [comment]
> This should apply only to air tanks. In a good way, a weapon should not require outerwear at all, it has a strap on all sprites.

backpack slot

**Comment by deltanedas** [comment]
slinging a gun shouldnt prevent wearing a bag, see cdda

**Comment by superjj18** [comment]
> > This should apply only to air tanks. In a good way, a weapon should not require outerwear at all, it has a strap on all sprites.
> 
> backpack slot

Your still defending this pr 9 months later?  

Imma be real never thought about this that much, but this change is honestly lame and I would be curious to see how the game feels with it reverted.  I think it would be for the best.

It's this PR's fault why managing my inventory is a pain in the ass unless I have a hardsuit or sec armor.

Why should I need armor to use a gun's shoulder strap or a air tank's straps?

**Pull request merged**
