### PR TITLE
Removes a LOT of bloat clothing

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Removes a lot of niche clothing, for various reasons explained in the "Why" section.
I mainly made this in preperation of Vox - it's better to get this out of the way first instead of just wasting my time spriting dead content that needs to be removed / content I want to remove.

## Why / Balance
Now that a of these actually end up incuring a maintenance cost since Vox are on the way, I figured it was best to just get these out of the way. There are probably more cantidates for removal then this, but these are the worst of the worst in my opinion.
*It is worth noting that a good portion of these are not maintenance-cost related,* as Vox can auto displace stuff like small hats and jumpsuits. They are still bundled in the same PR regardless, though, as it'd probably be pretty pointless to split them.

It is *also* worth noting that basically all outer clothing incurs a maintenance cost thanks to Vox, which definitely influenced some of my decisions (like with the basic & mime hardsuits.)

Generally speaking, most of these were removed to either directly interfering with something, or just feeling bloaty. Clothing should probably have *some* kind of use; if it's extremely niche & rare, or has a role that other cosmetics fill, then there's no point in really having it rot in the repo.

### For specific reasons, though...
**Basic Hardsuit:** I added this specifically so that the sprites could get reused, and for no other reason. The stats just do not justify this existing (it's basically just objectively better then the EVA suit,) & I can't see there really ever being a niche for it, outside of if someone adds something like hardsuit manufacturing.

**Mime Hardsuit:** Very, very niche. Not really funny or interesting enough to warrant existing like the Clown's hardsuit, which has a hilariously obnoxious-looking design & has built in squeaking and farting functionality.

**Syndicate Clothing:** These muddy up and directly interfere with syndicate aesethics for no real reason (see ship vs. ship outfits,) and are basically unused. They are also straight ports from /tg,/ meaning they not only have out-of-style nu-/tg/ sprites, but are also separated from their original context of implementation. I understand that these are probably good for admemes, but there are plenty of other options.

**Animal Masks:** These have difficult-to-read, uninteresting sprites, and only spawn in maint in a single loot pool spawner. There are also *six of them* which is definitely way too much.

**Cosmonaut Helmet:** A maint loot item that was ported from Eris like SCAF armor. One of the least fitting sprites in the game, and rarely used to boot.

**Powergloves:** Another random straight CEV-Eris ports. Probably not even mapped anywhere, and they're almost certainly pointlessly divorced from whatever functionality they had in Eris.

**Pod Wars Armor:** Added for a super niche situation in a gamemode that doesn't even really exist. Pirates can probably just use their hardsuits as armor on-station, anyways.

**Casual Jumpsuits:** This is one of the ones I care least about removing. With that being said, though, there's no reason to really have these exist when color jumpsuits exist. Passengers are most certainly not starved for options in that area of customization.

**Tricord Hat:** EXTREMELY similar to the normal pirate hat. Just looks plain worse compared to the normal one, there is barely any reason for this to exist.

**Hospital Gown:** Extremely pointless, This has been in the game for an entire year and I probably haven't seen it once. Medbay has no reason to ever dress you up in this, and there is basically no situation I can see anyone wearing this other then... roleplaying as a sick person, I guess? Which is valid, but probably not funny & frequent of a situation enough to warrant this item existing. It also seems like people apparently think the sprite sucks as well, but I can't weigh in about that myself since I've literally never seen it.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Everything SHOULD be migrated. There is a LOT that got killed here, though, so it's definitely not out of the question that forks who used this content may need to adjust.

**Changelog**
:cl:
- remove: Removed a lot of miscellaneous clothing that had little reason to exist.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Senior outfits are planned on being used in the upcoming loadout redux I believe, best to leave them be even if they need touchups

**Comment by SlamBamActionman** [comment]
> Senior outfits are planned on being used in the upcoming loadout redux I believe, best to leave them be even if they need touchups

The outfits can still be found on the repo; removing them now ensures that whoever re-adds them for loadouts give them the love they need, plus it prevents them from being grandfathered into that system with little thought.

**Comment by Mangohydra** [comment]
I completely agree with the 'This is a big one that a lot of people will probably be mad about.' with the senior clothes, please do not take our senior drip (they will be added to loadouts or something)

**Comment by Hanzdegloker** [comment]
> The outfits can still be found on the repo; removing them now ensures that whoever re-adds them for loadouts give them the love they need, plus it prevents them from being grandfathered into that system with little thought.

I was thinking more of the fact senior roles are apart of loadouts, with higher access and unique ID naming as a reward for high playtime in said role. I suppose they can live without their drip for now.

**Comment by OctoRocket** [comment]
"Bloat" gives a lot of character to the game. I don't see a real reason to be removing these, especially the ones that aren't going to be a maintenance burden for Voxes.

**Comment by ZeroDayDaemon** [comment]
> "Bloat" gives a lot of character to the game. I don't see a real reason to be removing these, especially the ones that aren't going to be a maintenance burden for Voxes.

While i agree that the huge variety of stuff gives ss13 and by extension ss14 a certain charm, I think the main issue is not that these items exist, but that their sprites stand out like a sore thumb from most other sprites.

If you could thing of great uses to give these items, a reason for them to exist, or take the fluff items and resprite them to be more consistent with other sprites, most people would probably not object to adding them back in a fixed state.

**Comment by deltanedas** [comment]
the real bloat is the 10 or so different colour variants for each type of clothes, dying can replace that

**Comment by OctoRocket** [comment]
> While i agree that the huge variety of stuff gives ss13 and by extension ss14 a certain charm, I think the main issue is not that these items exist, but that their sprites stand out like a sore thumb from most other sprites.

Then I would rather a respite and not an outright removal.

**Comment by ZeroDayDaemon** [comment]
> > While i agree that the huge variety of stuff gives ss13 and by extension ss14 a certain charm, I think the main issue is not that these items exist, but that their sprites stand out like a sore thumb from most other sprites.
> 
> Then I would rather a respite and not an outright removal.

Then you can resprite them and re-add them in another pr, the git history isnt going anywhere.

**Comment by OctoRocket** [comment]
> Then you can resprite them and re-add them in another pr, the git history isnt going anywhere.

I would still would rather not have them removed in the first place.

**Comment by Aexxie** [comment]
To be clear, I am not particularly against this, and agree a lot of these need respriting eventually anyhow. I just am afraid of this ending up like another shitty species with little extra thought - or, in this case, future-proofing.

I think a displacement map should be automatically attempted in-game for some sprites. This would be replaced by an actual sprite if there is one available.

**Comment by UbaserB** [comment]
Robohand gloves shouldn’t be removed since i sprited them myself in #24182, not by CEV-Eris. They are found in the robotics vendor and are part of the outfit. If you’re getting rid of just the gloves, might as well get rid of everything else in the vendor.

**Comment by Flareguy** [comment]
> While I support the removal of a lot of the really useless things (such as casual jumpsuits and the gloves), I really feel like Vox are not something we need enough to rush. It has only had interest and people actually working on it for like... what, 3 days to a week?
> 
> I also feel like Vox themselves need a resprite of their own altogether. They look utterly terrible as they are right now.

I'm in no rush, It's just what I feel like currently working on right now.
I get where you're coming from with the sprites, also, but we don't really have any good pre-existing alternatives that fit the artstyle, and in my opinion, it's not like the current ones are bad enough to completely halt progress on Vox or anything.

**Comment by UbaserB** [comment]
> but we don't really have any good pre-existing alternatives that fit the artstyle

What about the recent-ish paradise vox resprite?

**Comment by Flareguy** [comment]
> Robohand gloves shouldn’t be removed since i sprited them myself in #24182, not by CEV-Eris. They are found in the robotics vendor and are part of the outfit. If you’re getting rid of just the gloves, might as well get rid of everything else in the vendor.

Whoops, I was visually getting them confused with power gloves in my head. I don't know if they should exist still, but I'll leave it to another PR.

**Comment by Errant-4** [comment]
> While I support the removal of a lot of the really useless things (such as casual jumpsuits and the gloves), I really feel like Vox are not something we need enough to rush. It has only had interest and people actually working on it for like... what, 3 days to a week?
> 

Vox Design Doc has been around since January (cough Jan 31 but technically thats still January) and at the time I wrote it because people _kept bringing up the Vox_

**Comment by Aexxie** [comment]
> I'm in no rush, It's just what I feel like currently working on right now. I get where you're coming from with the sprites, also, but we don't really have any good pre-existing alternatives that fit the artstyle, and in my opinion, it's not like the current ones are bad enough to completely halt progress on Vox or anything.

I think the specific ones that are especially bad should definitely be removed. I also agree with the removal of hardsuits - I rarely even see people using them. I also vaguely fear the lashback that might be caused from removing the senior stuff immediately after they were re-added - especially since we are already being DDoS'd daily.

>Vox Design Doc was opened in January (cough Jan 31 but technically thats still January) and at the time I wrote it because people kept bringing up the Vox
> Some vox updates have been introduced since then. This is not really a NEW pursuit, it's just that Displacement Maps have sparked more activity because that was the biggest blocker so not much could get done on the sprite front... until now

Right, I know what you mean. Fairly sure I wrote a review on it as well; I just didn't remember seeing any progress on it until this was set up. I don't personally have the opinion that this is a "lazy" solution (it makes sense), but I feel like the magnitude of the purge will probably have some consequences, especially for flare, while not being the most ideal solution.

I also don't know how shitty the automated displacement mapping looks on existing clothing, but I still feel like this would be a better, lighter approach to the issue.

**Comment by QuietlyWhisper** [comment]
I think I'd rather have this clothing than the vox honestly, given a choice between the two...

**Comment by mirrorcult** [comment]
keep the senior outfits for the moment we can work it out later with them and it shouldnt affect vox anyway

the rest i dont feel strongly about, can just get removed

**Comment by mirrorcult** [comment]
> It seems most of these issues could be fixed with displacement maps. 

did you read the PR? the issue is that a lot of stuff like outer hardsuits and certain hats can't be properly displaced without looking like garbage (and necessitate their own vox sprites), flare outright says a lot of the other stuff could be displacement mapped but has different reasons for removing them

**Comment by OctoRocket** [comment]
I don't think they should be bundled together in that case. Bundling things that are up to be removed for objective reasons with things that are up to be removed for subjective reasons is a bad idea IMO. I would rather this be two separate PRs.

**Comment by Emisse** [comment]
> I don't think they should be bundled together in that case. Bundling things that are up to be removed for objective reasons with things that are up to be removed for subjective reasons is a bad idea IMO. I would rather this be two separate PRs.

no this is fine like this

**Comment by keronshb** [comment]
> > The outfits can still be found on the repo; removing them now ensures that whoever re-adds them for loadouts give them the love they need, plus it prevents them from being grandfathered into that system with little thought.
> 
> I was thinking more of the fact senior roles are apart of loadouts, with higher access and unique ID naming as a reward for high playtime in said role. I suppose they can live without their drip for now.

No that is not the point of loadouts at all.

**Comment by Everturning** [comment]
"little reason to exist" my ass while i agree with the power gloves and such, the shit like the maid outfit and basic hardsuit, animal masks and casual clothes and-
a lot of this is classic, and instead of removing them we should just... resprite them for the vox. even if you cant sprite other people can. this isn't "bloat" this is CHARACTER.
power gloves and cosmonaut helmet can go though

**Comment by EmoGarbage404** [comment]
@Everturning do not be needlessly aggressive and combative on PRs. They are simply making changes that they think are necessary and good. It's fine to disagree but lose the snark and attitude.

**Comment by metalgearsloth** [comment]
> Overall, I'd personally say we should wait to merge this until displacement maps are done. Once that happens we can re-evaluate what needs to be removed or taken care of through a displacement map.

They're done there's no reason to just delay discussion in the interest of hoping it dies out.

**Comment by metalgearsloth** [comment]
A lot of the clothing was ported poorly too for reference
https://github.com/space-wizards/space-station-14/pull/382
https://github.com/space-wizards/space-station-14/pull/419
https://github.com/space-wizards/space-station-14/pull/422

**Comment by OctoRocket** [comment]
> They're done there's no reason to just delay discussion in the interest of hoping it dies out.

This comment seems more than a bit bad-faith.

**Review by metalgearsloth — DISMISSED** [review]
Leave senior clothing but remove the pet variants of it.

I think the bat etc. masks are fine but not sure if they're even attainable ingame.

**Comment by Hmeister-real** [comment]
Im really, really sad to see the Casual clothes go, i really liked how they looked, and also the animal masks are really good for adminbus downstream (funny little cults), sad to see them go too

**Comment by Flareguy** [comment]
> Leave senior clothing but remove the pet variants of it.
> 
> I think the bat etc. masks are fine but not sure if they're even attainable ingame.

I've re-added senior clothing, though I feel like removing the pet variants right now is kind of pointless, and should probably just be done in batch in the future.

The animal masks only spawned in the maint loot spawner, and also directly incured a maintenance cost due to being masks (though it is maybe possible they could be displaced due to how unremarkable they are - they barely jut out at all.) I don't think they really make much sense to keep with the maintenance cost aside though, especially with the very middling sprites in mind.
There are other good, way more memorable & funny options for that kind of look, like the chicken suit, Richard hat, and red panda costume.

**Comment by beck-thompson** [comment]
Man I liked the look of the cosmonaut helmet. Why not just make it only equipable by non Vox species? Is there a policy to only have equipment that can be used by all species?

**Comment by Carmell0** [comment]
If this is merged we riot

**Comment by Verbalase** [comment]
Okay, this I cannot get behind... I like the clothing, even if it's unused or not. Could still be used whenever, y'know?

Whatever happens though, happens. 



> If this is merged we riot

we riot indeed

**Comment by EmoGarbage404** [comment]
@Carmell0 @Verbalase if you can't form a more robust criticism than "this sucks lets riot" then kindly refrain from interacting in discussions.

Thank you.

**Comment by Verbalase** [comment]
> @Carmell0 @Verbalase if you can't form a more robust criticism than "this sucks lets riot" then kindly refrain from interacting in discussions.
> 
> Thank you.

aw man the riot part wasnt for real

but aight

**Comment by GitHubUser53123** [comment]
Note the like-to-dislike ratio.

**Comment by Piras314** [comment]
I feel like calling casual jumpsuits mime hardsuit etc. "bloat" is kind of annoying. I for one really like both of those things.

Removal of most syndicate clothing (I assume the operative suits won't be removed at least) is disappointing but it is very rarely used so it's understandable.

Basic hardsuits are also weird so I understand that and the trico hat I've never heard of.

### **However**, why not have a list of unsprited clothing in the Vox PR and then people can resprite them if they want to see them, otherwise they will be gone?

**Comment by GitHubUser53123** [comment]
> Basic hardsuits are also weird so I understand that and the trico hat I've never heard of.

It acts as a base for all other hardsuits.

**Comment by MACMAN2003** [comment]
if you remove the basic hardsuit then what will replace it in the vault fridge?

**Comment by Aexxie** [comment]
> if you remove the basic hardsuit then what will replace it in the vault fridge?

Nothing, probably xd
The vault fridge doesn't actually serve a real purpose quite frankly. I am aware of everything it contains, but we could easily do without it entirely.

**Comment by deltanedas** [comment]
the point of the fridge afaik is to keep all maps vaults in sync

**Comment by Skarletto** [comment]
I'd rather not have to prototype upload every syndicate clothing item everytime I want to use them for admemes, but if they're really as bad for the repo as you think they are, then that's fine

**Comment by GitHubUser53123** [comment]
> I'd rather not have to prototype upload every syndicate clothing item everytime I want to use them for admemes, but if they're > really as bad for the repo as you think they are, then that's fine
How do you use uploaded sprites?

**Comment by Flareguy** [comment]
Added hospital gown for reasons listed in the PR body.

**Comment by OctoRocket** [comment]
I've seen the gown used plenty of times. More times when diseases were still in the game, sure, but still in used today. It's a roleplay item which has no good reason to be removed. I can see it being used more when newmed comes out too.

**Comment by beck-thompson** [comment]
I personally have seen the gown being used! There are ~2 doctors who I know who like to wear it as their "normal" doctor outfit.

**Comment by Aexxie** [comment]
You all do realize that the med gown was basically a flat color with no shading right?

**Comment by OctoRocket** [comment]
> You all do realize that the med gown was basically a flat color with no shading right?

So are medical gowns in real life.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
Personally I dislike the idea of this PR, I would rather Vox take longer than the removal of clothing from the game

**Comment by UbaserB** [comment]
can you remove the maints spawn loungewear? I was the one that introduced it and i dont feel happy with it anymore and its kind of useless

**Comment by ImWeax** [comment]
While there is certainly underused and redundant clothing, I feel like the variety available allows for creative character expression in what is primarily a roleplaying game, which is important. I'd agree with others here and say I'd prefer the Vox PR take longer instead of gutting content from the game.

**Comment by UbaserB** [comment]
WAIT I JUST REALISED NOOOO THE BEE MASK!!!!!! I care so much about it

**Comment by IamVelcroboy** [comment]
> WAIT I JUST REALISED NOOOO THE BEE MASK!!!!!! I care so much about it

Yeah, the masks can be good for theater roles, Halloween, and I've even seen parties where everyone wore a mask.

**Comment by MissKay1994** [comment]
I actually see the mime spacesuit at least once a day. I think people may just not know it exist or it's difficult to get because you need to ask for an EVA suit. The basic hardsuits are actually a sci tech they have to research and make iirc. Animal mask are not common at all but people actually use them believe it or not. A number of these I agree with on wait for Vox to be finished before we look at removing things. Vox not being able to wear some things is ok I'd say because they are a bit impractical for them

**Comment by metalgearsloth** [comment]
I encourage anyone who even mentions "vox" in their comment to ignore it and look at the bloat part.

**Comment by OctoRocket** [comment]
I’ve heard like 3 different reasons why this PR exists. Why does this PR
exist?

**Comment by ImWeax** [comment]
> I encourage anyone who even mentions "vox" in their comment to ignore it and look at the bloat part.

My previous response stands here - this is being viewed as "bloat", whereas from my, and many others, perspectives, it's variety that allows for creative character expression and roleplay. if all the "bloat" were cut out from the game, it would be a very bland experience.

**Comment by Piras314** [comment]
How is it bloat if it's used & liked? Answer: It's not!

To repeat from my last comment, if you don't have time / don't want to resprite these things for Vox, make a list of things you won't resprite in the Vox PR and if people like that clothing, they can resprite it for Vox.

**Comment by Carmell0** [comment]
Mime hardsuit is widely used by mimes, like, a lot. It's perfectly fine existing.

**Comment by GoodWheatley** [comment]
> Mime hardsuit is widely used by mimes, like, a lot. It's perfectly fine existing.

There’s zero reason for ANY service role to have a hardsuit.

**Comment by Flareguy** [comment]
Going to close this PR for now, as the net it casts is probably way too wide for just one PR. I *might* atomize some of this later, though I'm probably not going to go after everything I did in this PR.

**Comment by BYONDFuckery** [comment]
based

**Pull request closed without merging**
