### PR TITLE
Hair Overhaul

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Resprites every single human hair in the game.
(showing all 170 is hell so don't ask me to do it)

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: The legendary John Barber came to Centcomm with a business proposal. All human hairs have been cut with love!

### CODE REVIEW

**Comment by astriloqua** [comment]
# Visualization of some of the hairs
*I got bored, might contain silliness*
*Will update till all 170 is included*
<details>
<summary> Expand </summary>

### Afro
Afro

### Afro 2
Afro_2
### Afro Large
Afro_Large
### Ahoge
Ahoge
### CIA
cia
### Manbun
Manbun
### Drillruru
Drillruru
### Drill Extended
Drill_Extended
### Dreadlocks
Dreadlocks
### Double Buns
Double_bun
### Devil Lock
Devil_Lock
### Dandy Pompadour
Dandy_Pompadour
### Cut Hair
Cut_Hair
### Curls
Curls
### Crewcut
Crewcut
### Cornrows 2
Cornrows_2
### Cornrows
Cornrows
### Cornrow Tail
Cornrow_tail
### Cornrow Bun
Cornrow_Bun
### Cornrow Braid
Cornrow_Braid
### Combover
Combover
### Coffe House
Coffe_House
### Buzzcut
Buzzcut
### Business 4
Business_hair_4
#### Business 3
Business_hair_3
### Business 2
Business_hair_2
### Business
Business_hair
### Bun Thight
Bun_thight
### Bun Large
Bun_large
### Bun Head 3
Bun_head_3
### Bun Head 2
Bun_head_2
### Bun Head
Bun_head
### Braided Tail
Braided_tail
### Braided Front
Braided_front
### Braided
Braided
### Braid Short
Braid_short
### Braid Low
Braid_low
### Braid High
Braid_high
### Braid
Braid
### Bowlcut 2
Bowlcut_2
### Bowlcut
Bowlcut
### Bobdicker
Bobdicker
### Bobcurl
Bobcurl
### Bob 4
Bob_4
### Bob 3
Bob_3
### Bob 2
Bob_2
### Bob
Bob
### Beehive 2
Beehive_2
### Beehive
Beehive
### Bedhead 3
Bedhead_3
### Bedhead 2
Bedhead_2
### Bedhead
Bedhead
### Balding
Balding
</details>

**Comment by Alekshhh** [comment]
my god brother you're making this look like a skyrim mod

**Comment by juliangiebel** [comment]
I like them 👍

**Comment by Alekshhh** [comment]
I approve it but I also question if you're less sane than me

**Comment by VektorZ1** [comment]
It looks really cool

**Comment by EmoGarbage404** [comment]
cooltext441417700335461

**Comment by Equivocateur** [comment]
Emo has forcibly made every long/floorlength bedhead user wear shorts instead of skirts

**Comment by Alekshhh** [comment]
little does he know I injected a trojan into ss14 you're all fucked

**Comment by QuietlyWhisper** [comment]
I'll be real with you, the few human characters I did have have bad cuts now

**Comment by EmoGarbage404** [comment]
Gonna be real with everyone that has issues: you're going to have to list the specific hairs that you dislike. There are 170 haircuts and saying that some of them look bad is meaningless feedback

**Comment by QuietlyWhisper** [comment]
I did in fact mean all of them

**Comment by CloneTrooperSimp** [comment]
> Gonna be real with everyone that has issues: you're going to have to list the specific hairs that you dislike. There are 170 haircuts and saying that some of them look bad is meaningless feedback

Business hair 2 looks pretty icky imo, pretty much most of the business hair ones look kinda bad actually.

**Comment by CrigCrag** [comment]
mulder looks kind of silly now, the previous iteration was simpler and neater.

**Comment by QuietlyWhisper** [comment]
In my specifics though, 

- Slightly long hair is ok
- Very long hair with fridge looks awful, it's just entirely flat now
- Keanu hair front looks ok but the sides are awful and don't really match the front

**Comment by Yayts0** [comment]
Gonna be honest, a few hairs look nicer now such as the drill hair and most of the ponytails.
Except for ponytail 4 from the side view.

The rest of them though, I don't like them.
To give an example of a few I do not like the new sprite of:
The long hairs, especially long hair 3. 
The entire undercut series.

Though quite frankly getting the old sprites back would be nice, I dont think they were in need of a resprite anyway.
Maybe add two seperate sections for the old sprites and new sprites in the customisation menu? just an idea.

Just my thoughts.

**Comment by asperger-sind** [comment]
> Gonna be real with everyone that has issues: you're going to have to list the specific hairs that you dislike. There are 170 haircuts and saying that some of them look bad is meaningless feedback

I play exclusively one character and use keanu hair on that one, the new keanu hair is effectively a new hairstyle and I cerrtainly dislike it.
image
^NEW VERSION^

image
^OLD VERSION, YES I DONT HAVE A BETTER IMAGE^

**Comment by Equivocateur** [comment]
Floorlength Bedhead sideprofiles are weird, like they've been shaved on one side somewhat. 
image

Additionally they still turn skirts into shorts
image

For comparison I'm using Braid (Floorlength):
image


Its uncanny look is further exacerbated with any headgear.
image

**Comment by Just-a-Unity-Dev** [comment]
i kinda liked the curves on the original emo fringe

**Comment by Just-a-Unity-Dev** [comment]
also long emo gives slimes a unibrow

**Pull request merged**
