### PR TITLE
Fixed forensic scanner being able to break open locked lockers

### LINKED ISSUE #14450: forensic scanner is an emag
## Description
forensic scanner can unlock locked lockers after scanning them, which will abort the actual fingerprint scan

**Reproduction**
1. get scanner
2. teleport into hop
3. emag his locker using scanner
4. free aa!!!!!

**Screenshots**
funny that happens when using scanner on an opened locker

https://user-images.githubusercontent.com/39013340/223207254-297871be-c4f5-45e3-9bee-da7ce362aeff.mp4

### PR DESCRIPTION
**Pull request by Naive817**
## About the PR

fixes #14450 , forensic scanner no longer open a locked locker on doafter.
But I don't know whether my way of doing this is terrible or not.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Resisting a locked locker is still functional

https://user-images.githubusercontent.com/31364560/223925638-88ac9763-2c15-46dd-a241-340e5fd4048c.mp4

Forensic scanner no longer break open locks, also cancelling the doafter no longer have the pop up of "failed to kick open the door" 

https://user-images.githubusercontent.com/31364560/223925648-0e88157d-fedf-4434-8bf5-4aa0defda5eb.mp4

**Changelog**

:cl: furontier
- fix: Forensic scanners no longer functions as an emag.

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
This should be preventing the do_after in the first place.

**Comment by deltanedas** [comment]
changelog amag -> emag

**Comment by Naive817** [comment]
https://github.com/space-wizards/space-station-14/issues/14544
also forensic scanners have a tendency to break things with its do_afters

**Comment by metalgearsloth** [comment]
@Naive817 is this PR still needed with the recent do_after fixes.

**Pull request closed without merging**
