### PR TITLE
[Add] Adds HoS Flask

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

This PR adds a HoS flask. Sprites are by MrGreen

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**

:cl: MrGreen and OctoRocket
- add: Added HoS flask.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
Don’t they already have the vacuum flask?

**Comment by OctoRocket** [comment]
I don't remember a HoS specific vacuum flask.

**Comment by Emisse** [comment]
can you parent this to another flask so it inherits material composition

**Comment by OctoRocket** [comment]
What do you mean?

**Comment by Emisse** [comment]
can you make a base flask and parent them all to it wiht material composition

**Comment by metalgearsloth** [comment]
Are all the flasks this large

**Comment by OctoRocket** [comment]
> Are all the flasks this large

Yeah they are
image

**Pull request merged**
