### PR TITLE
Beret resprite and security beret

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Improved the beret sprites and added the security beret. they no longer have that weird dip in them
## Why / Balance

security has had only mime head level drip for too long

## Media

icon
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: JoeHammad
- add: security now has access to its own beret, fancy!

### CODE REVIEW

**Comment by Partmedia** [comment]
I'm going to defer to the sprite maintainers here, but I can't see a major difference between the new proposed security beret sprite and the old one.

**Comment by JoeHammad1844** [comment]
there was one pixel that wasn't there before

**Comment by Partmedia** [comment]
> there was one pixel that wasn't there before

Right, what I'm saying is, players might have a hard time noticing that one pixel is actually different, and if so, perhaps it makes sense to keep the same sprite for both.

**Comment by JoeHammad1844** [comment]
rebiew when

**Comment by EmoGarbage404** [comment]
ultimate spritetainer powers

**Comment by JoeHammad1844** [comment]
the power of the pull request flows through me

**Pull request merged**
