### PR TITLE
Feature: caracal crate

### PR DESCRIPTION
**Pull request by code-explorer786**
## About the PR 

add a single caracal crate

**Screenshots**

It's a video.

https://user-images.githubusercontent.com/68312688/194816637-92255e19-c5c2-4677-8be6-5a514f01f982.mp4

**Changelog**

:cl: coolusername
- add: Added caracal crate

### CODE REVIEW

**Review by Just-a-Unity-Dev — APPROVED** [review]

**Comment by EmoGarbage404** [comment]
there's no way to get this in game, so as far as i'm aware this is bloat content. Beyond that, even if it was added to cargo, do we really need *more* pointless animal crates?

**Comment by keronshb** [comment]
> there's no way to get this in game, so as far as i'm aware this is bloat content. Beyond that, even if it was added to cargo, do we really need _more_ pointless animal crates?

I'm thinking maybe they can be harvested for "leopard skin" or something similar to make those kind of clothes/tiles/etc

**Comment by ZeroDayDaemon** [comment]
As floppa has a chance to be the CMOs pet, this should be replaced with the Caracal Cat and not specifically the named floppa one.

**Review by mirrorcult — CHANGES_REQUESTED** [review]
see above

**Comment by code-explorer786** [comment]
yeah sorry for the inconvenience when i made this pr it was 22.00 and it was just a silly idea

**Pull request closed without merging**
