### PR TITLE
Playglobalsound fix

### PR DESCRIPTION
**Pull request by k3yw**
## About the PR

Added a workaround to display server-side autocompletion hint for `playglobalsound` command which utilizes attributions.yml file
Fixed some of the "valid but not really" `files` fields in several attributions.yml across the project

## Why / Balance

Eh idk it stopped working

## Technical details

Main idea was to read yaml filed in `SequenceDataNode`, think I would need a `[DataDefinition]`s for that but it simply didn't work out for me cuz I'm newb
Loop populates another list in a try\catch then concats original `ContentFilePath` read with looped one if project is being compiled in release mode

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed playglobalsound autocompletion

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Manually parsing licensing of files (of which most audio doesn't even use yet so will skip most things) is really bad and will just break frequently (hence why you're just using a try-catch and dumping exceptions).

Just use the metadata prototypes.

**Comment by k3yw** [comment]
> Manually parsing licensing of files (of which most audio doesn't even use yet so will skip most things) is really bad and will just break frequently (hence why you're just using a try-catch and dumping exceptions).
> 
> Just use the metadata prototypes.

Any hint on where it's utilized in the codebase?

**Comment by metalgearsloth** [comment]
AudioSystem, just lookup audiometadata in your IDE.

**Comment by metalgearsloth** [comment]
I ended up doing this.

**Pull request closed without merging**
