### PR TITLE
Increase role time required for CE,CMO,HOS by 5 times.

### PR DESCRIPTION
**Pull request by Emisse**
🆑 Emisse
- add: Role Time Requirements for CE,CMO,HOS increased by 5x

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
this should probably have an actual player facing changelog.

**Comment by Peptide90** [comment]
Take it this was discussed somewhere? Seems very MRP when the originals were designed to be very light, and high timers were very opposed?

**Comment by Partmedia** [comment]
This brings the timer from the current 5 hours to 25 hours. This seems a bit unreasonably high. There are outstanding issues with role timers saving, and it's going to be frustrating working up the hours again. This also doesn't address the root issue, which is that unfortunately it's possible to fill role time *without* understanding what's going on in the department. It doesn't address idling for role time.

If what we really want is to demonstrate role competency suitable for a high(er) roleplay environment, then we should have a different mechanism of assessing competence. Maybe an online quiz? Something a bit more nuanced than making the numbers on the timers bigger.

If this is change happens, count me out of playing these roles.

**Comment by metalgearsloth** [comment]
25 hours is gross overkill.

> There are outstanding issues with role timers saving

No there isn't?

**Comment by Partmedia** [comment]
> 25 hours is gross overkill.
> 
> > There are outstanding issues with role timers saving
> 
> No there isn't?

See #10655. Just because the issue isn't easily reproducible, and because complaints have died down, doesn't mean the issue has quietly gone away. I don't care about this issue (anymore) because I'm no longer impacted.

**Comment by metalgearsloth** [comment]
> I don't care about this issue

You're the only one I've seen report it so if you don't provide more info then nothing is happening.

**Comment by Partmedia** [comment]
> > I don't care about this issue
> 
> You're the only one I've seen report it so if you don't provide more info then nothing is happening.

Multiple admins are aware of the issue. If you want me to name them out by name, I can. The OCC copied on Discord is also searchable. Just because I'm the only one to file a Github issue doesn't mean I'm the only reporter. I don't have server-side access to debug the issue. I've tried multiple times to reproduce the issue locally, to no avail. I'm out of the limited resources I have.

**Comment by wrexbe** [comment]
5 hours, is probably somewhere between 5 - 11 rounds doing a single department. Assuming this is a new player, they probably have tried playing some other role as well. If they don't get how to play by that point, they probably aren't going to do well at the job, regardless of how high the wait time is. While setting it to 25 hours might prevent some bad eggs from getting into command positions, I think this is much more likely to make new people who might of liked the roles quit before they get there, and cause other new players to be intimidated by the game. It will also greatly increase the desire to cheat the AFK system, or find other ways to waste time, because people will feel forced to keep the game playing to unlock these roles. I think this will hurt the game, so I am closing this.

**Comment by Emisse** [comment]
I think 5 hours is too short considering the sheer amount of command staff players we see daily who do not know how to do the basics of the job or even what the job entails. These players actively degrade round quality from everyone else and contribute basically nothing being a learner in a role which should already know these things. When a CMO doesn't know how to clone or a CE doesn't know how to setup a power is a daily occurrence that is proof the current timer length is too short. I think the notion of trying to make every area of this game as accessible as possible to new players at the detriment of round quality and player experience is hurting the game. I also think making timers short makes time wasting/macroing more enticing since they think 'don't have to do it for that long'. I would honestly consider setting head roles to upwards of 50+ hours. Reluctance to do anything about this will further impact round quality daily as well with current administration issues, player culture, and maintainers not actually playing the game to know what the player experience even is right now.

**Comment by wrexbe** [comment]
Maybe a longer total play time requirement, along with this shorter department specific one, or some kind of minimum rounds played requirement, or a minimum account life requirement, or something like that would work better.

**Comment by moonheart08** [comment]
> 5 hours, is probably somewhere between 5 - 11 rounds doing a single department. Assuming this is a new player, they probably have tried playing some other role as well. If they don't get how to play by that point, they probably aren't going to do well at the job, regardless of how high the wait time is. While setting it to 25 hours might prevent some bad eggs from getting into command positions, I think this is much more likely to make new people who might of liked the roles quit before they get there, and cause other new players to be intimidated by the game. It will also greatly increase the desire to cheat the AFK system, or find other ways to waste time, because people will feel forced to keep the game playing to unlock these roles. I think this will hurt the game, so I am closing this.

Hi. You're not the administration team, this is an admin discussion.

**Comment by Partmedia** [comment]
I hope my two cents will be considered here:

I think we all agree we want a more fun game, whatever that means. It's just that we disagree how to get there. Clearly incompetent heads are demoralizing for players playing around them. We want a way to make sure that heads are reasonably competent.

Admins have a slider (role timers) that they can increase to increase competency, even if marginally. On the other hand, as a (I like to consider myself) competent player, increasing role timers, especially if I have to get more hours again, feels patronizing. It might also be a barrier to incoming players as @wrexbe has already stated.

On the other hand, the existing role timers are clearly not doing enough. I'm going to list a few alternatives, let's pretend we can fiat them into existence (code wise):

- Roleban more incompetent heads (probably too taxing on the admin team)
- Whitelist admin heads (might take a long time for admins to get around, admins don't see everything)
- An online quiz to demonstrate basic job competency (people might cheat on quizzes)
- An in-game performance review mechanic, e.g. only existing heads can promote others into head positions (players might spoil it)

I've brought up some of the drawbacks I could think of for each alternative, there are likely more. But I hope this gets the discussion headed off in the right direction.

**Comment by Tomeno** [comment]
I disagree with raising the role limits for the previously mentioned reasons, and I believe the core of the problems is that new players don't have any way of actually learning their role in-game, no matter how long they spend on it. We can't rely on them being told what to do by other players to learn how to perform their roles, so we need to estabilish some root knowledgebase that players will be able to build upon when learning how to play the game.
My preferred way of doing this is having in-game, in-world guidebooks for roles that should entirely cover the basics of each role and touch on advanced topics, as opposed to the wiki culture that has appeared on some SS13 servers.
That said, in the short term, raising role timers for head roles is a way to paper over the problem, but 25 hours is extreme for players who don't take the game super seriously, which they shouldn't have to. The same players who managed to not learn anything about a role while playing it for 5 hours will manage to repeat that feat however many times they need to in order to get higher access on their ID card, while people who want to spice up their gameplay by taking on more responsibility will be faced with a dull "grind" of playing the same role over and over until the timer is fulfilled so they can actually play something new.

**Comment by Visne** [comment]
Is this even a major issue on the MRP server? I think this will mostly be solved by having an in game tutorial per role, while increasing the amount of hours judt completely counts out casual players and locks even more of the limit job content that we have for newer players.

**Comment by HoidC** [comment]
this also means roles that require time played in heads require many more hours

**Comment by ZeroDayDaemon** [comment]
Too early, maybe in 2 to 4 years.

**Pull request closed without merging**
