### PR TITLE
Change Secret weights

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Added chance for extended in secret mode

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Added chance of extended mode to secret

### CODE REVIEW

**Comment by asperger-sind** [comment]
We've had Extended as an option in Secret for quite some time and then decided it's best to remove it because Extended isn't fun on Lizden.

**Comment by Myakot** [comment]
> ~We've had Extended as an option in Secret for quite some time and then decided it's best to remove it because Extended isn't fun on Lizden.~
> 
> nvm mirror replaced it with survival, still i dont think extended is going to be fun in any capacity on lizden or any other server really, especially with our amount of content

The reason this PR exists is because quite a lot of people on Corvax group servers actually want just a chill sandbox to have a rest from all of the events etc.

**Comment by HoidC** [comment]
can’t Corvax host their own branch but with Extended as a chance in the pool then? why does this need to be on Wizard’s Den?

**Comment by asperger-sind** [comment]
> The reason this PR exists is because quite a lot of people on Corvax group servers actually want just a chill sandbox to have a rest from all of the events etc.

PR this on Corvax's GH then, if you don't want it on upstream Corvax then make a branch or fork it.

**Comment by Myakot** [comment]
> can’t Corvax host their own branch but with Extended as a chance in the pool then? why does this need to be on Wizard’s Den?



> > The reason this PR exists is because quite a lot of people on Corvax group servers actually want just a chill sandbox to have a rest from all of the events etc.
> 
> PR this on Corvax's GH then, if you don't want it on upstream Corvax then make a branch or fork it.

I'm not the owner of this PR nor of this particular part of code, just provided an explanation to the sentence that I quoted above.

**Pull request closed without merging**
