### PR TITLE
Modify the red heath state (again)

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Modifies the red health state again to use a blue cross instead of a skull.

Untested because my dev environment client is still mysteriously broken, but it should look alright ingame considering it's outlined.

## Why / Balance
#22741 was merged despite its issues not being addressed (a pure white sprite is difficult to read in some circumstances & a skull probably doesn't communicate the fact that you need first aid as well,) so this hopefully rectifies that.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no CL no fun

### CODE REVIEW

**Comment by UbaserB** [comment]
the position of the plus is still kind of goofy

**Comment by mirrorcult** [comment]
SS14 Health icon owned copyright by Switzerland!!!!

**Comment by Sirionaut** [comment]
>>(2) By reason of the tribute paid to Switzerland by the adoption of the reversed Federal colours, and of the confusion which may arise between the arms of Switzerland and the distinctive emblem of the Convention, the use by private individuals, societies or firms, of the arms of the Swiss Confederation, or of marks constituting an imitation thereof, whether as trademarks or commercial marks, or as parts of such marks, or for a purpose contrary to commercial honesty, or in circumstances capable of wounding Swiss national sentiment, shall be prohibited at all times.

https://ihl-databases.icrc.org/en/ihl-treaties/gci-1949/article-53/commentary/2016#60_B

**Comment by Flareguy** [comment]
> > > (2) By reason of the tribute paid to Switzerland by the adoption of the reversed Federal colours, and of the confusion which may arise between the arms of Switzerland and the distinctive emblem of the Convention, the use by private individuals, societies or firms, of the arms of the Swiss Confederation, or of marks constituting an imitation thereof, whether as trademarks or commercial marks, or as parts of such marks, or for a purpose contrary to commercial honesty, or in circumstances capable of wounding Swiss national sentiment, shall be prohibited at all times.
> 
> https://ihl-databases.icrc.org/en/ihl-treaties/gci-1949/article-53/commentary/2016#60_B

I'll change it to a blue cross, then.
I still don't really think there's any icon that could convey the critical health state better so there's not really much else I can do.

**Comment by Errant-4** [comment]
Since I didn't expect the skull to be merged as-is I was still experimenting with alternate versions. Here is how the skull with a background, and a red H instead of cross would look like

image

image

**Comment by Terraspark4941** [comment]
i would prefer the skulls or the blue cross over red H, looks goofy ahh

**Comment by Errant-4** [comment]
I actually made a version where the BAD! text blinked, alternating between a darker version. And one where the BAD! text scrolled left and right. They did catch attention but they also made the word less readable which might be annoying if you don't already know that what it exactly says is irrelevant

**Comment by Flareguy** [comment]
I WAS going to mention the blinking BAD! text being probably being kind of annoying in practice, but I got beat to the punch.

I feel like there's nothing really particularly wrong with the blue cross symbol here; it'd be better if it was red since that's the same color as the health icon, but it can't be so there's nothing I can really do about that.
The cross fits in with the theming pretty well considering it's a pulse, and it perfectly conveys that you probably need to seek medical attention quickly.

**Comment by Terraspark4941** [comment]
Hey, throwing an idea:
Why not just make the text say "Very Bad!" instead? 
No need to fiddle with blinking icons or text, yes?

**Comment by Errant-4** [comment]
> Health is a scale from good to very bad. It stands to reason that one icon represents this one scale. The secondary icon is confusing. It's a med sign, so it means something medical is happening to my health, right? My first though upon seeing such a secondary icon is "There's something _medical_ happening to my health - I must be getting healed".
> 
> It doesn't get the "seek medical attention" point across.
> 
> I think I got to the heart of the problem. And this is it. Compare these two icons: the problem
> 
> These are supposed to represent **two steps on the health scale** (left: health3, right: health4).
> 
> Can you tell by just looking at them which one represents a health state worse than the other? **I can't.** What is really needed here is making these two more clearly convey that health4 is worse health than health3, without resorting to extra icons tangentially related to health. Also evidently just adding exclamation marks is also not a good solution.
> 
> "Very bad" works. "Critical" much better conveys the seriousness of the matter but unfortunately critical has its own meaning in SS14 vocabulary so it's probably off-limits.
> 
> Some form of blinking is still on the table.
> 
> Now we just need artists to work their magic.

Your screen capture ignores that the second one is blinking that little cross to more effectively grab your attention, which is it's main distinctive feature

**Comment by arimah** [comment]
To add to what @LordCarve has so eloquently argued in this thread, the use of a plus specifically feels extra misleading, as that symbol typically signifies something good and positive. It seems quite unintuitive that the emergence of a blue (not even red!) plus should mean "you are even more injured". I'm not arguing for re-breaking the Geneva Convention, just that a plus is the wrong solution to my mind.

Moreover, the placement of the icon is annoyingly far from the rest of the graphic; it almost looks like an additional status icon on top of the health indicator. If as a new player I saw a blue plus without further explanation, I might genuinely think it meant "you're healing".

The current skull is not ideal, but if nothing else, 💀 more clearly signifies "shit's real fucked and you might die" than ➕ does.

**Comment by Flareguy** [comment]
I MIGHT come back to this later. The skull really isn't THAT terrible ingame, though it definitely needs some kind of BG added eventually.

**Pull request closed without merging**
