### PR TITLE
Advanced treatment cyborg module for medical borg

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

Adds Advanced treatment cyborg module with advanced medical intruments for treatment. Adds items such as the Borg hypo and Borg dropper.

## Why / Balance

More extensive treatment tools, primarily related to treatment through liquid chemistry. Gives more possibilities to the medical borg if the chemist prepares a list of necessary medicines in liquid form.

Turns out the Borg have been dropping modules for a while now.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

:cl: Nimfar11

- add: Adds Advanced treatment cyborg module to the medical borg.
- add: Adds two new medical tools for the borg. Borghypo and Borgdropper.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i feel like the point of modules was to decouple abilities like this from the chassis itself. I'm not gonna hard block it but i feel like this should definitely just be a part of some kind of chemical synthesis module.

**Comment by metalgearsloth** [comment]
Defo don't put it on the chassis.

**Comment by deltanedas** [comment]
chem synthesis module, like deltav mediborg infinite chemical injector!?!

**Comment by Nimfar11** [comment]
To make a module only for glasses, it is very difficult to make a module that none of the Borg will use. Is it worth making such a chemical module with a 50 volume beaker and an injector with a capacity of 5 units?

**Comment by JoeHammad1844** [comment]
> chem synthesis module, like deltav mediborg infinite chemical injector!?!

if only we had a borg hypo.

**Comment by Nimfar11** [comment]
> i feel like the point of modules was to decouple abilities like this from the chassis itself. I'm not gonna hard block it but i feel like this should definitely just be a part of some kind of chemical synthesis module.

Redesigned the chemical treatment module. Chemical points are for someone else.

**Comment by Nimfar11** [comment]
@EmoGarbage404 
I removed the chemical goggles and made a medical borg module with chemical tools. Is that okay?

**Comment by EmoGarbage404** [comment]
good karma has been sown on this day

**Pull request merged**
