### PR TITLE
Return of injectable cigarettes

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

With microdosing fixed it should probably be fine to make cigarettes injectable again.
It currently injects 0.15u/3s split between all reagents in the cigarette, this means that if someone fills a cigarette that already has 10u of nicotine with an additional 10u of bicaridine they would get 0.075u nicotine and 0.075u of bicaridine in their chemstream every 3 seconds.
By doing some simple math we can conclude that the cigarette will have injected all of the bicaridine after a period of 400 seconds(11.66 minutes), for a total of 40 brute(13.33 pierce, 13.33 blunt, 13.33 slash) healed or 0.1 brute (0.033 pierce, 0.033 blunt, 0.033 slash) damage healed per second.
This healing rate is so low that it's not a balance issue anymore, manually filling the cigarette up to 20u also makes it last twice as long compared to a basic cigarette currently does on master, making you need to light a new cigarette less often.
Desoxyephedrine also scales correctly with dosage now so the speed boost and stun reduction you get are negligible.

Personally I would like to increase the solution container size of the cigarettes and the speed at which the chemicals are inhaled a bit, but before I do that I first want to know if we even want healing cigarettes to be a viable alternative way of healing small injuries. 
Syndicate smokes on master heal at the same rate as the example above but also 0.1/ damage/s in poison, burn and oxygen damage since they have omnizine, 
This is still extremely weak, and honestly a waste of TC, because you will choke while smoking it in a spaced area. 
Smoking a syndie smoke for almost 12 minutes also doesn't even heal the damage of a single bullet.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- tweak: Cigarettes can be injected again.

### CODE REVIEW

**Comment by keronshb** [comment]
Will review today/tomorrow

**Comment by Aisu9** [comment]
does this cover only cigarettes or does blunt are also getting this change?

**Comment by Arendian** [comment]
> does this cover only cigarettes or does blunt are also getting this change?

I put it on BaseSmokeable so it should work on all types of smokes.

**Comment by Equivocateur** [comment]
Is this a hidden ~syndicate smokes~ Interdyne Herbals nerf?

**Comment by Emisse** [comment]
im fine with this, im thinking maybe syndi cigs container size can be greatly buffed for long term low health recovery if you want to buff them

**Pull request merged**
