### PR TITLE
adds male and female arachnids

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
ararchnids are no longer unsexed

## Why / Balance
adds more customization that arachnid lacks as you can choose between a masculine or feminine body, arachnid is the only specie without this option

## Technical details
3

## Media
image
feminine vs masculine arachnid
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
nope

**Changelog**
no

### CODE REVIEW

**Comment by Hmeister-real** [comment]
its a trait of Arachnids, i like it. makes it more interesting to roleplay with

**Comment by LankLTE** [comment]
Should probably have a better reason than “they’re the only ones who have it”.

**Comment by Dutch-VanDerLinde** [comment]
> Should probably have a better reason than “they’re the only ones who have it”.

Ok

**Comment by Krunklehorn** [comment]
I thought they default to they/them?

**Comment by Dutch-VanDerLinde** [comment]
> I thought they default to they/them?

nuh uh

**Comment by magnitude9girthquake** [comment]
Every time i've used a scrambler it chooses she/her (I've used scrambler a lot)

**Comment by Errant-4** [comment]
> Every time i've used a scrambler it chooses she/her (I've used scrambler a lot)

Testing indicates that it never scrambles pronouns. Your base character has she/her set, right?

**Comment by Brandon-Huu** [comment]
NB erasure happening before our eyes

**Comment by magnitude9girthquake** [comment]
Nope, pronouns are not she/her before the scramble

**Comment by LankLTE** [comment]
If there is a bug with the scrambler that should be fixed separately regardless as we want to support unsexed species.

**Comment by Errant-4** [comment]
> If there is a bug with the scrambler that should be fixed separately regardless as we want to support unsexed species.

My testing indicated that the impacts both sexed and unsexed species just the same

**Comment by Dutch-VanDerLinde** [comment]
> If there is a bug with the scrambler that should be fixed separately regardless as we want to support unsexed species.

#25282

**Comment by IProduceWidgets** [comment]
Aren't male spiders usually smaller?

Also, how do the clothes look on this body shape since it's different than the other humanoid females

**Comment by Errant-4** [comment]
I said nothing about reptilians but are we seriously applying human sexual dimorphism to the SPIDERS? Come on.

**Comment by EmoGarbage404** [comment]
i don't really see an issue with arachnids not having distinct sexes. I think it's a fairly interesting trait and helps make them more distinct. Perhaps it's minor, but i think it adds a lot. I'm opting to close this PR. thank you for your contribution.

**Comment by Brandon-Huu** [comment]
> i don't really see an issue with arachnids not having distinct sexes. I think it's a fairly interesting trait and helps make them more distinct. Perhaps it's minor, but i think it adds a lot. I'm opting to close this PR. thank you for your contribution.

Extremely RARE EmoGarbage404 W

**Comment by PixelTheKermit** [comment]
> i don't really see an issue with arachnids not having distinct sexes. I think it's a fairly interesting trait and helps make them more distinct. Perhaps it's minor, but i think it adds a lot. I'm opting to close this PR. thank you for your contribution.

What emo said.

**Pull request closed without merging**
