### PR TITLE
Hypopen into PDA compartment

### PR DESCRIPTION
**Pull request by KaiShibaa**
-Allows Hypopen to be placed inside PDA like a regular pen.

### CODE REVIEW

**Comment by UKNOWH** [comment]
waited for it for so long

**Review by ShadowCommander — CHANGES_REQUESTED** [review]
This'll make the Hypopen able to write on paper. Maybe add a new tag `Pen` and add that to pens and the PDA whitelist?

**Comment by KaiShibaa** [comment]
I believe the Edagger works the same way? Being able to write with it.

**Comment by Fishfish458** [comment]
> This'll make the Hypopen able to write on paper. Maybe add a new tag `Pen` and add that to pens and the PDA whitelist?

Eventually there should be just a generic tag for adding it to that compartment but it should be intentional that it also works to write with. It works that way in ss13 and it means that a spent sleep pen(non-refillable) will not have any determined differences between a regular pen.

**Comment by ShadowCommander** [comment]
Alright, looks good then!

**Pull request merged**
