### PR TITLE
Insulated Gloves prevent use of guns

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

wearers of insulated gloves can no longer fire guns 
wearers of budget insulated gloves and other insulated gloves can still fire guns.

## Why / Balance

based of https://tgstation13.org/wiki/Clothing_and_Accessories#Insulated_Gloves where insulated gloves cant use guns.
This makes getting Insulated gloves a bit less usefull, and increase value of getting  combat gloves. 
insulatet gloves are an engineering item. and engineering dont have any guns. 
this will altso help out the detective. If gloves are removed it will leave more fingerprints.

## Technical details

becuse all this only effects insulated gloves i used the Insulatedcomponent. 
changed the `ShotAttemptedEvent ` to altso be sent to gloves. 
more gloves whit the insulated component have then what this is intended to hit so `PreventOpperatinGuns` is false by defult.
all guns or tools whit the gun component that can be operated whit insulated gloves need `bigTrigger: true`

## Media

want a picture of a gun not fireing?

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: wearers of insulated gloves can no longer fire guns.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
CHUNKY FINGERS!!!! !!!!

**Comment by Cojoke-dot** [comment]
uh... whad this? I don't think you meant to put this in here.
image

**Comment by ImRenQ** [comment]
> based of https://tgstation13.org/wiki/Clothing_and_Accessories#Insulated_Gloves where insulated gloves cant use guns.

And at the TG station, you can get protection from electricity in just 30 seconds

изображение

**Comment by jorgun** [comment]
> uh... whad this? I don't think you meant to put this in here. image

yes, this was from somthigng else

**Comment by Dutch-VanDerLinde** [comment]
> > based of https://tgstation13.org/wiki/Clothing_and_Accessories#Insulated_Gloves
> 
> изображение

why does this matter

**Comment by KingFroozy** [comment]
You should probably just make any weapon be very inaccurate with insulated gloves on, cause it's doesn't make much sense to not be able to shoot at all. Love the change though, it gives engis some needed nerfs, and salvagers now won't go and ask you for insuls instantly upon spawning. Also a good time to port CE's insuls after this PR gets merged.

**Comment by keronshb** [comment]
Definitely not in favor of this, chunky finger insuls were not a good change.

**Comment by beck-thompson** [comment]
I think its is a fun idea but probably not on insuls. Make a new item that takes like 3 seconds to equip and unequipped and does the same thing. Like an extra thick insulated glove

**Comment by ninruB** [comment]
> I think its is a fun idea but probably not on insuls. Make a new item that takes like 3 seconds to equip and unequipped and does the same thing. Like an extra thick insulated glove

This could be a thing for budget insuls. Make them always insulated like normal insuls, but give them the chunky fingers trait.

**Comment by jorgun** [comment]
> I think its is a fun idea but probably not on insuls. Make a new item that takes like 3 seconds to equip and unequipped and does the same thing. Like an extra thick insulated glove

the original idea was to altso add this to the insulated gloves. but i did not like how it worked.

**Comment by lanse12** [comment]
there's like one person that likes this on tg

**Comment by ps3moira** [comment]
there's some TG PR's that infamously bad. this seems like one of them and we would be dodging a bullet by not adding this

**Comment by mirrorcult** [comment]
yeah i was never personally convinced by this one

**Comment by Hrosts** [comment]
Maybe instead of preventing use of guns, you get a do-after on things which require fine motor skills? E.g. wielding, reloading.

**Comment by PuroSlavKing** [comment]
I guess I'm the only one who liked this nerf in ss13 😭

**Comment by jorgun** [comment]
@CaptainSqrBeard thanks for some good feedback. 

The real reason for the pr i have probably not adressed.
And it's  upsides and downsides.
Take magboots. Allows you to Walk whit in 0 gravity and over spills at reduced walkilgspeeds.
Glasse: engineering glasses protected from welding but not from flashes. Sec hud you see Criminals but not hp.
For gloves there is just get insuls and no upgrade or side choice. No need to break ino cap room to get better gloves..
Whit this nerf they will still do there jobb: Preventing electrocution. If you want to do combat you need combat gloves.

There is also the only situation this matters in.
If it is  a chance of electrocution and a gunfight at the same time. 
Sec officers don't have insulated and whud have to go get that in any case  or risk electrocution 
Or call for hos or warden that does have combat gloves.

**Comment by Everturning** [comment]
this doesnt make the game more fun for anyone. if the intent is to nerf engi, why? why would you NEED to nerf engi? also:
>Sec hud you see Criminals but not hp.
why is this relevant? also the medsec hud exists
> No need to break ino cap room to get better gloves.
this is like. the weirdest reason. why should you escalate to BREAKING INTO CAPS ROOM in order to shoot gun

**Comment by NULL882** [comment]
This is so good.

**Comment by BolloTea** [comment]
Guys, let's make it simpler - cvar. Those who don't like it will be turned off, those who don't like it will be turned on

**Comment by ArtisticRoomba** [comment]
> For gloves there is just get insuls and no upgrade or side choice. No need to break ino cap room to get better gloves..

I assume you mean "there's no downside currently for insulated gloves" and "there's no reason to get combat gloves/cappy gloves"

> Whit this nerf they will still do there jobb: Preventing electrocution. If you want to do combat you need combat gloves.

So you want to make combat gloves more prevalent.

> There is also the only situation this matters in.
> If it is a chance of electrocution and a gunfight at the same time.
> Sec officers don't have insulated and whud have to go get that in any case or risk electrocution
> Or call for hos or warden that does have combat gloves.

I don't think this is a good balance change.

1. There is no reliable way to get combat gloves either than stealing Captain, HoS, or Ward's gloves, or by buying a toolbox from the traitor uplink. ~~An annoying 2TC purchase that prevents me from gambling like a pro.~~
2. This makes people have to juggle putting gloves on and off during combat. Making something annoying for no reason as balance isn't fun.
3. Sooooo... where is the security officer gonna get combat gloves to fight a threat that involves electricity? If this change is ever seriously considered you would have to put combat gloves somewhere. Not in secoff's locker, because that would make security too powerful. Not in the armory, because that is just silly. And you would have to update the contraband list to include combat gloves under security restricted contraband, in code and in Space Law. Also, Warden is not gonna leave their office. Their job is brig duty and watching over the armory with intense paranoia.
4. More fingerprints left behind as a reason seems weird. Antags usually wear gloves to hide their fingerprints anyways. This just leads to more glove juggling. If you want to decrease the annoying prevalence of yellow insulated fibers across the station then make budget insuls and regular insuls have different fibers (was actually thinking about PRing this earlier).
5. Regular insuls blocking shots while budget insuls not blocking shots makes little to no sense. This just makes the first tider who got to the YouTool more powerful.
6. I hope you were thorough when going through the guns to assign `bigTrigger` or else there's going to be a _lot_ of complaining if this ever gets merged.
7. And god please make this a cvar.

If you really want to make combat gloves more prevalent then make combat gloves have a benefit in combat, rather than making _everyone else_ that doesn't have the gloves suffer.
For example, it could increase a gun's accuracy or control. This makes procuring them viable and might be remotely valid in terms of balance, but there are still some really rough spots. For example:

1. Only two people on station have the gloves roundstart, Ward and HoS. Cappy doesn't get this type of benefit because their job is micromanagement, not necessarily catching valids. Atmos might have one pair roundstart depending on map, which might have to be demapped if they ever get benefits and are sec restricted. This also might open up powergaming by the HoP or the Captain begging or stealing extra gloves.
2. Alternatively, to balance things out, you could add combat gloves to secoff's lockers rounstart. The problem is that this doesn't match the idea of Nanotrasen as a company, they want things to be as cheap as possible. This also gives all of security insuls which tips the balance over to the security side when fighting traitors and the local tider.
4. Nukies already have combat gloves so this balances them when fighting Security but otherwise tips the balance over to the nukie side when fighting literally anybody else.
5. This does give another reason to buy the 2TC suspicious toolbox in the traitor uplink.
6. You could split the gloves into combat gloves and insulated combat gloves, but... see where this is going?

Overall a complicated topic. But I don't think this PR makes any sense.

**Comment by EthanQix** [comment]
That feeling when boxing gloves are better than insuls for shooting guns.

I don't think this PR brings anything useful or fun to the table. This is backwards game design. If you want to make combat gloves a more attractive option, then _make combat gloves a more attractive option_.

**Comment by RedNiloc** [comment]
If your going to nerf insuls (Which I prefer you didn't honestly), you should probably make them fire guns slightly slower rather that not at all because its less annoying and still gives people the option to fire guns while having them on. I feel like not firing guns all together just makes it more of a tedious process in combat.

**Comment by EthanQix** [comment]
As a side note, the (admittedly rare) tesla gun would be rendered unusable - the weilder needs insuls to not get shocked when firing it.

**Comment by HelpTheSteak** [comment]
This will do nothing except make gun combat clunky for engi syndies or them get metagamed for having combat gloves

**Comment by keronshb** [comment]
We're not interested in adding this as a mechanic. The original PR was controversial enough, and is a balance change that probably shouldn't have happened.

If the concern is that Combat Gloves absolutely _have_ to have some sort of combat advantage, then please research into what would be the best course of action with that, that isn't nerfing something else. That being said, that's if we really _need_ to do that.

**Pull request closed without merging**
