### PR TITLE
fix wall closet storage range

### PR DESCRIPTION
**Pull request by qwerltaz**
## About the PR

decrease wall closet entering into storage range when closing.

## Why / Balance

Wall closets would suck you in when you close them, except a few pixels where you could still reach them but not be within their storage range, leading to many failed attempts at not closing oneself inside.

## Media

new

https://github.com/user-attachments/assets/7f783a09-59ba-468f-bad2-bd536f52ad0f

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n
**Changelog**

:cl:
- tweak: Reduced wall closet range. It's now much easier to not close yourself inside by accident.

### CODE REVIEW

**Comment by lzk228** [comment]
add cl, people really should know about that

**Comment by bruhmogus** [comment]
THANK GOD!!!!

**Comment by baddiePRO** [comment]
Salvation!!!!!!!

**Comment by AboveDeceased** [comment]
I want to hug you.

**Pull request merged**
