### PR TITLE
Paraplegicn't zombies

### LINKED ISSUE #22990: Being zombified as a wheelchair-bound character makes you immobile
## Description
You can't move.

**Reproduction**
1. Spawn as a wheelchair-bound character
2. Chug some romerol
3. Stab yourself to death
4. Become a statue

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

resolves #22990

People with the wheelchair bound trait that get zombified now get their legs healed and will be able to walk again.

## Why / Balance

Not being able to walk as a zombie isn't fun.

## Technical details

Upon being zombified the entity now loses the WheelchairBound and LegsParalyzed components.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- fix: Paraplegic entities have their legs healed when zombified.

### CODE REVIEW

**Comment by lzk228** [comment]
its a miracle!

**Comment by metalgearsloth** [comment]
Can we remove wheelchairs until vehicles are fixed yet.

**Comment by K-Dynamic** [comment]
Initial infected new lore: genetic extremists trying to spread zombie infection and do stuff like become immortal or cure paraplegics

**Comment by Kadeo64** [comment]
> Can we remove wheelchairs until vehicles are fixed yet.

isn't vehicles being fixed part of vehicle code refactor?
and aren't we only getting vehicle code refactor when @brainfood1183 finishes anurans? (or whatever the next species is)

**Comment by 2013HORSEMEATSCANDAL** [comment]
honestly i feel like those guys should crawl.

**Review by EmoGarbage404 — DISMISSED** [review]
need to pull master since wheelchairboundcomponent got redone

**Pull request merged**
