### PR TITLE
[Tweak] Arachnid tweaks

### PR DESCRIPTION
**Pull request by PixelTheKermit**
## About the PR

Makes it so arachnids get less hungry, take less asphyxiation damage and are slowed down less from pain
They can also wear glasses now (don't ask me how)

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**

:cl: PixelTK
- tweak: Arachnids suffer less now from hunger decay, asphyxiation and slowdown from damage.
- tweak: Arachnids can now wear glasses.... somehow

### CODE REVIEW

**Comment by DawBla** [comment]
Can you also add them glasses slot? I think it wasn't intended but as of right now you pretty much can't play sec as an arachnid and as engi you need to carry a welding mask

**Comment by PixelTheKermit** [comment]
> Can you also add them glasses slot? I think it wasn't intended but as of right now you pretty much can't play sec as an arachnid and as engi you need to carry a welding mask

having no glasses is intended

**Comment by metalgearsloth** [comment]
Considering welding is pretty important to engineering not being able to weld (when job selection isn't guaranteed) is pretty huge.

**Comment by PixelTheKermit** [comment]
> Considering welding is pretty important to engineering not being able to weld (when job selection isn't guaranteed) is pretty huge.
> 
> This also applies to sechud / medhud / whatever else.

I personally think they shouldn't have glasses, but I guess I could try out giving it a go for a bit and see how it goes.

**Comment by PixelTheKermit** [comment]
Right renamed pr to be shorter, and gave arachnids a glasses permit.

**Comment by PixelTheKermit** [comment]
If there's any more changes required do let me know.

**Comment by deltanedas** [comment]
good for gameplay + looks funny

its like those images of cats wearing headphones when they obviously are not over their ears

**Pull request merged**
