### PR TITLE
[New Food] Pelmeni

### PR DESCRIPTION
**Pull request by SonicHDC**
## About the PR

**Media**

https://user-images.githubusercontent.com/100022571/234249394-84fd734d-1c9c-4ffb-b65d-7bb1a49e2f37.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: SonicDC
- add: Added pelmeni!

### CODE REVIEW

**Comment by potato1234x** [comment]
whys the video from corvax?

**Comment by keronshb** [comment]
There is a current freeze on new recipes: https://github.com/space-wizards/space-station-14/issues/8524

**Comment by keronshb** [comment]
@SonicHDC you didn't have to close the PR. You can keep it open.

**Comment by keronshb** [comment]
@SonicHDC when the chef rework is done please feel free to reopen this

**Comment by metalgearsloth** [comment]
Just make it dumplings as they're significantly more popular than this.

**Comment by SonicHDC** [comment]
This pr is closes.
Recreated to https://github.com/space-wizards/space-station-14/pull/16286

**Pull request closed without merging**
