### PR TITLE
Fix hand order

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

as god intended

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by MACMAN2003** [comment]
i don't think putting the right hand on the left side is a good idea because it may confuse people who have trouble differentiating between left and right

**Comment by Emisse** [comment]
this is how it always was before, and how it has been in ss13 forever

**Comment by arimah** [comment]
Disregarding what SS13 has done forever (that game is no pinnacle of UI design by any stretch of the imagination), is there any reason for any reasonable person to reason themselves into the position of thinking left should be on the right and vice versa? _How_ does it make sense to swap these two? In game mechanical terms it makes exactly no difference, just... _why?!_ In real life, my right hand is on my right-hand side, funnily enough.

**Comment by EmoGarbage404** [comment]
I dont know how to say it but the art just looks better like that

**Comment by Emisse** [comment]
> Disregarding what SS13 has done forever (that game is no pinnacle of UI design by any stretch of the imagination), is there any reason for any reasonable person to reason themselves into the position of thinking left should be on the right and vice versa? _How_ does it make sense to swap these two? In game mechanical terms it makes exactly no difference, just... _why?!_ In real life, my right hand is on my right-hand side, funnily enough.

every item you see is from the front, basically facing you. this follows that and assumes youre looking at yourself from the front. tats why its like this

**Pull request merged**
