### PR TITLE
Added ore boxes to cargo.

### LINKED ISSUE #20251: Ore boxes should be cargo orderable
Title.

### PR DESCRIPTION
**Pull request by gusxyz**
## About the PR
Fixes #20251.

Adds orderable empty ore boxes to cargo.

**Changelog**
:cl:
- add: Empty ore boxes are now orderable from cargo.

### CODE REVIEW

**Comment by NancokPS2** [comment]
Why would cargo order ores instead of the refined materials? Is there a benefit to it?  
  
Cargo just needs to get orders for silver and gold already.

**Comment by deltanedas** [comment]
its for an ore box not ores...

**Comment by gusxyz** [comment]
> its for an ore box not ores...

Exactly what delta said and to expand I believe cargo not being able to order gold and silver is intentional maybe not.
It gives salvage a duty to provide the station with necessary material it can not order.

**Review by EmoGarbage404 — APPROVED** [review]
you accidentally deleted the `.run/Content Server+Client.run.xml` file.

fix that and this is gtg

**Comment by gusxyz** [comment]
It should be ready for merge let me know if i broke anything else

**Pull request merged**
