### PR TITLE
Refactor InnateToolSystem and InnateToolComponent

### PR DESCRIPTION
**Pull request by TokenStyle**
## About the PR

InnateTool is unremoveable items in hands (if has some). Used primararly for borgs. Drops items on destory entity. Useful component, though code quality of InnateTool should be more consistent and persistent. #25429

## Why / Balance

#25429

## Technical details

Refactor to follow conventions. Refac to Entity<...>. Deprecated removed

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Atm InnateToolComponent used only by behonker, id: BaseMobBehonker

### CODE REVIEW

**Comment by TokenStyle** [comment]
Found good code review #25994 of conventions, consistency. Excellent!

**Comment by TokenStyle** [comment]
HandEvents are all classes instead of record structs. Also without `[ByRefEvent]` (mostly)

**Comment by metalgearsloth** [comment]
Code seems okay but doesn't actually address the linked issue.

**Comment by metalgearsloth** [comment]
Code needs re-doing and I don't think this is the correct approach.

**Pull request closed without merging**
