### PR TITLE
Add banana cream pie recipe

### PR DESCRIPTION
**Pull request by AJCM-git**
Currently outputs ashes because the microwave is broken and makes every recipe output ashes, but once that is fixed it should work.
The recipe is way more complex in SS13 but we don't have the necessary tools to replicate that, so lets have this for now.

:cl: Abraham
- add: Can now cook banana cream pies

### CODE REVIEW

**Comment by Visne** [comment]
> 
> 
> Currently outputs ashes because the microwave is broken and makes every recipe output ashes, but once that is fixed it should work.
> The recipe is way more complex in SS13 but we don't have the necessary tools to replicate that, so lets have this for now.

Pretty sure microwave doesn't output ashes for every recipe, some stuff works.

**Comment by SweptWasTaken** [comment]
> 
> 
> > Currently outputs ashes because the microwave is broken and makes every recipe output ashes, but once that is fixed it should work.
> > The recipe is way more complex in SS13 but we don't have the necessary tools to replicate that, so lets have this for now.
> 
> Pretty sure microwave doesn't output ashes for every recipe, some stuff works.

This. I'm sure I cooked stuff the other day.

**Comment by AJCM-git** [comment]
Try going to your locals and make a burger and you will see what i mean. Here is the recipe straight from master
```
  time: 5
  reagents:
    chem.Flour: 5
  solids:
    FoodMeat: 1
```

**Comment by Visne** [comment]
> 
> 
> Try going to your locals and make a burger and you will see what i mean. Here is the recipe straight from master
> 
> ```
>   time: 5
>   reagents:
>     chem.Flour: 5
>   solids:
>     FoodMeat: 1
> ```

Yes, cheeseburger is broken, but not every recipe.

**Comment by Visne** [comment]
This recipe should work now #3411 is merged.

**Pull request merged**
