### PR TITLE
Delay the selection of traitors at round start.

### PR DESCRIPTION
**Pull request by Vordenburg**
## About the PR 

This PR delays traitor selection until X+Y time has passed, where X is a constant and Y is a random number. Both are server-side configurable.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a delay at the start of Traitor mode before players are selected to be an antagonist.

### CODE REVIEW

**Comment by Interrobang01** [comment]
This is to prevent traitor suicide rolling, right?

**Comment by Elijahrane** [comment]
> This is to prevent traitor suicide rolling, right?

There's that and it stops some of the cheese strats where you emag an objective within 30 seconds before anyone who could stop you can even walk there.

**Comment by GoodWheatley** [comment]
I’m going to be honest, while it might just be that I’m used to how it currently works, I don’t really see the need for this. Traitor suicide rolling is more of a player issue than a game issue, and those players should just be banned instead of the game changed to accommodate them (and what’s stopping them from suiciding once enough time has passed that they know they’re not a traitor)? And the emag cheese strat is annoying, but you also have to escape on the shuttle to complete a steal objective, and sec seeing all the bridge doors emagged and the comms console board gone is going to lead to an instant red alert, making escape much harder. Overall, I just don’t think this is a needed change.

**Comment by EmoGarbage404** [comment]
I don't mind this. Random delays for this kind of stuff isn't bad at all. Additionally, a small grace period is kinda nice and helps players start the round in a more typical way, even if they're a traitor.

**Comment by Just-a-Unity-Dev** [comment]
i like it, i prefer being surprised in bar with "whiskey echo whiskey lima alpha delta" rather than in engineering. like emo said, some randomized delay would be nice

**Comment by QuietlyWhisper** [comment]
Might also be relevant to the idea of sleeper agents I heard a while ago. 

Although I guess "activate sleeper agent" is kinda lame of an objective..

**Comment by Cheackraze** [comment]
I kinda like the idea as long as the delay is on the shorter end like 5 minutes or so tops.

**Comment by OldDanceJacket** [comment]
> I’m going to be honest, while it might just be that I’m used to how it currently works, I don’t really see the need for this. Traitor suicide rolling is more of a player issue than a game issue, and those players should just be banned instead of the game changed to accommodate them (and what’s stopping them from suiciding once enough time has passed that they know they’re not a traitor)? And the emag cheese strat is annoying, but you also have to escape on the shuttle to complete a steal objective, and sec seeing all the bridge doors emagged and the comms console board gone is going to lead to an instant red alert, making escape much harder. Overall, I just don’t think this is a needed change.

It's not **_just_** emag minute one strats;  After months of playing, a number of folks have noticed that the best time to get your objective is to get it in the first few minutes of the round, before departments are filled up, before folks are back from the bathroom/kitchen when they readied up, before everyone has their bearings and the late joiners start coming in from arrivals.

It adds a little bit of a grace period for Engineers to set up AME, HoP to sort out paperwork, SecOff's to shoot the shit, Bartenders and Chefs to prep a few meals, etc. 
I like it. 😃

**Comment by GoodWheatley** [comment]
> > I’m going to be honest, while it might just be that I’m used to how it currently works, I don’t really see the need for this. Traitor suicide rolling is more of a player issue than a game issue, and those players should just be banned instead of the game changed to accommodate them (and what’s stopping them from suiciding once enough time has passed that they know they’re not a traitor)? And the emag cheese strat is annoying, but you also have to escape on the shuttle to complete a steal objective, and sec seeing all the bridge doors emagged and the comms console board gone is going to lead to an instant red alert, making escape much harder. Overall, I just don’t think this is a needed change.
> 
> It's not **_just_** emag minute one strats; After months of playing, a number of folks have noticed that the best time to get your objective is to get it in the first few minutes of the round, before departments are filled up, before folks are back from the bathroom/kitchen when they readied up, before everyone has their bearings and the late joiners start coming in from arrivals.
> 
> It adds a little bit of a grace period for Engineers to set up AME, HoP to sort out paperwork, SecOff's to shoot the shit, Bartenders and Chefs to prep a few meals, etc. I like it. 😃

I do know that the current meta is rushing the objective, and that’s what I said in my critique. My point was while it’s possible to rush to get your objective, you’re ultimately drawing much more attention to yourself (and making it much more likely you’ll get caught) than if you wait until the station’s already descended into chaos. Adding a random delay to becoming an antag feels like a solution to something that isn’t a problem.

**Comment by Interrobang01** [comment]
Unless I'm not seeing something, I feel like this needs more player feedback. it's gonna be weird to be going around doing your job when you suddenly get turned into a traitor for no apparent reason. Everything else mechanically seems good though.

**Comment by mirrorcult** [comment]
> Traitor suicide rolling is more of a player issue than a game issue, and those players should just be banned instead of the game changed to accommodate them

this isnt how game design works. player issues are game issues

**Comment by mirrorcult** [comment]
i think this change is pretty good

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
