### PR TITLE
Energy Shotgun Change 2 - Narrow Nerf + instances from NoSpawn --> categories: [ HideSpawnMenu ] + self recharge removed + 1 more shot + normal recharge speed

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Nerfs the Narrow Fire Mode from 60 dmg over 4 projectiles to 52 damage over 4 projectiles.
Makes the energy shotgun no longer self recharge
Changes uses of noSpawn to categories: [ HideSpawnMenu ]
## Why / Balance

Miscommunication between me and Slam, as well as a bug that was in the release version of the shotgun lead to the narrow fire mode being stronger than intended by the maintainers.
The shotgun was basically a game changer during nuclear operative rounds, depending on which side got it. With the self recharge removed, it should no longer remove the concept of attrition from nukie rounds. If this turns out to make the weapon too weak, I'll change it.
 https://github.com/space-wizards/RobustToolbox/pull/5364 for the noSpawn instance changes
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Energy Shotgun's narrow fire mode's projectiles now deal 13 heat dmg each, for a total of 52. The energy shotgun additionally no longer self recharges and has received some minor buffs.

### CODE REVIEW

**Comment by slarticodefast** [comment]
You missed the last `noSpawn: true` for EnergyShotgunStealObjective in `traitor.yml`

**Comment by Boaz1111** [comment]
fuck, apologies, one moment

**Comment by Emisse** [comment]
it should probably have self recharge removed

**Comment by Pumkin69** [comment]
self recharge should stay and be nerfed to like 1 every 10 seconds or nerf the damage on narrow shot more and make the disabler shots more narrow so they hit more often

**Comment by 0x6273** [comment]
Isn't there a freeze on new guns?

**Comment by Boaz1111** [comment]
> Isn't there a freeze on new guns?

what about the word “nerf” do you not understand the gun has existed for a while now

**Comment by PrivateJoe09** [comment]
I disagree with the proposed changes. The Head of Security's gun should be a game-changer. Nukies already have powerful tools like the energy shield with a 95% reflection rate or a simple EMP. The self-recharging shotgun adds crucial diversity to their gameplay, making encounters more dynamic than just a "rush the armory with a lube grenade and fight security officers with MKs, maybe facing a HoS with a WT."

Nerfing the shotgun's self-charge risks relegating it to a weapon that stays in the locker. An EMP could easily neutralize the HoS, rendering the shotgun—a unique asset—useless. The energy shotgun already has a strong counter at the station for non antags if it gets taken: the reflect vest or cap's vest. The Head of Security, tasked with protecting the station, should have a weapon powerful enough to compel antagonists to plan around it.

Without the self-recharge, any experienced HoS would likely default to using a bulletproof vest, riot shield, and WT, making the energy shotgun a secondary option—useful only in niche situations, like against Diona or Moths, rather than the “Oh no, the HoS is here—prepare to EMP and push” reaction it should provoke.

If you must nerf it, consider lowering the shot count to 5 but maintaining the self-recharge. You could also nerf narrow a bit more and buff the wide shot feature as its spread is very high, making its effective range locked at 1 or 2 tiles at best. After all, it’s an energy shotgun. You’ve mentioned before that the counters exist—people just need to use them effectively. And when they do, the HoS often ends up dead.

**Comment by Lomovar** [comment]
I think due to the removal of self recharging, it is worth increasing the capacity of the shotgun battery

**Comment by EdenTheLiznerd** [comment]
I agree, the other changes are fine but removing the self-recharge will make this weapon useless on nukies. Power usually ends up going out more times than not meaning that there will be no way to recharge the gun, I'd the gun is to remain reliable I'm fine with the damage being touched up on but the self-recharge should stay.

**Comment by Boaz1111** [comment]
You’d best discuss this with Emisse, she wanted the outright removal.

**Comment by Boaz1111** [comment]
happy with the changes as they are now personally. will not touch the pr until maintainer review.

**Comment by Carmell0** [comment]
If it stopped self charging, I'd personally stop using it and I know others would too. Honestly, without self charging it's pretty much just a worse enforcer. Like, significantly worse. I'd rather use a kammer.

**Comment by Boaz1111** [comment]
Well then I suppose it’s a damned if you do, damned if you don’t situation

**Comment by Clone0401** [comment]
yea, if we don't want the full self-recharge, i'm infavor of makeing it like one of the comments above, something like 1 every 10 seconds.  another thing that could be done is EMP resistance but that doesn't help with the nukie issue

**Comment by slarticodefast** [comment]
Let's give the new balance a try. Thank your for your contribution.

**Comment by BramvanZijp** [comment]
I feel like this is going to make the gun much much worse, and I feel like the HoS SHOULD have a powerfull gamechanging weapon like the captain. Also, there were 2 self recharging guns, caps laser and energy shotgun, which IMO is much better then having it just be one of them, since in as mentioned, nukies, they can steal one without them instantly having the only recharging gun if the other is still in crew hands.

Here is how I would suggest a rework to work instead:
Re-add the self recharge, balance the amount as needed keeping the below changes in mind
Optionally make it so that firing the gun puts the self recharge on cooldown for x seconds, potentially depending on the firemode.
Change the shotgun to work with a % charge system instead of a number of shots charge system
Make the various firing modes take various amounts of charge. Disabler would take very little, wide spread average while narrow spread takes up more.

This way we can see the disabling mode used more often, and have widespread not be outright obsolete compared to narrow.
I feel like the self recharge functionality is something we should not take away from the weapon, but the above may make it more fair.

**Pull request merged**
