### PR TITLE
Add AI Lawpendium, a book with NT AI laws

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

add a book with all nt ai laws to rd's locker

## Why / Balance

good to know which set of laws you are about to load

## Technical details

no

## Media

https://github.com/user-attachments/assets/18e6e555-4ba7-46bf-a5c6-4abd8c647695

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

no

**Changelog**

:cl:
- add: Added a book with all NT AI laws to RD's locker.

### CODE REVIEW

**Comment by lzk228** [comment]
> I would suggest giant flashing rainbow waving text at start stating that AIs can't willingly change their laws so you should be cunning, make sure AI is busy before attempting law change and retreat if caught otherwise you have to come in heavy and tools to breach in.

yeah, these things are already planned, but i don't see how it affects the book in this pr
the book is just a showcase for all laws, so unaware crew could learn what they can expect from ai and don't go search laws in the game's code

**Comment by SlimmSlamm** [comment]
The Captain should have one or there should be one that spawns inside AI Upload on all stations

**Comment by PotentiallyTom** [comment]
I think this would work better as a guidebook entry, with the book acting as a link to said entry like the space law book. I don't think the potential AI laws should be hidden knowlege; syndies grabbing antimov aren't going to be able to reference this. 

I've not looked at the guidebook code but I imagine it would make it easier to keep up-to-date too.

**Comment by lzk228** [comment]
hm.. maybe guidebook is better, but I'm not sure if it sipports loc strings

**Comment by Everturning** [comment]
> I would suggest giant flashing rainbow waving text at start stating that AIs can't willingly change their laws so you should be cunning, make sure AI is busy before attempting law change and retreat if caught otherwise you have to come in heavy and tools to breach in.
> 
> Also that with AI in intelicard there is no AI to upload laws into... No idea if dormant AIs laws can be changed or they require role taken/player.

Dormant AI laws cannot be changed, no, i know because I uploaded nutimov into a dormant ai and when the ai came online it had crewsimov still

**Pull request closed without merging**
