### PR TITLE
Makes the e-sword light plasma fires, as intended.

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR
Made e-swords act as an ignition source

## Why / Balance
I saw a funny med nukie running around in plasma gas with an e-sword not on fire and thought "they should be on fire"

## Technical details
Added an event to IgnitionSourceSystem to properly work with the "ItemToggleHotComponent". Previously it only worked with the "IsHotEvent".

Added the IgnitionSource component to the energy sword.

## Media

https://github.com/space-wizards/space-station-14/assets/83733158/614456ff-38b6-4dbf-93ce-aa9472647a4b

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl: 
-tweak: E-sword now lights plasma fires

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Oh, I forgot to say, e-swords doing this is an intended feature and more of a bug fix over a new thing. The e-sword had the ItemToggleHot component in it already, just did not work right.

**Comment by K-Dynamic** [comment]
Atmos techs releasing open plasma fuel tanks at nukies:

Also I hope this means eswords can be used as welders

**Comment by Hmeister-real** [comment]
> Also I hope this means eswords can be used as welders

I really hope this means that too

**Comment by K-Dynamic** [comment]
> I really hope this means that too

Furiously repair syndie borgs with sword stabs :trollface:

**Comment by Cojoke-dot** [comment]
> Also I hope this means eswords can be used as welders

I thought about it but that would just cause too many issues. Nukies would be a lot more defensive and would cause nukie forts. There would also be the issue of the borgs and walls, having infinite Borg repairs would be broken. Finally, for syndicate, accidentally clicking on a normal wall or door when it's out would start to weld the object and blind you.

**Comment by HoidC** [comment]
> > Also I hope this means eswords can be used as welders
> 
> I thought about it but that would just cause too many issues. Nukies would be a lot more defensive and would cause nukie forts. There would also be the issue of the borgs, having infinite Borg repairs would be broken. Finally, for syndicate, accidentally clicking on a normal wall or door when it's out would start to weld the object and blind you.
> 
> If the e-sword became a welder it would need some kind of limit to its use, which would just destroy the item.

why would they make nukie forts, they already have access to welding tools and this isn’t a problem + that’d be a really ineffective strategy

**Comment by Cojoke-dot** [comment]
> Why would they make nukie forts, they already have access to welding tools and this isn’t a problem + that’d be a really ineffective strategy

True, it's not that great of an argument, but I think it would still cause a lot of issues for non-nukies. It would also be pretty hard to manipulate in order to weld, maybe the e-pen could weld. Either way, welding e-swords is not the purpose of this PR, I'll make a conversation in Discord.

**Pull request merged**
