### PR TITLE
give lizards their hair

### PR DESCRIPTION
**Pull request by LankLTE**
Snakes had their arms taken by god as punishment for their sins. Lizards have evolved past this feeble restriction, regaining not only their arms, but even their thumbs. They're just as good as humans in every way- except for one. Their scaled skulls are too tough for the hair follicles to arise though, into the light of day for all of spacekind to see. 

This changes today. 

With this PR, I've taken the step that you're all too afraid to and given the lizards their right to hair. "But think of the children!" you might plea. But think of **this:** how else will all these beautiful combinations come to grace our eyes?

The Moron!
image

The Fed!
image

what the fuck
image

Thank you all. I'll be seeing you on the station- with the gorgeous, golden locks that we have now been granted.

:cl: Lank
- add: Lizards will now be able to bless the station with gorgeous hair flowing from their scaly scalps.

### CODE REVIEW

**Comment by Skarletto** [comment]
what the hell

**Comment by LankLTE** [comment]
> what the hell

Humanity often fears that which they do not understand. Fear not, and be calm- you will come to with time.

**Comment by DogZeroX** [comment]
Only really want this if it's a wig item tbh

**Comment by mirrorcult** [comment]
really do not like

**Comment by Emisse** [comment]
this makes me physically sick

**Comment by UbaserB** [comment]
i dont know, i kind of like this addition.

**Comment by deltanedas** [comment]
i think it is wrong but funny

**Comment by asperger-sind** [comment]
This is so sickening that I went outside, climbed the closest mountain I could find, sat there looking at the sky like an idiot for 6 hours and got the Lord to whisper me the truth, I am now a prophet and our Lord's words are:
"THEE, LIZARDKIND SHAN'T HAVETH HAIR MORE PLENTLY THAN THEE EYEBROWS"

**Comment by UbaserB** [comment]
why dont we merge for a week and see how the community responds?

**Comment by AJCM-git** [comment]
What is hair but really thin scales

**Comment by moonheart08** [comment]
better idea than testmerging it:

**Comment by deltanedas** [comment]
:trollface:
nobody cares about who i was until i put on the mask

**Comment by LankLTE** [comment]
:despair:

**Pull request closed without merging**
