### PR TITLE
Update to backpacks and Duffels. Ported remainder, updated existing. Other generic fixes

### PR DESCRIPTION
**Pull request by Peptide90**
Changed names & descriptions in backpacks and duffel.
Added new backpacks for ERT.
Added Hydroponics and Surgery duffels.
To Do: Sprites for all above.
Signed-off-by: Peptide90 <user94636@protonmail.com>

## About the PR 

**Screenshots**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
@SweptWasTaken 

yaml looks fine to me.

**Comment by SweptWasTaken** [comment]
I do not agree with adding ERT duffel as we don't have ERT. No Botany duffel either as there's no unique sprite for it.

**Comment by Peptide90** [comment]
@SweptWasTaken My next PR I have now has the sprite for botany as well as all over missing backpacks and duffels (not done satchels yet). And have created the relevant loadouts for ERT, virology, genetics and toxins. They are mostly bare for now but just laying the groundwork for future updates.

**Comment by Peptide90** [comment]
Closing PR to get my repo setup correctly. Will send new PR on branch.

**Pull request closed without merging**
