### PR TITLE
Antag species whitelist for nukies

### PR DESCRIPTION
**Pull request by juliangiebel**
## About the PR

This PR adds a whitelist to `AntagLoadProfileRule` that allows certain species to be used regardless of the species override

The whitelist for nukies in this PR contains:
```yaml
    - Human
    - Dwarf
    - Arachnid
    - Moth
    - Reptilian
 ```
 The other species are commented out and should be uncommented when the issues they have are fixed

## Why / Balance

This allows better control of what species are allowed for a given antag. In this case the nuclear operatives

This is an alternative to #29707

### CODE REVIEW

**Comment by deltanedas** [comment]
it should also have issues made and linked so it doesnt just rot because nobody knows what its referring to

**Comment by juliangiebel** [comment]
This PR should be merged with #29707

**Comment by Jezithyr** [comment]
Yep merging this into https://github.com/space-wizards/space-station-14/pull/29707, I'll be updating the description to reflect that as well

**Comment by VasilisThePikachu** [comment]
Merged in as part of another pr

**Pull request closed without merging**
