### PR TITLE
Removes unfunny/unoriginal bar signs.

### PR DESCRIPTION
**Pull request by SweptWasTaken**
I removed 

- aloha snackbar
- ~~- maltese falcon~~
- the femboy one
- scotch servin will
- slipper shots
- syndi bar sign
- the cavern
- the adminbus
- the bark
- the cavern
- the nest
- the shaken
- vlads salad bar
- honked n loaded
- old cock inn 
- the greytide

I think these are all uninspired or shit. I could go into detail about why I chose to remove them, but basically I wanted to slash the shitty bar signs. 

The removed will of course be uploaded to the rsi-dump if anyone wants to readd them.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
ASS NATH

**Comment by gurfan** [comment]
powerful

**Comment by gurfan** [comment]
just about every bar sign you're deleting has a place in the game, why bother server owners in the future who have to go readd all the signs that were removed because you personally didn't like them, removals like this shouldn't be a part of the base game

**Comment by Visne** [comment]
> just about every bar sign you're deleting has a place in the game, why bother server owners in the future who have to go readd all the signs that were removed because you personally didn't like them, removals like this shouldn't be a part of the base game

You're right, the removals shouldn't be part of the base game as they shouldn't even have been in the base game to start with.

**Comment by SweptWasTaken** [comment]
> 
> 
> just about every bar sign you're deleting has a place in the game, why bother server owners in the future who have to go readd all the signs that were removed because you personally didn't like them, removals like this shouldn't be a part of the base game

Every texture I remove from the game gets relocated to https://github.com/space-wizards/rsi-dump

**Comment by partyaddict** [comment]
why did you add a furry one

Aloha Snackbar!

**Comment by SweptWasTaken** [comment]
> 
> 
> why did you add a furry one
> 
> Aloha Snackbar!

Which ones the furry one

**Comment by partyaddict** [comment]
> 
> 
> > why did you add a furry one
> > Aloha Snackbar!
> 
> Which ones the furry one

birdcage

also fucking hell you can't even read the wiggle room. god damnit swept

**Comment by ancientpower** [comment]
the birdcage sign already existed and it's a play on vox looking like birds

**Comment by partyaddict** [comment]
> 
> 
> the birdcage sign already existed and it's a play on vox looking like birds

do we have vox.

**Comment by PJB3005** [comment]
> do we have vox.

No(t yet)

**Comment by SweptWasTaken** [comment]
> 
> 
> > the birdcage sign already existed and it's a play on vox looking like birds
> 
> do we have vox.

We don't have AI so there's no need for it

**Comment by SweptWasTaken** [comment]
And if SS14 gets a race other than human it will be lizards because they're the most canon.

**Comment by ancientpower** [comment]
Everything and nothing is canon.

**Comment by SweptWasTaken** [comment]
> 
> 
> Everything and nothing is canon.

Does that mean New Zealand is canon?

**Comment by unusualcrow** [comment]
i propose renaming the term "bikeshedding" to "barsigning"

**Comment by PJB3005** [comment]
> And if SS14 gets a race other than human it will be lizards because they're the most canon.

Nah, Vox.

**Comment by SweptWasTaken** [comment]
> 
> 
> > And if SS14 gets a race other than human it will be lizards because they're the most canon.
> 
> Nah, Vox.

You're banned

**Comment by ancientpower** [comment]
TGstation is not my station, trees and vox not lizards and moths ok. praise nanotrasen.

**Comment by TheChosenEvilOne** [comment]
put me in the screenshot

**Comment by Zumorica** [comment]
> put me in the screenshot

me too, and remember to contribute to SS14 nerds

**Comment by SweptWasTaken** [comment]
This is ready for a merge

**Comment by optimumtact** [comment]
don't worry everyone we will add these back in our content fork everyone will inevitably use.

**Comment by ike709** [comment]
absolute madman

**Pull request merged**
