### PR TITLE
So long, Detroit.

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## Why? 
Due to my increased focus on contributing to the codebase and creating new features, maintaining and actively working on my map has no longer become my priority. I quite unfortunately have let it fall a bit to the wayside, and as such the quality of it has suffered. While i did enjoy working on and maintaining Barratry, in recent weeks, it's felt more like a chore than something i really enjoy.

Because of that, i'd like to formally remove the map from the game. The ideas i've had for it have run their course and it's about time someone else had the opportunity to showcase their own creations.

From the very first design, named Shitstation, it's been my pleasure to map for this game. I hope everyone enjoyed Barratry.

**Changelog**

:cl:
- remove: Barratry has been removed.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
RIP Barratry, ‘twas my favorite map too

**Comment by jessicamaybe** [comment]
Fixes #8038 and #9429

**Comment by EmoGarbage404** [comment]
> Fixes #8038 and #9429

lol both of these have been fixed for a while

**Comment by HoidC** [comment]
rest in peace detroit

we hated you

**Comment by mirrorcult** [comment]
now i definitely wont play the game

**Comment by Veritius** [comment]
o7

**Comment by mirrorcult** [comment]
that said it should probably just get derotated and not deleted

**Comment by Just-a-Unity-Dev** [comment]
i need a new favorite map now.......

**Pull request merged**
