### PR TITLE
Rainbow Weed

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds rainbow weed.

You can get rainbow weed from mutating regular weed, it has 3 space drugs, 3, lipolicide, 2 mindbreaker toxin, 2 happiness, and 0.6 psicodine.

depends on #27134

## Why / Balance

rainbow weed is a staple of the ss13 botanist, it was surprising we didnt have it already, mostly for rp purposes

## Media

An example of creating rainbow smokes

https://github.com/space-wizards/space-station-14/assets/79580518/4e19af03-d8b8-4205-8d50-b4021476d4fa

What all the reagents do together

https://github.com/space-wizards/space-station-14/assets/79580518/9ce57fdf-5039-45db-b269-7f1f9cf7d7f7

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added rainbow weed. It is obtained by mutating regular weed.

### CODE REVIEW

**Comment by deltanedas** [comment]
now require mannitol splashed on brain to put in mmi :trollface::trollface::trollface:

**Comment by potato1234x** [comment]
sounds like a job for emogarbage :clueless:

**Comment by UbaserB** [comment]
> * happiness makes you high, makes you laugh and whistle but when OD'ed it makes you cry

can you make happiness craftable using laughter, space drugs and some other chemical

**Comment by potato1234x** [comment]
its already craftable
image

**Comment by UbaserB** [comment]
> its already craftable

then change the recipe to AT LEAST include laughter, or make it so that there is an alternative recipe along with this one which is easier to craft but requires botany to help (with the liquid laughter and all)

**Comment by potato1234x** [comment]
might replace n2o with laughter

**Comment by UbaserB** [comment]
One more thing, Euphoria would sound cooler than happiness. After all, euphoria is the exhilarating feeling of happiness and kind of sounds cooler

**Comment by K-Dynamic** [comment]
Psychologist rp - rainbow weed foam grenades for mass mental health vines :trollface:

**Comment by mirrorcult** [comment]
rainbow weed should be added separately from the reagents included here, i dont see them as necessarily relevant to eachother

**Review by mirrorcult — CHANGES_REQUESTED** [review]
above

**Comment by potato1234x** [comment]
Theyre all narcotic reagents, i dont see why they shouldnt be added with the weed...

**Comment by Partmedia** [comment]
Per the reviewer feedback above and the [PR guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html), please separate unrelated changes to a separate PR or this PR may be closed.

**Comment by potato1234x** [comment]
Aight will do that soon, dont see how theyre unrelated tho

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
