### PR TITLE
Liberation Station Update

### PR DESCRIPTION
**Pull request by Jackal298**
## About the PR

PR for the "Liberation Station" update, magazines for weapons in the game were added to it, as well as an emag chambered for .25 caliber cartridges and a magazine for this caliber, access to it was also limited, now in order to take an item from there you need access from the "Armory "

I'd like someone to put it in the armory so the varden can give it extra magazines and speedloaders for weapons.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Changed vending machine "Liberation Station"

### CODE REVIEW

**Comment by deltanedas** [comment]
even if its not a funny centcom/admeme item it has a **ridiculous** amount of ammo

**Comment by Matz05** [comment]
It's also got upgraded ammunition from Science researches. Maybe remove that?

**Comment by Emisse** [comment]
armory isnt meant to have this

**Comment by CrigCrag** [comment]
Liberation Station doesn't appear in any armory afaik

**Comment by Jackal298** [comment]
> It's also got upgraded ammunition from Science researches. Maybe remove that?

there are not enough of them, let them be so that the RND can learn better technologies

**Comment by Jackal298** [comment]
> armory isnt meant to have this

and then what access to give?

**Comment by Jackal298** [comment]
> even if its not a funny centcom/admeme item it has a **ridiculous** amount of ammo

I did an update towards magazines for weapons, I brought it up, did it get better?

**Comment by Emisse** [comment]
its for admemes

**Comment by Jackal298** [comment]
> its for admemes

I removed access

**Pull request closed without merging**
