### PR TITLE
Fix winter coats prices

### PR DESCRIPTION
**Pull request by MilenVolf**
## About the PR
Fixes craftable winter coats prices
Makes most craftable winter coat require 5 cloth and 3 durathread to justify it's price.

## Why / Balance
It was abusable by cargo with uniform printer.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
No CL

### CODE REVIEW

**Comment by Kadeo64** [comment]
science and RD winter coats should keep caustic resist because a: caustic sucks and b: their labcoats have it

I think winter coats should also be purged from uniform printer because currently we have every winter coat but not even jumpsuits for some jobs (robotics and atmos off the top of my head) so either purge coats or add more jumpsuits

**Comment by icekot8** [comment]
I think the dural thread jackets should keep their defense

**Comment by MilenVolf** [comment]
To keep the armor there are 2 ways:
1) Make negative price value (To beat some armor price adjustments, but I hate the idea of doing it) or make them extremly expensive to produce.
2) Remove some "heavy armored" winter coats from uniform printer, making them nonrenewable, for example: Cmo and paramed winter coats.

**Comment by deltanedas** [comment]
just reduce the price???

**Comment by MilenVolf** [comment]
> just reduce the price???

Armor values add price to clothes. So, to compensate this, we need to make a negative static price value for them, but I don't like this idea. So instead we can make them more expensive to produce.

**Comment by deltanedas** [comment]
99% sure you can set the price multiplier to 0 on Armor

**Comment by MilenVolf** [comment]
> 99% sure you can set the price multiplier to 0 on Armor

There's only 1 Datafield in Armor component. No price multiplier

**Comment by MilenVolf** [comment]
Found out that it calculates in Server `ArmorSystem`. I guess that multiplier should be implemented but it's out of scope of this pr.

**Comment by deltanedas** [comment]
oh i mixed up damage and armor having the multiplier
would still be good for armor multiplier to exist, for this exact usecase

**Comment by MilenVolf** [comment]
> oh i mixed up damage and armor having the multiplier would still be good for armor multiplier to exist, for this exact usecase

I'll keep armor as soon as #24561 gets merged.

**Comment by MilenVolf** [comment]
I guess it's done. Ready to merge.

**Pull request merged**
