### PR TITLE
Make all nukies humans

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Changes nukie operative spawning to make all operatives human.
if your character was a human, they'll be preserved. If they're a lizard, moth, etc, it will replace the species with human and preserve whatever else it can (usually just eye color)

## Why / Balance

Species design is diverging a lot more and with Vox on the horizon, the variance in difficulty and mechanics from species to species is only widening. Not being able to guarantee basic things about operatives like damage resistances, diet, air type, etc. makes balance incredibly difficult as certain items that may be bad for one species are overpowered for another. Furthermore, it requires an endless mill of continual updates and safeguards to the mode for every species change, lest a balance tweak meant to affect regular station roles and gameplay spirals into the team balance and dynamics of Ops.

The easiest way to solve this is just standardizing nukies to just humans. This removes a lot of the potential negative variance in balance and gives people an even playing field for balance.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: All nuclear operatives are now humans.

### CODE REVIEW

**Comment by Moomoobeef** [comment]
I fear a Kerfuffle™ when discord general gets wind of this, but I definitely think it's a good idea balance-wise so :P

**Comment by Plykiya** [comment]
Does the nukie base have a magic mirror so people can change how they look if they're... force humaned?

**Comment by Cojoke-dot** [comment]
Why not just remove the racial traits instead?

**Comment by CoyoteTheClever** [comment]
I feel like its a really bad idea. There is a tendency to overbalance everything and sand away all the interesting edges around the game, and this is kind of a good example of this. Beyond that though, it also makes nukies seem like they are an inherently speciesist organization. Speciesism is against the rules, but also, who wants to play as a member of some species supremacist organization?

**Comment by Hrosts** [comment]
> certain items that may be bad for one species are overpowered for another

Is there a prominent case of this that can be pointed out or is it mostly hypothetical?

**Comment by whateverusername0** [comment]
next PR please change security and the chain of command to be human only. don't want them to die out because of the species differences :trollface:

**Comment by Dutch-VanDerLinde** [comment]
> Why not just remove the racial traits for nukies instead?

slimes magically gaining the ability to breathe oxygen when they join the terrorism group

**Comment by NeKognitoHazard** [comment]
The primary source of fun in SS14 is the unpredictability of the game meaning that no two rounds are the same. This unpredictability is caused by many things and is inevitable due to the nature of it practically being a sandbox world often with 50+ players. One of the most basic influences on this is player races and the quirks each race has.

Removing the ability for players to play as their preferred race for the very thin excuse of "balance" is incredibly lame. Using slimes as an example, they take reduced blunt but increased piercing damage, which makes them more vulnerable to ballistic guns than any other race. It is that player's choice to have picked a slime, and to have enabled nukies as one of their antags. Should security players be forced to play as humans too? An argument could be made a slime secoff is at an even bigger disadvantage as all the syndicate's guns are ballistic, whereas sec at least has laser rifles, so there's a chance the slime's damage modifiers wouldn't even come into play.

This seems like a "balance" issue that barely exists, and nobody asked to be changed.

**Comment by Cojoke-dot** [comment]
> slimes magically gaining the ability to breathe oxygen when they join the terrorist group

Advanced Nukie genetic alterations? I mean, sci-fi magic

**Comment by thebadman4662** [comment]
Innit bit racialist of Syndicate to ban other races from joining their ranks?

**Comment by Piras314** [comment]
Species are different in combat and mechanics... and this is a good thing. Removing this from nukies is removing some of the most interesting diversity and variety in appearance, mechanics and balance in the game when there isn't really currently a problem. It also removes practically all character customisation turning you into an urist.

If some people really have a problem with this, the solution is to able to change to a different character for a certain antag (e.g. having a character just for nukies, or a character that you don't want to be antag without having to turn antags off). This may be hard to code, but if people really cared about this they'd implement it.

If this is really what people want, it should at least only apply to certain species like Dionae, and not to Lizards, Moths, Humans, Dwarves, etc. who are quite well suited for combat.

**Comment by Emisse** [comment]
I agree but I think vox nukie funney

**Comment by Cojoke-dot** [comment]
It was that player's choice to turn nukies on... if they don't like how weak their species is in combat then don't have a combat antag on...

**Comment by Hrosts** [comment]
> the solution is to able to change to a different character for a certain antag

This will only lead to a lot of people picking "meta" species for that, which would kinda prove Emo's point. Now if you want to do that you have to commit to a certain specie for many many rounds, hoping to roll a nukie, which balances it out really.

**Comment by Cojoke-dot** [comment]
> This will only lead to a lot of people picking "meta" species 

Thoes are not the players who would play Vox, if they are playing a "meta" species they are going to be playing a "meta" species anyways in shift (IE: any other antag).

**Comment by Piras314** [comment]
> > the solution is to able to change to a different character for a certain antag
> 
> This will only lead to a lot of people picking "meta" species for that, which would kinda prove Emo's point. Now if you want to do that you have to commit to a certain specie for many many rounds, hoping to roll a nukie, which balances it out really.

This "prove's Emo's point" in that it presents an alternate solution that won't make people mad because it **actually gives people a choice of species**. The point of contention here isn't that humans or lizards are the best combat species and that people might prefer playing them as nuclear operatives, but that this removes any choice of species and I mean, also of simple character customisation, whereas the solution of a different character for nukie antag rolls solves both of those issues and addresses the initial reason for this PR.

**Comment by slarticodefast** [comment]
Playing vox will certainly be a handicap, just like negative traits are. But it is the player's choice if they want to face that challenge since they can just disable nukies for their vox character. Balancing species for combat is a general problem, not one that only affects nukies. Restricting nukies to humans will just remove a lot of fun and variety from that gamemode.

**Comment by ninruB** [comment]
> they can just disable nukies for their vox character.

Not entirely correct as this excludes them from nukie rolls in general while they're playing the vox character.
If Urist wants to play non-vox nukie, but also wants to play vox crew in case they don't get nukie, they can't do that because they outright disable nukie from the vox character.

**Comment by Dutch-VanDerLinde** [comment]
> Playing vox will certainly be a handicap, just like negative traits are. But it is the player's choice if they want to face that challenge since they can just disable nukies for their vox character. Balancing species for combat is a general problem, not one that only affects nukies. Restricting nukies to humans will just remove a lot of fun and variety from that gamemode.

yeah but negative traits are removed when you roll nukie

**Comment by bruhmogus** [comment]
can we please not make the syndicate racist?
also this removes the entire reason for choosing a race, upsides and downsides

**Comment by deltanedas** [comment]
i think codewise its a good thing to have just have the 1 yaml line separate

**Comment by Errant-4** [comment]
It would not address the "reduction of player agency" concerns, but would remove the apparent species supremacy aspect if rather than humans, nukies were (only visually) terminator endoskeletons. Sending killer robots for a possibly-suicide mission makes sense anyway

**Comment by Thurtik** [comment]
I don't entirely disagree but I think stripping the ability to play your character from people is kinda eh.., also the species don't have _that_ big of an impact on combat (yet) to warrant this (maybe except dionas but those are **weaker** than the average, not **stronger**)

**Comment by Brandon-Huu** [comment]
So are you also gonna remove DNA scrambler and destroy all hope for stealth ops?

**Comment by Djungelskog2** [comment]
If people are having issues by playing characters they don't want to as nukie, it's an opt-in anyways. if they want to play a certain race but not as a nukie don't enable nukies for that character. If people want the most "meta picks" race-wise they might as well have their entire character roster be lizards or humans, no reason the same logic shouldn't apply to crew/sec sided things.

**Comment by GNF54** [comment]
cybersun is now canonically speciesist

**Comment by metalgearsloth** [comment]
I'm fine with this for now. We bikeshedded a bit back when loadouts were implemented and came to the conclusion that job + antag priorities should be selected before character which would make this a lot more palatable to being turned off.

**Comment by PolarTundra** [comment]
I agree with others that this is a sour change that isn't necessary to prioritise balance over roleplay, alongside the other mentioned points about Cybersun now appearing speciesist.  I don't think this change improves the game, it just takes away from variety and expression through character creation and it'd be easier to address specific balance niches for this rather than just drop a blanket ban on any non-human character being a nukie.

**Comment by Gtheglorious** [comment]
I was about to write a huge thing about how this makes no sense and how you could just turn off nukie on species that would it be bad on, but then I actually critically read the PR and yeah this makes sense.

**Comment by PaulRuddsAssFuzz** [comment]
I understand that the widening availability of conventionally unaccommodated for spessraces can cause issues when playing the inherently self-reliant role of Nukie-
But that said, just limit to "entities that breathe oxygen" in a list?

While people should undeniably treat being a nukie as a canned backstory, one-off character as far as RP is concerned, it's still worth trying to mitigate the fact that stopping people from playing races they're _mechanically_ accustomed to would annoy them.

Also, does removing race limitations of Nukies not disproportionally advantage them even more over the crew, as people with said limitations can still play Security + Salvage?

**Comment by Doritodude77** [comment]
I understand that the widening availability of conventionally unaccommodated for spessraces can cause issues when playing the inherently self-reliant role of Nukie-
But that said, just limit to "entities that breathe oxygen" in a list?

While people should undeniably treat being a nukie as a canned backstory, one-off character as far as RP is concerned, it's still worth trying to mitigate the fact that stopping people from playing races they're mechanically accustomed to would annoy them.

Also, does removing race limitations of Nukies not disproportionally advantage them even more over the crew, as people with said limitations can still play Security + Salvage?

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I dislike this PR, as tundra has said this activity harms RP aspects of the game for balance. Personally I feel we should be trying to balance the game less, especially if the kind of changes are going to be as extreme as this one.

**Comment by PolarTundra** [comment]
> I dislike this PR, as tundra has said this activity harms RP aspects of the game for balance. Personally I feel we should be trying to balance the game less, especially if the kind of changes are going to be as extreme as this one.

Not to mention it feels like a slope where using this argument, certain species would be excluded from other antagonists like revs or positions like command/security... it has very bad implications for the game's future imo.

**Comment by Hrosts** [comment]
> This "prove's Emo's point" in that it presents an alternate solution that won't make people mad because it actually gives people a choice of species. The point of contention here isn't that humans or lizards are the best combat species and that people might prefer playing them as nuclear operatives, but that this removes any choice of species and I mean, also of simple character customisation, whereas the solution of a different character for nukie antag rolls solves both of those issues and addresses the initial reason for this PR.

It will prove Emo's point by making any balance difference between species much more prominent, as there will be a larger pressure on players to pick combat-proficient species. There will be little reason to pick anyone but lizards and humans, really, or whoever becomes the next meta darling. 
It might also become a cause for toxicity, where people picking slimes and dionas for nukies will be accosted by other players for making an "objectively bad" choice. 
It will also not solve any issues with the need for tweaks or balance patches, potentially making them harder to do, as every balance tweak will cause a wave of specie adjustments from nukie players.

The current option of keeping the specie of general game character is much more preferable, but the nukie humanization has been merged anyway, so it doesn't seem like there's much point to this discussion.

**Comment by Golinth** [comment]
Syndicates are now canonically racist, will keep this in mind for future RP!

But seriously, why was this merged, especially speed merged? Why is the perfect balance required in a game that is so far from feature complete, its not even worth considering, ESPECIALLY at the cost as something as fundamental as keeping your own character? Nukies are genuinely my favorite mode to play as, and they will be kept off until I can play as my character, as I designed them.

**Comment by ZombieChibiXD** [comment]
Not to be that guy but doesn't this PR make the syndicate some kind of... y.. know... Server Rule 1.3 point 3

**Pull request merged**
