### PR TITLE
Buff potassium availability from bananas

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Buffed the amount of potassium obtained by centrifuging banana juice and added banana juice to mimanas since mimanas are technically a variety of banana. 1u of potassium per 10u of banana juice is way too little for recipes that require a lot.

### CODE REVIEW

**Comment by GreyMario** [comment]
I'll say it again--I don't like the idea of contaminating juice outputs; I shouldn't have to run to Chems as a Bartender unless I require a specialty ingredient, and the juice of a common Botany crop shouldn't be a "specialty ingredient".

And making elemental potassium this easy to obtain is a recipe for disaster. We're talking "shitters will start taking Botanist or Service Worker to create potassiumbombs".

The best way to get elemental potassium from a banana without doing the enemy gamer's job for them is to find a way to make potassium extractable by refining banana juice in some fashion.

**Comment by CrigCrag** [comment]
agreed, i think centrifuging banana juice would be a good method of obtaining it

**Comment by UbaserB** [comment]
I will switch that out then to centrifuging recipe.

**Comment by mirrorcult** [comment]
yeah centrifuging banana juice is better imo

**Comment by UbaserB** [comment]
Ok fixed, turns out it was already a reaction but like barely gave anything so i buffed it a little.

**Pull request merged**
