### PR TITLE
Access denied sound

### PR DESCRIPTION
**Pull request by Decortex**
## About the PR

Changed airlock deny sound
## Why / Balance

Make it more sci fi
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Changed airlock deny sound

https://github.com/space-wizards/space-station-14/assets/122426300/8f9cb40e-3ade-4548-9286-60e5dd078e5a

### CODE REVIEW

**Comment by K-Dynamic** [comment]
> This is going is going to make the deny spam sound incredibly annoying.

Who wouldn't want a british door repeatedly saying 'access denied' as the tider tries to enter chem to make meth :trollface:

**Comment by Decortex** [comment]
> This is going is going to make the deny spam sound incredibly annoying.

this is already annoying.
Lets make it more annoying!!!

**Comment by EmoGarbage404** [comment]
>this is already annoying.
Lets make it more annoying!!! 

No thanks

**Comment by Decortex** [comment]
> > this is already annoying.
> > Lets make it more annoying!!!
> 
> No thanks

I can make it way quiter

**Pull request closed without merging**
