### PR TITLE
Draft for the Station AI (WIP/ not ready for merge)

### PR DESCRIPTION
**Pull request by Baptr0b0t**
## About the PR

Add the AI interface, a slot where it possible to put a borg brain, to offer different ability for control the station
## Why / Balance

An expected feature
## Technical details

WIP
## Media

Need a sprite for the AI machine
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Kadeo64** [comment]
IT'S HAPPENING 

>Need a sprite for the AI machine

use [tg's ai sprite](https://tgstation13.org/wiki/images/e/ea/AI.gif) as a placeholder

**Comment by metalgearsloth** [comment]
This requires a design doc.

**Comment by Kadeo64** [comment]
also iirc AI needs camera code refactor

it also probably needs a design doc but it's a ss13 feature and we already have AI core mapped so i assume a mostly 1 to 1 port of the basic AI systems (camera watching, door controls) will be accepted without document

**Comment by Baptr0b0t** [comment]
I also need to discuss how we do it, currently it's like a borg brain slot. Should it be a role in its own right?

**Comment by metalgearsloth** [comment]
> also iirc AI needs camera code refactor
> 
> it also probably needs a design doc but it's a ss13 feature and we already have AI core mapped so i assume a mostly 1 to 1 port of the basic AI systems (camera watching, door controls) will be accepted without document

It won't.

**Comment by Baptr0b0t** [comment]
> > also iirc AI needs camera code refactor
> > it also probably needs a design doc but it's a ss13 feature and we already have AI core mapped so i assume a mostly 1 to 1 port of the basic AI systems (camera watching, door controls) will be accepted without document
> 
> It won't.

I will construct a document if needed, but i don't really know what you want i put it in ?

**Comment by Kadeo64** [comment]
> It won't.

i guess the lesson was learned after revs huh

**Comment by Flareguy** [comment]
> IT'S HAPPENING HOLY SHIT
> 
> > Need a sprite for the AI machine
> 
> use [tg's ai sprite](https://tgstation13.org/wiki/images/e/ea/AI.gif) as a placeholder

The /tg/ AI sprite should be fine to use as a permanent thing. You *could* change it if you want, but it's a pretty good sprite IMO so I don't really think it's nessecarry.

**Comment by Baptr0b0t** [comment]
> > IT'S HAPPENING HOLY SHIT
> > > Need a sprite for the AI machine
> > 
> > 
> > use [tg's ai sprite](https://tgstation13.org/wiki/images/e/ea/AI.gif) as a placeholder
> 
> The /tg/ AI sprite should be fine to use as a permanent thing. You _could_ make a new one if you want, but it's a pretty good sprite IMO so I don't really think it's nessecarry.

For now im using the anomaly container, but i will check for other sprite later

**Comment by Kadeo64** [comment]
> The /tg/ AI sprite should be fine to use as a permanent thing. You _could_ make a new one if you want, but it's a pretty good sprite IMO so I don't really think it's nessecarry.

I feel like it's too flat, i'm more of a fan of the goon AI design but goon artstyle isn't exactly the same as ours. I'll see about making a custom sprite sometime later.

**Comment by Nimfar11** [comment]
A document has already been written at the AI station. You can develop on it, well, or write your own.

**Comment by Baptr0b0t** [comment]
> A document has already been written at the AI station. You can develop on it, well, or write your own.

Seem a good framework, where i can find it ? on ss13 ?

**Comment by Nimfar11** [comment]
> Seem a good framework, where i can find it ? on ss13 ?

It's relatively recently written and not yet approved. But as a possible option...
https://github.com/space-wizards/docs/pull/160

**Comment by Kadeo64** [comment]
Additionally, the lawset actively allows the AI to validhunt anyone who might pose a structural risk to the station. If someone is suspected of being a traitor the AI is perfectly able of having them killed via borgs because "They could buy c4 at any time! they're totally a traitor guys trust me!"

**Comment by PolterTzi** [comment]
> > > also iirc AI needs camera code refactor
> > > it also probably needs a design doc but it's a ss13 feature and we already have AI core mapped so i assume a mostly 1 to 1 port of the basic AI systems (camera watching, door controls) will be accepted without document
> > 
> > 
> > It won't.
> 
> I will construct a document if needed, but i don't really know what you want i put it in ?

_I think_ you should put the document as a feature proposal PR to the docs repository.
https://github.com/space-wizards/docs

**Comment by UbaserB** [comment]
> This requires a design doc.

isnt there already an AI design doc made

**Comment by tutoumi** [comment]
robotic's computer, now ai, i chose the good timing to return to roboticist main

**Comment by VasilisThePikachu** [comment]
> > This requires a design doc.
> 
> isnt there already an AI design doc made

https://github.com/space-wizards/docs/pull/160

there's this

**Comment by mirrorcult** [comment]
this should not be worked on upstream until there's an actual agreed upon design merged for it in the docs repo

**Comment by Baptr0b0t** [comment]
https://github.com/space-wizards/docs/pull/162

**Comment by Clostyandr** [comment]
> This requires a design doc.

Awwww, he just adding an interface, or he can't do this too without docs?

**Comment by ImRenQ** [comment]
sadly

**Pull request closed without merging**
