### PR TITLE
[BUGFIX] "Ghost" in the lobby lets you see the whole chat

### PR DESCRIPTION
**Pull request by Schrodinger71**
## About the PR
When you type "ghost" while being in the lobby, it lets you see the whole chat, like you're an observer. It doesn't make you a ghost, though. Your chat simply modifies.
What this PR does is checks whether the player is in lobby or not.
If he's in lobby - it will show an error that says that you can't use that in the lobby.

## Why / Balance
To simply fix the bug and prevent players from metainfo, maybe

## Technical details
What this PR does is checks whether the player is in lobby or not.
If he's in lobby - it will show an error that says that you can't use that in the lobby.

## Media
Before the fix:
image
After the fix:
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
I don't think the changes might be called "breaking"

**Changelog**
:cl: Schrodinger71
- fix: Fixed a bug letting players type "ghost" in the console and then see the whole chat while being in the lobby.

### CODE REVIEW

**Comment by Schrodinger71** [comment]
Huh

**Review by SaphireLattice — APPROVED** [review]
Looks alright. A bit unsure about the `_entities.System` usage here but it's already doing that for mind system...

**Comment by Everturning** [comment]
We can't observe them so until then they are both the best and not the best

**Comment by SaphireLattice** [comment]
Ah so it does need to be done through dependencies. Yeah gonna ask for that part to change then o/

Thanks @lzk228

**Comment by lzk228** [comment]
so, despite what sloth said this pr got merged wtf :trollface:

**Comment by Schrodinger71** [comment]
image
image

@SaphireLattice Yaahh

**Comment by TheShuEd** [comment]
Uh im sorry

**Comment by SaphireLattice** [comment]
Wouldn't call this small. Yeah that's a fail and I shouldn't have approved without testing this fully, as I've only looked at code.

**Comment by Schrodinger71** [comment]
But the way it's merged now, it works stably and everything is fine.

**Comment by JamiMyst** [comment]
the localized text doesn't work correctly, despite being there in folder

image

**Pull request merged**
