### PR TITLE
Adds Skub

### PR DESCRIPTION
**Pull request by SweptWasTaken**
All hail Skub. 

_I swear i'll make a serious PR soon._

- added Skub
- added Skub sound effect
- added Skub crafting recipe

### CODE REVIEW

**Comment by GlassEclipse** [comment]
fucking worthless shitbag scum fucker

**Comment by RemieRichards** [comment]
I knew this would happen, I didn't expect so soon.

**Comment by SweptWasTaken** [comment]
Believe it baby

**Comment by optimumtact** [comment]
pro skub

**Comment by PKPenguin321** [comment]
>skub.ogg

Huh. Skub.

**Comment by unusualcrow** [comment]
give me skub or give me death

**Pull request merged**
