### PR TITLE
Revert "Adds the thermo-electric generator (#18840)"

### PR DESCRIPTION
**Pull request by metalgearsloth**
This reverts commit a242af506ec752e575bc14ac116ecb8af5855cfe.

Funny playtest aside this is getting reverted until https://github.com/space-wizards/space-station-14/issues/19037 is done.

:cl:
- remove: Removed TEG temporarily.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
will conflict with #19036

**Comment by Just-a-Unity-Dev** [comment]
also ????
image

**Comment by metalgearsloth** [comment]
> also ???? image

all the datafields need updating to be camelCase so this may cause issues with maps anyway

**Comment by Emisse** [comment]
ill hold off mapping TEG for now until we figure out whats going on

**Comment by metalgearsloth** [comment]
I'm just going to spend the next couple hours reviewing and putting a PR up so will see how that goes

**Comment by metalgearsloth** [comment]
Ran out of time for this so will see tomorrow, but otherwise do not map.

**Pull request closed without merging**
