### PR TITLE
Wearable bee plush

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Bees are cute! Tom Cruize suggested that i added a bee hat, so i made the bee plush wearable.... so snuggly.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- add: The bee plush can now be worn on your head.

### CODE REVIEW

**Comment by lzk228** [comment]
it looks like a spider

**Comment by UbaserB** [comment]
> it looks like a spider

shut up its a bee

**Comment by deltanedas** [comment]
do bees have legs

**Comment by UbaserB** [comment]
> do bees have legs

YES THEY DO

**Comment by deltanedas** [comment]
:spider:

**Comment by TexCruize** [comment]
Bee's go buzz buzz and are made of bees

**Comment by JoeHammad1844** [comment]
goonstation reference

**Comment by drteaspoon420** [comment]
it looks like fat oblong spider with two leggs missing

**Comment by UbaserB** [comment]
> it looks like fat oblong spider with two leggs missing

ill make the legs lower

**Comment by Partmedia** [comment]
Please discuss with a sprite maintainer on how this sprite can be improved.

**Comment by UbaserB** [comment]
Its an issue with the sprite, i kind of forgot to draft it. Emisse recommended i just make the bee plush wearable on the head instead, and thats what im going to do.

**Comment by UbaserB** [comment]
lets GOOO

**Comment by UbaserB** [comment]
hold up let me fix the linter error

**Review by LankLTE — APPROVED** [review]
Yeah sure

**Pull request merged**
