### PR TITLE
Corrects aghost's hand placement

### PR DESCRIPTION
**Pull request by Verslebas**
## About the PR

I rearranged Agosta's hands so they'd show up like everyone else's.
## Why / Balance

Why not
## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Verslebas
- tweak: Changed admin ghost's hands order

### CODE REVIEW

**Review by PrPleGoo — APPROVED** [review]

**Comment by PrPleGoo** [comment]
Can you fill out the description of the PR?
Add the before/after screenshots you posted in discord.
And add a CL entry that you fixed the hands being wrong on aghosts.

**Comment by Verslebas** [comment]
> Can you fill out the description of the PR? Add the before/after screenshots you posted in discord. And add a CL entry that you fixed the hands being wrong on aghosts.

cl was created for the players

**Comment by Verslebas** [comment]
> Can you fill out the description of the PR? Add the before/after screenshots you posted in discord. And add a CL entry that you fixed the hands being wrong on aghosts.

about screenchots
i only have with my ui teehe :3

**Comment by PrPleGoo** [comment]
> about screenchots i only have with my ui teehe :3

That's fine

**Comment by ficcialfaint** [comment]
agree with PrPleGoo's comments

**Comment by Verslebas** [comment]
this?

**Comment by LankLTE** [comment]
Does this need a changelog? It’s not player facing

**Comment by Verslebas** [comment]
> Does this need a changelog? It’s not player facing

Yeah, that's why I didn't write it.

**Comment by ficcialfaint** [comment]
> It’s not player facing

why? it's something a regular player **can notice** while just playing. just a minor bug fix, won't be bad to include in the changelog. it's not like "we just changed the YAML order in prototype, you won't see any differences in-game"

**Comment by Verslebas** [comment]
> > It’s not player facing
> 
> why? it's something a regular player **can notice** while just playing. just a minor bug fix, won't be bad to include in the changelog. it's not like "we just changed the YAML order in prototype, you won't see any differences in-game"

alright

**Comment by PrPleGoo** [comment]
Yeah, looks good!

**Comment by ficcialfaint** [comment]
not really, try avoiding using acronyms in changelogs, use `admin ghost` instead in our case

**Review by ficcialfaint — APPROVED** [review]

**Pull request merged**
