### PR TITLE
Jetpack buff

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

~~Standard jetpacks can now go in suit storage, while smaller jetpacks like the mini variant can now go in the belt slot.~~ If you need a way to visualise how that would work realistically, remember that mini jetpacks are not only small but you're going to be in space where there is no gravity. In the future, perhaps jetpacks can weigh more.

_Only cap and CE's along with the mini jetpack is buffed._

## Why / Balance

Because there was no viable location to place the jetpack in normal circumstances, people would hold it in their hand. As a solution to that, I'm simply giving more options for players along with easier accessibility. Like, who would throw away their bag as a syndicate just to wear a jetpack?

**Changelog**

:cl: Ubaser
- tweak: Some jetpacks can be now worn in more slots.

### CODE REVIEW

**Comment by Emisse** [comment]
uhhhhhhhhhhuuuuuuuhhhuuuuuuuuuu im thinking maybe but miught need discussion

**Comment by KittenColony** [comment]
if it worked in zero gravity -on station- then it would be amazing

**Comment by metalgearsloth** [comment]
> if it worked in zero gravity -on station- then it would be amazing

That's why it doesn't work on station (tl;dr nukies get a huge advantage and playing 0-grav permanently sucks).

**Comment by Ilya246** [comment]
this will return the reason mini-jetpacks were so good, if you can put large jetpacks in suit storage, you no longer need an oxygen tank as you can just breathe out of the jet
you can just wear it as an oxygen tank with no downside

**Comment by UbaserB** [comment]
> this will return the reason mini-jetpacks were so good, if you can put large jetpacks in suit storage, you no longer need an oxygen tank as you can just breathe out of the jet you can just wear it as an oxygen tank with no downside however, a change i would suggest is making syndicate jetpacks give you extra speed

i tweaked it already based on what emisse told me to do

**Comment by LankLTE** [comment]
I feel like the only relevant change here is cap’s going on suit storage now, which is kind of unnecessary since it’s already the fastest (iirc) and the CE’s is supposed to be unique in that it can go on backs (while having a reasonable storage unlike the mini one). CE’s going on belts, and to a lesser extent the mini, is basically irrelevant since everyone and especially the CE will just be wearing their toolbelt anyways. I think this could use a better “why”, as people holding the jetpack in their hand is a fine way to make it have a tradeoff imo

**Comment by UbaserB** [comment]
> I feel like the only relevant change here is cap’s going on suit storage now, which is kind of unnecessary since it’s already the fastest (iirc) and the CE’s is supposed to be unique in that it can go on backs (while having a reasonable storage unlike the mini one). CE’s going on belts, and to a lesser extent the mini, is basically irrelevant since everyone and especially the CE will just be wearing their toolbelt anyways. I think this could use a better “why”, as people holding the jetpack in their hand is a fine way to make it have a tradeoff imo

the mini jetpack had the exact same slots as CE's one previously, so i changed nothing in that regard

**Pull request merged**
