### PR TITLE
Biomass

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Opening for visibility since it touches some pretty active parts of the content codebase (lathes and cloning)

- [x] Constructable reclaimer
- [x] AfterInteractUsing insertion
- [x] Cleanup
- [x] Number balance

**Changelog**

:cl: Rane
- add: Cloners now require biomass.
- add: Cloners have a chance of failure based off of the body's genetic damage.
- add: Added biomass material and biomass reclaimers.

### CODE REVIEW

**Comment by Elijahrane** [comment]
Seems ok to me now, only part I am not happy with is it uses climbing (drag and drop really sucks and I spent hours trying to make it work)

**Comment by Elijahrane** [comment]
Also if someone wants to make a reclaimer sprite...

**Comment by Elijahrane** [comment]
DNM, I think my last thing will be adding a cvar for whether the reclaimer accepted souled bodies (MRP players can handle it but LRP players probably cannot)

**Comment by Visne** [comment]
How easy is it to run out of biomass? How hard is it to get more biomass?

>Cloners have a chance of failure based off of the body's genetic damage.

Why?

**Comment by Just-a-Unity-Dev** [comment]
> How easy is it to run out of biomass? How hard is it to get more biomass?
> 

Clone people, instead of putting them in the morgue just use their dead body in exchange for biomass.


> Why?

Genetic damage would ruin the 1:1 replica since, genetic damage, therefore the chances of it failing

**Comment by Visne** [comment]
> Genetic damage would ruin the 1:1 replica since, genetic damage, therefore the chances of it failing

But why do we want that, from a gameplay perspective?

**Comment by Elijahrane** [comment]
> How easy is it to run out of biomass? How hard is it to get more biomass?
Starting biomass is enough to clone 5 people assuming you recycle the bodies after cloning. It's not hard to get more because you can use animals, mice, salvage mobs, etc. When I was playtesting salvage would constantly bring me unidentified humans and stuff that were an easy source.

>Why?
Isn't the entire point of genetic damage its interaction with cloning? Just remove it at that point

**Comment by Elijahrane** [comment]
> > Genetic damage would ruin the 1:1 replica since, genetic damage, therefore the chances of it failing
> 
> But why do we want that, from a gameplay perspective?

Because that's the purpose of that extremely niche damage type, and it makes cancer / decloners / rotting for a long time more threatening. It makes it so the morgue doesn't go completely unused if you are waiting on a bit more biomass. The main med machines we are missing also all interact with genetic damage

**Comment by Emisse** [comment]
keep genetic damage fail in, incentivizes people actually treating it

**Comment by Visne** [comment]
As long as the genetic damage isn't too tough, it's fine.

**Comment by Elijahrane** [comment]
alright, cvar added

**Comment by EmoGarbage404** [comment]
mfw this just silently removed cancer scanner?

**Comment by EmoGarbage404** [comment]
also why were rat king files randomly adjusted?

**Comment by Elijahrane** [comment]
> also why were rat king files randomly adjusted?

mass is relevant to biomass

**Comment by EmoGarbage404** [comment]
doesn't explain why the cancer scanner was removed. I get it might conflict with the new biomass stuff, but considering there was content removal it should have been at least included in the changelog.

**Comment by Elijahrane** [comment]
> doesn't explain why the cancer scanner was removed
because it's not usable in its current state after biomass

**Comment by EmoGarbage404** [comment]
> > doesn't explain why the cancer scanner was removed
> 
> because it's not usable in its current state after biomass

finish reading the rest of the comment
image
image
it's fine if it wasn't usable, but perhaps communicate that to players, seeing as it's a change the affects them directly.

**Comment by Elijahrane** [comment]
ok

**Pull request merged**
