### PR TITLE
More nullas as errors

### PR DESCRIPTION
**Pull request by metalgearsloth**

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
CS8625 is "Cannot convert null literal to non-nullable reference or unconstrained type parameter." for reference

**Review by PJB3005 — COMMENTED** [review]
You can actually just do `<WarningsAsErrors>nullable</WarningsAsErrors>` to get all of them. Do we want that?

**Comment by DrSmugleaf** [comment]
> You can actually just do `<WarningsAsErrors>nullable</WarningsAsErrors>` to get all of them. Do we want that?

If it saves us from the merciful github build yes

**Comment by metalgearsloth** [comment]
I thought I'd tried this and github chucked a tanty but maybe I didn't do it right so we'll give her a go.

**Pull request merged**
