### PR TITLE
add man-o-war shuttle

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

image
image
image
image

"Hello, this is me talking in a totally normal voice with absolutely no undertone or monotony. How is your day? Have you been enjoying the weather? I come from an ancient time and place which I cannot remember. Though I have found your illustrious station and generous crew, I may have difficulty communicating with you. That is terribly unfortunate."
image

## Why / Balance

current odds would place this at ~ 1:136.5 rounds of normal play.

Adds shuttle variety, Its a funny RP role. Pretty rare.
Admittedly this one is a bit *out there*.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- add: A shuttle full of travelers from a long forgotten time.

### CODE REVIEW

**Comment by UbaserB** [comment]
this is actually wild

**Comment by beck-thompson** [comment]
I love this idea and I love how uncommon it is. These things should almost never come up and be super fun when they do!

**Comment by LittleNorthStar** [comment]
Perhaps... Make them skeletons and remove the space suits?

**Comment by lanse12** [comment]
it doesn't even have side thrusters

**Comment by TheDoctor1977** [comment]
yeah this thing needs 4 directions of thrusters or it's gonna be miserable to control

**Comment by baddiePRO** [comment]
> Perhaps... Make them skeletons and remove the space suits?

Black Pearl skeleton pirates would be so awesome

**Review by TheShuEd — APPROVED** [review]

**Pull request merged**
