### PR TITLE
Added new tiles into the crafting menu

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Added a lot of new tiles into the Crafting menu 
**Screenshots**

image

**Changelog**

:cl: Seth
- add: Added new tiles into the crafting menu

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
These should really be made in a lathe.

**Comment by SethLafuente** [comment]
> These should really be made in a lathe.

I don't really get why in a decent amount of ss13 servers their made by hand why go through the trouble of putting them on the lathe?

**Comment by SweptWasTaken** [comment]
> 
> 
> > These should really be made in a lathe.
> 
> I don't really get why in a decent amount of ss13 servers their made by hand why go through the trouble of putting them on the lathe?

Because I think it's dumb that you can work a gold bar in your hands into an intricately carved golden tile.

**Comment by SethLafuente** [comment]
> > > These should really be made in a lathe.
> > 
> > 
> > I don't really get why in a decent amount of ss13 servers their made by hand why go through the trouble of putting them on the lathe?
> 
> Because I think it's dumb that you can work a gold bar in your hands into an intricately carved golden tile.

I mean you can make chairs and airlocks which require far more skill to make than a simple tile with some mediocre carving on it

**Comment by mirrorcult** [comment]
i really don't like how this bloats the crafting menu

it would really be better if there were a dedicated thing for this, like a tile fabricator or tile painter item

**Comment by SweptWasTaken** [comment]
> 
> 
> i really don't like how this bloats the crafting menu
> 
> it would really be better if there were a dedicated thing for this, like a tile fabricator or tile painter item

Or maybe just get made in a lathe which has categories.

**Comment by mirrorcult** [comment]
> 
> 
> > i really don't like how this bloats the crafting menu
> > it would really be better if there were a dedicated thing for this, like a tile fabricator or tile painter item
> 
> Or maybe just get made in a lathe which has categories. Anyway this PR won't be merged unless the recipes are moved to something else.

the crafting menu has categories too. its still bloat

**Comment by DogZeroX** [comment]
The crafting menu itself is kinda bad. In my opinion, it should show you all of icons of what you can craft, and when you click one of them it shows the materials needed without text, hovering over the material will tell you the name. Shorten the message to Materials required: "Gold icon" "Iron rod icon"

**Comment by SweptWasTaken** [comment]
> 
> 
> > > i really don't like how this bloats the crafting menu
> > > it would really be better if there were a dedicated thing for this, like a tile fabricator or tile painter item
> > 
> > 
> > Or maybe just get made in a lathe which has categories. Anyway this PR won't be merged unless the recipes are moved to something else.
> 
> the crafting menu has categories too. its still bloat

Well what do you want to do? The lathe seems a better place than any to craft tiles.

**Comment by mirrorcult** [comment]
> Well what do you want to do? The lathe seems a better place than any to craft tiles.

image

**Comment by SweptWasTaken** [comment]
> 
> 
> > Well what do you want to do? The lathe seems a better place than any to craft tiles.
> 
> image

I meant in scope of this PR. Should we close it? 

I don't think having a separate tile making machine is the solution. Just make a couple of tile recipes for inhand crafting, a couple more intricate ones in the protolathe and add as many tiles as you can to the tile-painter.

**Comment by mirrorcult** [comment]
im fine with that, these can be moved to the lathe then

**Comment by SweptWasTaken** [comment]
> 
> 
> im fine with that, these can be moved to the lathe then

Closing this then.

**Pull request closed without merging**
