### PR TITLE
survival nutribricks, lizzers can eat nutribricks, moffs can eat the leftovers

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Nutribricks now spawn in the survival kit in place of tinned meat.
Lizards can now eat nutribricks
Moths can now eat nutribrick wrappers

## Why / Balance

Every species now has something they can eat from their survival kit.

## Technical details

Added a new tag, `ReptilianFood`, which, as the name implies, is a specific tag to allow lizards to eat a specific item.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Aexxie
- tweak: Nutribricks spawn in Survival Kits in place of Tinned Meat.
- fix: Lizards can now eat Nutribricks.
- add: Moths can eat Nutribrick wrappers.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
uh, how much food value is that wrapper compared to the brick? lol

**Comment by Aexxie** [comment]
> uh, how much food value is that wrapper compared to the brick? lol

2 extra bites, since cloth is more scarce without just carrying mats around

**Comment by beck-thompson** [comment]
Love the wrapper idea!

**Comment by Aexxie** [comment]
I should add MoffPuffs that are basically cheese puffs but made of cloth

**Comment by Hanzdegloker** [comment]
I saw talk of compressed cloth that is easier to store and would be a good moff food. To be quite honest very rarely do I find food ever an issue as a moth main. BUT emergency kits should cover all species proper like and think your idea works quite well.

**Comment by Hanzdegloker** [comment]
> I should add MoffPuffs that are basically cheese puffs but made of cloth

literally, just add cotton balls lol

**Comment by Aexxie** [comment]
> > I should add MoffPuffs that are basically cheese puffs but made of cloth
> 
> literally, just add cotton balls lol

I'm thinking of just calling it MoffBalls™

**Comment by Hanzdegloker** [comment]
It also just came to me that moth balls themselves are a real thing, and I like the name moffballs :D

**Review by LankLTE — APPROVED** [review]

**Comment by Dutch-VanDerLinde** [comment]
you didnt change the engineering or security survival boxes

**Pull request merged**
