### PR TITLE
Add trading ship for future implementation

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This is a "trading ship" that in the future will appear instead of empty space at the trading outpost that the cargo shuttle FTLs to. The idea here is that as someone hops on the shuttle and arrives, they will have to manually drag the crates over to the palettes in order for it to be sold, and then when you start FTLing back; after short delay it gets sold. This aims to improve cargo gameplay by introducing a new element of interaction as it is currently a very slow department and usually ends up with them buying random stuff all the time.

### CODE REVIEW

**Comment by moonheart08** [comment]
We don't add unused content.

**Comment by UbaserB** [comment]
> We don't add unused content.

emisse approved it

**Comment by Emisse** [comment]
was sloth requested

**Comment by Emisse** [comment]
reviewed on discord

**Comment by GoodWheatley** [comment]
How does this improve cargo gameplay? You say that this helps alleviate cargo being a very slow department, but this appears to just make it even slower by adding extra busywork to the ideally streamlined task of selling things.

**Comment by UbaserB** [comment]
> How does this improve cargo gameplay? You say that this helps alleviate cargo being a very slow department, but this appears to just make it even slower by adding extra busywork to the ideally streamlined task of selling things.

When i meant slow, i meant the gameplay. Nothing to do. This gives cargo something new to do.

**Comment by GoodWheatley** [comment]
> > How does this improve cargo gameplay? You say that this helps alleviate cargo being a very slow department, but this appears to just make it even slower by adding extra busywork to the ideally streamlined task of selling things.
> 
> When i meant slow, i meant the gameplay. Nothing to do. This gives cargo something new to do.

Yes, but this doesn’t actually make playing cargo any more fun. It just makes selling stuff even more of a hassle when before it was relatively streamlined, which is necessary since cargo’s whole thing is selling things and then buying stuff with the profits.

**Comment by UbaserB** [comment]
> > > How does this improve cargo gameplay? You say that this helps alleviate cargo being a very slow department, but this appears to just make it even slower by adding extra busywork to the ideally streamlined task of selling things.
> > 
> > 
> > When i meant slow, i meant the gameplay. Nothing to do. This gives cargo something new to do.
> 
> Yes, but this doesn’t actually make playing cargo any more fun. It just makes selling stuff even more of a hassle when before it was relatively streamlined, which is necessary since cargo’s whole thing is selling things and then buying stuff with the profits.

idk as a cargo enjoyer i would enjoy going to the trading outpost as a break away from all the hassles of station.

**Comment by CatMagic1** [comment]
This is awesome, I love little roleplay things like this. It'd be even cooler if there was a ghost role human named some funny name like "Bob" or something who had to sit at the outpost waiting for people all day. Just sounds fun. They could help move the crates and just interact with cargo.

**Comment by CatMagic1** [comment]
image

**Comment by NancokPS2** [comment]
It really helps a department that is otherwise just pressing buttons on a machine and dragging crates. Also makes sense since Salvage also is about off-station duties.  
Btw, can we add a pair of oxygen lockers to the shuttle? I just feel like it is a good moment to bring that up.

**Pull request merged**
