### PR TITLE
Add direction relative to station for emergency shuttle's docking & nearby announcement

### PR DESCRIPTION
**Pull request by MilenVolf**
## About the PR
The title

Now emergency shuttle's docking announcement uses nav beacon location and direction relative to station

Addition to the #26437

### Shuttle docked:
image
### Shuttle nearby:
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
N/A

### CODE REVIEW

**Comment by lzk228** [comment]
great, now we will now that evac shuttle was docket near evac beacon!

**Comment by MilenVolf** [comment]
> great, now we will now that evac shuttle was docked near evac beacon!

It can be useful in case where evac docks not in evac zone. Beacon location will help to find it easier.

**Comment by slarticodefast** [comment]
I assume the direction is relative to the beacon? So it could be southwest of the station, but southeast of disposals. Then maybe make it something like "southwest of the station near disposals" instead. In case of a power outage with no working maps you have to know where the beacon is located, which might be hard for newer players who don't know the map. The current announcement telling you the side of the station the shuttle is on at least tells you in which direction to run based on screen orientation.

**Comment by MilenVolf** [comment]
> I assume the direction is relative to the beacon? So it could be southwest of the station, but southeast of disposals. Then maybe make it something like "southwest of the station near disposals" instead. In case of a power outage with no working maps you have to know where the beacon is located, which might be hard for newer players who don't know the map. The current announcement telling you the side of the station the shuttle is on at least tells you in which direction to run based on screen orientation.

## Shuttle docked:
image
## Shuttle nearby:
image

Will that do?

**Pull request merged**
