### PR TITLE
Added urn

### PR DESCRIPTION
**Pull request by NkoKirkto**
## About the PR

Added a Urn Item
## Why / Balance

So that chaplains have a more realistic and appropiate way to store the deceased or what ever the hell they burned(It was the Capitan O.O).
## Technical details

Added the item via yml. sprites in the Urn.rsi and modified the PietyVend to have 5 of them. Its a base storage item just large enough to store one singel pile of ash or what ever the hell you want to put in there(Gun definitely gun).
## Media

General Showcase
image
General showcase
image
Hand showcase with ash in the urn
image
Showcase that you can store other items
image
PietyVend showcase
(Showcase shows all 4 Directional sprites for the Hands)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

Added a Urn Item to Store Ashes of the deceased or what ever else you want to store. Available at the Piety Vend.

### CODE REVIEW

**Comment by JerryImMouse** [comment]
it looks too flat, maybe resprite it from different angle? e.g topdown view

**Comment by NkoKirkto** [comment]
Hm yeah im not very good at spriting is the thing. I could try.

**Comment by NkoKirkto** [comment]
> it looks too flat, maybe resprite it from different angle? e.g topdown view

The thing is 32x32 dosent let room for sprites like this(Its from Graveyard keeper.)
image

**Comment by NkoKirkto** [comment]
> > it looks too flat, maybe resprite it from different angle? e.g topdown view
> 
> The thing is 32x32 dosent let room for sprites like this(Its from Graveyard keeper.) image

Okay nvm  will give it some final touches but besides thath i think this looks mcuh better.
image

**Comment by Emisse** [comment]
good pr, art directors might want to look at it but i approve the concept

**Review by Emisse — APPROVED** [review]

**Comment by NkoKirkto** [comment]
> good pr, art directors might want to look at it but i approve the concept

You Mean Emo Garbarge or?

**Comment by Aexxie** [comment]
> Added a Urn Item to Store Ashes of the deceased or what ever else you want to store. Available at the Piety Vend.

if youre adding this you should totally be able to eat ashes too. please. (love it.)

**Comment by Hmeister-fake** [comment]
Very cool, but that's a coder sprite if I've even seen one.

**Comment by Hmeister-fake** [comment]
> Very cool, but that's a coder sprite if I've even seen one.

It would be cool if it was more curvy and maybe had some golden highlights around the cap? Maybe also add a stylistic handle to the top of the urn

**Comment by Emisse** [comment]
your path in the proto is lowercase for urn.rsi but the actual file is Urn.rsi

**Comment by NkoKirkto** [comment]
> your path in the proto is lowercase for urn.rsi but the actual file is Urn.rsi

Works in the Game but yeah will fix it only have to reset my LAptop this weekend so I will only be done Saturday German Time

**Comment by NkoKirkto** [comment]
> your path in the proto is lowercase for urn.rsi but the actual file is Urn.rsi

Issue is that git dosent recognize Uper/Lowercase changes to fiel names. So i hope changing one Pixel of the Icon.png changed it.

**Comment by NkoKirkto** [comment]
Just renamed it now so it is consistent

**Pull request merged**
