### PR TITLE
Fixes hallelujah.ogg

### LINKED ISSUE #22641: Holy Hand Grenade crashing the game upon using
## Description
Holy hand grenade crashes everyone's game around it upon using

**Reproduction**
Get a Holy Hand Grenade and use it, your game will crash, everyone around you will crash too

(Might be related to the sound it makes when you use it?)

### PR DESCRIPTION
**Pull request by Mirino97**
## About the PR
Fix #22641
We are currently dealing with what seems to be an Nvorbis issue where some .ogg files are somehow broken, freezing the client when trying to stream it. Weird, since it can be opened normally from explorer.
Somehow replacing the .ogg file with a new one fixes the problem.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by deltanedas** [comment]
ogg opus undefeated champion
- smaller filesize
- presumably no error if supported

**Comment by Mirino97** [comment]
Your words elude me, mister

**Comment by VasilisThePikachu** [comment]
> ogg opus undefeated champion
> 
>     * smaller filesize
> 
>     * presumably no error if supported

I actually looked into this. Opus did not have that big of a filesize difference (unless my mass vorbis to opus ffmpeg script sucked ass. It made some files smaller and others bigger). And I'm unsure about the error claim

**Comment by VigersRay** [comment]
I encountered the same problem, causing the server to lie on its side for more than 6 hours. And I personally spent 3 hours looking for what the problem was, rolling back each of my commits.

**Pull request merged**
