### PR TITLE
add ninja borg laws

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
low chance in ion storm lawsets

in tg its just copypaste of asimov but Spider Clan member, dont like that so i made new laws from scratch with some key implications:
- ninja can order you to kill it epic style
- ninja can order you to do something dishonourable like killing civilians or something
- death is preferable to ~~communism~~ mmi removal

## Why / Balance
:ninja: :robot: 

## Technical details
:ninja: :robot: 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
:ninja: :robot: 

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by GoodWheatley** [comment]
This should also be an interaction with the ninja gloves instead of being tied to an entirely different event

**Comment by deltanedas** [comment]
pro still waiting on syndiborgs

**Comment by GoodWheatley** [comment]
> pro still waiting on syndiborgs

Code them :trollface:

**Comment by deltanedas** [comment]
theres a dead(?) pr already so this until done

**Pull request merged**
