### PR TITLE
Resprite Electric-Grill

### PR DESCRIPTION
**Pull request by ps3moira**
## About the PR

Resprited electric grill
## Why / Balance

The current electric grill looks more like a electric stove-top than a electric grill, that is why I resprited it.
## Media

Here are examples of what the resprited electric grill looks like on it's different settings.

Screenshot 2023-11-06 222116
Screenshot 2023-11-06 222108
Screenshot 2023-11-06 222056
Screenshot 2023-11-06 222240
Screenshot 2023-11-06 222123

icon
low
medium
high

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Changed electric grill sprites

### CODE REVIEW

**Comment by lzk228** [comment]
i like it

**Comment by deltanedas** [comment]
`git checkout <upstream remote>/master RobustToolbox` and commit :trollface:

**Comment by ps3moira** [comment]
> `git checkout <upstream remote>/master RobustToolbox` and commit :trollface:

Doesn't seem to work 
image

**Comment by deltanedas** [comment]
bruh replace <upstream remote> with the name of space-wizards/space-station-14 remote :trollface:

**Comment by ps3moira** [comment]
> bruh replace with the name of space-wizards/space-station-14 remote :trollface:
image

**Comment by deltanedas** [comment]
:skull:

replace the part in brackets with the name of your upstream remote

for me its named upstream so `git checkout upstream/master RobustToolbox`

**Comment by ps3moira** [comment]
> 💀
> 
> replace the part in brackets with the name of your upstream remote
> 
> for me its named upstream so `git checkout upstream/master RobustToolbox`

Nothing works grahhh

**Comment by deltanedas** [comment]
:skull:

**Comment by ps3moira** [comment]
> 💀

it's pissing me off I just wanted to do a simple resprite 😭. I'll close and redo the PR

**Comment by deltanedas** [comment]
you dont need to close just force push, theres no reviews to troll

**Comment by ps3moira** [comment]
> you dont need to close just force push, theres no reviews to troll

https://github.com/space-wizards/space-station-14/pull/21524 Here's the redone PR without the messed up submodule 💀

**Pull request closed without merging**
