### PR TITLE
Deleting the old laser gun and replacing it with the COG

### PR DESCRIPTION
**Pull request by TaralGit**
Deleted the old lasergun and had it replaced with the COG laser carbine on packedstation. Also reduced ammo capacity for the Svalinn pistol (from 18 to 15) and the COG (from 36 to 30).

:cl:
- remove: Deleted the old laser gun.
- tweak: Replaced laser guns on packedstation with COG laser carbines.
- tweak: Reduced ammo capacity for the Svalinn and the COG.

laser_COG

### CODE REVIEW

**Comment by metalgearsloth** [comment]
the word before the colon is just used for the image so you need to make it a complete sentence on its own i.e. "laser gun" is just gonna be what shows up.

**Comment by TaralGit** [comment]
> the word before the colon is just used for the image so you need to make it a complete sentence on its own i.e. "laser gun" is just gonna be what shows up.

Done.

**Comment by Zumorica** [comment]
Conflicts

**Comment by TaralGit** [comment]
> Conflicts

Conflicts solved

**Review by ElectroJr — APPROVED** [review]
> > the word before the colon is just used for the image so you need to make it a complete sentence on its own i.e. "laser gun" is just gonna be what shows up.
> 
> Done.

The add entry still just says "add: laser carbine in packedstation", which will just show up in the changelog as "laser carbine in packedstation". You can probably just combine the `add` & `remove` entries into something like:

```
tweak: Replaced laser guns on packedstation with COG laser carbines.
```

Otherwise looks fine to me.

**Comment by TaralGit** [comment]
> > > the word before the colon is just used for the image so you need to make it a complete sentence on its own i.e. "laser gun" is just gonna be what shows up.
> > 
> > 
> > Done.
> 
> The add entry still just says "add: laser carbine in packedstation", which will just show up in the changelog as "laser carbine in packedstation". You can probably just combine the `add` & `remove` entries into something like:
> 
> ```
> tweak: Replaced laser guns on packedstation with COG laser carbines.
> ```
> 
> Otherwise looks fine to me.

yeah, good suggestion. edited changelog.

**Pull request merged**
