### PR TITLE
smoke grenades

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
revival of #16942 but better implementation

- tear gas not tear acid :trollface:
- tear gas grenade not tear smoke grenade
- better sprites
- tear gas 20u messages are now at 15u

depends on #20831 for tear gas to work

## Why / Balance
- smoke grenades provide very good cover for sus activites
- tear gas makes people scream involuntarily in a riot and potentially blinds them

## Technical details
added `SmokeOnTrigger` component/system which have cleaned up version of smoke reaction code
intentionally doesnt play a sound since SoundOnTrigger exists and is used

## Media
tear gas grenade on an assault belt

tear gas in guidebook

smoke grenade in uplink

smoke grenade big boy

tear gas gaming

https://github.com/space-wizards/space-station-14/assets/39013340/26e11abd-a83c-4e84-8fb7-63fd9cfa0538

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Added smoke grenades to the syndicate uplink for 1 TC, they create a large smoke cloud to provide cover for your heinous activites.
- add: Added tear gas grenades to the SecTech and security belts, use them to control riots.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
saxitoxin :trollface:

**Comment by JoeHammad1844** [comment]
security should probably also have access to smoke grenades

**Comment by JoeHammad1844** [comment]
tear gas belt overlay doesnt look like the icon

**Comment by JoeHammad1844** [comment]
gas masks should block tear gas

**Comment by mirrorcult** [comment]
not sure i understand why smokeontrigger has to exist instead of smoke nades just being chemical payload grenades

**Comment by JoeHammad1844** [comment]
crowbar twice and you can get the juicy insides

**Comment by JoeHammad1844** [comment]
> not sure i understand why smokeontrigger has to exist instead of smoke nades just being chemical payload grenades

it would probably be harder to tweak the cloud size if using chemicals

**Comment by deltanedas** [comment]
> not sure i understand why smokeontrigger has to exist instead of smoke nades just being chemical payload grenades

see the old pr, was impractical to tweak it

**Comment by deltanedas** [comment]
> gas masks should block tear gas

gas masks should filter air and block smoke but yeah

**Comment by JoeHammad1844** [comment]
smoke inhalation fixed so teargas should work now

**Comment by deltanedas** [comment]
tear gas worky

**Comment by asperger-sind** [comment]
> #21993 le smoke nade conflikt

yea i was planning on mentioning this like a week ago but forgot

either way i can probably incorporate the nades from this pr into the bombkit and by proxy nag delta to make lube and iron foam nades or both prs fusion dance or some shit

**Review by mirrorcult — APPROVED** [review]

**Comment by deltanedas** [comment]
pro just make it create a cloud directly instead of 6 beaker prototypes

**Comment by JoeHammad1844** [comment]
:steamhappy:

**Pull request merged**
