### PR TITLE
Fix rotated chair draw depth

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR 
Chair draw depth is adjusted on the client to draw the seat back over the player when the chair is facing north. However, a logic error exists in the code that restores the original draw depth that causes the chair to be drawn on top of the player.

Reproduction: sit in a chair, face north, then face any other direction. Player will be drawn under chair.

This PR fixes this (issues #11478 and #10326).

**Screenshots**

https://user-images.githubusercontent.com/3229565/198815216-c5570db3-a447-4482-96cf-d404531ee5d7.mp4

**Changelog**
:cl: notafet
- fix: Chairs are drawn correctly when rotated.

### CODE REVIEW

**Comment by ElectroJr** [comment]
Uhhh thanks for contributing but this is also now the 3rd open PR to fix these bugs (#12188 & #11600). 11600 even also mentioned those issues, so the PR is linked from them.

I get the impression people reaaaaly want this bug fixed.

**Comment by Emisse** [comment]
merge the one that does it best

**Comment by Kromabae** [comment]
please fix chairs

**Comment by Partmedia** [comment]
Mine is best because it adds comments, has the smallest code diff, and most clearly explains what's going on.

**Comment by Partmedia** [comment]
After reviewing the competing PR's, I feel that we shouldn't be letting perfection impede progress. All 3 of these PRs fix the layering bug, which is strictly an improvement from the status quo. It shouldn't be on those trying to improve things to also have to fix a loosely related bug.

**Comment by metalgearsloth** [comment]
Need to add comments in the code and also remove the references to the gh issues as it'll be a workaround.

**Comment by Partmedia** [comment]
Aren't these comments?
image

There's nothing in the code that refers to GH issues.

**Comment by metalgearsloth** [comment]
Anytime you use a workaround you should leave a comment so future coders know why a thing was done a particular way.

**Comment by Partmedia** [comment]
> Anytime you use a workaround you should leave a comment so future coders know why a thing was done a particular way.

Added a comment.

**Pull request merged**
