### PR TITLE
Make fland's mail into wheel-and-spoke distribution.

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Fixed [#26397 ](https://github.com/space-wizards/space-station-14/issues/26397#issue-2204488216)
image

## Why / Balance

good

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

I don't think this needs a cl

### CODE REVIEW

**Comment by Emisse** [comment]
ill take a look after work today

**Comment by PJB3005** [comment]
FYI "Addresses" is not a valid auto-close for GitHub https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by IProduceWidgets** [comment]
Ahh thank you, I was trying to figure out why that was being stubborn

**Comment by Emisse** [comment]
i lied i have time now

**Pull request merged**
