### PR TITLE
Cut low pressure damage to 1/4

### PR DESCRIPTION
**Pull request by PJB3005**
If the Marathon emergency shuttle gets breached, everybody without a suit dies in 60 seconds.

This is not an exaggeration. The entire shuttle reaches dangerously low pressure in 20 seconds, and at 2.4 pressure damage per second, spessmen is in crit in another 40.

If engineers want to respond, they would need to seal the breach in seconds. The canister on Marathon's shuttle can only fill the main shuttle area by like 6 kPa. This is a joke.

Yes, space should be deadly. But the current set of mechanics in SS14 give players 0 counter play, and most cases where "deadly space" actually matters is... nukies being poorly balanced. That's it.

Low pressure damage currently hurts the game *far* more than it adds. In the interest of not letting the game languish for another 6 months in this state, this is a bandaid fix.

When we get proper mechanics to allow players to DEAL with breaches, such as better ways to repressurize areas, this change can be reverted.

:cl:
- remove: Low pressure damage now does only 1/4th as much damage. This is a band-aid until better mechanics exists for the crew to deal with breaches of various kinds.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Would it be okay to add a comment saying it's temporary until we have breaching fixes so it doesn't get forgotten

Sidenote, we need to examine each shuttle because firelocks were delibrately removed from some of them, making depressurisation even worse

**Comment by keronshb** [comment]
> Would it be okay to add a comment saying it's temporary until we have breaching fixes so it doesn't get forgotten
> 
> Sidenote, we need to examine each shuttle because firelocks were delibrately removed from some of them, making depressurisation even worse

Shuttles probably need a better atmos backup instead of just one measily can of air.

**Review by keronshb — APPROVED** [review]

**Review by Tayrtahn — APPROVED** [review]

**Comment by deltanedas** [comment]
firelocks in shambles when they cant instakill people by not opening :trollface:

**Comment by BlueHNT** [comment]
This is a joke, right? You can already stand under low pressure for a ridiculous amount of time and now you can just live there? I sure hope this doesn't get down streamed.

**Comment by metalgearsloth** [comment]
> This is a joke, right?

Refrain from being toxic on PRs please.

> I sure hope this doesn't get down streamed.

Downstreams are in fact charge of themselves.

**Comment by BlueHNT** [comment]
> > This is a joke, right?
> 
> Refrain from being toxic on PRs please.

If this is already too toxic for you then you might need to change the age requirement to PG5.

**Comment by deltanedas** [comment]
> you might need to change the age requirement to PG5.

thats not how age ratings work and pg5 isnt a thing

**Comment by MutantMan2040** [comment]
The comments were too wicked for the playground. Four minutes is too long for survival, Space is not kid friendly, kids would die in under four minutes if they entered space. Cease your oppression of the masses, this is a foolish change which disrupts the balance/sense of the game.

**Comment by shampunj** [comment]
Just wear a space suit lol

**Comment by Admiral-Obvious-001** [comment]
I very recently had a shift where a revenant managed to work together with syndicate agents to space a majority of the station in combination with defile and C4.

Many, many people were killed very rapidly with the resulting spacing and new change that makes it mandatory to crowbar open firelocks with power and then atmos drained as a result of people with crowbars spacing the station worse.

Things I noticed. 

There aren't enough suits to go around (there shouldn't be). Though cargo can very quickly and cheaply fix that. 

If engineering is overwhelmed, or lacking in staff, you're fucked (This is usually true regardless.)

It somewhat feels like the spacing "meta/balance" is going in loops. I think this is a fine interim solution, but it's weird and will probably have knock on effects across the game.

**Comment by MjrLandWhale** [comment]
> If engineers want to respond, they would need to seal the breach in seconds.

Correct me if I'm wrong here, but using the default atmos cvars engineers have under half a second to seal before pressure drops into barotrauma territory. Spacing speed 0.15 so you lose 15% every tick (upped to current value in #28370), meaning after 4 ticks: 100kpa * (1-0.15)^4 -> 52kpa. Defualt atmos tickrate is 15, so you have about 4/15th of a second.

> When we get proper mechanics to allow players to DEAL with breaches, such as better ways to repressurize areas, this change can be reverted.

In terms of full answers to that statement, I don't have any. But I do have some observations and ideas: Keeping the station pressurized after any form of spacing is **difficult** after the changed to spacing speed. Due to the way firelocks are coded, they appear to only update every 30 game ticks. This means, at minimum, when any player opens a door to a spaced area, the pressurized section has to process (worst case) 15 atmos ticks before the firelock could update and close again.

With the current 0.15 spacing speed, 91.3% of all gas in the pressurized section is gone.
With the previous 0.05 spacing speed, you lose around 54% of all gas in the pressurized section.

I also understand there is probably some black coding magic in how gas mixtures are defined, segmented, and processed in the atmos code, otherwise we'd instantly be spacing a station before firelocks could kick in.  At a base level though, I think my point stands. The current spacing speed is FAR too aggressive to allow any type of mitigation (other than permanently carrying an O2/N2 tank).

Another issue is keeping enough gas in distro to support repressurizing the station. The way I'm reading gas vent code implies that, on update, you just move enough gas to fix any pressure difference between current & desired. Lets assume an area is at 60kpa, this means we need 40kpa to meet our desired pressure. In standard atmos at 2500L a tile, that means we're missing 1000L of gas. Each pipe can hold 200L of gas meaning we'd need to 5 pipes worth of distro pipenet gas (at 101kpa) to fully repressurize a single tile in my example.

Another example: A 10x10 fully spaced room. 100 tiles. 2500L per tile, 200L per pipe. Each tile uses 12.5 pipes of gas. This requires 1250 pipes worth of gas to repressurize. A few explosives can easily space a larger area.

All this is to say: The moment a spacing occurs atmos is currently screwed. The moment anyone opens a firelock to a spaced room, that connected area is essentially spaced before the firelock kicks in again. This is exacerbated by certain station designs (looking at Fland's hallways). As a result, I consider it a good day if I can keep distro running at 40-50kpa between spacings. Sidenote: The meteor changes have also made this problem much worse by both breaching the hull & then spacing interior sections.

Recommendation: Revert spacing speed changes. If not possible, increase the gas spawn amount of gas miners.

**Comment by deltanedas** [comment]
atmos is 2 ticks per second

**Comment by MilenVolf** [comment]
#29428 Can really help out with fixing breaches

**Comment by MjrLandWhale** [comment]
Ok, so the math becomes 2 seconds instead of <1/2. 

Revising my statements on firelocks, I seem to recall the server being 30 tick-rate? That's make it trigger (worst case again) every 2 atmos ticks. 

After 1 second:

- current speed: lose 30%
- previous speed: lose 10%

After 2 seconds:

- current speed: lose 48%
- previous speed: lose 19%

After 3 seconds:

- current speed: lose 63%
- previous speed: lose 27%

After 4 seconds:

- current speed: lose 73%
- previous speed: lose 34%


So holding a door open to drag a casualty through is enough to put the other side into barotrauma territory. Looks like old speed would take ~14 seconds to hit barotrauma territory. The air vent lockout threshold change means reverting the speed causes us to probably vent distro...

**Comment by DonkCoAcolyte** [comment]
I think that shuttle bombings killing most of the people present there extremely quickly shouldnt be seen as a bad thing, as it actually makes sense rp wise(shuttle bombing IS pretty nasty) and is a nothing burger gameplay wise(the last 2 minutes of "gameplay" where you sit in a chair are now replaced with deadchat). I personally think that the rest of the game would be affected too much in a negative way to justify sacrificing it all just to *survive* shuttle sometimes. Station side interactions that stem from spacings being rather deadly (saving someone from a spaced room, needing to patch up holes even in random nowhere rooms just because of it draining the surrounding area, sec needing to fiddle around either getting proper hardsuits or taking unarmored eva to get a criminal in space, said criminal using the relative safety and protection of space etc.) are trivialized/nullified by this change. In my personal experience engineering never had much issue actually fixing the spacings too station-side, provided the department was actually staffed. I dont personally understand what was supposed to be the *overwhelmingly negative* impact deadly space had with the normal damage values. It would help if some elaboration came through.

**Comment by DonkCoAcolyte** [comment]
The engineering department would loose quite a bit of work too, as spacings not being deadly would partially eliminate the urgency of fixing them.

**Comment by FairlySadPanda** [comment]
Whatever the final implementation of spacing is, can it please actually follow science rather than cartoon logic?

**Comment by Hmeister-real** [comment]
My favorite game, earthstation 14.

**Comment by JackSage** [comment]
This is clearly a result of the removal of atomisa's firefighting door remote
image

**Comment by TheDoctor1977** [comment]
> This is clearly a result of the removal of atomisa's firefighting door remote

Although I dislike the removal of the firefighting remote, the recent spacing issues are very much a consequence of the meteor changes, which really ought to be reverted and reworked.

**Comment by JackSage** [comment]
> > This is clearly a result of the removal of atomisa's firefighting door remote
> 
> Although I dislike the removal of the firefighting remote, the recent spacing issues are very much a consequence of the meteor changes, which really ought to be reverted and reworked.

Yeah I do think metors is part of the issue but I also think firefighting remote removal is too. Even before this nerf I saw way too many people literally see a firedoor with the firedoor lights engaged just crowbar open firedoors, realize "oh shit it's spaced" then run away, effectively spacing the room they were just in. But with this change it's going to get even worse since spacing is basically just tickling you, people will just completly outright ignore firelocks and just space more of the station. But I guess you can just take a nap with a medibot next to you if that happens.

**Comment by Muolai** [comment]
Personally i like the idea that you can venture out into space with just the regular survival box and get over to a safe space of the station, as it makes lone, unassisted survival more possible (this is fun). I do however think that there is a serious issue with how this is implemented, because the survival time can be infinitely extended (this is not fun) with meds or game mechanics (autoheal <20hp). I suggest that the damage be increased to 1/3 of original or be made an exponential function, and healing while taking baro-trauma be made less effective, another balancing lever might be an adjustment to emergency oxygen tanks.

**Comment by packmore** [comment]
> I think that shuttle bombings killing most of the people present there extremely quickly shouldnt be seen as a bad thing, as it actually makes sense rp wise(shuttle bombing IS pretty nasty) and is a nothing burger gameplay wise(the last 2 minutes of "gameplay" where you sit in a chair are now replaced with deadchat). 

might be tangential to the actual PR but shuttlebombing _is_ a bad thing when you observe it from a game balance perspective - although whether you think space station needs to be looked at from that angle is up to debate. 
a syndicate being able to achieve 2/3 of their tasks by simply dropping a syndie bomb on evac sucks for game balance, and it feels extremely defeating and unfun to the people affected by it, and to other syndies who actually care about putting the work in with their objectives.

however, like you said, it's ~2 extra minutes malding in deadchat before the round ends. it's not an issue so massive that i feel this band-aid was necessary, or at least this _extreme_, due to its effects on the rest of the game. if the main concern was shuttlebombing, there are better long and short term solutions to that than adding a blanket nerf to all pressure damage - readding firelocks to shuttles, as has been stated previously.

and if the main concern is the meteor events, then just band-aid that by temporarily reverting the meteor change. maybe i'm just missing something as i don't have proper knowledge of the game's development, but i also haven't heard a counter to either of these yet.

**Comment by DonkCoAcolyte** [comment]
> might be tangential to the actual PR but shuttlebombing _is_ a bad thing when you observe it from a game balance perspective - although whether you think space station needs to be looked at from that angle is up to debate. a syndicate being able to achieve 2/3 of their tasks by simply dropping a syndie bomb on evac sucks for game balance, and it feels extremely defeating and unfun to the people affected by it, and to other syndies who actually care about putting the work in with their objectives.
> 
Redtext/greentext is honestly a bit irrelevant, i believe? Yeah, you achieved 2/3 of your objectives by pressing a button, yes, its way easier than doing it the *proper* way, but did you actually have fun doing that?
Like, in almost every server there is, rules against metagaming are implemented, and whilst antags are usually exempt from it, rule 0 always applies.
If the person bombing the shuttle is only doing it to "win", then bwoink them over the head. They dont *get* playing antagonist. Them greentexting in an unfair way didnt achieve much either, as they dont get any special reward or continuous progress or anything for it.
As for the rest of the players, the "game" pretty much happened already, all antags did their thing, all crew had their time to play, aaaaand im repeating the point about it only being The last 2 minutes of the round that are affected. It is unfortunate that the players might get an unpleasent aftertaste from the whole round because of this, but again, this isnt severe enough to sacrifice the rest of the game for this.

**Comment by MorganTheMad** [comment]
One potential addition that might make this temporary fix less disruptive...

One of the primary balance disruptions is the speed penalty applied to space suits. If spacing is not deadly, then space suits are unnecessary, especially in combat.

However, in reality, pressure damage is DEBILITATING. Your joints ache, your skin itches, your head aches. While this is currently abstracted as pure damage... why not apply a speed penalty as well? One more severe than all space suits. (possibly less than the MOST encumbering space suits) That way a shuttle full of assistants can survive a shuttle bombing with a gas mask, but a corridor full of security  will be threatened in combat, a traitor trying to break into secure locations from the outside will have to be luckier to avoid being spotted, even with medication in their system.

Just to be sure, I've checked, and yes, people in pressurized aircraft can experience the bends if there is a sudden and complete loss of air pressure.

**Pull request merged**
