### PR TITLE
Major Anomaly Core Functionality Overhaul, Pt. 1

### PR DESCRIPTION
**Pull request by august-sun**
## About the PR
Gave each inert anomaly core a minimum added function appropriate for their type. These provide primarily utility-based benefits, with some being more specialized than others.

**Pyro Core:** A core that acts as a high-grade welding tool.

**Gravity Core:** Can be worn in either the belt or neck slots to provide magboot functionality

**Electricity Core:** Acts as a large battery.

**Ice Core:** Slips people, can make slippery floors.

**Rock Core:** Acts as a miniature wielded pickaxe single-handed, with same structural damage. Pocket pickaxe!

**Meat Core:** Can be microwaved to create an anomalous meat mass, a giant steak that can be cooked and eaten individually, or cut into 10 steaks.

**Liquid Core:** Pocket size jug. Does not spill when thrown. Must be filled from other containers.

**Bluespace Core:** 3x3 box. Can fit up to medium items.

**Shadow Core:** 2 minute long CD reusable mini smoke grenade.

**Tech Core:** Can be juiced to make Proktium, an extremely effective lubricant for machines even more effective than regular lube.

## Why / Balance
Currently, anomaly cores have very limited function. This gives each of them a unique feature that is beneficial to a user, as well as appropriate for the element of the anomaly. While some of these can cause trouble in the wrong hands, these arguably add more than enough intrigue that ideally offsets the risks they may pose.

## Technical details
Most YAML changes made to the cores draw components from items they act similar to, with only certain items inheriting parentage. While this extends the length of the descriptors, it avoids any unnecessary component complications or additions. This adds a description for each of the inert cores as well.

Sprites were added for new items (namely the anomalous meat mass and cooked version) and the added item state (the lit version of the pyro core welder).

A new component and system were made for the SmokeOnUse effect, allowing the shadow core to be used in-hand, adapted nearly identically from the SmokeOnTrigger system.

## Media
image
image
image
image
image
image
image
image
image
image
image
image
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:

- tweak: Added a wide range of new, unique uses for each inert anomaly core.
- add: Added new entity sprite states for new anomaly core functions.
- add: Added new anomaly-specific food.

### CODE REVIEW

**Comment by DieselMohawk** [comment]
One thing I noticed off the rip, for the meta.json file for the anomaly meat, you accidentally left "rouny meat cooked." That's probably causing an error.

**Comment by august-sun** [comment]
> One thing I noticed off the rip, for the meta.json file for the anomaly meat, you accidentally left "rouny meat cooked." That's probably causing an error.

Thanks, it's late and I at least wanted to get the uhhh proverbial meat of the PR out there. Will clean this up tomorrow!

**Comment by DieselMohawk** [comment]
> > One thing I noticed off the rip, for the meta.json file for the anomaly meat, you accidentally left "rouny meat cooked." That's probably causing an error.
> 
> Thanks, it's late and I at least wanted to get the uhhh proverbial meat of the PR out there. Will clean this up tomorrow!

All good, sleep well

**Comment by Cojoke-dot** [comment]
Great pr, I love the idea of cores doing more. I think the tech anom one is an issue though, too many shifts of non-antag sci making lasers and arming without any contraband. You essentially have a 1x1 item sec can't take from you without provocation that servers the same function as an 8tc item, it being a little slower is not going to affect much.

**Comment by Krovotushka** [comment]
Science would eat so good they become obese, also what about plant anomaly?

**Comment by DieselMohawk** [comment]
> Science would eat so good they become obese, also what about plant anomaly?

I believe a PR passed already that turned them into seeds

**Comment by august-sun** [comment]
> Great pr, I love the idea of cores doing more. I think the tech anom one is an issue though, too many shifts of non-antag sci making lasers and arming without any contraband. You essentially have a 1x1 item sec can't take from you without provocation that servers the same function as an 8tc item, it being a little slower is not going to affect much.

If it's not labeled as contraband, it was intended to be, apologies!

**Comment by Boaz1111** [comment]
It still says _the card zaps something in the airlock_ instead of something specifically for the core

**Comment by SoulFN** [comment]
I think this functionality should be moved to separate devices that are studied in the experimental tree (T2 or T3 technologies) and they require anomaly cores.

**Comment by Everturning** [comment]
these are really fucking OP holy shit
I am against these
there is no downside to any of them

**Comment by august-sun** [comment]
> A couple things:
> 
> Gravity Core: I'm conflicted about this. Coming from a server where the ONLY time we see the singularity is on Core, this feels pretty OP, but I don't know if it'd actually turn out that way. I would LOVE a storyline involving a heroic scientist sacrificing themselves to the tesla so everyone else could live, but I could see Science just handing these cores to Engineering, which a tesla would eat first anyways (and then stop because an engineer threw the core in, or it was just sitting next to a SMES that it's headed to eat). Regardless, I feel that even if people are using this in a meta way, any loose is going to result in evac no matter what -- you're just leaving a half-destroyed station instead of a fully-destroyed one.
> 
> Meat Core: fucking love this. we need more interactions with the kitchen
> 
> Tech Core: I almost think that the CD on this should be longer by a couple minutes, although I'd like to test it out in a real round before making this call for sure
> 
> > these are really fucking OP holy shit I am against these there is no downside to any of them
> 
> The downside is a) the very VERY long cooldown on some of these, b) which anomalies spawn is completely random, so fishing for the tech anom is probably going to require spawning several in the first place (which is suspicious behavior even without this PR being merged), and c) science will only ever get a handful of cores by round end at most, because they're encouraged to keep anomalies around for points. You're never going to have roundstart scientists handing out electric cores for greytiders' flashlights.

Appreciate the feedback here! And yeah, the cores are intended to be unique and useful tools without having a TON of abuse implemented. I have gotten feedback about the Tech Core potentially causing a bit too much trouble, my current alternative is creating a solution that does the same thing for machines that lube does, and making the anomaly generate said solution (which would be its ONLY purpose, it would not behave like lube).

Additionally, currently, the Bluespace Core is currently failing the integration test, so I'm exploring alternatives for that, as well!

**Comment by Cojoke-dot** [comment]
> > Great pr, I love the idea of cores doing more. I think the tech anom one is an issue though, too many shifts of non-antag sci making lasers and arming without any contraband. You essentially have a 1x1 item sec can't take from you without provocation that servers the same function as an 8tc item, it being a little slower is not going to affect much.
> 
> If it's not labeled as contraband, it was intended to be, apologies!

meh, it would still give a massive load on sec because a sci member took the core and emaged the proto-lathe so now all the tiders have lasers. Even if sec searched every sci they can hide the core in one large space, so plushies, G.O.R.I.L.A gauntlets, top hats, and lots of places sec would never check and just cause some sci who is a non-antag to emag the lathe. It would either end up with more people getting banned for emaging the lathe and handing out guns as a non-antag and/or a much greater strain on sec due to sci constantly making weapons, forcing them to destroy the rd server to prevent the production of more. idk, I don't see how this item is not just going to be abused to make sec shifts worse.

**Comment by Kandiyaki** [comment]
this is a REALLY cool idea, but I feel like it's too much to be able to get these effects near-roundstart. I'd say a good balance would be to make a new "harnesser" item that you can load cores into, which causes these effects based on the type loaded in, locked behind the same tech as the GORILLA gauntlet. this would:
- make it easy-ish to get the item, since anomaly core harnessing is a tier 1
- make it so these effects aren't just a free reward for taking down anomalies
- make the anomaly core harnessing tech finally have multiple uses
- make it so you need access to a protolathe in order to use the cores (tider repellent)
- make it so you don't have to mark the cores as science contraband, just the harnesser
- make it easy to give the harnesser a limited amount of charges per core in case of balance issues

could be implemented decently easily by just modifying the GORILLA gauntlet code, i think

**Comment by deltanedas** [comment]
tech anomaly core being an emag would go so hard for making free borgs

**Comment by EthanQix** [comment]
I think this is a great idea, though I'd modify two cores : 
- Grav core : the anti singulo effect is too situational to be really useful. Maybe make it a tiny grav gun instead ?
- Tech core : a mini emag for 0TC is OP no matter how you look at it, not to mention it could encourage shitter behavior. It shouldn't recharge at all.

**Comment by august-sun** [comment]
> this is a REALLY cool idea, but I feel like it's too much to be able to get these effects near-roundstart. I'd say a good balance would be to make a new "harnesser" item that you can load cores into, which causes these effects based on the type loaded in, locked behind the same tech as the GORILLA gauntlet. this would:
> 
>     * make it easy-ish to get the item, since anomaly core harnessing is a tier 1
> 
>     * make it so these effects aren't just a free reward for taking down anomalies
> 
>     * make the anomaly core harnessing tech finally have multiple uses
> 
>     * make it so you need access to a protolathe in order to use the cores (tider repellent)
> 
>     * make it so you don't have to mark the cores as science contraband, just the harnesser
> 
>     * make it easy to give the harnesser a limited amount of charges per core in case of balance issues
> 
> 
> could be implemented decently easily by just modifying the GORILLA gauntlet code, i think

So, the point mario made earlier regarding the aim of keeping anomalies alive early on is a key one. Yeah, you might get a cool object out of it if you kill the anomaly, but you've also just shut down one of the early, steady ways you have to generate points. There's incentive to keep anomalies stabilized at least initially for that sake.

Additionally, the cores aren't intended to be a science-only item, it's to give departments throughout the station useful interaction with the cores. Some are more specific, some are more general. The size of the object also comes into play, as putting them in a gauntlet kind of neutralizes that benefit.

Like others have said around the emag, I realize how much of a problem that has the potential to cause, so I'm looking at alternatives for it (like the previous mention of making it auto-generate a solution exclusively for speeding up machines).

**Comment by UncaughtEx** [comment]
Perhaps the tech anom core can wipe a borgs laws completely

**Comment by UncaughtEx** [comment]
A way to completely wipe borg laws and make free borgs would be fun

**Comment by Salinarin** [comment]
Tech anom core as an EMAG is too strange. Maybe make it a remote signaller with unlimited range or a door remote with random accesses?

**Review by LankLTE — CHANGES_REQUESTED** [review]
While these having some side effect is cool, their primary use is to power the GORILLA and it should stay that way. The meat, liquid & bluespace cores manages to strike a nice balance of being a simple neat side effect you can use them for, but almost all of the others are far too strong (tech, gravity, and electricity), or far too weak (ice, shadow). If that was sorted out and they were redone to be more middling effects I think this could be reconsidered but as-is this won't be merged.

**Comment by WhiteGorila** [comment]
Lots of bitching and moaning in the comments dispite the 24 likes, the game needs more fun in it

**Comment by Djungelskog2** [comment]
> Lots of bitching and moaning in the comments dispite the 24 likes, the game needs more fun in it

The game would be more fun if everyone got .35 pistols in their emergency boxes and 2 mags to go along with it round start 
Or is fun subjective

**Comment by WhiteGorila** [comment]
> > Lots of bitching and moaning in the comments dispite the 24 likes, the game needs more fun in it
> 
> The game would be more fun if everyone got .35 pistols in their emergency boxes and 2 mags to go along with it round start Or is fun subjective

That would be in the more fun category

**Comment by Djungelskog2** [comment]
> > > Lots of bitching and moaning in the comments dispite the 24 likes, the game needs more fun in it
> > 
> > 
> > The game would be more fun if everyone got .35 pistols in their emergency boxes and 2 mags to go along with it round start Or is fun subjective
> 
> That would be in the more fun category

WYCI? :godo:

**Comment by Spessmann** [comment]
Make this only apply to cores from supercritical anomalies so the regular ones still have use with gorilla gauntlets :trollface:

**Comment by insoPL** [comment]
> this is a REALLY cool idea, but I feel like it's too much to be able to get these effects near-roundstart. I'd say a good balance would be to make a new "harnesser" item that you can load cores into, which causes these effects based on the type loaded in, locked behind the same tech as the GORILLA gauntlet. this would:
> - make it easy-ish to get the item, since anomaly core harnessing is a tier 1
> - make it so these effects aren't just a free reward for taking down anomalies
> - make the anomaly core harnessing tech finally have multiple uses
> - make it so you need access to a protolathe in order to use the cores (tider repellent)
> - make it so you don't have to mark the cores as science contraband, just the harnesser
> - make it easy to give the harnesser a limited amount of charges per core in case of balance issues
> 
> could be implemented decently easily by just modifying the GORILLA gauntlet code, i think

Making universal item that transform into anomaly core specific item, then marking some of them as contraband would make more sense. Would also make mining with core look less goofy.

**Comment by superjj18** [comment]
singulooses and teslooses are cringe 👍 #BuffTheDecelerator

**Comment by strO0pwafel** [comment]
ideaguying
gravity: weightless pulling
ice: removes firestacks
electricity: defib

**Comment by august-sun** [comment]
> singulooses and teslooses are cringe 👍 #BuffTheDecelerator

Super agreed, I might PR this one.

**Comment by august-sun** [comment]
> ideaguying gravity: weightless pulling ice: removes firestacks electricity: defib

Per Lank's feedback, removing firestacks and defib might be too strong; at the moment, looking at converting the electricity one to a large battery equivalent, and for ice, making an ice crust floor with a 2 second doafter. Ice is one of those that's tricky to find an okay use for, and I think that'll be good enough for the potential novelty's sake without being too OP or in the way.

**Comment by HyperB1** [comment]
Tech core would be better off having multitool functionality.

**Comment by superjj18** [comment]
> Tech core would be better off having multitool functionality.

That's lame af, mini-emag is infinitely cooler

**Review by TheShuEd — CHANGES_REQUESTED** [review]
Ok, we discussed this pr by a group of maintainers and agreed on the following:

- Anomaly cores should not be useful “directly” as a container or tool. They may have alternative uses in other systems, but these uses should be incidental, as the primary purpose of the cores is to charge the GORILLA gauntlet
- The “add functionality for all cores” approach doesn't make sense. Most of the mechanics you've added are an owl on a globe, and are only added to add functionality everywhere. It's better to have no use at all than to have mediocre use.

As a result we decided that only the core meat anomaly and its recipe in the microwave made sense, all other changes should be canceled.

**Comment by august-sun** [comment]
Closing PR to submit with requested changes

**Pull request closed without merging**
