### PR TITLE
Update Core

### LINKED ISSUE #29614: Core has duplicate air alarm in the hallway next to botany
## Description

Core has an unused air alarm next to botany. It's not connected to any devices and is duplicate with the one on the lower right.

**Reproduction**

**Screenshots**

Content Client_JqtZkELRdB

**Additional context**

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Fixes #29614
I forgor about 29074 but ill fix it in a few days

Other misc fixes, alongside voxxie room!

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

image

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
The vox room is extremely intrusive and does not flow well into that room at all, no other place was suitable?

**Comment by lzk228** [comment]
the vox room will be suitable with directional windows and windoors

**Comment by UbaserB** [comment]
> The vox room is extremely intrusive and does not flow well into that room at all, no other place was suitable?

there could definitely be, there is one other place i was thinking, but im not super keen on replacing it. Waiting on emisse opinions and suggestions to fix though..

**Comment by Djungelskog2** [comment]
ok yea the vox box really aint doing anyone any favours... i think it would have been better if it were simply the same table but encased by glass with a small airlock to keep the theme of the food court in tact

**Comment by WallaceLordofOwls** [comment]
The vox box as you have implemented it does not work properly, and is in fact a massive hazard to the station. 

First off, regarding it not working, it needs an air alarm and a scrubber scrubbing oxygen or else the vox will die to oxygen that comes in.

Regarding it not working and killing the station, THE AIRLOCK IS NOT HOOKED UP. There is nothing stopping someone from accidentally opening both doors and letting O2 in and N2 out. 

How does this kill the station? Well, the vox box is filled with higher pressure nitrogen, so if ANYONE opens both doors, which is extremely easy to do accidentally, the entire west side of the station is flooded with nitrogen that proceeds to start suffocating people.

I know this because I have had to clean this issue up twice in two separate rounds as atmos, and let me tell you, changing the nitrogen and oxygen content in a full pressure room is not fast or easy.

Please fix this vox box ASAP or revert the PR immediately. I don't know what testing you did with the vox box, but it should have picked up these issues.

**Comment by Emisse** [comment]
You can leave feedback without this rhetoric, everyone who works on this game is a volunteer.
image

**Comment by UbaserB** [comment]
Also, I already know about the issue and it’s being worked on.

I already

**Pull request merged**
