### PR TITLE
Increase Tesla coil power output

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
Double energy per zap in the Tesla coil.

## Why / Balance
Tesla coils are generating too little power such that on stations like Meta, a round-start (pre-buffed) AME and Tesla are not enough to keep the station powered and the lights from blinking.

See: https://github.com/space-wizards/space-station-14/pull/28419

## Media
1-core (pre-PBJ-buff) AME + Tesla can now power Meta. Tesla still does not provide enough power by itself to power the whole station. Picture shows empty SMES charging with combined AME + Tesla output.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: notafet
- tweak: Increase power output from Tesla coils.

### CODE REVIEW

**Comment by LankLTE** [comment]
The Tesla probably should be enough to power a station on its own, no? Requiring two engines kind of undermines the point of using it vs singulo even further I feel like.

**Comment by deltanedas** [comment]
you never needed an ame with a good tesla setup ime

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
agree with Lank. Tesla should be able to solo power a station just like singulo or TEG. Perhaps it'd be worth increasing the frequency of the lightning instead of just the charge but in any case you shouldn't need to run the AME alongside it just to have functional power.

**Comment by Partmedia** [comment]
I made the number bigger so that the Tesla by itself can power Meta. I tested 1500000 (which was not enough) until I arrived at this number.

**Comment by Admiral-Obvious-001** [comment]
> agree with Lank. Tesla should be able to solo power a station just like singulo or TEG. Perhaps it'd be worth increasing the frequency of the lightning instead of just the charge but in any case you shouldn't need to run the AME alongside it just to have functional power.

Wouldn't increasing the frequency of lightning also substantially ramp up the destructive capacity of the tesla and also make it so it'd bypass the coils and grounding rods with higher probability?

**Review by EmoGarbage404 — APPROVED** [review]

**Pull request merged**
