### PR TITLE
Lets atmos build gas pipes in walls

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Changed it so that you can build gas pipe in impassable objects, such as walls

## Why / Balance

long-requested feature by all the people I know that play atmos

It's kind of a nice QoL change being able to build pipes through walls or windows, you still need to build the vents or pumps outside of walls so you can't really cheese anything. It just lets you repair stuff, make additions, or build shuttles a lot easier.

If you need an IC explanation as to how its done, just pretend that you're just drilling a hole or cutting out a part of the wall temporarily or something, like how people do repairs to houses...

## Technical details

bool

**Changelog**

:cl: 
- tweak: You can now build atmos gas pipes through things like walls.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
> nice QoL change 

how does this constitute a qol change

**Comment by Plykiya** [comment]
> > nice QoL change
> 
> how does this constitute a qol change

I'm probably not using the term in the way you interpret it so uh, just call it a buff if you want

**Comment by SlamBamActionman** [comment]
Disposal pipes can be built inside walls; I honestly thought atmos pipes were the same!

**Comment by EmoGarbage404** [comment]
> Disposal pipes can be built inside walls

this was fixed recently

**Comment by deltanedas** [comment]
frequently you have to take down walls or windows and remove the floor under it just to add a single pipe then fix it back up

if anything rcd should be able to do it since its le magic tool

**Comment by Plykiya** [comment]
> frequently you have to take down walls or windows and remove the floor under it just to add a single pipe then fix it back up
> 
> if anything rcd should be able to do it since its le magic tool

RCD currently has a check for InRangeUnobstructed to prevent you from building the rest of the options on walls, but it also prevents you from building layering things under doors IIRC...

**Comment by MACMAN2003** [comment]
> > nice QoL change
> 
> how does this constitute a qol change

this makes it so you don't have to deconstruct and then reconstruct a wall just to place a pipe in it

**Comment by mirrorcult** [comment]
this is Probably fine in the absence of pipe layering

**Comment by deepdarkdepths** [comment]
All this does is speed up setting up burn chambers by a lot which isn't an issue, it would be a welcome change due to pipe stacking being killed

**Comment by WarMechanic** [comment]
as long as its not disposal pipes under walls then its good

**Comment by GimmyPick** [comment]
Hope this one will be merged soon, i am tired of spending time on breaking current trit chambers in order to fil all 9 scrubbers

**Comment by Partmedia** [comment]
There is this technique for setting up radiators close to the station. In light of this, I wonder if this is still necessary?
image

**Comment by deltanedas** [comment]
thats not even a good use of radiators and is irrelevant to placing pipes under walls

**Comment by GimmyPick** [comment]
> There is this technique for setting up radiators close to the station. In light of this, I wonder if this is still necessary? 

how is this related

**Comment by Plykiya** [comment]
Apparently the blocker on this is "why should we have this when we just changed how disposal pipes work"

1. Disposal pipes were changed because it was a four steel solution for shitters and antags to get anywhere they wanted without any effort, gas pipes do not grant you access to anything
2. Gas pipes being changed to construct under things doesn't allow you to do anything antagonistic because you still need to get physical access to the other side
3. Allows atmos to do more of their job (repairing pipes, building new pipe systems) without opening up physical access to people who shouldn't be somewhere (example: building new pipe setup for chem so they have access to infinite X gas supply, doesn't require you to deconstruct chem walls to do it. chem setups are generally quite compact already)
4. The current atmos experience is pure suffering
5. Current building options require you to only be able to build pipes where there is open floor space. One of the biggest detriments to atmos construction plans is having to weave through doorways and praying that the one tile doorway is unoccupied by existing pipelines. The alternative is spending several minutes deconstructing and reconstructing walls just to build a single pipe.

**Comment by GimmyPick** [comment]
Facts, it became easier to make maxcap than frezon as for me. Destroying walls with current axe's structural damage is just pure pain, inability to place pipes under walls just demotivate people to cook gases. Making gases is the most difficult mechanic in the game, yet it's not rewarding compared to how much time you spend building the most effective schemes.

**Comment by GimmyPick** [comment]
i think wizdens forgor about this pr 💀

**Comment by Plykiya** [comment]
> i think wizdens forgor about this pr 💀

they haven't

**Comment by a-person5660** [comment]
They most certainly have

**Comment by Plykiya** [comment]
> They most certainly have

good thing I got promoted to maintainer in that timespan :godo:

**Comment by a-person5660** [comment]
> > They most certainly have
> 
> good thing I got promoted to maintainer in that timespan :godo:

Wheeeyyyyy, I really hope this goes through. This pr would make my life so much easier.

**Comment by Plykiya** [comment]
Maintainers have agreed this is mostly a fine change while we don't have the RPD.

**Comment by Plykiya** [comment]
Making maintainer sentiment statements on my own PR is funny as hell

**Pull request merged**
