### PR TITLE
Made N2O visible

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

Made n2o visible.

## Why / Balance

The texture already was in atmospherics.rsi, so why not?

## Media

**nitrous oxide being visible**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Nitrous oxide gas is now visible.

### CODE REVIEW

**Comment by LankLTE** [comment]
Pretty sure Nitrous Oxide irl is inivisble. Correct me if I'm wrong.

**Comment by lzk228** [comment]
image

**Comment by mirrorcult** [comment]
the textures do exist for ss13 but having it be invisible was a deliberate design choice here, not an oversight

**Comment by whateverusername0** [comment]
damn

**Pull request closed without merging**
