### PR TITLE
Fix door access in mapping mode

### PR DESCRIPTION
**Pull request by metalgearsloth**
Fix shouldn't break anythingTM.

Fixes https://github.com/space-wizards/space-station-14/issues/26802

### CODE REVIEW

**Comment by lzk228** [comment]
true hero

**Comment by Moomoobeef** [comment]
Mappers rejoice!!

**Comment by IProduceWidgets** [comment]
Thank you space jesus.

**Comment by metalgearsloth** [comment]
If it breaks just yell at me but makes mapping impossible rn.

**Comment by lzk228** [comment]
mappers rejoice

**Pull request merged**
