### PR TITLE
Validate prototype ids in c# fields

### PR DESCRIPTION
**Pull request by ElectroJr**
This PR makes the YAML linter use the new prototype id field validation method that is added in space-wizards/RobustToolbox/pull/4189 and makes the `ClothingSystem` use the new validation prototype. This PR also includes various fixes for problematic data-fields that fail the new validation.

Requires space-wizards/RobustToolbox/pull/4189

### CODE REVIEW

**Comment by mirrorcult** [comment]
lovely and beautiful

**Comment by mirrorcult** [comment]
deserializing directly into prototypes when

**Comment by ElectroJr** [comment]
> deserializing directly into prototypes when

I don't think it would even be all that hard to add this? Though I also don't want to encourage too much prototype hardcoding.

**Comment by moonheart08** [comment]
blessed

**Pull request merged**
