### PR TITLE
Shuttle walls visual change

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Makes shuttle walls use the plastinum sprites from /tg/ but edited to be brighter, also ports the old shuttle windows (using para sprites.)
Also removes interior shuttle walls; I have no clue what to do with them visually right now & the design of shuttle walls is probably too complex to simplify to something better. The current ones look pretty bad as well. If someone wants to readd them with better sprites then they're free to.

## Why / Balance
Our current shuttle wall sprites are great, but don't really fit at all - they're basically in a completely different style compared to every other wall in the game.
These sprites are by no means perfect, but should make it easier to do visually interesting stuff with shuttles later on + will probably look a little better once shuttle tiles are resprited and properly usable in shuttles.

## Media
Content Client_Qbrm0OxDYP

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: New shuttle wall sprites.
- remove: Removed interior shuttle walls.

### CODE REVIEW

**Comment by mirrorcult** [comment]
not sure how i feel about this. like you say the current shuttle walls are pretty good. i think the current ones will look significantly less out of place when we get actual good shuttle tiles

**Comment by mirrorcult** [comment]
and im not sure they even look particularly out of place right now

**Comment by IamVelcroboy** [comment]
Yeah, don't remove the interior walls. Don't use them if you don't want but they are used elsewhere.

**Comment by UbaserB** [comment]
I dont like these new sprites as they are currently

**Comment by potato1234x** [comment]
imo the ones we have fit fine, ive never once looked at them and thought they were out of place. these ones are objectively less shuttle looking and more insane asylum looking

**Comment by Flareguy** [comment]
Okay, I'm a bit late here, but here's my rationale...

__Artstyle concerns:__
image

**Left:** current shuttle walls, **Middle:** /vg/station shuttle walls, **Right:** proposed shuttle wall changes.
Outside of being relatively perspective-agonistic like the rest of our walls are (for the most part,) I feel like my assessment that these are made completely differently compared to most other walls in the game is likely pretty spot-on. They're fairly visually complex and sharp-looking. I won't really knock the blue-adjacent coloration much though, as they are literally meant to be made out of titanium. It arguably makes sense, though if you think it does personally is probably up for debate.

__Doing interesting stuff with shuttles in the future:__

This is mainly just conceptual and doesn't really hold as much weight (hell, this might even just flat out be outside my artistic capabilities,) but I eventually wanted to try making cool FTL / Goonstation external shuttle parts like [this](https://wiki.ss13.co/File:Cogmap2Arrivals.png) (the image on this post) or [this](https://wiki.ss13.co/File:HumanGUINew.png). I feel like it's fairly unlikely that the current style of shuttle walls will allow me to do this, due to their inner grey filling. I may just not be thinking hard enough about it, though, as I haven't actually tried making that yet.

image

**Comment by Flareguy** [comment]
DAMN IT I posted that way too early, I forgot to finish what I was writing.

There's one other component to this: as far as I'm aware, the proposed shuttle walls might be our best bet for a replacement with all of the above factors considered. The classic /vg/ ones are pretty good looking and fit the artstyle well, but look bad next to steel tiles due to their high brightness (they need to be used with shuttle tiles to look good,) and will also cause minor breakage here since these need to also use the alternate wall smoothing mode to work.
*(random image nabbed from google images showcasing the /vg/ shuttle walls in question)*
image

with all that being said, though, I've already finished shuttle tiles that are at least *marginally* better then what we have now. I should probably just PR those and wait for them to be mapped first to figure out what to do, like what mirror suggested.

**Pull request closed without merging**
