### PR TITLE
Rod: NEW Evacuation shuttle

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This is a new medium size shuttle for the station Marathon, ideal for a player base of around 60. It features a two separate engineering rooms to keep the power/atmos and seating area separate. The power/atmos is compact as to reduce space and keep it close together. Security also features a holding cell with a brig timer. 

**Departments include:**
- Bridge
- Medical
- Security
- Bar
- Engineering

**Features:**
- savegrid
- variantize
- base plastic tile with mono steel under the seats

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

rod_evac

**Changelog**

:cl: Ubaser
- add: Added a new evacuation shuttle for Marathon

### CODE REVIEW

**Comment by HoidC** [comment]
could there be double airlocks leading into bridge

**Comment by UbaserB** [comment]
> could there be double airlocks leading into bridge

not enough space

**Comment by Emisse** [comment]
box already has a unique shuttle

**Comment by UbaserB** [comment]
> box already has a unique shuttle

which station do you recommend @Emisse

**Comment by Emisse** [comment]
marathon, meta, origin, are missing unique ones off the top of my head

**Comment by UbaserB** [comment]
> marathon, meta, origin, are missing unique ones off the top of my head

alright, ill change it

**Comment by lzk228** [comment]
brig timer? for what lol?

**Comment by UbaserB** [comment]
#

> brig timer? for what lol?

even if its not used, "theoretically" it would be useful

**Comment by Emisse** [comment]
reviewed on discord

**Pull request merged**
