### PR TITLE
Turrets for the infiltrator

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR 
Puts turrets in the infiltrator ship, also adds a grinder to the syndieplanet cus I forgot and removes a wire above the snow tiles.
**Screenshots**

**Changelog**

:cl:
- add: The syndicate infiltrator ship now has automatic turrets that shoot intruders.
- add: The syndicate discovered grinders, now nukies have it at the outpost.

### CODE REVIEW

**Review by Emisse — APPROVED** [review]

**Comment by mirrorcult** [comment]
are you sure the turrets dont just shoot nukies

**Comment by metalgearsloth** [comment]
> are you sure the turrets dont just shoot nukies

They didn't in my pr.

**Comment by EmoGarbage404** [comment]
> are you sure the turrets dont just shoot nukies

Pretty sure this is just the same issue grenade penguin has but infinitely worse. Syndies and nukies dont actually have their proper factions assigned to them

**Comment by DogZeroX** [comment]
They shouldn't be since the only turret we have is allied to nukies, they only shoot syndie reinforcement at the moment.

**Comment by moonheart08** [comment]
The turrets do not shoot nukies, I confirmed this during live games.

**Pull request merged**
