### PR TITLE
MedTek Cartridge

### LINKED ISSUE #14543: musician and medical pda goodies should probably be cartridges
## Description
so you can steal from dead people / your old pda and put in new pda

### LINKED ISSUE #19159: Medical's Health Analyzer PDA should either be removed or made into a cartridge
All PDA systems should be made into cartridges.
This is also just a straight upgrade to health analyzer since it doesn't require battery. 
Maybe tie a cooldown to it to compensate.

### PR DESCRIPTION
**Pull request by ArchRBX**
## About the PR

Adds a new PDA cartridge that gives your PDA health analyzer functionality. This replaces the innate health analyzer medical PDA's have currently.

Medical Staff start with this cartridge preinstalled, and a spare cartridge is available in the CMO's locker.

Fixes #19159, partially fixes #14543

## Why / Balance

PDA functionality should be tied to cartridges, not to specific PDA models. Enables hired medical staff to use their PDA as a health analyzer by installing the cartridge.

Program leaves room for a PDA medical record display (like the wanted list cartridge) when those are implemented.

## Technical details

No major changes, just adds a new cartridge that applies the HealthAnalyzer component to PDA's on installation.

Makes the Silent property on health analyzers silence the beep on doAfter, too.

## Media

image-1

https://github.com/user-attachments/assets/122eb43c-f44e-4b28-9494-2527b124007e

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**
:cl:
- add: The MedTek PDA cartridge has now been added, providing health analyzer functionality to PDA's
- add: The MedTek cartridge has been added to the CMO locker, and comes preinstalled on medical PDA's, replacing the built-in analyzer functionality on these PDA's

### CODE REVIEW

**Comment by slarticodefast** [comment]
Fixes #19159
Partially fixes #14543

**Comment by Catdere** [comment]
I was reading though the everything and I think you forgot about the Agent PDA

**Comment by ArchRBX** [comment]
> I was reading though the everything and I think you forgot about the Agent PDA



The Syndicate Agent PDA? Strangely this doesn't have a health analyzer included in the original prototype, so a preinstalled MedTek wasn't added.
https://github.com/space-wizards/space-station-14/blob/9c2fe85d4765e03c5c4b931b76e8dbbb8fb2955b/Resources/Prototypes/Entities/Objects/Devices/pda.yml#L1131-L1155

**Comment by Golinth** [comment]
> > I was reading though the everything and I think you forgot about the Agent PDA
> 
> The Syndicate Agent PDA? Strangely this doesn't have a health analyzer included in the original prototype, so a preinstalled MedTek wasn't added.

Its parent is the medicalPDA, so it scans the same. Definitely have the scanner come pre-installed on it as well.

**Comment by ArchRBX** [comment]
> > > I was reading though the everything and I think you forgot about the Agent PDA
> > 
> > 
> > The Syndicate Agent PDA? Strangely this doesn't have a health analyzer included in the original prototype, so a preinstalled MedTek wasn't added.
> 
> Its parent is the medicalPDA, so it scans the same. Definitely have the scanner come pre-installed on it as well.

Oh, missed that! Easy fix.

**Comment by Fildrance** [comment]
Will op-ness of pda health scanner be addressed in this PR or better in separate one?
Emessie proposed to add cooldown, i'd propose to disable auto-updates...

**Comment by ArchRBX** [comment]
> Will op-ness of pda health scanner be addressed in this PR or better in separate one? Emessie proposed to add cooldown, i'd propose to disable auto-updates...

I don't have any personal desire to change the balance of it so that's probably better off in another PR. I think holding out your PDA constantly is a risk that balances it out in my mind.

**Comment by Ilya246** [comment]
as a side effect this PR makes health analyzer completely useless since cartridges are reusable, just give the cartridge to anyone who wants the scanner then have them install and eject

**Comment by ArchRBX** [comment]
> as a side effect this PR makes health analyzer completely useless since cartridges are reusable, just give the cartridge to anyone who wants the scanner then have them install and eject

Reasonable point! Will have to see what maintainers think, but that's a valid concern. I think giving the analyzer some perks might be the way forward as they were never used by Doctors anyway.

**Comment by Ilya246** [comment]
maybe just make this into a non-reusable cartridge

**Comment by ArchRBX** [comment]
> maybe just make this into a non-reusable cartridge

I think capping off the number of uses kinda defeats the idea behind role-related cartridges personally, as they're meant to facilitate hiring.

**Comment by thebadman4662** [comment]
> > Will op-ness of pda health scanner be addressed in this PR or better in separate one? Emessie proposed to add cooldown, i'd propose to disable auto-updates...
> 
> I don't have any personal desire to change the balance of it so that's probably better off in another PR. I think holding out your PDA constantly is a risk that balances it out in my mind.

And here comes ancient technique of keeping your ID out of PDA and ID on PDA slot. :godmode:

**Comment by superjj18** [comment]
> as a side effect this PR makes health analyzer completely useless since cartridges are reusable, just give the cartridge to anyone who wants the scanner then have them install and eject

I'd say just buff the health analyzer so it doesn't need batteries and it becomes something you can just give to non-meds without much worry

Honestly might be a nerf considering having an extra supply of batteries can be pretty useful for med

**Comment by Golinth** [comment]
> I'd say just buff the health analyzer so it doesn't need batteries and it becomes something you can just give to non-meds without much worry
> 
> Honestly might be a nerf considering having an extra supply of batteries can be pretty useful for med

Make it instantly scan and/or give additional info the cartridge won’t give, like chems currently in the system

**Comment by ArchRBX** [comment]
> I know there was this comment when I was building out the health analyzer [#19270 (review)](https://github.com/space-wizards/space-station-14/pull/19270#pullrequestreview-1583901912) was this method still fine?

Somehow didn't see your PR while making my own. I imagine that implementing the UI fragment is something that can be amended by another PR if that's something someone wants to pick up.

**Pull request merged**
