### PR TITLE
Remove Disabler Damage + Allow Pacifists to Use Disablers

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Removes the heat damage from Disablers and allows Disablers to be used by pacifists.
## Why / Balance

Currently, Pacifists can use stun batons but not disablers, which does not make much sense to me. Permitting this would allow more self-defense options for pacifists, especially for heads of staff and pacifist security members. Parent the Disaber SMG projectile to the Disabler projectile because… parenting is cool 😎(changes to Disabler bolt should affect both)
## Technical details

magic of yml
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/a1fdbe77-41e0-43e8-88e8-1679a18bdb26

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Pacifists can now use disablers

### CODE REVIEW

**Comment by Plykiya** [comment]
I'm all for changes that make pacifists less of a joke 👍

**Comment by metalgearsloth** [comment]
Sentiment among maintainers is pacifists shouldn't be using stamina damage weapons (which would also include stun batons).

**Comment by Cojoke-dot** [comment]
> Sentiment among maintainers is pacifists shouldn't be using stamina damage weapons (which would also include stun batons).

alright, I guess I make the inverse and remove stun batons from pacifists then, o7

**Comment by Cojoke-dot** [comment]
Reopen please I guess, they decided to have this one over stun batons getting removed from pacifists.

**Pull request closed without merging**
