### PR TITLE
More windoors (starring directional window)

### PR DESCRIPTION
**Pull request by SphiraI**
## About the PR
Adds both Plasma, and Uranium variants of secure/normal windoors, and directional uranium windows to complete "The Glass Set"

## Why / Balance
Slowly more and more structures of various glassy nature have been added, and this *should* round off the set for the main objects. (windoors, windows, *slim* windows, etc). *Aside from having at least plasma windoors just making sense, plasma windoors was also requested for a map being made, so there's that.*

## Technical details
- Mostly copied existing proto code, and tried to organize some stuff where I could, although probably still a bit messy and could have a once over later if needed. (Mostly things like ID names)

## Media
image
image
image
image
image

More-Windoors
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Sphiral
- add: NT has finally perfected methods for infusing Plasma/Uranium into Glass! Windoors now have such varients! And Uranium Slim Windows exist!

### CODE REVIEW

**Comment by MACMAN2003** [comment]
"ShardGlassRUranium" doesn't exist, you could instead try spawning a regular uranium glass shard and a metal rod

**Comment by SphiraI** [comment]
> "ShardGlassRUranium" doesn't exist, you could instead try spawning a regular uranium glass shard and a metal rod

Okay, maybe staying up finishing this PR wasn't the best idea, and maybe sleep *is* a good idea after all

Thank you tho

**Comment by B1essedknight** [comment]
I'm going to significantly enjoy reinforcing random parts of the station with this PR. Thanks for the good work. 👍

**Comment by TheShuEd** [comment]
Test fails is real.

it complains that after disassembly the price of components increases

**Review by lzk228 — CHANGES_REQUESTED** [review]
remove price from all windoors, maybe even set base windoor to 0, because why structures even cost like this
it also should fix tests

**Comment by UbaserB** [comment]
oh this is really good

**Pull request merged**
