### PR TITLE
SmartFridge now contains chemistry equipment

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Added 3 boxes of bottles, 3 boxes of pill canisters, and 3 boxes of beakers to the Smart Fridge. Eventually I want chemists to be able to dump bottles and pills into the fridge so doctors can come over and dispense them, but I think this is a good change to make it useful for now.

**Changelog**

:cl:
- tweak: SmartFridge now contains chemistry equipment.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
iirc in 13, chemists were able to stuff their goods (pills, bottles) in the smartfridge for other people to use instead of just throwing it all on the counter

**Comment by GoodWheatley** [comment]
> iirc in 13, chemists were able to stuff their goods (pills, bottles) in the smartfridge for other people to use instead of just throwing it all on the counter

Yeah that's the behavior I want to implement, but I feel like giving it a temporary use for now is a good idea (Plus the chemists would really appreciate the extra bottles)

**Comment by Illiux** [comment]
It seems redundant to put beaker, bottle, and canister boxes in the SmartFridge when they're all already in chemistry lockers. If we wanted to give chemists more of them it makes more sense to just add more to the locker rather than muddy the purposes of the three roundstart storages (locker, chemdrobe, SmartFridge).

But that aside I don't think it's a good idea to give this amount of any of them. We don't generally want departments to have everything they need for an entire round, and it's already possible to get more via lathing and cargo (though the lathe cost might be a bit high right now).

**Comment by mirrorcult** [comment]
smartfridges arent supposed to be for roundstart storage of anything. they're intended to be a place for chemists to put the things they make, this just muddies the water of what everything is supposed to do and oversupplies chemists

**Comment by moonheart08** [comment]
This isn't what smartfridges are for.

**Comment by GoodWheatley** [comment]
Ok after looking at the code for #11506 I'm reasonably sure that once it gets merged I can give the SmartFridge its ss13 behavior. It would be my first time actually coding in C++ so hopefully I don't make the entire codebase explode.

**Comment by mirrorcult** [comment]
we do not use C++ and it shouldnt be reimplemented with restocking

**Pull request closed without merging**
