### PR TITLE
Adds TimedDespawn component to Invisible Walls, nukes DeleteAfterTime

### PR DESCRIPTION
**Pull request by keronshb**
## About the PR 

fixes: #8430

Replaces the component on Mime's invisible walls with the one made in the magic PR.

This also removes DeleteAfterTime.

**Screenshots**

**Changelog**

:cl:

### CODE REVIEW

**Comment by mirrorcult** [comment]
this doesnt remove the old component, just the references to it in yaml

**Comment by keronshb** [comment]
> this doesnt remove the old component, just the references to it in yaml

I couldn't find an Invisible Wall component specifically. I think sloth nuked that one already.

**Comment by EmoGarbage404** [comment]
> > this doesnt remove the old component, just the references to it in yaml
> 
> I couldn't find an Invisible Wall component specifically. I think sloth nuked that one already.

i think she's referring to the DeleteAfterTimeComponent.

**Comment by keronshb** [comment]
> > > this doesnt remove the old component, just the references to it in yaml
> > 
> > 
> > I couldn't find an Invisible Wall component specifically. I think sloth nuked that one already.
> 
> i think she's referring to the DeleteAfterTimeComponent.

I can remove that too but I found the PR that nuked the invisible wall component:

https://github.com/space-wizards/space-station-14/pull/8433/files

**Review by wrexbe — APPROVED** [review]

**Pull request merged**
