### PR TITLE
Individual bar sign entities

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Noticed we had a choice of The Engine Change or a random bar sign spawner.

Made it so every bar sign now has it's own entity so people can make themed salvages and bars that are consistent.

The barsign component for some reason does not pull the localised name and description so these have been manually filled out. Probably affects the desciptions for it being off and EMP'd too.
**Screenshots**

bar signs

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Given it's one entity I think you're better off just VVing the sign as it bloats the spawn menu IMO.

**Comment by Peptide90** [comment]
> Given it's one entity I think you're better off just VVing the sign as it bloats the spawn menu IMO.

Agreed however how accessible do we want the mapping tools? Future categories would cut down bloat otherwise our mapping guide needs some serious cleaning up.

**Comment by moonheart08** [comment]
> Given it's one entity I think you're better off just VVing the sign as it bloats the spawn menu IMO.

This makes it that much more painful when we want to, say.. remove a sign. Now we have to update tons of VV, too. I'm p opposed to VV being the Mapping Solution in general when we can just add another prototype.

**Comment by PJB3005** [comment]
Clearly the solution is to turn the whole prototyping system into a Lisp variant and automatically generate bar sign entity prototypes from the bar sign definition prototypes.

**Comment by wrexbe** [comment]
Talked about this on discord, the new plan seems to be
- Make the barsigns (and potted plants) complete entity prototypes, icons, and all
- Get rid of the randomness, and just use a spawner to do the random.

@EmoGarbage404 wants to look into this.

**Pull request merged**
