### PR TITLE
Reduce the health of some mobs

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR
These mobs have gotten significantly more tanky after their crit states were removed. This brings it back to how it was, Cerbs get to enjoy slightly more hp than before though. 

## Why / Balance
These mobs used to have a crit state that didn't have different sprites. That crit state was removed but their dead hps weren't adjusted. These mobs are now rather tanky and very powerful. Fighting a holocarp was sometimes more scary than fighting a space dragon during a salvage mission for example.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
finally, one spider will no longer be able to tank an entire MK58 mag and kill everyone in the room

**Comment by Equivocateur** [comment]
> finally, one spider will no longer be able to tank an entire MK58 mag and kill everyone in the room

are you a bot

**Review by Partmedia — APPROVED** [review]
This brings their overall HP back to where they were before, so this is fine.

**Comment by JoeHammad1844** [comment]
> are you a bot

que?

**Pull request merged**
