### PR TITLE
bloodred magboots buff

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR

bloodred magboots:
- added jetpack functionality with 2 minutes worth of gas
- can be used for internals like normal jetpacks, but have the air capacity of about a standard emergency air tank
- slowdown 20% (15%) -> 10% (5%)
- price 2TC -> 4TC

all functionalities have been tested and appear to work correctly

**Media**

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Blood-red magboots now slow you down less and have jetpack functionality, but cost more.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This seems really strange. Operatives can just buy a jetpack and boots separately. Combining both of them feels like power creep.

**Comment by Ilya246** [comment]
> This seems really strange. Operatives can just buy a jetpack and boots separately. Combining both of them feels like power creep.

this is meant to make bloodred magboots not just notslips but worse, meant to be an alternative that makes you valid but is stronger
besides, a jetpack needs a free hand, whereas the boots do not need a free hand nor even a free back slot, which is meant to be their advantage

**Comment by Emisse** [comment]
i like this, a silly buff to a niche item but maybe nukies shouldnt start with it if its utility is this good>?

**Comment by Ilya246** [comment]
> i like this, a silly buff to a niche item but maybe nukies shouldnt start with it if its utility is this good>?

they already do not

**Comment by Ilya246** [comment]
verified, only medic starts with bloodred magboots, other nukies start with combat boots
also i believe loneop gets bloodred magboots in the ship's extra bloodred locker
also yeah, the test fail is definitely unrelated to the PR

**Comment by Emisse** [comment]
l;ets try it out

**Pull request merged**
