### PR TITLE
Maintenance loot pool overhaul

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Overhauls the maintenance locker loot pool and gives it a _lot_ more shit. Unfortunately, due to limitations with how SS14's fill system works, certain things you'd expect to be in have been omitted (eg. plushies.)
The chance of previously common items to spawn has also been decreased by a good bit (this is both intentional and a part of the aforementioned limitation with fills.) Important items like emergency spacesuits, tools, and crowbars should still be plentiful.

Due to the overall decreased yield of loot, I would highly suggest mapping more lockers / crates into maint after this.
...also adds maintenance crate spawners to benefit that exact scenario.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The maintenance loot pool has been overhauled and now contains substantially more possible items, good and bad.

### CODE REVIEW

**Comment by potato1234x** [comment]
ClothingNeckRedTie should be ClothingNeckTieRed and ClothingSocksUnderCoder should be ClothingUnderSocksCoder

**Comment by AJCM-git** [comment]
test failures

**Comment by AJCM-git** [comment]
@Flareguy are you coming back to this?

**Comment by Flareguy** [comment]
> @Flareguy are you coming back to this?

I should be able to soon, though I can't really be certain since the PR is a lot to deal with.

**Comment by Flareguy** [comment]
I have decided I will come back to this later

**Pull request closed without merging**
