### PR TITLE
add locale to Shuttle Console Map tab

### PR DESCRIPTION
**Pull request by VlaDOS1408**
## About the PR
added ftl localization for incorrect FTL status of the shuttle

## Media

UIUpdate_FixFTL

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Locale to shuttle-ftl-status-Invalid

### CODE REVIEW

**Comment by slarticodefast** [comment]
I what cases does this even show up as invalid? Isn't that a dummy state that should never occurr?

**Comment by Aeshus** [comment]
> I what cases does this even show up as invalid? Isn't that a dummy state that should never occurr?

It shouldn't occur, but I've seen this happen a few times in public games where the shuttle just... vanishes (probably destroyed by meteors).

**Review by Aeshus — APPROVED** [review]

**Review by slarticodefast — APPROVED** [review]

**Comment by MilenVolf** [comment]
Could you please also add localization for buttons above? Like "DOCK", "MAP", etc
image

**Comment by slarticodefast** [comment]
Yeah, those should definitely be localized. But your choice if you want to do that in this PR or a separate one.

**Pull request merged**
