### PR TITLE
Space Sharkminnow

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

The older brother of the space carp, it is more resilient and stronger, but also much rarer. Blood for the shark is not only food, but also a way to heal after a hard fight. Added sharks rare prototype to the random carp spawner in salvage.

<s>Do not carry out mergers prior to the merger of the PR 20692</s>
Going to add a vampirism property to the shark when attacking.
Apparently the PR won't be finalised, so I'm unhooking mine.

## Why / Balance

Intermediate mob between carp and dragon, sometimes you need something stronger than carp. Helps to fill this gap, also has the speciality of healing with the blood of enemies. For this purpose I added separate animal organs of the Bloodsucker.

## Media

изображение

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11

- add: Added space sharkminnow from the carp family.
- add: Added Bloodsucker's animal organs to heal by drinking blood.

### CODE REVIEW

**Comment by BolloTea** [comment]
please make her a spawner for cartographers

**Comment by Nimfar11** [comment]
@BolloTea So there's a spawner. Or do you mean add to the salvage randoms?

**Comment by BolloTea** [comment]
Yes please.  It would be very wonderful.  And sorry, I didn't notice the spawner)

**Comment by Nimfar11** [comment]
> Yes please. It would be very wonderful. And sorry, I didn't notice the spawner)

Done, hopefully the encounter will survive.

**Comment by Emisse** [comment]
I like this, should be good for expedition balance since we don't have to tune up space carps when we could just have these

**Comment by Aisu9** [comment]
tasty new organ for future crew customisation via surgery, me likey

**Comment by CrigCrag** [comment]
as an enjoyer of floating sharks i can say this is pretty awesome

**Pull request merged**
