### PR TITLE
Icarus beam

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR 
Weapon of mass destruction, intended as an alternative to Nuke for a future gamemode or any other purpose.
It appears using a similar algorithm as nukeops ship and targets the center of the grid and also has a lifetime.
Destroys all tiles and entities in a certain radius, as well as burns everyone in an even larger radius.
Have command to spawn to attack specific grid.

**Screenshots**

https://user-images.githubusercontent.com/14136326/178299832-1aab34f0-28be-4ec3-ae84-3192a280649d.mp4

**Changelog**

:cl:
- add: A new way to destroy a station - Icarus beam

### CODE REVIEW

**Comment by mirrorcult** [comment]
yeah, i'm not super on board with these being added upstream, as I don't think we would use it

**Comment by DogZeroX** [comment]
Also, isn't the firing sound from HalfLife 2

**Comment by moonheart08** [comment]
> Also, isn't the firing sound from HalfLife 2

Yyyyou're right.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
Find a new firing sound, ideally not one from SS13, as it's ripped audio.

**Comment by mirrorcult** [comment]
i dont think this will be used upstream

**Comment by GoodWheatley** [comment]
Is there any chance this PR could be reopened? Have an idea for an upstream use.

**Comment by mirrorcult** [comment]
redo the PR and add the upstream use yourself

**Pull request closed without merging**
