### PR TITLE
Coffee will cause you to jitter and stutter at 25u

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Coffee and iced coffee will now cause you to jitter when you drink more than 25u of it in your body, but it doesn't last for long.

## Why / Balance

Minor flavor change for coffee addicts being overloaded on caffeine and being a bit... energetic as they try to chase their addiction

## Technical details

just yml stuff

## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Coffee and iced coffee now makes you jitter and stutter above 25u.

### CODE REVIEW

**Comment by Plykiya** [comment]
not my fail.

**Comment by Golinth** [comment]
> Should we maybe have caffeine as a reagent and have coffee, energy drinks and similar add that to your body (Similar to alcoholic drinks adding ethanol)? There was this PR that got lost in the freeze: #26339

agreed. I think you should make it give you caffeine, and give this effect to that instead.

**Comment by Plykiya** [comment]
zuffering

**Comment by Plykiya** [comment]
jesus christ I just realized they named it "coffeine", like coffee, instead of just caffeine

**Comment by chromiumboy** [comment]
Hey, are you coming back this?

**Comment by Plykiya** [comment]
> Hey, are you coming back this?

I'll just close it and leave the PRs I actually care about finishing open

**Pull request closed without merging**
