### PR TITLE
Anomaly Synchronizer + Signallers tweaks

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Reduced the range of the signaller from infinity to 15 tiles. Added an advanced signaler, with a radius of 50 tiles. 

Fixed some anomaly synchronizer issues. Reduced power consumption and disabled additional anomaly pulses when disconnecting the synchronizer.

## Why / Balance
Continuing the process of improving anomalistics. 

Reducing the radius of the signaller is the right thing to do, I think. In the current version it's just the same as a wall button, but 100 times better because it's portable.
Now the signaller is a portable button within a limited radius. Balance. Signaller was used on not very frequent occasions. Most often it's either a remote C4 burst or APE control. All other cases are usually used almost closely, so they are not affected by this change.

The C4 blast all now requires closer contact with the target (about 1.5 screens), but along with the option of a slightly more difficult to mine advanced signaller (3 screens) it's an honest complication of remote detonation. 

maintaining anomalies is the primary objective of this change. In the current version, scientists often tie APEs to the signaller, and can sit quietly in the department pressing buttons in the inventory. It's clever, but it's not fun.
The signaller will now not work at any distance on the station, and the scientists will have to work a little harder.

Along with the Anomaly Synchronizer buff, scientists now need to set up autonomous anomaly containment circuits, and they become more dependent on the engineering department: without power, anomalies will begin to require the scientists' close attention.

**Changelog**
:cl:
- tweak: Remote signallers are now limited to a 15-tile radius
- add: Added an advanced remote signaler, with a range of 30 tiles.
- tweak: the anomaly synchronizer consumes much less power, and no longer causes the anomaly pulses when powering down.

### CODE REVIEW

**Comment by deltanedas** [comment]
i would rather see a better system for signaller to be a radio transmitter+button in 1 item and use recievers that get linked to things instead of just nerfing the signaller specifically

**Comment by TheShuEd** [comment]
@deltanedas there are still stationary buttons with a 200 radius that cover the entire station.
The idea is interesting, but I think the signal range should be completely redesigned here, if we create transmitters and receivers of signals

**Comment by LankLTE** [comment]
I’ve discussed before how I’m not really a fan of moving Sci further towards just “camp the anomaly all shift” because that’s not really fun for the scientists nor particularly engaging for anyone else. I think nerfing the remote signaler makes that more necessary since there’s no good way to remotely manage an anomaly now without research, which is a shame.

**Comment by deltanedas** [comment]
you still can just link it with buttons + two-way lever

**Comment by TheShuEd** [comment]
I think it's getting a lot harder now, given the frequency of power outages at the station. What are you suggesting? @LankLTE

**Comment by VektorZ1** [comment]
Sounds like a nice change, making things a bit more complicated
Also, speaking of signaller It would be really cool to have a signaller with multiple buttons

**Comment by K-Dynamic** [comment]
Cant wait to hear bug reports about signallers not working only to be told they have range limit now :trollface:

**Comment by TurboTrackerss14** [comment]
Great PR, however while midly out of scope it might be a good idea to give nukies an advanced signaller for super cool and interesting "explode tcomms and rush armory" strats without having to leave a straggler around tcomms due to range limitations

**Pull request merged**
