### PR TITLE
Self-inflicted melee damage and power cables

### PR DESCRIPTION
**Pull request by McFck**
## About the PR

Hitting cables now won't electrocute you. Hitting yourself will inflict 1/5 of the damage, except special damage like welders(can now be specified for the WeaponComponent). Also fixes hitSound for welder when lit. Fixes https://github.com/space-wizards/space-station-14/issues/16593

**Media**

https://youtu.be/-uLQ3h5V7h8
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Server owners can now opt out of reduced self damage or tweak reduced dmg multiplier
- tweak: Lit welder does welder sound
- tweak: Cables do shock damage on destroy, earlier was 0 (Destroying cables without protection WILL electrocute you)
- tweak: Hitting cables won't electrocute you
- tweak: Hitting yourself will inflict 1/5 damage (except welders and lighters)
- tweak: Can't hit yourself without hands(for self-bites scenarios)

### CODE REVIEW

**Comment by McFck** [comment]
> this is a bad change for cauterising since it will only heal 2 bleeding

oh shoot, true. I'll look into it. Maybe some exceptions array or smt idk. I was thinking about making something like exception full damage and exception 0 dmg. But like I can't say which weapon is a Bite and which is something else, cauterising will need it too. Will think about it

**Comment by Arteben** [comment]
Damaging yourself should just be an global option that the server can enable or not. And the electric shock must occur when the cable is destroyed, otherwise the mice will eat all the cables.

**Comment by McFck** [comment]
> Damaging yourself should just be an global option that the server can enable or not. And the electric shock must occur when the cable is destroyed, otherwise the mice will eat all the cables.

That is a good point, will do some changes.

**Comment by McFck** [comment]
thats the closest thing to the rat that can do some damage. And I've made it to take damage.

Анимация

**Comment by McFck** [comment]
Build crashed because of missing variable that is in the separate branch, so don't be disturbed.

**Comment by McFck** [comment]
@metalgearsloth

**Comment by McFck** [comment]
good luck banning contributors just for the hoaxes

**Pull request closed without merging**
