### PR TITLE
Add (basic) tritium-tritium fusion

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR
This PR adds a (real-life-based) fusion reaction, with one new gas: helium.

The new tritium-tritium reaction will produce helium and ~~radiation, when we code it...~~ a tremendous amount of heat, which can be used to power the TEG, completely scorch everything that exists to one side of a passive vent and boil off approximately a station's worth of iron. It'll be triggered at various temperatures ranging from 120000K to 250000K, whenever more than 0.02 mols of tritium have immediate temperatures of 1.12MK.

I originally planned to add more gases, mirroring /tg/based fusion, but decided to keep it simple and have just helium fusion instead. Reviews and nitpicks welcome.

**Media**
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: router
- add: The Nanotrasen Material Science division has resolved our previously leaky pipes into a form that can withstand nuclear fusion, occuring at ~200000K with pure tritium. Critical temperatures depend on mole count.
- add: Galactic stockpiles are short on Helium-4, which will be bought at an astounding price of 40 spesos per mole.

### CODE REVIEW

**Comment by potato1234x** [comment]
hell yeah

**Comment by BasedUser** [comment]
reviewmarked to check the yaml linter

**Comment by Anzarot121** [comment]
I think it costs too much. It's too easy to make and costs 40 credits per mole when the freson is 7.5. Maybe it's better to make it 5 per mole?

**Comment by BasedUser** [comment]
> > I think it costs too much. It's too easy to make and costs 40 credits per mole when the freson is 7.5. Maybe it's better to make it 5 per mole?

> It's too easy to make

counter-question, how much time does it take you to heat tritium to 200000°K and how much tritium can you heat up to that temp?

**Comment by Anzarot121** [comment]
> counter-question, how much time does it take you to heat tritium to 200000°K and how much tritium can you heat up to that temp?

scrubber into the tritium fusion room with a filter for tritium, from the scrubbers into the pump, from the pump into the radiator, from the radiator into the helium gas filter. And put the pipe on top of the filter.

**Comment by Ilya246** [comment]
heating gas to such high temperatures is extremely complicated, more so with higher amounts of gas, so this should be balanced
for comparision:
1mol trit -> 15 to 50mol frezon -> 112.5 to 375 money
1mol trit -> 0.5mol helium -> 20 money

**Comment by BasedUser** [comment]
fuck it

**Comment by Anzarot121** [comment]
I was wrong, I tested. I'm not sure it's even possible to heat the gas up to that temperature in game. The maximum I could get was 100k Kelvin.

**Comment by Ilya246** [comment]
it is possible to heat tritium to absurd temperatures, i've done it, the setup is a little complicated though
image

**Comment by Partmedia** [comment]
The fusion reaction itself seems balanced and reasonably based in reality. However, I think that since fusion reactions can take place in ordinary steel pipes, this heavily skews the risk/reward balance to something that has very little risk compared to the energy output. I could suggest one of:

- Making fusion take place only in a dedicated fusion reactor that is difficult to operate
- Significantly reducing fusion power output and taking the PR as-is

**Comment by BasedUser** [comment]
during a brief #development review it quickly became clear that fusion is ~~just a week away~~ probably incredibly broken considering we're using steel piping to contain megakelvins of temperature

but then again, so do scrubbers in the vast majority of tritium setups - i'll take a look if it's possible to localize this to say, a reactor entity with the /tg/ hypertorus sprite but not actually a hypertorus

**Comment by deltanedas** [comment]
> megakelvins of pressure

:trollface:

pipes inflatables directional windows etc shouldnt be able to contain several GPa of fire

**Comment by TemporalOroboros** [comment]
Honestly, chances are someone is going to add pipe rupturing at some point so that will probably take care of itself.

**Comment by BasedUser** [comment]
ok so torus bad

unless you give it bluespace levels of volume and magnetic containment, which is not happening

**Comment by Partmedia** [comment]
As I've discussed, I don't think this needs pipes bursting due to overpressure to added before this makes sense to add. I'm leaving this open until some progress can be made on the pipe end.

**Comment by BasedUser** [comment]
> As I've discussed, I don't think this needs pipes bursting due to overpressure to added before this makes sense to add. I'm leaving this open until some progress can be made on the pipe end.

All that for a drop of blood?
image
image

**Comment by BasedUser** [comment]
Will be refactored for atmos speedup soon™.

**Comment by Partmedia** [comment]
Seeing that there is an upper limit on gas mixture temperatures, this is going to need a substantial rework (e.g. fusion chamber) to work. Please re-open when you're ready.

**Pull request closed without merging**
