### PR TITLE
Gloves and hats for lawyers

### PR DESCRIPTION
**Pull request by Deenkaide**
## About the PR
Adding gloves and hats for lawyers

## Why / Balance
Because lawyers need hats and gloves

## Media
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
🆑Deenkaide
- add: Gloves for lawyers loadout
- add: Hats for lawyers loadout

### CODE REVIEW

**Comment by Everturning** [comment]
OBJECTION! You add the outlaw's hat, but, does the jury not know that outlaw hats are contraband, and thus antithetical to the concept of a lawyer? Additionally, the other hats just copy over from bartender!

**Comment by muburu** [comment]
> OBJECTION! You add the outlaw's hat, but, does the jury not know that outlaw hats are contraband, and thus antithetical to the concept of a lawyer? Additionally, the other hats just copy over from bartender!

syndicate drip IS considered contraband, but i've very rarely seen it enforced, they'll only confiscate it if they're really REALLY bored.. and i do agree that adding any kind of syndicate clothing to loadouts is a bad idea for non-antag loadouts, keep the drip exclusive for now..

**Comment by B1essedknight** [comment]
Seems the glove variants may slow this one down for now as Scarves tried to do something similar.
https://github.com/space-wizards/space-station-14/pull/27536#pullrequestreview-2032826498

**Comment by Deenkaide** [comment]
> You add the outlaw's hat, but, does the jury not know that outlaw hats are contraband, and thus antithetical to the concept of a lawyer?

I didn't know about that - Fixed.

> Additionally, the other hats just copy over from bartender!

Yes, I didn't add new hats, I added the ones that were in the game.

**Comment by Everturning** [comment]
> > You add the outlaw's hat, but, does the jury not know that outlaw hats are contraband, and thus antithetical to the concept of a lawyer?
> 
> I didn't know about that - Fixed.
> 
> > Additionally, the other hats just copy over from bartender!
> 
> Yes, I didn't add new hats, I added the ones that were in the game.

Fair on both, but i would argue that the lawyer doesnt need these hats. they don't fit with most suits and if they want either of these hats they can just ask the bartender

**Comment by Deenkaide** [comment]
> > > You add the outlaw's hat, but, does the jury not know that outlaw hats are contraband, and thus antithetical to the concept of a lawyer?
> > 
> > 
> > I didn't know about that - Fixed.
> > > Additionally, the other hats just copy over from bartender!
> > 
> > 
> > Yes, I didn't add new hats, I added the ones that were in the game.
> 
> Fair on both, but i would argue that the lawyer doesnt need these hats. they don't fit with most suits and if they want either of these hats they can just ask the bartender

If they don't want the hat, they don't have to take it

**Comment by EmoGarbage404** [comment]
After some review, I'm opting to close this PR for the following reasons:
- The hats added don't fit the style and theming associated with lawyers' outfits. They don't mesh well with the modern formal suits that lawyers have and loadouts shouldn't really contain items that so clearly clash with the rest of the standard equipment.
- The gloves, quite similarly, are quite arbitrary and don't fit. Gloves aren't typically worn with a suit in a formal setting and I think that their addition to the loadout doesn't add much. The specific choices are also quite arbitrary and I really don't see the reason for having them in particular.

If people wish to have these items, they should simply seek them out from various vendors at the start of the round. Loadouts should be reserved for things that are actually specific to jobs and not just random clothing. There's a reason why you can't just equip any arbitrary jumpsuit in a loadout.

Thank you for your contribution, but I'll be closing this PR. Feel free to contribute in the future.
Thanks.

**Pull request closed without merging**
