### PR TITLE
Basic liver mechanism

### PR DESCRIPTION
**Pull request by ike709**
## About the PR 

Adds a mechanism to livers. Currently, they don't do much since neither organ damage nor drunkenness are a thing, so they just metabolize all reagents like in SS13. To futureproof this and give YAML monkeys something to do, `toxin` and `boozePower` have been added and need to be set on reagents where relevant. I'm definitely not doing that in this PR unless a maintainer fusses at me to.

TODO:
- [x] Make livers actually work by bugging Smug to look at this.

**Changelog**

:cl: ike709
- add: Added a basic implementation of livers. They handle reagent metabolization now, but aren't damaged by alcohol or toxins yet.

### CODE REVIEW

**Comment by ike709** [comment]
@DrSmugleaf I tried testing this by setting my hunger to starving and eating a bunch of food, under the assumption that metabolizing the nutrient reagent in the food would fix my hunger. But nothing happened. Any ideas?

**Comment by ike709** [comment]
Apparently the issue is BloodstreamComponent is null...

**Comment by ike709** [comment]
I fixed that. Stomach doesn't seem to be adding reagents to the bloodstream.

**Comment by ike709** [comment]
Stupid thing works now.

**Review by Zumorica — APPROVED** [review]
This code is perfect.

**Pull request merged**
