### PR TITLE
Observation Kit

### PR DESCRIPTION
**Pull request by ERORR404V1**
## About the PR
Adds a new kit that includes syndicate crew monitor, high power cell and security hud disguised as sunglasses.

## Why / Balance
Created to avoid looking for a person in a stupor or looking where the chapter with the desired item is located. You can see the location of security personnel for jokes.

## Technical details
It doesn't change much.

## Media
The price was changed by 4 ТС
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/100093430/a0beb1de-74f9-4b02-a35d-386a2dcf6943

**Changelog**

:cl:

- add: Added observation kit what include syndicate crew monitor and security hud disguised as sunglasses.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
Why not use the spy monitor from the thief instead of creating an entirely new crew monitor copy?

**Comment by ERORR404V1** [comment]
If I'm not mistaken, only a thief has one.

**Comment by Dutch-VanDerLinde** [comment]
I mean like , use the thief spy monitor in the observation kit instead of creating a new item

**Comment by UbaserB** [comment]
how did i never notice this was a PR

**Pull request merged**
