### PR TITLE
Elysium Material & Balancing

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Adds elysium ore, elysium bars, elysium alloy, elysium glass, renames "Ore Processor" to "Refinery" as it has more functions such as creating alloys, adds a shiv and spear for elysium, adds elysium windows. Some balancing to spears, shivs, and captains sword were also added. Also adds a new medicine as well as a deadly toxin. I am currently working on walls and floor, and a pr for a forge allowing creation of metal items, weapons and armor. This pr will additionally include upgrades and enhancements for items and weapons through a new machine. I am also working on a pr that will add a plethora of medicines and toxins that utilize more minerals, and other reagents.

To help show that I am not making empty promises in terms of what I plan on adding, you can find the documentation on what else I plan to contribute to Space Station [here](https://hackmd.io/@DLqZlOrhTv2FMSyXBUUrgA/BJ-8laCP2).

**Media**

Elysium Ore
image

Elysium Ingot
image

Elysium Alloy
image

Elysium Glass
image

Elysium Glass (Refined)
image

Elysium Shard, Shiv, and Crude Spear (Left to Right)
image

Divine Sabre (Not obtainable yet, but will be in a later pr)
image

Elysium Glass Structures
image

Elysium Glass Structures (Reinforced)
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl: Cody ~ Aexxie
- add: Nanotrasen has discovered a new rare resource called Elysium. Elysium Ore can now be mined on asteroids with the improved equipment salvage is given.
- add: After extensive research, Nanotrasen has developed a use for Elysium. Elysium Ore can be refined into ingots, which can be further processed into glass, or alloyed to form an extremely strong metal.
- add: Adds structures such as windows for Elysium.
- tweak: Changes the name of the "Ore Processor" to "Refinery."

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Diff is absolutely cooked

**Comment by Aexolott** [comment]
> Diff is absolutely cooked

Real.

**Comment by Aexolott** [comment]
> Why wasn't this planned and discussed in the discord?

I have talked about it a lot, but never "planned" anything

**Comment by VasilisThePikachu** [comment]
HackMD page is private, you should probably make it public

**Comment by metalgearsloth** [comment]
- This PR scope creeps heavily / has an extremely weird diff, like adding lecter as trash to a food item or other random balance changes and this needs significant pruning.
- Between Uranium + gold + silver they're probably already not used as much as they should be before we need another material IMO.

**Pull request closed without merging**
