### PR TITLE
Prevent dragons from spawning off-station

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

wagoogus

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Dragons no longer spawn off-station.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Isn't this going to spawn them at the center of the grid.

**Comment by Emisse** [comment]
sounds good to me

**Comment by EmoGarbage404** [comment]
> Isn't this going to spawn them at the center of the grid.

No clue. The previous system got grid centers, so this does the same.

**Comment by deltanedas** [comment]
should also make spawner since ai wont place rifts, on low pop this is especially important

**Pull request merged**
