### PR TITLE
Adds emergency nitrogen lockers

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Does what it says on the tin: adds emergency nitrogen lockers, for nitrogen-breathing species. They contain nitrogen tanks (who could have guessed.)

Being that N2 breathing is supposed to be a meaningful gameplay handicap, and these have significantly less loot compared to O2 lockers anyways: **these are intended to be mapped much less frequently then normal emergency lockers.** They should probably almost always be in public areas & scattered about in maint, [judging by how /vg/ distributes them](https://game.ss13.moe/minimaps/images/maps/BoxStation/).

There is currently no wall-mounted variant ~~because I'm lazy~~ because we should probably see if people can responsibly map these first. We don't want them being spammed along every hall.

## Why / Balance
Good QOL for slimepeople, and probably going to end up being a prerequisite for Vox as well (considering /vg/ probably has them for a reason.)

## Media
Content Client_F0ufujWq7i

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added emergency nitrogen lockers. You can scarcely find them in public areas, or scattered around in maintenance tunnels.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
is that just a fire closet with a taped on sign?

**Comment by Flareguy** [comment]
> is that just a fire closet with a taped on sign?

From what I can tell, yes. Pretty funny (and fitting) considering these are mainly found in maint, and have way less compared to O2 lockers.

**Comment by Errant-4** [comment]
> is that just a fire closet with a taped on sign?

I did not notice that but I love the idea

**Comment by Errant-4** [comment]
Is there any way we can make that more obvious, like diagonal single-pixel cellux stripes on it or something

**Comment by Flareguy** [comment]
> Is there any way we can make that more obvious, like diagonal single-pixel cellux stripes on it or something

image

I actually completely forgot to add the tape marks from /vg/'s sprite, oops. 3/4ths is inherinitly is kind of meh for doing stuff like this, but it should still be pretty apparent that it's taped on.

**Comment by Errant-4** [comment]
Hmm wait what's going on here, on the first image in the op, you can actually see the bottom of the fire extinguisher symbol sticking out under the paper. But on this latest image you don't?

**Comment by Partmedia** [comment]
> Being that N2 breathing is supposed to be a meaningful gameplay handicap, and these have significantly less loot compared to O2 lockers anyways: **these are intended to be mapped much less frequently then normal emergency lockers.** They should probably almost always be in public areas & scattered about in maint, [judging by how /vg/ distributes them](https://game.ss13.moe/minimaps/images/maps/BoxStation/).

I feel that the only way to enforce this is to add a "random emergency locker" spawner that randomly selects a O2 locker or N2 locker based on a fixed probability, and then mark O2 and N2 lockers "no spawn".

Besides a spriting issue, what's the difference with filling the contents of the existing locker with an or-group of the nitrogen tank and oxygen tank? Or, why not make both available in the "emergency locker" and simply remove the "N2" from the locker face?

**Comment by Flareguy** [comment]
> > Being that N2 breathing is supposed to be a meaningful gameplay handicap, and these have significantly less loot compared to O2 lockers anyways: **these are intended to be mapped much less frequently then normal emergency lockers.** They should probably almost always be in public areas & scattered about in maint, [judging by how /vg/ distributes them](https://game.ss13.moe/minimaps/images/maps/BoxStation/).
> 
> I feel that the only way to enforce this is to add a "random emergency locker" spawner that randomly selects a O2 locker or N2 locker based on a fixed probability, and then mark O2 and N2 lockers "no spawn".

I've thought about this, and it *is* certainly an option, but it's definitely not one I want to have to resort to. Random spawns for this massively punishes map knowledge. It's probably not going to be great for either O2 breathers or N2 breathers; finding N2 lockers will become very RNG-based, and O2 breathers will have a chance to just randomly have an emergency locker spawn not be useful (which really sucks, because emergency lockers are already pretty niche as-is.)

To mitigate this effect, we could enforce that the N2-or-O2 spawns only get placed in public areas, but I'd rather just see if mappers can be trusted with not spamming N2 everywhere first.
> 
> Besides a spriting issue, what's the difference with filling the contents of the existing locker with an or-group of the nitrogen tank and oxygen tank? Or, why not make both available in the "emergency locker" and simply remove the "O2" from the locker face? This kind of feels a little bloat-y to me.

Along with the issues listed above, having to actually open an emergency locker first to see if it's suitable for you sounds really, *really* annoying.

**Comment by EmoGarbage404** [comment]
> I feel that the only way to enforce this is to add a "random emergency locker" spawner that randomly selects a O2 locker or N2 locker based on a fixed probability, and then mark O2 and N2 lockers "no spawn".

you could do this but i feel like mappers are going to be placing down these kinds of things with a bit more intention than just littering some spawners. Like if you want 2 oxygen and 1 nitrogen, you'd ideally want to map them in a group of 2 and 1 so it looks better. 

You also want to make sure that local sections of the lockers maintain the same distribution as that of the whole station. For example, having 24 oxygen lockers and 6 nitrogen lockers is indeed the 80/20 split, but it's really bad if all the nitrogen lockers are concentrated in one small hallway instead of being dispersed evenly among the rest of the emergency closets.

> Besides a spriting issue, what's the difference with filling the contents of the existing locker with an or-group of the nitrogen tank and oxygen tank? Or, why not make both available in the "emergency locker" and simply remove the "O2" from the locker face? This kind of feels a little bloat-y to me.

the general intent is just to allow mappers to balance the supply of nitrogen tanks and such to a level that's appropriate to the relative amount of crew breathing nitrogen. Additionally, having its own sprite also lets people find it more readily than having to open multiple lockers with only a chance to find it (introduces same issue i outlined above.)

**Review by EmoGarbage404 — APPROVED** [review]

**Pull request merged**
