### PR TITLE
Bruizine recipe: change lith from .9 to 1

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR
bruizine takes 1 lith instead of fucking .9

## Why / Balance

why .9 just why.

## Technical details

y .9

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
no cl weh

### CODE REVIEW

**Comment by Ilya246** [comment]
all chem ratios should be irrational numbers

**Comment by thebadman4662** [comment]
Its not 1 because bruizine does not require heat and Bica can be made to create razorium. If you are not careful you will make it due to leftover 10%, chemists should care what they are adding for at least some advanced chems.

**Comment by deltanedas** [comment]
nullified by chemmaster existing

**Comment by CrigCrag** [comment]
0.9 lithium is intentional to make the recipe slightly more difficult/complicated to make. Chemmaster or not I've seen people discussing their strategies on how to make it safely which i think is infinitely better than just a normal 3 chem reaction

**Comment by Aexxie** [comment]
> 0.9 lithium is intentional to make the recipe slightly more difficult/complicated to make. Chemmaster or not I've seen people discussing their strategies on how to make it safely which i think is infinitely better than just a normal 3 chem reaction 

Doesn't make it more difficult, nor really complicated, just a pain in the ass right now. This sort of thing is fine once we get chem rework but right now it's just an ugly uneven reaction that can be fixed simply by discarding excess. I'd also like to point out that, as it is now, we have no way to define custom amounts in either chem dispenser or chemmaster. It can be reimplemented later and yeah I'd like less even chems eventually but with our current system now is not really the time

**Comment by deltanedas** [comment]
lithium add 50 remove 5
bicar add 50

**Comment by Aexxie** [comment]
> lithium add 50 remove 5
> bicar add 50

That still doesn't change my statement at all.  If we have forced partial units then we need to be able to have custom transfer amounts. Imo it's unreasonable to think that we need this medicine to be special, just follow the format of literally every other chem until all of them are changed or a better solution is implemented. Not even the other new meds use the decimal unit.

**Comment by CrigCrag** [comment]
having every chemical be almost exactly the same is boring especially in a subdepartment with already incredibly low gameplay variation. having to dispose of excess products and be a bit extra careful with how you mix stuff is something new for chem and really not that annoying to deal with compared to other chemical recipes. further standardizing gameplay in a department where the entire gameplay loop is clicking buttons is not good imo.

also, the way you are "fixing" this reaction makes bruizine notably easier to make than the other brute meds, which require heat.

**Comment by Aexxie** [comment]
> having every chemical be almost exactly the same is boring especially in a subdepartment with already incredibly low gameplay variation. having to dispose of excess products and be a bit extra careful with how you mix stuff is something new for chem and really not that annoying to deal with compared to other chemical recipes. further standardizing gameplay in a department where the entire gameplay loop is clicking buttons is not good imo.
> 
> also, the way you are "fixing" this reaction makes bruizine notably easier to make than the other brute meds, which require heat.

the whole system is broken my man, fix it entirely or don't make single special chemicals at all. also we need more items that only mix with heat anyway. heat doesnt fuck up chem gameplay and make it more annoying, and it actually does add more variation. all you did was add more (pointless) clicks that end up being entirely useless because of the already broken system. and again, people can ignore the chem entirely so they do

**Comment by CrigCrag** [comment]
> the whole system is broken my man, fix it entirely or don't make single special chemicals at all. 

bruizine and the reaction work fine, the reaction system isn't broken. and if it is somehow then fixing it is preferable to removing stuff

> also we need more items that only mix with heat anyway. heat doesnt fuck up chem gameplay and make it more annoying, and it actually does add more variation. 

you can add new reagents with heat reactions if you wish, this doesn't mean you have to go to other reagents and make them require heat.

> all you did was add more (pointless) clicks that end up being entirely useless because of the already broken system 

if it's as useless as you claim then it shouldn't make any difference. bruizine is the only chemical that stands out with an odd mix ratio because it's one of the first ones to be added. unless a maintainer disagrees i really don't see an issue with adding slightly more thinking to make more complex reactions instead of just making the steps longer. 

> chem gameplay also isnt "boring" to people who like that sort of production-type gameplay. I haven't met a chemist who didn't avoid bruizine entirely due to this reason.

ive seen several chemists make bruizine just fine so it seems like a skill issue.

**Comment by Aexxie** [comment]
> bruizine and the reaction work fine, the entire reaction system isn't broken, and if it is somehow then fixing it is preferable to removing stuff
"broken" as in its overpowered and is going to be overhauled soon, so just wait

> you can add new reagents with heat reactions if you wish, this doesn't mean you have to go to other reagents and make them require heat.
I would like to see reactions involving cooling, mixing a supercooled chem with a superheated chem, etc but changing to a decimal number is a sad excuse for a change in gameplay.

> if it's as useless as you claim then it shouldn't make any difference. bruizine is the only chemical that stands out with an odd mix ratio because it's one of the first ones to be added. unless a maintainer disagrees i really don't see an issue with adding slightly more thinking to make more complex reactions instead of just making the steps longer.

there is not "slightly more thinking" you just pour shit in a beaker, throw it in a chemmaster, and get rid of the extra (which has no drawback because of the broken system I mentioned before!) all youre doing is making things more complex which is just entirely bypassed with our current system.

> ive seen several chemists make bruizine just fine so it seems like a skill issue.
wouldnt call it a skill issue, just use bicar whitch is a catchall and not have the terrible death chem as well as the extra steps for a relatively boring chemical

**Comment by Aexxie** [comment]
I apologize if I am coming off as heated, I've had to deal with a lot of bullshit today. I think the argument is a bit silly because it doesn't actually make the gameplay more fun, nor does it make it harder or more complicated. It's an inconvenience that just discourages people from using the new stuff. I think the partial units should just wait until the refactor to be implemented.

**Comment by CrigCrag** [comment]
I'll just leave with a bit of design philosophy on why I made bruizine the way it is.

1: 3 new chemicals, making all three the exact same is boring so I made it a point to give them a few different characteristics to reward doctors and chemists who pay that little bit of extra attention.
2: The dumping of excess chems will be more significant once the chem dispenser 1984 happens, which iirc just has a few more requirements before it's ready to go, I don't remember the issue number but chemists won't have infinite elements anymore.
3: The new brute chems are twice as effective as bicaridine at their respective damage type. Bicaridine is simple to make, but doctors and chemists who work with the slightly more complex systems will be rewarded with faster healing speed.
4: Odd ratios like 0.9 allow razorium to be created accidentally, through artifacts, liquid anomalies, or chemical spills. I wanted razorium/bruizine to have this available (since it's rare for chemicals to be heated naturally) without making bruizine be bland and boring to make

**Comment by Aexxie** [comment]
> I'll just leave with a bit of design philosophy on why I made bruizine the way it is.
> 
> 1: 3 new chemicals, making all three the exact same is boring so I made it a point to give them a few different characteristics to reward doctors and chemists who pay that little bit of extra attention.

I'm not saying it's a bad idea, it's just not worth it right now to have the ratios different from everything else when there is going to be a lot of changes in an undetermined amount of time.

> 2: The dumping of excess chems will be more significant once the chem dispenser 1984 happens, which iirc just has a few more requirements before it's ready to go, I don't remember the issue number but chemists won't have infinite elements anymore.

This is exactly part of the rework I am talking about. 

> 3: The new brute chems are twice as effective as bicaridine at their respective damage type. Bicaridine is simple to make, but doctors and chemists who work with the slightly more complex systems will be rewarded with faster healing speed.

Which is cool but at some point (everything I've seen so far) they just mass produce bicar.

> 4: Odd ratios (with no heat) like 0.9 allow razorium to be created accidentally through artifacts, liquid anomalies, or chemical spills, without compromising too much recipe complexity. I wanted razorium/bruizine to have this available (since it's rare for chemicals to be heated naturally) without making bruizine be bland and boring to make

I understand, but making it more boring to make is probably not the solution. It's not even a different step, just more clicks which you already mentioned that you wanted to avoid.

**Comment by thebadman4662** [comment]
> 3: The new brute chems are twice as effective as bicaridine at their respective damage type. Bicaridine is simple to make, but 
doctors and chemists who work with the slightly more complex systems will be rewarded with faster healing speed.

Twice is understatement. 5u of Bica treats 6.(6) puncture/slash/bruise damage. Pun/Lac/Bru heal from 30 to 40. They are very much worth it if you can pay attention while making them and treating patients. You can reduce treatment from few minutes of lying in bed to instantly being sent to nukie front line in best cases and like half minute treatment otherwise tops.

I love those meds though cryo pods are bit sad now as mass brute damage was go to use for them by me usually, you do not always get a clusterfuck of damage types patients for it and caustic can easily be treated with Sig...

**Comment by Aexxie** [comment]
> > 3: The new brute chems are twice as effective as bicaridine at their respective damage type. Bicaridine is simple to make, but
> > doctors and chemists who work with the slightly more complex systems will be rewarded with faster healing speed.
> 
> Twice is understatement. 5u of Bica treats 6.(6) puncture/slash/bruise damage. Pun/Lac/Bru heal from 30 to 40. They are very much worth it if you can pay attention while making them and treating patients. You can reduce treatment from few minutes of lying in bed to instantly being sent to nukie front line in best cases and like half minute treatment otherwise tops.
> 
> I love those meds though cryo pods are bit sad now as mass brute damage was go to use for them by me usually, you do not always get a clusterfuck of damage types patients for it and caustic can easily be treated with Sig...

- 36.75 for a single specific brute (3.5 heal and 10.5 OD)
vs
- 30 for all simultaneously (2 heal and 15 OD)

**Comment by deltanedas** [comment]
up to 30, it will do less if you have a single type

**Comment by Aexxie** [comment]
> up to 30, it will do less if you have a single type

yeah. Thats what I meant.

also the single type thing is where you should use specialized if you have a LOT of it but I feel like not having multiple is rarely the case in combat.

and finally that is also why it restricts you to using bicar. if you use multiple specialized you die worse

**Comment by JoeHammad1844** [comment]
the specialty meds are supposed to be more difficult to make because of how efficient they are

**Comment by deltanedas** [comment]
its also more difficult to use, difficulty to make doesnt really matter at scale since at the end of the day you have a 200u jug of whatever medicine

**Comment by Aexxie** [comment]
> the specialty meds are supposed to be more difficult to make because of how efficient they are

It's still not any more difficult to make. Just a pain in the ass. And again, it's only usable in one situation, and that is that you have a fuck ton of one specific type of damage which almost never happens in combat. Using it to heal a stubbed toe would be a waste.

> its also more difficult to use, difficulty to make doesnt really matter at scale since at the end of the day you have a 200u jug of whatever medicine

That's what it is right now because of infinite chems, hence "let's wait until the overhaul before messing with partial units"

**Comment by Blackern5000** [comment]
I've been playing a lot of chemistry recently and I gotta say I love the odd bruizine ratio, it's one of the only chems I do have to think about making since not only is it an odd ratio, but it also doesn't produce the same amount of chems as you put in so you can't just make 90/100u and dump it into a jug a few times like with all the other chems.

**Comment by EmoGarbage404** [comment]
i think that this weird little quirky chemical is nifty. Like, it's not the most complicated thing to make and the odd ratio doesn't do all that much, but it's more than a lot of other stuff so that's not half bad. It's probably worth keeping until there's some other worthwhile balancing factor.

**Comment by Aexxie** [comment]
> i think that this weird little quirky chemical is nifty. Like, it's not the most complicated thing to make and the odd ratio doesn't do all that much, but it's more than a lot of other stuff so that's not half bad. It's probably worth keeping until there's some other worthwhile balancing factor.

I suppose I just wish either more chemicals did it, or not have it all. I don't like the weird in between.

**Comment by CrigCrag** [comment]
more quirky chemicals coming soon godo

**Comment by Aexxie** [comment]
> more quirky chemicals coming soon godo

Please do. Probably reference this PR as well; it kinda includes reasons as to why it should be included. Definitely look at bicar too, because I still am yet to find any of the new ones used extensively.

**Pull request closed without merging**
