### PR TITLE
bagel update

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-medical overhaul
-skub
image

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
shuttle timers?

**Comment by JoeHammad1844** [comment]
>medical overhaul
>doesn't touch the treatment area

**Comment by Emisse** [comment]
except the treatment area now has shutters, solid doors to block LoS, and another bed

**Comment by Emisse** [comment]
bitch

**Comment by JoeHammad1844** [comment]
*cries

**Pull request merged**
