### PR TITLE
Remove Acidifier from Syndie Uplink and Increase Price to 4tc

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I removed the Death Acidifier Implant from the syndie Uplink and Increased its Price to 4tc

## Why / Balance

The reason for the blacklist is that Nukies and Nukie Reinforcements get a Acidifier in their bag by default so its just trimming bloat from the list.

The Price change is because its an incredibly powerful tool that can relatively silently round remove someone (Unintended use). Only Nukies should buy it if they want more (Literally no reason too, every Nukie and NukieReinforcement gets one for free)

Syndies can still acquire one via Surplus.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Death Acidifer Price 2->4
- remove: Removed Acidifier from Syndie Uplink

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Maybe make acid (or other 'bad') implants DNA-locked to buyer or unable to be used on crit/sleeping/dead people

**Comment by FungiFellow** [comment]
> Maybe make acid (or other 'bad') implants DNA-locked to buyer or unable to be used on crit/sleeping/dead people

I think it still should be used to destroy a body, the price change is just proportional opportunity cost

**Comment by deltanedas** [comment]
people using it as a weapon ive only seen by traitors not ops

**Comment by UbaserB** [comment]
Weirdly enough... #22192

**Comment by Ilya246** [comment]
acidifier's only use as a traitor is killing, for traitors death is usually the end so they don't care about their stuff being stolen

**Comment by QuietlyWhisper** [comment]
Why aren't microbombs also used for this?

**Comment by FungiFellow** [comment]
> Why aren't microbombs also used for this?

So Acidifiers only got introduced due to Flukies dying to Microbomb implant chain reaction.

The Minibomb (The Grenade) is 6tc and can gib several near instantly while having the possibility for offense and being loud.

**Comment by Holinka4ever** [comment]
Powercreeping inside uplink, uh oh.

**Comment by FungiFellow** [comment]
> Powercreeping inside uplink, uh oh.

It's not powercreep when its a direct nerf?

**Comment by Holinka4ever** [comment]
> > Powercreeping inside uplink, uh oh.
> 
> It's not powercreep when its a direct nerf?

I mean acdificier is powercreeping minibomb

At this point, if you wish that people should intend use acidificer as weapon, rename it then

**Comment by FungiFellow** [comment]
> > > Powercreeping inside uplink, uh oh.
> > 
> > 
> > It's not powercreep when its a direct nerf?
> 
> I mean acdificier is powercreeping minibomb
> 
> At this point, if you wish that people should intend use acidificer as weapon, rename it then

I can't throw an acidifier across HoP counter to instantly gib them

**Comment by Holinka4ever** [comment]
> > > > Powercreeping inside uplink, uh oh.
> > > 
> > > 
> > > It's not powercreep when its a direct nerf?
> > 
> > 
> > I mean acdificier is powercreeping minibomb
> > At this point, if you wish that people should intend use acidificer as weapon, rename it then
> 
> I can't throw an acidifier across HoP counter to instantly gib them

Isnt gibbing a lot of peps at once, without having targets on them, a bit of toxic behavior?

**Comment by QuietlyWhisper** [comment]
Acidifer was not intended to gib other people no. It's not a powercreep item, it's being used for a meta that shouldnt exist

**Comment by FungiFellow** [comment]
If common opinion comes to It I can literally just blacklist it from both uplinks and call it a day, Nukies get them by default anyways

**Comment by QuietlyWhisper** [comment]
> If common opinion comes to It I can literally just blacklist it from both uplinks and call it a day, Nukies get them by default anyways

Agreed

**Comment by deltanedas** [comment]
(add to nukie reinforcement bag too)

**Comment by FungiFellow** [comment]
> (add to nukie reinforcement bag too)

Already there

**Comment by FungiFellow** [comment]
So I'm removing them from syndie uplink but keeping them as a possibility in surplus with an increaseed value of 4tc.

The foolish nukie can choose to buy one at a loss if they misplace theirs.

**Comment by K-Dynamic** [comment]
Rip dna-lock acid implanter idea

**Comment by FungiFellow** [comment]
> Rip dna-lock acid implanter idea

If you want it, code it.

**Comment by Kadeo64** [comment]
step one: play passenger as lizard/arachnid
step two: buy overtuned gear (rigged gloves)
step three: get cuffs
step four: instantly stamcrit, acidify, and eat brains with no counter
step five: continue until you run out of TC for acidifier

**Comment by deltanedas** [comment]
just before being beaten unconscious, the head of personnel utters out "help maint" on Common Radio. paramedics and security immediately swarm the lizard/arachnid passenger, and his days of treachery are over

**Comment by Kadeo64** [comment]
> just before being beaten unconscious, the head of personnel utters out "help maint" on Common Radio. paramedics and security immediately swarm the lizard/arachnid passenger, and his days of treachery are over

speaking from experience this never happens

**Comment by keronshb** [comment]
It sounds like what really should happen is -
Acidifier Should be removed
Microbomb should be force implanted on nukies (as requested too many times now)
Microbomb implant explosion radius should be actually 1-2 tiles out.

**Comment by keronshb** [comment]
> > It sounds like what really should happen is - Acidifier Should be removed Microbomb should be force implanted on nukies (as requested too many times now) Microbomb implant explosion radius should be actually 1-2 tiles out.
> 
> Yeah acidifer seems like a skillissue bandaid fix disguised as a rimworld reference now that I think about it. I do think that it should stay for the ninja though because it's not exactly stealthy to explode on death

Don't quote me on this but I think ninja exploding could've been a reference to bosses exploding in Metal Gear/MGS3 when killed.

**Comment by Kadeo64** [comment]
> Don't quote me on this but I think ninja exploding could've been a reference to bosses exploding in Metal Gear/MGS3 when killed.

i'm like 90% sure that the microbomb in the first place was inspired by [MGS](https://metalgear.fandom.com/wiki/Microbomb) but none of the cyborg ninjas ever used a microbomb. if we got a ghost role that shoots bees or a ghost role that shoots poison arrows or a ghost role that shoots a tranquilizer dart from a mosin then the microbomb would be an appropriate reference

**Comment by Kadeo64** [comment]
> Not to go too of topic but in Metal Gear 2: Solid Snake there's a Ninja that explodes on death - https://youtu.be/ea7jY2pCROQ?t=324

I always forget about the MSX games.

**Comment by northerndakotas** [comment]
> step one: play passenger as lizard/arachnid
> step two: buy overtuned gear (rigged gloves)
> step three: get cuffs
> step four: instantly stamcrit, acidify, and eat brains with no counter
> step five: continue until you run out of TC for acidifier

Or, you know, just emag the recycler and do the same to an unlimited number of people by tossing them in the trash without needing cuffs and faster for less TC. If people want to spend a few TC for a quiet gibbing that sounds like a reasonable purchase to me.

**Comment by K-Dynamic** [comment]
> the radio in question:

Don't messages get cut off when you get hit over and over

**Comment by deltanedas** [comment]
ninja having microbomb is a tg terry referen :trollface:

**Comment by FungiFellow** [comment]
> > the radio in question:
> 
> Don't messages get cut off when you get hit over and over

Messages get interrupted if you get stunned while typing or take 10+ damage so the most you would get out is 
Ho-GLORF!! And that has a strong possibility of being ignored

**Comment by Kadeo64** [comment]
> Does the acidifier not leave behind a massive pool of blood? And have a do-after of several seconds? And require the victim to be fully dead unlike the recycler that works instantly at any amount of health? Like I said, a few TC for slightly stealthier gibbing sounds like a fair trade to me.

the "massive" pool of blood is literally countered by a damp rag, and also the victim being fully dead is worse because the acidifer only works if they die after it's been injected, you crit the victim and then inject the acidifer while they're crit, then when they die of bloodloss/airloss/you punching them to death they get instantly permakilled with no evidence at all aside from an easily cleaned blood puddle and a brain that's probably already been eaten

**Comment by northerndakotas** [comment]
> the "massive" pool of blood is literally countered by a damp rag, 

A damp rag? That you have to wring out at least 4-5 times? I think having to spend upwards of a minute or two with first a body and then with the pool of blood is already perfectly risky when you could have just thrown them in the trash in 5 seconds and been nowhere near the body when it gets gibbed.

> Northstars, sus toolbox or minibombs have tradeoffs for gibbing measured by sound or time, acidifers are purchased just for those two factors alone because syndies /suicide when caught

You're willfully ignoring that all of those other things have much more utility than just gibbing. They are weapons that can kill people outright. In the case of northstars and the toolbox, they're not even one time use.

> Oh yeah, acidifer instantly works when they're _critted_

I didn't know this. This seems like a bug since it doesn't work this way with the microbomb implant. Also you contradicted Kadeo so I'm not sure at this point.

> An _implant only intended for captured/crit syndies_ shouldn't be used for silent stealth gibbing of non-syndies (whole idea is kinda ass and screams greentexter)

I wish we had more greentexters then. I'd take a greentexter who uses their uplink in smart ways to kill their targets over a murderboner who emags the recycler and gibs half the station any day. Unfortunately I see the latter all the time.

**Comment by QuietlyWhisper** [comment]
> I didn't know this. This seems like a bug since it doesn't work this way with the microbomb implant. Also you contradicted Kadeo so I'm not sure at this point.

They're the same item but one doesnt have the explosion effect

**Comment by IProduceWidgets** [comment]
I don't think it needs to be removed. All the arguments for removing it seem like malding about stealth.

A price bump seems fine to me since the only concern is syndies using it, though, could also just add more evidence which I think would perform the item enough to make it fine. Maybe with the new gibbing functionality that Jez made which iirc allows giblets when bodyparts gib.

**Comment by QuietlyWhisper** [comment]
I think the actual issue is these items probably shouldnt be able to be used on other people?

**Comment by K-Dynamic** [comment]
Edit: reading through implanter files, acidifiers only work when mobstate is dead, so I will have to go back and correct my statements

> I think the actual issue is these items probably shouldnt be able to be used on other people?

Personally I like clever unintended behaviour, so I would be okay with syndies implanting innocent people to further their objectives

However, acidifiers clean up and delete bodies fully (no body parts or items to hide), and syndies will just reserve more tc instead of not buying it as that utility is too good - no more needing external access or building a secret room

I suggested a DNA-lock for suicide implants at least but that's a wyci

**Comment by Kadeo64** [comment]
> I think the actual issue is these items probably shouldnt be able to be used on other people?

I mean yeah but then there would be no reason whatsoever to purchase the acidifier, because realistically there's no reason to use the acidifier as a syndie unless you're scared about tiders robusting you and stealing your gear. Just removing it from the tot uplink entirely is the best option IMO because like, nobody is using this thing for it's intended purpose outside of nukies.

**Comment by QuietlyWhisper** [comment]
> I mean yeah but then there would be no reason whatsoever to purchase the acidifier. Just removing it from the tot uplink entirely is the best option IMO because like, nobody is using this thing for it's intended purpose outside of nukies.

You're right! There is no reason to purchase it! It's a device made to melt the user's equipment without causing damage to nearby entities.

**Comment by QuietlyWhisper** [comment]
As the creator of the item, with this knowledge, I would've simply not added this item to the uplinks because it's unnecessary.

**Comment by Kadeo64** [comment]
> You're right! There is no reason to purchase it! It's a device made to melt the user's equipment without causing damage to nearby entities. 

If you're going to permakill yourself and destroy your items, I don't see why you would be worried about environmental damage. If anything, the acidifier is just a worse purchase option than the bomb implants because you DON'T get a chance at taking out whoever killed you.

**Comment by FungiFellow** [comment]
Accidentally deleted it.

Its back now

**Comment by Emisse** [comment]
too many comments idc

**Comment by Kadeo64** [comment]
based

**Pull request merged**
