### PR TITLE
Voice Recorder & Audio Cassettes

### PR DESCRIPTION
**Pull request by DrMelon**
## About the PR
Added a voice recorder and playback device that uses analog audio cassettes. Players can record their conversations, up to 60 seconds in real-time length, and store the recordings on the cassettes. Players can toggle between recording and playback. If a message is too long to be said towards the end of the tape, it will be cut off partway through.

## Why / Balance
I envision it being useful for the Detective, Lawyer, and Reporter jobs; being able to record a conversation is a nice little RP feature for situations that those jobs often encounter. The tactile nature of the recorder and the physical cassette recordings make them valuable as evidence and even a useful tool for traitors to mislead people with; a recorded speech by the Captain deployed at the right time might make a difference. 

## Technical details
There are new components:
* CassetteTapeComponent - Manages the physical cassettes and data storage.
* CassettePlayheadComponent - Allows a device to record to and play back from a cassette.
* CassetteTapeSlotComponent - Special slots for tapes. Could be expanded for particular types and formats of tapes (e.g, large physical formats like reel-to-reel recordings).

## Media
Please enjoy this recorded demonstration. Uploaded to YouTube for length.
https://www.youtube.com/watch?v=FMcNt-bxsAw

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None known. 

**Changelog**
:cl:
- add: You can now record your beautiful voice onto an audio cassette. Up to one minute of recording is possible with this incredible technology! Use it to win arguments about things people said behind your back, or sneakily impersonate people with recorded clips of their voice!

### CODE REVIEW

**Comment by Hmeister-fake** [comment]
Would this record the sound around the cassette tape with the voices? Would be pretty fun to use them to document yourself as a reporter or something, record gunshots and explosions and then be able to upload them to the news.

**Comment by DrMelon** [comment]
> Would this record the sound around the cassette tape with the voices? Would be pretty fun to use them to document yourself as a reporter or something, record gunshots and explosions and then be able to upload them to the news.

I think that's a fun idea, definitely - however, since sound effects don't often show their source in the chat, it might be difficult for other players to understand if the explosions and gunfire they are hearing are recorded or not, which could cause confusion. That might be the objective for an antag though, so maybe there's scope to add a "noisemaker" antag tool for distractions if one doesn't already exist.

**Comment by GoodWheatley** [comment]
Good PR, the only nitpick I have is that 60 seconds is incredibly short if you’re trying to record an entire conversation. Maybe add a type of tape that can record for 10 minutes?

**Comment by DrMelon** [comment]
> Good PR, the only nitpick I have is that 60 seconds is incredibly short if you’re trying to record an entire conversation. Maybe add a type of tape that can record for 10 minutes?

Absolutely, it's possible to add more kinds of tape with prototypes - the lengths can be defined there.

**Comment by DrMelon** [comment]
Going to close this one - @Rainfey's version at #22638 has more features and integrates with the game a bit better!

**Pull request closed without merging**
