### PR TITLE
Prayer Fixes

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
- No more ahelp spam (admin chat now)
- Subtle messages fix
- Skub

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
DNM still fixing stuff

**Comment by metalgearsloth** [comment]
> DNM still fixing stuff

too late breaking master

**Comment by Just-a-Unity-Dev** [comment]
> > DNM still fixing stuff
> 
> too late breaking master

so true

**Comment by Just-a-Unity-Dev** [comment]
what the fuck did i do

**Comment by Just-a-Unity-Dev** [comment]
wa

**Pull request merged**
