### PR TITLE
nuke spinny lights

### LINKED ISSUE #18861: armed nuke should get an emergency light
## Description
hiding nuke under items is an incredibly scummy tactic
giving it a small emergency light would mitigate it

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
nuke has a spinny double light when armed

depends on #19314

fixes #18861

## Why / Balance
yes

## Technical details
uses RotatingLightComponent from light refactor/rework

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/3fbe5809-09cf-4870-9fe9-81cfb3abb5a0

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
wont break anything, will just do nothing if a nuke has no PointLightComponent and is armed

**Changelog**
:cl:
- tweak: Armed nuclear bombs now have warning lights. Set off a nuke and watch the light spin!!!

### CODE REVIEW

**Comment by VektorZ1** [comment]
What if you make the rotational speed dependent on the time remaining until the explosion.....

**Comment by deltanedas** [comment]
real

**Comment by Jezithyr** [comment]
Any chance you could update the sprite to have a little spiny red light on it? (To match with the lighting effects?) If not that's fine! This looks really nice :D

**Comment by deltanedas** [comment]
still needs light refactor to be merged + i cant sprite for shit so idk

**Comment by Jezithyr** [comment]
No problem then, once lighting refactor is merged this is good to go :)

**Pull request merged**
