### PR TITLE
HeightComparer is a little faster

### PR DESCRIPTION
**Pull request by wrexbe**
## About the PR
This gets called a lot, so making it faster helps.
It never gets any nulls, so we don't check for that now.
The heights being equal seems common, so it is up front.

### CODE REVIEW

**Review by PaulRitter — CHANGES_REQUESTED** [review]
- what if one is nullable? this will throw
- would comparing references be another fasttrack here?

**Comment by wrexbe** [comment]
@PaulRitter
>What if one is nullable? this will throw
>either way, i'd like an assert or smth in there, its kinda sus

Since it is going to crash if it is null, and tell you with an exception, an assert would be replacing one error for another. The exception being arguably the easier of the two to track down, because of IDE support. The previous behavior would be to eat the null, and keep going, which is worse in comparison. I don't think it will happen though, because the calling code does things that would fail if the array had null Networks.

> would comparing references be another fast track here?~~
Since the majority of them are not going to be the same reference. That means they have to go through an extra check, that will never return true.

> if they are never null, why not just call x!.Height.CompareTo(y!.Height) and be done with it?`
If the numbers are random, this would be about the same as what this code is, but since a lot of them have equal height, the code is faster.

**Comment by Zumorica** [comment]
Any comparison profiles/benchmarks?

**Comment by wrexbe** [comment]
H3 is winning, so I switched the implementation to that one

**Pull request merged**
