### PR TITLE
Adds Chefvend

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
Changelog:

-Adds a Chefvend for kitchens to specifically dispense basic ingredients.
-Removes duplicate ingredients from chef's locker
Screenshot 2022-12-08 150302

**Changelog**

:cl: Velcroboy
- add: added ChefVend

### CODE REVIEW

**Comment by ChilbroBaggins** [comment]
@Cheackraze I'm going to keep the comments specific to the individual machines. Monkey cube is not a bad idea.

This is only meant to get them started before other means of production are ready. So 1 cheese wheel isn't too much imo. But, I could be convinced that the milk and enzyme is enough.

**Comment by Cheackraze** [comment]
> @Cheackraze I'm going to keep the comments specific to the individual machines. Monkey cube is not a bad idea.
> 
> This is only meant to get them started before other means of production are ready. So 1 cheese wheel isn't too much imo. But, I could be convinced that the milk and enzyme is enough.

Ah my bad, apologies.  I just think that since often chefs are played by newer players, I'd rather guide them towards making cheese instead of giving a false impression that it's a base ingredient available somewhere.  The monkey cube thing is similar but also making the chefs kill and butcher their ingredients is funnier

**Comment by moonheart08** [comment]
This needs a unique sprite, it currently looks too much like the dinnerware.

**Comment by ChilbroBaggins** [comment]
I figured keep the departmental vends the same, like how botany does it. 3-4 machines that use the same body but change the graphic in the screen. Otherwise, most vending machines are just recolored versions of the same thing.

**Comment by moonheart08** [comment]
+

> I figured keep the departmental vends the same, like how botany does it. 3-4 machines that use the same body but change the graphic in the screen. Otherwise, most vending machines are just recolored versions of the same thing.

At minimum it's display needs to be visually distinct.

**Comment by ChilbroBaggins** [comment]
> At minimum it's display needs to be visually distinct.

It is. It will rotate between the bag of flour, egg, butter, and enzyme bottle. I don't remember what the dinnerware uses but it should be easy to tell the difference.

**Comment by EmoGarbage404** [comment]
It quite literally looks like the same sprite (the dinnerware) but the dishes graphic was replaced with just an overlay of supplies. I understand they're meant to look similar, but they currently lack visual distinction.

**Comment by ChilbroBaggins** [comment]
How do you feel about this?
image

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
