### PR TITLE
Moved the dollar sign in the cargo UI to the correct position

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
mirror why did you do this it's supposed to be in front of the amount.
**Screenshots**

**Changelog**

:cl:
- fix: The dollar sign in all of the cargo UI is now in the correct position in front of the amount.

### CODE REVIEW

**Review by Mirino97 — APPROVED** [review]
Fucking lmao

**Comment by mirrorcult** [comment]
this was intentional. they're spacebucks not dollars

**Comment by EmoGarbage404** [comment]
> this was intentional. they're spacebucks not dollars

them being placed like that offends every single bone in my body.

**Comment by mirrorcult** [comment]
that is the intention

**Pull request merged**
