### PR TITLE
add syndies+nukies gamemode

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR

adds a gamemode with both syndies and nukies and puts it into secret
weights altered so that the frequency of zombie rounds is unaltered, otherwise makes rounds with traitors and rounds with nukies both more common
probably should be replaced with a better solution regarding combining gamemodes later

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Traitors can now exist along with nuclear operatives.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
isn't this just dynamic?

**Comment by Ilya246** [comment]
> isn't this just dynamic?

yeah, we don't have dynamic yet so this is a workaround, no harm in doing it this way for now

**Comment by Equivocateur** [comment]
I think this would better fit as a "sub-gamemode" rather than its own one. As in there's the base nukies and there's a chance for tots to show up and vice versa.

**Comment by Ilya246** [comment]
> I think this would better fit as a "sub-gamemode" rather than its own one. As in there's the base nukies and there's a chance for tots to show up and vice versa.

as i said, that'd be somewhat of a needless complication considering there'd only be 1 combined gamemode with this PR
a better solution should be used if we get more combined gamemodes, in that case it would actually simplify this

**Comment by deltanedas** [comment]
with ling blob etc making subgamemodes would be way too much work, dynamic is the solution for that

**Comment by EmoGarbage404** [comment]
This is just a shitty workaround for not having dynamic. Are we going to have modes for every permutation of existing gamemodes? 

Even still, is having nukies happening simultaneously with traitors even a good idea? Most of the objectives will be fairly trivial if there's operatives running around to distract security.

**Comment by Ilya246** [comment]
> This is just a shitty workaround for not having dynamic. Are we going to have modes for every permutation of existing gamemodes?

as i said, when we actually have other combined gamemodes, yes, they should use dynamic, but since it's just one right now, it should be fine
> Even still, is having nukies happening simultaneously with traitors even a good idea? Most of the objectives will be fairly trivial if there's operatives running around to distract security.

i don't think that makes it any less fun, traitors will probably deal damage to the crew but they'll be heavily incentivised to fight nukies too, owing to needing to survive or protect other agents

**Comment by deltanedas** [comment]
not to mention the disk objective is hard anti-nukie

**Comment by Mudsson** [comment]
I think having nukies and syndies is a good idea, but if the ops die does the round end? This would kind of make it odd for syndies who have to fight nukies but not kill them to early so they can get their objectives.

**Comment by Emisse** [comment]
readjust the weights to put normal traitor back 0.65, i think this is fine for now given that its literally a few line change

**Comment by Emisse** [comment]
maybe comment to remove it when dynam is implemented

**Comment by deltanedas** [comment]
@Emisse total weight is now 1.05 is that fine or what else should be adjusted

**Comment by Emisse** [comment]
i said to readjust the weights you want them to equal the same

**Comment by deltanedas** [comment]
now adds to 1 again

**Pull request merged**
