### PR TITLE
Make baseball bat crafting require a slicing tool

### LINKED ISSUE #26679: bat should require tool(s) to make
## Description
bat is arguable one of the best melee weapons in the entire game and all you need is 2 chairs and you can make it in a few seconds. its amazing for validhunting or as 0 tc guaranteed weapon/gibbing tool. i think it should take a saw to craft like validhunter sawnoff does since how are you going to glue and sand down a few planks of wood with your bare hands

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Baseball bat crafts now have a midstep where you have to use a knife/shiv/etc to make the bat. You can also pry the wood back from the incomplete bat.

## Why / Balance

Closes #26679

The issue suggested needing a sawing tool, but since the only sawing tools right now are mostly in medical, I made it slicing instead (So you whittle a bat now). This means you can still use something like a glass shiv to make a bat pretty easy.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/32827189/ddbe2136-d649-46e2-b7fa-c26f50ba69cc

## Breaking changes

**Changelog**

:cl:
- tweak: Baseball bats now require a knife to craft

### CODE REVIEW

**Comment by JustSome1Nearby** [comment]
Really good idea, makes a lot of sence to me

**Comment by K-Dynamic** [comment]
I feel it would be better to make it a lathe-only recipe

**Comment by FairlySadPanda** [comment]
You can mass-produce 15-damage-per-swing-with-wideswing mops at the autolathe

**Comment by deltanedas** [comment]
science can still make it

**Comment by IamVelcroboy** [comment]
> > I feel it would be better to make it a lathe-only recipe
> 
> why would nanotrasen put contraband in the autolathe?

Is it really contraband? Or does security just tend to overreact whenever they see a guy with some sports equipment?

**Comment by thebadman4662** [comment]
Its restricted gear but some folks will throw word contraband even at plasma sheet in chef hands.

**Review by keronshb — APPROVED** [review]
A slicing tool is fine. This way you have an extra tool you need while also not making the bat require something ridiculous like an autolathe or med-only tools.

**Pull request merged**
