### PR TITLE
Changes light fixture values

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Ports the values for standard light fixtures from /vg/station. Overall, they're more white, and have higher energy, but a much lower radius.
I am aware that these probably will not perfectly translate 1:1, but the result on devstation looks promising, and the Pow3r hellbug makes this basically untestable without putting in a ton of effort.

## Why / Balance
Current lighting is kind of pissy and dim. It's difficult to describe but, it's definitely not perfect. The dimness especially can have quite and ugly effect.

This should make lighting moodier while making it less pissy.

## Media
**NEW**
image

**CURRENT/OLD**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Changed the lighting temperature.

### CODE REVIEW

**Comment by mirrorcult** [comment]
image

image

on box with new values

**Comment by mirrorcult** [comment]
image
image

bagel

**Comment by mirrorcult** [comment]
more contrast / less monotonous lighting is good

**Comment by mirrorcult** [comment]
> some sections of maps with slightly inadequate lighting due to the radius change but to be expected, its not too prevalent from the maps i tested though
> 

image

okay, core is uhh slightly underlit in some places

**Review by TheShuEd — COMMENTED** [review]
It is necessary to change the PointLightComponent of all PoweredLight proto in the same way. This is to make the lighting on the mapping match the lighting in the game.

**Comment by deathride58** [comment]
These values look incredibly unnatural, as the energy is way, *way* too high for general station lighting. The contrast created by the high energy combined with the low range is enough to cause eye strain in some of the areas highlighted by Mirror's screenshots, and the sheer intensity completely overpowers all forms of smaller light sources, causing well-lit areas to be even *more* monotonous than they are with the current light values on live. We imagine more color-saturated areas probably aren't gonna look pretty either.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Hi. I wrote both /vg/'s and SS14's lighting system. I think I know what I'm talking about when I **veto this PR**.

/vg/'s lighting model does not even *remotely* match the lighting system used by SS14. Blindly copying parameters over, as this PR does, makes *absolutely no sense*.

It is also blatantly clear that this PR darkens lighting in many cases, which means more lights need to be placed by mappers which *significantly* affects performance. No.

Even with all these technical facts, IMO this PR just looks bad. The huge shift in brightness inside a single room caused by the aggressive falloff is bad.

**Pull request closed without merging**
