### PR TITLE
Fix vending machines not requiring money

### PR DESCRIPTION
**Pull request by Slava0135**
## Media

https://github.com/space-wizards/space-station-14/assets/40753025/14cd571a-903d-4f10-b6c1-ac74274b2793

## Breaking changes

**Changelog**

:cl:
- fix: Fixed vending machines not requiring money to buy items!
- add: Crewmembers now start with 300$ in their inventory!

### CODE REVIEW

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I do think vends requiring money would be cool, it should be tied to the ID and by extension, the character, not the vend itself.

**Comment by baddiePRO** [comment]
when I smash em up with a baseball bat, will they spit money out?

**Comment by IlyaElDunaev** [comment]
Where can the players get more money?

**Comment by Slava0135** [comment]
> Where can the players get more money?

vault robbery

**Comment by Hanzdegloker** [comment]
okay but like, eventually actually have a money system based off this maybe?

**Comment by metalgearsloth** [comment]
> i thought 14 wasnt going to have economy

image

**Comment by potato1234x** [comment]
guh

**Comment by TheShuEd** [comment]
I want it in master branch 😢

**Comment by Terraspark4941** [comment]
new meta:
- break machines
- ask cargo for refund
- break refund box with bat
- no capitalism : ]

**Comment by PolterTzi** [comment]
Man, I got worried for a moment there.

**Pull request merged**
