### PR TITLE
Cargo Sale Pallet

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

This makes a terminal that can appraise and sell entities that are sitting on cargo pallets on the same grid as the terminal.  It then spits out a stack of cash equal to the amount sold. Some of the 'future work' mentioned in  #14363.

**Media**

https://user-images.githubusercontent.com/71046427/222880921-51632301-d23e-449f-b462-37781091aa38.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: checkraze
- add: Added cargo pallet console for localized cargo sales

### CODE REVIEW

**Comment by deltanedas** [comment]
this is ridiculously overpowered for things like botany farms which can be fully automated bar picking and clicking sell

**Comment by Cheackraze** [comment]
> this is ridiculously overpowered for things like botany farms which can be fully automated bar picking and clicking sell

this isn't intended to be on the same station, and once again, completely unrelated to this PR. If that's an issue, make an issue post about it.

**Comment by deltanedas** [comment]
oh its very good then i thought it was meant to be inside cargo

**Comment by Cheackraze** [comment]
> oh its very good then i thought it was meant to be inside cargo

nah the eventual idea is that cargo has to go to a depot/outpost to sell their stuff instead of just sending away the shuttle. they'd have to fly there and manually haul their goods onto the pallets, and then bring the cash back on to the station safely

**Comment by Cheackraze** [comment]
i just messed this branch up hard I need to reopen

**Comment by Cheackraze** [comment]
> @Cheackraze do you mind if I salvage this PR upstream

This got

**Comment by Cheackraze** [comment]
> @Cheackraze do you mind if I salvage this PR upstream

I closed this because this branch got cooked for some reason i dont remember. This bit has been merged already #14422. I have the cargo depot ready as well but I will probably have to update the map file to PR it since it's on a branch I haven't updated yet.  I can send you a screenshot when I get home later.

**Pull request closed without merging**
