### PR TITLE
Command and HoS safe locker

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

The command safe, where the most important things lie, is more sturdy and reliable. Just what the command is worthy of. I put the gun in the HoS safe.

**Media**
safe

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar

- add: Added command and HoS safe

### CODE REVIEW

**Comment by asperger-sind** [comment]
The sprite looks so out of place

**Comment by keronshb** [comment]
These are circa 2004-2006 lockers. I was there so I'd know.

Also I don't know if we really need safe lockers to gatekeep objectives. Feels like it doesn't promote the spirit of SS13/SS14.

**Comment by Nimfar11** [comment]
> These are circa 2004-2006 lockers. I was there so I'd know.
> 
> Also I don't know if we really need safe lockers to gatekeep objectives. Feels like it doesn't promote the spirit of SS13/SS14.

I'm going to redo the sprites a little bit now. 
As for the safe, it cracked just as well as the other lockers. It just seems that the HoS locker is overcrowded, and it would be convenient to move some risky things to another place. And as it seems, and the security chief, has to be a little careful.

**Comment by Nimfar11** [comment]
Provided that there is no way to defend against emag, it is more of a decorative defense and a bit of luck for the syndicate. And in some places the safes will be suitable: the vault with the nuclear, the cabinet HoS, perhaps the office of the Detective, if you want, even the office of the Captain. The Captain just has to have a safe for something.

**Comment by retequizzle** [comment]
screams "stuff all the traitory shit in here so if anyone goes for it we KNOW they're a traitor" imo

people are gonna play how they play but the last thing i want to do is encourage metagaming the objectives in such a way that a traitor has no real way to get to them without being outed

**Comment by keronshb** [comment]
It takes 9 hits with an e sword to destroy the captains/other secure lockers and about 3 for regular lockers. This PR makes that take even longer with the specialized lockers. This feels too metagame focused to be added to the game.

**Comment by Nimfar11** [comment]
> It takes 9 hits with an e sword to destroy the captains/other secure lockers and about 3 for regular lockers. This PR makes that take even longer with the specialized lockers. This feels too metagame focused to be added to the game.

It was always possible to reduce the strength of the safe, and where to put it depends on the mappers. I honestly do not remember that such lockers often break, most often it is emag opens.

**Pull request closed without merging**
