### PR TITLE
Extinguisher refactor

### PR DESCRIPTION
**Pull request by alwinnocom**
## About the PR

Refactored code according to code reviewer Deltaneda's recommendation: "a refactor would be a generic toggleable item with verb that isnt hardcoded to be fire extinguisher safety".

## Why / Balance

#20497

## Technical details

No high-level changes. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

There are no changes to Fire Extinguisher. It still works in-game.

Proof:
1. Safety is still on.
image

2. Sprays when safety off.
image

3. Bonfire is weakened.
image

4. Extinguisher is empty.
image

## Breaking changes

None.

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
thats still not generic everything is specific to fire extinguisher, it cant be reused for other things

**Comment by metalgearsloth** [comment]
At the moment this pr doesn't seem to address the code cleanup being requested so I'd suggest asking for further guidance on discord.

**Comment by alwinnocom** [comment]
Okay I'll ask on Discord. Thanks for the feedback.

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/pull/22286#issuecomment-1848936340

**Pull request closed without merging**
