### PR TITLE
Call goat protective services

### PR DESCRIPTION
**Pull request by metalgearsloth**
:cl:
- fix: Reproducible entities now have a capacity in confined areas.

### CODE REVIEW

**Comment by deltanedas** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! i hate animal rights

**Comment by deltanedas** [comment]
ok new cow meta is as follows:
1. have pen A with 4 cows and some kind of automatic offspring funneling
2. have pen B with the rest of them, 4 tiles away
3. repeat for more production

**Comment by mirrorcult** [comment]
animal abuse meta

**Comment by DogZeroX** [comment]
animal abuse peta*

**Comment by metalgearsloth** [comment]
> * have pen A with 4 cows and some kind of automatic offspring funneling
> 
> * have pen B with the rest of them, 4 tiles away
> 
> * repeat for more production

If you manage to do that you probably deserve it at that point.

**Comment by deltanedas** [comment]
cowops12345

**Pull request merged**
