### PR TITLE
No pacifist or blind sec

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

Added TraitRequirement 
~~block sec jobs if pacifist or blindness trait enabled~~
not content implemented 

## Media
image

### CODE REVIEW

**Comment by Plykiya** [comment]
BrigMed does exist sort of as a way for sec offs to function as pacifists, and they can still use batons.

**Comment by BolloTea** [comment]
https://github.com/space-wizards/space-station-14/pull/29932

**Comment by Plykiya** [comment]
> #29932

last I remember of the discussion they really didn't want that to get merged, so it's kind of a toss up at the moment

**Comment by cfif126** [comment]
YOU ARE REMOVING THE ROLEPLAY MECHANICS!!!!!!!!!!!! I WANNA BE A DIONA GOOD COP!!!! REMOVING THE FUN IS NOT AN OPTION!!!!!

**Comment by TheShuEd** [comment]
> YOU ARE REMOVING THE ROLEPLAY MECHANICS!!!!!!!!!!!! I WANNA BE A DIONA GOOD COP!!!! REMOVING THE FUN IS NOT AN OPTION!!!!!

what does this have to do with dionas?

**Comment by BolloTea** [comment]
Do you want to be a good cop?  remove pacifism :trollface:

**Comment by deltanedas** [comment]
blind secoff is basically cooperating with antags without good reason, and pacifist batong might be removed leaving them completely useless

**Comment by BolloTea** [comment]
If PR with batons is accepted, then the Dions in the sec will become useless.  And that's putting it mildly. Again, this PR is aimed at balance, not a dispute about pacifism

**Comment by BolloTea** [comment]
> blind secoff is basically cooperating with antags without good reason, and pacifist batong might be removed leaving them completely useless

Perhaps the idea is better than yours and cannot be conveyed

**Comment by cfif126** [comment]
> > YOU ARE REMOVING THE ROLEPLAY MECHANICS!!!!!!!!!!!! I WANNA BE A DIONA GOOD COP!!!! REMOVING THE FUN IS NOT AN OPTION!!!!!
> 
> what does this have to do with dionas?


Don't forget where i come from, Mr Ed. Pacifist dionas are funny, as well as pacifistic secs - it is a roleplay feature backed up with code

**Comment by BolloTea** [comment]
Does not affect Dion, only the pacifist trait.  Dions without a trait, they have a slightly different code

**Comment by TheShuEd** [comment]
> > > YOU ARE REMOVING THE ROLEPLAY MECHANICS!!!!!!!!!!!! I WANNA BE A DIONA GOOD COP!!!! REMOVING THE FUN IS NOT AN OPTION!!!!!
> > 
> > 
> > what does this have to do with dionas?
> 
> Don't forget where i come from, Mr Ed. Pacifist dionas are funny, as well as pacifistic secs - it is a roleplay feature backed up with code

don't forget what repository this discussion is in. in upstream diones don't have pacifism, and this topic doesn't make sense here

**Comment by TheShuEd** [comment]
> > > YOU ARE REMOVING THE ROLEPLAY MECHANICS!!!!!!!!!!!! I WANNA BE A DIONA GOOD COP!!!! REMOVING THE FUN IS NOT AN OPTION!!!!!
> > 
> > 
> > what does this have to do with dionas?
> 
> Don't forget where i come from, Mr Ed. Pacifist dionas are funny, as well as pacifistic secs - it is a roleplay feature backed up with code

don't forget what repository this discussion is in. in upstream diones don't have pacifism, and this topic doesn't make sense here

**Comment by Sarahon** [comment]
While I dislike the RP implications. I do fine that command being blind (Especially cap) is a real frustrating thing. It's so easy to steal from players with the blind disability.

**Comment by Djungelskog2** [comment]
Blind commands always fun, besides I hate removing disabilities/quirks from roles

**Comment by Golinth** [comment]
One of my favorite captain gimmicks that an admin used to play was a completely disabled old fart, who couldn’t see or walk (I miss wheelchairs) and needed an officer to basically take care of him at all times, in LRP! I genuinely hope this does not extend to command positions as well, otherwise RP moments like this will be completely impossible

**Comment by TheShuEd** [comment]
No, command roles can afford to be blind and still perform their duties. While the security, being blind or a pacifist, simply loses the ability to perform their game role, and in fact, engages in self-antagonism

**Comment by Sarahon** [comment]
> No, command roles can afford to be blind and still perform their duties. While the security, being blind or a pacifist, simply loses the ability to perform their game role, and in fact, engages in self-antagonism

Captain can barely function when blind.

**Comment by Djungelskog2** [comment]
I have some blind characters and people barely notice that your blind if you don't have your waking stick out and have decent map knowledge 

I think it's a skill issue ngl

**Comment by Sarahon** [comment]
> I have some blind characters and people barely notice that your blind if you don't have your waking stick out and have decent map knowledge
> 
> I think it's a skill issue ngl

There's no way you can argue that sec shouldn't be blind because it inhibits their job but then can defend cap being blind when they not only have sec access, but need to make sure nobody gets the nuke disk. And in nukies, they will not see the nukies coming. In fact, they see 0 antags coming as they are blind. Cap and HOP are both popular targets for antags because of their ID, and being blind makes that 100x easier to steal.

**Comment by Djungelskog2** [comment]
> > I have some blind characters and people barely notice that your blind if you don't have your waking stick out and have decent map knowledge
> > I think it's a skill issue ngl
> 
> There's no way you can argue that sec shouldn't be blind because it inhibits their job but then can defend cap being blind when they not only have sec access, but need to make sure nobody gets the nuke disk. And in nukies, they will not see the nukies coming. In fact, they see 0 antags coming as they are blind. Cap and HOP are both popular targets for antags because of their ID, and being blind makes that 100x easier to steal.

The captains job isn't to fight antags
And NT wouldn't be hiring non-security based in their ability to spot terrorists

**Comment by Sarahon** [comment]
> > > I have some blind characters and people barely notice that your blind if you don't have your waking stick out and have decent map knowledge
> > > I think it's a skill issue ngl
> > 
> > 
> > There's no way you can argue that sec shouldn't be blind because it inhibits their job but then can defend cap being blind when they not only have sec access, but need to make sure nobody gets the nuke disk. And in nukies, they will not see the nukies coming. In fact, they see 0 antags coming as they are blind. Cap and HOP are both popular targets for antags because of their ID, and being blind makes that 100x easier to steal.
> 
> The captains job isn't to fight antags And NT wouldn't be hiring non-security based in their ability to spot terrorists

...it's literally their job to keep the nuke disk out of the hands of nukies and direct sec as necessary if needs be. And it not being their job to "fight antags" doesn't mean they don't fight antags. They're literally geared up for exactly that. Why else would cap be provided a sword and laser if to not fight off any potential threats they come across? Not really sure what you mean.

**Comment by Sarahon** [comment]
> > > > > I have some blind characters and people barely notice that your blind if you don't have your waking stick out and have decent map knowledge
> > > > > I think it's a skill issue ngl
> > > > 
> > > > 
> > > > There's no way you can argue that sec shouldn't be blind because it inhibits their job but then can defend cap being blind when they not only have sec access, but need to make sure nobody gets the nuke disk. And in nukies, they will not see the nukies coming. In fact, they see 0 antags coming as they are blind. Cap and HOP are both popular targets for antags because of their ID, and being blind makes that 100x easier to steal.
> > > 
> > > 
> > > The captains job isn't to fight antags And NT wouldn't be hiring non-security based in their ability to spot terrorists
> > 
> > 
> > ...it's literally their job to keep the nuke disk out of the hands of nukies and direct sec as necessary if needs be. And it not being their job to "fight antags" doesn't mean they don't fight antags. They're literally geared up for exactly that. Why else would cap be provided a sword and laser if to not fight off any potential threats they come across? Not really sure what you mean.
> 
> Run for the hills Hos exists You don't have to fight antags Being blind doesn't stop you from being robust if emergencies call for it

>run for the hills
>runs in straight line because you could run into objects otherwise
>runs into a wall because you can't see
>dead

**Comment by Djungelskog2** [comment]
> > > > > > I have some blind characters and people barely notice that your blind if you don't have your waking stick out and have decent map knowledge
> > > > > > I think it's a skill issue ngl
> > > > > 
> > > > > 
> > > > > There's no way you can argue that sec shouldn't be blind because it inhibits their job but then can defend cap being blind when they not only have sec access, but need to make sure nobody gets the nuke disk. And in nukies, they will not see the nukies coming. In fact, they see 0 antags coming as they are blind. Cap and HOP are both popular targets for antags because of their ID, and being blind makes that 100x easier to steal.
> > > > 
> > > > 
> > > > The captains job isn't to fight antags And NT wouldn't be hiring non-security based in their ability to spot terrorists
> > > 
> > > 
> > > ...it's literally their job to keep the nuke disk out of the hands of nukies and direct sec as necessary if needs be. And it not being their job to "fight antags" doesn't mean they don't fight antags. They're literally geared up for exactly that. Why else would cap be provided a sword and laser if to not fight off any potential threats they come across? Not really sure what you mean.
> > 
> > 
> > Run for the hills Hos exists You don't have to fight antags Being blind doesn't stop you from being robust if emergencies call for it
> 
> run for the hills runs in straight line because you could run into objects otherwise runs into a wall because you can't see dead

You arent that blind unless your dam eyes are closed that is 100% a skill issue, don't forget that it's a handicap for a reason too anywho

**Comment by Sarahon** [comment]
> As stated in the stun baton PR (which I strongly disagree with) Pacifist Sec can still perform the main duties that are unique to a SecOff, which is to subdue, cuff and process antags. Will you be a less effective SecOff at killing slimes? Yes. But you can still stun them and still soak up hits while fight-capable crew help.
> 
> This PR limits roleplay roles for the sake of making Sec more homogeneous, which really isn't necessary when you can have an awfully unrobust SecOff with a shotgun, body armor and magboots, and a great robust SecOff with a stun baton, cuffs and a hippocratic oath in the same game.
> 
> I've never played with blindness though so I have no views on that.

If you've ever walked it I tear gas. It's exactly like that but the hr whole round minus the screaming

**Comment by Djungelskog2** [comment]
...you actually have been playing blind characters with your eyes closed?

Blindness is basically just late stage welding blindness

**Comment by Sarahon** [comment]
> ...you actually have been playing blind characters with your eyes closed?
> 
> Blindness (the trait) is basically just late stage incurable welding blindness

I'm talking about the blindness you get after tear gas buddy. It's the same effect as welding burn

**Comment by Djungelskog2** [comment]
> > ...you actually have been playing blind characters with your eyes closed?
> > Blindness (the trait) is basically just late stage incurable welding blindness
> 
> I'm talking about the blindness you get after tear gas buddy. It's the same effect as welding burn

Tear gas gives the the strict monochrome circle around you, welding blindness is the weird Ripple-mist effect

You said they were the same thing pal

**Comment by Cadunkus** [comment]
From a realism standpoint (don't start debating me about the cartoon logic present in the game), Nanotrasen wouldn't hire someone as a security officer if they're incapable of handling the equipment. Even though you could _mechanically_ be a blind or pacifist secoff, it's kinda anti-immersion.

Police usually have baseline [vision standards](https://www.ojp.gov/ncjrs/virtual-library/abstracts/police-vision-standards) they need to meet.

**Comment by SlamBamActionman** [comment]
I want to also add that disabling pacifism from Security won't stop roleplayers from roleplaying pacifism if they so choose. Like what is functionally different if I choose to put away my mk47 and combat knife and never activate harm mode?

Want to be a blind SecOff? Spend a minute starting and cancelling welding in maintenance.

**Comment by TheShuEd** [comment]
We debated and discussed for a long time, and decided that a better solution would be to add a warning window similar to the window when selecting the vox race, that such combinations of roles and traits will lead to a more difficult game.

However, the ability to limit role selection based on traits will remain in the game code for forks

**Comment by lzk228** [comment]
selfmerg :trollface::

**Comment by SlamBamActionman** [comment]
> selfmerg :trollface::

Like Ed said in their previous reply, this was discussed internally. Pretend another maintainer posted what Ed said if it helps.

**Pull request merged**
