### PR TITLE
Slight buff for Engineering Hardsuits for eyes

### PR DESCRIPTION
**Pull request by KaiShibaa**
- Engineering Hardsuits given eye protection against welder blinding

Oof owie my eyes

### CODE REVIEW

**Comment by Peptide90** [comment]
I mean it makes sense, but does it make sense for balance? I thought the idea was forcing them to wear welding goggles so they can’t wear sunglasses or a HUD.

**Comment by KaiShibaa** [comment]
I've seen that the meson

> I mean it makes sense, but does it make sense for balance? I thought the idea was forcing them to wear welding goggles so they can’t wear sunglasses or a HUD.

I've seen that the mesons (engineering goggles) do work against the welding blindness effect. However it's not readily available for engineers. I either could've added the mesons to the engineer tool vending or allowed the hardsuits with helmet on to prevent the blindness.

**Comment by metalgearsloth** [comment]
Doesn't ss13 have welding goggles?

The hardsuit probably shouldn't be able to do absolutely everything.

**Comment by Emisse** [comment]
theyre in engi vend i think

**Comment by KaiShibaa** [comment]
> theyre in engi vend i think

I checked and yeah they are there. 


> Doesn't ss13 have welding goggles?
> 
> The hardsuit probably shouldn't be able to do absolutely everything.

I agree then after noticing the goggles in the vend. Maybe perhaps having the goggles in engineering lockers as well?

**Comment by Emisse** [comment]
engi vend is readily available, imo it should either be one or the other so we dont have an over abundance of them. dont want to oversaturate the amount of goggles/weld masks available

**Comment by KaiShibaa** [comment]
> engi vend is readily available, imo it should either be one or the other so we dont have an over abundance of them. dont want to oversaturate the amount of goggles/weld masks available

Agreed. Now that I think about it, having them in lockers would make it fewer than the engi-vends. I only put out the PR because people seem to forget about the goggles being able to protect your eyes.

**Comment by mirrorcult** [comment]
i dont want to oversaturate but TBH there isn't quite enough yet

**Comment by Emisse** [comment]
we could add welding masks to atmodrobe if theyre not already there yet? instead of adding more to locker fills

**Comment by KaiShibaa** [comment]
> i dont want to oversaturate but TBH there isn't quite enough yet

Could maybe add more than the 4 inside the engivend. 

> we could add welding masks to atmodrobe if theyre not already there yet? instead of adding more to locker fills

Checked, there's no welding masks or goggles inside the atmodrobe. Could also do that

**Comment by KaiShibaa** [comment]
I'm thinking about upping the 4 to 5 at least from the engivend and having a few goggles/masks in the atmo one.

**Comment by Peptide90** [comment]
Atmos techs do welding now? Yous will need to decide if they deal with the hull or just with life support.

There is a specific welding supplies locker, stick masks in there with a probability for goggles since they’re more OP. Keep mesons in the vendor and up it to 5 (I never knew mesons protected from welding? They were for rads and seeing through walls).

**Comment by HoidC** [comment]
> Atmos techs do welding now? Yous will need to decide if they deal with the hull or just with life support.
> 
> There is a specific welding supplies locker, stick masks in there with a probability for goggles since they’re more OP. Keep mesons in the vendor and up it to 5 (I never knew mesons protected from welding? They were for rads and seeing through walls).

If you want to mess with pipes you need to weld to deconstruct

**Comment by Peptide90** [comment]
> > Atmos techs do welding now? Yous will need to decide if they deal with the hull or just with life support.
> > There is a specific welding supplies locker, stick masks in there with a probability for goggles since they’re more OP. Keep mesons in the vendor and up it to 5 (I never knew mesons protected from welding? They were for rads and seeing through walls).
> 
> If you want to mess with pipes you need to weld to deconstruct

Added an edit, anyway give them like 3 pairs of goggles or masks then, don’t want every grey and their dog welding.

**Comment by Emisse** [comment]
we have no rpd so atmos techs use the welder arguably more than engis

**Comment by Elijahrane** [comment]
stop buffing hardsuits

> There is a specific welding supplies locker, stick masks in there with a probability for goggles since they’re more OP. Keep mesons in the vendor and up it to 5 (I never knew mesons protected from welding? They were for rads and seeing through walls).

because they aren't mesons, and people have said there's no desire to port mesons as they exist in SS13.


> i dont want to oversaturate but TBH there isn't quite enough yet

Currently:

Atlas: 16 roundstart welding masks or goggles, 6 engineers -- 2 2/3 per eng.
Bagel: 32 roundstart welding masks or goggles, 7 engineers -- 4 4/7 per eng.
Box: 36 roundstart welding masks or goggles, 8 engineers -- 4 1/2 per eng.
Lighthouse: 18 roundstart welding masks or goggles, 8 engineers -- 2 1/4 per eng.
Marathon: 32 roundstart welding masks or goggles, 10 engineers -- 3 1/5 per eng

etc, you get the point

**Comment by retequizzle** [comment]
pretty sure it's already been said but gonna say it anyway

hardsuits don't need this, there's plenty of shit available on literally every map to prevent eye damage from welders, and the last thing we need to do is make hardsuits intrinsically protect against more things than they already do

**Pull request closed without merging**
