### PR TITLE
Create a new ghost role that allows ghosts to possess some lizard plushies

### PR DESCRIPTION
**Pull request by 3nderall**
## About the PR

This PR adds a new variant of the lizard plushie that ghosts can possess. This plushie cannot move and can only speak (not limited like animals). All speech is accompanied by a Weh! sound.

## Why / Balance

I wanted to add more ghost roles and saw a video of someone pretending to be a plushie with a chameleon projector and thought this would be funny and fit in with the spirit of space station 14

## Technical details

This PR adds a new entry to the grand lottery to have a 1 in 100 chance to spawn a possessed lizard plushie
It also changes the way bulk lizard plushie crates work, but it appears to be unchanged to players. This allows me to add a 1 in 10 chance to spawn a possessed lizard plushie when a crate is bought.
These crates are the only way to obtain a possessed lizard plushie

## Media

unknown_2024 08 18-22 58
unknown_2024 08 18-22 58_1
unknown_2024 08 18-22 59
unknown_2024 08 18-22 59_1

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The plushie factory seems to have been infiltrated by Nanotrasen's enemies and have trapped innocent souls within some of the lizard plushies. If any of these plushies are discovered, please report them to your local chaplain for an exorcism.

### CODE REVIEW

**Comment by lzk228** [comment]
\>give any item a ghost role
\>call it possessed
\>profit :trollface:

**Comment by 3nderall** [comment]
> >give any item a ghost role >call it possessed >profit :trollface:

When the wehpocalypse comes, I am making sure I will be spared

**Comment by slarticodefast** [comment]
There is this PR allowing PAIs to be put inside plushies, which has the some effect of the plushie being able to talk.
#30805

**Comment by 3nderall** [comment]
> There is this PR allowing PAIs to be put inside plushies, which has the same effect of the plushie being able to talk. #30805

These two systems together could create some funny rp where the pai is "inside" the plushie's head.

And does the pai system change the sound of the pai to match the plushie? Like how the plushie in this pr makes a weh! sound when talking?

**Comment by Emisse** [comment]
i dont think this is needed, and if admins want to do shenanigans they can just create ghost role in one button. I think a better solution would be something like the pai pr mentioned before.

**Comment by TheShuEd** [comment]
Agreed with Emisse
Meh

**Comment by TheShuEd** [comment]
also, it has been discussed more than once that cluttering the tour with uninteresting options without gameplay is a bad idea, and we, on the contrary, try to remove such roles

**Pull request closed without merging**
