### PR TITLE
Removes the Straylight SMG

### LINKED ISSUE #1880: Straylight gun in-hands are broken.
Straylight only displays one in-hands sprite: 
imagesa

### PR DESCRIPTION
**Pull request by SweptWasTaken**
We have too many SMGs and this one looks and has stats almost identical to the C20-R.

It'll be in the RSI-dump.

This will close #1880

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
image

They look almost IDENTICAL. I'm all for loads of Dakka but this gun is literally a carbon copy of the C20-r without a stock.

**Comment by SoulSloth** [comment]
Then why not remove the C20-R?

**Comment by SweptWasTaken** [comment]
> 
> 
> Then why not remove the C20-R?

C20-R looks cooler imo

**Comment by unusualcrow** [comment]
idk i kinda like the smg

**Comment by metalgearsloth** [comment]
you could always change the stats, I threw random numbers in there to begin with.

**Comment by SweptWasTaken** [comment]
I'm changing the stats by deleting it.

**Review by Zumorica — CHANGES_REQUESTED** [review]
Removing what little content we have seems like a *great* idea to get a finished game! Good job, Swept.

**Comment by RemieRichards** [comment]
That's... not a great argument.
1 gun isn't going to finish the game.

**Comment by SweptWasTaken** [comment]
> Removing what little content we have seems like a *great* idea to get a finished game! Good job, Swept.

It is a carbon copy in all but name of another SMG. Honestly, I was planning on adding it back at a later day as a "folded stock" sprite for the C20-R. 

However I am removing it now. I don't know why everyone's all of a sudden crying over a single SMG. I added a custom sprited, unique looking rifle the other day so I think removing this for now is a good tradeoff.

**Comment by Zumorica** [comment]
> I added a custom sprited, unique looking rifle the other day so I think removing this for now is a good tradeoff.

Sure, I'll retract my statement and give you that

**Review by DrSmugleaf — APPROVED** [review]

**Comment by DrSmugleaf** [comment]
It was good 
image

**Pull request merged**
