### PR TITLE
Make mime stamp silent

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Makes mime stamp silent
## Why / Balance

`# TODO`
## Media

https://github.com/space-wizards/space-station-14/assets/124214523/96de3466-0dfd-4d2a-a18f-904516961d9f

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Mime's stamp is silent now!

### CODE REVIEW

**Comment by UbaserB** [comment]
pretty based

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Just make the mime stamp null instead, seems like a waste of a prototype.

**Comment by lzk228** [comment]
> Just make the mime stamp null instead, seems like a waste of a prototype.

it cant be null

**Comment by EmoGarbage404** [comment]
> it cant be null

you changed the value to be nullable in this pr. For the mime stamp prototype, just have `sound: null` and it should just work.

**Comment by lzk228** [comment]
ok it can

**Comment by EmoGarbage404** [comment]
> ok it can

you need to add back the change to allow the stamp sound to be nullable

**Comment by lzk228** [comment]
> > ok it can
> 
> you need to add back the change to allow the stamp sound to be nullable

i checked again with new changes and it works like on related video

**Comment by lzk228** [comment]
bruh, linter tweaking

**Pull request merged**
