### PR TITLE
Adds .001 chance for vending spawners to spawn mimic

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Does what title says.

## Why / Balance
This PR might have a .001 chance of being accepted but I think it could be funny if it is. 😃

## Technical details
n/a

## Media
n/a
- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**
n/a

### CODE REVIEW

**Comment by UbaserB** [comment]
why do i feel like this is a really funny addition. Statistically, can you calculate how many rounds it takes before one of these appear based on the average of 1 hour shifts on LRP?

**Comment by IamVelcroboy** [comment]
Would be based on how many spawners ar on any given map

**Comment by EmoGarbage404** [comment]
> is the mimic AI even functional still lmao

no, or at least not the original one.

**Comment by IamVelcroboy** [comment]
Test fail talkin about vox legs n shit... Ignoring.

**Comment by Partmedia** [comment]
It looks to me like the mimic AI is working, so I intend to merge this.

https://github.com/space-wizards/space-station-14/assets/3229565/e3eb0fa8-7249-44e0-a5f7-744b83c32146

**Comment by metalgearsloth** [comment]
This seems like it should be an event like all other mob spawns, no?

It might inadvertantly affect spawns where you do not want taken over.

**Comment by IamVelcroboy** [comment]
I don't think it needs an event. It's funny because it would spawn where a vending machine normally would. What event would it even be? It's really just meant to be a simple random thing that takes players off guard. 

>It might inadvertantly affect spawns where you do not want taken over.

I guess I don't quite understand what you mean here? Mimics don't currently have ghostTakeover or sentience chance. Plus it's considerably rare.

**Comment by metalgearsloth** [comment]
Events can be centrally managed, if extended or Dev map gets run it won't have a chance of deciding to randomly kill people and being a pain in the ass.

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/issues/23703 because this will need fixing.

**Pull request merged**
