### PR TITLE
Crate buff (again)

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Commit says it all.
Increases flat reductions by 1 so knives and spears no longer break crates.

No changelog because I want people to suffer in game trying and not realising it will not break. There are still things that will break it so don't cry.
**Screenshots**

**Changelog**

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
making crates unbreakable was bad for cargo mains enough, now they'll have to suffer trying to break a crate open with knife???? pure evil, very funny

**Comment by Peptide90** [comment]
> making crates unbreakable was bad for cargo mains enough, now they'll have to suffer trying to break a crate open with knife???? pure evil, very funny

Yep. I'm fine with high level stuff breaking crates. In 13 that was essentially a mining mech with a drill otherwise non antags were not getting into crates, as it should be.

Now I forsee QM just asking for access from HoP but this is intended for MRP and situations where people RP anyway.

**Comment by Peptide90** [comment]
> This change is gonna be painful but overall it's probably for the best in the long run.
> 
> Except one thing: salvagers need lasers just to do their job remotely safely. It's a death sentence otherwise. So it's awkward for them to have to ask permission and hope sec bothers to help them do their job.
> 
> There was talk in Discord recently about adding back the proto-kinetic accelerator which in our case would only do damage in the vacuum of space and with limited range. That'd practically solve the issue of it being used against crew, meaning salvagers could spawn with one.

Yep gonna have to cooperate with other depts if they want legal weapons.

PKA was on my to do list but it's a long list so people will just have to cope and figure it out.

**Comment by mirrorcult** [comment]
> There was talk in Discord recently about adding back the proto-kinetic accelerator which in our case would only do damage in the vacuum of space and with limited range. That'd practically solve the issue of it being used against crew, meaning salvagers could spawn with one.

i absolutely don't want the PKA to be added tbh

**Comment by mirrorcult** [comment]
i was considering giving salvages machetes instead of knives (+5 damage) but otherwise they need to figure out how to ask people for help instead of going in solo and getting juked by ticks

**Pull request merged**
