### PR TITLE
Improve fax menu

### PR DESCRIPTION
**Pull request by VlaDOS1408**
Subdivision of: https://github.com/space-wizards/space-station-14/pull/33632 pr

## About the PR

Improved the fax menu. Now it doesn't look so scary in Russian localization.

## Why / Balance

It was the essence of pure terror

### Before
<details>

<details>
<summary>on RU locale</summary>

image
</details>
</details>

### After
<details>

</details>

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Fax UI Menu little reworked
- fix: Fix fax UI menu resizable

### CODE REVIEW

**Comment by slarticodefast** [comment]
Small request: Could you reorganize the buttons a little so they are better grouped by their purpose?

- Move "Print File" to "Copy" and "Send"
- Move "Refresh" to the receiver of the fax
- Standardize their size

Small Photoshop mockup:
391141400-551d0ed7-3bea-469b-98f8-75c02991326e

**Comment by IProduceWidgets** [comment]
Does this effect the admin fax ui?

**Comment by VlaDOS1408** [comment]
> Does this effect the admin fax ui?

Of course not, it's a completely different UI.

**Comment by slarticodefast** [comment]
I looked at it again and this does not seem to implement the requested changes yet.
Currently it looks like this:
grafik
But a better layout would be this in my opinion:
391162573-c238c24c-619c-455b-b391-2498f9dc630c
Could you make it look like that?

**Comment by VlaDOS1408** [comment]
> I looked at it again and this does not seem to implement the requested changes yet. Currently it looks like this: grafik But a better layout would be this in my opinion: 391162573-c238c24c-619c-455b-b391-2498f9dc630c Could you make it look like that?

Of course they are not implemented, they look bad. They are illogical and look crooked. I didn't just show 2 states in the screenshot - everything is active and open for the first time.

**Comment by slarticodefast** [comment]
> Of course they are not implemented, they look bad. They are illogical and look crooked.

What about them is illogical in your opinion?
My reasoning for moving them is:
- The "Refresh" button should be next to the list of fax receivers because it refreshes that list. Otherwise you would not know what it will refresh.
- The "Print File" button is next to "Copy" and "Send" because those are the three functions the fax machine has. The "Print File" button has nothing to do with the "Refresh" button, so they should not be grouped together.

**Comment by VlaDOS1408** [comment]
> > Of course they are not implemented, they look bad. They are illogical and look crooked.
> 
> What about them is illogical in your opinion? My reasoning for moving them is:
> 
> * The "Refresh" button should be next to the list of fax receivers because it refreshes that list. Otherwise you would not know what it will refresh.
> * The "Print File" button is next to "Copy" and "Send" because those are the three functions the fax machine has. The "Print File" button has nothing to do with the "Refresh" button, so they should not be grouped together.

image
khm
I'll just remind you what happened before.

The function of printing a local file has NOTHING to do with the paper in the tray. And if you transfer the update of the recipients to where you want, then the window will look clumsy, since now there are 3 beautiful lines of the same size. Now these elements are grouped according to the principle of "Miscellaneous". If you do it the way you want, the window will look overloaded and clumsy. In general, I can'T do it the way you want. Yes, maybe it would be more logical to some extent (the second, and the first is only indirectly), but it will be less beautiful, but I still want it to be pleasing to the eye, not more logical. Compare my version (updated by the way) and yours. Do you really want to tell me that yours looks better? Thank you, I hope you either changed your mind or you found a better solution.

**Comment by eoineoineoin** [comment]
Slarticodefast is correct here. The UI elements which have related functions should be beside each other. _You_ know what every button does because you made the UI, but consider a player who might be looking at this UI for the first time - for example that player will see a "Refresh" button which is somehow connected to "Print File," so they will wonder what relationship those functions have with each other, when in reality, those two functions are unconnected to each other.. In Slarticodefast's mockup, the "Refresh" button is beside the list of destinations because it refreshes that list. I think it could be improved even further, but it's a great suggestion. Here's a short article about this design concept with links you can use to learn more: https://lawsofux.com/law-of-proximity/

On a non-tehcnical level, your comments feel a little aggressive. Please bear in mind that everyone on this repository is a volunteer and is working in their free time to make the game better. I appreciate that English may not be your first language, but please consider toning down the language - if you're going to insult volunteers who are trying to help, I think you'll find that people will not want to work with you, no matter how good your contributions are.

Finally, your original PR description contains "Now it doesn't look so scary in Russian localization" - it would be good to know what the problem is so that we could learn to avoid making mistakes which cause problems for translations in the future.

**Comment by VlaDOS1408** [comment]
> Slarticodefast is correct here. The UI elements which have related functions should be beside each other. _You_ know what every button does because you made the UI, but consider a player who might be looking at this UI for the first time - for example that player will see a "Refresh" button which is somehow connected to "Print File," so they will wonder what relationship those functions have with each other, when in reality, those two functions are unconnected to each other.. In Slarticodefast's mockup, the "Refresh" button is beside the list of destinations because it refreshes that list. I think it could be improved even further, but it's a great suggestion. Here's a short article about this design concept with links you can use to learn more: https://lawsofux.com/law-of-proximity/
> 
> On a non-tehcnical level, your comments feel a little aggressive. Please bear in mind that everyone on this repository is a volunteer and is working in their free time to make the game better. I appreciate that English may not be your first language, but please consider toning down the language - if you're going to insult volunteers who are trying to help, I think you'll find that people will not want to work with you, no matter how good your contributions are.
> 
> Finally, your original PR description contains "Now it doesn't look so scary in Russian localization" - it would be good to know what the problem is so that we could learn to avoid making mistakes which cause problems for translations in the future.

1. Was I rude in the message above?
2. Here's what's on RU localization now:
image

3. Who would have any questions about the "Update" button in this place? I took it, pressed it, and saw that the recipients had been updated, that's it. What are the questions? Are you really serious now, do you want me, for the sake of a little more, just minimally more, logic, to rape this window? Are you sure you want to see this button there for the sake of beauty? I would be happy to put this button somewhere there, but there are no options in my head how to do this without messing up everything to hell. Here, look how it is now, how the hell can I put this button there without messing up anything? If this window was wide by default, then I would have no questions, I would just shove it to the right of the list and combine them using styles, but this is not the case. The window + is square, the list of recipients here is the very thing whose width shrinks the entire window, I can't put it horizontally, and if vertically, it will ruin clear lines, turning them into the devil knows what. If I do as you want, the window will be scary. This will be the same fax 2.0 with crooked buttons. And besides, should I remind you where this button was before me? Near the paper type change button and the send button, damn it!

So I made a couple of options. Are you saying that at least one of them looks better than my version? Only the latter looks more or less (apart from this inappropriate third button from the bottom), but I remind you that in other languages this construction will become so wide that you can die of horror. I spent 25 minutes by the way.

<details>
<summary>Variant's</summary>



### ---


### ---



### Before:


</details>

It looks bad. As a novice designer (We are currently studying FIgma on the 2nd course), my eyes are leaking out.
That's just the last option looks good, but again:
<details>
<summary>Click</summary>

### With the third variant

image

### With the my


</details>
No, I don't mind if you offer me an option on how to kill 2 birds with one stone, but for now I'm saying it looks bad, it's better now. Thanks.

**Comment by VlaDOS1408** [comment]
Here are more options. But then the lower panel becomes somewhat overloaded (as in the version with three buttons).
<details>


### ---

### ---



### Before:


</details>

**Comment by VlaDOS1408** [comment]
In principle, of the alternative options, this one looks good:
But there's this little, smelly button that's kind of off-topic.
image

**Comment by VlaDOS1408** [comment]
Well, I'm waiting for what you tell me and all that.

**Comment by slarticodefast** [comment]
Personally I still think the Refresh button should be best placed next to the receiver. But we can wait for someone else to chime in for that.

Thanks to eion for putting what I was trying to explain into technical terms.

**Comment by VlaDOS1408** [comment]
Well, that's what I might need to do there or something.

**Comment by VlaDOS1408** [comment]
> Personally I still think the Refresh button should be best placed next to the receiver. But we can wait for someone else to chime in for that.
> 
> Thanks to eoin for putting what I was trying to explain into technical terms.

Which option do you want me to implement?

**Comment by eoineoineoin** [comment]
Yes, ideally, the refresh button wouldn't be necessary at all, would certainly be an improvement if it could be removed. However, the paper type and print file button are still separated. I think this is closer to what a user would find more intuitive, but maybe needs headers to distinguish the "fax" controls from the "print" controls:



And of course, if we wanted to avoid bikeshedding over this, we could just fix the issue when the window is resized - that's a one-line diff.

**Comment by eoineoineoin** [comment]
I made a quick edit to your branch to demonstrate how the UI could be laid out grouping the controls by function.

**Comment by VlaDOS1408** [comment]
Ok

**Comment by Everturning** [comment]
why are all the PR author's comments marked as abuse tf?

**Comment by slarticodefast** [comment]
> why are all the PR author's comments marked as abuse tf?

They were blocked from the org for behavior in various PRs, even after already being warned by a moderator.
I'm not sure what this means for their PRs because those have been good changes. In this case the suggestion for the UI @eoineoineoin made is a good solution in my opinion. Eoin, could you maybe make a PR for that? While crediting the changes VlaDOS made of course.

**Comment by eoineoineoin** [comment]
That's unfortunate; their behaviour may not have been very good, but it does seem they were genuinely trying to make some improvements. I'd be happy to put the work in to polish and finish their PRs, since they fix issues in non-English builds.

In terms of this one, what would your preference be for how to get it in? Make a new PR, or push to this branch (not sure I have the permissions to do this, so you might have to do the push). I've pushed that change to https://github.com/eoineoineoin/space-station-14/commit/8899af2c0ad2a9c918c2250b37f310956cdf8c63 I still think it could be improved, maybe some headers on each section or something, but it's definitely an improvement on the current UI.

**Comment by slarticodefast** [comment]
Easiest would be to make a new PR, but make sure to keep the previous commits so that VlaDOS gets contributed for their work.

**Comment by TheShuEd** [comment]
Due to the author being banned from the repository, we will be closing this PR. Other contributors may continue the work by opening up a new PR. Should the author successfully appeal the ban, the PR may be re-opened.

**Pull request closed without merging**
