### PR TITLE
Bread dog

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Add brother of cak - breaddog.

**Recipe:**
time: 15
  reagents:
    Cognizine: 5
  solids:
    FoodBreadSausage: 1
    OrganAnimalHeart: 1
    FoodSpaceshroomCooked: 1

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/fa50befc-dd7d-41a9-a9f1-950fa6d3378c

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Edit:
new bark accent added:
image

**Changelog**
:cl:
- add: Added brother of cak - bread dog! 5 cognizine, sausage bread, animal heart, cooked spaceshrooms and 15 second in microwave = bread dog.

### CODE REVIEW

**Comment by UbaserB** [comment]
Love this idea, the accent should probably be different as right now its recognisably the rat king's and this might take away from that.

**Comment by TheShuEd** [comment]
what accent would you suggest?

**Comment by UbaserB** [comment]
The best idea would probably implement a custom accent similar to what cat ears do, but with "woof" and "bark" as suffixes/prefixes.

**Comment by noctyrnal** [comment]
accent should change things like "ah" into "arf" , "oh" into "oof" that type of thing like how UbaserB said

**Comment by TheShuEd** [comment]
it is quite difficult for me to set the right accent as English is not my native language. Can you make a full list of substitutions?

**Comment by TheShuEd** [comment]
image

**Comment by noctyrnal** [comment]
scooby doo accent :godo:

**Comment by TheShuEd** [comment]
hello my little... oh... friend?!?
image

**Comment by noctyrnal** [comment]
now make him carryable :3c

**Comment by TheShuEd** [comment]
he already is.

**Comment by strO0pwafel** [comment]
new! hotdog made from 100% dog! even the bun is made from authentic spessian dogs!

**Comment by Darkenson** [comment]
Oh hey, cute! Reminds me of the sanalites from hololive.

**Pull request merged**
