### PR TITLE
Add the ability for admin ghosts and cyborgs to buckle

### LINKED ISSUE #30898: Borg buckling do-afters don't work
## Description

When you try to buckle someone into a bed or chair as a borg, the do-after will start but not actually do anything.
Like, the do-after literally does nothing. You can see the do-after bar, sure, but it literally does nothing despite starting the do-after with all the correct arguments.

Typically when you start the buckle do-after, you are expecting the BuckleDoafterEarly() checks to be constantly running every tick to try and cancel the do-after, and then once it finishes it'll call OnBuckleDoafter() to actually buckle the person into the chair or bed.

Doing this as a human, that's what happens. But when done as a borg, neither of these do-after functions get called when I set up breakpoints in the code to try and figure it out.

https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs

I honestly have no clue how to debug it from here or how to fix it.

**Reproduction**

**Screenshots**

**Additional context**

### LINKED ISSUE #31109: Aghosts cannot buckle
## Description
title

**Reproduction**
1. try to buckle a mob to a chair/bed/whatever as an aghost
2. they do not get buckled
3. weep

**Screenshots**
https://github.com/user-attachments/assets/58378a95-db7d-4695-bf36-6d8dbe28ae87

### PR DESCRIPTION
**Pull request by Hreno**
## About the PR

It gives the ability for admin ghosts and cyborgs to buckle entities on chairs etc.

## Why / Balance

Fixes #30898
Fixes #31109 

## Technical details

The Buckle component was missing for these two entities.

## Media

[Peek 2024-08-17 22-20.webm](https://github.com/user-attachments/assets/043c436d-405f-473e-b95b-521848561360)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Can you buckle borgs to beds now?

**Comment by Brandon-Huu** [comment]
[Screencast from 08-17-2024 04:54:07 PM.webm](https://github.com/user-attachments/assets/78554965-36f4-41e0-bd31-7ef7e35e0860)

**Comment by Brandon-Huu** [comment]
Current master branch:

[Screencast from 08-17-2024 04:56:47 PM.webm](https://github.com/user-attachments/assets/fa32058d-7de7-48cf-b27b-efe128f0b141)

**Review by Brandon-Huu — CHANGES_REQUESTED** [review]
Just make it so the person doing the buckling doesn't need the buckle component.

**Comment by Hreno** [comment]
Hm, I see. This is going to be more tricky then.

**Comment by Plykiya** [comment]
oh, this was the issue? let me know if you want me to push the fix for it

**Comment by Hreno** [comment]
I'll close this.

@Plykiya Feel free to tackle this in a way Brandon-Huu suggests, as I don't have enough knowledge of the codebase yet.

**Pull request closed without merging**
