### PR TITLE
Change aghost speed 

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR

Change aghost walk (Shift) speed from 8 to 50.

## Why / Balance

Admins needs fast sprint. Slow walking doesn't make sense.
This will save mappers and admins from a routine task. I'm sure everyone is changing their speed in components.

## Technical details

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ko4erga
ADMIN:
- tweak: Changed aghost walk speed.

### CODE REVIEW

**Comment by lzk228** [comment]
not player facing changes, so you need to add `ADMIN:` in your CL like this
```
:cl:
ADMIN:
- tweak: text
```

**Comment by TurboTrackerss14** [comment]
Moving speed faster than 30 can cause PVS lag (said by a maintainer who I have since forgotten)
Most admins use a script similar to 
vvwrite /player/TurboTracker/AttachedEntity/MovementSpeedModifier/BaseSprintSpeed 30
vvwrite /player/TurboTracker/AttachedEntity/MovementSpeedModifier/BaseWalkSpeed 6
To set their speeds faster. 

Probably best not to jump it this fast.

**Comment by IProduceWidgets** [comment]
I also don't think this is a good idea because it flips the fast/slow walk binds. That's fine if you're doing it from a script because you know (presumably) what you're doing when you run it. It's very unintuitive as a default though.

**Comment by metalgearsloth** [comment]
As TT said this has been raised a lot before, I don't want PVS exposed to worse pop-in.

**Pull request closed without merging**
