### PR TITLE
Singulo drink - speed up animation

### PR DESCRIPTION
**Pull request by Jackrost**
Spin

**Media**
Old
ss14_drink_old
New
ss14_drink

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Do any of the other drinks use delays.

**Comment by AJCM-git** [comment]
like 30 so

**Comment by Jackrost** [comment]
> like 30 do

Is some of them are slow also?

**Comment by metalgearsloth** [comment]
If they were ported in the same pr it's very likely.

**Pull request merged**
