### PR TITLE
Added more pride cloaks and made them craftable at the uniform printer

### PR DESCRIPTION
**Pull request by TherapyGoth**
## About the PR
I added more of the pride flags as cloaks in game and made them all craftable 

## Why / Balance
I added more flag cloaks to be in line with the trans flag cloak.
I made them craftable to make them more accessible.

## Media
 
image

**Changelog**

:cl: TherapyGoth, SUPERFREAK
- add: added more pride cloaks!
- tweak: Pride cloaks can now be printed at the uniform printer!

### CODE REVIEW

**Comment by Eden077** [comment]
Incredibly fantastic change, I love wearing the vampire cloak so this is a big step up

**Comment by CatMagic1** [comment]
I thought the vampire cloak was an egg for like a full 5 rounds when I first saw it

**Comment by lzk228** [comment]
we already have pins, so is those capes really needed?

**Comment by deathride58** [comment]
Honestly there's not enough pride accessories. This PR is a good step forward!

**Comment by rosieposieeee** [comment]
> we already have pins, so is those capes really needed?

You mean the pins that are like, two pixels and get covered by everything?

This is a great addition! Disappointed with those who gave a thumbs down.

**Comment by Subversionary** [comment]
> Country capes would be cool too. People wearing french capes = revs confirmed.

Le bloat

**Comment by CatMagic1** [comment]
>Le bloat

Not more of bloat than this :trollface:

**Comment by NancokPS2** [comment]
This would be the only casual wear craftable at an uniform printer. Which imo makes no sense.   
Uniform printer is meant to be only for job related clothing.

**Comment by M3739** [comment]
Might be good also being added to the clothing vendors, if so desired, probably with all of the other scarfs,

Pride stuff is cool. Maints loot is also a good way to go about it.

Neat!

**Comment by metalgearsloth** [comment]
Agreed on not adding it to uniform printer, would be better as maints loot but fine as is after conflict resolve.

**Pull request merged**
