### PR TITLE
Items will display size when examined.

### PR DESCRIPTION
**Pull request by Varen**
## About the PR
Adds a line on every item that displays its size when examined. 

## Why / Balance
It's not normally possible to know an item size without it being inside a container. Removing items one by one from your backpack to fit in an item you don't know the size of only to realise it's actually too big to fit in the first place makes people cranky.

## Technical details
Every ItemComponent now adds tacks on its size when the OnExamine event happens.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: Examining an item now shows its size.

### CODE REVIEW

**Comment by lzk228** [comment]
better would be place it always in first line or last, so you don't need to search that

**Comment by Varen** [comment]
> better would be place it always in first line or last, so you don't need to search that

I agree. However I couldn't find a way to do that, since I can't really control in what order the OnExamine events are evaluated, right?

**Comment by deltanedas** [comment]
you can have it run before or after other system

**Comment by Varen** [comment]
> you can have it run before or after other system

If you can give me an idea of how to do that, do tell! I've been unable to find it so far.

**Comment by deltanedas** [comment]
SubscribeLocalEvent(OnWhatever, before: new[] { typeof(SomeSystem) })
or after to be after

**Comment by Varen** [comment]
> SubscribeLocalEvent(OnWhatever, before: new[] { typeof(SomeSystem) }) or after to be after

That'd be great if I was building the stack of systems for a specific thing, but this is in the SharedItemSystem, there's no way for me to know what is down the line, so doing it this way would be a pretty huge unweildy thing that'd break when some new component system gets added, so I don't think it'd fit.

**Comment by metalgearsloth** [comment]
ItemSystem is ubiquitous enough I don't think it's viable to try subbing before / after everything and I think it's up to other calls to do so, unless we added some priority system instead for it.

**Comment by EmoGarbage404** [comment]
> ItemSystem is ubiquitous enough I don't think it's viable to try subbing before / after everything and I think it's up to other calls to do so, unless we added some priority system instead for it.

adding a priority system to examine feels infinitely more sane but i wouldn't say it's necessary enough to block a PR over it.

**Comment by metalgearsloth** [comment]
yeah I think it's fine as is considering it's a bunch of additional work and not changing anything in the PR itself.

**Pull request merged**
