### PR TITLE
New lobby art: Hazard

### PR DESCRIPTION
**Pull request by ERORR404V1**
## About the PR
New lobby art

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added new lobby art (Hazard)!

### CODE REVIEW

**Comment by ERORR404V1** [comment]
The new PR was made because of my mistake in the old one.

**Comment by lzk228** [comment]
thats not even 'art', thats just some sprites put into one scene with some lights and thats all

**Comment by VektorZ1** [comment]
Meh

**Comment by beck-thompson** [comment]
I personally like it! Its interesting and unique.

**Comment by Cojoke-dot** [comment]
Can you use the ss14 sprites at least? The ninja does not even have the right helm

**Comment by Moomoobeef** [comment]
do we have to critique the definition of art? It's creative, I don't see a problem with it

**Comment by TheShuEd** [comment]
Yep, i also don't like it.

**Comment by UbaserB** [comment]
I like the art, but the composition is a bit small imo and some of the sprites aren't wizden (they look like /tg/?)

**Comment by potato1234x** [comment]
i enjoy

**Comment by ps3moira** [comment]
This lobby art's really cool, just needs more clean up and adjustments with composition. Also some sprite changes for the syndicate agent since those formal overalls are being planned to be removed.

**Comment by UbaserB** [comment]
Closed for the feature freeze #27898, comment when you want it re-opened.

**Comment by mirrorcult** [comment]
this is not relevant to the feature freeze dawg

**Comment by Emisse** [comment]
are you still working on this

**Pull request closed without merging**
