### PR TITLE
Revise atmos setup for central command map

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

This PR introduces a mapping change to the central command map such that it is no longer necessary to break down a window to turn on the station's distro loop as an atmos technician.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

New:
image
Old:
image

**Changelog**

Unnecessary as pointed out by lzk228 below. Change is indeed not important to players.

### CODE REVIEW

**Comment by lzk228** [comment]
i think centcomm updates dont need cl

**Comment by TsjipTsjip** [comment]
CL entry removed, thanks @lzk228 !

**Comment by Emisse** [comment]
is this saved as a grid

**Comment by TsjipTsjip** [comment]
> is this saved as a grid

Yeah, it should be. Works without issues on my local environment. No errors in the server console either.

**Pull request merged**
