### PR TITLE
kobolds no longer die at 40 hp

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
they now go into crit at 60 hp and die at 125 hp

## Why / Balance
kobolds shouldnt be as fragile as a mothroach

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
no

### CODE REVIEW

**Comment by UbaserB** [comment]
how much weaker is it compared to a monkey? It's meant to be more fragile.

**Comment by Dutch-VanDerLinde** [comment]
> how much weaker is it compared to a monkey? It's meant to be more fragile.

its the same
Why is it supposed to be fragile anyway

**Comment by Dutch-VanDerLinde** [comment]
> > > how much weaker is it compared to a monkey? It's meant to be more fragile.
> > 
> > 
> > its the same Why is it supposed to be fragile anyway
> 
> so it's mechanically different, otherwise it will be overwhelmingly stronger than a monkey because its much faster AND does more damage.

oh i didnt know they were faster, what about going into crit at 75

**Comment by UbaserB** [comment]
> > > > how much weaker is it compared to a monkey? It's meant to be more fragile.
> > > 
> > > 
> > > its the same Why is it supposed to be fragile anyway
> > 
> > 
> > so it's mechanically different, otherwise it will be overwhelmingly stronger than a monkey because its much faster AND does more damage.
> 
> oh i didnt know they were faster, what about going into crit at 75

Im not sure if you meant died, but if its only 75 then theres basically no point in having a difference. 75 is basically the same as 80.

**Comment by Dutch-VanDerLinde** [comment]
> > > > > how much weaker is it compared to a monkey? It's meant to be more fragile.
> > > > 
> > > > 
> > > > its the same Why is it supposed to be fragile anyway
> > > 
> > > 
> > > so it's mechanically different, otherwise it will be overwhelmingly stronger than a monkey because its much faster AND does more damage.
> > 
> > 
> > oh i didnt know they were faster, what about going into crit at 75
> 
> Im not sure if you meant died, but if its only 75 then theres basically no point in having a difference. 75 is basically the same as 80.

it goes into crit at 40 currently

**Comment by UbaserB** [comment]
> it goes into crit at 40 currently

what are the currently values for monkeys?

**Comment by Dutch-VanDerLinde** [comment]
> currently

100 crit 200 dead

**Comment by UbaserB** [comment]
> > what are the currently values for monkeys?
> 
> 100 crit 200 dead

probably make it make it 60 crit, 100 dead then.

**Comment by Dutch-VanDerLinde** [comment]
> honestly monkeys SHOULD be lower, they're small and don't need 100 hp.

no

**Comment by UbaserB** [comment]
> honestly monkeys SHOULD be lower, they're small and don't need 100 hp.

i agree

**Pull request merged**
