### PR TITLE
Update what package the user should install

### PR DESCRIPTION
**Pull request by LetterN**
## About the PR 
Tells the user what packages to install instead of some vague "FluidSynth or development package of FluidSynth"

### Screenshots

image

### CODE REVIEW

**Comment by DogZeroX** [comment]
I believe average player don't care about this changelog.

**Review by Veritius — APPROVED** [review]
lgtm

**Comment by moonheart08** [comment]
This is distro specific, isn't it? Hence the vague wording.

**Comment by Zumorica** [comment]
This is a bad change, honestly.

**Comment by PJB3005** [comment]
Ideally we would ship the Fluidsynth libraries ourselves, but this is a large component of libraries and it's *Linux* which basically means the thought of getting that to work reliably is making me hate myself.

And then Fluidsynth decided to start doing SONAME bumps over frivolous bullshit.

At the very bloody least we should never be recommending people to install -dev packages because they are inherently an ABI spaghetti mess (and absolutely atrocious about Linux in general).

**Comment by Visne** [comment]
Maybe we should ship SS14 in a Docker container

**Comment by Visne** [comment]
> Somebody *was* working on a Flatpak

I could try it, if you want

**Comment by Elijahrane** [comment]
I've tried it before, flatpak support for dotnet stuff is pretty bad unless something has changed recently. Theoretically you'd only need to flatpak the launcher though?

**Comment by wrexbe** [comment]
Closed. A different approach to the problem is needed.

**Pull request closed without merging**
