### PR TITLE
Store ninja objectives in conditions 2

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

Spider charge progress is now tracked in condition component rather than role

## Media

Peek 2023-10-10 19-05

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
> Spider charge objective is now removed if no valid targets found (making it optional objective for maps)

this was already done via the spider charge target requirement

**Comment by Slava0135** [comment]
> > Spider charge objective is now removed if no valid targets found (making it optional objective for maps)
> 
> this was already done via the spider charge target requirement

I think I didn't work or I haven't tested it beforehand

**Comment by deltanedas** [comment]
definitely did work, if you are on a map with no bombing targets it just didnt give you the objective

**Comment by Slava0135** [comment]
ok

**Pull request merged**
