### PR TITLE
Adds New SMG, Replaces Armory SMG on packedstation

### PR DESCRIPTION
**Pull request by buletsponge**
## About the PR 
Armory inside of packedstation for security department has had the normal SMGs removed. In place 'riot' SMGs have been created which is a normal Drozd but instead have Rubber magazines spawn in them.

**Changelog**

:cl:
- add: Added DrozdRiot
- tweak: Changed packedstation armory to spawn with non-lethal magazines and SMGs

### CODE REVIEW

**Comment by Elijahrane** [comment]
1. Security already has a bunch of nonlethal options, including the extremely effective taser.
2. Security fights opponents armed with fully automatic lethals at least once a round.
3. This encourages sec to more freely distribute the armory guns, and thus lose control of them.
4. Anyone with access to an autolathe who captures a gun can just empty the magazine and reload it with lethal rounds, meaning the SMG is still lethal for anyone except security.

**Comment by buletsponge** [comment]
> 1. Security already has a bunch of nonlethal options, including the extremely effective taser.
> 2. Security fights opponents armed with fully automatic lethals at least once a round.
> 3. This encourages sec to more freely distribute the armory guns, and thus lose control of them.
> 4. Anyone with access to an autolathe who captures a gun can just empty the magazine and reload it with lethal rounds, meaning the SMG is still lethal for anyone except security.

I understand what you are saying, however, I do not agree. On the contrary, Sec forces often times use Lethal force when not necessary. I feel as if the HoS or Captian should have to approve and order gaining lethal means of force before they are able to be implemented. This will promote more non-lethal means over lethal. Having to force sec forces to order lethal weapons will help keep the population alive. Besides, there is still a shotgun with lethal rounds in the armory (Which is usually taken by the Warden, rightfully so.) Besides, this is meant not for patroling but to quel large populations when riots happen (Yes I'm looking at you, Greytide.) 

On top of this, many times I have seen someone in an HoP position simply walk in and take a SMG because they have given themselves Armoury access. This shouldn't be happening because as soon as they are walking around and either they get killed or Atmo goes out (HoP doesn't have a Hardsuit...) suddenly there is an SMG free game for anyone to use. Lethal should be restricted more than what they already are. I personally feel they are far too accessible.

"Anyone with access to an autolathe who captures a gun can just empty the magazine and reload it with lethal rounds, meaning the SMG is still lethal for anyone except security." 
Anyone who captures the gun in the first place would have lethal rounds, so in turn, this is simply adding more steps to stop those who would acquire it, forcing them to put more effort into getting lethal means. Besides lethal should be a last resort option for sec forces anyways.

**Comment by Elijahrane** [comment]
>I feel as if the HoS or Captain should have to approve and order gaining lethal means of force before they are able to be implemented.

This is already the case, unless both are disabled in which case warden is 3rd in line.

>Having to force security to order lethal weapons will help keep the population alive.
Yes, all the alive people thankful I am waiting on cargo to get me a crate while a guy with an LMG is killing everyone on sight.

>This will promote more non-lethal means over lethal.
This promotes taking guns out of the armory because it not being lethal means they're no big deal, right? (Except they are because they can be reloaded with lethal rounds.)

>On top of this, many times I have seen someone in an HoP position simply walk in and take a SMG because they have given themselves Armoury access. 

So Security can arrest them and strip them of their weapons (and probably job after talking with the captain).

>This shouldn't be happening because as soon as they are walking around and either they get killed or Atmo goes out (HoP doesn't have a Hardsuit...) suddenly there is an SMG free game for anyone to use.

This is literally the same line of logic as to why I am against making the SMGs less lethal; they will be taken more and thus lost more.

>Anyone who captures the gun in the first place would have lethal rounds, so in turn, this is simply adding more steps to stop those who would acquire it, forcing them to put more effort into getting lethal means.

????????? What? If capturing a sec SMG is a big deal for you you probably had no access to firearms in the first place.

**Comment by Leander-0** [comment]
I will use examples to explain how this is wrong.

- Cargonia manages to secretly obtain access to a Security ID or any ID that lets them open weapons crates.

from that moment on security will be helpless to defend themselves and the crew from a mass murdering cargonia riot that end with all of sec and command dead with out being able to shoot back.

- Sudden nuke ops take control of cargo 

if any nuke ops manage to kill/take control of cargo the whole station becomes helpless against them because all of them are extremely armed with the best weapons the uplink can provide

- there is an active shooter killing the whole crew

another problem with security needing to ask cargo first for lethal guns is the time it takes for them to first off have the points to order said guns and second the logistics of providing the weapon to whats left of the sec officers if they are not even dead on the first place, a mass shooting are things that can take mere seconds or few minutes, security NEEDS to respond quick because the traitor can escape, steal important access, kill the sec trying to non lethally arrest him.

and about the having to ask cargo for guns what stops the captain, hop or hos to ask cargo at round start to only buy guns instead or the important cargo stuff the station needs like chemical crates, pizza or cows for example. all cargo money would be wasted only on guns the armory should have on the first place.

**Comment by Leander-0** [comment]
Also, as of right now security already has many non-lethal ways to deal with arrests we have flashes, flash grenades, batons and tazers, also at least packed station armory already comes with beanbag shotgun rounds (non-lethal) but most of the people don't use them mostly because when you shoot someone with non lethal rounds most of the people don't note the difference between lethal and non lethal rounds so the first thing people think when you shoot a running clown with non lethal rounds is that you are killing them and all people will go against you.

there is still some non lethal ways that haven't been implemented like the pepper spray and the bolas.

instead of removing the ways sec has for defending itself it would be better to add more non lethal ways to dealing with arrests.

**Comment by buletsponge** [comment]
Understandably, I can see the point of view both of you take on this, however, I stand by the changes I put forth for review. The vast majority of the scenarios being put forth are dire situations, which, might I add, are also able to be countered by non-lethal SMG rounds. I even dare say it is _more effective_ as **Rubber rounds will knock someone down faster than lethal** rounds which have to accumulate damage to kill someone. Not only that, but in the end, using less means of lethal appropriation will in the end create more roleplay. I personally would rather be captured and executed than simply outright killed in a firefight. More roleplay = better times. 
This is all in a effort to promote more opportunities for roleplay instead of simple firefights. The game's premise is not about winning, its about roleplay at its core and to argue against it simply for the fact of Security not being armed to take down others with guns is silly. Besides, HoS starts with his own SMG, as well as the Warden with a shotgun that is already two individuals with lethal. If The Captain or HoS has a dire need for lethals, then they can order them. Thats why there is Cargo department.

Rubber rounds are better. Rubber rounds keep people alive, which creates more roleplay.

**Comment by Leander-0** [comment]
> This is all in a effort to promote more opportunities for roleplay instead of simple firefights. The game's premise is not about winning, its about roleplay at its core and to argue against it simply for the fact of Security not being armed to take down others with guns is silly.

Traitors don't care for roleplay on Low RP servers. 

ask anyone on the discord about being a traitor and most of them will say how nice it was to obtain the GREENTEXT, just read the stories channel.

> If The Captain or HoS has a dire need for lethals, then they can order them. Thats why there is Cargo department.

as i already said what if the cargo guys are traitors. they can simply no deliver the guns or use them to kill everyone even if they are not cargonia.

going on a tangent, if you care about more rp and non boring rounds remember that traitor engineers can use the singulo or a plasma canister to end the round in 10 minutes because the station ends irrevocably destroyed.

You are trying to apply High RP server thinking and changes to Low RP servers.

**Comment by Elijahrane** [comment]
> Understandably, I can see the point of view both of you take on this, however, I stand by the changes I put forth for review. The vast majority of the scenarios being put forth are dire situations, which, might I add, are also able to be countered by non-lethal SMG rounds. I even dare say it is _more effective_ as **Rubber rounds will knock someone down faster than lethal** rounds which have to accumulate damage to kill someone. Not only that, but in the end, using less means of lethal appropriation will create more roleplay. I personally would rather be captured and executed than simply outright killed in a firefight. More roleplay = better times.
> 
> This is all in a effort to promote more opportunities for roleplay instead of simple firefights. The game's premise is not about winning, its about roleplay at its core and to argue against it simply for the fact of Security not being armed to take down others with guns is silly. Besides, HoS starts with his own SMG, as well as the Warden with a shotgun. That is already two individuals with lethal. If The Captain or HoS has a dire need for lethals, then they can order them. Thats why there is Cargo department.
> 
> Rubber rounds are better. Rubber rounds keep people alive, which creates more roleplay.
> 
> Edit- Spacing, Wording, Grammer.

All of your examples involve the security officer and the antag. That is 2 people. What about the pile of corpses and deadchat-whining ghosts after the antag and his buddies succeed in killing the entire station because no one can stop them?

**Comment by buletsponge** [comment]
I know how fast a round can end just as well as how long it can last too, but that's not the point being made. This is not to force High roleplay standards, it is simply to promote it more; I don't see the harm in that.



> > Understandably, I can see the point of view both of you take on this, however, I stand by the changes I put forth for review. The vast majority of the scenarios being put forth are dire situations, which, might I add, are also able to be countered by non-lethal SMG rounds. I even dare say it is _more effective_ as **Rubber rounds will knock someone down faster than lethal** rounds which have to accumulate damage to kill someone. Not only that, but in the end, using less means of lethal appropriation will create more roleplay. I personally would rather be captured and executed than simply outright killed in a firefight. More roleplay = better times.
> > This is all in an effort to promote more opportunities for roleplay instead of simple firefights. The game's premise is not about winning, its about roleplay at its core and to argue against it simply for the fact of Security not being armed to take down others with guns is silly. Besides, HoS starts with his own SMG, as well as the Warden with a shotgun. That is already two individuals with lethal. If The Captain or HoS has a dire need for lethal, then they can order them. That's why there is Cargo department.
> > Rubber rounds are better. Rubber rounds keep people alive, which creates more roleplay.
> > Edit- Spacing, Wording, Grammer.
> 
> All of your examples involve the security officer and the antag. That is 2 people. What about the pile of corpses and deadchat-whining ghosts after the antag and his buddies succeed in killing the entire station because no one can stop them?

As far as the piles of bodies go, this is exactly why I am pushing for this change. The number of people dying decreases (Or at least, helps keep the body count lower than normal).
 The examples are not just the antagonist and Security, it is anyone who may get their hand on the weapon in general. Security, Antagonist, or otherwise. As far as no one being able to stop them, I think you _really_ underestimate the power of non-lethal. Regardless of whether non-lethal or lethal rounds are being used, the traitor has many ways of killing everyone, just like you said. 
 The game is filled with many new players, and this can help keep self-antaging as well as security negligence down.

**Comment by Elijahrane** [comment]
The rubber bullets both run out quickly and need to reload and ministun. If the traitor is not followed up on during this time (and the stun length likely isn't enough from usual hallway firefight range) then he will get back up good as new or keep shooting. If, god forbid, you have 2 traitors (or when we get nuke ops in a few months) then it's basically impossible to stop them because they never have to stop and heal or save crit people.

**Comment by TimrodDX** [comment]
As the person who ported Packed, I'd like to weigh in for a moment. On the actual /vg/ map, there is only a single real gun in the armory - that being the shotgun. The HoS doesn't even have a gun on that map: that's something I put in because it's on Saltern.

image

The armory has three Energy Guns, two Laser Rifles, and the Ion Rifle. The Drozds I put in there are a stopgap because energy guns aren't yet in the game and lasers probably need a re-work due to doing basically no damage and only having eight shots. 

The answer here is to port Energy Guns, buff the damage and shot count on energy weapons, and then make it clear to Security that they're meant to use the non-lethal modes.

**Comment by PaulRitter** [comment]
ngl i dont see the issue with this if rubber rounds even knock people down quicker than regular bullets. havent checked the code yet so i cant speak on it

**Pull request merged**
