### PR TITLE
Long human ears

### PR DESCRIPTION
**Pull request by Sarahon**
## About the PR
Added long human ears for us wanting to play as weird humans.

## Why / Balance
For RP reasons and generally to just provide some more variety to humans. It also allows people to add additional head(top) cosmetics, like on other races, while keeping the cat ears meme alive.

 My PR before also wasn't really explained properly. Wanted to remove a file also (not sure if it worked but we'll see. with the program issues I'm not entirely sure how to fix it without just making a new PR)

## Technical details
Originally the "Head(top)" category for humans was completely disabled, even if you added an overlay, it wouldn't show. I just added the same line other species have.

Decided to add a completely new category to keep the original cat ears meme alive, but also unlock the ability now to add more head overlays to the humanoid characters.

## Media
image
Content Client_FcjDBKtyu3
Content Client_9crSZm8fSt

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: 
- add: Now can add head(top) cosmetics to humanoids and dwarfs.
- add: Added "long ears" for human and dwarf head(top) cosmetic.

### CODE REVIEW

**Comment by Sarahon** [comment]
> This PR looks to be identical to #29985? Just surprised to see it closed and then immediately reopened under a new PR number.

honestly I just can't seem to get the fucking shortcut to delete. I thought it was deleted but it won't go away! how do I remove this stupid file lmfao

**Comment by timurjavid** [comment]
Looks more like elf ears from the sides, which I guess is ok if you're going for like a human/elf hybrid vibe.

**Comment by Sarahon** [comment]
> Looks more like elf ears from the sides, which I guess is ok if you're going for like a human/elf hybrid vibe. Definitely good to add more variety to humans though, they're a bit boring.

I've said it once before and I'll say it again. Not only elves have long ears. In a lot of lore dwarfs will have long ears. I'm not really here to fight people on their stereotypes I just want more cosmetic flares that could make sense in a Sci-fi setting.

**Comment by Sarahon** [comment]
> Looks more like elf ears from the sides, which I guess is ok if you're going for like a human/elf hybrid vibe. Definitely good to add more variety to humans though, they're a bit boring.

Possibly the colour gradiation but I can't do much about it. The way the shader handles them especially makes it look a weird from up close, at least colour wise. They blend a lot better with darker skin tones. Size wise, I just wanted them big to be noticeable and not follow the odd trend of having tiny details on already small zoomed out sprites.

**Comment by Sarahon** [comment]
> The long ears don't look right imo, the sprite could definitely be improved.

Possibly the colour gradiation but I can't do much about it. The way the shader handles the colours especially makes it look a weird from up close, at least colour wise. They blend a lot better with darker skin tones. Size wise, I just wanted them big to be noticeable and not follow the odd trend of having tiny details on already small zoomed out sprites.

Though if you mean the side view looking weird, it's because it was between that or making them look very chunky. And I preferred them being pointy

**Comment by SlamBamActionman** [comment]
> I've said it once before and I'll say it again. Not only elves have long ears. In a lot of lore dwarfs will have long ears. I'm not really here to fight people on their stereotypes I just want more cosmetic flares that could make sense in a Sci-fi setting.

That's true, but you *are* PRing them for *humans* too. There are no humans who have ears that extreme IRL, so equating the design to a non-human species is a fair comparison (whether it be elves or otherwise). 

The question then becomes whether humans should be allowed to expand into the role of human-hybrid species. And that's a question for the species- and art team. Personally I like the groundedness of humans in SS14 since that contrasts well with the absurdity of the setting, but that's just my personal opinion. I'm not opposed to adding more customization to humans (I PR'd the human noses) as long as it's within the realm of... well, humans.

For dwarves? Go wild, they're "the" fantasy race.

**Comment by SlamBamActionman** [comment]
The changelog should also reference the change in a standalone manner; "Added my own long ears." doesn't tell a user anything if they read it in the patch notes.

**Comment by Sarahon** [comment]
> > I've said it once before and I'll say it again. Not only elves have long ears. In a lot of lore dwarfs will have long ears. I'm not really here to fight people on their stereotypes I just want more cosmetic flares that could make sense in a Sci-fi setting.
> 
> That's true, but you _are_ PRing them for _humans_ too. There are no humans who have ears that extreme IRL, so equating the design to a non-human species is a fair comparison (whether it be elves or otherwise).
> 
> The question then becomes whether humans should be allowed to expand into the role of human-hybrid species. And that's a question for the species- and art team. Personally I like the groundedness of humans in SS14 since that contrasts well with the absurdity of the setting, but that's just my personal opinion. I'm not opposed to adding more customization to humans (I PR'd the human noses) as long as it's within the realm of... well, humans.
> 
> For dwarves? Go wild, they're "the" fantasy race.

I don't really see why humans can't? If the actual attitude is that humans and other races can't mix is unrealistic. The "irl" argument only works if you are actually considering all the outcomes. And a hybrid-any race is realistic in this sci-fi game. Because there's no reason to believe 2 very humanoid creatures can't mix outside of the devs just claiming they can't with no reason to back it up. Who's to say a dwarf and human can't have made a long eared human in this instance then? They're both basically humans with just different heights.

**Comment by SlamBamActionman** [comment]
I'm not saying that it isn't valid to have humans with non-human features in general, even moreso in a sci-fi setting. There's media that does that and it can work very well to enhance the setting.

But in the same vein there's also media that chooses to limit the sci-fi impact on humans and uses that to enhance the setting too. Again, I think the mundanity of humans contrast thematically with the silly nature of things going on around them and adds to the charm of the game. It's subjective, sure, but it's when it comes to thematic elements such as these subjectivity is what we have to go by.

> It does not "remove" anything or harm anything in the game as ss14 wizden itself clearly does not want to constrict its game to a specific lore right now.

Maybe not lore, but there is clearly an art direction and desire to keep species design to *some* constrained and contained standard. Wizden is fairly conservative with this (seen by all the forks adding a ton more customizability to the base game; CD just added hair for moths), which is why something as big of a departure as adding non-human body features might get some push-back.

Both approaches are valid and can work. But I don't think one is necessarily better than the other, and since humans are right now one of the (if not the only) "grounded" species, I think moving away from that isn't purely a positive. I'd rather see that implemented via other species (again, I think these would make great dwarf ears, since they've already incorporated fantasy elements in their theming).

**Comment by Sarahon** [comment]
> I'm not saying that it isn't valid to have humans with non-human features in general, even moreso in a sci-fi setting. There's media that does that and it can work very well to enhance the setting.
> 
> But in the same vein there's also media that chooses to limit the sci-fi impact on humans and uses that to enhance the setting too. Again, I think the mundanity of humans contrast thematically with the silly nature of things going on around them and adds to the charm of the game. It's subjective, sure, but it's when it comes to thematic elements such as these subjectivity is what we have to go by.
> 
> > It does not "remove" anything or harm anything in the game as ss14 wizden itself clearly does not want to constrict its game to a specific lore right now.
> 
> Maybe not lore, but there is clearly an art direction and desire to keep species design to _some_ constrained and contained standard. Wizden is fairly conservative with this (seen by all the forks adding a ton more customizability to the base game; CD just added hair for moths), which is why something as big of a departure as adding non-human body features might get some push-back.
> 
> Both approaches are valid and can work. But I don't think one is necessarily better than the other, and since humans are right now one of the (if not the only) "grounded" species, I think moving away from that isn't purely a positive. I'd rather see that implemented via other species (again, I think these would make great dwarf ears, since they've already incorporated fantasy elements in their theming).

Then I will say you're(general you're- as in the design philosophy overall) is actively pushing people away from humans and I want them to stop it. The game is meant to be for anyone to be able to RP and have fun and heavily inspires from ss13. Having what would be "unlimited cosmetics" is only a positive and assuming they ever reach the amount of content 13 has, like gene mutations for example then this philosophy flies out the window. If it is to be denied because they do have the same mindset. I think it's a damn shame and I hope for a better mindset in the future. I shouldn't be forced into considering other races just because I want customisability (which tbh, long ears are not at all absurd, humans can be born with pointed ears or huge ears, it's just my version is exaggerated for the purpose that it's a tiny pixel game) in my sci-fi space game with space clowns, talking animals and exploding cats.

**Comment by SlamBamActionman** [comment]
> Having what would be "unlimited cosmetics" is only a positive

Hard disagree. Unlimited cosmetics ruin artstyles and visual cohesion. That's not to say games can't leverage it, but that's difficult as hell and more often than not results in [visual slop](https://www.newgrounds.com/art/view/3dylanstar/sfm-paintover-artstyle-ruining-spy-valve-portrait). Not everyone has a problem with that. But it is definitely a subjective take!

> I shouldn't be forced into considering other races just because I want customisability

I think you are undervaluing the varied looks that exist in the human race Some of those options are currently lacking though (where's my [cool body tattoo cosmetics](https://static.wikia.nocookie.net/obradinn/images/6/68/Maba.png/revision/latest?cb=20201030080944) at?).

>(which tbh, long ears are not at all absurd, humans can be born with pointed ears or huge ears, it's just my version is exaggerated for the purpose that it's a tiny pixel game)

So I did actually google images of pointy human ears before leaving my first comment just to make sure I wasn't making assumptions about how people look. The game and its pixel art style does necessitate exaggerations to some degree, but I find it hard to believe that this
image
was designed to represent [this](https://www.reddit.com/r/mildlyinteresting/comments/aq8yio/i_was_born_with_naturally_pointed_ears/)
image
when this is what the default is:
image

If anything the fact we're working with so few pixels means that even a single pixel has major impact on the visuals, and the PR's proposal has several.

**Comment by SlamBamActionman** [comment]
> Considering I wasn't at all referencing irl persons and doing a mutation, my justification is quite literally, I want the option of huge ears like that. My reference is closer to demons, elves, hobbits, etc.

I replied in the context of irl people because you said that the ears in this PR are not far off from how irl humans can have pointy ears in your parenthesis. I agree that treating this PR as adding a non-irl-human cosmetic option to the human species in the game is the best way to evaluate it.

> Tattoos are rarely seen and again, are hard to differentiate between a tiny pixel base. And also are not for everyone. My character wears 2 sleeve tattoos and you will not see them.

Tattoos were just an example of a cosmetic that is currently lacking from the game. We're missing piercings, earrings, different body sizes and things that are more impactful like limbloss (though bandages is a nice close second) just to give some examples. My point wasn't tattoos specifically, just that humans have plenty of potential customizable options without going into the realm of non-human features. 

> And we'll have to agree to disagree on the cosmetics. If you can explain to me what exact style ss14 is going for, then maybe I can reply to you in a more educated manner. But nothing about long ears somehow ruins the cohesion of the game. You're being a bit dramatic if that's actually what you personally think. (not to say you do think that either, but it's quite an interesting thing to mention in the middle of disagreeing with the long ears concept)

Look, long ears won't make me go "Ah fuck SS14's visuals are ruined" (the comment about "ruining arstyles" was in reference to "unlimited cosmetics", i.e. opening the doors wide open to basically any and all cosmetic changes regardless of theme). Like I said in my previous reply, giving humans inhuman features in a sci-fi setting is totally valid and can work, and if SS14 changes into that then it'll probably end up being fine. But having humans constrained to human features _is_ also a valid artstyle choice that has its own benefits too, and I'm expressing a subjective preference for it.

**Comment by Sarahon** [comment]
> > Considering I wasn't at all referencing irl persons and doing a mutation, my justification is quite literally, I want the option of huge ears like that. My reference is closer to demons, elves, hobbits, etc.
> 
> I replied in the context of irl people because you said that the ears in this PR are not far off from how irl humans can have pointy ears in your parenthesis. I agree that treating this PR as adding a non-irl-human cosmetic option to the human species in the game is the best way to evaluate it.
> 
> > Tattoos are rarely seen and again, are hard to differentiate between a tiny pixel base. And also are not for everyone. My character wears 2 sleeve tattoos and you will not see them.
> 
> Tattoos were just an example of a cosmetic that is currently lacking from the game. We're missing piercings, earrings, different body sizes and things that are more impactful like limbloss (though bandages is a nice close second) just to give some examples. My point wasn't tattoos specifically, just that humans have plenty of potential customizable options without going into the realm of non-human features.
> 
> > And we'll have to agree to disagree on the cosmetics. If you can explain to me what exact style ss14 is going for, then maybe I can reply to you in a more educated manner. But nothing about long ears somehow ruins the cohesion of the game. You're being a bit dramatic if that's actually what you personally think. (not to say you do think that either, but it's quite an interesting thing to mention in the middle of disagreeing with the long ears concept)
> 
> Look, long ears won't make me go "Ah fuck SS14's visuals are ruined" (the comment about "ruining arstyles" was in reference to "unlimited cosmetics", i.e. opening the doors wide open to basically any and all cosmetic changes regardless of theme). Like I said in my previous reply, giving humans inhuman features in a sci-fi setting is totally valid and can work, and if SS14 changes into that then it'll probably end up being fine. But having humans constrained to human features _is_ also a valid artstyle choice that has its own benefits too, and I'm expressing a subjective preference for it.

Fair. To me not having these elements and the possibility of the options being so anal just don't make me want to contribute in any large way because putting in a bunch of work and getting very little feedback is a problem. Adding smaller cosmetic things like ear rings and more tattoos is easy but I don't find that the conversation is often productive at all so I'm gonna just do small things and gauge it piece by piece. Wasting my time on a bunch of stuff to be denied is rather annoying

**Comment by deathride58** [comment]
Our word is not representative of all maints' thoughts, but honestly these ears are fine. They fit into the artstyle. These are very much in-line with the cosmetic expectations set by every other species. It's genuinely quite alienating the sheer gap in customizability between humans and nonhuman species, and this PR helps alleviate that by giving humans a bit of the customization they're missing. This PR isn't going to make humans unrecognizable nor cause a domino effect spiralling towards such, as this isn't really much of a departure at all from what humans are (it's *very* common in works featuring elves, [space elves](https://tvtropes.org/pmwiki/pmwiki.php/Main/SpaceElves) or not, to treat them essentially as weird humans anyhow). Right now, folks who wanna play a character a little more interesting than a human have to go all-in on playing a different species entirely, and that honestly shouldn't be the case.

Additionally, we find the angle of "restrict these to dwarves, they're the fantasy race", and "they are too unrealistic for humans/too unrealistic for this setting" incredibly silly. Star Trek, the sci-fi series that defined the overwhelming majority of the sci-fi genre's conventions, serves as the root for almost every trope in modern sci-fi media, and more, very prominently features [several](https://memory-alpha.fandom.com/wiki/Vulcan) [human](https://memory-alpha.fandom.com/wiki/Kellerun) [subspecies](https://memory-alpha.fandom.com/wiki/Romulan) with a distinct characteristic of pointed ears. To say that exaggeratedly pointed ears are unfitting of sci-fi settings is to ignore the foundational precedents laid out by the grandfather of sci-fi itself.

**Comment by SlamBamActionman** [comment]
> Additionally, we find the angle of "restrict these to dwarves, they're the fantasy race", and "they are too unrealistic for humans/too unrealistic for this setting" incredibly silly. Star Trek, the sci-fi series that defined the overwhelming majority of the sci-fi genre's conventions, serves as the root for almost every trope in modern sci-fi media, and more, very prominently features [several](https://memory-alpha.fandom.com/wiki/Vulcan) [human](https://memory-alpha.fandom.com/wiki/Kellerun) [subspecies](https://memory-alpha.fandom.com/wiki/Romulan) with a distinct characteristic of pointed ears. 

When I was saying "this setting" I meant SS14 specifically, where humans have (so far) been largely kept from having sci-fi/fantasy elements tied directly to their species. I already acknowledged that there's sci-fi media that has humanoid characters with non-human characteristics; it's just less common to see those with the label of _"human"_ (even the Star Trek examples you've linked distinguish them as a separate species from humans, putting them in the "humanoid" category instead). 

Dwarves in SS14, on the other hand, are more leaning into tropes with the accent and beer drinking buff tied to their species. 

> To say that exaggeratedly pointed ears are unfitting of sci-fi settings is to ignore the foundational precedents laid out by the grandfather of sci-fi itself.

The claim was that some sci-fi settings choose to not introduce non-human characteristics to human characters and that they're not worse off for it, not that doing so would be unfitting for sci-fi settings. Because, as you say, it's more common than not to have humanoids that look like humans but have minor differences in sci-fi media. But then we have sci-fi media like Aliens, The Fifth Element and Dead Space which are examples of sci-fi that, while having aliens, choose to represent humans without any non-human features (well, maybe a case can be made for the necromorphs... but you get the point). 


With all that said, I don't think it would be a sin if non-human ears were to be added to the game. But it _is_ a departure from how SS14's human species have been presented thus far. I just have a preference for one presentation over the other (for reasons stated previously).

**Comment by Sarahon** [comment]
> > Additionally, we find the angle of "restrict these to dwarves, they're the fantasy race", and "they are too unrealistic for humans/too unrealistic for this setting" incredibly silly. Star Trek, the sci-fi series that defined the overwhelming majority of the sci-fi genre's conventions, serves as the root for almost every trope in modern sci-fi media, and more, very prominently features [several](https://memory-alpha.fandom.com/wiki/Vulcan) [human](https://memory-alpha.fandom.com/wiki/Kellerun) [subspecies](https://memory-alpha.fandom.com/wiki/Romulan) with a distinct characteristic of pointed ears.
> 
> When I was saying "this setting" I meant SS14 specifically, where humans have (so far) been largely kept from having sci-fi/fantasy elements tied directly to their species. I already acknowledged that there's sci-fi media that has humanoid characters with non-human characteristics; it's just less common to see those with the label of _"human"_ (even the Star Trek examples you've linked distinguish them as a separate species from humans, putting them in the "humanoid" category instead).
> 
> Dwarves in SS14, on the other hand, are more leaning into tropes with the accent and beer drinking buff tied to their species. Even the simple fact that they're treated as a separate species to begin with leans into the fantasy trope.
> 
> > To say that exaggeratedly pointed ears are unfitting of sci-fi settings is to ignore the foundational precedents laid out by the grandfather of sci-fi itself.
> 
> The claim was that some sci-fi settings choose to not introduce non-human characteristics to human characters and that they're not worse off for it, not that doing so would be unfitting for sci-fi settings. Because, as you say, it's more common than not to have humanoids that look like humans but have minor differences in sci-fi media. But then we have sci-fi media like Aliens, The Fifth Element and Dead Space which are examples of sci-fi that, while having aliens, choose to represent humans without any non-human features (well, maybe a case can be made for the necromorphs... but you get the point).
> 
> With all that said, I don't think it would be a sin if non-human ears were to be added to the game. But it _is_ a departure from how SS14's human species have been presented thus far. I just have a preference for one presentation over the other (for reasons stated previously).

Truthfully, I'd not be surprised if the lack of human cosmetics is more due to peoples already non-interest in them. Not many people going onto a game like ss14 just wants to be their "normal human" - hence why people rush for the funny clothing or do funny gimmicks. Every other race gets to be bright and colourful with endless cosmetics(except for slimes, but those are plagued by the same arguments ironically), whereas humans are practically forced into what you will call "default". Which is, just boring to me!

**Comment by Emisse** [comment]
front sprite needs to look more pointy rather than shrek ear, otherwise this seems fine

**Comment by Sarahon** [comment]
> front sprite needs to look more pointy rather than shrek ear, otherwise this seems fine

I can do that.

**Pull request merged**
