### PR TITLE
Buff (Fix) Captain's Carapace

### PR DESCRIPTION
**Pull request by asperger-sind**
## About the PR

Captain's carapace no longer has slowdowns from it's parent, BaseLargeOuterClothing
## Why / Balance

It was intended this way and just didn't get fixed for like a year I think
## Technical details

Adds a line in the prototype clarifying the proper slowdowns (the lack thereof) as opposed to being parented from BaseOuterClothingLarge or whatever its called, also i didn't webedit this one
## Media
image
(no text mentioning the slowdown, no i dont have comparisons i forgot to grab one)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: BurninDreamer
- tweak: The Captain's Carapace no longer has a 10% movement speed penalty.

### CODE REVIEW

**Comment by asperger-sind** [comment]
i forgot changelog and had to edit it in so thats what it is for github relay
Changelog

🆑 BurninDreamer

tweak: The Captain's Carapace no longer is weighted down by the fabric of reality, or we just made it with lightweight steel.

**Comment by Aisu9** [comment]
powercreep~

**Comment by EmoGarbage404** [comment]
Drop the dumb over the top changelog and just list what you actually changed.

**Comment by asperger-sind** [comment]
> Drop the dumb over the top changelog and just list what you actually changed.

done

**Pull request merged**
