### PR TITLE
Removes SCAF armor

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Completely removes SCAF armor from the game.
Replaces it with a basic helmet in the single spot any piece of it is used (the maint loot spawner.)

Untested, but I don't think that'd really do much anyways.

## Why / Balance
SCAF armor just doesn't really make much sense to be in the game anymore. It's practically unused (Only the helmet is obtainable, and it's in a single spawner) and it's probably never going to get reused since:

1. It's (presumably) just a maint item plucked from Eris, but makes no sense to really exist (especially as a random maint item) in our setting.  It's super-futuristic-looking master chief armor. Even when salv were the ones getting this, it was pretty weird.
2. It's one of the most blatantly artstyle-breaking sprites in the game. That's not to say the sprite is bad, of course, but it is *hilariously* unfitting and would probably require a ton of work to make fit, which doesn't make much sense to devote time to since this item is basically unused.
3. The sprite seems to imply that it's spaceproof when it's not, and it wouldn't make sense to make spaceproof considering it's just meant to be simple maints armor.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
SCAF armor used to be pretty common, there's a good chance downstreams (especially ones focused on looting) may need to adjust their lootpools to remove it on their end.

**Changelog**

:cl:
- remove: Removed SCAF armor.

### CODE REVIEW

**Comment by UbaserB** [comment]
It's kind of funny how many thumbs down there are considering this was meant to be removed for ages

**Comment by K-Dynamic** [comment]
Rip meta maints loot

**Comment by Hmeister-real** [comment]
cant we keep it for admeme and downstream, but just remove it from maints loot? i like using it as an admin for a downstream server for events

**Comment by metalgearsloth** [comment]
> cant we keep it for admeme and downstream, but just remove it from maints loot? i like using it as an admin for a downstream server for events

We don't keep yaml for downstreams, just put it in your folder.

**Pull request merged**
