### PR TITLE
train update

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-remove swirlies between cars so feels better to traverse 
-move cmo office to surgery car and make medical entrance use double doored double doors
-reduced amount of overexposed lighting
-lawyers can now enter brig
-teg room big now and has a burn chamber
-remove lots of insuls around map
-qol fixes for many pipes doors and firelocks
-skub

### CODE REVIEW

**Comment by mirrorcult** [comment]
keep the SWIRLIES you have no soul

**Comment by Emisse** [comment]
the swirlies make it too hard to move around on lots of people got stuck in playtest. harlot

**Comment by Emisse** [comment]
id rather playtest the map more for more data collection

**Comment by UbaserB** [comment]
> the swirlies make it too hard to move around on lots of people got stuck in playtest. harlot

i told him lol

**Comment by TheShuEd** [comment]
bruh
😭

**Pull request merged**
