### PR TITLE
Added auto label for ChemMaster

### PR DESCRIPTION
**Pull request by artak10t**
## About the PR
Added auto label for ChemMaster output depending from solutions. Thus, the label chooses the most significant solution name. If we have solution A = 50u and solution B = 51u, output will be labeled according to solution B. Label can also be manually changed. Also fixed bug when couldn't transfer solution back into container in ChemMaster.

**Screenshots**

image

**Changelog**

:cl: artak10t
- add: Added auto labeler for ChemMaster.
- add: Added popup messages for ChemMaster buttons.

### CODE REVIEW

**Comment by mirrorcult** [comment]
label lineedit should be below the 'buffer' buttons imo

**Comment by artak10t** [comment]
Below you mean above pill types or just below buffer buttons or below buffer buttons but inside buffer itself?

**Comment by mirrorcult** [comment]
above pill types

**Comment by artak10t** [comment]
unknown

Ready for review. Unfortunately I don't have enough UI knowledge to make it look better

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
