### PR TITLE
Delete nonsense solar assembly construction through the Construction window

### PR DESCRIPTION
**Pull request by Hreno**
## About the PR

Deleted the "solar assembly" item in the Construction window.

I also fixed the description of solar tracker electronics.

## Why / Balance

It's not possible to construct it this way. The way to do it is to take solar assembly flatpack and use Multitool on it.

See more here #28009. That issue also mentions mispredicting glass floor which this PR doesn't fix.

## Technical details

Deleted construction YML stuff.

## Media

BEFORE (this doesn't work):
image

AFTER (it's gone):
image

Also a fix of the description of solar tracker electronics:
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by slarticodefast** [comment]
We should evaluate first if we want to merge #29224 instead, which expands the possibilities for constructing solars instead. I will put it up for maintainer discussion.

**Comment by Hreno** [comment]
> We should evaluate first if we want to merge #29224 instead, which expands the possibilities for constructing solars instead. I will put it up for maintainer discussion.

Sounds good. I missed that PR.

**Comment by Hreno** [comment]
Maybe this can be merged given that it's a quick fix PR, while the other one is a feature that requires maintainers discussions.

**Comment by slarticodefast** [comment]
> Maybe this can be merged given that it's a quick fix PR, while the other one is a feature that requires maintainers discussions.

Yeah, good point. Thanks for your contribution.

**Pull request merged**
