### PR TITLE
Removed Salv Borg Crusher Dagger

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I removed the Grapple Module's Crusher dagger
## Why / Balance

I made Grappling a T1 Tech a while ago and I think giving a Borg a crusher dagger at T1 is a bit much. I think the only reason that they had a crusher dagger originally was because it was at 8 damage not 15 like it is now. Salv Borgs still have access to the shovel in the mining module for self defense and can kill at least 3 carp with it before needing repairs.

I see no reason a Salvage Borg needs a dagger when their primary purpose is to mine like the drone they are. The Crusher dagger at the least has no Place in the Grapple Module.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed Crusher Dagger from Grapple Module

### CODE REVIEW

**Comment by SoulFN** [comment]
Just move grapple module to a higher tech or make separate modules with dagger and grapple gun

**Comment by SoulFN** [comment]
Borgs should have unique items that crew cant get or its hard to get, otherwise, theres no point in playing them

**Comment by FungiFellow** [comment]
> the crushers are meant as a salvage exclusive weapon and mining borgs aren't meant to be fighting.

Literally this. The only reason crusher daggers were In it before was because it was weak (Pre-Buff), right now it's one of the best melee weapons in the game. It's a MINING Chassis not a fighter.

Why should I ever spend TC on a weapons module when I can just make a mining borg instead?

Borgs should always be slightly worse than their Humanoid counterpart. Otherwise people will powergame playing as a borg

**Comment by Simyon264** [comment]
> when their primary purpose is to mine like the drone they are.

Mining gameplay is boring. Degrading salvage borgs to only mine would make me not want to play as one.

**Comment by Zealith-Gamer** [comment]
Borgs should *not* necessarily be weaker than their human counterparts. They already have a lot of limitations that humanoids don't. Also mining bots should have the option to salvage instead of mine. As a borg you can't pick things and that's a huge limitation. Can't use some items like the fulton. Can't upgrade weapons by simply picking them up. Have to listen to the crew, HUGE limitation.
I have no issue with removing the knife from the grapple and that is a weird place for the knife but the borg is placed in danger and should have a proper defense. Not sure how much the shovel does but there should be a salvage module with a proper weapon atleast, make it T3. But that's just my opinion.

As far as "why should i buy the weapon module" cus it has a gun and unless you're sci you can’t easily make borgs. If you are sci then you just make a borg army anyway, part of the perks of playing an antag sci.

Also this is from a borg player who actually enjoys mining.

**Comment by K-Dynamic** [comment]
> Borgs should _not_ necessarily be weaker than their human counterparts. They already have a lot of limitations that humanoids don't. Also mining bots should have the option to salvage instead of mine. As a borg you can't pick things and that's a huge limitation. Can't use some items like the fulton. Can't upgrade weapons by simply picking them up. Have to listen to the crew, HUGE limitation. I have no issue with removing the knife from the grapple and that is a weird place for the knife but the borg is placed in danger and should have a proper defense. Not sure how much the shovel does but there should be a salvage module with a proper weapon atleast, make it T3. But that's just my opinion.
> 
> As far as "why should i buy the weapon module" cus it has a gun and unless you're sci you can’t easily make borgs. If you are sci then you just make a borg army anyway, part of the perks of playing an antag sci.
> 
> Also this is from a borg player who actually enjoys mining.

Ok but being specialised doesn't mean you couldn't be overpowered. Keep in mind borgs have AA, are easily repairable, have no slowdowns or slipping, immune to spacing - and they won't need hands if their modules (grappling or syndicate module) are stronger than whatever could've picked up.

Personally, we should discuss:
- if borgs should fight and what enemies should they be able to handle
- if borgs should have access to weapons/high-damage tools
- how accessible weapon/damaging modules should be

**Comment by Zap527** [comment]
Call me a contrarian, but this is a good change. Cyborgs are designed to be worth less than a full crew member - they're here to assist another crew member in their tasks, not here to be another fully fledged salvager. The tradeoff they get is that they get immunity to most non direct damage hazards and near-instant healing in the form of welding.

The point in playing borg isn't to have cool free gear and immunities, it's to follow your silicon laws. It isn't much different to command roles, where the point of the role is to lead your department, not play with your shiny toys.

Having a free metaweapon in your kit doesn't make borg gameplay more interesting, it just give you more power to take down things alone which, once again, isnt really the point imo.

**Comment by Zealith-Gamer** [comment]
> Ok but being specialised doesn't mean you couldn't be overpowered. Keep in mind borgs have AA, are easily repairable, have no slowdowns or slipping, immune to spacing - and they won't need hands if their modules (grappling or syndicate module) are stronger than whatever could've picked up.
> 
> Personally, we should discuss:
> 
> * if borgs should fight and what enemies should they be able to handle
> * if borgs should have access to weapons/high-damage tools
> * how accessible weapon/damaging modules should be

These are good questions that should be discussed. I'm not saying you should give the borgs anything massive but specifically the "mining" borg should be able to have some weapons.

 
> The point in playing borg isn't to have cool free gear and immunities, it's to follow your silicon laws. It isn't much different to command roles, where the point of the role is to lead your department, not play with your shiny toys.

this is just weird, Borgs are players too, don't forget that. Just like any other players, borg players like shiny new fun stuff they don't get every round. Sure the point of a department head is to lead the department but they also get to play with fun shiny toys. 

> Having a free metaweapon in your kit doesn't make borg gameplay more interesting, it just give you more power to take down things alone which, once again, isnt really the point imo.

I'm not saying they should have "meta weapons". I'm agreeing with this PR, as having a dagger in the grapple module is weird. I'm trying to go against the people that are actively trying to make playing borg no fun. 
If I'm a mining borg I usually like to stay with the humans to try to prevent them from dieing. That means I will be fighting.

**Pull request merged**
