### PR TITLE
Syndicate Space Carp

### PR DESCRIPTION
**Pull request by BlitzGunner225**
## About the PR 
Space carps are very random due to everyone doing whatever they want as them. They might kill everyone and space everything or be strangely friendly. This is actually fine on its own as taming has itself become a mini gameplay aspect. Sometimes it works out and sometimes it dosen't. The problem is that taming a syndicate spawned carp and having it "not work out" or have those carps team with randoms, it essentially wastes that syndicate's TC. It's infuriating but if you force all space carps to be hostile then it takes away from some unique parts of the game. The creation of a syndicate space carp should alleviate this problem and add some new aspects.
Now you might at first think that this would be way too similar or possibly stronger than our good old mister holo but that isn't exactly true. For starters a space carp is a separate entity and not connected to you so it has it's own health that you would have to manage too. The second difference is that you have to stash the syndicate carp while it gains a soul which adds an extra risk to being caught. And thirdly space carps can't come out of nowhere like a holo can so you loose some surprise and don't always have backup. The only good thing is that you can give them chem shit but that requires extra work put in. You can also have your carp on the other side of the map doing stuff for you. All in all it would be a pretty unique ally.
And hey I could increase the TC if we really need to. 

**Screenshots**

alive
Credit to "Old Dance Jacket#1112" for the sprite.

**Changelog**

:cl:
- add: Added Syndicate Space Carp for 3 TC!
- remove: Removed 1 TC From Regular Space Carp!

### CODE REVIEW

**Comment by mirrorcult** [comment]
why are there both normal carp and syndicate carp. just have one

**Comment by BlitzGunner225** [comment]
> why are there both normal carp and syndicate carp. just have one

Higher Effort and risk in taming for less tc 
It also works as a wildcard for the crew if you let em loose

**Comment by mirrorcult** [comment]
this should be one item

**Comment by mirrorcult** [comment]
theres nothing different here other than the sprite and ruleset change. really no reason for it to confusingly be two different things

**Comment by BlitzGunner225** [comment]
> this should be one item

Normal carps are a cheap wildcard buy
Syndie carps are a more expensive safe buy

**Comment by keronshb** [comment]
Just chiming in, ideally what should be done instead if get dehydrated carps to work like they are on SS13: using it in hand before hydrating it marks you to ignore more or less.

**Comment by EmoGarbage404** [comment]
> > this should be one item
> 
> Normal carps are a cheap wildcard buy Syndie carps are a more expensive safe buy

That would be true if there were actual mechanical differences between the two items. As it stands, the only difference between these two is the fact that one has a slightly different ghost role text. Nevermind the fact that when ai controlled, it will attack the syndie, making it pointless.

**Comment by BlitzGunner225** [comment]
> Just chiming in, ideally what should be done instead is to get dehydrated carps to work like they are on SS13: using it in hand before hydrating it marks you to ignore more or less.

Someone tried to make a syndie exploding penguin that woudn't attack syndies and he died inside trying to get it to work
I have no idea how to code so I doubt I'd do better

**Comment by mirrorcult** [comment]
make it one item

**Review by mirrorcult — CHANGES_REQUESTED** [review]
see above

**Comment by BlitzGunner225** [comment]
> > > this should be one item
> > 
> > 
> > Normal carps are a cheap wildcard buy Syndie carps are a more expensive safe buy
> 
> That would be true if there were actual mechanical differences between the two items. As it stands, the only difference between these two is the fact that one has a slightly different ghost role text. Nevermind the fact that when ai controlled, it will attack the syndie, making it pointless.

Well being forced to not attack syndies is in of itself a game changer. I could try to see if I can make em do no damage to syndies but like I said I don't really know how to code. Admins shouldn't have too much trouble dealing with shitters as them as there should never prob be more than one occurrence at a time.

**Comment by EmoGarbage404** [comment]
> > > > this should be one item
> > > 
> > > 
> > > Normal carps are a cheap wildcard buy Syndie carps are a more expensive safe buy
> > 
> > 
> > That would be true if there were actual mechanical differences between the two items. As it stands, the only difference between these two is the fact that one has a slightly different ghost role text. Nevermind the fact that when ai controlled, it will attack the syndie, making it pointless.
> 
> Well being forced to not attack syndies is in of itself a game changer. I could try to see if I can make em do no damage to syndies but like I said I don't really know how to code. Admins shouldn't have too much trouble dealing with shitters as them as there should never prob be more than one occurrence at a time.

You havent actually codified that within in the game beyond the ghost role rules. Not only have drones proved that those rules dont work, but since the carps keep the old ai, they will hurt syndies when spawned.

**Comment by EmoGarbage404** [comment]
> > > > this should be one item
> > > 
> > > 
> > > Normal carps are a cheap wildcard buy Syndie carps are a more expensive safe buy
> > 
> > 
> > That would be true if there were actual mechanical differences between the two items. As it stands, the only difference between these two is the fact that one has a slightly different ghost role text. Nevermind the fact that when ai controlled, it will attack the syndie, making it pointless.
> 
> Well being forced to not attack syndies is in of itself a game changer. I could try to see if I can make em do no damage to syndies but like I said I don't really know how to code. Admins shouldn't have too much trouble dealing with shitters as them as there should never prob be more than one occurrence at a time.

You havent actually codified that within in the game beyond the ghost role rules. Not only have drones proved that those rules dont work, but since the carps keep the old ai, they will hurt syndies when spawned.

**Comment by BlitzGunner225** [comment]
I'll see if I can make anything to really stop syndie carps from hurting syndies

**Comment by Peptide90** [comment]
> I'll see if I can make anything to really stop syndie carps from hurting syndies

Factions my friend. We discussed something similar to stop zombie friendly fire so if you can pull it off, good luck!

**Pull request closed without merging**
