### PR TITLE
(Add) black cap and some contraband

### PR DESCRIPTION
**Pull request by Jackal298**
## About the PR

This PR adds a black cap from the TG build and also adds two neck gaiters to the СlothesMate contraband inventory

UPD: I had to slightly increase the restock price for cargo items from 4670 to 4750, but I think this is not such a big problem
## Why / Balance

Overall, I don’t see anything wrong with adding a neck gaiter to ClothesMate’s counterbat inventory, it doesn’t provide any particular benefits (other than cool style), 
## Media

2 black
1 black

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by icekot8** [comment]
оh.... The bot doesn't like that your item added 40 credits that were not expected for CrateVendingMachineRestockClothes

**Comment by Jackal298** [comment]
> оh.... The bot doesn't like that your item added 40 credits that were not expected for CrateVendingMachineRestockClothes
> 
> ```
> A total of 1 test files matched the specified pattern.
>   Failed NoCargoOrderArbitrage [1 s]
>   Error Message:
>      Found arbitrage on CrateVendingMachineRestockClothes cargo product! Cost is 4670 but sell is 4700!
>   Expected: less than or equal to 4670
>   But was:  4700.0d
> ```

we'll fix it now

**Comment by Morp9x** [comment]
If I'm not mistaken, the operative's clothing does not have tracking or health sensors, which makes this seem slightly illogical.  Perhaps we should issue this overalls only after hacking the machine through EMAG.

**Comment by Jackal298** [comment]
> If I'm not mistaken, the operative's clothing does not have tracking or health sensors, which makes this seem slightly illogical. Perhaps we should issue this overalls only after hacking the machine through EMAG.

Tacticool suits have life and tracking sensors, you are confusing them with regular operative overalls (there is a difference in the name, which is why they can be confused)

**Pull request merged**
