### PR TITLE
Made anchor visuals generic

### PR DESCRIPTION
**Pull request by TGRCdev**
## About the PR

This PR adds the `AnchorVisuals.Anchored` appearance data enum, which stores an entity's anchored status for use with `GenericVisualizer`.

## Why / Balance

There was no way to define anchor-state-dependent sprite states in an entity without writing a bespoke component. I implemented this for downstream content, and I wanted to offer the functionality upstream.

## Technical details

This is intended to allow entities to change their anchored appearance using the `GenericVisualizer` component. When an entity has the `Anchorable` component, their anchor state will be stored in their appearance data under the key `AnchorVisuals.Anchored`. This state can then be retrieved from the `GenericVisualizer` to implement anchor-dependent sprite states without a bespoke component.

I used this functionality to replace the `GasPortableVisuals` appearance enum, which was functionally identical, but intended specifically for anchoring gas canisters to connector ports.

```yml
- type: Anchorable
- type: GenericVisualizer
  visuals:
    enum.AnchorVisuals.Anchored:
      connectedToPort:
        False: { state: can-connector, visible: false }
        True: { state: can-connector, visible: true }
```

## Media

[Screencast_20241210_010947.webm](https://github.com/user-attachments/assets/08886e73-6918-4c03-b07f-de631451ea22)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

`GasPortableVisuals.ConnectedState` has been removed and replaced with the generic `AnchorVisuals.Anchored` enum.

**Changelog**

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Review by Aeshus — APPROVED** [review]
Seems to work as intended, thanks!

I was wondering if this would also be applicable to the nuke and its `NukeVisuals`, which serves a similar purpose (except it does weird stuff outside of the anchoring system).

(Guh, sniped my sloth)

**Comment by TGRCdev** [comment]
I could certainly check! I'm not aware of all the places in the code that have implemented this specific functionality, but it'll be a good opportunity to start looking.

**Comment by TGRCdev** [comment]
From a quick search, looks like the nuke, disposal units, and nav beacons could be simplified to use this. More commits coming.

**Comment by Aeshus** [comment]
I would probably just do those in a second PR as this one is pretty focused and that will just delay this being merged.

**Comment by TGRCdev** [comment]
Good point. In that case, everything is ready to merge.

**Review by slarticodefast — APPROVED** [review]
Works as intended. Thank you for your contribution!

**Pull request merged**
