### PR TITLE
Renames walls and rods to improve consistency

### LINKED ISSUE #5297: Low walls and metal walls still exist
## Description

Metal walls in particular are a bit confusing, especially metal walls as they look identical to solid walls.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Lamrr**
## About the PR 
This PR consistently names derivatives of materials making it easier to add more walls and rods based off different materials in the future.

Solid walls have been renamed to steel walls, reinforced walls have been renamed to plasteel walls and metal rods have been renamed to steel rods to reflect the materials used in their construction. Their construction graphs and their entity IDs have also been changed to reflect this (i.e wall -> steelWall, WallSolid -> WallSteel, etc) as well as the graphs of relevant entities (such as grilles, etc.).

C# code has mostly been untouched except for the RCD which now builds steel walls instead of solid walls, the reinforced wall handler is still named as such.

WallMetal has been removed, combined with #6063 this fully resolves #5297.

A full list of renamed entity IDs:
WallSolid -> WallSteel
WallReinforced -> WallPlasteel
PartRodMetal -> PartRodSteel
PartRodMetal1 -> PartRodSteel1

**A notice to cartographers;**
All maps have been updated to use the new entity IDs, however any other maps out there will have to be updated after this PR is merged. 

There are two ways to do this, 1) using a text editor and finding & replacing entity IDs by hand or 2) by using this [python script that I made](https://gist.github.com/Lamrr/7d9f425b98bcf66f86a427ac00ed308f) which will do it for you - with your map file in the same directory as the script simply use `python3 replace_deprecated.py` and then enter your map's filename (incl. extension) when prompted.

**Changelog**

:cl:
- tweak: The naming department has corrected product names to better reflect the materials used in their construction.

### CODE REVIEW

**Comment by Lamrr** [comment]
Hm, I'm not sure why the build failed - the changes seem to run fine on my end and I haven't touched anything relating to storage (assuming that's what `[WARN] Storage: Removed entity 5238 without a cached size from storage 5237 at Map=1, X=985.94, Y=-150.08` means). Would anyone be able to help diagnose this?

**Comment by Peptide90** [comment]
> Hm, I'm not sure why the build failed - the changes seem to run fine on my end and I haven't touched anything relating to storage (assuming that's what `[WARN] Storage: Removed entity 5238 without a cached size from storage 5237 at Map=1, X=985.94, Y=-150.08` means). Would anyone be able to help diagnose this?

I believe I had a similar issue with my PR. The problem was the mapping command was running on an initialized map so it was spawning things in. If you made any changes using the actual mapping command that could be it and you'll need to redo them uninit. There's also conflicts now that need resolving.

**Comment by Lamrr** [comment]
> > Hm, I'm not sure why the build failed - the changes seem to run fine on my end and I haven't touched anything relating to storage (assuming that's what `[WARN] Storage: Removed entity 5238 without a cached size from storage 5237 at Map=1, X=985.94, Y=-150.08` means). Would anyone be able to help diagnose this?
> 
> I believe I had a similar issue with my PR. The problem was the mapping command was running on an initialized map so it was spawning things in. If you made any changes using the actual mapping command that could be it and you'll need to redo them uninit. There's also conflicts now that need resolving.

Interesting, I'll redo the maps and see if that solves it.

**Comment by metalgearsloth** [comment]
You coming back to this @Lamrr ?

**Comment by Lamrr** [comment]
> You coming back to this @Lamrr ?

yeah i'll have to go over and resolve the conflicts / fix building when i have time

**Comment by metalgearsloth** [comment]
Just pign for re-open when you get a chance because all the maps are gonna need re-doing.

**Pull request closed without merging**
