### PR TITLE
Ghetto Mindshield Icon

### PR DESCRIPTION
**Pull request by coolmankid12345**
## About the PR

Added an icon for Mindshielded people when using the Sechud. (Thank you [Psychpsyo](https://github.com/Psychpsyo) for the icon.)
## Why / Balance

You probably don't want to have to guess who has and doesn't have a Mindshield so this will help. In a perfect world, I would have done the blue outline around the job icon but that is out of my area of expertise. This might make Syndicate gameplay harder if they want to impersonate Heads/Security but I hate syndies anyway so.
## Technical details

Checks if you have MindshieldComponent while wearing Sechuds and adds icon.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

### CODE REVIEW

**Comment by UbaserB** [comment]
I enjoy this.

**Comment by JoeHammad1844** [comment]
heres an idea, just add a blinking blue overlay to the job icon like ss13
image

**Comment by JoeHammad1844** [comment]
please make seeing mindshield icons seperate to the regular sechud tag so secglasses can see mindshields

**Comment by GoodWheatley** [comment]
> please make seeing mindshield icons seperate to the regular sechud tag so secglasses can see mindshields

Please stop trying to get sec glasses buffed, just wear the hud

**Comment by JoeHammad1844** [comment]
you VILL wear ze sechud and get flashed

**Comment by LankLTE** [comment]
Unrelated to getting the secglasses buffed for no reason (don’t do that), I’m mainly worried about the implications this has on other gamemodes. It’s nice for revs, but also makes it near impossible to stealth as a head or security, a job that’s already *very* difficult to begin with. Maybe there’s a way to solve this but I want to see that proposed as well first

**Comment by coolmankid12345** [comment]
> Unrelated to getting the secglasses buffed for no reason (don’t do that), I’m mainly worried about the implications this has on other gamemodes. It’s nice for revs, but also makes it near impossible to stealth as a head or security, a job that’s already _very_ difficult to begin with. Maybe there’s a way to solve this but I want to see that proposed as well first

Read the last sentence of why/balance. Jokes aside, if anything we could have a fake mindshield implant for like 2 tc or better yet the syndie can just go get themselves mindshielded.

**Comment by Nairodian** [comment]
Syndicates should be able to buy a fake mind shield implant for like 1 TC to counter this. Revos and Syndicates will almost never be in the same round unless an admin's already doing some fuckery so it won't cause issue.

**Comment by HerCoyote23** [comment]
Might be best just to have it be really hard to impersonate sec/captain. /tg/ has an good mindset on it: You have to be able to trust that security are not antagonists, otherwise an officer arresting you for a valid reason could be taken as an attempt on your life from an antag.
Also /tg/ gets around the heads problem by making heads just inherently unable to be revs, rather than giving them mindshields. That way you can still abduct and replace CE/RD/CMO/HOP, just not Captain or Security, who need to be trustable.

**Comment by LankLTE** [comment]
> Syndicates should be able to buy a fake mind shield implant for like 1 TC to counter this. Revos and Syndicates will almost never be in the same round unless an admin's already doing some fuckery so it won't cause issue. Hell even a real one wouldn't even be too big of a deal.

Issue with this is it prevents other antags (revs or any other to be added) from impersonating *entirely* (even though it's already much more difficult for them to do so)

**Comment by JoeHammad1844** [comment]
> Issue with this is it prevents other antags (revs or any other to be added) from impersonating _entirely_ (even though it's already much more difficult for them to do so)

their objective is not to impersonate heads, their objective is to kill every head on the station. stealth is only really involved in the first like half an hour of trying to convert as many people as possible and then you swarm sec and heads

**Comment by JoeHammad1844** [comment]
a revolutino is hard and at its weakest in the first 30 minutes trying to get the crew on their side, just making it harder with less economic flashes isnt fun and just makes it even harder

**Comment by brainfood1183** [comment]
Mind shield icon should only appear for those who have been implanted, sec and heads should likely not have any sort of icon and instead should have a different (yet similar implant with no icon. This is to prevent sec from knowing exactly who is sec or head and who is imposter.

**Comment by JoeHammad1844** [comment]
that will just make sec and heads think they needs mindshields and make it impossible to impersonate heads

**Comment by brainfood1183** [comment]
> that will just make sec and heads think they need mindshields

But if you dont do this then sec would instantly know if someone is posing as a head or sec because they odnt have a mindshield icon

**Comment by Subversionary** [comment]
> a revolutino is hard and at its weakest in the first 30 minutes trying to get the crew on their side, just making it harder with less economic flashes isnt fun and just makes it even harder

flash med kill secoff who walks alone in med get another flash flash sci
rev rounds are not hard its just headrevs are massive pussies and cede the win to command 90% of the time.

ergo your argument is a non-issue

for tots just make a fakecel mindshield implant for tots and its cool and make it 1tc

P.S. hudsunglasses are not real

**Comment by JoeHammad1844** [comment]
> flash med kill secoff who walks alone in med get another flash flash sci rev rounds are not hard its just headrevs are massive pussies and cede the win to command 90% of the time.

the other 10% of the time command calls shuttle and pussys out in maints :trollface:

**Comment by Subversionary** [comment]
> the other 10% of the time command calls shuttle and pussys out in maints :trollface:

not on shuttle doesnt count

**Comment by Psychpsyo** [comment]
How's this for a mindshield icon?
image
MindShield

**Comment by coolmankid12345** [comment]
> How's this for a mindshield icon? 

image

I like it but I feel like the blue should be darker to match most of the command job icons but that might just be me

**Comment by Psychpsyo** [comment]
> I like it but I feel like the blue should be darker to match most of the command job icons but that might just be me

I feel like having it be somewhat different from the command jobs is good since it makes it clear at a glance that it's not a job indicator.

**Comment by coolmankid12345** [comment]
> > I like it but I feel like the blue should be darker to match most of the command job icons but that might just be me
> 
> I feel like having it be somewhat different from the command jobs is good since it makes it clear at a glance that it's not a job indicator.

Works for me, I updated it with your icon now. Thanks

**Pull request merged**
