### PR TITLE
ninja bombing target whitelist warp point

### LINKED ISSUE #19974: Ninja can have a bomb arrivals objective
The bomb objective picks warp points and arrivals is often a warp point. Since warp point names aren't standardized, the best options for solutions are probably:
- create a new marker for "bombing objectives" to be manually mapped and use that, or
- do a range search for nearby arrivals airlocks and reject the warp point if it is too close (idk how close is too close, it should be conservative)

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
resolves #19974

WarpPointBombing used, has a spider charge on the icon in f5 for mapping

added to high importance (sec/armory/vault/bridge/atmos/science) or high population (bar/medical) areas

### CODE REVIEW

**Comment by deltanedas** [comment]
@metalgearsloth pro

**Review by AJCM-git — COMMENTED** [review]
I dont like how these have to be mapped, maybe a better implementation would be using wires and checking how secure they are (comparing to a datafield equal to LayoutId)?

**Comment by AJCM-git** [comment]
oop

**Comment by deltanedas** [comment]
then someone can spam lv at arrivals to force ninja to bomb it which id bad

**Comment by AJCM-git** [comment]
> then someone can spam lv at arrivals to force ninja to bomb it which is bad

WiresComponent aint for power wires but board wires (for hacking and stuff), i meant filtering for high sec stuff to bomb by querying WiresComponent with LayoutId set to HighSec

**Pull request merged**
