### PR TITLE
Secret stash anchoring fix

### LINKED ISSUE #31646: Trying to anchor a plant fails because the tool is hidden in the plant instead
## Description

There are many potted plants around most of the stations. Should you want to anchor one, you would typically use a wrench. Trying to do so starts the action, but stops in the middle because the wrench gets hidden into the potted plant.
Given two actions are being done at the same time, I'd suggest linking one of them to an auxiliary action (ALT + Click).

**Reproduction**
* Find potted plant
* Try to anchor it
* Smile at the progress bar being shown, anchor time is nigh
* Loudly sob at your wrench being hidden in the potted planted instead

**Screenshots**
https://github.com/user-attachments/assets/b80fc6c5-569e-4e9a-bc74-a8c8524f4239

**Additional context**
Clearly not an issue that prevents playing, but I found that the other day.

### PR DESCRIPTION
**Pull request by godisdeadLOL**
## About the PR

Anchoring potted plants and toilets (opened with crowbar) with a wrench fails because the wrench gets hidden instead. Problem is that two actions get triggered at the same time. 

Now anchoring action has higher priority over stashing. Also assigned stashing action to alt+click and unhidden verbs for secret stashes.

## Why / Balance

fixes #31646 and #31455

## Technical details

Removed field `HasVerbs` from `SecretStashComponent` as now it doesn't do anything. (maybe hiding verbs for potted plants was necessary?)

## Media

https://github.com/user-attachments/assets/51e66d14-2485-4ddf-bf98-946be80bde27

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 yuitop
- tweak: now anchoring has higher priority over stashing (in potted plants or toilets)
- tweak: assigned stashing to alt+click

### CODE REVIEW

**Comment by beck-thompson** [comment]
I have two concerns:

1.) You can no longer just place items inside directly without using the shortcut or the verb. I personally feel like that's kind of important! Instead of removing this functionality, could you just make the wrenching system go before the stash system (Or vice versa) so the default interaction with the wrench is sticking it in place instead of stashing the item? I feel like that would be the best of both worlds (The only issue is I'm not sure that the wrenching is predicted but I pray it is 😭)

2.) Having the close / open verb so far apart from the insert one is kind of annoying! I liked it when it was near the top so it was clear what you could do with the object. There have been many times in game that I have not known I could do something because it was hidden way down in the verb menu.
image

Also I hope my code wasn't too awful to deal with! Its much better than what was there before though 😆

**Comment by godisdeadLOL** [comment]
Thanks for feedback.

I didn't know that `SubscribeLocalEvent` allows to change events triggering order. Now `InteractUsingEvent` for `SecretStashSystem` triggers after `AnchorableSystem` and anchoring has higher priority over stashing.

For verb order, I think alternative verbs are always displayed after interaction verbs. I can restore stash action to being interaction verbs. I thought alt+click was convenient.

**Comment by beck-thompson** [comment]
> For verb order, I think alternative verbs are always displayed after interaction verbs. I can restore stash action to being interaction verbs if needed. I thought alt+click was convenient.

Your the boss! They both have their positives and negatives. Also the only reason `HasVerbs` exists was for the plants storage to be more "hidden" (Basically keeping their behavior the same as before my PR). It isn't like holding anything together so removing it is fine 😆

**Comment by godisdeadLOL** [comment]
Thinking about it, it's strange that you can both click and alt+click to stash items.

**Comment by godisdeadLOL** [comment]
i think I broke something
just ignore it

**Comment by godisdeadLOL** [comment]
I'll just close that pull request and re-open when fix some git issues.

**Pull request closed without merging**
