### PR TITLE
Drones

### PR DESCRIPTION
**Pull request by Emisse**
re enable drones. we are ready

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Are we?

**Comment by Elijahrane** [comment]
> Are we?

even with whitelist I ended up disabling them again on nyano FWIW

they need deafness and an unknown humanoid shader minimum I think, although some of the other mechanical parts can be relaxed a bit

**Comment by mirrorcult** [comment]
these really need whitelist and even then idk

**Comment by Emisse** [comment]
closing because roboticism

**Pull request closed without merging**
