### PR TITLE
Greyscale color clothing

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Greyscales jumpsuits, the prisoner jumpsuit, shoes, and *most* color gloves.
Instead of each piece of colored clothing having its own RSI, they all just use the same RSI, but with a color modifier passed through the layers that we want to recolor.
Additionally, some clothing (mainly shoes) now have different shades of color that are hopefully more fitting for their set then the ones before. The jumpsuits are all the same primary color as their previous counterparts though (as far as I can remember.)

Of note: there are some minor issues related to the spawn icon that I cannot fix (seemingly.) At worst, this *slightly* affects chameleon clothing, but it's not a big deal since there's already a tooltip telling you what piece of clothing you're morphing in to.

Also deletes the IHS combat gloves RSI because I am like 90% sure it is completely unused.

## Why / Balance
Color clothes were (apparently) pretty infamous for being really weird and inconsistent. Basically every piece of color clothing had a different shade of color, which tends to look really bad, especially if you're wearing the full set. Most color clothing was also littered with weird-ass palette choices (both bad ramps and bad color choices,) which this hopefully eliminates fully.

This *also* eliminates a lot of minor sprite inconsistencies within them (did you know yellow shoes had a good shade in the item sprite, but were piss yellow in the worn sprite?) but that's not really important.

## Media
Content Client_1bVZyQEh4L

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
This renames & deletes a few pretty common RSI paths, but they shouldn't be too hard to fix.

**Changelog**

:cl:
- tweak: Colored jumpsuits, shoes, and (most) colored gloves are now colorized off of one set of greyscale sprites. They should now be more consistent & significantly less ugly.

### CODE REVIEW

**Comment by UbaserB** [comment]
where is the black jumpsuit photo

**Comment by MACMAN2003** [comment]
finally, the power ~rangers~ tiders

**Comment by Flareguy** [comment]
> where is the black jumpsuit photo

Updated the image to include every jumpsuit.

**Comment by EmoGarbage404** [comment]
fart director rejoice

**Comment by DogZeroX** [comment]
Snoozer party

**Pull request merged**
