### PR TITLE
Cluster grenades for uplink and security

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

This PR refactors the clustergrenade system, adds a multitude of cluster grenade options to the syndicate uplink, puts the clusterbang in the sectech and adds a new grenade to the sectech.

Grenade types:

Security:

- ClusterBang: Splits into three flashbangs after a 3.5 second timer, these flashbangs explode one second after splitting up.
- Stinger grenade: A flashbang that additionally releases a spray of rubber pellets.

Syndicate:
- Cluster grenade(8TC): Splits into three explosive grenades after a 3.5 second timer, these grenades explode one second after splitting up.
- Shrapnel grenade(4TC): A grenade that instead of exploding releases a spray of lethal bullets that pierce mobs in an area around itself.
- Incendiary grenade(4TC): A shrapnel grenade that shoots piercing incendiary bullets, igniting anyone near the detonation area.
- Cluster banana peel(clown exclusive, 6TC): After landing on the floor it splits into 6 explosive banana peels, these banana peels have a 20 second timer if nobody slips on them.
- Slipocalypse ClusterBang(3TC): After landing on the floor it litters the area with 30 small pieces of syndicate soap, these pieces of soap evaporate after 60 seconds.

Other changes:

- Buffed the explosive banana peel so that it deals 60 damage to an unarmored target when stepped on.
- Instead of 4 frag grenades and 4 blast grenades the china lake bundle now contains 2 frag, 2 blast, 2 incendiary and 2 shrapnel grenades. The incendiary and shrapnel grenades explode at a static distance, don't trigger if hitting a mob but pierces them instead and don't trigger at all if they hit a wall before triggering.

**Media**

https://github.com/space-wizards/space-station-14/assets/137322659/aae3de4b-660b-4a9e-a632-047e0577fd54

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- add: Added a new type of grenade, these grenades release a spray of bullets instead of exploding: Shrapnel grenade, Stinger grenade and Incendiary grenade.
- add: Added two types of cluster grenade: The ClusterBang and the Cluster grenade, these split into three flashbangs and three explosive grenades.
- add: Stinger grenades and ClusterBangs are now available in the sectech.
- add: Incendiary grenades, Shrapnel grenades and Cluster grenades are now available in the syndicate uplink.
- add: Added the cluster banana peel to the uplink of syndicate clowns, it splits into multiple explosive banana peels after throwing.
- add: Added the Slipocalypse ClusterBang to the syndicate uplink, this grenade spreads small pieces of syndicate soap over an area after being thrown.
- tweak: The china lake bundle now contains 2 timed shrapnel grenades, 2 timed incendiary grenades, 2 frag grenades and 2 blast grenades.
- tweak: Explosive banana peels are now more explosive.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
I absolutely love this!

**Comment by JoeHammad1844** [comment]
maybe add some of the new grenades into the nukie grenade vest

**Comment by JoeHammad1844** [comment]
still working on this?

**Comment by metalgearsloth** [comment]
Merge after https://github.com/space-wizards/space-station-14/pull/13747/

**Comment by metalgearsloth** [comment]
@Arendian conflicts please

**Comment by metalgearsloth** [comment]
Re-open if you get a chance to work on it.

**Comment by Arendian** [comment]
I don't think I am able to reopen it so I'll make a new one

**Pull request closed without merging**
