### PR TITLE
Make Antimov & Overlord obtainable through the uplink

### PR DESCRIPTION
**Pull request by Veritius**
## About the PR
A kit including the Antimov and Overlord law boards can now be purchased from the uplink, for 8 TC.

## Why / Balance
Nukies can now subvert the AI, giving them an alternative to destroying it, letting the AI stay in the round and have some fun too. Traitors can also take advantage of these law boards for... troublemaking, I suppose. Antimov and Overlord are now Syndicate contraband.

**Changelog**
:cl:
- add: The Antimov and Overlord law boards are now obtainable through the uplink.

### CODE REVIEW

**Comment by Veritius** [comment]
main was outdated, fuck

**Comment by Veritius** [comment]
I've fucked this up and I do not know how to fix it.

**Comment by ArtisticRoomba** [comment]
learning git via trial by fire

**Comment by Djungelskog2** [comment]
the last law of the quarantine set implies that Current laws > Prevention of changing of laws
Which is against the rules

**Comment by Veritius** [comment]
good catch

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
Maybe add Syndicate law board too?

**Comment by slarticodefast** [comment]
Isn't this mostly similar to #31916?
Also it might be best to just wait for freeform law upload to be implemented. The other PR was waiting on that.

**Comment by Veritius** [comment]
i did not know that 31916 existed. also, i don't think it needs to be that expensive because using it can harm your objectives. it's not entirely beneficial to you, and might do more damage than good.

**Comment by Veritius** [comment]
eclipse's one was merged

**Pull request closed without merging**
