### PR TITLE
Simplify DoAfterArgs behavior for movement and distance checks

### LINKED ISSUE #25113: tile prying doesn't break on move when in zero g
## Description

- remove gravity
- get crowbar
- pry tile
- move
- finish prying tile

should get canceled after a certain amount of movement

### PR DESCRIPTION
**Pull request by nikthechampiongr**
fixes #25113

## About the PR

This pr makes it so that doafter checks for movement uses a single threshold, and with 2 bools to control whether it is checked and whether weightless movement is ignored.

It also makes doafters checks whether someone can actually interact with whatever they are trying to interact with.

## Why / Balance

I was asked to make these changes to the doafter system on discord.

I could only test this by running 2 clients at the same time, and stunning one while going on the other to try to do stuff like cuff them, heal them, etc. Obviously this testing is not very extensive but I can't do much locally. If this gets merged we can just adjust the value if needed if it's too forgiving, or too harsh.

## Technical details

Whether a doafter breaks on movement is now decided by BreakOnMove for both the target(if any) and the user.
If BreakOnWeightlessMove is set to false(true by default) then this check will be skipped when the user is weightless.

The shareddoaftersystem uses InRangeUnobstructed to determine whether the distance between the user and the target or between the user and their tool is acceptable.

It should be noted that some systems took advantage of the ability to determine whether to check either the user or the target for movement. This is no longer possible under this pr.

## Breaking Changes
All Doafters now check for distance by default.

The default movement threshold is now 0.3f instead of 0.1f

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by nikthechampiongr** [comment]
Ok then, I was asked to look into if I can just merge all the distance related thresholds into one. Please do not merge.

**Comment by keronshb** [comment]
> It should be noted that some systems took advantage of the ability to determine whether to check either the user or the target for movement. This is no longer possible under this pr.

I feel like losing this and losing the ability to not break on weightless is a huge loss.

**Comment by keronshb** [comment]
> > > It should be noted that some systems took advantage of the ability to determine whether to check either the user or the target for movement. This is no longer possible under this pr.
> > 
> > 
> > I feel like losing this and losing the ability to not break on weightless is a huge loss.
> 
> In that case I need clear direction of how maintainers want the issue resolved. Currently I am just implementing what I've been told to do on discord by other maintainers.

You could open a discussion on discord or ping the maints that requested it to discuss here so there's a central discussion place for it.

A good example is cuffs.

Cuffs should break on movement, right? Whether you move intentionally (to prevent breaking out while running away) or someone else moves you.

But what happens if you're floating? You're not moving on your own, no one else is moving you, and you're perpetually stuck uncuffing because weightlessness always keeps moving you in some way. It feels unfair. It would be nice to be able to just shut the feature off entirely instead of setting the movement threshold to something extremely large, which would make it not work as well for regular movement.

**Comment by metalgearsloth** [comment]
I think we can prune these harder but I don't want to leave you in conflict hell in the interim.

**Pull request merged**
