### PR TITLE
Janibelt whitelist fix and update

### PR DESCRIPTION
**Pull request by Sirionaut**
## About the PR

 added JanicartKeys & Plunger to janibelt whitelist - tags already existed

## Technical details
 added the proper tags to belts.yml

## Media

- [x] this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: JanicartKeys and Plunger fit into the janibelt now

### CODE REVIEW

**Review by lzk228 — CHANGES_REQUESTED** [review]
you also should to create a `JanicartKeys` tag, and give it to keys
and probably also a `LightReplacer` tag

**Comment by Sirionaut** [comment]
So the problem is obviosly deeper than just adding to the whitelist, at least from my limited programming understanding.

Through playing around I found other items have the same bug aswell, for example the handheld flashes, seeds (as mentioned in #20232 ) and the spraypainter. Also the medical belt accepts all Sprays, including weed sprays which seems not right?

And according to the code the LightReplacer should go on the JanitorialTrolley, but it doesn't.

I am also wondering if the fact that the LightReplacer entity uses the same string for id and component is a problem ?

Since the original bug is tagged as "easy" i assume someone else has an idea how to fix it, and i would greatly appreaciate a tip so i can learn more.

**Comment by Sirionaut** [comment]
> you also should to create a `JanicartKeys` tag, and give it to keys and probably also a `LightReplacer` tag

the tag "JanicartKeys" does exist, so adding it to the whitelist works, but you will still get the error msg even if it doesnt stop you from storing it.

I assume me forgetting to readd the Lightreplacer tag is the reason why the some checks failed, but since adding the tag doesnt fix the problem it seems unnecessary.

**Comment by Froozigiusz** [comment]
Please add also a plunger to the whitelist, it's really a shame that you can't have it on you in an easy way like that.

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/21212 is likely going to obsolete this.

**Comment by Sirionaut** [comment]
> #21212 is likely going to obsolete this.

How? From looking at the files, with my limited understanding it seems like the PR still uses whitelists for belts?

But i still haven't figured how to prevent the error message from poping up, but adding a few things to the existing whitelists seems reasonable, jani players want the janicartkey and plunger on their belts. Unless you hord flashlights or spacecleaner(not nice) you have no use as jani for all the space in your belt.

And from playing botany I learned that the sprays (like weed) don't fit in your belt, weed spray fitting in the medbelt but not botany belt seems silly.

**Comment by Sirionaut** [comment]
So should I update other things i noticed aswell? Weed/Pest Spray don't fit into botany belt, same with handlabeler.  If wanted I can look into other belts aswell.

**Comment by UbaserB** [comment]
can you add buckets/mouse traps to the whitelist?

**Comment by Sirionaut** [comment]
> can you add buckets/mouse traps to the whitelist? Both are roundstart jani item spawns and buckets are quite small now considering their item size change

From my understanding having the bucket, size 4, in the belt is contra the intent of the storage updates, same with the mops.
And with the new system you can store buckets in your backpack, which wasn't possible before(same with trashbags)

Mousetraps on the other hand would make more sense. Although i don't know why you would need to carry a single trap and not the whole box?

**Comment by UbaserB** [comment]
> > can you add buckets/mouse traps to the whitelist? Both are roundstart jani item spawns and buckets are quite small now considering their item size change
> 
> From my understanding having the bucket, size 4, in the belt is contra the intent of the storage updates, same with the mops. And with the new system you can store buckets in your backpack, which wasn't possible before(same with trashbags)
> 
> Mousetraps on the other hand would make more sense. Although i don't know why you would need to carry a single trap and not the whole box?

box takes space, i literally only need 1 for the pesky rodent that wants to drink my mop water.

**Review by lzk228 — COMMENTED** [review]
dunno

**Pull request merged**
