### PR TITLE
Add cartons for drinks so they dont shatter, remove duplicate items

### LINKED ISSUE #15230: Milk jugs shatter like glass
## Description

0/10 inauthentic milk experience

### PR DESCRIPTION
**Pull request by DawBla**
## About the PR

Added drinks_cartons .yml and .rsi to manage drinks that are in cartons so they don't shatter like glass containers
Removed duplicated items and cleaned up references

Resolves #15230 
**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Mumohan
- fix: Nanotrasen will no longer make cartons out of glass

### CODE REVIEW

**Comment by lapatison** [comment]
Could you do the same with soy milk and oat milk containers (and probably remove milk because rn its full duplicate idk) from Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
or it's out of scope of this PR?

**Comment by DawBla** [comment]
> Could you do the same (move, I mean) with soy milk and oat milk containers (and probably remove milk because rn its full duplicate idk) from Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml or it's out of scope of this PR?

Yeah I noticed that too when testing stuff in game, was not sure though if moving that won't cause any issues since the milk, cream etc. I changed are from the Drink category for the bartender to mix into cocktails. The duplicate Milk, soy milk and others are from food category which I assume is so they can be used by the chef to cook with. They even have different sprites so I just assumed it's made that way on purpose

Gonna take a closer look at it later today, but it should work as long as the reagents inside are the same

**Comment by DawBla** [comment]
Ill remove the duplicates

**Comment by DawBla** [comment]
Not sure what that build error means

**Review by Peptide90 — APPROVED** [review]
Fixes #15230.

Duplicates with different storage capacities will be on purpose as you say. Looks good after a cursory look. The test failing is the unrelated `SaveLoadSaveTest` so don't worry about that. Since linter and tests are passing otherwise I don't think there's an issues with the ID changes.

**Comment by Emisse** [comment]
nightmare map conflicts

**Comment by DawBla** [comment]
What the fuck happened

**Pull request closed without merging**
