### PR TITLE
Make flashes silent

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR

mutes used flash sound (excludes portable flasher)
## Why / Balance

byebye metagaming
## Technical details

something something two line deletion
## Media

flashes

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Skarlet
- remove: Removed handheld flash sounds on use.

### CODE REVIEW

**Comment by deltanedas** [comment]
media = an among with no legs (rimworld among)

the body drop sound is still very recognizable tho

**Comment by Skarletto** [comment]
> the body drop sound is still very recognizable tho

without the flash preceding it it'll be harder to metagame and could just be interpreted as someone getting electrocuted while tryna snip wires or somethin :trollface:

**Comment by EmoGarbage404** [comment]
Are revs really having that much of a skill issue that all of their conversion has to be silent?

**Comment by GreyMario** [comment]
gonna have to pass on this

don't flash roundstart and people won't hear you flashing

**Comment by deepdarkdepths** [comment]
No. Headrevs should be rewarded for proper stealthiness. If someone hears your flash and you cant convert them within the next 5 seconds, that's on you. If its that much of a problem make the flash slightly quieter instead of removing the sound entirely

**Comment by Skarletto** [comment]
> I thought about this problem before and I think a better solution is not to silence the flashes, but instead drown them out:

could always revert this PR if this is ever added godo

**Comment by Kadeo64** [comment]
> Are revs really having that much of a skill issue that all of their conversion has to be silent?

yes
revs flash roundstart and it gets metagamed instantly, code is set to red, cargo wastes their entire budget on mindshields, and the endround titlecard says "both command and revolutionaries survived" because someone rolled headrev while they were afk and didn't realize

**Comment by LookyPadooky** [comment]
wouldn't a better middleground be to only play the flash sound if you're affected by a flash? I feel like just the flash effect with no audio kinda lacks the impact unless I'm just wrong and you're doing that anyway

**Comment by FairlySadPanda** [comment]
Think @coolmankid12345 is looking into sound range atm? Which might be more elegant a fix than just removing the audio, which won't feel right

**Comment by Kadeo64** [comment]
isn't the entire point of a flash in real life to disorient someone through audiovisual disruption? the, you know, audio part is a big part of that.

**Comment by Emisse** [comment]
addressed by #23521

**Pull request closed without merging**
