### PR TITLE
Visualized regions for NavMapControl

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

This PR implements a method for adding room-bound overlays to UIs that use NavMapControl. As a demonstration of this system, the atmospheric alerts computer has been updated to display visual indicators of the rooms of the station that are monitored by its air and fire alarms.

## Why / Balance

The system provides a way to convey room specific visual information.

## Technical details

Nav map regions are color-coded overlays that can be generated for NavMapControl elements; these overlays are generated solely by the client and are only intended to be used for the purpose of visualizing an area.

The nav map region data is stored in a grid’s NavMapComponent, and are handled by SharedNavMapSystem. You define nav map regions using the NavMapRegionsProperties struct, which requires a net entity to be responsible for the nav map region (e.g., an air alarm, a nav map beacon), a list of seed points (the local tile coordinates from which the region will propagate), and the key for the UI that you intend to display the nav map region. There are optional arguments for the struct that can be used to set the color of the region, the maximum number of tiles the region can propagate, and the maximum radius the region can spread from the seed points.

Nav map regions can be added or updated using the SharedNavMapSystem.AddOrUpdateNavMapRegion function; they can be removed using the SharedNavMapSystem.RemoveNavMapRegion function. If the nav map collection is altered on the server side the component will be dirtied. Nav map region updates will be sent to the client as part of the nav map delta state.

Upon receiving a nav map state on the client, if the state contains a new nav map or a chunk was modified that intersects with a previously generated region, the associated region is recalculated. This consists of a flood fill operation, handled in NavMapSystem.Regions, that will find all reachable tiles within range of the seed points. Nav map regions will propagate over floor tiles and will be blocked by walls and airlocks (include firelocks). Flood fill operations are queued so that only one flood operation is run per nav map component per frame update.

The tiles assigned to a region during a flood fill are collated and merged into larger rectangles that span the local positions of these tiles to reduce the number of objects that need to be drawn on the NavMapControl. The list of merged tiles is fed into a NavMapRegionOverlay struct, which is stored in turn in the nav map component (in the RegionOverlays field) and can be easily retrieved using the SharedNavMapSystem.GetNavMapRegionOverlays function.

To draw the nav map regions on a NavMapControl, simply assign the overlays you wish to draw to the NavMapControl.RegionOverlays field.

## Media

[Here's a video of the system in action](https://youtu.be/CbH_U3rEIOw)

A screenshot of Box station after being hit by multiple immovable rods

rod_struck_station

Demonstration that the tile merging function can handle non-rectangular room geometries and automatically minimize the number of rectangles that need to be drawn

region_segmentation_cropped

[Update] Increased the color saturation of the regions to improve contrast with the station walls

updated_color_palette_cropped

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

NavMapState and NavMapDeltaState now require an addition argument in the form of a Dictionary<NetEntity, NavMapRegionProperties>; in most cases, this dictionary should be sourced from NavMapComponent.RegionProperties

**Changelog**

:cl:
- tweak: The atmospheric alerts computer has been upgraded to visually indicate the rooms of the station that are being monitored by its air and fire alarm systems

### CODE REVIEW

**Comment by ArtisticRoomba** [comment]
Holy shit

**Comment by UbaserB** [comment]
The color looks very poor next to the grey walls and stuff

**Comment by chromiumboy** [comment]
> The color looks very poor next to the grey walls and stuff

I'll consider a change in color palette if you have a set of hexcodes or RGBs to propose :P

**Comment by UbaserB** [comment]
> I'll consider a change in color palette if you have a set of hexcodes or RGBs to propose :P

That's probably not the way to go since it'll be very dark and bad for visibility. You have two choices, either make all the walls a ton brighter or just the walls adjacent to the rooms highlighted brighter

**Review by SlamBamActionman — APPROVED** [review]
Code looks okay to me; my one concern is performance, but if you (or another maintainer specialized in that area) can confirm it isn't an issue, then this PR is 👍

**Comment by chromiumboy** [comment]
> Code looks okay to me; my one concern is performance, but if you (or another maintainer specialized in that area) can confirm it isn't an issue, then this PR is 👍

I mean, its been fine for me during testing. The flood fills are staggered over multiple updates, and they are all on the client side, no additional load on the server there. All the region tiles drawn on the navmap are merged (see the above screenshot), so the number of rectangles that need to be drawn is surprising small

**Comment by BramvanZijp** [comment]
Merging this PR appears to be causing 2 errors on the client part of the master branch.

**Pull request merged**
