### PR TITLE
Chemvend rename

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

rename chemvend

## Why / Balance

chemvend is a really boring name tbh, nanochem also fits with the nanomed

**Changelog**

### CODE REVIEW

**Comment by VelonacepsCalyxEggs** [comment]
Dude

**Comment by potato1234x** [comment]
> Dude

What

**Comment by Holinka4ever** [comment]
Isnt like controversal?
Cause chemwend called like that to give a chemicals, not already made drugs.

**Comment by potato1234x** [comment]
> Isnt like controversal? Cause chemwend called like that to give a chemicals, not already made drugs.

raw elements could technically be considered drugs

**Comment by Holinka4ever** [comment]
Technically calling radium as drug
Or potassium.
Or sugar.

**Comment by potato1234x** [comment]
what

**Comment by Holinka4ever** [comment]
> what

It will be unintuitive. Peps would think that NanoDrug machine will give them already made drugs.
And prior of having pr that actually making some of reagents poisonos, it will be nonsense.

**Comment by potato1234x** [comment]
sounds cooler imo and its in tg so thats my reasoning

**Comment by LordEclipse** [comment]
Call it nanochem instead

**Comment by mirrorcult** [comment]
dont see a reason to change this, chemvend is fine

**Comment by potato1234x** [comment]
> Call it nanochem instead

good idea, done

**Comment by potato1234x** [comment]
starting to realise how stupid this pr is
idk why i opened it in the first place tbh

**Pull request closed without merging**
