### PR TITLE
Butcher-able gloves

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Most gloves can be butchered except boxing gloves and insuls (cutting insuls still gives the fingerless variety). Solves #21394.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- tweak: You can now butcher gloves.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Why not butcher syndie gloves? Couldn't someone meta this by attempting to cut gloves instead of trying them?

**Comment by UbaserB** [comment]
> Why not butcher syndie gloves? Couldn't someone meta this by attempting to cut gloves instead of trying them?

The syndicate accidentally butchering their chameleon gloves or thief butchering their one-of-a-kind thieving gloves:

**Comment by K-Dynamic** [comment]
> > Why not butcher syndie gloves? Couldn't someone meta this by attempting to cut gloves instead of trying them?
> 
> The syndicate accidentally butchering their chameleon gloves or thief butchering their one-of-a-kind thieving gloves:

That sounds like a skill issue on their part

Surely if moths can eat them then they should be butcherable

**Comment by deltanedas** [comment]
why cant i cut your gloves? perma!

**Comment by UbaserB** [comment]
Uhh turns out i need to fix something

**Comment by UbaserB** [comment]
yea i checked its fixed

**Review by Jezithyr — CHANGES_REQUESTED** [review]
Make Syndie gloves butcher-able as well please, we don't need more ways for people to metagame and identify syndies. If a syndie cuts their gloves it's a skill issue. Cutting is a do-after so syndies really need to be exceptionally bad to still cut their gloves.

As it stands right now this PR makes it too easy for players to get meta info

**Review by Jezithyr — APPROVED** [review]

**Pull request merged**
