### PR TITLE
Botany balancing fixes and QoL ('No romerol ambrosia' edition)

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

This PR makes a few changes to botany, mostly balance-oriented:
- Chemical mutations are picked from a weighted list instead of from literally every reagent ever
- ~~Plants will now create a popup when changing species, to make it easier to notice~~
- Species mutations are slightly more common
- Ambrosia deus and koibeans have both been nerfed
- Death nettles and blue tomatoes received slight buffs

**Note: The current reagent list is not comprehensive, would appreciate feedback about chemicals that should be added/modified**
## Why / Balance

For the chemical mutations:
- Picking from all reagents made it take a lot of reagents that were either useless, reskins of each other or both (mostly talking about bartending drinks or random useless reagents like aluminium)
- Picking from all reagents also introduced the possibility of possibly game breaking chemicals being introduced into the round (for example, romerol)

For the plant tweaks:
- Ambrosia deus and Koibeans are infamously powerful, I don't think they require further explanation.
- Death nettles had their usefulness reduced by chemical mutations, as they usually inject 3 or more chemicals at once, reducing damage output. To compensate, base damage has been upped to 15.
- Blue tomatoes wouldn't create a puddle big enough to slip in even when fully robust harvested, now they do (because it's funny)
## Technical details

The chemical mutation function now picks from a `WeightedRandomFillSolution` instead of a list of all the chemicals ever, so powerful/otherwise unobtainable chems are rarer overall, and the list of possible reagents is less bloated.
~~The plant mutation function now receives the tray's uid in order to be able to create a popup when the plant species is changed via mutation.~~
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Ambrosia Deus and Koibeans's chemical amounts have been reduced.
- tweak: Plant chemical mutations can no longer produce any reagent in the game.

### CODE REVIEW

**Review by Partmedia — APPROVED** [review]
Thank you for your contribution. This looks fine to me.

A few nits:

- To make `MutateSpecies` easier to test, I would have preferred to not pass an `EntityUid` into the function and instead return a bool representing whether or not a mutation took place.

I didn't think too carefully about the whitelist; it doesn't have Romerol so it's probably fine. Feel free to discuss with others here.

**Comment by Doru991** [comment]
1. Yeah but I'm not entirely sure how to recover the names of the previous and new plant species if MutateSpecies returns only a bool, though I suppose that's not too important since any popup at all will be enough to draw attention.
2. I feel like the list is a bit underpopulated/the higher weights don't have too much cool stuff so far, I'll wait to see if anyone else has ideas for it.
Generally my idea for the tiering was: Go from rarest - unobtainium (Chems that are either unobtainable through normal chem or very hard to do so, or are very dangerous) and the most common would be biological substances and stuff you could almost expect to be able to find in an actual plant.

**Comment by Partmedia** [comment]
> 1. Yeah but I'm not entirely sure how to recover the names of the previous and new plant species if MutateSpecies returns only a bool, though I suppose that's not too important since any popup at all will be enough to draw attention.

I see. Feel free to exercise your best judgement there. I'm actually of the opinion that there should be no popup, because it's not like a plant would loudly proclaim that it has in fact mutated. It's kind of up to you to pay attention and see that something changed, right? If somebody started hacking a door, you'd notice (or not) without a "Urist McHands has started hacking the door!"

But I'll leave this up to you.

>     2. I feel like the list is a bit underpopulated/the higher weights don't have too much cool stuff so far, I'll wait to see if anyone else has ideas for it.
>        Generally my idea for the tiering was: Go from rarest - unobtainium (Chems that are either unobtainable through normal chem or very hard to do so, or are very dangerous) and the most common would be biological substances and stuff you could almost expect to be able to find in an actual plant.

That seems reasonable. Again this looks fine to me as-is.

**Comment by DoubleRiceEddiedd** [comment]
> 2. I feel like the list is a bit underpopulated/the higher weights don't have too much cool stuff so far, I'll wait to see if anyone else has ideas for it.

I would like to see some currently unobtainable fancy looking drink(like singulo) be on the list instead of those drink bar can make by themself with ease, adding some chance that botany may provide barkeep some special drink.

**Comment by Doru991** [comment]
Not a bad idea, although in the specific case of the Singulo drink I have... another way for botany to obtain it in mind

**Comment by Doru991** [comment]
> I see. Feel free to exercise your best judgement there. I'm actually of the opinion that there should be no popup, because it's not like a plant would loudly proclaim that it has in fact mutated. It's kind of up to you to pay attention and see that something changed, right? If somebody started hacking a door, you'd notice (or not) without a "Urist McHands has started hacking the door!"

The issue is that people have complained that for some plants the sprite change is tiny or non-existent, so it can't really be observed without shift clicking the tray. And the one about hacking a door is kind of a bad example, since you will a) see the doafter above Urist's head when he unscrews the panel and b) hear the noise it makes; while plants mutating have no such cues.

**Comment by EmoGarbage404** [comment]
I'm not really a fan of the popup indicating the mutation has occurred. We have a wide variety of plant mutations with no direct indication, so not only does it feel inconsistent, it's also very "game-y" to be directly telling players that a fairly invisible change has suddenly occurred.

> The issue is that people have complained that for some plants the sprite change is tiny or non-existent, so it can't really be observed without shift clicking the tray.

I don't really see this as an overwhelming negative. It rewards players for being attentive and actually observing what has changed with their plants rather than simply waiting for popups to tell them in not-so-subtle ways.

**Comment by Doru991** [comment]
Since maintainer opinion (and my own, really) about it is overall negative, I'll be removing the popup feature in the final version of the PR. It wasn't even part of my original plan for it, more like an afterthought based on one or two players' complaints. Until then I'm still listening for more feedback regarding the chems currently in the whitelist.

**Comment by Partmedia** [comment]
> Since maintainer opinion (and my own, really) about it is overall negative, I'll be removing the popup feature in the final version of the PR. It wasn't even part of my original plan for it, more like an afterthought based on one or two players' complaints. Until then I'm still listening for more feedback regarding the chems currently in the whitelist.

Thanks. I think we've waited long enough to collect feedback on the whitelist, and hearing none I think we can go ahead and merge once the popup is adjusted.

**Comment by Sirionaut** [comment]
I would remove EZNutrient and Robust Harvest, while self fertilizing plants exist they still need outside input, but with this botany wouldn't need chem? Let plants produce the base chems and have a chemist refine/mix them.

Also charcoal, a plant can't produce 300°C in an oxygen absent environment within itself.

**Comment by DoubleRiceEddiedd** [comment]
> I would remove EZNutrient and Robust Harvest, while self fertilizing plants exist they still need outside input, but with this botany wouldn't need chem? Let plants produce the base chems and have a chemist refine/mix them.

Pretty sure due to compost and the robust harvest bottles Nutrimax vend has, botany already won't ask chemist for those two chemical. If you worry botany won't need chemist, mutagen is the one you should worry about.

**Comment by Partmedia** [comment]
Thanks for the updates. I intend to merge this as soon as I get around to testing it. I welcome anyone else to try to beat me to testing and merging :P

**Pull request merged**
