### PR TITLE
Fix engine command permissions for everyone

### PR DESCRIPTION
**Pull request by AruMoon**
## About the PR 
In this commit https://github.com/space-wizards/space-station-14/commit/221c23000e30ce78821d8306ceeecdc9279d5c21 you removed permissions for everyone from engine permissions, or you just broke it (most likely it is) and since that commit no one had permissions to quit, disconnect, launch gc and other commands except admins with HOST permission

**Screenshots**

изображение

**Changelog**

- Just added list of default commands in engineCommandsPerms.yml

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Doesn't this just duplicate the command perms?

**Comment by AruMoon** [comment]
> Doesn't this just duplicate the command perms?

Yes, it was removed from engineCommandsPerms.yml for some reason and it caused permissions error for quit and disconnect from the server for example

**Comment by metalgearsloth** [comment]
It was moved to clientCommandPerms.yml so this just means there's going to be an entire copy sitting there instead of fixing any underlying issue.

**Comment by AruMoon** [comment]
> It was moved to clientCommandPerms.yml so this just means there's going to be an entire copy sitting there instead of fixing any underlying issue.

Commands in clientCommandPerms.yml are client-side. And they work when you are not on the server, but in client. When you are connected to the server, server rewrites these permissions using engineCommandPerms.yml

**Comment by ElectroJr** [comment]
AFAICT all of these commands are client-side commands that never get sent to the sever in the first place. And to the best of my knowledge the server never somehow instructs the client to override `clientCommandPerms.yml`.

What was the actual issue / what commands were not working? Unless the deadmin command is failing me, these commands still seem to work just fine?

**Comment by AruMoon** [comment]
> AFAICT all of these commands are client-side commands that never get sent to the sever in the first place. And to the best of my knowledge the server never somehow instructs the client to override `clientCommandPerms.yml`.
> 
> What was the actual issue / what commands were not working? Unless the deadmin command is failing me, these commands still seem to work just fine?

изображение
This is how it happens

**Comment by mirrorcult** [comment]
this just sounds like `clientCommandPerms.yml` isnt in your client pack at all

**Comment by ElectroJr** [comment]
Even when joining corvax where I have no permissions at all, /quit works fine. So whatever is causing this is something else that you need to try debug, because I can't reproduce this and this PR doesn't fix whatever the underlying issue is.

**Comment by AruMoon** [comment]
> this just sounds like `clientCommandPerms.yml` isnt in your client pack at all

We found that there is something with filesystem of my system or space station 14

**Comment by AruMoon** [comment]
These permission files are missing in http://2.node.arumoon.ru:1212/manifest.txt

**Comment by AruMoon** [comment]
Ok, I found that packager doesn't include clientCommandPerms.yml when you build server without using SS14.Watchdog
And it must be fixed

**Comment by PJB3005** [comment]
You mean if you run the game server directly out of the repo with ACZ? Interesting issue. That should definitely be fixed.

**Comment by AruMoon** [comment]
> You mean if you run the game server directly out of the repo with ACZ? Interesting issue. That should definitely be fixed. 

I was lazy to setup ss14.watchdog and I just do builds by myself and run it by myself too

**Pull request closed without merging**
