### PR TITLE
Add bluespace chemistry technology

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

players suck and we cannot have nice things.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added high-capacity bluespace beakers and large-volume quick-injecting bluespace syringes.
- add: Replaced the tier 3 biochemical technology with Bluespace Chemistry.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by deltanedas** [comment]
med no longer beg sci for cloning rejoice

**Comment by EmoGarbage404** [comment]
> med no longer beg sci for cloning rejoice

we keep that on the down low :trollface:

**Comment by Matz05** [comment]
It's not good to make PRs under false pretenses, and with deliberately-misleading changelogs. If you're removing cloning, do it honestly, not by sneaking it into an unrelated PR.

**Comment by Matz05** [comment]
In fact, upon further inspection, removing cloning (and avoiding criticism for doing so) appears to have been the entire point of this PR, with the bluespace tech being cynically designed as a distraction to avert criticism. While I like the tech, and don't care one way or the other about the removal of cloning (maybe somewhat in favour actually), it needs to be explicitly stated in both the pull request and the change log that the primary purpose of this change is to remove the ability to research cloning technology, with the bluespace technology being a mostly-unrelated change bundled in.

**Comment by Emisse** [comment]
the commit name is literally remove cloning tech
image

**Comment by Emisse** [comment]
this isnt meant to be secretive

**Comment by Matz05** [comment]
...Alright, I just... don't like people being 'cute' with the changelogs and showcases, making 'secret' changes (or those couched in evasive language) and laughing at some perceived 'enemies' they're pulling one over on. It smacks of the cliquishness and secrecy that almost destroyed SS13, to me.
Perhaps I'm overreacting. Actually, I admit, I am overreacting.
Still, probably a good change in the long run. Good work, maybe describe it a bit more explicitly next time!

**Comment by S1ss3l** [comment]
The name of the PR currently is "Add bluespace chemistry technology". I feel like it's a very underhanded way of doing things too. It could have at least been stated why was cloning banished to the shadow realm.

**Comment by metalgearsloth** [comment]
> I am on the discord, my point is that a short informative blob about the pr in the description is good practice, especially when removing such popular feature that was central to a department not too long ago. I'm pretty sure I'm not the only one that would prefer looking things up directly here instead of in discord. Also that doesn't adress the point that the name of the pr and the cl are misleading.

I prefer not to have contributors harassed any more (which guess what also happened over this PR) than they already are thanks.

**Pull request merged**
