### PR TITLE
Correct some of the typos

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Removed multiple instances of programmer spelling

## Why / Balance

Some of the typos were user facing and made up look bad. stupid dog.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
fuck .swp files

**Comment by Brandon-Huu** [comment]
Oh god

**Comment by Emisse** [comment]
whats with the force pushed commits

**Comment by Brandon-Huu** [comment]
> whats with the force pushed commits

I'm awful at using git.

I included some of my vim swap files and previous commits that should not have been there. So i dropped the commits with rebase and force pushed

**Comment by deltanedas** [comment]
time to use nano son

**Comment by Brandon-Huu** [comment]
> whats with the force pushed commits

is there a way to remove them?

**Comment by Brandon-Huu** [comment]
Closed in favor of #25628

**Comment by Brandon-Huu** [comment]
I'm realizing now that, maybe i should have merged the other branch into this one instead of the other way around

**Pull request closed without merging**
