### PR TITLE
Xray cannon laser now penetrates walls

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

The laser from xray cannons now penetrates entities, deals 5/15 heat and radiation instead of 10/10 and has it's range reduced from 20 to 10 tiles(max visible range is 10.5 tiles). Structures with a high radiation resistance won't be penetrated, currently the following won't be penetrated: reinforced wall, plasma wall, reinforced plasma window, uranium wall, reinforced uranium window, radiation shutters and blast doors.

If a beam passes through someone and then gets reflected back into them it will deal damage twice.

Still has a visual bug when shooting from space into the station: the laser continues from a different location when hitting the first object that is on the station, but still ends up on the correct end location and deals it's damage in a straight line too. This visual bug also happens currently on master but is less noticeable because of the laser being stopped when hitting something.

## Why / Balance

Xray cannons shoot beams of radiation, radiation shouldn't be stopped by objects that normally don't block radiation.
Now that they go through walls they should probably do more radiation damage to represent this.

## Technical details

Instead of taking the first target from the list of targets that collisioned with the Collisionray, the entire list is looped through untill a target is found that isn't able to be penetrated. Damage is applied to the last entity hit, and all the entities the laser went through before hitting the final target.

PenetrationPower specifies the amount of targets being able to be penetrated, if not set the hitscan can penetrate an infinite amount of targets.
PenetrationLayer decides which CollisionLayer the hitscan is allowed to penetrate, if not set the hitscan can penetrate everything.
BlockedByRadiationResistance makes the hitscan get blocked by entities with the RadiationBlockerComponent, and a higher resistance on said component than the hitscan's penetration power.

## Media

The CanPenetrateMobs mentioned at the end has been replaced with PenetationLayer

https://github.com/space-wizards/space-station-14/assets/137322659/6f46f326-f278-4a80-a9b3-fda0723f93ba

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- add: Xray cannon lasers can now penetrate anything, except structures with high radiation resistance.
- tweak: Xray cannons now deal more radiation damage and less heat damage, range is reduced from 20 to 10 tiles .

### CODE REVIEW

**Comment by Ilya246** [comment]
could be reasonable to move svalinns to t2 and make xray t3

**Comment by Aexxie** [comment]
Plasma and Uranium windows should block radiation too, as well as rad shutters

**Comment by Arendian** [comment]
Made a video and fixed all the bugs I could find.

> Plasma and Uranium windows should block radiation too, as well as rad shutters
For windows I only made the reinforced versions block it, because the normal ones have the same radiation resistance as a normal wall.

> could be reasonable to move svalinns to t2 and make xray t3
I might do this in another PR together with the laser canon getting the ability to penetrate mobs. Both should probably be moved to T3 then and other balance changes like ammo could be done in that one.

**Comment by Aexxie** [comment]
> For windows I only made the reinforced versions block it, because the normal ones have the same radiation resistance as a normal wall, I updated the list of structures in the PR description.
Yeah, that's what I meant, sorry.

**Comment by metalgearsloth** [comment]
If we add this then at no point should we add any kind of thermal goggles or xray vision or the likes because this would become ridiculously overpowered.

**Comment by deltanedas** [comment]
this can already be done with particle decelerators

**Comment by metalgearsloth** [comment]
> this can already be done with particle decelerators

Didn't we nerf the shit out of them because they were also ridiculously OP.

**Comment by Kadeo64** [comment]
> Didn't we nerf the shit out of them because they were also ridiculously OP.

it turns out giving scientists the ability to spam 25 rad damage through walls was a bad idea

**Comment by TokenStyle** [comment]
> > this can already be done with particle decelerators
> 
> Didn't we nerf the shit out of them because they were also ridiculously OP.

Decrease laser distance for 5 blocks? Well, to make it much less OP, but let it get it's own niche

**Comment by metalgearsloth** [comment]
As the rest.

**Pull request closed without merging**
