### PR TITLE
THE RETURN OF ITEM STATUS

### PR DESCRIPTION
**Pull request by PJB3005**
## About the PR
This re-introduces item status IN THE PLACE IT ORIGINALLY BELONGS. ONE FOR EACH HAND. ON THE SIDES.

Also gave it a new look that matches the UI themes.

Currently working on improving the existing item status controls to be fancy. Guns already better.

## Why / Balance
The current location looks terrible and feels like an afterthought, and is covered by the inventory window. This way is how it was meant to be (I know because I meant it to be that way).

## Technical details

If there's more than two hands, the item status will use the "last active" hand of that side of the body.

## Media

image

image

## Breaking changes
Nada

**Changelog**

:cl:
- add: The item status menu has been moved to the side of the hands. There is now one for each hand.
- add: The item status menu fits with the rest of the HUD theme now.
- add: Improved, fixed and otherwise added a bunch of item status menus.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]
Failing sandbox checks.

**Comment by PJB3005** [comment]
1984 this is what I get for putting a refactor in my PR

**Comment by EmoGarbage404** [comment]
> 1984 this is what I get for putting a refactor in my PR

It was either you or me buster

**Comment by PJB3005** [comment]
merg

**Comment by K-Dynamic** [comment]
Everyday we get closer to god

**Comment by EEASAS** [comment]
> merg

people stated ingame that this looks weird, also sometimes it doesnt display the ammo counter/status for guns

**Comment by PJB3005** [comment]
> also sometimes it doesnt display the ammo counter/status for guns

That has always been the case for those guns, then. If there's any that you think should get status please do list them.

**Pull request merged**
