### PR TITLE
Resprites wooden walls

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
What it says on the tin - completely resprites wooden walls. Hopefully they'll fit in a little more against steel walls now.

## Why / Balance
Steel walls are kind of perspective-agonistic. Whoever sprited the material walls like ten years ago probably misinterpreted them, and as a result, all of them are in this weird top-down perspective that makes them look like complete and utter shit when used anywhere near solid walls. It isn't helping matters that the sprites are just ugly on their own as well.

Hopefully this makes them at least *slightly* more usable on-station.

## Media

Content Client_RKkhA16HOi
Content Client_Xp7v7NYGA5

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Resprited wooden walls. They should match the style of normal walls better now.

### CODE REVIEW

**Comment by CatMagic1** [comment]
Could use slightly more defined planks, as they are near invisible in the dark. But other than that these look pretty smooth.

**Review by Emisse — APPROVED** [review]

**Review by keronshb — CHANGES_REQUESTED** [review]
At a glance it's hard to tell if it's a wall or a floor. Could you make it a bit more defining?

**Comment by EmoGarbage404** [comment]
more specifically to what keron is saying, i think the walls need to be a touch darker so they have better contrast with the floor.

**Comment by Flareguy** [comment]
Will fix this later.

**Pull request closed without merging**
