### PR TITLE
Organize marking files for all species.

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
WHO DID THIS???
WWWHHHYYY???
image
The moth, reptilian, and diona marking sprites were all lumped together in single files with little to no organization. I've added organization for easy editing in the future. (If my organization sucks let me know, I can change it.)

## Why / Balance
Take one look at this and tell me it's acceptable.
image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
_I deeply apologize to all downstreams with more than four additional markings for the merge conflicts this will bring..._

All marking RSIs, Locales, and prototypes have been reorganized into file directories unique to each species, and a "misc" file for markings shared between species, which currently only includes gauze markings. The following is a guide on fixing additional markings that were located in the old filepaths.
- RSI files will need to be sorted into either one of the existing files, or given a file of their own. If you had a custom moth snout marking, you would place the file under `Textures/Mobs/Customization/Moth/snouts.rsi`
- prototypes will likely need to be rewritten, and have the file paths for their textures redefined. If you had a custom moth snout marking, you would put the prototype in a new file under `Entities/Mobs/Customization/Markings/Moth/snout.yml`
- locales have been organized into a single .ftl file for each species under `Locale/en-US/markings`, with the rest of the organization being done in the file itself. Markings that appear under the main customization section such as hair or facial hair are sorted into `Locale/en-US/markings/accessories`. If you had a custom moth snout and moth hair, you would place the locale for the snout directly into `Locale/en-US/markings/moth.ftl`, and the hair under a new file in `Locale/en-US/markings/accessories/moth-hair.yml`

**Changelog**
Not a player-facing change.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
Since I am almost certain multiple downstreams have custom cosmetics in these folders/filepaths, please change the Breaking Changes to briefly describe what is changed, and the steps required to fix it. Basically it should be possible to copy/paste it into #codebase-changes on Discord and downstreams should be able to follow it to fix their files.

**Comment by UbaserB** [comment]
623 changed files.. I was going to review this but nevermind it's going to take so long o7

**Comment by SlamBamActionman** [comment]
> 623 changed files.. I was going to review this but nevermind it's going to take so long o7

I'll do the first 300 and you do the last 300, deal? ;)

**Comment by UbaserB** [comment]
> I'll do the first 300 and you do the last 300, deal? ;)

i wouldnt even be able to keep track

**Comment by UbaserB** [comment]
me when 45464675 merge conflicts :godo:

**Comment by Dutch-VanDerLinde** [comment]
you should atomize it and do it species by species

**Pull request closed without merging**
