### PR TITLE
Touching up Bagel Security Brig

### LINKED ISSUE #33663: Bagel brigmed rooms do not have med access.
## Description
So if brigmed is not powergaming and only getting brig access as they should, they are unable to get to their supplies/morgue/bed or store meds in there without secoff access as well.

### PR DESCRIPTION
**Pull request by dylanstrategie**
## About the PR

General touch-up of Bagel's Security/Brig area (the separate permabrig across the hallway to the right has not been modified) with the following list of (hopefully exhaustive) changes:

- Brig Medbay airlock now is a Brig airlock instead of a Security airlock to allow access to the CMO, Brigmeds and Lawyers. All access to the Medical Cell below is still Security access, including the windoor between both, so Medical staff can't interfere with prison sentences. This fixes #33663
- The bed in the Medical Cell is now a medical bed instead of a normal bed to allow the prisoner to heal a bit better once patched up. Brig Medbay window now electrified to prevent Medical Cell prisoner from breaking out through here via windoor.
- The Brig Medbay now has an O2 medkit to allow Security to stabilize someone in crit while waiting for medical dispatch (Dexalin and Inaprovaline) and a roller bed for evacuations. Moved the Morgue tray to open above the windoor to get more usable space
- Moved a table that was blocking movement in southern Brig, moved a console to a corner in NW Brig by Warden to declutter
- Added paper bin, pen and paper to Interrogation
- Added a bottle of space cleaner and a box of spare lights in Security Break Room (top left)
- Changed Security Lobby to public access. Moved the cell recharger from there to Security Break Room and replaced it with a chess board. Added a hot drinks vending machine.
- Changed the lobby access button in the Security Front Office to an emergency shutdown button. This will drop shutters over all windows and doors out of the lobby into the hallway to allow Security Officers to control a riot.
- Security Locker Room shutter button moved to be easier to use. Added a button frame to this one (Caution) and the Janitorial Button in Brig (Janitorial)
- Massive rework of all the atmospherics layout in Security. All pipes have been rationalized in order to remove all the ones going under walls and generally declutter the pipe layout. Additionally, many rooms now have their own air alarms which link to their vents and scrubbers instead of one mega alarm in the Brig
- Basically none of the vents or scrubbers were linked. Redid everything by hand while adding air alarms. Addresses the security part of  #33488
- Fixed disposals to have a slighty easier path to repair
- Small tweaks to lighting to make things better lit while actually lowering power draw
- A MV power cable that was going under a wall was repathed
- Quality pass on airlock names, added custom naming to all buttons, windoors and the brig timers
- A few chairs and stools moved or added

## Why / Balance

Brig Medbay: Need an O2 kit to stabilize crit patients, Brig Meds and CMO should have access to it
Medical Bed in Medical Cell: Was already one in Brig Medbay, allows prisoner to go back to his proper cell and still heal well
Electrifying Brig Medbay: If you break the northern windoor from Medical Cell, you can then break the window to escape into brig lobby, unlike other cells
Space cleaner and spare lights: Standard on some other maps, this helps out the Janitor a fair bit and a partially blacked out or slippery Security is very unsafe
Security Lobby public access: The way it was set up before as a sort of "waiting room", it didn't make sense for it to be locked to Brig access, there's nothing of any value in here
Security Lobby shutdown: Allows Security to shut down their own brig entrance if things are out of control, since Bagel Brig is the easiest brig in the game to breach into (minus Reach I suppose). This also leaves an opening through Front Office for determined attackers. If you shut it down, your only remaining access (minus breaking stuff) is Security Break Room hallway access or maintenance into the same room
Piping and Atmos rework: More air alarms means easier atmospherics control for AI and Atmos Techs. Many were also going under reinforced walls which made it a nightmare to repair if a bomb went off in the Brig. Having all vents and scrubbers linked at roundstart is a no brainer.
Lights: Brig Medbay now matches lower cells with two small lights. Symmetry and redundant lights fixed in some cases. Power draw is similar if not slightly lower and the area was already well lit minus one mistake
Cell Recharger: Since Security Lobby is now all access, Security should be able to recharge their seclights without getting the battery yoinked. Before it was, people could still easily get in and running into the front lobby to recharge your stuff was a bit weird.

## Media

Full map render:
Bagel-0

Cropped Bagel Security/Brig area:
BagelSec

(I do not know how to render a pipe map)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by SlimmSlamm** [comment]
You could honestly add a door for medical to get inside BrigMed directly.

**Comment by dylanstrategie** [comment]
I think that would compromise the security of the Brig too much, plus allow a prisoner to easily leave by just opening a single airlock. The way it's set up, any medical crew with Brig access (only CMO in current build, but Brigmeds have that access too) can enter from Security Lobby and go there without issues

**Comment by dylanstrategie** [comment]
> I would replace the prisoner clothing locker with a medical locker and rearrange the room slightly (morgue to the top right corner, bed to the lower left corner, should give space for anothee locker or table)

I'm a bit apprehensive about adding more gear to either room, especially a full medical locker. I'm going to rotate the morgue tray so it opens against the door and leaves the top tile open though

> In the lower left in the locker room there appears to be a button that's blocked off by a biohazard locker, which I'd move behind the chair instead and mark with a decal

I think it's there to not impede movement. A much simpler solution would be to move the button. Also there is a decal under the biohazard locker already

**Comment by dylanstrategie** [comment]
New changes:

- Moved the Security Locker Room (bottom left) shutter button to the wall behind the chairs so it can be reached without having to open the biohazard locker or awkwardly squeezing into the doorway out
- Set the Locker Room back to two tube lights up from one, was too dark in practice. Also shifted a few lights around to optimize lighting coverage (Sec Lobby, Sec Break Room)
- Added a Janitorial Button frame to the janitorial button so it's easier to identify what it is
- Shifted the morgue tray so it opens against the windoor to Medical Cell to free up the tile above it. Added a roller bed to give something harmless to fill that space that can be of use (I still think a full medical/medicine locker would be way too much)

Main PR renders should be updated

**Pull request merged**
