### PR TITLE
The HUDening:tm: (SS13 HUD themes, Classic as default, and more)

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
This PR does a LOT of shit. So much, in fact, that I'm not going to bother writing anything specific on it and just give you a list:
- Adds the Plasmafire, Slimecore, Clockwork, and Retro themes from SS13 /tg/
- Tweaks Classic to use the smaller bottom bar sprites from SS13 (and updates it slightly)
- Makes Classic the default

## Why / Balance
Classic arguably just looks better then the current default for the most part, it has a lot more going on and is just generally cooler. Since I was adding all of these SS13 themes based on it and this had been in the cards for a while, I just figured I would get it out of the way in this PR.

All of the icons being full-sized in classic look really strange. Even though the spacing is "incorrect" compared to SS13 (for now) it still ends up looking better then it did before, in my opinion.

The new themes are all ports from /tg/ and are generally pretty well liked. Gridinv also gives them a lot more personality which is nice.

## Media
Classic (now the default:)
Content Client_TSsA3jswWe

Plasmafire:
Content Client_lq2LRYeJOJ

Slimecore:
Content Client_D7mxxhGvge

Clockwork:
Content Client_DxkqkF2qLi

Retro:
Content Client_mLJj6ExxNp

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
probably not?

**Changelog**

:cl:
- add: Added 4 new HUD themes: Plasmafire, Slimecore, Clockwork, and Retro.
- tweak: The default HUD theme is now Classic. The old default HUD theme still exists under the name "Minimalist."
- tweak: The modernized HUD theme has been renamed to "Eris."

### CODE REVIEW

**Comment by Morb0** [comment]
Glass theme 🙏

**Comment by Brandon-Huu** [comment]
why would you remove a theme?

**Comment by Flareguy** [comment]
> why would you remove a theme? I prefer modern over classic.

You can still use the old default. THIS is modernized (I don't have any other good screenshots of it on-hand:)
image

Modernized in general is very weird looking and I see no reason to continue supporting it, especially considering it's basically just Default with less color and CEV-Eris sprites. It's not like it has a gigantic maintenance cost or anything, but it just doesn't really belong in the game.

**Comment by JoeHammad1844** [comment]
syndicate theme

**Comment by JoeHammad1844** [comment]
by the way, on windows, hold alt and type 0153 on the numpad for the TM character ™

**Comment by VektorZ1** [comment]
Retro looks really weird, I don't know why you would add it

**Comment by deltanedas** [comment]
ss13 aesthetic

**Comment by Brandon-Huu** [comment]
Also, why are the sprites for the hands reversed?

**Comment by JoeHammad1844** [comment]
> Retro looks really weird, I don't know why you would add it

it's from the earliest builds of ss13

**Comment by Emisse** [comment]
Keep modernized for the people that want it, its no real maintenance burden

**Comment by Flareguy** [comment]
Alright, I'll keep modernized for now, at least until I make a replacement for it.

**Pull request merged**
