### PR TITLE
Mind ecs

### PR DESCRIPTION
**Pull request by ShadowCommander**
## About the PR

Moves functionality out of Mind and into MindSystem
Adds tests to mind code

My brain is fried on tests cases, so if there are any more that need to be get added let me know.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by AJCM-git** [comment]
Test failures are for real in this one

**Comment by ShadowCommander** [comment]
The test errors are on a test I just did cleanup on. The logic hasn't changed.

They also seem to be failing on other PRs, so not sure what's happening.

**Review by AJCM-git — APPROVED** [review]

**Review by moonheart08 — APPROVED** [review]
Clear for merge after fixed conflicts.

**Comment by moonheart08** [comment]
a.

**Pull request merged**
