### PR TITLE
simple ai visual randomization

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Just RandomSprite AI Core screen
yep, it require Loadouts, but shrimple for now

also add ArrivalsBlacklist to AI Eye
## Media

https://github.com/user-attachments/assets/acd1b562-c514-40e5-8a83-36c2c29f7903

**Changelog**
:cl:
- add: AI Core now have random screen each round

### CODE REVIEW

**Comment by Goldminermac** [comment]
Most of these seem a little too silly for me, at least to have the potential of being the starting sprite.

**Comment by Emisse** [comment]
i tink id rather just wait for it to loadout

**Comment by ScarKy0** [comment]
Id rather set it via loadout tbh

**Comment by lapatison** [comment]
Not quite sure about the `gondola` sprite. See #24655

**Comment by Everturning** [comment]
While watching the video I had a sudden urge to infiltrate the enemy organization to stop the doomsday plot while drinking a martini

**Comment by nymhole** [comment]
very cool, however the ai should be able to change it themselves, or change it before roundstart. the ai is going to have a LARGE number of verbs attached to it like in space station 13, so they should just start being added. there can also be a way to compact them into a more managable format, like a verb that opens up a list of buttons with misc ai abilities, such as change sprite, change false laws, or change hologram for AI holoprojectors.

**Comment by gostt899** [comment]
> Not quite sure about the `gondola` sprite. See #24655

maybe we can replace it with domo?

domo_kun-2860812490s

**Comment by TheShuEd** [comment]
Ok, lets wait loadouts

**Pull request closed without merging**
