### PR TITLE
coffin and two graves

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

This PR adds a coffin and two graves. I was shocked that there were no coffins in the game yet, so me as a chaplain was forced to use metal box of Satan himself (morgue).

**Media**

зображення

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Tunguso4ka
- add: Added coffin to bury your fellow spessmen with honor.

### CODE REVIEW

**Comment by lzk228** [comment]
so, grave works like crate? looking bad

**Comment by Tunguso4ka** [comment]
> so, grave works like crate? looking bad

and what do you suggest? Open it with shovel?

**Comment by brainfood1183** [comment]
open with shovel would be great, craft with shovel would be great also

**Comment by Emisse** [comment]
out of scope

**Pull request merged**
