### PR TITLE
Turn ReagentEffects into generic EntityEffects

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR changes `ReagentEffects` into a more generic `EntityEffects`; while this is mostly a namespace refactor, this opens up the effects to be used in other systems as well. 

To show this, `LavaSystem` has been removed. In its place, `TileEntityEffectSystem` has been added, which utilizes the new `EntityEffects` to achieve the same result.

## Why / Balance

`ReagentEffects` hosts a great amount of effects that are applied via Reagents; this includes adding firestacks, igniting, polymorphing, exploding, electrocution, damage etc. 

These effects are made very versatile and have great potential to be used in other systems as well, such as for melee items, stepping on tiles or activating items. At the moment those other systems have to basically recreate the `ReagentEffects`, causing unnecessary code duplication.

An example of this is the `LavaSystem`. All it does is add firestacks and ignite the entity walking on it. By making a more generic system `TileEntityEffectSystem`, lava tiles can now much more easily be expanded via yaml into acid tiles that deal caustic damage, water tiles that actually extinguish you, or maybe clown floor actually makes you laugh occasionally. 

## Technical details

- All instances of `ReagentEffect` and `ReagentEffectCondition` have been replaced with `EntityEffect` and `EntityEffectCondition`. 
- Affected scripts have been moved out of Chemistry/ReagentEffects to EntityEffects/Effects or similar.
- `ReagentEffect.cs` and `ReagentEffectCondition.cs` have been renamed to `EntityEffect.cs` and `EntityEffectCondition.cs`
- Effects _should_ support the basic `EntityEffectBaseArgs` properties to trigger. If a system wants to change the effect behavior (e.g. reagents) it can create a new args class implementing `EntityEffectBaseArgs` and cast to it in the effect.
- Some effects _currently_ only support the reagent-specific `EntityEffectReagentArgs` and not `EntityEffectBaseArgs`; not using reagent args will throw an exception. 
- Since I was moving things around anyways, all effects are now filescoped.
- `LavaSystem` & `LavaComponent` have been removed, replaced with `TileEntityEffectSystem` and `TileEntityEffectComponent`.
- `FlammableReaction` has a new property MultiplierOnExisting, used for lava tiles to ensure the same behavior where walking onto an existing tile while having firestacks doesn't light you as much.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

`ReagentEffect` and `ReagentEffectCondition` have been renamed to `EntityEffect` and `EntityEffectCondition`, and moved to a new namespace `EntityEffect` with subfolders `Effects` and `EffectConditions`, along with any existing effects.

If you have any custom reagent effects/conditions:
- Rename the base object and ensure it references the correct namespace.
- Replace `SolutionEntity` with `TargetEntity`.
- If using reagent-related args, cast the args to `EntityEffectReagentArgs`.

**Changelog**

no playerfacing changes

### CODE REVIEW

**Comment by mirrorcult** [comment]
this is in a good direction (i think we have an issue somewhere for turning this into a fully generic reusable thing) but seems inadequate, considering reagenteffects still carry a bunch of really solution-specific stuff in their args. if something else wants to call into entityeffects it has to deal with that, so its not exactly a generic system as suggested by the rename

**Comment by SlamBamActionman** [comment]
> this is in a good direction (i think we have an issue somewhere for turning this into a fully generic reusable thing) but seems inadequate, considering reagenteffects still carry a bunch of really solution-specific stuff in their args. if something else wants to call into entityeffects it has to deal with that, so its not exactly a generic system as suggested by the rename

I can agree that certain effects are still too reliant on reagent properties in the current state, though it should be possible to separate that out with a bit of elbow grease. I'll look into atomizing it further. Thanks for the comment, good to know I'm working towards a desired goal.

**Comment by moonheart08** [comment]
Agreeing with mirror, great direction on the approach, just needs better generalized. **Personally** here is what I would do:
- Create a new virtual record (non-struct) event to contain the most generic possible event arguments, like the target.
- Create a sealed inheritor of that record to  contain reagent effect specific behavior.
- Other uses, like the tile use, would have their own sealed inheritor.

This is Fast Enough for most uses, but does have the downside that we can't check at compile time if an effect is incompatible with a usecase.

**Comment by moonheart08** [comment]
> Maybe they can even be combined with [artifact effects](https://github.com/space-wizards/space-station-14/tree/master/Resources/Prototypes/XenoArch/Effects) as well?

Unlikely, they use a different, heavier weight system that uses ECS components directly instead of events to allow for dynamic behavior changes. Would be out of scope of this PR to refactor this (and I'm not sure it'd be an improvement)

**Comment by SlamBamActionman** [comment]
New commit splits `EntityEffectArgs` into `EntityEffectReagentArgs`, which is derived from `EntityEffectBaseArgs`.

_Most_ effects should now work with just `EntityEffectBaseArgs`, allowing systems to trigger them without using any of the reagent-specific data. If a system wants more specificity in how an effect is applied, they can create a new class inheriting `EntityEffectBaseArgs` and cast to it in the effect's `Effect` method. This is how `EntityEffectReagentArgs` does it, allowing it to e.g. modify the magnitude of an effect with the reagent amount. 

A few effects (mostly those that modify solutions) are currently reagent-only. They should ideally be coded for `EntityEffectBaseArgs`, but that ended up being a bit more involved and I didn't want to get stuck.

**Comment by SlamBamActionman** [comment]
Also I can't make heads or tails of the failed build message. If anyone has suggestions, I'd be happy to hear it.

**Comment by moonheart08** [comment]
> New commit splits `EntityEffectArgs` into `EntityEffectReagentArgs`, which is derived from `EntityEffectBaseArgs`.
> 
> _Most_ effects should now work with just `EntityEffectBaseArgs`, allowing systems to trigger them without using any of the reagent-specific data. If a system wants more specificity in how an effect is applied, they can create a new class inheriting `EntityEffectBaseArgs` and cast to it in the effect's `Effect` method. This is how `EntityEffectReagentArgs` does it, allowing it to e.g. modify the magnitude of an effect with the reagent amount.
> 
> A few effects (mostly those that modify solutions) are currently reagent-only. They should ideally be coded for `EntityEffectBaseArgs`, but that ended up being a bit more involved and I didn't want to get stuck.

I'd have an effect `throw NotSupportedException()` upon being used in a situation it doesn't support, instead of returning silently.

**Comment by SlamBamActionman** [comment]
Test failure is caused by serialization issues with EntityEffect. This is not caused by the PR itself, but rather an underlying problem which I do not know how to solve.

Any class that inherits EntityEffect and changes any of the properties (e.g `LogImpact`) causes the "modifies component on spawn" test error. Effects that don't touch them don't cause the error but something like the effect Ignite, which changes LogImpact to Medium, does.

But why does this only happen for TileEntityEffectComponent, and not for ReagentPrototype, or ReactiveComponent?

All other instances of components using EntityEffect (or ReagentEffect in the existing version) have the list inside of a separate class with the DataDefinition attribute. [ReactiveComponent](https://github.com/space-wizards/space-station-14/blob/6a9139b4e1427fa8ea397383c04f9391ee287fb7/Content.Shared/Chemistry/Reaction/ReactiveComponent.cs) is an example of this. For some reason this allows the effect to serialize properly. If TileEntityEffectComponent does something similar, it passes the test:
image

??

**Comment by moonheart08** [comment]
> Test failure is caused by serialization issues with EntityEffect. This is not caused by the PR itself, but rather an underlying problem which I do not know how to solve.
> 
> Any class that inherits EntityEffect and changes any of the properties (e.g `LogImpact`) causes the "modifies component on spawn" test error. Effects that don't touch them don't cause the error but something like the effect Ignite, which changes LogImpact to Medium, does.
> 
> But why does this only happen for TileEntityEffectComponent, and not for ReagentPrototype, or ReactiveComponent?
> 
> All other instances of components using EntityEffect (or ReagentEffect in the existing version) have the list inside of a separate class with the DataDefinition attribute. [ReactiveComponent](https://github.com/space-wizards/space-station-14/blob/6a9139b4e1427fa8ea397383c04f9391ee287fb7/Content.Shared/Chemistry/Reaction/ReactiveComponent.cs) is an example of this. For some reason this allows the effect to serialize properly. If TileEntityEffectComponent does something similar, it passes the test: image
> 
> ??

Remove any DataField markings from LogImpact, it shouldn't be serialized to begin with as it's an overridable property.

**Review by metalgearsloth — APPROVED** [review]
Some of the comments refer to reaction effects / reagent effects still (e.g. EntityEffect itself).

**Comment by SlamBamActionman** [comment]
> Some of the comments refer to reaction effects / reagent effects still (e.g. EntityEffect itself).

Should be fixed now, though it's not impossible I've missed some place.

**Pull request merged**
