### PR TITLE
Stop pAIs from being able to wipe each other/do other odd things, pAIs name themselves after their owners

### PR DESCRIPTION
**Pull request by 20kdc**
## About the PR
So apparently having no hands wasn't enough to stop them from being able to interact.

**Changelog**

:cl:
- fix: pAIs can no longer wipe each other or do other odd things. You can still wipe yourself with the ghost command.
- add: pAIs name themselves after their owner automatically

### CODE REVIEW

**Comment by 20kdc** [comment]
before any further stuff, should I also make them auto-rename to "XYZ's pAI"?

**Comment by 20kdc** [comment]
"GitHub Actions has encountered an internal error when running your job."

**Comment by mirrorcult** [comment]
> 
> 
> before any further stuff, should I also make them auto-rename to "XYZ's pAI"?

i say yes

**Comment by 20kdc** [comment]
well I ended up doing it anyway as a GH test-runner bug metagaming moment

**Pull request merged**
