### PR TITLE
Steal objective refactor

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
the StealTargetGroup prototype was deleted, all information from it was moved to StealConditionComponent. This makes it easier to add new steal tasks.

the name of the StealTarget group has been localized

minor edits to thief tasks: removed the task of stealing encryption keys because it was too easy (you can get them from vending).

all tasks that require stealing a circuitboard mechanism are now considered completed if the player has stolen the machine itself. This is necessary for correct work of the thief's pinpointer #23325

**Changelog**

:cl:
- remove: Removed Encryption key thief steal objective.

### CODE REVIEW

**Comment by deltanedas** [comment]
entity names can be localized is the loc change needed

**Comment by ficcialfaint** [comment]
uhhhhhh what's the point of this? entities already have localized names, just use them instead of creating seperated loc string, datafield and stuff

**Comment by TheShuEd** [comment]
ok, i remove this

**Comment by TheShuEd** [comment]
Entity names are not used here.  there may be names of groups of items.  for example: "any head cloaks"

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
StealTargetGroupPrototype should still exist as this just removes any sort of yaml validation.

**Comment by TheShuEd** [comment]
It's easier to make a new PR with changes that aren't blocked here.

**Pull request closed without merging**
