### PR TITLE
Mantles in dressers

### PR DESCRIPTION
**Pull request by Hanzdegloker**
Mantles in the dressers

## About the PR

This PR adds mantles to the spawn contents of filled dressers of all the department heads! Simple as that, the size of dressers also were increased since the HoS has too much drip.

## Why / Balance

I noticed when working on another PR, mantles do not natrually spawn within the dressers of the dept.
heads. Not only this I saw a thread from months ago about adding it to dressers but it seems it was enver
acted upon so I shall do so now.  Also sometimes a target for thieves? and it isn't a guaranteed spawn 
unless a mapper decided to place them?

## Technical details

Adds the dept. head's respective mantles to their dressers so that they may naturally spawn and do not need to be manually added by mappers. The size of dressers was increased in order to store the new mantles.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Mantles are now guaranteed to appear on every station inside the respective dept. head's dresser.

### CODE REVIEW

**Comment by MACMAN2003** [comment]
i think the maintainers want clothing things to be put in the dressers instead of the lockers

**Comment by MACMAN2003** [comment]
you could try making dressers have larger storage (or make some drip smaller)

**Comment by Hanzdegloker** [comment]
I suppose I could make dressers bigger, but I think that might be less likely to be merged than this workaround to be honest, a possible separate PR??? I would be down to do it though.

**Comment by deltanedas** [comment]
make dresser bigger drip shouldnt be going in locker

**Comment by lzk228** [comment]
nuuuh, lets make dressers bigger

**Pull request merged**
