### PR TITLE
SS14 Gender Swap Episode

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Adds 3 new reagents:
- Testosterone
- Estrogen
- Estrogen Plus

Each takes 20u to trigger their effect, changing the metabolizer's Sex and Gender, based on the chem. Estrogen Plus swaps the metabolizer's Sex and Gender between male and female. 

Currently a draft because I don't like the descriptions and guidebook stuff, I am taking suggestions, please give them.

## Why / Balance

Obvious stuff + new disguise opportunities without using TC
## Technical details

2 new reagent effects, SexChange and GenderChange. Input a Sex or Gender and the effects will change the metabolizer to said Sex/Gender, if none is set then swap the metabolizer between male/female if already male/female.
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/edb86341-c545-442a-a874-f63c8b36d3e9

Screenshot 2024-06-26 191720

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Adds Testosterone, a chemical that turns the metabolizer into a male
- add: Adds Estrogen, a chemical that turns the metabolizer into a female
- add: Adds Estrogen Plus, a chemical that swaps the metabolizer between being a male and female

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
rename estrogen plus to "gender fluid"

**Comment by EdenTheLiznerd** [comment]
As much as this would be a neat idea, I can already see it being used it for shittery by injecting people when they don't ask. I feel like this is better off as an artifact effect or something else due to it's potential to troll

**Comment by Cojoke-dot** [comment]
> rename estrogen plus to "gender fluid"

That is 100% going to end badly... its a pure white fluid...

**Comment by Plykiya** [comment]
> As much as this would be a neat idea, I can already see it being used it for shittery by injecting people when they don't ask. I feel like this is better off as an artifact effect or something else due to it's potential to troll

there's no manufacturing recipe for them

**Comment by foob1** [comment]
Maybe make this an artifact effect that is temporary?

Listen I'm gonna be real with you I'm 100% sure somebody is gonna use this to forcefully give breasts to people when they don't consent to it so um... yeah I'm not so sure about this one and I don't think all players will enjoy it. Forcing players out of their character isn't fun for everyone.

**Comment by Cojoke-dot** [comment]
> As much as this would be a neat idea, I can already see it being used it for shittery by injecting people when they don't ask. I feel like this is better off as an artifact effect or something else due to it's potential to troll

I thought about that, my idea was to require either a high amount of it or make it rare. I have not thought up a recipe for anything but Estrogen Plus right now. I put it to 20u to trigger the effect to avoid people trolling too hard with it, you would have to cuff someone or have a hypo to get enough into someone for it to trigger.

**Comment by Dutch-VanDerLinde** [comment]
make it 50 units like weh juice polymorph maybe

**Comment by Kadeo64** [comment]
okay well now it's obtainable in-game so I agree with dutch

make it higher than 20u to transition at least, maybe 30-35u? 

also might want to make an admin smite for this.

**Comment by Doctor-Cpu** [comment]
make soy milk contain traces of estrogen

**Comment by Kadeo64** [comment]
> I thought about that, my idea was to require either a high amount of it or make it rare. I have not thought up a recipe for anything but Estrogen Plus right now. I put it to 20u to trigger the effect to avoid people trolling too hard with it, you would have to cuff someone or have a hypo to get enough into someone for it to trigger.

it's extremely easy to force 20u into someone with a hypo though, which can lead to very uncomfortable RP situations. I feel like this is just going to be a major admin headache. Plus, foam bombs exist.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> make it 50 units like weh juice polymorph maybe

I wouldn't do that, since it only available from random elements the lower convert amount seems fair enough. since you will only get a few uses out of the chem if you get it.
Making it 50u or more will only give you a single use most of the time as well as make it a pain to get it to work, and may effectively make it require closer to 60-70u

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> > I thought about that, my idea was to require either a high amount of it or make it rare. I have not thought up a recipe for anything but Estrogen Plus right now. I put it to 20u to trigger the effect to avoid people trolling too hard with it, you would have to cuff someone or have a hypo to get enough into someone for it to trigger.
> 
> it's extremely easy to force 20u into someone with a hypo though, which can lead to very uncomfortable RP situations. I feel like this is just going to be a major admin headache. Plus, foam bombs exist.

thats not an issue with the chem tho, we have plenty of other fun chems that can impact players in a way that could make their round worse.

**Comment by Kadeo64** [comment]
> thats not an issue with the chem tho, we have plenty of other fun chems that can impact players in a way that could make their round worse.

dying is one thing, but near-permanently changing someone's character for the rest of the round in a way that could be really uncomfortable to them is another

**Comment by TraumaStationOfficial** [comment]
> > thats not an issue with the chem tho, we have plenty of other fun chems that can impact players in a way that could make their round worse.
> 
> dying is one thing, but near-permanently changing someone's character for the rest of the round in a way that could be really uncomfortable to them is another

Similar to how some shitter with Scissors can damage your experience by giving you a horrendous cut, except its much harder to fix

**Comment by FungiFellow** [comment]
I don't think this should be introduced at all, If I am going to troll someone with it I am going the full nine yards. Setting it at 20u does jackshit when you can forcefeed someone a pill in about a second. God forbid you make a foam nade

**Comment by VasilisThePikachu** [comment]
I wanna agree here, as much as I would like this to be a relatively low amount. Changing someone's gender in game without permission is gonna the player uncomfortable and be an admin nightmare

I think it's the main reason why no one has been commiting this in the first place.

**Comment by FungiFellow** [comment]
> I wanna agree here, as much as I would like this to be a relatively low amount. Changing someone's gender in game without permission is gonna the player uncomfortable and be an admin nightmare

It's gonna play out similar to shitters baldening the station in terms of annoyance (unless the person affected is particularly sensitive towards the topic of gender) but much harder to fix since it's not as accessible as Scissors.

**Comment by Kadeo64** [comment]
> It's gonna play out similar to shitters baldening the station in terms of annoyance (unless the person affected is particularly sensitive towards the topic of gender) but much harder to fix since it's not as accessible as Scissors.

baldening requires an avoidable doafter if you're paying attention and can be fixed with magic mirrors, this chem can be instantly injected by hypopen and can't be cured unless you find another 20u of this hyperspecific reagent.

**Comment by deathride58** [comment]
Honestly, if this is player-accessible at all, then it *needs* to be made a temporary effect (which would allow it to remain compatible with the intended purpose). Otherwise, it'll end up being used for genuinely extremely uncomfortable scenarios and other bad-faith cases more often than not.

**Comment by FungiFellow** [comment]
> ... bad-faith cases more often than not.

The Cat Ears + Janitorial Maid Dress + Stilettos + Gender Fluid :theendtimes:

But yeah this should remain strictly Admin only if implemented.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
What if there was an easy to make chem that could reset your current pronouns and sex?

**Comment by Plykiya** [comment]
> What if there was an easy to make chem that could reset your current pronouns and sex? And only have the "reset" chem be able to be made

like oculine? would be nice, would make it some normal random problem chem solves every so often

**Comment by mirrorcult** [comment]
for the reasons above with this being a chem effect we're just opting to close this after discussion, too much potential for stuff to get extremely uncomfortable in gameplay in a way that is not very fun for anyone involved

**Comment by Cojoke-dot** [comment]
Ok... so the key issue is the permanence of something that people may feel uncomfortable about and other players having the ability to do it involuntarily to a person. That makes sense, I think I'm going to make it an implant then, crafted in the medical fab, and would allow players who choose to implant themself to then use the action to change.

**Comment by mirrorcult** [comment]
that would probably be fine

**Comment by mirrorcult** [comment]
also is just thematically cooler

**Comment by catsocks1** [comment]
drinking the trans potion at 3am

**Pull request closed without merging**
