### PR TITLE
Made gasthermomachines connection pipes rotatable again 

### PR DESCRIPTION
**Pull request by Menshin**
## About the PR
Freezers and heaters were stuck in the default (south) position make proper piping sometime harder than necessary.
This PR make their conncetion pipes rotatable again.

**Media**

- [X] This PR does not require an ingame showcase, but i did it anyway.

*Eye facing south*
Content Client_JFyLk9m3DL

*Rotated 90 degrees*
Content Client_94Vg8cRIZU

**Changelog**

:cl:
- fix: Recent progress in atmos machines materials made heaters and freezers connection pipes rotatable again.

### CODE REVIEW

**Comment by ElectroJr** [comment]
IIRC there are some issues with the sprite not supporting rotations. If the machine is meant to be rotatable it needs to have directional states so that you can clearly identify the input & output sides.

**Comment by Menshin** [comment]
From my limited (i.e local) testing both the sprite rotation and pipenet connections were behaving correctly, but i'll investigate that.

**Comment by Menshin** [comment]
Ok, the whole sprite is actually rotated and localRotation is used for pipenet connection, so no problem on this front (if a bit ugly).

If that's preferred, i could always do like the PA control box and keep the freezer/heater sprite straight (facing south) and a pipe that would rotate depending on the directional state (_à la_ SS13).

**Comment by ElectroJr** [comment]
The sprite definitely should just be on its side or upside down, that looks silly. Without having to create directional sprites, I guess the main machine sprite be fixed to look south with a directional pipe sticking out makes sense. But IIRC that still requires updating the RSI to be 4 directional (even if every direction looks the same), because I don't think there is support for sprites where some layers snap to cardinal directions while others don't.

Also, the pipe should be visible even if the machine is not connected to a pipe net, so that you can always see how the machine is meant to be connected..

**Comment by Menshin** [comment]
Will do that.

**Comment by Menshin** [comment]
>But IIRC that still requires updating the RSI to be 4 directional (even if every direction looks the same), because I don't think there is support for sprites where some layers snap to cardinal directions while others don't.

Turned out you actually can (that or there's a bug with the current layers rendering implementation) by allowing the transform component to rotate while forbidding the actual sprite component to do so (4 directions layers will still snap to cardinals).

I've put two screenshots to showcase the various cases (vids were too big to be uploaded).
Should be ok for review.

**Comment by ElectroJr** [comment]
A. That was the wrong button.....

Using no-rot will break the sprite whenever it is viewed from some relative angle. E.g., see how the pipes aren't connected in this screenshot.

Content Client_0GVeaRDDtN

AFAIK the only solution is to just make the main machine sprite 4 directional


uhhh.. well I can't be bothered reverting

**Pull request merged**
