### PR TITLE
Ports the /tg/ gas analyzer sprites

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Ports the gas analyzer sprites from /tg/.
Also adds inhands using the ``electronic`` state from /tg/ because I think they fit well enough for this.

## Why / Balance
The current ones look completely out of place next to every other tool, are hard to identify at a glance as a gas analyzer, and are generally just boring as hell.

## Media
Content Client_FlpjjtXQpz

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Flareguy, mirrorcult
- tweak: Changed gas analyzer sprites.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
@mirrorcult

**Comment by UbaserB** [comment]
the blue.. is so blue..

**Comment by GoodWheatley** [comment]
didn't mirror say they think these sprites suck

**Comment by UbaserB** [comment]
If i were to give my opinion about it, i really like the sprite and really dont like the colours/contrast. It stands out being too vibrant and the icon on the screen is not visible enough.

**Comment by EmoGarbage404** [comment]
the blue could stand to be slightly less saturated, i do agree.

**Comment by Holinka4ever** [comment]
In my honest opinion, this version is lookin more out of place, rather old one.
Even its looking "boring", does this change anything? Like, its has one job, that it do perfectly.
It doesnt need tg/fication honestly.

Fan fact: tg/station stopped using that sprite and changed it to thing, that look modified radio from portal series. That doesnt make any sense ha.

**Comment by chromiumboy** [comment]
Yeah, I don't love the replacement sprites. They don't fit in well

**Comment by Terraspark4941** [comment]
if there was one sprite I disliked from TG, it would be the gas analyzer sprite
i think it *may* work with some contrast tweaking; otherwise, :-1:

**Comment by PJB3005** [comment]
This looks like somebody ripped a static fixture from a pipe rather than an item people are supposed to hold in their hands.

**Comment by Emisse** [comment]
mirror made this sprite for tg many moons ago

**Comment by mirrorcult** [comment]
everyone bullying me for my sprite ability

**Comment by mirrorcult** [comment]
we can certainly do better than this though im sure theres a better sprite somewhere

**Comment by deltanedas** [comment]
if a new sprite is needed why not reuse the shape it looks good

**Comment by PoorMansDreams** [comment]
I dunn like it uuu... uuhghh...

**Comment by GreyMario** [comment]
> The current ones look completely out of place next to every other tool, are hard to identify at a glance as a gas analyzer

Do you have your sprites backward because this perfectly describes the proposed replacement

**Comment by 13spacemen** [comment]
@Flareguy 
this isnt even what gas analyzers look like now on TG
port the latest sprite, its actually good

**Comment by TheShuEd** [comment]
I think it's been collectively agreed that this sprite is far worse than the existing one. I'm closing this PR. If the @Flareguy wants, he can reopen it with a better sprite.

**Pull request closed without merging**
