### PR TITLE
Bring back brigmedic 💙

### PR DESCRIPTION
**Pull request by Skyedra**
Recently, a well intentioned but unpopular [PR](https://github.com/space-wizards/space-station-14/pull/16069) removed brigmedic.  This PR seeks to revert it given the majority of reacts in both github and discord thread seem to be in favor of brigmedic.

## About the PR
(PR revert, no original code)

**Media**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Brings back brigmedic, my beloved.

### CODE REVIEW

**Comment by deltanedas** [comment]
you should probably move hardsuit to armory, remove disabler and stuff that removes departmental interaction

**Comment by SamuelChilcott** [comment]
> you should probably move hardsuit to armory, remove disabler and stuff that removes departmental interaction

I agree. Having a dedicated sec medic on board seems like a good addition, but their specialisation should be on being a medic, no immediately accessible hardsuit, especially no disabler etc.

**Comment by moonheart08** [comment]
I expect prompt 1984s but no, we're not readding the free hardsuit role. The game already has one of those (Paramedic) and it already causes issues. This is the same role except with security access to boot with none of the responsibilities of a medic, and it's primary use seemed to be security with a hardsuit, not an actual medic.

**Comment by metalgearsloth** [comment]
Discord discussion (outside of the 2,500 comment thread) https://discord.com/channels/310555209753690112/770682801607278632/1104619441356025896

**Comment by moonheart08** [comment]
In other words: Gimmie a well reasoned, thought out design doc for this role, what it should do,  what it should  not do and how it makes sure those things don't happen, and how it should influence the round, and I'll let you readd it.

**Comment by SEMoslaw** [comment]
I'm not a creator of this PR but those are my thoughts:

Brigmed acts as a doctor not as a security officer with medical equipment and skills. His main role is to maintain health for people in security and make sure that all prisoners are all in good health.

**Priority changes:**
-Remove disabler replace flash for self defence when interacting with prisoners.
-Move hardsuit to armory for emergency use only when large parts of the station are spaced for example.

**General behaviour:**
Brig med should never perform searches or investigations the only situation when he is allowed to be armed and take part in combat is in a full crisis situation on red alert when lethals are allowed and preferred (like nukies) or security have been seriously crippled (example: all security officers are down and only HoS is alive can then arm Brigmed appropriately to help contain situation before more officers become available again).

**Examples or role responsibilities:**
-Providing first aid to security officers and controlling that all security staff are is top condition ready to perform their duties.
-Being responsible for the health of prisoners held in brig. Making sure that they are in good health also reporting any excessive wounds to Warden in case of abuse.
-Making decisions on transporting prisoners into the medical department.
-Removal of implants (very often abused by security officers who do it on every occasion they get to check if someone is syndie without a valid reason).
-As mentioned above, in a crisis situation providing first aid to security officers in combat with major threats like nukies.

**Why Brigmed role is required:**
Because of the nature of the security department role they do get involved in a lot of combat so being able quickly regroup at brig to rearm and get first aid is really essential also it’s very common for arrested people to require some medical attention and transporting them through the station every time they decide to punch themselves in the cell or dragging medical staff who most of the rounds are very stretched is not really viable.

Looking also in the future we can expect the medical system only to grow and also to have other types of antag like revolution or blood cult where very often medical gets converted as one of the first departments which makes transporting captured crew members almost impossible to the medical department.

**Roleplay aspects:**
Why not just roleplay and get your role changed by HoP?
I do not believe this is a valid argument as roleplay should lead to some meaningful interactions, not the routine at the beginning of every shift. Following the same logic we could remove all of the gear from security and move it to the armoury and make all of the security staff roleplay to get belts, armors, stun batons, uniforms, etc before they can start their work. That would also force players to have more interaction but the question is would it actually be fun and meaningful?

Regarding the arguments that Brigmed role might be misunderstood by players leading them to play as security officer in my opinion are not really valid. 
As an example we have HoP which in many situations are known to act as security (HoPcurity) and there is no reason to replace his role with the Capitan.
Or in case of the Warden where in some instances they abandon Brig to go around chasing criminals and their role could also be filled by HoS. We could also argue that any Security officer could apply to HoP to become a Warden and anyone refusing to do so is just “avoiding roleplay”.

Both of those roles are really important even though they could be filled by others already available on the station yet they are essential and iconic. I don’t see the reason why the same logic should not be applied to Brigmed.
I think the main issue here is that Brigmed role is new and a lot of players do not understand its place. Where Warden leaving brig for 0.00001s will be called out instantly or HoP playing security will get arrested and demoted. Same thing didn’t have time to develop on our servers as this role is much younger and most players do not understand its place.

_That would be all for now I’m happy to expand on it if any of this stuff makes sense also I would probably need to clean it up a bit sorry if anything sounds weird English is not my first language._

**Comment by keronshb** [comment]
> Brigmed acts as a doctor not as a security officer with medical equipment and skills. His main role is to maintain health for people in security and make sure that all prisoners are all in good health.

Security should have to go to the medbay like everyone else.

I'm in favor of having doctors deal with medical issues in security, since it has been an issue in SS13 where servers will allow security to perform medical on eachother/prisoners (IMO they shouldn't).

I'm also in favor of not having paramedics either so doctors leave medical more. You can definitely have flavor roles for paramed and brigmed but neither should really be separate from Medical DOctor.

**Comment by SEMoslaw** [comment]
I've seen this sentiment to downscale departments to basically one job but all it does it allows people to fall into two categories:
1. Mr I stick my fingers everywhere -Type of player that has to run whole department and deal with every single thing denying opportunity to do anything for other players.
2. I'm here just to collect my gear -you see this guy at the beginning of the shift and then he dissipaters for the rest leaving his job understaffed.

MD should stay at medical and treat people. They should not wander around hanging in other departments or recover bodies under fire when people are dying in medical on the floor without even epi.
There is clearly constant need for simple medical treatment in security and there is no reason to deny it from roleplay or gameplay pov.
I'm pretty sure same thing will happen for security in future "when someone will code it" when they will be assigned to specific departments giving them basic access to those places as it was on some servers in SS13 and they will work with those departments to help maintain the order.

I'm also interested how you would plan to prevent people from healing each other? Are we removing all healing items from the station leaving the only available ones in medical in the locker or people will be banned for using a bruise pack? Or maybe the plan is that if you get shot once you will need long surgery and rehabilitation to prevent people from fixing themselves?

**Comment by deltanedas** [comment]
imo brigmed should just be to heal prisoners after shitsec beats them to crit for slipping
having it be a personal medic for all of sec is excessive, at that point why not have scimed, engimed, cargomed, bridgemed, barmed, ~~medmed~~?

**Comment by OctoRocket** [comment]
Brigmed is limited to only lrp because mrp is competent enough not to need it.

**Comment by Nutjob** [comment]
> imo brigmed should just be to heal prisoners after shitsec beats them to crit for slipping having it be a personal medic for all of sec is excessive, at that point why not have scimed, engimed, cargomed, bridgemed, barmed, ~medmed~?

It happens that prisoners try to injure or kill the officers, and not all of them are robust (especially cadets).
A couple of robust prisoners can mean up to 3-4 injured officers (plus the now-dying prisoners).
It happened to me several times to waste time and secoff to drag those prisoners to medbay, where they almost always arrive either critical or already dead.
A brigmed can at least stabilize the dying prisoners and the injured officers, making the process smoother and less painful.

> Security should have to go to the medbay like everyone else.

Everyone else doesn't have a prison/brig inside their department where riots can, and probably will, occur.

**Comment by NancokPS2** [comment]
A better solution would be to have all brigs have easy medical access like some stations due and maybe even a direct alarm to medical so the call for help is more immediate.   
If anything, give sec a good supply of stabilizing meds or a special tool for the warden that does it, so the wait for a doctor becomes less of a problem.  
If the prisoner is hurting themselves, i don't know if it was added yet, but that's what straight jackets are for.
 
I don't understand why having to interact with medical is somehow a problem when this is how the entire game is played for everyone in all cases. And yes, it's not as convenient, but it's not supposed to.    
You have an engineering issue? call engineering
Need supplies? call cargo  
Need medical attention? call medical  
    

Not even bridge, which is probably the best place to have dedicated services gets this privilege. They don't get mats for repairs nor meds for healing. The cap and all heads have to go to the same medbay.

**Pull request closed without merging**
