### PR TITLE
Removed Cannabis from thief objectives

### PR DESCRIPTION
**Pull request by ChaseFlorom**
## About the PR

Removed the cannabis objective from the thief objectives. 

## Why / Balance

20-30 cannabis leaves is neither fun for the thief, or for the botanist that they're asking to grow it. It doesn't fit with the heart of the thief objective system, as the only real way to accomplish it is to ask the botanist to grow it for you, or grow it yourself. Neither of which is stealing.

Resolve [#26321] 

## Technical details

Removed the proper .yml code.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: removed cannabis thief objective.

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
this might need to be removed in other places as well but i approve removing it in general

**Review by TheShuEd — CHANGES_REQUESTED** [review]
There are still some things that need to be removed.  prototype of the theft group, and a component in all types of cannabis

**Comment by TheShuEd** [comment]
I approve too

**Comment by ChaseFlorom** [comment]
Alright, I think I did both of those things requested.

**Review by TheShuEd — APPROVED** [review]

**Comment by TheShuEd** [comment]
Fix CL

**Comment by TheShuEd** [comment]
remove: removed thief cannabis objective

**Comment by ChaseFlorom** [comment]
Woo-hoo! Thanks.

**Pull request merged**
