### PR TITLE
Limit air lost by wrenching/breaking pipes

### PR DESCRIPTION
**Pull request by osjarw**
## About the PR
Capped the amount of air lost whenever a pipe is unwrenched/broken. (meteors)

## Why / Balance
Losing 15 minutes of accumulated air because someone unanchored a single pipe is kinda awful. This also applies to explosions. 

## Technical details
The amount of lost air is limited to the volume of the part being removed. 

Tested with Release on Oasis, @ 1500kPa, removing a single pipe used to drop distro by ~1300kPa, now the drop is ~1kPa.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Observe the air before and after the pipe is unanchored

before the change:

https://github.com/space-wizards/space-station-14/assets/62134478/6b23a9a2-f0b4-422d-b165-132c93482f06

after the change:

https://github.com/space-wizards/space-station-14/assets/62134478/b5698c38-bf52-4d1d-b7fb-55a253d157ef

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
numero uno atmos bug hunter

**Comment by Plykiya** [comment]
> numero uno atmos bug hunter

the more bugs that get solved the more I wonder how atmos ever survived before this, I always thought this was the behavior that it already had

**Comment by mirrorcult** [comment]
yeah i swear this behavior existed already? i guess not ??

**Review by mirrorcult — APPROVED** [review]

**Comment by Partmedia** [comment]
Thanks for the change. The original code seems to be trying to be clever about leaking the right amount of air such that it would fit the tile environment it was leaking to. Why don't we just get rid of that part and always leak an amount proportional to $V_{pipe} / V_{total}$?

**Comment by osjarw** [comment]
I didn't really stop to think what the original calculation was trying to do, besides calculating the amount of wanted moles with a bit iffy looking numbers. 
Because I was too tired to make sure that there exists a situation where this equation could produce valid results, I just put a safeguarding If in there(well, in this case it was a math.min).

Now that I've taken a slightly closer look at it, I think it's trying to calculate the amount of moles needed to increase the tile's pressure to whatever the pipe was at, and then pulling that many moles from the pipe network, regardless of the pipe temperature? 
So if a 4.5MPa pipe is wrenched in a spaced tile, I think it'd try to remove half a million moles from the pipe network? In laymen's terms, around 270 canisters of air. And if there is that many room temperature moles available, I think the tile pressure would become... Around 489MPa if my math is right.

This feels like they are asking "How many moles we need to get the tile to X pressure" instead of "How many moles get removed with this pipe". 

Anyways, after thinking through the math, it seems reasonable to just replace the equation with the one I added.
Am I supposed to make a new PR, since this one was merged already? Not that experienced with Github.

**Comment by Partmedia** [comment]
Yes, it's important to consider what the code was trying to do first, before you add your own changes. Otherwise we'll end up with layer on top of layer on top of layer.

I agree that does seem to be what the original code was trying to do.

Seeing that neither are terribly realistic, I would suggest removing the old calculation using your new one, since that one seems to be closer to the behavior we designed for/actually want. Please go ahead and create a new PR for that. No particular rush, since that's effectively what the code now does :)

**Pull request merged**
