### PR TITLE
Added Bananadine

### PR DESCRIPTION
**Pull request by Feluk6174**
## About the PR

Added a new narcotic named bananadine ([https://en.wikipedia.org/wiki/Bananadine](https://en.wikipedia.org/wiki/Bananadine)) and baked banana peels which are needed to get bananadine (Loosely based on the recipe found in The Anarchist Cookbook).

(BTW this is my first pr, if thers anything wrong with it, please tell me)

## Why / Balance

I thought it would be a fun thing to do if things in botany ever get slow, and a cool reference to the anarchist cookbook. And I also think it would be cool.

## Technical details

I don't think they are necessary in this case, if they are, please tell me.

## Media

https://github.com/space-wizards/space-station-14/assets/77207907/8db00193-fe2e-40ca-95bd-b2973e2be222

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No
**Changelog**

:cl:
- add: Bananadine is now a psychedelic that can be obtained by grinding baked banana peels, which can be obtained by microwaving banana peels.

### CODE REVIEW

**Comment by Doru991** [comment]
New botany drug just dropped

**Review by Partmedia — APPROVED** [review]
Thank you for your contribution. I think this is funny. Additionally, the quantities here are small enough that any sort of abuse for the amount of effort required is unlikely. I intend to merge this soon.

**Comment by Partmedia** [comment]
Additionally, please review the [Changelog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#writing-an-effective-changelog). Here, I think you can distill your change into one line.

**Comment by Feluk6174** [comment]
Ok, thanks. I condensed the changelog to one line.

**Comment by EmoGarbage404** [comment]
based and drugabuse-pilled. Hotly awaiting the jenkem pr (please don't actually)

**Pull request merged**
