### PR TITLE
add signal valve

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
can be controlled with signals like a door: open, close, toggle

behaves like a manual valve otherwise

**Media**
signals controlling

https://user-images.githubusercontent.com/39013340/227511629-b2fbbf7d-d0e8-4810-9266-d6fc55452ace.mp4

operating as a valve

https://user-images.githubusercontent.com/39013340/227511642-7f909be5-a06c-44c1-9143-d7068b438702.mp4

- [X] I have added videos to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: Added the signal valve for advanced atmosians.

### CODE REVIEW

**Comment by deltanedas** [comment]
if you are referring to #10584:
> We talked about it on discord and this needs to be something you attach to the atmos device (at least visually) you want to link to so it's visible what devices have a link to something.

that's exactly what this is, if you see a signal valve you know that whatever its attached to can be controlled remotely

**Comment by moonheart08** [comment]
Ah, aight.

**Comment by deltanedas** [comment]
@moonheart08 so is there anything i should change or is it good as it is

**Comment by mirrorcult** [comment]
this is good as is imo

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
