### PR TITLE
Makes thieving gloves sneakier

### LINKED ISSUE #21396: Thieving gloves don't function.
## Description

They simply don't do anything. People can see the do-after and also see the item transferring to your hand.

Edit: all they do is hide the text popup, which seems kind of pointless

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About the PR

Makes thieving gloves hide the do-after progress bar and item pickup animation from other players when pickpocketing/stripping targets.
Closes #21396 

## Why / Balance

#21396 Makes sense as a general complaint. People coming into the game would expect them to completely hide the action of pickpocketing another player, instead of just preventing the big warning popup.

## Technical details

Adds a field to DoAfterArgs that prevents the DoAfter from being shown to other players. Makes the stripping system use this field when stealthily stripping/planting items.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
https://youtu.be/vxrs4YOvu9E

## Breaking changes

**Changelog**

:cl:
- tweak: Thieving gloves now hide the entire pickpocketing action from other players, not just the popup.

### CODE REVIEW

**Comment by keronshb** [comment]
BLESSED

**Comment by UbaserB** [comment]
What if you can see the doafter but not anyone else? This way its hard to time your own escape when you steal something to put it in your bag/run away.

**Comment by TemporalOroboros** [comment]
> What if you can see the doafter but not anyone else? This way its hard to time your own escape when you steal something to put it in your bag/run away.

You can see your own hidden do-afters. They're just slightly transparent to indicate that they're hidden.

**Comment by TemporalOroboros** [comment]
Looks like the recording for the demo captured the wrong window. It works, but setting up the area takes like 30 minutes because we don't have any mapping tools. Since it crashed due to a physics bug I'm just going to leave it as is.

**Comment by LankLTE** [comment]
This might make them a bit strong since they’re currently priced around the way they currently work. I could also see your inventory items just disappearing because you weren’t paying attention constantly being annoying. That said, Im at least down to try this and see how it goes.

**Comment by Kayek14** [comment]
Keeping the price relitivtly low might be a good idea. Alot of traitors go loud. Keeping stealth methods cheap can be appealing. More ways to complete your objective instead of blowing up half the room or round removing a player sounds benificial.

**Comment by keronshb** [comment]
> This might make them a bit strong since they’re currently priced around the way they currently work. I could also see your inventory items just disappearing because you weren’t paying attention constantly being annoying. That said, Im at least down to try this and see how it goes.

I priced them thinking the doafter bar was invisible.

**Comment by UbaserB** [comment]
yay

**Pull request merged**
