### PR TITLE
rainbow lizard plushie

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR

Adds rainbow lizard plushie, which copies functionality from RGBee in shifting colours and being wearable

Adds plushie to arcade machine pool and presents

## Why / Balance
We love weh

Would've added to maints loot but might apparently affect performance

## Technical details

yml changes only

` Resources/Prototypes/Entities/Objects/Fun/toys.yml ` (adds rainbow lizard plushie)
` Resources/Prototypes/Catalog/Fills/Crates/fun.yml ` (added to locker loot pool)
` Resources/Prototypes/Entities/Objects/Decoration/present.yml `  (added to present loot pool)

## Media

image

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added rainbow lizard plushies, which can be found in arcade machines.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Weh

**Review by UbaserB — CHANGES_REQUESTED** [review]
Instead of being accessible from a cargo crate, can you make it accessible from the arcade machine instead?

**Review by UbaserB — APPROVED** [review]
its rare enough now so lgtm

**Comment by slarticodefast** [comment]
Tested in-game, works as intended. Should be fine if it is only available from the arcade machine.
Thank you for your contribution!

**Pull request merged**
