### PR TITLE
Reduces reflect chance for syndie swords to remain consistent with other melee reflect chances.

### PR DESCRIPTION
**Pull request by superjj18**
## About the PR
Reduces reflect chance for syndicate swords to in order to be consistent with other reflecting melee weapons.  Energy sword now has a 10% chance of reflection, and the double energy sword now has a 20% reflection chance.

## Why / Balance
I was against cap's saber reflect nerf, but now that it's been merged its only natural for the two syndicate energy swords to also be nerfed in this regard to better conform to the new balancing direction set by #26969 that does not like constant and random deflect chance.  Should a new reflect system emerge it can easily overwrite this change and return sword reflection back into the game in a more effective but still balanced state, otherwise its a very rare occurrence that should not be relied upon.  Otherwise from now on if a player wants a reliable reflect chance they must seek such in armor and shields.

I purposefully did not touch the Energy Katana, as Ninja is arguably the only human character in the game who reasonably deserves a decent reflect chance given their need for a defensive option. 

## Technical details
simple yml changes

## Media

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by metalgearsloth** [comment]
I don't see a reason why it needs to go in circles on pointless balance changes, either make the system or don't.

**Comment by superjj18** [comment]
> I don't see a reason why it needs to go in circles on pointless balance changes, either make the system or don't.

Why wasn't this the conclusion to #26969?  This change isn't really going in circles but rather simply conforming to the precedent set.  This doesn't touch captain's saber

**Comment by metalgearsloth** [comment]
> > I don't see a reason why it needs to go in circles on pointless balance changes, either make the system or don't.
> 
> Why wasn't this the conclusion to #26969? This change isn't really going in circles but rather simply conforming to the precedent set

1 of these isn't even attainable ingame, and 25% to 10% is such a minor change no one's even going to notice.

**Comment by superjj18** [comment]
> 1 of these isn't even attainable ingame, and 25% to 10% is such a minor change no one's even going to notice.

My mistake for not knowing the double blade wasn't attainable, but 25>10 is a 60% nerf, given the circumstances it is rather significant

**Comment by thebadman4662** [comment]
> > > I don't see a reason why it needs to go in circles on pointless balance changes, either make the system or don't.
> > 
> > 
> > Why wasn't this the conclusion to #26969? This change isn't really going in circles but rather simply conforming to the precedent set
> 
> 1 of these isn't even attainable ingame, and 25% to 10% is such a minor change no one's even going to notice.

60% change is rather noticeable, especially if you use epen on already decent armor to guarantee some more reflect checks thats mitigate bad RNG.

**Comment by K-Dynamic** [comment]
Actually syndicate assault borgs have deswords, and they are busted

**Comment by metalgearsloth** [comment]
> > 1 of these isn't even attainable ingame, and 25% to 10% is such a minor change no one's even going to notice.
> 
> My mistake for not knowing the double blade wasn't attainable, but 25>10 is a 60% nerf, given the circumstances it is rather significant

You can't earnestly tell me you can see a 5 second clip of 10% vs 25% reflection and tell me which one it is.

**Comment by thebadman4662** [comment]
> > > 1 of these isn't even attainable ingame, and 25% to 10% is such a minor change no one's even going to notice.
> > 
> > 
> > My mistake for not knowing the double blade wasn't attainable, but 25>10 is a 60% nerf, given the circumstances it is rather significant
> 
> You can't earnestly tell me you can see a 5 second clip of 10% vs 25% reflection and tell me which one it is.

Same could be said on 1%, but highroll clips are not the best measure, are they?

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> > > 1 of these isn't even attainable ingame, and 25% to 10% is such a minor change no one's even going to notice.
> > 
> > 
> > My mistake for not knowing the double blade wasn't attainable, but 25>10 is a 60% nerf, given the circumstances it is rather significant
> 
> You can't earnestly tell me you can see a 5 second clip of 10% vs 25% reflection and tell me which one it is.

well, since its % you could reflect 10/10 shots in both, so thats not a fair example, but this will have obvious and meta defining consequences.

**Comment by superjj18** [comment]
>well, since its % you could reflect 10/10 shots in both, so thats not a fair example, but this will have obvious and meta defining consequences.

I would argue this statement is true for the sabre rebalance as well, although admittedly, nerfing syndie borgs wasn't my intention, so I am thinking about what they SHOULD have.

edit: Maybe 40% since it's their only defensive option?

**Comment by deltanedas** [comment]
just implement scaling from low to high % based on movement speed

**Comment by LordEclipse** [comment]
> just implement scaling from low to high % based on movement speed

This, as well as if somebody is in combat stance "passively" reflecting vs  non-combat stance passive reflection.

**Comment by LordEclipse** [comment]
> > just implement scaling from low to high % based on movement speed
> 
> This, as well as if somebody is in combat stance "actively" reflecting vs non-combat stance passive reflection.

It could be a choice to actively reflect, but become unable to attack with the weapon, and passively reflect which is much lower but you can attack.

**Comment by superjj18** [comment]
> > just implement scaling from low to high % based on movement speed
> 
> 
> 
> This, as well as if somebody is in combat stance "actively" reflecting vs  non-combat stance passive reflection.

I actually like the idea of allowing esword and Sabre to be wielded, but instead of giving a damage buff it's a reflection buff.  You can either dual wield a sword and gun, or you can take a "Jedi" stance and focus on defense

Only issue is it's not very easy to animate as neither esword or Sabre would look good in the classic wield stance as the user would be holding the blade

**Comment by deltanedas** [comment]
> as the user would be holding the blade

two handed grip vs one handed

jedi master vs padawan

**Comment by keronshb** [comment]
D Sword shouldn't be touched since it's not in right now. E Sword is already low enough there's no need to make it lower.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
oh, also i think this PR forgot about the Epen

**Comment by deepdarkdepths** [comment]
> just implement scaling from low to high % based on movement speed

No one wants to code it I guess

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/pull/27151#issuecomment-2067525062

Balancing of one cap item should not be influencing antag item balancing nor should we be doing "temporary" tiny balancing changes on a whim.

**Pull request closed without merging**
