### PR TITLE
some securiby contra fixes

### PR DESCRIPTION
**Pull request by Killerqu00**
## About the PR
Seclite: allowed -> security
Trench whistle: allowed -> minor contra
Handcuffs: security -> security;command

## Why / Balance
handcuffs are mapped in bridge pretty often. Other items are used only by security and have functionality that is not supposed to be available to everyone (seclite has damage, whistle is used to stop people for a search/something else)

## Media
image
image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Seclite is now restricted to security.
- tweak: Handcuffs are now restricted to security and command.
- tweak: Trench whistle is now minor contraband.

### CODE REVIEW

**Comment by lzk228** [comment]
really don't know about the red whistle
we have like the same grey whistle from arcade, but the red one is contra and the grey one in good to go?

**Comment by Killerqu00** [comment]
> really don't know about the red whistle we have like the same grey whistle from arcade, but the red one is contra and the grey one in good to go?

doesn't the red whistle also do the alert thingie about your head?

**Comment by lzk228** [comment]
> doesn't the red whistle also do the alert thingie about your head?

looking on prototypes only the difference is grey whistle has distance 3 and red whistle has 5

**Comment by Killerqu00** [comment]
> > doesn't the red whistle also do the alert thingie about your head?
> 
> looking on prototypes only the difference is grey whistle has distance 3 and red whistle has 5

fair

**Comment by slarticodefast** [comment]
I asked the admins about the handcuffs and they said since it is mapped in the bridge it is ok. Thank you for your contribution.

**Pull request merged**
