### PR TITLE
ninja criminal records hacking

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
lets ninja hack criminal records console to set everyone to wanted, with a random funny reason.
added a few more to pad it out a bit.

## Why / Balance
people that were actually wanted can blend in better since it overwrites any reason they had

sec have to frantically start setting everyone back to none ~~before beepsky bonks them all~~

## Technical details
replaced the copypaste job of having a condition with a single bool, its now CodeConditionComponent and CodeConditionSystem. code is cleaner and less copypaste but at the cost of the prototype-based api needing you to use prototypes, which ninja already does.

## Media
cap isnt sus

cap is sus, but history is left alone

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
removed `TerrorConditionComponent` and `SpiderChargeConditionComponent.Detonated` in favour of the new `CodeConditionComponent`.

**Changelog**
:cl:
- add: Ninja can now hack criminal records consoles to make everyone wanted.

### CODE REVIEW

**Comment by TurboTrackerss14** [comment]
This just feels like an Emag PR with extra steps. 
What purpose does this serve the ninja? Feels like it would be much better suited for an emag action which are currently restricted per #24346

**Comment by deltanedas** [comment]
with sechud showing icons, it might trick secoffs into arresting people

with beepsky, :trollface:

without either, existing criminals can slip away into the shadows and ninja benefits from the chaos

**Comment by TurboTrackerss14** [comment]
>set everyone to wanted 
just turns this into "ignore the wanted list" 
better option would be to add and remove a random amount of random people to the list, while the havok would be smaller it would be much sneakier and harder to mitigate with "delete every current wanted level and start over"

**Comment by deltanedas** [comment]
it would still be trivially ignored because its a small easily metagamable list of funnies and non-crimes

**Comment by Tayrtahn** [comment]
How about reassigning existing records to different players? Harder to metagame then, since it's using actual reasons

**Comment by deltanedas** [comment]
if a ninja spawns on survival ideally this will do nothing since all the crew are NOT being shitters

**Comment by deltanedas** [comment]
merg

**Comment by deltanedas** [comment]
mmmmmmmmmmmmmmerg

**Comment by SoulFN** [comment]
Maybe you can make it as a new objective and harder to hack, for example, when ninja tries to hack console there is notification on security channel with location of console, like spacedragon rifts notification

**Comment by deltanedas** [comment]
99% sure i already made it an objective, in ss13 ai gets notification of ninja hacks so maybe could tell sec/command that

**Review by mirrorcult — APPROVED** [review]

**Comment by baddiePRO** [comment]
does the hacking overwrite existing criminal records, ie if somebody is in the system already for legitimate reasons will it change the existing reason to the made up reason?

**Comment by baddiePRO** [comment]
disregard my question, I am clearly incapable of reading

**Pull request merged**
