### PR TITLE
[Brigmedic] Something like a "big update"

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

**The work is completed.**

- [x] Custom locker.
- [x] Add existing items to locker.
- [x] Resprite jumpskirt and jumpsuit.
- [x] Resprite PDA animation.
- [x] Fix a bug with colors in the UI PDA of brigmedic.
- [x] Improve repsrite of brigmedic hardsuit. (https://github.com/space-wizards/space-station-14/pull/15461)
- [x] Remove EncryptionKeyMedical in locker after adding the headset.
- [x] Add tracking implants to the locker, for use on prisoners.
- [x] Change file names from "brigmed" to "brigmedic".
- [x] There may be something else.
> **New clothes:**
- [x] Custom headset.
- [x] Bedsheet.
- [x] _The Secret_ skirt of life.
- [x] Beret.
- [x] Armored medical gown.
- [x] Military-style medical mask.
- [x] Custom backpacks.

https://github.com/space-wizards/space-station-14/pull/15319

**Media**

The time has not come yet...
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added more things for the brigmedic, updated PDA animation, a new sprite for brigmedic locker, a custom brigmedic headset , new sprites skirts and overalls, a new beret, armored medical gown, new bags, a new military-style medical mask, and most importantly, a bedsheet, and all this for the brigmedic.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Syringe revolver?  Fires special syringe bullets that need to be researched by sci to make more of. Maybe they hold 5u of a chem.  Slow fire rate.  Probably OP as fuck. Nevermind that.

Instead like a paintball gun that fires chem balls that only really do anything if the chem has a "touch" effect?

**Comment by deltanedas** [comment]
syringe gun, from ss13

**Comment by keronshb** [comment]
> syringe gun, from ss13

Please god not this.

**Comment by GoodWheatley** [comment]
> syringe gun, from ss13

God no

**Comment by PuroSlavKing** [comment]
Considering the number of dislikes, this is a bad idea.

**Comment by MagnusCrowe** [comment]
Holobed projector for setting up an emergency triage station lol

**Comment by deltanedas** [comment]
(for surgery)

**Comment by PuroSlavKing** [comment]
> Holobed projector for setting up an emergency triage station lol

At the moment, it will look more like a joke, if it is still necessary, then after the merge of surgery.

**Comment by MagnusCrowe** [comment]
> > Holobed projector for setting up an emergency triage station lol
> 
> At the moment, it will look more like a joke, if it is still necessary, then after the merge of surgery.

It's just a week away!

**Comment by PuroSlavKing** [comment]
> It's just a week away!

surgery is a lie.

**Comment by Snowyypanda** [comment]
> > > Holobed projector for setting up an emergency triage station lol
> > 
> > 
> > At the moment, it will look more like a joke, if it is still necessary, then after the merge of surgery.
> 
> It's just a week away!

source? real?

**Comment by PuroSlavKing** [comment]
Bump 🪨

**Comment by Emisse** [comment]
lg2m

**Pull request merged**
