### PR TITLE
Revert "Replace loadbp usages with loadmap"

### PR DESCRIPTION
**Pull request by mirrorcult**
Reverts space-wizards/space-station-14#6085

This broke the `mapping` command, was spawning in unpaused maps. @metalgearsloth

### CODE REVIEW

**Comment by mirrorcult** [comment]
no idea how easy this is to fix so i'll wait for sloth to wake up and if its simple then just won't merge this

**Comment by metalgearsloth** [comment]
Map was paused when I stepped through it, at least on server. @Peptide90 needs to check they were on master first.

Also the other relevant PR is https://github.com/space-wizards/RobustToolbox/pull/2409

**Comment by mirrorcult** [comment]
morb0 bisected and this was the commit at fault, not just peptide

**Comment by metalgearsloth** [comment]
I'm suss on how rational this is, discord discussion https://discord.com/channels/310555209753690112/771041304108072961/931196383241846784

**Pull request closed without merging**
