### PR TITLE
Issue 8084 - Consistent map naming

### PR DESCRIPTION
**Pull request by FunkySphere**
## Changed all map names corresponding to their ingame type to avoid confusion 

**Tweak**: Tweaked map filenames, ids and paths, to [name]_station for stations and [name]_ship for spaceships, for the sake of consistency

**Screenshots**

**Before:**
before1
before2

**After:**
after1
after2

### CODE REVIEW

**Review by mirrorcult — COMMENTED** [review]
i'd reccommend not renaming the files themselves (or, at least not the map files, the prototype files should be fine) as that seems to have just caused quite a lot of conflicts

**Comment by Peptide90** [comment]
Oh god I can smell the conflicts.

Anyhow, we throwing PascalCase out the window for map IDs? All other IDs are in that format and imo having an underscore in is an extra character we don't need. But whatever the maintainers decide.

**Comment by FunkySphere** [comment]
I think i'll just try again with this issue

**Comment by Peptide90** [comment]
It was a valiant effort. Feel free to discuss it in the cartography discord channel

**Pull request closed without merging**
