### PR TITLE
Improve communications console countdown formatting

### LINKED ISSUE #30279: evac time in communication console is shown with a lot decimals
Screenshot_20240723_112102

### LINKED ISSUE #30491: Remaining evac time in comms ui has excessive precision displayed.
## Description
Lots of decimal places in countdown now, see screencap.

**Reproduction**
- Call shuttle
- Check comms console.

**Screenshots**
image

**Additional context**
NA

### PR DESCRIPTION
**Pull request by slarticodefast**
## About the PR
Fixes #30491
Fixes #30279

I decided it to format it into hh:mm:ss instead. The hours might be neccessary for "survive 90 minutes until evac arrives" type events.

## Why / Balance
better UI

## Technical details
Use hours, minutes and seconds instead.
If anyone knows how to do this purely in fluent, please tell me.

## Media
Screenshot (211)

Screenshot (212)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none

**Changelog**
nah

### CODE REVIEW

**Comment by IgorAnt028** [comment]
Maybe take away the hours on the timer? I don't think they'll be needed

**Comment by slarticodefast** [comment]
> Maybe take away the hours on the timer? I don't think they'll be needed

Like I said in the description: I added it in case someone does an event where the shuttle gets called at roundstart an you have to survive for 90 minutes or so until it arrives.

**Comment by Brandon-Huu** [comment]
There's a lot of space down there.

Why not ``Time remaining: X Hours, X Minutes, X Seconds``

**Comment by slarticodefast** [comment]
@Tayrtahn
`"g"` works, but shows decimal palces and there seems to be no default format without them.
I now use
`("time", diff.ToString(@"hh\:mm\:ss", CultureInfo.CurrentCulture))`
instead. Putting the format string into the ftl file seems like a bad idea since a wrong format string will cause an exception.

**Pull request merged**
