### PR TITLE
mining shuttle degentrified 

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-no more tiny fans
-no more docking airlocks
-no more uranium generator
-no more reinforced windows
-no more blast doors
-no more salvage tools or materials
feeling silly :P

image

### CODE REVIEW

**Comment by Hiucko** [comment]
What the hell is that thing

**Comment by spectralSpices** [comment]
> 

It's what the salvage shuttle was always meant to be....

**Comment by Anzarot121** [comment]
Excuse me, but how now to drag and drop resources for sale?

**Comment by naklikal** [comment]
jetpack?

**Pull request merged**
