### PR TITLE
Remove ERP from RD Figurine voiceline

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

it was missing a word lol

### CODE REVIEW

**Comment by Krovotushka** [comment]
My innocent ass didn't ever think of this phrase being ERPable

**Comment by muburu** [comment]
changelog: rd is no longer freaky

**Comment by mirrorcult** [comment]
it was definitely phrased this way intentionally (i.e. not a typo), pretty common to say this in ss13, but best to change it anyway because lol

**Comment by VasilisThePikachu** [comment]
You know what's worse... This is not the first PR removing a sussy line from the figurines

**Comment by Plykiya** [comment]
> changelog: rd is no longer freaky

what if the research director was the freak director, and instead of doing research they-- *cough cough

thanks vasilis

**Comment by EmoGarbage404** [comment]
`neurotoxin deployed. lung failure imminent. mission successful...`

**Pull request merged**
