### PR TITLE
More tiles (moved here)

### PR DESCRIPTION
**Pull request by UnderscoreX5**
Starting to add more tiles, will keep updated on the progress.

v0

image

v0.1

image
(removed the ultra bright white checkered floor, added 2 floors and fixed colors on the purple one)

v0.3 (removed corners from previous textures, fixed some textures and added a bunch of new ones)

image
image
image
(yellow-black and yellow-white squared floors are now the same layout, just like in the first pic, other 2 pics are older)

v0.4

image
image

v0.5 (added common checkered floors + renamed the "kitchen one" to a more generic name like the others)

image

v0.51 (added a grass variant + made old grass better)
image

v0.6 (added sand and a stand clear tile)
image
image
image

v0.61 (added a new variant to the stand clear tile, without text, will eventually make it loopable)
image

v0.62 (polished both the stand clear tile and the new variant)
image

### CODE REVIEW

**Comment by UnderscoreX5** [comment]
Moved here since gitkraken messed the previous one to a point it was unusable, its good now tough.

**Comment by metalgearsloth** [comment]
Any corner colourings are better off being covered under tile painting IMO.

**Comment by PaulRitter** [comment]
ye remove the decal ones, simply because adding them now & converting them later will be a major pita

**Comment by UnderscoreX5** [comment]
Yeah waiting if tech comes out soon, else i will just clean this up and it will be ready

**Comment by SweptWasTaken** [comment]
> 
> 
> Yeah waiting if tech comes out soon, else i will just clean this up and it will be ready

If this PR is in hibernation i'm just going to close it for now. You can be sure we'll need help on this stuff when the underlying system is implemented.

**Pull request closed without merging**
