### PR TITLE
Craftable explosion resistant closet :33 

### PR DESCRIPTION
**Pull request by Thinbug0**
## About the PR

Added a craftable explosion resistant closet
(my editing program chomped the quality on the lil silly showcase video, sorry qvq)

## Why / Balance

Its usage is pretty situational, but at the moment the average crew has no way to protect themselves from explosions. This closet would give them a small bit of safety, specially for storing jugs 
Not a lockable closet to prevent some goober hop from metagaming and replacing their locker with it 

## Technical details

Added 4 sprites and the ClosetBlast entity on closets.yml below the bomb suit closet, then some other stuffies so it can be crafted

## Media

https://github.com/user-attachments/assets/4fd84659-aac0-4119-b710-886e742ad217
showRecipe2
showSprite

Wanted to give some old reliable yet improvised and low tech vibes, while still feeling bulky and strong

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: 
- add: Added a recipe for explosion resistant closets!

### CODE REVIEW

**Comment by tutoumi** [comment]
I think you should replace steel by plasteel to make it rarer and more "realistic ?"

**Comment by Thinbug0** [comment]
> I think you should replace steel by plasteel to make it rarer and more "realistic ?"

that may be needed, but for how gimmicky its usage is i didnt wanna make it too annoying to craft

**Comment by slarticodefast** [comment]
Medical should not store jugs in a closet in the first place. This is treating the symptom, not the problem. It would be better to rework the smart fridge to be actually usable in my opinion.

Also your changelog is formatted wrong.

**Comment by Thinbug0** [comment]
> Medical should not store jugs in a closet in the first place. This is treating the symptom, not the problem. It would be better to rework the smart fridge to be actually usable in my opinion.
> 
> Also your changelog is formatted wrong.

what would be a more proper format for it? still struggling with that part 

and yeah if i was competent enough i would try doing something more fundamentally helpful with the smartfridge, but i dont got enough practice on this to tackle the issue itself

**Comment by thebadman4662** [comment]
Problem is CMOs(EA on every door including CHEMLAB my beloathed) and doctors being dumbassess, medbay have doors and rooms for a reason. Threat of tiders and clowns already is enough to keep juglocker out of ward. Bottles exist for a reason too, though on some maps you gotta raid other departments to have enough glass.

And even if medbay bombing happens, its on chemists to keep backups so doctors are not back to topicals age.

**Comment by slarticodefast** [comment]
> what would be a more proper format for it? still struggling with that part (thought of it being "Added a recipe for..." or "name can now be crafted!" instead but wanted to be more consistent with previous pr's changelogs)

It has to be formatted like in the PR template so that the bot can read and add it to the in-game changelog (you need the `- add:` part in a new line). Your choice of words is fine. 

grafik

**Comment by slarticodefast** [comment]
> and yeah if i was competent enough i would try doing something more fundamentally helpful with the smartfridge, but i dont got enough practice on this to tackle the issue itself

> Bottles exist for a reason too, though on some maps you gotta raid other departments to have enough glass.

Yeah, I'm not an expert on UI design either, but maybe the smart fridge should be able to store jugs similar to how the chem dispenser does it and be able to dispense bottles filled with the reagent of your choice by clicking a button in a menu. Each doctor could then carry a few of those in their belt. It could also allow to directly draw from the jugs with a syringe.

**Comment by Ilya246** [comment]
could have just blast closet which costs steel/rods and reinforced blast closet which costs plasteel and is much tankier

perhaps make the reinforced version capable of (barely) surviving a nuke, except maybe not pointblank

**Comment by Thinbug0** [comment]
After more coffee and thinking back on it yeah, it feels goofy and out of place for it to use normal steel, so swapped it with plasteel

Also yeah its most common usage would end up being for stuff like jugs, but i still think giving the average tider a way to deal a bit with explosions would be nice. Though at the moment the resistance isnt enough to protect small stuffies like glass, but im not sure if giving it like a %99 resistance would be way too much

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer vote and it was decided not to merge this for the reason already mentioned above. Med should not be encouraged to put a bomb-proof closet into their treatment room. Thank you for your contribution.

**Pull request closed without merging**
