### PR TITLE
The purge

### PR DESCRIPTION
**Pull request by Pixeltheaertist**
## About the PR

Removed a lot of mentions of some "station" or something. 
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Pixeltheaertist** [comment]
IGNORE THIS SORRY I DIDN'T MEAN TO MERGE TO WIZDEN

**Comment by mirrorcult** [comment]
you will be boiled

**Comment by lzk228** [comment]
planet station 14 real

**Comment by Pixeltheaertist** [comment]
forgive me 😔

**Comment by deltanedas** [comment]
boiled by boiler from rmc14

**Comment by ScarKy0** [comment]
You will not be forgiven.

**Pull request closed without merging**
