### PR TITLE
HUGE HEALTH ANALYZER UPDATE MERGE ASAP (Chem readouts and reduction of readout bloat)

### LINKED ISSUE #19354: Medbay has no way to tell what chemicals are in a patient
## Description
Chemicals have small overdose thresholds, and when medbay cannot tell what chemicals are in someone, overdoses can happen, especially if two different medics are trying to treat one person.
Having to remember what chemicals are in someone, and guess how many have been metabolised adds unnecessary complexity.

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

This pr IS AMAZING BECAUSE IT REMOVES DAMAGE READOUTS OF 0 AND ALSO reads out the chemicals in the chemstream of the mob.

**_BASICALLY THIS IS REALLY NICE BECAUSE A LOT OF TEXT BLOAT IS GONE!!!!_**

## Why / Balance

Resolves #19354

## Technical details

I just added checks to the health analyzer readouts to snip out empty values. I also added the function to read chems to the health analyzer.

## Media

image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
## Breaking changes

Literally nothing it makes the game a lot better!!

**Changelog**

:cl: Whisper
- add: The health analyzer now reads out the chemicals within a person!
- fix: Removed empty damage values from the analyzer, making it more clean.

### CODE REVIEW

**Review by DrSmugleaf — APPROVED** [review]

**Review by DrSmugleaf — APPROVED** [review]

**Comment by LankLTE** [comment]
Pretty sure showing chems inside someone has been denied in the past- I’m honestly not a huge fan of it and feel it should be something separate

**Comment by QuietlyWhisper** [comment]
> Pretty sure showing chems inside someone has been denied in the past- I’m honestly not a huge fan of it and feel it should be something separate

Wasn't sure about that honestly because it would just replicate 90% of the health analyzer code. It'd literally just be a health analyzer with a different readout

**Comment by QuietlyWhisper** [comment]
> > Pretty sure showing chems inside someone has been denied in the past- I’m honestly not a huge fan of it and feel it should be something separate
> 
> Wasn't sure about that honestly because it would just replicate 90% of the health analyzer code. It'd literally just be a health analyzer with a different readout

It'd be really easy though!

**Comment by LankLTE** [comment]
> Wasn't sure about that honestly because it would just replicate 90% of the health analyzer code. It'd literally just be a health analyzer with a different readout

Could just be part of IVs or something when those are added- I think personally managing bloodstream chems is a big part of Med's skill cap so I'm personally reluctant to remove this.

#19545 was also denied and it did effectively the same thing, so while I won't close this myself right now the general opinion is that health analyzers shouldn't have this function.

**Comment by QuietlyWhisper** [comment]
I'm gonna be real honest it's not as big as a gamechanger as it seems, chems dont last very long either way, it's kinda just a nice addon if anything. It's been in ss13 fairly long on tg and cm13 as far as I know, even if we dont use ss13 as examples for design, it really doesn't add much besides minor situational convince and a "cool" factor at best?

**Comment by LankLTE** [comment]
Don't think it's really "minor situational convenience" when you can use it to instantly tell if you're about to OD someone, if someone is poisoned, and what they're being poisoned by. These are all things you can figure out yourself, but recognizing those symptoms is something doctors have to learn and I don't think that's really a bad thing.

**Comment by QuietlyWhisper** [comment]
edit: added reagent colour

**Comment by QuietlyWhisper** [comment]
ALSO I think the health analyzer itself is the true convivence, as you said, any skilled doctor can work without one? In which case this only assists newer doctors learning the effects of medicines and toxins!

**Comment by lzk228** [comment]
showing chemicals should be able only with health analyzer upgrade cartridge, like on paradise station

**Comment by deltanedas** [comment]
or maybe a sci unlock that doesnt add a recipe but enables chem on all analyzers

**Review by LankLTE — CHANGES_REQUESTED** [review]
The Bloodstream readouts either needs to be removed or made a Sci research

**Comment by MiraslauKavaliou** [comment]
I really like the bloat removal, but I agree that the bloodstream read seems a bit op, also just kinda adding that bloat back into it. still really cool stuff

**Comment by CatMagic1** [comment]
Add the bloodstream read to some sort of advanced body exam thing, I don't think those examination rooms in most medicals really do anything mechanics-wise right now.

**Comment by QuietlyWhisper** [comment]
later

**Comment by MiraslauKavaliou** [comment]
@QuietlyWhisper if you are not willing to do it would you mind someone else doing the bloat removal part of your pr?

**Comment by QuietlyWhisper** [comment]
It'll be up in 12 hours

**Comment by QuietlyWhisper** [comment]
@LankLTE On the other topic I need to know now if making this a seperate tool is going to be insta denied so I dont waste time on it if thats alright

**Comment by LankLTE** [comment]
> @LankLTE On the other topic I need to know now if making this a seperate tool is going to be denied so I dont waste time on it if thats alright

No worries. I have no issues with it being a separate tool and to my understanding nobody else does either.

**Pull request closed without merging**
