### PR TITLE
Fix server crash when the seed extractor is used on the dev map

### PR DESCRIPTION
**Pull request by MossyGreySlope**
## About the PR
Attempting to use the seed extractor in the dev map would crash the server. This was resolved by marking the `InteractUsingEvent` as handled inside `SeedExtractorSystem`.

Also, thanks to Slartibartfast for walking me through this.

## Technical details
Added a line to `SeedExtractorSystem.OnInteractUsing` to make the event as handled. This prevents the `SharedInteractionSystem.InteractDoAfter` from attempting to access the plant item, which is been queued for deletion.
Since the check that the item isn't deleted is done using a `DebugTools.Assert`, this issue likely only affected the development server.

## Media
carrot

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
No changelog - minor bugfix.

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]
I tested it and it works as intended.
Thank you for your contribution and your first PR!

**Comment by slarticodefast** [comment]
Doing some testing with your PR to find out if merging master fixes problem with the labeler changes.

**Comment by SaphireLattice** [comment]
This does happen outside of dev map, right?

**Comment by slarticodefast** [comment]
> This does happen outside of dev map, right?

It's a debug assert so it will always happen when running the game in dev mode, independent of the map.
However the debug assert is there for a reason and was indicating something unintended was happening with the event chain for the interaction (in this case forensics being applied to an entity that already got deleted). This PR fixes it.

**Comment by chromiumboy** [comment]
Thanks for the fix

**Pull request merged**
