### PR TITLE
more traitor flavor

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

added even more traitor variation. all the copypastas are graciously "borrowed" from /tg :trollface: 
also did sum slight changes to antag selection locales.

## Why / Balance

more text, more lore, more rp

## Technical details

changed objectiveIssuer to work more like an intermediate thing for locales
added factions to ObjectivesTextGetInfoEvent. this will be useful if blood brothers ever get added.
and please don't look in ObjectivesSystem, the summaries are god awful.

## Media

image
image

some "slight" changes
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added even more traitor variation.
- tweak: Slightly changed antag selection text.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
While I do enjoy the addition of lore, it seems strange that these different flavor texts appear to imply rule enforcement with extra objectives, playstyles and allies demanded, especially since this isn't mechanically supported in any way.

If this is something we want then that's probably fine, but at that point it feels like we should start with a design document so it can be properly evaluated, instead of pushing it in via flavor text.

**Comment by lzk228** [comment]
i dont like that wall of text is getting bigger and bigger

**Comment by whateverusername0** [comment]
> While I do enjoy the addition of lore, it seems strange that these different flavor texts appear to imply rule enforcement with extra objectives, playstyles and allies demanded, especially since this isn't mechanically supported in any way.

people will figure it out somehow :trollface:

**Comment by SlamBamActionman** [comment]
> > While I do enjoy the addition of lore, it seems strange that these different flavor texts appear to imply rule enforcement with extra objectives, playstyles and allies demanded, especially since this isn't mechanically supported in any way.
> 
> people will figure it out somehow :trollface:

More that we'll get a bunch of people in #admin-questions asking "Do I *have* to kill people from WaffleCo as a DonkCo traitor?", "I rolled MI13 but wanted to go loud, can I?" or "Can I work with Syndies as a Corporate Climber?"

**Comment by whateverusername0** [comment]
> More that we'll get a bunch of people in #admin-questions asking "Do I have to kill people from WaffleCo as a DonkCo traitor?", "I rolled MI13 but wanted to go loud, can I?" or "Can I work with Syndies as a Corporate Climber?"

these questions can be answered with a single word 🤷

**Comment by SlamBamActionman** [comment]
My point is players shouldn't be made to wonder about that sort of stuff in the first place 😛

**Comment by Mirino97** [comment]
I have some concerns in regard's to this implementation in it's current state:

- The information is added to the same existing antag text. This gives an impression that being a "Gorlex Marauder" is important, and that there's something special in being one, like different rules, different ways to play, etc. It does NOT convey that this is just fluff.
- We don't have lore. Most players have no experience with ss13, so we're gonna be relegated to explaining the difference between Gorlex, Donk Co. and whichever other fluff lore companies there are.
- This adds fluff in the middle of important text, making it bigger unnecessarily (there are issues with the already big text and infodump in our current state)

If you somehow manage to separate this and make it clear that it's nothing but fluff, unimportant text, it'd be much better. I do understand this'll be a bit of a challenge though given how the UI's set up.

**Comment by whateverusername0** [comment]
i can try cutting off the goal part from the character menu and leave only the name and allies, will that make it any better?

**Comment by Nimfar11** [comment]
I think it can only be taken as a guideline, not a rule. An opportunity for a player to play out certain behaviours.
And about the lore, you could always make books with some extracts on the Syndicate corporations, and add them to the libraries.

**Comment by GroggleG** [comment]
This just seems like its trying to add round variation, I mean if you want more flavor of life why not work on other antags? I like the idea of varied corps but it just aint clicking for me.

**Comment by Emisse** [comment]
side note the orange text spam at the start of the game is insane especially if you have a special role, someone needs to make it more readable and not all bolded. this pr would exacerbate it greatly

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by whateverusername0** [comment]
some people just don't like to read 😔

**Comment by whateverusername0** [comment]
made the wall of text a little smaller, also changed the color of briefing
image
opinions?

**Comment by UbaserB** [comment]
imo it should be different colours, not all yellow or all red.

**Comment by BolloTea** [comment]
It looks very interesting and delicious in its own way.  There are many questions, but they are clearly not for this PR.  But, I noticed one thing - many are already complaining about the impossibility of selecting/configuring a list of agents, this is not critical, but still... There are those who, for example, would not want you to serve them looters (although I still believe that the variety that  forces you to adapt - it’s still better than indulgence in the form of choosing antagonists and play styles that are more pleasant to you, sorry, I digress).   Perhaps, after all, a slider with the choice of individual corporations would be a soft, albeit bloated way out of the situation

**Comment by BolloTea** [comment]
Sorry, this is in case there are rules between different corporations and styles of play on these agents

**Comment by ElPidor** [comment]
> some people just don't like to read 😔

I like reading and you forgot make some for these two boys 
 "S.E.L.F."
      &
"Interdyne Pharmaceutics"

**Comment by whateverusername0** [comment]
> > some people just don't like to read 😔
> 
> I like reading and you forgot make some for these two boys "S.E.L.F." & "Interdyne Pharmaceutics"

i don't got imagination nor time to make some quality text for these bad boys sorry mate

**Comment by ElPidor** [comment]
LETS GOOOO 
BEST PR EVER 
0 DAY LEFT

**Comment by whateverusername0** [comment]
reopen plis

**Comment by UbaserB** [comment]
I cant reopen it because it was either force-pushed or recreated

**Pull request closed without merging**
