### PR TITLE
Cog update

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR
Updated the bridge, updated east medbay to make it less cramped, added some atmos alert consoles, and also some other minor changes

## Media

Cog-0

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

no changelog

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
image


Decal is layered wrong in east med

**Comment by Emisse** [comment]
that can be a renderer error

**Comment by Hanzdegloker** [comment]
> that can be a renderer error

On both the renders?

**Comment by Spessmann** [comment]
yes, known error on both map renderer and the map website

**Comment by Spessmann** [comment]
in game its fine

**Pull request merged**
