### PR TITLE
Give dragon pull ability

### PR DESCRIPTION
**Pull request by SoulFN**
## About the PR

This PR adds puller components to base dragon prototype.
## Why / Balance

Because many corpses flies to the space and gibbed for entire round, also dragon can't eat them.
## Technical details

Just added component to the dragon prototype.
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
<!-- Add a Changelog entry to make players aware of new features or changes that could affect gameplay.
Make sure to read the guidelines and take this Changelog template out of the comment block in order for it to show up.
Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog. --!>

 :cl:

- add: Dragon can now pull things using tail.

### CODE REVIEW

**Comment by Boaz1111** [comment]
your changelog vanished

**Comment by SoulFN** [comment]
> your changelog vanished

Fixed

**Comment by Boaz1111** [comment]
"- add: Dragon can now pull things using tail."
should be on a separate line I think

**Comment by slarticodefast** [comment]
the `- add:` part needs to be in a new line below the cl symbol or the bot won't be able to read it

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
Has been approved by the character/species work group in the internal discussion, just needs a second maintainer to merge according ot the new policy.

**Pull request merged**
