### PR TITLE
HoP gets an armor vest in their locker

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

the hop now gets a slim basic armor vest in their locker
## Why / Balance

they are an important person, and being basically defenseless other than their disabler doesn't make sense for such a high risk role, its pretty easy to just emag their office open and gun them down with a viper, with this chance you will a least need to hit all your shots.

 it also kindof curbs powergaming because most hops just go to sec for gear and take more than they need
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
no change lig

### CODE REVIEW

**Comment by lzk228** [comment]
hop can go to hos amd ask for vest

**Comment by JoeHammad1844** [comment]
the point is that hop wont feel the need to go to sec, and therefore wont powergame like "hmm why not take a sec belt"

**Comment by mirrorcult** [comment]
you have been repeatedly told to stop wasting our time and making powercreep PRs that you know will just be closed and explicitly warned that there will be consequences if continued, in accordance with that warning you have been banned from contributing further

**Comment by mirrorcult** [comment]
times you have been warned or told to stop/change your behavior:
https://github.com/space-wizards/space-station-14/pull/18945#issuecomment-1672667015
https://github.com/space-wizards/space-station-14/pull/20785#issuecomment-1751180017
https://github.com/space-wizards/space-station-14/pull/18905#issuecomment-1678231208
https://github.com/space-wizards/space-station-14/pull/20389#issuecomment-1728903701
https://github.com/space-wizards/space-station-14/pull/20338#issuecomment-1725381469
https://github.com/space-wizards/space-station-14/pull/20215#issuecomment-1722429913
https://github.com/space-wizards/space-station-14/pull/20170#issuecomment-1719268009
https://github.com/space-wizards/space-station-14/pull/19249#issuecomment-1682006105
https://github.com/space-wizards/space-station-14/pull/18867#issuecomment-1669277662
https://github.com/space-wizards/space-station-14/pull/20970#issuecomment-1763223197
https://github.com/space-wizards/space-station-14/pull/20991#issuecomment-1763222548
https://github.com/space-wizards/space-station-14/pull/20182#issuecomment-1720385690

you can appeal this ban through our forums at https://forum.spacestation14.io

**Pull request closed without merging**
