### PR TITLE
Makes Eyepatches Flippable

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR
Adds the ability to flip eyepatches over to the other eye! No more having to deal with one eye always being the greedy one who gets to see!. This is the second time I made this pr due to me blowing up the last one.

## Why / Balance

Some people want their eyepatch on the other eye
## Technical details

Using FoldableClothing in the same way as the soft hats do but inverts the icon rather than using 2 separate files
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/da666925-8689-483a-b552-b912f7a7455f

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Cojoke-dot, AJCM-git
- add: You can now flip your eyepatches to the other eye! Yarrrrr!

### CODE REVIEW

**Review by metalgearsloth — DISMISSED** [review]
Thought I mentioned this before but does setting the scale not set it, because duplicating sprites for this is really bad.

**Comment by Cojoke-dot** [comment]
> Thought I mentioned this before but does setting the scale not set it, because duplicating sprites for this is really bad.

I got it to work with the icon of course, but I am not sure if I can get it to work with the clothing on the body. I'm going to work on it to see if I can get it to work, but I am not entirely sure if I can... I would need to swap the left and right sides of the sprite for the head, then flip the front and back to get them to align.

**Comment by Cojoke-dot** [comment]
> Thought I mentioned this before but does setting the scale not set it, because duplicating sprites for this is really bad.

Due to scale being applied to all layers, I can't use it to flip the eyepatch without flipping the entire player

**Comment by Cojoke-dot** [comment]
Oh… ha! I forgot about this PR, thanks for finishing it!

**Pull request merged**
