### PR TITLE
Fix atmos UI decimal separator bug

### PR DESCRIPTION
**Pull request by koteq**
## About the PR / Why / Technical details / Media

**Note:** the description was heavily modified, keep that in mind, as some comments down below may be slightly off.

Let's start with a simple diagram
`UI <--> Client <--> Server`

1. When a user inputs a decimal number on the UI, they put it into a text field
2. The Client then receives the input as a string and parses it into a float
3. After parsing, the Client updates the UI, formatting the parsed float back to string
4. There is also a Client-to-Server serialization, but _I do not touch it_ in this PR

Currently, the parsing of the user input (step 1) is done [in the current culture](https://github.com/space-wizards/space-station-14/blob/b1e2e4c16e8a6ada1c3291a56ec2df517305cfcd/Content.Client/Atmos/UI/GasPressurePumpBoundUserInterface.cs#L47-L53) which is [set by the localization manager](https://github.com/space-wizards/RobustToolbox/blob/61385b7c2167160ee6dfa1a4b800c0938c5dc7b2/Robust.Shared/Localization/LocalizationManager.cs#L303-L320), meaning it only supports a single decimal separator specified in the culture. The representation (step 3), however, [uses the invariant culture](https://github.com/space-wizards/space-station-14/blob/b1e2e4c16e8a6ada1c3291a56ec2df517305cfcd/Content.Client/Atmos/UI/GasPressurePumpWindow.xaml.cs#L47-L50), which always uses dot as a decimal separator regardless of the current culture.

This causes a bug when the localization manager uses a culture that has a decimal separator other than dot. Take a look at the recording featuring [Russian Corvax build](https://github.com/space-syndicate/space-station-14) of the game.

https://github.com/space-wizards/space-station-14/assets/1192090/cecc689b-4fb9-4a5b-87ae-2cc4ad8fe764

```
user input  → parsed float → UI representation
"1.23" → n/a → "0"
"1,23" → 1.23 → "1.23"
```

The bug can't be reproduced when the localization manager's default culture uses dot as decimal separator.

https://github.com/space-wizards/space-station-14/assets/1192090/8ab10e62-e174-425f-8a1c-83840479f6c5

---

To address the bug, I propose the following changes:
- Change how user input parsing (step 1) of decimal numbers works to support both dots and commas so that it matches [current standards](https://en.wikipedia.org/wiki/Decimal_separator#Current_standards)
- Change the UI representation formatter from invariant culture to the current culture
- Slightly increase the pressure input sizes to fit the `101.375` value on screen as a neat QoL change

---

## Open questions

- I'm not certain if the introduction of yet another parser aligns with the vision of the core contribution team, I'm open to a discussion on where the new helper methods should live

### CODE REVIEW

**Comment by arimah** [comment]
As someone whose native locale uses commas, I'm in two minds over this change.

On the one hand, I suppose it's kinda nice that I can use my numpad to input the decimal separator. Plus, most people are used to reading numbers in their own culture's formatting conventions.

On the other hand, in an English-language UI, I've come to expect English conventions, and I can never be _quite_ sure whether a comma is meant to be read a Swedish decimal separator or an English thousands separator, _especially_ if there are exactly three digits after the comma. "123,456" – is that 123-thousand-456, or 123-decimal-456? The game doesn't really use thousands separators anywhere (for better and worse), but I dislike the uncertainty. Especially when a misinput results in _three orders of magnitude_ of error!

(For full stops, with the specific combination of Swedish and English, there is no ambiguity, as Swedish uses a space for the thousands separator: `123 456,78`, hence a period could only mean decimals to my mind. Other languages use `.` as the thousands separator, so have fun figuring out what `123.456` is.)

**Comment by koteq** [comment]
I believe the server dictates the culture via the content package.
https://github.com/space-wizards/space-station-14/blob/d75d7d71879d8ef9251b5fab4b44489fb8b92cde/Content.Shared/Localizations/ContentLocalizationManager.cs#L12-L13

Meaning if you play on en-US servers you'd have to input dots, but on ru-RU server you'd see commas and have to input either commas or dots, which is why I added the fallback parsing.

**Comment by arimah** [comment]
Hmmm, alright, so I didn't initially read the code as thoroughly as I thought! If the server actually dictates a locale, then the client should always use that same locale, imo. I don't know offhand whether the client sets its own locale based on the server somehow. If it _doesn't_, then all the parsing code should _probably_ use the same locale as the server, which it currently doesn't _appear_ to do. Otherwise I expect it'll be hella confusing when the server formats it as "123.456" in places while expecting you to input "123,456". :D

**Comment by koteq** [comment]
I think the localization manager is shared between client and server, it's in the Client.Shared namespace for that reason.

**Comment by koteq** [comment]
Just to showcase the bug. Here is how it looks like on the upstream build.
```
input → result
"1.23" → 1.23
"1,23" → 123
```

https://github.com/space-wizards/space-station-14/assets/1192090/8ab10e62-e174-425f-8a1c-83840479f6c5

---

And there is Russian Corvax build.
```
input → result
"1.23" → 0
"1,23" → 1.23
```


https://github.com/space-wizards/space-station-14/assets/1192090/cecc689b-4fb9-4a5b-87ae-2cc4ad8fe764

**Comment by arimah** [comment]
Input and display _really_ should match each other, or there _will_ be confusion on some level. The way `,` turns into `.` after parsing is super weird and jarring. It's better than a value becoming something else, for sure, and luckily Russian doesn't use dots in their numbers, but it's still weird...

---

Look how silly this is: https://unicode.org/cldr/charts/44/by_type/numbers.symbols.html#4ec3d1b99830ad07

Fuck, why are humans so complicated and inconsistent.

**Comment by koteq** [comment]
I'm thinking of adding a new method to the RobustToolbox, wonder if @PJB3005 gonna like it or not.

```diff
diff --git a/RobustToolbox/Robust.Shared/Utility/Parse.cs b/RobustToolbox/Robust.Shared/Utility/Parse.cs
index 7f7490ef8..e20c4319b 100644
--- a/RobustToolbox/Robust.Shared/Utility/Parse.cs
+++ b/RobustToolbox/Robust.Shared/Utility/Parse.cs
@@ -1,5 +1,6 @@
 ﻿using System;
 using System.Globalization;
+using Robust.Shared.Localization;
 
 namespace Robust.Shared.Utility;
 
@@ -123,6 +124,12 @@ public static class Parse
         return TryFloat(text, NumberStyles.Float, out result);
     }
 
+    public static bool TryFloat(ReadOnlySpan<char> text, ILocalizationManager loc, out float result)
+    {
+        return float.TryParse(text, NumberStyles.Float, loc.DefaultCulture, out result) ||
+               float.TryParse(text, NumberStyles.Float, loc.FallbackCulture, out result);
+    }
+
     public static bool TryFloat(ReadOnlySpan<char> text, NumberStyles style, out float result)
     {
         return float.TryParse(text, style, CultureInfo.InvariantCulture, out result);

diff --git a/Content.Client/Atmos/UI/GasFilterBoundUserInterface.cs b/Content.Client/Atmos/UI/GasFilterBoundUserInterface.cs
index 87dcabe8db..f794978cb2 100644
--- a/Content.Client/Atmos/UI/GasFilterBoundUserInterface.cs
+++ b/Content.Client/Atmos/UI/GasFilterBoundUserInterface.cs
@@ -4,6 +4,7 @@
 using Content.Shared.Atmos.Piping.Trinary.Components;
 using JetBrains.Annotations;
 using Robust.Client.GameObjects;
+using Robust.Shared.Utility;
 
 namespace Content.Client.Atmos.UI
 {
@@ -51,9 +52,8 @@ private void OnToggleStatusButtonPressed()
 
         private void OnFilterTransferRatePressed(string value)
         {
+            var loc = IoCManager.Resolve<ILocalizationManager>();
+            var rate = Parse.TryFloat(value, loc, out var parsed)? parsed : 0f;
 
             SendMessage(new GasFilterChangeRateMessage(rate));
         }

diff --git a/RobustToolbox/Robust.Shared/Localization/ILocalizationManager.cs b/RobustToolbox/Robust.Shared/Localization/ILocalizationManager.cs
index 6ff2044b9..b602091ce 100644
--- a/RobustToolbox/Robust.Shared/Localization/ILocalizationManager.cs
+++ b/RobustToolbox/Robust.Shared/Localization/ILocalizationManager.cs
@@ -67,15 +67,15 @@ namespace Robust.Shared.Localization
         CultureInfo? DefaultCulture { get; set; }
 
         /// <summary>
-        ///     Load data for a culture.
+        ///     Fallback culture to be used in the absence of the main one.
         /// </summary>
-        /// <param name="culture"></param>
-        void LoadCulture(CultureInfo culture);
+        CultureInfo? FallbackCulture { get; set; }
 
         /// <summary>
-        ///     Sets culture to be used in the absence of the main one.
+        ///     Load data for a culture.
         /// </summary>
-        void SetFallbackCluture(CultureInfo culture);
+        /// <param name="culture"></param>
+        void LoadCulture(CultureInfo culture);
 
         /// <summary>
         ///     Immediately reload ALL localizations from resources.
diff --git a/RobustToolbox/Robust.Shared/Localization/LocalizationManager.cs b/RobustToolbox/Robust.Shared/Localization/LocalizationManager.cs
index 223497bd1..5addc4d0f 100644
--- a/RobustToolbox/Robust.Shared/Localization/LocalizationManager.cs
+++ b/RobustToolbox/Robust.Shared/Localization/LocalizationManager.cs
@@ -188,6 +188,25 @@ namespace Robust.Shared.Localization
             }
         }
 
+        public CultureInfo? FallbackCulture
+        {
+            get => _fallbackCulture;
+            set
+            {
+                if (value == null)
+                {
+                    throw new ArgumentNullException(nameof(value));
+                }
+
+                if (!_contexts.ContainsKey(value))
+                {
+                    throw new ArgumentException("That culture is not yet loaded and cannot be used.", nameof(value));
+                }
+
+                _fallbackCulture = value;
+            }
+        }
+
         public void LoadCulture(CultureInfo culture)
         {
             var bundle = LinguiniBuilder.Builder()
@@ -204,16 +223,6 @@ namespace Robust.Shared.Localization
             DefaultCulture ??= culture;
         }
 
-        public void SetFallbackCluture(CultureInfo culture)
-        {
-            if (!_contexts.ContainsKey(culture))
-            {
-                throw new ArgumentException("That culture is not loaded.", nameof(culture));
-            }
-
-            _fallbackCulture = culture;
-        }
-
         public void AddLoadedToStringSerializer(IRobustMappedStringSerializer serializer)
         {
             /*
```

**Comment by koteq** [comment]
It's a bit simpler. We have a string representation and a number representation. The flow is:
Player inputs a string → string gets converted to a number  → number gets formatted and displayed back as a string

We can have a relaxed parsing of the player input, allowing both commas and dots to be used as a decimal separator because it's [the standard](https://en.wikipedia.org/wiki/Decimal_separator#Current_standards).

On the way back, the number should be formatted according to the LocaleManager's culture of the client, as it's the most flexible way, which can enable clients to have any culture they want.

**Comment by koteq** [comment]
> Looking at the existing code there was an effort to implement the first option.

I think the LocalizationManager is flexible enough to enable clients to have a preference over the server. Even though it isn't implemented yet. I stuck with the first option because it's simpler given the codebase state.

**Comment by koteq** [comment]
> The player - whatever local culture they are using - gets native UI, regardless of server. Client parses the values before sending them over.

After thinking on the topic overnight, the second option is indeed superior, but only when the game client gets bundled with multiple languages, allowing the player to select one in the preferences screen. For now, while the game only allows a single language, the second option would result in an inconsistent look. For example, it doesn't make a lot of sense using Japanese dates formatting from the player's local culture if they are seeing English UI.

**Comment by koteq** [comment]
I updated the PR, yep, with a force-push 🤷 
And updated the PR's description to better state the issue and the intention

Marking it as ready for review, back again

**Review by PJB3005 — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
