### PR TITLE
Slows down parallax significantly.

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
https://cdn.discordapp.com/attachments/896189989665275954/983527030836588584/Space_Station_14_2022-06-06_19-22-59.mp4

## Changelog
:cl: moony
- tweak: Slowed down parallax significiantly. Space should feel much, much vaster now.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Looks a little too slow?

**Comment by DogZeroX** [comment]
Sad, liked when it looked like space dust.

**Comment by moonheart08** [comment]
> Looks a little too slow?

The uppermost layer repeats after about 1km. It's slow if you're moving slow, for shuttles it's fairly fast.

**Comment by PJB3005** [comment]
> Sad, liked when it looked like space dust.

/vg/'s parallax has an explicit space dust layer that can be toggled on and off in preferences

**Pull request merged**
