### PR TITLE
Suit Storage Visual Change

### PR DESCRIPTION
**Pull request by Alekshhh**
## Media

image
flat ver
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Yuoko** [comment]
sorry but it doesn't look attractive...

**Comment by Alekshhh** [comment]
this isn't a dating app

**Comment by EmoGarbage404** [comment]
image
mockup for flat-topped suit storage. just something to ponder.

**Comment by Rainbeon** [comment]
Flat Top mockup looks really pretty to me

**Comment by UbaserB** [comment]
i love the flat-topped so much more

**Comment by Alekshhh** [comment]
add it nerd

**Comment by Emisse** [comment]
flad toppe good can you do that

**Comment by Alekshhh** [comment]
done

**Pull request merged**
