### PR TITLE
give lawyers their own headsets!

### PR DESCRIPTION
**Pull request by randy10122**
## About the PR

gives the lawyer their own special headset with the service encryption key in it. also removes the service headset from the lawdrobe - might maybe put the new headset in there instead?
no new sprite because it doesnt really need one imo

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: randy
- add: Added a new headset, the Law & Order headset!
- add: Lawyers have been issued with a new, shiny headset. Shininess not guaranteed.

### CODE REVIEW

**Comment by deltanedas** [comment]
no common is very based if intended

**Comment by randy10122** [comment]
> no common is very based if intended

that is entirely my bad and i forgot that headsets dont come with common by default

**Comment by QuietlyWhisper** [comment]
> > no common is very based if intended
> 
> that is entirely my bad and i forgot that headsets dont come with common by default

Its a rather new change with the upcoming telecoms update, no worries!

**Comment by deltanedas** [comment]
like me, you commited engine somehow
1. rebase to before the funny commit
2. merge upstream
3. git restore RobustToolbox
4. commit and forcepush

**Comment by randy10122** [comment]
> like me, you commited engine somehow
how the fuck did i manage that
ill fix it when i wake up tomorrow

**Comment by ZoldorfTheWizard** [comment]
i don't see why we need to create a whole other headset why not give the lawyer the encryption key so they can insert it into their headset at round start?

**Comment by randy10122** [comment]
> I don't see why we need to create a whole other headset. 

you say this like its a difficult process - i say why not? it adds a little more flavour to the game

> why not give the lawyer the encryption key so they can insert it into their headset at round start? 

well thats just a weird backwards way to do it. at that point why arent you giving the lawyer their own headset?

**Comment by randy10122** [comment]
oh lord am i stupid

**Comment by randy10122** [comment]
git is driving me mental so im going to close this one and just open a new pr for the sake of my mental health

**Pull request closed without merging**
