### PR TITLE
Station Variations only apply to the largest grid

### LINKED ISSUE #25745: BasicRoundstartVariation needs to only affect station
having the fucking nukie shuttle and syndicate outpost and cargo shuttle and salvage shuttle trashed to hell is insane. also having lights out on these things is bad especially for antags roundstart, needs to be bound to station grid

### PR DESCRIPTION
**Pull request by blueDev2**
## About the PR

Station Variations only apply to the largest grid
Partially Fixes #25745
## Why / Balance

Messes and broken lights are (from what I understand) only supposed to spawn on the main station, not the cargo shuttle or other smaller grids associated with the station
## Technical details

Using the largest grid within the station (which should be the main station grid), get all the tiles and use the tile locations to spawn messes and trash.
When performing checks on lights, do not replace lights with broken lights if the light fixture is not on the largest grid within the station.
## Media

https://github.com/space-wizards/space-station-14/assets/89804215/e01f285b-f498-41a3-be69-5d5bb55527d1

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: blueDev2
- fix: Station Variations only apply to the largest grid

### CODE REVIEW

**Comment by wrexbe** [comment]
Idk the reasoning behind the original, but why not call it a GridVariation, and add some kind of variation component to a grid, when you want it to vary. You could then give the station and shuttle different amounts of trash, because you could configure the grids differently.

**Comment by mirrorcult** [comment]
because its supposed to apply per-station, the problem here is just that smaller grids are weighted more for some reason when they shouldn't be. its some bug in `TryFindRandomTileOnStation`, this isnt the correct solution

**Review by mirrorcult — CHANGES_REQUESTED** [review]
see above, the underlying bug should be fixed

**Comment by blueDev2** [comment]
1. I don't see the comment you placed
2. So it is correct behavior to have trash in all grids of the station, it's just random selection was favoring smaller grids?

**Comment by blueDev2** [comment]
Oh wait, are you just telling me to fix the function TryFindRandomTileOnStation so that it evenly chooses tiles properly?

**Comment by wrexbe** [comment]
Not saying what to do one way or the other here, but the reason small tiles get flooded is cause of this logic

```
for (var i = 0; i < puddleTiles; i++)
{
    if (!TryFindRandomTileOnStation(args.Station, out _, out _, out var coords))
        continue;

    var sol = proto.Pick(Random);
    _puddle.TrySpillAt(coords, new Solution(sol.reagent, sol.quantity), out _, sound: false);
}
```

**Comment by blueDev2** [comment]
Actually I think the problem is that TryFindRandomTileOnStation does not care about the size of the grid
All grids have an equal chance of being chosen, but smaller grids appear to be favored because they have less tiles to fill

**Comment by metalgearsloth** [comment]
Mapgrids don't store how many valid tiles there are so without looking at the code I doubt the random tile finder is considering grid mass.

**Comment by blueDev2** [comment]
Also TryFindRandomTileOnStation can simply fail if it choses a tile that is covered by a wall or has no atmos

**Comment by blueDev2** [comment]
I'm probably gonna close and remake this since all my current commits are going the wrong way
I didn't know that it's intended that the shuttle and other places should have trash, just less of it

**Comment by wrexbe** [comment]
The tile count has a relationship to mass for the grid, so you might be able to use that to bias the random towards grids, or randomly pick how many messes each grid needs

**Comment by blueDev2** [comment]
Made a new PR
https://github.com/space-wizards/space-station-14/pull/26694

**Pull request closed without merging**
