### PR TITLE
Add interlocking airlocks

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
This adds interlocking airlocks, airlocks that enforce correct cycling. Requested by @Emisse .

What this actually does is (1) add a signal transmitter to airlocks so that airlocks can inform machine links that they are open, and (2) add a signal receiver to airlocks so that a signal can bolt the door. This would be pretty useless if you only had one door, but the trick is if you have two, you can cross-link them so that opening one door bolts the other, and vice versa.

### Example with 1 Door

https://user-images.githubusercontent.com/3229565/219935008-33468b7e-9686-4ada-879e-57fb694a3fea.mp4

### Example with 2 Doors

Okay, but what if you have a door that's two wide? Here you need to be able to combine the two signal transmitters from the two adjacent doors into one signal that can be fed into both of the bolt signals on the other side. This special machine is called an "dual airlock controller 3000," but I have opted to name it what it's called on Earth, namely, an "OR gate."

**Exercise for the reader:** Why is an OR gate necessary? Why can't I just link both the "door open" signals from one side to each of the bolt signals on the other side?

https://user-images.githubusercontent.com/3229565/219935199-966a59c1-fda3-4c27-99a4-7126ffba737f.mp4

### The Ugly
This PR contains 3 commits.

Machine linking currently only supports one type of event, the `SignalReceivedEvent`. This means that it makes no concept of "0" or "1", or the difference between a "0 to 1" (like when opening an airlock) or a "1 to 0" (when closing an airlock). This makes it challenging to define what an OR gate should do. In the first commit, add a `enum SignalState` that represents 3 signal states to machine linking:

- A "momentary" pulse, which is the current behavior of machine links
- A steady "low"
- A steady "high"

The second commit adds the necessary transmit and receiver components to the airlock. Due to the design of the multitool (`SignalLinkerSystem`), it is impossible to complete links to a single entity with both transmit and receive components. Therefore, in this commit we also adjust the behavior of the multitool so that it can link such entities. Unfortunately, this breaks the "repeat link" feature where you can touch one transmitter and link multiple receivers; with this change, you have to walk back to the transmitter each time you want to link a receiver. This makes it painful, but not impossible, to link long conveyor belts.

The third commit adds the OR gate. This is necessary to support airlock cycling for two-wide doors.

There are YML's with untranslated text. I will fix those if there is conceptual agreement that this implementation would be acceptable.

### FAQ
**Doesn't this bypass access controls and allow anybody to bolt/unbolt doors?**
No, in order to complete a machine link, you already need to have access to the door.

**Media**
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: notafet
- add: Airlocks can now be configured to interlock and cycle correctly.

### CODE REVIEW

**Comment by Emisse** [comment]
i like this but is there a way to achieve behavior where when the outside one is opened it force closes the inside one, or if youre entering from outside and the inside is open it force closes the inside one. maybe there could be a sensor in the middle that detects spacing and closes the uninteracted one.

**Comment by Partmedia** [comment]
> i like this but is there a way to achieve behavior where when the outside one is opened it force closes the inside one, or if youre entering from outside and the inside is open it force closes the inside one. maybe there could be a sensor in the middle that detects spacing and closes the uninteracted one.

What should happen if something prevents the inside door from closing, e.g. a machine or person in the way? Doors also don't close instantly, and for a brief moment both doors would be open.

Doing this by bolting the doors means that you still have to cycle the airlock manually, but it stops you from making a mistake.

**Comment by Emisse** [comment]
youd delay the first door from opening until the other is closed

**Comment by Partmedia** [comment]
> youd delay the first door from opening until the other is closed

I think that would be possible. It would take an additional "someone tried to open me" transmit signal and some additional logic, maybe implemented in-game using more logic gates. SCI could have something to invent!

I think this change would be more suitable for a future PR, because the implementation in this PR (by cross-bolting) is probably as simple as it can get, and because it touches some machine linking bits that could be controversial, I want this to be small.

**Comment by Emisse** [comment]
yea i think this pr is fine overall and works for what we want this to achieve, maybe in the future two separate door prototypes could be made for one as an interior and one as exterior and they could just be linked

**Comment by deltanedas** [comment]
ive played with this on mining station it's very nice

**Comment by ike709** [comment]
In SS13, some servers have buttons next to each airlock to trigger cycling from the outside. There's also a wallmount computer inside for controlling atmospheric cycling (actually repressurizing or depressurizing when moving from/to a vacuum) and forcibly overriding the cycling to open/close both.

**Comment by Partmedia** [comment]
Will resolve merge conflicts and integration tests (yaml complaining about components added after init) if there is conceptual approval.

**Comment by AJCM-git** [comment]
> The second commit adds the necessary transmit and receiver components to the airlock. Due to the design of the multitool (SignalLinkerSystem), it is impossible to complete links to a single entity with both transmit and receive components. Therefore, in this commit we also adjust the behavior of the multitool so that it can link such entities. Unfortunately, this breaks the "repeat link" feature where you can touch one transmitter and link multiple receivers; with this change, you have to walk back to the transmitter each time you want to link a receiver. This makes it painful, but not impossible, to link long conveyor belts.

Cant you make it opt-in whether or not you can repeat link?

> if there is conceptual approval.

We do want this mechanic, yeah

**Comment by Partmedia** [comment]
> > The second commit adds the necessary transmit and receiver components to the airlock. Due to the design of the multitool (SignalLinkerSystem), it is impossible to complete links to a single entity with both transmit and receive components. Therefore, in this commit we also adjust the behavior of the multitool so that it can link such entities. Unfortunately, this breaks the "repeat link" feature where you can touch one transmitter and link multiple receivers; with this change, you have to walk back to the transmitter each time you want to link a receiver. This makes it painful, but not impossible, to link long conveyor belts.
> 
> Cant you make it opt-in whether or not you can repeat link?

Maybe, ideas welcome for this. The old logic stores a transmitter and receiver inside the multitool and has logic like:

1. If you poked a transmitter, replace the stored transmitter.
2. If you poked a receiver, replaced the stored receiver. If I have both, pop up the window.

This doesn't work with entities with both transmit and receive (like the new airlocks), because:

1. You poke the door, but you have no control over the order of event subscriptions, i.e. do you get the transmit side or receive side first?
2. When you go and link the other side, it uses the same order (the order where the event subscriptions come in) and so you can only link a transmitter to a transmitter.

**Comment by AJCM-git** [comment]
> > Cant you make it opt-in whether or not you can repeat link?
> 
> Maybe, ideas welcome for this. The old logic stores a transmitter and receiver inside the multitool and has logic like:
> 
>     1. If you poked a transmitter, replace the stored transmitter.
> 
>     2. If you poked a receiver, replaced the stored receiver. If I have both, pop up the window.
> 
> 
> This doesn't work with entities with both transmit and receive (like the new airlocks), because:
> 
>     1. You poke the door, but you have no control over the order of event subscriptions, i.e. do you get the transmit side or receive side first?
> 
>     2. When you go and link the other side, it uses the same order (the order where the event subscriptions come in) and so you can only link a transmitter to a transmitter.

Im not familiar at all with signal code but cant you keep both behaviors by adding a `RepeatLink` bool in the `SignalTransmitterComponent` and setting it to false for airlocks or something (obviously with something in the system to handle this)?

**Comment by juliangiebel** [comment]
Have you looked at #13645?
It refactors machine linking and adds the ability to send arbitrary data when invoking a link.
*(Also there is a freeze on machine linking but that got ignored by other PRs anyway)*

**Comment by Partmedia** [comment]
> Have you looked at #13645? It refactors machine linking and adds the ability to send arbitrary data when invoking a link. _(Also there is a freeze on machine linking but that got ignored by other PRs anyway)_

No, because this original work pre-dates that PR by about a month. Are you suggesting that would improve the multitool UI problems? Have you looked at whether or not the new linking logic works when both sources and sinks are on one entity?

**Comment by juliangiebel** [comment]
> Are you suggesting that would improve the multitool UI problems? 

You didn't mention any UI Problems?

> Have you looked at whether or not the new linking logic works when both sources and sinks are on one entity?

Completing a link takes precedence over starting one with the changes I made and a link will be started with the transmitter component if both are present.
At least that's the intended behaviour. I will test that again when I'm back home.

**Comment by Cheackraze** [comment]
one concern I have is the intended functionality with docking airlocks, since this is a primary use case.  When docking two airlocks together, the airlocks are forced open. This would bolt the inner airlock doors shut, making the docking airlocks completely inaccessible from the station side while something is docked.

**Comment by Partmedia** [comment]
> one concern I have is the intended functionality with docking airlocks, since this is a primary use case. When docking two airlocks together, the airlocks are forced open. This would bolt the inner airlock doors shut, making the docking airlocks completely inaccessible from the station side while something is docked.

It is, of course, possible for mappers to *not* link anything, and the current behavior will be preserved.

**Comment by Cheackraze** [comment]
> > one concern I have is the intended functionality with docking airlocks, since this is a primary use case. When docking two airlocks together, the airlocks are forced open. This would bolt the inner airlock doors shut, making the docking airlocks completely inaccessible from the station side while something is docked.
> 
> It is, of course, possible for mappers to _not_ link anything, and the current behavior will be preserved.

this is true but I was just excited to possibly replace the tiny fans there, but we might have to continue using them. I still see this being useful for other airlocks

**Comment by Myakot** [comment]
I've spent half a year battling engineers that built non-cycling-airlocks. I pray for your good health - that's how grateful I am for this PR. Heartfelt thank you.

**Pull request merged**
