### PR TITLE
cargo console radio messages on approving

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

the cargo request computer now reports to the supply radio when an order is approved, giving the price and information from the approver's card id.
the way to avoid this is to use QM requisition digi-board
## Why / Balance

It is nice to know who spent the money earned and where it was spent. Besides, more often than not, QM cannot know what its employees spend their money on.
## Technical details

I had to add the string `ProductName` to `CargoOrderData`, I tried to avoid this but I failed. 

## Media

изображение

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Сargo request console now reports when a request is approved

### CODE REVIEW

**Comment by superjj18** [comment]
Does it work with Borgs?  Or do they show up as “unknown” like announcements?  Since Borgs naturally are able to approve stuff

**Comment by icekot8** [comment]
> Does it work with Borgs? Or do they show up as “unknown” like announcements? Since Borgs naturally are able to approve stuff

just a blank in place of the approver's first and last name, since they don't have the card id.

**Comment by MissKay1994** [comment]
I don't see why not considering that the R&D computer announces researched tech in comparison. Seems like a decent enough idea and change that makes sense

**Comment by mirrorcult** [comment]
this is good

**Comment by Hrosts** [comment]
I fear this heavily nerfs all kinds of stealthy antagonist cargo strategies in favor of hands-on approaches and special items. It gives a lot of previously concealed information to the whole cargo department, as well as the HoP and the captain. Right now this information can be checked, but you would have to rely on crate invoices for that.

It has also very few avenues for counterplay - if you want to stealthily order something suspicious, you will have to either use the jammer while QM (or better most of command) is nearby, wait for a lucky comms disruption event, or disable the comms outright, which is high-tier sabotage and would not be worth it most of the time.

In comparison, RnD research is usually less suspicious, as the station benefits from it either way, a lot of dangerous stuff is locked behind department-specific fabricators, and your choice is always limited as to what research next.

Maybe it should be a console instead? Maybe with ability to hack/emag the cargo order console to disable the reporting.

**Comment by icekot8** [comment]
now: 
изображение
no " , "

**Comment by lzk228** [comment]
approved stuff should be listed in other console which not used now

**Comment by ImWeax** [comment]
> approved stuff should be listed in other console which not used now

A logistics records computer is a great idea - I still believe orders should be announced over radio - similarly to how science radio announced when technologies are unlocked. (maybe science radios should out who is unlocking a technology, also?)

**Review by mirrorcult — APPROVED** [review]

**Comment by icekot8** [comment]
thank

**Pull request merged**
