### PR TITLE
rebalance thermomachines and teg

### LINKED ISSUE #19432: Thermomachines are now unusable for any purpose
## Description

https://github.com/space-wizards/space-station-14/pull/18984 changed thermomachines to work at time scales incompatible with regular rounds.

**Reproduction**

1. Attempt to heat a gas mixture to 100C using a thermomachine.
2. Wait 15 minutes
3. Probably still not heated

**Screenshots**

**Additional context**

I get that it was made to make it "realistic" and make TEG not make magic free energy. The thing is that TEG does not need anything but room temperature gases to produce energy. Canister of 20C plasma in hot and 10C plasma in cold loop make plenty of energy for all currently mapped stations, trivial to achieve with a single radiator.

Thermomachines as they are now are unusable for anything, they can't heat or cool down gases in a reasonable timeframe.

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR

heaters now output 160kW of heating power, 320kW of freezing power for freezers
TEG output is now 1/40x of what it was before
closes #19432 

## Why / Balance

after the heater/freezer update, heaters/freezers became utterly useless at changing the temperature of any reasonable quantity of gas
additionally, it's extremely easy to make power with the TEG
this PR changes heater/freezer heat output and TEG power output to reasonable values
for reference, this PR should make it so TEG would need approximately 2 mol/s of plasma to power the station (less with more efficient setups)

**Changelog**

:cl:
- tweak: Heaters and freezers now work faster. TEGs now have their power output adjusted.

### CODE REVIEW

**Comment by Partmedia** [comment]
These changes bring us back to bringing thermodynamically unsound. However, the TEG has been adjusted in a way that should prevent the station from generating free energy. Heaters are now significantly faster than before. Future balance adjustments are still anticipated.

**Review by Partmedia — APPROVED** [review]

**Comment by Anzarot121** [comment]
Thank you for the inconspicuous energy absorber of two thermal machines and two sheets of steel.

**Comment by deltanedas** [comment]
wait real were people using thermomachines as selfantags powersink

**Comment by Anzarot121** [comment]
> wait real were people using thermomachines as selfantags powersink

I don't know, but I will use it like this. Moreover, powersink costs too much TC.

**Pull request merged**
