### PR TITLE
Posters/Signs now respect laws of physics

### LINKED ISSUE #14911: Broken posters don't obey the laws of physics
## Description

They basically float around when destroyed
**Reproduction**

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by HoofedEar**
## About the PR

Closes #14911. Adding MovedByPressure to BaseSign seems to make them respect colliding with solids when freely floating in space, while still allowing them to be stuck to walls and such

## Why / Balance

Signs/Posters ought to not float through walls, looks a bit silly. Makes the game more realistic-er 

## Technical details

N/A

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
This is not what that component is for, if a poster is deparented it should just be getting deleted.

**Comment by HoofedEar** [comment]
> This is not what that component is for, if a poster is deparented it should just be getting deleted.

Is there something already in place that does this? Or will I need to come up with some way to check for that?

**Comment by Emisse** [comment]
i think it just needs wallmount and snap cardinals, since it parents off of base sign and not base poster

**Comment by HoofedEar** [comment]
Closing this, coming up with a better solution

**Pull request closed without merging**
