### PR TITLE
Space Damage Increase

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR

Barotrauma damage has been very forgiving for a long time. This only changes the blunt damage you take from space. All non slime races still get over a minute to survive, as long as they have oxygen. Slimes get about 50 or so seconds with nitrogen. The space pen also didn't exist when space damage was nerfed, and you get 20 additional seconds to survive with it. 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://user-images.githubusercontent.com/104418166/212581581-f60d341b-de8e-4987-98e9-9b47d22a77d5.mp4

**Changelog**

:cl:
- tweak: Changed barotrauma damage to be much more deadly. Keep your survival box close.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by EmoGarbage404** [comment]
I'm not really sure why this is necessary. High space damage was present and a contentious issue for a long time. Space medipens did exist when it was rebalanced, but i felt it was in the best design to give everyone at least a minute of survival in space.

Space being more deadly isn't more interesting because space just needs to deal constant damage to be a good enough deterant. I'm not sure how making it more deadly accomplished anything but just making it more frustrating for players getting spaced randomly and limiting peoples options for sacrificing their health to go into space (i.e., rushing through a spaced area to escape a nukie).

**Comment by liltenhead** [comment]
You do get a minute in space with this change if you have oxygen, which everyone spawns with. Slimes have to do a tad bit more work to get nitrogen but that's a different issue. Without this change you get over 3 minutes of survivability in space with a pen and air. Right now you can watch people completely ignore space to chase a snydicate or nukie, as it's more efficient to be fast and the damage is easily healed with one pill.

You used to die in like 8 seconds, now it's several minutes. This change offers a middle ground.

**Comment by EmoGarbage404** [comment]
I'm not super diehard on how it is originally so I'm not going to really push on this, but I don't think it's bad that people are trying to power through space in high pressure situations.

Obviously, it isn't super feasible to be able to chase nukies through space for more than a short period, unless you're willing to take the precautions to be able to survive. Like I said though, I'm not married to the current values, and this change is whatever.

**Comment by asperger-sind** [comment]
While I somewhat agree that a middle ground might be better, I believe that the current amount of space damage is just more fun to play with as you just get access to more decisions, the opponent to more counterplay, etc.

Besides, a lot of people are used to current space damage, spanning across a dozen of servers compared to the first couple of space damage changes affecting Lizard with it's 30 pop constant. So changing space damage is going to be a bit confusing.

**Comment by liltenhead** [comment]
I'd like to imagine that having over a full minute of time in space still gives you options, like if you're gonna try to stop a nukie or something, know that your life is on the line in order to make the hero play. I personally feel that increasing space damage will allow players to more actively roleplay, as in engineering will be more necessary to get things fixed, and security will have more incentive to put on a hardsuit.

I'd like to see the new damage tested in an actual public environment. I agree the change will be a bit shocking to some, but I know others would like this change as well, or at least see how it plays out.

**Comment by EmoGarbage404** [comment]
It's not like having lower damage doesn't incentivize either of those things. People don't function normally in spaced areas. The damage, even if its not a huge amount, still functions as a good enough deterrent to players.

**Comment by liltenhead** [comment]
I guess all I can say is I disagree based off my own experiences. I frequently see people run towards recently bombed areas since they are more likely to catch the bomber and they've got 3 minutes to do so.

Even on a more minor scale some veteran engi players don't even bother going to get a hard suit to fix spacings, it's easier to put a few bandaids on instead and move quickly to fix a hole. 

I'm not sure I've got much else to add.

**Comment by EmoGarbage404** [comment]
also, was this tested in game? it looks like you webedited both commits and there's no video showcase of any kind.

**Comment by GoodWheatley** [comment]
> it looks like you webedited both commits

I have been summoned

**Comment by Cheackraze** [comment]
I can agree with both sides of the issue here.  Just wanted to add that, the more dangerous space becomes, the more people will go back to power gaming hardsuits, emergency suits, etc.

**Review by Emisse — APPROVED** [review]

**Comment by Cheackraze** [comment]
> > I can agree with both sides of the issue here. Just wanted to add that, the more dangerous space becomes, the more people will go back to power gaming hardsuits, emergency suits, etc.
> 
> I would gladly take nerfs to hardsuits in exchange for deadlier space

Hardsuits are already nerfed to the ground as it is.  Only way to nerf them would be to add mechanics like vision cones imo

**Comment by juliangiebel** [comment]
I'm in favor of increasing space damage. Esp. because there are also emergency suits which are supposed to not fully protect you but with the nerfed damage you can just space walk all you want with them.

**Comment by liltenhead** [comment]
Yes I tested this in game, I can throw a video up with a timer if you'd like. I figured web editing two values would be fine, if that's a problem I can learn how to do it the right way.

Anyways slimes get about 50 seconds, everyone else gets 80. Pen gives more time.

**Comment by liltenhead** [comment]
> > > I can agree with both sides of the issue here. Just wanted to add that, the more dangerous space becomes, the more people will go back to power gaming hardsuits, emergency suits, etc.
> > 
> > 
> > I would gladly take nerfs to hardsuits in exchange for deadlier space
> 
> Hardsuits are already nerfed to the ground as it is. Only way to nerf them would be to add mechanics like vision cones imo

I believe removing combat stats from the non combat suits would prevent that. I feel like half the reasons engis even want their suits is the extra damage resist. Also would require a future change to see how people react to this one.

**Comment by Elijahrane** [comment]
The original change predated really high-impact atmos emergency tools like air alarms and holofans, IIRC.

**Comment by mirrorcult** [comment]
air alarms + holofans + spacepens and stuff make me way more confident we can make space deadlier without it being that bad

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
