### PR TITLE
Revert Unknown Shuttle Antagonists 

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

Removes the Drone, Instigator, ManOWar, Raider, and Scooner & the Bang and Hook shuttles.

## Why / Balance

The PR was huge and not atomized in the slightest, maintainers thought all the shuttles were neutral or friendly, similar to the syndie escape shuttle. This isn't the case and the PR added several new antagonist shuttles, some of them with *huge* amounts of equipment. These can be re-looked at in the future but should get a proper maintainer & admin discussion before being merged.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl: Lank
- remove: Several antagonist shuttle events have been removed.

### CODE REVIEW

**Comment by UbaserB** [comment]
For reference, the discussion will get shoved here #31781

**Comment by bruhmogus** [comment]
does this remove the EVENTS or is this a complete revert

**Comment by metalgearsloth** [comment]
> does this remove the EVENTS or is this a complete revert

read the pr

**Comment by cfif126** [comment]
Womp womp, ruined best change to unknown shuttles

**Comment by vladkaron14R** [comment]
> ## О PR
> Удаляет Дрона, Подстрекателя, ManOWar, Raider и Scooner, а также шаттлы Bang и Hook.
> 
> ## Почему / Баланс
> Пиар был огромным и ни в малейшей степени не распыленным, сопровождающие думали, что все шаттлы нейтральны или дружелюбны, подобно шаттлу syndie escape. Это не так, и PR добавил несколько новых шаттлов антагонистов, некоторые из них с _огромным_ количеством оборудования. К ним можно вернуться в будущем, но перед объединением они должны пройти надлежащее обсуждение с сопровождающим и администратором.
> 
> ## Требования
> * [x]  Я прочитал и следую [Рекомендациям по удалению и журналу изменений](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
> * [x]  Я добавил медиа в
> 
> * удалить: Удалено несколько событий шаттла антагониста.

I apologize for the expression, but why was it deleted even if it was accepted from above? Everyone was really waiting for this update. In the end, this great idea was buried by you in the grave. People like you will only remove great things and mechanics like the shuttle of scraps and the question is why delete this content? That's right, so that you can then offer your "ideal idea"

**Pull request merged**
