### PR TITLE
Total Bartending Conversion (Part 1)

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 

Replaces all of bartending drinks, reagents, recipes, and textures with /tg/'s

**Textures**

- [ ] Bottles
- [ ] Glasses
- [ ] Cans

**Objects**
- [ ] Alcoholic
- [ ] Cans

**Reagents**
- [x] Alcoholic
- [x] Soda
- [x] Juice
- [x] Misc

**Localization**
- [x] Alcoholic
- [x] Misc

**Recipies**
- [x] Alcoholic
- [x] Misc

**Vendors/Reagent Dispensers**

- [ ] Booze-O-Mat
- [x] Soda Fountain
- [x] Booze Dispenser

**Removing old prototypes from maps**
- [x] maptainers did this for me thx

:cl:
- tweak: Bartending is all different now, ill fill this in later.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
how the fuck am I supposed to scroll through all this

**Comment by mirrorcult** [comment]
image
blaspheme

**Comment by ZeroDayDaemon** [comment]
> image blaspheme

do not fret, it will be restored, just needed to unclog the hell that was the drinks RSI folder for sanity

**Comment by ZeroDayDaemon** [comment]
Time to work on this again

**Comment by ZeroDayDaemon** [comment]
Time to want to die again

**Comment by ZeroDayDaemon** [comment]
reducing the scope of this

**Comment by Pangogie** [comment]
RIP hopes and dreams.

**Pull request closed without merging**
