### PR TITLE
Chief Engineer's Turtleneck

### PR DESCRIPTION
**Pull request by KingFroozy**
## About the PR

Added a Chief Engineer's Turtleneck, similiar to the Quartermaster's one.
The description reads: "A yellow turtleneck specifically designed for work in conditions of the engineering department."
Turtleneck itself includes two versions: with pants, and with a skirt. Both of these versions will spawn in the Chief Engineer's locker. It's also printable at the Uniform Printer. Both versions require 3 sheets of cloth to be sewed.
Design is approved by @Flareguy.

## Media

ChiefEngineersTurtleneck
PrintableTurtleneck
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Chief Engineer's Turtleneck. You can find it in their locker or sew it at the Uniform Printer!

### CODE REVIEW

**Comment by LankLTE** [comment]
This probably shouldn’t be in the locker, if someone really wants it they can ask the HoP to print it and we don’t need to start with head lockers being full of clothing variants again

**Comment by KingFroozy** [comment]
> This probably shouldn’t be in the locker, if someone really wants it they can ask the HoP to print it and we don’t need to start with head lockers being full of clothing variants again

I'm aware of this problem, and I was wondering of making prototypes of dressers, filled with specific clothes for each head. But at this point, I think, it's better to make more clothes for heads at the first place, else dressers would be pretty much empty for some of them. And, honestly, it kinda sucks to ask hop to make you a clothing every shift.

**Comment by Emisse** [comment]
ideally when loadout becomes a thing we will remove all clothes from lockers and put it in loadout

**Comment by Eden077** [comment]
And if someone else wants it they can realistically just use the printer

**Pull request merged**
