### PR TITLE
Revert "npc can no longer attack you through a locker"

### PR DESCRIPTION
**Pull request by metalgearsloth**
Reverts space-wizards/space-station-14#27677

### CODE REVIEW

**Comment by muburu** [comment]
any reasons why

**Comment by metalgearsloth** [comment]
> any reasons why

NPCs call melee code. NPCs hit people in containers.

The problem is melee code because malicious clients can do the exact same thing.

**Comment by Ilya246** [comment]
NPCs targeting people in lockers in the first place is a problem too, no?

**Comment by Tyzemol** [comment]
It is, but then someone reminded me ripley exists, and i remembered a cardboard box exists, those both are a "container" and mobs stop attacking people inside those with that pr, maybe its for the best its reverted.
I am currently thinking on how to differentiate between a crate and a walking crate and have no ideas other than checking for `DoorBumpOpener` tag that both ripley and cardboard box share, but thats jank...

**Pull request merged**
