### PR TITLE
Guidebook Tables

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds support for nice looking tables in the guidebook.

the new `<Table>` control allows you to lay stuff out nicely in a table without gridcontainer jank.
We also now have `<ColoredBox>` which is basically just Box on a panelcontainer and with better defaults. Good for tables and not much else.

Text centering is omegafucked because of guidebook jank but HEY IT WORKS it's good enough for a first pass and doesn't completely suck to write

## Technical details

PJB graciously coded TableContainer in the middle of the night to make this shit easy.
TableContainer needs to be moved to engine but this is high priority

image

## Media

image

made with the following XML
```xml
<Table Columns="3">
  <ColorBox Color="#994444">
    <Box>
      HEADER 1
    </Box>
  </ColorBox>
  <ColorBox Color="#449944">
    <Box>
      HEADER 2
    </Box>
  </ColorBox>
  <ColorBox Color="#444499">
    <Box>
      HEADER 3
    </Box>
  </ColorBox>
  <ColorBox>
    <Box HorizontalAlignment="Left" VerticalAlignment="Stretch" Margin="2">
      body 1
    </Box>
  </ColorBox>
  <ColorBox>
    <Box HorizontalAlignment="Left" VerticalAlignment="Stretch" Margin="2">
      body 2 OASDKFA F ASDKF ASD FKASD LFKA SLFKA SL
    </Box>
  </ColorBox>
  <ColorBox>
    <Box HorizontalAlignment="Left" VerticalAlignment="Stretch" Margin="2">
      body 3 BUT IT GOES CRAZY AND OFF THE RAILS OH MY GOD ITS ASDF ASF ASDFASKD FNMXV EWOR QIWEORP SV
    </Box>
  </ColorBox>
</Table>
```

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun but much thanks to PJB

### CODE REVIEW

**Comment by lzk228** [comment]
bless you 🙏

**Comment by Brandon-Huu** [comment]
Is it possible to set the dimensions of each column?

**Comment by Partmedia** [comment]
A few comments from me:

- Is there a reasonable way to merge ColorBox with the Box (and a color property?) Or are the defaults too different to reconcile?
- I'm having trouble getting vertical alignment to work in the table (see code below):

```
<Table Columns="3">
  <ColorBox Color="#994444">
    <Box>
      HEADER 1
    </Box>
  </ColorBox>
  <ColorBox Color="#449944">
    <Box VerticalAlignment="Center">
      HEADER 2
    </Box>
  </ColorBox>
  <ColorBox Color="#444499">
    <Box>
      HEADER 3
    </Box>
  </ColorBox>
  <ColorBox>
    <Box HorizontalAlignment="Left" VerticalAlignment="Stretch" Margin="2">
      body 1
    </Box>
  </ColorBox>
  <ColorBox>
    <Box HorizontalAlignment="Left" VerticalAlignment="Stretch" Margin="2">
      body 2 OASDKFA F ASDKF ASD FKASD LFKA SLFKA SL
    </Box>
  </ColorBox>
  <ColorBox>
    <Box HorizontalAlignment="Center" VerticalAlignment="Stretch" Margin="2">
      body 3 BUT IT GOES CRAZY AND OFF THE RAILS OH MY GOD ITS ASDF ASF ASDFASKD FNMXV EWOR QIWEORP SV
    </Box>
  </ColorBox>
</Table>
```

- This feels more like a "grid flow" layout than a table, but that's a small matter of naming.

Otherwise I feel that this serves a useful need and should go in even if it's a little imperfect now.

**Comment by EmoGarbage404** [comment]
> Is there a reasonable way to merge ColorBox with the Box 

it's completely doable to merge them but for the purposes of making tables doing it like this offered the least amount of boilerplate. I guess coloredbox could be renamed TableCell or something to be more clear in that but it's also not strictly bound to that either.

> I'm having trouble getting vertical alignment to work in the table (see code below)

To be quite honest i was having this issue too and couldn't really get decent vertical alignment. It might have to do with how the guidebook constructs text controls. I really was just focused on getting the basics out quickly because ik this is very high priority.

> This feels more like a "grid flow" layout than a table, but that's a small matter of naming

it's really only called "table" because the UI control is called "TableControl." It is indeed more of a grid flow layout but i didn't really want to cause confusion with GridContainer. It's just mirroring the name a la "Box" and "BoxContainer"

**Comment by mirrorcult** [comment]
agree with notafet but also id rather this just gets in rn in this state

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
