### PR TITLE
Add alternative crafting recipes for reinforced plasma/uranium glass

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Added two crafting recipes for reinf plasma/uranium glass each so that accidentally crafting regular plasma/uranium glass wouldn't be an unnecessary waste of resources
## Why / Balance

Quality of life, I have seen people (and myself) accidentally craft plasma/uranium glass waaayyyyy too many times when trying to craft the reinforced variants.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: 
- tweak: There are now more ways to craft reinforced plasma/uranium glass.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Are you coming back to this @MACMAN2003

**Comment by MACMAN2003** [comment]
does the pr need any changes?

**Comment by metalgearsloth** [comment]
It's failing tests.

**Comment by MACMAN2003** [comment]
i have no idea why SheetRPGlass1 and SheetRUGlass1 are working while SheetRPGlass0 and SheetRUGlass0 aren't.
the only differences between them are the number at the end and the recipe

**Comment by MACMAN2003** [comment]
tested it in localhost and all the recipes seem to work flawlessly (at least on my machine)

**Pull request merged**
