### PR TITLE
Monkey Ear Slot

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Gives monkeys an ear slot for headsets and the like. Also Pun Pun starts with a service headset.

## Why / Balance
Been playing as Pun Pun recently, and not being able to tune into the radio makes me sad. Works good for syndicate monkeys too

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- add: Added ears to monkeys, also Pun Pun starts with a service headset

### CODE REVIEW

**Comment by NancokPS2** [comment]
I don't get why monkeys get like a fraction of the slots that a human gets.  
I understand maybe no shoes and 1 hand slot to emulate the fact that they are small. But no tie nor pockets? why?

**Comment by deltanedas** [comment]
monkey ghost roles shouldnt be a complete respawn - someone

**Comment by metalgearsloth** [comment]
Do they even have ear slots in 13.

Also monkeys shouldn't just be a lower HP human.

**Comment by Alekshhh** [comment]
probably varies by server

**Comment by NancokPS2** [comment]
They are far from a low HP human, but even if they needed further nerfs, this is a pretty arbitrary way to do it.   

They already cannot wear certain items, expanding that list should help with the nerfs without clipping pockets from anything they wear or deciding they do not have a neck.  
  
I agree that a ghost role should not be smaller human, but they should have appropriate downsides.

**Comment by Alekshhh** [comment]
they also have clumsiness, so they can't shoot guns or climb tables

**Comment by UbaserB** [comment]
if people are too worried about it being too powerful, how about we make the headset exclusive to pun pun? in the first place pun pun is already a crew member… lore wise

**Comment by Alekshhh** [comment]
it's just a headpiece, there won't be a monkey meta after it's implemented. it's for convenience sake

**Comment by metalgearsloth** [comment]
sure but no more slots

**Pull request merged**
