### PR TITLE
Cane sword price reduction 5  -> 1, and Canes can fit on Belt/Exosuit slot

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

2 Buff to Canes

1. Cane sword price reduction 5  -> 1  
2. Canes can fit on Belt/Exosuit slot
## Why / Balance

Discussion for the balance of it can be found throughout https://discord.com/channels/310555209753690112/1234653039894204487 General consensus was that it would be a sidegrade to the other low cost options like the E-Pen, Mosin, and Cybersun Pen. If opinion goes against it I would be fine upping the price to 2 TC.

I am considering making it available in the surplus crate.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Canesword 5 -> 1TC
- tweak: Cane can fit in the Belt/Exosuit slot

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
The cane blade isn't a "sidegrade" to the cyber sun pen, it is a straight upgrade as it does twice the DPS, the mosin is also a gun and you can't compare a gun and a sword for balancing

**Comment by thebadman4662** [comment]
It trades all of the utility for bit of extra oomph and damage type that can be worse against most people(coats and stuff have slash resist) but causes bleeding and will punish pierce focused armors where cybersun gets to about crowbar strength.

If cybersun is at 1TC, cane seems fair to be same too, otherwise pen should probably be 2TC unless its meant to be OP purchase in terms of value by design.

**Comment by FungiFellow** [comment]
> The cane blade isn't a "sidegrade" to the cyber sun pen, it is a straight upgrade as it does twice the DPS, the mosin is also a gun and you can't compare a gun and a sword for balancing

Pen has utility in being able to be hidden in PDA's, Pockets and anything that can fit a 1x1 alongside stamped paper editing

**Comment by PolterTzi** [comment]
I can certainly agree with letting the cane fit in a belt or exosuit slot.
The cost reduction seems reasonable, but I feel like both being in the same PR might not be the best practice. But maybe I'm being too pedantic.

**Comment by ShadowCommander** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by thebadman4662** [comment]
Was I mistaken that balancing PRs are not going to be closed during freeze?

**Comment by Dutch-VanDerLinde** [comment]
> Was I mistaken that balancing PRs are not going to be closed during freeze?

balance prs that are actually needed

**Comment by ShadowCommander** [comment]
We're closing PRs that change things that aren't egregious enough that the role cannot be played. Or are not getting abused frequently enough that it's a problem over multiple rounds.

**Pull request closed without merging**
