### PR TITLE
fix cauterization

### LINKED ISSUE #21491: Heat damage no longer seems to cauterize
## Description

Normally this is something I would take care of because I know the code, but nothing's been changed in the system, I'm guessing something else broke it?

**Reproduction**

Any form of heat damage should cauterize bleeding.

bleed rate modifiers are unchanged...
image

I can't however, find any usage of this modifier set anymore in mob yml, which might be why it's broken, unless this is the default regardless, in which case I have no idea where the issue is

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Fixes #21491 

## Why / Balance

bugfix

## Technical details

We disallowed negative damage coefficients a while back. It was still needed for this one case, so I've added it back.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Heat damage cauterizes bleeding again.

### CODE REVIEW

**Comment by themias** [comment]
Tests failing since it looks like we don't want to allow negative modifiers at all.

**Comment by deltanedas** [comment]
so change the test

**Comment by themias** [comment]
> so change the test

True, I just wasn't sure what we wanted design-wise. Looking at the comment from the PR when we removed it, looks like ElectroJr wasn't aware that negative coefficients were still being used in this one case. I'll remove the test and reviewers can decide on it.

**Comment by Hmeister-fake** [comment]
Thank god, best bug fix PR ever.

**Review by mirrorcult — APPROVED** [review]

**Comment by K-Dynamic** [comment]
My long-desired stealth nerf to lasers and eswords accomplished :trollface: 

Also we can touch lights again to stop bleeding

**Pull request merged**
