### PR TITLE
syndicate ID for reinforcement, agent ID for commander and agent

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Syndicate reinforcements now come with a syndicate ID (not an agent ID)
The nukie commander and medic now come with agent ID's
## Why / Balance

nukies no longer need to buy an ID for reinforcements, which is just an extra cost on top of getting them armor and a weapon
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no CL no fun

### CODE REVIEW

**Comment by Holinka4ever** [comment]
In one side, its cool and interestind idea for reinforcement, if flukies dont buy spare ids for them.

In another side, its a free 6 cards to microwave them for more access, oh gosh, i love the smell of powercreeping in the morning.
But seriosly, it doesnt seems okay to be honest.
It would be alright, if syndicate cards wouldnt have interaction with microwave. Though, it can hell up curret tactics with nukes.

**Comment by JoeHammad1844** [comment]
oh yeah didnt think of that

**Comment by JoeHammad1844** [comment]
maybe reinforcements should come with syndie IDs

**Comment by JoeHammad1844** [comment]
yeah ill do that instead

**Comment by JoeHammad1844** [comment]
oop merge fail

**Comment by JoeHammad1844** [comment]
merge was not the correct word

**Comment by JoeHammad1844** [comment]
oops i did some stuff with CBURN by accident

**Pull request closed without merging**
