### PR TITLE
Newton cradle

### PR DESCRIPTION
**Pull request by lzk228**
## Media

https://github.com/space-wizards/space-station-14/assets/124214523/0b61e0e8-bd30-4e6e-a2b1-597b2d9abc5c

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by Pangogie** [comment]
Needs the sound.

**Comment by lzk228** [comment]
ahhh

**Comment by lzk228** [comment]
added

**Comment by Terraspark4941** [comment]
personally, i would like the side pendulums to go a bit higher on-sprite
otherwise, 👍

**Comment by IProduceWidgets** [comment]
With the sound, might want to add a way to toggle it to a static state.

**Comment by Jezithyr** [comment]
Second this, would be a good if there was a way to toggle it on and off, otherwise I have a feeling it's going to get yeeted into disposals pretty quick

**Pull request merged**
