### PR TITLE
Arachnid 2: Episode 2

### PR DESCRIPTION
**Pull request by PixelTheKermit**
## About the PR

Arachnids get 2 web slots (they're back! Yay!), added a web shield, made arachnid crafting completely exclusive to arachnids, tweaked sericulture to be faster and use less hunger, and hunger is now the same as humans.

Also adjusted the silk sprite.

## Why / Balance

 - 2 web pocket slots: These were here in the first iteration of the arachnid rework, and they didn't seem too overpowered to have now. So due to a few requests I decided to bring these back.
 - Web shield: Just thought it would be fun to add.
 - Exclusive crafts: Just didn't think web crafts should've been available to everyone, so I just made them exclusive.
 - Sericulture tweaks: I may have gone overboard with the sericulture hunger cost last pr, and thought I should tone it down. Also 3 seconds to make a web took too long imo.
 - Hunger + Thirst: I felt like with the extra pockets, there needed to be something to cancel it out. I decided to remove one of their positives to hopefully balance everything out.
 - New silk sprite: Old one sucked. New one better.

## Technical details

ConstructionPrototype can now use an "EntityWhitelist" to show/hide and allow/block certain crafts from an entity.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/85175107/558d4b1f-a607-47e7-825f-3b6a2e3d20d4

image

image

### UI
**Default**
image

**Classic**
image

**Modernized**
image

## Breaking changes

**Changelog**

:cl: PixelTK
- add: Arachnids can now weave a simple shield made out of silk.
- tweak: Arachnids now have two additional pocket slots. In exchange, they no longer have slower hunger.
- tweak: Arachnids are now the only species that can craft with silk.
- tweak: Arachnids now produce silk more efficiently.

### CODE REVIEW

**Comment by deltanedas** [comment]
arachnid 3 when

**Comment by PixelTheKermit** [comment]
> arachnid 3 when

what's a 3?

**Comment by deltanedas** [comment]
arachnid 2
arachnid 2 part 2
arachnid 4

**Comment by KingOnBudget** [comment]
Web Bola: A bola made out of silk.
Web Sack: Reskin emergency box has 30 storage but takes 30 storage itself.
Web Jacket: A jacket made out of silk has 10 storage just like a normal jacket.
Web Baret: A baret made out of web.
Shivs: Nornal shivs but cloth is replaced by silk
Web Vest: A vest thats made out of web. It gives no protection whatsoever but is called web vest for the funnies.
Web Fence: A fence made out of web. It isn't as resilent as a normal web and can be deconstructed way easier. Can not be connected to cables either. (Think it is a window but made out of web.)


To be fair I don't know how  hard any of these would be to add but I feel like they should be balanced since they are already existing items but reskinned. I made this account just now to comment this because I realy like playing arachinds.

Keep up the good work!

**Comment by LankLTE** [comment]
> To be fair I don't know how hard any of these would be to add but I feel like they should be balanced since they are already existing items but reskinned. I made this account just now to comment this because I realy like playing arachinds.

Bola and Shivs are probably a bad idea. Bola would be really good and a shiv doesn't really make sense? There's already a Web Winter Coat so the jacket is kind of irrelevant. Sack also just seems pointless to include
Fence and beret aren't necessary but I wouldn't be opposed to seeing them
Web Vest is really funny honestly I say do it

**Comment by PixelTheKermit** [comment]
> To be fair I don't know how hard any of these would be to add but I feel like they should be balanced since they are already existing items but reskinned. I made this account just now to comment this because I realy like playing arachinds.

Web bola: Seems a bit too much. Probably won't code this.
Web sack: Not sure how I feel about this, might need to think about it.
Web jacket: There already is a web winter coat.
Web baret: possible
Shivs: ...you can already make cloth...
Web vest: It's funny.
Fence: I like this.

**Comment by KingOnBudget** [comment]
> > To be fair I don't know how hard any of these would be to add but I feel like they should be balanced since they are already existing items but reskinned. I made this account just now to comment this because I realy like playing arachinds.
> 
> Bola and Shivs are probably a bad idea. Bola would be really good and a shiv doesn't really make sense? There's already a Web Winter Coat so the jacket is kind of irrelevant. Sack also just seems pointless to include Fence and beret aren't necessary but I wouldn't be opposed to seeing them Web Vest is really funny honestly I say do it

Bola and shiv of course wouldn't be just silk to make that would be too stupid. I wrote them expecting them would be crafted not just by silk but with a s resource used to make em being replaced by silk. For example web bola is made by cuffs and some silk and shiv is made using glass and silk. I guess I could have worded it better.

**Comment by Hmeister-fake** [comment]
> 

To be fair a web jacket would help if a fire anom went crit or something and the station gets really hot, winter coat heats you faster so having a choice not to have that is cool imo.

**Comment by LankLTE** [comment]
> winter coat heats you faster so having a choice not to have that is cool imo.

I'm pretty sure that's not how winter coats work, but either way just take it off...?

**Comment by KingOnBudget** [comment]
Web pistol: A pistol made out of web has infinite ammo very balanced pls add

**Comment by CrigCrag** [comment]
we're so back

**Comment by CatMagic1** [comment]
The web sack sounds really cool! I think it'd be funny to see arachnids put a bunch of things in sacks in their backpack. Even though it doesn't give any extra storage, it'd be just like how they wrap their food in movies and stuff.

**Comment by PixelTheKermit** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

I just had to deal with conflicts last night :despair:

**Comment by PixelTheKermit** [comment]
I'm deciding to do any more web stuff in another pr, don't feel like spriting.

**Comment by UbaserB** [comment]
arachnids, the race with too much content:tm:

**Comment by GeorgeGimme** [comment]
yeah give some other races stuff
like dwarfs cause they took my speed ;-;

**Comment by PixelTheKermit** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by LankLTE** [comment]
Changelog could probably be a little shorter, but I have no other issues.

**Comment by PixelTheKermit** [comment]
> Changelog could probably be a little shorter, but I have no other issues.

Tried shortening it, but I'm not sure if I could make it more shorter.

**Comment by PixelTheKermit** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

OH FOR FUCKS SAKE-

**Comment by PixelTheKermit** [comment]
Okay this should be fixed.

**Comment by Carolyn3114** [comment]
when's "Arachnid: Alyx" coming out?

**Comment by deltanedas** [comment]
why not go back to 4 hands since quad magdumping isnt a thing anymore

**Comment by PixelTheKermit** [comment]
> why not go back to 4 hands since quad magdumping isnt a thing anymore

4 hands are not fun to play with.

**Comment by EmoGarbage404** [comment]
Big fan of 4 handed gaming :trollface:

**Comment by deltanedas** [comment]
you can spam x or click item to switch fast so only real issue left is arachnid being giga shitter species since 2 cuffs to arrest and being fast

**Comment by PixelTheKermit** [comment]
> Big fan of 4 handed gaming :trollface:

Not a big fan myself, but since I'm not a maintainer I guess that doesn't matter.

**Comment by KingOnBudget** [comment]
we ball

**Comment by ViceEmargo** [comment]
Spooder gaming, let's go. Having extra pocket slots would be fantastic for engineering and gardening. 
All the tools right easily shoved into pockets would be just a small QOL than pulling them out of a toolbelt, or shoved into a backpack when I run out of tool space. Now I would be able to just balance pocket and toolbelt slots instead of having a fit over a single tool being in my backpack because it didn't fit in the toolbelt.

**Comment by PixelTheKermit** [comment]
To the mines I go.

**Comment by PixelTheKermit** [comment]
Okay PR is probably fine now.

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
lg2m

**Review by LankLTE — APPROVED** [review]
Looks good.

**Pull request merged**
