### PR TITLE
Add antagonist datafield to ghost roles

### PR DESCRIPTION
**Pull request by Equivocateur**
## About the PR
Adds an "_antagonist_" field in GhostRole types to denote that a ghost role is an _antagonist_, thus showing the user as an _antagonist_ in admin logs.

Defaults to false if not included.

Example usage:
```yml
  - type: GhostRole
    name: Cerberus, Evil Familiar
    description: Obey your master. Spread chaos.
    rules: You are an intelligent, demonic dog. Try to help the chaplain and any of his flock. As an antagonist, you're otherwise unrestrained.
    antagonist: true
```
**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
need no apply, not player facing

### CODE REVIEW

**Comment by deltanedas** [comment]
wtf I am the last thing you will ever see is valid now!!!

**Review by tom-leys — APPROVED** [review]
Looks good to me, though there are quite a few ghost roles in .yml you should probably be marking antagonist in the same PR.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
fix conflicts

**Comment by Emisse** [comment]
goncflict

**Comment by AJCM-git** [comment]
@Equivocateur Are you coming back to this?

**Comment by Equivocateur** [comment]
I'll reopen when I get to it

**Pull request closed without merging**
