### PR TITLE
Add Chef's Belt

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Adds a chef's belt: 
- Chefs start with a belt containing salt and pepper shakers
- Belts have slots for kitchen knife, cleaver, rolling pin, condiment bottles(cold, BBQ, ketchup, hot), enzyme, rolling pin, and salt & pepper shakers
- Belts can also store condiment packets, various smokables, mouse traps, monkey cubes, and skewers.
- Empty belts added to ChefDrobe(2)

## Why / Balance
Added utility and coolness for the chef role. 

## Technical details
n/a

## Media
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
n/a

**Changelog**
:cl: Velcroboy
- add: Added the chef's belt!

### CODE REVIEW

**Comment by Emisse** [comment]
cool but i dont think it should start filled because most of this stuff is in kitchen roundstart

**Comment by IamVelcroboy** [comment]
> cool but i dont think it should start filled because most of this stuff is in kitchen roundstart

What if I just limit it to just the s&p shakers? Either way is fine. I just like the idea of something in them at roundstart.

**Comment by EmoGarbage404** [comment]
just salt and pepper is fine

**Comment by IamVelcroboy** [comment]
Ok, I reduced it to just the s&p shakers

**Pull request merged**
