### PR TITLE
Med hud for medical cyborgs and med module merge

### PR DESCRIPTION
**Pull request by Mangohydra**
## About the PR

I recently saw the new changes to the eng borg modules, thought the med borgs could get some love so here we are.
## Why / Balance
The medical cyborg med modules are a bit of a mess, defib, analysis and treatment are separate modules, I've merged adv. treatment and analysis together because constantly switching between modules feels clunky and annoying.

## Media
med hud in action
image
new advanced medical module
image

**Changelog**
Medical cyborgs and their syndicate counterparts now have a medhud
The advanced treatment module has a health analyzer
The analysis module is removed from mechanical treatment research

### CODE REVIEW

**Comment by UbaserB** [comment]
why cant we make all borgs have medhud instead of just medical borg? It will help determine if something is threatening (and damaging) a human so that they know when law 1 should be followed. For example, currently you may have no idea if a human injested something toxic and are currently taking damage, so you accidentally break law 1 by “inaction”.

**Comment by PJB3005** [comment]
> For example, currently you may have no idea if a human injested something toxic and are currently taking damage, so you accidentally break law 1 by “inaction”.

Inaction doesn't apply if you have no way to know it's taking place.

This should not be given to all borgs.

**Comment by Mangohydra** [comment]
going to rework this so the medhud isn't standard on mediborgs but rather included with a module, likely adv. treatment, lord knows how long this will take

**Comment by IProduceWidgets** [comment]
I know closed, but borg hypopen seems iffy.

**Pull request closed without merging**
