### PR TITLE
Warden headdresses In-hand Sprites

### PR DESCRIPTION
**Pull request by onesch**
## About the PR
Adds in-hand sprites to the warden beret and cap. based [#33386](https://github.com/space-wizards/space-station-14/issues/33386)

## Why / Balance
Currently it has no in-hands, so this is adding one.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]
The code side looks good.
I will ask an art director for sprite approval.

**Comment by slarticodefast** [comment]
Also a small visual change like this does not need a changelog entry, could you remove that from your PR description?
You will of course still be mentioned in the game's credits for contributing.

**Review by Emisse — APPROVED** [review]

**Comment by slarticodefast** [comment]
Since emisse approved the sprite I went ahead and removed the changelog entry.
Thank you for your first contribution!

**Comment by onesch** [comment]
> Since emisse approved the sprite I went ahead and removed the changelog entry.
> Thank you for your first contribution!

I'm so glad I contributed to my favorite game!!

**Pull request merged**
