### PR TITLE
Makes Opporozidone revert rot stages

### PR DESCRIPTION
**Pull request by rbertoche**
## About the PR

I have just noticed Gotimanga's Opporozidone got merged in here, which allows me to PR my changes - mostly from march - to it.

Since I did not have time to test it yet, I thought I should still PR it since it's already done, but mark it as a draft until I'm sure it does work after merging one month ahead where these changes have been running on without issues on our Pirata server.

## Why / Balance

Rotting stages were added - in december? I can't be sure - which made the opporozidone PR (I believe both this one or the old closed one) not work again. The other relevant change, not allowing accumulators to go negative, is minor in comparison.

## Technical details

C# code at ReduceAccumulator had to be changed a bit in order to properly calculate rotting stages, given you need to calculate a new stage in some cases at the moment the Rotting component is being removed. This was the source of the most structural changes in that method. The other changes were, namely, preventing the accumulators from becoming negative, and adding one assert to make sure developers will know when they end up breaking logic in the method.
## Media
I will add media once I get to test it properly.

## Breaking changes

**Changelog**

:cl: rber
- fix: Opporozidone can revert rot stages.

### CODE REVIEW

**Comment by rbertoche** [comment]
Oh I thought making a thing which doesn't work work was not adding a new feature but anyway.

**Comment by mirrorcult** [comment]
oh, this was mislabeled yeah

**Comment by rbertoche** [comment]
oh cool I wasn't sure this was a mistake or just didn't qualify during the freeze somehow

**Comment by thebadman4662** [comment]
Opp have been working just fine for all my not-rotten-anymore patients. I have not had them not work once since merge.

**Comment by metalgearsloth** [comment]
Re-open if this gets done.

**Pull request closed without merging**
