### PR TITLE
telescreen and television require vision + Move eye to shared

### LINKED ISSUE #28806: fullvision on cameras when sleep
## Description
- Fullvision on the cameras while you sleep

https://github.com/space-wizards/space-station-14/assets/96445749/c4a5b7ce-2216-4f08-8819-a78039cf59b1

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

telescreen and television require vision require sight( ie: work like camera monitor console)
## Why / Balance

Fixes #28806(probably want to make blindness give Fullbright too), MORE CONSISTENCY!!! I LOVE CONSISTENCY!!!
Move to shared to fix UI mispredicts
## Technical details

yml add one component to telescreen and television :)
## Media

https://github.com/user-attachments/assets/0465cd01-6791-4714-b05c-2eeb9b6ca077

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: You can no longer use telescreens and televisions while blind or asleep.

### CODE REVIEW

**Comment by Plykiya** [comment]
ActivatableUIRequiresVision should probably be in shared to prevent that mispredict from happening

**Comment by Cojoke-dot** [comment]
> ActivatableUIRequiresVision should probably be in shared to prevent that UI mispredict from happening, doesn't seem to be too complex of a move

Sure, that worked. I uh... I just moved all eye to shared...

**Comment by Plykiya** [comment]
> > ActivatableUIRequiresVision should probably be in shared to prevent that UI mispredict from happening, doesn't seem to be too complex of a move
> 
> Sure, that worked. I uh... I just moved all eye to shared...

updatea the video

**Comment by Cojoke-dot** [comment]
> updatea the video

Video updated 👍

**Comment by Plykiya** [comment]
> > updatea the video
> 
> Video updated 👍

PopupClient() will solve the popup x9 issue

**Comment by Plykiya** [comment]
Oh, I just noticed a bug with the way PopupCursor/Client stacks the messages. Well, not your issue to deal with.

**Comment by Plykiya** [comment]
EyeProtectionSystem already calls functions that Dirty their components and EyeProtectionComponent itself has no need to be dirtied, seems fine

**Comment by Plykiya** [comment]
two line change, yeah ok

**Pull request merged**
