### PR TITLE
Glowy lights - light fixtures now actually glow

### PR DESCRIPTION
**Pull request by deathride58**
## About the PR
This PR fixes something that has always bothered us to an unreasonable extent: The lights. We've *very* frequently had moments where we genuinely can't figure out where the light source of a room is, simply because it's too dim, and the light fixture doesn't actually glow. So we made light fixtures glow! Simple.

## Why / Balance
Things that produce light not actually glowing is genuinely atrocious

## Technical details
This adds a new enum to PoweredLightLayers, and makes PoweredLightVisualizer make a check for whether or not that glow layer exists. If that glow layer exists, then the glow layer will have it's visibility toggled depending on whether or not the light is on. Simple simple.

### BEFORE:

image

(Special thanks to Errant from the Discord for this screenshot right below!)

### AFTER:

image

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**

:cl: Bhijn and Myr
- tweak: Light fixtures now actually glow when they're powered on. Like. Their sprite actually glows if the lighting is dim. Revolutionary technology, yes.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by Emisse** [comment]
test fail not erroneous

**Comment by deathride58** [comment]
aye, it's the service light that's causing the fail. commit to convert the service light to glowiness Soon

**Comment by deathride58** [comment]
image

should be fixed, he'll yeha

**Comment by UbaserB** [comment]
can you dim the service light as well? its really eye-catching.. and while thats a good thing i think its a bit excessive

**Comment by deathride58** [comment]
image

Toning down the service light light source's brightness is out of this PR's scope, but toning down the sprite's brightness is very much within! Though we do agree that the service light is pretty obnoxiously bright for what's supposed to be a tiny indicator light

**Comment by UbaserB** [comment]
Uhh i just noticed, shouldnt the different kinds of lights (LED vs normal) look different? like, slightly different hues to differentiate them..?

**Comment by deathride58** [comment]
Aye, making bulbs affect the glow layer's color if present would be pretty neat! It's something that we might end up tackling in the future (near or not), but on the bright side, at least the disparity between the various bulbs and the glow layer isn't *too* jarring

**Pull request merged**
