### PR TITLE
Adds grappling gun

### PR DESCRIPTION
**Pull request by metalgearsloth**
https://github.com/space-wizards/space-station-14/assets/31366439/5d5ac376-0ec9-488b-ad20-c9e14c91753e

Requires https://github.com/space-wizards/RobustToolbox/pull/4081

:cl:
- add: Added a grappling gun

### CODE REVIEW

**Comment by HoidC** [comment]
please make it so you can grapple onto an FTLing object

**Comment by deltanedas** [comment]
then it has issue of syndies grappling evac (instead of putting rods) for easy escape greentext

**Comment by deltanedas** [comment]
then it has issue of syndies grappling evac (instead of putting rods) for easy escape greentext

**Comment by HoidC** [comment]
> then it has issue of syndies grappling evac (instead of putting rods) for easy escape greentext

Make it so you’re rapidly damaged in FTL when outside or that shrimply doesn’t count for the objective

you not ON the shuttle

**Review by Emisse — APPROVED** [review]

**Pull request merged**
