### PR TITLE
Cyborgs now grant AI Vision

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Cyborgs now grant AI Vision like cameras

## Why / Balance

It seems like a logical thing, considering AI oversees cyborgs.

## Technical details

Added the AIVision component to the cyborg chasis.

## Media

None.
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Cyborgs now grant AI Vision.

### CODE REVIEW

**Comment by lzk228** [comment]
do they always provide the vision? probably should not when discharged or don't have a player (mind)

**Comment by ScarKy0** [comment]
By how the component works, they always do
Cameras also always do, no matter if powered or not

**Comment by lzk228** [comment]
it's understandable with cameras, but with borgs not really

**Comment by slarticodefast** [comment]
Wouldn't this give the AI vision also to syndie borgs? I don't think they should have station camera access. Maybe move it to BaseBorgChassisNT

**Comment by muburu** [comment]
what about emagged borgs? if they try to sneak off into maints or disable cameras to do something illegal wouldn't AI be able to easily see that and snitch immediately??

**Comment by ScarKy0** [comment]
> what about emagged borgs? if they try to sneak off into maints or disable cameras to do something illegal wouldn't AI be able to easily see that and snitch immediately??

Yes, but considering AI is kinda supposed to oversee borgs I think thats fine?
I don't know how to make it not work if the borg is emagged.

**Comment by LordEclipse** [comment]
> > what about emagged borgs? if they try to sneak off into maints or disable cameras to do something illegal wouldn't AI be able to easily see that and snitch immediately??
> 
> Yes, but considering AI is kinda supposed to oversee borgs I think thats fine? I don't know how to make it not work if the borg is emagged.

Make it either disable the AI vision conponent or delete it. Right now emagging a borg chassis is permanent, but perhaps at some point we would be able to reverse emag effects on Borgs, so maybe just make it disable the component

**Comment by Chubbicous** [comment]
Would be better in the future instead if we ever get AI syncing with cyborgs like in SS13, that any borgs that are synced/slaved to the AI give it vision, so that independent or emagged borgs don't allow it to spy on them.

It will get annoying otherwise if you get an ion/emagged law as a borg that's against the crew but the AI can see what you're doing no matter what.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
I said this on discord but this actually needs code backing which is why I never gave it to borgs.

**Comment by Ilya246** [comment]
> Make it either disable the AI vision conponent or delete it. Right now emagging a borg chassis is permanent, but perhaps at some point we would be able to reverse emag effects on Borgs, so maybe just make it disable the component

Urist McSyndie emags Si-170 -> Si-170 goes into maint while AI is watching -> AI notices Si-170 doesn't grant vision -> ";Si-170 emaged! !!"

**Comment by ScarKy0** [comment]
>Urist McSyndie emags Si-170 -> Si-170 goes into maint while AI is watching -> AI notices Si-170 doesn't grant vision -> ";Si-170 emaged! !!"

Exactly what I was thinking

**Comment by ScarKy0** [comment]
>I said this on discord but this actually needs code backing which is why I never gave it to borgs.

Honestly no idea what I can do, so ill close the PR for now

**Comment by nymhole** [comment]
> > Urist McSyndie emags Si-170 -> Si-170 goes into maint while AI is watching -> AI notices Si-170 doesn't grant vision -> ";Si-170 emaged! !!"
> 
> Exactly what I was thinking

the ai would still be able to see the borg get emagged, the borg just immediately becomes less useful to ai and stops giving info, preventing the ai from gathering the info needed to make a report, the report would sound more like "borg got emagged southwest maints". this specifically is a silly reason to not follow through but it is not the only reason and i understand it. i simply dont agree with this specific sentiment.

**Pull request closed without merging**
