### PR TITLE
Admin access configurator

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

- Adds the Universal ID Card, an ID card with all access levels (NanoTrasen-aligned and otherwise) for use by admins in-game where such an ID Card is needed. This ID card was also given a new job icon, recolored from an existing one.
- Adds the Universal Access Configurator, an admin version of the access configurator which can modify access for all access levels including Syndicate, Nukeops and Central Command.
- Modifies the ID card in the Admin PDA to be the Universal ID Card.
- Modifies the storage fill for the admin ghost satchel to include one universal access configurator, to remove the need for admins to spawn one in a secluded spot, potentially getting the item taken from them.
- Adds the `Admin` suffix to the Admin PDA, the Universal ID Card and the Universal Access Configurator.

## Why / Balance

To my knowledge it is currently not possible to modify access of Central Command doors or Syndicate doors for admins. This PR resolves that issue.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Items and job icon:
image

Universal access configurator UI:
image

Entity spawn panel under search term `Admin`:
image

## Breaking changes

None.

**Changelog**

:cl: Arimah and TsjipTsjip
ADMIN:
- add: Universal access configurator which can modify all access levels with the correct ID card.
- add: Universal ID card which has all access levels.
- tweak: Admin PDA's spawn with a universal ID card, admin ghosts get a universal access configurator in their bluespace satchel.

### CODE REVIEW

**Comment by dvir001** [comment]
Is this also fixing the mapping issue with the linking of any syndicate airlocks to anything?
Im assuming it is.

**Comment by TsjipTsjip** [comment]
> Is this also fixing the mapping issue with the linking of any syndicate airlocks to anything?
> Im assuming it is.

I am unaware of any mapping issue regarding syndicate airlocks, please elaborate or link a github issue.

**Comment by dvir001** [comment]
> > Is this also fixing the mapping issue with the linking of any syndicate airlocks to anything?
> > Im assuming it is.
> 
> I am unaware of any mapping issue regarding syndicate airlocks, please elaborate or link a github issue.

More of a fork issue, I'll test it later as this should cover it.

**Comment by Emisse** [comment]
> > > Is this also fixing the mapping issue with the linking of any syndicate airlocks to anything?
> > > Im assuming it is.
> > 
> > 
> > I am unaware of any mapping issue regarding syndicate airlocks, please elaborate or link a github issue.
> 
> More of a fork issue, I'll test it later as this should cover it.

not a fork issue, we have it upstream as well

**Comment by Emisse** [comment]
this should fix it i believe though

**Comment by lzk228** [comment]
no it doesnt
image

**Comment by TsjipTsjip** [comment]
> no it doesnt

I still do not know what the issue being described is. Please describe it or link a GitHub issue so I can potentially look into resolving this.

**Comment by lzk228** [comment]
> > no it doesnt
> 
> I still do not know what the issue being described is. Please describe it or link a GitHub issue so I can potentially look into resolving this.

#26802

**Pull request merged**
