### PR TITLE
Update DrawDepth.cs

### LINKED ISSUE #30187: Grinders appear below lights
## Description

**Reproduction**

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by justdie12**
## About the PR

i think grinder and some more stuff can be higher than wallmount lights. resolve #30187

https://github.com/user-attachments/assets/a0c4bedc-d866-4f6a-bf88-16fd8a475b5f

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by justdie12** [comment]
#30187 solution

**Comment by VasilisThePikachu** [comment]
This pr is getting closed for the following reasons
1. This is not a correct fix, now you made all `WallMountedItems` render bellow `SmallObjects` which will most likely cause jank. A better fix should probably just modify the blender.
2. Webedit. [Feature prs will be closed without review](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#testing). Please use [git](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html)

**Comment by justdie12** [comment]
> Этот pr закрывается по следующим причинам
> 
> 1. Это неправильное исправление, теперь вы сделали весь `WallMountedItems` рендеринг ниже `SmallObjects`, что, скорее всего, вызовет сбой. Для лучшего исправления, вероятно, следует просто модифицировать blender imo.
> 2. Webedit. [Ссылки на функции будут закрыты без проверки](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#testing). Пожалуйста, используйте [git](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html)

2. I CANT USE THE F*CKIN GIT BRO
1. yes, cuz i look at all WallMountedItems and se no errors, so..?

**Comment by VasilisThePikachu** [comment]
>     2. I CANT USE THE F*CKIN GIT BRO

Sorry, this is PR policy, and I'm just following it. If you have any issues setting up git or learning it we are gladly to help you over discord or the forums.

**Comment by justdie12** [comment]
> > yes, cuz i look at all WallMountedItems and SmallObjects and see no errors, so..?
> 
> Since nothing seemed visible does not mean it may not break anything. Im not the only maintainer thinking this
jkay i solve this nvm
> > I CANT USE THE F*CKIN GIT BRO
> 
> Sorry, this is PR policy, and I'm just following it. If you have any issues setting up git or learning it we are gladly to help you over discord or the forums.
but why my #29596 is merged?

**Pull request closed without merging**
