### PR TITLE
Drone Interaction Checks & Cleanup

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Drones can no longer do any interaction with non-drone mobs, or use computers.
Made DroneToolComponent generic, now called UnremoveableComponent

**Changelog**

:cl: Rane
- remove: Drones can no longer interact with people at all or use computers.

### CODE REVIEW

**Comment by moonheart08** [comment]
Maybe allow drones to use specific consoles?
Namely the cargo *request* console, so they can *request* (not order) materials, solar computer, and alerts computer.
Doublecheck they can still mess with APCs and air/fire alarms.

**Comment by Elijahrane** [comment]
At least how I understand it there are 2 responses here:
1. Not everything that should be using the component in that check is using yet, so that sort of cleanup is needed anyway.
2. Drones really should probably not be able to interact with anything with a UI, all the important ones are covered now. Anything they can still use is pretty low-priority (imo) and it makes it more obvious it's using older UI standards

**Comment by mirrorcult** [comment]
conflicts

**Comment by Elijahrane** [comment]
@mirrorcult conflicts resolved

**Pull request merged**
