### PR TITLE
Apc & Substation resprite

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

resprites the APC and substation to be in line with the SMES.

Keeping visual design consistency helps make the items more obvious as to their purpose and creates cohesion.

ditches a bunch of currently unused APC states. i'll add them back later when they are needed.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by Nairodian** [comment]
I think the APC screens could be a little rough for accessibility. I'm not sure any fixes really as it's not my field but I know someone with blue-yellow colorblindness who said they couldn't tell the difference between the full and charging states (where as before the blue was easily recognizable from the green). I know the charging state has a filling bar but that might be hard to discern at a glance, they suggested something like a checkmark for full, an energy bolt for charging, and an x for empty, though there are probably some other good shapes to use.

**Comment by EmoGarbage404** [comment]
i might just add the current state as examine text on the APC since its really hard to do clear iconography on a canvas that is literally like 6x8 pixels.

**Comment by Flareguy** [comment]
I really dislike the outline under the APC's screen. It makes the contrast of it feel kind of weird and mushy.
I would either make it all black, or make it all the color of the outline.

**Comment by WarMechanic** [comment]
will this interfere with adding a visualiser to substations

**Comment by EmoGarbage404** [comment]
> will this interfere with adding a visualiser to substations

Not in any way that isnt trivial to fix

**Comment by Emisse** [comment]
agree with flare, also this doesnt quite feel "wallmounted"

**Comment by Emisse** [comment]
substation look great though

**Comment by Emisse** [comment]
yellow state should have a triangle warning sign, red state should have an empty battery sign, so colorblind folk will understand

**Comment by EmoGarbage404** [comment]
Content Client_PwrZfDmdqf

new APC screen states

**Comment by EmoGarbage404** [comment]
> Would this close #28987 ?

no

**Pull request merged**
