### PR TITLE
Doubles the e-shotgun charges

### PR DESCRIPTION
**Pull request by SoulFN**
## About the PR

HOS energy shotgun can now shot 16 times.
## Why / Balance

After removing auto charge e-shotgun became useless, even the enforcers and kamerers are better, because you can reload them in combat and use different type of ammo, like rubber or uranium.
With energy shotgun, you can shoot literally only fon 4 secounds, and then, you need to recharge it.
## Technical details

Just changed his max charge values in prototypes
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: HOS energy shotgun max charges doubled

### CODE REVIEW

**Comment by Boaz1111** [comment]
personally, I think doubling it is too much.

**Comment by SoulFN** [comment]
> personally, I think doubling it is too much.

It can be EMPed and become useless, nukies, agents and even chemists can make EMP, but if it will be too OP, we can decrease charges or shot speed.

**Comment by Boaz1111** [comment]
i mean.. we could just make it emp proof

**Comment by baddiePRO** [comment]
EMP proof weapons would be an interesting concept, especially with eshotgun having stun mode

**Comment by thebadman4662** [comment]
> EMP proof weapons would be an interesting concept, especially with eshotgun having stun mode

EMP proof stunmeta, lets go. :trollface:

**Comment by Carmell0** [comment]
Bring back self recharge. HoS should have a reliable weapon, it only makes sense.

**Comment by SoulFN** [comment]
> Bring back self recharge. HoS should have a reliable weapon, it only makes sense.

I think, maintainers will not accept self recharge PR.

**Comment by BramvanZijp** [comment]
While I agree that the shotgun needs a buff, I don't think simply doubling the charges is the way to go about it.

Obviously I would prefer it if #32104 got merged (I made that) but if it does not, this might help but we'd have to see.

**Comment by SoulFN** [comment]
Closed because i think #32104 is a better solution

**Pull request closed without merging**
