### PR TITLE
TG Station Burgers

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

- Made some burgers craftable:
   - Ghost burger
   - McRib (Also made bbq ribs craftable due to recipe)
   - Spell burger
   - Crab burger (Added crab crate to cargo for ingredients)
   - Crazy burger
   - Roburger
   - Baseball burger
   - Rat burger
- Added burgers from TG
   - Cat burger (buy cat ears from uplink)
   - Human burger (Humans, dwarves and lizards now drop their own meats when butchered)
   - Plain burger
- Updated the recipes and tastes of most burgers

**Media**

Not needed?

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added 3 new burgers and made 8 unused burgers craftable.
- add: Cargo can now purchase a crate of crabs.

### CODE REVIEW

**Comment by Kirillcas** [comment]
is nice

https://user-images.githubusercontent.com/124053750/230721989-5eb96e04-f357-4018-9509-f4122748ea79.mp4

**Comment by Jackal298** [comment]
cool PR, can you add the recipe for xeno bread and spider bread?

**Comment by potato1234x** [comment]
> xenobread and spider bread? 
Ive ported over all the food and recipes from tg and im splitting them into their own prs, bread is next.

**Comment by Jackal298** [comment]
> > xenobread and spider bread?
> 
> Ive ported over all the food and recipes from tg and im splitting them into their own prs, bread is next.

Thank you

**Comment by LedinecMing** [comment]
Please, revert "cat ears from cat butchering" this is horrible idea.

**Comment by EmoGarbage404** [comment]
> Please, revert "cat ears from cat butchering" this is horrible idea.

You seem to be in the wrong place and repo.

**Comment by potato1234x** [comment]
> Please, revert "cat ears from cat butchering" this is horrible idea.

Having to **butcher** a cat for them would probably deter people from wearing them. Probably.

**Comment by EmoGarbage404** [comment]
Wait actually thats in this pr? That feels goofy.

**Comment by deltanedas** [comment]
doesnt that completely negate the N tc for buying them

**Comment by DogZeroX** [comment]
Yeah don't include that.

**Comment by potato1234x** [comment]
I dont see how else i could make the cat burger work. Should i just remove it entirely?

**Comment by DogZeroX** [comment]
Leave it, they'll either get it in salvage or with tc.

**Comment by potato1234x** [comment]
reverted.

**Comment by keronshb** [comment]
Currently frozen due to a freeze on food recipes: #8524

**Comment by metalgearsloth** [comment]
Re-open when chef rework is done.

**Comment by metalgearsloth** [comment]
Under https://github.com/space-wizards/space-station-14/issues/8524
As food doesn't really have a purpose it's subject to removal at any time pending chef work.

**Pull request merged**
