### PR TITLE
Resprite buckets

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Even though the bater wucket was funny, the sprite was crunchy as all hell. Welcome, regular bucket!

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- tweak: Resprited buckets.

### CODE REVIEW

**Comment by UbaserB** [comment]
It's worth mentioning that the sprite looks a little off to me, so please tell me how i can improve and fix it.

**Comment by EmoGarbage404** [comment]
The perspective and shading on this are generally just really strange and offputting. Especially regarding the base and top, they dont seem to follow the correct perspective. Its also completely pillowshaded on the front.

Also the switch from blue to gray is a downgrade IMO. Theres no need to desaturate random sprites.

**Comment by UbaserB** [comment]
> The perspective and shading on this are generally just really strange and offputting. Especially regarding the base and top, they dont seem to follow the correct perspective. Its also completely pillowshaded on the front.
> 
> Also the switch from blue to gray is a downgrade IMO. Theres no need to desaturate random sprites.

it's not for sake of desaturation, i just wanted to make the bucket metal. Let me try different shading.

**Comment by deltanedas** [comment]
bucket is still metal just painted blue :trollface:

**Comment by UbaserB** [comment]
ok pls rereview i fixed it up a bit

**Comment by UbaserB** [comment]
low resolution viewport

**Comment by UbaserB** [comment]
ive tweaked it again

**Comment by potato1234x** [comment]
i think this sprite is getting hate because it looks like modern tg beakers, personally i think it looks better than the current one

**Comment by K-Dynamic** [comment]
I would prefer the top to match the bottom in roundness

**Pull request merged**
