### PR TITLE
Fix accidental plasma burn nerf

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR
This change buffs plasma burn energy output.

## Why / Balance
After time compression was added, it became very apparent that plasma oxygen burns became very weak. Previously, it was impossible to sustain a TEG at 8x atmos speedup where a 1x speedup would be stable.

## Technical details
Multiplies plasma energy output by 10x.

## Media
image
<sup>Note: This *3.2 MW* TEG was built with a 32.3kL input pipenet.</sup>

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl: router
- tweak: Plasma now outputs 10x as much energy per mole.

### CODE REVIEW

**Comment by FrezonGrandmasterJurgenHabicht** [comment]
good, merge!

**Comment by Terraspark4941** [comment]
valid, although i believe the plasma fires were intentionally supposed to be more survivable?
eh, more power to engi over the greytide

**Comment by deltanedas** [comment]
active fires still light you on fire, which is what will do damage if you have a hardsuit on

**Comment by BasedUser** [comment]
Hang on, why does tritium have that term anyway?

**Review by Partmedia — APPROVED** [review]
Thanks for the amended fix. I tested and a plasma fire is a bit more deadly but still somewhat survivable. Since you say this fixes the burn chamber then we should go ahead.

**Pull request merged**
