### PR TITLE
Add markers (invisibility) to brainless ghost roles.

### PR DESCRIPTION
**Pull request by tom-leys**
## About the PR
- No longer have ERT teammembers or the public stand around like zombies for the greytide to loot while they wait for ghosts to animate their flesh
- MarkerComponent is what makes spawnpoints invisible. Add it to Ghost Roles with no mind or AI.
- This does not make the entity invulnerable, it's just not interactable by players. So area attacks or atmos issues might still kill it while it's waiting for a ghost
- Use showmarkers to see these entities

**Media**

https://github.com/space-wizards/space-station-14/assets/5285589/c26baf0d-4de3-48da-b456-d16c045da551

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Only admins will notice this change.

### CODE REVIEW

**Comment by deltanedas** [comment]
you can use ghost role spawners to prevent them existing at all before a ghost picks them

**Comment by tom-leys** [comment]
> you can use ghost role spawners to prevent them existing at all before a ghost picks them

Yeah, it's a content creation problem - there are a lot more ghost roles entities set up than spawners. Perhaps a better approach is to manually or somehow automatically create spawners.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
This is a hack. Please don't use markers.

**Comment by tom-leys** [comment]
Yeah, I think this idea is not popular. Ah well. I thought it would be helpful.

**Pull request closed without merging**
