### PR TITLE
Predict tile-prying

### PR DESCRIPTION
**Pull request by metalgearsloth**
Lattice itself we won't predict as we can't predict the entity spawn (yet) nor decal removal so this is the cleanest atm. This just means the do_after is predicted which feels cleaner.

Also removed a turfhelper that got added when it should be on the system instead + did some other cleanup around the place.

:cl:
- tweak: Tile-prying do_after is now predicted.

### CODE REVIEW

**Review by Partmedia — APPROVED** [review]
I got pinged as code owner for a superficial change but this looks fine.

Nitpick is that this is probably not deserving of a changelog entry.

**Comment by VasilisThePikachu** [comment]
Had we not mentioned we would not use programmer speak (do_after) for changelogs in a maintainer meeting?

**Comment by metalgearsloth** [comment]
> Had we not mentioned we would not use programmer speak (do_after) for changelogs in a maintainer meeting?

idk what else a player would call it given it's not referred to in a guidebook to my knowledge, but most ss13 players I know are familiar with the terminology.

**Comment by VasilisThePikachu** [comment]
> > Had we not mentioned we would not use programmer speak (do_after) for changelogs in a maintainer meeting?
> 
> idk what else a player would call it given it's not referred to in a guidebook to my knowledge, but most ss13 players I know are familiar with the terminology.

Progress bar

Though it does not really fit the current changelog. Maybe something like "Prying tiles feels less laggy now" or something similar.

**Comment by metalgearsloth** [comment]
> > > Had we not mentioned we would not use programmer speak (do_after) for changelogs in a maintainer meeting?
> > 
> > 
> > idk what else a player would call it given it's not referred to in a guidebook to my knowledge, but most ss13 players I know are familiar with the terminology.
> 
> Progress bar was agreed upon i think
> 
> Though it does not really fit the current changelog. Maybe something like "Prying tiles feels less laggy now" or something similar.

Even before I started coding I knew what prediction was but "less laggy" feels a lot more vague (framerate? network? idk) but maybe that's just because I live in OCE. I don't recall on the progress bar bit and didn't find anything in the past 2 months of notes.

**Comment by VasilisThePikachu** [comment]
Think it was said via voice, maybe it was not written down.

I did not know what a doafter was until I was told. Being new to 14 back then. I know what client prediction was from way before but someone less tech literate may not.

I was just providing a suggestion. I dont mean this to be rude.

**Pull request merged**
