### PR TITLE
Wide-spectrum anomaly locator

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

Adds a new item to the game "Wide-spectrum anomaly locator", being a modified anomaly locator. It has a 2-fold increased anomaly search range, but the distance detection function for it is disabled.

## Why / Balance

On large maps, the process of finding anomalies is difficult. This locator helps to detect the approximate location of anomalies, but does not remove the need to use conventional anomaly locators.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/c226b5a0-0c07-4e86-b7b3-db8ee4128382

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added wide-spectrum anomaly locator.

### CODE REVIEW

**Comment by mirrorcult** [comment]
interesting concept, i like it @EmoGarbage404

**Comment by TheShuEd** [comment]
@EmoGarbage404 
Ha, this is my first PR, and I'll say right away that I can't make a full-fledged second mode yet, I need time and experience on other PRs before trying to do this.

**Comment by chromiumboy** [comment]
I'm not sure how useful this would be, a 40 tile radius is a big area to search (5000+ tiles). And without directionality, if you have more than one anomaly on the station (e.g. when science has contained one and is farming it for points), it's highly likely that this device will pick up both of them at the same time, and you won't be able to distinguish between them

**Comment by TheShuEd** [comment]
@chromiumboy 
This locator has no purpose to find a specific location of the anomaly, but rather to answer the question "is it even here somewhere?", and this is necessary for really large maps, such as this one I'm working on:
https://github.com/TheShuEd/Gate-Station-SS14/tree/main

**Comment by chromiumboy** [comment]
> @chromiumboy This locator has no purpose to find a specific location of the anomaly, but rather to answer the question "is it even here somewhere?", and this is necessary for really large maps, such as this one I'm working on: https://github.com/TheShuEd/Gate-Station-SS14/tree/main

I see what you mean. But it still runs into the problem I mentioned before, when you have overlapping anomalies. At that distance it can be hard to tell if there is another anomaly nearby that you don't already know about. Also it would only be useful for detecting unannounced anomalies (as ones that are generated are always announced to the whole of science). This would require the science team to be proactive in looking for them. But given that anomaly spawns are very rare, no one in science is going to be doing that

**Comment by NancokPS2** [comment]
Well yeah, it's not perfect. It merely gives you a general area. That's the point.  
  
And i don't see how this wouldn't help with manual spawns? Because you know one exists doesn't mean you have the least idea of where it actually is. PLUS you can still use the normal locator to find it once close enough.  
  
This is meant to HELP find anomalies, not do so on it's own.

**Comment by chromiumboy** [comment]
Personally I'm not convinced, it's uses seem too niche to me

Maybe this could work as an alternate mode for the base scanner, but it doesn't warrent being its own separate device

**Comment by NancokPS2** [comment]
Well, as EmoGarbage suggested, this is probably the objective in the future.  
  
But it would probably be a new PR if anything.

**Comment by TheShuEd** [comment]
@EmoGarbage404 
I will reopen the PR a little later, I want to make changes from the master to the branch, and be able to make another other PR

**Pull request closed without merging**
