### PR TITLE
NSS Pillar mk2 - New Pillar

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Remade pillar from scratch totally changing a few departments and making the map larger in general from the inside out.

This culminates in:
- Bigger park and better HoP office and bridge.
- Moved a bunch of service based stuff to the left of the map and moved engineering to the top right.
- Atmos is now it's own department on the far left of the ship / station.
- A new arrivals, old arrivals is a backup docking point and also has the chapel.
- Lots more maint rooms and player opportunity rooms like shops and offices.
- Bigger and better court house with room for jury, lawyers for both sides, accused and judge.
- A new medbay in a "donut" shape so should be easier to navigate.

**Screenshots**

All screenshots are at 1.2x zoom so bare that in mind.
park
New Park. Slighly larger than the old.
HOP
HOPs office below the park.
cargo1
Cargo in the same spot as before, left of park. Sligthly new layout.
cargo2
Bottom of cargo showing the dock and QMs office.
library
Library in it's new position left of cargo. Left side of station is now a passenger focused area.
boxing
Boxing ring opposite library. EVA is down here too.
abandoned
Abandoned area left of boxing ring. Features two escape pod docks, a hangar bay and an old manufacturing area.
atmos1
Lower atmos, setup with two mix tanks and atmos locker room.
atmos2
Upper atmos, featuring all the tanks, filtering, canisters and other bits.
chapel
Chapel has been moved to left side of station, this is attached to where the old arrivals area was.
sec1
Left side of sec. Same place as previously, rejigged to have a staff room and dorm.
sec2
Right side of sec, more or less the same but with a bathroom for visitors and a closet in the corridor.
sec3
Upper sec showing off the armory and locker room. Also shows the security dock in top left with two airlocks and interrogation room.
perma
Perma brig above security as it was. Slightly bigger with three bedrooms, two toilets, stuff to do. Complete with a prisoner suppression system and N2O tank.
bridge1
Upper portion of bridge. Bridge is now wider and taller allowing for a more spacious vault and generator room.
court
Mega court house to drink your mega pints. Features security law office on the left for taking in the accused, tables for both defence and offence lawyers, a witness stand and on the right a jury stand and generic law office.
dorms
Dorms to the right of the court house. This is beside where the new arrivals is so players arrive more central and should hopefully have to run less.
medbay1
New medbay, long time coming. Hopefully it's better received with a nice big waiting room again, decent size them, cloning room right at the fore.
medbay 2
Surgery and virology in the lower with CMO having a good sight of everything.
medbay3
Right side of medbay with morgue, staff room and locker room.
engi1
New compact engineering department is now up where chapel and library was, right beside escape. Featuring big AME room, SMES bank, staff room, locker room and secure storage etc.
engi2
Above engineering is another SM room, such as was on original Pillar. This can be repurposed as a massive AME SMES room if people must (since SM is far off, but Tesla and Nuclear are closer).
sci1
Not a whole lot to show off in science. It has robotics and materials labs up top as was previous, shown here is a nice big containment room for testing artefacts.
salvage1
SALV
**Changelog**

:cl:
- add: NSS Pillar has been rebuilt from scratch! Expect a lot of changes and follow the directional signs not to get lost.

### CODE REVIEW

**Comment by Stealthbomber16** [comment]
im very excited to see how this compares to the infamous launch of the original NSS pillar

**Comment by Emisse** [comment]
excited to check it out, if its not merged when im home from work ill take a look at it

**Comment by Peptide90** [comment]
> excited to check it out, if its not merged when im home from work ill take a look at it

Going to do atmos piping tomorrow as ODJ is busy so should be ready for testing then.

@Stealthbomber16 hopefully it's tested more than any previous map launches. Whether the design changes are well received are to be seen. It could still benefit from a pass from someone for flavour, maints decor etc.

**Comment by Peptide90** [comment]
Added a fair few flavour things while I was doing atmos pipes so there's that. Screenshots are in. Haven't bothered with air alarms yet and we've lasted till now but if it's necessary then drop a comment requesting changes and I'll get to it in a few days.

**Comment by 5150Con** [comment]
For current Atmos mix chambers, there should be a better way to filter gases out, as I don't see any pipes to filter gases for Tritium production or other mixes that produce good and bad gas together. Maybe add another piping system that also leads to space, such as on Bagel Atmos. Additionally, for the holding chamber in Top Atmos, would putting air injector instead of powered vents be more effective?

**Comment by Peptide90** [comment]
Just done some changes such as giving magboots and jetpacks to EVA and Salvage. Gave jetpacks to Security. Removed public engivends because apparently that's a thing now. Added some misc decals and plushies. Gave doctors a paramedic suit locked with CMO access. There's a sign to ask them for it.


> For current Atmos mix chambers, there should be a better way to filter gases out, as I don't see any pipes to filter gases for Tritium production or other mixes that produce good and bad gas together. Maybe add another piping system that also leads to space, such as on Bagel Atmos. Additionally, for the holding chamber in Top Atmos, would putting air injector instead of powered vents be more effective?

All vents are passive in the tanks as that's what I've been told is the current go to. There's a connection port for pumping gas out of those chambers to take to the mix chambers so hopefully that's sufficient? It filters to the tank then you take from the tank.

**Pull request merged**
