### PR TITLE
Tag metal things metal

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
This tags a few common metal objects with the existing 'Metal' tag. This is so that the electromagnet (separate PR) picks up more items.

**Media**
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
N/A

### CODE REVIEW

**Comment by AJCM-git** [comment]
tbh, i think the "Metal" tag should deprecated and instead use/check `MaterialComponent`s in the usages

**Comment by EmoGarbage404** [comment]
There was talk of combining chems/materials and giving things intrinsic materials a la /tg/. I imagine thats pretty out of scope, but its something worse considering, as this implementation might be prone to various issues.

**Comment by EmoGarbage404** [comment]
There was talk of combining chems/materials and giving things intrinsic materials a la /tg/. I imagine thats pretty out of scope, but its something worse considering, as this implementation might be prone to various issues.

**Comment by moonheart08** [comment]
why are you using a tag for something you're trying to query for. Use a component or, better, extend materials.

**Comment by Partmedia** [comment]
> why are you using a tag for something you're trying to query for. Use a component or, better, extend materials.

Because the `Metal` tag has existed for a long time and seems like a great candidate to confer "whether or not it is made of metal". Doing the latter would require a bunch of previously tagged items to gain MaterialComponents.

**Comment by AJCM-git** [comment]
> Because the Metal tag has existed for a long time and seems like a great candidate to confer "whether or not it is made of metal". Doing the latter would require a bunch of previously tagged items to gain MaterialComponents.

Is there a problem with adding that component to the usages?

**Comment by Partmedia** [comment]
> Is there a problem with adding that component to the usages?

No, I can go ahead and make this change if this is the best way forward. To be clear, we're thinking about adding this component to all items currently tagged 'Metal' and keeping the 'Metal' tag?

**Comment by AJCM-git** [comment]
Adding it to all items tagged like that (and dealing with the one code reference in microwave) and deleting the tag would be the best

**Comment by Partmedia** [comment]
Overcome by events, will re-open at some point.

**Pull request closed without merging**
