### PR TITLE
Make sawedoff contra

### PR DESCRIPTION
**Pull request by sporkyz**
## About the PR

Made the sawn-off minor contraband to match the DB.
## Why / Balance

The sawn-off is still a potentially lethal firearm. It should be treated with the same contraband status as the double barrel. Requested in https://github.com/space-wizards/space-station-14/issues/31047
## Technical details

Made the sawn off have BaseMinorContraband as a parent
## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Set the sawn-off to be properly registered as minor contraband.

### CODE REVIEW

**Comment by UbaserB** [comment]
The issue you linked asks to restrict it to bartender/security, not minor contraband

**Comment by sporkyz** [comment]
> The issue you linked asks to restrict it to bartender/security, not minor contraband

I think a bartender/security contraband category does not currently exist because bartender isn't classified as a department, hence why the DB isn't restricted to bartender/security either. I can try and change this around though if you feel it'd be more reasonable.

**Comment by sporkyz** [comment]
Ah, yep. 
image
Seems the option isn't currently implemented.

**Comment by UbaserB** [comment]
> I think a bartender/security contraband category does not currently exist because bartender isn't classified as a department, hence why the DB isn't restricted to bartender/security either. I can try and change this around though if you feel it'd be more reasonable.

yes please, this is probably better (there are many things that the bartender is allowed to have that warrants its own category: armor vest, shotgun, bandolier)

**Comment by sporkyz** [comment]
> > I think a bartender/security contraband category does not currently exist because bartender isn't classified as a department, hence why the DB isn't restricted to bartender/security either. I can try and change this around though if you feel it'd be more reasonable.
> 
> yes please, this is probably better (there are many things that the bartender is allowed to have that warrants its own category: armor vest, shotgun, bandolier)

Alright. Should I leave this PR to be merged as a temporary solution while I work on the new system, or just close it and create a new PR once the job-contra changes are ready?

**Comment by UbaserB** [comment]
> Alright. Should I leave this PR to be merged as a temporary solution while I work on the new system, or just close it and create a new PR once the job-contra changes are ready?

it probably shouldnt take too long to pr so just close it in the meanwhile

**Comment by sporkyz** [comment]
Closing, working on a rework to the contraband category system instead

**Pull request closed without merging**
