### PR TITLE
Adding shock collars to the research.

### PR DESCRIPTION
**Pull request by Iced-Coded**
## About the PR

Reversed [0f6808e](https://github.com/space-wizards/space-station-14/commit/0f6808e16a7b7beb3a9a24309b27bb1426c72c17), and then, removed shock collars from being round-start, added them to the same research as electropack (Special Means), made the research more expensive as a result of it unlocking not just one, but two items. Also, antag's objective to steal shock collar is now an objective to steal electropack, as electropack is still round-start (from the [0f6808e](https://github.com/space-wizards/space-station-14/commit/0f6808e16a7b7beb3a9a24309b27bb1426c72c17) commit.)

## Why / Balance

I think it's a bit too unnecessary to completely remove such item from a game, just for reasons that it can be used to make unusual traps, events (for admins) and etc.
Personally, I don't think that any player would follow through this **just** to make a shock collar and do some inappropriate/weird stuff.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The R&D can now research shock-collars, and print them on a secfab

### CODE REVIEW

**Comment by Emisse** [comment]
no

**Comment by Iced-Coded** [comment]
> no

Why so?

**Comment by EdenTheLiznerd** [comment]
People get way too weird with the collars, it's been mass agreed that they can't be handled by the community and need to be removed.

**Comment by Iced-Coded** [comment]
Of course, I can make it **more harder** to obtain, if you think that already locking it beside research isn't enough.

**Comment by lzk228** [comment]
> I don't think that removing one thing because some people got weird with it is correct.

people violate the server's rules with the thing, thing got removed
returning the thing with harder way to obtain won't make people don't violate the rules

**Comment by Iced-Coded** [comment]
> returning the thing with harder way to obtain won't make people don't violate the rules

It will, since, the research will work like a form of **Barrier Effect**, in short, people will not do _x_ if it requires _lots of effort_ or/and is _heavily controlled_.
I will make a shock collar an Tier 2 research, which, imho, will require effort, to some extent.
Prove me if I'm wrong, I guess.

**Comment by Iced-Coded** [comment]
Closed due to the fact, that participants can't hold open conversations.

**Pull request closed without merging**
