### PR TITLE
[Remove] Removes some shoes from clothesmate

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

This is in an effort to clean up the clothesmate, as it has way too much stuff in it. The shoes are still in the game, so if someone wants to make a shoe vender they can.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Removed some shoes from the clothesmate.

### CODE REVIEW

**Comment by lzk228** [comment]
make that shoe vender then

**Comment by OctoRocket** [comment]
I have literally never seen anyone have any other shoe on than the white, brown, and black shoes.

**Comment by lzk228** [comment]
and with that you should reduce the price of the refill kit

**Comment by OctoRocket** [comment]
The refill kit refills *any* type of clothes vender, so it shouldn't reduce it.

**Comment by Nairodian** [comment]
I know of a few people who get the different types of shoes to match their outfit.

**Comment by OctoRocket** [comment]
Then I'll wait for a shoe vending machine texture, and then I'll make a shoe vender.

**Comment by Emisse** [comment]
shoes are fine in here imo, i want to separate out silly things and accessories so they can be in other pools/mapped

**Comment by OctoRocket** [comment]
Yeah, there is probably a better solution.

**Comment by Emisse** [comment]
closing due to my earlier comment

**Pull request closed without merging**
