### PR TITLE
Goon Mutator Pill (April Fools)

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds a goon human mutator pill to maint lockers, it mutates you into a goonstation human
the clothes dont fit that well but what can you do

## Why / Balance

would be quite funny to see a guy from a completely different codebase just walking around, would create a "kris where the fuck are we" type situation

## Media

https://github.com/space-wizards/space-station-14/assets/79580518/b36ae591-f708-44a6-8504-024fd4ea8e9d

https://github.com/space-wizards/space-station-14/assets/79580518/d274861b-d0ab-4b3b-9a38-a67fd4581f5c

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added the interdimensional pill. It can be found in maint lockers, and turns you into an interdimensional being.

### CODE REVIEW

**Comment by Catdere** [comment]
this is cursed

**Comment by Golinth** [comment]
genuinely terrifying. I love it

**Comment by Emisse** [comment]
remove the farts

**Comment by VasilisThePikachu** [comment]
Thank you for your PR, unfortunately, the maintainer's conscious was to deny it for the reason that farts are just uh... weird to say the least for this repo, and may be abused. We also don't find this funny in general as it just gives you a different sprite.

Thank you for your effort and good luck next year!

**Pull request closed without merging**
