### PR TITLE
update meta

### PR DESCRIPTION
**Pull request by lzk228**
- missing external airlocks bolting
- missing tiny fans under dock airlocks

### CODE REVIEW

**Comment by Emisse** [comment]
what are all these prs for, tiny fans shouldnt be mapped any more

**Comment by lzk228** [comment]
the issue is when external shuttle airlock is docked, it still causes spacing, so there is A LOT spacing even if airlocks are docked

**Comment by Emisse** [comment]
that should be fixed instead

**Comment by lzk228** [comment]
wyci, so now we need tiny fans for at least good game experience

**Comment by metalgearsloth** [comment]
Not adding placeholders.

**Comment by deltanedas** [comment]
airlocks block flow when docked (but not when opened by a player) so fan isnt needed

**Pull request closed without merging**
