### PR TITLE
Cak

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

A new cake cat has been added to the game. It can be baked by chefs according to the following recipe:

1 Cake plain
1 snacks raisin
1 animal heart
5u Cognizine
15u Milk
15 second in microware
and...
the cak is ready! And he is the ghostrole with OwO accent.

## Why / Balance

cak

## Technical details

cak

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/03e191a8-bcc7-4195-967b-295daa4fbf1c

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
cak 

**Changelog**
:cl:
- add: Now chefs can make a cake cat. You will need: 1 Cake plain, 1 raisin snack, 1 animal heart, 5u cognizine, 15u milk, 15 second in microwave. And new sweet ghost role CAK is created!

### CODE REVIEW

**Comment by deltanedas** [comment]
since it takes cogni to make it should have a replacement accent

**Comment by TheShuEd** [comment]
No. Not enough.

**Comment by TheShuEd** [comment]
and maybe, uh. give him an OwO accent.

**Comment by deltanedas** [comment]
> Not enough.

it only takes 5u and this costs 10u

**Comment by TheShuEd** [comment]
image
OwO is better!

**Comment by TheShuEd** [comment]
and now 5u cogni, 15u milk

**Comment by UbaserB** [comment]
this is terrifying

**Comment by KompaniLinge** [comment]
is it edible

**Comment by TheShuEd** [comment]
yes, edible

**Comment by Emisse** [comment]
approve

**Pull request merged**
