### PR TITLE
Adds stamina damage to the toy sword

### PR DESCRIPTION
**Pull request by Raitononai**
## About the PR

Gives 8 stamina damage to the toy sword, so you can have duels with your friends instead of endlessly hitting eachother with plastic. Was going to be 5 since it doesn't deal slight brute like boxing gloves but the toy hammer also deals 8 stam so whatever.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Gave the toy sword slight stamina damage, like the boxing gloves and toy hammer.

### CODE REVIEW

**Comment by keronshb** [comment]
Don't do this. It can become a mass-produced stun weapon.

Instead, make a recipe for training Bokken that needs wood and supplies from botany.

**Comment by Equivocateur** [comment]
> Don't do this. It can become a mass-produced stun weapon.

Since when you can produce it?
Its a rare drop off arcades and happy honks.

**Comment by asperger-sind** [comment]
> Don't do this. It can become a mass-produced stun weapon.

You used to be able to mass produce it before when you could just hack an arcade machine and shit out infinite toys, that got changed a while ago.

**Comment by Raitononai** [comment]
>  Don't do this. It can become a mass-produced stun weapon.

Boxing gloves and toy hammers do the same stamina damage as what I added and are way easier to get and i'll be surprised if you can find someone using any of them as actual stun weapons.

**Comment by asperger-sind** [comment]
Also to note, you need 15 melee hits from a toy e-sword to actually stun someone, even if its mass produced it wouldn't really matter.

**Comment by deltanedas** [comment]
real

**Comment by Emisse** [comment]
this is fine, it cant be produced and it has precedent from others

**Pull request merged**
