### PR TITLE
Adds industrial seed processor to the hydroponics research, makes the basic one a roundstart board

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Adds industrial seed processor to the hydroponics research, makes the basic one a roundstart board
## Why / Balance

Basic hydroponics needs some fancy sci-fi hydroponics gear instead of roundstart things. This one produces 2-5 seeds instead of the normal 1-3
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Boaz1111
- add: Added the industrial seed processor to the basic hydroponics research. It makes more seeds.

### CODE REVIEW

**Comment by deltanedas** [comment]
seed processor is only needed in an emergency rn it should do more

**Comment by Boaz1111** [comment]
> seed processor is only needed in an emergency rn it should do more

what do you mean?

**Comment by deltanedas** [comment]
if you are doing everything right clipping is all you need for seeds, seed extractors are only needed if a shitter spades them all or they otherwise die and you have no spare seeds

**Comment by GreyMario** [comment]
cargo when it can order a seeds crate, a medical seeds crate, an exotic seeds crate, and a restock for the seed vendor

**Comment by Boaz1111** [comment]
well.... it's better than the old thing, is it not?

**Comment by deltanedas** [comment]
sure but theres still no reason to make it since its just for emergencies you only need to get 1 seed out of it then youre good, any more isnt needed

**Comment by Stealthbomber16** [comment]
This does not need to exist. Botany already has infinite seeds with plant clippers.

**Comment by mirrorcult** [comment]
this is incredibly useless yeah

**Comment by metalgearsloth** [comment]
Yeah I think botany balance atm for seed production is non-existent so this isn't going to have a meaningful purpose until more botany work is done.

**Pull request closed without merging**
