### PR TITLE
Make ReconnectTest async behavior consistent

### PR DESCRIPTION
**Pull request by DrSmugleaf**
In this economy

Requires https://github.com/space-wizards/RobustToolbox/pull/1442 for the test to work but not for this PR to build.

Previously it would fail and succeed randomly, specially on Windows.

### CODE REVIEW

**Comment by Zumorica** [comment]
If this fixes it reliably I'll grant you 3 (three) free review tokens

**Comment by DrSmugleaf** [comment]
> If this fixes it reliably I'll grant you 3 (three) free review tokens

What if all three are huge body system PRs

**Comment by Zumorica** [comment]
I regret my comment already but sure

**Comment by Erisfiregamer1** [comment]
Apparently, this key (eaa7267d-1f2c-4723-bec7-46890c8a1278) wasnt foud in the dictionary. I was looking at the commit logs.

**Comment by metalgearsloth** [comment]
> 
> 
> Apparently, this key (eaa7267d-1f2c-4723-bec7-46890c8a1278) wasnt foud in the dictionary. I was looking at the commit logs.

We know it's been happening for months in the test

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
