### PR TITLE
Give headrevs synd key in bag

### PR DESCRIPTION
**Pull request by Subversionary**
## About the PR

Gives headrevs a synd key in bag together with the flash and sunglasses.

## Why / Balance

Headrevs are running around like headless chickens for 10 minutes without any semblance of cooperation. Running around station looking for blue "R"s is not good.
Headrevs should logically have a preestablished line of comms between each other.

Also it makes validchecks easier for secoffs that are short on mindshields.

Discord feedback thread here: https://discord.com/channels/310555209753690112/1167981870923923476.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Headrevs receive a blood-red encryption key.

### CODE REVIEW

**Comment by UbaserB** [comment]
sounds op and will ruin the balance revs have rn.. i personally feel like its at a pretty sweet spot

**Comment by Subversionary** [comment]
> sounds op and will ruin the balance revs have rn.. i personally feel like its at a pretty sweet spot

Revs are not really balanced - its an immediate steamroll on either side depending on who takes initiative first. This would go in-hand with #20958 if someone remembers that pr even exists.

**Comment by TK-A369** [comment]
Maybe create new radio channel, specially for revolutionaries?

**Comment by IProduceWidgets** [comment]
> Maybe create new radio channel, specially for revolutionaries?

What why? Thats just needless. They're "sponsored" by the syndicate anyway in the role text, and if they ever did exist at the same time (which would have to be an admin addition at the moment) then it makes sense that they could contact the syndies or nukies to me.

**Comment by Subversionary** [comment]
> Oh actually there is one natural occurrence. Loneops. Still, seems good to me.

Revs are not obligate to cooperate with the loneop.

**Comment by TsjipTsjip** [comment]
Would even go so far as to say that their objectives are directly contrary to eachother. Revolutionaries want to take control of the station, nuclear operatives want there to not be a station.

**Comment by QuietlyWhisper** [comment]
Consider giving them a radio with a custom radio channel instead, to avoid all this?

**Comment by Subversionary** [comment]
> Consider giving them a radio with a custom radio channel instead, to avoid all this?

It’d be bloat innit

**Comment by QuietlyWhisper** [comment]
> It’d be bloat innit

parent: radio
components:
rev channel

profit

**Comment by notquitehadouken** [comment]
or just expect revs to know what they're doing

**Comment by Emisse** [comment]
I don't think revs should have their own radio channel or use another antags. The main point of them is that they are radicalized crew.

**Comment by Subversionary** [comment]
jit built different

**Pull request closed without merging**
