### PR TITLE
Fixes Torch

### LINKED ISSUE #3243: Torch is battery powered
## Description
The torch makes clicky noises when turned on and off, and when it's empty it says "dead cell!".

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Closes #3243.

-Changes ExpendableLightComponent.cs from "on:off" to "lit:unlit" since that makes more sense. 
-Modified Flare to reflect this change.
-Moved torch from fluff_lights.yml to it's own yml.
-Updated torch.rsi meta.json.
-Adds crafting recipe for the torch.

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Get an exception (might've already existed) on server-side for the sprite:

[ERRO] go.comp.sprite: Layer with index '2' does not exist, cannot set set! Trace:
   at System.Environment.get_StackTrace()
   at Robust.Server.GameObjects.SpriteComponent.LayerSetState(Int32 layer, String stateId) in D:\Programming
Projects\space-station-14\RobustToolbox\Robust.Server\GameObjects\Components\Renderable\SpriteComponent.cs:l
ine 274
   at Content.Server.GameObjects.Components.Interactable.ExpendableLightComponent.UpdateSpriteAndSounds(Bool
ean on) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\Interactable\Expend
ableLightComponent.cs:line 117
   at Content.Server.GameObjects.Components.Interactable.ExpendableLightComponent.TryActivate() in D:\Progra
mmingProjects\space-station-14\Content.Server\GameObjects\Components\Interactable\ExpendableLightComponent.c
s:line 68
   at Content.Server.GameObjects.Components.Interactable.ExpendableLightComponent.Content.Shared.Interfaces.
GameObjects.Components.IUse.UseEntity(UseEntityEventArgs eventArgs) in D:\ProgrammingProjects\space-station-
14\Content.Server\GameObjects\Components\Interactable\ExpendableLightComponent.cs:line 36
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.UseInteraction(IEntity user, IEntity
used) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionS
ystem.cs:line 537
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.TryUseInteraction(IEntity user, IEnti
ty used) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\Click\Interacti
onSystem.cs:line 507
   at Content.Server.GameObjects.Components.GUI.HandsComponent.ActivateItem() in D:\ProgrammingProjects\spac
e-station-14\Content.Server\GameObjects\Components\GUI\HandsComponent.cs:line 557
   at Content.Server.GameObjects.EntitySystems.HandsSystem.HandleActivateItem(ICommonSession session) in D:\
ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\HandsSystem.cs:line 142
   at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.Enabled(ICommonSession session) in D:
\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 46
   at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.HandleCmdMessage(ICommonSession sessi
on, InputCmdMessage message) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Input\Bi
nding\InputCmdHandler.cs:line 65
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventA
rgs eventArgs) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySyst
ems\InputSystem.cs:line 62
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in D:\Progra
mmingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in D:\
ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 150
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in D
:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 284
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in D:\Programm
ingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 200
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__24_1(Object sender, Object systemMsg) in D:\Pro
grammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 61
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) i
n D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager
.cs:line 159
   at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in D:\ProgrammingProjects\space-station-
14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 54
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in D:\Programmin
gProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 83
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in D:\Prog
rammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 956
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\ProgrammingProjects\space-station
-14\RobustToolbox\Robust.Server\BaseServer.cs:line 559
   at Robust.Server.BaseServer.<MainLoop>b__44_1(Object sender, FrameEventArgs args) in D:\ProgrammingProjec
ts\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 403
   at Robust.Shared.Timing.GameLoop.Run() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Sh
ared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Se
rver\BaseServer.cs:line 409
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\ProgrammingProjects
\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 83
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in D:\ProgrammingProjects\space-station-14\Ro
bustToolbox\Robust.Server\Program.cs:line 50
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callb
ack, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Robust.Shared.Asynchronous.RobustTaskScheduler.Execute(Object o) in D:\ProgrammingProjects\space-stati
on-14\RobustToolbox\Robust.Shared\Asynchronous\RobustTaskScheduler.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callb
ack, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by SweptWasTaken** [comment]
> 
> 
> Get an exception (might've already existed) on server-side for the sprite:
> 
> [ERRO] go.comp.sprite: Layer with index '2' does not exist, cannot set set! Trace:
> at System.Environment.get_StackTrace()
> at Robust.Server.GameObjects.SpriteComponent.LayerSetState(Int32 layer, String stateId) in D:\Programming
> Projects\space-station-14\RobustToolbox\Robust.Server\GameObjects\Components\Renderable\SpriteComponent.cs:l
> ine 274
> at Content.Server.GameObjects.Components.Interactable.ExpendableLightComponent.UpdateSpriteAndSounds(Bool
> ean on) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\Interactable\Expend
> ableLightComponent.cs:line 117
> at Content.Server.GameObjects.Components.Interactable.ExpendableLightComponent.TryActivate() in D:\Progra
> mmingProjects\space-station-14\Content.Server\GameObjects\Components\Interactable\ExpendableLightComponent.c
> s:line 68
> at Content.Server.GameObjects.Components.Interactable.ExpendableLightComponent.Content.Shared.Interfaces.
> GameObjects.Components.IUse.UseEntity(UseEntityEventArgs eventArgs) in D:\ProgrammingProjects\space-station-
> 14\Content.Server\GameObjects\Components\Interactable\ExpendableLightComponent.cs:line 36
> at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.UseInteraction(IEntity user, IEntity
> used) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionS
> ystem.cs:line 537
> at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.TryUseInteraction(IEntity user, IEnti
> ty used) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\Click\Interacti
> onSystem.cs:line 507
> at Content.Server.GameObjects.Components.GUI.HandsComponent.ActivateItem() in D:\ProgrammingProjects\spac
> e-station-14\Content.Server\GameObjects\Components\GUI\HandsComponent.cs:line 557
> at Content.Server.GameObjects.EntitySystems.HandsSystem.HandleActivateItem(ICommonSession session) in D:
> ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\HandsSystem.cs:line 142
> at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.Enabled(ICommonSession session) in D:
> \ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 46
> at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.HandleCmdMessage(ICommonSession sessi
> on, InputCmdMessage message) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Input\Bi
> nding\InputCmdHandler.cs:line 65
> at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventA
> rgs eventArgs) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySyst
> ems\InputSystem.cs:line 62
> at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in D:\Progra
> mmingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 23
> at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.b__0(Object ev) in D:
> ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 150
> at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in D
> :\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 284
> at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in D:\Programm
> ingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 200
> at Robust.Shared.GameObjects.EntityManager.b__24_1(Object sender, Object systemMsg) in D:\Pro
> grammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 61
> at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) i
> n D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager
> .cs:line 159
> at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in D:\ProgrammingProjects\space-station-
> 14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 54
> at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in D:\Programmin
> gProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 83
> at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in D:\Prog
> rammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 956
> at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\ProgrammingProjects\space-station
> -14\RobustToolbox\Robust.Server\BaseServer.cs:line 559
> at Robust.Server.BaseServer.b__44_1(Object sender, FrameEventArgs args) in D:\ProgrammingProjec
> ts\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 403
> at Robust.Shared.Timing.GameLoop.Run() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Sh
> ared\Timing\GameLoop.cs:line 192
> at Robust.Server.BaseServer.MainLoop() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Se
> rver\BaseServer.cs:line 409
> at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\ProgrammingProjects
> \space-station-14\RobustToolbox\Robust.Server\Program.cs:line 83
> at Robust.Server.Program.<>c__DisplayClass2_0.b__0() in D:\ProgrammingProjects\space-station-14\Ro
> bustToolbox\Robust.Server\Program.cs:line 50
> at System.Threading.Tasks.Task.InnerInvoke()
> at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callb
> ack, Object state)
> at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> at System.Threading.Tasks.Task.ExecuteEntry()
> at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
> at Robust.Shared.Asynchronous.RobustTaskScheduler.Execute(Object o) in D:\ProgrammingProjects\space-stati
> on-14\RobustToolbox\Robust.Shared\Asynchronous\RobustTaskScheduler.cs:line 34
> at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callb
> ack, Object state)
> at System.Threading.ThreadHelper.ThreadStart(Object obj)

I can't say I actually see anything that could cause this issue, just pored over everything making sure it was right. Everything works in-game fine.

**Comment by metalgearsloth** [comment]
Does the torch have 3 layers?

```
sprite.LayerSetVisible(1, true);
sprite.LayerSetState(2, IconStateLit);
sprite.LayerSetShader(2, "unshaded");
```

TBH a bunch of this code should be on client anyway rather than setting it directly on the server.

**Review by PaulRitter — APPROVED** [review]

**Comment by SweptWasTaken** [comment]
Fixed the errors, edited ExpendableLightComponent to make it not always expect 3 layers. 

Builds are still failing, someone just fix this shit for me

**Comment by metalgearsloth** [comment]
swept you committed robust again AHHHHHHHHHHHH

**Comment by SweptWasTaken** [comment]
> 
> 
> swept you committed robust again AHHHHHHHHHHHH

I dunno how this keeps happening

**Comment by metalgearsloth** [comment]
If you fix robust commit theoretically build fixes (you can probably just commit latest version given it's at that anyway).

**Review by PaulRitter — APPROVED** [review]

**Pull request merged**
