### PR TITLE
Changing the side sprites of tactical vests

### PR DESCRIPTION
**Pull request by Jackal298**
## About the PR

I changed the side sprites of tactical vests in order to fix the problem of strange looking rigs and bandoliers when worn with tactical vests.
In size they are now similar to the detective vest and kevlar, but on the side sprites I made more highlighted details of the pouches on the vests
**Media**

vestup
vestup 2
vestup3

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Changed the side sprites of tactical vests to fix weird looking sprites when wearing a rig and bandolier

### CODE REVIEW

**Comment by Jackal298** [comment]
For some reason, I got an error, I didn’t know how to run the test again, so I closed it and then opened it again, now it’s gone

**Comment by 778b** [comment]
> For some reason, I got an error, I didn’t know how to run the test again, so I closed it and then opened it again, now it’s gone, is this normal?

yep

**Comment by keronshb** [comment]
Can you take some screenshots while wearing a jumpsuit, preferably something bright?

**Comment by Jackal298** [comment]
> Can you take some screenshots while wearing a jumpsuit, preferably something bright?

I did, what do you think?

**Comment by keronshb** [comment]
> > Can you take some screenshots while wearing a jumpsuit, preferably something bright?
> 
> I did, what do you think?

These two pixels should stay covered up by the vest. Otherwise I think it's fine.

image

**Comment by Jackal298** [comment]
> > > Can you take some screenshots while wearing a jumpsuit, preferably something bright?
> > 
> > 
> > I did, what do you think?
> 
> These two pixels should stay covered up by the vest. Otherwise I think it's fine.
> 
> image

I understand you, I'll finish it

**Comment by Jackal298** [comment]
> > > Can you take some screenshots while wearing a jumpsuit, preferably something bright?
> > 
> > 
> > I did, what do you think?
> 
> These two pixels should stay covered up by the vest. Otherwise I think it's fine.
> 
> image

I added two pixels, now this Pro will be approved?

**Pull request merged**
