### PR TITLE
Allow gunpowder to be recycled from bullet cartridges

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## Why / Balance
title

pipebombs are almost never used due to the fact that gunpowder is chemistry locked
this makes pipebombs possible to obtain as a non-chemist, as you can recycle casings after a gun fight to get gunpowder, while still being hard to mass-produce for a non-chemist

around 1 piece of gunpowder for every 2 bullet cartridges (material reclaimer)
around 1 piece of gunpowder for every 5 bullet cartridges (recycler)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- tweak: Bullet casings can now be recycled for gunpowder.

### CODE REVIEW

**Comment by JIPDawg** [comment]
I've also thought it weird the you can't get brass anywhere. Not sure if this was some balance thing but what about also adding brass to recycling/reclaiming bullet casings as well?

**Comment by baddiePRO** [comment]
> I've also thought it weird the you can't get brass anywhere. Not sure if this was some balance thing but what about also adding brass to recycling/reclaiming bullet casings as well?

if you did this, would you change bullet recipes to be brass as well?

**Comment by JIPDawg** [comment]
Thats...a good point. I just want to make a brass shittle ok.

**Comment by IProduceWidgets** [comment]
At some point someone needs to get around to changing the improvised shotgun she'll recipe to use gunpowder instead of matchheads, and maybe make match heads a source of gunpowder.

**Comment by Dutch-VanDerLinde** [comment]
> At some point someone needs to get around to changing the improvised shotgun shell recipe to use gunpowder instead of matchheads, and maybe make match heads a source of gunpowder.

yes

**Comment by metalgearsloth** [comment]
Being able to shoot a bullet and then recycle it seems goofy?

**Comment by Dutch-VanDerLinde** [comment]
> Being able to shoot a bullet and then recycle it seems goofy?

i guess so, but it'd be really hard(legally) to get your hands on some non-spent bullet cartridges as a job like a passenger
maybe match sticks grind into gunpowder instead of casings

**Comment by deltanedas** [comment]
why would spent casings have gunpowder

it would only really make sense for recycling fresh bullets

**Comment by PotatOverlord** [comment]
The problem with matchstick gunpowder is that it's just phosphorus on the tips (not even that, you can only strike the matches on a matchbox so they're safety matches and the phosphorus is on the box), unless NT is buying some epic matches. You could make it improvised gunpowder, but then that implies the existence of obtainable normal gunpowder so you'd have to make that a whole system and pretty soon you've started making a massive bullet/gun overhaul, which I assume is out of scope for the pr. 

I realise that i might've rambled for a bit, but this solution will work until someone with enough firearm knowledge can make/inform on the making of a deeper gun system imo. Better a quick fix than nothing at all.

**Comment by metalgearsloth** [comment]
> Better a quick fix than nothing at all.

What do you mean a quick fix? It's explicitly adding new mechanics but currently it's just powercrept when you can make free bombs after shooting at people.

**Comment by PotatOverlord** [comment]
I mean a quick fix in place of a whole bullet manufacturing system, but also a way for non chems to make gunpowder. Reading it back, I'm not really sure what I meant myself though... sorry for the weird tangent.

**Comment by deltanedas** [comment]
you should have to recycler unspent bullets not brass casings

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and the agreement was to close this PR. The main points brought up were:
- Empty bullets should not contain any gunpowder.
- This would allow you to mass-produce gunpowder from steel using the sec fab or an emagged lathe.
Thank you for your contribution.

**Pull request closed without merging**
