### PR TITLE
You can now beat people up with a microwave

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Requires #12523 

The idea for this came to me in a dream, and it was so funny to me I decided to try and make it reality. Enjoy beating in syndicate skulls with yet another improvised weapon.

**Changelog**

:cl:
- add: You can now beat people up with a microwave.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
> Why

Because it's funny

**Comment by moonheart08** [comment]
Can this be made to not fit in bags and require two hands somehow?

**Comment by GoodWheatley** [comment]
> Can this be made to not fit in bags and require two hands somehow?

Microwave wielding....

**Comment by EmoGarbage404** [comment]
> > Why
> 
> Because it's funny

The idea that someone with a wrench can steal the chef's main machine (which isnt trivial to replace) is really wack. Not a fan.

**Comment by GoodWheatley** [comment]
> > > Why
> > 
> > 
> > Because it's funny
> 
> The idea that someone with a wrench can steal the chef's main machine (which isnt trivial to replace) is really wack. Not a fan.

Yeah, I'll change the item size so it can't fit in bags

**Comment by EmoGarbage404** [comment]
Its not being able to bag it its being able to just pick up a difficult to produce machine. If you steal it early in the round, it could be close to 15-20 minutes before science can provide a replacement.

**Comment by EmoGarbage404** [comment]
Also, a 30 damage weapon is absurd.

**Comment by GoodWheatley** [comment]
> Also, a 30 damage weapon is absurd.

Counterbalanced it by giving it 0.5 attack speed, so you attack half as fast with it.

**Comment by ZeroDayDaemon** [comment]
> > Also, a 30 damage weapon is absurd.
> 
> Counterbalanced it by giving it 0.5 attack speed, so you attack half as fast with it. Averages out to 15 DPS if you can consistently land the hits.

That's 1 point more than the baseball bat, personally don't care about the whole chef thing, microwaves are everywhere, and if they aren't Trivial to make, that's another issue, not a this PR issue.

Do think it should require two hands and be unable to be placed in a bag.

**Comment by EmoGarbage404** [comment]
Baseball bats actually do 14 damage, not 29.

Also, being able to pick up the machine that facilitates 100% of chef gameplay is as absurd as being able to pick up a chem dispenser or cargo shuttle and walk off with it.

**Comment by ZeroDayDaemon** [comment]
> Baseball bats actually do 14 damage, not 29.
> 
> Also, being able to pick up the machine that facilitates 100% of chef gameplay is as absurd as being able to pick up a chem dispenser or cargo shuttle and walk off with it.

What is half of 30

**Comment by ZeroDayDaemon** [comment]
> Also, being able to pick up the machine that facilitates 100% of chef gameplay is as absurd as being able to pick up a chem dispenser or cargo shuttle and walk off with it.

I wouldn't say it's unreasonable to be able to pick it up with two hands provided it's not wrenched, a microwave is much smaller than a chem dispenser or a cargo shuttle, so enough of your strawman arguments

**Comment by ZeroDayDaemon** [comment]
Anyway something else that would probably be necessary for balance would be being slowed down when wielding it. Probably by about 30 or 40 percent

**Comment by EmoGarbage404** [comment]
Its not a strawman argument. Im not arguing that its unreasonable to pick up a microwave. What i am saying is that being able to pick up vital department equipment for the sake of "funny meme weapon" isnt good for the game.

**Comment by ZeroDayDaemon** [comment]
> Its not a strawman argument. Im not arguing that its unreasonable to pick up a microwave. What i am saying is that being able to pick up vital department equipment for the sake of "funny meme weapon" isnt good for the game.

Aren't there like 10 of these on every map in break rooms and maintenance? I see them a lot despite never needing to use them when playing. What stops someone from just wrenching it and dragging it off if it's so vital?

A requirement to use two hands,
Maybe a nerf on the damage,
And a movement speed reduction while holding it

Seem like perfectly valid resolutions to any balance issues.


The last concern, you worrying about vital equipment, microwaves are literally everywhere. The proposed movement speed reduction while holding it would make it harder to outright steal.
The entire game ss14 is based on, space station 13, was literally built upon the idea of "haha funny put it in the game" and the fact that microwaves are the sole vital thing in the kitchen should be addressed, instead of ignored. And not by blocking other PRs, but by actually fixing the core issue.

**Comment by OldDanceJacket** [comment]
Also...

>What i am saying is that being able to pick up vital department equipment for the sake of "funny meme weapon" isnt good for the game.

It's the spirit of the game actually. At it's very core.
Also doesn't this allow someone to pick up and move microwaves around now?

**Comment by ZeroDayDaemon** [comment]
All that being said, I dont thing this PR in its current state should be merged

**Comment by moonheart08** [comment]
This is not being merged unless picking up a microwave feels like picking up a microwave. Both hands occupied, doesn't fit in containers.

**Comment by moonheart08** [comment]
> Also...
> 
> > What i am saying is that being able to pick up vital department equipment for the sake of "funny meme weapon" isnt good for the game.
> 
> It's the spirit of the game actually. At its very core. Also doesn't this allow someone to pick up and move microwaves around now without awkwardly dragging it along?

no.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
> This is not being merged unless picking up a microwave feels like picking up a microwave. Both hands occupied, doesn't fit in containers.

if I need to record myself carrying a microwave to demonstrate what it should feel like I will.

**Comment by PJB3005** [comment]
> Also doesn't this allow someone to pick up and move microwaves around now without awkwardly dragging it along?

Nothing wrong with having a general-purpose way to lift small machines. Other things like cell chargers could use this too.

But this PR isn't that, it's clearly a joke. what happens to the microwave's power connection? Open UIs? What if it's actively cooking?

Also whacking people with a microwave does seem somewhat intrinsically funny, but only from a pure ridiculousness aspect. You could imagine this with any sort of countertop appliance and it'd be funny for the same reason.

**Comment by moonheart08** [comment]
Untested webedit, closing.

**Pull request closed without merging**
