### PR TITLE
Three more plushies

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR 
Added Ratvar, Space lizzer, and Rouny

**Screenshots**
unknown

**Changelog**

:cl:
- add: Ratvar, Rouny, and Space Lizard have joined the plushie gang, find them on your closest plushie crate or toy spawners!

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
license.txt for muffledweh, also snake_case pls. Non-centered sprite for rouny means it's gonna need custom bounds or it needs centering.

**Comment by DogZeroX** [comment]
Where do you want the 🐍?

**Comment by metalgearsloth** [comment]
> Where do you want the 🐍?

filename

**Comment by DogZeroX** [comment]
muffled_weh?

**Comment by metalgearsloth** [comment]
yiss

**Comment by DogZeroX** [comment]
image
Tell that to the rest of the files :> Changing it

**Comment by DogZeroX** [comment]
Counter-ratio

**Pull request merged**
