### PR TITLE
Remove RCD from tech and make it a crate

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

RCD is roundstart which means making it t2 tech feels like a gut punch.
This moves it and the ammo to a crate so cargo actually has something nifty that engies will want.

Removes the lathe recipes because they're obsolete in the face of this.

## Why / Balance

Roundstart tools should have roundstart resupplying.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the RCD and RCD ammo crates to cargo.

### CODE REVIEW

**Comment by keronshb** [comment]
I don't think we should remove it from printing.

In #15708 I have it so that printed RCDs should come with basic functionality. Round start RCDs should be full functionality. And Cargo RCDs should be an upgraded RCD with a CE lock called an Industrial RCD.

**Review by keronshb — APPROVED** [review]

**Comment by AjexRose** [comment]
Could RCD ammo be put into the engieVend so that engineers could buy restocks to get more ammo without needing to buy a crate and discarding the RCDs inside?

**Comment by EmoGarbage404** [comment]
> Could RCD ammo be put into the engieVend so that engineers could buy restocks to get more ammo without needing to buy a crate and discarding the RCDs inside?

The PR has two crates: one containing an RCD with 5 charges, and the other containing 3 RCD ammo, each granting 5 additional charges.

Just order the cheaper ammo crate instead of the full RCD crate

**Comment by JoeHammad1844** [comment]
why not just T1?

**Comment by EmoGarbage404** [comment]
why should you have to research something that already exists?

**Comment by JoeHammad1844** [comment]
> why should you have to research something that already exists?

MFW thats half the tech tree

**Comment by EmoGarbage404** [comment]
> MFW thats half the tech tree

#21462

**Comment by Golinth** [comment]
Didn't get to comment before this got merged, but I dont like that yet another engineering item is locked behind cargo having to order it. Engineering already heavily relies on cargo for materials, gasses, and repairs (AME and such), now they need to do so even more for RCD ammo. IMO the ammo should be a basic craftable on the autolathe, even if it needs to be more expensive than it is now.

**Pull request merged**
