### PR TITLE
Locker Fill Change

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes the items found in most lockers around the station.

## Why / Balance

It hopefully reduces the amount of bloat in certain lockers and fills others that are relatively empty with job-appropriate equipment.

## Technical details
The lockers that were changed and how are:
- Atmos: Removed oxy kit, added burn kit, added insuls, added atmosian plushie (small chance)
- Botanist: Removed seeds, added spade, added minihoe, added robust harvest (small chance), removed one of each clothing
- Captain: Removed captain's hat
- Chemistry: Removed syringe box, removed one bottle box, added latex gloves, added medical headset, added sterile mask. added chembag, added extra beaker box (small chance), added hand labeler (small chance)
- CMO: Removed virology circuit boards, removed biomass
- Engineer: Added electrical toolbox (small chance), added mechanical toolbox (small chance), added chips (small chance), added beer (small chance), added space lizard plushie (small chance)
- HOP: Removed black shoes, added HOP winter coat
- HOS: Removed beret
- Medical Doctor: Removed nitrous oxide tank
- Medicine Locker: Removed pill box, removed two epinephrine bottles, added gauze
- Paramedic: Added sterile gloves, added medical headset, added sterile mask, added first aid kit (small chance)
- QM: Removed brown shoes, removed quartermaster's hat
- RD: Removed robotech encryption keys, added purple gloves, added toolbelt
- Salvage: Added GPS, added handheld radio, added ore bag (small chance), added three flares (small chance each)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed most lockers by removing or adding appropriate items

### CODE REVIEW

**Comment by VektorZ1** [comment]
The change in chemistry sounds weird, what's the reason to remove their syringes?

**Comment by Alekshhh** [comment]
I don't believe they have much use when it comes to chemistry

**Comment by LankLTE** [comment]
I think the Chem syringes, CMO's biomass, medicine lockers' epinephrine and caps' hat should stay (unless they spawn with one now idk)

**Comment by Emisse** [comment]
chem needs syringes

**Comment by Emisse** [comment]
you probably should atomize this pr as it will make it 10x easier to review

**Comment by Alekshhh** [comment]
sure

**Pull request closed without merging**
