### PR TITLE
Made glass more opaque

### PR DESCRIPTION
**Pull request by iztokbajcar**
## About the PR

I made glass.png more opaque and modified rglass.png in a similar way so that the two wouldn't visually clash because of it. 

## Why / Balance

Hopefully solving issue #18482. This PR makes glass tiles more noticeable.

## Media

Glass before:
Screenshot_20240414_115321

Glass after:
Screenshot_20240414_115648

Side-by-side comparison:
Screenshot_20240414_120026

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None.

**Changelog**

:cl:
- tweak: Glass textures are now less transparent.

### CODE REVIEW

**Comment by UbaserB** [comment]
im all in for making the normal glass floors more opaque, but i feel it should be still a bit more transparent than the reinforced.

**Comment by iztokbajcar** [comment]
Thanks for the feedback, I'll take it down a notch.

**Comment by iztokbajcar** [comment]
Regular glass is now a bit more transparent, the result can be seen in the screenshot:

Screenshot_20240415_205136

**Comment by potato1234x** [comment]
no more invisible shittle :despair:

**Comment by notquitehadouken** [comment]
no more scenic view when i replace the floor with glass

**Pull request merged**
