### PR TITLE
Remove Clearly Nuclear on Author's Request

### PR DESCRIPTION
**Pull request by Piras314**
This reverts commit 806c0d162fffa41b47596f1a4d8c03e72c2ff7a9.

## About the PR

Reverted PR #25765 on request of the author who would no longer like their song to be used in this repo.

## Why / Balance

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- remove: Removed the nuke song "Clearly Nuclear" on request of the author.

### CODE REVIEW

**Comment by he1acdvv** [comment]
I am the author.

**Comment by ScarKy0** [comment]
High priority due to it being the request of the author.
Shame though I really liked hearing this track in nukie rounds

**Review by TheShuEd — APPROVED** [review]

**Comment by superjj18** [comment]
Kinda cringe but ok

**Comment by NoElkaTheGod** [comment]
Clearly Nuclear have fallen. Billions must Sound Station 14.

**Comment by he1acdvv** [comment]
> Clearly Nuclear have fallen. Billions must Sound Station 14.

still on goobstation btw.....

**Comment by superjj18** [comment]
I'm gonna attempt to express my disappointment in the least toxic way possible.

I don't know much about the author or their relationship to wizden and its' various forks, but this just seems like removing content due to personal drama.  If they have issues with wizden I get that, wizden can be major dorks at times, but the author ain't hurting wizden here, just wizden players.  Wizden server pops aren't gonna dip because a song gets removed, it's just marginally less content for players.

It just seems scummy to add something only to remove it later for personal reasons(especially related to petty drama).  If a maintainer left the project would they be able to go through code and rip out all of their code from the project?

I don't think there's anything on wizden's side that can or should be done other than go with the author's wishes, I just strongly question the author's motives and reasonings. Maybe there truly is some drama worth being this petty over, but in my experience with community drama it very rarely ever is.

**Comment by he1acdvv** [comment]
> I'm gonna attempt to express my disappointment in the least toxic way possible.
> 
> I don't know much about the author or their relationship to wizden and its' various forks, but this just seems like removing content due to personal drama. If they have issues with wizden I get that, wizden can be major dorks at times, but the author ain't hurting wizden here, just wizden players. Wizden server pops aren't gonna dip because a song gets removed, it's just marginally less content for players.
> 
> It just seems scummy to add something only to remove it later for personal reasons(especially related to petty drama). If a maintainer left the project would they be able to go through code and rip out all of their code from the project?
> 
> I don't think there's anything on wizden's side that can or should be done other than go with the author's wishes, I just strongly question the author's motives and reasonings. Maybe there truly is some drama worth being this petty over, but in my experience with community drama it very rarely ever is.

I respect your perspective on this matter. If you'd like to understand the reasoning behind my decision, I welcome you to reach out to me privately for a thoughtful discussion on Discord. However, I want to be clear that my position on this is firm, based on consideration of recent developments with Wizden. Given these circumstances, I have made the deliberate choice to dissociate my artistic work from that fork, and i hope that is respected.

I will not be discussing this over GitHub.

**Pull request merged**
