### PR TITLE
Raise GasMinMoles

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
Raises `GasMinMoles`, the minimum quantity of gas in moles considered to be non-zero, from `0.00000005f` to `0.001f`.

## Why / Balance
The old number is 50 parts-per-billion (ppb), which while is detectable in some contexts IRL, basically doesn't matter in Space Station 14 and results in situations like this where a tiny trace amount of gas stays in the gas analyzer forever:

gas-analyzer-bug

This change brings the zero-threshold to `0.001f`, which is already 10× less than `0.01f`, the YAML-hardcoded minimum threshold for most reactions to take place.

## Technical details
`GasMinMoles` is used by the atmosphere system in 3 places:

- LINDA to decide when to stop moving gases
- By the gas analyzer to decide when a gas mixture is effectively zero
- By `GasMixture` to determine when to zero out that value in gases removed

This change would (marginally) speed up LINDA by ignoring gases that don't matter and also spam the gas analyzer less with gases that basically don't matter.

I double checked that removing small amounts of gas doesn't affect typical tritium setups after this change:

image

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Partmedia** [comment]
Investigating (continued) test failure.

**Comment by Partmedia** [comment]
> This will make it impossible to work with high temperature gases as even 0.001 mols can be thousands of KPA at temperature in the millions. If the concerns you are trying to "fix" are purely UI related, change the UI instead of making gases magically disappear.

I don't think this is a problem. As you know, temperature a measurement of the average velocity of gas molecules. If you have very few gas molecules to begin with, while they may be moving very fast collectively they have very little energy. Standing in a room with 0.000001 moles of gas at 1 million K shouldn't kill you (but will in the current code) because there's only 1 Joule of energy.

**Comment by deltanedas** [comment]
> If the concerns you are trying to "fix" are purely UI related, change the UI instead of making gases magically disappear.

this is not a ui issue it literally ignores temperature increases from heater
i dont know what you are referring to with gases disappearing

**Comment by Ilya246** [comment]
> This will make it impossible to work with high temperature gases as even 0.001 mols can be thousands of KPA at temperature in the millions. If the concerns you are trying to "fix" are purely UI related, change the UI instead of making gases magically disappear.

first, gases of temperatures above 140kK are only reachable using specialised setups (i've managed to reach 1.2GK at most so far, though), and second, you'd generally only obtain 0.001mol or less of gas at those temperatures if you're feeding said overheated gas into the TEG a little amount at a time
otherwise, i would support using separate GasMinMoles values for pipe networks and tile atmospheres, so pipes can still have tiny amounts of gas while tiles will be considered empty earlier

**Comment by deltanedas** [comment]
this should just be ui change for gas analyzer

**Comment by Partmedia** [comment]
> this should just be ui change for gas analyzer

gas analyzer uses this exact constant pro

**Comment by deltanedas** [comment]
then why not merge if its just a ui thing

**Pull request closed without merging**
