### PR TITLE
tweak(CargoShuttle): Add a passive vent to cockpit, reposition existing one. Replace useless generator with usable one.

### LINKED ISSUE #30063: lost cargo technician can die of co2
Screenshot_20240715_112329

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Added a passive vent to cockpit, repositioned existing one.
Replaced the unusable generator with a usable one.

## Why / Balance

Resolves #30063 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**After**
image

By IProduceWidgets 

image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
> passive vent
should probably be an air vent

Also looks like you unlinked the conveyors and blast doors, but that could just be something funky with serialization. Best to check though.

**Comment by Brandon-Huu** [comment]
> > passive vent
> 
> should probably be an air vent, and a waste network instead.
> 
> Also looks like you unlinked the conveyors and blast doors, but that could just be something funky with serialization. Best to check though.

I didn't touch any of that.
The linking diff shows up in a lot of the map change PRs, never seen it cause any issues

**Comment by Brandon-Huu** [comment]
> should probably be an air vent, and a waste network instead.

A waste network? Where would the waste go?
Only recycling nitrogen and oxygen?

**Comment by IProduceWidgets** [comment]
> > should probably be an air vent, and a waste network instead.
> 
> A waste network? Where would the waste go? Only recycling nitrogen and oxygen?

The waste network takes gases out via the scrubbers, and then usually expels then through a passive vent in space.
Finding a good place the passive vent is usually the hardest part. They will function under some objects including thrusters and diagonal windows, but that's more a hacky workaround than anything. Id rather that while we wait on wall-integrated parts for this to be added than have no waste loop.

**Comment by Brandon-Huu** [comment]
> > > should probably be an air vent, and a waste network instead.
> > 
> > 
> > A waste network? Where would the waste go? Only recycling nitrogen and oxygen?
> 
> The waste network takes gases out via the scrubbers, and then usually expels them through a passive vent in space. Finding a good place the passive vent is usually the hardest part. They will function under some objects including thrusters and diagonal windows, but that's more a hacky workaround than anything. Id rather that while we wait on wall-integrated parts for this to be added than have no waste loop.
> 
> Also, you will need an air alarm for the air vent since the recent atmos changes.

Recycling oxygen and nitrogen only?

**Comment by IProduceWidgets** [comment]
> > > > should probably be an air vent, and a waste network instead.
> > > 
> > > 
> > > A waste network? Where would the waste go? Only recycling nitrogen and oxygen?
> > 
> > 
> > The waste network takes gases out via the scrubbers, and then usually expels them through a passive vent in space. Finding a good place the passive vent is usually the hardest part. They will function under some objects including thrusters and diagonal windows, but that's more a hacky workaround than anything. Id rather that while we wait on wall-integrated parts for this to be added than have no waste loop.
> > Also, you will need an air alarm for the air vent since the recent atmos changes.
> 
> Recycling oxygen and nitrogen only?

Normally scrubbers only scrub out toxic gasses and not nitrogen/oxygen (this can be changed in round at the air alarm, but I don't think we have any you can spawn with alternate settings). I wouldn't try to squeeze a recycling system with filters and whatnot into the cargo shuttle.

it w

**Comment by Brandon-Huu** [comment]
https://github.com/space-wizards/space-station-14/pull/30310

**Comment by deathride58** [comment]
u might wanna reread ur own pr title (unfortunate typo)

**Pull request closed without merging**
