### PR TITLE
Add Holy damage

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR adds the Holy damage type, a new damage type meant to be dealt to spirits and unholy creatures.

The main interaction for this is related to Revenant, making the Chaplain scarier for the spirit.

The PR introduces this the following way:
- The Metaphysical damage group has been added, currently only holding Holy damage.
- Revenants is the main and only base-game mob that can take Holy damage
  - Some admin-only mobs have also been given the ability to take Metaphysical damage.
- Holy damage can be dealt via attacking with the Bible, or splashing with Holy Water
- Holy damage can currently not be healed in any way (but normal crew can't take holy damage anyways).

The Gohei item also deals a negligible amount of Holy damage as flavor.

## Why / Balance

The addition of Holy damage adds a bit more importance to the Chaplain when it comes to dealing with supernatural threats, which are part of the SS14 fiction in the form of Revenants and admeme mobs like Hellspawns or Corrupted Corgis. This is a fairly barebones implementation and imo should be just a part of increasing Chaplain relevance to the station.

The damage dealt is the following, however note that Revenants take 2x damage:
- Bible: 25 Holy (+1 Blunt)
- Holy Water: 0.5 Holy / unit (up to 20u can be splashed)

Being able to deal 50 damage to the Revenant is a *very* strong ability, limited by the bible being a very limited item. Holy water becomes a decent alternative to deal with Revenants for regular crew if the Chaplain finds the time to bless water and hand it out, letting crew deal 20 damage per splash. Note that Revenants still take damage from other sources as normal, so while 20 damage is higher than what's normally available, it's not much higher than a baseball bat or spear.

An additional nice thing about holy water is that it's a high-damage item that is not harmful to regular crew, making it a very safe option for Sec/Command to provide should a Revenant become a problem.

The Gohei dealing Holy damage is just as flavor for what is meant to be a spirit-warding tool. In effect it deals as much damage to a Revenant as hitting it with a crowbar.

## Technical details

A new damage group, damage type, and a new damage modifier set. Bible got a melee weapon attack, matching normal books (1 blunt) plus the 25 Holy damage. 

## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Holy damage to the Chaplain's bible, holy water and the gohei, which can be exclusively dealt to spirits.

### CODE REVIEW

**Comment by muburu** [comment]
maybe revenants could deal unholy damage or something instead of cold when stealing souls, and in order to be revived the bible has to be used on the body or holy water has to be splashed on them

**Comment by bruhmogus** [comment]
skeletons should also be able to take this since they are very supernatural
zombies probably shouldn't since it's a virus and not reanimation

**Comment by UbaserB** [comment]
Does the Cerberus from Necronomicon get hurt from holy damage?

**Comment by SlamBamActionman** [comment]
> Does the Cerberus from Necronomicon get hurt from holy damage?

Yes, as it's a child to MobCorgiNarsi; 
`damageContainer: BiologicalSpiritual`
`damageModifierSet: Infernal`

**Comment by slarticodefast** [comment]
Code looks good and in-game test went well.
I tried doing the same with holy water and the revenant myself, but wasn't able to get the balance right.

Test results for the revenant:
Hit with bible: 51 damage
Splash with 20u of holy water: 20 damage
The revenant dies at 150 total damage.

I think 3 hits with a bible is reasonable considering there is usually only one on the station. Having to hide from the chaplain encourages the rev to move around more instead of simply staying in medbay all the time, while at the same time giving the chaplain some actual gameplay. So a good addition in that regard.

Holy water can be easily mass-produced and handed out to the crew as a weapon, but the damage is low enough to not be overpowered imo.

Since this PR has rather huge implications on combat and possible future features like cultists I will open a maintainer discussion thread to get a few more opinions.

**Comment by thebadman4662** [comment]
Does holy water work as incendiaries/acids do - on touch - in smoke bombs? Asking for a friend. :trollface:

**Comment by SlamBamActionman** [comment]
> Does holy water work as incendiaries/acids do - on touch - in smoke bombs? Asking for a friend. :trollface:

I do not recall the smoke code fully; it's possible if it matches other touch effects, though good luck timing it to a Rev appearing. ;)

**Comment by Sadie-silly** [comment]
> maybe revenants could deal unholy damage or something instead of cold when stealing souls, and in order to be revived the bible has to be used on the body or holy water has to be splashed on them

good concept, but what happens when there is no chaplain?

**Comment by MissKay1994** [comment]
I look forward to this. t finally gives chaplains being able to deal with revenants

**Comment by thebadman4662** [comment]
> > maybe revenants could deal unholy damage or something instead of cold when stealing souls, and in order to be revived the bible has to be used on the body or holy water has to be splashed on them
> 
> good concept, but what happens when there is no chaplain?

Just clone them :trollface:

**Comment by Errant-4** [comment]
> > maybe revenants could deal unholy damage or something instead of cold when stealing souls, and in order to be revived the bible has to be used on the body or holy water has to be splashed on them
> 
> good concept, but what happens when there is no chaplain?

The same thing will happen that happened every round before merge. I don't think we have anything yet that would be unbalanced due to missing chaplain

**Comment by BlitzTheSquishy** [comment]
This might mess some stuff up with delta-v (not your problem what so ever) cause we already have a form of this called immaterial damage. Interesting to see upstream wanting to add something similar.

**Comment by dvir001** [comment]
On Frontier were just going to make sure goblins take 15%+ more holy damage.

**Comment by Sadie-silly** [comment]
> > > maybe revenants could deal unholy damage or something instead of cold when stealing souls, and in order to be revived the bible has to be used on the body or holy water has to be splashed on them
> > 
> > 
> > good concept, but what happens when there is no chaplain?
> 
> The same thing will happen that happened every round before merge. I don't think we have anything yet that would be unbalanced due to missing chaplain

I was more worried about the suggestion of the comment i replied to, as if something like this is implemented, and the chaplain is the only one capable of healing unholy damage, not having a chaplain would make the revenant round remove every person it kills.

**Comment by FinnishPaladin** [comment]
> I was more worried about the suggestion of the comment i replied to, as if something like this is implemented, and the chaplain is the only one capable of healing unholy damage, not having a chaplain would make the revenant round remove every person it kills.

Just make the holymelons contain holy water, unless they already do that.

**Review by Errant-4 — COMMENTED** [review]
This seems reasonable, and if it conflicts with downstreams who already implemented Holy damage, it should be easy to resolve or opt out of this commit.

But I'm not sure about the name, especially if in the future this would include something like Psychic damage which is not really "Spiritual"?
I think "Metaphysical" or "Supernatural" would be more encompassing and fit better into the mostly-scifi setting

**Comment by SlamBamActionman** [comment]
PR has been updated with requested changes, as long with a new sprite for "Metaphysical".

**Pull request merged**
