### PR TITLE
Shadows decals

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
shadows decals, fake AO to simulate a height difference
for mapping

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by UbaserB** [comment]
i will probably use these

**Comment by mirrorcult** [comment]
i really dont want these, i dont want mappers to feel like they have to use them when we could just implement actual fake AO like tg in the future

**Comment by EmoGarbage404** [comment]
I really don't think we should have these. We should really just wait for the proper lighting rather than hacking it in with decals.

**Comment by TheShuEd** [comment]
the main idea was not to simulate AO from walls, but rather for moments with railings and stairs.

**Comment by TheShuEd** [comment]
But ok

**Pull request closed without merging**
