### PR TITLE
Add Winter Boots

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

SS13 had winter boots, and i LOVED them, but it was a shame 14 didn't. Hence, the solution to that problem.. i am adding winter boots! I took the sprites from /tg/ and reworked it so it fit in with our jacket sprites. It ALSO provides half as much temperature protection as the jacket, so it has functionality too. Enjoy your cold winter nights with these boots!
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image

**Changelog**

:cl: Ubaser
- add: Winter Boots are now available in the Winterdrobe.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
that sprite is MASSIVE

**Comment by UbaserB** [comment]
> that sprite is MASSIVE

they're about the same size as the /tg/ sprites, and compared to something like workboots (which realistically is about the same size as these) they are the same.

**Comment by deltanedas** [comment]
the shoes are bigger than the damn coat

**Comment by JoeHammad1844** [comment]
> > that sprite is MASSIVE
> 
> they're about the same size as the /tg/ sprites, and compared to something like workboots (which realistically is about the same size as these) they are the same.

the winter boots like two times the size of the other shoe sprites

**Comment by gusxyz** [comment]
> > that sprite is MASSIVE
> 
> they're about the same size as the /tg/ sprites, and compared to something like workboots (which realistically is about the same size as these) they are the same.

workboots are not realistically going up to my hips.

**Comment by EmoGarbage404** [comment]
i love these fat fuckin booties

**Pull request merged**
