### PR TITLE
Human plushie

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

removing racism. All species should have toys.

(also fixed the tabs to spaces in meta.json)

## Media

https://github.com/Dutch-VanDerLinde/space-station-14/assets/96445749/de7f41bc-012d-4551-943a-3cc082700df4

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added human plushie

### CODE REVIEW

**Comment by lzk228** [comment]
:trollface:

**Comment by FairlySadPanda** [comment]
but what sound should it m- oh

oh no

**Comment by UbaserB** [comment]
this is actually terrifying, DONT PUT IT IN THE PLUSHIE CRATE THIS IS A BAD IDEA

**Comment by FairlySadPanda** [comment]
More seriously for the description:

```A felt plush of Urist McHands, test dummy extraordinaire. He's screaming!```

If you wanted to make it an Isaac reference you'd want to add visible tears.

**Comment by TheShuEd** [comment]
if i want to make a reference to isaac, i have to do it with a water gun. :trollface:

**Comment by MACMAN2003** [comment]
he's so ugly i love him

**Pull request merged**
