### PR TITLE
Trash Compactor for Syndicate Janitors

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
This PR adds a version of the janitorial trash cart that can gib people when put inside as a job-specific syndicate item that janitors can buy in the uplink for 7 TC.

## Why / Balance
I saw that this was a thing on goon station and decided to implement it here as well. The 7TC are are higher than the price there cause syndies start with more TC.

## Technical details
New ``ShredderComponent`` and ``ShredderSystem`` that send a ``StartBeingShreddedEvent`` and ``DoneBeingShreddedEvent`` to any entity that gets put into a container it is on.
Bodies take that event and gib themselves.

## Media
Note: these are outdated and this is getting improved.
image

[SS14_trash.webm](https://github.com/space-wizards/space-station-14/assets/60073468/07df56ac-16ba-4717-98e5-4442d69ad098)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- add: Syndicate janitors can now buy a trash cart with built-in trash compactor in the uplink, allowing them to violently dispose of their targets in a not-so-discrete way.

### CODE REVIEW

**Comment by KingOnBudget** [comment]
This is a realy cool item but gibbing somebody this fast and this quiet just for 4 tc seems insanely strong.

**Comment by lzk228** [comment]
OP for 4 tc, maybe make that only dead bodies would be gibbed?

**Comment by Psychpsyo** [comment]
> This is a realy cool item but gibbing somebody this fast and this quiet just for 4 tc seems insanely strong.

I was thinking that though I wasn't sure about syndie item balance so I'd appreciate better price suggestions.

**Comment by GoodWheatley** [comment]
The reason why it costs four TC on goon is because on goon traitors only get 12 TC total. A equivalent price would be 6-7 TC.

**Comment by Psychpsyo** [comment]
> The reason why it costs four TC on goon is because on goon traitors only get 12 TC total. A equivalent price would be 6-7 TC.

That makes sense, changing it to 7 then.

**Comment by KingOnBudget** [comment]
> > This is a realy cool item but gibbing somebody this fast and this quiet just for 4 tc seems insanely strong.
> 
> I was thinking that though I wasn't sure about syndie item balance so I'd appreciate better price suggestions.

To be fair 4tc cost would be fine if you made the gibbing not instant and the sound bit louder. Like the corpse has to stay in there for a good 30 to 60 seconds to get gibbed(asking it to take minutes would be stupid as at that point you may use a bat and save on tc.). And maybe go as far as reducing the durability of the trash compactor so smashing it to save the body insade before it gets gibbed can be possible. As it stands it is impossible to save the body insade without jani accsess will be impossible.

**Comment by Aisu9** [comment]
no meat cube as a result of compacting someone?

**Comment by GoodWheatley** [comment]
Also it would be funny if this shook violently and  leaked blood while compacting like the biomass reclaimer does

**Comment by Psychpsyo** [comment]
Making this a draft until I implement all that.

**Comment by Hmeister-fake** [comment]
> > > This is a realy cool item but gibbing somebody this fast and this quiet just for 4 tc seems insanely strong.
> > 
> > 
> > I was thinking that though I wasn't sure about syndie item balance so I'd appreciate better price suggestions.
> 
> To be fair 4tc cost would be fine if you made the gibbing not instant and the sound bit louder. Like the corpse has to stay in there for a good 30 to 60 seconds to get gibbed(asking it to take minutes would be stupid as at that point you may use a bat and save on tc.). And maybe go as far as reducing the durability of the trash compactor so smashing it to save the body insade before it gets gibbed can be possible. As it stands it is impossible to save the body insade without jani accsess.

Personally I think 30 seconds is way way too much cause at that point you can just use a syndicate tool box, save 5 tc and not out yourself if your smart + tools. I feel like 3-10 seconds (depending on if they have any armor on) and a distinct metallic noise and then a loud squish would be good.

**Comment by Hmeister-fake** [comment]
Also question, would it hold rubbish like a normal cart?

**Comment by Psychpsyo** [comment]
> Also question, would it hold rubbish like a normal cart? (Trash for Americans*)

It works exactly like a regular cart except that bodies that go in get gibbed.

**Comment by KingOnBudget** [comment]
Can you put multiple corpses in it to gib all at once?

**Comment by Psychpsyo** [comment]
> Can you put multiple corpses in it to gib all at once?

Currently, yes.

**Comment by deltanedas** [comment]
yeah would be cooler if it had to chew for ~10 seconds then make a meat sound after

**Comment by Ilya246** [comment]
maybe just deal brute to anything inside

**Comment by UbaserB** [comment]
I dont like how all the blood spills out immediately and the cart automatically opens. I feel like there would be more opportunity to go stealth if you can keep it closed (and LOCKED since i mean there is a locking feature) until needed

**Comment by Psychpsyo** [comment]
> I dont like how all the blood spills out immediately and the cart automatically opens. I feel like there would be more opportunity to go stealth if you can keep it closed (and LOCKED since i mean there is a locking feature) until needed

I feel like it shouldn't be too easy to use it stealthily since it does just gib someone entirely.
And other people can still hear it either way so you can't really do it stealthily around them.

Also, if you could keep it closed that means if you just have a kill objective there is no reason to ever open it up again.

But I am currently making it shake for like 5 seconds while it's crunching so you might be able to drag it into a maints entrance / shove it out the airlock before it's finished. Or just shut it right after so you only get the blood puddle. (you're a jani, you have a good reason to be around the massive blood puddle)

**Comment by forgotmyotheraccount** [comment]
> I dont like how all the blood spills out immediately and the cart automatically opens. I feel like there would be more opportunity to go stealth if you can keep it closed (and LOCKED since i mean there is a locking feature) until needed

Maybe we should give the janitor some tools to clean up messes

**Comment by deltanedas** [comment]
like mops and buckets

**Comment by commash** [comment]
This only works on corpses, right? Not on alive people that are in the compacter for a moment?

**Comment by GeorgeGimme** [comment]
the organs should be inside the cart when you gib someone also it should only gib them when it gets locked so you cant just instagib players

**Comment by AJCM-git** [comment]
@Psychpsyo You coming back to this?

**Comment by Psychpsyo** [comment]
> @Psychpsyo You coming back to this?

Probably not anytime soon.

**Pull request closed without merging**
