### PR TITLE
Nukies can now purchase elite hardsuits

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Pretty simple, nukies can now purchase the elite hardsuit from their uplink for 8 TC. Also blacklisted the regular hardsuit from the nukie uplink, since they can now buy a superior version for the same price.

**Screenshots**

**Changelog**

:cl:
- add: Nukies can now buy elite versions of their hardsuits.

### CODE REVIEW

**Comment by asperger-sind** [comment]
I don't really like this idea, at least for 8 tc, and somewhat in general, it's most certainly just going to be an instabuy item like noslips are right now.

**Comment by GoodWheatley** [comment]
Would raising the price help with that?

**Comment by EmoGarbage404** [comment]
Isnt the elite hardsuit supposed to identify the commander? Dont they all already spawn with hardsuits anyways? Do they really need another direct upgrade to spend TC on? One that is, arguably, less interesting than other shop items.

**Comment by asperger-sind** [comment]
> Isnt the elite hardsuit supposed to identify the commander? Dont they all already spawn with hardsuits anyways?

Commander has their own hardsuit with it's own unique sprite and resistances, nukies (not the ones off reinforcement beacons) already spawn with normal bloodred hardsuits, yes.

I don't think a price change'd help, honestly, it's just the boring kind of purchase that you don't really want to see.

**Comment by GoodWheatley** [comment]
> Isnt the elite hardsuit supposed to identify the commander? Dont they all already spawn with hardsuits anyways? Do they really need another direct upgrade to spend TC on? One that is, arguably, less interesting than other shop items.

The commander gets his own unique hardsuit. The one I've made available for purchase is the one the medic gets by default. And aren't most of the items nukies spend TC on (no-slips etc.) direct upgrades anyway?

**Comment by asperger-sind** [comment]
> Ideally, if theres item that they _need_ to buy every single nukie round, they should just spawn with them rather than having to waste TC on them. Theres nothing tactical or interesting about having to buy no-slips/magboots every single round.

It's not really _need_, you CAN go without it, but there's no reason not to buy it if you're not spending all of your TC for something like an L6 Saw. It's also somewhat better now that you need to choose between combat boots/magboots/no-slips.

**Pull request closed without merging**
