### PR TITLE
mech air overhaul

### LINKED ISSUE #19116: VIM slowly suffocates its poor mouse passengers
repro
go in a vim
die after a while

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
instead of just taking in air when entering and dumping when exiting, airtight mechs will now intake air from the surrounding atmosphere and scrub waste gases, fixes #19116
this means that oxygen will automatically replenish and you cant get co2 poisoning anymore
however they dont have gas mix when built so you have to give it a few seconds to build pressure before getting in

doesnt ripley or honk in any way

unfortunately codewise this is largely a copypaste of pump vent + scrubber, not sure what could be done to reuse them

filtering is slow enough that if an empty vim is in a room with 1mpa of plasma, it will slowly fill up with plasma until its in an area where it can be dumped out, which is a very extreme case. if a vim is already filled with air then there is little danger from a room full of plasma.

**Media**
trust
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: The HAMTR and Vim now have builtin scrubbers to remove the risk of carbon dioxide poisoning.

### CODE REVIEW

**Comment by Emisse** [comment]
could you make the gases datafields in MechAirFilterComponent be part of the proto yml instead of hardcoded in

**Comment by deltanedas** [comment]
i think it requires using ids but yeah

**Review by Emisse — APPROVED** [review]

**Comment by metalgearsloth** [comment]
1. Someone familiar with atmos should look at this.
2. This needs to be re-useable with vehicles.

**Comment by deltanedas** [comment]
that would require a generic component for internal air not specific to mechs, not sure how to go about doing that
also cryo pod has basically the same thing except it has a pipe, could that be migrated to hypothetical internal air thing

**Pull request merged**
