### PR TITLE
dedicated burn and shock meds

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds dedicated burn and shock meds, Pyrazine and Insuzine (feel free to suggest better names :trollface:)

they are both derived from leporazine in some way

it might be worth letting pyrazine (or both) work on corpses since unloading a few incendiary shells on a naked urist gives 600+ heat damage :trollface:

## Why / Balance
right now there are dedicated cold (leporazine) and caustic (sigynate) along with meds for every brute kind. burn and shock are desperately needed, since people that come into med with it usually have a lot (being lit on fire, getting in a laser fight, trying to tide into a room, electric anomaly, etc.). in these situations you would always have to use dermatane meaning wasting any airloss med and being overall bad

pyrazine heals slowly but is extremely efficient (20 heat damage per unit over 10 seconds)
its slow so you dont chug pyrazine before going into a fight to instantly heal everything, for combat its roughly on par with derma

insuzine heals a lot of shock at normal speed since you usually dont need it in combat
its also a counter to licoxide since funny

their od's are very deadly (bleeding to death and freezing to death respectively)

## Technical details
no

## Media

cooking it and their effects work trust

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: New specialized burn medicines Pyrazine and Insuzine can be made, for heat and shock damage respectively.

### CODE REVIEW

**Comment by CrigCrag** [comment]
cant you mix these with eachother and derma to make overpowered super healing mixes

(this is why razorium exists for brute)

**Comment by deltanedas** [comment]
turn into kelotane when mixed with other burn med :trollface:

**Comment by GreyMario** [comment]
consider:

1. put insulating clothes on someone 
2. overdose them on insuzine
3. pump them full of cryoxadone
4. abracadabra

**Comment by Alekshhh** [comment]
I love chems ending with zine!!!!!

**Comment by deltanedas** [comment]
ok give them better names :trollface:

**Pull request merged**
