### PR TITLE
Janitor trolley resprite

### PR DESCRIPTION
**Pull request by Deahaka**
## About the PR 
Resprite Janitor trolley
Sponsored by the [Theta Community](https://github.com/ThetaStation/ThetaStation).
**Screenshots**

**Changelog**

:cl: WalterJe, DarthSidiousPalpatine
- add: Added new sprite for janitor trolley.

### CODE REVIEW

**Comment by Deahaka** [comment]
> Looks more like the Eris art style than what SS14 is going for, I don't like it.

"SS14"? More like "TG"? ;)

**Comment by Zumorica** [comment]
> "SS14"? More like "TG"? ;)

no

**Comment by KIBORG04** [comment]
Mop bucket not resprited

**Comment by ike709** [comment]
You can argue semantics but it still looks like Eris's awful everything-is-plastic style.

**Comment by moonheart08** [comment]
We're not upstreaming Tau Ceti's artstyle. Please stop with these PRs.

**Comment by Deahaka** [comment]
Okay

**Comment by LudwigVonChesterfield** [comment]
@Deahaka should we tell them about the closets?

**Pull request closed without merging**
