### PR TITLE
Removed roundstart cloners and scanners from packed and saltern.

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Replaces the roundstart cloning pods and scanners with a medical supplies crate, effectively research-locking them. The first and mildest in what will probably be a series of changes targeting cloning. 

**Changelog**

:cl: Rane
- remove: Removed roundstart cloners and scanners on medium and high pop maps. They now need to be researched.

### CODE REVIEW

**Comment by Elijahrane** [comment]
To summarize the arguments for this ultra based version:
1. You actually can get all the info you need without scanners: People can tell you what's wrong with them, or you can tell by the damage visualizers.
2. The damage visualizer gives all the information a doctor needs. Only brute and burn can be healed without chems, and those are shown in the damage visualizer. If someone is wounded without visual damage then it is toxins or airloss, both of which need chems anyway. (So you don't need to tell between them to shove tricord in their mouth)
3. Doctors are now a more in-depth social role where diagnosis is a process and they can use all the unused rooms around the medbay to physically examine people in privacy if needed.

**Comment by mirrorcult** [comment]
this diff seems far too large

**Review by mirrorcult — APPROVED** [review]
other than the diff

**Comment by metalgearsloth** [comment]
> this diff seems far too large

Part of it may be https://github.com/space-wizards/RobustToolbox/pull/2472

**Comment by Elijahrane** [comment]
I used the same process I always do to save, it's gotta be that engine change I think.

**Comment by hubismal** [comment]
copypasted from discord:

This is far too optimistic of a PR imo
the only reason people are cloned at all once they die is because someone occasionally runs down the cloning list or some good samaritan finds a body and goes through the whole process to make sure a person is cloned
in normal SS13 this makes sense but in SS14 where half of the players are new greytiders (most of which have no idea how to build a machine let alone research) cloning is never going to happen

**Comment by TimrodDX** [comment]
While I don't have any actual authority over changes to Packed, I'm going to say that I strongly recommend against this being merged there. I get that everyone is anti-cloner and pro-surgery, but the alternatives (things like the health HUD, health analyzers, the defibrillator and surgery) aren't in the game yet. I think this change is premature at this stage of the game.

**Comment by Delete69** [comment]
So if I released a map tomorrow would you make the decision to remove the body scanners? What is a medical department/hostpital without professional equipment?  Honestly if you really stop and think about this, it makes zero sense. Remove cloners? Maybe, but body scanners? That's ridiculous.

**Comment by metalgearsloth** [comment]
My only stake in this is that body scanner code is pretty shit

**Comment by Fishfish458** [comment]
If this is the place for discussion, after thinking it over a bit, I'm not quite sure removing the cloners at round start would accomplish much other than punish those who suffer an unfortunate accident early at round start and force science to always be under heavy pressure to research the specific medical path to get them as fast as possible.

Alternatively as a patch, cloning could be made to take longer and only be effective for those immediately in a scanner.

**Comment by Elijahrane** [comment]
> copypasted from discord:
> 
> This is far too optimistic of a PR imo the only reason people are cloned at all once they die is because someone occasionally runs down the cloning list or some good samaritan finds a body and goes through the whole process to make sure a person is cloned in normal SS13 this makes sense but in SS14 where half of the players are new greytiders (most of which have no idea how to build a machine let alone research) cloning is never going to happen
It may be hit or miss but I would say the rounds where cloning doesn't happen are in the minority. 9/10 of rounds science builds all copies of all the medbay machines anyway.


> the current cloning system is broken, yes, but I think it's actually helpful to the whole playtesting thing. you're way more likely to go to try a bunch of shit out to see what it does if you can be confident you'll probably be revived when something inevitably goes wrong
This is somewhat true but I think it's counteracted by the fact this will reduce round length; SS14 has an average round length longer than a lot of BYOND servers despite having a fraction of the content so even if people don't die a lot of them check out because there's nothing to do and nothing happening.

>I get that everyone is anti-cloner and pro-surgery, but the alternatives (things like the health HUD, health analyzers, the defibrillator and surgery) aren't in the game yet. I think this change is premature at this stage of the game.
Of what you listed only the defib is an alternative to cloning. Healing is so easy right now that the other things aren't needed and this will at least give docs something to do (diagnosis and patient management).

>I'm not quite sure removing the cloners at round start would accomplish much other than punish those who suffer an unfortunate accident early at round start and force science to always be under heavy pressure to research the specific medical path to get them as fast as possible.
I think that's preferable to metagamers rushing to get scanned 30 seconds in, and science barricades themselves in every round anyway like the apocalype is imminent so may as well give them something to worry about.

**Comment by Delete69** [comment]
Here's how this is going to go: At round start medical is going to harass science to research and build scanners/cloning pods. Within a few minutes of round start, these machines will be dragged over to medical and installed. This will happen, and be expected to happen _every single round_, and absolutely nothing will change except the 2 minutes you tacked onto the beginning of your now 92 minute round. It's not like this hasn't been discussed in length before in discord by numerous people. The consensus is usually that cloners and scanners are just too easy, and that the solution is your proposed "series of changes targeting cloning". Or, make your own map that's balanced around research and building. I know that once I release my own I will fight tooth and nail if someone wakes up one day and decides to just remove body scanners from it.

**Comment by Elijahrane** [comment]
Science can't even research cloners in 2 minutes, they literally don't have the points.

The rant about mapper sovereignty you are going on is extremely strange and basically irrelevant. If you ever make a map, sure, install cloners at roundstart. The SS14 secret police aren't going to kick down your doors at 1am.

**Comment by Delete69** [comment]
> Links?

CTRL-F

I see no issue with time-gating cloners. I'm all for making things more complicated, involved, engaging, or interesting, but my belief that body scanners are basic medical diagnostic equipment outweighs that. I'd rather not see medical be some kind of shamanistic society waiting on a gift from their technology-gods just because you can visually diagnose brute/burn damage. Go ahead and make your changes to the two devices, I've read your conversation as well as others, and I like your proposals. Everyone can easily agree that something needs to be done, but in my opinion you can skip the step of removing scanners and move forward.

**Comment by Elijahrane** [comment]
I think this PR is gonna end up being irrelevant anyway with changes from me and Fishfish in the next week or so.

**Comment by Elijahrane** [comment]
Closing this to lessen PR load since cloners are getting changed soon anyway

**Pull request closed without merging**
