### PR TITLE
remove netsync false from sprite component in prototypes

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

**Media**

 - [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl

### CODE REVIEW

**Comment by Emisse** [comment]
lord almighty

**Comment by metalgearsloth** [comment]
We should get a test for this too in the linter IMO.

**Comment by lzk228** [comment]
idk what exactly i should fix in removing useless lines

**Comment by ElectroJr** [comment]
> idk what exactly i should fix in removing useless lines

The issue is that you didn't only remove it from sprite component, but from other components as well, which still need it.
Assuming you used some automated tool to remove the lines, you need to redo that to only remove the lines from sprite components.

**Comment by lzk228** [comment]
fixed

**Pull request merged**
