### PR TITLE
Implement basic emoji support

### PR DESCRIPTION
**Pull request by juliangiebel**
## About the PR
Adds support for uncolored emojis using Noto Emoji https://fonts.google.com/noto/specimen/Noto+Emoji.
This font can be used by the font richtext tag or separately to where it's needed.

## Why / Balance
This was really easy to do. Idc if this PR just gets closed because we don't want emoji support.
I think this would be funny for PDA messaging

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Errant-4** [comment]
Why would we want this in chat, if even chatspeak words are banned?

**Comment by Menshin** [comment]
Can be fine in papers/books, but that seems really out of place in chat imho

**Comment by juliangiebel** [comment]
I also think they don't belong in chat. I just added them to the default font stack

**Comment by TheShuEd** [comment]
player: i found 🤡 
TTS: *died*

**Comment by juliangiebel** [comment]
> player: i found 🤡 TTS: _died_

A TTS will either describe the emoji or ignore it

**Comment by LankLTE** [comment]
Keep in mind that while this may not be desirable for chat, downstreams may want support for this for various things & PDA messaging probably could benefit from this too. Ahelp icons would also be really nice with this since currently they need to use a small batch of really odd emojis. If people are gonna use netspeak words they’ll do it regardless of if emojis are supported or not imho

**Comment by metalgearsloth** [comment]
Did you mean it requires https://github.com/space-wizards/RobustToolbox/pull/4834 ?

**Comment by juliangiebel** [comment]
Yea, thanks for noticing that 🙏

**Comment by IProduceWidgets** [comment]
Please add an accent that makes emjoji in chat change to descriptions of whatever the emojis for our sanity's sake.

**Comment by juliangiebel** [comment]
I removed the font from the default font stack. It can still be added where emoji support is needed and used for the font tag.
@metalgearsloth

**Comment by metalgearsloth** [comment]
Engine PR closed so not sure what's going on here.

**Pull request merged**
