### PR TITLE
Add's Senior role drip to the Uniform Printer.

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Added the Senior position drip to the Uniform Printer

## Why / Balance

Senior drip was lost when the roles got removed, this will bring them back without the issue of having the position.

## Technical details

Added all of the Senior position jumpsuits and skirts to clothing.yml and lathe.yml for the uniform printer.

## Media

Screenshot 2024-02-27 235658

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- add: Senior uniforms have been added to the Uniform Printer, visit your local hop today!

### CODE REVIEW

**Comment by potato1234x** [comment]
thank god

**Comment by Kadeo64** [comment]
step one: make senior officer jumpsuit
step two: face away from the camera
:trollface:

**Comment by Cojoke-dot** [comment]
> step one: make senior officer jumpsuit step two: face away from the camera :trollface:

Hahahaha… ya, who actually trusts a random person wearing sec shit? You can print hos stuff from the machine but not Normal sec outfits? It makes a little sense but not much. The reason I put it into the Fab over the second drobe us because the item is more of an rp thing, for promotions. 

I entend to bring back the senior position in a different way. It's just going to be a HOP job, like visitors, that heads can promote their right hand too. A co-head without the access bacicly. The role was never used right so I figured I'd just turn it into an RP thing instead.

**Comment by Kadeo64** [comment]
> Hahahaha… ya, who actually trusts a random person wearing sec shit? You can print hos stuff from the machine but not Normal sec outfits? It makes a little sense but not much. The reason I put it into the Fab over the second drobe us because the item is more of an rp thing, for promotions.
> 
> I entend to bring back the senior position in a different way. It's just going to be a HOP job, like visitors, that heads can promote their right hand too. A co-head without the access bacicly. The role was never used right so I figured I'd just turn it into an RP thing instead.

I was making a joke about the senior officer jumpsuit's back sprite

**Comment by Cojoke-dot** [comment]
> I was making a joke about the senior officer jumpsuit's back sprite

Hehehehe! I used your comment to explain why I did something.

**Comment by Kukutis96513** [comment]
You should probably post this PR in the pr-review-request discord channel so that it gets reviewed and merged.

**Comment by Cojoke-dot** [comment]
> You should probably post this PR in the pr-review-request discord channel so that it gets reviewed and merged.

**Comment by metalgearsloth** [comment]
Weird to timegate it but allow it to be freely craftable ingame but okay.

**Pull request merged**
