### PR TITLE
APC interface no longer restricted to a single user at a time

### PR DESCRIPTION
**Pull request by hyphenationc**
## About the PR

APCs are no longer accessible by only one user at a time.
## Why / Balance

AI should not be able to lock players out of APCs. Prevents #32312 
## Technical details

apc.yml has had singleUser value changed from true to false.
## Media

Unnecessary.
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]

**Comment by lzk228** [comment]
have you tested it in game? does the ui work in right way?

**Comment by hyphenationc** [comment]
> have you tested it in game? does the ui work in right way?

Works as well as it usually does. Two users (clients) can open the UI at the same time, and even if one has the proper access required (access: [["Engineering"]]) the other user without requisite access is unable to toggle it, while the one with is.

Small strangeness where if you lose access at any point while in the menu it locks you out even if you regain that access, but really that's neither here nor there.

**Comment by eoineoineoin** [comment]
The reason it's `singleUser: false` is that the UI doesn't properly work with multiple users. Here's a "captain" being unable to toggle the breaker, despite having proper access:



In ApcSystem.cs, there's a TODO, which you'd at least need to fix before making the UI multi-user:

```// TODO: this should be per-player not stored on the apc```

**Comment by hyphenationc** [comment]
Didn't see that todo. Probably shoulda checked, but I'll look into it now. Might be the cause of the
> small strangeness where if you lose access at any point while in the menu it locks you out even if you regain that access
bit.

If nothing else, I can probably scrape code from the vending machines to have it check on every interaction, or if that isn't what's happening there, whatever I make here can be applied there to prevent the same issue. Or something like that.

**Pull request closed without merging**
