### PR TITLE
Unknown shuttle event minor fixes

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
fixing some bugs.

greatly reduced chances of shuttle events

- Honki shuttle:
  - Removed (LRP hell)
- Cuisine shuttle:
  - Remove Ian meat
  - Remove 2/3 Dragon meat
  - Fix wires
- Syndicate shuttle
  - Add Gravgen
  - Add Thrusters
- Disaster Evacpod
  - Auto Mindshield implant for heads  

**Changelog**
:cl:
- remove: Removed Clown unknown shuttle
- tweak: Greatly reduced chances of shuttle events

### CODE REVIEW

**Comment by FungiFellow** [comment]
Can we get an Air Can and a scrubber or two on the cuisine shuttle?

The wall locker for the Evac Pod lacks a Wrench

**Comment by FungiFellow** [comment]
The Clown shuttle should stay gone, every time I've seen it the clowns end up pulling some bullshit

**Comment by IProduceWidgets** [comment]
One clown is a laugh, but three is slaughter.

**Comment by TheShuEd** [comment]
map errors + merg conflict
i recreate PR later

**Pull request closed without merging**
