### PR TITLE
Telecom server panel check

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

**Media**

Peek 2023-03-08 14-47

**Changelog**

:cl:
- tweak: maintenance panel needs to be opened to insert/remove keys in telecom server
- fix: telecom server now can be deconstructed with crowbar

### CODE REVIEW

**Comment by Kit0vras** [comment]
Maybe welding is better for deconstruct? people can just miss click with crowbar
And welding not so easy as prying

**Comment by Kit0vras** [comment]
or something else

**Comment by deltanedas** [comment]
basically every other machine is screwdriver -> crowbar to turn into machine frame
if you mess up just screw it again

**Comment by QuietlyWhisper** [comment]
How do you deconstruct the server now?

**Comment by Slava0135** [comment]
image
need to do something about this

**Pull request merged**
