### PR TITLE
add inline gas filter

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds a new inline gas filter costing 8 steel that doesnt split its pipenet in two.

a more compact version of joining the inlet and outlet with pipes

## Why / Balance
now that pipes cant be stacked a very common method of having an inline filter (placing a straight pipe over a filters inlet and outlet) cant be done in the same space.
**this can still be done without a dedicated item it just takes more space**

the new inline filter costs a piece of steel on top of that (8 total) in exchange for fitting in a single tile and more importantly **being easily recognizable** that its not a normal filter which stacked inline filters suffered from.

balance wise all this changes is how much space you need to do things, the mechanics of it are still possible.

## Technical details
setting inlet to be the same as outlet just werks

**this can freely be removed if someone changes filters to require flow in the future** similar to how radiators work

## Media
inline filter just acts like a straight pipe when off, and still respects the pressure limit
the "unpacked" version with regular filter also works the same way

https://github.com/space-wizards/space-station-14/assets/39013340/77385149-e1a7-4d8c-8c7e-5ab803fa1267

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Added inline gas filters to the construction menu for atmos techs.

### CODE REVIEW

**Comment by Ilya246** [comment]
8 steel is kind of a lot, even old inline filtering costed 4 per tile

**Comment by deltanedas** [comment]
3* but the cost is based on what the equivalent costs now (7), not what it used to cost

**Comment by EmoGarbage404** [comment]
> this can freely be removed if someone changes filters to require flow in the future similar to how radiators work

Why not just change that to begin with considering I'm pretty sure that flow based stuff is wanted moving forward.

**Comment by mirrorcult** [comment]
this is significantly more confusing than just connecting the inlet and outlet with pipes and that doesnt require an entire new pipe type thats barely distinguishable from a regular filter

**Comment by mirrorcult** [comment]
also feature freeze dawg

**Comment by deltanedas** [comment]
> Why not just change that to begin with considering I'm pretty sure that flow based stuff is wanted moving forward.

easier said than done :trollface:

> this is significantly more confusing

not much harder to ask what an inline gas filter does than to ask why a filter is looping in on itself

the real benefit would be being able to use it on small maps, you dont always have ~300 tiles of free space to build stuff on

> this is significantly more confusing than just connecting the inlet and outlet with pipes and that doesnt require an entire new pipe type thats barely distinguishable from a regular filter

its not much more confusing than asking why a filter is looping in on itself

**Comment by Partmedia** [comment]
> this can freely be removed if someone changes filters to require flow in the future similar to how radiators work

The [atmos roadmap design doc](https://docs.spacestation14.com/en/space-station-14/departments/atmos/proposals/atmos-rework.html) calls for devices like filters to be flow-based, so it would be better to implement that directly instead of having this in the interim.

**Comment by deltanedas** [comment]
wyci

**Comment by WarMechanic** [comment]
@deltanedas will you get this reopened? if not you should try it downstream

**Comment by GimmyPick** [comment]
so, will they add it?

**Pull request closed without merging**
