### PR TITLE
makes content support .yaml too

### PR DESCRIPTION
**Pull request by PaulRitter**
what it says on the tin

can be merged at your disclosure if a new RT version is pushed, shouldnt be breaking if not instantly merged after tho

### CODE REVIEW

**Comment by PaulRitter** [comment]
corresponding commit: https://github.com/space-wizards/RobustToolbox/commit/d8d2993d7f3dea3d92e529fa642c88754b4d30d2

**Comment by moonheart08** [comment]
But why though?

**Comment by moonheart08** [comment]
See https://github.com/space-wizards/RobustToolbox/issues/3759.

**Comment by PaulRitter** [comment]
> But why though? I'm not sure letting people randomly pick which file extension they want is a good idea.

The .yaml file extension isnt really an arbitrary file extension, it is pretty widely used, interchangable with .yml. The fact that contribs ran into this issue & were confused only further proves that point imo.
I really dont see the harm in supporting a file extension thats seeing alot of usage in general, its not like im implementing a .prototype file extension.

**Comment by PaulRitter** [comment]
look ultimately i just wanted to fix the yaml issue. if you think this is bad & would rather have a warning, do implement it. i just wanted a solution and thought this was the most userfriendly one, i dont mind if you were to change it to a warning

**Comment by Visne** [comment]
I personally dislike it because I will have to search for `*.y*ml` instead of `*.yml` if I'm filtering file extensions, and I already know I will forget sometime in the future. I think that having multiple extensions for the same type of file is a pretty big anti-feature in general.

**Comment by PJB3005** [comment]
The reason why this is a bad idea has already been clearly stated by the other people here and https://github.com/space-wizards/RobustToolbox/pull/3757. Being more lenient with input data just results in spaghetti that all future code is going to have to account for. This is quite clear already from all the commits involved, since it took you three engine commits for this already, and you still missed a spot.

I'd also like to mention that after you saw the revert PR you decided to direct push another commit to engine rather than making a PR for it. It is quite clear that this needed proper review (like I said, you still missed a spot in texture loading code) and it is clearly something that should have been discussed properly first. Furthermore I already expressed the fact that this is a bad idea on both GitHub and Discord the moment it was first discussed, which you must have seen.

**Comment by PaulRitter** [comment]
> This is quite clear already from all the commits involved, since it took you three engine commits for this already, and you still missed a spot.

This is due to me not doing due dilligence in the first commit, and realising it after double checking shortly after, not due to this being immensely complex. The spot I missed you are referring to is probably texture loading: I left that part out on purpose, since it isnt my area in the engine (and therefore i didnt know if there are any standard etc to account for here) and my fix was intended purely for prototype/map resource files.

> I'd also like to mention that after you saw the revert PR you decided to direct push another commit to engine rather than making a PR for it.

Yes i opted to fix the code currently on master. Nothing about that is etched in stone, I've already told you multiple times that I dont care if you replace this logic with a warning like you suggested.

> Furthermore I already expressed the fact that this is a bad idea on both GitHub and Discord the moment it was first discussed, which you must have seen.

I have you blocked on discord for your repeated unprofessional conduct, hence i cant and wont read your messages. I did not see any previous gh comments about it by you, but I admittedly did not search for any issues before making this change, so if there are any, thats on me.

And again, I dont care about this way of fixing the issue. If you think its bad, please replace it. You can instantly revert it for all I care. The only motivation I had here was to fix an issue a contrib brought up to me, not to stick to this specific solution of fixing the problem at hand. I'd appreciate if you would stop implying malice and assume that i am not trying to either undermine or ignore you based off of events that are evidently not in the slightest antagonistic.

**Comment by PaulRitter** [comment]
> I personally dislike it because I will have to search for `*.y*ml` instead of `*.yml` if I'm filtering file extensions, and I already know I will forget sometime in the future. I think that having multiple extensions for the same type of file is a pretty big anti-feature in general anyways, but that's YAML's fault.

Makes sense to me tbh. I thought supporting all filetypes might be more userfriendly, but i could imagine this scenario being more annoying than having to rename a file tbh.

**Comment by PJB3005** [comment]
> since it isnt my area in the engine 

If you weren't confident in the change you should have made a PR and asked for the other maintainers to review it, or simply even asked on Discord.

> Yes i opted to fix the code currently on master. 

There would have been no harm in merging the revert PR instead so we could hash things out properly.

> I've already told you multiple times that I dont care if you replace this logic with a warning like you suggested.

Quickly introducing extra tech debt instead of fixing the root problem is never how we should go about things.

There is no good reason for a dirty and temporary solution here, this is the first time I can recall that anybody has ran into this, and spending a day or two more on a proper solution isn't a going to hurt anything. I already have a local prototype fix and it's actually less work than this change.

> I have you blocked on discord for your repeated unprofessional conduct, hence i cant and wont read your messages

I do not see a reason for you to maintain write access to the repositories if I cannot trust to be able to effectively communicate with you.

I expect you to not rashly direct push things on a whim after I say it's a bad idea on Discord. Mistakes happen, but I then expect you to pause for a moment instead of direct pushing more things when I say it's still a bad idea on GitHub.

> You can instantly revert it for all I care.

Done

**Comment by PaulRitter** [comment]
again, i didnt intend my solution to be a quick and dirty fix but a permanent solution. yeez, can you calm down.

**Comment by PaulRitter** [comment]
stop acting like a bully and talk to me normally. people shouldnt really wonder why i went inactive having to constantly deal with this

**Pull request closed without merging**
