### PR TITLE
Supermatter Crystal (take 2)

### PR DESCRIPTION
**Pull request by whateverusername0**
regarding #28980 it shouldn't be copyrighted anymore 😄

## About the PR

Added the supermatter crystal and things related to it.

Radiates everything around it, shoots lightning bolts every now and then, scales it's power depending on damage taken and gases it inhales, which can very quickly turn into a nightmare for engineering squad. Very brittle, takes damage from high temperatures, pressure, specific gases, etc. etc.

Quick note: until being collided with something or getting damaged, SM won't do anything to prevent early game station destructions.

Alerts fellow engineers at a certain point if constantly taking damage, making them do their job to secure the SM and not screw the entire station up :trollface:

And, after reaching a certain point, starts _the final countdown™️_ and delaminates into a huge explosion, a tesla, a singularity or ~~reconance cascade'ing and ending the round~~ (unavailable due to me not having ideas on how to implement it's conditions since hypernob and antinob are not in the game yet)

Vaporizes whatever collides with it, except energy bolts which deal damage to it (emitter/disabler excluded).

Also added a new traitor objective that requires you to cut a sliver off of the crystal, which will greatly damage it and alert the crew, the sliver itself is highly radioactive so good luck keeping it safe :trollface:

## Technical details

even i don't 100% know how it works, i forgot half of the stuff while doing it 🤷‍♂️

## Media

in-game sprites
image

rat hate
https://github.com/space-wizards/space-station-14/assets/113782077/6c737074-4d33-467f-82a4-7563eabaec9e

automatic announcements
image

delamming (explosion)
https://github.com/space-wizards/space-station-14/assets/113782077/0fd5fbdb-2b84-4372-813d-8ef3576bd939

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## TODO
- [ ] Implement the objective correctly.
- [ ] Listen to people's opinions
- [ ] A lot of testing
- [ ] A lot of tweaking
- [ ] A lot of cleanup
- [ ] A lot of refactoring

**Changelog**

:cl:
- add: Added the supermatter crystal!
- add: Added new traitor objective: cut off a sliver from the supermatter crystal!
- tweak: Singularity now needs to consume the supermatter crystal to reach level 6.

### CODE REVIEW

**Comment by mirrorcult** [comment]
as is its incredibly unlikely we're going to accept SM as an engine in basically any capacity even with big changes, the previous PR should have been closed for this reason instead of having it be pending a rewrite but that is our bad for not doing so

has been ~general consensus for a while but essentially the only thing SM has going for it is its thematically pretty cool, as for its issues that we feel are pretty inherent
- extremely opaque, interacts with atmos gases in a way that has zero parallels to anything people could build intuition from
- extremely easy to mess up by accident in ways that are non obvious and completely detonate the station
  - extremely easy to sabotage in ways that are non obvious as a corollary
- has 'complex' (not really, just unexplained and unintuitive) interactions but is incredibly hard and not very fun to actually experiment with inround due to the extreme danger of fucking it up
- simply not very interesting. no maintenance or monitoring effectively required except to prevent sabotage, you basically just follow wiki directions to set it up and then its fine for the rest of the round
- atmos-interacting engine is already done better design wise by the currently-existing TEG and having both do the same thing design wise is kind of pointless

**Comment by mirrorcult** [comment]
obv you put a nontrivial amount of work into this (especially with the last pr) so apologies for just closing it outright. i would see if there are downstreams interested in having this implementation since it looks generally competent

**Comment by whateverusername0** [comment]
zis is so sad

> downstreams

oh well 🤷‍♂️

**Comment by Simyon264** [comment]
Why was it even closed?

**Comment by Tropica1Owl** [comment]
Ofc this gets closed but not that dubious APC resprite.

**Comment by whateverusername0** [comment]
> as is its incredibly unlikely we're going to accept SM as an engine in basically any capacity even with big changes, the previous PR should have been closed for this reason instead of having it be pending a rewrite but that is our bad for not doing so
> 
> has been ~general consensus for a while but essentially the only thing SM has going for it is its thematically pretty cool, as for its issues that we feel are pretty inherent
> 
> * extremely opaque
> * extremely easy to mess up by accident in ways that are non obvious and completely detonate the station
>   
>   * extremely easy to sabotage in ways that are non obvious as a corollary
> * simply not very interesting. no maintenance or monitoring effectively required except to prevent sabotage, you basically just follow wiki directions to set it up and then its fine for the rest of the round

also i believe you just described the AME 😆

**Comment by K-Dynamic** [comment]
> zis is so sad

Yeah, it's important to ask when planning contributions to see if your PR would be accepted in the first place

it's unfortunate you missed (not blaming you) previous discussions on why supermatter wasn't upstreamed on Discord, as well as outdated info still up suggesting SM is a requirement #20951

**Comment by mirrorcult** [comment]
> 
> also i believe you just described the AME 😆

the only points i think are relevant to the AME are easy to sabotage (true, but significantly easier to fix than SM and not nearly as big of a deal) and AME is uninteresting (also true, but AME at least requires refueling, which is more than you can say for the SM)

**Comment by Tropica1Owl** [comment]
> > also i believe you just described the AME 😆
> 
> the only points i think are relevant to the AME are easy to sabotage (true, but significantly easier to fix than SM and not nearly as big of a deal) and AME is uninteresting (also true, but AME at least requires refueling, which is more than you can say for the SM)

Refuelling like exchanging the plasma tanks on the collectors? If a battery change is the bare minimum for it to be considered maintenance then yes, the SM covers it too.

Also you're talking about SM's sabotage being too hard to fix when the Singulo and Tesla are in the game (You know, the two engines that are a guaranteed shuttle call every time they escape? Don't even get me started on how easy it's to screw them up too if you're a new player.)

Seriously, the **only** engine in the game that meets the criteria that you just described is the TEG, and maybe the Turbine if anyone ever codes that.

**Comment by LankLTE** [comment]
> also i believe you just described the AME 😆

We're already moving away from having the AME be the main power source on all but lowpop maps (which may not have a full engineering team to maintain it and thus needs to be simplistic), so I don't really see what the point is here.

**Comment by WarMechanic** [comment]
you could ask DeltaV if you want to implement it there, although it would be a bit iffy since we're currently looking to port someone else's supermatter implementation too.

**Comment by Just-a-Unity-Dev** [comment]
i'd like to have this open even if its not roundstart, perhaps as an orderable for cargo or something

**Comment by BolloTea** [comment]
That is, the reasons why SM is not added are:
* "Very difficult" - guides inside the game or Wiki. Players are not that stupid and sometimes don't mind having something difficult or something that would challenge them
* Opacity - why not make a console that would show you the state of the medium, gas, its temperature inside the chamber and other little things.  The author is no longer against making a service, which, if you so desire, can even be complicated or made more interesting.  If I'm not mistaken, there is such a console on the turbine, right?
* The explosion radius is not as critical as that of a nuclear warhead, if I’m not mistaken, and the destruction is much less than 13. Since there is no severe radiation background that would make the entire department glow like a Christmas tree.   And at the moment we have engines that are much more evil and dangerous, that are really capable of destroying the ENTIRE station, and not a small part of it
* we have TEG - diversity, more interactions and experiments, rather than collecting the same thing.  You would be tired of eating the same food over and over again, perhaps yes, just like the veteran engineers.
* Sabotage - if I'm not mistaken, in 13 you can prevent sabotage, even at the very last moment - although you will have to do a lot and literally almost sacrifice yourself to normalize the crystal.  In addition, do not forget about the alerts that they shout at you when the integrity of the crystal decreases, if I’m not mistaken with 75%, which means that you have at least 15 minutes to fix everything

**Comment by BolloTea** [comment]
Sorry if I messed something up or noted something incorrectly

**Comment by CyberDuck-Git** [comment]
image
What`s wrong?

**Comment by CyberDuck-Git** [comment]
> изображение Что не так?

Crystal do nothing

**Pull request closed without merging**
