### PR TITLE
Revert "Add chem solution atmos heating and cooling"

### PR DESCRIPTION
**Pull request by Chief-Engineer**
Reverts space-wizards/space-station-14#17854

Superheating stations 
image

### CODE REVIEW

**Comment by Emisse** [comment]
silly

**Comment by mirrorcult** [comment]
@0x6273

**Comment by 0x6273** [comment]
Oops

**Comment by retequizzle** [comment]
i for one like the fact that we are able to compress our stations with pressure and temperatures exceeding that of a neutron star

**Comment by Anzarot121** [comment]
Apparently, before making a heat conversion system, a thermal control system for the station is needed.

**Comment by 0x6273** [comment]
Does anyone know what happened to cause the infinite heating? This never happened during my testing..

**Comment by Emisse** [comment]
does it have something to do with anchored entities heating infinitely

**Comment by mirrorcult** [comment]
might have to do with solutions interacting with space?

**Comment by 0x6273** [comment]
> might have to do with solutions interacting with space?

Yeah that seems to be it. Goes to Inf then NaN.

image

**Pull request merged**
