### PR TITLE
Pomegranate & Bombegranate

### PR DESCRIPTION
**Pull request by drteaspoon420**
## About the PR

- Added Pomegranate & Bombegranate
- Miscellaneous fixes/adjustments to make Bombegranate work

## Why / Balance

Wanted to include something inspired by 'exploding' plants in nature that use violent explosion to send seeds in wider area. Usually the method is to store a lot of kinetic energy as it grows into strained shape or dries into one. Some plants have chemical reaction to produce some sort of propulsion.
Pomegranate was added just to provide pun for the mutation as the Bombegranate ,while inspired by Sandbox Tree Fruit, does not exist.

## Technical details

Added prototypes for seeds & produce, localization strings and artwork for Pomegranate & Bombegranate
Bombegranate also has prototypes and artwork for seed projectiles.
Bombegranate's chemical contents are 9u (at potency 10) divided to Sulfur,Hydrogen and Ethanol. It Juices into Welding Fuel.

Bombegranate when thrown explode into ten (10) seed projectiles delivering all of the fruit's chemical contents evenly divided with the projectiles (0.9u per projectile).

For the Bombegranatet to work I had to:
- `ClusterGrenadeSystem.cs` implemented AmmoShotEvent when using `GrenadeType.Shoot` to enable use of `ChemicalAmmo` component
- `ChemicalAmmoSystem.cs` fixed issue with dividing Integer value instead of Float/FixedPoint value. More than 1 projectiles caused value to be zero.
- `SolutionInjectOnCollideSystem.cs` fixed cases where trying to inject more than available space. While not issue in most cases

## Media

[grentree-grow.webm](https://github.com/space-wizards/space-station-14/assets/87363733/8ca1a5d1-6453-4392-8113-4aeb3b04b67a)
[grentree-throw.webm](https://github.com/space-wizards/space-station-14/assets/87363733/6552a47f-dff1-4d80-b1ed-aa981d419a04)
Updated Bombegranate sprites: 
bombegranate

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

There should be no breaking changes.

**Changelog**

:cl: DrTeaSpoon
- add: Pomegranate and its mutation Bombegranate

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
"I swear officer, they're omnizine grenades!"

**Comment by Tayrtahn** [comment]
Can we call them pomegrenades, or is that ripping off Barotrauma?

**Comment by drteaspoon420** [comment]
I am cool with that. It's reasonable pun to make.

**Comment by Tayrtahn** [comment]
> Maybe 'bombgranate' instead?
How about "bombegranate"?

**Comment by mirrorcult** [comment]
100% bombegranate

**Comment by potato1234x** [comment]
[pvz reference](https://plantsvszombies.fandom.com/wiki/Bombegranate)

**Comment by drteaspoon420** [comment]
Bombegranate it is.

**Comment by Catdere** [comment]
But real question where is Pomegrenade Extract from barotrauma

**Comment by deltanedas** [comment]
bicaridine

**Comment by drteaspoon420** [comment]
You want me to change the contents to bicaridine? medicine bombs? :D

**Comment by Catdere** [comment]
> You want me to change the contents to bicaridine? medicine bombs? :D

I mean it would be interesting for them to contain a medicine while also being explosive

**Comment by drteaspoon420** [comment]
They are only 'explosive' in sense that they break and send splinters when they get smashed into something.
Sending splinters that deliver chems. Right now the chems are 'brokendown' welding fuel (via centrifuge) that cause vomiting mostly.

**Comment by beck-thompson** [comment]
A classic mistake that I have also made 😆

**Pull request closed without merging**
