### PR TITLE
Add defib event, add fields to be able to disable crit defib and do after movement

### PR DESCRIPTION
**Pull request by DrSmugleaf**
## About the PR
The code is such a shitshow that I'm not sure what's a bug or intended so data fields it is

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Review by VasilisThePikachu — APPROVED** [review]
May want a CL since we now allow defib to be used when moving by default.

**Comment by deltanedas** [comment]
if BreakOnMove defaults to true then nothing was changed

**Comment by VasilisThePikachu** [comment]
> if BreakOnMove defaults to false then nothing was changed

it defaults to true

```cs
    [DataField]
    public bool AllowDoAfterMovement = true;
```

**Comment by DrSmugleaf** [comment]
> > if BreakOnMove defaults to false then nothing was changed
> 
> it defaults to true
> 
> ```cs
>     [DataField]
>     public bool AllowDoAfterMovement = true;
> ```
> 
> And the BreakOnMove doafter args becomes false cause we get the opposite bool. Thus it wont break on move. Unless im reading this VERY wrong

BreakOnMove defaults to false. This PR doesn't change any behavior, it is the same as master.
image

**Comment by VasilisThePikachu** [comment]
Ok I get it now. I was reading it wrong

**Pull request merged**
