### PR TITLE
Vending machines with ContainerSystem

### PR DESCRIPTION
**Pull request by CrazyCat2048**
## About the PR
Preparation for storing items in vending machines using a container (smart fridge just a week away 🙏).

## Technical details
Soon...

## Tasks
- [x] Add container
- [ ] Link the basic mechanics to the container
- [ ] Create entities from prototypes in advance
- [ ] Stack items according to meta data

### CODE REVIEW

**Comment by deltanedas** [comment]
i havent looked at it but will this make all vending machines spawn entities for their stock on init rather than when theyre ordered?

**Comment by CrazyCat2048** [comment]
> i havent looked at it but will this make all vending machines spawn entities for their stock on init rather than when theyre ordered?

Yes, this is the simplest solution. I don't know how difficult it will be for the server from the fact that 500+ objects will be created during map initialization

**Comment by metalgearsloth** [comment]
It won't be merged if you're spawning entire inventory machine stocks on mapinit.

**Comment by CrazyCat2048** [comment]
My fuck up. I incorrectly made a link to another PR, now the changes are not so transferred. Meeeeeh...

**Comment by deltanedas** [comment]
better solution would be to support the vending machine ui for storage containers, which would be used by smart fridge. thats already intended for people to put in things they made and not have any stock roundstart

**Comment by CrazyCat2048** [comment]
> It won't be merged if you're spawning entire inventory machine stocks on mapinit.

Thank you for saying this in advance. I have already refused such an implementation.

**Comment by CrazyCat2048** [comment]
> better solution would be to support the vending machine ui for storage containers, which would be used by smart fridge. thats already intended for people to put in things they made and not have any stock roundstart

I think that in any case it would be right to make a "common" logic for all vending machines so that an item can be inserted during interaction. General, that is, add a component with a container to the desired vending machine. And a new system that, when adding an item, would inform the SharedVendingMachineSystem about the addition and increase the number of items in the list. 

As for the UI, in any case I will have to make another one for a smart fridge, because my goal is to make stacks of items using the same meta information. And I will have to add buttons to issue several items at a time.

Plus, I will need to somehow change the logic of issuing the item, because I will issue the item not by prototype, but by EntityId.

**Comment by CrazyCat2048** [comment]
I will close it, because I initially chose the wrong approach with containers. I will create a new one later, as I expand the logic of vending machines

**Pull request closed without merging**
