### PR TITLE
Small syndicate gear tweak

### PR DESCRIPTION
**Pull request by dontbetank**
## About the PR 
Hypopen is inherited from BaseItem so it has size of 5 compared to normal pens sized 2. Inherited it from Pen instead and removed obsolete components. Energy sword is too expensive for it's performance. Lowered the price, increased damage. Also energy pen replaces the sword totally. So now pen is quiter and slower to use than esword. Stealth and robust variants of the same weapon. And some refactor.
**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Prentor
- tweak: energy sword is cheaper and stronger, energy pen is stealthier and weaker
- tweak: hypopen now has size of normal pen

### CODE REVIEW

**Review by Emisse — APPROVED** [review]

**Comment by dontbetank** [comment]
I guess someone should fix that test?

**Comment by GoodWheatley** [comment]
I don't think the chameleon function should be on an entirely separate headset for a different price, giving the normal 
syndie headset the chameleon ability and the common channel would be cleaner and make it a better option to buy.

**Comment by CaptainSqrBeard** [comment]
I more like encryption keys PR ( #12615 ) because you can buy encryption key for traitor channel and just use it for your headset

**Comment by dontbetank** [comment]
> giving the normal syndie headset the chameleon ability and the common channel would be cleaner and make it a better option to buy.
Nuclear operatives also own such headest. A they don't need to access common channel and chameleon by default. Also they usually use face cover while stealthing so badass view doesn't matter this much.

**Comment by dontbetank** [comment]
> I more like encryption keys PR because you can buy encryption key for traitor channel and just use it for your headset

This PR looks... kinda forgotten but still it is way better.

**Comment by EmoGarbage404** [comment]
not really sure why there's an equipment split between nukies and syndies considering the two items are near identical. You'd be better off just combining the two and then not limiting it. It's not like giving nukies a stealth headset is game breaking in any way.

**Comment by dontbetank** [comment]
> It's not like giving nukies a stealth headset is game breaking in any way.
Hm... But access to common channel shouldn't be free, I guess?

**Comment by AlexMorgan3817** [comment]
> > I more like encryption keys PR because you can buy encryption key for traitor channel and just use it for your headset
> 
> That PR looks... kinda forgotten but still it is way better.

They forgot me, but i am waiting for reviews and merge, and now i will finish last review of #12615

**Comment by dontbetank** [comment]
>They forgot me, but i am waiting for reviews and merge, and now i will finish last review

Ah well, you are alive. Guess I will remove the headset since it's useless

**Comment by GoodWheatley** [comment]
While I do agree the esword needs a buff, I don't think the epen needs an attack speed nerf considering how weak its attack is, and the prices of the esword and the epen don't really need to be adjusted.

**Comment by dontbetank** [comment]
Epen attack is not weak! It was like an esword but cheaper with the only drawback is having -2 damage. Also I didn't think about price much, so It may need some changes.

**Comment by GoodWheatley** [comment]
> Epen's attack is not weak! Pen itself is like an esword but cheaper with the only drawback is having -2 damage. Also I didn't think about price much, so It may need some changes.

Then nerf the epen's damage stats, energy weapons are supposed to have a higher attack speed than normal weapons. Also, what happened to giving the syndie headset the common channel and chameleon abilities?

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
