### PR TITLE
Fix a typo in the 10 commandments

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
This fixes a typo in the 10 commandments silicon lawset.

## Why / Balance
Grammar

## Technical details
Grammar

## Media
no

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no

### CODE REVIEW

**Review by UbaserB — COMMENTED** [review]
can you make the other the's also thy

**Comment by IProduceWidgets** [comment]
https://youtu.be/-8ihcq4hzR4?t=49

**Comment by slarticodefast** [comment]
> can you make the other the's also thy

Isn't "thy" old english for "your/yours"? So it wouldn't make sense to replace "the" with "thy"

**Comment by UbaserB** [comment]
> > can you make the other the's also thy
> 
> Isn't "thy" old english for "your/yours"? So it wouldn't make sense to replace "the" with "thy"

i thought thy is the and thou is your/s

**Comment by slarticodefast** [comment]
> i thought thy is the and thou is your/s

I think thou==you and thy==your/yours

**Comment by Hanzdegloker** [comment]
> i thought thy is the and thou is your/s

Do not covet thy neighbor ( thy = your )

Thou shalt not kill ( thou = you )

**Comment by Psychpsyo** [comment]
> can you make the other the's also thy

No, because "thou" means "you" and "thy" means "your".
Excerpt from the actual 10 commandments:
> <sup>12</sup> Honor thy father and thy mother, that thy days may be long upon the land which the Lord thy God giveth thee.
> <sup>13</sup> Thou shalt not kill.

(King James Bible, Exodus 20.12 and 20.13)

**Comment by slarticodefast** [comment]
Enough confirmation for me 👍

**Pull request merged**
