### PR TITLE
Captain drip 2nd update

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR

Further updates the captain's drip, as well as updates some central command drip to fit the current captain drip. Edited the captain's current hardsuit but I plan on making a new one and replace it with the new one whenever I get around to spriting that.

Specific edits:
- Edits the colors for the captain's backpack, dufflebag, satchel, mask, hardsuit/helmet, bedsheets
- Gives the carapace a golden badge
- Gives the captain's jumpsuit an ass, removes the golden cuffs on both suits and further waters down the shading to better fit our style, as well as give him golden buttons
- Gives the captain's bedsheet the bedsheet texture that we see on the inworld item
- Makes the wintercoat's buttons less jarring
- Adds the capcap to both lockers instead of just one kind
- Adds the same kind of jumpsuit/skirt that the captain has to the central commander's wardrobe, as well as a green capcap and hardhat
## Why / Balance

Forgot a bunch of stuff in my last PR, and I was asked to make some changes.
## Technical details

This is almost exclusively sprite swaps
## Media

2023-8-23_16 06 0h7
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Changed the captain's wardrode a little bit.

### CODE REVIEW

**Comment by potato1234x** [comment]
pictures?

**Comment by pharmacreep** [comment]
golden visor for the captains hardsuit helmet is awesome

**Comment by Skarletto** [comment]
that hardsuit is going in the bin I just don't wanna work on a replacement at the moment
also to look at the sprite changes @potato1234x open the github-actions dropdowns i can't be bothered making a picture for the pr when im still working on it

**Comment by potato1234x** [comment]
i love it

**Comment by Skarletto** [comment]
lmao I can make the visor blue again

**Comment by Emisse** [comment]
you could make them black so it looks like sunglasses even more

**Comment by Skarletto** [comment]
im gonna do that

**Comment by Skarletto** [comment]
image image
the holy grail

**Comment by potato1234x** [comment]
Aw i liked the golden visor :(

**Comment by ps3moira** [comment]
> image image the holy grail

A suggestion for the visor to be more like the original shade of blue the old-visor had, as this blue is a bit too bright

**Comment by Emisse** [comment]
i swagged on it first

**Comment by Skarletto** [comment]
i died

**Pull request closed without merging**
