### PR TITLE
SMG Magazine Fix

### PR DESCRIPTION
**Pull request by Keer-Sar**
## About the PR

Changes all SMG magazine pointers to follow the organization of \Resources\Prototypes\Entities\Objects\Weapons\Guns

Fixes a naming mistake in SMG Uranium mags. It was labeled as a rubber mag before.

Changes standard .35 submachine mags to have 35 bullet capacity. For some reason only the standard SMG mags had 30 vs every other magazine holding 35 rounds.

Comments out redundant migrations in migrations.yml for SMGmagazines and Box of SMG magazines as to preserve its history.
## Why / Balance

Pistols and SMGs used to be hosted in one big yml file, making it difficult to scroll thru and differentiate between an SMG and a pistol. They were grouped together based on bullet caliber. Pistols in ss14 are very different from SMGs and need to have better organization than the current .yml sprawl that plagues magazines.
Also guns were reorganized a month ago but magazines do not follow their folder structure.

Changing .35 SMG mags to have 35 rounds instead of 30 will buff the C-20 bundle as well as security SMGs. This is a convenience buff as you could already have a 35 capacity magazine using the practice magazines or any variant that's able to be printed on a lathe.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

fix: The standard SMG magazines now hold 35 rounds to match the capacity in all SMG magazine variants.
fix: The uranium SMG magazine's name was fixed from rubber SMG magazine.

### CODE REVIEW

**Comment by Plykiya** [comment]
Are... are you uh... gonna fix the merge conflict?

**Comment by slarticodefast** [comment]
Are you coming back to this?

**Comment by JIPDawg** [comment]
Please come back to this 😭

**Comment by slarticodefast** [comment]
Well, let's hope someone picks this up.
If you want to continue working on it, leave a comment and I will re-open the PR.

**Pull request closed without merging**
