### PR TITLE
Croc Hat

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Adds the comically large croc as a random item that appears in maintenance lockers.

**Media**

 
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- add: Added the comically large croc, now found rarely in maintenance lockers

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Pretty sure Croc is a trademarked brand

**Comment by Alekshhh** [comment]
yeah probably

**Comment by deltanedas** [comment]
according to wikipedia, the free encyclopedia, crocs are a trademarked brand of "foam clogs"

**Comment by Alekshhh** [comment]
well shit

**Pull request closed without merging**
