### PR TITLE
buff syndicate assault borgs

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
see title
makes the L6 self-charge at 1 shot per 4 seconds and replaces the energy sword with a double energy sword
also removes the cobra since it had no reason to be there

## Why / Balance
right now, syndicate cyborgs are definitely too weak for their 65TC cost
borgs are supposed to be specialists and excel at specific tasks (perhaps better than the crew) while being bad at others, and the assault cyborg's niche is supposed to be combat, so i made it actually good at it
i believe having a self-charging L6 and a desword, which syndies and nukies normally can't obtain, is fine for it, since it's a borg; also see engiborgs and the advanced tools module with its self-charging RCD
i have also considered replacing the crowbar with syndicate jaws of life, but jaws are not a combat item, so i decided against it
the emag and crowbar should be kept because otherwise the borg has a very high chance of just getting stuck somewhere and can't operate alone

## Media

tested, trust

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- tweak: Syndicate assault cyborgs now get a dual energy sword and a self-charging L6.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
i feel like a Jaws of life would suit the assault borg really well because then he doesn't have to wait however long for the emag to charge if they get stuck in a room where they don't have access.

**Comment by Ilya246** [comment]
> i feel like a Jaws of life would suit the assault borg really well because then he doesn't have to wait however long for the emag to charge if they get stuck in a room where they don't have access.

in an emergency just desword a wall open, will take some time but will at least let you out

**Comment by Dutch-VanDerLinde** [comment]
wouldnt a desword be too powerful? how about just making the assault borgs more resistant to damage or give them an eshield or something, idk

**Comment by Ilya246** [comment]
> wouldnt a desword be too powerful? how about just making the assault borgs more resistant to damage or give them an eshield or something, idk

i explained why i consider it reasonable in the PR description, borgs are supposed to be specialists and be able to do their job really well at the expense of being able to do anything else
the assault borg's job is to deal damage, and 200 health is roughly how much a bloodred effectively has

**Comment by LicoKokos** [comment]
Неплохо

**Comment by MarakCM** [comment]
> > wouldnt a desword be too powerful? how about just making the assault borgs more resistant to damage or give them an eshield or something, idk
> 
> i explained why i consider it reasonable in the PR description, borgs are supposed to be specialists and be able to do their job really well at the expense of being able to do anything else the assault borg's job is to deal damage, and 200 health is roughly how much a bloodred effectively has

100 hp to crit, 100 hp to death.
So weak... Like a naked Urist.
Also borg... Flashing.

**Pull request merged**
