### PR TITLE
remove modular grenades from construction

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
nukes the modular grenades from construction, only ever used as a griefing method from Sci. this could be uplinked or something but this is a lazy webedit PR

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
for the record this only removes the construction graph, nukies should spawn with 1 or 2 modular grenade bases for their shenanigans

**Comment by Zumorica** [comment]
> for the record this only removes the construction graph, nukies should spawn with 1 or 2 modular grenade bases for their shenanigans

FYI what you removed isn't a construction graph, it's a construction recipe prototype

**Comment by Just-a-Unity-Dev** [comment]
oh god damn it

**Comment by mirrorcult** [comment]
i don't think this is a good step and it seems broadly unpopular

**Pull request closed without merging**
