### PR TITLE
Lawdrobe update

### PR DESCRIPTION
**Pull request by beck-thompson**
## About the PR

Some basic changes to the Lawdrobe.

## Why / Balance

The lawdrobe was, overall, pretty dull so I added a few new things that greatly improve its role play potential!
## Technical details

- Added 5 new advertisements.
- Added 5 new thank you messages.
- Added Luxury Pen to Lawdrobe 2x.
- Added Judge robe and Hair to contraband.
- Added 100 space cash to contraband Inventory 2x.
## Media

[Meda.webm](https://github.com/space-wizards/space-station-14/assets/107373427/2d774ba3-1aaf-467c-b4e0-eac903e98a1a)

**Changelog**

:cl: Beck Thompson
- add: Lawdrobe has some new items and new ads!

### CODE REVIEW

**Comment by beck-thompson** [comment]
Hey! Obviously failing all those checks is probably not good at all :laughing:
I'm not quite sure what I did wrong so I would love if someone could give me some more information :)

**Comment by mirrorcult** [comment]
uhh, test fail looks like gh's fault, not yours

**Comment by beck-thompson** [comment]
OK great thanks for the info! Got worried I totally screwed up somehow :laughing:

**Comment by potato1234x** [comment]
why the soap

**Comment by beck-thompson** [comment]
For removing evidence! The CyberPen is obviously for forging documents so I thought adding soap to remove evidence would also be a good complement.

**Comment by potato1234x** [comment]
but you can just find soap in bathrooms its one of the more common items

**Comment by beck-thompson** [comment]
That's totally fair and if you think I should remove it I totally will. It is only for flavor purposes because, like you said, soap is relatively easy to find.

**Pull request merged**
