### PR TITLE
Make midround zombie outbreaks much rarer

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Midround zombie outbreaks now only have a 1/651 chance to occur every event tick, nearly 4x less likely than before.

## Why / Balance
Zombies happen way too often for what they are. Zombies are a midround antagonist that is not just snowballing, but guaranteed round-ending. Whether or not the crew wins against them, the shuttle needs to come regardless because chances are half the crew was round removed from the infection and there's no way to undo it. As well as the fact that zombies convert all otherwise interesting antagonists into the same exact shambling corpses, the only exception being the space dragon which just becomes outright overpowered when infected.
Currently, almost every single survival round ends in zombies. Playing an enjoyably chaotic shift or a story caused by some antagonist and then having it almost always entirely cut off by a consistently unfun midround event SUCKS, and 9/10 survival rounds end with zombies so as soon as you realize it's survival you're just waiting for the moment you hear "eeuurrghh" and biting sounds in the medbay.

**Changelog**

:cl:
- tweak: Zombie outbreaks are now SIGNIFICANTLY rarer

### CODE REVIEW

**Comment by DieselMohawk** [comment]
I agree that it's pretty bullshit.

**Comment by vorkathbruh** [comment]
maybe survival will actually be fucking bearable

**Comment by deltanedas** [comment]
major cargo skill issue just buy 50 guns

**Comment by deepdarkdepths** [comment]
I don't like this. Zombies are already irrelevant enough as is. Roundstart II is incredibly easy to shut down most of the time and this just gives less chances for takeovers to happen
Chaos is inevitable.

**Comment by slarticodefast** [comment]
Maybe it would be fine if it is just much rarer? Like 10% of the current chance? For me midround IIs happening was always the game telling me "this round has been long enough, time to end it". I totally agree this should not happen every time in survival mode, each round should feel unique and different.

**Comment by a-person5660** [comment]
Zombies need to be reworked or rebalanced, right now it's "oh the entire station is infected, time to /ghost and wait for 10 minutes for the shuttle"
They should be removed from mid round until they get that rebalancing. I'm usually against removing stuff but this is truly the only thing that really needs to go.

**Comment by deltanedas** [comment]
cargo buying 50 guns means the entire crew is armed not 6 people

**Comment by Ilya246** [comment]
i would suggest to instead just make them even rarer than they are now, maybe additionally also make them only potentially happen even later into the round
and maybe give cargo better zombie countermeasures they can purchase so if cargo has money they can basically just buy zombies away

**Comment by Radezolid** [comment]
> > the actual solution isnt make it rarer its make dynamic so how a round ends is actually considered and not just a completely random event
> 
> Oh yeah sure let's just keep this extremely unfun feature in the game for god knows how long until someone steps up to code a doc for an entirely new gamemode that was merged to docs 9 months ago that will just replace the YML being removed here anyway.

It's unfun for you maybe, I think zombies outbreaks are fun.

If cargo can't get guns fast enough that sounds like a skill issue. They got common radio, the QM can even work with command (Like he should do) to coordinate to contain this.
I dont see how removing this event would help, remember that space station 14 includes chaos, removing zombies because they cause it would be against the idea of this game in my opinion.

**Comment by Froffy025** [comment]
radezolid, this pr just removes zombies from midround events. zombie rounds will still be zombie rounds -- this PR just changes it so that survival/traitor rounds are always about surviving events/surviving traitors, instead of ever being about surviving the inevitable midround zombies.

**Comment by IProduceWidgets** [comment]
There might be a solution to this particular case without this, but it sure would be easier to handle with #29320

**Comment by Emisse** [comment]
cant you just lower the weighting

**Comment by BuggsWorth** [comment]
In my almost 600 hours playtime majority being on wizards den, ive seen mid round Zombies almost as often as ive seen Rev's, even on Survival.

Theyre designed to be round ending like nukies, but if the crew can work together it can be easily quelled. If theyre spawned at the end of a survival round where people cannot properly coordinate, thats just part of the chaos the game creates that we love so much.

I wouldnt remove them completely, maybe tweak the weighting if you want to change anything. Not to cause any offense but this seems like something made out of spite.

**Comment by Ilya246** [comment]
yes i already suggested this just make them happen at minimum an hour in and rarer than they do now

**Comment by BuggsWorth** [comment]
> yes i already suggested this just make them happen at minimum an hour in and rarer than they do now

Its an amazing idea having a minimum amount of time required to roll midround zombies so the crew has enough time to have their fun and roleplay, an hour in is right on time for the shift to start becoming stale.

**Comment by IProduceWidgets** [comment]
You can set the minimum time for the event in yml.

**Comment by TheDoctor1977** [comment]
My personal issue with midround zombies is that it’s just a big middle finger to almost every other midround antag. Sleeper Agents, Lone Ops, Space Dragons, they all get turned into zombies with the exact same goal.

**Review by metalgearsloth — DISMISSED** [review]
Talked with maints and consensus was just make it a round 1 hour earliest start + reduce the weighting a bit.

**Review by UbaserB — CHANGES_REQUESTED** [review]
After further internal discussion, please change the `earliestStart` to be 90 minutes in and the `weight` to be 1.

**Comment by UbaserB** [comment]
I just ended up doing it myself, will merge after tests finish

**Review by UbaserB — APPROVED** [review]

**Pull request merged**
