### PR TITLE
Implement Charcoal. #10042

### PR DESCRIPTION
**Pull request by WPRobson**
## About the PR
Relates to #10042
Adds charcoal into the game. Charcoal will remove other chemicals from the players chemical solution at a rate of 3u per tick, but is provided as a data-field so can be adjusted later in the chemicals prototype json. Also heals poison damage at 1 per tick. Charcoal will not remove itself from the chem solution and will be metabolized normally.

**Changelog**
:cl: WPRobson
- add: Added charcoal into the game. Heals poison damage and removes chemicals from the bloodstream

### CODE REVIEW

**Comment by Visne** [comment]
I kinda don't see why charcoal and carbon should be seperate things

**Comment by WPRobson** [comment]
The effect could be easily moved to carbon if decided that is better @moonheart08 originally created that issue maybe they have something to say about it?

**Comment by moonheart08** [comment]
Charcoal is a separate thing but it also shouldn't be directly dispensable. Do we have ash yet? If yes, recipe should be ash + carbon, if no i'll think of something in a bit.

**Comment by WPRobson** [comment]
Looks like we do have ash. Or at least I saw spawn it in a dev environment. So I can remove it from the dispenser and make it into a recipe

**Comment by WPRobson** [comment]
although saying that #10373 looks like it was meant to provide a way of easily making ash and that's not merged yet

**Comment by EmoGarbage404** [comment]
> Looks like we do have ash. Or at least I saw spawn it in a dev environment. So I can remove it from the dispenser and make it into a recipe

we have ash as an entity. It's gotten from crematoriums. Ideally, there'd be a better way of acquiring it.

**Comment by WPRobson** [comment]
@moonheart08 Should ash now be addable to beakers directly, so that it can be fed into the chem master? or should it be something like using the grinder to grind the ash into a beaker like plasma?

**Comment by moonheart08** [comment]
> @moonheart08 Should ash now be addable to beakers directly, so that it can be fed into the chem master? or should it be something like using the grinder to grind the ash into a beaker like plasma?

Addable directly. Look at how eggs work I think?

**Comment by WPRobson** [comment]
@moonheart08 Ok finally figured out how to get the new recipe working and make it so ash can be spiked and used

**Pull request merged**
