### PR TITLE
Good Intercoms

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Ike is finally off my ass because i did the shit i needed to.

**Media**

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Intercoms now have a menu for selecting the channel, toggling the microphone, and toggling the speakers.
- add: Intercoms now come with speakers, which allow you to hear what people are saying.
- tweak: Radio speakers are now much quieter, requiring you to stand next to them to make out what they're saying.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
ok apparently i commited on this branch by accident, so that's fun

**Comment by EmoGarbage404** [comment]
All fixed: ready for review

**Comment by deltanedas** [comment]
> add: Intercoms now come with speakers, which allow you to hear what people are saying.

sec will be trolled hard by tiders sitting at the intercom and repeating everything on common

**Comment by lzk228** [comment]
so big button

**Comment by Emisse** [comment]
fuck it we run it live

**Comment by hord-brayden** [comment]
> > add: Intercoms now come with speakers, which allow you to hear what people are saying.
> 
> 
> 
> sec will be trolled hard by tiders sitting at the intercom and repeating everything on common

I literally came here to say this, but that's more of a perk in my book. Reminds me of pirate radio - "You can't stop the signal!"

Query: would they have to parrot everything if they just put 2 intercoms keyed to different channels, right next to each other?

**Comment by EmoGarbage404** [comment]
> Query: assuming they work like handhelds: would they have to parrot everything if they just put 2 intercoms keyed to different channels, right next to each other?

No. Radio code already handles this.

**Pull request merged**
