### PR TITLE
dragon refactor, objectives and use GenericAntag

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR

refactor dragon code a good bit

only ingame changes should be:
- dragon briefing in character menu
- objectives to charge 3 carp rifts and survive

depends on #20186 and #20394

## Why / Balance
better greentext than pitiful "space dragon (123) (username) was a dragon with X rifts" also properly tracking rifts incase of dying, let people know how many rifts there were before death
if a rift is destroyed it is intentionally reset to 0.

## Technical details
- moved rift stuff except spawning action into `DragonRiftSystem`
- made said system use api in `DragonSystem` to do things instead of directly modifying it
- cleaned things up a lot but sadly still using accumulators since the logic isnt as simple as a timespan

## Media
look at him go

1 rift didnt charge...

blue rift

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
maybe?

**Changelog**
:cl:
- tweak: Space dragons get a proper greentext in the round end summary, along with objectives in the character menu.

### CODE REVIEW

**Comment by mirrorcult** [comment]
blesd

**Comment by deltanedas** [comment]
merg

**Review by mirrorcult — APPROVED** [review]

**Comment by KingOnBudget** [comment]
The carp summoning task will probably encourage dragons to spawn carps outside of the station where its harder to get to and easier to defend but this issue probably is outside of this PR.

**Comment by deltanedas** [comment]
pretty sure you arent able to spawn rifts outside

**Pull request merged**
