### PR TITLE
Let recyclers grind up people

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

they can't grind up alive people unless emagged, dw.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Emagged recyclers grind people again.

### CODE REVIEW

**Comment by Emisse** [comment]
i feel like this should do dmg over time instead of instagibbing, lest the nightmares return

**Comment by EmoGarbage404** [comment]
NIGHTMARE NIGHTMARE NIGHTMARE NIGHTMARE

**Comment by Emisse** [comment]
uh actually i hate the playerbase

**Comment by deltanedas** [comment]
so if i just wall up disposals and emag the grinder then turn it on it will instagib anything that gets flushed? fishtrap 2.0?

**Pull request merged**
