### PR TITLE
death to crlf

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
dox2unix everything

## Why / Balance
wyci

## Technical details
no

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by mirrorcult** [comment]
gonna go ahead and say this is not worth it

**Comment by VasilisThePikachu** [comment]
https://github.com/space-wizards/space-station-14/pull/25841

> A proper fix for this issue would be:
> 
> A PR to fix all existing CRLF files in the repo to be LF.
> A CI check to block future CRLF files.
- PJB

This does 1 out of 2 fixes

**Comment by botanySupremist** [comment]
WHY ARE THERE 734 CHANGES

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This PR isn't just removing CRLF, it's also nuking BOMs at the top of every file, which is a completely different issue.

**Comment by deltanedas** [comment]
dos2unix did it, and it would mean 700 out of 1.7M lines diff so its negligible

**Comment by PJB3005** [comment]
> dos2unix did it, and it would mean 700 out of 1.7M lines diff so its negligible

I don't care. Having a larger file diff is still annoying.

**Review by PJB3005 — APPROVED** [review]

**Comment by deltanedas** [comment]
<ins>/!\\</ins>

**Pull request closed without merging**
