### PR TITLE
ammo fill sound because i forgor

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
i thought it already did it but it didnt
this will only work when audio netentity stuff is done, a lot of sounds are broken currently

## Why / Balance
good

## Technical details
no

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Partmedia** [comment]
Is this still a draft?

**Comment by deltanedas** [comment]
idk if the sound was made to work yet :trollface:

**Comment by Partmedia** [comment]
Do you want to test this? Otherwise I'll go ahead and close this.

**Comment by deltanedas** [comment]
i broke branch locally anyway

**Pull request closed without merging**
