### PR TITLE
Hivelord mob

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds hivelords, a new mob that spawns on the mining asteroid. Currently, spawning is 60/40 between goliaths and hivelords.

Hivelords are fairly weak (75 health) and don't have a direct attack. However, they can spawn minions that are extremely weak (5 health) and swarm the player dealing low melee damage (7). Hivelords also move quite quickly meaning that they're a bit hard to catch up to.

Butchering a hivelord will drop a hivelord remains, which is a food item that heals brute damage and gives the "adrenaline" status effect, which causes all damage slowdown to be nullified while active. The remains become inert and useless after 2 minutes.

## Why / Balance

Adding variety to the mob pool is always a good thing. Goliaths are really tanky and require ranged attacks to fight effectively, which makes hivelords an interesting counter due to their swarms and high numbers being very strong against ranged attacks. This means that they are more of a melee option, as wideswings and high attack rates allow you to quickly dispatch the minions.

## Media

https://github.com/user-attachments/assets/418374e7-59cb-42f8-964e-2319942ccbc2

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the hivelord! This self-replicating alien is found on the mining asteroid. It's core is known to have powerful healing properties.

### CODE REVIEW

**Comment by Zalycon** [comment]
This is cool and all but isn't Adrenaline the same chemical compound as epinephrine? Which already exists.

**Comment by EmoGarbage404** [comment]
> This is cool and all but isn't Adrenaline the same chemical compound as epinephrine? Which already exists.

i mean the chemical isn't called adrenaline just the status effect. the chem inside the hivelord remains is called "rororium"

**Comment by sad2284** [comment]
Steeply! New mobs that are not immortal machines for annihilating the living are always cool and interesting.

**Comment by whateverusername0** [comment]
this is like lavaland but not lavaland.

also why don't make adrenaline a part of the emergency medipen? because right now it's kinda useless since it heals only while crit.

**Comment by FaDeOkno** [comment]
I don't really understand what is this thing exactly

**Comment by whateverusername0** [comment]
> I don't really understand what is this thing exactly

it spawns shitlings when you hit it that damage you

**Comment by whateverusername0** [comment]
also it's remains could be generalized for other mobs that are planned to be added, just in case you'll ever decide to make legions real

**Comment by Carolyn3114** [comment]
we have legion at home

**Pull request merged**
