### PR TITLE
Create ASTROID

### PR DESCRIPTION
**Pull request by rithikxxxxxx**
UHFIUSGFIUDGFIJSHIGIFIGG IUHG UHFIHIGFNIUFIFIUHFIGFGGFFUYGUYGYGFYUYYUYGUYUYUYUYUYFUYUYUYUYDUYGDUYDUYGDUYGDUYDYGUYGFUYGFJH UY SUYDGFU T BINSGUYB USGYFIF8YS8YFAIB IU IUNFY89  YERH GEHFVFBWRIUGFSFIF U IURIBFGWJDBH GKJ NFEYI IN  SGIUH UHFNFIU IUJFB HI HBFSIB J TTJJD RTUHISBIS STHE F HWFNH8 H UHUHF  HIUHF FJNVIHK  UHD FJ N FI J NERGNIUHJF

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Simyon264** [comment]
What?

**Comment by SoulFN** [comment]
Why wont you merge it?

**Comment by Errant-4** [comment]
> Why wont you merge it?

Merge _what_, exactly

**Comment by SoulFN** [comment]
> Merge _what_, exactly

This PR, it's very cool

**Comment by Simyon264** [comment]
What does the PR add? What is there to merge?

**Comment by deltanedas** [comment]
troll pr

**Comment by K-Dynamic** [comment]
:trollface: 

Only recourse is to make a proper asteroid pr out of spite

**Pull request closed without merging**
