### PR TITLE
Railings

### PR DESCRIPTION
**Pull request by StanberyTrask**
## About the PR 

Adds railing for stages and queues. they can be vaulted and you can toss things over them to throw tomatoes at the clown

**Screenshots**
Screenshot from 2021-12-09 01-51-58

**Changelog**

:cl: StanberyTrask
- add: added railing sprites, prototype, and construction graph

### CODE REVIEW

**Comment by metalgearsloth** [comment]
> constriction graph

**Review by mirrorcult — APPROVED** [review]
fix changelog and g2g

**Review by ElectroJr — APPROVED** [review]
Ditto

**Comment by StanberyTrask** [comment]
No more constriction graph

**Pull request merged**
