### PR TITLE
Immersive fight (frozen, waiting for a programmer)

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

This PR is not finished yet: it is a preview of what can be done if people like it. In case of good ratings and approval of the maintainers, I will finish the PR.

This PR is designed to remove the boring white stick with wide melee attacks. Instead, each weapon will have its own attack sprite.
Also, given that the dagger attack sprites are clearly shorter, they have reduced the attack distance. This will require reworking the weapon balance

## Why / Balance

More visual aesthetics

## Technical details

no code changes

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/8ff395a2-6915-45a0-ab70-366bbccd0798

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: In melee, a wide attack now displays the type of weapon used

### CODE REVIEW

**Comment by brainfood1183** [comment]
awesome.

**Comment by CatMagic1** [comment]
Awesome! I imagine this will make range more obvious.

**Comment by EmoGarbage404** [comment]
These should probably just use the icon sprites instead of implementing a bunch of extra weapon arc sprites.

**Comment by TheShuEd** [comment]
Then you will decide among yourselves how it should work. I will stop drawing sprites for the PR for now

**Comment by TheShuEd** [comment]
@CatMagic1 yep. But it requires programming. I would highlight the following things that need to be done: 
- Alternating strokes from left to right and from right to left. 
- Ability to adjust the animation speed. 
- The ability to adjust the range of animation from the player. 

I hope that someone will do this in a separate PR, because I could not figure out the code of the melee weapon system

**Comment by TheShuEd** [comment]
According to the decision of the maintainers, this PR is considered interesting, but the implementation is not optimal. It was decided that this mechanic should automatically use the melee weapon icon. 

## Someone else has to do it.

**Comment by TheShuEd** [comment]
Considering that this project has waited for a great programmer, I'm closing this PR.
#21050

**Pull request closed without merging**
