### PR TITLE
Added salvage magnets to T3 civilian tech.

### PR DESCRIPTION
**Pull request by magmodius**
## About the PR
Adds the salvage magnet board as part of Bluespace Cargo Transport.

## Why / Balance
Made to give cargo a way to rebuild the salvage shuttle. Also done to give constructed shuttles a practical purpose.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- add: The Bluespace Cargo Transport tech now also includes salvage magnet boards.

### CODE REVIEW

**Comment by mirrorcult** [comment]
this is quite good i think

**Comment by Aisu9** [comment]
the magnet as T3, one of the vital part of salvage?
remember the magnet is a round start construct, by making this a Research-only item every map should have their magnet removed

**Comment by magmodius** [comment]
> the magnet as T3, one of the vital part of salvage? remember the magnet is a round start construct, by making this a Research-only item every map should have their magnet removed

why should this change it to research only? there are plenty of maps that have roundstart boards/items that you can research later. it would not and should not remove anything. this is just as an emergency or if your science team has been running for a particularly long shift and want to create a mining vessel.

**Comment by mirrorcult** [comment]
> the magnet as T3, one of the vital part of salvage? remember the magnet is a round start construct, by making this a Research-only item every map should have their magnet removed

you cant create more salvage magnets, its an extremely rare machine. letting you duplicate them and have more salvages spawning is a pretty big boon

**Comment by Aisu9** [comment]
> > the magnet as T3, one of the vital part of salvage? remember the magnet is a round start construct, by making this a Research-only item every map should have their magnet removed
> 
> you cant create more salvage magnets, its an extremely rare machine. letting you duplicate them and have more salvages spawning is a pretty big boon

but isn't this one of the rules of mapping "never map admin items or available from research"?

**Comment by mirrorcult** [comment]
literally who cares, do you think we're bound by that by divine means and we cant deviate from it when it makes sense

**Comment by icekot8** [comment]
why?.. for example... you could make the magnet indestructible or something, instead of sticking a magnet in the service branch..... it's just a small band-aid on a huge cut in logic.. i don't like this band-aid.

**Comment by Varen** [comment]
Keep in mind, salvage magnets are tied to the station in terms of recharging etc. Having multiples will not serve any functional purpose, so this merely adds a way to replace destroyed ones.

**Comment by Nimfar11** [comment]
Can two or more magnets work properly? They don't seem to be able to work separately from each other.

**Comment by Kadeo64** [comment]
I don't think this needs to be in civilian tech considering shuttlecraft and salvage equipment is in industrial. Civilian tech is for cargo, Industrial is for salvage. I also think it's too niche to be a tier 3.

**Comment by deltanedas** [comment]
if you could have multiple wrecks at the same time it would be t3 op gaming buy i dont see why you should have to lock a server into one of the worse trees just to repair salv

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
Magnets would need to be changed to be semi-station independent. As is, you are basically making the most expensive repair kit.

**Comment by Kadeo64** [comment]
> if you could have multiple wrecks at the same time it would be t3 op gaming buy i dont see why you should have to lock a server into one of the worse trees just to repair salv

also thistbh I discussed this in general last night but civilian has like 4 good researches and the rest are either super situational or just plain bad. It has one of the best tier 3s but the researches you unlock in the process make it not worth it, where something like industrial has both great tier 1 and tier 2 so the tier 3 is that much more fun to unlock

**Comment by magmodius** [comment]
> magnet spawning tied to station atm

i see. in that case, this is practically worthless. probably should tested that first, that one is mb.

**Pull request closed without merging**
