### PR TITLE
Fix ninja not being able to use abilities

### LINKED ISSUE #23688: Ninja abilities don't work
## Description

When trying to use ninja abilities that cost power they do not work, instead a popup appears saying that the ninja suit does not have enough energy, this occurs at any charge rate from 0% to 100%

Ninja gloves still work.

**Reproduction**

1. Spawn in as a ninja
2. Attempt to use cloak/throwing star/katana teleport
3. Get trolled and go murderboning instead.

**Screenshots**

none

**Additional context**

First reproduced on wizden leviathan at round #43231, the ninja was mostly active on the northern side of the station starting from 40(?) minutes.

I was not playing since roundstart or latejoined, I started as an observer.

### PR DESCRIPTION
**Pull request by Costyyy**
## About the PR

Added missing UseDelay component to ninja
## Why / Balance

Ninja wasn't able to use some of its abilities.
Fix #23688
## Media

https://github.com/space-wizards/space-station-14/assets/48994982/28ce53a6-fa9f-4f10-b952-cb7026837b08

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- fix: Ninja not being able to use some abilities.

### CODE REVIEW

**Comment by deltanedas** [comment]
why was it not on mobhuman

**Comment by Costyyy** [comment]
> why was it not on mobhuman

Not sure. Is it supposed to be there?

**Comment by EmoGarbage404** [comment]
this is not the correct solution to the issue. The code should be checking a use delay on some kind of item, not the player. The code needs to be fixed to check the correct entity instead of just adding the component to the mob itself.

**Comment by deltanedas** [comment]
no its intentionally checking delay on the user so all abilities are disabled by being attacked while cloaked

**Comment by EmoGarbage404** [comment]
> no its intentionally checking delay on the user so all abilities are disabled by being attacked while cloaked

that is super fucking weird

**Comment by deltanedas** [comment]
maybe i could replace with a component that has a timespan for the delay and a timespan for when the delay is over :trollface:

**Comment by Costyyy** [comment]
So, should the code be changed to have the timer on the armor instead of the mob or should the component be moved to MobHuman?

**Comment by AJCM-git** [comment]
> So, should the code be changed to have the timer on the armor instead of the mob or should the component be moved to MobHuman?

Yeah UseDelay wasnt made for this, the best solution would prob be not using it at all and just adding a timespan to the suit component that updates when the ninja takes damage and checking that where there are `UseDelay.IsDelayed` checks or something like that. I'll see if i can do it

**Comment by Costyyy** [comment]
> > So, should the code be changed to have the timer on the armor instead of the mob or should the component be moved to MobHuman?
> 
> Yeah UseDelay wasnt made for this, the best solution would prob be not using it at all and just adding a timespan to the suit component that updates when the ninja takes damage and checking that where there are `UseDelay.IsDelayed` checks or something like that. I'll see if i can do it

Alright, I'll close this PR then

**Pull request closed without merging**
