### PR TITLE
Nukeops role restrictions revival

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
revival of #17929

- just 25h playtime

depends on #20108

## Why / Balance
good

## Technical details
no

## Media
(no more sec so outdated)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl: VigersRay
- tweak: The syndicate has begun to recruit more experienced people into the ranks of nuclear operatives.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
The salv, sec, and command playtime is dumb. Just make it an overall time requirement only.

**Comment by LankLTE** [comment]
Playing specific roles has really no set relevance to nukies (especially salvage wtf), I agree it should just be overall playtime. I wouldn’t mind commander having like 30 mins of nukie just to confirm you’ve played it at least once, but I don’t think that’s possible atm

**Comment by deltanedas** [comment]
> Playing specific roles has really no set relevance to nukies (especially salvage wtf), I agree it should just be overall playtime. 

i just did that :trollface:

> I wouldn’t mind commander having like 30 mins of nukie just to confirm you’ve played it at least once, but I don’t think that’s possible atm

i would too but antag playtime isnt tracked and im pretty sure it would make nukies impossible since:
- nobody has nukie playtime tracked
- nobody can be commander
- nukies cant start
- nobody can gain nukie playtime

if it were implemented it would require tracking playtime for a good while beforehand

**Comment by Equivocateur** [comment]
> nobody can gain nukie playtime

Pull a goonstation

* Track if a user had a win as nukie
* Prioritize them as commander
* Otherwise pick commander at random from 5

I'd bikeshed into axing having "commander" as a separate opt-in tbqh.

**Comment by deltanedas** [comment]
some people might still not be comfortable being commander after just 1 win though, perhaps picking the commander from most wins rather than just having at least 1

**Comment by crazybrain23** [comment]
Mentioning #14711 just so we have a connection to it. (To close it, there would also need to be a nukie playtime tracker.)

**Review by crazybrain23 — APPROVED** [review]
I don't see how this could be improved without adding antag playtime tracking in order to restrict nukie commander behind operative.

**Comment by mirrorcult** [comment]
reduce the playtime required to 5h

**Review by mirrorcult — CHANGES_REQUESTED** [review]
above

**Comment by Equivocateur** [comment]
> reduce the playtime required to 5h

5h is when people realize the antag tab exists, this solves nothing.

A new player in their first 5 hours is too busy figuring out how right click in combat mode works in melee, while nuclear operatives require you knowing:

- How to use an uplink
- What to buy
- How to operate a gun (bolt, reloading)
- Belt slot
- How to use a jetpack
- How does combat work exactly
- How space works
- - Movement in no-grav
- - Space wind
- - Pressure damage
- - Spacing
- The station
- Figuring out what a pinpointer does
- Stuns
- - Slip combat included, because slipping stamcrits
- Counters for common security strategies
- Communication channels (":t" is esoteric knowledge for newkies)
- Illicit access (by emag or hacking)

Setting it to 5 hours only prevents someone who just installed the game from having a crucial role in a round or, as a consequence, and not awful rounds because 4 out of 5 people on the nuclear operative team barely navigate around a vending machine menu let alone an uplink store against 75 crew members, half of which armed to the teeth because the commander thought it would be funny to warop.
image


You can reasonably figure out or experience the things listed above in 25 hours of playtime at which point you stand a fighting chance.

P.S. To be a cadet you're required **10 (Ten) hours** of playtime, a security **cadet**.
https://github.com/space-wizards/space-station-14/blob/66307df9702543987fc09d7f23091ff3350557f3/Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml#L8

**Comment by deltanedas** [comment]
> reduce this to meme number
> ok i reduce
> not merge

**Comment by Partmedia** [comment]
> > reduce this to meme number
> > ok i reduce
> > not merge

Sorry, our fault, if this happens again remember to give us a ping.

**Comment by lzk228** [comment]
no more "guys what is uplink"
lessgooo

**Pull request merged**
