### PR TITLE
apc touchup sprite

### PR DESCRIPTION
**Pull request by Emisse**
image
BEFORe

image
AFTER

made bortrers on the sprite so the screen isnt outlined in black annoy me

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Definitely better. Can you make them rotate again? It was more clear before which room they were in.

**Comment by Emisse** [comment]
no the rotated wallmounts look bad i wanna convert everything to this method

**Comment by IamVelcroboy** [comment]
😟

**Comment by EmoGarbage404** [comment]
could you make the borders a touch darker? or potentially not expand the screen border but instead just lighten up the black outline and make the sides a lighter color?

**Comment by Emisse** [comment]
updated

**Review by EmoGarbage404 — APPROVED** [review]

**Pull request merged**
