### PR TITLE
Reworked sprites, inhands and new melee weapons

### PR DESCRIPTION
**Pull request by TaralGit**
Anyway, for now I replaced the icon of the combat knife with something smaller and reworked the inhands for the fireaxe. 
The machete, baseball bat and captain's saber will be coded and added tomorrow.

Final Update: Added a proper changelog

🆑

-add: baseball bat, machete, captain's sabre and katana.

-fix: smaller combat knife icon, inhands for fireaxe, Olivaw pistol and WT-550 smg.

Screenshot 2021-04-01 062532-v6
*the kitchen knife is just for comparison 

Screenshot 2021-04-08 062449-before
*olivaw and wt inhands before. the both had the cr20r inhands

Screenshot 2021-04-09 032814-afterv2
*after.

### CODE REVIEW

**Comment by TaralGit** [comment]
Ok, I'm done with this PR.  
All four checks are completed, everything is where it's supposed to be. Still, if there's anything wrong just let me know.

**Comment by metalgearsloth** [comment]
What's wrong with the existing inhand sprites?

**Comment by SweptWasTaken** [comment]
> 
> 
> What's wrong with the existing inhand sprites?

I didn't see he did the inhands, he needs to post screenshots of what they look like.

**Comment by TaralGit** [comment]
> What's wrong with the existing inhand sprites?
> 
> Also changelog doesn't look like it's the right format.

Ok. I corrected the changelog and added screenshots.

**Comment by SweptWasTaken** [comment]
I like the inhands very much, they look great. The katana looks good + the sword but the bat and machete look bad.

If you remove the machete and bat i'll merge this.

**Comment by TaralGit** [comment]
> I like the inhands very much, they look great. The katana looks good + the sword but the bat and machete look bad.
> 
> If you remove the machete and bat i'll merge this.

ok, removed them. didn't cared too much about the bat but I will try to improve the machete in a next PR.  any suggestions to improve it?

**Pull request merged**
