### PR TITLE
Adds a bunch of UI icons for verbs.

### LINKED ISSUE #2993: We need verb icons.
Right now only a few verbs like rotate/debug have actual icons, but the system does support it.

Adding icons massively improves usability, so somebody should uh, get on that?

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Closes #2993 

Adds a bunch of icons for all the verbs in-game. Most of these are currently from freeicon, whose attribution standards are dogshit and i'll be replacing them with ones from thenounproject and hopefully some made by community members.

This is a draft PR to show i'm working on this.

**Screenshots**

**Changelog**

:cl: Swept
- add: Added icons for a bunch of verbs

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Ready for review. 

I removed all the non-public domain icons which made hunting for GOOD icons pretty hard. I've filled out around 80% of the stuff with missing icons. 

If you were gonna make any custom icons, we need some for cuffing/uncuffing, pulling, pickup and a few others.

I've included a folder with some more icons I picked out from the original source, as I think they'll be used in the future for something.

**Comment by SweptWasTaken** [comment]
I'm happy with this PR right now. Everything looks good and i've gone through and replaced all the wonky SVGs. These SVGs are black instead of white but they look fine.

devenv_2021-03-08_14-34-44
Content Client_2021-03-08_14-33-59

Here are pictures of the current state of the icons. This isn't meant to be an exhaustive PR, I just want to get this one in particular closed.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
`vv` and `upstairs` are still PNGs

**Comment by SweptWasTaken** [comment]
> 
> 
> `vv` and `upstairs` are still PNGs

Fixed.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
All your SVGs are incorrect sizes and your exports are not actually 96 DPI as claimed. They should all be resized so that the SVG is 1:1 with the exported images at 96 DPI.

**Comment by SweptWasTaken** [comment]
> 
> 
> All your SVGs are incorrect sizes and your exports are not actually 96 DPI as claimed. They should all be resized so that the SVG is 1:1 with the exported images at 96 DPI.

Bah, it looks good in-game to me if you want this fixed someone else do it bc i'm done with this PR.

**Comment by PJB3005** [comment]
The problem is the adaptive resize. You should have made it so that the whole page of the SVG export is the actual image exported (at 96DPI). This is so that somebody in the future doesn't have to guess the export parameters when modifying the file.

**Review by PJB3005 — APPROVED** [review]
I cleaned it all up, christ this was a mess.

**Pull request merged**
