### PR TITLE
Reduce synaptizine damage

### PR DESCRIPTION
**Pull request by Eden077**
## About the PR

I changed the damage values of synaptizine from 3 to 1

## Why / Balance

This was done considering synaptizine is a hyperlethal poison that can do around 90 poison damage with just 15u's, synaptizine does this through doing 3 poison every 0.5u's.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
 
:cl:
- tweak: Synaptizine now deals less poison damage.

### CODE REVIEW

**Comment by UbaserB** [comment]
Can you nerf it to 1u of damage but then make the recipe a lot harder to make? As it currently is, and even more with this change; it is very powerful for negating stun damage.

**Comment by Eden077** [comment]
Do feel free to change the recipe but currently I only have the time and focus to change how much damage it does currently

**Comment by Eden077** [comment]
But yes I will change it to 1

**Comment by Eden077** [comment]
Pretty sure my dev enviroment or PC is having a stroke, bear with me

**Comment by Eden077** [comment]
My dev environment isn't dying! _**Thank fuck**_

**Comment by Eden077** [comment]
Oh for fucks sake, everytime...

**Comment by Partmedia** [comment]
Could you please provide a bit more context and discussion for why you're making this change? For example, is synaptizine currently being overused/abused? If not, it is okay for some poisons to be very strong. Keep in mind that solution containers like food do not contain much room for chemicals, and nerfing it too hard would make some forms of sabatoge/poisoning too difficult.

**Comment by thebadman4662** [comment]
They are nerfing the drawback of it as combat drug, if you want to make poison there is plenty of better ones or easier to make for 3dmg/tick. You basically need Dip/Sed mix to use synapzine and with limited carbon I wish you luck with that, especially when you can make meth instead which will also buff your speed.

**Comment by UbaserB** [comment]
> Could you please provide a bit more context and discussion for why you're making this change? For example, is synaptizine currently being overused/abused? If not, it is okay for some poisons to be very strong. Keep in mind that solution containers like food do not contain much room for chemicals, and nerfing it too hard would make some forms of sabatoge/poisoning too difficult.

It was abused as a poison because despite being really cheap; it did a lot of damage very quickly (i think 15u is enough to crit someone) and is on the difficulty scale to produce as dylovene.

**Comment by Arendian** [comment]
This chem currently deals the same damage as unstable mutagen, which is also extremely easy to make, so as a poison it's damage is on the same level as a comparable one.
I also don't see why a chemical that's basically desoxyephedrine without the speed boost(both reduce stun and knockdown by 3s every 0.5s), and is also really easy to make, should be able to be outhealed by just injecting an equal amount of dylovene.
Lowering the damage to 1 every 0.5 seconds will basically make it so chemist traitors won't be able to be cuffed, without any downside or significant time investment.

**Comment by Partmedia** [comment]
> They are nerfing the drawback of it as combat drug

Thanks, this was the context that I was missing.

> It was abused as a poison because despite being really cheap

Combined with this, I think this makes a lot of sense.

**Review by Partmedia — APPROVED** [review]

**Comment by Eden077** [comment]
> I don't think the change is the correct way to balance Synaptizine because of the following reasons:
> 
> * Synaptizine currently deals the same damage as unstable mutagen(6/u), which is also extremely easy to make, so as a poison it's damage is on the same level as a comparable one.
> * Synaptizine is basically desoxyephedrine without the speed boost(both reduce stun and knockdown by 3s every 0.5s), but is really easy to make. It's damage shouldn't be able to be outhealed by just injecting an equal amount of dylovene.
> * Lowering the damage to 1 every 0.5 seconds will basically make it so chemist traitors won't be able to be cuffed, without any downside or significant time investment.

May I remind you it is still doing 1 damage per every 0.5u, it is still deadly if overused just like all stimulants

**Comment by Arendian** [comment]
> May I remind you it is still doing 1 damage per every 0.5u, it is still deadly if overused just like all stimulants

You can mix it with an equal amount of dylovene(heals 1 poison every 0.5u) to completely negate the damage.

**Comment by Eden077** [comment]
Alright well I'm gonna change it to 2 in that case, thanks.

**Comment by Eden077** [comment]
Wonderful... Now I gotta go fix it.

**Comment by Eden077** [comment]
Oh boy... Branch is properly fucked, gonna make a new PR that doesn't have a cooked submodule

**Comment by UbaserB** [comment]
> I don't think the change is the correct way to balance Synaptizine because of the following reasons:
> 
> * Synaptizine currently deals the same damage as unstable mutagen(6/u), which is also extremely easy to make, so as a poison it's damage is on the same level as a comparable one.
> * Synaptizine is basically desoxyephedrine without the speed boost(both reduce stun and knockdown by 3s every 0.5s), but is really easy to make. It's damage shouldn't be able to be outhealed by just injecting an equal amount of dylovene.
> * Lowering the damage to 1 every 0.5 seconds will basically make it so chemist traitors won't be able to be cuffed, without any downside or significant time investment.

i told them to make the recipe a lot different but they arent bothered doing that so i might do it in a separate PR later

**Comment by Partmedia** [comment]
> i told them to make the recipe a lot different but they arent bothered doing that so i might do it in a separate PR later

Please be respectful in offering feedback. Unless you are a maintainer, it can be appropriate to gently suggest changes (e.g. "I think it would be better if the recipe was different") but not require them (e.g. "I told them to..." or "Do this...").

**Comment by UbaserB** [comment]
> > i told them to make the recipe a lot different but they arent bothered doing that so i might do it in a separate PR later
> 
> Please be respectful in offering feedback. Unless you are a maintainer, it can be appropriate to gently suggest changes (e.g. "I think it would be better if the recipe was different") but not require them (e.g. "I told them to..." or "Do this...").

Oh, no this is something we discussed earlier in the discord and agreed on, no animosity here.

**Pull request closed without merging**
