### PR TITLE
revive saltern

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
bring best map up to scratch:
- [X] research assistant exists
- [X] add arrivals shuttle support
- [X] add 2 escape pods
- [X] add an anomaly room
- [X] convert toxins to xenoarch and actually have gases in it (how was it meant to be toxins???)
- [X] add det room
- [X] add spare id card in cap office
- [X] faxes!!!
- [X] mail!!!
- [X] clean up the sanctuary thing, add floppa and zookeeper as pets
- [X] soup sensor server in cmo room
- [X] telecomms outside the conference room
- [X] hos spoder
- [X] reclaimer in disposals (trash man setup)
- [X] remove ninja shoes
- [X] skub
- [X] atmosian plushie!!!
- [X] stuffed robotics below anomaly room

derotated omega since:
- moose is unique in terms of power i like it
- moose has cool loot for miners

**Media**
mail and fax

telecomms

anomaly room (no distro/waste shown)

xenoarch

disposals

robotics (no distro/waste shown)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Saltern has been refitted with the latest and greatest, it is now back in rotation.
- remove: Omega has been derotated due to excessive wear and tear.

### CODE REVIEW

**Comment by PJB3005** [comment]
holy shit saltern based???? (I am not biased)

**Comment by mirrorcult** [comment]
saltern 3

**Comment by deltanedas** [comment]
who made saltern i wonder

**Comment by PixelTheKermit** [comment]
We need to revive knightship next tbh

**Comment by deltanedas** [comment]
so slight issue there is z fighting with the overlapping conveyors, i want to retain the functionality of being able to use either recycler or reclaimer but is there a way to have one conveyor always draw over the other? it looks horrible when moving

**Comment by deltanedas** [comment]
i still need to do robotics and i dunno if there are unmainted lowpop maps that need replacing

**Comment by Scribbles0** [comment]
on review, found a few things that should probably be fixed

- missing disposal turn for mail into science

image

- disposals going through walls is a bit iffy but that might be a relic of the old map
- observatory still doesn't have power, might want to wire it up if you're going to have a job spawn there
- you can't mail stuff from bridge to anywhere else except for hop due to how disposals works
- mailing router for bridge/hop isn't tagged

also you'd probably need emisse's input on what map gets derotated, moose is currently unmaintained atm i think
aside from all of that, looks good to me

**Comment by deltanedas** [comment]
emisse said moose or omega and moose is being actively tweaked

ill fix the issues you found, thanks

**Comment by deltanedas** [comment]
added r&d console to robor room:


brigmed saving poor urist with defib (also at med and other places):


floppa room now powered:


bridge and hop mail are now part of the main loop:


also fixed the sci mail bend, added some more maint goodies and removed unneeded maint lights

**Pull request merged**
