### PR TITLE
Make tricordrazine cheaper to produce

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Tricordrazine is now cheaper to produce, requiring less commonly used ingredients instead of being a mix of dylovene/inaprovaline
```
- type: reaction
  id: Tricordrazine
  reactants:
    Copper:
      amount: 1
    Iron:
      amount: 1
    Potassium:
      amount: 1
  products:
    Tricordrazine: 3
```
    
## Why / Balance
Tricordrazine is a neat chemical to use on not-so-damaged patients, but the recipe for it calls for carbon, oxygen, and sugar, which are all important ingredients in medicines such as bicaridine (and by extension all advanced brutes), dexalin+, dermaline, bruizine, sigynate, etc.
Iron, copper, and potassium all are only used in one significant medicine: dex+, leporazine, and dylovene respectively. They're much more abundant in supply as well.
It's also quite annoying when you're trying to revive someone in a critical state from poisoning, and your inaprovaline mixes with your dylovene to make something entirely useless for the situation at hand.

## Media
https://github.com/user-attachments/assets/ee7b9f28-2663-4935-9a19-8b02dd32bf9c

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Tricordrazine is now mixed using copper, iron, and potassium rather than dylovene and inaprovaline.

### CODE REVIEW

**Comment by ZombieChibiXD** [comment]
This reduces the risk factor of medical and makes medical essentially something not specialized enough for crew member.
This breaks the design philosophy written here
[Design Principles - Chaos](https://docs.spacestation14.com/en/space-station-14/core-design/design-principles.html#chaos)

I agree poisoning is an annoying damage to handle, however this is not the fault of mixture of inap/dylo. Dylo is supposed to be minor poisoning medication (as seen at the rate of 1DMG/0.5u).
However due to chem/doctor not understanding how to counter-play poison does not warrant this change.

Ethylredoxrazine+Dylo is safe enough mix to insert to a patient to stabilize their poisoning, Additionally, if botany can make histamine from nettle or ling zhi for ultravasculine, we have a potent anti-poison meds to counter most poisoning case.

Additionally, for poisoning, Heartbreaker toxin as a poison counter is a valid play to stop the progression of the poison by purposefully killing the patient, rather than making the patient near round removed due to poisoning.

Also lastly. Cryoxadone. Cryomed for severe poisoning cases. Seriously. If medical could stop pressuring Chemist with inefficient reagent request and usage, it'll be for the better.

**Comment by ZombieChibiXD** [comment]
I don't appreciate your comment saying "stuck-up" when I'm just giving my thoughts.
I don't see where you came from with that "one chemical" reply.

If I mistook this PR as a undercover poison PR (with me bringing up ultravasc/cryo), that's my bad and I'll own up to it.

Either way, I disagree with this PR due to the side effects to the existing chem reaction, in addition to my personal bias of chemistry, since I find the current recipe to my liking. If by cheaper you're not getting enough trico, I suggest increasing the inap/dylo to trico amount to make not as expensive to your liking, while keeping the same reaction.

**Comment by ZombieChibiXD** [comment]
Anyways since your PR both involve trico and inap, doesn't this change how MediBot fundamentally work? At the base level I disagree with modifying existing reagents and position myself more in the position of adding new reagents instead of modifying existing ones.

**Comment by Plykiya** [comment]
> It's also quite annoying when you're trying to revive someone in a critical state from poisoning, and your inaprovaline mixes with your dylovene to make something entirely useless for the situation at hand.

the medibot preventing the crit poison patient from ever recovering:

**Comment by thebadman4662** [comment]
Mercury/Iodine/Aluminium have like ZERO use for good chems while chemists can run out of potassium just fine already, if you want underused reagents to see more use those would be my suggestions as right now I pretty much empty them all for 10+ extra jugs.

**Comment by EthanQix** [comment]
> > Mercury/Iodine/Aluminium have like ZERO use for good chems while chemists can run out of potassium just fine already, if you want underused reagents to see more use those would be my suggestions as right now I pretty much empty them all for 10+ extra jugs.
> 
> Problem is that those don't have any actual sources. Iron/copper can be obtained from steel/cables, and potassium can be ground up from bananas, but mercury, iodine, and aluminum are ONLY obtainable from chemical crates or restock boxes.

You can get iodine from rock salt.

**Comment by deltanedas** [comment]
you can make like 2400u of tricord with the copper since barely anything uses it

**Comment by Ilya246** [comment]
medibots make tricord for literally free so it should be really cheap

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and the agreement was that chem recipes should not be simplified too much. Multi-step reactions and side effects from combining the wrong reagents are what makes it feel like proper chemistry instead of a simple crafting mechanic. As such I will be closing this PR. thank you for your contribution.

**Comment by SaphireLattice** [comment]
The issue is that there's nothing stopping people from making godawful squares of beds and medibots. The swarms are utterly annoying to walk in for. And they are just infinite sources of tricordrazine. There's zero reason to make tricor compared to just spamming the damned bots.

And side effects are nice! I like that you can't mix brutes. But "useful chem for stabilizing someone in crit" conflicting with an anti-toxin into making something that works *only* for someone above 50 health is kinda frustrating. Kinda get it but, dunno. It's this one edge case that has no analogues.

**Comment by Ilya246** [comment]
i don't think it should be easier and better for chemists to make a medibot rather than to actually make trico

**Comment by deltanedas** [comment]
theres essentially no reason to use trico instead of keeping a patient for 5 seconds longer to heal the third/fourth damage type. the benefit of medibots is they have free basic healing. it might just be best to remove their inaprov so it cant conflict with poison patients or people using dex+ (the current meta)

**Comment by Scruq445** [comment]
everyone is forgetting that the Chaplain can make infinite holy water (basically tricord but with like 20% less brute healing) by just slapping a container of water with their book.

**Pull request closed without merging**
