### PR TITLE
Maxcap 1984

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR

Atmos techs are able to make bombs able to destroy entire departments in under 10 minutes and the only thing that’s stopping the majority of players from doing that is that the information is being kept “secret”, despite one player having made a literal calculator that tells them how effective their bomb is going to be. There’s already been an alarming rise in incidents where atmos bombs the nukies/dragons/whatever threat the station is facing, and it’s only going to get worse as the information continues to spread and powergamers start learning how atmos works. Until somebody’s rewritten atmos code to make maxcaps much harder to produce, rain’s silly value change needs to be reverted.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Gas-based explosives are now 5 times less effective.

### CODE REVIEW

**Comment by Ilya246** [comment]
just make the radius scale as `sqrt(overpressure * 6)` instead of `overpressure`, that makes small bombs still good while making big bombs *really* hard to make and actually require good recipes
i checked out the recipes current atmos techs use and they won't result in good bombs this way, decrease the `6` to make them even worse

**Comment by DawBla** [comment]
Atmos techs cant be traitors so they shouldnt ever make a station wiping nuke anyway
All this mechanic brings into the game is people trying to be heroes with makeshift tank bombs and doing more friendly fire damage than to the actual enemy

**Comment by GoodWheatley** [comment]
> just make the radius scale as `sqrt(overpressure * 6)` instead of `overpressure`, that makes small bombs still good while making big bombs _really_ hard to make and actually require good recipes

That only “solves” the problem by making the information even more restricted, until it inevitably starts leaking out again and we’re back at square one. All it takes is one png file containing the optimal recipe and now atmos is nuking the station again.

**Comment by Ilya246** [comment]
> > just make the radius scale as `sqrt(overpressure * 6)` instead of `overpressure`, that makes small bombs still good while making big bombs _really_ hard to make and actually require good recipes
> 
> That only “solves” the problem by making the information even more restricted, until it inevitably starts leaking out again and we’re back at square one. All it takes is one png file containing the optimal recipe and now atmos is nuking the station again.
no, not really, it requires you to do some other things which take actual time (20min if you speedrun) to make actual good bombs

**Comment by DawBla** [comment]
> That only “solves” the problem by making the information even more restricted, until it inevitably starts leaking out again and we’re back at square one. All it takes is one png file containing the optimal recipe and now atmos is nuking the station again.

Yeah, pretty sure relying on some game mechanic being gatekept by some circlejerk is a good safety measure

**Comment by Ilya246** [comment]
> You’re missing the point. Once you have the information, there’s no nuance to making a bomb; it’s as you said, a speedrun. Once that information inevitably spreads, there’s nothing but time standing in the way of atmos and a nuke that solves all the station’s problems, and most major antags only start attacking the station late in the round. Secrecy doesn’t work unless the code is actually secret, and not available for anyone with an internet connection to look at.
>
but didn't you yourself say
> Until somebody’s rewritten atmos code to make maxcaps much harder to produce, rain’s silly value change needs to be reverted.
>
, where my change would satisfy the "make maxcaps much harder to produce" condition and make the value change not required?

**Comment by BasedUser** [comment]
tank explosion code sucks anyway maxintensity should change but the radius should be capped (mirrors ss13)

**Comment by GoodWheatley** [comment]
> > When I wrote that, I didn’t mean that maxcaps would be timegated, I meant that you’d need to actually be careful with how much gas was reacting and how fast the reaction was if you didn’t want your bomb to become a plasmafire, like I discussed with you on Discord yesterday.
> 
> that would still result in the issue of just having to know the recipe and only having to speedrun the known recipe afterward, it just makes the recipe harder, further gating it

Which is why it’s necessary to hardcap the explosion radius. Discussing hypotheticals about how atmos explosions could or could not work in the future is irrelevant when there is a present problem of easy access to massive explosives that I am trying to fix.

**Comment by asperger-sind** [comment]
I believe this should be discussed with the presence of Emisse.

I also think that reducing the cap back to 14-range wont solve the problem at hand immediately, people will still make maxcaps and still deal stupidly high amounts of collateral damage or EoRG even if now the explosion is shuttle-sized and not station-sized. So we don't fully solve the issue and make a mechanic boring enough again for a decent chunk of the playerbase to forget about it.

Making maxcaps harder to make - while solving the issue NOW - just times it out for a bit before someone figures out a new maxcap recipe and either shares it or just plays around and tells everyone about it for long enough before someone else decides to try making one as well and succeeding. Basically we'll solve the issue for like a week or two and then it resurges.

Maxcaps are just not really well designed right now, they don't require basically any resources (except steel) if you have access to atmos, no gatekeeping mechanic like technology, while not being particularly hard to make if you have the knowledge to do so.

Router proposed just SS13-ifying maxcaps and that could probably work, but I'm not sure what other solutions there are to just making maxcaps an actual honest to god mechanic rather than a niche function atmos has.

**Comment by Ilya246** [comment]
> Making maxcaps harder to make - while solving the issue NOW - just times it out for a bit before someone figures out a new maxcap recipe and either shares it or just plays around and tells everyone about it for long enough before someone else decides to try making one as well and succeeding. Basically we'll solve the issue for like a week or two and then it resurges.
>
as i said, time to make the maxcap matters a lot, if the maxcap takes 20 minutes for a very experienced player if they get good luck (which is what my change would do), you can't use them to beat nukies (or pretty much any other antag) anymore, since in that time the nukies would likely either win already or be highly likely to lose

**Comment by asperger-sind** [comment]
> as i said, time to make the maxcap matters a lot, if the maxcap takes 20 minutes for a very experienced player if they get good luck (which is what my change would do), you can't use them to beat nukies (or pretty much any other antag) anymore, since in that time the nukies would likely either win already or be highly likely to lose

20 minutes from roundstart or 20 minutes after nukies are declared?
What if they already have tritium set up and their atmos setup is rigged in a way that they have spare outlets for plasma, tritium and oxygen while having spare heaters/freezers?

Assuming it requires frezon for filament compression, yes, that may solve the issue because now you have to basically finish atmos before making a maxcap, but you can kill nukies with a 14-range bomb, let alone something like 40-range.

**Comment by Ilya246** [comment]
> Assuming it requires frezon for filament compression
it does
>but you can kill nukies with a 14-range bomb, let alone something like 40-range.
exactly, and my change would solve this issue better (making 14-range bombs harder to make) than this change, hence why i'm suggesting it as what we should use for now

**Comment by deltanedas** [comment]
controversial idea: what if remove gas tank fracturing (reason: uh bluespace yeah)
then optionally add some funny toxins item that needs a lot of research to make bombs

**Comment by BasedUser** [comment]
from <https://github.com/space-wizards/space-station-14/blob/e25320c00957b5ef059b4fcc97ebcaa69944990e/Content.Server/Atmos/EntitySystems/GasTankSystem.cs#L275>:
```patch
                 pressure = component.Air.Pressure;
-                var range = (pressure - component.TankFragmentPressure) / component.TankFragmentScale;
+                var theoreticalRange = (pressure - component.TankFragmentPressure) / component.TankFragmentScale;
+                var range = MathF.Min(theoreticalRange, GasTankComponent.MaxExplosionRange); 
                 // Let's cap the explosion, yeah?
                 // !1984
-                if (range > GasTankComponent.MaxExplosionRange)
+                if (theoreticalRange > GasTankComponent.MaxExplosionRange * 4) // given some leeway for ratio
                 {
-                     range = GasTankComponent.MaxExplosionRange;
+                     theoreticalRange = GasTankComponent.MaxExplosionRange * 4;
                 }
 
-                _explosions.TriggerExplosive(component.Owner, radius: range);
+                var ratio = theoreticalRange / range;
+                // resolve explosive component idfk i'll make something up here
+                _explosions.QueueExplosive(component.Owner, "Default", _explosions.RadiusToIntensity(theoreticalRange),
+                    explosive.Slope * ratio, explosive.MaxIntensity * ratio,
+                    explosive.TileBreakScale, explosive.MaxTileBreak, explosive.CanCreateVacuum);

                 return;
```
solved ez

**Comment by Emisse** [comment]
we can go back to this if the other change proves ineffective

**Pull request closed without merging**
