### PR TITLE
Remove cat ear guaranteed spawns

### PR DESCRIPTION
**Pull request by metalgearsloth**
:cl:
- remove: Remove guaranteed cat ear spawns.

### CODE REVIEW

**Comment by Emisse** [comment]
i didnt even know it was on these maps

**Comment by EmoGarbage404** [comment]
mom found the ~~poop sock~~ toilet cat ears

**Comment by Emisse** [comment]
why does removing the cat ears cause cluster to fail load wtf

**Comment by EmoGarbage404** [comment]
> why does removing the cat ears cause cluster to fail load wtf

load-bearing femboy

**Comment by deltanedas** [comment]
> why does removing the cat ears cause cluster to fail load wtf

sloth only deleted the ears, didnt modify the container its in

**Comment by deltanedas** [comment]
finally cat ears are 100% valid

**Pull request merged**
