### PR TITLE
resprite every captain item

### PR DESCRIPTION
**Pull request by Emisse**
resprite almost every captain clothing item
put captains hardsuit to previous pierce resist so its mildly more useful in nukies ( not better than carapace though)

uhhh this was to make every captain item internally consistent with each other artstyle/palette wise. 
i use a lot of colors from newer stuff and also from the really old stuff and same with mixing the styles.
image

🆑 
- tweak: Captain clothing items have been resprited

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
pic when

**Comment by Emisse** [comment]
image

**Comment by Emisse** [comment]
pics posted

**Comment by UbaserB** [comment]
the hardsuit looks uhh superhero-ey and its so goofy imo

**Comment by Golinth** [comment]
kind of agree with UbaserB on the hardsuit, but everything else looks great

**Comment by JoeHammad1844** [comment]
yeah please remove the funny helmet wings

**Comment by Emisse** [comment]
ok its boring again

**Comment by asperger-sind** [comment]
Looks like this changes resists for cap hardsuit and also gives it a light, neither are in CL

**Comment by Hmeister-fake** [comment]
I love the new power ranger caps hardsuit lmao please keep it. Captains needs a goofy looking thing that looks very unique.

**Comment by FinnishPaladin** [comment]
yeah, imo the helmet wings look perfect..

**Comment by LordEclipse** [comment]
Go go Captain Ranger...

**Comment by IamVelcroboy** [comment]
Yeah, I'm team helmet wing. That looked dope!

**Comment by keronshb** [comment]
I'm absolutely loving the Kamen Rider styled hardsuit.

idk if I like this shade of blue. Can you post a comparison screenshot between live & here? I'm curious if my mind is just misremembering.

**Comment by MACMAN2003** [comment]
i feel like the brighter blue color fits the captain more, rather than the muted blue

**Comment by lexs0sa** [comment]
the wings look awesome

**Comment by Emisse** [comment]
ok i reverted it idk what anyone wants from me anymore

**Pull request merged**
