### PR TITLE
fix fireaxe but actually this time

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

fix fire axe wide swing actually this time

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by mirrorcult** [comment]
image
include screenshot of it being actually correct

**Comment by notquitehadouken** [comment]
:(

**Comment by notquitehadouken** [comment]
draf while i rember to fucking make sure it's sane

**Comment by metalgearsloth** [comment]
@notquitehadouken you coming back to this

**Pull request closed without merging**
