### PR TITLE
25% chance for ian suit in hop locker

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

## Why / Balance
doesnt have speed anymore so why not

## Technical details
no

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: HoP's locker will sometimes contain a rare item...

### CODE REVIEW

**Comment by deltanedas** [comment]
ian replacement bundle in uplink
20tc for an ian suit, knife, mop, water, disposal unit, trunk and tube

**Comment by AJCM-git** [comment]
Shrimply make Ian drop their skin when butchered and add a crafting recipe

**Comment by EmoGarbage404** [comment]
is the suit spacefaring?

also this seems like more pointless locker bloat

**Comment by metalgearsloth** [comment]
make it salvage loot or craftable or something, locker should be essentials noob.

**Comment by deltanedas** [comment]
ok ian crafting system incoming

**Pull request closed without merging**
