### PR TITLE
Adds coal

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
- Adds coal material that can be mined from asteroids
- Adjusts bulk steel recipe in the Ore Processor to require coal
- Adds reagent extraction through grinding to produce Carbon, Ammonia, and Hydrogen, along with trace elements of Sulfer and Mercury
- Adds coal to the Xmas present pool

## Why / Balance
- ~~Adds a little bit of depth to mining/ore processing as it makes the processors require a type of fuel.~~
- Adds new resource and method for obtaining useful reagents. 
- Makes a classic funny gift.  

## Technical details
n/a

## Media
Doesn't add any sprites. Coal sprite already existed. 

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**

:cl: Velcroboy
- add: Added coal. Coal has been added to the steel recipe in the Ore Processor. Coal can be ground up for Carbon and other elements. Coal can be mined or received as a gift if you've been naughty.

### CODE REVIEW

**Comment by Aisu9** [comment]
yay, now we just need to change steel ore into iron ore and change the steel sheet recipe

**Comment by MACMAN2003** [comment]
how the hell would coal get into an asteroid? also you shouldn't need coal for the ore processor because this isn't the 18th century, it would likely have a miniature electrical arc furnace built in

**Comment by VektorZ1** [comment]
There should probably be a recipe when chopping in a mixer

**Comment by IamVelcroboy** [comment]
> how the hell would coal get into an asteroid? 

Coal is just Carbon under extreme pressure. Why wouldn't it show up on asteroids?

>also you shouldn't need coal for the ore processor because this isn't the 18th century, it would likely have a miniature electrical arc furnace built in

The way I see it, this is a jumping off point for an upgraded machine that doesn't require coal. Besides, the amount of tech in this game that is already outdated/slash would be incredibly dated in the time period SS14 takes place is already like half the entities. So, 🤷‍♂️

**Comment by deltanedas** [comment]
why would it both use a lot of power *and* a solid fuel

**Comment by MrGreen006** [comment]
Wait does the processor still need power to work with this Pr? Or does it need both power AND coal?

**Comment by IamVelcroboy** [comment]
> There should probably be a recipe when chopping in a mixer

And make coal dust? What would you do with coal dust?

**Comment by FinnishPaladin** [comment]
ghetto chem anti-toxin..

**Comment by IamVelcroboy** [comment]
> why would it both use a lot of power _and_ a solid fuel

Good point. Something needs to ignite the coal, but I could see about reducing power load.

**Comment by IamVelcroboy** [comment]
There's possibly a case here for making a separate coal-powered machine that is the starting machine, with the more advanced, arc furnace unlocked through research...🤷‍♂️

**Comment by EmoGarbage404** [comment]
> There's possibly a case here for making a separate coal-powered machine that is the starting machine, with the more advanced, arc furnace unlocked through research...🤷‍♂️

i think that would be interesting, especially if it doesn't require any electricity. That's probably a bit out of scope, so if you want to undo the recipes, we can always add a coal-powered furnace in the future.

You should definitely make the coal able to be grinded into carbon, though,

**Comment by IamVelcroboy** [comment]
> > There's possibly a case here for making a separate coal-powered machine that is the starting machine, with the more advanced, arc furnace unlocked through research...🤷‍♂️
> 
> i think that would be interesting, especially if it doesn't require any electricity. That's probably a bit out of scope, so if you want to undo the recipes, we can always add a coal-powered furnace in the future.
> 
> You should definitely make the coal able to be ground into carbon, though,

OK, I'm off to work right now. But I'll do that later.

**Comment by Errant-4** [comment]
Why is there a coal furnace in space?
Earth banned it so NT is using up it's massive stockpile in space instead

**Comment by moonheart08** [comment]
I personally think making alternate power sources a future thing is best. In the meantime, coal would be a good candidate for a reliable source of carbon, hydrogen, and sulfer for chem.

**Comment by MrGreen006** [comment]
The great chem dispenser murder is near..

**Comment by mirrorcult** [comment]
totally fine with introducing coal as a material here but i'd rather it didn't power the reclaimer right now

**Comment by deltanedas** [comment]
maybe with:
- ore processor being roundstart and renamed to ore smelter to sound lower tech
- ore processor 2 electric boogaloo being in salv equipment and using power instead of coal
  still using a small amount of coal for steel production since yes
- a bit of coal mapped on reclaimer so you can bootstrap it better

**Comment by UbaserB** [comment]
Sounds cool.

**Comment by IamVelcroboy** [comment]
OK, I've removed it from the Ore Processor recipes. I left it in the steel recipe as it is part of the process realistically. Basically requires 2 pieces of coal for every 30 stack of steel which shouldn't be very restricting.

You can now grind coal for Carbon, Ammonia, Hydrogen and small amounts of Sulfur, and Mercury.

**Comment by IamVelcroboy** [comment]
I guess don't merge this yet. I just saw the PR that standardized sheets output. Since I was basing this on what steel sheets previously did, I'll redo the amounts later when I get a chance.

**Comment by Blackern5000** [comment]
> > how the hell would coal get into an asteroid?
> 
> Coal is just Carbon under extreme pressure. Why wouldn't it show up on asteroids?

This man does NOT know how coal forms

**Comment by Afrokada** [comment]
> > > how the hell would coal get into an asteroid?
> > 
> > 
> > Coal is just Carbon under extreme pressure. Why wouldn't it show up on asteroids?
> 
> This man does NOT know how coal forms

Yeah, it should be graphite instead of coal.

**Comment by IamVelcroboy** [comment]
OK, reagent output has been standardized to 10u of products. This is ready now.

**Pull request merged**
