### PR TITLE
put multitool on syndie holster

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
sus box has holster and all tools
holster can fit all tools except multi which is annoying
egg

(all other tools are allowed as they are melee weapons)

now it also allows multitools

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Syndicate shoulder holster now has a pocket for a multitool.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
Isn’t the holster supposed to only hold guns and ammo?

**Comment by deltanedas** [comment]
yes but since it can store any melee weapon, it can hold just about anything (but not multitool argh)

**Comment by AJCM-git** [comment]
> yes but since it can store any melee weapon, it can hold just about anything (but not multitool argh)

thats more of a side-effect thank something intended, whitelisted storages should remain more specific than vague

**Comment by deltanedas** [comment]
will make it just whitelist multitool in a bit

**Comment by AJCM-git** [comment]
> will make it just whitelist multitool in a bit

thats not the problem imo, the reason the holster can hold those tools in the first place is because they are regarded as valid melee weapons when they shouldnt, making it also hold multitools does not solve that

**Comment by deltanedas** [comment]
then why would the sus box have a holster and not a utility belt?

**Comment by GoodWheatley** [comment]
> then why would the sus box have a holster and not a utility belt?

Looks like an oversight by the holster PR’s author, it would make more sense for the holster to be unable to hold melee weapons and a utility belt going in the toolbox

**Pull request closed without merging**
