### PR TITLE
gas tank and jetpack volume reduction

### PR DESCRIPTION
**Pull request by dmnct**
## About the PR

PR #17106 did not achieve it's stated goal of reducing EVA times from effectively infinite to something that matters, so here we go again. All Gas tanks volumes are now reduced by 66-75%. Jetpacks, which survived the previous adjustment and still lasted several hours, will again match tank volumes, with their propulsive gas consumption reduced so they provide generally the same runtime as their current iteration.

The new proposed supply times, based on some Discord discussion:

Emergency tank:  4 minutes (down from 12)
Extended Etank:  9 minutes (down from 37)
Double Etank  : 15 minutes (down from 62)
Full tank    :  31 minutes (down from 94)

This will make it so EVA crews actually need to watch their pressure if they spend significant time outside the station, and/or have a canister in their general vicinity. 
Emergency tanks can no longer be used on timescales that far exceed escaping an emergency situation, but will probably be insufficient in extended emergencies, where access to canisters will now be much more important. How well this works in practice will have to be carefully watched.

The Improvised Pneumatic Cannon is also adjusted, and will now be able to fire 20 times again with a regular gas tank, or once with an Emergency Tank.

**Issue: What about the arachnids?**
With the new times, arachnids will be much more impacted by their missing suit storage slot. To work in vacuum they will need a jetpack even if they don't plan to float, or possibly carry multiple small tanks. I don't know how often they sign up for Engineering or Salvage, but this will certainly make their life in those roles much harder. Maybe it should be considered to give them Double Emergency Tanks on spawn (once we can specify spawn by species), though these tanks are currently very rare, and we might not want to proliferate them such.
Trying to survive in a highly perforated station will be difficult for everyone, but especially for arachnids. Even if they get a standard tank, they will have to carry it in hand. Extra attention should be paid to how viable they remain as a choice

Some options so far:
 - Add nothing, fix this on the arachnid side
 - Add Extended E or Double E oxygen tanks to all salvagers
 - Add some Double E oxygen tanks to the Salvage Vend
 - Researchable Double E tank
 - Go back to the drawing board with the times

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Errant
- tweak: Gas tanks and jetpacks have reduced capacity and now need to be refilled more regularly.
- tweak: Jetpacks now start fully filled.

### CODE REVIEW

**Comment by Ilya246** [comment]
also adjust Atmospherics.MinimumTritiumOxyburnEnergy so it doesn't break atmos bombs

**Comment by dmnct** [comment]
I assumed they will bring jetpacks (yes, absurd, but whatever.) or multiple emergency tanks while gearing up for the expedition. Why would an excursion to an alien planet be treated as less than an EVA?

Emergency tanks are being used to explore literal alien planets, I think that was the issue in the first place and it only got this far because emergency tanks lasted so long that this worked so no one noticed how absurd it is. We should never have gotten into this way of things in the first place, but I guess here we are. I am drafting this until further discussion

**Comment by deltanedas** [comment]
pro idea:
- double tank is same as larhe tank since its so rare
- extended tank is 15 mins so salv spoder can use it effectively
- maybe increase emergency

**Comment by LankLTE** [comment]
> pro idea:
> 
> * double tank is same as larhe tank since its so rare
> * extended tank is 15 mins so salv spoder can use it effectively

If that was done (and salv were given extended air tank boxes since I don’t think they have them atm), I think it’d be a good compromise.

**Comment by dmnct** [comment]
If the double emergency tank had the same volume as the standard tank, while still being smaller, it would just be a superior choice in every way. Arachnids would have to compete with everyone who could possibly grab them first, to have one. 
And the extended emergency tank is still meant as an emergency tool. I think they are fine where they are, but a double tank would allow arachnids to finish an expedition from what numbers you have stated above (possibly with resorting to use their emergency tank near the end if things went badly or they opened their bottle too early? 

So I think what's needed (unless arachnids are given an exoslot), is to somehow make it possible for them to get double tanks. A few maps have them in EVA storage but asking mappers to fix this is not the best way. 

Maintainers, how do you feel about putting, say, two double tanks in the Salvage Vendor? If someone else takes them or there are more than X arachnids who want to go on the expedition, I guess they will have to make do or resort to violence

**Comment by VektorZ1** [comment]
Double Etank as RnD technology

**Comment by dmnct** [comment]
Okay then. I'll let the Maintainers decide what, if anything, needs to be added or changed for/about arachnids for this. Ready for review since everything else works as intended

**Comment by Partmedia** [comment]
> So I think what's needed (unless arachnids are given an exoslot), is to somehow make it possible for them to get double tanks. A few maps have them in EVA storage but asking mappers to fix this is not the best way.
> 
> Maintainers, how do you feel about putting, say, two double tanks in the Salvage Vendor? If someone else takes them or there are more than X arachnids who want to go on the expedition, I guess they will have to make do or resort to violence

Sure, let's put two double tanks in the salvage vendor. This addresses the exosuit slot problem.

**Comment by dmnct** [comment]
> Sure, let's put two double tanks in the salvage vendor. This addresses the exosuit slot problem.

That PR was rejected, Emisse did not want it at roundstart

**Comment by Partmedia** [comment]
> > Sure, let's put two double tanks in the salvage vendor. This addresses the exosuit slot problem.
> 
> That PR was rejected, Emisse did not want it at roundstart

Would you mind linking that PR? We can talk to @Emisse and see if this change justifies reconsidering it.

**Comment by dmnct** [comment]
Just scroll up? I linked it to this one. Anyway it was 18489

**Comment by deltanedas** [comment]
imo double tanks should be a tech, or a new tank that can have over 1 mpa using plasteel for high pressure containment

**Comment by Partmedia** [comment]
> imo double tanks should be a tech, or a new tank that can have over 1 mpa using plasteel for high pressure containment

We're trying to fix the problem of arachnids not being able to go on expeditions at round start because they have no exosuit slot to put a large tank. Unless you're suggesting that you want arachnids to wait around for science to research this new technology?

**Comment by dmnct** [comment]
PR 18569, if merged, will reduce expedition duration to 5 minutes. 
That would put it within the capabilities of an Extended Emergency Tank, or 2 Emergency Tanks

**Comment by Partmedia** [comment]
> PR 18569, if merged, will reduce expedition duration to 5 minutes. That would put it within the capabilities of an Extended Emergency Tank, or 2 Emergency Tanks

If you want to wait for this, we can first merge the large tank reduction and wait to adjust the rest.

**Comment by deltanedas** [comment]
also didnt someone pr giving salv extended tanks

**Comment by dmnct** [comment]
> also didnt someone pr giving salv extended tanks
I did not find such a PR, although that might make sense even beyond arachnid considerations, since salvagers are expected to do vac work off-station where a life support emergency might take longer to resolve

Given that there is both a PR to reduce expedition length (18569), and an arachnid rework (18631) that will likely give their suitstorage slot back, I am of the mind that this PR does not need adjustments, but the question is: can it go through before those PRs are merged to see if there is any issue at all, or should it wait for either of them to go through first

**Comment by Partmedia** [comment]
Thank you for your contribution. Please be attentive to folks are feeling about this in the coming days, especially with respect to the smaller tanks, and we'll adjust as needed.

**Pull request merged**
