### PR TITLE
UI opacity option

### PR DESCRIPTION
**Pull request by c4llv07e**
## About the PR

I think right now the user interface takes up a lot of space on the screen with lots of windows, menus, etc. It would be nice to be able to make them more transparent.

Some suggested making only some elements transparent, but, as I understood, this would require using stylesheets, which, as I also understood, are currently "abandoned":

`// STLYE SHEETS WERE A MISTAKE. KILL ALL OF THIS WITH FIRE`

**Media**

https://github.com/space-wizards/space-station-14/assets/38111072/4f0df269-ae65-4585-99e9-893f22b0035d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: kseandi
- add: Now you can change the UI opacity in the settings!

### CODE REVIEW

**Comment by kxvvv** [comment]
only changes the inventory UI? doesn't change the UI of the computers for example?

**Comment by c4llv07e** [comment]
> only changes the inventory UI? doesn't change the UI of the computers for example?

No, it changes the opacity of the WindowRoot, so it changes every UI menu, that you can open in the game (excluding options and escape menus, because otherwise someone might hardlock UI).

**Comment by asperger-sind** [comment]
Low-res monitor QoL, Huzzah!

**Comment by deltanedas** [comment]
1. play on normal hud
2. put inventories to sides of the screen (previously they perfectly fit black borders now they dont :( )

**Comment by c4llv07e** [comment]
> 1. play on normal hud
> 
>     2. put inventories to sides of the screen (previously they perfectly fit black borders now they dont :( )

I've always played with the "Stockholm hud", so I have no problem placing it in the chat window :)

**Comment by metalgearsloth** [comment]
At this time this doesn't fit with the UI of the game, sorry.

**Pull request closed without merging**
