### PR TITLE
Add transporters

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Extremely WIP please suggest as many code and design changes as necessary before I do too much

Adds transporters which are constructible robots that carry items one at a time from providers to receivers.

## Why / Balance

cool

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added transporters! They move items one at a time from providers to receivers. You can construct them with steel, glass, and a battery.
- add: Added receivers and providers. Construct each with the required board.

### CODE REVIEW

**Comment by deltanedas** [comment]
wtf mindustry

**Comment by notquitehadouken** [comment]
> wtf mindustry

yes
that is totally the inspiration

**Comment by notquitehadouken** [comment]
WHAT

**Comment by notquitehadouken** [comment]
FUCK

**Comment by notquitehadouken** [comment]
okay i summoned it again

**Comment by notquitehadouken** [comment]
nobody's saying anything here so i'm going to close it until i'm actually done

**Comment by Peptide90** [comment]
Is this cargo mules that carry crates of items (probably more useful) or like a tiny drone that can carry or pull singular things?

**Pull request closed without merging**
