### PR TITLE
machine parts + power cell resprite

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Old parts + cell + recharger were shiny TG sprites to the max. The old vg ones were damn good and the cells just needed some workshopping.

also fixes a logic error in recharger visualizer that caused some stuff to not display properly.

## Media

image
parts are from vg and the cells are adaptations based off of some stuff flareguy did and i cooked into a stew.
image
new panel sprites, too

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by UbaserB** [comment]
pls.. the matter bin just fix it gahh

**Comment by LankLTE** [comment]
aren't we really close to just removing machine parts? I thought the lathes / heaters were kind of the final step in that. fine with changing them but it feels a little unnecessary if I'm correct on that timeline

**Comment by EmoGarbage404** [comment]
> aren't we really close to just removing machine parts? I thought the lathes / heaters were kind of the final step in that. fine with changing them but it feels a little unnecessary if I'm correct on that timeline

the original T1 parts are gonna remain just for construction/machine stuff. They're not functional beyond little doodads but i think that's a fine place to leave em.

**Comment by Emisse** [comment]
sovl matterbin = merge

**Comment by K-Dynamic** [comment]
return to monke parts

tbh the new (old? v3) parts are a bit hard to look at compared to tg parts (v2), especially the matter bin being skinny as heck

**Comment by potato1234x** [comment]
cell charger looks way too matte to me imo

**Comment by CatMagic1** [comment]
maintainers are brainwashed
these are fugly
actually the powercell is kinda cool

**Comment by EmoGarbage404** [comment]
> maintainers are brainwashed
> these are fugly
> actually the powercell is kinda cool

If you are just gonna leave garbage spam then do us all a favor and go away.

**Comment by sugacloud** [comment]
How did you even get hired into the development team?🤣
The sprites are just terrible

**Comment by CrigCrag** [comment]
> How did you even get hired into the development team?🤣 The sprites are just terrible

because there is no development team and every single person who works on this project is an unpaid volunteer doing every last bit of it in their free time.

**Comment by Aisu9** [comment]
both TG's team and WizDen's team, but yeah these sprite looks so depressing for lack of better terms, fitting the capitalist dystopia era that is SS13/14!

**Comment by sugacloud** [comment]
> > How did you even get hired into the development team?🤣 The sprites are just terrible
> 
> because there is no development team and every single person who works on this project is an unpaid volunteer doing every last bit of it in their free time.

let him better not do this, he will kill the game with his useless PRs

**Comment by mirrorcult** [comment]
image

**Comment by Aisu9** [comment]
> > > How did you even get hired into the development team?🤣 The sprites are just terrible
> > 
> > 
> > because there is no development team and every single person who works on this project is an unpaid volunteer doing every last bit of it in their free time.
> 
> let him better not do this, he will kill the game with his useless PRs

i gotta remind that that Emo brought what is currently Science and Cargo salvage content(that is getting slightly reworked by Emisse) he has been putting some of the most interesting job content the game saw in a good while

**Comment by mirrorcult** [comment]
that said i think these are pretty bad sprites probably would have been better to just de-eris the current ones

**Pull request merged**
