### PR TITLE
Red bool update

### PR DESCRIPTION
**Pull request by Hanzdegloker**
## About the PR

A PR removed energy drink from the soda dispenser and I think this is a travesty as I am red bool's strongest warrior
I love energy drinks irl and shall not have them be second rate in my funny space game. Therefore I added 6 new mixed
drinks that use energy drinks in em, and resprited the energy drink can as well as making red bool spawn in discount dans.

## Why / Balance

Why have energy drink as a reagent if it isn't given the respect it deserves eh? Plus once newmed is merged and we get 
actual caffeine as a reagent energy drinks will be a great way to acquire heart failure or act as a bootleg combat stim. 
Also energy drink based mixed drinks are staples at bars everywhere, vodka red bulls for miles.

## Technical details

6 new energy drink based mixed drinks

Budget Insuls
Vodka Red Bool
Watermelon Wakeup
Rubberneck
Irish Bool
Xeno Basher

Energy drink was added back to the soda dispenser

There is now 8 energy drinks in the booze-o-mat and up to 4 in discount dan's

Red Bool energy drink cans now have a new sprite that doesn't look like coder art

## Media

Screenshot_1

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

:cl:
- add: Added 6 new energy drink based mixed drinks.
- add: Added Red Bool energy drink back to the soda dispenser and gave it a new canned sprite.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
you cannot use the red bull can as your design.

**Comment by Hanzdegloker** [comment]
> you cannot use the red bull can as your design.

same design different colours at least?

the former sprite was a big E for energy drink and thats it

**Comment by Hanzdegloker** [comment]
Screenshot_2
Like this?

**Comment by Hanzdegloker** [comment]
Screenshot_3

New, hopefully more distinct, sprite.

**Review by VasilisThePikachu — APPROVED** [review]
Gosh i want a red bool right now...

**Pull request merged**
