### PR TITLE
Revert "Make wearing an Ushanka also apply accent to your name"

### PR DESCRIPTION
**Pull request by metalgearsloth**
Reverts space-wizards/space-station-14#29111

sorry gang but admin first

:cl:
- tweak: Ushanka no longer applies an accent to your name.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
why tho

**Comment by muburu** [comment]
any reason why

**Comment by mirrorcult** [comment]
image

**Comment by Skarletto** [comment]
thx

**Pull request merged**
