### PR TITLE
Blacklist Arrows from Pneumatic Cannon

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

Blacklist Arrows from Pneumatic Cannon
## Why / Balance

Arrows are balanced around the bow, not the pneumatic cannon. If you want high suprise burst damage you should be using a bomb or improvised shells
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Blacklisted Arrows from Pneumatic Cannons

### CODE REVIEW

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/pull/26878

Endlessly maintaining a blacklist is too much of a pain for a niche item.

**Comment by K-Dynamic** [comment]
> This has made the current bow worthless

Not if you're an ashwalker or undead roman skeleton :trollface:

**Comment by superjj18** [comment]
> > See #26878
> 
> > 
> 
> > Endlessly maintaining a blacklist is too much of a pain for a niche item.
> 
> 
> 
> This has made the current bow worthless

What if you buff the bow by making it cheaper to craft, and thus making it the "poor man's pneumatic cannon"

**Comment by Iamgoofball** [comment]
the mechanical device beats some wood and twine; more at eleven

**Pull request closed without merging**
