### PR TITLE
Nukie Medivisor REAL

### PR DESCRIPTION
**Pull request by Golinth**
## About the PR

Adds a new HUD that the nukie medic starts with, does the same shit as the other visor, but with health bars. Also tinted slightly blue to differentiate it. (because medhuds are blue)

Does not touch the original visor, or any other nukie fill. 

## Why / Balance

Requested in #21495 

## Technical details

No code changes, just added a new entity in YML and set the fill for the agent to include it.

## Media

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The Nukie Agent now comes with a medihud built into their visor!

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
does the visor detect health for everyone or just the other nukies? I have thought of this and more people would just choose to be combat agents instead of being the healer if it can view the health of everyone.

**Comment by Golinth** [comment]
> does the visor detect health for everyone or just the other nukies? I have thought of this and more people would just choose to be combat agents instead of being the healer if it can view the health of everyone.

Everyone. If there’s enough people ask for it, I’d be willing to try to set the healthbars for nukies only.

**Comment by metalgearsloth** [comment]
make it nukie + medic only or else this is a huge buff.

**Comment by Emisse** [comment]
arggh ahoy i be agreein with slothy

**Comment by Golinth** [comment]
> make it nukie + medic only or else this is a huge buff.

Do you mean make it work to only show healthbars of nukies, or to remove the jobicon aspect of it

**Comment by Ghagliiarghii** [comment]
I really like this but think the color of the new one should be a bit more blue, it's very hard for me to distinguish the two visually and I could see esp. color blind players having this issue.

**Comment by Golinth** [comment]
> I really like this but think the color of the new one should be a bit more blue, it's very hard for me to distinguish the two visually and I could see esp. color blind players having this issue.

Okay done. How do they look now? (Ignore the lack of a syndicate icon, they still show up, I wasnt an actual nukie)
image
and an updated comparison between the agent hud and the normal: 
image

**Comment by deathride58** [comment]
Yeah, that looks much better

**Comment by Golinth** [comment]
@metalgearsloth is there anything else I need to do for this PR? 
The visor is for the nukie medic only, and is unique, like their PDA or Hardsuit.

**Pull request merged**
