### PR TITLE
Latex and Nitrile gloves no longer leave Latex and Nitrile 'Fibers' behind.

### PR DESCRIPTION
**Pull request by hord-brayden**
## About the PR

Removed any traces of nitrile or latex glove 'fibers'.

## Why / Balance

The purpose of latex and nitrile gloves in medicine is to not leave traces. Additionally there are purpose built items (Hristov bundle) that intentionally include a pair of gloves in them, as a nod to agent 47, the intent of which is to remove any trace of of a specific person's influence on an item. Nitrile gloves would fall under this umbrella. 

There's been some discussion also about adding randomized allergies/allergens and then latex and nitrile would make sense as the go-to for medical doctor hand apparel to avoid potential allergies and cross contamination between patients. 

## Technical details

Literally just removed the fiber components of these 2 sets of gloves, effectively emulating the forensic glove build.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Latex and Nitrile gloves no longer leave fibers behind, when interacting with items.

### CODE REVIEW

**Comment by deltanedas** [comment]
this makes dets forensic gloves useless

**Comment by hord-brayden** [comment]
I wouldn't say useless. They still don't leave prints and have the guidebook functionality - but they'd be more relegated to a flavor item. 

Like robohands, power gloves, fingerless insuls, etc.

**Comment by CrigCrag** [comment]
this would make detective as a role even less useful and probably borderline useless.

unless I missed it I'm pretty sure the only discussion of allergies being added in the last month or so was an ideamen post that brought up a loose concept

**Comment by metalgearsloth** [comment]
> The purpose of latex and nitrile gloves in medicine is to not leave traces.

It's for diseases which is TBC.

**Comment by BolloTea** [comment]
Sorry, what I will say most likely does not apply to this repository.  But, it would be nice to expand the list of "fibers" or "materials", for example from Hardsuits or clothing.  For earlier, I’ll say that an experienced player will not be forced by the difficulty to intentionally mislead the detective by simply changing clothes, and so, the detective will have more clues to identify the criminal.  Again, sorry for being off topic.

**Comment by JoeHammad1844** [comment]
on TG nitrile (and I think latex) gloves speed up the application of medical items, like bruise packs and syringes, maybe they could do that instead?

**Comment by JoeHammad1844** [comment]
but I am supportive of the change

**Comment by hord-brayden** [comment]
let me know if you want me to close it or whatever works, i'm not butthurt as it took me all of 12 seconds to author!

Thanks everyone for your feedback, learning more everyday

**Comment by metalgearsloth** [comment]
I appreciate the effort but I think forensics needs to be more impactful as it's fairly underutilised and this is just going to make it less so.

**Pull request closed without merging**
