### PR TITLE
Pipe Bombs

### PR DESCRIPTION
**Pull request by Interrobang01**
## About the PR 

super duper unfinished PR, will make presentable soon

PR formerly known as the "Potassium Chlorate"

**Media**

https://user-images.githubusercontent.com/113810873/208823699-4bc6bb6e-b043-4e1a-9c2c-61eccc9cdfc9.mp4

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: literally nothing

### CODE REVIEW

**Comment by mirrorcult** [comment]
dont add explosive powder if its not going to do anything

**Comment by PixelTheKermit** [comment]
The explosive powder could be a lathe resource

**Comment by Interrobang01** [comment]
I need to make some more changes to this as requested, them being adding a basic use for the powder, making the recipe harder to do, and moving the powder prototype to materials and making it latheable.

As such, gonna convert this into a draft.

**Comment by CaptainSqrBeard** [comment]
thanks for pipe bomb recipe 💥

**Comment by Vej-sys** [comment]
One crossed wire, one wayward pinch of potassium chlorate, one errant twitch... and kablooie!

**Comment by PixelTheKermit** [comment]
Add the ullapool caber :godo:
_"A sober person would throw it"_

**Comment by Interrobang01** [comment]
as i am temporarily back from my caves-of-qud-induced hiatus, i have decided from the advice of others to rebrand this from the "potassium chlorate PR" to the "pipe bomb PR". i'm gonna probably maybe try to work on this more again soon

**Comment by metalgearsloth** [comment]
re-open if you work on it.

**Pull request closed without merging**
