### PR TITLE
Warden Hat Texture Change

### PR DESCRIPTION
**Pull request by TeaMakiNL**
About the PR
Changed the texture for the warden's hat when it's being worn

Why / Balance
Fixes [#29286](https://github.com/space-wizards/space-station-14/issues/29286) Doesn't affect balance.

Technical details
Added credits to myself in meta code.

Media
equipped-HELMET

Requirements

[X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
[X] I have added media to this PR or it does not require an ingame showcase.

Breaking changes
None

### CODE REVIEW

**Comment by TeaMakiNL** [comment]
Screenshot (1436)

**Comment by DieselMohawk** [comment]
Good job

**Comment by TeaMakiNL** [comment]
About the PR


Why / Balance


Technical details


Media


Requirements

[X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
[X] I have added media to this PR or it does not require an ingame showcase.


Breaking changes


Changelog

**Comment by JIPDawg** [comment]
Also putting "fixes  #29286" in the "Why/Balance" Section will auto close the original issue. (doesn't have to be in that section, but that's usually where people put it)

**Comment by JIPDawg** [comment]
and slight suggestion as it isn't obvious to some is maybe showing a picture of the before and after on a person.

**Comment by UbaserB** [comment]
can you show a photo of how it looks ingame please

**Comment by TeaMakiNL** [comment]
Can't show in-game view at the moment due to poor wifi and not being able to access the warden role in any server.

**Comment by Boaz1111** [comment]
just use localhost?

**Review by UbaserB — APPROVED** [review]
LGTM

**Comment by slarticodefast** [comment]
I went ahead and removed the changelog entry since resprites without gameplay impact should not get logged according to the PR guidelines. Otherwise thank you for the resprite and your first contribution!

**Pull request merged**
