### PR TITLE
Update zombie regen

### PR DESCRIPTION
**Pull request by nomad0260**
## About the PR 

**Changelog**

Change Bicaridine to omnizine, because zombie do not normal regen hp and lay in crit all round

:cl:
- fix: zombie now have normal regen!

### CODE REVIEW

**Comment by Elijahrane** [comment]
1u bicardine:
1.33 blunt
1.33 slash
1.33 piercing
Total: 4 damage

5u omnizine:
6.67 blunt
6.67 slash
6.67 piercing
10 toxin
10 radiation
10 asphyxiation
10 bloodloss
6.67 heat
6.67 shock
6.67 cold
Total: 80 damage

**Comment by nomad0260** [comment]
> 1u bicardine: 1.33 blunt 1.33 slash 1.33 piercing Total: 4 damage
> 
> 5u omnizine: 6.67 blunt 6.67 slash 6.67 piercing 10 toxin 10 radiation 10 asphyxiation 10 bloodloss 6.67 heat 6.67 shock 6.67 cold Total: 80 damage

zombie has attacked mostly a blunt, slash, piercing.
in rare incident have a heat or shock.
and we have 
5u omnizine:
6.67 blunt
6.67 slash
6.67 piercing
6.67 heat
6.67 shock
total: 33,35

maybe i overdid with omnizine, but 1 bicardine this very few
i look how many need time to stand up from crit (zombie take a slash damage from crowbar) and... he dont stand up

**Comment by CaptainSqrBeard** [comment]
Are they supposed to heal in crit? Code says that they heals after dealing damage. So now you just will get a large amount of health after hitting someone, making you OP in melee. Did you even tested your changes?

**Comment by EmoGarbage404** [comment]
5u omnizine after each hit is ridiculous.

**Comment by JustinTrotter** [comment]
Would this make two zombies be able to slowly hit each other to full heal?

**Comment by EmoGarbage404** [comment]
> Would this make two zombies be able to slowly hit each other to full heal?

Pretty sure zombies dont heal from each other.
Source: i wrote it.

**Comment by nomad0260** [comment]
> Are they supposed to heal in crit? Code says that they heals after dealing damage. So with these changes you will get a large amount of health after hitting someone, making you OP in melee. Did you even tested it?

Yeah, my bad, i read code wrong
But, zombies in 1 to 1 with a greytide with crowbar, zombie win anything (tested on corvax), for heal in battle 5 omnizine is not a OP, maybe, in isolated cases this give a win zombie, but what i see,

**Comment by metalgearsloth** [comment]
Zombies shouldn't be winning every 1v1, hot take.

**Comment by mirrorcult** [comment]
this is WAY too much

**Pull request closed without merging**
