### PR TITLE
Small addition to mercenary items

### PR DESCRIPTION
**Pull request by Jackal298**
Second try

## About the PR

Initially, this work was supposed to be larger and had to contain a special box in which all the items of the mercenary would be stored, as well as a set of things for the admin panel, but due to work and heat, I could not make them, pr included 4 things for caches:

Mercenary gas mask - similar to explorer gas mask and SWAT gas mask
Mercenary beret
Mercenary helmet - similar in protection to a regular helmet
Mercenary combat gloves - similar to the original gloves, but leave olive fibers

UPD:  I accidentally uploaded the PR to the old thread and it didn’t happen what I wanted, now I did everything right

**Media**

3 Merc

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added 4 new mercenary items

### CODE REVIEW

**Comment by Emisse** [comment]
goncflict

**Comment by Jackal298** [comment]
> goncflict

It's okay now?

**Comment by deltanedas** [comment]
you need to merge master and fix the conflicts then commit it

**Comment by Jackal298** [comment]
> you need to merge master and fix the conflicts then commit it

did i do everything right?

**Comment by Jackal298** [comment]
> goncflict

I fixed everything, check for problems

**Pull request closed without merging**
