### PR TITLE
Make bladed flatcap embed on hit

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Makes the item embed into entities when thrown/drag-pushed.

## Why / Balance

It is currently being dragged and flung-pushed to damage entities multiple times.

**Changelog**

:cl: Whisper
- tweak: Bladed flatcaps now embed on throw.

### CODE REVIEW

**Comment by Plykiya** [comment]
feels like we should just fix the dragging being throwing code since it affects like 500 other things rather than implementing fixes for it being bad

**Comment by EmoGarbage404** [comment]
fyi pulling no longer uses throw code so you may want to just close this

**Comment by AJCM-git** [comment]
yeah this isnt necessary anymore

**Comment by QuietlyWhisper** [comment]
Thank god

**Pull request closed without merging**
