### PR TITLE
Add succumb action 10 sec delay

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

requires #33026
title

## Why / Balance

to prevent abusing/overusing etc.

## Technical details

no

## Media

no

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added 10 seconds delay to Succumb action

### CODE REVIEW

**Comment by Everturning** [comment]
how do people abuse succumb

**Comment by lzk228** [comment]
pressing it right after reviving at least

**Comment by thebadman4662** [comment]
> pressing it right after reviving at least

Just make them auto-cata if abused instead. :trollface:

**Comment by Cojoke-dot** [comment]
> pressing it right after reviving at least

Probably need something to prevent /suicide when you're cuffed or its not going to matter

**Comment by thebadman4662** [comment]
> > pressing it right after reviving at least
> 
> Probably need something to prevent /suicide when you're cuffed or its not going to matter

Or last words. :trollface:

**Comment by Everturning** [comment]
> pressing it right after reviving at least

sometimes i just wanna be a ghost and people reviving me get in the way of that

**Comment by superjj18** [comment]
> > pressing it right after reviving at least
> 
> 
> 
> Probably need something to prevent /suicide when you're cuffed or its not going to matter

Cuffs don't stop people from biting their tongues

**Comment by Cojoke-dot** [comment]
> > > pressing it right after reviving at least
> > 
> > 
> > 
> > Probably need something to prevent /suicide when you're cuffed or its not going to matter
> 
> Cuffs don't stop people from biting their tongues

If you want it can be a gag but that seems more boring for the person in cuffs. The other option is to not make it an instant death but instead 150 bleed instant and max bleed stacks, but that seems less funny for jokes.

**Comment by SlamBamActionman** [comment]
I think any attempt to stop a person who does not want to play from playing is not going to be successful. 

Someone suicides in cuffs, or spams succumb to prevent revival? As lame as it is they are not obligated to play out being jailed.

Make the game force a duncecap on them or something so the remaining players can laugh at them instead.

**Comment by Cojoke-dot** [comment]
> I don't think any attempt to stop a person who does not want to play from not playing is going to be successful.
> 
> Someone suicides in cuffs, or spams succumb to prevent revival? As lame as it is they are not obligated to play out being jailed.
> 
> Make the game force a duncecap on them or something so the remaining players can laugh at them instead.

They can just ghost if they don't want to play. The /suicide command should not be used to just win the DAGD after you got caught and didn't make sure you were round removed. Suicide is a very inglorious death.

**Comment by Vonsant** [comment]
useDelay does not work on the first use, so this PR has neither meaning nor functionality.

**Comment by lzk228** [comment]
working on it

**Comment by BramvanZijp** [comment]
If people dont want to play, I feel like making it harder for them to leave their character dead is only going to cause more issues.

**Comment by SlamBamActionman** [comment]
> Is this delay applied upon entering crit? If so, I like this because it means people can't just succumb to be immune to poison damage soft round removal.

This reason alone would be enough to approve the PR, imo.

**Comment by superjj18** [comment]
Imma be real with you dude, if I don't wanna play, or if I want to rage quit, or if I simply don't like playing with you, there's absolutely nothing you can do to truly stop me, and if you even try I'm probably going to annoy/mess up your gameplay out of pure spite.

Best to let sleeping dogs(dead players) lie with this one.

**Comment by superjj18** [comment]
> Is this delay applied upon entering crit? If so, I like this because it means people can't just succumb to be immune to poison damage soft round removal.

I don’t think poison should soft round remove anyways.

**Comment by Callmore** [comment]
`/suicide` and `/ghost` during crit still bypass the delay, not a huge issue for `/suicide` since it still detatches you from your body, but `/ghost` doesn't, which can be used to bypass the timer.

**Comment by SlamBamActionman** [comment]
The way I see it, this helps against powergamers immediately dying to make themselves easier to ressurect in poisoning scenarios, and 10 seconds isn't a lot of time to wait if you just wanna dip.

What's the point of /ghost vs /suicide anyways? Feels weird to have two commands that do the same thing, at least for a normal player (admins might need it I suppose for admemes).

**Comment by slarticodefast** [comment]
> The way I see it, this helps against powergamers immediately dying to make themselves easier to ressurect in poisoning scenarios, and 10 seconds isn't a lot of time to wait if you just wanna dip.

Yeah, I think it's good to have, not only for poisoning but for bloodloss as well. Should the same be maybe done for the "Say last words" action since it is the same as succumb just with a window confirmation popup?

**Comment by slarticodefast** [comment]
I did a small adjustment to add the delay to the "last words" action as well so it cannot be circumvented.
Thank you for your contribution!

**Review by slarticodefast — APPROVED** [review]

**Comment by lzk228** [comment]
no fucking way, a PR gets merged!

**Pull request merged**
