### PR TITLE
Add new headset and channel for admemes

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR 
Uses miner headset sprite to add a new radio channel meant to be used for admin events. Originally this was intended to be given to pirates, and while that's currently likely to be the primary use, a new channel should be made if pirates are coded to have their own headsets. These should not be mapped or obtainable without an admin spawning them.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
If you're going to add a pirate channel, just add one. If you need an admeme channel, use the centcomm one? I dont get why there needs to be a new one.

**Comment by 0x6273** [comment]
I think having a console command for adding new radio channels makes more sense. Then you can have any number of new radio channels for admin events instead of just one, and you could specify name and color in the command.

**Comment by metalgearsloth** [comment]
I think the prototype uploading issue should be fixed over working around it for content's sake.

**Comment by metalgearsloth** [comment]
prototype reloading got fixed ig.

**Pull request closed without merging**
