### PR TITLE
mild syndicate bundle additions

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

adds an MMI to the syndicate surgery duffel bag
adds a multitool and remote signaller to the syndicate C4 bundle
## Why / Balance

surgery bag - fun, you can gib someone and keep them as a morbid pAI or borg them, whatever
C-4 bundle - so you can have more flexibility and adds more value to the bundle
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: JoeHammad
- tweak: syndicate surgery bundles now contain an MMI
- tweak: syndicate C-4 bundles now contain a multitool and remote signaller

### CODE REVIEW

**Comment by CatMagic1** [comment]
surgery one is fun

c4 one may be accused of power creep and I don't think it's really required but eh

**Comment by JoeHammad1844** [comment]
it removes reliance on science which may or may not have signalers researched and having to find vendor mats which may or may not have their singular remote signaler in stock

**Comment by CatMagic1** [comment]
> it removes reliance on science which may or may not have signalers researched and having to find vendor mats which may or may not have their singular remote signaler in stock

yeah it makes more sense now, especially for a bundle

**Comment by keronshb** [comment]
I'd argue against the MMI until a proper syndicate borg is in, otherwise it's another form of baby jail and that's not fun.

**Comment by keronshb** [comment]
> > I'd argue against the MMI until a proper syndicate borg is in, otherwise it's another form of baby jail and that's not fun.
> 
> It's funny and adds more possibility for being able to do stuff after death
> 
> Plus people can just ghost if they want (lame)

No it's bloat and no purpose unless there's syndiborgs.

**Comment by CatMagic1** [comment]
> > > I'd argue against the MMI until a proper syndicate borg is in, otherwise it's another form of baby jail and that's not fun.
> > 
> > 
> > It's funny and adds more possibility for being able to do stuff after death
> > Plus people can just ghost if they want (lame)
> 
> No it's bloat and no purpose unless there's syndiborgs.

It's just adding a small fun use to an item no one EVER buys

I really can't see how this hurts the game

**Comment by JoeHammad1844** [comment]
so if you make me take it out, and then syndie borgs get added, are you just gonna have to add it back in? its future proofing if nothing else

**Comment by moonheart08** [comment]
I told you to stop making these.

**Comment by JoeHammad1844** [comment]
Cringe

**Comment by CatMagic1** [comment]
but he's been a good boi lately :<

**Pull request closed without merging**
