### PR TITLE
Add webhook for votekicks

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR adds webhook functionality to the votekick system, allowing servers to connect webhooks for votekick notifications.

The webhook is added in the cvar `discord.votekick_webhook`, similar to the `discord.vote_webhook`.

## Why / Balance

Admin request to make the instances of votekicks easier to track.

It only sends updates for votes that have been initiated; if e.g. not enough ghosts are around to initiate a votekick, the message won't be sent. Cancelled votekicks are sent however, e.g. if the target is a de-admined admin.

## Technical details

I've had to separate the vote webhook functionality into its own script; it's been added to `Webhooks/VoteWebhooks.cs`, for possible future webhooks. This way the previously private functions can be reused for votekicks.

## Media

image
image
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

.ftl file `administration/commands/custom-vote-command.ftl` has been moved to `discord/vote-notifications.ftl` with added lines.

**Changelog**

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
These strings need to be localized. Otherwise looks good

**Comment by lzk228** [comment]
what is the difference between colors in message?

**Comment by SlamBamActionman** [comment]
> what is the difference between colors in message?

The little side thing in Discord; red, green or yellow

**Comment by lzk228** [comment]
i mean, do they mean something?

**Comment by SlamBamActionman** [comment]
> i mean, do they mean something?

Red: In progress vote
Green: Finished vote
Yellow: Cancelled vote

This matches the behavior of how custom votes are displayed

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
