### PR TITLE
Biocoded clothing

### PR DESCRIPTION
**Pull request by Macoron**
## About the PR

Adds biocoded clothing similar to Rimworld. Biocoded clothing will remember first wearer as its owner. It will refuse to be worn by anyone else until owner would disable biocoding or clothing would be emaged.

Biocoding added for all syndie hardsuits. Main motivation is that during nuke ops, greytiders really like to grab overpowered red hardsuits. This lead to confusion, friendly fire and powergaming.

I would also recommend to add this to other overpowered hardsuits, like ERT, death squad, CBURN, etc in separate PR.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/6161335/af6f5ab5-4e85-4028-bff9-32d906d3ae5a

**Changelog**

:cl:
- add: Syndicate has added a biocoding system to all of their hardsuits. Biocoding allows hardsuit to remember its first wearer as the owner. It will refuse to be worn by anyone else.
- add: Clothing biocoding lock can be disabled by owner or emag.

### CODE REVIEW

**Comment by CaptainSqrBeard** [comment]
Why wouldn't return them round-start microbomb implants? They're supposed to destroy operative loot on death.

**Comment by deltanedas** [comment]
that would make the stealthop suicide bombing cap strat stupidly strong since you just /suicide and boom hes dead no counter, versus having to buy macrobomb you get a few seconds to react to beeping

**Comment by GoodWheatley** [comment]
> that would make the stealthop suicide bombing cap strat stupidly strong since you just /suicide and boom hes dead no counter, versus having to buy macrobomb you get a few seconds to react to beeping

Microbombs don’t trigger on /suicide, and they don’t explode instantly

**Comment by deltanedas** [comment]
microbombs do trigger on suicide ans are instant, fire up ninja, antag ctrl then suicide

**Comment by DawBla** [comment]
The important thing is that the game has m**i**crobomb and m**a**crobomb implanters
Microbomb is designed to let you detonate it whenever you want, be it suicide or it even has a designated detonation action button and you cannot get it outside of Pirate Captain Chest
Macrobomb is designed to only detonate on your death and you cannot trigger it yourself, if you have the implant and type /suicide you will go catatonic and not die, hence no explosion. This one you can get as a nukie for example

**Comment by metalgearsloth** [comment]
I don't like this because you may as well biolock every piece of syndie equipment if you want to reduce friendly fire and macrobombs already covers off this.

**Comment by metalgearsloth** [comment]
Relevant discord convo is here https://discord.com/channels/310555209753690112/770682801607278632/1106580202219376711

**Pull request closed without merging**
