### PR TITLE
Rename nitrogen internals crate

### PR DESCRIPTION
**Pull request by MossyGreySlope**
## About the PR
Renames "slimeperson life support crate" to "internals crate (nitrogen)". This makes the crate name consistent with other internals crates, and ensures that anyone searching for "nitrogen" (such as a Vox player needing new tanks) can find it easily. This also adds "Intended for Slimepeople and Vox." to the description, which means the crate will show up in searches for either species name.

## Why / Balance
Currently, it's not obvious that someone looking to buy nitrogen tanks from Cargo should be searching for something named "Slimepeople", especially if their character is not a Slimeperson.

## Technical details
- Changes the id of the crate from `CrateSlimepersonLifeSupport` to `CrateNitrogenInternals`.
- Change the name of the crate from "slimeperson life support crate" to "internals crate (nitrogen)"
- Adds an extra sentence to the crate description.

## Media
internals
vox
description
crate
contents

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Rename the "slimeperson life support crate" to "internals crate (nitrogen)".

### CODE REVIEW

**Review by slarticodefast — CHANGES_REQUESTED** [review]
add the renamed entity to migrations.yml so that maps don't break

**Comment by MossyGreySlope** [comment]
> add the renamed entity to migrations.yml so that maps don't break

That's just and extra two lines to `migrations.yml`, which is unrelated to the EF database migrations, correct?

**Comment by Boaz1111** [comment]
yep, since you replaced an ID, any maps with that spawned will have issues if you do not do that

**Review by slarticodefast — APPROVED** [review]
Thanks for the cleanup!

**Review by Errant-4 — APPROVED** [review]
Looks fine, test fail unrelated

**Pull request merged**
