### PR TITLE
Set frezon sell price to 0

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

There are multiple atmos bugs that currently allow essentially infinite frezon generation.
#14287
#13748

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Frezon prices have tanked due to a recent influx of supply.

### CODE REVIEW

**Comment by asperger-sind** [comment]
This change is odd.
I don't think it's a good idea to make frezon worthless over bugs affecting atmos as a whole.

**Comment by potato1234x** [comment]
> This change is odd. I don't think it's a good idea to make frezon worthless over bugs affecting atmos as a whole.

this

**Comment by Ilya246** [comment]
the issue is greatly exaggerated here, #14287 isn't even a bug, it's just a property of the frezon mixing reaction, and #13748 doesn't allow for accelerated trit production either since even without that bug you would still be able to just make a bigger mix chamber

**Comment by EmoGarbage404** [comment]
Gas sell prices have always been quite strange. Firstly, all gases are infinite in supply, so their prices should theoretically be nothing. I know that trit and frezon need a mix chamber, but any tech worth their salt can set one up pretty easily. As such, from that point, you can produce basically infinite money in a system that doesnt even involve cargo.

My tl;dr is that atmos money is too easy and pretty lame for cargo. This nerf is fine. Atmosheads stay mad.

**Comment by Ilya246** [comment]
the price at least shouldn't be 0, should be maybe around 1/mole instead

**Comment by Cheackraze** [comment]
This is a terrible solution... should instead fix the bugs that allow for infinite production instead

**Comment by GoodWheatley** [comment]
> Gas sell prices have always been quite strange. Firstly, all gases are infinite in supply, so their prices should theoretically be nothing. I know that trit and frezon need a mix chamber, but any tech worth their salt can set one up pretty easily. As such, from that point, you can produce basically infinite money in a system that doesnt even involve cargo.
> 
> My tl;dr is that atmos money is too easy and pretty lame for cargo. This nerf is fine. Atmosheads stay mad.

Pretty sure this is supposed to be a temporary change until the bugs regarding frezon production are fixed.

**Comment by EmoGarbage404** [comment]
I understand that, but tbqh atmos money making has always been meta for cargo, which is really lame considering how uninvolved it is on Cargos side. I get that it's departmental cooperation, but cargo really just has to bug atmos techs and then just wait. In return, they get massive returns at low cost and effort on their part.

**Comment by mirrorcult** [comment]
if youre going to do this which you shouldn't because this is dumb then just remove gas selling entirely

**Comment by GoodWheatley** [comment]
> I understand that, but tbqh atmos money making has always been meta for cargo, which is really lame considering how uninvolved it is on Cargos side. I get that it's departmental cooperation, but cargo really just has to bug atmos techs and then just wait. In return, they get massive returns at low cost and effort on their part.

I feel like that’s more of an issue with cargo having no easy/fun way to earn money by themselves than with gas prices

**Comment by EmoGarbage404** [comment]
> if youre going to do this which you shouldn't because this is dumb then just remove gas selling entirely

Tbh im not opposed until gas has some sort of supply. Gas miners are just free money, considerint a decent setup can get you enough to offset the cost of a canister to package more.

**Comment by Emisse** [comment]
ok yes cargo having infinite money is bad but at least this is higher effort than them selling vending machines and stuff and also gives atmos something to do in game. id rather just have it bugged while we wait for fixe to rounding errors

**Comment by Ilya246** [comment]
there are no rounding errors, i explained it in the issue, the frezon burn reaction is just apparently wrong?

**Comment by Ilya246** [comment]
and no, atmos usually make gases specifically to sell, i don't think you'd often see atmos making trit, frezon, or N2O for the sake of it

**Comment by moonheart08** [comment]
This is a PR made to get a reaction and not propose a proper solution to the problem (i.e. **fixing bugs.**)

Do not make a point by pulling a knife, make a point with your words.

**Pull request closed without merging**
