### PR TITLE
Tripwires

### PR DESCRIPTION
**Pull request by PixelTheKermit**
## About the PR

Adds tripwires into the game. These slip you for a second with a secondary feature of firing a signal
The tripwires have 35 hitpoints, and take 35 upon tripping, instantly destroying them.

## Why / Balance

Thought this would be interesting to add and it could help spice up traitor gameplay by allowing them trap rooms.

## Technical details

There's a new StepTriggerSignalComponent that fires a signal with the help of StepTriggerComponent.
There's also now a DamageTriggerOnTriggerComponent, which damages the trigger upon it being triggered.
And then there's DamageSignalComponent, that does what SlipSignalComponent does, but for damage.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/85175107/9b133280-4e1f-4fee-91e4-8782ab6e078a

https://github.com/space-wizards/space-station-14/assets/85175107/2745ebc6-eed6-4198-b522-7d639efbcaf7

https://github.com/space-wizards/space-station-14/assets/85175107/a64e7f3f-7921-4bc1-b686-266b3c06db6f

## Breaking changes

**Changelog**

:cl: PixelTK
- add: Added tripwires! These can be crafted with a few LV cables and steel. It can trip and it can send signals. Useful for making traps, yet they're not very durable.

### CODE REVIEW

**Comment by mirrorcult** [comment]
they're a little conspicuous as traps

**Comment by deltanedas** [comment]
break lights guaranteed to be unseen

**Comment by metalgearsloth** [comment]
Make it function like the tripwires in sniper elite (1 use to activate, another to place) so you can place it at any angle.

**Comment by PixelTheKermit** [comment]
> Make it function like the tripwires in sniper elite (1 use to activate, another to place) so you can place it at any angle.

I'll keep that in mind.

**Comment by JoeHammad1844** [comment]
dastardly contraption, this has a LOT of potential

**Comment by PixelTheKermit** [comment]
Going to draft this and try to do @metalgearsloth 's suggestion.

**Comment by NancokPS2** [comment]
Is the tripping hard coded?  
Would be nice to have non-tripping wires as well.

**Comment by PixelTheKermit** [comment]
> Is the tripping hard coded? Would be nice to have non-tripping wires as well.

The tripping is literally just slipping, so no it's not hardcoded.
I am turning SlipSignal into StepTriggerSignal, which should allow for the non-tripping wires, however I'm unsure if I actually want non-tripping wires (they are *trip* wires afterall)

**Comment by Mudsson** [comment]
Do things that go under doors like mice and rats still set it off? Might be annoying to have people throw mice onto them like with mines.

Great idea by the way, this is gonna be awesome.
Can't wait to have tripwire close and bolt the door you went through then blow open a hole into space.

**Comment by forgotmyotheraccount** [comment]
Looks great, only thing I'd want added would be new sfx; one for tripping over (a thud rather than the standard wet slip) and one for the tripwire breaking (something like a guitar string snapping).

**Comment by PixelTheKermit** [comment]
> Going to draft this and try to do @metalgearsloth 's suggestion.

I couldn't figure out how to code this, so this will have to do for now.

**Comment by PixelTheKermit** [comment]
> Looks great, only thing I'd want added would be new sfx; one for tripping over (a thud rather than the standard wet slip) and one for the tripwire breaking (something like a guitar string snapping).

Something like this?

https://github.com/space-wizards/space-station-14/assets/85175107/852c9f3e-6646-42ff-87e1-5d2ff4e30273

**Comment by forgotmyotheraccount** [comment]
excellent

**Comment by Partmedia** [comment]
I know that this PR pre-dates https://github.com/space-wizards/space-station-14/pull/20714, but I think it makes a little more sense for the check to be weight-driven. Assuming the other PR is merged, would this be a matter of respriting it and updating the crafting recipe?

**Pull request closed without merging**
