### PR TITLE
epic jetpack move

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

jetpacks now fly on grids!

## Why / Balance

because unusable jets in zero gravity environment make no sense

## Technical details

i added another check to see if gravitycomponent is enabled. that's it.

## Media

https://github.com/space-wizards/space-station-14/assets/113782077/77ae687d-c028-47e2-90bc-013d7a5df966

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Jetpacks are now usable on grids.

### CODE REVIEW

**Comment by DogZeroX** [comment]
This been rejected a couple times now

**Comment by whateverusername0** [comment]
> This been rejected a couple times now

what why

**Comment by DogZeroX** [comment]
#24672

**Comment by exincore** [comment]
See #24672 and #16056. Also, feature freeze.

**Comment by beck-thompson** [comment]
See:
#24672
#14565
#16056

I think its one of those ideas that sounds good on paper (and makes logical sense) but is OP once you think about it!

**Comment by notquitehadouken** [comment]
it's also because it fatally errors whenever you turn off your jetpack

**Comment by whateverusername0** [comment]
now that we have #29009 can it get merged?

**Comment by whateverusername0** [comment]
or reopened at least

**Pull request closed without merging**
