### PR TITLE
New wooden tiles

### PR DESCRIPTION
**Pull request by NotSoDana**
## About the PR

Added some new wooden floor tiles with different colors + resprited old.

## Why / Balance

It will be useful in mapping, due to the wide variety. Think it wouldn’t be superfluous for the decoration of many places at the stations.

## Media

Screenshot_35
Screenshot_36

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Dezzzix
- add: Added some new wooden tiles
- add: Added wood parquet floor
- tweak: Resprited old wood tiles

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I don't think the new tiles are sufficiently useful to warrant all the extra variants and entities. The different types of wood are cool but largely superfluous since i really don't see much of a context that would warrant using a lot of these.

The larger issue is really the actual floor sprites. I don't think these are really a markable improvement on the current wood floors and I would rather keep the ones we have presently.

As such, I'm opting to close this PR. Thank you for your contribution. Feel free to continue contributing in the future.

**Comment by UbaserB** [comment]
> I don't think the new tiles are sufficiently useful to warrant all the extra variants and entities. The different types of wood are cool but largely superfluous since i really don't see much of a context that would warrant using a lot of these.
> 
> The larger issue is really the actual floor sprites. I don't think these are really a markable improvement on the current wood floors and I would rather keep the ones we have presently.
> 
> As such, I'm opting to close this PR. Thank you for your contribution. Feel free to continue contributing in the future.

can i ask you to not close it because ill genuinely use these variants as a mapper, ive been waiting on it for ages

**Comment by Pixeltheaertist** [comment]
are forks able to use these sprites? they're really good

**Comment by NotSoDana** [comment]
> are forks able to use these sprites? they're really good

Of course you can use it with copyrights on me: "NotSoDana" or "Dezzzix"

**Pull request closed without merging**
