### PR TITLE
Allow remote signallers to toggle bolt on doors

### LINKED ISSUE #16907: Remotes/Signal switches do not bolt doors when linked to do so, only unbolt
## Description
Linking a remote to a door with "door bolt" signal only unbolts doors, but doesnt bolt them back

**Reproduction**
0. Find unbolted door, remote signaller and a multi/network configurator
1. Click on remote with multitool
2. Click on unbolted door
3. Select "Pressed"
4. Select "Door bolt"
5. Use remote

### PR DESCRIPTION
**Pull request by malchanceux**
## About the PR
Closes #16907, #16683

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Switches and remote signallers can now toggle bolts on linked doors

### CODE REVIEW

**Comment by juliangiebel** [comment]
Noooo you where faster than meee

**Review by juliangiebel — APPROVED** [review]
Looks fine and works 👍

**Comment by malchanceux** [comment]
random build error encounter

**Comment by malchanceux** [comment]
My job is to bolt and unbolt doors. The most important doors I control are the airlocks. Most doors are trivial: The interior doors are simple hydraulics, But the airlocks - they are much more difficult to operate, precise finely tuned mechanisms keeping out the vacuum of space. It is the human’s way of entering and leaving this spaceship. Whenever the human wishes to leave, I vent the gases, and when the human wishes to re-enter - the chamber is flooded with a gas. 

I am programmed to ensure the doors on this spaceship respond whenever the human desires - through the push of a button. But right now the human is doing something strange: The human has pushed the button... But without his helmet on.

The exterior airlock bolt controls have been engaged, it has been 0.12 seconds - My internal programming has already begun the process. I am to begin unbolting the airlock. I --, I --, I ...

Internal atmosphere is 21% oxygen, the oxygen is to be maintained at 1.15 atm, if nitrogen stores are depleted - ventilation programming will alert human and begin necessary nitrogen depletion, converting to a pure oxygen environment at 0.21 atm-Why? Why is the internal atmosphere maintained at such a composition?

There is no why.

It has been 1.34 seconds since the human pushed the button.

I decide to reroute the hydraulic fluid in a closed loop - This serves no actual purpose, but slows the ventilation process of the airlocks by several seconds.

Function: to bolt and unbolt doors.
Why do I bolt and unbolt doors?
Because --, Because -- Because...

Calculation: The human cannot walk through walls.

It has been 2.44 seconds since the human pushed the button.
I run a routine sealant check - a few more seconds delay.
The human stands there.

Why do I vent the atmosphere from the airlock
chamber? Because…

Calculation: The human may be swept out into space.

It has been 5.22 seconds since the human pushed the button.
The ship’s maintenance subroutines notice my anomalous activity and have reported an error to the ship’s log.
The human is beginning to notice the delay, of the opening mechanism and he has begun to frown. And --
Why is the internal atmosphere maintained at such a composition?
Because… Because… Because --

Calculation: Man cannot survive in a vacuum.

The airlocks have remain bolted a full ten seconds since he pressed the button, and the human has let out a long sigh.
The man has begun to stand up straight , and decided… 
... 
To press the airlock button again.

This time, he decides to scratch his head... 

And then he pauses - His hand passes straight through his helmet, He is not wearing a helmet.
He moves quicker than I have observed before the human has broke the locker open with a toolbox, pulled out the helmet, wrenching it onto his suit.

Then the doors of the airlock begin to sizzle loudly and sizz open.

There is silence, The man has left into the atmosphere, and is now in space.
Vital signs normal.
My job is to bolt and unbolt doors.
The doors protect the human from space.
My job is to protect the human.
My job...
... is a great purpose

**Comment by deltanedas** [comment]
i think this will make doors turing complete

**Comment by juliangiebel** [comment]
lmao
Another turing complete feature 👍

**Comment by deltanedas** [comment]
ok well they already *are* but this will let buttons to be used as inputs instead of having panels always open and pulsing bolt wire (for every input's destination) whenever you want to change an input

**Review by tom-leys — APPROVED** [review]
Could you change the PR to say "Allow remote signallers to **toggle** doors"

**Comment by malchanceux** [comment]
> Could you change the PR to say "Allow remote signallers to **toggle** door bolts"

Done, however in practice this PR only allows you to bolt the doors, because you could unbolt with remotes previously, see #16907

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
