### PR TITLE
fix(Meta): Resolve every issue.

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Resolved every open issue.

Resolves https://github.com/space-wizards/space-station-14/issues/20788
Placed tiny fans on the airlocks to space

Resolves https://github.com/space-wizards/space-station-14/issues/27915
Linked the buttons

Resolves https://github.com/space-wizards/space-station-14/issues/27916
Rotated the shutter button

Resolves https://github.com/space-wizards/space-station-14/issues/28325
Replaced with large station miners

## Why / Balance

Resolves https://github.com/space-wizards/space-station-14/issues/20788
Resolves https://github.com/space-wizards/space-station-14/issues/27915
Resolves https://github.com/space-wizards/space-station-14/issues/27916
Resolves https://github.com/space-wizards/space-station-14/issues/28325

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
Can you elaborate on how you fixed the issues? 
The salvage airlock thing in particular, we're moving away from using tiny fans if that's what you did.

**Comment by Brandon-Huu** [comment]
> Can you elaborate on how you fixed the issues? The salvage airlock thing in particular, we're moving away from using tiny fans if that's what you did.

Yes

**Comment by Brandon-Huu** [comment]
> Can you elaborate on how you fixed the issues? The salvage airlock thing in particular, we're moving away from using tiny fans if that's what you did.

Should I use directional fans instead of tiny fans?

**Comment by IProduceWidgets** [comment]
> > Can you elaborate on how you fixed the issues? The salvage airlock thing in particular, we're moving away from using tiny fans if that's what you did.
> 
> Should I use directional fans instead of tiny fans?

Nah, just make the airlock smaller if its worth doing that.

**Comment by TurboTrackerss14** [comment]
imma be real https://github.com/space-wizards/space-station-14/issues/20788 looks more like a non-issue now currently. 
Because we have low pressure lockout and (atleast personally) I haven't seen any reports of cargo spacing more frequently since the issue first went live.

**Comment by Brandon-Huu** [comment]
Oop, I was just about to remove the tiny fans I added.

**Pull request merged**
