### PR TITLE
make radiator unary

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
changes radiator from being inlet/outlet to just exchanging heat with the environment and the pipenet
it is also no longer throughput based since that was bad
also a little prototype cleanup

@Partmedia 

## Why / Balance
- being directional meant sometimes it would lock up and do nothing while visually they are not directional, making it hard to debug a broken radiator setup
- having discrete inlet/outlet made giant radiator arrays very slow
- being throughput based was bad since youd expect a radiator full of hot plasma to radiate heat, shouldnt matter if you put a pump on the end of it. the old way also did not work on any map teg setup roundstart since theyd expect a unary radiator that cools passively rather than only when theres high throughput
- roundstart teg setups are less useless than they were before
- big radiator arrays are much more functional now as they all cool the same pipenet so more radiator = cooler

## Technical details
ripped out all inlet/outlet pressure difference logic and made it just based on time and temperature difference to the environment.
also cleaned it up a bit, a few less cryptic variable names

## Media
a few mins in space cools even plasma down a good bit with a big radiator array

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
HeatExchanger component and system moved into Piping.Unary Components/EntitySystems namespaces respectively.

**Changelog**
:cl:
- tweak: Radiators are now unary meaning they no longer need to be in a pumped pipeline to work, they can now passively exchange with no throughput needed.

### CODE REVIEW

**Comment by Ilya246** [comment]
i would approve of this, much more intuitive than the old behavior and fixes issues arising from the integration not being perfect

**Comment by Partmedia** [comment]
I'm willing to entertain this. Of course I don't like this and think that atmos would be more realistic, engaging, and fun to play if gases were driven by pressure differences and flowed through devices but it sounds like this is universally too hard for people. To address your individual points:

- This could be fixed with a sprite change
- You can speed it up by increasing the gas flow rate coefficient
- Being unary is bad because you'd expect flowing more gas to increase rate of radiation; there is now no way to control the radiators
- Those are problems with the roundstart TEG setups, not with radiators
- You could have gotten an effective big radiator array with current code by connecting radiators in parallel, not series.

Some compelling answers to these could change my mind.

**Comment by deltanedas** [comment]
> You could have gotten an effective big radiator array with current code by connecting radiators in parallel, not series.

sure a few people know this but its not at all intuitive

> Being unary is bad because you'd expect flowing more gas to increase rate of radiation; there is now no way to control the radiators

do you really ever need to do that? anyway signal valves can do this if you really want to stop radiating a cooling line

**Comment by Partmedia** [comment]
I'm going to need some stronger responses to more of the points to be convinced.

> > You could have gotten an effective big radiator array with current code by connecting radiators in parallel, not series.
> 
> sure a few people know this but its not at all intuitive

One could argue that being more realistic is more intuitive.

> > Being unary is bad because you'd expect flowing more gas to increase rate of radiation; there is now no way to control the radiators
> 
> do you really ever need to do that? anyway signal valves can do this if you really want to stop radiating a cooling line

Yeah, when you're using radiators to cool/heat a station you don't want it pegged to ± infinity. If you were making frezon you want just under 70K without going too low.

**Comment by Ilya246** [comment]
> One could argue that being more realistic is more intuitive.

only up to a rather shallow point, after that it gets much less intuitive and weird unless you have a background in the related subject
we should remember that this would apply to almost all atmos, or other, players

**Comment by deltanedas** [comment]
> Yeah, when you're using radiators to cool/heat a station you don't want it pegged to ± infinity. If you were making frezon you want just under 70K without going too low.

how id imagine a station heating solution is storage with hot and cold gas which can be pumped into/out of the station radiator loop
then just pump in hot gas until station is warm, pump it back out.
the radiators and supermatter/burn chamber/whatever to source the heat never get turned off, the pumps to station radiator line do

**Comment by Partmedia** [comment]
Current radiator behavior requires a pressure difference to move gas through, just like the TEG. Are you saying that the TEG should also be unary on each side, too?

**Comment by deltanedas** [comment]
> Current radiator behavior requires a pressure difference to move gas through, just like the TEG. Are you saying that the TEG should also be unary on each side, too?

all this changes with teg is making a cooling loop actually viable instead of being forced to either superheat coolant input so t^4 kicks in or just giving up and using a freezer

**Comment by Partmedia** [comment]
> all this changes with teg is making a cooling loop actually viable instead of being forced to either superheat coolant input so t^4 kicks in or just giving up and using a freezer

You realize now that there will be no "loop" if everything is unary, and that you were never supposed to be able to cool the cold side with a freezer. I don't find these arguments compelling.

If everything were unary, maybe that would make sense. But as it stands, it seems to me that heaters and freezers should become binary for consistency.

**Comment by deltanedas** [comment]
> You realize now that there will be no "loop" if everything is unary, and that you were never supposed to be able to cool the cold side with a freezer. I don't find these arguments compelling.

yes you arent supposed to and thats the point, radiators were so useless before this that you had to use le thermodynamically unsound freezer

and of course by loop i mean just a single pipenet

**Comment by Partmedia** [comment]
This TEG setup is just fine, without making radiators unary. I don't see what's so broken about radiators. Is this just major TEG skill issue?

https://github.com/space-wizards/space-station-14/assets/3229565/f8c229a4-7679-4527-a4bd-86cea80a5561

**Comment by deltanedas** [comment]
because currently they are throughput based and no throughput means no radiating

**Comment by deltanedas** [comment]
bruh non 0K gas molecules will still bump into the pipe walls and transfer heat to be radiated out

**Comment by Partmedia** [comment]
> bruh non 0K gas molecules will still bump into the pipe walls and transfer heat to be radiated out

Sure, add that to radiators instead of ripping out two ports, then.

**Comment by deltanedas** [comment]
still no reason for it to be throughput based, if anything that would hurt radiation since each molecule has less time to transfer heat to the radiator

**Comment by Partmedia** [comment]
> Here's is a direct quote from the intent of the original PR that implemented radiators:
> 
> > Only the gas flowing through the radiator have an opportunity to randomly bounce against the walls of the radiator, transferring heat.
> 
> It seems to assume that gas particles are somehow not impacting with the surface area of the vessel without an outside force moving them. I'm not well versed in physics, so I would be interested in the rationale behind this.

I'm the author of the original PR. The rationale is to make radiators behave in a manner consistent with real life, without simulating every single excruciating detail and grinding game performance to a halt.

You may have encountered these European-style radiators:

image

There's a little valve that controls fluid flow. When you shut off the valve, the heater doesn't heat anymore. Yes, the little bit of gas that's still left in the pipe does bump into the walls of the radiators and radiate. But since the valve is shut off, no more gas can flow in, and so when the gas already inside the pipe gives its heat to the radiator, it gets stuck there. **If there's no flow, there's no heat.**

What's different from real life and SS14 is that SS14 is a game, and things have to be fast. Therefore, when you allow a radiator to be unary and cool everything in the pipe, it cools not only what's in the pipe, but the whole pipenet. This is wholly unrealistic, because only a fraction of the whole pipenet can actually bump into the walls of the radiator. But this is an optimization that is required to make things fast.

So, the current behavior of only counting gas flowing through is a proxy to get imperfect, game-simulation atmos to behave in a way that is consistent with real life.

> still no reason for it to be throughput based, if anything that would hurt radiation since each molecule has less time to transfer heat to the radiator

Go study fluid dynamics please. [This is the first Google result](https://www.overclockers.com/water-cooling-flow-rate-and-heat-transfer).

**Comment by Ilya246** [comment]
right now ss14 gas physics pretends that all gas in a pipenet is "one gas", so making radiators unary would actually be more consistent with the current model, as gas does not have to move to do that

besides, if we want realism over gameplay, wouldn't we want to remove whatever else that doesn't exist or really happen in real life?
> There's a little valve that controls fluid flow. When you shut off the valve, the heater doesn't heat anymore. Yes, the little bit of gas that's still left in the pipe does bump into the walls of the radiators and radiate. But since the valve is shut off, no more gas can flow in, and so when the gas already inside the pipe gives its heat to the radiator, it gets stuck there.

well yeah of course it wouldn't remove heat out of adjacent pipes, only this pipe

**Comment by juliangiebel** [comment]
Isn't the main reason the gas locks up in the first place that pumps just stop pumping after a certain pressure? That is also based on a static value and not on the pressure difference between the in and output.
See my comment in this Issue: https://github.com/space-wizards/space-station-14/issues/20549#issuecomment-1737571139

**Comment by Ilya246** [comment]
> Isn't the main reason the gas locks up in the first place that pumps just stop pumping after reaching a certain pressure? That is also based on a static value and not on the pressure difference between the in and output. See my comment in this Issue: [#20549 (comment)](https://github.com/space-wizards/space-station-14/issues/20549#issuecomment-1737571139)

pumps could also be reworked to slow down and not completely stop above their max pressures, could also additionally decrease their max pressures to compensate

**Comment by daerSeebaer** [comment]
My two cents on the discussion here: Go for binary machines that improve the higher the flow gets, but still work somewhat reasonably without flow.

Heat transfer happens with or without flow. It happens as long as there is a heat difference between the gas and whatever it is thermally connected to. Hot gas in a radiator in space cools down. Hot gas in a TEG will produce power. Hot water in European-style radiator heating will heat your room.

But over time this cools the gas down and the process slows. By having a constant flow, the process is stabilized by introducing more hot gasses to replace the old. The magic word here is energy flow - faster flowing gas means more thermal energy moving through the machine in the same time. If that Energy can be used in the time the gas needs to pass through is another parameter.

Refactoring the whole PipeNet system to have internal temperature differences would be a lot of work, but right now this means that we have instantaneous heat transfer through an uninterupted pipe. Without this simplification, we would not have this discussion since flow would be the only thing letting anything in Atmos happen.

But if we have a simplified PipeNet, and this discussion, lets just take the best of both worlds: Make it work when it's warm enough, make it work better when more warm gas is constantly flowing by. For me this feels intuitive and gives us mechanics that are easy to get into but still have a learning curve.

And whatever we do - we must document all of it into the Guidebook, because right now most people I meet ingame have no clue of how anything in Atmos actually works and just consider everything that doesn't immediately work as expected "broken".

**Comment by Partmedia** [comment]
> That is in my opinion exactly how a radiator would behave over time. Without any pumping involved, a radiator would cool down the entire pipe network through gas expansion and contractions from heating/cooling, creating an inner gas current, albeit slower than with active pumping. This could be easily simulated by an effect proportional to the network volume and the volume of radiators involved.

I'm not opposed to this. I welcome a PR that implements this, instead of one that rips out the current implementation.

> Regardless, I feel like making devices rely on flow is contrary to how pipes themselves function. As you say, there are only 2 devices that rely on flow in some manner: TEG and your implementation of radiators. Is there a design document for the atmospheric system?

We're moving towards more devices that operate based on flow. In fact, the only devices that are inconsistent are the freezer and heater. (All vents and scrubbers do in fact work on flow, the other end is a tile atmosphere instead of another pipe). All other devices, be it valves, mixers, filters, etc. have gases that flow through them.

> As it is, it is unintuitive and unrealistic as there are no mechanics to allow high pressure gas flow. Past 9000kpa, players do not have the ability to move gas as that is the limit of volume pumps. Despite it being reasonable to assume that gas would still flow even when highly pressurized.

No, gases always flow from high pressure to low pressure. If you have a burn that gets you past 9000 kPa, you can still make it passively flow through the TEG as long as you have no pumps in the way.

> right now ss14 gas physics pretends that all gas in a pipenet is "one gas", so making radiators unary would actually be more consistent with the current model, as gas does not have to move to do that

Just because there are pipe nodes doesn't mean that you *must* only have *one* pipe node. See radiators, TEG, valves, mixers, pumps, etc...

**Summary**
I welcome a PR that lets radiators radiate with zero flow, albeit at a much slower rate.

I disagree with making radiators unary.

I don't want to do any pipenet reworking. The pipenet implementation as-is lets you simulate flow as long as the devices that you chose to implement work that way (i.e. based on flow).

**Comment by Partmedia** [comment]
Based on the discussion I've opted to close this PR for now. Please re-open if you believe that further discussion is needed. I welcome an alternative PR that adds passive cooling at a lower rate to the existing binary radiators.

**Pull request closed without merging**
