### PR TITLE
Add reflection for crystals

### PR DESCRIPTION
**Pull request by metalgearsloth**
Also technically means something like a thrown esword if collided with could reflect stuff.

No video coz it's just reflection again.

:cl:
- add: Crystals can now deflect guns.

### CODE REVIEW

**Comment by AJCM-git** [comment]
shouldnt they just reflect hitscan?

**Comment by metalgearsloth** [comment]
> shouldnt they just reflect hitscan?

I am of the opinion projectile / hitscan shouldn't mean non-energy vs energy and a separate tag should be used. e.g. disablers shoot energy projectiles which means not all projectiles are non-energy, and vice versa where there's no requirement that hitscan needs to be "energy" (if we decide to ever make projectiles just hitscan in the future).

**Comment by AJCM-git** [comment]
> > shouldnt they just reflect hitscan?
> 
> I am of the opinion projectile / hitscan shouldn't mean non-energy vs energy and a separate tag should be used. e.g. disablers shoot energy projectiles which means not all projectiles are non-energy, and vice versa where there's no requirement that hitscan needs to be "energy" (if we decide to ever make projectiles just hitscan in the future).

thats fair but then this would require such a tag since anti-bullets crystals are kinda funny

**Comment by metalgearsloth** [comment]
> > > shouldnt they just reflect hitscan?
> > 
> > 
> > I am of the opinion projectile / hitscan shouldn't mean non-energy vs energy and a separate tag should be used. e.g. disablers shoot energy projectiles which means not all projectiles are non-energy, and vice versa where there's no requirement that hitscan needs to be "energy" (if we decide to ever make projectiles just hitscan in the future).
> 
> thats fair but then this would require such a tag since anti-bullets crystals are kinda funny

Alright I finally added reflect types so disabler + hitscans get reflected by crystals and everything by eswords.

**Review by AJCM-git — APPROVED** [review]
my 3am brain thinks this fine, merg if want

**Pull request merged**
