### PR TITLE
QM drip DLC

### PR DESCRIPTION
**Pull request by Hanzdegloker**
## About the PR

Adds new formal suit for the QM as well as a QM themed beret that both spawn in their dresser. I designed both
to look good with the mantle as A. the QM's mantle did not go with any existing jumpsuits or outfits and B. to add
variety to the outfits the QM can be seen in. The Beret is a good choice for the QM that doesn't want the same hat
as their employees but dyed another colour and the formal suit is the perfect choice for the QM that wants to look
equal to the other Dept. heads in the fashion department.

## Why / Balance

I noticed the QM was lacking any outfits that matched their mantle, so I created a new jumpsuit and a new hat.
The Quartermaster's formal suit and the QM's Beret respectively.

## Technical details

Added new formal jumpsuit for the QM and new beret for the QM which both now spawn in the QM's filled dresser.

## Media

refrence

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Due to multiple complaints from quartermasters about "variety" in headware, Nanotrasen will supply a new hat across all stations, the QM's beret!
- add: Due to, in no way shape or form a bribe from a wealthy quartermaster, Nanotrasen will now stock formal suits for all
those inclined to master the quarters.

### CODE REVIEW

**Comment by UbaserB** [comment]
the white feels a bit too bright imo

**Comment by Hanzdegloker** [comment]
> the white feels a bit too bright imo

Take a gander at the outfit when it is not in neon white light

refrence

**Comment by MACMAN2003** [comment]
did you add these to the uniform printer?

**Comment by GreyMario** [comment]
really just doesn't seem to mesh well with the Quartermaster's Mantle

**Comment by Hanzdegloker** [comment]
> did you add these to the uniform printer?

I knew I was forgetting something, I can fix that ASAP

**Comment by K-Dynamic** [comment]
QM really ought to be wearing some sort of formal business suit or a dark chef uniform

**Comment by Hanzdegloker** [comment]
At the end of the day, Quartermaster is a military rank, hence my styling of the formal uniform

**Comment by K-Dynamic** [comment]
> At the end of the day, Quartermaster is a military rank, hence my styling of the formal uniform

Fair enough, and there's a bit of a joke to the dark chef uniform suggestion - US Space Force uniforms look suspiciously like chef uniforms, and QMs will raid the kitchen for food bounties :trollface:

**Comment by Emisse** [comment]
pull master i think this will goncflict

**Comment by Jezithyr** [comment]
> pull master i think this will goncflict

Doesn't look like it. If you didn't have any issues with it, then it looks good to merge to me!

**Pull request merged**
