### PR TITLE
Buff chemical reaction output and Burn med changes

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About the PR
Most chems now produce more when you react them to make medicine, and other chemicals.

## Why / Balance
It was painful to play chemist, and in my opinion just not fun since now all your effort had to be put into the meta chems, and never had the chance to make things like Bruizine, Insuzine, Cryoxadine etc. Also Kelotane and Insuzine are now buffed since they were under-used, especially insuzine, Dermaline however is now harder to produce. Mixing beverages in un-touched.

## Technical details
Just value changes

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
 Chem changes, Yikes! Im not a chem expert, please feel free to add your opinion on the changes. Burn med changes are pretty major, since derma is harder to make in large quantities, but made up for with the ability to make a 

**Changelog**

:cl: Hmeister

- tweak: Chemicals have now been balanced around the Chem dispenser nerf. Also Kelotane and Insuzine are made in larger quantities, and Dermaline in lesser.

### CODE REVIEW

**Comment by Zap527** [comment]
Right, so there are multiple things here. 

First off, this PR essentially nukes all and any chem memory chemists have built up over time due to all of the number changes. This is going to be majorly annoying to need to adapt to a new system, especially to one which doesn't follow the same ratio formulas.

Second, a lot of the changes just seem random? I understand the ones concerning specific burn/brute meds, as that's within the scope of your PR, but you practically changed half the recipes in the game. They also don't seem to follow any logic - you changed table salt from its correct chemical formula (NaCl), for instance.

Finally, I simply don't think that chemicals are unbalanced in their current state. Insuzine isn't underused because it's weak, it's underused because shock damage is very uncommon. Kelotane isn't meant to be a strong chemical alternative to dermaline, it's meant to be its precessor, kind of like hyronalin is just weaker arithrazine.

**Comment by Hmeister-real** [comment]
> Right, so there are multiple things here.
> 
> First off, this PR essentially nukes all and any chem memory chemists have built up over time due to all of the number changes. This is going to be majorly annoying to need to adapt to a new system, especially to one which doesn't follow the same ratio formulas.
> 
> Second, a lot of the changes just seem random? I understand the ones concerning specific burn/brute meds, as that's within the scope of your PR, but you practically changed half the recipes in the game. They also don't seem to follow any logic - you changed table salt from its correct chemical formula (NaCl), for instance.
> 
> Finally, I simply don't think that chemicals are unbalanced in their current state. Insuzine isn't underused because it's weak, it's underused because shock damage is very uncommon. Kelotane isn't meant to be a strong chemical alternative to dermaline, it's meant to be its precessor, kind of like hyronalin is just weaker arithrazine.

1) Fair point
2) I just feel like the amount you get from making chems is a bit too litte and want chemists to focus a little less on purely medicine 
3) i just want Kelo and Insuz to be a good alternative to Derma, not with stats, but by how much is able to be made (e.g. its nukies and they get to the station before chem can make good meds, so then chem can make a ton of Kelo fast even if its not as effective as derma)

**Comment by thebadman4662** [comment]
>  Finally, I simply don't think that chemicals are unbalanced in their current state. Insuzine isn't underused because it's weak, it's underused because shock damage is very uncommon.

I would say its both unless Salvs/Atmos are doing their job for once and you are not bottlenecked by carbon. Benzene cost makes Ins less efficient than Derma and then you are running into trouble finding 40+ shock people for 5u+ injection.

**Comment by deltanedas** [comment]
rebalance recipes for carbon economy

**Comment by Hmeister-real** [comment]
I think theres a better way of changing chems than what I did, thanks for the feedback though

**Pull request closed without merging**
