### PR TITLE
Candy Bucket for Halloween

### PR DESCRIPTION
**Pull request by Bixkitts**
## About the PR
Added a candy bucket and code to make it update visually

## Why / Balance
Imagine not being able to trick or treat (sprite created and feature requested by @ps3moira).
Also, hold-able container sprites updating based on contents wasn't in the game before.

## Technical details
My friends and I couldn't find any container in the whole game that
updates it's appearance while it's being held, so I made a component and system for it.
This is a rudimentary solution that covers this use case and ones like it.
It works only with enum.ToggleVisuals for full/empty, but I'm open to generalizing and expanding it more
(assuming there isn't already a component that we just couldn't find).

## Media

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Added means to trick or treat

### CODE REVIEW

**Comment by Bixkitts** [comment]
Build failed?!
Everything was working yesterday,
One sec I'm on it

**Comment by Bixkitts** [comment]
Still builds and runs fine on two of my machines, and I see other code accessing storage.StorageUsed without issue.
Dunno what that's about.

**Comment by CatMagic1** [comment]
Gonna start handing out drugs mixed with sugar as chemist.

**Comment by Bixkitts** [comment]
> Gonna start handing out drugs mixed with sugar as chemist.

Better not lace my drugs with candy!

**Comment by RyanStrudfelt** [comment]
have you got this working?

**Comment by Bixkitts** [comment]
Yep!
(Also works when swapping hands, don't think it's shown in the footage)
https://youtu.be/aBCEIzUA4g8

**Comment by RyanStrudfelt** [comment]
Very neat, I hope this gets merged on time for halloween!

**Comment by CatMagic1** [comment]
Can't wait to try this out next halloween (pls merge)

**Comment by Emisse** [comment]
looks cute and just in time for halloween will merge if no issues today

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
move components to shared pls

**Comment by Bixkitts** [comment]
doing it

**Comment by CatMagic1** [comment]
> doing it

merge speedrun

**Comment by Bixkitts** [comment]
Builds and works on my machine!
Test server is being funny, 
or I can't access StorageUsed any more on master branch as of this week.

I got the same error in https://github.com/space-wizards/space-station-14/pull/21257/commits/1dfd5473a35b249a348f7be68c89b2ae860db984
and it was resolved by just... pushing again.

I guess I'll merge master into candy_bucket and see if anything's up.

**Comment by Bixkitts** [comment]
There is indeed no longer a StorageUsed, I must compensate.
One sec.

**Comment by Bixkitts** [comment]
- merged master into local branch
- got it to work with brand new storage system added this week
- reset everything and applied it as a single commit
Happy Halloween!

**Pull request merged**
