### PR TITLE
fix(contraband): Make contraband work with chameleon items

### PR DESCRIPTION
**Pull request by Brandon-Huu**
# Why
No metagaming chump.

[Screencast from 08-13-2024 08:46:32 PM.webm](https://github.com/user-attachments/assets/fa31e141-98e0-4cc2-b359-735b0ea183f7)

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
done

**Comment by TheDoctor1977** [comment]
Something seems to be horribly wrong with your video.
IMG_8077

**Comment by Brandon-Huu** [comment]
> Something seems to be horribly wrong with your video. IMG_8077

That's just you.
It works on my laptop and phone

**Comment by slarticodefast** [comment]
Thanks for the fix!

**Pull request merged**
