### PR TITLE
Syndicate Bomb Fix

### LINKED ISSUE #20368: Syndie bomb keeps putting people in walls
## Description

The syndicate bomb keeps putting people in walls.

Not sure if this can be fixed, although I am making this issue just in case.
**Reproduction**

1) Go to 1 square wide hallway.
2) Buy bomb.
3) Become one with steel.
**Screenshots**

N/A
**Additional context**

N/A

### PR DESCRIPTION
**Pull request by gusxyz**
## About the PR
Your able to walk over the syndicate bomb.
Fixes #20368

I don't know if it was intentional that it was a solid object you couldn't passthrough.
## Why / Balance
A fix to you getting thrown into a wall when spawning the syndicate bomb

**Changelog**
:cl:
- tweak: Syndicate bomb no longer has anomalous properties.

### CODE REVIEW

**Comment by UbaserB** [comment]
finally! this happened to me so many times and screwed over rounds before...

**Review by EmoGarbage404 — APPROVED** [review]
add `canCollide: false` on physics component to fix the text and you're all good.

**Comment by gusxyz** [comment]
should be ready for merge

**Comment by Just-a-Unity-Dev** [comment]
> I don't know if it was intentional that it was a solid object you couldn't passthrough.

...it is though?

**Pull request merged**
