### PR TITLE
Whitelisted Sec Webbing

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I added Secbelt whitelist to Sec webbing and made both able to Hold More Ammo Types

## Why / Balance

Due to not having a proper whitelist people would do cringy shit like using it to replace their saber sheath or stuff that feels gamey such as sticking a Shotgun in there.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Added SecBelt whitelist to Sec webbing
- tweak: Added more Ammo holders to SecBelt whitelist

### CODE REVIEW

**Comment by FungiFellow** [comment]
Also the idea of making certain topicals fit in here too but that might be a bit much

**Comment by K-Dynamic** [comment]
I would rather belts and webvests have no whitelist and instead size restrictions (aka only allow up to 2x2 items inside)

**Comment by FungiFellow** [comment]
> I would rather belts and webvests have no whitelist and instead size restrictions (aka only allow up to 2x2 items inside)

I don't support that and think it sounds like something for another PR

**Comment by LankLTE** [comment]
imho sec webbing should just be a belt reskin since they take up the same slot and all, and that's what it used to be before gridinv

**Comment by FungiFellow** [comment]
> imho sec webbing should just be a belt reskin since they take up the same slot and all, and that's what it used to be before gridinv

Honestly yeah, difference from sec belt should be cosmetic.

But I should add more ammo options to the belt

**Comment by FungiFellow** [comment]
I love errors in files I never touched :)

**Comment by LordEclipse** [comment]
> imho sec webbing should just be a belt reskin since they take up the same slot and all, and that's what it used to be before gridinv

Actually, Web vest always allowed ammo, where the belt did not.

**Comment by keronshb** [comment]
> I would rather belts and webbing have no whitelist and instead size restrictions (aka only allow up to 2x2 items inside)

It's fine for these to have whitelists.

**Comment by thebadman4662** [comment]
But webbing never accepted anything bigger than 2x2??? First time hearing of shotgun in there that is not SO.

**Comment by LordEclipse** [comment]
> But webbing never accepted anything bigger than 2x2??? First time hearing of shotgun in there that is not SO. Not being able to fit gauze in there would feel weird...

Is this the sawn-off shotgun?

**Comment by FungiFellow** [comment]
> > But webbing never accepted anything bigger than 2x2??? First time hearing of shotgun in there that is not SO. Not being able to fit gauze in there would feel weird...
> 
> Is this the sawn-off shotgun?

It didn't have a whitelist and the shotguns are all 1x5

**Comment by thebadman4662** [comment]
> I vaguely recall kammerers being 2x2 for some reason at start of storage rework before being made 1x5
> 
> Internally it might still be considered 'normal' sized as opposed to 'large'

I believe they got nerfed with introduction of satchel grid, that made them something else than backpack cosmetic.

**Comment by Golinth** [comment]
I very much disagree with this, and think we should go in the opposite direction, removing whitelists from belts completely. 

Having to maintain these whitelists is already a maintenance burden (for how long did truncheons not fit in sec belts), and there are many entries that just don’t make sense (why can a wrench fit in my medical belt, but not a crowbar. Why can’t I put ammo in my sec belt, etc) and every new item needs to be considered. I think it’s best to just remove the whitelist completely, and like others have said, restrict the size to 2x2 for all belts. This eliminates storing shotguns in webvests (which is very stupid and needs to be fixed, I didn’t even know it was possible), and allows for the choice of belt to be a cosmetic one.

**Comment by FungiFellow** [comment]
> I very much disagree with this, and think we should go in the opposite direction, removing whitelists from belts completely.

Whitelists should stay, I should be able to accurately guess what's in them at a glance.

**Comment by FungiFellow** [comment]
> Whitelists should stay but the system for whitelisting prolly needs refining. I believe this was spoken about last time someone wanted to remove whitelists from belts.

It's just that the lists need a bit of clean-up, I made a forum on the discord for it: https://discord.com/channels/310555209753690112/1233152798544105482

I plan to fix more whitelists based on this feedback.

**Comment by Carmell0** [comment]
I (Jack Cardinal) feel targeted by this lmao. RIP to the secrig meta you were amazing

**Pull request merged**
