### PR TITLE
tweak(scram): Halved the cost of scram implant

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Halved the cost of the scram implanter

## Why / Balance

99% of the time this will kill you or teleport you to the same room you are already in.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Scram implanter cost lowered from 6tc to 3tc.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
I think that you should rather make the scram implant better/more consistent instead of just lower the price in [what is admitted to be a mald PR](https://discord.com/channels/310555209753690112/310555209753690112/1251303634000674970).

If it's not fun to use (or it results in unfun consequences) then cutting the price in half is not gonna solve that.

**Comment by ninruB** [comment]
Maybe a minimum teleportation radius with a higher overall teleportation radius?

**Comment by EmoGarbage404** [comment]
i agree with slambam.

in the future, make sure to completely fill out the balance changes section. low-effort PRs that don't fully explain their reasoning may be closed.

**Comment by Brandon-Huu** [comment]
> If it's not fun to use (or it results in unfun consequences) then cutting the price in half is not gonna solve that.

I noticed a problem in the game and created a PR to fix it. It is not a Mald PR.
I got annoyed by the armory not having the right implanter crate in them so I tried making PRs to fix it, that is not malding either.

**Comment by Brandon-Huu** [comment]
Wou

> I think that you should rather make the scram implant better/more consistent instead of just lowering the price in [what is admitted to be a mald PR](https://discord.com/channels/310555209753690112/310555209753690112/1251303634000674970).
> 
> If it's not fun to use (or it results in unfun consequences) then cutting the price in half is not gonna solve that.

Would be great if you could come up with an alternative solution, I posted on in the discord but I got stuck when it came to finding the distance between two tiles.

**Comment by SlamBamActionman** [comment]
> Would be great if you could come up with an alternative solution, I posted on in the discord but I got stuck when it came to finding the distance between two tiles.

I don't have to come up with an alternate solution to point out flaws in the ones that get submitted. And if I _have to_ think up a solution on the spot it probably won't be a very good one because good solutions tend to take time.

But since you asked, here are some suggestions:
- Try teleporting the max distance first
- Check if the grids in range have atmos and prioritize those
- Prioritize grids you don't have line of sight to
- Make the scram direction be in a 120 degree cone towards the mouse cursor, as opposed to 360 around the user

**Pull request closed without merging**
