### PR TITLE
Adds the Mime 

### PR DESCRIPTION
**Pull request by SweptWasTaken**
What it says on the tin. 

(Will unmark as draft when I map in the spawn location to Saltern)

### CODE REVIEW

**Review by DrSmugleaf — APPROVED** [review]

**Review by Zumorica — APPROVED** [review]

**Comment by SweptWasTaken** [comment]
Revert last commit and this is ready to be merged.

**Comment by SweptWasTaken** [comment]
Idk understand you committed the stuff and then didn't merge it? lol

**Comment by DrSmugleaf** [comment]
> Idk understand you committed the stuff and then didn't merge it? lol

Trying to get latest master to even startup the client is taking priority for a moment

**Comment by SweptWasTaken** [comment]
Ah ok that's fair

**Pull request merged**
