### PR TITLE
Thief stuff: Gloves, Spy Crew Monitor, Invisible Crate, Toy

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Adding themed items to the game for the thief. The PR includes next items:
1) The thief figurine is available in the figurine spawner. 
2) Void Cloak. Dark Void themed cape. Changes the conversation icon to purple alien. Can be found in the tech tunnels or theater crate.
3) Chameleon thief gloves. combines the functionality of chameleon gloves and the ability to steal things discreetly. Not available to players yet.
4) Spy Crew Monitor. A weakened version of the paramedic monitor that requires twice as much power. Not available to players yet.
5) Invisible Crate. A modified version of the stealth box. You can't move inside in it, but you can hide it in the right place and climb into it to become invisible instantly. Or you can stealthily carry valuable items in plain sight. Not available to players yet.

## Why / Balance
Getting cool stealth things ready for the [thief](https://github.com/space-wizards/space-station-14/pull/21520) new antagonist.
These items will be available to the thief at the beginning of the game in some starter packs.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/99ef49de-c557-4ed7-a24d-588152a2fb4a

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: New Thief figurine! New void cloak!

### CODE REVIEW

**Comment by HoidC** [comment]
pretty sure thieving gloves already have chameleon

**Comment by TheShuEd** [comment]
No, standard thief's gloves don't have a chameleon.

**Comment by TheShuEd** [comment]
The thief will have the option to choose 2 sets from the set when he appears. This key will be the value of one of those sets, and having it in the thief player's possession will mean that he didn't get something else useful, like a set of chameleon clothes. 

I think this is a good and powerful item that will help the thief fulfill his goals stealthily.

**Comment by TheShuEd** [comment]
In case of a clear imbalance, I can remove some communication channels from it. Or make several kinds of keys for different secret frequencies.

**Comment by EmoGarbage404** [comment]
"secret channels" have been discussed several times in the past and the overall consensus has been to deny them. If you wish to have a thematic all-radio-channel key, I think that's fine, but having hidden channels is really just a new player trap that's pretty easily confirmed by any experienced player.

**Pull request merged**
