### PR TITLE
The Shelfs Update

### PR DESCRIPTION
**Pull request by SphiraI**
## About the PR
Adds an array of new unique and functional shelfs to help with all your storing needs! Along with a couple extra types specifically specialized in holding specific kinds of items.

*Thank you to Kezu for sprites once again*

## Why / Balance
We already have Lockers, Crates, *Wall* Lockers, etc etc, yet the only structure with an internal inventory is a dresser found in dorms or Command Rooms. With the addition of these shelfs, not only can some of the extra wall space be used, but it can actually have a use and help provide some sense of organization to the chaos that can become storage.

## Technical details
- New prototype path in `Structures/Storage`, along with said proto's being added to the crafting graphs systems under the same name.
- A couple tags (`Ingredients`, `DrinkGlass`) added to chef-specific ingredient items and a couple cups mainly found around the bar respectively
- Lots of sprites for each locker organized with future adding in mind. (The three departmental ones having fill level functions)

## Media
**sprites have been updated as of 07/3/2024*
image
image
image
image
image

__*All sprites made by Kezu*__
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl: Sphiral&Kezu
- add: Added a variety of new wall based storages: Shelfs! Build some today!

### CODE REVIEW

**Comment by SphiraI** [comment]
Ack, completely forgot to test construction. Wanted to get PR'd before freeze.
!hour!

**Comment by BolloTea** [comment]
Very cute!

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
Art Director opinion here:

The 3/4s perspective on these clashes really heavily with other wallmounts so i think it'd probably be best to make them clearly recessed into the wall or w/e, like how defib cabinets and such look. I also don't really love how the bookshelf sprite looks so basing it off of that looks kinda weird for the base (the doors look clean af tho)

The free floating glass shelf is really weird and i don't really see many situations where it's going to fit in and look good. It'd be better if it wasn't physically on the wall itself.

I guess that's a general comment for a lot of these? They are sprited for perspective or tallwalls or w/e and it looks super weird with the top-down wall style. They should almost just be poking out of the side, like light tubes.

final misc thoughts: the cabinets with lights at the top look super weird and i think having it on the handle is a lot better. The shelf with the secondary wood one below looks super weird and perspectiveless and i think it might be best to just ditch it.

**Comment by SphiraI** [comment]
> final misc thoughts: the cabinets with lights at the top look super weird and i think having it on the handle is a lot better. The shelf with the secondary wood one below looks super weird and perspectiveless and i think it might be best to just ditch it.
- Originally the lights were on the handles, but it looked weird due to being a single pixel and just was kinda iffy-lookin in-game, so they were moved. As for the "kitchen" variation, I see what you mean. But do you mean just the wooden part? Or the entire thing altogether?

> all the other stuff
- I'll talk to Kezu and see what can be done without just redoin them, lol.

Thank you for the feedback though!

**Comment by potato1234x** [comment]
sprites make my neurons activate 👍

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by SphiraI** [comment]
> Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

Finally got to finishing this up with the updated sprites Kezu gave me, so time for legally obligated ping.

~Also not sure if the newest push not appearing is because it's closed, but I'll fix it when it gets reopened~

**Comment by Emisse** [comment]
looks good technically needs art director pass though so ill put it in for review with art directors in discord

**Review by Emisse — APPROVED** [review]

**Pull request merged**
