### PR TITLE
robust harvest 1984

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
ods at 30u for 6 damage/s so you cant just permanently have 300u of robust in you to be invincible

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Implemented a new robust harvest overdose threshold for Diona, preventing them from achieving immortality.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
diona nerfs before diona buffs
huh.

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by deltanedas** [comment]
not a diona nerf just a nerf to diona invincibility supersolider bullshit

**Comment by VasilisThePikachu** [comment]
fell im unsure how foam works but does it really manage to give you 800u of robust as a foam? if thats the case foam should get nerfed as well

**Comment by Aisu9** [comment]
> well im unsure how foam works but does it really manage to give you 800u of robust as a foam? if thats the case foam should get nerfed as well

foam inject the maximum amount of chemical a body can hold, yup touching foam for 0.1 second will do that

**Comment by VasilisThePikachu** [comment]
> > well im unsure how foam works but does it really manage to give you 800u of robust as a foam? if thats the case foam should get nerfed as well
> 
> foam inject the maximum amount of chemical a body can hold, yup touching foam for 0.1 second will do that

so what you are saying for example: foam bicar will max out at 15u when in contact with foam
BUT anything that does not have an overdose limit will give you 800u+?
Thats a lot of chems that can be abused like this, max for foam should be like 30u

**Comment by Aisu9** [comment]
> > > well im unsure how foam works but does it really manage to give you 800u of robust as a foam? if thats the case foam should get nerfed as well
> > 
> > 
> > foam inject the maximum amount of chemical a body can hold, yup touching foam for 0.1 second will do that
> 
> so what you are saying for example: foam bicar will max out at 15u when in contact with foam BUT anything that does not have an overdose limit will give you 800u+? Thats a lot of chems that can be abused like this, max for foam should be like 30u

no what i'm saying is everything will be set at 800+u inside any living body that make 0.1s contact with foam, but it chems with overdose value of not

**Comment by Interrobang01** [comment]
The CL should specify the PR is nerfing diona's usage of robust harvest and not botany's usage of robust harvest so the botanists don't riot

(ex: tweak: Implemented a new robust harvest overdose threshold for Diona, preventing them from achieving immortality.)

**Comment by deltanedas** [comment]
cl shamelessly stolen

**Pull request merged**
