### PR TITLE
Animal Husbandry

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## Animal Husbandry

wow what a funny title i sure wonder what that's about.

Adds some simple mechanics for minecraft-style animal husbandry.
When a pair of compatible animals are next to each other, there's a random chance that one can, after a short period, bear offspring. The animals need to be fed and not be thirsty (as well as not be player-controlled, infants, or dead)

This basically just amounts to some small mechanics for making animals renewable. I found it really dumb that all animals had to be acquired through cargo.

Animals after being born will be "infants" for several minutes, in which time they will have reduced size and be unable to breed.

Some animals, like chickens and ducks, lay eggs which hatch after a short period, rather than giving live birth.

**Media**

image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Certain livestock (cows, goats, pigs, chickens, ducks) now have the ability to produce offspring so long as they are properly tended to.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
Remember when I said I wanted Ian and Lisa to be able to make a baby Ian and you called me a weirdo? Good times

**Comment by Equivocateur** [comment]
> as well as not be player-controlled

Tactical `/ghost` out of a mob to do it and rejoin through ghost role

Emo what the fuck have you done

**Comment by EmoGarbage404** [comment]
> Tactical `/ghost` out of a mob to do it and rejoin through ghost role
> 
> Emo what the fuck have you done

image
i'm not degenerate

**Comment by Equivocateur** [comment]
> > Tactical `/ghost` out of a mob to do it and rejoin through ghost role
> > Emo what the fuck have you done
> 
> image i'm not degenerate

~~Miscarriage rp real~~
Still can join after the fact of that

**Comment by EmoGarbage404** [comment]
i'm not even sure that doing those steps is even remotely possible but since you're so determined i'll fix it, i guess.

**Comment by juliangiebel** [comment]
Now you just let people grief by taking every animal as a ghost role and making them all sterile. Great

**Comment by Aisu9** [comment]
> 

this is why cognizine must be used sparingly, don't want to make the entire herd sterile don't you (sterility should be applied when the animal become ghost role available/controlled by a player to prevent any awkward situation)

**Comment by Emisse** [comment]
i tested this last night but forgot to merge

**Comment by Aisu9** [comment]
do every animal actively seek food or are is the bug still in?

**Pull request merged**
