### PR TITLE
Add map Oasis

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Adds the map Oasis, which aims to feature a large park in the center of the station with some more open spaces than other maps-- among other novelties including HoP court, off-station perma, and a zoo!

It has a couple growing pains I am aware of, but which I dont think are game breaking enough to hold off until they're fixed. These include it being a good idea for there to be atmos devices that you can map as powered on, as well as some funky stuff with how shuttles interact with containment fields.

## Why / Balance

Fun.

## Media

V6:
Oasis
Oasis Perma
Oasis Briggle

V5:
https://github.com/space-wizards/space-station-14/assets/107586145/8286f75b-5481-4a56-9f6d-6eb23c8e7ed6
https://github.com/space-wizards/space-station-14/assets/107586145/5400501e-fe12-4d57-bb9b-44fb326018d5
https://github.com/space-wizards/space-station-14/assets/107586145/daae3cea-e97c-4fd0-b6f4-8581ec6b84bd

V4:
https://github.com/space-wizards/space-station-14/assets/107586145/9d7441d3-1002-4222-98b3-f4504e8608b5
https://github.com/space-wizards/space-station-14/assets/107586145/7da476aa-98d7-407e-8e27-b172e8191df2
https://github.com/space-wizards/space-station-14/assets/107586145/fdb016b9-6cf5-40d7-a5a6-a13af94531f4

V3:
https://github.com/space-wizards/space-station-14/assets/107586145/b3020ffe-5460-43c5-9c5e-e4403fd297e6
https://github.com/space-wizards/space-station-14/assets/107586145/10a3df23-80b8-4f88-aca8-addde35a6d72
https://github.com/space-wizards/space-station-14/assets/107586145/bb106fb0-2ca9-4391-8aa9-8fe5bd0075bd

V2:
https://github.com/space-wizards/space-station-14/assets/107586145/3e62ba25-74a6-42a3-880c-e4445de651d0
https://github.com/space-wizards/space-station-14/assets/107586145/789005cb-32ed-4ea8-8c25-7c13ae06d4dc
https://github.com/space-wizards/space-station-14/assets/107586145/bada0964-faae-4ce9-85cb-c3e956ba54e4

V1:
https://github.com/space-wizards/space-station-14/assets/107586145/e7c766ba-50f9-4e80-bd7d-74b7a127c593
https://github.com/space-wizards/space-station-14/assets/107586145/839db490-ac9d-4fc5-b3fb-a1b7152b28d0
https://github.com/space-wizards/space-station-14/assets/107586145/f053a8c8-fce3-413c-8a73-57c5741bb5fc

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None.

**Changelog**

:cl:
- add: New map Oasis.

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
birig shuttle render looks scuffed. It works. Trust.

**Comment by Cojoke-dot** [comment]
That is a cool map, I love the central portion, the courthouse, and sci. I think the vault in cargo is a terrible idea and I am not sure how the separate perma station would go with the current feel of the game. Normal ships would have to be able to warp to perma to give other people a way to break into and save someone from it. TVs in the prison cells are great, helps the reporter get more of an audience. Overall I like the station but it would be a pain to defend against nukies with all the open spaces and the nuke being so accessible.

**Comment by IProduceWidgets** [comment]
>Normal ships would have to be able to warp to perma to give other people a way to break into and save someone from it. 
Its all on the same map, so you can just drive on over! Theres also some easy shuttle making stuff near engineering.

>Overall I like the station but it would be a pain to defend against nukies with all the open spaces and the nuke being so accessible.
I did want to try to incentivize not immediately going for the armory. I think this achieves that, but the only way I know how to see if its the right amount of encouragement or not is to see how the meta evolves for the map. Playtests mean no one has a good plan for that sorta thing.

**Comment by K-Dynamic** [comment]
I like, but why is there a giant raisin room in engineering

Just replace it with engineering storage room - move the mats from grav to that room in case it's command-only

**Comment by deltanedas** [comment]
i love the brig shuttle force field but it will take like 5 minutes to shut down, unless you overrode that in the map's cfg entities

**Comment by Hmeister-real** [comment]
I really really like this map, very creative with the centre. I think the armory in Cargo is odd, but i think it's fine. Also you should put some more diverse stuff in the minable rock in perma, like maybe a retro laser or a sword so that prison breaks are funner.

**Comment by TheShuEd** [comment]
> i love the brig shuttle force field but it will take like 5 minutes to shut down, unless you overrode that in the map's cfg entities

When itested it, the shuttles flew quietly through the force field.

**Comment by IProduceWidgets** [comment]
> > i love the brig shuttle force field but it will take like 5 minutes to shut down, unless you overrode that in the map's cfg entities
> 
> When itested it, the shuttles flew quietly through the force field.

Yeah, at the moment the containment fields don't interact with grids. We may settle on a different solution in the future, but I think at least the idea of a closable bay is pretty neat, and this does at least stop entities from entering it unless they are buckled in a shuttle for the time being. 

It is a bit of a deep-spacing risk if turned on (they're currently such that its a bit of extra work to use them), but that might also just be something else to ponder about the fields when we get around to addressing the 'they don't interact with grids' issue.

**Comment by IProduceWidgets** [comment]
> I really really like this map, very creative with the centre. I think the armory in Cargo is odd, but i think it's fine. Also you should put some more diverse stuff in the minable rock in perma, like maybe a retro laser or a sword so that prison breaks are funner.

All the crates and lockers are hand-filled (with nothing too crazy). I don;t recall exactly whats in which off hand, but there's at least one way off the rock I can assure you.

**Comment by TaoNewt** [comment]
I dont know if this is an oversight, but engineers can get aa in under 60 seconds since the ame-room connects to the the board-room with the cap id by a single tile thick wall.

**Comment by IProduceWidgets** [comment]
I have a few more things I want to take a pass at, but, Its late and am sleep.

**Comment by Brandon-Huu** [comment]
Wasn't this already merged? I remember playing on this map a few days ago

**Comment by IProduceWidgets** [comment]
> Wasn't this already merged? I remember playing on this map a few days ago

Nah, just a playtest so I could find extra hiccups.

**Comment by Brandon-Huu** [comment]
does salvage have an expedition console?

**Comment by IProduceWidgets** [comment]
> does salvage have an expedition console?

Yes! I just haven't updated the images in a couple weeks.

**Comment by IProduceWidgets** [comment]
Test fail is pizza bounty arbitrage bein' cooked.

**Comment by superjj18** [comment]
I love this map, I especially love round ending chefs who think the center area's parrots and lizards are free meat :trollface: 

But for real, chaplain is so chill on this map, you get a bustling nature sanctuary right outside the chapel!

**Comment by Everturning** [comment]
needs #26365

**Comment by vorkathbruh** [comment]
having played the map a fair bit, i think it's a pretty nice high-pop which this game really needs. i would say that the departments feel a little TOO open, particularly sec and sci, there's no proper partition for anomalies and you need to set up shielding for the experimental vessels awkwardly, and the brig is a little large. medical is good, but the cryo doesn't really work without a freezer, and it feels like there are too few beds.

**Comment by IProduceWidgets** [comment]
> medical is good, but the cryo doesn't really work without a freezer, and it feels like there are too few beds.

I did add a freezer before merge, it just snuck in with some other minor changes I didnt think warranted a reimaging quite yet. 

I'm happy to report I spent my first shift post-merge operating the cryo-bay and it works as expected!

**Pull request merged**
