### PR TITLE
saltern map fixes (curadrobe and evac fire closet)

### PR DESCRIPTION
**Pull request by Kukutis96513**
## About the PR

Added a curadrobe to the librarians room and fixed a fire closet near evac.

## Media

before fix
Screenshot_418
after fix
Screenshot_420
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

hopefully none

### CODE REVIEW

**Comment by deltanedas** [comment]
gamer diff

**Comment by Emisse** [comment]
why is the diff so high

**Comment by Kukutis96513** [comment]
> why is the diff so high

no clue honestly, i just saved the map and then replaced the old file with the one i saved

**Comment by deltanedas** [comment]
ill incorporate these changes tomorrow

**Pull request closed without merging**
