### PR TITLE
add an arabian lamp.

### LINKED ISSUE #29800: Mapped MagicLamp in snowy_labs causing spacelaw and admin issues.
## Description
This has caused IC spacelaw issues and Admin ruling issues as to how this is even regarded.
Wizard federation is not real ™️, this shouldn't be mapped until they are. 

**Reproduction**

https://github.com/space-wizards/space-station-14/blob/eab93cb09ed52b2de4d9523b5ca67fc6954b2716/Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/guardian_activators.yml#L24
https://github.com/space-wizards/space-station-14/blob/eab93cb09ed52b2de4d9523b5ca67fc6954b2716/Resources/Maps/Dungeon/snowy_labs.yml#L10734

**Screenshots**
its in the map yml ™️ 

**Additional context**

Current issues are:
1. Metashield only references Syndicate, making Wizard Federation either explicitly not shielded or just not real at all. 
2. Spacelaw only references uplink items and contraband, a "genie" in a "bottle" is hard to lock down due to being part of a half implimented gamemode (Wizard) 

Both these issues will disappear into thin air upon Wizard Federation becoming real ™️

### PR DESCRIPTION
**Pull request by IProduceWidgets**
fixes #29800 

## About the PR

image

## Why / Balance

Its just a funny lamp. Maybe one day it will be for a genie. Its got a CC locked entity storage for admins to put a funny boon in and unlock at their whim. It also refills with fuel because its a magic lamp, but slower than it uses the fuel, so its not too magic.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: an arabian lamp!

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
[me the whole time making this:](https://www.youtube.com/watch?v=T9GmO_WFhjQ)

**Comment by FairlySadPanda** [comment]
Feature request!

Add a "rub" verb which opens the pray menu (the same one that comes up when you use the red phone etc)

**Comment by IProduceWidgets** [comment]
> Feature request!
> 
> Add a "rub" verb which opens the pray menu (the same one that comes up when you use the red phone etc)

Sure, that's easy enough.

**Comment by IProduceWidgets** [comment]
It just occurred to me you can probably emag the entity storage.

I'll add a toggle for that but probably in another PR since it will add c# and also its something I've wanted on other occasions for other things too.

**Comment by IProduceWidgets** [comment]
fixed it!

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by IProduceWidgets** [comment]
_I wish for the PR to be open._

**Comment by lzk228** [comment]
also would be cool to add 1x1 storage

**Comment by IProduceWidgets** [comment]
> also would be cool to add 1x1 storage

It has an entity storage (so a creature or something can be in it), I can add an item slot to it, but It feel a touch like its becoming the EveryItem

**Comment by TurboTrackerss14** [comment]
wtf I love this pr now

**Pull request merged**
