### PR TITLE
Half Revert #31978

### PR DESCRIPTION
**Pull request by cohanna**
## About the PR
~~The ability to upgrade reinforced windows to shuttle windows has been removed.~~

~~**You can still construct shuttle windows from scratch**~~
Partially reverts #31978 

## Why / Balance
~~This specific upgrade is largely used to upgrade the windows to brig and command offices which is very powergamey and
not very cool. Itd be one thing if these were meant to be destroyed but its 500 hp is comparable to a reinforced wall which makes it unreasonable for a 2 plasteel upgrade with no tools required.~~
Revert was requested by @keronshb in comments below

## Technical details
~~removed the upgrade edge on the reinforced window graph~~
Partially reverts #31978 

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: clinux
- remove: Normal and reinforced windows can no longer be directly upgraded using rods, plasma, uranium, or plasteel.

### CODE REVIEW

**Comment by thebadman4662** [comment]
Would it not be better to change cost instead rather than remove the feature?

**Comment by cohanna** [comment]
> Would it not be better to change cost instead rather than remove the feature?

I was leaning towards adjusting their health as an alternate over the cost (b/c frankly them having anything over 100hp is silly). I'm more than willing to massively nerf the shuttle walls and windows (as well as increase the cost for construction & upgrading) if that's what the general consensus yields. But since these structural parts are really only used for evac and from what I remember the main reason they have such large heath is to prevent EORG/shuttlebombing (not that it really helps, evac gets spaced and has holes blown in it consistently)
it both doesn't make sense for them to be so easily utilized and nerfs would get more maintainer pushback than removal, I opted to remove them instead.

**Comment by cohanna** [comment]
In terms of nerfs to the shuttle wall and windows I was thinking this:
Windows-
Hp decreased from 500->100
Construction cost increased from 2 plasteel -> 4

Walls-
Hp decreased from 600->400 (for total destruction, 200 to destroy into girder) (this gives it 100 and 50 more hp than a plasma wall respectively)
Construction cost increased from 4 total plasteel -> 5

What do you guys think?

**Comment by IamVelcroboy** [comment]
Shuttle structures are intentionally robust. I wouldn't make them weaker. Increase the cost and add to the complexity(extra steps) if you want to decrease the scenarios you mention.

**Comment by cohanna** [comment]
> Shuttle structures are intentionally robust. I wouldn't make them weaker. Increase the cost and add to the complexity(extra steps) if you want to decrease the scenarios you mention. 

I fully get why they are so beefy, but an upgrade to a 500hp window with anything that can be ordered from cargo for a reasonable price & quantity is insane at best. You should not be able to upgrade the brig windows to be almost the same hp as a reinforced wall with roundstart materials. 

What kind of steps do you even have in mind? The entire point of the window upgrade system is so that you can quickly upgrade windows. If you make the upgrade process complex then what's the difference between it and just deconstructing the existing window and constructing a shuttle one? The "extra steps" would be to deconstruct the existing window in this case, aka removing the upgrade path (which this PR does).

**Comment by IamVelcroboy** [comment]
I would say it's fairly reasonable to remove from the upgrade graph as long as they can still be built from scratch. But if it's preferable to leave it in, then look at the time it takes to build from scratch and add a welding step to make up the difference

**Comment by cohanna** [comment]
> But if it's preferable to leave it in, then look at the time it takes to build from scratch and add a welding step to make up the difference 

I can agree to that, up to the maintainers tho imo.

**Comment by keronshb** [comment]
Regarding window upgrades -
I'm in agreement that it should actually be really difficult for command/sec to upgrade windows. This is the 1# reason they weren't included in the RCD and that bypasses that step explicitly. Otherwise you do get command/sec upgrading windows with near indestructible windows every round and that's something we do not want to have gameplay wise.

**Comment by cohanna** [comment]
> Otherwise you do get command/sec upgrading windows with near indestructible windows every round and that's something we do not want to have gameplay wise.

This is what prompted the PR lol
Over the past month on lizard windows have increasingly been upgraded to shuttle windows in the bridge/brig/hop office and I had like 4 rounds in a row where the brig was reinforced with this. I'm sure this isn't as much as an issue on mrp servers but it's gotten very annoying on lrp.

**Comment by cohanna** [comment]
> If you swap this PR to a full revert it'd get my approval. This definitely needed a maintainer review before it was merged.

Ehhh... Im rather fond of the other window upgrades and really only think the issue lies with the shuttle windows.

**Comment by keronshb** [comment]
> > If you swap this PR to a full revert it'd get my approval. This definitely needed a maintainer review before it was merged.
> 
> Ehhh... Im rather fond of the other window upgrades and really only think the issue lies with the shuttle windows.

The main issue is that the original PR accidentally bypassed any official maintainer discussion.
As it is right now, it's also skipping the fact that we excluded this from RCDs for a reason - due to it being really powerful. Which is why we required the actual construction steps for these kind of windows. It's also why things like R-Walls and other specialty type walls aren't in the RCD/upgradable.

**Comment by HelpTheSteak** [comment]
I just think they look ugly when next to normal or reinforced walls so I'm on board :godo:

**Comment by cohanna** [comment]
> The main issue is that the original PR accidentally bypassed any official maintainer discussion.
> 
> As it is right now, it's also skipping the fact that we excluded this from RCDs for a reason - due to it being really powerful. Which is why we required the actual construction steps for these kind of windows. It's also why things like R-Walls and other specialty type walls aren't in the RCD/upgradable.

I can change this to a revert tomorrow if you really want but since we are on that biweekly release schedule would it not make more sense to have that maintainer discussion now and request changes to this PR? (Instead of reverting, opening a new PR re-adding the old stuff, maintainer discussion there) I'm down to make any requested changes since it's just yaml.

**Comment by keronshb** [comment]
> > The main issue is that the original PR accidentally bypassed any official maintainer discussion.
> > As it is right now, it's also skipping the fact that we excluded this from RCDs for a reason - due to it being really powerful. Which is why we required the actual construction steps for these kind of windows. It's also why things like R-Walls and other specialty type walls aren't in the RCD/upgradable.
> 
> I can change this to a revert tomorrow if you really want but since we are on that biweekly release schedule would it not make more sense to have that maintainer discussion now and request changes to this PR? (Instead of reverting, opening a new PR re-adding the old stuff, maintainer discussion there) I'm down to make any requested changes since it's just yaml.

We already had a lengthy talk about this, was going to make a post later tonight, but if you could swap this to a revert that'd make things easier.

The biggest two reasons for a revert:

1) It doesn't fit the game. 
- Only thing that really prevents people from spamming windows is materials. This is one of the reasons these window types weren't added to the RCD. To build these stronger windows, one of the biggest balance for them is the time & steps it would take to replace. 
- It removes the need for tools (welding, screwdriver, etc) to repair/remove/replace.
- It makes space-facing windows a non-issue to deal with. To replace a space facing window you should bring space protection and holofans with you, and air refill as needed.

2) It skipped the previous maintainer process unintentionally, so there was no discussion behind merging it back then.

**Comment by cohanna** [comment]
Note: these to fixes-
fix: Windows have been made to correctly display their damage visuals.
fix: Reinforced plasma windows have been given the correct amount of hp and no longer have 12x the amount they should.
Have been reverted as well.

**Comment by keronshb** [comment]
Could you keep the fix for damage visuals? Reinforced Plasma glass can stay reverted, would need to talk to the other devs about that.

Feel like the fix for the damaged visuals is fine, just not the upgrades.

**Review by keronshb — CHANGES_REQUESTED** [review]
> Could you keep the fix for damage visuals? Reinforced Plasma glass can stay reverted, would need to talk to the other devs about that.
> 
> Feel like the fix for the damaged visuals & plasma is fine, just not the upgrades.

@cohanna tagging and requesting changes for visibility

**Comment by cohanna** [comment]
> @cohanna tagging and requesting changes for visibility

Seen, will implement changes as soon as I get the time to

**Review by keronshb — APPROVED** [review]

**Comment by keronshb** [comment]
Tests went over fine. This is good to go.

**Pull request merged**
