### PR TITLE
[Clothing] Moth cloak and mask

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

Adds a cloak and a moth mask, the mask is put on using the icon in the hotbar if there is a moth cloak on the shoulders, or as a separate entity of the mask. The moth mask hides the identity, in the absence of an ID card in the slot.

**Media**
227636758-24529272-a1b1-43d0-a248-de25a28daf9a
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added Moth Cloak.
- add: Added Moth Mask.
- remove: Removed sadness!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
The mask clearly doesn't fit on the head.

**Comment by PuroSlavKing** [comment]
> The mask clearly doesn't fit on the head.

I understand, but otherwise it will be too fat to look at. If you do not zoom the game to 0.3, this problem is not critical, especially with hair.

**Comment by EmoGarbage404** [comment]
It's not my place to decide, but i personally think that, considering the sprite clearly wraps around the entire head, the side states should not have any of the head itself visible.

It should also hide hair, if it doesn't already.

**Comment by Emisse** [comment]
youre gonna want to add this to the head piece
  - type: Tag
    tags:
    - HidesHair
and also make the head piece visually cover the head entirely, the problem will be very noticeable on other races with colorful skin

**Comment by Flareguy** [comment]
Being a mask, it seems kind of weird the back of the head is visible.

**Comment by PuroSlavKing** [comment]
I have absolutely no idea how to hide it. We have several options.
1) A mask with a nose sticking out of it.
2) A mask with a head sticking out of it.
3) We cover the head with fur, and we get a mask similar to Jabba the Hutt, from Star Wars.
As for me, option 2 is the best, if someone succeeds in stylishly closing the neck, then write.

**Comment by Emisse** [comment]
just extend the back of it a bit

**Comment by PuroSlavKing** [comment]
Everything's great now.

**Comment by Emisse** [comment]
could you add this to the maint fluff loot pool in entities/markers/spawners/random/maintenance.yml so it has an in game obtainable source

**Comment by potato1234x** [comment]
maybe one in the autodrobe?

**Comment by PuroSlavKing** [comment]
> 



> maybe one in the autodrobe?

considering what I wrote about it being suitable for cosplay, it would be right to place it there... but I like the idea more that it can only be found, like the cloak of the admin, Goliath and others. If the PR is approved, the community will decide for itself whether they want to see it in autodrobe or not.

**Comment by Emisse** [comment]
lg2m

**Pull request merged**
