### PR TITLE
Spinal spike marking for Reptilians

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR

hehe lizard backspike go prod
## Why / Balance

more character expression
## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
add: Added backspikes marking to Lizards

### CODE REVIEW

**Comment by Flareguy** [comment]
Needs ingame screenshots.

**Comment by KittenColony** [comment]
done

**Comment by UbaserB** [comment]
oooo

**Comment by lzk228** [comment]
how it looks with clothing?

**Comment by KittenColony** [comment]
i dunno why this has an error

As it stands it clips through uniforms and is being put in place for when I make shirtless uniforms

**Comment by UbaserB** [comment]
> i dunno why this has an error
> 
> As it stands it clips through uniforms and is being put in place for when I make shirtless uniforms

lizards tails clip over pants so it'd be nice to imagine the lizard uniform just having holes in it (specially made for them) or something ^^

**Comment by KittenColony** [comment]
God I fucking hate this fickle piece of shit

**Pull request merged**
