### PR TITLE
saltern bounty

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- added bounty computer to cargo
- added a few decals to the cargo dock
- extended arrivals a bit so it hopefully always docks there

### CODE REVIEW

**Comment by DogZeroX** [comment]
By the way, did you mapped multiple bibles in the church?

**Comment by deltanedas** [comment]
ye

**Comment by DogZeroX** [comment]
Please remove them, I was greeted with about 6 remilia ghost roles because of it, bibles shouldn't be mapped really. ~~preferably just remove remilia tbh~~

**Comment by deltanedas** [comment]
funny bible study room

**Comment by Emisse** [comment]
remove them next update

**Comment by deltanedas** [comment]
you the one that asked for it goober

**Pull request merged**
