### PR TITLE
new chemical-Necrosol

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

This PR proposes the addition of necrosol, a new substance capable of curing frozen corpses

It's made from сryoxadone, blood and omnizine at temperatures above 370K.
## Why / Balance

Not too long ago, cryoxadone and doxarubixadone were added with the ability to heal the dead, which led to a huge balance error and a rollback of the changes. I propose to add a **weakened**, expensive and not available everywhere version of cryoxadone - necrosol. I took the properties of cryoxadone, removed the airloos cure, and changed the rest of the parameters a bit to keep the need for other ways to heal corpses alive

Necrosol requires omnizine to create, which involves something called **social interaction**. I think people should be able to animate the expensive crew of the station, and necrosol is well suited for that.

People can still be permanently taken out of the game by simple N̶o̶r̶t̶h̶ ̶S̶t̶a̶r̶ ̶g̶l̶o̶v̶e̶s acid damage
If we think treating poisons on corpses is wrong, I don't mind removing them.
# Technical details

This might be a bit wrong to work for plants, I don't really understand their metabolic system.....

I wanted to make this thing work **only** on corpses, but that's problematic with my poor C# skills.
## Media

изображение

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: A new reagent, necrosol, has been added. It can heal frozen corpses

### CODE REVIEW

**Comment by lzk228** [comment]
Replace "He" on "It" in cl

**Comment by Rainbeon** [comment]
Pretty sure it healing Toxin damage is a big no-no and half the reason it originally got axed.

**Comment by thebadman4662** [comment]
Original only needed dexalin pills or single sheet of plasma. This one requires omnizine.

**Comment by Rainbeon** [comment]
> Original only needed dexalin pills or single sheet of plasma. This one requires omnizine.

"Basically re-adding cloning" is still "Basically re-adding cloning" even if it requires Omnizine

**Comment by JoeTheJanitor** [comment]
> "Basically re-adding cloning" is still "Basically re-adding cloning" even if it requires Omnizine
This is not comparable to cloning at all. For one, this doesn’t even reverse decomposition, it seems that it will still need the corpse to be fresh to work. All it seems this does is heal damage faster as a reward for the crew working together to make it, instead of having to use the current method which is to have like 3 doctors apply a couple hundred ointment to heal the passenger who managed to set themself on fire and get 1000 burn damage.

**Comment by Emisse** [comment]
omnizine is very rare so sure

**Comment by K-Dynamic** [comment]
> omnizine is very rare so sure

For now, will probably be worth rechecking if/when botany gets plant scanners and stuff

**Comment by deltanedas** [comment]
it takes 20m to start mass producing buckets of omni pro

**Pull request merged**
