### PR TITLE
fix(Reinforcement Teleporter): Use the correct icon for syndicate kobolds

### LINKED ISSUE #30608: Kobold Reinforcements wrong UI icon
## Description
On the Genetic Ancestor REinforcement Beacon's UI, Kobold Reinforcements don't have their own icon, they use the traitor monkey sprite. Probably same for the nukie version

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Gave kobolds a custom icon in the reinforcement teleporter.

## Why / Balance

Resolves #30608

## Media

# Before
Screenshot from 2024-08-03 23-40-54

# After
Screenshot from 2024-08-03 23-40-58

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Plykiya** [comment]
See, though. I coded it so that it's supposed to fallback if there is no iconPrototype set, to the EntityPrototype. So that's not working properly and should be fixed rather than just setting the iconPrototype.

**Comment by Brandon-Huu** [comment]
> I coded it so that it's supposed to fallback if there is no iconPrototype set, to the EntityPrototype.
As far as I can tell that's not what the code does.

It falls back to a iconPrototype that is defined for the entire radial menu. So if multiple things are missing a iconPrototype they all fall back to the same thing.

**Comment by Plykiya** [comment]
> > I coded it so that it's supposed to fallback if there is no iconPrototype set, to the EntityPrototype.
> 
> As far as I can tell that's not what the code does.
> 
> It falls back to a iconPrototype that is defined for the entire radial menu. So if multiple things are missing a iconPrototype they all fall back to the same thing.

I'm the one who wrote it... and I wrote the fix here: https://github.com/space-wizards/space-station-14/pull/30650

**Comment by Brandon-Huu** [comment]
> > > I coded it so that it's supposed to fallback if there is no iconPrototype set, to the EntityPrototype.
> > 
> > 
> > As far as I can tell that's not what the code does.
> > It falls back to a iconPrototype that is defined for the entire radial menu. So if multiple things are missing a iconPrototype they all fall back to the same thing.
> 
> I'm the one who wrote it... and I wrote the fix here: #30650

https://github.com/space-wizards/space-station-14/blob/c04f71728eda8a74f1057608d28195f395ef1a02/Content.Client/Ghost/GhostRoleRadioMenu.xaml.cs#L69-L73

**Comment by Brandon-Huu** [comment]
I'll change it when I'm Not passed out in bed

**Comment by Brandon-Huu** [comment]
Oh you wrote another PR when I already had one open

**Comment by slarticodefast** [comment]
Looks like exactly the same change was done already in #30650, so I'm closing this now.

**Pull request closed without merging**
