### PR TITLE
Cola craft

### PR DESCRIPTION
**Pull request by Kit0vras**
### - Cola craft!
1 Ipecac + 1 Oxygen + 1 Water + 1 Sugar = 4 Cola.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added reaction for cola creation.

### CODE REVIEW

**Comment by deltanedas** [comment]
have you checked that this doesnt conflict with inaprovaline

**Comment by Kit0vras** [comment]
> have you checked that this doesnt conflict with inaprovaline

I think I overlooked this point, thank you. I'll think of something tomorrow.

**Comment by Kit0vras** [comment]
> have you checked that this doesnt conflict with inaprovaline

Resolved

**Comment by AJCM-git** [comment]
merge master

**Pull request merged**
