### PR TITLE
Make crafting names fluent for localization

### PR DESCRIPTION
**Pull request by LightVillet**
## About the PR

Make crafting names fluent for localization

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Review by DEATHB4DEFEAT — COMMENTED** [review]
missing newlines at the end of every fluent file except weapons.ftl and machines.ftl

**Comment by lzk228** [comment]
real pro

**Comment by deltanedas** [comment]
fake noob

**Comment by LightVillet** [comment]
> Names and descriptions shouldn't have fluent syntax inside it, like entityprototypes.

Can you please explain more? I found only `ent-*`, but it's working only with entities

**Comment by LightVillet** [comment]
> Names and descriptions shouldn't have fluent syntax inside it, like entityprototypes.
I am sorry, but I don't understand, why this pr was merged then?
https://github.com/space-wizards/space-station-14/pull/19241

**Comment by LightVillet** [comment]
Okay so far I'm waiting for this pr to be merged https://github.com/space-wizards/RobustToolbox/pull/4335

**Comment by Partmedia** [comment]
With https://github.com/space-wizards/RobustToolbox/pull/4335 this might not be needed. Please re-open if this is not the case.

**Pull request closed without merging**
