### PR TITLE
Change OOC color back.

### PR DESCRIPTION
**Pull request by Pangogie**
Change OOC color back.

Being able to read text is kinda important. Feel free to suggest a better colour for LOOC.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by weaversam8** [comment]
May I suggest `Color.Orchid` for LOOC?

**Comment by metalgearsloth** [comment]
image

I'm fine with that but it does mean I need to change my admin ooc colour.

**Comment by Zumorica** [comment]
Screenshots?

**Comment by Pangogie** [comment]
I went with MediumTurquoise.
image

**Pull request merged**
