### PR TITLE
Many improvements to disposals room

### PR DESCRIPTION
**Pull request by AJCM-git**
Changed the airlock so it had a name and could occlude, added a small light

### CODE REVIEW

**Comment by AJCM-git** [comment]
The diff is so big because all the parents and many of the IDs were updated and some APCs drawed power for some reason and modified their startingCharge by a bit.

**Comment by SweptWasTaken** [comment]
HAHA EAT MY MERGE CONFLICT IDIOT

**Comment by metalgearsloth** [comment]
> 
> 
> HAHA EAT MY MERGE CONFLICT IDIOT

Reverting pr in 3... 2...

**Comment by AJCM-git** [comment]
Merge conflicts solved

**Pull request merged**
