### PR TITLE
Nukie agent requires chemistry hours, rather than general medical hours.

### PR DESCRIPTION
**Pull request by vorkathbruh**
## About the PR
Change nukie agent's playtime requirement from 5 hours medical to 3 hours chemistry.

## Why / Balance
It seemed odd that nukie agents were expected to make chemicals for use in their hypospray but did not require any chemistry hours. Too often will the agent reportedly "not know how to make chems" which just isn't fun for anyone - the agent will be confused, feel pressured, and their teammates will be a little frustrated.

This change was inspired from the discussion in https://discord.com/channels/310555209753690112/1230539113459875940

## Technical details
It's a two line change, from DepartmentTimeRequirement for 18000s Medical to RoleTimeRequirement for 10800s JobChemist

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Webedit ops, first PR, who knows, but it's a two-line change within the role timer requirement. 

**Changelog**

:cl:
- tweak: Nuclear operative agents now require time in Chemistry rather than time in the Medical department.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Pretty sure you need playtime in medical to unlock chem anyways, so this works out perfectly

**Comment by vorkathbruh** [comment]
> Pretty sure you need playtime in medical to unlock chem anyways, so this works out perfectly

Yeah it pretty much extends the amount of time you need to spend overall. I was thinking of 3 hours in chem, as this is what you needed to unlock CMO but this is just simpler.

**Comment by keronshb** [comment]
This will need more discussion. It's not gameplay friendly that a singular nukie role could potentially cost 10 hours (or more if you need to play medical to unlock chemistry).

**Comment by Cojoke-dot** [comment]
> Pretty sure you need playtime in medical to unlock chem anyways, so this works out perfectly

Currently, the nukie agent requires 5 medical hours to unlock while the chemist requires 5 medical hours to unlock... chem takes 6 medical hours to unlock... when you need to make chems as the nukie agent, you should have some time in chemistry so you know what your doing.

**Comment by vorkathbruh** [comment]
After thinking about it, I'm gonna lower the chemistry time requirement to 3 hours. I guess the cumulative time from unlocking chemistry AND playing it for 5 hours is really a lot.

**Comment by Golinth** [comment]
Holy scrap, finally. Hopefully this cuts down on the amount of agents who have never touched chem.

**Comment by Golinth** [comment]
Ah, then it works out really well IMO.

**Comment by vorkathbruh** [comment]
> This will need more discussion. It's not gameplay friendly that a singular nukie role could potentially cost 10 hours (or more if you need to play medical to unlock chemistry).

commander takes at minimum 15 hours to unlock

**Comment by ImWeax** [comment]
> This will need more discussion. It's not gameplay friendly that a singular nukie role could potentially cost 10 hours (or more if you need to play medical to unlock chemistry).

I think it's perfectly fine for agent specifically to have a high hours played requirement, as it is a role that requires a lot of medical knowledge (you are a combat medic, you need to be prepared, and you need to be able to act fast, otherwise your team will die).

Regular nukies are fine to have lower hours - this is what people really want to play, especially those with lower hours. I have seen too many people roll nukie agent and have absolutely no clue how to make medicine, which is the number one thing the role is meant to do in preparation for station assault. If they aren't making meds, they may as well just be another operative rather than agent, and at that point, why even have the Agent role? A few hours of chem is totally reasonable here in my opinion.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
personally, i feel this is more than fine, and just makes it so people actually have to understand what the role is actually meant to do. a new player first experience making chems should not be as a nukie medic.

**Comment by Rainbeon** [comment]
> This will need more discussion. It's not gameplay friendly that a singular nukie role could potentially cost 10 hours (or more if you need to play medical to unlock chemistry).

The Nukie Agent role is by design one that needs that playtime as it requires basic competency in Chemistry to function correctly. As well as this, the bar for Nukie Agent is even higher than an actual Chemist would need to function, as they must do jug chem in a ChemMaster instead of use dispensers like normal, which is an extremely obtuse experience unless you're already familiar with how the machine works and which chems make what.

New players without Chem knowledge being thrown into Nukie Agent will simply not have any fun performing the role they signed up for. Agent is extremely obtuse to learn as it lacks QoL in the form of the dispenser (which is basically a Quality of Life machine, in current balancing), being on a time crunch to figure out what you're actually supposed to do, and not having another player to help you learn, like a CMO or second Chemist would.

As such it is incredibly common for the role to just be off-loaded to someone that wasn't selected as the Agent, thus "trading jobs", or just not having an agent altogether, which is even less friendly to gameplay. It is just a role with a very high skill floor relative to the other antagonist roles, and I think it's sensible to have time requirements that reflect that, as without it gameplay often suffers for all involved.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I think the general sentiment from everyone I talk to is that making the time you need to spend to unlock the role actually teach you the basics on how to actually do that role. As it currently is you get nukies that don't understand how to do basic medical and just pawn it off on another member, not to mention when new med comes in this change will be even more needed as from what I've heard, even basic combat meds will, react badly with other chems and could easily lead to the death of an entire team. overall, this is needed now, it was needed months ago, and it will be even more needed when new med comes out. this isn't about making it less friendly for new players, it's about making it so people can actually do their job on a high stress role that drives the round forward. it's not fun for other people to have to do another person's job because they were not given enough time to learn how to play the game, all it does it breed animosity among the nukie team.

**Comment by vorkathbruh** [comment]
Alright I'll give my full thoughts in this message

I can understand why the maintainers don't want excessive role timers - the sooner that players can get eligible for playing the roles they want, the better the experience. However, I think that there are exceptions to be made for certain roles, particularly the command roles and team antag roles. Syndicate agents are fine for anyone to be, a new syndicate agent doesn't really harm anyone, so why not let anyone opt in? But there's a huge problem with having an agent who simply has never touched chemistry in their entire playtime. Operatives are fine at 5 hours of playtime - for a similar reason that syndicate agents are fine to not have locked behind a role timer. Operatives have no particularly special duties or equipment, so they are the most 'basic' of the nukie roles. An agent is very specialized - you have to know how to play operative, plus how medical and chemistry works. Because of this, why would you be able to queue for agent without ever having touched chemistry? Any operative can apply sutures and meshes, so the chemistry part is really what's expected from the agent due to the hypospray.

Anyway, It's an anecdote but I don't think its crazy for me to say that a significant amount of agents that I have played with, upon some asking, reveal to me that they have NO idea how chems work. The most common approach is just saying "okay, look, give me your specialized gear and I'll play as the agent." This, I think, reveals a problem - players are queueing into agent, knowingly or unknowingly expecting to be able to pawn off the duty to someone else. Let's assume that they aren't. A person rolls nukie agent for the very first time without touching chem. They have to prepare and purchase items accordingly with their team, AND learn chemistry at the same time. They will inevitably be under time pressure and pressure from their peers since the nukies will of course want to leave eventually. I think this is the reason that a lot of the times the situation arises where the agent just gives up their role to someone else. The question is, is this fine or should they just have not been able to opt in for agent to begin with and 'take' this antagonist role over the person who DID have at least some experience with chemistry?

This is all to say, I think even when assuming good faith, someone playing nukie agent for the first time with 0 chemist is simply an overwhelming experience and it would be far more constructive if players had at least encountered and messed with chemistry before being able to play agent. I don't expect or want this role timer to be a 'robust player filter', but to make things go a bit more smoothly, as the clueless nukie agent is not fun for anyone, especially since it is arguably THE most important member on the nuclear operative team.

**Comment by EpicJoston** [comment]
While I think this is a good change, I don't think role timers are enough. We as a community need to make learning tools way more accessible to newcomers. SS14 is a hard game to learn and this would help in all aspects of the game, not just Nukie Agent.

Whether that be more online tutorials, reviving the wiki, or allowing the in-game guidebook to become far more detailed, something needs to happen, or we're going to constantly run into issues exactly like this.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I don't mean to seem rude or impatient but a change like this isn't asking for much and all it does it stop people who don't know how to play the role... from playing the role, and while it may seem like it may hamper a new player, there are both other nukie operatives that can be played and it's not fun for other people that have to pick up the slack of a bad medic.

I emphatically request that this be merged as this has been open for a while now and no negative opinions have made themselves known that have not been given a fair rebuttal and discussion.

**Comment by deltanedas** [comment]
merg

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
heya, do we know what's going on with this?

**Comment by metalgearsloth** [comment]
> heya, do we know what's going on with this?

Stop spamming the pr or I'll just close it.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I was just asking as nothing had been said about it for a week, and was wondering what was going on with it. i don't mean to sound inpatient.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
