### PR TITLE
Wizard GameRule and SpellBook

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

More progress towards implementing wizards for realsies. This does **not** add the wizard to the secret game mode pool, but it is able to be added both before and mid-round.  More spells/more balance/more testing should probably be done before it's set to be automated at round start/mid-round.

Checklist:
[x] Add game rule and game config preset
[x] Add entity content for spawners and ghost role spawners
~~[ ] Add the spawners to the wizard shuttle~~ (in a new PR, it works and tests fine without it but the spawn location isn't precise and I want to make some other changes to the shuttle at the same time)
[x] Add a spellbook using the store system and catalog existing wizard items
    [x] Balance the spellbook offerings (I gave them fairly arbitrary spell point costs, mostly in line with /tg/)
        - wands are limited charges so cheaper, staves are pretty pointless with their spells so they are also cheap, and books are just on cooldown so they are a bit more expensive. That's the extent of my balance reasoning.
[x] Add/Assign custom sprites for the spellbook, spell points, and spawner icons
[x] Finish localization for literally everything
[x] Discuss objectives and win conditions. Some places ended the round when the wizard dies but I have it implemented as optional, and with the station defaulting to the ramping event scheduler instead (basically like zombies).  Even though a wizard may be defeated, their loot is often still the most dangerous and chaotic stuff and having it in the hands of the crew still fulfills the purpose of increasing the chaos on station so I have it set to not end the round, but its a simple boolean in the gameruleconfig to enable that behaviour if we want.  Consensus seems to be that wizards only have abstract, fanciful objectives with no real success or failure states, so in the meantime I will look into the objectives system to see if I cant just write some silly abstract texts for objectives

**Media**

TODO: gunna flag this for review and get the tests going while making some kind of video or something i suppose
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: checkraze
- add: The Wizard Federation has gained an interest in Space Station 14!

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
tiny little nitpick with the cl, it's "Space Station 14"

**Comment by Cheackraze** [comment]
> tiny little nitpick with the cl, it's "Space Station 14"

fixed thanks

**Comment by GoodWheatley** [comment]
While I'm as excited to see a new antag as everyone else, I don't think we're ready for wizard to be fully implemented until keron refactors mind at the very least. There's a lot of core issues with how wizard code works, like:
- No voicelines when using spells & mute toxin doesn't stop verbal spells from being cast
- Massively reduced spell variety, almost no staffs, no funny melee weapons
- No way for a purchased spell to be directly put in a wizard's mind without severe jank iirc, so we have to use the spellbooks which not only don't disappear after being read, but also can be used by crew to learn spells (but if spellbooks work the way I remember them working, where you actually have to hold it to cast the spell, that's even worse since all you need to do is slip the wizard and now you too can wield the powers of space magic)
- No way to refund spells so the wizard can test them out before committing to them
- No scroll of teleportation to get onto the station, the wizard can't realistically use a shuttle to get there since he then has no reason to protect it after boarding, and the only way for him to actually board the station requires buying specific spells or items
- No requirement for him to wear robes for casting certain spells/using spells at their full power
While I do like to see the groundwork for wizard being laid, I don't think it's the right time to add a GameRule for it. It's probably going to give players the wrong impression if the admin says they're spawning in a wizard and a greytider who can throw fireballs shows up.

**Comment by EmoGarbage404** [comment]
I think the only thing that I'd consider necessary is the spell variety and the teleportation. Everything else is kinda secondary. My main issue with the current set of equipment is that most of it is pretty weak. The only good offensive options you have are fireball and instant death.

**Comment by 0x6273** [comment]
You could add "no client prediction" to the list of wizard code issues. I imagine this is not gonna feel so great to play if your ping isn't good, like if you're an  eu player on lizard.

**Comment by GoodWheatley** [comment]
> I think the only thing that I'd consider necessary is the spell variety and the teleportation. Everything else is kinda secondary. My main issue with the current set of equipment is that most of it is pretty weak. The only good offensive options you have are fireball and instant death.

The voicelines and robes are more important than you'd think, since the robe requirement and the voicelines heavily discourage the wizard from going fully stealth and just killing people in maints, and mute toxin is one of the most reliable ways to counter a wizard, since they can't launch fireballs or turn themselves into an immovable rod while the chem is metabolizing (The spell being cast is dependent on the voiceline being said. If the wizard can't speak, they can't cast the spell).

> You could add "no client prediction" to the list of wizard code issues.
~~You have alerted the sloth~~

**Comment by Cheackraze** [comment]
I appreciate the discussion but sadly all of this has more to do with spells themselves and not the gamerule presented here.  I also agree with most of these critiques on the spell casting system but it's off topic.  This is merely handling the spawning of the wizard and the creation of the magic item shop that they can use to purchase their magical effects.

Also I don't think anything in this pr needs prediction?

**Comment by 0x6273** [comment]
> Also I don't think anything in this pr needs prediction?

I think the wands are fine since they seem to use guncode, but the spells that you learn and cast from the action bar are not predicted when they definitely should be.

Also, it seems like fireball book spell is bugged and always fires in the same direction no matter where you click.

**Comment by Cheackraze** [comment]
> > Also I don't think anything in this pr needs prediction?
> 
> I think the wands are fine since they seem to use guncode, but the spells that you learn and cast from the action bar are not predicted when they definitely should be.
> 
> Also, it seems like fireball book spell is bugged and always fires in the same direction no matter where you click.

So no, nothing in this pr them.  This PR has nothing to do with individual spells or items and how they work.

**Comment by Cheackraze** [comment]
> Its weird to claim that your pr adding the wizard gamemode isn't related to the spells that they have available.

Balancing/fixing/creating new spells is completely out of scope, and discussion about them should be in a separate issue post, its just clogging this PR up and is completely irrelevant.

**Comment by HoidC** [comment]
I mean as far as I understand it this PR is adding wizards. You need to fix the current books at the very least, surely. (the fireball spell kills you if you use it while moving for example)

**Comment by Cheackraze** [comment]
> I mean as far as I understand it this PR is adding wizards. You need to fix the current books at the very least, surely. (the fireball spell kills you if you use it while moving for example)

No, that's 100% out of scope and should be brought up in a separate issue post.

Nukie game rule didn't create and rebalance all the syndicate shop items, nor did pirates, nor anything.  Please keep discussion to the content of the PR

**Comment by EmoGarbage404** [comment]
The comparison to operatives doesn't really apply, considering they reuse the traitor store. As this currently stands, all of the mechanics in this pr are in service of weapons/spells that are underwhelming, broken, and not viable for the actual gamemode being created.

Maybe making a bunch of spells isnt in scope, but its obviously related to the goal at hand.

**Comment by Cheackraze** [comment]
> The comparison to operatives doesn't really apply, considering they reuse the traitor store. As this currently stands, all of the mechanics in this pr are in service of weapons/spells that are underwhelming, broken, and not viable for the actual gamemode being created.
> 
> Maybe making a bunch of spells isnt in scope, but its obviously related to the goal at hand.

Then create an issue about those particular abilities.  It is off topic here.

**Comment by 0x6273** [comment]
This is admin only if I understand it correctly (can't be voted and not in secret_weights.yml) so I think it's probably fine to view this in isolation of the current state of wizard content?

**Comment by Cheackraze** [comment]
> This is admin only if I understand it correctly (can't be voted and not in secret_weights.yml) so I think it's probably fine to view this in isolation of the current state of wizard content?

Yes and i state as much in the description.  There is also some debate about whether wizards should be round start or mid round, and downstreams will probably want opposite behavior from what generic LRP wizard den operates, so it's set up to handle both traditional mechanics (round start, opt-in, and round ends when wizard dies, etc.) Or alternatively to be mid-round, non-round ending, etc, until game admins decide how it should actually function on their server.  I tried my best to make it as customizable and easy to configure for potential downstreams as possible with various modes in mind.

**Review by keronshb — CHANGES_REQUESTED** [review]
One thing that Wizard should be doing is letting the caster use spells innately without the need of the books, like how it works on SS13. A challenge I found is that it wasn't something super tangible with the current mind system. That's something that will really make Wizard, well your classic Wizard. 

If you can find a way to do this with the current mind system then more power to you, but I also feel having wizards cast spells without books is more or less a requirement for it to be implemented.

You should also add the option to turn someone into a wizard in the antag menu.

**Comment by Cheackraze** [comment]
> One thing that Wizard should be doing is letting the caster use spells innately without the need of the books, like how it works on SS13. A challenge I found is that it wasn't something super tangible with the current mind system. That's something that will really make Wizard, well your classic Wizard.
> 
> If you can find a way to do this with the current mind system then more power to you, but I also feel having wizards cast spells without books is more or less a requirement for it to be implemented.
> 
> You should also add the option to turn someone into a wizard in the antag menu.

so you're requesting I fix someone else's completely unrelated code, that you even admit is impossible to do, in systems completely out of scope of the PR, before this gets reviewed? I might as well just close this then because as stated multiple times that is completely out of scope of this PR and you even state that it is not possible to do currently.  Why are you letting perfection get in the way of progress on game modes that the game is desperately lacking, this makes 0 sense.

If this book problem is such a huge issue why were they added in that state to begin with and why wasn't the original author made to make these changes? It seems that they operate just fine, at least good enough to have been added to the game.

**Comment by HoidC** [comment]
> > One thing that Wizard should be doing is letting the caster use spells innately without the need of the books, like how it works on SS13. A challenge I found is that it wasn't something super tangible with the current mind system. That's something that will really make Wizard, well your classic Wizard.
> > If you can find a way to do this with the current mind system then more power to you, but I also feel having wizards cast spells without books is more or less a requirement for it to be implemented.
> > You should also add the option to turn someone into a wizard in the antag menu.
> 
> so you're requesting I fix someone else's completely unrelated code, that you even admit is impossible to do, in systems completely out of scope of the PR, before this gets reviewed? I might as well just close this then because as stated multiple times that is completely out of scope of this PR and you even state that it is not possible to do currently. Why are you letting perfection get in the way of progress on game modes that the game is desperately lacking, this makes 0 sense.
> 
> If this book problem is such a huge issue why were they added in that state to begin with and why wasn't the original author made to make these changes? It seems that they operate just fine, at least good enough to have been added to the game.

they don't operate good enough to have been added to the game 

I get what you're saying and you're right - it's admin only thus it's fine as it's a step toward adding it - but wizard content is not at the point at which it should be added to the game.

**Pull request closed without merging**
