### PR TITLE
Buffs the syndicate minibomb to be more devastating

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
...and changes some other syndicate explosive descriptions to be more descriptive. Couldn't fit it in the PR title, sorry!

It's no secret - the minibomb fucking _sucks._ For 6 TC, you get something that is basically just a glorified atmos drainer / body gibber. Despite having niche uses, I believe most players would consider it an utter waste of telecrystals when you could usually just break windows to space a room.

This turns the Syndicate minibomb into a tool designed to breach & _ruin_ small rooms. It does mediocre damage to walls,
but will easily tear sizable holes through the floor and cause entire rooms to be uninhabitable until they can be fixed by engineering / atmos.
To compensate for the massively increased breaching power, the price of the bomb has been nerfed down to 8tc.

**Media**

[Content.Client_UrC1vYQfNv.webm](https://user-images.githubusercontent.com/78941145/214610474-5593ddd3-5dfa-4dfb-96b0-725b5eb21667.webm)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The syndicate minibomb has been buffed.
- tweak: The syndicate has re-described several entries in their explosives catalog.

### CODE REVIEW

**Review by AJCM-git — CHANGES_REQUESTED** [review]
im pretty sure you can just use the localization string as the prototype description to avoid duplication
`description: uplink-explosive-grenade-desc`
in the prototype, for example

**Comment by arealbeba** [comment]
i don't like this, the thing is MINIbomb for a reason

**Comment by metalgearsloth** [comment]
Doesn't this just make it a more expensive version of the explosive bomb.

**Comment by Flareguy** [comment]
> Doesn't this just make it a more expensive version of the explosive bomb.

No, actually! The explosive grenade flat out cannot breach, gib, or destroy walls. The minibomb is unique in its breaching & gibbing capabilities.

**Comment by Flareguy** [comment]
> im pretty sure you can just use the localization string as the prototype description to avoid duplication `description: uplink-explosive-grenade-desc` in the prototype, for example

image
Doesn't work, unfortunately.
Probably for the best, since if someone changes the uplink description they could unknowingly mess up the item one.

**Pull request closed without merging**
