### PR TITLE
Fire anom rework

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Improved gameplay from the fire anomaly. Now it shoots slow exploding fireballs, gradually destroying the containment chamber. The explosions are weak enough to not require control after each pulse.

Overall, the gameplay becomes extremely similar to Ice Anomaly, which is an example of a good difficulty balance 

## Why / Balance
Fire Anomaly is too easy to maintain. Players build it up with glass and it becomes completely safe and does not require maintenance.

## Media
explosion power:

https://github.com/shampunj/space-station-14/assets/96445749/8655863e-169c-4590-92d6-329f78d40237

fireballs behaviour: (old video with OP explosion)

https://github.com/space-wizards/space-station-14/assets/96445749/5b3fcc9e-4df9-4680-b168-8b485dfc730b

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The fire anomaly is now heavier in content.
- tweak: Artifacts no longer block projectiles.

### CODE REVIEW

**Comment by Kadeo64** [comment]
does it still pulse and ignite people through the containment chamber or has that been removed because it's actually been balanced

**Comment by EmoGarbage404** [comment]
> does it still pulse and ignite people through the containment chamber or has that been removed because it's actually been balanced

kid named look at the changes in the PR

**Comment by TheShuEd** [comment]
is still setting people on fire. Suffer.

**Comment by EmoGarbage404** [comment]
nah new sprite is gas

**Comment by Kadeo64** [comment]
> > does it still pulse and ignite people through the containment chamber or has that been removed because it's actually been balanced
> 
> kid named look at the changes in the PR

video wasn't there when I made the comment 8head

**Comment by Aisu9** [comment]
honey look! another anomaly every one will want destroyed just dropped

**Comment by TheShuEd** [comment]
# Update
Also removed the imbalanced function of artifacts to block projectiles. Now you can't put an artifact under an ice or fire anomaly, completely removing the damage to the environment

**Comment by GreyMario** [comment]
at this rate anomalies are going to become too much risk for no reward; may as well get rid of the anomaly generator, no one's going to use it

**Comment by LankLTE** [comment]
This is just making another anomaly that you literally have to sit on top of 24/7. I’ve discussed before how I’m not really a fan of that kind of gameplay.

**Comment by JoeTheJanitor** [comment]
> This is just making another anomaly that you literally have to sit on top of 24/7. I’ve discussed before how I’m not really a fan of that kind of gameplay.

Making science have to actually keep an eye on anomalies instead of just turning them into glorified automatic point generators seems like a good thing. Right now, players just space the tile under it with an RCD, build a few directional windows, and forget about it.

**Comment by LankLTE** [comment]
> Making science have to actually keep an eye on anomalies instead of just turning them into glorified automatic point generators seems like a good thing.

I agree that making them do something more than just building a box around it is good, but I'm going to be real I don't think sitting in one place with a welder for an hour is enjoyable gameplay for anyone.

**Comment by Carmell0** [comment]
Hear me out: whenever you kill a anomaly you get a bunch of points, to help cope with anom powercreep

**Comment by notquitehadouken** [comment]
hot

**Pull request merged**
