### PR TITLE
Cleans up gun yaml

### PR DESCRIPTION
**Pull request by RiceMar1244**
## About the PR

Cleans up the yaml for a bunch of guns to more closely follow the specified yaml conventions at https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html as well as use multiple inheritance.

Please review this PR by commit. I do my very best to ensure that the changes are as easy to follow as possible by using atomic commits. It should be clear in each commit that nothing functionally changes, and as I continue, I get better at being clearer. I apologize for the size of this single PR, it was a bit of a rabbit hole since i set myself up to rely on the changes in this PR. I will avoid this in the future and I hope that in every other way, this PR is easy to review.

If you'd prefer instead, I've included a series of self-testing videos below to demonstrate that everything is still functional. You may also look at the changed files and verify that everything looks good, as I've improved their readability greatly.

## Why / Balance

I noticed that the yaml was a bit of a mess when I was previously working on something else and wanted to clean it.

### The goals of this cleaning
- fix formatting to closely follow wizden yaml conventions.
- remove base prototypes that represent "weapon types" and replace them with a collection of base prototypes that represent "weapon qualities".
- use multiple inheritance to build entity prototypes out of these inheritable qualities to improve clarity and ease of maintenance.

With these changes, the components list under a prototype look like a collection of properties unique to the entity (such as its visuals), as well as any variations on its inherited archetypes.

### The organization principles of this PR
- Prioritize inheritable templates that represent generic qualities over templates that try to represent a class of weapon. This makes the templates more flexible. Templates based on weapons types often overlap with each other and overextend on the most-fundamental identity of the weapon type. The borg-module L6 ROW could not inherit `BaseWeaponLightMachineGun` because it included components for magazines, which it doesnt need because it uses a battery.
- Seek to provide central points of control. Many weapon prototypes in `battery_guns.yml` specify the same fired hitscan with the same energy cost. This has been extracted to a base template such as `BaseGunRedMediumLaser`, even though it includes only a single component. This allows the standard firing cost to be controlled in one spot.
- When you create base templates, create them in a separate file. This is good separation, and as far as workflow goes, it allows somebody using your templates to move between tabs instead of scroll through walls of text.
- Seek to improve ease of prototyping but do not provide unnecessary defaults. Base templates like `BaseWeaponPistol` specified a default pistol sprite, when abstract prototypes should not specify textures (and the pistols would never realistically reuse the unique weapon sprite).

Please freely give feedback on my choices here, especially including stuff like naming conventions. I want these possibly-lasting changes to be as positive as they can be.

## Technical details

Just yaml

## Media

```Videos below recorded from commit [a78450c] and [d2251a6] in this branch.```

Please see this playlist of videos for a complete recording of personal testing. I go through the guns and ensure they still work the same.
https://youtube.com/playlist?list=PLWh913sXFuBuhNq_HzFV5AqyFH-UVeqq1&si=kBsIshuCXBvGrdR0
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

These changes may not be breaking, but I want to note that I have moved a number of base entity prototypes into a file called `legacy_guns.yml`, so that they can continue to be available to downstream prototypes that use them, with the intention that forks may remove them at their discretion. Moved prototypes are listed below:
- `BaseWeaponLightMachineGun`
- `BaseWeaponPistol`
- `BaseWeaponBattery`
- `BaseWeaponPowerCell`
- `BaseWeaponBatterySmall`
- `BaseWeaponPowerCellSmall`
- `BaseWeaponHeavyMachineGun`
- `BaseWeaponLauncher`
- `BaseWeaponRevolver`
- `BaseWeaponRifle`
- `BaseWeaponShotgun`
- `BaseWeaponSubMachineGun`
- `BaseWeaponSniper`
- `WeaponProtoKineticAcceleratorBase`
- `WeaponWaterGunBase`
- `BaseBow`

You may use the new abstract entity prototypes found in `base_gun.yml` and other weapon-type related files like `base_pistols.yml` to rewrite weapon prototypes to use multiple inheritance.
Remember the organizational principles highlighted in the PR.

**Changelog**

No CL!

### CODE REVIEW

**Comment by RiceMar1244** [comment]
Might make base templates for guns that fire specific hitscans since they seem to generally copy the same fire cost across their use

**Comment by FungiFellow** [comment]
Thanks for the clean up 👍

**Comment by RiceMar1244** [comment]
I'd push my new changes and undraft but my internets out for idk how long :/

**Comment by RiceMar1244** [comment]
Hold on whats goin on here-

**Comment by RiceMar1244** [comment]
Ok so I think these are just build errors that are happening to every recent push thats weird

**Comment by RiceMar1244** [comment]
Ok, I really didnt wanna pile more on to this, but thats what happened. I can just leave it alone now.

**Comment by RiceMar1244** [comment]
Oh i just realized that getting rid of the old base parents like that might cause problems for downstream weapon yaml files that use it. I should probably put those back in some kind of 'deprecated' file or something.

**Comment by RiceMar1244** [comment]
> Oh i just realized that getting rid of the old base parents like that might cause problems for downstream weapon yaml files that use it. I should probably put those back in some kind of 'deprecated' file or something.

Ive spoken to maintainers and received advise on the matter.

**Comment by RiceMar1244** [comment]
Ok so whatevers going wrong here Ill look into it tomorrow

**Comment by RiceMar1244** [comment]
Excuse me if I dont actually look into it 'tomorrow' (today) lmao- Ive got a few life things to be sorting out today.

**Comment by RiceMar1244** [comment]
Alright all clear. Testing video incoming. Ive got a pretty encompassing list here of things to check for on each weapon and ill be running through them in-game.

**Comment by RiceMar1244** [comment]
Aight the testing videos are attached and I can say that this thing is actually ready for review now

**Comment by RiceMar1244** [comment]
The foam dart rifle got added, so before this can be merged Ive got to fix its prototype since BaseWeaponShotgun is not a thing anymore.

**Comment by RiceMar1244** [comment]
Any additional commits from here on will be me maintaining this PR. For example, somebody just merged a PR adding the AmmoCounter component to pistols, and it caused merge conflicts for this PR, so I just now resolved that conflict.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Just combine BaseGun<Size> and BaseGun

**Comment by Partmedia** [comment]
Significant changes like this, especially to many abstract base entity prototypes, are likely going to be very disruptive for forks. Is it absolutely required that all of these base entity prototypes get removed/renamed?

**Comment by RiceMar1244** [comment]
> Significant changes like this, especially to many abstract base entity prototypes, are likely going to be very disruptive for forks. Is it absolutely required that all of these base entity prototypes get removed/renamed?

So, I do understand that this might cause disruption for forks and I have been thinking about that, which is why I wanted to be very clear in documenting what was removed. 

I dont mean to say this to deflect off of myself in any way, these are my changes and this is my PR, but when ive talked to maintainers about my progress here before, it sort of seemed like a 'rip a bandaid off' type of situation for downstream (iirc). I thought that would be fine since my goal here was to make it real easy to rewrite the prototypes.

The reason I removed all those base entity prototypes was because I dont think that they can really encompass universal qualities of a weapon archetype very well. I wanted to replace that with just the qualities. I can try to combine my qualities into the weapon archetypes themselves but that might not be much better than removing them because they still wouldnt do what downstream prototypes expect them to.

**Comment by RiceMar1244** [comment]
I am absolutely open to discussing a less disruptive way to do this.

**Comment by RiceMar1244** [comment]
Like with this ive kind of been waging a mini war with the concept of trying to embody an archetype instead of a quality and its possible I carried it too far. Admittedly there is value to defining the weapon archetypes, and I can surely look into remaking those archetypes out of the smaller qualities, so that I can "have my cake and eat it too" i guess lol

**Comment by Partmedia** [comment]
> it sort of seemed like a 'rip a bandaid off' type of situation

Analogies only go so far; but I would liken this to ripping off an arm (since this would likely result in runtime "server failed to start due to missing prototype" issues).

> Like with this ive kind of been waging a mini war with the concept of trying to embody an archetype instead of a quality

Another concern with this is how durable this "rip a bandaid off" situation is. If the next person has a slightly different idea of how weapons classes should be organized, do we rip this bandaid off, too, and break everything again?

> I am absolutely open to discussing a less disruptive way to do this.

At minimum, you should provide clear, unambiguous instructions for what a fork can do to migrate.

Even better, you can preserve all of the abstract base prototypes you removed, move them into a separate file, e.g. `legacy_guns.yml`, and do your best to make sure they still behave in reasonable ways.

Or, you can try to make the cleanup without affecting the base organization.

**Comment by RiceMar1244** [comment]
Thank you for the feedback. While I act on it, should I draft this PR?

**Comment by RiceMar1244** [comment]
Also,
> Even better, you can preserve all of the abstract base prototypes you removed, move them into a separate file, e.g. `legacy_guns.yml`, and do your best to make sure they still behave in reasonable ways.

When you mention ensuring that the legacy base prototypes still behave in reasonable ways, do you anticipate that it won't be as simple as just copy/pasting the old prototypes into the legacy_guns.yml file and not modifying them?

**Comment by metalgearsloth** [comment]
Sometimes I get doing like 1 or 2 breaking changes like the soda dispenser one, but this one is large and would affect every downstream quite painfully.

I would just dump them in another yaml file for the foreseeable future.

**Comment by RiceMar1244** [comment]
I see I see, yikes. Alright sure.

**Comment by RiceMar1244** [comment]
Oh fuck I forgot to build it like I told myself to lol

**Pull request closed without merging**
