### PR TITLE
Removes Trials of Mana grassland sprites: Bare Minimum Edition

### LINKED ISSUE #26449: Grass & dirt sprites need to be replaced / resprited
## Description
To be more specific, the offending sprites in question are ``Resources\Textures\Tiles\Planet\dirt.rsi`` and ``Resources\Textures\Tiles\Planet\Grass``.

image

Hilariously, these sprites are literally just straight up taken from Trials of Mana.
Outside of the obvious, these definitely do not fit the art style anyways (they're from an entirely different game, duh) and are pretty hueshifted & low in detail.

We have a few sprites in the repo to replace these already, namely ``grass.png``, ``grassdark.png``, and ``grasslight.png`` in the ``Resources\Textures\Tiles`` folder.. They are pretty noisy and likely won't look nearly as good, but should do the job alright.
If you can, you should probably add edge tiles to whatever one you decide to make the new "normal" grass, even if you suck at art and want to take this issue on. They are pretty important to making the grass biome look good.

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Since test fails were failing on #28838 and we need to get this out of the repo, I have remade the PR.
This replaces all grassland sprites from Trials of Mana with the "noise" grass sprites we had before. *This does not remove any content* since test fails were mysteriously failing on the previous PR. Someone will need to clean it up later.

Resolves #26449.

## Why / Balance
These sprites are from a real-ass game. We cannot use them.

The "noise" grass is also a much better replacement then the other grass. Dark/light grass is extremely noisy and probably needs to be removed later.

## Media
Content Client_S6OQVWUBwO

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by B1essedknight** [comment]
Seems that Git may be having a stroke with its tests. 

A different PR replaced only one sprite and all the tests failed.

**Comment by 0x6273** [comment]
> Seems that Git may be having a stroke with its tests.
> 
> A different PR replaced only one sprite and all the tests failed.

This PR deletes a sprite without replacing it. Pretty sure that's why the tests are failing.

**Comment by Ko4ergaPunk** [comment]
Why this merged? That's worst shit i've ever seen. If you just cut sprite from game DRAW alternative. That's not alternative. It looks much worse than what it was before

**Comment by NotSoDana** [comment]
God damn it.. why merge..? The worst thing i've ever seen in tiles..

**Pull request merged**
