### PR TITLE
add health icons to the secmed hud

### PR DESCRIPTION
**Pull request by PrPleGoo**
## About the PR
Added health icons to the sec hud

## Why / Balance
https://discord.com/channels/310555209753690112/1221690653990326273/1221690653990326273

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
Nope

**Changelog**
:cl:
- tweak: The crafted medsec hud now displays health icons too.
- tweak: The health status icon now goes on the left for all types of med HUD.

### CODE REVIEW

**Comment by Golinth** [comment]
IMO you should keep the health icons off the HUD. It adds even more clutter to the right side of the character (3 icons at once!), and makes an already very powergamey item even more powerful. 
I viewed the medsec as the sechud icon replacing the medical icon, instead of both working together.

**Comment by Golinth** [comment]
> I could just move the security status icons to the left. It makes more sense to have the HUD that displays 2 icons to use both sides of the mobs instead of just the right side.

Maybe the med icon on the left instead? The sec icons being on the right is ingrained in my brain from hundreds of hours in sec

**Comment by PrPleGoo** [comment]
> > I could just move the security status icons to the left. It makes more sense to have the HUD that displays 2 icons to use both sides of the mobs instead of just the right side.
> 
> Maybe the med icon on the left instead? The sec icons being on the right is ingrained in my brain from hundreds of hours in sec

There's probably med players who will yell the same thing about the medical icon. And I just moved the status - not the job.

**Comment by Golinth** [comment]
> There's probably med players who will yell the same thing about the medical icon. And I just moved the status - not the job.

Completely fair. Though it is worth noting that the sec status icons are intended to be connected to the job icons, from #26203

**Comment by PrPleGoo** [comment]
Ah is that what the offset is for on those things, right that makes sense. I'll just move the med icon then 👍

**Comment by PrPleGoo** [comment]
fucking kill me bro

**Pull request closed without merging**
