### PR TITLE
Make handheld flash not flash thourgh walls.

### LINKED ISSUE #5915: Flashing through walls.
## Description

The handheld flash can flash people through walls when activated in-hand. 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Charlese2**
Fixes #5915 
Also make it so mobs don't block the flash.

## About the PR 

**Screenshots**

**Changelog**

:cl: Charlese2
- fix: Flashing through walls.

### CODE REVIEW

**Review by PaulRitter — CHANGES_REQUESTED** [review]
why have it be split into two loops. afaict, this all can/should be done with one loop

**Comment by Charlese2** [comment]
If it is in the same foreach loop the flashableEntities list is not populated with all the mobs in the area yet. The InRangeUnobstructed method needs a full list so it can ignore Opaque objects (players) in the obstruction check. You get inconsistent results if some mobs will block the flash and some wont depending on where it is in the loop.

**Review by ShadowCommander — APPROVED** [review]
Walked them through it last night. Seemed like the only way to make it ignore flashable entities without messing with more physics collision groups.

**Review by PaulRitter — APPROVED** [review]
nevermind, i didnt see the lambda

**Pull request merged**
