### PR TITLE
Dress everyone up as clowns

### PR DESCRIPTION
**Pull request by Litogin**
## About the PR

The station staff will be dressed as clowns or partially
## Why / Balance

On the first of April

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Litogin
- tweak: everyone jobs clown clothes

### CODE REVIEW

**Comment by KingOnBudget** [comment]
Will the mime dressed up like a clown too??

**Comment by UbaserB** [comment]
You need to use the april fools branch, not master

**Comment by Litogin** [comment]
> Мим тоже переоденется клоуном??

No, the mime will remain in his clothes

**Comment by Litogin** [comment]
> Вам нужно использовать первоапрельскую ветку, а не мастер.
ok my mistake

**Pull request closed without merging**
