### PR TITLE
SMES QoL

### PR DESCRIPTION
**Pull request by VelonacepsCalyxEggs**
## About the PR
I have added some QoL for SMES. 
SMES now has some damage overlays, and an aftermath of it's destruction as well as an ability to repair it.
A bit more details:
When SMES reaches it's critical state, it spills 100u of licoxide. If it keeps being damaged, it explodes, and releases 64 moles of flaming plasma.

## Why / Balance
SMESes are a fairly important part of the station, and their "repairablity" and damage indication is very important, in my opinion.

## Media
https://youtu.be/KkeKjtaWm9c?si=8JODvBOg99JzXFrm

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: SMES has a damage overlay now.
- tweak: SMES can now be repaired with a welding tool.
- tweak: SMESes now explode when destroyed and cause a small plasmafire as well as spill licoxide.

### CODE REVIEW

**Comment by lzk228** [comment]
flaming plasma is too much

**Comment by EmoGarbage404** [comment]
test fails are not erroneous btw

**Comment by Holinka4ever** [comment]
Spilling 100u of licoxide for just putting into a critical state? Isnt it seems a bit of... usefull for whom that doing it?
Licoxide by the way, were nerfed from being easy earnable and powerfull reagent cause you just grinding batteries.

But then it got a change, that you need grind steel and batteries(also chemmaster) to get even one unit of it.

Giving free 100u of licoxide, by just beating SMES to critical state feels not okay

Thats my opinion

**Comment by JoeHammad1844** [comment]
if only we had standing fires from 13 instead of having to use plasmafires

**Comment by VelonacepsCalyxEggs** [comment]
> Spilling 100u of licoxide for just putting into a critical state? Isnt it seems a bit of... usefull for whom that doing it?
> Licoxide by the way, were nerfed from being easy earnable and powerfull reagent cause you just grinding batteries.
> 
> But then it got a change, that you need grind steel and batteries(also chemmaster) to get even one unit of it.
> 
> Giving free 100u of licoxide, by just beating SMES to critical state feels not okay
> 
> Thats my opinion

Agreed, 100u of licoxide is a bit too much. Maybe 30u is much more viable?

**Comment by VelonacepsCalyxEggs** [comment]
> if only we had standing fires from 13 instead of having to use plasmafires

Yeah...

**Comment by VelonacepsCalyxEggs** [comment]
I'll do some changes as soon as I get back home.

**Comment by Holinka4ever** [comment]
> > Spilling 100u of licoxide for just putting into a critical state? Isnt it seems a bit of... usefull for whom that doing it?
> > Licoxide by the way, were nerfed from being easy earnable and powerfull reagent cause you just grinding batteries.
> > But then it got a change, that you need grind steel and batteries(also chemmaster) to get even one unit of it.
> > Giving free 100u of licoxide, by just beating SMES to critical state feels not okay
> > Thats my opinion
> 
> Agreed, 100u of licoxide is a bit too much. Maybe 30u is much more viable?
Licoxide is powerfull even in 5 units. But.
I see that you still to want to add it, so what about to add licoxide smoke on critical state?It will turn mes actually dangerous device to work with.

**Comment by VelonacepsCalyxEggs** [comment]
> > > Spilling 100u of licoxide for just putting into a critical state? Isnt it seems a bit of... usefull for whom that doing it?
> > > Licoxide by the way, were nerfed from being easy earnable and powerfull reagent cause you just grinding batteries.
> > > But then it got a change, that you need grind steel and batteries(also chemmaster) to get even one unit of it.
> > > Giving free 100u of licoxide, by just beating SMES to critical state feels not okay
> > > Thats my opinion
> > 
> > Agreed, 100u of licoxide is a bit too much. Maybe 30u is much more viable?
> 
> Licoxide is powerfull even in 5 units. But.
> I see that you still to want to add it, so what about to add licoxide smoke on critical state?It will turn smes actually dangerous device to work with.
Indeed! Great idea, you mean like foam that dissipates over time?

**Comment by Holinka4ever** [comment]
> > > > Spilling 100u of licoxide for just putting into a critical state? Isnt it seems a bit of... usefull for whom that doing it?
> > > > Licoxide by the way, were nerfed from being easy earnable and powerfull reagent cause you just grinding batteries.
> > > > But then it got a change, that you need grind steel and batteries(also chemmaster) to get even one unit of it.
> > > > Giving free 100u of licoxide, by just beating SMES to critical state feels not okay
> > > > Thats my opinion
> > > 
> > > 
> > > Agreed, 100u of licoxide is a bit too much. Maybe 30u is much more viable?
> > 
> > 
> > Licoxide is powerfull even in 5 units. But.
> > I see that you still to want to add it, so what about to add licoxide smoke on critical state?It will turn smes actually dangerous device to work with.
> 
> Indeed! Great idea, you mean like foam that dissipates over time?


I mean mostly smoke reaction, water-like foam coming from device doesnt logicaly okay.

In other hand, smoking devices pretty common.

Also thinking of it, people would use smes as pushing stun bombs, putting things into disaster.
But will understand that a pep  whom bringing half-broken  smes to a public place, will indeed have bad intentions. Yeap.

**Comment by VelonacepsCalyxEggs** [comment]
I've tweaked the SMES again, added the foam effect. I think it acts pretty well, makes for some more robust traps you can do in engineering / solars. 
I will also do some playtesting with people on friday.

Here''s the new media:
https://youtu.be/IxvHtJKW-ME
(for some reason OBS changed the size of the SS14's window, but I think you can still see all you need.)

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Keep the explosion and the damage visualizer and remove the licoxide and the plasma, the licoxide would be cool if it was actually used for SMES maintenance/construction or something but without that feature it doesn't make much sense,  the plasma is way too dangerous no matter the amount it releases

**Review by AJCM-git — CHANGES_REQUESTED** [review]
.

**Comment by AJCM-git** [comment]
@VelonacepsCalyxEggs you coming back to this?

**Comment by VelonacepsCalyxEggs** [comment]
No, going through some troubles currently. I will continue this later. Closing it for now.

**Pull request closed without merging**
