### PR TITLE
Fixes power wire action electrocution

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR 

Fixes an issue where cutting a power wire and then mending all power wires still caused things to be electrocuted. Oops!

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Review by wrexbe — CHANGES_REQUESTED** [review]
Does not fix the problem. There are several classes that implement BaseWireAction, so the fix you have created only happens when one specific kind is mended, but it is still broken for the rest of the wires. The fix needs to be made on Wires System, not on individual wire types.

**Comment by vulppine** [comment]
yeah, each instance is meant to perform their own bookkeeping - however, if it would be better to track how many instances of a wire type is cut and store that within WiresComponent, rather than this method of individual bookkeeping, i could try to see how to approach a solution that leans itself towards that

**Comment by wrexbe** [comment]
So a possible solution is, you have this thing
```
    private void OnWiresPowered(EntityUid uid, WiresComponent component, PowerChangedEvent args)
    {
        UpdateUserInterface(uid);
        foreach (var wire in component.WiresList)
        {
            wire.Action.Update(wire);
        }
    }
    ```
If you also called wire.Action.Update on Mend, and Cut, and then did your checks on PowerWire in Update, it might work.

**Comment by vulppine** [comment]
> So a possible solution is, you have this thing
> 
> ```
>     private void OnWiresPowered(EntityUid uid, WiresComponent component, PowerChangedEvent args)
>     {
>         UpdateUserInterface(uid);
>         foreach (var wire in component.WiresList)
>         {
>             wire.Action.Update(wire);
>         }
>     }
> ```
> 
> If you also called wire.Action.Update on Mend, and Cut, and then did your checks on PowerWire in Update, it might work.


yeah, that's the solution i was thinking of, where rather than do the checks upon a wire cut/mend/pulse, instead it would use the update function already in the interface to instead update the entity's state - that way all a wire has to do is just listen for updates to ensure that the correct state is reached

**Comment by vulppine** [comment]
alright, addressed the request for changes, this should make electrocution updating a little less untied from when the wire has something done to it

**Comment by wrexbe** [comment]
Waiting for a bug fix with DoAfter cancelling putting the wires into a weird state.

**Comment by vulppine** [comment]
> Waiting for a bug fix with DoAfter cancelling putting the wires into a weird state.

do you have any reproduction steps? cancelling the doafter at the moment just removes a wire's ID from a set that blocks any interactions from reaching that wire

**Comment by wrexbe** [comment]
Reproducing this is kind of a pain
Screenshot 2022-06-28 134235

The easiest way I found to end up in this weird state is if you spam cut, and mend the two power wires for a bit, and let some do afters complete. I can't figure out a set of steps to cause the electrocution bug to happen, but maybe it'll go away if you fix this, since it's probably related to the wire cut count getting screwed up too.

**Review by mirrorcult — APPROVED** [review]

**Comment by metalgearsloth** [comment]
@wrexbe

**Comment by wrexbe** [comment]
The wire cutting do-afters are gone, and still can break it
Screenshot 2022-07-24 115115

**Comment by vulppine** [comment]
> The wire cutting do-afters are gone, and still can break it Screenshot 2022-07-24 115115

wire do-afters were removed in another PR (i just did an upstream merge on this)

however, i might've gotten the issue you were having: i added a check for if a wire is cut or not when the action is started, and spamming a single wire gave me a lot of popups about 'this wire can't be cut if it's cut/mended if it's mended'

**Review by wrexbe — APPROVED** [review]

**Pull request merged**
