### PR TITLE
Fix TC inserting into uplinks and PDAs

### LINKED ISSUE #15920: Nukies cannot place withdrawn telecrystals into their PDAs
## Description

Probably the uplink pda change pr
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by DawBla**
## About the PR

This PR fixes the TC inserting issue after the recent uplink changes. Instead of checking if the player has uplink window open, which stopped working, it unlocks the uplink when the user inputs the correct ringtone and lets them insert the TC. The nukie radio uplink and uplink implant are always unlocked. 
Resolves #15920

**Media**

https://user-images.githubusercontent.com/46636558/235329597-ad197e39-eef2-4c8e-8024-cf8564054051.mp4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Mumohan
- fix: Syndicate agents can once again deposit telecrystals into their uplinks

### CODE REVIEW

**Comment by DawBla** [comment]
If someone else wants to tackle this issue
`!_ui.SessionHasOpenUi(uid, StoreUiKey.Key, actor.PlayerSession)`
This part doesnt work and I have no clue why

**Review by crazybrain23 — APPROVED** [review]
I've tested everything locally and everything seems to work as it should.

**Comment by deltanedas** [comment]
merge now, ill change it to use locking if its lockable when i fix the ui thing on #15842

**Comment by deltanedas** [comment]
actually nah ill have to remove 99% of this if its merged before locking/unlocking

**Comment by deltanedas** [comment]
@DawBla this can be closed now

**Pull request closed without merging**
