### PR TITLE
Add xeno costume suit and head

### PR DESCRIPTION
**Pull request by Ithariel**
## About the PR 

Adds the xeno custume from tgstation

**Screenshots**

xeno-suit

**Changelog**

:cl:
- add: Added xeno costume

### CODE REVIEW

**Comment by DogZeroX** [comment]
Funny, because we literally removed it time ago, snrrrk.

**Comment by Ithariel** [comment]
> Funny, because we literally removed it time ago, snrrrk.

Uh oh. Not what i expected when i didn't find it. Is that a problem?

**Comment by DogZeroX** [comment]
It was removed for copyright for looking like Alien Franchise xenos.

**Comment by Ithariel** [comment]
> It was removed for copyright for looking like Alien Franchise xenos.

Well damn. Didn't think about that. Sad. Should i close this then?

**Comment by DogZeroX** [comment]
Pretty sure yeah unless you get a sprite that makes them look like our current xenos.

**Pull request closed without merging**
