### PR TITLE
More opportunities to implement wizards!

### PR DESCRIPTION
**Pull request by NULL882**
## About the PR

This PR is about the fact that now a scroll will appear in the game, with which you can make runes, for example, for the implementation of drawing runes to wizards or something else.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Video:
https://drive.google.com/file/d/1RtcG5IC3jsqRAMNxfhI44PqjMJCbDdYU/view?usp=sharing

**Changelog**

:cl: @NULL882
- add: A scroll of runes for the implementation of drawing!

### CODE REVIEW

**Comment by Jackrost** [comment]
On TGStation cultist can use ritual dagger to draw runes. I think scrolls needed for wizard because he doesn't use blood for runes.

**Comment by NULL882** [comment]
Well, then they will be used by wizards, in principle, my friend is already starting to do the working things of the cult.

**Comment by Jackrost** [comment]
> Well, then they will be used by wizards, in principle, my friend is already starting to do the working things of the cult.

I think we need to coordinate who is going to do a cult mode, because I already made some progress. You can look at my github branch.

**Review by mirrorcult — APPROVED** [review]
not sure it'll get used immediately but we can definitely use these for wiz events

**Pull request merged**
