### PR TITLE
Board descriptions for computers and machines

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Self explanatory. Was looking at boards for some reason and came across some TODO's. This PR does the following:

- Changed some console names into computers (all except shuttle console as ID is console too).
- Made all names lower case as we had a mixed bag of mostly PascalCase names which is not convention.
- Added descriptions to all electronics, machine and computer boards which state in their second word if it is for a machine, computer or electronics, just for added clarity.
- Changed the sprite for computers to mainboard so they differ from machine boards for that extra clarity at a glance.
- Made firealarm sprite match the airalarm for now since they're both atmos alarms. Made sense in my head, can change the firealarm to red outline if it matters.
- RE ID'd the reagentgrinder board from KitchenReagentGrinderMachineCircuitboard to ReagentGrinderMachineCircuitboard.
- Also fixed SMES construction in this PR.
- Also Also added in all missing boards to the game for computers since deconstructing some that are mapped in produced nothing making people think it was a bug.
- Also Also Also decided to add the criminal records computer while we're here so the asset is ready to be mapped for future functionality. UI and database stuff isn't my game so I'll leave that to someone else. Modified the generic sprite for it too since the current sec one was poo.

**Screenshots**

Computer boards are now:
mainboard
Instead of:
card_mod

**Changelog**

:cl:
- fix: All electronics, machine and computer boards now have updated names, descriptions and in some cases sprites.
- fix: SMES construction is now fixed.
- add: There's now computer boards for all computers on the station...some still don't do anything.

### CODE REVIEW

**Comment by Zumorica** [comment]
I don't really like the boards being called "PCBs", honestly.
And this makes it harder to tell at a glance whether a board goes in a machine frame or a computer frame

**Comment by Willhelm53** [comment]
Different colors maybe for machine/computer boards? Instead of the green?

**Comment by Peptide90** [comment]
> I don't really like the boards being called "PCBs", honestly. And this makes it harder to tell at a glance whether a board goes in a machine frame or a computer frame

How come? Before this all boards looked the same, now machine boards are the typical boards we have now and computer boards are the bigger variant so at a glance without even examining you know what it is for.

As for naming I unified them to PCB since they will ultimately be made on a printer. I can change it back to board but I'm not torn either way. Just thought we'd progress a little. The descriptions have what they are for in the first two words too. Want to go back to boards for all? Or would you prefer to have the name of what it's for in the name as well as description?

As for colours, they're usually used for specific boards e.g. red being security, high value or syndicate.

**Comment by ShadowCommander** [comment]
It doesn't matter too much to me whether it's board or PCB. Maybe some screenshots will help decide?

**Comment by Peptide90** [comment]
@ShadowCommander As requested, small gif showing them off. A selection of machine boards at the top (In entity menu they still show as [machine board], and bottom are all computer boards (different sprite now to differentiate).

Also a selection of electronics on the left which are the specific boards for things like airlocks, fire alarms, solar trackers etc.
F8OPyswhQL

**Comment by Peptide90** [comment]
Decided to just revert back to naming everything machine board and computer board. Also updated some consoles to computers for consistency.

**Comment by mirrorcult** [comment]
conflicts

**Review by mirrorcult — APPROVED** [review]

**Comment by ShadowCommander** [comment]
Does this have any problems with maps that have a ReagentGrinder since it got renamed?

**Comment by Peptide90** [comment]
> Does this have any problems with maps that have a ReagentGrinder since it got renamed?

The reagent grinder itself is still called a kitchenreagentgrinder. Probably because it looks like a mixer. But I'll have to wait till maps are merged if ya'll want it changed. There's no construction for them yet either so nothing to change there.

**Review by ShadowCommander — APPROVED** [review]

**Pull request merged**
