### PR TITLE
Makes constructibles flammable

### PR DESCRIPTION
**Pull request by Peptide90**
Small change to all constructible items that are wood, fabric or otherwise flammable to make them now catch fire and break down.

Fuel tanks now also react to fire and will explode.

Wasn't having much luck making objects flammable to burn things like trash so that's a job for another day.

All tested on localhost with no errors or issues.

### CODE REVIEW

**Comment by Zumorica** [comment]
(Also, currently I don't think we have any "on fire" sprite overlay for the things you made flammable, so you might have to get it from an SS13 codebase or get a spriter to draw one)

**Comment by Peptide90** [comment]
Ah yes forgot about that one. In my tests they all were destroyed very fast so I didn't realise. I'll take a look for that now and make the changes

**Comment by metalgearsloth** [comment]
Would having a fire shader be useful rather than requiring overlays for every sprite to be drawn maybe?

**Comment by Peptide90** [comment]
> Would having a fire shader be useful rather than requiring overlays for every sprite to be drawn maybe?

IIRC there's only one sprite for objects being on fire which we have as "fire" in the texture effects folder. Anything bigger like chairs, walls etc use the whole tile effects 1 to 3.

I was going to go with that but at first it wasn't recognising "fire" as a state (from the .JSON) and when I changed it to 1 I got an instant crash.

I'm easy though, whatever the best way is to go whether we use only a few sprites or if we go shaders. One for every item is over the top.

**Comment by Peptide90** [comment]
> 
> 
> (Also, currently I don't think we have any "on fire" sprite overlay for the things you made flammable, so you might have to get it from an SS13 codebase or get a spriter to draw one)

Added FireVisualizer to all of my changes and added a new custom sprite to cover it until we get a fire shader. This rounds out all constructibles that should burn i.e. not made out of metal or glass. Will look at doing the same with objects in future.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
firevisualizer isn't working as the default layer is being set to 0 which you'll need to fix by explicitly layering each of these.

**Comment by Peptide90** [comment]
> 
> 
> firevisualizer isn't working as the default layer is being set to 0 which you'll need to fix by explicitly layering each of these.

Not sure if how I've implemented it is right as it seems to work as intended for most things except for tables where the fire sprite goes behind the table. If you have an example of how I can specify a layer I will fix this tomorrow (as well as look to add the correct damage types and drop item ash for heat destruction). Thanks,

**Comment by metalgearsloth** [comment]
Lots of things use layers in yaml e.g. mobs, guns...

**Comment by SweptWasTaken** [comment]
Stale and very out of date. Closing.

**Pull request closed without merging**
