### PR TITLE
Fix ControlMob on already controlled mob

### LINKED ISSUE #4602: ControlMob issues when using multiple clients on debug
## Description

To replicate
- Start SS14 in Debug
- Open up a second client using runclient.bat and connect
- Right click the first client's player and select "Control Mob".

The first client's window will freeze, and when trying to move it will spam this in the server console. The freeze isn't fatal, it literally freezes everything on screen and they will only be allowed to interact with UI elements.

`[INFO] system.interaction: Invalid Coordinates: client=localhost@JoeGenero, coords=EntId=c1, X=-3.62, Y=3.65
[INFO] system.interaction: Use input validation failed`

The second client will be in control of the first clients player like normal but will not be able to use "Control Mob" as it's gone from the context menu.

I believe this process fucks up something crucial in the first clients mob because trying to equip a spear on my back spits out this in the server console and it freezes my inventory UI, clicking to rotate my character and other stuff.

`[FATL] unhandled: System.Collections.Generic.KeyNotFoundException: Entity 6092 does not have a component of type Robust.Server.GameObjects.ActorComponent`

Not sure if this is intended behavior in debug but I think at least getting your mob controlled should kick you out into a ghost.

**Screenshots**

First client on the left.
unknown

### PR DESCRIPTION
**Pull request by ShadowCommander**
## About the PR 

Change ControlMob so that it works when controlling a mob that another player is already controlling.
Fix old controller getting sent to nullspace by putting them in a ghost.

Fixes #4602

Tested by opening two clients and then using Control Mob from one to the other.

TODO

- [x] Fix new controller eye not getting set.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
This ever gonna get updated?

**Comment by Zumorica** [comment]
For the record, ActorSystem now supports kicking an exiting attached player out of an entity when attaching players to entities

**Comment by SweptWasTaken** [comment]
> 
> 
> For the record, ActorSystem now supports kicking an exiting attached player out of an entity when attaching players to entities

So this should probably be closed then.

**Comment by ShadowCommander** [comment]
Seems controller eye was fixed in some other commit on master. There's one more thing that needs to be fixed, which is the new controller can't use verbs for some reason.

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
