### PR TITLE
Switched CEV-Eris Closet Sprites with TG Closet Sprites

### PR DESCRIPTION
**Pull request by SweptWasTaken**
All the other things are me moving some decoration objects into some new folders.

### CODE REVIEW

**Comment by PJB3005** [comment]
I personally prefer the CEV Eris sprites here.

Really, if we're gonna merge something like this I think we're gonna need a clear team wide agreement which codebase to follow for spritework.

**Comment by SweptWasTaken** [comment]
The CEV-Eris sprites are still present in the textures folder. I just think the TG station sprites look much better than the CEV-Eris ones. I could always switch it back if its needed, and if I do, i'll convert the rest of the CEV-Eris sprites to .rsi.

**Comment by PJB3005** [comment]
Yeah I'm definitely not fond of changing the closet sprites and re organizing textures in the same PR.

**Comment by SweptWasTaken** [comment]
The "reorganization" were only two decorative files that I put in in the first place.

**Pull request closed without merging**
