### PR TITLE
Added a research for easier creation of advanced meds.

### PR DESCRIPTION
**Pull request by magmodius**
## About the PR
Gives science one new tier 3 biochemical research, allowing medical to create advanced meds (sutures, regenerative mesh) from the medical techfab.

## Why / Balance
Made to give the biochemical tree some form of actual consideration against the other techs. Nothing else in the tree is currently even remotely worth researching, especially now with the limited chems change. This should at least make biochem's T3s somewhat desired.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Science now has one new tier 3 biochemical tech. It adds a medical techfab recipe for regenerative meshes and medicated sutures.

### CODE REVIEW

**Comment by magmodius** [comment]
unsure how to fix the RSI error(s), as i am but a humble YML rat. some help/advice would be appreciated.

**Comment by magmodius** [comment]
actually, considering it a bit, i think i was way too generous with the construction amount for the advanced meds. they should probably be around 3 sheets of each material per med. that way a full stack of each mat would equal one stack of advanced meds.

**Comment by Nimfar11** [comment]
This PR is absolutely terrible.

**Comment by Kadeo64** [comment]
biochemistry needs something good because bluespace beakers are absolute hot dogshit right now but I don't think medical techfab is a good way to do it. From what i've seen of the medical techfab, medical supplies are absurdly cheap resource wise, so giving science the ability to mass produce bruise packs/ointment/sutures might have unintended effects on balance

**Comment by deltanedas** [comment]
pro idea infinite chem machine as biochem t3 :trollface:

**Comment by EmoGarbage404** [comment]
1. Putting a medical techfab inside of science defeats the point of having it. Its meant to have items that sci can't usually acquire.
2. The recipes for the advanced meds are absurdly cheap considering the cost to make them conventionally. You are basically skipping the extra resource and machinery to produce at the expense of the most common in game resources.

I dont think im opposed to adding the advanced meds but they could easily be tier 1 or tier 2 with balanced prices. The medfab really doesnt need to be here, though.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
^comment above

**Comment by Anzarot121** [comment]
Salvage literally can obtain medfab in the first minute of the round from their magnet.

**Comment by Kadeo64** [comment]
> pro idea infinite chem machine as biochem t3 :trollface:

part of bluespace chemistry :trollface:

**Comment by magmodius** [comment]
> 1. Putting a medical techfab inside of science defeats the point of having it. Its meant to have items that sci can't usually acquire.
> 2. The recipes for the advanced meds are absurdly cheap considering the cost to make them conventionally. You are basically skipping the extra resource and machinery to produce at the expense of the most common in game resources.
> 
> I dont think im opposed to adding the advanced meds but they could easily be tier 1 or tier 2 with balanced prices. The medfab really doesnt need to be here, though.

will remove the medfab shortly, but is there any ideas on how to balance the med prices? i already increased it so a stack of two different mats would only equal a single stack of the respective advanced med. is there more i should do? any advanced mats i should be throwing in, like plasma for the suture? 
i also would like to say that i want to keep the other recipes for the advanced chems relevant, which is why i made this a T3. it ensures that science will not simply always research biochem for this one specific thing, though that obviously requires that the med recipe be balanced enough for med to not immediately mass produce them.

**Comment by jjjlogs** [comment]
With this price in techfab it's cheaper to just buy emergency advanced kits in cargo than to buy mats for techfab. Do not forget that tech also needs to be researched.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
If you change entity IDs you need to add migrations or it breaks maps.

**Comment by magmodius** [comment]
> If you change entity IDs you need to add migrations or it breaks maps.

ah, right. i forgot to close this. it seems heavily unpopular even in this state and honestly at this point i think biochem needs a full rework instead of a bandaid fix like this, and that's something that i simply cannot do with my current knowledge. apologies for the time waste.

**Comment by K-Dynamic** [comment]
I still like the idea of printing advanced meds, probably requiring a dedicated researchable machine that would partly automate their recipe (i.e. dedicated chem measurement and microwaving)

**Comment by magmodius** [comment]
> I still like the idea of printing advanced meds, probably requiring a dedicated researchable machine that would partly automate their recipe (i.e. dedicated chem measurement and microwaving)

that would be cool. maybe if i ever get into _real_ coding for the game. but alas.

**Pull request closed without merging**
