### PR TITLE
Contextual menu item for pouring liquids into containers

### PR DESCRIPTION
**Pull request by Arteben**
## About the PR
Added a new component that allows pouring liquids, for example, using a bucket to refill a water tank. This was done to introduce barrels that can be used both for drawing water and refilling these containers.

## Technical details

Added a simple server component. This code is written using DrainComponent code as an example.
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

It change maxTransferAmount(250) in prototype bucket.yml 

**Changelog**

:cl:
- add: new right menu item allowing to pour containers

### CODE REVIEW

**Comment by lzk228** [comment]
YEAHHH LESSGOO!!🥳

**Comment by deltanedas** [comment]
Pour into the water tank (uppercase Pour lowercase the)

**Comment by NancokPS2** [comment]
In SS13 you could switch between pouring and extracting.  
Would that be better than having to go into the context menu for each attempt?

**Comment by EmoGarbage404** [comment]
does this really require a new component? This just seems like an extension of SolutionTransferComponent

**Comment by mirrorcult** [comment]
yeah this is basically identical to solution transfer?

**Comment by Arteben** [comment]
> yeah this is basically identical to solution transfer?

Transfer Amount allow only transform OR pouring solutions, this isn't allow these both actions together. I want to allow these actions together, a clicks for one and context menu option for second.

**Comment by Arteben** [comment]
> In SS13 you could switch between pouring and extracting. Would that be better than having to go into the context menu for each attempt?

make like the system from syringes and make it more general. I don't know, this change is more global and complex, more harder. I don't want to make global changes, honestly.

**Comment by mirrorcult** [comment]
> > yeah this is basically identical to solution transfer?
> 
> Transfer Amount allow only transform OR pouring solutions, this isn't allow these both actions together. I want to allow these actions together, a clicks for one and context menu option for second.

then just modify solution transfer instead of making a new component

**Pull request closed without merging**
