### PR TITLE
let AI be ion stormed

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
title

## Why / Balance
more fun gameplay and you have to be somewhat wary of the AI now

you can also reset the AI back to crewsimov or whatever using the law console

## Media
untested

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: AI may now be ion stormed.

### CODE REVIEW

**Comment by UbaserB** [comment]
funny

**Comment by LaOubliette** [comment]
Sovl

**Comment by ScarKy0** [comment]
I was coming up with a system for ion storm AI
law boards currently make ion storms trivial because they can just be re-inserted to reset the laws back to what they were

**Comment by Ilya246** [comment]
> I was coming up with a system for ion storm AI law boards currently make ion storms trivial because they can just be re-inserted to reset the laws back to what they were

yes but i think it's okay because you have to 1) know AI is ioned (hard) 2) get to AI core 3) get the law board and get it to an upload computer

**Comment by slarticodefast** [comment]
Make the law boards ion storm targets as well so you have to pick the best one from a corrupted set :trollface:

**Comment by ScarKy0** [comment]
> Make the law boards ion storm targets as well so you have to pick the best one from a corrupted set :trollface:

Me when all 12 law boards get ion stormed while literally laying on the ground

**Comment by Kadeo64** [comment]
ai malf

**Comment by vladkaron14R** [comment]
It's an interesting idea, but we need to make sure that the laws change like those of AI, as well as make cyborgs linked to AI

**Comment by slarticodefast** [comment]
Hey, I brought this up for dicussion with the maintainers and admins and due to a huge influx of similar PRs we decided to freeze AI law changes until some basic requirements for AI are implemented. See #31924 for more details. Once these are addressed the mentioned PRs will be re-evalutated. Thank you for your contribution.

**Pull request closed without merging**
