### PR TITLE
Adds Sechud to lockers and sec techfab

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- add: Added the SecHud to lockers, sec vendor, secfab.
- fix: Security will now receive the correct glasses box with their security supplies from cargo.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
I forgot to give one to the head of security

**Comment by JoeHammad1844** [comment]
give secglasses sechud like ss13 :trollface:

**Comment by deltanedas** [comment]
then theres no reason to have sechud just remove it
it would be inferior in every way

**Comment by JoeHammad1844** [comment]
in ss13 you could craft sechud glasses with sunglasses and sechud

**Comment by JoeHammad1844** [comment]
maybe ill try to make secglasses craftable and have sechud, wheres the crafting code?

**Pull request merged**
