### PR TITLE
Adds Bingus and Space Cat spawners

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
## About the PR
- Adds spawners for Bingus and space cats
- Adds Bingus to the Cat Spawner
- Adds rare chance(5%) for generic cat spawner to spawn space cat

**Media**

- [ x ] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

**Changelog**

:cl: Velcroboy
- add: Added Bingus and Space Cat spawners!

### CODE REVIEW

**Comment by ficcialfaint** [comment]
This is not how you add a CL. Do not break the PR description template.

**Comment by deltanedas** [comment]
why would players care

**Comment by ChilbroBaggins** [comment]
> This is not how you add a CL. Do not break the PR description template.

Do I need the CL? I guess I didn't think this was a big change. More for mappers to use.

**Comment by ChilbroBaggins** [comment]
> why would players care

I've had specific requests for both. Players like the variety and to RP with their cats. It's fun.

**Comment by ficcialfaint** [comment]
> > This is not how you add a CL. Do not break the PR description template.
> 
> Do I need the CL? I guess I didn't think this was a big change. More for mappers to use.

wat? your PR dead is literally only the CL

**Comment by ChilbroBaggins** [comment]
> > > This is not how you add a CL. Do not break the PR description template.
> > 
> > 
> > Do I need the CL? I guess I didn't think this was a big change. More for mappers to use.
> 
> wat? your PR desc is literally only the CL

Sorry, thought you meant the automated CL that converts it to logs/posts to Discord. What else do you need? I'm looking for the original template.

**Comment by ficcialfaint** [comment]
> > > > This is not how you add a CL. Do not break the PR description template.
> > > 
> > > 
> > > Do I need the CL? I guess I didn't think this was a big change. More for mappers to use.
> > 
> > 
> > wat? your PR desc is literally only the CL
> 
> Sorry, thought you meant the automated CL that converts it to logs/posts to Discord. What else do you need? I'm looking for the original template.

the PR template can be found [here](https://github.com/space-wizards/space-station-14/blob/e584b9a6ca59483f7b923a657d2138d87e3b7fe6/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by ChilbroBaggins** [comment]
Updated

**Comment by deltanedas** [comment]
im saying that the original changelog was not user facing, not that people wouldnt love bingus

**Comment by ChilbroBaggins** [comment]
> im saying that the original changelog was not user facing, not that people wouldnt love bingus

Oh, haha, I get it

**Pull request merged**
