### PR TITLE
Anomalies can't appear near gas miners, arrival docks and cryosleep unit

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Title

## Why / Balance
These three points are extremely important things for the round, so I would protect them from anomalies. And it's better to do this automatically for all maps at once than to manually zone on mapping.

**Changelog**
no cl! 
NO CL! 
**NO CL!**

### CODE REVIEW

**Comment by UbaserB** [comment]
> I approve of this, but shouldn't anti-anomaly zones be map-specific and explicitly mapped, rather that attached to entities which may or may not be used for its intended purposes (either by mappers or by players)?

sounds annoying i dont want to have to map that when this alternative exists

**Comment by GoodWheatley** [comment]
Anomalies showing up in the gas miner is funny

**Comment by Kadeo64** [comment]
> Anomalies showing up in the gas miner is funny

"A device designed to aid in the locating of anomalies. Did you check the gas miners?"

**Comment by metalgearsloth** [comment]
Areas are not a mapping crutch wanted and this is areas in a trenchcoat.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Mapping crutches are not wanted upstream and I don't really know why emisse and emo were okay with the originals being added in https://github.com/space-wizards/space-station-14/pull/23187

**Comment by deltanedas** [comment]
i dont see whats wrong with a mapper putting an anti anomaly zone at arrivals to make sure people dont immediately die

**Comment by metalgearsloth** [comment]
> i dont see whats wrong with a mapper putting an anti anomaly zone at arrivals to make sure people dont immediately die

Since I started we have been consistent on not wanting areas ported from 13.

If you want this make it a physical entity, not an area.

**Comment by metalgearsloth** [comment]
Additionally by substantially bumping anti-anomaly areas on station the expensive check for spawning them becomes exponentially worse because it has to iterate every single anti-anomaly for every spawn chance and the logic would need to be rewritten.

**Comment by deltanedas** [comment]
then pros will put the anti anomaly physical entity everywhere which will very slightly degrade performance and make anom farming trivial, have a dedicated place on the station where you spawn anoms

this would also make gorilla less useful since instead of moving anom out of a dangerous area, prevent it spawning there entirely

**Comment by metalgearsloth** [comment]
I never said we need 50 of them nor that they should even be replenishable.

**Comment by deltanedas** [comment]
even if theres only 1 and you cant replenish it then you could still move it away from arrivals which is bad

and if it cant be moved or destroyed its just a marker thats visible to players

**Comment by metalgearsloth** [comment]
> even if theres only 1 and you cant replenish it then you could still move it away from arrivals which is bad
> 
> and if it cant be moved or destroyed its just a marker thats visible to players

As opposed to:

A) A marker that only coders know about.
B) A re-implementation of areas.
C) The only mapping marker in the game that doesn't correspond to an entity besides spawn points.

**Comment by EmoGarbage404** [comment]
mfw players are expected to set up local servers so that they can learn the unknowable quirks of internal randomized system that have 0 telegraphing.

**Comment by deltanedas** [comment]
add note in guidebook that anomalies cant spawn in arrivals to not degrade peoples round immediately :trollface:

**Comment by LankLTE** [comment]
> then pros will put the anti anomaly physical entity everywhere which will very slightly degrade performance and make anom farming trivial

If Sci has enough time to cover literally the entire station in anti-anomaly devices they probably deserve the easy anom farming tbh

**Pull request closed without merging**
