### PR TITLE
Addition of medical hypospray.

### PR DESCRIPTION
**Pull request by NuarBoyNew**
## About the PR
The addition of medical hypospray, its third tier study technology.

## Why / Balance
To speed up the medical staff towards the end of the round.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
🆑
- add: medical hypospray
- add: RefillableMedipen technology in third tier

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
CL be broken you need 🆑

**Comment by NuarBoyNew** [comment]
> CL be broken you need 🆑

Thank, I fix it.

**Comment by Cojoke-dot** [comment]
hm... I don't think this would be useful at all... a hypo with only 5u of anything is almost pointless. I could not see any point of this for either offense or healing due to the limit on the amount of fluid. It would be more effective to use a syringe in a lot of situations due to not having to refill it to get the 10-15u normal needed for healing.

If this is meant to work more as an epi-pen, make it so you can hold 15u in it and can be filled from the chem master, like bottles. The name is also not great; I was thinking that it would be a printable hypo rather than having the purpose of being a refillable epi-pen.

**Comment by Hmeister-real** [comment]
i'd suggest just changing the sprite to the Brigmed Minihypos from #15319 that are currently unused

>P.S. Frontier station has a PR of the exact same thing, and also using the Brigmedic Minihypo sprite and has balancing like a 2.5 second cooldown, https://github.com/new-frontiers-14/frontier-station-14/pull/1038

**Comment by CatMagic1** [comment]
is that a gun?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Make it whitelisted to medicines and it's probably fine + you can maybe drop it a tier, then the CMO one is still at least special.

**Comment by Plykiya** [comment]
I would have no clue what I'm looking at based on the sprite

**Comment by metalgearsloth** [comment]
Re-open if you come back to it.

**Comment by Aisu9** [comment]
as an upgrade to syringes, it doesn't deserve to be a T2 biomedical, considering biomedical research are not picked in the first place(AND are limited to 5u injection where syringes are perfectly capable of injecting up to their entire payload)

**Pull request closed without merging**
