### PR TITLE
[Add] Hairflower to authodrobe

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added hairflower to authodrobe!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
can't you just craft it

**Comment by lapatison** [comment]
> can't you just craft it

Hairflower cannot be crafted, only FlowerCrown

**Comment by lzk228** [comment]
then it would be good to craft hairflower maybe

**Comment by Partmedia** [comment]
This PR is only adding one to the AutoDrobe. Even if it becomes possible to craft it in the future, I would still support making one available.

**Pull request merged**
