### PR TITLE
Kangaroos, boxer improvements, boxing bell and hamlet updates.

### PR DESCRIPTION
**Pull request by brainfood1183**
https://user-images.githubusercontent.com/113240905/233386975-533cccd8-eb97-487e-b87b-587aeafa4360.mp4

image

- Resprites kangaroo and space-kangaroo
- Added space kangaroo salvage and ordinary spawners.
- Removed the boxing kangaroo sprites, now kangaroos can be equipped with boxing gloves.
- Breath masks and oxygen tanks for kangaroos and hamlet
- Fixed a pixel in hamlets sprite.
- Added new bounce sound effect for kangaroo movement and kangaroo grunt for kangaroo scream.
- Added a kangaroo livestock crate that can be ordered through cargo.
- Added a kangaroo pet spawner (willow).
- Added a new wallmounted boxing bell, clicking on the bell makes the boxing ding ding sound.
- Boxer now spawns with the championship belt and shoes.
- Boxer now has maintenance access.

- [x] I have added screenshots and or videos.

**Changelog**

:cl:
- Added - Kangaroos in both ordinary and space forms.
- Added - new pet, Willow the boxing kangaroo.
- Added - Cargo may order a kangaroo livestock crate.
- Changed - boxer role now has maints access and comes with shoes and a championship belt.
- Added - Hamlet can now wear breath mask and oxygen tanks.
- Added - Boxing bell, Ding Ding!

### CODE REVIEW

**Comment by DogZeroX** [comment]
Better make a spawner of skippies that come with the gloves equipped

**Comment by brainfood1183** [comment]
> Better make a spawner of skippies that come with the gloves equipped

the pet comes with them equipped, rest dont but u can equip them

**Comment by deltanedas** [comment]
space hampter instamerge

**Comment by DogZeroX** [comment]
> > Better make a spawner of skippies that come with the gloves equipped
> 
> the pet comes with them equipped, rest dont but u can equip them. I searched to see if the boxing kangaroo was in use anywhere and it didnt look like it

If I want boxing kangaroo swarm, I don't want to equip all of them manually.

**Comment by brainfood1183** [comment]
> > > Better make a spawner of skippies that come with the gloves equipped
> > 
> > 
> > the pet comes with them equipped, rest dont but u can equip them. I searched to see if the boxing kangaroo was in use anywhere and it didnt look like it
> 
> If I want boxing kangaroo swarm, I don't want to equip all of them manually.

good point, i will make a spawner just for a kangaroo with boxing gloves

**Comment by brainfood1183** [comment]
> 

do you want them to be agressive? i assume so?

**Pull request merged**
