### PR TITLE
Balanced ChemVend Stock

### PR DESCRIPTION
**Pull request by wafehling**
## About the PR
I rebalanced what comes in the ChemVend and the ChemVend refills to be closer to actual usage levels by the average chemist

## Why / Balance
You do not need as much Radium as you do carbon. It's silly to get the same amounts of every chem when some are used for almost everything, and some have basically no use. 

I'm not a Chemist main or anything so if some of these numbers look off to you, feel free to tweak them. But this is based on several shifts of my chem experience

## Technical details
Just changed the numbers in a .yml, nothing fancy at all

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None, it's just a quantity swap.

**Changelog**
Rebalanced ChemVend stock for more accurate usage levels

### CODE REVIEW

**Comment by UbaserB** [comment]
iirc sugar is used a lot

**Comment by IProduceWidgets** [comment]
My initial reaction is maintaining this will probably be annoying as new reagent/reactions get added. 

Another thought is that this also means that the restock box will give quantities in line with this change iirc. which might be undesirable but meh.

**Comment by wafehling** [comment]
> iirc sugar is used a lot
I agree, +1'd it



> My initial reaction is maintaining this will probably be annoying as new reagent/reactions get added.
> 
> Another thought is that this also means that the restock box will give quantities in line with this change iirc. which might be undesirable but meh.

Haven't seen new reagents in a long while, and this balance is definitely needed, should be easy to tweak if needed once we've got things close.

**Comment by MONKEYGAMING123** [comment]
That is, roughly speaking, there are more of some substances, and less of some now?  There’s no point about radium, yes, chemists don’t need it in part, but botanists need it for mutagen and phalangimine.  I have explained what radium is for now because it is indicated in the example, I have not seen the numbers yet.

**Pull request merged**
