### PR TITLE
move revolver to detective inventory and more

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Moves the detectives revolver from their locker to their holster. Removed the pistol mag for a rubber speedloader and lethal speedloader.
This should bring them more in line with standard security as a side result, but for the most part it was just to remove the redundant pistol mag.

 Moved print analyzer and paper from their pockets to their bag while I had the opportunity. 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- tweak: The Detective's gun has been moved to their holster from their cabinet. It comes with one speedloader each of the standard rubber and lethal bullets of officers.
- tweak: The Detective's scanner and pad were moved to their backpack from their pockets.
- remove: Detective no longer spawns with a pistol magazine.

### CODE REVIEW

**Comment by Verslebas** [comment]
It seems to me that this change is problematic, there are cases when an ordinary officer becomes detectives due to their absence, and now it turns out that the officer will not be able to have a revolver

**Comment by QuietlyWhisper** [comment]
> It seems to me that this change is problematic, there are cases when an ordinary officer becomes detectives due to their absence, and now it turns out that the officer will not be able to have a revolver

All officers spawn with a pistol now whereas the detective spawns with... nothing currently actually. Just their prints kit in their pockets unfortunately

**Comment by Verslebas** [comment]
Yes, but they still has a revolver in their closet, a revolver is still a special attribute of a detective, a cmo will not spawn with a hypospray in a backpack, and a bartender with a shotgun, too

**Comment by Verslebas** [comment]
Because these are special attributes of their profession and if there is no main person in this profession, another person will be able to take a place and take possession of the attributes

**Comment by QuietlyWhisper** [comment]
The gun is not any more a key item of the detective as a pistol is for secoffs, I don't believe giving the detective his gun on roundstart takes away from anything a secoff already has or can obtain.

Argueably, the print kit and gloves are they key items of that role, not the weapon.

**Comment by EmoGarbage404** [comment]
this is neato and det can always pick up a secbelt in a locker

**Pull request merged**
