### PR TITLE
Change Vend Sound to TG

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

makes the vend sound like tg's (tg pr says its under cc0 1.0 and doesnt require attribution)

## Why / Balance

tg one is way more satisfying

## Media

https://github.com/space-wizards/space-station-14/assets/79580518/f9fd8acf-a26d-407e-8cb9-e6ec70e7d2fe

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: Changed the vending machine sound to tg's one

### CODE REVIEW

**Comment by deltanedas** [comment]
the sounds cut off early i dont like it

**Comment by potato1234x** [comment]
the current ones cut off too late

**Comment by crazybrain23** [comment]
> the sounds cut off early i dont like it

I agree, it sounds incomplete.

**Comment by UbaserB** [comment]
> the sounds cut off early i dont like it

it sounds like that because the sound is too short. Simply *stretch* the time a bit longer, doesnt even have to be much and it should immediately be a lot better

**Comment by potato1234x** [comment]
made it slower

**Comment by Keikiru** [comment]
I don't like how harsh the noise is. It's awfully sharp and hurts my ears.

Can you try muffling it a little?

**Review by TheShuEd — CHANGES_REQUESTED** [review]
just because you slowed him down didn't make him better. It still cuts off abruptly at the end.
fix the audio clipping, please.

**Comment by potato1234x** [comment]
I cant just construct the rest of the sound out of thin air...

**Comment by potato1234x** [comment]
i guess we close this :despair:

**Pull request closed without merging**
