### PR TITLE
fix: Include the officer name in all criminal records status changes

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Includes the name of the officer who sets a "prisoner" to no longer wanted.

edit:
Includes the name of the officer in every status change.

## Why / Balance

Every other status changes includes the officer name, why is this one different.
WHO THE FUCK KEEPS DELETING THE RECORDS AND SETTING THEM TO NONE

edit:
Wasn't just that one.

## Technical details

I am not a liberal arts major

## Media

outdated:
https://github.com/space-wizards/space-station-14/assets/103440971/ff3e2f98-2f15-4bfa-a162-f6e4f6d85028

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
I noticed that there are multiple other's that don't include the officers name. Going to change those as well

**Comment by Brandon-Huu** [comment]
There probably needs to be an announcement for when someone adds a new criminal record.

And a announcement when someone deletes a criminal record.

**Review by Veritius — CHANGES_REQUESTED** [review]
Shouldn't it all be `{$officer}` rather than `{$officer_name}` to fit the rest of the translations?

**Comment by Brandon-Huu** [comment]
> Shouldn't it all be `{$officer}` rather than `{$officer_name}` to fit the rest of the translations?

You are correct.

Fixed

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Im pretty sure these strings are never used so what does this change? probably better to just remove them

**Comment by Cojoke-dot** [comment]
Is the message for none originally "not wanted"? Maybe that should be changed to "removed their status" or something similar to reduce confusion. Technical "not wanted" refers to everything but the wanted status.

**Comment by Brandon-Huu** [comment]
> Is the message for none originally "not wanted"? Maybe that should be changed to "removed their status" or something similar to reduce confusion. Technical "not wanted" refers to everything but the wanted status.

"{$name} has had their status completely removed by {$officer}."

Would this be better?

**Comment by Brandon-Huu** [comment]
Wait changes are being awaited?

**Comment by Brandon-Huu** [comment]
> Im pretty sure these strings are never used so what does this change? probably better to just remove them

What are you talking about?

**Review by AJCM-git — APPROVED** [review]

**Comment by AJCM-git** [comment]
> > Im pretty sure these strings are never used so what does this change? probably better to just remove them
> 
> What strings? Can you be more specific?

nvm forgot criminal records do something very cursed to get some of it's strings so i missed them when searching the repo, my bad

**Pull request merged**
