### PR TITLE
Adds some extra toys to the arcade machine

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR 

Adds some extra toys to the arcade machine, including:
- Plushies
- Sports balls
- Foam dart crossbow/cap gun (and ammo!)
- ~~Toy singularity~~
- Toy esword (similar to SS13, where it comes in one color and does zero damage)

**Changelog**

:cl:
- add: FunTime Arcade Solutions™ has outfitted NanoTrasen stations with a new supply of arcade toys! Come spend your free time at the arcade machines for exciting, fun objects!

### CODE REVIEW

**Comment by Snowyypanda** [comment]
YES FINALLY CAPGUN AMMO THANK YOU THANK YOU also nice we got toy eswords now

**Comment by mirrorcult** [comment]
missing tag prototype for `CartridgeDart`

**Comment by mirrorcult** [comment]
also IIRC the toy singuloth was not added to this intentionally, because the distortion effect is overly distracting

**Comment by vulppine** [comment]
> missing tag prototype for `CartridgeDart`

in progress with changing the dart a bit at the moment, will add on the singulo removal (very sad) once i get some intended behavior working

**Comment by vulppine** [comment]
there, got it working (thanks sloth 🦊)

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
