### PR TITLE
I LOVE LEAN (Makes Lean Craftable and gives it wacky effects)

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
Makes Lean Craftable and gives it wacky effects
also fixes a typo
**Changelog**
:cl: Daemon
- tweak: Lean can now be made and has effects.

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
DNM quite just yet, still wanna mess around with balance

**Comment by scaly-chimp** [comment]
Lean so wacky it might break pvs.
@metalgearsloth can pvs handle 2x movespeed?
Even ignoring the balance of making a 2 reagent chem better than meth.

**Comment by ZeroDayDaemon** [comment]
> Lean so wacky it might break pvs.
> @metalgearsloth can pvs handle 2x movespeed?

Ehhh, It's wacky man, but if speed needs to he toned down then so be it.

> Even ignoring the balance of making a 2 reagent chem better than meth.

It also kills you very fast, and it's lean, it's wayyyyy more powerful than meth obviously

**Comment by metalgearsloth** [comment]
> Lean so wacky it might break pvs. @metalgearsloth can pvs handle 2x movespeed? Even ignoring the balance of making a 2 reagent chem better than meth.

no. 1.5 probably needs checking as ghosts currently have streaming issues.

> > Lean so wacky it might break pvs.
> > @metalgearsloth can pvs handle 2x movespeed?
> 
> Ehhh, It's wacky man, but if speed needs to he toned down then so be it.
> 
> > Even ignoring the balance of making a 2 reagent chem better than meth.
> 
> It also kills you very fast, and it's lean, it's wayyyyy more powerful than meth obviously

Forcefeeding is still instantaneous so an easy poison shouldn't be strong, especially when it's going to be crafted every round as a meme item. There's a reason meth is the way it is.

**Comment by ZeroDayDaemon** [comment]
> > Lean so wacky it might break pvs. @metalgearsloth can pvs handle 2x movespeed? Even ignoring the balance of making a 2 reagent chem better than meth.
> 
> no. 1.5 probably needs checking as ghosts currently have streaming issues.
> 
> > > Lean so wacky it might break pvs.
> > > @metalgearsloth can pvs handle 2x movespeed?
> > 
> > 
> > Ehhh, It's wacky man, but if speed needs to he toned down then so be it.
> > > Even ignoring the balance of making a 2 reagent chem better than meth.
> > 
> > 
> > It also kills you very fast, and it's lean, it's wayyyyy more powerful than meth obviously
> 
> Forcefeeding is still instantaneous so an easy poison shouldn't be strong, especially when it's going to be crafted every round as a meme item. There's a reason meth is the way it is.

okay, so more nerfing?

**Comment by metalgearsloth** [comment]
Need to check what meth is like because if it's just stronger meth you may as well remove meth.

**Comment by scaly-chimp** [comment]
Rn I think it's stronger, easier to make meth with a low electrocution chance.

**Comment by ZeroDayDaemon** [comment]
this looks better as a meme drink yeah? more shock, less poison since that can be forcefed, and much less speed

**Comment by ZeroDayDaemon** [comment]
alright, ready for review

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
