### PR TITLE
let the fireaxe (not the fire axe) pry plating

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

the fireaxe (the atmos one) can pry plating again
the fire axe (the nukie one) does not have this ability
## Why / Balance

Gives the atmos fireaxe one of its primary uses back. Engineers still have to use an RCD because they're undeserving of the holy axe :trollface:
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/20659419/486a3be4-236a-4c5c-a89d-c62a70aef816

## Breaking changes

**Changelog**

🆑 
- tweak: The atmospherics axe can pry plating again.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
I feel this is redundant because atmos techs can also get RCDs

**Comment by mirrorcult** [comment]
no

**Comment by K-Dynamic** [comment]
> no

Can you explain why for new people, like axes having infinite prying potential compared to RCDs?

**Comment by mirrorcult** [comment]
#24388

**Comment by MACMAN2003** [comment]
> I feel this is redundant because atmos techs can also get RCDs

the RCD doesn't return a steel tile when you use it


> no

why?

**Comment by mirrorcult** [comment]
it was removed for a reason and none of the reasons it was removed have changed

**Comment by mirrorcult** [comment]
should not have ever been added to begin with

**Pull request closed without merging**
