### PR TITLE
Fix windows not being able to be placed next to eachother

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

#18074 but better

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Windows can go next to eachother

### CODE REVIEW

**Review by EmoGarbage404 — APPROVED** [review]
:trollface:

**Comment by notquitehadouken** [comment]
pr merge speedrun?

**Comment by metalgearsloth** [comment]
Please don't use meme PR names because we have to rename it.

**Comment by Slava0135** [comment]
i don't think there is a problem with window placement

**Comment by BasedUser** [comment]
> i don't think there is a problem with window placement

try placing more than 3 windows in a line, or in atmos, breaking a window to the gas miners and replacing it

**Comment by Slava0135** [comment]
i tested it on master and it works

**Comment by Flareguy** [comment]
Does this fix #14424?

**Comment by Slava0135** [comment]
like i already reverted change that broke window placement before #17815

**Comment by deltanedas** [comment]
that didnt fix it
i have had window placement be fucky several times

**Comment by notquitehadouken** [comment]
> Please don't use meme PR names because we have to rename it.

new name 👍

**Pull request merged**
