### PR TITLE
Creating quran

### PR DESCRIPTION
**Pull request by voko421**
## About the PR
Add quran in game

## Why / Balance
I saw quran in textures and wanna to add it in game

## Requirements
I haven't finished making the quran and I need help, I'm a beginner prototyper. Now the quran has not been completely added to the game, it still needs to be added to the priest's closet/inventory, I really need help and I just want to show what I could do. it's maybe mistake in code, i checked only prototype and sprites

## Breaking changes
 Adding quran in the game(not finished)

:cl:
- add: Added quran

### CODE REVIEW

**Comment by voko421** [comment]
Maybe it didn't need to quran.ftl

**Comment by lzk228** [comment]
#27400 
please read this pr

**Comment by Uhboer** [comment]
билдецкий не для тебя, спрайты не добавил, овощь

**Comment by voko421** [comment]
> билдецкий не для тебя, спрайты не добавил, овощь

Овощ спрайты есть

**Comment by voko421** [comment]
> билдецкий не для тебя, спрайты не добавил, овощь

Овощ спрайты давно добавили

**Comment by voko421** [comment]
> #27400 please read this pr


I know that they added a Koran sprite, the path to the RSI of this sprite is indicated in the prototype

**Comment by slarticodefast** [comment]
>> https://github.com/space-wizards/space-station-14/pull/27400 please read this pr

> I know that they added a Koran sprite, the path to the RSI of this sprite is indicated in the prototype

They meant the design doc linked in the PR. The idea in there was not to make it a separate item, but to make the book item customizable using a menu and giving it a slightly different effect when used.

**Comment by superjj18** [comment]
We could do the tg thing where the Bible has a radial menu to select which sprite you want

**Comment by voko421** [comment]
they really need mechanics

**Comment by Terraspark4941** [comment]
> We could do the tg thing where the Bible has a radial menu to select which sprite you want

basically exactly what I wanted to achieve (i made the sprite and design doc)
however the mechanics have not been implemented as I wanted; in short:

> ...Quran, will be implemented with a different AoE healing mechanic to boot.

**Pull request closed without merging**
