### PR TITLE
Disposable Turrets for all (except nukies)

### PR DESCRIPTION
**Pull request by Interrobang01**
## About the PR

This PR removes the job restrictions from the Disposable Turret. It also moves it to the Weapons category, and puts Nuclear Operatives on the blacklist to comply with the original PR's demands.

Justification for job restriction removal:
All the other job-exclusive items are either exclusive because it fits thematically (holy hand grenade, fake capgun, necronomicon, explosive banana, potato... syndicate sponge?), or the item needs the job either mechanically or to not look suspicious (rigged boxing gloves, chimp ammo, gatfruit, proximity mine). The turret's engi/atmos/sci restriction fits neither of those. Thus, I ask "Why?".

**Media**

(no screenshot needed for now)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The Syndicate Disposable Turret is now approved for use by all syndicate agents (with the exception of nuclear operatives), instead of those from a select few jobs.

### CODE REVIEW

**Comment by Arendian** [comment]
I think them being job restricted to these roles is fine since they are all related to engineering complicated machinery, and in ss13 they are restriced to engineers for the TF2 reference.
My headcanon is that job specific items are things the agent prepared personally before he went on his mission, with the TC cost being the price of the syndicate bluespacing it to them.

**Comment by Interrobang01** [comment]
> I think them being job restricted to these roles...

I mean, the powersink is way more engineer-ey than the turret, and it's not joblocked. As is, arguably, the c4, the EMP-nade, the emag, the radio jammer, the jaws of life...

Also, the turret is such a unique item that it could encourage playing engi/sci just to be able to use it, and that's no good.

The TF2 reference is almost a good point, but it could still be done in a non-job-restriction way. Give engineers a 1-tc discount or something.

**Comment by Interrobang01** [comment]
Gonna change this PR's name and description a bit

**Comment by deltanedas** [comment]
diff got nuked

**Comment by Interrobang01** [comment]
i'm going to try and fix this now

**Comment by metalgearsloth** [comment]
I don't even play titanfall 2

**Pull request merged**
