### PR TITLE
add syndicate hud to nukeops uplink

### PR DESCRIPTION
**Pull request by takemysoult**
## About the PR

Added syndicate hud to nukeops uplink
## Why / Balance

Since there are only 7 lockers at the outpost and the agent shows up with a medical hud, you can't buy more than 6 reinforcements. Adding a syndicate hud to an uplink allows you to implement strategies with a large number of reinforcements
## Technical details

added the syndicate visor to the nukeops uplink
## Media

[X]
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
There were no breaking changes.

**Changelog**

:cl:
- tweak: Changed uplink catalog - add syndicate hud to nukeops uplink

### CODE REVIEW

**Comment by AjexRose** [comment]
im scared to ask.. but who is buying more then 6 reinforcements?

**Comment by takemysoult** [comment]
> im scared to ask.. but who is buying more then 6 reinforcements?

corvax players

**Comment by deltanedas** [comment]
pro warops just buy reinforcements nothing else

**Comment by Aisu9** [comment]
> pro warops just buy reinforcements nothing else

mostly because they know people will ghost/suicide/die to take them?

**Pull request merged**
