### PR TITLE
added a few chatsan entries

### PR DESCRIPTION
**Pull request by tosatur**
## About the PR
Added the following words to chatsan
- lmfao -> *laugh*
- lmfao. -> *laugh*
- rofl. -> *laugh*
- wtaf -> what the actual fuck
- wsg -> what's good
- mb -> my bad
- jfc -> jesus fucking christ
- omw -> on my way
- otw -> on the way
- yk -> you know
- istfg -> i swear to fucking god
- idgaf -> i don't give a fuck
- smth -> something
- allg -> all good

## Why / Balance
I kept using these in game and was dismayed to find a lack of a full sentence escape my character's lips

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Added more words to chat sanitisation

### CODE REVIEW

**Comment by UBlueberry** [comment]
can you add "yk" -> "you know"

**Comment by tosatur** [comment]
> can you add "yk" -> "you know"

i can add it but i'm worried about adding too many and breaking chat

i wanted to add "u" -> "you" but afaik that was removed already for the same reason

**Comment by Emisse** [comment]
you dont need to add punctuation in these anymore

**Comment by tosatur** [comment]
not sure why this test is failing?

**Comment by JIPDawg** [comment]
Looks like it's the classic nukeops fail and some cargo arbitrage test. Nothing you really need to worry about.

**Pull request merged**
