### PR TITLE
Stun prod

### PR DESCRIPTION
**Pull request by noudoit**
## About the PR

adds a stun type weapon that the crew can access via crafting this is not a good sec alternative as it does less stun drain per hit and cannot be carried easily.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added craft able stun weapon.

### CODE REVIEW

**Comment by noudoit** [comment]
time to figure out how do add to the crafting table
(:

**Comment by PixelTheKermit** [comment]
> time to figure out how do add to the crafting table

to the what?

**Comment by noudoit** [comment]
> > time to figure out how do add to the crafting table
> 
> to the what?

CRAFTIN TABLE i need to make le stun prod a craft able weapon

**Comment by mirrorcult** [comment]
add a crafting recipe prototype

**Comment by noudoit** [comment]
> add a crafting recipe prototype

working on this now i believe its working just testing with a copy of spears prototype then im going to alter it to something suitable.

**Comment by noudoit** [comment]
yeah crafting is confusing

**Comment by PixelTheKermit** [comment]
> yeah crafting is confusing

Make it not confusing, shrimple as that

**Comment by noudoit** [comment]
this will be left for a moment

**Comment by AJCM-git** [comment]
@noudoit you coming back to this?

**Pull request closed without merging**
