### PR TITLE
Train station

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
added some miscellaneous trivia. Some of it is just a convenience for mapping, some of it is specifically for the new station.
- Added new "Train lattice" that cannot be created, they have the full functionality of regular lattice, and cause players to experience new ambient sound effects in a space train theme.
- Added space train sound effects.
- Added 2 new types of portals using the Gateway portals sprite. Needed for mapping purposes. 
- The statues have now gotten noRot: true, and rotate beautifully with the camera.
- Added a blue comfy bench and construction recipe for it.
- All colored poweredLight lamps (crystal lamps, sodium lamps, LEDs) now glow the right color on mapping (previously all were white on an uninitialized map).
- ~~Added stained glass windows and construction recipe for them.~~ [Deleted]
- Added cool parallax with meteorites flying down. For the new station.
- FloorHullReinforced now `Indestructible: true` (used only on Pirate shuttle before). Made to make it harder to separate the train with explosions

Added Train Station
not added to rotation. Only playtest.

## Media
image

Render: 
[Train-0](https://github.com/space-wizards/space-station-14/assets/96445749/7f003e74-bf05-4915-9591-28ef6eec5acd)

**Changelog**
:cl: TheShuEd, Vsem, Jeb
- add: Added Train station! Only for Playtest

### CODE REVIEW

**Comment by mirrorcult** [comment]
want art director opinion on the windows imo

**Comment by TheShuEd** [comment]
### Deleted stained window

**Comment by K-Dynamic** [comment]
Space trains?

Sunless Skies pr based

**Comment by potato1234x** [comment]
what is that background parallax

**Comment by TheShuEd** [comment]
Shit, no

**Comment by TheShuEd** [comment]
Train-0

**Comment by potato1234x** [comment]
walking simulator map

**Comment by K-Dynamic** [comment]
God we need transit tubes from ss13 badly for bigger maps

**Comment by deltanedas** [comment]
we have that its called disposals

**Comment by notquitehadouken** [comment]
god forbid you accidentally bump one of the windoors when going between sections :trollface:

**Comment by Kadeo64** [comment]
> we have that its called disposals

disposals are loud and steel transit pipes are quiet and glass 
also transit pipes have diagonals (impossible)

**Comment by Carmell0** [comment]
Is this actually gonna be a station? One syndie bomb and the whole thing is getting cut in two. I love it

**Comment by deltanedas** [comment]
idk if its just maprender tripping but there are no grilles on the meteor shields so they wont do anything

**Comment by TheShuEd** [comment]
Its ok, WIP

**Comment by Kadeo64** [comment]
>`minplayers: 10`

\>no maxpop

\>potentially highpop map with 8 botany trays

\>2 botanists

\>8 trays

botany is already squabbling over tray space with 10 trays on packed and 9 on saltern

**Comment by K-Dynamic** [comment]
Alright we're gonna need space lube bottles and make a whole line from top to bottom

Let's see how that works for fast travel :trollface:

**Comment by deltanedas** [comment]
lube express on the side , big line of lube puddles with a break between each section for you to get off

**Comment by TheShuEd** [comment]
Updated render
- New engi
- New maints, new disposal travel pipes
- Many fixes

**Comment by Hmeister-real** [comment]
You left a safe in the armory unlocked

**Comment by Hmeister-real** [comment]
Also the west maints in the bridge are extremely undefended, just one depth charge or c4 and boom, free entry to caps locker, suit, spare ID and Renault if they are buckled to their bed assuming that it is a normal syndie, imagine nukies or even solo-op with a china lake in space :godo: . Maybe make it 2 layers of walls and glass on both sides and change the maints doors into command doors?

**Comment by Kadeo64** [comment]
So, I just remembered something. Bagel's AI core has reinforced plating over a disposals pipe, which makes the disposals pipe completely untamperable. I think that that should be done here, as all it takes is one shitter with an emergency EVA suit and a wrench to make the pipes outside the station deathtraps.

**Comment by TheShuEd** [comment]
updated render

[Train-0](https://github.com/space-wizards/space-station-14/assets/96445749/7f003e74-bf05-4915-9591-28ef6eec5acd)

**Comment by Kadeo64** [comment]
> we had a salamander test round today and someone did this, it sucked.

called it

**Comment by CatMagic1** [comment]
goob station fucking loves this map

**Pull request merged**
