### PR TITLE
Security Vest and Helmet Resprite

### PR DESCRIPTION
**Pull request by DieselMohawk**
## About the PR
 Resprites the default Security vest and helmet.

## Why / Balance
 The old variations were old and were beginning to fall behind the rest of the art style, plus I want to see usage of the vest and helmet as they have been mostly unused by anyone except cadets.

## Media

New:
image
image
image
image
Old:
image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Security Vest Resprited
- tweak: Security Helmet Resprited

### CODE REVIEW

**Comment by DieselMohawk** [comment]
Whoops, messed up the old icon previews

**Comment by ps3moira** [comment]
I don't like the flatness of the previous resprite for the helmet, but these changes don't look right, mainly the vest itself.

**Comment by Brandon-Huu** [comment]
Let's make them look less evil not more

**Comment by DieselMohawk** [comment]
> Let's make them look less evil not more

Please explain what makes you say that?

**Comment by KittenColony** [comment]
The vest looks like shit, can't exactly pinpoint what, it's better then the original. The main issue is when you paint shit, its still shit

the helmet looks better though

**Comment by KittenColony** [comment]
> > Let's make them look less evil not more
> 
> Would you mind explaining what makes you say that?

tfw shitsec

**Comment by DieselMohawk** [comment]
I'd like feedback on what does or doesn't work, it's fine to not like it, just tell me why in a way that I can work on.

**Comment by ps3moira** [comment]
> I'd like feedback on what does or doesn't work, it's fine to not like it, just tell me why in a way that I can work on.

Extremely stiff, I understand you were trying to do velcro straps on the sides as well but it just doesn't visually work.

**Comment by Golinth** [comment]
I feel like there isn’t enough depth(?) to the inventory sprite. Like with the shading and the shoulders, it’s very clear the old one is a representation of a physical object, while the new one has almost none of that, and looks closer to a painted cardboard cutout

**Comment by UbaserB** [comment]
It’s too dark for one, and the form feels off

**Comment by DieselMohawk** [comment]
Alrighty, this should be enough feedback. I'll keep the helmet design and completely rework the vest.
It will remain a relatively dark color to keep with the slim vest that most officers use, this is so that you can use the helmet with either vest and look good.

**Comment by IProduceWidgets** [comment]
I think the glass visor looks a little weird. I think I'd rather it get removed from the icon than added to the clothing sprites.

**Pull request closed without merging**
