### PR TITLE
[Sprite] New moth eyes

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

This way they look better, believe me 🤓 and now the eyes are even on all sides!!!

**Media**

MOTH

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame ugh ugh 

:cl: PuroSlavKing
- add: Added an alternative kind of moth eye marking!

### CODE REVIEW

**Comment by Partmedia** [comment]
Would this be better as an eye variant that can be customized in the character customization menu, or is the old one so bad that it's not worth keeping?

**Comment by PuroSlavKing** [comment]
> Would this be better as an eye variant that can be customized in the character customization menu, or is the old one so bad that it's not worth keeping?

cool customization has been and will remain, but as for choosing the shape of the eyes, there are already questions for who decides to create a new category of eye customization

**Comment by LankLTE** [comment]
Eye markings already exist..? Granted I'm not sure they can work with the way markings do, but given literally nobody else has complained about the eye markings changing it outright feels weird.

**Comment by PuroSlavKing** [comment]
> Eye markings already exist..? Granted I'm not sure they can work with the way markings do, but given literally nobody else has complained about the eye markings changing it outright feels weird.
> 
> EDIT: Personally I like these less. I'm sure there's some people who like these better, but that's why it should be implemented as a marking if it is going to be implemented (in my opinion)

ugh... eye markings rly exist. I will try to make 2 types of eyes, but considering that this will be the only race where there is a choice of eyes, I cannot vouch for the result 😶‍🌫️

**Comment by Emisse** [comment]
I like the + shaped eyes

**Comment by PuroSlavKing** [comment]
> I like the + shaped eyes

I like it too, but the game does not have a full-fledged eye shape selection, at the moment it looks more like makeup under the eyes, since the past eyes remain on the sprite 😕

**Comment by JoeHammad1844** [comment]
looks like its from a different art style

**Comment by PuroSlavKing** [comment]
> looks like its from a different art style

looks like a cape moth but with legs :trollface:

**Comment by UbaserB** [comment]
I want this to be optional like a marking, as i personally LOVE the + eyes a lot more but other people might also like this variatn

**Comment by PixelTheKermit** [comment]
these eyes don't look that good imo

**Comment by Luxzhv** [comment]
I must agree with many others, this seems like a minor but controversial art change. If you can somehow place the eyes on the "eye markings" layer and we can have more and different eye shapes in the future would be for the best, imo.

Variety is the spice of life afterall.

**Comment by Flareguy** [comment]
This should not modify ``full`` or the regular moth eye sprites. Otherwise, this is probably fine.

**Comment by metalgearsloth** [comment]
Re-open if you come back to this.

**Pull request closed without merging**
