### PR TITLE
You can FTL to the Chess Dimension.

### PR DESCRIPTION
**Pull request by PJB3005**
## About the PR
After all these years...

## Why / Balance
Amongus.

## Technical details
I love ECS.

## Media
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
* Breaks the 4th wall or something idk.

### CODE REVIEW

**Comment by UbaserB** [comment]
based

**Comment by deltanedas** [comment]
pro its merging into master not april 1th

**Comment by PJB3005** [comment]
oh jesus christ

**Comment by deltanedas** [comment]
good pr 1.7m added must be surgery :trollface:

**Comment by Simyon264** [comment]
and AI too

**Comment by baddiePRO** [comment]
holy hell

**Comment by JackSage** [comment]
Ah, finally, we can have chess Ops.

**Pull request merged**
