### PR TITLE
fixed nocturine locale

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
~~Removed Nocturine from the uplink catalog~~
Fixed the locale being missing for nocturine, also increased price from 5tc to 6tc

## Why / Balance
~~Nocturine was already intended to be removed in the PR which added Vestine, but was not. This change simply fixes the mistake.~~

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
I love railroading syndicates into lethals! I hate player freedom!

**Comment by Emisse** [comment]
it was decided to keep it in the uplink for a greater price than the synthesis kit

**Comment by Moomoobeef** [comment]
alright, I'll make that change tomorrow morning. 3am for me rn. I was just making the pr real quick bc ubaser asked me to

**Comment by Moomoobeef** [comment]
All my shit broke, trying to fix it so I can make the aforementioned change but I'm tired as hell so no promises.

**Comment by Emisse** [comment]
its supposed to be in the uplink what are you trying to do with this pr

**Comment by Moomoobeef** [comment]
image
literally just made it because devi asked me to, I was asking them for an idea for a PR I can just knock out because I felt motivation to actually contribute

image
and then after I made the PR they remembered that that was actually not what was supposed to happen.

So now this morning I was trying to put it back and such and vscodium just fucking broke and I'm trying to fix it

**Comment by Emisse** [comment]
its localization looks messed up in the uplink if you want to fix that

**Comment by Moomoobeef** [comment]
I want to, but I can't currently fix shit until I fix vscodium, so that has to wait until I get my shit unfucked

**Comment by Moomoobeef** [comment]
actually it's not vscodium that's broken specifically, I'm not really sure where the fault is but every time I run and debug it shits itself even without any changes of mine, so I'm trying to figure out what the fuck is wrong with the game so I can test my changes.

**Comment by Moomoobeef** [comment]
uhh I think I fucked something up

**Comment by Moomoobeef** [comment]
somehow I ended up with lots of other commits being included in this PR, and I don't really think that's supposed to happen. I have very limited git knowledge. I'm considering just closing this pull request and branch and making the changes all over on a new branch just so it isn't a mess. Let me know what you think @Emisse

**Comment by Partmedia** [comment]
> somehow I ended up with lots of other commits being included in this PR, and I don't really think that's supposed to happen. I have very limited git knowledge. I'm considering just closing this pull request and branch and making the changes all over on a new branch just so it isn't a mess. Let me know what you think @Emisse

Your Git history looks fine to me. You can double check this yourself using the files changed tab:

image

**Comment by Moomoobeef** [comment]
huh I guess so. Alright then, I think this is ready to merge in that case

**Pull request merged**
