### PR TITLE
Hasten handcraft gauze recipe & decrease techfab gauze cost

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR

- Reduces gauze construction doafter time from 10 seconds to 3 seconds
- Reduces medical techfab gauze cost from 2 cloth to 1 cloth

### Handcrafting
Gauze has an crafting time of 10 seconds for only a single unit of gauze, meaning players ignore the recipe in standard gameplay.

Reducing handcrafting to 3 seconds should be more reasonable yet balanced as players will still be limited by cloth, especially in dire situations without access to botany or textile crates.

### Techfab
The medical techfab gauze recipe is easily missed from lack of regular usage and difficulty of gathering cloth. Making gauze cheaper in the techfab should promote usage and showcase efficiency over handcrafting gauze.

It should also make it more on-par with other topical recipes; a 5-heal bruise pack prints for 0.5 mats, while a specialised 15-heal gauze prints for 1 mat instead of 2.

## Technical details

yml changes only
- `Resources/Prototypes/Recipes/Crafting/Graphs/improvised/gauze.yml` (reduced gauze recipe doafter from 10 seconds to 3 seconds)
- `Resources/Prototypes/Recipes/Lathes/medical.yml` (reduced med techfab gauze recipe cloth cost from 2 to 1)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Handcrafted gauze now takes 3 seconds instead of 10 seconds of crafting
- tweak: Medical techfab gauze recipe now takes 1 cloth instead of 2

### CODE REVIEW

**Comment by chromiumboy** [comment]
Sounds good to me, thanks for this

**Comment by slarticodefast** [comment]
Hmm, I'm not so sure about the price reduction:
- Gauze heals 5 slash and 10 piercing, an excellent tool for gun shot wounds (especially in nukie rounds)
- Bruise packs heal 15 brute damage (so 5 slash, 5 blunt, 5 pierce per use), so the same total
- if you butcher a bunch of jumpsuits from the autodrobes you can easily obtain tons of cloth, easier than other materials

**Comment by Aisu9** [comment]
> Hmm, I'm not so sure about the price reduction:
> 
>     * Gauze heals 5 slash and 10 piercing, an excellent tool for gun shot wounds (especially in nukie rounds), on top of the bleeding reduction
> 
>     * Bruise packs heal 15 brute damage (so 5 slash, 5 blunt, 5 pierce per use), so the same total
> 
>     * if you butcher a bunch of jumpsuits from the autodrobes you can easily obtain tons of cloth, easier than other materials

the printing cost reduction is ONLY for the medfab, considering it's a medical items it make sense that tech printing them is faster and more efficient than handmade

**Comment by chromiumboy** [comment]
Yeah, I'm not worried about the price reduction for the medifab either

**Comment by Plykiya** [comment]
as someone who decimates clothingdrobes during war ops
one drobe will grant you 200 gauze at the medifab right now

so it will now give 400 total gauze after the change

**Comment by Plykiya** [comment]
> > as someone who decimates clothingdrobes during war ops one drobe will grant you 200 gauze at the medifab right now
> > 
> > so it will now give 400 total gauze after the change
> 
> I mean the same could be said if you prowl maints or disposals for mats and just print a fuckton of bruise packs and ointments
> 
> I could leave the med techfab recipe unchanged but that kinda feels like a warops problem

it indeed changes basically nothing, evem during warops

people do not live long enough to use all this gauE

**Comment by SlamBamActionman** [comment]
This will make gauze significantly more easy to acquire, and I'm not sure if it's a good thing that it's reduced all the way to 3 seconds to craft; personally I find gauze to be one of the best common topicals in the game, with the crafting speed being a tradeoff of having it be readily available.

However I am willing to give this PR a go and see if it causes any issues in playtesting. 10 seconds *is* a long time, and making it easier to craft in the medfab is probably good because I find it to be the one topical medical tends to run out of.

**Comment by thebadman4662** [comment]
> However I am willing to give this PR a go and see if it causes any issues in playtesting. 10 seconds _is_ a long time, and making it easier to craft in the medfab is probably good because I find it to be the one topical medical tends to run out of.

Ironic, I have opposite experience and I use gauze even over Pun for patients with Lac/Bru wounds to speed up the treatment. It will mostly be help to antags, mobilized crew and sec as handcrafting was agonizing and doctors never know how to use medfab and print said gauze when you ask them for some and bring cloth.

**Pull request merged**
