### PR TITLE
Bee's cant become zombies anymore

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Self explanatory

## Why / Balance

Bee's are so fucking small, move fast and have the same chances of turning you into a zombie as a human.

If you think more mobs should be included in here let me know.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Vasilis
- fix: Bees can no longer turn into zombies.

### CODE REVIEW

**Comment by KingFroozy** [comment]
butterflies...

**Comment by deltanedas** [comment]
buuuuuzzz.......

**Comment by Partmedia** [comment]
Nitpick on the Changelog: "Bee's" is the possessive form of "bee", i.e. "the bee's house". I think you mean "bees". I also don't think it's necessary to say "and will just die." I've edited the Changelog for you in this change.

**Comment by VasilisThePikachu** [comment]
Minor Grammer mistake.

**Pull request merged**
