### PR TITLE
Added Disco Floor

### PR DESCRIPTION
**Pull request by ps3moira**
## About the PR

Added disco floors.
## Why / Balance

Because it's fun to get your groove on 😎 
## Media
disco
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes

**Changelog**
:cl:
- add: Added disco floors. Groovy!

### CODE REVIEW

**Comment by UbaserB** [comment]
omg this is so silly i love it

**Comment by TheShuEd** [comment]
how's the progress? Do you plan on fixing it and getting it out of the draft?

**Comment by ps3moira** [comment]
> how's the progress? Do you plan on fixing it and getting it out of the draft?

I've worked on it but I'm still stuck on the same issue of getting it to power on and off when connected with a multitool to a switch. I will try and find a coder to help with this

**Comment by metalgearsloth** [comment]
Re-open if you come back to it.

**Comment by kosticia** [comment]
no groove on😭😭😭

**Pull request closed without merging**
