### PR TITLE
Fix arrivals not docking on spinning stations

### LINKED ISSUE #25901: Arrivals not docking.
## Description
Sometimes arrivals is not docking, players panic and aHelp generating quite a few aHelps, they get teleported to arrivals on the ship departing again so not too impactful.

**Reproduction**
I don't really have any yet... Will update if one comes up.
It seems intermittent, have not found root cause.
Last seen on meta, nothing blocking the arrivals area.
There was a slight station rotation, as in it was drifting a bit.

**Screenshots**
image
image

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ShadowCommander**
## About the PR

Angle tolerance was too tight for the arrivals shuttle to dock on station when it was spinning.

Changed the tolerance from 0.01 to 0.15.

Fixes #25901

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed arrivals shuttle not docking with the station when it was slowly spinning.

### CODE REVIEW

**Comment by UbaserB** [comment]
Does this... also affect normal shuttle docking (e.g cargo)?

**Comment by ShadowCommander** [comment]
This affects any shuttle that automatically docks when coming out of FTL.

**Comment by metalgearsloth** [comment]
The coordinates might need bumping as well but we can do that in a separate pr.

**Comment by CatMagic1** [comment]
Ah, so it was me, the station rammer's fault.

**Pull request merged**
