### PR TITLE
Prying reinforced tile now will give you back metal rod

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

title
also removed FloorTileItemReinforced since it cannot be obtainable

## Why / Balance

its fucking annoying when you accidentally click with rod on plating and it becomes fucking floor tile and you just loose a rod

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Prying reinforced tile now will give you back metal rod

### CODE REVIEW

**Comment by MACMAN2003** [comment]
you're a hero

**Comment by LankLTE** [comment]
Glass can be placed as a tile as well, and when pried, gives you glass back. Is it possible to make prying reinforced tiles just give you a rod back? Requiring welding is still going to be annoying.

**Comment by UbaserB** [comment]
i agree with lank

**Comment by IProduceWidgets** [comment]
Seems weird to me to keep the tile items if practically youre just going to use rods anyway. I'd just have prying give a rod back.

**Comment by lzk228** [comment]
applied review

**Comment by deltanedas** [comment]
i think it should be the other way around, you have to explicitly craft reinforced tiles

the main issue with rods is you accidentally click and then it slows you down prying it, even if you get the rod back you wont get your time back

**Pull request merged**
