### PR TITLE
Rebalance small-a-1 for salvage ore mining

### PR DESCRIPTION
**Pull request by 20kdc**
## About the PR

The crates in `small-a-1` were always intended as a holdover until mining dropped ores.
Also removes a known "noob trap" (the plasmafire) since the salvage teams have just learned it.

**Screenshots**
image

**Changelog**

:cl:
- tweak: A certain sealed small asteroid will no longer contain plasmafire or crates.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Honestly, the map should just remain as is and procgen asteroids should be added. Seeing as it's just a blob shape with rock on it, there's no sense in getting rid of the old one just to replace it with something less interesting.

**Comment by juliangiebel** [comment]
I don't know about the plasma fire asteroid. That is one of the few actually dangerous salvage maps. (Excluding player controlled mobs whiche are just annoying imo)

**Comment by 20kdc** [comment]
Ok, compromise - keep the plasma fire, but still get rid of the crates, and maybe reduce the fire to a more scattered set of tiles?

**Comment by juliangiebel** [comment]
> Ok, compromise - keep the plasma fire, but still get rid of the crates, and maybe reduce the fire to a more scattered set of tiles?

That's good 👍

**Comment by 20kdc** [comment]
it's done

**Review by juliangiebel — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Comment by 20kdc** [comment]
So I just realized the changelog entry ended up being turned into a bit of a lie because of the later changes to the PR.
Oh well. Fun surprise for them all I guess.

**Pull request merged**
