### PR TITLE
Make Shark Plush Janitor-Bucketable

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
I added the ability to put the shark plushie into the janitor's mop bucket.
In doing so I also overhauled all the sprites for the shark plush, making them look nicer.

## Why / Balance
The shark covers up the water while it's in the bucket so you can't see how full it is but I think that is a small price to pay for bucket shark.

## Technical details
This adds one item slot to the mop bucket that only accepts the three variations of shark plushie.

## Media
New:
image
Old:
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None.

**Changelog**
:cl:
- add: Janitors can now take the shark plushie for a walk in their bucket.

### CODE REVIEW

**Comment by UbaserB** [comment]
i dont like how shiny the new sprite is

**Comment by Psychpsyo** [comment]
> i dont like how shiny the new sprite is

image
Is this better?

**Comment by Psychpsyo** [comment]
Ok, one more update since it was still to shiny:
image

**Comment by mirrorcult** [comment]
that looks much better imo

**Review by mirrorcult — APPROVED** [review]

**Comment by deltanedas** [comment]
fishe

**Pull request merged**
