### PR TITLE
fix(seizures): remove seizures from the game

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Increases the animation time of the mind shield flashing from 1 second to ~4~ 2 seconds.

## Why / Balance

My eyes, oh god my eyes.

## Media

**OUTDATED VIDEO**
[Screencast from 02-29-2024 12:52:06 PM.webm](https://github.com/space-wizards/space-station-14/assets/103440971/5988043b-fd7f-4438-bb6c-0218c81a6829)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by UbaserB** [comment]
now it feels a bit long, can you make it 2-3 seconds instead?

**Comment by Golinth** [comment]
for sure, make it 2 seconds. Its where I originally had it, but was told it looked a bit too slow.

**Comment by Hmeister-real** [comment]
Yeah 2 seconds sounds perfect

**Comment by Brandon-Huu** [comment]
Who broke the tests?

**Pull request merged**
