### PR TITLE
Fix pneumatic cannon in high power mode not firing correctly

### PR DESCRIPTION
**Pull request by luizwritescode**
## About the PR

Reduced the `BaseProjectileSpeed` multiplier from `4` to `2` to try and fix the pneumatic cannon projectile stopping at a fixed distance when trying to fire in High Power mode.

While this feels like a cheap fix, going any further requires changing the physics of throwing objects, which in turn may break more things. It's probably not worth it to mess with it just to fix an obscure item like the pneumatic cannon which is almost never seen in-game. It's already pretty fast at a 2x multiplier, no need to go faster any faster.

## Why / Balance

This description hints that projectiles where intended to go farther at High power, when in fact, they did not.
```
/// <summary>
///     How strong the pneumatic cannon should be.
///     Each tier throws items farther and with more speed, but has drawbacks.
///     The highest power knocks the player down for a considerable amount of time.
/// </summary>
public enum PneumaticCannonPower : byte
{
    Low = 0,
    Medium = 1,
    High = 2,
    Len = 3 // used for length calc
}
```

## Media

The video shows me using the pneumatic cannon at LOW, MEDIUM and HIGH power modes before the change. Then after the change I show just the new HIGH power mode speed. Before the change, notice how on HIGH power mode it abruptly stops at a fixed distance.

https://github.com/space-wizards/space-station-14/assets/33888056/c75468d9-3c77-4cd7-910d-bdc707729c18

## Breaking changes

No breaking changes, but I found out about other issues that I'll disclose below

## Out-of-Scope Issues

While testing the pneumatic cannon I found out that, at higher speeds, some objects will just ignore collision altogether. I guess a crowbar being shot through a pneumatic cannon _should_ deal damage, because it has the `DamageOnHighSpeedImpactComponent`, but as of right now it does not.

My guess (this is just a guess) would be the pneumatic cannon is finnicky because it uses the "throwing" system to launch it's projectiles, resulting in the weird scenario where shooting will try to "land" the item where you clicked on the screen. Ideally, the pneumatic cannon should feel more like shooting a bullet where you can only pick the direction you shoot and not like throwing a ball where you can pick where it will land.

**Changelog**

🆑 coffeeware
 - fix: Pneumatic cannon in High power mode now fires correctly

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Passing in the power to the throwingsystem call doesn't seem to hard to implement and would be preferable, same with marking it as not land-at-cursor.

**Comment by luizwritescode** [comment]
I tested more and the bug seems to happen inside TryThrow. WIth high enough speed (like when you multiply the base projectile speed of the pneumatic by 4, `baseThrowSpeed` becomes 80) this check for less than `MinFlyTime` keeps setting flyTime to zero if the direction vector is not long enough:

``` 
         // Set the time the item is supposed to be in the air so we can apply OnGround status.
        // This is a free parameter, but we should set it to something reasonable.
        var flyTime = direction.Length() / baseThrowSpeed;
        if (compensateFriction)
            flyTime *= FlyTimePercentage;

        if (flyTime < MinFlyTime)
            flyTime = 0f;
```

which it can't be, with that speed even at max distance throw flytime is like 0.13 then gets treated as OnGround too soon.

since there is a hardlimit on the time an item can fly there needs to be a check to adjust flyTime or increase the throw distance when the baseThrowSpeed is too high, or simply clamp it and not allow  an item to be thrown at that speed

**Comment by slarticodefast** [comment]
Thanks a lot for the investigation, looks like I introduced this with my recent throwing system change.  Previously in the if clause flyTime was set to MinFlyTime (with some weird offsets in the timestamps, which all cancelled out) instead of 0. I changed this because it caused items thrown directly in front of you to fly too far, but I did not account for extreme throwing speeds like pneumatic cannon.
A few solutions in mind:
- completely remove the two lines `if (flyTime < MinFlyTime) flyTime = 0f;` They are propably not neccessary anymore after my changes.
- set `MinFlytime` to a much lower value (if needed at all)
- set a maximum throwing speed (on the magnitude of crossing the whole map in less than a second)
- revert this so items thrown at extreme speeds overshoot again (should only affect the new precise throwing calculations directly in front of you)
- a combination of the above

Let me do some testing on what works best.

**Comment by luizwritescode** [comment]
I reverted to setting flyTime to MinFlyTime. Then had to create a check for extreme speeds. `compensateSpeed ` will forcefully reduce speed  so the item won't land instantly at high speeds, It also fixes overthrowing too close to your feet. right now only `PneumaticCannonComponent ` has this check set to true but anything that throws at speeds higher than normal can use it. Spears for example could make use of that.

**Comment by slarticodefast** [comment]
I made an alternative PR fixing this for all fast thrown items, not only the pneumatic cannon: #29935
This also avoids having to add another parameter to the TryThrow function.
@luizwritescode I made sure to list you as a contributor in the changelog.

**Comment by luizwritescode** [comment]
closing this because it got fixed in a much simpler way [here](https://github.com/space-wizards/space-station-14/pull/29935)

**Pull request closed without merging**
