### PR TITLE
Fix being able to interact through walls on rotated grids

### PR DESCRIPTION
**Pull request by ElectroJr**
## About the PR 

This updates how the `InRangeUnobstructed` handles the `ignoreInsideBlocker` option. Previously it would ignore any blockers if either of the end points were contained inside the physics body's `GetWorldAABB`. This causes issues when the physics body is rotated, as the `WorldAABB` `Box2` is slightly larger than the actual physics bounds. 

This allows you to interact with items through walls on rotated grids. This is easiest to see by just placing an item on the other side of a window, getting the station spinning, and noting that the interaction outline cycles between red and green as the station spins.

I just replaced that code by instead adding entities that intersect the endpoints to a list of ignored entities. The entity lookup doesn't seem to suffer from the same rotation issue, so that appears to fix it.

## Other `ignoreInsideBlocker` issues

`ignoreInsideBlocker` is set to true by the majority of interactions, As far as I can tell the purpose it currently servers is so that:
- You can interact with posters and other wall-mounted entities
- You can still interact with windows, despite them being blocked by the grille underneath them

but as a consequence:
- you can interact with a grille, despite there being a window on top  (inc cutting or shocking yourself when you only want to knock).
- You can interact with wires (or other entities) that are inside of walls (inc cutting / shocking).

I'm not sure how to fix these issues. You could just remove `ignoreInsideBlocker`, or at least set it to false in more instances. But then you couldn't interact with windows or wall-mounts, so maybe they should get some sort of ignore-walls tag that InRangeUnobstructed checks for???

:cl:
- fix: Fixed being able to interact through walls on rotated stations.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
What if we ignored any anchored entities on the same layer (when / if we get them) on the same tile if the target is anchored? i.e. if there's a windoor in the way it blocks interaction but a poster in the middle is still interactable?

**Comment by ElectroJr** [comment]
I'm not sure what you mean by layers here, but would that also prevent interactions with grilles under windows?

**Comment by metalgearsloth** [comment]
AFAIK under Acruid's original plan each anchored entity would occupy a slot and only 1 entity could fit in that slot (so content could easily check say "is there an APC in this slot") rather than having to iterate every entity on an anchored tile. Technically that system could allow for that by having higher layers block lower ones.

In our case in the short-term we might need a tag or something for it.

**Comment by metalgearsloth** [comment]
Also this doesn't fix putting into plants through walls for a short-term fix.

**Comment by ElectroJr** [comment]
Well the plant issue seems to be because the Interaction system checks if the clicked location is in range & unobstructed, not the centre of the target entity.  I guess it's done that way to makes it easy to interact with large entities, but it does also mean that if an entity's collision box allows part of it to be on top of a wall you can still interact with it. 

Should I just redo this PR (or close it and open another) that removes `ignoreInsideBlocker` in favour for some sort of tag, which can just be removed whenever the layer stuff gets added?

**Comment by metalgearsloth** [comment]
Maybe for now just add a check where if the target isn't anchored it does a normal raycast (nuking ignoreInsideBlocker I think, though we may need some form of it for the origin), then we'll implement the other path after i.e. if anchored ignore any anchored entities on the target tile.

**Comment by ElectroJr** [comment]
I'll probably come back to this eventually

**Pull request closed without merging**
