### PR TITLE
Tortoise

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Adds tortoise to the game.

## Why / Balance

cool

## Technical details

no

## Media

Screenshot_20240116_141856

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Tortoises added to the game. You can put some hats on their shell!

### CODE REVIEW

**Comment by CatMagic1** [comment]
my guy 26 SPRITES FOR THE TURTLE... worth it

hehe tuttle

**Comment by lzk228** [comment]
:trollface:

**Comment by Deserty0** [comment]
most based 🐢 in the world

**Comment by Kadeo64** [comment]
can we throw them at ATVs

**Comment by lzk228** [comment]
> can we throw them at ATVs

on skeleton motorcycle

**Comment by AJCM-git** [comment]
New fluff animals ordered from cargo or spawned in the station have been added to the freeze list #8524 with new requirements for they to be approved (tldr is that they must have something cool going on apart from being cute and having sprites, like new AI behaviors or being spawned in proc gens maps), feel free to re-open if you meet them.

**Pull request closed without merging**
