### PR TITLE
Add insulated atmos gloves

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

Adds the Insulated Atmos Gloves, and adds them to the Atmospheric Technician's Locker.

## Why / Balance

Multiple maps (Cluster, Saltern, Bagel) have Combat Gloves mapped in Atmospherics, which they shouldn't: #11365 
While these _should_ be removed, doing so removes a cosmetic alternative for atmos players and forces them use normal insulated gloves.

The sheer prevalence of insulated gloves is a detriment to detective investigation gameplay, as insulated gloves are widely used with no variation in fibers. Adding variation to the available insulated gloves will give detectives more to work with while keeping counterplay options available to antags. The atmos gloves leave the unique "blue insulated fibers" on items touched. 

The gloves are put in the atmospherics locker to make them available to atmos techs without needing to be explicitly mapped, and to keep atmos from stealing gloves from Engineering (which they have to do right now).

Giving atmos their own gloves also lays the groundwork for giving them different functionality compared to normal insuls (e.g. giving them heat resistance to pick up heated objects like heated pipes, a mechanic normal engineers are unlikely to interact with).

## Technical details

Like normal insulated gloves, but bloo.

After this PR, mappers should aim to remove/replace combat gloves mapped in Atmospherics.

## Media

image
image
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added insulated atmos gloves, found in atmospherics lockers.

### CODE REVIEW

**Comment by Boaz1111** [comment]
blue👍

**Comment by UbaserB** [comment]
based drip

**Comment by Dutch-VanDerLinde** [comment]
atmos has combat gloves in ss13 mapped in their locker pretty sure since they're fire proof
if combat gloves won't be added then these gloves should be fireproof once clothes being lit on fire is possible

**Comment by EmoGarbage404** [comment]
kinda confused at the implication that atmos is "stealing" insuls from engie considering they have a whole vendor full of em

**Comment by SlamBamActionman** [comment]
> kinda confused at the implication that atmos is "stealing" insuls from engie considering they have a whole vendor full of em

That's my b, was only considering the Engineering lockers. 👍

**Comment by Djungelskog2** [comment]
I'd be lying If I said I hadn't ever forgot about insuls as Atmos because they don't start in our lockers, possibly costing lives

**Comment by a-person5660** [comment]
I almost always forget insuls as an atmos tech and it always gets me killed, this is a very welcome change.

**Comment by SlamBamActionman** [comment]
Hello! The PR was put up to a maintainer vote which concluded with the following result: Do Not Merge.

The reasons given were the following:
- Atmos can get normal insulated gloves via Engineering.
- It's debatable whether Atmos even needs insuls to begin with.
- The issue with yellow insulated fibers being too common could be solved by giving budget insuls their own category instead.

As such, this PR will be closed. Thank you for your contribution, me.

**Comment by Dutch-VanDerLinde** [comment]
dont worry... they will neeed them whenever fire clothing gets added

**Pull request closed without merging**
