### PR TITLE
Headphones can be turned on

### LINKED ISSUE #23673: Headphones should be able to be turned on
## Description

There are custom sprites for headphones which look like little notes above your head, but i tested it ingame and theres no button. Makes me very sad.

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Headphones can be toggled on or off to display the music notes effect.

Closes #23673

## Why / Balance

looks cool

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

headphones

**Changelog**

:cl:
- tweak: Headphones can be turned on

### CODE REVIEW

**Comment by SonicHDC** [comment]
Maybe add to headphones a midi player but with 1 tile range or/and 25-40% volume?
Now thats looks strange, notes without music.

**Comment by themias** [comment]
> Maybe add to headphones a midi player but with 1 tile range or/and 25-40% volume? Now thats looks strange, notes without music.

I thought about some music functionality, but I figured it would be best to wait until the MIDI/audio issues are sorted out first. Maybe I'll open an issue for that after this PR is merged.

**Comment by UbaserB** [comment]
> Maybe add to headphones a midi player but with 1 tile range or/and 25-40% volume? Now thats looks strange, notes without music.

client-side midiplayer with low volume and muffles sound around you.. and doesn't turn off if you slip/etc... that sounds great lol

**Comment by K-Dynamic** [comment]
Unusual Headphones

Unbox Burning Flames Headphones from lottery crate

**Pull request merged**
