### PR TITLE
Add logging Bwoink unauthorized bwoink

### PR DESCRIPTION
**Pull request by TokenStyle**
## About the PR
On unauthorized bwoink no log happens, but should log. Maybe with timestamps (don't let spam with it).
To help for future investigation when refactor happen.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Actually fix it. Don't just make add to the to do

**Comment by TokenStyle** [comment]
It's too time consuming to me rn, so...

**Comment by TokenStyle** [comment]
just a week later

**Comment by Brandon-Huu** [comment]
That's crazy. Isn't logging just a single line of code?

**Comment by Simyon264** [comment]
I can include a fix for this in #23458

**Comment by TokenStyle** [comment]
> I can include a fix for this in #23458

It would be amazing! You can put my PR in your PR description, so github will mention this PR as resolved too

**Comment by moonheart08** [comment]
Not a fix or valid change, so closing.

**Pull request closed without merging**
