### PR TITLE
Rev and Zombie icon visibility to ghosts are now determined by a CCVar

### PR DESCRIPTION
**Pull request by nikthechampiongr**
Currently waiting on #21260.
## About the PR

This PR makes a new CCVar that determines whether ghosts can see stuff such as the Rev, headrev, and zombie icons. Admin ghosts and the actual antagonists will be able to view these icons regardless of what the ccvar is set to. The ccvar defaults to true.
## Why / Balance

See #21201. The ability for ghosts to see whether for example someone is a head rev or a rev can and has resulted in them immediately relaying this information the moment they are revived or brought back in the round in some other way. This is obviously problematic. This PR however does not actually make it so ghosts can't see antag icons on wizden servers, but just gives us the option of doing it along with any other downstream servers that want to as well.
## Technical details

A new CCVar was added which the AntagStatusIconSystem.cs subscribes to. If it is set to false then people who do not have the relevant antag component will not see the icon except for aghosts. The way the system checks if the player is an aghost is checking whether they have the ghost component and can interact, the same method that the actual aghost command uses.
## Media

https://github.com/space-wizards/space-station-14/assets/32041239/ac40d761-561e-44ef-899a-511414b9f291

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A
**Changelog**

no cl no fun

### CODE REVIEW

**Comment by notquitehadouken** [comment]
bro why it call the emergency shuttle

**Review by crazybrain23 — CHANGES_REQUESTED** [review]
Instead of hard-coding a check if they're a ghost (with or without the ability to interact), should this not be a component, like the sec hud?

**Comment by nikthechampiongr** [comment]
> Instead of hard-coding a check if they're a ghost (with or without the ability to interact), should this not be a component, like the sec hud?

Adding a component would likely mean I'd have to redesign how the entire system works, especially considering that visibility is already tied to specific antag components. I don't have time for that, if this needs a new component then someone else should pick this up.

**Comment by nikthechampiongr** [comment]
I guess if you just want a component for ghosts/aghosts specifically like what happens with revs and zombies I could do that but does it change anything if ghost checking was already hard coded?

**Comment by nikthechampiongr** [comment]
Looking back at what those components were used for, they serve multiple purposes like giving their faction an image and also gamemode specific stuff like stun times after conversion. Making a new component for ghosts/aghosts would just be duplicating the ghost component which already signifies that something is a ghost and you can use just as well to distinguish between ghosts and aghosts. At most I could just add a boolean to the ghost component that signifies it's an aghost, or I guess replace the ghost checking part with checking for a component that gets added to ghosts(if the ccvar is set to true) and aghosts.

**Comment by nikthechampiongr** [comment]
Yea ok a separate component probably works.

**Comment by nikthechampiongr** [comment]
Ok thanks for telling me in discord that #21260. If it gets merged without it checking for some access or specific item then I'll just nuke  AntagStatusIconSystemAntagStatusIconSystem and base stuff for the revs and zombies off that. If it goes through too many changes to be usable in the zombie/rev  cases where team antagonists need to always know who their teammates then I'll just add a component where if you don't have the necessary antag component it will allow you to view them anyways as suggested.

**Comment by nikthechampiongr** [comment]
Currently I don't feel like doing this as I got some other stuff to do right now. Might pick it up later if nobody does so. If someone does try to implement this, you'll likely need to make it so this stuff isn't entirely controlled by the client.

**Pull request closed without merging**
