### PR TITLE
Moths can eat plushies

### PR DESCRIPTION
**Pull request by marboww**
## About the PR

Now moths can eat plush toys and with a distinctive sound! And by eating plush bees, you get 5 ounces of groundbee!
## Why / Balance

#25359 It's logical and funny.

## Media
https://github.com/space-wizards/space-station-14/assets/152051971/ef1717f4-7f6f-46c4-9120-73d231a70db4

**Changelog**

:cl: marbow
- add: Moths can now eat plushies and with a distinctive sound!

### CODE REVIEW

**Comment by Hmeister-real** [comment]
You should replace or layer the eating sound with the plushie sound so we can hear them scream as they are being eaten, but that's probably out of scope for this.

**Comment by Errant-4** [comment]
This is pure evil. This should be illegal

**Comment by marboww** [comment]
> You should replace or layer the eating sound with the plushie sound so we can hear them scream as they are being eaten, but that's probably out of scope for this.

done

**Comment by UbaserB** [comment]
can you make the doafter longer? i would hate to accidentally eat bites out of my plushie by misclicking.

**Comment by marboww** [comment]
> can you make the doafter longer? i would hate to accidentally eat bites out of my plushie by misclicking.

then I'll just make it 2 times longer

**Comment by K-Dynamic** [comment]
Does this mean plushes around the station will be eaten by AI mothroaches

I would prefer not having to choose between saving my cute plushes or mothroaches

**Comment by marboww** [comment]
> Does this mean plushes around the station will be eaten by AI mothroaches
> 
> I would prefer not having to choose between saving my cute plushes or mothroaches

I don't see a problem here. Plush toys can always be ordered at cargo. Moths with AI will harm like mice with food... but weirder.

**Comment by FairlySadPanda** [comment]
A perma prisoner looks up from his bed to see a moth being thrown in. Curious, he wanders over to the new arrival. "Hi. I'm in for murdering the captain and spacing the bar. You?"
The moth looks up. "Weh."

**Comment by TheShuEd** [comment]
Are all the toys now being eaten with the same sound?  Considering that the main key difference between the toys is the different funny sounds, it would make sense to use them while eating (the plush human will scream)

**Comment by TheShuEd** [comment]
And what about toy tesla and toy singulo? Can you eat them too?

**Comment by brainfood1183** [comment]
How will this interact with the pr that lets you put things inside plushies?

**Comment by marboww** [comment]
> And what about toy tesla and toy singulo? Can you eat them too?

No, toy tesla and singularity do not belong to plushies. They don't have parent.

**Comment by marboww** [comment]
> Are all the toys now being eaten with the same sound? Considering that the main key difference between the toys is the different funny sounds, it would make sense to use them while eating (the plush human will scream)

It seems worth changing that.

**Comment by marboww** [comment]
> How will this interact with the pr that lets you put things inside plushies? I know that pr isn't merged currently either but i guess its worth considering.

I suspect that things from the bun will just disappear. But that PR has not yet been accepted. We'll see

**Comment by marboww** [comment]
> Are all the toys now being eaten with the same sound? Considering that the main key difference between the toys is the different funny sounds, it would make sense to use them while eating (the plush human will scream)

done. Here is an example

https://github.com/space-wizards/space-station-14/assets/152051971/a013f216-88e8-48a9-9b38-ce290ae8ab8d

**Comment by K-Dynamic** [comment]
> done. Here is an example
> 
>  bandicam.2024-02-19.21-04-44-060.mp4

plush mukbang asmr real

**Comment by deltanedas** [comment]
remove clothmade from dehydrated fish since its not cloth

**Comment by Kadeo64** [comment]
> > How will this interact with the pr that lets you put things inside plushies? I know that pr isn't merged currently either but i guess its worth considering.
> 
> I suspect that things from the plushies will just disappear. But that PR has not yet been accepted. We'll see

it's probably a good idea to prevent moths from eating plushies with items inside (like how you can't eat coats with items inside) because stuff like the nuke disk can be eaten.

**Comment by TheShuEd** [comment]
> it's probably a good idea to prevent moths from eating plushies with items inside (like how you can't eat coats with items inside) because stuff like the nuke disk can be eaten.

Not valid until items in the plushies are merged. 

It's a question of what will be added to the game first.)

But I think items should just drop to the floor if the toy is eaten.

**Comment by Hmeister-real** [comment]
> > Are all the toys now being eaten with the same sound? Considering that the main key difference between the toys is the different funny sounds, it would make sense to use them while eating (the plush human will scream)
> 
> done. Here is an example
> 
>  bandicam.2024-02-19.21-04-44-060.mp4

Finally, moth cannibalism

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
