### PR TITLE
Hamster plushie

### PR DESCRIPTION
**Pull request by Starbuckss14**
## About the PR

I replaced the old hampter plush with a new sad hamster meme plush. Now with sound!
## Why / Balance

I added it because I did. Also lowered plushie crate cost from 1000 to 750. Bulk lizard crate costs 500 so seemed fair I change the price.
## Media

raf,360x360,075,t,fafafa_ca443f4786

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:

- add: Sad Hamster Plushie
- tweak: cost of plushie crate lowered from 1000 to 750

### CODE REVIEW

**Comment by TeenSarlacc** [comment]
I like the sprite, why not just have both hampter plushies though?

**Comment by TheShuEd** [comment]
It's funny, but save it for the first of April.
I'm against the merge of this PR

**Comment by slarticodefast** [comment]
I agree with Ed. It does not fit in with our art style, so I will close this PR.
Thank you for contributing.

**Comment by Starbuckss14** [comment]
> I agree with Ed. It does not fit in with our art style, so I will close this PR. Thank you for contributing.

POV: The most angry PR managers in history. Closing a simple new plushie. Same "art style" as the old one.  Throngler plushie: yes ghost plushie: yes sad hamster plushie: NO! Seems like if your in the inner cycle you can add what ever the fuck you want but if your new... Get lost.

The two are the same art style. I ask you to reconsider.

**Comment by Starbuckss14** [comment]
> I agree with Ed. It does not fit in with our art style, so I will close this PR. Thank you for contributing.

Screenshot 2024-12-22 153549
Same art style.

**Comment by Starbuckss14** [comment]
This is a minor sprite and sound change to bring the old meme up to date.

**Comment by JIPDawg** [comment]
These 2 look incredibly different... This has nothing to do with an "inner circle" one looks like an actual plush, the other looks like a someone used the paint line tool to cut the picture out and paste it on top of the plush...

**Comment by ArtisticRoomba** [comment]
I will note that upstream does have art standards, and any sprite changes are subject to art maintainer approval.

You can take a look at PR #33508 for an example on how *everyone has to follow the same rules*. That PR has gone through many art reviews, as art maintainers want to make sure the new sprites fit the desired unique artstyle for upstream.

You can also look at the merged PR #33776 as proof that silly items *can* pass art maintainer approval and be merged.

As for this PR, the sprite doesn't match the artstyle and the sprites aren't attributed.

In no instance did the maintainers attack you or show anger towards you.

The ghost plushie and thronger plushie also fit in with our artstyle quite well, compared to what is basically a soft PNG of a hamster. They went through art maintainer approval just like everything else.

There is no "inner circle". Anyone is free to submit PRs and have them reviewed, with the same priority as anyone else.

If you really want to continue this PR and resprite the hamster, I'd recommend starting in the sprite-dungeon channel in the upstream discord server. There's info there for you to start and you can chat with art maintainers to get some feedback.

**Comment by Tayrtahn** [comment]
Please test your changes locally before submitting your PR. I assume your intention was to fade the image to transparent at the edges, but it actually fades to white. This is very obvious in-game and makes it look more like a sticker than an object with depth.
Screenshot 2024-12-22 at 8 00 50 PM

**Pull request closed without merging**
