### PR TITLE
Roboticist Uniform Update

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Updates roboticist suit sprites with the new tg ones

**Media**

2345678Untitled

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: Updated the roboticist uniform sprites.

### CODE REVIEW

**Comment by brainfood1183** [comment]
Monkeys can now wear jumpsuits, don't forget to make sprites for the monkey race.

**Comment by potato1234x** [comment]
seems like you've done it for me, thanks lol

**Comment by Flareguy** [comment]
These are really overdetailed in my opinion. The old ones aren't too hot, but this is _much_ harder to read.
The collar also just looks dumb imo but that's a lot more subjective.
image

**Comment by EmoGarbage404** [comment]
Also, just to comment, please post in game screenshots if you're making sprite changes.

**Comment by potato1234x** [comment]
god what did i do

**Comment by potato1234x** [comment]
im just going to make a new pr, no idea how to fix this

**Pull request closed without merging**
