### PR TITLE
Fixes food duplicating in the microwave

### LINKED ISSUE #23774: Meat duplication glitch
## Description

As i am trying to cook anything that has raw meat in the recipe, the meat cooks and pops out as steak before the recipe is completed. Example being a burger or sausage bread. I noticed it was inconsistent though as sometimes the meat would cook and sometimes it wouldn't.

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by Tin-Man-Tim**
## About the PR
Fixes #23774 

## Technical details
Any active ingredient doesn't get cooked, this prevents the duplication as seen in the issue above. Raw food that is not in a recipe inside the microwave will get cooked normally.

## Media
previous functionality:
https://github.com/space-wizards/space-station-14/assets/73014819/5bf69184-d90f-4491-b52c-f613bb84c812

New functionality:
https://github.com/space-wizards/space-station-14/assets/73014819/1bc5918c-2a7f-427d-b8bf-7593d7127fd0

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- fix: fixes raw food getting duplicated in the microwave

### CODE REVIEW

**Comment by UbaserB** [comment]
i swear there was another PR fixing this at the same time

**Comment by lapatison** [comment]
> i swear there was another PR fixing this at the same time

[This one?](https://github.com/space-wizards/space-station-14/pull/23835)

**Comment by UbaserB** [comment]
yes that one

**Comment by Tin-Man-Tim** [comment]
Didn't see that pr, just saw the linked issue. I'll close this then.

**Pull request closed without merging**
