### PR TITLE
add secglasses to captain roundstart

### PR DESCRIPTION
**Pull request by Killerqu00**
## About the PR

Captain gets secglasses roundstart instead of sunglasses.

## Why / Balance

QoL change and a logical outcome from making secglasses roundstart gear.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Captains spawn with a pair of security glasses instead of sunglasses.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
captain doesnt need this, they ain't security

**Comment by Killerqu00** [comment]
> captain doesnt need this, they ain't security

Captain often has to take a role of security in low-pop environment. Besides, captain is already armed with security-level gear, so why not?

**Comment by Dutch-VanDerLinde** [comment]
> > captain doesnt need this, they ain't security
> 
> Captain often has to take a role of security in low-pop environment. Besides, captain is already armed with security-level gear, so why not?

because that's not their main job, in a low pop environment you can just get the security gear yourself since you have the access

**Comment by Dutch-VanDerLinde** [comment]
and captain gets a disabler for self defense, not for validhunting

**Comment by Cojoke-dot** [comment]
I would say it's not needed, It feels kinda power gamy? Captain does not need a stun baton or a sec belt, they are not sec, they are a manager of managers. It ties into this 
https://forum.spacestation14.io/index.php?/topic/2940-non-security-heads-doing-securitys-job/

**Comment by Killerqu00** [comment]
> I would say it's not needed, It feels kinda power gamy? Captain does not need a stun baton or a sec belt, they are not sec, they are a manager of managers. It ties into this https://forum.spacestation14.io/index.php?/topic/2940-non-security-heads-doing-securitys-job/

I am not giving captain a sec belt??? These are security glasses, not a weapon.

**Comment by Dutch-VanDerLinde** [comment]
it's still related, sec glasses are security gear

the only time you really would need a sechud as non-sec is as the HoP for reading IDs, but that's it

**Comment by Cojoke-dot** [comment]
> > I would say it's not needed, It feels kinda power gamy? Captain does not need a stun baton or a sec belt, they are not sec, they are a manager of managers. It ties into this https://forum.spacestation14.io/index.php?/topic/2940-non-security-heads-doing-securitys-job/
> 
> I am not giving captain a sec belt??? These are security glasses, not a weapon.

can captain not just look at someone's ID? Why would being able to see people's jobs from a distance help the captain manage the station?

**Comment by Killerqu00** [comment]
> it's still related, sec glasses are security gear
> 
> the only time you really would need a sechud as non-sec is as the HoP for reading IDs, but that's it

quoting what you sent

> Heads other than the Head of Security should not try to acquire any security gear that they do not spawn with on their person, or in their office without an in character justification.

Captain spawned with sunglasses pre-roundstart secglasses. The only thing I am doing now is updating this in captain loadout.

**Comment by Dutch-VanDerLinde** [comment]
security sunglasses used to be roundstart before they also acted as a sechud, and the captain got normal sunglasses at that time, he's always had normal sunglasses

**Comment by Killerqu00** [comment]
I mean, not a big deal if this does not get merged, but this feels like an inconsistency to me

**Comment by Dutch-VanDerLinde** [comment]
it's not very inconsistent, he ain't sec, so he gets normal glasses
just like the musician

**Comment by B1essedknight** [comment]
I'm of the mind that Cappy doesn't need the secglasses round start as others have pointed out seeing as they aren't a security officer. Plus if they wanted to they could just go to sec and get the gear themselves.

**Comment by deltanedas** [comment]
if cap needs to hunt valids they can go raid sec

**Comment by Killerqu00** [comment]
not in mood to argue

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
So I know this is kinda different but how would people feel about HoP having a sec hud round start?

**Comment by superjj18** [comment]
I'll probably reopen this change at some point.  It just makes sense for the captain, who already has access to all information related to sec, to be kept in-the-know with what is now sec starter gear.  I see no reason beyond precedence and that they "aren't sec" which is a weak argument at best given the captain is given a disabler and armed to the teeth roundstart.  Where ever there is security threats, cap will always be one of the handful of people you can trust to help.

The only balancing concern I can think of is thieves being slightly nerfed by captain always having them on.

Other than that it is a QoL for cap with little to no real downsides.

**Comment by deltanedas** [comment]
cap shouldnt be using sechud to stun/kill people without ids or who are wanted, the disabler is for self defence

**Comment by Killerqu00** [comment]
can you stop? i closed this PR for a reason

**Comment by superjj18** [comment]
> cap shouldnt be using sechud to stun/kill people without ids or who are wanted, the disabler is for self defence

A person running around without an ID is absolutely something the Captain should be immidiately aware of.  To cap that's either an unruly crew-mate, an intruder/stowaway/visitor, or someone in distress, all of which are things cap should either be acting on, or actively communicating with command and security via comms about

**Comment by superjj18** [comment]
> can you stop? i closed this PR for a reason

There is an unsubscribe button for a reason

**Pull request closed without merging**
