### PR TITLE
Slip Nerfs

### PR DESCRIPTION
**Pull request by Absolute-Potato**
## About the PR 
Slipping now defaults to 3 seconds to recover compared to 5 seconds previously. You now also recover faster from falling through a glass table, which fixes a niche infinite combo that was possible before. Space lube now also slips you slightly further which is not only more fun but also can make it easier to get through very large puddles of lube when in the past would have been total CBT.

**Screenshots**

**Changelog**

:cl: AbsolutePotato
- change: Slipping now defaults to 3 seconds to recover, down from 5.
- change: You now recover much faster when crashing through a table. (prevents niche infinite combo)
- change: Space Lube is now a bit slippier

### CODE REVIEW

**Comment by DogZeroX** [comment]
Can you remove blood slipping? It's been discussing that it's annoying af afaik

**Comment by moonheart08** [comment]
> Can you remove blood slipping? It's been discussing that it's annoying af afaik

Mirrorcult agrees here so i'd say you're clear to remove it.

**Comment by Absolute-Potato** [comment]
Should puddles even *default* to being slippery in the first place? I feel like it should be an opt in, because not everything is going to make you faceplant the second you walk over it.

**Comment by Zumorica** [comment]
> Should puddles even _default_ to being slippery in the first place? I feel like it should be an opt in, because not everything is going to make you faceplant the second you walk over it.

Ye, puddles should *not* default to being slippery

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
