### PR TITLE
Action Upgrade System

### PR DESCRIPTION
**Pull request by keronshb**
## About the PR

The Action Upgrade System is used to upgrade specific actions! It will be extremely useful for upgrading actions like spells, or actions for future antags like Changelings or Cults.

Additional functionality was also added to actions:
- The ability to have a number of uses _before_ the cooldown kicks in
- Methods to get/set/adjust the number of remaining uses, charges, and delay

## Why / Balance

It's going to be needed for the upcoming Magic Rework and it's also a stepping stone to Wizard, Changeling, Cult, etc.

## Technical details

Any actions that need to be upgraded will require the ActionUpgradeComponent to be added to it.
Actions that are of a higher level should inherit from the parent (the original action) and only change what it needs to make a smooth transition.
Not all actions should be upgradeable, which is why this wasn't added to any base actions.
The available actions will be listed in the EffectedLevels dict, so actions can be any specific level or even skip levels
ie) If Fireball can be leveled up to Fireball 2 at level 2 and Fireball 3 at level 5, it allows level 3 to be fluff.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/54602815/ffc1cbef-a330-4991-92ec-5c74bed3c98e

Charges on action tooltips:

image

image

**Changelog**

:cl:
- add: Added the Action Upgrade System - used to upgrade specific actions!
- add: Added commands to upgrade actions.
- add: Added Charges information to action tooltips for actions with charges

### CODE REVIEW

**Comment by ps3moira** [comment]
This would be awesome for so many antags and abilities!

**Comment by Emisse** [comment]
-merge charges/remaining uses
-define renewable with a bool on the component
-show charges visually somehow in action icon

**Comment by keronshb** [comment]
> -merge charges/remaining uses -define renewable with a bool on the component -show charges visually somehow in action icon

First two done. Last one I'll have to think about for a bit.

**Comment by keronshb** [comment]
> -merge charges/remaining uses -define renewable with a bool on the component -show charges visually somehow in action icon

Third also now done

**Comment by UbaserB** [comment]
why is there a changelog for this, this doesnt affect players i think

**Comment by Emisse** [comment]
it does

**Pull request merged**
