### PR TITLE
Gives the Sec winter jacket armor values.

### PR DESCRIPTION
**Pull request by ethespacewollf**
First PR so don't bonk me too hard.

Changes: 
-Sec winter jacket name changed to Security Armored Winter Jacket
-Given a description of : While it doesn't provide as much protection as standard issue armor, it will hopefully reduce Lizard officer fatalities.
- New modifiers: blunt .75, slash .75, piercing .85

About: I often found that sec lizards died a lot to cold, and warden has a winter armored vest. On top of this, it takes the same slot as armor so I simply modified it to be weaker armor, yet still have the jacket temp resist.

### CODE REVIEW

**Comment by LankLTE** [comment]
Careful as the HoP can print these. It's the same reason my PR to make the HoS's Winter Coat have armor was closed (but if you're going to change Sec coats still, I'd change HoS's too).

**Comment by ethespacewollf** [comment]
> Careful as the HoP can print these. It's the same reason my PR to make the HoS's Winter Coat have armor was closed (but if you're going to change Sec coats still, I'd change HoS's too).

Ah I see. Hmmm I can try to find a workaround. Either by making a separate new item with the same or similar sprite, or something of that sort. Ill write the HoS's down as well then.

**Comment by Emisse** [comment]
I dont think any wintercoats should have armor besides the wardens

**Comment by keronshb** [comment]
> I dont think any wintercoats should have armor besides the wardens

I do think that if there's an equal piece (ie captains parade jacket) that has armor, then the winter coat should also have armor.

**Comment by AJCM-git** [comment]
These are easily printable and i agree wintercoats shouldnt really have armor (If there are any exceptions to this, those should be fixed tbh)

**Comment by keronshb** [comment]
> These are easily printable and i agree wintercoats shouldnt really have armor (If there are any exceptions to this, those should be fixed tbh)

I don't feel like enough discussion happened to actually close this PR.

**Comment by QuietlyWhisper** [comment]
remove the changed winter coats from the uniform printer, add them to the security vendor(s) and(?) security lockers as an option for secoffs.

I don't think secoffs losing all armor because it's a little chilly is fair, even more so when it's mildly realistic to have armored winter clothing.

Otherwise sec hardsuits are simply the best choice overall aside from movement speed, which feels unnecessary

**Comment by keronshb** [comment]
> remove the changed winter coats from the uniform printer, add them to the security vendor(s) and(?) security lockers as an option for secoffs.
> 
> I don't think secoffs losing armor because it's a little chilly is fair, even more so when it's mildly realistic to have armored winter clothing.
> 
> Otherwise sec hardsuits are simply the best choice overall aside from movement speed, which feels unnecessary

This is what I was thinking. Remove any armored winter coats from the printer and put them into sec lockers and/or sec-specific vendors.

**Review by keronshb — CHANGES_REQUESTED** [review]
If you're giving this armor, place copies inside of sec lockers and remove it from being printable by the HoP.

If there's a sec vendor, place some limited copies into it.

**Comment by AJCM-git** [comment]
re-open once you come back to this

**Pull request closed without merging**
