### PR TITLE
Fixes Skubsuit

### PR DESCRIPTION
**Pull request by SweptWasTaken**
The hat for the skubsuit has a broken icon/sprite. It's fixed now.

### CODE REVIEW

**Comment by PJB3005** [comment]
We must start an investigations team to find the root cause of how this could happen. I expect the incident report by friday.

**Comment by SweptWasTaken** [comment]
Someone sabotaged it, it was working fine when I pr'd it.

**Comment by AJCM-git** [comment]
The problem here is that i forgot to put the parent and a path in the sprite component on the skub hat prototype.
The actual fix should be this:
```
- type: entity
  parent: HatBase                 #new
  id: HatSkub
  name: Skub Hat
  description: 'Best paired with the Skub Suit.'
  components:
  - type: Sprite
    sprite: Clothing/Head/skubhead.rsi       #new
  - type: Icon
    sprite: Clothing/Head/skubhead.rsi
  - type: Clothing
    sprite: Clothing/Head/skubhead.rsi
```

**Comment by SweptWasTaken** [comment]
I'm very disappointed you attempted to sabotage skub Abraham. I thought I could trust you...

**Pull request merged**
