### PR TITLE
Refactor/wounds

### PR DESCRIPTION
**Pull request by Jezithyr**
## About the PR

TODO before opening pr:
- [X] Wounds can be created on body parts from specified damage types
- [X] Wounds have severity that scales effects
- [X] Wounds heal over time and healing rate can be adjusted
- [X] When a wound is healed it may change to another wound (a scar)
- [X] Damage from a wound can overflow onto surrounding parts if it is destroyed
- [X] Implement trauma system. Traumas are lists of wounds that can be applied based on damage numbers.
- [X] Implement wound hp/integrity systems. (HP heals, integrity does not)
- [X] Implement pain, acts as a softcap on the number of wounds. If pain is above certain thresholds the entity enters crit or dies. Most wounds cause pain. Pain can be modified to increase or decrease it's affect.
- [X] Treatments can be applied to wound entities to modify their attributes.
- [X] Rewrite bleeding system to be per-wound based instead of just a hp buffer
- [X] Pain, and wound components can be modified by treatments
- [X] Implement consciousness and consciousness modifier system. With thresholds for crit and death.
- [X] Convert crit and death states to use consciousness to trigger instead of direct damage
- [ ] Update defibrillator to provide a temporary consciousness buff instead of healing damage
- [ ] Update medical scanner to list wounds and general health
- [ ] Create easy to use API/Events for all wound-med features
- [ ] Implementing blocking flag for consciousness if a player has been dead long enough to prevent consciousness changes/reviving if the player has been dead long enough
- [ ] Implement critical parts for consciousness. If these parts gets damaged decrease consciousness, if they are destroyed kill the entity.
- [ ] Hook up treatments to usable actions/doafters on items
- [ ] Implement Icons/Screen effects for Pain
- [ ] Implement Icons/Screen effects for Bloodloss
- [ ]  Implement Icons/Screen effects for Consciousness
- [ ] When a part is destroyed, it amputates any connected parts and applies an amputation wound to the parent part.
- [ ] Setup all medical items to use the new treatment system
- [ ] Pain and wound components can be modified by reagents
- [ ] Map all damage types to traumas
- [ ] Balance medical items
- [ ] Balance wounds and damage types
- [ ] Rough rebalance of all weapons/attacks
- [ ] Implement explosion damage logic
- [ ] Implement wound cauterization (Heat damage has a chance to stop bleeding on parts)
- [ ] Implement wound stacking/reopening
- [ ] Implement medical inspection text logic
- [ ] Implement medical inspection prompt (A right click option to get a medical description of an entity)
- [ ] Add hotkey for medical inspect
- [ ] Implement placeholder bodypart targeting. (Randomly select a bodypart with bias towards the torso or head)

Out of scope features that *may* come in a later pr (Do not ask for these or you get the slap)
- Surgery
- Broken bones
- WoundPen (Wounds that get applied to organs that are inside of bodyparts)
- Organ damage
- Organ simulation
- Bloodvessels
- UI menus
- Targeting

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Jezithyr, DrSmugLeaf
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by ZoldorfTheWizard** [comment]
INSTAMERGE

**Comment by PixelTheKermit** [comment]
> INSTAMERGE

still a draft buddy

**Comment by deltanedas** [comment]
body scanner is using old bui code, update it to use the userinterface system in robust.server

**Comment by deltanedas** [comment]
also these shouldn't be in spawn menu

**Comment by Emisse** [comment]
they just need to be abstracted

**Comment by moonheart08** [comment]
the PR is way far from being done, don't try and review it.

**Comment by deltanedas** [comment]
:trollface: is this still being worked on

**Comment by Jezithyr** [comment]
Closing this because I created a new branch for the medical refactor :^)

**Pull request closed without merging**
