### PR TITLE
Add gas tank valve

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

Open valve to release gas from gas tank. If you are not holding it when opened it will fly in random directions until its empty.

## Why / Balance

There was no convenient way to empty gas tanks.
Flying gas tanks will be funny (when I add collision damage to them)

## Media

https://github.com/space-wizards/space-station-14/assets/40753025/d935ff1a-69ba-4b2e-a3aa-abcb93803eda

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Gas tanks now have valves, which can be used to vent their contents.

### CODE REVIEW

**Comment by mirrorcult** [comment]
the sound is a little offputting when its repeated so many times like that, i really love this conceptually though

**Review by mirrorcult — COMMENTED** [review]
should opening the valve tank be possible / have different behavior when internals are connected? imo it shouldnt be possible to just hard open it like that if its connected to something, since i think its implied the valve is already slightly open (to allow for breathing)

**Comment by PJB3005** [comment]
Oh my god we need the ability to propel yourself in space by aiming the gas tank so bad PLEASE

**Comment by CrigCrag** [comment]
maybe make airtanks deal damage when launched via gas

**Comment by JoeHammad1844** [comment]
Could confuse players who want to turn on internals and instead completely vent their o2

also, please show a video of you doing this with plasma in the tank

**Comment by deltanedas** [comment]
yeah the verb name should be changed to empty contents or something so its clearer that its not how you breathe out of it

**Comment by Slava0135** [comment]
> Could confuse players who want to turn on internals and instead completely vent their o2
> 
> also, please show a video of you doing this with plasma in the tank

A single tile contains about 100 moles of gas in normal conditions when a plasma gas tank (and others) contain about 2 moles, so you won't even see plasma.

**Comment by Slava0135** [comment]
actually you can see some plasma
Peek 2023-09-05 10-38

**Comment by JoeHammad1844** [comment]
> A single tile contains about 100 moles of gas in normal conditions when a plasma gas tank (and others) contain about 2 moles, so you won't even see plasma.

freeze the plasma super cold so it gets super condensed

**Comment by Slava0135** [comment]
Peek 2023-09-05 10-45

**Review by Partmedia — APPROVED** [review]
Looks good to me in testing. I still think the initial impulse is a little too big for realism-ish purposes, but that's a easy value tweak if you want to do that later.

**Pull request merged**
