### PR TITLE
Salvage expeditions

### PR DESCRIPTION
**Pull request by metalgearsloth**
I have a design doc but it currently has a bunch of uhh stuff all over it so will be made public at some time.
General goal is to have a more PvE combat focused part of salvage and moving hostile mobs off of the current salvage stuff so it's more environmental hazard based. It's also good as upstream to have some kind of basis to work on stuff like NPC pathfinding on planets, weather, grid overlap, planet landing, loading maps over several ticks, or procgen decals so we can code them and ensure they don't bitrot, plus it gives combat more active use outside of stuff like nukies.

Requires https://github.com/space-wizards/RobustToolbox/pull/3944

Flow is that:
- Salvage selects mission from console
- Takes shuttle to planet
- On planet map for <10 minutes
- Comes back (if they don't they die so no loitering).
- Forced RnR period before next mission (so traitors get a chance to engage with their target / if the station has gone to shit they stop missions).

Pretty much deep-rock galactic but in a much more compressed format.
In terms of players engaging with the station it should be similar to salvage atm.

5 missions of varying difficulties get offered with higher tiers being harder and providing more loot. ATM there's 2 mission types:
- Mining -> No dungeons but mobs spawned around the map
- Structure destroy -> Dungeons with target structures

For loot there's 2 varieties:
- Crate spawns using the salvage loot pool, with t3/t4 science parts available.
- Ores as a biome layer.

There's no explicit reward for finishing a mission (so you could just try and only loot instead) but it puts your expedition on a much higher cooldown if you fail.

Also made a bunch of other changes, e.g. to how biomes work to support stuff like infinite mobs on biomes.

UI:
image

Caves:
image

### CODE REVIEW

**Comment by moonheart08** [comment]
the worldgen curse

**Comment by metalgearsloth** [comment]
re-opening coz proggers being made

**Comment by deltanedas** [comment]
why closing all your prs? this seemed somewhat close to completion and wouldve completely revamped salvage gameplay
though if you got real stuff to deal with i get it

**Comment by Emisse** [comment]
hes taking a break stuff will be worked on later

**Comment by deltanedas** [comment]
yeah burnouts a bitch

**Comment by metalgearsloth** [comment]
guess who's back

**Comment by metalgearsloth** [comment]
Imagine if we test-merged haha.

**Comment by metalgearsloth** [comment]
testmerg

**Pull request merged**
