### PR TITLE
Allow EnsureSolution to report if it already existed.

### PR DESCRIPTION
**Pull request by Vordenburg**
## About the PR 

This PR makes the method consistent with EnsureContainer's API.

**Media**

**Changelog**

### CODE REVIEW

**Comment by Elijahrane** [comment]
If you wanted to make this analogous to ensurecomp with "out var" you would get the existing solution if it exists and a new solution if it doesn't

**Comment by mirrorcult** [comment]
this should return `bool` and have an `out Solution`, not the other way around

**Review by mirrorcult — CHANGES_REQUESTED** [review]
above

**Comment by AJCM-git** [comment]
reopen once you have time for this

**Pull request closed without merging**
