### PR TITLE
Replace .20 box for .20 magazine in syn uplink

### PR DESCRIPTION
**Pull request by EEASAS**
## About the PR

I replaced the .20 box in the tot and nukie uplink for a single magazine.
This is for AKMS bringing-back preparations.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The Syndicate has recalled the rifle magazine box and has replaced it for a singular magazine.

### CODE REVIEW

**Comment by Myakot** [comment]
Why did you swap it from 0.30 to 0.20? Was it a typo? If not - the 0.20 box still had a description of having 0.30 ammo (and basicsniperrifle works on 0.30)

**Comment by keronshb** [comment]
So why replace a box of ammo with a singular mag?

**Comment by keronshb** [comment]
@EEASAS Please fix the failed tests and checking to see if you're coming back to this.

**Comment by EEASAS** [comment]
guh its been some time since i've devved for this
hold on i'll try to fix it

**Comment by EEASAS** [comment]
i have no idea why is it conflicting, everything checks out to me

**Comment by keronshb** [comment]
> i have no idea why is it conflicting, everything checks out to me

Did you pull master to your local branch?

**Comment by EEASAS** [comment]
i just did that

**Comment by keronshb** [comment]
One more.

**Comment by EEASAS** [comment]
i have no idea why is it like that i pulled 3 times

**Comment by Vaaankas** [comment]
FYI i already removed the AK mag box in #18011

**Comment by AJCM-git** [comment]
@EEASAS resolve conflicts (try force-pushing after merging master if its still not letting you) (also, is this still necessary after the AK mag box was removed?)

**Comment by AJCM-git** [comment]
re-open once you come back to this

**Pull request closed without merging**
