### PR TITLE
Add a special hardsuit for nukie medic

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

The elite hardsuit is it's own thing and is visually distinct from the other operatives.

Giving the medic their own hardsuit not only fixes recognition issues (being mistaken for security) but also helps give more visual cohesion to all of the operatives.

The hardsuit differs by having a `+`-shaped visor as well as dark green bands along the arms and legs. 

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Nuclear Operative medics now come with a custom hardsuit.

### CODE REVIEW

**Comment by LankLTE** [comment]
Why give it such shitty resistances? Secoff's armor is better than this. You're just encouraging them to throw it into space at their earliest convenience and buy a better suit.

**Comment by LankLTE** [comment]
Nevermind I was looking at the helmet i'm a dumbass

**Comment by EmoGarbage404** [comment]
> Why give it such shitty resistances? Secoff's armor is better than this. You're just encouraging them to throw it into space at their earliest convenience and buy a better suit.

it has identical resistances to the blood-red suit.

**Comment by LankLTE** [comment]
> it has identical resistances to the blood-red suit.

now that I've promptly realized I can't read the word "helmet", I'll put my actual opinion here again:
This is a really weird and unnecessary nerf to the nukie medic while also not solving the recognition issue of the elite hardsuit should it be used elsewhere. I feel just respriting the elite hardsuit is a much, much better solution.

**Comment by commash** [comment]
> > Why give it such shitty resistances? Secoff's armor is better than this. You're just encouraging them to throw it into space at their earliest convenience and buy a better suit.
> 
> it has identical resistances to the blood-red suit.

Doesn't the current Elite Hardsuit have better resistances than the normal blood-red suit? I don't think the agent should be nerfed, this new suit should have the same resistances as the old elite hardsuit.

**Comment by Slava0135** [comment]
i like elite hardsuit more

**Comment by KingOnBudget** [comment]
this looks realy good!!

**Comment by JoeHammad1844** [comment]
good idea and i like the visor, but you should make the green bands white instead because green just doesn't look as good and has less contrast

also make the elite hardsuit purchasable, would be a shame to let it go to waste and you could buy an elite hardsuit in SS13, i think 10TC would be a good price because if it was any higher people would just buy the jug suit instead, or just give the medic hardsuit the elite suit resistances

**Comment by RyanStrudfelt** [comment]
Looks good. But definitely needs the elite hardsuits resistances. Shouldn't be purchasable either.

**Comment by EmoGarbage404** [comment]
updated screenshot with new design

**Comment by LankLTE** [comment]
Still don't see the point in nerfing the medics' hardsuit.

**Comment by JoeHammad1844** [comment]
i like the white patches but i dont like how the entire left arm is white, looks out of place

**Comment by BolloTea** [comment]
What didn't you like about the elite suit?  He is more than recognizable and well suited for a medic.

**Comment by Partmedia** [comment]
I have no comments on the armor value balance changes, only that I think this resprite is a good idea because it's easy to get the old medic hardsuit confused with security.

**Comment by Partmedia** [comment]
Now commenting on the armor balance since apparently discussion on this has ended.

I feel like the nerf to the hardsuit damage modifiers (compared to the elite hardsuit) is acceptable, and intend to merge this. But if this is controversial we can do just only the hardsuit sprite changes (making this parent from the elite hardsuit still) and kick the can down the road.

**Comment by JoeHammad1844** [comment]
i think if we give the medic their own hardsuit then the elite suit should be purchasable, its only really a minor upgrade and the jug suit is available already

**Comment by Partmedia** [comment]
That's fine, let's see how it plays out.

**Pull request merged**
