### PR TITLE
unique satchel grid

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

something i brainstormed ages ago during gridinv.

Satchels now consist of a single 4x4 grid and two 2x4 grids.

## Why / Balance

Satchels have been bag reskins for as long as they have existed. Duffels get the luxury of capacity buffs and slowdown, but satchels don't really have anything unique about them.

This adjusts satchels to be comprised of 3 smaller grids instead of one large one. Notably,
- Satchels now have more capacity than bags, 32 compared to a bag's 28.
- That capacity only allows for more smaller items, as you can't fit two 4x4 items inside the bag, like you could otherwise

This makes satchels ideal for people who just want to squeeze a few more knickknacks into their bag. This is just a little experiment.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

:cl:
- tweak: Satchels have a larger carrying capacity that is divided into pockets.

### CODE REVIEW

**Comment by UbaserB** [comment]
im a satchel user so this is totally going to be different

**Comment by K-Dynamic** [comment]
I wonder if satchels actually do make you harder to hit by like three pixels

**Comment by UbaserB** [comment]
Are there going to be any bonuses along with this change? To uh, balance it out. Otherwise, great PR i hope to keep it for ss14 onwards.

**Comment by UbaserB** [comment]
> it has more capacity than a bag its just split up

im blind

**Comment by Emisse** [comment]
fix test noob

**Comment by Hmeister-fake** [comment]
It should just let you open a second gridinv with the satchel (satchel+belt), makes no sense that it's bigger since it's visually a lot smaller and irl

**Comment by lzk228** [comment]
its a game, not irl :trollface:

**Comment by deathride58** [comment]
cant believe satchels are now a tarkov chestrig

**Comment by deltanedas** [comment]
escape from maintenance

**Comment by DogZeroX** [comment]
Could make the duffel long and not wide

**Comment by mirrorcult** [comment]
1x50 storage

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
test fail is not erroneous there are some satchel fills that are broken now

**Comment by juliangiebel** [comment]
@EmoGarbage404 The test failure seems related. It fails on to fill the detective satchel using storage fill on the spawn and delete all items test

**Comment by Emisse** [comment]
test fail appears to be related mr garbage.

**Comment by notquitehadouken** [comment]
literally me when test was dirty-disposed

**Comment by EmoGarbage404** [comment]
tests fixed (i think)

**Comment by Rainbeon** [comment]
> more bag space without a movement speed debuff... satchel ops is real gonna have to play with this change to see if it's good though I imagine inventory management will be a little bit harder

It gates you off of having too many big items (you can only fit a single 3x3 before it becomes impossible to fit another, while also restricting how many 2x2s you can hold in the process), carrying an item like a pickaxe gates you off from 3x3, some items like shotguns are impossible to put in your bag because there is no space that is 5 in length. I think it's a pretty reasonable trade off for 4 more slots without movement penalty. Overall I like it in concept

**Comment by sugacloud** [comment]
another unnecessary addition to an already inconvenient and disgusting inventory

**Pull request merged**
