### PR TITLE
Make cyborgs hands explosion proof.

### PR DESCRIPTION
**Pull request by Simyon264**
## About the PR

Currently, the beakers in the advanced treatment cyborg module can explode, meaning the cyborg gains 2 hands. This PR fixes that.

## Why / Balance

Free hands are bad for cyborgs.

## Technical details

YAML changes, a new datafield and a change in the BeforeExplosion event.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Simyon
- fix: The hands of cyborgs are now explosion proof. Your beakers wont ever break again!

### CODE REVIEW

**Comment by deltanedas** [comment]
cyborgs shouldnt let anything explode, add a bool to HandsComponent to disable explosion recursion then set it on base borg chassis. this would prevent any similar bugs in the future and reduce prototype bloat

**Comment by Simyon264** [comment]
Sounds solid.

**Review by deltanedas — APPROVED** [review]

**Comment by metalgearsloth** [comment]
Looks like more code just to bypass the fake hands hacks.

**Review by metalgearsloth — DISMISSED** [review]
As shitcodey as innatetools are why aren't the beakers just explosion resistant instead of adding overhead to every hand.

**Comment by Simyon264** [comment]
That was what I had originally until I was told otherwise.

**Comment by deltanedas** [comment]
someone adds c4 to a saboteur module now that has to be made explosion proof etc vs just have the hands not recurse

**Review by mirrorcult — APPROVED** [review]

**Comment by metalgearsloth** [comment]
> someone adds c4 to a saboteur module now that has to be made explosion proof etc vs just have the hands not recurse

The only reason borgs use hands is to use fake entities in a UI but tightly coupling this is a bad idea. See also the hacks trying to add more hands just to handle construction.

**Comment by deltanedas** [comment]
ngl a lot of funnies could be fixed by modules having a list of hand whitelists as well as items, then if the entity is removed you can only pick up an entity that matches the whitelist. can remove lingering stacks entirely in favour of a material sheet whitelist, then borgs can pick whatever set of materials they want to work with.

**Pull request merged**
