### PR TITLE
Add advanced APC mechanics

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
- Adds the ability to construct advanced APC units (High, Super, Hyper)
- APC circuit board boards are unlocked through research
- Adds a tier 2 Advanced Power Generation research
- Moved Super Pacman to tier 2 research(primarily to insensitive a new category) along with Hyper APCs 
- Advanced APC circuit boards are printed at an autolathe after being researched
- Added high and super boards to rare chance category on tech board spawner
- Fixes issue where deconstructing a pre-mapped advanced APC would yield a standard board and rebuilding the APC would result in a downgrade. 

## Why / Balance
These have always been available to mappers but they would be useful to players, especially when replacing pre-mapped advanced APCs. Also adds more depth to the power generation research tree with potential for future expansion. 

## Technical details
n/a

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**
:cl: Velcroboy
- add: Added advanced APCs! More power management options for engineers. Research then print at an autolathe near you!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
aren't higher capacity APCs conventionally done via higher-capacity power cells?

**Comment by IamVelcroboy** [comment]
> aren't higher capacity APCs conventionally done via higher-capacity power cells?

APCs don't currently utilize power cells. But if that's the direction you want to go, I could add them to the construction process.

Otherwise they just use circuit boards, and deconstructing an advanced APC would give you a standard board. So this, at least, changes that.

**Comment by chromiumboy** [comment]
> > aren't higher capacity APCs conventionally done via higher-capacity power cells?
> 
> APCs don't currently utilize power cells. But if that's the direction you want to go, I could add them to the construction process.

As power cells are now machine parts, I think this is the way to go, especially since using higher tier power is how the battery capacity of the substation and SMES are improved.

**Comment by IamVelcroboy** [comment]
> > > aren't higher capacity APCs conventionally done via higher-capacity power cells?
> > 
> > 
> > APCs don't currently utilize power cells. But if that's the direction you want to go, I could add them to the construction process.
> 
> As power cells are now machine parts, I think this is the way to go, especially since using higher tier power is how the battery capacity of the substation and SMES are improved.

It does make sense. I'll adjust the construction graph to include those.

**Comment by IamVelcroboy** [comment]
The one weird thing about using power cells is their capacities don't line up.
 
 Ex: I use a small cell for standard APC, the cell has a charge of 360, the APC is 50,000
 High = 720/100,000
 Super = 1080/150,000
 Hyper = 1800/200,000
 
 It's just kind of  a weird discrepancy.

**Comment by chromiumboy** [comment]
Power balance in this game is kinda whacky, but that's a whole other problem. The ratios would remain the same though, except for hyper power cells

**Comment by IamVelcroboy** [comment]
So just, ignore it for now?

**Comment by chromiumboy** [comment]
Yeah, just make it so that t1 power cell = 50K capacity, t2 power cell = 100K, etc with an UpgradeAPCCapacityComponent and System (see UpgradeBatteryComponent and System)

**Comment by IamVelcroboy** [comment]
Wow!, isn't that going to throw off everything that uses power cells though? Like flashlights, hard hats, some suits, etc?

**Comment by chromiumboy** [comment]
> Wow!, isn't that going to throw off everything that uses power cells though? Like flashlights, hard hats, some suits, etc?
> 
> Basic handheld items will never run out of power

No, don't change the base capacity of the power cells. Use the component-system I suggested to make it so that when a certain teir power cell is in the APC, the APC capacity is set to appropriate value

**Comment by IamVelcroboy** [comment]
> > Wow!, isn't that going to throw off everything that uses power cells though? Like flashlights, hard hats, some suits, etc?
> > Basic handheld items will never run out of power
> 
> No, don't change the base capacity of the power cells. Use the component-system I suggested to make it so that when a certain teir power cell is in the APC, the APC capacity is set to appropriate value

Ohhhhhhh...yes, I can do that. That makes sense.

**Comment by Emisse** [comment]
these were added with the intention that they wouldnt be obtainable in game, why do you think theyd be a good fit in the game right now

**Comment by IamVelcroboy** [comment]
> these were added with the intention that they wouldnt be obtainable in game, why do you think theyd be a good fit in the game right now

I guess I wasn't aware that was the intention. However, it creates a discrepancy when we map them in. Because we generally are mapping them in areas that have increased power draw and need a bigger source to draw from. When these are destroyed or replaced for whatever reason, they can only be downgraded. Except, the players don't even know that because, to them, an APC is an APC.

I also just thought this would provide a nice upgrade path. One more thing for engineers to tinker with and one more way to balance power as additional power draws get added throughout the round.

**Comment by IamVelcroboy** [comment]
So if [this](https://github.com/space-wizards/space-station-14/pull/24413) is a thing now. What direction should I move this in? Obviously, upgrading is out the window.

**Comment by deltanedas** [comment]
working like smeses and using a powercell to determine the capacity seems fine to me

**Comment by IamVelcroboy** [comment]
> working like smeses and using a powercell to determine the capacity seems fine to me

Looks like that's being removed

**Comment by IamVelcroboy** [comment]
Question: Would this be better if I removed the research elements and just had higher tier APCs drop respective boards and/or add advanced APC boards to some rare loot pools?

Another idea is to increase the cost of higher tier boards.

**Comment by UbaserB** [comment]
> > these were added with the intention that they wouldnt be obtainable in game, why do you think theyd be a good fit in the game right now
> 
> I guess I wasn't aware that was the intention. However, it creates a discrepancy when we map them in. Because we generally are mapping them in areas that have increased power draw and need a bigger source to draw from. When these are destroyed or replaced for whatever reason, they can only be downgraded. Except, the players don't even know that because, to them, an APC is an APC.
> 
> I also just thought this would provide a nice upgrade path. One more thing for engineers to tinker with and one more way to balance power as additional power draws get added throughout the round.

in core i never used any apc other than basic

**Comment by IamVelcroboy** [comment]
> in core i never used any apc other than basic

Ok...?

**Comment by Peptide90** [comment]
The reason I never implemented construction graphs for APCs is because they don't pass through the state of the cell you use. And changing the cell shouldn't involve deconstructing it as then you go through entity changes.

The values for cells vs power storage also don't line up due to balance and the extreme power needs of stations vs objects. All components on these should be the same except the cells.

**Comment by IamVelcroboy** [comment]
> Using cells was recommended above and the path I was going to take until [this](https://github.com/space-wizards/space-station-14/pull/24413/files#diff-3a397e793e8f210a99675062aa318ab67fa8a6b46e9ee175cbf3cb9db751e113) effectively removed the cell upgrading system. 

Which is why I started asking for more clarity on direction. Either I'd need to bring that particular bit of code back for this, or change gears and not use cells, but instead use different circuit boards. Or...open to other suggestions...?

**Comment by Peptide90** [comment]
> > The reason I never implemented construction graphs for APCs is because they don't pass through the state of the cell you use. And changing the cell shouldn't involve deconstructing it as then you go through entity changes.
> 
> > The values for cells vs power storage also don't line up due to balance and the extreme power needs of stations vs objects. All components on these should be the same except the cells.
> 
> Using cells was recommended above and the path I was going to take until [this](https://github.com/space-wizards/space-station-14/pull/24413/files#diff-3a397e793e8f210a99675062aa318ab67fa8a6b46e9ee175cbf3cb9db751e113) effectively removed the cell upgrading system.
> 
> Which is why I started asking for more clarity on direction. Either I'd need to bring that particular bit of code back for this, or change gears and not use cells, but instead use different circuit boards. Or...open to other suggestions...?

Is it really machine upgrading if you're swapping out one part and it produces a different end machine? That's the way I went on my branch was just one graph with lots of end nodes based on the prototype of cell used. It's just hacky because as I say it won't pass through the cell charge so to stop abuse you need the APC to spawn empty of charge, which kinda defeats swapping out dead cells. 

The system for making APCs needs changed either to allow passing through the stat from the container or to not use construction as it is.

**Comment by IamVelcroboy** [comment]
> Is it really machine upgrading if you're swapping out one part and it produces a different end machine? 

All I know is that cell swapping was removed for substations/SMES. So, I question if it will be accepted for APCs...

**Comment by AJCM-git** [comment]
> > Is it really machine upgrading if you're swapping out one part and it produces a different end machine?
> 
> All I know is that cell swapping was removed for substations/SMES. So, I question if it will be accepted for APCs...

Swapping the battery to upgrade is fine for APCs, but if you end up doing that the battery should actually interface with the APCs by making the charge is actually based on the battery capacity, there will probably be some balancing and tweaks to accomodate this but it's possible.
Another (maybe harder?) option is to add a single "upgraded" APCs (like the upgraded lathes) with huge bonuses and negative effects that can be worked around (this would require some creativity to figure out some cool effects tho)

**Review by AJCM-git — CHANGES_REQUESTED** [review]
read my previous comment

**Comment by IamVelcroboy** [comment]
Due to IRL and other commitments I won't have any time to work on this for at least a month or more. I am closing for now. Will reopen if/when I get more time.

**Pull request closed without merging**
