### PR TITLE
Cleans up ClothingShoesBootsMagSyndie in magboots.yml

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

uh... For some reason the ClothingShoesBootsMagSyndie had an Explosive component and there does not seem to be a way to set it off
## Why / Balance

:)
## Technical details

remove the Explosive component from ClothingShoesBootsMagSyndie
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by beck-thompson** [comment]
They have hidden explosives so hard to find you can't even activate them

**Comment by deltanedas** [comment]
i think its because it can be made into a maxcap like jetpacks/gas tanks

**Comment by Cojoke-dot** [comment]
> i think its because it can be made into a maxcap like jetpacks/gas tanks

mmm... ok... that makes sense. I checked the jetpack yml but forgot to look at its children...

**Comment by deltanedas** [comment]
i believe it can also inherit magboots just fine to remove even more duplication

**Comment by Cojoke-dot** [comment]
mmm... I broke something...

**Comment by Cojoke-dot** [comment]
> i believe it can also inherit magboots just fine to remove even more duplication

It would remove the tag duplication, that's about it. I'm more nervous about doing it for the magboots because it has the Appearance + GenericVisualizer components and I'm not sure what they would affect

**Comment by deltanedas** [comment]
validboots dont have jetpack visuals its just copy pasted magboot visuals

**Comment by Cojoke-dot** [comment]
> validboots dont have jetpack visuals its just copy pasted magboot visuals

the bloodred mags don't have an item sprite attached to them, so they inherit the sprite from the parented base jetpack, I found a fix so its whatever

**Comment by Cojoke-dot** [comment]
Mmm... I need to do more cleanup on this file...

**Pull request merged**
