### PR TITLE
Stealth Price Reduction

### PR DESCRIPTION
**Pull request by HerCoyote23**
## About the PR

Reduces the price of a bunch of stealth items, cause they're VERY pricey right now.
## Why / Balance

Should make stealth syndicate play more common/geared. Also the prices were just kinda too high earlier.

image
This kit(Chameleon, Storage, Jammer, Voice Changer) price goes from 29 -> 18tc
## Technical details

Storage implanter: 12->8
Radio Jammer: 5->4
Chameleon Kit: 6->4
Voice Changer Mask: 6->2

Clown Costume: 4->2 (You could pretty easily just get one from a clown vend. Or buy chameleon clothes.)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Syndicate has grown tired of losing overconfident "Loud" agents, and has reduced their stealth gear prices to encourage a more sneaky approach.

### CODE REVIEW

**Comment by KompaniLinge** [comment]
Good PR, all price changes seem fair IMO.

**Comment by NancokPS2** [comment]
You mean i can have an invisible fanny pack without spending most of my TC? What a joyous day.

**Comment by HoidC** [comment]
we are SO back
voice mask change definitely needs to happen that the price was ever increased from 4-6 in the first place was stupid

**Comment by deltanedas** [comment]
8tc storage implant my beloved
implant + 6 fish to kill whoever you want and stash their gear :trollface:

**Comment by Emisse** [comment]
sure

**Comment by CrigCrag** [comment]
storage implants make steal objectives really uninteractive, even moreso on MRP where random checking for syndie items you have no blatant evidence for isn't a thing.

**Comment by KompaniLinge** [comment]
> storage implants make steal objectives really uninteractive, even moreso on MRP where random checking for syndie items you have no blatant evidence for isn't a thing.

I'd disagree, mainly due to the fact sala-sec is much better at tying 2-2 together, and the fact that even if they cant particularly find the stolen item, they can oftentimes find the perpetrator, due to the fact the detectives and security officers on salamander can more often crack cases the in LRP Sec.
Plus, I've seen more people on salamander go loud then stealth for most shifts I can recall there being antags on, most of them are quite bomb-happy.

As for being "un-interactive", I dont quite get the point of this, its a 20unit fannypack with no real use other then storing the fruits of your labour.
The interactivity comes from actually stealthily grabbing the item you need, or coming up with a plot to obtain it.

**Comment by Ilya246** [comment]
but what about the agent ID price

**Comment by commash** [comment]
> but what about the agent ID price

Agent ID is already a very cost efficient buy at 3 TC. It doesn't really need a change.

**Comment by NancokPS2** [comment]
Is it? It depends on other items to be of any use, and it can be easily identified when someone tries to use it in their hand.  
  
It also grants no real benefit until you use it in someone's stolen ID. And at which point it's still barely better than an emag despite the work and risk required to copy a high value ID card.  
  
It's just so hard to even benefit from it. Yet it is even more costly than no-slips and almost as expensive as a chameleon kit.

**Pull request merged**
