### PR TITLE
Moose update [ResearchAssistant]

### PR DESCRIPTION
**Pull request by 778b**
## About the PR
Added ResearchAssistant to Moose map, also added missed BiomassReclaimer (it was in previous versions of the map)

**Media**
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: 778b
- add: Added Research Assistant to Moose!

### CODE REVIEW

**Comment by Cheackraze** [comment]
ive got a bigger update coming to moose here in just a bit, thanks for catching the biomass reclaimer though.  I usually do updates every 1-2 weeks depending on what we get for content so feel free to @me in the discord if you ever find anything else needing changes

**Comment by 778b** [comment]
> ive got a bigger update coming to moose here in just a bit, thanks for catching the biomass reclaimer though. I usually do updates every 1-2 weeks depending on what we get for content so feel free to @me in the discord if you ever find anything else needing changes

Ive no any merge conflicts, and didnt found any PR about Moose update, why u didnt create draft PR?

**Comment by Cheackraze** [comment]
> > ive got a bigger update coming to moose here in just a bit, thanks for catching the biomass reclaimer though. I usually do updates every 1-2 weeks depending on what we get for content so feel free to @me in the discord if you ever find anything else needing changes
> 
> Ive no any merge conflicts, and didnt found any PR about Moose update, why u didnt create draft PR?

I made a PR last night.  I update my maps about once a week, there's no reason for my to have a perpetual draft going

**Comment by moonheart08** [comment]
Contents match existing merged PR, closing.

**Pull request closed without merging**
