### PR TITLE
Time requirements for ERT, CBURN and Death Squad ghost roles

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

This pr creates new entities ERT ghost roles with following time requirements:
- Death Squad operative - 10 overall hours
- ERT Leader - 5 command hours
- ERT Engineer - 10 engineering hours
- ERT Medic - 10 medical hours
- ERT Security officer - 10 security hours
- CBURN operative - 10 overall hours

## Why / Balance

The point is to not give the role to players who is not familiar with their role and to prevent situations when i.e. engineer wouldnt know anything about power supply or something

## Technical details

no

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
ADMIN:
- add: Added ERT roles variations with time requirement.

### CODE REVIEW

**Comment by PoorMansDreams** [comment]
Only change I would make is to Add more time, like 10 more hours on all of em rahhhh

**Comment by IProduceWidgets** [comment]
I don't know if this one is a good idea. The truth is that when most of these roles get added the best indicator of what to add is ghost count. This makes that much less helpful.

**Comment by TheDoctor1977** [comment]
As someone who played a DS operative in what was literally their third round of SS14 ever and was almost instantly infected and killed by the zombies we were fighting because I didn’t know how anything worked, I approve.

**Review by Plykiya — CHANGES_REQUESTED** [review]
Admins want the option to have an entity with the time requirement and without the time requirement. So create another entity with the time requirement and add an appropriate suffix to differentiate the spawns.

**Comment by retequizzle** [comment]
while my stance at the moment is leaning no but ultimately willing to have unrestricted options for admins to use instead (so i can completely ignore the role timer restriction being proposed here), i have to point something out

> The point is to not give the role to players who is not familiar with their role and to prevent situations when i.e. engineer wouldnt know anything about power supply or something

brother you do realize these are admin only spawns, at which point if the admin is spawning them they're likely around to oversee if something goes sideways and further intervention is needed

all this PR is really coming across as is limiting the amount of players who would be eligible for ghost roles as they're spawned, so there's not as much competition for them from everyone else and i'm not sure i agree with that

**Comment by LordEclipse** [comment]
Honestly, I'd only really support it for the ERT Leader role at most, but even still, usually when I spawn an ERT I don't particularly care about if they do or don't succeed, it's about the experience, not victory or defeat. If you could make it an option somehow when spawning them, maybe a role timer variant instead of making them ONLY have role timers, because otherwise if I have 1 ghost, and I have 1 ERT and they want to be the ERT but can't, I'm most likely gonna setmind them into the ghost role anyway, without concern if they are competent or have enough time.

**Comment by lzk228** [comment]
> Admins want the option to have an entity with the time requirement and without the time requirement. So create another entity with the time requirement and add an appropriate suffix to differentiate the spawns.

applied

**Comment by Errant-4** [comment]
Hi, we have discussed this internally and there was interest, but new role timers are also on the Freeze list. (It was added after you have already made this PR, so you did not "miss this", rather the situation has changed).
It was in the end decided not to add these new role time requirements at this time, since we intend to review and balance the existing ones first and don't want to add new ones before that. We will probably include some version of this in the rework, but if we don't then you are welcome to reopen this once role time requirements have been removed from the freeze list. Either way, thank you for your contribution.

**Pull request closed without merging**
