### PR TITLE
Pill destruction

### PR DESCRIPTION
**Pull request by freeman2651**
## About the PR

Adds Damageable and Destructible components to pills. Pills can be smashed open to extract the goodness within or observe if they are more suspiciously colored then they should be. This makes it a less attractive option to store them in the open where they could be damaged by the environment or passing troublemakers. Due to spilling behavior, smashing pills open also tends to cause the pill-smasher to get covered in whatever was in them.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image

**Changelog**

:cl:
- tweak: Pills are now destructible.

### CODE REVIEW

**Comment by asperger-sind** [comment]
1. wait till this is merged
2. roll antag and place an explosive next to chem's pillpile
3. ???
4. profit :trollface:

**Comment by EmoGarbage404** [comment]
Based an pill-hating brained.

also since when does github have the fucking troll emoji

**Comment by GoodWheatley** [comment]
I will give you 1 (one) (uno) cookie if you make pills melt when splashed with water so I can grab a glass from the bar and ruin the chemistry desk in one throw

**Comment by deltanedas** [comment]
> also since when does github have the fucking troll emoji

@EmoGarbage404 i think it was added for april 1th since i saw it some time after that :trollface:

**Comment by deltanedas** [comment]
> I will give you 1 (one) (uno) cookie if you make pills melt when splashed with water so I can grab a glass from the bar and ruin the chemistry desk in one throw

potassium pill:

**Comment by mirrorcult** [comment]
very good

**Comment by deltanedas** [comment]
its easier mess to clean up when chem is bombed you just have a giant puddle and/or fireball to clean up rather than thousands of pills

**Comment by notquitehadouken** [comment]
well what if there's like 800 pills on the table and now chem gets to make them all again

**Comment by mirrorcult** [comment]
if they enjoy the button pushing job so much they'll make 800 of them then they will be thrilled to be given the opportunity to make 800 more

**Comment by OctoRocket** [comment]
then they can learn to use pill bottles next time :)

**Comment by deltanedas** [comment]
those will still be spilled pro
button pushera rise up :trollface:

**Comment by Kromabae** [comment]
finally the death of pill piles maybe :D

**Pull request merged**
