### PR TITLE
Blink

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

*blinks*

## Why / Balance

*blinks*

## Media

https://github.com/user-attachments/assets/d630e135-88c5-4f1e-8245-6a54e1ecee67

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl, let people find out themselves :trollface:

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Like the emote, not so much the sound

**Comment by Dutch-VanDerLinde** [comment]
The hell is that cartoony ass sound effect

**Comment by Krovotushka** [comment]
Type of sound you could hear from Drake while blinking

**Comment by TheShuEd** [comment]
Maybe add this sound only for mime?

**Comment by baddiePRO** [comment]
peak

**Comment by lzk228** [comment]
new emote sprite
blink

**Comment by ps3moira** [comment]
Should be saved for mime, there's no reason there should be a sound effect for rest of crew.

**Comment by Kadeo64** [comment]
it's funny but there needs to be a cooldown on the sound effect or else it's just going to be spammed like screams and yawns

**Comment by lzk228** [comment]
> it's funny but there needs to be a cooldown on the sound effect or else it's just going to be spammed like screams and yawns

this is general thing and out of scope for this pr

**Comment by lzk228** [comment]
weh, that's not what i wanted to do, so if anyone other want to continue it, you are welcome

**Pull request closed without merging**
