### PR TITLE
add lizard speech bubble

### PR DESCRIPTION
**Pull request by lunarcomets**
## About the PR
Changed the speech indicator of the reptilian to ones made by @AmalgoMyte, changing from the default indicator sprites.

## Why / Balance
The moth, arachnid, and slime species - all races that differ significantly from the more human races - all have unique speech indicators respective to the species. The reptilian race is significantly different enough from human to warrant it's own speech bubble, as well.

## Media

https://github.com/space-wizards/space-station-14/assets/140772713/423edc03-fe9e-4ea4-84d4-568bac26d0bb

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: lunarcomets | AmalgoMyte
- tweak: Gave the local lizards and kobolds their own speech bubbles!

### CODE REVIEW

**Comment by UbaserB** [comment]
your PR description is broken (i see no images too)

**Comment by lunarcomets** [comment]
mg, closing until tomorrow me can fix

**Comment by lunarcomets** [comment]
fixed description, added media

**Comment by MrGreen006** [comment]
Do kobolds have the lizard speech bubble as well?

**Comment by lunarcomets** [comment]
> Do kobolds have the lizard speech bubble as well?

that they do not but they probably should

**Comment by AmalgoMyte** [comment]
I think that the media preview is amazing..! You rock, dear.

**Comment by AmalgoMyte** [comment]
So far, I think that it being in a dark environment is still good for the sprite as well. I think this is good, for what it is.

**Comment by Flareguy** [comment]
Two things:
1. The lump in the middle is kinda weird, I'd probably remove it.
2. The color should definitely be brighter, it doesn't stand out enough at a distance I think.

**Comment by AmalgoMyte** [comment]
> Two things:
> 
> 1. The lump in the middle is kinda weird, I'd probably remove it.
> 2. The color should definitely be brighter, it doesn't stand out enough at a distance I think.


Thank you for the input, however I will wait for further inputs before deciding on any changes.

**Comment by Emisse** [comment]
hes an art director

**Comment by AmalgoMyte** [comment]
> hes an art director

Noted- I'll be working on it, then.

**Comment by AmalgoMyte** [comment]
> hes an art director

Apologies for not noticing sooner. I'm not really on here much.

**Comment by lunarcomets** [comment]
updated media

**Comment by lunarcomets** [comment]
@Flareguy thoughts?

**Comment by metalgearsloth** [comment]
Looks like he better have those thoughts on master.

**Pull request merged**
