### PR TITLE
Antimatter Engine Crates

### PR DESCRIPTION
**Pull request by 20kdc**
This means that the station should be able to get power relatively easily.
Granted, magical generators mean that's not a concern right now, but still.
Also note that the AME seems to need at least 4 core tiles to be able to perform stable injection. I haven't adjusted this in case it's according to plan.
Price values are 1234 because I don't know what the conversion rate is.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Good PR, but please adjust the prices of the crates to something you think is sensible at least and put the descriptions on the cargo yaml as well.

**Comment by 20kdc** [comment]
I don't know what sensible prices are since I'm not sure of the unit scale relative to SS13 or what other guidelines to use. "1234" is thus an obvious placeholder.
Will fix descriptions immediately.

**Comment by SweptWasTaken** [comment]
1.5k for engine parts 600 for jars 500 for controller :P

**Comment by 20kdc** [comment]
Ah, thanks. Done.

**Pull request merged**
