### PR TITLE
Make the heart soap not smell like condoms

### PR DESCRIPTION
**Pull request by leonardo-dabepis**
## About the PR

Changed the scent of the heart soap so that it smells like strawberries instead of condoms.
## Why / Balance

Most servers have rules against ERP, so it feels strange for there to be a reference to condom scent in the base game because it is an explicit sexual reference.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Soap no longer smells like condoms.

### CODE REVIEW

**Comment by deltanedas** [comment]
soap erp gang its joever...

**Comment by UbaserB** [comment]
why was there something like that in the game files lol..

**Comment by Emisse** [comment]
ss13 port

**Comment by CatMagic1** [comment]
16 and over audience when they see the word condom:

**Pull request merged**
