### PR TITLE
Task/fix nightvision huds

### LINKED ISSUE #18639: sechud is night vision
## Description

job icons are visible in the dark
**Reproduction**

wear sechud and have nothing in your active hand to see job icons
**Screenshots**

**Additional context**

additionally, secglasses arent hud, which seems strange to me as they did in ss13

### LINKED ISSUE #24426: Sechuds see through invisibility
## Description
you can see space ninjas real

### LINKED ISSUE #24905: Sec glasses and all other job/role icon seeable in dark
## Description
Sec, Med glasses and role icon like revo or zombie seeable in dark placeses.

**Video**

https://github.com/space-wizards/space-station-14/assets/59264914/c4fd6a0a-cb11-44c7-b17c-6910af2e1cd8

https://github.com/space-wizards/space-station-14/assets/59264914/1cd89db6-89a3-4025-a8c9-805a578085a8

**Additional context**
It's like nightseeing glasses what makes hiding in dark just pointless or vice versa zombie and revo can be more confident when know how much they and where they in dark room.

### PR DESCRIPTION
**Pull request by PrPleGoo**
## About the PR
Changed most HUDs so they don't act as night vision.

## Why / Balance
fixes #24905
fixes #24426
fixes #18639

## Technical details
Added a field to the StatusIcon prototype.
In the icon render code, unset the "unshaded" shader if the icon has the field "IsShaded" set to true.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Nope

**Changelog**
:cl:
- tweak: The medical HUD's brightness now scales with lighting again.
- tweak: Most HUD icon's brightness now scale with lighting.

### CODE REVIEW

**Comment by deltanedas** [comment]
isnt there another pr doing this

**Comment by PrPleGoo** [comment]
> isnt there another pr doing this

Not that I could find

**Comment by Hmeister-real** [comment]
you should put "fixes" before the issues so that they close if this is merged. Great PR, this really needed to be fixed

**Comment by gordod3** [comment]
https://github.com/space-wizards/space-station-14/issues/24905 not fixed enough - revo and zombie still see each other in dark places, but finally SeC and Med glasses work fine, thanks!

**Pull request merged**
