### PR TITLE
Battle mechs

### PR DESCRIPTION
**Pull request by ThunderBear2006**
## About the PR

Draft for mechs specialized in battle, will make pretty later. Heavily WIP

**Todo**
Rough summary, might be added too later on (? == Not sure if planned yet)

- [ ] Marauder
  - [X] Fire protection
  - [ ] Thrusters
  - [ ] Smoke grenade
  - [x] Punching?
  - [ ] Punch stunning
- [ ] Ammo counter?
- [ ] Switch fire mode action

- [ ] Mech guns , LMGS, SMGS etc.
- [ ] Mech lasers
- [ ] Anti mech weaponry
- [ ] Mech armor

- [ ] Seraph
- [ ] Dark gygax?
- [ ] Mauler?
- [ ] Ear candy ("All systems nominal")

**Media**

Below is an EXAMPLE of how a weapon may be installed/used within a mech.
the weapon demonstrated is a copy paste of the base SMG prototype for debug purposes, the mech may or may not actually be equipped with an SMG in the future

https://github.com/space-wizards/space-station-14/assets/100388962/ad1c0366-ed5d-44b8-8245-f71fe1e7886c

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by deltanedas** [comment]
ion rifle dear god

**Comment by JoeHammad1844** [comment]
durand t3 research :trollface:

**Comment by HoidC** [comment]
finally, titanfall 2 in spessgame

**Comment by Jezithyr** [comment]
Looks pretty sick! If you need any help with code support ping me on discord ;)

**Comment by Boaz1111** [comment]
I was working on combat mechs too, but didn't get the weapons on mechs to work, how'd you do it?

**Comment by AJCM-git** [comment]
Closing this due to inactivity, just comment if you are still working on it and I will gladly re-open

**Pull request closed without merging**
