### PR TITLE
Added Barozine Recipe

### PR DESCRIPTION
**Pull request by noverd**
## About the PR

I have added the Barozine recipe. Barozine can now be synthesized in a chemical dispenser
Leporazine + Inaprovaline + Siderlac = Barozine
Why is leporazine in the recipe? Because Leporazine and Barozine are similar. They are needed for the survival of an astronaut in outer space.
Why is Inaprovaline in the recipe? I think if Inaprovaline is used to stabilize the patient, why not to stabilize the pressure

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Barozine Recipe

### CODE REVIEW

**Comment by Cheackraze** [comment]
Barozine should never be craftable, it's way too strong of a chem

**Comment by noverd** [comment]
Barosin needs help from botanists to create, and the recipe itself is complex.

**Comment by Interrobang01** [comment]
> Barozine should never be craftable, it's way too strong of a chem

If it's too strong, add plasma or carpotoxin to the recipe. Personally I think the difficulty here alright but I don't have much experience with barozine.

**Comment by Cheackraze** [comment]
It soesnt matter how difficult it is to make, its too strong of a Chem.

**Comment by Interrobang01** [comment]
> It soesnt matter how difficult it is to make, its too strong of a Chem.

Add noct or a stupid temperature requirement? Randomize the recipe each game? It's possible to balance chemical power with obtuse recipes.

**Comment by noverd** [comment]
I can further complicate the recipe with carpotoxin

**Comment by noverd** [comment]
It will be difficult for chemists to make it, since botanists do not always do what chemists want

**Comment by noverd** [comment]
Barozine did not have a recipe, only because he is only in ss14

**Comment by Cheackraze** [comment]
Barozine is only to be found in space pens.  It's effects are too powerful to be player crafted, regardless of complexity

**Comment by Interrobang01** [comment]
> Barozine is only to be found in space pens.  It's effects are too powerful to be player crafted, regardless of complexity 

I don't have any experience with baro and need an example, what exactly about it is so strong? For me it just seems to give you a seizure and some pressure immunity for a few minutes as it slowly deals burn damage.

**Comment by noverd** [comment]
> Barozine is only to be found in space pens. It's effects are too powerful to be player crafted, regardless of complexity

most chemists won't brew it

**Comment by Cheackraze** [comment]
> > Barozine is only to be found in space pens.  It's effects are too powerful to be player crafted, regardless of complexity
> 
> I don't have any experience with baro and need an example, what exactly about it is so strong? For me it just seems to give you a seizure and some pressure immunity for a few minutes as it slowly deals burn damage.

It allows you to survive space with almost 0 damage, it's an unbalanced Chem that should not be craftable.

And if "most chemists won't brew it" then why does it need to be made anyway?  This is a terrible change for balance

**Comment by noverd** [comment]
> > 
> 
> It allows you to survive space with almost 0 damage, it's an unbalanced Chem that should not be craftable.
> 
> And if "most chemists won't brew it" then why does it need to be made anyway? This is a terrible change for balance

If you add carpotoxin to the recipe, then I think you won’t make much of it

**Comment by Cheackraze** [comment]
> > > 
> > 
> > 
> > It allows you to survive space with almost 0 damage, it's an unbalanced Chem that should not be craftable.
> > And if "most chemists won't brew it" then why does it need to be made anyway? This is a terrible change for balance
> 
> If you add carpotoxin to the recipe, then I think you won’t make much of it

Carpotoxin is trivial to obtain, and is usually available within 5 minute of a round.

Again, that's besides the point that Barozine should not ever be made craftable regardless of the ingredients

**Comment by Interrobang01** [comment]
> It allows you to survive space with almost 0 damage, it's an unbalanced Chem that should not be craftable.

You can also survive space with almost 0 damage with an emergency suit, and you can find those all over. Space isn't that big a deal.

**Comment by Cheackraze** [comment]
> > It allows you to survive space with almost 0 damage, it's an unbalanced Chem that should not be craftable.
> 
> You can also survive space with almost 0 damage with an emergency suit, and you can find those all over. Space isn't that big a deal.

And emergency suits have drawbacks, these things we call balance.  Baro is unbalanced to shit, on purpose. It should in no way ever be craftable.

**Comment by Interrobang01** [comment]
Look, let's just discuss this in #ideamen, alright?

**Comment by noverd** [comment]
I replace inopravlin with carpotoxin in the recipe

**Comment by noverd** [comment]
1 Lepos
1 Siderlak
1 Carpotoxin
converted into 1 unit of barozine

**Comment by deltanedas** [comment]
how to do unprotected eva like a BOSS
1. get bicaridine
2. eat it like ice cream
3. you can survive!!!

barozine kinda useless for master tiders

also webedit gaming

**Comment by moonheart08** [comment]
Webedit PR + Breaking intentional game design.

**Comment by noverd** [comment]
ok

**Pull request closed without merging**
