### PR TITLE
Refresh Lobby Info Box

### PR DESCRIPTION
**Pull request by Radosvik**
Update the Lobby Info Box[UpdateInfoText()] when PlayerStatusChanged()is called

## About the PR 
The PR #7402 added player count to the lobby info box, but I did not realize that it didn't update for the client as more players joined the server. This PR added UpdateInfoText() to the PlayerStatusChanged() method so that whenever that occurs the Info Box will refresh.
Because of this, the Info Box will now also display the correct map in the box when the map changes in lobby. (If PlayerStatusChanged is called)

Update:
I made UpdateInfoText() from the class GameTicker a public method so that I could call it elsewhere.

It will now  refresh when either CreateStandardVote() is called, the ForcePreset command is used, or a map changes due to TrySelectMap(), ForceSelectMap(), or SelectRandomMap().
**Screenshots**

https://user-images.githubusercontent.com/65792927/163608479-435a20ae-3a09-437f-8099-f821a7bb53ae.mp4

**Changelog**

:cl:
- tweak: Lobby Info Box now refreshes when needed.

### CODE REVIEW

**Comment by Radosvik** [comment]
For the Reviewers there is also the problem that when a Client Disconnects it doesn't display the correct player count and is off by one. I have been trying to dig around and resolve that issue, but I have so far failed. Any suggestions?

**Review by Veritius — APPROVED** [review]
lgtm

**Comment by mirrorcult** [comment]
> Because of this the Info Box will now also display the correct map in the box when the map changes in lobby. (If PlayerStatusChanged is called)

shouldnt the map changing also call `UpdateInfoBox` then?

**Comment by moonheart08** [comment]
> > Because of this the Info Box will now also display the correct map in the box when the map changes in lobby. (If PlayerStatusChanged is called)
> 
> shouldnt the map changing also call `UpdateInfoBox` then?

The map will only change when the playercount does under rotation mode. Vote maybe should though.

**Comment by Radosvik** [comment]
When I tried to do both of those things before making this PR, I got frustrated because it was a private method. Looking back at it now though, I can get that added in. Just to be sure though, it is fine to make UpdateInfoText() a public method right?

**Comment by Radosvik** [comment]
Should I put all of the tweaks under one tweak in the CL?

**Comment by mirrorcult** [comment]
ye, and it should be player facing (no mention of like specific methods/variables)

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
