### PR TITLE
kettle tweaks

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- removed OrGate since i think it was breaking ci even tho its migrated???
- removed (hopefully) all the funky components that shouldnt be serialized
- added 2 salv spawns (people commonly spawn inside eachother) and expedition/shuttle console to salv

also fixed warning from saltern having ihs gloves

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
real :trollface:

**Comment by metalgearsloth** [comment]
@Cheackraze FYI

Also what is that diff, had it not had new entities format saved yet.

**Comment by deltanedas** [comment]
it should have since you commited the resave command but idk

**Comment by deltanedas** [comment]
@metalgearsloth ci fixed!!!!!!!

**Comment by Cheackraze** [comment]
Thanks @deltanedas I think that's the only thing on my list to update kettle for.  I still want to do a re-decal over the entire map but I'll probably make a content freeze on it since it will probably take a few week's work with my current schedule

**Comment by metalgearsloth** [comment]
I think the diff being cooked is maybe tile changes + other changes in the same commit so git got confused on line changes.

**Comment by metalgearsloth** [comment]
merge master :trollface:

**Comment by deltanedas** [comment]
bruh the diff is the entire fucking file

**Comment by deltanedas** [comment]
@metalgearsloth :trollface:

**Comment by deltanedas** [comment]
ci is your fault :tm:

**Comment by Emisse** [comment]
diff cooked
game broke
tests fried
ready to merge

**Pull request merged**
