### PR TITLE
Cheaper medkit crates

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

most of the crates were like several thousand spesos and gave like 4 kits. I thought it made more sense to make them cheaper but only have one kit per.

## Why / Balance

This better incentivizes ordering single crates as they're actually at a price range where it'd be reasonable.

## Technical details

yaml

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: All of the emergency medkit cargo crates now only give a single kit but are cheaper in return.

### CODE REVIEW

**Comment by mirrorcult** [comment]
do the descriptions state you get >1 medkit?

**Comment by EmoGarbage404** [comment]
> do the descriptions state you get >1 medkit?

they did. good catch.

**Review by mirrorcult — APPROVED** [review]

**Comment by UbaserB** [comment]
If its literally one kit, why bother have a crate come with it?

**Comment by EmoGarbage404** [comment]
> If its literally one kit, why bother have a crate come with it?

Pushing crates is based

**Pull request merged**
