### PR TITLE
Fix produce yaml

### LINKED ISSUE #23600: bungo fruit cannot be eaten by lizards
## Description
lizards are supposed to be able to eat fruit but they cant eat bungo fruit

**Reproduction**
be LIZArd and eat bungo fruit, CANNOT

**Screenshots**
3

**Additional context**
they can eat the pits but not the main fruit, very weird

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Resolves #23600. Also like, makes oranges not meat any longer, mimanas considered fruit and onions the most nutritious they can be.

### CODE REVIEW

**Comment by GreyMario** [comment]
As someone who does bartending, can we avoid contaminating Juice outputs? I'd rather get potassium from processing banana juice, anyway--to prevent shitters from putting water in a ground banana to get an explosion.

**Comment by IamVelcroboy** [comment]
Something I noticed last week, but take a look at onions. They have less maxvol than the contents they contain. Seems like it would be appropriate fix for this PR.

**Comment by Partmedia** [comment]
As folks pointed out on Discord, adding potassium to bananas could cause unexpected self-potassium-bombing in stomachs. It would be better to include that in a separate PR so that we don't hold up this fruit fix.

**Comment by UbaserB** [comment]
> As folks pointed out on Discord, adding potassium to bananas could cause unexpected self-potassium-bombing in stomachs. It would be better to include that in a separate PR so that we don't hold up this fruit fix.

Oh okay, no worries

**Comment by UbaserB** [comment]
fixed.

**Comment by Partmedia** [comment]
Thank you for your contribution!

**Pull request merged**
