### PR TITLE
Wehvitational Wehularity Engine

### PR DESCRIPTION
**Pull request by Keer-Sar**
## About the PR

Created wehularity.yml with custom sprites. Modified generator.yml to hold a parented WehularityGenerator. Modified migration.yml to replace SingularityGenerator with WehularityGenerator
## Why / Balance

plushie_lizard

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/144283718/81c29d36-68be-4305-bbf3-5950b0a42a7f

Salturn Spawn Example

Thank you @SphiraI for the custom sprites!
## Breaking changes

**Changelog**

🆑 
- tweak: Singularity engines now have a strange new weh to them.

### CODE REVIEW

**Comment by PolterTzi** [comment]
Needs custom sounds.

**Comment by baddiePRO** [comment]
> Needs custom sounds.

was gonna say, 7/10 not enough weh

**Comment by UbaserB** [comment]
pr is cooked

**Comment by metalgearsloth** [comment]
don't branch from master, use april fools.

**Comment by Lakk55** [comment]
weh

**Pull request closed without merging**
