### PR TITLE
Security clothes overhaul

### PR DESCRIPTION
**Pull request by Thurtik**
## About the PR

This PR does several things:

1) It REVERTS the sprite changes done by #29082 , namely:
-security, warden and hos jumpsuits/skirts
-brown fedora and detective's trench coat
-detective's vest
-hos' armored trenchcoat
-warden's armored coat
-all the changed variations of helmets

2) It KEEPS/ADJUSTS the following features:
-the grey fedora is changed to look consistent with it's brown counterpart
-the noir trenchcoat stays but has it's sprite changed to look consistent with it's brown counterpart
-the hos' cap stays but has it's sprites edited to look less flat at the front when worn and viewed from the side + has a new icon that resembles more closely how it actually looks when worn

3) It ADDS the following features:
-the hos' sherrif hat is back again as a loadout option (and is printable at uniform printers)
-a detective badge that can be worn in the neck slot (obtainable from the detdrobe)
-the detective trenchcoats can now be opened/closed at will via the verb menu

## Why / Balance

The changes to sprites made in PR #29082 weren't recieved positively by most people, and most of the arguments provided in favor of those changes were debatable. Did the sprites look a bit more detailed than the others? Yes. Did it make them look out of place? No, not at all. Furthermore, the new sprites didn't even look consistent with their variations (e.g.: the grey and blue security jumpsuits/skirts and the warden's armored winter coat).

The PR wasn't all doom and gloom however, as it came up with some neat ideas which some people (including me) really liked (e.g.: a badge and openable coats for detectives), so I decided to expand upon them. This PR isn't meant to be just a hot-headed revert, it aims to bring people the best of both worlds.

## Media

Snímek obrazovky 2024-07-01 215343

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Reverted all of the recently changed security sprites back to their higher-quality versions.
- tweak: The head of security's cap has had it's sprite when worn slightly adjusted and recieved a new icon.
- tweak: The noir trenchcoat and grey fedora have had their sprites changed to keep them consistent with their brown counterparts.
- tweak: You can now open and close the detective's trenchcoats via the verb menu.
- add: The head of security's hat returns as a loadout option.
- add: Added a fancy new badge for detectives wearable in your neck slot (obtainable via the DetDrobe).

### CODE REVIEW

**Comment by mirrorcult** [comment]
at the very least the fedoras should not be reverted, these fedoras literally do not even look like fedoras

**Comment by mirrorcult** [comment]
other changes ill defer to @Flareguy and @EmoGarbage404

**Comment by Thurtik** [comment]
> at the very least the fedoras should not be reverted, these fedoras literally do not even look like fedoras

You're right, I will change them

**Comment by EmoGarbage404** [comment]
mfw reverting the resprite and not even fixing the det hat and coat being different colors

**Comment by Thurtik** [comment]
Better?
obrázek_2024-07-02_112250504

**Comment by Flareguy** [comment]
This PR more-or-less completely ignores the all arguments & benefits of the original security resprite PR. There's really no good reason to just revert this - I'm not going to regurgitate my points, but in my opinion, security was pretty plainly inconsistent with the rest of the clothing in the game, if nothing else.

If you think the security resprite is subpar, you should try to improve it & work towards the direction we're headed in, instead of reverting to inconsistent sprites.

**Comment by EmoGarbage404** [comment]
i think there are certain elements of the old sprites that i'd be fine with seeing return, notably the more vibrant red color palette. However, on the whole, the consistency issues are really blatant and i think the standardization of the department clothing is for the benefit of the visual style. 

If there are specific elements that you think would be valuable to standardize throughout all of security, then you should incorporate it uniformly throughout all the sprites rather than leaving a hodge-podge of sprites that weren't sprited with each other in mind and clearly don't fit.

additionally, changes like the opening coats and the separate hats/badges should have been done in another PR. kindly don't try and smuggle in additions like that in resprites.

For those reasons, I'm opting to close this PR. Feel free to open another one later incorporating the general criticism. Thank you.

**Comment by Thurtik** [comment]
> This PR more-or-less completely ignores the all arguments & benefits of the original security resprite PR. There's really no good reason to just revert this - I'm not going to regurgitate my points, but in my opinion, security was pretty plainly inconsistent with the rest of the clothing in the game, if nothing else.
> 
> If you think the security resprite is subpar, you should try to improve it & work towards the direction we're headed in, instead of reverting to inconsistent sprites.

Alright, let's look at the reasoning you gave in #29082 :

_-"Jumpsuits styled completely differently from every other jumpsuit, comparatively extremely detailed sprites with inconsistent coverage"_

"Extremely" is a big exaggeration. The detail gap wasn't so big that it would make them look out of place. Different stylization is good and adds variety. If cargo techs can have shorts and salvage technicians working overalls as a part of their jumpsuits, why are security's jumpsuits an issue? Also what inconsistent coverage? They covered (and even the new ones do) the same surface area as all other job-specific jumpsuits.

_-"The helmet was extremely over-detailed and randomly plucked from baystation security (or so I've heard.) The current helmet actually matches with the armor vest."_ 

It didn't look bad or out of place. Also who said it had to look like the armor vest?

_-"HOS's coat was reverted since the new one had some readability issues & kind of looked like syndicate gear."_

 What readability issues? To me, the new sprite has more readability issues. The details helped distinguishing it from something like a jensen coat. Also by saying "kind of looked like syndicate gear", did you mean the syndicate coat, aka the item that's impossible to obtain via normal means (unless you use chameleon clothes or want to fly around in space for 20 minutes looking for a left behind nukie shuttle)?

_-"Warden's weird armor vest webbing has been stripped since I think it makes him look more normal."_

Yet you left it on the winter variant. So much for "consistency", huh.

_-"The detective randomly used a bunch of CEV-Eris sprites still, and even outside of that, just generally looked really bad."_

They didn't look bad, that is subjective.

_-"Lots of generally awful contrast & color choice was strewn about through his wardrobe."_ 

Contrast helps readability. It's hard to discern what is what in a mush of similarly colored things.

_-"His fedora may as well have just been a bowler hat for crying out loud."_ 

Fixed.


And yes, there IS a really good reason to revert it - the positive and negative reactions ratio under the PR. If SS14 is supposed to be a community driven game, the community should have the final say in non-technical things like this.

**Comment by TheDoctor1977** [comment]
> If SS14 is supposed to be a community driven game, the community should have the final say in non-technical things like this.

This sums up my feelings on these recent resprites exactly. I have seen so many PRs get closed lately just because of some ambiguous vision that the maintainers have for the game that the community at large doesn’t seem to share.

**Comment by Emisse** [comment]
> And yes, there IS a really good reason to revert it - the positive and negative reactions ratio under the PR. If SS14 is supposed to be a community driven game, the community should have the final say in non-technical things like this.

LOL

**Pull request closed without merging**
