### PR TITLE
Adds the flash pen for revs.

### PR DESCRIPTION
**Pull request by nikthechampiongr**
## About the PR

With the blessing of @QuietlyWhisper I am reopening #22061 but this time the flash pen spawns in the rev pda.

## Why / Balance

Same as the last pr: Shouldn't affect game balance, should make revs metagamed less as easily.
## Technical details

The AntagSelectionSystem now has 2 new methods which make it try to spawn items on the PDA, if it fails then it will default to trying to put them inside the bag/pockets. If an item can be placed inside the pda any item that may still be in there will be deleted. 
## Media

https://github.com/space-wizards/space-station-14/assets/32041239/7ddf891e-0787-42bf-a220-31520c6870e8

287263166-050c01ba-7492-41e4-92ac-30bfbaecb91f

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

This is technically not a breaking change since all previous invocations should be valid but the signature of GiveAntagBagGear has been changed to allow for an already existing item to be passed in.

**Changelog**

:cl: QuietlyWhisper & nikthechampiongr
- add: Head Revolutionaries are now equipped with a flash pen.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
There’s still no explanation for why giving revs a special flash that can out them as a headrev is a good idea.

**Comment by deltanedas** [comment]
they already get outed as headrevs with flash

**Comment by nikthechampiongr** [comment]
> There’s still no explanation for why giving revs a special flash that can out them as a headrev is a good idea.

They already get ousted as a headrev simply for having a flash, at least this adds an IC reason. A pen is more stealthy. If you want to solve the metagaming issue then you need to make stealth items not immediately discoverable the moment someone inspects them.

**Comment by deltanedas** [comment]
flashes dont make people fall over, still valid

**Comment by GoodWheatley** [comment]
> flashes dont make people fall over, still valid

If somebody *sees* you flash someone, you should absolutely be outed as a headrev. What I’m concerned about is that if your bag gets searched and they find the flash pen there’s literally no other conclusion besides “you’re a headrev”.

**Comment by deltanedas** [comment]
sorry you have a flash and sunglasses in your bag, you must be a headrev

if they are checking everything in your pda and pressing pens they are already metagaming

**Comment by deltanedas** [comment]
and this le headrev confirmed argument can be avoided entirely by adding it to uplink or maints as well

**Comment by Hmeister-fake** [comment]
Genuinly how likely is it that sec removes your pen, and then uses it. Just make it only activate on hitting someone with it as a headrev, and not able to wide flash like actual flashes. Problem solved.

**Comment by HoidC** [comment]
> Genuinly how likely is it that sec removes your pen, and then uses it. Just make it only activate on hitting someone with it as a headrev, and not able to wide flash like actual flashes. Problem solved.

quite likely since they already check for laser and bomb pens

**Comment by K-Dynamic** [comment]
Very good chance that even if sec can't flash the pen they'll just confisicate them from the station

**Comment by nikthechampiongr** [comment]
This is it at its heart a stylistic change that just fits the revs gamemode. It is not meant to increase or reduce the chances of metagaming happening which is gonna happen either way, that stuff should just be left to the admin team. The only reason for this PR's existence is to provide a silly little pen that could conceivably be given to head revolutionaries in character

**Comment by EmoGarbage404** [comment]
> This is it at its heart a stylistic change that just fits the revs gamemode

I understand your position but it's undeniable that there are going to be some balance considerations from even something as simple as a unique reskin.

I don't really see this as reducing rev metagaming nor do i know if it'll greatly increase it. Its very hard to say.

**Comment by nikthechampiongr** [comment]
> I don't really see this as reducing rev metagaming nor do i know if it'll greatly increase it. Its very hard to say.

There is a pending pr that will categorize what stuff is contraband and what is not as well as when it can be seen correct? Do you want me to just draft this pr and wait on that pr so I can just give it a proper label?

**Comment by Rainbeon** [comment]
> > flashes dont make people fall over, still valid
> 
> If somebody _sees_ you flash someone, you should absolutely be outed as a headrev. What I’m concerned about is that if your bag gets searched and they find the flash pen there’s literally no other conclusion besides “you’re a headrev”.

Last sentence is flawed because everyone has a pen in their PDA and the PR mentions spawning the flash pen in the PDA, if they get searched it would appear they have nothing incriminating on them so there is no chance that "you're a head rev" is the conclusion that would be drawn.

**Comment by EmoGarbage404** [comment]
if a secoff is already doing full inventory searches based off of hearing clicking sounds in maints, i really doubt they are going to stop before pulling a pen out of a PDA to examine it.

**Comment by Rainbeon** [comment]
> if a secoff is already doing full inventory searches based off of hearing clicking sounds in maints, i really doubt they are going to stop before pulling a pen out of a PDA to examine it.

This would be an incredibly silly looking and obvious metagaming action though, no? Literally zero Sec Offs check pens as is, and meta wise they should have no knowledge of a Flash Pen if it were to hypothetically exist. Going "Let me look at your pen and also try to hit you in the face with it to test if its a Flash Pen" is fairly obvious metagaming to me unless the Flash Pen mechanic has been visually outted already (similar to how Uplink rules work)

**Comment by Aisu9** [comment]
remember, pda checking is only allowed when the person is serving prison time

**Comment by GreyMario** [comment]
> remember, pda checking is only allowed when the person is serving prison time

[citation needed]

**Comment by nikthechampiongr** [comment]
> remember, pda checking is only allowed when the person is serving prison time

Currently in wizard den servers there are no special search restrictions on pdas, it can be done in a random search.  https://forum.spacestation14.io/index.php?/topic/2216-abnormally-thorough-searches/#comment-10611

**Comment by K-Dynamic** [comment]
> > remember, pda checking is only allowed when the person is serving prison time
> 
> Currently in wizard den servers there are no special search restrictions on pdas, it can be done in a random search. https://forum.spacestation14.io/index.php?/topic/2216-abnormally-thorough-searches/#comment-10611

Yes just keep in mind most searches are just bag searches, and admins frown upon randon hallway PDA searches without good reason compared to checking in brig

**Comment by deltanedas** [comment]
> and this le headrev confirmed argument can be avoided entirely by adding it to uplink or maints as well

**Comment by nikthechampiongr** [comment]
> > and this le headrev confirmed argument can be avoided entirely by adding it to uplink or maints as well

If you want to re-open it feel free I guess. From what I understood the main reason the pr wasn't liked was because of how stealthy it was compared to the normal flash. Also  that it became stealth contraband. 

I don't feel like fighting for just a cool reskin right now.

**Comment by Hmeister-fake** [comment]
Very sad, no flash pen today...

**Comment by K-Dynamic** [comment]
Can we give them a chameleon flash instead of a pen

**Pull request closed without merging**
