### PR TITLE
More whitelist items for belt

### PR DESCRIPTION
**Pull request by lzk228**
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Anomaly and node scanners can be placed in utility belt.
- tweak: Whistles can be placed in utility and sec belts.

### CODE REVIEW

**Comment by Golinth** [comment]
Honestly, remove whitelists for belts completely imo

**Comment by Hmeister-real** [comment]
> Honestly, remove whitelists for belts completely imo

Not for all belts, like the salvage rig is a utility belt, but just has no whitelist, and thats its one gimmick.

**Comment by Golinth** [comment]
> Not for all belts, like the salvage rig is a utility belt, but just has no whitelist, and thats its one gimmick.

same thing with the sec vest. Round start I and many other officers trade their belt for a vest. IMO those should have other gimmicks, and be made more interesting (or just kept the same) instead of having random whitelists and wondering why my wrench fits on my med belt but not my crowbar.

**Comment by SoulFN** [comment]
Add anomaly locators too

**Comment by EmoGarbage404** [comment]
at this point it's probably just best to remove whitelists from belts. with gridinv and limiting stuff by a certain size, i don't really think it's necessary.

**Comment by superjj18** [comment]
> at this point it's probably just best to remove whitelists from belts. with gridinv and limiting stuff by a certain size, i don't really think it's necessary.

I agree, if we really cared about restricting it we could remove the whitelist and separate the toolbelt inventory like the satchel so it prevents guns and other large items

maybe instead of a 2x8 its 4 2x2s

**Comment by Hanzdegloker** [comment]
> at this point it's probably just best to remove whitelists from belts. with gridinv and limiting stuff by a certain size, i don't really think it's necessary.

woe be upon ye, toolbelt of only soda cans and bags of chips

**Pull request closed without merging**
