### PR TITLE
Remove plushie_lizard_mirrored.png

### LINKED ISSUE #28481: plushie_lizard_mirrored.png needs removing
Someone didn't know how to to do transforms and copy-pasted it.

### PR DESCRIPTION
**Pull request by LevitatingTree**
## About the PR
Just deleted the file, tiny PR.

## Why / Balance
Closes #28481.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by slarticodefast** [comment]
The png file is used for the `PlushieLizardMirrored` prototype. You have to replace it by mirroring the `plushie_lizard` sprite in yaml.
Also remove the state from the meta.json

**Comment by slarticodefast** [comment]
>Riip left-handed wehs

The plushie stays. But there is no reason to have a mirrored png when you can just mirror it in the engine.

**Comment by ArtisticRoomba** [comment]
PR #33776 uses the flipped plushie as an attribution. I guess I'll just attribute the regular plushie.

**Comment by pcaessayrs** [comment]
It looks like you'll want to change toys.yml to stop using the mirrored sprite and instead use `scale: -1, 1`, otherwise your build will not work (the YAML linter will reject it)

**Review by slarticodefast — APPROVED** [review]
Tested and works as intended.
Thanks for the cleanup!

**Review by SlamBamActionman — APPROVED** [review]

**Pull request merged**
