### PR TITLE
Prevent almost every player facing issue

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

Prevents nearly every player facing issue from impacting them, including:
- Latency during rounds
- All physics bugs
- Rule breaking, including:
  - Ban evasion
  - Self antagging
  - Text speak
  - Metagaming
    - Metacomming
    - Metafriending
    - Metagrudging
  - Powergaming
  - Antag rolling
  - RDM
  - Admin checking
- Incompetence of other players
- The player's own incompetence
- Visual bugs, including:
  - Vote UI overlap
  - Mobs appearing to be in the wrong state
  - HUD elements appearing when they shouldn't
- Economy balance issues
- Player movement input getting stuck

It also significantly reduces the amount of effort required to test new features, however this is an unintended side effect. Further testing may reveal more.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Changes have been made to prevent players from experiencing nearly every issue.

### CODE REVIEW

**Review by deltanedas — APPROVED** [review]

**Review by 0x6273 — APPROVED** [review]

**Review by Scribbles0 — APPROVED** [review]

**Review by GoodWheatley — APPROVED** [review]

**Review by unusualcrow — APPROVED** [review]

**Review by PixelTheKermit — APPROVED** [review]
This needs no further approval, merge right this instant.

**Review by crazybrain23 — APPROVED** [review]
I tested this locally and found no player issues.

**Review by QuietlyWhisper — APPROVED** [review]
Truly a PR of all time

**Comment by deltanedas** [comment]
i tested on lizard and it also works no player issues, instamerge

**Comment by moonheart08** [comment]
this is not being merged nice try

**Comment by EmoGarbage404** [comment]
in light of the fact that player issues are in fact game issues, i think the best course of action would instead be to delete the entire game.

**Comment by HoidC** [comment]
No, because people can make the game again. I think we should pool our money together to hire a squad of elite assassins that will kill anyone who concieves of the idea of making this game. NOBODY will ever suffer a player issue again.

In fact, to go further, let's carpet bomb the known locations of all players so that they do not cause further problems for other players.

**Comment by crazybrain23** [comment]
> In fact, to go further, let's carpet bomb the known locations of all players so that they do not cause further problems for other players.

I fail to see how a carpetium bomb will help but I'm down if you are.

**Comment by Slava0135** [comment]
If game will have no players there won't be any issues! So I propose deleting github repository and web site. Fork authors will be dealt with personally by our syndicate agents.

**Comment by PixelTheKermit** [comment]
I personally think we should take down the internet itself. Don't know how effective it would be but it shouldn't be that hard, right?

**Comment by AveriV2** [comment]
guess what just happened

**Comment by t0wnshark** [comment]
just fell to my knees in the middle of my kitchen

**Comment by lalmthelegendary** [comment]
crying in the club rn fr

**Comment by Walegphil** [comment]
Its so joever

**Comment by Stealthbomber16** [comment]
a visionary

**Comment by GoodWheatley** [comment]
Just saw someone fall to their knees in a kitchen

**Comment by Zoewithrose** [comment]
how did he know

**Comment by troytroy400** [comment]
He was limited by the technology of his time... but we were finally able to see it through.

**Comment by JohnnyMalawny** [comment]
still need this

**Pull request closed without merging**
