### PR TITLE
Add zombie faction, improve unzombify

### PR DESCRIPTION
**Pull request by DawBla**
## About the PR

Adds the zombie faction to the entity when zombified so AI zombies don't attack other zombies, restores previous factions when unzombified
Improves the unzombify function to undo all changes zombify does
Adds GetBloodlossThreshold to BloodstreamSystem, GetFactionList to FactionSystem and GetDamageModifierSetId to DamageableSystem
(please tell me if I did this wrong)
Removes some of the hardcoded parts

Fixes: #16166

**Media**

https://user-images.githubusercontent.com/46636558/236708702-e8a3dd14-a7d6-4416-9930-ae476a6b119f.mp4

(The second tarantula got the mind and waits for someone to pick it up as a ghost role, AI won't move it until someone grabs it and leaves, I assume it's intended?)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Mumohan
- Fix: AI zombies will no longer attack other zombies

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
I tried to do this once but unless hostile ai has been changed (Im not sure because theres been  alot of ai changes) ai will not check for faction changes mid combat, which is essential for this pr as zombies would still attack zombies they just turned

**Comment by DawBla** [comment]
> I tried to do this once but unless hostile ai has been changed (Im not sure because theres been  alot of ai changes) ai will not check for faction changes mid combat, which is essential for this pr as zombies would still attack zombies they just turned

Not sure if that's what you mean, but you can see in the video that zombie tarantula stops attacking the Urist and the other tarantula once they turn into zombies

Once I get home I'll check if they stop when someone else zombifies their target mid combat

**Comment by QuietlyWhisper** [comment]
> > I tried to do this once but unless hostile ai has been changed (Im not sure because theres been  alot of ai changes) ai will not check for faction changes mid combat, which is essential for this pr as zombies would still attack zombies they just turned
> 
> Not sure if that's what you mean, but you can see in the video that zombie tarantula stops attacking the Urist and the other tarantula once they turn into zombies
> 
> Once I get home I'll check if they stop when someone else zombifies their target mid combat

I didn't notice the video, it's prolly fixed now :D

**Comment by DawBla** [comment]
https://user-images.githubusercontent.com/46636558/236856087-18f7f68b-ff07-4a26-8d00-094b90f5061c.mp4

Checked it and yeah It Just Works™

**Pull request closed without merging**
