### PR TITLE
Tiles resprites

### PR DESCRIPTION
**Pull request by KIBORG04**
## About the PR 

**Screenshots**

| UGLY BEFORE | BEATIFUL AFTER |
| ------------- |:-------------:| 
| image | image |
| image | image    |  

Ported from https://github.com/TauCetiStation/TauCetiClassic/pull/3993 by [Theta Community](https://github.com/ThetaStation/ThetaStation)

**Changelog**

:cl:
- add: Resprite most tiles and tiles decals

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Can someone with github access slap a nice preliminary "needs discussion" on this one. This feels controversial.

**Comment by moonheart08** [comment]
> Can someone with github access slap a nice preliminary "needs discussion" on this one. This feels controversial.

It's a feature we could've upstreamed some time ago and opted not to.

**Comment by KIBORG04** [comment]
👌

**Comment by moonheart08** [comment]
I imagine these look p good with the right lighting and companion spritework, but we like our current style.

**Comment by moonheart08** [comment]
Before you close this though, I shall review.

**Comment by KIBORG04** [comment]
Why the map saving random type of tile?

**Comment by Emisse** [comment]
what if these were added as separate tiles, i do think they look nice and could be used as an alternative to standard steel floors.

**Comment by Peptide90** [comment]
> what if these were added as separate tiles, i do think they look nice and could be used as an alternative to standard steel floors.

Toggle lighting would have really made a difference here otherwise it’s hard to see how dark they really are. They do look cleaner because of the thinner grout lines in the center but they do look a lot more flat, and don’t match the style of everything else too much as Moony mentioned.

As an alternative it’s almost like a texture pack, if it’s the one tile I can see it being an option for a very different type of station (differentiate lore whatever) but if it’s a lot of tiles it’ll probably be largely unused. Still if it’s not much size / content wise it could be a discussion.

**Comment by moonheart08** [comment]
> > what if these were added as separate tiles, i do think they look nice and could be used as an alternative to standard steel floors.
> 
> Toggle lighting would have really made a difference here otherwise it’s hard to see how dark they really are. They do look cleaner because of the thinner grout lines in the center but they do look a lot more flat, and don’t match the style of everything else too much as Moony mentioned.
> 
> As an alternative it’s almost like a texture pack, if it’s the one tile I can see it being an option for a very different type of station (differentiate lore whatever) but if it’s a lot of tiles it’ll probably be largely unused. Still if it’s not much size / content wise it could be a discussion.

I think adding these in as alternates woudl just lead to major style clash.

**Comment by KIBORG04** [comment]
Screenshots with light

| UGLY BEFORE | BEATIFUL AFTER |
| ------------- |:-------------:| 
| image | image  |

When are resource packs?

**Comment by moonheart08** [comment]
We're not interested in redoing our tiles at this time.

**Comment by Emisse** [comment]
resource packs would be based

**Pull request closed without merging**
