### PR TITLE
Changed Lathe UI to two-column layout so its easier to see what materials are currently loaded

### PR DESCRIPTION
**Pull request by ItsMeThom**
- tweak: Changed the Lathe/UI layout to two column, to improve readability of the list of materials current in the lathe.

## About the PR

Modified the Lathe UI window be two-column layout (Recipes on left, materials on right)
## Why / Balance

Readability of the current amount of materials in a lathe/fab is very difficult as the materials window is squashed at the bottom of the recipes list, making it hard to see at a glance what the overall materals are, and what you might be missing. This leads to people just shoving entire stacks of materials in a lathe at once, instead of just sticking in the amount they need.

## Technical details

Reorgranised the structure so the queue, search/filter, recipies and amount to produce are in the left column, and the materials list and eject materials button are in the right column.

## Media
Old Lathe UI:
image
"Its hard to tell what exactly Im missing to build this, I might as well jam everything I can find in this lathe!" ~everyone
image

New Lathe empty/with materials loaded:
image
image

Protolathe and various techfabs also incorporate the change
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Changed Lathe UI to two column layout to improve readability of materials currently loaded.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
You should just embed the material eject menu into the right side of the lathe ui, since it now has the additional space to not look garbage.

**Comment by EmoGarbage404** [comment]
The way TG has it is that the left side has the list of recipes and the right side has both the queue and the material eject menu.

I don't really think that the UI being too busy is an issue, so long as it has decent margins.

**Comment by ItsMeThom** [comment]
Cool! I'll admit I havent seen the tg stuff in many years (Long time since I played SS13) but I can boot it up for a look, and then get to work updating this so the queue/eject options are on the left.

**Comment by ItsMeThom** [comment]
@EmoGarbage404 Ive updated it as you requested, to move both the materials ejection and queue directly onto the main screen of the lathe. Heres the updated screenshots:


Empty lathe:

image


Lathe with materials and build in progress:

image


Lathe at 'comfortable' level of window expansion to show all details.
image

 I was hesitant to make the window size any larger, as currenty the default size is 800, which does cut off some text i.e., the cubic volume of materials. If I were to make it any larger Id fear it would take up the whole screen.

**Comment by ItsMeThom** [comment]
I should also note that Ive discovered that the build queue only displays the current item building, not the entire queue. It's a bit odd, and Im not familiar enough with the code yet to fix it in this PR, but I will address that later on.

**Comment by EmoGarbage404** [comment]
Stack the queue and the material ui on top of each other to save space. Neither is regularly going to be full

**Comment by ItsMeThom** [comment]
> Stack the queue and the material ui on top of each other to save space. Neither is regularly going to be full

Like this? I think this works really well personally. Good idea!
image

**Comment by ItsMeThom** [comment]
Small bugfix for a line I commented out while testing the build queue list and didn't uncomment.

**Comment by crazybrain23** [comment]
What happened to the server list button?

**Comment by ItsMeThom** [comment]
> What happened to the server list button?

This is the AutoLate window (the most recent screenshot) It is not connected to the R&D server so they button isnt displayed. Rest Assured its present in the other lathes/fabs:

image

image
image

**Comment by ItsMeThom** [comment]
> some nits
> 
>     * 'No items in queue' message should either be removed or put somewhere else, looks weird there (plus i feel like 'no items in queue' is already communicated by there being nothing in the queue)
> 
>     * item description in the queue looks pretty weird cut off like that

Thanks for the feedback! You are right that it is redundant. I have removed it, and also the unnessecary item description (which was going to end up cut off more often than not) I had carried those over from the original implementation of the build queue. 

I also gussied it up a bit and added a background hilight for the item currently being built. Here are some screenshots of the changes:

image
image

**Comment by mirrorcult** [comment]
damn, looks great

**Comment by ItsMeThom** [comment]
> damn, looks great

Thanks! Heres a bonus space-station-factorio screenshot for fun

image

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
