### PR TITLE
New machete sprite

### PR DESCRIPTION
**Pull request by TaralGit**
Just a small PR to replace the old sprite since it looks more like a knife or a scalpel than the real deal. Pics for comparison:

Old:
old_machete

New:
machete_last

### CODE REVIEW

**Comment by Mith-randalf** [comment]
Maybe its just me but that looks more like a tanto than a machete. A machete is kinda defined by the increased broadness towards the business end, right?

**Comment by TaralGit** [comment]
> Maybe its just me but that looks more like a tanto than a machete. A machete is kinda defined by the increased broadness towards the business end, right?

I tried making it broader but at this size I couldn't without making it look ridiculously huge. 

And I still don't understand why I get conflicts for replacing my own old icon.png files. It's the second time this happened to me.

**Review by PaulRitter — CHANGES_REQUESTED** [review]
icon.png is cooked, fix it

**Comment by PaulRitter** [comment]
i really dont like closing pr's like these because you did put effort in, but ultimately i dont see why we even need to change the sprites. if they were shittily made codersprites i'd get it, but the current sprite is already p nice & fits in with the other textures imo.

**Pull request closed without merging**
