### PR TITLE
Fixed shuttle movements on some systems

### PR DESCRIPTION
**Pull request by devkoks**
## About the PR
Fixed shuttle movements in southern and northern coordinates

## Why / Balance
The shuttle couldn't move north and south.

## Technical details
The Dot system function was not functioning properly on some Vector2 system library, so the Dot function was copied to the MoverController.

## Media
None needed.
- [*] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None.

**Changelog**
No cl.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Is there a linked dotnet issue

**Comment by PJB3005** [comment]
This is straight up "this needs an upstream bug in the .NET runtime" tier if this fixes it. This really demands further investigation.

Can you send me the top of your server log when it starts (or at least enough for the intrinsics):

```
[INFO] root: Server -> Starting
[INFO] cfg: Configuration loaded from file
[DEBG] root: OS: Microsoft Windows 10.0.22631 X64
[DEBG] root: .NET Runtime: .NET 8.0.0 win-x64
[DEBG] root: Server GC: True
[DEBG] root: Processor: 24x AMD Ryzen 9 5900X 12-Core Processor
[DEBG] root: Architecture: X64
[DEBG] root: Robust Version: 205.0.0.0
[DEBG] root: Compile Options: DEVELOPMENT;TOOLS;DEBUG;CLIENT_SCRIPTING
[DEBG] root: Intrinsics: X86Aes;Avx;Avx2;Bmi1;Bmi2;Fma;Lzcnt;Pclmulqdq;Popcnt;Sse;Sse2;Sse3;Ssse3;Sse41;Sse42;X86Base
```

**Comment by metalgearsloth** [comment]
Also for reference if Vector2.Dot didn't work then the entirety of physics would break.

**Comment by PJB3005** [comment]
For another sanity check can you add the following code in your `Vector2Dot` function:

```cs
if (!float.IsFinite(value1.X) || !float.IsFinite(value1.Y) || !float.IsFinite(value2.X) || !float.IsFinite(value2.Y))
    throw new InvalidOperationException();
```

**Comment by PJB3005** [comment]
> Also for reference if Vector2.Dot didn't work then the entirety of physics would break.

If nothing else it's possible it's some cursed codegen issue that only manifests in this one method. 

@devkoks can you try if you move the code *calling* `Vector2.Dot` into a smaller function? Heck I'd be willing to see the result if you make `Vector2Dot` this:

```cs
        [MethodImpl(MethodImplOptions.NoInlining)]
        // Copied from "System.Numerics.Vector2.Dot", because it's working unstable on some systems.
        public float Vector2Dot(Vector2 value1, Vector2 value2)
        {
            return (value1.X * value2.X)
                 + (value1.Y * value2.Y);
        }
```

**Comment by PJB3005** [comment]
Another thing to try: `[MethodImpl(MethodImplOptions.NoOptimization)]` on `HandleShuttleMovement`

**Comment by devkoks** [comment]
> This is straight up "this needs an upstream bug in the .NET runtime" tier if this fixes it. This really demands further investigation.
> 
> Can you send me the top of your server log when it starts (or at least enough for the intrinsics):
> 
> ```
> [INFO] root: Server -> Starting
> [INFO] cfg: Configuration loaded from file
> [DEBG] root: OS: Microsoft Windows 10.0.22631 X64
> [DEBG] root: .NET Runtime: .NET 8.0.0 win-x64
> [DEBG] root: Server GC: True
> [DEBG] root: Processor: 24x AMD Ryzen 9 5900X 12-Core Processor
> [DEBG] root: Architecture: X64
> [DEBG] root: Robust Version: 205.0.0.0
> [DEBG] root: Compile Options: DEVELOPMENT;TOOLS;DEBUG;CLIENT_SCRIPTING
> [DEBG] root: Intrinsics: X86Aes;Avx;Avx2;Bmi1;Bmi2;Fma;Lzcnt;Pclmulqdq;Popcnt;Sse;Sse2;Sse3;Ssse3;Sse41;Sse42;X86Base
> ```

```
[INFO] root: Server -> Starting
[INFO] cfg: Configuration loaded from file
[DEBG] root: OS: Debian GNU/Linux 12 (bookworm) X64
[DEBG] root: .NET Runtime: .NET 8.0.1 linux-x64
[DEBG] root: Server GC: True
[DEBG] root: Processor: 12x Common KVM processor
[DEBG] root: Architecture: X64
[DEBG] root: Robust Version: 204.0.0.0
[DEBG] root: Compile Options: DEVELOPMENT;RELEASE;EXCEPTION_TOLERANCE
[DEBG] root: Intrinsics: Sse;Sse2;Sse3;X86Base
```

**Comment by PJB3005** [comment]
Issue reproduces locally for me by setting `DOTNET_enableSSSE3=0` via env variable and running the server on release. I'll see about getting a repro to `dotnet/runtime`. In the mean time I'll merge this workaround.

**Comment by PJB3005** [comment]
By the way @devkoks are you actually running the game on a **17** year old CPU? Intel CPUs with SSSE3 started shipping in 2006. If you aren't you should double check your hypervisor configuration or something as it may be misconfigured.

**Comment by devkoks** [comment]
> By the way @devkoks are you actually running the game on a **17** year old CPU? Intel CPUs with SSSE3 started shipping in 2006. If you aren't you should double check your hypervisor configuration or something as it may be misconfigured.

No, CPU installed on server: Intel Xeon E5-2620

**Comment by PJB3005** [comment]
Yeah then your hypervisor config is messed up and reporting a significantly older CPU to the VM. If nothing else, fixing this will slightly improve server perf. I also think some newer distros like RHEL 9 can't boot in this state.

**Pull request merged**
