### PR TITLE
Heterochromia

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR 
Heterochromia is now available through the markings tab, under the head section.

**Screenshots**

image
image
image
image

**Changelog**

:cl:
- add: Heterochromia is now available through the markings tab, located under the head section.

### CODE REVIEW

**Comment by moonheart08** [comment]
couldn't these all just be a single set of markings, i.e. `[Reptillian, Slime, Human]` for allowed species.

**Comment by Scribbles0** [comment]
ah.. didn't know, i'll fix it

**Comment by Scribbles0** [comment]
> couldn't these all just be a single set of markings, i.e. `[Reptillian, Slime, Human]` for allowed species.

hm, i'm not sure but i removed everything i edited except for but human loc, meta, prototypes, and sprites, then tested what you suggested, and the markings are not appearing for slimes and lizards. if i'm doing something wrong, do tell

**Comment by Scribbles0** [comment]
ah woops, hold on.. did something wrong, i'll push a commit in a sec

**Comment by Scribbles0** [comment]
aaaaaand there's some stuff from a deleted branch here.. great. probably doing something wrong, just give me a second to fix that other thing

**Comment by Just-a-Unity-Dev** [comment]
You changed `narcotics.yml` in your PR which is breaking the YAML linter and tests. Indentation is VERY important in YML.

image

**Comment by Scribbles0** [comment]
okay let's hope that fixed it (those changes are from a branch i deleted)

**Comment by mirrorcult** [comment]
im not a super big fan of this just in concept

**Comment by Scribbles0** [comment]
not a big fan of heterochromia or using the marking system to add it this way?

**Comment by mirrorcult** [comment]
heterochromia

**Comment by Scribbles0** [comment]
eh, a couple people seemed to want it and it is an IRL physical abnormality

**Comment by moonheart08** [comment]
@mirrorcult idk i like it and we can simply call people who use it poorly cringe.

**Pull request merged**
