### PR TITLE
1984 Cat Ears

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
## About the PR 
Syndi agents keep wasting their damn TC on this shit instead of doing the objectives.

**Screenshots**

**Changelog**

:cl: eclips_e
- remove: The Syndicate has withdrawn all Cat Ears from the Syndicate Uplink. Go do your objectives.

### CODE REVIEW

**Review by EmoGarbage404 — APPROVED** [review]
BASED

**Comment by Just-a-Unity-Dev** [comment]
Seriously though, current syndi's just butcher Renault and buy cat ears, do your objectives, not buy cat ears.

**Comment by EeveeTea** [comment]
Are you proposing adding it to the ClothesMate as a regular item? That would be a fantastic idea and make more sense than the current situation.

**Comment by EmoGarbage404** [comment]
> Are you proposing adding it to the ClothesMate as a regular item? That would be a fantastic idea and make more sense than the current situation.

no

**Comment by Just-a-Unity-Dev** [comment]
> Are you proposing adding it to the ClothesMate as a regular item? That would be a fantastic idea and make more sense than the current situation.

No.

**Comment by GoodWheatley** [comment]
> Are you proposing adding it to the ClothesMate as a regular item? That would be a fantastic idea and make more sense than the current situation.

No. Absolutely not.

**Comment by Visne** [comment]
Either do the emag thing (#10729) or don't merge this at all, imo. It would essentially completely remove cat ears from the game (as far as I know) and I'm not sure why that would be required.

**Comment by EmoGarbage404** [comment]
> Not sure what's purpose of this. If syndies buying this to flex / do gimmicks is a problem, nuke entire `UplinkPointless` category and it's contents. If not (and I believe it's not a problem), let syndies flex with their syndie skills and do their job. If they are "friendly" syndie, consider introducing antag bans.

not really opposed to nuking all the pointless uplink items. I rather they have new items which actually serve a purpose rather than pointless "drip".

**Comment by Visne** [comment]
I think flexing with "I still killed you all even though I spent half my points on cosmetics" is fine.

**Comment by Peptide90** [comment]
Agree with visne, yeah it might be annoying to your team mates but often syndie isn’t a team game, and the point of those items is to flex. Maybe it wouldn’t be so bad if I wasn’t made to make them like 20 TC, just makes it extra funny when they win. Hitman silent assassin style.

**Comment by Just-a-Unity-Dev** [comment]
okay how about I just make it 26 TC, to just dangle it infront of syndi agents even more

**Comment by Cheackraze** [comment]
im honestly better at greentext when i waste all my tc on drip and pointless crap, the objectives just kinda throw themselves at me when I do I have no fucking idea why

**Comment by EeveeTea** [comment]
Pretty sure Just-a-Unity-Dev and maybe EmoGarbage have something against me considering they opened this pull request immediately after denying mine (#10729). I made a reasonable argument that the cat ears fit better among the items in the ClothesMate, even while still being a syndie item, and wanted to promote further discussion on it. EmoGarbage just flat out denied it and closed the pull within 15 minutes. Meanwhile, this pull request is still open. They're both acting very immature, and not in a way I expect moderators to behave.

Makes me question whether I should finish my ghost radio/spirit box idea.

**Comment by EmoGarbage404** [comment]
This is from the original cat ears pr.
Screenshot_20220821-134759_Chrome

**Comment by EeveeTea** [comment]
You could've mentioned that earlier, I wasn't around when they were introduced. Still doesn't excuse the retaliatory pull request and your "BASED" first comment.

**Comment by mirrorcult** [comment]
> I think flexing with "I still killed you all even though I spent half my points on cosmetics" is fine.

this. i dont see any reason to remove them entirely, its a meme item like the syndie balloon was in SS13. if you want to nuke all pointless uplink items then make a PR for and justify that

**Pull request closed without merging**
