### PR TITLE
Pass through vehicle damage to rider

### LINKED ISSUE #10108: Vehicles need to pass through their damage to the rider
Right now they're extremely strong in melee due to being impervious to bullets.

### PR DESCRIPTION
**Pull request by jessicamaybe**
## About the PR 
Will pass through vehicle damage to the rider.

can be tweaked by changing "damageShare" on the vehicle if you want the vehicle to provide some protection

Fixes #10108

:cl:
- tweak: Vehicle damage will now get passed through to the rider.

### CODE REVIEW

**Comment by Elijahrane** [comment]
the rider can already take damage this just makes hitting the vehicle twice as good

**Comment by Snowyypanda** [comment]
terrible update

**Comment by mirrorcult** [comment]
> terrible update

pull requests are for code reviews and useful feedback only, do not spam this repository

**Comment by mirrorcult** [comment]
obsoleted by #10477

**Pull request closed without merging**
