### PR TITLE
Bring back tippy from april fools last year

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

Adds Tippy back for April's Fools! Get helpful tips from your local clown!
The majority of the work bringing back Tippy is thanks to #25315 and @QuietlyWhisper, I just did the last bit of code to get it working with the latest changes.

Summon Tippy with the `/tip` command. If you want to make some other item leave a helpful tip, use `/clippy <message> [entity prototype] [speak time] [animate time] [waddle]`.

## Why / Balance

Honk

## Technical details

Tippy is inserted into the Tips system, and has a system for appearing on the Client visually. 

## Media

https://github.com/space-wizards/space-station-14/assets/83650252/75f5e392-fb3a-4924-aa33-69fd5b79d1b5

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
FWIW, IMO - Tippy this is good enough to actually full-merge and keep

**Comment by CatMagic1** [comment]
mr slambam action man is it okay if we merge this on goob station (a fork(ish)) permanently
not sure if i actually have to ask for permission but it's your code

**Comment by Aexxie** [comment]
Yeah since it's a command idk why we can't just keep him xd

**Comment by LookyPadooky** [comment]
giving him a clippy or bonzi buddy style text to speech voice would be amazing

**Comment by LookyPadooky** [comment]
just remembered clippy doesn't actually have a voice........ but the bonzi buddy point still stands.....

**Comment by ThunderBear2006** [comment]
Tippy! Bring my boy back!

**Comment by metalgearsloth** [comment]
We really need tippy on main.

**Pull request merged**
