### PR TITLE
Added HoP's hardsuit!

### PR DESCRIPTION
**Pull request by Stanislav4ix**
## About the PR
Added HoP's hardsuit!

## Why / Balance
Head of personnel should have his own hardsuit for several reasons:
- First: almost all heads have their hardsuits.
- Second: the HoP's office on some maps is far away from the EVA storage.
- Third: it looks stylish, it also has almost no protection and most importantly does not slow down the wearer of this hardsuit.

## Technical details
Sprited by me, based on base hardsuit. HoP's closet now contains HoP's harsuit

## Media
equipped-OUTERCLOTHING
icon
equipped-HELMET
icon
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Lore
The best NT scientists decided to experiment and make a hardsuit out of fabric. They succeeded, it was light but had almost no protection from the external environment except for vacuum. They didn't want to just throw away what they made, so they decided to put these hardsuits in HoP's closets before changing the design. Now HoP is the happy owner of his own hardsuit. The end.

## My opinion
I believe that every department head should have his own hardsuit, regardless of which department he is the head of, in order not to die from the vacuum of space.

**Changelog**
:cl: Stanislav4ix
- add: Added HoP's hardsuit!

### CODE REVIEW

**Comment by UbaserB** [comment]
I swear i heard that this was in the game before and they removed it since the hop doesn’t need a hardsuit.

**Comment by Stanislav4ix** [comment]
> I swear i heard that this was in the game before and they removed it since the hop doesn’t need a hardsuit.

EVA suit sucks

**Comment by Kit0vras** [comment]
hop doesn’t need a hardsuit

**Comment by lzk228** [comment]
its already was discussed like gazillion times.
hop doesnt need a hardsuit

**Comment by asperger-sind** [comment]
> I swear i heard that this was in the game before and they removed it since the hop doesn’t need a hardsuit.

I don't think we've ever had hop hardsuit.

**Comment by K-Dynamic** [comment]
pr exists because eva suits suck ass with their current movement penalty :trollface:

**Comment by CrigCrag** [comment]
hop doesn't need to run around fast in spaced areas.

**Comment by Stanislav4ix** [comment]
Read "Lore" and "My opinion" pls

**Comment by GoodWheatley** [comment]
> Read "Lore" and "My opinion" pls

That still doesn’t explain why a job that primarily sits at a desk all round needs a hardsuit. The only reasoning you’ve given is “well every other head gets one so the HoP should get one too”, which is not a good argument.

**Comment by Aisu9** [comment]
powercreep, a love story between 80% of the player base and the few of them that decide to make content

**Comment by deathride58** [comment]
The EVA storage exists primarily for heads and other high-value individuals to be able to have some space protection when they otherwise wouldn't. This is simply redundant at best, powercreep at worst

**Comment by mirrorcult** [comment]
lore is neat but maintainer consensus is this isn't necessary

**Pull request closed without merging**
