### PR TITLE
Stop eating food if you drop it

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Stops the do-after for eating/drinking things if you drop the item from your hands

## Why / Balance

I'm tired of having to run away from my food to stop eating it, or accidentally eating papers in my hands

## Technical details

Sets the NeedHand argument for the do-after to true if the item started out in the user's hands

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/5f457fd7-db71-4bdc-a7bf-2fa8747e87e8

## Breaking changes

**Changelog**

:cl:
- fix: You can now drop food and drinks to stop consuming it.

### CODE REVIEW

**Comment by Plykiya** [comment]
test fail is TryStopNukeOpsFromConstantlyFailing, one day..... one day it'll stop failing

**Review by PJB3005 — COMMENTED** [review]
I would maybe add a comment explaining this behavior so it's more obvious. Otherwise looks good.

**Review by PJB3005 — APPROVED** [review]
The copy paste disgusts me but that's not your fault so.

**Comment by Plykiya** [comment]
> The copy paste disgusts me but that's not your fault so.

between the food and drink systems? yeah I don't really understand why they're separate despite doing the same thing

**Comment by IamVelcroboy** [comment]
We need something Ike this for drinking too. Really kills the immersion when you're trying to sip a drink on the bar and you just go full chug every time.

"chug" should be like an option instead of the default

**Comment by Plykiya** [comment]
> We need something Ike this for drinking too. Really kills the immersion when you're trying to sip a drink in the bar and you just go full chug every time.
> 
> "chug" should be like an option instead of the default

drinks are included in the PR

**Comment by IamVelcroboy** [comment]
> > We need something Ike this for drinking too. Really kills the immersion when you're trying to sip a drink in the bar and you just go full chug every time.
> > "chug" should be like an option instead of the default
> 
> drinks are included in the PR

Oh dang, I missed that!

**Pull request merged**
