### PR TITLE
Make puddle smoothing better

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Changes the puddle sprites so the ugly middle puddle doesnt have a huge corner sticking out

## Why / Balance

better sprites are good

## Media

https://github.com/space-wizards/space-station-14/assets/79580518/3c3c3c5a-c430-498f-a145-d653dfb7671a

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: potato1234_x
- tweak: Changed the puddle sprites so the smoothing is less jagged

### CODE REVIEW

**Comment by UbaserB** [comment]
feels more triangular

**Comment by Tayrtahn** [comment]
Can we see some before and after screenshots please?

**Comment by potato1234x** [comment]
> Can we see some before and after screenshots please?

before

https://github.com/space-wizards/space-station-14/assets/79580518/97ac6c72-07c0-48a1-997a-1872cfec9d48

**Comment by Tayrtahn** [comment]
Oh, that corner is pretty painful to look at, now that you point out it.

The new sprites make the overall puddle look a lot less square and grid-constrained. I like it!

**Review by EmoGarbage404 — APPROVED** [review]
sprites look good although i'd be interested in seeing how they look without the lighter streaks/highlights over all the textures. I think they look a bit busy at times.

**Comment by metalgearsloth** [comment]
finally someone did it.

**Pull request merged**
