### PR TITLE
Welding tweaks

### PR DESCRIPTION
**Pull request by Vermidia**
## Why / Balance

🐛, there was a discord issue on this but it's gone now.

## Technical details

- Fixes shards being weldable with an unlit welder.
- Moved and renable WelderRefinableComponent and RefinableSystem
- Minor cleanup of datafields, access and indentation 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Shouldn't be

**Changelog**

:cl:
- fix: Glass shards are no longer weldable with an unlit welder.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
shouldn't the welder code be checking for fuel regardless of if there is any cost to refine? Like if there's 0 fuel then won't it run out while refining?

**Comment by Vermidia** [comment]
I think it's a problem with the SharedToolSystem in this case
```
var doAfterArgs = new DoAfterArgs(EntityManager, user, delay / toolComponent.SpeedModifier, toolEvent, tool, target: target, used: tool)
 {
     BreakOnDamage = true,
     BreakOnMove = true,
     BreakOnWeightlessMove = false,
     NeedHand = tool != user,
     AttemptFrequency = fuel > 0 ? AttemptFrequency.EveryTick : AttemptFrequency.Never
 };
 ```
 Since it's 0, it never raises an event.

**Comment by EmoGarbage404** [comment]
`SharedToolSystem.CanStartToolUse` should still be checking that. Probably should be under `ToolUseAttemptEvent`.

**Comment by Vermidia** [comment]
Changed it so fuel is passed into ToolUseAttemptEvent, and that SharedToolSystem.Welder uses that event for its OnWelderToolUseAttempt. This fixes it and still makes it work for other things (construction, borg welding), with the small cavet that the pop-up messages don't seem to appear? This happens with the borg and glass shards.

**Comment by Vermidia** [comment]
Disregard the previous attempt, it broke things. Simplified it into simply adding a check in CanStartToolUse for the component and outting and checking that for AttemptFrequency as suggested.

**Comment by AJCM-git** [comment]
Alright did some (major) changes but this works crisp now

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
