### PR TITLE
Adjust Mindshield Pricing

### PR DESCRIPTION
**Pull request by ImWeax**
## About the PR

Decreased the amount of Mindshields provided in Mindshield crates to 2 down from the original 3.
Increased the price of Mindshield crates to 5000 credits, up from 3000, effectively raising the price per Mindshield from 1000 to 2500.
Updated the description of Mindshield crates to reflect the new amount contained.

## Why / Balance

With the newer SecHud changes allowing officers to see who is and is not mindshielded, this has led to there being a rush for Cargo to order as many mindshields as possible for the rest of the round as soon as security suspects revolutionaries at any point.

This is detrimental to the round as it makes the job of the head revolutionaries a lot more difficult as over half the station can quickly become immune to conversion. It also means Cargo is forced to spend all of their credits constantly on new mindshields, until the entire station is inevitably shielded. 

This change aims to disincentivize Security / Command forcing Cargo to essentially mindshield the entire station, and reserve what limited mindshields are available for those suspected of being a revolutionary. A single bounty currently is enough to buy several mindshield crates. This change should allow the amount ordered to be more reasonable.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: Weax
- tweak: The amount of Mindshields provided in Mindshield crates has been decreased.
- tweak: The price of Mindshield crates has been increased.

### CODE REVIEW

**Comment by Rainbeon** [comment]
This does nothing but make it near impossible for Sec to actually win a Revs round reasonably without resorting to frowned upon tactics. Mindshields are the counterplay for Revs, making them more substantially more expensive means Revs are going to be stuck in the Brig for faaaar longer doing absolutely nothing while waiting for Cargo to get 5k for a measly 2 shields. It'll also lead to rounds spiralling hopelessly out of control quicker and the harder you make this counterplay option for Sec, the quicker it devolves into the other kind of counterplay (murder everyone and hope you kill all the Heads).

Making non-lethal Sec counterplay almost impossible is not the answer, and would rather see a more dynamic counterplay option for Revs (perhaps make mindshields removable in non-Heads with the use of implanters? Sec can see if this happens with their fancy sec HUDs now so it shouldn't be as much of a problem as it would've been before where it was all assumption based)

**Comment by Hmeister-fake** [comment]
i like this.

**Comment by Emisse** [comment]
argh argh ahoy i dont be likin this me matey in isolation perhaps ye be proposin other balance chances at the same time ye ahoy

**Comment by deltanedas** [comment]
> people eventually unscramble their brains on their own unless they're re-flashed? 

that would be a completely nightmare for headrevs

forgot about 1 guy for too long? hes now given sec name of every headrev and rev

**Comment by ImWeax** [comment]
> If mindshields are really expensive, people being perma-flashed might want to be looked at too, maybe making it so that people eventually unscramble their brains on their own unless they're re-flashed? That'd allow security to just have the option of _being good at security_ and waiting out/beating the revs.

Currently head-revs are limited by how many flashes they can get their hands on. I think perhaps the means headrevs have to convert crew members should also be looked at. Maybe a flash pen that they need to recharge, or something along the likes.

This PR is mainly to discourage forcing cargo to order mindshields en-masse. Security should definitely be detaining revolutionaries. They have large amounts of crowd control at their disposal from round-start, as opposed to headrevs who need to constantly risk outing themselves and starting the onslaught of mindshield orders from cargo, effectively making the round impossible to win. Another suggestion is maybe mindshields should have durability, and only survive a certain amount of flashes before failing.

**Comment by Jezithyr** [comment]
>  Mind-shields are the counterplay for Revs
Mind-shields are not counter-play, they completely nullify rev's core mechanic. If everyone important on the station has mind-shields then it is effectively impossible for revs to win.

 Additionally, mind-shields don't create any gameplay, they do the oppsosite. Simply installing an implant to completely nullify an antagonist's ability is bad design since it just creates a situation where the entire round revolves around acquiring as many mind-shields as possible and not actually engaging in the cat-and-mouse gameplay that revs are supposed to create.

**Comment by Jezithyr** [comment]
> forgot about 1 guy for too long? hes now given sec name of every headrev and rev

Sounds like a skill issue :P (jk)
IMO if you have that much of the station converted that you are forgetting who you actually converted then you are probably pretty close to overwhelming security anyways so I doubt this would matter.

 It might be a good idea to implement some sort of tracking/timer so that they headrev could get reminders of whose flash is expiring soon....

**Comment by Rainbeon** [comment]
> > Mind-shields are the counterplay for Revs
> 
> Mind-shields are not counter-play, they completely nullify rev's core mechanic. If everyone important on the station has mind-shields then it is effectively impossible for revs to win.

Just because it is currently strong counterplay does not mean it is not counterplay. It is Sec's current move against Revs besides Mass Murder. And I agree with the last bit of that, which is why I suggested making mind-shields removable by implanter in that same post...

**Pull request closed without merging**
