### PR TITLE
Changes the RCD to construct empty light fixtures

### LINKED ISSUE #28349: RCD can spam out hundreds of lights on the same tile real quick.
## Description
Engies will spam the RCD light or other object on a single tile till the lighting starts getting sketchy.

**Reproduction**
Get rcd build a shit ton of lights on the same tile.

**Screenshots**
image

**Additional context**
NA

### PR DESCRIPTION
**Pull request by Lamrr**
## About the PR

Changes the RCD to construct empty light fixtures, instead of light fixtures pre-inserted with tubes/bulbs
Fixes #28349

## Why / Balance

The ability to construct many active light fixtures in parallel allowed players to spam out light sources too quickly. This is of particular concern due to the performance impact of lights. Now light fixtures come constructed empty, with tubes/bulbs having to be inserted afterwards by hand. This significantly raises the barrier to spamming. 

Construction cost has been halved to compensate for the changes.

It's worth noting that perhaps the broader problem with the RCD is the fact that you can preform an large amount of parallel actions at once (limited only by the amount of free space around you). Maybe this should be changed to a one action at a time approach, however that's outside the scope of this PR and would likely require further design disscussion _after_ the feature freeze.

## Media

Screenshot from 2024-05-29 01-04-30

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Light fixtures constructed by the RCD are now empty

### CODE REVIEW

**Comment by Lamrr** [comment]
> This shouldn't be an issue to begin with given the RCD enforces one fixture per tile (does it do that?)

It definitely does not do that (I did not know that was intended behaviour), you can see it doing the opposite of that in the linked issue.

**Comment by Lamrr** [comment]
> would be better to make it respect the fixtures (also just making lights not be able to be placed off of walls to begin with)

This might be a 'AND' situation, even with fixture restrictions the RCD could spam out a lot of lights. You  could still place three lights on a wall in a second, move three tiles repeat.

 IMO the time + material cost of constructing new lights should somewhat reflect their performance cost in game as a disincentive to using too many.

**Comment by moonheart08** [comment]
> > would be better to make it respect the fixtures (also just making lights not be able to be placed off of walls to begin with)
> 
> This might be a 'AND' situation, even with fixture restrictions the RCD could spam out a lot of lights. You could still place three lights on a wall in a second, move three tiles repeat.
> 
> IMO the time + material cost of constructing new lights should somewhat reflect their performance cost in game as a disincentive to using too many.

It's a much less significant issue if you can't just place them literally anywhere.  There's only so many walls in a room.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
what emo and moony said

**Comment by Lamrr** [comment]
I'm closing this as I unfortunately don't have the time go through and fix it as requested. One possible solution would be to make RCD's respect the existing construction system's placement restrictions instead of running its own checks in RCDSystem which seems to hold a host of problems including this and #28369

**Pull request closed without merging**
