### PR TITLE
Dummy proof China Lake

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

China lake ammo now explodes on the location you aim at and does not explode if it collides with an entity before coming within +/- 0.75 tile of the place you aimed at.
This change aims to fix the unwieldiness of the china lake and make it a more reliable and consistent weapon.

## Why / Balance

China lakes are quite accident prone because of the amount of unexpected things that are able to get in the path of your projectile, for example: 
- A crit person/animal right in front of your feet or or in a dark spot.
- Your nukie teammate making an unexpected move the moment you decide to fire
- The hitbox of the object you're peeking from extending a little bit further than the sprite

After this PR abovementioned situations will just end up in you wasting one of your bullets instead of it blowing up in your face.

## Technical details

Added the aptly named TriggerWhenReachingCoordinatesComponent, adding this component to an entity will trigger it whenever it passes the location the shooter was aiming at.
Currently the destination gets added whenever a projectile is shot so it doesn't work on thrown objects.
Above mentioned component has been added to the china lake ammo and TriggerOnCollide has been removed from said ammo.
With TriggerOnCollide removed the shot projectile won't explode and just get deleted if it collides with any entity that's not within +/- 0.75 tile of the place the user clicked when they shot.

## Media

https://github.com/space-wizards/space-station-14/assets/137322659/b74a713a-6f5e-4e00-b8c2-1edbf07df50d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- tweak: Projectiles now explode on the aimed location and don't explode if they collide with any entity before reaching said location.

### CODE REVIEW

**Comment by lzk228** [comment]
pjb once said
> remove that rp changelog

or something like that:trollface:

**Comment by JoeHammad1844** [comment]
i think having the projectile completely disintegrate sucks a lot because you have so few rounds, it suck to be aimed like 3 pixels off your target into something and have it just not explode.

it should pierce anything and explode exactly where you clicked, with the exception of walls but not windows (maybe)

**Comment by JoeHammad1844** [comment]
the pre detonation is a great plus, though

**Comment by VektorZ1** [comment]
It looks weird.
I think it's supposed to be a new weapon

**Comment by EmoGarbage404** [comment]
The hugbox is unreal.

**Comment by deltanedas** [comment]
ok but only sosa is able to use china lake properly right now, everyone else suicides

**Comment by Errant-4** [comment]
I have no opinion on making the china lake safer, but the mechanical approach used does not seem to achieve the stated goals of this PR.

-If a user unwisely fires at a too nearby target, the grenade will still injure them (and any ally around them) because the impact point matched "expectations" of the safety feature, but not the expectations of someone thinking the weapon is "safe"
-If a user fires at a target behind something like a table or counter, and the grenade hits the obstacle even just 1 tile before the target, the grenade will not explode contrary to user expectation.
-If the user fires at a group of people, the grenade will fail to explode unless the closest person was specifically targeted. This too is contrary to user expectations who just wanted to kill everyone in that general area. That's what a chinalake is for.

It might be a better idea to make the grenade detonate on impact as before, but only if it's beyond a predetermined "safe range"

**Comment by HoidC** [comment]
> The hugbox is unreal.

a grenade should not snag on someone who is on the ground (and in crit)

**Comment by EmoGarbage404** [comment]
> > The hugbox is unreal.
> 
> a grenade should not snag on someone who is on the ground (and in crit)

Then fix that instead of making it so that the game xovers for your ass whenever you make a shot that gets blocked.

**Comment by TurboTrackerss14** [comment]
Instead of the projectile getting ated. 
Just make it have a minimum arming range (so that shooter doesn't kill themselves due to shooting wall) exactly linked to +1 of the explosion radius. (no fucking clue how this would be coded but shh)

Having the player decide EXACTLY where a grenade laucher detonates it wicked powerful for anyone with even a moderate level of competence with the chinalake

**Comment by GoodWheatley** [comment]
This should be a expensive special type of ammo instead of being applied to the china lake as a whole, being able to precisely control where a grenade explodes is *extremely* powerful for skilled players.

**Comment by GoodWheatley** [comment]
> > > The hugbox is unreal.
> > 
> > 
> > a grenade should not snag on someone who is on the ground (and in crit)
> 
> Then fix that instead of making it so that the game covers for your ass whenever you make a shot that gets blocked.

There’s already a PR for this, https://github.com/space-wizards/space-station-14/pull/21511

**Comment by Arendian** [comment]
> it suck to be aimed like 3 pixels off your target into something and have it just not explode.

Currently if the projectile comes into contact within 0.75-1(most hitboxes extend a bit beyond their sprite) tile of where you aimed it will still detonate before colliding into said entity so you have to be aiming almost 1 tile away from where it collides with someone for it to be deleted. 
For example: aiming at the middle of a wall will still make it explode since it will attempt to collide around 0.5 tile from where you aimed, which is lower than the distance that's currently set(1 tile).
This "grace distance" can easily be increased if needed since it's just 1 variable.

> it should pierce anything and explode exactly where you clicked, with the exception of walls but not windows (maybe)

In another currently open PR I add 2 types of china lake ammo that penetrate mobs before reaching their detonation area, the explosive ones not penetrating is an attempt at differentiating these a bit more.
If it's more consistent to have all ammo act the same you can ignore this point.

> I think it's supposed to be a new weapon

I kind of had this feeling too(maybe a more high-tech  launcher) since proximity based ammo does not really fit the rustic look of the china lake, but I guess you could also see it as lobbing it at the floor instead of detonating it mid-air at the exact range you were aiming.

> The hugbox is unreal.

Sometimes some form of hugbox does improve gameplay, but I see where you're coming from.

> It might be a better approach to make the grenade detonate on impact as before, but only if it's beyond a predetermined "safe range"

I can easily convert it to this, it does sound a bit more like how other games with a china lake like launcher handle it.

> Instead of the projectile getting ated. Just make it have a minimum arming range (so that shooter doesn't kill themselves due to shooting wall) exactly linked to +1 of the explosion radius. (no fucking clue how this would be coded but shh)

If I do this I will probably make it a static distance instead of basing it on the explosion radius, except if the math for basing it on the explosion radius is easier than it sounds.

> > a grenade should not snag on someone who is on the ground (and in crit)
> 
> Then fix that instead of making it so that the game covers for your ass whenever you make a shot that gets blocked.

I think there is already an open PR for this.

**Comment by Anzarot121** [comment]
Why should a skill issue be solved mechanically at all?

**Comment by deltanedas** [comment]
because only 1 player is able to use it properly

**Comment by Anzarot121** [comment]
Only one person on your server. I regularly see it used correctly. I use it myself, although I explode 1 out of 10 times.

**Comment by asperger-sind** [comment]
> because only 1 player is able to use it properly

im all up for a grenade launcher to have a high skill requirement, besides, this is an exaggeration

**Comment by JoeHammad1844** [comment]
you know, the XM25 was basically this exact thing 
image

**Comment by keronshb** [comment]
This is not the correct fix for this. It mentions not hitting crit people and we have a PR up for that https://github.com/space-wizards/space-station-14/pull/21511

**Comment by JoeHammad1844** [comment]
china lake slug rounds when

**Pull request closed without merging**
