### PR TITLE
New sprite for the arachnid plushie.

### PR DESCRIPTION
**Pull request by PixelTheKermit**
## About the PR

Changed the sprite for the arachnid plushie.

## Why / Balance

I thought the old one kinda sucked, no offense to the original spriter.

## Technical details

N/A

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Just proving it works.
image

## Breaking changes

**Changelog**

:cl:PixelTK
- tweak: The arachnid plushie now has a new sprite.

### CODE REVIEW

**Comment by Krunklehorn** [comment]
I prefer the old one :X

**Comment by UbaserB** [comment]
this new one is a big improvement, but the sprite is a little unclear. Maybe make the back legs/arms a bit darker for contrast?

**Comment by PixelTheKermit** [comment]
> this new one is a big improvement, but the sprite is a little unclear. Maybe make the back legs/arms a bit darker for contrast?

I think you mean the appendages?
Anyways, does this look better, or does it need to be darker?

image

**Comment by PixelTheKermit** [comment]
> > this new one is a big improvement, but the sprite is a little unclear. Maybe make the back legs/arms a bit darker for contrast?
> 
> I think you mean the appendages? Anyways, does this look better, or does it need to be darker?
> 
> image

image
Here it is in-game (I think it looks better.)

**Comment by K-Dynamic** [comment]
I like it, but proportions and pose seem a bit off compared to other humanoid plushies (human and nukie specifically)

**Pull request merged**
