### PR TITLE
AI can use fire alarm

### PR DESCRIPTION
**Pull request by qwerltaz**
## About the PR

ai can use fire alarm

## Why / Balance

Really useful for ai. It was missed when adding ai whitelists I think. 

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: AI can now use fire alarms.

### CODE REVIEW

**Comment by ScarKy0** [comment]
Wait, the fire alarm actually does anything?

**Comment by thebadman4662** [comment]
Its been and still is broken for months I believe?

**Comment by slarticodefast** [comment]
Tested in-game and works as intended.

>Its been and still is broken for months I believe?

You can left click on them and the airlocks connected to the alarm close. Or is it supposed to do something else?

**Review by slarticodefast — APPROVED** [review]

**Comment by thebadman4662** [comment]
> Tested in-game and works as intended.
> 
> > Its been and still is broken for months I believe?
> 
> You can left click on them and the airlocks connected to the alarm close. Or is it supposed to do something else?

I suppose I never bothered to check in-game if it got fixed but my issue was marked as if it was, so I suppose it is after all. https://github.com/space-wizards/space-station-14/issues/28940#event-13221062916

**Comment by slarticodefast** [comment]
Thank you for your contribution!

**Comment by slarticodefast** [comment]
Oh, before merging, could you add a changelog to your PR description?

**Comment by qwerltaz** [comment]
> Oh, before merging, could you add a changelog to your PR description?

Done

**Comment by slarticodefast** [comment]
Thanks!

**Comment by thebadman4662** [comment]
> Tested in-game and works as intended.
> 
> > Its been and still is broken for months I believe?
> 
> You can left click on them and the airlocks connected to the alarm close. Or is it supposed to do something else?

So I did get to use fire alarm finally and they fail to do their job cause they are only partially fixed. 😅 https://github.com/space-wizards/space-station-14/issues/32859

**Pull request merged**
