### PR TITLE
Adds navmap beacon for escape pods

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Title

## Why / Balance
Seems like a useful thing for players to be able to find on the map.

## Technical details
n/a

## Media
n/a

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**
n/a

### CODE REVIEW

**Comment by deltanedas** [comment]
have to add to the pod yml too but maybe separate pr

**Comment by IamVelcroboy** [comment]
Oh, you mean like, add the beacon to the pod itself....I didn't even think of that. I was just thinking of putting these on the station near where the pods spawn...

**Comment by IamVelcroboy** [comment]
It's not the worst idea but I'm out of time to do it right now. I'll wait and see if anyone else likes that idea and maybe adjust when I have some time again.

**Comment by UbaserB** [comment]
yeah this is kind of iffy but as long as mappers dont actually put it on the pod itself, it should be fine

**Comment by deltanedas** [comment]
>  mappers dont actually put it on the pod itself, it should be fine

oh i just realised putting on the pod would hide it from the station map :trollface:

**Comment by IamVelcroboy** [comment]
> > mappers dont actually put it on the pod itself, it should be fine
> 
> oh i just realised putting on the pod would hide it from the station map :trollface:

Haha, yeah, didn't even think of that either, different grids... 🙃

**Comment by metalgearsloth** [comment]
Wouldn't you just put it on the dock airlock instead?

**Comment by deltanedas** [comment]
yes anything that is on the grid

**Pull request merged**
