### PR TITLE
Remove Geras from Slimes to address combat balance

### PR DESCRIPTION
**Pull request by Jezithyr**
## About the PR

Removes the Geras ability from Slimes. This was originally done as part of the Human-Only nukies revert but was broken out into a separate PR because it is a separate balancing change. 

## Why / Balance

It's being removed in it's current form due to it giving a large combat advantage to Slimes (Specifically making it easier to escape capture from stuns). This was brought up as a balance issue with nukie slimes but it extends to other antags and combat focused-roles. In the future it may be possible that Geras returns but right now it creates a large power-difference between slime and non-slime antags.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed the Geras ability from Slimes

### CODE REVIEW

**Comment by TheShuEd** [comment]
I would just add 2-3 seconds of doafter to the transformation, which would make it impossible to use the ability during combat 
I don't REALLY like that one of the coolest features of the species is turned off.

**Comment by LankLTE** [comment]
Excluding combat balance there’s also various issues of Geras being very buggy with no intent from the author to fix it, and being (in my opinion) far too similar to Nymphs in design. There’s some other lesser issues like distinguishing them from hostile simple mobs as well. 
I’m all for slimes having some unique features but I don’t think Geras is a good one. If anyone has better ideas I’d love to hear them.

**Comment by Thurtik** [comment]
What if they moved slower instead of faster than humanoid form? I've always found it weird that just a blob of slime (not too far from a snail or slug if you think about it) is able to crawl faster than something that walks on legs

**Comment by HelpTheSteak** [comment]
I'm not sure why geras are even being considered being removed when 1. You lose any action besides a weak attack and moving the same speed as you already were without a hardsuit or duffel. 2. You are still weak to bullets and be stunned 3. Sec are allowed to use lethals on you as soon as you go geras 4. You lose all your armor and guns and headset and Id besides the one or two things you put in your internal storage

**Comment by HelpTheSteak** [comment]
If there is a movement increase its very small since I have had people catch up to me before

**Comment by Djungelskog2** [comment]
Ive never seen geras really be creatively used outside of slipping out of cuffs, and ive literally not used it (on purpose) ONCE as crew because it serves no functionality to me. Not to mention how annoying it is when i press 2 to scream and whup! all my items drop on the floor, and how it defaults to 2 after you swap back. Last note: its still super buggy and lots of its promised functionalities are still missing which I doubt are getting added anytime soon

**Comment by HelpTheSteak** [comment]
I mean technically you can use geras to get 2 lives as a zombie since when you get killed as a geras you switch back to your human form who immediately gets reinfected thus giving you full health

**Comment by EdenTheLiznerd** [comment]
If I remember correctly, Geras have the ability to just... Delete station critical equipment without very much effort as well

**Comment by HelpTheSteak** [comment]
> If I remember correctly, Geras have the ability to just... Delete station critical equipment without very much effort as well

Huh?

**Comment by Clonko** [comment]
Even though the original developer of the geras PR isnt doing bugfixes there are PRs to fix bugs with them (also stuff like the speed is bugged too, so they have the same movement speed as slime-people). 

Though I'd also rather something to replace em as they're not the most interesting mechanic.(You'd have to plan ahead to make any use out of it, also only really worth it to traitors, or shitters as its 90% just avoiding stuns right now as losing all your stuff isnt worth it to most jobs, even with the threat its better to just run, combat wise atleast.)

The PRs in question here: #28941 #27417

**Comment by GoodWheatley** [comment]
> If I remember correctly, Geras have the ability to just... Delete station critical equipment without very much effort as well

There isn’t any bug report, open or closed, that reports geras transformations being able to delete items. If this behavior is still present in the game, please make a proper bug report for it.

**Comment by Just-a-Unity-Dev** [comment]
I'm fine with geras being removed because I did _not_ expect polymorph to be jank, I would however enjoy it to be ironed out as (like what @HelpTheSteak said) it's a complete negative that I've not seen many slimes use whilst spectating outside of shittery. (mfw I'm playing sec and I get trolled by a slime that immediately goes geras when we hit them with a stun baton, preventing them from being cuffed)

**Review by LankLTE — APPROVED** [review]
Maintainers have agreed that, on top of the combat balance discussed in this PR, Geras are also largely broken, and polymorph has a wide array of issues that make it unsuitable to use for a full species. Geras generally aren't used in-game for anything past just messing around or escaping as an antag, and there's also issues with it as a feature being too similar to nymphs. I personally feel slimes would be better suited with something more interesting and unique, and encourage people to come up with / code something like that.

**Comment by lemonrat-1** [comment]
haha, made a github account specifically to comment on this...
i use geras a lot for roleplay reasons. when people geras to escape stuns/cuffs, can't you just pick them up? and maybe make the geras weaker than it already is! I dont know, i just really don't wanna see this feature get removed. I really enjoy it.

**Comment by Anzarot121** [comment]
So now slimes are just a race with debuffs?

**Comment by TheShuEd** [comment]
Yep, waiting for other, less broken mechanics for the species

**Pull request merged**
