### PR TITLE
Plushie fix + addition

### PR DESCRIPTION
**Pull request by KyuPolaris**
## About the PR
Fixed plushies that failed to make their appropriate noises when activated or thrown. Added new "creature plushie"

## Why / Balance
Fixes were found while adding "creature plushie", now all plushies should work as intended

## Technical details

Plushies now use appropriate EmitSound functions when they were on previous EmitSound functions

## Media
image
https://medal.tv/games/requested/clips/1VJ5ayME_DVQZQ/d1337GqT9avn?invite=cr-MSxvTTQsMTY0NzEyMjEs

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
n/a

**Changelog**
:cl:
- add: creature plushie
- add: muffled ian noise for atmosian
- fix: fixed some plushie sounds not playing as intended

### CODE REVIEW

**Comment by Plykiya** [comment]
the two test fails are related to a Vox's quack.ogg, the code didn't change either of those so it should be fine...

**Comment by FairlySadPanda** [comment]
merge this immediately, don't let the copyright police arrive and 1984 this

**Comment by UbaserB** [comment]
Why are there so many different changes in a pr meant for a plushie addition

**Comment by metalgearsloth** [comment]
Your changelog is mangled, also split this pr out please.

**Comment by KyuPolaris** [comment]
> Why are there so many different changes in a pr meant for a plushie addition

I found that a handful of the plushies weren't triggering the right sound as they should

**Comment by KyuPolaris** [comment]
> Your changelog is mangled, also split this pr out please.

Apologies, this was my first PR. I will clean it up when I get home from work

**Comment by IProduceWidgets** [comment]
Why remove the IanToy ?

**Comment by KyuPolaris** [comment]
Ian toy was not removed but moved a little bit up as while it's a figure
it's based off of the plushies

**Pull request closed without merging**
