### PR TITLE
Update robotics headset to include binary channel

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Updates robotech encryption key to use the Binary channel
Updates Robotics Headset to include science and robotech encryption keys.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Robotics headset now lets you talk to robots!

### CODE REVIEW

**Comment by LankLTE** [comment]
No idea of how people feel about this balance wise, but RD should probably get this too if robotocists are since they’re supposed to manage the Borgs in place of AI.

Changelog should probably be more clear because “talk to robots” sounds like you’re just saying Hi in person which you can already do

**Comment by DogZeroX** [comment]
Binary is supposed to be robot only, that's why it is... binary.

**Comment by IProduceWidgets** [comment]
No strong opinion one way or the other on balance, but I figured I should at least update the robo encryption key since currently it is just a reskinned science encryption key. If we decide against binary channel for humans then I can yoink the robotics headset out of the RoboDrobe as it doesn't make much sense to be otherwise.  

As an aside, Binary channel currently is like any other radio channel where the borgs just whisper into the radio and humans can hear it if close enough.

**Comment by NancokPS2** [comment]
I remember nyanotransen having this, and the logic was that roboticists have their own human to robot translation system.  
Which makes sense if you're the one MAKING the robots. Being able to listen and decode their binary messages makes sense when you are the one programming them in the first place.  
  
Maybe in the future it could be a bit more nuanced, like requiring an extra addon in your PDA (wireless interception?) or something like that.    
  
What i'm not sure is what purpose this would serve, maybe recalling robots for maintenance and whatnot? I mean, clown and mime have service channel and i'm not sure how justified that is either.

**Comment by LankLTE** [comment]
I kind of think it’s at least more interesting to have robots given their own channel the crew don’t have access to, both gameplay wise and logically. Maybe give traitors access for TC since I’ve heard some servers do that. Regardless I don’t have super strong opinions on this because I doubt it’ll change much

**Comment by Equivocateur** [comment]
Wont go well long-term with malf AI and whatnot.
For RP reasons I think there should be an RD-only console that can read binary comms. And the binary translator key only available to traitors via the syndicate uplink.

**Comment by PJB3005** [comment]
Binary channel in headset is literally a traitor item in SS13.

**Comment by JustCone14** [comment]
I don't think crew should have access to the Binary channel at all. Or there should be some sort of console that only the RD has access to so they can read but not chat with the robots.

**Comment by Errant-4** [comment]
Even if we added this we will probably just have to remove it the moment AI is in and can be traitor.

**Comment by hord-brayden** [comment]
Though this is closed - does this have any relevance to the suit senor 'binary' channel?

**Comment by Emisse** [comment]
binary on suit sensor refers to alive or dead

**Comment by QuietlyWhisper** [comment]
I didn't catch this pr in the sea of prs, but robotics encryption key was going to be converted into the binary translator key for science to print and use in the original design.

**Pull request closed without merging**
