### PR TITLE
Non-lethal double-barreled shotgun for booze storage

### PR DESCRIPTION
**Pull request by lapatison**
## About the PR

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Double-barreled shotgun from bartenders booze storage has been replaced with non-lethal version

### CODE REVIEW

**Comment by Snowyypanda** [comment]
lEtS bAbY pRoOf ThE gAmE ThAt SoUnDs LiKe FuN

**Comment by mirrorcult** [comment]
dont spam useless shit on github

**Comment by deltanedas** [comment]
merg, doesnt make much sense to have 2 lethal + 24 nonlethal shells

**Comment by lapatison** [comment]
How can I request a review?

**Pull request merged**
