### PR TITLE
Nerfed supermatter, minibomb, and syndiebomb prices

### PR DESCRIPTION
**Pull request by Eden077**
## About the PR
 I have raised the minibomb and supermatter bomb to 8, the Syndie Bomb has been raised to 15 telecrystals in the uplink. (This is a Band-Aid PR, it will be reverted once a proper fix/system is in place)

## Why / Balance
 I did this as to discourage shuttle bombing and leaving giant craters inside the station, Syndie Bomb price was done so you can't buy two  bombs by gibbing Renault. It will also encourage different strategies as Syndie instead of relying on shuttle bombing and departmental destruction. The only reason I haven't touched C-4 is because the timer is high enough to expect security to throw it somewhere else before it explodes

## Technical details
 It was a few simple changes to the uplink catalogue, I only changed the uplink prices for the items listed above

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: EdenTheLiznerd
- tweak: The Syndicate has raised the prices on their minibombs, supermatter bombs and syndiebombs as to discourage wasting precious resources on NT shuttles

### CODE REVIEW

**Comment by HoidC** [comment]
is there not a better solution to this specific problem than hard gutting explosives

**Comment by Eden077** [comment]
Until a better system can be designed and shuttle bombing can be curbed I don't believe so, I'm fully willing to bring explosives back to the original price when they can't shuttle bomb and do departmental destruction. I'm waiting for someone to improve the bomb defusal system so it isn't dumb luck

> is there not a better solution to this specific problem than hard gutting explosives

**Comment by deltanedas** [comment]
#20819

**Comment by Eden077** [comment]
> #20819

Yeah I saw this a bit ago, as I said, I'm awaiting for the system to be implemented before I revert the pricing, this is just a temporary Band-Aid for a bigger issue that I can't code

**Comment by deltanedas** [comment]
making them more expensive wont prevent using them to bomb evac

**Comment by Eden077** [comment]
> making them more expensive wont prevent using them to bomb evac

I've only nerfed them enough to curb a bit of shuttle bombing, this isn't to prevent it, I'm fine with people bombing the shuttle but within reason. Syndie Bombs are also used for shuttle-bombing and can be can be just well... too put it it bluntly, it's fucking busted, It bypasses EOD and RD suit and just gibs them outright, I'm trying to discourage shuttle-bombing and Syndie Bombs until a system is designed to fix them

**Comment by Eden077** [comment]
But yes I will immediately revert these back to their original values when a permanent and decent fix is brought to the table.

**Comment by deltanedas** [comment]
> It bypasses EOD and RD suit and just gibs them outright,

that was a bug which is now fixed i believe, explosion resistance was broken

**Comment by Eden077** [comment]
> > It bypasses EOD and RD suit and just gibs them outright,
> 
> that was a bug which is now fixed i believe, explosion resistance was broken

From what I've heard it's still occurring, I'll need to do some digging later, but the armor bypass isn't the worst part, the system of defusal and how big the explosion is where our problem is right now, it's pure luck if you can defuse the bomb or not

**Comment by Eden077** [comment]
I just tested the Syndie Bomb, it indeed still bypasses full EOD armor

**Comment by deltanedas** [comment]
https://github.com/space-wizards/space-station-14/pull/20816

this was merged 3 hours did you test after that commit

**Comment by Eden077** [comment]
> #20816
> 
> this was merged 3 hours did you test after that commit

Hm... unsure, I'll do an additional test

**Comment by Eden077** [comment]
> #20816
> 
> this was merged 3 hours did you test after that commit
It hasn't been published yet

**Comment by deltanedas** [comment]
just merge master and compile

**Comment by asperger-sind** [comment]
While the syndicate bomb is a hard "maybe" and the suppermatter nade could (theoretically) use a tone-down in the explosion strength rather than price I can't help but to completely disagree with the minibomb as it's already a sub-optimal item and not a very good explosive for any purpose other than gibbing, which is to say a very niche way of roundending someone because of other options available.

If anything the minibomb should be reworked or have its price reduced to 5 as opposed to putting it up to 8, its not a good item and there should be changes to make it good rather than make it even worse.

**Comment by Eden077** [comment]
> While the syndicate bomb is a hard "maybe" and the suppermatter nade could (theoretically) use a tone-down in the explosion strength rather than price I can't help but to completely disagree with the minibomb as it's already a sub-optimal item and not a very good explosive for any purpose other than gibbing, which is to say a very niche way of roundending someone because of other options available.
> 
> If anything the minibomb should be reworked or have its price reduced to 5 as opposed to putting it up to 8, its not a good item and there should be changes to make it good rather than make it even worse.

It's problem is that it's used to space the evac shuttle, as I've said before it's all getting reverted once someone actually makes a proper system/fix

**Comment by asperger-sind** [comment]
> It's problem is that it's used to space the evac shuttle, as I've said before it's all getting reverted once someone actually makes a proper system/fix

It spaces 1 singular tile, 2 if you get lucky, if anything I don't think that nerfing explosives as a whole to bandaid evac shuttles is a good idea to begin with.

**Comment by deltanedas** [comment]
> It's problem is that it's used to space the evac shuttle

a wrench and a screwdriver can space the evac shuttle too, as can a c4
spacing evac is only an issue because the anti building mechanism doesnt let you repair anything

**Comment by Eden077** [comment]
Which is why I'll backdown and close/revert the PR if someone starts working on a system/workarounds for this issue

**Comment by JoeHammad1844** [comment]
im ''okay'' with increasing the syndie bomb price but there is no reason to change the minibomb price, youre just fucking over regular syndies at this point, the explosion isnt large and can be patched up very fast, the problem is that you cant repair the evac shuttle.

a better solution would be to make evac shuttles bigger, the most common one, the courser, is way too small for a high-pop server

**Comment by LankLTE** [comment]
There are a lot of solutions to shuttle bombing and this is the worst one

**Comment by asperger-sind** [comment]
> every single bomb mentioned is ass for their price at the current moment

someone revive #17292 please

**Comment by keronshb** [comment]
Don't make a bandaid fix. Instead, fix the actual problem. Also please explain what the full reasoning is behind this.

**Comment by Aisu9** [comment]
first issue, destructive power
second, too cheap for what they provide (linked to the first issue)
syndicate bomb was and i suppose still in discussion regarding proper balance, and give the ability to maximum two syndicates players from purchasing 2 department erasing device(if they decide to split renault's bounty). that only have a 55% chance of diffuse with protective armours that supposedly doesn't work as of right now. and every syndicate players can purchase at least one.
There should be a balance between structural destructive power and organic destructive power, and right now syndicate bombs are WAY TOO CHEAP for what they offer (let alone you can try to forcibly blow it up but falling the diffusing at the cost of your own life but that doesn't really matter)

**Comment by keronshb** [comment]
> first issue, destructive power

Bombs exist in all shapes and sizes in Space Station. Destructive power isn't really an issue, especially minibombs.

> second, too cheap for what they provide (linked to the first issue)

I'm not familiar with the supermatter bomb, but the big bomb up to 15 is a bit ridiculous.

> syndicate bomb was and i suppose still in discussion regarding proper balance, and give the ability to maximum two syndicates players from purchasing 2 department erasing device(if they decide to split renault's bounty). that only have a 55% chance of diffuse with protective armours that supposedly doesn't work as of right now. and every syndicate players can purchase at least one.

If the bomb suits aren't working, they should be fixed. Raising the TC of an item won't fix that issue. By the sounds of it, max caps aren't in yet and those are free to make.

I think Engineering's capability to fix the damage were brought up in the past. Another potential solution is to improve their ability to fix the station - but not to the extent where every destruction becomes trivial to fix.

**Comment by Aisu9** [comment]
super-matter grenades are microbomb with bigger radius, a vacumm effect AND doesn't gib people alone (and space more tiles)

So ultimately the issue doesn't reside in the price but the toughtness of walls and efficiency of the tools that are supposed to helps(because maxcaps sounds like it should not nukes the entire station)

**Comment by deltanedas** [comment]
only real issue with repairing syndie bombs is that it has a few detached grids which prevent repair and need an axe to remove, if it just fully removed those it would be quick fix for someone with the mats

**Comment by Just-a-Unity-Dev** [comment]
Why are we punishing players for going the extra effort to get 2 syndiebombs? Setting the price to 15 TC prevents a syndicate agent from buying anything useful and will just change the bomb's original purpose as a distraction to nothing but a griefing tool.

**Comment by mirrorcult** [comment]
this seems like a broadly unpopular solution for whatever problem its trying to solve and think i agree with the dissenters here

**Pull request closed without merging**
