### PR TITLE
Atmos devices are linkable

### PR DESCRIPTION
**Pull request by Tyzemol**
## About the PR 

**Screenshots**

https://user-images.githubusercontent.com/85772526/184541897-57ef3471-14d1-4f35-ac03-cc41bd9cc5d1.mp4

**Changelog**

:cl:
- add: pipe valves, pumps, thermomachines, filters and mixers are now linkable via multitool

### CODE REVIEW

**Comment by Elijahrane** [comment]
Seems like an OK implementation but isn't this a bit strange when there are air alarms that also control these, and are behind access locks?

**Comment by juliangiebel** [comment]
Air alarms don't control atmos devices @Elijahrane only scrubbers, vents and firelocks :|

**Comment by juliangiebel** [comment]
We talked about it on discord and this needs to be something you attach to the atmos device (at least visually) you want to link to so it's visible what devices have a link to something.

This is to prevent someone from secretly linking atmos devices and sabotaging atmos that way.

Players need to be able to remove the link by removing the object that was attached to the atmos device to create the link.

**Comment by Tyzemol** [comment]
> this needs to be something you attach to the atmos device (at least visually) you want to link to so it's visible what devices have a link to something.

Makes sense, so it would be fine to just add a little antenna with maybe a couple LEDs to a device to indicate it has been linked?
Also, thinking about it, how would one know _where_ the device is linked, it would be impossible to notice somebody linking to an atmos device, if it were already linked somewhere, that sounds like a problem i wouldn't be able to fix without actually knowing how to code, i could still look into trying to add a little antenna to linked devices though.

**Comment by metalgearsloth** [comment]
You coming back to this @Tyzemol ?

**Comment by Tyzemol** [comment]
> You coming back to this @Tyzemol ?

Yeah i dont think i am, at least not until i actually know how to code.
Adding the way to unlink a device sounds complicated.

**Pull request closed without merging**
