### PR TITLE
[FEAT: SPECIES] Dogs(canines)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About the PR
Adds the canine species with... a very... limited selection of options because A: I'm lazy and B: I'm also quite lazy.

There are a couple of issues that I'd like to address but I don't actually have a solid modularisation plan in place yet, lol:

- Make it so default markings can be removed.
- Make it so you can copy marking color and paste it into any other marking(apparently being done upstream).
- Make it so the sprite backend does not require you to... template out... a default.. human... so... BASICALLY HAVE OVERLAYS WORK IN A WAY THAT YOU CAN HAVE ONES BEHIND.

The above would require non-modular changes to the content pack which I... yeah, see above.

But at least this shows you how to add a species modularly.

**Media**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a new species: canines.

### CODE REVIEW

**Comment by DogZeroX** [comment]
this is the right repo.

**Comment by vulppine** [comment]
out of curiosity, what do you mean by the third point? the first two are doable in upstream, but the third point needs clarification

**Comment by Gandalf2k15** [comment]
> out of curiosity, what do you mean by the third point? the first two are doable in upstream, but the third point needs clarification

For some reason my brain wasn't working correctly, but in SS13, tails are rendered BEHIND the mob when facing south. I might be oblivious to this ability but currently it overlays ontop when facing south, and all other examples of tails have a human cutout of the south facing sprite.

**Comment by vulppine** [comment]
> > out of curiosity, what do you mean by the third point? the first two are doable in upstream, but the third point needs clarification
> 
> For some reason my brain wasn't working correctly, but in SS13, tails are rendered BEHIND the mob when facing south. I might be oblivious to this ability but currently it overlays ontop when facing south, and all other examples of tails have a human cutout of the south facing sprite.

iirc this does require changes to sprites so that you can have a single layer that reorders itself, otherwise you would need two different layers (this is how it was before when lizards were first added)

**Comment by Gandalf2k15** [comment]
> > > out of curiosity, what do you mean by the third point? the first two are doable in upstream, but the third point needs clarification
> > 
> > 
> > For some reason my brain wasn't working correctly, but in SS13, tails are rendered BEHIND the mob when facing south. I might be oblivious to this ability but currently it overlays ontop when facing south, and all other examples of tails have a human cutout of the south facing sprite.
> 
> iirc this does require changes to sprites so that you can have a single layer that reorders itself, otherwise you would need two different layers (this is how it was before when lizards were first added)

That appears to be the case, I don't know what's better. The old system of needing two layers would prevent edge cases where more markings or parts are overlapped by the tail.

**Comment by ElectroJr** [comment]
Direction dependent layer sorting is a feature that still needs to be added.

**Comment by vulppine** [comment]
> Direction dependent layer sorting is a feature that still needs to be added.

yeah i’d prefer this over doing double layers again (however, grouping multiple target layers to apply to in a single marking definition shouldn’t be impossible either)

**Pull request closed without merging**
