### PR TITLE
Health analyzers now show the user the chemicals inside the person being scanned

### PR DESCRIPTION
**Pull request by SpeltIncorrectyl**
## About the PR
* Health Analyzers readouts now have a section denoting the chemicals inside the scanned person.

## Why / Balance
Playing medical roles would greatly benefit from the ability to see what chemicals are in someone. This could be for reasons like treating poisons, avoiding overdoses or knowing when one course of drugs has finished to administer the next. It is also general QOL.

## Technical details
* Modified HealthAnalyzerScannedUserMessage (a struct that is sent from HealthAnalyzerSystem to HealthAnalyzerWindow) to have an extra nullable field called chemicals which stores a list of the chemicals in the scanned person.
* HealthAnalyzerSystem counts the chemicals in the scanned person and adds it to the HealthAnalyzerScannedUserMessage,
* HealthAnalyzerWindow reads the chemicals from the message, and handles if it is null (it its null it does nothing). If it's not null then it removes blood chemicals from the chemicals list (Blood, SpiderBlood, Slime, Water). If there is atleast one chemicals then it shows them all in a list.
* The HealthAnalyzerWindow is a bit larger to compensate for the extra space needed to display the chemicals.

## Media
Here is a video demonstrating scanning chemicals:
https://github.com/space-wizards/space-station-14/assets/66873282/412701e0-9c96-4006-8967-3abdb4a13d68

## Breaking changes
* HealthAnalyzerScannedUserMessage has an extra field called Chemicals which defaults to null and is handled if it's left to default to null (so maybe it's not actually breaking).

**Changelog**
:cl:
- tweak: Health analyzers (medical PDAs included) can now show you the chemicals inside someone.

### CODE REVIEW

**Comment by mirrorcult** [comment]
not in favor of this being on health analyzers at all, they do not need more power

**Comment by mirrorcult** [comment]
IMO if this functionality is to exist it should require placing them into a stationary machine, like sleepers in ss13 which showed a chemical readout

**Comment by SpeltIncorrectyl** [comment]
> IMO if this functionality is to exist it should require placing them into a stationary machine, like sleepers in ss13 which showed a chemical readout

That's too inconvenient, if it was implemented like that it would be used very rarely.

**Comment by mirrorcult** [comment]
not really? they're going to be in medbay anyway

**Comment by SpeltIncorrectyl** [comment]
> not really? they're going to be in medbay anyway
Sleepers themselves will be used to inject drugs, but using them just to see what drugs are in someone is too inconvenient to happen.

**Comment by Equivocateur** [comment]
> > IMO if this functionality is to exist it should require placing them into a stationary machine, like sleepers in ss13 which showed a chemical readout
> 
> That's too inconvenient.

Too bad! Having a single wonderscanner that tells everything EXACTLY about a person is *too* convenient!

**Comment by mirrorcult** [comment]
make your point without being a dick

**Comment by SpeltIncorrectyl** [comment]
Comparing this with giving mk58s to sec officers.
* That increased the firepower available to sec officers. You could (very weakly) argue that it is a QOL feature because sec officers don't have to ask the warden for a pistol, and therefore was more convenient, but that isn't a very good argument. It straight up made them more powerful (not saying that is bad, just using it as an example).
* Giving the health analyzer the ability to see chemicals inside someone can be argued as QOL because it is something that a doctor could theoretically do before, by guessing how many chemicals are in someone. They don't even have any new information (in a sense) - if you know how many chemicals you injected into someone (which you should know anyway), you know the metabolism rates (on the chempedia) and you know how much time is passed (all humans have an innate sense of the passing of time) then you can work out how many chemicals are in someone. However this is difficult, and adds mental load.

Is this a buff to medical? Yes. But is it as tangible as giving sec officers mk58s? No. There is no healing tool they start with in their pocket giving more powerful actions they can take. There is no new healing scanner that gives them information that they couldn't already work out with a bit of mental effort. This is why I believe this to be (in some part) a quality of life change.

**Comment by LankLTE** [comment]
I feel not knowing what Chems are inside of someone is part of the skill behind medbay. It’s typically possible to tell and it’s something you have to learn

**Comment by mirrorcult** [comment]
to be clear im very confident my opinion on this isnt going to change, this should not be on health analyzers

**Comment by Equivocateur** [comment]
> make your point without being a dick

I wont even figure out an excuse on this one, that's just an L on me, my bad.

> That increased the firepower available to sec officers. You could (very weakly) argue that it is a QOL feature because sec officers don't have to ask the warden for a pistol, and therefore was more convenient, but that isn't a very good argument.

#18006 was caused because security at the sight of anything that is A) ranged (nukies, traitors with a gun, etc) or B) reliably wins 1v1's (hostile ai mobs before #19475 and #19392) you'd either have to retreat (not doing security work) or beg warden for a gun and hope he greenlights that. Security getting a pistol roundstart is not much of a QoL than enabling security to do their work on the spot without dying in the process.

> There is no new healing scanner that gives them information that they couldn't already work out with a bit of mental effort. 

Why make something new if we have a [medical scanner machine](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Structures/Machines/medical_scanner.yml) that you can use for more detailed readouts on a person? Having the handheld/pda scan everything even further reduces the already low *depth* of medical. If they want a more detailed readout for some reason they should use that instead of a magical scanner in their pda that tells everything at once without any ambiguity.

**Comment by SpeltIncorrectyl** [comment]
Putting chemical scanning on health analyzers is too powerful.

**Comment by chromiumboy** [comment]
I like the idea of it, but I agree that this feature shouldn't be on health analyzers / PDAs, it should be a separate device instead

**Comment by lzk228** [comment]
alright, look, ss13 paradise build already did everything
we need a health analyzer upgrade, that like cartridge inserts in health analyzer and allow it scan chems

**Comment by SpeltIncorrectyl** [comment]
I thought I could reopen it as a draft

**Comment by SpeltIncorrectyl** [comment]
The idea of cartridge sounds good, I suppose balance could come from restricting the cartridge, but for now I'm going to close this pr. If I make it I will make a different pr for it, but the balance seems difficult, even impossible, so I don't think I will bother.

**Comment by SpeltIncorrectyl** [comment]
#19354, this pr aint it

**Pull request closed without merging**
