### PR TITLE
Cluster med refactor + un-abandoning of surgery room

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Refactored the cluster med(moved around the beds, added cryo, removed the inner walls) and un-abandoned the surgery room
## Why / Balance

image

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

**Changelog**

:cl: Boaz1111
- tweak: Refactored Cluster's medbay, including cryo in the bottom left room

### CODE REVIEW

**Comment by KashRas2** [comment]
Surgery room must be sterile, so it is better to remove the connection with the morgue, because bruh.

**Comment by KashRas2** [comment]
Oh, my bad. Surgery in maintenance. Anyway, it need to be sterile.

**Comment by pigeonpeas** [comment]
it's really nice! although, i would like some more green in virology.

**Comment by deltanedas** [comment]
cryo with no filters eventually poisoning patients :trollface:

**Comment by HelpTheSteak** [comment]
Maybe add a paramedic locker somewhere because cluster always missed one

**Comment by Boaz1111** [comment]
> Maybe add a paramedic locker somewhere because cluster always missed one

cluster's too lowpop for paramed

**Comment by Boaz1111** [comment]
> > cryo with no filters eventually poisoning patients :trollface:
> 
> With 1000L and 540 pressure surely it will be enough to last whole shift... right? _clueless_

well, lets atmos do something I suppose

**Comment by lzk228** [comment]
image
weird decals placement

**Comment by thebadman4662** [comment]
> > > cryo with no filters eventually poisoning patients :trollface:
> > 
> > 
> > With 1000L and 540 pressure surely it will be enough to last whole shift... right? _clueless_
> 
> well, lets atmos do something I suppose

Even if cryopod gets toxic, medical can always crowbar it open and reassemble to let in another 1k of gas.

**Comment by HelpTheSteak** [comment]
> > Maybe add a paramedic locker somewhere because cluster always missed one
> 
> cluster's too lowpop for paramed

Yes but unless it got changed a thief objective is the void suit and it is impossible to get it without a admin spawning it on cluster

**Pull request merged**
