### PR TITLE
babyproof arrivals shuttle

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

With some exceptions for things you might take with you like items,

All entities on the arrivals shuttle have god mode
All entities on the arrivals shuttle cannot be deconstructed
All entities on the arrivals shuttle cannot be deconstructed with a RCD
All entities on the arrivals shuttle cannot be destructed
All entities on the arrivals shuttle cannot be unanchored
The apc infinitely recharges.

dependency: Uncuttable cables from #33281 PR

## Why / Balance

Make rules become mechanics
The arrivals shuttle is generally a "do not tamper" zone, and the wizden server rules are such that you might be banned for doing so. This makes it much less possible to break that rule.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Arrivals shuttle is more tamper proof.

### CODE REVIEW

**Comment by Everturning** [comment]
If arrivals is at station when nuke explodes, will it still reach the people inside to kill them? Otherwise people can and have a probability of rushing to arrivals when nuke is close to detonation

**Comment by IProduceWidgets** [comment]
> If arrivals is at station when nuke explodes, will it still reach the people inside to kill them? 

Probably not. Smells like the lesser of two evils to me though.

**Review by keronshb — DISMISSED** [review]
I do not think this is the right direction to go with this.
Description should be made more clear.

**Comment by BombasterDS** [comment]
> I do not think this is the right direction to go with this. Description should be made more clear.

There is no situations in the game where you want  arrivals shuttle and terminal to be damaged (except building Narnia), so this PR is fine

**Comment by Minemoder5000** [comment]
> I do not think this is the right direction to go with this.

What do you think is the right direction to go in?

**Comment by keronshb** [comment]
> > I do not think this is the right direction to go with this.
> 
> What do you think is the right direction to go in?



> > I do not think this is the right direction to go with this. Description should be made more clear.
> 
> There is no situations in the game where you want arrivals shuttle and terminal to be damaged (except building Narnia), so this PR is fine

Less "I dont think we should do this" and more things can be improved, with a slight sprinkle of misunderstanding.
Arrivals shuttle can't be used as a fortress so that's fine.
And instead of opting for usual power we're going to take a magic power approach.

**Comment by IProduceWidgets** [comment]
Just shneeds the cable changes from #33281 and should be good to go.

**Comment by insoPL** [comment]
> If arrivals is at station when nuke explodes, will it still reach the people inside to kill them? Otherwise people can and have a probability of rushing to arrivals when nuke is close to detonation

It is strange that arrivals shuttle even launches during nuke or swlf destruct. 

Also when I was new player I died several times when arrival shuttle despawned on me.

**Comment by superjj18** [comment]
> If arrivals is at station when nuke explodes, will it still reach the people inside to kill them? Otherwise people can and have a probability of rushing to arrivals when nuke is close to detonation

To be fair, using the arrival shuttle to escape is a trap that new players fall in all the time because the logic is 100% reasonable, and the fact that the shuttle just leaves them behind in space in  a position where they are actively dying(to spacing) and will be gibbed in like 90 seconds if they don't escape is a massive flaw with the current arrival system.

**Review by Emisse — APPROVED** [review]

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by slarticodefast** [comment]
merging master to see if the tests pass now

**Pull request merged**
