### PR TITLE
added sprite for implanter.

### PR DESCRIPTION
**Pull request by LinkUyx**
## About the PR

Added sprites for implanter. He was previously withdrawn to the syringe.

**Media**

Content Client_HfsqK7PeG7
Content Client_TRdyWkdHMH
Content Client_MxoORStXVH
Content Client_f4zRfUDxx0

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Link
- add: Added sprite for implanter.

### CODE REVIEW

**Comment by deltanedas** [comment]
the old used sprite was a bent syringe

**Review by keronshb — CHANGES_REQUESTED** [review]

**Comment by LinkUyx** [comment]
> Just a few things and this should be good to go. In addition to my review can you also please make the sprite more obvious when it's full? It's hard to tell if it's empty or not.

I understand your claim and probably even agree. Rewrote the wording of the copyright. Well, I made the light bulb indicator of an empty implanter from blue to purple.

**Comment by keronshb** [comment]
> > Just a few things and this should be good to go. In addition to my review can you also please make the sprite more obvious when it's full? It's hard to tell if it's empty or not.
> 
> I understand your claim and probably even agree. Rewrote the wording of the copyright. Well, I made the light bulb indicator of an empty implanter from blue to purple.

You still need to grab a commit from where you got it from. Any one will do as long as the sprite is in that commit. Once you get that this is good to go

**Comment by LinkUyx** [comment]
> > > Just a few things and this should be good to go. In addition to my review can you also please make the sprite more obvious when it's full? It's hard to tell if it's empty or not.
> > 
> > 
> > I understand your claim and probably even agree. Rewrote the wording of the copyright. Well, I made the light bulb indicator of an empty implanter from blue to purple.
> 
> You still need to grab a commit from where you got the base sprites from. Any one will do as long as the sprite is in that commit. Once you get that this is good to go

that is, I need to write in the copyright (or description of the commit) that I am the author of the sprite and what exactly is taken as a reference?

**Comment by keronshb** [comment]
> > > > Just a few things and this should be good to go. In addition to my review can you also please make the sprite more obvious when it's full? It's hard to tell if it's empty or not.
> > > 
> > > 
> > > I understand your claim and probably even agree. Rewrote the wording of the copyright. Well, I made the light bulb indicator of an empty implanter from blue to purple.
> > 
> > 
> > You still need to grab a commit from where you got the base sprites from. Any one will do as long as the sprite is in that commit. Once you get that this is good to go
> 
> that is, I need to write in the copyright (or description of the commit) that I am the author of the sprite and what exactly is taken as a reference?

Here's this as an example:

https://github.com/space-wizards/space-station-14/pull/14987/files

Puro had modified the sprite but the base sprite is taken from that commit on TG. You need to have your copyright like that.
You should be able to actually use that same commit since it's the same sprite but modified.

**Comment by LinkUyx** [comment]
> > > > > Just a few things and this should be good to go. In addition to my review can you also please make the sprite more obvious when it's full? It's hard to tell if it's empty or not.
> > > > 
> > > > 
> > > > I understand your claim and probably even agree. Rewrote the wording of the copyright. Well, I made the light bulb indicator of an empty implanter from blue to purple.
> > > 
> > > 
> > > You still need to grab a commit from where you got the base sprites from. Any one will do as long as the sprite is in that commit. Once you get that this is good to go
> > 
> > 
> > that is, I need to write in the copyright (or description of the commit) that I am the author of the sprite and what exactly is taken as a reference?
> 
> Here's this as an example:
> 
> https://github.com/space-wizards/space-station-14/pull/14987/files
> 
> Puro had modified the sprite but the base sprite is taken from that commit on TG. You need to have your copyright like that. You should be able to actually use that same commit since it's the same sprite but modified.

all corrected

**Comment by keronshb** [comment]
@LinkUyx 

One more change, if you use an empty implanter to draw an implant out of someone, the icon state won't change:
implanter full

This should have the green/full icon state.

**Pull request closed without merging**
