### PR TITLE
add atmosia to devmap

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
gives devmap an atmos compartment, replaces the fueled generator with a debug generator, moves some lockers around, adds frezon miner prototype

## Why / Balance
easier atmos testing

## Media
Dev-0

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
no cl

### CODE REVIEW

**Comment by lzk228** [comment]
well.. we already have testteg map, but adding it to dev wouldn't hurt i suppose

**Comment by Ilya246** [comment]
> well.. we already have testteg map, but adding it to dev wouldn't hurt i suppose

this doesn't just have teg but everything for convenient atmos testing including a gas miner for every gas, a burnchamber (plasmafire included aka 9 instant plasmafire markers), and a room ready for testing how spacing interacts with an air vent

**Comment by superjj18** [comment]
Normalize putting things in the test map.

honestly if you left some notes around, you could probably make it a tutorial map

**Comment by chromiumboy** [comment]
Thank you for your contribution!

**Pull request merged**
