### PR TITLE
dark green jumpsuit recolor, casual green jumpsuits added

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

I recolored the dark green jumpsuit/jumpskirt to actually be dark green.
I added a casual green jumpsuit/skirt
## Why / Balance

For the dark green jumpsuit, it originally wasn't remotely dark green. This makes it... make sense. 
For the casual green jumpsuit, it was like the most important one that was missing. Open to revert this one pending clothesmate dying system. 
## Media

image
dark green(right)
casual green(left)
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added casual green jumpsuits and skirts to the clothesmate.

### CODE REVIEW

**Comment by lzk228** [comment]
casual green too dark imo

**Comment by UbaserB** [comment]
solves #28092

**Review by UbaserB — CHANGES_REQUESTED** [review]
Can you make both a tad bit brighter (esp the casual jumpsuit)?

**Comment by UbaserB** [comment]
Are you coming back to this?

**Comment by Boaz1111** [comment]
review adressed.

**Review by UbaserB — APPROVED** [review]

**Comment by slarticodefast** [comment]
@UbaserB So, do we make an exception to this comment?
grafik

**Comment by Boaz1111** [comment]
casual jumpsuit's still a jumpsuit

**Comment by SlamBamActionman** [comment]
I feel that this would've been better split up as two PRs, but the green jumpsuit needs that recolor and the casual green jumpsuit is a staple color. Since it has art maintainer approval, I'll merge it.

**Pull request merged**
