### PR TITLE
simple space mobs cant be flashed

### LINKED ISSUE #20783: Space Dragons needs flash immunity
## Description

Flashing a creature without items trivializes any encounter, there is no protection against it and it disables the entire screen for the player in addition to slowdown.

**Reproduction**

1. Be a mighty space dragon
2. Get flashed a single time
3. Die since there's nothing you could have done to prevent it

**Screenshots**

**Additional context**

These antag types/events should be redesigned if flash is intended to work this way on them, since it's a melee creature it cannot actually do anything against even a single cadet.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
all simple space mobs are immune to flashing now

fixes #20783

## Why / Balance
flash shouldnt work on fishe and dragon

## Technical details
no

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
space dragon is rev

**Comment by deltanedas** [comment]
real...

**Comment by JoeHammad1844** [comment]
i think mobs like space bears and carps should be flashable so that heads without weapons can use their flash and run away

**Comment by KingOnBudget** [comment]
> i think mobs like space bears and carps should be flashable so that heads without weapons can use their flash and run away

Why would a head fight a space bear or a carp. If they get carp bombed they won't have time to react fast enough and flash anyways.

**Comment by JoeHammad1844** [comment]
> Why would a head fight a space bear or a carp. If they get carp bombed they won't have time to react fast enough and flash anyways.

its usually not their choice to fight, and barratry has the space bear in maints that could find its way to a head, it would also help sec fight it

**Comment by JoeHammad1844** [comment]
well it gives them a better chance to run away

**Comment by deltanedas** [comment]
you can already outrun a bear

**Comment by metalgearsloth** [comment]
I no flasha da fish

**Pull request merged**
