### PR TITLE
Add a mapping merge driver allowing conflicting changes to the map file

### LINKED ISSUE #1476: Mapping merge driver
The disposals tyranny ends today.

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Closes #1476 
Fixes #@ike709's sense of eternal despair.
Allows multiple people to work on the same map file at the same time across different branches.

- [x] Entity resolution.

- [ ] Grid resolution.

- [ ] Tilemap resolution.

- [ ] Meta resolution.

- [ ] Unknown mapping fallback to a regular conflict.

- [ ] Tests.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Please for the love of god start working on this again. This is absolutely a must-have before we leave early access.

**Comment by 20kdc** [comment]
Regarding future work on this:
1. If a grid conflict occurs, what should it do? Forcing a standard conflict isn't particularly useful behaviour for grid conflicts
2. meta resolution isn't required for now since map saving always sets them to the same values regardless of what came in.
3. Am I okay to continue work on this in a separate PR?

**Comment by DrSmugleaf** [comment]
> Regarding future work on this:
> 
> 1. If a grid conflict occurs, what should it do? Forcing a standard conflict isn't particularly useful behaviour for grid conflicts
> 2. meta resolution isn't required for now since map saving always sets them to the same values regardless of what came in.
> 3. Am I okay to continue work on this in a separate PR?

1 & 2: No clue
3: Yes

**Comment by DrSmugleaf** [comment]
Superseded by https://github.com/space-wizards/space-station-14/pull/2803

**Pull request closed without merging**
