### PR TITLE
Adds yellow handrails

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Yellow handrails are now a thing. Currently can't construct them because try making the graph any different to the original one? Maybe I can just do a separate graph and entry but eh.

Currently seeking feedback on the bounding box situation, I tried to keep it as nice as possible for every direction but it can get nasty depending on the rotation of the entity. Corner one also needs some love as I can't figure out a 2 shape bounding box (like the regular railing corner) without it erroring. @metalgearsloth much appreciated
**Screenshots**

yellowrail

**Changelog**

:cl:
- add: Adds yellow railings to stop you idiots falling in places.

### CODE REVIEW

**Comment by Peptide90** [comment]
> These look super out of place. Is there alternative spritework?

I can edit them to remove the concrete base if that makes more sense. Or offer it as an alternative since I imagine planets will appreciate the concrete.

**Comment by PJB3005** [comment]
What about the Eris ones? 
image

**Comment by moonheart08** [comment]
> What about the Eris ones? image

We already have these, I think they want something closer to a fence.

**Comment by metalgearsloth** [comment]
If it's not flat then I can't really help with bounds. See what the existing railing does (though I agree Eris' one is better).

**Pull request closed without merging**
