### PR TITLE
Four cooking recipes changed to use liquid egg instead of whole egg, and 5u of milk added to cake batter

### PR DESCRIPTION
**Pull request by SamGithubAccount**
## About the PR

Changed the recipe for brownies, cannabis brownies/special brownies, chow mein, and egg-fried rice to to require liquid egg instead of a whole egg. 5u of milk were added to the CreateCakeBatter reaction.
## Why / Balance

To better fit with other recipes, such as pancakes, nettle soup, and noodles. Solves issue #30123, as the other three recipes mentioned seem to make sense with a whole egg, either fried or boiled.
Cake batter was created from the required reagents in beaker; probably why the recipe was what it was previously.  To fix this, 5u of milk were added to its recipe, which as far as I know shouldn't affect chefs too much.
## Technical details

Added 6 (raw) `Egg` reagent per previously used whole egg and removed previous FoodEgg requirements in the four previously mention recipes.
Added 5u of milk to cake batter recipe to prevent it occurring in beaker before brownies can be made
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: TheKittehJesus
- tweak: The recipe for chow mein, egg-fried rice, and both brownies now use liquid egg instead of a whole egg. 
- tweak: Cake batter now also requires 5u of milk

### CODE REVIEW

**Comment by beck-thompson** [comment]
Is the egg glitch fixed? @Katzenminer, @Tayrtahn and I noticed that if the recipe cook time is longer than 5 seconds the eggs cook and the recipe will not be completed (Brownies are susceptible to this). Its very annoying!

**Comment by Katzenminer** [comment]
Im still working on the glitch myself at first I thought it was because there is a node as a chemical reaction for cooking  but that didn't help but without temperature components it works, so I'm still searching and testing at the moment.

**Comment by SamGithubAccount** [comment]
I ended up opening issue #30259 while working on this.  I could submit a pull request to temporarily disable the cooked egg recipe in the meantime, as it doesn't seem to have much use and seems to be most commonly associated with that bug.

**Comment by Katzenminer** [comment]
> I ended up opening issue #30259 while working on this.  I could submit a pull request to temporarily disable the cooked egg recipe in the meantime, as it doesn't seem to have much use and seems to be most commonly associated with that bug.

From my testing unless I failed in correctly disabling it, it didn't even fix the issue.   I find it strange because as mentioned disabling the temperature component does help. I will continue working on it in 15 minutes wehn I'm home.

**Comment by SamGithubAccount** [comment]
Pull request #30294 also accomplishes similar things in a slightly different way.

**Comment by Katzenminer** [comment]
The thing is just changing the recepies doesn't fix the egg glitch does it?

**Comment by SamGithubAccount** [comment]
> The thing is just changing the recepies doesn't fix the egg glitch does it? (For me that didn't work)

I was referring to the tweak part of your PR where you changed some cooking recipes to use the (Raw) Egg reagent instead of requiring using a whole egg.

**Comment by Katzenminer** [comment]
Ah yeah I see then it's the same other than the milk I thin wich is a nice idee I think.

**Pull request merged**
