### PR TITLE
prevent nettles from injecting through hardsuit

### LINKED ISSUE #14890: nettles shouldnt penetrate hardsuit
## Description
while i too love deathnettles trolling nukies, it makes absolutely no sense

nyano probably good reference since hypo and syringe cant be used with suit

**Reproduction**
1. get nettle
2. spawn urist with hardsuit
3. whack him, reagents injected

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
deathnettle no longer trump card against nukies unless you convince them to take suits off first

fixes #14890

**Media**
look ma no histamine

https://user-images.githubusercontent.com/39013340/227928295-9415c98b-5bbd-4ccc-bf26-603528d8505e.mp4

i tested lexorin nettle and it instantly kills unsuited urists as expected

- [X] I have not added a video to this PR showcasing its changes ingame

**Changelog**
:cl:
- tweak: Nettles can no longer inject solutions through hardsuits. Yes, this means deathnettles don't work on nukies anymore.

### CODE REVIEW

**Comment by Snowyypanda** [comment]
adding a pop up message saying " you can't inject someone through a hardsuit" would be helpful for people that don't know why said action isn't working imo

**Comment by deltanedas** [comment]
popup exists now:

**Comment by deltanedas** [comment]
@vulppine anything else

**Comment by Myakot** [comment]
> @vulppine anything else

Do you plan for it to only affect hardsuits? Not things like bombsuits (or doomguy combat suit)?
Then again, I suppose it is logical that it won't affect only airtight gear.

**Comment by deltanedas** [comment]
the main intention was preventing botanists from steamrolling nukies, but exceptions can be made for some suits that arent hardsuits.
should be careful though, you could argue kevlar vest too but then bartender is immune to deathnettle

**Review by vulppine — APPROVED** [review]

**Pull request merged**
