### PR TITLE
add syndicate monkey reinforcement

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR

adds a syndicate reinforcement monkey you can buy for ~~9~~ 8 TC
price balanced around the 16 TC human reinf, considering that the human reinf:
- has 2 hands
- can wear more gear, such as the web vest (which the monkey can't wear)
- comes with a pistol, a knife, a pinpointer and even a survival box, which additionally has the flash-resistant syndicate mask
- can talk
- is sometimes hard to stealth if the name generates badly

**Media**

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added syndicate monkey reinforcement teleporter. Ook!

### CODE REVIEW

**Comment by Ilya246** [comment]
just-in-case price if people find a way to make way too good use of this, could reduce to 8 or maybe even 7 TC otherwise

**Comment by Geekyhobo** [comment]
3 nukies 120tc / 9tc = 12 monkey fighters, fishops has been replaced

**Comment by deltanedas** [comment]
monkey ops (when monkeys were 100% ghost roles like if you remember)

**Comment by Emisse** [comment]
make it 8 so its half of the human one

**Comment by Ilya246** [comment]
ok it's 8 tc now

**Comment by Vaaankas** [comment]
Monkeys still have the Clumsy component, right? So them having a pistol is more of a meme

**Comment by deltanedas** [comment]
should probably be removed now that sentient monkeys are very rare theres no shitter monkeys running around with guns

**Comment by Ilya246** [comment]
> Monkeys still have the Clumsy component, right? So them having a pistol is more of a meme

i'll change it so that the syndicate monkey does not have it

**Comment by Ilya246** [comment]
changed and tested, syndicate monkey can fire guns confirmed

**Comment by JoeHammad1844** [comment]
the monkeytide

**Comment by JoeHammad1844** [comment]
where do they get the knife, pistol, pinpointer, ect. do they have a backpack?

**Comment by JoeHammad1844** [comment]
it says it comes with a pistol and a knife, if not, can it at least come with a knife in its hand? and can it wear the syndie EVA?

**Comment by JoeHammad1844** [comment]
L6 monkey is GOING to be real and dangerous, by the way

**Comment by Ilya246** [comment]
> it says it comes with a pistol and a knife, if not, can it at least come with a knife in its hand? and can it wear the syndie EVA?

yes, it can wear the syndie EVA, but not bloodreds or juggs
otherwise, you can buy it a mosin for 1 TC or a pistol for not much more

**Comment by JoeHammad1844** [comment]
> * comes with a pistol, a knife, a pinpointer and even a survival box, which additionally has the flash-resistant syndicate mask

what about this?

**Comment by Ilya246** [comment]
> > * comes with a pistol, a knife, a pinpointer and even a survival box, which additionally has the flash-resistant syndicate mask
> 
> what about this?

i was talking about the 16TC human reinf here

**Comment by Geekyhobo** [comment]
Can we give the monkey a custom not damage resistant bloodred hardsuit, just to make they have the drip, and for them to make it to the station alive?

**Comment by Ilya246** [comment]
> Can we give the monkey a custom not damage resistant bloodred hardsuit, just to make they have the drip, and for them to make it to the station alive?

nukies start with a bunch of syndicate EVAs in their shuttle which monkeys can wear

**Comment by JoeHammad1844** [comment]
misread ops

**Pull request merged**
