### PR TITLE
Stun Batons can no Longer be Used by Pacifists

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Removes Pacifits ability to use weapons that deal more than 10 stamina damage or throw weapons that would deal stamina damage on hit.
## Why / Balance

image

## Technical details

Uses the `StaminaDamageOnHitAttemptEvent` with some modifications. Fixed a comment that got invalidated in a previous pr of mine.
## Media

https://github.com/user-attachments/assets/f9431cf5-91a7-4ec6-80ca-6d218ae06b2d

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Pacifits can no longer use stun batons.

### CODE REVIEW

**Comment by deltanedas** [comment]
toy hammer new thief kidnapping meta??

**Comment by Golinth** [comment]
The toy sword and toy hammer should be included as well then, since they both deal stamina damage. Shoving too.

**Comment by beck-thompson** [comment]
Doesn't the toy hammer have a chance to insta kill someone as well?

**Comment by SlamBamActionman** [comment]
While I disagree with the maintainers' stance on this PR overall (Thief is already in a disadvantageous position enough imo), the PR should absolutely not be expanded to include toy swords or shoving and the like. Since when is hitting someone with a toysword an effective strategy to kidnap and kill someone, seriously?

The reason why thieves can "attack" at all is so they can break open lockers and *blend in*. You should be able to play along if someone throws you a toy sword, or have a modicum of self-defense by shoving and disarming people.

**Comment by DieselMohawk** [comment]
I guess kidnapping isn't pacifism. Which makes sense, good PR

**Comment by Golinth** [comment]
> Since when is hitting someone with a toysword an effective strategy to kidnap and kill someone, seriously?

While I also don’t like or agree with the maintainers’ stance here, I have seen someone be kidnapped (and have been kidnapped) with someone using a toy hammer. All it takes is assuming someone is playing along before you’re knocked to the floor and cuffed, to be executed. 


If the maintainer consensus is that all stun weapons are a no go, they should stick to it. What if a stun weapon comes out that is between a toy sword and stun baton in terms of effectiveness? Should the pacifist be able use it, or should they block it because “no stun weapons.” If they block it you get into the argument of “well toy swords are barely worse and they are allowed” if they allow it then you get “well the stun baton got blocked but not this, what gives?” I think it’s gotta be all or nothing, or risk unintuitive gameplay.

**Comment by Cojoke-dot** [comment]
Guess I should have added this
image

**Comment by thebadman4662** [comment]
> toy hammer new thief kidnapping meta??

Pacifists shoudl not be able to use toy hammers, its a lethal weapon that instantly gibs(sometimes) after all.

**Comment by SlamBamActionman** [comment]
To make my stance clear:
Thieves are allowed to kill crew should they so choose, and are already at a major disadvantage by not being able to choose their equipment as freely as a traitor, not to mention the whole no-damage thing.

Kidnapping a conscious target is a weak and very dangerous form of murder, since you have to contend with fighting back and radio callouts. If a thief pulls it off with a stun baton then I say good job! The idea that the thief should not be allowed to kidnap people at all is ludicrous since *they got a whole kit dedicated specializing in kidnapping*.

If the actual concern is that a thief may be able to fight back by stunning Sec... If Sec can't get a hold of a single guy incapable of actually harming them and only getting them out of the fight for 5 seconds at a time, then that's not the Thief being busted.

**Comment by Cojoke-dot** [comment]
> The idea that the thief should not be allowed to kidnap people at all is ludicrous since they got a whole kit dedicated specializing in kidnapping.

Meh, don't you get sleeping drugs with that kit so you don't have to stun them?

**Comment by SlamBamActionman** [comment]
> Meh, don't you get sleeping drugs with that kit so you don't have to stun them?

Yes, but that's sort of my point. It provides a reliable and safe kidnapping alternative that is superior to stun batons, so clearly "thieves may not kidnap" isn't part of their design. Why then limit stun batons?

Turns out "Sentiment among maintainers is that thieves should not use stun batons" isn't actually an explanation for why there should be a balance change.

**Comment by keronshb** [comment]
This has nothing to do with thieves and only to do with pacifism.

If it's causing thieves so much of an issue because their identity is pacifism, we should work to decouple that.

**Comment by BombasterDS** [comment]
Stun is only way for pacifist to counteract antags. They literally can't attack or shoot them back, so i don't see any reason to leave them helpless by removing ability to use stun weapons.

In my opinion, best way to weak stun meta is adding stamina damage resistance to some armor.

**Comment by Cojoke-dot** [comment]
> Stun is only way for pacifist to counteract antags. They literally can't attack or shoot them back so i don't see any reason to leave them helpless by removing ability to use stun weapons.

yeah... I don't think you know what "pacifist" means... I believe the intent of the trait is to prevent all overtly hostile actions from the pacifist, I have no clue why they can use bombs though...

**Comment by BombasterDS** [comment]
> > Stun is only way for pacifist to counteract antags. They literally can't attack or shoot them back so i don't see any reason to leave them helpless by removing ability to use stun weapons.
> 
> yeah... I don't think you know what "pacifist" means... I believe the intent of the trait is to prevent all overtly hostile actions from the pacifist, I have no clue why they can use bombs though...

Pacifists, as i read on wikipedia, can defend themselfs, so stunbatons is most unharmful way to do that.

Additionally, pacifist may become traitor in round, so stun baton is only way to complete maroon objective, without TC spending (if you're really wanna complete pacifist route as traitor)

**Comment by Brandon-Huu** [comment]
> Thieves are allowed to kill crew should they so choose,

This is such a goofy admin ruling.
Pacifist serial killers running amok, can't make themselves hit someone with a toy sword but stuffing their incapacitated body into an incinerator is joyful for them.

**Comment by Brandon-Huu** [comment]
> > > Stun is only way for pacifist to counteract antags. They literally can't attack or shoot them back so i don't see any reason to leave them helpless by removing ability to use stun weapons.
> > 
> > 
> > yeah... I don't think you know what "pacifist" means... I believe the intent of the trait is to prevent all overtly hostile actions from the pacifist, I have no clue why they can use bombs though...
> 
> Pacifists, as i read on wikipedia, can defend themselfs, so stunbatons is most unharmful way to do that.
> 
> Additionally, pacifist may become traitor in round, so stun baton is only way to complete maroon objective, without TC spending (if you're really wanna complete pacifist route as traitor)

Sleepy drugs?

**Comment by BombasterDS** [comment]
> > > > Stun is only way for pacifist to counteract antags. They literally can't attack or shoot them back so i don't see any reason to leave them helpless by removing ability to use stun weapons.
> > > 
> > > 
> > > yeah... I don't think you know what "pacifist" means... I believe the intent of the trait is to prevent all overtly hostile actions from the pacifist, I have no clue why they can use bombs though...
> > 
> > 
> > Pacifists, as i read on wikipedia, can defend themselfs, so stunbatons is most unharmful way to do that.
> > Additionally, pacifist may become traitor in round, so stun baton is only way to complete maroon objective, without TC spending (if you're really wanna complete pacifist route as traitor)
> 
> Sleepy drugs?

I don't think that it's good idea to leave just one option for pacifist traitor to complete their objectives. 
And if you're not traitor, you just can't inject chloral fast enough, if you're not CMO. (or foam enjoyer)

**Comment by Cojoke-dot** [comment]
> I don't think that it's good idea to leave just one option for pacifist traitor to complete their objectives.

The whole point of the trait is to make you think differently, your thinking too in the box. There is always another way to do something, its space station. Let's say you need to take out cap as a pacifist traitor. One idea off the top of my head is to shock them to death. Shock the bridge door, steal their gloves, then put a conductive pair in front of the door. They go to grab another pair of glove, put on the conductive pair, get shocked, then you slam their head into the door till they die.

If you plan on playing pacifist traitor, you are planning of giving up options, that's the whole point. The options that are being given up(as of this pr) are direct melee attacks with non-lethal weaponry.

**Comment by Djungelskog2** [comment]
Yes isn't the entire point of pacifism not doing any lasting or truly damaging harm to anyone? Me arresting someone forcefully with no damage done is still pacifism

**Comment by Cadunkus** [comment]
To add on to what other people have been saying, this is also just a buff for pax which is already really strong as a combat chem. OP, do you often play chemist? O_o

**Comment by Cojoke-dot** [comment]
> To add on to what other people have been saying, this is also just a buff for pax which is already really strong as a combat chem. OP, do you often play chemist? O_o

Uh... it's pax... what combat are you doing while under pax? If a chemist wanted to disabled someone they could just use noct or any other poison, they can't apply pax in combat unless they are an antag or breaking space law(ie: cmo can't use their hypo to do it)

**Comment by UbaserB** [comment]
> Uh... it's pax... what combat are you doing while under pax? If a chemist wanted to disabled someone they could just use noct or any other poison, they can't apply pax in combat unless they are an antag or breaking space law(ie: cmo can't use their hypo to do it)

Pax used to be meta’d and was very powerful, often used against nukies as cmo, or as a self defense.

**Comment by Cojoke-dot** [comment]
> > Uh... it's pax... what combat are you doing while under pax? If a chemist wanted to disabled someone they could just use noct or any other poison, they can't apply pax in combat unless they are an antag or breaking space law(ie: cmo can't use their hypo to do it)
> 
> 
> 
> Pax used to be meta’d and was very powerful, often used against nukies as cmo, or as a self defense.

That's an issue with cmo hypo rather than an issue with pax and pacifism.

**Comment by UbaserB** [comment]
> That's an issue with cmo hypo rather than an issue with pax and pacifism.

also worth mentioning: pax slimes

**Comment by Cadunkus** [comment]
> That's an issue with cmo hypo rather than an issue with pax and pacifism.

Still capable of getting Pax into people's system without the hypo (i.e. gas nades). I'm curious if you've ever hit a secoff with pax and gotten batonged anyway. 🤔

**Comment by SlamBamActionman** [comment]
Hello! The PR was put up to a maintainer vote which concluded with the following result: Do not merge, but look into adjusting pacifism in other ways.

The issue at its core during the discussion was what pacifism should actually be in terms of gameplay, and the lack of consistency when it comes to using equipment. This discussion overlapped quite a lot with #30777's discussion due to how stun batons are mostly relevant to Security. 

As a trait, limiting it to not allowing direct bodily harm (damaging melee, guns & throwables) makes it more consistent, which is desirable. Since stun batons deal no direct damage they should therefore not be included in pacifism limitations. If one intends to harm with the pacifism trait the stun baton is indeed a useful tool, but it isn't the harmful action itself and has applications that don't involve dealing damage.

There were some other thoughts and suggestions for pacifism raised during the discussion however. It would be of interest to explore the following options:
1) Rename the trait from "Pacifist" to "Pacified", to make it sound less like a held belief and more like a state (RP reason could be having a pacifism implant).
2) Make disablers deal no damage, allowing them to be used by pacifists.
3) Allow bolas to be used by pacifists (giving them a ranged option instead of disablers). 
4) Disallow grenades to be used by pacifists (save for flash grenades).

**Comment by Cadunkus** [comment]
>     1. Rename the trait from "Pacifist" to "Pacified", to make it sound less like a held belief and more like a state (RP reason could be having a pacifism implant).

Having it be a pacifism implant is a lot more interesting for roleplay purposes especially since pacifism as a belief (i.e. the Hippocratic oath "Do no harm") often permits harm in self defense and a player could simply choose to not act in harm if they want to be a pacifist, basically the pacifism trait isn't very realistic. A character completely unable to hurt other people but tries to find ways to loophole that mental rule and a character who vehemently believes that hurting other people is wrong are two very different characters.

I would support this change.

**Pull request closed without merging**
