### PR TITLE
Botany research/lathe missing tools

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
Changelog:

-Adds lathe recipe for plant clippers
-Adds clippers, minihoe, spade to biotech research

### CODE REVIEW

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by ChilbroBaggins** [comment]
Oh, static recipe ≠ dynamic recipe

**Comment by EmoGarbage404** [comment]
> Oh, static recipe ≠ dynamic recipe

wdym

**Comment by ChilbroBaggins** [comment]
> wdym

The spade/minihoe are already in the autolathe which uses static recipes. (which I didn't notice). The protolathe where the other tools are found uses dynamic recipes.

**Comment by EmoGarbage404** [comment]
oh i didn't realize those were in the autolathe. that's honestly kinda strange. I'm not opposed to just moving them all to be in the protolathe.

**Comment by ChilbroBaggins** [comment]
haha, and shovel is in both

**Comment by ChilbroBaggins** [comment]
While I'm at this, should there be a pickax recipe somewhere?

**Comment by EmoGarbage404** [comment]
> While I'm at this, should there be a pickax recipe somewhere?

yes and either in the autolathe or just make it markably cheaper than drills in salvage tech.

**Comment by ChilbroBaggins** [comment]
Industrial engineering is required before salvage tech. Can unlock there.

**Comment by EmoGarbage404** [comment]
> Industrial engineering is required before salvage tech. Can unlock there.

that's space-faring tech. Normal salvage equipment has no prerequisites.

**Comment by ChilbroBaggins** [comment]
yeah you're right.

Also, again the recipe exists already. It was just never added anywhere.

**Comment by ChilbroBaggins** [comment]
I just added to autolathe then, since it's kinda pointless to unlock both that and the drill in the same tech.

**Review by EmoGarbage404 — APPROVED** [review]

**Pull request merged**
