### PR TITLE
Door electronics access

### LINKED ISSUE #5353: Airlock Boards cannot have their accesses programmed
## Description
An assistant with a screwdriver, welding tool, crowbar and wirecutters can permanently turn any secure airlock or windoor into  a generic all-access airlock.

Step 1) Follow the Deconstruction Guidelines laid out in the Construction Menu
Step 2) Reinsert the door electronics
Step 3) You now have a generic green airlock

Issue: Door Airlock electronic boards cannot be reprogrammed and do not store their old access restrictions. So I'm actually seeing some people who are not antag just turning the HoP door into all-access, or making security/brig all-access.  

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by rolfero**
## About the PR 
Adds the possibility to swipe your ID card on door electronics to overwrite access levels.

If you examine door electronics with a multitool, you can check what access level it's currently programmed with.

In the future this could be done nicer (ui, adding several access sets, access on door electronics prototypes etc) but it's fully functional right now.

Fixes #5353

**Screenshots**

https://user-images.githubusercontent.com/45628623/200197010-0052b2cb-8d76-4ec9-ab39-3d8afec75927.mp4

**Changelog**

:cl:
- add: You can now add access levels to constructed doors by swiping an ID card on the door electronics before inserting them.

### CODE REVIEW

**Comment by retequizzle** [comment]
seems like it'd be pretty easy to tamper with, should make for good mischief alongside of adding a QoL improvement for repairing doors

i take it if you use an altered ID that has multiple levels of access (let's say an engineer with cargo/salv perms), it'll mirror those copied accesses as well? or will the swiped ID only provide permissions for the ID type it belongs to?

**Comment by rolfero** [comment]
> seems like it'd be pretty easy to tamper with, should make for good mischief alongside of adding a QoL improvement for repairing doors
> 
> i take it if you use an altered ID that has multiple levels of access (let's say an engineer with cargo/salv perms), it'll mirror those copied accesses as well? or will the swiped ID only provide permissions for the ID type it belongs to?

the swiped ID replace the current needed permissions with all of the permissions the ID has - which means you should probably get the door electronics swiped with a minimal-access-needed ID from the HoP before insertion.

**Comment by Cheackraze** [comment]
> seems like it'd be pretty easy to tamper with, should make for good mischief alongside of adding a QoL improvement for repairing doors
> 
> i take it if you use an altered ID that has multiple levels of access (let's say an engineer with cargo/salv perms), it'll mirror those copied accesses as well? or will the swiped ID only provide permissions for the ID type it belongs to?

I can see some serious issues with perms this way. Say Sammy salvage builds a shittle, and wants the airlock to be salvage exclusive so he swipes his ID on the electronics to set the perms. While stealing some vending machines, Gary Greytide comes along and spaces the shittle and loots his stuff because the door has Maints access allowed. In fact, everyone has maints access, so using the ID this way will appear to the player to 100% not work.  It should be an AND instead of OR access list then, so that you need all of the same perms as the ID instead of one of many. Although I've only dealt with access levels on the yml side and AFAIK it's all OR accesses and not AND, tho there is probably a way to do that

**Comment by 0x6273** [comment]
Swiping an ID card on an unpowered door electronics board to update its access doesn't really make sense to me. The card reader would need power to function.

**Comment by JustinTrotter** [comment]
> Swiping an ID card on an unpowered door electronics board to update its access doesn't really make sense to me. The card reader would need power to function.

What about inserting the board, powering it, and then swiping the card while the panel is open to give it a one time access set? It would only reset when removing the board.

During the initial setting swipe, it could open a menu that allows you to specifically toggle all the access that id has privilege to.

**Comment by Cheackraze** [comment]
How about using the ID computer, inserting the door electronics like an ID and requiring HoP to modify access?

**Comment by GoodWheatley** [comment]
> How about using the ID computer, inserting the door electronics like an ID and requiring HoP to modify access?

I can see a lot of problems with this system, since half of the time the ID computer board's been stolen and the HoP has transcended the mortal plane and is no longer reachable without breaking the convential boundaries of time and space, and the other half of the time setting up a new door would require you to walk to the HoP's office, stand in the line, and then go back to finish building the door, which is extremely time-consuming.

**Comment by Cheackraze** [comment]
> 

So for one, it keeps the duty of delegating access to the HoP, which is his main job anyway. Two, it limits who can change door accesses because that's a really, really powerful tool of you're able to just stick your ID into an open door panel to change the perms. For three, it allows precise and accurate settings on the perms. And four, it encourages more social interaction in the game instead of discouraging.  Having HoP or the ID board go missing is just a part of the experience, and might inventivize regular crew to care more about the wellbeing of Ian's owner.

**Comment by rolfero** [comment]
Wrote this in discord right now:
What do people think about door electronics access? I do agree that we will at some point probably not want to do it the way my PR implements it: swiping an access card on a door electronics board copies your access to the board, meaning you require the same (or higher) access as the ID.
/tg/ has a UI you use when you press the board, similar to the ID computer I guess, where you set the access levels.
I feel this pr is a step in that direction, but that you still need some interdepartmental communication (want to repair a brig windoor? then you need to either get an ID with brig access from HoP or you can get one from a sec officer that will make it require slightly higher access)
I do not think using a separate machine to set the door electronics access (as discussed in the comments) is the right way to go. In that case it's better to just unlock an access-setting-ui when the door electronics is already in the airlock.

And do anyone think the mechanics the PR suggests is not good enough to be implemented yet? I feel like it solves a problem I've had several times when playing, which is that you cant build functioning access-locked airlocks.

**Comment by theashtronaut** [comment]
I was going to suggest, why not incorporating the tg method where you click on the board with a multi-tool and set access. You can _also_ swipe a card to have it copy all those into it, but you can click on it to further tweak it as well. It's just a shortcut. 

This means you don't _need_ a specific ID for construction, nor do you need to take it to some machine to program it.

**Comment by moonheart08** [comment]
Are you coming back to this?

**Comment by AJCM-git** [comment]
reopen once you come back to this

**Pull request closed without merging**
