### PR TITLE
Thief guidebook entry

### PR DESCRIPTION
**Pull request by deepdarkdepths**
## About the PR
Added a new guidebook entry pertaining to the thief. Completes #22918.
Please ignore my attempts at fixing my commits.. 

## Why / Balance
No entry for it yet!

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

🆑 

- add: Added the thief entry into the guidebook.

### CODE REVIEW

**Comment by UbaserB** [comment]
Can you write as a note that animals need to be dragged or stay in a pet carrier when the round ends for those objectives to complete, and that the detective's flippo lighter spawns in his JACKET specifically (lots of players tend to overlook this).

**Comment by UbaserB** [comment]
I thought the lighter doesnt spawn on the player and spawns on the jacket in the locker

**Comment by Dutch-VanDerLinde** [comment]
> I thought the lighter doesnt spawn on the player and spawns on the jacket in the locker

it spawns in the jacket all the time, even the jackets that get dispensed from the detdrobe

**Comment by deepdarkdepths** [comment]
> I thought the lighter doesnt spawn on the player and spawns on the jacket in the locker

Should I amend the "spawns on the player" thing then? I forgot they spawned without jackets tbh.

**Comment by deepdarkdepths** [comment]
Closing in favor of a new pr due to royally fucking up this branch.

**Pull request closed without merging**
