### PR TITLE
Makes Lizard animals REAL

### PR DESCRIPTION
**Pull request by DogZeroX**
Gave Lizards an actual lizard looking sprite, and the old one got renamed to slug.
## About the PR 

**Screenshots**

**Changelog**

:cl: Lizard Master
- tweak: Lizards (animal) now look like Komodos instead of worms.
- add: Added slugs, what used to be old lizard sprite.

### CODE REVIEW

**Comment by mirrorcult** [comment]
but soul sprite

**Comment by mirrorcult** [comment]
actually this is fine if you readd the old lizard sprites as a snake or something

**Comment by DogZeroX** [comment]
Sorry but I don't add garbage :P

**Comment by mirrorcult** [comment]
slug time

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
