### PR TITLE
space doafters, like doafters but in space

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
doafters, by default, will ignore your own movement if you are weightless (can be disabled with BreakOnWeightlessMove, bikeshedding welcome its a sus name)
changed target position code to target *distance* so you can maintain the same distance and still do it

intended for stripping and cuffing to actually be possible with no gravity
coincidentally makes it so they can work with gravity so long as you maintain the same distance (so perfectly chasing a suspect or spinning them around you, which would be funny)
since cuffing works with no gravity sabotaging grav no longer makes it impossible for sec to cuff you

i have only tested these doafters so far, though i dont think it will break anything

this also enables you to heal yourself in space since before this any bit of drifting would cancel it

**Media**

stripping and cuffing with gravity, only change is the spinny part since distance

https://github.com/space-wizards/space-station-14/assets/39013340/1e13dcf1-8202-44b7-ad67-4a1450dfc6fb

stripping and cuffing without gravity, works even if you and the target are drifting (at the same speed)

https://github.com/space-wizards/space-station-14/assets/39013340/5a54ce33-94cb-435d-958f-d933b8220310

using a jetpack to change speed and thus distance, it fails now

https://github.com/space-wizards/space-station-14/assets/39013340/380e490a-12b3-4eff-b6d1-dc683fb4711b

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: DoAfters (green bar above your head) now work when moving without gravity so you can cuff, strip and use meds in spess.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Shouldn't the do_afters just be using distancethreshold instead then?

**Comment by deltanedas** [comment]
it does
but instead of checking difference in position its difference in distance

**Review by mirrorcult — APPROVED** [review]

**Comment by deltanedas** [comment]
its christmas

**Comment by mirrorcult** [comment]
YOU'RE christmas

**Comment by metalgearsloth** [comment]
Uhh doesn't this mean someone can forcecuff you now if they can outrun you.

**Comment by deltanedas** [comment]
oh true shit i created a spider meta

**Pull request merged**
