### PR TITLE
Adds Ganja Brownies

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
## About the PR
- Adds recipes for basic and "special" brownies. You can make them by the batch of 6 and cut into individual pieces.
- Special brownies require cannabis butter to make which also comes with it's own recipe. 
- In-line with [this](https://github.com/space-wizards/space-station-14/pull/19183) PR from yesterday, producing canna-butter is a more efficient method than drying/grinding leaves.  See breakdown:
>raw leaf=15thc
6leaves(90) + butter = 1 cannabutter= 82thc(10% loss)
2 CB(164) = 6 brownies = 150thc (~9% loss)
1 brownie = 25thc (17% overall loss)
- Brownies are also stronger than blunts/joint

**Media**
208764335-b9cd6408-b78b-4c18-b3a3-3cab6c697851

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

**Changelog**

:cl: Velcroboy
- add: Chef Velcroboy has been in the kitchen messin around with the botanicals. New recipes have been developed for some extra "special" brownies. Careful with these...

### CODE REVIEW

**Comment by UbaserB** [comment]
the butter sprite does not look like butter imo

**Comment by ChilbroBaggins** [comment]
> the butter sprite does not look like butter imo

It's the same butter we've always had. Just with a green tint. It could always be re-sprited but I didn't see that being w/in the scope of this PR.

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
resolve conflicts then good to merge @ChilbroBaggins

**Comment by ChilbroBaggins** [comment]
Conflicts resolved

**Pull request merged**
