### PR TITLE
Weh!

### PR DESCRIPTION
**Pull request by DogZeroX**
**Screenshots**

https://user-images.githubusercontent.com/43253663/147896702-06bcb562-2a8a-491b-ac8c-c062ff2cf175.mp4

## About the PR 
Replaces the Squeak sound of the Lizard with the well-known "Weh"
It also fixes the Vox Plushie's EmmitSoundOnLand
**Changelog**

:cl:
- add: The prophecy is true, the arrival of the ЩΣΉ, is finally here!

### CODE REVIEW

**Comment by mirrorcult** [comment]
weh

**Comment by hugmeorelse** [comment]
weh

**Comment by BlackMajor** [comment]
Weh!

**Comment by DogZeroX** [comment]
weh

**Comment by DeltaFire15** [comment]
weh.

**Comment by moonheart08** [comment]
weh

**Comment by wrexbe** [comment]
weh

**Comment by mirrorcult** [comment]
Whoops i meant to hit the 'delete and publicly execute sergal' button

**Pull request merged**
