### PR TITLE
Added realisation of Robust separate localization

### PR DESCRIPTION
**Pull request by Tornado-Technology**
## About the PR
Implements split localization from my PR in RobustToolbox

depends on https://github.com/space-wizards/RobustToolbox/pull/5227

## Why / Balance
It's cool!

## Technical details
`ContentLocalizationManager.Culture` now returns the current culture, or the default `en-US `culture

## Media
https://github.com/space-wizards/space-station-14/assets/54727692/5a6f7e08-cc5a-4cde-a8c2-9ac78462ff09

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- add: Separate localization for server and client.

### CODE REVIEW

**Comment by Tornado-Technology** [comment]
It might be possible to add a translation selection on the client to the UI, but I haven't figured out how to get all the folders yet.

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This isn't going to work. There are far too many server-sent strings that it makes changing the client language impossible.

Fixing this requires redoing how every user-facing `string` in the entire game and engine is handled and has many unsolved problems. This PR isn't starting anywhere.

**Comment by Tornado-Technology** [comment]
> This isn't going to work. There are far too many server-sent strings that it makes changing the client language impossible.
> 
> Fixing this requires redoing how every user-facing `string` in the entire game and engine is handled and has many unsolved problems. This PR isn't starting anywhere.

I mean translating client content, I was thinking of translating server strings as well, but we can all have other problems

**Comment by PJB3005** [comment]
We are not interested in providing support for a broken localization system that has half the strings as the server language and the other half as the client language. That is just going to cause bug reports we can't fix.

**Comment by Tayrtahn** [comment]
It's a nice dream! 

If you want to make this a reality, the first step is to move ALL the localization string lookups to the client and have the server only ever send LocIds (and args) to the client. For *everything*. It'd be a massive project, but that would need to be done first, before something like this could be added.

**Pull request closed without merging**
