### PR TITLE
Fix some closets being not deconstructable

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Makes some closets deconstructable
Makes ClosetBase abstract, replace it with ClosetSteelBase im migration
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by lzk228** [comment]
closing cause ill do that in #23056

**Comment by metalgearsloth** [comment]
Fix test

**Comment by lzk228** [comment]
migration.yml my beloved

**Comment by lzk228** [comment]
test fail seems to be unrelated

**Pull request merged**
