### PR TITLE
macrobomb 20->13 TC

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
changes price of the nukie macrobomb implant from 20 to 13 TC

## Why / Balance
it has rather little utility and high possibility of friendly fire so 20 TC is just never worth it, 13 seems like a better figure

## Media

untested

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Macrobomb implant price reduced 20->13 TC.

### CODE REVIEW

**Comment by sporekto** [comment]
Maybe reduce the explosion radius a little? For balance

**Comment by sporekto** [comment]
Maybe reduce the explosion radius a little? For balance

**Comment by UbaserB** [comment]
makes it a more valid option for loneops now, which i appreciate.

**Comment by Ghagliiarghii** [comment]
This is funny so I approve

**Comment by Ilya246** [comment]
i will wait for more discussion and/or a maintainer opinion before making further adjustments

**Comment by Hmeister-real** [comment]
8 Tc is better

**Comment by Ilya246** [comment]
reminder that you can implant macrobombs into anything living, and i'm pretty sure *you can implant them into monkeys and mice*

**Comment by keronshb** [comment]
How about 15 instead?

I forgor if we have Cayanne added but that's also one of the planned implementations to do funny fish bomb.

**Comment by vanilia123** [comment]
Good PR

**Comment by sporekto** [comment]
> How about 15 instead?
> 
> I forgor if we have Cayanne added but that's also one of the planned implementations to do funny fish bomb.

Agree with you

**Comment by MACMAN2003** [comment]
> > reminder that you can implant macrobombs into anything living, and i'm pretty sure _you can implant them into monkeys and mice_
> 
> what kind of mouse is going to run right into the captain and die?

the indisputable gigachad known as Mouse (123)

**Comment by Ilya246** [comment]
> How about 15 instead?
> 
> I forgor if we have Cayanne added but that's also one of the planned implementations to do funny fish bomb.

13 seems more reasonable to me considering syndicate bombs are 11 TC and you can arm them in space then drag them anywhere plus you don't have to die to use them, so i believe 15 TC is too expensive for what it is
if this does somehow turn out to be too cheap, we can raise it later

**Comment by deltanedas** [comment]
> what kind of mouse is going to run right into the captain and die?

this is the 5tc nuke disk purchase

**Comment by tutoumi** [comment]
> > reminder that you can implant macrobombs into anything living, and i'm pretty sure _you can implant them into monkeys and mice_
> 
> what kind of mouse is going to run right into the captain and die?

you give the mouse some cheese and ask gently

**Pull request merged**
