### PR TITLE
Adjusts the lethality of meteor explosions

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

Anti-personnel damage has been halved and tile breaking normalized. Boom hearing range and explosion radius remains unchanged.

## Why / Balance

Meteors piercing through stations is good as it raises spacing potential of meteor swarms 👍. Being instantly crit by a meteor explosion through a reinforced wall which you did not see coming is not good.
Previous meteor explosions were designed to do considerable damage to (presumably) have an effect on reinforced walls, but the recent buff to meteors means that this paradigm is no longer necessary. This PR adjusts the damage of meteors such that you can survive the fragments of a singular meteor, before being crit by another or dying to depressurisation.

## Technical details

Adjusts meteor YAML prototypes.

## Media

C-4 with edited values detonated 2 tiles away from a Urist, of each meteor size and before/after changes.
https://youtu.be/6MxzLFs5Wqw?si=WvT6djvHUm7vrfT8

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No

**Changelog**

:cl:
- tweak: Adjusted meteors to have less lethal blast fragments.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Needs before and after if you really want to get this merged before the other changes are even live.

**Comment by WarMechanic** [comment]
I'll record damage adjustments then

**Comment by WarMechanic** [comment]
recorded before/after, tested on an unarmoured urist with no eva protection
damage is basically halved but doesn't affect damage from spacing

**Comment by ps3moira** [comment]
back in my day meteors used to gib ya! what's with all this halving damage mumbo jumbo

**Comment by WarMechanic** [comment]
> back in my day meteors used to gib ya! what's with all this halving damage mumbo jumbo
> 
> edit: ohh it's for the explosion not the actual meteor itself

i actually dont know if being direct hit by the meteor will kill a player like how it destroys structures but that would be funny

**Review by metalgearsloth — APPROVED** [review]
Just waiting for internal approval.

**Pull request merged**
