### PR TITLE
Minifig Rarities and Price Adjustments for Minifigs

### PR DESCRIPTION
**Pull request by PoorMansDreams**
## About the PR

Minifigs have rarities, and prices to reflect them! A lotto crate but doesn't blow up your budget. 
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Miniature figurines now have rarities

### CODE REVIEW

**Comment by Tayrtahn** [comment]
You'll probably need to add the figurine box to the Ignored list at the top of Content.IntegrationTests/Tests/CargoTest.cs so this doesn't start randomly triggering test failures.

**Comment by metalgearsloth** [comment]
> You'll probably need to add the figurine box to the Ignored list at the top of Content.IntegrationTests/Tests/CargoTest.cs so this doesn't start randomly triggering test failures.

Stuff should not be getting added to it.

**Comment by Tayrtahn** [comment]
> > You'll probably need to add the figurine box to the Ignored list at the top of Content.IntegrationTests/Tests/CargoTest.cs so this doesn't start randomly triggering test failures.
> 
> Stuff should not be getting added to it.

I mean, this is a lotto crate, so it's sometimes going to be worth more than it costs to buy, which means it will fail the test based on RNG. If it's not ignored and gets merged, it's going to make random PRs start failing checks.

If you mean that there shouldn't be more lotto crates added to the game, then that's a different story and not something I have an opinion on.

**Comment by mirrorcult** [comment]
all in all seems strange to me as a lotto crate, i dont really see the logic in making certain ones rarer and i dont think players will understand that they're not all equal chance either, opting to close

**Pull request closed without merging**
