### PR TITLE
acting captain

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
## About the PR

EXTREMELY bandaid patch but it will keep players from malding (also draft)

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: eclips_e
- fix: Nanotrasen has implemented a new system of judging which head is eligible for acting captain automatically.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
guh

**Comment by deltanedas** [comment]
pros can just 1. get hours 2. get spare id

**Comment by Just-a-Unity-Dev** [comment]
> pros can just 1. get hours 2. get spare id

players r malding that there's no captain

**Comment by Just-a-Unity-Dev** [comment]
> so they can stop malding and become cap

people have skill issue and also the inability to sandbox in a sandbox game soooo

**Comment by Myakot** [comment]
Imagine having sheep instead of department heads.

**Comment by metalgearsloth** [comment]
no

**Comment by Just-a-Unity-Dev** [comment]
gjuh ok

**Pull request closed without merging**
