### PR TITLE
Wide anomaly locator

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

Adds a new item to the game "Wide-spectrum anomaly locator", being a modified anomaly locator. It has a 2-fold increased anomaly search range, but the distance detection function for it is disabled.

## Why / Balance

On large maps, the process of finding anomalies is difficult. This locator helps to detect the approximate location of anomalies, but does not remove the need to use conventional anomaly locators.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/c226b5a0-0c07-4e86-b7b3-db8ee4128382

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added wide-spectrum anomaly locator.

### CODE REVIEW

**Comment by TheShuEd** [comment]
Reopened PR from:
https://github.com/space-wizards/space-station-14/pull/20572

**Comment by JoeHammad1844** [comment]
why cant you just increase the range of the anomaly locator? adding an extra item seems like bloat to me

**Comment by EmoGarbage404** [comment]
you seem to have accidentally re-encoded all of your files that you modified, and it's significantly bloated the diff. Can you fix this?

**Comment by TheShuEd** [comment]
@EmoGarbage404 
Done

**Pull request merged**
