### PR TITLE
Fixed cognizine not working on monkeys

### PR DESCRIPTION
**Pull request by MrToofters**
## About the PR

Removed the chance of monkeys having ghost roles.
## Why / Balance

It was changed so cognizine can work on monkeys. It would be good to have monkey helpers you can talk to.
## Technical details

No changes
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes.
**Changelog**

:cl:
- fix: Fixed Cognizine not working on monkeys.

### CODE REVIEW

**Comment by Partmedia** [comment]
Could you link to any discussions about this that may have taken place? Will folks be unhappy if monkeys don't start with ghost roles available?

**Comment by LankLTE** [comment]
> Could you link to any discussions about this that may have taken place? Will folks be unhappy if monkeys don't start with ghost roles available?

It's already very rare- but I think just removing the component is a bad way to fix cognizine not working on them when the system could be fixed instead.

**Comment by MrToofters** [comment]
> > Could you link to any discussions about this that may have taken place? Will folks be unhappy if monkeys don't start with ghost roles available?
> 
> It's already very rare- but I think just removing the component is a bad way to fix cognizine not working on them when the system could be fixed instead.

Im really not a coder and i just really wanted to make cogni work on monkeys but if you have a better idea do what to do youre welcome to do it.

**Comment by Partmedia** [comment]
This actually isn't the problem. The problem is that only monkeys only have a 1/20 chance of being sentient, see #16363.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
This is not a solution for the problem, i think the issue is that `MakeSentient` reagent effect does not work cuz of this check (the probability affects whether or not the component is present). Either way the effect is very badly designed and it needs a refactor (prob split it into `GiveMind`, `GiveGhostRole`, `GiveSpeech` effects or something)
image

**Pull request closed without merging**
