### PR TITLE
Lathe-able Welding Masks

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Making this on the behalf of someone who mentioned it's surprisingly difficult to get your hands on a welding mask.
This allows you to construct one in an Autolathe with four steel and two glass.

(Had to change the composition of the mask from 5 steel to 2 as to avoid cargo abuse with the hyper lathe + material reclaimer.)

## Why / Balance
Welding masks actually do show up for non-engineers a lot less than you'd think; the main way of getting them being praying to god they're mapped in a maints room.
This is the most direct approach to fixing that, also providing a renewable source of them.

## Media
- [X] This PR does not require an ingame showcase.

**Changelog**
:cl:
- add: Welding masks can now be made in the Autolathe.

### CODE REVIEW

**Comment by Tayrtahn** [comment]
I like this personally, but I have a suspicion that this might be a bit controversial.

**Comment by Tayrtahn** [comment]
Alright then, guess that shows me

**Comment by LordEclipse** [comment]
Don't welding masks give you flash protection as well? They really need a vision nerf

**Comment by Holinka4ever** [comment]
> Don't welding masks give you flash protection as well? They really need a vision nerf

Yes, they have flash protection, though, it more honest rather than sunglasses, cause you cant hide wielding mask under gas mask or other closing head healmet and call it for "drip" situations.

Anyway, It will be issue if whole station will wear wielding masks. Let time decide what will be

**Comment by K-Dynamic** [comment]
> Anyway, It will be issue if whole station will wear wielding masks. Let time decide what will be

"REVS"
"EVERYONE PRINT MASKS"

Ought to make printing welding masks slow, lock behind T1 research, or remove flash protection

**Comment by Holinka4ever** [comment]
> > Anyway, It will be issue if whole station will wear wielding masks. Let time decide what will be
> 
> "REVS" "EVERYONE PRINT MASKS"
> 
> Ought to make printing welding masks slow, lock behind T1 research, or remove flash protection

In space station 13, coders resolved this problem by adding huge penalty to visbility, aka you dont see anything outside 3x3 tiles around you. It turned into non-profitable for combat, due lack of visibility wile innit. Though, them also added action to "open/alter" wielder mask, that allows to see things normal,but reverting flash and wielder protection.

**Comment by deltanedas** [comment]
> aka you dont see anything outside 3x3

this is basically slightly better blindfold

**Comment by Holinka4ever** [comment]
> > aka you dont see anything outside 3x3
> 
> this is basically slightly better blindfold

Yeah, my bad.
You actually see outside 3x3, but you cant see it very well. 
Still, idea of mass production wielding masks is maybe interesting, but current powergamey behavior of people, may turn this it into despair.

**Comment by Holinka4ever** [comment]
> > > aka you dont see anything outside 3x3
> > 
> > 
> > this is basically slightly better blindfold
> 
> Yeah, my bad. You actually see outside 3x3, but you cant see it very well. Still, idea of mass production wielding masks is maybe interesting, but current powergamey behavior of people, may turn this it into despair.

P.S.
Why its got merged before conservation about cons and pros? What about colored version of wielding masks?

**Pull request merged**
