### PR TITLE
Increases power usage across the station

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Gives engineering a reason to setup a generator.

See file changes but generally increased computer and machine usage across the board. Made the gravity generator particularly hungry too (it has to look after a whole station afterall. When we make compact ones they will need to have a different component for radius based gravity and lower power usage).

Consolidates some of the changes from #5870 to make them less harsh in some cases.

### Case study: Saltern

3 minutes: 2x SMES at 30%, all substations now charged
5:30 minutes: both SMES fully drained, very short (sub 5 seconds) brownout.
medbay @ 9:50
engineering @ 10:15 then brownouts till 10:30
bar kitchen @ 11:10
dorms disposals @ 11:45 + brownouts till 11:55
brig and arrivals still between 30 and 40%
cargo 30%
library 70%
bridge 15%

Packed fares better as it has 3x SMES and more substations as well as 3x SMES which aren't connected to grid that can easily be done to buy extra time.

This gives engineering a clear objective at round start to get a minimum amount of power generation going. And although the departments depowering is based on their machines they have primiarly, it make sense for security (+vault to go last).

If you want to delay against this simply map an extra SMES or two to increase the duration till bad stuff happens but currently Saltern spawns with two debug generators anyway which reduce the power draw by 6000 watts, prolonging the time to set up.

**Screenshots**

Altered packedstation atmos slightly to have it's own substation and also changed the HV wiring so that the engineering substations are now on the supply side of the SMES and not the input side.
packed

**Changelog**

:cl:
- tweak: The power bill has finally arrived. Computers and Machines use considerably more power now. Engineering better be fast at getting some generation going!

### CODE REVIEW

**Comment by Peptide90** [comment]
Will do some further tests on this with solars and engine setup to ensure balance is okay (as might bring grav gen down some)

**Comment by mirrorcult** [comment]
> Will do some further tests on this with solars and engine setup to ensure balance is okay (as might bring grav gen down some)

did you end up doing this?

**Comment by Peptide90** [comment]
Should be good to merge now. Tested on Saltern and Packed with no major issues. Should make brownouts more common and engineering have about 10 minutes before people start shouting.

Decided to also port from Moonys PR so that AME no longer requires power to start so station is recoverable.

**Comment by metalgearsloth** [comment]
> Should make brownouts more common and engineering have about 10 minutes before people start shouting.

Is it 10 minutes before blackout or 10 minutes before power starts going down?

**Comment by Peptide90** [comment]
> > Should make brownouts more common and engineering have about 10 minutes before people start shouting.
> 
> Is it 10 minutes before blackout or 10 minutes before power starts going down?

For Saltern when I last tested it was 10 minutes until a department actually lost power (med and eng). There isn't really a way to balance power draw vs power production otherwise, the only way to keep it semi realistic and useful would be to add more SMES which would give about 2.5 minutes extra each until substations start to drain. That and better power network designs so subs aren't overloaded.

Saltern only really has 2 SMES so doubling that would make it 10 minutes to a brownout then 20 mins to blackouts. Packed has lots of spare SMES that just need connected.

**Comment by metalgearsloth** [comment]
Can't you just VV the starting charge to be higher for SMES?

10 minutes until brownout seems okay, I would say at least 15-20 before a total blackout.

**Comment by Peptide90** [comment]
> Can't you just VV the starting charge to be higher for SMES?
> 
> 10 minutes until brownout seems okay, I would say at least 15-20 before a total blackout.

Just tested, Saltern spawns with the SMES full. With a third SMES mapped in you get about 7-8 minutes until the brownout so with that about 15 minutes until substations start dying. Both stations spawn with an AME so I think this is fair for now - 15 minutes is more than enough time to setup an AME or any other engine and start building more storage. I'll push the 3rd SMES PR for saltern.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
