### PR TITLE
Kettle medical rework

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

Large sections of Kettle's medical department have been reworked including:

- Ward
- OR
- Cloning
- Cryogenics

## Why / Balance

Kettle's medical ward was still one of the few wards that consistently gets deconstructed because it is too clunky to work with. This rework introduces a move of the ward such that it is more accessible to the general public, along with a more open layout.

To encourage use of the cryogenics facilities, an additional cryo pod was added for a total of two, and the entire "subdepartment" has been moved closer to the ward. Cloning now has the entire room it used to share with cryogenics.

**I may still change the following:**
- Cryogenics piping (Not entirely proud of this, tho it does work.)
- Paramedic location (They could get a proper room.)

This is mainly because this is some large work and still needs feedback.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Medical ward:

Screenshot from 2023-09-29 19-39-42

Cryogenics and surgery:

Screenshot from 2023-09-29 19-39-49

Cloning:

Screenshot from 2023-09-29 19-39-56

**Changelog**

Adding because this does seem like a significant enough change, if told to remove I will remove it.

:cl:
- tweak: Kettle's medical ward was reworked.

### CODE REVIEW

**Comment by deltanedas** [comment]
cryo piping seems ok to me

**Comment by JoeHammad1844** [comment]
add some tile decals to the main treatment room so areas stand out

**Comment by TsjipTsjip** [comment]
> add some tile decals to the main treatment room so areas stand out

Working on this now.

**Comment by TsjipTsjip** [comment]
Decals added in https://github.com/space-wizards/space-station-14/pull/20435/commits/57e5e8c9c5f608b917dbba777a09aad00dc7e30a .

**Comment by JoeHammad1844** [comment]
nice

**Comment by TsjipTsjip** [comment]
Issue remaining on this merge: There's not enough medical doctor lockers to cover the map prototype's staff allocation (1-1 senior, 3-5 doctors, 8-8 interns). This will be fixed in a future commit.

**Comment by TsjipTsjip** [comment]
Added lockers, but actions failure does seem related. I'm gonna see what's up with that.

**Comment by TsjipTsjip** [comment]
YAML validator should now be passing. PR is ready for review, no additional work will be done unless requested.

**Pull request merged**
