### PR TITLE
Welding fuel now evaporates

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Added welding fuel to list of reagents that evaporate

## Why / Balance

Common tactic is to just break welding fuel tanks at all the sec doors during revs and they have no options to clean it for the rest of the shift, this nerfs it although I'm sure revs will just switch to using soda

Maintainers have mentioned in passing that all slippery liquids should evaporate over time, but the implications that has on space lube is uh.... not one I want to just PR without someone telling me to

## Technical details

Gotta admit the way evaporation reagents are set up feels kind of... gross

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl:
- tweak: Welding fuel now evaporates over time.

### CODE REVIEW

**Comment by deltanedas** [comment]
make it ProtoId[] at least

**Comment by 0x6273** [comment]
Welding fuel doesn't have a gas equivalent so this wouldn't work when evaporation gets fully implemented.

**Comment by Plykiya** [comment]
> Welding fuel doesn't have a gas equivalent so this wouldn't work when evaporation gets fully implemented.

fully implemented?

**Comment by 0x6273** [comment]
> > Welding fuel doesn't have a gas equivalent so this wouldn't work when evaporation gets fully implemented.
> 
> fully implemented?

Right now it just deletes the reagents instead of evaporating.

**Comment by Plykiya** [comment]
> > > Welding fuel doesn't have a gas equivalent so this wouldn't work when evaporation gets fully implemented.
> > 
> > 
> > fully implemented?
> 
> Right now it just deletes the reagents instead of evaporating.

feels like it would get kind of complicated for atmos to deal with that many different gasses...

**Comment by Plykiya** [comment]
> make it ProtoId[] at least

seems like a lot of other functions in Solution.cs expect it to be a string[] and I'm brain damaged trying to convert from ProtoId<ReagentPrototype>[] to a string[]

**Comment by metalgearsloth** [comment]
> > make it ProtoId[] at least
> 
> seems like a lot of other functions in shared Solution.cs expect it to be a string[] and I'm brain damaged trying to convert from ProtoId[] to a string[] in a way that's smarter than adding an overload on every function that takes `ProtoId<ReagentPrototype>[]`, then doing a `foreach prototype in prototypes`, and prototype.ToString() on each one....

they cast

**Comment by Psychpsyo** [comment]
~~new jani idle game just dropped?~~

**Comment by IamVelcroboy** [comment]
Should just condense to an extra slippery oil slick

**Comment by Plykiya** [comment]
> > > make it ProtoId[] at least
> > 
> > 
> > seems like a lot of other functions in shared Solution.cs expect it to be a string[] and I'm brain damaged trying to convert from ProtoId[] to a string[] in a way that's smarter than adding an overload on every function that takes `ProtoId<ReagentPrototype>[]`, then doing a `foreach prototype in prototypes`, and prototype.ToString() on each one....
> 
> they cast

maybe I'm doing it wrong but it's not casting for me

**Comment by Plykiya** [comment]
Two new symptoms I have to deal with

1. Because welding fuel evaporates, you can't mop it because the absorbent system thinks as long as a puddle is evaporating it's fine to just leave it alone
2. The absorbent system treats all evaporating reagents as something acceptable to clean with, meaning you can now use welding fuel to mop up puddles

Great, great great....

**Comment by diraven** [comment]
What happened to space cleaners, cleaner grenades, janitors, cleanbots etc? Can they not clean that up?

**Comment by Plykiya** [comment]
> What happened to space cleaners, cleaner grenades, janitors, cleanbots etc? Can they not clean that up?

during revs? there's basically no access to any of that

**Comment by PJB3005** [comment]
I would rather make welding fuel not slippery than make it just evaporate into nothing. The real risk with a welding fuel leak should be the *fire hazard* whenever we ever implement non-gas fires.

**Comment by Plykiya** [comment]
alrighty

**Pull request closed without merging**
