### PR TITLE
Revert Removal of Senior roles

### PR DESCRIPTION
**Pull request by RaptorGalaxy**
## About the PR
I reverted the removal of Senior Roles because I thought it was a bad idea and that they had a lot of value for teaching new players.

## Why / Balance

For many departments senior roles were useful for teaching new players as well as indicating to new players who should be trusted to help them. This was especially apparent in Security where the complexity of the job as well as the need for the Head of Security and Warden to deal with other concerns during a round made it difficult for them to effectively teach Cadets. Relying on other Security Officers was not always possible as the job takes a long time to learn and Security Officers are frequently not up to the challenge of teaching new Cadets as they are not always completely competent themselves. They were also useful for Security with the current meta of placing Cadets in squads lead by Senior Officers to help teach Cadets. 

Senior roles were useful because they provided a way for players to self designate as instructors as well as allow new players to quickly identify who they could expect to help them to learn their job.

Concerns about people playing those roles and refusing to assist new players are better resolved either in character (demotion etc) or out of character through Moderator intervention.

## Technical details

This is just a reversion of the commit that removed Senior Roles. I have not tested it at time of writing so it may cause issues.
## Media

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: Senior Roles.

### CODE REVIEW

**Comment by HoidC** [comment]
it begins

**Comment by CrigCrag** [comment]
changelog typo

**Comment by deltanedas** [comment]
cl has a typo, close pr now

**Comment by Errant-4** [comment]
Please add a "." to the end of the cl entry

**Comment by deltanedas** [comment]
and remove s

**Comment by RaptorGalaxy** [comment]
Failed to build because Seniors don't have spawnpoints on Aspid.

**Comment by Kadeo64** [comment]
can we add and remove seniors every week it would be funny I think

**Comment by deathride58** [comment]
It'd be far better to reimplement them as alt titles that're automatically applied if a player meets the conditions. Senior roles as a separate job carry maintenance overhead for not much benefit over that alternative.

**Comment by deltanedas** [comment]
an idea that may be better is experienced players can opt in to being a teacher
if an intern role joins it tells them either in greeting or as a popup in center for visibility, saying talk to XYZ to learn stuff

**Comment by Nairodian** [comment]
Look, don't start a back and fourth. That makes this whole thing look really bad.
Try to actually address concerns brought by #22303 and on the original #18181 PR, otherwise the opinion isn't going to change.
I've given up on this whole ordeal because I'm not knowledgeable enough to do a lot of this and am busy with my own stuff, hell the original thing was just a middle ground because we had no other way to do it at the time.

Currently the general idea from maintainers is to make it into some kind of opt-in title system based on your playtime, but that doesn't have any work going into it as far as I'm aware.

However for other ideas, a good place to start is proper communication on what the role does, both to the player playing it and new players. Whole slew of ways to do this, to name a few;
- Some kind of text pop-up for people taking the role, in chat, in it's own box, who knows.
- Text pop-up for new players pointing out what a Senior role is and does.
- Job icons that point out Seniors to Interns and Interns to Seniors.

For more balance and design choices;
- Removal of their extended access so people stop using them just to multi-job. (I am not a big fan of this as it restricts what a Senior can teach, but if it helps in teaching new players I'll live with it)
- A system that treats Senior role slots the same as the basic job slot, so if all the Engineer slots are taken, so is the Senior role, as to prevent people from just picking it to divert full departments.
- Make a new whitelist system and make it whitelist only, so admins allow select people they know would use the role properly. (Once again, I don't like this idea as it creates more admin work, but I could see it being very good.)

There are very few ways to actually "mechanically enforce" or "encourage" teaching, so I do kind of disagree with those stances, but it stands there are ways to improve the system from what it is, and it's not going to get re-added if you don't do that.

**Comment by keronshb** [comment]
We're not looking to readd them at this time.

If you can implement a system that can prefix a title depending on hours played that would be a preferable solution. And even then the "Senior" title should also be optional.

**Comment by Nairodian** [comment]
> If you can implement a system that can prefix a title depending on hours played that would be a preferable solution. And even then the "Senior" title should also be optional.

I'm going to leave my collection of thoughts about this here, as it's the best place to be seen for any soul who's going to try to add this system, and so I don't have to mention them after it's made.
(I'm not a maintainer, but I feel like these gripes are reasonable.)

- The title needs to carry with it the expectation of teaching, just like the roles did, otherwise it'll fall down to the same "I have more hours than you, fuck off" issue.
- The title needs to be opt-in, as stated above.
- The fact it'd take a basic job slot is poor to me, as a Senior shouldn't be expected to drop their teaching to help a department.
- I don't think the possibility of having a department full of all Seniors is sane or a good idea, I personally think the title should be limited to one person per department.
- Having it not be it's own role restricts their access, meaning it restricts what they can teach without extra hurdles to jump through.
- Preferably admins would have a way to ban players from using the title if they aggressively misuse it, just like the role.
- The lack of communication between new players and what a Senior does still needs to be fixed some how, as it'd be even worse now because a new player isn't going to go around checking people's ID cards like that. The clothing was made to make them stand out at least a little bit.

**Comment by nikthechampiongr** [comment]
>     * The title needs to carry with it the expectation of teaching, just like the roles did, otherwise it'll fall down to the same "I have more hours than you, fuck off" issue.

How would that be implemented? We could make it clearer that it's a teaching role but that is just a recommendation to players.  Leaving it to admins to enforce it will put a big burden on administration because we'll have to look over seniors to make sure they are teaching people along with everything else. I guess you could make it a whitelist thing but that may be a bit too much.

**Comment by keronshb** [comment]
> > ```
> > * The title needs to carry with it the expectation of teaching, just like the roles did, otherwise it'll fall down to the same "I have more hours than you, fuck off" issue.
> > ```
> 
> How would that be implemented? We could make it clearer that it's a teaching role but that is just a recommendation to players. Leaving it to admins to enforce it will put a big burden on administration because we'll have to look over seniors to make sure they are teaching people along with everything else. I guess you could make it a whitelist thing but that may be a bit too much.

Change "Senior" to "Teacher"

**Comment by GJAAMER** [comment]
Does anyone even understand why stupid decisions are made, like removing leading roles, even when almost no one supports them?
The game is castrated - and rejoices
and when they ask us to return what was good and everyone supports it, we get a refusal...
Official development does not take into account people’s opinions at all

**Comment by metalgearsloth** [comment]
> Does anyone even understand why stupid decisions are made

Thread's not a dumping ground for your garbage. Please refrain from being toxic in future.

**Comment by OtherSkittle** [comment]
> How would that be implemented? We could make it clearer that it's a teaching role but that is just a recommendation to players...

Is the job title and description of Scientist just a recommendation too? Can scientists just go do cargo work if they want to without changing their title? The fact that it requires 60 or however many hours to even unlock (and should also be optional) is in my opinion enough for them to be blamed if they didn't figure it out yet.

>  Leaving it to admins to enforce it will put a big burden on administration because we'll have to look over seniors to make sure they are teaching people along with everything else. I guess you could make it a whitelist thing but that may be a bit too much.

Admins don't have to put more effort than any other rule breaker in the game. If someone is ahelped for refusing to teach with a senior prefix then they can be checked out. Not all seniors need to be tracked constantly. There might even be plenty of rounds where a senior exists and there are no players that require teaching after all.

**Comment by EmoGarbage404** [comment]
> There might even be plenty of rounds where a senior exists and there are no players that require teaching after all.

is there any other role in the game where your purpose is irrelevant for "plenty of rounds"? Half the reason seniors dick off so hard is because you might not have any new players to teach or the new players might not want you to instruct them or even know that you are supposed to.

roles are meant to just be default IC representations of tasks that someone is meant to be doing. They're not set in stone, they're not unchangeable, but they represent a concrete concept.

Seniors and mentor roles in general fail because you're approaching an IC problem with some kind of RP solution that just isn't going to work. New players just need the information presented as clearly as possible so they can learn and do their stuff. Having to RP out an encounter to learn things is just going to lead to OOC talk and be arguably a harder barrier of entry than just reading the wiki.

that aside, my issue isn't with teaching new players info, but what roles do to game balance as a whole. Roles shouldn't be overlapping and doing one another's jobs. If a role is marked by experience and is going to be twiddling their thumbs for possibly entire rounds, it's just going to lead to situations where they do other roles jobs because _teaching new people isn't enough content to remotely justify a job._

needing admins to enforce manage players and doing their jobs isn't the issue, but it becomes an issue with the role as a whole when you can go multiple rounds in a row with literally nothing to do, especially on MRP servers where players are going to be more skilled, on average. A player with nothing to do is going to inevitably step on the toes of other roles, which isn't ideal.

**Comment by PJB3005** [comment]
> Is the job title and description of Scientist just a recommendation too? Can scientists just go do cargo work if they want to without changing their title? 

On LRP, yes actually.

I think you'll generally find that what drives people to "do their job" is more the fact that they started with access and equipment for their job, and the fact that if you selected a job you probably don't hate playing it.

> If someone is ahelped for refusing to teach with a senior prefix then they can be checked out.

New players, who would be the "victims" under such a policy, generally are not going to know what rules are being violated and start slinging ahelps on the first day of the job.

Ahem.

Seriously this entire thing seems so mechanically poor. Tying a charitable intent (teaching) to an exclusive prestigious job slot just creates a conflict of interest. Now admins have to clean up the mess.

Having it as an alternate job title is really the only good choice here. It doesn't convey prestige, it doesn't require extra playtime. People enable it *if they want to teach* and there's no other reason to enable it otherwise.

Also I'm sure I've seen some arguments like "how would new players know who to ask for getting taught without this?". Uhm:

> :m hey I'm kinda new, does anybody mind mentoring me?

Like seriously even if I want to be charitable I do not see these as necessary in the first place, let alone worth kicking up drama over.

**Comment by OtherSkittle** [comment]
> is there any other role in the game where your purpose is irrelevant for "plenty of rounds"? Half the reason seniors dick off so hard is because you might not have any new players to teach or the new players might not want you to instruct them or even know that you are supposed to.
> ...
> but it becomes an issue with the role as a whole when you can go multiple rounds in a row with literally nothing to do, especially on MRP servers where players are going to be more skilled, on average. A player with nothing to do is going to inevitably step on the toes of other roles, which isn't ideal.

So is the general consensus that senior roles are only there to specifically teach and completely ignore their job otherwise? Because I was not personally aware of that. I think senior roles should be something of a marker for new players to know they are people that have designated themselves as willing to teach the job.

Also RP roles already exist that have the same "problems" so you might as well remove them too. Isn't half the point of the game the roleplay aspect?

> Seniors and mentor roles in general fail because you're approaching an IC problem with some kind of RP solution that just isn't going to work. New players just need the information presented as clearly as possible so they can learn and do their stuff. Having to RP out an encounter to learn things is just going to lead to OOC talk and be arguably a harder barrier of entry than just reading the wiki.

So why do intern roles exist? As far as I know, intern roles have 100% overlap with regular roles, uselessly occupy job slots similarly to senior roles and fail to advertise degree of knowledge in that specific job (since hours fail as a metric for knowledge, experienced people can still use intern roles if regulars are filled up and the amount of time required to unlock the regular role is pitiful). The only thing that is left is the RP component of playing as a character that doesn't know the job.

I don't know what makes you think that talking to people in the game would "arguably (be) a harder barrier of entry than just reading the wiki", but there are people who learn better from examples than from being loredumped by the wiki. Let's not forget how out of date/incomplete it is and just generally is a pain to use during the game. If "information presented as clearly as possible" is the goal here then the wiki is a really bad replacement over a living breathing human being that can actively explain the game to you with the thing that is being explained right in front of the new player.

As things stand right now, new players won't just suddenly stop asking other players for help with learning their job, and people who know their job will still have to take time out of running the station to teach the new player, and this will also again lead to the same exact issues of 'rp solution for ic problem' and 'is probably going to lead to ooc chat', so I really fail to see how removing senior roles is in any way related to this.

The only thing it accomplishes is to make it harder for new players to find people that are willing to teach them. I don't know how much harder that is or how big of a problem it is but frankly considering the only benefits are (as far as I can tell) to stop people from using the role as a playtime flex, well, I just wonder why we didn't wait for a replacement before removing it.

And not to get off topic but

> New players, who would be the "victims" under such a policy, generally are not going to know what rules are being violated and start slinging ahelps on the first day of the job.

Is this seriously necessary? Because the only thing even thinking to write this in the first place manages to do is taint this whole debacle as thinly veiled hatred towards new players.

Just to clarify my position on this so people don't just assume I want this reverted or whatever:

- removing senior role = good (poor implementation in hindsight plus role bloat)
- removing senior role without replacement = bad (why now? no seriously I'm not trying to be mean or anything I assume it was this bad for a long time so why specifically now and not when a replacement is available?)
- intern roles still existing = highly confusing considering removal of senior roles (what is even the point of these roles? none of the ss13 servers I'm aware of have this)
- prefix thingy = good I hope this one happens
- learning by reading the wiki = good although wiki could be better but alas
- learning by asking others = also good
- arguing that only one of these is necessary/is sufficient/should exist = bad (more options are always better imo)

**Comment by RaptorGalaxy** [comment]
Well that was closed pretty quick.

**Comment by PJB3005** [comment]
> > New players, who would be the "victims" under such a policy, generally are not going to know what rules are being violated and start slinging ahelps on the first day of the job.
> 
> Is this seriously necessary? Because the only thing even thinking to write this in the first place manages to do is taint this whole debacle as thinly veiled hatred towards new players.

I genuinely cannot fathom what could possibly make you read my comment like this.

**Comment by OtherSkittle** [comment]
> I genuinely cannot fathom what could possibly make you read my comment like this.

No other rule break would justify using victim with quotation marks like this. The only reason that I can think of for someone to put quotation marks in that context is that they do not agree that new players would be victims in that circumstance, that they are actually posers and have not suffered from being affected by a rule being broken like everyone else does. In reality if that rule were to exist new players wouldn't be "victims", they would just be plain victims like every other person who is affected by a rule break.

Now I don't know if this was your intent but I genuinely do not see any other intent to adding quotation marks like that. You're not quoting anyone as far as I can tell.

**Comment by PJB3005** [comment]
I put "victim" in quotation marks because it's such a petty and minor transgression (that isn't even in the rules, and absolutely should not be either).

I'm going to encourage you to be a little more open minded (and also, like, engage with the actual argument?) instead of saying stuff like "you hate new players!!".

**Comment by Aexxie** [comment]
> changelog typo 

Cl fuckery, doesn't say "Added"

**Comment by OtherSkittle** [comment]
> I put "victim" in quotation marks because it's such a petty and minor transgression (that isn't even in the rules, and absolutely should not be either) that it barely even seems severe enough to use the word. If I wanted to be less brief I would've used "the people who are affected" or something.

If you don't think it's severe enough to use the word then don't use the word. You're the one who picked the word. If the word didn't reflect what you meant to say then don't use that word. It's literally that easy.

Either than that it appears we are in agreement. You think it would be a petty and minor transgression, and I agree that you think that. Considering advertising that part of your belief is completely unrelated to the rest of your post I fail to see the reason behind adding it aside from, well, advertising that you think lesser of new players.

And for the record, not being a dick is already in the rules, it just happens that the rules are pretty much never enforced on LRP. As for whether or not taking a role whose only purpose is to be a teacher for new players (and do your job) and refusing to teach new players counts as being a dick to new players, well, personally I think it counts but what do I know. It's not like I think these people should be permabanned. But if a person is misusing a role to that degree I don't see why they shouldn't be rolebanned at least.

> I'm going to encourage you to be a little more open minded (and also, like, engage with the actual argument?) instead of saying stuff like "you hate new players!!".

Do you really think the reason that I ignored the rest of your comment was because I am too closed minded? My post was already too fucking long to begin with why would I have any qualms about adding a couple more paragraphs if I felt necessary. There is nothing in your initial post that I disagree with aside from maybe the first paragraph but that part is also completely off topic so I didn't bring it up.

The only reason I mentioned you at all is because of that unnecessary comment of yours.

**Comment by Nairodian** [comment]
Okay jesus fuck it's not that deep. Yes, Senior roles are important and discussion is needed, but they're not major to the game unless you're new. I really hate the way _everyone_ has reacted, it's a stupid space game, just chill out.

If you're going to discuss be respectful and forward discussion on how to reimplement the system in a new fashion, if you have gripes outside of that, there are other places to voice those without making everyone who collectively like Senior roles look bad.

**Pull request closed without merging**
