### PR TITLE
Resolves ReinforcedWallVisualizer is Obsolete

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About the PR

Splits the ReinforcedWallVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by deltanedas** [comment]
madlad actually made 50 prs

**Comment by metalgearsloth** [comment]
respect

**Comment by CaptainSqrBeard** [comment]
man took this line in PR guideline too serious 💀 
image

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Generic Visualizer

**Comment by DrSmugleaf** [comment]
Reopen when you come back to this.

**Pull request closed without merging**
