### PR TITLE
Add suit storage

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
Adds suit storage for oxygen if you have outer clothing equipped
**Screenshots**

image

**Changelog**

:cl: Daemon
- add: Added suit storage!

### CODE REVIEW

**Review by juliangiebel — APPROVED** [review]
Should really any piece of outer clothing enable the suit storage slot?
Other than that lgtm

**Comment by ElectroJr** [comment]
> Should really any piece of outer clothing enable the suit storage slot?

IMO only specific clothing should enable extra inventory slots. Also those slots should probably be hidden from the UI until the user has the appropriate clothing equipped. So this probably isn't the right way to do this and would require extending the inventory system.

**Comment by ZeroDayDaemon** [comment]
Because any clothing at the moment works, is why i've specifically limited the slot to only oxygen canisters for the moment until systems are in place that make it able to only be enabled by certain clothing

**Comment by ZeroDayDaemon** [comment]
I'll try and make a suitstorage component ig

**Review by PaulRitter — APPROVED** [review]

**Comment by PaulRitter** [comment]
some refactor is needed of the inventorysystem, yes, but out of scope for this imo

**Pull request merged**
