### PR TITLE
Gauze Markings 2 - Medical Boogaloo

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
Added eight (8!!!) new markings [at time of pr], four exclusive to the lizards, mostly to fix sprite errors, as well as removing them from slimepeople, unfortunately they are too goopy to be wrapped in bandages. Also it fixes the right thigh wrap so it no longer says 'leg' wrap >:(

## Why / Balance

Consistency is important, as well as making the markings actually _look good_ on lizard people, as well as adjusting it so slimes can't get wrapped. . . how would that even work?
## Media

image
image
-TODO-

- [x] Add photos

## Breaking changes

**"Changelog"**

Tweaked/Added: Lizard inclusive eyepatches, using latest invention "K.C. Medical Tape" to hold parts down to account for frills.
Tweaked/Added: Lizard claws are now accounted for when being bandaged.
Tweaked/Removed: Slimes can no longer be mummified.
Removed: My sanity.

actual changelog
:cl:
Removed: Removed Gauze markings from slimes
Added: Added five new markings to Lizards to account for sprite differences
Added: Added two new markings to cover your knuckles for all except slimes and Diona
Added: New blindfold wrap, lizard variant included

### CODE REVIEW

**Comment by UbaserB** [comment]
send photos!

**Comment by KittenColony** [comment]
i broke two dev environments to make this fucking thing im trying my best

**Comment by KittenColony** [comment]
if someone wants to actually get me some images for these that'd be amazing

**Comment by KittenColony** [comment]
photos snent.

**Comment by CrigCrag** [comment]
i don't know if it was fixed but i think the scar snd eyepatch sides from the initial PR are backwards from each other. the right eyepatch shows up on the right eye but the right scar shows up on the left eye.

**Comment by KittenColony** [comment]
So for some reason everything is just fucking broken



> i don't know if it was fixed but i think the scar snd eyepatch sides from the initial PR are backwards from each other. the right eyepatch shows up on the right eye but the right scar shows up on the left eye.

You'd have to ask @UbaserB about that, as it stands I can't add more to this PR without breaking anything due SDK bullshit 😔

**Comment by KittenColony** [comment]
fixed it

**Comment by KittenColony** [comment]
as it stands this is ready to be merged, the content is ready

however if we merge it now then there will have to be a "Gauze 3" in order to add moth wraps and such

**Pull request merged**
