### PR TITLE
Tweaking weldable component fuel consumption

### PR DESCRIPTION
**Pull request by Wirdal**
## About the PR
Changing the default fuel consumption that weldable entities consume. I'm not sure if this is exactly enough, but it's a starting place. Open to tweaking more. I didn't change security doors cause they already seemed deliberately high. In all, this should make fuel make something you're cognizant about whenever you're welding clowns in an airlock.

Now, one thing the issue mentioned was that experimental welders regenerated more fuel than they consumed when on. I didn't address this in this PR, but I was considering disabling fuel regeneration when it was on for those sorts of entities.

https://github.com/space-wizards/space-station-14/issues/16130

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Changed fuel consumption for weldable things to be higher in general.

### CODE REVIEW

**Comment by deltanedas** [comment]
i think best solution is for being lit to consume much faster (like 2/s) and have no fuel consumed by the doafter, which rewards bulk welding, nerfs cauterising a bit, makes regen more noticable when off

**Comment by Wirdal** [comment]
Yeah, I suppose it makes sense. I'm not a welder so I don't really know if you need to "turn it up" when welding.

Maybe a combination of both is a way to go? I think high sec doors costing more makes sense to me.

**Comment by kuesa** [comment]
lgtm 👍

**Comment by deltanedas** [comment]
high sec doors would take more since more time = more time spent lit = more fuel used

**Comment by Wirdal** [comment]
They already take more time to weld. I think you're suggesting removing some functionality from the weldable components entirely. By having a strict fuel consumption per time unit, with no fuel interaction on what you're welding

**Comment by deltanedas** [comment]
exactly, then to make something consume more fuel just increase the welding time

**Comment by Wirdal** [comment]
Well, all things considered this still tackles the issue. Removing properties from a component is a slightly larger undertaking that I would probably want a new task for. Since I'm brand new to the project, I don't feel comfortable doing this off the cuff for the related issue.

**Comment by deltanedas** [comment]
yeah current changes seem fine, ill probably do welding change after

**Pull request merged**
