### PR TITLE
uichange APC

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
## About the PR

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: DEATHB4DEFEAT
- tweak: Nicer APC UI

### CODE REVIEW

**Comment by metalgearsloth** [comment]
I'd rather have https://discord.com/channels/310555209753690112/346743671787356160/1077881323043160114 for APCs

Also you used buttons as panelcontainers again.

**Comment by DEATHB4DEFEAT** [comment]
> I'd rather have https://discord.com/channels/310555209753690112/346743671787356160/1077881323043160114 for APCs

that does look much better

**Comment by jamessimo** [comment]
Ah I didn’t see this PR before making mine. 

https://github.com/space-wizards/space-station-14/pull/14258

**Comment by AJCM-git** [comment]
> Ah I didn’t see this PR before making mine.
> 
> #14258

Yours looks better, so i think it would supersede this

**Pull request closed without merging**
