### PR TITLE
reenable revs

### PR DESCRIPTION
**Pull request by Emisse**
reenabled but make it very rare, i honestly think the biggest issue beforehand was how prevalent it was, i think its fine if its rare atm pending the revs remake

🆑 
- tweak: Rev's reenabled

### CODE REVIEW

**Comment by deltanedas** [comment]
rest in piss zombies

**Comment by MACMAN2003** [comment]
finally, less traitor rounds

**Comment by K-Dynamic** [comment]
Idk if rarity impacted its issues

**Comment by Emisse** [comment]
beforehand it was almost as prevalent as traitor so a very clear meta was defined

**Comment by Ilya246** [comment]
revolution against zombies is real

**Comment by Hmeister-real** [comment]
My god, finally. less fucking traitor rounds with power gaming sec or the Lizard 5-zombie-rounds-in-a-row incident

**Comment by asperger-sind** [comment]
Can we re-add suspicion now :trollface:

**Comment by Kadeo64** [comment]
time to wear a welding mask everywhere again :trollface:

**Comment by EmoGarbage404** [comment]
I have a minor change to flashes that i want to do before this is properly reenabled.

**Comment by SpeltIncorrectyl** [comment]
I miss revs... I should call them

**Comment by LankLTE** [comment]
Weren’t there a fair few admin issues with revs? Maybe you talked with them already but that should probably happen before this is merged

**Comment by Everturning** [comment]
real or (let them eat) cake?
maybe make it so that headrevs can get 1 (one) implanter for converting mindshielded person roundstart, to encourage demindshielding

**Comment by wafflewarior** [comment]
I thought it was waiting a rework. enabling a game mode with underlying issues even if you make it rare just seems like you're making it so every once and a while there will just be a bad round.

**Comment by Hmeister-real** [comment]
> I thought it was waiting a rework. enabling a game mode with underlying issues even if you make it rare just seems like you're making it so every once and a while there will just be a bad round.

It solves more problems than it adds at the moment. The lack of diversity is accustoming new secoffs into bad habits and the repetetiveness of all of the other game modes is shit.

**Comment by Krunklehorn** [comment]
> It solves more problems than it adds at the moment.

No it does not. The frequency of rev rounds could be seen as one of the issues with the gamemode, but certainly not the most prominent.

**Comment by coolmankid12345** [comment]
And here I thought I would never see my son again

**Comment by FungiFellow** [comment]
Revs manages to be less fun to deal with than zombies, and that's saying something.

**Comment by Emisse** [comment]
> Weren’t there a fair few admin issues with revs? Maybe you talked with them already but that should probably happen before this is merged

admins are fine with this

**Comment by vorkathbruh** [comment]
we are so back vivabros

**Comment by wafehling** [comment]
All I'd suggest is removing the 5% from traitors instead of zombies. Traitors is fun enough but incredibly common.

Otherwise, yes please.

**Comment by pigeonpeas** [comment]
taking it from zombies is probably not the best choice, maybe take it from survival or traitors?

**Comment by MACMAN2003** [comment]
> taking it from zombies is probably not the best choice, maybe take it from survival or traitors?

i think taking it from traitors would be a good idea

**Comment by Golinth** [comment]
we're so fucking back. Does this mean that PRs related to revs will be accepted, or are we still waiting for the rev rework before anything can be worked on

**Comment by metalgearsloth** [comment]
> we're so fucking back. Does this mean that PRs related to revs will be accepted, or are we still waiting for the rev rework before anything can be worked on

They're not being accepted unless it's a full rework.

**Comment by thebadman4662** [comment]
Are revs capable of convering people considering flashes are bugged now with all 3 attacks and do not hit anyone but the owner with Z attack AOE?

**Comment by SpeltIncorrectyl** [comment]
VIVA!

**Pull request merged**
