### PR TITLE
remove coal from the ore processor steel recipe

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

removed coal from the steel crafting recipe in the ore processor
## Why / Balance

having steel (the most asked for resource) require a secondary, rarer resource to craft makes it painful for cargo when they have enough steel in the ore processor but not enough coal, making it so they have to beg salvage to do another mining trip just to get some coal.
## Technical details

n/a
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The ore processor no longer needs coal to print steel.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Coal and steel are equal rarity last time i checked. Is something wrong with the generation?

Removing coal is dumb becauss then it literally has 0 purpose.

**Comment by IamVelcroboy** [comment]
Yeah, what Emo said. It should be the same drop rate. Would it help to have a coal veins maybe?

**Comment by poklj** [comment]
in one round of Salvage we pulled 2 mag astroids, did 2 static Asteroids and an expidetion resulting in 0 coal, and 675 sheets of steel on fland station; I know it's only n=1 for sample size but uh, salv is broken while coal is part of this recipe

**Comment by EmoGarbage404** [comment]
If coal isnt generating then someone should fix that.

**Comment by IamVelcroboy** [comment]
Spawning in both low yield(left) and high(right) I am getting both coal and steel when I test 
image

**Comment by IamVelcroboy** [comment]
OK, I see the issue. It looks like procgened asteroids are using WallRock which does not inherit the loot pool and very few pre-mapped asteroids are using the asteroid rock that does.

I think I'll give Wall Rock a chance top drop coal. The alternative would be to have coal veins. (Would need more sprites for that.)

**Comment by metalgearsloth** [comment]
Better pr is up.

**Pull request closed without merging**
