### PR TITLE
Increase syndicate uplink discount amount to 6.

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Increased the amount of discounted items syndicate agents have from 3 to 6.

## Why / Balance

The point of the discounts was to encourage trying new items and strategies, however having the amount be only 3 almost never gave anything worth using. I believe this change will help syndie agents actually make cool things with the discounts instead of never looking at the tab.
Chance to roll different discount categories remains unchanged.

## Technical details

Increased amount of uplink discounts to 6 and modified the tests to account for that.

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Syndicate uplinks now have 6 discounts instead of 3.

### CODE REVIEW

**Comment by slarticodefast** [comment]
Why the hell is that number hardcoded everywhere in the first place?

**Comment by beck-thompson** [comment]
Love this change! Hopefully this gives some unused items more love. Even with 3 I've chosen items I never would have before, making it 6 will really help

**Comment by ScarKy0** [comment]
> Why the hell is that number hardcoded everywhere in the first place?

Wish I knew. Was hella confusing to find since I thought its in a yml file

**Comment by ScarKy0** [comment]
Next step after this is giving nukies discounts :godo:

**Comment by ArtisticRoomba** [comment]
holy hardcode

**Comment by ScarKy0** [comment]
> Might be pedantic but I think five discounts would be better (especislly if the discounts apply on multiple already-popular items)

Discounts have a decreased chance to happen on the stronger items alrrady (think emags etc), theyre not all the same chance

**Comment by SlamBamActionman** [comment]
I've checked the discount menu every now and then and I have largely been disappointed by the selection. It's either something pointless, something that is still expensive, or something that won't work for my current objective. 

I guess if you end up with 4+ good discounts this might be a bit too powerful, but I am willing to see how this rolls.

**Review by SlamBamActionman — APPROVED** [review]

**Comment by chromiumboy** [comment]
Sure, let's give it a go

**Pull request merged**
