### PR TITLE
Rewires the closet behind the HoP's office.

### PR DESCRIPTION
**Pull request by TimrodDX**
[MAPPING]

## About the PR 

This PR adds exactly five LV wires to the substation closet behind the HoP's office. Previously, this room had a light fixture in it but no LV wires, meaning the light would always be unpowered unless someone manually wired it up. The wires are extended from the APC in the Captain's office, which shouldn't change the overall power net too much.

**Screenshots**

image

This is the room as it exists on live.

image

This is the same room with the extra wiring. No other changes were made.

**Changelog**

:cl:
- tweak: Rewired the closet behind the HoP's office on Saltern.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
screenshot?

**Comment by TimrodDX** [comment]
> 
> 
> screenshot?

Oh, sorry. Just added them. If you need them from mapping mode I can also do that, but some of the wires aren't visible because they go under a wall and the substation.

**Comment by SweptWasTaken** [comment]
Conflicts :/

Might have to redo it.

**Comment by SweptWasTaken** [comment]
> 
> 
> Conflicts :/
> 
> Might have to redo it.

I fixed it for you and pushed it to master, so closing this. Good first PR.

**Pull request closed without merging**
