### PR TITLE
[Add] Adds winterdrobe

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

Adds a winterdrobe to house the newly added scarfs. Sprite thanks to MrGreen06.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**

:cl: MrGreen and OctoRocket
- add: Added a winterdrobe to store all your scarfs!

### CODE REVIEW

**Comment by lzk228** [comment]
you should add refilling kit

**Comment by Emisse** [comment]
can you remove the winter stuff from normal clothesmate, and add a restock box to this

**Comment by OctoRocket** [comment]
Done!

**Comment by Jackal298** [comment]
You forgot to transfer the syndicate scarves that appear after the clothing machine emag

**Pull request merged**
