### PR TITLE
SyndiCat

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Added new ghost role to be bought at nukeOps uplink for 10 TC.
Syndie Cat, implanted with microbomb.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/f8f2194f-195e-4039-b39f-0d6b9280c5e2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new ghost role to be bought at uplink for 10 TC. Syndie Cat, implanted with microbomb.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Isnt this basically just an upgraded grenade penguin?

**Comment by TheShuEd** [comment]
Looks like it. Forgot the penguin existed.

**Comment by deltanedas** [comment]
mouseops + syndicat beloved team

**Comment by TheShuEd** [comment]
meh. map render error... ignore

**Comment by JoeHammad1844** [comment]
TK :trollface:

**Comment by JoeHammad1844** [comment]
10TC is a little pricey though. bomb penguins (are perfectly priced in my opinion) have AI so its really good at killing people efficiently due to how robust AI is, dodging and weaving and having precise attacks.

paying double for a budget version sounds like a ripoff

**Comment by TheShuEd** [comment]
Unlike the penguin, this cat can now explode at the press of an implant ability button. Also, the player is clearly smarter than the penguin, and can ambush the target. And the damage from the microbomb explosion is quite high

**Comment by JoeHammad1844** [comment]
valid cat is kill on sight and doesn't have any access so its pretty hard to ambush even with the instant detonation

**Comment by ps3moira** [comment]
👀

**Comment by TheShuEd** [comment]
If it's not needed, tell me, I'll close the PR

**Comment by Jezithyr** [comment]
This is hilarious and definitely fits SS14, maybe in the future we can have the cat be able to ventcrawl 😏

**Pull request merged**
