### PR TITLE
Tried to make large wood less ugly

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
Where everyone saw only hideousness I saw potential (and hideousness) So I tried to make it look better.

I made the planks less short by using variants with less cuts in the planks.

There still are some shorty planks, but I kept them because I think having them appear occasionally serves to break it up visually rather than it looking the same in every spot.
## Why / Balance
It looked bad

## Media
image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
The tile has a higher number of variants, requiring revariantizing on maps which use them. However I don't think any maps currently use them (because they are so ugly) but it may be of concern downstream.

**Changelog**
:cl:
- fix: Fixed large wood planks being so repulsive.

### CODE REVIEW

**Comment by Moomoobeef** [comment]
I am welcome to remove some of the shorter ones so they are less common (or kill them entirely) if folks think I should

**Comment by Psychpsyo** [comment]
> I am welcome to remove some of the shorter ones so they are less common (or kill them entirely) if folks think I should

I think getting rid of the very short ones is a good idea.
They're just kinda meh.

**Review by TheShuEd — CHANGES_REQUESTED** [review]
Please edit attribution files

**Comment by TheShuEd** [comment]
3 weeks without responding on requested changes...
Ok, seems it derelict now.

If you wanna continue work on your PR, please comment and we reopen it.

**Pull request closed without merging**
