### PR TITLE
Add spices

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Adds a new condiment and its related shaker; spices! A full shaker spawns in the chef belt, and can be used to top foods for a little bit of extra flavour. I was not sure which plant reagents to pick for refilling the shaker, so i decided for it's recipe to use capasisisian oil and like black pepper. As someone who plays a lot of chef nowadays, i feel like this will be a great change 👍🏻 

## Why / Balance

I know it’s underutilised, but recently i have become obsessed about flavour text. When i ate food that said “this burger tastes spicy, like ketchup and mustard and eggs and cheese” or something along those lines (yes i know i could have worded it better) it made me really happy. Ive been looking forward to a might higher standard of roleplay and i may even roleplay eating a burger or sort of food at a desk and use the forks and spoons )that are also never used)! If needed though, i can add this to recipes to add variety and more properly integrate it but all i really want is that extra kick of flavour.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

image

**Changelog**

:cl: Ubaser
- add: Chefs now spawn with a spices shaker

### CODE REVIEW

**Comment by TheShuEd** [comment]
Why is this necessary? 
Where "Why / Balance" 🤔

**Comment by UbaserB** [comment]
> Why is this necessary?
> Where "Why / Balance" 🤔

updated

**Comment by UbaserB** [comment]
Im going to add a bit more to this PR so that spices have a proper use in regards to food recipes.

**Comment by UbaserB** [comment]
gonna wait till chef rework

**Pull request closed without merging**
