### PR TITLE
New station map Origin

### PR DESCRIPTION
**Pull request by brainfood1183**
A new station map called Origin

Origin-0

Here are some additional images to show the atmos working, singularity spinning and the ame functioning.

Untitled-38
Untitled-39
Untitled-40
Untitled-41

### CODE REVIEW

**Review by brainfood1183 — COMMENTED** [review]
updated

**Review by brainfood1183 — COMMENTED** [review]
updated again

**Review by brainfood1183 — COMMENTED** [review]
added a new floor decal for this station and the wall map for this station

**Review by moonheart08 — CHANGES_REQUESTED** [review]
- [ ] Most of your hallways are barren and are desperately in need of assorted nooks and crannies due to a lack of landmarks around them. Look at Kettle for ideas here, it does this quite well.
- [ ] There's too much dead space (in the form of actual space) around bridge, making accessing it from maint somewhat difficult. Maybe tie this into the above?
- [ ] A number of external docking locks have lattice in front of them and should either be normal externals, or moved forward so they can actually be used as docks.
- [ ] Maintenance is pretty empty, look at Omega & Bagel for ideas here.
- [ ] There needs to be a lot more public emergency closets. Maybe tie this into the "halls need more decor" point. Also put some just behind maint doors, too.
- [ ] A lot of rooms have maintenance near them but no actual maintenance entrance, Atmos for example. This should be rectified, the majority of rooms should have a maintenance entrance, as it provides a secondary exit to the room should something happen.
- [ ] Command has no disposals
- [ ] Med needs disposals in cloning, surgery, and morgue.
- [ ] Medical viro lobby needs additional decor, it's barren atm.
- [ ] Pass the medbay design by PJB I consider then the medbay expert and am not sure about this one.
- [ ] I don't recall the AI being radioactive, why does it have collectors

**Comment by brainfood1183** [comment]
all these should have now been adressed

**Comment by moonheart08** [comment]
> all these should have now been adressed

Can you update the rendered image for me.

**Comment by moonheart08** [comment]
image
- all of these double-airlocks need put into a single tile, you can stack firelocks on top of doors just fine. (to save on work i'd move the doors, not the firelocks)
- Maint seems too bright
- Your halls have about twice as many lights as they actually need, test them in-game to figure out what you can remove but it should be ~1/2 of them.
- A lot of rooms are also overlit, once again the above advice. Keep in mind there is a **light cap**, and if there's more than 128 lights affecting the visible scene at once (which your overuse can cause), the game's graphics will get a bit fucky.
- Some of maint is still pretty empty feeling. Try making it less cramped, adding more lockers, racks, tables, chairs, debris, air canisters, water tanks, fuel tanks, etc. Also use wall-mounted maintenance lockers if you really need them. Some areas are now good while others are just a pancake stack of empty halls:
image
image

- Some sections of maint should really get built out, long one tile wide halls are not great feeling. For example:
The wrap here:
image
image
- Look at how other maps do decals, often encasing the room in solid decal doesn't look as good as using the alternating edges.
- I don't know how I didn't notice this before but cargo has no maint.

# THE NITPICKS
Everything here is entirely optional to fix.
- The crayon numbers used permanently on the floor should probably be replaced with some new, less hand-drawn looking number decals.
image
- Potted plants are a mysteriously rare sight here when they're pretty great filler.

**Comment by comradef191** [comment]
- You don't seem to be able to... Get anywhere with maint? If we look at Meta as an example, you can stealthily sneak around large swaths of the station using them. Here, there's a few sections of maint separated by normal hallways or locked departments. Making navigation with them tricky.

- Heavy focus on symmetry throughout can make the map feel overly repetitive 

- Advise against needless doublewalls in name of symmetry:
unknown

Echoing most of Moony's points about maint being both barren and far too lit. 
Also agree with the points on Decal usage.

**Comment by brainfood1183** [comment]
> image
> 
>     * all of these double-airlocks need put into a single tile, you can stack firelocks on top of doors just fine. (to save on work i'd move the doors, not the firelocks)
> 
>     * Maint seems too bright
> 
>     * Your halls have about twice as many lights as they actually need, test them in-game to figure out what you can remove but it should be ~1/2 of them.
> 
>     * A lot of rooms are also overlit, once again the above advice. Keep in mind there is a **light cap**, and if there's more than 128 lights affecting the visible scene at once (which your overuse can cause), the game's graphics will get a bit fucky.
> 
>     * Some of maint is still pretty empty feeling. Try making it less cramped, adding more lockers, racks, tables, chairs, debris, air canisters, water tanks, fuel tanks, etc. Also use wall-mounted maintenance lockers if you really need them. Some areas are now good while others are just a pancake stack of empty halls:
>       image
>       image
> 
>     * Some sections of maint should really get built out, long one tile wide halls are not great feeling. For example:
>       The wrap here:
>       image
>       image
> 
>     * Look at how other maps do decals, often encasing the room in solid decal doesn't look as good as using the alternating edges.
> 
>     * I don't know how I didn't notice this before but cargo has no maint.
> 
> 
> # THE NITPICKS
> 
> Everything here is entirely optional to fix.
> 
>     * The crayon numbers used permanently on the floor should probably be replaced with some new, less hand-drawn looking number decals.
>       image
> 
>     * Potted plants are a mysteriously rare sight here when they're pretty great filler.

updated the map with some hopefull fixes to these issues.

**Comment by moonheart08** [comment]
Need to remove Splitstation's files (Resources/Maps/split.yml and Resources/Prototypes/Maps/split.yml) from the game.

**Comment by brainfood1183** [comment]
> Need to remove Splitstation's files (Resources/Maps/split.yml and Resources/Prototypes/Maps/split.yml) from the game in this PR.

ok i will but the map isnt working i dont think

**Pull request merged**
