### PR TITLE
Adds a small amount of space to the chefs hat

### PR DESCRIPTION
**Pull request by UKNOWH**
Now you should be able to put mouse in the chef hat

## About the PR 

**Screenshots**

rat in the hat

**Changelog**

:cl:
- add: You can now put stuff in the chef hat

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This is the kind of content we need.

**Comment by Veritius** [comment]
You might want to append 'Ripmorld' after the CL emoji, as without it, your GitHub username will be displayed.

Also, clearly unfinished PR, no ability for the mouse to control the person smh my head

**Review by ElectroJr — CHANGES_REQUESTED** [review]
The storage size either needs to be smaller, or the hat needs to have a bigger item size so that you can't fit a hat into another hat.

Also while not technically directly related to this PR, mice should have an item size, and should be sized so that only a single mouse can fit inside of the hat.

**Comment by UKNOWH** [comment]
> you can't fit a hat into another hat.

can I try to make a blacklist , would that work?

**Comment by UKNOWH** [comment]
> The storage size either needs to be smaller, or the hat needs to have a bigger item size so that you can't fit a hat into another hat.
> 
> Also while not technically directly related to this PR, mice should have an item size, and should be sized so that only a single mouse can fit inside of the hat.

I have tested it , you can't do that

**Comment by UKNOWH** [comment]
https://user-images.githubusercontent.com/60119809/164148380-6d7623f9-c7cb-4e52-8b66-a6ab61a11ebe.mov

**Comment by UKNOWH** [comment]
> Also while not technically directly related to this PR, mice should have an item size
I can do that in another PR

**Comment by ElectroJr** [comment]
> I have tested it , you can't do that

Ah my bad, it looks like there is already a check to prevent inserting equal or larger storage inside other storage.

**Pull request merged**
