### PR TITLE
Survival boxes can survive explosions

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

Survival boxes and its variants now provide 90% explosive damage reduction to its contents.

## Why / Balance

Survival boxes have an awkward shape (3x3, which is horrible for satchels)
Survival boxes are functionally useless (1:1 storage volume:capacity)
Granting survival boxes explosive damage reduction to contents gives it a functional use besides inventory management and makes for a fun play on words too.

- Hold tear gas grenades without being blinded the moment water and potassium react on top of you
- Hold chemical beakers without " " " " " " " " " " " "

## Technical details

YAML warrior

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Nope

**Changelog**

:cl:
- tweak: Survival boxes are better at surviving explosions

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Should c4 be able to blow up a bottle thats inside the box?

**Comment by Cojoke-dot** [comment]
Wait... I thought those boxes were made of cardboard?

**Comment by WarMechanic** [comment]
> Should c4 be able to blow up a bottle thats inside the box? Was testing this PR, c4 next to a backpack that a survival box with a glass bottle inside. The c4 explosion almost always destroys the bottle.

Maybe? If thats how it is with syndicate duffel bag then so be it (it could also be that the bottle is more fragile).
Putting 4 pipe bombs in a survival box, they will not explode when exposed to another pipe bomb explosion.

**Comment by osjarw** [comment]
Will this change only affect survival boxes, or all that is made of cardboard, like the other cardboard boxes and the cardborg costume?

Also I can already imagine paramedics rummaging through the trash in order to make their bottles explosionproof...

**Comment by Brandon-Huu** [comment]
> Will this change only affect survival boxes, or all that is made of cardboard, like the other cardboard boxes and the cardborg costume?
> 
> Also I can already imagine paramedics rummaging through the trash in order to make their bottles explosionproof...

It doesn't really protect bottles

**Comment by WarMechanic** [comment]
> It doesn't really protect bottles.

in regards to high damage explosions like c4 the 90% damage reduction wont save large beakers or smaller, however it will protect jugs from being detonated. this is probably an overkill scenario i dont really see traitors bombing the chem locker specifically with c4 and it will mostly protect against stray explosions.
if you have the boxes to spare you could probably try to encase as many jugs as possible in a jug but this is probably really pragmatic

the main deal breaker is using the survival box to protect grenades, the moment a security officer blows up it detonates the tear gas that might be in their belt which causes everyone to go blind

**Comment by ps3moira** [comment]
Do explosive protection stack? If so then a 90% explosive resistant with the added benefit of a cardboard box also some how being 90% explosive resistant feels kinda broken. Or at least power creeps nukies to have no way for the bombs they're carrying to go off on them.

**Comment by WarMechanic** [comment]
> Do explosive protection stack? If so then a 90% explosive resistant syndicate bags with the added benefit of a cardboard box also some how being 90% explosive resistant feels kinda broken. Or at least power creeps nukies to have no way for the bombs they're carrying to go off on them.

my guess is probably, although by the time that the explosive resistance comes into effect you'd probably be already dead, also syndicates can get access to alotta explosives so one survival box wont hold 8 c4s.
it only takes one explosive being destroyed for the rest of them being chain detonated, so you cant really do half and half either.

**Comment by baddiePRO** [comment]
if I were to put a c4 block and firebombs/pipebombs in the box together, will the c4 still set off the other bombs?

**Comment by Brandon-Huu** [comment]
> if I were to put a c4 block and firebombs/pipebombs in the box together, will the c4 still set off the other bombs?

yes

**Comment by UbaserB** [comment]
This is sort of weird and inconsistent (practically useless too?)

**Comment by UbaserB** [comment]
It has been discussed internally and the consensus is that it limits antagonist gameplay of an object that already has a clear use; to store emergency supplies. It would be more appropriate to add a specialised item for this purpose instead.

**Pull request closed without merging**
