### PR TITLE
Adds brig access to hop

### LINKED ISSUE #8378: HoP doesn't have brig access
## Description

The HoP, while having access to security, can't enter it due to not having brig access. This has been a problem since brig access was introduced.
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Peptide90**
Fixes #8378
## About the PR 

**Screenshots**

**Changelog**

:cl:
- tweak: HoP now has Brig access instead of Security access.

### CODE REVIEW

**Comment by moonheart08** [comment]
Do we really want to encourage this.

**Comment by Peptide90** [comment]
> Do we really want to encourage this.

Reasoning on the issue, hop have security access anyway so usually I’d say remove that but I guess as “spare captain” they may have reason? however they can just give themselves access anyway. 

Otherwise give them brig so they can go hide in there but remove security since that’s what’s actually used for cells.

**Comment by wrexbe** [comment]
I think adding the brig permission, and taking away the sec access is how you should do this. The lawyer also has brig access. Brig access is really just visiting permissions.

**Comment by Peptide90** [comment]
> I think adding the brig permission, and taking away the sec access is how you should do this. The lawyer also has brig access. Brig access is really just visiting permissions.

Done it this way, no more hopcurity.

**Pull request merged**
