### PR TITLE
Added tags to machine parts and power cells

### PR DESCRIPTION
**Pull request by Vaaankas**
## About the PR 

Added tags to machine parts and power cells, mainly for the purpose of using them in the crafting recipes, with higher tier parts being interchangeable with lower tier requirements.
 
:cl: vanx
- add: Added tags to machine parts and power cells

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Like i said in the other pr, you can just use the power cell component instead of a tag. And i really think that machine parts should either have a unique step or just have a single tag (`Manipulator`) rather than unique tags for each tier.

**Comment by Vaaankas** [comment]
> Like i said in the other pr, you can just use the power cell component instead of a tag. And i really think that machine parts should either have a unique step or just have a single tag (`Manipulator`) rather than unique tags for each tier.

The tag system allows for crafting using parts of a specific tier or higher.

**Comment by EmoGarbage404** [comment]
> The tag system allows for crafting using parts of a specific tier or higher.

I get that, but it isn't consistent with how the parts work with machines. It'd be better to make a unique step and implement a generic "upgradeable" component so that you could just replicate how machines handle higher-tier parts.

**Comment by Vaaankas** [comment]
ok

**Pull request closed without merging**
