### PR TITLE
Body parts can be put in trash bags

### LINKED ISSUE #14034: Human limbs can't be put in a trash bag
Human limbs can't be put in a trash bag.

i am unsure if other types of limbs can be put in a trash bag or even if organs can be put in one

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## Body parts can be put in trash bags

Janitors can now more easily clean up unfortunate accidents.

Resolves #14034

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- add: Body parts can now be put in trash bags. Viscera Cleanup Detail!

### CODE REVIEW

**Review by DrSmugleaf — APPROVED** [review]
This also makes them recyclable, is that intended?

**Comment by QuietlyWhisper** [comment]
I thought that was reliant on the recyclable tag/component, with an included tag for what material it drops?

**Comment by DrSmugleaf** [comment]
> I thought that was reliant on the recyclable tag/component, with an included tag for what material it drops?

https://github.com/space-wizards/space-station-14/blob/5b0e760d7740cd8cba0b76010240f06fabeacc8f/Content.Server/Recycling/RecyclerSystem.cs#L134

**Comment by QuietlyWhisper** [comment]
Mmmm... I'll see what this results in through dev enviro test, if it simply shreds body parts, I suppose thats not bad anyways? It could even make biomass if that's a wanted feature.. at a much lower return, anyways.

**Comment by QuietlyWhisper** [comment]
> This also makes them recyclable, is that intended?

Tested on dev enviro, if you meant the recycler machine, there is no interaction between them currently. It probably requires the other tag along with a material.

**Comment by QuietlyWhisper** [comment]
This should be ready to merge.

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
