### PR TITLE
Updates to the QM cloak.

### PR DESCRIPTION
**Pull request by Sarahon**
## About the PR
The QM cloak was inconsistent and looked as if it was saved in a jpeg format. So I decided to clean up the sprite, using the original colours and taking direction from the sprite team on discord. 

## Why / Balance
I would just like it to look more consistent and have an improved palette.

## Media
Aseprite_P5L2cum7LN
QM update

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by beck-thompson** [comment]
Wow I didn't realize the old one looked so bad.... The new sprite is much better 👍

**Comment by baddiePRO** [comment]
QM speeen

**Review by UbaserB — CHANGES_REQUESTED** [review]
The yellow stripes need to be less bright (or like less off-color to the rest of the outfit) alongside less depth (right now it looks like it's patched on-top instead of being part of the markings).

Edit: The shading on the back is also a bit weird, the crease in the middle that is added shouldn't be there and altogether should have softer, more "rounded" (in a 3D sense i guess?) shading. Sort of hard to explain but the original cloak was better in that regard.

**Comment by Sarahon** [comment]
> The yellow stripes need to be less bright (or like less off-color to the rest of the outfit) alongside less depth (right now it looks like it's patched on-top instead of being part of the markings).
> 
> Edit: The shading on the back is also a bit weird, the crease in the middle that is added shouldn't be there and altogether should have softer, more "rounded" (in a 3D sense i guess?) shading. Sort of hard to explain but the original cloak was better in that regard.

tbf, I just kinda tried to emulate the original. It wasn't clear at all to me that the weird side parts were meant to show a "curve" when there's light bumps in the middle. So I assumed it's meant to be like a shoulder blade/arm parts showing behind. I can change it though.

**Comment by UbaserB** [comment]
You coming back to this?

**Comment by UbaserB** [comment]
Closing this PR for two reasons. Firstly it is derelict, but also after discussion and a maintainer vote we've decided that this PR misses the point of the hi viz stripe on the sprite and the sides have odd shading. A lot of detail in the sprite was removed with your changes overall and altogether we've decided that even if the cloak could use work this is not the right direction.

**Pull request closed without merging**
