### PR TITLE
Reduce rusty wall occurrences

### PR DESCRIPTION
**Pull request by metalgearsloth**
Every station looks like barratry as there's so many rusty walls onscreen everywhere.

### CODE REVIEW

**Comment by mirrorcult** [comment]
it looks good though

**Comment by Hmeister-real** [comment]
It gives engis a job, also an excuse to enter departments to weld it. Also looks good. please no

**Comment by UbaserB** [comment]
I was thinking it was a tad bit excessive

**Comment by metalgearsloth** [comment]
image

It just looks obnoxiously common to me when the entire station looks like this and will never be repaired.

**Comment by Simyon264** [comment]
One thing I also noticed: The rusty walls also replace Shuttle walls, making shuttles look like a mess.

**Comment by EmoGarbage404** [comment]
I'm fine with this for the following reasons:
- the uniformly applied rust tends to make areas that should be in good condition look ruined to an out-of-place degree
- the rusted walls, while fixable, don't really have enough mechanical incentive to do so to make me feel like the reduction is beneficial
- it is kinda ugly

**Pull request merged**
