### PR TITLE
C-SAR added to uplinks.

### PR DESCRIPTION
**Pull request by c0rigin**
## About the PR

Added the C-SAR to uplinks for 23 tc.
6 rpm, using 30 round magazines of .25 caseless, decently accurate in 3 round bursts.
A burst fire rifle with caseless ammunition (now where have I heard that totally original specification before...)

## Why / Balance

It provides the holder some accurate long range damage, if they are patient enough to use the bursts and wait for spread to reset. Should help alleviate the "spam lasers down a hallway and pray" strategy that some crewmates are so fond of.

## Technical details

No.
## Media

image

**Showcase video**:
https://streamable.com/re1z32

## Breaking changes

No.

**Changelog**

:cl:
- add: Added the C-SAR burst rifle to uplinks for 23 tc.

### CODE REVIEW

**Comment by CatMagic1** [comment]
Looks kinda bad and also gun freeze

**Comment by c0rigin** [comment]
i know, this is my first pr, and also i'm a shitty artist

**Comment by LankLTE** [comment]
Thank you for the contribution, but as said above, new guns are currently frozen (see #8524 for a list of current freezes). 
I also don't feel this gun really has a niche in the uplink. The C20 already serves the purpose of an affordable fully-automatic weapon, and being caseless isn't particularly useful for a weapon like this, while also making ammo impossible to find on-station with no extra magazines available to purchase like the C20.

**Comment by c0rigin** [comment]
Ah, sorry, I forgot about the freeze.

**Pull request closed without merging**
