### PR TITLE
Todd lobby themes

### PR DESCRIPTION
**Pull request by WTCWR68**
## About the PR 

**Changelog**

:cl: Todd
add: added 3 new lobby themes.

### CODE REVIEW

**Review by Peptide90 — APPROVED** [review]
lgtm

**Comment by Fishfish458** [comment]
Was skeptical about Comet Halley but it does come up in free music archive under creative commons, never knew.

**Comment by Peptide90** [comment]
> Was skeptical about Comet Halley but it does come up in free music archive under creative commons, never knew.

Definitely the best of the three but I don't recognise any so.

**Review by moonheart08 — APPROVED** [review]
fuck yes title3

**Pull request merged**
