### PR TITLE
Omega Station 

### PR DESCRIPTION
**Pull request by Emisse**
This will phase Atlas out of rotation and replace it with Omega. Atlas was mainly just a test to put in a goon map and see how it played. Omega Station is a low pop map with a squarish shape. It was made by Okand37, the creator of delta station. It is currently defunct in ss13 but a couple servers still maintain their own versions of it. I used several versions of this map for inspiration and also redid some departments from scratch, like med, sci, and engi. It has a north side bridge and a center service area. It has a maximum of 35 players. The bulk of the station occupies about a 100x100 space. It is similar size to moose and saltern.  Thank you for reading. There are no guns of any sort mapped currently so it does not conflict with the ongoing gun refactor.

here is an ms paint render:
image

some candid photos since i cannot render:
image
image
image
image
image
image
image
image
image
image
to all coders. yes power on omega starts instantly in arrivals. no i dont know why it doesnt on some othermaps

### CODE REVIEW

**Comment by Froozigiusz** [comment]
> This will phase Atlas out of rotation

It's sad to see Atlas go away, I liked it. Also in [Progress Report #34](https://spacestation14.io/post/22-05-25-progress-report-34/) (the newest as of right now) It's mentioned being added, so it's a small amount of time to see it go away.

**Comment by Emisse** [comment]
atlas has some problems that i need to figure out so id rather spend the time maintaining other maps and putting it on the backburner for now. needless to say i dont plan on having it gone forever

**Comment by moonheart08** [comment]
omega-0

**Comment by Emisse** [comment]
thanks moony, sad to see decals no worky on it

**Comment by Emisse** [comment]
this is giving me conflicts and is annoying so im just remaking

**Pull request closed without merging**
