### PR TITLE
Reworks the Python to match the SS13 .357

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
While the Python was already "good," nobody used it because it didn't feel good to use & was basically just a slightly better version of the pistols. A long-time complaint I've seen is that all of the traitor guns are painfully mediocre, so this should hopefully do something to curb that.
This PR adds .357 ammo that does 54 damage per shot - used on the Python and Mateba. The python itself has also recieved an increased firerate, but is now much louder and _much_ more expensive in the uplink.

Capguns also match the Python a little better now since that's what they're meant to do.
Also changed some uplink gun descriptions to describe things slightly better - the viper is no longer listed as "underpowered" but the cobra is.

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The Syndicate has supplied traitors with a much newer, much scarier model of the Python chambered in classic .357.
- tweak: The Mateba now fires faster and uses .357.

### CODE REVIEW

**Comment by LankLTE** [comment]
mfw the revolver does more damage than the hristov

**Comment by asperger-sind** [comment]
the big iron on his hip

**Comment by keronshb** [comment]
Ill review this weekend.

**Comment by keronshb** [comment]
@Flareguy fix tests and I'll review today

**Comment by Flareguy** [comment]
> @Flareguy fix tests and I'll review today

I think the test fails are erroneous?

**Comment by keronshb** [comment]
> > @Flareguy fix tests and I'll review today
> 
> I think the test fails are erroneous?

If you merge master into the branch the tests should be fixed.

**Comment by Emisse** [comment]
I approve this buff, although I do miss the predator

**Comment by metalgearsloth** [comment]
Unique ammo types are cringe

**Pull request merged**
