### PR TITLE
Pirate Ship 

### PR DESCRIPTION
**Pull request by Emisse**
A stolen SolGov vault craft crewed by ruthless pirates looking to plunder any space stations in the nearby sectors. Inspired by the beestation pirate shuttle, this pirate shuttle is intended for use in admemes or whenever someone wants to code pirate midrounds. Pirates will need to spawn with magboots as this does not have grav. Only spawner I've placed on it for now is a captain spawner so that it's spawnable. argh
image

### CODE REVIEW

**Comment by mirrorcult** [comment]
that is probably too many guns

**Comment by Emisse** [comment]
it can be changed more when we're closer to pirates actually being in

**Comment by mirrorcult** [comment]
yeah fair

**Comment by metalgearsloth** [comment]
That is a lot of thrusters

**Comment by Emisse** [comment]
beeg ship

**Comment by CrudeWax** [comment]
can you replace the walls, and floors with wooden ones so it feels like scrappy space pirates

**Comment by moonheart08** [comment]
> can you replace the walls, and floors with wooden ones so it feels like scrappy space pirates

Ehhh I think this looks better as-is.

**Comment by ScalyChimp** [comment]
Could you maybe add some muskets/flintlocks? That's what they're in for. Maybe get rid of the lasers, they seem pretty technologically advanced for pirates.

**Pull request closed without merging**
