### PR TITLE
Wheelchair fixes

### LINKED ISSUE #18848: Wheelchairs need fixing
- Sprite netsync needs removing we just purged them all.
- Don't Ensure on comp init.
- Don't RemComp in a component's startup eventbus.
- WheelChairBound should be MapInit not startup.

Also the localisation needs fixing.

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR

Closes #18848

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Morb0** [comment]
System.InvalidOperationException : Released on different thread than took lock???

**Comment by QuietlyWhisper** [comment]
Will this also fix #18874? We can close that one as well if so, and reenable the wheelchair trait!

**Comment by Morb0** [comment]
> Will this also fix #18874? We can close that one as well if so, and reenable the wheelchair trait!

Nope, only minors fixes. Vehicles stun immune are more global.

**Comment by NancokPS2** [comment]
> Will this also fix #18874? We can close that one as well if so, and reenable the wheelchair trait!

Do you mean the bug that this one fixes? #18962

**Pull request merged**
