### PR TITLE
Fixes instant ramen

### LINKED ISSUE #10060: Misleading description or missing feature on instant ramen
Apparently the instant ramen is supposed to have a reaction when coming into contact with water. I'm guessing someone just forgot to add a reaction to turn 3 dry ramen and 1 water into hot ramen, as hot ramen already exists in the drinks prototype beneath the dry ramen one.

Screenshot_20220726_160237

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Fixes #10060 
**Screenshots**

**Changelog**

:cl:
- fix: Instant ramen now works with cold water.

### CODE REVIEW

**Comment by moonheart08** [comment]
Just use a microwave. Seriously.

**Comment by mirrorcult** [comment]
or just fix the description

**Comment by Emisse** [comment]
1984

**Comment by Peptide90** [comment]
> Just use a microwave. Seriously.

Pick your damn fix, seriously.

**Pull request closed without merging**
