### PR TITLE
Add AKMS into t-uplink

### PR DESCRIPTION
**Pull request by EEASAS**
## About the PR

Added the AKMS into traitor uplink.
Also renames the "NT" in the uplink to "SYN"
**IMPORTANT!! please help me fix the description in the uplink this is HELL HOLY SHIT**
also it cost 12tc

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The Syndicate has supplied their traitors and nuclear operatives with a rifle, the AKMS.

### CODE REVIEW

**Comment by deltanedas** [comment]
i think its ok for 12 tc, unrobust tider's version of buying a fireaxe and raiding armoury

**Comment by crazybrain23** [comment]
> Also renames the "NT" in the uplink to "SYN"

This probably won't be merged until this is two separate PRs.

**Comment by deltanedas** [comment]
the NT (2125 - 2^15) or something bit is 2 part:
- implies uplink was nanotrasen tech
- implies its hacked since 2^15 le hacker number

**Comment by Myakot** [comment]
This + 1TC ammo packs of 150 bullets each.

**Pull request merged**
