### PR TITLE
Adds teshari species

### PR DESCRIPTION
**Pull request by metalgearsloth**
* Cleaned up some species code to share more datafields (to be re-done because merging in constantly is gonna be a pain and will need cleaning up at the end).
* Long-term goal is to replace dwarves because this actually makes use of markings and is better for debugging different size species.
* Needs mechanics implemented before making roundstart.

:cl:
- add: Adds Teshari to species, admin only for the moment.

### CODE REVIEW

**Comment by Verbalase** [comment]
What even happened to this?

**Comment by mirrorcult** [comment]
it wasnt added?

**Comment by UbaserB** [comment]
ahhhhh i want this so much though

**Comment by Verbalase** [comment]
> it wasnt added?

as in why exactly

**Comment by mirrorcult** [comment]
feel free to copy the branch and make a PR yourself if you want to push for it to be ingame

**Pull request closed without merging**
