### PR TITLE
Added leg shackles

### PR DESCRIPTION
**Pull request by chavonadelal**
## About the PR

Adding leg shackles for security.
## Why / Balance

- I think this thing suggests itself. The game implements almost all types of restrictions on freedom and this is the most obvious of the unrealized ones. Slows down by 50%, cannot be removed without assistance, is put on another and removed from another with an additional delay of 10. There is also a 5-second delay for putting on yourself so that you don't accidentally fall into a trap. 

- Leg shackles have been added to the prison box and as a default recipe available in the security techfab. I was thinking of making this an investigational recipe in the newly added new technology at the first level in the arsenal branch "Special Means", but I'm not sure if it's needed, so that's it.

- I don't draw well, I hope you like the sprite. And if not, then please help me with it, I can't draw any better.. 😕 

See also in this category #31095 
## Media

https://github.com/user-attachments/assets/ca1bba36-20a6-48ac-a982-b2e3febcd77e

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: to4no_fix
- add: Added leg shackles
- add: Leg shackles added to prison wardrobe
- add: A recipe for the production of leg shackles added to the security techfab

### CODE REVIEW

**Comment by ps3moira** [comment]
Should probably require brig access and or use an emag to remove it

**Comment by chavonadelal** [comment]
> Should probably require brig access and or use an emag to remove it

It's just a huge metal shackles, no technology, just a lock that can't be broken without help or something. Right now I'm not sure if it's necessary.

**Comment by SlamBamActionman** [comment]
Isn't this functionally the same as throwing a bola on someone who is handcuffed?

**Comment by chavonadelal** [comment]
> Isn't this functionally the same as throwing a bola on someone who is handcuffed?

It's not the same, because a person can free themselves and take it off, but a collar cannot be taken off by oneself at all.

**Comment by SlamBamActionman** [comment]
> > Isn't this functionally the same as throwing a bola on someone who is handcuffed?
> 
> It's not the same, because a person can free themselves and take it off, but a collar cannot be taken off by oneself at all.

Functionally I think it won't result in much of a difference. Here's my thinking:

If you have arrested someone and put them in a cell/perma, they should not have any restriction of movement because that's unfun gameplay for the arrested (which is why we have rules against leaving people cuffed in their cells). 

If we instead look at transporting someone who you have just arrested, or transporting someone from their cell to somewhere... They will already be in handcuffs, so attaching a bola to them means they won't be able to remove it without first removing the handcuffs. And if they have managed to remove the handcuffs somehow then something has happened that has allowed them to escape Security.

The main difference between bola and shackles becomes the self-removal after having escaped from Security. I think it's very punishing to go through the effort to escape only to have to walk around at 50% speed with a visible "I am a confirmed escaped convinct" item, trying to find another antag who can remove them for you.

**Comment by chavonadelal** [comment]
> > > Isn't this functionally the same as throwing a bola on someone who is handcuffed?
> > 
> > It's not the same, because a person can free themselves and take it off, but a collar cannot be taken off by oneself at all.
> 
> Functionally I think it won't result in much of a difference. Here's my thinking:
> 
> If you have arrested someone and put them in a cell/perma, they should not have any restriction of movement because that's unfun gameplay for the arrested (which is why we have rules against leaving people cuffed in their cells). 
> 
> If we instead look at transporting someone who you have just arrested, or transporting someone from their cell to somewhere... They will already be in handcuffs, so attaching a bola to them means they won't be able to remove it without first removing the handcuffs. And if they have managed to remove the handcuffs somehow then something has happened that has allowed them to escape Security.
> 
> The main difference between bola and shackles becomes the self-removal after having escaped from Security. I think it's very punishing to go through the effort to escape only to have to walk around at 50% speed with a visible "I am a confirmed escaped convinct" item, trying to find another antag who can remove them for you. 

This is necessary for inadequate and especially dangerous prisoners, especially since emo has already approved of this and would be happy with this idea himself.

**Comment by chavonadelal** [comment]
No one is going to hang this on everyone. There must be a good reason for this, like any special means

**Comment by Emisse** [comment]
after the shock collar i am in doubt of the community for things like this

**Comment by chavonadelal** [comment]
> after the shock collar i am in doubt of the community for things like this

I don't see a problem, it's like with weapons, for example. You just shouldn't abuse them.

**Comment by chavonadelal** [comment]
@Emisse If you are confused by the availability of shackles, I can - move this to the Special Means technology so that it is necessary to research it first before getting the shackles.

**Comment by foob1** [comment]
Do we really need more things that make it impossible for prisoners to escape by themselves? Its already hard enough...

**Comment by chavonadelal** [comment]
> Do we really need more things that make it impossible for prisoners to escape by themselves? Its already hard enough...

A prison cell is not a children's camp, especially since this is not something that everyone is supposed to wear (like putting a muzzle on). I plan to move this around and make it researchable, but would like some feedback first.

**Comment by foob1** [comment]
> 
> A prison cell is not a children's camp, especially since this is not something that everyone is supposed to wear (like putting a muzzle on). I plan to move this around and make it researchable, but would like some feedback first.

Pretty sure it's just gonna be abused by sec to put on every perma prisoner so it's impossible for them to escape solo. I don't think we should add a feature that makes it impossible for prisoners to escape solo, escape by yourself from the brig is already hard enough. Perhaps there should be some way to be able to remove it by yourself.

**Comment by foob1** [comment]
> 
> There is already the main restriction - you can't leave a group of prisoners with this, because they can remove each other's leg shackles. Well, as for some kind of difficulty - the antagonists are already doing whatever they want at the station, they are legitimately causing utter chaos. But once you get caught - there is a problem with the skill, and you still have a chance to escape.

Maybe make it so you can remove it by yourself with a screwdriver? So even if you do manage to escape solo, it won't be impossible for you to survive out in the station without help from others.

**Comment by Savsj** [comment]
We just got rid of shock collars because people couldnt behave, i have a feeling this is gonma be just as bad because sec is just gonna leave people fully chained up, gagged and shoved in a closet, if some one is ALREADY in perma why are we taking steps to encourage them to just bite their tongue? There is no world in which sec we have will not abuse this maliciously to make everyone else have less fun.

**Comment by chavonadelal** [comment]
> We just got rid of shock collars because people couldnt behave, i have a feeling this is gonma be just as bad because sec is just gonna leave people fully chained up, gagged and shoved in a closet, if some one is ALREADY in perma why are we taking steps to encourage them to just bite their tongue? There is no world in which sec we have will not abuse this maliciously to make everyone else have less fun. 

The collar was cut from the game because idiots acted weird while wearing it (ERP)

**Comment by Savsj** [comment]
> > We just got rid of shock collars because people couldnt behave, i have a feeling this is gonma be just as bad because sec is just gonna leave people fully chained up, gagged and shoved in a closet, if some one is ALREADY in perma why are we taking steps to encourage them to just bite their tongue? There is no world in which sec we have will not abuse this maliciously to make everyone else have less fun.
> 
> The collar was cut from the game because idiots acted weird while wearing it (ERP)

Insert the picture of the guy just staring into your soul. Also you didnt answer the question of, fundamentally, why should we make other peoples lives worse? They already got caught, 95/100 times they are not escaping perma even WITH help. So precisely what is the use case for this? Other than some cruel bloat?

**Comment by chavonadelal** [comment]
> > > We just got rid of shock collars because people couldnt behave, i have a feeling this is gonma be just as bad because sec is just gonna leave people fully chained up, gagged and shoved in a closet, if some one is ALREADY in perma why are we taking steps to encourage them to just bite their tongue? There is no world in which sec we have will not abuse this maliciously to make everyone else have less fun.
> > 
> > The collar was cut from the game because idiots acted weird while wearing it (ERP)
> 
> Insert the picture of the guy just staring into your soul. Also you didnt answer the question of, fundamentally, why should we make other peoples lives worse? They already got caught, 95/100 times they are not escaping perma even WITH help. So precisely what is the use case for this? Other than some cruel bloat?

For the same reason why there is a muzzle and an electric backpack. Restriction for especially dangerous and inadequate prisoners

**Comment by chavonadelal** [comment]
> > > > We just got rid of shock collars because people couldnt behave, i have a feeling this is gonma be just as bad because sec is just gonna leave people fully chained up, gagged and shoved in a closet, if some one is ALREADY in perma why are we taking steps to encourage them to just bite their tongue? There is no world in which sec we have will not abuse this maliciously to make everyone else have less fun.
> > > 
> > > The collar was cut from the game because idiots acted weird while wearing it (ERP)
> > 
> > Insert the picture of the guy just staring into your soul. Also you didnt answer the question of, fundamentally, why should we make other peoples lives worse? They already got caught, 95/100 times they are not escaping perma even WITH help. So precisely what is the use case for this? Other than some cruel bloat?
> 
> For the same reason why there is a muzzle and an electric backpack or an eye patch. Restriction for especially dangerous and inadequate prisoners

**Comment by chavonadelal** [comment]
Also, don't forget about the eye patch.

**Comment by slarticodefast** [comment]
I brought this up for maintainer discussion and the general agreement was that this should not be added. The main points brought up in the discussion were:
- According to space law prisoners must be granted freedom of movement, so the only way this could be used legally is for prisoner transport.
- We want to give antagonists a chance to break out for balancing reasons. Making it almost impossible is simply not fun for anyone from a gameplay perspective.
- 50% slowdown is an extreme debuff. If you also wear a dufflebag or hardsuit you can barely move at all. Even 20% slowdown would have a significant effect on combat.
- Since it can easily mass-produced and has no downside it encourages sec to simply use it for every single prisoner.

As such I will be closing this PR. Thank you for your contribution.

**Pull request closed without merging**
