### PR TITLE
Add ultrakill coin (april fool)

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

adds ultrakill coin

- reflects bullets to nearest not-you target
- only works when thrown
- gets destroyed when it reflects anything

## Why / Balance

funni

game balance go die

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added ultrakill coin that reflects bullets to the nearest target when thrown. Make with 1 steel. Go ham.

### CODE REVIEW

**Comment by Killerqu00** [comment]
is original coin sound copyrighted?

**Comment by notquitehadouken** [comment]
> is original coin sound copyrighted?

it doesn't make a sound

**Comment by notquitehadouken** [comment]
no media but it works

**Comment by notquitehadouken** [comment]
no

**Pull request closed without merging**
