### PR TITLE
Adds atmospherics access to the fire fighting door remote. Feels like…

### PR DESCRIPTION
**Pull request by Plykiya**
… an oversight for the atmos door remote to not have atmos access.

## About the PR

Added atmospherics access to the fire fighting door remote.

## Why / Balance

Because it feels like an oversight for the door remote that only atmos has access to, to not have access to atmos. Every other door remote is essentially made to mimic the holder's starting access, so it feels fitting for the atmos door remote to have atmos access. Plus, having additional access to distro or freezers is helpful during "firefighting" efforts by non-atmos and adds another target for antags to try and steal.

## Technical details

I added the Atmospherics tag to the engineering.yml access file for the firefighting door remote.

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes.

**Changelog**

:cl:
- tweak: The firefighting door remote now has access to atmos doors.

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
I think in some maps its available to engineers.

**Comment by PoorMansDreams** [comment]
> Is it not available to engineers?

only atmos gets access to the firedoor remotes
engi get insuls and magboots

**Comment by LankLTE** [comment]
This feels unnecessary? The other door remotes have the holders' access because they're for that department, but the firefighting door remote is just that, for firefighting.

**Comment by deltanedas** [comment]
firefighting remote is in atmos lockers only, they are for the atmospherics department

**Comment by Plykiya** [comment]
> This feels unnecessary? The other door remotes have the holders' access because they're for that department, but the firefighting door remote is just that, for firefighting.

Firefighting gear is featured inside atmos. For example, atmos has both a hardsuit and a firefighting suit. Giving the fire remote atmos access allows the user to open the atmos locker to retrieve the proper atmos firefighting suit, and better equip whoever it is to fight fires.

**Pull request merged**
