### PR TITLE
egg rework

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- made raw egg turn into uncooked protein when eaten
- raw egg can be heated to become cooked egg which becomes cooked protein when eaten
- eggs can be heated in a plasma fire / on a grill / in a microwave to boil then and eventually explode if the internal pressure is too high (conductivity of eggshell has a cited paper)

frying pan and egg frying when :trollface:

## Why / Balance
eating raw egg can make you puke :trollface:
cooking egg now makes it twice as yummy as before
eggs eggs eggs eggs eggs

## Technical details
added `DamageEntity` construction completion thing for egg to explode

## Media
raw egg

egg cooked in a hotplate

egg boiling and exploding also work trust

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Raw eggs are no longer safe to eat, you have to make a dish or boil them first.

### CODE REVIEW

**Comment by UbaserB** [comment]
What about for uncracked eggs?

**Comment by deltanedas** [comment]
they have raw egg

**Comment by brainfood1183** [comment]
can we have an eggoverlay (like for creampie but for throwing eggs at the hop)

**Comment by dvir001** [comment]
image

**Comment by deltanedas** [comment]
kid named unstable mutagen

**Comment by Emisse** [comment]
I didnt know there was an explode node on construction graph

**Comment by deltanedas** [comment]
yes i made it

**Pull request merged**
