### PR TITLE
Nerfs normal nettles to be weaker than their deathnettle counterparts

### PR DESCRIPTION
**Pull request by EdenTheLiznerd**
## About the PR

Normal nettles have had their reagent hold amount drastically reduced, if the deathnettle is to be an upgrade than the nettle should be lower in capabilities than the deathnettle, it shouldn't be reliable when it's a normal plant

## Why / Balance

This was set to balance due to the normal nettle having more capabilities than it's stronger brother, a normal nettle shouldn't be capable of holding 25 whole u's of amatoxin, it has been reduced to 3

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
 :cl:
- tweak: Nettles are now weaker than their deathnettle counterparts

### CODE REVIEW

**Comment by thebadman4662** [comment]
Why the histamine nerf though?

**Comment by EdenTheLiznerd** [comment]
> Why the histamine nerf though?

It nerfs the amount of reagent entirely, I can't make it hold more than it's reagent limit

**Comment by Anzarot121** [comment]
1. And tsk, you nerfed the death nettle into the trash right according to the precepts of the TG coders and now you want to do the same with the usual one. Why do you hate botanists?

**Comment by EdenTheLiznerd** [comment]
I would rather you remain civil on my PR, botany shouldn't have access to plants capable of taking down a fully grown man in 2 hits, this mitigates that, it's a fair change in accordance with the current deathnettles

**Comment by mehx3** [comment]
Changing amount of histamine doesn't change maximum amount of amatoxin that you can cross-pollinate into a nettle. You just made getting histamine a lot harder. Also i don't see any reason to change injection amount, because it can't even penetrate hardsuits. Poor flukies are safe since deathnettle is nerfed. Normal nettle can be used as a ghetto single-use hypospray that injects 6 units, while deathnettle can deal 17 damage that is hard to heal and inject couple units of amatoxin/lexorin. Overall it's really sad that unique mechanic has to be changed because there's no chem inside uplink to counter caustic/amatoxin specifically. Fells like backwards balancing

**Comment by EdenTheLiznerd** [comment]
You may blame people for abusing deathnettles and nettles entirely to validhunt and ppwergame, until a proper botany system is in place deathnettles will always ruin the balance

**Comment by Holinka4ever** [comment]
> I would rather you remain civil on my PR, botany shouldn't have access to plants capable of taking down a fully grown man in 2 hits, this mitigates that, it's a fair change in accordance with the current deathnettles

In opinion, its actually okay due that deathnettles or simple nettles become too popular and being overkill weapon.

But its it too harsh to nerf it like that?
Someone told that problem that it become too popular and every crewmate have own deathnettle for joy and suffering. If problem were around that "everyone using it", so what about to cut ability to public use, instead of doing this significant nerfs?

In that pr of nerfing deathnettles, people told that implementing system were you cant use deathnettles without botanists gloves, cause they gonna inject their stuff into you. Yo.

**Comment by mehx3** [comment]
If you find deathnettle specifically to "ruin the balance", why do you change normal nettle? Amatoxin nettle is only useful against single target and takes time to deal damage. It's been around forever and never been a problem. If nuikes well being is your main concern then just remove ability to penetrate armor

**Comment by EdenTheLiznerd** [comment]
You may blame people for abusing deathnettles and nettles entirely to validhunt and ppwergame, until a proper botany system is in place deathnettles will always ruin the balance

I will wait for someone else to code a system like that, even then, botany still shouldn't have weapons that rival literal guns and spears etc etc, 

Someone else is gladly invited to go code that system, I'm just preventing botany from validhunting and powergaming, I will close or revert the PR if someone makes that change but I am sticking with this currently

**Comment by EdenTheLiznerd** [comment]
Holy fuck my GitHub is dying

**Comment by EdenTheLiznerd** [comment]
> If you find deathnettle specifically to "ruin the balance", why do you change normal nettle? Amatoxin nettle is only useful against single target and takes time to deal damage. It's been around forever and never been a problem. If nuikes well being is your main concern then just remove ability to penetrate armor 

It's more of a balancing issue of it being stronger than the deathnettle

**Comment by mehx3** [comment]
> > If you find deathnettle specifically to "ruin the balance", why do you change normal nettle? Amatoxin nettle is only useful against single target and takes time to deal damage. It's been around forever and never been a problem. If nuikes well being is your main concern then just remove ability to penetrate armor
> 
> It's more of a balancing issue of it being stronger than the deathnettle

Maybe removing the ability to pen armor was just enough then? There's no reason to inject 2/3 units of anything, just another gutted mechanic

**Comment by EdenTheLiznerd** [comment]
> > > If you find deathnettle specifically to "ruin the balance", why do you change normal nettle? Amatoxin nettle is only useful against single target and takes time to deal damage. It's been around forever and never been a problem. If nuikes well being is your main concern then just remove ability to penetrate armor
> > 
> > It's more of a balancing issue of it being stronger than the deathnettle
> 
> Maybe removing the ability to pen armor was just enough then? There's no reason to inject 2/3 units of anything, just another gutted mechanic

Again, if people didn't validhunt or powergame it would not be an issue but it's an issue now that needs fixing.

**Comment by deltanedas** [comment]
whats the point of it if not to validhunt? what else are you going to do with your amatoxin nettles? give them to sec?

**Comment by EdenTheLiznerd** [comment]
> whats the point of it if not to validhunt? what else are you going to do with your amatoxin nettles? give them to sec?

Well validhunting is against the rules so... Not sure what you wanna do about that one, I'm no longer going to be discussing the past PR on deathnettles, this PR's purpose is to make nettles weaker than their deathnettle counterparts

**Comment by EdenTheLiznerd** [comment]
> as  in whats the point of having nettles at all if not for stinging people/mobs with them

They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin

**Comment by mehx3** [comment]
> > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> 
> They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin

You already deleted the ability to do anything to nukies as a botanist

**Comment by EdenTheLiznerd** [comment]
> > > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> > 
> > They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin
> 
> You already deleted the ability to do anything to nukies as a botanist

If you could bring actual criticism that'd be grand

**Comment by mehx3** [comment]
> > > > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> > > 
> > > 
> > > They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin
> > 
> > 
> > You already deleted the ability to do anything to nukies as a botanist
> 
> If you could bring actual criticism that'd be grand

You reason to nerf nettle is "to be worse than deathnettle". My criticism is you didn't thoroughly thought out deathnettle nerf and now you want to take away whole mechanic because of it. You reason to change normal nettle is invalid

**Comment by EdenTheLiznerd** [comment]
> > > > > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> > > > 
> > > > 
> > > > They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin
> > > 
> > > 
> > > You already deleted the ability to do anything to nukies as a botanist
> > 
> > If you could bring actual criticism that'd be grand
> 
> You reason to nerf nettle is "to be worse than deathnettle". My criticism is you didn't thoroughly thought out deathnettle nerf and now you want to take away whole mechanic because of it. You reason to change normal nettle is invalid

It was thought out, normal nettles are a minor oversight now being accounted for, I'm not taking away the mechanic that's just a blatant overreaction, the mechanic has been whittled down cause it's unfair and unfun

**Comment by mehx3** [comment]
> > > > > > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> > > > > 
> > > > > 
> > > > > They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin
> > > > 
> > > > 
> > > > You already deleted the ability to do anything to nukies as a botanist
> > > 
> > > 
> > > If you could bring actual criticism that'd be grand
> > 
> > 
> > You reason to nerf nettle is "to be worse than deathnettle". My criticism is you didn't thoroughly thought out deathnettle nerf and now you want to take away whole mechanic because of it. You reason to change normal nettle is invalid
> 
> It was thought out, normal nettles are a minor oversight now being accounted for, I'm not taking away the mechanic that's just a blatant overreaction, the mechanic has been whittled down cause it's unfair and unfun

In most cases you don't have "clean" nettle. It takes time and rng to get. Before your nerf i could get lexorin/pax/any funny reagent from random chemical mutation and still use without having to cross-pollinate nettle with woodcaps to clean all other reagents because nettle injected 6 units. Now that ability has been removed. How is that an overreaction?

**Comment by EdenTheLiznerd** [comment]
> > > > > > > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> > > > > > 
> > > > > > 
> > > > > > They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin
> > > > > 
> > > > > 
> > > > > You already deleted the ability to do anything to nukies as a botanist
> > > > 
> > > > 
> > > > If you could bring actual criticism that'd be grand
> > > 
> > > 
> > > You reason to nerf nettle is "to be worse than deathnettle". My criticism is you didn't thoroughly thought out deathnettle nerf and now you want to take away whole mechanic because of it. You reason to change normal nettle is invalid
> > 
> > It was thought out, normal nettles are a minor oversight now being accounted for, I'm not taking away the mechanic that's just a blatant overreaction, the mechanic has been whittled down cause it's unfair and unfun
> 
> In most cases you don't have "clean" nettle. It takes time and rng to get. Before your nerf i could get lexorin/pax/any funny reagent from random chemical mutation and still use without having to cross-pollinate nettle with woodcaps to clean all other reagents because nettle injected 6 units. Now that ability has been removed. How is that an overreaction?

And yet it's still being constantly abused, I will wait for a mantainer to offer their input and go from there

**Comment by mehx3** [comment]
> > > > > > > > as  in whats the point of having nettles at all if not for stinging people/mobs with them
> > > > > > > 
> > > > > > > 
> > > > > > > They can still do it, they just aren't two tapping anymore, stops people from just walking up to nukies and crottong them in 15 seconds cause their entire bloodstream is amatoxin
> > > > > > 
> > > > > > 
> > > > > > You already deleted the ability to do anything to nukies as a botanist
> > > > > 
> > > > > 
> > > > > If you could bring actual criticism that'd be grand
> > > > 
> > > > 
> > > > You reason to nerf nettle is "to be worse than deathnettle". My criticism is you didn't thoroughly thought out deathnettle nerf and now you want to take away whole mechanic because of it. You reason to change normal nettle is invalid
> > > 
> > > 
> > > It was thought out, normal nettles are a minor oversight now being accounted for, I'm not taking away the mechanic that's just a blatant overreaction, the mechanic has been whittled down cause it's unfair and unfun
> > 
> > 
> > In most cases you don't have "clean" nettle. It takes time and rng to get. Before your nerf i could get lexorin/pax/any funny reagent from random chemical mutation and still use without having to cross-pollinate nettle with woodcaps to clean all other reagents because nettle injected 6 units. Now that ability has been removed. How is that an overreaction?
> 
> And yet it's still being constantly abused, I will wait for a mantainer to offer their input and go from there

I just don't understand your reasoning. OP against nukies? Remove hardsuit pen, up the damage a bit and it's fixed. Why even change injection amount? What abuse are you talking about? If you believe that changing injection amount woudn't change much - how are you fixing said abuse?

**Comment by deltanedas** [comment]
to determine if its use is abuse you need design reasoning for what its actually meant to be used for. if you dont know what its meant to be used for you cant say what is abuse outside of obvious cases (2 tapping heavily armed nukies)

**Comment by Anzarot121** [comment]
> I would rather you remain civil on my PR, botany shouldn't have access to plants capable of taking down a fully grown man in 2 hits, this mitigates that, it's a fair change in accordance with the current deathnettles

How am I not polite? You are literally removing mechanics from the game under the guise of "balance". If your PR is accepted, it will be impossible to kill even a cockroach with nettles. At maximum potency, 100, which is impossible to achieve without RNG mutations, nettle will deal as much as 12 damage over 24 seconds.

**Comment by EdenTheLiznerd** [comment]
The change is already merged and being tested, you more than welcome to share your dismay in the discord feedback thread

**Comment by metalgearsloth** [comment]
Because the children can't be nice to each other no one gets to talk at all.

**Comment by Emisse** [comment]
merging this but with the caveat that im fine with people buffing these up to an acceptable point, so dont freak out

**Pull request merged**
