### PR TITLE
Pilot alert and console flavortext

### PR DESCRIPTION
**Pull request by CrudeWax**
## About the PR 
Adds extra flavor text to consoles.
Replaces placeholder PILOT alert with a OC icon drawn by me.

**Screenshots**

image

**Changelog**

:cl: CrudeWax
- add: Added additional flavor text to consoles
- tweak: Replaced placeholder piloting alert icon

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Not a big fan of the changes:
1. The majority of them have spelling / grammar mistakes.
2. Jet fuel can't melt steel beams is some cringelord shit.
3. Most of them just make the description unnecessarily long to put teh funney in.
4. I'm not a big fan of the alert icon but it's better than what we have I guess.

**Comment by PaulRitter** [comment]
Some of the added descriptions seem pointless to me/make it unnecessarily bloating.

Also im sorry but i dont like that icon, it just looks weird and isnt descriptive :D I was more thinking putting a spaceship there or smth? maybe just the classic tilted rocket?

**Comment by DmitriyRubetskoy** [comment]
image

**Comment by metalgearsloth** [comment]
Just trim it down to the icon to merge and we can talk about the descriptions in another PR or on discord.

**Pull request merged**
