### PR TITLE
Cutter machine & steel mozaic item tiles

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR

Adds new cutter machine. With this machine you can craft tiles with patterns:
- Dark steel
- Steel steel
- White steel
- Concrete
- Wood
- Technical

Also adds TileItem for all dark, steel and white tiles. A little sprite fix of existing steel tiles.

P.S. That's water jet cutter

## Why / Balance

It's really annoying when after an explosion (or just rip off with crowbar) you can't fix floor to original state. 
image
Adding new steel tile variations to the build menu is boring and sooo messy. That's why i think adding a new machine is better idea.
Concrete just cool. 

## Media
image
image
image
**[Video with all features](https://youtu.be/1PlEPvJhLJo?si=F5ZgyRtgRpS8fb9v)**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ko4erga
- add: Added a cutter machine for crafting patterned steel tiles, concrete and wooden tiles.
- tweak: After rip off patterned tiles you get current pattern, not just steel tile.

### CODE REVIEW

**Comment by ps3moira** [comment]
Wanted to ask, isn't this what was intended for the Sheet Meister in https://github.com/space-wizards/space-station-14/pull/16686 ?

**Comment by Plykiya** [comment]
interior design is my passion
also they don't do the same thing, the sheetmeister creates a material you can craft with while this creates the output tile itself

**Comment by ps3moira** [comment]
> interior design is my passion
> 
> also they don't do the same thing, the sheetmeister creates a material you can craft with while this creates the output tile itself

You get what I'm suggesting though. It doesn't make sense to have two machines that do very similar jobs, that's just unnecessary machine bloat

**Comment by Plykiya** [comment]
> > interior design is my passion
> > also they don't do the same thing, the sheetmeister creates a material you can craft with while this creates the output tile itself
> 
> You get what I'm suggesting though. It doesn't make sense to have two machines that do very similar jobs, that's just unnecessary machine bloat

EmoGarbage is about to make a BioGen that turns fruits into materials just like how the meat turns into sheets, so uh, not sure about the bloat thing

**Comment by EmoGarbage404** [comment]
I think this is fine as its own machine. Its nifty and would go well with the other tile related things in the astroturf tech

**Pull request merged**
