### PR TITLE
Imagine if artifacts fucking killed you

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

changes:
- light artifact is brighter and flashbangs you
- banana artifact makes more bananas + potassium puddle
- made temperature effects more severe + more common

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Increased the danger of most artifact effects and added some new ones.

### CODE REVIEW

**Comment by AJCM-git** [comment]
language

**Comment by UbaserB** [comment]
what about uhhh, when artifacts make puddles of a random liquid they can make the liquid something dangerous too? like amatoxin for example

**Comment by Anzarot121** [comment]
> what about uhhh, when artifacts make puddles of a random liquid they can make the liquid something dangerous too? like amatoxin for example

One day, the artifact created a pool of fluorine with chlorine and entered a self-activation cycle. I lost half of the RND. Or it was a poo; of potassium with water.

**Comment by Equivocateur** [comment]
> One day, the artifact created a pool of fluorine with chlorine and entered a self-activation cycle. I lost half of the RND. Or it was a pool of potassium with water.

R&D is not without risk

**Comment by Slava0135** [comment]
Research & Destruction

**Comment by GeneralGaws** [comment]
AWESOME PR, but puddles was great too..

**Pull request merged**
