### PR TITLE
New Space Ruin: Syndicate Dropship (from /tg/) (also adds plastitanium windows)

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Ports & adapts the syndicate dropship ruin from /tg/. This ruin is small, but contains a nice chunk of specific loot, including armory closets with combat gloves, a single chameleon kit backpack, and a fully functioning shuttle. That may *sound* appetizing, but the shuttle is probably a smidge more fortified then what you'd expect.
Content Client_X7mxGrRRK2

Also *finally* ports over plastitanium windows. The syndicate airlocks and stuff will need to be modified to not look like plasmaglass later.

## Why / Balance
Small ruins are good for atmosphere + we don't have any ruins with anything dangerous in them yet. I look forward to seeing salvagers get gunned down by the turrets and/or the guy inside.

Plastitanium windows look a *lot* better then plasmaglass for plastitanium shuttles, not much to add there. We've been missing them for a really long time.

## Media
Content Client_X1zKZqW4mt

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Nothing here feels significant enough to warrant a CL, I think.

### CODE REVIEW

**Comment by deltanedas** [comment]
stealthops getting trolled by salv when they roll visors wreck :trollface:

**Comment by Flareguy** [comment]
Replaced the visor with combat gloves since being able to instantly tell if someone is a nukeop is dumb. Salv will probably want those more anyways.

**Comment by UbaserB** [comment]
the windows look surprisingly good

**Comment by Emisse** [comment]
syndi foot soldier my beloved

**Comment by K-Dynamic** [comment]
Add more dangerous wrecks like these and salvage may actually have reason to use ship guns

**Comment by Emisse** [comment]
ruins will have mobs eventually i just want them to have special mobs so waiting on some things

**Comment by K-Dynamic** [comment]
> ruins will have mobs eventually i just want them to have special mobs so waiting on some things

You know, it'd be funny if the syndicate dropship lorewise was 'accidentally' magnetised while on patrol (especially since it's fully functional), with one or two angry syndie reinforcements inside

**Pull request merged**
