### PR TITLE
Python/Throwing Knife Price Tweak

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I changed the Python's price to 6TC and the Throwing Knives to 7
## Why / Balance

Python isn't worth 8TC and Throwing Knives have AP alongside being relatively quiet and reusable. They should be sidegrades, but I view the knives as a little bit better.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Python 8 -> 6TC
- tweak: Throwing Knives 6 -> 7TC

### CODE REVIEW

**Comment by FungiFellow** [comment]
Some folk have suggested tweaking Python ammo refill prices down too. Any thoughts?

**Comment by ARMOKS** [comment]
Throwing knifes even with AP aren't worth more than 4-5 TC, making them 7 would kill them. They are a high skill item and I think we should aim to not nerf said items. If you made them 7 why would anyone ever get them over viper + 4 spare mags, which would vastly outclass the throwing knives. They also have sooo many downsides to actually trying to use them and are useless if you're against more than one person and very easy to lose.

**Comment by superjj18** [comment]
How is an AP automatic revolver less value than knives?

**Comment by deepdarkdepths** [comment]
I dont think throwing knives should be touched considering their required skill floor.

**Comment by UbaserB** [comment]
After I PR'd the buff, throwing knives are now at the perfect balance. They have A LOT of downsides and are generally not a great purchase unless in certain situations. Doing this would kill them off, like someone else said.

**Comment by Jarmer123** [comment]
I like this change. Throwing knives are high skill celling until a syndie gets a banana peel and can just throw 4 AP knives into you whilst you can do nothing but lay there or god forbid they get syndie soap.

**Comment by asperger-sind** [comment]
> I like this change. Throwing knives are high skill celling until a syndie gets a banana peel and can just throw 4 AP knives into you whilst you can do nothing but lay there or god forbid they get syndie soap.

Just like most things in this game, lord forbid the syndie uses cuffs on you after you slip and then has the liberty to beat you to death with a 1-damage weapon.

**Comment by K-Dynamic** [comment]
> Just like most things in this game, lord forbid the syndie uses cuffs on you after you slip and then has the liberty to beat you to death with a 1-damage weapon.

No but it would be way slower and gives more time for backup to arrive

Getting off-topic but if sec had instastuns (requiring reaction time faster than ping allows) we'd be seeing massive discourse over sec being too OP - thankfully we don't have soap or lube because that would break balance

Getting back on-topic, knives are okay for 6 tc - unlike a python where you can just instantly teleport more ammo at low price, you'd need to repurchase the knives for full cost to match its speed, so making it more expensive seems ofd

**Comment by mirrorcult** [comment]
don't personally see the reasoning here, agree with the dissenting comments

**Pull request closed without merging**
