### PR TITLE
Autogenerates IgnoredComponents

### PR DESCRIPTION
**Pull request by PaulRitter**
This now is a cleanup for the sourcegen in robusttoolbox to properly recognize all names

needs https://github.com/space-wizards/RobustToolbox/pull/1459

### CODE REVIEW

**Comment by PaulRitter** [comment]
Until i figure out how to properly select ONLY component-classes this will be bikeshedded, sorry

**Comment by PaulRitter** [comment]
This now is a cleanup for the sourcegen in robusttoolbox to properly recognize all names

**Comment by metalgearsloth** [comment]
Doesn't seem to work when I checkout robust

**Comment by PaulRitter** [comment]
this will not be viable, at least not in its current form. (maybe) this could be done as a buildtask. tbd

**Comment by AJCM-git** [comment]
Engine PR was closed so

**Pull request closed without merging**
