### PR TITLE
roundstart mop and stuff

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
made jani stuff and uniform printer roundstart instead of tech

## Why / Balance
good + less useless shit in t1 so i can get astro ice unlocked faster

## Technical details
no

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by UbaserB** [comment]
Im pretty sure there was an issue that mentioned this, let me find it

**Comment by deltanedas** [comment]
yes thats what "good" is

**Comment by UbaserB** [comment]
image
#21462

**Review by EmoGarbage404 — DISMISSED** [review]
move robotic cleanliness and meat manipulation techs down to tier 1 so that tier 2 doesn't have more technology than t1.

**Pull request merged**
