### PR TITLE
Give the Zombie Bundle .357 incendiary ammo

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

It contained a mateba and .45 incendiary, but the PR to buff the python borked that and it now has a mateba and some useless ammo. Balance be damned, this gives it a Python (Mateba is deathsquad patented) and 2 speedloaders of .357 incendiary to go with it. 
If this turns out too broken just give them the old .45 and a deckard or something, but this is more fun. 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**

:cl: Lank
- add: The Python is now included in the Syndicate Zombie Bundle, in place of the Mateba. Appropriate ammo has been provided.

### CODE REVIEW

**Comment by LankLTE** [comment]
Test failure should be unrelated

**Comment by metalgearsloth** [comment]
stop adding unique ammo aaaaaa

**Comment by Aisu9** [comment]
zombies already take double damage from fire (only 50% more when Emo's tweak gets merge) i'm not sure Nukies need 51 damage incendiary ammo

**Comment by LankLTE** [comment]
> stop adding unique ammo aaaaaa

i mean literally every other ammo type has incendiary variant (maybe not .60, but that's its own beast) so I don't see adding this one as a huge issue. I mean granted if .357 is gonna be removed anyways it won't be an issue, but as is the zombie bundles' gun is pointless 

> zombies already take double damage from fire (only 50% more when Emo's tweak gets merge) i'm not sure Nukies need 51 damage incendiary ammo

It does 48 damage. That said the bundle already had incendiary rounds so I don't see why this is a huge issue

**Comment by LankLTE** [comment]
closing so i can make revolvers good

**Pull request closed without merging**
