### PR TITLE
Admin Observers get a hat slot and a pda

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Ok MAYBE this is for drip reasons... but I added a PDA by default to be able to read stuff like news/pda/round time so this is a very nice change.

Said pda will always spawn in when you enter aghost. The clothes won't stay though 

Due to a wierd issue, you will need to press the inventory button from the ui instead of just pressing "I"

## Why / Balance

Above, this is a very important change and will greatly enhance admin expirience

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

ignore most of these images im lazy to take new ones. Now its just hat slot and pda

### CODE REVIEW

**Comment by lzk228** [comment]
maybe better belt and backpack instead of uniform, neck and eyes?

**Comment by deltanedas** [comment]
combine this with whistle pr :trollface:
spook all the inferior ghosts

**Comment by VasilisThePikachu** [comment]
> maybe better belt and backpack instead of uniform, neck and head?

Admins don't need a backpack, they can spawn in anything anyway. Neither do they need a belt

like I said the other stuff is for drip.

**Comment by Skarletto** [comment]
lmfao

**Comment by lzk228** [comment]
> Admins don't need a backpack, they can spawn in anything anyway. Neither do they need a belt

ok, only backpack then
for transportation specific things, that cannot be just spawned

**Comment by VasilisThePikachu** [comment]
> > Admins don't need a backpack, they can spawn in anything anyway. Neither do they need a belt
> 
> ok, only backpack then for transportation specific things, that cannot be just spawned

You would have to spawn then in anyway at least once. I feel like its useless clutter

**Comment by LankLTE** [comment]
they can just hold the backpack if they need one

**Review by moonheart08 — CHANGES_REQUESTED** [review]
if we want this we should be adding loadout/species ghosts (i.e. ghosts that use ur character as the sprite) instead of a hack meant to allow admins to meme.

**Comment by deltanedas** [comment]
pro ghost loadout:
- EnsureComp<HandsComponent>
- copy paste addhand
- add unremovable synthesizer
costs all the loadout points

**Comment by moonheart08** [comment]
@deltanedas Kindly stop shitposting on PRs, productive discussion please.

**Comment by IProduceWidgets** [comment]
I suggest the default PDA to be the MedicalPDA since it can medscan, which is something admins somewhat regularly need, also it might prevent accidentally dropping an AA id somewhere.

**Comment by VasilisThePikachu** [comment]
> I suggest the default PDA to be the MedicalPDA since it can medscan, which is something admins somewhat regularly need, also it might prevent accidentally dropping an AA id somewhere.

This is an empty PDA, there's no id. As for the other I could look into that

**Comment by VasilisThePikachu** [comment]
> if we want this we should be adding loadout/species ghosts (i.e. ghosts that use ur character as the sprite) instead of a hack meant to allow admins to meme.

This feels kinda out of scope for this pr. The pda part is a good change at least.

I don't see how loadouts would fix this. And having a ghost of just your species but transparent and white is just weird-looking.

**Comment by LankLTE** [comment]
> This feels kinda out of scope for this pr. The pda part is a good change at least.

I do agree the requested change is out of scope- however I don't see any purpose this has apart from "aghosts can look funny". Maybe an admin can correct me if I'm wrong, but I don't see why they can't just spawn a PDA if they need one for whatever reason, especially since they can give themselves however many hands they may need.

**Comment by VasilisThePikachu** [comment]
> > This feels kinda out of scope for this pr. The pda part is a good change at least.
> 
> I do agree the requested change is out of scope- however I don't see any purpose this has apart from "aghosts can look funny". Maybe an admin can correct me if I'm wrong, but I don't see why they can't just spawn a PDA if they need one for whatever reason, especially since they can give themselves however many hands they may need.

I was making this while with an admin in a vc, and some others seemed to agree to like this. At least the pda part to be able to read the news mostly. It's nice not having to spawn it every 5 seconds to check news

Now the rest... yeah the admins did just say they wanted hat slot for the funny but I did go overboard too

**Comment by LankLTE** [comment]
This still just feels like a weird change to let admins look funny on occasion, especially in regard to the clothing slots which I’m not a massive fan of. If any admins can say whether they actually need a dedicated PDA slot I suppose that’d help.

**Comment by VasilisThePikachu** [comment]
> This still just feels like a weird change to let admins look funny on occasion, especially in regard to the clothing slots which I’m not a massive fan of. If any admins can say whether they actually need a dedicated PDA slot I suppose that’d help.

Ok i will be honest... i was told to give em hats... i went a LITTLE overboard

But i feel like the pda is a nice addition to allow admins to easily check news, check round time and the manifest, could also add a medical scanner to it in case an admin needs it.

**Comment by Skarletto** [comment]
> This still just feels like a weird change to let admins look funny on occasion, especially in regard to the clothing slots which I’m not a massive fan of. If any admins can say whether they actually need a dedicated PDA slot I suppose that’d help.

we dont need a pda we need something to be able to see the round time in a ui or something. PDA is just a workaround for that.

**Comment by dvir001** [comment]
There need to be a new admin utility to read news without the need for PDA, and tbh if anything there need to just be a Centcom PDA as a full ui "app" like the fax ui and others.

This is a good work around but the real fix probably wont be to add a PDA slot for ghosts.

**Comment by VasilisThePikachu** [comment]
> There need to be a new admin utility to read news without the need for PDA, and tbh if anything there need to just be a Centcom PDA as a full ui "app" like the fax ui and others.
> 
> This is a good work around but the real fix probably wont be to add a PDA slot for ghosts.

Yes, im aware adding it as an action is probably better. I can't really get anything else to work right now. And this just makes sure that if any new apps show up like pda messaging it wont need to be manually added to admins.

**Comment by Emisse** [comment]
make this use the new clothing ui tab

**Comment by AJCM-git** [comment]
Wouldnt a backpack slot make more sense? The only reason I can think of you would need a pda slot is to ease checking the news and that can be accomplished better by adding a news instrinsic UI to aghosts. With a backpack slot they can just put a BoH or something and store the PDA and all they need in there. Also update media

**Comment by VasilisThePikachu** [comment]
> Wouldnt a backpack slot make more sense? The only reason I can think of you would need a pda slot is to ease checking the news and that can be accomplished better by adding a news instrinsic UI to aghosts. With a backpack slot they can just put a BoH or something and store the PDA and all they need in there. Also update media

What else would you put in that backpack though? And the pda is a health analyzer with logo probe. Along with any other goodies pda have like alert status round time etc. Yes though there probably should be a news ui somewhere since you can only delete posts from there

**Comment by AJCM-git** [comment]
> What else would you put in that backpack though? And the pda is a health analyzer with logo probe. Along with any other goodies pda have like alert status round time etc. Yes though there probably should be a news ui somewhere since you can only delete posts from there

You would put the PDA with those functions + anything else you may need, it's just a better solution with more applications

**Comment by VasilisThePikachu** [comment]
What else does an admin regularly use?

**Comment by Skarletto** [comment]
gas analyzer

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Yeah, having a pocket and backpack slot seems like a better option than the PDA slot (maybe make them spawn with a BoH too?)

**Comment by VasilisThePikachu** [comment]
> Yeah, having a pocket and backpack slot seems like a better option than the PDA slot (maybe make them spawn with a BoH too?)

Da fuck is a boh

**Comment by AJCM-git** [comment]
> Da fuck is a boh (box of hugs?)

close, bag of holding

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Fix linter (also update media)

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
