### PR TITLE
Foxes

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR

Foxes.

**Media**

Screenshot_20230329_192519

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: YIP YAP YIP YAP YIP YAP YIP YAP

### CODE REVIEW

**Comment by vulppine** [comment]
i primarily did this to see what it's like to add a new species as well (and to see if i can still even do this)

**Comment by moonheart08** [comment]
FURRY!!!!!!!!!!!!!!!!!!!

**Comment by mirrorcult** [comment]
MY favorite animal, the fucks

**Comment by Skyedra** [comment]
Awoo :heart:

**Comment by AJCM-git** [comment]
Where are ALL the fox sounds

**Comment by Veritius** [comment]
please no more cosmetic races

**Comment by VasilisThePikachu** [comment]
Don't revert after april fools please thanks

**Comment by deltanedas** [comment]
yeah this is a crazy amount of effort just to be removed after a day

**Comment by rbertoche** [comment]
please keep it

**Comment by Just-Sim** [comment]
god please

**Comment by PuroSlavKing** [comment]
return..

**Pull request merged**
