### PR TITLE
Implemented toggleable FPS counter.

### PR DESCRIPTION
**Pull request by pointer-to-null**
## About the PR 
Made a simple toggleabe FPS counter available through game settings.
Requires https://github.com/space-wizards/RobustToolbox/pull/2246

**Screenshots**

изображение

**Changelog**

:cl:
- add: Added a FPS counter game option.

### CODE REVIEW

**Comment by mirrorcult** [comment]
we have an fps counter in the F3 menu already?

**Comment by pointer-to-null** [comment]
Yes, I know about F3 debug display. But it would be nice to have a standalone option when released.

**Comment by mirrorcult** [comment]
yeah, fair enough

**Comment by Ephememory** [comment]
good pr

**Pull request merged**
