### PR TITLE
added new flavor book to library

### PR DESCRIPTION
**Pull request by Nettingman**
## About the PR
Adds a new flavor book "The Lusty Reptilian Janitor" to the library.

## Why / Balance
This is a parody of book "The Lusty Argonian Maid" from the Elder Scrolls series, since the reptilian species is partially based on the argonian species of Elder Scrolls.

## Technical details
I added the book's content, and a new cover icon for the book.
The content is safe for work, it only hints at the romance between the two characters.

## Media
screenshot

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: A new book "The Lusty Reptilian Janitor" can now spawn on bookshelves.

### CODE REVIEW

**Comment by Djungelskog2** [comment]
I already know what everyone else is gonna say, but its better than the lusty xeno maid, and its tradition

**Comment by UncaughtEx** [comment]
> I already know what everyone else is gonna say, but its better than the lusty xeno maid, and its tradition

Yeah 
Plus we've got the lusty exo babes posters anyway

**Comment by bruhmogus** [comment]
this is... fucking hilarious lmfao
i hope this gets merged simply because if its closed i get to call the maintainers hypocrites since there's like eight porno posters already in the game

**Comment by Nettingman** [comment]
Damn, sorry, I use git pretty regularly, but this is my first pullrequest. I tried to rebase, was that a bad idea? I can see there has been a submodule update in those 3 new commits.

**Comment by Nettingman** [comment]
Okay, I undid the rebase, because I've found that my indents were messed up as well, hopefully this solves the problem.

**Comment by foob1** [comment]
Too descriptive with the glancing and blushing part. Wizden is a 16+, i think if you want to implement this, you should bring this to a fork that’s 18+

**Comment by Nettingman** [comment]
I would rather tone it down if deemed necessary and have it on Wizden.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
Isn’t this just the “lusty argonian maid” word for word?

**Comment by Skarletto** [comment]
inappropriate

**Comment by Everturning** [comment]
change the bit about the stain on the pants
or you can cleverly tear away by having something at the end like:
_The rest of the pages have been torn out._
or
_The page cuts off, but the paper is too sticky to continue._

**Comment by Skarletto** [comment]
> The page cuts off, but the paper is too sticky to continue.

absolutely not

**Comment by Everturning** [comment]
> > The page cuts off, but the paper is too sticky to continue.
> 
> absolutely not

for sure

**Comment by Cojoke-dot** [comment]
> Plus we've got the lusty exo babes posters anyway

It's Busty Backdoor Exo Babes 6 thank you very much
image

**Comment by Nettingman** [comment]
> It's Busty Backdoor Exo Babes 6 thank you very much image

**Comment by Golinth** [comment]
If someone would get an ERP bwoink or ban for saying anything that is on an item or in a book, that item/book should be removed or reworded. This definitely falls under that category IMO.

**Pull request closed without merging**
