### PR TITLE
add new decals

### PR DESCRIPTION
**Pull request by Jaraten**
## About the PR
Adds 3 new varieties of thin decals under 3 tile colors.

## Why / Balance
Additional decor for mappers

## Media
Снимок экрана 2024-06-09 144935
Снимок экрана 2024-06-09 150652
Снимок экрана 2024-06-09 150621

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added new thin decals!

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by Jaraten** [comment]
> Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

reopen it, please.

**Comment by Jaraten** [comment]
Ubuntu is complaining again over nothing. Can you run the tests again?

**Comment by Flareguy** [comment]
I don't feel like these fit very well in to the game. They're very under-detailed and simplistic.
In addition, I feel like we already suffer with a degree of "floor tile bloat" from the amount of decals and floor tile variations we have; these really don't help matters in that regard.

As such, I'm opting to close this PR. Thank you for your contribution.

**Pull request closed without merging**
