### PR TITLE
Boxstation shuttle

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR 
Adds boxstation shuttle from TG as default emergency shuttle, should be less crammed than the one we have. If anything I could make a bigger one since we are high pop most of the time and this seems more mid-pop
**Screenshots**

image

**Changelog**

:cl:
- add: The emergency shuttle has changed to the Boxstation shuttle from TG.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by moonheart08** [comment]
Does this fit on every station? Did that test get merged.

**Comment by metalgearsloth** [comment]
> Does this fit on every station? Did that test get merged.

Need to update it. wrexbe seemed fine with me putting it on top of the map load test so I gott ado that.

**Comment by DogZeroX** [comment]
Map in the description has been updated.

**Comment by TimrodDX** [comment]
Does this fix Waystation? I'm still kinda pissed off about that whole thing.

**Comment by EmoGarbage404** [comment]
> Does this fix Waystation? I'm still kinda pissed off about that whole thing.

literally irrelevant since waystation isn't even in the game files anymore.

**Comment by TimrodDX** [comment]
> > Does this fix Waystation? I'm still kinda pissed off about that whole thing.
> 
> literally irrelevant since waystation isn't even in the game files anymore.

Thank you for making my decision to leave the project an easy one.

**Comment by moonheart08** [comment]
> Does this fix Waystation? I'm still kinda pissed off about that whole thing.

Even if it was in, no it would not, as Waystation does not work with any standard SS13 shuttle designs.

**Comment by Visne** [comment]
Why are there chairs in front of the airlocks? 🤢

**Comment by mirrorcult** [comment]
still of the opinion that this shuttle is pretty ugly and would not fit very well. i'm all for a bigger shuttle design but this is a downgrade

**Comment by metalgearsloth** [comment]
> still of the opinion that this shuttle is pretty ugly and would not fit very well. i'm all for a bigger shuttle design but this is a downgrade

What's your suggestion

**Comment by mirrorcult** [comment]
> 
> What's your suggestion

a shuttle built for our docking port dimensions and new required shuttle devices rather than a port from SS13

**Pull request closed without merging**
