### PR TITLE
Renamed the CMO's cats

### PR DESCRIPTION
**Pull request by Snowni**
## About the PR 

Gave the CMO's pets names for more personality. Also renamed the sloth and the ferret for if/when they ever get added in to a map.

**Changelog**

:cl: Seija

tweak: Renamed the cats that spawn in the CMO's office.

### CODE REVIEW

**Comment by mirrorcult** [comment]
blessed first PR

**Review by mirrorcult — APPROVED** [review]

**Comment by ZeroDayDaemon** [comment]
this edits the base entities incorrectly, otherwise now every single cat and mob of that type will have the names of specific ones

**Comment by ZeroDayDaemon** [comment]
actually I'm noticing a lot of them are like that, any base mob type needs to be generic and have a derivative with the specific pet name, otherwise every cat is now named runtime

**Comment by Emisse** [comment]
we do be needing spawners for different animals n stuff too

**Comment by ZeroDayDaemon** [comment]
my suggestion is moving all base animal types back to animals and making pets the one for named specific derivatives of a base animal type

**Comment by Emisse** [comment]
theres a few we'd have to move from animal to pets and vice versa but for future that would clean it up a lot

**Comment by ZeroDayDaemon** [comment]
if this PR gets merged, I'll just fix it after

**Comment by Peptide90** [comment]
It'd be good git practice to make the corrections suggested so imo no reason to merge this as is. Correcting the pets to be separate entities can be this PR.

Spawners for all animals can be a different PR or I can handle it later. It's a few copy pastes.

**Comment by Snowni** [comment]
Going to edit it and reopen it again, can't seem to revert the changes on my fork so just doing it from scratch

**Pull request closed without merging**
