### PR TITLE
Hardsuit armor value tweaks

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Cap's hardsuit buffed to 30% flat resistance to all brute damage, hes the most important man on the station and deserves more than 25% resistance

CMO's hardsuit buffed to 30% radiation resistance

syndie hardsuits also get more radiation resistance

the riot suit is also worse against bullets
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- add: the nanotrasen-syndicate arms-race has introduced minor improvements to existing hardsuits

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Didn't we just nerf hardsuits to not be the be-all.

Also hardsuits definitely do not need more explosion resistance.

**Comment by JoeHammad1844** [comment]
can I get some more actionable constructive criticism?

**Comment by metalgearsloth** [comment]
Why should hardsuits be the best defensive option for every situation?

**Comment by JoeHammad1844** [comment]
I mean, what specifically do you want changed?

**Comment by LankLTE** [comment]
Constructive criticism:
Riot armor change is weird but I don't really have much to say about it. I never really see it used though so I'm not sure it needs to be nerfed. 
Wardens' hardsuit is supposed to be slow to discourage them from wearing it and make them walking tank.
Cap's hardsuit shouldn't be even close to as good as the carapace, its use is to provide space resistance.
CMO's hardsuit already has the lowest speed penalty of any hardsuit in the game (with one)- it's effectively just a better labcoat. Giving it resistances makes that problem worse on top of it being on a role that downright doesn't need them.
Bloodred explosion resist only really makes the chinalake better which doesn't really need to be done. The rad / heat resist changes are also just really random and I don't see much of a point.

**Comment by Emisse** [comment]
Captain's Hardsuit is meant to be a tradeoff to the carapace's resist for space proofing.

**Comment by Emisse** [comment]
Warden hardsuit is meant to be slow so they dont sit in their hardsuit in the brig all round, cmo hardsuit isnt meant to be defensive beyond space proofing, explosive resists on all hardsuits were nerfed so that explosives could be useful again

**Comment by JoeHammad1844** [comment]
ah, ill change that then

**Comment by JoeHammad1844** [comment]
now cap gets 30% resist

**Comment by JoeHammad1844** [comment]
hmm how did I manage to break this?

**Comment by JoeHammad1844** [comment]
this error doesn't make sense

**Comment by JoeHammad1844** [comment]
this error doesnt seem to have anything to do with anything ive changed

**Comment by KaiShibaa** [comment]
I wouldn't buff hardsuits more. People wear them 24/7 and there shouldn't be MORE reasons for that.

**Comment by deltanedas** [comment]
hardsuit helmet battery slot :trollface:

**Comment by JoeHammad1844** [comment]
I don't understand this error at all

**Pull request closed without merging**
