### PR TITLE
Delivery oriented drip for QM

### PR DESCRIPTION
**Pull request by JoelZimmerman**
## About the PR
This adds a modified version of one of the jumpsuits and jump skirts from Paradise Station for the QM. The hold sprite was made by myself. It spawns in the dresser in the QM's office, but can also be made using the uniform printer.

## Why / Balance
I figured the QM deserves an outfit that lets them stand out from their underlings, but also without having to get into the full formal outfit. Not only that, it comes in charcoal black and delivery brown, which seriously shows that the most important thing for you is a speedy delivery for the rest of the crew!

## Technical details
- Added and modified the colors a bit for a new jumpsuit and jump skirt, originally comes from Paradise Station.
- Added the outfits to the QM dresser and made it craftable with the uniform printer.

## Media
outfitpreview

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:

- add: A new business jump shirt for the Quartermaster can now be found in their office dresser.
- add: The uniform printer now has the ability to make a replacement business uniform for the Quartermaster.

### CODE REVIEW

**Comment by Scruq445** [comment]
I would really love this!

**Comment by lzk228** [comment]
qm has too much drip

**Comment by UbaserB** [comment]
> qm has too much drip

I think HoS still has more

**Comment by lzk228** [comment]
btw your cl is broken, should be
```
:cl:
- add: Text
- tweak: Text
```

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Changelog needs to not be RP oriented please.

**Comment by JoelZimmerman** [comment]
> Changelog needs to not be RP oriented please.

Is this better?

**Comment by metalgearsloth** [comment]
yeah that looks fine

**Comment by Sarahon** [comment]
What's it look like with the cloak on?

**Comment by SlamBamActionman** [comment]
It looks like it clips weirdly with one of the hands in the side sprite.

That being said, amazing drip that is fitting for the job, 10/10 love it.

**Comment by JoelZimmerman** [comment]
> What's it look like with the cloak on?

preview2

**Comment by KingFroozy** [comment]
/tg/ styled sprites detected 😱

**Comment by Sarahon** [comment]
> > What's it look like with the cloak on?
> 
> preview2

Not bad, I dig it.

**Comment by UbaserB** [comment]
Closing this PR for now since clothing is frozen, see issue no. 8524. If you want this reopened after the freeze ends, please ping me.

**Pull request closed without merging**
