### PR TITLE
Increased damage for laser weapons

### PR DESCRIPTION
**Pull request by TaralGit**
The damage for lasers is ridiculously low compared to projectile weapons. Laser deals 10 heat damage and heavy laser deals 30. Compared to .35 auto pistol rounds that deal more damage than laser and very close to a laser cannon (24 piercing). So I made this PR to buff laser to 15 heat damage and heavy laser  to 45.

:cl:
- tweak: Increased laser damage

### CODE REVIEW

**Comment by Pangogie** [comment]
There's a reason that normal bullets were removed from the armory and laser guns stayed.

**Comment by PaulRitter** [comment]
>no reason for buff provided in pr
>game admin telling me its not a good idea

gotta give me a better reason to merge it that that :P

**Comment by TaralGit** [comment]
> > no reason for buff provided in pr > game admin telling me its not a good idea
> 
> gotta give me a better reason to merge it that that :P

Ok. I provided a reason in the PR. The laser damage is too low compared to projectiles.

**Comment by Peptide90** [comment]
> > > no reason for buff provided in pr > game admin telling me its not a good idea
> 
> > 
> 
> > gotta give me a better reason to merge it that that :P
> 
> 
> 
> Ok. I provided a reason in the PR. The laser damage is too low compared to projectiles. 

Is that not because they're recharge able? I've not checked your values but yeah.

**Comment by TaralGit** [comment]
> > > > no reason for buff provided in pr > game admin telling me its not a good idea
> > 
> > 
> > > 
> > 
> > 
> > > gotta give me a better reason to merge it that that :P
> > 
> > 
> > Ok. I provided a reason in the PR. The laser damage is too low compared to projectiles.
> 
> Is that not because they're recharge able? I've not checked your values but yeah.

I'm fully aware that laser guns are supposed to do less damage than firearms. But a laser cannon doing less damage than even a small caliber pistol? And iirc on most servers basic laser guns did like 20 burn.

**Comment by Elijahrane** [comment]
Needing to land 2 entire magazines into someone to crit them before even factoring in armor does seem kind of shit

**Comment by Peptide90** [comment]
> > > > > no reason for buff provided in pr > game admin telling me its not a good idea
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > gotta give me a better reason to merge it that that :P
> 
> > > 
> 
> > > 
> 
> > > Ok. I provided a reason in the PR. The laser damage is too low compared to projectiles.
> 
> > 
> 
> > Is that not because they're recharge able? I've not checked your values but yeah.
> 
> 
> 
> I'm fully aware that laser guns are supposed to do less damage than firearms. But a laser cannon doing just slighty more damage than a small caliber pistol? And iirc on most servers basic laser guns did like 20 burn.
> 
> 

Good reasoning, I approve this message.

**Pull request merged**
