### PR TITLE
FIX modifier cofficients

### PR DESCRIPTION
**Pull request by NULL882**
## About the PR

The mirror shield has normal protection against lasers.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: @NULL882 
- fix: Fixed HEAT damage multiplier against mirror shield.

### CODE REVIEW

**Comment by Aisu9** [comment]
the mirror shield will increase damage taken by the wearer by 70% passively and 60% while active with these changes

**Comment by NULL882** [comment]
> the mirror shield will increase damage taken by the wearer by 70% passively and 60% while active with these changes

This is how he should do it, because I only corrected a typo in the file itself, which fixed the logic of the shield itself and its protection.

**Comment by Aisu9** [comment]
did you fix shield logic?
because with how i remember shield works, the mirror shield that reflect lasers... should increase the damage the wearer take with these numbers, it's 170%/160% of the base damage.
if i shot with with a 10 heat damage laser you will suffer between 17 and 16 damage with that "old?" working logic

**Comment by Aisu9** [comment]
you can check the wooden shield for example, the fire damage modifier is 2.0. you'll take 100% more fire damage if you keep it in your hands

**Comment by NULL882** [comment]
Oops, I made a mistake in the coefficients...

**Comment by Slava0135** [comment]
i am not yaml expert but i think this changes nothing

**Comment by metalgearsloth** [comment]
If you get a chance to revisit let us know.

**Pull request closed without merging**
