### PR TITLE
Add underwear and undershirts

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## Why / Balance
why would spaceman be wearing nothing under jumpsuit

## Technical details
adds Undershirt and Underwear ``HumanoidVisualLayer``

## Media
image
image

you can recolor the underwear
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Added underwear and undershirt markings!

### CODE REVIEW

**Comment by lzk228** [comment]
socks?

**Comment by IamVelcroboy** [comment]
Socks!

**Comment by bruhmogus** [comment]
socks.

**Comment by Hanzdegloker** [comment]
Finally

**Comment by EmoGarbage404** [comment]
sprites are very cm13

**Comment by baddiePRO** [comment]
> socks?

make the coder socks a sock option :godo:

**Comment by 0x6273** [comment]
This makes no sense as markings, that's for things like tattoos and scars that are part of your body, not clothing. This should use the loadout system instead.

**Comment by Dutch-VanDerLinde** [comment]
> This makes no sense as markings, that's for things like tattoos and scars that are part of your body, not clothing. This should use the loadout system instead.

no

**Comment by 0x6273** [comment]
> > This makes no sense as markings, that's for things like tattoos and scars that are part of your body, not clothing. This should use the loadout system instead.
> 
> no

??

**Comment by Dutch-VanDerLinde** [comment]
there's no point coding an entire ass system just to do something that can already be done with markings

no one said that markings have be specifically for body stuff because gauze markings exist

**Comment by lzk228** [comment]
> This makes no sense as markings, that's for things like tattoos and scars that are part of your body, not clothing. This should use the loadout system instead.

i already have a branch with underwear and socks and clothing slots, loadouts included :godo:

**Comment by BolloTea** [comment]
> > This makes no sense as markings, that's for things like tattoos and scars that are part of your body, not clothing. This should use the loadout system instead.
> 
> i already have a branch with underwear and socks and clothing slots, loadouts included :godo:

unexpectedly from you.  But, we are waiting for this PR)

**Comment by SlamBamActionman** [comment]
Hello! The PR was put up to a maintainer vote which concluded with the following result: Merge, with changes.

The reason it has taken so long to come back with a result is due to this feature being important when it comes to the user experience regarding nudity. The maintainers do not want to put emphasis on nudity (strict ERP rules are there for a reason) and we believe making underwear a fashion choice would strengthen that. But at the same time it is an accessibility issue if players feel uncomfortable due to their characters being naked/made naked via game mechanics. We feel this PR is a step in the right direction to give players control over this, but maintainers raised some feedback we'd like to see before this gets merged.

1. Only the following underwear should be considered:
  - Underwear (Briefs)
  - Underwear (Default)
  - Underwear (Satin)
  - Bra (the classic version)
  - *new: Tanktop 
  - *new: Binder

2. Underwear should not be colorable; this change should be possible via yaml.

3. The sprites should be slightly less bright in their whiteness. Refer to white jumpsuit sprites for an appropriate color. 

With these changes we are also creating a Github issue for a client-side nudity toggle feature request, but that is outside the scope of this PR.

**Comment by Dutch-VanDerLinde** [comment]
> Hello! The PR was put up to a maintainer vote which concluded with the following result: Merge, with changes.
> 
> The reason it has taken so long to come back with a result is due to this feature being important when it comes to the user experience regarding nudity. The maintainers do not want to put emphasis on nudity (strict ERP rules are there for a reason) and we believe making underwear a fashion choice would strengthen that. But at the same time it is an accessibility issue if players feel uncomfortable due to their characters being naked/made naked via game mechanics. We feel this PR is a step in the right direction to give players control over this, but maintainers raised some feedback we'd like to see before this gets merged.
> 
> 1. Only the following underwear should be considered:
> 
> * Underwear (Briefs)
> * Underwear (Default)
> * Underwear (Satin)
> * Bra (the classic version)
> * *new: Tanktop
> * *new: Binder
> 
> 2. Underwear should not be colorable; this change should be possible via yaml.
> 3. The sprites should be slightly less bright in their whiteness. Refer to labcoats sprites for an appropriate shading.
> 
> With these changes we are also creating a Github issue for a client-side nudity toggle feature request, but that is outside the scope of this PR.

1. Whats a binder
2. does the 'Only the following underwear should be considered:' mean only those underwear are kept in the PR?

**Comment by SlamBamActionman** [comment]
> 1. Whats a binder
> 2. does the 'Only the following underwear should be considered:' mean only those underwear are kept in the PR?

1. A binder (or chest binder) is a top undergarment that compresses the chest area. They tend to look like a tank top but cut off above the belly-button.

2. Yes; shirts had pushback from maintainers due to readability (they take up a lot of space in the top area to the point of just being regular clothes, and the size can impact readability), and the other sprites lean more into fashion alternatives.

**Comment by EthanQix** [comment]
Make sure white boxers with red hearts are the default underwear option

**Comment by Dutch-VanDerLinde** [comment]
> > 1. Whats a binder
> > 2. does the 'Only the following underwear should be considered:' mean only those underwear are kept in the PR?
> 
> 1. A binder (or chest binder) is a top undergarment that compresses the chest area. They tend to look like a tank top but cut off above the belly-button.
> 2. Yes; shirts had pushback from maintainers due to readability (they take up a lot of space in the top area to the point of just being regular clothes, and the size can impact readability), and the other sprites lean more into fashion alternatives.

how come sports/strapless bras and lowrides were not considered?

**Comment by SlamBamActionman** [comment]
> how come sports/strapless bras and lowrides were not considered?

We want to keep the number of underwear low. Those other options are sorta in the same areas as the ones we listed as desirable.

We're aiming for "Do I have an option available that I feel OK with my character wearing?" rather than "Which of these similar options suit my character the most?", to avoid emphasizing the underwear.

**Comment by Tunguso4ka** [comment]
Woah, nice PR :godo:

And thats kinda sad that underwear will not have color chooser...

**Comment by UbaserB** [comment]
Are you coming back to this?

**Pull request closed without merging**
