### PR TITLE
Magazine Refactor: Fixes one issue in #28880

### PR DESCRIPTION
**Pull request by Keer-Sar**
## About the PR

- Changed the entry in the syndie-uplink for the surplus rifle to be the Kardashev-Mosin and put "surplus rifle" in its description.
- Fixed the entry in the syndie-uplink for the SMG magazine.
- Removed "any" from the empty magazines and put "lethal" on magazines that are full of bullets
- Created new sprites for magazines using the same sprite
- Created new mags for ammunition that didn't have a magazine for it yet
- Fixed the SMG magazine (.35 auto rubber). It was labeled and colored for rubbers but had uranium ammo in it.
- Changed SMG pistol magazines from a removed gun to be High-capacity pistol mags to hopefully be added to the game later.
- Added sprite for Uranium, practice, and empty Bulldog drum magazines.
- Renamed shotgun drums to Bulldog ammo drums
- Added Lecter to the name for magazines used in the lecter rifle
- Added AKMS to the name of magazines used in the AKMS light-rifle
- Alphabetizes the entries in the meta.json for boxes.rsi
- Fixed the empty pixel of a bullet that's supposed to be at the bottom of pistol mags

## Why / Balance

There's too much inconsistency with most magazines in the game right now. See #28880 for an example. Now, all weapons except the WT550 and Cobra have the 5 main different magazine colors/types. 
- None (Blank)
- Lethal (Red) 
- Practice (White) 
- Incendiary (Orange) 
- Uranium (Green)

While this PR does create magazines and ammo boxes, the PR doesn't add a way for players to obtain the new items.

This all started when I was just trying to figure out the cause of the bug in #28880 which I DID FIND but couldn't fix. Then, when I looked to see if the bug happened to any other magazines, I saw how mags-variants were missing from some guns while others had 6 different variants.
## Technical details

There should be no changes to code other than sprites and yaml files. 
## Media

Current picture of how things are right now: 
image

After the PR:
Screenshot 2024-06-22 024454

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## List of To-Do's (My check-list while working over the week on this)

- [X] Fix the surplus rifle in the uplink to show the item's real name.
- [X] Fix the SMG mag entry in the uplink
- [x] Add "lethal" to the default magazines used in job prototypes
  - [X] Mk58 mags
  - [X] WT550 mags
  - [X] SMG mags
  - [X] Lecter mags
  - [x] AKMS mags
  - [x] Viper mags -> Uses Mk58 mags, not machine pistol mags
  - [x] N1984 mags
  - [x] Bulldog mags
  - [x] Cobra mags
  - [x] Speed Loaders
  - [x] Vector mags
  - [x] Machine Pistol mags
- [x] Remove the "any" part of any magazines.
- [x] Create/Edit sprites for duplicate mags.
  - [x] Make .20 rifle incendiary mags use a different sprite
  - [x] Make pistol magazine (.35 auto incendiary) use a different sprite
  - [x] Make speed loader (.45 magnum incendiary) use a different sprite
  - [x] Make ammo drum (.50 incendiary) use a different sprite
  - [x] Make magazine (.30 rifle incendiary) use a different sprite
  - [x] Make all practice ammo mags use white for their color
  - [x] Make all incendiary mags orange (all ammunition boxes are white)
- [x] Make practice ammunition boxes white
- [x] Make incendiary ammunition boxes orange
- [x] Fix SMG magazine (.35 auto rubber) to be uranium. (The thing holds and is sprited for uranium)
- [x] Change machine pistol magazines to Extended Pistol magazine
  - [x] Add Uranium magazine for Extended Pistol mags
  - [x] Add Incendiary magazine Extended Pistol mags
- [x] ~Change pistol magazines to Mk58 magazine~
- [x] Add Uranium magazine for ammo drums
- [x] Add Practice magazine for ammo drums
- [x] Add Incendiary magazine for SMGs
- [x] Change magazine to Lecter magazine
- [x] Change light-rifle magazine to AKMS magazine
- [x] Change ammo drums to Bulldog ammo drums
- [x] ~Remove Bulldog ammo drum recipe from sec techfab (they're in the emag'd autolathe already and no security shotgun has a magazine)~ -> out of scope, could have unforeseen consequences
- [x] Remove machine pistol magazine (.35 auto rubber)
- [x] ~Remove WT550 magazine (.35 auto top-mounted any)~ Needed in secfab to craft empty mags
- [x] ~Give magazine boxes unique sprites~ -> To-do in separate PR
  
## Final things To-Do
- [x] Fix "any" magazines appearing empty when full
- [x] Fix all top-loaded magazines to appear full until empty. (Ammo drums & WT550) -> issue with ContentHelpers.RoundToLevels()
- [x] Fix ammo boxes looking empty when they still have any ammo in them -> issue with ContentHelpers.RoundToLevels()
- [x] Fix SMG magazine (.35 auto any) from having 35 rounds to 30
- [x] ~Move magazine types into their description.~ -> Requires changes in c# 
- [x] ~Double check all modified objects and make required entries in migration.yml~ -> nothing was changed

## Breaking changes

**Changelog**

🆑 
- tweak: The Surplus Rifle in the syndicate uplink is now the weapon's proper name.
- fix: A spelling mistake in the uplink for the SMG magazine was fixed.
- fix: Variant magazines for all weapons have been changed to all have distinguishable colors.
- tweak: Magazines for the Lecter are now named Lecter magazines.
- tweak: Magazines for the AKMS are now named AKMS magazines.
- tweak: Machine Pistol magazines are now named High-capacity pistol magazines.
- tweak: Ammo drums are now named Bulldog ammo drums.
- fix: The SMG magazine (.35 auto any) now correctly has space for 35 cartridges instead of 30.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
thats an absolutely massive changelog wtf

**Comment by beck-thompson** [comment]
Massive changelog but makes sense I guess 😆

**Comment by RiceMar1244** [comment]
Why label the magazines for specific guns?

**Comment by Plykiya** [comment]
my hero

**Comment by Plykiya** [comment]
fwiw the "Empty" suffix doesn't show up in the lathe name, just the spawn menu, which is kinda annoyinf

**Comment by IProduceWidgets** [comment]
If you have extra time after all that, one that's always bothered me is the pistol mags appearing to have an empty at the bottom when they are full.

**Comment by IProduceWidgets** [comment]
Yeah!

**Comment by RiceMar1244** [comment]
> > Why label the magazines for specific guns?
> 
> Every magazine in the game only works for one gun at the moment. The only exception being SMG magazines working with both Droidz and C-20s.
> 
> In real life, magazines for any gun are usually made to work with their own gun. It's rare to find a magazine that works for multiple guns. And those that do either work well, have feed-problems, fall out of the magwell unless you hold it, or slide in completely but dont work at all.

Right, and usually i am an advocate for following the realism in some situations because it can lead to very natural solutions that 'just click' kind of like how things tend to in real life. Its just that in my own opinion, im not sure what strictly assigning each mag to a gun would do, even if purely in name. Ill note that each of the battery powered devices in the game use the same standardized power cells no matter what company makes the gadget.

**Comment by Plykiya** [comment]
> > fwiw the "Empty" suffix doesn't show up in the lathe name, just the spawn menu, which is kinda annoying but understandable why it doesn't show up
> 
> dang it you're right, now i gotta figure out how to get lathes to show suffixes else the only way to differentiate them will be by their sprites

yeah, that's exactly the problem I had when I was working on adding all the mags
I don't know if the maintainers want suffixes to be visible to players since the only place I know of that shows it is the spawn entity menu

**Comment by Plykiya** [comment]
alright I got confirmation from maintainers that suffixes aren't even meant to be shown to the user, but also said if you want suffixes to add them in the lathe code itself

**Comment by Cojoke-dot** [comment]
mmm... tranq drums? They got their new fancy teal sprites that would look good on a drum

**Comment by thebadman4662** [comment]
> You can't get tranqs as a syndie, I think printing bulldog mags at a sec-fab is wrong anyways as well.

Whole boxes of shells do not fit into secbelt/webbing and after nerfs you really gotta make use of it somehow...

**Comment by Plykiya** [comment]
this might be a bad time to bring this up but can you make mags use the color attribute rather than making a new sprite for each mag that uses a different color line?

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/pull/26943

**Pull request closed without merging**
