### PR TITLE
Replicate the PDA belt slot sprite in the IDSLOT

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
Requires #21456

## About the PR

Adds the belt equipped sprite to the PDA for the IDSLOT.

image

**Changelog**

### CODE REVIEW

**Comment by UbaserB** [comment]
Can you make it less bright? Right now it stands out a lot….

**Comment by Subversionary** [comment]
Can you make it less bright? Right now it stands out a lot….

**Comment by EmoGarbage404** [comment]
I think showing the PDA on the player is just kinda pointless? The sprite doesn't really accurately reflect what they look like and players wear PDAs 99% of the time anyway. It just kinda looks like visual noise.

**Comment by QuietlyWhisper** [comment]
> I think showing the PDA on the player is just kinda pointless? The sprite doesn't really accurately reflect what they look like and players wear PDAs 99% of the time anyway. It just kinda looks like visual noise.

it's not a new sprite, it's literally the belt slot sprite in game right now. If that's the case consider removing that all together then, no?

**Comment by Emisse** [comment]
This literally already exists now except this adds same functionality to belt slot, that said I still think it's ugly and we should probably make equipped sprites for pdas.

**Pull request merged**
