### PR TITLE
Syndicate Lobbying Bundle (briefcase with spacebucks)

### PR DESCRIPTION
**Pull request by lapatison**
## About the PR

 
**Media**

Screenshot_1

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Syndicate lobbying bundle: briefcase containing 5,000 spacebucks has been added to the uplink!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
30,000 bucks for 1 TC is ludicrous

**Comment by Aisu9** [comment]
> 30,000 bucks for 1 TC is ludicrous

time for another gimmick Traitor purchase at 20TC?

**Comment by lapatison** [comment]
> 30,000 bucks for 1 TC is ludicrous

Why tho? You can't put them in cargo console, for example, or do anything else. They are completely useless.

**Comment by EmoGarbage404** [comment]
> Why tho? You can't put them in cargo console, for example, or do anything else. They are completely useless.

wdym? you can sell them on the cargo shuttle for their equivalent value.

**Comment by lapatison** [comment]
> > Why tho? You can't put them in cargo console, for example, or do anything else. They are completely useless.
> 
> wdym? you can sell them on the cargo shuttle for their equivalent value.

Dayum. I didn't know that. Perhaps, 2TC for 5k would be better?

**Comment by KaiShibaa** [comment]
I'm curious what would this be used for

**Comment by EmoGarbage404** [comment]
i could see this being a pretty good item for bribing cargo, but IMO:
- the amount needs to be balanced so that you can't completely invalidate other forms of money making
- the briefcase and/or cash itself needs to be obnoxiously valid looking. I feel like cargo should know that taking 5k off of a suspicious looking guy is a syndie ploy.

**Comment by Aisu9** [comment]
wouldn't this make for a good cargo tech only item tho?
Unless there is cargo techy you must help to complete their objectives(or the other way around) i really don't see any uses from this purchase
(Let's be honest salvage don't need this one with all the weapons they hoard)

**Comment by asperger-sind** [comment]
How would the current ruleset and player mentality handle this? Wouldn't accepting a syndicate briefcase fall under "cooperation with a syndicate member", and wouldn't players just go "HOLY SHIT SYNDIE BRIEFCASE RED ALERT CONFIRMED SYNDIES ON BOARD" upon seeing a briefcase with $30,000

**Comment by Emisse** [comment]
im thinking traitor supply are just gonna buy tons of these and sell them all

**Comment by deltanedas** [comment]
new cargo meta

**Comment by Partmedia** [comment]
In the future, it would be best if unrelated changes (e.g. to capitalization of other items) are separate commits, so that if reverts need to happen they can happen individually.

This sounds pretty amusing and would be fun if we could come to an agreement on the numbers.

**Comment by lapatison** [comment]
I don't think it would be a good idea to make it job-specific. I also increased the price of the item to 4TC for 5000 spacebucks, /tg/station-like.
What else can I do to balance it out?
> In the future, it would be best if unrelated changes (e.g. to capitalization of other items) are separate commits, so that if reverts need to happen they can happen individually.

Noted

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by EmoGarbage404** [comment]
i think this is pretty fun. 5k is reasonable for 4TC and there's some interesting roleplay/bribe opportunities that can arise out of this.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
