### PR TITLE
Convert all textures to RGB

### LINKED ISSUE #9955: Some textures are in RGB color and some are in Indexed color
## Description

end my fucking suffering.
convert to rgb.
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Converted all textures to RGB.

## Why / Balance
Resolves #9955.

## Technical details
Instead of changing 16.539 files by hand, I just created a python script :trollface: 

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

None.

### CODE REVIEW

**Comment by UbaserB** [comment]
what the actual heck is this

**Comment by EmoGarbage404** [comment]
Helllll yeah brother

**Comment by Winkarst-cpu** [comment]
> what the actual heck is this

Hell :trollface:

**Comment by mierdapovareshka** [comment]
бля чё это за говно ебаное

**Comment by Winkarst-cpu** [comment]
> бля чё это за говно ебаное

Приколы.

**Comment by PJB3005** [comment]
Uh, I don't see the point of this? Isn't it like two button presses to tell your image editor to disable indexed color if you're working on it?

**Comment by mirrorcult** [comment]
image

I believe I've discovered the issue with this PR

**Comment by Winkarst-cpu** [comment]
Guys, this PR goes to hell. Will do a new one...

**Pull request closed without merging**
