### PR TITLE
Emag nerf

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 

**Screenshots**

**Changelog**

:cl: Rane
- tweak: Emags no longer force open bolted or unpowered doors.
- tweak: Emags no longer work on the ID console.

### CODE REVIEW

**Comment by moonheart08** [comment]
This isn't the nerf we really want.
Emags should not open doors, period, and _especially_ should not be unlimited AA.

**Comment by Fishfish458** [comment]
> This isn't the nerf we really want. Emags should not open doors, period, and _especially_ should not be unlimited AA.

I don't really see an issue with it's limited ability to open doors at this time since there's a lot less things that can actually be emagged for benefit right now. Later down the line its door opening ability can be brought into question though I think it's a bit early. It should be limited in its ability to do so though.

**Comment by Elijahrane** [comment]
Can we get a "needs discussion" tag

**Comment by Elijahrane** [comment]
Summary of my arguments:
1. The bolt change introduces counterplay. Now, someone emags into a sensitive area, it's a skill issue on behalf of the head of that department for not bolting the door.
2. The ID console change introduces some niche protection for the Agent ID card, which should naturally add more variety in traitor purchases.
3. The emag already has a decent bit of resource management because time is a resource. If you waste a bunch of time waiting on recharges, that's more time for people to put things together and catch you and more time for your objective to move somewhere you've lost track of.

**Comment by Fishfish458** [comment]
> make it have 0 charges on buy and let it build up to 3 charges. Creates more pressure on the emag user who now has to hold the contraband around and doesn't get the immediate uses of it, and as Rane has said. **Time is a valuable resource.**

I do like that, it would keep people from rushing at the start.

**Comment by Elijahrane** [comment]
> > make it have 0 charges on buy and let it build up to 3 charges. Creates more pressure on the emag user who now has to hold the contraband around and doesn't get the immediate uses of it, and as Rane has said. **Time is a valuable resource.**
> 
> I do like that, it would keep people from rushing at the start.

I'll add it in a bit, that's a more elegant way to prevent rushes than other ones I was thinking of.

**Comment by TimrodDX** [comment]
This is a very, very bad idea. I think it's also emblematic of this bizarre "childproofing" thing everyone wants to do for some reason (see: recent nerfs to deconstruction) that go against the entire idea of what SS13 is. It's also incredibly short-sighted, to the point where I would consider this one of the worst changes to the game short of the time /tg/ banned antags from killing people.

First, doing this is only going to further invite metagaming. As it stands, I've seen too many rounds where the heads withdraw their magic door wands from their lockers and use them to bolt anything that might be broken into - I can't tell you how many times I've seen the doors to EVA and the gravity generator bolted by the HoP in the first thirty seconds of the game. It will shoehorn traitors into buying either the toolbox or the bag of C4, which is also a bad idea because the whole point of being an antag is that you're given room to experiment. There's a reason that telecrystals and the uplink exist, after all.

As to your argument that the Agent ID Card and C4 aren't useful, they are - they're just both situational. C4's entire purpose is to force a shuttle call by blowing holes in the station (while not having to be near those holes and not having to lug a hardsuit around) or destroying power infrastructure. The ID card also has its uses, but isn't meant to be a required purchase.

Second, you have the problem of future content - specifically Nuke Ops. Nuke Ops need the element of surprise to be effective, and because of that need the emag to quickly get in and out of places. It's why some servers go so far as to spawn an emag on the nuke shuttle, specifically to ensure the round doesn't become unwinnable if someone forgets to buy one. This will also invite metagaming in the form of the heads now bolting every external airlock at round start to prevent the ops from getting in, as they'd now have to lug tools around or waste a bunch of time hacking through every door on the station.

I think at a minimum, I would need to see the following questions answered:

- Why is this good for the game?
- Why is this nerf necessary? What data are you basing the need for this on?
- What do you plan to do to stop the heads from bolting everything each round, unprovoked?
- How would you ensure that Nuke Ops remain playable? 
- How do you respond to the fact that C4 would now be a mandatory purchase?
- How would traitor objectives be adjusted to account for this?

**Comment by Elijahrane** [comment]
> I think at a minimum, I would need to see the following questions answered:
> 
>     * Why is this good for the game?
Less cancer nerf than the proposed alternative IMO.


>     * Why is this nerf necessary? What data are you basing the need for this on?

I've been told the emag is getting nerfed no matter what, even though I don't think it's too bad besides the id console interaction. No data, but I'd be interested in seeing some.

>     * What do you plan to do to stop the heads from bolting everything each round, unprovoked?

Is locking your doors metagaming? Do you never lock your doors IRL because you don't want to metagame any burglars?

>     * How would you ensure that Nuke Ops remain playable?

None of the door remotes can bolt external doors.
>     * How do you respond to the fact that C4 would now be a mandatory purchase?

I thought emag was supposedly mandatory now? And you'd probably have better luck with just a toolbelt if it's a quiet enough area.

>     * How would traitor objectives be adjusted to account for this?

I don't think there's been much consideration of traitor objectives at all considering even our best traitors have an abysmal redtext rate, but I wanted to meet the demand for a nerf.

**Comment by EmoGarbage404** [comment]
I think the bolting interaction being solved by emag isnt that bad. Bolted doors still have a variety of ways to bypass them. I think while the emag does need a slight nerf, there probably just needs to be more useful items that can be purchased by Traitors that fit into the same general playstyle as the emag. Id prefer if more options for traitors were introduced rather than their options further limited.

**Comment by BlitzGunner225** [comment]
Like I said before getting aa is pretty easy with the emag, and with its other million uses, the agent id gets completely invalidated even with its lower price. 
The agent I’d has a far more interesting and challenging way of getting more access and the emag being able to hack id computers is pretty op anyways

**Comment by freeman2651** [comment]
Illicit access to a location is just one of many options a traitor has to go about getting to an objective (if their objective is even in the armory, for instance). If your target has bolted and locked the doors up tight on your target, you might want to think about alternative strategies like just hacking in, getting access, securing a door remote, or going around the door through a wall. These alternative ways are naturally, more risky, take more time, or may outright blow your cover, but that's part of the game. Its not really any fun if traitors can just emag their way into whereever they want when nobody is looking for 30 seconds.
The Emag has always had the problem of being far too useful to pass up because it was an instant skeleton key into anywhere with access restrictions, plus developers could not resist turning way too many mundane machines into something insanely dangerous when swiped with one, further bolstering how useful it can be.

**Comment by Fishfish458** [comment]
> Like I said before getting aa is pretty easy with the emag, and with its other million uses, the agent id gets completely invalidated even with its lower price. The agent I’d has a far more interesting and challenging way of getting more access and the emag being able to hack id computers is pretty op anyways.

The agent ID and emag live in the same area but definitely don't step on each other toes since one copies access and acts as a fake ID to access an area and the other one noisily breaks open the door and bolts it in a very obvious non-stealthy way.

If someone was being a detective and saw the vault wide open and bolted they would absolutely check for what's stolen vs someone who acquired the access, went in and out with the door still intact.

**Comment by BlitzGunner225** [comment]
> > Like I said before getting aa is pretty easy with the emag, and with its other million uses, the agent id gets completely invalidated even with its lower price. The agent I’d has a far more interesting and challenging way of getting more access and the emag being able to hack id computers is pretty op anyways.
> 
> The agent ID and emag live in the same area but definitely don't step on each other toes since one copies access and acts as a fake ID to access an area and the other one noisily breaks open the door and bolts it in a very obvious non-stealthy way.
> 
> If someone was being a detective and saw the vault wide open and bolted they would absolutely check for what's stolen vs someone who acquired the access, went in and out with the door still intact.

You can get aa in like 3 seconds by breaking into command or hop and hacking the ID console

**Comment by Fishfish458** [comment]
> You can get aa in like 3 seconds by breaking into command or hop and hacking the ID console

which is exactly an issue this pr is aiming to fix currently

**Comment by freeman2651** [comment]
> You can get aa in like 3 seconds by breaking into command or hop and hacking the ID console

That hopefully comes with the obvious risk of getting caught, but since its LRP that's not always the case. The agent ID still has its niche which is copying over access from any cards you find.

**Comment by ike709** [comment]
> tweak: Emags no longer force open bolted or unpowered doors.

Worth noting that in SS13 (at least on some servers) emagging a bolted door makes it impossible to ever open again short of deconstructing & reconstructing it. Makes it good for denying access to specific rooms without tools, among other things.

**Comment by moonheart08** [comment]
Ok so as far as I can tell, this is a very point-making-y way of saying "no, i don't like your proposed nerf you're not even doing yet because it'd cause an imbalance". Please actually discuss and figure out the details of this, because this ain't the way. You've successfully gimped the emag into uselessness, and I guess successfully made your """point""" about how any nerf at all is a really bad thing.

**Comment by Elijahrane** [comment]
> Ok so as far as I can tell, this is a very point-making-y way of saying "no, i don't like your proposed nerf you're not even doing yet because it'd cause an imbalance". Please actually discuss and figure out the details of this, because this ain't the way. You've successfully gimped the emag into uselessness, and I guess successfully made your """point""" about how any nerf at all is a really bad thing.

Do you really have to read the worst into everything? It's been discussed a lot today and people have said even with these changes they'd still buy emag every round so it's apparently not too useless.

**Comment by Fishfish458** [comment]
> You've successfully gimped the emag into uselessness, and I guess successfully made your """point""" about how any nerf at all is a really bad thing.

So things are heated I guess, everyone has their own opinion on it, though I'm kind of curious what yours is. What regarding the proposed nerfs gimps it into uselessness?

**Comment by moonheart08** [comment]
> > You've successfully gimped the emag into uselessness, and I guess successfully made your """point""" about how any nerf at all is a really bad thing.
> 
> So things are heated I guess, everyone has their own opinion on it, though I'm kind of curious what yours is. What regarding the proposed nerfs gimps it into uselessness?

You can have your cake and eat it too if you literally just make it an expendable item. I don't know why spending, idk, 4TC for 4 charges and getting everything the emag offers as-is is such a big deal. This PR was made because Rane didn't like that option.

**Comment by Elijahrane** [comment]
> You can have your cake and eat it too if you literally just make it an expendable item. I don't know why spending, idk, 4TC for 4 charges and getting everything the emag offers as-is is such a big deal. This PR was made because Rane didn't like that option.

Expendable utility items don't feel good IMO. What problems are we attempting to solve with any emag nerfs? I've listed a few but I'm interested to know what ones I might have forgotten.

**Comment by Fishfish458** [comment]
What if we were to go the route that TG took now in terms of splitting the emag and airlock override card into different items?

**Comment by Elijahrane** [comment]
> IMO I believe the base emag's utility of unlocking functions of various devices is built on experimentation 
Also this is the main complaint with limited charges, any fun but suboptimal interactions would barely get used because you need to save your charges to open a locker

**Comment by moonheart08** [comment]
I doubt the people interested in doing cool things are going to be roadblocked by opening a single locker.

**Comment by Elijahrane** [comment]
I also feel like making it expendable doesn't solve most of the problems people have brought up with the emag. Such as:
1. Emag rushing in the first few minutes is pretty stupid (that just makes it quicker, worse, and with more TC left over for violent means of overcoming any resistance.
2. Emags invalidate most of the other B+E traitor items (it really doesn't change the calculus on what to buy other than having more TC available)

I'm not even sure which problem it's supposed to solve, tbh

**Comment by optimumtact** [comment]
The 3 charges was a deliberate design choice FYI, the goal was to use the device for a high noise breakin to a specific area of a department, and/or an emergency fast escape if a stealth burglary went bad.

3 charges is about the right number to get you through a dept maint door, into a specific room and then one charge for any emergency situations to come up.

**Comment by Elijahrane** [comment]
> 3 charges is about the right number to get you through a dept maint door, into a specific room and then one charge for any emergency situations to come up.
> 
> Reducing it to one makes using it as a fast getaway tool much more difficult.

luckily I never actually pushed that, I stand by the changes in the original commit though

**Comment by optimumtact** [comment]
Well you don't have to change things just because I said, just offering some perspective.

**Comment by Elijahrane** [comment]
wasn't quite sure what to with the charges, I'm kind of liking the suggestion someone brought up in the discord of making them use the same rechargers batteries, tasers etc use

**Comment by Fishfish458** [comment]
> not quite sure what to with the charges, I'm kind of liking the suggestion someone brought up in the discord of making them use the same rechargers batteries, tasers etc use

Would be interesting though for some situations it could reduce the amount of time between charges if they're crafty enough.

**Comment by Fishfish458** [comment]
Though going back to the very beginning, this PR is purely a nerf against a capability the emag has currently. would it be agreeable to create another discussion regarding handling it or is it to be handled here and now?

**Comment by Elijahrane** [comment]
> Though going back to the very beginning, this PR is purely a nerf against a capability the emag has currently. would it be agreeable to create another discussion regarding handling it or is it to be handled here and now?

IMO what I would like now is to discuss the two current changes, test them, and if emag is still overtuned come up with some sort of change for charging later.

**Comment by PJB3005** [comment]
The fact that the emag even affects the ID console right now is absurd. This should just be merged either way.

**Comment by UKNOWH** [comment]
If this is merged , can we add an "airlock permit overwriter" which functions like an old emag on doors that is sold for 2 TC

**Comment by UKNOWH** [comment]
Or 4 TC , because it fuctions as a quiet c4 charge

**Comment by Fishfish458** [comment]
> If this is merged , can we add an "airlock permit overwriter" which functions like an old emag on doors that is sold for 2 TC

probably best to move this to a separate discussion place

**Review by ShadowCommander — APPROVED** [review]
Current code looks fine. Haven't read the full discussion, but that can be discussed after this nerf.

**Review by mirrorcult — APPROVED** [review]
im fine with these initial nerfs, we can decide if it needs more after

**Pull request merged**
