### PR TITLE
floor recharger examine charge rate

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
how it was before:

this just floors it

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by juliangiebel** [comment]
> why not 36W or 36,7W?

That's exactly what this PR does

**Comment by deltanedas** [comment]
this pr changes it to be 36W
cbf to do the / * thing and its not really important

**Comment by Kit0vras** [comment]
> this pr changes it to be 36W cbf to do the / * thing and its not really important

Ahhh, sorry, I'm stupid
from the picture it was not to understand

**Comment by deltanedas** [comment]
screenshot was just the previous behaviour

**Comment by deltanedas** [comment]
test fail erroneous

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
