### PR TITLE
Playing Cards

### PR DESCRIPTION
**Pull request by Fishfish458**
## About the PR 

Opening this as a draft because I could use some input on the UI, particularly displaying sprites of the cards themselves in it and if it's possible in an efficient manner as well as any input on if there's any better way of handling the sprite layers

I know that at the very least I can trim the base card layer away from the current card files and will do that, as far as actually setting the color and suite as seperate layers, I could also use advice on a way to handle that across different kinds of playing cards.

If this makes PR status and merged then after this comes implementing all the other kinds of decks.

LEFT TODO:

- [x]  Fix bug with taking out a card from hand when you're holding one already
- [ ] Clean up card hand UI a bit more and if possible include actual card sprites in it
- [x] Seperate card layers into a detail and base layer at the very least.
- [ ] Whatever the heck is going on with appearance component and pockets
- [ ] Final cleanup

**Screenshots**

go fish

shuffling and pickup

ui

### CODE REVIEW

**Comment by Willhelm53** [comment]
Great work! One of the tests seems to not like spaces in your filenames. Seems to be the `.png`s

**Comment by Fishfish458** [comment]
> Maybe you just extend tabletop framework? I'm not sure about creating two separate systems for cards and all other tabletop games.

the playing card system should be separate and open because of how diverse the use of cards are.
separating them makes players able to look at their own cards with with no risk of cheating.
allows for making deck building games where players can get randomized packs and mix them in.
allows for syndicate playing cards to be used as throwing weapons which they had previously.
allows for the magic tarot cards which were able to create summonables depending on the card.

I do think most other games should be using the same the board game system when both players should be seeing the same thing though.

**Comment by Fishfish458** [comment]
> 

I really don't see how binding them to the tabletop will allow for a better UX and less systems since it will still need to have the all the same functionality of picking up cards, deleting cards by adding them to the deck, shuffling decks, grabbing cards from your hand and being able to flip them privately. There is no ability to examine either to determine card count.

**Comment by Fishfish458** [comment]
Closing this for now since this is lowest priority for me currently and I don't like having open prs/drafts that aren't active.

Still believe it shouldn't be part of tabletop system but will flesh it out more once I get some other stuff done.

image

**Pull request closed without merging**
