### PR TITLE
argocytes

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

adds argocytes for future colony stuff.

i embark on ai shenanigans in a future pr.

credit to aleksh for sprites
## Why / Balance

fun
## Technical details

i made yet another simplemob parent. kill me.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

no cl no fun

### CODE REVIEW

**Comment by mirrorcult** [comment]
the splunkies

**Comment by MrGreen006** [comment]
Really love how alien they look. Real goofballs

**Comment by UbaserB** [comment]
this is insanely cool im so excited i so want this so much omg

**Review by mirrorcult — APPROVED** [review]

**Comment by UbaserB** [comment]
How do you get ferrochromic acid

**Comment by EmoGarbage404** [comment]
> How do you get ferrochromic acid

slaying argocytes

**Pull request merged**
