### PR TITLE
Mirror speed penalty for worn duffels and hardsuits when in-hand

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds ye olde feature Emisse asked for ages ago.
Mirrors the speed penalty from ClothingSpeedModifier with a new HeldSpeedModifier.

## Why / Balance

The speed penalties for both duffels and hardsuits are trivial to bypass. By simply holding it in your hand, you can ignore an up to 50% speed penalty with the only risk being slipping, something that's also trivial to bypass by just instantly equipping the item.

By adding the penalty when held, not just when worn, you actually have to think about the tradeoffs of the penalty instead of just holding it in your hand and sprinting at full speed and little consideration for much else.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Speed penalties for duffels and hardsuits now apply when held, not just when worn.

### CODE REVIEW

**Comment by asperger-sind** [comment]
Pretty sure there was an attempt to implement this before and the consensus was that having the item in-hand is a fair tradeoff despite the mali of having a slowing item in-hand. You have to consider that the reaction timeframe isn't great enough for most players to instantly equip the item upon slipping, just as it isn't great enough to start walking instead of sprinting, getting slipped in combat or in any other way by surprise when the slippery object comes out before you can notice it or before your actions get through ping is also a factor that has to be considered.

There are also problems as such people potentially disarming you and stealing the item, and being effectively one-handed while carrying the item, people deliberately slipping you to get ahold of your item (see: security open carrying batons), and potentially many more.

I think it's fair to allow a player to wear an item that would slow them down in-hand without incurring the speed malus due to the above described risks the player would take, the changes of this PR are probably fine in a vacuum where you're the only player on the server, but in a multiplayer game where players can be admittedly selfish or antagonistic this just removes a perfectly fine mechanic.

**Review by Brandon-Huu — CHANGES_REQUESTED** [review]
delete this

**Comment by Brandon-Huu** [comment]
So now people can have their move-speed reduced by 75% for wearing and holding a hardsuit?

**Comment by Aisu9** [comment]
does it cover when you are dragging them too?

**Comment by EmoGarbage404** [comment]
> does it cover when you are dragging them too? because people will 100% work this around by dragging them with their hand or tail

if you're dragging it around you're sacrificing a hand slot if you're not a lizard and it's also extremely vulnerable to just being plucked off of the floor. you lose all of the security of holding it in your hand while also keeping all of the same risks of getting slipped or interrupted in various ways.

**Comment by Partmedia** [comment]
Thanks for the bug fix. I think it's pretty clear that an item that is supposed to encumber you when worn should probably encumber you carrying it around.

I noticed that the values set for `HeldSpeedModifier` mostly duplicate numbers already set in `ClothingSpeedModifier`. Since the purpose of this change is to eliminate any discrepancy between a worn vs. held encumbrance, I suggest that `HeldSpeedModifierSystem` use the `ClothingSpeedModifier` values by default, and perhaps only use the `HeldSpeedModifier` if needed. Or just eliminate `HeldSpeedModifier` entirely. That way, `ClothingSpeedModifier`s obscured through, e.g. inheritance, don't start falling out of date with `HeldSpeedModifierSystem`. If however you believe it's important to carry around a second set of `HeldSpeedModifier`, that's also fine, in which case let me know and I'll merge.

**Comment by asperger-sind** [comment]
> > delete this
>
> This is really not an appropriate tone for discussing a proposed change.

Pretty sure they were referring to their suggested changes in some way.

>I don't think this mechanic is designed around reaction timeframe, simply as a way to encourage players to not wear hardsuits all the time. If you would like to propose a time delay for equipping/unequipping heavy items, feel free to propose that in a separate issue/PR.

This isn't the point, the point is that Emo's reasoning for removal of this balance-wise doesn't make sense in a practical scenario; it isn't "trivial", as Emo put it, to prevent the loss of the item in-hand, by slipping or not. Otherwise people would never ever lose their in-hands items because they'd never slip or never get disarmed or however else they lose their items as-is. I've gone over this more in my first comment.

**Comment by Emisse** [comment]
Urge to speedmerge rising

**Comment by Terraspark4941** [comment]
Looking at the complaints, would it be viable to increase/decrease the inherited value by a set percentage for tradeoff balance? (Logic: Hardsuits encumber less because legs are no longer "held back" by the weight?)

**Comment by asperger-sind** [comment]
> Looking at the complaints, would it be viable to increase/decrease the inherited value by a set percentage for tradeoff balance? (Logic: Hardsuits encumber less because legs are no longer "held back" by the weight?)

I've thought of this compromise, and it is in my eyes indeed a valid solution, but I still don't think this is necessary.

**Comment by Brandon-Huu** [comment]
What would be the downside of merging ClothingSpeedModifierComponent and HeldSpeedModifierComponent then using a boolean flag to specify whether it should also slow when held?

**Comment by arimah** [comment]
I don't completely understand why hardsuits would slow you down when held in hand. I always imagined the slowdown was caused by them being harder to move your limbs inside of, due to being thick and bulky. With this change, transporting hardsuits kinda just becomes a chore. Imagine trying to get emergency EVA suits to a spaced area - might as well just drag a locker at that point. If they're lightweight to be carried in a single hand, they shouldn't slow you down considerably, imo.

The duffelbag thing I completely agree with however.

**Comment by JoeHammad1844** [comment]
> I don't completely understand why hardsuits would slow you down when held in hand.

it's called weight

**Comment by deltanedas** [comment]
emergency eva should be a bit faster when held, for emergencies

**Review by metalgearsloth — APPROVED** [review]

**Comment by Brandon-Huu** [comment]
I don't play SS-14 Anymore. 
But I would like to mention that a couple of weeks ago, might have been a month at this point.

Players were dragging hard suits inside of lockers instead of holding them because it is faster. ( i think )
Kinda weird

**Pull request merged**
