### PR TITLE
Remove Knightship

### PR DESCRIPTION
**Pull request by 20kdc**
## About the PR

That of moving twice in a direction to that it moves in such's orthogonal. - Knightship

It was never built to survive game updates. *Worse, it shows.*
Knightship is incapable of handling certain major game events like diseases and zombies, and it's been brought out of rotation for a while.

**Changelog**

:cl:
- remove: Knightship is officially deceased.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Rip to a legend

**Comment by Macoron** [comment]
Move it to salvage? Will need some rework though

**Review by PaulRitter — APPROVED** [review]
grafik

**Comment by 20kdc** [comment]
> Move it to salvage? Will need some rework though

Simply "moving it" would be a bad idea - salvage maps are supposed to follow certain guidelines to ensure they spawn properly and don't cause trouble

**Review by moonheart08 — APPROVED** [review]
o7

**Comment by PaulRitter** [comment]
marking it derelict so someone that is looking for old content to revive can find it incase it gets merged

**Pull request merged**
