### PR TITLE
Add explosive banana peel

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

It adds explosive banana peel

**Media**

Peek 2023-02-20 15-29

**Changelog**

:cl:
- add: added explosive banana peel to clown uplink (2 TC, 45 total damage)

### CODE REVIEW

**Comment by deltanedas** [comment]
even without stacking, this is **insanely** overpowered for 2 tc. should be at least 6 tc and combine ecplosions like cfl3 does to prevent stacking

**Comment by Slava0135** [comment]
> even without stacking, this is **insanely** overpowered for 2 tc. should be at least 6 tc and combine ecplosions like cfl3 does to prevent stacking

you need 2 of them to near crit a person (after slipping once they won't slip second time, if they are careful), and this is also assuming no armour

**Comment by Slava0135** [comment]
can't decide if this should be clown exclusive item, or should I add it to botanist and mime uplink as well

**Comment by deltanedas** [comment]
buy 10 of them to gib anyone who runs through a door

**Comment by deltanedas** [comment]
ok gib is exaggeration but its instant crit with less than a minute to live

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Way too powerful for only 2 tc (also i think it would be more interesting if this was just a reskinned mine without payload)

**Comment by Slava0135** [comment]
> Way too powerful for only 2 tc (also i think it would be more interesting if this was just a reskinned mine without payload)

reskined mine that is also slippery?

**Comment by AJCM-git** [comment]
yeah

**Comment by Slava0135** [comment]
i was thinking about just reskinning mine - explosion can't be too powerful because then slipping won't do anything.
also you won't be able to pick it up (feature?)

**Comment by AJCM-git** [comment]
>  i was thinking about just reskinning mine - explosion can't be too powerful because then slipping won't do anything.
> also you won't be able to pick it up (feature?)

My idea was that it should be a reskinned, slippery **unprimed** mine  that can carry a payload, bonus points if it indistinguishable from a normal nana except you can screwdrive it to open the panel for the payload which changes the sprite a little bit

**Comment by Slava0135** [comment]
> > i was thinking about just reskinning mine - explosion can't be too powerful because then slipping won't do anything.
> > also you won't be able to pick it up (feature?)
> 
> My idea was that it should be a reskinned, slippery **unprimed** mine that can carry a payload, bonus points if it indistinguishable from a normal nana except you can screwdrive it to open the panel for the payload which changes the sprite a little bit

there seem to be a bug, that you can't put payloads into spawned modular mines

**Comment by Slava0135** [comment]
it wasn't a bug, it just didn't show you need to add wires

**Comment by Slava0135** [comment]
Peek 2023-03-06 11-03
doesn't show up in construction menu for some reason

**Comment by Slava0135** [comment]
In order for this to be useful, we need more payloads (there is only chem, flash and explosive payloads + bike horn).
Maybe add some payloads to uplink?

**Comment by Slava0135** [comment]
(mine recipe doesn't require banana peel right now, but i will fix it a bit later)

**Comment by Slava0135** [comment]
added proper recipe
image

**Comment by Slava0135** [comment]
for some reason it skips wiredCase state (it doesn't need wire and proximity sensor)

**Comment by Slava0135** [comment]
i think there are not enough reasons for this to exist, you can just put peel on modular mine with similar effect

**Pull request closed without merging**
