### PR TITLE
French and Spanish traits

### PR DESCRIPTION
**Pull request by BackeTako**
## About the PR

Added French and Spanish as speech traits.

## Why / Balance

Now that we have seprate speach section to traits they can be added as discussed in #27129.
Could possibly raise the cost for any of them if deemed necesassy but one should be good for them.

## Media

Speach

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added French and Spanish speech traits.

### CODE REVIEW

**Comment by TheShuEd** [comment]
Can I ask you to sort them by cost?

**Review by slarticodefast — APPROVED** [review]

**Comment by Froffy025** [comment]
my life's work.. blessed day... thankyou forever

**Review by UbaserB — DISMISSED** [review]
Can you make the Russian accent not a trait?

**Comment by BackeTako** [comment]
> Can you make the Russian accent not a trait?

sure thing

**Comment by lzk228** [comment]
not a word in russian :trollface:

**Comment by BackeTako** [comment]
> not a word in russian :trollface:

no russian in here

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
Thank you for your contribution!

**Comment by lzk228** [comment]
probably because it would be a little chaos with all that cyrillic replacements

**Comment by UbaserB** [comment]
> excuse me, why?

a large proportion of raiders are russian and the trait will likely increase admin workload

**Pull request merged**
