### PR TITLE
Add syndicate satchels, nukies spawn with their backpack preference

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
requires #25715

## About the PR
title, and made syndicate backpack have 1 more row of storage to be in line with the syndicate duffel

made syndicate backpack 1 TC in the uplink since nukies get them for free

## Why / Balance
nukies spawn with their backpack preference is good cause all the other roles in the game have it like that
syndicate satchel added, since there's a backpack

## Media
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Syndicate satchels can now be bought in the syndicate uplink.
- tweak: Nuclear operatives now spawn with their backpack preference.

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
I don't know if I like this because as a nukie you normally need the storage space of the duffel and you can't know in advance if you will be a nukie. That said, if you buy any of the bundles you get a free one, so meh. Guess its fine.

**Comment by Dutch-VanDerLinde** [comment]
> I don't know if I like this because as a nukie you normally need the storage space of the duffel and you can't know in advance if you will be a nukie. That said, if you buy any of the bundles you get a free one, so meh. Guess its fine.

The backpack/satchel gets extra movement speed AND has 1 extra row of storage

**Comment by Dutch-VanDerLinde** [comment]
> What's wrong with using loadouts for this?

Nothing, could probably close until loadouts are merged

**Comment by Dutch-VanDerLinde** [comment]
> your branch seems uh a little messed up.

Yeah

**Pull request closed without merging**
