### PR TITLE
Add command to convert firelocks to double-edge

### PR DESCRIPTION
**Pull request by metalgearsloth**
This makes monstermos nicer to work with as you won't instantly space an area.

Given https://github.com/space-wizards/space-station-14/pull/16115 probably plays less nicely with that now so that might need adjusting.

### CODE REVIEW

**Comment by Emisse** [comment]
will firelockify convert every firelock or just ones in rows of 3

**Comment by Emisse** [comment]
also having to add the new firelocks to air alarms and fire alarms is going to make this redundant as you will have to go through every firelock again

**Comment by metalgearsloth** [comment]
> also having to add the new firelocks to air alarms and fire alarms is going to make this redundant as you will have to go through every firelock again

what if I scripted it.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
This really needs to transfer the device connections too

**Comment by metalgearsloth** [comment]
Will look at this + the other atmos stuff later.

**Pull request closed without merging**
