### PR TITLE
Fix StepTriggerImmune + Make Syndicats StepTriggerImmune

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Fix StepTriggerImmune so bots no longer have to deal with cutting themselves on glass shards + make it so you can't one-shot syndicates with mousetraps
## Why / Balance

#29782
## Technical details

`StepTriggerAttemptEvent` was never called on the thing stepping on the other thing, not it is
## Media

image
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Syndicats are no longer affected by glass and other simular floor events.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
bleh, this makes it so honkbots don't slip people... which makes sense why it was not like this before... syndicats also noslip sooo...

**Comment by Cojoke-dot** [comment]
> bleh, this makes it so honkbots don't slip people... which makes sense why it was not like this before... syndicats also noslip sooo...

oh wait... did not know the honkbot bug never got fixed, weird...

**Comment by Vermidia** [comment]
My PR is still up #27684 which fixes both

**Comment by Cojoke-dot** [comment]
> My PR is still up #27684 which fixes both

I see, sick, you got this then! uh... notes I found... I'll post them in your pr...

**Pull request closed without merging**
