### PR TITLE
Flare gun 1984

### PR DESCRIPTION
**Pull request by metalgearsloth**
Flares apply 4 stacks of fire to anything touched which means it's exclusively used as a makeshift flamethrower and not as a *flare*.

:cl:
- tweak: Flare pellets no longer apply fire stacks.

### CODE REVIEW

**Comment by mirrorcult** [comment]
4 was too many but they should still apply at least 1 or 2 firestacks imo

**Comment by potato1234x** [comment]
> 4 was too many but they should still apply at least 1 or 2 firestacks imo

agreed

**Comment by metalgearsloth** [comment]
> 4 was too many but they should still apply at least 1 or 2 firestacks imo

Any issues with making it only affect 1 mob and not every one it collides with.

**Comment by mirrorcult** [comment]
that would be fine

**Comment by AJCM-git** [comment]
linter fail

**Pull request merged**
