### PR TITLE
Make the hypospray unable to draw toxins

### PR DESCRIPTION
**Pull request by Simyon264**
## About the PR

This PR makes the hypospray unable to draw any toxins. Other instant injectors remain unaffected.

## Why / Balance

This PR was mainly made after some initial discussion and then some in #design-discussions. See also #28659. The main concern is that CMOs can inject poisons and other toxins instantly. This encourages valid hunting which I've observed multiple times. Now, why not just let admins deal with it? Well, mechanically reinforced rules are better most of the time and more admin workload is always bad.

## Technical details

Adds a new DataField to the Hypospray component which dictates if it should filter out Toxins or not upon drawing. To support this, I've added a new Method in the Solution class which filters out any reagents which are part of a group.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://skibidi.unstablefoundation.de/github/Desktop%202024.07.10%20-%2014.49.32.03.mp4

(I know, the domain is very cringe, its the only fileserver I have)

**Changelog**

:cl: Simyon
- tweak: The CMOs Hypospray now has a filter which removes any toxins drawn from a solution.

### CODE REVIEW

**Comment by thebadman4662** [comment]
Isn't point of Hypo to be a weapon in first place? How do you inject chloral to sedate unruly patients if they refuse to stand still for 6 seconds? Bomb medbay with foam/smoke bombs???

**Comment by Simyon264** [comment]
> How do you inject chloral to sedate unruly patients if they refuse to stand still 
If they refuse, they don't want treatment anyways. You can get security.
> Isn't point of Hypo to be a weapon in first place?
I wouldn't say so. The description says "A sterile injector for rapid administration of drugs to patients". This doesn't really scream "weapon" to me.

**Comment by lzk228** [comment]
remove role-play ahh changelog

**Comment by EdenTheLiznerd** [comment]
While I'm fine with this and think it's alright, it could be much better. A quick doafter for the hypo would work wonders and would help the issues with CMO's act as medsec, CMO's have issues with it and this PR is a good step towards it but needs improvement.

Removing poisons from it as a whole ruins the reward of successfulpy stealing the hypo as an antagonist.

**Comment by Simyon264** [comment]
> Removing poisons from it as a whole ruins the reward of successfulpy stealing the hypo as an antagonist.
You can still use narcotics such as nocturine or pax. And having an instant injector in combat is very powerful.

**Comment by Holinka4ever** [comment]
Why you locking sandbox possibilities?
If cmo validhunt, its an admin job, nor a coder.
If they wish to kill, they still can overdose people with medicine, nothing would actually change.

**Comment by Aisu9** [comment]
welp, CMO will just use the medicine with either the harsher OD effect OR the lower OD threshold, well done for not thinking about alternatives.
report the fuckers
admins keep crying about receiving ahelp to ban MORE bad actors
contributors and maintainers keep forcing mechanics and keep bad actors among the playerbase

**Comment by Simyon264** [comment]
> welp, CMO will just use the medicine with either the harsher OD effect OR the lower OD threshold, well done for not thinking about alternatives. report the fuckers admins keep crying about receiving ahelp to ban MORE bad actors contributors and maintainers keep forcing mechanics and keep bad actors among the playerbase

No need to be hostile.

**Comment by Simyon264** [comment]
> Why you locking sandbox possibilities? If cmo validhunt, its an admin job, nor a coder. If they wish to kill, they still can overdose people with medicine, nothing would actually change.

Admin workload keeps increasing, this is an issue. Overdosing on medicine usually is slower than most poisons.

**Comment by Aisu9** [comment]
Another issue, what happen if the CMO absorb bruizine and punturaze in the Hypo?
they didn't absorbed razorium, but they still can still inject it.
what is the next step? removing OD? removing interesting interactions that punish uncommunicative doctors?

**Comment by metalgearsloth** [comment]
> Another issue, what happen if the CMO absorb bruizine and punturaze in the Hypo? they didn't absorbed razorium, but they still can still inject it. what is the next step? removing OD? removing interesting interactions that punish uncommunicative doctors?

Please stop being hyperbolic

**Comment by PJB3005** [comment]
I would be sad to see this go, but if people really cannot help themselves but validhunt as CMO with this then this is probably the way it has to be. 

Admin decision though IMO, since this aims to solve validhunting.

**Comment by Aisu9** [comment]
> > Another issue, what happen if the CMO absorb bruizine and punturaze in the Hypo? they didn't absorbed razorium, but they still can still inject it. what is the next step? removing OD? removing interesting interactions that punish uncommunicative doctors?
> 
> Please stop being hyperbolic

maybe, but i don't give one week before there is another PR forcing another mechanic change to the Hypospray, people will always find a way to use this medical tools for valid hunting.
Please don't go shocked pikachu's face when it happen, ain't the first time i'm being ignored after reporting a blatant design flaw change that did happen.

**Comment by Tayrtahn** [comment]
I think the suggested fix of adding a short, break-on-move DoAfter would better address the valid-hunting problem.

**Comment by Plykiya** [comment]
> I think the suggested fix of adding a short, break-on-move DoAfter would better address the valid-hunting problem.

it would ruin the hypo as a noct option for antags, and ruin the hypospray for nukies in combat healing, unless the implication is that all antag hypos are still instant?

**Comment by SlamBamActionman** [comment]
Copying my response from https://github.com/space-wizards/space-station-14/issues/28659#issuecomment-2220579546 since discussion appears to be happening here instead:

> Is it unreasonable to just make the hyposprays have a 0.5-1 second doafter that gets broken immediately upon movement?
> 
> If you are hypo-ing someone that is willing to be healed they're likely standing still anyways, and you're going to be faster than a syringe regardless when treating people. This stops CMOs from running in and souping someone up with Chloral Hydrate in the middle of a firefight, but still keeps it somewhat viable as an offensive tool if used in conjunction wtih other equipment (slip the shitter with soap, inject inject).

**Comment by metalgearsloth** [comment]
Doesn't giving it a do_after just turn it into a syringe? It would make the item a macguffin at that point.

**Comment by PJB3005** [comment]
I think nerfing chloral hydrate would be a better solution, probably:
1. make it take like 15-30 seconds to drop somebody
2. make dylovene counter chloral hydrate by removing it from your system (I know this was a thing in SS13).

that would still leave it *strong*, but higher risk to use and open up some counter play.

**Comment by Simyon264** [comment]
> make it take like 15-30 seconds to drop somebody

While this is a fix, I believe it will still not stop CMOs from Validhunting.

**Comment by Aisu9** [comment]
if you really wanna go full-mechanic/RP, you can force pacifism on CMO job + make pacifism forbid the use and injection of poison and prevent overdosing or mixing chem that will result in dangerous substance.
Or delivered job ban could also be harsher, without appeal possible(despite the admins being stretched thin already, but this is bound to weed out bad actors)

**Comment by Plykiya** [comment]
I think trying to mechanically change the hypo with do-afters and whatnot would just cause the hypo to lose its identity, and the toxin filtering option is basically the best method for stopping chloral hydrate specificially.

It's also, eh, it kind of gives the CMO hypo a little flavor? Like it's one of those weird fancy water filtering things that let you safely drink swamp water, but instead you can guarantee you're not injecting poisons into people regardless of how polluted the source you draw from is

**Comment by SlamBamActionman** [comment]
> Doesn't giving it a do_after just turn it into a syringe? It would make the item a macguffin at that point.

Syringes have a doafter of 3-5 seconds iirc depending on what the target is doing. If the proposal was to give it a similar doafter, sure, then it's worthless. But we're talking 0.5-1; long enough that it can break, but short enough that it saves you heaps of time.

Hyposprays already has a hidden delay in the form of a 0.5 UseDelay cooldown. Giving it a doafter would just change that from "instant use, 0.5 cooldown" to "0.5 delay, no cooldown".

**Comment by PJB3005** [comment]
> While this is a fix, I believe it will still not stop CMOs from Validhunting.

30 seconds is plenty of time for a traitor to retaliate in a way that is going to leave the CMO even more messed up than the traitor in that exchange.

> Syringes have a doafter of 3-5 seconds iirc depending on what the target is doing. If the proposal was to give it a similar doafter, sure, then it's worthless. But we're talking 0.5-1; long enough that it can break, but short enough that it saves you heaps of time.

Important to note that the hypospray only injects 5 units at a time, slowing this down would make it really annoying for bulk-injection.

**Comment by thebadman4662** [comment]
> Important to note that the hypospray only injects 5 units at a time, slowing this down would make it really annoying for bulk-injection.

CMO syringe meta back on menu? :godmode:

**Comment by Cojoke-dot** [comment]
There are just too many ways to kill someone with chemicals for this to be effective I think. A doafter would make the hypo a much less fun item. Another option could be just increasing the time between hypo injects for the cmo's hypo. Making it slower should not affect healing, just give more time for chems to react before another injection. The time increase would have to be significant in order for the hypo to be less effective than a regular weapon.

**Comment by Plykiya** [comment]
> I think nerfing chloral hydrate would be a better solution, probably:
> 
>     1. make it take like 15-30 seconds to drop somebody
> 
>     2. make dylovene counter chloral hydrate by removing it from your system (I know this was a thing in SS13).
> 
> 
> that would still leave it _strong_, but higher risk to use and open up some counter play.

this should definitely happen regardless of what's decided to do with hypos or not, chloral is way too strong compared to how rare noct is

**Comment by SlamBamActionman** [comment]
> > Syringes have a doafter of 3-5 seconds iirc depending on what the target is doing. If the proposal was to give it a similar doafter, sure, then it's worthless. But we're talking 0.5-1; long enough that it can break, but short enough that it saves you heaps of time.
> 
> Important to note that the hypospray only injects 5 units at a time, slowing this down would make it really annoying for bulk-injection.

Bulk injections are already "slowed down" by the UseDelay. Changing it into a DoAfter would make dumping 30u reagent into someone take 3 seconds instead of 2.5, with all the benefits of using a doafter would bring (no more insta-inject chloral hydrate!)

**Comment by Plykiya** [comment]
> > > Syringes have a doafter of 3-5 seconds iirc depending on what the target is doing. If the proposal was to give it a similar doafter, sure, then it's worthless. But we're talking 0.5-1; long enough that it can break, but short enough that it saves you heaps of time.
> > 
> > 
> > Important to note that the hypospray only injects 5 units at a time, slowing this down would make it really annoying for bulk-injection.
> 
> Bulk injections are already "slowed down" by the UseDelay. Changing it into a DoAfter would make dumping 30u reagent into someone take 3 seconds instead of 2.5, with all the benefits of using a doafter would bring (no more insta-inject chloral hydrate!)

you can guarantee you don't fail even with the useDelay, an injection that might take 3 useDelays might get canceled four or five times with a do-after just trying to get one in

**Comment by SlamBamActionman** [comment]
> you can guarantee you don't fail even with the useDelay, an injection that might take 3 useDelays might get canceled four or five times with a do-after just trying to get one in

I mean yeah, that's the point.
- Don't use the hypospray on people who are moving, i.e. most people in active combat.
- Use it on people who are still, i.e. most people who need healing. 

How often do you actually see CMOs/Agents live-inject someone in the middle of combat, versus the injured person stepping back from the front lines to get quickly patched up? Keep in mind that if a DoAfter were to be implemented crew/Nukies would quickly learn this and know to stand still for a second as they ask for healing.

**Comment by thebadman4662** [comment]
> Use it on people who are still, i.e. most people who need healing.

> crew/Nukies would quickly learn this and know to stand still for a second as they ask for healing.

Most people that need healing won't bloody stop even as you point and whistle(always bother sec for em as MD/chemist/para) at them. 😭 
They would rather crawl at double speed debuff in near-crit state to medbay on other side of station than get full heals in ~5 seconds.

**Comment by SlamBamActionman** [comment]
> Most people that need healing won't bloody stop even as you point and whistle(always bother sec for em as MD/chemist/para) at them. 😭 They would rather crawl at double speed debuff in near-crit state to medbay on other side of station than get full heals in ~5 seconds.

That's not a problem the Hypospray helps much with to begin with; sure, you can inject someone who is running around, but you won't be able to scan them to determine damage to begin with.

Moving the 0.5 delay from UseDelay to a DoAfter will fuck over CMOs trying to inject non-crit moving players who don't have the awareness to stop and CMO knows beforehand the damage they have taken without scanning. And that's it. It would not affect crit players, players who lay down in medbay beds and players who have the sense to... stand still next to a doctor, which they'd have to do anyways if it wasn't the CMO treating them.

I feel that's a fair tradeoff for preventing CMOs injecting non-crit moving players with poison, which is what the current hypospray design excels at.

**Comment by Plykiya** [comment]
you're not really intended to scan people as a nukie agent, you roughly know what damage they'll take and you can get an idea from what their symptoms are by examining their physical condition (pale means lack of bleed, etc etc....)

**Comment by Cojoke-dot** [comment]
> but you won't be able to scan them to determine damage to begin with.

If they are running around then you use a general med mix for common combat damages, like a mix of punc and derm or something. Adding a doafter removes its advantage over the syringe, why would the item be special then? What advantage would be given over a normal injection?

**Comment by SlamBamActionman** [comment]
> If they are running around then you use a general med mix for common combat damages, like a mix of punc and derm or something. Adding a doafter removes its advantage over the syringe, why would the item be special then? What advantage would be given over a normal injection?

How is a 0.5 second injection not a massive advantage over a 3-5 second injection? That's still an incredibly good deal in 95% of usecases.

**Comment by Brandon-Huu** [comment]
Just ban the valid hunters.

**Comment by Simyon264** [comment]
> Just ban the valid hunters.

If it was that easy, it would have already happened.

**Comment by Brandon-Huu** [comment]
> > Just ban the valid hunters.
> 
> If it was that easy, it would have already happened.

So the problem is valid hunting CMO using their hypopen to sleep people.
You remove the ability to sleep with hypopen, You still have a valid hunting CMO.

**Comment by slarticodefast** [comment]
>The issue is the CMO valid hunting using their hypopen to sleep people.

Again some advertisement for my PR changing chloral hydrate to make you drowsy instead of forcing you to sleep instantly :)
#27454

**Comment by Brandon-Huu** [comment]
> > The issue is the CMO valid hunting using their hypopen to sleep people.
> 
> Again some advertisement for my PR changing chloral hydrate to make you drowsy instead of forcing you to sleep instantly :) #27454

Chloral hydrate is needed for psychiatric patient RP.
It's impossible to put a straight jacket onto someone without chloral.

**Comment by Hrosts** [comment]
Have the toxins inside the hypo make it beep loudly and annoyingly. You still CAN inject things with it, but people will know if you're planning to use it for no good.

**Comment by SlamBamActionman** [comment]
> That 3-5 seconds gets 3 times the chems in. So 1.5 seconds for 15u of whatever assuming you click right as the last doafter ends. You could make it like topicals and have doafters loop but that feels like it's going to end up having a lot of people od from a missed doafter cancel. It adds multiple levels of failure over just a single doafter of a syringe. Making it one doafter turns it into a lame syringe...

Again, hyposprays currently already have a delay, only that it happens after the injection in the form of a UseDelay. So for 15u injection with a hypo it takes 1 second if you click as soon as the delay ends. 

15u with UseDelay: Inject > 0.5s Delay > Inject > 0.5s Delay > Inject = 1s 
15u with DoAfter: 0.5s Delay > Inject > 0.5s Delay > Inject > 0.5s Delay > Inject = 1.5s

The main impact would be on single injections which, true, would no longer be instant. Which would be the point. 0.5s is still really fast; for comparison a health analyzer scan takes longer than that at 0.8 seconds.

**Comment by Sarahon** [comment]
"Mechanically reinforced rules are better most of the time", can't lie, this is a crazy comment to make. I am just getting into the habit of treating CMO like warden when they loose. CMOLOOSE! A CMO not in medbay (assuming they aren't fetching something or doing command stuff of course) is just a bad cmo. Destroying the antag usage of hypo does more than just nerf a cmoloose.

**Comment by SlamBamActionman** [comment]
> "Mechanically reinforced rules are better most of the time", can't lie, this is a crazy comment to make. I am just getting into the habit of treating CMO like warden when they loose. CMOLOOSE! A CMO not in medbay (assuming they aren't fetching something or doing command stuff of course) is just a bad cmo. Destroying the antag usage of hypo does more than just nerf a cmoloose.

Using rules (or worse, player culture) to enforce game balance is terrible game design and ripe for abuse. It's throwing up one's hands as a game designer and saying "fuck it, admins will manually handle it".

If a CMO wants to go out and kill Nukies, they will. And frankly I say they should have that choice if push comes to shove. The issue is that the game heavily currently encourages them to do so by giving them a tool that is as useful offensively as it is defensively (attacking vs. healing), and there are different ways to go about solving that.

I think banning poisons from the hypospray, even if it was only the CMO's, ruins a bit of the modularity of the game. I'd rather have a solution that overall tips the tool into defensive utility than selectively marking what reagents does and doesn't work in the hypospray.

- How does the hypospray handle low OD thresholds?
- What about reagents mixing inside the hypospray?
- If the answer is "keep them separate, like a stasis syringe" then what's keeping them from mixing inside the target?
- Does Ipecac count as a poison? Puking is a decently strong effect.

**Comment by Veritable-Calamity** [comment]
I feel this is a balance issue that is going the wrong way about it. Hypospray's usefulness as an offensive weapon mirrors its effectiveness as a means of rapidly healing patients. This is why it's such a valuable item to antagonists.

Additionally, it is absolutely intended to be able to subdue unruly patients. This is a normal part of medicine both IRL and in-game, and in most situations security is never required in either case.

Instead of removing the ability to draw toxins, the hypospray should rather be limited in it's means of injection. A hardsuit or space suit shouldn't be something a hypospray is able to inject through without finding the 'injection port' on the suit - implementing a doafter for this type of action would make sense. In this regard, we effectively nullify the ability of the hypospray to be effective against nukies, spacesuit-wearing traitors, and the deathsquad. Certain types of body armor could also cause this do-after to occur.

Having counterplay to this issue would be a better implementation than an outright removal of a capability.

**Comment by Simyon264** [comment]
You make solid points. If having a doafter for hardsuits is preferred, then I can do that.

**Comment by Sarahon** [comment]
> > "Mechanically reinforced rules are better most of the time", can't lie, this is a crazy comment to make. I am just getting into the habit of treating CMO like warden when they loose. CMOLOOSE! A CMO not in medbay (assuming they aren't fetching something or doing command stuff of course) is just a bad cmo. Destroying the antag usage of hypo does more than just nerf a cmoloose.
> 
> Using rules (or worse, player culture) to enforce game balance is terrible game design and ripe for abuse. It's throwing up one's hands as a game designer and saying "fuck it, admins will manually handle it".
> 
> If a CMO wants to go out and kill Nukies, they will. And frankly I say they should have that choice if push comes to shove. The issue is that the game heavily currently encourages them to do so by giving them a tool that is as useful offensively as it is defensively (attacking vs. healing), and there are different ways to go about solving that.
> 
> I think banning poisons from the hypospray, even if it was only the CMO's, ruins a bit of the modularity of the game. I'd rather have a solution that overall tips the tool into defensive utility than selectively marking what reagents does and doesn't work in the hypospray.
> 
> * How does the hypospray handle low OD thresholds?
> * What about reagents mixing inside the hypospray?
> * If the answer is "keep them separate, like a stasis syringe" then what's keeping them from mixing inside the target?
> * Does Ipecac count as a poison? Puking is a decently strong effect.

Yet wizden is one of the least mechanically locked down servers and seems to work well enough to keep a high pop community that seems to majorly follow the rules placed inside said server. I don't think treating servers like they're all children is at all a good mindset. Furthermore, each department and player also helps moderate these things via ingame means on top of that. Cap, if he cares could fire CMO for cmoloosing over and over easily. It just takes enough people to notice and complain about it. On top of that, assuming med is actually running correctly, the idea of CMO using hypo to help out in a combat situation isn't always a bad thing. I do not at all agree that the game encourages CMO to loose. Specifically because med is a shitshow, especially during nukies. We've all seen what happens when CMO abandons their post during disasters in med - it's not good!

A bad CMO will go out and kill nukies, regardless of hypospray usage. You could make this same argument for almost any tools certain departments have at their disposal. And people have made solid arguments in terms of patient usage. Some prisoner patients may try to break out, using the hypospray in that situation to subdue them seems invaluable. 

I think chems do mix inside the target also, but don't quote me on that.

**Comment by thebadman4662** [comment]
> I think chems do mix inside the target also, but don't quote me on that.

Yes, they do in any container of choise: mobs, stomachs, floor puddles, liquid/powder containers, machines...

**Comment by Erisfiregamer1** [comment]
imo why not just make drawing toxins require it to be emagged

**Comment by Veritable-Calamity** [comment]
> You make solid points. If having a doafter for hardsuits is preferred, then I can do that.

I think this would be a much better way of going about it, for sure.

**Comment by thebadman4662** [comment]
> imo why not just make drawing toxins require it to be emagged

Not only require CMO being robbed but also almost half of your TC in emag tax? Why not buy your own hypo at that point. 😕

**Comment by cohanna** [comment]
theres really no need to nerf the hypospray
its a powerful item, yes, but so are most of the command items. Thats kinda the point. You could just as easily say the CE's magboots cause with valid hunting as they are essentially noslips. Or that the RD's teleporter causes valid hunting cause the RD can enter risky situations and leave immediately. 
Just because a non sec item can be used in a lethal way, doesn't mean that it shouldn't be in the game. Hell even the atmos fire axe would be removed under this mindset as its really not used for anything other than combat. If you remove the hypospray's ability to draw toxins you are not solving the "issue" of valid hunting. You are just making the game experience worse.

**Comment by BolloTea** [comment]
Let's delete the game then.  Again, raids and Valinghunters are a problem for the administration, not the game.  Can't cope?  make tracking tools or tighten rules.  You are not forced to do 1984, but all the discussions there were about cmo and hypo are stupid.  You will kill the balance and the item itself, you yourself will return everything to its previous course in a week, since there will be more complaints about bad hypo, but there will be no cmo violators.  If you change the balance every time because of players who don’t follow the rules, then it means you’re doing a poor job as an administrator, and it’s not the game’s fault.

**Comment by Djungelskog2** [comment]
i haved used toxins/chloral like... once as cmo with their hypo and its when me and a chemist had spare time so we were fucking around and experimenting with some exotic chems to see what they did in action

if your doing your fucking job this change shouldnt really effect you in the slightest

**Comment by deltanedas** [comment]
adding a short doafter makes validhunting much harder

**Comment by BolloTea** [comment]
> Я использовал токсины/хлорал, например... однажды, как CMO с их гипо, и это было, когда у меня и химика было свободное время, поэтому мы возились и экспериментировали с некоторыми экзотическими химикатамитреть, ч

> Если ты делаешь свою чертову работу, то это изменение не должно на тебя как-то повлиять.
>
But not when you're the antagonist

**Comment by ThatOneGoblin25** [comment]
This is a bit like taking a hammer to a whole item just over powergaming. Especially since we haven't tried any other sort of nerf yet. Personally I don't see a big enough reason to nerf the hypo like this since nearly every reagent is poisonous in quanitity. DoAfters were touched upon in the convo but rather than injection prehaps only when inserting reagents into the hypo?

Additionally if this PR is merged there's also the loop of just mixing toxin in the 30u sized hypo, i.e razorium.

**Comment by cohanna** [comment]
> adding a short doafter makes validhunting much harder

that's still a pretty big blow for antags for what is an extremely small subset of CMO's abusing the hypo for validhunting. This is entirely an enforcement issue, not a mechanic one. As many have stated previously, the hypo having combat potential isn't a negative and has many uses for both the CMO and antags be it in RP or whatever else. A CMO abandoning their position to valid hunt is the issue, not the tools they use. 
I fully believe changes should push to add more options for everyone, not to reduce them due to a few people **rule-breaking**.
Yes admin workloads are increasing, and yes it would be nice to have fewer validhunters, but im of the mindset that these are byproducts of an increased population of the game and its complexity and should seek to be remedied via more staff in general, not through the slow dismantling of the sandbox created.

**Comment by deathride58** [comment]
This has been discussed among maintainers as part of the [maintainer policy](https://docs.spacestation14.com/en/staff/maintainer-policy.html). The unanimous decision throughout the 24-hour discussion period is that this PR is simply not desired. Here are the general notes of what was touched over during that conversation:

- A lot of the balance issues with the hypospray's lack of filter is less an issue of the hypospray itself, but rather, an issue with chemistry as a whole. If the hypospray itself is nerfed, then the actual problematic chems in question are just gonna be applied through other methods that're likely to be more problematic than the hypospray is (an item that's intended to be quite powerful to begin with, on account of it being a one-of-a-kind item)
- Chems in general, particularly poison, are *extremely* strong against single targets to begin with, with many of them being able to crit with incredibly low doses (though the actual DPS varies heavily among them, and only a subset of harmful chemicals are a part of the toxins reagent group)
- Chloral hydrate in particular is a particularly egregious outlier among chems, in that there's no period of drowsiness like there is in SS13 (it just drops you instantly once you hit the threshold). There's a pr up to fix this by implementing that drowsiness effect (https://github.com/space-wizards/space-station-14/pull/27454)
- Roles like Nuclear Operatives that are supposed to be overpoweringly strong should probably be given counterplay to chemical warfare (which the hypospray is especially strong at). Nukies currently completely lack any good way of dealing with chem warfare if there's no experienced chemist on the team (the combat medkit completely lacks tools to deal with toxin damage, for instance)

This PR will be closed, as the dissenting opinions are ones that would require changes that're very much outside of this PRs scope in order to be resolved (and honestly it'd be unfair to expect the author to do so on their own). One of the bullet points (specifically, the bullet point regarding chloral hydrate, which is one of the main issues raised in community discussions surrounding the issue) additionally has a PR up to address it.

Maintainer policy currently doesn't lay out what should be done in cases like this where a PR simply lacks support by the time the 24-hour discussion period is over, and we (as in Bhijn and Myr) acknowledge this. There have been no objections raised to the notion of the PR being closed, and thus that will be the course of action here. It's very likely the maintainer policy will see an adjustment in the near future to clarify this.

**Pull request closed without merging**
