### PR TITLE
Add Mime outfit 🎭 & HoP outfit 📎 . 

### PR DESCRIPTION
**Pull request by Sauberstaub**
hop
mime

I can't into cherry-pick but I'm sure you can deal with the captain commit.

### CODE REVIEW

**Comment by PJB3005** [comment]
> I can't into cherry-pick but I'm sure you can deal with the captain commit.

Yeah, it's pretty easy to deal with. Thanks for mentioning it though so I noticed ahead of time.

**Comment by DamianX** [comment]
It looks like this forgot to stage several files like hop_jumpsuit.rsi, mask_mime.rsi and more.

**Comment by PJB3005** [comment]
@Sauberstaub 	any chance of you making a PR with the missing files?

**Comment by Sauberstaub** [comment]
@PJB3005 Sorry. My modem was dead for about a week the day after I made this PR. I think I lost those files....

**Pull request merged**
