### PR TITLE
Snout Fitting Masks

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Adds 32(+1 from the existing neck gaiter one) new sprites for reptile muzzle fitting masks.
Adds the inventory species ID "reptilian" to lizard mobs to actually use these sprites.

This is a new sprite for every mask _**EXCLUDING**_ the Italian moustache, ninja, and plague doctor mask.

## Why / Balance
It improves the look of a lot of masks when worn by lizards as half of them usually clipped through their snout.
I personally feel like since we already have a unique monkey fitting sprite for every jumpsuit this isn't too far fetched, since that's arguably harder to maintain.

## Media
image
_(The mime and clown masks were slightly adjusted since this image was taken.)_
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
Unsure if it's required.

### CODE REVIEW

**Comment by UbaserB** [comment]
the clown one is so deformed lol

**Comment by Nairodian** [comment]
> the clown one is so deformed lol

It now looks like this, there's a couple variants but this was the best I could do.
image

**Comment by deathride58** [comment]
For inspiration: ya might be able to go for something like CitMain's snout-having clown mask sprites!
image

Lizard snouts aren't anywhere near the size of the snoots seen across CitMain, but the general idea is applicable: extending those gaudy lips across the side profile

**Comment by Nairodian** [comment]
> For inspiration: ya might be able to go for something like CitMain's snout-having clown mask sprites!
> Lizard snouts aren't anywhere near the size of the snoots seen across CitMain, but the general idea is applicable: extending those gaudy lips across the side profile

I like this, but I'm also trying to maintain a flow between the front view still, which feels out of place with a smile that large.
image

**Comment by Nairodian** [comment]
There's this, but I think he looks, just a little goofy.
image

**Comment by Flareguy** [comment]
I'm not too worried about maintenance cost here, especially since later on a lot of these won't be able to be displacement mapped anyways (gas masks and clown mask are good examples.) Looks fine to me.

**Pull request merged**
