### PR TITLE
Remove Pun Pun’s PDA, keeps their ID Card

### LINKED ISSUE #16360: Pun Pun can be a traitor
I have no idea what’s going on with this, but the bartender monkey can be a traitor. They have the objectives, uplink, everything.

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR

Fixes #16360 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Pun Pun has lost PDA privileges.

### CODE REVIEW

**Comment by deltanedas** [comment]
then pun pun cant get glasses which might be bad

**Comment by lzk228** [comment]
> then pun pun cant get glasses which might be bad, maybe replace with a bartender id card

with his name on it

**Comment by Nimfar11** [comment]
Shouldn't we just give out the card then?

**Comment by GoodWheatley** [comment]
> then pun pun cant get glasses which might be bad, maybe replace with a bartender id card

It’s a monkey, it shouldn’t have bartender access just so it can get a pair of sunglasses

**Comment by mirrorcult** [comment]
idk this is kind of funny to be honest

**Comment by Emisse** [comment]
this is so good why would we remove it

**Comment by GoodWheatley** [comment]
> this is so good why would we remove it

Because a monkey being able to replace the bartender the instant they spawn in is stupid imo & it fixes a bug with them being able to roll traitor

**Comment by LordEclipse** [comment]
> > this is so good why would we remove it
> 
> Because a monkey being able to replace the bartender the instant they spawn in is stupid imo & it fixes a bug with them being able to roll traitor

ANY creature with the ability to hold a PDA can be made a traitor. Not a bug, intentional behavior.

**Comment by GoodWheatley** [comment]
> > > this is so good why would we remove it
> > 
> > 
> > Because a monkey being able to replace the bartender the instant they spawn in is stupid imo & it fixes a bug with them being able to roll traitor
> 
> ANY creature with the ability to hold a PDA can be made a traitor. Not a bug, intentional behavior.

After checking the code, the reason Pun Pun can roll traitor is because they have a roundstart PDA, not because of their PDA slot. I’m only removing the PDA they start with, not the slot itself.

**Comment by deltanedas** [comment]
> It’s a monkey, it shouldn’t have bartender access just so it can get a pair of sunglasses

glasses for drinking

**Comment by ChilbroBaggins** [comment]
> then pun pun cant get glasses which might be bad, maybe replace with a bartender id card

Can't you just add
eyes: ClothingEyesGlassesBeer
?

**Comment by LordEclipse** [comment]
> > > > this is so good why would we remove it
> > > 
> > > 
> > > Because a monkey being able to replace the bartender the instant they spawn in is stupid imo & it fixes a bug with them being able to roll traitor
> > 
> > 
> > ANY creature with the ability to hold a PDA can be made a traitor. Not a bug, intentional behavior.
> 
> After checking the code, the reason Pun Pun can roll traitor is because they have a roundstart PDA, not because of their PDA slot. I’m only removing the PDA they start with, not the slot itself.

To roll traitor Pun Pun would need a mind. Is Pun Pun round start ghost role? The only way for Pun Pun to become a traitor is if Pun Pun was somehow a round start ghost role, and had a mind within the first 5 or so minutes of a traitor round, or however long it takes to roll traitor.

**Comment by Emisse** [comment]
pun pun spawns at roundstart but wont have a valid mind until someone picks them

**Comment by deltanedas** [comment]
> Can't you just add
eyes: ClothingEyesGlassesBeer
?

drinking glasses not eye glasses!!!!

**Comment by ChilbroBaggins** [comment]
> drinking glasses not eye glasses!!!!

right right, still should be easy to just have them spawn with them. Then you don't need to worry about access

**Comment by crazybrain23** [comment]
> > drinking glasses not eye glasses!!!!
> 
> right right, still should be easy to just have them spawn with them. Then you don't need to worry about access

Monkey's have one hand and no pockets, where are you going to put the (drinking) glasses?

**Comment by ChilbroBaggins** [comment]
> Monkey's have one hand and no pockets, where are you going to put the (drinking) glasses?

On their face

**Comment by crazybrain23** [comment]
> > Monkey's have one hand and no pockets, where are you going to put the (drinking) glasses?
> 
> On their face

A glass cup on their face?

**Comment by ChilbroBaggins** [comment]
> A glass cup on their face?
> Drinking glass: the thing you fill with drinks in order to drink them.

Holy shit haha😂....I'm out of it today.

**Comment by ChilbroBaggins** [comment]
But you should give them beer glasses anyway...

**Comment by brainfood1183** [comment]
pun pun isnt like ordinary monkeys, pun pun is a crewmember. I kinda like pun pun having access and sometimes being a syndie tbh.

**Comment by GoodWheatley** [comment]
> pun pun isnt like ordinary monkeys, pun pun is a crewmember. I kinda like pun pun having access and sometimes being a syndie tbh.

In ss13 Pun Pun is the bartender’s pet that usually lives a short life of 2 minutes before being meatspiked by the chef for meat, this is the kind of role I want to emulate

**Comment by mirrorcult** [comment]
honestly i get that punpun is like that in ss13 but i like brainfoods vision more here

**Comment by mirrorcult** [comment]
being a syndie is ehhh but i like punpun having an id at least

**Comment by ChilbroBaggins** [comment]
> In ss13 Pun Pun is the bartender’s pet that usually lives a short life of 2 minutes before being meatspiked by the chef for meat, this is the kind of role I want to emulate

That honestly sounds a lot less fun.

**Comment by GoodWheatley** [comment]
PR updated

**Pull request merged**
