### PR TITLE
New tear gas sprite

### PR DESCRIPTION
**Pull request by LentilMan**
## About the PR

The old tear gas sprite didnt match the same perspective as other grenades, so i decided to try and make a new sprite (both normal and primed versions)
## Why / Balance

I decided to change it because it was an issue brought up in the art channel of the space station 14 discord (also it bothered me)
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
regular
primed
image

(bottom sprite is primed)
## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by UbaserB** [comment]
how is the sprite against normal grey tiles?

**Comment by LentilMan** [comment]
not too bad, the outline could use a little tweaking

**Comment by UbaserB** [comment]
> not too bad, the outline could use a little tweaking

send a photo

**Comment by LentilMan** [comment]
image
here it is compared to a bunch of different tiles, just in case, the greyer tiles do tend to blend with the outline a bit more than what would be liked

**Comment by lzk228** [comment]
Please read the docs or ask for help in discord. Because your pr doesnt do anything related with repsrites, you just uploaded raw sprites to main folder.

**Comment by EmoGarbage404** [comment]
As per the guidelines for pull requests stated [here](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html), I'm going to close this PR for the use of the github web editor. Please refrain from using it in the future.

You can consult the [SS14 setup guide](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html) for information on how to set up git on your machine.

Thank you for your contribution.

**Pull request closed without merging**
