### PR TITLE
Removes CLF3

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Removes CLF3 from the game.
Addresses part of #28606.

## Why / Balance
CLF3 in its current state is just better potassium + water that is barely more difficult to synthesize. This is not only boring as hell, but is very abusable (hence the linked issue.) Non-antagonists should probably not be able to semi-trivially synthesize explosives that are actively *good* at breaching the hull with a recipe that only requires two base reagents & a bit of heating up.

Maybe I *could* use the firebomb explosion type to make something more interesting & balanced, but explosions are difficult to tune & the PCTide is soon:tm:. From my limited testing with FireBomb explosions, I'm frankly not even sure you *can* make something that doesn't breach the hull while still doing some amount of fire damage.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Probably none???

**Changelog**
:cl:
- remove: Removed CLF3.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Why not remove potassium and water too? It's much easier to make and can be used to make throwable glass bombs that almost one hit crit a player wearing secoff level armor

**Comment by BolloTea** [comment]
This is not a solution to the problem.  But rather, escape from it, because in this way you can remove all the explosives, instead of writing a guide to the correct synthesis, to avoid accidents.  After all, the person above is right when he mentioned potassium + water, jokes about mixing it are basic and cannot be eradicated, but newcomers will continue to fall for it.

**Comment by ninruB** [comment]
Pretty sure CLF3 is distinct to pot+water now because it requires heat to explode while pot+water just explodes on contact.

**Comment by slarticodefast** [comment]
I do not think this one is really necessary for the PC tide. Other than nerfing welderbombing, which is quick and easy to do for everyone, obtainings these chemicals is only possible for a chemist, which is gated behind 4 hours of medical gameplay. Even then making CLF3 would require some preparation. You would also have to remove lots of other dangerous stuff (napalm, phlogiston, foam, smoke, water+potassium explosion, probably even mutagen and razorium) to make a chemist completely unable to grief if they wanted to. You could argue the same with plasma gas, what is stopping an atmos tech from openening a canister somewhere and setting it on fire? Or an engineer setting the AME injection to maximum?
I would instead suggest increasing the role timer for chemistry a little.

**Comment by mirrorcult** [comment]
yeah this one probably doesnt matter

**Comment by ps3moira** [comment]
CLF3 isn't the issue, this is obviously a player issue.

**Comment by mirrorcult** [comment]
> CLF3 isn't the issue, this is obviously a player issue.

this is meaningless, if you have something easily griefable its not a 'player issue' if griefers abuse it, its a game issue that its so easy for bad players to abuse it

that said i dont think this is actually easily griefable or abusable to begin with so i dont see the need for it

**Pull request closed without merging**
