### PR TITLE
Refactor/VendingMachines

### PR DESCRIPTION
**Pull request by CrazyCat2048**
# This is a new PR, but still related to #17767

## Separation of the vendingMachineComponent

Previously, the VendingMachineComponent contained more than 30 fields that were too general and really needed to be separated.
Now, after the separation, there are new components for working with machines, as well as for adding other objects for the future.

### Why is this necessary?

First of all, I have plans to add the logic of adding items to a smart refrigerator. Secondly, to remove the possibility for each machine to be contraband or emagged.

### **New components:**

| New vending machine component | Description |
| ------------- | ------------- |
| VendingMachineInventoryComponent | Standart inventory  |
| VendingMachineEjectComponent | Responsible for issuing items |
| VendingMachineEmpEjectComponent | Responsible for issuing items during the EMP effect |
| VendingMachineRestockComponent | It is needed to replenish the machines with the help of a pack |
| VendingMachineVisualStateComponent | Designed for the visual state of the machine |

| New auxiliary component | Description |
| ------------- | ------------- |
| BrokeComponent | The component required for the operation of VendingMachine |
| DispenseOnHitComponent | Parameters for randomly throwing an item with a recharge |

### Separated data from the general VendingMachineComponent

| Separated data  | Description |
| ------------- | ------------- |
| VendingMachineData | A dummy class that combines the general data of vending machines |
| VendingMachineInventoryTypePrototype | The prototype that is being added to .yaml file of the package of items for machines itself |

### **New systems:**

| New system | Description |
| ------------- | ------------- |
| VendingMachineEmaggedSystem | Separation from the main Vending Machine System class for easier configuration in the future |
| VendingMachineDamageSystem | OnBreak and OnDamage events |
| VendingMachineEmpSystem | Designed for ejecting objects after the EMP effect |
| VendingMachinePriceSystem | Counts the entire price inside the machine |
| VendingMachineSystem | Now this system is designed only to work with inventory |
| VendingMachineUiSystem | Works with UI events |
| VendingMachineVisualStateSystem | Visualization of the vending machine depending on the condition |

**Changelog**

:cl:
- tweak: NanoTrasen announces that it will improve vending machines in the future!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
consider using partial systems for the various VendingMachineSystems. It allows you to specify fewer dependencies and more obviously show that they are linked. It especially helps with code navigation via IDE.

**Comment by CrazyCat2048** [comment]
Moved the PR to a new one #18051

> consider using partial systems for the various VendingMachineSystems. It allows you to specify fewer dependencies and more obviously show that they are linked. It especially helps with code navigation via IDE.

Thx, it's ready

**Comment by CrazyCat2048** [comment]
@0x6273 Hi. Moved the PR here. Or are you no longer interested in this PR?

**Comment by CrazyCat2048** [comment]
Somebody, please?
I'm trying to somehow solve the problem with sending RT changes to PR

**Comment by CrazyCat2048** [comment]
PR broke (again). Creating a new one with fewer changes

**Pull request closed without merging**
