### PR TITLE
New anomaly behaviour: Invisibility

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

added 2 new anomaly behaviour:
- Invisibility
- Jumping invisibility

## Why / Balance

Good luck

**Changelog**
:cl:
- add: anomalies have the ability to gain invisibility behavior

### CODE REVIEW

**Comment by osjarw** [comment]
Tested this, seems to be working just fine. I didn't manage to find any gamebreaking bugs in couple minutes of testing.
Though I'm not that convinced that handling these will be that hard, unless you get a invisible, jumping, and wandering grav anom.
The glow of the anoms is still perfectly visible, though some anoms lack those, like the aforementioned grav anom.

**Comment by TheShuEd** [comment]
as well as a liquid anomaly containing dark liquid will not almost glow at all.

**Comment by osjarw** [comment]
Here's a little recording of the invisibility behaviour in action. 

https://github.com/space-wizards/space-station-14/assets/62134478/688a2bea-1f71-4fd7-ab6e-5c1692d59add

**Comment by IProduceWidgets** [comment]
There's some (not from your PR) weird behavior where StealthOnMove sometimes un-stealths when it teleports and sometimes doesn't. I think its distance related, but I'm not sure.

**Comment by TheShuEd** [comment]
Ok, thx, well

**Comment by ps3moira** [comment]
he was a good stalker.

**Pull request merged**
