### PR TITLE
NCS Aspid

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

The NCS Aspid is a mid-pop map modeled as a large passenger ship. It features hangar-like docks for evac, cargo, and other shuttles, with an atmos 'engine' and 'thruster'. It is an original design, taking inspiration from BeeStation's NSV, Atlas station, and others.

It did well on an initial playtest and is ready as is.  In the first large update after merge will probably expand Medbay, add a new parallax and maybe a unique taxi pilot job role or something similar
**Media**

map render is current to [bc5d27b](https://github.com/space-wizards/space-station-14/pull/13958/commits/bc5d27b9858bcf207e5447437b9d880b0683097c)
Aspid-0

bonus pic of hangar dock for evac:
aspid

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: checkraze
- add: Added the NCS Aspid

### CODE REVIEW

**Comment by Cheackraze** [comment]
is this the heisenbug? it looks unrelated

**Comment by Emisse** [comment]
yes test fail is erroneous

**Comment by moonheart08** [comment]
I'll review this when I get back in a few days.

**Comment by Emisse** [comment]
playtested on lizard with minimal bugs, good reception. ready for merge after checkraze fixes RD door

**Comment by Cheackraze** [comment]
> playtested on lizard with minimal bugs, good reception. ready for merge after checkraze fixes RD door

did all suggested changes and its good to go

**Comment by moonheart08** [comment]
yeet

**Pull request merged**
