### PR TITLE
Added proper capitalisation for supervisors when entering the game

### PR DESCRIPTION
**Pull request by averystarbits**
## About the PR
Changed job-supervisors.ftl to inclue proper capitalisation.

## Why / Balance
It just really pissed me off to look at.
image

## Technical details
Edited 
job-supervisors-$role/department = the head of department to -> Head of Department

## Media
image
to
image

## Requirements

- [ /] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [/ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
> such small locale fix doesn't require a changelog

Yeah, it doesn't really have any gameplay impact.
Could you remove the changelog from your PR description?

**Comment by slarticodefast** [comment]
Also your computer's time settings seem to be really messed up somehow
grafik

**Comment by baddiePRO** [comment]
> Also your computer's time settings seem to be really messed up somehow
> grafik
> 

nah they're a timelord

**Comment by averystarbits** [comment]
> > such small locale fix doesn't require a changelog
> 
> Yeah, it doesn't really have any gameplay impact. Could you remove the changelog from your PR description?

sure just woke up

**Comment by averystarbits** [comment]
> > Also your computer's time settings seem to be really messed up somehow
> > grafik
> 
> nah they're a timelord

because of this comment i will refuse to fix it until i feel like it

**Comment by slarticodefast** [comment]
I just hope it doesn't break anything in our repository when we merge any commit from the future

Do you have linux/window dual boot by the way? That often causes this because they use a different hardware clock setting.

**Comment by averystarbits** [comment]
> I just hope it doesn't break anything in our repository when we merge any commit from the future
> 
> Do you have linux/window dual boot by the way? That often causes this because they use a different hardware clock formats.

Late reply yes I dualboot windows & linux. I've just been too busy to set it up.

**Pull request merged**
