### PR TITLE
Adjust a lot of sprites for the new grid inv. Also changes some inv grids around.

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

~~Okay, first off, don't kill me for adding extra things to this. I had to go through every item entity in the game and I found some shit that needed fixing on a handful of occasions. Also, I'm easily distracted.~~ see atomized PRs

The PR primarily reshapes items storage shapes, changes their storage rotations, and shifts their sprites to line up with the new grid based storage system. 

image
image
image
image
image
image
image
image
image

image
image
image
image
image
image
image
image
image
image
image
image

image

image

image

image

image

image

image

image

image

image

image
image
image

image
(ignore mops and defib, atomized.)
image
image
image

(ignore belt size, atomized)
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

image

image

289619358-91a01c91-d05f-4ed3-aba7-9bc0ed6be6f0

This PR doesn't do it, because I was asked to atomize it, but I thiiiiinnnnk after we play with the new storage grid for a while we should change all Sidearms to an 'r' shape.

Okay, crucify me.

## Why / Balance

Pretties, easier to see, adds some minor variety and starts to stretch grid inv legs, Im too ADD to not add random shit to this PR.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Unless I really messed up all this should break is your muscle memory.

**Changelog**

:cl:
- tweak: The items in your inventory will hopefully look a little cleaner!
- tweak: Low capacity shotguns now have more interesting inventory shapes.
- tweak: A handful of inventories have been reshaped. The Syndicate Shoulder Holster now holds the guns you always wanted it to!
- tweak: Sidearms and pistol magazine now fit in the Secbelt
- tweak: Mop is Large
- fix: An elusive jar that refused to fill will now hold water!

### CODE REVIEW

**Comment by asperger-sind** [comment]
blessed beyond belief, the showcase is absolutely gorgeous

**Comment by JoeHammad1844** [comment]
what does the syndicate shoulder holster look like?

**Comment by IProduceWidgets** [comment]
Oops! missed an image! (I wish there was a less painful way to preview the PR text with embeds.)

image

**Comment by JoeHammad1844** [comment]
sweet

**Comment by JoeHammad1844** [comment]
did you not change the knives?

**Comment by deathride58** [comment]
Honestly the baguette should probably be l o n g

why?

funni

**Comment by lzk228** [comment]
> Honestly the baguette should probably be l o n g
> 
> why?
> 
> funni

>want to put cap id in satchel
>l o n g baguette
>:trollface:

**Comment by Errant-4** [comment]
The upright plates, specifically, look very strange (presumably because they are heavily cognitively associated with being flat)

**Comment by IProduceWidgets** [comment]
> did you not change the knives?

Unfortunately, I did not change the knifes. 
They need new sprites, and because of their fine details, they are non-trivial to make. 

Another solution would be to rotate them, but.... they look mildly cursed if I do that.

**Comment by IProduceWidgets** [comment]
> The upright plates, specifically, look very strange (presumably because they are heavily cognitively associated with being flat)

Hmm. Yeah. The plates are a weird quirk of how plates function in-world (you place other entities on top of them, just willy-nilly). The way entities stack means its better for the to be offset to the low side of the sprite.

Ill quickly make a set of storedSprites for the plates so they look a little less janky

**Comment by IProduceWidgets** [comment]
> Honestly the baguette should probably be l o n g

If you want to sprite it, the current sprite is a bit blagh for that.

**Comment by moonheart08** [comment]
No T or L shaped tools. 
image
Especially no this.

**Comment by moonheart08** [comment]
image
Please no.

**Comment by IProduceWidgets** [comment]
> No T or L shaped tools. image Especially no this.

I have a good reason for this one though! It makes the clown hammer hard to steal and keep away from the clown. Plus, the clown doesn't need all of their storage space anyway.

**Comment by Flareguy** [comment]
Please remove all of the non-90-degree rotations here.
image

If you want to make these items fit in the box, you should make a new sprite for them.

**Comment by IProduceWidgets** [comment]
> Please remove all of the non-90-degree rotations here. image
> 
> If you want to make these items fit in the box, you should make a new sprite for them.

Cow tools are already cursed, Im just making them not sit in boxes they shouldn't be in.

Glowsticks use changing states based on whether they are active or not, and that is not currently supported for storedSprite.

Ill see what I can come up with for airtanks.

**Comment by Flareguy** [comment]
> > Please remove all of the non-90-degree rotations here. image
> > If you want to make these items fit in the box, you should make a new sprite for them.
> 
> Cow tools are already cursed, Im just making them not sit in boxes they shouldn't be in.
> 
> Glowsticks use changing states based on whether they are active or not, and that is not currently supported for storedSprite.
> 
> Ill see what I can come up with for airtanks.

Do not include non-90-degree rotated sprites, period (yes, even for the sprites I didn't show here - my bad for not clarifiying.) They make mixels and do not look good.
If there's no way to properly fix them, then just leave them be. I'd much rather have a sprite that slightly pierces the bounds then something look completely out of place next to everything else.

**Comment by arimah** [comment]
The trash bag shape – I can't tell if that's meant to be a joke or if you really want to keep it that way, but in either case, I would kindly ask you to reconsider. It's a _bag_. It does not feel justified to me to turn it into a crude representation of a rubbish bin. Since most trash is 1x2, the proposed shape will make it much harder to fill the trash bag in a reasonable manner. It's also significantly harder to tell how full the bag is.

The medal case being so tall looks weird to me. A 4x2 arrangement of medals makes more sense than 2x4 in my mind and is less intrusive.

This change also alters the size (in number of grid squares) of several items. For instance, the mops now require twice the storage space, despite still having "size: normal" as far as I can tell;the multitool has shrunk to half its previous sizes; and the light replacer uses twice the number of squares and is impossible to fit nicely into a coat.

---

Overall, this sort of special-case shaping smells an awful lot of the arbitrary number system that was in the game prior to the inventory reworks. The more snowflake shapes there are, the harder it is to reason about storage. The more one deviates from "small = 2 squares, normal = 4 squares" and so on, the harder it is to reason about storage. It all becomes so, well, _arbitrary_.

**Comment by IProduceWidgets** [comment]
New etank sprites
image

**Comment by IProduceWidgets** [comment]
> The trash bag shape – I can't tell if that's meant to be a joke or if you really want to keep it that way, but in either case, I would kindly ask you to reconsider. It's a _bag_. It does not feel justified to me to turn it into a crude representation of a rubbish bin. Since most trash is 1x2, the proposed shape will make it much harder to fill the trash bag in a reasonable manner. It's also significantly harder to tell how full the bag is.

I do intend to keep it that way. It auto fills, and the worst case is something like 6 unused squares. I'm 100% okay with you having to get your hands dirty to maximize the storage space in a bag you can empty on every corner.

> The medal case being so tall looks weird to me. A 4x2 arrangement of medals makes more sense than 2x4 in my mind and is less intrusive.

Looks wrong for the sprite though, also the medal case is a secret item that gives you better nested storage.

> This change also alters the size (in number of grid squares) of several items. For instance, the mops now require twice the storage space, despite still having "size: normal" as far as I can tell;the multitool has shrunk to half its previous sizes; and the light replacer uses twice the number of squares and is impossible to fit nicely into a coat.

By popular demand I changed the light replacer to a normal Small 1x2.
The mop is a large item now. Its a mop.
The multitool and network config changed to accommodate the welder.

I also think its worth having *some* items be special cased. This is by no stretch going overboard.

**Comment by JoeHammad1844** [comment]
those look horribly out of style, try using the same colour pallet as the originals

**Comment by IProduceWidgets** [comment]
> those look horribly out of style, try using the same colour pallet as the originals

It is the same color palette taken straight from the originals. I kinda agree, I have not been able to make a sprite that looks better than a -45* rotation of the in-hand sprite.

**Comment by JoeHammad1844** [comment]
well, same colour pallet, but not the same colours in the same place, try doing that

**Comment by LordEclipse** [comment]
> The trash bag shape – I can't tell if that's meant to be a joke or if you really want to keep it that way, but in either case, I would kindly ask you to reconsider. It's a _bag_. It does not feel justified to me to turn it into a crude representation of a rubbish bin. Since most trash is 1x2, the proposed shape will make it much harder to fill the trash bag in a reasonable manner. It's also significantly harder to tell how full the bag is.
> 
> The medal case being so tall looks weird to me. A 4x2 arrangement of medals makes more sense than 2x4 in my mind and is less intrusive.
> 
> This change also alters the size (in number of grid squares) of several items. For instance, the mops now require twice the storage space, despite still having "size: normal" as far as I can tell;the multitool has shrunk to half its previous sizes; and the light replacer uses twice the number of squares and is impossible to fit nicely into a coat.
> 
> Overall, this sort of special-case shaping smells an awful lot of the arbitrary number system that was in the game prior to the inventory reworks. The more snowflake shapes there are, the harder it is to reason about storage. The more one deviates from "small = 2 squares, normal = 4 squares" and so on, the harder it is to reason about storage. It all becomes so, well, _arbitrary_.

Also the CE's toolbelt which is supposed to have more storage space just simply doesn't have more space

**Comment by IProduceWidgets** [comment]
> Also the CE's toolbelt which is supposed to have more storage space just simply doesn't have more space

Works for me, I hadn't changed anything about the belt size. I was just showing all the stuff fits. 

Ill add an extra 2x2 on the end.

**Comment by IProduceWidgets** [comment]
Knives
image

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
Every instance of the Small_Wide size should be replaced with a `storedRotation: -90` as #22258 will make it display with the piece rotated properly by default. There's no need to duplicate an item size as that is not what they're meant for.

**Comment by IProduceWidgets** [comment]
> Every instance of the Small_Wide size should be replaced with a `storedRotation: -90` as #22258 will make it display with the piece rotated properly by default. There's no need to duplicate an item size as that is not what they're meant for.

I tried this first, and it causes lots of parenting issues.

**Comment by EmoGarbage404** [comment]
> I tried this first, and it causes lots of parenting issues.
> 
> i.e you can reasonably put a size specifier on a base item, but doing so with storedRotation leads to pain.

internally, the parenting is handled the exact same and shouldn't have any issues. What exactly was the problem?

**Comment by IProduceWidgets** [comment]
If you parent a rotation, every entity after it needs a rotation or will be rotated (which is just normal parenting behavior).

This is weird though, as it means if you want to parent the functionality of something it also comes with the sprite elements, which can then only be replaced by doing another rotation. It just adds a bunch of seemingly unnecessary Item and storedRotation specifiers. 

Surely 22258 can handle both orientations (as well as unusual orientations)?

**Comment by IProduceWidgets** [comment]
Odds and ends:
image

**Comment by EmoGarbage404** [comment]
> If you parent a rotation, every entity after it needs a rotation or will be rotated (which is just normal parenting behavior).
> 
> This is weird though, as it means if you want to parent the functionality of something it also comes with the sprite elements, which can then only be replaced by doing another rotation. It just adds a bunch of seemingly unnecessary Item and storedRotation specifiers.
> 
> Surely 22258 can handle both orientations (as well as unusual orientations)?

i feel like if the majority of entities needs to be horizontal by default, it might make more sense to make the default shape for small be a horizontal 1x2. even still, rotations probably shouldn't be specified on BaseItem to begin with since they're tied to sprites which have lots of variation between each other in scale and shape and whatnot.

**Comment by IProduceWidgets** [comment]
Its honestly about 50/50 (I just didn't need to add any screenshots of items that didn't need to be swapped).

**Comment by IProduceWidgets** [comment]
And exactly! The Small_Wide prevents needing to add a rotation to base items, and can be easily switched with just an
type: Item
  size: Small

**Comment by IProduceWidgets** [comment]
This is a small thing, but I also think it would be strange to try to add an item, only to find that when you parent its base the sprite is rotated.

**Comment by IProduceWidgets** [comment]
Heres an example:

Say I wanna make High-heel boots.
I make my sprites upright, like would be normal to work on.

icon
equipped-FEET
inhand-left
inhand-right

But they're thigh highs and larger than regular boots, so I want them to be Normal sized.
Well, with Small_Wide, all I gotta do is make my entity and tell it the size.

image

Because the parent doesn't have a rotation, I'm done!

If don't have a size that is the 2nd most common item shape in the game,
I gotta add a second storedRotation: 0 to set it as not being sideways.

Seems bads.

**Comment by IProduceWidgets** [comment]
> internally, the parenting is handled the exact same and shouldn't have any issues. What exactly was the problem?

Heres an example:

Say I wanna make High-heel boots.
I make my sprites upright, like would be normal to work on.

icon
equipped-FEET
inhand-left
inhand-right
image4f001-4ce2-4a3d-8023-4dfcd1559e4f)

But they're thigh highs and larger than regular boots, so I want them to be Normal sized.
Well, with Small_Wide, all I gotta do is make my entity and tell it the size.

image

Because the parent doesn't have a rotation, I'm done!

If don't have a size that is the 2nd most common item shape in the game,
I gotta add a second storedRotation: 0 to set it as not being sideways.

Seems bads.

**Comment by IProduceWidgets** [comment]
Dropped Small_Wide and gave everything the spins.

**Comment by Errant-4** [comment]
Can you please also uncurse the botanical belt
image

**Comment by IProduceWidgets** [comment]
The hoe is a bit cursed, but it kind of always was.
image

**Comment by IProduceWidgets** [comment]
I atomized everything that seemed out of place or wasnt solely an adjustment for grid inv sprites.

**Comment by metalgearsloth** [comment]
Going to be merge conflict hell while it's this big so.

**Pull request closed without merging**
