### PR TITLE
Feature/medical belt changes

### PR DESCRIPTION
**Pull request by WPRobson**
## About the PR
Allows the medical belt to hold health analyzers, latex gloves and sterile masks #11173

**Changelog**

:cl: WPRobson
- add: change: medical belts can now store health analyzers, latex gloves and sterile masks

### CODE REVIEW

**Comment by WPRobson** [comment]
I seem to have messed up my fork slightly and it's showing the commits of my last PR for some reason

**Comment by Elijahrane** [comment]
Disagree with these really, if they don't have the space for a health analyzer they already have a slower one always on their person

**Comment by Kromabae** [comment]
It's a non Issue change so doesn't matter if it's in or not, so kinda what ever imo if you want medical main feedback for it

basically no one is gonna use it ever but it is medical equipment so meeh why not

**Comment by WPRobson** [comment]
Those are very valid options, but it doesn't hurt anything to let those items be stored in the belt?

**Comment by Elijahrane** [comment]
> Those are very valid points, but it doesn't hurt anything to let those items be stored in the belt?

It ruins the tradeoff of discrete vs PDA health analyzers.

Toolbelts and medical belts and supposed to be very specific and I don't think clothing should go in them. If it does go in them, then at least for consistency other belts need the relevant gloves/masks to be whitelisted too.

**Comment by Visne** [comment]
> then at least for consistency other belts need the relevant gloves/masks to be whitelisted too.

Sure, wyci.

**Comment by Cheackraze** [comment]
didnt the utility belt PR get closed because it was 'too powerful' to let it hold t-rays and gas analyzers? this goes even beyond that with clothing being stored in them

**Comment by metalgearsloth** [comment]
I'm curious why it has wrench whitelisted on master at least.

**Comment by Elijahrane** [comment]
> I'm curious why it has wrench whitelisted on master at least.

Medical wrenches are a thing for a reason lost to time. I think a few surgeries used one or something. I've seen it on SS13 and US and I have no idea what it's supposed to do.

**Comment by mirrorcult** [comment]
i dont see why they need to be able to store clothing. analyzer seems reasonable enough to put in it but, eh

**Comment by Emisse** [comment]
medical wrench no longer has uses in 13 besides for cryo tubes

**Comment by mirrorcult** [comment]
> medical wrench no longer has uses in 13 besides for cryo tubes

and the funny suicide

**Comment by ZeroDayDaemon** [comment]
Medical wrench at this point only has a unique suicide interaction iirc

**Comment by Visne** [comment]
Why was this closed? I still think it is a good change.

**Pull request closed without merging**
