### PR TITLE
Remove the shock collar.

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

Removes the shock collar and the associated objective from the game, replacing the spawn with an electropack.

## Why / Balance

It's evidently causing admin issues, given there needed to be an announcement made on top of the various bwoinks and bans I've seen about it. Furthermore I see absolutely zero reason a shock collar needs to exist in this game in the first place when the electropack serves the exact same function while also ignoring the obvious implications around a shock collar. 
If the goal is to be cruel or whatever do it with an implant or something similar that actually gives that implication and not something people are going up to sec asking to have put on them while wagging their tail. 

**Changelog**

:cl: Lank
- remove: Removed the shock collar and associated thief objective.

### CODE REVIEW

**Comment by DieselMohawk** [comment]
Used shock collars a bit, they feel very mean spirited and they don't give any downside outside of shocking the person.
Electropack will likely be better.

**Comment by BRINGit34** [comment]
It's been used a lot in a way that violates spacelaw. I have seen many instances of it being used to restrict movement when there is no threat to life or limb.

**Comment by beck-thompson** [comment]
Its one of those things that sounds like a good idea but people end up not being able to handle it :(

**Review by chavonadelal — CHANGES_REQUESTED** [review]
As one of his co-authors, it is very unpleasant for me that they want to cut it out, in fact flushing the work of several people down the toilet. Even if, to my great regret, the maintainers decide that this should be done (**although I strongly disagree with this**), it cannot be completely cut out of the game, it should remain available through the admin spawn, because there are many less useful things in the game that have been available exclusively through the spawn menu for years. Allow you to add this to maps or something else at your discretion. Moreover, according to the idea, there are two of them in the locker, and not one, as you have just done.

**Comment by VasilisThePikachu** [comment]
> As one of his co-authors, it is very unpleasant for me that they want to cut it out, in fact flushing the work of several people down the toilet. Even if, to my great regret, the maintainers decide that this should be done (**although I strongly disagree with this**), it cannot be completely cut out of the game, it should remain available through the admin spawn, because there are many less useful things in the game that have been available exclusively through the spawn menu for years. Allow you to add this to maps or something else at your discretion. Moreover, according to the idea, there are two of them in the locker, and not one, as you have just done.

I do understand your anger about this, the shock collars were actually brought up by me and another maintainer while the pr was opened about the... negative reactions that some players may find with the item. But other maintainers insisted on keeping it and that we were overblowing it, we also forgot to bring in admins to chat about this. 

Sadly, as we expected, some players reacted... weirdly with it. From what I heard admins have handed out a lot of warnings and bans in game, similar reactions in the discord chats (to the point where we even made an announcement to tell people to stop)

Even if it was kept in game, I don't think we would want anyone mapping it, as it would lead to the same issues as above. An admin is free to load the protype and sprite live during the runtime of a round. So it can be spawned by admins anyway if they choose to.

The eletropack IS staying, we are NOT removing it.

**Comment by Iced-Coded** [comment]
Hey, decided to share my opinion on this.
IMHO, I don't think that we should **completely** remove them. We could leave it as an admeme, since, it can be used for several pretty fun in-game events.

**Comment by chavonadelal** [comment]
> > As one of his co-authors, it is very unpleasant for me that they want to cut it out, in fact flushing the work of several people down the toilet. Even if, to my great regret, the maintainers decide that this should be done (**although I strongly disagree with this**), it cannot be completely cut out of the game, it should remain available through the admin spawn, because there are many less useful things in the game that have been available exclusively through the spawn menu for years. Allow you to add this to maps or something else at your discretion. Moreover, according to the idea, there are two of them in the locker, and not one, as you have just done.
> 
> I do understand your anger about this, the shock collars were actually brought up by me and another maintainer while the pr was opened about the... negative reactions that some players may find with the item. But other maintainers insisted on keeping it and that we were overblowing it, we also forgot to bring in admins to chat about this. 
> 
> Sadly, as we expected, some players reacted... weirdly with it. From what I heard admins have handed out a lot of warnings and bans in game, similar reactions in the discord chats (to the point where we even made an announcement to tell people to stop. Where it did not help)
> 
> Even if it was kept in game, I don't think we would want anyone mapping it, as it would lead to the same issues as above. An admin is free to load the protype and sprite live during the runtime of a round. So it can be spawned by admins anyway if they choose to.
> 
> The eletropack IS staying, we are NOT removing it. Just the collar

What's stopping this from staying in the game like dozens of unused items? Let the admins use it at their own discretion. Although I'm still categorically against touching the collar at all. A great thing. How many times have I bothered different people, including Emo, asking for help with it...

**Comment by LankLTE** [comment]
> Although I'm still categorically against touching the collar at all. A great thing. How many times have I bothered different people, including Emo, asking for help with it...

I’m not sure if you’re aware, but the electro pack is staying. The shock collar specifically has a very unfortunate implication that various players clearly abuse- so I see very little reason to keep it in the game at all.

**Comment by JIPDawg** [comment]
It sucks that it's being used to such a degree, I do feel the shock collar is better than the electropack. Simply as a not many people wear anything on their neck slot. As a thief or using thieving gloves I had planned on stealing the collar and putting it on a potential target and killing them with it cause it'd be hilarious, but then having to take off the backpack (much more noticable) and then putting the new one on is much harder. 

I also have yet to RP as the guy from SAW :(

**Comment by deltanedas** [comment]
shock collar isnt able to stunlock, so theyd rat you out instantly

**Comment by JIPDawg** [comment]
> shock collar isnt able to stunlock, so theyd rat you out instantly

But if I put it on stealthily in a crowded area they wouldn't know who did it. Also I had planned on using a camera and being in the next room.

**Comment by GoGoRoboto** [comment]
this might be the saddest day of my life (real, not lies)

I do agree that warden's fun should be restricted when funny things are added i support this

**Comment by NotSoDana** [comment]
All as I said in PR to add this item. It's been used a lot of times in a way that violates spacelaw, i don't mention that this collar fully out of logic of NT and human rights. From the begin, merging and giving s(hit)ecurities free use of it was failure idea.

**Comment by Iced-Coded** [comment]
> I’m not sure if you’re aware, but the electro pack is staying. 
There's no need for radical means when removing items (IMHO), we could just make it non-roundstart, either ordered by cargo, or, researched and made by R&D.

Or if you still think this will **still** cause lots of problems (which I don't see realistically, since, no weird player would go to such extent to get 1-2 items.) for players and admins - just make it an **admeme**, which, would completely make sure that players won't get their hands on it by normal means (and not just admins spawning it in.).

**Comment by EmoGarbage404** [comment]
i cannot take this shit anymore

**Comment by deltanedas** [comment]
erp squad in shambles :sob:

**Comment by Baptr0b0t** [comment]
We can change the collar to a belt or at boot slot.

**Pull request merged**
