### PR TITLE
FloatMathDSL, Shader Dev Window, Color Slider Breakout

### PR DESCRIPTION
**Pull request by Tyler-IN**
Requires space-wizards/RobustToolbox#1145

shader dev window

extract ColorSlider from MagicMirrorBoundUserInterface

minor shader tweaks

add crappy iced-over shader for testing

image

image

image

includes possible in-game adaptation of FloatMathDSL

### CODE REVIEW

**Comment by GlassEclipse** [comment]
If this is abandoned, I can take it over.

**Comment by AJCM-git** [comment]
Yes it is, IIRC the only thing that needs this to be done is addresing the reviews in the engine-side PR

**Comment by AJCM-git** [comment]
Yes it is, IIRC the only thing that needs this to be done is addressing the reviews in the engine-side PR

**Comment by DrSmugleaf** [comment]
Superseded by https://github.com/space-wizards/space-station-14/pull/2572

**Pull request closed without merging**
