### PR TITLE
Anomaly Core - Usage Effect

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Anomaly cores can now be used to trigger the pulse effect of the corresponding anomaly with a 3-second delay. This can only be done with a decaying core. Inert cores lose this property. Once used, the core is completely destroyed.

## Why / Balance

Continued work on the anomaly cores. Adding individuality to different cores. Cores are now useful for antagonists.

## Technical details

Anomaly cores use the same anomaly effect components (like EntityAnomalyComponent), but the OnPulseAnomalyEvent event is invoked for them via a core interaction.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/fa922891-2f96-45d1-9d9a-b70f4c2795ac

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: You can now use decaying anomaly cores to cause a one-time pulse effect of this anomaly.

### CODE REVIEW

**Comment by lzk228** [comment]
they activates on using or when you throw them?

**Comment by TheShuEd** [comment]
after activation, with a 3-second delay

**Comment by GoodWheatley** [comment]
imo I think it would be a better idea to also implement the anomaly-specific buff from consuming a core over this if we want to make them useful for antagonists. Most supercritical effects are already going to mess the station up, and having a decaying core just make a pulse if you throw it isn’t going to be as useful in terms of destruction.

**Comment by TheShuEd** [comment]
There will be a separate PR that adds recipes for dishes with cores. And these dishes will have positive effects.

**Comment by notquitehadouken** [comment]
mmm, grenades

**Comment by TheShuEd** [comment]
If you think about it that way, it's true - after the supercrit of the anomaly the station will already be in chaos, and a grenade with one ripple of the same kind of chaos, with a limit of 10 minutes - somehow uninteresting. Hmm. What will be the options for interesting effects?

**Comment by UbaserB** [comment]
> If you think about it that way, it's true - after the supercrit of the anomaly the station will already be in chaos, and a grenade with one pulse of the same kind of anomaly, with a limit of 10 minutes - somehow uninteresting. Hmm. What will be the options for interesting effects?

i made a list of functions AGES ago let me find it on discord… when i was discussing it there was a lot of agreement iirc

**Comment by UbaserB** [comment]
liquid anomaly: medicine (could be randomised or omnizine even)
blackhole anomaly: minibomb
pyro anomaly: fire bomb (sets nearby people on fire)
meat anomaly: can be eaten or cooked into a very nutritious food
ice anomaly: cools the nearby area (can work as a portable freezer for atmos for eg?)
rock anomaly: is a package of “ores” that can be smelted
electrical anomaly: automatically recharging battery
bluespace: emergency teleporter (one use)

**Comment by TheShuEd** [comment]
As far as I understand, the effect should only work during core decay. Once it's decomposed, it's useless. That's why effects on a permanent effect, like a cooling refrigerator sounds strange

**Comment by UbaserB** [comment]
> As far as I understand, the effect should only work during core decay. Once it's decomposed, it's useless. That's why effects on a permanent effect, like a cooling refrigerator sounds strange

makes sense. I was just suggesting ideas.

**Comment by VektorZ1** [comment]
I think if one realizes the core-garnet idea, one should make them cheaper and probably use an inert core. It would be better to kraft 3-6 grenades from one core. Otherwise it's too expensive and almost a pointless feature

**Comment by TheShuEd** [comment]
Perhaps in the future I will make a second version of this PR

**Pull request closed without merging**
