### PR TITLE
traitors are more sociable (not just among themselves anymore)

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

The traitors have 2 new objectives, they can now be required to have a head or an ordinary humanoid fly off to CentCom alive and free

## Why / Balance

At this point, the traitors don't look like what I'd like to see them look like. They're regular villains with black morals who only help each other (unless they got opposite goals). That's not cool, antagonists should make the round interesting. For everyone. 
My objectives will cause conflict among the traitors. They'll have to talk to each other more carefully and go to the point of killing much less often. Killing for highrisk isn't cool. 
The man has a target on the CMO hypospray? haha, he'll kill it of course since that's the most encouraged way to go. By killing you get the items and your coveted highrisk. Now that very CMO (probably) needs to be rescued by another agent, which will cause a business conversation or massacre between the two of you. It's more interesting, imho
Also, my objectives can cause fun, like "Steal the senior engineer's magnetic boots and make sure he flies off to CentCom".
From time to time, the traitors will have to save the scientist from himself, because he is very important to his employers.

More gray morality for agents is cool.  

Maybe I should engage in some petty trolling so the agent doesn't know if he needs to rescue a coworker or a regular person.
## Technical details

I'm not quite sure about `GetProgress`, at least it worked correctly during the test
I'm not sure about line 149 of `Resources/Prototypes/Objectives/traitor.yml`, I didn't have the intelligence to figure out if I'm right or not
now two lists are declared in the `KillPersonConditionSystem` class:`killPersonTargets` and `killHeadTargets`. My system is tied to them
I didn't understand where I should get the `TargetObjectiveComponent` from, so I made getting it so silly. Please, if this is creating a problem, help me solve it
## Media

изображение
(objectives are issued through the console, they can't be in that order in the game)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Traitors may be tasked with evacuating a head or regular humanoid.

### CODE REVIEW

**Comment by lzk228** [comment]
write normal cl instead of that goofy rp cl

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Please don't just copy-paste killpersoncondition code.

**Comment by icekot8** [comment]
> write normal cl instead of that goofy rp cl

ok.

> This is just the protect target objective?

yes. 
existing target on defense... too easy. an agent can stand up for himself, a head or a greytide is more often no than yes.
I regret writing such a heavy description.

**Comment by K-Dynamic** [comment]
Wouldn't this kinda blur the line on 'friendly' traitors? You might need to remind the traitor not to give out contraband to a head or something

> This is just the protect target objective?

Can you roll protecting non-traitors as an objective?

**Comment by Krunklehorn** [comment]
As it stands, protecting a rando doesn't seem too exciting, even they're a member of command.

Would it be too much to ask for something more like a VIP condition that purposefully forces two traitors against each other?

"This is your target, kill/protect them, but watch out, someone else has been hired to protect/kill them as well."

**Comment by Dragonjspider** [comment]
My interpatation of that is more of a test to see if the agent has what it takes to defend a target who can't defend themselves as well, or a test to see if the agent who plans on killing the target can work under higher pressure than usual.
Like some kind of field practice if you get what I mean.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
I think this is a very non-objective, as it currently stands. Whether or not you get it or not is basically just up to luck deciding not to obliterate your target. I think it should probably be limited to a crew member who is already targeted by others as it means there's a more tangible threat and ability to introduce conflict between syndies.

**Comment by icekot8** [comment]
> I like this but wouldn't this kinda blur the line on 'friendly' traitors? You might need to remind the traitor not to give out contraband to a head or something

I think this is more of a question for the head who accepted the contraband. This can also be seen as a contradiction in goals. The head must be **free**. If the quartermaster happens to have an energy sword, he will most likely not be free.

> Would it be too much to ask for something more like a VIP condition that purposefully forces two traitors against each other?
> 
> "This is your target, kill/protect them, but watch out, someone else has been hired to protect/kill them as well."

I was thinking about it last night and liked the idea, started making it, and then saw EmoGarbage404's comment this morning and realized the system is complete garbage.
Duels are a topic for a separate PR, and I'll make one if this one gets merged.  I don't feel like working having the opportunity to get "We don't want antagonists fighting for regular people."

Duels, in my opinion, should be something more than the currently proposed objective. 2 agents should get a minimum of objectives other than dueling. That would be a real duel. Right now the assassin may or may not get resistance, I think that is fair
> I think this is a very non-objective, as it currently stands. Whether or not you get it or not is basically just up to luck deciding not to obliterate your target. I think it should probably be limited to a crew member who is already targeted by others as it means there's a more tangible threat and ability to introduce conflict between syndies.

thank you so much for your review, I thought about it for two and a half hours and realized how to implement it. The PR is ready for merge, I hope.

I also changed the technical details in the text of the PR, but to write that the target can only be on the already target... I do not see the point.

**Comment by keronshb** [comment]
> Steal the senior engineer's magnetic boots and make sure he flies off to CentCom

This plays into the friendly antagonist issue. While yea they're stealing something, forcing them not to kill in their objs allows the antagonist to be more friendly.

Also think of the implications needed. For an agent to steal magboots AND let the CE fly off, assuming the CE has them on them, they'd have to not only stun the CE somehow, but they'd also need a way to prevent the CE from ratting them out.

Putting a stun weapon into the Traitor arsenal has proven to be awful (EBow), and forcing traitors to steal security equipment just makes a meta.

Then you also need to deal with the CE, who won't be happy that their boots were stolen.

Also what happens if the CE dies to someone else after you stole the magboots? I doubt the CE would want you to stick around them to protect them, after stealing their property. Do you try and kill the other traitor out of revenge? Would it even matter since the CE already died?

**Comment by keronshb** [comment]
> I think this idea has a lot of roleplay potential as it means you either need nonlethal means or kill them but let them get revived and evac to CC - not necesarily friendly

The kill - throw to meds to revive - tactic doesn't work.
For servers that allow you to remember how you died, it makes it hard for the traitors to add any intrigue.
For the servers that don't, it's exceptionally hard to enforce anyway.

> * Heads that know you're a syndie could still be threatened to hand over their item

Doesn't stop them from going to Security after.

It also starts to become a grey admin rule.
"It says you had to protect me/get me onto t he shuttle but you killed me and stole my boots!"

**Comment by Emisse** [comment]
this needs admin team discussion

**Comment by IProduceWidgets** [comment]
Friendly antags doesnt make any sense. If you want a rare extra hard kill objective, dont bank on the (ludicrously rare) chance of two antags having a conflicting protect and kill objective, and instead just make a non-antag crewmember have an objective to keep someone alive instead. Way more engaging, and makes more sense.

**Comment by ps3moira** [comment]
Meta-friending syndicate and friendly antags just doesn't make sense for, well antags.

**Comment by K-Dynamic** [comment]
This PR has kinda stuck on my mind for a while so I wanna leave my thoughts to the author

What if it was reframed so traitors have to *kidnap* non-antag targets? (Keep alive but restrained, maybe evac or maroon or bluespace away idk)

That way there's the social element where traitors might conflict with one another, but are much less likely to be friendly with their target (who won't want to be restrained and might still get hurt or knocked out)

**Pull request closed without merging**
