### PR TITLE
Fix projectiles and vehicles

### PR DESCRIPTION
**Pull request by metalgearsloth**
- Projectile collision gets relayed to the rider
- Can shoot from vehicles
- Hitscan too

:cl:
- fix: Shooting at and shooting from vehicles now works as expected

### CODE REVIEW

**Comment by mirrorcult** [comment]
superseded by #10477

**Comment by metalgearsloth** [comment]
Will make some tweaks but it also fixes https://discord.com/channels/310555209753690112/790656972801572905/1008328931893579836

**Review by wrexbe — DISMISSED** [review]
- made segway
- made gun
- picked up gun
- got on segway
- driving around, firing my gun a bunch, bullets not working
- segway I was driving blew up, guess it was shooting my vehicle
- sad, no merge

**Comment by wrexbe** [comment]
- updated PR to master
- shooting from segway didn't blow up the segway
- effect is still in the wrong direction

**Pull request merged**
