### PR TITLE
Hotfix babyproof arrivals terminal and arrivals shuttle

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Merge #33284 and #33281 into staging, as a hotfix. Make arrivals terminal and arrivals shuttle invulnerable to most damage

## Why / Balance
Admins wanted this out on live faster than the next release cycle

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: IProduceWidgets
- fix: The terminal is more tamper proof.
- fix: Arrivals shuttle is more tamper proof.

### CODE REVIEW

**Comment by Errant-4** [comment]
1. Does this actually need a CL entry, or will the one on master be already in the changelog?
2. Squash or not?
3. Needs 2 more approvals due to being hotfix

**Review by SaphireLattice — APPROVED** [review]
1. Axe the changelog entry in the PR description itself cherry-pick the change of existing ones
2. Squash should be fine, conflict resolution will suck but nothing too awful. Honestly not sure what procedures are for messing with changelog. **We'll need to document this later**
3. Approved with condition this passes tests, as the two PRs have already been approved

**Comment by Errant-4** [comment]
Added CL entries from the original PRs, I guess we will undupe that bridge when we get there

**Comment by SaphireLattice** [comment]
Note: Check failure is due to the labeler

Something to fix as I've noted in `#maintainers` on Discord

**Comment by SaphireLattice** [comment]
Not required for now, I suppose

**Comment by SaphireLattice** [comment]
And I'm a dumbass and did a wrong pr

**Review by slarticodefast — APPROVED** [review]

**Pull request closed without merging**
