### PR TITLE
Pacifier

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR

Adds pacifier. Also pacifier can spawn in maint clothing loot spawner.
Pacifier have mumble accent

## Why / Balance

idk why, but i think that's must be in game. Anyway, you can't deny that it's fun and cute UwU

## Media

{5F933B99-5F63-4808-87F6-9FCA8A91B6C6}
{CF75F846-BF41-4C39-A0F0-997616EF0010}
{71B4117C-0ABE-4CBC-837A-77C9642BB757}

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:Ko4erga
- add: Added pacifier.

### CODE REVIEW

**Comment by ScarKy0** [comment]
If you can please give the cat ears speech pattern to anyone wearing it thatd be golden

**Comment by Ko4ergaPunk** [comment]
move a little for hamster

**Comment by NotSoDana** [comment]
Wtf man...

**Review by TheShuEd — CHANGES_REQUESTED** [review]
Displacement maps > Tons of similar sprites

**Comment by Ko4ergaPunk** [comment]
Damn, i don't know how to draw displacement maps >m<

**Comment by VasilisThePikachu** [comment]
Thanks for your pr, unfortunately we don't think this has a purpose for upstream.

**Comment by foob1** [comment]
we are NOT doing this again

**Comment by GentleButter** [comment]
bruh. D:

**Comment by ilikeships** [comment]
coalest of the coal

**Pull request closed without merging**
