### PR TITLE
Scale radiation intensity with stack size

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title
goes from 0.1 up to 1.0 intensity at full size

## Why / Balance
being able to stack up 10 bananium and have the same radiation as 1 doesnt make sense
also doesnt make sense that you could have 10 bananium on the same tile and it would heavily irradiate that 1 tile but not spread since their intensity wouldnt combine

makes handling lots of bananium more dangerous as a result

## Technical details
just changed radiation gridcast to check stack size

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Bananium's radiation intensity increases in large stacks now.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
if we're merging this the value needs to be way more sane because 3 rads for a stack is literally equivalent to a small singulo

**Comment by deltanedas** [comment]
1.0 for a stack?

**Comment by Partmedia** [comment]
When *shouldn't* radiation intensity increase when stacked? Why make it a separate component, instead of checking for a stack in RadiationSystem?

**Comment by deltanedas** [comment]
then id have to add baseIntensity to every radiation source (admittedly there arent that many) or have float inaccuracies pile up by restacking and dividing multiplying over and over

**Comment by Partmedia** [comment]
> then id have to add baseIntensity to every radiation source (admittedly there arent that many) or have float inaccuracies pile up by restacking and dividing multiplying over and over

I don't understand what you think the problem is. Instead of storing the cumulative radiation source, why not just multiply by the number of items in the stack at time of use in `UpdateGridcast()`?

**Comment by deltanedas** [comment]
o thats smart

**Comment by Partmedia** [comment]
New patch looks great, thank you very much. I'll give it a quick local test soon.

**Review by Partmedia — APPROVED** [review]

**Pull request merged**
