### PR TITLE
Donk co. microwave + microwave tweaks

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Adds the Donk co. microwave, which replaces the microwave at the nukie base & shuttle. It cooks x2 as fast, at the cost of being more likely to explode (10% to 30%) from cooking unsafe stuff. It cannot cook Id cards without exploding.

Microwave explosions now spit out the machine parts and delete the board from the machine.

## Why / Balance

Stops nukies from getting AA for cheap.

Makes microwave explosion not be a simple fix of crowbar + screwdriver.

## Technical details

Adds a new field to MicrowaveComponent for Ids, which the Id card system checks when microwaving. Made both types of microwave explosions call a new mthod which does the part ejecting and board destruction.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/32827189/641d3e8b-1b93-48c9-b862-c351a78c3f42

https://github.com/space-wizards/space-station-14/assets/32827189/0f14d1cc-974c-4abd-8a19-d5db99135476

https://github.com/space-wizards/space-station-14/assets/32827189/4fa47869-5088-408b-a84f-22d9863617f4

## Breaking changes

probably not
**Changelog**

:cl:
- add: Nukie planet now has an improved Donk co. microwave, which cooks twice as fast but is more likely to explode. It can't handle id cards without exploding.
- tweak: Made microwave explosions destroy the machine board and spit out the machine parts.

### CODE REVIEW

**Comment by ElPidor** [comment]
That would be funny idea for a syndi cook to have an ability of making donk ko food.

**Comment by Holinka4ever** [comment]
There is also microwave in ship, so what about to change it too?

**Comment by EmoGarbage404** [comment]
TBH i think it would be better to just make this microwave completely unable to work with ID cards. I don't think the limited randomness it enables by having a probability is particularly beneficial, especially when that balance can still be extremely strong and enable nukie teams to storm entire departments.

**Comment by Vermidia** [comment]
Sure

**Pull request merged**
