### PR TITLE
RPED

### LINKED ISSUE #3044: Part exchanger
We need a part exchanger for upgradeable machines so you don't have to disassemble the machine to change the parts.

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
adds the RPED as a science tech. For making all of your machine upgrading woes just a bit better.
the actual place in the science tree (like most things) is a bit arbitrary and should probably be changed.

Closes #3044 
**Screenshots**

**Changelog**

:cl:
- add: Added the Rapid Parts Exchange Device. Just load it up with parts and click on a machine to instantly upgrade it.

### CODE REVIEW

**Comment by theashtronaut** [comment]
Does it require the maintenance panel to be open to replace parts? It didn't look like it did when I looked at the AfterInteract

**Comment by EmoGarbage404** [comment]
> Does it require the maintenance panel to be open to replace parts? It didn't look like it did when I looked at the AfterInteract

It doesn't. Is that a relevant feature from 13 that matters? I feel like needing a screwdriver is a bit superfluous.

**Comment by theashtronaut** [comment]
It is how it worked in SS13 for the RPED (not the stupid BRPED that should never be added). The idea was the RPED can't actually replace parts if the machine isn't 'open' to get at those parts. If that functionality is not desired it's not really a big deal :woman_shrugging:

**Comment by EmoGarbage404** [comment]
> It is how it worked in SS13 for the RPED (not the stupid BRPED that should never be added). The idea was the RPED can't actually replace parts if the machine isn't 'open' to get at those parts. If that functionality is not desired it's not really a big deal tho 🤷‍♀️

Yeah u right im lazy and eating apple slices rn ill go code it in like a minute.

**Comment by Streaky-Haddock** [comment]
If you use an RPED with the panel CLOSED, it will tell you what parts are inside. With the panel open, it'll try to swap lower components for higher. That's the purpose of the screwdriver, really.

**Comment by EmoGarbage404** [comment]
> If you use an RPED with the panel CLOSED, it will tell you what parts are inside. With the panel open, it'll try to swap lower components for higher. That's the purpose of the screwdriver, really.

The one thing worth noting is that not all machines have wire panels. Maybe I'll keep that functionality as an alt verb.

**Comment by theashtronaut** [comment]
> If you use an RPED with the panel CLOSED, it will tell you what parts are inside.

I was a fan of the idea that when examining an upgraded machine, the examine tooltip would tell you what upgraded parts are in it and what they were doing to the machine. see https://github.com/space-wizards/space-station-14/issues/11530

**Comment by EmoGarbage404** [comment]
> > If you use an RPED with the panel CLOSED, it will tell you what parts are inside.
> 
> I was a fan of the idea that when examining an upgraded machine, the examine tooltip would tell you what upgraded parts are in it and what they were doing to the machine. see #11530

Showing average rating definitely isnt that difficult but showing effects would have to be done on a per-machine basis. I'll look into showing part ratings on examine though.

**Comment by EmoGarbage404** [comment]
fixed the thing that was causing test fails on this for like literal weeks that i just somehow didn't notice.

**Pull request merged**
