### PR TITLE
Fix gauze eyepatch flying pixel

### PR DESCRIPTION
**Pull request by fqqf**
## About the PR
Fix gauze eyepatch flying pixel

## Why / Balance
- Fix gauze eyepatch flying pixel

## Technical details
- Fix gauze eyepatch flying pixel

## Media
before: 
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by slarticodefast** [comment]
I cannot see the pixel in there. Are you sure you got the right file?
grafik

Also this does not need a changelog.

**Comment by fqqf** [comment]
> I cannot see the pixel in there. Are you sure you got the right file? grafik
> 
> Also this does not need a changelog.

thats because you cant see it on blue. Use black
image

**Comment by fqqf** [comment]
> Also this does not need a changelog.
removed it

**Comment by slarticodefast** [comment]
Found it. That is the most evil hidden pixel I've ever seen. Photoshop does not even select it due to low transparency.
Thanks for the fix!

grafik

**Review by slarticodefast — APPROVED** [review]

**Pull request merged**
