### PR TITLE
don't require salvage map prototypes to specify their bounds

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

I just made salvage maps use the same thing as the asteroids.
The grids are spawned on a separate map and the bounds are calculated there.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

MAP MORE SALVAGES NOW. THIS IS NOT A DRILL. MAP EM BIG. MAP EM GOOD. JUST MAP EM.

### CODE REVIEW

**Comment by Aisu9** [comment]
I know Z axis is highly experimental at this point, but wasn't it supposed to be used on salvages maps to make them "big"?

**Comment by moonheart08** [comment]
> I know Z axis is highly experimental at this point, but wasn't it supposed to be used on salvages maps to make them "big"?

what Z axis??

**Comment by Nails-n-Tape** [comment]
> > I know Z axis is highly experimental at this point, but wasn't it supposed to be used on salvages maps to make them "big"?
> 
> what Z axis??

yeah, someone did a serverwide test on z levels a while back. dunno who or when tho.

**Comment by Emisse** [comment]
> > > I know Z axis is highly experimental at this point, but wasn't it supposed to be used on salvages maps to make them "big"?
> > 
> > 
> > what Z axis??
> 
> yeah, someone did a serverwide test on z levels a while back. dunno who or when tho.

moony was the one who made that

**Pull request merged**
