### PR TITLE
Makes secure crates harder to break into

### PR DESCRIPTION
**Pull request by Peptide90**
Made a metallic damage type that can't be damaged below a rather high threshold (read: nearly impossible to break without high end weapons like captains sabre or guns / laser weapons). This means far less cargonia.

:cl:
- tweak: Sad day for Cargonia. All secure crates have been buffed so your basic tools won't break them anymore,

### CODE REVIEW

**Comment by Mith-randalf** [comment]
yo can this be applied to doors

**Comment by Peptide90** [comment]
Fixes #5742

**Comment by TimrodDX** [comment]
I only partially agree with this. I think that without the emag being in, this makes cargo traitor borderline impossible. Raising the threshold on the gun crates is fine, since that gives security plenty of warning when they hear the inevitable emitter noises - but I think cargo should be reasonably able to build an AME if they want, or get bombsuits.

A better solution would be to implement order history on the console and put cargo computers in the HoP office/on the bridge in most stations to make it clear if and when cargo orders guns.

**Comment by Mith-randalf** [comment]
What if I PR an initial version of the emag (opens + breaks doors, crates, lockers)? Both will merge at the same time cos feature freeze right?

**Comment by Peptide90** [comment]
> I only partially agree with this. I think that without the emag being in, this makes cargo traitor borderline impossible. Raising the threshold on the gun crates is fine, since that gives security plenty of warning when they hear the inevitable emitter noises - but I think cargo should be reasonably able to build an AME if they want, or get bombsuits.
> 
> 
> 
> A better solution would be to implement order history on the console and put cargo computers in the HoP office/on the bridge in most stations to make it clear if and when cargo orders guns.

Fair comments. It's simple to for now just set the parent for those crates back to genericcrate rather than basesecurecrate or however I named it.

2nd solution assumes you have competent players which right now we do not. We have cargonia every single round and self antags. In Ss13 I don't recall ever being able to break into a crate without a mining mech but I do agree maybe gun crates should realistically be more secure than bomb suit crates or w/e.

**Comment by Peptide90** [comment]
On second thought no I think this stands. Cargo shouldn't be able to get stuff in secure crates and if they do want it then they can steal an ID or get HoP.

Cargo making AME is bad stuff.

**Pull request merged**
