### PR TITLE
New manual external

### PR DESCRIPTION
**Pull request by SonicHDC**
## About the PR

New manual opening variant of external airlock.
## Why / Balance

It was only one type airlocks what can open like a doors but closes automatically. Good thing for small corridors/rooms, save players in "moving lag" moments.
The best for mappers. Sometimes they can't fit 2 locks cycle system.

## Media

loks

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: SonicHDC
- add: Added manual external airlocks!

### CODE REVIEW

**Comment by lzk228** [comment]
why?...

**Comment by Hmeister-real** [comment]
> why?...

To avoid accidental spacing, very useful imo

**Comment by lzk228** [comment]
just make default external airlocks not opened on bump

**Comment by deltanedas** [comment]
shrimbly link doors to bolt eachother and prevent instant spacing

**Comment by SonicHDC** [comment]
> The best for mappers. Sometimes they can't fit 2 locks cycle system.

I just want add a special airlock, for small constructions. And not for arrivals or evac.
Good door for old builded things, without sensors on lock.

**Comment by Partmedia** [comment]
Could you better explain/demonstrate what purpose this new airlock is designed to serve? My worry is that having too many variations confuses the function, which may or may not be better served by a different configuration of the airlocks that we already have.

**Comment by metalgearsloth** [comment]
Re-open if you come back to it + get emisse approval.

**Pull request closed without merging**
