### PR TITLE
Replace Cellular Slime mob damage with Caustic

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR removes Cellular from the slime mob, replacing it with Caustic.

## Why / Balance

With the changes introduced in #32209 and #32136, Cellular is made into a more deliberately caused damage type that is more complex to heal. Slimes dealing Cellular was added when they were first introduced and I can't find any solid reasoning for it.

Caustic is still not the easiest damage to heal so the change to Caustic should be appropriate.

## Technical details

Yaml change.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Slimes no longer deal Cellular damage.

### CODE REVIEW

**Comment by thebadman4662** [comment]
> Its easier to heal cell. than caus. Cell. - fal + ari (easy 1-2 steps chems) Caus. - siginate (very complex recipe) or very inefficient healing using ointment

Pha will require Sig/oints soon due to different PR of Slam, so this one is just making Dox/Pha giga niche in this PR as only grey matter poison/eating brains/failed implanting will cause it. New Pha would be dogwater compared to Dox-Cryo mix in pretty much all scenarios.

**Comment by keronshb** [comment]
Slimes dealing cellular damage is brought from SS13.
They should be doing cellular since they're absorbing when they eat (or attack).

**Comment by SlamBamActionman** [comment]
> Slimes dealing cellular damage is brought from SS13. They should be doing cellular since they're absorbing when they eat (or attack).

I don't think an in-universe reason should trump gameplay, especially since it's debatable whether it applies here (only the yellow slimes do cellular, so it seems more like the damage type acts to differentiate them as another "type" of slime compared to blue or green, rather than representing "eating").

With the cited PRs and this one, cellular would only be dealt via:
1. Rotting.
2. Eating brains.
3. Benzene reagent.
4. Failed implant checking.

Excluding slimes from this makes the damage type come from more controlled and unique circumstances, making it possible to design its treatment much more deliberately compared to if it's being dealt by a random vent mob.

**Comment by keronshb** [comment]
> Excluding slimes from this makes the damage type come from more controlled and unique circumstances, making it possible to design its treatment much more deliberately compared to if it's being dealt by a random vent mob.

It's still fine for slimes to deal cellular damage, though.
Although all types of slimes should be doing cellular and not a single color.
I think an in universe explanation is fine enough sometimes.

Sounds like we don't have the same slime eating that SS13 has yet, which should be ported over (allows them to do mitosis and grow).

I would say it's not too far of a stretch to give them cellular damage because they "absorb"

**Comment by SlamBamActionman** [comment]
> It's still fine for slimes to deal cellular damage, though. Although all types of slimes should be doing cellular and not a single color. I think an in universe explanation is fine enough sometimes.
> 
> Sounds like we don't have the same slime eating that SS13 has yet, which should be ported over (allows them to do mitosis and grow).
> 
> I would say it's not too far of a stretch to give them cellular damage because they "absorb"

Let me see if I can explain what I mean with its use being more deliberate as a damage type.

With the proposed changes to Phalanx in the linked PR, Cellular will be *a lot* slower to heal and more complex to treat. This is because it will be largely dealt to a single character as a form of punishment for a choice they made; eating a brain or failing an implant check > causes Cellular damage > Cellular is hard to heal and forces you to spend a long time in medbay > you don't want to eat a brain/fail an implant check.

Slimes, as a random vent spawn, take that agency away from the player. You are often forced into taking some amount of damage, and if that is Cellular... Now you'll be sent packing to medbay for a deliberately extra slow treatment through no real fault of your own.

I think it's fair to say that lying in a medical bed waiting for a reagent to metabolize is boring. That is fine if the player knowingly chooses to inflict that damage onto themselves, less so if the game decided to spawn a slime in the same room as you.

(And to address the other ways to take Cellular: Benzene is so low damage you never see any chemist try to use it for poison, and rotting is its own special case that requires rare cryo drugs to fix anyways.)

**Comment by thebadman4662** [comment]
> (And to address the other ways to take Cellular: Benzene is so low damage you never see any chemist try to use it for poison, and rotting is its own special case that requires rare cryo drugs to fix anyways.)

Me making grey matter pill, feeding it to hos then feigning ignorance how to make cellular meds as they are permanently in near crit... or 20u kept them in crit forever till medication? :trollface:

**Comment by SlamBamActionman** [comment]
> > (And to address the other ways to take Cellular: Benzene is so low damage you never see any chemist try to use it for poison, and rotting is its own special case that requires rare cryo drugs to fix anyways.)
> 
> Me making grey matter pill, feeding it to hos then feigning ignorance how to make cellular meds as they are permanently in near crit... or 20u kept them in crit forever till medication? :trollface:

Hey, if you get your hand on a brain or three, who am I to stop your beautiful antaggery? 😉

**Comment by keronshb** [comment]
> Slimes, as a random vent spawn, take that agency away from the player. You are often forced into taking some amount of damage, and if that is Cellular... Now you'll be sent packing to medbay for a deliberately extra slow treatment through no real fault of your own.
> 
> I think it's fair to say that lying in a medical bed waiting for a reagent to metabolize is boring. That is fine if the player knowingly chooses to inflict that damage onto themselves, less so if the game decided to spawn a slime in the same room as you.

I have comments for the implant check PR but I'll save it for that.

I see what you're trying to go for, but thematically for slimes they've always been cellular damage. I don't really see the issue allowing a creature to deal some cellular damage.

That being said, unless there's some sort of guideline or comments somewhere of "this is where you can and cannot use this damage type", I don't really see the issue per say of giving them to slimes. It also makes slimes that much more dangerous and a reason for people to be scared of them, no?

**Comment by SlamBamActionman** [comment]
> I see what you're trying to go for, but thematically for slimes they've always been cellular damage. I don't really see the issue allowing a creature to deal some cellular damage.
> 
> That being said, unless there's some sort of guideline or comments somewhere of "this is where you can and cannot use this damage type", I don't really see the issue per say of giving them to slimes. 

I can very bluntly say I do not care what slimes have thematically been previously. Not only is it untrue for SS14, where Caustic have been the main shared slime damage type, but at its core they're *slimes*. Probably one of the most malleable creature when it comes to its properties (unlike say snakes, which are known to be venomous). "Slimes ruin the DNA of their targets" is something we can just decide isn't canon anymore. Hell, replace Cellular with Poison and say "They're mutated toxic sludge" and presto, it makes sense in-universe.

There is no guideline or comment because there is no design document around this yet. So if I need to make it official:

`Should this PR to through, Cellular should only be used in very deliberate cases where a difficult- and slow-to-heal damage type is warranted. This would either be cases where the damage is brought upon the player themselves as a kind of tradeoff, or unique circumstances where the damage is meant to leave lasting consequences beyond normal damage types.`

> It also makes slimes that much more dangerous and a reason for people to be scared of them, no?

There's a difference between being scared of a mob because you will take damage, and the feeling of trepidation at to spending a long time in Medbay through no fault of your own. 

Caustic is more than enough reason to want to avoid being injured by slimes. Its a damage type that is slow and annoying to heal if Medbay hasn't specialized in caustic treatment, but it isn't impossible (ointment heals minor Caustic) and if Medbay has put in the proper work it can still be treated fairly quickly.

**Review by keronshb — APPROVED** [review]
After thinking it over a bit, trying to narrow cellular down to a single type is probably for the better. Fix the test and this is good to go. Since you're also a maint this is 2/2 approvals.

**Pull request merged**
