### PR TITLE
Gun prediction

### PR DESCRIPTION
**Pull request by metalgearsloth**
Hopefully I didn't balls anything up.

Still needs more work given container and interaction predictions weren't in but it should be easier to add now.

- Hitscan moved into a prototype instead of a component
- Predicted camera recoil and muzzle flash. Currently hitscan lasers aren't predicted because it needs seeded randomness and I out of scoped it
- Removed RangedWeapon and moved the functionality elsewhere
- Refactored the overall gun structure to be less messy. Shooting goes through the respective client / server-side systems. Inheritance is now SharedRangedWeapon > SharedWeaponType > Client / Server weapon type.
- Audio variations to sounds and made them easier to adjust (const floats)
- Support for firerates higher than tickrate
- When a revolver is spun the CurrentSlot is now hidden until you shoot (russian roulette)
- Removed AmmoBox component

Still TODO for guns:
- Predicted interactions
- Predicted containers
- Predicted hitscan lasers
- Predicted entity spawning (low prio)
- inhand visualizers

Functionality should be identical, it was mostly a refactor. Because I moved some stuff around it might also not reflect exp, PJB and py01's work that's still in there (IItemStatus, Linspace, etc.)

I'm still kind of suss on the shooting code so if someone could double-check that especially that'd be great (it's under the client / server-side RangedWeaponSystems + SharedRangedWeapon).

### CODE REVIEW

**Comment by PJB3005** [comment]
I have containers theoretically predicted in a branch, but I haven't tested it yet.
 
https://github.com/PJB3005/space-station-14/tree/20-10-04-container-predict
https://github.com/PJB3005/space-station-14-content/tree/20-10-04-container-predict

**Comment by metalgearsloth** [comment]
> 
> 
> I have containers theoretically predicted in a branch, but I haven't tested it yet.
> 
> https://github.com/PJB3005/space-station-14/tree/20-10-04-container-predict
> https://github.com/PJB3005/space-station-14-content/tree/20-10-04-container-predict

I can give it a try though without interaction as well it doesn't allow the interactions to be fully predicted.

**Comment by metalgearsloth** [comment]
(Also build's failing because it needs RT update I think).

**Comment by metalgearsloth** [comment]
(God damnit I forgot the clumsy check still)

**Comment by metalgearsloth** [comment]
If someone wants to pick this up LMK as I won't get a chance to finish it for a few months. It needs interaction + container prediction added and likely further work on the ranged weapon systems.

**Comment by metalgearsloth** [comment]
Closing for the time being until I can come back to it (80% of the work is done overall as it needs interaction prediction + entity spawning prediction to work really well).

**Pull request closed without merging**
