### PR TITLE
Arcade tweak

### PR DESCRIPTION
**Pull request by Jackrost**
Space Villain Arcade prizes now separated into normal and special prizes. Each arcade can give 1-2 toy weapon to you.

* Prize list is now separated into normal and special. Number of special prizes can be adjusted (both in prototype and ingame).
* Number of normal prizes is "number of prizes - number of special prizes".
* Special prize dropped with 30% chance by default. It can be adjusted also. If you don't get special prize still, then keep playing and you get it.
* Window minimum size was increased to make action text fit into window fully. Content is centered now.
~~* Elements of window don't align properly still.~~

- [X] This PR does not require an ingame showcase

:cl: Jack Rost
- tweak: arcade now guarantees that you get 1-2 toy weapons by default.
- tweak: minimum size of window is a little bigger. Window content is centered now.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Seems better to just use weighted random?

**Comment by Jackrost** [comment]
> Seems better to just use weighted random?

Hm, I try look at it later and check it out.

**Comment by Jackrost** [comment]
>

**Comment by Jackrost** [comment]
Ops, I mistake button

**Comment by Jackrost** [comment]
> Seems better to just use weighted random?

Do you refer to lines when I choose between normal and special prizes, or you offer to use weight random for all prizes and take them from one list?

**Review by AJCM-git — CHANGES_REQUESTED** [review]
I think the most sane way to do this is for you to move both `_possibleSpecialRewards` and `_possibleRewards` to a single `EntityLootTablePrototype` and handle probabilities there (Then you get the prototypes in here with something like            
` var rewards = _prototypeManager.Index<EntityLootTablePrototype>("ArcadePossibleRewards");` and if you do this you can keep the old spawning behavior almost intact)

**Comment by AJCM-git** [comment]
@Jackrost you coming back to this?

**Comment by Jackrost** [comment]
> @Jackrost you coming back to this?
much later. I'm busy. Converted this PR to draft for now

**Comment by AJCM-git** [comment]
reopen when you are free

**Pull request closed without merging**
