### PR TITLE
Add a new chemistry bag.

### PR DESCRIPTION
**Pull request by reapsnI**
## About the PR
Add a new bag for chemist's for speeding up their work process. Works as a ore bag or plant bag. Can only fit chemistry bottle's, pill and pillcanister.

**Screenshots**
Eng bagDescription
Spawn screen Entity spawn menu
Bag uiUI with whitelist entity's

Inventory screen Inventory view
FrontFront view
BackBack view
RightRight side view
LeftLeft side view

**Changelog**
Added spawn in chemistry locker.
Added entity code for bag.
Added texture and sprite.
Added relation's for a bag.

:cl: Inspaer
- add: Added a new bag!
- remove: Nothing!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
is this not just what the medical belt does? also 176 storage is actually insane, even if it's just pills.

**Comment by reapsnI** [comment]
> is this not just what the medical belt does? also 176 storage is actually insane, even if it's just pills.

It works the same way as other bag's. Just imagine. When you are getting a final product form a chemmaster 4000. You dont need to stash in in your bag one by one. Just one simple click on a chemmaster with a bag. And you are getting all product in it. Then you can hop up stand, and drop all the pills with one click. I forgot to describe that.

**Comment by Kromabae** [comment]
this is basically medicalbelt but without the ability to put ointment and bruisepacks in it and it's 175 space compared to medical belt 40

**Comment by EmoGarbage404** [comment]
> > is this not just what the medical belt does? also 176 storage is actually insane, even if it's just pills.
> 
> It works the same way as other bag's. Just imagine. When you are getting a final product form a chemmaster 4000. You dont need to stash in in your bag one by one. Just one simple click on a chemmaster with a bag. And you are getting all product in it. Then you can hop up stand, and drop all the pills with one click. I forgot to describe that.

this is the kind of gameplay that we're looking to discourage. Creating large amounts of pills and dumping them on a counter is imo kind of lame and we're trying to move towards a more resource-strict chem. In that concept, something like this lacks a purpose.

**Comment by reapsnI** [comment]
> > > is this not just what the medical belt does? also 176 storage is actually insane, even if it's just pills.
> > 
> > 
> > It works the same way as other bag's. Just imagine. When you are getting a final product form a chemmaster 4000. You dont need to stash in in your bag one by one. Just one simple click on a chemmaster with a bag. And you are getting all product in it. Then you can hop up stand, and drop all the pills with one click. I forgot to describe that.
> 
> this is the kind of gameplay that we're looking to discourage. Creating large amounts of pills and dumping them on a counter is imo kind of lame and we're trying to move towards a more resource-strict chem. In that concept, something like this lacks a purpose.

Well, we still have a SmartFridge. Maybe this bag will be useful in future in combo with a fridge.

**Comment by DummeHytteOst** [comment]
i don't see this being good at all, it makes medkits and medical belts worth less, and being able to hold a total of 421 pills in one bag is extreamly excessive in my opinion, i don't see it being very usefull since moving pills is not an issue anymore, with pills being put directly into pill bottles now, and pill bottles already got the ability to pick up a ton of pills off the ground with a single click.

**Comment by moonheart08** [comment]
This is way too overpowered and excessive.

**Pull request closed without merging**
