### PR TITLE
add station records computer

### PR DESCRIPTION
**Pull request by not-gavnaed**
add station records computer(https://github.com/space-wizards/space-station-14/issues/14524) for aspid and bagel

- [yes ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image
image
image
image

I will make all the other maps soon, this is my first experience

**Changelog**

:cl:
- add: Added Station Records Computer on Aspid & Bagel

### CODE REVIEW

**Comment by not-gavnaed** [comment]
я старался

**Comment by Cheackraze** [comment]
This is fine but I will probably change them in aspid on the next update

**Review by Emisse — APPROVED** [review]

**Comment by moonheart08** [comment]
@not-gavnaed In the future, please get in contact with mappers for approval to edit their map before PRing.
Future PRs done without this approval will be closed.

**Comment by not-gavnaed** [comment]
> @not-gavnaed In the future, please get in contact with mappers for approval to edit their map before PRing. Future PRs done without this approval will be closed.

okay

**Pull request merged**
