### PR TITLE
make meat sizzle when cooked

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

## Why / Balance
good

## Technical details
no

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/dea849f1-39a8-4a5f-8421-0847512c350b

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
the sound effect doesn't really sound like sizzling meat at all. it's also quiet as shit.

**Comment by deltanedas** [comment]
look i just used a random sound that sounded right ish :trollface:

**Comment by metalgearsloth** [comment]
Make it sound like the fattest bacon known to man.

**Comment by deltanedas** [comment]
ok i will maybe make a good sound tomorrow :trollface:

**Comment by deltanedas** [comment]
@EmoGarbage404 updated video with new sound

**Review by DrSmugleaf — APPROVED** [review]

**Comment by EmoGarbage404** [comment]
makes me shed an american tear (bacon fat) but yeah this is good.

**Comment by deltanedas** [comment]
:flag_us:

**Comment by lzk228** [comment]
YEAHH LESSGO

**Pull request merged**
