### PR TITLE
L6 Wielded Sprites

### PR DESCRIPTION
**Pull request by HerCoyote23**
## About the PR

Adds wielded sprites for the L6 SAW, fixing #17069 
Also fixes the inhand-right sprite to not be off by one.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image
image

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Review by deltanedas — CHANGES_REQUESTED** [review]
meta indent should be 2 space

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
what he said.

**Comment by HerCoyote23** [comment]
Indented

**Review by metalgearsloth — APPROVED** [review]

**Comment by metalgearsloth** [comment]
buh the images were so large I scrolled past the cl.

**Comment by HerCoyote23** [comment]
Guh same

**Pull request merged**
