### PR TITLE
Basically every electronic device can now be used by the AI.

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Made most if not all electronic devices be usable by AI.

## Why / Balance

AI was meant to be able to interact with every electronic. This PR basically ensures of that. (With minor exceptions)

## Technical details

Modified yaml files for most electronic items.
That includes: 
~~Dispensers:~~
~~Booze~~
~~Chem~~
~~Soda~~

Arcades: (Have AI wires)
Space Villain
Block Game

~~Power/Generation:~~
~~AME Controller~~

Machines:
Vending Machines (Have AI wires)
~~Salvage Magnet~~
~~Reagent Grinder~~
~~Microwave~~
Jukebox (Has AI wire)
Gravity Generator
Mini Gravity Generator
~~Flatpacker~~
~~Fax Machine~~
~~Captain Fax Machine~~
~~ChemMaster~~
~~A.P.E~~
Anomaly Generator (Has AI wire)
~~Electrolysis Unit~~
~~Cryopod~~

Computers:
ID Computer
IFF Computer
Alerts Computer
R&D Computer
Analysis Console
Body Scanner Console
Cargo Request Computer
Cargo Bounty Computer
Cargo Sale Computer
Cloning Console Computer
Communications Computer
Crew Monitoring Console
Criminal Records Computer
Mass Scanner Computer
Medical Records Computer
Power Monitoring Computer
Station Records Computer
Solar Control Console
Salvage Expedition Console
Robotics Console
~~Tech Disk Terminal~~

Doors:
Firelocks (No bolt UI)
High Sec Doors (Has AI wire)

Shuttles:
Station Anchor (not indestructible)

~~Piping/Disposal:~~
~~Disposal Unit~~
~~Mailing Unit~~

Wallmounts:
Air Alarm (Has AI wire)

Piping/Atmos:
~~Pressure Gas Pump~~
~~Volumetric Gas Pump~~
Signal Valve
Space Heater
~~Gas Filter~~
~~Gas Mixer~~
Freezer
Heater
Hellfire Freezer
Hellfire Heater

## Media

None. Don't know what to show here.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: ScarKy0
- add: A lot more electronics can now be used by the AI.

### CODE REVIEW

**Comment by ScarKy0** [comment]
Exceptions: Shuttle consoles(their UI doesnt work), news console(doesnt work) and most electronics that would allow a complete destruction of the station.

**Comment by lzk228** [comment]
gives ai too much power
i'm still of the opinion that AI access should be limited to machines with an AI wire

**Comment by ScarKy0** [comment]
> gives ai too much power
i'm still of the opinion that AI access should be limited to machines with an AI wire

I agree, but by design AI is to have access to all electronics.
If I knew how to make a machine have AI wires I absolutely wouldve done it

**Comment by Nimfar11** [comment]
It seems AI shouldn't have a direct way to control equipment, only through consoles. I mean Piping/Atmos.

**Comment by metalgearsloth** [comment]
Rather than bikeshedding every one list needs stripping down, also stuff like the A.P.E shouldn't be useable by AI.

**Comment by ScarKy0** [comment]
>Rather than bikeshedding every one list needs stripping down, also stuff like the A.P.E shouldn't be useable by AI.

What stuff should I take out? Ill update it next chance I get

**Comment by ScarKy0** [comment]
> I mean Piping/Atmos.
AME Controller also seems superfluous here.

Removed AME controller, but in ss13 AI could control atmos just fine, ill remove it if a maintainer asks though

**Comment by Nimfar11** [comment]
> Removed AME controller, but in ss13 AI could control atmos just fine, ill remove it if a maintainer asks though

Did this happen under direct control, or through the console? It seems to me that even in ss13 the AI could not do this, perhaps through a signal pump.

**Comment by ScarKy0** [comment]
> Did this happen under direct control, or through the console? It seems to me that even in ss13 the AI could not do this, perhaps through a signal pump.

Direct control, unless its malf only

**Comment by ScarKy0** [comment]
Added AI wires to arcades, vending machines, jukeboxes, anomaly gen, high security doors, secure doors and air alarms

**Comment by slarticodefast** [comment]
Could you remove pumps, filters, mixers and valves from the whitelist as these are not digital devices? The signal valve can stay as an exception.

**Comment by lzk228** [comment]
> not digital devices

in that case would be logical to remove buttons aswell

**Comment by ScarKy0** [comment]
> Could you remove pumps, filters, mixers and valves from the whitelist as these are not digital devices? The signal valve can stay as an exception.

Will take care of it after I wake up

**Comment by ScarKy0** [comment]
Done, so basically ready for merge I believe

**Comment by slarticodefast** [comment]
Thank you for your contribution!

**Pull request merged**
