### PR TITLE
Removes the steal QM's computer board objective from the game, makes protect much rarer

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
What it says on the tin. These objectives do very little to actually drive the round forward in any interesting way, and are usually just a huge pain in the ass to complete.

The computer board objective here is are the real stinker - they're basically impossible to do stealthily, removing them from the round barely does anything interesting, they don't even make sense for the syndicate to be stealing, and also makes the item act as weird meta-contraband when there's nothing really that remarkable about them.

Protect may be okay to get once in a while, but as a primary objective it sucks since you barely have any influence on it (without dedicating your entire round to it, at least.) I was considering removing it from the objective pool, but I feel like making it rare may make some interesting situations (ie. "FUCK, I got protect and now I have to figure out how to deal with it now.")

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Removed the steal objective for the supply board.
- tweak: The protect objective is now much, much less likely to appear than other objectives.

### CODE REVIEW

**Comment by Geekyhobo** [comment]
I think removing them might be a bit much, reducing their probability would be a better start. Also, I think part of the reason that they are a pain in the ass, is because they are some of the only objective in the game. I think you might be better off creating more objectives then removing them.

**Comment by Equivocateur** [comment]
the id board at marathon arrivals is literally free

**Comment by Emisse** [comment]
I like the board objectives

**Comment by deltanedas** [comment]
board objective is free greentext its very very hard to fail it
- marathon arrivals checkpoint has an id computer for this purpose
- on any other map you have 3 guaranteed boards so theres enough to go around for everyone

the most it comes to is a bit of trolling, robbing first the bridge board for myself then the hops board for my buddy, and after hop malds on an announcement stealing his new one after he leaves office yet again

**Comment by Equivocateur** [comment]
> stealing his new one after he leaves office yet again

Stealing the third board gives hop the *hop*e that he can get it back, blow up the computer instead

**Comment by Flareguy** [comment]
> board objective is free greentext its very very hard to fail it
> 
> * marathon arrivals checkpoint has an id computer for this purpose
> * on any other map you have 3 guaranteed boards so theres enough to go around for everyone
> 
> the most it comes to is a bit of trolling, robbing first the bridge board for myself then the hops board for my buddy, and after hop malds on an announcement stealing his new one after he leaves office yet again

This does kind of make sense then, actually... it's pretty boring still, but it at least does SOMETHING to drive the round considering you'll need to bust into bridge or the captain's office. It can probably stay until we at least get more steal objectives (like the secret documents or HOS's laser.)

Supply board is still ass though so that's not changing unless someone can give a good argument for it - that one is basically impossible to do stealthily, and does nothing other than potentially fuck over cargo (and even then they have a spare, I've heard.)

**Comment by deltanedas** [comment]
while it sometimes drives the round almost always its just swing by hops when nobodys looking and steal it then watch as nobody gives a shit

**Comment by LankLTE** [comment]
> does nothing other than potentially fuck over cargo (and even then they have a spare, I've heard.)

There's one in the QM's locker- and I presume you're supposed to break in and steal that one because yeah, it's basically impossible to take the actual board. Like with the ID Computer, I imagine the intent isn't even to try and disrupt them because alternatives exist, it's just an item that's relatively difficult to get, protected, and actually has multiple copies you could steal (as compared to most other steal objectives). 
Not to say I think it should stay because the QM's room is still 95% of the time visible from cargo and it's basically impossible to stealthily break in, and very very easy to do after evac leaves if you really want greentext.

**Comment by deltanedas** [comment]
even before evac just hack/flush yourself in steal it and leave nobody really cares

**Comment by metalgearsloth** [comment]
@Flareguy are you coming back to this

**Comment by Slava0135** [comment]
merged #18925 so I guess I close this

**Pull request closed without merging**
