### PR TITLE
Added Tourniquets to stop bleeds

### PR DESCRIPTION
**Pull request by PoorMansDreams**
## About the PR

Adds a very fast acting Tourniquet to stop bleeding, but does some brute/aphyx damage in turn.
## Why / Balance

Gauze and Tranx needles often take too long and you'll probably bleed out before fully injecting it
Deals some brute damage in turn, as well as some aphyx damage. (tourniquets hurt)
## Media

https://www.youtube.com/watch?v=d_qTfsNhlSo
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Added Tourniquets, find them in your local Sectechs.

### CODE REVIEW

**Comment by PoorMansDreams** [comment]
My previous Clone of git blew up and is in flames. thankfully this works. 😭

**Comment by PoorMansDreams** [comment]
[deltanedas](https://github.com/deltanedas):
i dont think this should be a thing until wounds, since irl putting on tourniquet is bad

[lzk228](https://github.com/lzk228):
AHHHHH MY EYES, NAME STARTS WITH CAPITAL LETTER AHHHH

[Aisu9](https://github.com/Aisu9):
for information bleedrate is capped at 10, because people cannot deal with heavy bleeding

previous comments from the previoust PR

**Comment by deltanedas** [comment]
just push commits to previous pr branch you dont need to remake after every single change

**Comment by PoorMansDreams** [comment]
Sorry I’m still fairly new to this I didn’t know you could commit to previous branch with different you know

**Comment by deltanedas** [comment]
the command to fix it `git checkout upstream/master RobustToolbox` then commit that :trollface:

**Comment by PoorMansDreams** [comment]
image

**Comment by PoorMansDreams** [comment]
image_2023-12-30_040147313

**Comment by K-Dynamic** [comment]
Funny, heat damage (including touching lights and welding yourself) is meant to cauterize and stop bleeding but hasn't worked for like a month now

Tourniquets seem a bit redundant if that bug gets fixed

**Comment by PoorMansDreams** [comment]
I rarely see nukies/sec/other blokes use the weldtouch/Cautery tool to stop bleeds even back when the tourches stopped bleeding
I hope the tourni brings attention to bleeding better

**Comment by PoorMansDreams** [comment]
image_2023-12-30_073804020
bit darker to get that red on black sec feeling

**Comment by TheShuEd** [comment]
I think the sprite needs to be completely redone.  now it looks like... a black cigarette?  it is necessary to adhere to the style of bandages. 

 It is also necessary to generally discuss whether this is necessary in the game, given the mechanics of cauterization of wounds.

**Comment by PoorMansDreams** [comment]
image (3)
no longer looks like an evil blunt

**Comment by K-Dynamic** [comment]
I mean once woundmed is properly implemented, there's a good chance the tourniquet will be rather important (used irl to stem bloodloss without requiring cauterising, which comes with its own risks and side effects)

**Comment by Emisse** [comment]
update meta.json attribution

**Comment by PoorMansDreams** [comment]
> update meta.json attribution

done :godo:

**Comment by Jezithyr** [comment]
> I mean once woundmed is properly implemented, there's a good chance the tourniquet will be rather important (used irl to stem bloodloss without requiring cauterising, which comes with its own risks and side effects)
> 
> As such despite current redundancy and weak state of bleeding, I'd like to see tourniquets

Yep Tourniquets are going to be VERY important in newmed!
LGTM merging!

**Pull request merged**
