### PR TITLE
map atmosphere reactions

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds support for running reactions on planets, fire and maybe in the future fusion if you made a tritium planet
only enabled for exped planets currently since theres no other way to have plasma atmosphere planet

## Why / Balance
volatile atmosphere + high temp being a fire planet makes sense, requires atmosias help or sending in a borg or something to safely do stuff

## Technical details
- bad
- doesnt update the planets gas visuals so you cant actually see that its on fire
- it doesnt light people on fire since thats a tile thing, would probably require copypasting a lot of stuff
- dont know how to query all entities on a map but not on a shuttle grid

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none

**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by Partmedia** [comment]
Conceptually I like this idea. It would, of course, be best to see the fire burn, so I hope you'll investigate this.

In technical details, I was really hoping you'd explain what precludes planet maps from reacting atmospheres right now; and how your change adds reacting atmospheres. I guess I'll have to go look.

Please adjust your changelog when ready for review.

**Comment by deltanedas** [comment]
previously only gridatmosphere had any processing done per tick, now at least reactions are done but implementing more would probably be a large copypaste job of atmos code
for visuals i still cant find what renders the mapatmos Mixture on every tile

**Comment by Partmedia** [comment]
> previously only gridatmosphere had any processing done per tick, now at least reactions are done but implementing more would probably be a large copypaste job of atmos code for visuals i still cant find what renders the mapatmos Mixture on every tile

Why don't planet maps have GridAtmospheres?

**Comment by deltanedas** [comment]
because then lighting a cigarette would crash the server having it be a single tile is a good optimisation

**Comment by deltanedas** [comment]
cant do this

**Pull request closed without merging**
