### PR TITLE
Adds cat ears as rare loot and traitor item

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Added cat ears by popular request. Strip me of all my titles and permissions now before they convince me to do something else silly.

Gives the OwO / UwU accent. Is animated.

Can only be obtained by traitor uplink for 3tc, as 1% rare drop chance in salvage crates and in maint fluff spawners.
**Screenshots**

Content Client_12BDxUzHZT

**Changelog**

:cl:
- add: Cat Ears have arrived. Gives you the UwUs. Find it in a maint spawner, salvage crate or traitor uplink.

### CODE REVIEW

**Comment by Sk1Wass3r** [comment]
based

**Comment by mirrorcult** [comment]
death

**Comment by moonheart08** [comment]
death

**Comment by Peptide90** [comment]
> death
> death

Make no mistake, weeb culture is a mystery to me and I don't understand half of what is said in chat

**Comment by Kromabae** [comment]
bild
just ognna put this here :P

**Comment by moonheart08** [comment]
unfortunately that was a joke. Sorry!

**Comment by Peptide90** [comment]
Anyone else want to voice an opinion on this one?

**Comment by Emisse** [comment]
I'm all for it I think people will have fun with it.

**Comment by Elijahrane** [comment]
this pr is based

**Comment by metalgearsloth** [comment]
Based on trash

**Comment by DogZeroX** [comment]
Cope, leave it to bother the normies.

**Comment by UKNOWH** [comment]
give it a tag so in the future we can put it in teh downstreams

**Comment by UKNOWH** [comment]
REOPENED!!!

**Comment by UKNOWH** [comment]
16 TC I suggest

**Comment by Kromabae** [comment]
Fingies crossed for the good memes

**Comment by mirrorcult** [comment]
if the ears are made >20TC then im fine with merging

**Comment by Emisse** [comment]
real

**Comment by UKNOWH** [comment]
make it 22TC

**Comment by UKNOWH** [comment]
Just don't make it worth as much as a machine gun

**Comment by mirrorcult** [comment]
this is considerably more valuable than any gun given my knowledge of SS14 traitors

**Comment by Emisse** [comment]
i would kill every traitor on the station to buy cat ears

**Comment by UKNOWH** [comment]
At least make it give you vaccum resistance , or complete disease resistance. Otherwise it would be too underwhelming for an over 20 TC item

**Comment by mirrorcult** [comment]
no

**Comment by TimrodDX** [comment]
If this is merged I am putting two of these in the coder room on Delta just to see how high the murder rate in that area can go.

**Comment by UKNOWH** [comment]
> If this is merged I am putting two of these in the coder room on Delta just to see how high the murder rate in that area can go.

Duo it
**do it**

**Comment by Kromabae** [comment]
just make it 20TC, be the same as ballon, just useless stuff that ppl can use to meme with

**Comment by youarereadingthis** [comment]
Personally I would prefer that a meme/kink like this is very rarely if ever seen as it clashes very heavily with the space corporation theme.
I don't mind one bit that some people may enjoy this on their own time but it seems distasteful to me at the least.

If it were to be implemented in any form then it makes the most sense as something you're forced to wear at later stages of the owona virus. Bonus points for if it's similar to a zombie invasion where you can shoot them on sight.

**Comment by EmoGarbage404** [comment]
catgirl maid infection virus? I might have to see what rane's cool with on nyanotransen....

**Comment by mirrorcult** [comment]
if this is to be merged it needs to be >20TC and not mapped anywhere imo

**Comment by mirrorcult** [comment]
That Is My Final Decision

**Comment by Kromabae** [comment]
21TC immune to disease, final offer, these ears will make syndie vs syndie more prevalent

**Comment by Kromabae** [comment]
also how can we have catmaid cafe neon signs but no catmaids, thonkers

**Comment by youarereadingthis** [comment]
1. Psalm 73:6-8 They wear pride like a jeweled necklace and clothe themselves with cruelty. These fat cats have everything their hearts could ever wish for! They scoff and speak only evil; in their pride they seek to crush others.

**Comment by ZeroDayDaemon** [comment]
Speed merging rn.
Lgtm 
Approved!

**Comment by Elijahrane** [comment]
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ Wizards, ░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Comment by Peptide90** [comment]
> Personally I would prefer that a meme/kink like this is very rarely if ever seen as it clashes very heavily with the space corporation theme.
> 
> I don't mind one bit that some people may enjoy this on their own time but it seems distasteful to me at the least.
> 
> 
> 
> If it were to be implemented in any form then it makes the most sense as something you're forced to wear at later stages of the owona virus. Bonus points for if it's similar to a zombie invasion where you can shoot them on sight.

I'll increase to 20 TC.

But yes, they were in 13 and a large portion of our players would enjoy it too. Since it's animated and bait I wanted it to be very rare however, note, not everything on station comes from NT and we already have stuff like bunny ears so it's already murky. 

Personally I have no interest and just want to see the chaos and murder it brings, plus we're zero tolerance on ERP.

**Comment by UKNOWH** [comment]
>I'll increase to 20 TC.
21 or mirror might not merge it

**Comment by Peptide90** [comment]
> > I'll increase to 20 TC.
> > 21 or mirror might not merge it

We shall see ;) If a T wants to go hardcore and only use cat ears that's cool but needing another TC is cruel heh.

**Comment by youarereadingthis** [comment]
You must kill the fox to become a cat.
That, or maybe emag the cargo console and ordie a syndie crate and cross your fingers there's TC in it.

**Comment by UKNOWH** [comment]
How about a OwOnagen infector + cat ear as a furry apocalypse starter pack. The cat ears would neglect you from all negetive sideeffects of owonegen

**Comment by Peptide90** [comment]
What needs changed?

**Comment by UKNOWH** [comment]
> What needs changed?

just make it cost 21 TC

**Comment by Peptide90** [comment]
> > What needs changed?
> 
> just make it cost 21 TC

Done. Thought 20 would have been enough. Now it’s unobtainium.

**Comment by Emisse** [comment]
you can get more than 20 you just need other traitors tc or to butcher renault

**Comment by metalgearsloth** [comment]
oWo what's this *merges pullsies requestsies*

**Pull request merged**
