### PR TITLE
Feat/nightvision

### PR DESCRIPTION
**Pull request by tom-leys**
## About the PR
- All mobs and players have quite strong night vision, brightening up dark areas considerably but not always penetrating the shadows
- Lights are more powerful and effective overall
- Computer, Substation and ambient lights have been rebalanced (or they are overpowering)
- PDA light very strongly nerfed. You'll notice it and rely on it in very dark areas but otherwise can barely see it. Similar use to now.
- Torches and player lights nerfed slightly (more powerful in this PR than before overall)
- ~~Spiders have such strong night vision they hate the brightness of regular corridors~~
- Sunglasses, combat glasses and welding masks will darken your vision (you'll adjust as long as it isn't very dark)
- Some other light sources might require nerfs still
- It's quite possible to end up "blinded" (things appear too white) for a few seconds coming out of corridors or by bright light sources in dark areas. It's cool though.

~~This is a more extensive version of https://github.com/space-wizards/space-station-14/pull/17084 (closed)~~
Requires Engine: https://github.com/space-wizards/RobustToolbox/pull/4106

**Media**

Youtube demos

Night Vision: https://www.youtube.com/watch?v=8JrGEDx1S6Q
Sunglasses : https://www.youtube.com/watch?v=zj0DV0-hptM

Regular lighting in a corridor
image

Power has gone out
image

Extremes are possible in the same image
image

Standing on a bright lightsource will blind you (well, your eyes adapt to the brightness to be exact)
image

~~Those flares are blinding to a spider~~ (I have reduced the blinding, see comments)
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: You have nightvision now. Spend some time in the darkness to adapt. Enjoy the gorgeous new lighting.
- add: Spiders hate the light, it seems far too bright. They prefer the dark.
- remove: PDA lights are very dim now. You'll only be able to use them in the dark.
- add: Can't see in the dark? Perhaps you need to take off your sunglasses.
- add: Ghosts can see much better in the dark without having to disable lighting. They have the best possible nightvision.

### CODE REVIEW

**Comment by moonheart08** [comment]
- Content should be able to postprocess the lighting buffer.
   - So that it can have a shader replace the eye searing overbright regions that spiders for example see with static, which is just as good of a visual indicator to the player without blinding them.
       - Seriously if blowing out the screen with white gets merged I'll be upset.
       - If you want to be cooler instead make it so it completely dims out your eye adaption so you can only see the flare. This'll let you dazzle mobs with bright lights which is much more interesting and *darkens* your screen instead of brightening it.

**Comment by moonheart08** [comment]
Absolutely need @PJB3005 review.

**Comment by tom-leys** [comment]
> Dazzling spiders (if blowing out the screen with white gets merged I'll be upset.)

It actually looks super cool in game, not as horrible as it might look in a single screenshot. Fortunately it's very easy to scale the effect or turn it off, I'd hate to make you upset. 

It's probably too easily griefable anyway. 

I wasn't too attached to the effect, it's scalable using NightVision.lightIntolerance and so can be cranked up or down as we desire easily.

Blowing the screen out white might be painful in our current lighting system, but it looks nicer now because the rendering saturates correctly. Also because the game is generally easier to see anyway due to the dynamic lighting system you don't need to crank your monitor brightness up as high. 

Generally I've found that the HDR lighting turns the expsoure up to 2-3x in normal lit corridors compared to the lighting we used to have. The lighting generally looks much brighter, clearer and more dramatic.

> 
>     * Eye adaption scaling seems super dramatic.

I hope you meant that as a compliment? It looks really dramatic and nice in game. It also makes it a lot less painful to play when the power is out or some lights have failed because you don't have to squint any more.

**Comment by tom-leys** [comment]
Here's one option with Shiva

image

If you REALLY hate blowing out the screen we can turn down the light sensitivity like this, though bear in mind that 3 flares really are VERY bright (we might want to reduce their power?)

image

**Comment by tom-leys** [comment]
Sunglasses and welding masks protect against bright lights, I've moved AutoExposure and NightVision into client code.

**Comment by Skyedra** [comment]
The HDR visual effects are very cool aesthetically, nice :)  I am also a fan of being able to adapt eyes to see what's going on in the dark, as that can be a problem previously if you find yourself pda-less in somewhere unlit (ie: prison break).

However, I am a little worried about the additional complexity added to gameplay with the equipment modifiers.  In particular, sec having to (or being subtly encouraged to) micromanage sunglasses status every time they go into maints seems like it will be unpleasant.  Besides the tediousness of managing glasses status, it might also discourage sec using nonlethal flashes because they don't know if other sec still have their glasses on / don't have time to get their own glasses on.  Plus, unequipping glasses every entry means extra time to be distracted every time going into maints.  Maints are already quite dangerous to go in, so adding additional danger from having to fanangle with equipment seems like it would exacerbate it.

**Comment by tom-leys** [comment]
> In particular, sec having to (or being subtly encouraged to) micromanage sunglasses status every time they go into maints seems like it will be unpleasant. 

Sec will be able to see in maints with glasses on just as easily as they do pre-PR at least. They could also just use a flashlight.

Mostly I used it as a cool demo

**Comment by Vaaankas** [comment]
please merge

**Comment by tom-leys** [comment]
HDR engine changes are now async. As now there is no engine support for player-centred "nightvision" light but otherwise it works well.

**Comment by Peptide90** [comment]
Very interesting changes. Presumably since you have eyewear that affects your night vision this makes things like night vision goggles more achievable. And certain species having better innate night vision as some do in SS13 as a buff.

**Comment by Errant-4** [comment]
@tom-leys just checking if you saw that this has merge conflicts according to github

**Comment by metalgearsloth** [comment]
> @tom-leys just checking if you saw that this has merge conflicts according to github

https://discord.com/channels/310555209753690112/928056457117696020/1111955581587165224

**Comment by tom-leys** [comment]
> > @tom-leys just checking if you saw that this has merge conflicts according to github
> 
> https://discord.com/channels/310555209753690112/928056457117696020/1111955581587165224

Hi @metalgearsloth - I wasn't aware that it had become blocked. However there are engine changes which require merging (Requires Engine: https://github.com/space-wizards/RobustToolbox/pull/4106)

Also, the policy is not to resolve merge issues until a maintainer requests it. I imagine you're requesting it now?

Thanks

-Tom

**Comment by VektorZ1** [comment]
Waiting.....

**Comment by metalgearsloth** [comment]
> Waiting.....

Don't necro with useless comments thanks.

**Comment by JoeHammad1844** [comment]
hmm, can eyewear multiply light aswell? and apply a colour filter?

**Comment by JoeHammad1844** [comment]
if so we could have realistic night vision goggles that blind you in regular lighting but allow you to see in near pitch darkness, but you would also need to have to toggle them with an action. thing is that pitch black places dont have light so you still wouldn't be able to see, which could be circumvented by having the night vision goggles, when activated, produce a cone of light, and maybe only have that light be visible to other night vision users, which would be like having an IR flashlight

**Comment by Peptide90** [comment]
@tom-leys are you still working on this PR. Love the work and would hate to see it go to waste.

We've lightly discussed on discord and seems there's still changes requested on this. Are you in the discord to chat or prefer comments here?

**Comment by VektorZ1** [comment]
PR is now over a year old! Congratulations!

**Comment by tom-leys** [comment]
> PR is now over a year old! Congratulations!

Nah, we're still 4 months to go. By the way, the PR is currently waiting for me to do updated tests on it and then there's some willingness to test merge it.

**Comment by WarMechanic** [comment]
Have you experimented with colour shifting effects? I think all this stuff is really cool, it means an experienced maintcrawler may consider an eyepatch to have on-demand dark adjustment like pirate boarders of old. However, it seems kinda hard to intuitively tell how dark an area actually is. What if darkness adjustment made your screen cooler and more blue?

**Comment by superjj18** [comment]
How will this interact with #26932?  Should we buff emergency lighting since it was nerfed a while ago to be smaller?  (Radius nerfed in #22310)

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by TokenStyle** [comment]
Merge freeze is over, this PR it's gorgelous, certainly need it. There's need fix tests, merge conflicts and PR is done.
Wish you best, it's amazing PR!

**Pull request closed without merging**
