### PR TITLE
WT550 Buffs + Burst Mode for WT550 & C-20R

### PR DESCRIPTION
**Pull request by BramvanZijp**
## About the PR
The following stat changes have been made to the WT550:
Firerate: 5 > 5.5
Firemodes: Semi, Full > Semi, Burst (5), Full
MinAngle:  2 > 1
MaxAngle: 16 > 6
AngleIncrease: 3 > 1.5
AngleDecay: 16 > 6

It also gives the C-20R the same 5 round burst firemode option.

## Why / Balance
Currently, the WT550, which is the standard weapon for a Head of Security, is a worse drozd.
This PR aims to have its DPS be slightly better then a pistol, while still worse then the drozd, and in exchange, buffing the accuracy.
While it is still quite far from lecter-level precision, it should now be able to engage better on medium ranges as opposed to only close.
Lastly, the Burst firemode, which I see rarely used in weapons, is now available in 5 shot bursts, just to give the weapon a unique identity and maybe further help with recoil control.

In general, this PR would make the weapon feel unique, since while it is still slower then a drozd, its easier to hit more of your shots. Making it a more balanced weapon, having solid but not amazing damage and accuracy.

As for the C-20R, the 5 mode burst should help with trigger & recoil control, allowing you to not quite fire semi without going into spray and pray level accuracy due to firing for an extended period of time.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: BramvanZijp
- tweak: Nanotrasen's Small Arms Division has slightly improved the firerate and drastically improved the accuracy on its WT550 SMGs.
- add: The WT550 and C-20R SMGs can now fire in a 5 round burst-fire mode, making it easier for their users to control the recoil on these weapons.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
NT gun buff nice

HoSs better be reminded not to carry these roundstart on green

**Comment by SoulFN** [comment]
I like it, WT550 was weak weapon, no one used WT if they had drozd in they armory, in my opinion, we need to nerf armories on maps, remove all drozds, enforcers and other strong weapons, leave a small number of not particularly strong weapons like a double-barrelled shotguns, security will have to order weapons from cargo, but then you need to add more ways for cargo to make money

**Comment by deepdarkdepths** [comment]
> NT gun buff nice
> 
> HoSs better be reminded not to carry these roundstart on green

HOS can carry their gun on green.

**Comment by Cojoke-dot** [comment]
Yeah, this feels like a needed buff. For a gun that looks cool it was quite shit. I like the burst, though how many bursts can you get off with one mag?

**Comment by BramvanZijp** [comment]
> Yeah, this feels like a needed buff. For a gun that looks cool it was quite shit. I like the burst, though how many bursts can you get off with one mag?

6 bursts due 5 round bursts of a 30 capacity mag.

**Comment by Brandon-Huu** [comment]
Wait what? The head of securities gun is worse than a drozd? That makes no sense

**Comment by BramvanZijp** [comment]
> Wait what? The head of securities gun is worse than a drozd? That makes no sense

Which is why I made this PR.

**Pull request merged**
