### PR TITLE
Make railings render over tables

### LINKED ISSUE #31575: Rails render under tables
## Description

It should render above otherwise it looks weird and can mess up some builds

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Title.

## Why / Balance
Fixes #31575.

### Before
изображение

### After
изображение

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Now railings render over tables.

### CODE REVIEW

**Comment by lzk228** [comment]
aw man i can't look at all those railings that have BaseStructure as parent and just copy paste all the components, gonna cleanup it after this pr

**Comment by Winkarst-cpu** [comment]
> aw man i can't look at all those railings that have BaseStructure as parent and just copy paste all the components, gonna cleanup it after this pr

Yeah, this is terrible.

**Comment by IProduceWidgets** [comment]
Wont you get the opposite bad behavior if the railing is on the North side?

**Comment by Winkarst-cpu** [comment]
> Wont you get the opposite bad behavior if the railing is on the North side?

https://github.com/user-attachments/assets/e8d05f73-5542-48ca-91a4-859e1949e4a5

**Pull request merged**
