### PR TITLE
Fix: #4037 Being able to dehandcuff yourself while dead

### LINKED ISSUE #4037: Being dead does not stop you from attempting to escape from handcuffs
## Description
As in the title, you can resist and successfully escape from cuffs while dead. Being stunned or damaged will reset resisting as usual.

### PR DESCRIPTION
**Pull request by scrato**
## About the PR 
Fixes #4037 
You now won't be able to get away if you're incapacitated or dead. 
I chose not to show a message, because, you know, dead people won't read.

**Changelog**

:cl:
- You now won't be able to get out of handcuffs if you're dead or incapacitated

### CODE REVIEW

**Comment by TimrodDX** [comment]
Just out of curiosity, and to stop me putting up an issue if I don't need to, does this also disable being able to pull objects while dead?

**Review by ShadowCommander — CHANGES_REQUESTED** [review]
Both of these should actually check ActionBlocker.CanInteract or one of the other ActionBlockers if they don't already. That would decouple this better and cover more cases where the player shouldn't be able to interact.

**Comment by scrato** [comment]
@TimrodDX 
> Just out of curiosity, and to stop me putting up an issue if I don't need to, does this also disable being able to pull objects while dead?

Nope, I'm afraid you have to put up a ticket, it has to be implemented in the specific behaviors.

@ShadowCommander
perfect, thank you. Will do!

**Comment by scrato** [comment]
@ShadowCommander Yeah, `ActionBlockerSystem.CanInteract()` was called but only 
`if(!IsOwner && ActionBlockerSystem.CanInteract(user))`
So because he was the owner of the handcuffs he could not remove them.
I think the isOwner-check is unnecissary at this point.
If I cannot interact it doesn't matter if I'm the owner or not, I simply cannot dehandcuff.

The code before shows a message `Loc.GetString.("You can't do that!")`. Is this still ok? I think if you're dead, reading this might confuse you. So I'm not sure about this.
I leave the message in and repair the rest.

**Review by ShadowCommander — APPROVED** [review]
Looks good!

**Comment by ShadowCommander** [comment]
Just remove the unnecessary using then it's ready to merge.

**Comment by scrato** [comment]
@ShadowCommander done :)

**Pull request merged**
