### PR TITLE
[Trait] Wheelchair bound

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR

Rework of #17116 with all requested changes.

Major change - splitting to 2 systems:
`LegParalyzedComponent` - disallow player to move and force him to lay down
`WheelchairBoundComponent` - spawn wheelchair and buckle player
Always spawning wheelchair on trait component applying looks cringie

**Media**

https://github.com/space-wizards/space-station-14/assets/14136326/960b5976-5bb8-45b9-b394-90936b504971

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: VigersRay, Morty
- add: Added wheelchair bound trait

### CODE REVIEW

**Comment by potato1234x** [comment]
finally i can steal peoples wheelchairs as clown

**Comment by Myakot** [comment]
> finally i can steal peoples wheelchairs as clown

True clowning is putting people in wheelchairs and THEN stealing them.

**Comment by potato1234x** [comment]
very true

**Comment by Emisse** [comment]
nukies will need a syndicate wheelchair, i think vg has sprites for this

**Comment by Emisse** [comment]
image
image
image
image

**Review by ZoldorfTheWizard — CHANGES_REQUESTED** [review]
LegParalyzed component should be plural (LegsParalyzed) in my opinion since when you apply this component it does not care which leg or how many legs the mob may have. 

Renam and ill speedmerg

**Comment by Morb0** [comment]
Done

**Pull request merged**
