### PR TITLE
Rebalance amatoxin so it is a slower killer

### PR DESCRIPTION
**Pull request by EdenTheLiznerd**
## About the PR

Amanita has been changed from 6 poison to 3 but it's metabolism rate is 0.25, if a full 30 units is given it can kill in 24.76 seconds (Yes I ran a stopwatch) just 5 units does around 32.10 _iirc_

## Why / Balance

Amatoxin killing you in just 12 to 16 seconds is well... Not great, you'd just drop and die with no ability to help yourself, this rectifies that by giving you time to run and grab charcoal or ask for help, note that it will still push you into full crit and death if left untreated

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
 :cl:
- tweak: Amanita toxin now kills you slightly slower, providing you time to seek charcoal before it's too late

### CODE REVIEW

**Comment by EdenTheLiznerd** [comment]
It... Ran just fine... What-

**Comment by EdenTheLiznerd** [comment]
Looks to be, it doubles the time it takes to kill you so... Mission accomplished

**Comment by deltanedas** [comment]
yes but it also takes a much higher dose

**Comment by EdenTheLiznerd** [comment]
> yes but it also takes a much higher dose

5u's do just around 31 to 32u's, that's pretty damn good

**Comment by Hrosts** [comment]
If you want to make it a slow killer, you should set its metabolism to some number less than 0.5 while increasing its damage, similar to how it currently works with lead. This here is just a straight up nerf, with it being both slower to kill and needing more of it for the same damage.

6/0.5 = 12 damage/u before
4.10/0.65 = ~6.3 damage/u after
You've made it 2 times as weak.

**Comment by deltanedas** [comment]
i think 0.2u/s would be a slow killer but also not too slow like lead, so theres still a good amount of actively dealt damage

**Comment by SlamBamActionman** [comment]
I disagree with this change from a balance point of view. While yes, Amatoxin is a very powerful toxin, it's also one of the hardest to acquire in the game in any meaningful quantities. Unless you are Chemistry or Nukies, your only reliable option is to use the kitchen blender, and even then the recipe is gated behind hydrogen which only Chemistry and possibly Cargo has access to.

Additionally, _all players_ start out with an amatoxin counter in the form of the emergency epipen. It's also one of the easiest toxins to treat in the medbay; someone dead from amatoxin can be immediately defibbed, and any additional airloss damage is just an inap or even bloodpack away.

**Comment by EdenTheLiznerd** [comment]
> If you want to make it a slow killer, you should set its metabolism to some number less than 0.5 while increasing its damage, similar to how it currently works with lead. This here is just a straight up nerf, with it being both slower to kill and needing more of it for the same damage.
> 
> 6/0.5 = 12 damage/u before
> 4.10/0.65 = ~6.3 damage/u after
> You've made it 2 times as weak.

Again it's still relatively easy-access to get amatoxin so it being a bit weaker isn't exactly a huge issue

**Comment by deltanedas** [comment]
its half the damage, thats not a bit weaker its a major nerf
its now on par or worse with mutagen i think

**Comment by BolloTea** [comment]
Please take away his ability to touch botany, he has already killed the nettle

**Comment by OctoRocket** [comment]
Even at 25ish seconds, it might not be enough time for you to receive help, but I do think it's better. I've always thought that having amatoxin as a slow but hard to heal poison would work well, needing intensive treatment but providing time to get that treatment. If balanced this way, it would be more of a tool of getting someone out of a fight (such as the captain or HoP) and open up opportunities to steal from them. This is just ideaguysing so maybe this is a bad idea but it's an idea.

**Comment by ZoNeSRuS** [comment]
Referring to the experience of the 13th station, I can say. Poison either kills or is useless, there is no third option. The poison must be prepared and injected into the victim. This is much more difficult than pressing a toolbox in the teeth.

**Comment by EdenTheLiznerd** [comment]
> Please take away his ability to touch botany, he has already killed the nettle

If you can come to my PR with genuine criticism that'd be great, thanks

**Comment by EdenTheLiznerd** [comment]
> I'll start by saying that I don't think this is necessary to begin with, amatoxin is still effectively gated behind botany and an exotic seeds crate, which for your average traitor would take about as much effort to procure as getting something like a stunbaton or making a better poison via the uplink chems, while effective injection of amatoxin is also a problem to be solved.
> 
> The PR's intent should not be shifted into "hey we should objectively nerf amatoxin" because "well it's still pretty good", there's no reason why amatoxin shouldn't be viable, shifting its use case into a slow but effective poison is *fine* but making it worse at killing in the process is uncalled for.
> 
> I agree with deltanedas' suggestion here, 0.2u/s is a pretty good mark.

Exotic seed crates are mapped on quite a few stations, I'll see about changing the rate of metabolization but again, it shouldn't be instant death, no matter the circumstance

**Comment by HoidC** [comment]
> Even at 25ish seconds, it might not be enough time for you to receive help, but I do think it's better.
> I've always thought that having amatoxin as a slow but hard to heal poison would work well, needing intensive treatment but providing time to get that treatment. If balanced this way, it would be more of a tool of getting someone out of a fight (such as the captain or HoP) and open up opportunities to steal from them. This is just ideaguysing so maybe this is a bad idea but it's an idea none the less.

At the point of which you’re in position to poison either of these people, mugging them through violence is probably quicker and easier and less risky.

**Comment by EdenTheLiznerd** [comment]
> > Even at 25ish seconds, it might not be enough time for you to receive help, but I do think it's better.
> > I've always thought that having amatoxin as a slow but hard to heal poison would work well, needing intensive treatment but providing time to get that treatment. If balanced this way, it would be more of a tool of getting someone out of a fight (such as the captain or HoP) and open up opportunities to steal from them. This is just ideaguysing so maybe this is a bad idea but it's an idea none the less.
> 
> At the point of which you’re in position to poison either of these people, mugging them through violence is probably quicker and easier and less risky. 

Generally this is more of a nukies balancing tweak, instakilling them with amatoxin feels pretty lazy on the game design spectrum so I feel like it doing as much damage as it does is pretty balanced for it's primary use

**Comment by SlamBamActionman** [comment]
I'm confused, how do you propose normal crew poisons Nukies? Best shot they got is the hypospray, which is one-of-a-kind, and after that we're looking at 2u dipped spears.

**Comment by EdenTheLiznerd** [comment]
> I'm confused, how do you propose normal crew poisons Nukies? Best shot they got is the hypospray, which is one-of-a-kind, and after that we're looking at 2u dipped spears.

Again a few well placed spear shots can still deal fair points of damage, the point of the poison isn't to instantly kill said nukie, you are better off using it to weaken them and make them more susceptible to other damage types, x-ray cannons and rifles, the like

**Comment by UbaserB** [comment]
> > I'm confused, how do you propose normal crew poisons Nukies? Best shot they got is the hypospray, which is one-of-a-kind, and after that we're looking at 2u dipped spears.
> 
> Again a few well placed spear shots can still deal fair points of damage, the point of the poison isn't to instantly kill said nukie, you are better off using it to weaken them and make them more susceptible to other damage types, x-ray cannons and rifles, the like

continuing from this, amatoxin should temporarily remove max stamina but in exchange have relatively low damage.

**Comment by OctoRocket** [comment]
That would be a very cool twist on amatoxin that makes it more than just
another poison.

**Comment by EdenTheLiznerd** [comment]
If someone can make a PR doing that I'll close this one 👍

**Comment by Anzarot121** [comment]
> Generally this is more of a nukies balancing tweak, instakilling them with amatoxin feels pretty lazy on the game design spectrum so I feel like it doing as much damage as it does is pretty balanced for it's primary use

Christ, did the botanists kill you again? One person with a spear will deal a maximum of 24 damage if he manages to hit the nuker 2 times. And this is not poison damage, which is difficult to heal, it’s just asphyxiation damage, which will all go away in 12 seconds. If you allowed a man with a spear to come to you while being a nuker, then I don’t know, do the depressurization, there is no need to weaken the botanists.

**Comment by OctoRocket** [comment]
It was identified in previous PRs that amatoxin was an issue.

**Comment by EdenTheLiznerd** [comment]
> > Generally this is more of a nukies balancing tweak, instakilling them with amatoxin feels pretty lazy on the game design spectrum so I feel like it doing as much damage as it does is pretty balanced for it's primary use
> 
> Christ, did the botanists kill you again? One person with a spear will deal a maximum of 24 damage if he manages to hit the nuker 2 times. And this is not poison damage, which is difficult to heal, it’s just asphyxiation damage, which will all go away in 12 seconds. If you allowed a man with a spear to come to you while being a nuker, then I don’t know, do the depressurization, there is no need to weaken the botanists.

I have nukie turned off actually, better yet, amatoxin does poison, not asphyxiation, feel free to check the damage type that is labeled under my changes

**Comment by K-Dynamic** [comment]
Making amatoxin act for much longer in exchange for less poison upfront is cool, means you have to constantly cure the poison damage or find charcoal (or vomit)

Maybe add an OD component where going over a certain unit just increases the damage while purging some units per tick

**Comment by TaoNewt** [comment]
Its not exactly overpowered. Its obtainable by a single job, its obvious to grow, it comes from a special crate, you need to blend it, you need to remove the nutriment if you want it to be potent, it takes multiple injections to kill, it takes enough time to kill that you can call out, its treatable in med.
Its a unique murder tool, its nowhere near as common or versatile as the guns, sabers or bombs, or even accessable as lex, so why further weaken it?

**Comment by asperger-sind** [comment]
> Generally this is more of a nukies balancing tweak, instakilling them with amatoxin feels pretty lazy on the game design spectrum so I feel like it doing as much damage as it does is pretty balanced for it's primary use

Crew injection methods are few and in-between, and if you see anyone that isn't the CMO using chems to combat nukies chances are they, surprisingly, aren't even using amatoxin, it's way more common to see people using spears to inject ipecac into nukies, and the hypospray owner wouldn't bother with botany as they most likely have chem access and can make XYZ that won't be overkill.

Instakilling isn't an option for 9/10 scenarios, the 1/10 is easily deductible (CMO gaming), and if a CMO goes headfirst into melee range they're taking a very risky play so it's only fair they get rewarded.

"Primary use" is silly to use here as it has not been established once throughout this conversation - or in general - it'd be good if a definition for amatoxin's primary use could be established before discussing so here's my pitch: slow-killing, but highly effective, general poison available to botany.

**Comment by ZoNeSRuS** [comment]
> > > В целом, это больше похоже на балансировку нюки, инстакиллинг с помощью аматоксина кажется довольно ленивым в спектре игрового дизайна, поэтому мне кажется, что он наносит столько урона, сколько он делает, довольно сбалансирован для своего основного использования
> > 
> > 
> > Боже, неужели ботаники опять убили тебя? Один человек с копьем нанесет максимум 24 урона, если ему удастся попасть в нюкера 2 раза. И это не урон ядом, который трудно лечить, это просто урон от удушья, который все пройдет за 12 секунд. Если вы позволили человеку с копьем подойти к вам, будучи нюкером, то я не знаю, делайте разгерметизацию, не надо ослаблять ботаников.
> 
> На самом деле, у меня nukie отключен, а еще лучше, аматоксин отравляет, а не удушает, не стесняйтесь проверять тип урона, который помечен под моими изменениями



> > > Даже на 25-й секунде этого времени может быть недостаточно для получения помощи, но я думаю, что это лучше.  Я всегда думала, что прием аматоксина в качестве медленного, но трудно излечиваемого яда будет работать хорошо, нуждаясь в интенсивном лечении, но давая время для этого лечения. Если бы это было сбалансировано таким образом, это было бы скорее инструментом для того, чтобы вывести кого-то из боя (например, капитана или HoP) и открыть возможности для кражи у них. Это всего лишь идеи, так что, возможно, это плохая идея, но, тем не менее, это идея.
> > 
> > 
> > В тот момент, когда вы можете отравить любого из этих людей, ограбление их с помощью насилия, вероятно, быстрее, проще и менее рискованно.
> 
> В целом, это больше похоже на балансировку нюки, инстакиллинг с помощью аматоксина кажется довольно ленивым в спектре игрового дизайна, поэтому мне кажется, что он наносит столько урона, сколько он делает, довольно сбалансирован для своего основного использования

Do I understand correctly that you decided to kill a whole mechan without understanding how it works? (I'm talking about botany now)If it bothers you so much, then open the code and see how the injector component works.

MeleeChemicalInjector
    transferAmount: 2
    solution: food
    pierceArmor: false //<-This property is already present in the component, and it is responsible for breaking through the rigs.
    
When the problem of poisons arose on my server, I just added 1 line. And now the rigs are protected from nettle attacks. And I don't understand why something should be nerfed when it can be done deeper. If you see a problem in poisons, give them protection (In my case, the rigs are the protection), but making poisons useless is to follow the path of simply scoring a goal will be more effective.

**Comment by ZoNeSRuS** [comment]
> > Please take away his ability to touch botany, he has already killed the nettle
> 
> If you can come to my PR with genuine criticism that'd be great, thanks

Do I understand correctly that you decided to kill a whole mechan without understanding how it works? (I'm talking about botany now)If it bothers you so much, then open the code and see how the injector component works.

MeleeChemicalInjector
transferAmount: 2
solution: food
pierceArmor: false //<-This property is already present in the component, and it is responsible for breaking through the space suits.

When the problem of poisons arose on my server, I just added 1 line. And now the space suits are protected from nettle attacks. And I don't understand why something should be nerfed when it can be done deeper. If you see a problem in poisons, give them protection (In my case, the space suits are the protection), but making poisons useless is to follow the path of simply scoring a goal will be more effective.

**Comment by K-Dynamic** [comment]
> > Making amatoxin act for much longer in exchange for less poison upfront is cool, means you have to constantly cure the poison damage or find charcoal (or vomit)
> 
> this PR makes amatoxin metabolize faster therefore lasting shorter than other reagents

I misread darn

**Comment by EdenTheLiznerd** [comment]
Reminder that a majority of maps come pre-mapped with exotic seed crates and that spears can be thrown, that's 2u's of poison per spear throw which adds up pretty quickly

**Comment by deltanedas** [comment]
> spears can be thrown

iirc this doesnt inject when thrown

**Comment by asperger-sind** [comment]
> Reminder that a majority of maps come pre-mapped with exotic seed crates and that spears can be thrown, that's 2u's of poison per spear throw which adds up pretty quickly

If someone is willing to throw and land several consecutive poisoned spears at you to kill you, they probably deserve to kill you, exotic seeds crate being mapped is a mapping issue and should be dealt with a mapping solution.

**Comment by Hrosts** [comment]
So, if you want to make it a slow burn while keeping the same damage/u:
Metabolism: 0.25
Poison: 3
This will make it kill twice as slow, while maintaining the old dosages for everything. Crit time of 32s, 12 damage/u

If you want to make it a slow burn, but make it _more_ deadly if not treated:
Metabolism: 0.2
Poison: 3
Crit time of 32s, 15 damage/u
OR
Metabolism: 0.25
Poison: 4
Crit time of 25s, 16 damage/u

I am not suggesting the options for opposite behavior as the initial stated goal was to "give you time to run and grab charcoal or ask for help".

**Comment by EdenTheLiznerd** [comment]
Changes are in, should provide less controversy overall and hopefully is good enough for the general populace

**Comment by thebadman4662** [comment]
Herbisquito about to murderbone whole station and this time they won't be even around when they feel ill to get spotted by their clueless victims. :trollface:

**Comment by EdenTheLiznerd** [comment]
> So, if you want to make it a slow burn while keeping the same damage/u: Metabolism: 0.25 Poison: 3 This will make it kill twice as slow, while maintaining the old dosages for everything. Crit time of 34s, 12 damage/u
> 
> If you want to make it a slow burn, but make it _more_ deadly if not treated: Metabolism: 0.2 Poison: 3 Crit time of 34s, 15 damage/u OR Metabolism: 0.25 Poison: 4 Crit time of 25s, 16 damage/u
> 
> I am not suggesting the options for opposite behavior as the initial stated goal was to "give you time to run and grab charcoal or ask for help".

Your suggestion has been implemented @Hrosts

**Comment by Hrosts** [comment]
I will mention that this change indirectly buffs the hypodart - 7u of amatoxin will now crit (105 Poison) if not treated in any way.

**Comment by OctoRocket** [comment]
> I will mention that this change indirectly buffs the hypodart - 7u of
amatoxin will now crit (105 Poison) if not treated in any way.

How long would it take to crit?

**Comment by EdenTheLiznerd** [comment]
Also I did just test, spears do inject upon being throwing (not sure if that is intentional or not but it does work)

**Comment by EdenTheLiznerd** [comment]
Again, I would rather amatoxin remain viable but not nerfed into the ground, I'm going to say current implementation is as good as it's getting currently without just... Numerous calculations

**Comment by EdenTheLiznerd** [comment]
Closing as part of the freeze, will reopen when that's finished

**Comment by OctoRocket** [comment]
Damn he called you a doofus…

**Comment by asperger-sind** [comment]
Even if the feature freeze was in-place I don't think this falls under "new feature" because it's a rebalance.

**Comment by EdenTheLiznerd** [comment]
So I'm a bit of a dumb dumb, lemme just uh... Reopen this :trollface:

**Comment by EdenTheLiznerd** [comment]
@metalgearsloth Oh supreme leader, is this ready to merge or do you want something changed?

**Comment by metalgearsloth** [comment]
I don't think any other maints have an opinion or they didn't see so.

**Comment by EdenTheLiznerd** [comment]
Truly a day to celebrate.

**Pull request merged**
