### PR TITLE
Arsenal tech discipline

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds a new tech discipline, arsenal.

full of weapons and other dangerous shit.

**Media**

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the new Arsenal research discipline.
- add: Added incendiary ammunition variants.
- tweak: Salvage Weapons and Signalling Tech are now part of the Arsenal discipline.
- tweak: Reduced taser shot count from 10 down to 5.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
this is funny

**Comment by Myakot** [comment]
Goodbye medium roleplay, embrace dakka.

**Comment by deltanedas** [comment]
taser ops

**Comment by Jackal298** [comment]
Will there be speedloaders in the research?

**Comment by OttoMaticode** [comment]
ever heard the tale of pandora's box?

**Comment by VektorZ1** [comment]
Taser too cheap, doesn't even require silver

**Comment by Equivocateur** [comment]
> taser ops
Counterpoint
image

**Comment by OttoMaticode** [comment]
> > taser ops
> 
> Counterpoint image

realise

**Pull request merged**
