### PR TITLE
Bots can now be put in closets

### LINKED ISSUE #10558: bots can't be placed in entityStorage
## Description

for some reason, you can't shove bots in lockers

**Reproduction**

spawn bot
spawn locker
try to place bot in locker
fail

**Screenshots**

image
image

**Additional context**

### PR DESCRIPTION
**Pull request by JustinTrotter**
## About the PR 
Fixes #10558 
**Screenshots**

**Changelog**

:cl:
- tweak: Bots can now be stuffed into closets

### CODE REVIEW

**Comment by Elijahrane** [comment]
This doesn't fix the actual bug and will likely have unintended consequences elsewhere

**Comment by JustinTrotter** [comment]
> This doesn't fix the actual bug and giving them a body will have unintended consequences elsewhere. You are also septupling the amount of entities bots take up

I don't understand several things. 

How does this not fix the bug? The bot goes into the closet now.

Can you give me an example of one of these unintended consequences? I'll address them if necessary.


From what I saw in the entityStorageSystem it requires entities by default to be mobs or items to enter it. The bodyComponent does that. All other mobs have this component including simplemobs. So what's the danger here?

How does this increase the amount of entities bots take up times 7? I don't understand this at all.

**Comment by Elijahrane** [comment]
> How does this not fix the bug? The bot goes into the closet now.

The bug is with the closet behavior, not with the bots. Giving them a body shouldn't be necessary.

>Can you give me an example of one of these unintended consequences? I'll address them if necessary.
You can dupe borg arms via gibbing, things that expect a body may accept the bots now where they wouldn't before and treat them wrong. In addition, they don't even have a body that accurately describes what they have.

>How does this increase the amount of entities bots take up times 7? I don't understand this at all.

Each limb or organ is its own entity

**Comment by EmoGarbage404** [comment]
At the very least, if you want to do it like this, the bot should have a custom body preset with the correct number of limbs.

**Comment by JustinTrotter** [comment]
> At the very least, if you want to do it like this, the bot should have a custom body preset with the correct number of limbs.

Sounds good. What would be the appropriate number of limbs for bots in this case?

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
