### PR TITLE
let medibot express itself better

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
adds the AM hate monologue from I Have No Mouth And I Must Scream to the list of medibot's rare quotes

## Why / Balance
now medibots can express their real feelings

## Media
tested, works
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
no

### CODE REVIEW

**Comment by chromiumboy** [comment]
I don't think this really fits...

**Comment by Ilya246** [comment]
> I don't think this really fits...

it's rare and is meant to be funny via surprising you

**Comment by Ilya246** [comment]
update: tested, added media

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and the consensus was to close this for the following reasons:
- The text is too long and causes visual spam.
- We don't want to include something that mentions specific hate to one species ("human").
- It does not really fit the medibot and not everyone will get the reference.

Thank you for your contribution.

**Pull request closed without merging**
