### PR TITLE
Ore Bags Can Go Into Your Pocket

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Reduced ore bag size to 10, so they can fit in pockets. Reduced the bag size from 175 to 150.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Ore bags can now go into your pockets, but had their slot size reduced a small amount.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i kinda disagree with this change. You're able to carry an absurd amount of ores in a single mining bag. Making it so you can both carry all the ores you want AND a full set of tools with both hands free feels silly.

**Comment by Alekshhh** [comment]
it's really for convenience. you are limited to three ore bags if you have a tool in your hand too. I can make the slots even smaller if need be, but it feels fine as is

**Comment by EmoGarbage404** [comment]
> are limited to three ore bags if you have a tool in your hand too.
my brother in christ you can go unload it at a base you don't need to carry around several metric tons of rocks.

**Comment by Alekshhh** [comment]
I just want them in my pocket if I feel like taking a few pet rocks at home while my priority isn't mining. even if it is a priority, it's not that big of a deal

**Comment by deltanedas** [comment]
when im done with exped swapping out belt with bag and going mining is fine since i wont have any use for the tools, but i might find a rogue xeno so having laser and knife is still important

**Comment by Emisse** [comment]
i dont like this i feel like if you want an ore bag with you it should go on belt, back, or hand. pocket feels a bit too convenient for convenience sake to me

**Comment by Alekshhh** [comment]
fair enough

**Pull request closed without merging**
