### PR TITLE
Kettle QoL

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

All these changes are for the Kettle map.

- RoboTech Deluxe vendor mapped into robotics
- Borg charging stations mapped for the following locations:
  - Robotics (2)
  - Cargo lobby
  - Arrivals
  - Evac
  - Tool room north of bar
  - Leisure/laundry area east of dorms
  - AI sattelite
- Solid plasma removed from sci and med
- Cargo now spawns with a guaranteed solid plasma crate (this is more plasma than originally present, but cargo has to distribute it)
- Cargo now spawns with 60 steel instead of 30 steel (should help with borg construction)
- Chemists now have a note in their area informing them that there is a drain in the morgue.
- Senior roles for engineering, med, sec and r&d.

## Why / Balance

Kettle has not been updated for borgs yet. This should accomodate that and make things easier roundstart. I have no claims that this is balanced, and I'm open for feedback on this subject.

## Technical details

n/a

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Don't believe media is necessary here, but if requested I will add.

## Breaking changes

n/a

**Changelog**

n/a

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
No clue why the yaml linter failed. Did it fail on my map file or is this something from unrelated commits from others?

**Comment by JustCone14** [comment]
> No clue why the yaml linter failed. Did it fail on my map file or is this something from unrelated commits from others?

code base was just changed so it's probably that.

**Comment by JustCone14** [comment]
"Serialization has been changed to require data definitions to be made partial (this includes components for example)"

**Comment by TsjipTsjip** [comment]
Marked as draft because senior roles are not yet in, I would like them in, but need some help in setting this up.

**Pull request merged**
