### PR TITLE
Lockable Suit Storages

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

image

Makes suit storages lockable.

## Why / Balance

Very silly that these couldn't be locked given how precious these suits are. It feels like a direct downgrade to map them without lockability.

## Technical details

Basically just YML changes, Floofers supplied me with the sprites.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- tweak: Suit Storage Units are now lockable.

### CODE REVIEW

**Comment by deltanedas** [comment]
rd suit stealers will seethe

**Comment by UbaserB** [comment]
woooo!

**Comment by NancokPS2** [comment]
I used to take the suits on a whim because i thought "if they aren't locked it must be for a reason".  
Until i realized how much it shafted late join paramedics. I wonder what was the original idea behind not locking them.

**Comment by rosieposieeee** [comment]
> I used to take the suits on a whim because i thought "if they aren't locked it must be for a reason". Until i realized how much it shafted late join paramedics. I wonder what was the original idea behind not locking them.
> 
> Maybe the point was to allow regular doctors to assist spaced patients? But they can just get a normal EVA if they are in such an emergency.

Yeah, pretty annoyed that the pr that properly added paramedic access was closed for basically no reason. I would vastly prefer that paramedics got their own access. Latejoining to find your suit gone, and its ALWAYS gone, makes paramedics into regular doctors but without chemistry access. It sucks.

**Comment by JoeHammad1844** [comment]
the paramedic suit isnt a hardsuit

**Comment by JoeHammad1844** [comment]
also you can give the para suit storage externals access instead since regular doctors dont have externals access

**Comment by UbaserB** [comment]
But then that means that so many other jobs like cargo, engineering etc can open it as long as they're in med (med is freely open so its likely that someone will open it)

**Comment by UbaserB** [comment]
> the paramedic suit isnt a hardsuit

wrong, its a hardsuit. In the games files at least, in-game its just called a void suit since it looks cool.

**Comment by JoeHammad1844** [comment]
a hardsuit has a togglable helmet, does the paramedic suit?

**Comment by rosieposieeee** [comment]
So _**in the files**_, should I call it a softsuit, a void suit...?

Also hell no on the externals thing. Paramedic should just have their own access. I am absolutely not making it Externals so any ham-and-egger can come along and nab it too.

**Comment by LankLTE** [comment]
> Yeah, pretty annoyed that the pr that properly added paramedic access was closed for basically no reason. 

We’ve explained why in that PR. I spoke with Emisse (the head mapper) as well as other maintainers beforehand and they agreed it was unnecessary as well, so it really wasn’t closed for no reason.

On a different note, I believe this will break every currently existing map as they have the non hardsuit versions mapped yet no suit storage. Might be wrong though, and I don’t know what maps did when suit storages were initially added, so maybe it isn’t an issue.

**Comment by rosieposieeee** [comment]
Yes, the Paramedic suit storages will need to be mapped just like last time. I don't play on upstream maps so I'm not modifying any maps here.

**Comment by rosieposieeee** [comment]
I'm just gonna remove the Paramedic suit storages from this PR since Paramedics can't have shit in wizdetroit.

**Comment by LankLTE** [comment]
> I'm just gonna remove the Paramedic suit storages from this PR since Paramedics can't have shit in wizdetroit.

Never said that was necessary- I’m fine with parameds having a suit storage. Just saying that there should probably be some solution to existing maps just not having parameds hits (other than the one in the bend) after this PR is merged and before *every* map is updated

**Comment by rosieposieeee** [comment]
> > I'm just gonna remove the Paramedic suit storages from this PR since Paramedics can't have shit in wizdetroit.
> 
> Never said that was necessary- I’m fine with parameds having a suit storage. Just saying that there should probably be some solution to existing maps just not having parameds hits (other than the one in the vend) after this PR is merged and before _every_ map is updated

It's probably out of scope for this PR if mapping changes have to happen. I'd rather just get the lockers locking first, since that already works. It's like two yaml changes to add the paramedic storages back in anyway.

**Comment by UbaserB** [comment]
> > > I'm just gonna remove the Paramedic suit storages from this PR since Paramedics can't have shit in wizdetroit.
> > 
> > 
> > Never said that was necessary- I’m fine with parameds having a suit storage. Just saying that there should probably be some solution to existing maps just not having parameds hits (other than the one in the vend) after this PR is merged and before _every_ map is updated
> 
> It's probably out of scope for this PR if mapping changes have to happen. I'd rather just get the lockers locking first, since that already works. It's like two yaml changes to add the paramedic storages back in anyway.

i could potentially do it myself as its not a hard change after this PR, else emisse would likely be willing to.

**Pull request merged**
