### PR TITLE
Syringe QoL improvements

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Made it so that you can't toggle to draw if your syringe is full, can't toggle to inject if your syringe is empty, and updated the messages so that both users/targets could be able to tell if they are trying to draw or inject rather than just "inserting a needle."

## Why / Balance

I noticed people thinking their syringes were broken because they were attempting to inject while empty or draw while full. I also noticed that both doctors and their targets were unable to tell if they were drawing or injecting. Many times this resulted in a doctor drawing blood from the patient rather than injecting medicine....

## Technical details

Added checks for injector state (draw/inject) for messages and checks based on the volume of the container to prevent toggling.

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None that I know of

**Changelog**

:cl:
 - tweak: Syringes now prevent injecting on empty and drawing on full.
 - tweak: You can now tell if you are being drawn from or injected by a syringe.

### CODE REVIEW

**Comment by deltanedas** [comment]
i think any human being would know if theyre being injected with something vs drawing blood, theyre opposite motions

**Comment by Plykiya** [comment]
it doesn't take any kind of special medical knowledge to know whether someone is pulling something out of you versus putting something in you, you just look at the syringe and see if the funny liquid is increasing or decreasing...

**Review by VasilisThePikachu — APPROVED** [review]
Anyway this looks good to me in my opinion

**Comment by K-Dynamic** [comment]
> That's mostly true, but I don't think it's this simple when we put it in context of the game, consider this counterargument...

Ok but consider the fact 99% of doctors don't want to repeat a 5 second doafter when injecting a dead patient, or the fact people just examine the strip menu to see the syringe

I have literally never seen the scenario you've described with two tl;dr alone since patients will just get pissed (they have chembook in their guide), and traitors will not be fucking around with a syringe when they'll just minibomb your bed

**Comment by vorkathbruh** [comment]
pretty sure syringes show whats inside so you cant fake injections anymore so idk what is being waffled about

**Comment by deltanedas** [comment]
> An inquisitive player suspecting a traitor doctor would try to acquire a medical analyzer and try to catch the culprit red-handed

this just doesnt exist

why would a traitor try to draw 15u of your blood, they could inject a lethal dose of poison instead (which you would not think twice of since draw=valid and you arent already stripping so you wont see whats in the syringe, otherwise youd see its empty so theyre drawing)

15u on its own does no damage 30u will do a tick of bloodloss any more you can just poison someone

**Comment by VasilisThePikachu** [comment]
> Long reply:
> Effort post...

If I were in front of you and I tried injecting you with poison when I claimed I would be drawing blood you would have probably noticed. Since instead of a red liquid filling the syringe, the liquid is going into you. 

I don't see how knowing this is "metagaming" or "powergaming". No information is shared out of the game, you don't need to be a medical professional to realize someone is using a syringe on you. I sadly don't see this argument making sense. I doubt hiding injections or showing them will change anything

Anyway, I will stop arguing about this, a maintainer can see this discussion and decide themselves.

**Comment by Cojoke-dot** [comment]
Pro- you don't have to check your syringe if it's injecting when it's full
cons- you can't do some weird-ass syndie play that would not work anyways because it says if someone is injecting or drawing from you that someone can invalidate by inspecting the person injecting you.

You're trying too hard to not get a change that is more of a bug fix than anything, the only negative to this is a trick that does not even work nor does it make any sense when you could just get a hypopen

**Comment by vorkathbruh** [comment]
implanters (which are syringes) alert you when injecting so this really just feels like more consistent design

**Comment by Brandon-Huu** [comment]
Yeah. I agree these two changes should be in separate PRs

**Comment by deltanedas** [comment]
> The biggest problem is the newbies being yelled at by veterans more

yep this is much worse than a hypothetical traitor non-issue

**Review by AJCM-git — APPROVED** [review]
Don't got too much time to explain but the arguments against the popup are just very weak, you should always be able to tell what's happening to your character in the case of something as obvious and inconsequential as drawing or injecting, there are a million other more obvious ways to tell if someone is incompetent and you still have to pay attention to the popup to get the necessary information. 
Any intrigue that was caused by the vagueness of the old message can be disregarded as it's pretty inconsequential and it can still exist by being willfully (or unwillingly) incompetent and injecting way smaller doses than what's necessary to heal or injecting a chem with no effects, just that this time the intrigue is reinforced by the fact that you know someone *did* inject you but don't know if they willfully made an error, instead of before where you had to wonder if the error was made at the injecting/drawing part, basically it moved this extremely minor case of intrigue a step forward, so it's basically the same.

**Pull request merged**
