### PR TITLE
Grey mantle in winterdrobe

### PR DESCRIPTION
**Pull request by pigeonpeas**
## About the PR
Adds a grey mantle, meant for everyone on the station. I like mantles, and I wanted to be able to have one without being command

## Media
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added non command mantle into the winterdrobe

### CODE REVIEW

**Comment by EdenTheLiznerd** [comment]
Oh these look awesome, a lot of people would definitely love to have these

**Comment by Kukutis96513** [comment]
head of tiders..

**Comment by Aisu9** [comment]
next step, allowing custom colouration of grey-scale items

**Comment by pigeonpeas** [comment]
> head of tiders.. (also could it be possible for it to be in loadouts?)

was planning on doing this after this gets (hopefully) merged because i'm _laazyyy_

**Comment by timurjavid** [comment]
> > next step, allowing custom colouration of grey-scale items
> 
> this is the next step, along with removing all the color options from the vendors to stop the item bloat

Don't want to get off-topic too much, but is there an issue open for this? I'd be interested in looking it

**Comment by IProduceWidgets** [comment]
> > > next step, allowing custom colouration of grey-scale items
> > 
> > 
> > this is the next step, along with removing all the color options from the vendors to stop the item bloat
> 
> Don't want to get off-topic too much, but is there an issue open for this? I'd be interested in looking it

I think someone has washing machines that can recolor greyscale items in the works, I would ask on Discord, dunno if its pred yet.

**Comment by UbaserB** [comment]
It might be better for it to be a rare maints loot tbh

**Review by SlamBamActionman — APPROVED** [review]
While Command mantles are a sign of status and thus need to be restricted in number and availability, we also have plenty of capes that don't signify role. I think this works just fine in the winterdrobe as an addition to the "winter passenger" clothing line.

**Review by UbaserB — CHANGES_REQUESTED** [review]
It should be a passenger loadout unlock instead of in the winterdrobe and printable.

**Comment by Pumkin69** [comment]
i prefer it as a 60 hours passenger unlock because i like status symbols.

**Comment by pigeonpeas** [comment]
Alright, I removed it from the lathes, and the winterdrobe, then added it into the passenger loadout with a 20 hour timer.

image

**Comment by TheWaffleJesus** [comment]
you forgot to add it to the winterdrobe, pretty sure (silly)

**Pull request merged**
