### PR TITLE
Show how close bodies are to rotting

### PR DESCRIPTION
**Pull request by quatre**
## About the PR
When examining a dead body, you will be able to see of close it is to rotting.

 - "It still looks fresh.", in the first third of the pre-rot period
 - ~"It looks ripe."~ "It looks somewhat fresh." , in the second third
 - ~"It's starting to look bad."~ "It doesn't look fresh anymore.", in the last third

## Why / Balance
This could help players prioritize medical care.

## Technical details

I ~completely stole~ took inspiration from the OnExamined of RottingComponent, but this time I did it with the Generic Entity<T> thing.

## Media
not_decaying
bad
ripe
fresh

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Examining bodies now shows how close they are to rotting.

### CODE REVIEW

**Comment by mirrorcult** [comment]
"ripe" is a really weird word to use to describe this imo

**Comment by quatre** [comment]
> But should this be in basic examination or in health examination? Seems a little out of place with the "He is dead." missing.
Probably could be in the other examinations. I prefer it to stay in the OnExamined because it will be more visible, but I wont be sad if we move it elsewhere.

The "He's dead." is missing because it's soul-less (Purple text) It shows He's dead if I possess it. 

> "ripe" is a really weird word to use to describe this imo
Assuredly. I'm not a native English speaker, so if anyone has a better idea for the descriptions, shoot!

**Comment by HoidC** [comment]
> > But should this be in basic examination or in health examination? Seems a little out of place with the "He is dead." missing.
> > Probably could be in the other examinations. I prefer it to stay in the OnExamined because it will be more visible, but I wont be sad if we move it elsewhere.
> 
> The "He's dead." is missing because it's soul-less (Purple text) It shows He's dead if I possess it.
> 
> > "ripe" is a really weird word to use to describe this imo
> 
> Assuredly. I'm not a native English speaker, so if anyone has a better idea for the descriptions, shoot!

"It looks fresh."
"It's beginning to decay."
"It's heavily decayed."
this is is my suggestion

**Comment by mirrorcult** [comment]
agree with hoid

**Comment by Hmeister-fake** [comment]
>  "It's heavily decayed." 

sounds a bit too harsh, new players may get confused with it and rotting. I suggest "It's about to decay past revival" or "It's about to rot"

**Comment by quatre** [comment]
> > "It's heavily decayed."
> 
> sounds a bit too harsh, new players may get confused with it and rotting. I suggest "It's about to decay past revival" or "It's about to rot"

Meat (the food) also has the PerishableComponent and it cannot be revived, so talking about Revival would be strange, although unexpected and fun. Why not?

I don't really like "about to rot" because, even though in the game a thing is either rotting or not rotting, to me it makes more sense as a continuum. And so, I wanted the wording not to sound too mechanical, a bit like we have the quite poetic Yellow and Purple texts that stay a bit in the vague.

**Comment by quatre** [comment]
Thanks everyone for your inspiring suggestions.
I'm thinking to go with:
- It looks fresh.
- It looks somewhat fresh.
- It doesn't look fresh anymore.

It works with everything (bodies, meat, future perishables?), doesn't sound too obvious and steers away from the semantic field of rot/decay, avoiding confusion.

Thanks for mentioning `GrammarComponent`. Though I'd happily keep it for another change as suggested, I think it would make it even more engaging.

**Comment by yathxyz** [comment]
> > "It's heavily decayed."
> 
> sounds a bit too harsh, new players may get confused with it and rotting. I suggest "It's about to decay past revival" or "It's about to rot"

I believe that the most relevant word would be "decomposing".

**Comment by quatre** [comment]
I made the changes, and re-checked the labels IG, they look good. If nobody objects I'll skip re-uploading screenshots.
CI is complaining, but that doesn't look related to this change.

**Comment by Partmedia** [comment]
Hi there, thanks for the PR. I've pushed some minor changes that use a numeric FTL string. Please review that and give it an okay. As for the actual FTL strings themselves, I think the text and color could still use some improvement. But I don't consider that a blocking issue and will merge tomorrow if we can't think of something better :)

**Review by Partmedia — APPROVED** [review]

**Comment by quatre** [comment]
Thanks for the changes! It works as expected and the code looks better, so it's good to go in my opinion. There's still the issue of failing tests, but that still seems unrelated.

**Pull request merged**
