### PR TITLE
Add airtight component to diagonal shuttle walls

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
1 line edit to make diagonal walls airtight so they can be used.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
How does this work if you're standing in the same tile as the diagonal? Will it not prevent air from reaching you?

**Comment by ChilbroBaggins** [comment]
I tested by spawning mice in the area. Before edit, they died, after they lived. Your concern is if someone is standing directly on the half tile that's "open"?

**Comment by EmoGarbage404** [comment]
Yes.

**Comment by ChilbroBaggins** [comment]
hmm. well, seems a small chance that someone would stand in that spot for long enough to die, but making the walls act as a half tile is probably over my head.

**Comment by mirrorcult** [comment]
where exactly are these mapped that this actually matters? if these are required to be airtight i cant imagine the map not looking incredibly wrong and ugly

**Comment by ChilbroBaggins** [comment]
Screenshot 2022-09-29 133555

**Comment by ChilbroBaggins** [comment]
Currently trying to use them here

**Comment by moonheart08** [comment]
They should not be full airtight, only the two flat walls should have the airtight bit set.

**Comment by ChilbroBaggins** [comment]
> They should not be full airtight, only the two flat walls should have the airtight bit set.

I'm not sure I understand what you're saying.

The sections that are diagonal are letting not airtight and that's a problem.

**Comment by ElectroJr** [comment]
The diagonal tiles should only block air in two directions, and let air flow in the other two. I.e., in tis image red = blocked.

**Comment by ChilbroBaggins** [comment]
so, if I'm not mistaken, it;s really just a matter of adding

    noAirWhenFullyAirBlocked: false
    airBlockedDirection:
    - South
    -East

**Comment by ElectroJr** [comment]
I think so. you should also check the directions are correct by using the `showatmos` command. Blocked directions should have little white lines.

**Comment by ChilbroBaggins** [comment]
Looks legit
image

**Review by ElectroJr — APPROVED** [review]

**Pull request merged**
