### PR TITLE
Scattershot antag fixes

### LINKED ISSUE #27402: NUKIES CAN ROLL THIEF
image

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

fix some incorrect calculations that resulted in overestimating the amount of antags there should be for latejoin. I don't know if this entirely fixes it but it was broken anyways.

also thieves now check for mutually exclusive antags, so nukeops can't be thieves anymore.

adds some comments and shit.

fixes #27402 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by Plykiya** [comment]
also affects #27424 and #27423

**Comment by metalgearsloth** [comment]
test fail real?

**Comment by EmoGarbage404** [comment]
> test fail real?

probably i'll look at it tomorrow (3hr calc final dear god)

**Comment by metalgearsloth** [comment]
goofy

**Pull request merged**
