### PR TITLE
TESTMERGE| Removes HoP from cluster, gives every head an ID card computer

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Removed HoP from cluster, gives every head an ID card computer
## Why / Balance

https://discord.com/channels/310555209753690112/770682801607278632/1250464450868416543
For a testmerge, multiple people were okay with it
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Boaz1111
- add: Added ID card computers to every head room on cluster |TESTMERGE|
- remove: Removed HoP on cluster |TESTMERGE|

### CODE REVIEW

**Comment by beck-thompson** [comment]
I don't think I agree but Its a good thing to test! Hoppy is odd compared to the rest of the heads. Maybe we should also try giving them more things to do for another test (Duno what that would be 😆)?

**Comment by deltanedas** [comment]
finally janitors have no gods no masters

**Comment by Moomoobeef** [comment]
this is blasphemy

**Comment by Boaz1111** [comment]
this is war

**Comment by Boaz1111** [comment]
needed more controversial prs

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Need someone to give a good reason why removing hop is good for the state of the game. From what I can tell this is another "I as a hop only stay in my office resulting me to get bored, if only I could have much more fun by leaving my office and actually *roleplaying*"

I will also add what panda added here, ian as a tot target, reducing heads by 1 makes revs easier and if the captain is dead no one is there to fill in as the head of all heads unless you wanna make the hos that one.

**Comment by Boaz1111** [comment]
yeah I agree, people were talking about it, I don't necessarily agree with it, but I figured I would open a pr to see what y'all tohught

**Comment by engineer-pearl** [comment]
I would raise a few concerns

There is benefit to having someplace to take people who lack IDs, and benefit to having a good starting location for job changes. I have also reached out to HOP when departments are unstaffed.

**Comment by EtereohZ** [comment]
Wasn't this already tried last year?


> I would raise a few concerns
> 
> There is benefit to having someplace to take people who lack IDs, and benefit to having a good starting location for job changes. I have also reached out to HOP when departments are unstaffed.

I agree.
I think it's important to have a central role who can serve as liaison between the departments and the crew, as the other heads are too focused, and rightly so, on their own departments. Someone handling personnel, ID's and accesses (also service).
It's also a great RP role.

**Comment by Boaz1111** [comment]
closing the PR for now

**Comment by LordEclipse** [comment]
If HOP were gone, who would lead the service department? Sure, its a collection of mostly unrelated jobs, but you can't give the job to Captain, as Captain leads the heads and station, and every other head has their place.

**Comment by thebadman4662** [comment]
HoPs never do their job and manage service though...

Still, heads should have their own ID computers so they can promote, demote and hire crew themselves. ID consoles in hos and cmo office would greatly help cleaning manifest and marking legacy IDs as crew permanently dies or become perma prisoners.

**Pull request closed without merging**
