### PR TITLE
Added lobby music: space lift to rigel

### PR DESCRIPTION
**Pull request by dahnte**
## About the PR

Added new lobby music

## Why / Balance

Some variation to the current lobby music lineup

## Technical details

Modified `attributions.yml` and `lobby.yml` in the `lobby` folder, added `space_lift_to_rigel.ogg`

## Media

https://www.youtube.com/watch?v=Svx5qe4y5kE

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added lobby music: space lift to rigel!

### CODE REVIEW

**Comment by CatMagic1** [comment]
I like chill lobby songs, this is really nice 
however
https://github.com/space-wizards/space-station-14/issues/8524

**Comment by dahnte** [comment]
> I like chill lobby songs, this is really nice however #8524

got it, should I close or leave it until the freeze is over?

**Comment by CatMagic1** [comment]
uhhhh I am not a maintainer so wait until one of them tells you what to do

**Comment by moonheart08** [comment]
It's still frozen. We're not accepting new lobby music at this time.

**Pull request closed without merging**
