### PR TITLE
Add radiation damage to anomalous particles 

### PR DESCRIPTION
**Pull request by lzk228**
### Default particles
Before:
Heat: 5
After:
Heat: 3
Radiation: 0.25
### Omega particle
Before:
Heat: 20
After:
Heat: 10
Radiation: 5
## Why / Balance

https://en.m.wikipedia.org/wiki/Radiation

Why so small values?
So that there were injuries, but not very serious 

## Technical details

added category-comment before anomalous particles:trollface:

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

no

**Changelog**

:cl:
- tweak: APE/CHIMP particles now also causes radiation damage.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
What's the point in giving a utility tool more damage? We've already rejected damage buffs to the APE/CHIMP in the past.

**Comment by chromiumboy** [comment]
APE and CHIMP barely do any damage already, why drop it further?

**Comment by lzk228** [comment]
> What's the point

https://en.m.wikipedia.org/wiki/Radiation

> more damage

but it less total damage

**Comment by LankLTE** [comment]
Linking a wiki article to radiation is not a reason why. This change feels unnecessary.

**Comment by Aisu9** [comment]
this is the point of **"utility"** tools no? your supposed to kill people with utility tools

**Comment by Varen** [comment]
Would this allow radiation triggering on an artifact? Cause if so that's better than crafting uranium spears.

**Comment by chromiumboy** [comment]
> Would this allow radiation triggering on an artifact? Cause if so that's better than crafting uranium spears.

You need 50 damage for the radiation trigger, so the proposed damage model wouldn't make this option feasible

**Comment by deltanedas** [comment]
radiation damage is not radiation, no amount would do it afaik

**Comment by ItsMeThom** [comment]
> > Would this allow radiation triggering on an artifact? Cause if so that's better than crafting uranium spears.
> 
> You need 50 damage for the radiation trigger, so the proposed damage model wouldn't make this option feasible

Would it build up over time on the artifact or is it based on a single strike? its very frustrating that the only way to trigger the radiation activator is by tracking down some uranium glass or throwing the artifact near the singularity (if the station even has one). Having a fallback case where an emitter can be used, albeit slowly, is very useful.

**Comment by metalgearsloth** [comment]
Change doesn't seem favourable.

**Pull request closed without merging**
