### PR TITLE
Added Metal Tag to Syndicate IDs

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I added the Metal Tag to Syndicate IDs.
## Why / Balance

Nukies can microwave their ID and copy it repeatedly for nigh AA. I don't think having AA before even entering the same space as the station is balanced.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

image

:cl:
- tweak: Syndicate IDs make Microwaves explode

### CODE REVIEW

**Comment by FungiFellow** [comment]
Wrong branch

**Comment by Golinth** [comment]
This is a pretty significant nerf to nearly every nukie strategy besides the basic hit armory first ‘stealth ops’ 
I do think that nukies need to be nerfed somehow, but I don’t think I like further limiting the availability strategies for nukies.

**Comment by FungiFellow** [comment]
> This is a pretty significant nerf to nearly every nukie strategy besides the basic hit armory first ‘stealth ops’ I do think that nukies need to be nerfed somehow, but I don’t think I like further limiting the availability strategies for nukies.

I don't think 3TC AA is balanced for Nukies to have

**Comment by thebadman4662** [comment]
Far from AA considering it can dupe access and thus you are not guaranteed anything new, can do 100 cooks and still have only bad access, its just that the average goes up if you manage to avoid frying your syndicards early and remember to try and copy new access every time.

**Comment by ElPidor** [comment]
you just buy clown kit and put clown id's, Nerf didnt work lol

**Comment by FungiFellow** [comment]
> you just buy clown kit and put clown id's, Nerf didnt work lol

Guess what ID is about to also get nerfed.

**Comment by Golinth** [comment]
> Guess what ID is about to also get nerfed.

Unless you create a brand new ID type, im not sure what you could do here. Giving it agent ID would be OP, making the ID metal would make all IDs metal.

**Comment by Hrosts** [comment]
Wouldn't an easier option be to remove the microwave from the nukie base?

**Comment by mirrorcult** [comment]
microwave should just get removed from the nukie base. i agree this is really stupid for nukies to be able to do

**Comment by thebadman4662** [comment]
Microwave is also gateway to microwave chemistry, you would remove more than just IDs.

**Comment by thebadman4662** [comment]
> they have a hotplate

Hotplate can't be used for microwave chem, microwave itself is one of "ingredients".

**Comment by FungiFellow** [comment]
> Hotplate can't be used for microwave chem, microwave itself is one of "ingredients".

To my understanding the microwave is only needed for Aloe / Sutures / Meshes

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by Brandon-Huu** [comment]
Also making them metal doesn't stop the nukies from just buying other id cards from the uplink

**Comment by deltanedas** [comment]
then you at least have to pay for aa instead of literally free aa

**Pull request closed without merging**
