### PR TITLE
Run variantize on barratry

### PR DESCRIPTION
**Pull request by TsjipTsjip**
Also use new asteroid plating tile in sci

## About the PR

- Run variantize on barratry's grid
- Use the new asteroid plating texture in sci's asteroid annex

## Why / Balance

https://discord.com/channels/310555209753690112/771041304108072961/1144540254632677406

## Technical details

n/a

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Sci annex:
image

## Breaking changes

n/a
**Changelog**

n/a

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
Diff is half the map size again somehow. Think variantize has something to do with it?

**Comment by Emisse** [comment]
its because of the tile changes yes

**Comment by TsjipTsjip** [comment]
I don't do mapping in an IDE. The only thing I can do is upload the file my mapping server gives me. And it works, otherwise I wouldn't open the PR.

**Comment by TsjipTsjip** [comment]
Hold off on merging, requested changes are coming.

**Comment by TsjipTsjip** [comment]
Requested changes applied.

**Pull request merged**
