### PR TITLE
Pressure & volume pumps can be toggled on/off now

### PR DESCRIPTION
**Pull request by 20kdc**
Clicking on the pump toggles it on/off.

This might or might not be suitable for a separate component.
Tell me in PR comments I guess.

### CODE REVIEW

**Review by PaulRitter — CHANGES_REQUESTED** [review]
you should use ihandinteract for this, iactive has no implicit interactionchecks run

**Comment by 20kdc** [comment]
ah

**Comment by 20kdc** [comment]
...what IHandInteract, exactly? I was unable to find an interface with that name.

**Comment by PaulRitter** [comment]
IInteractHand, sorry

**Review by PJB3005 — COMMENTED** [review]
Don't listen to Paul this should 100% be `IActivate`. These kinds of interactions are exactly what `IActivate` is meant for (do not involve hand contents, you could easily toggle a pump with a pen in your hand).

If interaction checks are not ran by InteractionSystem on `IActivate` that should be fixed instead because that's 100% a bug.

**Comment by PaulRitter** [comment]
i'll call that an oopsie on my part

**Review by metalgearsloth — APPROVED** [review]

**Comment by metalgearsloth** [comment]
@collinlunn

**Review by collinlunn — APPROVED** [review]
Looks fine

**Pull request merged**
