### PR TITLE
great organs reparenting

### PR DESCRIPTION
**Pull request by lzk228**
reparented all organs

before

<details>
  <summary>graph in text</summary>

```
digraph {
BaseItem -> BaseAnimalOrganUnGibbable ;
BaseAnimalOrganUnGibbable -> BaseAnimalOrgan ;
BaseAnimalOrgan -> OrganAnimalLungs ;
BaseAnimalOrgan -> OrganAnimalStomach ;
OrganAnimalStomach -> OrganMouseStomach ;
BaseAnimalOrgan -> OrganAnimalLiver ;
BaseAnimalOrgan -> OrganAnimalHeart ;
BaseAnimalOrgan -> OrganAnimalKidneys ;
OrganAnimalStomach -> OrganBloodsuckerStomach ;
OrganAnimalLiver -> OrganBloodsuckerLiver ;
OrganAnimalHeart -> OrganBloodsuckerHeart ;
OrganAnimalStomach -> OrganAnimalRuminantStomach ;
BaseItem -> SentientSlimesCore ;
OrganHumanBrain -> SentientSlimesCore ;
BaseHumanOrgan -> OrganSlimesLungs ;
BaseItem -> BaseArachnidOrgan ;
OrganAnimalStomach -> OrganArachnidStomach ;
BaseArachnidOrgan -> OrganArachnidLungs ;
BaseArachnidOrgan -> OrganArachnidHeart ;
BaseHumanOrgan -> OrganArachnidLiver ;
BaseHumanOrgan -> OrganArachnidKidneys ;
BaseArachnidOrgan -> OrganArachnidEyes ;
BaseArachnidOrgan -> OrganArachnidTongue ;
BaseItem -> BaseDionaOrgan ;
BaseDionaOrgan -> OrganDionaBrain ;
OrganHumanBrain -> OrganDionaBrain ;
BaseDionaOrgan -> OrganDionaEyes ;
BaseDionaOrgan -> OrganDionaStomach ;
BaseDionaOrgan -> OrganDionaLungs ;
OrganDionaBrain -> OrganDionaBrainNymph ;
OrganDionaStomach -> OrganDionaStomachNymph ;
OrganDionaLungs -> OrganDionaLungsNymph ;
MobDionaNymph -> OrganDionaNymphBrain ;
MobDionaNymphAccent -> OrganDionaNymphStomach ;
MobDionaNymphAccent -> OrganDionaNymphLungs ;
OrganHumanHeart -> OrganDwarfHeart ;
OrganHumanLiver -> OrganDwarfLiver ;
OrganHumanStomach -> OrganDwarfStomach ;
BaseItem -> BaseHumanOrganUnGibbable ;
BaseHumanOrganUnGibbable -> BaseHumanOrgan ;
BaseHumanOrganUnGibbable -> OrganHumanBrain ;
BaseHumanOrgan -> OrganHumanEyes ;
BaseHumanOrgan -> OrganHumanTongue ;
BaseHumanOrgan -> OrganHumanAppendix ;
BaseHumanOrgan -> OrganHumanEars ;
BaseHumanOrgan -> OrganHumanLungs ;
BaseHumanOrgan -> OrganHumanHeart ;
BaseHumanOrgan -> OrganHumanStomach ;
BaseHumanOrgan -> OrganHumanLiver ;
BaseHumanOrgan -> OrganHumanKidneys ;
OrganAnimalStomach -> OrganMothStomach ;
OrganHumanStomach -> OrganMothStomach ;
OrganHumanLungs -> OrganRatLungs ;
OrganAnimalStomach -> OrganRatStomach ;
OrganAnimalStomach -> OrganReptilianStomach ;
BaseItem -> SentientSlimeCore ;
OrganHumanBrain -> SentientSlimeCore ;
BaseHumanOrgan -> OrganSlimeLungs ;
OrganHumanLungs -> OrganVoxLungs ;
}
```

</details>

out

after
<details>
  <summary>graph in text</summary>

```
digraph {
OrganAnimalStomach -> OrganMouseStomach ;
OrganAnimalStomach -> OrganBloodsuckerStomach ;
OrganAnimalLiver -> OrganBloodsuckerLiver ;
OrganAnimalHeart -> OrganBloodsuckerHeart ;
OrganAnimalStomach -> OrganAnimalRuminantStomach ;
SentientSlimeCore -> SentientSlimesCore ;
OrganSlimeLungs -> OrganSlimesLungs ;
OrganAnimalStomach -> OrganArachnidStomach ;
BaseArachnidOrgan -> OrganArachnidStomach ;
BaseOrganLungs -> OrganArachnidLungs ;
BaseArachnidOrgan -> OrganArachnidLungs ;
BaseOrganHeart -> OrganArachnidHeart ;
BaseArachnidOrgan -> OrganArachnidHeart ;
BaseHumanOrgan -> OrganArachnidLiver ;
OrganAnimalLiver -> OrganArachnidLiver ;
BaseArachnidOrgan -> OrganArachnidLiver ;
BaseHumanOrgan -> OrganArachnidKidneys ;
OrganAnimalKidneys -> OrganArachnidKidneys ;
BaseArachnidOrgan -> OrganArachnidKidneys ;
BaseOrganEyes -> OrganArachnidEyes ;
BaseArachnidOrgan -> OrganArachnidEyes ;
BaseOrganTongue -> OrganArachnidTongue ;
BaseArachnidOrgan -> OrganArachnidTongue ;
BaseItem -> BaseBaseOrgan ;
BaseBaseOrgan -> BaseOrgan ;
BaseBaseOrgan -> BaseOrganBrain ;
BaseOrgan -> BaseOrganEyes ;
BaseOrgan -> BaseOrganTongue ;
BaseOrgan -> BaseOrganAppendix ;
BaseOrgan -> BaseOrganEars ;
BaseOrgan -> BaseOrganLungs ;
BaseOrgan -> BaseOrganHeart ;
BaseOrgan -> BaseOrganStomach ;
BaseOrgan -> BaseOrganLiver ;
BaseOrgan -> BaseOrganKidneys ;
BaseOrganLungs -> OrganAnimalLungs ;
BaseAnimalOrgan -> OrganAnimalLungs ;
BaseOrganStomach -> OrganAnimalStomach ;
BaseAnimalOrgan -> OrganAnimalStomach ;
BaseOrganLiver -> OrganAnimalLiver ;
BaseAnimalOrgan -> OrganAnimalLiver ;
BaseOrganHeart -> OrganAnimalHeart ;
BaseAnimalOrgan -> OrganAnimalHeart ;
BaseOrganKidneys -> OrganAnimalKidneys ;
BaseAnimalOrgan -> OrganAnimalKidneys ;
BaseOrganBrain -> OrganDionaBrain ;
BaseDionaOrgan -> OrganDionaBrain ;
BaseOrganEyes -> OrganDionaEyes ;
BaseDionaOrgan -> OrganDionaEyes ;
BaseOrganStomach -> OrganDionaStomach ;
BaseDionaOrgan -> OrganDionaStomach ;
BaseOrganLungs -> OrganDionaLungs ;
BaseDionaOrgan -> OrganDionaLungs ;
OrganDionaBrain -> OrganDionaBrainNymph ;
OrganDionaStomach -> OrganDionaStomachNymph ;
OrganDionaLungs -> OrganDionaLungsNymph ;
MobDionaNymph -> OrganDionaNymphBrain ;
MobDionaNymphAccent -> OrganDionaNymphStomach ;
MobDionaNymphAccent -> OrganDionaNymphLungs ;
OrganHumanHeart -> OrganDwarfHeart ;
OrganHumanLiver -> OrganDwarfLiver ;
OrganHumanStomach -> OrganDwarfStomach ;
BaseOrganBrain -> OrganHumanBrain ;
BaseHumanOrgan -> OrganHumanBrain ;
BaseOrganEyes -> OrganHumanEyes ;
BaseHumanOrgan -> OrganHumanEyes ;
BaseOrganTongue -> OrganHumanTongue ;
BaseHumanOrgan -> OrganHumanTongue ;
BaseOrganAppendix -> OrganHumanAppendix ;
BaseHumanOrgan -> OrganHumanAppendix ;
BaseOrganEars -> OrganHumanEars ;
BaseHumanOrgan -> OrganHumanEars ;
BaseOrganLungs -> OrganHumanLungs ;
BaseHumanOrgan -> OrganHumanLungs ;
BaseOrganHeart -> OrganHumanHeart ;
BaseHumanOrgan -> OrganHumanHeart ;
BaseOrganStomach -> OrganHumanStomach ;
BaseHumanOrgan -> OrganHumanStomach ;
BaseOrganLiver -> OrganHumanLiver ;
BaseHumanOrgan -> OrganHumanLiver ;
BaseOrganKidneys -> OrganHumanKidneys ;
BaseHumanOrgan -> OrganHumanKidneys ;
BaseOrganStomach -> OrganMothStomach ;
OrganAnimalLungs -> OrganRatLungs ;
OrganAnimalStomach -> OrganRatStomach ;
OrganAnimalStomach -> OrganReptilianStomach ;
BaseSlimeOrgan -> SentientSlimeCore ;
BaseOrganStomach -> SentientSlimeCore ;
BaseOrganBrain -> SentientSlimeCore ;
BaseSlimeOrgan -> OrganSlimeLungs ;
BaseOrganLungs -> OrganSlimeLungs ;
OrganHumanLungs -> OrganVoxLungs ;
}
```

</details>

out

### CODE REVIEW

**Comment by 0x6273** [comment]
Test fail looks real

**Comment by lzk228** [comment]
test godt got angry at me

**Comment by IProduceWidgets** [comment]
I gotta say, 5 layers or parenting hell seems like we're doing something wrong and should reevaluate whether we would rather just use more txt but not have this many reference abstractions.

**Comment by lzk228** [comment]
fixed tests and update pr info

**Comment by lzk228** [comment]
curse RT

**Comment by lzk228** [comment]
OH LORD HELP ME TO DEFEAT THIS RT
i'll better reopen it

**Pull request closed without merging**
