### PR TITLE
add Fresium, a chillingly complex chemical to prank your friends with

### PR DESCRIPTION
**Pull request by CrigCrag**
# Notice: I do not endorse pranking your friends with this chemical 
## About the PR

This PR adds Fresium. Fresium is a somewhat complex coolant that does a lot of things. The list is as follows:

- It is slippery, like ice.
- If you spill it on the ground, it will freeze the ground wherever it spills and also slip you.
- It's cold enough to fight fires.
- It cools down anyone who gets it on their skin.
- It reacts somewhat harshly with water, instantly freezing it into ice and releasing Frezon into the atmosphere.
- If ingested, it will slow you down significantly for a while, even after the chemical is done metabolizing.
- While metabolizing, it makes you very cold (capped at 160.15K, or -113C)
- Leporazine will purge it from your bloodstream rapidly
- Anyone who has more than 40 units in their bloodstream will notice that their legs have suddenly ceased function. This is a buff to wheelchair bound crewmates (I didn't forget about you o7) Your legs will not work until the chemical drops below 40 units once again. In testing you can use this in foam grenades to immobilize groups of people if they don't escape fast enough.

### Fresium has a very complex reaction
The reaction works as follows:
3 units Frezon (uses the newly added gas condenser to make this a reagent)
1 unit Plasma (as a catalyst)
2 units Nitrogen (per 3 units Frezon)
0.22 units Cryoxadone (per 3 units Frezon)
0.08 units Table Salt (per 3 units Frezon)
1.5 units Water (per 3 units Frezon)

In this reaction, the Nitrogen is released into the air as gas.
Either table salt or water must be added last, or else Saline will be made before the reaction can happen.

Now, you may be thinking:
## What the scallop? This reaction is COMPLICATED! nobody would EVER make this. explode this guy NOW!
The reaction produces 5 units of Fresium for your troubles, and less if you mess it up. However, assuming you don't dump a ton of water into the mix, you should always get Fresium out of the reaction. The main danger of this reaction is managing leftover water. If there is too much excess water (more than 0.99u) it will react with the newly produced Fresium to produce Frezon gas. The amount of Fresium you get in the end depends on how well you manage the excess water. 

I've fiddled around with the reaction in the chemmaster a good bit and I think it's kind of fun to calculate the exact numbers of reagent that should be added at once to make the reaction clean, but that might just be me.

So, you made Fresium, what will ya do with it?
You could:
- make a skating rink, slip the HoS on it, and get thrown in perma
- put it in chem grenades and immobilize the entire station so that only those with wheelchairs may move 
- freeze the clown into a statue for drinking all your meds
- dump a bunch of water in the beaker and release frezon in the bathroom/
- you could probably use it to speed up how fast someone cools down in a cryopod
## Why / Balance

More fun chemicals are fun. The gas condenser deserves something fun to go along with it and we need more complex and quirky chemical reactions in preparation for the chem rework. Precise reactions like this one and the bruizine one will reward chemists who do the math right as they will waste less of their chemicals. Additionally, it's just something new for chemists to play around with and inevitably mess up, causing a bit of havoc. 
## Technical details

it uses like the reagent code and the locale code and the yaml to add a new reagent.
## To Do:
- [X] Test the code more
- [X] Tweak and balance it a bit
- [ ] Make sure the tests don't fail because they definitely will
- [X] Add it to maints pills
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
https://youtu.be/hsKZGQWTzJg
https://youtu.be/MSkBnk34eJU
**Changelog**

:cl:
- add: Added Fresium, a military grade coolant that you SHOULD NOT INGEST OR SPLASH ON YOUR FRIENDS!

### CODE REVIEW

**Comment by mirrorcult** [comment]
i feel like this could just be properties of frezon itself but this is interesting enough that im fine with it tbh

**Comment by CrigCrag** [comment]
> i feel like this could just be properties of frezon itself but this is interesting enough that im fine with it tbh

it would stop frezon from being a recreational drug anyways (reagent effects are shared between gas and reagent i think) which would spark the biggest atmos riots ever seen

**Comment by UbaserB** [comment]
i love this so much

**Comment by CrigCrag** [comment]
i do not have the slightest clue why the linux test is exploding maybe they need to download open source headphones or something.

test fails seem erroneous but i might just be stupid, this should be ready for review

**Comment by TurboTrackerss14** [comment]
Might be a good idea to ensure this doesn't break thermodynamics/cargo economy by making more frezon than it takes to make. 
Spilling water onto (number) units of this, siphoning said frezon and selling it yada yada

**Comment by CrigCrag** [comment]
now takes 3 frezon to make 5 fresium, if you do it as efficiently as possible and harvest and recycle all the frezon produced from turning your 5 fresium back into frezon (you get 15 mol) you can recycle it into 2.8 frezon, so it is now at a loss.

**Comment by CrigCrag** [comment]
merge conflicts fix this is good to go i think

**Comment by Kadeo64** [comment]
>put it in chem grenades and immobilize the entire station so that only those with wheelchairs may move 

yet another win for the mechtide....

**Comment by CrigCrag** [comment]
next up is fresium+ which just freezes your game

**Comment by Emisse** [comment]
fuck it we ball

**Pull request merged**
