### PR TITLE
RND server boards

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Makes the R&D server constructible and adds a board.
The board isn't obtainable besides just deconstructing the roundstart server
Please don't change that willy-nilly.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The R&D server can be deconstructed. Be warned: this resets all unlocked technology, points, and the current discipline.

### CODE REVIEW

**Comment by deltanedas** [comment]
so in other words we can now reroll trees so 1. get a telepad 2. get a few bags of holding 3. get cloner 4. uhhhh whats industrial

**Comment by EmoGarbage404** [comment]
> so in other words we can now reroll trees so 1. get a telepad 2. get a few bags of holding 3. get cloner 4. uhhhh whats industrial

yes. The balancing factors of this specific change are:
- you cannot have them simultaneously
- you have to research each from the beginning
- you discard any points you had on the server

I think this is more than fair, especially if there's a situation where Sci might need to unexpectedly pivot to another discipline.

**Comment by VektorZ1** [comment]
This change is good, but it permanently kills the discs. After the change, they cannot be used for research because of the duplicates. Getting t3 with them will just become a pointless roulette, too expensive to spin with the long and costly but reliable method of resetting the server.

**Comment by EmoGarbage404** [comment]
> This change is good, but it permanently kills the discs. After the change, they cannot be used for research because of the duplicates. Getting t3 with them will just become a pointless roulette, too expensive to spin with the long and costly but reliable method of resetting the server.

a few benefits to consider about using disks over resetting:
- you don't have to re-unlock t1/t2 technologies (which would probably be more expensive than the printing)
- disks can be acquired without having to get permission from the RD to reset the server.

I think that having these as options is fairly balanced.

**Pull request merged**
