### PR TITLE
Buffing the reflect rate of the captains sabre to 35% from 10%

### PR DESCRIPTION
**Pull request by LentilMan**
## About the PR

I have buffed the reflect percentage on the Captain's Sabre to 35%
## Why / Balance

Not that long ago, the reflect rate of the Captain's Sabre was nerfed to 10% from 50%, The sword did need a nerf as 50% was too much. However 10% is way too much of a nerf, keep in mind the captains Sabre is a one-of-a-kind sword that is only used by one person on the station. It does not seem right that the Sabre should have been nerfed so badly. Thats why I chose to buff it to 35%, to allow it some purpose in combat besides just straight melee combat. 
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Tweak- Buffed reflect rate of Captain's Sabre to 35%

### CODE REVIEW

**Comment by LentilMan** [comment]
Note: may need discussion

**Comment by Golinth** [comment]
I do think that it should be something better than an e-sword, as it is unique. Maybe make it an objective too.

**Comment by MerrytheManokit** [comment]
Honestly a valid change as in its current state its almost outcompeted by the e-dagger

**Comment by deepdarkdepths** [comment]
Just wait for the scaling based on movement speed instead of going back and forth on the percentage

**Comment by MerrytheManokit** [comment]
> Just wait for the scaling based on movement speed instead of going back and forth on the percentage
I feel like it needs this just so its not in a pathetic state for the week or two before the update releases

**Comment by MerrytheManokit** [comment]
> Just wait for the scaling based on movement speed instead of going back and forth on the percentage
I feel like it needs this just so its not in a pathetic state for the week or two before the update releases

**Comment by metalgearsloth** [comment]
I think we have better things to be focussing than balancing minutia for this, just let it sit for a bit.

**Comment by SteroidsOnSteroids** [comment]
so you're telling me that nerfing captain's saber to 10% was so important that it overrode other stuff but this, this un-nerf, isnt important?

kinda ridiculous

**Comment by metalgearsloth** [comment]
> so you're telling me that nerfing captain's saber to 10% was so important that it overrode other stuff but this, this un-nerf, isnt important?
> 
> kinda ridiculous

Offer something of value or don't offer anything at all please. The change has been in less than a day.

**Comment by LentilMan** [comment]
Yes but the captains sabre has a worse reflect rate then any other sword in the game now

**Comment by LentilMan** [comment]
The sword needed a nerf but 10% is way too much

> Yes but the captains sabre has a worse reflect rate then any other sword in the game now

**Comment by LentilMan** [comment]
The sword needed a nerf but 10% is way too much, as the sword barely provides any protection anymore

**Comment by LentilMan** [comment]
> I think we have better things to be focussing than balancing minutia for this, just let it sit for a bit.
I feel like the buff is needed

**Comment by Ilya246** [comment]
> > so you're telling me that nerfing captain's saber to 10% was so important that it overrode other stuff but this, this un-nerf, isnt important?
> > kinda ridiculous
> 
> Offer something of value or don't offer anything at all please. The change has been in less than a day.

i'm pretty sure a large amount of people have said that 10% was too low in both this and the previous discussions with next to no disagreement (and i agree, though i'd actually suggest 25% 30% instead), those should count as being of value
no reason to not just merge this and test this instead since this seems like a better figure for the reflection chance: try 35% right away vs try 10%, see it fail, then after a long time try 35% if anyone can be bothered to fix it

**Comment by Barrett-S** [comment]
I think this oughta be re-opened....

**Pull request closed without merging**
