### PR TITLE
Adds "Paramedic" to ID card computers and IDs

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Medical now has a "Paramedic" subclass. Paramedic lockers and doors now have proper access. This also addresses issue #22345.

## Why / Balance

Fixes a permission issue on aspid, keeps normal medical doctors from digging through a paramed's stuff, allows for parameds to have locked doors. Future PR may include said doors, and possibly some gear.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Didn't we remove their unique access?

**Comment by Aexxie** [comment]
> Didn't we remove their unique access?

I don't think they ever had unique access, but I might be wrong. The other day we removed externals, if thats what you mean

**Comment by LankLTE** [comment]
Paramedics previously had their own access that was half-implemented. A PR attempted to add it fully but following discussion we opted to remove it fully instead.

**Comment by Aexxie** [comment]
> Paramedics previously had their own access that was half-implemented. A PR attempted to add it fully but following discussion we opted to remove it fully instead.

Unfortunate, I couldn't find any other pr mentioning it so I went with this solution. I didn't really think about removing the door until a good while into making this. I'll do that then I suppose

**Pull request closed without merging**
