### PR TITLE
Allow pAI to serve as a borg brain.

### PR DESCRIPTION
**Pull request by tday93**
## About the PR

Allows pAI's to serve as borg brains, by first jamming them into an MMI

## Why / Balance

Makes an existing technique of coordinated ghosting and positronic brain activation less clunky. 

The pAI can now be inserted into an MMI, and from there into a cyborg.

## Technical details

Added PAIs to the MMI's slot whitelist, and updated appearance code and sprites to show that its a pAI in there.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: tday
- add: Activated Personal AIs may now be inserted into Man-Machine Interfaces.

### CODE REVIEW

**Comment by lzk228** [comment]
pai should be pai.

**Comment by Hmeister-fake** [comment]
This shouldnt be something that a PaI can naturally do, there should be a PaI Module of some kind that can have a PaI put into it that is just as expensive than a Borg Brain.

**Comment by Hmeister-fake** [comment]
Otherwise Borg Brains will be never used since you can just use a PaI for free

**Comment by tday93** [comment]
> This shouldnt be something that a PaI can naturally do, there should be a PaI Module of some kind that can have a PaI put into it that is just as expensive than a Borg Brain.

Yeah was thinking about this. Wasn't sure if it was balanced by not being able to craft pAIs, the cost being finding one. 

Does almost certainly need some additional cost however.

**Comment by tday93** [comment]
Updated to require the pAI to first be inserted in to an MMI.

I feel this should capture much more of the materials cost for creating borgs, while still giving a bit of trade with regards to positronic brains. Also the idea of clumsily jamming one into an MMI made me laugh.

**Comment by nikthechampiongr** [comment]
Won't this render positronic brains useless?

**Comment by tday93** [comment]
> Won't this render positronic brains useless?

I don't think so? As they can be directly constructed - as far as I'm aware personal AIs cannot.

**Comment by metalgearsloth** [comment]
I don't think PAIs should be powercrept into crewmembers and should just remain a funny ghost role, if people want to be borgs they just use the MMI or take it roundstart.

**Comment by K-Dynamic** [comment]
I dunno, pAI borgs would be more content and a way to reintroduce players back into round (ghost roles are lacking) - is that a problem in of itself?

Also players keep asking roboticists to upgrade pAIs but sadly their roleplay is turned down

**Comment by Carmell0** [comment]
What about a PaI robot sci can either research or make?

**Pull request closed without merging**
