### PR TITLE
escape + kill objective changes

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- kill objectives now count you as dead if you don't escape on the emergency shuttle.
- this prevent a kill target youve never heard of going afk in space/maints/locker never to be seen again and conveniently leaving coords off so youll never be able to track them down short of nuking the station. made it less difficult so you might possibly be tasked with killing more people as you don't actually have to kill everyone, you could iron foam evac or something and prevent your target(s) from escaping if you are a pussy
- also means you arent incentivised as crew to always use pods when there isnt any danger just to meta avoid bombings/fishops/funnies

**Media**
cant test kill because rmobjective is being idiot, i did test head assassination and the marooning, 50% things work tho

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Going afk and missing evac now counts as being killed for the kill objective.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
in 13 shuttle escape is always shuttle escape so anyone wanted by sec still has a chance of getting caught, pod is mainly RP reasons.

**Comment by deltanedas** [comment]
evac always gets bombed by noobs so escaping there is a challenge even if sec doesnt notice you
if you really want can make pods not count

**Comment by metalgearsloth** [comment]
See what another maintlord thinks

**Comment by Emisse** [comment]
pods shouldnt count

**Comment by deltanedas** [comment]
pod no longer count :trollface:

**Comment by DogZeroX** [comment]
Reminds me that pod should take you to that small terminal thing instead of centcom

**Comment by Aisu9** [comment]
so escaping via emergency pod is metagaming but bombing the evacuation shuttle isn't?
i feel like this change is only to provide sweaty gamers that hardcore farm 3/3 green text

**Comment by Aisu9** [comment]
i get it that antag have leeway to kill their targets blablabla, but they shouldn't turn the emergency shuttle into a flying morgue or Swiss cheese for the sake of 'feeling their objectives"

**Comment by Aisu9** [comment]
people afk-in lockers? make every lockers airtight (some are already airtight like the botany one, THIS will prevent locker afk)
people in space? buy a syndicate eva and cobra and fill 'em with lead
in maintenance? it's not that big just search them, we all have eyes and syndicates have weapons on top of that.
If crewmembers are not incentivised to use emergency pods, then why they are in to begin with just remove them.

**Comment by Mudsson** [comment]
Maybe renaming the objective to "prevent from escaping alive" or "prevent from escaping alive on the Evac shuttle" to communicate this more clearly.

**Comment by deltanedas** [comment]
> buy a syndicate eva and cobra and fill 'em with lead

its easy if you know that your target is afk at 3953, 202

now try to find them without this information

**Comment by Aisu9** [comment]
> 

what about the tank lifetime "recent" nerf? you must refill every 15 or so minutes, they'll die eventually. but again why making traitor objectives easier to accomplish? they already have the upper hand in every situation thanks to their uplink. is this really cause for concern and changes for "metagaming" sake? when shuttle bombing is one of the "allowed" metagaming cases only traitor can employ

**Comment by deltanedas** [comment]
now the target is afk in a 3x3 box with an open oxygen canister that will essentially last forever, never to be seen again

**Comment by Aisu9** [comment]
will this scenario ever happen? or even happen in the last 3 years? (because now it might happen thanks to you)
then again, instead or punishing every players, just implement a tag if SSD=dead for objectives

**Comment by deltanedas** [comment]
i have seen it many times where the kill target has hopped into the 6th dimension never to be seen again and theres a failed objective as a result

if ssd=dead is ok, why are you intentionally missing evac when not afk

**Comment by Aisu9** [comment]
every times i missed evac it is because i completely forgot about the shuttle to be honest (but i could also see people trying to escape their syndicate killer while the shuttle is waiting, or just can't progress because they don't have tools to open un-powered doors and no one answer and try to help them)

**Comment by Aisu9** [comment]
but you should also know by now that if people doesn't jump on the shuttle of their own volition, it's maybe they don't want to live the 3 insufferable minutes of intense shuttle griefing

**Comment by Aisu9** [comment]
with the recent addition of starvation and nerf of breathing tank capacity, is there any incentive in removing the journalist mode difficulty on kill objectives? (i wanna emphasise the changes that has been made to make syndicate win their greentext instead of small changes here and there to improve overall roleplay (like forcing players to pay a visit to chef or returning on station to refill air reserves)

**Pull request merged**
