### PR TITLE
Tweaks PDA flashlight slightly

### LINKED ISSUE #4881: PDAs have barely any light
## Description

Presumably they got nerfed in the recent lighting tweaks. And yes, the flashlight is actually on.

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Closes #4881.

Slight tweak since it was definitely too dark. 

**Screenshots**

Befo'
Content Client_2021-11-06_15-24-01

Afta'
Content Client_2021-11-06_15-23-37

**Changelog**

:cl: Swept
- tweak: PDA flashlights are brighter now

### CODE REVIEW

**Comment by mirrorcult** [comment]
lame

**Comment by AJCM-git** [comment]
I think it's fine, it is currently way too dim and 2 tiles is fine, and the flashlight is still a viable option

**Comment by mirrorcult** [comment]
ehhhhhh ok im fine with it

**Comment by SweptWasTaken** [comment]
> 
> 
> lame

We will have spooky station one day, I promise.

**Pull request merged**
