### PR TITLE
Added a chainsaw weapon. New sprite & sounds.

### PR DESCRIPTION
**Pull request by Jessetriesagain**
## About the PR
Added a chainsaw melee weapon with a new sprite and attack sound. Vroom.

**Media**
- [x ] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl: Jesse
- add: Chainsaw Weapon Sprite
- add: Chainsaw Attack sound
- add: Chainsaw Weapon statistics

https://github.com/space-wizards/space-station-14/assets/138042477/1c8d3cdc-5ad9-4fad-9d84-07a39f041da1

### CODE REVIEW

**Comment by spectralSpices** [comment]
Sounds great, but the sprites are a bit...weird? Also, I feel like it should require two hands to use.

**Comment by asperger-sind** [comment]
1. Couldn't this use SS13 sprites? I know they have a chainsaw and I think even wield sprites for it.
2. The changelog should be more player-facing e.g "added a new weapon: the chainsaw! it does xyz with xyz stats and is obtainable via xyz method"

**Comment by FacePluslll** [comment]
this should 100% be a two-handed weapon, also I think there needs to be some kind of idle sound for the chainsaw when it's held to really sell the chainsaw vibe

**Comment by Jessetriesagain** [comment]
> this should 100% be a two-handed weapon, also I think there needs to be some kind of idle sound for the chainsaw when it's held to really sell the chainsaw vibe

I'll do that - will honestly make the wielding sprite less awkward to make too. Thanks for the feedback all!

**Pull request closed without merging**
