### PR TITLE
Disable SSD indicators on LRP

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

Disables SSD indicators on LRP, leaving them enabled on MRP. This does not affect examine text.

## Why / Balance

LRP rules don't make a distinction between SSD and non-SSD players. Players frequently attempt to justify actions by saying that the victim was SSD. Highlighting who is SSD may lead to an increase in this behavior as players may reasonably assume that the game wouldn't be telling them someone is SSD if it wasn't relevant.

Retains the indicators on MRP since MRP rules do make a distinction for SSD players.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
image
I do believe that is misinformation, im gonna check the rules

**Comment by deltanedas** [comment]
way too often people on lrp steal from ssd people and even fucking crit people so removing it is good

**Comment by lzk228** [comment]
mrp when?

**Comment by LankLTE** [comment]
Can’t they just shift click someone to see if they’re SSD? It seems weird to say the indicator will be abused when it’s basically QoL to save you from inspecting them if that’s the case.

**Comment by asperger-sind** [comment]
This is an anti-feature. This PR intends to remove QoL for identifying SSD people, which is possible without the QoL but takes slightly more time as you have to shift+click or inspect them via content menu.

**Comment by Aisu9** [comment]
mind that should not prevent turning off/on suit helmet and internal

**Comment by NancokPS2** [comment]
If there's no distinction beween SSD and non-SSD, then stealing from them is not a problem, and removing a QoL to address a non-issue makes no sense.  
If there is, then the rules are already in place to prevent it.

**Comment by NancokPS2** [comment]
> 

Then there it is, it is already against the rules to mess with SSD people.  
And this actually helps people know that someone is SSD and therefore not eligible to strip.

**Comment by deltanedas** [comment]
> And this actually helps people know that someone is SSD and therefore not eligible to strip.

if you are already stripping a specific person examining will make it clear anyway

if you are just looking for people to loot as a shitter, an icon next to their heads is not good and will just create admin overhead

**Comment by asperger-sind** [comment]
> if you are just looking for people to loot as a shitter, an icon next to their heads is not good and will just create admin overhead

If you're looking for SSDs to loot you are dedicated enough to shift+click or examine everyone in sight and probably can guess at a glance if someone is SSD or not and then examine, it's really a non-issue to look for SSDs if you're trying to, removing a QoL feature will of course make it easier, but it's going to be insignificant if anything.

unrelated to reply but i want to say that its dumb to remove a genuinely useful feature because it can theoretically be mildly abused by bad actors

**Comment by NancokPS2** [comment]
> This is about stopping the people who are walking around and happen to see someone SSD, and about removing the "why is the game broadcasting the info if it doesn't matter" excuse. It's not about stopping people dedicated to finding an SSD person to loot, attack, or whatever. Very few people seem to go out of their way to find someone SSD to mess with, they just happen to see them, and that'll happen a lot more if you highlight every SSD person.

That sounds like the problem is that the rule isn't being enforced, rather than the feature facilitating it.  
It is like saying "We can't let people get access to a screwdriver because they can tear apart APCs" or that you can't let people break lights because they'll abuse it.  
  
And they aren't allowed to in the first place because it is self antag.  
It can be abused just as easily and causes even more issues, yet there's no issue with it. But people showing they are SSD is somehow a problem?  
  
Stripping is self antag regardless of SSD status, removing this because it makes it easier to find targets is a pretty weak reason and inconsistent with other design choices.

**Pull request merged**
