### PR TITLE
Replaces all old maint hatches with the yellow airlock.

### PR DESCRIPTION
**Pull request by SweptWasTaken**
Looks better imo. If this gets merged i'll probably make a pr removing the old hatches.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
image

**Comment by moonheart08** [comment]
i like the old airlocks more, tbh

**Comment by PJB3005** [comment]
At the very least give them a unique lick of paint and preferably even department-specific paint.

**Comment by SweptWasTaken** [comment]
> 
> 
> At the very least give them a unique lick of paint and preferably even department-specific paint.

Will do.

**Comment by SweptWasTaken** [comment]
Nuking because I fucked the local branch hard

**Pull request closed without merging**
