### PR TITLE
Security Melee Weapon, the Truncheon

### PR DESCRIPTION
**Pull request by HerCoyote23**
## About the PR

Adds a new weapon to security's arsenal-- the Truncheon.
Currently, security doesn't actually have any proper melee weapons other than the baton. There is no lethal melee option(there's the knife, but that's a desperation weapon). It's pretty common for security officers to craft a bat or spear when they need a proper melee weapon. This is not very thematically fitting, they should have proper weapons instead of cobbled together creations. Also gives more variety to sec, giving them a melee option if they so choose.

The truncheon does 17 Blunt, and has the same disarm malus as the stun baton. Similar to how sec's lasers are a step down from cap's laser, it's a step down from cap's sabre(which does lots of bleed and attacks faster).

It's not meant to be carried at all times like a stunbaton, but rather distributed in an emergency, similar to lasers. As such, it's printable from the secfab for 300 plastic and 300 metal, and I mapped a few into the armory on every station(At least I think I did, I'm still figuring out mapping.).

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Following a recent increase in Behonker activity, Nanotrasen has equipped its security teams with a more harmful alternative to the stun baton.

### CODE REVIEW

**Comment by Cheackraze** [comment]
I dont think sec needs more weapons, this is just going to encourage them to kill instead of arrest.

**Comment by Aisu9** [comment]
i thought is was a big no to give sec lethal
Not meant to be carried around? then why it's 30? and not 90/back slot only?

**Comment by Aisu9** [comment]
if anything they can use their baton turned off if they need lethal, just go with the buddy system

**Comment by HerCoyote23** [comment]
Harmbaton deals 7 blunt. This isn't for sec to have lethals on hand, but rather have a decent melee lethal option. At the moment, Sec's best lethal melee option is the knife, which deals 10 slash. No mucho.

**Comment by Aisu9** [comment]
Security might be the only department that doesn't need more content for the foreseeable future.
Knife deal 10 slash sure.... but it also increase bleeding rate by 2 with each swing AND the knife attack 1.5 times per seconds, meaning they have 15 dps and this is without accounting bleeding

**Comment by Cheackraze** [comment]
If this is meant to be kept in the armory then that's where it will live forever since compared to literally any gun it is worthless.  Sec doesn't need a codified harm baton, they have plenty of lethal weaponry

**Comment by HerCoyote23** [comment]
Huh, that's better than I thought. If the knife's good, then this would be variety. An alternative, with blunt damage instead.

Guns are pretty much across the board better than (non-esword) melee. I've still seen secoffs using spears/bats though.

**Comment by AjexRose** [comment]
New Tier 3 Arsenal Tech?

**Comment by Emisse** [comment]
yea lock this behind sec research

**Comment by HerCoyote23** [comment]
I added it as a T2 8k point research called Advanced Riot Control, and increased the damage to 18, since as a highish tech weapon it should probably be better than the knife.
In the future, I'd like to add the telescopic riot shield to Advanced Riot Control, if/once it gets added.

**Review by EmoGarbage404 — APPROVED** [review]
lgtm

**Pull request merged**
