### PR TITLE
Makes the orb roll

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About the PR

The orb is a sphere, it now rolls.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The orb rolls.

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
Google says the coefficient for rolling friction is usually 1/100-1/1000 the coefficient for sliding friction.

**Comment by AJCM-git** [comment]
wheres the video of it rolling, i demand it

**Comment by TemporalOroboros** [comment]
Provided at some point not dead of night o clock.

**Comment by TemporalOroboros** [comment]
> wheres the video of it rolling, i demand it


https://github.com/space-wizards/space-station-14/assets/53582584/7493f4f1-3d16-4738-b7c5-03d5c08c0dee

**Comment by TemporalOroboros** [comment]
Test failure appears to be something to do with telecomms wiring.

**Comment by AJCM-git** [comment]
test failure is a false flag

**Comment by ChilbroBaggins** [comment]
Bowling when

> > wheres the video of it rolling, i demand it
> 
> Space.Station.14.2023-05-14.22-10-20.online-video-cutter.com.mp4

OK, now do it with 10 beer bottles standing in a triangle shape at the end of a long hallway...

**Pull request merged**
