### PR TITLE
Add plastic sheets chemical recipe

### PR DESCRIPTION
**Pull request by mhamsterr**
New ways of getting old materials are cool (and will be much cooler if we will have limited amount of chems at the roundstart)

## About the PR

+ Added plastic recipe. You can now make your very own plastic sheets by mixing together 5 parts oil, 3 parts ash and 2 parts sulfuric acid and then heating it up to 374k (10u of 'mixture' = 1  plastic sheet).

**Media**

https://github.com/space-wizards/space-station-14/assets/81412348/400171dc-fa56-4c8e-88d4-932d7c5358d7

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: mhamster
- add: Added plastic sheets recipe. Mix together 5u oil, 3u ash and 2u sulfuric acid, heat it up to 374k and receive your homemade plastic sheet.

### CODE REVIEW

**Comment by 0x6273** [comment]
Why would oil turn into ash when heated? None of these recipes make sense.

**Comment by deltanedas** [comment]
it should probably explode rather than turn to ash
isnt there a thing for burning paper to get ash

**Comment by mhamsterr** [comment]
> Why would oil turn into ash when heated? None of these recipes make sense.

Because of tg ss13: https://tgstation13.org/wiki/Guide_to_chemistry#Ash

Actually, i found more interesting solution on [paradisestation wiki](https://paradisestation.org/wiki/index.php?title=Guide_to_Chemistry#Ash), but i'm not sure if this can be done without any c# changes:
> You can also create it (ash) by heating up Oil to 874K, but if it's 30u of oil or more, this WILL result in a large fire, which if done in chemistry will likely blow the welding tanks and ignite everyone nearby. Burning paper and scooping it up is a much safer method of making ash.

**Comment by mhamsterr** [comment]
> isnt there a thing for burning paper to get ash

i think there isn't yet?

**Comment by deltanedas** [comment]
#10373 is a derelict that could be revived with reviews addressed

**Comment by mhamsterr** [comment]
Ash chemical recipe is purged from this pr and moved to #18955

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
