### PR TITLE
Increase all welding times 5x in wall deconstruction

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Closes https://github.com/space-wizards/space-station-14/issues/7065

**Changelog**

:cl: Rane
- tweak: All welder steps in wall deconstruction now take 5 times as long.

### CODE REVIEW

**Comment by HoofedEar** [comment]
Does this buff wall construction though? Did we already make wall construction take time instead of being instant? We need both!

**Comment by Elijahrane** [comment]
wyci

**Comment by TimrodDX** [comment]
5x is way too much.

**Comment by Elijahrane** [comment]
> 5x is way too much.

It's still way faster than hacking

**Comment by ElectroJr** [comment]
> Does this buff wall construction though? 

> wyci

Given that its literally part of the same construction graph, you might as well add a 2 second do after to wall construction in this PR

**Comment by Elijahrane** [comment]
> > Does this buff wall construction though?
> 
> > wyci
> 
> Given that its literally part of the same construction graph, you might as well add a 2 second do after to wall construction in this PR

okay

**Review by ElectroJr — APPROVED** [review]

**Pull request merged**
