### PR TITLE
ninja role restrictions

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
add some restrictions to ninja ghost role

depends on #20108

## Why / Balance
dont want random noobs who have 5m in the game sniping it when pros have been waiting 40m for it :trollface:

intended to be a little less than nukies (current 4x :trollface:)

## Technical details
no

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by LankLTE** [comment]
Gonna be honest I don’t like adding random unrelated role restrictions to Antags (how is engi even remotely relevant)

**Comment by deltanedas** [comment]
- full bag of tools in your bag so you should know how to use them
- knowing how emagging works since dealing with emags is common in engi
- knowing what apc/sub/smes are so having an intuition for what is better to drain from

**Comment by deltanedas** [comment]
also this and many other ghost roles would probably benefit from dialog + lottery instead of ping sniping

**Comment by LankLTE** [comment]
> also this and many other ghost roles would probably benefit from dialog + lottery instead of ping sniping

Yeah but that's just a matter of when someone codes it. "Passenger mains" sniping ninjas isn't really an issue

**Comment by Nairodian** [comment]
> also this and many other ghost roles would probably benefit from dialog + lottery instead of ping sniping

#10206 Someone _could_ pick this PR back up.

**Comment by NancokPS2** [comment]
> * full bag of tools in your bag so you should know how to use them
> 
>     * knowing how emagging works since dealing with emags is common in engi
> 
>     * knowing what apc/sub/smes are so having an intuition for what is better to drain from
> 
> 
> basically its not that a ninja needs to be an engi main, its just that a ninja that has never touched engineering would do poorly


Knowing how to fix an emag is completely irrelevant to the usage of one. You must know how to use it, not how to fix it (and a non antag engineer has no reason to know how they are used either). Which is painfully simple.  
  
Ninja can also teleport and emag near limitlessly. They don't even need to know how to hack or pry open doors to be effective.  
  
Knowing about power is useful, but not necessary. And with 20 hours you WILL know how it works well enough to tell what to destroy to disrupt it.

**Comment by deltanedas** [comment]
already removed the department requirements pro

**Comment by Froozigiusz** [comment]
This ghost restriction thing could be used to re–enable maintenance drones! They can get massive nerfs but please, I just want the small bots to run around

**Comment by deltanedas** [comment]
merg...

**Comment by GeorgeGimme** [comment]
new players deserve to have fun too i get that longer time players want the ninja role but taking away too many parts of the game from newer players will discourage them from continueing to play

**Comment by deltanedas** [comment]
yes we should remove command timers clearly, back to first game caps

**Comment by GeorgeGimme** [comment]
i think less tryhard/experienced caps would make for more unique rounds
i want to see clown get AA more

**Comment by GeorgeGimme** [comment]
but i was talkign about ghost roles because new players would be bored as hell when they die if they are not allowed any ghost roles

**Comment by GeorgeGimme** [comment]
a better solution to waiting for ghost roles would be adding more ghost roles so that dead players have stuff to do

**Comment by deltanedas** [comment]
merg

**Comment by deltanedas** [comment]
@LankLTE pro

**Comment by LankLTE** [comment]
New players taking ghost roles isn't a problem- restricting this is unnecessary. "Random noobs sniping ghost roles from pros who have been waiting 40m" is just saying "New players are playing the game," a system like ghost role polling should be implemented to fix the "sniping antags" issue.

**Pull request closed without merging**
