### PR TITLE
Add a cooldown for a door deny sounds and visuals

### PR DESCRIPTION
**Pull request by koteq**
## About the PR

Add a small cooldown for the access denied sound and visuals.
~~Add denied access attempts to the log probe PDA cartridge.~~

## Why / Balance

In my opinion, players are heavily abusing the access denied sound as an annoying doorbell when they want to enter somewhere. ~~The introduced cooldown should push players into more IC way of _asking_ for access to the areas they aren't allowed to.~~

It should also help to address an issue when you may not be able to open a door even when you have the right access, just because someone locks the door into a constant cycle of deny animation by rapidly clicking it.

## Technical details

Add denied access logging into the access reader system, plus subscribed it to the `BeforeDoorDeniedEvent`, cancelling the event if the user had been denied from accessing the door recently.

## Media

https://github.com/space-wizards/space-station-14/assets/1192090/f4d10fea-0257-4f74-a9f8-cdec96965c1f

Plus slightly rearranged the log probe PDA UI to make it look like a table:

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a small cooldown for denied door/airlock access attempts.

### CODE REVIEW

**Comment by Kadeo64** [comment]
30 seconds seems like a lot of time, maybe 10-15 seconds would be better?

**Comment by SpeltIncorrectyl** [comment]
30 seconds is way way to long.

**Comment by MACMAN2003** [comment]
30 seconds is a very long time, i feel like 1-2 seconds is long enough

**Comment by keronshb** [comment]
This is intentional and should not have a delay. It's easy for people to miss or outright ignore chat, where it's harder to ignore the door buzzing.

**Comment by koteq** [comment]
Guys, I can be any number, and I'd prefer a maintainer to pick the value, well, if the PR would get accepted, ofc.

From my experience playing the game, I never had a situation where I'd need to bump into an airlock twice in a row. Usually, I am mostly aware of what access I have, only bumping into something like botany or kitchen airlock just because it looks like a general access one.

**Comment by Kadeo64** [comment]
> This is intentional and should not have a delay. It's easy for people to miss or outright ignore chat, where it's harder to ignore the door buzzing.

I think that a short delay prevents it from being too annoying. 3-5 seconds since it's an intentional feature.

**Comment by GreyMario** [comment]
If you're going to claim that the current state of obnoxious access denied alarms is acceptable, then I'm going to reserve the right to crit anyone abusing it instead of using things like the department intercom or desk bell.

**Comment by Kadeo64** [comment]
> If you're going to claim that the current state of obnoxious access denied alarms is acceptable, then I'm going to reserve the right to crit anyone abusing it instead of using things like the department intercom or desk bell.

marathon
image
core
image

do you see a desk bell/intercom here

**Comment by keronshb** [comment]
The logging is also intrusive on fingerprint scanning. Instead of needing security or someone to come scan the door to see who used it, this just tells you outright.

If logging is kept in and the delay is shortened, it's still also extremely easy to spam the log.

**Comment by Varen** [comment]
Knocking for urgency by repeatedly using the access denied thing is honestly peak emergent gameplay, if someone is rude about it it's an IC issue really.

**Comment by UbaserB** [comment]
30 seconds is way too long i agree.

**Comment by K-Dynamic** [comment]
30 seconds way too long

It would also be better to make an 'access denied' message popping up for player feedback, similar to that of trying to open a secure crate or locker without access

**Comment by EmoGarbage404** [comment]
tbh i don't really see an issue with the way it's currently done. The sound effect and red flash are plenty effective for communicating the lack of access. The popup would just be visual noise.

**Comment by deltanedas** [comment]
5 seconds seems too long imo maybe 3

also datafield is already vv rw dont need it

**Comment by koteq** [comment]
Reduced the cooldown to 2.5 seconds

https://github.com/space-wizards/space-station-14/assets/1192090/f4d10fea-0257-4f74-a9f8-cdec96965c1f

**Comment by K-Dynamic** [comment]
> Reduced the cooldown to 2.5 seconds
> 
>  Screen.Recording.2024-02-03.at.17.46.25.mp4

You'll still want an 'access denied' popup message for better readability, much better now though

**Comment by UbaserB** [comment]
> Reduced the cooldown to 2.5 seconds

to be fair i still am not a fan of the cooldown. I understand it’s annoying, but I’ve been playing a bit of ss13 recently and i loved it when i could tap the doors even faster than we currently do in 14. As a compromise, can you make it so that the sound is a lot quieter and duller instead of making the time between each beep a lot longer? At least maybe give my idea a try, even if you don’t commit it.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
We don't want the deny visual cooldown at this time. However, the logprobe changes are quite nice. Could you please remove the unwanted changes so this can go through?

**Pull request closed without merging**
