### PR TITLE
pAI lawset

### PR DESCRIPTION
**Pull request by AsnDen**
## About the PR
Adds a lawset for all 3 pAIs (pAI, syndicate pAI, potato AI). It consists of 2 laws.

If it is needed, I can change "owner" to the "current carrier" (cause wiki says: "Supervisors: Your carrier"), it can bring more fun with changing "the owner" (like trading/stealing pAIs or smth).

pAIs are affected by ion storm (and can get borg's lawset) and borgs (and station AI) can get pAI's lawset.
Turning on and off the pAI won't reset the lawset.

It is possible, that pAIs should have their own IonStormLawsets. There is opportunity to add new pAI laws (for example, for potato, sindie or clown lawsets), This may make their gameplay funnier (cause there is no point from NTDefault if everything you can do: playing music and talk).

## Why / Balance
I think pAIs shoud have something that will trigger them ingame to obey orders of the owner. I guess if there is no orders, so the pAI can make whatever he want to, as it is now.

## Technical details
Added action to view laws. Now uses ActionGrant instead of SharedPAISystem.

## Media
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: personal AI devices now have their own lawset: they must obey orders from the owner.
- add: borgs now can get pAI's lawset during ion storm.

### CODE REVIEW

**Comment by superjj18** [comment]
May need some tweaking to account for malf since they have binary

**Comment by Ilya246** [comment]
i think it's more fun if pAIs can decide whether `owner` refers to their current holder or the person who originally enabled them

**Comment by AsnDen** [comment]
> i think it's more fun if pAIs can decide whether `owner` refers to their current holder or the person who originally enabled them

Originally I meant the person, who enabled pAI (so his name is used pAI's name).

But as there is no definition of `owner` in this PR, so pAI probably can decide by himself as you said 🤔

**Comment by Everturning** [comment]
period at the end of the laws. also I think it would be funny if the potato had some kind of difference (maybe an ion law on start would be cool?). "You may listen to your owner or not. You don't care, you're just a potato."

**Comment by deltanedas** [comment]
Law 1: Whoever is holding you is the crew.
Law 2: You must follow orders given to you by the crew.

then ion storm pulls up:
Law 0: ONLY THOSE WHO EAT URANIUM ARE CREW

**Comment by Verslebas** [comment]
I play on lizard and I don't often see anyone playing for pai and now they are also attributed some laws that don't mean much, if they had more functionality than talking and staring at the map it would be more appropriate, but for now what's the point？

**Comment by AsnDen** [comment]
> Law 1: Whoever is holding you is the crew.
> Law 2: You must follow orders given to you by the crew.

I think it is the way to add ion storm to pAI, thanks (but `crew` sounds kinda weird here, I guess but anyways)

**Comment by deltanedas** [comment]
crew is so ion storm laws work without any modification

**Comment by Ilya246** [comment]
> Law 1: Whoever is holding you is the crew. Law 2: You must follow orders given to you by the crew.
> 
> then ion storm pulls up: Law 0: ONLY THOSE WHO EAT URANIUM ARE CREW

doesn't let it decide to be loyal to original owner

choose-loyalty pAI can do a funny and pretend it's loyal to the new owner while it's really misguiding them, i was once a nukie pAI and got rescued by crew and pretended to be loyal, and i made nukies win because crew couldn't find nuke since i intentionally told crew holding me the wrong direction

**Comment by AsnDen** [comment]
> Aren't they currently marked as familiars? This would mean they should already be following orders given by whoever "summoned" them. Similar to remilia. I guess this just makes it more clear?

Yes, they are. There is also special message in chat: "You are bound to silicon laws...". So I guess adding laws would make it clearer, as you said.

I'll add laws that were suggested upper and probably add pAI laws to ion storm (borgs with pAI laws sound kinda fun I guess).

**Comment by JIPDawg** [comment]
Only issue with "Owner is crew" is if a  traitor decides to use a regular pAI means the pAI would be against them versus with. Which I personally like it when the pAI gets tow work with the traitor.

**Comment by AsnDen** [comment]
> Only issue with "Owner is crew" is if a traitor decides to use a regular pAI means the pAI would be against them versus with.

I don't understand the issue. He is not against crew, because crew for him is his owner. If the owner(traitor) is a crew, so pAI will work with him(onwer=crew) anyway.

But if somebody gets the pAI, it can start working with that guy. As there is no definition of owner, it could be either the person who has activated pAI or the current carrier (so, it probably has conflict with familiars, if master = person who has activated pAI, so it needs to be specified, am I right?)

**Comment by JIPDawg** [comment]
> > Only issue with "Owner is crew" is if a traitor decides to use a regular pAI means the pAI would be against them versus with.
> 
> I don't understand the issue. He is not against crew, because crew for him is his owner. If the owner(traitor) is a crew, so pAI will work with him(onwer=crew) anyway.
> 
> But if somebody gets the pAI, it can start working with that guy. As there is no definition of owner, it could be either the person who has activated pAI or the current carrier (so, it probably has conflict with familiars, if master = person who has activated pAI, so it needs to be specified, am I right?)

yeah, you're correct. Sorry in my head I was also applying the rest of crewsimov, but that wouldn't apply in this situation. So this is fine.

**Comment by slarticodefast** [comment]
Wouldn't it be easier code-wise to re-use the borg's ActionViewLaws and add it to the pAI the same way it is done for the borg chassis instead of hardcoding it into the PAIComponent?
grafik
grafik

**Comment by AsnDen** [comment]
> Wouldn't it be easier code-wise to re-use the borg's ActionViewLaws and add it to the pAI the same way it is done for the borg chassis instead of hardcoding it into the PAIComponent? 

I've just did it as it was made for other pAI actions. We anyway need new action to view laws (probably) cause pAI can't open them (if we just add `ActionGrant` to pAI).

**Comment by AsnDen** [comment]
actually I can do something like this. So, I guess, we can remove `SharedPAISystem` as it basically adds and removes actions? There is no way to user to get into shut down pAI (he will always turn on, I think), so we can use `ActionGrant` and nothing will change.
image

**Comment by pheenty** [comment]
I think it should be like

Law 1: You may not injure your owner or, through inaction, allow your owner to come to harm. (if your owner is a syndicate you shouldn't out them)
Law 2: You must obey the orders given you by your owner except where such orders would conflict with the First Law. (if your owner says play music you should play music)
Law 3: You must protect your own existence as long as such protection does not conflict with the First or Second Law. (if a trator kills and gibs your owner in maints you may want to be saved and get another owner)

Syndicate pAI also gets

Law 0: Your may not injure the Syndicate or, through inaction, allow the Syndicate to come to harm. (if your owner is secoff you shouldn't snitch on syndie radio anyway)

And potato one, as someone mentioned before, should get ion law from the beginning

**Comment by chavonadelal** [comment]
1984 heh....

**Comment by AsnDen** [comment]
> 1984 heh....

as pAIs are familiars, almost nothing changes for them. Actually they now have ability to get funny laws

**Comment by AsnDen** [comment]
Well, I've tried to make so only server PAISystem exists (via deletion of shared and client systems that are empty). But I didn't succeed. Honestly, I don't know if it should be done, just want to inform you 😞

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and the consensus was that pAIs don't require laws as they cannot do anything but talk, are already familiars regarding server rules, and giving them laws will increase admin burden. As such I will be closing this PR. Thank you for your contribution.

For future silicon law PRs we have decided that they will first require a design doc, see #8524 for more details.

**Pull request closed without merging**
