### PR TITLE
small-ship-1 salvage update

### PR DESCRIPTION
**Pull request by Emisse**
before
image
after
image

### CODE REVIEW

**Comment by Emisse** [comment]
goal of these is to make smaller salvages less soul crushing and devoid of happiness and joy, ill go over the other ones soon too

**Comment by Cheackraze** [comment]
dont forget to update the salvage prototype yaml if the sizes of any of them change, they need the bounds listed in the prototype

**Comment by Emisse** [comment]
the sizes stay within the contstraint specified by the yml broke ass

**Comment by Emisse** [comment]
actually one of em didnt fugg

**Comment by Emisse** [comment]
actually wait why do these all have super specific bounding boxes thats stupid shouldnt they just be generic sizes, small medium large

**Comment by Emisse** [comment]
ok nevermind im not updating salvage anymore this is dumb

**Pull request closed without merging**
