### PR TITLE
Implementing the hardsuit resprites made by gtheglorious

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

I implemented the new hardsuit sprites gtheglorious created, at their request
## Why / Balance

resprite
## Technical details

nuh uh
## Media

secsuit
wardensuit
Jugsuit

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

nuh uh
**Changelog**

tweak: The security hardsuit, warden hardsuit, and juggernaut suit have all gotten new sprites made by gtheglorious.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
baystation voidsuits when :trollface:

**Comment by JoeHammad1844** [comment]
god damn the jugsuit has an ASS

**Comment by JoeHammad1844** [comment]
i dont like the new hos suit sprite, it looks too similar to the warden's hardsuit sprite

**Comment by JoeHammad1844** [comment]
the hos's hardsuit also feels too iconic to change

**Comment by Terraspark4941** [comment]
is the changelog missing the 🆑 near the beginning?
dont think it will post if the 🆑  is missing

**Comment by Emisse** [comment]
i think you should maybe keep the visors of the 3 sec suits as they were so theyre still easily distinguishable from each other

**Comment by Emisse** [comment]
so like the split normal sec one, the circular hos one, and the wardens you can keep as the current one

**Comment by JoeHammad1844** [comment]
if the hos's suit was white he would just be the elite combine from hl2

**Comment by Boaz1111** [comment]
As mentioned, it's not my sprites, will relay the feedback though, also, the HoS suit has not been resprited, that's the warden suit

**Comment by JoeHammad1844** [comment]
nope, that is the HOS's suit
image

**Comment by Gtheglorious** [comment]
> so like the split normal sec one, the circular hos one, and the wardens you can keep as the current 

Sec suit had to have the split visor removed for accessibility, it was too similar to the both of the nukie hardsuit variants (as all of their helmets have parallel line visors). 

Sec has the middle bar splitting the visor removed, Warden has a visor similar to a riot helmet, and hos hasn’t been changed (PR got messed up).

**Comment by Boaz1111** [comment]
Wait shit I fucked up, gimme a sec

**Comment by Boaz1111** [comment]
I'll fix this tomorrow

**Comment by Brandon-Huu** [comment]
You could had just converted to draft instead of closing

**Pull request closed without merging**
