### PR TITLE
Adds minable salt "ore"

### LINKED ISSUE #22825: Feature Request: Salt Rocks in Salvage Ore
## Description
Salt Rocks should be added to salvage so sodium, chloride, and iodine are easier to obtain for chemistry. When ground or dissolved in a water container, they give 5u for each of these chems. Can also be used for making Saline solution in a pinch.

### PR DESCRIPTION
**Pull request by Zadeon**
## About the PR

Adds salt as a new "ore" for salvage to mine. This salt ore can then be ground up for its base chemicals: sodium, chlorine, and iodine.
Closes #22825

## Why / Balance

Makes it a bit easier for chemistry to obtain these chemicals without having to order them. Right now it has the same rarity as quartz for spawning in asteroids but I am open to changing spawn values if deemed necessary.

## Technical details

Adds a new ore to Resources/Prototypes/Entities/Objects/Materials/ore.yml with the id: SaltOre. Asteroid generation is also updated to include this new ore.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

## Breaking changes

None that I know of.

**Changelog**

:cl:
- add: Added salt as a new type of ore that can be mined from asteroids. Salt can be ground up for its base components.

### CODE REVIEW

**Comment by Zadeon** [comment]
The sprites were made by a friend of mine but they wish to remain anonymous. Is there anything I need to change or add to the meta.json files because of this?

**Comment by UbaserB** [comment]
the ore sprite looks a bit weird. In rock it's fine but the item itself is a bit hard to discern

**Comment by Zadeon** [comment]
> the ore sprite looks a bit weird. In rock it's fine but the item itself is a bit hard to discern

Any suggestions on how to improve it?

**Comment by UbaserB** [comment]
bigger chunks of white "crystals" with defined form on top of a rock (like geode style even maybe)

**Comment by Zadeon** [comment]
Reposting this here from the issue so it doesn't get looked over, but PolterTzi does bring up a good point about ground salt already being electrolized:
>I don't quite understand why salvage would want specifically sodium and chlorine over table salt. Could be me forgetting something, but feels like salt would be more useful.
>And it just feels weird to have ground salt be already electrolised.

So should grinding raw salt give 10 units of tablesalt and 5 units of iodine instead?

**Comment by Zadeon** [comment]
Here's an alternate sprite for the salt ore.
image

The artist probably won't be able to do much more on this so if these don't work somebody else might have to sprite it.

**Comment by Zadeon** [comment]
Updated so that grinding salt gives 10 units of tablesalt and 5 units of iodine. We still need to decide whether one of these existing sprites works for the item or if a completely different sprite needs to be made.

**Comment by Emisse** [comment]
we can adjust balance stuff later depending on feedback

**Pull request merged**
