### PR TITLE
Remove tasers from arsenal tech

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Tasers are highly controversial and, though they are rare due to the cost of unlocking, when they are present in rounds they exacerbate the worst aspects of stun meta. Extremely hard to counter, they really just turn nukeops and revs rounds into a rush for arsenal so sec can play cleanup.

now that we have an alternative T3, i really don't mind cutting them.

## Why / Balance

Tasers suck and trivialize antags and i don't think any cost is gonna justify adding them back.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed the Handheld Electrical Propulsion technology and its associated item, tasers, from research.

### CODE REVIEW

**Review by Partmedia — APPROVED** [review]
While it seems to me that people who put work into a high-effort unlock should be able to get something fun, I also defer to emo on technology balancing. It sounds like the meta happens often enough that it is an issue.

**Comment by HoidC** [comment]
never thought I'd see the day where emogarbage argued for the removal of tasers

**Comment by JoeHammad1844** [comment]
tier 3 x-ray cannons when

**Comment by aesdfxcgvbh** [comment]
Why not just make tasers unable to penetrate a spacesuit? Scientists rarely unlock them anyway

**Pull request merged**
