### PR TITLE
PlantHolderVisualizer component system refactor

### PR DESCRIPTION
**Pull request by ModeratelyAware**
Part of #8995 
Converted PlantHolderVisualizer to ECS component and system.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
people have reaped the punishment for putting their new visualizer system at the end of the list... next time be more original and avoid conflicts...

**Comment by ModeratelyAware** [comment]
> people have reaped the punishment for putting their new visualizer system at the end of the list... next time be more original and avoid conflicts...

I am not sure I understand?

**Comment by EmoGarbage404** [comment]
this isn't for you. oftentimes, people will put their visual component at the very bottom of the IgnoredComponents list, which always causes tons of conflicts.

**Comment by ModeratelyAware** [comment]
> this isn't for you. oftentimes, people will put their visual component at the very bottom of the IgnoredComponents list, which always causes tons of conflicts.

Oh, so you mean not the actual Visuals enum but the component itself? Just trying to make sure I'm not doing anything wrong (or will do anything wrong) as I am pretty new and also going through a lot of visualizers.

**Pull request merged**
