### PR TITLE
Ghost role drop-down alignment

### LINKED ISSUE #33387: Availability dropdown in the ghost role menu sticks out too much
## Description

I can understand why that direction was taken, as it needs to stand out some way from the other rows when it gets dropped down but there's better ways to do it. The biggest issue that bothers me right now is consistency; when everything is on it's default mode (aka what you're looking at most of the time), it sticks out far too much compared to the other options and looks jarring on the eyes.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Intoxicating-Innocence**
## About the PR

This change makes the drop-down buttons in the ghost role availability menu no longer stick out horizontally with respect to other buttons.

To address concerns that this may make the button less distinct from its children, a larger spacing has been added below it.
## Why / Balance

This change addresses the issue laid out [here](https://github.com/space-wizards/space-station-14/issues/33387)
Fixes #33387 
## Technical details

It is a single line of code that adds a margin to an existing element.
## Media

Before:
beforeAlignment
After: 
afterAlignmentNew

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by Aeshus — APPROVED** [review]
Works as intended!

**Comment by Aeshus** [comment]
@Intoxicating-Innocence You probably don't need a change-log for this change.

> Log only changes with significant in-game impact. This may include new features or changes or tweaks to existing features that affect balance. Minor changes to object appearances and descriptions typically do not affect how you would play the game. Changelog entries for major sprite updates are appropriate.
- https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#writing-an-effective-changelog

(Also, your current change-log formatting has issues, as you're missing the :cl: emoji and a space between the `-` and `tweak`. See https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog-template)

**Comment by Intoxicating-Innocence** [comment]
> @Intoxicating-Innocence You probably don't need a change-log for this change.
> 
> > 2. **Log only changes with significant in-game impact.** This may include new features or changes or tweaks to existing features that affect balance. Minor changes to object appearances and descriptions typically do not affect how you would play the game. Changelog entries for major sprite updates are appropriate.
> 
>     * https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#writing-an-effective-changelog
> 
> 
> (Also, your current change-log formatting has issues, as you're missing the 🆑 emoji and a space between the `-` and `tweak`. See https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog-template)

Noted, I think when i read the guidelines i focused on the examples and not the paragraph header.

**Review by slarticodefast — APPROVED** [review]
Absolutely blessed PR, this was annoying me way too much :)
Tested in-game and works as intended.
Thank you for your first contribution!

**Comment by MilenVolf** [comment]
Put `Fixes #33387` into description so github will attach this issue to this PR and merging this will automaticly close attached issue

**Pull request merged**
