### PR TITLE
Nerf bible

### PR DESCRIPTION
**Pull request by metalgearsloth**
70 damage per 5 seconds is absurd. I also added a message where no damage is changed.

Fixes https://github.com/space-wizards/space-station-14/issues/10018

:cl:
- tweak: Bible heal has been reduced from 70 damage per 5 seconds to 10 damage per 5 seconds.

### CODE REVIEW

**Comment by Elijahrane** [comment]
I looked up bible in 5 different SS13 codebases and they all heal 10 per second. Chaplain is already deliberately weaker by having familiars instead of some sort of weapon. Does the bible need to be 5x worse than it was in every SS13 server with chaplains on top of that?

**Comment by metalgearsloth** [comment]
/tg/ also allows you to stunlock people.

**Comment by Elijahrane** [comment]
Oh, nevermind, you doubled the use delay too, so it's 10 times worse than in every ss13 server

**Comment by metalgearsloth** [comment]
Non-combat item that almost fully heals 2 damage types?

**Comment by HoidC** [comment]
> Non-combat item that almost fully heals 2 damage types?

if I understand things correctly it's not going to be in practise ever doing 70 heal unless you somehow got equal splits across 4 damage types

in gameplay it takes a good 5-6 hits to actually fully heal you

**Comment by Elijahrane** [comment]
> Non-combat item that almost fully heals 2 damage types?

It heals 2 groups, not 2 types. To get full healing you would need to have damage in 6 different types. If it's all in 1 type, you will heal about 20 damage, or 4 per second

**Comment by moonheart08** [comment]
You've successfully nerfed it so hard it heals under 2 damage a hit in most cases.

**Comment by OldDanceJacket** [comment]
With this change it's also completely worthless when someone is in crit state. 
In actual gameplay the best way to play Chaplain is to be at the bedside of a real doctor as they give their medicine while you support with your bible.

Chaplain is one of the few jobs that promotes RP as well as actually positively helping the crew, with their healing aimed entirely at folks that are using more mundane weapons like toolboxes and the like. Folks also react positively towards the job across the board, actually caring if the Chaplain is in danger or not.

**Comment by Kromabae** [comment]
rip bible

**Comment by mirrorcult** [comment]
seems unpopular to nerf it this hard. im of the opinion it should probably be nerfed (bible healing is kind of a wack concept to begin with) but probably not this bad

**Comment by EmoGarbage404** [comment]
> seems unpopular to nerf it this hard. im of the opinion it should probably be nerfed (bible healing is kind of a wack concept to begin with) but probably not this bad

The nerf in a later commit isnt too bad.

**Comment by mirrorcult** [comment]
didnt notice that. this is probably fine then

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
