### PR TITLE
New IDs

### PR DESCRIPTION
**Pull request by AJCM-git**
New IDs that actually fit in the ID slot

### CODE REVIEW

**Comment by ComicIronic** [comment]
Independent to the visuals of the new cards: should we be re-spriting things to fit in inventory slots? Most item icons in the game aren't designed around fitting neatly in a less-than-32x32 box, so doing this might mean a lot of work. I also don't inherently see the benefit.

**Comment by AJCM-git** [comment]
@PJB3005 Is there any reason for the 22x22 UI slots?

**Comment by PJB3005** [comment]
The SS13 sprites are like this because they are HUD icons so they are smaller to take less room.

**Comment by SweptWasTaken** [comment]
Looks ready for merging to me unless anyone else has an issue with the sprites. 

I wish we could have some smaller sprites make for IDs on the ground since they look massive but that might hinder readability.

**Pull request merged**
