### PR TITLE
medibot fixes and refactoring

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- made medibot code slightly less evil
- emagged medibots no longer need you to have more than 0 damage to sleep you so they are much more useful
- treatment to use was changed to use mob states instead of hardcoded damage values, so medibot will give crit mouse airloss med instead of waiting for mouse to get impossible 100 damage
- fixed All done. being in chat and logs oop

## Why / Balance
bye bye shitcode

## Technical details
- instead of checking TotalDamage to decide the treatment it checks `Treatments` dictionary with the patients mob state.
  TotalDamage is now only used for thresholds to avoid unnecessary injections of trico
- thresholds are no longer hardcoded, theyre stored in the component's treatments
  trico requires you have >0 <50 damage so it isnt wasted
  chloral hydrate has no thresholds so it doesnt require you have 1 damage before sleeping

## Media
eepy

urist given lexorin then medibot gave dex+ and revived urist

gamer giving dex+ once crit (now inaprov again)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
replaced `Medibot`'s fields with the required `treatments` dictionary

**Changelog**
:cl:
- fix: Fixed emagged medibots not injecting healthy people with chloral hydrate.

### CODE REVIEW

**Comment by lzk228** [comment]
medibots become useful???

**Comment by deltanedas** [comment]
slightly more useful

**Comment by Emisse** [comment]
operation run failed tests until they pass is a go

**Comment by deltanedas** [comment]
operation sleepy time

**Comment by Doru991** [comment]
> replaced inaprov with dex+ to work on mobs that dont use 100 damage crit threshold, no real difference ingame since it would only give when crit (besides if you have only airloss damage, then it will heal it all)
Why does it matter whether they use 100 damage threshold? Wouldnt inaprov work the same?

**Comment by lzk228** [comment]
> Why does it matter whether they use 100 damage threshold? Wouldnt inaprov work the same?

some mobs can be dead at 100 damage, so the real solution, to make inaprov heal only in crit state

**Comment by Doru991** [comment]
Inaprov is already based on mobstate instead of hardcoded damage pro

**Comment by lzk228** [comment]
only pro here is deltanedas then :trollface:

**Comment by deltanedas** [comment]
pro i thought it was hardcoded 100 dmg :trollface:

**Comment by lzk228** [comment]
lessgo

**Pull request merged**
