### PR TITLE
Fix checking traitor stealth items (thief gloves, etc.) via prototype ID

### PR DESCRIPTION
**Pull request by 0x6273**
## About the PR

Traitor stealth items such as thieving gloves, explosive pens, no longer leak their real identity via their prototype ID. To the client they are identical to black gloves and regular pens, respectively. 

## Why / Balance

This is to combat cheat clients that would read the client prototype ID to check for traitor items.

## Technical details

This changes the StoreSystem and SpawnItemsOnUseSystem to spawn the regular item, then add components to it server-side.
Currently WIP for 3 reasons:
- [ ] Some code duplication for adding comps to an entity from `ComponentRegistry` (copy-pasted from ArtifactSystem)
- [ ] Need consensus from maintainers if this is a good approach (it has limitations, like not working for items spawned from things other than stores and SpawnItemsOnUse)
- [ ] Needs to be applied to every stealth item, not just explosive pen and thief gloves.

Another approach I considered was a way to "spoof" the prototype ID that's sent to the client, so that it appears as "Pen" on the client and "PenExplosive" on the server. But I think this would require engine change, and I'm not sure how to implement it.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Rainfey** [comment]
With this forcing the secret components to be server side only, will it affect client side prediction?

**Comment by 0x6273** [comment]
> With this forcing the secret components to be server side only, will it affect client side prediction?

You can't really have client prediction on an item that should be indistinguishable from another item without that predicted behavior. Prediction requires client components, and that means cheaters can just VV the item and look if those components are present.

**Comment by metalgearsloth** [comment]
If we really wanted this (as is this is just a prediction nightmare) then it should be using session-specific components / sendtoowner and where inadequate it should be fixed, not this.

**Comment by 0x6273** [comment]
> If we really wanted this (as is this is just a prediction nightmare) then it should be using session-specific components / sendtoowner and where inadequate it should be fixed, not this.

Can you give an example of how to do this with sendtoowner? I searched the codebase for that but got 0 results.

**Comment by metalgearsloth** [comment]
> > If we really wanted this (as is this is just a prediction nightmare) then it should be using session-specific components / sendtoowner and where inadequate it should be fixed, not this.
> 
> Can you give an example of how to do this with sendtoowner? I searched the codebase for that but got 0 results.

The actual name is SendOnlyToOwner.

**Comment by metalgearsloth** [comment]
derelict.

**Pull request closed without merging**
