### PR TITLE
Reparent closets and lockers, make them craftable [DRAFT]

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Partitial remake of #21008
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:

### CODE REVIEW

**Comment by lzk228** [comment]
@iacore look

**Comment by iacore** [comment]
nice attempt!

things that don't belong in this patch:

- modified damage modifier and other stuff not belong to crafting.
- `parent: secure_locker` 
FYI: secure locker is locker but much harder to break


Because space suit storage are also subclass of locker, you have to create the following hierarchy:

base <- steel base <- steel variants
base <- wooden base <- wooden variants
base <- cylinder base <- cylinder variants
base <- other variants

**Comment by lzk228** [comment]
Pic is existing parenting in game?

**Comment by iacore** [comment]
> Pic is existing parenting in game?

Yes. the ClosetBase tree is outdated because I changed it

**Comment by lzk228** [comment]
bruh im stupid

**Comment by lzk228** [comment]
i need comment to reopen

**Comment by iacore** [comment]
why your repo name be like `space-station-15` :flop:

**Comment by lzk228** [comment]
@iacore can i contact with you somehow somewhere out of github?

**Comment by iacore** [comment]
> @iacore can i contact with you somehow somewhere out of github?

https://www.1a-insec.net/about

**Comment by iacore** [comment]
my friend please rebase, not merge :)

**Pull request closed without merging**
