### PR TITLE
CMO Drip DLC

### PR DESCRIPTION
**Pull request by Hanzdegloker**
## About the PR

I will not rest until every department head has a spare jumpsuit/jumpskirt ( Now with new sprites! )

## Why / Balance

Every department head should have at least one set of spare clothes, also every department head already has a turtleneck besides CMO and HoP so might as well fill in the gaps and solve the aforementioned issue.
## Technical details

added new CMO turtleneck jumpsuit/jumpskirt
added new head mirror
added the new CMO drip to the CMO dresser
added the CMO turtleneck jumpsuit/jumpskirt to the clothes printer
10% chance the head mirror will spawn in a filled medical doctor locker

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added CMO turtleneck jumpsuit/jumpskirt.
- add: Added a head mirror which may spawn in medical doctor's lockers

### CODE REVIEW

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
i love the idea, but i dont like how it looks

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
the lack of shading on the turtlenecks doesn't look great and there's some contrast issues on the cyan pants. I don't really get why the CMO needs turtlenecks to begin with but whatever.

the head mirror looks fine aside from the icon, which could definitely just use a different perspective and a more dynamic pose for the strap. Besides that, i don't really think it needs to be limited to CMO at all. I don't get your goal of giving every head unique headgear when they really just don't need it most of the time and already have berets or whatnot to differentiate themselves a lot of the time. The head mirror is probably better off as just a normal clothing item for mappers to populate stuff with.

**Comment by Hanzdegloker** [comment]
> the lack of shading on the turtlenecks doesn't look great and there's some contrast issues on the cyan pants. I don't really get why the CMO needs turtlenecks to begin with but whatever.
> 
> the head mirror looks fine aside from the icon, which could definitely just use a different perspective and a more dynamic pose for the strap. Besides that, i don't really think it needs to be limited to CMO at all. I don't get your goal of giving every head unique headgear when they really just don't need it most of the time and already have berets or whatnot to differentiate themselves a lot of the time. The head mirror is probably better off as just a normal clothing item for mappers to populate stuff with.

the QM has the soft cap or the beret, CE has the hardhat or the beret, HoS has like 3 different hats. The goal is more to get the dressers of the Heads to look similar in options. The turtleneck deal is simple, QM, CE, RD and HoS have turtlenecks already so this is more of filling in the gaps than anythin. It was once brought up by a persons that every head should have at least one alternative jumpsuit/jumpskirt spare in their dresser and yeah hence my deal.

There is shading on the turtleneck, just very subdued, I can make it more noticeable. The head mirror Icon is kinda estranged yes, I found one example of a sprite in ss13 but tried to do it on my own anyways for practice, I'll redo it. I suppose the head mirror could be made generic, but I mean look at the love the HoS gets, so many items their dresser is FULL while one of the items in the CMO dresser is just an extra of what they're already wearing. Anyhow I appreciate your feedback and thankyou for looking at my stuffs.

**Comment by Hanzdegloker** [comment]
I made some fixes and redid the sprites

**Comment by mirrorcult** [comment]
this needs updated to use loadouts

**Comment by mirrorcult** [comment]
@Flareguy sprite opinions

**Comment by Hanzdegloker** [comment]
> this needs updated to use loadouts

It'll be done by tomorrow night o7

**Review by EmoGarbage404 — APPROVED** [review]

**Pull request merged**
