### PR TITLE
Added light post sprites

### LINKED ISSUE #10138: small_light_post.rsi is missing the burn and broken states.
Fixing this just requires creating the sprites and adding them to the RSI (adding the png & updating the meta.json).

### PR DESCRIPTION
**Pull request by Violet754**
## About the PR

Adding and or adjusting the burnt, empty and damaged post light sprites.

Resolves #10138

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

L_20230308_120637
couldnt get the burn one to show up ingame due to a burning system not being implemented? but the texture and state are there.

**Changelog**

:cl: Nekomancer
- add: Added small light post state sprites
- tweak: Tweaked small light post empty sprite

### CODE REVIEW

**Comment by Violet754** [comment]
updated the changelog.

**Comment by EmoGarbage404** [comment]
you shouldn't add the sprites if you can't get them to display in game.

**Comment by Violet754** [comment]
im only adding what was requested in https://github.com/space-wizards/space-station-14/issues/10138 i have attempted to burn the light post but it appears that feature isnt complete yet, i could attempt to get it easily visible ingame but it would require debug code or some method im not aware of and would be outside the scope of https://github.com/space-wizards/space-station-14/issues/10138.

**Comment by EmoGarbage404** [comment]
apologies, i misunderstood. I thought that you couldn't get any of the images to appear in game.

**Comment by Violet754** [comment]
all good! i should have been a bit more clear about it being a unfinished feature not me being unable to get it ingame.

**Pull request merged**
