### PR TITLE
Clown Clothes Resprite

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes the base clown clothes, keeping it as faithful to the old sprite as much as possible. Specifically:
- Added proper credit to the meta files
- Tweaked the clown shoe outline and filled spaces based on the former colors
- Redid the jumpsuit pants completely while keeping everything else intact apart from some tweaks
- removed the mysterious mouth from the mask, gave the hair an outline, moved the mask down to match the eyes, brightened the eyes a little, removed the excessive outlines on the mask itself
- Added extra shades to the Giggles Von Honkerton from the icon sprite to the equipped sprite and did some cleanup, added the zipper from the icon to the equipped sprite while extending the backpack down a pixel, cleaned up the icon sprite significantly
- Changed all icons and held sprites

I understand this is a controversial sprite to change, but be kind. I thought it deserved some love.
I'll add the monkey jumpsuit if it gets merged.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: The clown got a new coat of paint. New honk, same as the old honk.

### CODE REVIEW

**Comment by Luxzhv** [comment]
Seems softer and brightened up a bit to help with visibility, fairly good.

**Comment by GoodWheatley** [comment]
I like the original sprites better tbh

**Comment by brainfood1183** [comment]
Looks great, although cluwne would probably need resprite to.

**Comment by Emisse** [comment]
i like old clown mask/backpack, clothes and shoes are alright

**Comment by PuroSlavKing** [comment]
soap

**Comment by Emisse** [comment]
ITS WEIRD

**Comment by Alekshhh** [comment]
let me cook

**Comment by JoeHammad1844** [comment]
old honk is more honk

**Pull request closed without merging**
