### PR TITLE
Cluster 2.0 (Update 2.5)

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR

entirely new layout made from scratch

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Cluster-0

**Changelog**

uhh idk if this needs to have a cl sure it's a major map change but it's an existing station

### CODE REVIEW

**Comment by Emisse** [comment]
missing detective spawnpoint, so add a spawnpoint or remove det from proto

**Comment by Scribbles0** [comment]
> missing detective spawnpoint, so add a spawnpoint or remove det from proto

woopsie

**Comment by Froozigiusz** [comment]
Maybe make chapel smaller and put a tiny security's arrival outpost? It could also be connected with a medical compartment if you get creative (I would place it between chapel and medical and chapel and restructure the maintenance corridor)

**Comment by Emisse** [comment]
ill look at this later tonight or tomorrow

**Comment by deltanedas** [comment]
i feel telecomms might be a bit too hard to sabotage for traitors

**Comment by Froozigiusz** [comment]
Give it a proper changelog, I think it's ready to be merged.

**Comment by Scribbles0** [comment]
updated the map image to latest changes

**Pull request merged**
