### PR TITLE
remove useless tip

### PR DESCRIPTION
**Pull request by lzk228**
no cl

### CODE REVIEW

**Comment by Flareguy** [comment]
What's useless about the alt-click tip? It lets you eat while both of your hands are full.

**Comment by Zumorica** [comment]
> What's useless about the alt-click tip? It lets you eat while both of your hands are full.

That's not the tip that was removed in this PR, it's this one: "As the Chief Medical Officer, your hypospray starts with omnizine, which can heal almost every type of damage at once, but can't be synthesized. Use it wisely!"

**Comment by Flareguy** [comment]
> > What's useless about the alt-click tip? It lets you eat while both of your hands are full.
> 
> That's not the tip that was removed in this PR, it's this one: "As the Chief Medical Officer, your hypospray starts with omnizine, which can heal almost every type of damage at once, but can't be synthesized. Use it wisely!"

I somehow entirely missed the newline, I have no idea why. God damn it.

**Comment by deltanedas** [comment]
17000 pro

**Pull request merged**
