### PR TITLE
adds the turrets back to the nukie ship

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

adds the turrets back
1 on the back
1 in the cockpit
1 in the break room
1 in the power room
1 in that horizontal hall above the break room

moved the gravity generator to the south part of powergen to fit the turret better
moved the power monitor console so the turret doesnt shoot that instead of the doorway
moved the disposals unit in the break room
removed the banners in the horizontal hall, replaced banners with wall flags
## Why / Balance

too easy for non-kies to break in and FTL the ship with the nuke and make it unwinnable for nukies without admin intervention
lasers invalidate em anyway
## Technical details

i had to do code surgery to get this to work
## Media

all types of reinforcement + commander not gettin shot
image
dots placed on the turrets
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: JoeHammad
- add: the nukie shuttle now has its turrets back, think twice about breaking in!

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
12:46 i go to bed

**Comment by metalgearsloth** [comment]
None of the issues that originally caused their removal seem to be addressed, i.e. parking it on top of the nuke.

**Comment by Simyon264** [comment]
Why were they removed? The PR that removed them does not have a lot of details.

**Comment by deltanedas** [comment]
someone planted nuke close to shuttle so its turret always covered it, really shitty tactic

> make it unwinnable for nukies without admin intervention

just drag the nuke with you

**Comment by keronshb** [comment]
> None of the issues that originally caused their removal seem to be addressed, i.e. parking it on top of the nuke.

Here are some ways to satisfy this:

- Make sure the nuke cannot be unanchored when armed & counting down
- Also make sure that the floor under it can't be cut off to prevent cheese
- Prevent nukie ship from parking too close to station

**Comment by GoodWheatley** [comment]
> > None of the issues that originally caused their removal seem to be addressed, i.e. parking it on top of the nuke.
> 
> Here are some ways to satisfy this:
> 
> * Make sure the nuke cannot be unanchored when armed & counting down
> * Also make sure that the floor under it can't be cut off to prevent cheese
> * Prevent nukie ship from parking too close to station

Or you could just make the turrets not fire on people on a different grid.

**Comment by deltanedas** [comment]
aka only put them on the inside

**Comment by Nimfar11** [comment]
Now there are restrictions that a nuclear bomb can't be put close to space.

**Comment by keronshb** [comment]
> insane idea but what if we made it station nuke only and that nuke remained anchored at all times

No because that makes it too easy. There's been enough playdata from 13 to show a regular nuke can work fine, when coded properly.

**Comment by HoidC** [comment]
> > insane idea but what if we made it station nuke only and that nuke remained anchored at all times
> 
> No because that makes it too easy. There's been enough playdata from 13 to show a regular nuke can work fine, when coded properly.

easy for whom

**Comment by deltanedas** [comment]
if its too easy (for nukies presumably) remove the random code and just make it always give the code to the infiltrator's nuke

**Comment by HoidC** [comment]
> if its too easy (for nukies presumably) remove the random code and just make it always give the code to the infiltrator's nuke

I don’t really see how it’s too easy for the nukies when it gives the crew a consistent location to defend which also allows large and dramatic firefights to occur (the highlight of the mode)

babysitting a bomb is pretty boring but I wouldn’t call it hard when you can just dump it or wall off some exterior part of the station

**Comment by Ilya246** [comment]
just readd internal turrets only and should be fine, also take into account that nuke actually needs to be inside now to be armable

**Comment by JoeHammad1844** [comment]
test fail seems erroneous

**Comment by JoeHammad1844** [comment]
> Or you could just make the turrets not fire on people on a different grid.

place lattice under yourself and turrets will ignore you

**Comment by JoeHammad1844** [comment]
> No because that makes it too easy. There's been enough playdata from 13 to show a regular nuke can work fine, when coded properly.

keep in mind that in ss13 (TG station) the nuke cant be disarmed without the disk, which can be taken out after arming (because nukies need to escape alive to get major)

**Comment by JoeHammad1844** [comment]
thing is if i remove the turrets from the front you can just laser the turret in the cockpit for free.. but you could just close the shutters actually

**Comment by JoeHammad1844** [comment]
okay ill remove the turrets from the outside but i'm keeping the one on the inside and at the back

**Comment by JoeHammad1844** [comment]
all turrets have been removed from the outside except for the one at the back

**Comment by JoeHammad1844** [comment]
erroneous test fail

**Comment by JoeHammad1844** [comment]
> Here are some ways to satisfy this:
> 
> * Make sure the nuke cannot be unanchored when armed & counting down
> * Also make sure that the floor under it can't be cut off to prevent cheese

if its unanchored you dont get syndie major

**Comment by lexs0sa** [comment]
idc if i get banned for being off topic or rude or w/e but you are literally the worst PR creator for the history of this game, no clue why you were un repo banned and I would genuinely spend your time wiser elsewhere. also if you switch the 1844 to 1488 in your name it becomes a hate symbol, always found that kind of odd.

**Comment by LordEclipse** [comment]
> idc if i get banned for being off topic or rude or w/e but you are literally the worst PR creator for the history of this game, no clue why you were un repo banned and I would genuinely spend your time wiser elsewhere. also if you switch the 1844 to 1488 in your name it becomes a hate symbol, always found that kind of odd.

Christ, calm down, how else do you expect people to learn and improve?

**Comment by lexs0sa** [comment]
> > idc if i get banned for being off topic or rude or w/e but you are literally the worst PR creator for the history of this game, no clue why you were un repo banned and I would genuinely spend your time wiser elsewhere. also if you switch the 1844 to 1488 in your name it becomes a hate symbol, always found that kind of odd.
> 
> Christ, calm down, how else do you expect people to learn and improve?

idk the 1844 / 1488 thing always struck me as weird tho

**Comment by CrigCrag** [comment]
fellas, is it hateful to *checks notes* have 4 random numbers at the end of your name?

**Comment by VasilisThePikachu** [comment]
Maybe i understand one in the cockpit, everywhere else is meh in my opinion

**Comment by GoodWheatley** [comment]
> also if you switch the 1844 to 1488 in your name it becomes a hate symbol, always found that kind of odd.

This doesn’t even make *sense*???? Why are you randomly switching a 4 out for a 8????

**Comment by VasilisThePikachu** [comment]
> idc if i get banned for being off topic or rude or w/e but you are literally the worst PR creator for the history of this game, no clue why you were un repo banned and I would genuinely spend your time wiser elsewhere. also if you switch the 1844 to 1488 in your name it becomes a hate symbol, always found that kind of odd.

image

**Comment by JoeHammad1844** [comment]
image
huh

**Comment by VasilisThePikachu** [comment]
Don't worry about it

**Comment by JoeHammad1844** [comment]
first they came for lex sosa
i did not speak out because i was not lex sosa
then they came for the maintainers
i did not speak out because i was not a maintainer
but when they came for the contributors, there was no one left to speak for me

**Comment by EmoGarbage404** [comment]
please keep discussion relevant to the PR. thank you.

**Comment by Ilya246** [comment]
it definitely needs the internal turrets to stop people from just taking the shuttle and flying off then proceeding to do nothing the remainder of the shift
also stops nuke stealing if nukies leave it on the ship
needs to make sure people can't just break the front window and ignore the turret because it's behind the console, or build a thindow to be able to pilot the console from behind while not in los of the turret
could relocate the navigation console deeper in maybe?

**Comment by JoeHammad1844** [comment]
> it definitely needs the internal turrets to stop people from just taking the shuttle and flying off then proceeding to do nothing the remainder of the shift also stops nuke stealing if nukies leave it on the ship needs to make sure people can't just break the front window and ignore the turret because it's behind the console, or build a thindow to be able to pilot the console from behind while not in los of the turret could relocate the navigation console deeper in maybe?

there are shutters

**Comment by Ilya246** [comment]
> > it definitely needs the internal turrets to stop people from just taking the shuttle and flying off then proceeding to do nothing the remainder of the shift also stops nuke stealing if nukies leave it on the ship needs to make sure people can't just break the front window and ignore the turret because it's behind the console, or build a thindow to be able to pilot the console from behind while not in los of the turret could relocate the navigation console deeper in maybe?
> 
> there are shutters

shutters and blast doors are useless as long as there's the possibility to build a button

**Comment by Ilya246** [comment]
i think safely stealing the nukie shuttle should require you to deconstruct at least one reinforced wall

**Comment by Emisse** [comment]
superceded

**Comment by JoeHammad1844** [comment]
i cri evri tiem

**Pull request closed without merging**
