### PR TITLE
Revert "Reduce number of unsafe and insane presents"

### PR DESCRIPTION
**Pull request by crazybrain23**
Reverts space-wizards/space-station-14#22067

Reasons for:
- The whole point is that it was chaos.
- It was unjust to reduce the chaos.
- Project Managers liked the chaos.

Reasons against:
- Too much chaos is problematic.
- It's fine how it is right now.
- Head admins didn't like the issues that come with so much chaos.

This PR will be either closed or merged, based on maintainer's choice.

### CODE REVIEW

**Comment by crazybrain23** [comment]
> Was there some discussion that preceded this PR being made.

Ret in the admin discussion after #22067 was merged.
image

Also @moonheart08 seemed to be more for keeping the choas as part of the whole point, but for the other PR (#22065): 
image

**Comment by crazybrain23** [comment]
Basically the nerf was controversial, so I'm offering a chance to unnerf it, depending on maintainer/admin consensus.

**Comment by Hmeister-real** [comment]
> The chaos stuff is a lot more subjective. Every round could be extremely chaotic if that's what players wanted and admins could manage, but I doubt most players want an entire month of never ending chaos. I don't know how chaotic things were for the short time the other percentages were being used, I only really have the accounts of other admins to go off of

1/3 rounds being somewhat chaotic because someone got an uplink, debug, admeme thing or whatever is funny; Most of the time it's not a big deal

**Comment by moonheart08** [comment]
worth noting however i'm perfectly fine with the nerfed odds.

**Pull request closed without merging**
