### PR TITLE
Fix lag spike from stinger grenades

### PR DESCRIPTION
**Pull request by iaada**
## About the PR

`ClusterGrenadeComponent` - specifically the type that spawns bullets - currently causes a lag spike when it goes off. This is because every bullet tries and fails to reference the already deleted grenade. This PR stops the bullets from looking for the grenade.

## Why / Balance

Lag is bad.

## Technical details

Changed `ShootProjectile` in `SharedGunSystem` to make the parameter for gun source nullable.

## Media

Causes ugly admin logging, but previously there was no admin logging at all.
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: aada
- fix: Stinger grenades no longer cause lag spikes.

### CODE REVIEW

**Comment by beck-thompson** [comment]
fixes: #32642?

Also amazing first contribution

**Comment by Plykiya** [comment]
I took a swing at the problem in my complete cluster grenade refactor and explain it similarly in my latest post, and I mean I guess you can get around the issue by just NEVER setting the ProjectileComponent's gunUid at all, it just feels wrong using gun code to shoot a projectile without providing the gunUid 

https://github.com/space-wizards/space-station-14/pull/31108

**Comment by iaada** [comment]
> I took a swing at the problem in my [complete cluster grenade refactor](https://github.com/space-wizards/space-station-14/pull/31108) and explain it similarly in my latest post, and you can get around the issue by just NEVER setting the ProjectileComponent's gunUid at all which I did at some point, but it also just feels wrong using gun code to shoot a projectile without providing the gunUid because it causes bad admin logs as you've already explained so I didn't go that route

I totally agree that my PR is sloppy. I was just looking at a simple fix, but you're is definitely much better done.

**Comment by Plykiya** [comment]
> > I took a swing at the problem in my [complete cluster grenade refactor](https://github.com/space-wizards/space-station-14/pull/31108) and explain it similarly in my latest post, and you can get around the issue by just NEVER setting the ProjectileComponent's gunUid at all which I did at some point, but it also just feels wrong using gun code to shoot a projectile without providing the gunUid because it causes bad admin logs as you've already explained so I didn't go that route
> 
> I totally agree that my PR is sloppy. I was just looking at a simple fix, but you're is definitely much better done.

I mean I still haven't fixed the problem

**Pull request closed without merging**
