### PR TITLE
Adds sound effect to burning yourself on a light fixture

### LINKED ISSUE #597: Make it more obvious when getting burnt by lights
If you attack lights with an empty hand and inadequate protection you can get burnt. There's no popups or notifications when this happens, making it easy to accidentally crit yourself without knowing what happened.

We should notify the player they've been damaged. Simplest way would be to have a popup via `IServerNotifyManager` or equivalent for client/shared. Another option would be some kind of damage overlay or screen effect for all damage, or a sound effect specifically for being burnt by lights.

### LINKED ISSUE #682: Play a hiss sound when burning your hand on a light bulb
Create or find a hiss sound and implement it when touching a hot light bulb.

### PR DESCRIPTION
**Pull request by collinlunn**
Closes #682
Closes #597

Additional notifications methods for player damage are still needed - it is still not obvious that you are taking damage.

### CODE REVIEW

**Comment by unusualcrow** [comment]
Maybe find a different sound?
This one has an impact kick at the beginning of it which doesn't make much sense

**Comment by PJB3005** [comment]
Yeah this is a sound for a laser impact, which is definitely neat (we could use it for the laser gun) it's not exactly fitting.

**Comment by collinlunn** [comment]
Added a second sound that is more of a hiss, and is played instead on a burn. Not perfect, but I can't find anything better at the moment.

**Comment by PJB3005** [comment]
Already have the welder sound at `/Resources/Audio/items/welder.ogg`

**Comment by collinlunn** [comment]
Will get to this another time

**Comment by PJB3005** [comment]
You might just be able to crop the sear sound to cut out the initial laser hit. Seems like it'd sound great.

**Pull request closed without merging**
