### PR TITLE
Change Thief Syndie & Chameleon kit contents, add Syndie codeword paper

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR adjusts and adds items to the Syndie and Chameleon Thief kits, bringing them more in line with their themes and evening out their strengths.

- Agent ID has been removed from the Syndie Kit, and can now instead be found in the Chameleon Kit.
- The Syndiecate pAI has been removed from the Syndie Kit.
- Syndie Kit now includes a Radio Jammer.
- Syndie Kit now includes a piece of paper containing one Traitor codeword.
  - This codeword is randomly selected per paper from the list of traitor gamerule codewords added to the round.
  - If there is no traitor gamerule added, a fake codeword will be randomly generated instead.
  - The codeword works if the traitor gamerule has been added but no traitors have yet to be assigned.
- Syndie Kit now includes a Lighter.

The PR also adds an admeme "syndicate codewords registry" item which lists all active codewords and won't generate a fake one if none exists.

## Why / Balance

The Chameleon kit is largely kneecapped by not having an Agent ID since any player wearing a sechud (including borgs) will be able to easily see through any disguise without much effort. Moving it from the Syndie kit will allow Chameleon kit users to feel free to choose other kits to pair with it instead. The Agent ID also provides similar functionality to the EMAG in their primary usecase (providing access to areas you should not have) so this keeps those items from stepping on each others toes.

There is also an issue of Thieves being metagamed if found with an EMAG, as it can lead an overzealous SecOff to check the PDA ID despite not having a good reason to. 

To compensate for losing the powerful Agent ID, the Syndie Kit has been buffed with the Radio Jammer. While not as powerful to a Thief (the primary usecase of a jammer would be to keep someone from calling out as you murder them) this item could still provide some benefit in delaying reports of thefts. When combined with the EMAG it could delay someone reporting hearing EMAG sounds for a few seconds. It also does not suffer from the stealth item metagaming issue.

There is also a niche usecase of using the Radio Jammer to block the Cargo console from announcing purchases.

Additionally, the Syndie Kit has been given a paper with a single traitor codeword. This codeword is selected randomly for each paper to make it unreliable to find other Thieves with. If there is no Traitor ruleset added, the codeword will be faked by generating it from the list of available traitor codewords. This synergizes well with the kit's intended purpose of connecting the Thief with a Syndicate agent but also keeps the Thief from being able to metagame the gamemode should there be no Traitors on the station.

If the paper is spawned after a midround traitor is assigned, it will be able to get that traitor's codewords as well. Since the codeword can be used to get in contact with Traitors the Syndicate pAI is no longer necessary; it was a bad way to get in touch with Traitors and mostly used to either work with or ruin things for Nukies instead.

The Syndie Kit is also given a lighter to burn the paper, as well as light the Interdyne cigs.

## Technical details

Had to make the codeword generation function public, but other than that it's pretty straightforward.
Check for traitor gamerule upon spawning, get their codewords, select x codewords and put them on the paper.

## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: SlamBamActionman, PolarTundra
- add: Thief's Syndie Kit now comes with a Radio Jammer, a lighter and a Syndicate codeword.
- tweak: Thief's Agent ID has been moved from the Syndie Kit to the Chameleon Kit.
- remove: The Syndicate pAI has been removed from the Thief's Syndie Kit.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
Syndicate pAI has been removed due to being made redundant with the added codeword paper, plus it solves Thieves selling out/working with Nukies which has been seen as a largely undesirable use of it.

**Comment by slarticodefast** [comment]
> plus it solves Thieves selling out/working with Nukies which has been seen as a largely undesirable use of it

Aww, I really liked that possibility. It is only able to interact with traitors who bought syndicate coms or nukies once they are already at the station, so not that overpowered. It was really rare, so it should be fine to keep it in my opinion. And as a ghost role it was always fun to assist and advise somone with his thievery.

**Comment by SlamBamActionman** [comment]
> > plus it solves Thieves selling out/working with Nukies which has been seen as a largely undesirable use of it
> 
> Aww, I really liked that possibility. It is only able to interact with traitors who bought syndicate coms or nukies once they are already at the station, so not that overpowered. It was really rare, so it should be fine to keep it in my opinion. And as a ghost role it was always fun to assist and advise somone with his thievery.

I won't deny that it opens up some good potential for roleplay and synergy, but a robust Thief could make things swing very heavily in both directions. Either the Thief immediately sells out the Nukies which can be absolutely disasterous for a StealthOps (robbing Nukie players of a round through no fault of their own) or the Thief EMAGs a bunch of borgs on the station, explodes substations, hypos the Captain and overall becomes an additional operative with extreme stealth.

**Comment by slarticodefast** [comment]
Considering that the maximum number of thieves got increased recently you are probably right. Especially the impact on stealthops is a good point

**Comment by deltanedas** [comment]
> nukies once they are already at the station

this is false, syndicate radio is long range

**Pull request merged**
