### PR TITLE
Adds unique sprite for NTBlockGame screen

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Original sprite was CrudeCode's but I modified it to better fit.

Sprite could probably use some work I mainly made this to demonstrate how to do it for Crude.

**Screenshots**

**Changelog**

:cl: Swept
- add: Adds unique screen for NTBlockGame

### CODE REVIEW

**Comment by DmitriyRubetskoy** [comment]
blankgame

Updated version of the sprite made in cooperation with /tmp/moony#0029

**Comment by PaulRitter** [comment]
> Updated version of the sprite made in cooperation with /tmp/moony#29

as far as i can tell this hasn't been added to the pr yet, has it?

**Review by PaulRitter — CHANGES_REQUESTED** [review]
also jfc clean your pr, there is some other rework in there

**Comment by moonheart08** [comment]
Yea that sheet isn't in the PR at all.

**Comment by SweptWasTaken** [comment]
> 
> 
> also jfc clean your pr, there is some other rework in there

Wdym clean it check the commits

**Comment by SweptWasTaken** [comment]
Modified the sprite to include the blinking at the end.

**Comment by PaulRitter** [comment]
> > also jfc clean your pr, there is some other rework in there
> 
> Wdym clean it check the commits

nvm i had a brain moment

**Pull request merged**
