### PR TITLE
Added Cog(map) and its own evac shuttle

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR

Added Cog, a new map based on a mix of [goonstation's ](https://goonhub.com/maps/cogmap?x=151&y=151&zoom=-2&sx=130&sy=232)cogmap and [Citadel's ](https://webmap.affectedarc07.co.uk/maps/cit/cogstation/)cogmap and my own ideas. I also added a evac shuttle (emergency_wode.yml) to fit Cog's rather wide evac (Wode is a placeholder name that can be changed later)

### new features (from goon's):
- new evac shuttle
- a reporter's office (with reporter job ofc)
- a remade, larger brig 
- warden's office
- a small medical room in brig
- quartermaster's office
- a shuttle construction bay
- virology
- interesting maints rooms
- singo containment in the middle of engineering
- routing room has be turned into teg
- owl room has been turned into bee room
- grav gen in (former) shuttle bay
- tons of conveyer belts in disposals (these don't lead to routing systems)
- disposal pipes leading from the kitchen to sec (to feed prisoners, it is locked behind a windoor to prevent chef from breaking into sec)
- disposal pipes from botany to the freezer
- disposal pipes from kitchen to the freezer
- disposal pipe from atmos to engineering
- disposal pipes that dont lead to disposals are color-coded
- the animal ranch is now under service doors, allowing more service roles to work with the animals
- clown and mime now have a nice room
- gambling table
- cargo dock has been pushed outward to allow cargo to dock
- toxins lab has been turned into artifact lab
- sec has their own evac pod (for prisoners mostly)
- moved robotics to sci, turned chem to med

### other things to note
- no library or librarian job
- the routing system has mostly been remove due to the fact we do not have mass launchers
- the routers on the far edges of the station have been removed because they would block shuttle access for cargo, salvage, and other shuttles trying to fly to the station
- the doors in security that look like normal glass doors have had their security access removed to allow people to emag to the brig without needing to recharge 
- ~~With the solar panels, Singo, AME, and TEG, the power is superfluous~~ Singo can no longer solo, the amount of rad collectors has been reduced from 6 to 4
- no lawyer room
- the cartridge is the reporter's room is for news, not logprobe
Please give feedback, ~~additionally I may have to add Cog to some files to get it in the map rotation but im not sure which ones those are, please tell me~~

## Media

**Cog**
Cog-0
**Wode evac shuttle**
image
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Cog, a new midpop map based on Cogmap from ss13

### CODE REVIEW

**Comment by deathride58** [comment]
Coggers

**Comment by Spessmann** [comment]
that was quick

**Comment by Pumkin69** [comment]
okay unironically triple layer armory and/or airlock it
remove the pipes in the teg room
add mapped trans pride cloak :godo:
and make all the beds in medical med beds and you have a good map

**Comment by Djungelskog2** [comment]
I really like the main design, no issues from what I see there, but the decoration and aesthetics in the lengthy hallways both in and out of departments are lacking

**Comment by Djungelskog2** [comment]
I should add: some areas feel way larger and spacious than they should be, not that they necessarily need to be shrunk but that they could have more physical objects, deco or props to make it feel and look better

**Comment by Djungelskog2** [comment]
image_2024-08-10_152909339
image_2024-08-10_152925784
image
image_2024-08-10_153047101
image_2024-08-10_153059568
These are my only notable nitpicks, They just feel rather empty, either due to their size or lack of deco

**Comment by Ilya246** [comment]
that evac shuttle looks like a real easy target for mass murder via bombing

**Comment by Krovotushka** [comment]
This atmos looks packed Atmos but

**Comment by Cojoke-dot** [comment]
Holy shit this hit me with memories...

image

4 SecTechs, 2 only blocked by one door of security? I uh... think the 2 at the front of sec seem excessive and insecure.

Maybe throw some vending machines, lockers, and chairs up here, seems like there is a good space for it too
image

Logger pro cartridge?
image

Maybe you should just turn this into a normal front desk? I see you kinda converted the Telesci room but this just looks silly.
image

There needs to be some magic mirrors somewhere, maybe in the barbershop?
image

This area looks horrid to work in to be honest, and I'm not sure if you're going to be able to get the ship parts out of there without having to deal with them bumping into doors and one-tile-wide spaces. Maybe merge the 2 rooms, remove the ship part stuff, move the gas tank inside, and flaten that wall. Knock the northern wall up for the storage room into space a little more so you don't bump into the PA every time you enter that room.
image

The Rad shields on the engi windows are pointless with plasma glass, it blocks all rads anyways. Maybe swap it for normal glass or remove the rad shutters(I would say make them normal glass for consistency with fland).

**Comment by Hrosts** [comment]
What I noticed is that there is no meteor protection anywhere except the telecoms satellite.

**Comment by maximus-not** [comment]
ngl 2X3 burn chamber ooof requesting 3X3 plzzzz

**Comment by Spessmann** [comment]
I will make changes later today

**Comment by Spessmann** [comment]
I dont know if the bot shows images for updated maps so ill get one

**Comment by Emisse** [comment]
i will review tonight or tomorrow

**Comment by Spessmann** [comment]
posting image in comments as well as pr
Cog-0

**Comment by lzk228** [comment]
btw, there is no need to add cl about adding evac shuttle, just simple
`- add: Added Cog, a new midpop map based on Cogmap from ss13`
would be enough

**Comment by Spessmann** [comment]
another day another image
Cog-0

**Comment by Spessmann** [comment]
im going to just post the updated images in the pr description

**Comment by BasedUser** [comment]
no misc printers/mechcomp replacement devices, time to die due to nukie armory

**Comment by juliangiebel** [comment]
This **mapping** pr contains code changes, which prevents the map server from adding the map to the viewer
ezgif-5-9e00418563

**Pull request merged**
