### PR TITLE
Remove the network tab

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Removes the network tab from options

## Why / Balance

It is useless and bloat, if a user needs to change these settings they are free to modify their cvars manually via the clientconfig.toml file or via the cvar command.

We dont want users to willy-nilly change these cause "oh no im lagging and i was told to turn off client prediction in #help"

## Technical details

Remove network tab

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Pspritechologist** [comment]
Add a warning not to change them then? I'm always going to be against removing settings menus because "We don't want people changing them." I totally understand that client-side prediction isn't something that should be played with (especially since turning it off literally just breaks some things iirc), but perhaps just remove that one setting for now until it works better?
People can toy with things and see what breaks, I don't think that's a problem. Add a reset button to the settings menu, that'll solve more issues than removing it :P

**Comment by PJB3005** [comment]
Actually here's the more likely scenario:

1. User messes with random settings they don't understand.
2. User forgets they did this.
3. Game acts up and user doesn't realize this is their fault.
4. Now it's our problem.

Before we fixed invalid keybinds.yml causing the game to not start, people would dead-ass modify their keybinds, break the file, and then not realize the cause and effect and ask for help for why their game doesn't start. Now imagine this for subtle performance parameters like networking.

**Comment by EmoGarbage404** [comment]
oh boy look at me im removing the game im removing content

**Comment by VasilisThePikachu** [comment]
> Wouldn't it be better to just have some big overlay blocking the buttons saying something along the lines of "Mess with this and we won't help you if you break stuff"? With a button to dismiss it.
> 
> Or if you really wanted to stop people from touching it, locking it behind a value you have to manually set by editing your config file

I really don't see a reason for players to touch this in the first place. Those who do can just edit their cvar. Servers that want their players to have access to this menu can just revert the pr. The cvars still exist.

**Comment by PJB3005** [comment]
> Or if you really wanted to stop people from touching it, locking it behind a value you have to manually set by editing your config file

That would be fine

**Comment by Jezithyr** [comment]
> Actually here's the more likely scenario:
> 
>     1. User messes with random settings they don't understand.
> 
>     2. User forgets they did this.
> 
>     3. Game acts up and user doesn't realize this is their fault.
> 
>     4. Now it's our problem.
> 
> 
> Before we fixed invalid keybinds.yml causing the game to not start, people would dead-ass modify their keybinds, break the file, and then not realize the cause and effect and ask for help for why their game doesn't start. Now imagine this for subtle performance parameters like networking.

Or people write "guides" for how to "optimize" the game like they do in counterstrike and people just copy those values without knowing what they do and end up causing clientside issues that we now can't reproduce because they changed prediction settings without knowing what they are doing.

This happens in alot of valve games where people just use console commands to "optimize their networking" and half the fucking commands are placebo's since they got removed when CSGO updated to CS2

**Comment by Jezithyr** [comment]
There is zero reason for players to be messing around with prediction settings *unless they understand what they are doing* and in that case *they should already understand how CVARs work*, putting developer settings that can very easily completely break the user experience in the user-facing options menu is a tremendously stupid idea, even if you lock them behind some sort of UI "toggle".

A UI toggle does not work to prevent users from just clicking "Ok" like they do when they get a EULA pop-up and changing the settings anyways without knowing what they are doing.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
What the hell, the whole tab? Being able to actually turn on client prediction is the whole reason why I’m still playing this game and didn’t stop after an hour, the removal of this option is… confusing at best.
All this does is raise the bar to entry for people who don’t live in the same country as a server, and will actively harm the new player experience.
Like, actually revert this.

**Comment by EmoGarbage404** [comment]
> Being able to actually turn on client prediction is the whole reason why I’m still playing this game and didn’t stop after an hour, 

its on by default 14head

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
thank god, but then the other issue is the problem, if the client prediction is being "ass" for that player and while rare, it can be. 
then they are left with no way to turn it off without asking in the discord as to how

**Comment by EmoGarbage404** [comment]
turning off the prediction isn't going to fix any bugs and is instead going to drastically degrade the quality of the game. there's no situation in which players should turn off prediction (i'm fairly sure it outright breaks several things) and anyone who has been telling people to do so or anyone who claims that it 'fixes' something are mistaken.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I'll take your word for it, still the removal of a whole settings tab is a little insane, and sorry to "come out swinging",
I saw what i thought was, maybe one of the worst changes to ever be done and acted with more passion than maybe i should have.

If it truly will have no impact on current and new players, then sure seems fine

**Comment by mirrorcult** [comment]
please read the PR and actually have basic understanding of the game before commenting on them next time

**Comment by Emisse** [comment]
squeeze my kidney like a balloon

**Comment by Jezithyr** [comment]
> What the hell, the whole tab? Being able to actually turn on client prediction is the whole reason why I’m still playing this game and didn’t stop after an hour, the removal of this option is… confusing at best. All this does is raise the bar to entry for people who don’t live in the same country as a server, and will actively harm the new player experience. Like, actually revert this.

This is precisely why it's being removed. *Prediction is ON and setup with decent values by default*, 9/10 there is no reason for a player to touch prediction and chances are if they do need to, they're already talking with someone who can help them set the CVARs correctly. Networking and prediction values can still be changed, but since they are not the sort of thing that the average player should be playing around with, they shouldn't be shown as a menu option which is why they are limited to CVARs now.

**Pull request merged**
