### PR TITLE
Adds a holy book

### PR DESCRIPTION
**Pull request by exp111**
Also called Bible

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
What does it do

**Comment by exp111** [comment]
It can currently only store items and you can select a style. Haven't thought about other uses yet

**Comment by SweptWasTaken** [comment]
>Haven't thought about other uses yet

Maybe make it readable first

**Comment by TheChosenEvilOne** [comment]
It should have a chance to heal if a chaplain uses it on someone.

**Comment by Git-Nivrak** [comment]
It has a 60% chance to heal and 40% chance to deal 10 brain damage (Only if you're a chaplin) if you're not a chaplin it will cause brain damage either way (only to you though) and it can also bless water (regardless if you're a chaplin)
At least in ss13

**Comment by metalgearsloth** [comment]
@exp111 were you coming back to this soon? If not I'll close in a week.

**Comment by exp111** [comment]
Currently busy with irl stuff so you can close it

**Pull request closed without merging**
