### PR TITLE
fix railing vaulting

### PR DESCRIPTION
**Pull request by Fishfish458**
## About the PR 

This fixes  railing vaulting

in the flaps pr, vaulting was changed from using the smallImpassable collision layer to using VaultImpassable

railing

### CODE REVIEW

**Comment by metalgearsloth** [comment]
> in the flaps pr, vaulting was changed from using the smallImpassable collision layer to using VaultImpassable

Won't this break a lot of things? Apparently cloners are colliding with players again. SmallImpassable is what it should be doing or maybe Impassable.

**Comment by Fishfish458** [comment]
As far as breaking anything, vault impassable is basically always used in tandem with smallimpassable and impassable so nobody should be getting anywhere they shouldn't as far as i've tested.

I'm still going through and trying to test out if there's a better solution that will fix these, If you do have a good example for what vaultimpassable is supposed to represent it's been hard to find.

**Comment by Fishfish458** [comment]
On this, I've gone through and tried a lot of different ways but I can't find a good way of separating out larger sized items such as closets from mobs unless there is another collision layer at work.

I'm still pretty confident in that vault impassable is always treated as a step down from impassable and in all the uses i've seen it generally uses both.

I figure that the options are:
1. I can revert all the collision changes from previous pr, use smallimpassable for vaulting and flaps can use mobImpassable
2. Make changes to the cloner and railing to put them in line with the other changes.

That's all I can come up with, I'm not trying to rock the boat or anything, I'm fine with whatever's best.

**Comment by metalgearsloth** [comment]
> That's all I can come up with, I'm not trying to rock the boat or anything, I'm fine with whatever's best.

More and more everyday I get motivated to just refactor things to have just the 1 layer. Some stuff is still a mess so it's probably fine for now.

**Pull request merged**
