### PR TITLE
Adds slottable Encryption Keys

### PR DESCRIPTION
**Pull request by Mirino97**
## About the PR

Adds a range of encryption keys and the ability to slot them into a headset.

## FULL DISCLAIMER:
I am shit at code. I am just shit in general. 
Therefore, I fully expect this PR to be extra shit and for a maintainer to look at it for 5 seconds and just go "fuck no".
I mainly did this one as a training exercise for myself since I have no ECS/game-dev/C# experience and am honestly dumbfounded I managed to fluke my way into a working implementation, no matter how simple.
I'm PR'ing cuz someone told me "couldn't hurt to try". Sorry if they're wrong!

**Screenshots**

keysmade

**Changelog**
add: Added encryption keys. You can now insert them into headsets! (They do nothing and you can't get one atm)

### CODE REVIEW

**Comment by Mirino97** [comment]
Forgot to mention I do plan to follow up with the actual departmental channels.
Just thought it'd be a good idea to compartmentalize.

**Comment by metalgearsloth** [comment]
Repo deleted?

**Comment by Mirino97** [comment]
> Repo deleted?
> 
> Or is github trolling me.

OH SHIT MY DUDE, MY BAD.
No I totally deleted it due to a bug I was having (that was completely unrelated to what I changed, but since I lack experience, seemed like a good idea). Turns out it wasn't my code.
Since mirrorcult is working on a radio refactor, I thought it prudent to just wait (and forgot to close the PR, sorry again.)
I can re-PR it if you think it's worth anyone's time!

**Comment by metalgearsloth** [comment]
Did you ping her on it or did you see the draft PR?

The code looked mostly okay, it's just as a new contributor I'd prefer if the whole thing was there before merging.

**Comment by Mirino97** [comment]
> Did you ping her on it or did you see the draft PR?
> 
> The code looked mostly okay, it's just as a new contributor I'd prefer if the whole thing was there before merging.

I did both. I saw the draft PR and asked her about it, but I didn't go into details. Just asked if she was still working on it and went "Ah ok, I'll wait then".

I'm actually surprised you found the code to be mostly ok. This fills me with confidence.
I assume by "You'd prefer the whole thing was there before merging" you mean "check with mirrorcult specifically"?

**Comment by metalgearsloth** [comment]
Nah it's more that it's kinda placeholder right now but from my perspective there's no guarantee you'd finish it.

If she's still working on it we can just close it for now and re-open when she's done.

The main 2 things I saw (because for whatever reason github isn't letting me add comments) is
1. You added a new filetype to gitignore which is a bit suss
2. You never added the encryption key to the itemslot in the InteractUsingEvent
3. For sprites unless you need it you'll want to add "netsync: false" to it.

**Comment by Mirino97** [comment]
Aaaaaaah okay, gotcha! You're right, this is placeholder as they have... no use whatsoever. They were not added to all headsets on game init, nor did they *do* anything. This was just "adding the item and half-inserting it correctly."


To address your concerns:
1: Fuck me, dude. Yeah, I completely forgot about this. I was trying to add the .bak exclusion because it's a file generated by notepad++ when you don't save your progress. Instead of adding it globally to my machine, I added it to the repo itself. Will correct in future PR's!
2: D'oh! Thanks for pointing it out. I'll fix it too.
3: Gooooootcha. I know what you're talking about, so will add whenever I re-PR this.

All in all, I'm surprised this was even passable by a maintainer's standards. 
Thank you for your time reviewing it! You can close it while I wait for the radio rework, and when that's done, I'll PR it again.
Cheerio!

**Pull request closed without merging**
