### PR TITLE
Short and fat lizard tail

### PR DESCRIPTION
**Pull request by pigeonpeas**
## About the PR
Adds a short tail for the reptilian species

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image
image
image
image

## Breaking changes

**Changelog**

:cl:
- add: Lizards can optionally have short tails now.

### CODE REVIEW

**Comment by pigeonpeas** [comment]
heres to hoping i didnt fuck up something important

**Comment by UbaserB** [comment]
CL should be something like "add: Lizards can optionally have short tails now."

**Comment by pigeonpeas** [comment]
> CL should be something like "add: Lizards can optionally have short tails now."

hows this look

**Comment by UbaserB** [comment]
> > CL should be something like "add: Lizards can optionally have short tails now."
> 
> hows this look

the "add" is not part of it. So it's gramatically incorrect

**Comment by pigeonpeas** [comment]
> > > CL should be something like "add: Lizards can optionally have short tails now."
> > 
> > 
> > hows this look
> 
> the "add" is not part of it. So it's gramatically incorrect

graaaah im just stealing what you wrote then

**Comment by Brandon-Huu** [comment]
Doesn't "can" already imply having an option.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
I do not like this sprite, it feels very one-dimensional and looks more like a flap from behind than a tail.

**Comment by pigeonpeas** [comment]
> I do not like this sprite, it feels very one-dimensional and looks more like a flap from behind than a tail.

is there anything specific you thing i could add or change to make it better?

**Comment by TemporalOroboros** [comment]
???

**Comment by pigeonpeas** [comment]
sorry i just dont know if i can make it any better. im not good at spriting

**Comment by UbaserB** [comment]
i can try revive it maybe, ill figure out exactly whats wrong about ut

**Pull request closed without merging**
