### PR TITLE
Ports some /tg/ + /vg/ space ambience

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Does what it says on the tin, adds spookyspace1.ogg & spookyspace2.ogg from /vg/station, and adds ambispace2 from /tg/station.

## Why / Balance
I've wanted to do this for a while, and now that we're getting more space gameplay with the salv rework, I felt like it was an appropriate time. More space ambience will also probably do wonders for atmosphere in general.

~~Starlight and Drifting, on the other hand, are fine songs, but when you have all 3 space music tracks together using similar instruments and going for basically the same thing, they really mush together in your mind and really get on my nerves when exploring space. I probably couldn't tell you which song is which for the life of me.
Hell, before making this PR, I only thought there were two songs instead of three!~~
This PR no longer removes these, I'll possibly come back to see if I still want to remove them separately later.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Rainbeon** [comment]
Man I'm really gonna miss Starlight, always felt the most iconic to me of the space ambience songs

**Comment by Unbelievable-Salmon** [comment]
Getting rid of Starlight is a huge loss. I'll miss Drifting too, but Starlight even more so.

**Comment by NkoKirkto** [comment]
Cant you just leave them in the pool so that it is random wich Ambiant song you get? I mean it feels like your loosing a part of SS14 history here

**Comment by Flareguy** [comment]
Added back the old space music since I just want the space ambience in the game right now.
I might revisit removing those later, though.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
