### PR TITLE
senior security jumpskirt resprite and security jumpskirt sprite minor fix

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## Why / Balance
old senior jumpskirt had the old security jumpskirt style as it was not respirted in #25269

also changes a few things on the normal security jumpskirt, it had an extra armband where it shouldn't have and the skirt part was too far forward

the skirt on the old sprite (the skirt part is too far):
image

new sprite skirt:
image

## Media
image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by InfinityPandaRed** [comment]
YES SIR

**Review by Flareguy — COMMENTED** [review]
You forgot the sleeve asymmetry on the new sec jumpskirt sprite. This looks fine otherwise, though.

**Review by Flareguy — CHANGES_REQUESTED** [review]
Pretend the above review was requesting changes. I forgot to set it to that

**Comment by Dutch-VanDerLinde** [comment]
> You forgot the sleeve asymmetry on the new sec jumpskirt sprite. This looks fine otherwise, though.

wdym, i don't see anything wrong with it
the part above the skirt looks exactly the same as the sec jumpsuit

**Comment by Flareguy** [comment]
> > You forgot the sleeve asymmetry on the new sec jumpskirt sprite. This looks fine otherwise, though.
> 
> wdym, i don't see anything wrong with it the part above the skirt looks exactly the same as the sec jumpsuit

The armband is supposed to be asymetrical (only appearing on one arm,) yet it appears on both east and west rotations.

**Comment by Dutch-VanDerLinde** [comment]
> > > You forgot the sleeve asymmetry on the new sec jumpskirt sprite. This looks fine otherwise, though.
> > 
> > 
> > wdym, i don't see anything wrong with it the part above the skirt looks exactly the same as the sec jumpsuit
> 
> The armband is supposed to be asymetrical (only appearing on one arm,) yet it appears on both east and west rotations.

image

i fixed that already i think

**Review by Flareguy — APPROVED** [review]

**Pull request merged**
