### PR TITLE
Four 'new' signs

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

Added four signs that are from /tg/.

## Why / Balance

Mostly to allow an easier time finding the custodian/janitor, psychologist or lawyer office/court.

## Technical details

N/A

## Media

ss (2023-10-06 at 06 32 29)
"Cust" sign was updated to the following
273296843-08805a32-2456-4097-b2a7-f1e76e6e8e65

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Mostly dependant on mappers adding it to their map so no changelog

### CODE REVIEW

**Comment by Partmedia** [comment]
We don't refer to the janitor in-game as "custodian" so this abbreviation might be a bit confusing, especially for non-native speakers. This would be better changed to "JANI", in which case you should double check this doesn't duplicate an existing sprite.

**Comment by IamVelcroboy** [comment]
>  in which case you should double check this doesn't duplicate an existing sprite.

We don't have a poster-sized Jani yet, and we could really use one!

**Comment by forgotmyotheraccount** [comment]
jani

5000 years in photoshop

**Comment by UbaserB** [comment]
wooo signs my beloved

**Pull request merged**
