### PR TITLE
Station Map window edges

### LINKED ISSUE #15998: Station map control could really use some margins
## Description

the way it cuts off at the edge looks really strange. just some small margins around the control would look nice

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Station Maps now have proper edges like the Crew Monitor and Power Monitor. 
All of these windows are also no longer resizable. This never actually did anything useful, just increased the blank space around the edges and potentially annoyed the player who grabbed it too close to the edge when trying to move it

Fixes #15998

## Media

Before
Screenshot from 2024-01-13 12-54-36

After
image

[Screenshot from 2024-01-13 12-53-50](https://github.com/space-wizards/space-station-14/assets/35878406/f8c8577c-44c6-469d-8226-e343b31d1138)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: The empty space around Map UI window edges is no longer resizable.
- fix: Station Map ui now has proper edges.

### CODE REVIEW

**Review by juliangiebel — CHANGES_REQUESTED** [review]
Can you try setting the top and bottom margin so that they're even?

**Comment by Errant-4** [comment]
Do you mean something like this?
image
(The top gap is still a bit thicker but it proves to be a pain to fine-tune this)

**Comment by juliangiebel** [comment]
Yea, like that

**Comment by Errant-4** [comment]
> Yea, like that

Done, I have updated the image in the opening post

**Review by juliangiebel — APPROVED** [review]

**Pull request merged**
