### PR TITLE
add carp hardsuit for traitors

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
add valid version of carp suit to uplink
it protects from space and adds you to dragon faction

depends on #25154

## Why / Balance
it costs 4 tc since:
- eva suit is 2 tc
- carp suit has no slowdown, 3tc
- carp suit isnt valid, 5tc
- shiva and shit will probably start eating you since theyre just as well fooled as carp, 4tc

open to balancing

all carp get fooled but not sharkminnow they too smart

pro strat:
1. be lone salv
2. buy carp hardsuit
3. rescue lost fishies from wrecks
4. put them in a crate then let them out for budget fishops with lots of prep work
5. take off hood/helmet when theres a lone fish so people think since you being chased you couldnt have done it...

## Technical details
carp moved to Dragon faction since that makes sense and carp suit making you immune to ticks and what not doesnt make sense (so many mobs are simple hostile)
code is fairly simple but it handles the edge case of someone already in Dragon faction

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Added the Carp Hardsuit to the uplink which is spaceproof and makes carp think you are one of them.

### CODE REVIEW

**Comment by Kadeo64** [comment]
>be lone salv
>buy this
>only take dragon expeds
>free gamer loot

**Comment by Kadeo64** [comment]
also since it's a softsuit shouldn't the helmet be separate

**Comment by deltanedas** [comment]
its a onesie the hood just unfolds over your head and its airtight due to space magic

**Comment by K-Dynamic** [comment]
>buy carp hardsuit and emag
>emag biofabricator
>print carp cubes
>spray 20 cubes at once
>grind corpses and make more carps
>vibe with space ninja and call for space dragon
>vibe with space dragon

**Comment by deltanedas** [comment]
biofab is stupid expensive so you will need to also take over cargo or unsus ask them for 5 stacks of plasma

**Comment by Kadeo64** [comment]
> biofab is stupid expensive so you will need to also take over cargo or unsus ask them for 5 stacks of plasma

can confirm biofab needs like 6 monkeys to make 1.7 kobolds

**Comment by Anzarot121** [comment]
Will this faction move fix the bug where normal dragon carp attack zombie carp, but they don't respond?

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by deltanedas** [comment]
open

**Pull request merged**
