### PR TITLE
Reorganize communications console UI

### PR DESCRIPTION
**Pull request by eoineoineoin**
## About the PR

Requires https://github.com/space-wizards/RobustToolbox/pull/4165 to get the fancy UI effects to work on non-default UI scales.

This reworks the UX of the communications console. The old UI looked like:

OldLayout

It had a number of behaviours which I thought were awkward:

The station alert level drop-down would change the level immediately after selecting a new level, without any confirmation. If you mis-clicked on a level, you have to wait for a timeout before you can correct it.

The "Call Emergency Shuttle" button also doubled as a "Recall Emergency Shuttle", which made it far too easy to click on the wrong thing (and have to wait for a timeout _and_ would reset any running timers on when the shuttle was arriving)

It also felt pretty cramped; the "Announce" and station alert-level buttons are real close together, making them feel like they should be linked, when they're not.

I've re-worked the layout; made the UI bigger (makes sense to me - Captain isn't going to send announcements on a teeny little blackberry; gotta have a big important console) which allowed for spacing the functions out into clearly separate sections. I also made it look a bit more like an IMPORTANT SPACE COMPUTER:

NewLayout

It still does all the same things, but hopefully improves the UX:

The station-alert-level dropdown now lets you select a level, but doesn't change it until you hit the "Set Station Status" button.

The call/recall button is now two buttons which are physically separated to prevent mis-clicks. The UI flows from top-to-bottom in order of what actions you might usually do (announce then change station level in one column, and call shuttle, shuttle info and recall shuttle in the second column) which I think feels better.

I added some highlights/shadows to the buttons (optionally!), to make the whole UI look less flat:

RegularButtonHighlight

And added a widget for a "panel mounted" effect, which again, makes the UI look less flat:

PanelMount

There's also an optional highlight/shadow effect on the square and anglerect panels.

These effects needed a new control, and while I was at it, I've added an element for this "bracket" pattern, which I've seen on the UI design Figma, but hasn't been implemented AFAICS:

BracketedContainer

Finally, the "shuttle arrriving in" timer has a pleasing blink:

https://github.com/space-wizards/space-station-14/assets/1676295/47933f32-a6ac-4e6c-ae3e-84f63a71c2bc

 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Cripes
- tweak: Communications console UI has been updated

### CODE REVIEW

**Comment by DogZeroX** [comment]
The beginning of intrinsic UIs??

**Comment by GeneralGaws** [comment]
Oh. My. God, looks crazy

**Comment by DogZeroX** [comment]
This needs discussion, preferably on discord.

**Comment by PJB3005** [comment]
Since we had a chat about this on Discord. My opinions on this:

* The pillow shading and rounded corners look bad. Even if it was consistent with the rest of the UI (which it isn't) it still wouldn't look good IMO.
* The layout doesn't make much sense. The communications console is a **console** so I expect it to have a display (up top in the UI) and a keyboard section with physical buttons. In this case, the physical emergency shuttle buttons (which I do admit look cool) would be in a row.
* Those emergency buttons should probably also be closer together IMO. Feels weird how distant and separated they are.

**Comment by deathride58** [comment]
Some UX thoughts from the perspective of a UX designer:

- The general idea is fairly respectable, and the layout is fairly neat! Though it could definitely use a bit of work.
- There's a *lot* of dead space there, with several instances of redundant information (notably, 75% of the alert level box, and the shuttle arriving indicator), information taking up more space than is probably necessary (again, the alert level box is a good example), and quite a lot of outright blank space (with the idea behind this PR being to turn the comms console UI into a diegetic interface, it'd probably be ideal for that completely blank space to instead contain *something,* such as a logo or something thematically appropriate.)
- The styling of the UI makes it fairly hard to tell at a glance that the emergency shuttle call/recall buttons are indeed buttons, especially since they use the same exact look as the shuttle arriving indicator.
- The announcement text box is looking pretty thin; it's very much worth keeping in mind that it's semi-common for players to end up writing a solid paragraph in that box, especially in more roleplay-focused environments. Thin textboxes almost always discourage longer writing, as they end up feeling quite cramped to type in.
- The arrival timer blinking does look fancy at a glance, but is something that could quite easily end up distracting.

**Comment by AJCM-git** [comment]
@eoineoineoin you coming back to this?

**Comment by eoineoineoin** [comment]
Yeah, I'd like to polish it up and get it in, but, in the interests of doing only one thing at a time, want to get https://github.com/space-wizards/space-station-14/pull/17135 in first, so I've converted this to a draft. If this is being completely vetoed, please close it, but I think there's some good stuff in here that can help the rest of the game UI.

**Comment by AJCM-git** [comment]
> @AJCM-git Yeah, I'd like to polish it up and get it in, but, in the interests of doing only one thing at a time, want to get #17135 in first, so I've converted this to a draft. If this is being completely vetoed, please close it, but I think there's some good stuff in here that can help the rest of the game UI.

I think an improvement to the comms console is wanted, these in specific not that much but they can improve with feedback and improving iterations

**Comment by graevy** [comment]
comms console serverside is also in need of a refactor imo. the station -> centcomm shuttle launch is buried in the update method rather than emergencyshuttlesystem / roundendsystem. i'm planning on tackling it after i'm done with the shuttle timers

**Comment by metalgearsloth** [comment]
@eoineoineoin are you still interested in working on this coz your uis are sex.

**Pull request closed without merging**
