### PR TITLE
Bleeding happens for longer, but the amount of damage it does is significantly reduced.

### PR DESCRIPTION
**Pull request by ThomasBestvina**
Resolves: #17021

## About the PR

The MaxBleedAmount has been reduced to 18.5, and the BleedReductionAmount has been reduced to 0.4. This makes the theoretical max time you will bleed (after you have stopped getting attacked) about 231.25 seconds, increased from the previous 200 seconds, in return however the amount of damage a player will take from bleeding has been reduced from 1, to 0.75, per update. In addition the BloodLossThreshold has been reduced from 0.9 to 0.85.

In theory this should make it so you have far more time to get medical attention, while taking less damage. This should also make it less likely that you will bleed when you get into a fight. (Assuming you win relatively cleanly).

So in total if I have numbers correct, you have about 30 more seconds to seek medical attention, while taking about 12% less damage in total. Please feel free to correct me on that, I am not entirely sure it is correct.

**Media**

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Added blood thinner to the water supply so bleeding hurts less.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Bleed chance needs to be dropped significantly but I need to try it ingame myself.

**Comment by metalgearsloth** [comment]
Specifically:
- Simplemobs pretty much can't get medical aid and so are guaranteed to just die after any fight.
- Forcing everyone to carry gauze + blood packs on them 24/7 is a bad meta.

**Comment by ThomasBestvina** [comment]
Will do.

**Comment by Aisu9** [comment]
pretty sure you are all forgetting about the "critical chance", you know that small % weapons have to straight up remove X% of their damage as blood. there is nothing as bleed chance, all weapon increase bleedrate depending on their damage type (slash damage being the higher at 20% of their damage as bleedrate)

**Comment by QuietlyWhisper** [comment]
You seem to only have changed the bloodloss damage of silicons unless I missed something. You'll want to do this via the base mob

**Comment by QuietlyWhisper** [comment]
also as painful as this sounds, some species have the value defined in their YML as well, which will override the base mob. You can (if I remember correctly) remove those lines so they just inherit from the base mob... I think the slime for example has the bloodloss damage defined as 1 for some reason

**Comment by ThomasBestvina** [comment]
NPCs/pets.yml:        Bloodloss:
NPCs/silicon.yml:        Bloodloss:
NPCs/simplemob.yml:        Bloodloss:
NPCs/slimes.yml:        Bloodloss:
Player/silicon.yml:        Bloodloss:
Species/base.yml:        Bloodloss:

This is every single one I will look through and change. If you have any specific requests just put them here... I guess? Honestley not that bad. Though I'm thinking slime could have a different blood loss value cos slime blood maybe depletes faster? Idk.

The ones grepped with a Bloodloss value not on this list are skeleton and NPCs/Player as that looked different.

**Comment by metalgearsloth** [comment]
Superceded by https://github.com/space-wizards/space-station-14/pull/17528 which in hindsight should've been frozen.

**Pull request closed without merging**
