### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Zumorica**
makes the readme awesome

### CODE REVIEW

**Comment by Mirino97** [comment]
Awesome!

**Review by metalgearsloth — APPROVED** [review]

**Comment by DrSmugleaf** [comment]
when has this game ever been awesome

**Review by moonheart08 — APPROVED** [review]

**Comment by metalgearsloth** [comment]
> when has this game ever been awesome

when hud refactor got merged

**Review by Just-a-Unity-Dev — APPROVED** [review]

**Comment by mirrorcult** [comment]
ASS 14

**Comment by moonheart08** [comment]
the PR count being above 100 is bothering me.

**Pull request closed without merging**
