### PR TITLE
Adds generic damage visualizer to the game

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR 

This PR adds a generic damage visualizer to the game. How to use it is pending rewrite due to several changes I made over the lifetime of this PR, look at `human.yml` and any of the window prototypes for examples of how to use this.

**Screenshots**

I don't have many useful screenshots, since I'm not that good at spriting, and this is more of a dynamic sprite layer change if anything. I can take video if needed, however, to showcase how this works.

**Changelog**

:cl:
- add:  NanoTrasen has cut the budget on maintaining how pretty things look on our stations. You may notice things around you slowly become more decrepit over time, for example, skin.

### CODE REVIEW

**Comment by mirrorcult** [comment]
based, would like if there were some example screenshots/video of it working

**Comment by DrSmugleaf** [comment]
> one, I don't know how actually useful this is

Very, we need it for windows and body parts for example.

**Comment by vulppine** [comment]
> > one, I don't know how actually useful this is
> 
> Very, we need it for windows and body parts for example.

actually, body parts were one of my primary reasons for doing this - you can't specifically target layers (at the moment!) and give them damage, though, instead the damage is applied evenly throughout the entire body according to the internal DamageSpecifier that the humanoid has

**Comment by DrSmugleaf** [comment]
> actually, body parts were one of my primary reasons for doing this - you can't specifically target layers (at the moment!) and give them damage, though, instead the damage is applied evenly throughout the entire body according to the internal DamageSpecifier that the humanoid has

I'm so sorry that you had to interact with body code, as one of the few people that have been in charge of it.
The sprites that we intended to use for damaged body parts are in #2022, if they are of any use to you.

**Comment by vulppine** [comment]
> I noticed a big flaw with this visualizer. It stores some per-entity data in itself. Visualizers are all meant to be flyweighted per prototype, meaning that one visualizer instance controls how many entities with the same prototype look. If you want to store some special per-entity appearance data, you should probably do so with `AppearanceComponent` data instead of storing it in the visualizer

sure - so anything that i assumed would've been stored as part of an instance of a visualizer (e.g., what sprite layers have been disabled on an entity, what the last damage threshold was for an entity) should instead be stored in the visualizer's internal data?

**Comment by vulppine** [comment]
i'll try to update this with comments to make it more clearer!

**Pull request merged**
