### PR TITLE
Mining Rebalance

### PR DESCRIPTION
**Pull request by EmoGarbage404**
### Magnet Asteroid Generation
Magnets asteroids had the general issue of feeling super empty. I partially reduced the total number of tiles so that they are a bit more compact and the other changes to ore amounts should hopefully make them feel a bit more full.

### Material Values
The main goal of this was twofold:
- for vgroid/expeds, decrease the overall amount of material as well as the density of ore as to encourage exploring more of the area.
- for magnets, increase the amount of ore to make the generation feel less empty as well as decrease the ore amounts themselves to make it multiple trips necessary.

The way i addressed this was by reducing the amount of refined materials a single piece of ores gives you (5 -> 1) as well as adjusting the amount of ore being spawned as needed. This should ideally give a more balanced amount of materials.

#### VGroid/Expeds
(expedition planets have the same values)

| Ore | Old Avg. Amount (ore chunks) | New Avg. Amount (ore chunks) | Old Avg. Amount (sheets) | New Avg. Amount (sheets) |
| -------- | -- | -- | -- | -- | 
| Iron | 3,750 | 1,875 | 18,750  | 1,875 | 
| Quartz | 3,750 | 1,875 | 18,750 | 1,875 |
| Coal | 3,750 | 1,500 | 18,750 | 1,500 |
| Salt | 1,875 | 1,000 | 9,375 | 1,000 |
| Gold | 1,500 | 800 | 7,500 | 800 |
| Silver | 1,500 | 800 | 7,500 | 800 |
| Plasma | 1,500 | 315 | 7,500 | 315 |
| Uranium | 1,500 | 315 | 7,500 | 315 |
| Bananium | 1,500 | 0 (magnet-only) | 7,500 | 0 (magnet-only) |
| Artifact Fragments | n/a | n/a | 450 | 100 |
| Diamond | 33.75 | 33.75 | 168.75 | 33.75 |

#### Magnet Asteroids
Magnets randomly populate ores 5 to 7 times.
A single population is displayed as "poor" in the UI.

| Ore | Old Avg. Amount (ore chunks) | New Avg. Amount (ore chunks) | Old Avg. Amount per 1 Population (sheets) | New Avg. Amount per 1 Population (sheets) |
| -------- | ------- | -- | -- | -- |
| Iron | 45 | 90 | 225 | 90 | 
| Quartz | 45 | 90 | 225 | 90 |
| Coal | 45 | 54 | 225  | 54 |
| Salt | 22.5 | 27 | 112.5 | 27 |
| Gold | 11.25 | 36 | 56.25 | 36 |
| Silver | 11.25 | 36 | 56.25 | 36 |
| Plasma | 11.25 | 27 | 56.25 | 27 |
| Uranium | 11.25 | 27 | 56.25 | 27 |
| Bananium | 11.25 | 40.5 | 56.25 | 40.5 |
| Artifact Fragments | n/a | n/a | 4.5 | 15 |
| Diamond | 2.25 | 0 (vgroid/exped-only) | 11.25 | 0 (vgroid/exped-only) |

## Why / Balance
Material supply is currently very out of wack. The overall amounts of every material are way too high, which makes meaningful economic gameplay (read: #30869) impossible due to the sheer volume you can acquire. On the other hand, the veins are so infrequent and dense in places that actually finding the ore becomes difficult. 

this isn't necessarily the most refined approach at this. My goal was just to reduce the pure amounts of all the materials to a level where it made sense. The VGroid should not be an infinite material generator and the magnet should be a easy-to-acquire reliable source of specific materials.

## Technical details

Changed DungeonConfigPrototype to have an intermediate class so i can modify it directly before generation instead of having to do stuff manually.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Reduced the amount of ore on the mining asteroid and expeditions.
- tweak: Increased the amount of ore on magnet asteroids.
- tweak: Each piece of ore now only has enough material to create 1 sheet.
- fix: The salvage magnet now accurately reports the contents of asteroids.

### CODE REVIEW

**Comment by coolsurf6** [comment]
Would it be possible to increase the variety of lower to higher range populations for specific ores? So for 3 different types of Asteroids that you cna pick from in the magnet menu, each will have one type of ore that has a really really good population level so there is a bit more variety? 

From what I've played with Salvager, the ore population amounts are so close to poor I'd always just go to the Vroid no matter what. If this is something you've already done then please disregard (maybe an example image of what it looks like now on the magnet menu would be nice to reference)

**Comment by EmoGarbage404** [comment]
> Would it be possible to increase the variety of lower to higher range populations for specific ores? So for 3 different types of Asteroids that you cna pick from in the magnet menu, each will have one type of ore that has a really really good population level so there is a bit more variety?
> 
> From what I've played with Salvager, the ore population amounts are so close to poor I'd always just go to the Vroid no matter what. If this is something you've already done then please disregard (maybe an example image of what it looks like now on the magnet menu would be nice to reference)

It might be worth looking into setting up asteroids to always contain some "moderate" level of an ore, but as it stands, i think the randomness is mostly effective at getting that done. It's worth playtesting these tweaked values (since both vgroid and magnets look vastly different) before messing with it anymore since they really are quite a big departure.

**Comment by coolsurf6** [comment]
> > Would it be possible to increase the variety of lower to higher range populations for specific ores? So for 3 different types of Asteroids that you cna pick from in the magnet menu, each will have one type of ore that has a really really good population level so there is a bit more variety?
> > 
> > From what I've played with Salvager, the ore population amounts are so close to poor I'd always just go to the Vroid no matter what. If this is something you've already done then please disregard (maybe an example image of what it looks like now on the magnet menu would be nice to reference)
> 
> It might be worth looking into setting up asteroids to always contain some "moderate" level of an ore, but as it stands, i think the randomness is mostly effective at getting that done. It's worth playtesting these tweaked values (since both vgroid and magnets look vastly different) before messing with it anymore since they really are quite a big departure. 

I really do like making magnet asteroids finally viable. The way I see it is if you can spend the same amount of time to get more than maybe 3 to 4 times the amount of ore for only one specific type (and maybe 1.5 to 2x of maybe 2 other random types). It might make it viable. 

Right now they seem like it is probably only worth getting for Bananium (which I love this change), or if the salavgers didn't get enough in the first 15 minutes of mining.

**Comment by EmoGarbage404** [comment]
the vgroid is still superior to the magnet in terms of raw material amounts but the balancing factor is going to be mobs and difficult. So at roundstart when you're weaker, magnet is going to be more appealing since it's low-risk.

**Comment by coolsurf6** [comment]
Would it also be possible to make it so Diamonds can spawn on asteroids? The sheer happiness of a Salacer with gwts rewarded for actually looking at the asteroid section now upon seeing a high population diamond asteroid would be really nice. 

Obviously still incredibly rare. But could be rewarding for when a salvager returns to start checking the magnet more.

**Review by metalgearsloth — APPROVED** [review]
Based.

**Pull request merged**
