### PR TITLE
Remove mimic rule pending rework

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

comment out MimicVendorRule from events entity table

## Why / Balance

right now mimic has very low impact on the round and here is a small more detailed list
- just replaces a vendor and gives nothing instead (might be annoying with some rare vendors)
- has sprite of default robust softdrinks
- has no loot
- does nothing

with all this i think it's better to remove the rule until someone will rework it

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Mimic vendor event was removed pending rework.

### CODE REVIEW

**Comment by muburu** [comment]
but it's rare funny useless thing..... isn't there some beauty in that????

**Comment by Everturning** [comment]
why can't you just do the rework and then merge that rather than remove it completely "pending" nothing

**Comment by lzk228** [comment]
wyci
i don't know how to code

**Comment by cohanna** [comment]
instead of removing em how about restricting it to targeting drinks/food/games/clothes vendors (aka non essential/rare) until more functionality is added?

**Comment by Cadunkus** [comment]
> but it's rare funny useless thing..... isn't there some beauty in that????

"Rare" is a stretch. Seems like every other soda machine starts scooting around doing absolutely nothing.

**Comment by slarticodefast** [comment]
I brought this up for maintainer discussion and the agreement was that while this event has almost no impact on the round, we can keep it for now as a fun little easter egg. I will open an issue for it to be improved.

**Pull request closed without merging**
