### PR TITLE
Borgs can no longer see mindshield + AI can no longer toggle off seeing job icons

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Cause it was never meant to be. :(

## Why / Balance

AI has no reason to toggle off seeing jobs. It just clogs up the action menu. Should be reverted once the hud actually does more than just job icons (if ever).

## Technical details

Removed the action for AI job icon toggle and removed the mind shield seeing component for borgs.

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: AI can no longer toggle seeing jobs off. 
- fix: Borgs can no longer see mindshield status.

### CODE REVIEW

**Comment by lzk228** [comment]
can AI still see mindshield?

**Comment by ScarKy0** [comment]
> can AI still see mindshield?

AI could never see mindshields

**Review by slarticodefast — APPROVED** [review]
Tested in-game and works as intended.
Thanks for the PR!

**Comment by chromiumboy** [comment]
Yep, looks good, thanks!

**Pull request merged**
