### PR TITLE
Revert "Give cap door remote his access"

### PR DESCRIPTION
**Pull request by metalgearsloth**
Reverts space-wizards/space-station-14#26378

Apparently it's unintended or smth check admin chat.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
post the snippets nerd

**Comment by metalgearsloth** [comment]
image

**Comment by Emisse** [comment]
to clarify, getting AA cap card is definitely the best thing you could get from a kill. but duplicating it always requires another item/machine like agent id or id card machine. this kinda removes that whole facet of it since you just get le AA remote which i never wanted

**Comment by Baptr0b0t** [comment]
> to clarify, getting AA cap card is definitely the best thing you could get from a kill. but duplicating it always requires another item/machine like agent id or id card machine. this kinda removes that whole facet of it since you just get le AA remote which i never wanted
@Emisse 
I understand your point of view, however I find that the captain not being able to use the remote controller on the department doors makes it completely useless. 
If I create a PR allowing certain door remote work with the ID, like the default one without access and the command ? that would be better balanced ?
Or do we have to make the command door remote useless and be the least powerful than the others ? Because few people can access the bridge and bolt it is almost useless.

**Pull request merged**
