### PR TITLE
Rat King Resprite

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changed the rat king sprite, as the older one was all over the place

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Changed the rat king sprite, boss says!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
The old sprite shows its age, but I'm not a fan of this new one either. The tan-colored hands and legs look very strange. The large tooth also looks very cartoony and not very good. Lastly, the overall body shape is still very stiff and feels not very organic looking.

**Comment by Alekshhh** [comment]
the hands and legs are more reminiscent of real rats and add a bit of variety to the whole body, the large tooth is pretty much the same as the old one with small changes, don't see the issue with it looking a little silly given the nature of the lad, and I like the body being stiff like it is in the original, since it looks sort of mutated in a way like I'd assume this large rat is

**Comment by moonheart08** [comment]
I think this looks pretty good.

**Comment by PixelTheKermit** [comment]
I think it's quite good

**Comment by brainfood1183** [comment]
I think its an improvement over the old sprite, gives the rat king a bit more character. I do think however that the pink color on the hands and feet is to bright and should be toned down and not as bright as the ears. The rats themselves have a darker pink on their feet.

**Comment by Alekshhh** [comment]
I based the palette off the original colors, but if it would look good with darker pink I can do that

**Comment by ZoldorfTheWizard** [comment]
into content with ye

**Pull request merged**
