### PR TITLE
tweak(lost_cargo): Reorganize shuttle atmos

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Added a vent to cockpit.
Added a waste network to vent out unwanted gasses.
Added a air alarm.
Added air sensors

## Why / Balance

Resolves https://github.com/space-wizards/space-station-14/issues/30063

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**AFTER**
image

By IProduceWidgets 

image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
I'm guessing I should remove the filters and just make the waste network a straight pipe out of the shuttle

**Comment by Brandon-Huu** [comment]
There are two filters under the conveyor belts.
They filter out nitrogen and oxygen and return it to the vent pipes

**Comment by IProduceWidgets** [comment]
image

**Comment by Brandon-Huu** [comment]
Got homework due in 5 hours, will come back to this later... maybe

**Comment by Brandon-Huu** [comment]
> image

thank you!

**Comment by deltanedas** [comment]
waste doesnt have oxygen or nitrogen without player intervention

**Comment by Brandon-Huu** [comment]
> image

How does the window below the SMES work?
When I save the shuttle it says it's not anchored

https://github.com/space-wizards/space-station-14/pull/30310/files#diff-ac27255241036456463f3b8b7d17784961bf3e4ec131a192394e831deb2608eeR1582-R1590

**Comment by Brandon-Huu** [comment]
> > image
> 
> How does the window below the SMES work? When I save the shuttle it says it's not anchored
> 
> https://github.com/space-wizards/space-station-14/pull/30310/files#diff-ac27255241036456463f3b8b7d17784961bf3e4ec131a192394e831deb2608eeR1582-R1590
> 
> image

Maybe disregard this

**Comment by Brandon-Huu** [comment]
It might be a few days before I can actually finish this.

**Pull request closed without merging**
