### PR TITLE
Firelock improvements part 1

### LINKED ISSUE #25788: Firelocks act like they can be opened when they require a crowbar
## Description

Previously when you tried to open a firelock that was unpowered, it would make no sound indicating you had to crowbar it. If you try to open a firelock now, it will make a "fwoosh" sound as if it was being opened, and you will be able to move into it for a fraction of second, but it will never open because it requires a crowbar.

**Reproduction**

1. Unpower a firelock door
2. Try to spam it open with E or click it
3. Actually open it with a crowbar instead

**Screenshots**

**Additional context**

### LINKED ISSUE #25975: Firelocks are not properly predicted
## Description

Firelocks are not properly predicted at all. 
All the logic is on the server. 
This causes issues like #25788.

### PR DESCRIPTION
**Pull request by nikthechampiongr**
fixes #25788 
fixes #25975 

## About the PR

These are some basic improvements to firelocks, I'll make more but I was advised to split prs.

This PR makes it so: 
- Firelocks can be pried by hand at half the speed of using a crowbar.
- As a side-effect of the above, the pryingsystem was modified to take a custom modifier for PryUnpowered doors stored in the component instead of being hardcoded to 10% speed. 
- Firelocks no longer have broken prediction.
- Firelocks will not be closed due to a hazardous environment for 2 seconds after you have pried them open.

## Why / Balance

Firelocks often end up obstructing players to an extreme degree, being unbelievably frustrating to deal with. Making them pryable by hand alleviates some of this frustration by not stranding you in an deadly environment if you are unlucky enough to not have a crowbar. Unlike normal airlocks, firelocks can be pried by hand even when powered.

Prediction stuff is self explanatory.

## Technical details

PryUnpowered doors can now provide a custom modifiers with the PryUnpoweredComponent for prying with your hands.

I moved as much stuff as I could to shared. One thing I could not move is the atmos checks that firelocks still do. Instead, to predict this properly 2 bools are set to indicate whether the firelock is locked due to hazardous temperatures or atmosphere which are synced to the client. Additionally this allows me to remove atmosphere checks when determining whether a firelock can be opened, and whenever visuals are updated since now they can just check the bool.

For the firelocks not closing I just store a default cooldown on the firelock and then store a timespan whenever the firelock is pried open and then check it on the EmergencyPressureStop function.

I originally wanted to make firelocks fully depend on fire alarms, however the following issues were raised with this:
- A lot of stations do not have adequate coverage of air alarms.
- Most shuttles do not have air alarms at all.

As such, firelocks still have magic sensors.

I additionally changed the update interval to first be a proper constant, and that it is based on tickrate so that it gets slowed down/sped up by updating the tickrate on a server. This is good considering that it runs atmos checks on firelocks.

Lastly, firelocks have the unique property of being pryable by hand without having to be unpowered. This is because the check for this is done by the airlocksystem. Firelocks do not have the airlock component.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Firelocks can now be pried by hand.
- tweak: Firelocks will now not automatically close for 2 seconds after you pry them open.
- fix: Firelocks are now properly predicted.

### CODE REVIEW

**Comment by asperger-sind** [comment]
Does this fix firelock maintenance panels? If not, could you look into that while you're at it?

Firelock maint panels used to be broken for a while, showing up empty with no wires or contacts despite still being boltable, etc.

**Comment by nikthechampiongr** [comment]
> Does this fix firelock maintenance panels? If not, could you look into that while you're at it?
> 
> Firelock maint panels used to be broken for a while, showing up empty with no wires or contacts despite still being boltable, etc.

They have maintenance panels? I thought they intentionally could not be hacked. I could do this on a follow-up pr since I was advised to split stuff so it doesn't get too big.

**Comment by K-Dynamic** [comment]
> They have maintenance panels? I thought they intentionally could not be hacked. I could do this on a follow-up pr since I was advised to split stuff so it doesn't get too big.

If intentional it's a pain in the ass to deal with

You'd need a firelock remote and the firelock itself would still need power, making unbolting impossible if you're not atmos

**Comment by deltanedas** [comment]
game theory remove firelocks entirely

**Comment by nikthechampiongr** [comment]
Ah fuck, another pr was made before this that also deals with firelock prediction in a different way and I had no idea until now. I'll need to see if I can resolve this.

**Comment by nikthechampiongr** [comment]
I guess I'll wait for the other pr to get merged and then integrate the changes.

**Comment by nikthechampiongr** [comment]
Forgot to put this in draft because of that.

**Comment by nikthechampiongr** [comment]
Well that pr seems to be closed with no new one coming. Undrafting.

**Review by ShadowCommander — APPROVED** [review]

**Pull request merged**
