### PR TITLE
Recompress some lobby images to be under a 1mb

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

What it says on the tin

All is the same in terms of looks.

Behonker managed to get a lot of compression since it's only black and white, and it already has film grain, so the compression is barely noticeable.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Iamgoofball** [comment]
> I have added screenshots/videos to this PR showcasing its changes ingame, or this PR does not require an ingame showcase

Why did you check this box despite making a decidedly visual change?

**Comment by VasilisThePikachu** [comment]
> > I have added screenshots/videos to this PR showcasing its changes ingame, or this PR does not require an ingame showcase
> 
> Why did you check this box despite making a decidedly visual change?

Are you able to tell apart compression?

**Comment by VasilisThePikachu** [comment]
> What tool and settings were used to recompress them? It should probably be documented so it's the same for all future lobby art, since making changes like this to large files is gonna increase repo size and fetch time.

I used krita but most editors will probably work too.

What I did was import the image, save as webp and when it asks for the resolution. Save it with 100 quality and 99 quality. See which one is smallest in file size and upload that one.

In certain art pieces like the behonker. You can get away with 25% (in this case)

It pretty much is a "play around with the quality settings when saving webp and pick the lowest file size that looks the best"

**Comment by 0x6273** [comment]
> What it says on the tin

So you're telling me that "compression" did this? They're 2 different images! https://imgsli.com/MjkxNDYw

**Comment by 0x6273** [comment]
Reclaimer nuke looks fine I think: https://imgsli.com/MjkxNDYy
Behonker looks significantly worse, you need to tweak the quality settings so it doesn't look blurry/artifacty. https://imgsli.com/MjkxNDYz

**Comment by VasilisThePikachu** [comment]
I pers

> > What it says on the tin
> 
> So you're telling me that "compression" did this? They're 2 different images! [imgsli.com/MjkxNDYw](https://imgsli.com/MjkxNDYw)

Ok fine, for this one you are right. I assumed the one on the discord was the same image. No need to get sassy.

> Behonker looks significantly worse, you need to tweak the quality settings so it doesn't look blurry/artifacty
I personally don't see a difference.

**Comment by VasilisThePikachu** [comment]
And the comperison https://imgsli.com/MjkxNDY1

**Pull request merged**
