### PR TITLE
buff gas leak event

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
makes the gas leak event 4x as strong, and also adds water vapor to the list of leakable gases

## Why / Balance
currently the gas leak event can be ignored essentially every time, this makes it less ignorable and an actual issue
why water vapour? the fog is coming

## Media

untested

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Gas leak events are now 4 times as strong, and may leak water vapor. The fog is coming.

### CODE REVIEW

**Comment by SpeltIncorrectyl** [comment]
I literally have no idea what the gas event actually does, I hear the announcement and notice nothing.

**Comment by deltanedas** [comment]
it randomly adds a bad gas somewhere usually an escape pod or the cargo shuttle

**Comment by Hrosts** [comment]
The comment suggest the molesPerSecond parameters are kept low so that people have enough time to run away. As those parameters are now higher, it would be cool to make sure this is still the case... or not, if you want to be especially evil

**Comment by DexProcter** [comment]
Does gas still kill really fast if there is a high amount of pressure or I guess in general alot of gas in the area? I remember you would die almost instantly if you took one breath of high concentration of plasma....or maybe im confusing them with max pressure air tanks.

**Comment by potato1234x** [comment]
can you make it select multiple vents to pump from

**Pull request merged**
