### PR TITLE
Dehydrated Space Dragon

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
A new item has been added to the uplink at the fair cost of 12 telecrystals.
This item acts like a dehydrated space carp, but spawns an event space dragon instead that can spawn rifts and carp, the item has a 30 minute timer on it just like the hardbomb, to avoid early-round mass sabotage with it.
The dragon is **_not_** entirely aligned with the person who purchased them and can freely eat them after being ghost controlled. I've kept the petting for the AI since it'd be annoying to get instantly killed by the dragon you spawned when the ghost who takes control 4 seconds later would've teamed up with you.

## Why / Balance
Funny chaos causing item, upgrade to carps but less flexible because you can only get one and can't adjust how much tc you spend on it. You could get two if you kill renault though which gives a bit more incentive to protect the fox.

## Media
https://github.com/space-wizards/space-station-14/assets/140123969/48c5c92e-309d-43ec-9ab7-5ec4656cd585

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The syndicate has started selling dehydrated space dragons on their uplinks.

### CODE REVIEW

**Comment by deltanedas** [comment]
dragonops is real

**Comment by UbaserB** [comment]
is it syndicate only or nukies too? Personally i feel it should be locked out of nukies.

**Comment by Aisu9** [comment]
> is it syndicate only or nukies too? Personally i feel it should be locked out of nukies.

nukies doesn't need this, and if they ever have them make them unpettable

**Comment by Kadeo64** [comment]
I think having a full on rift spawning dragon is kinda busted for 25 TC. maybe something like 45 TC so it takes two traitors + renault/another traitor donating 5tc to spawn? Dragons may be weak but like, being able to control where it spawns means you can just spawn it outside armory and destroy all the guns before security can react

**Comment by KompaniLinge** [comment]
i think this is fun, especially seeing how underpowered dragons are, i dont really see the issue with this.

**Comment by Aisu9** [comment]
> i think this is fun, especially seeing how underpowered dragons are, i dont really see the issue with this. (except for maybe the eating ability.)

not anymore, they get a free stacking regen with each body in their stomach, pretty sure any body do so there is this too going for them and again the crew.

**Comment by KompaniLinge** [comment]
> > i think this is fun, especially seeing how underpowered dragons are, i dont really see the issue with this. (except for maybe the eating ability.)
> 
> not anymore, they get a free stacking regen with each body in their stomach, pretty sure any body do so there is this too going for them and again the crew.

I mean they're still piss easy to kill, i dealt with one like 3 days ago, it got swarmed and killed so fast it was barely even an issue. I was referring more to the ability to consume walls.

**Comment by vanilia123** [comment]
Great idea, hope we will see it in game. Dragon is after huge nerf (passive regen), so it makes sense to actually see them more often.

**Review by keronshb — CHANGES_REQUESTED** [review]
25 tc is extremely low to give a traitor the ability to summon an actual Midround Antagonist.

I'd like to understand why this is needed to be in an uplink.

**Comment by EmoGarbage404** [comment]
i don't really see a point in muddling the identity of the space dragon for what amounts to, at best, ineffective sabotage and throwaway TC. especially if the dragon gets buffed in the future (there are several PRs on way) it'll make the balance of this item fairly dubious. It's also worth considering people just buying it not as a meaningful distraction but just to cause a bunch of chaos early in the round.

**Comment by keronshb** [comment]
My concern here is that Traitors are not responsible for summoning midround antagonists, that's the job for the game to handle.

Apparently there's some interaction with the comms console that got through that should also be reviewed, but besides the point.

Imagine we had every antagonist from SS13 in - blob, wizard, nightmare, blood demon, etc. It would be extremely boring if traitors had the ability to summon any of these threats in the middle of a round, even when collaborating. It'll turn the traitor round into "what midround can we force this time?" Also it may not work with traitor objectives. Yeah a dragon could be a good opportunity to steal something, but should never be the norm. 

It takes away the experience of the round turning into something interesting.

**Comment by metalgearsloth** [comment]
Don't rely on the salvage one existing after vgroid.

**Comment by Emisse** [comment]
i dont think space dragon should be buyable, should stay midround

**Comment by EmoGarbage404** [comment]
Thank you for your contribution, but i will be closing the PR at this time. It's the general opinion that the space dragon should stay midround and not be introduced via syndicate. Existing expedition space dragons already are very placeholder-y and cause confusion between the dragon simplemob and the actual midround antagonist. It's a bit of an oversaturation to allow for potentially 2-3 dragons to appear in a single round. Furthermore, being able to so readily introduce the chaos of a dragon at a moments notice without any real preparation is likely to lead to frankly quite annoying abuses in situations like bar-rp or the emergency shuttle. 

Thank you for your time.

**Pull request closed without merging**
