### PR TITLE
adds a throngler plushie, and adds it to the grand lotto

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
There is now a plushie throngler, which can be found in the grand lottery. It has no combat value whatsoever, but it otherwise does the same things as the throngler (attacking fast, being huge, being funny). It has no damage, and is just a toy.

## Why / Balance
I jokingly suggested this idea in general and everyone there immediately latched on so I decided I might aswell make it since it is very little work and very funny.

## Technical details
Wrote yml, drank lemonade, made PR. Not much technical stuff to speak of here

## Media
https://github.com/user-attachments/assets/3d339e29-794d-4beb-bd67-f45098350628

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Breaks cargo techs hearts?
   (none)

**Changelog**

:cl:
- add: Added The Throngler (Plushie) to the grand lottery!!

### CODE REVIEW

**Comment by Plykiya** [comment]
give it... one stamina damage? like a worse toy hammer

**Comment by Moomoobeef** [comment]
I don't really think I should. I gave it the same rarity as other lottery plushes so it's not like its super rare like the OG throngler, and with how high the attack rate is that would be inviting idiots with autoclickers to use it to knock people on the floor

**Comment by mirrorcult** [comment]
Zased

**Comment by Killerqu00** [comment]
it should not have high attack speed with an attack sound, this will get abused a lot

**Comment by metalgearsloth** [comment]
> it should not have high attack speed with an attack sound, it's going to result in people audio spamming it to annoy people

I did think that but it's also incredibly rare so.

**Comment by Killerqu00** [comment]
> > it should not have high attack speed with an attack sound, it's going to result in people audio spamming it to annoy people
> 
> I did think that but it's also incredibly rare so.

it has the same chance as other plushies..

**Comment by Moomoobeef** [comment]
I am clearly a professional :clueless:

**Review by Dutch-VanDerLinde — APPROVED** [review]

**Comment by slarticodefast** [comment]
Tested it in-game, works as intended.
I would say make it as rare as the original throngler to counteract the potential for sound spamming and this PR should be good to merge.

**Comment by Moomoobeef** [comment]
whabam

**Comment by Ilya246** [comment]
what's next, L6 capgun? actually good idea possibly

**Comment by Moomoobeef** [comment]
that sounds like exactly what I should do next

**Comment by SlamBamActionman** [comment]
Finally I can cosplay an Animal Crossing villager.

Great and funny item, makes for a good joke.

**Review by slarticodefast — APPROVED** [review]

**Comment by Terraspark4941** [comment]
died 2024, born 2024
welcome back throngler

**Pull request merged**
