### PR TITLE
contrabandInventory Changes

### PR DESCRIPTION
**Pull request by AgentSmithRadio**
## About the PR
I've added contrabandInventory menus, the kind that you access by manipulating the "Manager" wire on vending machines, to nearly every vending machine SS14.

## Why / Balance
contrabandInventory is a woefully under-explored mechanic in SS14, and I wanted to take advantage if the world-building, flavour and gameplay opportunities available from populating these secret menus.

To note, beyond securing the equipment, hacking a vending machine isn't hard once you locate the Manager Wire in any given round. There are a few goals I have in mind:

1. The items inside of the machines should be faithful to what those machines are.
2. The items inside of the machines should raise questions about the SS14 universe, the corporations behind these machines, and what happened on the space station before the crew arrived on disaster day.
3. None of these items should become meta. If a vending machine begs to be hacked every shift, the items inside are too powerful.
4. The items shouldn't be high-end prestige items, but they should be interesting.
5. The vending machine stocks should never invalidate the role of Cargo in station function.

Two major changes of note:
First, Changeling Sting has been removed from the Shamblers EMAG menu, and Syndi-Cakes has been removed from the GetMore EMAG menu, to move those items to their contrabandInventory menus.
Second, figurines have been placed in their revelevant Drobe machines.

My reasoning for adding figurines to the machines is as follows:

1. It removes a lot of weight from purchasing figurines from Cargo, which is a fairly friviolous purchase, and makes obtaining a full crew set much more reasonable.
2. It gives a reason for innocent people to trespass or seek permission to hack Drobes for roleplaying purposes. It makes every department a bit less secure, which is fun for antags and an added joy for Security.
3. It can allow us to return the figurine objective back to Thief by making obtaining figurines accessible by hacking a crap-ton of Drobes across the station. It adds an element to thief gameplay that is interesting and different, but isn't in itself illegal.
4. Toys are fun, seeing more figures is part of what makes Cog interesting in its design, I'd love to see them show up more often.
5. This makes the Cargo figurine bounty much less awful to accomplish by making it reasonable to complete for knowledgeable players.

## Technical details
I went through every vending machine .yml file, added a "contrabandInventory:" line if there wasn't one, then added each item for those menus. I kept formatting consistent with the currently .yml files.

## Media
[Here is a video](https://www.youtube.com/watch?v=Ve6KyhcpOqo) of how to access the contrabandInventory menu, and showing every vending machine contrabandInventory menu. EMAG menus not included. Video uploaded to YouTube due to file size, video is approximately 5 minutes long.

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Merge Conflict with medidrobe.yml, seems simple to fix, requesting input.

**Changelog**
:cl:
- add: Added manager wire hacking menus to nearly all vending machines. Get hacking!

### CODE REVIEW

**Comment by AgentSmithRadio** [comment]
Simple issue with the medidrobe.yml, it looks like my version was pre-change, anyone with write access can easily fix the issue.

**Comment by slarticodefast** [comment]
The `- add` should be in a new line after the :cl: or the bot won't be able to read it.

**Comment by AgentSmithRadio** [comment]
Done and done, I think.

**Comment by NoElkaTheGod** [comment]
Well, this is just what i did, but actually makes sense

**Comment by thebadman4662** [comment]
> None of these items should become meta. If a vending machine begs to be hacked every shift, the items inside are too powerful.

I suppose multitool is getting removed from toolvend cause its damn close to being 100% cut managament wire nowadays.

**Comment by AgentSmithRadio** [comment]
> Well, this is just what i did, but actually makes sense

There are a few things I like in your proposal, namely the water bottles in the BoozeOMat, the Cyborg Cardboard Hat in the Robotech Deluxe (noting that it's already available in the TheaterDrobe) and adding a bar or two of soap to a vending machine in general. I'll have to think on these a bit more, or maybe add them in a future revision.

**Comment by AgentSmithRadio** [comment]
> I suppose multitool is getting removed from toolvend cause its damn close to being 100% cut managament wire nowadays.

It's probably the most meta Manager Wire item in the game currently, because it's the only remotely useful one, and it appeals to Greytiders. The cost of multitools is mostly having someone willing to give you one if you're a Passenger, rather than the device actually being expensive at the autolathe.

I'll note that the Cow Toolbox that I've added to the YouTool also has a functioning multitool, and unlike most of the items in that toolbox, it's not a nerfed version of it, so I'm effectively doubling the number of hackable multitools in the game. I'm not convinced that this will cause a real balance issue, but maybe people have opinions on this one.

**Comment by AgentSmithRadio** [comment]
Due to issues with the merge conflict and me not knowing how to SmartGit, I need to redo all of this from scratch and test it again. The content will likely remain the same when I do the next pull request.

**Pull request closed without merging**
