### PR TITLE
Gauze Markings 3 - Revenge of the Wrap

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
Moth Rights activists rejoice, become victims to pyrotechnic weaponry.
Moths are now wrapped in gauze :)
Adds 13 new gauze wraps exclusive to moths, lizard wraps are cleaner in code to match the new moth wraps, and I stubbed my fucking toe

## Why / Balance
Moths need gauze too!

That and the ones currently assigned looked fucking terrible and I had a wave of motivation

## Technical details
changed names in gauze.rsi, added 13 new gauze wraps (ftl/yml/png)

## Media
euhg1
euhg2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
nuh uh

**Changelog**
:cl:

* add: Added 13 new gauze wraps for moth that fit their twig bodies
* tweak: Gauze markings have been moved to the Overlay category, allowing gauze to not take up marking points

### CODE REVIEW

**Comment by Terraspark4941** [comment]
Lizard wraps CL doesn't look player facing, remove or relocate to technical changes at least

**Comment by KittenColony** [comment]
merg me pr

**Comment by K-Dynamic** [comment]
Perfect for halloween mummy costumes

**Comment by KittenColony** [comment]
ok it has localization errors gimme a bit

**Comment by KittenColony** [comment]
good enough

**Comment by Dutch-VanDerLinde** [comment]
Changelog be broken syntax is incorrect

**Comment by KittenColony** [comment]
@Emisse this shit has been ready for -months-

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by K-Dynamic** [comment]
@KittenColony this is sweet victory

**Pull request merged**
