### PR TITLE
Add PercussionInstrument tag to Woodblock

### PR DESCRIPTION
**Pull request by DanSAussieITS**
## About the PR
Added PercussionInstrument tag to the Woodblock so that it can be used in DAW construction.

## Why / Balance
Seems a little odd that an instrument that belongs to the percussion family as clearly as the woodblock can't be used as a percussion instrument for the DAW.

Currently there are only 2 instruments that count in that capacity: The Xylophone and Glockenspiel. The next smallest (Keyed) has 3, so this would bring it in-line.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by DanSAussieITS** [comment]
Ah fuck, forgot about the bounty. I guess having a full high-value bounty in one purchasable crate is a bit much unless the crate price or required items for the bounty were to be increased.
Bit of a shame since it would be nice to have a higher chance of finding enough instruments for a DAW in maints without having to pester cargo every time.

**Comment by DanSAussieITS** [comment]
Re-opened at Emo's request

**Comment by Emisse** [comment]
fix cargo arbitrage test failure=

**Comment by DanSAussieITS** [comment]
I have clearly screwed up somewhere since all these checks are now failing after changing the instruments required for the bounty

**Comment by metalgearsloth** [comment]
> I have clearly screwed up somewhere since all these checks are now failing after changing the instruments required for the bounty

No I'm just doing something on master for a moment, just wait a bit.

**Comment by DanSAussieITS** [comment]
Just gonna leave this for a day or so and hope whatever's causing the SpawnAndDelete test failures sorts itself out

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
