### PR TITLE
Adds Proto-Kinetic Burster

### PR DESCRIPTION
**Pull request by RiceMar1244**
`Drafted so that I can seek maintainer approval on the concept and so I can ask what the status on the gun freeze is.`

## About the PR

Adds a new tool to the salvage specialists' proto-kinetic arsenal, the Proto-Kinetic Burster. The burster is a sidearm weapon that seeks to compliment the accelerator rather than attempt to replace it in the players choice of tools. It has a larger battery with significantly less recharge speed, and shoots bursts of 3 weaker bolts. It is meant to be a high utility emergency sidearm that also plays off of some of the niche use cases of the PKA that it struggles to fully capitalize on.

## Why / Balance

The PKA is like the 'sustain' ranged weapon and mining tool of the salvagers' proto-kinetic arsenal. I wanted to try to capture the other end of that spectrum and provide a 'burst' weapon/mining tool. My hope is that the PKB's large charge pool but incredibly slow recharge time will provide an interesting resource management augmentation to salvage's weapons that they typically are not concerned with due to the infinite recharge. There are a range of use cases for a quickly applied barrage of kinetic bolts, use cases which the current slow but consistent weapons dont fully enable, and the large charge capacity of the PKB lets miners get creative with how they use their burst to get out of tricky situations or get into them.

## Technical details

There's only a teeny bit of new code. I just modifying the basic entity ammo recharging system to add a specified number of ammo instead of a flat 1.

## Media

In-world:
326290783-aa6f4d44-d9af-4ab6-bed7-c0ed71352219
Storage sprite (ive been wanting to use this new system hehe):
326290791-337dd80f-12b9-4d60-ac4d-b562f94c91be
The sprites themselves:
326302982-2fcf2021-49dd-4bc2-92da-2c4a9620bb9d

`All but the last video here show the old fire rate. I replaced the combat application video because its the most relevant when considering the changes.`

A showcase of the PKB's ability to set up nooks for mining charges, and its ability to dig a tunnel in an emergency:

https://youtu.be/A_8VNHXs_AI?si=iRXe5r5s5OF7TkRS

A showcase of the PKB's ability to breach a location at a reinforced window (the grille must still be wirecut):

https://youtu.be/llbIW36wux0?si=XV3SbYw7NGV-_9as

A showcase of the PKB's ability to assist in recovering from zero gravity stranding:

https://youtu.be/t5NmktEpDK8?si=rHD1VRKrpzR6h4Qz

A showcase of the PKB's limited range and applicable but limited effectiveness in combat:

https://youtu.be/qNTgG0VeCWU?si=7a5xtap5m82DfOTp

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: RiceMar
- add: Added the Proto-Kinetic Burster to salvage arsenal research.

### CODE REVIEW

**Comment by ImRenQ** [comment]
Isn't 90 damage in a few seconds too much?

**Comment by RiceMar1244** [comment]
I was wanting to hear some feedback on that part yeah. I want to make the active decision to use all your slow-charging barrages on a single target feel atleast somewhat valid, but it did seem like a bit much. I just wasnt sure if the lengthy recovery compensated, but i guess its gotta be taken for what it is, 90 damage in a couple seconds.

**Comment by ImRenQ** [comment]
A long recharge can be compensated by carrying several proto-kinetics in a backpack at once.

**Comment by K-Dynamic** [comment]
I'm glad to see the burst fire idea be tested https://github.com/space-wizards/space-station-14/pull/27452#issuecomment-2082026655, definitely needs tuning on the damage and tunnelling though

Like you store a bunch of these and punch through a whole row of rocks or nukies as it stands https://github.com/space-wizards/space-station-14/pull/27526#issuecomment-2084790585

I think conceptually the PKA and PKB should be swapped; the PKA should be the smaller portable sidearm with consistent mining, the PKB should be the larger (harder to hoard) burst firearm with faster mining and wielding

**Comment by RiceMar1244** [comment]
> I'm glad to see the burst fire idea be tested [#27452 (comment)](https://github.com/space-wizards/space-station-14/pull/27452#issuecomment-2082026655), definitely needs tuning on the damage and tunnelling though
> 
> Like you can store a bunch of these and punch through a whole row of rocks or nukies [#27526 (comment)](https://github.com/space-wizards/space-station-14/pull/27526#issuecomment-2084790585)
> 
> I think conceptually the PKA and PKB should be swapped; the PKA should be the smaller portable sidearm with consistent mining, the PKB should be the larger (harder to hoard) burst firearm with faster mining and wielding

A few responses, I just woke up so im gonna bullet point them instead of write it all out:
- I either wasnt aware or didnt remember that somebody had suggested a burst fire weapon.
- On the topic of mining with a full inventory of these: mathematically speaking, the total quantity of rock you could dig out by dedicating your entire inventory is likely less than the amount of rock you could mine by just swinging the pickaxe.
- On the topic of nukies: I will likely already be lowering the damage, but completely disregarding this, it has half the range of the PKA and its full burst doesnt even put down an unarmored target from full. *Two* of these wont even put down a nukie, and even then youd have to land it all. I guarantee that any other combat option would be more viable in a prolonged encounter, like nukies.
- On the topic of swapping concepts: the backbone that makes this concept work *is* its collapsibility. It isnt actually smaller than the PKA right now, but i emphasize its collapsibility to protect it from even being made larger. This is a back pocket topical-use tool and the harder it is to carry around, the more it has to be pulled out of its niche. Itd have to recharge at the rate of a normal PKA just to justify its storage and handling difficulty. It seems to be a pattern in game design that large weapons necessitate sustain.

**Comment by RiceMar1244** [comment]
To summarize the idea of packing an inventory full of these, youd need like 6 PKAs of lathe materials to set that up per miner, and then:
- In mining, it doesnt mine fields of rock more efficiently than a pickaxe.
- In combat, its less stored up damage than an equally full inventory of laser pistols.
- Even in zero gravity nav, it doesnt fly you better than just a jetpack, but i could see salvagers easily falling into situations where they dont have their jetpack on them, but they do have *this thing*.

**Comment by RiceMar1244** [comment]
On that note, as the author of the PR, for the sake of any future balance on this weapon, I want to emphasize the recharge speed as the primary pivot point of balance. I'm happy with where 9 bolts in your back pocket can get you. It pretty properly supports every primary use case described above. The three bursts is like three bars of meter on your 'special ability'.

**Comment by RiceMar1244** [comment]
I cut the fire rate in half for the time being, because there is no way to enforce a pause in between bursts for weapons with burst fire mode. In the future if that changes, I will probably try to return to its old fire rate with a pause because I like the way it dakkas

**Comment by RiceMar1244** [comment]
Alright, I spoke with the plasma cutter person. However, I am a foolish fool and did not realize there was a freeze on guns. This PR will stay drafted for now while I seek maintainer approval on the concept.

**Comment by RiceMar1244** [comment]
Additionally, the concept may depend on improvements to the gun system, since this thing is turning out to be incredibly hard to tweak properly with how some things work right now.

**Comment by RiceMar1244** [comment]
If I cannot get maintainer approval because of technical stuff, I will close the PR and return to it later.

**Comment by RiceMar1244** [comment]
So here's the funny thing. I'm finally getting to play shifts more often since the busy last leg of the college semester, and honestly? I'm on the fence about if salv even needs this lmaoo (as cool as it is and as much as I enjoy designing sci-fi weapons). 

It's not off the table, ill give it some more critical thought, cause I've been struggling tweaking this thing to a satisfying game feel in the first place, so id rather just take this chance to take and break and re-familiarize myself with the salv vibe.

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by Froozigiusz** [comment]
> So here's the funny thing. I'm finally getting to play shifts more often since the busy last leg of the college semester, and honestly? I'm on the fence about if salv even needs this lmaoo (as cool as it is and as much as I enjoy designing sci-fi weapons).
> 
> It's not off the table, ill give it some more critical thought, cause I've been struggling tweaking this thing to a satisfying game feel in the first place, so id rather just take this chance to take and break and re-familiarize myself with the salv vibe.

I think that the problem of samey–ness you feel is the result of their identical linearity of bullets, much like how similar submachine guns can feel to each other.
I propose overhauling the burst aspect of this tool to be more shotgun–like, having multiple particles spewed out at a wide angle (and random direction to emphesize it's industrial/mining purpose!), then high damage would be unreiable, and many rocks would be punched through. I guess sprite would have to get a tad bit wider in the likes of the stereotypical elephant rifle.

**Pull request closed without merging**
