### PR TITLE
Paperwork ghostrole

### PR DESCRIPTION
**Pull request by GrumpyKal**
## About the PR
Paperwork has been added as a round start ghost role similar to Hamlet.

## Why / Balance
RP, fun, and so the Librarian won't feel so lonely.

## Technical details
Paperwork is now available as a round start ghost role with mouse accent and sloth sounds.

## Media
paperworkrole
slothaccent

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No major changes

**Changelog**

:cl:
- add: Paperwork is now available as a round start ghost role
- tweak: Paperwork now makes sounds when being pet

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
paperwork needs to be able to do paperwork

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Remove the "Remove: nothing" and "fix: nothing" from the changelogs, as long as you have them listed they will be put in the changelog.

For the "Add" avoid using technical jargon. Just say "Paperwork is now a roundstart ghost role" or something

The "Tweak" could use a better wording "Paperwork makes a sound when petting it"

**Comment by GrumpyKal** [comment]
I've updated the Changelog section per Vasilis's comment to remove the lines I'm not using and reword the "tweaks". I've updated the language in the "About" and "Technical Details" section to replace instances of 'static ghost role' with 'round start ghost role' to bring it more in line with the phrasing used in the Changelog section.

**Review by VasilisThePikachu — APPROVED** [review]
Looks fine to me

**Comment by Emisse** [comment]
we dont want more roundstart pet ghostroles

**Comment by GrumpyKal** [comment]
Thats fine, as I commented in the HowToCode channel when making this, it was mostly so I could learn more about how to make pull requests. First time submitting. I'll get started on the next one then. :)

**Comment by EmoGarbage404** [comment]
Thank you for the PR, but at this time, the maintainer team as a whole does not feel that we need more round-start pets to be ghost roles. I'll be opting to close the PR, but please make more in the future.

**Pull request closed without merging**
