### PR TITLE
Mini Ebow [Antag Item]

### PR DESCRIPTION
**Pull request by Ablankmann**
## About the PR 
This PR ports the Miniture Energy Crossbow from Nyano, and adds it to the Uplink. Thank you, Rane!
The Mini Ebow does little (if any) damage, but does 1-3 seconds of stun. It's intended to be used as a combo weapon.

**Changelog**

:cl:
- add: Added the Miniature Energy Crossbow. The comboing begins.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
You didn't actually make the prototype for the bolt that it fires.

**Comment by Ablankmann** [comment]
> You didn't actually make the prototype for the bolt that it fires.

Fixed (hopefully)

**Comment by moonheart08** [comment]
I am incredibly apprehensive about readding the so-called "wombo combo".

**Comment by Ablankmann** [comment]
> I am incredibly apprehensive about readding the so-called "wombo combo".

Understandable. Let me know if you feel like it needs any tweaks, though

**Comment by moonheart08** [comment]
> > I am incredibly apprehensive about readding the so-called "wombo combo".
> 
> Understandable. Let me know if you feel like it needs any tweaks, though

In case you're not aware of the prevalence in SS13 this item has, it's basically the murderboner's toolkit.
This + an esword and you can simply murder the entire station with stunlocks.

**Comment by metalgearsloth** [comment]
I thought ss13 removed it. When I played it was just ebow + esword and target dead with no recourse.

**Comment by Ablankmann** [comment]
> Contributor



> > > I am incredibly apprehensive about readding the so-called "wombo combo".
> > 
> > 
> > Understandable. Let me know if you feel like it needs any tweaks, though
> 
> In case you're not aware of the prevalence in SS13 this item has, it's basically the murderboner's toolkit. This + an esword and you can simply murder the entire station with stunlocks.

I haven't played SS13 a day in my life due to how daunting byond seems, so I was not, aware of this. Reckon I'll close this, then

**Pull request closed without merging**
