### PR TITLE
Gay Boykissers

### PR DESCRIPTION
**Pull request by BackeTako**
## About the PR

Added a male gay pride pin

## Why / Balance

Boykissers rejoice.

## Media

time_to_kiss_boys

gaypin

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Gay Pin

### CODE REVIEW

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by VasilisThePikachu** [comment]
mrrp meow

**Comment by cfif126** [comment]
borzoi wtf

**Comment by snebl** [comment]
Why does this have a 1:1 dislike ratio??

**Comment by VasilisThePikachu** [comment]
> Why does this have a 1:1 dislike ratio??

Probably bigotry. Emotes are not accounted into pr review anyway

**Comment by ilikeships** [comment]
waiter waiter i'll have more bloat please

**Pull request merged**
