### PR TITLE
Fire sprite change for mice

### PR DESCRIPTION
**Pull request by PaigeMaeForrest**
## About the PR

A new fire sprite was added to fit the mouse.

## Why / Balance

This is a fix to "Mouses needs a proper burning sprite #12129"
currently fire will appear on the ground away from the mouse.

## Technical details

the metadata for the fire sprites folder had the new sprite added to it, along with that the fire sprite is now chosen on the mouse itself instead of its parent like other animals.

## Media

 Before the change:

Screenshot 2024-04-05 152944
Screenshot 2024-04-05 152941
Screenshot 2024-04-05 152936
Screenshot 2024-04-05 152931

After the change (changed mouse only sprite)

Screenshot 2024-04-05 152905
Screenshot 2024-04-05 152902
Screenshot 2024-04-05 152857
Screenshot 2024-04-05 152852

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

There should be no breaking changes. (nothing removed)
I have experienced no issues while testing. 
rats have been changed as well
this now includes hamsters and mothroaches, although mothroaches require something better, mostly bigger
the meta.json has been edited to be much easier to read

also to note: this is my first PR, i may have messed up royaly 

**Changelog**

:cl: BITTERLYNX

- fix: Rodents are more visually pleasing to burn
- fix: mothroach and hammy also more visually pleasing to burn

### CODE REVIEW

**Comment by PaigeMaeForrest** [comment]
i am unsure of why the meta.json file shows as deleted and readded, unsure if that would be aproblem

**Comment by deltanedas** [comment]
its just how the diff works if you rewrote most of it

**Comment by PaigeMaeForrest** [comment]
ah that makes sense

**Comment by Tayrtahn** [comment]
Also because it's an ugly one-liner json file. You're certainly not required to, but if you _wanted_ to make it pretty-print style, that would be welcome and appreciated.

**Comment by PaigeMaeForrest** [comment]
my guess by pretty you mean formatted not horrible straight line
it wanted to do that on its own when i edited it, id be happy to do it again

**Review by Tayrtahn — APPROVED** [review]

**Comment by PaigeMaeForrest** [comment]
single line badness fixed!

**Pull request merged**
