### PR TITLE
Make mechanism behaviors properly update, fix eating and drinking

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Also adds a hungry command.

### CODE REVIEW

**Review by Zumorica — APPROVED** [review]
So, again we've gone back to implementing ECS in body parts? Pretty based

**Comment by DrSmugleaf** [comment]
> So, again we've gone back to implementing ECS in body parts? Pretty based

No, otherwise I would have had to reimplement the prototype system, component system, sprite component, grammar component, icon component and damageable component for body parts.

**Comment by Zumorica** [comment]
It was a joke.

**Comment by DrSmugleaf** [comment]
> It was a joke.

Just like body system

**Pull request merged**
