### PR TITLE
Secure bar substation for omega station

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

Substation near the bar in omega station has been moved and is now behind an engineering locked door.

## Why / Balance

Mapping conventions.

## Technical details

I did have to remove a fire suit, gas mask and helmet that was placed on a rack in the location where the substation is now, but had no good spot to place it in again. I've replaced this with a fire-safety wall closet, which I hope is sufficient.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

New vs old (Note the old image is taken in a loaded map, not in mapping mode):
image
image

## Breaking changes

n/a

**Changelog**

n/a

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Why's the map diff so large?

**Comment by TsjipTsjip** [comment]
Not a day goes by I don't ask myself the same question.

On a serious note, I honestly got no clue. All I know is that I tested it and that it does work? Map diffs are usually rather large.

**Comment by metalgearsloth** [comment]
They're not normally half the map file, no

**Comment by deltanedas** [comment]
half the maps are saved with crlf

**Comment by Emisse** [comment]
it be like that sometimes, editing old decals often does it or editing entities that have had their names changed

**Pull request merged**
