### PR TITLE
Clumsy is now a trait!

### PR DESCRIPTION
**Pull request by beck-thompson**
## About the PR

When doing #31147 someone had a good idea of making clumsy a trait! To the maintainer reading this, you might want to merge my refactor PR first but it won't really matter either way.

## Media

https://github.com/user-attachments/assets/e6cca7a8-9715-4c58-ac0c-9f146c683b11

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Beck Thompson
- add: Clumsy is now a selectable trait.

### CODE REVIEW

**Comment by Emisse** [comment]
i dont think this should be a trait

**Comment by beck-thompson** [comment]
> i dont think this should be a trait

Mind explaining why? I don't see the issue but I could be missing something!

**Comment by Emisse** [comment]
it should be unique to clown otherwise its less funny

**Comment by Plykiya** [comment]
> it should be unique to clown otherwise its less funny

I think a gun blowing up in someone's hands that isn't intentionally dumb like the clown is even more comedic due to how unexpected it is

**Comment by slarticodefast** [comment]
I have put this up for discussion with the maintainers and the general agreement was that this should stay unique to the clown (and monkeys/kobolts). It is what makes the clown special and might cause problems when a security player chooses it (see discussion in #30777).

**Comment by Aisu9** [comment]
> I have put this up for discussion with the maintainers and the general agreement was that this should stay unique to the clown (and monkeys/kobolts). It is what makes the clown special and might cause problems when a security player chooses it (see discussion in #30777).

thought the meat and bone of this game was roleplay, why tactical advantage(or in this case disadvantage) is so much of an issue for a Roleplay orientated game?

**Pull request closed without merging**
