### PR TITLE
Hardhats are minor armor

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## Hardhats are minor armor

Adds 5% damage reduction for blunt and slash to hardhats.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- add: Hardhats are now PPE certified. They will reduce blunt and slash injuries by 5%.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
First, hardhats are already better than other headwear due to their (decently good) headlight. In that sense, I don't think they need a buff of any kind.

While I understand that it's a bit strange that hardhats don't provide any innate protection, I am generally opposed to sticking buffs like this onto items that are already better than their other options.

**Comment by QuietlyWhisper** [comment]
But if youre saying that having an armored helmet light is  too much, consider that people that want a helmet light with armor will likely be wearing a hardsuit rather than just a simple helmet

**Comment by EmoGarbage404** [comment]
It's not like you have a choice of using them with a hardsuit. Giving them a pointless 5% blunt protection doesn't fix the fact that engineers choose to wear hardsuits. If you're wearing a hardsuit, you have to have an empty head slot for your helmet, hence why no one bothers with hardhats.

**Comment by QuietlyWhisper** [comment]
Giving them a minor protection benefits engineers who don't instantly put on hardsuits I suppose? There must be a better way to shake up the engineer hardsuit stuff a bit...

**Comment by deltanedas** [comment]
so:
- i sometimes go winter coat + hardhat for movespeed and storage, being a little bit more robust is nice
- you forgor to :cl: Whisper

**Comment by QuietlyWhisper** [comment]
After some talk in the discord though, we have come to the conclusion that hardsuits should probably be nerfed rather than buffing alternative engineer gear

**Comment by deltanedas** [comment]
yeah since 99% of the time you put on hardsuit at roundstart
in RoE or something it says on yellow engis should be suiting up, but they already have suits permanently attached to them

**Comment by QuietlyWhisper** [comment]
I forgot who mentioned it but I think the solution we found was sinply nerfing general use hardsuits to be more inline with standard EVA, with only protections based on the role purpose

Ive also considered adding a battery to the hardsuit so it cant be worn forever (this would exclude security, centcom, bloodreds)

**Pull request closed without merging**
