### PR TITLE
Sanitize shorthand emotes throughought the whole message

### PR DESCRIPTION
**Pull request by Aeshus**
## About the PR
I refactored the `ChatSanitizerManager` class to:

1. Make its parsing more versatile using regex instead of only matching the end so that it can sanitize shorthand emotes at the start and in the middle of a message.

2. Get it closer to being ready for when we have to integrate it with all of the new chat v2 stuff in progress (which are also planning to use a regex for this). 

Additionally, the order of sanitization in the main chat manager has been changed so that the capitalization and stuff applies after the word order has been changed. 

This continues work on #17313 (the word expansion part is currently implemented separately through accents).

Some future work to be done is to integrate with the new v2 chat systems and to move the dictionary to a prototype.

## Why / Balance
- The original implementation simply checked the end of the message for the string, which wasn't very effective and caused some false-positives.
- It previously needed to hard-code punctuation (which was only done for periods) and it would miss simple ones like `Lol haha` just because `Lol` wasn't at the end of the sentence.
- As well, the word Parallel would trigger it as it ends in "`lel`", causing the player to say "Paral" and laugh emote.

## Technical details

The main thing was changing the matching system from a string to a regex. The regex is explained in the comments but I'll explain it again with examples:

The pattern is: `$@"\s{escaped}(?=\p{{P}}|\s|$)|^{escaped}(?:\p{{P}}|(?=\s|$))"`

So, if we are searching for lol, it would look like:

- `\slol(?=\p{{P}}|\s|$)`
	- This matches if it starts with a space and is succeeded by a punctuation, whitespace, or end of string.
	- This was done to make sure that only the whole word would be matched, instead of just a part.
	- "Haha[ lol]!" => "Haha!" + "emote laughs"
	- "It's a lollipop" => "It's a lollipop"

- `^lol(?:\p{{P}}|(?=\s|$))`
  - This matches if the word starts at the beginning of the string and either ends in punctuation or is succeeded by whitespace or the end of the string.
  - This was done to make sure that if it starts with a message, it would consume the punctuation (so "Lol!" becomes "emote laughing") or it needs whitespace or end of line to make sure that it isn't inside another word.
  - "[Lol] that's funny?" => "That's funny?" + "emote laughs"
  - "Lollipops" => "Lollipops"
  - "[Lol!] That's so funny!" => "That's so funny" + "emote laughs"
  - "[Lol,] that's a good joke" => "That's a good joke" + "emote laughs"

As well as that, in order to keep "backwards compatibility", I thought that instead of letting the user spam `lol lol lol lol lol` and have that queue up a lot of emotes, it will only use the last emote in the message. 

This keeps it the same as the old implementation (as previously, the only one to be emoted would *have* to be at the end): 

- (old) "Haha lol :)" => "Haha lol" + "emote smiles"
- (new) "Haha lol :)" => "Haha" + "emote smiles" 

Importantly, the emote that comes out stays the same.

Another backwards compatibility thing is that it will consume the punctuation if the word is at the start of the message (which was previously hardcoded only for periods).

- (old) "lol." => "" + "emote laughs"
- (new) "lol." => "" + "emote laughs"

The backwards compatibility wasn't extended to when it would delete punctuation at the end of a longer message just because the shorthand preceded it, such as:

- (old) "Haha that was good lol." => "Haha that was good" + "emote laughs"
- (new) "Haha that was good lol." => "Haha that was good." + "emote laugh"

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/87614336/c057b5df-3a7e-4008-9320-6da4ee3691dd

## Breaking changes

(Minor Breaking Changes, as this API was only used in one place)
- `TrySanitizeOutSmilies` was renamed to `TrySanitizeEmoteShorthands` as it's more representative of what the function is doing now.
- `TrySanitizeEmoteShorthands` will now sanitize shorthands throughout the message instead of just at the end.

**Changelog**

:cl:
- tweak: Emote shorthands (like "lol" or ":)") sent in chat are detected throughout the whole message. Note that only the last shorthand in the message will be emoted.

### CODE REVIEW

**Comment by lzk228** [comment]
what if "lol" is the part of some word? will it replace?

**Review by Emisse — APPROVED** [review]

**Comment by TheShuEd** [comment]
Uh, I didn't get anything to do a code review.

**Review by SlamBamActionman — APPROVED** [review]
Tested this merged with current master and it seems to work as intended. Regex *seems* fine but this PR will probably benefit from some live testing. 

As the last interaction on this PR was before the review guidelines change, I will count Emisse's previous approval as the second required approval.

**Comment by deltanedas** [comment]
real my hack wasnt a hack

**Pull request merged**
