### PR TITLE
Vox plushie

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR 
Added a vox plushie in the random plushie pool and in the toy cargo crate!
**Screenshots**

unknown

**Changelog**

:cl:
- add: Added a vox plushie.

### CODE REVIEW

**Review by DrSmugleaf — APPROVED** [review]

**Comment by SweptWasTaken** [comment]
The sprite is really bad. It looks more like a big duck than a Vox.

**Comment by PJB3005** [comment]
That looks like something from duck game skreeeeeeeee

**Comment by metalgearsloth** [comment]
image

**Comment by DogZeroX** [comment]
@metalgearsloth Vox IRL

**Comment by SweptWasTaken** [comment]
I don't care for the sprite.

**Comment by SweptWasTaken** [comment]
From a maintainer standpoint I don't know how I feel about concretely declaring that Vox exist in Space Station 14. We have the Vox race barely with the mob, and that's not implemented at all in regular gameplay. The Vox plushie is something that players will actually see.

Additionally the sprite is garbage and I don't want it merged in it's current state.

(I agreed with Smug in dev chat to reopen this to get other takes).

**Comment by Zumorica** [comment]
As for me, I'm fine with merging it as long as the sprite gets improved :relieved:

**Comment by SweptWasTaken** [comment]
> 
> 
> As for me, I'm fine with merging it as long as the sprite gets improved 😌

Nine days without any activity, re-closing.

**Comment by DogZeroX** [comment]
unknown

**Comment by DogZeroX** [comment]
My face when, a simply PR about a vox plush PR had to go through two closes, this says a lot about society. 😔

**Comment by SweptWasTaken** [comment]
> 
> 
> unknown

I can't tell if this is worse or better than the last but it looks awful. 

> My face when, a simply PR about a vox plush PR had to go through two closes, this says a lot about society. 😔 Though feel free to suggest anything for it.

🤔 I'm a maintainer I close PRs if they are stale or they don't fit the codebases standards.

**Comment by PJB3005** [comment]
Ok I'll admit that seeing it in-game like that it does have pretty bad color contrast

**Comment by DogZeroX** [comment]
unknown

**Comment by PJB3005** [comment]
Speedmerge

**Review by SweptWasTaken — APPROVED** [review]

**Pull request merged**
