### PR TITLE
Colorblind friendly thermomachine LED colors

### PR DESCRIPTION
**Pull request by deathride58**
## About the PR
This PR is straight-forward: it swaps out the red/green palette of thermomachines in favor of an orange/cyan palette.

## Why / Balance
So https://discord.com/channels/310555209753690112/1185781016598679604/1254601734307713115 pointed out that the thermomachines are a bit hard for colorblind folks to properly distinguish. And one quick look at the sprites shows exactly why: the only differentiation between a heater and a freezer is that the LED is either red or green respectively. This differentiation is *the* worst possible scenario for full protanopes and full dueteranopes alike, as those two forms of colorblindness are strictly red/green colorblindness (as in they cannot reasonably differentiate between red and green).

This PR replaces that differentiation with a far, *far* saner alternative: a simple orange/cyan differentiation. The following screenshot of Adobe's colorblind safety tool says all that needs to be said about this alternative palette
firefox_nMD9lZm32D

This PR primarily serves as a stopgap until someone can make a sprite for the thermomachines that doesn't rely strictly on color for differentiation. We are not a spriter ourself, and thus we offer this replacement.

Additionally, it'd probably be a good idea for the LEDs to be given an unlit layer, as lighting does affect the ingame readability quite a bit, but we feel like that's out of this PR's scope.

## Technical details
N/A

## Media
dotnet_lCpGyDd8bE

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**

:cl: Bhijn and Myr
- tweak: The colors of the LEDs on the heater and freezer thermomachines has been changed from red/green (respectively) to orange/cyan (respectively). In laymen's terms, this makes thermomachines far more reasonably differentiable for those with colorblindness.

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Can we just add color blind options?

**Comment by deathride58** [comment]
For in-world objects that convey information through visuals, having separate variants for colorblindness can genuinely be counterproductive, especially in a roleplay-centric multiplayer environment. Having to account for the fact that thermomachines could be seen as either red/green or orange/blue depending on someone's settings would, simply, be an unnecessary form of friction that's avoidable by just making the sprite accessible by default to begin with.

And as someone who's colorblind: the current sprite in the repo ain't accessible at all.

**Comment by Tayrtahn** [comment]
Imo, orange and blue are more sensible indicators for hot and cold anyway.

**Comment by Golinth** [comment]
we have a colorblind setting in game, maybe tie these new colors to them?

**Comment by Ghagliiarghii** [comment]
Makes more sense than it did before and I love accessibility improvements, good PR :+1:

**Comment by mirrorcult** [comment]
these are good colors anyway even if they werent also better for accessibility, green doesnt make any sense for a cooler

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
