### PR TITLE
Buff Bulk Lizard Plushie Crate

### PR DESCRIPTION
**Pull request by Kukutis96513**
## About the PR

Increased the amount of plushies in the bulk lizard plushie crate.

## Why / Balance

https://discord.com/channels/310555209753690112/1204995315757879346 the lizards demand more plushies
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Changed the amount of plushies in the lizard plushie crate.

### CODE REVIEW

**Comment by UbaserB** [comment]
Sounds good

**Comment by IProduceWidgets** [comment]
Might be worth weighing this with #25132 in mind one way or another.

**Comment by Kukutis96513** [comment]
> Might be worth weighing this with #25132 in mind one way or another.

Could make it more expensive i guess..

**Comment by MouseHatsForAll** [comment]
Ah, thanks for adding in more plushies for my 'Weh' addiction. Much appreciated!

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Too many ents, just change the price.

**Comment by Kukutis96513** [comment]
> Too many ents, just change the price.

alright, increased price from 2500 to 5000.

**Comment by metalgearsloth** [comment]
> > Too many ents, just change the price.
> 
> alright, increased price from 2500 to 5000.

You did the opposite thing, decrease the price and leave it at 5 plushies.

**Comment by TheShuEd** [comment]
5 plushie for 500$

**Review by TheShuEd — APPROVED** [review]

**Comment by Kukutis96513** [comment]
> > > Too many ents, just change the price.
> > 
> > 
> > alright, increased price from 2500 to 5000.
> 
> You did the opposite thing, decrease the price and leave it at 5 plushies.

didnt know if you wanted me to lower the price or increase the price..

**Pull request merged**
