### PR TITLE
Added a research and construction path to the base R&D point generator.

### PR DESCRIPTION
**Pull request by magmodius**
## About the PR
Added an experimental tier 3 technology that would allow science to create safe point generators.

## Why / Balance
Each focus that science has access to should, hopefully, help the specific department(s) that the focus is based on. And the experimental focus tree does do that, mitigating the safety risks of having anomalies active across the station. However, their tier 3 technology hardly helps their work or keep the station safe. While fun to use, the tier 3 techs for experimental are practically just toys. This tech is made to give science an absolutely safe way to research, while keeping the generation over time effect that would allow them to focus on utilizing their toys rather than babysitting anomalies or artifacts. The recipe requiring an anomaly core ensures that science will still have to put in some kind of risk for the reward of long-term safety.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Science now has a new tier 3 experimental technology, allowing them to safely research anomaly cores.

### CODE REVIEW

**Comment by Minty642** [comment]
high chance not getting merged

**Comment by magmodius** [comment]
> this is one of the prs of all time

i figured i would get my T3 ideas out there, whether or not they'll actually be merged. better to have tried to get something into the game than forever be in the WYCI realm.

**Comment by K-Dynamic** [comment]
Probably not gonna be merged but seeing more usages of anomaly cores is cool

**Comment by mirrorcult** [comment]
this seems extremely gameplay-defeating

**Comment by magmodius** [comment]
> this seems extremely gameplay-defeating

possibly? but i don't really see how it's much different from the anomaly synchronizer in that regard. obviously it would remove the pulses from the anomaly, but it would also require science make several anomalies in a row to get the full benefits of a single high-severity anomaly. also, while i don't think it should entirely remove the gameplay loop for the dept, i do think the T3 for each department should at least significantly ease the department's job. none of sci's other T3s help with that. 
i suppose if you wanted to be really stingy about it, i would rather the anomaly synch be a T3 than things stay as they are for experimental tech.

**Comment by Hent798** [comment]
Have we given up on the score generator only to end up returning to it?
This generator reduces all anomalies to zero, the anomalies will simply be destroyed and these generators will be manufactured, and only T3 science will be studied.

**Comment by icekot8** [comment]
I agree with mirrorcult and Hent, it's too much.
Like, why keep an anomaly when you can kill it and use its core much safer? T3 research is already one of the most useful, in my opinion. OP :skull:

**Comment by Kadeo64** [comment]
Experimental tier 3 is arguably one of the better tier 3s right now I don't think it needs to be broken overpowered.
I mean a base RND point source makes 50 guaranteed points a second, and them being locked behind anomaly cores doesn't matter when science has an anomaly core surplus in most rounds. This is just going to lead to science rushing experimental tier 3 and decaying anomalies to setup a five rnd point source farm that generates them 250 points a second with no maintenence required.

**Comment by EmoGarbage404** [comment]
Passive point generation was removed deliberately. Being able to generate infinite unlimited points at no cost, threat, or effort spits in the face of what makes the department interesting.

This discipline is already the most chosen by players. Buffing it even more by letting people get infinite points is ludicrous.

No balance or change short of reworking the generator entirely would make this be considered.

**Comment by deltanedas** [comment]
for more points instead do something like experimental vessel, upgraded artifact scanner or something

**Comment by magmodius** [comment]
T3 experimental is the most researched? really? i thought it was pretty useless.

that being said, i completely understand why this was closed. i didn't particularly expect it to get far, so i'm not too broken up about it. i would like to posit the idea of the anomaly synchronizer being made T3 instead, but if experimental tech is already getting researched as much as is said, that would probably be a bad idea.

**Comment by deltanedas** [comment]
on deltav everyone goes industrial every round so its a bit different

**Pull request closed without merging**
