### PR TITLE
Chatfactor: The Addition-ing

### PR DESCRIPTION
**Pull request by FairlySadPanda**
## About the PR
The addition-only changes to Chatfactor, with the minimum done aside to make the code compile and run.
Chatfactor is here: [#24680]

## Technical details
5,000 lines of additions with numerous edits to the rest of the code base is impossible to review. This allows the actual new code to be reviewed separately from the feature branch.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Literally no CL, no functional changes at all.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Good 👍

**Comment by Brandon-Huu** [comment]
God damn, 48 files changed

**Comment by FairlySadPanda** [comment]
This has received no interest to review so am closing

**Comment by deltanedas** [comment]
no review = instamerge not close :trollface:

**Comment by Brandon-Huu** [comment]
> no review = instamerge not close :trollface:

We're only human after all

**Pull request closed without merging**
