### PR TITLE
Rod event has a proper annoucement

### PR DESCRIPTION
**Pull request by DogZeroX**
## Why / Balance

The event text is like this on ss13, it is funnier, fills crew with confusion.
## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Changed the announcement of the immovable rod event.

### CODE REVIEW

**Comment by baddiePRO** [comment]
no CL :godo:

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
zased and rodpilled

**Comment by UbaserB** [comment]
wait if they say this every time a rod hits, then wont it be weird that every time centcom picks it up; they are confused?

**Comment by Hanzdegloker** [comment]
> wait if they say this every time a rod hits, then wont it be weird that every time centcom picks it up; they are confused?

This tbh, the other is vague and abstract but everyone knows whats gonna happen. Tis iconic at this point.

**Pull request merged**
