### PR TITLE
Glued chairs :trollface:

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Add ability to glue entities with StrapComponent (chairs, beds)
You cannot unbuckle yourself, but other players can unbuckle you (because it was causing exeptions :trollface:)

## Why / Balance

more fun

## Technical details

dont think so

## Media

Screenshot_20240619_113822

https://github.com/space-wizards/space-station-14/assets/124214523/e4fbd790-ad3a-4ba0-a9fc-c66d02015cf8

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added ability to glue chairs and beds.

### CODE REVIEW

**Comment by TurboTrackerss14** [comment]
I would be grand with this going in, but only after the chairbuckling doafter pr (i forgor the number or if its even up)
Because getting buckled to an chair during combat because someone got a single good mouse click off is cringe. Doubley so with a glued chair.

**Comment by beck-thompson** [comment]
oh god no not more for the refactor 😭 😭 😭

**Comment by beck-thompson** [comment]
Was there a reason you didn't use the `UnbuckleAttemptEvent`? I'm still trying to understand events and it feels like that would work here but I'm not sure.

**Comment by lzk228** [comment]
> Was there a reason you didn't use the `UnbuckleAttemptEvent`? I'm still trying to understand events and it feels like that would work here but I'm not sure.

i didnt look too much for all new methods in buckle system

**Comment by ps3moira** [comment]
Super glue not regular glue, cause it'd be kinda broken if you can just insta-drag someone onto a chair and they can't move. The glue-chair meta....the horrors

**Comment by lzk228** [comment]
> Super glue not regular glue, cause it'd be kinda broken if you can just insta-drag someone onto a chair and they can't move. The glue-chair meta....the horrors

there is no super glue reagent, glue and crazy glue both have the sape SpaceGlue, difference only in consumption and respectively in glued time

**Comment by lzk228** [comment]
closing until #26765 merged

**Pull request closed without merging**
