### PR TITLE
Added a regular and an engraved zippo (flippo) lighter

### PR DESCRIPTION
**Pull request by Darkenson**
## About the PR

I added a flippo lighter and a golden engraved flippo lighter. The engraved flippo can be a thief's objective, with half the weight of the forensic scanner.
Also moved the lighter sounds (and the new flippo sounds) to a folder, for better organization.

## Why / Balance

It's cool, it uses the expanded itemToggle system, and the engraved lighter has been added as a potential target for the thief.

## Media

https://github.com/space-wizards/space-station-14/assets/4154895/5edbe353-e9f6-4075-85a2-a6a85c358efc
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Added an engraved flippo lighter, found in the detective's coat. 
- add: The engraved flippo lighter may become the thief's objective.
- add: Added a regular flippo lighter.

### CODE REVIEW

**Comment by UbaserB** [comment]
cute

**Comment by lapatison** [comment]
How about using the Paradise zippo sounds?
[open](https://github.com/ParadiseSS13/Paradise/blob/3f5c57b7868d4173be6d6409babad95cd7118904/sound/items/zippolight.ogg)
[close](https://github.com/ParadiseSS13/Paradise/blob/3f5c57b7868d4173be6d6409babad95cd7118904/sound/items/zippoclose.ogg)

**Comment by JoeTheJanitor** [comment]
“Zippo” is a specific brand name, so its probably a good idea to rename this to something slightly different. “Flippo”, maybe?

**Comment by Darkenson** [comment]
> “Zippo” is a specific brand name, so its probably a good idea to rename this to something slightly different. “Flippo”, maybe?

Renamed it to Flippo.

**Comment by Darkenson** [comment]
> How about using the Paradise zippo sounds? [open](https://github.com/ParadiseSS13/Paradise/blob/3f5c57b7868d4173be6d6409babad95cd7118904/sound/items/zippolight.ogg) [close](https://github.com/ParadiseSS13/Paradise/blob/3f5c57b7868d4173be6d6409babad95cd7118904/sound/items/zippoclose.ogg)

Added and edited them to be quicker. The opening one sounds a tad strange since it's double action, but it's good enough I think.

**Comment by Darkenson** [comment]
Also added the Flippo engraved lighter as a thief objective, with half the chance of the forensic scanner, with 80% of the difficulty (since it's hidden in the coat, but it's not necessary for the detective's activity, so it's less likely to be missed).
image

**Pull request merged**
