### PR TITLE
Gives Mediborg the Medical Hud

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Title
## Why / Balance

I assumed that mediborgs already had the hud when making #27875, as the hud is used to help people in need.
## Technical details

yml changes
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Medical Borgs now have medical huds

### CODE REVIEW

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Okay this is starting to pile up, just make a new parent prototype with the ShowHealthBars and ShowHealthIcons comps configured and make every entity prototype with the following pattern inherit it  (prots can have multiple parents)
``yaml
  - type: ShowHealthBars
    damageContainers:
    - Biological
  - type: ShowHealthIcons
    damageContainers: 
    - Biological
```

**Comment by Cojoke-dot** [comment]
Meh... Don't know what's causing the GitHub error but I did the requested change. I think I set all the items that needed the parent but I'm not sure, tell me if you notice anything I missed.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
These are the only ones that need to be parented to  ShowMedicalIcons:
MobMedibot, ClothingEyesHudMedical,  ClothingEyesHudMedOnion (prob should just be parented to the base hud), ClothingEyesHudMedOnionBeer (same), ClothingEyesHudMedSec,  ClothingEyesHudMultiversal (only partially cuz it overrides ShowHealthBars) , ClothingEyesHudOmni (same).

**Comment by Cojoke-dot** [comment]
Ok, all of the objects are parented that you requested, plus BorgChassisMedical because that's the main point of the pr. I believe the only thing I missed last time was MobMedibot.

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
