### PR TITLE
pens are bought in boxes now

### LINKED ISSUE #15179: Traitors should be able to identify if a pen is of the explosive, hypo, or e-sword variety
## Description
If a traitor buys a surplus crate and gets a pen in it, they will have no way of identifying the pen at first glance. With the addition of exploring pens this can be quite leathal to the traitor. If they attempt to use it to investigate, and its the exploding pen, they will either waste it, or end up blowing themselves up.

**Additional context**
Yes I know this is a skill issue, but we should find a way to remedy this since new players might kill themselves and waste their traitor round unintentionally.

Some ideas:

We can have them spawn with removable labels.
We can allow traitors to be able to identify what variety they are by examining them.
Remove exploding pens from surplus crates.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
fixes #15179 by making all pens come in unique boxes

the type of pen can be seen by name and from sprite so dont leave them out on the floor or in your hand

**Media**
surplus with exploding pen box:

each pen (old):

https://user-images.githubusercontent.com/39013340/230535991-1a39d7fb-23e5-4c84-8e32-6823aaad5b03.mp4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: The Syndicate has started packaging its sinister pens in boxes for easier identification by the end user.

### CODE REVIEW

**Comment by keronshb** [comment]
This isn't the correct way to solve this issue. Ideally someone with a traitor mind would be able to see an alternate description of the item.

**Comment by EmoGarbage404** [comment]
> This isn't the correct way to solve this issue. Ideally someone with a traitor mind would be able to see an alternate description of the item.

That was pr'd and rejected by PJB.

**Comment by keronshb** [comment]
> > This isn't the correct way to solve this issue. Ideally someone with a traitor mind would be able to see an alternate description of the item.
> 
> That was pr'd and rejected by PJB.

Huh.

Well then honestly I don't think this should go through either.

**Comment by EmoGarbage404** [comment]
Honestly i think its pretty funny. Maybe consider giving the wrappers a unique look?

**Comment by keronshb** [comment]
Looking back at it, it's part of the fun not knowing what you got. It's a roulette box more or less unless you directly buy it.

**Comment by GoodWheatley** [comment]
The entire reason this is an issue is because traitors are accidentally triggering the explosive pen and killing themselves while trying to check what type of pen it is. Just remove explosive pens from surplus crates, problem solved.

**Comment by GoodWheatley** [comment]
I agree with keron that the best solution would be allowing traitors to know what type of pen it is on examine (which would also be nice for all the other stealthy traitor items that we keep removing unique descriptions from), but if PJB doesn't want that then removing the explosive pen from the surplus crate is the next best solution.

**Comment by Interrobang01** [comment]
Why is removing the pen from the surplus any better than what this PR does? Removing the pen makes the surplus just a tiny bit less random, while this PR doesn't have any similar drawbacks.

**Comment by Interrobang01** [comment]
One way to fix the problem could be to put a manifest on the surplus outlining all items contained within, using uplink names rather than examine names. Then again, it still wouldn't fully solve the problem of cluelessly activating the pen and dying.

**Comment by deltanedas** [comment]
what if the manifest says there's an e-dagger and an exploding pen?

**Comment by mirrorcult** [comment]
well then that's funny

**Comment by Interrobang01** [comment]
Good point. That is a rather unlikely occurrence, though.

I suppose some sort of logic could be implemented to put wrappers only on ambiguous items and only when they're in a surplus, but that may be out of scope.

Ultimately this PR is probably fine as it is.

**Comment by mirrorcult** [comment]
i think this PR is fine as is

**Comment by Emisse** [comment]
I think you should give the pen wrappers a unique sprite

**Comment by deltanedas** [comment]
like a modified chocolate bar or completely separate

**Comment by DawBla** [comment]
The ideal solution would be for Traitor PDA to show what type of pen is inserted in it.
It keeps traitors just like every other player (how PJB wanted) and just lets them use their unique PDA which they can lose

**Comment by CaptainSqrBeard** [comment]
I like this solution but it will be cooler if it wouldn't use chocolate wrappers.

**Comment by deltanedas** [comment]
committed toolbox again somehow lovely

**Comment by deltanedas** [comment]
@Emisse gave each funny pen a unique box is it good now

**Pull request merged**
