### PR TITLE
Rat kings can butcher things

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Rat kings have gained the ability to butcher animals and clothes

## Why / Balance

I noticed there were some rat kings who were hunting the kitchen animals but were incapable of actually butchering them to eat them. This helps them out a bit.

**Rats butchering Rats**
Yes, this does mean the rat kings can butcher their own rats, but I tested it locally to see if it was possible to go infinite.

After butchering all of my starting rats, I was not even capable of creating one new rat from the meat they gave me. Drinking blood was already nerfed quite a bit in previous PRs for the rat king as well so I doubt it will change much there.

## Technical details

SharpSystem's butchering was updated to work without hands

The EntityUid being used to butcher is set to the item the user is holding, otherwise it'll try to set it to the user, and if that fails it'll just be the default

## Media

https://github.com/user-attachments/assets/c8e98d77-1e40-43db-85a5-09b02df716e4

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: The rat king is now capable of butchering things, like animals.

### CODE REVIEW

**Comment by DogZeroX** [comment]
I wanted to give this ability to species/mobs with claws in general.

**Comment by Plykiya** [comment]
> I wanted to give this ability to species/mobs with claws in general.

just give them the SharpComponent if this ever gets merged

**Comment by ps3moira** [comment]
Wasn't there a PR that made it so there couldn't be self-sustaining rat kings feasting on there own blood? Wouldn't this undo that and cause the same balancing issue if they can butcher and eat their own rat servants

**Comment by Cojoke-dot** [comment]
> Wasn't there a PR that made it so there couldn't be self-sustaining rat kings feasting on there own blood? Wouldn't this undo that and cause the same balancing issue if they can butcher and eat their own rat servants

read pr description...

**Comment by ps3moira** [comment]
> > Wasn't there a PR that made it so there couldn't be self-sustaining rat kings feasting on there own blood? Wouldn't this undo that and cause the same balancing issue if they can butcher and eat their own rat servants
> 
> read pr description...

2 am reading pr's :trollface:

**Comment by slarticodefast** [comment]
https://github.com/user-attachments/assets/8d39b64a-637f-490f-9c18-d600f702ccdb

Since you set NeedHand to false in the DoAfterArgs BreakOnDropItem and BreakOnHandChange no longer work.

**Comment by Plykiya** [comment]
> butcher.mp4
> 
> Since you set NeedHand to false in the DoAfterArgs BreakOnDropItem and BreakOnHandChange no longer work. Otherwise this got conceptual approval.

tragedy

**Pull request merged**
