### PR TITLE
Changes to CE's suits

### PR DESCRIPTION
**Pull request by KingFroozy**
## About the PR

Fixed CE's jumpsuit being noisy with colors, added a proper icon and in-hands, also remade the jumpskirt sprites for consistency. Removed random blank sprites in jumpsuit folder and meta-file. Resprited CE's turtleneck for so said consistency.
## Why / Balance

Sprite & colour consistency.
## Technical details

None.
## Media

chief_engineeer

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

none.
**Changelog**

### CODE REVIEW

**Comment by KingFroozy** [comment]
Ignore the test fail probably, i didn't see any relation to the PR.

**Comment by deepdarkdepths** [comment]
Test fail is TryStopNukeOpsFromConstantlyFailing. As usual

**Review by EmoGarbage404 — DISMISSED** [review]
A few basic thoughts:

I like the more saturated yellow but the contrast is quite a bit higher for things like the detailing on the turtleneck. That should be fixed.

The darker color on the pants is cool but the posted screenshots have significantly simplified and reduced shading compared to the original. The original design of the pants and all the shading is fine: the only thing i would change is the color. It also has the same high-contrast issues as the top part of the outfit, especially with the darker colors on the outlines. It's especially noticeable on the skirts (To which all of this equally applies)

I do like the new vest and i think the reduction in visual noise helps it a lot. However, not having an outline on both sides of the straps gives it some contrast issues with the yellow suit below it. I think those should be restored. 

Additionally, the back of the vest has a section with very weird shading:
image

i feel like it should just continue the pattern on the rest of it and have some light shading on the lowest part.

As a final note, please submit screenshots of the art in-game. Seeing how it looks in a more natural environment is preferable to just screenshots from an editor.

**Comment by KingFroozy** [comment]
> A few basic thoughts:
> 
> I like the more saturated yellow but the contrast is quite a bit higher for things like the detailing on the turtleneck. That should be fixed.
> 
> The darker color on the pants is cool but the posted screenshots have significantly simplified and reduced shading compared to the original. The original design of the pants and all the shading is fine: the only thing i would change is the color. It also has the same high-contrast issues as the top part of the outfit, especially with the darker colors on the outlines. It's especially noticeable on the skirts (To which all of this equally applies)
> 
> I do like the new vest and i think the reduction in visual noise helps it a lot. However, not having an outline on both sides of the straps gives it some contrast issues with the yellow suit below it. I think those should be restored.
> 
> Additionally, the back of the vest has a section with very weird shading: image
> 
> i feel like it should just continue the pattern on the rest of it and have some light shading on the lowest part.
> 
> As a final note, please submit screenshots of the art in-game. Seeing how it looks in a more natural environment is preferable to just screenshots from an editor.

I did just copy the original colors of the jumpsuit to turtleneck for above said consistency, but sure.
I'll chalk more about it in discord channel so cya

**Comment by KingFroozy** [comment]
Made some requested changes, though colors are left untouched, as they're the same as the normal jumpsuit, so if there are still complaints about them, I'd like to leave it for a different PR.

Chief
Chiefy
Turtle
Turtly

Sorrs for being so late, my butt is too lazy and shy to speak up.

**Review by UbaserB — COMMENTED** [review]
Hi, just pointing out that some of the changes requested by emo still aren't fixed (see: pants for example)

**Comment by KingFroozy** [comment]
> Hi, just pointing out that some of the changes requested by emo still aren't fixed (see: pants for example)

They are? The shading is back to what it was, and I already pointed out that the colors are left, cause I don't want to make it inconsistent from the reqular jumpsuit. If Emo suggests changing the whole CE's palette, I'll do it though. And the back vest is the same as the reqular too, with which no one had any issues before (at least I didn't see any).

**Comment by UbaserB** [comment]
> They are? The shading is back to what it was, and I already pointed out that the colors are left, cause I don't want to make it inconsistent from the regular jumpsuit. If Emo suggests changing the whole CE's palette, I'll do it though. And the back vest is the same as the regular too, with which no one had any issues before (at least I didn't see any).

An example would be that the pants only have two colours for shading and this is still far too simplistic

**Comment by KingFroozy** [comment]
oh yeah, also, test fail is unrelated

**Comment by KingFroozy** [comment]
> A few basic thoughts:
> 
> I like the more saturated yellow but the contrast is quite a bit higher for things like the detailing on the turtleneck. That should be fixed.
> 
> The darker color on the pants is cool but the posted screenshots have significantly simplified and reduced shading compared to the original. The original design of the pants and all the shading is fine: the only thing i would change is the color. It also has the same high-contrast issues as the top part of the outfit, especially with the darker colors on the outlines. It's especially noticeable on the skirts (To which all of this equally applies)
> 
> I do like the new vest and i think the reduction in visual noise helps it a lot. However, not having an outline on both sides of the straps gives it some contrast issues with the yellow suit below it. I think those should be restored.
> 
> Additionally, the back of the vest has a section with very weird shading:
image
> 
> i feel like it should just continue the pattern on the rest of it and have some light shading on the lowest part.
> 
> As a final note, please submit screenshots of the art in-game. Seeing how it looks in a more natural environment is preferable to just screenshots from an editor.

Is there a chance I'm ever getting reviewed again?

**Review by UbaserB — COMMENTED** [review]
One more nitpick I noticed, can you make the border/outline on the skirt a bit less dark? It's weird considering the rest of the grey doesn't have it that way and it'd look nicer if so.

**Comment by KingFroozy** [comment]
> One more nitpick I noticed, can you make the border/outline on the skirt a bit less dark? It's weird considering the rest of the grey doesn't have it that way and it'd look nicer if so.

done, though idk if it's even noticeable. Also, ignore the force push, it's fixed (fuck it)

**Comment by UbaserB** [comment]
> > One more nitpick I noticed, can you make the border/outline on the skirt a bit less dark? It's weird considering the rest of the grey doesn't have it that way and it'd look nicer if so.
> 
> done, though idk if it's even noticeable. Also, ignore the force push, it's fixed (fuck it)

I can't tell the difference

**Comment by KingFroozy** [comment]
upd

> I can't tell the difference

Now what? I'm starting to get exhausted of this tbh.

**Comment by KingFroozy** [comment]
@slarticodefast soooooo, whatcha think about finally merging it?

**Comment by slarticodefast** [comment]
> soooooo, whatcha think about finally merging it?

I just added the label because the others forgot to do that.
This needs art director approval

@UbaserB

**Pull request merged**
