### PR TITLE
Adding whitelist to pill cannisters

### PR DESCRIPTION
**Pull request by BlitzTheSquishy**
## About the PR

Added a whitelist to Pill Cannisters to reduce their ability to be used for powergaming.

## Why / Balance

Due to the lack of a whitelist on pill cannisters it is possible to put 300u of reagents inside a single pill canister via the use of bottles, as well as effectively doubling that again with the use of combat medkits (though with those it's intentional). 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by BlitzTheSquishy** [comment]
Oki doki I think that's all

I should mostly note cause there are issues with medics using this in downstream servers (Delta-V) to hold extremely high amounts of meds for little cost to themself.

**Comment by mirrorcult** [comment]
@EmoGarbage404 did you have any strong opinion on this

**Comment by EmoGarbage404** [comment]
i think whitelisting this (like most of these basic small container whitelists) is really dumb when its just pointing out the fact that our itemsizes on the whole trend way too small. If all items marked tiny were _actually_ the same size then it'd make sense but people arbitrarily buff item into the smallest size possible because they are afraid of inventory management.

i'd rather see problematic items like bottles and beaker nerfed to 1x2 or 2x2 instead of this comedic race to the bottom where everything is just a 1x1.

**Comment by EmoGarbage404** [comment]
and just to clarify further: the whole point of item sizes was to fix this super common issue where you weren't able to have lots of small things stored in a container without also allowing larger items to be in there. You couldn't have a bag that stores 10 tiny things without also allowing it to store small things.

I feel like that kind of logic was a large factor in why a lot of things had such pointlessly restrictive whitelists and I don't think this really addresses the core problem. Sure, it solves it for the single instance of pill canisters, but it doesn't do much for many other situations.

**Comment by Emisse** [comment]
you could just make the pill canister have a lot of small segmented 1x1s instead of whitelist

**Comment by EmoGarbage404** [comment]
> you could just make the pill canister have a lot of small segmented 1x1s instead of whitelist

the issue with the 1x1s is that bottles are also confusingly 1x1 despite carrying like triple the amount of chem in them

**Comment by Emisse** [comment]
just make them a size bigger

**Comment by Emisse** [comment]
we got the sizes and the shapes for this porpoise

**Comment by thebadman4662** [comment]
> > you could just make the pill canister have a lot of small segmented 1x1s instead of whitelist
> 
> the issue with the 1x1s is that bottles are also confusingly 1x1 despite carrying like triple the amount of chem in them

Not triple, 50% at best. Pills can have whole 20u in them.

**Comment by deltanedas** [comment]
its still op because of how useful an entire pharmacy in a single canister is compared to a few pills you can hand out on halloween

**Comment by BlitzTheSquishy** [comment]
> you could just make the pill canister have a lot of small segmented 1x1s instead of whitelist

This doesnt work

bottles are 1x1
syringes are 1x1

**Comment by BlitzTheSquishy** [comment]
> > > you could just make the pill canister have a lot of small segmented 1x1s instead of whitelist
> > 
> > 
> > the issue with the 1x1s is that bottles are also confusingly 1x1 despite carrying like triple the amount of chem in them
> 
> Not triple, 50% extra at best. Pills can have whole 20u in them.

The main thing here is that pills are harder to control the exact dosage at the time of dispensing, while bottles you can always choose the dosage while pills are locked at a single dosage upon creation..

**Comment by BlitzTheSquishy** [comment]
> we got the sizes and the shapes for this porpoise

and what size/shape would you make a pill canister that holds 10 items (hopefully pills) or pills. If you want to compress other meds combat medkits already half their space (intentional), and it's printable!

In my own honest opinion... why wasn't this whitelisted to pills only already?

**Comment by packmore** [comment]
if the permanent solution is going to take a long time to write, i would rather have a temporary bandaid that will later get reverted.
this change is good. most "tiny" items in game still would not fit in a pill bottle, even if we kept the ones that realistically would still be tiny. a pen is not going to fit in a pill bottle. the whitelist makes sense imo.

**Comment by BlitzTheSquishy** [comment]
I would also like to add the point of magazines, though yes its a different system. 
ALL BULLETS are 1x1, but they compress down in a magazine which represents that they are even smaller than a 1x1
This should be the same for pills

**Comment by K-Dynamic** [comment]
> I would also like to add the point of magazines, though yes its a different system. ALL BULLETS are 1x1, but they compress down in a magazine which represents that they are even smaller than a 1x1 This should be the same for pills

Yeah we did this already for swabs, they went from storage box to dispenser

Don't forget to change the pill bottle to a non-copyright pez dispenser :trollface: 

Cigarette box? Cigarette dispenser :trollface:

**Comment by BlitzTheSquishy** [comment]
> > I would also like to add the point of magazines, though yes its a different system. ALL BULLETS are 1x1, but they compress down in a magazine which represents that they are even smaller than a 1x1 This should be the same for pills
> 
> Yeah we did this already for swabs, they went from storage box to dispenser
> 
> Don't forget to change the pill bottle to a non-copyright pez dispenser :trollface:
> 
> Cigarette box? Cigarette dispenser :trollface:

we can leave the canisters (case what if you want multiple types of pills, or a two step pill or whatever) it was just an example

**Comment by metalgearsloth** [comment]
This seems to be a no from what I've read from maints for reasons above.

**Comment by BlitzTheSquishy** [comment]
> This seems to be a no from what I've read from maints for reasons above.

I will note that my responses to the maintainers weren't taken into account, nor responded in turn.

**Comment by BlitzTheSquishy** [comment]
https://github.com/space-wizards/space-station-14/pull/33074 it got merged anyway, in one way or another

**Pull request closed without merging**
