### PR TITLE
Minify meta.json files

### PR DESCRIPTION
**Pull request by metalgearsloth**
These were always supposed to be minified we just got lazy. Also a handful of files were saved as utf-8 bom which I have updated to utf-8 (all of the cigar files + a handful of othe rones).

I also included the script I used to do it + checked it ingame.

### CODE REVIEW

**Comment by mirrorcult** [comment]
i really hate it if we're doing this, these are way harder to edit and rsiedit doesn't emit them minified anymore (+ people are unlikely to want to do if they're not using rsiedit) so it's just going to pile up again

what is the motivation, just reduced line count? i don't really think it matters

**Comment by metalgearsloth** [comment]
If we do intend these to be hand editable now then it should just be yml like everything else.

**Comment by DrSmugleaf** [comment]
> rsiedit doesn't emit them minified anymore
Minified JSONs is a setting in RSIEdit, it could be enabled by default.
https://github.com/space-wizards/RSIEdit/blob/a4a1dd9c66607cee3909908e848157c643e0ae6e/Editor/Models/Preferences.cs#L24

**Comment by moonheart08** [comment]
> If we do intend these to be hand editable now then it should just be yml like everything else.

We've established multiple times they should be YML.
wyci

**Comment by PJB3005** [comment]
> We've established multiple times they should be YML.

Please no I don't want to have slow-ass YAML loading even more. Also YAML libraries in e.g. Python are all garbage compared to `YamlDotNet`.

If you wanna edit minified JSON files just install something like [this](https://marketplace.visualstudio.com/items?itemName=eriklynd.json-tools) into VSCode. One command to format the JSON (so it's readable) and another to pack it back down when you're done.

Also if we don't wanna minify the JSON at least change the editorconfig to match the current style we have (2 space indents).

Also merge #12997 first please I beg

**Comment by DrSmugleaf** [comment]
> We've established multiple times they should be YML. wyci

when

**Comment by AJCM-git** [comment]
The maintainer council has deemed this as cringe as it would make things harder to edit and review for no real gain

**Pull request closed without merging**
