### PR TITLE
Remove drone AA

### PR DESCRIPTION
**Pull request by metalgearsloth**
Originally I wanted to also have mice able to go under doors but they die almost immediately due to respiration.

:cl:
- tweak: Drones can now go under doors. They also are no longer considered flying and don't have all-access.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Closing in favor of the sergal's idea.

**Comment by metalgearsloth** [comment]
Okay I forgot no one's gonna be coding that for a hot minute and this is probably better to reduce the ahelp quantity.

**Comment by mirrorcult** [comment]
is this still necessary with the drone interaction cleanup? seems like rogue drones are not as prevalent now

**Comment by moonheart08** [comment]
> is this still necessary with the drone interaction cleanup? seems like rogue drones are not as prevalent now

Yes, so they can't open doors for people.

**Comment by mirrorcult** [comment]
conflic

**Pull request merged**
