### PR TITLE
Make air tanks appear on the back in suitstorage

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## Why / Balance
it looks nice

also does it to jetpacks

## Media
image

image

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by UbaserB** [comment]
Can you include jetpacks too (they can act like air tanks)

**Comment by Dutch-VanDerLinde** [comment]
i will for the ones that can fit in there

**Comment by Hanzdegloker** [comment]
this PR makes me whole, lovely work

**Comment by Yousifb26** [comment]
Where does the backpack/duffle go (if you have one on)

**Comment by Dutch-VanDerLinde** [comment]
> Where does the backpack/duffle go (if you have one on)

behind the air tank

**Pull request merged**
