### PR TITLE
Fancy table

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Port Fancy tables from TG

carpet manufacturing added. Players are now able to print, stitch and collect carpets from the floor, as well as cut them into cloth.

Added new tables that you can place a rug on to cover them like a tablecloth

## Why / Balance
Fancy 

## Media
image

https://github.com/space-wizards/space-station-14/assets/96445749/9c3f4d85-a3e9-45ea-a316-e8b7f32f6f08

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:

- add: Carpets can now be printed at the uniform printer.
- add: Carpets can be collected from the floor and buthered into fabric.
- add: New white and cyan carpets.
- add: Carpets can now be placed on wooden tables to get beautiful new tables with tablecloths.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Looks nice

**Comment by UbaserB** [comment]
can you add a white version as well

**Comment by TheShuEd** [comment]
image

**Comment by DogZeroX** [comment]
Shouldn't you be able to make this by putting carpet on top of tables? In a perfect world you would be able to add and remove them, like an overlay.

**Comment by TheShuEd** [comment]
dont merg

**Comment by TheShuEd** [comment]
https://github.com/space-wizards/space-station-14/assets/96445749/9c3f4d85-a3e9-45ea-a316-e8b7f32f6f08

**Comment by UbaserB** [comment]
> 2024-02-26.17-10-10.mp4

oh my god, this is a feature we need forever.

**Pull request merged**
