### PR TITLE
organs edible to lizards, and make their food contents uncooked proteins

### LINKED ISSUE #20881: Lizards can't eat organs
## Description

Probably simply just not tagged as meat.

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Added the meat tag to organs so lizards can consume them with their whitelisted stomach.
Changed nutriment within organs to uncooked protein so only animals can safely consume them without cooking.
resolves #20881

NPC mobs will also avoid eating brains to make player's lives just a tiny bit better.

## Why / Balance

Food.
You can get round removed by a random mouse interrupting borging.

## Technical details

Nothing complex, added tag.
Changed nutriment to uncooked protein.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- fix: Lizards can eat organs again!
- tweak: Organs now contain uncooked proteins instead of edible nutriment. Animals will be able to consume this.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
missed a few

**Comment by QuietlyWhisper** [comment]
> Can you also tag them as BadFood so mice won’t eat gibs

why wouldn't mice eat gibs?

**Comment by GoodWheatley** [comment]
> > Can you also tag them as BadFood so mice won’t eat gibs
> 
> why wouldn't mice eat gibs?
> 
> it's morbid and looks funny

Can you at least tag the brain as BadFood so people don’t get round removed by a mouse in disposals

**Comment by QuietlyWhisper** [comment]
> > > Can you also tag them as BadFood so mice won’t eat gibs
> > 
> > 
> > why wouldn't mice eat gibs?
> > it's morbid and looks funny
> 
> Can you at least tag the brain as BadFood so people don’t get round removed by a mouse in disposals

that's fair

**Comment by QuietlyWhisper** [comment]
ok done

**Comment by notquitehadouken** [comment]
top 0b10 ways to dispose of gibbed bodies as syndie
0b1: Consume the flesh
0b10: Don't

**Comment by deltanedas** [comment]
also from testing stomach metabolises reagents injected which is bad

**Review by LankLTE — APPROVED** [review]
My bad on missing this.

**Comment by LankLTE** [comment]
> also from testing stomach metabolises reagents injected which is bad

~~Great time to leave a comment~~ 
Do you mean proteins are metabolized by stomach if injected? That’s unrelated to this PR if so.

**Comment by deltanedas** [comment]
yeah any drink or food is and yes its unrelated

**Comment by deltanedas** [comment]
also im idiot and commented on wrong pr :trollface:

**Pull request merged**
