### PR TITLE
Nerf paramed PDA scanning speed and buff all others to be the same

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

This changes all pdas to scan in 1 sec

## Why / Balance

~~I found it weird that CMO and peramed had different scantimes on their pda. This makes the cmo's scanner as fast as the perameds~~

Maintainers want it nerfed, you get what you asked for!

~~If  you prefer then ask me to nerf perameds pda scantime instead.~~

all are 1 sec now

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Vasilis
- tweak: All pda's with built in medical scanners now take one second to scan.

### CODE REVIEW

**Comment by deltanedas** [comment]
neither of them should be fast imo

**Comment by VasilisThePikachu** [comment]
yeah i was unsure myself, i can nerf it if most agree no need to make a new pr

**Comment by EmoGarbage404** [comment]
Nerf both of these. Paramed power creep is dumb af

**Comment by LankLTE** [comment]
Honestly I'd say just make all of them 1.2. iirc interns have a slower one while CMO and now paramed (maybe chem?) has a faster one- it's kind of inconsistent and weird

**Comment by VasilisThePikachu** [comment]
Meh i dont know about nerfing others, they seem fine

**Comment by MaloTV** [comment]
>:( No

**Comment by VasilisThePikachu** [comment]
> > :( No

:trollface: :

**Comment by Emisse** [comment]
just make them all the same

**Comment by VasilisThePikachu** [comment]
> just make them all the same

Well they already be the same now, all are 1 second. Medical scanner is left how it is and I think it should stay like that.

**Comment by LankLTE** [comment]
> Well they already be the same now, all are 1 second. Medical scanner is left how it is and I think it should stay like that.

Like I said in my earlier reply, Doctor's is 1.2 and Interns have 1.4. Just make them all 1 for consistency's sake.

**Comment by Equivocateur** [comment]
Did everyone here collectively agree to not mention that its "P**a**ramed" and not "P**e**ramed"?

**Comment by Partmedia** [comment]
Because of the spelling problem, and because the changes are not significant to warrant a Changelog, I have elected to remove it.

**Comment by Partmedia** [comment]
I agree that there is no reason for the PDAs to scan at different speeds. Let's just make them all the same.

**Comment by VasilisThePikachu** [comment]
I think this should have a cl

**Comment by LankLTE** [comment]
I agree, this is pretty notable (especially for parameds)

**Review by LankLTE — APPROVED** [review]

**Pull request merged**
