### PR TITLE
More Sprites

### PR DESCRIPTION
**Pull request by SweptWasTaken**
This adds sprites for Xenos, Shuttles, Singulo, Various NPCs that will need to be sorted at one point, Hydroponics, Mechs, Corgi stuff, PDAIcons, Wizard, Magic Effects and slimes.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Sorry for that comment, this PR was crashing my browser. 

This adds sprites for Xenos, Shuttles, Singulo, Various NPCs that will need to be sorted at one point, Hydroponics, Mechs, Corgi stuff, PDAIcons, Wizard, Magic Effects and slimes.

**Comment by PJB3005** [comment]
I'm not fond of just copying random sprite in wholesale with no projected use in sight.

About shuttles: Eris shuttles are specially drawn to match the shuttle layout. This of course makes them look great, but it does make me unsure their sprites are suited to being copied in wholesale. There's also a ton of them.

Mechas: aren't there proposals for like modular mechs, hell even ones that are actively being used by other servers? Again I'd rather import these sprites when such a feature gets implemented so that we're not committing sprites we won't use anyways. Also you didn't cut out unlit variants for states as far as I can tell.

Xenos: some of the action buttons you implemented might still have to be edited later to fit into our actions system when we implement it, so...

Can you see where I'm going with this?

**Comment by SweptWasTaken** [comment]
#277  and #278 
So were these joke issues?

Memory said he would work on shuttles so I converted the sprites. He didn't end up working on them but I put them in anyway. 
We've been talking about wander AI recently so I got a ton of npc sprites from ERIS and converted them.
We were also talking about adding in a simple gamemode so I converted Wizard.

Bla bla bla

So should we just not add sprites if their underlying systems are not being worked on at this exact moment? It's like 1.31mb, it's not adding bloat to the project if they're available in the sprites folder for when people want to work on them.

**Comment by PJB3005** [comment]
> #277 and #278
So were these joke issues?

Neither of these issues implied this. The first one is just implementing stuff like clothing which is a massive "can't go wrong". This still implies having an actual implementation instead of simply dumping them into the textures folder. The second one is fixing missing inhands for tools and whatever that were added before we, well, coded inhand support.

> So should we just not add sprites if their underlying systems are not being worked on at this exact moment?

I'd rather add sprites once we have a better idea for how the sprites will be used, yes. This can be quite different from regular SS13.

**Pull request closed without merging**
