### PR TITLE
Show role playtimes in lobby

### PR DESCRIPTION
**Pull request by metalgearsloth**
Doesn't look the greatest but this screen already needs some cleanup.
Needs https://github.com/space-wizards/RobustToolbox/pull/4449 to not shift on first scroll.

image

:cl:
- add: Added role playtimes on the lobby screen so you can stop asking admins.

### CODE REVIEW

**Comment by crazybrain23** [comment]
Will there be a way to see total playtime?

**Comment by metalgearsloth** [comment]
> Will there be a way to see total playtime?

Future PR, ideally it would use a gridcontainer rather than what I did but that would also require redesigning the entire screen.

**Comment by EmoGarbage404** [comment]
put a margin between the times and the buttons, you animal

**Comment by forgotmyotheraccount** [comment]
i'd recommend ditching the second counter to reduce visual clutter but as you said the screen as a whole could use a bit of an overhaul, nothing wrong with this for the time being

**Comment by crazybrain23** [comment]
> i'd recommend ditching the second counter to reduce visual clutter but as you said the screen as a whole could use a bit of an overhaul, nothing wrong with this for the time being

I think it might be DD:HH:MM, if it's like the admin command.

**Comment by metalgearsloth** [comment]
Gonna make it a separate screen formatted better when I get time, this was just a placeholder.

**Pull request closed without merging**
