### PR TITLE
give gas analyzer UI higher precision

### PR DESCRIPTION
**Pull request by qwerltaz**
## About the PR

Mainly, I propose higher precision for the gas analyzer.
- Add 3 decimal places to gas analyzer UI moles, and make them dimmer.
- Decimal mole representations in the analyzer UI now align for all gases (unless the moles are in hundreds or more).
- Stop sending gas info to the client gas analyzer UI if there's less gas than the minimum to be displayed. This prevents the UI from showing "zero" moles of gas.

Some comments that I addressed:
- as for clarity, I tried to address this by changing the text color from default almost white to full white, which distinguishes the digits more.
- as for performance due to higher precision, as I understand it, gas moles are always stored as floats with 15-digit precision. the gas mix sent from the server to the client in `GasAnalyzerUserMessage` already has this precision, and is only rounded by the client.

## Why / Balance

My view is that higher precision gives more feedback to the player and gives engagement opportunities. Every mole has its story. Let's say there's 0.00017 mol frezon in the air. where did it come from? Are we near Atmos? Was it a slight leak on their side? Was there a usual gas leak? did an ice anomaly go critical somewhere? How about 0.00200 mol of nitrous oxide? Are there many slimes on the station? Or was someone trying to gas a department, or have a laughing party (talking from experience)? Sometimes you can infer a lot just from seeing any digits at the gas analyzer. It encourages engagement with the world. These possibilities drop with lower precision. 5-digit precision seems like a good middle ground. 
Amounts meaningful to reactions are in full white to still be easily distinguishable

## Technical details

- `GenerateGasEntryArray` now takes the analyzer component and uses its `UIMinMoles` to decide whether to send a UI message.

## Media

23-11-25_238_dotnet

23-11-25_237_dotnet

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The gas analyzer Now has higher precision.
- fix: The gas analyzer no longer displays a gas when there's "zero" of it.

### CODE REVIEW

**Comment by chromiumboy** [comment]
You have adequately explained the need for higher levels of precision in the mol readings. Gameplay wise, it is not useful, and I dont see how it help with player engagement like you claim. Knowing that there is 0.00017 mol of Frezon is no more helpful than knowing there is 0.00 mol of Frezon present

The additional digits creates a big block of text which is hard to read. On top of the last three digits a dark grey. This makes the text less legible overall

**Comment by qwerltaz** [comment]
> Knowing that there is 0.00017 mol of Frezon is no more helpful than knowing there is 0.00 mol of Frezon present

Yes, it doesn't change much in terms of gameplay. But The "0 mol" is pretty unintuitive. It's quite confusing as to what it means at first. And I myself have grown to just fully ignore it. And one solution is to just not show the gas when it's below 0.01mol, but another is to increase the precision so it's not confusing still, but also retains the fact that these gases were here and we see their remnants, it retains some history of the tile. And again what I wrote in Why/Balance. That's how I feel about it a least.

> The additional digits creates a big block of text which is hard to read. On top of the last three digits a dark grey. This makes the text less legible overall

This might be up to preference, but I don't have the UI expertise to confidently answer, unfortunately. All I can say is that after some time playing with it, I still like using it.

**Comment by qwerltaz** [comment]
I see. Thank you for your time.

**Comment by Partmedia** [comment]
Thanks for your submission. We know that it takes time to put these PR's together. It can help to discuss proposed changes on Discord first, I believe in this case the same issues were [brought up earlier](https://discord.com/channels/310555209753690112/1120041991753961583/1177642225522442322).

**Pull request closed without merging**
