### PR TITLE
Fix some lathe recipe textures showing up blank

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Updated all parts of lathe recipe UI to use EntityPrototypeView rather than layered textures

## Why / Balance

Stuff that was fabricating was showing up incorrectly and looked weird

## Technical details

Newly introduced EntityPrototypeView handles getting the appearance of an entity based off its EntityPrototype, making it easier to deal with entities that create their appearance by layering their sprite

I had to reimplement the queue list without using ItemLists since ItemLists don't use EntityPrototypeViews.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/3ab1d059-f74f-4981-b1ec-b9de086e39db

**Changelog**

- fix: Lathe recipe UI updated so that textures appear correctly.

### CODE REVIEW

**Comment by deltanedas** [comment]
i think you can use gamer table now instead of beloved ItemList

**Comment by Plykiya** [comment]
> i think you can use gamer table now instead of beloved ItemList

like, the tables in #28484? I... I guess I could? But I still don't know how to uh, get it to limit its height and contain it with a scroll bar when it gets too large

**Comment by ShadowCommander** [comment]
You can probably use ListContainer for this. I made it to be a more customizable ItemList.

**Comment by Plykiya** [comment]
> You can probably use ListContainer for this. I made it to be a more customizable ItemList.

does it uh... does it work without buttons... cause I'm just displaying stuff, not really any buttons involved

**Comment by ShadowCommander** [comment]
If you don't want buttons, then the queue should be short enough to just use a BoxContainer with a ScrollContainer, but I was thinking you should be able to click on the queue to cancel entries in the queue.

**Comment by Plykiya** [comment]
> If you don't want buttons, then the queue should be short enough to just use a BoxContainer with a ScrollContainer, but I was thinking you should be able to click on the queue to cancel entries in the queue.

thank you for the ScrollContainer wisdom

**Comment by Plykiya** [comment]
I fixa tha lathes
image

**Pull request merged**
