### PR TITLE
moths can eat goat wool

### LINKED ISSUE #21670: moths should be able to eat goats coats
## Description
title

if nobody else does it i might in a day or so

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
resolves #21670

moths can eat goats wool and then wait for it to regrow when fed

shearing does not exist but might add later, convert 3 fiber to 1 cloth so when eaten its more nutritious but cloth gives 3 fiber when ground so no funny business is possible

## Why / Balance
more source of food for moth friend

## Technical details
added Wooly system basically udder but better
changed food slightly to support the use case and have no issues, meaning `RequireDead` was added since having to kill a goat to eat its wool would be weird

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/972dea44-d870-413b-b55c-40d532f2e460

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Goats now grow wool which moths can eat.

### CODE REVIEW

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
works for me

**Comment by lzk228** [comment]
is there a conflicts with milking?

**Comment by deltanedas** [comment]
idk

**Comment by deltanedas** [comment]
alt clicking with bucket milks
alt clicking without eats
using eat verb with bucket eats

**Pull request merged**
