### PR TITLE
remove _activeDoors, use query instead

### LINKED ISSUE #14282: SharedDoorSystem manually tracks doors
## Description
`_activeDoors` :skull:

might fix tomorrow if im done with ninja reviews

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
storing state in the system is bad, so changed it to use EntityQuery
afaik the only information stored in it was if it was opening and had no state change, but nothing seems broken since updating already checked if it had no state change to ignore it.
everything i can think of works fine on a hallway door, havent tested high security as i assume it behaves the same.

closes #14282 

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by metalgearsloth** [comment]
have you profiled

**Comment by deltanedas** [comment]
no, however it doesnt seem any slower, even on debug

**Comment by metalgearsloth** [comment]
the only reason it existed was coz doors were taking 1ms ticktime from updating every tick.

**Comment by deltanedas** [comment]
:skull:

**Comment by ElectroJr** [comment]
You can still remove _activeDoors by just adding an active door comp & moving some data like the next state change over to that component.

**Pull request closed without merging**
