### PR TITLE
Change PlantAdjustAttribute to use Probability

### PR DESCRIPTION
**Pull request by PolterTzi**
## About the PR

Removes the Prob variable from PlantAdjustAttribute and makes it use Probability instead, like effects reagent effects.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

The Prob variable in the PlantAdjustAttribute prototype has been removed. Probability should be used instead.

### CODE REVIEW

**Review by Partmedia — CHANGES_REQUESTED** [review]
Please review the [pull request guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html) particularly about lumping fixes with functional and breaking changes.

**Comment by PolterTzi** [comment]
Point taken.

**Comment by PolterTzi** [comment]
Alright, I removed the changes directly referring to the guidebook, should be singular enough, I hope.

**Comment by Partmedia** [comment]
Thanks, this looks reasonable. I can't test this right now; do you happen to have screenshots/videos demonstrating the new code working? (this is also something that the pull request guidelines ask for)

**Comment by PolterTzi** [comment]
There wasn't really anything added, so the code handling Probability should now be the same that does so for other effects, but I'll record a test for added certainty.

**Comment by PolterTzi** [comment]
Not exactly the most scientific, hard to demonstrate randomness, but this shows MutationMod increasing after left4zed is added.

https://github.com/space-wizards/space-station-14/assets/62557990/29aef339-7018-42c5-9e8f-5500d7d839b8

**Review by Partmedia — APPROVED** [review]

**Comment by Partmedia** [comment]
Thanks for your contribution!

**Pull request merged**
