### PR TITLE
Fix for Mopped chems not transfering

### PR DESCRIPTION
**Pull request by Titian3**
## About the PR
A recent PR (#18758) from @Fahasor fixing several mopping and transfer issues has cause the transfer of solutions to stop working.
This fix builds on that PR to solve all the issues listed below:
- #19156 - Nonwater solutions not transferring to solution container.
- #18756 - Solution Visual not updating on bucket.
- #18755 - Solution Visual not updating on Mop.
- #17036 - Partial solution transfers and full transfers

**Media**
Video shows the following tests which covers the above issues, I've speed it up so you don't have to suffer this Jani gameplay loop for long..:
- Full transfer Test with water(10 water bucket, 10 weldFuel mop):
- Full transfer Test without water(30 weldFuel bucket, 10 weldFuel mop):
- Partial transfer Test with water(240 weldFuel bucket, 10 water bucket, 25 water mop, 25 weldFuel mop):
- Partial transfer Test without water(240 weldFuel bucket, 25 water mop, 25 weldFuel mop):
- Visual on mop update
- Visual on bucket update

https://github.com/space-wizards/space-station-14/assets/47093363/bb9e8bdc-6169-4af0-b307-b1e2d9e85508

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Repo
- fix: Janitors have remembered how to wring a mop, mops can transfer chemicals back to buckets etc again.

### CODE REVIEW

**Comment by Titian3** [comment]
Not sure why these build tests keep failing for me 😟 But they all passed locally.

**Comment by Fahasor** [comment]
Eeew, sorry?

**Comment by ficcialfaint** [comment]
> Not sure why these build tests keep failing for me 😟 But they all passed locally.

Nw, it's not your fault

**Comment by hord-brayden** [comment]
anxiously awaiting this one, thanks for jumping on this @Titian3

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
