### PR TITLE
Adds examine values to armor

### PR DESCRIPTION
**Pull request by rolfero**
## About the PR 

You can now examine armors to see their armor values

(Related to #11090, #11091)

**Screenshots**

Edit: New screenshot, new color

lightblue-comparison

**Changelog**

:cl:
- add: Armors shows their armor values when examined!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Just a nitpick, but i think the percentages should be colored green, not orange. Makes more sense for a positive attribute to be colored with a more positive color.

**Comment by rolfero** [comment]
> Just a nitpick, but i think the percentages should be colored green, not orange. Makes more sense for a positive attribute to be colored with a more positive color.

I think green should be used sparingly, since it could be harder to read on when the background is especially light. Maybe white or blue is a better option?

green-comparison
white-comparison
lightblue-comparison

**Comment by moonheart08** [comment]
Go with the blue.

**Comment by rolfero** [comment]
> Go with the blue.

Commited this change

**Pull request merged**
