### PR TITLE
clown mimimi sleeping sound

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

~~I could not find the origins of the sound so no attribution i guess (please)~~

**Media**

https://github.com/space-wizards/space-station-14/assets/40753025/3d863063-bb54-43c1-8f09-9deccf73f26b

**Changelog**

:cl:
- add: clowns now make funny sound when sleeping

### CODE REVIEW

**Comment by deltanedas** [comment]
why this for clown only

**Comment by Slava0135** [comment]
maybe I should make it a different component? so you can customize

**Comment by Emisse** [comment]
you need to find the sound attribution or this wont be merged

**Comment by Slava0135** [comment]
found different sound, not as silly though

https://github.com/space-wizards/space-station-14/assets/40753025/c4692e37-9d74-4e91-91c5-a8b2c53fae29

**Comment by LankLTE** [comment]
Don't take my word as fact because I might be wrong, but I dug around a bit and it seems the sound originates from here: https://soundbible.com/1683-Silly-Snoring.html
It dates back to 2011 (at least) and I can't find any traces of it before that. Also says it's public domain so.. go for it, I guess?

**Comment by Slava0135** [comment]
found different sound, not as silly though

https://github.com/space-wizards/space-station-14/assets/40753025/c4692e37-9d74-4e91-91c5-a8b2c53fae29




> Don't take my word as fact because I might be wrong, but I dug around a bit and it seems the sound originates from here: https://soundbible.com/1683-Silly-Snoring.html It dates back to 2011 (at least) and I can't find any traces of it before that. Also says it's public domain so.. go for it, I guess?

thanks!

**Comment by Slava0135** [comment]
god damn github for keeping text from previous comment

**Comment by Slava0135** [comment]
maybe i will keep the other sound for animals?

**Pull request merged**
