### PR TITLE
Atomic bomb add uranium 

### PR DESCRIPTION
**Pull request by kerisargit**
## About the PR
The "nuclear bomb" cocktail now adds uranium to the body rather than radium.

## Why / Balance
1. Because uranium is used to create the cocktail
2. It makes sense for the antagonists to hack into the alcohol distributor in order to get uranium.

- [ ] This PR does not require an ingame showcase

**Changelog**
- tweak: The "nuclear bomb" cocktail now adds uranium to the body instead of radium

### CODE REVIEW

**Comment by keronshb** [comment]
Please try updating to master to see if it fixes the failed test.

**Comment by kerisargit** [comment]
All tests completed successfully ＼(^ω^＼)

**Comment by LankLTE** [comment]
Changelog should probably better reflect that the *drink* is what's being modified.

**Comment by kerisargit** [comment]
I was changed it

**Comment by LankLTE** [comment]
Looks good, thanks.

**Pull request merged**
