### PR TITLE
Entirely remove Splitstation and Waystation.

### PR DESCRIPTION
**Pull request by moonheart08**
## Why?
Instead of going through and pointing out every single flaw with these maps, I'll put it at this:
- Waystation is not liked by the playerbase and is generally a broken map due to perfectly recreating it's original instead of being playable.
- Splitstation looks **horrible**, and doesn't execute many of it's ideas well. Like the above, it's not a super widely liked map.

It's worth noting this means we now have two empty slots for new maps should this get merged.

**Changelog**
:cl: moony
- remove: Entirely removes Splitstation and Waystation from the game.

### CODE REVIEW

**Comment by Peptide90** [comment]
And is this an executive decision or a personal one? I’ve seen equal people say they like and dislike split so who’s the majority who think it looks horrible, considering it’s just recently been updated? And if we’re replacing it with another square then bravo.

**Comment by Elijahrane** [comment]
I like splitstation

**Comment by Just-a-Unity-Dev** [comment]
I too like split station, I havent seen a single shred of feedback (GH issues or Peptide being pinged), so I find this weird how a neutral (not too liked, not too hated) by the community is being removed. Waystation I'm fine, it was jank and some core features (see emergency shuttle) didn't even work.

**Comment by Partmedia** [comment]
I like split, and would be in favor of removing Waystation (since there's Packed).

I do think that the split idea could be executed better, for example, by having separate distro and power networks so that north and south station are really "split", but first we'd have to decide to save split!

**Comment by Peptide90** [comment]
> I like split, and would be in favor of removing Waystation (since there's Packed).
> 
> I do think that the split idea could be executed better, for example, by having separate distro and power networks so that north and south station are really "split", but first we'd have to decide to save split!

Fun fact, power is already split. Most generation happens below but the top station has it's own SMES bank. It also has room for it's own distro, can't remember if I implemented it but it's easy to do.

**Comment by liltenhead** [comment]
I like Split, Not too big on Waystation though.

**Comment by Ablankmann** [comment]
Split is an okay map tbh, but I can understand Waystation being removed. Not a fan of that one

**Comment by PaulRitter** [comment]
Because there seems to be confusion about if this is a decision by the maintainer team or not:
No, this is a suggestion by moony, nothing more, nothing less.

**Comment by Peptide90** [comment]
> Because there seems to be confusion about if this is a decision by the maintainer team or not:
> No, this is a suggestion by moony, nothing more, nothing less.

I do respect it was given the needs discussion tag straight away but I was under the impression discussion, especially ones that might rack up lots of comments should happen in discord. This is resolved on my part now anyways but it’s at least a shock to see something in the GitHub channel with zero prior warning or discussion. That is all :)

**Comment by metalgearsloth** [comment]
I think peptide is actively seeking to maintain split so we can probably close this given way got removed?

**Comment by mirrorcult** [comment]
yea we should be good now

**Pull request closed without merging**
