### PR TITLE
Red version of cap cap for the HOS

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Gives the HOS a red version of the Captain's cap cap
## Why / Balance

it shouldn't affect balance, it's a hat. as for why it should be added, currently there are three "formal" suits (red, green, and blue) and two matching caps (blue and green), this would add in the missing cap (red) for the HOS.
## Technical details

n/a
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

## Breaking changes

n/a
**Changelog**

:cl:
- add: Added a red HOS cap like the captain's blue one.

### CODE REVIEW

**Comment by lzk228** [comment]
nuhh, hos isn't goin to drip

**Comment by MACMAN2003** [comment]
i don't think that ubuntu build error is related to a few yaml changes

**Comment by UbaserB** [comment]
I think this takes the individuality away from the cap’s cap and makes it more of a generic item that several heads/etc have. I dont mind the idea of hos having a proper hat, but it was probably be best to have a unique sprite.

**Comment by MACMAN2003** [comment]
> I think this takes the individuality away from the cap’s cap and makes it more of a generic item that several heads/etc have. I dont mind the idea of hos having a proper hat, but it was probably be best to have a unique sprite.

in my defense only the captain, hos, and centcomm, have formal suits so it'd make sense for the hos to have a cap as well

**Comment by EmoGarbage404** [comment]
i really don't get why HOS needs a third special hat. they already have a beret as well as a unique hat. considering that HOS is one of the worst offenders for having a ton of bloated clothing options, this needs a better justification for being added.

as an aside, just because a PR doesn't affect balance doesn't mean you can omit your reasoning for making the pr.
image

**Comment by MACMAN2003** [comment]
i'll update the description to give it an actual reason to be added

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Remove the pet variant as it's bloat.

**Comment by MACMAN2003** [comment]
gonna have to re-do it from the ground up

**Pull request closed without merging**
