### PR TITLE
Minor buffs to captain's sabre (and fancy-ified the description)

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Minor improvements to the Captain's Sabre. Does slightly more damage, and now does piercing damage as well. Sabre can also be used to pry unpowered doors (at a slower speed than other tools, mind you.)

### Buffed Damage
_Improved from **17 Slash** to **16 Slash + 4 Pierce**_
> From experience, the sword feels pretty underwhelming. It might be great at stabbing a tider for slipping you as is, but is pretty inefficient at most actual CQC. As it was, it was also the second-lowest damage dealing sword in the game by quite a bit.

### Added Prying
_The Captain's Sabre can now pry unpowered doors._
> Idea I am returning to because I constantly find myself without power, and never had time to grab a crowbar because shit kept coming up (I actually do my job!) While it can partially function as a crowbar, it does so at a 0.8x speed.

## Media

https://github.com/space-wizards/space-station-14/assets/125095677/4ea45872-df08-4d78-a6bc-965c5d605272
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Captain's Sabre now functions as a budget crowbar.
- tweak: Captain's Sabre received a slight damage buff.

### CODE REVIEW

**Comment by Aexxie** [comment]
addenda: I know it is a "ceremonial" weapon BUT trying to kill something with the laser pistol usually ends up in other people getting hurt too (ricochet, people being in proximity.) It's great for hitting something with precision.

**Comment by UbaserB** [comment]
I appreciate this PR, the extra functionality is really cool and goofy imo.

**Comment by asperger-sind** [comment]
Looks like this has changes to the energy katana, this isn't anywhere else in the PR other than changed files.

Either way I'm against damage buffs to the sabre, 17 slash damage with 1.5 attack speed is already really strong and making it deal 24 damage with 1.5 attack speed is just ridiculous and makes captain even more of a lootbox.

**Comment by Aisu9** [comment]
why the energy katana lose 5 slash damage and gain 10 heat damage? why it's not stated in overview and changes?

**Comment by UbaserB** [comment]
for me the damage balancing doesn’t really matter but if people really don’t want the buff i still want the crowbar ability be added!

**Comment by Aexxie** [comment]
> why the energy katana lose 5 slash damage and gain 10 heat damage? why it's not stated in overview and changes?

I just noticed that, I was messing around trying to figure out why something wasn't working. One second.

Also, for reference, the sabre still does only a little over half as much damage as the esword lol

**Comment by Emisse** [comment]
Slash is already the best damage type, I don't think it needs a damage buff

**Comment by Aexxie** [comment]
can we keep the crowbar thing lol

**Comment by UbaserB** [comment]
i want to keep the crowbar thing

**Pull request closed without merging**
