### PR TITLE
Pills are now created from beaker, not buffer

### PR DESCRIPTION
**Pull request by osjarw**
## About the PR
Title

## Why / Balance
Now making pills is a lot less annoying, since you don't have to do it with a empty chemmaster anymore. 
I think that this will encourage chemists to make pills more often.
Also if I recall correctly, this is how it worked in SS13, but I might be wrong. 

## Technical details
On the chemmaster UI, now the generated label is created using the chems in the beaker instead of chems in the buffer.
On the server side, the solution is fetched from the chemmaster's input slot, and passed to withdrawfrombuffer which now accepts an optional Solution argument, which can be used as a new source of the chems. 
Also the input beaker is manually synced using UpdateChemicals, to make sure the client is aware of the new state of the beaker. 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/62134478/81d78632-9ba2-43e0-b962-3224f4855847

## Breaking changes

**Changelog**

:cl:
- tweak: Chemmaster now creates pills using the input beaker, instead of drawing from the buffer.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
The chemmaster should be the place to pack chems not a chem dispenser/holder 2.0, I think this is the wrong direction to go

**Comment by osjarw** [comment]
Just slap a limited buffer onto it and it is now just a packing station.

**Comment by osjarw** [comment]
Also I don't think this would turn it into a chem dispenser 2.0.
At the worst I think it would just make chemists store the chems at the chemmaster, and give a bunch of pills to med.
But I don't think that'll happen, med would probably just be way too angry to let them do that.

**Comment by gostt899** [comment]
Unless you have a bluespace beaker this just makes pill production way slower. I think a better way to do this would either be to make a way to designate what chems from the buffer you want in the pills.

**Comment by osjarw** [comment]
>  I think a better way to do this would be to make a way to designate what chems from the buffer you want in the pills.

I showcased a demo for a system that does this on Discord, if you wanna check it out.
Personally I don't think it should be done this way currently, since that will definitely encourage chemists to store literal tons of meds in the chemmaster. 
Though I think that could work, if the buffer was limited.

**Comment by osjarw** [comment]
> I showcased a demo for a system that does this on Discord, if you wanna check it out. Personally I don't think it should be done this way currently, since that will definitely encourage chemists to store literal tons of meds in the chemmaster. Though I think that could work, if the buffer was limited.

I guess I should it the demo over here, so people can somewhat easily discuss it.
I think that this makes pill creation too easy, and encourages people to just dump a whole lot of chems in the chemmaster.
I can already see someone dumping all oxygen, sugar and carbon into the device, and printing out pills containing those three ingredients. 

Also it should be mentioned that this video isn't about this PR, it is from another branch.

https://github.com/space-wizards/space-station-14/assets/62134478/6fd5d831-d073-4a66-88f4-bfc27bd7ebb1

**Comment by QuietlyWhisper** [comment]
> and encourages people to just dump a whole lot of chems in the chemmaster. I can already see someone dumping all oxygen, 

really cool demo, would be really nice with polish, but again, and like you said, this just makes chemmaster a better chem dispenser with no other changes

**Comment by IProduceWidgets** [comment]
I agree that it will be much slower to make pills from the beaker. The standard beaker is only 100u while a full pill canister takes 180u.

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
can we get this reopened?

**Comment by osjarw** [comment]
I'm not entirely sure if I'll continue working on this.
I've gotten kinda demoralized by the opinions implying that we shouldn't incrementally improve existing systems, and we shouldn't lay groundwork for future features with PRs that by themselves look like awful ideas, instead we should completely rework the existing systems and all affected features and problems in one go.
I'm not talented enough designer nor coder to completely redesign the chemmaster, so I just wanted to do what little I could to improve the current state of pill creation.

**Comment by engineer-pearl** [comment]
This doesn't even seem like a bad idea on its own?

Also in my opinion, trying to take things in one go is... Not usually the right move. Especially given that other things are changing in parallel. 

Getting pills out of chem master is the first step to getting the chem master situation fixed. I would say adding a bunch more empty jugs would be the next step, so there actually is somewhere else to store chems

**Comment by osjarw** [comment]
> This doesn't even seem like a bad idea on its own?

adding limited storage to chemmasters was, and it would've worked really well with this one

**Comment by PJB3005** [comment]
I don't like this PR because it's working around SS14 symptoms that are better addressed in a different way, IMO: https://github.com/space-wizards/space-station-14/pull/27317#issuecomment-2079660444

**Comment by engineer-pearl** [comment]
Ah, I see.

Yeah there's a bit more work needed before tossing the infinite storage - it's currently the bandaid to chemists having nowhere else to store stuff. I don't like using the chem master as infinite storage, but that means I'm always out of jugs!

**Comment by engineer-pearl** [comment]
My advice? If you don't feel confident in your ability to design or work ahead - use smaller chunks, not larger ones. 

If a storage limit would work well with the PR, great. It can be added next PR. 

Incremental improvements are good, and smaller PRs tend to be easier to add anyway.

**Pull request closed without merging**
