### PR TITLE
9 new cargo bounties

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Added 10 new cargo bounty:
- 1 any anomaly core for 10000
- 3 any borg module for 3500
- 7 artifact fragment for 32500
- 8 any organs for 3500
- 5 hand labelers for 6660
- 8 warm clothes for 6000
- 15 batteries for 24500
- 6 any laser hitscan gun for 28500
- 30 any meat food for 9500

## Why / Balance
more content

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added 9 new cargo bounties!

### CODE REVIEW

**Comment by Ilya246** [comment]
i think noslip shoes should be worth more and batteries worth less

**Comment by TheShuEd** [comment]
come up with a specific cost

**Comment by Ilya246** [comment]
just RTSC'd, noslip shoes accept: advanced magboots (only one), snakeskin boots, galoshes (limited), space ninja shoes, noslips, borgs, spiders, reagent slimes, any flying mob, shiva, rat king and rat servants, revenants (if you can sell one), the various bots, xenos

**Comment by Ilya246** [comment]
also you forgot to state the warm cloth bounty in the PR description

**Comment by EmoGarbage404** [comment]
The anomaly core bounty is a literal scam and the artifact fragment one is going to lose money compared to just minor research + selling. Id reduce the core bounty to 1 and make it significant compared to a core's default price (10k). Fragment bounty needs better returns.

Noslip bounty is kinda weird just because player's may not know what is and isnt a noslip

**Comment by TheShuEd** [comment]
ok, remove noslip
1 anomaly core for 10000
7 fragment for 32500

**Comment by Ilya246** [comment]
perhaps increase warm cloth 4500->6000 so people actually bother doing it over other bounties
warm cloth would need you to: order cloth -> go to hop and hope he is at his workplaec -> ask him to print 8 winter coats

**Comment by Ilya246** [comment]
it appears that warm cloth also accepts: hardsuits, hardsuit helmets, firesuits and fire helmets, emergency suits, winter boots

**Pull request merged**
