### PR TITLE
O2 Medkits Get Emergency Nitrogen Tank

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Added the emergency nitrogen tank to the O2 deprivation medkit.

## Why / Balance

Slimes can't breathe oxygen and it just seems fair.

## Technical details

yml change

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added an emergency nitrogen tank to the oxygen deprivation first aid kit.

### CODE REVIEW

**Comment by Errant-4** [comment]
Might want to change the name from OXYGEN deprivation kit, then

**Comment by Plykiya** [comment]
> Might want to change the name from OXYGEN deprivation kit, then

I considered air deprivation kit... but I'd also have to change the sprite...
Do we have an icon for general air...?

**Comment by Ghagliiarghii** [comment]
If we're doing species specific starting kits (n2 kit for slimes specifically as they're currently the only nitrogen breathers) I would also support adding a kit for moths with food that's not inedible to moths. I don't remember if there's a good 1x1 textile for moths in the game? If not one could be added without too much effort.

I like this idea.

**Comment by Errant-4** [comment]
> If we're doing species specific starting kits (n2 kit for slimes specifically as they're currently the only nitrogen breathers) I would also support adding a kit for moths with food that's not inedible to moths. I don't remember if there's a good 1x1 textile for moths in the game? If not one could be added without too much effort.
> 
> I like this idea.

This is not about the starter Survival Boxes, thats a very different and more difficult change due to how spawning works

**Pull request closed without merging**
