### PR TITLE
Revert "Plating & Tech Maint resprites (#15817)"

### PR DESCRIPTION
**Pull request by metalgearsloth**
This reverts commit 06482a9b2ae405457bb8d1951886846bc7a33c31.

### CODE REVIEW

**Comment by deltanedas** [comment]
pro why they were nice

**Comment by metalgearsloth** [comment]
Couple of the other maints didn't like it.

**Comment by Emisse** [comment]
image
you are wrong
my reasoning

**Comment by deltanedas** [comment]
yeah i thought plating looked sus but you dont mention techmaint floor which is really nice

**Comment by Emisse** [comment]
i have no opinion on the tech maint sprites they looked exactly the same

**Comment by deltanedas** [comment]
theyre a bit different but not as different as plating

**Comment by Emisse** [comment]
image

**Comment by deltanedas** [comment]
i am creed

**Pull request merged**
