### PR TITLE
uplink locking/unlocking, minor pda refactor

### LINKED ISSUE #15920: Nukies cannot place withdrawn telecrystals into their PDAs
## Description

Probably the uplink pda change pr
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- makes all the pda stuff pass in uid instead of using .Owner
- ringtone is not saved if you enter uplink code to prevent trolling (#15811)
- instead of just opening uplink, entering code now locks and unlocks it. you use the old uplink button to open it, buy your soap, then enter code again to lock. it will also close the store ui so you can run around with it at the bottom of your screen ready to buy anything at a moments notice.
- apc copypaste flavour text (for syndies), to warn noobs to lock after using
- fixes #15920

**Media**

https://user-images.githubusercontent.com/39013340/234830714-ed9de221-d828-4d39-a2e9-8003f0f76dcd.mp4

look ma i didnt leak my uplink code (cbf to tell client to reset the code so you need to reopen the ringtone ui)

flavour text, noob warning

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl:
- tweak: Entering your ringtone uplink code now locks and unlocks your uplink rather then directly opening it.
- tweak: When you set ringtone, if it is your uplink code it will not be saved.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
Closing the uplink window should lock the uplink, having to re-enter the code isn’t that intuitive

**Comment by deltanedas** [comment]
then why have it be a lock at all if it functions the same as no lock

**Comment by deltanedas** [comment]
spoiler for the flavour

**Comment by deltanedas** [comment]
spoiler for flavour above

**Comment by deltanedas** [comment]
also no merge until i figure out how to only show the footer on traitor uplinks and not rev/nukie stores

**Comment by deltanedas** [comment]
god damn this is cursed, the store code for sending init state only does anything for revs (i assume, everything else has no store ui)

**Comment by deltanedas** [comment]
footer is now hidden if you cant lock it (nukie, rev)

**Comment by deltanedas** [comment]
https://user-images.githubusercontent.com/39013340/235360824-7dccce1a-3479-4be9-8328-9b673380ae7b.mp4

@metalgearsloth ready to merg

**Comment by DawBla** [comment]
@deltanedas you might want to make the locking unlocking work like
unlock on right code, lock on any other
People are really confused right now and leave their uplinks open since the menu looks like the old ones where only syndies could see the uplink button and having to enter the secret ringtone again to lock it back is very confusing

**Comment by deltanedas** [comment]
could also just add a button to lock uplink below it, more explicit

**Pull request merged**
