### PR TITLE
Adds the NetProbe cartridge

### PR DESCRIPTION
**Pull request by juliangiebel**
## About the PR 
This PR adds the NetProbe cartridge. This program allows you to click on an entity that has a `DeviceNetwork` component and it displays some info about that network device. Namely: Name, Address, Frequency and Network (which is the `deviceNetId`s enum name if it exists and the id number if it doesn't).

The program saves up to nine entries and deletes the oldest one when scanning another device while full.

The cartridge can be found as rare loot in maintenance.

### Note:
Currently being able to see the address and frequency of devices isn't very useful but I will add ways to use that information in the near future.

**Screenshots**

image
grafik
**Changelog**

:cl:
- add: added a new PDA cartridge: The NetProbe cartridge.

### CODE REVIEW

**Comment by juliangiebel** [comment]
Converted to draft because I want to add scrolling and make the maximum amount of saved entries configurable in yaml

**Comment by Halalrc** [comment]
Привет. Подскажи эта система картриджей будет как ветка развития в РНД? И будет ли возможность модернизировать КПК под каждый отдел? Какие ещё планируются картриджи?

**Comment by Just-a-Unity-Dev** [comment]
> Привет. Подскажи эта система картриджей будет как ветка развития в РНД? И будет ли возможность модернизировать КПК под каждый отдел? Какие ещё планируются картриджи?

English only, please

**Comment by metalgearsloth** [comment]
This PR isn't the place to be asking about ideas for PDAs, that's for discord.

**Comment by juliangiebel** [comment]
There is currently no plan to make cartridges an RND branch.
If you want to know some ideas I have for cartridges, I listed them in here: https://hackmd.io/mxO_hTmHTjm-OnvGLnwdJA#Cartridges
You're also welcome to implement your own ideas.

**Comment by juliangiebel** [comment]
I added the maximum number of entries as a data field to the component and added a scrollbar that shows if there are more entries than the UI can fit.
This is ready for review now.

**Comment by 0x6273** [comment]
It should be possible to localize the network names via fluent.

**Pull request merged**
