### PR TITLE
Atmos needs a new backpacks

### PR DESCRIPTION
**Pull request by KingFroozy**
[AtmosBackpack.zip](https://github.com/space-wizards/space-station-14/files/12178379/AtmosBackpack.zip)
[AtmosDuffelbag.zip](https://github.com/space-wizards/space-station-14/files/12178380/AtmosDuffelbag.zip)
[AtmosSatchel.zip](https://github.com/space-wizards/space-station-14/files/12178381/AtmosSatchel.zip)

## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by lzk228** [comment]
bro...

**Comment by AjexRose** [comment]
Guide be upon thee 

https://docs.spacestation14.io/getting-started/git

**Comment by KingFroozy** [comment]
Dude, I don't know, how this thing works! I can't uderstand it!

**Comment by AJCM-git** [comment]
We have a guide for git https://docs.spacestation14.io/getting-started/git. If you still have problems see if you can partner with someone that knows how to use it either in discord or another medium.

**Comment by AjexRose** [comment]
the discord has had a dedicated section to helping code in #howdoicode, they can help you out

**Comment by potato1234x** [comment]
bruh the zip files arent even zip files theyre just renamed pngs 💀

**Pull request closed without merging**
