### PR TITLE
Revert rat servant health back to normal

### PR DESCRIPTION
**Pull request by Ilushkins33**
## About the PR

Reverts https://github.com/space-wizards/space-station-14/pull/15148 changes

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ilushkins33
- tweak: Rat servants health is now back to normal

### CODE REVIEW

**Comment by metalgearsloth** [comment]
If you're making balance changes please explain why.

**Comment by deltanedas** [comment]
hes a rat main :heart:

**Comment by Ilushkins33** [comment]
> If you're making balance changes please explain why.

Becasue you can literally kil a rat servant with you bare hands

**Comment by moonheart08** [comment]
> > If you're making balance changes please explain why.
> 
> Becasue you can literally kill a rat servant with you bare hands

it's a rat, and more importantly it's a spammable rat.
can you justify this any way else

**Comment by Ilushkins33** [comment]
> it's a rat, and more importantly it's a spammable rat.
can you justify this any way else

Rats already robusted by mousetraps, and that PR made it that you can crit a rat with a simple crowbar swing 

So it's sounds more like skill issue to me

**Comment by Stealthbomber16** [comment]
rat being as fast as it is and dealing as much damage as it does and being able to fit under doors and being available in such high quantities should not be able to take multiple hits from melee weapons.

plus you've got the new bleed system which has functionally appeared to be a massive rat buff. rat health reduction is completely fair imo 40 health rats was just stupid

**Comment by Ilushkins33** [comment]
> plus you've got the new bleed system which has functionally appeared to be a massive rat buff. rat health reduction is completely fair imo 40 health rats was just stupid

So i made it 30 health (~1 baseball bat swing), because 15 health is kind of absurd too

**Comment by keronshb** [comment]
I feel the previous PR should have had a balance discussion to go with it as well before it got merged. It was starting to have a discussion but then it was instantly merged which isn't great.

What I would do is see how long it takes to spawn the rats, how strong they are (health, damage, numbers) and then adjust from there.

I only know Rat King From SS13 so I don't know the difference here just yet so excuse me for speaking out of ignorance but what I would personally do is:

Cap the spawned rats at 4-6
Have a long delay on the timer
Have a check to see how many rats are spawned from this king and have diminishing returns

Alternatively:
Same as above but also give the rat king a points shop to adjust his rats.

**Comment by brainfood1183** [comment]
The issue is rats are small and fast which makes them hard to hit. Reducing their health i think fixes the issue but also nerfs the rat king considerably as an antag. If the nerf is to harsh then perhaps rats being able to "evolve" into larger rats by eating lots of food that are tougher but much slower and larger so easier to hit.

**Comment by MagnusCrowe** [comment]
They are already so fast and so small.  They be rats, sneaky, annoying little jerks who should fight in swarms or using guerilla tactics.

**Pull request closed without merging**
