### PR TITLE
Fix lizards losing snouts when equipping a head bandana

### LINKED ISSUE #29914: bandana on head hides reptilian's snout
it looks horrible
image

### PR DESCRIPTION
**Pull request by luizwritescode**
## About the PR

The infamous no-snout lizard issue. Fixes #29914 go read how we found the root issue there.

The game's clothing code is scattered among a few systems so there was a slight logic oversight for how bandanas work

#24597 adds foldable bandanas to the game

#25716 tried to fix mask bandanas but introduced this to head bandanas

## Why / Balance

Have you seen a no snout lizard? The thing was cursed. If you don't believe me go look in the attached issue.

## Technical details

For some weird reason head bandanas inherit mask bandanas so they end up getting a `HideLayerClothingComponent` set to snout when that was not intended. Someone could probably switch the inheritance of both but even that won't solve the item updating its component upon being folded/unfolded

My solution was to add two fields in `FoldableClothingComponent` specifying what `HideLayerClothingComponent` will update to upon calling `OnFolded` from `FoldableClothingSystem`

## Media

https://github.com/user-attachments/assets/350b692c-17c0-4b6a-bc75-89518f07f34e

## Breaking changes

Thankfully nothing was renamed or removed

**Changelog**

🆑 coffeeware
 - Fix: Lizards will no longer lose their snouts when equipping head bandanas

### CODE REVIEW

**Comment by Golinth** [comment]
does this also fix the chaplain's plague doctor hat hiding snouts as well?

**Comment by luizwritescode** [comment]
> does this also fix the chaplain's plague doctor hat hiding snouts as well?

it does now

**Comment by Moomoobeef** [comment]
image
image
image
Somehow you broke the changelog, with this PR showing up in each changelog since it was merged.

**Comment by Golinth** [comment]
It’s a big deal, it needs to be repeated! 

Though I wonder if it has to do with adding \* before Fix:, making it a bullet point

**Pull request merged**
