### PR TITLE
small senior physician drip update

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

gave the senior physician the medical beret and nitrile gloves on round start.
it would be a shame to see the brigmedic gear go unused, no?
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cee ell, bro

### CODE REVIEW

**Comment by JustCone14** [comment]
Beret good.

**Comment by Nairodian** [comment]
I'm personally not a fan of the beret. It's silver, not white thus it looks out of place among the rest of their gear. (at least to me)

**Comment by JoeHammad1844** [comment]
that's a good point

**Comment by LankLTE** [comment]
I believe Nairod has plans to make berets for Senior roles- though regardless I agree this one looks out of place since its' a different color from the rest of their gear.

**Comment by UbaserB** [comment]
isnt there a medical beret that is the same color?

**Pull request closed without merging**
