### PR TITLE
New Chemistry Item: Large Pill Canister

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## New Chemistry Item: Large Pill Canister

Hello chemists! Tired of packing pills in batches of 9? Well now you can pack them in batches of 30!

This will:
- allow chemistry to save clicks, thus reducing the workload and stress of chemistry work
- allow chemistry to move multiple pills at once
- allow chemistry to store large batches of pills somewhere other than the counter, if they wish
- let chemistry hand out their standard pill canisters to doctors!
- allow chemistry to make smaller dose pills without the headache of packing 9 pills at a time on a large batch
- saves chemistry time to make more niche chemicals for other departments, like salt for the chef and chemicals for botany!

FAQ: 
Q. Won't this be metagamed for people to hold a shit ton of pills?
A. No, it's unwieldy as a survival box, and just like a survival box, removing a single pill already makes the canister useless to them. It's exactly the same as holding 30 pills in your bag, but will always take up 30 space if you use pills!

Q. This will allow chem to produce a ridiculous amount of high dose pills?
A. Not at all actually! this only affects chemistry's ability to *pack* pills! If chemistry already has a large batch of medicine, they were going to pack it 9 at a time regardless! It does not change the fact that chem will still have to mix all the chemicals needed to even start packing!

Q. What's the intended purpose then?
A. Chemistry can make many low dose pills at once! rather than slowly packing 10-15u pills, you could do it all at once!

In closing; this item will should not cause balance issues. If it did, that would be a result of the chem dispenser being too strong, which is entirely it's own issue. I hope this will make chem players happy, and more interested in playing the role without the tediousness.

**Media**

Screenshot 2023-02-10 103040

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- add: Added the large pill canister, an unwieldy 30 storage canister.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
This will be left as a draft until licensing is resolved.

**Comment by QuietlyWhisper** [comment]
And as always, I'm more than open to feedback either on discord or here. I hope this item will bring a nice QOL for chem.

**Comment by Cheackraze** [comment]
Why do pills need another buff? They are already too strong compared to liquid chems and this just exacerbates the issue further.  And doesn't this just directly obsolete the smaller pill bottles? Why even have small pill bottles when you have these?  If anything pills should get mega nerfed to like maximum 5u if we are going to let chemists make 30 of them with a push if a button. 

I absolutely live doctor RP and I haven't played doctor in months, because its just pills all the time, and it's absolute garbage for doctors.  This just makes the problem 3x worse

**Comment by GoodWheatley** [comment]
I'm going to be honest, considering how I already see hundreds of pills littering the chemistry desk every round, I think you need to drastically nerf pills before this can be implemented without making chemistry gameplay even worse. Making pill production require plastic (microplastics...) and nerfing pill chem capacity to ~20u is a good place to start.

**Comment by Cheackraze** [comment]
I think overall this is a bad change unless pills get nerfed to at least 10u _first_

**Comment by arealbeba** [comment]
what if pill's capacity increased with upgraded chemmaster?

**Comment by arealbeba** [comment]
that would give motivation to science department for upgrading chemistry

**Comment by QuietlyWhisper** [comment]
> what if pill's capacity increased with upgraded chemmaster?

Thats actually not too bad of an idea, but me and the other coders/maintainers were trying to find a way to break pill meta in it's current state...

Came to the conclusion that pills should be limited to 10u and require plastic in some way to produce, while bottles will remain unchanged. This will ideally push medical to use pills for minor injuries and bottles for major, as bottled chems tend to do a better job at healing people with massive injuries

**Comment by moonheart08** [comment]
I really don't like this sprite.

**Comment by QuietlyWhisper** [comment]
After some good talks in the discord, I don't think this should be added. I've had a change of heart and realize this would increase entity spam, as the only thing stopping entity spam with pills right now, are pill canisters. I'll be more focused on working with moony to reach https://github.com/space-wizards/space-station-14/milestone/3 instead, which should help medical gameplay overall.  If things like this are needed then, I'll reopen this.

**Comment by VektorZ1** [comment]
with the new update of Pills 1984 I think this PR would be appropriate

**Comment by QuietlyWhisper** [comment]
> with the new update of Pills 1984 I think this PR would be appropriate

I've been considering it, but also removing the canister's ability to produce pills, leaving it as a storage container. Unsure. Freeman mentioned it being rather redundant, and I also feel the fridge in chemical would be better suited for that...

**Pull request closed without merging**
