### PR TITLE
Cargo/Brown repalette

### LINKED ISSUE #18627: cargo backpack inhand-right sprite issue
left and right facing sprites should be swapped

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Repalettes cargo and the brown outfit set so they're more consistent (also resolves #18627 )

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- tweak: Changed cargo and brown outfit colors to be more consistent

### CODE REVIEW

**Comment by Jackal298** [comment]
And where is the change of the miner's cloak?

**Comment by lzk228** [comment]
icons on id card should be same color as jobicon

**Review by lzk228 — CHANGES_REQUESTED** [review]
change pdabordercolor in prototypes

**Comment by Alekshhh** [comment]
ngl couldn't find the job icons, also where's the pda borders

**Comment by lzk228** [comment]
i mean that you should leave the icons as they are
all icons should have one similar color

**Comment by lzk228** [comment]
fix #18627 here please

**Comment by Alekshhh** [comment]
gotcha

**Comment by JoeHammad1844** [comment]
I really dont like what you did with the hardsuits, them, the ore bag and bedsheets look like completely different art styles, aswell

**Comment by deltanedas** [comment]
spationaut suit helmet looks like its made of wood

**Comment by Alekshhh** [comment]
changed already

**Comment by JoeHammad1844** [comment]
still looks like its from a different art style, the hardsuits, ore bag and bedsheets  just don't need to change

**Comment by Alekshhh** [comment]
the hardsuit is a repalette save for the spatio helmet, the ore bag is actually readable now and the bedsheet didn't even look like the item sprite

**Comment by Flareguy** [comment]
I went into more detail on discord and there are still things I want changed, but for the most important & concise things:

- Do not repalette the generic brown items (or move it out to its own PR if you dislike the shade of brown that already exists, for whatever reason.) There is zero reason for this to be "consistent" with cargo, and the brown you repaletted it to is in my opinion kind of muddy and saturated.
- Alter the salvage hardsuit repalette to actually fit the hardsuit's sprite, or change it back to the old sprite. The only thing the changed colors really do is muck up the pre-existing contrast by a small margin, and the colors were arguably already consistent as-is. I don't really see a need for it to change and would probably just not mess with it if the goal is consistency.

**Comment by Alekshhh** [comment]
do you realize that each brown item is a different color
cargo uses these items, so them being consistent with cargo's brown is good
the color is fine as well, it has always been there. I don't know why me suddenly working on it makes this a major issue when it wasn't even a problem for years
and the hardsuit colors makes the contrast a bit clearer if anything

**Comment by Flareguy** [comment]
> do you realize that each brown item is a different color
> cargo uses these items, so them being consistent with cargo's brown is good

I apologize if I wasn't clear here or just flat out wrong (I honestly don't remember which.)
What I was trying to say is that you should not repalette the brown items in this PR. They are not cargo items so they don't belong here, the changes are already pretty big and change a lot so it'd make this PR pretty hard to review as well.
If you want to make scarves that match cargo more then make cargo scarves, don't mess with the brown stuff.

> the color is fine as well, it has always been there.

No other item in the brown item set uses any color even remotely like this to my knowledge, so this doesn't make much sense to me. Just because the color was used in cargo doesn't mean it's automatically a good fit for the set, especially considering these, again, are generic items belonging to their own set (I'm pretty sure the brown shoes are used in literally *every department* in one way or another.)

> and the hardsuit colors makes the contrast a bit clearer if anything

(Not ingame screenshots but this should do a good enough job of showcasing it)
image

I don't really care about the purple here much, though the removal of the additional color is probably not good. My main gripe is the brown, which... basically uses the same color but brighter. So it's got an inherintly less defined outline, which is worse for contrast.

**Comment by JoeHammad1844** [comment]
> I went into more detail on discord and there are still things I want changed, but for the most important & concise things:
> 
> * Do not repalette the generic brown items (or move it out to its own PR if you dislike the shade of brown that already exists, for whatever reason.) There is zero reason for this to be "consistent" with cargo, and the brown you repaletted it to is in my opinion kind of muddy and saturated.
> * Alter the salvage hardsuit repalette to actually fit the hardsuit's sprite, or change it back to the old sprite. The only thing the changed colors really do is muck up the pre-existing contrast by a small margin, and the colors were arguably already consistent as-is. I don't really see a need for it to change and would probably just not mess with it if the goal is consistency.

I concur

**Comment by Emisse** [comment]
i think the more sane way to go about this is piece mealing each item change in a separate pr, since some of the stuff looks great and would get merged instantly

**Pull request closed without merging**
