### PR TITLE
Straw hat.

### PR DESCRIPTION
**Pull request by Adrian16199**
A craftable, flammable straw hat.

Thats it.

to-do:
- [X] Why it no flame = nvm, that was done.
😔 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame show case

https://github.com/space-wizards/space-station-14/assets/144424013/55d810b1-6652-41ad-bce8-0c35a6e19863

https://github.com/space-wizards/space-station-14/assets/144424013/a23e20b1-7dae-4b8c-ac79-05170fc94f45

## Breaking changes

**Changelog**

:cl:
- add: Added a straw hat that can be crafted with wheat.

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
This needs to be added to the pirate ships

**Comment by Adrian16199** [comment]
To be fully honest, I have no idea what that is but if you tell me where to put it, sure.

**Comment by Geekyhobo** [comment]
Does this really need a CL

**Comment by Adrian16199** [comment]
I mean, idk, I prefer to know what was added compared to lookin at 300 github changes with comments. Everyday.

**Pull request merged**
