### PR TITLE
Adding prosthetics to the game. (Using tattoo system)

### PR DESCRIPTION
**Pull request by Iced-Coded**
## About the PR

I've added some prosthetics by using a tattoo system, which, is already in the game.

## Why / Balance

It's a pure cosmetical thing, which, doesn't even change balance in any thing.

## Technical details

It doesn't change the code, just adds a new code above.

## Media

This PR does a pretty small thing, so it doesn't require a screenshot.

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alex
- add: Added purely cosmetic prosthetics

### CODE REVIEW

**Comment by deltanedas** [comment]
its spelled prosthetic not prostetic :trollface:

**Comment by Iced-Coded** [comment]
Alright, thanks for correcting.

**Comment by deltanedas** [comment]
the rsi is also named that...

**Comment by CaptainSqrBeard** [comment]
how it looks in-game?

**Pull request closed without merging**
