### PR TITLE
Adds vending restocks for ChefVend and Condiment Stations

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
As title says plus adjusts Chefvend->ChefVend for consistency.

## Why / Balance
They were missing

## Technical details
n/a
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase
207685787-75f78a6f-e03f-46eb-b58a-0db5ec98acb5

## Breaking changes
n/a

**Changelog**
:cl: Velcroboy
- add: Nanotrasen suppliers now carry restocks for ChefVends and popular condiments. Get them at your nearest cargo depot.

### CODE REVIEW

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
Good pr. Only thing it needs are locale strings for the crates (look at how other crates do it)

**Comment by dvir001** [comment]
This is still missing the .FTL

**Comment by IamVelcroboy** [comment]
Wow, I 100% forgot about this PR. I can add the localization file tomorrow.

**Comment by IamVelcroboy** [comment]
Yeah, I'm not seeing localization on these which is why, I'm guessing, Emo reverted their request. If something is still needed, point me in the right direction and I'll add it. Otherwise, I'm moving on.

**Pull request merged**
