### PR TITLE
Upstream Discount Dan's resprite

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR

Upstreams resprite of Discount Dan's vending machine.  Removes soul.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

No changelog.

### CODE REVIEW

**Comment by Emisse** [comment]
looks good

**Comment by potato1234x** [comment]
wasnt the entire point of the discount dans sprite for it to be a "discount" sprite

**Comment by EmoGarbage404** [comment]
> wasnt the entire point of the discount dans sprite for it to be a "discount" sprite

no

**Comment by SonicHDC** [comment]
image
Yey, no one looked to this

**Comment by Hyenh** [comment]
> image
> 
> Yey, no one looked to this

image

**Comment by potato1234x** [comment]
> image
> Yey, no one looked to this

Whats wrong with it?

**Pull request merged**
