### PR TITLE
Add material doors and recipes to make them

### PR DESCRIPTION
**Pull request by Fishfish458**
## About the PR 
This PR adds material doors for a various amount of current materials (and some yet to be obtainable)
specifically:
* Wooden door
* Metal door
* Plasma door
* Diamond door
* Uranium door
* Gold door
* Silver door
* Sandstone door
* Paper door (paper doesn't currently stack and as such has no recipe right now)

all recipes require 20 of the material and take 15 seconds to build and deconstruct.
Most of these materials do have counterparts as walls that are currently unbuildable but exist in the tile spawner

**Screenshots**

materials
doors built
doors
paperdoor
deconstruct

:cl:
- add: Added craftable doors for most materials you can and can't get your hands on

### CODE REVIEW

**Review by Peptide90 — APPROVED** [review]
lgtm - partially completes #5231 (only one missing maybe is Ice but you'd need a new material for that I think. OR14 probably already has it).

For wall construction you could possibly base them all off the girder still as a frame and just have the main material requirement change except for the wood, paper and ice which can just be material? If you do follow up with that PR remember to do fixes # issue number for it to auto close the issue.

**Comment by Fishfish458** [comment]
> 

I'm not sure where the Ice one comes from but I can add it if it has a door, though there's also no stackable Ice resource like the rest of them have.

I figured out the issue with the paper sheet I was referencing so added that as a recipe as well.

**Comment by moonheart08** [comment]
> lgtm - partially completes #5231 (only one missing maybe is Ice but you'd need a new material for that I think. OR14 probably already has it).
> 
> For wall construction you could possibly base them all off the girder still as a frame and just have the main material requirement change except for the wood, paper and ice which can just be material? If you do follow up with that PR remember to do fixes # issue number for it to auto close the issue.

Or14 does not currently have an ice resource sprite or prototype.

**Comment by Peptide90** [comment]
> > lgtm - partially completes #5231 (only one missing maybe is Ice but you'd need a new material for that I think. OR14 probably already has it).
> 
> > 
> 
> > For wall construction you could possibly base them all off the girder still as a frame and just have the main material requirement change except for the wood, paper and ice which can just be material? If you do follow up with that PR remember to do fixes # issue number for it to auto close the issue.
> 
> 
> 
> Or14 does not currently have an ice resource sprite or prototype.

Fair thought you might with the whole ice to water thing but never checked. Even so would be an easy one to add down the line and have it blend to water or get expensive and use atmos heat to change state to puddles. Scope creep though not needed in this PR.

**Comment by Delete69** [comment]
Are these supposed to be unaffected by power and only open with a crowbar?

**Pull request merged**
