### PR TITLE
Manifest & Player list in status.

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
The server is now capable of reporting the current crew manifests and player list so bots can print them out. Does not include actually adding support to any bots. (yet)

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by AJCM-git** [comment]
@PJB3005

**Comment by PJB3005** [comment]
Having a real déjà vu moment because I swear I already commented on something like this.

This shouldn't be in `/status`, it should be some other endpoint or `/info` at least. We don't want to bloat the contents of the status message too much IMO.

**Comment by moonheart08** [comment]
> Having a real déjà vu moment because I swear I already commented on something like this.
> 
> This shouldn't be in `/status`, it should be some other endpoint or `/info` at least. We don't want to bloat the contents of the status message too much IMO.

I am too as I could swear I had already changed it to use /ss14/manifest. Whoops!
I'll check my local branches later.

**Comment by AJCM-git** [comment]
@moonheart08 status on this?

**Comment by moonheart08** [comment]
> @moonheart08 status on this?

currently not working on any PRs, but the requested change should be pretty easy for anyone to make.

**Comment by AJCM-git** [comment]
gotcha, reopen once you are free then (tagged this as derelict in case anyone wants to step in)

**Pull request closed without merging**
