### PR TITLE
Rename Dungeon Master Laws to not run into copyright problems

### PR DESCRIPTION
**Pull request by Litraxx**
## About the PR
Changed the Dungeon Master lawset and related prototypes to a more generic name, because of copyright concerns.

## Why / Balance

Resolves https://github.com/space-wizards/space-station-14/issues/33671

## Technical details

Basic renaming nothing fancy

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

- Renamed `DungeonMasterCircuitBoard` to `GameMasterCircuitBoard`
- Renamed `DungeonMasterLawset` to `GameMasterLawset`
- Renamed laws in `DungeonMasterLawset` from `Dungeon<Number>` to `Game<Number>`
- Renamed law string resources from `law-dungeon-<Number>` to `law-game-<Number>`

**Changelog**

:cl:
- fix: Renamed the Dungeon Master lawset to Game Master lawset

### CODE REVIEW

**Review by slarticodefast — CHANGES_REQUESTED** [review]
Don't directly edit the map files, please revert all changes to the maps, including the whitespace.
Instead add the renamed entities to migrations.yml so that is done automatically.

**Comment by slarticodefast** [comment]
Could you also undo the whitespace changes in oasis.yml? I would like to avoid merge conflicts for mappers working on that map.

**Comment by Litraxx** [comment]
> Could you also undo the whitespace changes in oasis.yml? I would like to avoid merge conflicts for mappers working on that map.

Should be done now, had to fight Rider a bit to get it reverted

**Comment by ScarKy0** [comment]
Could the CL be "The "Game Master" lawset is now legally distinct"? :godo:

**Review by slarticodefast — APPROVED** [review]
Looks good to me. Thanks for the cleanup and your first contribution!
Can you add a changelog for this since it has an in-game impact?
For example: "Renamed the Dungeon Master lawset to Game Master lawset."

**Comment by chromiumboy** [comment]
As far as I'm aware, there's no need to rename the board prototypes. It's only the text thats visible to the public (i.e the label and description) that's a potential issue. I'd like to avoid migrations and breaking changes if possible

**Comment by Litraxx** [comment]
> As far as I'm aware, there's no need to rename the board prototypes. It's only the text thats visible to the public (i.e the label and description) that's a potential issue. I'd like to avoid migrations and breaking changes if possible

While that is true, I think it would be better to rename all associated prototypes, to avoid any confusion for future contributors.

> Also there's no need for a CL, the change is so minor

I agree with this, but I'm just following what the maintainer asked

**Pull request merged**
