### PR TITLE
Add Missing Unlocks to Emagged Lathes and Move Recipes to Protolathe

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

All the autolathe dynamic recipes were moved to the protolathe.

Emagged Protolathe gets
- Truncheon
- TelescopicShield
- HoloprojectorSecurity
- ~~WeaponDisabler~~
- ~~WeaponDisablerSMG~~
- PortableRecharger

Emagged Circuit Imprinter gets
- ShuttleGunSvalinnMachineGunCircuitboard
- ShuttleGunPerforatorCircuitboard
- ShuttleGunFriendshipCircuitboard
- ShuttleGunDusterCircuitboard

## Why / Balance

These are all the security recipes that were missing from the emagged recipe lists. There doesn't seem to be any particular reason these recipes shouldn't be accessible via emagging when everything else is.

The original PR for ship guns gave the autolathe emag access to the power cages, but they forgot to add in a way to get emag access to the ship guns themselves so I moved it to the circuit imprinter.

I moved all the autolathe dynamic unlocks over to the protolathe since autolathes are meant for non-research crafting and the protolathe is meant for research gated crafting.

## Technical details

yml stuff

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

image

## Breaking changes

**Changelog**

:cl:
- add: The emagged protolathe can now print truncheons and the new T3 portable recharger.
- add: The emagged circuit printer can now print ship guns.
- tweak: Autolathe emagged recipes that are research gated have been moved over to the protolathe.

### CODE REVIEW

**Comment by Plykiya** [comment]
I've never really interacted with protolathes before so I have no idea how "in flavor" it is to have the truncheon and telescopic shield in its recipe list.

If it can print laser guns, it might as well as be able to print disablers as well.

**Review by CringeCursed — APPROVED** [review]

**Comment by thebadman4662** [comment]
Even syndies can print disabler pistols now while sec still can't. 😭

**Comment by Plykiya** [comment]
> Even syndies can print disabler pistols now while sec still can't. 😭

Sec can do it. I was the one to patch it in.

**Comment by Plykiya** [comment]
I have been informed on what the actual intended purpose of autolathes/protolathes are
namely that autolathes are for things that are unlocked immediately (no dynamic recipes) and the protolathe is for stuff that is unlocked through research (mainly dynamic recipes)

so I'll do a follow up PR moving all the autolathe dynamic emag recipes over to the protolathe

**Review by EmoGarbage404 — DISMISSED** [review]
> There doesn't seem to be any particular reason these recipes shouldn't be accessible

I have some pretty major balance concerns about giving syndicate members trivial methods of obtaining stun equipment. Truncheons, disablers, and disabler SMGs were formerly completely limited to sec. This made acquiring one require engaging with sec directly.

With these changes, emags become even more powerful as a way of obtaining stun equipment to use against sec and crew.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> > There doesn't seem to be any particular reason these recipes shouldn't be accessible
> 
> I have some pretty major balance concerns about giving syndicate members trivial methods of obtaining stun equipment. Truncheons, disablers, and disabler SMGs were formerly completely limited to sec. This made acquiring one require engaging with sec directly.
> 
> With these changes, emags become even more powerful as a way of obtaining stun equipment to use against sec and crew.

if i could give my 2 cents on this, while i do agree about disablers the truncheon in practice is mainly used to crit wounded suspects that have been harmed from bullets or lasers due to the high damage of each hit. I personally, have never stunned anyone with the truncheon because they have always gone crit before hand

What i suggest is that the disablers are removed but not the truncheons and we see if its broken and abused or if its actually ok.

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
think this is fine with no disablers

**Pull request merged**
