### PR TITLE
Honk mech recipe & stat buff

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR

Honker mech:
- faster movement speed (still slower than Ripley)
- removed structural damage and made dps slightly higher than ripley
- recipe made much cheaper

## Why / Balance

I found the Honker unusually absent from rounds despite being one of two mechs and no longer locked behind T3.

Testing confirmed outdated stats: unusually low speed compared to Ripley, slow yet high damaging melee with structural component, and being extremely expensive to fabricate. This may have to do with mechs in general being undermaintained and the Honker formerly being a T3 tech.

- increased the speed to be approximately 75% of sprint speed (assuming 4.5 base sprint speed, 3.38 is equivalent to 75%). For comparison, the Ripley is faster at 3.6 sprint speed (equivalent to 80%) but much less armoured with 75% damage transfer.

- decreased damage per swing from 25 to 16 and removed structrual damage, increase swing rate from 0.75 to 1 - should feel more consistent in combat

- decreased the recipe cost to what seems more in-line with a T2 tech - many parts no longer require a full stack of steel each, and bananium cost is decreased as it is typically ignored by salvage.

Please keep in mind the Honker mech has a 50% damage transfer to the pilot (ignoring other stats). This may need to be adjusted for balance.

Changes overall are to increase accessibility of Honker mechs and improve interest in mech code.

## Technical details

yaml changes only:
- mechs.yml
- mech_parts.yml

Weirdly 100 bananium in yaml material seems to be equivalent to 2/3 (0.66) bananium in-game, I haven't been able to explain why

## Media

image

image

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

:cl: Damn Feds
- tweak: Honker mech is much cheaper to produce, hits slightly harder and faster overall. Honk!

### CODE REVIEW

**Comment by Kadeo64** [comment]
Honk was locked behind tier 3? as far as I remember it's always been tier 2 civilian. 

But also, I would recommend reverting the movement speed and instead adding the airtight component that the HAMTR and VIM have. The Honk is a combat mech after all.

**Comment by K-Dynamic** [comment]
> Honk was locked behind tier 3? as far as I remember it's always been tier 2 civilian.
> 
> But also, I would recommend reverting the movement speed and instead adding the airtight component that the HAMTR and VIM have. The Honk is a combat mech after all, it doesn't need movement speed when it has ranged weapons.
> 
> (disclaimer: mech ranged weapons will never happen)

Honk horn ranged weapon :trollface: 

The move speed was _really _slow__ so I'd rather keep it at that for now. The airtightness is a bit weird as I recall breathing issues for crew, as well not wanting it to go up against nukies (it's a *civilian* clown mech; more armoured but not more combat-worthy than a ripley exosuit)

**Comment by Kadeo64** [comment]
> Honk horn ranged weapon :trollface:

the horn is a glorified noisemaker right now


> The airtightness is a bit weird as I recall breathing issues for crew 

valid I'm pretty sure airtightness is buggy on humanoids 

>as well not wanting it to go up against nukies (it's a _civilian_ clown mech; more armoured but not more combat-worthy than a ripley exosuit)

the HONK is only in civilian because clown is in service. It's designed to be a powerful combat mech with clown themed equipment in ss13. Plus, nukies should get used to fighting combat mechs anyway.

**Comment by deltanedas** [comment]
airtight is fine theres proper air filtering now

**Comment by Kadeo64** [comment]
> airtight is fine theres proper air filtering now

cover5
god I love hiatuses

**Comment by EmoGarbage404** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by K-Dynamic** [comment]
Reopen

**Comment by Golinth** [comment]
> The airtightness is a bit weird as I recall breathing issues for crew, as well not wanting it to go up against nukies

Now that nukies don’t have fire axe prying, spacing is much less prevalent. (Plus an emergency EVA can be worn while piloting it, negating the lack of air tightness anyway) and like delta said, crew breathing through airtight is good now

**Comment by K-Dynamic** [comment]
I'm a bit put off at the honker construction eating clown shoes, clown mask and needing to be 'honked' by a bike horn

I _might_ add a clown costume crate idk

**Comment by Flareguy** [comment]
This is a buff to a feature that's basically barely functional to begin with (mechs,) and is probably only going to serve to mess up balance, especially when factoring in the lack of the all of the combat downsides they had from SS13.

Thank you for your contribution, but we're going to need more feature-complete mechs before doing this.

**Pull request closed without merging**
