### PR TITLE
Resprite antique laser pistol

### PR DESCRIPTION
**Pull request by RiceMar1244**
## About the PR

Resprites the antique laser pistol to use a more focused color palette and to look slightly more like its reference, the System Shock 2 laser pistol, while retaining its familiar in-game form.

## Why / Balance

The current sprite uses a lot of different shades of grey and white, so I wanted to try to touch it up a bit, and ended up doing so in both color and form with a new sprite. I went through a few versions regarding this, but I am settling on something closer to the in-game sprite because I enjoyed the unique identity the weapon has grown into.

## Media

Here is the current updated sprite after feedback in the comments:

github
ingame
reference image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: RiceMar1244
- tweak: Resprited the captain's antique laser pistol.

### CODE REVIEW

**Comment by MACMAN2003** [comment]
the charge area seems a bit small

**Comment by KittenColony** [comment]
I don't know what to say specifically but it looks flat

It's definitely an improvement over the current model but it has no depth to it

**Comment by MozarteanChaos** [comment]
the lineart in particular could use some work - most items in SS14 use coloured outlines, sometimes even incorporating some shading into the lineart, so a pure black outline seems out of place

**Comment by Emisse** [comment]
looks good but outline needs to not be so dark all the way around

**Comment by RiceMar1244** [comment]
Thanks to all who commented so far for the feedback. Ill follow your advices and update the sprite.

**Comment by superjj18** [comment]
> the charge area seems a bit small

Maybe make it two pixels tall instead of one?

**Comment by RiceMar1244** [comment]
To be clear to anyone viewing this PR while its drafted. I havent been able to do too much work the past few days but im working on a version that looks alot more like the current sprite. Had fun making the on-model version but im liking how this is turning out more.

**Comment by Golinth** [comment]
The new version looks significantly better, and is an improvement on the current sprite IMO. I love how it looks.

**Comment by ps3moira** [comment]
This don't look as interesting as the original to me at least. The cool glowing lights and details on the original are lost in exchange for a flatter look with a NanoTrasen logo.

**Comment by RiceMar1244** [comment]
I appreciate all feedback on the details and am genuinely considering it. On that note, I don't know if I need to clarify this, but I just wanted to note for the sake of reviewing that the emote reactions to this PR are not necessarily indicative of a consensus on this sprite, as a lot of the initial thumb downs were added in response to the poor-quality first-draft sprite.

**Comment by RiceMar1244** [comment]
On that note though, since this isnt currently being reviewed afaik, Ive got some time to talk about that specific detail regarding the logo where the light once was.

**Comment by RiceMar1244** [comment]
The intent with this sprite is to preserve the original sprite's design of a clunky outdated laser weapon that has some ornamental value to the captain. I think the logo speaks strongly to the weapon's ornamental value while the lights speak more to its outdatedness.

1) The green lights: The green lights are neat because they are big and ugly, to be entirely honest. The big light panel on the side of the gun speaks to its unsophisticated design as a less modern laser weapon. You'd wonder if the lights were there to provide some overly complicated readout that only meant something to a weapons researcher or if it was the result of some forced effort to make the coolest new laser weapon on an emerging market.

2) The logo: The logo is also neat, and Ill get it out of the way real quick that I think it fits rather snuggly in the more angular shape of the white section. This weapon is a relic of technological history, and whose history that is is not really specified, but I enjoy the idea that it could be Nanotrasen's history. Alternatively, I also think that the logo references a duty to Nanotrasen. One could think the captain themselves could have had the weapon decorated with the symbol of their duty.

**Pull request merged**
