### PR TITLE
Make server super popular

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR 

**Screenshots**

**Changelog**

:cl: Morty
- add: Added fun

### CODE REVIEW

**Comment by N3X15** [comment]
no fun allowed

**Comment by Morb0** [comment]
Ow. miss merge...

**Comment by ZeroDayDaemon** [comment]
Great PR!

**Comment by PJB3005** [comment]
Should've changed the text color too, then you would have had an instant merge. Too late now.

**Pull request closed without merging**
