### PR TITLE
Passenger Loadout Additions

### PR DESCRIPTION
**Pull request by KyuPolaris**
## About the PR
I added a bunch of the items found in the ClothesMate machine into the Passenger loadout options.

## Why / Balance

I made this change to give passengers a little bit more variety and uniqueness to their loadout if they ended up as a passenger since the passenger loadout is quite sparse and it saves the rush of passengers running to a ClothesMate.

## Technical details

YML changes

## Media
Medal_eWfjJ2gJ4q
Medal_FxfKwfYEQs
Medal_jSUII2fipU
Medal_TIfXI1cCQ1

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n/a

**Changelog**
:cl:
- add: The budget for clothes for passengers has been increased to include common ClothesMate items!

### CODE REVIEW

**Comment by lzk228** [comment]
not everything should be in loadouts

**Comment by JIPDawg** [comment]
Era of greytide is over. Although I personally think this bloats the load out a bit to much.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
All this does is add the drip you would have to run for round start to the loadout, this is a easy merge, the list wont even be that long since they will all be separated into their own category's, unlike how the vend itself is bloated.

**Comment by SebaenSah** [comment]
Seeing as these are features that are purely for visual customization and don't really add anything to the gameplay loop as a whole I literally see no reason why this is even a issue worth debating. Just merge it.

**Comment by UbaserB** [comment]
Its far too long of a list.. theres a way to implement it better but it requires coding.

**Comment by Cojoke-dot** [comment]
> Its far too long of a list.. theres a way to implement it better but it requires coding.

What do you mean? Uh... do you mean having subsections in loadout categories so you have to click an option to see all the colored outfits? Or like having jump suits and skirts filtered in some way?

**Comment by MayaIsIncrediblyDisappointed** [comment]
Made an account specifically to comment on this, boo fucking hoo its a bit bloated.
### No one fucking cares.
If there's a better way to implement it suggest it then, everyone whos commented against this has not provided anything as even a slight suggestion to how it could be improved.

Look, if they want the bloat reduced sure add the most common stuff then, but it's genuinely not worth debating it.

If anything, temporary bloat and someone can make a new PR when they code something to be cleaner to make it cleaner.

This would save a solid few minutes for newer players playing passenger to get drip, making them more likely to stay too.

**Comment by mirrorcult** [comment]
this is good and i think realistically should probably eventually just remove these from the clothesmate and have people do it through loadouts

**Comment by Hrosts** [comment]
> should probably eventually just remove these from the clothesmate and have people do it through loadouts

Counterpoint, there are situations when both civilians and antagonists might want to switch their clothes mid-round

**Comment by slarticodefast** [comment]
I just started working on a laundry machine PR like they exist in SS13. With that you could put your grey jumpsuit and a crayon inside to recolor it. That would avoid the item bloat in both the loadout and the clothesmate.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> this is good and i think realistically should probably eventually just remove these from the clothesmate and have people do it through loadouts

I do think we should have both, as the reasons stated above, sometimes you want to change drip midround, and all this PR does is   add the round start clothes to loadouts.

**Comment by KyuPolaris** [comment]
> > this is good and i think realistically should probably eventually just remove these from the clothesmate and have people do it through loadouts
> 
> I do think we should have both, as the reasons stated above, sometimes you want to change drip midround, and all this PR does is add the round start clothes to loadouts.

To add on to this, this PR only effects Passengers. Removing the clothesmate would effect everyone

**Comment by UbaserB** [comment]
> > Its far too long of a list.. theres a way to implement it better but it requires coding.
> 
> What do you mean? Uh... do you mean having subsections in loadout categories so you have to click an option to see all the colored outfits? Or like having jump suits and skirts filtered in some way?

I remember maintainers had a very specific idea but I cant quite remember what they proposed. The way I'd do it is a selection "jumpsuits" where if you tap if you can see the full dropdown of all jumpsuits. This way you can easily find jumpsuits/scarves/gloves without making it ridiculously long and full of lots of scrolling.

**Comment by UbaserB** [comment]
> > The way I'd do it is a selection "jumpsuits" where if you tap if you can see the full dropdown of all jumpsuits. This way you can easily find jumpsuits/scarves/gloves without making it ridiculously long and full of lots of scrolling.
> 
> So, the loadout system?

no i mean like, jumpsuits and jumskirts are seperated under the whole "jumpsuit" header on the left side
and hats would be "bandana" and "caps" and etc like that, dropdowns and not entirely new categories

**Comment by Veritable-Calamity** [comment]
Gonna put in my 2 spesos on this issue.

I agree that not everything should be in loadouts, but there is no true mechanical or design issue preventing this specific PR from happening. Sure, it's sprawl and it's a mess right now - that's why we iterate on code, and build off the shoulders of those that came before. We're in playtest - this may not be as big of an issue as people may suspect it is: we won't know until we try.

In regards to this PR, there is no harm in adding the ability for people to pull clothing selections from the clothesmate in the loadout screen. In fact, this actually speeds up rounds a little bit as the clothesmates are only used for those who want to change their look mid-round (or get non-job clothing) rather than roundstart dress-up.

My vote is for merge.

**Comment by Agustron24** [comment]
This is good, merge

**Comment by Agustron24** [comment]
Shame.

Oh true i quited ss14, anyways

**Pull request closed without merging**
