### PR TITLE
Adds small bar-themed Salvage

### PR DESCRIPTION
**Pull request by Delete69**
## About the PR 

**Screenshots**

image

**Changelog**

:cl:
- add: Adds small bar-themed salvage

### CODE REVIEW

**Comment by Delete69** [comment]
Toggle subfloor has been whacky, so the screenshot is a bit odd.

**Comment by Peptide90** [comment]
Update the change log to add: bar themed salvage map.

Or nothing if you want it a secret.

Makes me think of the fallout 2 encounter cafe of broken dreams, would be nice to get more themed things in like Prey etc.

**Comment by Delete69** [comment]
> Makes me think of the fallout 2 encounter cafe of broken dreams, would be nice to get more themed things in like Prey etc.
 I tried to add a dead human, and outfit him as the a bartender, as well as 2 live Xeno. The Xenos died and upon saving and revisting the map later, the human body and Xenos were gone ;\

**Comment by PaulRitter** [comment]
shotgun on the salvage might be a tad too op imo. especially if it spawns everytime

**Pull request closed without merging**
