### PR TITLE
Secoff senior uniform fix

### PR DESCRIPTION
**Pull request by Kukutis96513**
## About the PR

moved afew pixels in the senior secoff uniform sprite

## Why / Balance

sprite was weird compared to the rest of the jumpskirts
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
### Before the sprite fix 
Screenshot_396
### After the sprite fix
Screenshot_395

## Breaking changes
 hopefully none.

**Changelog**

Ignore the long list of commits, git's acting weird and shows unrelated stuff, nothing should be affected except the senior secoff sprite.

### CODE REVIEW

**Comment by Kukutis96513** [comment]
@QuietlyWhisper it's been fixed i think

**Comment by Dutch-VanDerLinde** [comment]
Did you just replace the senior jumpskirt with the normal sprite

**Comment by Kukutis96513** [comment]
> Did you just replace the senior jumpskirt with the normal sprite

just moved like 4 pixels on each side sprite i'm fairly sure

**Comment by Kukutis96513** [comment]
i'm fairly sure the actual secoff jumpskirt has been fixed already, this only fixes the senior jumpskirt

**Comment by Dutch-VanDerLinde** [comment]
Erm then why do the files changed just show the normal jump skirt

**Comment by QuietlyWhisper** [comment]
> @QuietlyWhisper it's been fixed i think

Thats a really old screenshot of the basic security jumpskirt that's already been fixed unless its broken on other jumpskirts too

**Comment by Kukutis96513** [comment]
> > @QuietlyWhisper it's been fixed i think
> 
> Thats a really old screenshot of the basic security jumpskirt that's already been fixed unless its broken on other jumpskirts too

yeah apparently it wasn't fixed for the senior jumpskirt, this PR does that now

**Comment by VasilisThePikachu** [comment]
Not sure what all those master Marge's are about, I also assume you checked out from another branch. No worries though. This seems fine now. Though maybe do check your git to not have to do all this every time.

**Pull request merged**
