### PR TITLE
LED-display gasmask

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

Adds a Protogen mask. For the record im not a furry, just cant sleep knowing that this mask is not in the game.

You can hate me for it, but one day the crude biomass that you call a temple will wither, and you will beg my kind to save you. But I am already saved, for the Machine is immortal...

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

зображення

**Changelog**

:cl: Tunguso4ka
- add: Added a new gas mask with a LED-display.

### CODE REVIEW

**Comment by deltanedas** [comment]
how do i close someone elses pr

**Comment by GoodWheatley** [comment]
> how do i close someone elses pr

As a person with the power to close PRs, 

:trollface: cry about it

**Comment by LankLTE** [comment]
Not an artist but this has no depth- it’s really hard to tell what it’s actually supposed to be, especially from the front.

**Comment by Nimfar11** [comment]
Is it possible to make it animated?

**Comment by CatMagic1** [comment]
make it emaggable

👍

**Comment by deltanedas** [comment]
emag protogen mask to give it illegal protogen sprite :trollface:

**Comment by lzk228** [comment]
equipped sprite is for reptilians, make ut for humans

**Comment by lzk228** [comment]
amd i think if it LED, it should has more functionality than any other mask

**Comment by TemporalOroboros** [comment]
You made me google protogen to figure out what what looks off with that mask.
First couple results seem to indicate that the display doesn't wrap around the entire skull: it's just from the jawline/cheekbone/eyesocket/hairline forwards.

Also seconding the "if this exists it should probably have animation or what have you".

**Comment by deltanedas** [comment]
something actually cool would be different sprites which get updated when the wearer emotes things like laughs cries etc

**Comment by Tunguso4ka** [comment]
okay, thats sounds complicated. I accept your challenges!

**Comment by MrGreen006** [comment]
When I first saw this PR I instantly thought of a purge mask. This is cool too.

**Comment by VasilisThePikachu** [comment]
amazing, finally this is becoming more of a furry game then it already is

though I will be honest it does look a lil goofy

**Comment by Flareguy** [comment]
Thank you for your contribution. Unfortunately at this time, we don't think this item is a good fit for the game.

**Comment by TemporalOroboros** [comment]
As Flare just copypasta'd the minimum viable close message and you deserve an actual explanation as to why this was closed it basically boiled down to two reasons:
1. Some of the maints are a bit wary of adding anything that's just furry culture. They didnt discuss any particular reasons, just don't like the vibes.
2. The person who originally created protogens or their predecessor believes that they have the copyright for the design as a whole and we don't really want to fight off a DMCA claim, even if it's probably baseless.

**Comment by Tunguso4ka** [comment]
> As Flare just copypasta'd the minimum viable close message and you deserve an actual explanation...

thanks.
I knew it would be closed, so i was ready for it.

**Comment by JoeHammad1844** [comment]
it would fit better if it was more like daft punk/purge style instead of protegen

**Pull request closed without merging**
