### PR TITLE
Fixed Lizard swipe

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
It recently came to my attention that lizards on their melee attack did piercing damage instead of slashing damage, this PR switches that. (Thank you Aexxie for informing me of this terror)

## Why / Balance
Reptilian melee (unarmed) is now a claw swipe

## Technical details
Changed Prototypes/Entities/Mobs/Species for reptilians, flipped piercing to slash on them

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: 
tweak: Tweaked reptilian unarmed attacks to deal the correct damage types

### CODE REVIEW

**Comment by Eden077** [comment]
The universe can finally be at peace

**Comment by KittenColony** [comment]
balance has been restored

**Comment by metalgearsloth** [comment]
Isn't piercing the bullet one that goes through a lot of stuff.

**Comment by KittenColony** [comment]
> Isn't piercing the bullet one that goes through a lot of stuff.

piercing just means it pierces something, either a sword stab, a spear, a bullet or bite

**Comment by Aexxie** [comment]
Finally. Just a pointer, we still need the attack sprite to change (the slashing one).

Could be interesting to change spiders' attack sprites to the bite ones, too.

**Pull request merged**
