### PR TITLE
Added the Cardborg

### PR DESCRIPTION
**Pull request by Captain-Wet-Beard**
The cardborg believes that they are a cyborg. This is likely a case of space madness.

## About the PR
While working on cyborg and robotics related stuff, I ended up making this role to test out some basic concepts. Since the cardborg believe's they're a cyborg, they must obey Asimov's Laws. I think the role might be fun, at least to practice some of the RP elements of cyborgs before they're implemented.

**Screenshots**
Beep Boop

**Changelog**

:cl:
- add: Added the Cardborg as a playable role.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
This seems better suited as an admin event

**Comment by Captain-Wet-Beard** [comment]
> This seems better suited as an admin event

I could see that, especially if the costume isn't removable

**Comment by Emisse** [comment]
this is what no silicons has drove us to

**Comment by mirrorcult** [comment]
im fine with adding this only if a mapper wants to put this in their map as a funny thing

**Comment by metalgearsloth** [comment]
@Captain-Wet-Beard have you talked to any mappers about it.

**Comment by mirrorcult** [comment]
reopen this PR if it can be added to a map

**Pull request closed without merging**
