### PR TITLE
ERT troop transport ship

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Adds a small troop transport ship for ERT use

**Media**

image
pictured above is the troop transport shuttle (ERT does not spawn on the shuttle by default)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no change log lolmao

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Why does it look phallic

**Comment by JoeHammad1844** [comment]
I never thought it looked like that until now, but it looks fine on the mas scanner so im SURE it's fine

**Comment by Emisse** [comment]
theyre intended to use the dart

**Comment by JoeHammad1844** [comment]
this is a lot smaller and is intended to be somewhat disposable, could also work for ship v ship (I even made a syndie version)

**Comment by metalgearsloth** [comment]
We've decided not to merge this at this time as the dart is intended to be used and new maps entail more maintenance burden, sorry.

**Comment by JoeHammad1844** [comment]
zad

**Pull request closed without merging**
