### PR TITLE
bartender suit

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR

Makes the bartender suit consistent on all sides
## Why / Balance

it's goofy
## Technical details

texture edit
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Skarletto** [comment]
idk why the pr was named that oops

**Comment by Skarletto** [comment]
im gonna buy the company named github

**Comment by Flareguy** [comment]
I think the lighter pants look a lot better, please base the color fix off of those instead of the back sprite.

**Comment by Skarletto** [comment]
aight

**Comment by Skarletto** [comment]
boom done

**Pull request merged**
