### PR TITLE
feat: electricution for AI

### PR DESCRIPTION
**Pull request by Fildrance**
## Requirements

- [ ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Everturning** [comment]
what does this do

**Comment by ScarKy0** [comment]
> what does this do

Flidrance posted this for me to use the code in my PR
Currently working on allowing AI to electrocute doors and toggle emergency access

**Comment by muburu** [comment]
> > what does this do
> 
> Flidrance posted this for me to use the code in my PR Currently working on allowing AI to electrocute doors and toggle emergency access

shouldn't you just add an action that lets them pulse wires instead of making shocky doors a dedicated action (it would be applicable to alot of other stuff as well)

**Comment by ScarKy0** [comment]
> shouldn't you just add an action that lets them pulse wires instead of making shocky doors a dedicated action (it would be applicable to alot of other stuff as well)

Having AI open a panel and then find the wire to pulse seems a lil annoying

**Comment by ArtisticRoomba** [comment]
AI is wired directly into all the airlock doors, they have executive control over them through that wire. It fits better to just have it through the radial menu. 

We should also think about if we want AI to be able to "hack" airlock doors to assume normal control over them when the AI wire is cut. Something like a 30 second timer/doafter.

**Comment by slarticodefast** [comment]
> Flidrance posted this for me to use the code in my PR

You don't need to make a PR for that. They can simply push it to their own fork and you pull it from there.
If you have a PR that is ready for review, please add a PR description so people know what it is about. I am closing this for now, leave a comment if you want it reopened.

**Pull request closed without merging**
