### PR TITLE
add leather satchel to all loadouts

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
its in the master tider 10h passenger group

## Why / Balance
satchel

**Changelog**
:cl:
- add: Leather Satchels can be picked in loadouts now.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Why all loadouts...

**Comment by deltanedas** [comment]
why not

**Comment by UbaserB** [comment]
Blessed, i always go to the clothesmate to get the leather satchel regardless of my job.

**Comment by metalgearsloth** [comment]
just code global loadouts bro

**Comment by deltanedas** [comment]
wyci goober

**Comment by EmoGarbage404** [comment]
i dont really see a point of just devaluing one of the few actually valuable and sought after general loot items because people want it. we already has a similar convo about general clothing and stuff in the clothesmate and the decision was to close it.

> wyci goober

also sticking an additional group onto every single loadout just to add one item is incredibly smelly. like thats a serious long term maintenance problem.

**Pull request closed without merging**
