### PR TITLE
nukie reinforcements

### PR DESCRIPTION
**Pull request by Vaaankas**
**Changelog**
Reinforcements agents bought from nukies' uplink will have the NukeOperative component and count as nukies for the gamerule.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
finally, now we can get turrets back on the ship, right?

**Comment by deltanedas** [comment]
i think this is for:
- greentext
- if reinforcement stays alive round wont end anymore

**Comment by lzk228** [comment]
does they be labeled as an antag?

**Comment by Vaaankas** [comment]
> does they be labeled as an antag?

no, same as regular reinforcement agents. its out of scope of this PR tho

**Pull request merged**
