### PR TITLE
Darts can now pop balloons. 

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

BalloonPopperSystem now also works on being thrown, and the component has been given to darts. The official security anti-inflatable armament has also been given the ability to be thrown for the same effectiveness as being hit- it's sharp, but it doesn't embed as you're presumably aiming at the balloon (the 1 pierce damage is emotional)

## Why / Balance

Darts are sharp and should pop balloons. Any references to "bloons" are entirely circumstantial. 

## Technical details

Adds a check for ThrowDoHitEvent that pops the balloon. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/968452f5-89ed-4551-8ce3-41b3da047a72

**Changelog**

:cl: Lank
- add: Darts can now pop balloons. Keep them away from any monkeys.

### CODE REVIEW

**Comment by LankLTE** [comment]
Note that, to the best of my testing, the popping audio is also broken on a current build and has nothing to do with my changes.

**Comment by Cojoke-dot** [comment]
This PR is integral to the state of the game

**Comment by mirrorcult** [comment]
wondrous

**Comment by TheShuEd** [comment]
I suggest removing the BalloonPopper component, and adding this functionality to the SharpComponent

**Comment by LankLTE** [comment]
> I suggest removing the BalloonPopper component, and adding this functionality to the SharpComponent

Main reason I don’t is things like darts and the inflatable device can’t cut food or butcher (which I believe is the purpose of it?). We also don’t want balloons being popped by everything because they’re just cosmetic, as-is it’s just the inflatable device (basically a meme item) and now darts (also for a meme)

**Comment by TheShuEd** [comment]
well, maybe, I just don't like having separate systems and components for memes. As for me, memes should exist only at the yml level

**Comment by TheShuEd** [comment]
Maybe merg with DamageThrowOnHit?
With check on piercing/slash damage

**Comment by TheShuEd** [comment]
or in general, replace it with a system with shields that take part of the damage

**Comment by luizwritescode** [comment]
> I suggest removing the BalloonPopper component, and adding this functionality to the SharpComponent

> Maybe merg with DamageThrowOnHit?

Be very careful when coupling components as that is the main reason buggy interactions start happening.

That being said, this PR is a fun addition. I like it.

**Comment by dvir001** [comment]
You forgot to assign monkey the ``Monkey`` faction and Ballons the ``Ballons`` one and make them hostile to another.

**Comment by Plykiya** [comment]
> > I suggest removing the BalloonPopper component, and adding this functionality to the SharpComponent
> 
> > Maybe merg with DamageThrowOnHit?
> 
> Be very careful when coupling components as that is the main reason buggy interactions start happening.
> 
> That being said, this PR is a fun addition. I like it.

vietnam flashbacks to pull dragging throwing and everything smashing into the floor as I move it around

**Pull request merged**
