### PR TITLE
Mice no longer have to eat an entire bakery to stay alive

### LINKED ISSUE #10594: Mice need way too much food/drink.
## Description

You are a mouse, a small, tiny, cute miserable little shitter designed to rest tightly in the pocket of their owner, or walk around the station consuming food.
You, just so happen, to be very small, and weight not a lot, except for the fact that you can eat through the entire kitchen, botany, every department with their donk pockets and pizzas, and still not feel full, not even close, no, you won't even feel that you ate all that, you'll at some point start starving even if you ate food throughout that entire timespan whilst doing it with supreme efficiency.

**Additional context**

tl;dr, mice need to eat much, much less to actually sustain themselves, unlike how it's currently unintentionally(?) realized wherein you need to eat 400 pounds of food to actually go out of the starving debuff for 2 minutes. (not like you can do the 400 pounds, you can eat 2-3 bites per cycle AT MOST)

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR 
Closes #10594 and makes it so mice can last 17 minutes until starving instead of 9.

**Changelog**

:cl:
- tweak: Mice no longer have to eat an entire bakery to stay alive

### CODE REVIEW

**Comment by mirrorcult** [comment]
this doesnt fix anything. its not that mice need to eat too often (they -should- have to eat pretty often), its just that they should have to eat less food to be satiated, which this does not affect.

**Comment by HoidC** [comment]
wtf how did you merge to master

**Comment by EmoGarbage404** [comment]
average github chicanery.

**Comment by OctoRocket** [comment]
so basically I did an oopsie

**Comment by OctoRocket** [comment]
I discarded my change and synced my fork of the repo, removing the commit

**Comment by PaulRitter** [comment]
lmfao

**Comment by OctoRocket** [comment]
Well since I have all of your attentions, would you rather mice have to eat less or what

**Comment by OctoRocket** [comment]
I am but a mere typo fixer though so this pr is most likely going to remain closed

**Pull request merged**
