### PR TITLE
Renamed "Substations" to "Transformers"

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
I renamed substations to transformers.

## Why / Balance
image
image
image
These are *all* substations. The problem with a "substation" is that it is a very very vague term. It's pretty much just any facility between the generators and consumers that performs any number of operations (including and mostly converting voltages but they do other things too)

Transformer is a more *apt* term because transfomers are a device that does one thing, raise or lower voltage. Transformers are also more consistent with the sprite.
image

I was talking about this in general, about how transformer would be a more apt term for what we currently call substations, and someone challenged me to PR it, so I did.

## Technical details
I literally did a find and replace for all instances of "substation" to "transformer" using vscodiums preserve case feature. I also changed file and foldernames and did some additional cleanup. I tested all facets of substation operation after making the changes (converting/storing power, power monitoring, power sinks, the ability to make the boards and the machines themselves) and all worked perfectly.

This does make modifications to map files as well, which means custom names ("Command Substation", "Arrivals Substation", etc.) will also be changed to transformer, requiring no intervention from map maintainers.
I also set migration.yml to include the changes from substation to transformer

I'll honestly be super surprised if this actually gets merged, as I mainly did this for a laugh and folks told me that maintainers would not like a find&replace. However I did put care into testing and cleaning up the resulting find&replace and I think "transformer" is much more accurate for what we currently call substations

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Shouldn't be any

**Changelog**

:cl:
- tweak: Substations are now known a little more aptly as transformers!

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
This PR is not going to get merged.

**Review by deltanedas — APPROVED** [review]

**Comment by mirrorcult** [comment]
do not manually find & replace entity ids, use a migration

**Comment by IProduceWidgets** [comment]
Why didn't you just change the name of the entity? I don't super care, but it does seem like this is going to be issue bait.

**Comment by Partmedia** [comment]
I don't think it's appropriate to replace all of the entity ID's. This is going to cause a lot of breakage on downstreams as well as in localization strings, and churns a lot of files in the repository without a good reason. At the most, this should have only been a name change.

While I agree that it is more accurate to call the device a "transformer" and not a "substation", players are likely coming with an expectation of some amount of agreement with SS13 and the old terminology. There's another argument to be made: this is NanoTrasen, so somehow they've miniaturized all of the components of a substation system, including transformers and breaker boxes, into one device.

Given that it's not even clear whether HV/MV/LV is AC or DC, it's kind of moot to call this a "transformer". As far as I can tell, everything is a DC power flow and so this should be a "large DC buck converter".

**Comment by Partmedia** [comment]
Transformers are also purely passive devices; our substations have a battery and there may be a UI planned. Unless there are commensurate behavior changes, our substations are truly substations and not transformers.

**Comment by Moomoobeef** [comment]
I hadn't even thought of downstream implications, that's a yikes. Plus partmedia honestly makes a good point, so I'm going to close this. I end up making another one down the line that is less haphazard but I don't feel like working on that any time soon as I have a few other projects (both ss14 and not) atm, this was just something I tossed together quickly.

Thanks for the feedback everyone

**Comment by Peptide90** [comment]
My two cents on this closed PR for if the author comes back to it.

This is the future and the voltages could still be pretty low for HV so a mini substation is very apt actually. The device performs switching on and off so it contains switchgear like a sub. Partmedia is very correct that a transformer is passive and only does one thing. 

Transformers could totally be a cheap alternative addition to the game but there's very little benefit to that over a regular substation

**Comment by Moomoobeef** [comment]
maybe we should add complicated switchgear for HRP engineering :godo:

> My two cents on this closed PR for if the author comes back to it.
> 
> This is the future and the voltages could still be pretty low for HV so a mini substation is very apt actually. The device performs switching on and off so it contains switchgear like a sub. Partmedia is very correct that a transformer is passive and only does one thing.
> 
> Transformers could totally be a cheap alternative addition to the game but there's very little benefit to that over a regular substation

**Pull request closed without merging**
