### PR TITLE
Flatpacker Tweaks

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

- add a label telling people to insert a board (nothing told them to do this)
- change the no board menu to look less barren
- center text in the cost box
- lower costs slightly
- Make boards be consumed on pack

## Why / Balance

Main balance change is consuming boards on packing. Previously, they were reusable. This is mostly okay, as most machines don't really pose a huge issue being in large quantities. However, especially with the addition of computers to the flatpacker, duping rare equipment and boards such as salvage magnets, research servers, ID console boards, communication console boards, etc is a pretty notable issue.

I lowered the price a tad, not really enough to offset it, but just to throw a small bone.

## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The flatpacker now consumes boards when packing them.

### CODE REVIEW

**Comment by mirrorcult** [comment]
i did think it was weird it didnt consume the board

**Comment by EmoGarbage404** [comment]
> i did think it was weird it didnt consume the board

i thought it would be cool then i realized "oh yeah producing 20 salvage magnets is probably a bad thing"

**Comment by GreyMario** [comment]
actually that sounds fucking amazing let's have an 80 pop server with 20 teams all just playing magnet salvage

**Comment by DogZeroX** [comment]
rip material economy

**Comment by mirrorcult** [comment]
flatpacker 2001 that doesnt consume the board

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
