### PR TITLE
Red crowbars no longer fit in pockets

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

It's not good for balance when one of the variants is stronger than the rest. It was mistakenly changed in #30828 and I bet Emisse totally skimmed over it, which is how it got merged.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ubaser
- fix: Red crowbars no longer fit in pockets.

### CODE REVIEW

**Review by lzk228 — CHANGES_REQUESTED** [review]
then you also should remove "A pocket crowbar" part from its description

**Comment by Pumkin69** [comment]
i mean i agree but i also think crowbars should fit in pockets all together

**Comment by UbaserB** [comment]
> then you also should remove "A pocket crowbar" part from its description

yea true

**Comment by thebadman4662** [comment]
If its smaller than 2x2 it should fit in pocket to be consistent with other items.

**Comment by UbaserB** [comment]
test fail doesnt look related

**Comment by keronshb** [comment]
I believe Pocket Crowbars are fine.

**Comment by ninruB** [comment]
I'm not even sure why we're removing pocket crowbars as a whole considering that in the original PR discussion Emisse, among others, agreed that pocket crowbars are fine.

**Comment by UbaserB** [comment]
> I'm not even sure why we're removing pocket crowbars as a whole considering that in the original PR discussion Emisse, among others, agreed that pocket crowbars are fine.

I'm going to be checking in with the maintainer team again to see what's best, especially considering the new PR.

**Pull request merged**
