### PR TITLE
Automatically merge changelog files

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR 
Allow downstreams to have their own changelog yml file.
It will automatically load all yml files in `/Changelog/`, merge, sort by time add return as one changelog.

**Screenshots**

**Changelog**

### CODE REVIEW

**Comment by PJB3005** [comment]
How does this handle merging IDs between the files?

**Comment by Morb0** [comment]
> How does this handle merging IDs between the files?

Don't see a good solution here. Only these:
- Use `Changelog.yml` as a base file and add new entries from other files using its last entry ID.
- Try to use only  in code total length of array with all entries from all files.

**Comment by metalgearsloth** [comment]
Do we even need to merge the IDs? They're not used for display and I imagine any downstreams could just point their action at their own file.

**Comment by AJCM-git** [comment]
There seems to be no more interest on discussing this further anytime soon

**Pull request closed without merging**
