### PR TITLE
Murders CEV-Eris bookshelves in cold blood

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Ports the bookshelf sprites from old /tg/station, but repalettes & reshades them to not have 5 million colors.
While these are probably objectively ""worse"" from a technique standpoint (as useless as a metric as that is,) I feel like the artistic consistency is more important overall.

Also, Jesus Christ, just look at it. It barely even looks like wood.

paintdotnet_m0ukpJxIV6

This USED to also fix the issue with bookshelves taking eons to fill, but it causes an error when over-filling sometimes so tests fail ~~even though the game literally stops it from overfilling.~~ I do not feel like going through orGroup CBT right now, so for now you will still be held captive to never seeing the bookshelf filled sprites.

**Media**

q8yytVcFG8

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Bookshelves have been resprited, and no longer look like they are made out of anomalous plastic pretending to be wood.
- tweak: Bookshelves now take slightly longer to destroy.

### CODE REVIEW

**Comment by Emisse** [comment]
these feel weird for some reason, they feel chunky?

**Comment by JoeHammad1844** [comment]
they look out of place

**Comment by Emisse** [comment]
i think you should repalette the eris ones with these but keep the shape these feel like chunky peanut butter

**Comment by AJCM-git** [comment]
@Flareguy You coming back to this? I also like the old palette and perspective better, but current shelves carry WAY too much so a mix of both could do the trick

**Comment by Flareguy** [comment]
> @Flareguy You coming back to this? I also like the old palette and perspective better, but current shelves carry WAY too much so a mix of both could do the trick

I'll consider it once I'm finished with my current projects - If I don't do anything in the next few days it's probably safe to close (assuming I don't just do it myself.)

**Pull request closed without merging**
