### PR TITLE
Add maximum atmos temperature limit

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
Adds `Atmospherics.Tmax`, a maximum absolute temperature temperature limit for gas mixtures.

## Why / Balance
Safe numeric code enforce numeric ranges to be within a certain well-defined range. For example in a temperature simulation, it is safe to constrain temperature in a "reasonable" range where we know that the physical laws stop applying. There is already such a limit for the minimum temperature; this adds one for the maximum temperature.

This should never happen:
image

And of course while it is better to fix the problem at the root, bugs happen and code should still be robust.

### Balance
Anything that scales with temperature, e.g. damage and reaction rates, can still go through a very big range with this temperature cap.

### Physical Justification
These sorts of temperatures would never exist in real life for a variety of reasons:
- At some pressure the container would just explode, venting it
- At some temperature the container would just melt, also venting it
- At some temperature any gas would instantly converted to plasma, causing it to violently destroy the container

While it is true that temperatures exceeding this can exist on stars, that sort of defies the simple $PV=nRT$ physics we have. In numerics speak, we'd say that this is *out of the domain of our model*.

### CODE REVIEW

**Comment by Ilya246** [comment]
1) i'm pretty sure this makes maxcaps impossible even if we fix the other changes
2) 20000C is very little, unless we revert this once we get pipe bursting
3) i believe this kills a lot of TEG setups
setting it to around 200000C or 140000C should work better

**Comment by comasqw** [comment]
Maybe you’ll stop touching the atmosphere? this bug happened because of your shit-pr, and now instead of fixing it, you add a limit of 20,000. Genius.

**Comment by EmoGarbage404** [comment]
@comasqw if you're gonna shit up github with childish finger pointing at volunteers then you're just going to get banned.

You're not going to get many warnings.

**Comment by TemporalOroboros** [comment]
I strongly dislike the idea adding an upper temperature limit to atmos on principle. If we absolutely must, I request it be set to the Hagedorn or Planck Temperature as those are actual physical limits instead of some arbitrary cutoff.

**Comment by Holinka4ever** [comment]
In my honest opinion, early or later, they should be limit, due of humanity progress, cause its kinda funny and unlogical that atmos are able to syntez an entire sun in burn chamber that made from steel and glass.

But due of recently bug that allows to do it... Thats pr is looks like a bandaid of that mistake, rather than balance fix, and of corse, people will be on emotions, cause atmos the most intriguing and interesting mechanic in ss14, and it got limited due of bug.

So anyway, idea of giving limit is okay, someone told that instead if limiting, heat could be on fast cool itself due of some laws that i dont know, but making this due of "plasma flood" situation, is kinda harsh path to walk in.

**Comment by Emisse** [comment]
agree with temporal, seeing atmos hit exceptionally high numbers is also helpful for indicating a bug is present

**Comment by Partmedia** [comment]
> I strongly dislike the idea adding an upper temperature limit to atmos on principle. If we absolutely must, I request it be set to the Hagedorn or Planck Temperature as those are actual physical limits instead of some arbitrary cutoff.

I gave a few physical justifications for why a limit should exist in the PR description. The ideal gas law, and indeed the physical state of gas breaks down at high enough temperatures. What principle do you feel like is being broken?

Perhaps the limit set here is too low. Some here have suggested a few higher limits. I'm okay with a higher limit, we should decide what it should be.

There would still be ways to catch bugs, namely:

1. Hitting the debug exception that this adds.
2. Seeing the temperature limit be reached. Maybe the current limit is too small. But surely there is some limit that we can agree on should never be reached.

It feels like there is no limit now because you can represent infinity as a floating point. But due to floating point precision issues there already is a limit beyond which things just stop behaving correctly (see why we have to have space friction to limit the distance something flies from the station).

I'd liken this to a numeric seat belt that reduces damage when something goes wrong. A seat belt is not a band-aid.

> So anyway, idea of giving limit is okay, someone told that instead if limiting, heat could be on fast cool itself due of some laws that i dont know, but making this due of "plasma flood" situation, is kinda harsh path to walk in.

All gases cool to tiles, then to space, when superconduction is enabled. Superconduction is not enabled by default for a variety of reasons. In practice that would also limit temperatures because it's hard to fight $T^4$ scaling.

**Comment by Ilya246** [comment]
> Seeing the temperature limit be reached. Maybe the current limit is too small. But surely there is some limit that we can agree on should never be reached.

once again, i propose 200kK, i believe that temperature is not reachable unless you're deliberately trying to optimise a burn for extremely high temperatures and nothing else

**Comment by deltanedas** [comment]
20kC is nowhere near physics breaking and the starting point for a lot of burns
this will completely gimp teg

**Comment by Partmedia** [comment]
> That being said - the question we should be asking is: **are we sure we want a limit?**

Absolutely. In fact there's already a limit, it's called `float.MaxValue`. But limits of floating point precision mean that some operations don't behave as you would expect at much lower values.

> Such an arbitrary maximum introduces **new** edge-cases (possibly bugs), above being just one example, because now we are violating laws of not just physics, but mathematics as well. ∃x ∈ ℝ / { 0 } (x + x = x). That **is** going to bite us in the ass sooner than you think.

We're programming with real computers with real limits on the number of bits in the mantissa. The objective of this is to limit values in a range where floats behave relatively sanely. If you want to see on your own computer:

```
Python 3.9.18 (main, Sep 12 2023, 01:16:40)
>>> 3e305 + 1.1e305 - 1.1e305 - 3e305
-3.89812560456e+289
```

That number is not zero.

> If (and this is a very big if) we wanted to limit temperatures, in my opinion the best way to tackle this problem is by introducing some form of "temperature entropy" which would soft cap temperatures in a sane range, rather than hard capping it, like this:

I welcome a patch. Even then, a limit is prudent to make sure big numbers can actually return to zero. As I showed above, $x + y - y - x$ is not equal to zero when $x$ and $y$ are very large.

Tmax bumped to 200K.

**Comment by deltanedas** [comment]
before burn energies were nerfed, 200kK was very much a reasonable temperature you could get in normal gameplay. after the nerfs i doubt its possible to get without a dedicated max temp setup.

**Comment by LordEclipse** [comment]
> before burn energies were nerfed, 200kK was very much a reasonable temperature you could get in normal gameplay. after the nerfs i doubt its possible to get without a dedicated max temp setup.

did the nerf break atmos? Because atmos has been acting very funky for the past few days or so

**Comment by deltanedas** [comment]
burn nerf was just changing energy values so thats not related

**Comment by Partmedia** [comment]
> > before burn energies were nerfed, 200kK was very much a reasonable temperature you could get in normal gameplay. after the nerfs i doubt its possible to get without a dedicated max temp setup.

That's because the energies from before were not unreasonable. The "hard" limit should not be reachable through normal gameplay.

> did the nerf break atmos? Because atmos has been acting very funky for the past few days or so

No. This is better addressed in a separate thread, but the breakage is likely from https://github.com/space-wizards/space-station-14/pull/22803 which was partially addressed in https://github.com/space-wizards/space-station-14/pull/22876. I am aware of another issue but am waiting for an okay to adjust the clamping behavior of `AdjustMoles()`.

**Comment by deltanedas** [comment]
energy from before was not unreasonable compared to how it is now


https://github.com/space-wizards/space-station-14/assets/39013340/d5624f1d-d495-4437-ad85-a7301d1956e4

this fire from ~30m ago is now at about 1200K, which is extremely slow burning and cold when it should be fast and hot

**Comment by Ilya246** [comment]
> before burn energies were nerfed, 200kK was very much a reasonable temperature you could get in normal gameplay. after the nerfs i doubt its possible to get without a dedicated max temp setup.

actually no, before burn changes, even the hottest TEGs only got to around 90kK, and you couldn't reach anywhere above 140kK without deliberately building a temperature-burn setup due to how burns work

**Comment by EmoGarbage404** [comment]
200,000K is literally hotter than a fucking star. this is just to make sure floating point math doesn't shit itself and die at unreasonable values (a perfectly valid concern and something to account for). There's no reason why a realistic atmos sim would reach those temperatures nor would even the ability to _occasionally_ reach those temperatures justify the additional performance cost of migrating the entire system to use high precision.

**Comment by Ilya246** [comment]
> 200,000K is literally hotter than a fucking star. this is just to make sure floating point math doesn't shit itself and die at unreasonable values (a perfectly valid concern and something to account for). There's no reason why a realistic atmos sim would reach those temperatures nor would even the ability to occasionally reach those temperatures justify the additional performance cost of migrating the entire system to use high precision.

actually no, there are no such issues
i don't think there was any real reason to merge this

**Comment by Partmedia** [comment]
Thanks for writing in with your comments.

> So I want a design decision be made here. Do we want a temperature limit or not?

The [design decision was to limit pressure and temperature in most atmos devices](https://github.com/space-wizards/docs/pull/78). In practice pressure limits are set by bursting and temperature limits (through what you call "quantum thermal conductivity") are set by the (currently-disabled) "superconduction" code. This is partially implemented e.g. in https://github.com/space-wizards/space-station-14/pull/20931 but not quite ready for show time just yet.

Perhaps that is where our fundamental miscommunication was. I do appreciate your thoughtful comments here.

**Pull request merged**
