### PR TITLE
i made cryopod EMAG'able

### PR DESCRIPTION
**Pull request by justdie12**
https://github.com/user-attachments/assets/540f2f0e-9576-4309-b20b-1b7f9f57e92e

## About the PR

because it makes it easier for the syndicate to work, how will it take highrisk without a card with access to cryo if the head has gone to SSD? EMAG is a universal device.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by lzk228** [comment]
is it possible to deemag the pod?

**Comment by justdie12** [comment]
> is it possible to deemag the pod?

no cuz why

**Comment by lzk228** [comment]
> > is it possible to deemag the pod?
> 
> no cuz why

because it has TOO MUCH impact on the game, if traitor emags the pods everyone will be aware of going to cryo just because your equipment can be stolen
also i bet in every traitor round all the pods will be emagged

**Comment by deltanedas** [comment]
> everyone will be aware of going to cryo just because your equipment can be stolen

your gear can already be stolen by anyone with a microwave or a head/sec id, leave it in your locker

**Comment by VasilisThePikachu** [comment]
For the reasons stated above, i will sadly be closing the pr. Its a bit too much creep and there is no indication to someone inserting themselves into cryo that the current cryo is emaged

And webedit. Please use git

**Comment by justdie12** [comment]
> For the reasons stated above, i will sadly be closing the pr. Its a bit too much creep and there is no indication to someone inserting themselves into cryo that the current cryo is emaged
> 
> And webedit. Please use git

why indication is need?

**Pull request closed without merging**
