### PR TITLE
Allow some mobs to walk slowly

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

for a lot of mobs that have walkspeed the same as sprintspeed i reduced walkspeed
for details check files changed

## Why / Balance

i want to walk

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Reduced walk speed of some small mobs (mice, cockroaches, bees etc.)

### CODE REVIEW

**Comment by UbaserB** [comment]
can you let other species like mothroaches and cockroaches and stuff as well if they don't have it?

**Comment by lzk228** [comment]
> can you let other species like mothroaches and cockroaches and stuff as well if they don't have it?

yep, added

**Review by UbaserB — APPROVED** [review]

**Comment by slarticodefast** [comment]
Do they still trigger mousetraps when walking? See #30593

**Comment by lzk228** [comment]
> Do they still trigger mousetraps when walking? See #30593

yes they do

**Comment by slarticodefast** [comment]
Then it got my approval.

**Comment by IamVelcroboy** [comment]
Honestly, it should be bumped down so they don't. It's a fair tradeoff to be super slow or risk the snap. But a sneaky mouse should be able to avoid the traps

**Comment by lzk228** [comment]
> Honestly, it should be bumped down so they don't. It's a fair tradeoff to be super slow or risk the snap. But a sneaky mouse should be able to avoid the traps

well... i think it's out of scope of this pr

**Comment by IamVelcroboy** [comment]
> > Honestly, it should be bumped down so they don't. It's a fair tradeoff to be super slow or risk the snap. But a sneaky mouse should be able to avoid the traps
> 
> well... i think it's out of scope of this pr

It's really just a matter of making it like 1.9 instead of 2.5, but your PR your call 🤷‍♂️Just my suggestion.

**Comment by mierdapovareshka** [comment]
бля чё это за говно ебаное

**Pull request merged**
