### PR TITLE
Misc sprite changes

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

- Grey mice no longer turn brown on death
- Fax machine resprite
- Livestock crate resprite
- Remote signaller resprite
- Cell recharger resprite

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: Changed sprites of the livestock crate, t-ray, fax machine, remote signaller and cell rechargers.
- fix: Fixed grey mice changing colors on death.

### CODE REVIEW

**Comment by Kit0vras** [comment]
please, take fax sprites from TGstation, they a lot better

**Comment by GoodWheatley** [comment]
Like all of them except the fax and tray sprites, fax looks really weird from this perspective and tray doesn’t fit with the visual style of the other tools anymore

**Comment by potato1234x** [comment]
done

**Comment by Emisse** [comment]
the cell recharger tower might look better if its a bit shorter so it fits the lower profile of the other sprite

**Comment by EmoGarbage404** [comment]
The tg fax machine is super blueshifted, more than I'd consider comfortable for metal.

**Comment by brainfood1183** [comment]
fax machine looks angry

**Comment by Flareguy** [comment]
The remote signaler resprite is a little confusing to me. Comparing the two sprites side-by-side, it seems like it'd be a lot better to just give the old sprite a darker edge on the bottom to convey depth.
The new one is standing upright (which doesn't make any sense for a small object like it,) and the strong hueshift applied to it makes it feel a lot shinier than it should probably be IMO.

**Comment by Flareguy** [comment]
Also the /tg/ fax machine is basically as blue as an eris sprite, it's probably going to stick out like a sore thumb ingame. I think the one you had before was a lot better in that regard, if you want to update the fax machine you should probably use it instead (or at least repalette the /tg/ one.)

**Comment by potato1234x** [comment]
i agree, fax has been reverted

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
