### PR TITLE
Error entity

### LINKED ISSUE #9661: ERROR should be a spawnable item
## Description

Because funny
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sunbear-dev**
## About the PR 
I added a new entity that is an error. It has the food and slippery component.  Resolves #9661. 

I copied the error.rsi in RobustToolbox and moved it to Textures/Objects/Fun, I also formatted it to be more readable. Right now these files are otherwise the same, but if the error object ever get's changed in the future it makes more sense to have a copy in the textures folder.

**Screenshots**

afbeelding

**Changelog**

:cl: SunbearDev
- add: added an error as an object!

### CODE REVIEW

**Review by mirrorcult — CHANGES_REQUESTED** [review]
you shouldn't copy the rsi over, as moony said you should be able to use `/EngineResources/Textures/error.rsi` for the sprite state and have it work fine

**Comment by sunbear-dev** [comment]
The linter/autochecker does not like it, but I changed the sprite location to the path mentioned. Is this what was intended?

**Comment by ElectroJr** [comment]
The actual rsi path should just be `sprite: error.rsi`. Both the engine & content resources folder effectively get merged, and the sprite comp RSI paths all implicitly get a `/Texture/` prefix added

**Comment by sunbear-dev** [comment]
I finally understand now, I changed it and it works. Thank you for the help!

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
