### PR TITLE
Medical Scrubs Expansion

### PR DESCRIPTION
**Pull request by evilexecutive**
## About the PR

This is adding six new scrub colors to the game for Medical mains to express themselves. One of which requires an Emag to access. They can be found in Medical Scrub cates, as well as medical doctor lockers, order some from Cargo! Or maybe station medbays might start getting stocked with them. This PR has been converted to Wizden's master branch by request of the DeltaV dev team. 

As a note, I have intentionally not placed the cybersun scrubs in the syndicate uplink, because I'm working on a "Universal Clothes Bundle" template that will be used to add entire sets of drip. They'll be available via the uplink in a future PR, which is out of scope for this PR. 

**Media**
image
image (1)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: VMSolidus
- remove: Scrubs can no longer be obtained from the MediDrobe
- add: NT may have forgotten to check their MediDrobes for contraband
- add: Eight different colors of scrubs and surgical caps can now be found in medical scrub crates!
- add: Scrubs can now spawn in one of 8 exciting new colors. Please report sightings of a mysterious 9th color to management.(this needs to be mapped in)

### CODE REVIEW

**Comment by moonheart08** [comment]
Don't really like this as it removes color direction from medical spritework.
Medical is blue, not rainbow.

**Comment by rosieposieeee** [comment]
Yeah, medical is blue! And pink, and white. Trans flag scrubs please.

**Comment by Flareguy** [comment]
I mostly agree with what moony said. Please only put the blue scrubs in the medical lockers - even with labcoats it's still not clear what department they are at a glance.
The cyan scrubs are also a little redundant considering we already have blue ones, I would remove them.

**Comment by JoeHammad1844** [comment]
I like the cybersun one but not the rainbow one, it just doesn't fit medical and breaks a lot of immersion

**Pull request closed without merging**
