### PR TITLE
Black gloves are a lot darker now

### LINKED ISSUE #28474: Black gloves are visually inconsistent
## Description

They are far too pale compared to the rest of the black wardrobe (which i often wear) and it bothers me a lot. You can see an example in the screenshot below.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Slardar0609**
## About the PR

Changed black gloves texture to be darker
## Why / Balance

Black gloves' sprite changed to be darker
Fixes #28474
## Technical details

N\A
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A
**Changelog**

- tweak: Changed black gloves' sprite to be a lot darker

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
the increased darkness on the main color really hurts the readability on these

**Comment by UbaserB** [comment]
I never suggested to change the icon sprite, only the worn sprite.

**Review by Slardar0609 — COMMENTED** [review]
now icon is not dark, only the texture

**Comment by Brandon-Huu** [comment]
This is honestly so weird
Why can't we set the color of the sprite with yaml?

**Pull request closed without merging**
