### PR TITLE
Security biosuit sprite fix

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Makes the security biosuit use sprites from vgstation so that it's red, instead of blue.
It seems like someone forgot to port the tg sprites at some point. Despite the incorrect attribution, the blue ones are from Eris, which makes sense there since they have blue security. We do not.

## Why / Balance
Contrary to popular belief, security is not actually blue. It is red.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
If only they had a use right now...

**Comment by deltanedas** [comment]
urist has been mewing big time god damn

**Comment by Catdere** [comment]
> If only they had a use right now...

as if they had a use in ss13?

**Comment by TheShuEd** [comment]
try update from master to fix errors

**Comment by Hanzdegloker** [comment]
NewViro is just a year away...

**Pull request merged**
