### PR TITLE
Make lockers can be deconstructed only when unlocked now

### PR DESCRIPTION
**Pull request by TokenStyle**
## About the PR
Fixed lockers that was deconstructable even when they closed and locked and you didn't have access to them. In short - get stuff by 5 seconds, 5 sec it's time to screw down any locker, except LockerBaseSecure one. From this issue #26955
Now they are deconstructable only if they're opened/unlocked (like crates)

## Why / Balance
Get stuff "stealthy" in 5 sec? It's OP too much.

## Technical details
Basically revert #24942 of the LockerBase. It's had broken graph node, needs fix in future if you would like to destruct locker ability.

## Media

https://github.com/space-wizards/space-station-14/assets/56667933/58cebb3f-e07f-4aeb-9ef8-a084d2fcc4fd

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Lockers cannot be deconstructed with a screwdriver when locked now.

### CODE REVIEW

**Comment by UbaserB** [comment]
fix the issue, not remove it

**Comment by TokenStyle** [comment]
> fix the issue, not remove it

Make it deconstructable/screwable, but only when it's opened?

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Don't just remove deconstruction. Make it so that you can only deconstruct it if it's unlocked. Similar to crates.

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by Brandon-Huu** [comment]
> Don't just remove deconstruction. Make it so that you can only deconstruct it if it's unlocked. Similar to crates.

well deconstruction is removed now

**Pull request merged**
