### PR TITLE
Turtleneck Fever/Respites

### PR DESCRIPTION
**Pull request by Catdere**
## About the PR
Adds/Respites turtleneck sprites for CMO, HoS, RD, and Syndicate

## Why / Balance
The current sprites of the HoS, RD and Syndie turtleneck did not match the current style of CE and QM's turtleneck. This pr changes and updates the old sprites to fit in more with the others. This also adds a new turtleneck for CMO because they are the only head of a department that did not have one.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Chief Medical Officer's turtleneck.
- tweak: Changed RD, HoS, and Syndicate's turtleneck.

### CODE REVIEW

**Comment by lzk228** [comment]
they're so pretty

**Comment by UbaserB** [comment]
drip

**Comment by EmoGarbage404** [comment]
These are all new-tg style sprites and clash hard, visually. They need to be replaced.

**Comment by Catdere** [comment]
> These are all new-tg style sprites and clash hard, visually. They need to be replaced.

I assume you would prefer a more style like this?
image

**Comment by EmoGarbage404** [comment]
> I assume you would prefer a more style like this? image

i think that looks a lot better (the pants are a bit of a weird color)

**Comment by JoeHammad1844** [comment]
le out of art style but at least with the RD i can wear jackboots and black gloves for the TG drip (dear god I love TG RD drip)

**Comment by Catdere** [comment]
> i think that looks a lot better (the pants are a bit of a weird color)

thank you for the feedback. I'm going to slowly un/TG/ify the sprites.

**Comment by JoeHammad1844** [comment]
> thank you for the feedback. I'm going to slowly un/TG/ify the sprites.

technically we are on the TG sprite base, but its old TG

**Comment by Catdere** [comment]
> technically we are on the TG sprite base, but its old TG
true!! I'm most likely going to use this is my main reference for the new ones. Also I'm going to make CMO's match their hat in color because drip. I'm going to start working now the drip is cooking.

image

**Comment by Catdere** [comment]
> Why close?

going to make a new pr when I remake all the sprites, and they are ready to be shipped out.

**Comment by lzk228** [comment]
you can just upload them to same branch and reopen pr, or you could just set that pr on draft

**Pull request closed without merging**
