### PR TITLE
More feedback for emag recharging

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
The emag now tells you how long it'll take to recharge, making it more obvious that it recharges.
**Screenshots**

max-charges
yellow

**Changelog**

:cl: Rane
- add: The emag now shows how long it has until the next charge when you examine it.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Would this be better as an IItemStatus?

**Comment by Elijahrane** [comment]
I dunno, is that useful if the sprite doesn't change?

**Comment by metalgearsloth** [comment]
What does that have to do with the sprite?

**Comment by Elijahrane** [comment]
I don't know what IItemStatus is or does

**Comment by metalgearsloth** [comment]
It's the control that shows when you have the thing equipped in your hand.

**Comment by Elijahrane** [comment]
I'll have a look

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
