### PR TITLE
blood-red phone

### LINKED ISSUE #22528: Feature Request: Red Phone For Nukie Outpost
## Description

Since ahelping is the only way for them to ask for gimmick stuff, I don't see why the outpost shouldn't start with one. Would just need the admin notif changed from Centcom to Syndicate.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
added it to the nukie planet

## Why / Balance
resolves #22528

## Technical details
no

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
valid

**Comment by UbaserB** [comment]
perfect

**Comment by Emisse** [comment]
i thought they already had a way to contact admins

**Comment by deltanedas** [comment]
fax only goes to centcom i think

**Pull request merged**
