### PR TITLE
Automatic holiday sprites

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

adds a system to allow swapping sprites / doing visuals based on holidays.
it's fairly customizable and i just added in a few for that good ol' christmas spirit.

## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Certain objects around the station will now look different during the festive season.

### CODE REVIEW

**Comment by lzk228** [comment]
wait, sprite changing only for christmas? can i make like for halloween or another holiday?

**Comment by EmoGarbage404** [comment]
> wait, sprite changing only for christmas? can i make like for halloween or another holiday?

yep

**Comment by lzk228** [comment]
but can i make like for christmas and halloween for one entity?

**Comment by EmoGarbage404** [comment]
also yes

**Comment by noctyrnal** [comment]
jolly :D

**Pull request merged**
