### PR TITLE
Clonegenesis

### PR DESCRIPTION
**Pull request by RumiTiger**
## About the PR
A new experimental discipline technology, "Clonogenesis", has been added to the game. This tech costs 50,000 points and is a Tier 3 technology. Unlocking it provides access to everything needed for human cloning, including the medical scanner, cloning pod, and cloning console. The process of constructing the cloning pod has also been made slightly more challenging, now requiring 5 plasma and 5 glass.

## Why / Balance
The cloning machine represents an interesting mechanic, and I believe it’s unfair to deny players the opportunity to interact with it. Currently, seeing a functioning cloning machine even once in 20 rounds is quite rare. It doesn’t seem right that the only ones who can bring the cloning machine to the station are the disposals. Adding this machine to the experimental discipline would significantly increase its popularity. Furthermore, a tier 3 technology priced at 50,000 points seems quite justified for a cloning machine.

## Media
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
**Changelog**
:cl:
- add: A new experimental discipline technology, "Clonogenesis", has been added to the game!
- tweak: Now, in addition to everything else, you'll need 5 glass and 5 plasma to create the cloning pod!

### CODE REVIEW

**Comment by Lyroth001** [comment]
this feels like it should be a civilian tech, since thats where all the other med stuff is, and means we might actually see that T3d at a reasonable timeframe. Although i do agree with Blackern that cloning should probably not be a tech at all

**Comment by Aisu9** [comment]
we will get back on square one : Security taking science hostage and threatening to gib each and every scientist if they don't research cloning

**Comment by Veritius** [comment]
Cloning was made inaccessible through normal means because it just isn't particularly interesting mechanically. Adding a means to get cloning reliably, no matter how difficult, doesn't fix the flaws with cloning that are still extremely present.

**Comment by Aisu9** [comment]
okay hear me out, what if it was a T3 but not present in the research nodes? it is a hidden tech only available from the tech disk printing machine?

**Comment by Djungelskog2** [comment]
> Cloning isn't an interesting mechanic, and this was done originally when cloning was removed from roundstart medical.
> 
> * Round removal is apart of the game, rotting corpses shouldn't be revived (at all, in my opinion, but oppo is a whole different conversation.) so easily.
> * Science will get harassed for not researching cloning because people are just like that.
> * Cloning isn't engaging, you just scan the guy, duplicate 'em, and now they're alive with little to no effort on behalf of medical.
> * This was already removed from research in the past, it wasn't engaging then, it won't be now.

1: I would agree if it werent for the fact that every single murder HAS to be round removal if done by an antag, not just a normal heal-able kill.
2: I just disagree
3: WYCI i guess? there is certainly opportunity to make it far more interesting
4: Refer to point 3

I do think it should be civ tech though

**Comment by RumiTiger** [comment]
> Cloning isn't an interesting mechanic, and this was done originally when cloning was removed from roundstart medical.
> 
> * Round removal is apart of the game, rotting corpses shouldn't be revived (at all, in my opinion, but oppo is a whole different conversation.) so easily.
> * Science will get harassed for not researching cloning because people are just like that.
> * Cloning isn't engaging, you just scan the guy, duplicate 'em, and now they're alive with little to no effort on behalf of medical.
> * This was already removed from research in the past, it wasn't engaging then, it won't be now.

The game already has a substance called Opporozidon, which is significantly easier to obtain than a cloning machine, yet it has almost the same properties. Furthermore, as I understand it, cellular damage is needed in the game only because of the cloning machine.

**Comment by Aisu9** [comment]
> > we will get back on square one : Security taking science hostage and threatening to gib each and every scientist if they don't research cloning
> 
> Has this actually happened or is it just an old anecdote that gets brought up every time cloning is mentioned (sec rulebreaks not withstanding)

it happened twice on salamander last year

**Comment by RumiTiger** [comment]
> okay hear me out, what if it was a T3 but not present in the research nodes? it is a hidden tech only available from the tech disk printing machine?

The issue with this proposal is that the cloning machine could be researched almost at the start of the round. While I understand that it would depend on chance, such an opportunity would still exist

**Comment by Aisu9** [comment]
or the year prior, i believe it was the last straw that caused cloning to be ultimately removed fro mT3

**Comment by Aisu9** [comment]
> > okay hear me out, what if it was a T3 but not present in the research nodes? it is a hidden tech only available from the tech disk printing machine?
> 
> The issue with this proposal is that the cloning machine could be researched almost at the start of the round. While I understand that it would depend on chance, such an opportunity would still exist

the tech disk printing machine print a single crafting research(and not an entire research node) and is completely random, with T2 and T3 techs being less likely to roll

**Comment by ViceEmargo** [comment]
Cloning requires biomass, which is procured through a Biomass Reclaimer machine, or salvage to find chunks of biomass on expedition/VGroid.
If cloning were to come back, you'd need to add the biomass reclaimer to this research as well, as I don't think it makes sense for salvage to be the last piece of the puzzle. (albeit, salvage can proclaim a bunch of biomass compared to grinding a ton of monkeys)

**Comment by RumiTiger** [comment]
> Cloning requires biomass, which is procured through a Biomass Reclaimer machine, or salvage to find chunks of biomass on expedition/VGroid. If cloning were to come back, you'd need to add the biomass reclaimer to this research as well, as I don't think it makes sense for salvage to be the last piece of the puzzle. (albeit, salvage can proclaim a bunch of biomass compared to grinding a ton of monkeys)

As I remember, there is already a research in the game that unlocks the biomass reclaimer

**Comment by RumiTiger** [comment]
> the tech disk printing machine print a single crafting research(and not an entire research node) and is completely random, with T2 and T3 techs being less likely to roll

I still think this is a bad idea, sorry. Scientists should have a clear goal, not a vague task

**Comment by Djungelskog2** [comment]
> > 1: I would agree if it werent for the fact that every single murder HAS to be round removal if done by an antag, not just a normal heal-able kill. 2: I just disagree 3: WYCI i guess? there is certainly opportunity to make it far more interesting 4: Refer to point 3
> 
> Did you just tell me to make the mechanic this pr is implementing interesting instead of telling the person making the pr to do it...?

Anyone who cares enough to fix the problem

**Comment by ViceEmargo** [comment]
> > Cloning requires biomass, which is procured through a Biomass Reclaimer machine, or salvage to find chunks of biomass on expedition/VGroid. If cloning were to come back, you'd need to add the biomass reclaimer to this research as well, as I don't think it makes sense for salvage to be the last piece of the puzzle. (albeit, salvage can proclaim a bunch of biomass compared to grinding a ton of monkeys)
> 
> As I remember, there is already a research in the game that unlocks the biomass reclaimer

Ah, I see it now.
It's a T1 service research, meat manipulation (wow that name)
Thank you for reminding me.

**Comment by Aisu9** [comment]
> > the tech disk printing machine print a single crafting research(and not an entire research node) and is completely random, with T2 and T3 techs being less likely to roll
> 
> I still think this is a bad idea, sorry. Scientists should have a clear goal, not a vague task

and i am adamant that such mechanic should not be available behind and limiting research tier period as it will lead to player animosity toward science.

**Comment by LankLTE** [comment]
There was also a large culture of people saying getting any T3 that wasn’t cloning was just throwing the round / helping antags. I imagine having more options can help this but it’s still a valid concern as cloning solely helps the crew vs things like speed boots or bags of holding which can also help antags if used correctly

**Comment by Aisu9** [comment]
> There was also a large culture of people saying getting any T3 that wasn’t cloning was just throwing the round / helping antags. I imagine having more options can help this but it’s still a valid concern as cloning solely helps the crew vs things like speed boots or bags of holding which can also help antags if used correctly

and if we try to think like them, allowing antagonist to work in department allow them to get more themed gears, cargo traitors can easily get guns, engineering traitors can break wherever using their tools, medbay traitor get a large panel of medicine/topical/poison.
So is cloning really and issue or was the players behaviour was the real problem back then? I for myself do understand that death should be impactful, but it death REALLY impactful when every methods of RR cannot be dodged?
Unless you play as the whinny careful crew with a broom stuck up your backside, denying antags was not really liked last time i played but again, every 5th PR are salt PR made to make Greentext easier without any meaningful or solid arguments(looking at you PR that made escape pods that bring you to CC count you as marooned on station but also count traitor as escaped alive to CC)

**Comment by Kadeo64** [comment]
died 2023 born 2024 welcome back CMO killing RD because he decided to research something fun (speedboots) instead of cloning

**Comment by BramvanZijp** [comment]
This will become an "essential" unlock, meaning everybody will yell at science if it is not picked as the tier 3, killing veriaty with the others. Since this is likely too powerfull to be a tier 2, even if it costs 50k points, I feel like this PR should not be merged. Maybe it could be an ultra rare drop from the tech disk terminal but even then thats iffy.

**Comment by deltanedas** [comment]
cloning is the opposite of an interesting mechanic

**Comment by goet** [comment]
Cloning is not gonna help anyone who is an antag target, they usually gib you. This would just ensure they would do it in a way where you can't be cloned, which would satisfy only those who really enjoy being killed the same way every round. You are only punishing the few antags who are trying to make the round more interesting instead of toolbox bombing a random guy and then not doing anything for another 94 minutes. 

Cloning also completely invalidates the fear of workplace accidents, if your depth 6 artifact burned you to crisp or whatever the paramedic will just put you in the magic respawn machine. The "RP environment" falls apart if people are not afraid to die.

**Comment by Kadeo64** [comment]
y'know, maybe people re-introducing removed content should learn from why the content was removed in the first place. This PR doesn't seem to address any of the issues that t3 cloning had in the past besides the fact that it's not in medical research so it's not an objectively bad tier 3 option

**Comment by ps3moira** [comment]
Pretty much everything that's been said before on why cloning is bad and was removed has been said, and the reasoning in why this PR should happen doesn't change any of these issues for an inherently bad mechanic.

**Comment by Emisse** [comment]
cloning

**Comment by EthanQix** [comment]
Cloning was removed from medbay (barring jackpot loot from salv) for good reasons. Reintroducing it with the "balance" that the cloning pod now requires some more (trivially obtainable) materials doesn't address any of said reasons. This PR should be closed.

**Comment by Aisu9** [comment]
> Cloning was removed from medbay (barring jackpot loot from salv) for good reasons. Reintroducing it with the "balance" that the cloning pod now requires some more (trivially obtainable) materials doesn't address any of said reasons. This PR should be closed.

where i do agree it could be a PH piece of content while waiting for surgery to come in and allow brain transplantation, ANY undodgeable RR methods should ALSO be removed

**Comment by Aisu9** [comment]
> > where i do agree it could be a PH piece of content while waiting for surgery to come in and allow brain transplantation, ANY undodgeable RR methods should ALSO be removed
> 
> Round removal is part of the game. Sometimes you die forever and you can't do anything about it. That's why rounds are only 1-2 hours long, and ghost roles exist. I genuinely feel we need MORE round removal in the game so people get used to it. People are too accustomed to being revived no matter what and always mald in OOC that they didn't survive the things meant to kill them. Syndies round removing is part of the game. Dragons round removing is part of the game. Immovable rods exist and are part of the game. Oftentimes, the only thing you can do is try again next time. Losing is fun, after all.

i NEVER said RR was bad, i only said that UNDODGEABLE RR should not be part of the game, yeah it should happen but it SHOULD NOT be a sweaty pro-gamer move neither an unskilled manipulation like moving the fucking recycler on top of disposal chute, you wanna RR someone put in some effort!

**Comment by Aisu9** [comment]
also ghost role exist? are you talking about the 7+ mouses that instantly get murdered on sight by anyone?
or the botany trays or vending machine? i sure love having nothing to do than yelling on passerby or having the botanist growing weed in my tray
or the minibots? that NEVER get picked during conscious event
or positronic brains? to have the crew yell at you and treat you worse than a door opener.
the game barely have any content because contributors dont care about what the job should be and continue mergin SS13 slop again and again, thought they were supposed to be a focus on job content? the only final-vision job content i saw since i started playing was the few addition and changes to to science. 
botany? barely anything but additional mutation when the system as a whole need a reactor
Chef and cooking? same it need a complete overall
Medical and Chemistry? someone is working on it, someone singular so it's bound to take a while
Meanwhile the contributors? keep pumping antagonists and other content that doesn't bring any department closer to their 1.0 version

**Comment by Killerqu00** [comment]
> also ghost role exist? are you talking about the 7+ mouses that instantly get murdered on sight by anyone? or the botany trays or vending machine? i sure love having nothing to do than yelling on passerby or having the botanist growing weed in my tray or the minibots? that NEVER get picked during conscious event or positronic brains? to have the crew yell at you and treat you worse than a door opener. the game barely have any content because contributors dont care about what the job should be and continue mergin SS13 slop again and again, thought they were supposed to be a focus on job content? the only final-vision job content i saw since i started playing was the few addition and changes to to science. botany? barely anything but additional mutation when the system as a whole need a reactor Chef and cooking? same it need a complete overall Medical and Chemistry? someone is working on it, someone singular so it's bound to take a while Meanwhile the contributors? keep pumping antagonists and other content that doesn't bring any department closer to their 1.0 version

these damn contributors (which are basically just random people implementing stuff for the game for free) coding what they want to see in the game! So evil!

about cloning: I am personally all for cloning, as long as it's not just a T3 research and rather a rare tech disk salvage can find; cloning shouldn't count as the same person for the sake of antagonist objectives (so if you killed your target and it gets cloned, you still succeeded).
using ghost roles as an argument against cloning isn't sufficient: ghost roles are very underwhelming at the moment, most of them have practically 0 roleplay/gameplay opportunities, spectating a round might be unironically more engaging and fun.

**Comment by PJB3005** [comment]
@Aisu9 please be respectful, ranting about contributors is not appropriate.

**Comment by RumiTiger** [comment]
Thank you all for your opinions and suggestions!

I've reconsidered my proposal and identified two significant issues:
- The limited and unengaging gameplay of the cloning machine (yes, I’ve changed my mind)
- The cloning machine overshadows the other research disciplines

Once again, thank you all!

**Pull request closed without merging**
