### PR TITLE
Quartermaster Promotion

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-qm can no longer be antag

reason i made this pr: antag qm is stupid

### CODE REVIEW

**Comment by Fishfish458** [comment]
I'm ok with QM not being antag but I don't think they should be command access.

**Comment by Emisse** [comment]
ok i dont really care either way ill just remove it

**Comment by Fishfish458** [comment]
> ok i dont really care either way ill just remove it

I'm not really the decider either, just voicing opinion.

**Comment by Peptide90** [comment]
Title mix up? ;) 

QM being antag makes sense because they're like a lowly dock worker, easily corruptible way onto the station.

I'm easy either way but I don't think they should be a head and thus not much point protecting their antag status. Just my 2c

**Comment by Emisse** [comment]
as an antag they spawn with a high risk item and can just endlessly buy weapons all round with no immediate repercussions. its not fun and i feel like people are kinda tired of it

**Comment by Saakra** [comment]
Jokes on you, antag or not, they buy weapons anyways. And so do the random cargo lads. Everytime I'm QM, I have to drag every ordering computer into my office to stop that from happening every round

**Comment by Peptide90** [comment]
> as an antag they spawn with a high risk item and can just endlessly buy weapons all round with no immediate repercussions. its not fun and i feel like people are kinda tired of it

Fair enough, HoP and Captain should be overseeing the orders and cargo techs reporting them (MRP).

We do need conditions to make sure if QM is antag nobody gets their stuff as objectives. Otherwise personally I think QM antag in 13 is fun, things like cult and rev make sense for them.

**Comment by BlitzGunner225** [comment]
You know what’s fun 
Causing enough chaos to steal the teleporting and ordering computer 
That requires actual strategy and skill
What’s not fun is syndies getting unlimited guns roundstart 
I think cargo should in general get syndie nerfs. For starters only QM has ordering access and there will also be a spare QM card. You can still convince the qm to order guns or find a way to get access so it just makes the strat harder.

**Comment by Fishfish458** [comment]
> You know what’s fun Causing enough chaos to steal the teleporting and ordering computer That requires actual strategy and skill What’s not fun is syndies getting unlimited guns roundstart I think cargo should in general get syndie nerfs. For starters only QM has ordering access and there will also be a spare QM card. You can still convince the qm to order guns or find a way to get access so it just makes the strat harder.

Most quartermasters don't give a fuck and will order an emitter and guns regardless of their own status most rounds. Removing syndie from QM is one thing but I think the rest is gonna have to be fixed with MRP.

**Comment by BlitzGunner225** [comment]
> > You know what’s fun Causing enough chaos to steal the teleporting and ordering computer That requires actual strategy and skill What’s not fun is syndies getting unlimited guns roundstart I think cargo should in general get syndie nerfs. For starters only QM has ordering access and there will also be a spare QM card. You can still convince the qm to order guns or find a way to get access so it just makes the strat harder.
> 
> Most quartermasters don't give a fuck and will order an emitter and guns regardless of their own status most rounds. Removing syndie from QM is one thing but I think the rest is gonna have to be fixed with MRP.

If they’re breaking open crates then just arrest em all

**Comment by Fishfish458** [comment]
> If they’re breaking open crates then just arrest em all

Yeah, it's kind of the constant battle of cargo vs sec, at what point is it validated to raid cargo because they're opening boxes they shouldn't be. It's not really outlined all too well when cargo is doing things they shouldn't like buying an emitter, though another solution could also be departmental security to keep tabs.

**Comment by Peptide90** [comment]
Go old school and put ordering consoles that are department specific so engi have to request an emitter or sec have to order guns.

Kind of half joking but maybe some stuff should be restricted and need higher approval OR we leave everything as is as it's an MRP issue and currently LRP has no issues with this behaviour.

**Comment by Emisse** [comment]
i think making qm non antag would reduce the prevalence of this happening quite a bit, obviously i have no data to support this.

**Comment by Kromabae** [comment]
> > If they’re breaking open crates then just arrest em all
> 
> Yeah, it's kind of the constant battle of cargo vs sec, at what point is it validated to raid cargo because they're opening boxes they shouldn't be. It's not really outlined all too well when cargo is doing things they shouldn't like buying an emitter, though another solution could also be departmental security to keep tabs.

a valid time to raid cargo would be if there's sussy sounds like an emitter coming from there, besides captain should pay random visits to places every now and  then to check up on every department. A lazy cap shows.

**Comment by HoofedEar** [comment]
After reading all the comments people have made, plus the arguments made in the QM issue, it looks like simply removing QM's ability to be antag is a perfectly acceptable solution for now.

Any QM ordering an emitter and busting open crates (should) count as self antag, due to there never being a reason for Cargo to do this. (Sec should be called to have them take care of whoever is breaking in, or if the HoS deems in necessary, provide Carog with nonlethals themselves.) A QM who sees one of their Techs do this should report them to Sec immediately.

I understand that in LRP we get away with not doing a lot of the things we should, but a good way to limit that behavior is to prevent QM from being antag at all so that the onus is on them to report any suspicious behavior, no matter what. If Sec hears an emitter coming from Cargo, that means it's time to raid Cargo because all of the Techs are antags and probably spaced their QM. (lol)

**Comment by TimrodDX** [comment]
I think this is a bad idea for several reasons.

> I understand that in LRP we get away with not doing a lot of the things we should, but a good way to limit that behavior is to prevent QM from being antag at all so that the onus is on them to report any suspicious behavior, no matter what.

What you're assuming there is that the QM is going to be obligated to report anything at all. There's a huge difference between "this role can't be an antag" and "this role is obligated to report to security", which is something that simply doesn't exist. Without the cargo shuttle being in and having an ability to send back unwanted crates, there's not really anything I can do as QM to stop anyone ordering guns short of dismantling the cargo console and spacing it.

> Any QM ordering an emitter and busting open crates (should) count as self antag, due to there never being a reason for Cargo to do this.

No. This is a horrible idea. The QM needs to be able to react, and needs to have discretion. As an example, when I play QM I often order lasers for Salvage to make it easier to deal with the carp swarms in the salvage wrecks, because as it is the Salvage team is horribly underequipped to handle some of those. Should I then be banned for self-antag? 

Doing this would absolutely kill emergent gameplay in Cargo, which is what SS13 is all about. 

> as an antag they spawn with a high risk item and can just endlessly buy weapons all round with no immediate repercussions. its not fun and i feel like people are kinda tired of it

The easier solution here is to remove the supply board from the list of traitor objectives, and buff the other traitor weapons. Cargo traitors order guns because the ones in the uplink suck. This is why I told people not to nerf the emag, because if the traitors don't have access to the tools they need they're going to use the ones they have. 

This is the equivalent of saying we should prevent Chemistry from being traitors because they have access to lexorin smoke grenades, or preventing Engineers from being antags because they have access to the singularity. What you have to do is remove the incentive to order guns, rather than simply banning anyone who does.

**Comment by freeman2651** [comment]
I don't think QM should be a head role but I agree with them not being an antagonist. He is in charge of a whole department by itself but traditionally he's not really considered a head of staff. The disconnect is that his role is unique in that he's a supervisor of other people in his chain of command, but he's not a head of staff. This confuses people because they think "in charge of other people = head of staff", and nowhere else in the station (besides maybe warden, to an extent) has this supervisory role without the Head of Staff string attached.

It will _probably_ reduce the amount of secession and general non-compliance from cargo, but I do think one of the pervasive issues that always happens with cargo is they have pretty decent agency over both ordering dangerous equipment and methods to open that equipment aren't terribly dangerous or difficult to get. To boot, everyone generally wants access to a gun because it is a better chance to win at any conflict that might arise, so the QM is not exactly discouraged from getting in on the gun crates because he doesn't really get anything from reporting it to security (even if they do come) and doing so anyways would probably earn the animosity of anyone he snitched on. Plus with salvage being more dangerous, I am typically more apt to give cargo some leeway with guns since it makes their job significantly safer.

I do think 100% that the quartermaster being an antagonist is a no-no since he just throws around so much influence and makes cargo significantly harder to police since there is not a single person that can be trusted in the department.

**Comment by Peptide90** [comment]
Have to agree with TImrod on this one. QM is a good traitor role.  However the part on self antag is iffy, if QM orders lasers for salvage then it's up to security to open that crate for them. If security deem it too much of a risk to arm salvage then that's totally acceptable to deny that.

Removing the cargo related objectives from traitor is a good idea, we can easily add other objectives instead OR as I mentioned, make that objective not role if you have a QM traitor.

What happens when I add the salvage foreman role (salvage supervisor, NOT head, like QM). They don't have any related objectives but they sure as hell should remain a member of the crew that can easily be corrupted, which is what it stems from. Heads not being antag is because it would be too easy and for lore reasons, QM is not a head so why validate that.

Also, I know it was mentioned that having discussions on Git isn't exactly ideal, maybe we should consult on either the forums on issues like this or in a discord thread and create said PR / issue when we're at a point. I know why this PR was made and like a lot of PRs, often you don't expect it to turn into drama but it can happen.

**Comment by mirrorcult** [comment]
we can try this and see if we want to add command access or anything after this, or if this is enough

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
