### PR TITLE
Adds Buy Before Condition

### PR DESCRIPTION
**Pull request by keronshb**
## About the PR

Adds a store condition so that it requires one or more purchases of a different listing before unlocking another listing.

## Why / Balance

It's a good concept + needed for Wizard spellbook upgrades.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Media JUST for demo purposes (you do not need to buy an esword to unlock dsword).

https://github.com/space-wizards/space-station-14/assets/54602815/605668a2-9c7b-482f-ae54-36b899c51cb4

## Breaking changes

I don't think is breaking but I moved the ID field from the Prototype to Data so this could be possible.

**Changelog**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
This should probably indicate it locks other stuff, like the locked one is always in UI but the button is greyed out and on hover says "requires XYZ" or something.

**Comment by LankLTE** [comment]
Probably doesn’t need a CL since it isn’t applied to anything and players don’t need to know about a system being added

**Comment by Clostyandr** [comment]
> > ugh, so... i need to spend TC to useless thing, to buy what i need?
> 
> This is for wizard.

Oh, i got it. This not gonna be used for traitors and nukeOps, but gonna be used for wizard? If i'm right, that's cool!

**Comment by keronshb** [comment]
> > > ugh, so... i need to spend TC to useless thing, to buy what i need?
> > 
> > 
> > This is for wizard.
> 
> Oh, i got it. This not gonna be used for traitors and nukeOps, but gonna be used for wizard? If i'm right, that's cool!

Wizard and anything relevant.

**Comment by EmoGarbage404** [comment]
i obliterated your CL because it was CRINGE (did not abide by the changelog standards for relevancy)

**Pull request merged**
