### PR TITLE
allow toy executions

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
foamblade foam cutlass plushies etc can now be used to execute people

## Why / Balance
cause of death: among us

## Technical details
subscriptions are on MeleeWeapon now and it checks for Sharp or having no damage

## Media

maybe could use custom messages for some items but it work

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
Changelog was not an Impostor.
2 Impostors remain.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
1. this allows a shit ton of weapons to be able to execute due to not requiring sharp component anymore
2. i don't get why this should be functionality at all.

**Comment by deltanedas** [comment]
> this allows a shit ton of weapons to be able to execute due to not requiring sharp component anymore

it doesnt, it requires it either be sharp or have no damage. bats cant execute

> i don't get why this should be functionality at all.

pirate execution with foam cutlass arrrr

**Comment by metalgearsloth** [comment]
No changes to execution until https://github.com/space-wizards/space-station-14/issues/24180 is done

**Comment by Veritius** [comment]
not allowing no-damage weapons to execute was intentional though
it kind of removes a little bit of the drama, which is the whole point
executions are meant to be dramatic, not funny

**Comment by UbaserB** [comment]
This doesn't make sense to me.

**Comment by deltanedas** [comment]
you can execute with a cap gun, why so serious

**Pull request closed without merging**
