### PR TITLE
-Make Rat Kings employable, slightly more useful, and more neutral

### PR DESCRIPTION
**Pull request by superjj18**
## About the PR

Rat kings can now be given an ID/PDA and a comms headset by crew.  Despite not needing to use doors, they can use their ID access to open doors for others.  They have also been granted the ability to pull things.  Changed Rat King's role rules from "You are an antagonist" to "You have no allegiance".

## Why / Balance
I have asked staff on a couple occasions about if the Rat King is an antag or are they more of a neutral party that can be hired/adopted like a skeleton, and the response was always inconclusive.  This change mechanically allows the Rat King to play as a neutral character similar to a skeleton or law-free borg, as well as to be recognized as crew for both borgs and space law purposes.  The Rat King cannot equip anything on his own so he would need likely a crew member's help, and I'd rather have a Rat King with a comms headset than Punpun with one.  Pulling has been given so that they may better interact roleplay wise, from saving a friendly crewmate to dragging a victim into their lair.

All these changes, including the change in Rat Kings rules from "You are an antagonist" to "You make da roolz" allow for a larger variety of roleplay situations with our rare rat abomination and greater player agency.  None of these changes are a significant buff to the Rat King.  Nothing else needs to change rule-wise as players will still be free to react to Rat King as they have, or explore friendlier options without compromising the core gameplay of the role("AAAAH A RAT").

## Technical details
Added a bunch of components to regalrat.yml, created a inventory template for Rat King, and modified the wording of the Rat King role rules.

## Media
image
image
image

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- tweak: Rat Kings can be given an ID, Comms, can pull things, and are now truly neutral!

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
your changelog's broken

**Comment by UbaserB** [comment]
... they can already go underneath doors. What would getting a PDA even do for them?

**Comment by Hanzdegloker** [comment]
> ... they can already go underneath doors. What would getting a PDA even do for them?

"Borg, murder that rat, they are not crew"

**Comment by superjj18** [comment]
> ... they can already go underneath doors. What would getting a PDA even do for them?

Yes as pointed out by Hanz, as well as stated by the "About the PR" section, it is primarily to give command/crew the option to declare Rat Kings crew in the eyes of borgs and space law, but it also comes with the added benefit of allowing the Rat King to open doors for others similar to how  a borg can use their innate AA to open restricted doors for people(obviously the Rat King would need to be given that access by someone else as they cannot equip items on their own).

This is entirely optional depending on how the Rat King, Command, and Crew interact with each other.

**Comment by FairlySadPanda** [comment]
Any role that isn't supposed to be a default antag needs the ability to hold an ID or a PDA atm to avoid crew shithousery with crew/not-crew given crewsimov and similar problems. I did the same for scugs and they're a joke PR for one day.

**Comment by superjj18** [comment]
image
I have finally found out how to add alternate sprites per species!  This draft can finally be completed once I get that set up(i have to edit a handful of sprites)

**Comment by Dutch-VanDerLinde** [comment]
> image
> 
> I have finally found out how to add alternate sprites per species!  This draft can finally be completed once I get that set up(i have to edit a handful of sprites)

Why do that when you can just change the offset like borgs do for hats?

**Comment by superjj18** [comment]
> > image
> > I have finally found out how to add alternate sprites per species!  This draft can finally be completed once I get that set up(i have to edit a handful of sprites)
> 
> Why do that when you can just change the offset like borgs do for hats?

because I do not know how and I have been begging in howdoicode for a few days now and this is the first working solution I have found

**Comment by superjj18** [comment]
Ah... sadness, I see what your referring to now.  I've wasted a bunch of time but at least I only resprited like... 12 sprites thus far.  I wish I found that sooner, I even checked the silicon.yml but its actually in the inventory templates. 

Edit actually now I am not sure, because it needs to be offset depending on the direction since it is not centered like the borg hat would be

**Comment by Emisse** [comment]
im fine with this but adding the sprite changes for every headset is kind of unhinged, we have? displacement mapping support either soon or rn which this should probably use

**Comment by beck-thompson** [comment]
I think this is a good idea. A lot of times I see rat kings try to be nice but its REALLY hard make it "official" and this does a lot in healing that.

**Comment by superjj18** [comment]
> im fine with this but adding the sprite changes for every headset is kind of unhinged, we have? displacement mapping support either soon or rn which this should probably use

The only other way I saw personally was using offset in the inventory template like with borgs, however unlike borgs ratking's sprite is not really centered, so I did what was done for Hammy's cosmetics.  I will say from what I've seen so far it works flawlessly despite being a pain in the ass to gimp the pixel art precisely, but I will monitor #26709 and see if it can be applied to this PR.

**Comment by The-Best-Nerd** [comment]
tbh not fond of this. rat kings have the ability to make armies and whatnot - various "powers" and a sort of ungovernability in terms of rules status that just lets them go on a murder spree when they don't feel like playing nice anymore.

**Comment by superjj18** [comment]
> tbh not fond of this. rat kings have the ability to make armies and whatnot - various "powers" and a sort of ungovernability in terms of rules status that just lets them go on a murder spree when they don't feel like playing nice anymore.

This change does not change the fact that ratkings are completely valid to KOS, it just gives crew/command a friendlier route for dealing with them should they choose.  I never said hiring the ratking was a good idea, merely that it is an option :trollface:

**Comment by mirrorcult** [comment]
don't think this should get merged without being displacement mapped

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by superjj18** [comment]
Reopen(but I still need to figure out the displacement mapping stuff which I will get to eventually)

**Comment by GroggleG** [comment]
interesting, if we do this honestly give those skavens a hand like a monkey or possibly just a tail.

**Comment by superjj18** [comment]
> interesting, if we do this honestly give those skavens a hand like a monkey or possibly just a tail.

The reason against that is then they would be able to use weapons and guns

**Comment by GroggleG** [comment]
> > interesting, if we do this honestly give those skavens a hand like a monkey or possibly just a tail.
> 
> The reason against that is then they would be able to use weapons and guns

Easily side stepped by the typical "hands are too big!" or a similar to ninjas inabillity, this PR is to make more useful, yes?

**Comment by superjj18** [comment]
I suppose it would be nice to allow them to put on their own items without needing someone else.  There's just a lot of edge cases I'd need to think about to not make things too crazy

**Comment by GroggleG** [comment]
Quality over quantity, rather see it later than sooner if it works better in practice

**Comment by Brandon-Huu** [comment]
Is this still being worked on?

**Comment by superjj18** [comment]
> Is this still being worked on?

It's always in the back of my mind, I've just been focusing on other things(like looking for a job).  I haven't played ss14 in a bit but ill give it a quick looksee and see how easy it is to convert this to the displacement maps(I wonder if it would be easier just to start over in a new branch)

**Comment by DieselMohawk** [comment]
I like the idea since Rat Kings are now Neutral, which means they can be evil rats or crew rats. I would like to see this work out.

**Comment by superjj18** [comment]
ugh, I haven't worked in this code base for a few months and displacement maps seem kinda confusing, if anyone wants to adopt this PR go for it

**Comment by Brandon-Huu** [comment]
> ugh, I haven't worked in this code base for a few months and displacement maps seem kinda confusing, if anyone wants to adopt this PR go for it

Why are displacement maps necessary?

**Comment by superjj18** [comment]
> > ugh, I haven't worked in this code base for a few months and displacement maps seem kinda confusing, if anyone wants to adopt this PR go for it
> 
> Why are displacement maps necessary?

this PR was started before displacement maps were implemented, you can read the comments above, specifically the ones from Emisse and Mirrorcult about using displacement instead of replacing the images which is why it was held up by the feature freeze.  Also being like 800 commits out of date I did notice a couple of conflicts including the relatively new hand UI.

**Comment by Brandon-Huu** [comment]
> > > ugh, I haven't worked in this code base for a few months and displacement maps seem kinda confusing, if anyone wants to adopt this PR go for it
> > 
> > 
> > Why are displacement maps necessary?
> 
> this PR was started before displacement maps were implemented, you can read the comments above, specifically the ones from Emisse and Mirrorcult about using displacement instead of replacing the images which is why it was held up by the feature freeze. Also being like 800 commits out of date I did notice a couple of conflicts including the relatively new hand UI.

Could the headset and ID be split into separate PRs?
I'm assuming the ID part doesn't require displacement maps?

**Comment by superjj18** [comment]
> > > > ugh, I haven't worked in this code base for a few months and displacement maps seem kinda confusing, if anyone wants to adopt this PR go for it
> > > 
> > > 
> > > Why are displacement maps necessary?
> > 
> > 
> > this PR was started before displacement maps were implemented, you can read the comments above, specifically the ones from Emisse and Mirrorcult about using displacement instead of replacing the images which is why it was held up by the feature freeze. Also being like 800 commits out of date I did notice a couple of conflicts including the relatively new hand UI.
> 
> Could the headset and ID be split into separate PRs? I'm assuming the ID part doesn't require displacement maps?

Found some time now, gonna try and do this suggestion today.  ID I think just naturally works without any displacement changes

**Comment by superjj18** [comment]
recreated this with just the ID changes in #30381 closing this branch

**Pull request closed without merging**
