### PR TITLE
Official CentCom Costume to uplink

### PR DESCRIPTION
**Pull request by FilinSep**
## About the PR
adding:
1. Official Centcom Costume Bundle to Uplink

## Why / Balance
1. More variety for antagonists
2. SS13

## Media

image

**Changelog**
under

### CODE REVIEW

**Comment by Holinka4ever** [comment]
Isnt like chameleon suit can turn into centcom official?

**Comment by CatMagic1** [comment]
This got removed

https://github.com/space-wizards/space-station-14/pull/6895

**Comment by JoeHammad1844** [comment]
how about a ghost role that has a low chance of spawning for a REAL centcom official to come to the station and do an audit, would be a good roleplay opportunity and a reason for this to exist

**Comment by JoeHammad1844** [comment]
also 25TC is too much, make it 2TC

**Comment by CatMagic1** [comment]
>how about a ghost role that has a low chance of spawning for a REAL centcom official to come to the station and do an audit, would be a good roleplay opportunity and a reason for this to exist

yeah, that was the original problem
I think everyone is fine with some kind of cc rep, inspector, assistant kind of event but it's just a wyci

**Comment by FilinSep** [comment]
> also 25TC is too much, make it 2TC

it's too imbalance

**Comment by deltanedas** [comment]
chameleon can do this and isnt 25tc

also this still needs a way to avoid being metagamed as per the removal pr discussion

**Comment by CatMagic1** [comment]
The solution is just to add the centcomm event. So players believe it both ic and ooc, removing the risk of metagaming.

**Comment by JoeHammad1844** [comment]
> > also 25TC is too much, make it 2TC
> 
> it's too imbalance

whats worth more? clothes? or a full auto shotgun?

**Comment by FilinSep** [comment]
> > > also 25TC is too much, make it 2TC
> > 
> > 
> > it's too imbalance
> 
> whats worth more? clothes? or a full auto shotgun?

trust

**Comment by JoeHammad1844** [comment]
compelling argument

**Comment by LankLTE** [comment]
Chameleon clothes already do this job and the costume was removed for good reasons that haven't been addressed.

**Pull request closed without merging**
