### PR TITLE
anonymize salvage wrecks

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

changes the salv magnet ui to not show the name of salvage wrecks.

## Why / Balance

Salvage wrecks have always had the issue of just being memorized and then ran through for optimal loot. While this will hopefully get better with more robust spawners and other things, being able to just pick-and-choose the size of the wreck removes any consideration of risk from going to them. 

Making them anonymous increases the risk which feels reasonable considering they are meant to be the more populated and plentiful option for magnet salvaging.

## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: You can no longer see wreck names in the salvage magnet UI.

### CODE REVIEW

**Comment by deltanedas** [comment]
deltav has a size small/medium/large for every wreck that gets shown instead, gives you a little information but not enough to metagame specific wrecks loot. would be worth considering that instead of just removing it entirely

**Comment by EmoGarbage404** [comment]
> deltav has a size small/medium/large for every wreck that gets shown instead, gives you a little information but not enough to metagame specific wrecks loot. would be worth considering that instead of just removing it entirely

my plan is to implement procgen space junk and then balance wrecks to be rarer, more dangerous, and more valuable. The size also doesn't seem interesting to me since there isn't ever really a reason to go with anything less than the largest size available.

**Comment by deltanedas** [comment]
if there are only 1 or 2 salvagers you might want to go for smaller wrecks than a giant one you wont be armed to deal with or wont have enough time to loot all

**Comment by EthanQix** [comment]
If salv is getting 3 random wrecks to choose from with no extra info, might as well give them only one since their choice becomes meaningless...

**Comment by engineer-pearl** [comment]
Small is also good if you have a trainee on board.

**Comment by EmoGarbage404** [comment]
> if there are only 1 or 2 salvagers you might want to go for smaller wrecks than a giant one you wont be armed to deal with or wont have enough time to loot all

fair enough. it's not very hard to do so i guess i'll go implement it.

**Comment by EmoGarbage404** [comment]
image

now displays the size of the wreck

**Pull request merged**
