### PR TITLE
Fix food trash not spawning

### LINKED ISSUE #20463: Food Containers Disappearing After Being Used
## Description

Found three instances of this:

Getmore Chocolate Corp: Except for the chocolate bar wrapper, every other snack container in these machines leaves no trash once completely eaten.
Bowls: Ate french onion soup that also disappeared.
Gatfruits: The revolver doesn't spawn after eating.

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

Fixes #20463
## Why / Balance

After the recent food refactor which renamed the `Trash` variable to `TrashPrototype`, the `TrashPrototype` variable in `FoodComponent.cs` no longer pointed to the correct yml data field
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Trash spawns correctly after food is eaten.

### CODE REVIEW

**Comment by deltanedas** [comment]
dont change the yml change the field to Trash so datafield automatic name is correct

**Comment by Doru991** [comment]
Oh so the change in FoodComponent.cs was accidental?

**Comment by deltanedas** [comment]
yes a sneaky field name that didnt match its datafield tag

**Comment by Doru991** [comment]
Ight, I thought the datafield was supposed to be changed to be more intuitive/explicit or something, anyway changed the .cs to match the .yml's instead and now the clown can live happily ever after having banana peels again

**Pull request merged**
