### PR TITLE
Fix female clothing mask

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Closes https://github.com/space-wizards/space-station-14/issues/10139
**Screenshots**

image

**Changelog**

:cl: Rane
- fix: Fixed the sprite modifications for female humanoids jumpsuit slot clothes.

### CODE REVIEW

**Comment by Elijahrane** [comment]
ok tests are making me insane amogus, all of these errors are unrelated

**Comment by Elijahrane** [comment]
I removed StencilClear because it doesn't seem to actually do anything and the shader on the jumpsuit mapped layer because it just loads as a null string

**Comment by PJB3005** [comment]
Stencil clear is necessary because otherwise a dirty stencil buffer (from, say, overlapping humans) might cause problems.

**Comment by Elijahrane** [comment]
> Stencil clear is necessary because otherwise a dirty stencil buffer (from, say, overlapping humans) might cause problems.

alright, it's a bit odd it was on the left leg though

**Comment by PJB3005** [comment]
> alright, it's a bit odd it was on the left leg though

Wait what?

**Comment by Elijahrane** [comment]
> > alright, it's a bit odd it was on the left leg though
> 
> Wait what?

image

**Comment by PJB3005** [comment]
That uh, definitely aint right.

**Comment by Elijahrane** [comment]
> That uh, definitely aint right.

would deleting the sprite and state fix it? can a layer just be a shader?

**Comment by PJB3005** [comment]
Ok actually I checked the original commit and this is "fine": https://github.com/space-wizards/space-station-14/commit/9beb7e48d452c75328c3733fb4a457d4530bee86#diff-469d81b5e2283cca1e21409f96e45130e147da9114e74d4855846ece383c1ec1R62

The leg texture is never actually loaded because the shader just always writes `vec4(0.0)` as color. This is really confusing though and I should definitely have left a comment two years ago.

**Comment by Elijahrane** [comment]
mmmm, 1 remaining bug where the stencil isn't applied on first load, might take a bit to solve that

**Comment by Elijahrane** [comment]
image
it's trying to render before the main screen is loaded which might have something to do with it

**Comment by Elijahrane** [comment]
3 hours of debugging later I am 80% confident the bug is sprite.LayerSetVisible being wonky. If you set the stencil mask to visible by default in yaml all bugs go away. If you make a test where you make everything on your entity invis before the main screen loads, then it seems your client didn't get the memo you can still see everything until it's """fixed"""

**Pull request merged**
