### PR TITLE
Make the trading outpost stationary

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

image
image

## Why / Balance

Quit moving it nerds.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Is this using the regular or the unpowered one?

**Comment by Emisse** [comment]
image

**Comment by EmoGarbage404** [comment]
thank you brave soldier i was not going to read through 500 lines of yaml

**Comment by regenpower** [comment]
this will severely affect the economy

**Comment by Golinth** [comment]
> this will severely affect the economy

Good

**Comment by DieselMohawk** [comment]
Alrighty guys, time to move the station to the ATS instead.

**Pull request merged**
