### PR TITLE
Origin Update 3.0

### PR DESCRIPTION
**Pull request by brainfood1183**
Origin-0

Origin has been updated. Here is a list of changes.

- Science shuttle was removed from south of science. (moony requested change).
- Science genetics was removed from the south of science. (a genetics can be added when we have gameplay incoming for it). (moony requested change).
- EVA suits removed from maintenance and science. (moony requested change).
- Surgery and tools removed from robotics (operating table and some non lethal tools were added back in).
- Machette and combat knife spawns were removed. (moony requested change).
- The drug den (gamer room) north of medical was removed and replaced with an arcade. (moony requested change but not specifically replacement).
- Science uranium generators were removed, science can no longer go off grid. (moony requested change).
- An analyzer was removed from artifacts lab (now only one but space to place another).
- Tools removed from the CE office (has enough tools). (checkraze requested change).
- The armory loadout was altered as well as the armory layout. (moony requested change).
- Maintenance tunnels added to the north and south sides of science. (moony requested change).
- Many walls have changed between rwalls and solid walls depending on their ingame purpose. (checkraze requested change).
- Many windows have changed between reinforced window and normal window depending on their ingame purpose. (checkraze requested change).
- Many of the head rooms now have switches and shutters to help syndies and heads in different situations. (checkraze requested change).
- The kitchen now has shutters and can close up shop. (checkraze requested change).
- The icecream parlor now has shutters and can close up shop.
- Botany now has shutters and can close up shop.
- The donk cafe was improved.
- The doors on the syndie shuttle were changed from vault doors to external doors (stealth requested change).
- The protolathe removed from engineering (checkraze requested change).
- The rd server and points in science moved to a new secure location. (checkraze requested change).
- Telecomms now has rwalls  (checkraze requested change).
- The maint cloner removed  (moony requested change).
- Chem stuff removed from virology  (moony requested change).
- Open prison made more secure.
- Fixed hole in wall near detective office.
- Most counters replaced with reinforced tables  (checkraze requested change).
- Some maint loot spawners were reduced specficially those adding resources  (moony requested change).
- Drone room replaced with a sec checkpoint. (moony requested change but not specifically a replacement).
- High level parts removed from maintenance  (checkraze requested change).
- Ore processor now in wall between salv and cargo. (checkraze requested change).
- A few lights added to dark areas of station that should not be dark such as north part of botany (stealth requested change).
- RTVs removed from robotics. (moony requested change).
- The miasma room removed. (moony requested change).
- baby singulo has been removed. (moony requested change).
- Solar arrays have had an increase in connectivity to the main station to reduce the ease of sabotage. (mervill requested change).
- Grav is now separate from the rest of the room it resides in making it a little harder to sabotage (mervill requested change).
- Courser shuttle by checkraze now selected as the default emergency shuttle for origin.
- Altered the catwalk north of xenoarch room, this modification gives more room for the new emergency shuttle.
- Moved the golden toolbox to the bridge.
- Added a zebra scarf to theatre.
- Reworked robotics a little (east side of the map).
- Added Exosuit fabricator to robotics.
- Removed the shuttle console circuit board from the CE's office.
- Added the map back into the station rotation loop for the server.
- Removed the RPG from the armory (cosmos requested change).
- Removed engi-vends from youtool rooms.
- Changed all department all access doors to all access glass airlocks to make it more clear which doors general public have acccess to for example the entrance doors to medical are no longer medical all access airlock but all access glass airlocks.
- Added Hamlet spawner to bridge.
- Added a geiger counter to engi.
- Added fax machines.
- Added intercoms.
- Modified bar a little.
- Modified icecream parlor a little.
- Added some christmas decorations (these were recently removed again since christmas is over).
- R&D had the insulated gloves, 2 bars of gold and grinder removed (checkraze requested change).
- Security rechargers removed from science and cargo (checkraze requested change).
- Pinpointer added to the vault  (checkraze requested change).
- Lattice added to space outside waste disposal conveyor (checkraze requested change).
- Firelocks added between salv and cargo (checkraze requested change).
- Some maint loot changes  (emisse requested change).
- Perma brig now has mv electrified windows, all wall are rwalls (emisse requested change).
- Bar now has a shutter over its windoor (emisse requested change).
- More crowbars and some emergency suits added to arrivals shuttle (checkraze requested change).
- RTGs removed from engineering  (emisse requested change).
- Engineering layout  was modified to better utilize space  (emisse requested change).
- Arrival shuttle generators changed (emisse requested change).
- Grav now has an access door (emisse requested change).
- Bathroom near engineering changed.
- Security locker room changed (emisse requested change).
- Law office lawdrobe moved (emisse requested change).
- Tiny fans added to evac (emisse requested change).
- Artifact chambers now have pipes to pull gas from chambers (emisse requested change).
- Maint vault removed near science (emisse requested change).
- Security checkpoint added to medbay (checkraze requested change).
- Captains loot in captains bedroom altered (emisse requested change).
- Carpet in arcade room changed  (emisse and moony requested change).
- Grinder removed from chemistry (emisse requested change).
- Plasma removed from RD office (emisse requested change).
- Arrivals has an intercom and intercom all replaced with intercom commons for general access.
- Atmos crew can now get into the area between the gas miners and atmos (emisse requested change).
- fax machines in moved from their head offices to general department areas  (checkraze requested change).
- Reduced the medical stock in medbay store room (emisse requested change).
- Removed toxin medkits from virology (emisse requested change).
- Redesigned the medbay locker room (emisse requested change).
- Small perma brig replaced with boxing ring (emisse requested change not specific replacement).
- Floor in EVA under catwalk changed to plating (emisse requested change).
- Perma visitation now has reinforced glass, locker in perma checkpoint now is empty  (emisse requested change).
- Added a security checkpoint near cargo (checkraze requested change).
- Moved mime job spawner from icecreamparlor to mime bedroom (checkraze requested change).
- Signal switches in cargo shuttle dock moved from reinforcedglass to rwalls  (checkraze requested change).
- Many cosmetic changes to some rooms (checkraze requested change).
- Technology disk printer added to server room in science.
- Extended janitorial area and added a new waste sorting area. All waste now comes directly here. The janitorial team may then sort it into either useful items going to cargo or trash going to waste disposal.
- Added a hotplate to chemistry.
- Created a room in medical designed for the crypod (no crypod in there but the piping is ready for a crypod).

### CODE REVIEW

**Comment by Mervill** [comment]
The solar panel arrays should probably be more "strongly connected" to the station. The southern array for example needs only two (three?) cuts on a single tile to irreparably separate it from the main station. The northern array is a bit better but could use another one or two strong links to the main body of the station so it's not trivial to break it permanently.

Unless the map renderer is broken, I think there are two window/grille combos missing from the left side of the gravity generator room.

**Comment by brainfood1183** [comment]
> 

well get on improving those, the missing grille window in rav is intentional so you can get to it, although securing it further might be good idea yea

**Comment by brainfood1183** [comment]
> The solar panel arrays should probably be more "strongly connected" to the station. The southern array for example needs only two (three?) cuts on a single tile to irreparably separate it from the main station. The northern array is a bit better but could use another one or two strong links to the main body of the station so it's not trivial to break it permanently.
> 
> Unless the map renderer is broken, I think there are two window/grille combos missing from the left side of the gravity generator room.

I made these changes, improved the connectivity of the solar arrays so they are not so easily sabotaged and i added grille and window to grav so it is separated from rest of room.

**Comment by Mervill** [comment]
Can you keep the image in the op up-to-date with your current changes? Or maybe post them along with comments? Eventually we will have a bot to do this but in the mean time it would help if we're always looking at the most recent render.

**Comment by brainfood1183** [comment]
> Can you keep the image in the op up-to-date with your current changes? Or maybe post them along with comments? Eventually we will have a bot to do this but in the mean time it would help if we're always looking at the most recent render.

it has been updated.

**Comment by mirrorcult** [comment]
closing and reopening PRs does not do anything

**Comment by brainfood1183** [comment]
> closing and reopening PRs does not do anything

well i closed it and made a new one but was told to reopen this one instead and i cannot fix this pr.

**Comment by mirrorcult** [comment]
closing and reopening PRs does not do anything

you can just push. stop doing that

**Comment by brainfood1183** [comment]
> closing and reopening PRs does not do anything
> 
> you can just push. stop doing that

finally fixed it, this time it closed automatically because i reset the branch completely so it had 0 files in it then just pushed the 2 changed files.

**Pull request merged**
