### PR TITLE
Fix misc virtual item issues

### PR DESCRIPTION
**Pull request by ElectroJr**
This PR :
- Makes virtual items delete themselves whenever they are removed from the hands container, not just on unequip events
- Updates the hands-GUI when a virtual-item's blocking entity is updated. 
- Moves the interaction blocking to shared, so that any predicted interactions get properly blocked.

Initially this PR had other changes, but those can now be found in #5982 and #6033 instead.

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
Stripping is broken when:
Stunned, Crit, Dead, Handcuffed, or otherwise incapacitated

Fails when the person that's being stripped wouldn't be able to remove that item themselves?

**Review by PaulRitter — CHANGES_REQUESTED** [review]
i dont like it. the solution here should be for the code to run the handsdrop function before calling equip, not have equip have a snowflaky flag imo

**Review by ElectroJr — COMMENTED** [review]
> the solution here should be for the code to run the handsdrop function before calling equip, not have equip have a snowflaky flag imo

As you don't want to actually drop the item if it cannot be equipped (at least, not without having a weird unequip-then-reequip interaction when failing).  the various `CanEquip` checks still need to be done before dropping the item.  So `TryEquipActiveHandTo` can't just directly call `TryEquip`, 

I've removed the `fromHands` bool and just fleshed out `TryEquipActiveHandTo` to basically be a modified version of `TryEquip` with it's own networked event, I think that's good enough until hands gets fully refactored and this can hopefully be done more elegantly

**Comment by ElectroJr** [comment]
The hands-inventory interface changes have been removed here. That issue is now fixed in #6033 instead.

The description has been updated and the PR is quite a bit smaller now,

**Review by ShadowCommander — APPROVED** [review]

**Pull request merged**
