### PR TITLE
Remove contests

### PR DESCRIPTION
**Pull request by metalgearsloth**
- Not mentioned anywhere ingame.
- Stupid.

Resolves https://github.com/space-wizards/space-station-14/issues/15069

Edit: CalculateDisarmChance is a fuck because sometimes it clamps and sometimes it doesn't when the chance is inverse.

### CODE REVIEW

**Comment by asperger-sind** [comment]
This kind of ends up making shoves worse than they should be because now they're not affected by damage & stamina contests, mass contest removal is good thought. Better shoves on successive shoves is a pretty big factor when it comes to shoving, same with things like bola -> shoves being worse now because shoves aren't affected by stamina.

**Comment by metalgearsloth** [comment]
> This kind of ends up making shoves worse than they should be because now they're not affected by damage & stamina contests, mass contest removal is good thought. Better shoves on successive shoves is a pretty big factor when it comes to shoving, same with things like bola -> shoves being worse now because shoves aren't affected by stamina.

**Comment by asperger-sind** [comment]
> Hidden combat mechanics are stupid.

Then make them clearly visible, add an examine popup saying that the person is liable to getting shoved more easily, add a guiedbook entry, add a description saying this to the disarm action, make the popups on shoves say that the person isn't weak enough to be shoved easily.

My point is that there are methods of getting this information to the player and that outright removal (affecting balance mind you) isn't a good solution to information that just isn't conveyed

**Comment by UbaserB** [comment]
im fine with removing contests of *mass*, but the condition (stamina, health) of the player shoving should still affect the rng

**Comment by metalgearsloth** [comment]
> My point is that there are methods of getting this information to the player and that outright removal (affecting balance mind you) isn't a good solution to information that just isn't conveyed

I don't think any human could calculate on the fly what their chance is to disarm based on their current stam + damage vs their target's. In fact I don't think anyone out-of-game even has any idea what the values are like.

**Comment by asperger-sind** [comment]
> I don't think any human could calculate on the fly what their chance is to disarm based on their current stam + damage vs their target's. In fact I don't think anyone out-of-game even has any idea what the values are like.

Is it bad? No. You don't need to be able to clearly calculate your chance on the fly, but you should be able to accurately guess whether or not you can shove someone, which you can do with conveyed information.

> This also makes stuff like mob balancing shit when a spider can get instantly stunned due to arbitrary density values being used everywhere.

Mass contest removes this, I'm fine with mass contest being removed as it's a bad thing to have unlike stamina/damage contests.

**Comment by metalgearsloth** [comment]
> Is it bad? No. You don't need to be able to clearly calculate your chance on the fly, but you should be able to accurately guess whether or not you can shove someone, which you can do with conveyed information.

Such as? Also are you aware that your chance to shove someone actually decreases as they get more hurt.

**Comment by UbaserB** [comment]
> > Is it bad? No. You don't need to be able to clearly calculate your chance on the fly, but you should be able to accurately guess whether or not you can shove someone, which you can do with conveyed information.
> 
> Such as? Also are you aware that your chance to shove someone actually decreases as they get more hurt.

it should be the opposite way around, as YOU get more hurt you have less chance to shove someone

**Comment by metalgearsloth** [comment]
> > > Is it bad? No. You don't need to be able to clearly calculate your chance on the fly, but you should be able to accurately guess whether or not you can shove someone, which you can do with conveyed information.
> > 
> > 
> > Such as? Also are you aware that your chance to shove someone actually decreases as they get more hurt.
> 
> it should be the opposite way around, as YOU get more hurt you have less chance to shove someone

That's not how it works on master atm, hence why this system is beyond stupid.

**Comment by UbaserB** [comment]
> > > > Is it bad? No. You don't need to be able to clearly calculate your chance on the fly, but you should be able to accurately guess whether or not you can shove someone, which you can do with conveyed information.
> > > 
> > > 
> > > Such as? Also are you aware that your chance to shove someone actually decreases as they get more hurt.
> > 
> > 
> > it should be the opposite way around, as YOU get more hurt you have less chance to shove someone
> 
> That's not how it works on master atm, hence why this system is beyond stupid.

yeah ok im fine with this pr being merged as the changes get resolved lol, all i care about is conditional player status affecting rng

**Comment by asperger-sind** [comment]
> Such as? Also are you aware that your chance to shove someone actually decreases as they get more hurt.

Such as the methods I described. My testing implies otherwise for the chance part.

An Urist vs. Urist2 shove with Urist2 being the target and having 50-70 damage shows 47 stamina damage per shove with very frequent shoves, Urist2 with 95 damage gets shoved for 100+ stamina damage usually on the first attempt.
Urists in this example are identical humans.

**Comment by africalimedrop** [comment]
lilten literally just did a video on this re 'hidden'. it appeared to work as intended other than an apparent bug where you'd disarm an unarmed person instead of shoving, and even if it didnt work any person acting in good faith would flag it for a fix not gut the system. its a pattern im seeing a lot and im gonna question it.

**Pull request merged**
