### PR TITLE
Medical Locker Fill Change

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changed the contents of various medical lockers

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed medical locker contents

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
I dont think it needs changing

**Comment by Alekshhh** [comment]
you're going to need to be more specific

**Comment by JoeHammad1844** [comment]
I just think the contents are fine right now

**Comment by Alekshhh** [comment]
I don't

**Comment by JoeHammad1844** [comment]
evidently

**Comment by potato1234x** [comment]
why though these are basically unnoticeable

**Comment by UbaserB** [comment]
good changes.

**Comment by keronshb** [comment]
Please explain the reasoning behind this change.

**Comment by Alekshhh** [comment]
CMO: they don't need the viro boards as they're redundant, and having three biomass you will only use once every a hundred rounds isn't a good thing to fill your locker with. I can get ONE biomass maybe but not three
medical supplies locker: I felt like one epinephrine bottle is enough per locker, given you also have them from medical vendors and pill bottles are redundant in general
MD lockers: why do they need funny gas, let alone with a random chance. that stuff stays in the surgery room
chem lockers: given how rarely chemists use bottles, and the fact that they can just materialize them in their machines, having just one felt better than two, and swapping it with a chance to get a beaker box felt more appropriate. the other equipment like gloves was for consistency with MD lockers. the chem bag and labelers are job appropriate too
paramed lockers: same as chem. I would've slapped a handheld crew monitor in their lockers but I know handholding isn't respected so I gave them a medkit instead since I felt like it was fitting. although I can swap it to an O2 kit as it may be even more fitting

**Comment by deltanedas** [comment]
aspid has no medicine vendor

**Comment by Alekshhh** [comment]
what the FUCK

**Comment by EmoGarbage404** [comment]
> aspid has no medicine vendor

sounds like an aspid problem

**Comment by Alekshhh** [comment]
aspid medical is scuffed in general but that's not for this pr

**Pull request merged**
