### PR TITLE
nukies get night vision

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Nukies now get night vision. Actually its sechud. Actually those are the same

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: JoeHammad
- add: Nukies now get sechu- I mean night vision.. same thing.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
They should get actual nightvision instead sir.

**Comment by IntegerTempest** [comment]
I want to make a spacial syndicate hud for opers. This should be a special military development of the syndicate and not a simple sec hud.

**Comment by JoeHammad1844** [comment]
they need a faction overlay like revs

**Comment by deltanedas** [comment]
valid balloon just got valider...

**Pull request closed without merging**
