### PR TITLE
Give weh juice slight toxin damage

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Juice that makes you weh now deals 1 poison per unit.
## Why / Balance

1. nothing good should come for free
2. something something equivalent exchange
3. I Hate Fun™
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Weh juice now deals a tiny amount of poison damage.

### CODE REVIEW

**Comment by potato1234x** [comment]
literally why

**Comment by MACMAN2003** [comment]
> literally why

i've yet to see a round where the chems in medbay/the drinks in the bar haven't been spiked with weh juice or someone foam-flooded with weh juice. plus injecting ground up plushies into the bloodstream can't possibly be healthy.

**Comment by deltanedas** [comment]
counterpoint moths eat cloth and cotton (not to mention plastic cones) so how could it be toxic to them

cotton is probably safe to eat anyway for humans :trollface:

**Comment by metalgearsloth** [comment]
Not seeing a compelling argument unless another maint disagrees.

**Comment by Djungelskog2** [comment]
alternatively it gives a forced accent that occasionally replaces words with weh based on the dosage (Lizards, the pets, also now say Weh!)

**Pull request closed without merging**
