### PR TITLE
Add second ear slot

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

**Media**

https://github.com/space-wizards/space-station-14/assets/124214523/f6271ed6-e09f-44b3-bfb1-78ae0108bc99
shit, sorry for bad quality

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added slot for second ear!

### CODE REVIEW

**Comment by UbaserB** [comment]
Does this mean you can wear two headsets…?

**Comment by Emisse** [comment]
what is he cooking

**Comment by lzk228** [comment]
> Does this mean you can wear two headsets…?

yes, like in ss13

**Comment by lapatison** [comment]
Finally I can put cigarette behind the ear like my Pa

**Comment by keronshb** [comment]
> > Does this mean you can wear two headsets…?
> 
> yes, like in ss13

What SS13 server allows two earslots and headsets?

Please make it so that only one headset can be equippable at a time. Two is exceptionally overpowered.

**Comment by mirrorcult** [comment]
i dont know of this as a feature in any SS13 server. this isn't unreasonable to add but headsets need to take up both ear slots in this case

**Comment by EmoGarbage404** [comment]
We don't think that the positive aspects of multiple ear slots outweighs the additional maintenance burden added by it. Closing this pr.

**Comment by lzk228** [comment]
> What SS13 server allows two earslots and headsets?

paradise

**Comment by githubuser4141** [comment]
> i dont know of this as a feature in any SS13 server. this isn't unreasonable to add but headsets need to take up both ear slots in this case

Baystation & Paradise afaik

**Pull request closed without merging**
