### PR TITLE
add data science research and craftble R&D servers

### PR DESCRIPTION
**Pull request by lermal**
Adding data science technology and the ability to create R&D servers

## About the PR

My pull request adds the ability to explore and create/disassemble R&D servers. The need for such a technology appeared after the work of the T3 technology research was changed. Many people playing for scientists want to explore all possible technologies, not limited to just one. I tried to make a sufficiently balanced crafting of the new server so that it could not be created simply by buying materials.

I described all the changes below:
- Added a new technology "Data Science"
- Added a machine board for the R&D server
- Added R&B server collection recipe
- When disassembling the server, all the materials required for assembly fall out of it

**Media**

https://github.com/space-wizards/space-station-14/assets/82917953/e1f0d1d6-02a1-44e6-ab8f-43e1b8631f1b

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a new technology "Data Science"
- add: Added creating R&D servers and disassembling them

### CODE REVIEW

**Comment by 0x6273** [comment]
I don't think this should be gated behind research, since then you're screwed if R&D server gets bombed and you didn't have it unlocked beforehand.

**Comment by EmoGarbage404** [comment]
However, resetting a server under the new system could be very interesting. I would recommend that you change the pr to just make the server constructible and remove the technology for it. (You should also just make the machine board require standard parts like steel or cables)

**Comment by IntegerTempest** [comment]
I think it would be better to do so that it would be possible to order a circuit board in cargo. If your server is destroyed, then this way it can be returned back.

**Comment by Interrobang01** [comment]
> I don't think this should be gated behind research...

Possible solutions could include putting board in salvage, giving RD a spare board, giving RD a magic button that can be used once and only once to create any other board, so using it as a backup comes at a cost...

Personally I think that silver and uranium are rare enough that crafting board is balanced. If in doubt add even rarer resources.

And probably don't make it purchase-able, there is no price sweet spot where it's neither easy to get a lot of nor impossible to convince cargo to get even 1 of.

Anyways I particularly like the idea of removing the tech and putting boards in salvage rarely, if it makes everyone happy.

**Comment by EmoGarbage404** [comment]
mapping it into salvage as a rare thing is fine imo. My main issue is just that this completely bypasses the lockout, as obtaining these materials isn't extraordinarily difficult, and could feasibly be accomplished almost every round.

**Comment by Interrobang01** [comment]
> And probably don't make it purchase-able...

on second thought there probably is a sweet spot for purchasable-able boards for specifically when all servers get destroyed; cargo becomes a lot more willing when they realize science becomes totally crippled without that expensive $50,000 board.

Just beware of atmos techs frezoning the place up.

**Comment by lermal** [comment]
> I think it would be better to do so that it would be possible to order a circuit board in cargo. If your server is destroyed, then this way it can be returned back.

It's a good idea. I can really replace the technology with the purchase of a fee. I only have in mind the "R&D Server Kit", which will include all the server components and the board. You can also make a simple purchase of a ready-made server.

**Comment by lermal** [comment]
> I understand people's feelings toward the lockout system...

Creating a new server does not speed up the research process, since everything has to be research from scratch and in each lathe you need to change servers for a specific subject

**Comment by LordEclipse** [comment]
> > I understand people's feelings toward the lockout system...
> 
> Creating a new server does not speed up the research process, since everything has to be research from scratch and in each lathe you need to change servers for a specific subject

Aren't research points also locked to one server? Like non-transferable.

**Comment by EmoGarbage404** [comment]
Once you have enough points to unlock a discipline, it's pretty easy to just switch your vessels and analysis consoles to a different server.

The issue is really just that having multiple servers directly circumvents lockout in a very consistent way that isn't very difficult (there are many maps where the only material not immediately available is uranium).

**Comment by Interrobang01** [comment]
Could maybe lean into the uranium, reducing all the prices but increasing uranium price? It's an option.

Also, what if the default mapped research servers was made out of expensive high tier parts, and servers made of lesser parts ran incredibly inefficiently?

**Comment by AJCM-git** [comment]
After some discussion, it has been decided that the current mechanic of resetting the servers handles the intended purpose of this pr

**Pull request closed without merging**
