### PR TITLE
Add easy window upgrading, fix some other window issues.

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
**First off, the main thing:**
Windows can now have rods/plasma/uranium/plastic added to them to quickly and easily upgrade them to reinforced/plasma/uranium/tinted versions. Plasteel can also turn reinforced windows into shuttle windows.
**_ENGINEERS REJOICE!!!_**

**Secondly:**
Window HP is now a bit more standardized and not completely all over the place.
- window: 50 (Glass)
- tinted window: 50 (Glass) (these use plastic now to allow them to fit in the upgrade tree alongside reinforced windows)
- plasma window: 75 (Glass)
- uranium window: 75 (Glass)
- clockwork window: 75 (RGlass)
- reinforced window: 75 (RGlass)
- reinforced plasma window: 150 (RGlass)
- reinforced uranium window: 150 (RGlass)
- shuttle window: 500 (RGlass)

Thindows have half the HP and the same damage mods as their full version. (600 HP reinforced plasma glass thindow is dead)

**Thirdly:**
Window damage visuals are fixed, for awhile now they've displayed very strangely due to not having their values updated when windows got their HP nerfed. Visuals display at 20% damage, 40% damage, and 80% damage now.

## Why / Balance
So basically, trying to upgrade ANYTHING as an engineer has just been absolutely horrible. You'd first need to get the materials, craft them together, remove the old window, possibly mess with some grilles and float around in space, and chances are you won't even get everything done in time. Now you can get the materials, bring them to the place you want to upgrade, and now it's just a few doafters and boom, done! Engineers can pre-emptively upgrade windows before meteors hit evac now without going through an hour and a half of pain!

## Media

https://github.com/user-attachments/assets/b22d8715-5f00-4bfb-8a93-59929b013add

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
**Changelog**
:cl:
- add: Normal and reinforced windows have been made directly upgradable using rods, plasma, uranium, or plasteel.
- tweak: Reinforced plasma and uranium windows have been made tougher.
- fix: Windows have been made to correctly display their damage visuals.
- fix: Reinforced plasma windows have been given the correct amount of hp and no longer have 12x the amount they should.

### CODE REVIEW

**Comment by DogZeroX** [comment]
King

**Comment by lzk228** [comment]
applying plastic on directional window should make frosted windows, yes they don't have functionality rn, but still

**Comment by Dragonjspider** [comment]
Engineering borgs rejoice!!! 🤖

**Comment by thebadman4662** [comment]
> reinforced plasma window: 150 (RGlass)
I see commit buffing it from 100 to 150 but at same time I recall they are capable of tanking around 50 L6 saw shots, was that fixed sometime?

**Pull request merged**
