### PR TITLE
Aclownominations

### PR DESCRIPTION
**Pull request by Ablankmannn**
## About the PR 
I am not sorry, nor do I ask for forgiveness. 
This (hopefully) adds an admeme only set of creatures known as Clown Abominations, with stuff that was jokingly thrown around in the discord

**Changelog**

:cl:
- add: Added Aclownominations. It is said they feed on spessmen and orphans alike.

### CODE REVIEW

**Comment by Zumorica** [comment]
For writing changelogs, don't consider the entry type suffix (e.g. add) to be part of the sentence
Your changelog should look like this:
`add: Added aclownominations. It is said they [...]`

**Comment by Ablankmannn** [comment]
rookie mistake, my bad

> For writing changelogs, don't consider the entry type suffix (e.g. add) to be part of the sentence Your changelog should look like this: `add: Added aclownominations. It is said they [...]`

rookie mistake, my bad

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Sprites are invalid and need fixing, also parenting to MobHuman / MobXeno is yuck and should be cleaned up.

**Comment by ike709** [comment]
Aclowninations is less of a mouthful IMO

**Pull request closed without merging**
