### PR TITLE
Space carp resprite

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes space carp sprites and removes the glow-in-the-dark teeth they had. If it gets approved I'll do the magicarp and holocarp (although I'd need help with a coder to do it nicer)

**Media**
image

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Aleksh
- tweak: Changed space carps visually, and removed their glowing mouth

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
1. There's no point splitting sprites if they're going to use the same shader
2. Sprites shouldn't have harsh borders.

**Comment by Alekshhh** [comment]
> 1. There's no point splitting sprites if they're going to use the same shader
> 
>     2. Sprites shouldn't have harsh borders.

The issue is, if I make it one single sprite, the mouth and eyes will be colored along with the whole body. It ends up looking like this, and it's very ugly
image

**Comment by CaptainSqrBeard** [comment]
I honestly don't like these sprites. Maybe that issue for any resprite but idk.

**Comment by deltanedas** [comment]
I also don't like, looks too shark-like and the one facing down looks more like spitter from ror1 than a terrifying fish

**Pull request closed without merging**
