### PR TITLE
Reptilian species

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
Basic Reptilian (Lizardperson) species

Adds new enums for body parts: tail, horns, snout, frills

**Screenshots**

image
image
image

**Changelog**

:cl: Daemon
- add: Added new species, the Reptilian (Lizard Person)

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
Currently the only customization supported is scale color

**Comment by moonheart08** [comment]
I think, judging by the tests, you broke something pretty fundamental in HumanoidAppearanceSystem.

**Comment by ZeroDayDaemon** [comment]
yeah this is pretty hacky because most of the systems don't really support new body parts or certain species having body parts that other species' don't

**Comment by ZeroDayDaemon** [comment]
I'm looking into trying to add better support in another branch I haven't pushed yet, and then rework this to that branch with better species support

**Comment by ZeroDayDaemon** [comment]
I give up

**Comment by DogZeroX** [comment]
(༎ຶ ෴ ༎ຶ)

**Comment by ZeroDayDaemon** [comment]
Aight imma give this another shot

**Comment by DogZeroX** [comment]
Ask for help if you need :>

**Comment by ZeroDayDaemon** [comment]
It's failing because it's trying to set the color of certain body parts that not all species have

Content.Client/CharacterAppearance/Systems/HumanoidAppearanceSystem.cs

**Comment by mirrorcult** [comment]
reopen when you have a chance to work on it again

**Pull request closed without merging**
