### PR TITLE
ID Console can no longer grant access the privileged ID doesn't have. (read: AA nerf)

### PR DESCRIPTION
**Pull request by moonheart08**
What it says in the title. Additionally, you no longer need to be the HoP to use the console, your ID just can't do very much.
Intent is to use this for some experiments soon with removing the HoP outright or just replacing them with a less privileged job, in favor of allowing departments to manage their own hiring.
However I expect this specific change to be permanent regardless of how the experiments go.

**Media**
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: moony
- tweak: ID Card Console now requires the privileged ID have the access being granted.
- tweak: The ID Card Console is no longer access locked, all cards can use it.
- tweak: The HoP has had additional accesses added to their card so they can continue to function as normal. This does NOT include head accesses, they can no longer grant access to captain's office for example.

### CODE REVIEW

**Comment by deltanedas** [comment]
I think it's an interesting idea but be prepared for players to ***seethe*** if merged

also this should eventually have extra id consoles mapped to departments for easy promoting so no running around to hop which isn't even real anymore

**Comment by moonheart08** [comment]
> I think it's an interesting idea but be prepared for players to _**seethe**_ if merged
> 
> also this should eventually have extra id consoles mapped to departments for easy promoting so no running around to hop which isn't even real anymore

this is why i'm doing it because I don't give two shits about players seething

The plan's to give every dept an ID console yes.

**Comment by deltanedas** [comment]
the id computer board objective should also be removed since its meaningless if you just go to your depts front desk and take it

**Comment by GoodWheatley** [comment]
If this PR didn't mess with the HoP I'd say this was a great change, but the way it is right now is definitely going to backfire.
This change completely prevents the HoP from performing promotions to important roles, and instead requires the Captain or the department head to come down to the office, hop the counter, and do the promotion themselves. While I could see how this can be justified as a good thing, I feel like its going to just aggravate both the HoP and the other head, as they both have to go put of their way to do this previously simple task. It's even possible this could lead to the HoP begging for the spare captain ID at roundstart, so they can perform their job and fulfill promotion requests. While this is likely going to be a minor issue, there's something much bigger I'm worried about:
*This change directly encourages Hopcurity.*
With the already low importance of their job degraded even further, the HoP is more free than ever to fuck off and validhunt. They even start with security access now, so they can waltz in, grab sec officer gear, and go out to hunt antags. Validhunting isn't gameplay that should be encouraged by any means, and will likely create even bigger headaches for admins since there won't even be a log message saying they added sec access to their ID card.

**Comment by moonheart08** [comment]
> If this PR didn't mess with the HoP I'd say this was a great change, but the way it is right now is definitely going to backfire. This change completely prevents the HoP from performing promotions to important roles, and instead requires the Captain or the department head to come down to the office, hop the counter, and do the promotion themselves. While I could see how this can be justified as a good thing, I feel like its going to just aggravate both the HoP and the other head, as they both have to go put of their way to do this previously simple task. It's even possible this could lead to the HoP begging for the spare captain ID at roundstart, so they can perform their job and fulfill promotion requests. While this is likely going to be a minor issue, there's something much bigger I'm worried about: _This change directly encourages Hopcurity._ With the already low importance of their job degraded even further, the HoP is more free than ever to fuck off and validhunt. They even start with security access now, so they can waltz in, grab sec officer gear, and go out to hunt antags. Validhunting isn't gameplay that should be encouraged by any means, and will likely create even bigger headaches for admins since there won't even be a log message saying they added sec access to their ID card.

the captain having to do promotions is the point lol

also HoP *has security access regardless of this change*, the current ID console allows them to give it to themselves trivially.

Both of these are completely moot points.

**Comment by Emisse** [comment]
wheatley opposed ready for merge

**Comment by Stealthbomber16** [comment]
please explain why removing hop's effective access to armory encourages hopcurity

**Comment by Cheackraze** [comment]
Though you want to 'expirement', this change will render Hop's job impossible to do even when you're not 'expirementing'.  This effectively makes Hop's job impossible to perform.  It needs to be an _option_, not forced, if you're going to 'expirement'

**Comment by EmoGarbage404** [comment]
it's stated in the pr that this change is meant to be permanent.
the greater experiment is to test removing HOP as a role on stations. This change is just assisting with that.
also in you spelled experiment wrong like 3 times.

**Comment by vulppine** [comment]
this would allow other players to duplicate their access across other ID cards, if they have access to the ID console, right? this'll definitely be interesting in terms of balancing how giving ID access works

**Comment by Cheackraze** [comment]
This will also kill many low pop rounds and is terrible for RP.  This should be a separate entity so that this change is not forced and permanent

**Comment by vulppine** [comment]
i know that in some SS13 servers, you can give temporary guest passes to other people via some guest pass console, that has a player's ID access (selective, of course) - but only ID access from the card that they have at the moment

**Comment by moonheart08** [comment]
> this would allow other players to duplicate their access across other ID cards, if they have access to the ID console, right? this'll definitely be interesting in terms of balancing how giving ID access works

Correct. Which is in part why I do not see any change in how this affects lowpop, it's just cap's job to dole out important access instead of HoP's, and now folks can let others into their department more easily if needed.

**Comment by moonheart08** [comment]
> 

Yea, i'm considering adding this.
It'd be very easy to head-lock ID consoles again upon introduction of a guest pass system but I like the potential (ab)use of the console.

**Comment by Cheackraze** [comment]
Low pop servers without a single person in say, engineering, will result in nobody able to set up engineering.  Or nobody in security means that nobody can react to any lethal threat.

And its terrible for RP because why would administrative duties be divided up among everybody? Why wouldn't you have a position that can handle personel requests? How is the paramedic going to get external access? How is sec going to get external access? Now tiders will be able to share their accesses freely.  One tider gets access to a command ID, now the entire crew has it because the ID consoles are public access and unguarded.  Or, a scientist now just has to sit microwaving id's for 10 minutes in the break room and now using the publicly available console, can effectively get AA. Thats besides the point that HoP is one of like 3 total jobs where the role-playing is built right into the job, by making requests for stamps and calling the heads for confirming requests.  This is a very ill conceived change and it should be made _optional_, not mandatory.  Feel free to "expirement" but this isn't that, this is just a forced, drastic change to a role that has been well defined, fully functioning, and beloved for over a decade

**Comment by randy10122** [comment]
> how is this terrible for RP 
if you want an ID change into a department you no longer have to go talk to the HoP about it, meaning there is considerably less chance for interaction with other players 


i personally dont see why you wanna remove the HoP entirely?? like. i just dont get it
im a bit iffy on this pr as a whole

**Comment by moonheart08** [comment]
This PR does not remove the HoP and this is not the place to discuss that.

Lowpop already has that problem unless there's a HoP or Captain, that has not changed with this PR and won't change even with HoP's change to captain's righthand man instead of a paper pusher.

**Comment by moonheart08** [comment]
ID Consoles additionally will not be public, where did that get stated. You are being reactionary, kindly cool your head and discuss changes calmly.

**Comment by Cheackraze** [comment]
> This PR does not remove the HoP and this is not the place to discuss that.
> 
> Lowpop already has that problem unless there's a HoP or Captain, that has not changed with this PR and won't change even with HoP's change to captain's righthand man instead of a paper pusher.

These ID consoles changes do, in fact, affect the existing HoP role, and make your intended changes forced upon every shift, not just ones you 'expirement' with

**Comment by asperger-sind** [comment]
I believe this should be testmerged instead of arguing over Discord/Github because arguments on this topic will last for an eternity, open alpha after all.

Maybe a maintainer meeting topic? March 18 isn't that far away.

**Comment by Cheackraze** [comment]
> ID Consoles additionally will not be public; where did that get stated? You are being reactionary, kindly cool your head and discuss changes calmly.

You literally have stated that regular crew will be able to use them?  Sure it might not be in the main hallway but this gives access to nearly everybody.  I'm not being reactionary, im pointing out the obvious scenarios that you have not considered and are just handwaving away

**Comment by moonheart08** [comment]
> > ID Consoles additionally will not be public; where did that get stated? You are being reactionary, kindly cool your head and discuss changes calmly.
> 
> You literally have stated that regular crew will be able to use them? Sure it might not be in the main hallway but this gives access to nearly everybody. I'm not being reactionary, im pointing out the obvious scenarios that you have not considered and are just handwaving away

i have considered what happens if it gets broken into, the ability for people to modify their own IDs if they get access to the console is Intended.

**Comment by EmoGarbage404** [comment]
i genuinely want to know why do you keep misspelling experiment?
is it a pun? a portmanteau of expire and experiment?
the answer grips me to my core.

**Comment by Cheackraze** [comment]
> i genuinely want to know why do you keep misspelling experiment? is it a pun? a portmanteau of expire and experiment? the answer grips me to my core.

Please don't clutter github with irrelevant posts

**Comment by EmoGarbage404** [comment]
> Please don't clutter github with irrelevant posts

i was simply curious.

**Comment by Cheackraze** [comment]
> > > ID Consoles additionally will not be public; where did that get stated? You are being reactionary, kindly cool your head and discuss changes calmly.
> > 
> > 
> > You literally have stated that regular crew will be able to use them? Sure it might not be in the main hallway but this gives access to nearly everybody. I'm not being reactionary, im pointing out the obvious scenarios that you have not considered and are just handwaving away
> 
> i have considered what happens if it gets broken into, the ability for people to modify their own IDs if they get access to the console is Intended.

Ok, so letting the entire crew share whatever access they obtain with eachother with no oversight is intended?

**Comment by randy10122** [comment]
oh, also, as someone who plays HoP more than any sane man should, this will make even more of the job just staring at chat and waiting for something to happen which SUCKS

**Comment by moonheart08** [comment]
> oh, also, as someone who plays HoP more than any sane man should, this will make even more of the job just staring at chat and waiting for something to happen which SUCKS

Hence the fact we want to make HoP an actual righthand man, as discussed within the game's discord.

**Comment by moonheart08** [comment]
This is not the place to discuss the extended changes, as they have not been made yet and are being formalized still.

**Any further off-topic discussion will be hidden. Focus on the PR itself.**

**Comment by moonheart08** [comment]
> > > > ID Consoles additionally will not be public; where did that get stated? You are being reactionary, kindly cool your head and discuss changes calmly.
> > > 
> > > 
> > > You literally have stated that regular crew will be able to use them? Sure it might not be in the main hallway but this gives access to nearly everybody. I'm not being reactionary, im pointing out the obvious scenarios that you have not considered and are just handwaving away
> > 
> > 
> > i have considered what happens if it gets broken into, the ability for people to modify their own IDs if they get access to the console is Intended.
> 
> Ok, so letting the entire crew share whatever access they obtain with eachother with no oversight is intended?

...yes, that already happens with AA and this actually nerfs their ability to do any significant damage with that because fewer personnel have AA.

**Comment by Cheackraze** [comment]
> > > > > ID Consoles additionally will not be public; where did that get stated? You are being reactionary, kindly cool your head and discuss changes calmly.
> > > > 
> > > > 
> > > > You literally have stated that regular crew will be able to use them? Sure it might not be in the main hallway but this gives access to nearly everybody. I'm not being reactionary, im pointing out the obvious scenarios that you have not considered and are just handwaving away
> > > 
> > > 
> > > i have considered what happens if it gets broken into, the ability for people to modify their own IDs if they get access to the console is Intended.
> > 
> > 
> > Ok, so letting the entire crew share whatever access they obtain with eachother with no oversight is intended?
> 
> ...yes, that already happens with AA and this actually nerfs their ability to do any significant damage with that because fewer personnel have AA.

The crew cannot share their accesses currently, as they don't have free access to the ID console.  You are just intentionally misrepresenting the argument now and not actually addressing the criticism in good faith.

**Comment by EmoGarbage404** [comment]
it was never specified that they had free access to the console to begin with?

**Comment by Cheackraze** [comment]
> it was never specified that they had free access to the console to begin with?

tweak: The ID Card Console is no longer access locked, all cards can use it.

It's right in the changelog

**Comment by EmoGarbage404** [comment]
> tweak: The ID Card Console is no longer access locked, all cards can use it.
> 
> It's right in the changelog

console not being access locked != publicly available.

**Comment by Cheackraze** [comment]
> > tweak: The ID Card Console is no longer access locked, all cards can use it.
> > It's right in the changelog
> 
> console not being access locked != publicly available.

The consoles are going to be in every department because it's up to the individual departments to hire since captain can't.  You're not discussing this in good faith.

Just make this a new prototype and don't fuck with the existing one so that you can do this on your own and not force it upon every single shift

**Comment by Veritius** [comment]
> You're not discussing this in good faith.

**Comment by EmoGarbage404** [comment]
1. consoles don't have to be in every department, especially unsecured. they can be in Head's offices, if they're per department.
2. hop's ID can still grant basic access to all departments.
3. can you take a chill pill, por favor? no need to get so heated. i can assure you that i'm arguing in good faith.

**Comment by Cheackraze** [comment]
> > You're not discussing this in good faith.

Yup why bother.  Every criticism I have comes with a deceitful response about how this is intended to play out.

**Comment by Cheackraze** [comment]
> 1. consoles don't have to be in every department, especially unsecured. they can be in Head's offices, if they're per department.
> 2. hop's ID can still grant basic access to all departments.
> 3. can you take a chill pill, por favor? no need to get so heated. i can assure you that i'm arguing in good faith.

So now only heads will have the consoles then? Why the change to allow any ID Card to use it then since it's already command locked? And HoP doesn't have med, sci, engineering, sec, or cargo access to start, so they literally cannot hire to those departments.

And stop with the gaslighting.  How about you take a chill pill since you seem to be so heated about this.

Not once have I used inflammatory language, stop insulting people who are merely trying to point out the obvious flaws.

**Comment by EmoGarbage404** [comment]
> So now only heads will have the consoles then? Why the change to allow any ID Card to use it then since it's already command locked? And HoP doesn't have med, sci, engineering, sec, or cargo access to start, so they literally cannot hire to those departments.

the consoles aren't command locked. they're locked only to head of personnel access. this is to allow individual heads to have limited access to the console in order to do more minute hiring and etc.

the pr gives hop those extra accesses: it's in the changelog.

**Comment by moonheart08** [comment]
Hi! The comment section has been unlocked. Please address concerns or ideas **politely** and **calmly** from this point on.

**Comment by deltanedas** [comment]
should just do a test run of it and see how it plays
worst case hop becomes full time ian protector which is ok

**Comment by PJB3005** [comment]
~~I am a boomer therefore hate change~~

I don't see mentioned what happens to the ability to change job title/name on the card? Surely that's not available for everybody right?

**Comment by moonheart08** [comment]
> ~I am a boomer therefore hate change~
> 
> I don't see mentioned what happens to the ability to change job title/name on the card? Surely that's not available for everybody right?

Oop, I entirely forgot to fix that. What do you think a good solution would be there?

**Comment by moonheart08** [comment]
I personally think requiring HoP access to change an ID's name would make sense, and head access for job titles?
Hm.

**Comment by deltanedas** [comment]
yeah its a good solution, so cmo can make his doctor a paramedic but if you want to change name to "red sus" you need to go to hop

**Comment by Veritius** [comment]
Will using a preset still set the job name?

**Comment by moonheart08** [comment]
> > > snip
> > > also HoP _has security access regardless of this change_, the current ID console allows them to give it to themselves trivially.
> 
> But they don’t get brig access, and iirc that’s the access all the sec gear is locked behind. Maybe I’m overreacting/missing the point, but I’m just concerned about the potential ramifications of giving a job already known to be a loose cannon even less reason to stay at their station.

HoP gets brig access regardless of this change, they effectively had AA.

**Comment by PJB3005** [comment]
> Oop, I entirely forgot to fix that. What do you think a good solution would be there?

For normal job titles there's a pretty easy answer with this current system: just only allow assigning job titles that you have all the necessary access for. This doesn't address custom job titles though. The funniest solution I can think of is "custom job titles can be done by anybody" meaning that anybody can make themselves the "Chef Engineer", but not "Chief Engineer". Better read those IDs carefully!

Name changes (and custom job titles if we hate fun) I want to say "sure, leave it to HoP" but aren't you planning on eventually removing HoP?

I made the joke earlier about hating change but I am generally quite iffy on this change and still have some thoughts/concerns.

I don't like the idea that just anybody can change access for anybody else. I do like that this makes it easier to get jobs re-assigned in the round, because the HoP/captain are often absent/busy/dead/acting like blue security, but it should be limited to heads of staff.

It makes absolutely no sense to me, from neither gameplay nor RP, that any department member can permanently grant access to anybody else. Doctors shouldn't just have the function of promoting other doctors, that's always something at *least* the CMO should sign off on. And "all it takes is an ID getting in the hand of an assistant for one minute for them to copy the access" is way too viral of a gameplay idea. Normally "everybody has AA" requires a specific few high-value things to be leaked. With this system, we're going to need to put "don't copy that floppy" posters around the station due to how rampant copying *will* be.

"The ID consoles aren't public" does not hold much water. If it doesn't have an ID lock, people are not going to hesitate much about a quick trip to the CE's unused office. Let alone anybody caring to report it in that case.

Hell, I don't even want to think about how dangerous ID cards in *medbay* will be. There's an ID console right next to cloning and the morgue. People *are* going to take a quick trip to the CMO's to copy these while a patient is being cloned.

If you still want regular department members to have some degree of power here, guest passes seems like the most they should get.

Also, what about removing access? Can everybody remove any access from another ID, or only the access levels they have themselves?

I feel like, roleplay wise, ability for any head of staff to "steal" people from other departments without the other department head giving consent also doesn't make much sense. An idea: if the CMO were to give an engineer (not in their department) medical access, they would only put an "amendment" on their ID. It would be easily visible that they have amended access and still list their original job title as engineer. Full, clean changes can only be done through a master ID console (HoP/captain). Heads would have full reign to change titles and demote people within their own department, however.

**Comment by EmoGarbage404** [comment]
I proposed yesterday having a base access required. For example, you have to have command access in order to change a person's ID. That could be extended for name/job changes. If you really wanted to, you coule give HOP or Cap a unique access (or just HoP access) that allows them to change Id names and assign non-preset job names.

**Comment by GoodWheatley** [comment]
> > > > snip
> > > > also HoP _has security access regardless of this change_, the current ID console allows them to give it to themselves trivially.
> > 
> > 
> > But they don’t get brig access, and iirc that’s the access all the sec gear is locked behind. Maybe I’m overreacting/missing the point, but I’m just concerned about the potential ramifications of giving a job already known to be a loose cannon even less reason to stay at their station.
> 
> HoP gets brig access regardless of this change, they effectively had AA and this PR actually _nerfs_ their access to security.

Just checked this on master, HoP currently has neither security nor brig access on their ID card when the round starts. Yes, they can just immediately add those accesses to the card, but that leaves a log message that makes it obvious what the HoP is doing. And I'd argue that the HoP doesn't even need to get armory access, the secbelt gear is arguably more effective at hunting valids than what you can get in the armory since stun resistance is limited to a few complex chemicals and our lethal weapons feel like they've been babyproofed, but that's not relevant to this discussion.

Also why does the HoP have QM access now? Doesn't that go against the heads performing promotions themselves?

**Comment by PJB3005** [comment]
Is HoPcurity really that big of a concern that we need to come up with a system where they can't get armory access? Sure they shouldn't start with it, but...

**Comment by EmoGarbage404** [comment]
> Is HoPcurity really that big of a concern that we need to come up with a system where they can't get armory access? Sure they shouldn't start with it, but...

It really isn't. HOP having security access isn't that big of a deal either.

**Comment by GoodWheatley** [comment]
> Is HoPcurity really that big of a concern that we need to come up with a system where they can't get armory access? Sure they shouldn't start with it, but...

It probably isn't going to be an issue, I've just had bad experiences in the past with renegade HoPs who decide they're the guy who's going to singlehandedly kill all the traitors. Admittedly I haven't seen this happening for a few months, so I'm probably just overreacting.

**Comment by Biglulux** [comment]
Supposedly, HoP is the right hand man of the captain. But a lot of people, including this PR, don't treat him like it. If HoP is really the right hand man of the captain, he should start with AA.

**Comment by moonheart08** [comment]
> Supposedly, HoP is the right hand man of the captain. But a lot of people, including this PR, don't treat him like it. If HoP is really the right hand man of the captain, he should start with AA.

A right hand man doesn't mean an equal.

**Comment by PJB3005** [comment]
It's indeed true that HoP is traditionally in a weird spot: not having AA, but having everything to give themselves AA without trouble. I don't think it's anything worth fixing though.

**Review by GoodWheatley — APPROVED** [review]
After thinking about it for a while, I think the issues I brought up likely won't actually be a problem in the game, and this will be a good change once the issues PJB brought up are addresssed. I do have slight reservations about the potential nonexistence of the the HoP in the future, but I'll wait until the experiments are run to comment on that.

wheatley approved not ready to merge :godo:

**Comment by OldDanceJacket** [comment]
Why move in this direction of the ID terminal(with the suggested experiments of trying to remove the HoP) when you could instead add in the missing features of HoP instead? Allowing them to add in Jobs onto the manifest properly ala the **Plexagon HR Core** or do work on making paperwork better thanks to richtext?

**Comment by moonheart08** [comment]
> Why move in this direction of the ID terminal(with the suggested experiments of trying to remove the HoP) when you could instead add in the missing features of HoP instead? Allowing them to add in Jobs onto the manifest properly ala the **Plexagon HR Core** or do work on making paperwork better thanks to richtext? Do you see this PR interacting with either of those?

Because I want to experiment with giving the other heads more substance, first.

**Comment by deltanedas** [comment]
:rocket:

**Comment by tom-leys** [comment]
I really like this PR, I think it made the console much less OP.

Perhaps it's time to put this console in the office of other heads, like CE, Chief of Security, QM, etc. 

We might lock out the ability to change job titles from these consoles, though better would be that you can only change titles within your domain (CE can only change From engineers TO engineer titles, or move passengers into Eng).

**Comment by deltanedas** [comment]
in the 3 weeks its been merged i also really like it

i also agree that its probably time to start experimenting with giving heads consoles (and removing the board objective it was just piss easy already let alone with one in every department)

wrt names, maybe just make job changing command access and name changing hop access

**Pull request merged**
