### PR TITLE
Health alert tweaks

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Tweaks health alert sprites: now they have some text!

in order:
- good
- okay
- poor
- bad
- bad!

also fixes a bug where the last alert would not show.

## Why / Balance

hard for colorblind people to discern between the different alerts. The text should hopefully make it a bit easier.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The health alerts now have text to help discern how gravely injured you are.

### CODE REVIEW

**Comment by KidzAra** [comment]
The idea is interesting, but the text seems somehow superfluous.

**Comment by JoeHammad1844** [comment]
could you add an alert for full health?

**Comment by EmoGarbage404** [comment]
> The idea is interesting, but the text seems superfluous.

it is specifically designed for people with colorblindness, who find the current health icon difficult to read. The sole use of color is an accessibility issue and this will hopefully be helpful for those who need it.

**Comment by deltanedas** [comment]
> could you add an alert for full health?

that was removed for rp reasons i believe, "im 100%" etc

**Comment by BolloTea** [comment]
What if we made it a separate option so that a person with color blindness could select it in the settings themselves?

**Comment by Keikiru** [comment]
> What if we made it a separate option so that a person with color blindness could select it in the settings themselves?

Why? Giving the default more information redundancy is far better for accessibility and readability.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
