### PR TITLE
Donksoft guns & foam dart "refactor"

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Yet another Wheatley webedit pr smh

This PR not only adds Donksoft replicas of the L6, c20r, and Viper, but also makes foam darts proper bullets. I changed the parenting from BaseItem to BaseBullet, so darts will actually fly properly instead of going 1 tile ahead and skidding to a halt. Also added riot darts, modified foam darts which can stamcrit someone in 5 hits. I'm planning in the future once I've added some more Donksoft guns to add the replicas and riot darts to uplinks, so they'll be able to be obtained outside of admin shenanigans.

**Changelog**

:cl:
- tweak: foam darts are now proper bullets
- add: Riot darts, rubber-cored foam darts which do moderate stamina damage on hit (unobtainable for now)
- add: Donksoft LMGs, SMGs, and pistols are now in the game (unobtainable for now)

### CODE REVIEW

**Comment by retequizzle** [comment]
even unobtainable, i do not like the idea of toy weaponry being used to potentially disable other players via stamcrit, it seems excessively powergamey

**Comment by metalgearsloth** [comment]
Also we have beanbags so this just copies their functionality.

I'd also rather keep silhouetting as is because having to examine a gun to determine if it's the donksoft version or the regular version is silly.

**Comment by GoodWheatley** [comment]
> even unobtainable, i do not like the idea of toy weaponry being used to potentially disable other players via stamcrit, it seems excessively powergamey

Would reducing the stamina damage of the regular dart to 1 address this?

**Comment by CaptainSqrBeard** [comment]
Foam force! These guns are cool, but maybe they really must be more easily to determine. Like how it does cap gun - it have one blue pixel at end of the barrel.

**Comment by GoodWheatley** [comment]
can someone smarter than me look at this and tell me why tests keep failing

**Comment by Just-a-Unity-Dev** [comment]
YAML Linter says you may have added an additional space on the `smgs.yml`, tests are also failing because of it

**Comment by Just-a-Unity-Dev** [comment]
For the love of god Wheatley use a god damn text editor, not webedit

**Comment by moonheart08** [comment]
No webediting large PRs.

**Pull request closed without merging**
