### PR TITLE
Pet Carrier (Zookeeper gameplay?)

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Adds an animal carrier to the game. Big animals! Including humans.

The carrier can rarely be found in technical tunnels or can be pushared in cargo for 500$. It is an two-handed item, and yet works like drawers, allowing you to "swallow" 1 entity above it. Such as an animal, or other object.
The carrier can be welded to prevent living creatures from escaping from it.

Tests have been carried out: there is no possibility of being completely trapped in the carrier

## Why / Balance
Primarily created for the thief's new antagonist: [SCUM](https://github.com/space-wizards/space-station-14/pull/21520)
They will have a target on animal theft, and this item can help a lot with that. Also additional opportunities for traitors to sneak Ian (or other traitors) in covertly

## Technical details
While doing this seemingly simple PR, I came across the sudden horrors of combining EntityStorage and Item components, and maybe did a little dirt. Make sure it's a good one.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/4b53b8f8-f3f7-4022-b8ee-29d3b5d2a65d

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Animal carriers can now be found in the maintenance or bought in cargo. They are useful for carrying someone heavy in your arms.

### CODE REVIEW

**Comment by TheShuEd** [comment]
realized that this can be abused by assembling matryoshka dolls from players with players.

Most likely there is a need for a weight limit, the calculation of which has not yet been created.

**Comment by CatMagic1** [comment]
> realized that this can be abused by assembling matryoshka dolls from players with players with players...

test merge I wanna see this

**Comment by UbaserB** [comment]
I LOVE this so much, but why does it spawn in maint tunnels? Its a bit odd of a choice and i feel like its a better fit purchasable from cargo and spawns in zookeeper offices.

**Comment by TheShuEd** [comment]
Ok, add it to Cargo. Adding to Zookeeper offices its separate mapping PR

**Comment by UbaserB** [comment]
Another question, can other people open the cage while you hold it? If thats the case, its a bit unprotected.

**Comment by TheShuEd** [comment]
By the way, the carrying should be made two-handed, like a defibrillator!

**Comment by TheShuEd** [comment]
@UbaserB 
oh, I didn't check that.  if through the inspection menu you can press E on an item on another player, then most likely yes, you can

**Comment by TheShuEd** [comment]
image
Now it's two-handed!

**Comment by lzk228** [comment]
bluespace power:trollface:

**Review by Emisse — APPROVED** [review]

**Pull request merged**
