### PR TITLE
Cowtools worldwide

### PR DESCRIPTION
**Pull request by Tyzemol**
## About the PR
Moo!
(obviously intended for april first)

**Media**
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: due to a mistake during shipping, new NT stations have been supplied with the wrong tools!

### CODE REVIEW

**Comment by Emisse** [comment]
this one is very good

**Comment by deltanedas** [comment]
1. change branch from master to april fools
2. might be worth changing cow toolbox to have regular tools for extra funny

**Comment by Tyzemol** [comment]
yes all i did is swap the sprites, however when making the real cowtools be normal tools, i parented them to real normal tools (now renamed and reskinned to cowtools) so that they work as you would expect so they are exactly the same, no downgrades

**Comment by retequizzle** [comment]
works for me

**Pull request merged**
