### PR TITLE
Candles Crate

### PR DESCRIPTION
**Pull request by githubuser508**
## About the PR
Added a crate for candles that Cargo can order. 2 BoxCandle and 2 BoxCandleSmall for 500 spesos.

## Why / Balance
Candles are a fun little item that can be useful for Chaplain RP and just general vibes. They are consumable and, as far as I am aware, unrenewable at the moment. Reselling is a big loss; the entire crate would sell for 70 spesos.

## Technical details
yaml changes
- `Resources/Prototypes/Catalog/Cargo/cargo_service.yml` (added crate and price to Cargo's service list)
- `Resources/Prototypes/Catalog/Fills/Boxes/security.yml` (added crate fill for the candles crate)

## Media

candles2
candles1

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

There should not be any breaking changes. Hopefully.

**Changelog**

:cl:
- add: Candles crate and the ability for Cargo to order it.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
Thank you for your first PR! Codewise it looks good!

I think that candles are available in the Chaplain's vending machine and may be restockable that way? That being said, there is an argument to be made to have them directly orderable via Cargo instead of needing the restock box.

Either way you may want to stock the crate with the candle boxes instead of having them be lying freely in the crate.

**Comment by githubuser508** [comment]
Hello, thank you for the quick review! I didn't know about the candle boxes, and they do certainly look like the better implementation. I did a test and seems like the Chaplain vendor can't be restocked currently (tested the generic wardrobe refill box to no effect). But I'll probably save looking at the PietyVend and restocking that for another PR.

**Comment by Cojoke-dot** [comment]
500 for a few candles seems pricy(You can get 5 weh plushies for the same price). Maybe 2-3 boxes instead because candles tend to not last that long in comparison to the length of a shift.

**Comment by SlamBamActionman** [comment]
I think it all looks good; I would probably change the description slightly (it can be interpreted as 2 boxes total, rather than 2 large boxes & 2 small boxes) but that's all I can think of.

`Contains two boxes of candles, large and small. For atmosphere or something.`
to something like
`Contains two large and two small boxes of candles. For atmosphere or something.`

**Review by SlamBamActionman — APPROVED** [review]

**Comment by githubuser508** [comment]
I believe the check also needs to be rerun. I'm not sure if I can rerun tests myself.

**Review by SlamBamActionman — APPROVED** [review]
Good clean fun, I approve of this PR

**Pull request merged**
