### PR TITLE
make borgs obey AI

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
- gives borgs a law 0 that makes them obey the AI's orders
- moves emag to law -1
- makes emag law overrule other "you must obey x" laws

## Why / Balance
as far as i am aware, this has been a planned change for a while

might want to wait until AI has better options to deal with intruders into law upload

definitely needs a balance discussion

emag being law -1 might seem weird but i believe it's fitting for the emag being a machine-glitching device

## Media
image

after sus
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Borgs' default lawset now makes them obey the AI above all else.

### CODE REVIEW

**Comment by Ilya246** [comment]
drafting this because freeze, to be undrafted when it's known whether we want this

**Comment by slarticodefast** [comment]
Needs a design doc according to the freeze list #8524
grafik

**Comment by ArtisticRoomba** [comment]
If the AI has any laws that remove the prevention of causing harm (which happens often) the AI can just casually designate Borgs to hurt and kill organics under Law 0. It overrides all other laws.

To make this better the law should probably be moved down and add a clarifier "unless violating the (no harm/obey orders) laws" a design doc would be nice to see the argument as to how this would be better.

**Comment by Tyzemol** [comment]
One could argue there is a design doc already related to this, the [Moony's Better AI](https://github.com/space-wizards/docs/pull/160), that makes AI more of a head of borgs than just a door opener.
However that doc has existed for half a year by now i've no clue why it's still marked as a draft.

**Comment by VasilisThePikachu** [comment]
Please request for this PR to be opened after the freeze is over or remake it after. Thank you

**Pull request closed without merging**
