### PR TITLE
Makes noslips quieter.

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About the PR

Makes the noslip chameleon shoes mute the footsteps of the person wearing them. While they are not totally silent, if there's any ambiant noise they are effectively so.

## Why / Balance

Silent footsteps briefly came up as a bug a few days ago and I was surprised we didn't have a tot item for that already. Sneaky tot is now slightly sneaker, but if they wear them in public and any nearby sec are paying attention they could be caught out.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
https://youtu.be/M0J7ulJSitc

## Breaking changes

**Changelog**

:cl:
- add: The syndicate has started distributing padded footwear to their agents.

### CODE REVIEW

**Comment by lzk228** [comment]
then it becomes pretty obvious that this shoes is chameleon

**Comment by deltanedas** [comment]
same with noslips

**Comment by Emisse** [comment]
I think this should be combined with noslip. Makes them easier to identify for people paying attention but also makes the item stronger at the same time while reducing uplink bloat.

**Comment by keronshb** [comment]
> I think this should be combined with noslip. Makes them easier to identify for people paying attention but also makes the item stronger at the same time while reducing uplink bloat.

I highly disagree. By making footsteps quieter, this allows people to antag check for the item more easier.

Please separate it from noslips.

**Comment by LankLTE** [comment]
> I highly disagree. By making footsteps quieter, this allows people to antag check for the item more easier.

Noslips are consistently one of the best traitor items, so I really wouldn’t be opposed to having them be more obvious as a sort of downside while also being a useful upside. It’s also something you’re unlikely to notice in crowded areas or quick interactions so it’s not like it’ll insta-out you like a bloodred would.

**Comment by Hmeister-fake** [comment]
Maybe it would be better if you could buy a seperate item that silences footsteps like "Syndicate footwear pads" that you can insert into shoes so that you could hide them and not out yourself by accident for 1tc? They could also come with the chameleon kit.

**Comment by deltanedas** [comment]
people can validcheck for noslips by making a line of banana peels outside sec

**Comment by Hmeister-fake** [comment]
> people can validcheck for noslips by making a line of banana peels outside sec

Just pretend to walk over them instead of blindly running over peels

**Comment by deltanedas** [comment]
oops you forgot to hold shift now you are valid salad and the patrolman will kill you on sight

**Comment by LankLTE** [comment]
> people can validcheck for noslips by making a line of banana peels outside sec

don't really see how that's relevant to here other than saying there's already a, very niche and easy to counter, way to check for noslips.

**Comment by keronshb** [comment]
> people can validcheck for noslips by making a line of banana peels outside sec

There's a huge difference between someone actively playing in bad faith (your example) vs implementing something that people can use subtly as an antag check (this PR, even if it's not the main point of the PR)

**Comment by deltanedas** [comment]
ok well a simple solution is to have a verb to toggle sound so you can be sneaky when you want but not be valid at other times

**Comment by TemporalOroboros** [comment]
My original idea for avoiding getting checked by people was to just keep your old shoes. Swap as necessary.

**Comment by keronshb** [comment]
> ok well a simple solution is to have a verb to toggle sound so you can be sneaky when you want but not be valid at other times

That can be a possible solution. I know some servers have done a special check so if they had the antag datum they'd be able to see the switch but others wouldn't be able to.

**Comment by TemporalOroboros** [comment]
I personally don't like OOC mechanical checks like that so I'm not going to go that route for this PR.

**Comment by deltanedas** [comment]
yeah just have it visible to anyone like chameleon

**Comment by keronshb** [comment]
> I personally don't like OOC mechanical checks like that so I'm not going to go that route for this PR.

That's fine but it will definitely need some sort of toggle to help fight against antag checking.

**Comment by VektorZ1** [comment]
At 13 there is duct tape that can be used to make shoes quieter. I think it's more interesting than an antagonist-only item.

**Comment by hord-brayden** [comment]
I think there's fantastic potential here for improving noslips and sort of 'combatting' meta-gaming. I've seen sec try to test noslips when searching someone before and for various reasons, dehydration or a duffel bag and being loaded down, they won't slip on soap. I think watching them put their collective heads together to determine if something is slightly noisier than usual, would be rife with false positives and negatives and overall a major waste of their time. I see that as a win, personally.

**Comment by GeorgeGimme** [comment]
dam noslips are runed now im never buying em agan

**Comment by AJCM-git** [comment]
At this state it seems that we are not gonna be accepting these changes, the main problem seems to be that the slip cancellation and noise cancellation features should be separated, either by adding an uplink item to explicitly cancel sounds, adding a general purpose duct tape that helps cancel sound or another solution in the same mindset as those.

**Pull request closed without merging**
