### PR TITLE
AI Private radio channel

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

Adds the 'AI Private' radio channel, similar in scope to the one from SS13.
The channel can be accessed by the AI (duh) and by all intercoms.
Intercom hearing range is also increased a bit to allow the AI to actually eavesdrop.
## Why / Balance

The concept was suggested/discussed in #31906.
- Gives the AI some opportunities to listen in on the crew and get an idea of what's happening without needing them to use their headset. 
- Allows the AI to speak 'locally' to crew through an intercom without being heard by everyone on radio.
- Allows crew to communicate semi-privately with the AI, which may be useful in some situations. Messages sent via AI private also stand out compared to the constant flow of common radio messages, making requests made via the intercoms harder to miss.

## Technical details

The Intercom component has a new FreeChannels attribute, which indicates what channels it can be tuned to regardless of inserted encryption keys.
When created without encryption keys, the intercom will automatically try to tune in to AI Private instead of common, otherwise it will just use the first key (usually common).
## Media

ai

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: The AI can now use its own private channel to eavesdrop and communicate via intercoms.

### CODE REVIEW

**Comment by TheDoctor1977** [comment]
With this, we may also want to consider increasing the range of intercoms, because currently the way most intercoms are mapped requires you to basically stand directly next to them to be heard.

**Comment by deltanedas** [comment]
"private" channel someone can just turn on permanently to snoop on:

**Comment by Doru991** [comment]
> With this, we may also want to consider increasing the range of intercoms, because currently the way most intercoms are mapped requires you to basically stand directly next to them to be heard clearly.

Yes I did increase the hearing range of intercoms as the description says. I'm not sure if enough though

**Comment by TheDoctor1977** [comment]
> Yes I did increase the hearing range of intercoms as the description says. I'm not sure if enough though

I suppose it depends on where the intercoms actually are in the maps, and it definitely doesn't help there's not really a mapping standard for them. 4-5 tiles would probably be reasonable, but I'm just eyeballing it.

**Comment by Doru991** [comment]
It's currently increased from 2 to 4, but yes most maps don't really have them in consistent places because they're quite rarely used as anything other than free encryption key lootboxes.

**Comment by superjj18** [comment]
Part of me thinks that intercoms should be turned into poor man’s holopads, letting the AI “possess” one to hear and communicate like they were a sentient hydroponic tray

**Comment by Doru991** [comment]
I feel like if someone went and added all that extra functionality to intercoms it'd be better if they just added it to, well, actual holopads.

**Comment by Errant-4** [comment]
Could call it AI Direct, instead of Private?

**Comment by PJB3005** [comment]
Maintainer consensus seems to be that this implementation of the feature isn't very good, and it'd be better if we just had SS13's implementation. For those who are not familiar:

* Radio channels are all specific frequencies, common is 145.9 kHz and AI private is 144.7 kHz.
* Intercoms (and handheld radios) can just be set to any frequency in the range 144.1 kHz through 148.9 kHz, though it's in 0.2 kHz steps.
  * Channels with encryption keys still use this frequency system, but they're all below 144.1 kHz.
* AI private only really shows up around the uplink and core and is not really considered security critical because it's a fixed frequency.

This has some implications:
* You don't need to literally show a drop down in the intercom, meaning you don't have "AI private" in every intercom...
* Enterprising crewmembers or silicons can make a mostly-private radio channels by just using one of the open radio channels.
* The AI has 3 intercoms in its room that it can configure to anything. One of these is common, another is AI private, and another is unconfigured by default (IIRC?).

This enables many neat emergent game mechanics which this PR just doesn't have.

**Comment by Doru991** [comment]
This makes sense, and I agree it would be a better mechanic but since radio frequencies are currently only flavor text as far as I can tell, it would imply a heavy rework of the radio system (and all radio-enabled devices), which would be way beyond the scope of this PR. Feel free to close this for now, and if the future radio system rework doesn't include the AI channel I'll request for this to be re-opened.

**Comment by slarticodefast** [comment]
> Feel free to close this for now, and if the future radio system rework doesn't include the AI channel I'll request for this to be re-opened.

Allright, leave a comment when you want it re-opened. Thank you for your contribution.
Until the radio refactor is done #32711 should serve as a good alternative way for players to privately communicate with the AI without relying on intercoms.

**Pull request closed without merging**
