### PR TITLE
Syndicate surplus crates

### PR DESCRIPTION
**Pull request by Macoron**
## About the PR 
Add syndicate surplus (cost 20 TC, 50 TC content inside) and super surplus crates (cost 40 TC, 125 TC content inside). I just copied TC values from TG wiki, no idea how it will work with SS14 uplink pricing.

Still it good way to risk all TCs and get some good weapon bundle. Or pile of useless junk.

**Screenshots**

**Changelog**

:cl:
- add: Attention syndicate agents! We have found some old crates with random junk inside. We are ready to sell it for 20 telecrystals while content inside cost 50 telecrystals.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
125 TC worth of items for 40TC feels clinically insane.

**Comment by Snowyypanda** [comment]
> 125 TC worth of items for 40TC feels clinically insane.

it will force antag syndies learn to do teamwork if they want the good stuff

**Comment by EmoGarbage404** [comment]
Zombie bundle has just shown that a 40TC will be powergamed by 2 syndie players every single round. Allowing just 2 players to buy the national armaments of iraq with literally no downside (as you would most likely get everything you wanted) seems like it would only result in chaos.

**Comment by ScalyChimp** [comment]
> Zombie bundle has just shown that a 40TC will be powergamed by 2 syndie players every single round. Allowing just 2 players to buy the national armaments of iraq with literally no downside (as you would most likely get everything you wanted) seems like it would only result in chaos.

I think that's the point of the super surplus crate.

It's only a problem if it happens super often, which if it does, the price can be tweaked.

**Comment by EmoGarbage404** [comment]
What im saying is, it *will* happen super often. The fact that any syndie, at the beginning of a round, can roll the die to get random loot thats double the value of what he could otherwise get normally. Thats overpowered enough. The fact that 2 syndies, (which isnt that hard to arrange due to protect objectives) can get triple the value of loot from one purchase just further highlights the rediculous upsides of this bundle. It needs a significant TC nerf, imo.

**Comment by Peptide90** [comment]
Excuse my ignorance but do traitors know who the other traitors are at round start? If no that needs changed to code words then we have less traitor cooperating.

**Comment by ScalyChimp** [comment]
Isn't protect objective admin-only?, it is in ss13 iirc.

**Comment by EmoGarbage404** [comment]
Traitors don't know other traitors at start, but theres a protect objective that will inform you of one other traitor that you'll need to protect. Usually 1-2 players a round will have this objective. I personally have had rounds with 2 people i have to protect.

**Comment by Macoron** [comment]
Here is some rolls for super surplus crate. IMO it's balanced ok, because:
- You get incompatible items (no-slip shoes and magboots)
- You get dublicates (4 parapens)
- You just physically can't use all this weapon

Still, let admins/maintainers decide final TC prices.

Roll 1:
```
[INFO] root: syndicate hardsuit bundle
[INFO] root: nuclear authentication disk
[INFO] root: syndicate EVA box
[INFO] root: holoparasite box
[INFO] root: flashbang
[INFO] root: syndicate rubber stamp
[INFO] root: speed loader (.40 magnum)
[INFO] root: C-20r bundle
[INFO] root: soap
[INFO] root: black shoes
[INFO] root: energy sword
[INFO] root: C-20r bundle
[INFO] root: Predator
[INFO] root: pistol magazine (.25 caseless)
[INFO] root: cap gun
[INFO] root: Syndicate Smokes packet
[INFO] root: blood-red magboots
[INFO] root: box of .30 rifle bullets
[INFO] root: blood-red magboots
[INFO] root: composition C-4
[INFO] root: suspicious toolbox
[INFO] root: syndicate rubber stamp
[INFO] root: suspicious toolbox
[INFO] root: nuclear authentication disk
```

Roll 2:
```
[INFO] root: China-Lake bundle
[INFO] root: syndicate zombie bundle
[INFO] root: syndicate jaws of life
[INFO] root: pen
[INFO] root: syndicate hardsuit bundle
[INFO] root: C-20r bundle
[INFO] root: pen
[INFO] root: clarissa
```

Roll 3:
```
[INFO] root: Bojevic bundle
[INFO] root: box of .30 rifle bullets
[INFO] root: Predator
[INFO] root: clarissa
[INFO] root: pistol magazine (.35 auto)
[INFO] root: nocturine bottle
[INFO] root: pistol magazine (.25 caseless)
[INFO] root: speed loader (.40 magnum)
[INFO] root: mandella
[INFO] root: holoparasite box
[INFO] root: Predator
[INFO] root: clown costume duffel bag
[INFO] root: pen
[INFO] root: Syndicate minibomb
[INFO] root: flashbang
[INFO] root: C-20r bundle
[INFO] root: soap
```

Roll 4:
```
[INFO] root: syndicate rubber stamp
[INFO] root: health analyzer
[INFO] root: soap
[INFO] root: assistant ID card (assistant)
[INFO] root: cryptographic sequencer
[INFO] root: syndicate surgical duffel bag
[INFO] root: box of .30 rifle bullets
[INFO] root: Cybersun pen
[INFO] root: clown costume duffel bag
[INFO] root: black shoes
[INFO] root: energy sword
[INFO] root: soap
[INFO] root: Kardashev-Mosin
[INFO] root: syndie balloon
[INFO] root: Kardashev-Mosin
[INFO] root: syndicate EVA box
[INFO] root: syndie balloon
[INFO] root: pen
[INFO] root: pen
[INFO] root: composition C-4
[INFO] root: explosive grenade
[INFO] root: blood-red magboots
[INFO] root: flashbang
[INFO] root: Kardashev-Mosin
[INFO] root: composition C-4
[INFO] root: pen
[INFO] root: box of .30 rifle bullets
[INFO] root: black shoes
[INFO] root: blood-red magboots
```

**Comment by ScalyChimp** [comment]
> Traitors don't know other traitors at start, but theres a protect objective that will inform you of one other traitor that you'll need to protect. Usually 1-2 players a round will have this objective. I personally have had rounds with 2 people i have to protect.

That's a problem with the protect objective, not this pr.

**Comment by EmoGarbage404** [comment]
Theres nothing wrong with having to team and protect another player.

> > Traitors don't know other traitors at start, but theres a protect objective that will inform you of one other traitor that you'll need to protect. Usually 1-2 players a round will have this objective. I personally have had rounds with 2 people i have to protect.
> 
> That's a problem with the protect objective, not this pr.

There's nothing wrong with traitors working together and protecting each other. The issue is being able to effectively double the contents you could buy in a round.

**Comment by EmoGarbage404** [comment]
This will only get more unbalanced as more effective and useful traitor items are added.

**Comment by moonheart08** [comment]
> This will only get more unbalanced as more effective and useful traitor items are added.

The question is whether the traitors (plural) can effectively agree on and use the items given.
Different items require different strategies and this throws any pre-built strats out the window as you can't rely on it
I believe at minimum testing this out on live would be a good idea.

**Comment by BlitzGunner225** [comment]
If we want some funky but still useful results before it’s added there are a few ways to do it
One is to do some calculations but I’m doin something right now so I’ll say how well can do it later.

**Comment by mirrorcult** [comment]
lets see how this goes, it's a lot of TC but the fact that it isn't coordinated at all means its a lot more worthless than it looks

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
