### PR TITLE
Adds several new food recipes, including with organs!

### PR DESCRIPTION
**Pull request by naltee**
## About the PR

This PR adds several new food recipes that grant a use for ingredients the chef may come across, but have no way to use (save for deep frying) up until now. These ingredients include: slimeballs, Maintenance Peaches, skub (tastes like skub), fat, lemon-lime soda, bone, liver, stomach, hearts, lungs, and kidneys. In addition, these organs can now be butchered into food-ready versions, as a workaround for the variety of organs and lack of wildcard functionality in recipes. If I didn't do this, I'd need an exponential amount of variations for the same recipe, especially for HAGGIS NEMO ME IMPUNE LACESSIT.

## Why / Balance

This gives chefs the ability to use things that they might not be able to use otherwise, especially slimeballs and organs.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

Screenshot from 2024-03-30 16-13-23
Screenshot from 2024-03-30 16-16-50

Sprites are currently programmer art. Pull request pending as draft until proper spritework.

:cl:
- add: Chefs now have access to new recipes, utilizing a variety of ingredients that they may otherwise have no use for. No more deep fried organs!

### CODE REVIEW

**Comment by AjexRose** [comment]
The lemon lime items dont match the art of the game very well. Too photo realistic to be viable.

**Comment by FairlySadPanda** [comment]
So there might be a freeze on new chef recipes, as there's already a tonne

That said I fully support authentic cuisine from the British isles making it into the game, but notice that there's neither battered sausage, battered chocolate bar, OR chicken parmos represented.

**Comment by musicmanvr** [comment]
> So there might be a freeze on new chef recipes, as there's already a tonne
> 
> 
> 
> That said I fully support authentic cuisine from the British isles making it into the game, but notice that there's neither battered sausage, battered chocolate bar, OR chicken parmos represented.

What's wrong with adding more depth to what chefs can make?

**Comment by UbaserB** [comment]
> So there might be a freeze on new chef recipes, as there's already a tonne
> 
> That said I fully support authentic cuisine from the British isles making it into the game, but notice that there's neither battered sausage, battered chocolate bar, OR chicken parmos represented.

last i checked it was a restriction, no one's stopping you but you shouldn't PR new content when possible since it can be removed.

Either way, some of the sprites in this PR are weird.

**Pull request closed without merging**
