### PR TITLE
Applies multiple fixes to Reach and Dart maps

### PR DESCRIPTION
**Pull request by LittleBuilderJane**
## About the PR 
Fixes power related issues on both Reach and Dart as well as adds more Thrusters on Reach, Dart gets it's SMES fixed.
**Screenshots**

**Changelog**

:cl: Schiene
- add: Fixed Power issues on both Reach and Dart, Reach has more thrusters.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Try to keep PRs single purpose and not include changes for 3 maps in the 1 PR.

**Comment by LittleBuilderJane** [comment]
> Try to keep PRs single purpose and not include changes for 3 maps in the 1 PR.

I normally do, but I made all of this in the same Branch, so I was forced to make it 1 PR.

**Comment by metalgearsloth** [comment]
> > Try to keep PRs single purpose and not include changes for 3 maps in the 1 PR.
> 
> I normally do, but I made all of this in the same Branch, so I was forced to make it 1 PR.

You can cherry pick commits from 1 branch over to another branch, or alternatively make another branch and then soft reset back then remove the other maps.

**Comment by LittleBuilderJane** [comment]
> > > Try to keep PRs single purpose and not include changes for 3 maps in the 1 PR.
> > 
> > 
> > I normally do, but I made all of this in the same Branch, so I was forced to make it 1 PR.
> 
> You can cherry pick commits from 1 branch over to another branch, or alternatively make another branch and then soft reset back then remove the other maps.

Sooo...you want me to close this PR and do it without map or..?

**Comment by metalgearsloth** [comment]
just remove the other maps from this PR and put them on their own PRs.

**Comment by LittleBuilderJane** [comment]
> just remove the other maps from this PR and put them on their own PRs.

I removed the Commander from this, since it should be on it's own branch. I left the Reach and Dart patches in here.

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
