### PR TITLE
Add separate entities for ghost role mobs from the respective base mobs.

### PR DESCRIPTION
**Pull request by Veritable-Calamity**
## About the PR
Separated prototypes of creatures that have ghost roles into both their "AI" and "Ghost Role" variants. This is part of the SS14 Admin effort and closes https://github.com/space-wizards/space-station-14/issues/10442, when merged.

## Why / Balance
This creates a more streamlined (and easier to use) methodology to spawn in ghost-role mobs.

Additionally, some mobs did not have a method to add them without creating a ghost role.

## Technical details
No C# changes are needed in this PR.

## Media
image
Additional media will be attached as the PR approaches completion.

- [X] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
No breaking changes are expected at time of review. However, until this PR is complete some spawners will spawn a version of the mob that does not include a ghost role component.

**Changelog**
:cl:
ADMIN:
- tweak: Changed how some mobs are represented admin-side.

### CODE REVIEW

**Comment by Veritable-Calamity** [comment]
Not sure how c47e999 got into this branch, but it doesn't change anything compared to master.

**Comment by Veritable-Calamity** [comment]
It was probably the bad idea to start on this the day before I have a vacation planned, but expect to see more commits on this around the 1st of June.

**Comment by TheDoctor1977** [comment]
> Changelog
🆑
tweak: Changed how some mobs are represented admin-side.

There’s an admin-only changelog, that should probably be used here.
IMG_7819

**Comment by Veritable-Calamity** [comment]
Will be back to working on this on the 1st: I'm currently out on vacation.

**Comment by Veritable-Calamity** [comment]
> > Changelog
> > 🆑
> > tweak: Changed how some mobs are represented admin-side.
> 
> There’s an admin-only changelog, that should probably be used here. IMG_7819

Good catch. I was unaware that existed.

**Comment by Veritable-Calamity** [comment]
Hi all, I was on a mild hiatus. This will be continued when I get time to sit down and finish the PR.

**Comment by Veritable-Calamity** [comment]
Closing until I'm certain I have the time to work on this. My job has been hitting me pretty hard with time-consuming things that keep me from dedicating much time to this.

**Pull request closed without merging**
