### PR TITLE
Introduce balanced pipe stacking

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR
(cherry picked from commit 155404f8a07d19cb87f279e7fab03f1443cca7d6)
read https://github.com/Goob-Station/Goob-Station/pull/391 for all real details

fixes pipestacking but i guess you might want to set the variable to be normally true because realism or whatever

## Why / Balance
see parent PR

## Technical details
see parent PR

## Media
ok i'm genuinely not sure how to do this since i don't have uploading still (still waiting on my PC to arrive to do normal git shit), my phone is full of memory but i TRIED in the parent PR i can hire an underpaid russian worker to record it please fucking ask though

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
this breaks the economy-wait what do you mean code breaking changes  
none

**Changelog**
:cl: router
- tweak: Reintroduced limited pipe stacking. Beware of placement order, as you can't place smaller pipes overlaying large pipes doing the same thing - each new pipe must add a new flow direction to get anchored on.

### CODE REVIEW

**Comment by ImRenQ** [comment]
cool

**Comment by PJB3005** [comment]
Just code pipe layers instead.

**Comment by deltanedas** [comment]
when who codes it

**Comment by BasedUser** [comment]
you can do both pipe layers and stackmos for maximum autism, i would assume that it'd add new PipeDirections

**Comment by BasedUser** [comment]
oops wrong branch push

**Comment by PJB3005** [comment]
Maintainer consensus is that pipe stacking was never an intended game mechanic, and is also extremely unintuitive. You are effectively clipping pipes into each other here.

The issue of "atmos setups are too complicated" should be addressed with pipe layers, not this "feature".

**Comment by BasedUser** [comment]
Pipe layers aren't mutually exclusive to this PR being merged. I actually think the opposite, "atmos setups being too complicated" is an issue of UX, which isn't something pipe layers would solve (see: /tg/). To solve pipes being unreadable, you need enforcement of pipe colors across all of the playerbase, not some layering or magic stacking system - both layering and stacking have a visibility cost to them, yes, but the actual utility from it is justified.

This image is actually "readable", yes, but now imagine you have no pipe colors as is common with most of Atmos players. 


The maintainer team, it appears, also missed the point of this PR entirely, as it's to provide verticality on TOP of the existing pipes, as a CVar that anyone can change to false/true if balance/"""readability""" is to be preserved, this prioritizes downstreams and server hosts. To be blunt, people can choose to have stacking or not, so just disable it if it's such a burden on the game experience, that's why some people actually change **compatibility flags** in Doom and its sourceports.

Besides, it doesn't remove stacking restrictions entirely, making pipes act more like IRL manifolds - if you try to put a straightpipe on top of another straightpipe in the same direction, you will get a stacking error and an unanchored pipe, however, adding a different/additional direction will allow the pipe/device to be placed. This way, you can turn a pipe into a T intersection if you want to just fine, also addressing player skill issues of messing up some bullshit pressurized connection.

**Comment by Ilya246** [comment]
could implement funny special Atmos Glasses:tm: that color each pipenet randomly for you

**Comment by PJB3005** [comment]
> The maintainer team, it appears, also missed the point of this PR entirely, as it's to provide verticality on TOP of the existing pipes, as a CVar that anyone can change to false/true if balance/"""readability""" is to be preserved as is, this prioritizes downstreams and server hosts.

Our stance is that this "feature" is a bug, and we aren't adding compat flags to re-add bugs as they may be removed at any moment again.

**Comment by BasedUser** [comment]
Thank you for the transparency on this.

**Pull request closed without merging**
