### PR TITLE
Fill lockers with stuff

### PR DESCRIPTION
**Pull request by 20kdc**
+ Stuff in lockers (5d9cb36)
  + atmos/engineer/ce hardsuits, breath masks and oxygen tanks
  + chef can actually get meat (edit: via monkey cubes, a red crowbar for killing the monkeys, and a filled water spray bottle)
  + fix janitor closet misorganization
  + medical/medical doctor randomly can get latex gloves (they don't DO anything but they don't have to r/n)
  + ~~detective gets pen & 3 paper~~ Removed, see comments
+ ~~Adds monkey cube crates to cargo (dcca6bc)~~ Removed, see comments
+ ~~Saltern: Adds cargo ordering computer (bridge only has a requests computer) (31f8b36)~~ Removed, see comments

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
- Don't add anything to cargo, i'm doing that in #1835 
- Don't add hardsuits they don't do anything.
- We have a detective?

**Comment by Zumorica** [comment]
> * Don't add hardsuits they don't do anything.

They do work though. They protect you from high/low pressure.

**Comment by SweptWasTaken** [comment]
> 
> 
> > * Don't add hardsuits they don't do anything.
> 
> They do work though. They protect you from high/low pressure.

oh fug, do you have to have both helmet and suit for them to work

**Comment by Zumorica** [comment]
> > > * Don't add hardsuits they don't do anything.
> > 
> > 
> > They do work though. They protect you from high/low pressure.
> 
> oh fug, do you have to have both helmet and suit for them to work

Kiiiinda? They work differently than in SS13, right now wearing only one part protects you a bit, but not as much has having both. In the future I'll make the head part protect your head body part, and the rest protect your torso, etc.

**Comment by SweptWasTaken** [comment]
> 
> 
> > > > * Don't add hardsuits they don't do anything.
> > > 
> > > 
> > > They do work though. They protect you from high/low pressure.
> > 
> > 
> > oh fug, do you have to have both helmet and suit for them to work
> 
> Kiiiinda? They work differently than in SS13, right now wearing only one part protects you a bit, but not as much has having both. In the future I'll make the head part protect your head body part, and the rest protect your torso, etc.

Eventually when hotbars are added hardsuits will be one piece anyway, with the hotbar enabling you to toggle the helmet on and off.

**Comment by Zumorica** [comment]
> > > > > * Don't add hardsuits they don't do anything.
> > > > 
> > > > 
> > > > They do work though. They protect you from high/low pressure.
> > > 
> > > 
> > > oh fug, do you have to have both helmet and suit for them to work
> > 
> > 
> > Kiiiinda? They work differently than in SS13, right now wearing only one part protects you a bit, but not as much has having both. In the future I'll make the head part protect your head body part, and the rest protect your torso, etc.
> 
> Eventually when hotbars are added hardsuits will be one piece anyway, with the hotbar enabling you to toggle the helmet on and off.

absolutely.

**Comment by 20kdc** [comment]
So to be clear @SweptWasTaken : I should revert dcca6bc (i.e. add monkey cubes to cargo)?
Also, what about 31f8b36 (add cargo ordering computer to Saltern)?

I don't think there's a detective, but there is definitely a detective locker prototype and I figured putting something in there was, well, something.

**Comment by SweptWasTaken** [comment]
> 
> 
> So to be clear @SweptWasTaken : I should ~revert~ force-push-nuke on my end [dcca6bc](https://github.com/space-wizards/space-station-14/commit/dcca6bcf0e009ef4b05b081dc02808a9f17863b7) (i.e. add monkey cubes to cargo)?
> Also, what about [31f8b36](https://github.com/space-wizards/space-station-14/commit/31f8b3673d9b6318335d578fdc99d56be37693c3) (add cargo ordering computer to Saltern)?
> 
> I don't think there's a detective, but there is definitely a detective locker prototype and I figured putting something in there was, well, something.

Yes please. The detective locker prototype is a misnomer, it should just be called a closet since it's used in dorms, detective's office, the bar etc.

**Comment by 20kdc** [comment]
Force push that just happened was to remove the two commits that involved Cargo

**Review by Zumorica — APPROVED** [review]

**Pull request merged**
