### PR TITLE
Change alarm sound

### PR DESCRIPTION
**Pull request by Decortex**
## About the PR

Change alarm sound

https://github.com/space-wizards/space-station-14/assets/122426300/b4605963-02aa-425f-b077-a68070d3bc23

## Why / Balance

From annoying to cool sci fi sound
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: changed alarm sound

### CODE REVIEW

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Update attributions.yml in the folder to reflect the new license and source of the file please

**Comment by BolloTea** [comment]
Pressing and atmospheric sound - I like it.  Perfect for dark events or zombie mode

**Comment by Decortex** [comment]
> Update attributions.yml in the folder to reflect the new license and source of the file please

 updated 

> Also webedit _WOOP WOOP_ did you test your changes?

No. My pc broken

**Comment by VasilisThePikachu** [comment]
Looked a bit into pixabays TOS

Since this audio work was not published before January 9, 2019. This is not CC0 or CC-BY-NC-4.0

And is a nonstandard license. Which is most likely sadly not a choice.

I will let maintainers chime in instead about this.

**Comment by VasilisThePikachu** [comment]
btw just saying you dont have to mark your pr as draft every time you want to make a change. Just make your change

**Comment by Decortex** [comment]
> btw just saying you dont have to mark your pr as draft every time you want to make a change. Just make your change

Ok

**Comment by potato1234x** [comment]
why not use the one tg has it sounds much better

**Comment by Decortex** [comment]
> Looked a bit into pixabays TOS
> 
> Since this audio work was not published before January 9, 2019. This is not CC0 or CC-BY-NC-4.0
> 
> And is a nonstandard license. Which is sadly not a choice for a license.
> 
> I will let maintainers chime in instead about this.

So what they said about it?

**Comment by deathride58** [comment]
The license in attributions.yml is flat-out wrong, as the site you link *explicitly* states it to be licensed under Pixabay's content license. This content license is not at all CC-BY-NC-4.0

This license is, in turn, strictly incompatible with FOSS games, as per this prohibition outlined within:

image

(Basically, for a closed-source server, the usage is fine since there's no standalone distribution, but for a server that makes its source available, such as this one, the usage is outright forbidden.)

**Comment by deltanedas** [comment]
even closed source servers have to distribute the file to clients

**Comment by Decortex** [comment]
Well...

**Pull request closed without merging**
