### PR TITLE
Adds a flash kit and a specialized explosive kit to the uplink

### PR DESCRIPTION
**Pull request by asperger-sind**
## About the PR

This PR adds 2 new purchases to the uplink.

The bombkit, which includes a supermatter grenade, 2 whitehole grenades, a smoke grenade, an iron foam grenade, and a lube foam grenade. It costs 9 TC.

The flashkit, which includes 2 flashes, 2 flashbangs, one pair of sunglasses and a filled clusterbang, it costs 2 TC.
 
Removes flashbangs and supermatter grenades from individual uplink purchase.

This PR also includes a prototype for pre-filled modular grenades, including a base modnade, base reagent A and B and a base modnade payload. While adding 3 filled modnades, 1 for smoke grenades, 1 for lube grenades, 1 for iron foam grenades, which most likely can be re-used as mapping props.

TODO: kill the modnades and replace them with proper smokenades because deltanedas' pr merged

## Why / Balance

Supermatter grenades being available for individual purchase was pretty ridiculous considering that they're almost a flat upgrade to minibombs while the flashbang purchase was incredibly forgettable and terrible 3-year-old filler content that was never bought.

The kits are intentionally underpriced for now, imo the bombkit could be bumped to 10 or 12 TC if people find it too strong, not sure about the flashkit because it going for anything above 3-4 TC makes it an "ehh..." purchase.
## Technical details

The prototype for filled modnades is kind of a mess but I'm not really sure how it should be made if not like it is, also there are potential quantum storage concerns with the boxes from the kits because they are specified to have 12 storage units while still parenting from the generic box prototype, not sure how to fix this with the new storage system tho, aside from whitelisting specific items into the box.
## Media
https://github.com/space-wizards/space-station-14/assets/38016303/6dd4a003-1dca-4276-be46-d6f2276c35df

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A?
**Changelog**

:cl: BurninDreamer, Flareguy
- add: The flashkit and specialized explosive kit have been introduced and are now available at the traitor uplink for 2 and 9 TC.
- tweak: Supermatter grenades and flashbangs have been removed from individual uplink purchase.

### CODE REVIEW

**Comment by asperger-sind** [comment]
tests fail because god wills it i dont know?

**Comment by EmoGarbage404** [comment]
flashkit is fine but bombkit seems quite powerful. it's 9TC for what is currently like 14TC of actual loot. i'm not saying it's bad per se, just very strong. would want a second opinion.

**Comment by Hmeister-fake** [comment]
Bomb kit seems strong for 9 tc, but good where it stands as not many objectives would benefit from most of the grenades since their very specificed. 9 tc sounds fine, so does 2 tc for flash kit. One worry is with nukies i can imagine metal foam and lube spam would get pretty annoying, maybe bump the price up or remove it and add back seperate supermatter grenades for nukies?

**Comment by asperger-sind** [comment]
One worry is with nukies i can imagine metal foam and lube spam would get pretty annoying, maybe bump the price up or remove it and add back seperate supermatter grenades for nukies?

I could probably increase the price for nukies in specific but in hindsight I kind of want to see this.

**Comment by Hmeister-fake** [comment]
> I could probably increase the price for nukies in specific but in hindsight I kind of want to see this.

Yeah sure, as long as you can't buy 4 entire bomb kits and still have 4 tc left with one uplink

**Comment by JoeHammad1844** [comment]
the bombkit price is fine, its a quantity discount

**Comment by AJCM-git** [comment]
@asperger-sind are you coming back to this?

**Pull request closed without merging**
