### PR TITLE
Retexrute grass and dirt tiles

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR

Retexture grass and dirt tiles. Also replace texture of grass battleground

## Media

grassRetexture

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Ko4erga
- tweak: Grass and dirt tiles retexture.

### CODE REVIEW

**Comment by NotSoDana** [comment]
The way better, than what we have now

**Comment by IProduceWidgets** [comment]
Hmmm. I don't dislike them, but they also kind of feel like leaves.

**Comment by Ko4ergaPunk** [comment]
> Hmmm. I don't dislike them, but they also kind of feel like leaves.
> 
> Though maybe that's not true when they're not in isolation. That is usually the case with tile sprites.

Mmm... I can agree with you, but in-game that's looks normal. idk why :p 
I tried to use noise, but it's looks like pixel camouflage. I think it's better to leave it and don't change 
image
image

**Review by TheShuEd — APPROVED** [review]

**Review by Flareguy — CHANGES_REQUESTED** [review]
I'm not really a big fan of these. They feel kind of blobby and not very grass-like.

In general, I feel like these take a bit too hard after the Trials of Mana grass. Tiles are generally best when they have subtle detailing, and the use of the grass sprites we have right now (in my opinion) makes the grass biome feel a lot better ingame.

I think it might be better to just adjust the shade of it to match the foliage, and see how it feels. I won't stop you if you want to try to make something new, though.

**Comment by Ko4ergaPunk** [comment]
Жесть он крут

**Pull request closed without merging**
