### PR TITLE
Unanchored and unchored thrusters

### PR DESCRIPTION
**Pull request by lzk228**
fixes the problem that when rocket engines were ordered, the Cargo Shuttle's electrical grid overloaded and it couldn't fly.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

idk what to type in cl

### CODE REVIEW

**Comment by potato1234x** [comment]
thats pretty funny ngl

**Comment by metalgearsloth** [comment]
Isn't this going to cause issues with all the existing thrusters?

**Comment by Ilya246** [comment]
you could try adding a thruster/gyro crate prototype instead, same way containment field generators do it

**Comment by lzk228** [comment]
> Isn't this going to cause issues with all the existing thrusters?

yes

> you could try adding a thruster/gyro crate prototype instead, same way containment field generators do it

okay,then ill do it all later

**Comment by metalgearsloth** [comment]
Re-open if you come back to this.

**Pull request closed without merging**
