### PR TITLE
mini jetpack changes

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR 
Adds a mini jetpack crate to cargo's catalog. Fixes an air capacity bug and buffs the mini jetpack's capacity a little.

**Changelog**

:cl:
- add: A mini jetpack crate can now be found in cargo's ordering catalog.
- tweak: Mini jetpacks now have slightly more air capacity.
- fix: Fixed certain mini jetpacks having the capacity of a normal jetpack.

### CODE REVIEW

**Comment by mirrorcult** [comment]
why make them larger, i dont see the point, they're mini

**Comment by Scribbles0** [comment]
without using them as an internal tank (to breathe), mini jetpacks ran out in 35 seconds if you used them continuously pre-buff. the buffed ones are good for 3 minutes and 37 seconds of continuous use. if it needs to be changed, give me a timeframe and i can try to match the tank capacity to it, but this might make them a bit nicer to use instead of just always picking a normal jetpack.

**Comment by mirrorcult** [comment]
i suppose you could 2x or 3x it but the restriction on volume makes for more interesting gameplay imo (having to be wary of your fuel, switching it on and off constantly, etc)

**Comment by Scribbles0** [comment]
alright, i'll see if there's a volume that can fit those requirements

**Comment by Scribbles0** [comment]
these are the results i got after some testing, opinions? also i found a bug where because the empty mini jetpack did not have its volume set, it would use the volume of its parent, the base jetpack, which was 70. i'll implement a fix for it
5 volume: ~1:27
4 volume: ~1:10
3 volume:  ~52 seconds

**Comment by Scribbles0** [comment]
just committing my changes, also fixed the bug. not sure if it's a good fix, but it works

**Comment by joniroq** [comment]
> i suppose you could 2x or 3x it but the restriction on volume makes for more interesting gameplay imo (having to be wary of your fuel, switching it on and off constantly, etc)

You say "interesting", Salvage players say "laborious and unfun". At this point no one uses Mini Jetpacks and Salvage players will rush to get big jetpacks as soon as possible. Which depending on the competency of Cargo can take a while and even then some maps don't provide you with an air canister to refuel out the gate which means begging atmos for a spare; which they almost never do. It's common that it can take 10-15 mins _to even have the gear ready to actually do their job._

The only time mini's get used is by people who don't know better, followed by ":u My jetpack ran out I'm stuck in space, help please" shortly after.

and inb4 "just use fire extinguishers" I guarantee that if you bother to hunt down a water tank a cargo tech will have sold it while you're in space. Plus you can expend an entire extinguisher just trying to pull something heavy back.

**Comment by Scribbles0** [comment]
yeah, i wanted to make players actually consider taking a mini over a normal jetpack so it isn’t just “buy 2 jetpack crates so we can both have normal ones” which is why i thought 12 was a good volume

**Comment by civilCornball** [comment]
Heyyy, salvage player here. Currently writing my two cents, will finish within the hour. Just so ya know I’d be annoyed if you merged this before I can say anything.

**Comment by 0x6273** [comment]
I think increasing their capacity by 3x is too much. I play salv a lot and often use minis, and I like that their gameplay is different to regular jetpacks in that you have to be much more conscious about how much gas you're using.

**Comment by EmoGarbage404** [comment]
perhaps the jetpacks should be split up. Keep standard jetpacks for engineering and such while allocating mini jetpacks as the salvage tool. As for the capacity increase, that seems silly. It's a *mini* jetpack, the limited gas is a key concept.

**Comment by Scribbles0** [comment]
i was just thinking that 37 seconds was a bit too little compared to the regular jetpack's use time. i'll change the PR so that it fixes the bug and adds a separate crate for mini jetpacks as suggested.

**Comment by mirrorcult** [comment]
im fine with a separate crate but im also fine with increasing the mini jetpack capacity by a little bit. still should be outclassed by normal jetpacks but enough to be useful

**Comment by Scribbles0** [comment]
PR updated

**Pull request merged**
