### PR TITLE
Human-only Nukies

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR

Makes nukies human only.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: The Syndicate
- tweak: Nukies are now human-only.

### CODE REVIEW

**Comment by Stealthbomber16** [comment]
should really just make nukies use the player's race

**Comment by GoodWheatley** [comment]
> should really just make nukies use the player's current species

Making them all human is easier, people who play Diona for RP purposes probably don’t want to end up being a nukie

**Comment by metalgearsloth** [comment]
I want to play reptilian nukies

**Comment by asperger-sind** [comment]
Whilst I agree that the random specie system that was previously in place was annoying because it just forced you into a specific specie that might be flat out awful for combat (see: dionae) or into a specie you just don't want to play as,

but I don't think this change is a very good solution to the problem; it works as a band-aid because of how humans are balanced, but in the long run this should certainly be replaced with a system that allows you to select your specie manually upon spawn.

(And maybe **first** name to go along with a preset second name e.g: Jamiemyname Wabidiwabidiwabidi that'd go along for every other nukie.)

**Comment by EmoGarbage404** [comment]
I'm not opposed to this. Currently, species are in a very weird place balance wise, and are designed to interact in very specific ways with the station and crew. Nukies, being such a radically different gamemode, don't really make use of this. At best, some options become slightly more viable as certain species, but oftentimes you just have to deal with potential downsides to a species you didn't willingly pick.

While being able to pick your species on spawn could be a valuable trait, there's also merit in having all nukies be uniform (in this case, humans).

At the very least, I think this change is a good intermediate option considering the challeneges that might come from mid-round character/species selection.

**Comment by Just-a-Unity-Dev** [comment]
TBH if we want everyone in this scenario to win, nukies would preferably spawn as the actual player's character

**Comment by Visne** [comment]
Honestly feel like there shouldn't be such significant differences between species that this kind of stuff is necessary in the first place.

**Comment by EmoGarbage404** [comment]
> Honestly feel like there shouldn't be such significant differences between species that this kind of stuff is necessary in the first place.

I mean, there are enough differences for people to complain. Specifically with dionae, their traits are ill suited to frenetic combat. But, it's fair that at some point in the foreseeable future, there will be new species that could make this a reoccuring issue.

**Comment by Scribbles0** [comment]
to give my opinion, i agree with @EmoGarbage404 here. while letting people choose their own species for nukies could work well, it could also be a detriment if a species with significantly different mechanics appear. until we can get a solid idea of what we want with species, this works for now.

**Comment by potato1234x** [comment]
why doesnt it just take your character as the nukie? makes no sense to me

**Comment by Emisse** [comment]
out of scope of this pr

**Comment by PixelTheKermit** [comment]
This works, but is _really_ a band-aid. I think adding a blacklist/whitelist for some species would be the best option

**Comment by GoodWheatley** [comment]
> I think adding a blacklist/whitelist for some species would be the best option

That’s exactly what this PR does

**Comment by PixelTheKermit** [comment]
> > I think adding a blacklist/whitelist for some species would be the best option
> 
> That’s exactly what this PR does

why not allow lizard or slime nukies then?

**Comment by PixelTheKermit** [comment]
> TBH if we want everyone in this scenario to win, nukies would preferably spawn as the actual player's character

I feel like this would suck for RP

**Comment by DummeHytteOst** [comment]
it would be better to allow people to choose their species, than this, some players do want to play nukie as species other than humans, it makes for less interesting rounds if every nukie was a human.
making every nukie a human is just a boring and bad choice.

i am guessing this PR was made mainly because a few players don't like playing as diona nukie, which is fine each to their own, but it would ruin it for those who likes playing diona nukies.

most players just don't know the pros and cons of each specie and then claim that they are bad.

giving dionas 20~ more health would probably make them more accepted, and it would justify their increased mass and slowness.

**Comment by Just-a-Unity-Dev** [comment]
> > TBH if we want everyone in this scenario to win, nukies would preferably spawn as the actual player's character
> 
> I feel like this would suck for RP

elaborate? most ss13 servers already do it just with a randomized name

**Comment by PixelTheKermit** [comment]
> > > TBH if we want everyone in this scenario to win, nukies would preferably spawn as the actual player's character
> > 
> > 
> > I feel like this would suck for RP
> 
> elaborate? most ss13 servers already do it just with a randomized name

I guess it could work with a randomized name

**Comment by vulppine** [comment]
imo, i think having this pull from the player's current character (similar to how SS13 does it) would be the best way to go about it for now

**Comment by Scribbles0** [comment]
closing in favor of making nukie species pull from player characters

**Pull request closed without merging**
