### PR TITLE
Cigarettes now do very minor cellular damage

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Nicotine, which is the only reagent present in ALL cigarettes, now has a 2% chance to deal 2 cellular damage per .5u
This averages to about 14.4 damage per hour, so a 2 hour shift would bring you up to 28.8 damage, and a 7 hour shift would crit you.

## Why / Balance
Smoking kills, and this game does not sufficiently reflect that as of now.

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Smoking now causes mild lung cancer in the form of cellular damage.

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by Kadeo64** [comment]
"Surgeon General's Warning: Cigarette Smoking may be harzardous to your health."
-MG2:SS

**Comment by themias** [comment]
It seems my chain-smoking ass is getting removed from the round one way or another. 😭

**Comment by MACMAN2003** [comment]
not realistic, you should explode into a pile of gibs when you touch a cigarette :godo:

**Comment by deltanedas** [comment]
1 in x chance to be gibbed

**Comment by ArchPigeon** [comment]
nice RP punishment you've got there

**Pull request merged**
