### PR TITLE
Adds gingerbread men to the game

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds a non-roundstart gingerbread man race.
If this gets merged quickly enough they could maybe be temporarily made roundstart, but it is Christmas's Eve so I've opted not to turn that on.

## Why / Balance
Aleksh made these and I thought they would be cute to add, like a Christmas-y version of the skeletons.

## Media
Content Client_kevQ5J5X0L

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Flareguy. Aleksh
- add: Added gingerbread men. You may see them if the admins are feeling particularly jolly.

### CODE REVIEW

**Comment by Emisse** [comment]
can you make these roundstart for christmas, we can disable after christmas

**Comment by Emisse** [comment]
maybe we can let chef make gingerbread men in the future

**Comment by lzk228** [comment]
> maybe we can let chef make gingerbread men in the future

too much magic cooking without magic

**Comment by Emisse** [comment]
ok whatever its christmas we can kill thes later

**Pull request merged**
