### PR TITLE
upped the bandolier slots to 14 and made it function like an ammo box

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

I turned the bandolier into a BallisticAmmoProvider and upped the slots to 14. I also made a parent for this for future changes. 
## Why / Balance

The bandolier was too useless in the current state, being an extremely restricted belt. Sloth suggested I turned it into a BallisticAmmoProvider, since that was basically what it's function was anyways. Now it's more convenient to quickly reload your shotgun with a bandolier. 
## Media

https://github.com/space-wizards/space-station-14/assets/149967078/99bcec95-b45e-4e19-a569-98eb0293ad18

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: The bandolier now stores a maximum of 14 shotgun shells instead of 7.
- tweak: The bandolier now functions like an ammunition box for shotgun ammo.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Shouldn't this be an ammo provider.

**Comment by Boaz1111** [comment]
> Shouldn't this be an ammo provider.

what do you mean?

**Comment by Boaz1111** [comment]
oh.... do you mean like.... the magnum ammo boxes etc?

**Comment by Boaz1111** [comment]
> Shouldn't this be an ammo provider.

tried making it an ammo provider, caused all kinds of issues with duplication, visual issues, other bugs. So not gonna happen.

**Comment by metalgearsloth** [comment]
> > Shouldn't this be an ammo provider.
> 
> tried making it an ammo provider, caused all kinds of issues with duplication, visual issues, other bugs. So not gonna happen.

No other ammo storage uses storage component over ammoprovider and there's no reason for this to be an exception. Mobs don't need to be walking around with another 14 entities.

**Comment by Boaz1111** [comment]
> > > Shouldn't this be an ammo provider.
> > 
> > 
> > tried making it an ammo provider, caused all kinds of issues with duplication, visual issues, other bugs. So not gonna happen.
> 
> No other ammo storage uses storage component over ammoprovider and there's no reason for this to be an exception. Mobs don't need to be walking around with another 14 entities.

Sorry.... what do you mean?

**Comment by metalgearsloth** [comment]
If you want to bump bandolier it needs to use ammoprovider, the only reason it doesn't atm is because it was made before ammoprovider was a thing and not updated.

**Comment by NeviNovat** [comment]
Will this remove the SHIT + E shortcut for accessing the belt slot items? Thats how I used it.

**Comment by Aisu9** [comment]
shouldn't the shotgun cartridge be an ammo provider like EVERY OTHER ammo boxes?

**Comment by Boaz1111** [comment]
> shouldn't the shotgun cartridge be an ammo provider like EVERY OTHER ammo boxes?

The cartridge dispenser you mean? Yes, I do believe so, I'll check though

**Pull request merged**
