### PR TITLE
Adding a new Cryogenics reagent - Opporozidone

### PR DESCRIPTION
**Pull request by Gotimanga**
## About the PR
Added a new, cryogenics chemical for Chemistry to synthesize: Opporozidone. This chemical can reverse rot that has accumulated on patients making them revivable again, if used under the right conditions.
image

## Why / Balance
I fell that the only option for revival after the current time to rot (10 minutes) should not just be borging. This method will allow medics to reverse rotting in patients allowing them to be defibbed and revived - unlike cloning, you don't just hit a button and the patient is healthy either, you will still need to heal the patient afterwards.

In terms of balance, this chemical will require co-operation between regular medics, chemists, and botanists as well as cargo in terms of supplying plasma (It is consumed, not a catalyst) and Carpotoxin. It will also require some level of knowledge in terms of cryogenics and rotting. 

## Technical details
Added "MetaboliseWhileDead" data field to reagent prototype
Added  "ReduceAccumulator" method to RottingSystem

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Station 6 Medical Uni has released a new cryogenics chemical, Opporozidone. Its effects will reduce rotting in deceased patients

### CODE REVIEW

**Comment by LankLTE** [comment]
I’ve discussed in the past that I’m overall not a fan of rot being completely undoable, feel like it kind of makes dying more trivial (and dying is part of the game). That said I think this is probably a good way to go about it should it be done- it’s not trivial to do and takes a lot of cooperation.

**Comment by LordEclipse** [comment]
> I’ve discussed in the past that I’m overall not a fan of rot being completely undoable, feel like it kind of makes dying more trivial (and dying is part of the game). That said I think this is probably a good way to go about it should it be done- it’s not trivial to do and takes a lot of cooperation.

Also gives a good niche requirement for the Cryo pods, which are heavily underused.

**Comment by LankLTE** [comment]
> Also gives a good niche requirement for the Cryo pods, which are heavily underused.

I mean that could probably just be fixed by making cryoxadone work while dead.

I feel like this change is just going to even further encourage throwing bodies out the nearest airlock, or gibbing, both of which syndies already have a lot of methods to do.

**Comment by Holinka4ever** [comment]
> > Also gives a good niche requirement for the Cryo pods, which are heavily underused.
> 
> I mean that could probably just be fixed by making cryoxadone work while dead.
> 
> I feel like this change is just going to even further encourage throwing bodies out the nearest airlock, or gibbing, both of which syndies already have a lot of methods to do.

On every changelog, people will do diffrent stuff, to adapt to new mechanics/rules. Is that bad, that players will adapt to this? At this point, we just need to sit down and do nothing, because its only thing that preventing people to action not according to _curret plan_.

**Comment by Holinka4ever** [comment]
In my honest opinion, this pr is a thing, that medical always need.
Like, a lot of situations were you couldnt get enough time, to save a fella/patient due of rot.
And also actually nice show, how to make a departament friendship between chemistry and hydroponics, not by limiting, but adding more efficient aid!
 
Only thing is dissapoint me, that name is not showing that reagent is from cryo family.
I mean i understand that oppor- is short for opportunity, but -zine is from diffrent reagent family, though, the are effective at some point. What about to add -don to end?
Like Opporzinedon?

**Comment by Aisu9** [comment]
you could replace one of the chem in the recipe with cognizine, sure it will be a tad harder to make BUT you wont be able to cheese it completely with the recent nerf of koi bean mutation, unless botany is rocking 20+ trays dedicated for this cryo medicine

**Comment by Gotimanga** [comment]
@Holinka4ever, I'd be happy changing the name to Opporozidone.
I literally just ripped the name from Star Treck like most of the other chems in the game and that was the name that sounded coolest (despite the fact that in the show it's actually used to treat burns). Thanks for the suggestion

**Comment by Gotimanga** [comment]
> you could replace one of the chem in the recipe with cognizine, sure it will be a tad harder to make BUT you wont be able to cheese it completely with the recent nerf of koi bean mutation, unless botany is rocking 20+ trays dedicated for this cryo medicine

I'll think about this one

**Comment by potato1234x** [comment]
amazing pr

**Comment by Gotimanga** [comment]
> you could replace one of the chem in the recipe with cognizine, sure it will be a tad harder to make BUT you wont be able to cheese it completely with the recent nerf of koi bean mutation, unless botany is rocking 20+ trays dedicated for this cryo medicine

Replaced Sidelarc with Cognzine (I really liked the suggestion as it really fits what this chem is doing, it's even in the description). Since it's a little harder to make I've also buffed the time it takes off the rotting accumulator from 10 to 20, especially since when using cryogenics some of the medicine is wasted (The pod injects 1u/second while the body metabolises 0.5u /second so you'll probably heal past the rotting threshold and waste some meds)

**Comment by Gotimanga** [comment]
And removed ephedrine to save the chemists _some_ suffering considering they have to make Cog now :)
If anyone wants to give feedback on the current recipe, feel free, I'd love to hear what people have to think

**Comment by Subversionary** [comment]
> I’ve discussed in the past that I’m overall not a fan of rot being completely undoable, feel like it kind of makes dying more trivial (and dying is part of the game). That said I think this is probably a good way to go about it should it be done- it’s not trivial to do and takes a lot of cooperation.

Having a dedicated person to run around the station making notifying people of requirements is not making it "not trivial".
If relevant parties are presented with a task minute 0 of shift - reasonable quantities can be achieved by 30 minutes.

My 2 cents is that this chemical should not be supported by default and the cryo tube has to be upgraded by science before there could be any use for it.

**Comment by Gotimanga** [comment]
Re-opened as #24074

**Pull request closed without merging**
