### PR TITLE
Bloodloss drunk status no longer persists after being healthy AND dead bodies will still bleed

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

- Added a new function to drunk code; It can be removed entirely at any point.
- Added a new function to drunk code; a certain amount of time can be removed from the status.
- Drunk effect ends when blood level is healthy, instantly!
- dead bodies bleed
- dead bodies do not recover blood (lol)
- dead bodies do not take further bloodloss damage to prevent issues with revival gameplay down the line

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- fix: The drunk effect of having a low blood level is now instantly removed when healthy!
- add: Dead bodies will persist in bleeding after death!

### CODE REVIEW

**Comment by mirrorcult** [comment]
is 'drunkenness from low bloodloss' and 'drunkenness from actually being drunk' delineated between or can you cure being drunk by making yourself bleed and then healing it

**Comment by QuietlyWhisper** [comment]
> is 'drunkenness from low bloodloss' and 'drunkenness from actually being drunk' delineated between or can you cure being drunk by making yourself bleed and then healing it

fuck

**Comment by QuietlyWhisper** [comment]
That being said, bloodloss drunk effects stack with normal drunk effects, simply making it last longer overall...

**Comment by mirrorcult** [comment]
what i'd probably do is store how much drunkenness was added from bleeding on the component then just remove that much when you get healed

**Comment by QuietlyWhisper** [comment]
image
I think I could!

**Comment by QuietlyWhisper** [comment]
Ok the drunk portion of this pr is DONE! Now I just gotta shuffle this dead check around...

**Comment by QuietlyWhisper** [comment]
Should be done but I'd appreciate a code review because I cannot guarantee I did everything correctly. Everything seems to work as I want it to in testing!

**Review by keronshb — APPROVED** [review]

**Comment by keronshb** [comment]
Should be fine for now. Pulling bodies will be the preferable method in the future but we'll experiment with this for a bit.

**Pull request merged**
