### PR TITLE
Turn off handheld radios for now.

### PR DESCRIPTION
**Pull request by Pangogie**
Can we just uh... Ya...
Handheld radios have no purpose yet except to greatly annoying everyone in the round and cause headaches for admins.

### CODE REVIEW

**Comment by HoofedEar** [comment]
Would perhaps limiting the amount of radios someone can use at once be a better solution? Radios do serve a good purpose for being able to communicate across the station.

**Comment by Veritius** [comment]
It's handheld radios, which are used pretty much exclusively to scream into and clog up chat.

**Comment by Pangogie** [comment]
Oops ya, should've made that more clear. Edited title for clarity. HAAANNDDHELD radios.

**Comment by moonheart08** [comment]
Don't think this is necessary, add an admin button to turn off radios instead.

**Review by Peptide90 — APPROVED** [review]
50/50 on the execution but end of the day they're kinda useless till we get proper telecoms anyway.

If it cuts down on potential griefing which it will then I approve, and this is the least LOC way of doing it. Could have just commented it out though so it's noticable in future, maybe a TODO for tcoms?

**Pull request closed without merging**
