### PR TITLE
Major UI Improvement 

### PR DESCRIPTION
**Pull request by SpyDev14**
## About the PR
I've fixed Resizable for Fun, Cargo, Communication Console, improved the appearance of fax, cargo console, and particle accelerator. Fixed bugs and all that stuff. Now in the Russian localization, the particle accelerator menu does not become vertical. In short, I improved and upgraded a lot of things.

## Why / Balance
Initially, I was annoyed that I couldn't properly resize the communication console and it wasn't working properly, but then I went to fix everything I saw. Many menus in the Russian localization are broken, as the words in some places are forced to be much longer than in English. The cargo console is generally difficult to use! There was nothing to see, and the particle accelerator console looked like after the apocalypse

## Technical details
I cleaned up and cleaned all the files that I touched.

## Media
Below
Ps: I will also attach a few screenshots with RU localization before

**Changelog**
:cl:
- tweak: Cargo console reworked
- tweak: Fax menu reworked
- fix: fix PA console menu
- fix: fix Communication Console resizable
- fix: fix PowerCharge menu (Gravity generator)
- fix: fix shuttle map status-invalid locale

UIUpdate_CargoConsole

UIUpdate_CargoConsole-Huge
UIUpdate_CargoConsole-Low
UIUpdate_CommCons
UIUpdate_CommCons-Big
UIUpdate_Fax

UIUpdate_FixFTL
UIUpdate_PA

### CODE REVIEW

**Comment by VlaDOS1408** [comment]
> I'm going to need to see an actual PR description about the changes here.

Update

**Comment by lzk228** [comment]
you'll probably have to split up those things in smaller prs to getting reviewed faster
also please upload actual screenshots from wizden's build

**Comment by VlaDOS1408** [comment]
> you'll probably have to split up those things in smaller prs to getting reviewed faster
> also please upload actual screenshots from wizden's build

fk, lazik, where do you think I downloaded these screenshots from? Everything below the mark is for a general understanding of the picture. Everything above is relevant. Or are you confused by that 1 single screenshot from the corvax build? Well, I just forgot to take a stretched screenshot of the fax on wisden.

**Comment by MilenVolf** [comment]
> fk, lazik, where do you think I downloaded these screenshots from? Everything below the mark is for a general understanding of the picture. Everything above is relevant. Or are you confused by that 1 single screenshot from the corvax build? Well, I just forgot to take a stretched screenshot of the fax on wisden.

I agree with lzk. Please split up this PR so it will be easier to review the changes you've made. It got too many screenshots. I assume that the video format would be much preferable

**Comment by slarticodefast** [comment]
Yeah, this needs to be split up into one PR for each device. Not only for making the review easier, but also to reduce potential merge conflicts for forks who maybe have made changes to one of them.

**Comment by VlaDOS1408** [comment]
> Yeah, this needs to be split up into one PR for each device. Not only for making the review easier, but also to reduce potential merge conflicts for forks who maybe have made changes to one of them.

What categories do you want me to divide my work into?

**Comment by MilenVolf** [comment]
> > Yeah, this needs to be split up into one PR for each device. Not only for making the review easier, but also to reduce potential merge conflicts for forks who maybe have made changes to one of them.
> 
> What categories do you want me to divide my work into?
For example
`CargoProductRow.xaml` with `CargoProductRow.xaml.cs` in one PR, `CargoConsoleMenu.xaml` with `CargoConsoleMenu.xaml.cs`, etc.
xamls that were modified alone could also be in a separate PR, like `FaxWindow.xaml`

**Comment by VlaDOS1408** [comment]
i'm create a "Improve Cargo Console Menu", "Improve Fax Menu", "Fix Communication Console Menu", "Fix Particle Accelerator Menu" and "The long-awaited Shuttle Console Map tab locale". Okay?

**Comment by slarticodefast** [comment]
That would be perfect, thanks!

**Comment by VlaDOS1408** [comment]
How i can make this Pr was draft?

**Comment by slarticodefast** [comment]
grafik
Clcik on "Convert to draft" on the right side

**Pull request closed without merging**
