### PR TITLE
saltern senior and atmos removal

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
what will atmos do now that they dont have 5 mins of roundstart welding to do!!! :trollface:

### CODE REVIEW

**Comment by Emisse** [comment]
youll need to change ur proto next

**Comment by Anzarot121** [comment]
Oh, thank you! I hate this pump from tritium camera to distro. And fucjing volumetric pumps.

**Comment by deltanedas** [comment]
i already removed volumetric pump

**Comment by Anzarot121** [comment]
Yes, I'm see. I thanking you for this.

**Comment by potato1234x** [comment]
first time atmos player's nightmare

**Comment by deltanedas** [comment]
second time atmos players dream
maps having atmos removed is good because everyone just removes it roundstart anyway

**Pull request merged**
