### PR TITLE
kill target has to be human

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
no more pai/mouse kill targets
also eradicated linq from the condition

**Media**
will not pick pai see

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- fix: Non-humanoids such as mice and pAIs can no longer be kill targets.

### CODE REVIEW

**Comment by mirrorcult** [comment]
sad

**Comment by lzk228** [comment]
humanoid 🤓

**Comment by deltanedas** [comment]
tests not my fault :trollface:

**Comment by Emisse** [comment]
i think this pr SUCKS

**Comment by PixelTheKermit** [comment]
> tests not my fault :trollface:

Don't worry it's my fault

**Review by PixelTheKermit — APPROVED** [review]

**Comment by deltanedas** [comment]
fun but may as well not be an objective its guaranteed

**Comment by EmoGarbage404** [comment]
so glad i never have to kill `brain` again!

**Comment by deltanedas** [comment]
just juice brain unrobust noob noob fake unrobust

**Pull request merged**
