### PR TITLE
Recipe for cream

### PR DESCRIPTION
**Pull request by jimmy12or**
## About the PR
Renewable cream option!

## Why / Balance
Makes it possible for a chef to reduce milk into cream if they run low, or to make some for the bartender for other drinks.

## Technical details
Adds a recipe to make cream by heating up milk. 2u milk to 1u cream. A full large beaker of milk in a microwave will take the full 30sec time to heat up enough to reduce. Then put in a shaker and shake to Aerate the fluid and make it creamier.

## Media
Tiny bit of code, no need for media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Had an issue with left-over cream by-product when milk was used in any microwave recipe. Has been fixed by the addition of using a shaker.

**Changelog**

:cl:
- add: Added a recipe for cream. Heat some milk and shake some air into it.

### CODE REVIEW

**Comment by beck-thompson** [comment]
Felind players rejoice 😆

**Comment by Brandon-Huu** [comment]
Does this break any recipes that use milk in the microwave?

**Comment by jimmy12or** [comment]
> Does this break any recipes that use milk in the microwave?

In my tired state of submitting this, I forgot to test this to find out. This is certainly an important question and I thank you for asking it. Having now tested, I can say that it thankfully does NOT stop you from making any recipes in the microwave that use milk, however much like how eggs leave cooked egg as a byproduct whenever you do a recipe that uses raw egg, this one now leaves excess cream in the container if one is used such as a beaker.
   I will endeavor to fix this issue as best I am able.

**Comment by jimmy12or** [comment]
Should no longer conflict with any recipes unless a bar drink later needs hot milk for one of their depraved creations.

**Comment by jimmy12or** [comment]
Should be ready for review.

**Pull request merged**
