### PR TITLE
Ert names ops

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

ERT, CBURN and deadsquad operatives now will have new last names, mostly it's names of stars and constellations

## Why / Balance

looks cool
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
its too personal, these aren't characters the same way a regular player is. it also doesnt make sense militarily because you wont be referred to with your full name

**Comment by JoeHammad1844** [comment]
it also doesn't make sense to give them special last names because these are regular people, not a deviant art users special OC dont steal

**Comment by EmoGarbage404** [comment]
> its too personal, these aren't characters the same way a regular player is. it also doesnt make sense militarily because you wont be referred to with your full name

all of the first names are just "Corporal", "Sargeant", "Commander", etc. i think it's fine personally.

**Comment by JoeHammad1844** [comment]
being called by your rank and last name makes the most sense for a military, which the ERT is similar to

**Pull request merged**
