### PR TITLE
Fixed AI Actions

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

My other PR needs to get merged before this one https://github.com/space-wizards/space-station-14/pull/31799

AI Actions now work correctly.(Mass Scanner. Crew Monitor, Criminal Records)
~~Gave AI a Comms console.~~

## Why / Balance

Bugfixes mostly but also AI had comms in ss13.

## Technical details

Added missing components to the AI that allow it to use the monitors.

## Media

First image unrelated.
image
image
image
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Changed all shuttles to transmit their timer over Wireless instead of Private.
Screens now take info from the Wireless netId.

**Changelog**

for non-players: aghost's comms console now has a functional broadcast button.
:cl:
- fix: AI Actions now work.

### CODE REVIEW

**Comment by ScarKy0** [comment]
I wont be doing any fancy submodule action
You get the idea, this PR needs https://github.com/space-wizards/space-station-14/pull/31822 merged, but because idk how submodules work they share code or stuff, will fix when im eventually ready to move on from draft

**Comment by ScarKy0** [comment]
TODO: Figure out why AGhost and AI cannot broadcast via comms console

**Comment by ScarKy0** [comment]
> TODO: Figure out why AGhost and AI cannot broadcast via their comms consoles

Figured it out but im gonna pause work until other stuff gets merged in first

**Comment by ScarKy0** [comment]
> Figured it out but im gonna pause work until other stuff gets merged in first

I lied

**Comment by UbaserB** [comment]
so based!

**Review by metalgearsloth — COMMENTED** [review]
I'm not sure if you actually intended it to but this doesn't actually do anything with the actions.

**Comment by ScarKy0** [comment]
> I'm not sure if you actually intended it to but this doesn't actually do anything with the actions and doesn't fix their UIs.

This fixes that the consoles in the UI dont display any data when opened

**Pull request merged**
