### PR TITLE
feat: now when research is unlocked in console, approver of reasearch is radio-ed too

### PR DESCRIPTION
**Pull request by Fildrance**
## About the PR

Research console now is announcing who approved tech unlock.

## Why / Balance
It should be same as cargo requests. Also resolves internal conflicts when someone researches only what he wants for points that all team is bringing up (had some rounds where RD was not liking it and had to remove consoles from all scientists instead of just firing one dude).

## Technical details

Simple changes, ALMOST one-liner.

## Media

[emag_cargo.webm](https://github.com/user-attachments/assets/aaa59d9f-2a68-403f-8840-78d48970bf62)
[emag_research.webm](https://github.com/user-attachments/assets/465d4814-4098-4cb3-bc7a-4dd2b00a3b95)
[borg_is_logged.webm](https://github.com/user-attachments/assets/91868e7d-58a1-4013-86f4-651e836888b5)
[borg_name_in_consoles.webm](https://github.com/user-attachments/assets/4754b88f-0261-4c79-b0f0-ee1d2e69a9c7)

## Requirements

- [x ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: When research is unlocked in console the approver of the research is named.
- add: Borgs door access is getting logged now (and is accessible in Log Probe Cartridge)
- add: e-magged research and cargo consoles are not radio-ing any messages on research/buy confimation (for anyone)

### CODE REVIEW

**Review by slarticodefast — CHANGES_REQUESTED** [review]
Currently borgs show up with an empty name when they approve research because they have no ID. Do the same thing as in #30107 to fix that.
Also make the formatting for the name and job the same as there for consistency reasons.

**Comment by deltanedas** [comment]
should really have an event that access logs, comms, cargo, research etc all raise and borg handles it once

**Comment by slarticodefast** [comment]
>should really have an event that access logs, comms, cargo, research etc all raise and borg handles it once

Yeah, that would be even better. Avoids hardcoding the borgchassis into other sysems.

**Comment by Fildrance** [comment]
> should really have an event that access logs, comms, cargo, research etc all raise and borg handles it once

fixed. code related to access logs is wierd and required checkin property on id card... but oh well.

**Comment by Everturning** [comment]
I dislike this bc it makes it harder to hide that you're antag. What is the benefit of emagging a protolathe if you cant research the cool sec tech in secret. 
Right now if you research sec items then people will notice but there will still be an air of suspicion and suspense, and they'll have to figure out who and why it would be researched. This removes that rp possibility.

**Comment by Fildrance** [comment]
> I dislike this bc it makes it harder to hide that you're antag. What is the benefit of emagging a protolathe if you cant research the cool sec tech in secret. Right now if you research sec items then people will notice but there will still be an air of suspicion and suspense, and they'll have to figure out who and why it would be researched. This removes that rp possibility.

e-mag console and remove your id, then research- it will work and leave 'approver' blanc.

**Comment by Everturning** [comment]
> > I dislike this bc it makes it harder to hide that you're antag. What is the benefit of emagging a protolathe if you cant research the cool sec tech in secret. Right now if you research sec items then people will notice but there will still be an air of suspicion and suspense, and they'll have to figure out who and why it would be researched. This removes that rp possibility.
> 
> e-mag console and remove your id, then research- it will work and leave 'approver' blanc.

removing id will prevent you from researching. It's access locked.

**Comment by Fildrance** [comment]
> > > I dislike this bc it makes it harder to hide that you're antag. What is the benefit of emagging a protolathe if you cant research the cool sec tech in secret. Right now if you research sec items then people will notice but there will still be an air of suspicion and suspense, and they'll have to figure out who and why it would be researched. This removes that rp possibility.
> > 
> > 
> > e-mag console and remove your id, then research- it will work and leave 'approver' blanc.
> 
> removing id will prevent you from researching. It's access locked.

Not if u emag console, then any1 can do research

**Comment by SlamBamActionman** [comment]
You can also use a Radio Jammer, as the radio message originates from the console (if I recall) and turning the jammer on will prevent it from sending out a message.

At least it does for Cargo. I've ordered contraband stuff right under QM's nose this way.

**Comment by Fildrance** [comment]
> You can also use a Radio Jammer, as the radio message originates from the console (if I recall) and turning the jammer on will prevent it from sending out a message.
> 
> At least it does for Cargo. I've ordered contraband stuff right under QM's nose this way.

If this is not working with research console - file issue and i'll fix it separately : >

**Comment by IProduceWidgets** [comment]
I think it needs some player feedback if you cant hear the radio. Like a popup over the console or something.

**Comment by Fildrance** [comment]
> I think it needs some player feedback for if you cant hear the science radio. Like a popup over the console or something.

that sounds reasonable, but again, separate issue - as it is required for all consoles, and is not connected to original problem not getting researcher in radio message. Fila an issue, link it, POSSIBLY will fix it... lets not feature creep this thing, lets merge it  without possibly breaking massive changes <_<

**Comment by SlamBamActionman** [comment]
Hello! This PR was put up to a maintainer vote with the result: Merge.

Ensure that it works after the merge conflict is resolves. I'm also curious of how the message is handled when the console is emagged and used by someone without an ID. Ensure it doesn't just go "researched by .", it would look a bit weird.

**Comment by Fildrance** [comment]
Changed emag consoles (cargo and research) to not output messages. I tested it (see media)

**Pull request merged**
