### PR TITLE
AI is properly connected to the power network.

### PR DESCRIPTION
**Pull request by Mervill**
## About the PR

Quick fix that gets the AI connected to the power network.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: AI is properly connected to the power network.

### CODE REVIEW

**Comment by Errant-4** [comment]
What does this _mean_? Does this change it's gameplay behaviour if power is lost?

**Comment by Mervill** [comment]
Right now the AI dosen't actually die when it looses power. I suppose I could also go in and add that but I was concerned I might be stepping on someone's toes. At the moment it's just kindof odd that it's permanently marked as `unpowered` despite the AI obviously being alive.

I don't know if moony's doc ever touched on power loss mechanics but I think it's generally assumed that the AI dies without power. This at the very least is a step toward that.

**Comment by Mervill** [comment]
actually it does look like it's supposed to at least disable the eye when you loose power but it dosen't seem to work properly

**Comment by EthanQix** [comment]
> Right now the AI dosen't actually die when it looses power. I suppose I could also go in and add that but I was concerned I might be stepping on someone's toes. At the moment it's just kindof odd that it's permanently marked as `unpowered` despite the AI obviously being alive.
> 
> I don't know if moony's doc ever touched on power loss mechanics but I think it's generally assumed that the AI dies without power. This at the very least is a step toward that.

Honestly if the intended behavior was for AI to die when they lose power, no AI would survive past the 5 minutes mark...

**Comment by nymhole** [comment]
if this is true, ai should have an emergency battery that can be replaced by crew. this is because the emergency SMES can be distrupted by in-round events, and the ai should have some time to react. ai also needs the ai-interactable turrets found in space station 13. 

upon further inspection this PR just adds the functionality of unpowered/powered and no actual use for it, which is absolutely a step in the right direction but also might be added in another PR.

**Comment by SaphireLattice** [comment]
> I don't know if moony's doc ever touched on power loss mechanics but I think it's generally assumed that the AI dies without power. This at the very least is a step toward that.

That specific document, if I am reading things right, proposes an AI that is basically an "infomorph". In that version the AI has no single central component, brain or core that can be taken out, and instead it runs based on having enough machines contributing "compute" to sustain its existence. Though in practice most of that "compute" does comes from a single source - the AI core (or I imagine "AI server room" with bunch of generic "compute" giving machines that aren't core)

Either way, without power AI should have some sort of backup battery for full operation and/or battery-powered emergency sleep mode that's basically a crit state.

**Comment by Mervill** [comment]
Someone will fix this when AI needs interacts with power properly

**Pull request closed without merging**
