### PR TITLE
Fix cutters and screwdrivers in lathes

### PR DESCRIPTION
**Pull request by InverselyKinematic**
## About the PR

Fixes the appearance of wirecutters and screwdrivers in lathes.
It was previously just the color mask.
It MIGHT break stuff that relies on the first sprite layer, but both still displayed colors correctly so it should be fine.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: fixed wirecutters and screwdrivers appearing incorrectly in lathes

### CODE REVIEW

**Comment by Menshin** [comment]
Hasn't this been fixed by #15706 ?

**Comment by InverselyKinematic** [comment]
FUCK

**Comment by deltanedas** [comment]
pro

**Comment by Menshin** [comment]
> guess no pr :despair:

https://github.com/space-wizards/space-station-14/issues/15839 should be accessible if you want to begin contributing.

**Comment by InverselyKinematic** [comment]
ill check that out later

**Pull request closed without merging**
