### PR TITLE
wait for event startAfter before running event

### LINKED ISSUE #10153: VentClog event will trigger foam instantly
## Description
VentClog event will trigger foam instantly. It used to give long delay, enough to get away from vents into maintenance, warn people over radio about foam, question whenever that was FalseAlert, walk back and die to foam.

**Reproduction**
- Stand next to vent
- addgamerule VentClog
- Die

**Additional context**
Probably introduced by PR #9589.

### PR DESCRIPTION
**Pull request by JustinTrotter**
## About the PR 
Fixes #10153

This issue affected all delayed start events, including Kudzu and Meteor Swarm.

The refactor #9589 fires the events based on the startAfter timer. However, the GameTicket.GameRule was firing them immediately if the round had already started. Removing this call allows for the StationEventSystem to do its job properly.

**Screenshots**

**Changelog**

:cl:
- fix: events with intended delay no longer start immediately after they are announced

### CODE REVIEW

**Comment by metalgearsloth** [comment]
I haven't playtested ingame but this doesn't seem like it would fix the random ventclog?

**Comment by mirrorcult** [comment]
this doesnt fix the issue, this is only relevant to the `addgamerule` command which is not invoked by the basic event scheduler

**Comment by JustinTrotter** [comment]
> this doesnt fix the issue, this is only relevant to the `addgamerule` command which is not invoked by the basic event scheduler

It does fix this issue though. I  tested it just now (I hacked various settings and turned events on in sandbox, removed all other events, and tweaked the configuration in order to make it schedule to fire after the first 10 seconds) and it works fine.

Please look at `Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs` `line 106`

The BasicStationEventSchedulerSystem was refactored to use `addgamerule` as part of its update.

**Comment by metalgearsloth** [comment]
> > this doesnt fix the issue, this is only relevant to the `addgamerule` command which is not invoked by the basic event scheduler
> 
> It does fix this issue though. I tested it just now (I hacked various settings and turned events on in sandbox, removed all other events, and tweaked the configuration in order to make it schedule to fire after the first 10 seconds) and it works fine.
> 
> Please look at `Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs` `line 106`
> 
> The BasicStationEventSchedulerSystem was refactored to use `addgamerule` as part of its update.

That code path doesn't go through the command?

**Comment by mirrorcult** [comment]
> The BasicStationEventSchedulerSystem was refactored to use `addgamerule` as part of its update.

i'm aware, i wrote that refactor. that doesn't go through the command, which is what you updated. looking at the issue its only relevant to `addgamerule` which was an intended thing.

**Comment by JustinTrotter** [comment]
I see, I've made some wrong assumptions. Tested just now on master and it's a non-issue. The scheduled event fires correctly on master. Sorry for the fuss.

**Pull request closed without merging**
