### PR TITLE
Changes the chatbox to be more consistent with SS14's UI

### LINKED ISSUE #4136: Chatbox UI is not consistent with the rest of the games UI
## Description

Chatbox UI uses rounded buttons when everything else uses the slanted button design.

**Screenshots**

Content Client_2021-06-04_20-23-34
firefox_2021-06-04_20-23-55

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Closes #4136.

Mostly a test PR just to see what people think of this. The rounded buttons don't fit the rest of SS14's UI so I changed some stuff around. Open to suggestions. 

I also changed the chat-bar text to be less wordy.

I think the button on the channel change are a bit wide on the l/w so will change those too.

**Screenshots**

Before
Content Client_2021-06-04_21-07-58
After
Content Client_2021-06-04_21-03-22

Before
Content Client_2021-06-04_21-08-03
After
devenv_2021-06-04_21-03-15

**Changelog**

:cl: Swept
- tweak: Changed chatbox UI to be more consistent with SS14's UI

### CODE REVIEW

**Comment by Ygg01** [comment]
Looks good to me swepotoroni.

**Comment by ShadowCommander** [comment]
I feel like the current channel selector (the green one) should be a bit smaller, since without the rounded corners the space it looks like it takes up is larger.

If possible it would be nice to add angles to the selectors on the bottom, since the design from what I understand is to indicate buttons by the color and shape.

How does the filter button look with angled corners?

**Comment by SweptWasTaken** [comment]
> 
> 
> I feel like the current channel selector (the green one) should be a bit smaller, since without the rounded corners the space it looks like it takes up is larger.

Agreed

> 
> If possible it would be nice to add angles to the selectors on the bottom, since the design from what I understand is to indicate buttons by the color and shape.

I agree but the way the chatbox is written there's no way to give individual StyleCases to the buttons on the bottom.

> 
> How does the filter button look with angled corners?

Bad. Trust me.

**Comment by ShadowCommander** [comment]
Maybe just make the bottom buttons regular angled buttons?

**Comment by RemieRichards** [comment]
local needs the leftside slant, and console needs the rightside slant

**Review by RemieRichards — CHANGES_REQUESTED** [review]
local needs the leftside slant, and console needs the rightside slant

**Comment by clement-or** [comment]
I've always preferred rounded buttons, as plain square buttons have a "prototype" look that doesn't look great. Also, use some padding and margin, more room makes the ui breathe more and also allows more room for error.
Not a fan of those changes at all

**Comment by SweptWasTaken** [comment]
> 
> 
> local needs the leftside slant, and console needs the rightside slant

Not really sure what to do about getting the first and last channel selector button from the list and modifying their StyleClass.

> 
> 
> I've always preferred rounded buttons, as plain square buttons have a "prototype" look that doesn't look great. Also, use some padding and margin, more room makes the ui breathe more and also allows more room for error.
> Not a fan of those changes at all
> 
> EDIT : Also slanted buttons are a nightmare to work with from a designer's perspective, you can't stack them properly, padding and margins become weird and it makes a lot of unused space. If it were me I would completely yeet them from SS14's ui

I'm on the opposite side of things. I think rounded stuff looks dumb and cheap. But it's subjective.

**Comment by SweptWasTaken** [comment]
If anyone has any interest in salvaging the works in this PR and applying reviews let me know otherwise i'm going to strip the other stuff and merge the filter and chatbar text changes.

**Pull request merged**
