### PR TITLE
Added Basic Parts Technology

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Added parts technology into the R&D console
**Screenshots**

image
image

**Changelog**

:cl: Seth
- add: Added basic parts technology

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Research is liable to change so pointless adding this IMO, especially if we go with experisci.

**Comment by SethLafuente** [comment]
> Research is liable to change so pointless adding this IMO, especially if we go with experisci.

eh it won't harm adding it so is easier to make machines like the protolathe and autolathe chips on RD's locker

**Comment by metalgearsloth** [comment]
but it's gonna be nuked soon anyway?

**Comment by SethLafuente** [comment]
> but it's gonna be nuked soon anyway?

how soon is soon?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Alphabetise and it'll be merged.

**Comment by metalgearsloth** [comment]
You coming back to this?

**Comment by SethLafuente** [comment]
> You coming back to this?

I’m currently on a trip and I have no computer near here so I will later 

welp I guess it got merged?

**Pull request merged**
