### PR TITLE
New lobby art : Blueprint

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

image

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: data_redacted
- add: New lobby art (of an Air Alarm blueprint).

### CODE REVIEW

**Comment by tutoumi** [comment]
Very cool art

**Comment by JoeTheJanitor** [comment]
‘Nanotransen’ now canon!
(It says ‘nanotransen electrical division’, and is misspelled in the syndie note, though the second makes some sense)

**Comment by PJB3005** [comment]
Could you save it as a WebP instead after #25184? The image is 2.2 MB and it could be a lot smaller.

**Comment by IData-RedactedI** [comment]
I'll see what I can do


> Could you save it as a WebP instead after #25184? The image is 2.2 MB and it could be a lot smaller.

I'll see what I can do

**Comment by VasilisThePikachu** [comment]
All you need to do is drop the current png in krita (or any of your favourite image software should be able to do this). Export as webp. When it asks you for quality. Just put it to 99% and use this as the file.

**Comment by UbaserB** [comment]
> Could you save it as a WebP instead after #25184? The image is 2.2 MB and it could be a lot smaller.

saved, and added the file changes in advance for when the PR gets merged so there should be no merge conflict

**Review by VasilisThePikachu — APPROVED** [review]
Looks ok to me

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
