### PR TITLE
Removes Spaceacillin

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

why does this shitass chem exist

suture crafting recipe uses cryptobiolin since it'd be useless otherwise

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Lank
- remove: As disease has been eradicated, Spaceacillin can no longer be created or found. 
- tweak: Creating medicated suture now required Cryptobiolin in place of Spaceacillin.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Missed a duffel fill

**Comment by LankLTE** [comment]
> Missed a duffel fill

whoever put spaceacillin in that duffel bag is dead to me

**Comment by hord-brayden** [comment]
I like it as a poison, genetic damage is a helluva thing. Probably shouldn't be laying around but nixing it means we may never get it back again, and it makes me sad.

**Comment by LankLTE** [comment]
> I like it as a poison, genetic damage is a helluva thing. Probably shouldn't be laying around but nixing it means we may never get it back again, and it makes me sad.

it does one damage per unit, I don't really see how it's even remotely a useful poison

**Comment by UbaserB** [comment]
Instead of removing it entirely, why dont we make it slightly slow dow the zombie virus?

**Comment by OctoRocket** [comment]
Why would you make it over just place anti-zombie meds?

**Comment by LankLTE** [comment]
> Instead of removing it entirely, why dont we make it slightly slow dow the zombie virus?

What's the point? Ambuzol is easier to make and gets rid of it entirely (on top of not doing cellular damage) 

also test fail is unrelated

**Comment by UbaserB** [comment]
oh yeah true

**Comment by EmoGarbage404** [comment]
I have a great solution

**Pull request merged**
