### PR TITLE
Solutions on thrown spears/shot arrows

### PR DESCRIPTION
**Pull request by drteaspoon420**
Spears inject their solution on thrown hit.
Arrows now have 5u solution storage that is injected when it hits target.

## About the PR

Spears now also inject their solution when thrown instead of just when hit in melee.
Arrows can be now also be given chemicals (5u) that they inject when they hit a target.

## Why / Balance

Spear thing is just mechanical consistancy thing.
Arrows is more for thematic consistancy where make shift weapons are these wierd things you MacGyver together.

## Technical details

Spear has been given 'SolutionInjectOnCollide' component (only used by tranq 50. cal shotgun shells so far).
Arrow has been given `SolutionContainerManager`, `RefillableSolution`, `InjectableSolution`, `SolutionInjectOnCollide` and `SolutionTransfer` components.

## Media

[poison_tribal.webm](https://github.com/space-wizards/space-station-14/assets/87363733/cfca56ef-2f28-4c8b-bcd6-42a212f957bd)

[poison_tribal2.webm](https://github.com/space-wizards/space-station-14/assets/87363733/8edbf92c-2391-4d00-8e9e-8b05d3445813)

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: DrTeaSpoon
- tweak: Arrows can now be doped with chemicals.
- fix: Spears now correctly transfares chemicals when thrown.

### CODE REVIEW

**Comment by deltanedas** [comment]
licoxide arrow homemade taser real
i think thrown spear didnt inject solutions due to balance concerns

**Comment by drteaspoon420** [comment]
From quick search, I did not find even discussion about it.
In discord any discussion related to it is just people complaining when they discovered that it doesn't work.

**Comment by deltanedas** [comment]
ok i double checked the embedding pr it doesnt mention solution so idk

**Comment by mirrorcult** [comment]
there are sprites included in the arrow RSI for a reagent overlay

**Comment by JoeHammad1844** [comment]
another step towards the syringe gun

**Comment by metalgearsloth** [comment]
Might be sussy but will see, at least spears break.

**Comment by drteaspoon420** [comment]
[poison_tribal2.webm](https://github.com/space-wizards/space-station-14/assets/87363733/8edbf92c-2391-4d00-8e9e-8b05d3445813)
Visuals

**Comment by drteaspoon420** [comment]
I believe this PR is ready, unless someone has complaints/concerns.

**Comment by deltanedas** [comment]
a bug i found with visuals is that it doesnt get removed once the poison is all injected, it keeps the overlay even though its empty when edit solutions is used

**Comment by drteaspoon420** [comment]
I look into fixing that.

**Comment by EmoGarbage404** [comment]
that's more than likely an issue with solutioncontainervisuals

**Comment by Slava0135** [comment]
fun fact: arrows reflected with esword/shield would still inject

**Comment by deltanedas** [comment]
i dont think arrows or spears should be reflected since laser is le energy or something, bullets are tiny but a big spear would be too big or something

**Pull request merged**
