### PR TITLE
Add Bomber Jacket to ClothesMate

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About the PR

Babies first SS14 PR, lets see if I did it right, or if I have to instantly close this, woooo.

Update: All I wanted to do was add a jacket to the ClothesMate, why am I delving into the economic status of the NT fabric industry.

**Media**

Content Client_PEBE3IBSou

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: added bomber jackets to clothesmate vendor
- del: removed bunny and cake hat from clothesmate
- tweak: moved bowler hat to bardrobe

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
pr is fine but do we *really* need more clothing shoved in the clothesmate? it'd be nicer to have some stuff that could be used to populate maps.

**Comment by metalgearsloth** [comment]
Clothesmate has too much stuff in it, see https://github.com/space-wizards/space-station-14/issues/12462

**Comment by EmoGarbage404** [comment]
> Clothesmate has too much stuff in it, see #12462

can i just go webedit remove all the funny items?
i think this should be in there, at the very least.

**Comment by EmoGarbage404** [comment]
just remove the funny hats

**Comment by Jackrost** [comment]
It's good to discuss ideas in discord with main devs. Less work to do if your ideas have an issue

**Pull request merged**
