### PR TITLE
Add examine string for starving entities

### PR DESCRIPTION
**Pull request by MisterMecky**
## About the PR

Adds an examine string for entities that are currently starving

Allows for easier identification of people who are dying from starvation.

**Media**

https://github.com/space-wizards/space-station-14/assets/62370007/aaaadcf5-0d66-4e95-928c-deb9298e9cef

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Mobs can be examined to see if they are currently starving.

### CODE REVIEW

**Comment by lzk228** [comment]
nahhh

**Comment by EmoGarbage404** [comment]
I feel like this is just a bandaid to starving indicators not being very good.

**Comment by MisterMecky** [comment]
> I feel like this is just a bandaid to starving indicators not being very good.

Would a better solution be to make the people starving more aware of whats causing them damage? Something like a big red popup text every now and then.

**Comment by PrPleGoo** [comment]
> Would a better solution be to make the people starving more aware of whats causing them damage? Something like a big red popup text every now and then.

Is this for the people who are starving or for the people trying to help the starving people?

**Comment by PrPleGoo** [comment]
#18066

**Comment by deltanedas** [comment]
a hud isnt the same as examining an individual person to see if they are starving, not even showing if they are just hungry

**Comment by MisterMecky** [comment]
This should be under health examine, but I no longer feel like this is needed.

**Pull request closed without merging**
