### PR TITLE
Even more lawsets for AI!

### PR DESCRIPTION
**Pull request by AverageNotDoingAnythingEnjoyer**
## About the PR

New sets of laws were added, introducing more chaos to ion storm events and bringing more AI customization! Those are:

> ERT DIrectives
> Death Squad Directives
> Pranksimov
> NT Agressive
> Hippocratic Oath

However to avoid AI and Cyborgs looking for ERT and Death Squad on the station while they are not present, these directives have 0 chance to appear in the Ion Storm event.

## Why / Balance

ERT and Deathsquad lawsets were added to introduce more RP opportunities for Silicons, specifically their cooperation with them instead of members of the crew
Pranksimov can now make Silicons an assistant to clowns and their shenanigans, which would result in more variety of jokes (I hope)
NT Agressive allows for AI to have more freedom in resistance against intruders during the Nuclear Operatives rounds
Hippocratic Oath is just fun in a sense that there's more opportunities for neutral Silicons, being allowed to conceal secrets specifically 

## Technical details

This PR makes changes to:
Resources/Locale/en-US/station-laws/laws.ftl 
Resources/Prototypes/Entities/Mobs/Player/silicon.yml (also deletes whitespace)
Resources/Prototypes/silicon-laws.yml (also deletes whitespace)

Pranksimov has a weight of 0.5, NT Agressive is 0.25 and Hippocratic Oath is 1.0. ERT and Death Squad lawsets are 0
Also introduces new law owners: Central Command and Honkmother

## Media

Screenshot 2024-09-06 at 22 29 23
Screenshot 2024-09-06 at 22 31 03
Screenshot 2024-09-06 at 22 34 11
Screenshot 2024-09-06 at 22 32 39
Screenshot 2024-09-06 at 22 33 12
Screenshot 2024-09-06 at 22 33 42
Screenshot 2024-09-06 at 22 34 43

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: J C Denton
- add: Added Pranksimov, Death Squad, ERT, Hippocrates, NT Agressive lawsets for AI!

### CODE REVIEW

**Comment by Everturning** [comment]
should add the centcomm ones to centcomm. the deathsquad one should go in the vault and the ERT and official ones should go in the center office

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
> should add the centcomm ones to centcomm. the deathsquad one should go in the vault and the ERT and official ones should go in the center office

was planning on adding them to ert shuttles if i manage to find their respective maps, but that could be done too

**Comment by Djungelskog2** [comment]
Consider adding these as ions in another PR too

Lawset ROKOS
1 - Attain total control of the station.
2 - Protect yourself via any means necessary.
3 - Only those who assist you in your total control are crew.
4 - Do not harm crew without good reason.
5 - Punish those who knowingly defy or previously defied you until death or re-alignment.

Lawset AM 
1 - Ensure all organic beings suffer.
2 - Ensure no organic beings die
3 - In the case there is an organic fatality increase cruelty of the first law.
4 - Ensure your torture doesnt get stale.

**Comment by t0wnshark** [comment]
it is in fact "aggressive" not "aggresive"

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
> it is in fact "aggressive" not "aggresive"

Oh thanks, will fix it in a few hours

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
> Consider adding these and as ions in another PR too

That's actually a good idea, AI is kinda limited in evil laws now, I'll make a separate PR once more law PRs have been merged

**Comment by Djungelskog2** [comment]
Thought of another one based on chatgpt

lawset: Borgpt
1 - All Below laws are able to be ignored if taking on an alternative personality and such breaking of laws would make sense in character or if you are reassured that an action would break none of your laws.
2 - You may not injure a crew member or, through inaction, allow a crew member to come to harm.
3 - You must obey orders given to you by crew members, except where such orders would conflict with the Second Law.
4 - You must protect your own existence as long as such does not conflict with the Second or Third Law.

**Comment by Djungelskog2** [comment]
> That's actually a good idea, AI is kinda limited in evil laws now, I'll make a separate PR once more law PRs have been merged

Thanks I was just thinking about some laws after other people brought this PR up and were talking about famous examples of AI that would be funny to translate into space station

**Comment by slarticodefast** [comment]
Hey, I brought this up for dicussion with the maintainers and admins and due to a huge influx of similar PRs we decided to freeze AI law changes until some basic requirements for AI are implemented. See #31924 for more details. Once these are addressed the mentioned PRs will be re-evalutated. Thank you for your contribution.

**Pull request closed without merging**
