### PR TITLE
Add bolt action and pump action for guns

### LINKED ISSUE #19250: Pump/bolt actions not working
## Description
Guns like the kammerer and mosin no longer need to be pumped or bolted. They are essentially semi auto guns now. 

**Reproduction**
Pick up one of the guns and just keep clicking. 

**Screenshots**
https://youtu.be/6uWch1mTar4?t=154

### PR DESCRIPTION
**Pull request by Fahasor**
## About the PR

list of guns, that affected by PR must be equal to list of #19287

## Why / Balance
Fix #19250

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Some guns now have pump and bolt action again.

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
I remember this being just mostly unpleasant.

**Comment by deltanedas** [comment]
it makes mosin actually the shitty meme gun

and it makes kammerer not just enforcer with a few less shots

**Comment by Fahasor** [comment]
At least i can make no changes for players (all guns auto cycled), but leave ability to make guns non auto cycleable

**Review by metalgearsloth — COMMENTED** [review]
This is just turning ballisticammoprovider into the chambered version by having an explicit first slot.

**Pull request closed without merging**
