### PR TITLE
Computers aren't affected by the power being off anymore #4014

### PR DESCRIPTION
**Pull request by scrato**
## About the PR 
It fixes Bug 4014: Computers aren't affected by the power being off anymore.
I check directly in the interaction system whether a device that is a PowerReciever recieves power when trying to activate it, so it doesn't have to be done in every console / electronic device.
**Changelog**

### CODE REVIEW

**Comment by Zumorica** [comment]
Hardcoding this is bad. This should be a per-component behavior.

**Comment by scrato** [comment]
Oh, I understand. But 'PowerRecieve' already is a behaviour which is used in the yml files.
I just wanted to make sure it is checked at all times.

**Comment by scrato** [comment]
Okay, so it has to be implemented in every console... You're right. Thank you!

**Comment by scrato** [comment]
@Zumorica maybe creating another behavior "NeedsPowerToActivate" and use this for my code fragment instead of "PowerRecieve"? Then I can declare ComputerBase as NeedsPowerToActivate and we won't be as restricted as before?
My fear is, If I add the if(!Powered) return; to every console (as it has been done on the R&D console and a few arcade ones) then the possibility of forgetting this code part in future consoles will be very high.
What do you think?

**Comment by Zumorica** [comment]
Hardcoding components like this to the interaction system is not good, if someone "forgets" to code a power check, it can be fixed.

**Comment by metalgearsloth** [comment]
@scrato Are you familiar with how the eventbus works? The purpose of the ActivateInWorldMessage is for other systems to handle it.

**Comment by scrato** [comment]
@metalgearsloth  No I'm not. I'm very sorry, I've read the tutorials. But I'm new to git (not new to c# though) and wanted to contribute. 
Is there some Kind of tutorial in HackMD about ActivateInWorldMessage ?

**Comment by metalgearsloth** [comment]
Afraid there's no hackmd on it.

Essentially the message gets raised and any subscribers (EntitySystems) get passed the message to their handlers. In this case it has the Handled property so any system that subscribes can mark it as handled and the interaction won't continue.

The tricky part is some devices work with no power (e.g. APCs) and some also choose to show a different UI when not-powered.

**Comment by scrato** [comment]
Yeah, I can understand the reasoning behind that, and I see why hardcoding is bad at this situation. 
But I did know the Eventhandling and the 'handled' pattern, the word 'eventbus' did not ring a bell for me. 
But now it does. Anyway, I noticed that every console / machine I checked already did the power check on it's own except the ID console, so I made a new Pull Request.

**Pull request closed without merging**
