### PR TITLE
New Bullpup rifle (lecter base)

### PR DESCRIPTION
**Pull request by Elysium206**
## About the PR. 

This PR is the addition of a new bullpup assault rifle named the "Hellion" that is functionally a lecter, but will be added alongside the lecter rather than replacing it. my FUTURE intention is to either
A) add this rifle to station armories alongside lecters for added variety 
B)Replace H.o.S' WT550 with this rifle to give them a Unique weapon which could possibly be a syndicate steal objective in the future 

But for now all i've done is added the rifle to the game. 
## Why / Balance

The game balance of this should be good as is due to it being mechanically identical to the lecter in damage, range, spread, ammo, everything. it is a purely asthetic PR
## Technical details

In the Rifles.YML i added a new entity called the "hellion" and made the "lecter" its parent to ensure any balance changes to the lecter apply to this rifle as well. then in the Texture>Objects>Weapons>Guns>Rifles i added a new "hellion.RSI" folder with all of the sprites. Testing it in the Dev environment showed no issues or crashes from modifications so i SHOULD be good (I hope!)
## Media

image
image
image
image
image
image

The base, icon, mag-0, and bolt-open are completely original by myself. the inhand sprites, and backpack sprite are modified versions of the C-20R sprites to save on time seeing as how the guns are visually similar

## Breaking changes

N/A

**Changelog**

add: New Bullpup assault rifle added to the game!

### CODE REVIEW

**Comment by nikthechampiongr** [comment]
Looks like the merge conflict resolution ate the - type: entity on top of the prototype.

**Comment by Hmeister-fake** [comment]
Is this a new gun or a resprite? Either way looks very cool, SS14 lacks guns with shiny night visions sights, it add's a lot of flavor great job.

**Comment by nikthechampiongr** [comment]
> Is this a new gun or a resprite? Either way looks very cool, SS14 lacks guns with shiny night visions sights, it add's a lot of flavor great job.
Resprite.

**Comment by JoeHammad1844** [comment]
we already have a bullpup, the M90GL, currently unused because its underbarrel grenade launcher hasnt been implemented yet

**Comment by JoeHammad1844** [comment]
I do like this though

**Comment by Elysium206** [comment]
> I do like this though

Thank! I feel like station armories need some variety. I also think it's be sweet if this replaced H.O.S wt550

**Comment by JoeHammad1844** [comment]
agreed, a low accuracy SMG isnt the best option when you have civilians running around

**Comment by JoeHammad1844** [comment]
i think the colour is a bit off though, the green and red is fine but i cant exactly put my finger on why it seems off, is it using the lecters colour pallet?

**Comment by metalgearsloth** [comment]
Needs updating to replace the existing sprite, also yaml looks invalid.

**Comment by JoeHammad1844** [comment]
ill try my hand at changing the sprite

**Comment by JoeHammad1844** [comment]
thoughts?
image

**Comment by BolloTea** [comment]
x-01 when?

**Comment by Stanislav4ix** [comment]
BS artillery when?:)

**Comment by Elysium206** [comment]
> BS artillery when?:)

WYCI

**Comment by BolloTea** [comment]
@Elysium206 , can I suggest you better sprites?

**Comment by BolloTea** [comment]
image

**Comment by BolloTea** [comment]
I'm not a very good spriter, but if there are any shortcomings on my part, I can correct them

**Comment by HoidC** [comment]
halo 3 odst submachine gun

**Comment by BolloTea** [comment]
I’m experimenting, if there are any suggestions or shortcomings on my part, please let me know.
image

**Comment by JoeHammad1844** [comment]
> image

i think you got it first try with this one

**Comment by BolloTea** [comment]
The sprites are almost ready. All that remains is to complete the position in the hands, I can throw off ready-made options if necessary

**Comment by BolloTea** [comment]
bolt-open
base
icon
equipped-BACKPACK
mag-0
inhand-left
inhand-right

**Comment by TaralGit** [comment]
I have this one.

Helion

**Comment by metalgearsloth** [comment]
What's going on with this pr

**Comment by BolloTea** [comment]
Providing support

**Comment by metalgearsloth** [comment]
Ping me when the bikeshedding's done and we can revisit.

**Pull request closed without merging**
