### PR TITLE
Printable Special Mags and Empty Mags and Material Rebalance for Ammo

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

- Added pre-filled ammo type magazines of all types to the secfab. (ammo drums, speedloaders included)
- Added empty magazines of all types to the secfab.
- Removed printing single bullets and shells at secfab in favor of full mags and ammo boxes
- Reviewed and adjusted the material cost of ammo boxes and bullets to be more sensible (some were three times more expensive than they should have been).
- Material cost of a bullet has been standardized between ammo boxes and mags. Mags cost some steel (25 or 50), and mag ammo material is 20% more expensive for the convenience of having it preloaded in the mag.
- Ammo boxes have had their count adjusted to be two times the average size of the largest capacity magazine that exists (speedloaders have 6 ammo, ammo boxes now have 12. ammo drums have 8 ammo, ammo boxes now have 16, etc) to balance their printing costs.

Before and after of material costs: https://docs.google.com/spreadsheets/d/1aLQ8unSzfENT1s8wBRUH0Tjo5--qFfdDdZXAmXokuwQ/edit?usp=sharing

todo tasks:
- [x] replace single printable ammo with full mag equivalents
- [x] rebalance material costs so that full mags are more expensive than empty mag + ammo boxes
- [x] change latheRecipes to support layered textures so that things like speedloaders and ammo boxes display properly

## Why / Balance

A lot of people end up printing a standard mag then just dumping all the ammo on the ground to fill it with stuff from boxes. Boxes seem to be preferred, so I'm setting up a balance in which printing out empty mags and filling them with ammo from boxes makes sense when time is ample.

## Technical details

so many yml changes... to achieve empty magazines, I noticed that BallisticAmmoProvider automatically fills a magazine up by default by the given prototype if not null. So I made empty variants that had the proto as null, so they don't fill up on spawn.

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/98e3b6d2-9313-4cbd-b1b8-cf2401bac445

image

## Breaking changes

**Changelog**

:cl:
- remove: You can no longer print singular bullets at the security techfab.
- add: The security techfab now has recipes for ammunition boxes and pre-filled magazines of every type of ammo.
- add: You can now print empty magazines at the security techfab.
- tweak: Material costs for printing all ammo and mags were rebalanced.

### CODE REVIEW

**Comment by thebadman4662** [comment]
If its not too much trouble, can empty colored ones be printed too? Even if it was only for rubbers it would be great.

**Comment by Plykiya** [comment]
> If its not too much trouble, can empty colored ones be printed too? Even if it was only for rubbers it would be great.

I initially considered adding colors but I really wanted to avoid people thinking it was already pre-filled with ammo. I can do it if there are more people who support it... but it will also end up causing some amount of selection bloat.

**Comment by thebadman4662** [comment]
Thats why just blue would be enough, if its not rubbers then its obviously some kind of lethal mag or at very least stun+execution one.

**Comment by Plykiya** [comment]
> Thats why just blue would be enough, if its not rubbers then its obviously some kind of lethal mag or at very least stun+execution one.

Okay, sure. I'm all for the distinguishing options being lethal and non-lethal for colors. Two options per mag is bearable.

**Comment by Plykiya** [comment]
image

Regarding the lethal/non-lethal distinguishment, should I rename them?

**Comment by thebadman4662** [comment]
Beanbags are pretty much rubbers of shotguns so you probably want to use them over slugs that are lethals that do not spread into pellets.

**Comment by Nairodian** [comment]
I'd just remove all the special ammo single rounds and make it so you can craft full special mags.

**Comment by Plykiya** [comment]
> I'd just remove all the special ammo single rounds and make it so you can craft full special mags.

Oh, yeah, I do find the single rounds of ammo pretty bad to deal with as well...

**Comment by ElPidor** [comment]
this shit must be applied to emagged autolathe

**Comment by SpeltIncorrectyl** [comment]
Can you make empty shotgun magazines printable?

**Comment by Plykiya** [comment]
> this shit must be applied to emagged autolathe

I have never emagged an autolathe in my life, I will look into it


> Can you make empty shotgun magazines printable?

I already stated I added shotgun ammo drums

**Comment by thebadman4662** [comment]
> > this shit must be applied to emagged autolathe
> 
> I have never emagged an autolathe in my life, I will look into it

Basically you can either print single bullets of ammo, unlocked top RD server ammo or whole boxes. Mags you gotta buy. 😢

**Comment by Plykiya** [comment]
> > > this shit must be applied to emagged autolathe
> > 
> > 
> > I have never emagged an autolathe in my life, I will look into it
> 
> Basically you can either print single bullets of ammo, unlocked top RD server ammo or whole boxes. Mags you gotta buy. 😢

since this PR is slowly ballooning in task size, I'll do the emag printing recipes and whatnot in a separate PR

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
This causes way too much entity bloat by forcing every cartridge to be manually inserted and can't be merged as is.

**Comment by Plykiya** [comment]
Let me just convert this to a draft while I make like seven more changes for Nairod...

**Comment by Plykiya** [comment]
and now I have to figure out why LatheRecipes don't support sprite layers.

**Comment by Plykiya** [comment]
I figured out... at least what happens? LatheMenu uses SpriteSystem's GetPrototypeIcon on an EntityPrototype of the result, which returns either an icon or the spriteComponent.icon without support for layering textures....

this is starting to dip into engine-level stuff and I don't really know how to proceed

**Comment by ElPidor** [comment]
> > > this shit must be applied to emagged autolathe
> > 
> > 
> > I have never emagged an autolathe in my life, I will look into it
> 
> Basically you can either print single bullets of ammo, unlocked top RD server ammo or whole boxes. Mags you gotta buy. 😢

that's very stupid tbh. I can print anything as sec's can print but i cant print mags
Viper stays as basically useless pistol. Most syndy just buy esword and noslips with soap or revolver because it's a huge waste of tc for buying it. But in case if you buy emag hack the autolathe print as hell mags you'll get a good coop style with a lot of funny bullets flying around, 
for example you can buy bulldog and other syndi but emag and print some shotgun shells and hide them in cigaretes box, though it's very slow to reload the drum, because you cant right click it with a box of ammo and put it all in it.

**Comment by Plykiya** [comment]
I have slept on the problem, gotten some advice, and I will work on the LatheRecipe sprite fix in another PR for the time being.

**Comment by metalgearsloth** [comment]
@Plykiya is this still being worked on.

**Comment by Plykiya** [comment]
> @Plykiya is this still being worked on.

only in the sense that I stare longingly at my IDE and wish I knew more about the codebase
I basically need either icons to support layers to get the thumbnails for each recipe to show up correctly, or I need to figure out how to make fake entities in nullspace like the guidebook does

**Comment by Plykiya** [comment]
I added an updated video showcasing what it currently looks like without sprite layering.

**Comment by Plykiya** [comment]
I uploaded a video to demonstrate the current issue

The entities have a base layer for the magazine, and then another layer the bullets.

Because of the lack of support for layering, everything that should have bullets inside them appear without bullets, such as speedloaders. Speedloaders are basically only completely differentiable by the bullets inside them. Boxes for shotgun shells similarly show up completely blank.

**Comment by Plykiya** [comment]
wait a minute.... why do all the icons show up correct in the entity spawn panel
oh... I just need to copy what that does

**Comment by Plykiya** [comment]
Well this should fix it, but I'm getting a strange error on compile unrelated to any of the normal build tests. If I fix this, then this PR should be ready to open again....

**Review by metalgearsloth — APPROVED** [review]

**Comment by SpeltIncorrectyl** [comment]
This has been merged and the world is at balance.

**Pull request merged**
