### PR TITLE
rouny meat and steak

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
rouny gets special meat when butchered
meat can be cooked in a fire to make rouny steak which is a good food

tastes like lost friendship :( you couldve made him a pet

## Why / Balance
rouny

## Technical details
no

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/2f404472-c325-4a01-a27f-358afd2190aa

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**

### CODE REVIEW

**Comment by LankLTE** [comment]
> tastes like lost friendship :( you couldve made him a pet

Sir he killed 3 people and was biting my leg

**Comment by deltanedas** [comment]
your fault for not securing him properly

**Comment by Doru991** [comment]
While not related exclusively to this PR, isn't it kinda weird/unintuitive that xenos are butchered via meatspike? The meatspike seems to be generally used on humanoid creatures like monkeys or players, and xenos mostly don't fit in that group.

**Comment by deltanedas** [comment]
yeah i think they used to be knife butchered but someone mustve changed it, or i remembered wrong

**Comment by deltanedas** [comment]
rouny

**Pull request merged**
