### PR TITLE
Security Resprite

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Resprites / returns SS13 sprites for most of the basic uniforms & outfits of security.
Also makes some fairly minor changes related to the clothing sec wears:
- The alternative detective coat has been removed since it's not needed anymore.
-  The grey detective coat has been added because we didn't have it. What's even the point of having the grey fedora without it?
- This isn't *technically* a removal, but the HOS hat has been transformed in to a cap since the old one looked bad. Someone can probably re-add the cowboy hat with new sprites if they want to.

## Why / Balance
Security is one of the most hodge-podgey looking departments in the game. Jumpsuits styled completely differently from every other jumpsuit, comparatively extremely detailed sprites with inconsistent coverage, several old CEV-Eris leftovers that were never removed for some reason...
For specific elaboration:

- The helmet was extremely over-detailed and randomly plucked from baystation security (or so I've heard.) The current helmet actually matches with the armor vest.
- HOS's coat was reverted since the new one had some readability issues & kind of looked like syndicate gear.
- Warden's weird armor vest webbing has been stripped since I think it makes him look more normal.
- The detective randomly used a bunch of CEV-Eris sprites still, and even outside of that, just generally looked really bad. Lots of generally awful contrast & color choice was strewn about through his wardrobe. His fedora may as well have just been a *bowler hat* for crying out loud.

## Media
image

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Resprited most of Security's basic attire.

### CODE REVIEW

**Comment by deltanedas** [comment]
hos cowboy hat is the goat bring it back

**Comment by UbaserB** [comment]
voxxie!

**Comment by IProduceWidgets** [comment]
Have to agree, that new hat looks weird and I cant really tell what it is on the head.

**Comment by K-Dynamic** [comment]
How does the HoS cap compare with the warden cap? I kinda want the new HoS cap to be more prominent

**Comment by Doc-Michael** [comment]
I must ask what was the reason for the removal of protection values from Det coats?
i could have understood decreasing the protection values by -5% to make it a sidegrade to the armour in exchange for having more space.
Fully removing them will force dets to use either their own vest or one of the sec vests, at least in order to survive any basic combat scenario...
So the point is using the coats without armour is putting yourself at a massive disadvantage, not to mention being an easy target to syndicate agents and revolutionaries.

**Comment by Just-a-Unity-Dev** [comment]
i agree with the most of the resprites but the fedora is egh

**Comment by ImRenQ** [comment]
изображение
изображение
It seems to me that only the detective in gray clothes looks better.
_unfortunately, I couldn't insert the second image without losing quality._

**Comment by ps3moira** [comment]
sec officer's jumpsuit looks extremely flat

**Comment by IProduceWidgets** [comment]
Hmm. On second blush I dunno how I feel about this vest change
image

It might be better to just add badges as a neck item like the lawyer. They're kind of finicky to make but I think I've got one if you want it, it will just need some very minor tweaks since I made it for an ERT role.

(I also prefer the small armor style, but that's pretty minor)

equipped-NECK
icon
[meta.json](https://github.com/user-attachments/files/15876948/meta.json)

**Comment by Flareguy** [comment]
> 
> It might be better to just add badges as a neck item like the lawyer. They're kind of finicky to make but I think I've got one if you want it, it will just need some very minor tweaks since I made it for an ERT role.


This is understandable, but is frankly a bit extra, and would probably end up being a pretty annoying detour. I mainly just want to get the basic security outfits up-to-standard here, more then anything.

**Comment by Flareguy** [comment]
> sec officer's jumpsuit looks extremely flat

They use the exact same template as every other jumpsuit in the game.

**Comment by KingFroozy** [comment]
The detective change is like the most noticeable one, and I love it.

**Comment by Doctor-Cpu** [comment]
Could the trenchcoats be made to opened and closed like the labcoats?
Also id prefer the hos cowboy hat to the new sprite.

**Comment by Thurtik** [comment]
I dont like this at all. Getting a police cap for hos would be sick, but not at a price of the sheriff hat. Also the new sprites you've made are just downgrades. Since when is having more detail and looking nicer than the rest a bad thing? And if it's really hurting the job uniforms' consistency that much (which it's not), why not just make the rest of the departments' uniforms nicer instead?

**Comment by ps3moira** [comment]
> > sec officer's jumpsuit looks extremely flat
> 
> 
> 
> They use the exact same template as every other jumpsuit in the game.

Sure but they still look extremely flat in coloring. Also the helmet looks more like a bike helmet than a proper security helmet. I'd suggest adding more details or darker coloring.

**Comment by FairlySadPanda** [comment]
HOS cowboy hat should be preserved and made loadout

**Comment by TheDoctor1977** [comment]
I really love the current brown detective coat and would hate to see it go, maybe instead you could add (a more similarly colored version of) the new coat sprite as an "opened" version like with lab coats?

**Comment by LeanMeanKillingMachine** [comment]
I'm sorry, but the reasoning for the changes is very much flawed. You can't simply downgrade to inferior sprites because you think the current one is too detailed, that's incredibly weird. Also, you're not even certain of what you're talking about in the reasoning "...or so I've heard". That doesn't bode well for the rest of this.

I also dislike the argument that HOS' armored trenchcoat looks too much like the Syndicate's. They're very distinguishable for each other, and no one even touches the regular syndicate clothing.

These sprite changes are unnecessary and actively diminish the quality of Security's spritework. Also, keep the damn cowboy hat. What is it with people and getting rid of the cowboy things?

**Comment by EmoGarbage404** [comment]
beatings will continue until art style improves

**Comment by Emisse** [comment]
you guys can add cowboy hat as an unlockable for hos if it doesnt look bad but for now this is a improvement to our sprites
we arent going for overly detailed sprites we are going for a specific style. "less detailed" does not = bad

**Comment by LeanMeanKillingMachine** [comment]
Sorry - what is this specific style? It just seems to me that the wider community is not privy to the vision you share. More and more PRs get approved even with a majority negative reaction, some of them aren't even properly justified to us.

It seems like there's a set path here, regardless of what we think about it.

**Comment by EmoGarbage404** [comment]
There is a [publicly available art style document](https://docs.spacestation14.com/en/space-station-14/art.html) that outlines in detail what the intended art style is. This includes both rendering as well as visual theming.

**Comment by skypatrol21** [comment]
> beatings will continue until art style improves

the best part of the don't be a dick rule is staff seem not always read it. It seems you have a clear vision of how you think the game should be and will be rude to anyone who doesn't share it, which is already uncool. But not being able to really quantify your vision and share it with other people makes it really hard to collaborate with.

**Comment by metalgearsloth** [comment]
> Do staff not have to follow the don't be a dick rule?

This was to flareguy who is also an art director.

> But not being able to really quantify your vision and share it with other people makes it really hard to collaborate with.

The comment directly above yours links the document so avoid being needlessly inflammatory towards others, thank you.

> More and more PRs get approved even with a majority negative reaction, some of them aren't even properly justified to us.

I have read the entire PR and at no point was anything not justified but if you can point to specifics it would be appreciated.

**Pull request merged**
