### PR TITLE
Zombie Mode 𝓡𝓮𝓭𝓾𝔁

### LINKED ISSUE #10384: Zombie gamerule should delay making them zombies
Ideally someone doesn't know they're a zombie until 5-10 minutes in so people have time to get in the game properly before a breakout.

Right now they can choose when to be a zombie but it should also have a delay to allowing them to turn / telling them.

### LINKED ISSUE #13982: Shuttle should be auto-called if a large percentage of the crew is zombified
## Description

The last 3 zombie rounds I've played have had to be ended through admin intervention because almost everyone got zombified and the salvage techs that managed to not get infected can't feasibly mount a counterattack against 70-something zombies. Player zombies have also developed a concerning habit of smashing the comms consoles when there's nobody else to attack, rendering the round unable to be ended IC until the crew transfer shuttle arrives or an admin forcibly ends the round. I would suggest the shuttle being auto-called if all comms consoles are destroyed, but that would encourage zombies to smash the consoles even more, so a auto-call once enough people are zombified should fix the issue.

### LINKED ISSUE #16166: all zombies need to have one faction
## Description

Zombie tarantulas [AI] will be attacking human zombies
**Reproduction**

**Screenshots**

**Additional context**

### LINKED ISSUE #16529: Zombie exceptions
image

### LINKED ISSUE #16581: Zombies are overpowered
- Romerol still needs fixing, however zombies despite being already overpowered received even more buffs to the point they guarantee round-end.

https://github.com/space-wizards/space-station-14/pull/16325
https://github.com/space-wizards/space-station-14/pull/16235

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

back and better than ever after a bunch of changes to bring back old behavior and add back some new stuff.

**Zombie Changes**
- non-human zombies are now tinted green
- all zombies can now see a status icon, helping them determine who is and who is not a zombie.
- Zombies no longer do any friendly fire damage
- Zombies can no longer revive after being killed.
- Adjusted damage values to make zombies less blazingly weak to heat
- non-player-controlled zombies now have proper AI and will attack non-zombies
- zombified carps, morbs, etc. will no longer continue to attack zombies once zombified.
- zombies no longer heal heat damage, only blunt
- healing on bite is now way less weird garbage
- humanoid zombies can now pry doors 

**Infection Changes**
- Zombie Infection now deals constant damage instead of ramping up over time
- Infection now properly deals toxin damage.

**Initial Infected Changes**
- Initial infected now get an audio queue when they are chosen (it's the zombie one i was too lazy to find another)
- Initial infected begin taking damage from the infection after 12.5 to 15 minutes.
- Initial infected can no longer cure and inoculate themselves from the zombie virus, thus rendering themselves unable to do initial infected stuff.
- Changed text that incorrectly referred to them as "patient 0"

**Zombie Mode Changes**
- Fixed a bug where no infected would be chosen during a midround zombie outbreak.
- Delayed initial infected selection in zombie mode by 10 to 15 minutes. No more roundstart "ZOMBIES"
- Fixed certain entities being counted as alive when they really weren't.
- Shuttle is now automatically called when 50% of the crew becomes zombies.
- Reenabled in secret and increased odds because i love it.

**Zombie midround changes**
- Fewer initial infected are selected for midround outbreak
- initial infected have less time before infection damage sets in

Probably fixes #16581
Probably fixes #16529
Fixes #16166
Fixes #13982
Fixes #10384

**𝓶𝔂 𝓼𝓹𝓲𝓮𝓵**
Really felt like a bit of a "death by a thousand paper-cuts" situation. None of these issues were a massive undertaking, but a lot of these problems have been silently piling up from some of the more controversial changes a few months ago. And while some of the more glaring issues were reported, many of the finer balance minutiae weren't mentioned in issues and had to be gleaned from individual contributors and admins.

Even still, this fix, which i believe to be pretty comprehensive, did not take super long to throw together. It would've been appreciated if the problems with the mode were more publicly communicated so they could've been taken care of before the mode was thought to be worth removing. Outright removing it before even making github issues for a majority of the problems is kinda like taking a cannon to a ballgame: but here we are i guess.

if there are any more issues that people have that need fixing, then they can report them via the github or discord forum instead of keeping them in private channels. :heart:

**Media**

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog** (let's try to keep it short)

:cl:
- add: Non-human zombies now are the proper color and zombies can now identify one another and are unable to harm one another.
- add: Removed zombie revival, decreased passive zombie healing, and adjusted zombie weaknesses.
- fix: Fixed zombie NPCs continuing to attack other zombies.
- tweak: Zombies can now pry open doors.
- tweak: Made initial infection selection more obvious.
- fix: Fixed an issue where midround zombie outbreaks wouldn't create any zombies.
- tweak: Initial infected selection is now delayed at the start of zombie rounds.
- add: The emergency shuttle is now automatically called when enough crew become zombies.
- add: Reenabled zombie mode in secret.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
I reckon the shuttle should automatically call at 50% zombies, and spawn in a group of at least 4 CBURN operatives on the 'dart' ship, or maybe even a lone op spawn

**Comment by Emisse** [comment]
i feel like zombies should have innate constant regen at a low amount so they can heal out of crit unless killed or heat damaged into crit.

**Comment by EmoGarbage404** [comment]
> i feel like zombies should have innate constant regen at a low amount so they can heal out of crit unless killed or heat damaged into crit.

they did in the past and this pr retains that functionality. They heal a small amount of brute damage every second.

**Comment by Emisse** [comment]
so truers rise

**Comment by lzk228** [comment]
> * all zombies can now see a status icon, helping them determine who is and who is not a zombie.

metagaming?

> * Shuttle is now automatically called when 50% of the crew becomes zombies.

can it be turned off?

**Comment by Equivocateur** [comment]
> metagaming?

The other way around. Combats prankster hops giving people "Zombified" ID cards making them look zombified in the shift+click menu.

**Comment by EmoGarbage404** [comment]
breaking this down point-by-point because text blob isn't helpful:
> This doesn't prevent the round from stalling in situations where a large enough group abandons the station on something like the cargo shuttle. 

This is a common problem that can occur with basically any antag who doesn't have a stationary goal. Considering that every station has access to a completely self-sufficient shuttle, stalling on it is going to be an issue no matter what. At the very least, the 50% threshold is going to be more effective at preventing said stalling, since getting 30+ people is more difficult than something like stealing the nuke and flying off to a different map.

> > all zombies can now see a status icon, helping them determine who is and who is not a zombie.
> 
> metagaming?

I mean it's only for zombies to know each other internally, so it's moreso a convenience feature. Zombies already can't do damage to each other so this just makes it more clear.

> they are still encouraged to because they have an advantage in encounters in spaced areas. [...] some admins held the opinion that it isn't fun, and there is no interesting counterplay, for many players dying because zombies spaced the station early in the round. 

I mean, spacing is probably one of the most common environmental threats on the station. Ignoring the fact that airlocks render a decent amount of the station safe from direct spacing (which are made more effective in these changes since zombies no longer have to destroy all of them to access areas of the station), emergency suits and air tanks are extremely common. Perhaps it would be worthwhile to give zombies a small amount of pressure damage as an offset to discourage them to space areas; however, many zombies have hardsuits so the effects of that might not be felt. 

>While the automatic shuttle call attempts to mitigate the effects of a station wide power outage or destroyed comms console, it creates the potential for zombie players to justify destroying those objects: "I'm not stalling the round because the shuttle will automatically come if zombies kill all the players." However, it is not effective in preventing round stalling if many players are just hidden away from zombies, especially if they are off station.

I mean, i have to concede on your first point because it's not necessarily wrong? Damage to power structures and destruction of things like communication consoles are less game-ending when there remains a way out. I don't really see your issue with it. The latter point, regarding hiding and stalling, is really only relevant for hiding on the cargo shuttle (something not typicially afforded to people outside of cargo) and throwing yourself into space (something only the dumbest of people are going to do: it's literally suicide anyways). If hiding on-station in closets and lockers is an issue, I could additionally implement an overlay that allows zombies to "see" living players through walls, which would help guide them towards sneaky targets trying to hide.

> To be a good main antag, the antag should typically cause issues throughout the length of the round, as traitors and many SS13 antags do, or should require the time at the start of the round where they aren't having an impact to prepare so that they can cause issues for the rest of the round, as nukies do.

I mean this is kinda an arbitrary definition of it. Barring a 15 minute grace period to prevent immediate rushing and destruction (a frequent problem that was actually told to me), initial infected are not only given time to prepare but, due to their longevity and infection capabilities, can persist and continue to cause conflict throughout the duration of the round (especially with initial infected being able to mask their infection, creating paranoia).

I would also give my opinion regarding the various "admin issues" that were mentioned, but as was said to me in the past:
> "It's pretty bold of you to be saying the things that led to these changes are 100% manageable in-game despite not being one of the people actually having to mange it."

I suppose that my opinion on these things is unwanted, and, quite frankly, I'm not in the mood to bend over and explain my thoughts to a group of people that won't even let me know what issues they have, much less include me on discussions they have surrounding features that I create and maintain.

In regards to issues with admins coming up with rules suiting my gameplay changes and modifications, I leave it at: "tough shit; not my problem."

**Comment by LankLTE** [comment]
> or should require the time at the start of the round where they aren't having an impact to prepare so that they can cause issues for the rest of the round, as nukies do. The game mode created by these changes is just 10-15 minutes of extended with an early forced midround event

Is that not exactly what nukies are? You get 15-30 minutes of station activities, then nukies flood in and the round’s over one way or another. This PR changes zombies to have “time at the start of the round to prepare” so I don’t see why “10-15 minutes of extended with an early forced mid round event” is a problem.

**Comment by deltanedas** [comment]
giving zombies spacing damage might incentivise people to space everything to cull hordes, at least in salv/engineering where suits are expected, which basically swaps the shitters roles from zombies spacing to crew spacing

**Comment by EmoGarbage404** [comment]
Made some changes to address stalling:

The infection percentage for calling the shuttle now only accounts for players on-station. In this scenario, fleeing the station would simply discount the group from the count, allowing the round to end more organically. This also shifts the dynamic subtly from "infect all players" to simply "overrun the station." This in turn makes stalling more difficult and makes fleeing more of an organic choice without severe downsides to round quality.

**Comment by retequizzle** [comment]
i do think that change is needed and i'm surprised/disappointed none of us brought that up as an option beforehand

**Comment by Emisse** [comment]
run it live!!!

**Comment by liltenhead** [comment]
I know this is already merged but a lot of the silent issues were "silent" due to no direction of what zombies are supposed to be doing. There still isn't an agreed upon ruleset for zombies, and some of this changes will thankfully help with the admin load. I worry that this was merged back without much direction for players to follow but I guess we just roll with it.

**Comment by EmoGarbage404** [comment]
at it's core, zombies has always been a pretty simple conversion antag. Zombies eat humans make zombies eat humans. I think that part was always fairly well understood by players.

The issue as a whole, was a direction for the gamemode. My goal with the changes was just to extend the existing gameplay and scenario into something that had a more clear end. As such, the only goal zombies are trying to accomplish is overrunning the station, which trigger a round end on majority zombification. 

I think this is sufficient in both retaining the relatively simple core gameplay while also giving them better round integration.

**Comment by HoidC** [comment]
> I know this is already merged but a lot of the silent issues were "silent" due to no direction of what zombies are supposed to be doing. There still isn't an agreed upon ruleset for zombies, and some of this changes will thankfully help with the admin load. I worry that this was merged back without much direction for players to follow but I guess we just roll with it.

zombies are zombies, they're meant to convert people
is it really that complicated

**Comment by liltenhead** [comment]
Sorry, let me clarify what I meant. Yes, it is obvious a zombie bites people. However, how are you supposed to go about doing it? Are you allowed to destroy power? Are you allowed to go for flanks? Are you supposed to run into grilles or avoid them? There's dozens of scenarios that get ahelped every time zombies start getting more numbers. I frequently see new players and veterans alike biting pipes and other things that don't help them directly zombify anyone, but could be argued that killing people indirectly to zombify them furthers a zombies goals.

That is what I mean by there isn't much direction.

**Comment by EmoGarbage404** [comment]
I've always been of the opinion that really anything goes as long as you're actively trying to infect a player.

I think, especially with how the new auto-ending works (+ whenever we get autoshuttle), station destruction isn't as much of an issue.

**Pull request merged**
