### PR TITLE
You can now pet the AI core.

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Title.

## Why / Balance

AI is a silicon too, it deserves love as much as the borgs :(

## Technical details

Added the InteractionPopup component

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: You can now pet the AI Core.

### CODE REVIEW

**Review by Emisse — APPROVED** [review]

**Comment by CookieMasterT** [comment]
As the person who pr'd petting borgs:
**Let's go**

**Comment by ScarKy0** [comment]
> As the person who pr'd petting borgs:
Let's go

Thank you for possibly the most important feature in the modern day ss14

**Comment by ScarKy0** [comment]
Emisse approved and for some reason it didnt add the label so i did it myself :godo:

**Review by slarticodefast — APPROVED** [review]
Vital PR.

**Pull request merged**
