### PR TITLE
Antag Playtime Tracking

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Tracks and displays the playtime for antags
## Why / Balance

Let players see how much time they have playing antag and allow for antag playtime requirements.
## Technical details

uhhhhhhhhhhhhh... adds a playtime tracker to AntagPrototype then reads that when assigning the playtimes to track... I think... 
From testing, I can confirm it does not double count playtime overall and it also records both the player's Job time and the antag time.
## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Antagonist playtime is now tracked and can be viewed in the player stats menu

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
uhhhh.... fail my fault

**Comment by Cojoke-dot** [comment]
Mmmmm... I did this wrong...

**Comment by BramvanZijp** [comment]
> Mmmmm... I did this wrong...

Easy fix, not worth closing this over

**Comment by Cojoke-dot** [comment]
nah I meant to set it to a draft, whoops

**Comment by Cojoke-dot** [comment]
mmm... found more bugs when making another pr with these changes, I'm setting it back to draft to fix them

**Comment by Cojoke-dot** [comment]
I'm not going to finish this lol, if anyone wants to finish it all that was needed to be done is fixing the color of the roletime requirements for jobs

**Pull request closed without merging**
