### PR TITLE
Pacification status effect and Pax

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Adds an effect that disables your combat mode, and a chem to induce it. Pretty shrimple.

**Changelog**

:cl: Rane
- add: Added Pax, a drug that disables people's combat mode.

### CODE REVIEW

**Comment by HoidC** [comment]
what does this actually do in-world out of curiosity

**Comment by Just-a-Unity-Dev** [comment]
>disables combat mode

>what does this do

>mfw

**Comment by Elijahrane** [comment]
> what does this actually do in-world out of curiosity

it pacifies them

**Review by mirrorcult — APPROVED** [review]
fine with the concept maybe needs a 2nd opinion

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
