### PR TITLE
add some circuits from proto to imprinter

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
who put my dear circuits in the protolathe 
**Screenshots**

**Changelog**

:cl:
- add: Some miscellaneous electronics have been additionally added to the circuit imprinter.

### CODE REVIEW

**Comment by Elijahrane** [comment]
> who put my dear circuits in the protolathe

there was supposed to be a distinction between electronics and circuits

**Comment by EmoGarbage404** [comment]
> > who put my dear circuits in the protolathe
> 
> there was supposed to be a distinction between electronics and circuits, with electronics being much simpler to produce. this is just going to make eng gameplay super awful

firstly, from a realism perspective, there is absolutely no difference between "electronics" and a "circuitboard" gameplay-wise or visually. The only difference is that these specific recipes are slightly more common than the others in the printer.

secondly, i don't think there's really that much of an issue of needing to go interact with science to get some parts printed. someone else can weigh in on this, but i think it's more interesting if these types of construction things require more cooperation from different departments.

Also, i genuinely doubt this is going to make engineer gameplay "super awful"

**Comment by Elijahrane** [comment]
>firstly, from a realism perspective, there is absolutely no difference between "electronics" and a "circuitboard" gameplay-wise or visually. The only difference is that these specific recipes are slightly more common than the others in the printer.

they are different gameplay wise. Circuitboards are boards for upgradable machines, electronics are simple parts for electronic devices like doors, switches, etc.

>secondly, i don't think there's really that much of an issue of needing to go interact with science to get some parts printed. 

We have that with machines already. You should be able to do the basics of your job. For engineers, I would say 'constructing a door' is very basic.

**Comment by civilCornball** [comment]
Why can’t they be in both?

I don’t know all that much about the gameplay difference and how that’s impactful, but I DO know that I personally have told people as sci that “I can’t find the door electronics in the circuit printer” because I have been conditioned to look for board-like objects in the printer.

Being in both makes it easier to find them.

**Comment by Elijahrane** [comment]
> Why can’t they be in both?

perfect solution

**Comment by EmoGarbage404** [comment]
added it to both

**Pull request merged**
