### PR TITLE
Made Sec Hud Show Borg Job Icons + Made Borgs Unimplantable

### LINKED ISSUE #25211: station borgs should have borg icon on sechud

### PR DESCRIPTION
**Pull request by Zadeon**
## About the PR

This PR makes it so that people wearing sec huds will see the borg job icon beside borgs instead of the unknown job icon. This only works with station borgs and not syndicate borgs. Syndicate borgs will show up as unknown to people wearing sec huds. Also I found through testing that borgs didn't have the Unimplantable tag, so this PR also fixes that.
Closes #25211

## Why / Balance

It felt strange that we had the borg job icon available but borgs would always show up as unknown when using the sec hud so I wanted to fix that. Unfortunately, this change clashes with the current ruling for borgs where if somebody has a job icon displayed then it means they're a crew member. This change makes borgs also see borg job icons for other borgs (because they use the same system sec huds use for showing job icons). I'm making this PR now in the state it's currently in because I could not for the life of me figure out how to code it so that if you are playing as a borg you do not see job icons over other borgs. Also couldn't figure out how to make syndicate borgs show the borg job icon if you're playing as a nuke op. I'm willing to implement this functionality if somebody can show me how (or leave the PR as is and we redefine borg rules, whichever is easier).

## Technical details

In ShowSecurityIconsSystem.cs inside the DecideSecurityIcon function, it will now check if the entity has the BorgChassisComponent and does not have the ShowSyndicateIconsComponent. If true, it will grab a new BorgJobIcon field added to BorgChassisComponent which holds the JobIconBorg status and set jobIconToGet to this value.
Added Unimplantable to the tags of BaseBorgChassis.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
PoV of a crew member wearing sec hud:
image
PoV of a station borg:
image
PoV of a nuclear operative:
image

## Breaking changes

None.

**Changelog**

:cl:
- tweak: Borgs now show their job icon while wearing sec hud.
- fix: Borgs can no longer be implanted.

### CODE REVIEW

**Comment by UbaserB** [comment]
i hate how the borg icon is offcentered lol

**Comment by Zadeon** [comment]
I have brainstormed one solution to my problem and it would be giving borgs their very own special ShowSecurityIcons component that doesn't show job icons for borgs. But I don't really like the idea of making what would be an almost exact copy of this system if it's possible to implement what I'm looking for all inside ShowSecurityIconsSystem.cs.

**Comment by LankLTE** [comment]
Might need a rules change since wizden rules define crew as people with SecHud icons and Borgs are (I think intentionally) not crew.

**Comment by trollbreeder** [comment]
Wouldn't it be cool if the borg job icon was colored based on the type of borg? (e.g. service is green icon, engineering is yellow icon, etc)

**Comment by Zadeon** [comment]
Somehow I messed up this branch big time. I'm just going to close it and make a fresh PR.

**Comment by Zadeon** [comment]
New PR is up here: #26004

**Pull request closed without merging**
