### PR TITLE
Ports /vg/station barricade sprites & slightly buffs them

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Ports the barricade sprites from /vg/station. Also makes them slightly easier to construct, and gives them slightly more HP.

Currently, none of the new variants are constructible due to limitations with the construction system (read: "I don't have the skill to fix this because I can't code.")

## Why / Balance
More ammunition for mappers to use + they look really good. I first thought the "mismatching" wood color would end up looking bad, but I feel like it fits even better then it did before.

The buffs are a result of psuedo-porting the stats from /vg/station, and also to encourage people to build barricades more.

## Media
Content Client_43qF0NJdLk
Content Client_MW2VwtSR29
Content Client_ATtvXUDDld
Content Client_XtFODpZ3QM

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added several new types of barricades for mappers to use, all using sprites from /vg/station. The regular, full-tile barricade has also received a new sprite from /vg/station.
- tweak: Barricades are now slightly stronger & cheaper to make.

### CODE REVIEW

**Comment by mirrorcult** [comment]
barricades being occluding is slightly strange to me given the sprite seems to imply you can see through them but im ok with it i suppose

**Comment by LankLTE** [comment]
Yeah barricades blocking line of sight is weird when there's massive open space in the middle of it

**Comment by BasedUser** [comment]
> it would be cool, tho impossible to implement, for it to partially occlude whats behind them so you can see little bits

dynamically generate occlusion linedefs

**Comment by EmoGarbage404** [comment]
test fail is not erroneous, you duped the construction graph prototype ID.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
