### PR TITLE
Pirate assets

### PR DESCRIPTION
**Pull request by brainfood1183**
Contains new pirate clothing and equipment to improve the pirate antag experience.

Untitled-53

Includes

- Pirate cannon - (1 shot and reload launcher with a low to medium damage output which takes typically 2 hits to crit a regular crewmember and 3 to crit a crew member in a hardsuit, 2 hits to break reinforced window so low damage and 2 tile radius), should be 1 or 2 aboard a pirate ship.
- Cannonball - ammunition for the cannon, should be 3 or 4 per ship.
- Cutlass - a melee weapon for pirates, does 18 damage with a regular swing speed (captains sabre is a lot better than cutlass).
- Energy Cutlass - comparable to an energy sword except slightly different damage outputs.
- Foam Cutlass - a foam version of a  cutlass for dressing up as a pirate and having fun.
- Pirate Slops - a pirate jumpsuit.
- Pirate Captain Slops - a more distinguished pirate jumpsuit.
- Pirate accent - triggered by wearing Pirate Slops makes you sound like a pirate by swapping out words with more piratey words.
- Deep Space EVA Suit - replaces the standard EVA suit for pirates (looks like deep diver costume and should replace the spawns on the pirate ship). It is heavy and you move slowly wearing it so idea is pirates will take off the EVA suit when they board station.
- Deep Space EVA helmet - a helmet to go with the new EVA suit.
- Pirate Captains Cloak - a cloak to help the pirate captain stand out from the other pirates.
- Pirate Captain Ancient Hardsuit - a hardsuit for the pirate captain with built in helmet, similar to the captains hardsuit but slightly worse.
- Pirate Backpack - a new backpack for pirates to make them feel special.
- Pirate chest - comes in 3 varieties, empty, antag which is designed to be placed on the pirate ship and fun which is a fun pirate themed crate that cargo can order. The pirate themed crate contains 2 outfits to dressup 2 crew members and 2 foam cutlass swords.
- Alterations to PirateGear- the PirateGear loadout

1. swapped brown jumpsuit for pirate slops
2. swapped pirate captain hat for black bandana (pirate captain hats still on pirate ship)
3. removed pirate garb (pirate garbs still on the pirate ship)
4. swapped the engineering backpack for a pirate backpack which is filled and contains a survival box, cutlass, pirate revolver and eyepatch.
5. swapped workboots for lacedshoes
6. pirategear still keeps the appraisal tool, passenger PDA and utility belt.

this pirate gear is used by the pirate spawner so pirate that spawn will now have this loadout. 
i also created a piratecaptaingear set however there is currently no spawner for a piratecaptain.

I have made no alterations to the actual pirate.yml map in this pull request.

### CODE REVIEW

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
previous prs have commits on this branch. Please remove them.
You are more than likely creating branches off of previous branches, instead of master.

**Comment by brainfood1183** [comment]
not sure how you know previous prs have commits on this branch? looking at files none of files from any other branch?

**Comment by EmoGarbage404** [comment]
> 

The entirety of originstation is on this pr.

**Comment by brainfood1183** [comment]
so i need to rebase pirateassetbrnach to master? is there a chance i will lose this pr or commited changes?

**Pull request closed without merging**
