### PR TITLE
Added "wink" and "tearfully smiles" emotes + more cry emote variations

### PR DESCRIPTION
**Pull request by jamessimo**
## About the PR

Added "winks" when you use 
;), ;] (+ inverse)

Added "tearfully smiles" when you use
:'), ='], :'] (+ inverse)

Added more ways to "cry" with 
:'(, ='[ etc.. 

also added 07 as salute emote. 

## Why

Found myself not being able to wink using a very common emotes like ;) and cry with :'(. 
Just to give some robustness to emotes which are common place.

## Media

- [X]  this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Can now "wink" with the text emote ;) or ;]
- add: Can now "tearfully smile" with the text emote :') and similar variants 
- tweak: Added more ways to "cry" with the emote :'( and similar variants

### CODE REVIEW

**Review by PJB3005 — APPROVED** [review]

**Comment by potato1234x** [comment]
now make >:) or >:(

**Comment by jamessimo** [comment]
> It's me.. agent 0@salutes

that wouldn't happen because it only sanitizes whole words.

**Comment by IProduceWidgets** [comment]
Barely related, and not un this pr, but wth is 

> ;_;7
tearfully salutes 

Lmao.

**Comment by jamessimo** [comment]
> now make >:) or >:(

I avoided these because its not clearcut what the intent of >:) is. Its not angry and its not happy.  >:( feels more than a frown and didn't want to add a new term.

**Pull request merged**
