### PR TITLE
remove atlas, cluster, europa, saltern

### PR DESCRIPTION
**Pull request by Emisse**
basically, these maps have had issues on and off since their inception. be it design, layout, lack of updates, etc. we are moving in a direction where we are working on refining what we have and trimming off things we don't need. ill list reasons for each's removal below. thank you to everyone who maintained these maps over the years.

atlas: inspired by goons atlas, created by emisse in 14. maintained by deltanedas for the last year or so. this map is fundamentally flawed and needs a complete rework to survive. it has a future in ultra low pop servers if redesigned for current year from the ground up.

cluster: created by scribbles. maintained on and off by many people. a cute little low pop with a ring like design, does not hold up current year and basically same issues as atlas.

europa: created by ubaser. a test bed for planetary stations, not seen by many but it worked well for what it was.

saltern: created by PJB. maintained by emisse and then nairod. the first map ever made for ss14. you can tell. needs a reimagining.

🆑 
- remove: Atlas, Cluster, Europa, & Saltern removed from the game.

### CODE REVIEW

**Comment by bruhmogus** [comment]
"these maps had slight issues before so we need to remove half of the map pool"

**Comment by Emisse** [comment]
reading comprehension

**Comment by TheDoctor1977** [comment]
Just deleting them seems excessive, could they not just be removed from rotation until someone goes in and fixes their issues?

**Comment by Emisse** [comment]
waste of space and maintenance burden

**Comment by regenpower** [comment]
tragedia
o7

**Comment by Dutch-VanDerLinde** [comment]
remove packed pls....

**Comment by Hanzdegloker** [comment]
Damn, low-pop map purge

**Comment by NotSoDana** [comment]
finally

**Comment by Boaz1111** [comment]
not to worry chat i’m gonna fix cluster

**Comment by slarticodefast** [comment]
Damn, that's a lot of low pop maps gone.
RIP Saltern

**Comment by EmoGarbage404** [comment]
atlas rest in piss

**Comment by SlamBamActionman** [comment]
This is a bit frustrating because, as someone who wants to get into mapping for SS14, the "issues" listed do not explain anything other than some vague elusion to bad design. It was the same when Gemini was removed, the only answer I could get was "it was designed in an old way".

> cluster: does not hold up current year and basically same issues as atlas.

Okay but *what are the issues*? Is it that it is lacking space in some departments? Is the maints pathing too free, or too restrictive? The distribution of departments relative to each other? 

I'm not arguing against removing the maps (no matter how much I love Cluster) and if you say they needed to go I believe you. But, concretely, what are the issues?

**Comment by Emisse** [comment]
if youre interested feel free to ask me in discord whenever

**Comment by SlamBamActionman** [comment]
Emisse on Cluster, from Discord:

> every firelocked area needs to be redone to current standards (1 escape strategy per area), central area should be redone to allow more space/more privacy, medical layout is bad (just big and empty and open cryo and surgery should be closer), maint detailing needs redoing (too visually cluttered by mismatched tiles and firelocks and catwalks), firelocked areas in maints need redoing, cameras will need complete redo when AI is out in a week, security is "ok" but warden really needs to be able to see cells from his office so it should be rearranged, EVA is too far from everything, needs to be a pretty simple path from HoP (preferably), engineering way too cramped, atmos needs expansion, they need room for another engine, cargo bay needs expansion too small, substation 1x1 rooms are old fashioned and need killing, arrivals should probably be protected since it is completely exposed 180 degrees at this point and every arrivals has at least 90 degrees of protection to full, atmos and air alarms and fire alarms need complete redoing due to the age

**Comment by Killerqu00** [comment]
image
According to this image by Boaz, this would leave 2 maps for population between 10 and 30, and no maps at all between 7 and 10.

**Comment by Brandon-Huu** [comment]
Nah, that's crazy.

Emisse destroying the game

> if youre interested feel free to ask me in discord whenever

Why wouldn't you just create an Issue for it on github so that everyone can easily see what is wrong with the maps.

**Comment by Scruq445** [comment]
I FUCKING LOBE SELF-MERGERS! I FUCKING LOVE WHEN PEOPLE IN POWER DIRECTLY GO AGAINST THE WILLS OF THE PEOPLE FOR THEIR OWN CHANGES.

**Comment by EmoGarbage404** [comment]
"will of the people" larpers when you ask them to exert a fragment of that will to update and maintain maps instead of leaving one person to work on 10+

**Comment by MWGMorningwood** [comment]
The real focus here should be improving mapping as a whole. If maintaining these is such a burden, why has the system yet to be improved?
We (MWG) will be looking at this over the next few weeks. If something can be made to aid in creating/editing maps sensibly, maybe the 'burden' will be reduced or eliminated. It might even open up the possibility of more contributors on the mapping side.

Regardless, I think removing the maps alone is the wrong call. This is treating a symptom, not the main issue.

**Comment by Brandon-Huu** [comment]
> "will of the people" larpers when you ask them to exert a fragment of that will to update and maintain maps instead of leaving one person to work on 10+

Maybe if the people complaining actually opened issues for the map something could be done.

**Comment by ZeroDayDaemon** [comment]
I am willing to say that I am willing to maintain saltern.
Me actually doing it is another matter entierly.

**Comment by Brandon-Huu** [comment]
> "will of the people" larpers when you ask them to exert a fragment of that will to update and maintain maps instead of leaving one person to work on 10+

image

Cluster had no opened issues when it was removed from the game

**Comment by metalgearsloth** [comment]
> if youre interested feel free to ask me in discord whenever

Reading comprehension.

**Pull request merged**
