### PR TITLE
Fix windoor deconstruction

### PR DESCRIPTION
**Pull request by ElectroJr**
Door & windoor construction require you to add door electronics. But for some reason I'm not sure of, doors & windoors don't start with door electronics (@ShadowCommander)? They don't currently serve a purpose outside of construction, but for that reason alone they should at least be spaned into doors.

Doors had a workaround with a separate deconstruction step that would spawn in door electronics when deconstructed with an empty container, windoors didn't have this. The result was that you could only deconstruct windoors that were constructed by players instead of spawned in.

This just makes doors start with door electronics and removes the deconstruct workaround.

:cl:
- fix: Fixed being unable to deconstruct windoors.

### CODE REVIEW

**Comment by ShadowCommander** [comment]
The reason Airlocks didn't spawn with electronics is so that I didn't have to do map changes. That should probably be done now, but need to do so when no map PRs are open or to merge those first.

**Comment by Lamrr** [comment]
> The reason Airlocks didn't spawn with electronics is so that I didn't have to do map changes. That should probably be done now, but need to do so when no map PRs are open or to merge those first.
> 
> Doing this without map changes will cause the next person to do map changes to have all the airlock boards spawned as part of their PR.

I'm confused, why does it require map changes?

**Comment by ElectroJr** [comment]
> Doing this without map changes will cause the next person to do map changes to have all the airlock boards spawned as part of their PR.

AFAIK mapping is meant to be done on an un-initialized map, before MapInit events are run. As the boards are added on map-init, that should be fine, right?

**Comment by ShadowCommander** [comment]
So, when this was initially put in, it failed some test, so I tried checking out the old commit to check what went wrong, but couldn't get it to work. Since there's no failing checks now, then it can _probably_ be removed now.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
