### PR TITLE
Adding a ghost role for parrots.

### PR DESCRIPTION
**Pull request by marboww**
## About the PR

This is a PR that adds a 5% chance that when creating a parrot it will become a ghost role. 
## Why / Balance

Our parrot has a voice and a speech accent (#26340). It would have been more appropriate to make him a ghost role.
## Technical details

Changes were copied from part of the MobMonkey prototype
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### Change history
- Chance change from 10% >>> 2.5%
- Chance change from 2,5% >>> 5%

**Changelog**

:cl: marbow
- add: Now there is a chance that parrots can become a ghost role.

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
Ghost role + movement + ability to talk normally is really strong considering most ghost role pets are completely incapable of speech.

**Comment by marboww** [comment]
> Ghost role + movement + ability to talk normally is really strong considering most ghost role pets are completely incapable of speech.
> 
> Pirate parrots absolutely should be a ghost role though.

that's right. In such cases, what is the best thing to do? Increasing the price of livestock parrots? Or reducing the chances of a ghost role?

**Comment by Dutch-VanDerLinde** [comment]
just make it rarer

**Comment by marboww** [comment]
ok

**Comment by BellwetherLogic** [comment]
Maybe they have a list of words they can actually say, and everything else gets replaced by bird noises? 

Bonus fun if there's a small chance that if you hear a word it gets added to the list.

**Comment by metalgearsloth** [comment]
What about poly? Isn't that supposed to be what parrots are for.

**Comment by mirrorcult** [comment]
agree with sloth, this isnt really what parrots are for, just need to implement ss13 parrots, theres plenty of other pet ghost roles to pick

**Pull request closed without merging**
