### PR TITLE
Gas miner adjustments

### PR DESCRIPTION
**Pull request by Sothanforax**
## About the PR

Increase the outside pressure of the o2/n2 gas miners in most stations applicable. (Don't ask me about Aspid, I already have a headache.)
mapping work was all @akato-harris 
## Why / Balance

Stations could not be repressurized at the previous 300kPa on all the gas miners, this aims to change that.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None that either of us are aware of.

**Changelog**

:cl:
- tweak gas miners on Atlas, Core, Fland, Gemini, Marathon, Meta, Omega, Origin, Packed, and Saltern to 4000kPa.

### CODE REVIEW

**Comment by akato-harris** [comment]
I spent way too long on this... My brain is leaking out my ears. Time to drink...

**Comment by Emisse** [comment]
also atomize mapping prs into 1 pr for map

**Comment by Sothanforax** [comment]
> we have prototypes for gas miners for stations, they should just be swapped to that

could we just change the prototype and close this then?

**Comment by K-Dynamic** [comment]
> we have prototypes for gas miners for stations, they should just be swapped to that

I think they have weird transitions so swapping out might require new intemediary gas miners

Gas miner 1 has like 50 kpa or something
Gas miner 2 has 300 kpa
Gas miner 3 has 4500 kpa

**Comment by Emisse** [comment]
i can just update them next time i update maps

**Comment by akato-harris** [comment]
It looks like Shuttle has 300kPa, Station has 1000kPa, and Large Station has 4500kPa. However, the issue was a majority of stations were running the miners at 300 kPa.

**Comment by deltanedas** [comment]
> Stations could not be repressurized at the previous 300kPa on all the gas miners, this aims to change that.

this is a krill issue i think

**Comment by deltanedas** [comment]
yep this is 100% unnecessary

1. saltern
2. gas mixer 21% oxygen everything at max pressure, but keep distro pump off for now
3. use f7 fill gas to remove all oxygen and almost all nitrogen
4. turn on distro
5. watch station go from vacuum to safe in ~5 seconds

**Comment by Emisse** [comment]
argh

**Pull request closed without merging**
