### PR TITLE
make fire not burn through hardsuits

### LINKED ISSUE #21290: you cant make armor fireproof without making it laser proof
## Description

since fire does heat and lasers do heat, theres no way to distinguish between getting shot with a laser and being on fire so firesuits will make you nigh invincible when deathsquad comes knocking
**Reproduction**

spawn in a CBURN guy
spawn in a pulse rifle
shoot the CBURN guy until they go horizontal and count every blast

**Additional context**

firesuits should be fire resistant, but not pulse rifle resistant

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
instead of fire burning your skin through hardsuits they heat you up

- normal firesuit has worst fire protection because its not even pressure sealed
- hardsuits have 95% protection
- atmos hardsuits are immune to fire damage

also nerfed atmos hardsuit heat/cold damage reduction so lasers and mr freeze gaming work on atmosia

made default hardsuit temperature protection be 1% not 0.1%, it needs further tweaking because full firestacks dont change temp at all even with just atmos fire helmet so somethings up with it

fixes #21290

## Why / Balance
makes no sense, now atmos fire suit is actually good at walking in fires.

hardsuit users dont get burned to death, they get baked alive (ideally, see temperature not changing funny)

## Technical details
added inventory relayed `GetFireProtectionEvent` which `FireProtectionComponent` uses
simply reduces fire damage

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Firesuits and hardsuits now protect your skin from fire, you will instead die of heatstroke.

### CODE REVIEW

**Comment by Everturning** [comment]
it's a firesuit, at least make it capable of firewalking

**Comment by deltanedas** [comment]
yes atmos firesuit has full fire protection

**Comment by Golinth** [comment]
holy moly thats a massive nerf to atmos damage reductions

**Comment by deltanedas** [comment]
atmos suit should be for tanking laser shots and nonexistent cold weapons it should be for walking around fires

**Comment by Golinth** [comment]
Agreed 100%. Will this affect the damage they take from being warmed up by the fire around them though?

**Comment by deltanedas** [comment]
leaving insulation adjustment to another pr but right now hardsuits are basically immune to fire because they perfectly insulate

**Comment by mirrorcult** [comment]
was the atmos armor change intended, i definitely feel like they should have significantly less fire armor with this

**Comment by mirrorcult** [comment]
otherwise this doesnt change much

**Comment by deltanedas** [comment]
> was the atmos armor change revert intended, i definitely feel like they should have significantly less fire armor with this

atmos armour before this is for tanking laser shots and esword attacks they still die quickly to a proper fire
right now they actually take no damage at all from fire because temperatureprotection is insanely strong and still needs reworking, probably with per-limb stuff in newmed

**Comment by mirrorcult** [comment]
yes i mean that 53b2464e4137c29157f2778a4e0dc891547ac4a2 seems to have reverted the change that makes atmos not tank lasers and shit

**Comment by mirrorcult** [comment]
ok pro

**Comment by deltanedas** [comment]
also removed the 50% caustic resistance from atmos hardsuit who tf did this

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
