### PR TITLE
Add nukie agent combat defib

### LINKED ISSUE #16299: Nukie Agent needs combat defibs
title
i dont want to give them regular defibs
combat defib not coded yet
todo

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Closes #16299 
Adds the combat defibrillator to the game
The sprites can definitely be worked on, but it's good enough for now
Here are the things that are different
- Has an item size of 20
- Is one handed
- Does not require a battery
- Uses charges, with 2 maximum charges and a 60 second regeneration time
- Cannot be turned off
- Spawns with the nukie medic
- Heals 10 more asphyxiation

**Media**

image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the combat defibrillator to the nukie medic duffel

### CODE REVIEW

**Comment by notquitehadouken** [comment]
UH OH

**Comment by notquitehadouken** [comment]
fixed it

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
You shouldn't copy-paste the existing system for this, it should just use that instead.

**Comment by Slava0135** [comment]
IMO nukies should explode on death

**Comment by EmoGarbage404** [comment]
> > You shouldn't copy-paste the existing system for this, it should just use that instead.
> 
> there's like a 70 line difference between the original and this one i don't know what you mean

it is literally 100% the same with the exception of using charges instead of batteries. You are completely able to combine them.

**Comment by notquitehadouken** [comment]
fuck this

**Comment by deltanedas** [comment]
pro just have a helper function that checks for limitedcharges or powercell slot then use that everywhere

**Comment by notquitehadouken** [comment]
this shit would NEVER be merged today

**Pull request closed without merging**
