### PR TITLE
Replace noSpawn: true with categories: [ HideSpawnMenu ]

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

- I replaced every instance of `noSpawn: true` with `categories: [ HideSpawnMenu ]`, which has the traits of hiding the entity from the spawn menu and is not inheritable.

- I also added the `Actions`, `Spawner`, or `Debug` category where it was relevant not that you would ever see it, given that it's hidden from the spawn menu.....

## Why / Balance

`EntityPrototype.NoSpawn` has a message saying `[Obsolete("Use HideSpawnMenu")]`, but ymls don't actually trigger this warning. I removed the last two references to `NoSpawn` in the codebase here: https://github.com/space-wizards/space-station-14/pull/30082, so it's as good as time as any to fully obsolete the field.

## Technical details

`noSpawn: true` is used to hide the entity from showing up in the Entity Spawn Panel, for whatever reason it was replaced by the `hideSpawnMenu` field.

I think I could technically replace `noSpawn: true` with `hideSpawnMenu: true`, but I also found zero other instances of this in the codebase. The only places I found `hideSpawnMenu: true` used was for the `entityCategories` themselves, so I'm just going to use the `HideSpawnMenu` category. The HideSpawnMenu category has a description of `# simple category that just exists to hide prototypes in spawn menus` so I guess it feels at least intended to use it this way.

HideSpawnMenu updated in: https://github.com/space-wizards/RobustToolbox/pull/5061

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot 2024-07-16 131313

## Breaking changes

Nothing actually broken...

**Changelog**

not even player facing

### CODE REVIEW

**Comment by Winkarst-cpu** [comment]
118 changed files, this is will never be merged 😞

**Comment by Plykiya** [comment]
I'm a little bit iffy on `Resources/Prototypes/Entities/Effects/mobspawn.yml`

I added the Spawner category to them because they're literally called mob spawners, but it's not technically a Spawner in the sense of the ghost roles like the nukeops or dragon

**Comment by Plykiya** [comment]
> 118 changed files, this is will never be merged 😞

good thing it's all yml :godo:

**Comment by Winkarst-cpu** [comment]
My one-line yml change was hanging around for around 3 days. Some math, and your will take around 354 days :trollface:

**Comment by IProduceWidgets** [comment]
I scrolled through all the yml changes and they all seem fine. I also think the test is probably fine, but someone smorter than me should probably test the test tests as expected.

**Comment by Plykiya** [comment]
fuckin lowercases

**Comment by Plykiya** [comment]
fuck it we ball

**Pull request merged**
