### PR TITLE
Syndicate pAI for uplink [broken]

### PR DESCRIPTION
**Pull request by crazybrain23**
## About the PR

Part 2 for #18625, changed the description to retain the HHGTTG reference and added it to the uplink. You can only buy one pAI per uplink to prevent ghost role spam.

**Media**

https://github.com/space-wizards/space-station-14/assets/44417085/da6671d6-340c-4c47-bdf5-193ff56865a5

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: crazybrain
- add: Uplinks can now purchase one Syndicate pAI.

### CODE REVIEW

**Comment by lzk228** [comment]
sprite definitely should be looking like normal

**Comment by crazybrain23** [comment]
I think I broke something.

**Comment by deltanedas** [comment]
you committed engine somehow
`git checkout --theirs RobustToolbox` and commit

**Comment by crazybrain23** [comment]
Okay so now it's worse

**Comment by crazybrain23** [comment]
I'm just going to make a new branch for this.

**Pull request closed without merging**
