### PR TITLE
remove extended from voting pool

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
who even likes this?
**Screenshots**

**Changelog**

:cl:
- fix: Extended is no longer in the game mode voting pool.

### CODE REVIEW

**Comment by DogZeroX** [comment]
At this point just disable voting since we only have extended and secret as voteable

**Comment by EmoGarbage404** [comment]
> At this point just disable voting since we only have extended and secret as voteable

counterpoint: a vote with only 1 option is funny

**Comment by DogZeroX** [comment]
Dumbasses calling for vote all the time for no reason moment.

**Comment by keronshb** [comment]
Based???

**Pull request merged**
