### PR TITLE
Antimov in both Traitor & Nukie Uplinks

### PR DESCRIPTION
**Pull request by LordEclipse**
## About the PR
I added the Antimov AI Lawboard to both the Traitor and Nukie Uplinks, they are priced at 14 and 24 TC respectively.

## Why / Balance
Syndies/Nukies need a reliable way to compromise the A.I., and Antimov should not be available to crew roundstart.

## Media
image

**Changelog**

:cl:
- add: The Antimov Law Board is now available in both the Traitor and Nuclear Operative Uplinks, 14 and 24 TC respectively.

### CODE REVIEW

**Comment by Djungelskog2** [comment]
what abt overlord

**Comment by cohanna** [comment]
Very steep price for a pretty useless item for traitors. Sure you can make the AI go genocidal but unless you are doing budget nukies (which you wouldn't be able to with this price) you wouldn't see your value returned since you would also be caught in the crossfire. Personally, I would make it like 12tc for both which is just enough to make it the "main item" for a round but leaves enough leeway for a traitor to do literally anything else.

**Comment by cohanna** [comment]
nevermind i missread lol, this looks good

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
Maybe make the law board cost 6-10 tc for the traitors?
14 tc leaves you with only 6, which isn't enough to even buy an EMAG for hacking.
Plus it makes the player entirely reliant on AI, which isn't quite good

**Comment by Djungelskog2** [comment]
> Maybe make the law board cost 6-10 tc for the traitors? 14 tc leaves you with only 6, which isn't enough to even buy an EMAG for hacking. Plus it makes the player entirely reliant on AI, which isn't quite good

i agree, id be fine with 10-12 though

**Comment by PJB3005** [comment]
I am genuinely begging people to just code Freeform already

**Comment by pheenty** [comment]
The problem with antimov for traitors is that they are crew members too

**Comment by LordEclipse** [comment]
> I am genuinely begging people to just code Freeform already

Well, if freeform does get coded I can just swap it out.

**Comment by baddiePRO** [comment]
what if ninja spawned with a spider clan lawset board too?

**Comment by Sadopeer** [comment]
14 and 28 are very high, id put it down to 8. You still have to break in, plus if you are caught in the act it's game over for you even if you manage to put it in.

**Comment by superjj18** [comment]
> what if ninja spawned with a spider clan lawset board too?

Meh, with ninja it's a lil too easy with their teleport.  Maybe once AI has turrets and other defenses available so that it's more complicated than a 10 second tp in, swap, tp out.

**Comment by baddiePRO** [comment]
> Meh, with ninja it's a lil too easy with their teleport.  

fair point, maybe put the spider clan board in the circuit imprinter?

**Comment by Everturning** [comment]
add overlord for the funny s.e.l.f. agents

**Comment by slarticodefast** [comment]
The maintainer vote decided we can add this in the meantime until we have proper freeform law upload.

**Pull request merged**
