### PR TITLE
Remove archaic accent

### PR DESCRIPTION
**Pull request by lzk228**
## Why / Balance

miku said its awful or terrible or something
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- remove: Removed archaic accent.

### CODE REVIEW

**Comment by Hmeister-fake** [comment]
Please do not, i beseech you. its a funny accent that a lot of people use.

**Comment by metalgearsloth** [comment]
@UbaserB was this yours I forgor

**Comment by EmoGarbage404** [comment]
if you want to be funny and talk in an archaic way just actually type with archaic language instead of using an accent that breaks for a good 90% of words and makes people incomprehensible.

**Comment by UbaserB** [comment]
> @UbaserB was this yours I forgor

it was someone's elses but i did a huge overhaul so might as well be mine

**Pull request merged**
