### PR TITLE
Nerfs Synaptizine to 6 damage per 1u instead of 15 per 1u

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Synaptizine was absolutely busted killing anybody who drank only 7u of it with uncurbable radiation damage with 10 poison damage and 5 radiation damage per tick this nerfs the chemical into a more manageable form curing 1u of Synaptizine with 3u of Dylovene it still dangerous but more of a slow poison and not and insta kill machine 
**Screenshots**

5u examples
Before:
SS14 Loader_ULAiA9Z7zv
After:

**Changelog**

:cl:
- tweak: Synaptizine damage per unit nerfed from 15 to 6

### CODE REVIEW

**Comment by SethLafuente** [comment]
I assume there is no need for changelogs for this small kind of changes just making sure

**Comment by SweptWasTaken** [comment]
> 
> 
> I assume there is no need for changelogs for this small kind of changes just making sure

>>Generally, only put things in changelogs that players actually care about. Stuff like "Refactored X system, no changes should be visible" shouldn't be on a changelog.

I think players would care about a nerf. I've updated your changelog.

**Comment by SethLafuente** [comment]
yeah I kind of accidentally put it at 0.70 when I meant to put it at 0.67 just notice the error a second ago it dosent make much difference but its kind of important

**Comment by SweptWasTaken** [comment]
> 
> 
> yeah I kind of accidentally put it at 0.70 when I meant to put it at 0.67 just notice the error a second ago it dosent make much difference but its kind of important

I'll direct commit it.

**Pull request merged**
