### PR TITLE
Add wheelchair crafting & supporting crates

### LINKED ISSUE #19753: Wheelchairs have no obtainable source
## Description

They can't be crafted or bought, for example.

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR

Closes #19753
Closes #19625
Place to utilities category

7 seconds to craft
Materials:
- 4 steel
- 6 metal rod

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Morb0, Kezu02
- add: Added wheelchair crafting
- add: NanoTrasen has begun producing spare canes and wheelchairs for our disabled crew. Order them from Cargo!

### CODE REVIEW

**Review by ficcialfaint — APPROVED** [review]

**Comment by Morb0** [comment]
Apply changes from https://github.com/space-wizards/space-station-14/pull/19625
image
Screenshot 2023-09-04 142340

**Review by LankLTE — CHANGES_REQUESTED** [review]
The white cane probably shouldn't be purchasable- the idea is that it's exclusively for the blind and with this change I could see Cargo running around with a bunch of them.

**Comment by revsys413** [comment]
> The white cane probably shouldn't be purchasable- the idea is that it's exclusively for the blind and with this change I could see Cargo running around with a bunch of them.

i would argue accounting for that possibility is less important than giving blind characters a chance to get a replacement cane if/when it gets stolen

**Comment by LankLTE** [comment]
> i would argue accounting for that possibility is less important than giving blind characters a chance to get a replacement cane if/when it gets stolen

The cane doesn't actually do anything, though. It's just to inform you that they're blind. That point is lost when cargo can order 3 of them for 300 spesos and now half of cargo is running around with one. Even if a blind person did lose one, you now have 2 extras that cargo is probably going to start walking around with.

**Comment by revsys413** [comment]
> The cane doesn't actually do anything, though. It's just to inform you that they're blind. That point is lost when cargo can order 3 of them for 300 spesos and now half of cargo is running around with one. Even if a blind person did lose one, you now have 2 extras that cargo is probably going to start walking around with.

that does make sense—maybe just have them individually orderable?

**Comment by Kezu02** [comment]
> > The cane doesn't actually do anything, though. It's just to inform you that they're blind. That point is lost when cargo can order 3 of them for 300 spesos and now half of cargo is running around with one. Even if a blind person did lose one, you now have 2 extras that cargo is probably going to start walking around with.
> 
> that does make sense—maybe just have them individually orderable?

I placed it as three in https://github.com/space-wizards/space-station-14/pull/19625 since I thought it'd be odd to have a shipment crate come in with just one cane inside and seemed like a waste of space logistics wise, though that would leave spare canes for cargo to possibly play around with as mentioned earlier. They aren't good wielded weapons either so their use remains solely for the blind.

**Comment by LankLTE** [comment]
I'm fine with this option if the crate is changed to contain one cane rather than 3 (while keeping the price the same). Giving 3 is unnecessary and would just lead to people who aren't blind running around with loads of them.

**Comment by CatMagic1** [comment]
Make canes show footsteps within a certain range (probably not in this pr).

**Pull request closed without merging**
