### PR TITLE
Emagging reclaimer now ignores if target is dead

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Does what it says on the tin. This is my first time coding in C#, so please point out if I've made any critical mistakes.

**Changelog**

:cl:
- add: Emagging a biomass reclaimer now allows you to gib live targets.

### CODE REVIEW

**Comment by Elijahrane** [comment]
fwiw in the original PR I considered implementing this and decided against it

**Comment by GoodWheatley** [comment]
> fwiw in the original PR I considered implementing this and decided against it

Emagging a recycler does the same thing and nobody has a problem with it, even though it usually means shoving a stunned person down disposals is a free gib. Plus the biomass reclaimer is usually in a very public room, and it still requires a 7 second DoAfter.

**Comment by Elijahrane** [comment]
> > fwiw in the original PR I considered implementing this and decided against it
> 
> Emagging a recycler does the same thing and nobody has a problem with it, even though it usually means shoving a stunned person down disposals is a free gib. Plus the biomass reclaimer is usually in a very public room, and it still requires a 7 second DoAfter.

emagging recyclers was removed a long time ago

**Comment by moonheart08** [comment]
Not sure this is a good idea.

**Comment by GoodWheatley** [comment]
Closing this for now since apparently this might be OP, will think of a better emag interaction later

**Comment by Jackrost** [comment]
Few ideas:
1. Jam reclaimer so you need time to clean it.
2. Spread miasma after completion or while it's working

**Pull request closed without merging**
