### PR TITLE
Require Wield To Activate Double-bladed ESword

### LINKED ISSUE #32772: Single-hand wield dsword when opened in container/on the floor
## Description
You can wield and attack with a dsword with onehand if you activate it in your backpack / on the floor before equipping it
(Not sure if this just changes the effects)

**Reproduction**
- Get retracted dsword
- Put it in container / backpack or on the floor
- Activate it in context menu
- Equip it
- You can now hold it and swing it with only one hand, leaving the other hand free

**Screenshots**
image
image
image
image

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by thetolbean**
## About the PR
Despite being balanced around being wielded, the double-bladed esword could be swung using only one hand if activated on the ground and then picked up. Now, the double-bladed esword can only be activated by wielding it, and can not be activated on the ground. This means that throwing it, putting it down, or dropping it turns the blade off.

## Why / Balance
Fixes #32772 and enforces intended weapon balancing.

## Technical details
Add `onActivate: false` component to the double esword, preventing it from being activated outside of the user wielding it.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: The double-bladed esword now can only be activated when wielded.

### CODE REVIEW

**Comment by ScarKy0** [comment]
Hopefully this doesnt break the syndie assault borg's esword?

**Comment by thetolbean** [comment]
> Hopefully this doesnt break the syndie assault borg's esword?

I tested both, and this does not affect the [one handed] variant that the borgs use

**Comment by thetolbean** [comment]
{3EE4C8A7-D0B7-45F8-93D2-3B89EDF709D8}

I have realized that the double bladed esword is more broken than I had originally thought. If you enable it on the floor and then pick it up, you can no longer attack with it, but the model is broken as it pairs the wielded blades with the unwielded handle. Looks like I will have to turn it off on pickup

**Comment by thetolbean** [comment]
This change also prevents people from attacking with it when it is unpowered as well, so I am going to have to look into degerming if it is powered on or off

**Comment by keronshb** [comment]
> {3EE4C8A7-D0B7-45F8-93D2-3B89EDF709D8}
> 
> I have realized that the double bladed esword is more broken than I had originally thought. If you enable it on the floor and then pick it up, you can no longer attack with it, but the model is broken as it pairs the wielded blades with the unwielded handle. Looks like I will have to turn it off on pickup

Some of this is fixed in the hypereutactic blade PR, so you can lift some of the fixes from that

**Comment by thetolbean** [comment]
I have modified how I've gone about this

Initially I had added the `MeleeRequiresWield` component, but that had a few unintended side effects:
- You could not attack with the weapon turned off
- You still get the benefit of the high reflect chance
- The sprite is completely broken

The route i have gone now, is adding the parameter `onActivate: false` to the itemToggle component. This has one issue which is not game breaking or vital:
- You can no longer put down, drop, or throw the weapon without it deactivating

However, this has the pros of:
- You can attack with the weapon turned off
- You no longer get the benefits of the high reflect chance without wielding it
- The sprite behaves as intended
- You can no longer have the activated weapon in one hand

**Comment by keronshb** [comment]
> I have modified how I've gone about this
> 
> Initially I had added the `MeleeRequiresWield` component, but that had a few unintended side effects:
> 
>     * You could not attack with the weapon turned off
> 
>     * You still get the benefit of the high reflect chance
> 
>     * The sprite is completely broken
> 
> 
> The route i have gone now, is adding the parameter `onActivate: false` to the itemToggle component. This has one issue which is not game breaking or vital:
> 
>     * You can no longer put down, drop, or throw the weapon without it deactivating
> 
> 
> However, this has the pros of:
> 
>     * You can attack with the weapon turned off
> 
>     * You no longer get the benefits of the high reflect chance without wielding it
> 
>     * The sprite behaves as intended
> 
>     * You can no longer have the activated weapon in one hand

https://github.com/space-wizards/space-station-14/pull/32414/files#diff-f50dce3ddc3b090c3a6851ce337a78cf0d86c78cc10eb8061f630a8106d7e4c6

MeleeRequiresWield works for this.
You need to do some sprite renaming for it to work properly.

**Comment by thetolbean** [comment]
> https://github.com/space-wizards/space-station-14/pull/32414/files#diff-f50dce3ddc3b090c3a6851ce337a78cf0d86c78cc10eb8061f630a8106d7e4c6
> 
> MeleeRequiresWield works for this. You need to do some sprite renaming for it to work properly.

This does prevent the user from attacking with the weapon in one hand, which is part of the issue, but it does not take into account if the weapon is activated or not. So if someone wants to hit someone with the blades disabled, it prevents them.

This would also require new sprites, as the Dsword does not have a sprite for an unwielded blade, only an unwielded handle and wielded blades.

The main issue with allowing it to be used in one hand is the high reflect chance. If you have it in one hand, you still have the benefit of the 75% reflect chance, which is balanced under the assumption that it will only be held in both hands. In comparison to the eshield it has a lower reflect chance, but it also doesn't burn out and provides a constant reflection bonus.

In my implementation, it prevents the dsword not only from attacking with one hand, but it also prevents it from providing its above average reflection chance.

**Review by slarticodefast — APPROVED** [review]
Yep, this is pretty much a bugfix. Before it acted weirdly when activated on the ground. With this PR it works a intended. Thank you for your contribution.

**Review by Errant-4 — APPROVED** [review]
Tested, looks good

**Pull request merged**
