### PR TITLE
Escape pods

### PR DESCRIPTION
**Pull request by metalgearsloth**
Forgot I coded this oop sorry emisse.

Most of the changes are me cleaning up shuttle namespaces a lot and separating emergency stuff from generic shuttle behaviours.

https://user-images.githubusercontent.com/31366439/227386944-98a36a1c-7e50-4e5b-ad92-f0f144823a0b.mp4

:cl: metalgearsloth & emisse
- add: Added escape pods.

### CODE REVIEW

**Comment by moonheart08** [comment]
If someone would be so kind as to write a guide entry on evac to go next to this PR that'd be cool

**Comment by deltanedas** [comment]
yeah its also needed for arrivals too since its not immediately obvious that you should wait, get on, wait then get off

**Comment by metalgearsloth** [comment]
Just needs a basic pod and we gucci.

**Comment by deltanedas** [comment]
have you tested if traitor escape objective works on pod, i think it is meant to

**Comment by metalgearsloth** [comment]
> have you tested if traitor escape objective works on pod, i think it is meant to

I thought they had to be on eshuttle in ss13.

**Comment by Emisse** [comment]
objectives should not work on pods, thats dumb

**Pull request merged**
