### PR TITLE
Add missing break on RemoveDisallowedJobs

### PR DESCRIPTION
**Pull request by metalgearsloth**

### CODE REVIEW

**Comment by Visne** [comment]
Wait, are jobs removed from the list completely if you don't meet the time requirements?

**Review by Visne — APPROVED** [review]

**Comment by metalgearsloth** [comment]
> Wait, are jobs removed from the list completely if you don't meet the time requirements?

Yes. This is used for gameticker when spawning a player to know which jobs they aren't allowed.

**Comment by Visne** [comment]
Ah, sure.

**Comment by Visne** [comment]
Feel free to just merg, tbh

**Pull request merged**
