### PR TITLE
Secret door

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

A secret door to secret rooms, for secret activities.

**Media**

изображение
изображение

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11
- add: Adds a Secret Door for construction

### CODE REVIEW

**Comment by deltanedas** [comment]
pro i did this a few weeks ago but couldnt get it to connect to walls when closed so i gave up

**Comment by brainfood1183** [comment]
I notice sprites only display in 1 direction? i assume you can rotate the object for walls running vertical?

**Comment by Nimfar11** [comment]
> I notice sprites only display in 1 direction? i assume you can rotate the object for walls running vertical?

Hmmm, no, it doesn't spin during construction. But it should. I'll get right on it.

**Comment by Nimfar11** [comment]
Now it's turning

**Pull request merged**
