### PR TITLE
PKA resprite

### PR DESCRIPTION
**Pull request by RiceMar1244**
## About the PR

This PR changes the textures for the salvage department's PKA weapon to look more like a rock-punching cannon. It replaces textures already in the game and adds wield sprites and belt equip sprites that weren't present before. It also adds a few animation assets for blinking lights into the .rsi folder for the future when that starts working.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

icon
inhand-left
inhand-right
wielded-inhand-left
wielded-inhand-right
equipped-BELT
packrat

**Changelog**

:cl: RiceMar
- add: To satiate the salvage department's rabid hunger for firepower, Nanotrasen has started manufacturing proto-kinetic accelerators with bulky cannon-like frames around the same internal machinery.

### CODE REVIEW

**Comment by RiceMar1244** [comment]
Oh I'm seeing there is an unsuccessful check related to the animation assets I put into the .rsi folder but weren't able to use yet. Let me know if those need to go.

**Review by lzk228 — CHANGES_REQUESTED** [review]
if you use new sprites, you should write them in meta.json

**Comment by RiceMar1244** [comment]
The animation sprites are not used because I found that there is probably not yet a way to make the conditional inhand animations work properly. I decided to leave them in here but i see that the checker is not happy about that, so I can remove them if I need to.

**Comment by RiceMar1244** [comment]
Alright I think I'm just going to remove the unused assets real quick

**Comment by RiceMar1244** [comment]
AH SHOOT

**Pull request merged**
