### PR TITLE
More jumpskirts, codersocks, beesocks and radioactive waste cleanup

### LINKED ISSUE #1231: ClothingPrefix is broken
Test case is looking at jumpskirts. If you equip one in-game it will just be the male version of the jumpsuit on your body. The YAML has a ClothingPrefix which is supposed to specify the prefix for the -equipped- version of the sprite. 

Unfortunately it doesn't appear to work. A hacky workaround for it is to rename the inhand clothing sprite to the prefix of the -equipped- clothing sprite and then it will work. 

It's hard to explain but if you look at the YAML files and the ingame reality you'll see that it's broken.

### PR DESCRIPTION
**Pull request by SweptWasTaken**
I did spend a lot of time working on this pr but it might be controversial. I do have a plan for the whole jumpskirts/jumpsuits thing to make it less "bloaty".

- Fixes #1231 (Will close this if this pr is merged)
- Adds jumpskirts for all of our current jobs.
- Massive cleanup of the jumpsuits/skirts we have already and adds unique inhand sprites for them all.
- Adds hydro, chemistry, paramedic, qm and all scrub jumpsuits.
- Replaces RD, HoS, Sec and Engineer jumpsuits with tg sprites. 
- Cleans up the clothing prototypes folder.
- MASSIVE refactor of the OuterClothing folder structure.
-- Removed a lot of duplicate/outdated OuterClothing sprites.
-- Separated OuterClothing into armor, coats, hardsuits, misc and suits.
- Adds coder and beesocks.
- "Fixed" the APC icon (Issue discovered here #1232 )

image
Discord_2020-06-23_13-46-43

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
Beesocks, good pr

**Comment by dootdoom** [comment]
image

**Comment by Rodey125** [comment]
NO SWEPT NO

**Comment by yeeyeh** [comment]
image

**Comment by Fikou** [comment]
n<fill out words>r

**Comment by SweptWasTaken** [comment]
How do I remove the picture of the dog taking a shit from my pr

**Comment by dootdoom** [comment]
you dont

**Comment by SweptWasTaken** [comment]
Forgot to mention that I also did a bit of an overhaul to the "tiles" folder, relegating all the unused tiles to their own folder.

**Comment by SweptWasTaken** [comment]
Closing because I can't be bothered to rebase this and i'm splitting this pr into multiple...

**Pull request closed without merging**
