### PR TITLE
Small clamp for fland cargo

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

Moved the lightbulb in the cargo storage 1 tile so there is no completely  dark corner, and added a table with a small hydraulic clamp on top of it in said corner.

## Why / Balance

Fland cargo starts with a ripley but it has no claw, making it useless until they do get one.
Asking sci for a big claw will still be worth it because it can carry 10 objects, while the small claw is only able to carry 4.

**Changelog**
1 moved light bulb
A table with a small hydraulic clamp on top of it in the corner of the cargo storage room.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Why doesn't every cargo dept get a ripley with small claw, even holding 4 items is a boon for a crate-heavy job

**Comment by Emisse** [comment]
no, was just testing things to see how it roundstart would do, i think this might giga conflict with the current fland pr up

**Comment by Arendian** [comment]
I'll wait for that other PR to be done first then

**Comment by Kadeo64** [comment]
small note, the small hydraulic clamp DOES NOT work with the Ripley APLU. It functions exactly the same as the normal clamp but is limited to the HAMTR only.

**Comment by Arendian** [comment]
> small note, the small hydraulic clamp DOES NOT work with the Ripley APLU. It functions exactly the same as the normal clamp but is limited to the HAMTR only.

I tested it locally on the latest version and was able to install and use it with the ripley

**Pull request closed without merging**
