### PR TITLE
Patch Cargo Lathe Abuse

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Reduces the selling price of several cargo abusable lathe-produced items, even through tech trees.

## Why / Balance
Infinite money glitches are stupid.

- Flatpack: $500 -> $250
- Force Field Projector: $250 -> $130
- Laser Rifle: $500 -> $420
- Disabler SMG: $500 -> $260
- Synthesizer: $200 -> $90
- Practice Laser Rifle: $500 -> $300
- All Cyborg Modules: $250 -> $100
- Practice Disabler: $500 -> $100
- Holobarrier Projector: $80 -> $50
- Science Magboots: $400 -> $200
- Rollerbeds: $200 -> $120
- Stun Baton: $100 -> $80
- Truncheon: $100 -> $80
- Surgery Drill: $60 -> $40
- Bruise Pack: $10 -> $5
- Ointment: $10 -> $5
- Jug: $80 -> $60
- C.H.I.M.P Handcannon: $500 -> $100
- Riot Shield: $100 -> $90
- Solar Tracker Electronics: $100 -> $85
- All Portable Generator Machine Boards: $100 -> $40
- Wallmount APU Electronics: $100 -> $40
- Wallmount Substation Electronics: $100 -> $40
- Wallmount Generator Electronics: $100 -> $20
- All Surgery Tools (Excluding Drill): $60 -> $20
- Large Beaker: $40 -> $20
- All Types of Craftable Bullets: $10 -> $1

## Technical details
Nothing extremely notable but I ripped out the sell price of each individual branch of round (.35, .45, .20, etc) and just put it on the base parent they all pull from instead.

## Media
- [X] This PR does not require an ingame showcase

**Changelog**
N/A

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Should this route not be added to the arbitrage test?

**Comment by EmoGarbage404** [comment]
> Should this route not be added to the arbitrage test?

I think the understanding is that converting raw materials into goods for profit is fine, it just needs to be a manageable amount

**Comment by metalgearsloth** [comment]
If it requires manual upkeep I would argue a test with a threshold would be easier long-term.

**Comment by EmoGarbage404** [comment]
> If it requires manual upkeep I would argue a test with a threshold would be easier long-term.

if someone wants to bikeshed a threshold then that's fine with me.

**Comment by K-Dynamic** [comment]
NT has now saturated the market with their knockoff lathable items, decreasing their prices and driving cargo out of business

**Pull request merged**
