### PR TITLE
add 2 new artifact effects

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
artifacts get 2 new types of effects: 
Spiral Attraction and Spiral Repulsion.

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/a9125e6b-8859-4ceb-90b9-c3f8fc92354a

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added 2 new artifact effect: attraction and repulsion

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Make both of these more common. These could very much just be t1 or t2.

**Comment by TheShuEd** [comment]
Done

**Comment by TheShuEd** [comment]
14 minute speedrun

**Comment by Clostyandr** [comment]
god bless TheShuEd

**Pull request merged**
