### PR TITLE
Security Whistle

### PR DESCRIPTION
**Pull request by brainfood1183**
Added - Security Whistle. Can be worn in the neck slot, using it makes a whistle noise. All security personnel except the detective start with a whistle in their neck slot.

https://github.com/space-wizards/space-station-14/assets/113240905/829cc67e-fd4a-4628-ba44-be10c430d32f

(sprite has been altered since video, changing the blue strap for a subdued red one)

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Nairodian** [comment]
#20079?

**Comment by JoeHammad1844** [comment]
not as good as the other whistle PR

**Comment by brainfood1183** [comment]
> not as good as the other whistle PR

Didnt realize there was another whistle pr, this can be closed if the other gets merged. I do think the exclaimation should only appear above the whistle blowers head though to draw attention to one blowing whistle. Not really a good way of doing it without being able to specifically target a person with the whistle first.

**Comment by AJCM-git** [comment]
> > not as good as the other whistle PR
> 
> Didnt realize there was another whistle pr, this can be closed if #20079 gets merged. I do think the exclaimation should only appear above the whistle blowers head though to draw attention to one blowing whistle. Not really a good way of doing it without being able to specifically target a person with the whistle first.

Gonna close this one in favor of the other one, you can request/help out with what you said in the other pr (feel free to reopen if the other one gets abandoned tho)

**Pull request closed without merging**
