### PR TITLE
Make mantles loadout only.

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This PR changes mantles to be only accessible through loadouts, requiring 20 hours of playtime as that head. 

It additionally removes mantles from dressers, and makes it so that there is no in-round way to obtain any.

## Why / Balance

It makes makes feel more special, and adds it as a "reward" for playing a bunch of command. This has been a feature planned for a long time, but had been put on hold because loadouts weren't a thing back then.

## Media

_An example of how it looks at 0 head playtime:_

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ubaser
- add: Mantles are now available in loadouts, requiring 20 hours of that head of department's time.
- remove: Mantles are no longer spawned in dressers or able to be printed at uniform lathes.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Cloaks are a Theif objective, that's why heads start with them in their dresser iirc

**Comment by Plykiya** [comment]
Removing them from dressers would make it impossible for the steal cloak objective to work if the head chooses not to spawn with the cloak, because a lot of command just does not choose to spawn with their cloaks.

**Comment by UbaserB** [comment]
> Removing them from dressers would make it impossible for the steal cloak objective to work if the head chooses not to spawn with the cloak, because a lot of command just does not choose to spawn with their cloaks.

i forgor that was a thing hold on

**Comment by Everturning** [comment]
Why do we need to gatekeep fashion?

**Comment by ZombieChibiXD** [comment]
> Mantles are no longer spawned in dressers or able to be printed at uniform lathes.
Inconsistent changelog with the pull.

**Pull request merged**
