### PR TITLE
Adding an anomaly scanner to the PDA

### PR DESCRIPTION
**Pull request by ImRenQ**
## About the PR
The PDA of any R&D employee can be used as an anomaly scanner

## Why / Balance
It's handy. The PDA medical department has such a feature

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/164364533/4c95c922-6bbf-4acd-b125-7ef016beb30a

**Changelog**
:cl: RenQ
- add: The PDA of any R&D employee can be used as an anomaly scanner

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
this really ought to just be a cartridge rather than entirely built in.

**Comment by ImRenQ** [comment]
can it stay that way until the cartridges for the medical department are added?

**Comment by lzk228** [comment]
why we have built-in health analyzer in med pda? because default health analyzer needs charge to use
also health analyzer is useful to ALL, not only medics, anomaly scanner useful only for sci, so i think only anomaly scanner should scan anomalies

**Comment by IProduceWidgets** [comment]
Does it mean they have to hold their PDA to keep the UI? Because that's kind of interesting.

**Comment by ImRenQ** [comment]
for this you need to use
    inHandsOnly: true
It works not only in the hands

**Comment by ImRenQ** [comment]
I will close this PR and try to understand how the cartridges work. 
Would a cartridge in the RD's closet be a good solution?

**Comment by lzk228** [comment]
> Would a cartridge in the RD's closet be a good solution?

put them in T2 anomaly tech

**Comment by ImRenQ** [comment]
> > Would a cartridge in the RD's closet be a good solution?
> 
> put them in T2 anomaly tech

Isn't it too late? by this point, R&D has stable anomalies, which will be enough for them until the end of the round
the cartridge will only slightly facilitate the work of scientists

**Comment by ImRenQ** [comment]
at this level, scientists have access to tools with which anomalies can be stable without the attention of scientists

**Comment by lzk228** [comment]
they have scanners in lockers at roundstart
can print scanners in T1 anomaly tech
and cartridges in T2 anomaly tech would be just nice addition
as i said before, the main thing why med pda can scan people - health analyzer requires charge
anomaly scanner doesnt

**Pull request closed without merging**
