### PR TITLE
Add nose customization to humans & dwarves

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR adds noses to humans and dwarves. They can be found as markings in the customization tab of character creation.

## Why / Balance

Noses are a great way to make characters more varied and add personality. 

## Technical details

Since most masks are made for normal noses, some of the new nose shapes would clip out of the masks without extra support for it. To fix this, noses get hidden similar to how hair is hidden when certain masks/helmets are equipped. This check is also performed on masks toggles. 

Some masks such as the normal breathing mask and medical mask work with the new noses. Because of this, some specificity is required with giving HidesNose to certain masks, instead of just giving it to all base mask prototypes. 

Due to how chameleon masks work, they default to hiding noses even for masks that would not normally hide the nose shape.

The PR does not incorporate noses for slimes due to issues with transparent markings being layered on top of the base body sprite.

## Media

image
image
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added new noses for humans and dwarves.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
image image

Surgical mask and breath mask with the Schnozz nose, which is the largest one available.

**Comment by lzk228** [comment]
what about slime people?

**Comment by SlamBamActionman** [comment]
As listed in the PR:
> The PR does not incorporate noses for slimes due to issues with transparent markings being layered on top of the base body sprite.

It's not an impossibility for slimes to have noses, but it would require a bunch of extra work and possibly editing the base slime sprite, and I am not sure what consequences that would have for things like gibbing. So I left it out of this PR.

**Comment by K-Dynamic** [comment]
They're kinda cursed and I love it

**Comment by Everturning** [comment]
schnozz is "hey ferb whatcha wanna do today"

**Comment by Hmeister-real** [comment]
Every human i have is having a Schnozz, i love this

**Comment by Emisse** [comment]
love nose customization

**Comment by 2013HORSEMEATSCANDAL** [comment]
if this doesnt get merged im gonna go insano style

**Pull request merged**
