### PR TITLE
Added Mop, Bucket and Fire extinguisher into the Autolathe

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Added Mop, Bucket and Fire Extinguisher into the Autolathe only Impacts the emotions of the janitor when they realize they can get a lot of buckets and mops

**Screenshots**
Content Client_ThpYpYItJ1

**Changelog**
+ Added Fire Extinguisher to Autolathe
+ Added Bucket to Autolathe
+ Added Mop to Autolathe

:cl:
- add: Added fun!
Any one with any amount of knowledge in this would have taken minutes to add all this stuff it took me 10 hours it isn't much it isn't anything really but its a start and getting started on things is one of the hardest things today I learned a lot maybe I did the format wrong and this will be rejected and if it is at least I have the knowledge I learned along the way

### CODE REVIEW

**Comment by metalgearsloth** [comment]
You've done something wrong as this is just a copy of your plastic branch

**Comment by SethLafuente** [comment]
> You've done something wrong as this is just a copy of your plastic branch

When I test it it shows the Mop Bucket and Fire extinguisher it also has the plastic branch in it but im sure it should contain all the other stuff

**Comment by SethLafuente** [comment]
If you mean the PR looks exactly the same is because I pretty much just copied and pasted it

**Review by PaulRitter — CHANGES_REQUESTED** [review]
this pr has the same changes as the plastic pr. please resolve this

**Comment by SethLafuente** [comment]
Will change it in a few hours

**Comment by metalgearsloth** [comment]
Superseded by https://github.com/space-wizards/space-station-14/pull/4039 as this was just your plastic branch again

**Pull request closed without merging**
