### PR TITLE
Add l10n support for the construction menu

### PR DESCRIPTION
**Pull request by koteq**
## About the PR

Add localization support for the construction menu and prototypes involved in it.
See https://github.com/space-wizards/space-station-14/issues/22814

## Why / Balance

Players on non-English servers find it difficult using the construction menu because it's in English.

## Technical details

- Inject ContentLocalizationManager into a handful of prototypes, adding l10n support to their Names and Descriptions
- Slightly refactor *GraphStep type serializes, adding l10n support
- Changed a few LOC functions, passing already translated arguments instead 

Sidenote: I think most of the LOC helper usages break the separation of concern principle and should be removed. It isn't up to a translator to decide whenever to translate an argument or not. The code should pass down already translated arguments into parametrized fluent messages. Furthermore, fluent doesn't support spaces, making it impossible to translate a LOC(robot arm) call.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added localization support to the construction menu

### CODE REVIEW

**Comment by lzk228** [comment]
Related PR
https://github.com/space-wizards/RobustToolbox/pull/4335

**Comment by koteq** [comment]
> https://github.com/space-wizards/RobustToolbox/pull/4335

> commented on Aug 30

> is bad because it uses ISerializationHooks which are obsolete

I have a bad feeling about it.

**Comment by metalgearsloth** [comment]
Use the LocIds or whatever, you shouldn't be using a hook and definitely not using it for IoCManager resolves to store on components.

**Comment by koteq** [comment]
I'll be closing it for now because I don't feel confident enough on making changes _the right way_. Maybe someone else would take it over and build a proper solution. Or perhaps I'll come back to it one day when I become more used to the codebase.

**Pull request closed without merging**
