### PR TITLE
Medkit Fill Change

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes certain medkit fills, while adding a few small new items to them.

## Technical details
There are two new items - rad auto-injector and charcoal pill. The injector contains 15u arithrazine and 5u bicaridine, and the charcoal pill contains 10u charcoal. There are also new chemical syringes added to certain kits.

The anti-poison medipen was renamed to poison auto-injector, for consistency sake.

- Burn Kit - Removed two ointment, removed inaprovaline syringe, added two regenerative meshes, added sigynate syringe, added five kelotane pills
- Toxin Kit - Removed one poison auto-injector, removed one ipecac syringe, removed two dylovene pills, added ethylredoxrazine syringe, added three charcoal pills
- Rad Kit - Removed ointment, removed one emergency medipen, removed three hyronalin pills, added geiger counter, added phalanximine syringe, added rad auto-injector
- Advanced Kit - Removed one bloodpack, added one regenerative mesh
- Combat Kit - Removed tranexamic acid syringe, removed poison auto-injector, added saline syringe, added emergency medipen

As a side note, I'm planning on adding blood filters to toxin kits. You'll be able to treat poison damage using them, which means people won't be permadead to poison-related attacks, such as revenants. It's more of a rubber-band solution, but it'll make toxin kits look fuller and more meaningful. 

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Alekshhh
- tweak: Changed most medkit fills

### CODE REVIEW

**Comment by deltanedas** [comment]
phalan is for cellular not radiation, maybe you meant arithrazine?

**Comment by Alekshhh** [comment]
I know but I felt like it fit, you get me. geiger counter makes no sense either but it fits and it's cute to have

**Comment by JoeHammad1844** [comment]
I like the geiger counter.
also, if I remember correctly ethylredo-whatever only works in cryo?

**Comment by Alekshhh** [comment]
it's anti-histamine, but since that's never an issue it's just a poison cure. thought it'd be cute to have, since toxin kit is very lacking

**Comment by metalgearsloth** [comment]
sur

**Pull request merged**
