### PR TITLE
Move PDA cartridges to HoP.

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Moves the spare PDA cartridges to the PTech vendor.

## Why / Balance

Papers please the hop please.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: PDA cartridge extras are now located in the HoP's Ptech vendor!

### CODE REVIEW

**Comment by 3nderall** [comment]
Log probe should stay in detective's locker since the round doesn't start with it installed on their pda.

**Comment by Cojoke-dot** [comment]
> Log probe should stay in detective's locker since the round doesn't start with it installed on their pda. Don't know about other cartridges since I don't play command

It really should just start in the Det Pda instead...

**Comment by ScarKy0** [comment]
>Log probe should stay in detective's locker since the round doesn't start with it installed on their pda.

The det does start with LogProbe preinstalled

**Comment by Zap527** [comment]
I don't think this is a good change

I've had many issues with captains rushing my locker as CMO to install the cartridge in their PDA roundstart. I think heads should keep control over who gets their departemental gear instead of the HOP being the point of contact. The last thing I want is for all of sec to have the medtek installed because they asked the HoP while I'm none the wiser.

**Comment by SlimmSlamm** [comment]
Not a good change. The heads of a department shouldn't have to visit HoP or beg HoP for their cartridges.

**Comment by superjj18** [comment]
Both the head and hop should have them

**Comment by superjj18** [comment]
> I don't think this is a good change
> 
> 
> 
> I've had many issues with captains rushing my locker as CMO to install the cartridge in their PDA roundstart. I think heads should keep control over who gets their departemental gear instead of the HOP being the point of contact. The last thing I want is for all of sec to have the medtek installed because they asked the HoP while I'm none the wiser. 

By issues you mean they did it and it was kinda cringe?  The scenario you're describing seems like a total non-issue.  While I do agree it shouldn't be freely given to everyone I also recognize that even if everyone did have all the apps it would hardly be any issue at all as they don't really hurt anyone, like I said it's just kinda cringe.

What's with the false scarcity of "nooo this minor thing MUST BE PROTECTED.  I will be physically harmed if some rando had it"

**Comment by Zap527** [comment]
It is not a non-issue. When I sign up for medical, it's generally because I want to play medical. It's painful when people from other jobs get the medtek because it means they're going to avoid medical in the future.

Some CMOs don't care and are fine with people alleviating their workloads. Some CMOs would rather have people come to medical every time. I think it should be up to the CMO to decide whether someone gets departemental tools or not, not the HOP. Giving heads control over their department imo is always better.

**Comment by superjj18** [comment]
> It is not a non-issue. When I sign up for medical, it's generally because I want to play medical. It's painful when people from other jobs get the medtek because it means they're going to avoid medical in the future.
> 
> Some CMOs don't care and are fine with people alleviating their workloads. Some CMOs would rather have people come to medical every time. I think it should be up to the CMO to decide whether someone gets departemental tools or not, not the HOP. Giving heads control over their department imo is always better.

Med is where the chems are.  Topicals from station medkits ain’t doing shit against 3+ crew KIA(which is a pretty common code blue occurence)

HOP is CMO’s boss last time I checked, so it’s up to CMO to communicate their intentions beforehand with hop

**Comment by superjj18** [comment]
> > It is not a non-issue. When I sign up for medical, it's generally because I want to play medical. It's painful when people from other jobs get the medtek because it means they're going to avoid medical in the future.
> > Some CMOs don't care and are fine with people alleviating their workloads. Some CMOs would rather have people come to medical every time. I think it should be up to the CMO to decide whether someone gets departemental tools or not, not the HOP. Giving heads control over their department imo is always better.
> 
> Med is where the chems are. Topicals from station medkits ain’t doing shit against 3+ crew KIA(which is a pretty common code blue occurence)

HOP is CMO’s boss last time I checked, so it’s up to CMO to communicate their intentions beforehand with hop

**Comment by Zap527** [comment]
The CMO's boss is the captain.

Heads should have control over their department and people should not be able to simply bypass a department altogether because the HoP said so. Even if in some cases medical will be needed despite the medteks, most of the time people will just powergame it to self medicate. That's incredibly boring for doctors who signed up to heal people and now need to wait even longer between mass casses.

**Comment by slarticodefast** [comment]
This was discussed in the staff channel and it was decided not to merge this for the following reasons:
- We would rather keep the heads having control over their own deparmental equipment, especially in cases where there might be no HOP.
- It would encourage the HOP and captain to install all cartridges for themselves at round start, even if they do not need them.
- Keeping them decentralized is better since they are theft targets.

**Pull request closed without merging**
