### PR TITLE
Artifact hemoglobin trigger now accepts all sentient blood types

### PR DESCRIPTION
**Pull request by wafehling**
## About the PR
I changed the "Reaction with Hemoglobin" artifact trigger to trigger with all types of sentient blood, and changed the hint to "Reaction with hematological fluid"

## Why / Balance
Being a moth/slime/arachnid scientist sucks when you get this node. It's better-balanced across species now.

## Technical details
Just changed a couple .YMLs, nothing fancy.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None.

**Changelog**
Changed artifact hemoglobin trigger to accept all sentient blood types

### CODE REVIEW

**Comment by Nimfar11** [comment]
Should we remove the slime? Playing as a slime person, it was fun enough to catch a discouraged human and ask for his blood in the name of science.

**Comment by lzk228** [comment]
do slime and other bloods even contain hemoglobin?

**Comment by Veritius** [comment]
just rename the trigger

**Review by Veritius — APPROVED** [review]
yml is fine

**Comment by wafehling** [comment]
> Should we remove the slime? Playing as a slime person, it was fun enough to catch a discouraged human and ask for his blood in the name of science.

You can ask for people's blood anywhere, anytime, for any reason. They don't gotta know you're lying

**Pull request merged**
