### PR TITLE
Mannequin

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Added mannequin to the game on which you can hang you clothing!
- Mannequin have own inventory slots that can wear some clothing.
- Mannequin can be crafted for 5 wood and 2 metal rod
- Mannequin can be destroyed and all stuff will drop from it
- Mannequin don't shows on crew monitor if suit sensors enabled

## Why / Balance
Funny + Cool + Clothing shop/collecting +  Maybe prank someone with it

## Technical details
Almost everything is prototypes, but i added additional condition (if suit sensor user have mobState component) in suit sensor's system, so we'll know if wearer is living or non living creature 

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Added !HasComp<MobStateComponent>(sensor.user) check in server SuitSensorSystem.cs (line 311)

**Changelog**
:cl:

- add: Added craftable mannequin that you can hang clothing on!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
test fail isn't erroneous. You need to add `- type: ContainerContainer` to the prototype and might also need to add the relevant components.

very cool PR tho

**Comment by UbaserB** [comment]
the sprite is oddly cursed

**Comment by MACMAN2003** [comment]
it'll be really funny when someone sets a mannequin down and someone else moves it around each time they leave so it looks like the mannequin is scp 173

**Comment by Poisonlight13** [comment]
Maybe that could be an event where a random mannequin on the map becomes possessed or something 

> it'll be really funny when someone sets a mannequin down and someone else moves it around each time they leave so it looks like the mannequin is scp 173

**Comment by BombasterDS** [comment]
bruh, finally worked!

**Comment by BombasterDS** [comment]
> test fail isn't erroneous. You need to add `- type: ContainerContainer` to the prototype and might also need to add the relevant components.
> 
> very cool PR tho

Thanks for advice!

**Pull request merged**
