### PR TITLE
#391 Done Lathe animations

### PR DESCRIPTION
**Pull request by Decappi**

### CODE REVIEW

**Comment by Zumorica** [comment]
Seems this makes lathes use animations, right? You might want to change the title of the PR to reflect this! I added the DO NOT MERGE label for now, so it's fine.

**Comment by Decappi** [comment]
That's still a WIP. I'm done with the Autolathe. The problem I'm having is the Protolathe - we've got inserting animations which don't include the Protolathe itself. How do I add a new AnimationLayer which would be showing animations on top of the other layers? Right now It's being shown as the singular layer.

**Comment by PJB3005** [comment]
You'll want to define an extra layer on the sprite and then set its visibility to play the animation.

**Comment by Decappi** [comment]
Ok, it's added, and both are working now. Is there a saner way to add the animation layer inside the visualizer which doesn't involve jumping through the hoops?

**Comment by PJB3005** [comment]
I'd love to come up with a better way to do this kinda stuff but this is fine for now.

**Pull request merged**
