### PR TITLE
mined gas is worth 0

### PR DESCRIPTION
**Pull request by Emisse**
infinite money glitch no longer real

### CODE REVIEW

**Comment by Interrobang01** [comment]
but it's not infinite money because the only way to sell gas is via gas tanks and gas tanks cost like 1k each

**Comment by Emisse** [comment]
im watching atmos in real time take a canister, fill it up with 650 thousand mols of oxygen and sell it

**Comment by Interrobang01** [comment]
oh well if they're getting 65k per can out of pure oxygen and it's less labor than frezon or smth then yeah this is good

although i don't think co2 miners are ever mapped so maybe keep co2 sell price

**Comment by Emisse** [comment]
almost every map has a co2 miner

**Comment by Interrobang01** [comment]
i stand corrected

**Comment by lzk228** [comment]
there definitely should be  cl

**Comment by deltanedas** [comment]
cmb cooled oxygen :trollface:

**Pull request merged**
