### PR TITLE
Add description of tool qualities to entity

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

add the name of item's tool quality to description

## Why / Balance

came up with this after a discussion in https://github.com/space-wizards/space-station-14/pull/32285
so now you can see that gas tanks can be used for rolling

## Technical details

check the code, it's not too much and there are comments

## Media

Screenshot_20240924_235746
Screenshot_20240924_235804
Screenshot_20240924_235810

omnitool shows the chosed tool quality
Screenshot_20240924_235820
Screenshot_20240924_235832

rolling stuff
Screenshot_20240924_235848
Screenshot_20240924_235902
Screenshot_20240924_235917

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Item's tool function now shows on examine.

### CODE REVIEW

**Comment by lzk228** [comment]
and i thought that will be in spider or xeno desc, like they can be used for prying, but they use the other component
so no, spiders can't be usable for prying :trollface:

**Comment by deltanedas** [comment]
PryingComponent my beloved

**Comment by Everturning** [comment]
I dislike this bc at the same time it's vague and also too informative. I believe new players should either learn what tools do on their own or get help from someone who does know. alternatively, this should only be enabled for grasshopper and then nowhere else

**Comment by deltanedas** [comment]
only way you are going to figure out some round objects can be used to roll dough is grepping the source code, nobody should have to do that

**Comment by Everturning** [comment]
> only way you are going to figure out some round objects can be used to roll dough is grepping the source code, nobody should have to do that

must all discovery be made obvious? the rolling stuff with an o2 tank should be hidden until someone decides to tell someone who doesn't know that you can do that. the contraband levels PR, while somewhat good for the game, got rid of the lawyer, for example, arguing that cybersun pens and such were not in fact contraband, and the conversations that came from that

**Comment by GoodWheatley** [comment]
> > only way you are going to figure out some round objects can be used to roll dough is grepping the source code, nobody should have to do that
> 
> must all discovery be made obvious? the rolling stuff with an o2 tank should be hidden until someone decides to tell someone who doesn't know that you can do that. the contraband levels PR, while somewhat good for the game, got rid of the lawyer, for example, arguing that cybersun pens and such were not in fact contraband, and the conversations that came from that

in what world does knowledge gating o2 tank rolling tech help the game

**Comment by Everturning** [comment]
In what world does spoon-feeding all the information about an item help the game if not to remove any sort of discovery

**Comment by deltanedas** [comment]
time to remove guidebook because its spoon-feeding

**Comment by august-sun** [comment]
I think that this is kind of a tough spot because one of the big allures of SS13 originally was the fact that some things, you could just discover or encourage people to try out in a "what if" kind of way. At the moment, SS14 doesn't necessarily have the features that allow for that kind of discovery quite yet, or at least I'm having trouble thinking of particular things that people enjoy discovering themselves.

**Comment by lzk228** [comment]
> I think that this is kind of a tough spot because one of the big allures of SS13 originally was the fact that some things, you could just discover or encourage people to try out in a "what if" kind of way. At the moment, SS14 doesn't necessarily have the features that allow for that kind of discovery quite yet, or at least I'm having trouble thinking of particular things that people enjoy discovering themselves.

all i can answer to it that ss14 is more newplayer-friendly than 13

**Comment by august-sun** [comment]
> > I think that this is kind of a tough spot because one of the big allures of SS13 originally was the fact that some things, you could just discover or encourage people to try out in a "what if" kind of way. At the moment, SS14 doesn't necessarily have the features that allow for that kind of discovery quite yet, or at least I'm having trouble thinking of particular things that people enjoy discovering themselves.
> 
> all i can answer to it that ss14 is more newplayer-friendly than 13

Yeah, part of that I think is an existing question of whether or not discoverability becomes a deliberate choice within the game, but letting players know what's possible is, at minimum, a positive to show how versatile things can be in this game.

**Review by TheShuEd — APPROVED** [review]

**Comment by slarticodefast** [comment]
Thank you for your contribution!

**Pull request merged**
