### PR TITLE
Make penguin plushie lore accurate

### PR DESCRIPTION
**Pull request by PJB3005**
Real

### CODE REVIEW

**Comment by lzk228** [comment]
what does that mean?

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by VasilisThePikachu** [comment]
Anyway as funny as it would be to merge this, meme pr

linux does have audio

**Comment by UbaserB** [comment]
> Anyway as funny as it would be to merge this, meme pr
> 
> linux does have audio

 can i ask why close?

**Comment by VasilisThePikachu** [comment]
> > Anyway as funny as it would be to merge this, meme pr
> > linux does have audio
> 
> can i ask why close?

This pr just made the penguin plushie silent

That's it.

**Comment by deltanedas** [comment]
this doesnt have any ingame changes wym

i use arch btw

**Pull request closed without merging**
