### PR TITLE
Stition update and merge

### PR DESCRIPTION
**Pull request by Benito-Mussolini-II**
updated stition.yml
merged upstream

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Pretty tasteless.

**Comment by UbaserB** [comment]
why would someone pr something like this

**Comment by Benito-Mussolini-II** [comment]
MISINPUT AHHHHHH

**Comment by mirrorcult** [comment]
repoban speedrun

**Comment by Simyon264** [comment]
any%

**Pull request closed without merging**
