### PR TITLE
lovable animals

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

Now the animals, when successfully petted, will give you cute hearts.

## Why / Balance

it's cute

## Technical details

Added the ability to spawn entities in case of successful or failed interaction

## Media

Анимация5

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Animals now give cute hearts when you pet them.

### CODE REVIEW

**Comment by lzk228** [comment]
too much hearts

**Comment by TheShuEd** [comment]
you can't have too many hearts.

**Comment by Partmedia** [comment]
Thank you for your contribution. Per the [pull request guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html), please separate unrelated code cleanups and variable renames from the content changes.

**Review by Partmedia — CHANGES_REQUESTED** [review]
It looks like in cleaning up your PR, you accidentally removed the bit that actually spawns the `InteractSuccessSpawn`. This PR no longer works.

**Comment by TheShuEd** [comment]
@Partmedia Done..

**Review by Partmedia — APPROVED** [review]

**Comment by Partmedia** [comment]
Thank you for your contribution.

**Pull request merged**
