### PR TITLE
Gave lab Coats Storage Room

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Gives Coats storage room
**Screenshots**

image

**Changelog**

:cl: Seth
- add: Added Storage Room to Coats

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
You haven't turned quick equip off meaning these will both equip the coat and open the storage window when you press z with them in your hand.

**Comment by SethLafuente** [comment]
> You haven't turned quick equip off meaning these will both equip the coat and open the storage window when you press z with them in your hand.

just test it it out it dosent do that

**Comment by SweptWasTaken** [comment]
Yeah I forgot they got rebound.

**Review by SweptWasTaken — APPROVED** [review]
I'd rather you didn't duplicate this across all of the coats and made a base but I can't be asked to guide you through that so i'm just gonna merge it.

**Pull request merged**
