### PR TITLE
Science overhaul

### PR DESCRIPTION
**Pull request by AW-FulCode**
## About the PR 

An overhaul to the research system that reduces the dependency on research points and instead has technology unlocked via experiment activities.

This PR includes the core changes to the research system and some of the experimental machinery used to drive technology unlocks (with more to be added later on, this PR is already quite big).

### Changes to the research system
Technologies can now be unlocked via disks. Working like the research point disks but instead of giving points a specific technology is unlocked.

Technology can now be hidden from the research console. This is to accomodate the new research disk technologies, which are designed to be pre-requisites for other technologies (research disks are experimental results, pre-requisites to the actual usable technology).

Future technologies are only visible if their pre-requisites (including hidden techs) are unlocked or unlockable. This is so players can better navigate which technologies they can unlock next and what experiments they need to conduct.

Exclusive technologies - some technologies can be made incompatible with others per R&D server. The idea is that R&D servers should eventually become specialised to a specific tech-tree. Though implemented, none of the technologies use this yet - though once each tree has become well developed enough scientists should have to pick a specialisation to focus on (the intent being that only 1 or 2 branches should be completable per round). This can also allow for sabotage technologies designed to poison R&D servers.

The technology tree has been re-arranged to fit in to several branches, most of which require at least one experiment activity to progress. Current branches include cleaning/janitorial, medical/chemisty, and engineering. Botany technologies are still unlocked by points (for now). 

### Experiment Technologies

In order to traverse each research branch, experiment machines are available. Each machine is designed to reward a research disk once a certain goal has been achieved, while also providing actual uses beyond that.

Added technologies include:

- (Cleaning) Analysis Mop Bucket - when a new reagent is added to the mop bucket, a paper report is printed listing the contents of the bucket. This may be useful for identifying unknown spillages. Once 10 (or more) unique reagents (other than water) are added to the bucket, a research disk is produced to progress the cleaning technology branch.

- (Medical/Chemistry) Chemical Analysis Machine - works exactly the same as the analysis mop bucket but accepts input from bottles instead of mops. Also requires power and must be anchored. Will produce a research unlock disk once 5 (or more) unique medicinal reagents are added to it. Can be used to determine unknown chemicals without having to soak them in to a mop first.

- (Medical) Medical Research Bed - acts as a self-updating health analyzer that works for any buckled entity. Tracks the amount of health restored on itself over time (for all buckled entities over time). Will print a research unlock disk at 150 health restored. Will also list unmetabolised substances within the entities bloodstream.

- (Engineering) Research SMES - a specialised research SMES that has a toggleable "research mode". Once research mode is on, power will be directed to an "analysis store". From this store, the SMES's total capacity will be increased over time. Once the capacity has reached twice an ordinary SMES, a research unlock disk will be produced. The capacity can be increased to 10 times a normal SMES. However, the analysis store has an overload threshold which if breached will cause the research SMES to take damage until it explodes. The overload can be ignored if a toggleable shield is activated. The shield requires an upkeep from the analysis store and will turn off if not paid for - it must be turned back on manually if this happens.

### Other minor changes
Monkeys are now injectable - this is so players don't resort immediately to human medical experiments 

Solution containers can now have tag-based input restrictions. When interacted with by any other container, only containers with the specified tags will add reagents to the receiver. Otherwise the interacted with container will give out reagents, similar to a reagent tank. This was required for the analysis mop bucket (mop input only) and chemical analyser machine (bottle input only).

The cleaning technology branch has the high capacity mop at the end of it (for now). The high capacity mop can hold as much liquid as a mop bucket.

### Future Work

The next step will be add experiment technology for botany research. Once that has been done, all existing technologies will requires experiment activities.

After that, further research activities will be added to the engineering branch, in order to break the tree up - starting with robotics.

To better help players understand how to progress, a textbook printer with basic guidelines on how to use the experiment technology will be added.

After that, work can be done on additional research branches (such as security), new unlockable technologies, and more experiment activities for each research branch.

**Screenshots**

Example of research disk unlock. Also note the future technologies pane.
after submission

The Research SMES and its UI (the generator attached is unlockable at the same time as the Research SMES circuit board).
Research SMES powered

Pictured here is a chemical analysis machine (north of the player), an analysis mop bucket (east), and an open report with a list of reagents (in this case produced by the bucket). The player is also holding a high capacity mop.
chemanalyser

The high capacity mop.
highcapmop

A beaten monkey strapped to the medical research bed and injected with omnizine via hypospray.
medresearchbed

**Changelog**

:cl: Coles_Magnum
- add: an experiment-driven R&D department overhaul, includes four new experimental machines and a fancy mop
- tweak: monkeys are now injectable

### CODE REVIEW

**Comment by moonheart08** [comment]
Hey, can we chat in the discord? This **needs** a proper design document.

**Comment by AW-FulCode** [comment]
> Hey, can we chat in the discord? This **needs** a proper design document.

sure thing, I am Colossaeus Mentula#6438

**Comment by AW-FulCode** [comment]
https://hackmd.io/@ColesMagnum/rJzhjglNo

Here is a comprehensive design document. It presents the primary aims of this work, a list of proposed technologies, a proposed tech tree diagram, and a development approach.

**Comment by mirrorcult** [comment]
the only part of this i'm 100% on is unlocking techs with disks instead of point generation. i really, really do not care for the experiment side of things and it ends up being a reification of what made destructive analyzer sci shitty (in that its basically deterministic and doesnt actually present any variety). furthermore a lot of the experiments reward some perverse incentives (like the bed one.. sci would just beat the shit out of themselves and then heal it with the bed). without the rest of the game being properly balanced around oversupply and multiple paths to acquiring things most of the other experiments are shit too (like the chemical analyzer). this would require a fuckton of effort in basically every aspect of the game that i don't feel confident would be done after this PR is merged

**Comment by AW-FulCode** [comment]
> the only part of this i'm 100% on is unlocking techs with disks instead of point generation. i really, really do not care for the experiment side of things and it ends up being a reification of what made destructive analyzer sci shitty (in that its basically deterministic and doesnt actually present any variety). furthermore a lot of the experiments reward some perverse incentives (like the bed one.. sci would just beat the shit out of themselves and then heal it with the bed). without the rest of the game being properly balanced around oversupply and multiple paths to acquiring things most of the other experiments are shit too (like the chemical analyzer). this would require a fuckton of effort in basically every aspect of the game that i don't feel confident would be done after this PR is merged

Alright I'll have a think about how some these things can be resolved, there are some good points you raised here that were also mentioned in some earlier discussions too on the discord. 

With regards to perversity, that is a very good point. One idea I had down the track was to have entity-based goals for the medical research bed, bringing that in early (forcing the scientists to use a monkey for example) may be a way to alleviate that. I'll have a careful review of the other experiments to prevent that sort of behaviour, at least where possible.

A consistant point made (with reference to the destructive analyser) were deterministic and consistent outcomes for each research branch. I can think about how I can remedy this for the technologies here - someone mentioned the use of RNG to vary the goals which I did have in mind for some of the experiments. This should be fairly easy to do for the chem analyser (and mop bucket), I'll have a think of what I can do with other activities.

With regards to the over supply and multiple paths, that will be a difficult task that will require ongoing effort to properly balance. This very well could be a deal-breaker and I understand, the best I can is make the components and underlying systems as easy as possible to adjust for ongoing change as possible. In the mean time some goals (such as for the chem analyser) can be made more difficult (while also being varied) to reflect easy to access to chemicals.

If this does not end up being a fit for the main branch, that's alright. I still very much want to keep on adding to this even as just a fork, and as such I appreciate the feedback.

**Comment by Jackrost** [comment]
Give security practice target and prototype gun. That's make sense to get damage data from target and also give security shooting range to practice their accuracy while they have free time.

**Comment by EmoGarbage404** [comment]
> Give security practice target and prototype gun. That's make sense to get damage data from target and also give security shooting range to practice their accuracy while they have spare time.

Is accuracy even a factor in a 2d game? People are just gonna stand next to the target and beat it with a crowbar for points over and over.

**Comment by Jackrost** [comment]
> Is accuracy even a factor in a 2d game? People are just gonna stand next to the target and beat it with a crowbar for points over and over.

That's why you need prototype gun. Target don't give points from others weapon

**Comment by AW-FulCode** [comment]
> Give security practice target and prototype gun. That's make sense to get damage data from target and also give security shooting range to practice their accuracy while they have spare time.

I have had a few additional tech ideas so I made a little sub-section for feedback like this in my design doc.

Something like this could work. I'd want to add some variation to the goal to keep things different each round, but that can be achieved through some means. One idea that comes to mind is basing the goal on distance from the target - and having various shooting goals at different ranges. If possible, a moving target would also bring some challenge.

It would be a while before I'd implement something like this, but always good to have these kinds of things written down.

**Comment by EmoGarbage404** [comment]
I think my main issue with this, which can't really be easily fixed, is that adding more variation and depth to this system requires just a straight increase of different types of machines. I'm not confident that the actual amount of machines will grow to stop the department from going stale. Additionally, with every machine, you run into balancing it against all other machines, which creates a design nightmare.

**Comment by moonheart08** [comment]
This is just gonna sit here stale, so closing. Come back when the design has been fully consulted over with the other people trying to rework science ( @mirrorcult @EmoGarbage404 )

**Comment by AW-FulCode** [comment]
All good, I'll be sure to let the right people know once I have things put together. Thanks!

**Pull request closed without merging**
