### PR TITLE
Update Medical Guidebook

### PR DESCRIPTION
**Pull request by Aeshus**
## About the PR

This PR updates and rewords all of the Medical Guidebook Entries (excluding the reference ones), including:
* Medical (Expanded greatly, Medical Doctor has been merged into it)
* Chemistry (Expanded greatly)
* Cloning
* Cryogenics
* Paramedics (New)

This also deleted the Medical guide entries that were just glorified reference sheets, as that already exists in the Chemistry reference.

## Why / Balance

The previous guidebook was outdated and listed false information.
* It excluded any information on the HUD to see health bars
* Didn't really explain the suffering to get Cloning
* Didn't explain Cryogenics steps very well
* Medical now includes information on beds

The `Medical Doctor` guidebook entry was merged into the `Medical` guidebook entry. These used to be separate but didn't have any content difference and it was just an extra button to navigate to. 

This is now closer to how other departments like Cargo are organized, with the main entry being for the most common job that everyone in the department needs to know, and the sub-entries go into specific tasks and more specialized jobs.

This tries to address all of the issues in Vasilis' HackMD.

## Technical details

N/A

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

<details><summary>
Medical
</summary>

image 
image 
image 
image 
image 
image 
image 

</details>

<details><summary>
Chemist
</summary>

image
image
image
image
image
image
image
image
image

</details>

<details><summary>
Cloning
</summary>

image
image

</details>

<details><summary>
Cryogenics
</summary>

image
image

</details>

<details><summary>
Paramedic
</summary>

image
image
image

</details>

## Breaking changes

The `Medical Doctor` guidebook entry was merged into the `Medical` guidebook entry. 

**Changelog**

:cl:
- add: Added a guide for Paramedics.
- tweak: Large rework of the Medical and Chemists guidebooks.
- tweak: Cryogenics and Cloning guides are now up-to-date.

### CODE REVIEW

**Comment by deltanedas** [comment]
trolled by: newmed soon :tm:

**Comment by Aeshus** [comment]
> trolled by: newmed soon ™️

If we get Surgery within the next month or two, I'm going to be very angry. I'm not going rewrite this guide again... 

They should put more effort into making Salvage and Cargo better, not Medical.

**Comment by Partmedia** [comment]
Thanks for the PR. Please review the [ChangeLog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog). Could I ask why this is drafted?

**Comment by Aeshus** [comment]
> Thanks for the PR. Please review the [ChangeLog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog). Could I ask why this is drafted?

This was in-progress

**Comment by Aeshus** [comment]
I haven't been working on this in a while and I don't have the energy to keep it up to date or even deal with the merge conflicts.

If anyone else wishes to take up the mantle, feel free.

**Pull request closed without merging**
