### PR TITLE
JaniDrobes can now dispense Mops

### PR DESCRIPTION
**Pull request by NoobyLegion**
## About the PR 

**Screenshots**

**Changelog**

Fixes https://github.com/space-wizards/space-station-14/issues/11291
:cl: NoobyLegion
- add: JaniDrobe can now dispense Mops

### CODE REVIEW

**Comment by theashtronaut** [comment]
Shouldn't Drobes only contain wardrobe items? i.e. clothing
The mops should be added to the custodial closet, or if that doesn't exist then one should be made. In fact any non-clothing items imo should be removed from drobes and put in the job's locker / dedicated equipment vending machine.
Alternatively a "Janivend" machine? I don't think every job needs a dedicated equipment vending machine but :woman_shrugging:

**Comment by EmoGarbage404** [comment]
Custodial closet exists and it has mops in it.

**Comment by mirrorcult** [comment]
#11348
custodial closet should just be made to have 2 mops in it if this is an issue. either way, you can lathe them or buy more from cargo so

**Comment by mirrorcult** [comment]
superseded by #11366

**Pull request closed without merging**
