### PR TITLE
Syndie airlocks

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

This PR adds syndicate airlocks with a red-and-black color scheme, so syndie maps and shuttles don't have to use (ironically) security-colored airlocks anymore. Also includes external syndicate airlocks to prevent people from casually walking into the nukie ship, ~~and add an extra hurdle for powergamers rushing the syndi puddle~~.
Added separate syndicate access level intended primarily for traitors who have an agent card, which is planned to be used in the upcoming Haven Orbital map, and may be used inside syndicate ships such as the syndi puddle.
Airlocks include both agent and operative versions.
Credits: @Doru991 (YAML and sprite work)
@MaloTV (Initial sprite work)

**Media**

airlocks2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Doru991 & MaloTV
- add: The Agent ID card now comes with access to a limited suite of Syndicate facilities, not including those reserved for operatives.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
so nukies wont be able to access their own ship without scanning the commander or medic's ID? I think it should just be a single syndicate access

**Comment by Doru991** [comment]
This doesn't contain actual mapping so the nukie shuttle could just be mapped with the regular syndie variant. Or as an alternative, regular nukie operatives could start with a special agent ID that has that access from the start

**Comment by MaloTV** [comment]
Very cool Sprites i wonder who did them

**Comment by EmoGarbage404** [comment]
the sprites for these are very saturated and don't really match the syndicate color scheme. I would recommend perhaps using a black base with red accent lines (inverting the current colors)

**Comment by Doru991** [comment]
I'm pretty sure Malo used the colors of the syndicate logo to make the sprites, I'll try to see if it'd look better if it used the same red as some other syndie objects

**Comment by deltanedas** [comment]
theres another syndie airlocks pr and personally the sprites in that are way nicer

**Comment by Doru991** [comment]
Can you drop a link to that one?

**Comment by deltanedas** [comment]
https://github.com/space-wizards/space-station-14/pull/16959

**Comment by Doru991** [comment]
Gonna be honest I have no idea what's going on with that PR since it seems like someone accidentally tried to merge a whole Russian fork into upstream, I couldn't even find the syndie airlock texture as one of the changed things in that PR

**Comment by deltanedas** [comment]
nevermind im idiot

**Comment by Doru991** [comment]
pro
that one is closed tho but the red on black color scheme might look better near walls and stuff, I'll try to re-edit it into something similar

**Comment by deltanedas** [comment]
yes its a derelict steal the precious sprites :trollface:

**Comment by Doru991** [comment]
I made a new palette based on the surplus crate one, this one hopefully goes a bit harder

**Comment by MaloTV** [comment]
>:(

**Comment by Doru991** [comment]
Sorry Malo I didn't mean it like that I was genuinely trying not to inconvenience you 😕

**Pull request merged**
