### PR TITLE
Soda water and vodka recipes

### PR DESCRIPTION
**Pull request by saga3152**
## About the PR
You can now craft soda water from 5 water and 1 carbon dioxide and vodka from 1 ethanol and 1 water, that's not 40% but more simple
Also tweaked crystals reaction by changing ethanol to plasma
## Why / Balance

I thought that these recipes were missing so I added them
## Requirements

- [X]  I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: You can now make vodka and soda water.

### CODE REVIEW

**Comment by slarticodefast** [comment]
Wouldn't the water+ethanol reaction conflict with the CreateCrystals reaction in [fun.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Recipes/Reactions/fun.yml)?

**Comment by saga3152** [comment]
> Wouldn't the water+ethanol reaction conflict with the CreateCrystals reaction in [fun.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Recipes/Reactions/fun.yml)?

Fixed, now you use plasma instead of ethanol to CreateCrystals I guess it still makes sense

**Comment by JIPDawg** [comment]
I don't think I agree with using plasma to create crystals. If it's going to be used then it at least needs the catalyst: True tag so it is not used up.

**Comment by pheenty** [comment]
> Wouldn't the water+ethanol reaction conflict with the CreateCrystals reaction in [fun.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Recipes/Reactions/fun.yml)?

same with chloral hydrate

**Comment by saga3152** [comment]
> same with chloral hydrate

Feels like this is too much of an issue

**Pull request closed without merging**
