### PR TITLE
I changed the recipe for Desoxy Ephedrine to be more realistic.

### PR DESCRIPTION
**Pull request by noverd**
In the real world, Desoxy Ephedrine does not require very high temperatures to cook.

## About the PR 
I changed the recipe for Desoxy Ephedrine to be more realistic.
In the real world, Desoxy Ephedrine does not require very high temperatures to cook.
I lowered the temperature needed to cook the Desoxyephedrine.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Changed Desoxyephedrine recipe

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
This is to prevent chemdiots from creating meth, and intentional.

**Comment by mirrorcult** [comment]
this will need more justification beyond "it isn't exactly like in real life"

**Comment by noverd** [comment]
how do they get that hot? If you want to do it, you can still

**Comment by mirrorcult** [comment]
yes, so this changes literally nothing for no reason

**Comment by noverd** [comment]
it will be easier for beginners to cook it

**Comment by noverd** [comment]
some of them just heat it up in the microwave once and then quit because it didn't work out

**Comment by Elijahrane** [comment]
> it will be easier for beginners to cook it

this isn't a good thing for meth, lol

**Comment by EmoGarbage404** [comment]
tbh, the proper response is probably just to make bunsen burners or hot plates for chemists to use. That would be better than microwaves, which are admittedly a strange object for a chemist to use.

**Comment by noverd** [comment]
Yeah

**Comment by moonheart08** [comment]
It's non-trivial for a reason. Realism is not the goal.

**Pull request closed without merging**
