### PR TITLE
saltern update

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-vault & technical storage standardization
-skub

### CODE REVIEW

**Comment by deltanedas** [comment]
evil crlf

**Comment by Emisse** [comment]
i saw it and didnt even care bro

**Comment by deltanedas** [comment]
configure youre git!!!!!!!!!!!

**Comment by Emisse** [comment]
configure your git bitch ass check the other diffs notice the odd 1 out. odd one out = saltern = saltenr problem

**Pull request merged**
