### PR TITLE
Dr. Gibb Vendor

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

adds the dr gibb vending machine from TauCetiClassic (plus consistency in emaggable vendors)

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added the Dr. Gibb Vendor

### CODE REVIEW

**Comment by Equivocateur** [comment]
The new winterdrobe looks like it belongs in med with those large stripes and unfun "deny" sprite

**Comment by Eden077** [comment]
Yeah I don't... Really like the new winterdrobe, it doesn't look very winter like anymore

**Comment by Emisse** [comment]
i think our current winterdrobe looks better

**Comment by potato1234x** [comment]
done

**Pull request merged**
