### PR TITLE
Clown Visual Tweaks

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Tweaks the clown sprite here and there
Edited cluwne and banana clown suits to fit the tweaked one
Repaletted cluwne bag to fit the tweaked one

## Media

image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- tweak: Changed clown clothing sprites.

### CODE REVIEW

**Comment by UbaserB** [comment]
can i see a direct comparison between the old and new

**Comment by Alekshhh** [comment]
image
ye

**Comment by UbaserB** [comment]
i dont like how the head is rounded from the back

**Comment by Alekshhh** [comment]
could make it a wee less yeah

**Comment by deltanedas** [comment]
giggles von honkerton went from angry to happy :trollface:

**Comment by Alekshhh** [comment]
redemption arc

**Comment by MACMAN2003** [comment]
i feel like the clown's sprites shouldn't be touched like how when mojang redid minecraft's textures they didn't touch diamond ore's

**Comment by Alekshhh** [comment]
the only major change was the pants that were previously just a blob, otherwise the rest is just a tweak here or there

**Comment by muburu** [comment]
i think these are good (especially the cluwne) but the strap on the clown mask doesn't feel right

**Comment by deltanedas** [comment]
its actually a mask now

**Comment by UbaserB** [comment]
did you seriously forget to edit the banana suit shoes and mask? lol.

**Comment by Alekshhh** [comment]
they seemed unique enough to not touch

**Comment by Alekshhh** [comment]
I'll be back

**Pull request closed without merging**
