### PR TITLE
Vending UI facelift

### PR DESCRIPTION
**Pull request by jamessimo**
## About the PR

Touched up the vending machine UI by making it use Fancy window, giving it a footer and giving the itemlist some better padding + spacing using new inengine feature.

## Why

Its a commonly used UI that still used the old default window and wasn't utilizing new itemlist features like spacing.

## Technical details

Just swaps default window to fancy window, adds some flavor text to the footer and itemlist now uses itemseperation 

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: vending machine UI improved

### CODE REVIEW

**Comment by Hmeister-real** [comment]
Can we get a before and after?

**Comment by jamessimo** [comment]
> Can we get a before and after?

before
vendOld

after
newvend

**Comment by Hmeister-real** [comment]
Yeah looks cool

**Comment by juliangiebel** [comment]
It needs margin on the sides

**Review by ficcialfaint — APPROVED** [review]
This is neat, LGTM

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
