### PR TITLE
D-Sword Tweak

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes the d-sword, specifically:
- Increased wideswing charge (0.9 -> 1.25)
- (new) Increased slash damage (9 -> 15)
- (new) Increased heat damage (9 -> 12)
- Reduced structural damage (20 -> 15)
- Reduced attack speed (1.5 -> 1.4)
- Reduced reflect change (75% -> 50%)

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed d-sword to be less of a death hurricane, and more of a precise killer

### CODE REVIEW

**Comment by Xeno4** [comment]
No. Just no. Its already too low damage, and you want to nerf it more?

**Comment by Myakot** [comment]
I love how you make it absolutely worse than a single esword, and leave it's cost as-is.
Just stun baton the e-sworders, or banana pie them, or spear lycoxide, or anything at all, but shooting at them.

**Comment by Emisse** [comment]
this weapon has always been impossible to balance, even in ss13. if we really want it balanced wed remove it lmao

**Comment by asperger-sind** [comment]
> this weapon has always been impossible to balance, even in ss13. if we really want it balanced wed remove it lmao

I think it's better here because it's not just a flat upgrade and rather an epen on steroids.

**Comment by Alekshhh** [comment]
after testing I think this works fine
- it can kill security in hardsuits in six normal swings, and in four heavy swings
- regular hardsuits go down in 5 normal swings, and 4 heavy
- captain goes down in 8 normal swings, and 6 heavy
- anyone else unfortunate enough to not be decently armored (most of the crew) will die rather quick, four regular swings and three heavy swings

**Comment by Just-a-Unity-Dev** [comment]
> this weapon has always been impossible to balance, even in ss13. if we really want it balanced wed remove it lmao

cant do that without an outroar of players

**Comment by Equivocateur** [comment]
Meanwhile two baton hits and youre fucked

**Comment by asperger-sind** [comment]
> Meanwhile two baton hits and youre fucked

space station games try to balance desword or stunbaton (impossible)

**Comment by FacePluslll** [comment]
I think the Desword is fine as is. Stun batons and disablers will still fuck you over, stims usage with the desword is harder to use now since the nerf and it cost 16tc for lower DPS compared to the 8tc esword. The only reason its 16tc is its wider swings, higher swing rates and higher reflection rate. The only thing that could possibly justify a nerf is its reflection rate to like 60%-70% without going into a complete rebalance.

**Comment by keronshb** [comment]
Please explain why you think these are good changes.

Look at the values in the comments of the original PR to see various tests vs humans and structures.

https://github.com/space-wizards/space-station-14/pull/17227

**Comment by Alekshhh** [comment]
tests have been performed with the current energy blade and double energy blade (not mine)
for the energy blade
- it takes 4 regular hits to crit a civvie, 2 charged hits to crit
- it takes 6 regular hits to crit a hardsuit seccie, 3 charged hits to crit
- it takes 7 regular hits to crit a hardsuit cappy, 4 charged hits to crit
for the dblade
- it takes 6 regular hits to crit a civvie, 4 charged hits to crit
- it takes 9 regular hits to crit a hardsuit seccie, 6 charged hits to crit
- it takes 12 regular hits to crit a hardsuit cappy, 8 charged hits to crit
for my dblade
- it takes 4 regular hits to crit a civvie, 3 charged hits to crit
- it takes 6 regular hits to crit a hardsuit seccie, 5 charged hits to crit
- it takes 8 regular hits to crit a hardsuit cappy, 6 charged hits to crit

with this in mind, you can see that my current dsword matches with the current energy sword when it comes to damage, reflection of attacks aside, while the current dsword struggles to match up with both even when widestriking. while it is true that the dsword can dish out more attacks much faster, and it has the advantage of reflecting projectiles, you have to consider that unlike the energy sword, it takes both your hands to use, meaning you are only relying on the dsword when it comes for combat, unlike the energy sword that has a free hand and can carry anything to help it, like any gun or a shield. this makes it struggle to compete with a regular esword, since your only option is melee, and given how batons are a funny little thing people pull out any time the word nukie is mentioned, you're rather outclassed unless you swap out to a gun quickly, assuming you had enough TC to buy one - if you're a traitor, you're out of luck, as a lone op you're one TC short of a C-20r, and as a nukie, assuming you didn't buy anything other than the dsword and noslips, you'd have to ask for spare TC if anyone has it - or if you're fairly robust and can kite a few baton swings and get lucky on disabler deflection.
I believe my changes to the dsword help make it stand out as a a strong weapon by itself - it has the capabilities of structure destruction of a fireaxe despite the small nerf, the melee prowess of a perced up esword and the defense of a shield in the form of reflection. your only enemy is a baton, as it always is for anything, but that's beyond me, unless MELEE reflection is added. it makes the TC cost worth it, although some may argue they'd want it lower.

**Comment by Myakot** [comment]
> tests have been performed with the current energy blade and double energy blade (not mine) for the energy blade
> 
> * it takes 4 regular hits to crit a civvie, 2 charged hits to crit
> * it takes 6 regular hits to crit a hardsuit seccie, 3 charged hits to crit
> * it takes 7 regular hits to crit a hardsuit cappy, 4 charged hits to crit
>   for the dblade
> * it takes 6 regular hits to crit a civvie, 4 charged hits to crit
> * it takes 9 regular hits to crit a hardsuit seccie, 6 charged hits to crit
> * it takes 12 regular hits to crit a hardsuit cappy, 8 charged hits to crit
>   for my dblade
> * it takes 4 regular hits to crit a civvie, 3 charged hits to crit
> * it takes 6 regular hits to crit a hardsuit seccie, 5 charged hits to crit
> * it takes 8 regular hits to crit a hardsuit cappy, 6 charged hits to crit
> 
> with this in mind, you can see that my current dsword matches with the current energy sword when it comes to damage, reflection of attacks aside, while the current dsword struggles to match up with both even when widestriking. while it is true that the dsword can dish out more attacks much faster, and it has the advantage of reflecting projectiles, you have to consider that unlike the energy sword, it takes both your hands to use, meaning you are only relying on the dsword when it comes for combat, unlike the energy sword that has a free hand and can carry anything to help it, like any gun or a shield. this makes it struggle to compete with a regular esword, since your only option is melee, and given how batons are a funny little thing people pull out any time the word nukie is mentioned, you're rather outclassed unless you swap out to a gun quickly, assuming you had enough TC to buy one - if you're a traitor, you're out of luck, as a lone op you're one TC short of a C-20r, and as a nukie, assuming you didn't buy anything other than the dsword and noslips, you'd have to ask for spare TC if anyone has it - or if you're fairly robust and can kite a few baton swings and get lucky on disabler deflection. I believe my changes to the dsword help make it stand out as a a strong weapon by itself - it has the capabilities of structure destruction of a fireaxe despite the small nerf, the melee prowess of a perced up esword and the defense of a shield in the form of reflection. your only enemy is a baton, as it always is for anything, but that's beyond me, unless MELEE reflection is added. it makes the TC cost worth it, although some may argue they'd want it lower.

Why are you calculating "hits", when you should be calculating "dps". This is not showing anything useful.
- 2 power hits with a regular esword take like 6 seconds (critted civvie)
- 4 power hits with a current DEsword take less than 4 seconds (critted civvie)

The quoted comparison says that both swords "match when it comes to damage", while it's a 33% difference in an actual game.

**Comment by Alekshhh** [comment]
you can calculate dps if you want but thinking about how many hits it takes for someone to turn horizontal is more reliable

**Comment by Myakot** [comment]
Well, it's a weapon. It's used for combat, it's dps is it's main characteristic. All else is complimentary.

If you want to get rid of structural damage so much then just give it "prying" with same speed as Syndi Jaws or even higher.

**Comment by FacePluslll** [comment]
> you can calculate dps if you want but thinking about how many hits it takes for someone to turn horizontal is more reliable

DPS _**does matter**_ in this case (this assumes there's no resistances applied to a person).

Current Desword DPS (has a Attack Per Second of 1.6 and a crit mod of 1.5):
- Normal Damage (normal left click swing) 18 damage:  28.8 DPS 
- Crit Damage (wide swing that lands a crit) 27 damage: 43.2 DPS

NEW Desword DPS (has a Attack Per Second of 1.4 and a crit mod of 1.35):
- Normal Damage (normal left click swing) 27 damage:  37.8 DPS 
- Crit Damage (wide swing that lands a crit) 36.45 damage: 51.03 DPS

Current Esword DPS (has a Attack Per Second of 1 and a crit mod of 2):
- Normal Damage (normal left click swing) 30 damage:  30 DPS 
- Crit Damage (wide swing that lands a crit) 60 damage: 60 DPS

The current Desword stats takes about 3 seconds to kill person while it takes about 2 seconds with the new stats. With the current damage values its basically the same amount of time to kill as an esword.

**Comment by Alekshhh** [comment]
I do believe that's fine, if not even good.
and I'm not sure what the fascination is with structure damage, it tears down structures just as fine, just not on par or better than the fire axe

**Comment by keronshb** [comment]
> Well, it's a weapon. It's used for combat, it's dps is it's main characteristic. All else is complimentary.
> 
> If you want to get rid of structural damage so much then just give it "prying" with same speed as Syndi Jaws or even higher.

I think there's a point to both.

DPS is important but also the melee meta is jousting too for SS14 if I'm not mistaken.

Jousting in SS13 is two people rushing at each other and trying to get a click in. So while DPS can be important, overall damage per click is more important because of this.

**Comment by Myakot** [comment]
> > Well, it's a weapon. It's used for combat, it's dps is it's main characteristic. All else is complimentary.
> > If you want to get rid of structural damage so much then just give it "prying" with same speed as Syndi Jaws or even higher.
> 
> I think there's a point to both.
> 
> DPS is important but also the melee meta is jousting too for SS14 if I'm not mistaken.
> 
> Jousting in SS13 is two people rushing at each other and trying to get a click in. So while DPS can be important, overall damage per click is more important because of this.

Jousting is a thing only because of similar attack speeds. There's **no reason** whatsoever to joust with a weapon with a higher attack speed. You have to stick to your target and just wail at them.

**Comment by keronshb** [comment]
> > > Well, it's a weapon. It's used for combat, it's dps is it's main characteristic. All else is complimentary.
> > > If you want to get rid of structural damage so much then just give it "prying" with same speed as Syndi Jaws or even higher.
> > 
> > 
> > I think there's a point to both.
> > DPS is important but also the melee meta is jousting too for SS14 if I'm not mistaken.
> > Jousting in SS13 is two people rushing at each other and trying to get a click in. So while DPS can be important, overall damage per click is more important because of this.
> 
> Jousting is a thing only because of similar attack speeds. There's **no reason** whatsoever to joust with a weapon with a higher attack speed. You have to stick to your target and just wail at them.

As an alpha strike that works. It's why revolvers or cornering someone can be considered highly effective. 
There are multiple ways to get someone off of you isn't there? Slipping and bola come to mind. Flashes and Flashbangs too for sec.

vs Security or a head there's always the baton issue, which is where jousting is more prevalent unless you have some sort of anti-cc.

**Comment by Alekshhh** [comment]
we can close this pr for now until the rebalance pr comes out

**Comment by asperger-sind** [comment]
> I think there's a point to both.
> 
> DPS is important but also the melee meta is jousting too for SS14 if I'm not mistaken.
> 
> Jousting in SS13 is two people rushing at each other and trying to get a click in. So while DPS can be important, overall damage per click is more important because of this.

DPS is good, but pales in comparison to the current meta, which is running in and out with heavy attack crits and (preferably) a high damage per swing weapon, the basic e-sword with 30 damage for comparison, an experienced player will time the opponent's attacks, start charging their heavy attack by the time the opponent's heavy attack crit duration will wear off, go in, get an attack off and repeat, they will not come in close to you with your fast attack speed weapon because they'll trade more damage than they should, so they do the described chain and either not take damage at all or avoid taking the crit hit.

All this meaning that high damage weapons are already better in comparison to fast weapons except on the condition where you need to rapidly kill someone stunned, then light attacks with alternation between CC (flash for example) and some knife are slightly better because you have less of a hand switch cooldown and get to utilize your DPS.

If melee rework gets merged (the idea of which I do not like as it overnerfs heavy attacks and leaves us with annoying click combat as the superior choice) then the meta will be running circles around someone trying to juke as many attacks while clicking on them in the process, in which case DPS will be better.

**Comment by keronshb** [comment]
> DPS is good, but pales in comparison to the current meta, which is running in and out with heavy attack crits and (preferably) a high damage per swing weapon, the basic e-sword with 30 damage for comparison, an experienced player will time the opponent's attacks, start charging their heavy attack by the time the opponent's heavy attack crit duration will wear off, go in, get an attack off and repeat, they will not come in close to you with your fast attack speed weapon because they'll trade more damage than they should, so they do the described chain and either not take damage at all or avoid taking the crit hit.

This is exactly what jousting is.

**Comment by keronshb** [comment]
> I can close this pr for now until the rebalance pr comes out

I'll leave it up to you but I was just going to leave DNM on until the melee PR went through.

**Comment by Alekshhh** [comment]
I'll leave it up then

**Comment by keronshb** [comment]
@Alekshhh the melee PR was merged. Try testing with live values and your PR values.

**Comment by Alekshhh** [comment]
it's a bit interesting. for the results:

esword
- 3 regular 4 wideswing civvie
- 4 regular 5 wideswing seccie hardsuit
- 5 regular 6 wideswing captain hardsuit

dsword
- 5 regular 6 wideswing civvie
- 7 regular 9 wideswing seccie regular armor
- 8 regular 10 wideswing captain hardsuit

funnily enough I tested it on regular armor (carapace/kevlar) too and it took a hit extra to down with a dsword, likely due to the combined blunt and burn doing less damage than the pure burn esword, since the armor has good blunt resistance

but by itself the dsword with the new weapon update is pretty much the same as my dsword change before it. I didn't test my dsword since I made a new branch but you could assume it'd kill a lot faster

**Pull request closed without merging**
