### PR TITLE
Yet another gun revamp

### PR DESCRIPTION
**Pull request by TaralGit**
Concerning the https://github.com/space-wizards/space-station-14/issues/7984 issue and the https://github.com/space-wizards/space-station-14/pull/8301 pull request.

WIP. 

traitor
Traitor/nuke ops guns: From upper right to left: Cobra silenced handgun (replacement for Mandella), Python (replaces Predator), Viper (replaces Clarissa), C20r, m-90gl (replaces Z8 carbine), Bulldog shotgun (replaces Bojevic)

sec
Security and others: Pump action, double barrel and sawd off shotguns, Vector (replaces Drozd), new detective revolver sprite, new laser gun sprite and the combat shotgun

ert and ds
ERT and Death squad get their pulse weapons and the mateba revolver

Credits: 
pireamaineach for the Cobra (tgstation PR but it was closed)
vgstation for the Vector, Python and Inspector revolvers
world server for the m-90gl
terragov colonial marines for the double barrel, sawd off and pump action shotgun
ds13 for the laser gun
Shiptest for the mateba revolver
the rest are from tgstation

### CODE REVIEW

**Comment by Snowyypanda** [comment]
awesome work, i'd love to see more of gun updates

**Comment by metalgearsloth** [comment]
Merge after https://github.com/space-wizards/space-station-14/pull/8301 and https://github.com/space-wizards/space-station-14/pull/8372 or shankings will occur

**Comment by TaralGit** [comment]
ok this is ready. whatever guns that need reworks will be done in a next PR since I no longer have time.

**Comment by TaralGit** [comment]
oh crap. conflicts

**Comment by TaralGit** [comment]
after careful consideration, I decided to close this PR for good because of conflicts and wait until every gun refactor pull is merged before I'll open a new one.

**Pull request closed without merging**
