### PR TITLE
Nerf Giant Spiders

### LINKED ISSUE #19359: Spiders are comically strong
## Description

a single spider can crit in 4 hits + can proc max bleeding. This is a relatively common station event, why are they so strong??

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR
Giant spiders have received some direct and indirect buffs recently making them extraordinarily strong. This dials them back quite a bit while still being fairly powerful.
Resolves #19359 

## Why / Balance
This makes it a bit more reasonable for a person to be able to 1v1 a giant spider without great gear. I also buffed their poison but reduced their pierce meaning you'll bleed less but won't be able to heal it quite as easily on your own. This will take about 7 hits to crit someone with no armor or poison resistance. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Reduced both the damage and health of giant spiders.

### CODE REVIEW

**Comment by Errant-4** [comment]
Keep in mind that the +25% click attack bonus is probably going away in the not-too-distant future, though I guess we can just buff their damage then to 8/8 or something

**Comment by keronshb** [comment]
Wait for #19138 to be reviewed and accepted/denied before this can be potentially merged.

**Comment by NancokPS2** [comment]
I had a few recent encounters with them.  
It got like 3 hits in before i even started firing, i still killed it while missing at least 40% of shots from ONE mag and only died due to crit, because i started talking in comms instead of healing.  
They barely stand a chance in 1v1 even with mob AI.  
  
I got another encounter in another shift as an atmos, me with a crowbar and a passenger with what looked like a wrench, the spider died in second and no one was even crit.  
  
Any rando that encounters one unprepared SHOULD be dying from them, if a bald seccie with the base .45 ammo and an atmos with a crowbar can easily stomp one. I'd say they need a buff if anything, not a nerf.

**Comment by liltenhead** [comment]
They have the hp of a human, webs that slow you down. They do damages that cause bleeding and can't be protected by armor. Also security already could kill them with their guns, but they are like an 1/8th of the station at best. Sure, the insanely gifted combat players can reasonably 1v1 but for a common enemy they shouldn't be boss fights.

**Comment by NancokPS2** [comment]
I am far from a gifted player, but i find them barely worth worrying over.  
  
A boss fight is something like a queen, which can easily topple like 6 somewhat armed passengers.  
A spider is barely more dangerous than another human with a makeshift weapon.  
  
I would say to run some numbers and leave their survivability comparable to a human with a Type 2 vest and their kill time on par with a crude spear or a combat knife.  
This sounds pretty fair and an easy 2v1 target. But deadly to the average crew

**Comment by Equivocateur** [comment]
> I am far from a gifted player, but i find them barely worth worrying over.
> 
> A boss fight is something like a queen, which can easily topple like 6 somewhat armed passengers. A spider is barely more dangerous than another human with a makeshift weapon.
> 
> I would say to run some numbers and leave their survivability comparable to a human with a Type 2 vest and their kill time on par with a crude spear or a combat knife. This sounds pretty fair and an easy 2v1 target. But deadly to the average crew.
> 
> OR just make them slower so you can escape them and get someone to help. Altho getting jumped in maints should still be a death sentence imo

image

**Comment by Partmedia** [comment]
If you are able to start a discussion or link to discussions that have already taken place on the spider balance, please link them here so that we have a better idea of how to proceed.

**Comment by liltenhead** [comment]
Other than the issue I linked I don't know other discussions. I changed numbers based off testing, and observations I've had lately.

**Comment by JustCone14** [comment]
Anecdotally I know this is a discussion that happens somewhat frequently on lowpop salamander rounds as 7-8 tarantulas can easily wipe the majority of the station population.

**Comment by Eden077** [comment]
As someone who plays Salamander only, since most people aren't running around with weapons spiders can easily kill a majority of crew members or maybe even all of them due to at least 7 to 8 spiders spawning at one time

**Comment by NancokPS2** [comment]
That sounds like a disproportional spider spawn.  
It should be fixed by lowering spiders per pop rather than nerfing spiders.  
Or as a last resort, spawn nerfed spiders on low pop.  
  
It's not really a good idea to balance something around extreme cases.

**Comment by LordEclipse** [comment]
> That sounds like a disproportional spider spawn. It should be fixed by lowering spiders per pop (or increasing the minimum amount for any spawns) rather than nerfing spiders. Or as a last resort, spawn nerfed spiders on low pop.
> 
> It's not really a good idea to balance something around extreme cases.

image-1
This was caused by 1 spider on salamander. Which was player controlled.

**Comment by NancokPS2** [comment]
That sounds like an issue, but an image without context does not say much.  
Did the crew try to fight them unequipped? How many spiders vs how many crew members where there?  
How capable at combat where the crew?  
  
There are a lot of factors to consider

**Comment by LordEclipse** [comment]
> That sounds like an issue, but an image without context does not say much. Did the crew try to fight them unequipped? How many spiders vs how many crew members where there? How capable at combat where the crew?
> 
> There are a lot of factors to consider

Every single crew in the picture tried to fight the spider, all except for the RD, there appears to be 12 dead crew members in that picture, and most of it was done by 1 spider. And this is salamander, people don't carry weapons readily on them at all times, not to mention needlessly preparing "just in case" something happens is against the rules anyway.

**Comment by liltenhead** [comment]
> That sounds like a disproportional spider spawn. It should be fixed by lowering spiders per pop (or increasing the minimum amount for any spawns) rather than nerfing spiders. Or as a last resort, spawn nerfed spiders on low pop.
> 
> It's not really a good idea to balance something around extreme cases.

The dragon boss on salvage currently does less damage than spiders, and only has 100 more health but is like twice the size. Yet the salvagers know what they are up against and still die to it on a fairly frequent basis.

**Comment by NancokPS2** [comment]
Ok, then something must have happened on my encounters. This definitively does not sound like the spiders i saw.  
They must have been damaged previously or something. Disregard my comments.

**Comment by deltanedas** [comment]
on salamander youd usually expect the crew to not be running around with spears and bats 24/7 so you cant exactly blame them for getting fucked up by an overly strong mob

**Comment by deltanedas** [comment]
pro

**Pull request merged**
