### PR TITLE
Add membral wings to moth markings.

### PR DESCRIPTION
**Pull request by pigeonpeas**
## About the PR
Adds membral wings for moths to use.

## Why / Balance
More marking variety. (+ cute bees)

## Media

image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: New moth tail marking, membral wings.

### CODE REVIEW

**Comment by UbaserB** [comment]
fix cl

**Comment by pigeonpeas** [comment]
> fix cl

i'm so bad at changelogs..,,

**Comment by Dutch-VanDerLinde** [comment]
> fix cl

cl isn't broken

**Comment by Dutch-VanDerLinde** [comment]
the changelog text doesn't matter it's just whatever's below the 🆑

**Comment by UbaserB** [comment]
> cl isn't broken

IMG_4414

**Comment by pigeonpeas** [comment]
> > cl isn't broken
> 
> IMG_4414

is fix 👍

**Comment by EdenTheLiznerd** [comment]
Looks amazing, moth customization goes even better

**Comment by lunarcomets** [comment]
as someone who is NOT an undercover agent representing the bees of space station, i approve

**Comment by K-Dynamic** [comment]
We have come for your nectar

**Comment by EmoGarbage404** [comment]
i mean i know there are ideas of transitioning moths to a generic insectoid race but adding fly wings before that seems to be really strange. They are explicitly moths and I don't think harming the visual identity by letting them cosplay as flies and bees is particularly valuable.

**Comment by pigeonpeas** [comment]
> i mean i know there are ideas of transitioning moths to a generic insectoid race but adding fly wings before that seems to be really strange. They are explicitly moths and I don't think harming the visual identity by letting them cosplay as flies and bees is particularly valuable.

I understand that having non moth wings may harm the visual identity a little, but I believe it is worth it in allowing players to better represent their characters. Additionally, I do not believe the visual identity is affected that much. There are already other markings in the game that I believe make the moths look less like moths than this, a good example being the white fly wings.

image

The white fly wings arguably affect the visual identity more, as the reduced fluff around the neck can look quite odd, and not very moth-like in certain circumstances.

image

image

(default wings for reference)
image

**Comment by UbaserB** [comment]
whitefly looks like like the moths i see irl, instead of being comically overfluffy. I think it’s _more_ realistic personally.

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by EmoGarbage404** [comment]
this got closed due to the freeze but i'm going to make a proper decision in the meanwhile.

I don't think that markings should serve to undermine the actual visual identity of the species they apply to. Major deviations in design or style harm the visual identity of a species and should be kept to an absolute minimum. While I do agree that some wings perhaps could serve to be more fitting to the moth appearance, I don't think introducing even more severe deviations is to the benefit of the visuals.

More concrete guidelines on species identity will be coming in the near future so look out for those.

Regardless, I'm saying that this PR will remain closed, even after the freeze is over.

Thank you.

**Comment by pigeonpeas** [comment]
> this got closed due to the freeze but i'm going to make a proper decision in the meanwhile.
> 
> I don't think that markings should serve to undermine the actual visual identity of the species they apply to. Major deviations in design or style harm the visual identity of a species and should be kept to an absolute minimum. While I do agree that some wings perhaps could serve to be more fitting to the moth appearance, I don't think introducing even more severe deviations is to the benefit of the visuals.
> 
> More concrete guidelines on species identity will be coming in the near future so look out for those.
> 
> Regardless, I'm saying that this PR will remain closed, even after the freeze is over.
> 
> Thank you.

understandable! take care, hope there are many a bug fixes during the freeze.

**Pull request closed without merging**
