### PR TITLE
Allow wieldable guns to cycle in hand

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

Applies https://github.com/space-wizards/space-station-14/pull/27307 to https://github.com/space-wizards/space-station-14/pull/26970

## Why / Balance

At the moment, interacting in-hand while a gun wields it proceeds to unwield the gun rather than cycle it. Gun interactions can become click interactive and unintuitive, especially with pump action shotguns.

## Technical details

Applies the new variable to the wieldable gun parent rather than to multiple guns, attempts to address the concern of applying variables en masse.

**Changelog**

:cl:
- tweak: Guns will now cycle when interacting with them in-hand after wielding.

### CODE REVIEW

**Comment by RiceMar1244** [comment]
Hey WarMechanic, thanks a bunch for your original PR. Im currently cleaning up gun yaml right now and im actually moving the stuff from base_wieldable.yml into a base_gun.yml with a bunch of other inheritable qualites. You want me to add this change in there?

**Comment by RiceMar1244** [comment]
Not saying you should close this. This will definitely take less review before merging and its sounds like a good change. If it gets merged before my thing Ill make the changes that I need to.

**Comment by WarMechanic** [comment]
> Hey WarMechanic, thanks a bunch for your original PR. Im currently cleaning up gun yaml right now and im actually moving the stuff from base_wieldable.yml into a base_gun.yml with a bunch of other inheritable qualites. You want me to add this change in there?

This sounds great, I'm pretty sure metalgearsloth had some concerns about value inheritance so that would probably clean up everything nicely.

**Comment by Errant-4** [comment]
Do I understand correctly that this makes the only way to unwield the gun right click? This would be a significant QOL downgrade for reloading, since now to get a free hand to grab your new magazine, instead of just pressing Z and C you have to toggle off harm mode, bring the mouse down to the gun and right-click then find Unwield. This is significantly slower and more distracting, requiring the player to divert both their mouse and their gaze from the action. In the middle of a firefight.

I don't think this feature should go through like this without addressing the issue it causes. I have seen it mention that switching hands while Wielding could unwield, that may be a good solution?

**Comment by Errant-4** [comment]
I have been informed you can switch to the second hand and press Drop to unwield. Also I coded the QOL thing I mentioned

**Comment by WarMechanic** [comment]
> Do I understand correctly that this makes the only way to unwield the gun right click? This would be a significant QOL downgrade for reloading, since now to get a free hand to grab your new magazine, instead of just pressing Z and X you have to toggle off harm mode, bring the mouse down to the hand windows to right-click the gun and find Unwield. This is significantly slower and more distracting, requiring the player to divert both their mouse and their gaze away from the action. In the middle of a firefight.
> 
> I don't think this feature should go through like this without addressing the issue it causes. I have seen it mentioned that switching hands while Wielding could unwield, that may be a good solution?

The current state of unwielding is terrible QoL for shotguns that need you to manually cycle after every shot. Where the natural course would be to interact in-hand to cycle the shot as you used to, you need to alt-click the gun to cycle it which takes much more effort. This PR addresses that, and allows you to Wield, Cycle, Eject and Unwield (through dropping offhand) purely through keybinds.


> I have been informed you can switch to the second hand and press Drop to unwield. But by then I coded the QOL thing I mentioned, anyway

I think this could use a bit more discussion, because I believe that the off-hand wield could be used in the future for underbarrel weapons like the M-90 GL.

**Comment by deltanedas** [comment]
if that forum suggestion of wielding being a passive thing when you have a free hand was implemented, pressing z would always cycle and there would be no unwield so nothing to conflict with

**Comment by Errant-4** [comment]
> the off-hand wield could be used in the future for underbarrel weapons like the M-90 GL.

I think this would essentially create tech debt, because it would cement a solution where only two-handed weapons can use this alternate fire, and it only supports exactly one alternate fire per weapon. So the moment anyone would want to go further than that, they would need to create a new, more accomodating solution anyway

**Comment by Boaz1111** [comment]
> > the off-hand wield could be used in the future for underbarrel weapons like the M-90 GL.
> 
> I think this would essentially create tech debt, because it would cement a solution where only two-handed weapons can have such alternate fire, and it only supports exactly one alternate fire per weapon. So the moment anyone would want to go further than that, they would need to create a new, more accomodating solution anyway

we already have a form of alt fire, but it's for battery weapons

**Pull request merged**
