### PR TITLE
add tank and emergency box

### PR DESCRIPTION
**Pull request by pofitlo**
## About the PR

I added a nitrogen tank and an emergency kit with it. everything was prepared for slimes, but I'm too bad at C# code to implement a system for issuing equipment specifically for spacies. so... let me at least leave it like that. maybe someone, someday, will realize this

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: nitrogen tank and an emergency kit with it

A1

### CODE REVIEW

**Comment by crazybrain23** [comment]
The changelog could easily get slime player's hopes up. Might be worth adding a disclaimer that they won't actually get the box.

**Comment by Scribbles0** [comment]
maybe add the emergency and regular nitrogen tanks to emergency lockers? we don't have them in there, only the o2 tank variants

**Comment by deltanedas** [comment]
yeah it should also be in emergency locker loot pool

**Comment by moonheart08** [comment]
Unused content is not permitted, this should be integrated in properly as an alternate emergency kit in order to make it into the game.

**Pull request closed without merging**
