### PR TITLE
Cobra price fix

### PR DESCRIPTION
**Pull request by metalgearsloth**
It fires caseless rifle ammo at 4x a second so is a bit stronger than the other options.

:cl:
- tweak: Bump cobra TC cost.

### CODE REVIEW

**Comment by LankLTE** [comment]
I think 10 is too high personally

**Comment by AjexRose** [comment]
wasnt the cobra pre-pistol-price-cut 8 tc?

**Comment by metalgearsloth** [comment]
6 instead?

**Comment by LankLTE** [comment]
I was gonna say 6, 8 might make more sense as a middleground but I think having guns at varying prices is good for the uplink

**Comment by liltenhead** [comment]
The cobra has worse dps than every other syndicate gun in the game currently besides the python. However, the python does 52 dps regardless of armor, or species resistance, making it a more efficient gun in many scenarios. 

If anything the cost of the ammo could be increased to discourage using a gun meant for assassinations in a normal fire fight.

**Comment by deltanedas** [comment]
cobra also has an extremely distinct sound which immedistely leads to callouts of "cobra shots at X location", making the gun itself more expensive would make it even more unreasonable for pros which would pre price cut rarely use pistols, if ever.

**Comment by metalgearsloth** [comment]
Dumped my list on discord but I'll get through bolts + that first and revisit:

- dump values into spreadsheet
- make c20r burst fire
- make LMGs / rifles / snipers better accuracy than SMG but require wielding
- buff shotguns (bulldog etc.), honestly just make them 2shot kills point blank
- nerf china lake (again)
- nerf hardsuit explosion resistance
- stam damage nerf again
- probably nerf soaps idk

**Comment by deltanedas** [comment]
soap nerf evil evil evil evil evil evil :trollface:

**Pull request closed without merging**
