### PR TITLE
Moths get insect blood

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Weird that moths have human blood when they're insects. 
I love bleeding sewerage.
PRed at the request of MrGloopy (Myr'thel Salic).

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- tweak: Moths now have insect blood.

### CODE REVIEW

**Comment by brainfood1183** [comment]
insects do not have hemocyanin blood though, also spiders are not insects they are arachnids.

**Comment by PixelTheKermit** [comment]
image

**Comment by MrGloopy** [comment]
> image
> 

Could give them slime blood then? If not a new yellow blood type, but I feel more blood types would be getting into the realm of potential bloat.

**Comment by PixelTheKermit** [comment]
> > image
> 
> Could give them slime blood then? If not a new yellow blood type, but I feel more blood types would be getting into the realm of potential bloat.

Giving them slime blood is silly. It's imo better to just make a new blood solution (It's really not that hard to do, and could be reused for other insects.)

**Comment by Dutch-VanDerLinde** [comment]
if theres gonna be a new blood type, give it to cockroaches too since they are insects aswell and currently use slime blood

**Comment by UbaserB** [comment]
Whichever blood the maintainers decide on, im still waiting on their review.

**Comment by LankLTE** [comment]
I think that, at least, moths shouldn't get blue blood. It doesn't make a ton of sense.

**Comment by mirrorcult** [comment]
moths should not get blue blood

**Comment by UbaserB** [comment]
Would slime blood, or insect blood (i will have to make a new reagent for this) be a better alternative?

**Comment by UbaserB** [comment]
Im going to make it use insect blood, so im drafting for now.

**Comment by UbaserB** [comment]
just triple checked it, should be good to go and ready for review now. These changes are based on what u maintainers seen to feel is ok.

**Comment by brainfood1183** [comment]
https://i.pinimg.com/736x/03/5f/e4/035fe43c77579c6b12e97df569d2a855.jpg

**Comment by brainfood1183** [comment]
035fe43c77579c6b12e97df569d2a855
All the different colored blood types.

**Comment by UbaserB** [comment]
> All the different colored blood types.

i dont see invertebrates in this list

**Comment by mirrorcult** [comment]
should be yellower

**Comment by UbaserB** [comment]
> should be yellower

ok let me do that in 1 second

**Comment by UbaserB** [comment]
its yellower now

**Review by mirrorcult — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
