### PR TITLE
Roundstart antag role restrictions

### PR DESCRIPTION
**Pull request by VigersRay**
## About the PR

Adds the ability to specify time requirements for setting antagonist checkboxes. Most likely, nuclear operatives need this, people who do not know how to turn on the harm mod or heal should not fall for such antagonists.

Depends:
https://github.com/space-wizards/space-station-14/pull/17925

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

### CODE REVIEW

**Comment by lzk228** [comment]
would be good if there was no checkfield, but just a "Locked" or ❌

**Comment by EmoGarbage404** [comment]
> would be good if there was no checkfield, but just a "Locked" or ❌

this could probably be done by hiding the checkbox and making a small texture visible.

**Comment by metalgearsloth** [comment]
Honestly it should just be similar to jobs, with categories + locked showing if it's restricted.

**Comment by VigersRay** [comment]
> было бы хорошо, если бы не было контрольного поля, а было бы просто "Заблокировано" или❌

I wanted to do this, but unfortunately there is a list that can only contain objects of the checkbox type.
Of course, for the checkbox, you can change the picture of the pressed state, but for some reason you can’t change the square. In any case, knowing that I tried to do it but could not.

**Comment by VigersRay** [comment]
> Honestly it should just be similar to jobs, with categories + locked showing if it's restricted.

Type to do as a list of works but instead prioritize two buttons "yes" and "never"? Or is it also a priority for antagonists? So far, this makes little sense given that we never have more than one antagonist in the game.
Or is it about the fact that if the antagonist is blocked, then draw a line on top of it that says blocked?

**Comment by lzk228** [comment]
> "yes" and "never"

just "Yes/No"

**Comment by EmoGarbage404** [comment]
image
 goofy mspaint example.

**Comment by deltanedas** [comment]
i think improving the ui should be for another pr, better to have competent nukies first

**Comment by metalgearsloth** [comment]
Don't need categories for now but 100% needs UI reflecting if the role is restricted or not which only requires a single control to be added.

**Comment by metalgearsloth** [comment]
I'm working on something else to restrict antags so might end up doing the required changes.

**Comment by metalgearsloth** [comment]
> I'm working on something else to restrict antags so might end up doing the required changes.

I did not end up finishing it but UI needs to reflect it in this pr and it shouldn't take long to do, please.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
A visual UI representation like in emo's mockup (or something similar) is necessary

**Pull request closed without merging**
