### PR TITLE
Double base cigarette and cigar volume and inhalation speed

### PR DESCRIPTION
**Pull request by BuggsWorth**
## About the PR

Doubles the volume of the base cigarette and cigar entities (aligning normal cigarettes with "Dan's soaked smokes") and doubles the rate at which chemicals in smokeables are inhaled to counter its extended duration.

## Why / Balance

Many chemicals and narcotics when added to cigarettes are either not abundant enough and/or do not metabolize fast enough to possess a significant threat or achieve a desired effect, allowing more room for chemicals to be added means that a higher amount of said chemicals will enter the blood stream allowing for longer or more potent effects with accumulation. This will expand upon gameplay opportunities for the entrepreneurial Chemist, Syndicate Agent with a chemical kit, or Botanist with a "Green" thumb alike. This change will also indirectly buff the Syndicate Omnizine cigarette, allowing it to be inhaled/metabolized faster.

**Numbers:**
Normal cigarettes containing 10u of Nicotine will be finished in ~2 minutes (from ~4 minutes)
Cigarettes as they are in game with a full 20u of chemicals normally last ~8 minutes (~4 minutes with this change)
Cigarettes with a full 40u of chemicals such as the Syndicate Omnizine smoke will be finished in ~8 minutes (from ~12 minutes)
+/- 30 seconds

## Technical details

Simply doubles the smokeable max volume to the base cigarette/cigar entity to 40 from 20 and doubles the inhalation amount per second to 0.1 from 0.05, this will make cigarettes metabolize 0.30u per inhalation from 0.15 in practice.
The increase in the inhalation amount per second is done to offset the additional time that would be needed to completely smoke a cigarette with its additional volume in the event chemicals are added and increase the amount of chemicals entering the body, this would mean that normal cigarettes without chemicals will last a lot shorter however, as the time to finish a smoke is tied to remaining chemicals (when Nicotine runs out the cigarette becomes unlit/consumed).

Additionally, doubled the amount of added chemicals in Dan's soaked smokes to extend its duration.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Doubled the volume of chemicals that cigarettes/cigars can hold to 40u total
- tweak: Cigarettes/cigars are now smoked and metabolize chemicals much faster
- tweak: "Dan" figured out how to add more chemicals to his soaked smokes

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
My only complaint is that this makes cigs run out very quickly, I usually smoke cigs in-game roundstart till end.

normal cigs, I usually smoke 3-4 packs or so

Dan's soaked, my fav, a shift I smoke 2 packs clean

after this change, I will be smoking 3-4 if it's dan's soaked smokes, and around 7-8 of normal packs during my usual shift. I already feel 4 minutes is pretty scuffed for constantly needing to light a new cig, why I love Dan's as is right now.

No way to at least have one brand be the "long lasting" cig? I just want to be able to smoke for rp reasons, the current 8min per dan's soaked cig feels fair and not too annoying for the fact I only want it as a cosmetic rp thing.

**Comment by BuggsWorth** [comment]
> My only complaint is that this makes cigs run out very quickly, I usually smoke cigs in-game roundstart till end.
> 
> normal cigs, I usually smoke 3-4 packs or so
> 
> Dan's soaked, my fav, a shift I smoke 2 packs clean
> 
> after this change, I will be smoking 3-4 if it's dan's soaked smokes, and around 7-8 of normal packs during my usual shift. I already feel 4 minutes is pretty scuffed for constantly needing to light a new cig, why I love Dan's as is right now.
> 
> No way to at least have one brand be the "long lasting" cig? I just want to be able to smoke for rp reasons, the current 8min per dan's soaked cig feels fair and not too annoying for the fact I only want it as a cosmetic rp thing.

If for RP reasons there should be a brand of longer lasting smokes, I could just buff the amount of reagents inside Dan's, as they are its either 10u of medicines or 2-5u narcotics along with the base 10u nicotine which makes it last longer.

**Comment by thebadman4662** [comment]
> My only complaint is that this makes cigs run out very quickly, I usually smoke cigs in-game roundstart till end.
> 
> normal cigs, I usually smoke 3-4 packs or so
> 
> Dan's soaked, my fav, a shift I smoke 2 packs clean
> 
> after this change, I will be smoking 3-4 if it's dan's soaked smokes, and around 7-8 of normal packs during my usual shift. I already feel 4 minutes is pretty scuffed for constantly needing to light a new cig, why I love Dan's as is right now.
> 
> No way to at least have one brand be the "long lasting" cig? I just want to be able to smoke for rp reasons, the current 8min per dan's soaked cig feels fair and not too annoying for the fact I only want it as a cosmetic rp thing.

If simply fact something is smoking in your characters mouth is enough for you then you could... douse them with water or drinks over the course of shift. Cigarettes do not care what kind of chems get injected... Try potassium cigs sometime after drinking water :trollface:

**Comment by BuggsWorth** [comment]
> > My only complaint is that this makes cigs run out very quickly, I usually smoke cigs in-game roundstart till end.
> > normal cigs, I usually smoke 3-4 packs or so
> > Dan's soaked, my fav, a shift I smoke 2 packs clean
> > after this change, I will be smoking 3-4 if it's dan's soaked smokes, and around 7-8 of normal packs during my usual shift. I already feel 4 minutes is pretty scuffed for constantly needing to light a new cig, why I love Dan's as is right now.
> > No way to at least have one brand be the "long lasting" cig? I just want to be able to smoke for rp reasons, the current 8min per dan's soaked cig feels fair and not too annoying for the fact I only want it as a cosmetic rp thing.
> 
> If simply fact something is smoking in your characters mouth is enough for you then you could... douse them with water or drinks over the course of shift. Cigarettes do not care what kind of chems get injected... Try potassium cigs sometime after drinking water :trollface:

There shouldnt be need for a workaround for roleplay, ill look into buffing Dan's later when I have the time. But Potassium Water cigs are something I NEED to try.

**Comment by BuggsWorth** [comment]
Doubled the amount of chemicals added in Dan's soaked smokes to extend its duration

**Comment by IProduceWidgets** [comment]
It might be better to make cigs burn a fixed amount of time and just change the solution injection rate to meet that instead of how they work now.

**Comment by Hanzdegloker** [comment]
> Doubled the amount of chemicals added in Dan's soaked smokes to extend its duration, they should last ~6 minutes instead of ~2-4 minutes depending on what cigarette you get

Chain smokers, we are so back

**Comment by BuggsWorth** [comment]
> It might be better to make cigs burn a fixed amount of time and just vary the solution injection rate to meet that instead of how they work now.

This is a much better idea, plus my PR was a bit short sighted (didnt account for cigars). As we speak im working on modifying the SmokableComponent to scale the inhalation rate with the reagent quantity and a set duration for smokables.

**Pull request closed without merging**
