### PR TITLE
remove evac shuttle emag lmao

### PR DESCRIPTION
**Pull request by Emisse**
horrifically abusable

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by deltanedas** [comment]
hijack emergency shuttle objective for actual syndies in shambles now :trollface:

**Comment by Clostyandr** [comment]
Do some shitcode, make it EMAGable only for traitors!

**Comment by deltanedas** [comment]
can this be reverted now that revenant cant emag it, or maybe have it check that you actually have the objective

**Comment by VasilisThePikachu** [comment]
the problem here was that people were just metagaming the position of the command room in space so once the shuttle arrived they would be inside the command room where they can instantly hijack the shuttle

**Comment by deltanedas** [comment]
thats meant to smish them, just fix that and problem solved

**Pull request merged**
