### PR TITLE
Librarian gameplay (DND, but in SS14)

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
## About the PR

Improves tabletop by allowing players to clone objects to a tabletop and remove them. This means that, yes, you can now play ~~Dungeons and Dragons~~ Crypts & Carps and ~~Warhammer 40k~~ Conflictwrench 80k. No, you unfortunately cannot remove chess pieces and toy with lifesized chess pieces.

This hopefully gives librarians some fun to do outside of organizing books in the library.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
https://cdn.discordapp.com/attachments/782607766799253528/1114069889037107251/DNDSheetPR.mp4

**Changelog**

:cl: eclips_e
- add: Nanotrasen has decided to supply their librarians with the famous game Crypts and Carps' character sheets, and have advised people to avoid calling it by a similarly named board game that starts with D.
- add: You can now put in and take out objects from and into tabletop games (chess, battlemaps, more).

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
rain woke up today like "oh i'm gonna be productive" and then in 2 hours i'll be dead

**Comment by mirrorcult** [comment]
@Visne your vision is being realized

**Comment by Just-a-Unity-Dev** [comment]
> > The explosive actually does have an effect
> 
> I mean outside of the board

Does it really matter though? If a syndie places a C4 inside of the board then that's on them lol

**Comment by Just-a-Unity-Dev** [comment]
> if a syndie throws an explosive at someone they shouldn't be able to effectively disarm it by hitting a board with it

eh, fair enough i guess. do explosives have a tag that i can just add to the ent blacklist?

**Comment by Just-a-Unity-Dev** [comment]
bwuh, erroneous test fails

**Comment by EmoGarbage404** [comment]
I get that 'DND' isn't a formal trademark of WOTC (as far as I can tell), but Dungeons & Dragons and D&D are, from what I can tell. I think it's frankly just a bit close for comfort, especially with the character sheets, which are near direct copies. Consider renaming it to something else?

**Comment by deltanedas** [comment]
space dungeons and space dragons

**Comment by Just-a-Unity-Dev** [comment]
I was recommended Carps & Crypts

**Comment by VektorZ1** [comment]
I think it would be better to make copying things to the board, without the ability to pull, but only to delete. It might not make as much sense IC (though who cares?), but it would avoid the problems described above and similar in the future.

**Comment by mirrorcult** [comment]
this should really be a whitelist

alternatively: iirc visne's original idea with this is that items on top of the table the game is on would have their sprites copied into the tabletop world. that way u dont have to deal with actually putting them in the tabletop world

**Comment by Just-a-Unity-Dev** [comment]
> iirc visne's original idea with this is that items on top of the table the game is on would have their sprites copied into the tabletop world. that way u dont have to deal with actually putting them in the tabletop world

guess I can do this

**Comment by Just-a-Unity-Dev** [comment]
gweuh

**Comment by Visne** [comment]
End goal (of my idea) would be to have the entire table and the (whitelisted) items on it inside of your viewport, so doing it so only items on the table appear in the viewport sounds like a good step into that direction to me. Also, it makes more sense to then show the items in both the viewport and in the normal world, instead of moving items "in and out" of the tabletop view.

For now it probably makes sense to show all items you put on the table in the tabletop viewport, but in the future I guess it would be so that only specific tabletop gaming items are shown in the viewport, and then for example a pack of cards which would be 1 item in the normal world would become a stack of 52 individual cards in the tabletop view. Those can then be interacted with just as in Tabletop Simulator on Steam, where you can flip them and put them in your hand etc.

> I was recommended Carps & Crypts

I remember someone coming up with 'Syndies & Spacecrafts' or something like that somewhere in the past (Discord search sucks so much)

**Comment by Just-a-Unity-Dev** [comment]
a

**Comment by Just-a-Unity-Dev** [comment]
ghhhhhhhhhhghghrewerewhhhh why

**Comment by Just-a-Unity-Dev** [comment]
ok test fail is erroneous

**Comment by Just-a-Unity-Dev** [comment]
grah

**Comment by Just-a-Unity-Dev** [comment]
eh i'll work on this

**Comment by Just-a-Unity-Dev** [comment]
> It's unintuitive to have to be holding the object when you right click, but having to be holding it can prevent accidental deletions. Maybe it could have a doafter, but I don't think it needs one. Not having to hold it + a doafter might be a more intuitive option.

I don't really get how holding + RMB is unintuitive, alongside that, what right click does at the moment is get the currently held entity and request for it to be deleted to prevent code duplication. Right click menu would also likely involve some form of hacks in order to get it working.

**Comment by Just-a-Unity-Dev** [comment]
You hold left click to select and right click to remove the selected object I don't think this is unintuitive

**Comment by Just-a-Unity-Dev** [comment]
REJOICE

**Pull request merged**
