### PR TITLE
Colourblind-friendly Hunger and Thirst Icons

### PR DESCRIPTION
**Pull request by Keikiru**
## About the PR

Changes the icons for the three stages of both Hunger and Thrist to be more visually distinct from their other stages and to no longer rely on colour coding.
Creates a flashing animated sprite for Starvation and Parched states, making them much more noticable with the intention to draw attention towards managing these states.

Related: https://github.com/space-wizards/space-station-14/issues/18032#issuecomment-1636675201

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

<details>
<summary>First iteration</summary>

dotnet_9SReiOdDmu
dotnet_kNb3Tf4iRf

</details>

**Second iteration**:
thirsty and peckish icons
starving and parched icons

**Changelog**

:cl: Keiku
- tweak: Improve hunger and thirst warning icons

### CODE REVIEW

**Comment by mirrorcult** [comment]
definitely much better spritework and colorblind-friendly icons are always good, im not sure the thirst ones make a lot of sense to me though

**Comment by Keikiru** [comment]
> definitely much better spritework and colorblind-friendly icons are always good, im not sure the thirst ones make a lot of sense to me though

Thank you!
I'm not entirely confident on how to convey increasing levels of Thirst, so it's something I will iterate on further.

**Comment by moonheart08** [comment]
I think the thirst one is a clear enough indicator personally, definitely a big improvement over the prior one.

Color-blind icons are always a nice to have, we really need more accessibility features.

**Comment by Keikiru** [comment]
Thirst icons have been changed and the screenshots have been updated. I'm much happier with this second iteration.
How do the new ones look?

**Comment by lzk228** [comment]
that's really should ve toggleable

**Comment by mirrorcult** [comment]
yeah i like the new ones a lot more

**Comment by ficcialfaint** [comment]
These are great, but the starving one seems a bit complicated to me and the yellow outline looks a bit of weird (the shape I mean)

**Comment by Partmedia** [comment]
Thank you for your contribution!

**Pull request merged**
