### PR TITLE
Sleeper Agents

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Adds Sleeper Agents from Goon. The chance of Sleeper Agents showing up on station can happen regardless of what mode is selected, and if Traitors are on station, they can get objectives to activate Sleeper Agents with specific phrases. About 20-30 minutes into a round, the CentCom radio system will be hijacked and broadcast an audio file that immediately activates all Sleeper Agents on station. However, this announcement can happen even if there are no Agents to activate, adding to the paranoia! 

**Screenshots**

**Changelog**

:cl:
- add: *khzrrt* ALPHA MIKE OCTOBER GOLF UNIFORM SIERRA *khrzzzzzzt*

### CODE REVIEW

**Comment by Partmedia** [comment]
Could you comment on the balance changes from Sleeper Agents? Specifically, given that there are already mid-round antags, what is more "fun" about a Sleeper Agent?

For those of you unfamiliar, Sleeper Agents do not receive their objectives until they are "activated" by someone saying the phrase that activates them.

**Comment by Elijahrane** [comment]
according to https://github.com/space-wizards/space-station-14/issues/8524 there's an antag freeze

**Comment by Just-a-Unity-Dev** [comment]
> according to #8524 there's an antag freeze

If I recall correctly this was greenlit by a maintainer, I may be wrong though

**Comment by Just-a-Unity-Dev** [comment]
Are you doing this *entirely* from web-edit?

**Comment by GoodWheatley** [comment]
> according to #8524 there's an antag freeze

Personally asked moony and got the greenlight to do this

**Comment by GoodWheatley** [comment]
> Are you doing this _entirely_ from web-edit?

Yes (I’m installing Rider this weekend I’m actually going insane)

**Comment by GoodWheatley** [comment]
Quick todo list so future me doesn't forget what to do:
- Actually code SleeperAgentRuleSystem, make sure the phrase activation system works properly
- Add gamerules so the Agent Activation event a) doesn't happen if the gamemode is Traitor b) has a chance to happen even with no Sleeper Agents on station
- Add cool audio for the Agent Activation event
- Make sure Sleeper Agents and their objectives show up on the round end screen, and specify if they were activated or unactivated.
- Code the "Activate Sleeper Agent" objective
- Finally, make sure that Sleeper Agents only are able to see the uplink upon being activated

**Comment by GoodWheatley** [comment]
Updated todo list:
- Crush all the bugs in SleeperAgentRuleSystem 
- Still gotta add those gamerules for the event triggering
- Still working on cool audio
- Code "Activate Sleeper Agent" Objective

**Comment by GoodWheatley** [comment]
All the major code parts are done so its ready for review I guess, come on down to laugh at my kitbashed hackjob C# code

**Comment by Just-a-Unity-Dev** [comment]
Wheatley, please get an IDE. Your PR doesn't even build.

**Comment by mirrorcult** [comment]
as is stated in our PR guidelines you should avoid using the github web editor for any PRs, especially for C# PRs, and especially for PRs of this size. this is not a supported method of development and is far too error prone, which puts an extremely heavy burden on reviewers. re-open the PR when you've properly rewritten it using an actual IDE.

**Pull request closed without merging**
