### PR TITLE
fix legally distinct visor man plush name.

### PR DESCRIPTION
**Pull request by PJB3005**
am in vr. approved by real spaniard.

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
vrchat moment

**Comment by PJB3005** [comment]
i have made a github pr while unable to move head in vr evena phone would be less bad.

**Comment by EmoGarbage404** [comment]
Closed for webedit

**Comment by PJB3005** [comment]
> Closed for webedit

Dont you ever say that to me again i had to figure out how to exit vim on the steamvr keyboard bitch.

**Comment by VasilisThePikachu** [comment]
> > Closed for webedit
> 
> Dont you ever say that to me again i had to figure out how to exit vim on the steamvr keyboard bitch.

W-what... How? I'm... Scared

I mean it's probably not too hard... Why

**Comment by PJB3005** [comment]
> > > Closed for webedit
> > 
> > 
> > Dont you ever say that to me again i had to figure out how to exit vim on the steamvr keyboard bitch.
> 
> W-what... How? I'm... Scared
> 
> I mean it's probably not too hard... Why

SteamVR keyboard doesn't have an esc key to switch mode.

I tried to open Windows' on-screen keyboard instead but SteamVR can't interact with it and I had to close it trough System Informer.

**Comment by nikthechampiongr** [comment]
> SteamVR keyboard doesn't have an esc key to switch mode.


Sounds like a skill issue for not binding zz to switch you to normal mode.

**Comment by rbertoche** [comment]
By the way, I think it's worth noting that this was not wrote by a spanish speaker, it was actually made by a portuguese speaking brazilian contributor, so it wasn't a fix, rather it just changed the language of it from portuguese to spanish.
Just as a clarification, nothing else. It wasn't my contribution or anything.

**Pull request merged**
