### PR TITLE
Unbreak the Geneva Conventions

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Burn the papers, destroy the evidence, we had a red cross. It is now a skull. It flashes. It draws the player's attention to it just as before.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
I know this is technically not really a player facing change that would need a cl but please, just let me have this one. It's too funny not to have.

:cl: Errant
- fix: HUD elements no longer violate the Geneva Conventions.

### CODE REVIEW

**Comment by nikthechampiongr** [comment]
Wait so we can't violate the Geneva conventions?

**Comment by Errant-4** [comment]
> Wait so we can't violate the Geneva conventions?

You can, the game UI shouldn't

**Comment by JoeHammad1844** [comment]
1984

**Comment by JoeHammad1844** [comment]
just make it a green cross instead like paradise station

**Comment by lzk228** [comment]
i don't understand the joke...

**Comment by Errant-4** [comment]
> i don't understand the joke...

The game is technically literally violating the real world Geneva Conventions by displaying the red cross, which is a protected symbol. The joke is that "we are no longer in violation of the Geneva Conventions" sounds hilarious, even though it's actually true (and even though we were unlikely to receive even a strongly worded letter for it)

**Comment by nikthechampiongr** [comment]
Specifically Article 44 of the Geneva Conventions of 12 August 1949.

**Comment by Errant-4** [comment]
This issue was previously discussed on #3396 when a medkit with the red cross symbol was submitted. That is of course a more direct violation, but it does not mean that a HUD icon isn't. Back then, it was decided to not use the symbol.

**Comment by deltanedas** [comment]
green cross might seem like healing, this is a good compromise

**Review by juliangiebel — APPROVED** [review]
I also think that the skull is a good compromise vs the usual green cross used as a  replacement to the red one

**Comment by Flareguy** [comment]
I don't like this very much. It doesn't contrast well due to not having a background, and doesn't really convey "you need to seek medical attention" as well as the old icon. I worry that someone seeing this for the first time might think they are actively dying or something.

If you aren't sure of a better replacement for the skull, you should at least add a white background to it, like what the cross has now.

**Comment by UbaserB** [comment]
the skull looks goofy

**Comment by nikthechampiongr** [comment]
> the + feels more iconic to me

For that you'd need to swap colors around.

**Comment by Errant-4** [comment]
> the skull looks goofy

Name me one thing that doesn't look goofy in this game

> I don't like this very much. It doesn't contrast well due to not having a background, and doesn't really convey "you need to seek medical attention" as well as the old icon. I worry that someone seeing this for the first time might think they are actively dying or something.
> 
> If you aren't sure of a better replacement for the skull, you should at least add a white background to it, like what the cross has now.

I mean, if they see that icon, the chances are quite high they ARE actively dying to something, perhaps blood loss, and have seconds to cry for help or something. That cross/skull is only there on the last stage before crit 
But I guess the art director spoketh. I can't add a white background for a white skull, though.
I'll see what I can come up with

**Comment by OctoRocket** [comment]
Their health says BAD! They'll know that they need medical assistance. I like the skull better than the current cross.

**Comment by Flareguy** [comment]
> I mean, if they see that icon, the chances are quite high they ARE actively dying to something, perhaps blood loss, and have seconds to cry for help or something. That cross/skull is only there on the last stage before crit But I guess the art director spoketh. I can't add a white background for a white skull, though. I'll see what I can come up with

I was trying to imply a red skull on a white background. I probably should have clearly stated that.
> 
> As mentioned above, it could be a red background white cross, I think that's okay?

I feel like this could contrast weirdly, but it's worth a shot. If it doesn't work, I'd suggest trying other things like changing the cross's color or giving it a white outline on top of the red BG or whatever.

**Comment by Sirionaut** [comment]
> Article 44 of the Geneva Conventions of 12 August 1949.

Gonna be the stickler here, and say no. 

There are 4 Geneva Convention, each with an Articel 44.

**Comment by nikthechampiongr** [comment]
> > Article 44 of the Geneva Conventions of 12 August 1949.
> 
> Gonna be the stickler here.
> 
> There are 4 Geneva Convention, each with an Article 44.
> 
> It starts with Article 38 of the first Convention, which does allow the use of the symbol for medical personnel of armed forces. Same with medical buildings.
> 
> > Article 39 - Use of the emblem
> > Under the direction of the competent military authority, the emblem shall be displayed on the flags, armlets and **on all equipment employed in the Medical Service.**
> 
> https://ihl-databases.icrc.org/en/ihl-treaties/gci-1949/chapter-7/commentary/2016?activeTab=1949GCs-APs-and-commentaries
> 
> The red cross just goes with the "every use is illegal" story because it gets them attention.
> 
> IF we wanna go full rules lawyer, any monochromatic flag with a cross shape on it is illegal, because it can be seen as making fun of the Swiss flag, which is protected from being denigrated by the Geneva convention.
> 
> > (2) By reason of the tribute paid to Switzerland by the adoption of the reversed Federal colours, and of the confusion which may arise between the arms of Switzerland and the distinctive emblem of the Convention, the use by private individuals, societies or firms, of the arms of the Swiss Confederation, or of **marks constituting an imitation thereof,** whether as trademarks or commercial marks, or as parts of such marks, or for a purpose contrary to commercial honesty, or in circumstances capable of wounding Swiss national sentiment, shall be prohibited at all times.
> 
> Disrespecting the Swiss flag is a war crime. Displaying the red cross properly on medical equipment in a scifi corporate warzone probably isnt.

I was just referring to the first which is good enough. Should have probably mentioned it to tho. 


>With the exception of the cases mentioned in the following paragraphs of the present Article, the emblem of the Red Cross on a white ground and the words "Red Cross", or "Geneva Cross" may not be employed, either in time of peace or in time of war, except to indicate or to protect the medical units and establishments, the personnel and material protected by the present Convention and other Conventions dealing with similar matters. The same shall apply to the emblems mentioned in Article, second paragraph , in respect of the countries which use them. The National Red Cross Societies and other Societies designated in Article 
 shall have the right to use the distinctive emblem conferring the protection of the Convention only within the framework of the present paragraph.

**Comment by SonicHDC** [comment]
Weh, no more med cross. Only white goomba...

**Pull request merged**
