### PR TITLE
Add pipe destruction behavior

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
This adds a destruction behavior to pipes, namely, converting them to a broken pipe that can be unwrenched and welded.

## Why / Balance
It makes a bit more sense for pipes to break when damaged, like disposal pipes, instead of disappearing immediately. This is also a quality of life prerequisite for future pressure-based pipe damage, because having pipes evaporate into thin air without any indication of what went wrong is not good.

## Media

https://github.com/space-wizards/space-station-14/assets/3229565/dbbd5922-bc8a-4bfd-9d18-6631e51daf06

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: notafet
- tweak: Pipes now leak their contents when destroyed. Make sure to drain pipes before removing them.

### CODE REVIEW

**Comment by Partmedia** [comment]
Pipes now burst when destroyed. Needed to prevent cascading failures in the linked PR.

https://github.com/space-wizards/space-station-14/assets/3229565/364c88e0-ec4f-41bb-b41c-61e07127b082

**Review by keronshb — CHANGES_REQUESTED** [review]
I'd like to see the following:

- A screenshot/video of the current damaging system of what it would look like when pipes are damaged under tiles.

- Pipe damage should leave more hints on what broke
  - The current way its done makes it exceptionally hard to tell what kind of pipe broke
    - I wouldn't know if a T, + or L pipe broke since it's just 1/2 of a damaged pipe
  - Another screenshot/video of what these broken pipes would look like if there are tiles

- If broken somewhere in the station, what devices can an atmos tech use to find where it is?
  - Please try loading a station, having a few pipes break, and then try to find them with the current devices to see what I mean

**Comment by Partmedia** [comment]
> I'd like to see the following:
> 
>     * A screenshot/video of the current damaging system of what it would look like when pipes are damaged under tiles.
> 
>     * Pipe damage should leave more hints on what broke
>       
>       * The current way its done makes it exceptionally hard to tell what kind of pipe broke
>         
>         * I wouldn't know if a T, + or L pipe broke since it's just 1/2 of a damaged pipe
>       * Another screenshot/video of what these broken pipes would look like if there are tiles
> 
>     * If broken somewhere in the station, what devices can an atmos tech use to find where it is?
>       
>       * Please try loading a station, having a few pipes break, and then try to find them with the current devices to see what I mean

This PR only adds destruction behavior. Pipes breaking on pressure damage is in the other PR.

In this PR, there is no way to destroy pipes beyond hitting it with a crowbar.

**Comment by Partmedia** [comment]
>     * A screenshot/video of the current damaging system of what it would look like when pipes are damaged under tiles.
> 
>     * Pipe damage should leave more hints on what broke
>       
>       * The current way its done makes it exceptionally hard to tell what kind of pipe broke
>         
>         * I wouldn't know if a T, + or L pipe broke since it's just 1/2 of a damaged pipe
>       * Another screenshot/video of what these broken pipes would look like if there are tiles

This is how disposal junctions break. Players seem to be able to repair disposal junctions fine. I don't think this is a concern.

If you insist, then individual sprites for these pipes can be added.

Note that without this PR, *pipes simply disappear*. So this PR represents an improvement from the status quo.

**Comment by keronshb** [comment]
> This PR only adds destruction behavior. Pipes breaking on pressure damage is in the other PR.

That's fine. What you can do is pull from your pressure damage branch to this one temporarily and then cause some damage in the pipenet & report back with vids. Then just discard changes when you're done.

> If you insist, then individual sprites for these pipes can be added.

100% otherwise it's going to be exceptionally hard to figure out what was damaged

**Comment by Partmedia** [comment]
> > This PR only adds destruction behavior. Pipes breaking on pressure damage is in the other PR.
> 
> That's fine. What you can do is pull from your pressure damage branch to this one temporarily and then cause some damage in the pipenet & report back with vids. Then just discard changes when you're done.

IMO this change is not related to pressure damage. Even if pressure damage ultimately is not merged, then this change still makes sense because pipes currently *disappear* when destroyed.

> > If you insist, then individual sprites for these pipes can be added.
> 
> 100% otherwise it's going to be exceptionally hard to figure out what was damaged
> 
> I'd also say maybe make em a bit messy too. When they break in the media it's just neatly in the middle of the tile.

Sure, this can be done. Still, is the change here *not* an improvement over the current behavior, which is that it disappears entirely when you hit it with a crowbar?

**Comment by Partmedia** [comment]
It sounds like there may be some misunderstanding about what this actually changes.

**Current behaivor:** When you hit a pipe with a crowbar enough times, it simply disappears.

**New behavior:** When you hit a pipe with a crowbar enough times, it turns into a broken pipe and leaks gas, as if you unanchored it.

**Comment by LankLTE** [comment]
> **New behavior:** When you hit a pipe with a crowbar enough times, it turns into a broken pipe and leaks gas, as if you unanchored it.

Does this mean there’s no way to remove a pipe without it flooding the room? I’d honestly assumed the pipe not filling the room if broken was intentional and the point of atmos having an axe

**Comment by keronshb** [comment]
> IMO this change is not related to pressure damage. Even if pressure damage ultimately is not merged, then this change still makes sense because pipes currently _disappear_ when destroyed.

I was suggesting it as a way to try and blow up a pipe without needing to damage it yourself as a way to test it getting damaged underneath a tile.

> **New behavior:** When you hit a pipe with a crowbar enough times, it turns into a broken pipe and leaks gas, as if you unanchored it.

I saw in the other PR that all of the damaged pipes all became the same sprite, which makes it harder to discern what kind of pipe was broken.

**Comment by Partmedia** [comment]
Here is a recording of the old behavior:

https://github.com/space-wizards/space-station-14/assets/3229565/d74ccfa9-2d13-4436-82c6-93d19b792b82

Note that when the pipe is destroyed, it **simply disappears** which makes it very hard to tell that something has broken.

This is a recording of the new behavior:

https://github.com/space-wizards/space-station-14/assets/3229565/bfe09f94-f7a3-451b-a23c-0a8397992dc5

At the very least, it leaves evidence that there was a pipe there. This is not perfect, but I believe this represents an improvement over what currently happens, so I'm opting to merge this.

**Pull request merged**
