### PR TITLE
Fix construction action

### LINKED ISSUE #11028: Construction node actions are called three times when switching entities
## Description

Actions defined on a node that also changes entity, it causes the actions to be run three times. Once [on the old entity](https://github.com/space-wizards/space-station-14/blob/c55a015b77da8169434175aa29b306c892153511/Content.Server/Construction/ConstructionSystem.Graph.cs#L236), once when [spawning the new entity](https://github.com/space-wizards/space-station-14/blob/c55a015b77da8169434175aa29b306c892153511/Content.Server/Construction/ConstructionSystem.Graph.cs#L280), and then once [after transferring containers](https://github.com/space-wizards/space-station-14/blob/c55a015b77da8169434175aa29b306c892153511/Content.Server/Construction/ConstructionSystem.Graph.cs#L332).

**Reproduction**

1. Make a constructionGraph node that defines `entity:` and `actions:`
2. Build to the node.
3. Code runs the defined `actions:` three times.

```yml
- type: entity
  name: dummy
  id: Dummy
  components:
  - type: Construction
    graph: DummyConstruction
    node: firstNode
  - type: Sprite
    sprite: error.rsi
    state: error
  - type: Clickable

- type: entity
  parent: Dummy
  name: dummy2
  id: Dummy2
  components:
  - type: Construction
    graph: DummyConstruction
    node: secondNode

- type: entity
  parent: BaseItem
  name: dummy counter
  id: DummyCounter
  components:
  - type: Sprite
    sprite: error.rsi
    state: error

- type: constructionGraph
  id: DummyConstruction
  start: start
  graph:
  - node: start
    edges:
    - to: firstNode
      steps:
      - material: Steel
        amount: 1

  - node: firstNode
    entity: Dummy
    edges:
    - to: secondNode
      steps:
      - tool: Screwing
    - to: start
      steps:
      - tool: Anchoring

  - node: secondNode
    entity: Dummy2
    actions:
    - !type:SpawnPrototype
      prototype: DummyCounter
    edges:
    - to: firstNode
      steps:
      - tool: Anchoring

- type: construction
  name: dummy construction
  id: DummyConstruction
  graph: DummyConstruction
  startNode: start
  targetNode: firstNode
  category: test
  objectType: Structure
  placementMode: SnapgridCenter
  icon:
    sprite: error.rsi
    state: error
```

**Additional context**

So far this hasn't really affected any construction, since actions on nodes are both rare and usually don't depend on previous state.

### PR DESCRIPTION
**Pull request by rolfero**
## About the PR 

Fixes #11028

### CODE REVIEW

**Comment by Zumorica** [comment]
DNM until I personally test this

**Review by Zumorica — COMMENTED** [review]
This introduces a bug: if a node & entity change occurs, the executed node actions will *not* get the user entity. That's because the actions will get executed on component startup where the user entityuid is not available. I don't think this has an easy fix.

**Comment by rolfero** [comment]
> This introduces a bug: if a node & entity change occurs, the executed node actions will _not_ get the user entity. That's because the actions will get executed on component startup where the user entityuid is not available. I don't think this has an easy fix.

Could you split the actions into two: spawn actions and finished construction action? This gives you the added benefit of having one set of actions called on entity spawn, whether it is placed on the map or by other means, and one set of actions only called when construction is finished.

**Comment by Zumorica** [comment]
> Could you split the actions into two: spawn actions and finished construction action? This gives you the added benefit of having one set of actions called on entity spawn, whether it is placed on the map or by other means, and one set of actions only called when construction is finished.

Sounds like overcomplicating things for no good reason, and in most cases you'd end up with *a lot* of duplicated code...

**Comment by rolfero** [comment]
> > Could you split the actions into two: spawn actions and finished construction action? This gives you the added benefit of having one set of actions called on entity spawn, whether it is placed on the map or by other means, and one set of actions only called when construction is finished.
> 
> Sounds like overcomplicating things for no good reason, and in most cases you'd end up with _a lot_ of duplicated code...

Its adding one IGraphAction field, and calling it instead of .Actions, so not much duplicated code. Since this bug still doesnt affect any current constructions, nothing even needs to be updated, its just added functionality.

**Comment by Zumorica** [comment]
> Its adding one IGraphAction field, and calling it instead of .Actions, so not much duplicated code. Since this bug still doesnt affect any current constructions, nothing even needs to be updated, its just added functionality.

Ah, you made it sounds like you wanted to create an entirely new type of actions *just for this*, not just adding a new list of actions somewhere.

I'm not a fan of this solution as it feels hacky, but I'm not opposed to it.

**Comment by rolfero** [comment]
> > Its adding one IGraphAction field, and calling it instead of .Actions, so not much duplicated code. Since this bug still doesnt affect any current constructions, nothing even needs to be updated, its just added functionality.
> 
> Ah, you made it sounds like you wanted to create an entirely new type of actions _just for this_, not just adding a new list of actions somewhere.
> 
> I'm not a fan of this solution as it feels hacky, but I'm not opposed to it.

It does feel hacky, I agree, but it does come with the added functionality to separate actions called when an entity is spawned (which is the situation currently), and actions called when a node is reached through construction.
This should mean that you can easier add actions that happen when you finish constructing something (and that applies to the new entity), which doesn't apply to the entity when it is, for example, spawned on the map at round start.

I'm looking into the change right now, I'll try to see if it's feasible.

**Comment by Zumorica** [comment]
What's the benefit? What would you use this for? I honestly don't see it.

**Comment by rolfero** [comment]
> What's the benefit? What would you use this for? I honestly don't see it.

When I did #10987 I tried to have APC:s panels open using an action after construction - if I did this using a node action, all APC:s on the station would start with open panels.
And if I did it through an edge action, the new entity wouldn't be passed to the action, so the action wouldn't be called correctly.

I don't think it's obvious that whenever an entity spawns, if it has the construction component, it will call the entities construction node's actions upon initialization.

When a node & entity change occurs in a construction, there is currently no way to separate actions occuring during the construction (which will always have the user passed to them), and actions occuring during spawning (which will always need to handle not having a user passed to them).

**Comment by Zumorica** [comment]
> When I did #10987 I tried to have APC:s panels open using an action after construction - if I did this using a node action, all APC:s on the station would start with open panels. And if I did it through an edge action, the new entity wouldn't be passed to the action, so the action wouldn't be called correctly.

You could have just used a different prototype that starts with the panel already open, I don't really see the problem.

> I don't think it's obvious that whenever an entity spawns, if it has the construction component, it will call the entities construction node's actions upon initialization.

What can I say, this is explained in the [construction docs](https://docs.spacestation14.io/en/content/construction/index) but sure, I made it even more clear now.

> When a node & entity change occurs in a construction, there is currently no way to separate actions occuring during the construction (which will always have the user passed to them), and actions occuring during spawning (which will always need to handle not having a user passed to them).

They should both be the same. Node actions are meant to *always* modify the node entity in a certain way (such as changing a sprite, etc). If you want an entity in a node to differ between being spawned and reaching that node through construction, you should use a different node. An entity that reaches a node and an entity that has been spawned at a certain point *should be the same*.

**Comment by rolfero** [comment]
> You could have just used a different prototype that starts with the panel already open, I don't really see the problem.

Yes, and that's what I did in the end. But I was also told "This can also be done by adding an IGraphAction to the construction graph that opens the panel", which means maybe it's not that intuitive (which was probably the word I was looking for rather than "obvious")


But I do get your points regarding node actions, and I agree now that that's what's reasonable.

**Pull request merged**
