### PR TITLE
Disable climbing when buckled

### PR DESCRIPTION
**Pull request by metalgearsloth**
@nuke-makes-games @DrSmugleaf

### CODE REVIEW

**Review by DrSmugleaf — APPROVED** [review]

**Comment by ShadowCommander** [comment]
Shouldn't this be a CanMove check or something?

**Comment by ShadowCommander** [comment]
Oh, is this a fix getting buckled while in the process of climbing?

**Comment by RemieRichards** [comment]
@ShadowCommander while on a climbable, such as tables, you are `isClimbing` for the entire time.

**Comment by metalgearsloth** [comment]
> 
> 
> @ShadowCommander while on a climbable, such as tables, you are `isClimbing` for the entire time.

Yep. I mainly noticed in medical on saltern where you can buckle from a table and when you come out of the buckle you can immediately get back on the table again.

I don't think climbing should have a CanMove check because if you get stunned on a table you should still be on the table even though you can't move.

**Comment by RemieRichards** [comment]
yeah you definitely shouldn't fall off/through the table just because you got stunned.

**Pull request merged**
