### PR TITLE
Mop bugfix

### LINKED ISSUE #17036: Mop can't transfer to buckets when full
If mop has stuff on it and you try to transfer to a bucket full of water transfer is blocked or smth.

### PR DESCRIPTION
**Pull request by Fahasor**
## About the PR

Fixes bug with mop. Before if you attemp to transfer units of some mud into bucket and units of water exist into mop and bucket and mud that transfering does not fit in bucket, then you mop after interaction contain more than it must (more than maxVol). If mop in this state you can't use it until you spill mop for example (bad explanation).
Also tried to fix another bug. 
When you use mop with mud on container without water, but with something, then mop status does not updates.
edit code comments little bit for undestanding how mop mechanic must work.
Also i think i maybe changed work of popups.

Maybe my PR resolves #17036 but i don't know how to replicate it to undestand is it related to my PR

Sorry, i think this PR are bad, i just recode behaviour not by bugs, but by my view, so you can advise me something if you want

**Media**

First Bug

https://github.com/space-wizards/space-station-14/assets/70820551/ec10d351-4fd4-42dc-b38a-8ba6bcc0b45d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Mop now does not stops absorbing for no reason.

### CODE REVIEW

**Comment by Fahasor** [comment]
I think i must edit coments in code if they made to give understanding how mop mechanic must work, but i don't know how, i already made PR.

**Comment by DBrutski** [comment]
Hello @metalgearsloth .

I know @Fahasor face to face and he asked me to review this PR. I didn't check the sources. 

There're discussions:
1) The name of the PR should contain the name of an issue
2) The description should be in the issue
3) Steps of reproducing the bug should be in the issue
4) At first bug should be reproduced on incorrect version (preferably by unit test), and only then it is fixed.
5) Commit names should be meaningful and follow the project's guideline (e.g. https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53).
6) Commits should contain atomic changes so that they can be easily rolled back.
7) Comments in code should only be at the level of a public method or class, the rest should be discarded.

What I missed? 
What to do with those issues?

Best regards,
Dzmitry.

**Comment by metalgearsloth** [comment]
PR looks fine?

**Comment by rudi-kit** [comment]
Sources must be covered by tests and refactored.

**Comment by Fahasor** [comment]
I just re open my PR, i think commit history can be dirty and there is a lot to change in PR

**Pull request closed without merging**
