### PR TITLE
Rebalance the EOD Suit

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR
The hard bomb gibs you in a bomb suit, which makes it not that valuable for actually defusing bombs. This PR makes it so that as long as you aren't badly damaged and literally standing on the bomb, you won't gib.

## Why / Balance
Rebalances the bomb suit to slow you significantly, but offer good enough protection to leave your body in one piece if you fail to defuse a bomb. I also lowered the blunt damage of the hard bomb, cause otherwise the bomb suit would have to have even better stats to not gib, and I don't want to buff the helmet to discourage people from wearing it all of the time. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Rebalanced the bomb suit to slow you significantly, but offer greater protection against explosions.

### CODE REVIEW

**Comment by LinkUyx** [comment]
I don't think so.
It would have been better to leave piercing and slash at the same values.
Blunt is too big for this suit

**Comment by Partmedia** [comment]
Modifying the armor coefficients would make this too desirable for someone to nab at round start and make it unavailable for actually defusing a bomb (see the last PR that touched this). Because of the low bomb timer, I don't think a slowdown is appropriate, either. Overall I think it should *only* reduce explosion damage and still be fast. Otherwise this is not very useful for what this item was designed to do (stay in the EOD cabinet until there's a bomb threat).

**Comment by liltenhead** [comment]
I really don't see people wearing a suit that slows you down 50% the entire shift. I also think it makes sense that a bombsuit that is as bulky as it is would probably be somewhat resilient to damage.

**Comment by Partmedia** [comment]
> I really don't see people wearing a suit that slows you down 50% the entire shift. I also think it makes sense that a bombsuit that is as bulky as it is would probably be somewhat resilient to damage.

As I mentioned before, the problem with a slow suit is that the bomb timer is already short, and so people are going to have a hard time hustling back to security to pick up the suit, then hustle to wherever the bomb is.

**Comment by LankLTE** [comment]
> I really don't see people wearing a suit that slows you down 50% the entire shift. I also think it makes sense that a bombsuit that is as bulky as it is would probably be somewhat resilient to damage.

More importantly it makes it harder to get to the bomb with the suit

**Comment by Equivocateur** [comment]
> > I really don't see people wearing a suit that slows you down 50% the entire shift. I also think it makes sense that a bombsuit that is as bulky as it is would probably be somewhat resilient to damage.
> 
> More importantly it makes it harder to get to the bomb with the suit

Hold it in hand

**Comment by forgotmyotheraccount** [comment]
Is this a problem with the EOD suit or a problem with the bombs?

**Comment by liltenhead** [comment]
> Is this a problem with the EOD suit or a problem with the bombs?

I figured it'd make sense that the EOD suit could survive any bomb, so buffing it to be able to do so would leave bombs to be threatening and require getting the right equipment to deal with it.

**Comment by LankLTE** [comment]
> I figured it'd make sense that the EOD suit could survive any bomb, so buffing it to be able to do so would leave bombs to be threatening and require getting the right equipment to deal with it.

You only buffed the EOD suit by 5%, so if a difference that minor works you could probably tone down the syndicate bomb while still having it be threatening

**Comment by liltenhead** [comment]
Alright if I get a chance, I can look into the bomb more.

**Pull request closed without merging**
