### PR TITLE
fix windup attack using NextAttack

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
on kettle maintscalibur has like 30m nextattack to prevent using light attack
unfortunately this made it not usable at all since, against the documentation, heavy attack checked NextAttack
so this pr removes the check for heavy

tested works and doesn't fuck up cooldown after light swing or heavy -> light
maintscalibur now works as intended
also fixes chosen weapon of the tider

**Media**
- [X] bottom text

**Changelog**
:cl:
- fix: Maintscalibur and chosen weapons of the tider now actually work. Greytide worldwide!

### CODE REVIEW

**Comment by deltanedas** [comment]
no i tested on kettle it now works as intended, you can only heavy swing (i presume unless you wait out 30 mins or whatever then itll work like normal claymore)

**Comment by Elijahrane** [comment]
So it's intended behavior that you can't light attack with it except after 30 minutes?

**Comment by deltanedas** [comment]
i dont think the ~30 mins is intended, more of just an unreasonable amount of time so that you dont try to use it
weapon of the tider also has a random long number for it

**Comment by Elijahrane** [comment]
> i dont think the ~30 mins is intended, more of just an unreasonable amount of time so that you dont try to use it 

It's a map saving artifact though, see https://github.com/space-wizards/space-station-14/issues/13008

It's not intended behavior at all

**Comment by deltanedas** [comment]
oh :skull:

**Comment by EmoGarbage404** [comment]
Could the issue with the attack delays be due to WindUpStart on meleeweaponcomponent not having a time offset serializer?

**Comment by deltanedas** [comment]
it seems like it shouldnt be serialized in the first place

**Pull request closed without merging**
