### PR TITLE
L6 Fits in the Suit Storage Slot

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Lets the l6 fit in the suit storage slot
## Why / Balance

CONSISTENCY!!! :) 
## Technical details

Do it like how other guns do it
## Media

image

Screenshot 2024-09-22 152344

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: L6 Saw now fits in the suit slot
- tweak: L6 Saw is now a 5x4 item

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
pretty sure this is for balancing

**Comment by Cojoke-dot** [comment]
> pretty sure this is for balancing

Meh, other huge items and most guns can be stored in the slot. My mind went to the mini jet pack for a size comparison if other stuff that size could fit in the slot. An extra couple bag slots could be good sure, but nukies are the main user of the weapon and they already have the space for everything they need. Maybe it if you have something huge on your back, it blocks your bag from opening :trollface:

**Comment by ps3moira** [comment]
Seems intentional if it's a massive machine gun tbf

**Review by UbaserB — APPROVED** [review]

**Comment by UbaserB** [comment]
Thanks for your contribution.

**Pull request merged**
