### PR TITLE
Glasses/Hud Art Dump with Minor Changes To Beer Goggles

### PR DESCRIPTION
**Pull request by DerbyX**
## About the PR

Adds in a bunch of artwork for @PrPleGoo to use in their upcoming PR.
Also changes the wearing texture for beer glasses to resemble it better. (It was previously the sunglasses texture)
(**Subnote**: Moved all "glasses" to be effected with a hud element over to hud instead of glasses)

**Media**

Bundle of the new art assets:
ComboHudsBundle
Old and New Beer Goggles:
BeergogglesOld
BeergogglesNew

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

N/A

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
do we even want huds that just let you see everything? it seems really overpowered.

**Comment by DerbyX** [comment]
It's mainly a sort of end-game tier item. Not meant to be gotten immediately. Likely to be made with science or the likes

**Comment by EmoGarbage404** [comment]
i'm not a huge fan conceptually of "it's all the previous things combined", but that decision is up to a maintainer.

**Comment by DerbyX** [comment]
I see your point. Though having a doctor know that the patient is starving or a brigmedic able to look at both medical status and security status is definitely a good thing.

**Comment by PrPleGoo** [comment]
I agree the panopticon might be a bit too strong. But it can't hurt to just put it in and leave it as a badmin item.

**Comment by DerbyX** [comment]
@Emisse Merge Pls  👉👈

**Pull request merged**
