### PR TITLE
Glass box fixes + Construction & Stealthy deconstruction

### PR DESCRIPTION
**Pull request by MilenVolf**
## About the PR
- Fix not being able to close opened glass boxes prototypes.
- Fix glass box damage overlay textures.
- Fix glass box's fixture. Now only lasers can shoot through it.
- Add glass box frame. You can climb on it, just like on table.
- Add alarm sound on glass box destruction.
- Add glass box's construction graph. Now can be constructed and deconstructed. Glass Box Deconstruction takes 20 seconds.
- Broken glass box now can be repaired.
- Glass box now can be repaired with welder.
- Glass box now has locked and unlocked sprite states.

Still, there's a lot of work to do. Damage visuals fix required.
I put some TODOs for further fixes and upates.
Could be better if we had alarm system or smth, but it's okay for now.

Also it fixes modular grenade with voice trigger being able to be put in vim chassis.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Content Client_WwQ5A11mwW

https://github.com/space-wizards/space-station-14/assets/63782763/82030b96-3cbc-4e6c-8e25-fb0e425a338b

**Changelog**

:cl:
- add: Glass Box now can be constructed and deconstructed!
- tweak: Glass Box now makes an alarm sound on destruction.
- fix:  Now Antique Laser can be put back in the Glass Box.

### CODE REVIEW

**Comment by Kadeo64** [comment]
I don't think stealthy deconstruction is a good idea if it uses the default tools, stealthy deconstruction should require unique tools provided by the syndicate on roundstart if you have the steal laser objective like how 13 does it.

**Comment by metalgearsloth** [comment]
@MilenVolf what'd you change with warning_buzzer.ogg

**Comment by MilenVolf** [comment]
> @MilenVolf what'd you change with warning_buzzer.ogg

Removed the hum in the background.

**Comment by MilenVolf** [comment]
If needed I'll revert the change and will make it in another pr

**Comment by metalgearsloth** [comment]
> If needed I'll revert the change and will make it in another pr

There was no comment on it so not sure what happened there.

**Pull request merged**
