### PR TITLE
Changes the large beaker size to 10.

### LINKED ISSUE #11109: Large beaker should have more size
Right now it's the default item size of 5. It should be at least 10 or 15 (probably 15).

### PR DESCRIPTION
**Pull request by NoobyLegion**
Fixes  #11109

**Changelog**

:cl: NoobyLegion
- changes: sets large beaker size to 10

### CODE REVIEW

**Comment by Visne** [comment]
I've edited the description of your issue to include "Fixes  #11109". That way if this PR is merged, that issue will automatically be closed.

**Comment by 0x6273** [comment]
This breaks beaker boxes since they now don't have the capacity to hold 3 small + 3 large beakers. We really need a test for this...

**Comment by mirrorcult** [comment]
we actually do have a test for that, however
image
uhhhhh

**Comment by Visne** [comment]
How is adding a single YAML value causing the tests to run infinitely

**Comment by mirrorcult** [comment]
https://discord.com/channels/310555209753690112/900426319433728030/1018900580984430633 this maybe

**Comment by Visne** [comment]
Seems like just one of the tests on my PR (#11145) is also stuck, but the others passed

**Review by vulppine — CHANGES_REQUESTED** [review]
You need to fix the existing boxes of beakers by changing their contents, so that the space inside a beaker box is used correctly.

**Comment by NoobyLegion** [comment]
removed 1 beaker, so it fits now

**Review by vulppine — APPROVED** [review]
works for me - a discussion could be made on if there should be 1 large beaker and 4 small beakers for organizational purposes, but i think 2 and 2 is fine enough for round-start/discovered boxes

**Pull request merged**
