### PR TITLE
E to interact with disposal bins.

### PR DESCRIPTION
**Pull request by sentient-ai**
Opens the disposal bin UI without dropping the item in there. This time without past PR baggage.

### CODE REVIEW

**Review by ShadowCommander — CHANGES_REQUESTED** [review]
You should probably make a new method that returns a bool and then call that from both InteractHand and IActivate. That way if there are more checks needed later it only needs to be changed in one place.

**Comment by sentient-ai** [comment]
Thanks for the feedback, don't quite know good practices.

**Comment by ShadowCommander** [comment]
Well you're doing good. Finding things that are easy to fix and are good quality of life fixes. Good practices comes from reading stuff and just having experience with fixing things, so you know how do write stuff the first time.

**Comment by sentient-ai** [comment]
I feel like a "check if have arms, isn't in a locker, isn't knocked out, etc." needs to be higher up in the class hierarchy to pull from, but I'm not sure how that'd be done. Apparently you can interact with pretty much all computers, vending machines, etc while inside a locker, and I'm assuming the same's true for not having hands, though I'm not sure how to remove them in the game as of now to check.

**Comment by ShadowCommander** [comment]
Use the early exit pattern where if the check fails then return false. Like how the other if statements are.


For the interaction checks that can probably be moved up to the InteractionSystem, but that's outside the scope of this PR.

**Comment by sentient-ai** [comment]
For iActivate? The function has potential voids in it so doing that makes the build unhappy. Not sure how to work around that.

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
