### PR TITLE
add cpr (needs help)

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Ports CPR from DeltaV's repository.
There's a lot taken off because this system required a lot of changes, but currently it does work.

I don't really have the skill level to do this all myself, but I made the effort to get the code more visible to contributors hopefully!
Feel free to take the branch/code/whatever to work on it.

Bugs: 

- cpr needs a sound, I didnt pull the one from deltav
- unbuckles people then starts cpr
- mobs that can be picked up cause weird visuals when you preform cpr on them
- probably many more interaction bugs, emo says the code isn't predicted.
- CPRDoAfterEvent is a DataDefinition but is not partial

## Why / Balance

Airloss based medicines are the only way to recover airloss in patients. CPR allows doctors to revive otherwise healthy patients if no airloss medicine is available.

CPR should do brute damage each time it is performed. The medical training skill was cut out.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
cpr imo should only hear airloss on crit patients (if you havent added that already)

**Comment by Peptide90** [comment]
> cpr imo should only hear airloss on crit patients (if you havent added that already)

And have a limit to what it heals i.e only bringing them to an out of crit / stable place where they either breathe on their own, or deteriorate again due to an underlying issue.

**Comment by metalgearsloth** [comment]
For this sort of stuff you should use their commits instead of copying it across I think.

**Comment by QuietlyWhisper** [comment]
> For this sort of stuff you should use their commits instead of copying it across I think.

it's not entirely copied, I cleaned out a lot of the original pr... but uh.. I'll try to figure out how to do that next time

**Comment by DebugOk** [comment]
> I dont think you should be able to perform CPR on beings that you can pick up, like mice

You crush them anyways. It has a very high chance of failing

**Comment by mirrorcult** [comment]
the image of a spaceman desperately  giving CPR to a mouse is funny enough that i 100% want to allow it

**Comment by JoeHammad1844** [comment]
> the image of a spaceman desperately giving CPR to a mouse is funny enough that i 100% want to allow it

ok, true

**Comment by QuietlyWhisper** [comment]
This is likely not going anywhere anytime soon but at least the code is here for later

**Pull request closed without merging**
