### PR TITLE
Increase the time it takes to strip something off of someone

### PR DESCRIPTION
**Pull request by HoofedEar**
## About the PR 

Increases the time it takes to strip things off of someone from 2 seconds to 6 seconds.

**Screenshots**

**Changelog**

:cl:
- tweak: Requires a little more effort strip something off of someone.

### CODE REVIEW

**Comment by BlitzGunner225** [comment]
I feel like tripling it is a bit too far 
Maybe just 3 as we just need a bit more time so that most people won’t loose their pdas unless they aren’t paying attention at all

**Comment by Snowyypanda** [comment]
so now you either gotta cuff someone after disabling them and hope to god they don't scream over mic or straight up kill them for their loot

**Comment by Fishfish458** [comment]
This should be position dependent, quicker to add or remove things from peoples hands, a lot longer to take their entire jumpsuit off.

**Comment by HoofedEar** [comment]
> I feel like tripling it is a bit too far Maybe just 3 as we just need a bit more time so that most people won’t loose their pdas unless they aren’t really paying attention

In my testing 3 was too quick as well

> ... loot

Yeah.


> This should be position dependent, quicker to add or remove things from peoples hands, a lot longer to take their entire jumpsuit off.

Big agree tbh

**Comment by youarereadingthis** [comment]
The biggest problem with stealing is PDAs in my opinion.
If the PDA took longer to steal, and if pockets were easier to steal from that sounds great to me.
Also, if it weren't for heavy stuns all over the place this wouldn't be such an issue.

**Comment by mirrorcult** [comment]
im fine with this as a stopgap before making it position dependent. its pretty fast right now

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
