### PR TITLE
New sound emotes for Reptilians and humanoids

### PR DESCRIPTION
**Pull request by SabatonShip**
## About the PR

Added the following sound emotes for Reptilians:

- hisses
- purres
- growls
- whines
- whips tail
- screams
- sneezes
- snorts

Added the following sound emotes for humanoids:

- sniffs
- cracks knuckles

Enabled triggers for sneeze

Increased radius for the Vocal category in the emote wheel to fix the issue of buttons overlapping each other.

Added sniff icon.
## Why / Balance

These changes were made to enhance the role-playing experience and provide more interaction options for players. By adding specific sound emotes for Unathi and general emotes for all humanoids, players can express their character's actions and emotions more vividly. This helps in creating a more immersive environment and can make interactions between players more dynamic and interesting. And I like Reptilians alot.
## Technical details

The new sound emotes were added to the emote system, allowing players to trigger them.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/87234822/743ac7c0-84e4-465c-823e-0e74bf923d86

## Breaking changes

Icons for the new emotions are missing. The most suitable icons from the available ones have been selected.

**Changelog**

:cl:
- add: Added sound emotes for Reptilians: hisses, purrs, growls, whines, whips tail, screams, sneezes, snorts.
- add: Added sound emotes for all humanoids: sniffs, cracks knuckles.
- tweak: The sneezing sound has been enabled.

### CODE REVIEW

**Comment by deepdarkdepths** [comment]
"Purres" should be "purrs".
Besides that, I hope these get in so lizards can also have a wide range of sounds to finally choose from.

**Comment by SabatonShip** [comment]
> "Purres" should be "purrs".
Besides that, I hope these get in so lizards can also have a wide range of sounds to finally choose from.

You are right! I'm glad this grammar error isn't in the files; I was writing the words hastily in the pull request body, because English isn't my main language, hehe! So yeah, please check if the trigger words match the sounds in meaning!

And yes, I hope so too. I spent a lot of time on this...

**Comment by deepdarkdepths** [comment]
> > "Purres" should be "purrs".
> > Besides that, I hope these get in so lizards can also have a wide range of sounds to finally choose from.
> 
> You are right! I'm glad this grammar error isn't in the files; I was writing the words hastily in the pull request body, because English isn't my main language, hehe! So yeah, please check if the trigger words match the sounds in meaning!
> 
> And yes, I hope so too. I spent a lot of time on this...

An instance of "purres" is in your emotes.ftl file.

**Comment by SabatonShip** [comment]
> > > "Purres" should be "purrs".
> > > Besides that, I hope these get in so lizards can also have a wide range of sounds to finally choose from.
> > 
> > 
> > You are right! I'm glad this grammar error isn't in the files; I was writing the words hastily in the pull request body, because English isn't my main language, hehe! So yeah, please check if the trigger words match the sounds in meaning!
> > And yes, I hope so too. I spent a lot of time on this...
> 
> An instance of "purres" is in your emotes.ftl file.

Bad. Wait a minute...

**Comment by Thurtik** [comment]
Can we keep the original scream sound? It was kinda iconic. The rest are fine, not quite _silly_ enough for my taste, but that's probably just me

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
The reptilian emotes all need proper icons

**Comment by regenpower** [comment]
i agree with Thurtik, the current scream is beautiful and imo should stay
(i made a github account just to say this)
i also agree with the silly part, my first thought was that the funny spess lizors are all silly goobers and probably don't make predator sounds, but that is just personal opinion aswell

**Comment by Golinth** [comment]
These sound way way too deep for the funny lil spess lizards that we have IMO. They’d make great mob noises tho

**Comment by ps3moira** [comment]
These don't sound like lizard sounds and more like dragon sounds. Only one that sounded fine was the cracked knuckles emote

**Comment by Hmeister-real** [comment]
maybe pitch the Lizard sounds higher. I like them, but there are a lot of silly lizzos who would NOT sound like that. But at the same time, it sounds good for more tough lizzos, could be a toggle or smthn.

**Comment by vorkathbruh** [comment]
im all for new noises but do not touch reptilian_scream.ogg please

**Comment by foob1** [comment]
These emote audios sound like they come from a giant dragon rather than a human sized humanoid reptilian. Maybe it would be better to use these sounds for a space dragon?

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> These emote audios sound like they come from a giant dragon rather than a human sized humanoid reptilian. Maybe it would be better to use these sounds for a space dragon?

I would have to agree, these sounds sound like they would be coming from a larger lizard than a humanoid one, these would fit the space dragon well tho

**Comment by Usha-Ai** [comment]
As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.

**Comment by Usha-Ai** [comment]
Also, for the sake of understanding, some of the sounds that were recorded were taken from tigers and crocodiles, since lizards are not much smaller than them and are almost in their weight category and, accordingly, will sound the same.

**Comment by foob1** [comment]
> As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.

I don't know what fork or game you've been playing but they're the same size as humans

Content Client_AaLMLcquol

**Comment by Usha-Ai** [comment]
> > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> 
> I don't know what fork or game you've been playing but they're the same size and height as humans
> 
> Content Client_AaLMLcquol

I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.

**Comment by LankLTE** [comment]
> I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.

And I think these sounds would fit better for something like a space dragon- but the face of the matter is these sounds are added to the reptilian species which are the same size as humans.

**Comment by foob1** [comment]
> > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > 
> > 
> > I don't know what fork or game you've been playing but they're the same size and height as humans
> > Content Client_AaLMLcquol
> 
> I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.

Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts

**Comment by Usha-Ai** [comment]
> > > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > > 
> > > 
> > > I don't know what fork or game you've been playing but they're the same size and height as humans
> > > Content Client_AaLMLcquol
> > 
> > 
> > I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.
> 
> Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts

Why do you perceive them as huge and scary lizards? No one can force you to use that "threatening growl." Again, an example from life is dogs, they also growl, but this does not prevent us from perceiving them as cute animals. And one more thing... don't you have lizard lore?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
We explicitly don't have lore. I can give a better list later and offer suggestions from other servers but the snarls and growls do not fit for lizards.

**Comment by Usha-Ai** [comment]
I have no right to force you to do this, but here is a link to our community, where people sat and wrote the lore of lizards, I advise you to read it, at least in translation, to understand the difference in our thinking. And I will be very glad if you tell me what you have that’s similar! 
https://station14.ru/wiki/%D0%A3%D0%BD%D0%B0%D1%82%D1%85%D0%B8

**Comment by foob1** [comment]
> > > > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > > > 
> > > > 
> > > > I don't know what fork or game you've been playing but they're the same size and height as humans
> > > > Content Client_AaLMLcquol
> > > 
> > > 
> > > I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.
> > 
> > 
> > Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts
> 
> Why do you perceive them as huge and scary lizards? No one can force you to use that "threatening growl." Again, an example from life is dogs, they also growl, but this does not prevent us from perceiving them as cute animals. And one more thing... don't you have lizard lore?

Yes I have lore for my reptilian character and I don't think it makes sense for them to sound like a dragon, same thing with a majority of SS14 reptilian characters that I've seen. I suggest making these sounds a higher pitch as the sounds don't make sense for the average SS14 reptilian character.

**Comment by foob1** [comment]
> I have no right to force you to do this, but here is a link to our community, where people sat and wrote the lore of lizards, I advise you to read it, at least in translation, to understand the difference in our thinking. And I will be very glad if you tell me what you have that’s similar! https://station14.ru/wiki/%D0%A3%D0%BD%D0%B0%D1%82%D1%85%D0%B8

You realize you can PR this for your fork if you have specific reptilian lore for that fork right?

**Comment by Usha-Ai** [comment]
> > > > > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > > > > 
> > > > > 
> > > > > I don't know what fork or game you've been playing but they're the same size and height as humans
> > > > > Content Client_AaLMLcquol
> > > > 
> > > > 
> > > > I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.
> > > 
> > > 
> > > Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts
> > 
> > 
> > Why do you perceive them as huge and scary lizards? No one can force you to use that "threatening growl." Again, an example from life is dogs, they also growl, but this does not prevent us from perceiving them as cute animals. And one more thing... don't you have lizard lore?
> 
> Yes I have lore for my reptilian character and I don't think it makes sense for them to sound like a dragon, same thing with a majority of SS14 reptilian characters that I've seen. I suggest making these sounds a higher pitch as the sounds don't make sense for the average SS14 reptilian character.

I'm not talking about the history of your character, but about the background of the race itself, their religion, principles and general knowledge base that was laid down by the developers, and not by the player

**Comment by foob1** [comment]
> > > > > > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > > > > > 
> > > > > > 
> > > > > > I don't know what fork or game you've been playing but they're the same size and height as humans
> > > > > > Content Client_AaLMLcquol
> > > > > 
> > > > > 
> > > > > I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.
> > > > 
> > > > 
> > > > Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts
> > > 
> > > 
> > > Why do you perceive them as huge and scary lizards? No one can force you to use that "threatening growl." Again, an example from life is dogs, they also growl, but this does not prevent us from perceiving them as cute animals. And one more thing... don't you have lizard lore?
> > 
> > 
> > Yes I have lore for my reptilian character and I don't think it makes sense for them to sound like a dragon, same thing with a majority of SS14 reptilian characters that I've seen. I suggest making these sounds a higher pitch as the sounds don't make sense for the average SS14 reptilian character.
> 
> I'm not talking about the history of your character, but about the background of the race itself, their religion, principles and general knowledge base that was laid down by the developers, and not by the player

There... isn't any lore laid down by the devs and they just stated that. Are you on the right repository?

**Comment by Usha-Ai** [comment]
> > > > > > > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > > > > > > 
> > > > > > > 
> > > > > > > I don't know what fork or game you've been playing but they're the same size and height as humans
> > > > > > > Content Client_AaLMLcquol
> > > > > > 
> > > > > > 
> > > > > > I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.
> > > > > 
> > > > > 
> > > > > Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts
> > > > 
> > > > 
> > > > Why do you perceive them as huge and scary lizards? No one can force you to use that "threatening growl." Again, an example from life is dogs, they also growl, but this does not prevent us from perceiving them as cute animals. And one more thing... don't you have lizard lore?
> > > 
> > > 
> > > Yes I have lore for my reptilian character and I don't think it makes sense for them to sound like a dragon, same thing with a majority of SS14 reptilian characters that I've seen. I suggest making these sounds a higher pitch as the sounds don't make sense for the average SS14 reptilian character.
> > 
> > 
> > I'm not talking about the history of your character, but about the background of the race itself, their religion, principles and general knowledge base that was laid down by the developers, and not by the player
> 
> There... isn't any lore laid down by the devs and they just stated that. Are you on the right repository?



> > > > > > > > As a co-author of these sounds, I dare say: they were deliberately made more rough and with the bass turned up. They are not people, they are almost a meter taller and have a different body structure. Compare with crocodiles or alligators for greater identity.
> > > > > > > 
> > > > > > > 
> > > > > > > I don't know what fork or game you've been playing but they're the same size and height as humans
> > > > > > > Content Client_AaLMLcquol
> > > > > > 
> > > > > > 
> > > > > > I don’t argue with the fact that they have a similar texture, but there is lore and simple logic! I don’t mean it at all, you have the right to think as you want, but here’s a living example for you - a space dragon, its texture is also not much larger than a person’s.
> > > > > 
> > > > > 
> > > > > Lore? This isn't paradise station with unathi and I'm pretty sure most people don't RP their reptilian characters being huge monstrous beasts
> > > > 
> > > > 
> > > > Why do you perceive them as huge and scary lizards? No one can force you to use that "threatening growl." Again, an example from life is dogs, they also growl, but this does not prevent us from perceiving them as cute animals. And one more thing... don't you have lizard lore?
> > > 
> > > 
> > > Yes I have lore for my reptilian character and I don't think it makes sense for them to sound like a dragon, same thing with a majority of SS14 reptilian characters that I've seen. I suggest making these sounds a higher pitch as the sounds don't make sense for the average SS14 reptilian character.
> > 
> > 
> > I'm not talking about the history of your character, but about the background of the race itself, their religion, principles and general knowledge base that was laid down by the developers, and not by the player
> 
> There... isn't any reptilian lore laid down by the devs and they just stated that. Are you on the right repository?

ahem.. I sincerely thought that you had a history of the race.. In any case, even based on biology, they look and are a more animal race, albeit intelligent and close to human. And based on the already recorded sounds and the structure of the head, it is quite expected to hear a growl from them, although yes, I agree here, not so low.

**Comment by Usha-Ai** [comment]
and I also suggest not looking solely at the growl, evaluate other sounds, for example, rumbling! I think it sounds more than appropriate and fits both the ear and the character very nicely.

**Comment by Usha-Ai** [comment]
To be honest, I initially suggested to my comrad to introduce these sounds into the game just for the sake of rumbling and hissing.

**Comment by foob1** [comment]
> ahem.. I sincerely thought that you had a history of the race.. In any case, even based on biology, they look and are a more animal race, albeit intelligent and close to human. And based on the already recorded sounds and the structure of the head, it is quite expected to hear a growl from them, although yes, I agree here, not so low.

SS14 upstream does not have set lore for things such as the reptilian species, but their size is the same as that of humans and that's intentional, and therefore it wouldn't really make sense to have such low pitch sounds if reptilians are this size. If the maintainers intended for reptilians to be larger, they would have probably made them look larger (for example dwarfs are supposed to be small and therefore they look small).

The problem is mainly with how low pitch the sounds are which doesn't make sense for how reptilians actually are upstream, and I suggest raising the pitch and changing some sounds for it to make sense. I think the idea of adding sounds is a great idea, but I don't really see the pitch of the sounds fitting with how reptilians actually are ingame. If your community that you showed us previously has set lore on reptilians though, I suggest you make a PR for that fork.

**Comment by Usha-Ai** [comment]
> > ahem.. I sincerely thought that you had a history of the race.. In any case, even based on biology, they look and are a more animal race, albeit intelligent and close to human. And based on the already recorded sounds and the structure of the head, it is quite expected to hear a growl from them, although yes, I agree here, not so low.
> 
> SS14 upstream does not have set lore for things such as the reptilian species, but their size is the same as that of humans and that's intentional, and therefore it wouldn't really make sense to have such low pitch sounds if reptilians are this size. If the maintainers intended for reptilians to be larger, they would have probably made them look larger (for example dwarfs are supposed to be small and therefore they look small).
> 
> The problem is mainly with how low pitch the sounds are which doesn't make sense for how reptilians actually are upstream, and I suggest raising the pitch and changing some sounds for it to make sense. I think the idea of adding sounds is a great idea, but I don't really see the pitch of the sounds fitting with how reptilians actually are ingame. If your community that you showed us previously has set lore on reptilians though, I suggest you make a PR for that fork with the current sounds.

It would be great if you pointed out specific sounds that you are not satisfied with, except for the growl, I’m already working on it.

**Comment by foob1** [comment]
> It would be great if you pointed out specific sounds that you are not satisfied with, except for the growl, I’m already working on it.


Maintainers know best (_usually_), metalgearsloth already pointed some things out


> We explicitly don't have lore. I can give a better list later and offer suggestions from other servers but the snarls and growls do not fit for lizards.

**Comment by foob1** [comment]
> It would be great if you pointed out specific sounds that you are not satisfied with, except for the growl, I’m already working on it.

Though I personally think the hissing, sniffing, and tail whipping for the reptilians are good. The other audios for reptilians could use sound changes and/or a higher pitch.

**Comment by deepdarkdepths** [comment]
Maybe there could be female and male reptilian sounds? If we already have separate screams, coughs, and sighs for male and female humans then there shouldn't be an issue.

**Comment by foob1** [comment]
> Maybe there could be female and male reptilian sounds? If we already have separate screams, coughs, and sighs for male and female humanoids then there shouldn't be an issue.
> 
> Some of the sounds could still be pitched up in general but it would be nice to have some variation. 

That would be super cool. Maybe the female sounds could be a higher pitch than the male sounds?

**Comment by Dutch-VanDerLinde** [comment]
make the old scream the female scream and the new one the male scream ez

**Comment by SabatonShip** [comment]
Greetings everyone,

I appreciate all of your feedback regarding this topic. It's valuable to me, and I'm ready to make adjustments based on your comments!

Regarding the scream, I agree with you that the current "silly" scream has become quite iconic. I personally like it too. I didn't intend to remove it; rather, I aimed to create an alternative that could instill more fear, as I felt the current scream, while suitable for younger reptilians, might sound too cute or unfitting in RP situations. Based on your feedback, here are several options, starting with the most likely:

- Remove the second added scream.
- Increase its pitch and keep it as an separate emotion. ("terrifying scream")
- Make it a separate emotion and add it only for the male.

Regarding the growls, I also understand your concerns about them. I'll remove 2 of 3 growls, and with the rest I'll try increasing the pitch, and will remove it if it still don't meet expectations.

As for the purr, whine, snort sounds, if you don't have specific feedback on them, I believe they sound good and can remain unchanged!.. I guess..

The idea of having different sounds for different genders is good, of course I'm aware of it, but _needed_ the right sounds. So that, if you have any suitable sounds, additional feedback, you can help! Also, if you can draw icons... Until then, I'll probably transfer the pool request to the draft

Again thank you all!

**Comment by SabatonShip** [comment]
> We explicitly don't have lore. I can give a better list later and offer suggestions from other servers but the snarls and growls do not fit for lizards.

Yes, please!

**Comment by SabatonShip** [comment]
maybe later, in another century...

**Comment by superjj18** [comment]
Yeah a lot of these are way too serious and intimidating for the default lizard boys.  The game is about goofy spacemen not a gritty dnd rpg with Dragonborn characters running around.

HOWEVER, I would absolutely love for these emotes to get put on the space dragon instead

**Pull request closed without merging**
