### PR TITLE
Non-destructive XenoArch Research

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Ultimately, destroying artifacts in order to get points from them hasn't been majorly beneficial for science. Due to the sheer overwhelming value of points, especially with the relatively low number of artifacts per round, players are incentivized to simply get through the graph as quick as possible rather than engaging with any of the effects in a meaningful way. 

By changing the point process to be nondestructive, players can enter a state of post-point-clarity where they can actually do interesting and fun things with the artifacts that they've spent time researching.

**Media**

https://user-images.githubusercontent.com/98561806/231911325-2bc862e7-5ad4-4656-aa15-e37636875e30.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The research team in the XenoArcheology lab have discovered how to extract points from artifacts without breaking them.

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]
id rather the button be called 'extract' or something 'points' is really stupid. but concept good willing to try as ive said before

**Comment by EmoGarbage404** [comment]
renamed "Points" to "Extract"

**Comment by deltanedas** [comment]
since extract isnt dangerous why is the button still red

**Comment by crazybrain23** [comment]
Do you still get the same amount of points if you extract after each node, compared to only extracting at the end?

**Comment by EmoGarbage404** [comment]
> Do you still get the same amount of points if you extract after each node, compared to only extracting at the end?

yes, it's the same amount

**Pull request merged**
