### PR TITLE
Add remove tiles rod to immovable rod event

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Immovable rod that can remove tiles will spawn with a probability of 1 in 3333 during the immovable rod event

## Why / Balance

one in thousands rounds its epic to see that kind of chaos on a station

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl but a lot fun

### CODE REVIEW

**Comment by LankLTE** [comment]
Maybe hot take but I don’t think random 1 in a bajillion chances to just instantly end the round are fun or necessary

**Comment by Brandon-Huu** [comment]
I prefer the 20% chance of singulo

> Maybe hot take but I don’t think random 1 in a bajillion chances to just instantly end the round are fun or necessary

Being an engineer in this situation would be fun.

**Comment by K-Dynamic** [comment]
> one in thousands rounds its epic to see that kind of chaos on a station

I feel it's better to lock this behind admin (especially if there's already a meme going on)

**Comment by lzk228** [comment]
> Maybe hot take but I don’t think random 1 in a bajillion chances to just instantly end the round are fun or necessary

its game about chaos, so more types of chaos is better, i suppose

**Comment by metalgearsloth** [comment]
That orGroup is nasty and I don't think this is fun either.

**Comment by Simyon264** [comment]
I think this would be a really cool adition. Especially because of the "Chaotic" [Core Pillar](https://docs.spacestation14.com/en/space-station-14/core-design.html#core-pillars) .

> No two rounds should play alike. The combination of antagonists, incompetence, and disasters should create situations where players have to deal with rapidly changing and escalating situations.

**Comment by Brandon-Huu** [comment]
the 1 in 1 million round being hit with a tile destroying rod was too much for SS14

**Pull request closed without merging**
