### PR TITLE
Make medical beds uncraftable

### LINKED ISSUE #17946: Medical beds being craftable is stupid
it effectively lets you bypass healing as a game mechanic make them uncraftable, maybe also nerf them

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Made medical beds uncraftable.

## Why / Balance
Resolves #17946.

## Technical details
Removed ``MedicalBed`` prototype from the ``furniture.yml`` (I also accidentally removed whitespaces, but I guess it's fine).

## Media

изображение

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: The medical bed was removed from the construction menu.

### CODE REVIEW

**Comment by Aisu9** [comment]
or... what about making the crafting only available for medical staff? spiderfolks have unique options why not making unique job crafting options?

**Comment by Winkarst-cpu** [comment]
> or... what about making the crafting only available for medical staff? spiderfolks have unique options why not making unique job crafting options?

For me, the overall concept of a simple bed giving you passive healing is a little dumb. It will be better if medical beds were remade into something like a cryogenic sleep unit, but medical (as I remember, it's something like that in SS13).

**Comment by UncaughtEx** [comment]
Can't wait to intentionally dismantle medical beds as antags

**Comment by JIPDawg** [comment]
I also think it's important to note that since that issue was created med beds were already nerfed once in #18222 I personally rarely see people craft med beds. If anything make it behave similarly to Tric. Damage above X amount will not heal.

**Comment by Winkarst-cpu** [comment]
> I also think it's important to note that since that issue was created med beds were already nerfed once in #18222 I personally rarely see people craft med beds. If anything make it behave similarly to Tric. Damage above X amount will not heal.

Then maintainers will decide...

**Comment by themias** [comment]
If this gets merged, it might be worth adding some way for cargo to order more beds.
They're very easy to build currently, but I think there should be a way to rebuild med if (when) need be.

**Comment by Ilya246** [comment]
i'm pretty sure that issue is from a long time ago where they used to heal much more than they do now, so current beds are probably fine

**Comment by JIPDawg** [comment]
> i'm pretty sure that issue is from a long time ago where they used to heal much more than they do now, so current beds are probably fine

Yes, I posted the pr that nerfed med beds. Before they healed all brute and burn damage which was incredibly strong. Now it's just poison, blunt and cold. At a rate of .2. I think it's balanced now.

**Comment by Cadunkus** [comment]
Medical beds require durathread which isn't free and the healing you get from them is too slow to put other healing methods out of a job, they're used in conjunction with them for a little bonus, plus from a thematic standpoint it makes sense that resting = recovery.

How exactly is this OP anyway? Pretty much the only people who use medical beds are medbay and rarely salvagers (please don't discourage salvagers from making their ship liveable instead of a filthy depressurized tin can). Nukies aren't stopping in the middle of a mission to order durathread from cargo and have a little nap nap, security aren't hoarding medical beds to beat revs in a war of attrition, engineering go to medbay if they stand around the singulo for too long. If people crafting medical beds in bulk made standard healing mechanics irrelevant then it'd be worth a PR but this is a non-existent issue.

**Comment by slarticodefast** [comment]
You will also need to remove it from the constructionGraph.
I will bring it up for maintainer discussion.

**Comment by slarticodefast** [comment]
You only removed the medicalbed node, but not the edges leading to that node, causing the tests to fail.

**Comment by Cojoke-dot** [comment]
It's poison, blunt, and cold... just double what the normal bed gives you. I could see maybe reducing the blunt healing but the cold and poison makes sense to me(blanket and rest to heal sickness). I don't see why they need to be removed from crafting and quite frankly I don't wana read 500 GitHub comments on the issue and this post so uh... o7.

**Comment by thebadman4662** [comment]
> It's poison, blunt, and cold... just double what the normal bed gives you. 

Medical bed is only one to heal cold, otherwise yeah, just double healing.

**Comment by UncaughtEx** [comment]
Medical having all their beds removed by one guy and a screw driver because sec needed mats :godo:

**Comment by slarticodefast** [comment]
I brought this up for maintainer discussion and it was agreed to close this PR. The main points made were:
- The healing effect has already been nerfed.
- Objects should not be mapping only unless neccessary.
- Further balancing has to be made anyways when NewMed is included

**Comment by Winkarst-cpu** [comment]
> I brought this up for maintainer discussion and it was agreed to close this PR. The main points made were:
> 
>     * The healing effect has already been nerfed.
> 
>     * Objects should not be mapping only unless neccessary.
> 
>     * Further balancing has to be made anyways when NewMed is included

Okay.

**Pull request closed without merging**
