### PR TITLE
Magnetized Borg Locomotion

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I gave Borgs the action to toggle magboots

## Why / Balance

It is a QoL change, balanced due to the speed penalty from the magboots being applied

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Ilya246** [comment]
i think it's good since borgs have no way to use magboots otherwise and i think borgs should be useful in zerograv

**Comment by UbaserB** [comment]
Solves #21576

**Comment by K-Dynamic** [comment]
Mostly agree but a syndie borg with L6 or DE sword won't be gimped by low grav and can charge in as usual

**Comment by FungiFellow** [comment]
> Mostly agree but a syndie borg with L6 or DE sword won't be gimped by low grav and can charge in as usual

Syndie borgs have Space Mob Movement

> - type: MovementAlwaysTouching

**Comment by metalgearsloth** [comment]
is this supposed to be draft

**Pull request closed without merging**
