### PR TITLE
add more carp plushies

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
holocarp and magicarp getting their attention

## Why / Balance
:fish:

## Technical details
:fish:

## Media
:fish:

:fish:

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
:fish:

**Changelog**
:cl:
- add: Holocarp and Magicarp plushies can now be found in maintenance.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Fische update is real

**Comment by Slava0135** [comment]
fish race when

**Comment by Qsan163** [comment]
I think we need rainbow carp plushie also  .

**Comment by deltanedas** [comment]
when you make greyscale sprite :trollface:

**Comment by pigeonpeas** [comment]
> when you make greyscale sprite :trollface:

image

not sure why it has the black background, but it shouldn't be too hard for you to get rid of :3

**Pull request merged**
