### PR TITLE
make vent clog event only affect single station vents

### LINKED ISSUE #9229: Ventclog event affects the nukie shuttle
## Description
The event VentClog also causes foam to spew from the vents in the nuclear operative shuttle.

**Reproduction**
N/A

**Screenshots**

A ventclog event killed all the nukies this round before they made it to the station.
ventclognukie

**Additional context**
Not sure if other station events such as breakerflip or gas leak will also trigger on the nukie shuttle.

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

Closes #9229

**Media**

For demonstration purposes all vents are affected (commented part of the code)
Peek 2023-01-24 22-07

**Changelog**

:cl:
- tweak: vent clog event now only affects single station vents (no more foam in nukie ship)

### CODE REVIEW

**Comment by Slava0135** [comment]
May as well tweak APC events, but better approach would be creating new class for station local events. Because right now station events are announced globally even if it doesn't affect every grid (unless you override methods).

**Comment by AJCM-git** [comment]
I would rather this be a bool in `StationEventRuleConfiguration` that gets handled on `StationEventSystem` or something than special casing events like this

**Comment by Slava0135** [comment]
The reason why you would want to have a separate class for this is that you need to store chosen station somewhere (in field).

**Comment by moonheart08** [comment]
> I would rather this be a bool in `StationEventRuleConfiguration` that gets handled on `StationEventSystem` or something than special casing events like this

This is correct behavior already, I don't think it needs the bool.

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
