### PR TITLE
Add gasping sound

### LINKED ISSUE #18194: gasping should has a sound
-

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

title
resolves #18194
## Technical details

gasp popup was changed to emote
## Media

https://github.com/space-wizards/space-station-14/assets/124214523/4f189142-fcf6-4bee-b0c8-2548c61932f4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
time to be dead in med and ignored by the doctors, but with sound

**Comment by K-Dynamic** [comment]
> time to be dead in med and ignored by the doctors, but with sound

Fake your last breath, get ignored still

**Comment by UbaserB** [comment]
i want it to be more subtle, being as loud as it is and as abrupt is not very pleasant to my ears.

**Comment by Hmeister-fake** [comment]
it need a variaty of gasps, and different gasps for each species. Imagine a full medical full of the exact same gasping sound over and over and over, lmao

**Comment by mirrorcult** [comment]
i support this conceptually but this sound sucks + needs to be more subtle + needs variation or its going to feel terrible

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
what mirror said

**Comment by lzk228** [comment]
updated, but i couldnt find gasp sounds for xenos

https://github.com/space-wizards/space-station-14/assets/124214523/4f189142-fcf6-4bee-b0c8-2548c61932f4

**Comment by UbaserB** [comment]
Would it be possible to make the gasp softer?

**Comment by lzk228** [comment]
do you think people irl really gasps softly? :trollface:

**Comment by lzk228** [comment]
gonna fix linter later

**Comment by UbaserB** [comment]
> do you think people irl really gasps softly? :trollface:

well its much quieter at least, even after the change. Its like very faint, since not much air can pass through your throat.

**Comment by IProduceWidgets** [comment]
I like it. I think it will fit in better when there are more things that make noise in medical like beeping heart / o2 monitors and stuff.

**Comment by TheShuEd** [comment]
I also think the sounds are too harsh.  I would like to make them longer, and with longer wheezing.  Well, the tests are also broken.

**Comment by lzk228** [comment]
ok tests are fixed
i ported sounds from tg and paradise so if somebody has a better sounds please write here or in my discord `@lzk228`

**Comment by lzk228** [comment]
stale

**Comment by lzk228** [comment]
I decided to open pr again and ready for review

**Comment by lzk228** [comment]
the branch is cooked so ill open new pr

**Pull request closed without merging**
