### PR TITLE
Body code cleanup

### PR DESCRIPTION
**Pull request by 0x6273**
- Change events to be `record structs`s.
- Kill float accumulators and replace them with `TimeSpan`.
- Replace all other uses of floats for storing time with `TimeSpan`.
- Replace property fields on comps with regular fields.
- Add missing `[DataField]` to fields that should be saved.
- Use `EntitySystem` proxy methods where possible.
- Use `Entity<TComp>` in private methods. (I plan on updating public api methods in a future pr. For this pr I wanted to keep breakage to a minimum.)
- Replace prototype ID strings with `ProtoId<TProto>`.
- Minor style things to make code more readable, including by not limited to:
    - Combine if statements.
    - Fix wrong indentation/whitespace.
    - Split long lines into multiple lines.
- Change a test so that it actually simulates the game instead of manually ticking individual systems `Update` methods (this broke after killing float accumulators).

## Breaking changes
All events under `Content.*/Body` were changed from classes to `record struct`s. These need to be raised and subscribed to by ref instead of by value.
The organ added/removed events has had their names changed, see https://github.com/space-wizards/space-station-14/pull/24946/commits/8e6fdd888bcdd10b8485c9ed947d852db739f21c

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Conflict with https://github.com/space-wizards/space-station-14/pull/19383 ?

**Comment by 0x6273** [comment]
> Conflict with #19383 ?

There is some overlap, but it doesn't look too bad. I can make a pr to @Jezithyr's pr branch to fix the conflicts, after this is merged.

**Comment by 0x6273** [comment]
Would it make sense to move the update timers to a new `OrganTickerComponent` instead, and have the systems subscribe to an event instead of using `Update` method? I think this could get rid of a lot of code dupe.

**Comment by Jezithyr** [comment]
Why create a new component for organ ticking when we can just have the ticking logic on the organ comp?

**Comment by Jezithyr** [comment]
I can handle merging this into the new med code

**Comment by 0x6273** [comment]
> Why create a new component for organ ticking when we can just have the ticking data on the organ comp?

Because you could have organs that don't need to tick.

**Comment by Jezithyr** [comment]
> > Why create a new component for organ ticking when we can just have the ticking data on the organ comp?
> 
> Because you could have organs that don't need to tick.

All organs will need to tick to properly handle organ decay

**Comment by Jezithyr** [comment]
> > Why create a new component for organ ticking when we can just have the ticking data on the organ comp?
> 
> Because you could have organs that don't need to tick.

It might also be better to implement a more generic ticking component that allows update tracking for multiple systsems 🤔

**Comment by 0x6273** [comment]
> > > Why create a new component for organ ticking when we can just have the ticking data on the organ comp?
> > 
> > 
> > Because you could have organs that don't need to tick.
> 
> All organs will need to tick to properly handle organ decay, and any that don't are edge cases that can be handled by a boolean check

That sounds like it should just be on its own `OrganDecayComponent`. Not all organs should decay, for example bone marrow or mechanical organs.

Organ ticking (for functionality of the organ, i.e breathing, heart beats) can happen at different rates for different organs, and it should be possible to speed up, slow down, or pause organ ticking without affecting organ decay.

**Comment by Jezithyr** [comment]
> > > > Why create a new component for organ ticking when we can just have the ticking data on the organ comp?
> > > 
> > > 
> > > Because you could have organs that don't need to tick.
> > 
> > 
> > All organs will need to tick to properly handle organ decay, and any that don't are edge cases that can be handled by a boolean check
> 
> That sounds like it should just be on its own `OrganDecayComponent`. Not all organs should decay, for example bone marrow or mechanical organs.
> 
> Organ ticking (for functionality of the organ, i.e breathing, heart beats) can happen at different rates for different organs, and it should be possible to speed up, slow down, or pause organ ticking without affecting organ decay.

Bonemarrow does not count as an organ and mechanical organs will be handled with the implant system. All organs *will* tick, metabolism is also getting reworked to use normal chemical reactions instead of a separate system

**Comment by Jezithyr** [comment]
Heartrate, pulse, etc. will simply be a value that gets updated via organ ticking. There is not need for additional update ticking, especially when organ updates will dispatch events for other components to listen for.

**Comment by 0x6273** [comment]
> Heartrate, pulse, etc. will simply be a value that gets updated via organ ticking. There is no need for additional update ticking, especially when organ updates will dispatch events for other components to listen for.

How would lungs work then? Right now, they alternate between inhaling and exhaling every 2 seconds, which can altered by things like the stasis bed.

In this new system, would individual breaths no longer be simulated and you inhale and exhale at the same time, and stasis bed just changes how much oxygen is consumed?

**Comment by Jezithyr** [comment]
> > Heartrate, pulse, etc. will simply be a value that gets updated via organ ticking. There is no need for additional update ticking, especially when organ updates will dispatch events for other components to listen for.
> 
> How would lungs work then? Right now, they alternate between inhaling and exhaling every 2 seconds, which can altered by things like the stasis bed.
> 
> In this new system, would individual breaths no longer be simulated and you inhale and exhale at the same time, and stasis bed just changes how much oxygen is consumed?

Breathing updates would be handled by a separate system that integrates with atmos and then transfer the appropriate reagents to the organ where it gets handled via organ/metabolism simulation. Individual breaths WOULD be simulated however that's a special case. Everything else simulation related would be ticking at the same rate.

**Comment by Jezithyr** [comment]
Also don't worry about the merge conflict label, just keep cleaning things up and I'll handle the merge conflicts on my side. When it comes to organ ticking, just implement it as part of the organComponent for now, since that's how I'm handling it in the refactor. That may change in the future but for now just stick with that so we don't have more merge conflicts.

**Comment by Jezithyr** [comment]
Looks good to me

**Pull request merged**
