### PR TITLE
Add all relevant autodrobes and more hats across the station

### PR DESCRIPTION
**Pull request by Fishfish458**
## About the PR 
This PR:
* Removes job based clothing from Clothesmate and adds in the mutli-colored jumpsuit and clothes
* Change bar cabinet to always give shotgun/body armor
* Removed chances from spawning job based outfits for botany (These can be removed all together when drobes are actually mapped)
* Add hat counterparts to Autodrobe's costumes
* Change holoparasite box to use boxCardboard and contain the flashy troublemaker hat
* Add some shakers to the bar vend
* Adds all currently releveant autodrobes

TODO:
- [x] hydrobe
- [x] lawdrobe
- [x] secdrobe
oops all autodrobes:
- [x] detdrobe
- [x] medidrobe
- [x] cargodrobe
- [x] atmosdrobe
- [x] engidrobe
- [x] chefdrobe
- [x] chemdrobe
- [x] janidrobe

**Screenshots**

clothesmate
troublemaker
morehats
sechats

image
flashy

:cl:
- add: Added more clothes to the ClothesMate to make greytide less grey
- add: Job AutoDrobes are now coming to stations near you! Dress for the job.

### CODE REVIEW

**Comment by TimrodDX** [comment]
I just saw this, and I think a better solution would be to port the department-specific clothing machines from /tg/, which I'd want for Delta anyway.

image

image

image

image

image

**Comment by DogZeroX** [comment]
This makes me want a loadout system, kinda want the formal assistant suit...

**Comment by Fishfish458** [comment]
> I just saw this, and I think a better solution would be to port the department-specific clothing machines from /tg/, which I'd want for Delta anyway.
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image

Yeah, those are the end goal I think since chaplain already has his own and there's certainly more to come. I'm mainly mainly trying to make the clothesmate the go to assistant style station.

**Comment by Fishfish458** [comment]
Eh sure why not, I'll see how many vending machines I can get done before I go crazy, will re-open later

**Comment by DogZeroX** [comment]
Can just draft it.

**Comment by Fishfish458** [comment]
> Can just draft it.

that i will

**Review by Peptide90 — APPROVED** [review]
Reviewed, lgtm. Two minor comments about adding latex gloves to medical.
Also is there a science one missing? Doesn't need to be included in this PR if it is.

**Comment by Fishfish458** [comment]
They actually all use the same normal-unshaded so that was convenient. genedrobe is by far the most barebones.

image

**Comment by Fishfish458** [comment]
added last 4:
virodrobe
genedrobe
scidrobe
robodrobe

**Review by SweptWasTaken — APPROVED** [review]

**Pull request merged**
