### PR TITLE
 make poncho and sombrero spanish accent

### PR DESCRIPTION
**Pull request by ravage123321**
## About the PR

cl

## Why / Balance

this accent not used anywhere, so i decided to add it to some spanish/mexican clothing

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
do we have a spanish accent? Or is this PR unfinished, because it wouldn't work as intended.

**Comment by lzk228** [comment]
> do we have a spanish accent? Or is this PR unfinished, because it wouldn't work as intended.

yeah, it's exist, i don't know how to paste link to path, so `/Content.Server/Speech/EntitySystems/SpanishAccentSystem.cs`

**Comment by Partmedia** [comment]
Thank you for your contribution. Please describe your changes in English, discuss the "why", and correct the capitalization and punctuation in your Changelog entry.

**Comment by Tunguso4ka** [comment]
you also need to add your ss14 account nickname after :cl:

**Comment by Equivocateur** [comment]
> you also need to add your ss14 account nickname after 🆑

> need

Since when

**Comment by PJB3005** [comment]
You don't need to, it uses your GitHub username by default. It can be whatever you prefer and doesn't need to match your SS14 one.

**Comment by Tunguso4ka** [comment]
ah... sorry

**Comment by LankLTE** [comment]
While I don't have a problem with the changes inherently, it feels weird to have clothes that people could just want to wear normally force them to also have an accent (the accent itself is also pretty bare-bones but that's not your fault).

**Comment by deltanedas** [comment]
italian moustache and rat king crown do this too

**Pull request merged**
