### PR TITLE
Add Command pai

### PR DESCRIPTION
**Pull request by Baptr0b0t**
## About the PR

I add the PAI command, similar to the default one with the ability to listen to all NT communication and access to crew monitoring to help high ranking members

## Why / Balance

Allows a preview of the expected AI update, the idea having been closed by the frezze feature, I am relaunching it today
In addition, numerous silicon rounds leading a PAI to take the role of Borg leader, now it's official.
Also it could in the future become a thief's objective

## Technical details

Adds a new item, which takes the attributes of the PAI by default, adds all NT comms to the listener, adds an action allowing you to open the crew manifest UI

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

3 New icon
**Changelog**

:cl:
- add: Added a new Pal for the captain !

### CODE REVIEW

**Comment by deltanedas** [comment]
snitching on binary is bad enough now pai will say john smith valid on sec radio

**Comment by Baptr0b0t** [comment]
> snitching on binary is bad enough now pai will say john smith valid on sec radio

PAI cannot talk in any new chanel, just listening

**Comment by Djungelskog2** [comment]
oh yea i saw this one a while back, i was waiting for it cant wait to see it

**Comment by Baptr0b0t** [comment]
> oh yea i saw this one a while back, i was waiting for it cant wait to see it

https://github.com/space-wizards/space-station-14/pull/28003
Closed by feature freeze

**Comment by slarticodefast** [comment]
The crew manisfest probably should be a pai expansion card using this #26344.

The captain always having a pai with him still has an influence on balance, even if it cannot use coms. Let's say you stealthily kill the captain, take his stuff and he later gets found and revived. On MRP following the "new life rule", you cannot remember what led up to your death or while being dead, but having a constant observer with you circumvents this. I think it is fine if the captain sometime picks up a pai, but it should not be default equipment with extra functionality encouraging players to take this ghost role.

**Comment by Ghagliiarghii** [comment]
> The crew manifest probably should be a pai expansion card using this #26344.
> 
> The captain always having a pai with him still has an influence on balance, even if it cannot use coms. Let's say you stealthily kill the captain, take his stuff and he later gets found and revived. On MRP following the "new life rule", he cannot remember what led up to his death or what happened while being dead, but having a constant observer with you circumvents this. I think it is fine if the captain sometime picks up a pai, but it should not be default equipment with extra functionality encouraging players to take this ghost role over normal pais.

I think there will be many rounds where nobody bothers to take the role (like currently with Pun Pun etc.), but an alternative sol'n to fix this might be to just have a weight like 0.50 probability the command pAI spawns in the locker, so it's an every other round thing. (or 0.75 chance or whatever). I would be fine with either one.

**Comment by metalgearsloth** [comment]
Discussed with other maints. Design-side we don't want PAIs to be powercrept and high-impact roles.

**Comment by VigersRay** [comment]
PAIs on Sunrise like be:
image
image
Also syndi PAI has EMAG.
image

**Comment by lzk228** [comment]
> PAIs on Sunrise like be:

#26344

**Comment by VigersRay** [comment]
> > PAIs on Sunrise like be:
> 
> #26344

It seems to me that RND as usual will not care about creating these modules for the sake of ordinary PAI. Well, I hope this will not break my jokes too much.

**Pull request closed without merging**
