### PR TITLE
Nuke ops war anounce sound

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR 
Allow `ChatSystem` anounces method use custom sound file and add `sound` field to `CommunicationsConsoleComponent`.

**Screenshots**

**Changelog**

:cl:
- add: Added nuke ops sound declaration of war

### CODE REVIEW

**Comment by DogZeroX** [comment]
Pretty sure we already have this audio somewhere

**Comment by Morb0** [comment]
Delta level sound contains it in its mix.

**Comment by ike709** [comment]
\> not using bee's [war ops song](https://www.youtube.com/watch?v=N9559mSGjKg)

**Comment by metalgearsloth** [comment]
> > not using bee's [war ops song](https://www.youtube.com/watch?v=N9559mSGjKg)

thistbh. Would need to bump the delay to avoid overlap or account for it in the announcement in commsconsolecomponent.

**Comment by Morb0** [comment]
It would be easier if someone made a "Request changes" exactly what they want me to do.
If that is adding music from bee, then I'm not really interested in that.

**Review by mirrorcult — CHANGES_REQUESTED** [review]
there is an empty `StationEvent.cs` file that needs to be removed, otherwise good

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
