### PR TITLE
(Reagent) Minor blood and uncooked protein rework

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

See attached images, makes these reagents dangerous to humans, and feed non-humans.

Blood metabolizes into uncooked proteins at a 1:0.5 rate, which is also limited by uncooked proteins being metabolized into 0.5 proteins in non-humans.

humans trying to metabolize uncooked proteins will be poisoned with a 10% chance to vomit.
Because the blood will not all be turned into uncooked proteins, this will help reduce the amount of food poisoning they get! (Wow realism!)

Humans will see medium size, red popup indicating they are sick from what they consumed if they are metabolizing this dangerous food.

I also cleaned up duplicate values in SpiderBlood by making it a child of Blood.

Also minor change but I made the reagents Food/Drink so they're metabolized by the stomach and not the heart. (In theory anyways, organs don't do anything...)

## Why / Balance

Stops humans from drinking blood off the floor for the most part. Also opens up uncooked proteins effects to other species that can consume uncooked protein with no issue prior to this PR (Slimes will be able to gain food from uncooked protein for example)

This also indirectly buffs non humans by allowing them to consume blood, which although is a very, very, weak food source, can still be considered.

Also affects humans eating raw meat and the like, as they contain uncooked proteins.
Also reduces the amount of poison humans will take indirectly, as they will have the chance to vomit.

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- add: Blood when consumed metabolizes into uncooked proteins, and sates thirst of non-humans
- add: Non-humans will have a small amount of hunger sated when consuming uncooked proteins.
- tweak: Humans will take poison damage with a chance to vomit when metabolizing uncooked protein.
- tweak: Humans take less damage from uncooked proteins (2->1)
- add: Humans will "feel sick" when they metabolize uncooked proteins.

### CODE REVIEW

**Comment by CatMagic1** [comment]
I have drunk large amounts of blood in my life and have never been poisoned by it.

**Comment by QuietlyWhisper** [comment]
> I have drunk large amounts of blood in my life and have never been poisoned by it.

You probably didn't feel too great after doing so, or at least normally you wouldnt

**Comment by HoidC** [comment]
> I have drunk large amounts of blood in my life and have never been poisoned by it.

human blood?

**Comment by deltanedas** [comment]
- drinking blood should turn into uncooked proteins not injecting
- humans should get human blood
- injecting human blood into humans should restore blood
- injecting wrong blood should give hemotransfusion shock from fish game
- blood types would be easy to implement with reagent data since its properly stored now, could then use that for blood type shock from fish game

**Comment by Equivocateur** [comment]
> injecting wrong blood should give hemotransfusion shock from fish game

AHTR should be fatal if not corrected fast

**Comment by CatMagic1** [comment]
> > I have drunk large amounts of blood in my life and have never been poisoned by it.
> 
> human blood?

Yes.
Large amounts of human blood.

**Comment by deltanedas** [comment]
> AHTR should be fatal if not corrected fast

being too realistic and having your immune system kill you would be bad since someone gets a hypopen with blood to instantly kill you

**Comment by HoidC** [comment]
> > > I have drunk large amounts of blood in my life and have never been poisoned by it.
> > 
> > 
> > human blood?
> 
> Yes. Large amounts of human blood.

why?

**Comment by deltanedas** [comment]
well you can do a few of them by just making blood damage stuff be in drink metaboliser effect instead of poison
then have restoring blood be in medicine effect

**Comment by QuietlyWhisper** [comment]
> well you can do a few of them by just making blood damage stuff be in drink metaboliser effect instead of poison then have restoring blood be in medicine effect

I'm pretty sure there would be no difference because everything gets sent to and handled by chemstream and not the organs themselves, unfortunately

**Comment by deltanedas** [comment]
no drink is just metabolised by the stomach

**Comment by QuietlyWhisper** [comment]
> no drink is just metabolised by the stomach


https://github.com/space-wizards/space-station-14/assets/121047731/57461ab4-09db-4c82-bda4-65aecfdb4881

image

**Comment by CatMagic1** [comment]
> > > > I have drunk large amounts of blood in my life and have never been poisoned by it.
> > > 
> > > 
> > > human blood?
> > 
> > 
> > Yes. Large amounts of human blood.
> 
> why?

we are always watching

**Comment by QuietlyWhisper** [comment]
Added a message humans will see when they drink these reagents
image

**Comment by QuietlyWhisper** [comment]
So a new issue just came up, dwarves don't use the human metabolizer, they have a few unique interactions. Thus meaning dwarves would have no issues drinking blood or uncooked protein. I'm unsure if this should be left as is, I don't know the anatomy of a dwarf, so I'm not sure if they'd have sensitive stomachs or not.

**Comment by githubuser4141** [comment]
> > I have drunk large amounts of blood in my life and have never been poisoned by it.
> 
> Unless its half a litre in a sitting its not “large” amounts.
> 
> Drinking blood is toxic, a biohazard (when pr?) in most cases and your stomach doesn't like either.
> 
> Drinking blood off the floor by itself is bad enough, but I disagree with the implementation here - literally injecting blood (back) into a body causes the aforementioned effects.

Do small amounts of toxin damage heal themselves, though? If they don't, then this literally just poisons you - doesn't matter about dosage. In SS14 without self-healing one could consume 1 drop of blood per day and die on day 100 because they'd be at 100 toxin damage.

**Comment by QuietlyWhisper** [comment]
> > > I have drunk large amounts of blood in my life and have never been poisoned by it.
> > 
> > 
> > Unless its half a litre in a sitting its not “large” amounts.
> > Drinking blood is toxic, a biohazard (when pr?) in most cases and your stomach doesn't like either.
> > Drinking blood off the floor by itself is bad enough, but I disagree with the implementation here - literally injecting blood (back) into a body causes the aforementioned effects.
> 
> Do small amounts of toxin damage heal themselves, though? If they don't, then this literally just poisons you - doesn't matter about dosage. In SS14 without self-healing one could consume 1 drop of blood per day and die on day 100 because they'd be at 100 toxin damage.

There was a recent pr for passive healing, not sure if it applies to all damage types or which types it does

Theres not very many scenarios where youd be drinking blood in ss14 aside from puddles, and if not, its in a container in which case the player is likely drinking a lot and will discover this was not a great idea

Youll also not be entirely poisoned by the entire contents of what you drank, as theres still a chance the body will react by vomitting.

**Comment by QuietlyWhisper** [comment]
> > > > I have drunk large amounts of blood in my life and have never been poisoned by it.
> > > 
> > > 
> > > Unless its half a litre in a sitting its not “large” amounts.
> > > Drinking blood is toxic, a biohazard (when pr?) in most cases and your stomach doesn't like either.
> > > Drinking blood off the floor by itself is bad enough, but I disagree with the implementation here - literally injecting blood (back) into a body causes the aforementioned effects.
> > 
> > 
> > Do small amounts of toxin damage heal themselves, though? If they don't, then this literally just poisons you - doesn't matter about dosage. In SS14 without self-healing one could consume 1 drop of blood per day and die on day 100 because they'd be at 100 toxin damage.
> 
> There was a recent pr for passive healing, not sure if it applies to all damage types or which types it does
> 
> Theres not very many scenarios where youd be drinking blood in ss14 aside from puddles, and if not, its in a container in which case the player is likely drinking a lot and will discover this was not a great idea
> 
> Youll also not be entirely poisoned by the entire contents of what you drank, as theres still a chance the body will react by vomitting.

Alternatively, it would also be a 5 minute adventure to limit damage to a certain amount of blood consumed.

Uncooked proteins seems fair game because youll only find it in raw meat and mice

It actually might even be a better practice to have blood metabolise into uncooked proteins as a human, so we dont need to code duplicate effects here

**Comment by QuietlyWhisper** [comment]
Gonna set this to draft and make that change.

Also looking for more feedback on if these should even poison you at all; its not really part of my PR, uncooked protiens always did 2 damage to humans

**Comment by QuietlyWhisper** [comment]
Ok so basically I realized I made blood have the exact same effect as uncooked protein, so I just condensed the yml and incidentally made metabolism more realistic by having blood get metabolized into uncooked protein!

**Comment by Aisu9** [comment]
mmmmh yes, self brute medication, food and drink by using your own lizard blood

**Comment by QuietlyWhisper** [comment]
> mmmmh yes, self brute medication, food and drink by using your own lizard blood

Youd be doing significantly more damage to yourself than youd be healing, let alone of you can even get a decent anount of healing out of it, but sure, you *could* look at ut that way. Slimes can actually do this with very little downsides currently.

**Comment by UbaserB** [comment]
New “drink blood” meta as a lizard :3

**Comment by QuietlyWhisper** [comment]
It's a silly gimmick at best, food healing has always been really shit, and considering you only get a fraction of protiens per unit it will be significantly lower...

If it really is as strong as people are thinking it will be its very easy to simply lower the metabolism amount to further reduce how much protiens are gained from it

**Comment by UbaserB** [comment]
> It's a silly gimmick at best, food healing has always been really shit, and considering you only get a fraction of protiens per unit it will be significantly lower...
> 
> If it really is as strong as people are thinking when we see it live, it will be its very easy to simply lower the metabolism amount to further reduce how much protiens are gained from it

i wasn’t talking about healing. I was talking about the satiating hunger bit lol

**Comment by QuietlyWhisper** [comment]
> i wasn’t talking about healing. I was talking about the satiating hunger bit lol

It should be the same output in theroy, since it goes blood>uncooked protien>protien in animals, where each transition reduces the total amount of reagent consumed

**Comment by Emisse** [comment]
Whisper chem balancer hasnt failed me yet

**Comment by QuietlyWhisper** [comment]
if this goes well with the players I'll replicate it into a proper diet restriction system so lizards can go back to eating whatever they want (with consequences)

**Comment by LankLTE** [comment]
> if this goes well with the players I'll replicate it into a proper diet restriction on foods so lizards can go back to eating whatever they want (with consequences)

I figure I should say that there needs to be some system other than every food item from manually being a “food group” reagent, as that’s arguably worse for maintenance than what we currently have. If that’s doable, then go for it.

**Comment by QuietlyWhisper** [comment]
> I figure I should say that there needs to be some system other than every food item from manually being a “food group” reagent, as that’s arguably worse for maintenance than what we currently have. If that’s doable, then go for it.

It will be as simple as I made telecoms I promise

**Comment by QuietlyWhisper** [comment]
> > I figure I should say that there needs to be some system other than every food item from manually being a “food group” reagent, as that’s arguably worse for maintenance than what we currently have. If that’s doable, then go for it.
> 
> It will be as simple as I made telecoms I promise

I'm sure we're not looking to replicate food contents 1:1 with real life anyways.

**Pull request merged**
