### PR TITLE
remove ingestion / identity blockers from bandanas

### LINKED ISSUE #27163: Unable to eat food with bandana on
## Description

"You need to take off the black bandana first!"

**Screenshots**

image

### PR DESCRIPTION
**Pull request by aspiringLich**
Bandanas cover your head, not your face, so they should not block ingestion / identity. This is the intended behavior as `enabled: false` was present on `IngestionBlocker` and `IndentityBlocker` but it does not actually do anything. I don't think it's really necessary to add the disabled marker, since I'm not aware of this being a problem anywhere else, it's just whoever first wrote the yaml made a mistake. 

Fixes #27163.

There are bandanas that cover your mouth too, these block ingestion like normal.

**Changelog**

:cl:
- fix: Bandanas no longer prevent you from eating or being identified.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Please test your pr.

**Comment by aspiringLich** [comment]
I did, forgot to add an image.

Screenshot_20240603_075355

**Comment by 0x6273** [comment]
> Oh the builds fail, that's weird it runs locally...

The test fails are real, there's no way you ran them locally. Also this looks like a webedit.
image

**Comment by aspiringLich** [comment]
Mhm it was but i fetched the branch locally. Probably messed something up there because it definitely ran. I'll test in a bit not at my computer right now.

**Comment by Zap527** [comment]
I'm pretty sure these components are intended to be there due to bandanas being foldable into a bandit-style, which covers the mouth. If it's also blocking identity and ingestion while unfolded, that's a bug that should be adressed instead of essentially moving the bug.

**Comment by Zap527** [comment]
Ah, scratch my comment. I just saw that this does indeed adress foldable bandanas. Curse my reading comprehension skills.

**Comment by 0x6273** [comment]
> Mhm it was but i fetched the branch locally. Probably messed something up there because it definitely ran. I'll test in a bit not at my computer right now.

How did you run the tests? You are supposed to run all three of `Content.Tests`, `Content.IntegrationTests` and `Content.YAMLLinter`. You can look in the workflow yamls for the commands, I don't think they're documented on the dev wiki.

**Comment by aspiringLich** [comment]
I did some more testing. I think the reason this has gone so long unfixed is bandanas seem to work as expected with every single race, it is only specifically moths that are affected. Why seems to escape my comprehension.

Anyway putting `ClothingHeadBandBase` after `ClothingMaskBand<Color>` seemed to fix it so...

Screenshot_20240603_141412

I have to go, but later I'll stare at the YAML some more and try and figure out what the heck is going on, and see if there's a better way to do this.

**Comment by aspiringLich** [comment]
this has seemed to be fixed last i played so...

**Pull request closed without merging**
