### PR TITLE
Paper save button, back to ctrl+enter save.

### PR DESCRIPTION
**Pull request by PJB3005**
## About the PR
Saving paper is on ctrl+enter again, regular enter is new line. Added a save button that shows the hotkey to fix the UI issue.

## Why / Balance
This is objectively the correct way to handle this.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**
:cl:
- tweak: Saving paper is on ctrl+enter again. Also there's a visible "save" button now.

### CODE REVIEW

**Comment by Strol20** [comment]
I think a separate setting is needed to complete this war

**Comment by PJB3005** [comment]
> I think to end this war between enter and ctrl + enter, we need to make it a separate setting

Absolutely not. This is standard behavior in every GUI program with a multi-line text input, which is exactly what paper (and every other multi-line control in the game) is.

We could expose this in the controls menu sure, but these low-level GUI key binds are icky to expose to users as modifying them can seriously break their game in ways they don't realize. If people really want they can already edit their key binds config file.

**Comment by PolterTzi** [comment]
As far as I know, I've personally used more GUIs that send on Return and newline on Shift+Return than the way you describe, so I don't think it's quite the case with every GUI.

**Comment by PJB3005** [comment]
> As far as I know, I've personally used more GUIs that send on Return and newline on Shift+Return than the way you describe, so I don't think it's quite the case with every GUI.

These are things like chat clients, where typing multi-paragraph messages are not the common use case. Anything where you _are_ expected to type multi-paragraph posts, **like GitHub**, this is not the standard.

**Comment by Everturning** [comment]
"hey what if we made it customiz-"
"absolutely not"

**Comment by Brandon-Huu** [comment]
I despise this

**Comment by deltanedas** [comment]
this is correct way
if you are just writing 1 line on paper you are shitter mime just bypassing vow

**Comment by Brandon-Huu** [comment]
What program even uses [ CTRL ] + [ ENTER ] for new lines?

**Comment by mirrorcult** [comment]
this isnt using ctrl+enter for new lines. its using ctrl+enter for save, like it says in the pr title

**Comment by MACMAN2003** [comment]
I would say that using control + enter to save is a bit esoteric. I feel like control + s would be obvious-er.

**Pull request merged**
