### PR TITLE
Prevent using LOOC in crit

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds a configurable CCVAR for disabling players in critical condition from using LOOC chat.
Configured to false for all wizard's den servers (figure i'd let the admins tweak it if they feel the need)

Supersedes #17907 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Players in critical condition can no longer use LOOC chat.

### CODE REVIEW

**Comment by lzk228** [comment]
if players share IC info in LOOC, then administration definitely do something wrong

**Comment by HoidC** [comment]
top 10 ss14 mistakes: 

number 1: blame the admins for anything that's not their fault

**Comment by Nairodian** [comment]
> if players share IC info in LOOC, then administration definitely do something wrong

We like to enforce things mechanically where we can.

**Review by metalgearsloth — APPROVED** [review]

**Comment by Emisse** [comment]
im just gonna merge this so we can stop the circular arguments about it

**Pull request merged**
