### PR TITLE
Standard issue handguns for security

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

No this is not a shitpost. Security being unable to handle basic threats without running to warden for anything is a pain in the ass. Batons are good but nonhuman targets (especially in groups) are a huge threat to players. Consider this the buff security desperately needs amid continuous increases in danger around them.

the deets:
- secoffs, cadets, warden, and HOS start with a mk 58 loaded with rubber rounds.
- these roles additionally get a lethal pistol magazine in their bag.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Security staff are now being issued handguns with rubber bullets for station security. An extra magazine with lethals has additionally been supplied in their bags.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Ignoring the lethals part of this:

> Cadets rn don't get them because that seems like it could be very bad.

I get conflicting info on whether intern roles are just a flag saying "I'm new" or genuinely supposed to punish you for 5 hours.

**Comment by EmoGarbage404** [comment]
> I get conflicting info on whether intern roles are just a flag saying "I'm new" or genuinely supposed to punish you for 5 hours.

i can add them in. I was advised not to but i do enjoy maximizing pain for everyone.

**Comment by Mirino97** [comment]
I am VERY opposed to this.

Didn't we just do a whole pass a few months ago removing most lethals from security?
The possibility of shitsec'ing and loot pinata far outweight the perceived merit of "better defense"

You're not supposed to have a tool for every job constantly with you.

**Comment by FacePluslll** [comment]
Have you ever had a moment in your life thinking "this is a horrible idea but fuck it", it's one of those moments with this pr.

**Comment by deltanedas** [comment]
can only imagine what the shitters/powertrippers/people that slip and cuff sec will do

**Comment by metalgearsloth** [comment]
> can only imagine what the shitters/powertrippers/people that slip and cuff sec will do

They're too busy raiding maint loot.

**Comment by notquitehadouken** [comment]
can't wait to kill 1 secoff as syndie and get a gun out of it

**Comment by EmoGarbage404** [comment]
> can't wait to kill 1 secoff as syndie and get a gun out of it

you are aware that you can purchase a gun

**Comment by notquitehadouken** [comment]
> > can't wait to kill 1 secoff as syndie and get a gun out of it
> 
> you are aware that you can purchase a gun

yes but now i don't have to do the purchasing part

**Comment by FacePluslll** [comment]
test merge this bad boy for a day and watch the amusement/horror that follows it I say

**Comment by Emisse** [comment]
all your arguing about hypotheticals means nothing lets just try it and if its bad well revert in a week

**Pull request merged**
