### PR TITLE
Removes paramedic suit from medidrobe

### LINKED ISSUE #22145: Paramedic checklist
## Description
Just some things I want to change
Feel free to do things for me

* [x] remove spare suit and clothes from the medical wardrobe machine #22146
* [x] rename their medical belt to EMT belt #22173
* [ ] make the EMT belt a unique prototype and give it a darker sprite
* [ ] change the suit to function like a hardsuit (like voidsuits do in baystation 12) but in return remove slash resistance, make it ginormous, and it won't get a built in flashlight
* [x] give them blue shoes and rollerbed in bag #22649
* [x] add the room and role to barratry #22150
* [x] add the room and role to marathon #22151

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

removes the paramedic voidsuit from the medidrobe
removes paramedic clothes from the medidrobe
adds the paramedic winter coat to the paramedic locker
adds the regular doctor jumpsuits and skirts to the medidrobe
## Why / Balance

rampant powergaming!

resolves #22145
the guy who added the role said they would do it #15439
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: JoeHammad
- remove: Removed the spare paramedic clothes and EVA suit from the medidrobe
- add: added medical doctor jumpsuits and skirts to the medidrobe

### CODE REVIEW

**Review by Brandon-Huu — APPROVED** [review]
image

**Comment by JoeHammad1844** [comment]
realest image

**Comment by Rainbeon** [comment]
This is really bad for maps where Paramedics require promotions to even exist (Marathon, Barratry) and having an extra single one is really nice for solo Paramedic stations (most of them!) for when the actual Paramedic dies on the job and needs to be saved. There is an actual function for this besides random Medical Interns stealing them.

**Comment by EmoGarbage404** [comment]
don't we have mapped drobes for paramed?

**Comment by JoeHammad1844** [comment]
> This is really bad for maps where Paramedics require promotions to even exist (Marathon, Barratry) and having an extra single one is really nice for solo Paramedic stations (most of them!) for when the actual Paramedic dies on the job and needs to be saved. There is an actual function for this besides random Medical Interns stealing them.

the paramedic's suit isnt the only EVA capable suit on the station, any empathetic captain or hop would let you take an EVA suit to save somebody, if you're desperate you might even ask engineering

**Comment by JoeHammad1844** [comment]
> don't we have mapped drobes for paramed?

not sure what you mean by this but there is a spare pair of clothes in the paramedic locker. if you want I can give paramedics the cap and windbreaker on spawn

**Comment by JoeHammad1844** [comment]
by the way i am perfectly willing to do the mapping required to add paramedics to maps, i just don't know how to add them to the stations job roster, if you know what i mean

**Comment by Rainbeon** [comment]
> the paramedic's suit isnt the only EVA capable suit on the station, any empathetic captain or hop would let you take an EVA suit to save somebody, if you're desperate you might even ask engineering

Yes, obviously you can go into space to save someone with an Emergency EVA suit even, but for Medical that's... kind of the entire reason the Void Suit exists. To be a suit for Medical to help save people in space.

Furthermore this removes the ability to have *two* dedicated Paramedics on high-pop stations with only one Paramedic at round-start, as most maps have the equipment otherwise to support this

It further also makes no sense to remove their base clothes from the Medidrobe when every other department has their clothes in their respective drobes, such as Atmos, Sec, Sci, Cargo, Engi... so on.

**Comment by Emisse** [comment]
also dont give them nitriles

**Comment by JoeHammad1844** [comment]
> Yes, obviously you can go into space to save someone with an Emergency EVA suit even, but for Medical that's... kind of the entire reason the Void Suit exists. To be a suit for Medical to help save people in space.

This is only really needed on two maps (that i know of) and I plan to add paramedic support to those maps

> Furthermore this removes the ability to have _two_ dedicated Paramedics on high-pop stations with only one Paramedic at round-start, as most maps have the equipment otherwise to support this

This is a roleplaying game, ask the HOP for a job change and a suit

> It further also makes no sense to remove their base clothes from the Medidrobe when every other department has their clothes in their respective drobes, such as Atmos, Sec, Sci, Cargo, Engi... so on.

Paramedics don't have as high a population as doctors, and there is a spare pair in the paramedic locker. I believe you can also print them at the HOP's uniform printer

**Comment by JoeHammad1844** [comment]
> also dont give them nitriles

why not? they're just cosmetic currently, and it fits better with their blue

**Comment by Emisse** [comment]
image

**Comment by JoeHammad1844** [comment]
what could this mean

**Comment by Rainbeon** [comment]
>This is only really needed on two maps (that i know of) and I plan to add paramedic support to those maps

Can you perhaps do this first before making the maps awful for Paramedic players?

>This is a roleplaying game, ask the HOP for a job change and a suit

You already do the job change and that's perfectly fine, but HOP can't print Void Suits.

**Comment by JoeHammad1844** [comment]
> You already do the job change and that's perfectly fine, but HOP can't print Void Suits.

there are plenty of EVA suits in EVA

**Comment by Rainbeon** [comment]
> there are plenty of EVA suits in EVA

Do you not see anything wrong with a Paramedic being forced to use standard EVA instead of their literal job suit?

**Comment by JoeHammad1844** [comment]
> Do you not see anything wrong with a Paramedic being forced to use standard EVA instead of their literal job suit?

no, I don't, you can put up with 10% slower move speed, right?

> Marathon, Barratry, and maybe some other maps. (I haven't played Core enough to remember and don't get to play small ones often)

I'll check those out

**Comment by Rainbeon** [comment]
>no, I don't, you can put up with 10% slower move speed, right?

By the same logic why does the Paramedic Void Suit exist then if it serves no purpose for the Paramedic?

**Comment by JoeHammad1844** [comment]
> By the same logic why does the Paramedic Void Suit exist then if it serves no purpose for the Paramedic?

10% lower move speed vs not having EVA at all, that comparison makes sense

**Comment by JoeHammad1844** [comment]
alright, the paramedic no longer gets nitriles

**Comment by Rainbeon** [comment]
> 10% lower move speed vs not having EVA at all, that comparison makes sense

I mean why not just map a standard EVA if its the same. Paramedic Void Suit has Rad resistance and Caustic resistance as its defining traits and its highly useful for identification of Paramedics/actual Medical Staff versus someone that just has an EVA suit, and visual identification is important for recognizing what's happening and who's yelling at you to open your department through the window.

If you just want to curb random interns/docs stealing it from the drobe for Powergaming I'd rather see it just put in with the CMO's handout stuff instead (like how there's an extra Handheld Crew Monitor for extra promotions, include an extra suit too) or something along those lines. But just voiding it entirely does not seem helpful.

**Comment by JoeHammad1844** [comment]
there's usually no need for a second paramedic anyway and there are 10 different ways of identifying yourself that isn't your EVA suit. 

also, heres the new paramedic room on barratry
image
just uhh.. how do I add them to the job pool?

**Comment by Rainbeon** [comment]
>  just uhh.. how do I add them to the job pool?

It's part of the yml file for the map pretty sure under availableJobs.

**Comment by JoeHammad1844** [comment]
paramedic room on marathon
image

**Comment by Rainbeon** [comment]
I think Cluster and Omega (maybe Saltern too? Less sure on this) also lack spawns and depended on MediDrobe for the role

**Comment by Emisse** [comment]
cluster and omega dont have paramedic

**Comment by JoeHammad1844** [comment]
> cluster and omega dont have paramedic

should i do all the maps in one PR or one at a time?

**Comment by Emisse** [comment]
make mapping changes separately, do not add paramedic to maps its not on

**Comment by JoeHammad1844** [comment]
> do not add paramedic to maps its not on

why not?

**Comment by Emisse** [comment]
the maps were not designed with them in mind

**Comment by Rainbeon** [comment]
> the maps were not designed with them in mind

As is they are currently played with them anyway a decent bit of the time due to HoP promotions and MediDrobe, atleast Barratry and Marathon do (I doubt Low Pop stations do this as often)

**Comment by JoeHammad1844** [comment]
would adding paramedics to just marathon and barratry be fine?

**Comment by Emisse** [comment]
i have no issue with those 2

**Comment by Emisse** [comment]
medical is already very central on pubby though so i wonder how necessary it is

**Comment by JoeHammad1844** [comment]
now that the paramedic suit is available on barratry and marathon we can stop arguing!

**Comment by JoeHammad1844** [comment]
well, hopefully soon to be

**Comment by JoeHammad1844** [comment]
Do I need to make any changes, emisse?

**Comment by Rainbeon** [comment]
Can we still keep the normal Paramedic clothes in since those aren't power-gaming, or atleast in reduced amounts while also adding Medical Doctor jumpsuit/skirts? (I'm really not sure why those are not available while Paramedic jumps are)

**Comment by JoeHammad1844** [comment]
> Can we still keep the normal Paramedic clothes in since those aren't power-gaming, or atleast in reduced amounts while also adding Medical Doctor jumpsuit/skirts? (I'm really not sure why those are not available while Paramedic jumps are, which causes HoP-based MD promotions to have to use Paramed stuff)

they are in the paramedic locker. and the medidrobe already has regular medical clothing

**Comment by JoeHammad1844** [comment]
wait they actually arent, ill quickly add them

**Comment by Rainbeon** [comment]
>and the medidrobe already has regular medical clothing

It actually doesn't which is strange

**Comment by JoeHammad1844** [comment]
fixed now

**Comment by Rainbeon** [comment]
Alrighty I'm happy enough with it now personally, may wanna update Changelog and maybe PR title for scope

**Comment by JoeHammad1844** [comment]
changed

**Pull request merged**
