### PR TITLE
Saucestation Lobby Image

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Adds a new lobby screen in the theme of Pizza Tower intro cards. Approved by Tour De Pizza.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Aleksh
- add: Added a saucy new lobby screen!

### CODE REVIEW

**Comment by potato1234x** [comment]
amazing

**Comment by moonheart08** [comment]
Not super certain about a) using a character we have no rights to and b) having a letterboxed lobby screen.

**Comment by deltanedas** [comment]
i think the letterboxing is ok given that the left side uses black slanted lines it blends in

**Comment by VasilisThePikachu** [comment]
> Not super certain about a) using a character we have no rights to

Well, the developers of the game that own the character did allow it. Check the imgur link in the attributions this pr adds

**Comment by Emisse** [comment]
Looks good to me

**Comment by metalgearsloth** [comment]
> > Not super certain about a) using a character we have no rights to
> 
> Well, the developers of the game that own the character did allow it. Check the imgur link in the attributions this pr adds

It doesn't say the license.

**Comment by Alekshhh** [comment]
I asked them for a more coherent response

**Comment by Alekshhh** [comment]
I have not gotten an answer for a while so assume this as dead

**Comment by potato1234x** [comment]
Rip

**Comment by CaptainSqrBeard** [comment]
Rip

**Pull request closed without merging**
