### PR TITLE
Adds the Improvised Shotgun

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds craftable improvised shotguns to the game. Also adds improvised shotgun shells, however you cannot craft them as ~~I was too lazy to remove them~~ they're probably not possible to make balanced currently with the options the crafting system has available.
The improvised shotgun is made up of four parts: A gas pipe, some cloth, a wooden stock made with 5 planks, and a modular receiver. You can get the receiver in maintenance rarely, or make it at an autolathe (abliet, it's pretty god damn expensive.)

**Why it's good for the game™:**
Players have complained about lack of options in situations like zombies for a while now, and this should hopefully fix that. They are expensive to make and are completely useless without ammo, so it's likely they'll only be made in small quantities when there isn't an emergency.
This also gives cargo something they can produce & sell, which is something we've wanted for a while (I think?)

**Media**
Content Client_nXKwxPysui

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added craftable improvised shotguns. Ammo not included.

### CODE REVIEW

**Comment by Myakot** [comment]
I'm happy for getto-gameplay. Need maximum amounts of it. Murderhobos in maints scaring both antags and sec

**Comment by Emisse** [comment]
im alright with it

**Comment by Jackal298** [comment]
Might add a saw-off option for the shotgun

**Comment by Flareguy** [comment]
> Might add a saw-off option for the shotgun

I was hesitating on this since it could potentially make them too overpowered (at least, without any kind of downside attached to sawing it off.) Craftable weapons are fairly overpowered right now and it wouldn't be good for the improvised shotgun to follow suite.
If it ends up being fine in testing (once merged,) a sawn-off variant could probably be added - there's already sprites for it in /tg/.

**Comment by Jackal298** [comment]
> > Might add a saw-off option for the shotgun
> 
> I was hesitating on this since it could potentially make them too overpowered (at least, without any kind of downside attached to sawing it off.) Craftable weapons are fairly overpowered right now and it wouldn't be good for the improvised shotgun to follow suite. If it ends up being fine in testing (once merged,) a sawn-off variant could probably be added - there's already sprites for it in /tg/.

I think that if they can make it possible to use liquids during crafting, then maybe we will be able to make a normal crafting cartridge.

As for the cutoff, I understand you, considering that the game does not have the mechanics of loss of damage at a distance

**Comment by Jackal298** [comment]
hi, i have a question, why do the detail sprites have a problem with displaying sprites? I'm trying to fix it but I don't understand what the problem is

**Pull request merged**
