### PR TITLE
Zombies drop their headsets.

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Zombies will drop their headsets, like gloves.
Prevents zombie metagaming through comms they shouldn't be able to understand.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- tweak: Zombies drop their headsets, preventing them from hearing comms.

### CODE REVIEW

**Comment by deltanedas** [comment]
inb4 new handheld radio meta

**Comment by Slava0135** [comment]
fun fact: zombies can toggle their helmet and turn helmet lights

**Comment by Slava0135** [comment]
> inb4 new handheld radio meta

gonna add battery slot to them

**Comment by QuietlyWhisper** [comment]
> inb4 new handheld radio meta

that would be really funny. Having a language system and component would fix this though! Beyond me, currently.

**Comment by deltanedas** [comment]
zombies hear the crew as gruaahh...
crew hear the zombies as braaaaains.....
zombies hear eachother fine

**Comment by Snowyypanda** [comment]
the more realistic approach to this is to make whatever the words that are displayed in chat look like gibberish, this is lazy design

**Comment by Snowyypanda** [comment]
also zombies drop their gloves? why? that doesn't make sense

**Comment by deltanedas** [comment]
> also zombies drop their gloves? why? that doesn't make sense

for gameplay duh zombies using insuls is sussy + makes it easier to see if someone is a zombie

**Comment by QuietlyWhisper** [comment]
I didn't add the gloves part, that's been in the code for ages. I guess the coder wanted zombies to be affected by grilles.
image

**Pull request merged**
