### PR TITLE
Rename head roles, so they all can be abbreviated to HoS (April Fools)

### PR DESCRIPTION
**Pull request by TK-A369**
This PR is to be temporarily merged for April Fools.

## About the PR
This PR changes names of head roles.
- Captain -> Head of Station
- Head of Personnel -> Head of Service
- Chief Engineer -> Head of Singularity
- Chief Medical Officer -> Head of Surgery
- Research Director -> Head of Science
- Quartermaster -> Head of Supply
- Head of Security stays the same, because it's already abbreviated to HoS

[This message](https://discord.com/channels/310555209753690112/1187578944199868446/1188083093245010041) gave me idea to do this PR.

## Why / Balance
It's funny change for April Fools.

## Technical details
N/A

## Media
img
img
img
img

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**

### CODE REVIEW

**Comment by TK-A369** [comment]
Should I add changelog?

**Comment by 6SpadesLuke** [comment]
make head of security head of shitsec

**Comment by Tayrtahn** [comment]
Mm, subtle and brilliant. I appreciate the thoroughness of updating all the items and even the loading screen tips!

> Should I add changelog?

Nah, not needed for an April Fools thing.

**Review by Tayrtahn — APPROVED** [review]

**Comment by Tayrtahn** [comment]
> Good PR I only have one suggestion

I like it, but it kinda messes up the HoS theme, no?

**Comment by PJB3005** [comment]
Head of Still Just a Week Away

**Comment by Tayrtahn** [comment]
Perfect

**Comment by TK-A369** [comment]
Okay, I will change "Head of Surgery" to "Head of Still Just a Week Away", as PJB suggested.
Also I found some of items not renamed properly, I'll fix that.

**Review by VasilisThePikachu — APPROVED** [review]
Meow

**Comment by JackSage** [comment]
hos to hos's office, the guy who killed hos is now wearing hos's ID and killing the hos!

**Comment by deltanedas** [comment]
the head of still just a week away stormed in with a host of security officers and demoted me on the spot

**Pull request merged**
