### PR TITLE
Saltern Tweaks

### PR DESCRIPTION
**Pull request by SweptWasTaken**
- Makes the bar look nicer
- Fixes dark areas of the station
- Dorms is actually dorms, with 3 rooms
- Some tile fuckups in maint
- Small changes

### CODE REVIEW

**Comment by PJB3005** [comment]
Screenshots?

**Comment by Zumorica** [comment]
I hope you didn't forget to fix roundstart atmos!

**Comment by SweptWasTaken** [comment]
Content Client_2020-10-21_11-06-14
Content Client_2020-10-21_11-06-49

Bar and Dorms

**Comment by Zumorica** [comment]
cute, good changes

**Comment by SweptWasTaken** [comment]
> 
> 
> cute, good changes

meet me in dorms 3 after merge

**Comment by DrSmugleaf** [comment]
But where is dorms 4

**Comment by SweptWasTaken** [comment]
> 
> 
> But where is dorms 4

your bedroom

**Comment by PJB3005** [comment]
But where will we fit the locker room now?

**Pull request merged**
