### PR TITLE
Kolibri

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Added the worlds tiniest gun
## Why / Balance

bored and I need practice + It's funny. Does 18 stun, 2 pierce, and 2 blunt. I kinda want to turn this into an uplink weapon primarily for stunning; would be cool to see fresh syndi tactics + maybe would allow nonlethal robberies(?)

I would be happy to do balancing later on

## Media

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

shhh.

### CODE REVIEW

**Comment by Aexxie** [comment]
This was primarily for testing a few things, thought I might as well pr it since I did it.

**Comment by metalgearsloth** [comment]
There's currently a freeze on adding new guns and I don't foresee this fitting in balance wise.

**Comment by JoeHammad1844** [comment]
i think a better way to do non lethals is just allow syndies to buy rubber bullets for the viper

**Comment by Aexxie** [comment]
> There's currently a freeze on adding new guns and I don't foresee this fitting in balance wise.

yeah me neither lol. just for fun

**Comment by metalgearsloth** [comment]
boop

**Pull request closed without merging**
