### PR TITLE
Spationaut Hardsuit Light buff

### PR DESCRIPTION
**Pull request by buntobaggins**
## About the PR
Buffed the light on the Spationaut Hardsuit to make it easier to operate in low light conditions.

## Why / Balance
Areas like big wrecks or large asteroids have wide open spaces that can be hard to illuminate with the light currently on most hardsuits. This change makes the light on par the the standard flashlight.

## Technical details
Added the PointLight component the the Spationaut Hardsuit helmet with a radius of 6 

## Media

Base Game:
salvLIghtBuffBefore
PR:
salvLightBuffAfter

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
There should be none. (but this is my first pr so who knows)

**Changelog**

:cl:
- tweak: Increased light radius on the Spationaut Hardsuit

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
But why not just carry a flashlight? They're in the Salvage tech vend

**Comment by Radezolid** [comment]
Carry a floodlight or flares from the salvage vendor.
This removes pretty much the only reason to ever wear a mining hardsuit.

**Comment by deltanedas** [comment]
mining hardsuit should be worn for extra protection not because the default suit has a laughably bad light

**Comment by buntobaggins** [comment]
> Carry a floodlight or flares from the salvage vendor. This removes pretty much the only reason to ever wear a mining hardsuit.

The problem with flares and flashlights is that they will run out of power fairly quickly and also take up a hand or pocket slot to use. This isn't that big a deal but it can just be annoying. The only down side to this change would be that flashlights would become obsolete since the salv suit would provide the same light with infinite battery but I don't think this is really a bad thing since salv should have better light options then the flashlight. Right now I just find dealing with lights as salv to be to annoying without really adding anything meaningful to the gameplay loop.

**Pull request merged**
