### PR TITLE
Gas Masks, Oxygen Tank Correction, and Correct Fills for lockers and survival boxes 

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
Added multiple gas mask variants,
Fixed Survival boxes and their fills, for jobs like engineering and security
Fixed emergency gas tanks being incorrectly named and sized

**Screenshots**

image

**Changelog**

:cl: Daemon
- add: Added several gas mask variants
- tweak: Tweaked Survival Boxes
- tweak: Tweaked Locker Fills

### CODE REVIEW

**Comment by Emisse** [comment]
can you add heat protection to the atmos gas mask

**Comment by ZeroDayDaemon** [comment]
> can you add heat protection to the atmos gas mask

Yeah, am going to, as well as the captain and centcom one

**Comment by Emisse** [comment]
probably just do .9 on them

**Comment by ZeroDayDaemon** [comment]
> probably just do .9 on them

20 heat armor on /tg/ that would be 0.20? i have no idea what the conversion is

**Comment by Emisse** [comment]
that would be .8 here

**Comment by Emisse** [comment]
it basically multiplies that damage type by the coefficient, so the lower your decimal the greater the damage reduction. deathsquad for reference is all .2 which is 80% reduction, captains carapace is .5 which is half, etc etc

**Comment by Emisse** [comment]
yea they look good now

**Comment by ZeroDayDaemon** [comment]
DNM yet

**Comment by ZeroDayDaemon** [comment]
Ready for review

**Pull request merged**
