### PR TITLE
TG Vending Machines + Tweaks

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds some tg vending machines and fixes small inconsistencies related to vending machines

**Media**

prthumb3

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added 11 new food/drink vending machines.
- add: Added Robotech Deluxe filled with robotics equipment.
- add: Added CentDrobe filled with centcom drip.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
More food/drink vendors is good, but I'd rather you split up the original vendors' stock between the multiple machines rather than just duplicating it.

**Comment by potato1234x** [comment]
done

**Comment by Emisse** [comment]
MAKE BIG NUMEBR SMALLER SO MAKE 8>2 AND STHIT WE ARE TRYING TO REDUCE TOTAL VEND CONTENT THANK YOU

**Comment by Emisse** [comment]
QUANTITY AND TYPES

**Comment by potato1234x** [comment]
would 4 or 3 be alright for the unique drinks? i want to make it obvious that the product is unique to that machine

**Comment by Emisse** [comment]
SUR

**Comment by potato1234x** [comment]
done

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
approve

**Pull request merged**
