### PR TITLE
Shoe Admeme

### PR DESCRIPTION
**Pull request by MaloTV**
## About the PR

Added Mob that is Hostile against Arachnids with admeme Suffix

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
icon
:cl: MaloTheDuck
- add: Added Shoe Enemy the Natural Enemy against Spiders [Admeme]!

Fear

### CODE REVIEW

**Comment by MaloTV** [comment]
Forgot to change the licence

**Comment by Segonist** [comment]
amazing

**Comment by MaloTV** [comment]
> amazing

I am the strugel why is github so complicated AHHHHHHHHHHHHHHHHHHHHHHH

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Admemes should be prototype uploaded or go in the RSI dump not in the main repo, see what another maint thinks.

**Comment by potato1234x** [comment]
amazing

**Comment by Partmedia** [comment]
Thank you for your contribution. While this is funny, I don't think that this is a good fit for the main game at this time. Game admins can of course, still upload temporary prototypes if they wish to use it, and of course, some forks may welcome this addition.

**Comment by AJCM-git** [comment]
> Admemes should be prototype uploaded or go in the RSI dump not in the main repo, see what another maint thinks.

I agree with Sloth and Partmedia, i think enough maints have given their opinion, closing

**Pull request closed without merging**
