### PR TITLE
WATTAGE IS NOT A UNIT OF STORED ENERGY

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by Simyon264** [comment]
peak PR

**Comment by deltanedas** [comment]
blessed

**Comment by Moomoobeef** [comment]
you could have changed it to KWh, but that works too ig

**Comment by osjarw** [comment]
> you could have changed it to KWh, but that works too ig

Those units are kinda too big, I think APCs contain like 0.0139 KWh

**Comment by deltanedas** [comment]
kwh vs 3600kj who would win

**Pull request merged**
