### PR TITLE
 Add skeleton as round-start species

### PR DESCRIPTION
**Pull request by SansTheSkellyCrew**
I believe Skeleton is balanced and should be playable. It is beginner friendly, I personally hate the hunger, thirst and oxygen mechanics of the game.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Halloween was last october bruh

April fools on the other hand...

**Comment by Dragonjspider** [comment]
Skeleton is not really balanced... they can just go into spaced areas for no cost...

**Comment by SansTheSkellyCrew** [comment]
Keeping Skeletons for just Halloween seems like developers can't come up with other ideas for Halloween

**Comment by SansTheSkellyCrew** [comment]
> Skeleton is not really balanced... they can just go into spaced areas for no cost...

they can't be revived if they actually die and can't be healed with chems

**Comment by LordEclipse** [comment]
> > Skeleton is not really balanced... they can just go into spaced areas for no cost...
> 
> they can't be revived if they actually die and can't be healed with chems

They can be healed with milk.

**Comment by Dragonjspider** [comment]
Sure not being able to be revived is a fair point, but the New Life Rule doesn't apply to them, since they're left as a skull on the ground, I can imagine a lot of syndies getting outed for that, which doesn't sound fun to me personally.

I love playing a skeleton, but I think skeletons should be left as a limited thing personally.

**Comment by SansTheSkellyCrew** [comment]
> Sure not being able to be revived is a fair point, but the New Life Rule doesn't apply to them, since they're left as a skull on the ground, I can imagine a lot of syndies getting outed for that, which doesn't sound fun to me personally.
> 
> I love playing a skeleton, but I think skeletons should be left as a limited thing personally.

Perhaps can just make a specific rule for that?

**Comment by metalgearsloth** [comment]
Go to ideaguys.

**Pull request closed without merging**
