### PR TITLE
Speedloader fix

### LINKED ISSUE #9896: Speedloaders don't Speedload
## Description

Name explains itself. The only way to use the "speed"loader in its current state is to unload it, and put every bullet in the gun manually. I don't call that speedloading. 
Happy 1000th open issue

**Reproduction**

Get a revolver (any revolver, as long as it has a speedloader)
Get a speedloader for said revolver
Unload revolver
Attempt to use speedloader on revolver
If done correctly, the speedloader will do absolutely nothing. 

**Additional context**

This has been an issue ever since the gun rework I believe, but... Nobody's reported the issue. This says a lot about our society

### PR DESCRIPTION
**Pull request by PixelTheKermit**
## About the PR 
The speed loaders didn't work for a while, so I decided to fix it because it's better than manually putting every bullet in
Closes #9896

**Screenshots**

https://user-images.githubusercontent.com/85175107/200184560-89a9575b-b60e-4aed-8b55-2e11aed9971f.mp4

**Changelog**

:cl: PixelTK
- fix: After a very long time, speed loaders have finally been fixed.

### CODE REVIEW

**Review by Mervill — CHANGES_REQUESTED** [review]
It looks like I still can't load the `WeaponSniperMosin` using `SpeedLoaderLightRifle`

Also, the syndicate ammo menu needs to be updated to provide `SpeedLoaderLightRifle` along with this change instead of `MagazineLightRifle` as it is currently.

Add 'Closes #9896' to your OP so it auto-closes the related issue when this is merged.

**Comment by PixelTheKermit** [comment]
> It looks like I still can't load the `WeaponSniperMosin` using `SpeedLoaderLightRifle`.
I'll try fixing this later today, since I cannot do it right now

**Comment by PixelTheKermit** [comment]
Right time to fix this

**Comment by PixelTheKermit** [comment]
I cannot figure this shit out

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
SpeedLoader should transfer everything

**Comment by PixelTheKermit** [comment]
> SpeedLoader should transfer everything

11pm brain cannot understand right now, please elaborate

**Comment by PixelTheKermit** [comment]
The revolver in the video can only contain 5 bullets, while the speedloader has 6 bullets. That's why all the bullets aren't transfered if that's what you're talking about

**Pull request merged**
