### PR TITLE
rename SmokeDissipateSpawn to SpawnOnDespawn

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
renames SmokeDissipateSpawnComponent to SpawnOnDespawnComponent since it has nothing to do with smoke

## Why / Balance
having SmokeDissipateSpawn in a random things yaml would seem wrong now its clear that its fine

## Technical details
works same way as before

## Media
foam reactions dont exist
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
renamed `SmokeDissipateSpawnComponent` to `SpawnOnDespawnComponent`

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Partmedia** [comment]
I'm inclined to close this because this is a real breaking change that impacts all forks that brings very little benefit. Unless you're willing to personally go audit and fix all forks, I think this would be better addressed by better documentation in the component.

**Comment by deltanedas** [comment]
- mining station doesnt have it at all in content or prototypes
- unrebased deltav content and prototypes are same as here
- corvax content and prototypes are same as here

any others you think it might affect

**Comment by Partmedia** [comment]
> * mining station doesnt have it at all in content or prototypes
> 
>     * unrebased deltav content and prototypes are same as here
> 
>     * corvax content and prototypes are same as here
> 
> 
> any others you think it might affect

Okay, I'm satisfied if you do an audit. Could you please check Pirata and N14 and a few other random samples of forks in #forks-advertisement?

**Comment by deltanedas** [comment]
- nuclear 14 same as here
- pirata doesnt have it at all
- stationware same as here
- frigid doesnt have it at all

**Review by Partmedia — APPROVED** [review]
Given your audit, this breaking change is fine.

**Pull request merged**
