### PR TITLE
Add Changeling antagonist

### PR DESCRIPTION
**Pull request by Arctic-Husky**
## About the PR

The Syndicate now has another weapon in their arsenal, the infamous Changeling!

**List of currently implemented features:**

- DNA Sting, the changeling can use this action on another player to get their DNA
- Transform: the changeling can change its physical structure to that of another person whose DNA they have obtained (still implementing, didn't mess with UI stuff yet)
- Evolution Menu: the changeling can open a store and spend 10 points (configurable) on abilities that they will use throughout the round
- Arm Blade: the changeling can mutate one of their arms to become a sharp blade capable of prying open doors like a crowbar
- Absorb DNA: the changeling can absorb all of the DNA of the victim, making them become a DNAless husk (still implementing that last part)

**Plans for features:**

I plan to implement most or all of the features that TG's changeling has.
Reference: https://tgstation13.org/wiki/Changeling

**Media**

- [ ] I have added videos to this PR showcasing its changes ingame

DNA Sting, Absorb, Transform abilities showcase
https://youtu.be/LDBqbl0Sn6U
[link to video](https://www.youtube.com/watch?v=LDBqbl0Sn6U)

Changeling Shop and Arm Blade abilities showcase
https://youtu.be/ox7Hy8k995M
[link to video](https://www.youtube.com/watch?v=ox7Hy8k995M)

**Changelog**

:cl:
- add: Introducing the Syndicate's latest weapon: the Changelings, masters of shape-shifting prowess.

### CODE REVIEW

**Comment by Arctic-Husky** [comment]
Hi, I want to ask a question about a script that I had to use from the Polymorph system (https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Polymorph/Systems/PolymorphSystem.Map.cs). This script is going to be very useful for my implementation of the "Transform" ability, because it will work a lot like how polymorphs currently work, with the pauses map. I tried using this class to access these methods, but noticed they are private, so I had to create a copy of this script for my own system for it to work (ChangelingSystem.Map.cs). However, reusing code like that isn't really good practice, so I want to ask how I should approach this problem. Should I extract this part of the class to be something of its own and have both systems use it?

**Comment by fidso** [comment]
BRAZIL CAMPEAO PENTA NUMERO UNO 🇧🇷 🇧🇷

**Comment by moonheart08** [comment]
This feature is large enough that a design doc is **required**, and additionally "tg did it" is generally not accepted design reasoning here, so you'll need to support and evaluate every feature changelings have that you implement.

**Comment by moonheart08** [comment]
> I want to ask a question about a code snippet that I had to use from the Polymorph system (https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Polymorph/Systems/PolymorphSystem.Map.cs). This snippet is going to be very useful for my implementation of the "Transform" ability, because it will work a lot like how polymorphs currently work, with the pauses map. I tried using this class to access these methods, but noticed they are private, so I had to create a copy of this script for my own system for it to work (ChangelingSystem.Map.cs). However, copying code like that isn't really good practice, so I want to ask how I should approach this problem. Should I extract this part of the class to be something of its own and have both systems use it?

What prevents you from adapting/expanding Polymorph?

**Comment by EmoGarbage404** [comment]
Id probably create some kind of class that PolymorphPrototype inherits from. Kinda like how StoreListing does it. That way, you can just store/specify all the info in there.

**Comment by Arctic-Husky** [comment]
> This feature is large enough that a design doc is **required**, and additionally "tg did it" is generally not accepted design reasoning here, so you'll need to support and evaluate every feature changelings have that you implement.

Thank you for your feedback. I will make sure to provide a design document and include each feature that I plan to implement for the Changeling.

**Comment by Arctic-Husky** [comment]
> What prevents you from adapting/expanding Polymorph?

I just wanted know your opinions on this before messing with it!

> Id probably create some kind of class that PolymorphPrototype inherits from. Kinda like how StoreListing does it. That way, you can just store/specify all the info in there.

Interesting idea, I'll look into that!

**Comment by malchanceux** [comment]
An arm blade item [already exists](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml), as well as [chitinous armor](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml#L195)

Judging by how you named the changeling armblade "TrueArmBlade" I assume this is intentional?
image

**Comment by Arctic-Husky** [comment]
> An arm blade item [already exists](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml), as well as [chitinous armor](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml#L195)
> 
> Judging by how you named the changeling armblade "TrueArmBlade" I assume this is intentional? image

It is intentional! Before making this PR, I was developing everything in another downstream, and didn't want to mess with the original arm blade prototype, as its missing a component, and I wanted to avoid having merge conflicts if upstream changed it. Now that I separated the code from that repo, I can change it and probably will do so

**Comment by metalgearsloth** [comment]
Re-open if you get a chance on discord.

**Pull request closed without merging**
