### PR TITLE
Barratry

### PR DESCRIPTION
**Pull request by Emisse**
almost no more reinforced walls
removed almost all vending machines
most lights have been removed
all lights have been removed from maintenance
many firelocks have been removed
all gamer gear has been removed
trash has been amplified 
dirt has been amplified
atmos has been scalped
chemistry has had chem dispensers removed
medical beds have been removed
any beneficial technology around the map has been removed
defibs have been reduced by 80%
skub

### CODE REVIEW

**Comment by Emisse** [comment]
sad render isnt updated

**Comment by Tunguso4ka** [comment]
sounds horrifying.

**Comment by UbaserB** [comment]
this is going to traumatise me

**Comment by mirrorcult** [comment]
barratry 3

**Comment by deltanedas** [comment]
finally fuck firelocks

**Comment by GoodWheatley** [comment]
the cooler barratry

**Pull request merged**
