### PR TITLE
uncomment cl template

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
uncomment the changelog template :trollface:

## Why / Balance
pros keep leaving out :cl: or not formatting it right

## Technical details
no

## Media
merge and open new pr :trollface:
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by Partmedia** [comment]
I don't think this is a good idea. "Pros" can still continue to not format it right, except now that PRs with the default Changelog (like this one) will inevitably get merged and show up in the Changelog.

**Comment by deltanedas** [comment]
there is no :cl:

**Comment by Interrobang01** [comment]
We could have one of those "[X] I have read and agreed..." boxes for the changelog so people pay more attention.

Or we could move the add/remove/tweak/fix examples to the comment above the :cl: so leaving it as the default wouldn't do anything. Examples of proper usage of the changelog could be provided as comments or in the linked documentation.

**Comment by Partmedia** [comment]
There were a lot of alternatives discussed and rejected in [#18900](https://github.com/space-wizards/space-station-14/pull/18900). Please take a look at the discussion there.

**Comment by deltanedas** [comment]
pro

**Pull request closed without merging**
