### PR TITLE
Moving Target

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Added a moving target to the secfab
## Why / Balance

Fun for target practice!
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

https://github.com/space-wizards/space-station-14/assets/149967078/277e7d3a-f418-4bf4-b7a2-b84f23f247e3

:cl:
- add: Added a moving target to the secfab.

### CODE REVIEW

**Comment by Kadeo64** [comment]
is it cognizinable?

**Comment by TheShuEd** [comment]
It should be possible to turn it on and off.  And it should have a different sprite.  anything with wheels or chassis.

**Comment by Kadeo64** [comment]
> It should be possible to turn it on and off. And it should have a different sprite. anything with wheels or chassis.

would be funny if it was just the normal target but with roller skates

**Comment by Boaz1111** [comment]
> is it cognizinable?

No

**Comment by Boaz1111** [comment]
> It should be possible to turn it on and off.  And it should have a different sprite.  anything with wheels or chassis.

Not sure how I can do that without making a whole new toggleable random walk component

**Comment by deltanedas** [comment]
pro idea just have conveyors able to move targets then have conveyor loop in target practice area

**Comment by Kadeo64** [comment]
> pro idea just have conveyors able to move targets then have conveyor loop in target practice area

go ping emisse then

**Comment by Boaz1111** [comment]
> pro idea just have conveyors able to move targets then have conveyor loop in target practice area

I believe they can when unanchored, but this has erratic movement, which is good for practice(players move erratically too)

**Comment by EmoGarbage404** [comment]
this really just looks kinda janky

**Comment by metalgearsloth** [comment]
RandomWalkController is really not built for mob movement (it assumes the target is a dynamic body not KC) and is pretty bad anyway.

**Pull request closed without merging**
