### PR TITLE
Set the Medical Scanner to Climbable

### LINKED ISSUE #7038: Vaulting effect missing from Scanner and Cloner
## Description
Vaulting effect missing from Scanner and Cloner when exiting them. Resulting in people getting stuck and need someone to come wrench them free
**Screenshots**

**Additional context**
Luv u

### PR DESCRIPTION
**Pull request by themias**
## About the PR 

- The medical scanner was missing the 'climbable' token
- Resolves #7038

**Screenshots**

**Changelog**

:cl:
- fix: The medical scanner is now climbable

### CODE REVIEW

**Comment by themias** [comment]
It looks like they both still have collision. I can update the collision to fix the issue then.

**Comment by themias** [comment]
> IMO cloners / scanners just shouldn't collide with mobs which might already be fixed on master?

Sorry to ping, but I don't have privilege to add reviewers. Just want to let you know I've made the change if you want to review.

**Comment by moonheart08** [comment]
The actual fix for this used to be they were vaultable. Just make them vaultable again and have people ejected from them automatically vaulting.

**Comment by themias** [comment]
Both the scanner and cloner use ClimbSystem.ForciblySetClimbing() to set the ejected entity to isClimbing mode, so in that sense this is already fixed.
The only difference is that medical scanner was missing Climbable.

I don't think the Climbable token is needed for the ForciblySetClimbing() to work, but it would probably be best to have if a player was disoriented and walked into a stuck position behind it and needed to manually vault to get back out.

**Pull request merged**
