### PR TITLE
Adds nitrile gloves to syndie medical bundle

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

the syndicate surgery bundle now contains a pair of nitrile gloves, the nukie medical bundle now also contains nitrile gloves instead of latex ones
## Why / Balance

futureproofing, fingerprint removal and emisse asked me to remove the MMI (sad)
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
no cl because minor addition

### CODE REVIEW

**Comment by metalgearsloth** [comment]
are you powercreeping again

**Comment by JoeHammad1844** [comment]
dad gave me the belt last time

**Comment by Holinka4ever** [comment]
It doesnt seems nessesary bad, i mean, what is powercreeping? Giving powerfull items, that can drasticly change balance around them/their user.

So in defence for joe... its feels like a joke, rather than thing that can do something valid. 

Only thing is giving a pain, that metacurity will be curios if you see with MMI outside the science in you bag.

**Comment by HerCoyote23** [comment]
Not sure I like this. 
First off, power creeping is slowly and repeatedly buffing things, not one big buff.

Also I feel like the uplink shouldn't have access to everything on the station. By putting MMI in the uplink, you're sorta discouraging tators from interacting with the crew and stealing/asking for an MMI. Instead they just buy it and that much interaction is lost.

**Comment by JoeHammad1844** [comment]
> Also I feel like the uplink shouldn't have access to everything on the station. By putting MMI in the uplink, you're sorta discouraging tators from interacting with the crew and stealing/asking for an MMI. Instead they just buy it and that much interaction is lost.

it's 4TC and its a bundle, its meant to have everything you need medically and most people will just ask for an MMI instead of blowing nearly a quarter of their TC on it

**Comment by Emisse** [comment]
remove mmi from bag

**Comment by JoeHammad1844** [comment]
okay then

**Comment by JoeHammad1844** [comment]
it is done

**Comment by JoeHammad1844** [comment]
wait, im going to add a rollerbed

**Comment by JoeHammad1844** [comment]
okay good to go (bloodred roller bed when)

**Pull request merged**
