### PR TITLE
pinpointer can now be reconfigured. any pinpointer can't be emagged

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

removed `OnEmagged` method for pinpointer
now all pinpointers except ninja (it literally only needs it to find a station) can be reconfigured

## Why / Balance

The pinpointer was very rarely what the emag was applied to, also according to #8524 we should abbreviate EMAG INTERACTIONS.
this pinpointer change, in my opinion, would make it more interesting, and the objective of **hidden** disk theft would become at least somewhat real.
## Technical details

Now according to the standard:
`UpdateTargetName = true`
`CanRetarget = true`
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Any pinpointer can't be emagged
- tweak: Now the regular pinpointer can be reconfigured to a different object

### CODE REVIEW

**Comment by deltanedas** [comment]
emagging pinpointer is essential when you are given code to your own nuke rather than the stations

**Comment by Golinth** [comment]
> emagging pinpointer is essential when you are given code to your own nuke rather than the stations

thats why the normal pinpointer in the nukie shuttle exists, and as far as I can tell, this still allows that one to be reconfigured to point at the nuke

**Comment by icekot8** [comment]
> emagging pinpointer is essential when you are given code to your own nuke rather than the stations

done.

**Comment by MACMAN2003** [comment]
hopefully there's an option to swap it back to the disk

**Comment by icekot8** [comment]
> I think nuclear ops pinpointer shouldn't be free to reconfigure to anything either, given that it might break their ability to find the nuclear disk

actually, I thought so too initially, and the ops shuttle has a regular pinpointer. it was just the delta comment that influenced my decision.

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by icekot8** [comment]
can defrost?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Normal pinpointers should not be able to be reconfigured, if nukies need it either spawn it or update it as required.

**Comment by slarticodefast** [comment]
If you want to continue working on this, leave a comment and I'll re-open the PR.

**Pull request closed without merging**
