### PR TITLE
Adding new Cryogenics Reagent - Opporozidone (Attempt 2)

### PR DESCRIPTION
**Pull request by Gotimanga**
## About the PR
Added a new, cryogenics chemical for Chemistry to synthesize: Opporozidone. This chemical can reverse rot that has accumulated on patients making them revivable again, if used under the right conditions.
image

## Why / Balance
I fell that the only option for revival after the current time to rot (10 minutes) should not just be borging. This method will allow medics to reverse rotting in patients allowing them to be defibbed and revived - unlike cloning, you don't just hit a button and the patient is healthy either, you will still need to heal the patient afterwards.

In terms of balance, this chemical will require co-operation between regular medics, chemists, and botanists as well as cargo in terms of supplying plasma (It is consumed, not a catalyst) and Carpotoxin. It will also require some level of knowledge in terms of cryogenics and rotting. 

I have created a new PR instead of fix the old one because the issues that were being raised were difficult to fix

## Technical details
~~Added "MetaboliseWhileDead" data field to reagent prototype~~
Added  "ReduceAccumulator" method to RottingSystem

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes in game, **or** this PR does not require an in game showcase

**Changelog**
:cl:
- add: Chemists can now create opporozidone, which reverses the effects of rotting in deceased patients while in cryo.

### CODE REVIEW

**Comment by Gotimanga** [comment]
Ready for review

**Comment by Partmedia** [comment]
Linking the old comments thread because it still may be relevant: https://github.com/space-wizards/space-station-14/pull/21839

I'm going to bring this up for additional comments from Discord.

**Comment by Kukutis96513** [comment]
Doesnt cryox and doxarubixadone start working at around 213k and not 150k? kind of strange for this to require 150k temperature unlike the other cryo meds..

**Comment by Gotimanga** [comment]
> Doesnt cryox and doxarubixadone start working at around 213k and not 150k? kind of strange for this to require 150k temperature unlike the other cryo meds..

This PR was originally made before #22785 which raised the minimum threshold - the temperature used to be 150k. While this wouldn't have too many effects due to the patient not being alive (the original reason for the aforementioned PR was because patients in critical condition died before they were cold enough to metabolise the drug), even the recently introduced cryogenic drugs like Aloxadone and Necrosol share the same threshold, so I will be changing this soon. Thank you for mentioning it :)

**Comment by superjj18** [comment]
Would the term "Mob" be the right word to use as an IC examination text?

**Comment by Kukutis96513** [comment]
> Would the term "Mob" be the right word to use as an IC examination text?

I think that part is in the guidebook and is OOC?

**Review by mirrorcult — APPROVED** [review]
on design i suppose lets just see how it goes. more crew power at the high end is probably fine

**Comment by mirrorcult** [comment]
needs non-IC changelog, will just edit myself

**Pull request merged**
