### PR TITLE
Implement shuttle crushing

### PR DESCRIPTION
**Pull request by metalgearsloth**
TODO:
- Need to implement damage over time for small collisions
- Gibbing / deletion threshold for bigger collisions

:cl:
- add: You can now crush things between shuttles

### CODE REVIEW

**Comment by PaulRitter** [comment]
smh i thought we said no erp content

**Comment by metalgearsloth** [comment]
Will undraft when it's ready

**Comment by moonheart08** [comment]
the return of the king

**Comment by metalgearsloth** [comment]
Working on NPCs a bunch more so will re-open in a few weeks

**Pull request closed without merging**
