### PR TITLE
Removes autodrinking

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

This is a quick and easy PR to disable autodrink until a better solution is decided upon. Instead of waiting for the best solution, I figured that it would be a good idea to get something out now and improve it later.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Centcom has agreed to temporally disable the vacuums on drinks for now.

### CODE REVIEW

**Comment by mirrorcult** [comment]
yeah people seem to really hate this think we just need a better solution

**Comment by OctoRocket** [comment]
I see how it could be useful if you want to get a drink out of a vending machine and just need to drink something, but in mrp situations it is very useful to be able to drink slowly.

**Comment by Emisse** [comment]
i do like shlorpin at my own speed

**Review by keronshb — CHANGES_REQUESTED** [review]
#15434 is the preferred fix for this at the moment, unless you add item cooldowns to food/drink in this PR.

**Comment by Myakot** [comment]
I've seen quite a lot of people complain that they accidentally drank copious amounts of meds, while they only intended to sip once.
Is it possible to make auto drink toggle able?

**Comment by PixelTheKermit** [comment]
Why do we need auto drinking again?

**Comment by DogZeroX** [comment]
This seems like just some TG gamer tier thing, don't like it personally.

**Comment by HoidC** [comment]
> #15434 is the preferred change for this at the moment, unless you add item cooldowns to food/drink in this PR.

Why is this the preferred change?

It is kind of unintuitive to have to click twice to stop drinking something and instead chug the whole thing - and even then, I don’t really see why auto drinking and eating needs to exist, other than thatIt’s good QOL; however, I don’t think it should be the default. Many, many players I’ve played with recently agree that this sucks, especially on Salamander.

I can see the use of auto drinking but I don’t think it should exist until it’s either toggleable or isn’t the default - so for example your preferred solution PR inverts things so it’s two clicks to autodrink.

**Comment by VasilisThePikachu** [comment]
Idea: Pressing use once let you drink/eat like before. HOLDING down use autodrinks/eats

**Comment by OctoRocket** [comment]
> #15434 is the preferred change for this at the moment, unless you add item cooldowns to food/drink in this PR.

The idea is to have this be merged as a quick fix, and then enhance the behavior later.

**Comment by OctoRocket** [comment]
I think that a single drink should be the default behavior. and double clicking should autodrink, but that is not for this PR.

**Comment by keronshb** [comment]
> > #15434 is the preferred change for this at the moment, unless you add item cooldowns to food/drink in this PR.
> 
> Why is this the preferred change?
> 
> It is kind of unintuitive to have to click twice to stop drinking something and instead chug the whole thing - and even then, I don’t really see why auto drinking and eating needs to exist, other than thatIt’s good QOL; however, I don’t think it should be the default. Many, many players I’ve played with recently agree that this sucks, especially on Salamander.
> 
> I can see the use of auto drinking but I don’t think it should exist until it’s either toggleable or isn’t the default - so for example your preferred solution PR inverts things so it’s two clicks to autodrink.

We're experimenting with how repeated doafters could be applied and currently food and drink are the best way to test because tools are nowhere near ready yet to accept it. People want a cancel button for the repeat so hitting the button twice is the better solution than to comment it out. A user pref is on the horizon but not ready yet.

There are some cases where we found that having an item cooldown would be better than a doafter. Depends if they're on self vs other, how short they are, etc. Food and Drink (for self) is a candidate for that and will be the accepted solution.



> > #15434 is the preferred change for this at the moment, unless you add item cooldowns to food/drink in this PR.
> 
> The idea is to have this be merged as a quick fix, and then enhance the behavior later.

This is not game breaking and it's not the accepted quick fix. Please make the changes requested.

**Comment by OctoRocket** [comment]
> We're experimenting with how repeated doafters could be applied and currently food and drink are the best way to test because tools are nowhere near ready yet to accept it. People want a cancel button for the repeat so hitting the button twice is the better solution than to comment it out. A user pref is on the horizon but not ready yet.

Why not this https://github.com/space-wizards/space-station-14/pull/15613 ?

**Comment by OctoRocket** [comment]
Also, if this is not the accepted quick fix what is? It seems like most people want it gone for drinks entirely or to have it activate depending on a key combination or something else. I personally don't think that repeatable doafters work well for drinks at all and would rather have it removed entirely.

**Comment by keronshb** [comment]
> > We're experimenting with how repeated doafters could be applied and currently food and drink are the best way to test because tools are nowhere near ready yet to accept it. People want a cancel button for the repeat so hitting the button twice is the better solution than to comment it out. A user pref is on the horizon but not ready yet.
> 
> Why not this #15613 ? Also yes it is a better solution, but this solution is ready right now, and the other one isn't last time I checked.

That still needs to be reviewed and to check to see what healing items it effects.

This solution is just not going to be accepted unless the changes are made to remove it and replace it with an item cooldown.

**Comment by OctoRocket** [comment]
Considering there is another solution waiting to be merged and that changing the doafters to be cooldowns is much to hard for me to do with my limited c# knowledge, I will be closing this PR. I hope that there is some change to the behavior soon.

**Comment by deltanedas** [comment]
to be a cooldown give it UseDelayComponent and _useDelay.BeginDelay(uid, useDelay); after checking _useDelay.ActiveDelay(uid, useDelay) (for self drinking only)

**Comment by OctoRocket** [comment]
To be honest, I am not really focused on this PR at the moment as many other people have taken interest in this themselves. I will not being updating this PR with new updates.

**Pull request closed without merging**
