### PR TITLE
The return of the 'long bedhead' haircut as an alternative

### PR DESCRIPTION
**Pull request by ImRenQ**
## About the PR
Added back the 'old' sprite of long bedhead haircut as a secondary choice to the current long bedhead.

## Why / Balance
The new sprite (#19298) haircut is very different from the original

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
long_bedhead

**Changelog**
🆑 RenQ
- add: brought back the classic long bedhead as an alternative to the current one.

### CODE REVIEW

**Comment by UbaserB** [comment]
my friend actually wanted it back too

**Comment by pharmacreep** [comment]
still don't get why we can't jus have tha new n old styles at tha same time to hush both crowds

**Comment by PJB3005** [comment]
> still don't get why we can't jus have tha new n old styles at tha same time to hush both crowds

That is literally what this PR does.

**Review by PJB3005 — APPROVED** [review]

**Review by Tayrtahn — APPROVED** [review]

**Comment by pharmacreep** [comment]
> > still don't get why we can't jus have tha new n old styles at tha same time to hush both crowds
> 
> That is literally what this PR does.

no i mean all hairstyles that got replaced, wait a while from now n youll see another pr up about reintroducing tha old haircuts

**Pull request merged**
