### PR TITLE
Nerf bombsuit helmet

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR
Bombsuit helmet offers too much protection against explosives, this nerfs it. 

## Why / Balance
Being able to survive a china lake with just a bombsuit helmet on and nothing else is odd. Also, a naked person with just a bombsuit helmet won't gib from a hardbomb with the current values. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Reduced the bombsuit helmet's explosive resistance.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
2 things
- is the combination of the helmet and suit still strong enough after you only nerf the helmet?
- is it worth making into an action to put on rather than keeping it a single item? (Its probably prefered to keep as is since it's not really connected to the suit)

**Comment by liltenhead** [comment]
Yeah the bombsuit is 85% explosive resist. It is enough resistance to not even die to the hardbomb, it just crits you. I mean you'll still die from it anyways but it's still really strong on its own. 

And yeah I don't think making it attached to the suit would be too fitting.

**Comment by QuietlyWhisper** [comment]
I doubt bombsuits are realistically strong enough to avoid that much damage anyway, so long as you can be recovered with enough time to be healed, I can see why youd still want to use a bomb suit aside from avoiding being gibbed

**Comment by Slava0135** [comment]
0.2 * 0.9 = 0.18, basically just 2% extra explosion resistance with full suit - not very worth it.
maybe make it 0.75 => 0.2 * 0.8 = 0.15, 5% extra protection when wearing with suit.

**Comment by MiraslauKavaliou** [comment]
A lot of these types of issues would be fixed with a body part damage system, such as your head surviving without your body surviving

**Comment by liltenhead** [comment]
> 0.2 * 0.9 = 0.18, basically just 2% extra explosion resistance with full suit - not very worth it. maybe make it 0.75 => 0.2 * 0.8 = 0.15, 5% extra protection when wearing with suit.

I mean that's fine, but the bombsuit on its own is more than enough anyways. But the bombsuit currently is 85% reduction so I'm not entirely sure what you're asking for here.

**Pull request merged**
