### PR TITLE
Magazine name renamed to be more specific

### PR DESCRIPTION
**Pull request by BulletGrade**
## About the PR 
Made magazine names more specific
eg. SMG magazine (.35 auto top-mounted) was renamed to WT550 magazine in order to make it more clear that the magazine is exclusive to WT550.

**Screenshots**

**Changelog**

:cl:
- magazine box (.30 rifle) renamed to L6 SAW magazine box (.30 rifle)
- magazine (.40 magnum) renamed to Lamia magazine (.40 magnum)
- SMG Magazine (.40 magnum) renamed to Drozd magazine (.40 magnum)
- magazine (.35 auto) renamed to Pistol magazine (.35 auto)
- high-capacity magazine (.35 auto) renamed to Machine Pistol magazine (.35 auto)
- SMG magazine (.35 auto top-mounted) renamed to WT550 magazine (.35 auto top-mounted)

EDIT: Worth noting that most of these changes are from Timrod's suggestions in #3679.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
I don't think this is the right way to tackle this.

The optimal way would be editing the descriptions of the guns themselves and saying what caliber or magazine type they use.

**Comment by Peptide90** [comment]
> I don't think this is the right way to tackle this.
> 
> The optimal way would be editing the descriptions of the guns themselves and saying what caliber or magazine type they use.
> 
> You can leave the WT550 mag name the same tho.

Personally I think less is more. As in it should be simplified down to one magazine or clip for each caliber and that should do all relevant weapons. E.g. having rifles in 556 and 762 variants and they all take the same magazine. Having a 9mm and 556 SMG etc

That way there's a variant between ammo for the two weapons but you're not fumbling with different names and crap just for some ammo. It's not a milsim and the likes of CM can just reimplement it.

**Comment by metalgearsloth** [comment]
> 
> 
> > I don't think this is the right way to tackle this.
> > The optimal way would be editing the descriptions of the guns themselves and saying what caliber or magazine type they use.
> > You can leave the WT550 mag name the same tho.
> 
> Personally I think less is more. As in it should be simplified down to one magazine or clip for each caliber and that should do all relevant weapons. E.g. having rifles in 556 and 762 variants and they all take the same magazine. Having a 9mm and 556 SMG etc
> 
> That way there's a variant between ammo for the two weapons but you're not fumbling with different names and crap just for some ammo. It's not a milsim and the likes of CM can just reimplement it.

This was the already simplified version from the hackmd compared to the original.

With that being said these should probably be dynamically generated.

**Comment by SweptWasTaken** [comment]
I think this is a good enough solution for now, all things considered. Please un-capitalize stuff like "Machine Pistol" and "Pistol" and it'll be mergeable.

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
