### PR TITLE
Make CLF3 reaction require heating first.

### PR DESCRIPTION
**Pull request by ImWeax**
## About the PR

CLF3 must now be heated to 370K before the reaction takes place

## Why / Balance

A couple reasons
1) Bombs and dangerous reagents should require some level of complexity to make. I know potassium+water bombs still exist but I feel like having 1 dangerous "cold" mix reaction is fine
2) Prevents easy chem bombing by just grabbing and throwing jugs onto the floor in quick succession (chemmasters should be locked behind chem access anyways - but with newmed coming chemistrys role as a whole will be shifting so it will be interesting to see what becomes of the chem machines)
3) This prevents new chemists destroying half of chem as easily by misclicking. It takes intentional actions on the chemists behalf to create a large CLF3 explosion in the middle of the lab.

## Technical details

funny 1 yaml line added
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Weax
- tweak: The CLF3 reaction now requires heating first before you can engulf chemistry in fiery death.

### CODE REVIEW

**Comment by Plykiya** [comment]
I do love blowing up my heater and being unable to make any other chems

**Comment by Dutch-VanDerLinde** [comment]
this makes it impossible to actually get CLF3

**Comment by ImWeax** [comment]
perhaps we should let buckets be pre-heated on a hotplate (or in a microwave). I think you can heat them in microwaves currently. I'll look at what can be heated on hotplates

**Comment by EEASAS** [comment]
are stasis beakers just useless now
or does heated clf3 in a stasis beaker only explode when it lands on the ground?

**Comment by HelpTheSteak** [comment]
"Bombs and dangerous reagents should require some level of complexity to make"

The free 30 stack of uranium plus the grinder in kitchen :godo:

**Comment by PJB3005** [comment]
Not commenting on whether this is a good change or not, but everybody asserting this means you blow up your heater needs to hand in their chemistry license.

**Comment by thebadman4662** [comment]
> are stasis beakers just useless now or can heated clf3 in a stasis beaker still explode when it lands on the ground?

I believe it mixes by spilling on the ground, thats why gravity prevents it mixing.

**Comment by deathride58** [comment]
Honestly it's genuinely surprising that it *didn't* already require heating, considering that's how it's always worked both in SS13 (where the required temp is 424k) and in real life (won't post real-world instructions on how to make it for obvious reasons (it's an extremely dangerous chemical to contain and work with)).

**Comment by thebadman4662** [comment]
Okay, assuming you are a nukie, how do you make CLF3 now? You just make a single beaker and are done for the shift assuming id does not blow hole in floor and gets spaced?

**Comment by deathride58** [comment]
All this PR does is set the minimum required temp for ClF3 to form. So long as the relevant chems are preheated, existing methods for forming ClF3 are unaffected. The only method this affects is grabbing off-the-shelf chlorine and fluorine, and throwing both at the same spot to create an explosion via puddle mixing.

... Also, for the case of being a nukie: please, we beg you to love yourself and consider modular grenades. You can do *so* much more with nades than what you're stuck with when lobbing beakers around. Even the most basic of research into grenadecrafting will have your squad actively thank you.

**Comment by ARMOKS** [comment]
Great change, for the people questioning how to make it you would heat one of the chems to a very high temp, place the chem inside a jug, then add units of the other chem 5 at a time with a dropper, which should work. CLF3 mod nades can be made by combining an exothermic  reaction with the chlorine and Florine, so it should still be possible

**Comment by Tayrtahn** [comment]
> Beakers are used as throwables for a reason, modnades are either on a timer or rely on nukie micro with a remote signaler; beakers at the very least tie the time to reaction of modnades, if not react faster. You use the right tool for the right job.

Sounds like a good argument to add an impact trigger module for modular grenades.

**Comment by EpicJoston** [comment]
I'm not a fan of this change. If this is a response to trying to nerf the Incredibly Balanced CLF3 Explosion Damage (Trademarked, all rights reserved) then I'd be much more in favor of simply nuking the damage. Trying to make CLF3 bombs more difficult to make is not going to balance their absurd explosive power, and I strongly dislike the "nerf everything" attitude SS14 is trending towards.

That being said, chem bomb explosion damage is not OK in its current state and both the CLF3 and Potassium + Water explosions should be made less impactful, just not so nerfed that it might as well not exist.

Making things more annoying to do is not a fun way to balance things.

Of course all this discussion could be made useless with new med, so maybe we should hold off and see what happens then.

**Comment by ImWeax** [comment]
I did more testing here. You are more than capable of making CLF3 without blowing up your heaters with this change - Heat up your reagents separately then go mix them in a bucket in maints - its not terribly difficult. For those saying CLF3 needs a buff after this change, I fully disagree. 50u/50u mix of chlorine/fluorine is more than enough to space a room. If you want to make a CLF3 bomb, use chem grenades and *heat your reagents first*. Or use potassium/water.


> Honestly it's genuinely surprising that it _didn't_ already require heating, considering that's how it's always worked both in SS13 (where the required temp is 424k) and in real life (won't post real-world instructions on how to make it for obvious reasons (it's an extremely dangerous chemical to contain and work with)).

I am tempted to raise the required temp to 424K for continuity for new SS14 players coming across from 13, but as we dont have a way actually monitor temperatures in-game I would say 370K is reasonable. 

Please also note that *the yaml file itself* indicated there was meant to be a mintemp implemented for the CLF3 reaction in the first place, but the reaction likely got missed when reagent temperatures were added. I'll actually remove that comment from the file now also.

**Comment by thebadman4662** [comment]
Will beakers not cool down in the grenades making CLF3 reaction not happen though or it happens only when beaker is empty?

**Comment by ImWeax** [comment]
> Will beakers not cool down in the grenades making CLF3 reaction not happen though or it happens only when beaker is empty?

I don't believe solutions passively cool at the moment. But as ARMOK suggested previously, you could mix it with a reductive recipe (like for sulfuric acid) to generate heat for the explosion.

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
> Honestly it's genuinely surprising that it _didn't_ already require heating, considering that's how it's always worked both in SS13

i left a comment on the original yaml when i implemented it, we just didnt have heating then lol

**Pull request merged**
