### PR TITLE
Adding a new lobby screen, featuring a wrecked medbay

### PR DESCRIPTION
**Pull request by Raccoononi**
## About the PR

Added a new lobby screen that I drew.

## Why / Balance

More loading screen is scientifically proven to be better for eyeballs.
The chems have blown themselves up twice already.
A clown is attempting to cook meth in the rubbles.
The CMO is nowhere to be seen.
Injured people are flooding in because of gunshots in the hallway.
Air itself is getting thin, and so is your tank.
You are a moth.

## Technical details

Enjoy the artwork, I hope you like it.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
-
medbay
image

## Breaking changes

None.

**Changelog**

-add: new loading screen. Please enjoy it with eyeballs.

### CODE REVIEW

**Comment by Raccoononi** [comment]
Please excuse the checks, I have no idea how to use git and this already took 99% of my brain to get onto here.

**Comment by FairlySadPanda** [comment]
And I'll disagree. You don't need to be the most god-tier artist to make SS14 lobby art. I'm not. This clearly tells a story and is appropriate to theme.

**Comment by EmoGarbage404** [comment]
I've un-hidden both comments on this PR.

For people engaging, please remember to stay civil and provide constructive feedback. Do not be rude and try and provide points to help the author identify how they could improve their art. The goal isn't to shut something down, but to try and make it the best that it can be.

Of course, due to numerous reasons, we can't and shouldn't have infinite lobby art. We have to make decisions regarding what can and cannot be included in the game based on the quality of what's proposed.

Even if something doesn't make it into the game, that is not a statement on how good a piece of art is. Still feel free to share it in the #fanart channel or post it on social media.

In any case, just keep things civil and productive.

Thank you.

**Comment by Raccoononi** [comment]
Author here, +1 on the constructive feedback thing, I drew this one pretty quickly and there is no personal offense taken for pointing out where it can be improved and how. Thank you.

**Comment by slarticodefast** [comment]
Personally I love the story this artwork tells.
I have brought this up for discussion with the other maintainers and it was agreed to not include it since we have enough lobby art at the moment. Lobby art has also been added to the list of current freezes. I hope to see you contributing in the future. Thank you.

**Pull request closed without merging**
