### PR TITLE
Buff monkey/kobold cubes box and a lot boxes cleanup and fixes

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

- hatsune miku bag is a really in bag yml now
- some cleaning in boxes
- cube boxes now in Catalog
- give whitelists to boxes that are bigger inside
- standartize boxes id
- give cube boxes 3x3 grid and additional cubes

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Cube boxes now contains 8 cubes instead of 6.

### CODE REVIEW

**Comment by lzk228** [comment]
dunno how to fix, help me pls

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by lzk228** [comment]
reopen please

**Comment by lzk228** [comment]
im gonna split it and reopen

**Pull request closed without merging**
