### PR TITLE
Set TA to 2 hours playtime requirement

### PR DESCRIPTION
**Pull request by Equivocateur**
## About the PR

mlem

## Why / Balance
In light of recent events

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

image

**Changelog**

no

### CODE REVIEW

**Comment by keronshb** [comment]
Please give a better explanation.

**Comment by Equivocateur** [comment]
> Please give a better explanation.

Consistent raids by 0-hour accounts that pick exclusively TA, breaking into places or mass sabotaging roundstart, this causes panic bunkers to be enabled almost every single (other) day.

**Comment by NancokPS2** [comment]
If the issue is 0 hour accounts why not just set it to 1 hour?  
With this logic cadet should also be 2 hours since they have guns.  
Also, breaking into places and mild tomfoolery are not the end of the world, sec can easily deal with it.

**Comment by Equivocateur** [comment]
> If the issue is 0 hour accounts why not just set it to 1 hour? With this logic cadet should also be 2 hours since they have guns. Also, breaking into places and mild tomfoolery are not the end of the world, sec can easily deal with it.

cadets are at 10 hours playtime requirement.

**Comment by Doru991** [comment]
I think this isn't a bad idea even without the raids, since 2 hours is like just one or two shifts and it'd be better for players to get a slight grasp on how the controls and rounds work before getting handed hardsuits and full tool sets

**Comment by keronshb** [comment]
I brought this up and we're not going to go with this change. It's a band-aid fix and not a great one at that. We do have ideas to fix the core issue, but this aint it.

**Comment by Equivocateur** [comment]
> get asked for better explanation, slapped DNM

> provide

> DNM stays

https://discord.com/channels/310555209753690112/770682801607278632/1162479935659704452

**Comment by Equivocateur** [comment]
mfw slapped closed when I was typing

**Pull request closed without merging**
