### PR TITLE
Makes Donut Boxes and Syndicakes use cabinet perspective sprites

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Makes Donut Boxes and Syndicakes use their older SS13 cabinet perspective sprites. Not much else to say.

## Why / Balance
Cabinet perspective, contrary to popular belief, is not completely irredeemable and actually has notable advantages over 3/4th sprites in some situations. Namely, it excels at definition, especially on cubic objects. Being able to see the side of a sprite gives you a good idea of how bulky it's meant to be, and for the donut box and syndicakes this is no exception.

The 3/4th perspective really makes no sense to use here outside of being arbitrarily "correct" since it completely removes any and all definition the items had before. The donut box here is particularly egreigous - it just looks like an ambigious white box, which is not only ugly but also bad for recognizability.

image

## Media
Content Client_fsitfGntaf

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The donut box and Syndicakes now use sprites that give them a more defined shape.

### CODE REVIEW

**Comment by mirrorcult** [comment]
mmmmmmmmmmmm idk if im convinced

**Comment by deltanedas** [comment]
filled donuts box sprite looks bad tbh

**Comment by ItsMeThom** [comment]
I like it! And I agree with your points about the perspective. Good job 👏

**Comment by JoeHammad1844** [comment]
the shading is a lot worse (near non-existant) and they look like they're on the mat_fullbright 1 pill

**Comment by RiceMar1244** [comment]
Criticizing the sprites shown will not be a part of my objection, since its more important to discuss the perspective itself, but I think everything youve mentioned about achieving a bulkier fuller look can be done with something that is front facing, like if it were just tilted down and the top of the donut box was visible. This cabinet perspective only makes it looks like youre on the wrong side of the box sometimes.

**Comment by Luxzhv** [comment]
I'd more say of having some extra darkening to the 3/4th's perspective on both items, or at least having the mosr distant lines being darker. Other then that, I like the 3/4th's style.

**Comment by Flareguy** [comment]
Closing for now, might reopen later.

**Pull request closed without merging**
