### PR TITLE
Update barratry

### PR DESCRIPTION
**Pull request by EEASAS**
## About the PR

updated barratry. thats about everything.
first off, removed the maints katana/murasama since powergamers were just taking it roundstart
revamped the store area
maints changes
and other things that i forgor, sorry.
just see the actual map file in your local server asdfasdf
also it's roughly 2:50AM in the time of making this so i may or have not meseed things up

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
why not move muramasa to the derelict, then you need to be a giga powergamer to get it

**Comment by EEASAS** [comment]
i moved the murasama to that one plasma room with holocarp and turrets

**Comment by deltanedas** [comment]
thats still standard powergamer territory but ok

**Comment by Emisse** [comment]
@Scribbles0 required approval here

**Review by Scribbles0 — APPROVED** [review]
lgtm @Emisse can merge now

**Pull request merged**
