### PR TITLE
DisplayCase add

### PR DESCRIPTION
**Pull request by Deahaka**
## About the PR 
Add displaycase for captain's laser. Less mess in the captain's locker.
**Screenshots**

after some hits

**Changelog**

:cl:
- add: Added displaycase.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
ooh, looks nice

**Review by EmoGarbage404 — APPROVED** [review]
tbqh this should probably be an entitystorage which houses the gun. Having it spawn in when destroyed and create a broken case seems a bit weird. This implementation is probably fine for now, as it would probably require some code changes to EntityStorageSystem

**Comment by KIBORG04** [comment]
it looks plastic not for the ss14 style

**Comment by mirrorcult** [comment]
yeah not sure how i feel on the sprite here, looks too wallening

**Pull request closed without merging**
