### PR TITLE
Better Music (April Fools)

### PR DESCRIPTION
**Pull request by musicmanvr**
## About the PR

Adds objectively better music to the nuke countdown and space ambience.
(This is a joke.)

Selections include:
Atomic Amnesia MMX
Dies Irae
Rhapsody No. 2
The Blue Danube

Some of the stuff doesn't really line up with the nuke explosion, but this is an april fools PR.
## Why / Balance

April Fools!

Does not remove any content, only changes the sound collection.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- fix: Made the Nuke and Space Ambience music objectively better. (April Fools!)

### CODE REVIEW

**Comment by musicmanvr** [comment]
i have literally no idea why this is failing 👎

**Comment by potato1234x** [comment]
copyright still applies during april fools, probably...

**Comment by musicmanvr** [comment]
> copyright still applies during april fools, probably...

protip, i laid out all the copyright stuff with proper info, use yer eyes

**Comment by metalgearsloth** [comment]
> > copyright still applies during april fools, probably...
> 
> protip, i laid out all the copyright stuff with proper info, use yer eyes

As I read it you actually broke their license. You misattributed it as CC-BY-SA-3.0 but they are actually CC BY-NC-ND 3.0 Deed which specifies you may not make derivatives which you said you've done.

**Comment by musicmanvr** [comment]
oops, lemme fix that

**Comment by musicmanvr** [comment]
breach of copyright law has been fixed :trollface:

**Comment by musicmanvr** [comment]
Never rechecked so 🤪

**Pull request closed without merging**
