### PR TITLE
Formal Uniforms

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds formal versions of some clothes

## Why / Balance

Consistency across drobes and more wardrobe choices

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added chem, viro, and genetics formal uniforms.

### CODE REVIEW

**Comment by Flareguy** [comment]
Hello! Thank you for the contribution, but the atmos casual uniform was deliberately designed with being atmos-only in mind - these being flat-out recolors is a fairly boring way to go about this, and they also don't really lend themselves well to other colorschemes.

I'd love to see casual uniforms (or just other alternate uniforms for jobs that don't have them in general!) for other jobs provided they have unique designs, but this ain't it.

**Comment by potato1234x** [comment]
> Hello! Thank you for the contribution, but the atmos casual uniform was deliberately designed with being atmos-only in mind - these being flat-out recolors isn't the way to go about this, and they also don't really lend themselves well to other colorschemes.
> 
> I'd love to see casual uniforms (or just other alternate uniforms for jobs that don't have them in general!) for other jobs provided they have unique designs.

should they just be recolors of the scientist formal uniform or something?

**Comment by Flareguy** [comment]
> > Hello! Thank you for the contribution, but the atmos casual uniform was deliberately designed with being atmos-only in mind - these being flat-out recolors isn't the way to go about this, and they also don't really lend themselves well to other colorschemes.
> > I'd love to see casual uniforms (or just other alternate uniforms for jobs that don't have them in general!) for other jobs provided they have unique designs.
> 
> should they just be recolors of the scientist formal uniform or something?

No. Make unique designs if you want to give them "formalwear."
I would personally just focus on giving them alternate uniforms in general instead of theming them specifically for formalwear, but you can still go with "formalwear" if you wish.

**Comment by potato1234x** [comment]
Neat

**Comment by potato1234x** [comment]
damn i reread your comment and i did the exact opposite im an idiot 😐

**Pull request closed without merging**
