### PR TITLE
Fix Drozd and C-20r unwielding on use-in-hand

### PR DESCRIPTION
**Pull request by Doomsdrayk**
## About the PR

Makes the Drozd and C-20r rack instead of unwielding when used in hand while wielded.

## Why / Balance

Racking rather than unwielding is the intended behavior for when these guns are used while wielded. A tangentially related PR accidentally changed this behavior (details below).

## Technical details

No C#, just added unwieldOnUse: false to both guns.

#27907 removed BaseGunWieldable as a parent for the Drozd and C-20r, which previously provided this behavior to them. This PR re-adds the behavior directly to the guns' prototypes.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes.

**Changelog**

:cl:
- fix: The Drozd and C-20r do not unwield on use again.

### CODE REVIEW

**Comment by Partmedia** [comment]
Thanks for the PR. When I apply the patch I don't seem to see any difference; could you explain what the change is?

**Comment by Doomsdrayk** [comment]
Thank you for reviewing my PR!

To clarify what the change is, here is a sequence of events with and without the patch:

### Without the patch:
1. Load in, then spawn and pick up a C-20r
2. Press use-in-hand (default z) -> You wield the C-20r
3. Press use-in-hand (default z) again -> **_You unwield the C-20r_**

### With the patch:
1. Load in, then spawn and pick up a C-20r
2. Press use-in-hand (default z) -> You wield the C-20r
3. Press use-in-hand (default z) again -> **_Closed bolt_**

Hope this clarifies it! If either of these sequences produces a different result for you, please let me know so I can investigate further. Also note that this only affects the C-20r and Drozd, not any other guns (that part probably wasn't in question, but I just wanted to be sure).

**Comment by Errant-4** [comment]
Why is WieldableComponent not on the parent SMG to begin with?

**Comment by Doomsdrayk** [comment]
WieldableComponent is not on the BaseSMG because not all SMGs can be wielded. In particular, the WT550 is an exclusively one-handed SMG. If we choose to put WieldableComponent on BaseSMG and define all SMGs to be wieldable, the WT550 will need to be either given a wielded sprite and accuracy modifier, or removed/deprecated. Either of these routes are doable but both seem like they warrant further discussion.

**Comment by Partmedia** [comment]
Got it, thanks for the explanation. The reason this was really confusing to me might have been related to the mispredict issue that you already fixed and merged.

**Comment by Partmedia** [comment]
Thanks for the fix!

**Comment by Partmedia** [comment]
Thanks for the fix!

**Pull request merged**
