### PR TITLE
Shut up a child throwing a tantrum

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
this looks pretty bad with lack of context

**Comment by Kadeo64** [comment]
> this looks pretty bad with lack of context

it's funny to check is:pr is:merged and see this

**Comment by FairlySadPanda** [comment]
Raised the process fault here on voice chat but just to re-iterate:

This will happen whenever an additional person - usually a non-technical contributor, like a spriter or audio technician, gets their work in-game via the help of a friendly contributor.

There should be a new row added to PRs to list contributors who should be added to the credits that are not the person making the PR, and there needs to be a process for adding these people in along with the main contributor.

**Comment by TsjipTsjip** [comment]
I should also add that this is presently possible, if the helping contributor knows how, to add a coauthor to a commit. This essentially attributes the "authorship" of a commit to the helping contributor and the artist, and this is respected by the currently in-place system for listing all contributors. This is a built-in feature in Git, which GitHub is compliant with.

This does not fully cover it, as FairlySadPanda has raised above, sometimes artists might want to be credited through more than their GitHub handle, but that in itself would require a whole new system as well.

<details>
<summary>Co-authors usage</summary>
To add a co-author to a commit, the commit message must end with a blank line followed by a co-authors line for each co-author of the commit.

Example:

```
Add functionality to manually add contributors to the contributions list.

Co-authored-by: GITHUB-NAME-OF-AUTHOR <COMMITTER-EMAIL-OF-AUTHOR>
```
Where you can substitute `GITHUB-NAME-OF-AUTHOR` and `COMMITTER-EMAIL-OF-AUTHOR` with the correct values.
</details>

**Pull request merged**
