### PR TITLE
Cyborg module action icons

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Makes the cyborg modules have icons in the HUD instead of being the boring module sprite.

## Why / Balance

Easier to see what the modules are without having to click through all of them.

## Technical details

Made a new BorgModuleIcon component that takes a RSI path and state to it. When a module with said component is installed it uses that icon in the HUD. Otherwise defaults to a new no-action state.

## Media

extinguisher-module
gps-module
tool-module
wire-module
geiger-module
rcd-module
adv-tools-module
construction-module
mining-module
appraisal-module
grappling-module
node-scanner-module
anomaly-module
adv-cleaning-module
light-replacer-module
cleaning-module
adv-diagnosis-module
defib-module
treatment-module
diagnosis-module
clowning-module
gardening-module
harvesting-module
musical-module
service-module
syndicate-weapon-module
syndicate-operative-module
syndicate-martyr-module
syndicate-esword-module
syndicate-l6c-module

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Cyborg modules now have icons instead of using the module sprite.

### CODE REVIEW

**Comment by ScarKy0** [comment]
Sci, service and syndi ones left

**Comment by ScarKy0** [comment]
It should be all good to go now

**Comment by lzk228** [comment]
i'm jyst curious, why you didn't put this datafield in ItemBorgModule?

**Comment by ScarKy0** [comment]
> i'm jyst curious, why you didn't put this datafield in ItemBorgModule?

In all honesty, didnt realize I couldve
and PJB said making a component for this is totally fine

**Review by metalgearsloth — APPROVED** [review]
art maintainer approved + they talked with pjb

**Pull request merged**
