### PR TITLE
Wrenchable Chairs and Plants

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Makes chairs and potted plants wrench-able, but you would need to have something inside the plant to wrench it. Also, chairs would need to be wrenched and unwrenched if they could be moved initially, notably on office chairs and wooden seats.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed certain chairs and potted plants to be wrench-able. Plants need to have something in them first to anchor them.

### CODE REVIEW

**Comment by Flareguy** [comment]
Doesn't chair deconstruction use a wrench?

**Comment by Alekshhh** [comment]
it uses a screwdriver

**Comment by AJCM-git** [comment]
linter fail

**Comment by AJCM-git** [comment]
linter still fails

**Comment by AJCM-git** [comment]
image

click on this to see whats wrong with your yaml (also test your changes)

**Comment by metalgearsloth** [comment]
Does this still affect plants

**Comment by Alekshhh** [comment]
seems like it, but only if there's something inside it initially

**Pull request merged**
