### PR TITLE
Add 4 new drinks to bartender job

### PR DESCRIPTION
**Pull request by efzapa**
## About the PR 
This change adds 4 new drinks to the bartender's disposal. The Bermuda Triangle, Daiquiri, Mimosa, and Whiskey Sour

I tried to replicate each drink to real life as best I could without having to dabble in hydroponics and making crops that literally only have one use

**Screenshots**

image

**Changelog**

:cl:
- add: Added 4 new drinks, Bermuda Triangle, Daiquiri, Mimosa, and Whiskey Sour

### CODE REVIEW

**Comment by Macoron** [comment]
Please, merge it after #7916

**Comment by Peptide90** [comment]
Looks good. Yaml looks all in order but build test failing.

#7821 related however, @DogZeroX were you trying to consolidate away from cev sprites for drinks?

**Comment by efzapa** [comment]
> Looks good. Yaml looks all in order but build test failing.
> 
> #7821 related however, @DogZeroX were you trying to consolidate away from cev sprites for drinks?

I just used the sprites we're currently using. Are there new drinking glass sprites we're trying to move to?

**Comment by Peptide90** [comment]
> > Looks good. Yaml looks all in order but build test failing.
> 
> > 
> 
> > #7821 related however, @DogZeroX were you trying to consolidate away from cev sprites for drinks?
> 
> 
> 
> I just used the sprites we're currently using. Are there new drinking glass sprites we're trying to move to?

In that case disregard, I was just going off your meta.json file saying it was from cev. If you made the sprites yourself based on them feel free to add a "modified by X" to the end.

**Comment by efzapa** [comment]
> > > Looks good. Yaml looks all in order but build test failing.
> > 
> > 
> > > 
> > 
> > 
> > > #7821 related however, @DogZeroX were you trying to consolidate away from cev sprites for drinks?
> > 
> > 
> > I just used the sprites we're currently using. Are there new drinking glass sprites we're trying to move to?
> 
> In that case disregard, I was just going off your meta.json file saying it was from cev. If you made the sprites yourself based on them feel free to add a "modified by X" to the end.

gotcha, will edit then 👍

**Comment by efzapa** [comment]
until I can figure out what's causing build problems imma draft this

**Comment by ZeroDayDaemon** [comment]
> Looks good. Yaml looks all in order but build test failing.
> 
> #7821 related however, @DogZeroX were you trying to consolidate away from cev sprites for drinks?

That would be me, not Slork.

Issues with the The transformable container component need to be addressed as well as the move from Eris based bartending to /tg/ based bartending.

**Pull request closed without merging**
