### PR TITLE
Remove welding mask from tech assistant 

### LINKED ISSUE #12088: Tech assistant spawns with a welding mask on
It looks stupid and tbh it should just be in the engivend.

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Title fixes #12088

## Why / Balance

asked in #12088 

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
no they look stupid with it dont remove

**Comment by lzk228** [comment]
> no they look stupid with it dont remove

add orange cone instead:trollface:

**Comment by Tunguso4ka** [comment]
now they will burn their eyes trying to disassemble the wall to the space...

**Comment by CatMagic1** [comment]
actual joke pr

**Comment by Partmedia** [comment]
This was implicitly approved by @metalgearsloth in the linked issue and now approved by me. As the issue points out, it is rather simple for the engineering assistant to go get one from the EngiVend.

I've opted to remove the Changelog entry because it does not meet the [significance guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog).

**Comment by lzk228** [comment]
> I've opted to remove the Changelog entry because it does not meet the [significance guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog)

if people can see the change in game, that should be in changelog, so remove yourself next time

**Pull request merged**
