### PR TITLE
ninja can spawn earlier, 1h reoccurence

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
so far ive only seen ninja in 3 rounds:
- a 2h round with 1 flukinja and 1 ninja that spawned as evac docked to centcom
- another round i dont remember
- just now ninja spawned 20s before evac
this lets them spawn 30m in which should make it more common for lizard
also upped player requirement to 40 so no steamrolling

## Why / Balance
ghosts want something to do + very rare
also i learned that reoccurence is a thing so why not

## Technical details
no

## Media
video of me waiting 43 mins 11 seconds for ninja spawn too big to upload sorry
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Ninjas can spawn from 30 mins in, instead of 45.

### CODE REVIEW

**Comment by Aisu9** [comment]
that will be SO BAD for Salamander... fricking hell

**Comment by Aisu9** [comment]
one ninja on sala is already bad enough because they go on a rampage

**Comment by deltanedas** [comment]
with 60 min reoccurence it will at least force a no double ninja period

**Comment by QuietlyWhisper** [comment]
Increase the min player count from 15 to something a lot higher would save the lowpop servers as well as salamander, theres typically only one secoff per 10 players if I had to estimate

**Pull request merged**
