### PR TITLE
Revamp Getmore Inventory 

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Revamped Getmore inventory to better suit the purpose of it. Added pistachios, sunflower seeds and CnDs from tg. Made the syndicakes box not cabinet perspective
## Why / Balance

the inventory did not have unique items apart from the raisins, the chocolate and the syndicakes (which are now emag only like tg)
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: Potato1234_x
- tweak: Changed the contents of the snack vendor to better fit snacks.
- add: Added C&Ds, Bob's sunflower seeds and Sweetie's pistachios.

### CODE REVIEW

**Comment by potato1234x** [comment]
test fails not my fault??

**Comment by Jackal298** [comment]
> test fails not my fault??

I have the same garbage with tests, I'm glad that you embodied the idea that I wanted to do at some point but could not

**Comment by EmoGarbage404** [comment]
these are cute and i like them

**Comment by deltanedas** [comment]
why does the bottom item look doctored bruh

**Comment by potato1234x** [comment]
> why does the bottom item look doctored bruh

how so

**Comment by deltanedas** [comment]
the e's are all fucked

**Pull request merged**
