### PR TITLE
Add health analyzer to protolathe

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

thats all

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Health analyzer can be printable on protolathe

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Considering these are roundstart they probably shouldn't be gated behind tech?

**Comment by EmoGarbage404** [comment]
> Considering these are roundstart they probably shouldn't be gated behind tech?

Yeah. Theres no point in gating them.

**Comment by EmoGarbage404** [comment]
> Considering these are roundstart they probably shouldn't be gated behind tech?

Yeah. Theres no point in gating them.

**Comment by FellowsinSpess** [comment]
Doesn't the Medical Techfab make these? I swear you can make the health analyzers in the medical protolathe.

**Comment by Emisse** [comment]
they in medfab and we dont want these everywhere

**Pull request closed without merging**
