### PR TITLE
Amber Station - Added Holopads, Atmos Monitoring, and Advanced SMESes

### PR DESCRIPTION
**Pull request by southbridge-fur**
## About the PR

Holopads, atmos monitoring, and Advanced SMESes are now in master, this adds them to Amber Station.

Holopads have been spread around the map to various areas. I tried to give one to each department plus one to every major job. The clown has a holopad board so they (or the mime) can build an art installation with it if they want. There is a public holopad in the library, to help incentivize people to go to the library. Every head gets one in their room, and I've tried to name the pads in such a way that they stay neatly organized in the call list. 

I already had the atmos monitoring devices in my previous PR but didn't realize I needed to also have the console. I've added the console to atmos, the bridge, and the evac shuttle. 

Also the advanced SMESes were added moments ago, so I've added them too.

Also addressed some issues:

- Fixed the fact that the bartender can't close all their shutters. I realized that the TV blocked the shutter so I removed that shutter and put a directional wall there instead. 
- Gave the fake nuke disk a funny description that makes it more obvious it's the fake.
- Generally fixed up some areas that could use screens, fire extinguishers, and other wall-ornaments. 

## Why / Balance

New features that need to be mapped have been mapped!

## Media

Atmos network monitor 
image

Holopads! 
image

Advanced SMESes
image

Bartender shutters
image

Fake nuke disk
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by southbridge-fur** [comment]
Addresses #33916

**Comment by southbridge-fur** [comment]
test fail real

**Comment by southbridge-fur** [comment]
I don't know what's wrong. I don't have any serialized invalids.

**Comment by ArtisticRoomba** [comment]
Heya. The Advanced SMESes and AME power curve PRs work with the larger goal of enabling stations to conform with the current legacy engineering design document. In short:
- At 5 minutes, the AME is turned on. The battery levels on your primary SMES bank should be close to or above 30% at this time.
- At 10 minutes, the solars are presumed to have been setup. The battery levels should now be around 20%.
- At 15 minutes, battery levels can drop nearing 20-10%.
- At 20 minutes, a major power source is assumed to have started. The batteries shouldn't be dead at this point.

If you could make sure your map conforms to this with the advanced SMES changes, that would really help engineering.

image

**Comment by Pumkin69** [comment]
great work you are doing a wonderful job <3

**Comment by ArtisticRoomba** [comment]
```
Failed GameMapsLoadableTest("Amber") [8 s]
  Error Message:
   SERVER: 7.999s [ERRO] map: Error in map file: found local entity UID '0' which does not exist.
```
Might have invalids.

**Pull request merged**
