### PR TITLE
CargoConsoleMenu localization

### PR DESCRIPTION
**Pull request by modern-nm**
## About the PR

This PR adds localization capability for CargoConsoleMenu (name of entity: ComputerCargoOrders)

## Why / Balance

Please let me tell you a story of my vision. First i decided to make these changes on one of russian community servers. But taking into account future changes of .yml files by space-wizards community (they are regularly added to our space-station build), we will have to constantly edit xml files to remove duplicate categories — imagine someone added cargoproduct with category "Fun", when we have tons of items with category "Развлечения".

To summarize: my PR makes possible to localize categories of "cargoproduct" and makes communities do less work when upstream comes

## Technical details

New code considers strings comparisons of prototype.Category (Content.Client/Cargo/UI/CargoConsoleMenu.xaml.cs) using Loc.GetString(...). And that's all.

## Media

Off course there are no visible changes on eng-localization

Снимок_ножницы

That's how these changes look like on our community build, using other .ftl file

Снимок_ножницы2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

.yml
- every category of type "cargoProduct" was edited to "cargoproduct-category-name-{categoryName}"

.ftl
- file "cargoproduct-categories.ftl" was added to english localization to localize categories of cargoProduct

.cs
- CargoConsoleMenu.xaml.cs got tweaks which prevent issues with strings comparisons

**Changelog**

### CODE REVIEW

**Comment by modern-nm** [comment]
This is my first attempt to contribute in your build, so i hope u'll be merciful and don't smash me

**Comment by TheShuEd** [comment]
you can remove CL, these is no changes to common players

**Comment by modern-nm** [comment]
> you need remove CL, these is no changes to common players

thank you

**Comment by KashRas2** [comment]
no cl no fun 🐔

**Pull request merged**
