### PR TITLE
White cane recipe

### PR DESCRIPTION
**Pull request by inkeyz**
## About the PR

added a recipe for a white cane to the medical techfab. and changed stats a little.
## Why / Balance

it seems to be difficult to get one if a blind person has lost his somewhere, so I think that a medbay should be able to make new ones. also reduced damage and increased size a little to prevent the use of cane by non-blind persons

## Media

image

-  [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑

- tweak: White cane recipe now added to medical techfab
- tweak: White cane has reduced damage and increased size

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
the damage doesn't need to be increased nor the size increased, using it wielded is just as good as a crowbar (8 blunt) but you lose an extra hand that can be used for grabbing dropped weapons and such.

the cane is also visibly smaller than a roller bed, which makes it non nonsensical to weigh the same.

the cane does NOT need to be nerfed

**Comment by Aisu9** [comment]
the damage are being reduced

**Comment by JoeHammad1844** [comment]
it doesnt deal more damage though, youd be more effective in combat with a crowbar which is 
1. easier to find 
2. deals the same amount of damage as a wielded cane
3. is one handed
4. is lighter (10 weight)
and the stealing 'problem' is solved anyway by putting the cane in the techfab in the first place, there is no need to nerf the cane, it just fucks over the blind people you pretend to be defending

**Comment by Aisu9** [comment]
because it's a fricking cane and not a rod of pure steel

**Comment by deltanedas** [comment]
bat is pure wood so why does it do more damage than crowbar

**Comment by JoeHammad1844** [comment]
> because it's a fricking cane and not a rod of pure steel

hitting someone with the cane wielded does the same amount of damage as a punch

**Comment by LankLTE** [comment]
This has already been PRed to be cargo orderable- and I'm leaning towards that option as it'd discourage people from buying it freely because of money (as compared to nerfing the already-awful stats). If you could give justification as to why this option is better that would be appreciated.

**Comment by inkeyz** [comment]
I also had opinion like this, but someone in the comments to that PR said "the idea is that it's exclusively for the blind and with this change I could see Cargo running around with a bunch of them." and in order to preserve the exclusivity of it, I suggested making it printable only in a medical techfab, because doctors will not give canes to anyone, but only to those who needs it (well, according to the idea ..). also, this statement leaded me to make canes a less desirable object to use for non-blind persons (as I wrote in the description) which led to the nerf. and blind people are kind of rare visitors on the station, I'm not sure that three pieces will be needed at once. if a medical techfab can print things like a defibrillator and an hand labeler, then why can't it print canes? from my point of view, this is logical. also after losing a cane person must wait for cargo to deliver it to medbay and it can take some time. but if person will get a new cane immediately it will save their time.

**Comment by NancokPS2** [comment]
Having people run around with canes doesn't seem like a problem at all. You can't fake being blind because it literally says so in your description. And using stuff not themed to your character has NEVER been a problem.     

If people want to carry around a cane, i don't see an issue with them doing so. There's no such thing as item "exclusivity" other than obvious cases like department/head-only gear and sensitive items like the nuke disk. If blind characters feel less "exclusive" then i think the problem is on them. Specially when you have to gather mats and get access to a lathe/fab to even get one so it isn't like people are going to run around with this for the sake of it.
  
But it DOES make sense for a medfab to have this. Mostly so the general lathes don't get overloaded with even more misc stuff.

**Pull request closed without merging**
