### PR TITLE
Cog update 

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR

changed all the firelocks on cog to glass firelocks
thats it

## Media

Im not gonna post a screenshot because you can't tell if anything is different looking at the screenshot, but all the regular, non-see-through firelocks (most of the firelocks) have been converted to the glass version which you can see through and shoot through with a laser.

(also the bot will post a screenshot anyway)
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

no changelog

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
How long did this PR take you to do?

**Comment by Spessmann** [comment]
not that long

**Comment by Spessmann** [comment]
rather easy

**Comment by Brandon-Huu** [comment]
> not that long

alright.

I was just gonna point out that you could had just renamed the prototype in the .yml file instead of going in game to make the changes.

Saves a lot of time on some things

**Comment by Spessmann** [comment]
thats what i did

**Comment by Spessmann** [comment]
except i already has SOME glass firelocks, so i just moved everything in the "firelocks" area to the "glass firelocks" area

**Comment by Boaz1111** [comment]
> > not that long
> 
> alright.
> 
> I was just gonna point out that you could had just renamed the prototype in the .yml file instead of going in game to make the changes.
> 
> Saves a lot of time on some things

That is like severely frowned upon.

**Comment by Boaz1111** [comment]
Last I checked

**Comment by Boaz1111** [comment]
nvm am wrong

**Pull request merged**
