### PR TITLE
Plant Analyzer 

### PR DESCRIPTION
**Pull request by Yter-alt**
## Plant Analyzer
I moved the ss13 plant analyzer. I also added the capabilities of the botanist pda analyzer. I added it to the vending machine. 

The plant analyzer gives out information:
1) Potency.
2) Yeild
3) Harvest type
4) Seed health and current plant health
5) The comfortable temperature for the plant
6) medicinal components that are in it 
7) The bonuses he gets from mutations.
8) Current Problems that Concern the Plant

I also slightly changed getting negative traits for mutations. The creator of the original  system Notafet agreed to the changes after a little discussion in discord. Now the negative traits have a constant chance, which will not increase if you increase the chance of mutations with left-4-zed. 

**Media**
- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase!

image

**Changelog**

:cl:
- add: Plant Analyzer
- fix: Fixed negative mutation chances

### CODE REVIEW

**Comment by deltanedas** [comment]
this seems stupidly strong for getting *just* the right breed with no downsides

**Comment by DogZeroX** [comment]
If it's really that OP, then it should prolly be science content.

**Comment by EmoGarbage404** [comment]
I think items that flatly tell you all the information you could ever need are kinda boring. This seems very unnecessary, in my opinion.

**Comment by Yter-alt** [comment]
> I think items that flatly tell you all the information you could ever need are kinda boring. This seems very unnecessary, in my opinion.
The analyzer has been in ss13 all its life, and it hasn't been boring. It is a necessary thing in botany. I'll tell you more, there was even a gene editor in cc13. 

> this seems stupidly strong for getting just the right breed with no downsides
The flaws remain, it's just that now the chance of negative genes can't be 100%

**Comment by Nimfar11** [comment]
It seems to me that a plant analyzer can be a little push for the development of botany, which is in a certain stagnation of ideas. Having such a device, it will become more interesting to play with plant modification.

**Comment by EmoGarbage404** [comment]
> I completely agree. We must remove the anomaly and health scanner.

*Yes.*

**Comment by deltanedas** [comment]
this but unironically :trollface:

**Comment by GoodWheatley** [comment]
> I think items that flatly tell you all the information you could ever need are kinda boring. This seems very unnecessary, in my opinion.

I agree with this regarding the health and anomaly analyzers, but I think the plant analyzer is something than botany desperately needs. There are several hidden plant mechanics that aren’t communicated to the player at all, and the analyzer making it clear what the mechanics are doing would vastly simplify botany onboarding and make it a more enjoyable experience.

**Comment by deltanedas** [comment]
if all you have used is health examine, you could say the same for health analyzer too since it doesnt mention radiation or poison at all, and with limited accuracy on others

**Comment by potato1234x** [comment]
finally i can stop accidentally killing plants

**Comment by metalgearsloth** [comment]
> > I completely agree. We must remove the anomaly and health scanner.
> 
> _Yes._

I agree with wheatley to the extent 90% of botany gameplay is surprise mechanics as none of it is documented anywhere (wiki or guidebook) so as a player it's a blackbox unless you code dive or experiment a lot. What's worse is the fact there's 0 reason to even engage with any of its systems as you can just spam plants out anyway.

**Comment by EmoGarbage404** [comment]
> > > I completely agree. We must remove the anomaly and health scanner.
> > 
> > _Yes._
> 
> I agree with wheatley to the extent 90% of botany gameplay is surprise mechanics as none of it is documented anywhere (wiki or guidebook) so as a player it's a blackbox unless you code dive or experiment a lot. What's worse is the fact there's 0 reason to even engage with any of its systems as you can just spam plants out anyway.

I agree that its a lot of non-visual blackbox mechanics, but adding literally all conceivable info into a single device is overkill.

**Comment by keronshb** [comment]
I didn't review this PR yet so I don't know how they're intended to work here but I'm very familiar with how they work on ss13 so I'll go off of that knowledge.

This would be better to have than the swab system we have now since the swab system is kinda gross and also code is reused between disease and plants.

I prefer to have devices that give you information you need (analyzers) because the game can be cryptic at times. There's also some devices that I think should not exist at all (handheld crew pointer + handheld crew monitors). But maybe the analyzers can be shifted to a vendor/sci unlock/cargo. Which in-lies another problem of making cargo/sci/mining the backbone of the station.

**Comment by metalgearsloth** [comment]
> The analyzer has been in ss13 all its life, and it hasn't been boring. It is a necessary thing in botany. I'll tell you more, there was even a gene editor in cc13.

TBH I think botany is one of the departments that should've been redesigned for 14 as it's not sure whether it wants to be genetics powergaming or food growing for chef and I think it should emphasise the latter.

As it stands the genetics side is unfeasible to play without something telling you what is going on so it either needs a lot of refactor around it to trim it down or a plant analyser.

> that I think should not exist at all (handheld crew pointer + handheld crew monitors).

Based (agreed).

**Comment by EmoGarbage404** [comment]
At the very least, the analyzer should be destructive in some way.

**Comment by GoodWheatley** [comment]
> At the very least, the analyzer should be destructive in some way.

Consider that you might have to scan hundreds of plants several times during a shift just to see what’s going on with their genetics. While the idea makes sense, it’s just going to end up being another hidden mechanic that unfairly frustrates and confuses new botanists.

**Comment by EmoGarbage404** [comment]
Considering that the actual obtuse mechanics at play are the breeding mutation systems, i don't see how blatantly listing out all the info is fixing the problem. Many of the things that are listed here could easily be observed, which is more interesting imo.

I don't see how being a destructive sample is a hidden mechanic. A system for plant clippings already exists and has balance features. I would much rather prefer having some kind of reasonable downside considering that it lowers skill level so considerably.

**Comment by viauno** [comment]
> At the very least, the analyzer should be destructive in some way.

Plant analyzer should be used on seeds so you still have to damage the plant by taking seeds. Also it should display Maturation and Production genes, they are quite time consuming to figure out by just standing around.

**Comment by keronshb** [comment]
How much overlap does this have with the swab system too? If there's enough then you should also remove the botany swab portions (leave the disease part if it's still in).

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Do you have a code formatter you can run over this?

**Comment by metalgearsloth** [comment]
@Yter-alt are you coming back to this mate?

**Pull request closed without merging**
