### PR TITLE
Sound effect plays when an item is thrown

### PR DESCRIPTION
**Pull request by Rember**
Adds a "woosh" sound effect when an item is thrown. Take a closer look at this code because I'm fairly inexperienced with this sort of stuff, and the sound effect doesn't sound super great either so you may have to look for a new one.

### CODE REVIEW

**Review by Zumorica — APPROVED** [review]

**Review by DrSmugleaf — APPROVED** [review]

**Comment by metalgearsloth** [comment]
Our licencing for audio is non-existent but mine putting it in where you got it where audio's played?

**Comment by Rember** [comment]
> 
> 
> Our licencing for audio is non-existent but mine putting it in where you got it where audio's played?

I took the sound effect from here: https://www.fesliyanstudios.com/sound-effects-search.php?q=woosh (I believe the specific file was Whoosh B1 Sound Effect)

The policy page for sound effects mentions that the sound effects may only be used in the context of a project and crediting is not required, so that should be fine (no distincion about commercial/non-commercial either, it seems). Here's the page, it's not very long: https://www.fesliyanstudios.com/sound-effects-policy

**Review by chairbender — CHANGES_REQUESTED** [review]
I would suggest putting a text file in the same folder as the sound saying where you got the sound from, as a stopgap until we have a better way of tracking this stuff. This is the approach I used when taking sounds from tg, check Resources/Audio/Voice/Human/license.txt. Even though the page says you don't need attribution, we still want a link to the source so in the future we won't be scratching our heads wondering where it came from and we won't want to dig up this PR to find that info.

**Comment by PJB3005** [comment]
Yeah, just do a text file. I think I did the same before for a few other audio files.

**Comment by Rember** [comment]
Oh shoot, just got notified this got merged but I didn't put in the text file you guys asked. I was away for the weekend but I'll be returning today so I'm going to make a new commit/PR for it later

**Comment by metalgearsloth** [comment]
TBH you included it here so I was fine with that though I'm not sure how it counts for attribution as IANAL.

**Pull request merged**
