### PR TITLE
Remove obs kit

### PR DESCRIPTION
**Pull request by metalgearsloth**
Syndi handheld crew monitor got removed. Give them their own content instead of reskinning NT stuff.

### CODE REVIEW

**Comment by Nimfar11** [comment]
So now NT does not have a handheld crew monitor.

**Comment by Ilya246** [comment]
actually yeah since the normal handheld monitor got removed, it wouldn't really be a reskinned NT thing anymore
that is, unless we readd the NT monitor as a tech or something

**Comment by metalgearsloth** [comment]
Syndies should get their own local radar or a heatmap or some shit.

**Comment by foboscheshir** [comment]
With its removal from the NT, it became only a syndie item

**Comment by Olexiy-Lapin** [comment]
> Syndies should get their own local radar or a heatmap or some shit.

So maybe it's worth adding them first?

**Pull request merged**
