### PR TITLE
Minor addition to Cybersun pen description

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR
Cybersun Pen description:

`A high-tech pen straight from Cybersun's legal department, capable of refracting hard-light at impossible angles through its diamond tip in order to write.` 

has the following added to the end: 

`So powerful, it's even able to rewrite officially stamped documents should the need arise.`

## Why / Balance

Cybersun Pen's ability to rewrite stamped documents is hidden knowledge, despite being a very strong effect when utilized correctly. 

CentCom Pen description isn't changed since that item is much rarer and not part of the Syndicate arsenal.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
ftr its in the uplink description

**Comment by SlamBamActionman** [comment]
`Cybersun's legal department pen, invaluable for forging documents and escaping prisons. Smells vaguely of hard-light and war profiteering.`

Imo "forging documents" isn't descriptive enough, sounding more like flavor text. Especially next to "escaping prisons" which the pen only helps with by being a stabbing weapon.

**Comment by deltanedas** [comment]
its also a screwdriver :trollface:

**Comment by Partmedia** [comment]
I feel like the hidden capabilities should be prominently displayed in the uplink, but hidden from the description since all players can see it.

**Comment by SlamBamActionman** [comment]
Unlike something like the hypopen, the Cybersun pen in the uplink is not a disguised version of another item. When I call it "hidden knowledge", I mean that its functionality is not described well in the game and is only known word-of-mouth, not that it is intentionally designed to be a covert item.

Additionally, thieves get access to CS pens via their toolkit, and I _think_ Salvage can find them as well.

**Comment by Partmedia** [comment]
> `Cybersun's legal department pen, invaluable for forging documents and escaping prisons. Smells vaguely of hard-light and war profiteering.`

I feel that this better fits the style and tone of other item descriptions. I don't think a description has to give away all the details.

I'm fine with merging either, so please give this a consideration and let me know what you'd like to go ahead with.

**Comment by SlamBamActionman** [comment]
That is the Uplink description, so it's already being used there. I didn't write it, I just cited it in response to the comment above it.

**Comment by LankLTE** [comment]
> I feel like the hidden capabilities should be prominently displayed in the uplink, but hidden from the description since all players can see it.

Trying to hide stuff like that isn't great. Players will know the cybersun pen can do this if they stalk the repo / play a ton, but players who just pick it up won't as the description doesn't state it. Adding it to the description just makes that feature more accessible.

**Pull request merged**
