### PR TITLE
Atlas Rework

### PR DESCRIPTION
**Pull request by Doctor-Cpu**
## About the PR

- Added an actual atmos
- Perma and Warden in sec
- Expanded Bridge and added meeting room for RP
- Widened dorms and cryo

## Why / Balance

Quite a few dislike atlas in it's current state with atmos and bridge being the main ones I see. Tried to keep the changes small to not make it a different map and as a break from programming. 

## Technical details

N/A

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Atlas has been reworked.

### CODE REVIEW

**Comment by XGabriel08X** [comment]
Finally
Goodlas

**Comment by Wudanty** [comment]
A much needed change

**Comment by deepdarkdepths** [comment]
No more shitty atmos my beloved

**Comment by Lamrr** [comment]
I like perma and it's little window into maint, that should be fun. But what's up with the wardens office (bedroom)? I don't think it should have wood and carpet and there definitely shouldn't be a bed in front of the armoury blastdoor.

I'd say move that console out into the wardens other office area and just turn the place into auxiliary sec storage, which seems to be needed considering the main entrance into the armour also seems to be blocked by lockers and cabinets?

**Comment by deltanedas** [comment]
yeah i think:
- move bed onto scrubber or remove it
- remove blast door between armoury and wardens room
- move that gun safe to the right, above where the removed blast door is

**Comment by Doctor-Cpu** [comment]
I originally had a window under the blast door in wardens room but I can't find a way to keep it so it's been yeeted and the gun safe has been moved in its place.
Beds also been moved.

> I don't think it should have wood and carpet and there definitely shouldn't be a bed in front of the armoury blastdoor.

I view the commands bedrooms as a good in-character way of saying that they're going ssd without just stating they're going ssd like they need some alone time. Wardens current room just feeling way to cramped and open for that to be done on current atlas.

> I'd say move that console out into the wardens other office area and just turn the place into auxiliary sec storage, which seems to be needed considering the main entrance into the armour also seems to be blocked by lockers and cabinets?

Isn't that the purpose of the break room to the right as secs gear is already stored there?

**Comment by deltanedas** [comment]
need to remove all the door state stuff that shouldnt be saved

**Comment by deltanedas** [comment]
if those tiny fans are at external airlocks dont, theyre linked to bolt so you dont space anything.

**Comment by Doctor-Cpu** [comment]
> if those tiny fans are at external airlocks dont, theyre linked to bolt so you dont space anything.

They were there before I shifted the arrivals up so i presumed they were needed. I can remove them and the ones at evac and cargo if needed as well.

**Comment by deltanedas** [comment]
arrivals evac and cargo are good (until we get the new directional fans :trollface:)

**Comment by Doctor-Cpu** [comment]
> arrivals evac and cargo are good (until we get the new directional fans :trollface:)

ah so no issue? I just readded ones at arrivals.

**Comment by deltanedas** [comment]
yep theyre good :+1:

**Comment by Doctor-Cpu** [comment]
hopefully last commit unless i find more blunders

**Comment by Dr-piss** [comment]
jani has no buckets, no water tank and the closet is in disposals for some bizarre reason

**Pull request merged**
