### PR TITLE
Adds gratuitous logging to AlertsUI for debugging.

### PR DESCRIPTION
**Pull request by Acruid**
Someday we will find the bug! In response to #6570.

### CODE REVIEW

**Comment by moonheart08** [comment]
This should all be debug logs with a specified sawmill, shouldn't it?

**Comment by Acruid** [comment]
Debug logs are suppressed in release builds, I need the players to see these so they can provide more info when the bug happens. Once we actually identify the cause of the bug this PR can be reverted.

**Comment by mirrorcult** [comment]
this can be reverted now

**Comment by mirrorcult** [comment]
probably

**Pull request merged**
