### PR TITLE
Changes to "Burst" firemode; Drozd, WT550 and C20-r

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR makes changes to the Burst firemode of guns, with major changes to Drozd and minor changes to WT550 and C20-r. The burst firemode was underutilized due to being largely unnecessary; no guns were balanced around it, and since you had to continuously hold the mouse button down to fire, you had free control to stop firing mid-burst. This PR aims to change that.

General changes:
- Burst firemode now fires the entire burst after pulling the trigger, even if the trigger is let go. The gun continues to fire even if the gun is let go until either the burst is over or all ammo is used up. 
- A delay has been introduced between bursts. This keeps burst mode from being used as full-auto by timing clicks/holding the trigger.
- Guns now have the ability to fire faster when toggled into burst mode.

Drozd changes (major):
- Drozd has been changed into a burst-only firemode SMG.
  - 3 bullets per burst, fired over 0.25 seconds. There is a burst delay of 0.25 seconds. This results in 6 shots per second, which is the same DPS as the previous version. 

WT550 changes (minor):
- WT550 is still an auto/semi/burst firemode toggle. 
- The burst mode has the same 5 bullets per burst but buffed to fire them over 0.714 seconds, with a burst delay of 0.2 seconds. This results in 5.5 shots per second, which is the same DPS as the full-auto mode. 

C20-r changes (minor):
- C20-r is still an auto/semi/burst firemode toggle.
- The burst mode has the same 5 bullets per burst and does not have a buffed firing speed, with a burst delay of 0.25 seconds. This results in a slightly lower DPS. However, due to each SMG mag containing 30 bullets and the C20-r's ability to auto-eject its mag, it becomes a lot more controllable to hotswap to a new mag with a bullet still in the chamber, which skips having to bolt the gun. Therefore it becomes much easier to reload faster if managed correctly.

## Why / Balance

The Drozd, AKMS and Lecters were raised as currently being very similar with no real stand-out features in between them. The Drozd is supposed to have slightly higher DPS by sacrificing accuracy, but this is largely not felt in gameplay and hasn't created much distinction between the weapons. 

Changing the Drozd into a burst-fire only SMG pushes it into a much more unique niche, while perserving the strong DPS and higher spread. The choice to change the Drozd was due to the spread; being able to burst 3 bullets very rapidly with full accuracy down a hallway while cornerpeeking could be very punishing for the other side, but with spread you're encouraged to engage in the mid-range instead where it becomes harder to disengage.

The WT550 change makes the burst fire an optional mode for those that feel it suits them better; it's not much faster than full-auto (5.5 vs 7 firerate) and the delay keeps the DPS in check.

The C20-r change could have followed the same reasoning if not for the very strong assistance it provides for reloading. It becomes a lot harder to lose the final chamber bullet and the speedier reload this results in can make for frighteningly little downtime.

## Technical details

To make for comfortable prediction the client is supposed to send shoot commands to the server. These are sent when the mouse button is held down and the server just checks if enough time has passed for the next shot to happen.
Since bursts are supposed to continue no matter what the client's input is the server might need to take responsibility for firing the bullets itself via its own update loop. `BurstEnabled` ensures this.
This is really only noticeable if the client experiences packet loss (e.g. a lag spike). 

Since the ship cannons also uses the gun system there has been a `DefaultDirection` property added that makes any thrown guns actively shooting fire in the direction of the sprite's muzzle.

## Media

Video link ([youtube](https://www.youtube.com/watch?v=LCns95cXJB8)):
[Video link](https://www.youtube.com/watch?v=LCns95cXJB8)

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: WT550 and C20-r's "burst" firemodes are now actual bursts.
- tweak: Drozd is now a burst-only weapon (DPS remains unchanged!).

### CODE REVIEW

**Comment by Golinth** [comment]
Burst fire my beloathed, I'm glad its here as an option though

**Comment by JIPDawg** [comment]
I too personally hate burst fire weapons. Do they at least give like improved accuracy?

**Comment by SlamBamActionman** [comment]
> I too personally hate burst fire weapons. Do they at least give like improved accuracy?

Spread has not been changed. Technically the Drozd/C20-r do get better spread since the delay between bursts allows for some cooldown between shots (WT550 is a fully accurate gun), but the benefit provided with the Drozd is the ability to make great burst damage from cover. 

I think it is worth exploring a gun that gets disasterous spread if spammed but burst mode keeps it controlled, but that's not this PR.

**Review by Errant-4 — APPROVED** [review]
Tested and found no issues. I think good burst fire is an addition that we generally wanted for a while, now

**Comment by Errant-4** [comment]
Now that burst fire will be more viable we might actually need to think of a better UX solution to switching firemode, but that's not strictly a consideration for this PR

**Comment by The048** [comment]
I don't understand why the Drozd in particular was made burst-fire instead of the Lecter. Generally, its a lot more common to see assault rifles portrayed as burst-fire weapons [see: the M16, which the Lecter seems to be somewhat based on], and I the standard 25-round magazine that the Lecter takes would fit burst fire quite well. As well, the Lecter seems to fall into a more accuracy-oriented role, with stronger individual bullets than the Drozd.

**Comment by thebadman4662** [comment]
Probably because lecter is nearly laser-accurate(true laser would be viper full auto, even actual lasers seem to be less accurate than it) in full auto. Drozd quickly loses accuracy after just a couple of bullets.

**Comment by thebadman4662** [comment]
Gotta say, drozd feels awful to use now to me. From trusty magdump weapon its that weird two handed inaccurate bursty pistol now, feels more like clumsy LMG than SMG.

**Pull request merged**
