### PR TITLE
That's pretty crate

### PR DESCRIPTION
**Pull request by SweptWasTaken**
Just a general cleanup pr for crates. I'm gonna go off [tgs supply crates](https://tgstation13.org/wiki/Supply_crates) so yell at me if you don't want that.

- [x] Changed plasma crate to phoron
- [x] Fix crate icons
- [x] Add the rest of the crates 
- [x] Make it so you can weld crates shut
- [x] Make it so you can anchor crates 
- [ ] Add tgcrates content
- [x] Add secure crates that can be locked
- [ ] Add crates to cargo console

Can't wait for you guys to see what I have in **store**. I might be **freight**end by your reactions though. Just be on the lookout I might add some se**crates** in this pr. Although with all these puns I might be sent **packing**. I've been having a **crate** time writing these puns.

### CODE REVIEW

**Comment by Zumorica** [comment]
Fix the conflicts if you want this merged, please.

**Comment by SweptWasTaken** [comment]
Will get this up to scratch and mergeable tomorrow

**Comment by SweptWasTaken** [comment]
Will get this up to scratch and mergeable tomorrow x2

**Comment by SweptWasTaken** [comment]
This will be mergeable by Monday

**Comment by SweptWasTaken** [comment]
Who put the stale tag on this? It'll be mergeable in an hour.

**Comment by SweptWasTaken** [comment]
Closing in favor of #1835

**Pull request closed without merging**
