### PR TITLE
Added warden gas mask! (again)

### PR DESCRIPTION
**Pull request by Stanislav4ix**
## About the PR
Added warden gas mask!

## Why / Balance
HoS has his own gas mask (SWAT gas mask), now warden also has gas mask!

## Technical details
Now SWAT and warden gas mask have "Flash Immunity", that means that you can not wear sun glasses and you won't get flashed. Also warden's suit storage unit has warden gas mask in it. I took a sprite from "Paradise Station" but I didn't like that, so I just resprited that.

## Media
image
image
image

- [x] I have added screenshots to this PR showcasing its changes ingame.

**Changelog**
:cl: Stanislav4ix
- add: Added warden gas mask!

### CODE REVIEW

**Comment by GoodWheatley** [comment]
Remove the flash immunity from the warden and HoS gas masks

**Comment by Stanislav4ix** [comment]
> Remove the flash immunity from the warden and HoS gas masks

Why?

**Comment by GoodWheatley** [comment]
> > Remove the flash immunity from the warden and HoS gas masks
> 
> Why?

It’s powercreep

**Comment by asperger-sind** [comment]
I think it's fine if the HoS' mask flash resist stays, it's common for heads to have better gear and/or special gear, the HoS doesn't have a lot besides that.

**Comment by EmoGarbage404** [comment]
these shouldn't have flash immunity. Security already has sunglasses and these having flash immunity invalidates the tradeoff between sunglasses/HUD

**Comment by Stanislav4ix** [comment]
> these shouldn't have flash immunity. Security already has sunglasses and these having flash immunity invalidates the tradeoff between sunglasses/HUD

Then the glass in the helmet is simply painted without any protection? Somehow illogical

**Comment by Carolyn3114** [comment]
> Contributor

armour

**Comment by Stanislav4ix** [comment]
> > > these shouldn't have flash immunity. Security already has sunglasses and these having flash immunity invalidates the tradeoff between sunglasses/HUD
> > 
> > 
> > Then the glass in the helmet is simply painted without any protection? Somehow illogical
> 
> armour

The gas mask serves as armor, and the glass is made of a material that protects against flash

**Comment by Stanislav4ix** [comment]
> > > > these shouldn't have flash immunity. Security already has sunglasses and these having flash immunity invalidates the tradeoff between sunglasses/HUD
> > > 
> > > 
> > > Then the glass in the helmet is simply painted without any protection? Somehow illogical
> > 
> > 
> > armour
> 
> The gas mask serves as armor, and the glass is made of a material that protects against flash

And if someone from S.W.A.T. forgot his sunglasses at home? :trollface:

**Comment by metalgearsloth** [comment]
I agree with emisse.

**Pull request closed without merging**
