### PR TITLE
Origin Station Update 19.08.2023 (hop rework, centcom bag removal)

### PR DESCRIPTION
**Pull request by brainfood1183**
Removed - centcom bag spawn (it has a centcom pda with AA in it :O ) and added a centcom scalf there instead.
Reworked - Hop office a little.
Added - theatre south of hop office.
Removed - some lights from maints to make it a little darker in places.
Reworked - area south of bridge into a bridge bar.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by LankLTE** [comment]
btw #19256 fixes the AA issue, if that's merged it could probably stay

**Comment by brainfood1183** [comment]
> btw #19256 fixes the AA issue, if that's merged it could probably stay

if it is merged then i will add it back.

**Comment by Equivocateur** [comment]
yeah the bag was a blunder, couldve sword it didnt have aa before.

HoP is missing a fax machine which I just remembered.

**Comment by brainfood1183** [comment]
> yeah the bag was a blunder, couldve sword it didnt have aa before.
> 
> HoP is missing a fax machine which I just remembered.
> 
> I'd also remove the blast door from bridge bar since its technically AA to anyone with a network configurator and a button.

will do

**Comment by crazybrain23** [comment]
> > btw #19256 fixes the AA issue, if that's merged it could probably stay
> 
> if it is merged then i will add it back.

You won't have to add it back, I've added a "do not map" suffix.

**Comment by Emisse** [comment]
find the invalid in your prototype file and delete it

**Comment by brainfood1183** [comment]
> find the invalid in your prototype file and delete it

should be fixed now, seems if a switch links to an object that is deleted it will cause the invalid issue.

**Comment by Emisse** [comment]
dont readd the centcom bag it should not be mapped

**Pull request merged**
