### PR TITLE
Update UI when the AME node group is changed, fix AME connection issues

### PR DESCRIPTION
**Pull request by 20kdc**
This fixes the AME core count indicator being out of date, and fixes the node setup so they all use AdjacentNode instead of the AME itself using CableDeviceNode.

## About the PR

**Changelog**

:cl:
- fix: Updates AME core count indicator as the layout changes.
- fix: AME connection issues shouldn't occur anymore.

### CODE REVIEW

**Comment by mirrorcult** [comment]
fixes #4364 and #4365?

**Comment by 20kdc** [comment]
Doesn't fix #4365
Does fix #4364 though

**Comment by 20kdc** [comment]
The main thing about the connection changes is it fixes that thing where the AME controller fails to recognize the AME shielding's existence.
Should I try to fix #4365 here? It seems like a single-line change

**Comment by mirrorcult** [comment]
go for it if you think you know how

**Comment by 20kdc** [comment]
Correction: fixing #4365 is definitely not a single-line change. It's more like a bit of a clean up of how core visuals are updated. But yeah I know how.

**Comment by 20kdc** [comment]
I say a bit of a cleanup, I do just mean a bit. Specifically the problem is the controller sends it's injection state through to the NodeGroup, but when setting up the NodeGroup there's no injection state, so whatever state it uses would probably end up wrong. Better to have the NodeGroup pull the injection state from the master controller instead.

**Review by Zumorica — APPROVED** [review]

**Pull request merged**
