### PR TITLE
Saturate the captain's palette

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Made the captain's palette deep blue like how it used to be
## Why / Balance

The more saturated blue allows the captain to stand out more. Given the importance of the captain in gameplay I feel like having the captain stand out visually would help emphasize this importance.
## Technical details

n/a
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

it's a saturation change i don't feel like it's important enough for a cl

### CODE REVIEW

**Comment by UbaserB** [comment]
i prefer the desaturation more

**Comment by deepdarkdepths** [comment]
Yeah desaturation is preferred for me too. I dont think its necessary considering the captain is the only blue guy you're ever going to see on the station and their outfit is recognizable quickly even to new people.

**Comment by EmoGarbage404** [comment]
I think the more saturated palette detracts from the look and makes the captain look fairly cartoon-y. I don't really take any issue with the current captain outfit. Thank you for your contribution, but I'm opting to close the PR at this time.

**Comment by MACMAN2003** [comment]
> I think the more saturated palette detracts from the look and makes the captain look fairly cartoon-y. I don't really take any issue with the current captain outfit. Thank you for your contribution, but I'm opting to close the PR at this time.

Could you discuss this with the other maintainers before closing it?

**Comment by mirrorcult** [comment]
art directors (emogarbage, flareguy, brainfood at the moment) generally have more authority to close PRs on this basis

**Comment by MACMAN2003** [comment]
could it discussed with the other art directors then?

**Pull request closed without merging**
