### PR TITLE
make holofans destructable

### LINKED ISSUE #20352: Holofans need to be damageable/destrucible
Nukies hate this one weird tick!
Content Client_GwbDX2fgTM

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Fixes #20352 

## Why / Balance

oh yeah baby i love blatantly broken mechanics

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Holofans can now be destroyed by explosions.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
video demonstration? can bullets still go through? will wide swinging prioritize players or the holofan?

**Review by Partmedia — APPROVED** [review]

**Comment by iacore** [comment]
You can't hit it with melee. Bullets still go through. Laser go through.

**Comment by GoodWheatley** [comment]
> You can't hit it with melee. Bullets still go through. Laser go through.
> 
> still intangible

The point is that explosions will destroy them now, so you can’t surround a syndicate bomb with holofans and contain the entire explosion.

**Comment by notquitehadouken** [comment]
> > You can't hit it with melee. Bullets still go through. Laser go through.
> > still intangible
> 
> The point is that explosions will destroy them now, so you can’t surround a syndicate bomb with holofans and contain the entire explosion.

atmos techs when their funny gas blocker no longer protects against nuclear warheads

**Pull request merged**
