### PR TITLE
Tator alert refresh

### PR DESCRIPTION
**Pull request by GTRsound**
Refreshed the tator alert for the modern era of robust toolbox!

replaces old sound, keeps the same length and decibel level although perceived loudness might be a little bit louder than the old one on the LUFs side.

for quick preview:
https://soundcloud.com/alvo_gtr/tatoralert/s-t8Kl6DJy0wj?si=a53b2061f5d8492ebe77509bdd19c7ce&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

-Sound design done in serum with post FX
-Kontakt library used for orchestral sounds and some sound design
-Splice loop for string ambience

:cl:
- tweak: Picked as traitor sound changed

### CODE REVIEW

**Comment by mirrorcult** [comment]
this sounds pretty sick. sound needs to be converted to mono, though

**Comment by GTRsound** [comment]
ah shit, stereoized it trying to make it sound all modern and shit. can definitely squeeze it to mono though.

**Comment by DogZeroX** [comment]
You are forced to do a new one for nukies after this :>

**Comment by mirrorcult** [comment]
actually maybe this is supposed to be stereo i might be high. cause its not positional

**Comment by mirrorcult** [comment]
the old tatoralert is mono so now im not sure

**Review by vulppine — APPROVED** [review]
wew lad

**Comment by GTRsound** [comment]
off to nukie alert

**Pull request merged**
