### PR TITLE
add igniter

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds igniter from ss13 which can be used to spark fires with a signal
can be made in protolathe using 3 steel 1 glass 1 plastic via the explosives technology

## Why / Balance
- very nice for starting up burn chamber, use igniter instead of tossing in a welder with holofan or flushing it in via disposal
- can be used for sussy item soon...

## Technical details
- made SetIgnited in IgnitionSourceSystem public
- added IgniteOnTrigger component/system

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/c12bdc5d-6e36-4ecf-b5d7-454c22f75d77

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Added the igniter for sparking flames, can be found in the vendomat and robotics vendor or produced by science.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
single tank bombs when

**Comment by JoeHammad1844** [comment]
well you'd need an infrared sensor for that actually. at least for the GAMER configuration

**Comment by deltanedas** [comment]
tile bomb trust
- implement window breaking from pressure
- put your bomb mix in window
- put igniter in the bomb box
- blindfold someone and put them next to it
- :trollface:

**Review by mirrorcult — APPROVED** [review]

**Comment by Geekyhobo** [comment]
am hurt lol
#16874

**Comment by Geekyhobo** [comment]
this was much more well done than when i did it although

**Comment by deltanedas** [comment]
this is item not structure :trollface:

**Pull request merged**
