### PR TITLE
Box Update 2.1

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-service worker spawn lmao
-more firelocks in maints so spacing isnt mega mode
-firelocks over bar for bartender
-mail room has a cargo box..,,
-holodeck is now halloween themed!
-skub

### CODE REVIEW

**Comment by Emisse** [comment]
wrong changelog oop fixenow

**Comment by mirrorcult** [comment]
what does a halloween themed holodeck entail

**Comment by Emisse** [comment]
hanted fores..,

**Comment by mirrorcult** [comment]
understood

**Pull request merged**
