### PR TITLE
Remove spare CE belt

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

CE spawns with it and there's not really a point in there being a second one.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Removed the spare CE belt.

### CODE REVIEW

**Comment by moonheart08** [comment]
no fun allowed!!!!

**Comment by PJB3005** [comment]
The belt should have stayed in the locker and the CE should have spawned with no belt instead.

**Comment by deltanedas** [comment]
why would ce not have a belt when every techie, engi and atmosian does have one

also this is probably just to troll atmos begging ce for belt roundstart

**Comment by PJB3005** [comment]
> why would ce not have a belt when every techie, engi and atmosian does have one

Ok fine then do what SS13 does where CE starts with a *regular* belt and the belt in the locker is empty.

> also this is probably just to troll atmos begging ce for belt roundstart

So? It's special equipment for a reason.

**Pull request merged**
