### PR TITLE
Register more console commands for admins and mods

### PR DESCRIPTION
**Pull request by Moneyl**
This adds more console commands to `groups.yml` so they're available for admins and not just from the server console. I tested every command and excluded ones that can still crash the client or server if given invalid arguments.

Commands given to admins:
- `kick` - Kick a player from the server (also added for mods)
- `listplayers` - List all players connected to the server (also added for mods)
- `loc` - Gives location of specified player (also added for mods)
- `lsmap` - Lists all the maps and info about them
- `lsgrid` - Lists all grids and info about them
- `mindinfo` - Displays info about specified players mind
- `addrole` - Add role to player
- `rmrole` - Remove role from player
- `srvpopupmsg` - Display a popup message for the specified player
- `cvar` - Change cvars. Unsure what can be done with this so let me know if it should be server console only.
- `netaudit` - Lists info about NetMsg security
- `showtime` - Lists server uptime
- `szr_stats` - Serialization stats
- `mem` - Memory allocation stats
- `group` - Supposed to list current group but really does nothing if not used from server console

Commands not added because they can crash the server with invalid args:
- `addai`
- `rmgrid`
- `gc`

Commands not added because they can crash the client with invalid args:
- `loglevel`
-  `testlog`

Commands not added because unsure if they should be server console only:
- `addmap`
- `rmmap`
- `savebp`
- `loadbp`
- `savemap`
- `loadmap`
- `pausemap`
- `unpausemap`
- `querymappaused`
- `mapinit`
- `shutdown`
- `saveconfig`
- `gc_mode`

I'd appreciate some feedback on if anything should be moved around/fixed. Not completely sure what is safe to give to admins and what should be server console only.

### CODE REVIEW

**Comment by PJB3005** [comment]
`cvar` is definitely not something you want exposed to regular administrators.

Same with `netaudit` really.

Maybe have a separate role for login local? Man I wish we had SS13's matrix permissions.

**Comment by Moneyl** [comment]
I guess could make a host role that's used for local login and add all the stuff that we don't want admins to have to it. Should the commands that can crash the server be left server console only or should I add them to the host role? Since right now the only way coders can access higher privilege commands is to login, they'd be getting the role with things admins don't have. 

I can see it two ways. We leave the ones capable of crashing as server console only so we don't crash the server constantly. Other option is to give us all the tools until we get a proper account system to assign perms to. Might be useful when bugfixing on the public server for us to have access to everything. Watchdog should handle when we accidentally crash the server.

**Comment by PJB3005** [comment]
Could also just fix the command to not crash the server.

**Comment by Moneyl** [comment]
Alright, might as well while I'm on it. `addai` is a client command and all the others are in the engine. It fine to do all the engine commands in one PR since there's so few?

**Comment by PJB3005** [comment]
Sure.

**Comment by Moneyl** [comment]
Ok. #708 fixes `addai`, [engine #980](https://github.com/space-wizards/RobustToolbox/pull/980) fixes `loglevel`, `testlog`, and `gc`. Wasn't able to fix `rmgrid`. It crashes when trying to delete any grid, see [engine #981](https://github.com/space-wizards/RobustToolbox/issues/981). Will add a host role and re-add some of the fixed commands soon.

**Comment by Moneyl** [comment]
Ok. Made a host group and gave it the commands that admins probably shouldn't have. Excluded `rmgrid` since it still causes crashes and I dunno how to fix. Linked the engine issue for that in the last message. Have [engine PR](https://github.com/space-wizards/RobustToolbox/pull/993) that makes the login command use the host group.

**Comment by Moneyl** [comment]
Also added the commands that were fixed and gave anything I wasn't sure who should have to the host group.

**Pull request merged**
