### PR TITLE
DoAfter Refactor Fixes

### LINKED ISSUE #14273: Doafters are currently broken.
## Description

Doafters are currently broken now; not sure if this PR caused it. Linking a video for easier explanation.
Crowbaring an active fire airlock also does nothing now.

**Reproduction**

See video

**Screenshots**

https://user-images.githubusercontent.com/121047731/221356298-032ca3ea-ee38-4ffe-b243-c7e73c11dc11.mp4

**Additional context**

### PR DESCRIPTION
**Pull request by keronshb**
## About the PR

closes #14273

What this fixes:

BotanySwab/Disease Swab - Does not double dip uses (was activating twice because of the swab having a doafter for plants and one for humans). Grabs the disease data now correctly too.
Healing - Prevents multi-use, actually heals the target now.
Drinks - Prevents multi use on force feeding targets
Food - Prevents multi use on force feeding targets
Tile Prying - Prevents multi use on multiple tiles
Door Prying - Fixes an issue where doors wouldn't be able to be pried again if cancelled.
Syringes - Prevents multi use on injecting self/targets.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: BotanySwab/Disease Swab - Does not double dip uses (was activating twice because of the swab having a doafter for plants and one for humans). Grabs the disease data now correctly too.
- fix: Healing - Prevents multi-use, actually heals the target now.
- fix: Drinks - Prevents multi use on force feeding targets
- fix: Food - Prevents multi use on force feeding targets
- fix: Tile Prying - Prevents multi use on multiple tiles
- fix: Door Prying - Fixes an issue where doors wouldn't be able to be pried again if cancelled.
- fix: Syringes - Prevents multi use on injecting self/targets.

### CODE REVIEW

**Comment by deltanedas** [comment]
its not just for force-feeding, eating it yourself also has same effect

**Comment by keronshb** [comment]
> its not just for force-feeding, eating it yourself also has same effect

Yes, that's fine.

**Comment by deltanedas** [comment]
interesting new meta is codified if this is merged as-is

**Comment by potato1234x** [comment]
tbh the tile prying was pretty cool for a bug

**Comment by potato1234x** [comment]
does this also fix removing encryption keys?

**Comment by deltanedas** [comment]
(removing encryption key from a headset would make like 20 popups)

**Comment by TokenStyle** [comment]
This is next PR for DoAfter refactor https://github.com/space-wizards/space-station-14/pull/13225 fixes

**Pull request merged**
