### PR TITLE
Add the ability to put hats on medibots

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Lets you put hats on Medibots
## Why / Balance

:)
## Technical details

Creates an inventory template for the Medibot and applies the components needed to support it
## Media

Screenshot 2024-06-03 233425Screenshot 2024-06-03 233535
Screenshot 2024-06-03 233549Screenshot 2024-06-03 233417

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: You can now put hats on Medibots

### CODE REVIEW

**Comment by engineer-pearl** [comment]
I don't think this will make it in with the feature freeze but the answer is both :) and traffic cone. 

Can you do the janibots as well?

**Comment by AJCM-git** [comment]
Feature freeze, request to have it reopen once it's done

Also, there should be multiple inv default templates for both hat and the other combination monkeys and hamlet use and a default entity prototype that they inherit to avoid all this duplication

**Comment by Brandon-Huu** [comment]
Aren't you supposed to put the feature freeze label on this?

**Comment by AJCM-git** [comment]
i could have sworn i did wtf

**Comment by Cojoke-dot** [comment]
Reopen pwease

**Comment by Cojoke-dot** [comment]
> Also, there should be multiple inv default templates for both hat and the other combination monkeys and hamlet use and a default entity prototype that they inherit to avoid all this duplication

Can you reword this? I'm confused what you are asking me to do.

**Comment by deltanedas** [comment]
monkeys wear more than hats to still need its own layout

**Comment by engineer-pearl** [comment]
Borgs can only wear hats that others put on them, so if we want to reuse anything, I would suggest that one.

**Comment by deltanedas** [comment]
yes it works the exact same way as borgs

**Comment by Cojoke-dot** [comment]
I can't merge the layouts, all of them are unique and you can't parent inventoryTemplate

**Comment by AJCM-git** [comment]
> I can't merge the inventorys, all of them are unique and you can't parent inventoryTemplate

could have sworn there were at least two that were almost identical, anyways, mostly meant making a common proto with `UserInterface Strippable InventorySlots Inventory(default template, just here to make the purpose of the proto clearer)` components and make the things using displacement maps (monkey, manequinn, etc) inherit that (and then some cleanup of repeated comps of course)

**Comment by Cojoke-dot** [comment]
It has the issue of the hat rotating based on the direction the medibot is moving

**Comment by deltanedas** [comment]
transform norot should help but idk how it would interact with space medibot

**Comment by Cojoke-dot** [comment]
> transform norot should help but idk how it would interact with space medibot

I tried that one previously, no success.
image

**Comment by metalgearsloth** [comment]
> transform norot should help but idk how it would interact with space medibot

Transform norot on entities is a bad idea, do you mean sprite norot.

**Comment by deltanedas** [comment]
sprite is already norot unless theres a way to make the clothing layers norot too

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
