### PR TITLE
Move Access & AccessReader to shared.

### PR DESCRIPTION
**Pull request by ElectroJr**
This just moves the `Access` and `AccessReader` systems & components to shared. In preparation for eventually ECS-ing & predicting door opening/closing

Changes include:
- Moving files
- Namespaces changes
- Renaming the `AccessReader` class to `AccessReaderComponent`
- Defining an abstract `TryGetSlot` in SharedInventoryComponent with an implementations in the client & server versions.

This last change was required for the `AccessReaderSystem.FindAccessTags()` function. The name is just from the existing client-side function. It should probably have a more descriptive name like `TryGetSlotEntity` or something, but I'd rather not make more changes and cause issues for the `InventoryComponent` refactor.

### CODE REVIEW

**Comment by Macoron** [comment]
So now hacked clients can see all access that ID card have?

**Comment by metalgearsloth** [comment]
Ideally it'd fall under "only send state to holder" probably so doors can be properly predicted.

**Comment by ElectroJr** [comment]
Well currently it's not networked yet, but it would have to be eventually. Instead of just making it networked I could create a networked event that only sends the access data to a client when they pick up or equip the ID card. As far as I know there is currently no way to easily selectively send component states only to specific clients, and it just has to be done that way with a custom networked event every time.

But yes, then a hacked client could inspect a card's access permissions simply by picking up an ID card. Getting prediction working will in general make hacking easier. If hacking becomes a problem, I'd much rather have smoothly operating doors and just play on whitelisted & well moderated servers than deal with lag.

**Comment by metalgearsloth** [comment]
> As far as I know there is currently no way to easily selectively send component states only to specific clients, and it just has to be done with custom networked events.

There was but it got nuked recently so we can optimise a fast path and it's intended that this is added back in later as a slow path.

**Review by ShadowCommander — APPROVED** [review]

**Pull request merged**
