### PR TITLE
Add a health overlay for eye equipment

### PR DESCRIPTION
**Pull request by PrPleGoo**
## About the PR
Add a health overlay for eye equipment

**Media**
ezgif com-gif-maker

**Changelog**
:cl:
- add: added an overlay for the diagnostic hud that displays relative health for inorganics
- add: added an overlay for the medical hud that displays relative health for biologicals

### CODE REVIEW

**Comment by Emisse** [comment]
diagnostic hud is for showing integrity of silicons and exosuits

**Review by moonheart08 — CHANGES_REQUESTED** [review]
this is literally just healthoverlaysystem but worse. Do not duplicate code. Do not copy-paste. Write a generalized system.

**Comment by PrPleGoo** [comment]
> diagnostic hud is for showing integrity of silicons and exosuits

Yeah, it shows healthbars for inorganic damage containers:
ezgif-1-798b78183b

**Comment by PrPleGoo** [comment]
> this is literally just healthoverlaysystem but worse. Do not duplicate code. Do not copy-paste. Write a generalized system.

Didn't know that existed, thanks!
I'll have a look on Thursday.

**Comment by PrPleGoo** [comment]
I had an expected extra hour of time :)

**Comment by PrPleGoo** [comment]
I don't like how the existing system's health bars look and I'm not a fan of showing the "crit" healthbar when a mob is still alive. However, I consider these to be wholly other issues that I'm not going to touch. While I was down there I did fix the health bars on mobs without a critical state.

**Pull request closed without merging**
