### PR TITLE
adjust artifact probability equation

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
adjusts the equation to be a normal distribution with a std. deviation of 0.75.
**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl just maff

### CODE REVIEW

**Comment by ElectroJr** [comment]
Not directly related to this PR, but AFAICT GetRandomTrigger()/GetRandomEffect() can error if there is nothing at the target depth that satisfies the black/white lists.

**Comment by EmoGarbage404** [comment]
> Not directly related to this PR, but AFAICT GetRandomTrigger()/GetRandomEffect() can error if there is nothing at the target depth that satisfies the black/white lists. So this PR could probably also fix that.

this can't happen, as the depths themselves are derived from the prototypes. Then it calculates the probability for each depth, before finally selecting one at the end.

**Comment by ElectroJr** [comment]
The main problem is that the whitelists aren't checked prior to selecting a depth. So if you had only a single prototype with a depth of 100, and it had some selective entity whitelist, currently the randomization could randomly choose that depth 100 before applying the whitelist, leading to it trying to pick from an empty list.

**Comment by EmoGarbage404** [comment]
ah. I guess that currently isn't a problem because none of the depths have only effects with whitelists on them.

**Pull request merged**
