### PR TITLE
Role localization

### PR DESCRIPTION
**Pull request by Rinkashikachi**
## About the PR

In this PR I've localized departments and antag roles. You can see departments in character editor and during late join role selection. These are role categories. "job" was localized, but the names themselves like Security or Civilian were not.

Also I've localized antag role name and descriptions. These can also be seen in character editor. Nothing fancy.

### CODE REVIEW

**Comment by Rinkashikachi** [comment]
I have no idea why this failed

**Comment by Rinkashikachi** [comment]
@metalgearsloth sorry for tagging you, but is it possible that check failed for no reason? This happened to me once already during my first PR, I've performed basically an empty commit and the check passed,

Everything works fine on my end, test, which fails here, passes on my end. This PR is not affected by other changes and I didn't do anything new.

**Comment by mirrorcult** [comment]
yes, this test failure is erroneous, most likely a pooling issue. i can rerun checks

**Comment by Rinkashikachi** [comment]
> yes, this test failure is erroneous, most likely a pooling issue. i can rerun checks

thanks

**Comment by Rinkashikachi** [comment]
> > yes, this test failure is erroneous, most likely a pooling issue. i can rerun checks
> 
> thanks

yup. it worked

**Comment by Rinkashikachi** [comment]
While this was hanging someone else implemented part of this PR into the master

**Comment by metalgearsloth** [comment]
PR probably needs re-doing. Role timers was first and needed to do it for proper tracking.

**Pull request closed without merging**
