### PR TITLE
Space Dragons can't be flashed

### PR DESCRIPTION
**Pull request by Lyroth001**
## About the PR

Removed flash from Space Dragons status whitelist

## Why / Balance

Getting flashed as a dragon feels bad, especially considering they already have bad vision in the dark. This would make it harder for sec to fight them, however I think its fitting for a dragon to be immune

## Technical details

Overwritten whitelist inheritance from basesimplemob

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Shouldn't be any

**Changelog**

:cl:
- tweak: Dragons are immune to flashes

### CODE REVIEW

**Comment by slarticodefast** [comment]
Better than the FlashImmunityComponent would be to remove the Flashed effect from the whitelist of statuseffects. The same should be done for the skeletons.

**Comment by Cojoke-dot** [comment]
> > Better than the FlashImmunityComponent would be to remove the Flashed effect from the whitelist of statuseffects. The same should be done for the skeletons.
> 
> Couldn't dragons be converted in revs then? Eh that sounds funny do it anyway.

nah, they are immune to being converted to revs

**Comment by slarticodefast** [comment]
The event gets cancelled either way, both FlashImmunityComponent or dewhitelisting work. So they won't be converted. Not having it in the whitelist is the better way to do it in my opinion, in case someone will automatically look up the applicable status effects in the future, for example for some sort of beastiary listing various mobs' weaknesses.

**Comment by Lyroth001** [comment]
> Better than the FlashImmunityComponent would be to remove the Flashed effect from the whitelist of statuseffects. The same should be done for the skeletons.

Where is the whitelist? I can't find anything like that in the yml or any obviously dragon related files elsewhere

**Comment by slarticodefast** [comment]
Here is an example from `simplemob.yml`, which I think the dragon inherits from.

grafik

You will have to overwrite them, so make sure to list the others that should still be applied again.

**Comment by Lyroth001** [comment]
> Here is an example from `simplemob.yml`, which I think the dragon inherits from.
> 
> grafik
> 
> You will have to overwrite them, so make sure to list the others that should still be applied again. The inheritance for status effects could probably use some clean up in general.

Forgot inheritance was a thing lmao, there's the issue. Thanks!

**Review by slarticodefast — APPROVED** [review]
Tested it in-game, works as intended.
The test fail is unrelated.

**Comment by slarticodefast** [comment]
Thank you for contributing :)

**Pull request merged**
