### PR TITLE
Resolve ClustergrenadeVisualizer is Obsolete

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About the PR

Splits the ClusterGrenadeVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Review by metalgearsloth — DISMISSED** [review]
Pretty sure this already has a component.

**Comment by TemporalOroboros** [comment]
> Pretty sure this already has a component.

Do you want me to move the base state to shared (and thus the server) or split SharedClusterGrenadeComponent?

**Review by AJCM-git — CHANGES_REQUESTED** [review]
pretty sure you can make this a generic visualizer

**Comment by TemporalOroboros** [comment]
> pretty sure you can make this a generic visualizer

Number of grenades is not within set bounds.

**Comment by TemporalOroboros** [comment]
> Pretty sure this already has a component.

No such component exists in shared or client.

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
