### PR TITLE
operating table fix

### PR DESCRIPTION
**Pull request by Emisse**
first time i ever seen this why the fuck is it a table and not a bed its fixed now it wont spit you into the wall. i guess this now also fixes a debug assert in maps with operating tables that somehow had rotation despite being norot to begin with

🆑 
- fix: Operating table won't get you stuck in walls anymore

### CODE REVIEW

**Review by AJCM-git — CHANGES_REQUESTED** [review]
wouldnt this inherit the bed construction?

**Comment by Emisse** [comment]
no

**Comment by Emisse** [comment]
image
image
image

**Comment by Emisse** [comment]
although this test is throwing a silly 
image

**Comment by AJCM-git** [comment]
> although this test is throwing a silly image

core dying now

**Pull request merged**
