### PR TITLE
Cargo Bags

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds cargo bags because grey bags weren't enough

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added bags for cargo techs.

### CODE REVIEW

**Comment by UbaserB** [comment]
why does the satchel have 4 pixels of blue? its not consistent

**Comment by potato1234x** [comment]
wait what where

**Comment by UbaserB** [comment]
> wait what where

in the middle, around the bottom

**Comment by potato1234x** [comment]
shit im a bit colorblind lemme fix that

**Comment by deltanedas** [comment]
spicy

**Pull request merged**
