### PR TITLE
Sliceable doAfter

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
change the way food is sliced - food is now sliced whole after a small doafter than requires multiple clicks on a single entity

## Why / Balance
- new entities appearing after each click prevented cutting the food further, which led to pixelhunting of the corner of the sprite, where you can often click to cut the whole dish.
- we don't have a visualization of half sliced food, and a full circle of cheese is no different than a circle of cheese with only one slice left in it. This causes dissonance. Now the food is either fully whole or fully sliced.

## Media

https://github.com/user-attachments/assets/50f131ee-07dc-4120-bcc0-29c1c9bd0c0d

**Changelog**
:cl:
- tweak: change the way food is sliced - food is now sliced whole after a small doafter than requires multiple clicks on a single entity

### CODE REVIEW

**Comment by UbaserB** [comment]
As someone who plays a lot of chef, this is an incredible upgrade thank you.

**Comment by themias** [comment]
The pixel-hunt problem is real, but I gotta admit that there's something satisfying about *CHOP CHOP CHOP CHOP*

**Comment by ps3moira** [comment]
Feel like stuff like meat shouldn't have a do-after. Gives more control

**Comment by Hrosts** [comment]
>The pixel-hunt problem is real, but I gotta admit that there's something satisfying about CHOP CHOP CHOP CHOP

This

Maybe it should have a chain of short do-afters with each slicing off one piece? And to have it play the chopping sound on each. Basically make it similar to how magazines are reloaded. This would both remove pixel hunting for most cases and keep the aesthetic part unscathed.

**Comment by TheShuEd** [comment]
> Maybe it should have a chain of short do-afters with each slicing off one piece? And to have it play the chopping sound on each. Basically make it similar to how magazines are reloaded. This would both remove pixel hunting for most cases and keep the aesthetic part unscathed.

I don't think the doAfter sequence is a good idea, given that it can be interrupted, and again the second problem arises

**Comment by TheShuEd** [comment]
> Feel like stuff like meat shouldn't have a do-after. Gives more control

it's easily customizable through yml, anyone can did it now.

**Comment by TheShuEd** [comment]
> but I gotta admit that there's something satisfying about _CHOP CHOP CHOP CHOP_

I guess I just need to find a better default sound than the lonely CHOP right now

**Pull request merged**
