### PR TITLE
nukeops.ogg spawn alert with more soul

### PR DESCRIPTION
**Pull request by GTRsound**
Nuke Ops revamp

-Changed TTS from illegible roboaids to the same TTS used for traitortot
-Added hype metal backing music (supplied from splice)
-SFX work to make it all gel together

need those nukies to be overdosing from adrenaline all the way from winning the rngesus lottery to the alert which now slams you to your seat with a fuck mothering metal track provided from LOWTOW's splice pack.

preview link: https://soundcloud.com/alvo_gtr/nukeops/s-xYgvqj5VfLI?si=20154dba6ecf4334a18669f2b8f6d622&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
I like the new sound but the current one already gives that feeling of "oh shit, we're gonna kick some ass today". Just my 2c

**Comment by ikamuse** [comment]
it feels over exaggerated and very out of place for me, i personally think the current one needs somewhat of a change but this leans too much into being childish.

**Comment by Veritius** [comment]
The music feels really out of place.

**Comment by Veritius** [comment]
Also, licensing. What's the license for this asset? What's the license for the backing music? What's the license for the TTS? You really need to name this stuff.

**Comment by theashtronaut** [comment]
hearing it at full volume on my browser, maybe the pumped up music could be a little quieter compared to the TTS as it's pretty difficult to make out the words
otherwise I personally like it more than the existing one :woman_shrugging:

**Comment by GTRsound** [comment]
> Also, licensing. What's the license for this asset? What's the license for the backing music? What's the license for the TTS? Is your usage compliant with the resources' licenses? You need to write this down in the licensing file.

Can update licensing for the splice samples, however the TTS is coming out of an FL Studio VST, so it's my resource. Going to rework this in the meantime.

**Pull request closed without merging**
