### PR TITLE
Make miners respect AtmosDeviceUpdateEvent.dt

### PR DESCRIPTION
**Pull request by quatre**
## About the PR

Make miners respect AtmosDeviceUpdateEvent.dt

Miners' prototype have been changed to reflect this (I read somewhere that we have about 1 atmos tick/0.5s, my tests show more like 1/0.53 but that looks close enough).

This also means that miner's spawnAmount is now expressed in mol/s.

See: #18781

## Why / Balance
People were reporting miners "stopped working after a while". Not sure this is the fix (or there is even a problem), but it looks right.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Partmedia** [comment]
This looks fine to me. I see that you have already adjusted the YAML such that the before/after mining rate is roughly the same.

Please document the units in `GasMinerComponent.cs` so that it is abundantly clear that this is a "moles/sec" instead of "moles per effective atmos tick."

**Comment by quatre** [comment]
Thanks for the review, I'll add the comment when I have a moment later today.

Not necessarily to be handled as part of this PR but: I also noticed that miners don't benefit from the atmos speedup introduced in #21954.
I feel they should (after all, they are a bit like big "pumps" too), but I am not 100% sure.

If we give them the atmos speedup however, we'll probably need to adjust the code so the miner produces gas up to the target pressure. As of now, miners don't mine at all if there's no "room" for the whole spawnAmount.

**Review by Partmedia — APPROVED** [review]

**Comment by Partmedia** [comment]
I'm going to remove the changelog; players shouldn't actually notice any change.

**Comment by Partmedia** [comment]
Thanks for your contribution!

I personally don't think that the speedup should affect mining rate, but happy to discuss this further. While you're right that presumably the miners are pumping from somewhere, in game terms this is effectively a resource spawner, whereas `atmos.speedup` is about making things already on the station pump faster.

You may consider changing the pressure bound check anyway, because it's quite possible that this is limiting the mining rate.

**Comment by quatre** [comment]
With your explanation (speeding-up things already on the station), I can also see why we would not factor in `atmos.speedup`.

If I have a moment I'll change the pressure check because it reflects better how I think it should work (dare I say "in reality" ?), but I'm not sure it's currently limiting the mining rate: unless I missed something, pressure around the miner never seems too close to `maxExternalPressure` in-game.

**Comment by Partmedia** [comment]
You're welcome to take a look at improving the bounds check; but if it's not limiting perhaps it just becomes a problem for later:tm:. Thanks again for your PR and in advance for improvements elsewhere.

**Pull request merged**
