### PR TITLE
Adds catgirls

### PR DESCRIPTION
**Pull request by Zumorica**
This has been a long time coming.

### CODE REVIEW

**Comment by unusualcrow** [comment]
took you long enough

**Comment by Zumorica** [comment]
This was still a WIP so I'll close it for now..... :wink:

**Comment by Zumorica** [comment]
This needs some more time in the oven, closing for now!
Maybe next year, though... :wink:

**Comment by OctoRocket** [comment]
uh oh

**Comment by Kromabae** [comment]
DONT LET THIS APRIOL 1st MEME DIE LET IT BE A THING :D

**Comment by Peptide90** [comment]
> DONT LET THIS APRIOL 1st MEME DIE LET IT BE A THING :D

#6939 ;) it's past 12 o clock here.

**Comment by ScalyChimp** [comment]
> DONT LET THIS APRIOL 1st MEME DIE LET IT BE A THING :D

look at the changed files

**Comment by Fishfish458** [comment]
These species seem kind of OP compared to the other ones right now, I'm not sure they should have the ability to teleport.

**Comment by mirrorcult** [comment]
the vore implementation is stellar but should be moved to a different PR

**Review by DogZeroX — APPROVED** [review]
I approve this.

**Comment by Zumorica** [comment]
After much deliberation, I've come to the conclusion that this PR should be reworked from scratch to ensure I can deliver high quality catgirl code. I estimate that this will take me around a year, so please be patient! :wink:

**Comment by OctoRocket** [comment]
wow 3 years

**Pull request closed without merging**
