### PR TITLE
Fix: Make Plushie Damage Unexaminable

### LINKED ISSUE #33052: damage examine should not be available if the damage is zero
like what
image

### PR DESCRIPTION
**Pull request by thetolbean**
## About the PR
Removes the `examine damage` button from plushies due to the fact that they have no damage.

## Why / Balance
Fix #33052 and remove useless button

## Technical details
Sets `BasePlushie.MeleeWeapon.hidden` field to `true`

## Media
Before (in examine menu):
image
_Image credit to Izk228_

After (Button not visible):
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]
Thanks for the fix!

**Comment by lzk228** [comment]
i think that's not the right fix
it should affect the damage examining code and check if it 0 and then do something i don't know

**Comment by lzk228** [comment]
and the issue is not about the plushies, but the stuff i said above

**Comment by PJB3005** [comment]
> and the issue is not about the plushies, but the stuff i said above

God damnit you're right. I should've checked the original issue.

I do think though that hiding damage values for zero damage by default is not a good idea though. It's not obvious to players that "the button isn't there" means "it does no damage" in my opinion. This isn't a problem with plushies because *they're plushies* but I'm sure there's less-obvious cases.

But yes, the menu should at least show "it does no damage" instead of being blatantly bugged.

**Comment by thetolbean** [comment]
May be reverted if #33064 is merged

**Pull request merged**
