### PR TITLE
Makes rusty walls use /tg/ sprites

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Changes the rusty wall sprites to ones from /tg/, also adds rusty reinforced walls.
Also trims down the yaml for rusty walls since a good amount of it was copypasta'd.

## Why / Balance
image

The current rusty walls (right) are pretty damn ugly, they're literally just noise. I don't really know what else to say.

## Media
Content Client_i3jP0usfjx

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- tweak: Rusty walls have new sprites, courtesy of /tg/station.

### CODE REVIEW

**Comment by UbaserB** [comment]
Waiting for this to be merged, eagerly..

**Comment by EmoGarbage404** [comment]
You're branch is cooked.

**Comment by deltanedas** [comment]
git checkout upstream/master RobustToolbox ops

**Comment by potato1234x** [comment]
very goode pls merge

**Comment by Flareguy** [comment]
Didn't feel like trudging around with submodules so I just made a new PR: #24471

**Pull request closed without merging**
