### PR TITLE
Prevent Digiboard recycling

### LINKED ISSUE #33301: QM's Requsition Digi-board will be turned into cardboard if it falls into the recycler.
## Description

Take the digiboard and put it in a recycler. Now you have a piece of cardboard.
**Reproduction**

1. Take digiboard.
2. Accidentally drop it into the recycler.
3. Pick up cardboard.
**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by thetolbean**
## About the PR
Add the necessary tag to the requisition digi-board in order to prevent it from being recycled

## Why / Balance
Fix #33301 and prevent a high value target from being recycled

## Technical details
Adds the `HighRiskItem` tag to the requisition digi board to prevent it from being recycled

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: The Quartermaster's requisition digi-board can no longer be recycled.

### CODE REVIEW

**Comment by thetolbean** [comment]
@slarticodefast got your suggestion merged
Now I know tags are one of the unfortunate things that gets overridden

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
Thanks for the fix!

**Review by SaphireLattice — APPROVED** [review]
Looks good to me. I would have forgotten about the tag overwriting >_>

This needs to be a lint or something

**Comment by thetolbean** [comment]
> Looks good to me. I would have forgotten about the tag overwriting >_>
> 
> This needs to be a lint or something

I think anyone BUT Slarti would've forgotten it

**Comment by slarticodefast** [comment]
> This needs to be a lint or something

Sometimes you want to overwrite them in order to remove tags from the parent.
And tags get overwritten because the list containing them is a single datafield.

**Comment by SaphireLattice** [comment]
> Sometimes you want to overwrite them in order to remove tags from the parent.

Quite aware, yup.

Was thinking sorta, lint with an easy suppression. "Yes I am aware of what I'm doing, I *want* to ignore the following tags" and have it fail if these tags either don't exist, or there's an extra one on parent that got overwritten.

**Pull request merged**
