### PR TITLE
Make crushers not craftable/researchable

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Crushers/Crusher daggers/Crusher glaives can no longer be researched by sci or printed at protolathes.

## Why / Balance
Crushers got a major buff and no longer should be able to be mass produced. A half-decent sci team could make 20 crusher daggers and suddenly the entire crew has e-sword dps weapons during nukies.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Crushers can no longer be researched.

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]
Remove the comment.

**Comment by metalgearsloth** [comment]
@Emisse

**Comment by Kadeo64** [comment]
people forget that nukies have guns
you're gonna get shot before you can get close with salvage weaponry unless you're hiding around a corner (where you will promptly, be shot)
I think the salvage weapons are balanced but maybe they should be made 7500 points and be moved to tier 2 arsenal

**Comment by GreyMario** [comment]
people forget that there are other uses for the buffed weaponry than just "nukies go brrr"

frankly, the equipment never should have been buffed in the first place, but since we're on a "powercreep salvage" trip, the ability for Normal Crewmembers That May Or May Not Be Antags to access the equipment needs to be cut down severely. _Nothing exists in a vacuum_ (figuratively, at least).

**Comment by vorkathbruh** [comment]
mass producible 45 damage melee was not a good idea believe it or not

**Comment by vorkathbruh** [comment]
nukies gamemode is not even the reason why craftable glaive is unbalanced, it means that any random shitter can have a better weapon than esword with basically roundstart tech to validhunt with (or be antag with, added bonus because they're not contraband!)

**Comment by metalgearsloth** [comment]
Emo mentioned PKA going to cargo instead and I agree but for now this is fine.

**Pull request merged**
