### PR TITLE
Add CI job for building and testing with FULL_RELEASE

### PR DESCRIPTION
**Pull request by DrSmugleaf**
## About the PR
We have the technology.
Looking forward to no longer breaking master unexpectedly.

### CODE REVIEW

**Comment by ike709** [comment]
Might be worth adding one to do `dotnet publish` too, since that currently doesn't work.

**Comment by DrSmugleaf** [comment]
Minor oversight, I didn't remember the resources get read from a different path on full release

**Comment by metalgearsloth** [comment]
Possible to get one for debug in future because it's been broken for a couple of months

**Comment by wrexbe** [comment]
> Possible to get one for debug in future? coz it's been broken for a couple of months

The future is now

**Comment by wrexbe** [comment]
It was way way way too slow doing the content integration test in debug. I'm going to drop that from the action for now, so at cover at little bit of debug builds, instead of nothing.

**Pull request merged**
