### PR TITLE
Makes knives fly straight when thrown

### PR DESCRIPTION
**Pull request by SpaceRox1244**
## About the PR

Makes knives fly straight instead of spinning when thrown so that it looks like the blade is embedding and not the handle.

## Why / Balance

Just visual.

## Media

https://youtu.be/B-87M3x3lFI?si=vXcRumRZO8wKBLAc

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

No CL

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]
I tested it and this looks much better. Thank you for your contribution.

**Comment by SpaceRox1244** [comment]
Thanksies. As a note should I include a short video for things as small as this? Would that make you not have to open it up and test it personally?

**Comment by Plykiya** [comment]
oh cool, I can combine this with my other PR that only makes knives deal damage if you hit with the pointy end

**Comment by slarticodefast** [comment]
> Thanksies. As a note should I include a short video for things as small as this? Would that make you not have to open it up and test it personally?

Yeah, best always include some media. It shows us that PRs have been tested in-game by the author and are not simple web edits. Usually I always test PRs myself before approving, but the author should of course do so as well before. Also media is useful for other players to have a look and give feedback. And the russian game changelog usually adds images or videos from the PR.

**Comment by TheShuEd** [comment]
Yep, good

**Pull request merged**
