### PR TITLE
Remove Rubber Rounds, Give Security Disablers

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
As per #26443, removes all ability obtain rubbers, perhaps they can be readded later when someone figures out how to balance this hell.

---
- Removes all recipes related to rubbers, boxes, mags, rounds. (Not beanbag shells.)
- Replaces all security's sidearms with the lethal variant, meaning they have one mag in the gun and one spare. (The detective just got their non-lethal speedloader removed.)
- Removes the research tech for rubbers, puts beanbags as roundstart tech in the sec techfab.
---
- To replace rubbers, a disabler spawns in every security officer's locker.

## Why / Balance
The linked issue covers most of the "why". But in short, rubbers are extremely hard to balance with disabling tech alongside it, we have a system where rubbers just entirely beat out disablers in any situation currently.

## Media
- [X] This PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added disablers to every security officer locker.
- remove: Any way to obtain rubber bullets has been removed.

### CODE REVIEW

**Comment by thebadman4662** [comment]
Could disabler also get added to secfab? Now that sec will rely on it more, we should probably have option to print them if there are resources... Add to riot tech I guess if roundstart feels to powerful?

**Comment by Nairodian** [comment]
> Could disabler also get added to secfab? Now that sec will rely on it more, we should probably have option to print them if there are resources... Add to riot tech I guess if roundstart feels to powerful?

I could, but I also don't think it'll be an issue. Most maps will still have mapped spare disablers and you can order more from cargo with the nonlethals crate.

**Comment by K-Dynamic** [comment]
Tranqs should also be examined, they're abused quite heavily

Also stingers too, which are based on rubbers

**Comment by vorkathbruh** [comment]
BASED ASF

**Comment by Nimfar11** [comment]
Is it possible to try to create a balance? I have not seen any attempt to balance the rubber. Reduce stamina damage? To make sure that rubber could not penetrate a hard suit and heavy armor?

**Comment by ImWeax** [comment]
> Is it possible to try to create a balance? I have not seen any attempt to balance the rubber. Reduce stamina damage? To make sure that rubber could not penetrate a hard suit and heavy armor?

Then this results in rubbers in pistols being underwhelming. I think removing them is the way to go, disablers & smg disablers fulfill the purpose that rubbers have anyways

**Comment by Nimfar11** [comment]
Rubber is the only way to stun someone after being hit by an EMR.

**Comment by deltanedas** [comment]
different ways to stun without battery:
- slipping
- beanbags
- tranq

**Comment by UbaserB** [comment]
we need energy bola

**Comment by skypatrol21** [comment]
> BASED ASF

I better get 2 lethal mags to fill the hole in my heart

**Comment by thebadman4662** [comment]
> different ways to stun without battery:
> 
>     * slipping
> 
>     * beanbags
> 
>     * tranq

You forgot truncheon, how could you?!

**Comment by rosieposieeee** [comment]
i think this change will just result in more people getting magdumped with lethals when they run out of other options instead of at least having rubbers as a backup

**Comment by ImWeax** [comment]
> i think this change will just result in more people getting magdumped with lethals when they run out of other options instead of at least having rubbers as a backup

This is more an RP / admin issue - security officers by law should not be magdumping lethals into someone just because they cant hit stun batons.



> Rubber is the only way to stun someone after being hit by an EMP.

Per other replies, there is the option of advanced riot control from science, for stun options without battery. Also bolas, stinger grenades, flashing + slipping, etc. In my opinion EMPs should be a valid counter to the 'common' stun options for sec.

**Comment by Nimfar11** [comment]
> Per other replies, there is the option of advanced riot control from science, for stun options without battery. Also bolas, stinger grenades, flashing + slipping, etc. In my opinion EMPs should be a valid counter to the 'common' stun options for sec.

You can defend yourself with points, and a grenade is more likely to stun your own than the enemy. Most of these suggestions are not so convenient or even harmful. Antags are already strong, and further strengthening them I think breaks the balance between sec and antags. If there will be no rubber, the only good option for stun will be stanbaton, which can be easily discharged by EMP. Do antags really suffer so much that rubber keeps them out of play?

Translated with DeepL.com (free version)

**Comment by Golinth** [comment]
A well prepared syndie is already a monster to deal with, why are we making it even harder for security to do their jobs? Like others have said, why not attempt to balance rubbers before going this full nuclear option that further limits security’s ability to do their job without using lethals

**Comment by Golinth** [comment]
> different ways to stun without battery:
> 
> * slipping
> * beanbags
> * tranq

Slipping is not reliable enough to cuff, and both beanbags and tranqs are shotgun only, further cementing the dominance of the shotgun meta.

**Comment by Nairodian** [comment]
To put this into perspective, rubber bullets have been in the game for ~4 years and no one has found a way to balance them yet. It's always been a "Hey someone should fix that," but clearly this has not been done. Stamina code is an absolute mess to deal with in it's current state which makes it none the better.

**Comment by Golinth** [comment]
> To put this into perspective, rubber bullets have been in the game for ~4 years and no one has found a way to balance them yet. It's always been a "Hey someone should fix that," but clearly this has not been done. Stamina code is an absolute mess (from what I've been told) to deal with in it's current state which makes it none the better.

I get that it’s a bitch to work with, and that no one wants to do it, but I genuinely don’t see this going any other way than once an EMP goes out, security goes full lethals due to a lack of accessible options. I’d much rather see rubbers nerfed to near uselessness, to be used as an absolute last resort, than limiting sec’s options by removing them entirely.

**Comment by asperger-sind** [comment]
If hypothetically an antag uses an EMP to prevent their arrest, then magdumping them with lethals is viable and should be encouraged rather than "well they tried to counterplay you, now just use rubbers which didn't get counterplayed".

I'm fine with rubbers being removed because while they do serve a purpose and can theoretically be balanced (weak against armor, etc.), the overall gain from removing rubbers is IMO greater than waiting for a proper fix or just keeping them in.

>A well prepared syndie is already a monster to deal with

Then bring out the big guns. A well-prepared antag should be stronger than a security officer with anything less than an armory firearm.

**Comment by Nairodian** [comment]
> I get that it’s a bitch to work with, and that no one wants to do it, but I genuinely don’t see this going any other way than once an EMP goes out, security goes full lethals due to a lack of accessible options. I’d much rather see rubbers nerfed to near uselessness, to be used as an absolute last resort, than limiting sec’s options by removing them entirely.

All things considered, yeah lethaling someone who EMP'd you is fine escalation. They are actively intentionally trying to disarm you, they know what they're doing, and they should understand that might get them shot.

**Comment by EmoGarbage404** [comment]
ok now make secglasses roundstart

**Comment by Xeno4** [comment]
i have a perfect fucking idea. Make the rubber bullets use `BluntStaminaDamageFactor` for dealing stamdamage. This will actually make stun dependant on the resistance for blunt, that is kinda realistic.

**Comment by Golinth** [comment]
> i have a perfect fucking idea. Make the rubber bullets use `BluntStaminaDamageFactor` for dealing stamdamage. This will actually make stun dependant on the resistance for blunt, that is kinda realistic.

Dude thank you some one else gets me. I’ve been asking what people think about that for ages. And  while we’re at it, make disabler/baton stuns based on electrical resistance. Not many armors, if any, have some, but it opens up the ability for specific suits or traitor items to counter stuns more.

**Pull request merged**
