### PR TITLE
Derelict icon hotfix

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Fixed derelict borg not seeing icons

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by Aeshus — APPROVED** [review]
Seems good as many lawsets still would require knowing who is/isn't crew and this is the current way we handle it.

**Comment by ScarKy0** [comment]
> Seems good as many lawsets still would require knowing who is/isn't crew and this is the current way we handle it.

It was just forgotten and got noticed during a secret playtest tm

**Review by slarticodefast — APPROVED** [review]

**Review by Errant-4 — CHANGES_REQUESTED** [review]
Can you please wait until the publish and rebase this to Stable

**Review by Errant-4 — APPROVED** [review]
I approve, but we need a third one

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
oh wait, I already approved :clueless:

**Comment by Errant-4** [comment]
> oh wait, I already approved :clueless:

10 point for enthusiasm, though

**Review by chromiumboy — APPROVED** [review]

**Pull request merged**
