### PR TITLE
made cognizine work via spray bottle

### PR DESCRIPTION
**Pull request by Interrobang01**
spray-a-brain real

made cognizine work via spraying from fire extinguisher or spray bottle or similar
bonus: it's instant, no metabolism needed
still needs 5u to work though

i can add things other than mobs to the whitelist too, but it seems to not work on items for whatever reason 

## About the PR 

**Media**

https://user-images.githubusercontent.com/113810873/211239616-3f2d83ed-ab3d-4f45-a1d5-ad5b2ff44658.mp4

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Cognizine now works in a spray bottle -- and, it's instant!

### CODE REVIEW

**Comment by mirrorcult** [comment]
i dont know that this really makes sense/is much of a good idea?

**Comment by Interrobang01** [comment]
> i dont know that this really makes sense/is much of a good idea?

I think it does make sense to make more chems usable with spray bottles. The whole system seems rather underutilized.

I guess there are some problems like potentially being able to spray multiple entities at once, plus in the PR's current state it doesn't really bring anything new like spraying sentience on vending machines, but I could always change that.

Ultimately this PR was just me testing chemical spraying, so if I can't easily fix potential issues I'll have to close it.

**Comment by AJCM-git** [comment]
yeah if this can give sentience to multiple entities with a single spray, that should be fixed before it can be merged

**Comment by Interrobang01** [comment]
closing this, will reopen when i decide to work on it again

**Pull request closed without merging**
