### PR TITLE
Fixes ghost duplication on gib

### LINKED ISSUE #3232: Ghost's duplication on gib
## Description
When player's mob is gibbed while player is inside ghost(both MobObeserver or AdminObserver), player would be teleported to gib location and put inside new Ghost, leaving old Ghost inactive and visible.

### PR DESCRIPTION
**Pull request by Injazz**
Still not sure whether culling deleted components is okay, but other solutions are way more hack-ish
Closes #3232

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
1. This should not be `BodyComponent`'s job. It's `BrainBehavior`'s.
2. Do not hardcode prototype IDs checks like that.
3. This *transfers* the mind out of the mob and by extension also the brain, meaning that being revived later with the brain is impossible.

All in all, this is a terrible fix. Make it so that when brainbehavior tries to transfer the mind on gib it instead leaves it in the ghost if it's visiting.

**Comment by Injazz** [comment]
made request changes
https://github.com/space-wizards/RobustToolbox/pull/1564 needs to be merged first

**Comment by Injazz** [comment]
@ShadowCommander  why you closed this PR?

**Comment by ShadowCommander** [comment]
The better fix is #3680

**Pull request closed without merging**
