### PR TITLE
The Mobs of the Living Light

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

A line of mobs composed of light, invulnerable to firearms, and extremely durable to melee attacks. However, they are very vulnerable to laser weapons. 
Two mobs for close combat and one for long-range fire.
Also added one of the mobs to Artifact Polymorphism.

## Why / Balance

Right now, there are few mobs of one type in the game that can be used in expeditions or events. These mobs will provide another choice, perhaps in the future they can be used in night expeditions (they glow brightly, so it is more beautiful).

## Media

https://github.com/space-wizards/space-station-14/assets/128169402/5a3abbf7-57b2-4176-b40e-f7ca095ab752

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11

- add: Adds three new mobs from the Living Light family

### CODE REVIEW

**Comment by mirrorcult** [comment]
these are rly cool, i like the work put into these

**Comment by UbaserB** [comment]
something about the sprite is odd. Not sure if its the clarity, color or shape but yeah idk.

**Comment by TheShuEd** [comment]
I like it
But sprite pallete is strange

**Comment by Nimfar11** [comment]
I'll think about changing the colour scheme.

**Pull request merged**
