### PR TITLE
Use CannyFastMath & Update Packages

### PR DESCRIPTION
**Pull request by Tyler-IN**
Requires space-wizards/RobustToolbox#1130

### CODE REVIEW

**Comment by Tyler-IN** [comment]
includes @ComicIronic's #1123

**Comment by ComicIronic** [comment]
You should explicitly not have to commit submodule changes if you add a "Requires ..." statement to your PR now.

**Comment by TYoung86** [comment]
Note this removes some Decimal stuff cause that just provides a mechanism to slow down the server by fucking with reagents.

**Comment by Tyler-IN** [comment]
Note this removes some Decimal stuff cause that just provides a mechanism to slow down the server by fucking with reagents.

**Pull request merged**
