### PR TITLE
Light bulbs don't burn hands anymore

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Removes the ability to burn yourself on lightbulbs

## Why / Balance

While I understand the point of the feature is part flavor and partly to prevent griefing, anyone motivated enough to grief light bulbs isn't going to take the time to screw the bulbs out one at a time. They're just going to take a crowbar and hit it.

Not only that, but this is one of the only things in the game that you can spam click to actively hurt yourself. People use this as an absurd method of suicide or to cauterize wounds in combat, both of which makes no sense, and the latter diminishes the usage rates of actual methods to stop bleeding like tourniquets, gauze, or cauterizers which SHOULD be the only intended method to stop bleeding.

## Technical details

Removes the GloveHeatResistanceComponent which according to the TODO comment only served the purpose of protecting people from lightbulbs

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

GloveHeatResistanceComponent removed

**Changelog**

:cl:
- remove: You can no longer burn yourself on light bulbs.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
If your primary purpose for removing this is because it invalidates bleeding, then just fix the shitty bleeding and cautery mechanics instead of removing this

**Comment by Plykiya** [comment]
> If your primary purpose for removing this is because it invalidates bleeding, then just fix the shitty bleeding and cautery mechanics instead of removing this

isn't that what newmed is going to do? either way I don't like the spam click suicide either, which is kinda egregious as well

**Comment by EmoGarbage404** [comment]
What does it matter? You can literally suicide instantly with a command.

**Comment by Plykiya** [comment]
> What does it matter? You can literally suicide instantly with a command.

by biting your tongue, sure

but this isn't a suicide command, and it's out of place with all the other things that you interact with in this roleplaying game. it's faster to kill yourself on a light bulb than to run into a high voltage fence, it's faster to kill yourself on a light bulb than stabbing yourself to death, etc etc and in my opinion it doesn't feel like it adds anything fun to the game

**Comment by EmoGarbage404** [comment]
i don't deny that their are issues with some interactions involving lightbulbs (they should probably have an interaction delay and shouldn't cauterize wounds) but i think flat out removing a flavor mechanic because of that is kinda extreme. i'd rather just see the issues voiced here resolved properly rather than just removing this outright.

**Comment by PJB3005** [comment]
Imagine if we just coded light switches instead...

**Comment by MeowVal** [comment]
to be fair you can burn yourself on lightbulbs in real life especially the incandescent type, for LEDs, they need to be pretty bright before they get hot enough for you to burn yourself so for the realism it makes sense, the issue I see is that it can be spam clicked and not the burning in of itself.

**Pull request closed without merging**
