### PR TITLE
Vending machine polish 2

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

i guess im the vending machine guy now

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: Vending machines have been polished. Again.

### CODE REVIEW

**Comment by UbaserB** [comment]
the border at the top of the chef one looks weird imo

**Comment by JoeHammad1844** [comment]
polerowany automat :trollface:

**Comment by potato1234x** [comment]
> the border at the top of the chef one looks weird imo

usually if i change things too drastically people get mad so i tried to stay as close to the original as i could, should i remove it?

**Comment by UbaserB** [comment]
no no the checkered pattern is fine its just the border is pure grey which is weird, id think itd match the checker patterns since it’s still part of it

**Comment by potato1234x** [comment]
so like this
image
or this 
image

**Comment by UbaserB** [comment]
second imo

**Comment by potato1234x** [comment]
done

**Review by PrPleGoo — APPROVED** [review]

**Pull request merged**
