### PR TITLE
Revert "Revert "Tweaks player BB""

### PR DESCRIPTION
**Pull request by SweptWasTaken**
Reverts space-wizards/space-station-14#2264

When is camera rotation ever used in normal gameplay? The upsides of this BB is much better than the downsides which would only be seen on the dev side. (And rarely at that)

### CODE REVIEW

**Comment by PJB3005** [comment]
> When is camera rotation ever used in normal gameplay?

Do you want rotatable shuttles?

**Comment by SweptWasTaken** [comment]
> 
> 
> > When is camera rotation ever used in normal gameplay?
> 
> Do you want rotatable shuttles?

Not at the cost of basic gameplay. Fix BBs first.

**Comment by Zumorica** [comment]
Slipping on soap/banana peels doesn't work as great with the small box BB

**Comment by PJB3005** [comment]
I'd say the box isn't very small in the first place. Also being square makes it much more consistent for if we ever give stuff proper corner nudging.

**Comment by Zumorica** [comment]
Visually your feet can stand on top of a soap bar and you don't slip as long as your chest doesn't touch it. How should we solve this? And there's also the issue of people's feet being on top of a wall when walking into those from above

**Comment by PJB3005** [comment]
The visual feet thing with walls should just be solved by somebody actually bothering to fix the broken Y sorting system.

**Comment by SweptWasTaken** [comment]
> 
> 
> The visual feet thing with walls should just be solved by somebody actually bothering to fix the broken Y sorting system.

Isn't zumorica the one who implemented y-sorting?

**Comment by Zumorica** [comment]
> > The visual feet thing with walls should just be solved by somebody actually bothering to fix the broken Y sorting system.
> 
> Isn't zumorica the one who implemented y-sorting?

Nah, I made a bad PR for it but it got closed in favor of a better one by someone else

**Comment by brndd** [comment]
> Visually your feet can stand on top of a soap bar and you don't slip as long as your chest doesn't touch it. How should we solve this? And there's also the issue of people's feet being on top of a wall when walking into those from above

make soap and banana peel bounding boxes big enough to reach the player bounding box even if they're at their feet

**Comment by PaulRitter** [comment]
does it change anything for this issue that we now have rotatable bbs?

**Comment by PJB3005** [comment]
No @PaulRitter

**Comment by SweptWasTaken** [comment]
Obviously PJBs not gonna budge on this one.

**Pull request closed without merging**
