### PR TITLE
Security Helmet Reshape Redo

### PR DESCRIPTION
**Pull request by DieselMohawk**
## About the PR
 Reshaped the Security helmet to better represent real world examples of helmets and how they sit on the head. Fixes miscoloration on the back of the helmet. Make the ear cover more easily recognizable on the side of the helmet.
Original PR #30961 
Reversion of previous PR #31198 
## Why / Balance
 People tend to not use the helmet due to their opinions on how it looks. 

## Media

image
image
image
Screenshot 2024-08-19 135512

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Reshaped the Security Helmet

### CODE REVIEW

**Comment by Yebok24** [comment]
I don't think people who don't use helmet are going to use it after any resprite. They just want drip instead of protection

**Comment by Iced-Coded** [comment]
> I don't think people who don't use helmet are going to use it after any resprite. They just want drip instead of protection

This. But IMHO it's still a great reshape.

**Comment by UbaserB** [comment]
Apologise for the delay, it took a while to get opinions from the rest of the art director team. It's been discussed and while there there are rather neutral opinions on the minor changes this PR brings, the overall consensus is to close it. The reasoning is that it's not needed as the current helmets look fine, and personally if I were to give a reason it'd be that the silhouette is odd on the equipped sprite and the icon is a little too small/ not detailed enough. Thank you for your contribution.

**Comment by DieselMohawk** [comment]
Alrighty, I'll try again later, thanks for the feedback

**Pull request closed without merging**
