### PR TITLE
fix reflected projectiles dealing stamina damage

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

see #17498
should we fix igniting/stun projectiles too?

**Media**

Peek 2023-06-25 22-32

**Changelog**

:cl:
- fix: fixed reflected projectiles dealing stamina damage

### CODE REVIEW

**Comment by Slava0135** [comment]
gif framerate is shit but you can trust me

**Comment by metalgearsloth** [comment]
Doesn't this break stun baton throws

**Comment by Slava0135** [comment]
> Doesn't this break stun baton throws

Wait, you could throw them to deal stamina damage?

**Comment by Slava0135** [comment]
> Doesn't this break stun baton throws

ok, i actually have no idea what you talking about but stun baton swing works as before

**Comment by Mudsson** [comment]
Does this also fix in incindeary ammo applying fire to reflects?

**Comment by Slava0135** [comment]
> Does this also fix in incindeary ammo applying fire to reflects?

No

**Comment by moonheart08** [comment]
> > Doesn't this break stun baton throws
> 
> Wait, you could throw them to deal stamina damage?

yes

**Comment by deltanedas** [comment]
new nukie meta just play bowling with 2 batons and throw them

**Comment by Slava0135** [comment]
> > > Doesn't this break stun baton throws
> > 
> > 
> > Wait, you could throw them to deal stamina damage?
> 
> yes

it doesn't work on master if so

**Comment by dolgovmi** [comment]
> > > > Doesn't this break stun baton throws
> > > 
> > > 
> > > Wait, you could throw them to deal stamina damage?
> > 
> > 
> > yes
> 
> it doesn't work on master if so

Pretty sure because it's disabled for a long time

**Comment by Just-a-Unity-Dev** [comment]
it's been broken since weapon refactor

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
File-scoped namespace needs reverting because it gets massive conflicts.

**Comment by Slava0135** [comment]
> File-scoped namespace needs reverting because it gets massive conflicts.
> 
> Also just subscribe to ThrowDoHitEvent and the stun batons can probably be fixed.

reverted namespace

don't want to fix batons in this PR (also C# VSCode extension just broke after update and I can't do shit)

**Comment by Slava0135** [comment]
funny, how did this compile locally

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
