### PR TITLE
Cluster Station

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR 
Switches out Omega for a new map, Cluster. If I did anything wrong or if something on the map needs to be changed, please let me know.

**Screenshots**

Cluster-0

**Changelog**

:cl:
- add: Added Cluster, a new low-pop map!
- remove: Removed Omega

### CODE REVIEW

**Comment by lapatison** [comment]
Looks like kitchen entrance have a missing tile
image

**Comment by moonheart08** [comment]
Maybe worth doing a poll, as imo packed should be derotated instead being the second oldest lowpop map (saltern is special, praise be, but i'm willing to replace it should we get a third lowpop)

**Comment by moonheart08** [comment]
Esp as overall I think omega is better than the other two lowpops.

**Comment by Just-a-Unity-Dev** [comment]
Just my 2c but Omega feels really weird, I don't know if it's the layout or the decoration but it just looks really weird to me. Saltern's my favorite though.

**Comment by Scribbles0** [comment]
alright, i'll get a poll going then. i just chose omega cause i thought the 2 maps were a bit similar

**Comment by Just-a-Unity-Dev** [comment]
[poll](https://strawpoll.com/polls/X3nk6O8JjyE0)

**Comment by Scribbles0** [comment]
shit i don't know why my deleted branch stuff is here, i'll get rid of that later

**Comment by mirrorcult** [comment]
looks like people are mostly in agreement to rotate out packed, so get the PR fixed + derotate packed and this is good

**Comment by Scribbles0** [comment]
might just make a new PR if i can't fix the files showing "changes"

**Comment by Scribbles0** [comment]
yeah, i'm just gonna make a new PR cause that's cleaner and i have no clue how to fix the file thing

**Pull request closed without merging**
