### PR TITLE
Hunger and thirst HUDs

### PR DESCRIPTION
**Pull request by PrPleGoo**
## About the PR
Adds some HUDs so the bartender and chef can do their jobs better.
This PR was forked off of #18054, so review that first.

**Media**
Credits to @DerbyX for the icons and the onion ring goggles!
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: Added onion goggles for the chef. It displays hunger icons for hungry/overfed mobs. Can also be eaten.
- tweak: The chef's starting gear now includes the onion goggles
- tweak: The beer goggles now display thirst icons for thirsty/overhydrated mobs.
- tweak: The bartender's starting gear now includes the beer goggles

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i feel like these should definitely be separate research unlocks instead of roundstart equipment. Especially for the beer goggles, which aren't very rare at all.

**Comment by PrPleGoo** [comment]
> i feel like these should definitely be separate research unlocks instead of roundstart equipment. Especially for the beer goggles, which aren't very rare at all.

I don't think there's an issue with having these at round start. Hybrid variants that could do the job of both should be a R&D thing.

**Comment by EmoGarbage404** [comment]
these feel like very strong convenience tools. If the intent is concerns around determining hunger, then that issue should just be fixed. In general, tools for seeing information regarding every player are very strong and shouldn't be regularly given out.

**Comment by PrPleGoo** [comment]
> tools for seeing information regarding every player are very strong

Bruh, it's hunger and thirst.

**Comment by EmoGarbage404** [comment]
i mean yeah it's not the most important thing in the world but it's also a feature that could easily just be put in research, an area that's sorely lacking for chef and bartender and specializes specifically in providing helpful items like these to crew members.

**Comment by PrPleGoo** [comment]
> i mean yeah it's not the most important thing in the world but it's also a feature that could easily just be put in research, an area that's sorely lacking for chef and bartender and specializes specifically in providing helpful items like these to crew members.

I'm not opposed to the idea but I'd rather have _a_ way to get these items in the game without touching research in this PR as well. Can always be added to R&D and removed from starting gear in the same PR.

**Comment by HoidC** [comment]
> i mean yeah it's not the most important thing in the world but it's also a feature that could easily just be put in research, an area that's sorely lacking for chef and bartender and specializes specifically in providing helpful items like these to crew members.

if you add research items for every single category, such as a less useful item for chef/bartender, will they end up ever getting researched?

**Comment by EmoGarbage404** [comment]
> if you add research items for every single category, such as a less useful item for chef/bartender, will they end up ever getting researched?

i mean considering they're strict upgrades to what chef/bartender normally get, i could see that some people might want them. It could also be something medical is interested in, considering how often they deal with starving patients nowadays. I'm just saying that integrating it into a the general upgrade gameplay loop of research could be a benefit.

and especially since these items are relatively weak, they could be T1 research and additionally available in random clothing spawners or something.

**Comment by Emisse** [comment]
I agree that this should be put in research

**Comment by PrPleGoo** [comment]
> I agree that this should be put in research

Should I remove it from the starting equipment so this PR can just go through?

**Comment by keronshb** [comment]
> Should I remove it from the starting equipment so this PR can just go through?

Go for it

**Comment by Emisse** [comment]
im gonna merge this and we can put it in research later, i think its good to familiarize players with it first

**Pull request merged**
