### PR TITLE
Medical Gauze Markings

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR

Adds gauze markings to all limbs, excluding for Diona.

## Why / Balance

It allows players to RP long-term injuries, blah blah expression of character. You can be a burn victim now.

## Media
image_2023-12-08_223123870

**Changelog**

:cl:
- add: Added various gauze wraps to most species in the form of markings

### CODE REVIEW

**Comment by throge** [comment]
I like it. It'd be nice to actually be able to show injuries without having to write it in your description or smt

**Comment by KittenColony** [comment]
note that this doesn't change the markings cap, so you can't go full mummy as a human or dwarf (yet)

**Comment by throge** [comment]
Ah fuck. still good to have anyways

**Comment by KittenColony** [comment]
anyway, tfw you use \ instead of / and it fails the YAML check

**Comment by Kadeo64** [comment]
toilet paper accident

**Comment by lzk228** [comment]
> note that this doesn't change the markings cap, so you can't go full mummy as a human or dwarf (yet)

oh, then good i think

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
