### PR TITLE
Make airlocks able to be broken down (still strong) and modify a damage container to make more sense

### PR DESCRIPTION
**Pull request by Emisse**
yes

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
so what exactly does this change do? other than whats in the files changed thing

**Comment by Emisse** [comment]
mobs will be able to break down doors or mobs of tiders

**Comment by JoeHammad1844** [comment]
well you changed the airlocks damage modifier set to strong metallic, which does the opposite
image
just look at those flat reductions

**Comment by Emisse** [comment]
yes its lower than it was before

**Comment by JoeHammad1844** [comment]
what does structural metallic look like? i cant find it in modifier_sets.yml

**Comment by Emisse** [comment]
its what i put on walls

**Comment by JoeHammad1844** [comment]
i mean, what are the resistances and reductions

**Comment by Emisse** [comment]
look on master

**Comment by JoeHammad1844** [comment]
im confused

**Comment by deltanedas** [comment]
thats definitely stronger than before

**Comment by Emisse** [comment]
no it was using structural before

**Comment by Emisse** [comment]
because i literally implemented it the day before

**Comment by Emisse** [comment]
STOP NECRO POSTING MY BALANCE CHANGES

**Comment by JoeHammad1844** [comment]
lmao i had an outdated version of the code on my PC

**Pull request merged**
