### PR TITLE
Terminator Resprite

### PR DESCRIPTION
**Pull request by xKREKSx**
may have gotten some things wrong, since this is my first PR.
## About the PR

Resprite all the body parts of the "terminator" antagonist.
Resprite terminator skull icon
## Why / Balance

the new sprites look better to me than the old ones.

## Media
Видео без названия — сделано в Clipchamp
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Emisse** [comment]
the torso midsections shape looks a bit too square compared to the original one.

**Comment by EmoGarbage404** [comment]
i think the wires detract from the aesthetic of it. I really like the colors tho

**Comment by IProduceWidgets** [comment]
Makes me think of christmas

**Comment by brainfood1183** [comment]
I like the new skull sprite. I dont really like the new character sprite, i feel as though the added wiring muddles the appearance of the cyborg a little to much. I understand the original sprite is a little bland colorwise and possibly to blue but the old sprite is at least easy to interpret. Prehaps a color change is needed to move away from the blueness but i think the wiring is a bit to much.

**Comment by deltanedas** [comment]
keep wires as christmas rsi, remove otherwise :trollface:

**Review by TheShuEd — CHANGES_REQUESTED** [review]
based on general feedback: keep the new skull sprite, but remove the body resprite from the PR

**Pull request closed without merging**
