### PR TITLE
derotate barratry

### PR DESCRIPTION
**Pull request by Emisse**
i dont feel like maintaining this map and im not madly in love with anything the map does, needs a bit of a rework

🆑 
- remove: Barratry

### CODE REVIEW

**Comment by Veritius** [comment]
youve ruined my fuckign day!!!

**Comment by deltanedas** [comment]
crlf ops configure youre git :trollface:

**Comment by UbaserB** [comment]
can we derotate aspid while we're here lol

**Comment by Pangogie** [comment]
:(

**Comment by VasilisThePikachu** [comment]
YIPEE

**Comment by deltanedas** [comment]
the day egg died

**Comment by Hmeister-real** [comment]
It's so over, you can't have shit in detroit.

**Comment by K-Dynamic** [comment]
https://youtu.be/znNciln7qwY?si=qD3PkGI__uylOYrj

**Comment by Kadeo64** [comment]
> can we derotate aspid while we're here lol

please god aspid is awful it doesn't make sense that it's 70 pop when it has 3 medical beds, 4 eva suits, and the worst science department known to spessman

**Comment by CatMagic1** [comment]
I'm an avid detroit hater but I'm also a rebel so I do not like this change

**Pull request merged**
