### PR TITLE
Rev fixes and tweaks

### LINKED ISSUE #21530: HeadRev loosing abilities after cloning
**Reproduction**
1. clone headrev
2. he can't see rev icons, and revs can't see his icon

### LINKED ISSUE #21828: revs dont lose briefing when headrev dies
## Description
maybe role as well, and maybe when mindshielded too not sure

### LINKED ISSUE #22249: Rev loosing rev status on cloning
## Description
Only saw with head rev but assuming it would affect normal revs too. The head rev loses the Head rev status after cloning.

**Reproduction**
- Make a head rev
- Kill them
- Clone them
- The rev status is missing.

**Screenshots**
N/A

**Additional context**
Assuming it is the same on normal revs, Also I could not use the admin rev action to make them in to a rev again so it seems it broke the entity in some way.

### PR DESCRIPTION
**Pull request by coolmankid12345**
## Why / Balance
Code was shit, still shit but not as shit (debatable). Exilement barely functioned and I can't believe I left it like that. Exilement is actually a functioning feature now but it might be a little too harsh as just touching a shuttle can start the timer. Luckily you are given two minutes to get your ass back to the station before you are exiled. Once you are exiled you can not be unexiled and exiled Head Revs lose the ability to convert. The revolution will also end if all Head Revs decide to become exiled.

Head Revs can now be cloned properly as well in the rare cases it happens. Shuttle is now called on Head Rev defeat as well.

Fixes #21530, fixes #22249, fixes #21828 

## Technical details
A few things have changed. `OnClone` is used for giving head revs their components in their new body and removing them on the old one. `OnExiledGridChanged` checks when command staff and head revs switch grids so they start exilement or have exilement removed if they come back on time. Removed all the NPCFaction shit for now as I couldn't fix it and Pun Pun when converted would attack anyone. `IsGroupDead` got split into `IsOffStation` as I think checking if someone is off station separately would do wonders.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by deltanedas** [comment]
>  Head Revs can now be exiled as well and will cause Revs to be de-converted if they are.

headrev going into space for a second ends the revolution???

**Comment by GoodWheatley** [comment]
> > Head Revs can now be exiled as well and will cause Revs to be de-converted if they are.
> 
> headrev going into space for a second ends the revolution???

Shouldn’t have abandoned the station :trollface:

**Comment by deltanedas** [comment]
salv or engi headrev never leaving the station for their life wow so quirky

**Comment by noctyrnal** [comment]
no more salv head rev stall?! holy

**Comment by Dutch-VanDerLinde** [comment]
how about instead of them leaving the station, its if they're cuffed

**Comment by Terraspark4941** [comment]
you could possibly escape cuffs, so not viable imo

**Comment by K-Dynamic** [comment]
I would also like cuffing (at least 5 minute continous condition) of all living headrevs as a non-lethal way of derevving, and vice versa with living heads

**Comment by IProduceWidgets** [comment]
How about a short timer for exile. I don't think anyone would mind you dipping off station for 2 minutes as QM to get your mindshield crate off the shuttle, but leaving for longer than that is probably you doing a round stall.

**Comment by metalgearsloth** [comment]
There's currently discussions around revamping revs to fit better with the game so not sure if this would ever get reviewed though as is the code would need a fair amount of cleanup due to being skrunkle.

**Comment by coolmankid12345** [comment]
> though as is the code would need a fair amount of cleanup due to being skrunkle.

Real I haven't written a single good piece of code in my life and what the hell is skrunkle.

**Comment by metalgearsloth** [comment]
Given revs were disabled bandaid prs aren't being merged at this time.

**Pull request closed without merging**
