### PR TITLE
[CHANGE] microwave only removes access

### PR DESCRIPTION
**Pull request by Fishfish458**
## About the PR 
This changes the microwave to only ever remove accesses instead of adding them.

**Screenshots**

microwave

### CODE REVIEW

**Comment by moonheart08** [comment]
Was there some abuse of the mechanic?

**Comment by Fishfish458** [comment]
> Was there some abuse of the mechanic? I don't like nerfing things unless super necessary.

This was actually the last round I was ghosting, but yeah, I've definitely seen it more than this.
image

**Comment by Elijahrane** [comment]
This guy has managed to steal a microwave and an ID console and presumably a whole bunch of spare IDs to burn through. That's quite a lot of effort to try for AA and I don't really agree with this nerf

**Comment by mirrorcult** [comment]
yeah this seems like a reasonable amount of effort

**Comment by Matz05** [comment]
Seems like stealing an ID console (which is a sensitive bit of tech Security is supposed to be watching), a microwave, and a box of spare IDs (again, suspicious/restricted material, though not outright contraband), and 'fuzzing' the console with microwaved random-access IDs is exactly the kind of thing that should be possible. It's a lot of effort and infrastructure compared to just breaking in somewhere. Seems like an unnecessary nerf that removes possibilities and fun, rather than adding them.

**Comment by Fishfish458** [comment]
To obtain access to any department you simply need access to a publicly available microwave and your own ID. past that it's just pulling a lever until you get the right access, that definitely isn't effort required.

**Comment by Elijahrane** [comment]
> To obtain access to any department you simply need access to a publicly available microwave and your own ID. past that it's just pulling a lever until you get the right access, that definitely isn't effort required.

A better nerf would be frying turning the id into a burned mess

**Comment by Matz05** [comment]
There should probably be a chance of bricking the card, yes. But only a chance.

**Comment by Acruid** [comment]
Notice that both Elijahrane and Matz05 both initially assumed that IDs are consumed in the process of gambling for increased access. This should be the cost of the bet, right now they is no buy-in and AA can be won for free.

Giving the microwave a chance to permanently ruin the ID seems like the obvious choice here. The odds can be tweaked based on how many blank IDs are generally available so the ~~slot machine~~ microwave doesn't pay out too often with random access vs destroyed ID cards.

**Comment by PJB3005** [comment]
Maybe also make blank IDs (like the ones the HoP spawns with) not be eligible because they haven't been "activated" yet by an ID console. Thus meaning you need to use/steal real crew IDs.

**Comment by Matz05** [comment]
That sounds reasonable as a move to make if it needs nerfing again after this, but might be too much of a change to make in one step. We want the mechanic to be useful in at least some circumstances, after all, right?

**Comment by metalgearsloth** [comment]
There was a round where a bunch of crew went to the chef and they were all trying to get AA, just food for thought.

**Comment by Matz05** [comment]
People tend to rush a newly-implemented mechanic for a while after it's put in. However, the rate of people trying it isn't the issue, it's the actual effect of successes on rounds. How often (even with the inflated rate of attempts) have non-antags managed to get ID console-capable cards through this method, known what they have, and broken into a place where they have managed to use an ID console to produce an AA card, and had their use of it become a problem?

**Comment by Fishfish458** [comment]
> People tend to rush a newly-implemented mechanic for a while after it's put in. However, the rate of people trying it isn't the issue, it's the actual effect of successes on rounds. How often (even with the inflated rate of attempts) have non-antags managed to get ID console-capable cards through this method, known what they have, and broken into a place where they have managed to use an ID console to produce an AA card, and had their use of it become a problem?

So on the very round this whole conversation started I actually jumped on lizard just to try it again, after the kitchen got it's electricity restored I was able to HoP access in under 4 minutes.

In a game where it's easy to acquire access but removal requires the HoP or captain, if people decide to start handing out AA, there's no putting the genie back in the bottle.

going to try an implementation of just a chance to straight burn the card up with microwave use.

**Comment by Fishfish458** [comment]
Made a change that gives a 15% chance to burn the card complete. and changed it back to giving permisisons

Though the message doesn't quite play, I'm assuming because it's destroying the entity before it does.
burn

**Comment by mirrorcult** [comment]
yeah, you should just make it popupcoordinates instead i think, or have it pop up on a different entity that isnt getting nuked

**Comment by Fishfish458** [comment]
> yeah, you should just make it popupcoordinates instead i think, or have it pop up on a different entity that isnt getting nuked

using popupcoordinates did fix it:
pop

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
