### PR TITLE
Don't allow non-hard anchor overlap

### PR DESCRIPTION
**Pull request by metalgearsloth**
AKA conveyor overlaps.

:cl:
- tweak: Anchoring no longer allowed on non-collidable but occupied tiles (e.g. conveyors).

### CODE REVIEW

**Comment by S1ss3l** [comment]
Wait does it mean that we won't be allowed to stack 20 gas filter on the same tile now ?

**Comment by Zumorica** [comment]
> Wait does it mean that we won't be allowed to stack 20 gas filter on the same tile now ?

That was never intentional, it was a bug.

**Comment by S1ss3l** [comment]
Atmos main in shamble rn. But hold on, won't it prevent pipe crossing too ? Like when you have two pipe on a tile in a cross formation but you dont want the content of the pipe to mix so you don't use a 4-way pipe. And how will it work with freezer/heater and canister ?

**Comment by metalgearsloth** [comment]
> Atmos main in shamble rn. But hold on, won't it prevent pipe crossing too ? Like when you have two pipe on a tile in a cross formation but you dont want the content of the pipe to mix so you don't use a 4-way pipe. And how will it work with freezer/heater and canister ?

This doesn't affect gas pipes and doesn't prevent gas filter stacking as they don't have physics bodies. That would require either anchoring layers (out of scope) or atmos to handle it via event subscription.

**Pull request merged**
