### PR TITLE
Test to ensure all maps have needed job spawnPoints

### PR DESCRIPTION
**Pull request by corentt**
## About the PR 
So this adds a test to ensure that all maps have the spawn points corresponding to the available jobs sets in the map prototype.

This PR also modify two maps (Omega and Box) so the test pass.

**Changelog**

:cl:
no cl
no fun

### CODE REVIEW

**Review by EmoGarbage404 — APPROVED** [review]
Test looks good, maybe tweak the wording of the error a bit idk?
 you'll probably either have to fix box yourself or get emisse to do it.
Also how dare you steal my funny cl thing.

**Comment by corentt** [comment]
> 

I changed the error wording a bit.
I'm fine with making the box change. Should I open a new PR, or doing here ?
And sorry, I didn't know it was your cl stuff, I just remember seeing this and though it was fun too !

**Comment by EmoGarbage404** [comment]
Nah, youre good. You could probably just make the changes in this pr.

**Comment by corentt** [comment]
I ended up updating all of them...

**Comment by Elijahrane** [comment]
> This PR also create the boxer spawnpoint and modify four maps (Omega, Box, Lighthouse and Centcomm) so the test pass.

so this test will require all map prototypes to contain all jobs?

**Comment by corentt** [comment]
> just check if a job has setPreference and ignore lack of spawn if it's false

I made this change and thus reverted changes related to Lighthouse and boxer.

I also made change to only take into account roundstartJob instead of availableJob, and reverted change to centcomm.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
