### PR TITLE
Configure and enable bors

### PR DESCRIPTION
**Pull request by moonheart08**
soon tm

Will announce to contribs to merge master into their PRs after this is done & merged.

### CODE REVIEW

**Comment by moonheart08** [comment]
bors try

**Comment by moonheart08** [comment]
it's ALIVE

**Comment by mirrorcult** [comment]
he lives

**Comment by moonheart08** [comment]
the spurious fail is a sign of things to come

lmao

**Comment by moonheart08** [comment]
ah hm
i did mess it up after all oops, wonder what it was waiting on

**Pull request merged**
