### PR TITLE
Add whistle and new sound for emotion 

### PR DESCRIPTION
**Pull request by Klaypexx**
## About the PR
Added whistle sound and sound for salute and crying (crying sound support only human and slime).

**Media**

https://user-images.githubusercontent.com/68664576/235550358-e1a43f80-63f9-4e78-9602-fa2eefac8057.mov

https://user-images.githubusercontent.com/68664576/235550367-72112b62-4d71-483c-a57f-ba919ba7de18.mov

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Klaypexx
- add: Added whistling emotion
- add: Added sounds for the emotion of salute and crying

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Please use your original PR.

**Comment by Klaypexx** [comment]
> Please use your original PR.

The original one is completely broken. (accidentally filled it with last month's merge updates)

**Comment by metalgearsloth** [comment]
The original looks fine, the second one looks like it's cooked, but they're still recoverable.

**Comment by Klaypexx** [comment]
> The original looks fine, the second one looks like it's cooked, but they're still recoverable.

May i open the second one?

**Comment by Klaypexx** [comment]
This is the original... (i am bad in github interface)

**Comment by metalgearsloth** [comment]
Just merge in master, soft reset to it, then force push is the easiest way to fix it.

**Comment by Klaypexx** [comment]
> Just merge in master, soft reset to it, then force push is the easiest way to fix 

the original commit also had weird incompatibility bugs that only got resolved when I pushed merge a second time while updating the branch to the latest version.  I think it would be much easier to open a second attempt

**Pull request closed without merging**
