### PR TITLE
One Rat King per MouseMigration event

### LINKED ISSUE #25218: Rat king ghost role duplicates
## Description

The last few times i have seen rat king, there have been at least 2 or even 3 at the same time. As far as I understand this is not intentional.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Exactly one Rat King ghost role will be spawned per MouseMigration event.

Fixes #25218 

## Why / Balance

SpecialEntries for VentCrittersRule were added in #17833. I'm not sure if the intention was to allow multiple Rat Kings. If that's the case, maybe we just need to decrease the probability to keep it from happening as often.

## Technical details

Since SpecialEntries are guaranteed to spawn at least once, then we can set the probability of later spawns to zero if we want exactly one entity spawned.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Only one rat king will spawn per Mouse Migration event

### CODE REVIEW

**Comment by wafehling** [comment]
I dunno, multiple rat kings brokering deals and battling for turf is a lot of fun.

**Comment by themias** [comment]
> I dunno, multiple rat kings brokering deals and battling for turf is a lot of fun.

Yeah, it can be fun to have multiple. If it's what we want, we should just close this PR and #25218 as well.

**Comment by Hmeister-real** [comment]
> > I dunno, multiple rat kings brokering deals and battling for turf is a lot of fun.
> 
> Yeah, it can be fun to have multiple. If it's what we want, we should just close this PR and #25218 as well.

yeah 2 rat kings is fun, it's rare enought to get one of them anyway, and even rarer to actually get to play as it. Wstill wishing for that ghost role rework....

**Comment by mirrorcult** [comment]
i think this is fine tbh

**Comment by mirrorcult** [comment]
though is it -always- spawning at least 1 with the current code? cause that seems unintentional yes

**Comment by themias** [comment]
> though is it -always- spawning at least 1 with the current code? cause that seems unintentional yes

It seems Slava0135 intended for it. 
```
    /// <summary>
    /// At least one special entry is guaranteed to spawn
    /// </summary>
    [DataField("specialEntries")]
    public List<EntitySpawnEntry> SpecialEntries = new();
```

**Comment by Slava0135** [comment]
FYI #17833 did not change this behaviour 
image

**Comment by themias** [comment]
Looks this this is the intended behavior, so I'll close this PR.

**Pull request closed without merging**
