### PR TITLE
Adds Lead & Zinc, nerfs Licoxide.

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

Adds Lead, a toxin obtained in very small amounts from grinding steel. Has no taste and does 20 damage per unit, but metabolizes at 0.03u/sec, effectively 30 seconds per unit, or 2 1/2 minutes to crit someone. 
Grinding batteries now gives Zinc instead of Licoxide. It's only used for crafting Licoxide alongside Lead at the moment.
Licoxide is now only obtained through combining Zinc and Lead, at a 1:1:1 ratio (1 Zinc + 1 Lead gives 1 Licoxide). 

You get 0.5u of lead per sheet, alongside 22 iron and 2.5 carbon (to prevent people from grinding 30 sheets at once). This should make Lead, and by extension Licoxide, very annoying and suspicious to get as you have to grind large amount of steel for a long while to get any meaningful amount. 

**Media**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Lank
- add: Added Lead, a tasteless, incredibly powerful but slow-acting poison obtained in small amounts by grinding steel.
- tweak: Grinding powercells now gives Zinc instead of Licoxide
- tweak: Licoxide is now obtained through a combination of Zinc and Lead.

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
The damage dealt by the healthchange effect is multiplied by the amount being metabolized. It deals the amount you set per unit in total after the reagent has fully metabolized.

**Comment by LankLTE** [comment]
Forgive me if I'm misunderstanding, but the damage listed both on the wiki and in the yaml is per second, which is why both the units per second and the damage is so low. In total it does 20 damage per unit, I've tested that and know it works.

**Comment by Anzarot121** [comment]
Too much lead per sheet of steel. If it is present as an alloying additive, it is less than half a percent of the composition of the alloy.

**Comment by LankLTE** [comment]
> Too much lead per sheet of steel. If it is present as an alloying additive, it is less than half a percent of the composition of the alloy.

Truth is you’re going to have to suspend your disbelief a bit. While I absolutely _could_ make it 99 iron and 0.5 lead, having it be as-is works better for gameplay. If you want an “in lore” excuse, you can use steel to make bullets at a SecFab so it likely has some significant amount of lead in it (and gunpowder, but that’s why I’m saying to let it slide).

**Comment by lapatison** [comment]
Do we really need two new reagents whose sole purpose is to nerf licoxide?

**Comment by LankLTE** [comment]
> Do we really need two new reagents whose sole purpose is to nerf licoxide?

Lead is designed to also be a unique poison that fills a currently unused archetype (very strong but slow acting), in addition to crafting Licoxide. Zinc was basically just made to nerf it, but it’s possible more can be added to it now that it exists.

**Pull request merged**
