### PR TITLE
More Coats

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-adds bartender winter coat to bardrobe
-adds clown winter coat to theaterdrobe
-adds mime winter coat theaterdrobe
-adds wardens armored winter coat to locker (slightly less bullet proof than his normal coat but has winter coats temp resist)

ill add hood functionality some time later on to all coats when i figure that out

### CODE REVIEW

**Comment by mirrorcult** [comment]
idk how I feel about the clown/mime coats, I feel like it goes against their distinct styles

**Comment by Emisse** [comment]
> idk how I feel about the clown/mime coats, I feel like it goes against their distinct styles

idk i think theyre cute

**Comment by Veritius** [comment]
> idk how I feel about the clown/mime coats, I feel like it goes against their distinct styles

Mime is alright, but Clown is definitely against the regular style. Just red and white stripes would be better than this... jester outfit? Definitely doesn't work.

**Comment by mirrorcult** [comment]
no the jester outfit is awesome

**Comment by Emisse** [comment]
when i asked in discord a few days ago mirror said they were fine 
image
im cry now

**Comment by mirrorcult** [comment]
i have hangups about it but i cant figure out what they are

**Comment by Emisse** [comment]
winter coat biased maintainer!!!

**Comment by ShadowCommander** [comment]
In game screenshots would help a lot.

**Comment by Emisse** [comment]
image
thats how it would look on a default clown

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
