### PR TITLE
Ion rifle sprite

### PR DESCRIPTION
**Pull request by TaralGit**
Added the ion rifle. Or the sprite at least (credit goes to tgstation). Don't know how to code it but I think it would be nice to have a sprite ready at least.

Edit: Added a placeholder prototype (which basically makes the rifle a laser gun) and corrected the icon.png. Will try to add sprites for the ion hitscan as well.

### CODE REVIEW

**Comment by deltanedas** [comment]
icon has a background???

**Comment by TheShuEd** [comment]
You don’t have to program such a thing.  It’s enough to set up prototypes

**Comment by JoeHammad1844** [comment]
adding a changelog implies that it's functional, dont add a changelog if its just the sprite

**Comment by JoeHammad1844** [comment]
please remove the changelog, it isnt needed

**Comment by TaralGit** [comment]
> please remove the changelog, it isnt needed

Changelog has been removed.

**Comment by Boaz1111** [comment]
If you want me to I can make the YAML and balancing for you!

**Comment by TaralGit** [comment]
> If you want me to I can make the YAML and balancing for you!
The .yml is there but it acts as a laser gun. If you can you can implement this as a proper ion rifle (that only does damage to electronics or mechs).

**Comment by Errant-4** [comment]
For someone to implement this as an item prototype, they would also need sprites for it's projectile/beam

**Comment by metalgearsloth** [comment]
Leave it on the backburner until someone codes it.

**Comment by Boaz1111** [comment]
Is the meta.json file correct with the copyright?

**Pull request closed without merging**
