### PR TITLE
Add checkbox for toggle walking

### PR DESCRIPTION
**Pull request by Keikiru**
## About the PR

Add a checkbox toggle for running/walking.

## Why / Balance

A toggle for running/walking has been desired, as continously pressing down shift to walk can be painful.

As mentioned in the Accessibility doc:
<https://hackmd.io/PIF3dxZkRS27hIyJM58xLw#Controls>

## Technical details

Adds a clientside CVar `control.toggle_walk` hooked up to a checkbox on the settings controls tab.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

toggle-walk

## Breaking changes

N/A

**Changelog**

:cl: Keiku & onoira
- add: A checkbox in the Controls menu can now be ticked to toggle running/walking.

### CODE REVIEW

**Comment by lzk228** [comment]
YEAHHH TY ILY

**Comment by deltanedas** [comment]
makes soap combat actually survivable

**Comment by Keikiru** [comment]
Ready for review

**Comment by Keikiru** [comment]
The changelog didn't work for some reason and the coauthor trailer is broken in the commit message

**Pull request merged**
