### PR TITLE
Make atmos Turing-complete

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR 
This adds pneumatic valves. Pneumatic valves have three ports. Like manual valves, pneumatic valves permit bidirectional flow between the inlet and outlet, but only if the pressure at the control port is high enough.

That's it! As it turns out, this is all it takes for atmospherics to be Turing-complete. See below.

**Screenshots**

This demonstrates an atmos [ring oscillator](https://en.wikipedia.org/wiki/Ring_oscillator). Pump (1) is the source of pressure that powers the atmospheric circuit. The input to the first [inverter](https://en.wikipedia.org/wiki/Inverter_(logic_gate)) (2) is pulled low (to vacuum) in this picture through the manual valve. A volumetric pump (3) limits the flow into the inverter node (4). The feedback pipe (5), shown disabled in this screenshot, feeds back the output of the inverter chain into the input. This causes self-sustained pressure oscillations.

turing3

This behaves like an inverter because when the input (2) pressure is low, the output (4) pressure is high, because the pneumatic valve is off and the volume pump (3) is pumping the pressure at (4) up.

For the second inverter in the chain, the input pressure is high. This turns the second pneumatic valve on, which fights against the second volume pump. Because the second pneumatic valve is designed to be faster than the volume pump, the second inverter's output pressure falls low, close but not quite at vacuum.

To make the ring oscillator exhibit self-sustained oscillations, turn the forcing valves off and turn the feedback valve on, as shown in the screenshot below. Over time, the pressure at each of the inverter nodes [swings up and down with no outside input](https://en.wikipedia.org/wiki/Oscillation).

turing2

**Exercises for the Reader**

1. How would you make an atmos NAND gate?
2. Once you have an atmos NAND gate, what other gates can you make?
3. Once you have logic gates, what else can you make?
4. How do you make a memory element using atmos?

**Answers to Selected Exercises**

1. Here is one option:
    turing4

**Changelog**
:cl: notafet
- add: Add pneumatic valves, which control gas flow based on control pressure.

### CODE REVIEW

**Comment by Zumorica** [comment]
This has my approval

**Comment by EmoGarbage404** [comment]
Most sane atmos player.

**Comment by juliangiebel** [comment]
⭐

**Comment by moonheart08** [comment]
waiting on emisse approval then i'll merg

**Comment by SplinterGP** [comment]
atmos nerds rise up

**Review by Emisse — APPROVED** [review]

**Comment by PJB3005** [comment]
Wasn't this already possible by using mixers? Mixers only let gas through if both sides have appropriate mix, so you could use a chained mixer->filter to achieve the same effect.

**Pull request merged**
