### PR TITLE
Disarm + stam changes

### PR DESCRIPTION
**Pull request by metalgearsloth**
Seems like people think stuns are still a little too strong though any changes are inherently going to nerf other options (flash and soap are the main two that came to mind anyway).

- Removed mass contest because it's hidden, our mass is inconsistent, and leads to silly situations.
- Predicted the disarm effect.
- Disarms do flat stamina damage but have a 1/4 chance to cause a weapon drop but otherwise need to stamcrit to shove.
- Changed stun baton from 2 to 3 hits stun.
- Disabler changed from 3 to 5 hits to stun.
- Probably going to nerf soap slip time so people don't just carry around soap everywhere to throw (maybe like 2-3 seconds).

Tentatively resolves https://github.com/space-wizards/space-station-14/issues/18332 by nerfing stamina damage for sec options.
See https://github.com/space-wizards/space-station-14/pull/17520 for stam regen cooldown reduction.

Open to more ideas I mainly just want to remove the mass contest.

:cl:
- tweak: Removed disarm mass contest as it was hidden. Disarms now just have the 1/4 chance to drop the target's weapon but otherwise do stamina damage of 15.
- tweak: Stun batons now take from 2 to 3 hits to down someone. Battery usage dropped by half.
- tweak: Disablers take from 4 to 5 hits to down someone. Battery usage also dropped by half.

### CODE REVIEW

**Comment by HoidC** [comment]
> Seems like people think stuns are still a little too strong though any changes are inherently going to nerf other options (flash and soap are the main two that came to mind anyway).
> 
>     * Removed mass contest because it's hidden, our mass is inconsistent, and leads to silly situations.
> 
>     * Predicted the disarm effect.
> 
>     * Disarms do flat stamina damage but have a 1/4 chance to cause a weapon drop but otherwise need to stamcrit to shove.
> 
>     * Changed stun baton from 2 to 3 hits stun.
> 
>     * Disabler changed from 3 to 5 hits to stun.
> 
>     * Probably going to nerf soap slip time so people don't just carry around soap everywhere to throw (maybe like 2-3 seconds).
> 
> 
> Tentatively resolves #18332 by nerfing stamina damage for sec options. See #17520 for stam regen cooldown reduction.
> 
> Open to more ideas I mainly just want to remove the mass contest.
> 
> 🆑
> 
>     * tweak: Removed disarm mass contest as it was hidden. Disarms now just have the 1/4 chance to drop the target's weapon but otherwise do stamina damage of 15.
> 
>     * tweak: Stun batons now take from 2 to 3 hits to down someone. Battery usage dropped by half.
> 
>     * tweak: Disablers take from 4 to 5 hits to down someone. Battery usage also dropped by half.

could baton be 2 hit before slowdown

worst part of fighting them is that getting hit once is usually the end unless you've got a pistol or something to magdump quickly with, would give one time to re-assess the situation and run

**Comment by metalgearsloth** [comment]
>could baton be 2 hit before slowdown

> worst part of fighting them is that getting hit once is usually the end unless you've got a pistol or something to magdump quickly with, would give one time to re-assess the situation and run

No slowdown is probably best, then have bolas or whatever if you want snares / slows.

**Comment by HoidC** [comment]
> > could baton be 2 hit before slowdown
> 
> > worst part of fighting them is that getting hit once is usually the end unless you've got a pistol or something to magdump quickly with, would give one time to re-assess the situation and run
> 
> No slowdown is probably best, then have bolas or whatever if you want snares / slows.

wait, you're going to remove slowdown? awesome

**Comment by Partmedia** [comment]
I think the stun and disabler changes make non-lethals too weak and security too difficult to play. We don't want security officers running around shooting with big guns at the first sign of trouble. Nukies have buddies and their buddy will shoot you if you try to stun one of them (it's on them for going out alone).

I think it would be better to make the effects of stun-blocking drugs last significantly longer.

**Comment by deltanedas** [comment]
remember there are no stun blocking drugs, only knockdown reducing drugs
and yeah stims dont last long enough

also 3 hit baton seems too much for sec dealing with shitters

**Comment by HoidC** [comment]
> remember there are no stun blocking drugs, only knockdown reducing drugs and yeah stims dont last long enough
> 
> also 3 hit baton seems too much for sec dealing with shitters

it's not particularly hard to hit someone three times with a melee weapon with windswing being a thing now

**Comment by metalgearsloth** [comment]
> I think it would be better to make the effects of stun-blocking drugs last significantly longer.

Could leave disabler at 4 shots.

The issue is stun combat still needs to be viable against nukies because if they hit armory first (which is extremely common) then sec don't have access to lethals and are almost as useful as any other crew member.

**Comment by HoidC** [comment]
> 

I mean that’s an issue that arguably needs dealing with stun combat or not anyway. Either other places get incentivised or armoury gets made less easy to breach. You can do it as traitor 9 times out of 10 as well - the mines outside on some maps are a start but it’d be nice if there were turrets or something to discourage it, or proximity sensors or something. 

Every single nukie round give or take is this same strategy and it gets boring for both sides.

**Comment by JoeHammad1844** [comment]
> No slowdown is probably best, then have bolas or whatever if you want snares / slows.

I disagree
1. if you have like 30,000 volts or whatever going through you you wont be able to run, just suddenly bieng as nimble as acat to down on the floor seems too harsh of a change and doesnt make sense
2. bolas weigh 20 and when you run and throw you dont get any extra velocity added to the throw, it's just like standing still and throwing, meaning you wont be able to actually hit anyone whos running

**Comment by liltenhead** [comment]
> remember there are no stun blocking drugs, only knockdown reducing drugs and yeah stims dont last long enough
> 
> also 3 hit baton seems too much for sec dealing with shitters

Security has access to flashes, and flash resistance isn't that common. If security can't safely detain people through non lethal means they can escalate to lethal. Or use their rubber bullets they start with, and ask sci to research non lethal technology to get more. Beanbags are also a thing and are probably fine being a two shot stun. I guess what I'm trying to say there are still plenty of options overall.

**Comment by commash** [comment]
Personally, I think the correct fix to stuns would be to have certain armor vests provide stamina damage resistance. Off the top of my head, the Syndie web vest, sec vest, and the captain's armor should all take reduced damage from stuns. Probably some others as well.

That way, stuns will still be good against unequipped people and tiders, but make loud syndies and hard targets a bit more resistant to being two hit downed.

**Comment by LankLTE** [comment]
> Have certain armor vests provide stamina damage resistance.

This has been vetoed time and time again, it probably won’t end up happening.

**Comment by BlitzGunner225** [comment]
I recommend that stuns are more effective in low gear scenarios and less effective in high gear scenarios (like 2 baton hits for unarmored and 8 for juggies). This means when lethals are in play it becomes tense for both sides, puts both sides on a somewhat even playing field, makes melee more viable, means we don’t need hard counters like emp grenades which kinda suck, and something else I forgot.

**Comment by notquitehadouken** [comment]
> [...](like 2 baton hits for unarmored and 8 for juggies)[...]

yeah making 8 hits for juggernauts makes sense instead of the heavily armored, space-faring suit of armor completely failing due to a funny electrical stick

**Comment by metalgearsloth** [comment]
will re-open when I get a chance to finish.

**Pull request closed without merging**
