### PR TITLE
Thieving Kit: Chameleon Thieving Backpack

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

The thieving chameleon kit now has a chameleon thieving backpack.

The backpack is padded to make no sound when inserting items into it, which differentiates it from the regular chameleon backpack.

## Why / Balance

More thievery is more fun, and most of the time people only know they're robbed because the sound effect of stuffing something into a bag is so damn loud. If you can silently take someone's clothes off of them, surely you can put it into your bag without making a sound as well.

It's a much needed buff to the chameleon kit which is mostly a funny gimmick kit at the moment.

## Technical details

- Creates a chameleon backpack with a null storageInsertSound to give it the effect of being silent
- Put all the chameleon kit stuff into the backpack for convenience

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/957eab3d-36c3-4097-b3d3-2c08f872b925

https://github.com/space-wizards/space-station-14/assets/58439124/efea5eab-7477-4a43-bfba-27c6ba62e703

**Changelog**

:cl:
- add: The thieving chameleon kit now has a chameleon thieving backpack, which makes no sound when items are inserted into it.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
HE SPAWNED WITH A GREY BACKPACK, VALID!!!

**Comment by deltanedas** [comment]
mime thief for everyone

**Comment by Dutch-VanDerLinde** [comment]
should be in chameleon kit though i think

**Comment by Plykiya** [comment]
> HE SPAWNED WITH A GREY BACKPACK, VALID!!!

gib him, he's a pacifist, he can't fight back

yeah I really don't like how meta-able this is but I don't know another way to do it with how startingGear currently works

**Comment by Plykiya** [comment]
> should be in chameleon kit though i think

I didn't include it with the syndie stuff for the same reason syndies don't get the chameleon thieving gloves

**Comment by Piras314** [comment]
Putting it in a kit is a good idea because it removes the meta-able component of it, you could even put one in every single kit if you want to ensure everybody gets at least one and they can just throw the other away. Or some other, better workaround.

**Comment by Plykiya** [comment]
ah, you mean put it with the chameleon kit of the thieving toolbox options

I understand now, I'll take a look into that

**Comment by TurboTrackerss14** [comment]
>pov you get shiftstart metachecked for holding a second backpack
>pov you get metachecked because someone sees you put something in your bag but makes no sound 
>pov you get metachecked because someone sees chameleon dropdown and can check if you are a thief or a traitor with a single item insert. 

The toolbox starts in your bag expressly to not out you shiftstart. 
The items going straight into the bag instead of just getting dumped onto the floor is 👍 
but the metachecking that will occur.... so much metachecking...

**Comment by Ghagliiarghii** [comment]
Agree with previously stated issues - also would be nice if there were a satchel / duffel equivalent following your load out preference.

**Comment by Plykiya** [comment]
> > pov you get shiftstart metachecked for holding a second backpack
> > pov you get metachecked because someone sees you put something in your bag but makes no sound
> > pov you get metachecked because someone sees chameleon dropdown and can check if you are a thief or a traitor with a single item insert.
> 
> The toolbox starts in your bag expressly to not out you shiftstart. The items going straight into the bag instead of just getting dumped onto the floor is 👍 but the metachecking that will occur.... so much metachecking...

kill the metacheckers by blowing up their hands if they try to use the backpack

**Comment by SlamBamActionman** [comment]
Good item that is not strictly necessary but gives the Chameleon Kit extra value and pairs well with its intended playstyle (doing crime while blending in). It bears the risk of being found out from someone noticing the lack of noise but for someone to pay that much attention they're likely already suspicious of you.

8/10 good buff to the Chameleon Kit.

**Comment by Plykiya** [comment]
yeah so uh, I dunno what's up with the items falling on the floor since I didn't touch that logic, but yeah, there we go

**Comment by Plykiya** [comment]
> > yeah so uh, I dunno what's up with the items falling on the floor since I didn't touch that logic, but yeah, there we go
> 
> You would need to change the kit contents to spawn a filled bag to avoid that

I'm pretty sure it already does avoid that when I play thief, it just for some reason doesn't do it in debug?

**Comment by deltanedas** [comment]
i would just make all bag sounds a little quieter so theres no metagaming a valid bag roundstart

or have it so when you use thieving gloves to steal an item you can silently put it in your bag for a few seconds

**Review by TheShuEd — APPROVED** [review]

**Comment by Plykiya** [comment]
holy shit I'm testing out the bag sound range, you can literally hear people stuffing things in their bag from outside of your screen

**Comment by Plykiya** [comment]
> i would just make all bag sounds a little quieter so theres no metagaming a valid bag roundstart
> 
> or have it so when you use thieving gloves to steal an item you can silently put it in your bag for a few seconds

https://github.com/space-wizards/space-station-14/pull/30225

**Comment by Plykiya** [comment]
ya ok, shouldn't need a completely silent backpack with the sound nerf now

**Pull request closed without merging**
