### PR TITLE
Salvage compass, a tool to stop salvage specialists from getting stranded in space.

### PR DESCRIPTION
**Pull request by Interrobang01**
## About the PR 

https://discord.com/channels/310555209753690112/311537926376783886/1043958837608190192 full argument here

> Salvage specs getting permanently stranded in space because a newbie touched the cargo shuttle computer in just the wrong way is, in my opinion, unfun for everyone involved, in the past, present, and future. Risks are acceptable, but they must be able to be prepared for. There are ways to reduce the risk of getting stranded, but they are hard to get, and there is no 100% foolproof method of preventation.
> 
> This PR makes a new Pinpointer-based tool, a Salvage Compass, appear in every salvage locker. When turned on, the arrow will point towards the salvage magnet, helping disoriented salvage specialists. This will not eliminate stranding completely, but it will get rid of it enough to be more fun when it does happen.

Forget all that, salvage specs getting lost is still a huge problem, but I realize adding a magical tool that solves all your problems is not the right way of fixing it. I will still keep this PR up, and instead of the pinpointer appearing in every salvage locker, it appears only in QM's locker 25% of the time. QM can hand it out to salvage techs if they desire.

**Screenshots**

image

**Changelog**

:cl:
- add: Rarely, the Quartermaster will spawn with a Salvage Compass that shows the direction the Salvage Magnet is in. If the Quartermaster is lucky enough to get it, they can hand it out to their salvage specialists to help them if they get lost.

### CODE REVIEW

**Comment by JustinTrotter** [comment]
What happens if there's more than one magnet? Some custom forks may have more than one. Points to the closest one?

**Comment by mirrorcult** [comment]
its a pinpointer so yes

**Comment by mirrorcult** [comment]
and for the record, i dislike adding this and i don't think there is sufficient evidence that this happens often enough for anything to actually be done about it

**Comment by JustinTrotter** [comment]
> and for the record, i dislike adding this and i don't think there is sufficient evidence that this happens often enough for anything to actually be done about it

Also the gps exists. So salvages should radio the station for its position or report their own to get picked up.

**Comment by EmoGarbage404** [comment]
already gave my opinions on this in the discord but i'll reiterate.

salvagers getting knocked into space is an inherently interesting event that has a variety of unique and varied solutions. It also can be a source of valuable IC conflict that isn't directly just killing other people. I've never seen it happen frequently enough to warrant this type of response, so I naturally find this pr rather bizarre. Furthermore, this takes probably the least interesting approach to solving the issue, which is just directly pointing the person to where they have to go, allowing them to engage in reckless behavior like throwing item to generate thrust with basically no risk.

The proper fix would be to give salvagers maybe a GPS of some kind or suit coordinates or... Oh wait. Those things only exist. This problem is only an issue if you are unwilling/unable to communicate with anyone on the entire station. Furthermore, this is just another obligatory "take this because it's objectively better than every other option" item that invalidates basically every other strategy. 

In your pr description you lament the lack of, "no 100% foolproof method of preventation," and I would simply like to comment that SS13 and SS14 are, at their core (more than being about supposedly smacking people with microwaves) games about collaborating with other people in order to overcome difficult and emergent situations. Getting lost in space and having to radio the station to try and desperately get back certainly fits that criteria. 

I suppose, in closing, all I would say is that this pr is taking away a genuinely unique and engaging emergent experience under the guise of it being not "fun".

**Comment by Interrobang01** [comment]
Honestly, these are good points. I still feel like the situation is unfun, but I don't think this is the best solution anymore. I don't want to close this (sunk cost fallacy) but I think I'll take it out of salv lockers and put maybe one in the QM's locker or reduce the probability of it being in salv locker to 10% or something.

**Comment by civilCornball** [comment]
I just thought they should have a GPS in their basic kit.
That way, there’s player interaction - they need to phone home to get station coords.

**Comment by metalgearsloth** [comment]
Pinpointer code also isn't really built to handle many entities so this would need its own solution like a minimap if we did it.

**Pull request closed without merging**
