### PR TITLE
Code cleanup: Dirty(Comp)

### PR DESCRIPTION
**Pull request by Tayrtahn**
## About the PR

Replaced all uses of Dirty(Component) with Dirty(Uid, Component) in content.

## Why / Balance

Over 100 compiler warnings removed.

## Technical details

Some systems had to be modified to pass around uids internally. ~Notably, the (numerous) systems related to pulling relied on passing and tracking components, so they were modified a bit to be more based around uids. Those systems definitely could still use a refactor, but that was not the intention of this PR. This just changes what needed to be changed to get uids tracked (and maybe a teensy bit more to be consistent).~

I did test as many aspects of this as I could. However, this PR makes (mostly small) changes to a bunch of different systems, so be prepared to do some triage if this gets merged. Everything worked fine for me, and most potential issues would just be client mispredictions, but I'm not going to pretend that I was able to think of and test every possible edge case.

## Media

Code.
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

The public APIs for TagSystem and SharedInstrumentSystem have changed to require `EntityUid` parameters for more methods. Systems that call these methods will need to be updated.

**Changelog**

Not today

### CODE REVIEW

**Comment by ElectroJr** [comment]
This should get tested with https://github.com/space-wizards/RobustToolbox/pull/4978 in case one of the uid-component pairs is wrong.

**Comment by Tayrtahn** [comment]
> This should get tested with [space-wizards/RobustToolbox#4978](https://github.com/space-wizards/RobustToolbox/pull/4978) in case one of the uid-component pairs is wrong.

I actually added that check to Dirty myself for the purpose of testing this! It did find one mismatch in my testing, which has been fixed. Definitely a good addition to Robust Toolbox.

**Comment by metalgearsloth** [comment]
This has a significant amount of conflicts with https://github.com/space-wizards/space-station-14/pull/24936

**Comment by Tayrtahn** [comment]
> This has a significant amount of conflicts with #24936

Oh, I'll bet it does! Glad to see another attempt at a proper rework of pulling. I'll give that some time to get stabilized before fixing up those conflicts.

**Comment by metalgearsloth** [comment]
> > This has a significant amount of conflicts with #24936
> 
> Oh, I'll bet it does! Glad to see another attempt at a proper rework of pulling. I'll give that some time to get stabilized before fixing up those conflicts.

Just nuking the pulling changes is easier realistically.

**Comment by Tayrtahn** [comment]
Yeah, I'll just revert my changes to those files, merge, and do another pass looking for Dirty, in case any slip through.

**Pull request merged**
