### PR TITLE
adds rubber bullets to uplink

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

adds the rubber bullet magazine for the viper and cobra to the uplink
turns the fire axe and desword entries into comments
## Why / Balance

#21197
non lethal takedowns allow for fun gimmicks like SAW traps/kidnapping for information without being railroaded into nocturine

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- add: rubber bullets for the viper and cobra have been added to the syndicate uplink

### CODE REVIEW

**Comment by metalgearsloth** [comment]
How does someone balance non-lethal sec gear vs syndie gear if syndies also get the same gear.

**Comment by JoeHammad1844** [comment]
> How does someone balance non-lethal sec gear vs syndie gear if syndies also get the same gear.

trial and error :trollface:

**Comment by JoeHammad1844** [comment]
having syndies only options be lethal is really lame and makes it hard to do certain gimmicks

**Comment by deltanedas** [comment]
yeah 90% of syndies having no discreet access to nocturine ruined stealth imo, along with any hrp kidnapping stuff

**Comment by JoeHammad1844** [comment]
hmm, today i will remove options for syndicates and sell it back to them under a high time cost

**Comment by Unbelievable-Salmon** [comment]
What about a mag for the cobra? If we're concerned about syndi stealth I think giving non lethal means to the silenced pistol is worth considering.

**Comment by JoeHammad1844** [comment]
> What about a mag for the cobra? If we're concerned about syndi stealth I think giving non lethal means to the silenced pistol is worth considering.

thats actually a really good idea

**Comment by JoeHammad1844** [comment]
ill add that in a second

**Comment by JoeHammad1844** [comment]
voper :trollface:

im leaving that in, its funny

**Comment by JoeHammad1844** [comment]
wait fuck i gotta remove the fireaxe and desword

**Comment by Brandon-Huu** [comment]
Why is the double e-sword being removed?

**Comment by notquitehadouken** [comment]
> Why is the double e-sword being removed? or am i misreading?

being added back into the uplink file, but still commented out so they're not actually in it

**Comment by Emisse** [comment]
i dont like syndies having access to this from uplink

**Comment by JoeHammad1844** [comment]
> i dont like syndies having access to this from uplink

but it doesnt kill people

**Comment by JoeHammad1844** [comment]
if a seccie can completely disable someone in a bloodred with rubber bullets they get roundstart i dont see how syndies being able to do the same is bad

if everybody is special, nobody is

**Comment by JoeHammad1844** [comment]
welp now i need to increase the price of nocturine

**Comment by JoeHammad1844** [comment]
there go

**Comment by JoeHammad1844** [comment]
> i dont like syndies having access to this from uplink

please provide reasons

**Comment by asperger-sind** [comment]
I think this is good, there's no reason to not add a (slightly weaker) ammo sidegrade when we already have lethals, I just don't want to see this being used as an argument to increase the price for normal viper ammo or something like that.

My reasoning is that if the tot in question gets access to lethals, they can roundend XYZ just the same as they would with rubbers, but its not a straight downgrade because rubbers go through armor while not killing but merely stunning, allowing the victim to retaliate or call the tot out on radio, it's slightly weaker than lethals, sure, but its optional and for the tot to decided whether or not they need or want to use this.

**Comment by JoeHammad1844** [comment]
lethals:
tot shoots you
you get crit
you get gibbed in maint

rubbers:
tot shoots you
tot has to cuff you
you can yell VALID!!
tot then has to kill you with something else
tot gibs you in maints

**Comment by Brandon-Huu** [comment]
The mods hate syndicates not killing people

**Pull request closed without merging**
