### PR TITLE
Tortilla dough, Taco shells, and Tacos

### PR DESCRIPTION
**Pull request by phunnyguy**
## About the PR

Added Tortilla dough, created via mixing 15u cornmeal and 10u water, Tortilla dough strips, and Tortilla dough flats.
Added recipe for turning Tortilla dough flats into Taco shells
Added multiple recipes for turning taco shells into various tacos using different ingredients.

## Why / Balance

Makes corn more of a staple produce like wheat, allowing for more variety in the kitchen.

## Media

image
[2023-10-06 14-59-26 (1).webm](https://github.com/space-wizards/space-station-14/assets/90366172/140f9fbe-12bb-4778-8df0-e17b118ded74)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not re
quire an ingame showcase

## Breaking changes

**Changelog**

:cl: Phunny
- add: Added Tortilla doughs and variants.
- add: Added Taco shells and recipe
- add: Added various types of Tacos
- tweak: Changed naming of the original taco to soft shell taco

### CODE REVIEW

**Comment by deltanedas** [comment]
theres already unused cornmeal dough why not reuse that

**Comment by phunnyguy** [comment]
> theres already unused cornmeal dough why not reuse that

The recipe for that dough is Cornmeal, Milk, and eggs, which is used for cornbread.

Tacos on the other hand, at least realistically just use corn flour, water, and salt.

**Review by LankLTE — CHANGES_REQUESTED** [review]
There is a pre-existing taco food and recipe (FoodMealTaco and RecipeFoodMealTaco) respectively. I'm fine with this being used instead as instead as it's more in-depth, but the pre-existing recipe, food, sprites, etc. should be modified / removed.

**Comment by phunnyguy** [comment]
> There is a pre-existing taco food and recipe (FoodMealTaco and RecipeFoodMealTaco) respectively. I'm fine with this being used instead as instead as it's more in-depth, but , but the pre-existing recipe, food, sprites, etc. should be modified / removed.

I didn't want to touch that recipe due to not wanting to step on anyone's toes. Since that other taco recipe is flour based it could just be renamed to soft taco, with the corresponding internal names changed to reflect that.

**Comment by phunnyguy** [comment]
Updated the names for the old taco, just changed it to soft taco. I don't think the sprite needs to be changed, the shell color on the old taco is closer to a flour tortilla and it is overall quite visually different from the new tacos.

image

**Comment by phunnyguy** [comment]
Updated the taco shell in the sprites to be a little less flat looking.

image

New taco shell sprite for example.

**Comment by brainfood1183** [comment]
Nachos next?

**Comment by phunnyguy** [comment]
> Nachos next?

Should be pretty easy once this gets merged, thinking uhh, use a knife on the tortilla flat for raw tortilla chips.
Cook 1 raw tortilla chips for tortilla chips.
1 raw tortilla chips + cheese wedge for chips and queso
1 raw tortilla chips + 1 tomato + 1 onion + 1 chili for chips and salsa

**Comment by potato1234x** [comment]
> I don't think the sprite needs to be changed
>
i really think you should use/modify the tgstation sprites because the distinct lack of shading is going to conflict with everything else in the game

**Comment by phunnyguy** [comment]
> > I don't think the sprite needs to be changed
> 
> i really think you should use/modify the tgstation sprites because the distinct lack of shading is going to conflict with everything else in the game

I could do that, though the old taco sprite that's used now is for soft tacos. Hard shell tacos on /tg/ look like:
image

and are pretty huge in my opinion:
image


Maybe just take the color scheme from the /tg/ sprite and throw it on the new one?:

image

**Comment by potato1234x** [comment]
i'd use the softshell tacos from tg (https://tgstation13.org/wiki/Guide_to_food#/media/File:Plaintaco.png) and recolor them to fit the hardshell tacos

**Comment by phunnyguy** [comment]
> i'd use the softshell tacos from tg (https://tgstation13.org/wiki/Guide_to_food#/media/File:Plaintaco.png) and recolor them to fit the hardshell tacos

And the softshell taco should just use the same sprite but not recolored?

**Comment by phunnyguy** [comment]
After no response for a few days I went and just modified the colors on the taco sprites I made to better match the tgstation tacos.

Would rather not just make the hard shell sprite a recolor of the soft shell sprite as I think they'd be too visually similar.

Will update the image in the PR to reflect the new sprites.

**Comment by deltanedas** [comment]
you dont need to constantly merge master for no reason :trollface:

**Comment by phunnyguy** [comment]
> you dont need to constantly merge master for no reason :trollface:

image
image

**Comment by deltanedas** [comment]
it doesnt matter

**Review by phunnyguy — COMMENTED** [review]
Finalized in commit [f72da95](https://github.com/space-wizards/space-station-14/pull/20797/commits/f72da9553878d1e850982f9e8100fffedd670bb9). The old taco consumable was renamed to soft taco, internal naming changed to reflect this as well. Sprites of the old taco item remain unchanged as they already resemble that of a soft taco.

**Comment by Stealthbomber16** [comment]
hard tacos can not be eaten by lizards. intended?

**Pull request merged**
