### PR TITLE
Cargo Repalette

### LINKED ISSUE #18627: cargo backpack inhand-right sprite issue
left and right facing sprites should be swapped

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Repalettes cargo technician, quartermaster and general cargo things to a more consistent color. Salvage not included.
Also fixes #18627 

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:Alekshhh
- tweak: Changed quartermaster and cargo technician palettes, as well as some cargo department things (salvage not included)

### CODE REVIEW

**Comment by Flareguy** [comment]
Don't make the salvage sign a different color from the supply one, they both reside in the same department so it'll just cause confusion.
I would also change back the headset colors, I don't think the new ones work very well on the headset sprite. I would be understanding if you hade a more deliberate intention behind it other than consistency, but to me it just seems kind of weirdly saturated and nothing else. The sprite already fit.

Everything else looks fine.

**Comment by Alekshhh** [comment]
I was worried to change the shading on the headsets since then they'd stick out even more, so I just repaletted it

**Comment by Alekshhh** [comment]
oops

**Comment by Alekshhh** [comment]
image
tried regardless

**Comment by Flareguy** [comment]
These all need meta.json updates indicating you changed them.

**Comment by Alekshhh** [comment]
do they really need it if it's just a palette swap? for the banner I think it's necessary since it's an entirely new design but just for a small color change it may be unnecessary

**Comment by Flareguy** [comment]
Apologies for the delay.
The salvage sign colors are still different from the cargo ones according to the rsi diff, fix that and it should be good-to-go.

**Comment by metalgearsloth** [comment]
@Alekshhh are you coming back to this?

**Comment by Alekshhh** [comment]
no

**Comment by GoodWheatley** [comment]
It’s cargover

**Comment by JoeHammad1844** [comment]
the PDA and headset looks like they're made of peanut butter, no likey

**Pull request closed without merging**
