### PR TITLE
Remove CargoPallet component from the cargo pallet

### PR DESCRIPTION
**Pull request by Minemoder5000**
## About the PR

Removes the CargoPallet component from the cargo pallet
## Why / Balance

Fixes https://github.com/space-wizards/space-station-14/issues/32977
## Technical details

Removed a couple lines of yaml
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

Minemoder
:cl:
- fix: The cargo shuttle's cargo pallets can no longer sell or buy.

### CODE REVIEW

**Comment by Minemoder5000** [comment]
uh oh, something got pushed that shouldnt've been pushed

**Comment by 0x6273** [comment]
Probably needs a name change also to avoid confusion?

**Comment by UbaserB** [comment]
> Probably needs a name change also to avoid confusion?

nah its fine, iirc the desc. got changed in another pr already a while ago

**Comment by Minemoder5000** [comment]
Can confirm, 
image

**Review by slarticodefast — APPROVED** [review]
Thanks for the fix!

**Comment by TheShuEd** [comment]
Propose delete pallet proto, and migrate it to catwalk

**Comment by UbaserB** [comment]
> Propose delete pallet proto, and migrate it to catwalk

personally i like the aesthetic of it not being connected

**Comment by chromiumboy** [comment]
> > Propose delete pallet proto, and migrate it to catwalk
> 
> no, we might want to have a cargo pallet that can both sale and buy stuff, or forks can have it
> 
> to resolve the shuttle sell issue just replace cargo pallets with catwalk on the cargo shuttle

This seems the best solution

**Comment by Minemoder5000** [comment]
Alright, should I close this pr and open another one with the cargo shuttle catwalks?

**Comment by Nettingman** [comment]
This is great, thank you. One of my favorite departments is Cargo, and moving the computer from ATS took out half of the fun, glad it can't be used anymore!

**Pull request merged**
