### PR TITLE
Weapons resize 

### PR DESCRIPTION
**Pull request by Vaaankas**
## About the PR
Rebalances most melee and ranged weapons in regards of inventory size and of concealability: 

Larger and more powerful weapons (Automatic rifles, shotguns, laser rifles) are now harder to conceal, with most of them only being able to fit inside dufflebags or in the backpack slot. 

SMGs are able to be placed in the suit slot, while pistols remain unchanged (besides a few cleanups) and still are the most easily concealable ranged weapon.

Screenshot_22 *image updated

Larger melee weapons have been changed to look nicer and more logical, with more dangerous weapons taking more slots and being more difficult to hide on one's person.
Screenshot_23  *pic updated 

## Why / Balance

Large weapons are now harder to conceal, thus making threats more clear and provoking player interactions (for example, a tider with a backpack that just stole a double-barrel will not be able to carry it without it being visible on their sprite, unless they turn it into a sawn-off).

This change will give the players that want to use a large gun a choice to either:

- Carry it in their hands
- Carry it in their backpack slot
- Carry it inside a dufflebag and suffer the movement penalty

Either choice leads to potential interactions and makes the player take a trade-off.

It will also make it substantially harder for a single character to amass a mobile arsenal of weapons for themselves, which i view as a positive thing.

I think this change will make the game more clear and concise in terms of player-vs-player threat gauging and interaction, while still leaving room for surprising and outplaying opponents.

## Technical details

Its just prototypes.

## Media

- [yes] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No, its just some prototype changes.

**Changelog**

:cl: vanx
- tweak: Most weapons have been resized to take up more inventory slots.
- tweak: Larger weapons are not able to be put in the suit slot now, only on the back.

### CODE REVIEW

**Comment by Ilya246** [comment]
i don't think drill should be so large despite how good it is

**Comment by Vaaankas** [comment]
@Ilya246 I feel like its a fairly large industrial tool that would be pretty bulky. I know spessmen are allergic to carrying things in their hands but maybe not every item has to fit in their bag nicely.

@Dutch-VanDerLinde Thanks, i fixed that!

**Comment by SlamBamActionman** [comment]
While I am not against these changes on principle, it does bring in some concerns about balance changes and just general QoL being reduced in some cases.

- Knives no longer fit in pockets.
- Weapons require ammo, which in certain cases can take up a lot of space. 
- Duffelbags give you a 10% movement speed decrease, giving an additional hindrance for gun-heavy antags.
- Swords might be excessively large compared to their damage potential. 

That being said I'm not opposed to testing this. It's an interesting idea.

**Comment by Vaaankas** [comment]
Thanks for sharing your concerns! Let me answer some:

>     * Knives no longer fit in pockets.
They still do since they still are a _small_ item. I think it is consistent that a 3-slot knife fits in a pocket since 3-slot pistols can aswell.
>     * Weapons require ammo, which in certain cases can take up a lot of space.
>     * Duffelbags give you a 10% movement speed decrease, giving an additional hindrance for gun-heavy antags.
I think nuclear operatives already started with duffelbags, besides, gun heavy antags will most likely have access to chest rigs which are intended to carry ammo. And so does security. In any case, they can still carry their guns in hand (i know no one likes it, but thats something we're trying to force for reasons above).
>     * Swords might be excessively large compared to their damage potential.
That's fair.

**Comment by Ko4ergaPunk** [comment]
image

**Comment by deltanedas** [comment]
drill is a terrible melee weapon why would you want to make it big

**Comment by Vaaankas** [comment]
> image

Bag is for real robust players only, tssss

**Comment by Vaaankas** [comment]
Screenshot_15
Made swords and drill more compact, changed China-Lake and fixed L6 not spawning in the bundle due to being ginormous.

**Comment by deltanedas** [comment]
drill has like 8 dps its not even comparable to a sword

**Comment by Ko4ergaPunk** [comment]
The weapons are monstrously large. It looks weird that you can't put smg in backpack. Takes up too much space considering guns are flat

**Comment by Vaaankas** [comment]
> drill has like 8 dps its not even comparable to a sword

I just thought it would make sense for an industrial tool to take up some space. Besides, players being able to carry all the tools they might ever need at once with no tradeoff feels off to me.

**Comment by Dutch-VanDerLinde** [comment]
I don't think its powergaming to carry a drill with you as salvage

**Comment by Vaaankas** [comment]
> The weapons are monstrously large. It looks weird that you can't put smg in backpack. Takes up too much space considering guns are flat

You can put an SMG in a backpack, but not in a satchel. And you can also put them in your suit slot.

Sadly there is no way to scale the inventory sprites themselves, if that is your concern. But i personally prefer gameplay over graphics.

**Comment by Vaaankas** [comment]
> I don't think its powergaming to carry a drill with you as salvage

I just think restrictions like this force player interactions, and that is most important.

If you go salvage as a duo, for example, and each of you is self-sufficient and packed with all they will ever need, you wont even need to talk to eachother. Changes like this, while they may decrease the "QoL" of individual players a bit, will force them to work together. Say in this example: if a drill is too large, one player might opt into carrying it while the other carries meds and so on.

**Comment by VektorZ1** [comment]
With those changes it would be a real necessity to get weapons like the SMG with folding butts and such

**Comment by Vaaankas** [comment]
> With those changes it would be a real necessity to get weapons like the SMG with folding butts and such
I would love to see sawn off Kammerers and folding stocks in SS14, but thats out of scope of this PR...
Screenshot_17

**Review by Flareguy — CHANGES_REQUESTED** [review]
Do not use ``storedRotation`` in non-90-degree angles. It makes mixels (mixed pixel sizes) and generally looks bad.
If you want to change the orientation of a sprite, use the ``storedSprite`` component (see the crowbar for an example) and then run the base item through something like rotsprite (built in as an optional rotation mode to aesprite & libresprite, also comes as its own program.) This will not produce a *perfect* result, but will usually look significantly better then manipulating the sprite with ``storedRotation`` like is being done here.

**Comment by TurboTrackerss14** [comment]
What is with the random suit coordinate and other "system" changes in the first commit? 

Also gross, these sizes are way WAY to big in my opinion. Leave them as they are :tm:

**Comment by juliangiebel** [comment]
Do not combine random changes like that and I also think the gun sizes don't need to be changed

**Comment by Vaaankas** [comment]
> Do not use `storedRotation` in non-90-degree angles. It makes mixels (mixed pixel sizes) and generally looks bad. If you want to change the orientation of a sprite, use the `storedSprite` component (see the crowbar for an example) and then run the base item through something like rotsprite (built in as an optional rotation mode to aesprite & libresprite, also comes as its own program.) This will not produce a _perfect_ result, but will usually look significantly better then manipulating the sprite with `storedRotation` like is being done here.

I just started having fun with the new inventory system, damn. No more 45 degree angles it is then.

Reverted the sec belt aswell
Screenshot_19

**Comment by Vaaankas** [comment]
> Do not combine random changes like that (belts, antique laser, etc.) and I also think the gun sizes don't need to be changed

This PR doesnt change anything about the antique laser, and yea, the belt is reverted now :(

But i dont agree with the last sentence, i think it would be good for the game to have them be larger. Its a way better alternative to making them not puttable in backpacks at all!

**Comment by Flareguy** [comment]
> I just started having fun with the new inventory system, damn. No more 45 degree angles it is then.
> 
> Reverted the sec belt aswell Screenshot_19

You don't need to change the items back to account for the sprite! We have the ``storedSprite`` component like I mentioned, you can just give them a unique sprite instead of rotating it with ``storedRotation``.
As I mentioned in my review, rotsprite will work well for this. Some manual cleanup may be desirable afterwards, but is in all likelyhood probably completely optional.

**Comment by Vaaankas** [comment]
> You don't need to change the items back to account for the sprite! We have the `storedSprite` component like I mentioned, you can just give them a unique sprite instead of rotating it with `storedRotation`. As I mentioned in my review, rotsprite will work well for this. Some manual cleanup may be desirable afterwards, but is in all likelyhood probably completely optional.

I did try rotsprite to some success, but wasn't quite satisfied. I guess i will leave that for now, especially when, as others here have mentioned, it widened the scope of this PR a bit too much. Thanks for the explanation though, much appreciated!
storage

(If someone recreates those melee weapons as horizontal feel free to PM me @vanxxxx and we'll assemble another PR)

**Comment by LordEclipse** [comment]
> > Do not combine random changes like that (belts, antique laser, etc.) and I also think the gun sizes don't need to be changed
> 
> This PR doesnt change anything about the antique laser, and yea, the belt is reverted now :(
> 
> But i dont agree with the last sentence, i think it would be good for the game to have them be larger. Its a way better alternative to making them not puttable in backpacks at all!

I think this just encourages murderboning if syndies, for instance, cannot conceal their guns, as once they buy them they pretty much have to use them, and they are already contraband which forces them to make a choice rather than give them options. Also forces players to always grab a duffelbag, making the other bags comparatively useless as concealment of lethal weaponry is awfully important for syndicate gameplay. Players already can't carry a mobile armory, gridinv already prevents this. Baseball bat is also needlessly huge in comparison to something much better, like the claymore, and both the energy katana and regular katana.

**Comment by Admiral-Obvious-001** [comment]
Overall, I think most of the changes are a good idea. The baseball bat probably doesn't need to be a 8x2, an 8x1 would be fine and the sawn off shotgun is basically made so it can fit in a compact space, honestly it should be the size and shape of a handgun.

It does make satchels a bad idea for long guns, but is that really a bad thing?

**Comment by Vaaankas** [comment]
> I think this just encourages murderboning if syndies, for instance, cannot conceal their guns, as once they buy them they pretty much have to use them, and they are already contraband which forces them to make a choice rather than give them options.

The only syndie agent guns that are affected by this PR are the mosin, c20r and the bulldog, none of these were inconspicous to begin with, and C-20 still fits on the suit slot. I would argue that this change will nerf security more than the agents, since sec are the ones that rely on big guns instead of trinkets.

>  Also forces players to always grab a duffelbag, making the other bags comparatively useless as concealment of lethal weaponry is awfully important for syndicate gameplay. Players already can't carry a mobile armory, gridinv already prevents this. 

Picking a dufflebag is now more viable, yet not overpovered since movement speed is still very important. It would come to player's own choice in playstyle. Duffelbags might also see increased attention from sec, as they learn that this is basically the only way of carrying weapons discreetly. Also dont forget that pistols, Eswords, hypopens and other easily concealable tools still exist and some are exclusive to agents.

Gridinv prevents weapon gathering to some extent already, that is right. But its still not uncommon to see someone carry 2 or more full sized guns (think a drozd+laser rifle) without even having their hands occupied.

Before gridinv, a shotgun used to be 30 units out of duffelbag's 120 =, thats 25%.
Right now its 5 grids out of 40, thats only 12,5%, so you can effectively fit double the shotguns in the same bag.
WIth this PR, it will take up 16 out of 40 slots, making it 40%.

> Baseball bat is also needlessly huge in comparison to something much better, like the claymore, and both the energy katana and regular katana.

Baseball bat is made so large so it doesn't fit inside a backpack. That is because its a cheap and robust weapon that should be hard to carry about unnoticed as a downside.

**Comment by Vaaankas** [comment]
> The baseball bat probably doesn't need to be a 8x2, an 8x1 would be fine 

Oh yea, that looks good enough to me

Screenshot_20

**Comment by asperger-sind** [comment]
> Picking a dufflebag is now more viable...

Yet now picking a satchel is even *less* viable now, despite already not being very good before.

> Besides, players being able to carry all the tools they might ever need at once with no tradeoff feels off to me. (Powergamers are gonna hate this one, arent they)

The tradeoffs of carrying "all the tools one might ever need" are that your inventory flexibility is heavily reduced while the amount of management required to keep your inventory functional is heavily increased, if you decide to stuff up on "things you need" before getting into a hypothetical action scenario you will be much less likely to be able to utilize gear that is temporarily accessible during the scenario while making the aftermath (looting) a lot more complex, now compare this to someone with an empty bag who doesn't have much choices to make or micro to manage. There are downsides and they reveal themselves very fast in action-packed gameplay and certainly do matter.

Neither is shoehorning balance changes alike the drill going to start upholding communications between people, if anything it's going to make life more annoying 95% of the times for little-to-no reason.

Now then, I really don't think the gun changes are good for the game. Carrying a sizeable gun and a couple of mags along with several other objects first and foremost prevents colossal inventory tedium, inventory micro as a nukeop is already a massive hindrance and making it worse by making most guns virtually impossible to fit in an inventory unless it's nearly or completely emptied isn't fun at all, I don't want to spend 15 seconds rearranging my bag and dropping items on the floor to fit in an SMG I looted from a secoff, and neither do the 20 ghosts staring me and the survivors down, longing for action.

This is a videogame after all, fun is first and foremost, balancing guns in a way that you're forced into one path or archetype of interactions if you have a gun makes the game less fun as well as being *more* annoying, I could be using the lot of the utility and miscellaneous tools nukeops get to allow for more fun interactions in general but instead I'm stuck with all of my inventory being taken up by a gun and it's few mags.

Solution? Just keep guns as they were.

**Comment by vanxxxx** [comment]
> > The baseball bat probably doesn't need to be a 8x2, an 8x1 would be fine
> 
> Oh yea, that looks good enough to me
> 
> Screenshot_20

hi i don't know why I received a lot of emails in 5o'clock.I don't know why you let someone @ this account.but anyway please check your settings or something else:)
Screenshot_20240315_081229_QQ Mail

**Comment by Admiral-Obvious-001** [comment]
> > > The baseball bat probably doesn't need to be a 8x2, an 8x1 would be fine
> > 
> > 
> > Oh yea, that looks good enough to me
> > Screenshot_20
> 
> hi i don't know why I received a lot of emails in 5o'clock.I don't know why you let someone @ this account.but anyway please check your settings or something else:) Screenshot_20240315_081229_QQ Mail

Screenshot_20240314_203356_Chrome
Configure your account settings to not receive sn email notification when a comment is posted (the posted image are default settings).

**Comment by vanxxxx** [comment]
> > > > The baseball bat probably doesn't need to be a 8x2, an 8x1 would be fine
> > > 
> > > 
> > > Oh yea, that looks good enough to me
> > > Screenshot_20
> > 
> > 
> > hi i don't know why I received a lot of emails in 5o'clock.I don't know why you let someone @ this account.but anyway please check your settings or something else:) Screenshot_20240315_081229_QQ Mail
> 
> Screenshot_20240314_203356_Chrome Configure your account settings to not receive sn email notification when a comment is posted (the posted image are default settings).

thank for your advice but i mean i have no relationship with Vaaankas who interact with you,and i have no idea why these messages are mentioning me:( mayby he leave a wrong dress

**Comment by northerndakotas** [comment]
MFW I already fill up 80% of my duffel bag as HoS at round start.

On a more serious note, this does so many awful things to Sec when they need to use long guns. Do any of the standard issue armory guns fit in a duffel alongside a survival box? If this change automatically forces players to choose between just 1 gun and their survival box, I don't think it's been thought through enough.

The proposed options available to players are:

> Carry it in their hands

Practice bad firearm safety by brandishing your weapon around the whole station and if you get slipped once you have armed an antag. This behavior is so frowned upon that it's one of the very first things sec cadets are taught not to do.

> Carry it in their backpack slot

Replace your entire inventory with a gun. No longer have a backpack to carry ammo in.

> Carry it inside a dufflebag and suffer the movement penalty

Replace your entire inventory with a gun again, but now with some ammo and a movement penalty. 

Fitting a gun in your inventory is already a very tedious and frustrating process. This does nothing but make the issue so much worse.

As an aside the baseball bat is 4 times the length of a saber. Which I find funny.

**Comment by Cojoke-dot** [comment]
> > I don't think its powergaming to carry a drill with you as salvage
> 
> I just think restrictions like this force player interactions, and that is most important.
> 
> If you go salvage as a duo, for example, and each of you is self-sufficient and packed with all they will ever need, you wont even need to talk to eachother. Changes like this, while they may decrease the "QoL" of individual players a bit, will force them to work together. Say in this example: if a drill is too large, one player might opt into carrying it while the other carries meds and so on.

what... do you know about the pickaxe... either way if you're mining you don't need meds... also it's salv, people who are not going to use a drill because they would have to return to the station and ask someone for something.

**Comment by skypatrol21** [comment]
> > The weapons are monstrously large. It looks weird that you can't put smg in backpack. Takes up too much space considering guns are flat
> 
> You can put an SMG in a backpack, but not in a satchel. And you can also put them in your suit slot.
> 
> Sadly there is no way to scale the inventory sprites themselves, if that is your concern. But i personally prefer gameplay over graphics.

until you can hotkey grab from suit storage this change just makes the games controls more complicated. I essentially only play sec, and If I can no longer hotkey grab my weapon, then I would probably stop playing.  These changes seem like its trying to fix a problem that doesn't really exist.

**Comment by LordEclipse** [comment]
> > > > > The baseball bat probably doesn't need to be a 8x2, an 8x1 would be fine
> > > > 
> > > > 
> > > > Oh yea, that looks good enough to me
> > > > Screenshot_20
> > > 
> > > 
> > > hi i don't know why I received a lot of emails in 5o'clock.I don't know why you let someone @ this account.but anyway please check your settings or something else:) Screenshot_20240315_081229_QQ Mail
> > 
> > 
> > Screenshot_20240314_203356_Chrome Configure your account settings to not receive sn email notification when a comment is posted (the posted image are default settings).
> 
> thank for your advice but i mean i have no relationship with Vaaankas who interact with you,and i have no idea why these messages are mentioning me:( mayby he leave a wrong dress

You are getting emails because you replied to the PR, you need to disable email notifications to prevent them from getting sent to your email.

**Comment by Admiral-Obvious-001** [comment]
Being able to stuff 9 baseball bats into a backpack never really made sense, as one example.

Some of the sizes probably don't quite make sense, like the swords but I do strongly think that the weapon sizes did and do need to be rebalanced. (On top of bottle cigarette pack meta too.)
Kammerer being a 4x2 never really made sense to me for example, same with a bunch of other sec weapons like the Lecter. The swords are probably too small and don't need to be double stacked unless it's a short blade though.

**Comment by K-Dynamic** [comment]
I'm having a tough time liking this pr

Pro: Stuffing multiple guns or bats into bags is bad

Con: All these different weapon shapes are gonna be hell to keep track of, since size doesn't explain custom shapes

**Comment by Vaaankas** [comment]
> MFW I already fill up 80% of my duffel bag as HoS at round start.

HoS can take a WT550 or a Drozd from the armory and wear it on his suit slot no problem.

> On a more serious note, this does so many awful things to Sec when they need to use long guns. Do any of the standard issue armory guns fit in a duffel alongside a survival box? If this change automatically forces players to choose between just 1 gun and their survival box, I don't think it's been thought through enough.

Again, carrying weapons in the duffel is an option with heavy tradeoffs. This way we'd force players to think about other ways to carry guns, which were previously almost unheard of.

> The proposed options available to players are:
> 
> > Carry it in their hands
> 
> Practice bad firearm safety by brandishing your weapon around the whole station and if you get slipped once you have armed an antag. This behavior is so frowned upon that it's one of the very first things sec cadets are taught not to do.

Exactly! It is now very much skill dependant and very interactive. Antags will have an easier time seeing if a secoff is heavily armed too, and would be able to pick their fights wisely.

> > Carry it in their backpack slot
> 
> Replace your entire inventory with a gun. No longer have a backpack to carry ammo in.

Dont forget looking very stylish as the result. But on a more serious note, yes, it would be nice to have this as a viable options because of reasons described above. In the secoff example, they still have access to webbings to store ammo in.

> > Carry it inside a dufflebag and suffer the movement penalty
> 
> Replace your entire inventory with a gun again, but now with some ammo and a movement penalty.

I think that this should be an option, but it is penalized accordingly, again, to make people consider other, more interactive ways of transporting firearms.

> Fitting a gun in your inventory is already a very tedious and frustrating process. This does nothing but make the issue so much worse.

As it should be. Taking a gun out of you ass in an instant is a very gamey mechanic and i would like to reduce it if possible.

This is not a QoL change, its about making guns feel and look like guns and forcing player interactions with the way you have to treat them.

**Comment by Vaaankas** [comment]
> this would be a really rough change for sec, making the satchel basically unusable for an entire role.

You can still use a satchel and carry the gun in your hands or in the suit slot if its an SMG. 

The only difference is that you wont be able to keep it safely hidden at all times, which is what this PR is all about.

**Comment by rosieposieeee** [comment]
> > this would be a really rough change for sec, making the satchel basically unusable for an entire role.
> 
> You can still use a satchel and carry the gun in your hands or in the suit slot if its an SMG.
> 
> The only difference is that you wont be able to keep it safely hidden at all times, which is what this PR is all about.

the issue is that every other person on the station will slip you. there is no amount of skill that someone with a gun in their hand can have that beats guy with soap. the only skill is walking everywhere, which means nothing gets done, and knowing not to hold the gun in your hands, which this pr makes mandatory. if satchels cant hold guns, then satchel players will just never have guns, and sec can never even choose to be able to keep pace with anyone.

plus, if you cant safely put your gun away, inventory management becomes twice as hard. what are you supposed to do, just throw it on the fucking ground

the other issue is that anything in your suit slot means you cant actually have an oxygen tank. emergency ones run out laughably quickly. this is already a tradeoff sec has to make pretty often, and again, making it mandatory sucks.

if this gets merged im open firing on anyone who walks up to me with a bar of soap as sec

**Comment by rosieposieeee** [comment]
like, honestly, if your issue is that the guns are HIDDEN, then maybe make some kind of alt to webbing that is a gun sling that can only hold one gun and a bunch of ammo, and have the guns visibly show up in the sling, _then_ make guns impossible to hidden carry without a movement penalty

**Comment by Vaaankas** [comment]
Added mosin storage sprite.

Reduced the guns' wideness since they were feeling a bit off.

Screenshot_22

**Comment by Krunklehorn** [comment]
As someone who uses the satchel, I'm confused that anyone considers the backpack as a hands-down meta. I actually think all of the bags are in a pretty good spot right now. People use them for their own reasons.

I already manage long guns like the bartender's shotgun just fine and probably won't be bothered too much by drastic changes if I know that everybody else is also encouraged to mix up their inventory strategies.

I mean, isn't that the point of gridinv? To give inventory more variety and force us to make tough choices? Yeah it sucks that I won't be able to carry much, but it already didn't make sense that I could fit a giant laser rifle into a satchel in the first place.

**Comment by K-Dynamic** [comment]
> Added mosin storage sprite.
> 
> Reduced the guns' wideness since they were feeling a bit off.
> 
> Screenshot_22

Not 100% onboard but way better than before

**Comment by skypatrol21** [comment]
> like, honestly, if your issue is that the guns are HIDDEN, then maybe make some kind of alt to webbing that is a gun sling that can only hold one gun and a bunch of ammo, and have the guns visibly show up in the sling, _then_ make guns impossible to hidden carry without a movement penalty
> 
> just making all the weapons bigger is a lazy bandaid fix that penalizes the wrong players and makes all interactions with weaponry worse

This is a very strong point and suggesting that guns should go in your suit storage is not a reasonable solution to these absurd sizes

**Comment by Vaaankas** [comment]
> > Added mosin storage sprite.
> > Reduced the guns' wideness since they were feeling a bit off.
> 
> Not 100% onboard but way better than before

It was a bit over the top before, wasnt it? xD

Anyway, the guns are still lentgh-gated from backpacks and satchels and the ones longer than 6 grids can't go into suit slots.

**Comment by Vaaankas** [comment]
> This is a very strong point and suggesting that guns should go in your suit storage is not a reasonable solution to these absurd sizes

Why not? Having your gun in the suit storage is more interactive than having it in your backpack since people can walk up and see it by examining you. I see it as a good thing for the game. It also already represents you character carrying the gun on them on a sling or in a holster.

**Comment by Vaaankas** [comment]
> > Why not? Having your gun in the suit storage is more interactive than having it in your backpack since people can walk up and see it by examining you. I see it as a good thing for the game. It also already represents you character carrying the gun on them on a sling or in a holster.
> 
> Did you not just say you forbid a large amount of these guns from going into the suit slot?

Yep, the 8x2 ones can only be worn on the back, thats the ultimate sling representation already coded into the game.

**Comment by Vaaankas** [comment]
> > Yep, the 8x2 ones can only be worn on the back, thats the ultimate sling representation already coded into the game.
> 
> that just completely removes your inventory and is not good. The having a gun instead of a backpack thing is meant to be cosmetic, not necessary.

I think it is good to have it be an option that is not purely cosmetic. It makes sense, looks good and cinematic and is very interactive. Player inventory is not limited to backpacks too: most people with guns have access to webbings and bandoliers.

Besides, being able to carry all you need at once enables powergaming and reduces player interaction as i described above.

**Comment by Vaaankas** [comment]
> > Besides, being able to carry all you need at once enables powergaming and reduces player interaction as i described above.
> 
> Removing people's inventories for having a weapon is not the solution to powergaming, that's like if sec went "we're sick of people running away from us!" and just chopped off everyone in the station's legs. Powergaming will always be an issue and there's no good single solution to entirely get rid of it.

Its not removing anything per se, or attempting to solve powergaming once an for all; dont be overly dramatic. If people want to carry large guns in their bag they can still do so at 10% movement speed penalty with a dufflebag. What this does is shine light on other options and propose different, more interactive playstyles.

**Comment by rosieposieeee** [comment]
i just dont think this could be a fun change. no one wants to lose almost their entire inventory just to holster a gun. maybe make guns visible in a satchel or bag, like when you shift click or in the sprite, poking out of them. because you could realistically hold even rifles in a satchel or bag, just sticking out.

**Comment by asperger-sind** [comment]
> There is walking, and there is using teamwork.

> You can put your gun on the ground or on a table etc. I dont see a problem with that.

And many more left unquoted. I'll be real, a lot of the arguments seem to completely ignore the state of the game and the overall viability of one's actions, a lot of the things proposed as "solutions" and "more interactive gameplay options" just don't work on live servers and LRP even more so.

**Comment by LordEclipse** [comment]
> > > Besides, being able to carry all you need at once enables powergaming and reduces player interaction as i described above.
> > 
> > 
> > Removing people's inventories for having a weapon is not the solution to powergaming, that's like if sec went "we're sick of people running away from us!" and just chopped off everyone in the station's legs. Powergaming will always be an issue and there's no good single solution to entirely get rid of it.
> 
> Its not removing anything per se, or attempting to solve powergaming once an for all; dont be overly dramatic. If people want to carry large guns in their bag they can still do so at 10% movement speed penalty with a dufflebag. What this does is shine light on other options and propose different, more interactive playstyles.

so people can just powergame duffelbag inventory instead of being given a choice? 10% movement debuff isn't actually a big deal. Nukie duffelbags give that movement debuff and they run around just fine

**Comment by Zap527** [comment]
I think most of the backlash comes from misunderstanding what this PR is trying to accomplish, and also jumping on preconcieved notions of balance and fun.

A lot of the game's depth comes from forcing imperfect solutions to imperfect problems, allowing flexibility in how to approach the issue but also creativity. Quite literally, if you open the game's design principles, you will see that:
> One key mantra to use when making new mechanics is “nothing is perfect”, conceptually this means that your mechanic should not allow for “perfect” solutions. Make sure to sprinkle plently of opertunities for players to intentionally or unintentionally screw up while interacting with your mechanic.

From where I'm standing, this is what this PR is trying to accomplish, by using pre-existing systems (backpack/suit wearing). Increasing inventory sizes forces players to choose from an array of imperfect options. All solutions have their advantages and drawbacks, allowing for dynamic gameplay and skill expression (choosing the right option for the right fights) from, relatively speaking, simple and intuitive mechanics.

Of course, this may break some roles/antagonists' workflow. Security will no longer be able to easily conceal weapons, nuclear operatives may have inventory issues and traitors might get shoehorned into commiting to a plan sooner than later if they buy large weapons. I don't think it's fair to just praise this, quote design docs and be done with it, as there will be players who suffer from potentially lowered QoL

While I don't think these concerns should stay unadressed, I also think they're being blown out of proportions. QoL isn't the only metric we should use to discuss game mechanics - not to say that it's unimportant. I think that forcing security to readapt their workflow in a playtest isn't a terrible problem. If it ends up being one, well, reverts exist.

**Comment by SlamBamActionman** [comment]
I think the main thing I disagree with here is removing the ability to have these items in the suit slot. Not only does this mess things up for certain roles (Bartender and HoS comes to mind) but I think it would greatly reduce QoL in terms of interacting with stuff. Considering the size of the weapons you'd simply encourage people to walk around with their backpack in their hands, which adds another layer of juggling things.

If the issue is that items don't show up on the back of characters when in the suit slot... I see no reason why one can't add sprite support for it that uses the backpack sprite and simply layer the items accordingly. 

I'd rather see the inventory size change get pushed through on its own and tested first, before seeing if guns need to be back slot only.

**Comment by Vaaankas** [comment]
> I think the main thing I disagree with here is removing the ability to have these items in the suit slot. Not only does this mess things up for certain roles (Bartender and HoS comes to mind, who carry their large weapons with them at all times) but I think it would greatly reduce QoL in terms of interacting with stuff. Considering the size of the weapons you'd simply encourage people to walk around with their backpack in their hands, which adds another layer of juggling things.
> 
> If the issue is that items don't show up on the back of characters when in the suit slot... I see no reason why one can't add sprite support for it that uses the backpack sprite and simply layer the items accordingly.
> 
> I'd rather see the inventory size change get pushed through on its own and tested first, before seeing if guns need to be back slot only.

That sounds reasonable, i did put a lot of changes in the same basket here... Though I'm curious to what the maintainers will say.

I made another PR to adress the suit-slot-weapon-visibility issue aswell.

**Comment by EmoGarbage404** [comment]
After internal discussion that maintainer consensus was that the changes made in this PR weren't necessary in the current balance of the game and were unjustified for a lot of the weapons. Specifically, the drastic increase in length for most guns and large melee weapons seemed to be a crippling nerf that severely hurts players without duffel bags.

It's for these reasons that we won't be accepting this PR. Thank you for your contribution.

**Pull request closed without merging**
