### PR TITLE
fix: Removes broken chemicals (razorium)

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Removes all known broken chemicals from the game.
Removed all mentions of Razorium. 
Razorium can no longer be made.
## Why / Balance

Razorium is made in the most random conditions.

90u sugar 90u lithium 10u bicardine makes razorium
100u lithium 50u sugar 50u bicardine doesn't

# WHY

There are other horrible situations like this as well but I have forgotten... 

It's honestly so shift ruining in. Whenever this happens I just give up on making chems and go grab a health analyzer.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by moonheart08 — CHANGES_REQUESTED** [review]
This is a major balance change as now you can freely mix all the brute medication, making the distinction entirely moot among other things.

**Comment by beck-thompson** [comment]
Also this should have a CL because this is a big change to med

**Comment by EmoGarbage404** [comment]
spite pr. at least put a little more effort in to come up with a reason why it isn't good besides incomprehensible ranting.

**Comment by Emisse** [comment]
image
this should be looked at in case its actually a bug so it can get fixed

**Comment by Brandon-Huu** [comment]
> > 90u sugar 90u lithium 10u bicardine makes razorium
> 
> image
> 
> it doesnt

Due it with jugs, not machines

**Comment by Brandon-Huu** [comment]
The "custom amount" thing was also broken when this happened

**Comment by Brandon-Huu** [comment]
> spite pr. at least put a little more effort in to come up with a reason why it isn't good besides incomprehensible ranting.

What other reason do I need besides "It doesn't work correctly and rewriting how chems metabolize is too much work for a bug thats been in the game for months and never resolved"

**Comment by Brandon-Huu** [comment]
Lace also is kinda broken but its fine

**Comment by deltanedas** [comment]
cope :trollface:

**Comment by Brandon-Huu** [comment]
Good bug, unlike the razorium bug

**Comment by Tayrtahn** [comment]
> What other reason do I need besides "It doesn't work correctly and rewriting how chems metabolize is too much work for a bug thats been in the game for months and never resolved"

Please submit an issue describing the bug.

**Pull request closed without merging**
