### PR TITLE
Industrial Welding Tool Craft

### PR DESCRIPTION
**Pull request by SoulFN**
## About the PR

Thir PR adds craft for industrial welding tool to autolathe
## Why / Balance

Gives engi and sci opportunity to upgrade their tools in the early shift period
## Technical details

No
## Media

- This PR does not require an ingame showcase

## Breaking changes

No
**Changelog**

:cl:
- add: Added craft for industrial welding tool to autolathe

### CODE REVIEW

**Comment by MAXbetov** [comment]
Thanks for miner and stealer

**Comment by SoulFN** [comment]
I hope, this works

**Comment by deathride58** [comment]
The industrial welder is a straight upgrade to the normal welder, and alongside the advanced variant, exists primarily as a nice-to-have form of loot to give players a small reward for exploring earlier in the round. This PR directly removes a reason to go out and explore early in the round, while also introducing a bit of bloat to the autolathe since this PR doesn't replace the existing welder recipe wholesale (which it honestly should, as there's pretty much no reason to build a normal welder if the industrial welder becomes a standard recipe).

Is there a reason why this needs to be readily-available roundstart? What problem does this PR seek to solve?

**Comment by UbaserB** [comment]
The experimental welder is research (not sure which tier it is), so maybe the industrial version can be added to a lower tier like t1 as an addition to one of the already existing ones?

**Comment by SoulFN** [comment]
> The industrial welder is a straight upgrade to the normal welder, and alongside the advanced variant, exists primarily as a nice-to-have form of loot to give players a small reward for exploring earlier in the round. This PR directly removes a reason to go out and explore early in the round, while also introducing a bit of bloat to the autolathe since this PR doesn't replace the existing welder recipe wholesale (which it honestly should, as there's pretty much no reason to build a normal welder if the industrial welder becomes a standard recipe).
> 
> Is there a reason why this needs to be readily-available roundstart? What problem does this PR seek to solve?

it's good to give them a chance to improve their tools, because they really need them (engineers for sure), I know about advanced tools tech, but sometimes scientists can't research them or it takes too long, an industrial welding tool isn't too different from a regular tool, but it's very rare to find one, which takes away the point of it, why do you need an item when you can't get one, and it's much easier to get a better one? (I`am about experimental welding tool)

**Comment by SoulFN** [comment]
> The experimental welder is research (not sure which tier it is), so maybe the industrial version can be added to a lower tier like t1 as an addition to one of the already existing ones?

I think I can make an advanced industrial welder researceble in different PR, but I don't want to make an industrial welding machine a technology, it` not too powerful to spend your research points.

**Comment by EmoGarbage404** [comment]
I don't really see a reason to make upgrades this plentiful. These are better off let as uncommon loot in maints or inside of engineering rather than being so readily available. Being able to distribute these upgrades to anyone severely harms the value of regular welders.

**Pull request closed without merging**
