### PR TITLE
Fix issue with windows not dropping shards

### LINKED ISSUE #16706: Plasma glass shard inconsistencies
## Description
Obtaining plasma glass shards is very inconsistent. The only way I was able to get some is by breaking a plasma glass table. Breaking plasma glass sheets and windows seems to have a 50/50 chance to drop a regular glass shard, or nothing at all.

**Reproduction**
Break plasma glass sheets and windows. Regular glass shards will be created.
Only breaking plasma glass tables seem to produce the plasma shards.

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Glass shards have SpaceGarbage component, so they were colliding with the window upon spawning and were immediately being deleted. This change skips deletion if the entity was created on the current tick.

Fixes #16706 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Fixed an issue where broken windows weren't dropping shards

### CODE REVIEW

**Comment by themias** [comment]
Hmm, failing tests seem unrelated. I'll get the latest whenever those are fixed.

**Comment by ElectroJr** [comment]
I think a better fix would be to just make the space-garbage system not delete newly spawned entities. That would avoid unnecessarily slowing down entity spawning due to destruction, and fix similar issues for garbage spawned via other means.

**Comment by deltanedas** [comment]
its possibly doable with lifestage

**Comment by themias** [comment]
> its possibly doable with lifestage

It's already initialized by the time it collides. Thanks for the idea, though.

**Comment by Vordenburg** [comment]
The issue with SpaceGarbage is that the entities spawned are not attached to the grid they're being placed on, thus the cross-grid collision and deletion.

**Comment by metalgearsloth** [comment]
Superseded by https://github.com/space-wizards/RobustToolbox/pull/4126 I forgot vord mentioned it.

**Pull request closed without merging**
