### PR TITLE
Shotgun spread increase.

### PR DESCRIPTION
**Pull request by Admiral-Obvious-001**
This is another test to reduce shotgun lethality in long halls. A lot of the mid range consistency of shotguns seems to stem from spread of pellets. This should again nerf the shotgun at extreme ranges while allowing for them to dominate point blank compared to rifles.

## About the PR

Increased shotgun spread by 7 degrees to test live.
## Why / Balance

Shotguns are still very strong at mid/long range and tweaking damage further will cause shotguns to lose dominance point blank versus SMGs,
## Technical details

I changed an value
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Probably not.

**Changelog**

:cl:
- tweak: Changed shotgun spreads to be less consistent in long hallways.

### CODE REVIEW

**Comment by Admiral-Obvious-001** [comment]
22 degrees might be a little too much but feels about right I think?

**Comment by ps3moira** [comment]
Is there video to show the differences?

**Comment by metalgearsloth** [comment]
A screenshot with the gun overlay would be appreciated.

**Comment by Admiral-Obvious-001** [comment]
I'm an idiot and forgot to set this one to draft to get the images first. I'll close it for now and reopen it later once I get them (might be a couple of days due to work).

**Comment by deltanedas** [comment]
you can just set it to draft :trollface:

**Pull request closed without merging**
