### PR TITLE
New cloth & hair

### PR DESCRIPTION
**Pull request by JustArt1m**
## About the PR
Adds a new hair.

## Why / Balance
Just for big customization options.

## Media
Bob5Hair
LongWithBundlesHair

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Just_Art
- add: Added bob 5 hair!
- add: Added long hair with bundles!

### CODE REVIEW

**Comment by Emisse** [comment]
Looks good but we cannot legally license these as CC-BY-SA 3.0 due to them being a derivative of copyrighted work. You will need to find an appropriate license to fit these or contact the copyright holders for sublicensing. An alternative would be to change them just enough to not directly infringe and remove any reference to copyrighted material.

**Comment by JustArt1m** [comment]
> Looks good but we cannot legally license these as CC-BY-SA 3.0 due to them being a derivative of copyrighted work. You will need to find an appropriate license to fit these or contact the copyright holders for sublicensing. An alternative would be to change them just enough to not directly infringe and remove any reference to copyrighted material.

Will it be enough to remove references from the names?

**Comment by potato1234x** [comment]
new tg style sprites bad

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
The hair is fine, but the maintainer team does not want the clothing outfits. If you remove them, we're perfectly fine with adding in the hair.

**Comment by JustArt1m** [comment]
> The hair is fine, but the maintainer team does not want the clothing outfits. If you remove them, we're perfectly fine with adding in the hair.

Ok, i'll delete them

**Pull request merged**
