### PR TITLE
feat(inventory): Add secondary smart-equip star

### PR DESCRIPTION
**Pull request by exincore**
## About the PR

Adds a secondary quick-remove marker to the grid inventory to indicate the next-in-line item to be quick-removed.

See #22236

## Why / Balance

Provides greater visual indication of the ordering of grid inventory items. This change assists players checking whether items are in the desired order when planning to quick-remove more than one item sequentially.

## Technical details

Replaces the marking `bool` with an `enum` for each grid piece to indicate a first or second quick-remove marking. During draw, the corresponding texture is selected.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot_20240229_044441_cropped

Screenshot_20240229_044517_cropped

<details>
<summary>Original PR media - out of date</summary>

Screenshot_20240228_190328_cropped

Screenshot_20240228_190330_cropped

</details>

**Changelog**

:cl:
- add: Inventories now show a secondary smart-equip star.

### CODE REVIEW

**Comment by exincore** [comment]
Open for feedback, especially for the icon itself. Here is a mini bronze star replacement.

Screenshot_20240229_013526_cropped

**Comment by K-Dynamic** [comment]
> Open for feedback, especially for the icon itself. Here is a mini bronze star replacement.
> 
> Screenshot_20240229_013526_cropped

Bronze star too dark to see (especially with welder), maybe make the outline brighter

**Comment by ThatOneGoblin25** [comment]
Silver star?

**Comment by exincore** [comment]
> Silver star?

I considered silver but dismissed it because I thought it would be too bright and detract from the primary gold star. However, in practice, it seems very nice.

Screenshot_20240229_021624_cropped

**Comment by exincore** [comment]
Matched luminosity. I might keep the edges lighter than the corresponding gold star since the sprite is smaller and the "inside" has fewer pixels to shine with.

Screenshot_20240229_035254_cropped

**Comment by notquitehadouken** [comment]
maybe make it the same size as the gold star?

i don't really see a reason to make it smaller if it already has a distinct color

**Comment by exincore** [comment]
> maybe make it the same size as the gold star?
> 
> i don't really see a reason to make it smaller if it already has a distinct color

I chose a different shape for color vision accessibility.

**Comment by Golinth** [comment]
personally, I think the small silver star was the best looking, and the best at conveying what it meant to the player. The order usually goes Gold > Silver > Bronze anyway.

**Pull request merged**
