### PR TITLE
Syndicate item fix ups

### PR DESCRIPTION
**Pull request by ThatGuyUSA**
## About the PR
Changed various uplink descriptions, fixed syntax errors, and made various items that were not syndicate contraband into syndicate contraband.

## Why
The uplink descriptions, while not wrong, seemed to be torn between numbers and words when using timers.

## Technical details
Changed 1 .ftl, and 6 .yml. (it says 2 .ftl but trust me it's only 1)

## Media
Media can be seen here, there is quite a lot for a PR post so I put it in a google document if that's okay
https://docs.google.com/document/d/1wYRldRX2nrx0fzYxlh72CZea0Ia1j4VsHTVYaMkEIgs/edit?usp=sharing

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

### CODE REVIEW

**Comment by ThatGuyUSA** [comment]
I built and ran this successfully... how...

**Comment by slarticodefast** [comment]
Unrelated random test fail, I'm rerunning it for you

**Review by slarticodefast — APPROVED** [review]
Thanks for the cleanup!

**Comment by slarticodefast** [comment]
ignore the weird labeler fail

**Pull request merged**
