### PR TITLE
Medical belt can now hold additional medical items

### LINKED ISSUE #11173: Health analyzer can't be stored in medical belt
Also latex gloves, and sterile masks.

### PR DESCRIPTION
**Pull request by DerSheppard**
## Medical belt now holds additional medical items  

The medical belt is now able to hold a health analyzer, latex gloves, nitrile gloves and sterile mask.
Fixes #11173 

**Screenshots**

image

**Changelog**

:cl: Sheppard
- add: Medical belt can now hold additional medical items.

### CODE REVIEW

**Comment by Cheackraze** [comment]
Again? I thought this was decidedly a bad change. If utility belts can't even hold all tools why do doctors get to store clothing in their belts

**Comment by DogZeroX** [comment]
#11188

**Comment by EmoGarbage404** [comment]
Maybe the health analyzers shouldn't be in here, but i don't think theres anything wrong with adding gloves and masks and such. Probably shouldn't have been closed this quickly.

**Comment by rolfero** [comment]
If this PR isnt accepted, please close #11173

**Pull request closed without merging**
