### PR TITLE
Adds 2 new space ruins

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds 2 new space ruins: the empty flagship, and chunked telecomms.
Empty flagship is a refitted version of spacebattle.dmm from ss13. Chunked telecomms is a small ruin that replaces relaystation.

The empty flagship has lots of miscellaneous loot, and is most desirable for its cargo cache & armor.

Chunked telecomms does not have much loot at all. It only contains a single encryption key & industrial loot spawner.

## Why / Balance
I always thought SS13 spacebattle had immaculate vibes for just how eerie and empty it was, so I made it in to a space ruin.

Relaystation was also just not really interesting or fair; getting free security telecomms keys is not good. Chunked telecomms still has the *potential* for this, but you'll more often then not get something mediocre. This is also good since we generally need more lower-tier space ruins to pad out the ruin pool.

## Media
**Chunked telecomms**

image

**Empty flagship**
Content Client_ZOqzl1fOeB

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- remove: Replaced RelayStation with a more fair ruin.

### CODE REVIEW

**Comment by GroggleG** [comment]
>Chunked telecomms does not have much loot at all. It only contains a single encryption key & industrial loot spawner.

Is that a uh, fucking centcomm encrypt or am I tweaking?

**Comment by Flareguy** [comment]
> > Chunked telecomms does not have much loot at all. It only contains a single encryption key & industrial loot spawner.
> 
> Is that a uh, fucking centcomm encrypt or am I tweaking?

It's a random encryption key spawner. What you will actually get from it is random.

**Comment by Holinka4ever** [comment]
In my opinion, space ship need enemies to defend loot, cause in other wise its just loot pinyatã for salvage and no more.

**Comment by Emisse** [comment]
its a ruin not a salvage, we will add special mobs to them eventually

**Pull request merged**
