### PR TITLE
Add Syndicate SecShades to uplink

### PR DESCRIPTION
**Pull request by TurboTrackerss14**
## About the PR
This item has sat unused for a while now from what I see. Lets give it a run.

## Why / Balance
2tc sounds reseasonable to experiment

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Add hidden security hud shades to syndicate uplink.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
@TurboTrackerss14 for scrutinized topics such as item and uplink balancing, you are expected to provide legitimate justification for the changes you are making. Please elaborate why you think your proposed changes are good beyond simply "sounds reseasonable [sic]"

**Comment by TurboTrackerss14** [comment]
Originally it was just a "oh this item is unused". 

After a few minutes of thought I considered it a reasonable addition to the uplinks catalog considering the "buff" security gets working as a whole, with the new Criminal record usage and all sec starting with hud now.
Giving a traitor an opertunity to spotcheck their wanted status. 

This doesn't feel to big as it doesn't show wanted reason, nor announce it when it goes live. Just the HUD icon change/appearing.

**Comment by Cojoke-dot** [comment]
Maybe a nukie version of this for stealth ops but a syndicate hud? That would help with something like a fake centcom visit and you not killing the rest of your team due to having no visor

**Comment by EmoGarbage404** [comment]
> Giving a traitor an opertunity to spotcheck their wanted status.

i feel like it's a pretty boring way to introduce this kind of behavior. It's pretty similar to how we've refused PRs in the past that allow traitors to simply purchase a sec radio key. You're compromising internal communication (one of sec's only real advantages) while creating no risk or emergent gameplay. I think it's far more interesting to encourage people to steal sechuds or secglasses from wherever they can get them, as it leads to greater player interaction.

I feel like items like this--that you can essentially acquire normally through some kind of thievery--are bad fits for uplink items since they partially invalidate a more risky style of play.

**Comment by Ghagliiarghii** [comment]
just buy thieving gloves and steal it from a sec cadet or buy a gun and kill a security officer in maints or something

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
Personally, I think we should bring back the old observation bundle that had the glasses and the syndie crew monitor.

**Comment by TooSillyFennec** [comment]
Headrev should have this too. (As a replacement for their sechud implant)

**Comment by ps3moira** [comment]
This seems like a lazy syndicate item. Plus there's items in the uplink that do both of these things.

**Comment by TurboTrackerss14** [comment]
Closing due to lack of discussion + agreement with above stated points. 
Traitors have IC methods of attaining sechud, and this was removed from a bundle with good reason.

**Pull request closed without merging**
