### PR TITLE
Adds clap and laugh actions.

### PR DESCRIPTION
**Pull request by SweptWasTaken**
Refactored ScreamAction.cs to be a little more generalized and added a basic-bitch SoundAction.

### CODE REVIEW

**Comment by PJB3005** [comment]
I am not fond of adding new actions for every silly emote like this. This should really be generalized into a separate system so you have ONE action to access all these silly sound emotes.

**Comment by SweptWasTaken** [comment]
> 
> 
> I am not fond of adding new actions for every silly emote like this. This should really be generalized into a separate system so you have ONE action to access all these silly sound emotes.

I mean there's not really a HUGE selection of these you could add. These 2 are pretty iconic and think would be fine as their own emotes for now. It's not like they clog up the actions UI menu.

**Comment by metalgearsloth** [comment]
PJB's about to do hugs so maybe see how he does it and copy it.

**Comment by SweptWasTaken** [comment]
> 
> 
> PJB's about to do hugs so maybe see how he does it and copy it.

K. I still think it's fine to have this stuff in here since we have so little emotes as it is. I'll close this for now.

**Pull request closed without merging**
