### PR TITLE
N2O color change

### PR DESCRIPTION
**Pull request by laok233**
## About the PR

changed N2O color in gas analyzer.
Fixes https://github.com/space-wizards/space-station-14/issues/30382
## Why / Balance

the same color is used for oxygen.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Can you show a picture of the new color next to the o2 one?

**Comment by laok233** [comment]
for some reason the image isnt shown
link: image

**Comment by laok233** [comment]
image

**Comment by slarticodefast** [comment]
Small tip: If you write "Fixes #30382" in your PR description it will automatically close that issue once your PR gets merged.

**Comment by Brandon-Huu** [comment]
Add
``Resolves #30382``` 
to your PR description

**Pull request merged**
