### PR TITLE
Chemical implants for security and syndicate uplink

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

Adds two new implants for security: the lethal chemical implant and the nonlethal chemical implant.
Adds one new implant for the traitor/nukie uplink: the emergency chemical implant.

The emergency chemical implant injects the user with 30u of omnizine and 20u of dexalin plus when the they go into crit, after which it is deleted.

The security chemical implants contain either 25u of lexorin and 25u of nocturine for the lethal version, or 50u of nocturine(170 seconds of sleep) for the nonlethal version.
The security chemical implants can only be remotely activated through a criminal record console, this requires security access.

## Why / Balance

The emergency implant allows traitors and nukies to get out of crit if they fall into it while not in reach of the enemy. It can't be activated manually, so it's not just an easy way to get some healing mid-battle.

The security chemical implants give security more variety in their punishment levels, this will allow security to release known criminals with a chemical implant instead of just putting them in perma. If the person that got released gets caught causing trouble again they can be remotely incapacitated or killed.

## Technical details

When a chemical implant is successfully injected into an entity, their criminal record will be updated with this new implant. If the "activate implants" button on the criminal record console is pressed all the chemical implants in their body will be triggered instantly. When triggered, the implant will transfer it's solution to the bloodstream of the entity it's implanted in, after that it gets deleted.

## Media

https://github.com/space-wizards/space-station-14/assets/137322659/6d680960-b8df-4c54-8f52-b5c5a549ac49

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- add: Security can now get lethal and nonlethal chemical implanters from cargo, these implants can be remotely triggered from a criminal record console.
- add: The syndicate uplink now has an emergency implanter available for purchase, this implant will inject healing chemicals when the user goes into crit.

### CODE REVIEW

**Comment by UbaserB** [comment]
this is actually really clever wow

**Comment by K-Dynamic** [comment]
Healing implants in general are interesting. However, 30u omnizine heals 40 of each brute type alone, and 20u dexalin+ heals like 140 asphyx and 120 bloodloss. This might depend on where and how you die but it seems unbalanced.

Sec implants loaded with massive amounts of syndie chems (nocturine and lexorin) seems off; non-lethal should replace nocturine with chloral hydrate or licoxide.

Kill implants seem really excessive too; they'd probably be okay for MRP (repeated escapes from perma lead to execution), not so much for LRP.

**Comment by thebadman4662** [comment]
Chloral hydrate would be lethal in implant though, thats why its nocturine.

**Comment by deltanedas** [comment]
healing implant should be fairly expensive since it does much better than most medics

**Comment by ArchPigeon** [comment]
This seems like it would just make seccies implant criminals with killswitches then throw them in perma, offering zero counterplay for the criminal in the unlikely chance that they escape from perma somehow

**Comment by VektorZ1** [comment]
nocturine with lex is basically sindy chemicals. I think it would be better to add some new reagent that can disarm the target for a while, but not kill it

**Comment by K-Dynamic** [comment]
> nocturine with lex is basically sindy chemicals. I think it would be better to add some new reagent that can disarm the target for a while, but not kill it

Licoxide would work as per previous suggestion (basically chem with stunning percentage)

That or make it directly do stamina damage and stun them without chem (shock collar essentially)

Kill implants seem really out of place for sec, especially since executions warrant captain's approval unless the perma is extremely dangerous to begin with... then they'd be executed anyway?

**Comment by thebadman4662** [comment]
Well, its not like a permadeath implant so I guess sec will have option to revive them still, just won't have to deal with time limit as much.

**Comment by IProduceWidgets** [comment]
I actually think lexorin is best, but I would just remove the nocturine. Then it's a funny problem where if you have one you can potentially save yourself from getting ended by the implant by using an emergency pen or epinephrine.

Some additional bikesheds I would like to mention:
- a similar way to activate the tracking implant so it says where they are.
- perhaps a way to add chemicals to an empty implanter so you can make your own "emergency chemicals" would be neat.

**Comment by deltanedas** [comment]
> perhaps a way to add chemicals to an empty implanter so you can make your own "emergency chemicals" would be neat.

emergency amatoxin implanter :trollface:

**Comment by Carmell0** [comment]
Reminds me of the time chem and CMO made a mix that round removed you and put it in the hypo, called it "emergency suicide"

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by JackTalentedCoder** [comment]
Are you going to make new version? This upstream have a potential in game

**Pull request closed without merging**
