### PR TITLE
SS14 Gender Swap Episode 2

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Adds a Gender Swap implant which gives the user an action that swaps their pronouns and sex between male/female. Can be printed in the Medical Fabricator.
## Why / Balance

same reasons as #29528 but without the issues of people getting randomly injected with chems.
## Technical details

Swaps the gender and sex of the user between female/male. No effect on Neuter and Epicene individuals gender-wise and no effect on Unsexed individuals sex-wise. Uses SetSex and SetGender, runs a QueueIdentityUpdate if the gender is changed and user has the IdentityComponent.
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/6c3c2696-1bea-449e-8f3d-98b60c8bcbf4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Adds the Gender Swap Implant to the medical fab, allowing the user to swap between female/male.

### CODE REVIEW

**Comment by Errant-4** [comment]
This made me think, but what do the pronouns ingame *actually* represent in the game world? Thus, what would be a reasonable "requirement"/cause in-game/universe for them to change

Asking because just swapping between she and he is half the job, what if a vox wanted to change from she to they? It sounds like maybe this implant could be a bit more customisable in scope when activated, but you are under no obligation to consider this scopecreep

**Comment by Cojoke-dot** [comment]
> Asking because just swapping between she and he is half the job, what if a someone wanted to change from she to they? It sounds like maybe this implant could be a bit more customisable in scope when activated, but you are under no obligation to consider this scopecreep

yeah, I thought about that, I would need a UI popup for that to function in the way I would want it and that's just too much for me.

**Comment by engineer-pearl** [comment]
I don't know... My mind is already going to that interaction I had one session that really didn't feel good. Note this is a low accuracy representation cause it was a bit ago and I didn't want to linger on it.

Someone: "Good boy" 
Me (borg): "I am not a boy"
Someone: "Law 2, you are now a boy"

This feels like something that just extends this type of interaction to organics?

**Comment by Errant-4** [comment]
> I don't know... My mind is already going to that interaction I had one session that really didn't feel good. Note this is a low accuracy representation cause it was a bit ago and I didn't want to linger on it.
> 
> Someone: "Good boy" Me (borg): "I am not a boy" Someone: "Law 2, you are now a boy"
> 
> This feels like something that just extends this type of interaction to organics?

This PR literally specifies that the effect needs to be activated by the player, how is your borg story comparable?

As a sidenote, if someone acts creepy by your judgement,  do not hesitate to ahelp them. Especially if they are using rank/relative status

**Comment by engineer-pearl** [comment]
I was looking in the video for how it was locked to the player, but it looks like it only requires an injection. My point of reference here is mind shields, so I am not seeing what part requires consent to succeed.

**Comment by Errant-4** [comment]
> I was looking in the video for how it was locked to the player, but it looks like it only requires an injection. My point of reference here is mind shields, so I am not seeing what part requires consent to succeed.

From what I understand it works like the identity scrambler. Anyone can inject your character, but that only gives them the ability. You the player need to activate it

**Comment by Plykiya** [comment]
> > I was looking in the video for how it was locked to the player, but it looks like it only requires an injection. My point of reference here is mind shields, so I am not seeing what part requires consent to succeed.
> 
> From what I understand it works like the identity scrambler. Anyone can inject your character, but that only gives them the ability. You the player need to activate it

I tried to DNA scrambler people as an antag for the fun of getting someone arrested for not being the real (job person) but was disappointed to learn that it required the person to activate it

**Comment by engineer-pearl** [comment]
Ah, well that's not so bad then. 

I haven't used the scrambler myself - I don't have many antags selected, and only had one round as an antag (surprise Nukie round), so it's nice to know my frame of reference is just a bit more limited than it needed to be.

**Comment by 0x6273** [comment]
I think this should just open an ui that lets you pick any sex/pronoun

**Comment by Thurtik** [comment]
I don't see the point in adding this. If you wanna play as some gender, just make your character that gender.

**Comment by Plykiya** [comment]
> I don't see the point in adding this. If you wanna play as some gender, just make your character that gender.

you can pretend to be a ling by genderswapping and then using a magic mirror for your hair

a surprising amount of people attempt to cosplay as other people on shift... to varying degrees of success based on gender/race

**Comment by Sarahon** [comment]
This will make secs job a nightmare to be honest.

**Comment by ZombieChibiXD** [comment]
My only question with this is, does implanter revert the gender change process?

**Comment by Cojoke-dot** [comment]
> My only question with this is, does implanter revert the gender change process?

You need another implanter but yeah, you can revert it.

**Comment by Plykiya** [comment]
> This will make secs job a nightmare to be honest.

Sec genders people male 95% of the time regardless of what the target is, I think they'll be fine.

**Comment by SlamBamActionman** [comment]
While it might complicate things a bit codewise, I think opening up a small UI window to select sex & pronouns would be ideal. That way it is more futureproof against species without binary sexes and allows for a pronoun change at the same time.

The potential to use this to evade Sec is less than what a pair of scissors does, and if someone does escape Sec using this... Honestly it'd be pretty based and a Sec skill issue.

**Comment by Cojoke-dot** [comment]
> While it might complicate things a bit codewise, I think opening up a small UI window to select sex & pronouns would be ideal. That way it is more futureproof against species without binary sexes and allows for a pronoun change at the same time.

yeah... I'm at the point where I'm just going to learn how UI works so I can do it, PR is going into draft I guess

**Comment by Sarahon** [comment]
> > This will make secs job a nightmare to be honest.
> 
> Sec genders people male a majority of the time regardless of what the target is, I think they'll be fine.

Not necessarily what I meant. More that for me who plays a female character. If I steal a guy's ID people have easily identified me as a thief. If I can just change my gender then it becomes a lot harder for sec but a lot easier for me as antag

**Comment by Peptide90** [comment]
NT give out gender therapy to their workers while on shift working now? The megacorp really does have feelings!

On a serious note, I see how you aimed the first PR at having an alternate way to hide your identity that’s easy access. Putting this now into medical fabs adds an extra layer of complexity that I just can’t see sticking. 

Yes it doesn’t cost TC but the sole purpose of having this implant is to evade security. And other reason does not belong in a 3 hour round / shift where 90% of players are working. Your character can change gender between shifts. If there’s flaws with my lore or reasoning I’m all ears but this just seems like bait to me and I can’t see much of a reason for it to exist in a round when other things achieve the same end.

**Comment by ZombieChibiXD** [comment]
> If there’s flaws with my lore or reasoning I’m all ears but this just seems like bait to me and I can’t see much of a reason for it to exist in a round when other things achieve the same end.

I don't know, some people like the ability to actually be genderfluid? Or gender fluid clown? The ability to change name on shift? The RP possibilities are endless.

**Comment by Cojoke-dot** [comment]
Nah, probably not. I've lost most of the motivation to make PRs sadly. I may come back to this in the future but for now I'll close it.

**Pull request closed without merging**
