### PR TITLE
Emag be quiet

### LINKED ISSUE #20641: Other players can see the floating text message when you emag something
## Description
When you emag a door a message pops above your head *The card zaps something in the airlock*. Everyone else can see the same message.

**Screenshots**
 
Zapping an airlock:
image

**Additional context**
This is a problem because it can artifically give away the player using the emag. 
There are already physical clues that someone is using the emag:

1. The emag is held in your hand(might be another issue because the emag currently has no in hand sprite).
2. There is an audible zap and buzz when the emag is used.
3. The airlock lights up and then goes dark before opening.

Players should have to be aware and specifically looking for this happening if they want to catch someone using an emag. The blatent *The card zaps something in the airlock* is artfical and very easy to spot even if you are not looking for it.

emags are supposed to be a stealth option, having a large amount of text float above your head for a few seconds is anything but stealthy and offputting.

Open to sugestions and opinions!

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Closes #20641 

Makes the text that shows up when you emag something only visible to the emagger

## Why / Balance

See #20641 

## Technical details

Changes the `PopupClient` to `PopupEntity`

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: EMAGs no longer show the emag text to literally everyone

### CODE REVIEW

**Comment by LankLTE** [comment]
Yeah this is not an issue, the emag isn’t supposed to be completely silent and unnoticeable

**Comment by deltanedas** [comment]
not an issue as in it doesnt happen

**Comment by notquitehadouken** [comment]
apparently my eyes decieveth

**Comment by Partmedia** [comment]
This screenshot is with two side-by-side clients. I confirm that "nothing happens".

image

**Pull request closed without merging**
