### PR TITLE
remove directional switch/button

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

removed the construction graphs and entity prototypes, migrated them to the fixed versions

maps will need resaving after merge

## Why / Balance
since all switches/buttons are now directional these look horrible

so removed them

## Technical details
no

## Media
one of them on box that used to be directional and will be normal

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
removed the directional prototypes:
```yml
# 2023-09-13                                                                                                                                                                    
ApcNetSwitchDirectional: ApcNetSwitch                                                                                                                                           
SignalButtonDirectional: SignalButton                                                                                                                                           
SignalSwitchDirectional: SignalSwitch
```

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Emisse** [comment]
hmm we still need directional ones for door locks, etc but i guess we can remap them

**Comment by ChilbroBaggins** [comment]
Why?

**Comment by deltanedas** [comment]
> hmm we still need directional ones for door locks, etc but i guess we can remap them

they are directional

> Why?

the directional prototypes look horrible
the other ones were recently made directional so theyre both redundant and bad

**Comment by ChilbroBaggins** [comment]
> the directional prototypes look horrible 

Can you provide a better picture. I can't really tell from the one above on mobile. We've been using these downstream for over a year with no issues. 

Where is the PR that made the other ones directional? I don't see it.

**Comment by ChilbroBaggins** [comment]
Nevermind, I found it.... This is the wrong way to fix the problem. The respire shouldn't add an offset. That is handled by the prototype. A better fix would be to recenter the sprites.

**Comment by deltanedas** [comment]
> But don't remove the whole thing. Because just making the sprite directional isn't the same as making the entity directional.

as far as i know the entities cant be used from behind the wall etc so its still ok

the issue in words is the button sprite is offset so it appears between 2 tiles instead of like the normal one

**Comment by ChilbroBaggins** [comment]
> as far as i know the entities cant be used from behind the wall etc so its still ok 

The base ones can be used 360 degrees. 

The directional are 180.

> the issue in words is the button sprite is offset so it appears between 2 tiles instead of like the normal one 

Right, because it's being offset by both the sprite and the prototype. So just remove the line above and it should be ok. 

Reason you'd want to alternatively recenter the sprite though, is for the base switches. Because they can be accessed 360. It could be weird for them to be offset.

**Comment by deltanedas** [comment]
that doesnt make sense since its facing a direction how can it be used from any angle
would make more sense for a floormounted one (which would also be useful in its own right i hate walls)

**Comment by ChilbroBaggins** [comment]
Because that's just the sprite.

The degree of accessibility is defined in the wallmount->arc node.

**Comment by ChilbroBaggins** [comment]
There's also the option of simply making all switches directional. I didn't do that originally because I thought there was still some cases where they are useful with 360 access. And options are nice. 

I'd probably wait for more input from Emisse before doing that though.

**Pull request closed without merging**
