### PR TITLE
Medical borg add chem glasses

### PR DESCRIPTION
**Pull request by marboww**
## Why / Balance

This is quite logical. Borg will be able to understand what substance he is taking. This also works on the syndicate's medical borg. (#27880)

## Media
image

## Technical details

Adding the SolutionScanner, FootstepModifier Component
### Micro-Changes
Adaptation of ShowMedicalIcons for the syndicate (#28391)

**Changelog**

:сl: marbow
- add: Now the medical borg can examine the contents of the solution and the health of the patient.

### CODE REVIEW

**Comment by marboww** [comment]
oh, it seems I have to get approval from certain people?

**Comment by marboww** [comment]
thanks Ed

**Comment by 0x6273** [comment]
Why? "This is quite logical" isn't a very good justification. What problems are these changes trying to solve?

Med borgs already have med scanner module, and they can communicate with the doctors to find out who needs treatment.
And they can read the labels to find out what's in a jug or beaker. If it's mislabeled or not labeled at all, that is a chem player skill issue and not a problem with the game design.

**Comment by B1essedknight** [comment]
Considering that organic doctors have a medical Hud apart of their default kit (if they choose to wear it) it makes sense that a robot that was tailor-made for the medical department would have it built in, plus it can be a nice bit of QoL so the borg can identify at a glance who needs aid more rather then scanning and inspecting. 

As for the chem goggles, Idk, even the job its made for barely uses it.

**Comment by muburu** [comment]
> Why? "This is quite logical" isn't a very good justification. What problems are these changes trying to solve?
> 
> Med borgs already have med scanner module, and they can communicate with the doctors to find out who needs treatment. And they can read the labels to find out what's in a jug or beaker. If it's mislabeled or not labeled at all, that is a chem player skill issue and not a problem with the game design.

medical doctors can get medhuds roundstart on every single station, why shouldn't medborgs have such a basic thing? i really don't like it when cyborgs are designed to be helpless babies that can't do anything on their own.

as for chem goggles i don't see any reason for them to not have it, they're apart of medbay and that includes chem, you aren't getting some insane unbalanced advantage by being able to see what's in a beaker.

plus, the diagnosis module isn't even a thing anymore, you only get a medical scanner with the advanced module (which is dumb i don't know why the basic module doesn't have it).

**Comment by EmoGarbage404** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by marboww** [comment]
@EmoGarbage404 reopen please

**Comment by marboww** [comment]
> Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

@EmoGarbage404 reopen please

**Comment by Cojoke-dot** [comment]
#28391

**Comment by marboww** [comment]
why can my changes freeze, but almost the same changes from others don’t? ok, I'll fix it

**Comment by marboww** [comment]
I'm waiting...

**Review by TheShuEd — APPROVED** [review]

**Pull request merged**
