### PR TITLE
Players can no longer see that emagged cyborgs' internals have been tampered with.

### PR DESCRIPTION
**Pull request by Zap527**
## About the PR
Emagged cyborgs can no longer be revealed by simply examining their internals

## Why / Balance
Currently, it is incredibly easy for any crew member to walk up to any cyborg and either ask them to open themselves or directly do it, with only a screwdriver, allowing them to immediately know whether a cyborg was emagged or not. 
This effectively means that emagged cyborgs can be "gamed" incredibly easily by anyone, without much in the way of counterplay on the end of the cyborg.

This change kills "screwdriver meta" for good. Originally, it was tied to diagnostic HUDS, but after maintainer feedback it was deemed better to just axe the message altogether.

## Media
Emagged borgs are no longer visibly emagged.
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl: Jajsha
- tweak: Emagged cyborgs no longer reveal that they have been emagged by simply examining their internals.

### CODE REVIEW

**Comment by B1essedknight** [comment]
Technically Engineering in some cases would also be able to see their internals since some stations have diagnostic huds mapped within their department.

However I like this as it gives more reason to use the diagnostic hud, since I rarely ever see anyone use it and most borgs just come up and ask to be repaired anyways.

**Review by mirrorcult — APPROVED** [review]

**Comment by lzk228** [comment]
@Zap527 could you please send a link to the discord review?

**Comment by Zap527** [comment]
https://discordapp.com/channels/310555209753690112/770682801607278632/1238306744413978716 is the start of the review process.

Important part is mostly this
image

**Comment by EpicJoston** [comment]
Now that compromised law governing internals can no longer be discovered by examination, we need to add another way for Scientists to discover that a Cyborg has been emagged. Ideally this will happen by running a 'diagnostics test' on suspicious Borgs which will check the law governing internals similar to how an implant search works. This way you remove the 'gamey' screwdriver element of being an emagged borg while still forcing Security to utilize Science to confirm emag status on rogue Borgs.

The problem with making it impossible to confirm if a Borg is emagged at all is the fact that not all Borgs acting in rogue ways are emagged. Some are ion stormed, and some are completely fine but are forced to act suspicious because of Law 2. I cannot in good faith trust people to intuitively figure out if a Cyborg is emagged, because most players don't properly understand Silicon laws and can't tell the difference between Ion Storm and Emag. Ironically, I've almost exclusively used the trusty screwdriver to defend Cyborgs against faulty emag accusations.  Without this surefire check, perfectly fine or fixable Cyborgs are going to be unjustly destroyed and sent back to Science for a new chassis, which was already a common occurrence despite the fact anyone could check the law governing internals. 

Additionally, the new Robotics Console makes it easier than ever to metagame emag status. You just tell Security which Borgs you've disabled or destroyed, and if the Borg is later seen still functional without being repaired then it must be emagged. Alternatively, Security can radio the RD asking to disable a Borg standing in front of them, and if it doesn't get disabled then its emagged. This means evil Borgs are still completely vulnerable to being 'gamed' without room for deception, or players will simply ignore everything and just murder all suspicious Borgs on sight without question. I feel this change has created more problems for Borgs, not less.

**Comment by Zap527** [comment]
Might as well adress this even though this is merged.

­> Ideally this will happen by running a 'diagnostics test' on suspicious Borgs which will check the law governing internals similar to how an implant search works.
While this might seem like a good idea in theory, this would essentially be adding a "traitor tester". In a social deduction context, mechanical confirmation is always a big no-no, as it, well, removes the social deduction part. In a perfect world, an emagged borg should be able to mimic not being emagged, and it should be up to the crew to intuit that they are malfunctional.

>The problem with making it impossible to confirm if a Borg is emagged at all is the fact that not all Borgs acting in rogue ways are emagged.
> Without this surefire check, perfectly fine or fixable Cyborgs are going to be unjustly destroyed and sent back to Science for a new chassis, which was already a common occurrence despite the fact anyone could check the law governing internals.
The crew should not try to figure out whether a cyborg is *emagged* or not, they should try to figure out whether they are *malfunctional* in general. There is nothing protecting ionned cyborgs from being taken down by the crew if their laws are proving to be a threat, and nothing protecting non-antagonist cyborgs behaving erratically due to them being a shitter, ignoring their laws or rules lawyering to an extreme degree. All malfunctional cyborgs should be handled in the same way.

> Additionally, the new Robotics Console makes it easier than ever to metagame emag status. You just tell Security which Borgs you've disabled or destroyed, and if the Borg is later seen still functional without being repaired then it must be emagged. Alternatively, Security can radio the RD asking to disable a Borg standing in front of them, and if it doesn't get disabled then its emagged.
This is an issue with the robotics console PR - not mine. I agree with you that emag checking in general, especially in this way, is not a good game mechanic.

**Comment by deltanedas** [comment]
validchecking with console is removed in https://github.com/space-wizards/space-station-14/pull/27876

**Comment by Zap527** [comment]
It still introduces *some* valid checking in the form of "if they dont blow up they're emagged", but it's better than having emagged cyborgs blow up.

**Comment by EpicJoston** [comment]
While I agree that emagged borgs should have the ability to pass as a not emagged borg, if someone has reasonable suspicion that a borg IS emagged, they should be able to investigate it. It's exactly like if there's reasonable suspicion that a Syndie has an implanter of some kind. Metachecking Syndies for implants is forbidden by the rules, and there's no reason why metachecking Borgs for emag in the same way can't exist like that.

To counter the Ion Storm arguement, I've had a round where an Ion Storm borg was disabling computers because they were "causing spacing to captains". I solved this issue by getting the Captain to retitle themselves to "Station Overlord", 'removing' the Captain and disabling the Ion Storm Law. However, before I could do this, I had to spend over 10 minutes convincing the entirety of Security that the borg was in fact not emagged, despite the fact they could see the panel, and was fixable. Not even one minute after I fixed the Ion Storm law and parted ways with the Borg, a mob of civilians showed up and destroyed the borg anyway, despite the fact that it was perfectly lawful and functional.

This has happened MULTIPLE TIMES in my experience and is the number one reason why I do not trust ANYONE to treat borgs with ANY form of respect. The slightest hint of suspicion that they're malfunctional and without an emag test to protect them against faulty accusations, which WILL HAPPEN, perfectly functional borgs will suffer the same fate as malfunctional ones, which is not going to be fun for the Borg player who was doing nothing wrong. The fact that Security can still metacheck Borgs with the console feeds into this issue, just disable a borg in viewing distance and if they don't get disabled they're emagged, and the borg has 0 counterplay to this.

**Comment by StarryEyes0822** [comment]
My biggest issue with this is the valid hunting mentality the moment a borg doesn't immediately comply to the exact expectation of the crew giving them a task. 

Borgs are already not considered crew, and aren't given the same respect or protection that crew is given, so they are already seen as valid to most shitters who don't get there way, now there's no way for us to protect the borgs from getting gibbed and forced to wait for a new body. 

Borgs are already pretty expensive to make as is, and with issues with getting salvage to mine (might just be a Lizard issue) and provide mats for sci will just kill the idea of people wanting to play borg or get borged, cause you're not gonna wanna play a pai, while you're stuck waiting for a new body that might not come for ignoring a shitter trying to break into the bridge.  

Like the concept is intreteresting in theory but we need to have some way to protect borgs from randomly getting gibbed cause "tider x" says the borg is emaged and borg is saying they aren't, and it just turns into sec/sci having to take sides causing more of a rift between the departments that already currently exists, cause then a potentially innocent borg gets gibbed or "tider x" is gonna grief the rest of shift cause sec/sci didn't believe them for face value.

**Comment by Zap527** [comment]
I would argue that the points being raised here are player issues. Cyborgs are not exempt from escalation rules in any way according to the rules, so destroying them without proper reason is not only failure to follow escalation but also most likely validhunting. 

I'll also paste here some of my thoughts which I put on the forums to give a little more insight as to what I think borgs should be and the background behind this change

>No matter how it winds up tuned, giving unfakeable feedback to functions which do not affect emagged cyborgs (The brain plopping out on its own, the cyborg itself exploding) goes against the principle that emagged cyborgs should be intuited over them behaving irrationally, in the same way as traitors are found.
There should not be a 100% reliable way to “test” a cyborg, as that leads to some behaviors which are unfun. You wouldn’t want an “uplink checker” in security’s possession, for instance, as syndicates would be in constant fear of being randomly checked by a potentially powergamey security officer and having their round ruined. The same principle can be applied to cyborgs, and this reasoning is the main reason behind the PR removing the law governing internals damage message.

>Security does have implanters, but not only do they not work as a “traitor test” of sorts (they just remove implants), but using them as a mock traitor test is so controversial that a rule clarification has been made disallowing implant checking in most cases.

I’m not arguing that there shouldn’t be some ways to check cyborgs, actually there already is a semi-equivalent to the implant check, which is checking the cyborg for syndicate modules. I’m just explaining my thoughts on the place emagged cyborgs should have in the game.

**Comment by EpicJoston** [comment]
Making it easier to find emagged borgs is not the reason I'm arguing against this. Finding emagged borgs is easy, as you've mentioned there's a lot of ways to already detect them outside of witnessing them violating the 1st or 2nd Law. The new Robotics Console providing a 'crew manfiest' for Borgs makes it really easy to discover illegal Borg operations and modifications without metagaming. These are both good things for the game.

The problems I'm listing are player and server culture problems. Borg abuse is absolutely real. Noone treats them with any respect, and over escalate constantly. As soon as one Borg is considered emagged, the entire crew is extra suspicious of every borg, regardless of how lawful it is. With no way to "detect" or "investigate" rogue borgs, Science cannot stop civilians from getting bats and mops and destroying the Borg because "they think it's emagged, and rogue borgs are valid", which is why the over escalation is so common.

For that reason, I cannot trust majority of the player base to intuit rogue status. These changes do not affect me personally, I've been detecting rogue borgs without screwdrivers for months. The problem is with Bernie the Chemist seeing some Ion Storm borg disable an APC because they needed to be annoying, "intuitively" figuring out that they're emagged and gibbing them with a bat. Or some tider walking up to a Borg screaming "Laws" and then yelling that they're emagged when the Borg ignores their "Law 2 request". Or security getting confirmation of an aggressive Borg with a laser module, and then killing all other borgs on sight to be remade "just to be safe". It is the nature of SS14 to walk into situations without context and make faulty deductions because of it. Players are going to make faulty deductions against Borgs constantly, and I've never personally seen any intervention from people breaking over escalation rules against Borgs.

I've been saving innocent and functional Borgs from fates like these for months, because I know how to access the right information to shut down piss poor intuition. I can first prove that they're in fact not emagged, and then figure out if its Ion Storm causing the borg to act rogue, or if someone gave it a Law 2 request to enable their criminal activity. Of all the "roleplay" interactions in the game, trying to figure out why Borgs are acting strangely is my favourite. Without any due process to properly investigate borgs, this avenue of the game will be gone because people will just kill borgs they cannot trust and wordlessly expect Science to remake them.

Thats why I'm advocating for more ways to diagnose Rogue Borgs, and if you want Science to treat rogue borgs like Security treats traitors, this absolutely needs to happen in one form or another. It gives Robotics content, it will promote interaction between Science, Silicons, and Security, as well as opening another area of the stations that traitors can sabotage to keep their illegal operations secret. It will also (hopefully) lessen the over escalation issue. As the game stands right now, I wouldn't be surprised if Borg murder rates have skyrocketed. That needs to change, because people that play borgs are players too, and I'm honestly sick and tired of how changes like this promotes violent behavior towards borgs.

**Comment by Zap527** [comment]
We've officially gone full circle: my own maldpost about getting my chassis destroyed by chemists is now being used to argue against my own PR.

Jokes aside, I am in agreement with most, if not all, of your arguments. Borg abuse is real, and they are not held on equal ground to crew members in the mind of most players. However, I don't think that PRs in general should take rulebreaks into account for their justifications. I think I have lain my reasoning behind the PR already, and while I am not disagreeing that it could have negative effects on borg treatment, I believe this is something which could, and should, be quelled by IC, OOC and admin intervention.

Once again, I'm not against the fundamental idea of a way to, potentially, "check" broken laws. What I am against is how easy it previously was to differenciate an emagged from non-emagged cyborg. I see many ways to nudge players into being more clement with cyborgs, alas the feature freeze is here and we are left arguing on a merged PR.

**Comment by EpicJoston** [comment]
I find that really funny because those are MY maldposts not YOURS!!!

Seriously speaking, PRS absolutely need to take into account the rules. If admins want to make certain things forbidden, such as building on the ATS for example, then it should absolutely be enforced by the game mechanics. Rules should only exist when trying to make something impossible actively makes the game worse. Also, if something as simple as implant checking syndies is problematic, I have no faith any amount of OOC or Admin intervention can save Borgs.

I don't want this change reverted by the way, I just really want to give Science investigative tools similar to Security that only works for Borgs. I think it would be really beneficial for antag interaction and roleplay. The only real reason I'm being this vocal about it is because of the freeze. If this change shipped with ways to analyze and edit laws, or run diagnostics checks to uncover Ion Storm Interference, or more direct ways to give Borgs Law 2 orders so you can more definitively identify when they're ignoring Law 2, I think the purpose of forcing people to use intuition to identify rogue borgs would've been successful. And these things can still be added, greatly enhancing the social deduction elements of the game.

But this change got shipped alone. Now borgs are going to be unfairly accused of being rogue for stupid reasons, and that really annoys me. I'm glad these discussions happened though, because it sounds like everyone's working towards the same goal, we're just approaching from different directions.

**Pull request merged**
