### PR TITLE
Reduce Cost of Bloodred Mags to 2TC

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Reduces the cost of bloodred magboots to 2TC in the syndicate uplink catalog.
## Why / Balance

Currently for syndicates you need a way to prevent slipping and that boils down to 1/2 items in the uplink
- No-slips: cham tech, no slipping, the stealthier of the two options
- Bloodred Magboots: Magboots, gives slowdown, is a 2 minute jetpack, no stealth capability

Currently no-slips have no downsides and are purely better for Traitors, they are cheaper, give no disadvantages, and don't make you valid. On the other side bloodred Magboots cost twice the TC, provide similar functionality to the no-slips in most situations, and make you instantly valid. Unless you're specifically planning on taking out gravity no-slips are always the better option. I don't see why the more niche of the 2 items should cost 2x the amount. This would mostly affect Traitors due to the smaller budget while slightly "nerfing" nukie agents by "removing" 2 tc from their starting equipment. The slowdown and cost are more noticeable now than ever due to the elite suit nerfs.
## Technical details

yml edits
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Bloodred Magboots are now 2TC

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
This is a nukie buff not a nerf

**Comment by Cojoke-dot** [comment]
> This is a nukie buff not a nerf

Its 2tc, at most its going to make taking out grav 8-10tc out of 200tc cheaper for the whole team. So sure, its more of a buff for nukies, but they also got a massive nerf to elite hardsuits.

**Comment by Cojoke-dot** [comment]
Failing tests from changing one number... huh...

**Comment by Killerqu00** [comment]
> Failing tests from changing one number... huh...

this test fail is not your fault i think

**Comment by metalgearsloth** [comment]
Discussed with maintainers and opting not to change the price at this time.

**Pull request closed without merging**
