### PR TITLE
Change the syndicate charge to start a timer on signal

### PR DESCRIPTION
**Pull request by SaphireLattice**
## About the PR
Made the charge start the timer countdown, rather than getting detonated instantly

Mutually exclusive with #32429 that instead changes minibomb to start the timer, but keeps C4 instant. For maximum fun, consider them non-exclusive.

## Why / Balance
Minibomb + C4 can not be dodged, predicted or counterplayed by any way other than extreme paranoia towards anyone being nearby. If the instant detonation succeeds, which depends on item dropping skills of the player and the target being in the right spot (e.g. distracted by roleplaying and typing), the target will be not just killed but completely gibbed. This shouldn't be something that any traitor can do with a minibomb after spending just extra 2 TC. At this point just give them a one-time-use throwable instagib Throngler for 8 TC. Same deal.

It affects the instant C4 strategy of nukies, but pre-cooking the C4 sounds pretty doable. Does make it less of an instant grenade though.

Alternative to this PR would be to give the minibomb way more explosive resistance, make it start a timer when damaged by an explosion, and just completely break without explosion if it gets damaged to destruction. Rather than the current behavior of deleting itself explosively.

## Technical details
Feels like shitcode, basically copy-paste of the existing `TriggerOnSignalComponent` code, but with `StartTimer` instead of `Trigger`. Unsure if I got the `EntityUid user` right for that method though. Also added new localisation strings, woo!

## Media
It's visually minimal but can attach a recording later.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Syndicate C4 now starts a countdown on signal, rather than exploding instantly.

### CODE REVIEW

**Comment by pheenty** [comment]
c4 + minibomb is basically the only reasonable way to kill a person that is always in a crowded area on highpop, cmo for example

**Comment by thebadman4662** [comment]
Rise of IEMMs?

Perhaps wardens will manage at to salvage one laser rifle more on average during generic nukie armory rush.

**Comment by ArtisticRoomba** [comment]
I've precooked C4, it's pretty doable. 

I think this change is valid enough but maybe the maintainers have a better idea for balance. I can confirm the "Hey (lad, lass), what's up?" message I type to people that come up to me as captain sometimes get rudely interrupted by a bomber jacket with a C4 and minibomb dropped at my feet. Maybe this will push people into other strategies like hypopen poisoning/radio jamming?

**Comment by SaphireLattice** [comment]
Ah shit, "Link defaults" isn't working, because it needs to be set up in `source_ports.yml` too. Guess I could just move it back to using "Trigger" port? Gonna wait for feedback I guess.

**Comment by Plykiya** [comment]
> c4 + minibomb is basically the only reasonable way to kill a person that is always in a crowded area on highpop, cmo for example

that feels like a lack of creativity or willingness, it shouldn't need to take a "instakill this person with a click of a button" to kill someone. on several stations you are completely capable of killing the CMO in front of everyone, killing everyone who retaliates, then dumping the CMO's body out the virology trash chute into space

**Comment by Cojoke-dot** [comment]
> c4 + minibomb is basically the only reasonable way to kill a person that is always in a crowded area on highpop, cmo for example

skill issue...

**Comment by pheenty** [comment]
> not every kill needs to be a perfect no-witnesses assassination

Depends on your playstile, I personally would rather skip the objective then do it loud

**Comment by ArtisticRoomba** [comment]
Also a person standing in a crowd is asking to be poisoned with a pen/shit stolen with gloves. Instead of casting the wand of instant death.

**Comment by beck-thompson** [comment]
This makes sense: If we want an instant gib bomb we should make it its own uplink item.

**Comment by SaphireLattice** [comment]
Aaand I've also figured out a relatively clean way to make the minibomb *timer* activate when it gets C4 bombed (and otherwise just gets broken)

Now the question is, do I make another, basically conflicting in idea PR, or...

**Comment by Bobylein** [comment]
> > not every kill needs to be a perfect no-witnesses assassination
> 
> Depends on your playstile, I personally would rather skip the objective then do it loud

Well bombing medbay is anything but subtle..

**Comment by pheenty** [comment]
> Well bombing medbay is anything but subtle..

By loud I mean nstantly outing me as a traitor

> I feel this would be a good change, though combining things like C4 and mini bombs should be rewarding, it still needs counterplay

Fair enough, but all the proposed methods kill the combo entirely

**Comment by SlamBamActionman** [comment]
> Fair enough, but all the proposed methods kill the combo entirely

You just need to be more creative. Glue the bombs and container and convince your target to pick it up.

And like, maybe a free instant round removal option is just not particularly engaging gameplay.

**Comment by pheenty** [comment]
> You just need to be more creative. Glue the bombs and container and convince your target to pick it up.

 I see no reason why I would pick up a container when I can just press E to look what's inside

> And like, maybe a free instant round removal option is just not particularly engaging gameplay.

Fair enough again

**Pull request merged**
