### PR TITLE
Increase lone ops TC from 40 to 60

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Created a new lone ops outfit load out that just gives them a 60 TC radio.

## Why / Balance

I've never seen a lone ops succeed... they're kind of pathetic of a threat when compared to a space dragon or a ninja. I was also recommended to do it by an admin.... maybe as a shitpost suggestion?

## Technical details

Created new 60TC uplink in the yml, created new lone ops loadout in the yml that uses the 60TC uplink. Functionally the same as the base nukie 40TC loadout besides the difference in TC.

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

**Changelog**

:cl:
- tweak: Lone operatives now start with 60TC instead of 40TC.

### CODE REVIEW

**Comment by Plykiya** [comment]
need to do a bit more... pushed a bit too early

**Comment by Plykiya** [comment]
okay, tested it, good now

**Comment by Plykiya** [comment]
well, false alarm, I tested it with addgamerule Loneops and it works just fine. Good for review I guess....

**Comment by Golinth** [comment]
Seen a lone-op win exactly once in my 1500+ hours of play, so this is a welcome change IMO. Also, fun fact, the round doesn't even end when they detonate the nuke.

**Comment by rosieposieeee** [comment]
you could give them eighty TC and i still think dont think id ever see them win tbh

good change though

**Comment by Plykiya** [comment]
> you could give them eighty TC and i still think dont think id ever see them win tbh
> 
> good change though

pitbull named syndicate assault cyborg and their nukie master armed with nothing but a welder

**Comment by Dutch-VanDerLinde** [comment]
the 60 TC uplink doesnt have the NukeOpsUplink which im pretty sure means they can buy the same things syndicate agents can, you should fix that

**Comment by Golinth** [comment]
> preventing them from getting a cyborg seems like a decent midpoint

With 60TC, the lone op can break into cap’s office, butcher Renault, and get 5 TC to afford the Borg

**Comment by Golinth** [comment]
> Let's face it - if they can manage to do that without spending a single TC - they absolutely deserve it.

I completely agree, but it’s still worth considering if the PR owner wants 0 possibility of a Borg

**Comment by Plykiya** [comment]
> > Let's face it - if they can manage to do that without spending a single TC - they absolutely deserve it.
> 
> I completely agree, but it’s still worth considering if the PR owner wants 0 possibility of a Borg

Eh, I think it's fine if the owner is required to fully stealthops to get a single borg. A single nukie borg with an unprotected owner is basically on the same level of threat as a ninja or a space dragon. Can cause a lot of death if unhandled but most of the time very easy to kill.

Fixed it so it uses the nukie shop.

**Pull request merged**
