### PR TITLE
Temperature overhaul

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- general refactoring
- added a few docs to temperature fields
- add internal temperature component which is modified by surface temperature
- cooking uses internal temperature now

should be compatible with better temp alerts since we both file scoped it :trollface:

internal temperature doesnt affect animals right now but it could in the future
would make reptiles actually realistic ish since they cant regulate temperature, they have to rely on the enivornment (air and insulation) instead of sweating and stuff

## Why / Balance
https://youtu.be/4gTMtUAAoNw

cooking things at 1000C doesnt cook them faster it just burns the outside while leaving the inside raw
you have to actually give it time to dissipate heat to the inside so everything cooks

(when food burning implemented this will actually nerf plasma fire cooking since everything would be scorched and carcinogen rich)

## Technical details
- deprecated the `HeatCapacity` field on `TemperatureComponent`, it uses `GetHeatCapacity` on the system now
- added `InternalTemperatureComponent`

## Media

cooking steak in a plasma fire, its internal temperature does not rise as quickly as surface temperature (which is close to the fire's)

https://github.com/space-wizards/space-station-14/assets/39013340/7db17769-4f83-45b2-b837-64337d5129b9

bacon spawned in space retains some heat internally (not really accurate since water evaporating would rapidly cool the insides)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no since HeatCapacity its obsoleted

**Changelog**
:cl:
- tweak: Meats now cook based on internal temperature. Don't make steak in a plasma fire unless you want to scorch the outside before the inside can even cook.

### CODE REVIEW

**Comment by deltanedas** [comment]
why did i click open :trollface:

**Comment by Partmedia** [comment]
Please do not make refactoring changes, breaking changes, and feature changes in the same PR.

**Comment by deltanedas** [comment]
that goes against the policy of bringing files you touch up to the latest standards

**Comment by Partmedia** [comment]
Please review the latest [pull request guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). You can of course bring up a file to the latest standards in one PR, and then follow on with your changes.

**Comment by deltanedas** [comment]
> You can of course bring up a file to the latest standards in one PR, and then follow on with your changes.

that would have lots of conflicts and be a huge pain to fix

**Comment by Partmedia** [comment]
> that would have lots of conflicts and be a huge pain to fix

Then make only content changes in this PR.

**Comment by deltanedas** [comment]
yes and it will still conflict because file scoping

**Comment by Partmedia** [comment]
This code doesn't compile.

**Comment by deltanedas** [comment]
@Partmedia it do

**Comment by deltanedas** [comment]
@Partmedia

**Comment by deltanedas** [comment]
@Partmedia remove do not merge :trollface:

**Comment by Partmedia** [comment]
> @Partmedia remove do not merge :trollface:

Not until checks demonstrate that this code compiles. But sorry for the delay and long wait on this.

**Comment by deltanedas** [comment]
very real

**Review by Partmedia — APPROVED** [review]
Thank you for your contribution. A few notes:

1. Of course I would have preferred the changes to HeatCapacity be split out in a separate PR. But I've reviewed your specific changes here and they look innocent enough. *Please strongly consider following the PR guidelines in future PRs.*
2. It seems to me that the data fields in `InternalTemperatureComponent` belong in `TemperatureComponent`. You admit that `InternalTemperatureComponent` does not work without `TemperatureComponent`, so why is it a separate component? It's not like any entity with `TemperatureComponent` doesn't have an internal temperature, either. In fact, you can just store the reciprocal of conductivity (thermal resistivity) and set it to zero when you want a TemperatureComponent that instantly equalizes.

I don't care enough so you have my approval. Let me know if you want to go ahead and make the suggested changes in (2) or if I should just merge.

**Comment by deltanedas** [comment]
> It seems to me that the data fields in InternalTemperatureComponent belong in TemperatureComponent. You admit that InternalTemperatureComponent does not work without TemperatureComponent, so why is it a separate component? It's not like any entity with TemperatureComponent doesn't have an internal temperature, either. In fact, you can just store the reciprocal of conductivity (thermal resistivity) and set it to zero when you want a TemperatureComponent that instantly equalizes.

when i first started i added them as fields to the temperature component but it was too messy and i made it into a separate component
also means there is less edge case handling since the fields can just be required instead of handling 0s for things

**Comment by Partmedia** [comment]
> when i first started i added them as fields to the temperature component but it was too messy and i made it into a separate component also means there is less edge case handling since the fields can just be required instead of handling 0s for things

I see. As I mentioned, storing thermal *resistivity* instead of *conductivity* allows you to avoid special-casing 0.

**Comment by Partmedia** [comment]
Turns out that I'm having an off-day. Sorry, *conductivity* as you've stored here is the way to prevent divide-by-zero's. Unless otherwise specified, I think anything with a temperature also has an internal temperature, so setting a high default conductivity is probably fine. This also avoids having to remember to TryComp both internal and external temperatures.

Ultimately as I've mentioned I'm also fine with this as-is. Are you considering a revision? If not, I'm going to merge this.

**Comment by deltanedas** [comment]
i am gaming it can be changed later :trollface:

**Comment by Partmedia** [comment]
Cook chicken to an internal temperature of 165°F.

**Pull request merged**
