### PR TITLE
Colourful curtains

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
9 new colourful curtains. Can be crafted from carpets.

## Why / Balance
More mapping stuff

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: 9 new colourful curtains. Can be crafted from carpets.

### CODE REVIEW

**Comment by CatMagic1** [comment]
fancy!!!

**Comment by beck-thompson** [comment]
Yes please those look great!

**Comment by Emisse** [comment]
can collide physics override failure

**Comment by TheShuEd** [comment]
Huh

**Comment by K-Dynamic** [comment]
Why yes, I use carpets as my curtains :trollface:

**Comment by IamVelcroboy** [comment]
These are great. Can you please add a random spawner that includes both open and closed versions as well?

**Comment by TheShuEd** [comment]
image
+fancy white

**Comment by TheShuEd** [comment]
> These are great. Can you please add a random spawner that includes both open and closed versions as well?

Maybe in the future. Not right now.

**Pull request merged**
