### PR TITLE
Added "The Throngler"

### PR DESCRIPTION
**Pull request by PoorMansDreams**
## About the PR
Added "The Throngler"

## Why / Balance
An uncraftable Admeme weapon of mass destruction. But Not as horrendous as the Debug Gibstick

## Technical details
adds another weapon under the Swords.yml and another item sprite under Melee

## Media
https://www.youtube.com/watch?v=oK06Di-aGYk

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
Added "The Throngler"

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
the inhands for this look genuinely terrible. At least do 64px inhands in a separate RSI so they can at least be held, visually.

**Comment by PoorMansDreams** [comment]
please look at only fixes inahnd sprites the most recent one [83979fe] broke everything

**Comment by PoorMansDreams** [comment]
Inhand sprites… are better?
https://github.com/space-wizards/space-station-14/assets/150595537/75a2ac49-4faf-4cff-b92e-818c5f654fc8

**Comment by PoorMansDreams** [comment]
Imagine Sprites have been updated to be a bit more bearable

**Comment by Emisse** [comment]
putting this in cargo gambling crate with astronomically low chances

**Pull request merged**
