### PR TITLE
Potato battery update + potato AI

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

This PR overhauls the potato battery:
- Makes it actually craftable.
- New sprite that is an actual potato
- Capacity heavily nerfed
- Can't fit in chargers (How would that even work?)

Along with the potato battery, there are the supercompact AI chip and the potato AI, definitely not an elaborate reference.
## Why / Balance

Potato battery:
- The sprite was ancient and quite literally didn't match up with anything else currently in the game.
- It was kind of weird that an item that is a makeshift battery isn't actually craftable, and was only available on a couple maps where it was mapped. (Given how ugly it was that might've been a good thing)
- Emo agreed that it should be craftable (https://discord.com/channels/310555209753690112/346743671787356160/1164302079716769812)

Potato AI:
- It's funny
- Allows you to get more pAIs than what was mapped originally
- Instead of 30 normal pAI's in the ghost role list, some will be potatoes, making it artificially appear more diverse :trollface: 

## Technical details

In terms of code, only added a blacklist to `ItemSlotsComponent` to be able to prevent the potato battery from being inserted into regular rechargers.
## Media

potatoss

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Potato batteries can be built by crew.
- add: New compact AI chips may be powered via potato batteries.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
not really a fan of  being able to use potatoes to bypass the cost of making positronic brains. There's obviously more of a time investment but there's a vast difference in the material cost that I don't think is made up for.

**Comment by Doru991** [comment]
Would you rather increase the material cost of the potato or change its function from posibrain to pAI?

**Comment by EmoGarbage404** [comment]
> Would you rather increase the material cost of the potato or change its function from posibrain to pAI?

probably would rather just make it a flavored PAI, tbh.

**Comment by Doru991** [comment]
Yeah I was thinking about that, though in that case I'd like to move the chip out of the lathe so it's entirely hand-craftable, any issues with that?

**Comment by forgotmyotheraccount** [comment]
> > Would you rather increase the material cost of the potato or change its function from posibrain to pAI?
> 
> probably would rather just make it a flavored PAI, tbh.

ah, so that's what the P stands for

**Comment by EmoGarbage404** [comment]
> Yeah I was thinking about that, though in that case I'd like to move the chip out of the lathe so it's entirely hand-craftable, any issues with that?

yeah that's fine.

**Comment by Doru991** [comment]
Alright I'll reorganize it all in like half an hour

**Comment by Doru991** [comment]
Done, this was one of the two implementations I had in mind anyway, and the 'pAI = potato AI' pun is funnier tbh

**Comment by JoeHammad1844** [comment]
> not really a fan of being able to use potatoes to bypass the cost of making positronic brains. There's obviously more of a time investment but there's a vast difference in the material cost that I don't think is made up for.

if you could put these in borgs it would be really funny

**Comment by Doru991** [comment]
Yeah but uhhhh balance

**Comment by JoeHammad1844** [comment]
if only people were better.. also how do yuo even make the potato (ai) chip?

**Comment by Doru991** [comment]
Just craft it with 1 steel, 1 glass, 2 wires and 2 capacitors, no dont ask how you can put that together by hand

**Comment by potato1234x** [comment]
PotatOS my beloved

**Pull request merged**
