### PR TITLE
expedition air mod

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds a mod for air mixture to expeditions

current mods:
- space (no atmosphere)
- breathable, same as before
- 5 mols nitrous oxide (dangerous) - slows you down, might knock you out eventually
- 5 mols carbon dioxide (dangerous) - poisons you a bit
- 80 mols carbon dioxide (toxic) - uhhh you dead
- 100% plasma (toxic) - uhhh you dead
- 20% oxygen 80% plasma (volatile) - if planet atmos wasnt suck, no welding allowed or future temp mod trolls you with permanent fire

the more dangerous ones are biome restricted since trees probably wouldnt survive in a plasma atmosphere

inb4 bunch of conflicts over the next few days

**Media**
mission selection showing descriptions:

caves with no air:

lavaland with poisoned air:

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: NanoTrasen has discovered new planets with dangerous atmospheres, or none at all, to send salvagers to.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
merge deez

**Comment by metalgearsloth** [comment]
I just ran a publish too.

**Comment by deltanedas** [comment]
didnt notice the funny cl

**Comment by Anzarot121** [comment]
Just throw welding in an oxygen-plasma atmosphere and watch the server crash.

**Comment by deltanedas** [comment]
ideally server would crash yes but i dont think planet air does any reactions

**Comment by Anzarot121** [comment]
> ideally server would crash yes but i dont think planet air does any reactions

I still feel like it should work. I hope they will give me a ban for a server crash, no one plays on West Europe anyway.

**Comment by deltanedas** [comment]
i outlined a better idea for planet atmos reactions in an issue

**Pull request merged**
