### PR TITLE
Replace Barratry mines near cargo with kick mines.

### PR DESCRIPTION
**Pull request by PJB3005**
Real funny map design.

# No.

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- tweak: Replaced some lethal mines in Barratry maintenance.

### CODE REVIEW

**Comment by Emisse** [comment]
spite pr closing

**Comment by Just-a-Unity-Dev** [comment]
don't kickmines kick you from the server

**Comment by deltanedas** [comment]
funny

**Comment by GoodWheatley** [comment]
wtf sovl removal

**Pull request merged**
