### PR TITLE
Paramedic Suit [RESPRITE]

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

The old paramedic sprites felt really old, were way too vibrant and compelled me to fix and improve many of the previous issues. This NEW suit encompasses a built-in gas mask look and other features like an antennae, and even a large health symbol in the middle of the chest. Paramedics rejoice!

I have updated this PR following the art director's criticism and is ready to be merged as long as no one suddenly changes their mind.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

image
image
image
image

**Changelog**

:cl: Ubaser
- tweak: Revamped the Paramedic Void Suit sprite.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
i don't think this looks any better, infact it doesn't fit the art style and is too drab

**Comment by UbaserB** [comment]
i remember hearing that the art direction of the game is to become more drab and dull, "to fit the aesthetic" or whatever words they said that day

**Comment by NancokPS2** [comment]
It looks really cool, but maybe it should have more med colors?  
Since, you know, it is a med role.

**Comment by Emisse** [comment]
i like it we will need to see art directors think

**Comment by ZeroDayDaemon** [comment]
I feel like the helmet looking like a mask but not actually being a mask is a bit meh

**Comment by UbaserB** [comment]
> I feel like the helmet looking like a mask but not actually being a mask is a bit meh

thought about myself, if i could code then i would implement that change… unless its possible through yaml actually i might check it out.

**Comment by EmoGarbage404** [comment]
IMO this sprite looks wildly out of style. The colors are a bit too desaturated and the complete lack of outlines make this look straight out of eris or smth.

**Comment by UbaserB** [comment]
Currently reworking the sprite.

**Comment by metalgearsloth** [comment]
> Currently reworking the sprite.

mark it as draft then you goob

**Comment by UbaserB** [comment]
i cant while im on mobile i have to wait like 3 hours unless you can do it for me

**Comment by JoeHammad1844** [comment]
I dont like how open the visor is now

**Pull request merged**
