### PR TITLE
Detective module (service)

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I added an Investigation Module for the Service Borg

It contains a Seclite, Forensic Scanner and a Engraved Flippo Lighter

## Why / Balance

I thought it would be cool to have a Borg Detective. This is balanced by not being any more effective than a humanoid Detective

## Media

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image(Yes I know the Sprite for the Module Icon is a bit Borked, it has been fixed)
## Breaking changes

**Changelog**

🆑 

-add: Added Investigation Module for Service Borg

### CODE REVIEW

**Comment by deltanedas** [comment]
using mspaint for spriting real

**Comment by FungiFellow** [comment]
> using mspaint for spriting real

I had to turn to GIMP :(

**Comment by Kadeo64** [comment]
> using mspaint for spriting real

don't diss mspaint it has layers now

**Comment by FungiFellow** [comment]
> the hell is the icon on the side lol?

So first version of the icon sprite didn't have a transparent background, it has since been fixed. You can see the updated version here
icon-monocle

**Comment by metalgearsloth** [comment]
Human detectives get a gun, borgs are not supposed to human harm, this isn't a good idea.

**Comment by FungiFellow** [comment]
> Human detectives get a gun, Borgs are not supposed to human harm, this isn't a good idea.

But it doesn't have a Gun

**Comment by GreyMario** [comment]
Better watch out, that seclite's chambered in magnum

Last I checked, identifying a criminal helped to reduce potential future crew harm...

**Comment by Rainbeon** [comment]
> Human detectives get a gun, borgs are not supposed to human harm, this isn't a good idea.

The gun is not vital in any way to the human detective's role and this module does not even have a gun included

**Comment by musicmanvr** [comment]
> Human detectives get a gun, borgs are not supposed to human harm, this isn't a good idea.

it includes no gun 💀

**Comment by IProduceWidgets** [comment]
Whats the lighter for? Also a more useful tool would be some way to access the LogProbeCartridge ui. Not sure how you'll do that though without a PDA / making some PDA abomination.

**Comment by FungiFellow** [comment]
> Oh this is deleted my bad. just here Lich posting from my phylactery.

I got a vague hope of it being reopened maybe

**Comment by FungiFellow** [comment]
> I got a vague hope of it being reopened maybe

If it were reopened I would need to discard and redo my commits because it's nearly 2000 commits behind

**Pull request closed without merging**
