### PR TITLE
Toggle windoors open with a click

### PR DESCRIPTION
**Pull request by themias**
## About the PR 

Clicking or activating a windoor manually will cause it to remain open instead of auto-closing.
This could be used in places like botany, kitchen, or chemistry where you often need it open longer.

Implements #10462

**Screenshots**

<video src='https://user-images.githubusercontent.com/89101928/190271109-a1c446d1-9f46-4982-b6f5-17614ce801a5.mp4'></video>

**Changelog**

:cl:
- tweak; Windoors will stay open when manually clicked or activated

### CODE REVIEW

**Comment by ElectroJr** [comment]
Didn't #11180 already do this?

**Comment by mirrorcult** [comment]
uhhhh this was already implemented

**Comment by themias** [comment]
Damn, I'm blind. Nevermind 😆

**Comment by Visne** [comment]
Sorry for not closing that issue. Still, I wonder how you managed to implement a feature that was already in the game  😆

**Pull request closed without merging**
