### PR TITLE
Emote Panel

### PR DESCRIPTION
**Pull request by DocNITE**
## About the PR
Added emote panel, what can be activate by action button (in left bottom toolbar). 
Oh, and it's require for merging(or not idk) another PR: [Radial UI](https://github.com/space-wizards/space-station-14/pull/18110)

Well, i extend existing' `EmotingComponent`. So, there you can see some emotions, what can be work if entity has `BodyEmotesComponent` or `VocalComponent`. So, if entity doesn't have one (like Vocal), emotes from that group cannot show in Radial

**Media**
image

https://github.com/space-wizards/space-station-14/assets/69177241/d1c516bb-7476-4e78-b7cb-f1e9dce35df2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by deltanedas** [comment]
please dont replace 2 for screaming it will ruin the peoples muscle memory

**Comment by PixelTheKermit** [comment]
> please dont replace 2 for screaming it will ruin the peoples muscle memory

get used to it moment

**Comment by PixelTheKermit** [comment]
also could probably remove screaming from the actions panel

**Comment by DEATHB4DEFEAT** [comment]
please remove the scream action
it has no reason to exist and is taking space

**Comment by JoeHammad1844** [comment]
> please dont replace 2 for screaming it will ruin the peoples muscle memory

agreed

**Comment by ps3moira** [comment]
I think it'd be better if there was a option in the controls menu to add custom hotkeys. For example, setting control+shift+s does @snaps.

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/pull/18110

**Pull request closed without merging**
