### PR TITLE
Add Fruit Tag to watermelon slice

### PR DESCRIPTION
**Pull request by blueDev2**
## About the PR

Add Fruit Tag to watermelon slice
## Why / Balance

Lizards should be able to eat watermelons

## Media

https://github.com/space-wizards/space-station-14/assets/89804215/964d3924-a78c-4162-ab2d-22bfc2e40839

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: blueDev2
- fix: Watermelon slices are now considered fruit

### CODE REVIEW

**Comment by slarticodefast** [comment]
There is a [cargo bounty](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Catalog/Bounties/bounties.yml) asking for 12 fruits. I think with this tag each slice would count as one. Maybe make a new FruitSlice tag and whilelist that for lizards instead?

**Comment by blueDev2** [comment]
> There is a [cargo bounty](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Catalog/Bounties/bounties.yml) asking for 12 fruits. I think with this tag each slice would count as one. Maybe make a new FruitSlice tag and whilelist that for lizards instead?

Pineapple is also sliceable and pineapple slices are also fruits.
I'm not sure if it is a problem, and if it is, I think making a sliced tag and blacklisting that on the bounty makes more sense.

**Comment by blueDev2** [comment]
Right, there is no blacklist system
I still think adding a fruitslice tag is not needed though

**Comment by slarticodefast** [comment]
The problem is that one watermelon turns into 5 slices, which each count as one fruit. So three are enough for the bounty. But you are right that the same thing is true for onions and pineapples, so it's not this PR's fault.

**Pull request merged**
