### PR TITLE
Remove fake lag in release mode

### LINKED ISSUE #10702: Mapping command should disable fake lag
## Description

Fake lag is ran on localhost and makes mapping more frustrating, and potentially is causing the mass grid spawning issue (might be a tick rate thing too?)

Running the mapping command should disable fake lag.

### PR DESCRIPTION
**Pull request by ElectroJr**
Now fake lag is only present in debug mode, which people should be using anyways when testing PRs.

Fixes #10702.

### CODE REVIEW

**Comment by mirrorcult** [comment]
tbh what if we just disabled the mapping command straight up if you aren't on release mode so this + crashes can be avoided entirely

**Comment by EmoGarbage404** [comment]
> tbh what if we just disabled the mapping command straight up if you aren't on release mode so this + crashes can be avoided entirely

If thats done, you might want to make booting up ss14 in release easier/specify how its done somewhere. A lot of mappers aren't in the technical side and might not really know what running in release mode means/how to do it.

**Comment by ElectroJr** [comment]
> tbh what if we just disabled the mapping command straight up if you aren't on release mode so this + crashes can be avoided entirely

The mapping command is still useful when testing/debugging. If you want to outright disable it, at least it should be a cvar so it can be re-enabled. without having to addd a `--force` to the command or something like that.

> If thats done, you might want to make booting up ss14 in release easier/specify how its done somewhere.

Well if they aren't currently using release mode, that's something that needs to be fixed regardless of whether or not the mapping command gets changed. Though I assumed that mappers just used local release servers & the launcher, instead of a dev env.,

**Comment by EmoGarbage404** [comment]
> Well if they aren't currently using release mode, that's something that needs to be fixed regardless of whether or not the mapping command gets changed. Though I assumed that mappers just used local release servers & the launcher, instead of a dev env.,

The mapping guide suggests using the dev environment. Additionally, while it says to use release mode, it doesn't actually say how to launch the game in release instead of debug.

**Comment by ElectroJr** [comment]
>  it doesn't actually say how to launch the game in release instead of debug.

I added a section to the docs

**Pull request merged**
