### PR TITLE
Lockers for clown, mime and NT Representative

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR

This PR adds 3 new lockers for mapping/event purposes: clown\`s and mime\`s both have Theatre access and NT representative\`s locker with Command access.

## Media

зображення

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Tunguso4ka
- add: NT found clown and mime lockers in its stockpiles.

### CODE REVIEW

**Comment by Tunguso4ka** [comment]
maybe i should add next blueshield and nt rep job with accesses and uniform for them.

**Comment by GoodWheatley** [comment]
The blueshield locker should be removed, we’re not adding that job upstream.

**Comment by lapatison** [comment]
> maybe i should add next blueshield and nt rep job with accesses and uniform for them.

FYI [previous attempt](https://github.com/space-wizards/space-station-14/pull/10336) to add the BS was unsuccessful, with relevant discussion.

**Comment by brainfood1183** [comment]
Clown locker isnt colorful enough imo

**Comment by Tunguso4ka** [comment]
> Clown locker isnt colorful enough imo

i take that sprite from ss13.

**Comment by BolloTea** [comment]
Good job 👍
Finally, NT realized what a horror they had caused with their negligence and finally returned the long-awaited lockers to us ;)

**Comment by BolloTea** [comment]
Tungusochka, I'm sorry, but I'm curious if you plan to continue transferring the scenery from 13?  Yes, I understand that this is not in this repository, but I'm just very curious

**Comment by Tunguso4ka** [comment]
>  plan to continue transferring the scenery from 13? 

Well, yes. I will try to add everything that would fit into the SS14.

> I'm just very curious

You can just ask things like that in the discord.

**Comment by KingFroozy** [comment]
> > maybe i should add next blueshield and nt rep job with accesses and uniform for them.
> 
> FYI [previous attempt](https://github.com/space-wizards/space-station-14/pull/10336) to add the BS was unsuccessful, with 
relevant discussion.

Don't think it's really relevant to this discussion, but the only way I see BS in the game is them being a paramedic for heads with just a little bit of armament, such as flash or disabler. All they should have is basic access (cargo, engi, and not atmos, salv, etc.) to departments, medical belt, flash, disabler (or the same pistol that officers spawn with), and **maybe** a portable crew monitor, that's all. This will most likely prevent BS from being a walking validhunter, and rather make them a guy, who's only purpose is to actually protect heads, and not go off seeking for antags. Everything that is not included in their starter kit and makes any sufficient threat to antags, such as tracker implants, or serious weaponary (or even a full sec belt), should be considered as powergaming, if there are no special reasons for that. Other than that, or even less threatening, BS shouldn't be in the game. Sorry, if it's too off topic.

**Pull request merged**
