### PR TITLE
Hidden door (false wall) construction

### LINKED ISSUE #2233: Fake walls
we have the technology

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
A much needed feature for any scheming crew member or antag looking for a sneak secret passage way.

Adds construction for regular walls and reinforced wall type secret doors. Look exactly the same as walls so hard to spot and follow same construction as SS13.

To build, use the construction menu, build a girder, unwrench the girder then apply more metal.

PJB mentioned it only opening on the second click but that's out of scope for me, if anyone wants to edit the door component to have a bool for second clip opening then fill your boots.

Fixes #2233
**Screenshots**

**This video shows an earlier version. It no longer has the outline and the name / description match that of a wall.**
Content Client_8ROka6oDBi

**Changelog**

:cl:
- add: Added buildable hidden doors / false walls. Check them out in the construction menu. Perfect for that hidden passageway or secret stash. To build, unwrench a girder then apply steel or plasteel.

### CODE REVIEW

**Comment by Peptide90** [comment]
Ran into an issue with this with smoothing. With smoothing on the door component can't figure out what sprite to use when open causing a crash. Without smoothing the regular wall is very out of place.

**Comment by 20kdc** [comment]
This is another one of those cases where the weirdness with icon smoothing causes trouble, I think.
What's the exact exception when you have smoothing on?

**Comment by 20kdc** [comment]
Oh! I've determined the problem.
I think the best solution here would be to put the hidden door states into the RSI of the walls.

**Comment by 20kdc** [comment]
If not that, then you could set the "default" RSI to be the normal ones for the walls, then override the RSI for the door visual layers.

**Comment by Peptide90** [comment]
> Oh! I've determined the problem. I think the best solution here would be to put the hidden door states into the RSI of the walls.

I believe I tried that as I tried that (and trashed it rather than commit due to the error). Any idea how I would I go about doing that but overriding it to the door states?

**Comment by 20kdc** [comment]
Sprite layers can also have `sprite:`, which specifies an RSI file just for that layer.

**Comment by Peptide90** [comment]
Haven't touched this in a long while so probably at risk of going derelict. Since smoothing and door are their own components and are not related to sprite component they crash when trying to go from smoothed to open. Any ideas would be appreciated.

**Review by wrexbe — CHANGES_REQUESTED** [review]
I'm not seeing a crash, but the transitioning images being different then the walls is noticeable. The reinforced wall also flickers when near the end of it's open animation. Better to just make these yourself, based on the original walls.

**Comment by Peptide90** [comment]
> I'm not seeing a crash, but the transitioning images being different then the walls is noticeable. The reinforced wall also flickers when near the end of it's open animation. Better to just make these yourself, based on the original walls.

Not sure I follow. Not sure if the version on this branch is the one that crashes as I scrapped all changes when it didn't work and went back to square one. I'll take a look now and make sure it smooths and commit it see if it crashes.

**Pull request closed without merging**
