### PR TITLE
Shiny Diamonds

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Added diamonds ore and recipe to refined diamonds. Also minor resprite.

Diamonds may appear very rarely and in small quantities on expeditions and wrecks.

so far have no use other than selling. They're worth a 500$ per diamond!
we can add new recipes after that, like the diamond drill, diamond jewerly etc
## Media

https://github.com/space-wizards/space-station-14/assets/96445749/034b547d-de05-4468-892b-507480f0a6d4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added diamonds ore!
- add: Diamonds can now be sold at a bargain price.

### CODE REVIEW

**Comment by UbaserB** [comment]
i feel like the sprite is a tad bit too small

**Comment by TheShuEd** [comment]
Just replace vault diamonds to new

**Comment by pigeonpeas** [comment]
Is there even really a point to refining them if they are worth the same amount?

**Comment by TheShuEd** [comment]
Well, the refinied diamonds have already been in the game all this time. Now they can simply be produced. And now they can be used in crafting in future PR

**Comment by K-Dynamic** [comment]
De Beers kicking and screaming as spessmen make their own diamonds:

**Review by Flareguy — CHANGES_REQUESTED** [review]
Please revert the diamond sprites or make something new. These are fairly out-of-style (they have an excessive amount of hueshifting,) and are a lot smaller and harder to identify.

If you want to modify the diamond sprites at all, I would suggest just touching up the current diamond sprites. They're not the best thing in the world, but are pretty okay and could probably work as a good jumping-off point.

**Comment by TheShuEd** [comment]
Анимация12

**Review by Flareguy — COMMENTED** [review]
My previous review still applies here, outside of the cyan coloration part (which *is* better but was still the least important part.) These are still too small and too hueshifted.

I would suggest just making the old sprite smaller overall somehow, or just leaving it unchanged if you're not sure what to do.

**Review by Flareguy — APPROVED** [review]

**Comment by lzk228** [comment]
selfmerge :trollface:

**Pull request merged**
