### PR TITLE
Rebalanced uplink explosives

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
So the last minibomb rebalance was a bit of a fiasco, and just made it worse than a grenade in every way. This makes it a utility explosive with a 10 second timer and very small, but very powerful radius. The spacing restriction was transferred to grenades. Useful for surgically destroying structures or bodies, but pretty useless against people with its 10 second timer.
**Screenshots**

minibombexplosion

New explosion radius. However, this will gib bodies (not living people) and instantly destroy substations. TC cost increased by 1 so you can only buy 2 with your starting TC to prevent too much egregious gibbing.

**Changelog**

:cl: Rane
- tweak: Minibomb radius massively reduced.
- tweak: Minibomb timer increased to 10 seconds.
- add: Minibombs have a new, distinctive timer sound.
- tweak: Minibomb will reliably destroy the tile under it, including gibbing dead bodies (but not living people.)
- tweak: Grenades can no longer space tiles.
- tweak: TC cost of uplink explosives has been adjusted based on their relative strength.

### CODE REVIEW

**Comment by mirrorcult** [comment]
with C4 also being added minibombs are in an even weirder place, not sure how i feel

**Comment by Fishfish458** [comment]
> with C4 also being added minibombs are in an even weirder place, not sure how i feel

IMO from my time playing ss13, c4 isn't really supposed to be comparable to an grenade/minibomb unless you stacked like 3 of them together and even then you'd have to get the triggers together, even then it's not supposed to gib or space floors, which I think should be the minibomb's job.

**Comment by mirrorcult** [comment]
yeah these are in a really weird state with c4 now tbh, maybe these are fine still as they can space areas and C4 cant? it feels like one of them should be removed though

**Comment by Fishfish458** [comment]
I think c4 should take another hit to it's ss13 counterpart and do 50 damage to people instead of 100 to seperate it further from a standard grenade or require it to be placed to be activated and not usable in hand.

**Comment by Elijahrane** [comment]
I think this would have decent use just for gibbing, if c4's gibbing ability is nerfed a bit. It's a decent amount of TC to gib 1 target imo

**Comment by mirrorcult** [comment]
yeah we can see how this goes then

**Pull request merged**
