### PR TITLE
Noise

### PR DESCRIPTION
**Pull request by Slubudan**
## PR About "Guten Orbit" lobby music
Pull request for addition of lobby music I made.

_I'd say it checks out, but always doublecheck._

Willhelm53 created a tutorial guide for demonstration puspose which made me able to contribute this. Very Nice.

**Changelog**

:cl: Casul
- add: Added a new lobby song, "Guten Orbit"

### CODE REVIEW

**Comment by Willhelm53** [comment]
Reviewed. No changes needed from my perspective. Good work!

**Comment by Willhelm53** [comment]
Good job fixing the merge conflict! Ironic that it was caused by the very guide you followed to get here 😂

**Review by mirrorcult — APPROVED** [review]
changes look fine but probably want discussion on whether we want this song in teh game

**Comment by Slubudan** [comment]
> changes look fine but probably want discussion on whether we want this song in teh game

It's just music, so would neither harm nor really benefit, but had no negative reactions so far. 
Choice is yours obviously.

**Comment by Willhelm53** [comment]
How come you closed this? Seemed alright to me. Maybe post the song again as a .wav or other embeddable format in #music-and-sound to solicit feedback again? Make it real easy for folks to just press play. I think people will agree it fits the tone of the game once they hear it.

**Comment by Slubudan** [comment]
> How come you closed this? Seemed alright to me. Maybe post the song again as a .wav or other embeddable format in #music-and-sound to solicit feedback again? Make it real easy for folks to just press play. I think people will agree it fits the tone of the game once they hear it.

Recently acquired new tech and a better DAW, made the track in garageband on an iphone only, which was quite limited. 
I will look to make some edits i am only now able to do, or reconstruct it inside the program from scratch. 

I want my noise to be proper music.

**Comment by Willhelm53** [comment]
You love to see it! Godspeed 🚀 

And FYI, you can keep this branch on your github and just remove/reupload the file when you're ready for it. Keep the PR closed, and reopen it when the time is right.

**Comment by Slubudan** [comment]
Problem i see here is accessability, either format, be it .wav or .mp3, cant be properly played on a phone without a download i.e. , and many use a phone to check up on discord.
Posting the soundcloud link is a possibility, but i'd have to post it too many times to get proper review and reach more people, for it gets lost fast in the channels communication. And obviously i want to avoid spamming just for the Advertisement of a mediocre ambient track

Leaving the PR closed for edit is what i wanted to do, just afteredit the files and go back to open. Good functionality of github.

**Pull request closed without merging**
