### PR TITLE
Fix rotation of attack animations when view is rotated and when users are on different grids

### LINKED ISSUE #17056: Wide-attack swing doesn't follow cursor with rotated camera
## Description

It's rotation is offset by whatever the eye rotation is.
**Reproduction**

- rotate camera
- swing weapon

### LINKED ISSUE #20995: Power attacks (right click) while riding a vehicle are not properly synced with camera rotation
## Description

Attacking with power attacks in melee while on a vehicle causes seemingly random offset to all attacks. Such attacks even break the vehicle someone is currently riding.

**Reproduction**

1. Ride a vehicle
2. attempt to power attack with a melee weapon

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by eoineoineoin**
## About the PR

Fixes #17056, fixes #20995 and another similar bug. When the player's camera isn't aligned with the grid, attack animations are played with the wrong transform. Similarly, when the player is on a different grid to the attacker and those grids have a relative rotation, the animation would be played with an incorrect rotation.

## Media

https://github.com/space-wizards/space-station-14/assets/1676295/ef495501-fc51-43aa-a397-e776d7512c39

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Does this work with multiple eyes? That was the main blocker as attached player doesn't work for it.

**Comment by eoineoineoin** [comment]
I can test - how can I add multiple eyes to a player? The bugs fixed by this PR currently affect all players, though. Not sure why the multiple eyes would be a blocker?

**Comment by metalgearsloth** [comment]
> I can test - how can I add multiple eyes to a player? The bugs fixed by this PR currently affect all players, though. Not sure why the multiple eyes would be a blocker?

Cameras, which AI gameplay is reliant upon.

**Comment by eoineoineoin** [comment]
OK, tested with cameras (just used a camera monitor computer; there is no "AI gameplay," right?) and they *are* inconsistent.

The problem is with the way the code currently works; the animation has the parent set to the weapon user, but because it doesn't want to track the user turning, it sets sprite.NoRotation=true. This flag isn't documented, but causes the animation to ignore the rotation of the view matrix (but still rotate the sprite by sprite.Rotation.) Since there can be multiple render targets with different view rotations, this strategy will never work.

Some ideas for potential solutions:

1. Set the animations parent to something else like the grid, or null.
2. Add something to apply the inverse user rotation to the animation transform.
3. Make camera render targets respect the user's camera orientation
4. Something different?

Number 1 would  be the simplest, though it would allow the animation to translate relative to the weapon user - maybe only noticeable if the user can move fast? I'm inclined to go with number 2 for correctness; I'm not aware of a component which would do this already, but it could plausibly be done within the animation track.

Number 3 would co-incidentally "fix" the inconsistency for this use-case (but not in general; it could show up again if a new way to have multiple render targets was made) but I think the fact that cameras don't respect the user's camera rotation is a bug, right?

Any preference?

**Comment by Nopey** [comment]
Hello Eoin! This bug has been annoying me in-game, so I was glad to find your PR.

> 1. Set the animations parent to something else like the grid, or null.

Using the grid as a "stationary" reference is a good idea, makes these anims behave well when on e.g. the cargo shuttle.

> 2. Add something to apply the inverse user rotation to the animation transform.

I think it is easier to let our TransformSystem do the work of calculating rotations, and worry about "calculating" (setting) the animation's position instead.

to summarize, I believe it would be best to parent the animation to the grid (when available) and use a (new?) component+system to manually, continuously copy the user's world position to the animation's.

> the fact that cameras don't respect the user's camera rotation is a bug, right?

I asked in #development on Discord, [link to post](https://discord.com/channels/310555209753690112/310555209753690112/1198437582950899723), and multiple viewports at different angles is desired behavior.

**Comment by ShadowCommander** [comment]
@eoineoineoin are you coming back to this? If not then @Nopey would you like to work on this?

**Comment by eoineoineoin** [comment]
Would love to see this fixed for sure (didn't see Nopey's comment at the time, sorry!) - don't mind if someone else picks up the pieces, but all those solutions seem a little hacky to me, and I didn't see any feedback on a nicer way to structure a solution.

**Comment by metalgearsloth** [comment]
I think I agree that the solution is updating either its rotation or position every frame to update with the user (rotation might be more performant from memory).

The issue is we want the initial rotation of the user considered but then if they rotate we don't also want to rotate it with them. This should hopefully fix it for cameras too so AI isn't gimped.

**Comment by Nopey** [comment]
Opened PR #27494, which takes the mapgrid + continuously updating position approach.

**Pull request closed without merging**
