### PR TITLE
In-hand apprasial tool sprite

### PR DESCRIPTION
**Pull request by UBlueberry**
## About the PR

The appraisal tool now has in-hand sprites, as well as a side belt sprite.
I did the adding-it-into-the-game part. @obscenelytinyshark on Discord did the sprites.

## Why / Balance

We were joking around about what a senior cargo technician would get as a reward for being a senior, and somebody threw out "golden appraisal tool". It was then that we realized the appraisal tool has no in-hand sprite... and the rest is history.

## Media

image
Belt view.

image
MK 18 for reference.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- fix: The appraisal tool now has in-hand sprites!

### CODE REVIEW

**Comment by TiniestShark** [comment]
first real spriting attempt, hoping to add to more projects considering how much joy this game has given me.

**Comment by ArtisticRoomba** [comment]
Love the sprites. Good PR.

**Comment by UBlueberry** [comment]
> first real spriting attempt, hoping to add to more projects considering how much joy this game has given me.

can't wait. :D

**Comment by chromiumboy** [comment]
Tested in-game, it looks good!

**Pull request merged**
