### PR TITLE
Remove unecessary easy pry prototypes

### PR DESCRIPTION
**Pull request by nikthechampiongr**
## About the PR

This removes unused prototypes that will probably remain unused forever and ever. 

## Why / Balance

They have simply been bugging me for being unused.

They were originally added for the purpose of allowing mappers to map them to shuttles and arrivals so people could escape them without a crowbar in #19394. This use was made redundant after #17189 was merged. Additionally #21002 made all normal airlocks pryable by hand when unpowered making these airlock prototypes completely and utterly useless. 

## Technical details

I deleted the file.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

gaming
**Changelog**

no cl no fun.

### CODE REVIEW

**Comment by lzk228** [comment]
they are used, and even they are not, you should put them in migration.yml

**Comment by nikthechampiongr** [comment]
> they are used, and even they are not, you should put them in migration.yml

I honestly did not expect them to be used at all considering how they were became redundant  roughly 2 weeks later. Ok one moment.

**Comment by lzk228** [comment]
> making these airlock prototypes completely and utterly useless.

dont they opens faster? whay extremely helpful when you have 20 seconds to escape from arrivals shuttle?

**Comment by nikthechampiongr** [comment]
> > making these airlock prototypes completely and utterly useless.
> 
> dont they opens faster? whay extremely helpful when you have 20 seconds to escape from arrivals shuttle?

Nope

**Comment by nikthechampiongr** [comment]
> > > making these airlock prototypes completely and utterly useless.
> > 
> > 
> > dont they opens faster? whay extremely helpful when you have 20 seconds to escape from arrivals shuttle?
> 
> Nope

The prying component which is on tools that can pry contains a modifier for prying. Since we don't have a prying component when prying without a tool it just puts a default modifier of 0.1f. Originally it was 1.0f but that was changed in the pr that made all doors pryable by hand when unpowered.

**Comment by nikthechampiongr** [comment]
That being said, doors can apply their own modifier which however will apply to all prying attempts. I can make the prototypes do that, but I don't think they will ever be used.

**Comment by nikthechampiongr** [comment]
The modifier for pryunpowered could also just be moved to the pryunpowered component which doors get. Again tho I don't think these will ever see actual use.

**Review by TheShuEd — APPROVED** [review]

**Pull request merged**
