### PR TITLE
Added implanter sprite

### PR DESCRIPTION
**Pull request by LinkUyx**
## About the PR

Due to the addition of a sprite to the syndicate implanter and mindshield, I decided to make a full sprite for the regular implanter as well, which still looks like a syringe. The new sprite looks more logical than the old one.
## Media

resprite

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Emisse** [comment]
looks good

**Review by Emisse — APPROVED** [review]

**Comment by Slava0135** [comment]
why copyright points to commit of a tgstation fork, not the main repo?

**Comment by Slava0135** [comment]
doesn't have correct sprite in medfab
image

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
You need to fix the icon in the lathe recipe. Just find the recipe where the implanter appears and remove the sprite field from it.

otherwise, this is gtg

**Pull request merged**
