### PR TITLE
Swept's HUD changes 

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Please comment on colors. I think these best fit the rest of the current HUD, but they could need some tweaking.

- Changed the hat, mask and ear hud icons to be more legible (I might change the ID and neck one)
- Edited the goon icons so that the actual hand/suit/etc is on top of the scan-lines
- Edited the goon icons so that clothing etc actually match with the icons
- Reset the HandsGUI to use no_letter hand icons

Current HUD can be viewed here - https://github.com/space-wizards/space-station-14/pull/3655

**Screenshots**

Bare
Content Client_2021-03-26_10-45-20
Decked out
image

**Changelog**

:cl: Swept
- tweak: Changed the HUD sprites

### CODE REVIEW

**Comment by metalgearsloth** [comment]
We're probably better off hiding the icon when something is the slot so you don't need to make all of the icon art conform to it IMO

**Comment by SweptWasTaken** [comment]
> 
> 
> We're probably better off hiding the icon when something is the slot so you don't need to make all of the icon art conform to it IMO

Do you want me to add the icon as a layer for if this eventually happens?

**Comment by SweptWasTaken** [comment]
Also don't merge i'm taking reviews and tweaking it.

**Comment by SweptWasTaken** [comment]
New changes to UI

Content Client_2021-03-28_17-55-27

UI skin I added that converts the old UI

Content Client_2021-03-28_17-19-34

**Comment by Peptide90** [comment]
Does this close #272? Since it's kind of redundant now or is that still relevant. Last commit was over a month ago by @chairbender.

**Comment by SweptWasTaken** [comment]
> 
> 
> Does this close #272? Since it's kind of redundant now or is that still relevant. Last commit was over a month ago by @chairbender.

No, this is meant to replace the current default HUD with the blue-black one. Ike said he'd be working on HUD themes soon so i've packed his and an alternate one I made into their own folders.

**Comment by SweptWasTaken** [comment]
Seeing as ike branched from this without a word to me for #3774 what do I do about this PR?

**Comment by ike709** [comment]
@SweptWasTaken You don't need to jack, your PR just needs to be merged before mine.

**Pull request merged**
