### PR TITLE
Hand-prying unpowered fire/airlocks is faster.

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This PR buffs prying open unpowered doors and airlocks to reduce the threat level of spaced rooms, as mentioned by jez in previous conversation (in the design discussion channel). Specifically, it takes half as long now.

## Why / Balance

**Changelog**

:cl: Ubaser
- tweak: Hand-prying unpowered doors and firelocks is a lot faster now.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Wait why remove the flare? I think there's one more empty tile to add the airlock wrench

**Comment by UbaserB** [comment]
> Wait why remove the flare? I think there's one more empty tile to add the airlock wrench

there's no more space, and the flare is going to fit **inside** the airlock wrench

**Comment by Hanzdegloker** [comment]
Ah yes, no more rounds start rushing to yoink a crowbar? Yes please

Will this be equal in effectiveness to a crowbar by the way? In door prying that is.

**Comment by UbaserB** [comment]
yes

**Comment by EmoGarbage404** [comment]
>This solves the problem of "are crowbars powergaming?" 

no. question solved. This is just a 1x1 crowbar but we put it inside the player inventory. why not just give people a crowbar?

**Comment by EmoGarbage404** [comment]
also can you not pry most unpowered doors with your bare hands??

**Comment by asperger-sind** [comment]
> i feel like to that point it'd be better to improve the actual baseline survivability by reducing those pry doafters and having better firelock mechanics rather than just introducing special-case tools that we just give everyone round start.

Yeah, if the item is roundstart available to everyone and 1x1, why not just integrate it into hand-prying by making hand-prying better?

We could have crowbar prying as instant but have an internal cooldown of the current doafter length so you can't pry tiles everywhere like you could 2-3 years ago, pretty sure that's also what SS13 does. While making handprying still use a doafter now with the same duration as crowbar prying doafters.

image
This was also raised in the Discord design discussion channel.

**Comment by chromiumboy** [comment]
I also agree that it would be better to make hand prying better than to add a very specialized door prying tool

**Comment by UbaserB** [comment]
ready for le review

**Comment by Partmedia** [comment]
I feel like this changes balance in the wrong direction.

I don't feel that making prying easier, especially without tools, "reduce the threat level of spaced rooms" because it makes it easier for spacing and other atmos problems to spread. Suddenly instead of one player dying, you have the whole station dying. This actually makes it more dangerous.

**Comment by asperger-sind** [comment]
Hand prying is pitifully bad right now to the degree of it being almost unusable, besides, atmos woes spreading means more volume to dissolve into and more vents/scrubbers to work with so it's not that bad.

**Comment by Partmedia** [comment]
> Hand prying is pitifully bad right now to the degree of it being almost unusable

This sounds a bit like hand-prying power-creep to me. Hand-prying exists for [a very specific purpose](https://github.com/space-wizards/space-station-14/pull/19394). Before that, you couldn't hand-pry. You're really supposed to go get a crowbar.

> atmos woes spreading means more volume to dissolve into and more vents/scrubbers to work with so it's not that bad

While there is "more volume to dissolve into" that doesn't make things better; spreading fires and spacing really does mean that one person trying to save themselves messes it up for a lot of other people.

**Comment by Partmedia** [comment]
To follow up with the submitter: the "Why/Balance" section of the PR description exists for a reason. Please fill that in with links to relevant discussions or a summary of discussions that exist, otherwise the only information I have to go off of is what people are writing in the comments.

**Comment by UbaserB** [comment]
will explain in a moment

**Comment by ps3moira** [comment]
Doesn't really make sense if people can pry open airlock doors with their bare hands really fast. What's the point of a crowbar then? People in spaced rooms should die if it's spaced without a crowbar. People should be open airlock doors if it's just unpowered.

**Comment by UbaserB** [comment]
going to close it for the feature freeze

**Pull request closed without merging**
