### PR TITLE
Super realistic nuke disk (april fools)

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

The nuclear authentication disk is now hyper-realistic and big enough so that no one will have trouble finding it if it goes missing, april fools!
## Why / Balance

i have seen too many rounds where the captain and the nukies both can't find the disk because it's too tiny and not brain scarring-ly realistic. Le April first :trollface: 
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
## Breaking changes

**Changelog**

:cl:
- tweak: The nuclear authentication disk is now disturbingly realistic, april fools!

### CODE REVIEW

**Comment by Vaaankas** [comment]
now it needs a comically large nuke

**Comment by Slava0135** [comment]
i think its a bit extreme but idea is funny overall

**Comment by potato1234x** [comment]
holy shit its huge

**Comment by metalgearsloth** [comment]
just scale the original

**Comment by K-Dynamic** [comment]
"This is a **small** item."

**Comment by moonheart08** [comment]
For game performance reasons it's probably unwise to use a 1024x1024 sprite, as it makes atlas generation more difficult. Use something smaller.

**Comment by CatMagic1** [comment]
make it a ginormous item so the cap is forced to put it down sometimes

**Comment by VasilisThePikachu** [comment]
Thank you for your PR, Unfortunately, there are some performance concerns, and putting half a megabyte into the repo is not very good.

Good luck next year.

**Pull request closed without merging**
