### PR TITLE
Pills 1984

### PR DESCRIPTION
**Pull request by freeman2651**
## About the PR

Reduces the dosage limit on pills from 50u to 20u. (Adjusts the pill volume itself, the volume of pills included in first aid kits, and the maximum dosage output for pills in the Chemmaster).

50u is an entire small beaker of chemicals. An entire glass of drink. Half of a large beaker. If we try to put a real-world equivalent on this assuming 1 unit is 10ml, pills are holding half a liter of chemicals. Realism aside, force feeding someone 50 units of any one chemical which only takes about a second is a surefire way to kill them, especially with something as easy to dispense as radium.

20u pills significantly reduces the amount of damage a single pill can cause. There is still enough room for packing multiple chemicals into a single pill and users can always take more than one pill if they need more medication (or have it administered as liquid).

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Pill dosage limit reduced to 20u from 50u.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
What’s stopping chemists from just making 2.5x as many pills?

**Comment by metalgearsloth** [comment]
> What’s stopping chemists from just making 2.5x as many pills?

Future pill entity count 1984

**Comment by deltanedas** [comment]
funny troll give DespawnTimer to pill :trollface: 
what the fuck github has trollface how

**Comment by deltanedas** [comment]
at the very least make it 25u since mouth is 50u

**Comment by freeman2651** [comment]
> What’s stopping chemists from just making 2.5x as many pills?

This isn't made to address the amount of pills chemistry makes, this is made to address the absolutely insane amount of chemicals one can stuff into a single pill and then jam into someone's bloodstream.

**Comment by GoodWheatley** [comment]
> > What’s stopping chemists from just making 2.5x as many pills?
> 
> This isn't made to address the amount of pills chemistry makes, this is made to address the absolutely insane amount of chemicals one can stuff into a single pill and then jam into someone's bloodstream.

I get the reasoning behind the PR, but this inevitably is going to increase the already extreme amount of entities chemistry produces. Chemicals in a pill already take 20 seconds to actually start metabolizing, and I don't want to start messing with pill reagent quantities until their pvs priority is adjusted or there's a material cost for making them like bottles.

**Comment by Emisse** [comment]
goodwheatley disapproves ready to merge

**Review by Emisse — APPROVED** [review]

**Review by PixelTheKermit — APPROVED** [review]
Merge and revert if it causes more problems than it solves

**Comment by GoodWheatley** [comment]
> goodwheatley disapproves ready to merge

I'm gonna sue you

**Comment by freeman2651** [comment]
> > > What’s stopping chemists from just making 2.5x as many pills?
> > 
> > 
> > This isn't made to address the amount of pills chemistry makes, this is made to address the absolutely insane amount of chemicals one can stuff into a single pill and then jam into someone's bloodstream.
> 
> I get the reasoning behind the PR, but this inevitably is going to increase the already extreme amount of entities chemistry produces. Chemicals in a pill already take 20 seconds to actually start metabolizing, and I don't want to start messing with pill reagent quantities until their pvs priority is adjusted or there's a material cost for making them like bottles.

none of these concerns touch the fact that you can jam 50 units of reagents into a single pill which is obscene at current dosage values

**Pull request merged**
