### PR TITLE
made the guitars be able to be worn on suitstorage

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

made the guitars be able to be worn on suitstorage
## Why / Balance

i wanna carry a guitar and a backpack
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Boaz1111
- add: Guitars can now be worn in the suit storage slot

### CODE REVIEW

**Comment by ps3moira** [comment]
can you send a picture with how it looks

**Comment by Boaz1111** [comment]
> can you send a picture with how it looks

it's exactly the same sprite you goober just for suit storage, not just backpack

**Comment by JIPDawg** [comment]
Where banjo

**Comment by Boaz1111** [comment]
Banjo can't be worn on the backpack slot

**Pull request merged**
