### PR TITLE
CE's locker now starts with combat gloves

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 
Does what it says on the tin.

**Screenshots**

**Changelog**

:cl:
- tweak: Due to a bureaucratic error at Central Command, the Chief Engineer's locker was incorrectly stocked with insulated gloves instead of combat gloves. This mistake has been rectified, and Chief Engineers will receive the appropriate gloves at the start of the shift.

### CODE REVIEW

**Comment by mirrorcult** [comment]
??? why

**Comment by mirrorcult** [comment]
the CE doesn't do combat, they're an engineer

**Comment by GoodWheatley** [comment]
> the CE doesn't do combat, they're an engineer

Bringing it in line with the fact that atmos techs get the gloves from their vending machine

**Comment by mirrorcult** [comment]
atmos techs should not be getting anything except insulated gloves. this is standardizing it in the wrong direction

**Comment by mirrorcult** [comment]
arguably atmos techs dont even need insulateds

**Comment by GoodWheatley** [comment]
> atmos techs should not be getting anything except insulated gloves. this is standardizing it in the wrong direction

Alright then, closing this.

**Pull request closed without merging**
