### PR TITLE
ambuzol beef

### PR DESCRIPTION
**Pull request by Emisse**
make ambuzol require zombie blood
make ambuzol blood require omnizine

rn its metagaming to create this and admins are stepping in when people make it preemptively which is stupid so just make it require zombies first and problem solved

🆑 
- tweak: Ambuzol now requires zombie blood

### CODE REVIEW

**Comment by Emisse** [comment]
idk why i named this ambuzol beef i just got off a 16 hour shift

**Comment by deltanedas** [comment]
ambuzol plus requiring omnizine will mean:
- on zombie gamemode it will be impossible to make since 3 minutes in botany hasnt made omnzine
- midround zombies it will still be easy to make since botany has made 1500u of omnizine

**Comment by UbaserB** [comment]
i feel like this is a bad idea

**Comment by Emisse** [comment]
> ambuzol plus requiring omnizine will mean:
> 
> * on zombie gamemode it will be impossible to make since 3 minutes in botany hasnt made omnzine
> * midround zombies it will still be easy to make since botany has made 1500u of omnizine

yea thats fine

**Comment by Emisse** [comment]
> i feel like this is a bad idea

no

**Comment by K-Dynamic** [comment]
On the plus side chemists will probably fuck off to hide now and wait until zombie blood is available

**Comment by arimah** [comment]
Funny, I had the exact same idea not 10 hours ago before going to bed. Great minds etc. I like this. It adds more risk to zombies, in that you would now have to kill a zombo _and_ retrieve its body before you can start treating the infection.

**Comment by LankLTE** [comment]
I swear I've been told before by admins that making this pre-emptively is fine? I don't see how it's any more metagaming than making bicar before anyone has any brute damage is. With limited chems it's probably not an issue to just let people use their resources on it if that's what they're choosing to use it on tbh- normal ambuzol was intentionally designed to not be a round-ender for zombies (since it has to be re-applied constantly and you can realistically only carry so much).

**Comment by LankLTE** [comment]
A better solution might just be to make ambuzol use more chem resources so they aren't making as much of it vs actual meds but I'll stand by the fact that making it pre-emptively isn't really something admins should be stepping in on

**Comment by Emisse** [comment]
no because we just had a giga large argument in admin chat about it

**Comment by Emisse** [comment]
also thats the wrong solution

**Comment by Emisse** [comment]
its either this solution or taking more drastic measures at removal

**Comment by LankLTE** [comment]
I don't really see why as a discussion that had to be private, but if why making this early is considered metagaming could be explained that'd probably be helpful, I think that's kind of an unreasonable thing to say imho given literally every chem is made pre-emptively (that's literally the point of them)

**Comment by Emisse** [comment]
i would agree thats unreasonable as well but changing admin policies is a nightmare

**Comment by Emisse** [comment]
as well as many admins believing that making the chem pre emptively is meta gaming

**Comment by LankLTE** [comment]
might be a discussion worth having publicly then? rules are up to admins but again, really don't see how making ambuzol early is metagaming any more than making phalanx before any genetic damage sources come up is & if game stuff is being changed around it, is worth discussing

**Comment by Admiral-Obvious-001** [comment]
I will point out that earlier today I played a partial shift on Salamander where I was the Janitor. Using a mop and bucket alone I was able to supply med with enough zombie blood to inoculate the entire station from the virus before I had to leave via cyro.

I do think this change would be a step in the right direction to making the virus more of a long term problem and further integrates botany into the solution.

**Comment by Holinka4ever** [comment]
I like these pr, because its nailing two problems with zombies gamemode:

1)Making Ambuzol like in industrial level is a bit frustrating for zero patients and zombified crew cause, having a bunch of vaccine is kinda killing all they joy from infected players.

2)Powergamers has an egoistical manner to make ambuzol to be prepared for zombie apocalypse, that would not come, or would come. This is hilarious at some points.

**Comment by deltanedas** [comment]
on mrp i rarely if ever see powergamed ambuzol, only happened when i got romerol on salv and started making vaccines ultrapowergamer style

**Comment by Hrosts** [comment]
Maybe instead of omnizine, ambusol plus should require any of the high-tier anti-poison medicines - Diphenhydramine, Ultravasculine, Stellibinin? I mean to have 3 interchangeable recipes at the same time.

This:
- Still locks the vaccine behind a harder-to-get chem
- Gives botany less of a push to hard focus omnizine, giving them more freedom (it's already used in necrosol and is very valuable on its own)
- Makes it possible, though hard, for chemistry to get ambusol plus when botany is out of order/botanists are absent.
- Kinda makes more sense recipe-wise

As it stands now, this might hurt MRP servers to solve the issue which is not present there in the first place.

**Comment by Holinka4ever** [comment]
> Ultravasculine,

You cant get ultravasculine, cause it makes from histamine, source of it was emagged booze dispenser... thats means.. uhh oh.
Ohhh... yeap.


> * Still locks the vaccine behind a harder-to-get chem

If a pep would see an obstacle, that can be walk though, they will do it, means that still gonna make ambuzol without zombees.

> * Gives botany less of a push to hard focus omnizine, giving them more freedom (it's already used in necrosol and is very valuable on its own)

Thing is, that,in chaos of zombie infection, peps will not sudenly rush to botanics to make reagent from zombie virus.

> * Makes it possible, though hard, for chemistry to get ambusol plus when botany is out of order/botanists are absent.

Same problem with zombies infection panic.

**Comment by K-Dynamic** [comment]
> I don't really see why as a discussion that had to be private, but if why making this early is considered metagaming could be explained that'd probably be helpful, I think that's kind of an unreasonable thing to say imho given literally every chem is made pre-emptively (that's literally the point of them)

My personal thoughts: It seems like making other chems before injuries occur is acceptable meta, because crewmembers are guaranteed to get injured. Compared to ambuzol which is only ever used for zombies, which occur like 20%(?) of rounds and is not guaranteed (this point is kinda moot because you could then argue phalanxamine is meta since cellular damage is rare).

The other issue is that zombies aren't an injury to heal but a full-blown antag, with their own antag rules. Thus the station technically can't prepare against them with ambuzol without evidence they exist.

Lastly, ambuzol is actually really easy to make thanks to muscle memory, and chem making ambuzol makes zombies winning much less likely.

(This is just my interpretation, and I personally still think you should able to flex on lazy initial infects by making all your meds first then ambuzol later.)

(Also, imo zombies need a rework again; command initial infect sabotages comms and chems too easily and wins, yet being a zombie with no abilities is boring.)

**Comment by deltanedas** [comment]
ambuzol just needs a harder recipe than playing with lego, so metagaming or not you cant just crank it out in 5 seconds

**Comment by Hrosts** [comment]
> You cant get ultravasculine, cause it makes from histamine, source of it was emagged booze dispenser... thats means.. uhh oh.
> Ohhh... yeap.
Ultravasculine can be found in lingzhi mushrooms, which botany can grow. Alternatively, common nettles contain histamine.

> If a pep would see an obstacle, that can be walk though, they will do it, means that still gonna make ambuzol without zombees.
I'm talking about ambusol plus, not the normal one. As it still requires ambusol as a precursor, you will need zombie blood to get the vaccine.

> Thing is, that,in chaos of zombie infection, peps will not sudenly rush to botanics to make reagent from zombie virus.
This can be also said about Emissee's requirement for omnizine. If no omnizine - no vaccine. Except in my case chemists can still make dyphenhydramine for ambusol plus.

**Comment by Holinka4ever** [comment]
> Ultravasculine can be found in lingzhi mushrooms, which botany can grow. Alternatively, common nettles contain histamine.

Ahh alright! Nothing lost forever!

> This can be also said about Emissee's requirement for omnizine. If no omnizine - no vaccine. Except in my case chemists can still make dyphenhydramine for ambusol plus.

That might work actually, cause botanics is still luck-dependece job. I am only here for standard ambuzol that asking zombie blood.

**Comment by IamVelcroboy** [comment]
If you don't want it preemptively made, have it require a reagent that can only be found in the body of a zombie. No zombies no vaccine.

**Review by GoodWheatley — APPROVED** [review]
good change, I think that ambuzol+ should be removed entirely though tbh

**Comment by UbaserB** [comment]
Ambuzol+ is simply for the scenario that if people manage to kill most of the zombies in time and the station isn’t entirely dead, they now are vaccinated against zombie diseases and have a proper chance to fight back. 
As a proposal instead of removing it entirely, what if ambuzol+ was incredibly difficult to make? So that it’d only be feasible after zombies were mostly/entirely cleared out so that any chances of it popping up in the future (like a zombie hiding in maintenance) had no chance to spread. 
OR 
You could even make it REMOVE the zombie infection from people already dead. That would probably be a better solution actually because if you make the recipe hard enough, it would only be feasible after the station recovers and it would also help with removing bring some people back into the round and also give a proper reason for moving all the corpses into medical.

After-all, the original idea was to allow for gameplay after the zombie apocalypse occurs and succeeds fighting against but also to not have anything (or at least much) related to it until it begins.

**Comment by thebadman4662** [comment]
Amb+ unzombifying dead bodies does sound nice, yeah.

People should not be getting to medical in first place if you gonna attack them as zombie and zombie vs survivor war is pretty much lost or won over cargo and/or armory as without ranged weapons survivors will have way harder time stopping zombie tide.

**Comment by IProduceWidgets** [comment]
I'm late to the party, and did not participate in the admin beef stew, but my 2c is this is a good change because
a) Making ambuzol with no threat removes most of the tension from zombies, and immediately stops any chance for zombies to snowball into a horde which they need to win.
b) Ambuzol needs to be fast to produce so its a winnable race against the clock for chemists to get it done before the zombies inevitably target chemistry.

**Pull request merged**
