### PR TITLE
Strip markdown from silicon laws before saying them

### LINKED ISSUE #28673: Ion borg laws display weirdly
## Description
When stating an ion law, it puts code along with the law

**Reproduction**
I think this can be done with any ion'd borg

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Tayrtahn**
## About the PR

Markdown tags are now stripped from the identifiers and descriptions of silicon laws when the state law buttons are used.

## Why / Balance

ion-law-markdown

Fixes #28673

## Media

Screenshot 2024-06-04 at 3 34 56 PM

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
it should manually generate a single scrambled identifier for it instead of `Law :`

**Comment by Tayrtahn** [comment]
> it should manually generate a single scrambled identifier for it instead of `Law :`

Agreed. I just need to find a way to do that that isn't jank.

**Comment by ElectroJr** [comment]
> Agreed. I just need to find a way to do that that isn't jank.

IMO its still worth merging this in the meantime, unless someone is actively working on a better fix at the moment

**Comment by Tayrtahn** [comment]
> IMO its still worth merging this in the meantime, unless someone is actively working on a better fix at the moment

The soonest I could fix this is Monday, so yeah, maybe merge as-is unless someone else wants to take a crack at it.

**Pull request merged**
