### PR TITLE
Turn arrivals into a planetmap

### PR DESCRIPTION
**Pull request by metalgearsloth**
Want to fix some other bugs first before merge.

image

(Lattice bug already fixed)

:cl:
- add: Arrivals is now stationed on a planet.

### CODE REVIEW

**Comment by lzk228** [comment]
arrivals design doesn't fit into planet

**Comment by deltanedas** [comment]
its cool also trollers might decide to get some wood and build a house on arrivals planet

**Comment by EmoGarbage404** [comment]
Considering that the planet has no resources, food, or anything else, i dont see how this is encouraging people to not go to the station.

This is literally just a nicety so that you cant sabotage atmos at arrivals

**Comment by EmoGarbage404** [comment]
> So, this change is to make it so arrivals can't be spaced. Sort of mechanically enforcing the arrivals sabotage rule, I don't mind that. There is probably a simpler way to go about it, but that discussion can be saved for later. (Edit: Mostly seeing as its only been a couple of hours, and I'd like to wait to see if others have thoughts before I keep going.)

That's what this is doing? It's introducing a mechanical change that makes it impossible to perform atmos sabotage. And, it's doing so in a way that isn't introducing logical inconsistencies into the game.

**Comment by Ilya246** [comment]
also nerfs the strat of syndies throwing out implanters at arrivals

**Comment by Subversionary** [comment]
> also nerfs the strat of syndies throwing out implanters at arrivals

They're thrown during ftl by keeping the airlock open

**Comment by mirrorcult** [comment]
whats blocking this i Desire it

**Comment by metalgearsloth** [comment]
> whats blocking this i Desire it

2 or 3 more prs fixing independent bugs let me go fix em.

**Pull request merged**
