### PR TITLE
Syndicate Flatpack Bundle

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

I created a new 12 TC bundle that includes the following:

    - id: Multitool
    - id: EmaggedAutolatheFlatpack
    - id: EmaggedProtolatheFlatpack
    - id: EmaggedCircuitImprinterFlatpack
    - id: SheetSteel
      amount: 2
    - id: SheetGlass
      amount: 2
    - id: SheetPlastic
      amount: 2

Which gives syndicates access to plenty of printable ammo, tools, or potentially weaponry but is balanced by the risky and suspicious nature of having a set up of tampered lathes somewhere that you'll have to hide. The goal of this bundle is to give non-scientists access to this kind of option at the tradeoff of not having an emag to use for other things like opening doors or lockers.

## Why / Balance

I like interacting with emagged lathes, but I don't play as a scientist, so I never have access to them myself.

## Technical details

I added flatpacked versions of the three lathes I used, and then I parented those to create the emagged versions. The bundle itself is straightforward.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot 2024-06-29 065447

**Changelog**

:cl:
- add: Added the syndicate flatpack bundle for 12 TC.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i think this is just kinda lame. Just handing syndicates any item they want at the cost of TC invalidates the social engineering aspect of the role. Being able to get lathes and materials at the cost of TC just removes the need to ever interact and engage with cargo or science.

**Comment by Plykiya** [comment]
> i think this is just kinda lame. Just handing syndicates any item they want at the cost of TC invalidates the social engineering aspect of the role. Being able to get lathes and materials at the cost of TC just removes the need to ever interact and engage with cargo or science.

pretty average description of salvage traitor gameplay already... infinite materials, every lathe, and endless borgs....

I don't think anyone who's working alone is going to buy this, and I think having something that involves working together with other traitors is kinda nice. And while you skip the social engineering aspect for the lathes and basic materials, you still don't get access to things like gold, plasma, uranium, etc, which still leaves room open to interact with those departments

**Comment by Plykiya** [comment]
> handing syndicates any item they want at the cost of TC

I mean, sure, but there also exists things like a 2TC toolbox with insuls and all the tools you would need despite it being possible to just social engineer it out of engi or scavenge it around the map, syndicate jaws of life equivalent could just be stolen from the CE or you could ask science to make you one, you can purchase soap at will rather than just finding one in a locker, you can buy an EVA suit instead of just grabbing one from a locker or asking HoP for one. I don't know, it feels like this is kind of in the same boat to  me...

**Comment by Dutch-VanDerLinde** [comment]
1. toolbox, it's valid, the insulated gloves & mask are also valid
2. jaws of life, it's also valid and better than a normal jaws
3. soap, it's better than normal soap, also valid
4. EVA suit, valid

the things in the kit aren't valid
you get free (whatever) without social engineering, at the cost of them being valid

**Comment by Plykiya** [comment]
> 1. toolbox, it's valid, the insulated gloves & mask are also valid
> 
>     2. jaws of life, it's also valid and better than a normal jaws
> 
>     3. soap, it's better than normal soap, also valid
> 
>     4. EVA suit, valid
> 
> 
> the things in the kit aren't valid you get free (whatever) without social engineering, at the cost of them being valid the things inside the kit are things you can reasonably obtain, all the items you listed are unique

the fact it's emagged is valid, the crate itself is valid
I mean, if the issue is the materials aren't valid enough, then just get rid of the materials and ask cargo for some stacks

**Comment by Dutch-VanDerLinde** [comment]
> > 1. toolbox, it's valid, the insulated gloves & mask are also valid
> >    
> >    2. jaws of life, it's also valid and better than a normal jaws
> >    3. soap, it's better than normal soap, also valid
> >    4. EVA suit, valid
> > 
> > the things in the kit aren't valid you get free (whatever) without social engineering, at the cost of them being valid the things inside the kit are things you can reasonably obtain, all the items you listed are unique
> 
> no one carries around the susbox, they take the tools out of it making the "valid" part moot. the mask and gloves are barely valid, it's maints loot and people wear it in the open
> 
> the fact it's emagged is valid, the crate itself is valid and an indicator the weapon factory exists somewhere
> 
> I mean, if the issue is the materials aren't valid enough, then just get rid of the materials and ask cargo for some stacks. This is on the same potential threat level as being discovered with a syndicate surplus bundle, and harder to hide than a surplus bundle

you can just deconstruct the crate

**Comment by ps3moira** [comment]
This feels boring. If there's ingame way of getting these things, making it so you can just instantly buy it feels cheap.

**Comment by Xeno4** [comment]
make those lathes be a blood-red version of their station counterparts or make them have some visual/description distinction from the station's lathes. That would make em valid.

**Comment by keronshb** [comment]
> i think this is just kinda lame. Just handing syndicates any item they want at the cost of TC invalidates the social engineering aspect of the role. Being able to get lathes and materials at the cost of TC just removes the need to ever interact and engage with cargo or science.

This.

Traitors do not need everything under the sun to be purchaseable and it removes the element of them stealing it or procuring it themselves.

For that, this will be closed.

**Pull request closed without merging**
