### PR TITLE
skeleton minplayers restriction

### PR DESCRIPTION
**Pull request by NakataRin**
## About the PR

Prevent ClosetSkeleton event from happening if there's not enough (10) players on the server
## Why / Balance

Skeleton players can do antag activities. Antags on extended with a small amount of people ain't fun.
## Technical details

N/A
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Skeletons can only spawn with 10 people on the server now.

### CODE REVIEW

**Comment by muburu** [comment]
but traitors is still 5 players minimum lol

**Comment by NakataRin** [comment]
> but traitors is still 5 players minimum lol

Traitors have certain objectives, they can't go massacre the entire station. Skeletons can.

**Comment by Brandon-Huu** [comment]
> > but traitors is still 5 players minimum lol
> 
> Traitors have certain objectives, they can't go massacre the entire station. Skeletons can.

Traitor's aren't required to follow any of their objectives

**Comment by NakataRin** [comment]
> > > but traitors is still 5 players minimum lol
> 
> > 
> 
> > Traitors have certain objectives, they can't go massacre the entire station. Skeletons can.
> 
> 
> 
> Traitor's aren't required to follow any of their objectives

Yet they're encouraged to by the game design. Regardless, this conversation has no purpose anymore.

**Pull request merged**
