### PR TITLE
Generic power switch component

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Also, in case you were wondering about me not updating the UI in the disposal part, that was useless because it updates on power change anyway.

**Changelog**

:cl: Rane
- add: Machines with power buttons in their UI can also be turned on or off from the context menu.

### CODE REVIEW

**Comment by PJB3005** [comment]
This kind of thing should be a visible switch in the UI, not a random verb many people may not think to check at all.

(yes, this means machine UIs should open even if the machine is depowered. They should be greyed out and obviously unusable)

**Comment by Elijahrane** [comment]
> This kind of thing should be a visible switch in the UI, not a random verb many people may not think to check at all.

It's not exclusive, the disposal unit has both

**Comment by PJB3005** [comment]
Look I obviously don't play the game, but why do people want to turn things off?

Is power actually a scarce resource with current engineering balance?

**Comment by Elijahrane** [comment]
> Look I obviously don't play the game, but why do people want to turn things off?
> Is power actually a scarce resource with current engineering balance?

Occasionally it is, during brownouts. Other machines might be somehow disruptive and unneeded at the moment (due to their noise, their effects on the local area, their effects on people.) I have some machines downstream that people do want to shut off sometimes.

And, for UI, if a machine has a UI you can add a power button there no problem. For machines without a UI (which is a good number of them), then having it on an alt verb is better than putting it on a UI (which you will also need an alt verb to open because the primary verb is probably whatever the main use of the machine is)

**Comment by PJB3005** [comment]
> turning it off makes it an excellent hiding spot

Disposals bins allow you to turn the pump off for this. Flush it once, pump off, stick item in. 

> (which is a good number of them)

Why can't they? A power button and some diagetic markings would do a great deal for the game.


> (which you will also need an alt verb to open because the primary verb is probably whatever the main use of the machine is)

I can't think of many machines that fall into this category justifiably.

**Comment by Mervill** [comment]
#11612 Anything modifying ApcPowerReceiverComponent directly will break the PowerGridCheck station event.

**Comment by Elijahrane** [comment]
>Why can't they? A power button and some diagetic markings would do a great deal for the game.

I didn't say they couldn't. Nothing about this PR says they can't, in fact it's easier now than ever for machines to put a power button in their UI. For machines without existing UI, I think an EUI that just contains a power button would be a clunkier user experience than this here, but if you want I can write one...

You can press other diegetic buttons on machine via alt menu without opening the UI (to eject, etc) so I don't see why having an alt verb option is a bad thing.

**Comment by moonheart08** [comment]
Actually build the functionality into the machines instead of just tacking it on.

**Comment by Elijahrane** [comment]
> Actually build the functionality into the machines instead of just tacking it on.

What exactly does this mean? The current wrench = power button is much more tacked on

**Comment by PJB3005** [comment]
Wrench = power is emergent behavior
Verb switch is a very low-effort feature

**Comment by Elijahrane** [comment]
> Verb switch is a very low-effort feature

Is the problem that the alt verb exists at all? Other machines have alt verbs that perform the same function as UI buttons. I agree that UIs of devices with power switches can be updated to include a power button, and this PR makes that easier to accomplish by making the behavior not duplicated.

**Comment by PJB3005** [comment]
The problem is that having the button *only* in the right-click menu means that it is very easy for people to not understand why their machine isn't receiving power/working.

**Comment by Elijahrane** [comment]
> The problem is that having the button _only_ in the right-click menu means that it is very easy for people to not understand why their machine isn't receiving power/working.

okay, we can agree to only have the verbs on machines that only have a UI button then. I've removed it from base computer and can decide on a machine-by-machine basis which machines would benefit from the effort to add the power button to the UI also.

**Comment by Elijahrane** [comment]
There we go, now power logs are no longer hardcoded to disposals...

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
