### PR TITLE
Galoshes 1984

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-galoshes slow you down
-fuck you

### CODE REVIEW

**Comment by BlitzGunner225** [comment]
Why
If someone has galoshes then arrest them and give the boots to the role that actually needs and uses it
Unless you’re a syndie then steal em all

**Comment by moonheart08** [comment]
> This is excessive and really overkill. Just make it so that blood puddles dont slip people. Theres no need to nerf such a mundane item.

In fact blood puddles are due to have this changed. Galoshes work as-is, there is no reason to nerf them.

**Comment by Peptide90** [comment]
Imo no need to nerf them, it's like insulated gloves they're a benefit of the job and sought after. Jani just needs to report them stolen.

Maybe blood puddles under a certain size don't slip and only big puddles do? And small ones dry to a decal faster idk.

**Comment by Emisse** [comment]
Honestly mixed on this one so I threw this out to start more discussion on it.

**Comment by Fishfish458** [comment]
just some context. In most ss13 servers they do actually have a SLIGHT move speed debuff, enough to where if you were being nefarious they could be a detriment. The no slip shoes are a straight up upgrade in that they have no debuff. I don't think that sec would ever really police galoshes.

**Comment by ZeroDayDaemon** [comment]
damn I actually agreed with this one

**Pull request closed without merging**
