### PR TITLE
Roburger, nanomachines, a unique medipen with their plus version (needs review)

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

This PR proposes adding a RoBurger to the game reminiscent of SS13. As we don't have a (working) virus system, I made the possibility of becoming a cyborg possible, but not guaranteed. Additionally, I created NanoMachines+ auto-injector as a last chance during a conditional revolution for the Research Director. The nanomachine injector also has a chance to be found during salvage. Additionally, a positronic brain was added to the RoBurger recipe.

Under specific conditions outlined in the technical details, nanomachines turn your character into a cyborg. Whether you can revert back depends on these conditions.

The nanomachines+ allow you to **gamble**: if you survive their effect, you'll become a cyborg forever, but in any case, you'll lose responsibility

### For contemplation
Actually, I planned to create another version of nanomachines that would result from their combination with vestin, but I'm really unsure how to balance that. I had this idea of making them a self-repairing substance, increasing hunger, persisting in the bloodstream at a steady level around one unit, and turning someone into a cyborg upon death. But after some consideration, I realized that even accounting for substance loss during bleeding, it's not fair.

## Why / Balance

I believe that a system allowing the crew to be mechanized through food is quite interesting. I'm drawn to this SS13 mechanic, and I've decided to adapt it with some modifications and additions of my own. This shouldn't disrupt the balance, as nanomachines, especially nanomachines+, are quite difficult to obtain. Additionally, nanomachines have a slowed metabolism, allowing enough time to call for help on the radio or reach medical for treatment.
During development, I made every effort to avoid bugs, duplications, and similar issues.

## Technical details

During the creation of the nanomachines code, I had to think carefully. I needed to avoid the possibility of turning just any mouse into a sentient machine. To achieve this, I replicated a couple of arguments with stomach conditions for both dwarves and humans. Yes, only they can become cyborgs from the _nanomachines_, but anyone experiencing the effects of _nanomachines+_ can embrace their fate.

I also introduced a mechanical taste, a couple of pop-ups to make people aware of the risk, and similar elements.

The medipen with nanomachines+, found either with the research director or salvagers, injects 6 nanomachines+ into the body. Then, a game of chance begins: you shout, spill your blood on the floor, and fall into shock. If your character reaches 30 nanomachines+ in their blood, they become a cyborg **forever**. The chances of success and failure seem almost equal based on my tests. Nanomachines+ metabolize at a rate of 3 per second and replicate at 6. This is triggered by the character falling to the ground. I've already checked for potential bugs; for example, during the conversion of a head into a cyborg, the revolution ends in favor of the uprising.

There are two ways to become a cyborg with nanomachines: either instantly get 20 nanomachines in your system or fall into critical condition with 5 or more nanomachines. If you're converted by 20 nanomachines, you become a cyborg with a machine interface, **forever**. Considering that the roburger has 7 nanomachines, I don't think this can be significantly abused. When robotized through the second method, if you die in cyborg form, you'll return to your human form. Also, you become a cyborg with a positronic brain instead of a human-machine interface to prevent brain duplication."

Roburger deals around 100 damage, but very slowly, akin to uranium

## Media

изображение
изображение
изображение
изображение
изображение
(I can't upload the video since it's too large even after compression...)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Adding nanomachines and nanomachines+, along with the medipen containing the latter, which can be found in the RD's locker or through salvaging!
- tweak: Roburger reworked!

### CODE REVIEW

**Comment by lzk228** [comment]
webedit ops real

**Comment by deltanedas** [comment]
https://i.makeagif.com/media/6-10-2016/Xi2W2j.gif

**Comment by CrigCrag** [comment]
i love gambling, can we instamerge

**Comment by Holinka4ever** [comment]
Guide to advanced antag trolling as scientist:

1. Choose scientist
2. Become an antag(if you didnt, repeat this step, but never skip it)
3. Research chemicals,material reclaimer and microwave with chemical grenades
4. Buy bread
5. Make roboburgers
6. Put them into material reclaimer
7. Get a nanomachines
8. Put enough nanomachines into solutions
9. Turn wide mob into machines
10. ....
11. Profit!

**Comment by icekot8** [comment]
> Guide to advanced antag trolling as scientist:
> 
>     1. Choose scientist
> 
>     2. Become an antag(if you didnt, repeat this step, but never skip it)...

for this you need 4 roboburgers... in decomposition - 4 positronic brains, the price of which is quite steep.

anyway, if we think it's unfair, I can just raise the upper robotization threshold

**Comment by icekot8** [comment]
maybe... when I get ideas for vestine nanomachines, I'll make a second attempt at merge...

**Pull request closed without merging**
