### PR TITLE
smoke grenade arming sound

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
beep beep

it work

### CODE REVIEW

**Comment by Hmeister-fake** [comment]
I prefer it being silent, i feel like beeping isn't something it should do since other grenades beep because they are electronic. Smoke grenades (from the sprite and real life smoke grenades) are completely mechanical, so i feel like maybe a loud click as you pull the safety pin from it and then a mettle rattling as you drop it would sound, cooler, be more distinctive, and also more silent which is the point of the grenade since it's meant to be sneaky sneaky.

**Comment by deltanedas** [comment]
ok well i am shit at making sounds so wyci

**Comment by Hmeister-fake** [comment]
> ok well i am shit at making sounds so wyci

How about, when i record the sound?
(or steal it off the internet)

**Comment by Hmeister-fake** [comment]
> How about, when i record the sound? (or steal it off the internet)

I have the sounds ready, but idk what file format lets me send them in a comment, any help?

**Comment by deltanedas** [comment]
just make pr add it to somewhere in audio, update attributions.yml wherever and make pr like this one but using path of new sound

**Pull request closed without merging**
