### PR TITLE
nerf diona mass

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
1-2 shove stamcrit is a joke
its still higher than human but not by much

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Just remove disarm mass contest and make it do stam damage as surprise mechanics are silly.

**Comment by deltanedas** [comment]
then cant push dwarf for being small

**Comment by Emisse** [comment]
my brother in christ it is code you can just add that feature

**Comment by Emisse** [comment]
this needs to be solved in another way

**Pull request closed without merging**
