### PR TITLE
Behonker Lobby Art

### PR DESCRIPTION
**Pull request by PoorMansDreams**
## About the PR

image

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

**Changelog**

:cl:
- add: New lobby art (of horror)

### CODE REVIEW

**Comment by MACMAN2003** [comment]
this image goes hard

**Comment by K-Dynamic** [comment]
I hope turning up the brightness and contrast in that picture reveals a fuckton more background details

**Comment by notquitehadouken** [comment]
fear

**Comment by Tayrtahn** [comment]
It's quite dark. I would either brighten it up a little bit or go all-in on the black and white horror motif and make it look like security footage (film grain, scan lines, distortion, overlays). Maybe even put it on a security monitor.

**Comment by deltanedas** [comment]
yeah some post processing would help it looks too much like a render rn

**Comment by PoorMansDreams** [comment]
ill slap some stuff onto it, I like the idea of it being chest cam footage har har

**Comment by chromiumboy** [comment]
Sorry, but if you didn't say the subject in the title, I'd have no idea of what I'm looking at. The updated version is better but still too dark to get a good read

**Comment by FairlySadPanda** [comment]
https://github.com/space-wizards/space-station-14/assets/732532/6cf8612f-fb9f-43ad-895b-80eade624599

Resolve 18 my beloved

**Comment by OctoRocket** [comment]
I can make it or even when it's small and on my phone screen... I think that the brightness is good for the effect it's going for

**Comment by PoorMansDreams** [comment]
image
changed to this

**Comment by UbaserB** [comment]
> image
> 
> changed to this

terrifying

**Comment by wafehling** [comment]
> image
> 
> changed to this

This one is quality

**Comment by Emisse** [comment]
honk man scary

**Pull request merged**
