### PR TITLE
Replace fire extinguishers in salvage lockers with a short duration jetpack

### PR DESCRIPTION
**Pull request by iaada**
## About the PR
Adds a new, shorter duration jetpack as the main space travel in salvage specialist locker fills. Also includes a small chance to get a fire extinguisher and a very small chance to get a mini jetpack instead.

## Why / Balance
Discussion of adding mini jetpacks round start #32803
Players have a lot of difficulty navigating in space with a fire extinguisher, and it can lead to some common un-fun experiences. While extinguisher travel is very funny, players get lost constantly because of the limited mobility. Round start space mobility will help new players get their bearings and old players rescue their newbies. It will also (presumably) help them to do their job and contribute to cargo better.

The refurbished jetpack has roughly 1/4th the duration of a mini jetpack. By being a noticeably shorter duration, the refurbished jetpack still encourages players to find better jetpacks through means such as HoP, salvaging, or purchasing. But because it's good enough for magnet salvage, finding a better jetpack isn't a top priority and doesn't stall the start of the shift. The shorter duration also makes it rather bad at reaching the VGroid, so progression shouldn't be largely affected.

The random locker fill is because gambling is fun. It can create small RP moments along the lines of drawing the short straw, or gifting a better jetpack to someone who needs it more. It also further pushes salvagers to find jetpack upgrades.

## Technical details
Changes to an entityTable and adds a new item.

## Media
icon3 icon icon2

image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: aada
- tweak: Replaced the fire-extinguisher in Salvager lockers with refurbished jetpacks.
- add: Salvager lockers have a chance of having a fire-extinguisher or a mini-jetpack instead of a refurbished jetpack.

### CODE REVIEW

**Comment by slarticodefast** [comment]
Well, this means salvage won't be able to do this: #31754

**Comment by iaada** [comment]
> Well, this means salvage won't be able to do this: #31754

That PR is sick, but most stations have extra fire extinguishers mapped in salvage and they're not hard to come by regardless.

**Comment by Ilya246** [comment]
this should maybe be a smaller item size

**Comment by iaada** [comment]
> this should maybe be a smaller item size

It's based off the mini jetpack which is a 4x4. I agree that visually they both feel like they should be 4x2 (it's named mini after all), but that's outside of scope.

**Comment by thebadman4662** [comment]
They are named mini because they are whitelisted on your suit slot like captain jetpack.

**Comment by august-sun** [comment]
Oh shit you actually did it! I'm curious to see the reception to this one, would love to see if it strikes the balance right!

**Comment by iaada** [comment]
I fucked it

**Pull request closed without merging**
