### PR TITLE
Implements a Dynamic Lighting System on maps.

### PR DESCRIPTION
**Pull request by DoutorWhite**
## About the PR

It implements a system into the game that dynamically changes the lighting of maps, being automatically added to planets. In practice, it can be said that it is the addition of a day and night cycle. All values ​​are contained in the component and can be adjusted freely.

## Why / Balance

It's an interesting feature aesthetically and adds more immersion when you're on planets. It's quite rational for planets to have a light cycle.

## Technical details

Adds a new component called "LightCycle", which contains some predefined values ​​and settings. These values ​​are passed to a class called "LightCycleSystem", which uses these component values ​​to calculate four waves that represent the variation of each color component as a function of time (duration of the current round). Each wave has a different behavior, and each parameter is explained in the code in relation to its exact operation. It has an intensity curve, which is responsible for darkening and brightening the map, and three color curves. These changes are made at a regular frequency, defined by a CVar. Finally, this component is automatically added and activated planets, which can also be deactivated by CVar. 

Pretty simple, overall, and solid performance. As the changes are relative to its original color, planets that are dark by nature will remain dark. The transition is very smooth and can be adjusted via Cvar, as explained. If the cycle length is not accelerated, even a low frequency like once every 10 ticks should be unnoticeable. One detail is that I'm always mentioning planets, but, in fact, this PR works with any map with the "MapLight" component, just add the "DayCycle" component, activate it, and have fun!

## Media

https://github.com/space-wizards/space-station-14/assets/68350815/e71ee7a5-4b72-41c4-9c5f-b78e1ac3fe23

Component
Component2

This is an extremely accelerated version of the cycle, and everything can be adjusted, from the color, light level, to the duration of the cycle. Nothing is hard coded, and the mechanisms to avoid fatal errors are present.

A non-accelerated version of the light cycle: https://youtu.be/gjyfwGOn5Xk

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes

There are no major changes to the original code, the only change is that the component must be added by default to planets. 

**Changelog**
:cl: 
- add: A dynamic lighting system for planets, which will now have a day and night cycle with a very smooth and gradual transition.

**Observation**

Nothing is hard-coded, as I said, this is a system that gives a lot of creative freedom to its end users. If there are reservations regarding colors, cycle length, being too light or dark, know that everything is adjustable!

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Effect looks good but needs to be clientside, not serverside.

**Comment by DoutorWhite** [comment]
> Effect looks good but needs to be clientside, not serverside.

Thanks! That means alot to me. I'll try to remove it from the server side.

**Comment by keronshb** [comment]
Exceptionally good work!

**Comment by DoutorWhite** [comment]
> Exceptionally good work!

Thanks! I moved everything to the client side, and now the code should be cleaner overall.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
MapLightComponent is still netsynced and will require an engine PR to change it.

**Comment by metalgearsloth** [comment]
Also in future best not to do development off of your master branch.

**Comment by chromiumboy** [comment]
Hi @DoutorWhite, are you coming back to this?

**Comment by DoutorWhite** [comment]
> Hi @DoutorWhite, are you coming back to this?

Possibly! I'm just taking some time.

**Comment by chromiumboy** [comment]
No worries! I'll close it for now, so it's not sitting in the review queue, you can just re-open it when you're ready to come back to it

**Pull request closed without merging**
