### PR TITLE
Corner Clothing UI

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

The clothing UI is now in the corner! Fun!

## Why / Balance

Having it directly above the hands takes up a ton of prime screen real estate for something that is really not that important most of the time.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Your clothing is now displayed in the corner rather than above the hotbar.

### CODE REVIEW

**Comment by CrigCrag** [comment]
ui change detected, brace for riots and years of bikeshedding

**Comment by LankLTE** [comment]
I'm sure there's a genuine reason, but can I ask why this can't be a toggle?

**Comment by EmoGarbage404** [comment]
> I'm sure there's a genuine reason, but can I ask why this can't be a toggle?

making it a toggle is functionally too complex for what i think is very little gain. if you look at the modifications needed to move the inventory into the corner, you'd see that it's decently non-trivial.

**Comment by metalgearsloth** [comment]
ItemStatus actually fixed again for the first time in 3 years holy shit.

**Comment by metalgearsloth** [comment]
> I'm sure there's a genuine reason, but can I ask why this can't be a toggle?

If downstreams want a cvar toggle maybe but someone would need to maintain it.

**Comment by deathride58** [comment]
Honestly a cvar toggle would be extremely clunky compared to the saner alternative of allowing all UI elements to be individually repositioned to the user's preference (which would be a pretty huge accessibility improvement)

**Comment by GreyMario** [comment]
This overlaps with the action bar, causing conflicts with lots of actions being assigned (such as with Space Ninja).

**Comment by LordEclipse** [comment]
Could have this as another thing that toggles between UI styles as well

**Comment by Hmeister-fake** [comment]
My muscle memory, oh no

**Comment by aesdfxcgvbh** [comment]
You can press I and there will be more space.  And now I have to constantly drag the cursor from one corner of the screen to another for the sake of your “convenience”.  I'm looking forward to adding tile-based movement, it's so convenient.  Give at least the opportunity to change this option in the settings.

**Comment by Emisse** [comment]
maintaining two versions is a lot more extra work than you think and not something anybody is willing to do at the moment

**Comment by he1acdvv** [comment]
Make it a toggable option to switch between this and old UI options.

**Pull request merged**
