### PR TITLE
1984 mouse AI

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Mice AI can no longer eat dead mice

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Vasilis
- fix: Fixed the issue where mice were cannibalizing fallen brethren.

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
worst PR EVER

**Comment by deltanedas** [comment]
wtf my fully automatic mousetrap with uses dead mice as bait

**Comment by LankLTE** [comment]
> wtf my fully automatic mousetrap with uses dead mice as bait

i introduce: cheese

**Comment by deltanedas** [comment]
waste of perfeclty good food

**Comment by Tunguso4ka** [comment]
> waste of perfeclty good food

well, mice are a perfectly good food too.

**Pull request merged**
