### PR TITLE
Godo Pin

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Adds a godo pin. Nothing else needs to be said.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Aleksh
- add: Added godo pin.

### CODE REVIEW

**Comment by 0x6273** [comment]
image
Please fix your editor so it respects editorconfig `insert_final_newline` for .yml files.

**Comment by 0x6273** [comment]
Size 10 seems pretty big for a pin. But if you decrease it you should probably do it for the other pins too so for consistency.

Also, why not make this obtainable as maint/salv loot?

**Comment by Alekshhh** [comment]
> Size 10 seems pretty big for a pin. But if you decrease it you should probably do it for the other pins too for consistency.
> 
> Also, why not make this obtainable as maint/salv loot?

I do not know how to make it maint/salv loot, I just followed how the other pins are made in the files. I'll try to do that

**Comment by Alekshhh** [comment]
> image Please fix your editor so it respects editorconfig `insert_final_newline` for .yml files.

how do I do this for notepad++

**Comment by 0x6273** [comment]
> I do not know how to make it maint/salv loot, I just followed how the other pins are made in the files. I'll try to do that.

You could look at the PR diff for #13472 

> as for size I think it's because of the lil "hair" godo has on the emote

By size I mean inventory, not sprite. They all take up 10 which is inherited from `ClothingNeckBase`.

**Comment by Alekshhh** [comment]
strange, I simply copied the details from the other pins. the size shouldn't have changed in that case...

**Comment by 0x6273** [comment]
> strange, I simply copied the details from the other pins. the size shouldn't have changed in that case...

The other pins are 10 also since they all inherit it from `ClothingNeckBase`. You could override it if you want
```yaml
  - type: Item
    size: 2
```


> how do I do this for notepad++

Not sure since I don't use it but maybe check if there's a setting or plugin to make it respect editorconfig?

**Comment by Alekshhh** [comment]
all issues should be resolved!

**Review by 0x6273 — APPROVED** [review]

**Comment by metalgearsloth** [comment]
shouldn't this credit the original art?

**Comment by Alekshhh** [comment]
> shouldn't this credit the original art?

if you can tell me who made the original godo I can credit it appropriately

**Comment by Alekshhh** [comment]
kind of the best I can do without info

**Comment by AJCM-git** [comment]
We cant merge this without crediting the original author, you should either find them or make a sprite based on this

**Comment by Alekshhh** [comment]
can't be godo and do crime why live

**Comment by Alekshhh** [comment]
I will close it as having copyright issues is not worth a silly little pin, but if anyone has pin ideas lemme know

**Pull request closed without merging**
