### PR TITLE
revamp meteors

### PR DESCRIPTION
**Pull request by HolySSSS**
## About the PR
Less meteors. I s'pose I'll go on space dusty road..

## Why / Balance
The impact of each meteor swarm is powerful, let's go easier on engis.
I can change the frequency of meteors as well, but I don't know how the weights exactly work right now.

## Technical details
This changes the chance of each meteor spawn in each meteor category spawn.
This also changes the frequency of each meteor swarm.

TO BE:
Small: 85% Small, 15% Medium
Medium: 35% Small, 60% Medium, 5% Large
Large: 30% Small, 40% Medium, 30% Large
Frequency: 22.5 minutes to 40 minutes

AS IS:
Small: 70%, 30% Medium
Medium: 30% Small, 60% Medium, 10% Large
Large: 20% Small, 40% Medium, 40% Large
Frequency: 7.5 minutes to 12.5 minutes

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Each meteor swarm got less meteors now.
- tweak: The meteor swarms appear rarer.

### CODE REVIEW

**Comment by slarticodefast** [comment]
Yes, please. The meteors actually destroying stuff is a nice change, but most rounds currently end by everyone suffocating, even if engineering is non-stop fixing stuff. This is especially bad on servers with lots of new players. The frequency should be lowered as well in my opinion.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
these aren't numerical amounts for how many meteors are spawned. These are just weighted probabilities. you didn't even nerf anything: you actually buffed the likelihood of larger meteors in both the medium and large swarm.

**Comment by HolySSSS** [comment]
Thanks for checkin', gonna look and fix it.

**Comment by EmoGarbage404** [comment]
Youd be better off just changing the cvars for the frequency since that has been the primary complaint.

**Comment by HolySSSS** [comment]
Requested changes done

**Comment by HolySSSS** [comment]
Closing, #29194 got merged.

**Pull request closed without merging**
