### PR TITLE
Fix PA particles

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

PA particles went right through players. LAME!

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Particles from the Particle Accelerator once again collide with players. Be careful, engineers!

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Does this apply to decelerators too?

**Comment by mirrorcult** [comment]
yes

**Comment by deltanedas** [comment]
decels shot through walls before do they still do it now

**Comment by EmoGarbage404** [comment]
Yeah

**Comment by deltanedas** [comment]
blessed

**Pull request merged**
