### PR TITLE
medical lockers no longer have belts in them.

### LINKED ISSUE #31469: Medical belts in doctor's lockers start empty?
## Description

I mean, security has dozens of fully loaded secbelts in every locker, I don't know if this is intended or unintended

**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
Removed the empty belts from medical lockers. Empty belts are now in the medidrobe.

## Why / Balance
fixes #31469 

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: medibelts are found in the medidrobe instead of in lockers.

### CODE REVIEW

**Comment by Plykiya** [comment]
So, from a balance perspective, I don't think it really changes that much. The same way that there's no reasonable way sec is using an extra dozen batons and cuffs, med having these extra topicals is about the equivalent of cargo just giving med one crate of materials.

On the other hand, it gives antags more incentives to try and break into med to steal a belt when they're wanted and can't freely walk into the med

**Comment by Cojoke-dot** [comment]
How many lockers normally spawn in station? Just off the top of my head I wanna say Marathon has 4 in its backroom… so uh… 8 or so brute packs and ointment, about one or two extra vends of those I think?

**Comment by slarticodefast** [comment]
Since this would add quite a lot of topicals to the round start equipment medical has available, could you remove the belt from the locker and put a few empty ones into the medidrobe instead? The chemdrobe for example already has a few in it as well.

**Comment by Moomoobeef** [comment]
this PR now does something entirely different than what it originally set out to do :/ still fixes #31469 though
I'll edit the PR title/description to fit

**Comment by Moomoobeef** [comment]
while this does TECHNICALLY solve the issue, I can see the issue "medical belts in **medidrobe** start empty" being made for exactly the same reason. So at the end of the day, is this PR even worth it at all?

**Comment by slarticodefast** [comment]
The idea behind the decision was that clothing closets and drobes should only contain clothing, but not tools or medical supplies. It is a little inconsistent right now how it's handled everywhere else. Thank you for adjusting this.

**Pull request merged**
