### PR TITLE
Nerf the elite hardsuit

### PR DESCRIPTION
**Pull request by nikthechampiongr**
## About the PR

This pr nerfs the elite hardsuit by reducing its sprint speed by 10% and increasing its price by 2 tc. The Nukie commander hardsuit remains unaffected. 

## Why / Balance

The Elite hardsuit has taken a foothold as the "best" purchase for most any combat antagonist plan. 
Prevalence of purchase has brought attention to its large balancing issues. It is a no slowdown hardsuit which can only be compared with the nukie commander hardsuit which is a special item which can only exist at most once per round. It additionally offers an extremely good deal for the protection it offers, making you effectively immune to laser guns while protecting you from all the other common damage sources.

## Technical details

Yaml changes my beloved.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Elite Syndicate hardsuit is now slightly slower.
- tweak: The Elite Syndicate hardsuit now costs 12 Telecrystals.

### CODE REVIEW

**Comment by ARMOKS** [comment]
It has 40% pierce and now costs as much as a Jugg suit? On top of being slower?

**Comment by EmoGarbage404** [comment]
i mean the real nutty part is the 80% heat resist, not the speed. Its niche is intended to be fire damage and such, not just all lasers. Having such a blatant counter against lasers is always going to be busted since lasers as a majority of crew armaments during nukeops.

**Comment by nikthechampiongr** [comment]
> It has 40% pierce and now costs as much as a Jugg suit? On top of being slower?

A jug suit slows you down by 35%

**Comment by deltanedas** [comment]
>  reducing its sprint speed by 10%

even less people will buy it, just nerf the burn resistance since its fireproof it doesnt need to be laserproof

**Comment by ARMOKS** [comment]
If nukies were to start with 50TC and no suit so they could choose which suit to buy this would be alright, but is this really worth 30% of a nukies entire budget?

**Comment by ARMOKS** [comment]
> > It has 40% pierce and now costs as much as a Jugg suit? On top of being slower?
> 
> A jug suit slows you down by 35%

Yeah the whole point of buying the elite suit IMO is the extra 10% speed, its the single most important factor in combat

**Comment by nikthechampiongr** [comment]
> i mean the real nutty part is the 80% heat resist, not the speed. Its niche is intended to be fire damage and such, not just all lasers. Having such a blatant counter against lasers is always going to be busted since lasers as a majority of crew armaments during nukeops.

would you like the speed nerf to be replaced with a nerf to the heat resistance? Also you wish this to affect the nukie commander suit as well? Since that is when nuke ops would be involved.

**Comment by ARMOKS** [comment]
> > reducing its sprint speed by 10%
> 
> even less people will buy it, just nerf the burn resistance since its fireproof it doesnt need to be laserproof

Fire is not prominent at all in nukie combat

**Comment by deepdarkdepths** [comment]
> > > reducing its sprint speed by 10%
> > 
> > 
> > even less people will buy it, just nerf the burn resistance since its fireproof it doesnt need to be laserproof
> 
> Fire is not prominent at all in nukie combat

Chem and nukie agent making fire blasters:

**Comment by nikthechampiongr** [comment]
> If nukies were to start with 50TC and no suit so they could choose which suit to buy this would be alright, but is this really worth 30% of a nukies entire budget?

Yes actually because the entire team should not be buying it even without the nerf, the default operative jumpsuit gives a 50% decrease to everything. Getting the elite hardsuit specializes you with heat resistance and a higher speed.

**Comment by Dutch-VanDerLinde** [comment]
in my opinion, the elite suit is a sidegrade for operatives that want to sabotage more, giving more fire/heat and explosion resistance at the cost of brute resistance, if the laser resistance is that much of a problem then just decrease it instead of increasing the price

**Comment by ARMOKS** [comment]
> > > > reducing its sprint speed by 10%
> > > 
> > > 
> > > even less people will buy it, just nerf the burn resistance since its fireproof it doesnt need to be laserproof
> > 
> > 
> > Fire is not prominent at all in nukie combat
> 
> Chem and nukie agent making fire blasters:

I have gone against this a total of one time in all my nukie rounds, even if it happened youre more than likely in a spaced room as a nukie so it goes out right away

**Comment by ninruB** [comment]
"taken foothold as the best [loud] hardsuit" by whose decree? First time hearing this take, I personally think it's not a very good purchase.

I don't think this change is warranted, this takes out the item's _niche_ of being the fast (faster by 10%, which is not that big of a problem) hardsuit, while making the opportunity cost high enough to a degree where the cost alone might make the item extremely situational, which is pretty bad for a valid-salad hardsuit.

A cost of 10TC already cuts your TC in half for traitors while 12TC starts to invalidate more loadouts than it should, it is by no means the "best" option outside of specific edgecases which aren't problematic enough to warrant a nerf.
What can you get for 8TC that completes your loadout after you've gotten an elite suit?

The current "hit armory then cargo" staple strategy almost completely invalidates lasers from a non-warops nukies round, you're not taking a lot of heat damage from lasers and most other heat damage is from fire, while you have access to spacing in near-unlimited quantities which makes it very unlikely.

If anything, keep the price, heatres and no slowdown intact and double down on the item's niche instead by stripping away more non-heat resistances.

**Comment by ChineseRansomware** [comment]
> "taken foothold as the best [loud] hardsuit" by whose decree? First time hearing this take, I personally think it's not a very good purchase.

Its piss easy to call elite/commander hardsuits the "best" because EVA suit balancing has always been rigged towards either making you a sitting duck or give meme resistances.
And, frankly, you know how and why balance changes like these happen on here :trollface:

You're not meant to lose a 1v1 with an elite suit. You're not meant to win a 1v5 with an elite suit.

**Comment by Golinth** [comment]
> > > It has 40% pierce and now costs as much as a Jugg suit? On top of being slower?
> > 
> > 
> > A jug suit slows you down by 35%
> 
> Yeah the whole point of buying the elite suit IMO is the extra 10% speed, its the single most important factor in combat

Absolutely this. It’s to the point where I will buy the backpack because the speed decrease from the duffle is too much. Speed is king here, and anything that nerfs it is an immediate no go. It’s why the CE’s shoes are so prized.

**Comment by Golinth** [comment]
> i mean the real nutty part is the 80% heat resist, not the speed. Its niche is intended to be fire damage and such, not just all lasers. Having such a blatant counter against lasers is always going to be busted since lasers as a majority of crew armaments during nukeops.

For 8 TC you get an e-shield, the 100% counter to all lasers

**Comment by Hmeister-real** [comment]
I literally only buy it so i can speed-op with it and a syndie backpack and run in with melee, i will never buy it again if it has a slowdown.

**Comment by TurboTrackerss14** [comment]
1) Why not edit the armor/resistance values. 

As stated in above comments, the elite suit niche is more as the anti heat/laser armor than anything else. 
The movespeed while related to this has pushed its niche instead to be the "combat generalist" hardsuit due to movespeed being so pivotal for our current combat style. (stunmeta blah blah) 

2) Why change the TC price 

While 50% of your TC as a traitor is a big spend, it only locks you out of the bundle purchases. Small arms and melee weapons are still just as purchasable as before, with the loss of 1-2 magazines.
The price additionally hits Nukies. Where it is not an uncommon occurrence to see EVERY nukie have this purchased, showing that it very much overshadows the normal Blood-red hardsuit to the point of them being willing to ditch their free hardsuit for said upgrade.

>Why not just push it further into the niche and reduce the non-heat armor values down

Personally I wouldn't be opposed to this but the movespeed was the glaring issue with how viable it is currently. You can't have your cake and eat it. Armor or movespeed, one has to go. My personal push is for movespeed, but ofcourse if an armor nerf PR comes up that gives a reasonable level of nerf. It would get my thumbs up too.

**Comment by vorkathbruh** [comment]
> > i mean the real nutty part is the 80% heat resist, not the speed. Its niche is intended to be fire damage and such, not just all lasers. Having such a blatant counter against lasers is always going to be busted since lasers as a majority of crew armaments during nukeops.
> 
> For 8 TC (4TC less than this proposed nerf) you get an e-shield, the 100% counter to all lasers

takes up hand slot though in the age of Gun Wielding

**Comment by Brandon-Huu** [comment]
Anyone else watch the littenhead video?

**Comment by whateverusername0** [comment]
instead of nerfing major antagonists how about buffing the crew?

**Comment by Emisse** [comment]
that is literally just power creep

**Comment by nikthechampiongr** [comment]
> why was this merged do we remove esword too because its popular

 :trollface:

**Comment by ninruB** [comment]
> why was this merged do we remove esword too because its popular

no it gets buffed instead because the popular opinion claims its underpowered :trollface:

**Comment by whateverusername0** [comment]
image

the people have decided. we're merging it

**Pull request merged**
