### PR TITLE
Adds recipe for Smile the Slime

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Adds a recipe for Smile the Slime

## Why / Balance
Seemed very sciency to me. Like a more engaging way to obtain your science pet.
I'm def open to feedback for recipe balance and whatnot.
I considered making it a generic slime as opposed to "Smile" but...more work I guess. Figured I'd wait to see what people think of it how it is. 

## Technical details
Might want to remove map spawns 🤷‍♂️?

## Media
n/a

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**
:cl: Velcroboy
- add: Added science! Smile the Slime can be created in the lab through a mixture of reagents.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
> generic friendly slime would be cool instead of smile

Probably does make more sense. But my initial thought was, "where did Smile come from? How did he get here?" Science! Was the answer, if course. 

I'm off to work right now. So, I'll just wait and see if there other thoughts on it when I get back.

**Comment by Graded5** [comment]
recipe should include omnizine due to Smile dropping omni when butchered

**Comment by UbaserB** [comment]
I would limit it to one smile per round, and require something special so that only science can create it. This is just a suggestion, but it would fix a bunch of issues.
What if RD has smile's core, then you need to create a "slime casing" using chemistry, and then you can craft smile using smile's core + casing. This would also give rise to the potential to create infinite friendly slimes (of several varieties perhaps?) or even traitor slimes.. oh boy my ideas go wild.

**Comment by KingOnBudget** [comment]
infinite omnizine farm

**Comment by slarticodefast** [comment]
Are you coming back to this? If you want I can open a maintainer discussion thread for this first to get conceptual approval before you make any changes.

**Comment by IamVelcroboy** [comment]
> Are you coming back to this? If you want I can open a maintainer discussion thread for this first to get conceptual approval before you make any changes.

Yes, I was planning on it when I'm not quite so busy IRL. My plan was to add a unique brain that can either be mapped in or added to RD locker.

**Comment by SlamBamActionman** [comment]
Hello! Thank you for your contribution! This was discussed a bit more internally and as-is the PR allowing multiple Smile the Slime isn't desirable, as it adds potentially unlimited Smile ghost roles and the recipe even makes it possible for non-Sci to make it. 

Having a slime core or making generic slimes has more support from maintainers (think of a parallel to how botany can make killer tomatoes), though an exact implementation hasn't been agreed upon. 

Since there hasn't been any update to this PR since the original commit I will be closing it for now. Let a maintainer know if you want it reopened, or submit a new PR with a new design. Thanks!

**Comment by IamVelcroboy** [comment]
Haha, I wad literally planning to work on this tomorrow. 😄 No worries though. I'll open new PR when it's ready.

**Pull request closed without merging**
