### PR TITLE
Add ERT time stats

### PR DESCRIPTION
**Pull request by poeMota**
## About the PR

Now time played on ERT roles and midround borgs will be displayed in game stats.

## Why / Balance

executed a TODO from GhostRoleComponent.

## Technical details

Added a “job” field to GhostRoleComponent that allows the JobComponent to be overwritten when taking a ghost role.

## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Now the time played on ERT roles and midround borgs will be saved to the player's stats

### CODE REVIEW

**Review by TheShuEd — APPROVED** [review]

**Comment by Emisse** [comment]
would it be possible to add this to midround borgs

**Comment by poeMota** [comment]
> would it be possible to add this to midround borgs

This also requires a slight modification to ToggleableGhostRole, I can do that if needed

**Comment by poeMota** [comment]
so I did it

**Comment by lzk228** [comment]
`>`take role of positronic brain
`>`the scientists says "we don't have materials for now so you should wait for the body"
`>`wait till the round ends
`>`profit of farming hours :trollface:

**Comment by poeMota** [comment]
> `>`take role of positronic brain `>`the scientists says "we don't have materials for now so you should wait for the body" `>`wait till the round ends `>`profit of farming hours :trollface:

Well in this way you can also just farm hours on the borg afk

**Pull request merged**
