### PR TITLE
New Minor Antag: Vampire

### PR DESCRIPTION
**Pull request by Rainfey**
## About the PR
Design doc https://github.com/space-wizards/docs/pull/131
Add a new vampire minior antag
I'm requesting feedback on tweaking of mechanics, ideas for abilities and insight on potential balance issues

### Vampire Traits
- Pressure Immune
- Immune to cold temperatures (but not heat)
- Cannot rot
- Will heal (even from death) when placed inside a closed Coffin (Rate of 2 per second, burn at 1 per second)
- New abilities are gained for possessing certain amounts of blood
- Being exposed to starlight burns the vampire 
(ISSUE: Currently im checking if the tile is empty, any better way of checking for space?)
- Cannot digest normal foods, must subsist on blood (Still able to consume Pills)
- Drinking blood will heal the vampire by 3 brute and 1.25 burn (reused bloodsucker metabolism)
- Will be burned by holy water (splash and ingestion/injecton) and the bible
- Attempting to pick up the bible will severely burn and stun the foolish vampire
- (Not Done) Abilities are blocked when in the chapel
- (Not Done) Draining the vampire of blood will prevent them from using abilities (and being teleported to their coffin if you are fast enough)
- Increased melee damage, 10 slash per hit

### Vampire Abilities
| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Toggle Fangs | Starting Ability | 0 blood | 0 seconds |

The vampire extends their fangs so they may drink from their victim (by interacting with them at close range)
While drinking blood others will hear the drinking sound and a blood pool will begin to form around the victim (messy eaters)
Blood can be drank from any humanoid - living or dead, but not those who have rotted
A uninjured body provides 300u of blood, but the vampire is limited by their stomach capacity
Drinking the blood of the Chaplain will instead burn the Vampire.
Others at close range will be able to see a vampires fangs (when examining) 

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Glare | Starting Ability | 0 blood | 60 seconds |

The vampire releases a powerful flash from their eyes, stunning any victim without eye protection for 10 seconds
This has no effect on the Chaplain

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Hypnotise | Starting Ability | 0 Blood | 60 seconds |

The vampire stares into its victims eyes for 5 seconds, forcing them to sleep for 60 seconds.
Has no effect on the chaplain.

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
|  | Stellar Weakness | Starting Ability |  |  |

Vampires are burnt by the light of the sun, or to be specific - the few billion stars they are exposed to outside the station.

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Polymorph: Bat | 30 blood | 20 blood | 30 seconds |

The vampire changes into the form of a bat
(QUESTION: Should this bat be able to go through doors like mice? SS13 implementations of this allow vent crawling)

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Blood Steal | 30 blood | 20 blood | 60 seconds |

The vampire forcibly extracts blood from all humanoids in the area (3 tiles)
Has no effect on the chaplain.

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Chiropteran Screech | 50 Blood | 10 Blood | 60 seconds |

The vampire shrieks and stuns nearby (3 tiles) humanoids for 3 seconds
(QUESTION: Should this include an EMP effect to block radios?)

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
|  | Deaths Embrace | 150 Blood | 100 Blood | 0 seconds |

Upon death if the vampire has enough blood stored - their body will be teleported to the last coffin they slept in.

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
| Image | Cloak of Darkness | 300 Blood | 20 Blood | 10 seconds |

The vampire activates a stealth, similar to that of a ninja.

| Icon  | Name | Unlock Requirement | Use Cost | Cooldown |
| ----- | ------- | ---------------------- | ---------- | ----------- |
|  | Full Potential | 600 Blood |  |  |

The vampire reaches their full potential, rendering them immune to Holy damage.
May the Gods have mercy upon your souls, _para bellum_

### Other ideas for abilities
Summoning bat minions
Private vampire radio channel (intrinsic radio?)
Converting the dead into thralls
Regeneration - Passive healing
Direct attack methods - Some kind of necrotic touch ability

Provisions are coded for players being able to choose their bloodline, which can alter when abilities are unlocked, their costs and cooldowns - along with other parameters.
I havent implemented the above yet (i suck at UI's) and so all vampires get the 'Default' bloodline.

### CODE REVIEW

**Comment by mirrorcult** [comment]
this will need a doc at https://github.com/space-wizards/docs

**Comment by Rainfey** [comment]
Understood, once details are finalized i'll do a writeup.

**Comment by LordEclipse** [comment]
You couod have the abilities unlocked through an antag store as they drain blood from their victims

**Comment by icekot8** [comment]
I like this PR, actually. But I think you could avoid the 3 second stan by wearing earplugs or maybe headphones? That should give debuffs. But 9 seconds of stasis for a humanoid for a corpse.... That doesn't seem right to me, at least it shouldn't affect the chaplain since he's above that.
The rest of the abilities are actually pretty well balanced and will provide gameplay for both the antagonist and the chaplain.

**Comment by keronshb** [comment]
I have a shop PR in the works that will give it action upgrade functionality. Once #24005 is merged, I'll be doing that PR soon after. Not sure if Vampire will need this, but just giving you a heads up that it could be something you'd be using.

**Comment by Rainfey** [comment]
> > QUESTION: Should this bat be able to go through doors like mice? SS13 implementations of this allow vent crawling
> 
> No. Being a flyer is a huge benefit already (slipping immunity, launching resistance via `CanMoveInAir`). `SmallMob` collision layer is **very** powerful and should be used with scrutiny. Regular bats don't have it for a reason: `SmallMob` + flyer = a nasty combo. If there is a design direction to give vampires that ability, make that a separate "transform into a rat" or something that's appropriately more costly. This way at least you can have _either_ flying _or_ crawling under doors, not both at the same time.
> 

There is no design directive to require going through doors as a bat - only that SS13 had the functionality.
The only issue with not having it is that bats cant open doors - full stop.

>I like this draft, actually. But I think you could avoid the 3 second stan by wearing earplugs or maybe headphones?

There is currently no such thing as hearing protection in game, technically headphones are just neck items.
But yes if hearing protection is added (besides hardcoding specific items) then it should protect from this ability

> You couod have the abilities unlocked through an antag store as they drain blood from their victims
I considered a store, but i like the idea of vampire bloodlines - where each bloodline has a focus (such as melee, ranged, stealth etc), and thats the direction i would like to explore.
The problem with vampire + store is the currency would be blood - they could practically infinitely generate currency.

**Comment by Rainfey** [comment]
Ah looks like Remilia specifically is a DoorBumpOpener - and i just chose MobBat as the polymorph target
I'll create a dedicated vampire bat type

**Comment by Carolyn3114** [comment]
can you use bloodpacks to gain blood?

**Comment by Rainfey** [comment]
Not currently, you can drink blood for hunger and thirst - but it must come from a humanoid for you to gain Blood for abilities.
You can however drain a person, then use a bloodpack to refill their blood - and then drain them again.

**Comment by thelittleskeleton** [comment]
would be kind of cool if the vampire could convert people into thralls by dragging them into maints and using an ability with a long doafter on them/their corpse - you could make it an antag objective to create x number of thralls or something

**Comment by Rainfey** [comment]
I have shied away from any conversion mechanics - i fear they may push this beyond the bounds of a minior antagonist.
Not exactly minor anymore when i have an army of thralls prowling the halls.

Still willing to get feedback on the idea however, SS13 has both converting others to vampires or converting them into thralls.

**Comment by K-Dynamic** [comment]
Probably hardlimit the numbers of thralls they can have then, like 2 per vampire

Werebat form when

**Comment by melanoTurbo** [comment]
I think vampire should be able to heal with the blood he drank

**Comment by Rainfey** [comment]
Updated with the blood healing, luckily thats already in the game (for shark's)

**Comment by Kadeo64** [comment]
hmm.. what if, wooden bullets, makeshift shotgun shells crafted from plastic, steel, and wood, they deal a minimal amount of damage normally, cause bleed, and most importantly, deal a lot of damage to vampires.

**Comment by UbaserB** [comment]
YOOO VAMPIRE!?!?!

**Comment by BreadyToad** [comment]
Would be cool if vampires not only had their abilities blocked when in chapel but started burning alive like it was in SS13. Plus, if you want to explore vampire bloodlines than you could look at paradise's implementation, they did an amazing job with vampire specialisation

**Comment by keronshb** [comment]
Added Frozen due to the antag freeze. Please still feel free to work on the doc & PR as needed. https://github.com/space-wizards/space-station-14/issues/8524

**Comment by Rainfey** [comment]
I pivoted my design a little, since i am horrible at UI stuff and adding multiple bloodlines was proving to be a coding mess -

I'm trying out the store idea instead, hopefully i can balance it based on the cost of abilities and with blacklists (ie you can only buy one polymoph form)

@keronshb Once this PR is ready for review - do i proceed as normal or are there additional steps? (like discussing it with maintainers)

**Comment by metalgearsloth** [comment]
> I pivoted my design a little, since i am horrible at UI stuff and adding multiple bloodlines was proving to be a coding mess -
> 
> I'm trying out the store idea instead, hopefully i can balance it based on the cost of abilities and with blacklists (ie you can only buy one polymoph form)
> 
> @keronshb Once this PR is ready for review - do i proceed as normal or are there additional steps? (like discussing it with maintainers)

The PR will get reviewed at some point but much more stringently than a normal PR, I think ninja had over 200 comments and even that felt short.

**Comment by deltanedas** [comment]
200 on first pr :trollface:

**Comment by RedNiloc** [comment]
I have an idea, that maybe vampires can pry doors with bare hands and even powered ones (Like zombie) since they are extremally strong creatures.

**Comment by Xkallubar** [comment]
Add thralls but make it so that initially vampires have a cap of like 1-2 thralls, and depending on their bloodline, or if they get the final upgrade, they gain extra thrall slots.

**Comment by tutoumi** [comment]
i think lizards and spiders species should not be able to be vampire cause its praticly normal to see them drink blood on the ground for exemple

**Comment by Kadeo64** [comment]
you should be able to craft crosses and stakes to combat vampires, crosses would take a lot of wood but prevent a vampire from using their abilities near it, and stakes would deal increased melee damage to the vampire

**Comment by tutoumi** [comment]
> > > > i think lizards and spiders species should not be able to be vampire cause its praticly normal to see them drink blood on the ground for exemple
> > > 
> > > 
> > > no specism, even more if it's to metacheck them(also gender/specie loc antags is lame as fuck)
> > 
> > 
> > well then we should do something about those animal stomachs, i don't know, make them feel sick by fact that they drink blood on the floor, they already can clean their murders by drinking the blood, making them be able to recharge their blood stock without being suspected would make these species (I aim more the lizard specie) even more powerfull and unbalanced, and if the vampire is immune to space and cold, it remove the main and praticly only disadventage of lizard wich is their cold blood.
> 
> aren't vampires supposed to restock their blood points by drinking blood from crew member directly and not from the floor tho? What about slime players then? they got a fancy regen no matter their current health status! this is certainly unbalance in favours of slimes traitor/nukie/thief. What about dwarfs that can heal their bruises and burns with alcohol and not suffer alcohol poisoning? this also is not very balanced, just grab a jug of booze and your good for the entire round. Not EVERY lizard players will be vampire at the end of the day, so these concerns are close to irrelevant. not everything is numbers and stats, it's a roleplaying game for fuck sakes

true true, I didn't realized this, humans suck than.

**Comment by tutoumi** [comment]
and why not a very very very (like, very very) little chance of spawning, in expeditions or maints, a mask that transform you into a vampire if you manage to be touched by blood with it equipped ?

**Comment by Clostyandr** [comment]
What's up! How it goes?

**Comment by Spargenox** [comment]
So, I just thought of this very same idea and I had some suggestions for this.

My first idea is that he should start on a salvage wreck, something for salvage to find in their endeavors (and provide the vampire with something of a challenge to get started... it would also be hilarious for salvage to have to deal with a full scale antag of some kind while out there, especially since they find him in a 'coffin'

Also, one of his powers should be some form of mind control (very traditional for a vampire to have thralls, and a ready source of blood for him to consume).  This power should be expensive and cost blood. 

As for goals, one may be for him to take control of the ship.... Through mind control or his own raw charisma

It should also be extremely hard to kill him.  As in, people need spears or wooden stakes to stop him, but his thralls should be able to drag him away and revive him. Killing him may need holy water, lots of fire, sunlight, or shoving a grenade down his pants (kudos if you know the reference)

As for his ability to do damage, he should be monstrously strong, capable of taking on multiple people with his bare hands, and take lots of damage too.  

Another idea i had was he could call in a single favor from centcom (to represent his ancient deals and pacts made a hundred years ago) that is up to the Admin to decide the limits.  

This is a great idea! Thanks for being awesome!

**Comment by tutoumi** [comment]
just to know, when you mean minor antag, you mean like a traitor wich is "minor" cause there is other traitors ? or really just like dragon/space ninja/terminator ?

**Comment by TheShuEd** [comment]
Antag refactor merg! Unfrozen! 🎈

**Comment by metalgearsloth** [comment]
> Huh? 🤔

Refactor is maybe 30% of where antags need to be so they're still frozen.

**Comment by tutoumi** [comment]
What is the other 70% then ?

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by Psychpsyo** [comment]
If there is a vampire radio channel, I vote that all bats also have access to it.

**Comment by Strol20** [comment]
Time to wake up

**Comment by a-person5660** [comment]
Wake the fuck up samurai, we got a station to burn!

**Comment by chavonadelal** [comment]
It's time to open it!

**Comment by Golubgik** [comment]
TIME!!!!!!

**Comment by tutoumi** [comment]
OPEN pretty please

**Comment by Strol20** [comment]
> OPEN pretty please

He hasn't done anything on GitHub in a long time

**Pull request closed without merging**
