### PR TITLE
Major Tesla tweaks

### PR DESCRIPTION
**Pull request by TheShuEd**
### Strike prob
Lightning strike targets can now be ignored by a lightning strike with a certain chance.

A tesla coil has a 50% chance of being ignored.

This increases the importance of placing ground rods around the tesla to contain it, previously they were useless with 4 coils.

Now, placing just 4 coils will result in a serious chance of lightning striking an unintended device. We NEED 4 grounding rods.
### Lightning Bounce Fix. 
Fixed a small bug where lightning always reflected at least 1 time, even if it shouldn't.

### Tesla coil nerf
Now the tesla coils is just as completely absorbing all lightning, preventing it from being reflected. This greatly reduces the amount of energy produced by the tesla, because previously 1 tesla strike could charge 3-4 coils at once.

the amount of energy received from a lightning strike is reduced by 2 times
Given the frequency of lightning strikes, and the low rate of energy output, this should not affect the final energy output much

### Destructible coils.
Lightning strikes deal 1 structural damage. Coils are now visually cracked and need to be repaired by welding every 30 minutes. grounding rods are now the only device that is immune to lightning damage and can hold back the tesla indefinitely.
image

**Changelog**
:cl:
- tweak: Tesla coils now have a 50% chance of not attracting lightning.  Installing ground rods is now much more important!
- tweak: Nerf tesla energy producing.
- add: Now tesla coils are gradually wearing out, taking damage from lightning. Keep an eye on them and repair them with a welder every 20-30 minutes. Grounding rods are immune to lightning damage.

### CODE REVIEW

**Comment by TheShuEd** [comment]
I'm thinking of making several small patches based on feedback, and then writing a guidebook that describes the technical details in detail

**Comment by Emisse** [comment]
How performant is this compared to the current system?

**Comment by TheShuEd** [comment]
I can’t say the exact values, but in general I reworked the lightning system to a more optimized one, and here I simply tied the anomaly to new functions.  It should be faster anyway

**Comment by TheShuEd** [comment]
Logically, it has a very weak effect on optimization.  Since we simply skip the elements of the list and take the next ones.

**Comment by Ilya246** [comment]
i would recommend removing the ignore chance from grounding rods, else nobody will use it because it will always loose
"never safe" is not something you ever want something that destroys the station to be

**Comment by LordEclipse** [comment]
Having failure being rng based never feels good. People barely usw singulo because it randomly fails despite all the protective barriers.

**Comment by Ilya246** [comment]
> Having failure being rng based never feels good. People barely usw singulo because it randomly fails despite all the protective barriers.

singulo does not currently randomly fail, but a bug caused it to, so engi either never used it or left a person to watch and control it at all times

**Comment by LordEclipse** [comment]
> > Having failure being rng based never feels good. People barely usw singulo because it randomly fails despite all the protective barriers.
> 
> singulo does not currently randomly fail, but a bug caused it to, so engi either never used it or left a person to watch and control it at all times

the uncertainty would regardless cause them to use boring engines like the AME

**Comment by TheShuEd** [comment]
I removed the 5% chance of being ignored at the ground rod. Now there's no randomness. But now coils and rods take structural damage from lightning strikes, and they need to be repaired periodically with welding. If I counted correctly, this should be done about once every half hour.

**Comment by TheShuEd** [comment]
https://github.com/space-wizards/space-station-14/assets/96445749/e57424c6-ba2b-4296-99c5-78867c208f72

**Comment by TheShuEd** [comment]
Still not sure how to properly calculate the balanced value of the generated energy. Right now, the tesla should be generating less

**Comment by TheShuEd** [comment]
I don't understand what the errors are, frankly.

**Comment by deltanedas** [comment]
error is unrelated

also i think instead of no maintenance = tesloose, it should be no maintenance = no power like singulo

instead of lightning destroying the coils and grounding rods, it simply makes them less efficient because arcs degrading the surface. then you just repair them to bring efficiency back up similar to fish game reactor

**Comment by Emisse** [comment]
i think thats probably better idea so the idea of power generation is less binary than (power or station destroyed)

**Comment by TheShuEd** [comment]
I can remove the damage from lightning from the rods.  the coils will break, but with the right number of rods, it will remain safe

**Comment by deltanedas** [comment]
with singulo if you forget to refuel it you get less power
with proposed tesla changes, if you forget to weld it *the entire station blows up*

**Comment by TheShuEd** [comment]
Okay, let's say. Thesla coils break after 30 minutes without maintenance and the station remains without power. The ground rods break after 1 hour+ without maintenance and Tesla runs away. Is that normal?

**Comment by deltanedas** [comment]
grounding rods shouldnt break otherwise you cant rely on them to keep things safe

**Comment by Ilya246** [comment]
just make it give power forever, the balancing of making it equally bad as singulo does not work
right now:
singulo - certainly dangerous if contained, dangerous depending on chance if loose
tesla - safe if contained, guaranteed station death if loose
overall, tesla is less safe
there should be actual reasons to use the less safe option, there's literally no reason to use it if it's just singulo but with much deadlier loose

**Comment by TheShuEd** [comment]
well the main problem now is the tesla doesn't require any upkeep at all. You build it and forget about it, getting infinite energy.

**Comment by Ilya246** [comment]
additionally: while contained, singulo's gravity and radiation are easily dealt with and actually deter sabotage attempts, whereas tesla is extremely easy to sabotage: just unanchor the tesla coils and grounding rods
i believe it is fine for tesla to have no upkeep

**Comment by chromiumboy** [comment]
PJB has said before that unattended engines should not result in it exploding / widespread destruction, so containment needs to remain assured without maintenance

Tesla coils can (and should) degrade with use, but grounding rods should not

**Comment by TheShuEd** [comment]
Okay, now the grounding rods can hold off lightning strikes indefinitely.

**Comment by TheShuEd** [comment]
I think the option that Tesla gradually destroys the coils and rods is a more interesting option.  Yes, she will escape over time, but I think Tesla's escape is fun

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
