### PR TITLE
The medical beret is real

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

This PR adds a medical beret. It can be found in the MediDrobe in a quantity of 4 pieces
The brig medical's beret has been renamed
## Why / Balance

I think what doctors lack are nice hats.
Berets are very aesthetically pleasing.
## Media

изображение
изображение
изображение
изображение
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Medical berets added to MediDrobe

### CODE REVIEW

**Comment by UbaserB** [comment]
where is the button lol

**Comment by icekot8** [comment]
> where is the button lol

the last medic's beret was made for a brig doctor..... The button is some kind of "emblem," I guess.
I removed it because it doesn't fit the horde of doctors.

**Comment by UbaserB** [comment]
> > where is the button lol
> 
> the last medic's beret was made for a brig doctor..... The button is some kind of "emblem," I guess. I removed it because it doesn't fit the horde of doctors.

feels weird this is the only beret in the game that doesnt have a button

**Comment by snebl** [comment]
> > > where is the button lol
> > 
> > 
> > the last medic's beret was made for a brig doctor..... The button is some kind of "emblem," I guess. I removed it because it doesn't fit the horde of doctors.
> 
> feels weird this is the only beret in the game that doesnt have a button

The mime's red beret also doesn't have one. So it's not the only one.

**Pull request merged**
