### PR TITLE
Fix chromite chasm sprite

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR
Nothing personal, Ed.

## Media

chromite

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by TheShuEd** [comment]
I don’t see any problems with reprite, except for one thing.  All other chasms still have stripes.  We either remove them everywhere or leave them (and fix the direction, it's very simple).  But let's maintain the visual integrity of the same gameplay elements

**Comment by EmoGarbage404** [comment]
@Ko4ergaPunk please refrain from inappropriate comments in your PRs.

**Comment by Ko4ergaPunk** [comment]
Removed stripes from other chasms. Be honest, i think they looks weird if chasm larger than 2x2 tiles

chasm

**Comment by SonicHDC** [comment]
Maybe just make all chasms no rotate?

**Comment by TheShuEd** [comment]
Yes, add noRot: true in transform component

**Comment by Flareguy** [comment]
I've always thought the stripes on the chasms looked tacky, so removing them all should be fine.

**Comment by TheShuEd** [comment]
so, I checked, it’s not necessary, but it turns out

**Pull request merged**
