### PR TITLE
Walls, catwalks, table frames can no longer be constructed rotated.

### PR DESCRIPTION
**Pull request by 20kdc**
This fixes the bug where if you pull a girder, the resulting wall is rotated.

### CODE REVIEW

**Review by Zumorica — APPROVED** [review]
LGTM, I don't think there's a better/more elegant solution.

**Comment by 20kdc** [comment]
Ahahahaha do not merge until I send in a new commit, turns out that this stuff isn't supposed to have a rotation of zero but instead -1.5something because rotations are completely wonky

**Comment by 20kdc** [comment]
Fixed, walls face south (but *why*)

**Review by PaulRitter — APPROVED** [review]
hello im just here to rant about the rotation var YES IT MAKES NO SENSE IT MAKES ME SO HECKING ANGRY

**Pull request merged**
