### PR TITLE
Add under-pressure lockout to air vents

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR 
When some part of the station inevitably get spaced, air vents pump air from dist to un-space it. Because air vents are "pressure-based" pumps, they tend to transfer air faster to locations that have low pressure (good).

Unfortunately, this also means that until a room with an air vent is patched up, these air vents tend to pump a lot of precious dist air into space. This means that widespread spacing can cause the pressure in the dist network to fall, and when that happens, areas that are not spaced (but are at low pressure because passengers hold doors open) also do not get repressurized by dist (bad).

This is a problem easily fixable by **NT-patented A.I. technology!** _Brought to you by RD's AI CORE_.

The complicated A.I. technology is too top-secret and patented to be disclosed lest Syndicate corporations steal their secrets, but can be summarized as:

1. Is the pressure less than the _under-pressure lockout (UPLO) threshold_? If so, this area is probably spaced. Don't pump air.
2. Otherwise, pump air.

This means that dist focuses on keeping aired up parts of the station all gassed up. Of course, to repair spacing, clever atmospheric technicians will have to 1) seal a breech and 2) figure out how to bring the pressure above the UPLO threshold.

### Balance
I believe this change strikes the right balance between making sabotage possible and making bad situations recoverable.

This change makes air vents (the default air distribution device used by many mappers) more spacing-proof. Currently, even minor spacing events can depressurize dist to the point where it is ineffective at gassing up areas that are not spaced. The layout of most dist networks are not conducive to the type of debugging that we would like to see, i.e. tracing the dist net until spacing is found, because 1) there are many maps with very different layouts in rotation, and 2) because dist frequently crosses into areas where atmospheric technicians do not have access. For large stations, it can be extremely difficult to locate breeches.

This change does not mean that atmospheric technicians can lounge around. They are still required to repair breeches and bring the pressure up above the UPLO before dist can kick in. We can adjust the UPLO as a built-in difficulty knob:

- 20 kPa: You need to get an atmos tech to drag a gas can in to re-pressurize a room, before the vent will kick in
- **1 kPa (this PR)**: opening a door to an un-spaced area will transfer enough air to turn on the vent
- 0.001 kPa: Breathing will be enough to get the UPLO to go away and turn the vent back on

Unsavory players can still shut down dist with a passive vent to space.

**Mappers:** If you dislike your crew that much, you can replace air vents with air injectors.

**Changelog**

:cl: notafet
- add: Air vents are now more resilient to spacing

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]
im in favor of this as a mechanic. IMO vents should get some kind of examine that tells you this information, as it might be a bit unintuitive

**Comment by Partmedia** [comment]
> im in favor of this as a mechanic. IMO vents should get some kind of examine that tells you this information, as it might be a bit unintuitive

I'll add some examine text to show if vents are in UVLO.

**Comment by Partmedia** [comment]
Added examine text for UPLO.
uplo

**Comment by ike709** [comment]
based idea, stealing for SS13

**Review by wrexbe — APPROVED** [review]

**Comment by Cheackraze** [comment]
Love it but i do need to point out that Split Station uses active vents inside its filter/miner/pressure chambers and the distro network will probably fail hard on the first spacing and be unrecoverable to most engi/atmos teams

**Pull request merged**
