### PR TITLE
Missing Uniform Held sprites

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Changes the held sprites of all uniforms to be accurate to the item instead of a generic jumpsuit sprite.

**Media**

Screenshotting all of those items from every position would be horrible. Have a front facing screenshot.
prthumb2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: Changed the held sprites of almost every uniform to be more accurate.

### CODE REVIEW

**Comment by AJCM-git** [comment]
Did you sprite these? Copyright in meta.json files may need updating either way

**Comment by potato1234x** [comment]
they're just from their original sources but scaled down.

**Comment by AJCM-git** [comment]
> they're just from their original sources but scaled down.

how did you scale them down? you need to mention that the inhand variants were modified like that by you in the copy

**Comment by potato1234x** [comment]
Thats going to be super annoying... Oh well, i'll get on it tomorrow.

**Comment by AJCM-git** [comment]
do mention if it was scaled down by hand or using some automated tool in there

**Comment by potato1234x** [comment]
done

**Pull request merged**
