### PR TITLE
bloody microwaves

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

funnee
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Microwaves now become bloodstained if you microwave animals inside of them. Who was doing this?

### CODE REVIEW

**Comment by lzk228** [comment]
how to clean them?

**Comment by EmoGarbage404** [comment]
> how to clean them?

not even omega soap washes off sin

**Comment by lzk228** [comment]
> > how to clean them?
> 
> not even omega soap washes off sin

pure evil...

**Comment by deltanedas** [comment]
new soap brand called crowbar and screwdriver, nt doesnt want you to know

**Comment by Myakot** [comment]
> Contributor

🎵 We're breaking the wo-orld, breaking the la-aw. 🎵

I'm not that savvy into item states - does this PR allow for bloody microwaves to be mapped in, or do you have to bloody them on the go?

**Comment by Slava0135** [comment]
skill issue

**Pull request merged**
