### PR TITLE
pipebombs and IED rework

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
added pipebombs, gunpowder material and reworked IEDs

IEDs have been renamed to fire bombs, they now do very weak damage but ignite nearby objects
IEDs random timer was changed from (0-60 seconds) to (0-15 seconds)

pipebombs are craftable with gunpowder, lv cable and pipe and do 90 damage in total with a random timer inbetween 1-10 seconds, cannot be linked

## Why / Balance
IEDs are almost never made, due to them being very bad at exploding because of their random timer

pipebombs are offered as an alternative improvised explosive, being harder to make (you need chems to get gunpowder) but are stronger at doing direct damage

## Technical details
added ``DoesIgnite`` and ``FireStacksOnIgnite`` to ExplosionPrototype, lets you choose if the explosion ignites entities or not

## Media
https://github.com/space-wizards/space-station-14/assets/45323883/70f112a6-32e8-4bae-870b-468ecb2bbb0c

https://github.com/space-wizards/space-station-14/assets/45323883/3415baee-682a-41cf-8114-d594872d753a

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
IEDs are renamed to fire bombs

**Changelog**
:cl:
- add: Gunpowder can now be made by chemists with 6 parts potassium, 2 parts sulfur and charcoal.
- add: Pipebombs may now be crafted with a pipe, gunpowder and LV cable.
- tweak: IEDs have been reworked, they are now called "fire bombs" and generate a weak explosion that ignites nearby objects.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
I can't wait to get together with the boys to see how many pipebombs we can build with a functional factory line (warops/revs/greytide moment)

**Comment by Kadeo64** [comment]
#notmyfirebomb
dosbox_2013-07-10_21-36-04-06

**Comment by EmoGarbage404** [comment]
just a general comment, but IIRC, in /tg/, regular explosions do minor create fires in the surrounding area. I think that should generally be true for all of our explosives.

**Comment by deltanedas** [comment]
FireStacksOnIgnite allows this, most explosions can have a low number then gamer firebomb can have 10 :trollface:

**Comment by metalgearsloth** [comment]
will see how it goes

**Pull request merged**
