### PR TITLE
Adds high capacity water tanks.

### PR DESCRIPTION
**Pull request by Lamrr**
## About the PR 
Adds high capacity water tanks which hold 10x as much water (10,000 units) compared to normal ones. Useful for botantists for keeping their plants well watered without running the station dry. I've also buffed the transfer amount for these tanks, with the highly pressurised water coming out at 100 units at a time, at the same time making it less useful for precise mixing.

Sprites, name, description (but not capacity) is from /tg/station.

**Screenshots**

Screenshot from 2022-02-11 14-48-48

**Changelog**

:cl:
- add: High-capacity water tanks have arrived! Botanists no longer have to scavenge for water.

### CODE REVIEW

**Comment by mirrorcult** [comment]
im not really convinced we need these, why are water tanks not good enough

**Comment by Lamrr** [comment]
> im not really convinced we need these, why are water tanks not good enough

Botany is pretty water intensive. With each tray taking 100u of water, a default water tank can only refill 15 trays (~1.5 refills of the entire set of hydroponics trays on most maps) before you need to find a replacement tank.

**Comment by mirrorcult** [comment]
what's the issue with having to find a replacement tank

**Comment by Lamrr** [comment]
> what's the issue with having to find a replacement tank

It's not particularly exciting gameplay, it just means waddling through maint. to see if there's a spare tank. Water tanks aren't even orderable through cargo irrc.

> What if sinks could fill up water tanks? I'm not sure how frequently this depletes during botany use, e.g. if it's every 15 minutes they have to fill up water that's not so bad.

I'm not opposed to this, but currently sinks are very finite (~500 units) and coding a plumbing system for sinks is a bit beyond the scope of this PR and my skills.

**Comment by Acruid** [comment]
SS13 Units follow some weird nonlinear scaling for units = liters.
Syringe: 15u = 15ml, 1,000u/L
Beaker: 25u = 250ml, 100u/L
Our Beaker: 50u = 500ml, 100u/L
Lg Beaker: 100u = 1L, 100u/L
1qt Blue Spray bottle: 100u = ~1L, 100u/L
Hydro Soil: 200u
32qt Yellow rolling mop bucket: 500u = ~30L, ~16u/L
2gal Blue Bucket: 70u = ~7L, 10u/L
55gal? (being generous) Water Tank: 1,500u = ~200L, 7.5u/L
Magic HC water tank: 10,000u = ~2,000L?, 5u/L

Here is a graph to visualize this, notice the log scaling...
image

**Review by mirrorcult — APPROVED** [review]
i think im fine with this for now

**Comment by mirrorcult** [comment]
fine with this being added but it should be salvage-only probably, as a big reward

**Review by mirrorcult — APPROVED** [review]

**Comment by Willhelm53** [comment]
Worth noting as well that the transfer amount from reagent tanks can be set via your bucket as of #6313, but this was merged a few days after your PR was submitted.

**Pull request merged**
