### PR TITLE
Familiar Garbs

### PR DESCRIPTION
**Pull request by noctyrnal**
## About the PR

added the "Familiar Garbs" outfit, a reference to everyone's favourite family guy :godo:

## Why / Balance

because its funny

## Technical details

just added the outfit

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

none

**Changelog**

- add: Added the "Familiar Garbs"
5743c437f536255d79062b49fa3b770f

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Peter what are you doing?
Crack.
What the fuck!

**Comment by camrynz** [comment]
Lois remember that time I shipped a maxcap to centcomm?

**Comment by VasilisThePikachu** [comment]
I'm so sorry

https://github.com/space-wizards/space-station-14/assets/34938708/6fc6fb30-7f8a-4b4b-b3a4-43c13e9a4adb

**Comment by LordEclipse** [comment]
Hey Lois, remember that time I was a Nuclear Operative for The Syndicate?

**Comment by JoeHammad1844** [comment]
remove the changelog, it's funnier when its a surprise

**Comment by JoeHammad1844** [comment]
> Hey Lois, remember that time I was a Nuclear Operative for The Syndicate?

nukie peter

**Comment by keronshb** [comment]
You should definitely change the title of the PR, otherwise this is fine.

**Comment by deltanedas** [comment]
it seems today
that all you see
is tiders in maints
and erp in closed appeals

**Comment by noctyrnal** [comment]
titled change , Peter will be real soon

**Pull request merged**
