### PR TITLE
Adds a small AI survey drone to the salvage map list.

### PR DESCRIPTION
**Pull request by Phantom-Lily**
## About the PR 
Added a new map to salvage. A small AI-controlled survey drone that failed due to electrical breakages.

**Screenshots**

image

**Changelog**

:cl:
- add: Added a new small drone wreck to salvage.

### CODE REVIEW

**Comment by PaulRitter** [comment]
could be a bit more busted up, no? this is practially an almost functional ship afaict

**Comment by Phantom-Lily** [comment]
Part of the point was to make something that failed in a more subtle way than being blown up or taken over, but sure, I suppose I can make it a little more roughed up on the outside at least.

**Comment by Phantom-Lily** [comment]
image
Screenshot of the drone in its new state. This good enough?

**Comment by moonheart08** [comment]
seems good to me

**Comment by PaulRitter** [comment]
yeet

**Pull request merged**
