### PR TITLE
Make the escape menu look better

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Requires [engine PR 5041](https://github.com/space-wizards/RobustToolbox/pull/5041)

Made the escape menu fullscreen

## Why / Balance

As of right now, the escape menu is literally just a window that pops up in the middle of your screen.

I also want this so people (me) can put things that aren't buttons (a continuously scrolling list of all the contributors) into the escape menu

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Made the escape menu take up the whole screen and have some better visuals

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Can this become a option in the settings? 
I would hate having a full screen menu block the view of the entire game

**Comment by notquitehadouken** [comment]
> Can this become a option in the settings? I would hate having a full screen menu block the view of the entire game

how often do you have the escape menu open

**Comment by Brandon-Huu** [comment]
> > Can this become a option in the settings? I would hate having a full screen menu block the view of the entire game
> 
> how often do you have the escape menu open (also it's gonna be transparent)

most of the game when playing chem

**Comment by deathride58** [comment]
What are you doing in chem that needs the escape menu open at all times?

Only thing we can think of off the top of our head is guidebook, but that's got a hotkey (defaults to numpad 0, can be rebound)

**Comment by notquitehadouken** [comment]
> What are you doing in chem that needs the escape menu open most of the time?
> 
> Only thing we can think of off the top of our head is guidebook, but that's got a hotkey (defaults to numpad 0, can be rebound)

and guidebook isn't changed, it's still a regular window

**Comment by notquitehadouken** [comment]
merge conflicts unresolvable until i'm done with engine work

**Comment by notquitehadouken** [comment]
image
development is going smoothly

**Comment by metalgearsloth** [comment]
Re-open if you come back to it.

**Comment by notquitehadouken** [comment]
he did not, in fact, come back to it

**Pull request closed without merging**
