### PR TITLE
Riot gear expansion (April fools)

### PR DESCRIPTION
**Pull request by PolterTzi**
## About the PR

Expands the riot gear available in lathes and SWAT crate.

## Why / Balance

To add some variety.

## Media

image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by PolterTzi** [comment]
> Why are they, censored?

For the funny.

**Comment by CatMagic1** [comment]
funny

**Comment by metalgearsloth** [comment]
I don't find anti-LGBT content particularly funny but if you have a good reason explain it on the forums.

**Comment by Brandon-Huu** [comment]
That's crazy.

**Comment by CatMagic1** [comment]
wait this is anti-lgbt?
oh fuck i'm an idiot

**Comment by Jezithyr** [comment]
The PR author explained their intent for this PR and it honestly makes sense. This was meant as a play on "Pride is a Riot", which specifically references Stonewall (aka the first "Pride parade" which was actually a riot) and is a call to action in some pride circles. The renaming from Riot Control Gear to Riot Gear, definitely supports this (if you were going to riot in support for trans rights, you would probably wear a rainbow after all). 

Not sure what the blurring was for but I imagine it might have been to reference censorship? Either way, was it a good idea to make such a specific reference? Probably not, but it definitely wasn't malicious. That said, it's way too easy it is to misinterpret this sort of joke because of it's depth. Hell I had no idea this was a play on Pride is a Riot/reference to Stonewall until they explained it in their appeal. They've been unbanned from github since this entire situation looks to be a big misunderstanding of a very nuanced joke.

**Pull request closed without merging**
