### PR TITLE
gives all heads of staff flashes 

### PR DESCRIPTION
**Pull request by randy10122**
…lashes, a little setup for the telebaton

## About the PR

gives all heads of staff their own backpacks, satchels, duffelbags, and puts flashes in them
also has the setup for the telebaton once i implement that

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:randy
- add: all heads of staff now have flashes in their bag for self defence

### CODE REVIEW

**Comment by Stealthbomber16** [comment]
they don't even have sunglasses

**Comment by randy10122** [comment]
> they don't even have sunglasses

i went over this in the previous pr (that i closed bcos i fucked up)
you can use flashes as melees  to not flash yourself (it also lasts longer)

**Comment by metalgearsloth** [comment]
We're not adding telescopic baton and it's questionable to even give heads flashes.

**Comment by randy10122** [comment]
> We're not adding telescopic baton 

why did it already exist in the captains bag then (even if commented out)

>it's questionable to even give heads flashes.

how tf is it questionable? they have no other means of nonlethal defence - they deserve Something, and this is the least powerful option out of all of them

**Comment by moonheart08** [comment]
im making an executive decision

**Pull request merged**
