### PR TITLE
Clowning around

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR
Clown shoes now have 20 storage, for always being able to prank on the go.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl lots of fun

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Why

**Comment by GoodWheatley** [comment]
> Why

1) legacy feature
2) clown buff
3) it's funny

**Comment by AJCM-git** [comment]
make it only able to store the horn/a pie and im in

**Comment by Scribbles0** [comment]
> make it only able to store the horn/pies and im in

banana peels and maybe soap should also be apart of this list

**Comment by GoodWheatley** [comment]
> make it only able to store the horn/pies and im in

I think it's funnier if the clown gets cornered and they just pull a stun baton out of their shoes but I'll look into that

**Comment by mirrorcult** [comment]
why. they already have a funny backpack

**Comment by Emisse** [comment]
clown needs a silly satchel still, needed one for like 18 years

**Comment by GoodWheatley** [comment]
> why. they already have a funny backpack

maximum pranking power

**Comment by EmoGarbage404** [comment]
this pr doesn't have any logic or justification behind it other than "lol funny"

**Comment by GoodWheatley** [comment]
> this pr doesn't have any logic or justification behind it other than "lol funny"

It's a fun way for a clown to stash some extra items in case their backpack gets stolen or they get arrested, and it makes sense because of how huge the clown shoes are.

**Comment by EmoGarbage404** [comment]
first, i tend to dislike random items with storage because it just leads to the random "lol secoff didn't take off every single random item now i have tools in perma." It also just makes it a stupidly good hiding spot for whatever various traitor items you like, because (quite rightfully) people won't think to check clown shoes for hidden items within them.

That being said, it additionally just doesn't make sense. it's not like they have a pocket or visual aspect that shows why this makes sense. you could use this justification to put any amount of random storage on any random clothing item.

**Pull request closed without merging**
