### PR TITLE
detective patch

### LINKED ISSUE #24709: detective is still listed under security
## Description
detectives arent apart of security anymore, yet they're still listed as security on the cerw manifest, which is strange

**Reproduction**
- be detective
- check crew manifest, notice that you're listed under security

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
detectives now appear under civilian rather than sec and now spawn with jack boots instead of combat boots

their survival box is also a normal one instead of a security one

## Why / Balance
they dont need a combat knife (they're not sec)
they shouldnt appear under security in the crew manifest (they're not sec)
they shouldnt spawn with a security survival box (they're not sec)

resolves #24709 
## Technical details
3

## Media
image
detective under civilian

image
new detective icons
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Detectives are now listed under civilian instead of security.

### CODE REVIEW

**Comment by Hmeister-fake** [comment]
I feel like them having a vest is fine, since barkeeps get one too. they look odd without one.

**Comment by Dutch-VanDerLinde** [comment]
> I feel like them having a vest is fine, since barkeeps get one too. they look odd without one.

they still have one in their locker and vending machine, they just dont spawn with one (like bartenders)

**Comment by asperger-sind** [comment]
> I feel like them having a vest is fine, since barkeeps get one too. they look odd without one.

They normally get their armored coat, so its not that bad.

**Comment by GreyMario** [comment]
now remove security playtime requirement (they're not sec)

**Comment by Holinka4ever** [comment]
Isnt it a test-merge?
I mean, patching it, giving me bad thoughts that test-merge can become... permament.?..
Anyway their autodrobe has free armour dispenser though.

**Comment by CrigCrag** [comment]
> Isnt it a test-merge? I mean, patching it, giving me bad thoughts that test-merge can become... permament.?.. 

multiple PRs (patches) can be reverted at once

**Comment by Holinka4ever** [comment]
Anyway, i am gonna put my quarter into jar.
So what about to take their weapon away?
The gun, the revolver.
They doesnt need it at all, cause they are not whom hunts for antags or else, though.
In a story for private investigator, their job is not asking for a gun or any weapon. Their job as telling on wiki page, is about invistigate things undercover, to find truth and etc. Why they need a gun for this job? Lets also take notable  investigators from a history for example:

Sherlock Holmes, instead of weapon, he used his sharp mind, to solve unsolveable crimes!

Timtim! Batman! That guy from judgement series!

Sam from Sam&Max! Used their brain to solve crimes, even though they have weapon, but they using it notable rare, and game is point and click, nor the shooter.

So why at this point dec should have weapon, if he need to investigate minor station stuff, nor the true antagonistic shemes byond his work flow? Thing is that service det doesnt work in lrp scenary, and you need a lot of time to make it work. Is about to delete his gun his grip.

**Comment by Dutch-VanDerLinde** [comment]
> Anyway, i am gonna put my quarter into jar. So what about to take their weapon away? The gun, the revolver. They doesnt need it at all, cause they are not whom hunts for antags or else, though. In a story for private investigator, their job is not asking for a gun or any weapon. Their job as telling on wiki page, is about invistigate things undercover, to find truth and etc. Why they need a gun for this job? Lets also take notable investigators from a history for example:
> 
> Sherlock Holmes, instead of weapon, he used his sharp mind, to solve unsolveable crimes!
> 
> Timtim! Batman! That guy from judgement series!
> 
> Sam from Sam&Max! Used their brain to solve crimes, even though they have weapon, but they using it notable rare, and game is point and click, nor the shooter.
> 
> So why at this point dec should have weapon, if he need to investigate minor station stuff, nor the true antagonistic shemes byond his work flow? Thing is that service det doesnt work in lrp scenary, and you need a lot of time to make it work. Is about to delete his gun his grip.
> 
> P.S. If you gonna tell argument my text with "But barthender has weapon and armour too, boo!", i will say that barthender has place to defend from, what detective defending with his gun?

the detective is defending himself with the gun

**Comment by Holinka4ever** [comment]
> the detective is defending himself with the gun

Why he need to defend himself? 
Is he a head? Is he a sec? Is he holding highrisk?
He is just a part of service, where people asking his help or not. He doesnt need a gun for this.

**Comment by magnitude9girthquake** [comment]
I mean considering the det is supposed to find the bad guy and go directly to the crime scene as opposed to bartender who mostly just deals with people throwing glass its fair to have something to defend themselves with (and syndicates could target det so they dont get caught)

**Comment by Holinka4ever** [comment]
> I mean considering the det is supposed to find the bad guy and go directly to the crime scene

Thats good point, but det will be with secOffs, that will can defend him. Also, investigating without secOffs can be considered as validhunting, that might be against rules.

> (and syndicates could target det so they dont get caught)

Syndcate can target anyone, even a poor passenger.
Should we give the passenger a roundstart weapon, to have option to defend themself?

**Comment by magnitude9girthquake** [comment]
The passenger doesnt have tools to find out who the syndicate agent is, the detective's main job is to find out who did what

**Comment by Holinka4ever** [comment]
> The passenger doesnt have tools to find out who the syndicate agent is, the detective's main job is to find out who did what

Now we are breaking validhunting line, clap clap.
Service det is not a mere sec. 
More like, private investigator of minor stuff on station, that can be in service for officers, but not by himself.

**Comment by magnitude9girthquake** [comment]
If the det has no means of self defense then they will be an easy target and get attacked almost every round by syndies so they dont get caught. As it is right now det is the highest priority target in service because their job actually directly affects the syndicates

**Comment by commash** [comment]
I would actually go the opposite and give the det nothing but lethals. Not making a decision on whether having det as seperate from sec being a good idea, but I think giving the det nonlethal rounds makes them MORE likely to validhunt syndies and go for arrests.

In addition, I think having lethals would add more roleplay for security, as it would bring into question the detectives use of lethals (and potentially lead to consequences).

**Comment by UbaserB** [comment]
I would keep everything and just change the icon and job location on the list. Thats what i was originally planning to do, and it simply doesnt work with their weapons and gear gone.

**Comment by EmoGarbage404** [comment]
i agree with devi. i'd rather just start with correcting the icon & job placement and then re-examine the other stuff later. I don't really think they warrant any of the other changes at this time.

**Comment by Dutch-VanDerLinde** [comment]
what about the combat boots --> laceup shoes change

**Comment by GoodWheatley** [comment]
If the combat boots get removed they should be changed to jackboots to keep the current look

**Comment by Dutch-VanDerLinde** [comment]
changes: detectives still keep lethals and their vest

now they just get jackboots, listed under civilian, new icons and normal survival box

**Comment by Holinka4ever** [comment]
> If the det has no means of self defense then they will be an easy target and get attacked almost every round by syndies so they dont get caught.

 Antags are chaotic neutral beings, that means we cant think what their next step will be, from being yoinki sploinky and validhunter+ to maintence threat and murderdromer

> As it is right now det is the highest priority target in service because their job actually directly affects the syndicates

If security "hire" him, he can work with syndicate related stuff, but he cant do it by himself, because its a validhunt, validhunt.
Thats really, really weird, because detective independence kinda broke all logic keys with him.
Because... det become a civil validhunter, and now this is a high stakes of a problem.

Someone told that det in security is just secOff with changes. That bolder between sec and det is slowly turning into dust, is that a really problem? Is game a competitve hero rpg, that roles should be diffrent to each other?

**Pull request merged**
