### PR TITLE
Hristov for nuclear operatives

### PR DESCRIPTION
**Pull request by Jackal298**
## About the PR

I made this PR due to the fact that, it seems to me the price of a sniper kit is very small, and also because half of its contents are useless for a nuclear operative, I made a kit that is ideal for them, it includes one rifle and a box of 30 cartridge, everything comes in a syndicate duffel bag, it all costs 20 TC, this set is exclusive to the syndicate and cannot be sold in the agent uplink and get caught in the support crate, I also removed the ability to buy a sniper set from nuclear supporters due to the meaning of duplex items

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a special Hristov Bundle for nuclear operatives for 20 TC
- tweak: The sniper bundle is now an agent exclusive

### CODE REVIEW

**Comment by Jackal298** [comment]
"flare launch"

**Comment by Jackal298** [comment]
"I start a signal fire to check"

**Comment by Jackal298** [comment]
you can request a merge

**Comment by DjfjdfofdjfjD** [comment]
It doesn't cost 20 TC, two packs of cartridges for an increase in the price of 8 TC?

**Comment by Jackal298** [comment]
> It doesn't cost 20 TC, two packs of cartridges for an increase in the price of 8 TC?

I wanted to raise the price of the rifle so the nukers wouldn't spam it

**Comment by Jackal298** [comment]
> > > It doesn't cost 20 TC, two packs of cartridges for an increase in the price of 8 TC?
> > 
> > 
> > I wanted to raise the price of the rifle so the nukers wouldn't spam it
> 
> just make it wieldable and all the problems with it being bought twice disappear

Okay, I'll review my PR

**Pull request closed without merging**
