### PR TITLE
Fix VV perm

### PR DESCRIPTION
**Pull request by metalgearsloth**

### CODE REVIEW

**Review by ElectroJr — COMMENTED** [review]
To ensure the /vv command and the VV-verb permissions are consistent the `_clientConGroupController.CanViewVar()` in the client's `AdminVerbSystem` should probably be replaced with a `_clientConGroupController.CanCommand()`

**Review by ShadowCommander — APPROVED** [review]

**Review by ElectroJr — COMMENTED** [review]
As mentioned on the discord, `showmarkers` is also missing permissions. So is
`menuvis` (allows you to look into containers & see invisible entities with right-click menu).

So might as well also add those.

Also, the `cvar` command needs permissions. I assume everyone should get access to that, given that it has its own permissions system with things like `CVar.CHEAT` for fake-lag. Users should definitely be able to do things like set their UI-scale via the cvar

and devwindow

**Comment by Efruit** [comment]
and (s)csi

**Comment by Zumorica** [comment]
Merging for now, I'll address the inconsistent VV perm and the rest of missing perms in an upcoming PR

**Pull request merged**
