### PR TITLE
New thief intro

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Adds a new custom track for receiving the thief antag roll, made by pigeonpeas.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/134914314/9f973713-884d-4587-9dc1-860d187addb8

**Changelog**

:cl: pigeonpeas
- add: Thieves now have a new starting intro.

### CODE REVIEW

**Comment by TheShuEd** [comment]
Bruh, please, no

**Comment by UbaserB** [comment]
> Bruh, please, no

why, what’s the issue with it?

**Comment by TheShuEd** [comment]
I just don't like this new sound, I don't think it matches the style of the game or the thief

**Comment by Kit0vras** [comment]
good sound, but TheShuEd is right

**Comment by Nairodian** [comment]
I do very much like the music, but yeah I have to admit it feels too.. energetic, for a stealth role. Sounds like something I'd hear out of SCP Secret Lab, which I'd say is a fine thing applied to the right role.

**Comment by LordEclipse** [comment]
Sounds very Madness Combat-y

**Comment by TheShuEd** [comment]
Given the overall feedback and the likes/dislikes ratio, I'm closing this pr. This track has its place, but definitely not as an intro for the stealthy role of a thief. Perhaps you will find another use for it.

**Comment by TheShuEd** [comment]
Bruh, still not stealsy, still not thiefy

**Comment by UbaserB** [comment]
> Bruh, still not stealsy, still not thiefy

i havent updated it yet

**Comment by TheShuEd** [comment]
I listened to what you pinged me on discord

**Comment by UbaserB** [comment]
The person who made the track is going on a break so it'll be a while until this PR gets updated

**Comment by ps3moira** [comment]
This doesn't sound fitting of the game at all or what a thief theme song should even sound like. Maybe aim for something like the Thief (2014) game OST, but even then I'm not sure a thief antag should even get a sound effect.

**Comment by UbaserB** [comment]
I will reopen this if they ever come back to it.

**Pull request closed without merging**
