### PR TITLE
Better puddle visuals

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

**Media**

Peek 2023-03-10 19-16

**Changelog**

:cl:
- add: added new puddle visuals!

### CODE REVIEW

**Comment by PixelTheKermit** [comment]
I'm honestly not sure how I feel about this, looks too... squarey for me. Visuals also appear a bit bugged in the video attached.

**Comment by Slava0135** [comment]
> I'm honestly not sure how I feel about this, looks too... squarey for me. Visuals also appear a bit bugged in the video attached.

it's not buggy, it just shows flow direction (if there is no flow - there is connection)

**Comment by potato1234x** [comment]
why not use the sprites from goonstation?

**Comment by mirrorcult** [comment]
goonstation puddle sprites look terrible tbh

**Comment by potato1234x** [comment]
i mean they are better than the current squares

**Comment by metalgearsloth** [comment]
> i mean they are better than the current squares

We're getting new ones.

**Comment by Slava0135** [comment]
sloth will make this better

**Pull request closed without merging**
