### PR TITLE
[Tweak] Remove some confusing words from archaic.

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

It removes the "like" to "enjoy" translation as it doesn't work with comparisons, removed the "cozenage" translation because words that it replaces are better IMO, and removes some of the "consort" translations. The large majority of these changes were suggested by Eden (hunter_liznerd on discord).

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: OctoRocket and Eden
- tweak: Removed annoying archaic replacements that involve like and other confusing swaps.

### CODE REVIEW

**Comment by Eden077** [comment]
A quick example for like is kind of looking like this this "It's almost *like* enjoy it never happened"

**Comment by UbaserB** [comment]
i thought i removed the "like" to "enjoy", since i noticed it wasnt perfect. Sorry bout that

**Comment by UbaserB** [comment]
It was actually really hard to tweak the archaic words and stuff

**Comment by Eden077** [comment]
> It was actually really hard to tweak the archaic words and stuff

Nah it's fine, I love the archaic accent so far, calling for help in archaic Is a blast as well considering they literally go "ASSIST! I BESEECH THEE! ASSIST ME! ASSIST!" we lost it when that happened lol, keep up the good work

**Pull request merged**
