### PR TITLE
diagonal window glass and pirate shuttle improvements

### PR DESCRIPTION
**Pull request by brainfood1183**
Added - Diagonal window glass (window, rwindow, plasma, rplasma, uranium, ruranium and shuttle) and also includes diagonal damage sprites.
Added - Diagonal grilles (includes diagonal electrified sprite).
Added - dark external shuttle airlock glass and standard  (to match the typical syndi shuttle walls).
Changed - syndicate airlock sprites to be closer to the typical syndicate shuttle walls (now grey instead of jet black).
Added - diagonal windows and grille are craftable.
Updated - Pirate shuttle with a new look and some new items listed below.
Updated - the infiltrator with dark external shuttle airlocks.
Added - ironclad II armor (not a hardsuit) intended to provide a bit of protection for pirates.
Added - pirate PDA and ID card (pirates have syndi access).
Changed - pirates now start with syndicate faction (this was the system change).

Pirate shuttle changes

- Changed the shuttle walls to plastitanium (usual for syndis) and windows to plasma.
- Changed the external shuttle airlocks to dark versions.
- Added 2 suits of ironclad II armor (not hardsuits).
- Added 2 improvised laser pistols.
- Added 2 turret toolboxes (hit em with wrench to place).
- Added 1 syndicate armored coat.
- Changed airlocks to syndi airlocks (pirates now have syndi access).
- Added a small prison cell to the pirate shuttle.

untitled-350
untitled-348
untitled-351

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by UbaserB** [comment]
i dont like how the glass is pink, the contrast is bad

**Comment by rosieposieeee** [comment]
Fantastic! Been missing diagonal windows for a while now. Only thing missing now is diagonal reinforced solid walls.

**Comment by BolloTea** [comment]
Diagonal windows are certainly good, and I'm very glad that you returned to supporting pirates.  But there are a couple, but:
  1) This is the bridge of the ship (the cockpit, its style does not look appropriate). 
 2) Gateways... The black color looked much more aesthetically pleasing, and the plasma glass... In general, it doesn’t look bad.  
Sorry for the harsh criticism, but I am more than sure that many people think the same.

**Comment by brainfood1183** [comment]
> Diagonal windows are certainly good, and I'm very glad that you returned to supporting pirates. But there are a couple, but:
> 
>     1. This is the bridge of the ship (the cockpit, its style does not look appropriate).
> 
>     2. Gateways... The black color looked much more aesthetically pleasing, and the plasma glass... In general, it doesn’t look bad.
>        Sorry for the harsh criticism, but I am more than sure that many people think the same.

I darkened the syndi airlocks and i made the plasma glass more opaque.

untitled-352

**Comment by BolloTea** [comment]
And one small, impudent wish: would it be possible to make one room for holding prisoners on a pirate shuttle? Just keeping them in the captain's cabin or in storage is not very convenient)

**Pull request merged**
