### PR TITLE
Singularity, Particle Accelerator & Radiation Collectors

### PR DESCRIPTION
**Pull request by PaulRitter**
what it says on the tin

### Containmentfield-Generators
```
- Gains 4 Power when hit by Emitterbolt and distributes it, together with the buffer, to the connections. Stores remainder (if some connections cannot be done) in buffer
- Buffer can be up to 6 Power
- If ANYTHING is between the generators a connection will not be created
- A Connection is fed Power by the Generator (as explained above)
- A Connection saves its given Power (up to 10)
- A Connection looses 1 Power per second
- A Connection needs 1 Power to repell any entity and 1 + 2 * Singulo-Level Power to repell the singulo
- If a connection does not have enough power stored to repell an obj, it dies
- If a connection reaches 0 Power, it dies
```

### Emitter
```
- Needs 500W
- Emits Emitterbold every second
```

### ParticleAccelerator
```
- Needs Level * 1500 + 250 W
- Emits 3 (1 per emitter) ParticleProjectiles every second
```

### Singularity
`Starts with 180 Power`
#### Levels
```
Dead:    Energy == 0
Level 1: Energy <  200
Level 2: Energy >= 200
Level 3: Energy >= 300
Level 4: Energy >= 600
Level 5: Energy >= 1000
Level 6: Energy >= 1500
```
#### Energyloss (per second)
```
Level 1 => 1
Level 2 => 2
Level 3 => 5
Level 4 => 10
Level 5 => 15
Level 6 => 20
```
#### Energygain by ParticleProjectile
```
Level 0 => 1,
Level 1 => 3,
Level 2 => 6,
Level 3 => 10,
```
#### Other Energygain
`+1 Energy per Entity/Tile absorbed`

#### Radiation Emitted
`10 * Level => Rads per seconds`

### Radiation Collector
`Rads per seconds * 3000W => Watts per seconds`

## Neat lil' Pictures
grafik
grafik
grafik
grafik
grafik
grafik
grafik

# ToDo
- [x] fix emitter sprites being weird on level3
- [x] have connections decrease power over time
- [x] update values in pr

- [x] find a way to handle singulo breaking containment (swallow containmentfield if level goes above X? swallow containmentfield if it completely overlaps?)
- [x] singulo pull
- [x] containment-gens sharing power
- [X] polish ui (until pjb replaces it)
   - [x] close window if person walks away
   - [x] general ui usability checks
   - [x] close button
   - [x] ui update when pa changes shape
- [x] rework emitter bolts to have a max range
- [x] rework particles to have a max range
- [x] particles should only apply (radiation-)damage to humans/mobs
- [x] particles should pass ~~windows, but not walls~~ EVERYTHING
- [x] particles should charge the singulo
- [x] neighbours should reiterate pa to have a pa split in half if you actually split it in half
- [x] get all values (rads/energy/power) and write em down in the pr so people can complain about unbalanced stuff
- [x] ~~make singulo energy loss per second~~ always has been 🔫 
- [x] reenable emitter need for containment fields
- [x] lower containmentfield max distance to 4.5 (maybe optimize)
- [x] rework pa-code a bit to make it more sane (updating vars & ui)
- [x] center pa parts, emitter & containmentfieldgen on tile on anchor
- [x] wirehack img
- [x] ~~pjb: what if the wiring panel had a physical seven-segment display for the strength~~ not in this pr it wont, i wanna start working on componentdependencies
- [x] audio should always play
- [x] power drain

Stuff to fix from the old pr:
- [x] client crash when the player is deleted by singulo
- [x] no proper sprite animation control for the radiation panel, it just loops the animation over and over regardless of its state
- [x] singulo doesn't eat underfloor objects + some more objs
- [x] audio issue described in the PR description (have singulo play audio even if out of screen)
- [x] change some getcomponents to trygets

### CODE REVIEW

**Comment by Zumorica** [comment]
Overcedes and closes #1548

**Comment by RemieRichards** [comment]
Supersedes, :P

**Comment by DrSmugleaf** [comment]
> Supersedes, :P

Greatercedes

**Comment by Zumorica** [comment]
:pensive:

**Comment by unusualcrow** [comment]
thanks

**Comment by PaulRitter** [comment]
ready for review

**Comment by PaulRitter** [comment]
ah crap it aint done yet...
- [ ] pawirewindow title
- [ ] pa border -> outline component
- [ ] ghost succ
- [ ] pa takes mv over powerbox
- [ ] console takes apc
- [ ] console shutdown -> pa shutdown
- [ ] pa unlit layers
- [ ] add particle focuser thingy

**Comment by PaulRitter** [comment]
ready for merge imo

**Pull request merged**
