### PR TITLE
tweak(cuffs): Make it possible to put someone who is not crit or dead into a strait jacket

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Made it so putting a straitjacket on someone who is stunned takes one less second to do.

## Why / Balance

Without this change it is impossible to put a combative person into a strait jacket unless they are chemically restrained, in critical condition or dead.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
**Before:**

[Screencast from 06-22-2024 09:43:43 AM.webm](https://github.com/space-wizards/space-station-14/assets/103440971/50a36d01-11ea-454b-a7f8-93a9516af478)

**After:**

[Screencast from 06-22-2024 09 35 53 AM.webm](https://github.com/space-wizards/space-station-14/assets/103440971/9e7fd2d5-32bb-4bc4-9bfd-b6e482de3ba9)

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
isn't the intent to make it not possible to put a straitjacket on someone who is knocked down from a baton? I don't love that this essentially allows you to force the most restrictive cuff onto any player by yourself.

**Comment by Brandon-Huu** [comment]
> isn't the intent to make it not possible to put a straitjacket on someone who is knocked down from a baton? I don't love that this essentially allows you to force the most restrictive cuff onto any player by yourself.

How else are you supposed to put it on them without chloral or gunning them down?

**Comment by Brandon-Huu** [comment]
Can I put chloral hydrate into Warden's locker so there's a non-lethal way to put someone in a strait jacket?

**Comment by Brandon-Huu** [comment]
Because right now it really useless unless chem is willing to make chloral for you

**Comment by thebadman4662** [comment]
> isn't the intent to make it not possible to put a straitjacket on someone who is knocked down from a baton? I don't love that this essentially allows you to force the most restrictive cuff onto any player by yourself.

Compared to zipties/makeshift/steel cuffs outright being unable to be broken from when buckled the straitjacket seems merciful.
If someone have access to it chances are they have access to metal cuffs so theres little to no benefit for non-sec to use those except maybe if you manage to loot them from medbay on Origin as antag. Medbay basically have never it mapped but brigmeds/permas on some maps do.

**Comment by keronshb** [comment]
There's absolutely no need to use a straightjacket as cuffs like this.

**Comment by ZA24567** [comment]
i think its more intended to be used in a medical setting after sedating someone with n2o so that you can control potentially rowdy people in medical. i have personally never seen it used though but that's what i think the intended purpose is.

**Comment by thebadman4662** [comment]
> i think its more intended to be used in a medical setting after sedating someone with n2o so that you can control potentially rowdy people in medical. i have personally never seen it used though but that's what i think the intended purpose is.

That requires suit slot so armor/EVA, which is silly requirement for straitjacking prisoners, they need to be simply made go into outer clothing instead of being cuffs on hands.

**Comment by Brandon-Huu** [comment]
> There's absolutely no need to use a straightjacket as cuffs off a stun like this.

If someone is suicidal and needs a less harmful way to be restrained there is.

I had a guy crit me because it was impossible to put the strait jacket on them

**Comment by Brandon-Huu** [comment]
> There's absolutely no need to use a straightjacket as cuffs off a stun like this.

I had them in cuffs, but had to remove them to put the strait jacket on.
Was completely impossible to do so

**Pull request closed without merging**
