### PR TITLE
Lizard name datasets

### PR DESCRIPTION
**Pull request by DogZeroX**
Finally, Lizards will no longer have human names on the randomizer.
Drafted because it needs names to not be hard-coded to human + Randomizing name when changing specie
## About the PR 

**Screenshots**

**Changelog**

:cl:
- tweak: Naming machine fixed, now you can get a reptilian name when clicking randomize on character selection.

### CODE REVIEW

**Comment by ike709** [comment]
\> Names don't follow the normal `Verbs-the-Noun` convention

cringe

**Comment by DogZeroX** [comment]
This is just like TES, you have both Argonian names and Tamrielic. If you want a verb-the-noun just make it yourself.

**Comment by ike709** [comment]
SS13's convention is derived from Tamrielic.

**Comment by metalgearsloth** [comment]
I added species specific naming (30% jank) but want a second opinion on names before touching anything.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
