### PR TITLE
New floors

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
aka "can we have tiles that aren't impossible to modify please thanks"

**Screenshots**
image

**Changelog**
:cl: moony
- add: A whole new tileset to help make future tiles easier to make, and also to reduce the grunge just a little.
- remove: Removed sovl.

### CODE REVIEW

**Comment by moonheart08** [comment]
wheres my di- oh right it's not rsi this is so sad.

**Comment by Emisse** [comment]
absolutely refuse to bikeshed this just merge it and let players decide if they like it

**Comment by EmoGarbage404** [comment]
tbh feeling the same way. Better just to test it out rather than having petty bikeshedding over probably the most insignificant topic imaginable.

**Comment by Visne** [comment]
1. Something every player will be staring at for almost the entire duration of gameplay is not insignificant.
2. There will be many people that dislike such a change anyways, and you will hear it. Good luck figuring out if they are a minority or majority.

**Comment by Kromabae** [comment]
why not both?

**Comment by EmoGarbage404** [comment]
> why not both?

seems weird to have two very similar tiles in the game. Better to choose one or the other.

**Comment by Kromabae** [comment]
to be honest, as long as the game is functional it can legit look liek a 5 year olds crayon drawing of the end of the world for all i care, also ithe tiles dont look that bad just kinda wonder why all of them got this grill pattern to them

**Comment by theashtronaut** [comment]
It might look different when actually in game, but going off the screenshot I'm not a huge fan of the grill pattern/texture on the tiles. It makes them look blurry. Other than that they look great though

**Comment by ike709** [comment]
I really don't like the way this looks tbh.

**Comment by Just-a-Unity-Dev** [comment]
the smooth-tiles & grill pattern feel... off, that's all i have to say at least

**Comment by Peptide90** [comment]
Not as a replacement, possibly as an alternative for marking out depts or whatever. Looks too stylised (yet not?) to be a common floor and or anyone else's comments on blurry / low res.

**Pull request closed without merging**
