### PR TITLE
New Hunger Icons and PDA Name Capitalization

### PR DESCRIPTION
**Pull request by DerbyX**
## About the PR

• Capitalized PDA names
• Redid hunger icons to give more flair and better visuals to indicate the stages of hunger.

**Media**

NewHungryIconPeckish
NewHungerIconStarving
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Derby
- tweak: PDAs names are now properly capitalized.
- tweak: Hunger Icons now give a slightly better indication for the different states of hunger.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i viscerally despise these icons

**Comment by Flareguy** [comment]
These sprites feel out-of-style - their seem illustrated rather then manually sprited, which doesn't seem like a great idea for a 32x32 hud element.

**Comment by JoeHammad1844** [comment]
these icons just suck

**Comment by DerbyX** [comment]
I could redo the icons using the current ones but just add more visual indicators instead

**Comment by DerbyX** [comment]
Made the color more vibrant. An indicator seemed a bit too different with the current live icon.
RevampedHungerIconStarving
RevampedHungerIconPeckish

**Comment by kxvvv** [comment]
image
write `x` inside the cube

**Comment by crazybrain23** [comment]
Also, changing the PDA names should be a separate PR since it's an unrelated change.

**Pull request closed without merging**
