### PR TITLE
Chemistry Rework

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## Chemistry Rework

I'm fully aware this will massively change chemistry, and have gone over it several times with the playerbase in discord, as well as some contributors, maintainers and admins.

All values are subject to change, and I mostly want to see a playtest and how chemistry and doctor players will handle this rework. I'm fully open to responding to and listening to feedback and questions in this github PR. Keep in mind any harsh values are always changeable, as I don't expect this PR to be set in stone by any means.

**I would also like to thank and credit @Slava0135 for letting me use their code from #13794, which allowed me to implement plastic as a ChemMaster resource!**

That being said; here it is!

The Chemistry Rework (All tested in my dev environment)

Pills: 
- can now only be dispensed to 10u, but have a maximum of 15u
    - can have 5u more Solution injected into them to reach the max limit of 15u *(but not pulled)*
    - from aid kits have had their maximum capacity reduced to 15, which are already entirely filled (Dexalin, dylovene, etc..)
- cost plastic at the chemmaster (150 plastic per pill)
- Nerfed digestion speed by 50% (The time it takes for things to get taken into the chemstream, from 20 to 30 seconds)

Bottles:
- have 3 Weight, down from 5
- Doubled bottle capacity - 60u 
- are 50% cheaper at medfab (now 100 glass)

Syringes:
- Self injections now take 2 times longer, rather than 2 times shorter
- Syringes inject faster into others:
- 50% decrease in delay per 5u (from 1 second added to 0.5)
- 25% decrease in delay on crit patients (modifier increased from 2 to 2.5)

Pillbox spawns removed from:
- Wall-mounted medical lockers 
- Medicine lockers 

**FAQ regarding changes**
Q. Why would it be slower? (Syringe self injections)
A. See the comments of #9697. The actual slowdown is only 1.5 seconds longer as well, it won't hurt you, just dissuade you from doing it yourself.

Q. Bottles have 3 Weight, down from 5, as well as the U increase? Why?
A. This makes bottles ideal storages, rather than glasses and beakers. Paramedics will now be able to carry more medicine with them, and inject them more efficiently.

Q. Why do pills cost so much plastic?
A. This will likely be tweaked after a playtest, but ideally should limit the use of pills to people who actually need them, in situations where a brute pack and bed can be used. Not every medical situation needs to be solved with a pill. It also hard limits how many pills chem can make, if they choose to go all in one one chemical rather than making 10 pills of 6 different varieties, or perhaps making 20 pills of the main three damage types. 

Q. Why is the pill capacity so low?
A. Pills of 10u bicard already heal 40 brute. Any higher than that makes all other forms of healing redundant. I've tweaked syringes to be more efficient and configured the bottle capacity to allow for more room in chemical mixing, as well as for handling more critical patients faster to compensate. This change to pills will ideally change doctors mindset to save pills for minor-medium wounds, while extremely minor injuries will be treated with brute packs and a bed, as originally intended.

Q. Why was digestion made slower?
A. Drinking and eating chems shouldn't be made to be stronger than injecting them... in this PR, the most efficient way to deliver chemicals in any scenario is to inject them, which makes sense. It's going directly into your bloodstream instead of being metabolized.  

Q. This doesn't change the underlying issue of infinite medicine creation!
A. No, it doesn't. but it does mitigate the issue. We already have a bigger medical rework coming in, and if you want to consider this a minor fix to medical meta until then, so be it. I'd rather have less medicine being put out than have it remain in it's current state, where pills are free and are put out in batches of hundreds, bottles are useless, and brute packs and beds being rarely used.

Q. Won't players just ask for a syringe to treat themselves or drink directly from the bottles?
A. This is less of an issue with medical design and moreso with how the playerbase interacts with medical content. Now that the costs of medical are a lot steeper, chemists will likely be more careful about who they hand out their stuff too, as resources (bottles and plastic) are now taken into account. I've also accounted for this by nerfing self-injection and drinking, to allow doctors to actually have a chance to do their job.

Q. Why are pills only filled to 10u, but can have 5u injected?
A. It allows for tampering with pills, be it poison or whatnot for syndicates. This is a new feature I added to pills. You could also just mix more chemicals into the pills if you really wanted to.

**Media**

_**This PR may require screenshots/videos. Please give me a list what is needed.**_
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Whisper
- tweak: Pills can now only be dispensed to 10u, but have a maximum of 15u
- add: Pills can have 5u more Solution injected into them to reach the max limit of 15u (but not pulled)
- tweak: Pills from aid kits have had their maximum capacity reduced to 15, which are already entirely filled (Dexalin, dylovene, etc..)
- add: Pills cost plastic at the chemmaster (150 plastic per pill)
- tweak: Nerfed digestion speed by 50% (The time it takes for things to get taken into the chemstream, from 20 to 30 seconds)
- tweak: Bottles have 3 Weight, down from 5
- tweak: Bottles are now doubled bottle capacity - 60u
- tweak: Bottles are 50% cheaper at medfab (now 100 glass)
- tweak: Syringes self injections now take 2 times longer, rather than 2 times shorter
- tweak: Syringes have a 50% decrease in delay per 5u on patients (from 1 second added to 0.5)
- tweak: Syringes have a 25% decrease in delay on crit patients (modifier increased from 2 to 2.5)
- remove: Removed Pill Canister Boxes from wall-mounted medical lockers 
- remove: Removed Pill Canister Boxes from medicine lockers

### CODE REVIEW

**Comment by deltanedas** [comment]
changelog seems really long should be summarized or just "big chem rework"

**Comment by Slava0135** [comment]
> changelog seems really long should be summarized or just "big chem rework"

big chungus
Big_Chungus_%28artwork%29

**Comment by QuietlyWhisper** [comment]
> changelog seems really long should be summarized or just "big chem rework"

While I can shorten it, its important for medical players to be aware of the exact changes to the medical gameplay

**Comment by deltanedas** [comment]
the last 2 can be combined easily

**Comment by 0x6273** [comment]
> tweak: Bottles have 3 Weight, down from 5

Small beakers are size 5 and hold 50u, and big beakers are 10 and hold 100u. If bottles are 60u now, then the size should be somewhere between small and big beakers.

> remove: Bottles cannot be drunk anymore

This makes no sense at all?

> tweak: Syringes self injections now take 2 times longer, rather than 2 times shorter

Neither does this. Why would it be slower?

**Comment by QuietlyWhisper** [comment]
@0x6273 
I'll start writing down FAQ for this pr, a lot of people are asking the same questions

**Comment by QuietlyWhisper** [comment]
I'm also adding drinking back so that change can be disregarded

**Comment by QuietlyWhisper** [comment]
PR has been updated to include FAQ.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
This is a terrible idea. Especially as a "temporary" change.

**Comment by QuietlyWhisper** [comment]
Fyi for anyone in the discord that doesnt know how guthub works, this pr is closed and will not be added to the game. Moony and I have discussed what to keep however, and so far the pill unit limit and syringe changes will remain

**Comment by QuietlyWhisper** [comment]
While that wont fix chemistry ability to make pills at no material cost, like glass for bottles, syringes will hopefully be more viable in normal gameplay

**Pull request closed without merging**
