### PR TITLE
Speeds up Airlocks

### PR DESCRIPTION
**Pull request by SweptWasTaken**
I thought the airlocks were super sluggish without a real need for them to be. I halfed their open/close times and I think they look much snappier, plus they mesh with the airlocks "when it lets you through" state much better. 

Only modified the basic airlock in-case this pr in case it gets shot down immediately. 

Comparison of different timings. (Blue is original timing, Green is quicker timing)

### CODE REVIEW

**Comment by PJB3005** [comment]
I like it.

**Comment by AJCM-git** [comment]
\>hasnt died because the airlock didnt open in time

**Comment by SweptWasTaken** [comment]
Ok i'll go through and edit all the airlocks. This should be ready for merge next commit.

**Comment by SweptWasTaken** [comment]
Added everything except for the external airlocks, since I think they're weightiness is warranted. Walking around the station during testing was so nice.

**Comment by SweptWasTaken** [comment]
Updated the C#. Put it at 0.8f from 1.2f it feels ok to me but could need some tweaking.

**Pull request merged**
