### PR TITLE
Guidebook updates for Antagonist entries

### PR DESCRIPTION
**Pull request by UBlueberry**
## About the PR

Updates all antagonist guidebook entries and somewhat makes their quality consistent. This is a less broad version of #28795, which I have decided to close so everything is cleaner and isn't a big mess. This is JUST for antagonists.
## Media

image
image
image
image

image
image
image
image
image

image
image
image

image
image
image
image
image

image
image
image

image
image

image
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The guidebook entries for all antagonists have been revised.

### CODE REVIEW

**Comment by Aeshus** [comment]
I’m not sure that listing specific objectives for traitors is a good idea.

1. It adds to the maintenance burden since any new objectives would require updating the guidebook (unless it’s explicitly stated that the guide isn’t an exhaustive list).
2. It now serves as a prime metagaming resource as it explicitly outlines what suspicious behaviors certain antagonists might engage in.

I think it would be better to replace the list with only the categories of objectives (e.g., steal/murder or maroon/help/survive/die a glorious death). 

The guide could then focus on explaining how traitors could approach completing these categories of tasks and highlight important things (e.g., avoiding mass damage or mass murder, clarifying the difference between marooning and murder, how to establish contact with someone they’re helping, etc.).

**Comment by UBlueberry** [comment]
I understand the maintenance burden but now that all of the traitor objectives have a big fat "The Syndicate wants to steal this" text line when you examine it, I don't think having the same list in the guidebook does any extra harm. Maybe I'm misremembering something, I'll have to check

I'll come back to the Traitor entry regardless to rewrite the objectives part

**Comment by UBlueberry** [comment]
I didn't write too much about how to do tasks but its a little cleaner now

**Comment by Dutch-VanDerLinde** [comment]
no thief guidebook?

**Comment by UBlueberry** [comment]
i can't believe that has never crossed my mind

**Comment by Emisse** [comment]
seems fine

**Comment by UBlueberry** [comment]
oops was gonna push one more thing but i'll make a new pr for that

**Pull request merged**
