### PR TITLE
Riot crate overhaul

### PR DESCRIPTION
**Pull request by nomad0260**
## About the PR

Now Security can't make war crimes with riot kit

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: no_mad
- tweak: Replace Enforcer in riot crate to non-lethal

### CODE REVIEW

**Comment by nomad0260** [comment]
Who buy a non-lethal kit (i remember for you, this riot crate, not anti-xenos) in xeno invasion?
For this have a shotguns and smgs crate

**Comment by deltanedas** [comment]
oh yeah theyre separate, good change then

**Comment by metalgearsloth** [comment]
We're not interested in PRs from bigots.

**Comment by nomad0260** [comment]
> We're not interested in PRs from bigots.

double standards

**Comment by S1ss3l** [comment]
This would need a lot more context for us non discord lurker but, is that a desirable change or not ? If it is I can make another pr myself.

**Pull request closed without merging**
