### PR TITLE
UI Additions: New Radial UI

### PR DESCRIPTION
**Pull request by DocNITE**
## About the PR
Reopen from that [PR](https://github.com/space-wizards/space-station-14/pull/18110#event-9973964856) with solved "problems"

### CODE REVIEW

**Comment by dmnct** [comment]
Why not just reopen that PR?

**Comment by DocNITE** [comment]
> Why not just reopen that PR? (I guess it doesn't matter now, but just for future reference)

Well, i can't reopen (i deleted branch before, so i reopen a new pr)

**Comment by juliangiebel** [comment]
You didn't delete the branch from your repository, otherwise it would say so ins the PR history of your previous PR.
Please merge the branch from this PR onto the branch from your previous one and reopen it.

**Comment by noverd** [comment]
why

**Pull request closed without merging**
