### PR TITLE
make pulled uncuffing slower & reduce uncuff spam cooldown

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

A more modest version of #28991 

Makes it so that people who are currently being pulled by someone have a 2x slower uncuff speed (30s).
Also reduces the 30 second cooldown to 3.

## Why / Balance

Makes performing sec duties with prisoners significantly easier by making the cuffing much less infrequent by increasing the duration of the doafter. you can still escape but it's gonna take a longass time and sec will have a comical amount of time to block it.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Attempting to uncuff oneself while being pulled will now take twice as long.
- tweak: Reduced cooldown after attempting to uncuff oneself back to previous values.

### CODE REVIEW

**Comment by keronshb** [comment]
Being able to still hit the uncuff button while being pulled is super intended. It's made that way so people do need to pay attention to the person they're dragging around (or bucklecuffed).

**Comment by EmoGarbage404** [comment]
> It's made that way so people do need to pay attention to the person they're dragging 

i mean considering that dragging someone literally physically links the two together, slows you down, and takes up a hand slot, i don't really see how you'd be doing so and ignoring the person. This is mostly a buff to allow sec to actually transport and do stuff with prisoners without having to constantly smack them or drag them around to repeatedly stop the doafter when they're in the middle of something.

**Comment by Plykiya** [comment]
if you're pulling them you're not forgetting them, so I like this more than the other proposed solution
now you can actually one-man implanter check someone without killing them

**Comment by Djungelskog2** [comment]
I could agree with adding a decently short time of ~10 seconds since uncuffing yourself actually hurries security along with processing, and this also feels extremely boring from a prisoner point of view. Being unable to uncuff yourself in any situation feels super shitty because it limits your input and makes you feel like people are wasting your time even more than it normally would. (Also ssd people can still drag you IIRC, so you could be dragged into a random corner of maints and have your kidnapper go sad or catatonic and your softlocked unless someone finds you)

**Comment by Djungelskog2** [comment]
Also just punching your prisoner till they stop trying to uncuff themselves is a completely valid method to stop players who do this

**Comment by thebadman4662** [comment]
Yeah but then admins give you funny looks and mutter something about rolebans. 😭

**Comment by Djungelskog2** [comment]
> > It's made that way so people do need to pay attention to the person they're dragging
> 
> i mean considering that dragging someone literally physically links the two together, slows you down, and takes up a hand slot, i don't really see how you'd be doing so and ignoring the person. This is mostly a buff to allow sec to actually transport and do stuff with prisoners without having to constantly smack them or drag them around to repeatedly stop the doafter when they're in the middle of something.

If they are physically moving it automatically gets cancelled, and if they're doing anything other than just being processed or being in med while standing still, sec deserves to be kept on their toes for not doing their job 
And if they're trying to escape while being searched or similar your job is to actively watch over those prisoners to make sure they don't do stuff like that.

**Comment by keronshb** [comment]
> > It's made that way so people do need to pay attention to the person they're dragging
> 
> i mean considering that dragging someone literally physically links the two together, slows you down, and takes up a hand slot, i don't really see how you'd be doing so and ignoring the person. This is mostly a buff to allow sec to actually transport and do stuff with prisoners without having to constantly smack them or drag them around to repeatedly stop the doafter when they're in the middle of something.

It's not that you're ignoring the person in the sense that you aren't holding them, but think of it like "i'm the guard, distracted with processing, meanwhile the person that I'm pulling is doing X to break out of their cuffs" like a spy movie or something.

So if the guard is smart enough and paying attention, they can notice their prisoner is trying to escape and just shift them a bit to  stop it. But if they're too engrossed in multitasking, it's their fault that they didn't stop the uncuff attempt.

This also plays into the idea of having more officers the better.

**Comment by EmoGarbage404** [comment]
changed the full blockage to just a 2x modifier to the duration.

hopefully this still retains the balance between the ability to escape and not annoying the everloving god out of secoffs just trying to do basic tasks.

**Comment by Djungelskog2** [comment]
Yea sounds good

**Review by ShadowCommander — COMMENTED** [review]
Looks good. I suggest changing the CL to:
- tweak: Attempting to uncuff oneself while being pulled will now take twice as long.
- tweak: Reduced cooldown after attempting to uncuff oneself back to previous values.

**Pull request merged**
