### PR TITLE
Updated ContainerHelpers to use new extensions

### PR DESCRIPTION
**Pull request by DTanxxx**
There is also a pull request made to RobustToolBox to include the new extension.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Fixes #2510

**Comment by DTanxxx** [comment]
Hi Project Manager(s),

Regarding the failed build test, I looked into the repo and saw that the submodule RobustToolbox points to the RobustToolbox at branch fd93fcb, which does not have the changes by the commit:
[https://github.com/space-wizards/RobustToolbox/pull/1389](url)

Instead, only the master branch has been updated, so this commit fails as it uses the new extensions. Is there a way to update the branch fd93fcb? Thanks.

**Comment by metalgearsloth** [comment]
> 
> 
> Hi Project Manager(s),
> 
> Regarding the failed build test, I looked into the repo and saw that the submodule RobustToolbox points to the RobustToolbox at branch fd93fcb, which does not have the changes by the commit:
> [https://github.com/space-wizards/RobustToolbox/pull/1389](url)
> 
> Instead, only the master branch has been updated, so this commit fails as it uses the new extensions. Is there a way to update the branch fd93fcb? Thanks.

Merge from the latest master and it should be okay.

**Comment by DTanxxx** [comment]
I don't think I have access to branch fd93fcb as it doesn't show up on the list of drop down branches, neither in the actual project nor my fork. I could only look into that branch if I click on RobustToolbox module from the space-station repo itself (with the @ sign next to RobustToolbox folder showing the branch). So I'm not too sure how to merge master into that branch.

**Comment by metalgearsloth** [comment]
It doesn't need the branch if you just merge from master. I hadn't pushed a submodule update for smug's thing at the time (but we have since done one).

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
