### PR TITLE
Industrial Reagent Grinder

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Added an industrial reagent grinder, that works like a recycler(can use conveyors). It mass-grinds things, at the cost of only being 0.9 times as efficient. It's researchable in the hydroponics research
## Why / Balance

>Botany grows produce for chem
>Lot of produce
>Chem can't grind it all
>Work goes to waste
This allows for rapid grinding of plants, causing the chem-botany teamwork to grow. 
factorio real
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Boaz1111
- add: Added an industrial reagent grinder to the basic hydroponics research. It grinds things into reagents like a recycler.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
How does it work

I'd rather a material reclaimer since it grinds as you put stuff in, then you remove solutions from it with a beaker

**Comment by Boaz1111** [comment]
> How does it work
> 
> I'd rather making material reclaimers buildable since it grinds as you put stuff in, then you remove solutions from it with a beaker

that's exactly how this works

**Comment by Kadeo64** [comment]
>Botany grows produce for chem
>Lot of produce
>Chem can't grind it all
>Chem/Bot asks science for cool tech
>"We're rushing experimental go away"
>Work goes to waste anyway

**Comment by K-Dynamic** [comment]
> that's exactly how this works

I see, that'e convenient then; I thought there'd be a UI like that of regular reagent grinder

**Comment by Carmell0** [comment]
ITS FINALLY REAL IVE BEEN ADVOCATING FOR THIS THING FOR MONTHS

**Comment by Boaz1111** [comment]
I KNOW YOU INSPIRED ME TO MAKE THIS

**Comment by Aisu9** [comment]
what is the point of the industrial reagent grinder when you can use a material reclaimer? you wont have material lost and you will grind items instantly

**Comment by Kadeo64** [comment]
> Why make it less efficient? It's kind of counter intuitive and encourages using the earlier machine to optimize instead, I'd look for another downside like the other machines do, such as waste heating issues.

I think at the point you **_need_** this machine you probably have enough plants on your counter to let some of their chems go to waste. If you only have 3 deus leaves you want to get as much omnizine out of them as possible but when you have 20 leaves you just want to get it over with.

**Comment by deltanedas** [comment]
entirely countered by eggs existing
just crack into bucket and dump into chemmaster

**Comment by K-Dynamic** [comment]
> entirely countered by eggs existing just crack into bucket and dump into chemmaster

Ideally we're trying to get away from that since it adds another rng step to botany, especially if there is a better grinder for both chef and chem

**Comment by UbaserB** [comment]
where is the photo/video showcasing it

**Comment by Kadeo64** [comment]
> where is the photo/video showcasing it

it's just a material reclaimer but reskinned

**Comment by Kadeo64** [comment]
> entirely countered by eggs existing just crack into bucket and dump into chemmaster

eggmeta is annoying

**Comment by deltanedas** [comment]
this is just a worse material reclaimer theres no reason for this to be made

**Comment by UbaserB** [comment]
> this is just a worse material reclaimer theres no reason for this to be made

simple solution, make it work better for plants and not work for anything else

**Comment by Boaz1111** [comment]
Yeah I'm probably going to tweak it to 
1. Make it work like a recycler(conveyor belt real)
2. Up the efficiency to like 1.0 or 1.1?

**Comment by deltanedas** [comment]
conveyor belt real would make it god tier for auto egg since its now fully automated

**Comment by Fildrance** [comment]
New sprite and disable processing of anything but plants, or bust!

**Comment by Boaz1111** [comment]
> New sprite and disable processing of anything but plants, or bust!

I'd rather a maintainer give their review on the concept in general as well as if it really needs a new sprite.

**Comment by metalgearsloth** [comment]
sure ig

**Pull request merged**
