### PR TITLE
[Tweak] Change minimum player count for nukeops from 20 to 15

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

A change for sala, hopefully this means more nukie rounds.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: You know only need 15 people for a nukeops round.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
If nukeops spawns at 15pop isn't that just a loneops at that point?

**Comment by deltanedas** [comment]
roundstart loneops with starting c4

**Comment by Aisu9** [comment]
it's possible to allow this lowpop threshold only if there is a Warden/HoS/Captain or QM on board? i wont lie if the station is filled with civilian/service your just better of starting the round with a triggered nuke grenade

**Comment by OctoRocket** [comment]
I don't really think there is a way to check who is onboard, and yeah it would be a lone op.

**Comment by AJCM-git** [comment]
> I don't really think there is a way to check who is onboard, and yeah it would be a loneop.

then there is not really a lot of purpose for this right?

**Comment by OctoRocket** [comment]
Well it would still allow for nukies to happen, and if I remember correctly loneops only start to spawn near the end of the round and I basically don't see them at all.

**Comment by OctoRocket** [comment]
Any more criticism?

**Comment by AJCM-git** [comment]
> Any more criticism?

Well this would just make nukies a more common loneop in lowpop, if the problem is that loneops starts too late then that is the thing that should be changed, not this

**Comment by OctoRocket** [comment]
That is probably true, maybe they can spawn after 30 minutes? There is also the issue that having someone permadie on lowpop is hard unless they were killed by a syndie because they often speedrun cloning tech if someone dies.

**Pull request closed without merging**
