### PR TITLE
1x2 cable coils

### PR DESCRIPTION
**Pull request by Killerqu00**
## About the PR

1x2 cable coils

## Why / Balance

1x2 cable coils

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Cable Coils are now small in size, taking only 1x2 space in containers.

### CODE REVIEW

**Comment by DogZeroX** [comment]
Should adjust the sprite so it matches the grid

**Comment by Killerqu00** [comment]
> Should adjust the sprite so it matches the grid

most sprites in the game do not match the grid at all

**Comment by DogZeroX** [comment]
That's why you manually adjust it to make it match so it looks good

**Comment by Killerqu00** [comment]
> That's why you manually adjust it to make it match so it looks good

Well, I could, but there are multiple sprites, meaning that I would have to delete the old ones and make new ones.
If that's actually needed, I can do that.

**Comment by potato1234x** [comment]
> Well, I could, but there are multiple sprites, meaning that I would have to delete the old ones and make new ones. If that's actually needed, I can do that.

afaik you can just specify inventory orientation

**Comment by PJB3005** [comment]
Yeah even just rotating it 90 degrees, which some items do for gridinv, would help.

**Comment by Killerqu00** [comment]
> Yeah even just rotating it 90 degrees, which some items do for gridinv, would help. 

got it, will do

**Review by PJB3005 — DISMISSED** [review]
You can just set `storedRotation: -90` on the item component, don't change the actual sprites.

**Pull request merged**
