### PR TITLE
salvager maxim suit

### PR DESCRIPTION
**Pull request by Emisse**
need for expedition rare reward, endgame armor

image

no cl since not available yet

### CODE REVIEW

**Comment by MACMAN2003** [comment]
imagine returning to the station with your crew kitted out and everyone screams "NUKIES" after seeing you :clueless:

**Review by metalgearsloth — APPROVED** [review]
vox lookin ass

**Comment by K-Dynamic** [comment]
Maybe make them gold or diamond-coloured to avoid bloodred confusion

**Comment by EmoGarbage404** [comment]
Bloodred hardsuit is when there is color red

**Comment by GreyMario** [comment]
can I get that with a side of powercreep

**Comment by K-Dynamic** [comment]
> Bloodred hardsuit is when there is color red

Sec hardsuits were resprited to avoid nukie confusion, and they had even less red

**Pull request merged**
