### PR TITLE
nuke biochem

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- chemistry -> roundstart except chem payload (explosives)
- surgical tools -> roundstart
- biochemical stasis moved to civilian t2 to flesh it out more, includes cryo pod now
- mechanized treatment moved to civilian t2, includes adv treatment now
- cryopod combined with biochemical stasis
- biofabrication combined with meat manipulation
- chem dispensery -> roundstart, adv treatment moved to mechanized treatment
- bluespace chemistry -> civilian still t3

chemical goggles roundstart since if you are pro you dont need them anyway + its not op enough to justify a dedicated tech and none other really fit it. also added it to medfab since new chemists might use it
also added nitrile gloves to medfab roundstart since no tech added it and its just drip

## Why / Balance
death

## Technical details
no

## Media
protolathe starts with basic chemistry gear (so does medfab)

surgery real

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Dissolved the biochem technology discipline into others and roundstart availability.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
if we're going to continue gutting the biochemistry discipline it might make sense to just remove it at this point. As it stands, it essentially has nothing in and would be better off just dispersed into civilian services.

**Comment by deltanedas** [comment]
future pr i cannot be responsible for outright deleting the discipline thats even more unwanted than arsenal :trollface:

**Comment by EmoGarbage404** [comment]
> future pr i cannot be responsible for outright deleting the discipline thats even more unwanted than arsenal :trollface:

statistically they were equivalent like a few weeks ago but just do it in one PR because there's no point in this long drawn out death march where we obliterate every unlock in the discipline one-by-one.

**Comment by deltanedas** [comment]
rest in piss wont be missed :trollface:

**Pull request merged**
