### PR TITLE
Saltern: Add antimatter and singularity engine rooms

### PR DESCRIPTION
**Pull request by 20kdc**
Adds rooms for antimatter and singularity engines.

# Questions people haven't yet asked, but will

## Where is stuff?

https://user-images.githubusercontent.com/22304167/102420159-617e3600-3ff9-11eb-9980-365d11be0988.png

North-east of Engineering is the place where the AME room is.

South of gravity generator is the place where the Singularity Engine is.

## Why aren't there AME crates?

They caused PVS crashes. Seriously. Add them to the map for yourself (there's a place specifically for them in the north-west of the AME room), then go walk around the gravgen.

## Why isn't there an unfinished Particle Accelerator?

Every time, without fail, when I setup the PA, the singularity either evaporates or gets loose. And it usually makes a beeline for the PA, which then crashes the server if in debug.

## Why does the singularity keep eating the field generators?

I don't know.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Looks ok, could do with some catwalks around the actual singularity structure. You should also add a spare-parts room for the singularity and AME. Spare emitter, fuel tanks for AME etc.

**Comment by 20kdc** [comment]
I'm kind of assuming the spare parts room already exists (the room filled with secure crates north of engineering).

**Comment by SweptWasTaken** [comment]
> 
> 
> I'm kind of assuming the spare parts room already exists (the room filled with secure crates north of engineering).

Throw some spare engine parts in there then.

**Review by metalgearsloth — APPROVED** [review]
I couldn't replicate the crash on my end.

**Pull request merged**
