### PR TITLE
New wooden furniture

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR
Adds craftable high and small fences, wooden bench. New stairs.

## Media
woodenFur

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Ko4erga
- add: Added craftable high and small wooden fences, bench. New stairs.

### CODE REVIEW

**Comment by TheShuEd** [comment]
Old wooden counter now looking ugly :trollface:

**Comment by TheShuEd** [comment]
I love it

**Comment by pigeonpeas** [comment]
the fences remind me of project zomboid, very silly, i like

**Comment by UbaserB** [comment]
can you add pews for the chapel

**Comment by potato1234x** [comment]
> the fences remind me of project zomboid, very silly, i like

this is exactly what i thought

**Comment by musicmanvr** [comment]
the poop stairs :trollface:

**Comment by Ko4ergaPunk** [comment]
> can you add pews for the chapel

I can't make furniture longer than one tile :c

**Pull request merged**
