### PR TITLE
Make sale console anti-shitters

### LINKED ISSUE #26952: sell consoles on trade post should be undesctructible
i had situation when dragon spawned on trade post and carps broke both consoles

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

make sale console undesctructable and unconstructable
resolves #26952

if its not the right way to change the components, please tell me

## Why / Balance

anti-shitters

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Sale consoles can no longer be deconstructed or broken

### CODE REVIEW

**Comment by Killerqu00** [comment]
consider that this also influences nukies, since breaking ATS is a popular tactic

**Comment by Cojoke-dot** [comment]
Mmmeeeehhhh… I don't like indestructible things… also you could just unanchor it and throw it into deep space still, this ain't going to stop someone from taking out the ats

**Comment by Holykittens** [comment]
You could make it so its possible to damage but not destroy the consoles, then make them repairable.
This allows Antags to disrupt cargo with out basically rendering them toothless.
Some one will need to go out to ATS with tools/materials (probably glass/lv cable) and fix it to get things running again.

**Comment by slarticodefast** [comment]
Test fail is real. Maybe making it repairable makes more sense, so you can still sabotage the ATS, but not permanently. Or add a backup circuit board in the QMs locker (that's what we did with the other irreplacable machines at least).

**Pull request closed without merging**
