### PR TITLE
Musician's skirt

### PR DESCRIPTION
**Pull request by JustArt1m**
## About the PR
The female version of the musician's clothes.

## Why / Balance
Just for more customization.

## Media
MusiciansSkirt_prewiew

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Just_Art
- add: Added a musician's skirt!
- add: Added musician's clothes to AutoDrobe!

### CODE REVIEW

**Comment by lzk228** [comment]
the skirt looks too short

**Comment by UbaserB** [comment]
I feel the sprite as it is, is too unfitting

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
The dithering and very saturated purple colors stick out in relation from the other clothing in game. I'd rather this just be an adjustment of the regular musician suit with a skirt, like most other jumpskirts.

**Review by Flareguy — COMMENTED** [review]
I would probably remove the "drooping" part of the tuxedo that leaks into the skirt area, it looks kind of odd here and doesn't make much sense.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Needs updating for loadout + don't put it on the vendor.

**Comment by JustArt1m** [comment]
> Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

Please reopen my PR.

**Pull request closed without merging**
