### PR TITLE
introduce Bleed alert

### PR DESCRIPTION
**Pull request by Phill101**
## About the PR
#18281
This PR adds a new AlertType - `Bleed` which is updated on `BloodstreamSystem.TryModifyBleedAmount`

**Media**
g4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Phill101
- add: Added bleeding status icon

### CODE REVIEW

**Comment by PrPleGoo** [comment]
Looks good but I'm not sure I agree conceptually. 

Shouldn't the alert icon be showing you how much blood you have left? 
In that case the switch you have now can be simplified and change the alert message instead. 

The icon can be picked based on the percentage of blood you have left.

**Comment by Just-a-Unity-Dev** [comment]
> Shouldn't the alert icon be showing you how much blood you have left?
In that case the switch you have now can be simplified and change the alert message instead.

not sure how a human person can deduce how much blood they have in their body by simply looking at a wound

**Comment by PrPleGoo** [comment]
> not sure how a human person can deduce how much blood they have in their body by simply looking at a wound

Ever hear of people reporting wooziness after donating blood? 
Not sure why you would assume that people need to look at something to deduce the alert.

**Comment by Phill101** [comment]
Replaced switch with Math.Round and Math.Clamp as it was suggested in Discord.
And also I scaled the initial icon. See the updated gif.

**Comment by UbaserB** [comment]
i know this is already merged, but the fact that the size of the pixels doesnt match the other icons hurts me

**Comment by Emisse** [comment]
the codebase is open source and anyone can contribute

**Comment by UbaserB** [comment]
i mean i was already thinking of maybe changing it myself but idk if i have enough motivation so we’ll see

**Pull request merged**
