### PR TITLE
vox voices revamp

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Replace vox voices with less shrill ones

## Why / Balance
Some people find the current ones unbearable,  #31612 was about to turn them off
With the high frequencies toned down and some hiss added, they somewhat retain their current character without being so ear-piercing

## Media

https://github.com/user-attachments/assets/3ff0989a-9fb5-4cfc-b9ee-9dea18493e1d

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: Vox sounds are now less unbearable.

### CODE REVIEW

**Comment by UbaserB** [comment]
cute

**Comment by Hanzdegloker** [comment]
laugh is a lil quiet, but is good overall

**Comment by engineer-pearl** [comment]
Thank you for retaining the vibe. These are definitely sounds that go well with my "I AM YELLING ALL THE TIME!" vibe.

**Comment by Dutch-VanDerLinde** [comment]
why does the laugh sound like he has a muffle on his face

**Comment by Errant-4** [comment]
I am testing some alternate laughs that are less underwater

**Pull request merged**
