### PR TITLE
Cryogenic Sleep Units

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds cryogenic storage units, a safe way for players to exit (or even enter) the round in a way that doesn't involve sitting on a bed in dorms.

When inside cryostorage, your body is safely stored so you don't have to worry about someone taking your belongings and your job slot is opened so that someone else can have your role.

## Why / Balance

Players going SSD in random hallways is a big issue and generally makes the game feel shitty. People who aren't playing should be out of sight and mind. Not clogging up dorms.

Adding back in the job slots also means that rounds don't die in pop as all the job slots get taken as people refuse to log out of the game.

## Technical details

Cryostorage players are saved on a pause map and the console included allows you to retreive their stuff.

## Media

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added cryogenic sleep units. Disconnecting or ghosting inside one of these pods will keep your body secure and free up your job slot on the station.
- add: Added cryogenics access, which allows someone to retrieve items from inside of cryogenic sleep units. This is given to security and command by default.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Cryo good

How does this affect kill/maroon or item objectives

What happens if you carry a mob or player in your inventory

Can just about anyone take your items

**Comment by Emisse** [comment]
can a player drag another currently connected player into this

**Comment by EmoGarbage404** [comment]
> can a player drag another currently connected player into this

yes. should that be changed?

**Comment by Emisse** [comment]
yes you should only be able to drag disconnected players or yourself into it

**Comment by EmoGarbage404** [comment]
> yes you should only be able to drag disconnected players or yourself into it

i mean if you drag a connected player in they have 5 minutes to decide to get out so i don't think it's a huge issue. You also can't lock people in or anything.

**Comment by Emisse** [comment]
alright

**Comment by Emisse** [comment]
if they reconnect will the latejoin sleepers spit them out

**Comment by K-Dynamic** [comment]
> > yes you should only be able to drag disconnected players or yourself into it
> 
> i mean if you drag a connected player in they have 5 minutes to decide to get out so i don't think it's a huge issue. You also can't lock people in or anything.

Does this include people who are incapacitated (no2, critted or dead)

**Comment by Emisse** [comment]
yea that as well

**Comment by EmoGarbage404** [comment]
as it currently works, you only rejoin if the global rejoining is enabled. I can make it so that dead/incapacitated bodies can't be inserted into cryosleep, tho.

**Comment by Emisse** [comment]
dead or incapacitated ssd players should be able to, just make it so currently connected players cant be put in

**Review by Emisse — CHANGES_REQUESTED** [review]
what i said above

**Comment by mirrorcult** [comment]
agree with emisse too many potential issues with being able to force non ssd people in

**Comment by Aisu9** [comment]
can you retrieve someone sleeping in?(disconnected of course) what happen if someone blow up the unit with people in?
(this also better not have an emag interaction)

**Comment by Emisse** [comment]
no

the cryopod should be immortal

**Comment by EmoGarbage404** [comment]
the cryopod is immortal and i'm removing the emag effect now (god i hate emags being tied to accessreader)

**Comment by K-Dynamic** [comment]
> can you retrieve someone sleeping in?(disconnected of course) what happen if someone blow up the unit with people in? (this also better not have an emag interaction)

I'd rather cryopods be treated as off-limits like stations arrivals and its shuttle

**Comment by SonicHDC** [comment]
Wait, what's happen if you disconnect or your internet blow up? Another player will place your body in cryosleeper? You just deletes and cant return in body without rejoining? Or you can?

**Comment by EmoGarbage404** [comment]
with the last commit, you can no longer drag in characters who have a mind and you cannot emag cryogenic units to remove the access. And, for posterity, the units have always been fully invincible.

**Comment by Aisu9** [comment]
> with the last commit, you can no longer drag in characters who have a mind and you cannot emag cryogenic units to remove the access. And, for posterity, the units have always been fully invincible.

are the person sleeping in also impervious to damage or not? in the limited case were people come back before the 5 minutes after either internet or electricity get cut

**Comment by SonicHDC** [comment]
> > with the last commit, you can no longer drag in characters who have a mind and you cannot emag cryogenic units to remove the access. And, for posterity, the units have always been fully invincible.
> 
> are the person sleeping in also impervious to damage or not? in the limited case were people come back before the 5 minutes after either internet or electricity get cut

Most strange, on ui screen written "Body removed when disconnect". What if i leave game or reconnect and will be transported in unit, when out of game? Maybe don't remove a body when disconnected?

**Comment by mirrorcult** [comment]
if you leave the game for long enough for someone to notice, put you in a cryopod, and then have the timer run down then you werent playing the round anyway

**Review by Emisse — APPROVED** [review]

**Comment by deepdarkdepths** [comment]
What happens if you return to the game after your body is gone? Are you unable to play again or can you rejoin the round like normal?

**Comment by Hrosts** [comment]
> dead or incapacitated ssd players should be able to

Wouldn't this make it an impervious anti-Revenant measure, in addition to making morgue partially obsolete?

**Pull request merged**
