### PR TITLE
Space Carp Rework

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changed space carp sprite, removed glow in the dark teeth, removed gib in files (not used anyway and is ugly)
I've also removed some excess code that is handled via SimpleSpaceMobBase

**Media**

image
newerfishe

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed space carps visually. Grrrr!

### CODE REVIEW

**Comment by deltanedas** [comment]
fishe ate too much food, now he is fat

**Review by keronshb — CHANGES_REQUESTED** [review]
I think these are a bit too beefy for my liking and they do seem slightly out of place when put next to Magicarp and Holocarp. But I do think they would work well as an alternative sprite or spawn? SS13 had a handful of fishe that spawned in with space carp and carp events (big shark like carp, regular carp, etc). Could you add these as alternative spawns?

image

**Comment by moonheart08** [comment]
Frankly I don't like these at all, even as alt spawns. They look out of place.

**Comment by moonheart08** [comment]
After a bit of discussion, we've concluded we don't intend to use these sprites, even as alternates.

**Pull request closed without merging**
