### PR TITLE
Inspector Coat and Brown Fedora Tweak

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes the palette and tweaks the sprite to be neater

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:Alekshhh
- tweak: Changed brown fedora and inspector's coat palette and minor adjustments

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I think you unintentionally changed the Detective coat instead of the inspectors coat. 

I would prefer if the design on the detectives coat stayed the same since its a twin peaks reference.

**Comment by GoodWheatley** [comment]
As someone who frequently plays detective, I feel like these sprites look a lot blander and flatter compared to the old ones. Also changing the coat loses the twin peaks reference.

**Comment by Alekshhh** [comment]
it was the inspector coat mb gang

**Comment by GoodWheatley** [comment]
> it was the inspector coat mb gang

Yeah, but the sprite you modified is the detective trenchcoat, not the inspector coat

**Comment by Alekshhh** [comment]
no the fuck it ain't

**Comment by GoodWheatley** [comment]
> no the fuck it ain't

I've played detective for 100 hours I know which coat is which

**Comment by Alekshhh** [comment]
mate
image

**Comment by GoodWheatley** [comment]
> mate image

then why are you modifying detective.rsi????

**Comment by Alekshhh** [comment]
we call that a skill issue in our field

**Pull request merged**
