### PR TITLE
Added my own readme

### PR DESCRIPTION
**Pull request by PunkKeroro**
## About the PR

Adds a text file MY_README.txt

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by juliangiebel** [comment]
Why?

**Comment by PunkKeroro** [comment]
Sorry i'm goin through the docs.spacestation14.io/getting-started/git Learning about Git and going through the steps.

I did step 5.2  I did not realize it was actually going to make a pull request to the space-wizards/space-station-14 Repo

**Comment by deltanedas** [comment]
:trollface:

**Comment by juliangiebel** [comment]
> Sorry i'm goin through the docs.spacestation14.io/getting-started/git Learning about Git and going through the steps.
> 
> I did step 5.2 I did not realize it was actually going to make a pull request to the space-wizards/space-station-14 Repo

No problem. Good luck with learning git 👍

**Pull request closed without merging**
