### PR TITLE
Remove all command age requirements

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Removes the age requirements from command jobs

## Why / Balance

From what I can tell this was merged with this on accident.

Maintainers see the maint review thread on this.

The original pr also claimed this was as an example. #30347

In my opinion wizden should not have an age requirement for command.

Note to everyone: FORKS CAN REVERT THIS, this pr is being made for wizard den and targeting the LRP servers

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: Vasilis
- tweak: Removed the age requirement for command jobs.

### CODE REVIEW

**Comment by Ertanic** [comment]
Maybe you should have just made it a matter of disabling the age restriction via cvar?

**Comment by VasilisThePikachu** [comment]
> Maybe you should have just made it a matter of disabling the age restriction via cvar?

Are you concerned about forks? Forks may revert this with git if it gets merged.

**Comment by superjj18** [comment]
Nepo-baby command member update pog

Why yes my father is a CC official, that's how I became a captain at 18

**Comment by Moomoobeef** [comment]
captain at 17 :skull:

**Comment by 0x6273** [comment]
> From what I can tell this was merged with this on accident.

No, that PR has a changelog entry so it's definitely not an accident.

> In my opinion wizden should not have an age requirement for command.

"In my opinion" is not a very good explanation for making a change like this. Could you explain why do you hold that opinion?

**Comment by VasilisThePikachu** [comment]
> > From what I can tell this was merged with this on accident.
> 
> No, that PR has a changelog entry so it's definitely not an accident.
> 
And it was in an RP way, which goes against our policy. Anyhow, in the pr description you can see how it's explained to be "As an example". Internal maintainer review noticed this as well after being merged. With the idea that it would be fine to revert this if it ended up being a problem.

Along with that, something else was amiss during the review of this pr, which I will cover next

> > In my opinion wizden should not have an age requirement for command.
> 
> "In my opinion" is not a very good explanation for making a change like this. Could you explain why do you hold that opinion?

Now yes I made this pr with a headache and it was late. So let me explain further.

In upstream as of currently we do not want to restrict player creation. And as the maintainer review is going currently. Most other maintainers agree.

Yes, it is silly that an 18-year-old can be a captain from a rp standpoint, which from a quick chat (And also recognizing some names) I had seems to be why most of the downvotes are there. Most of our servers are LRP and we do not have a lore. And it feels like a weird limitation to have on Wizard den servers. Hell, even then. I wouldn't mind seeing someone explain how to get captain at the age of 18. It gets people role-playing and creating a story.

The second part of this story is that, this feature getting into upstream was not voted in. The species team (which I'm part of) was NOT notified about this change. I only found out after someone asked about it in the general chat on discord.

Normally, we use the [work groups](https://docs.spacestation14.com/en/general-development/work-groups.html) system to alert maintainers that are interested in a certain part of the game about changes and to give their opinions. This did not happen, I do not blame anyone for the slip up. We are human, after all. But I believe now that we have noticed this, we believe that it should have not made it into the game.

**Comment by slarticodefast** [comment]
We gave it a vote among maintainers and the decision was to merge this due to the reasons already mentioned above:
- Wizden servers are mostly LRP
- It can be confusing when you unlock a new role, but cannot select it and have to edit the character you have been playing so far to be able to
- Forks can easily adjust this to their desired roleplay standards with a few lines of yaml

**Comment by Sarahon** [comment]
Can't wait for more of the silly based skibidi command, fresh out of space highschool as captain to teach us about the based skibidi toilet stuff or something I suppose. Now they have their age as an excuse to be obnoxious.

**Comment by VasilisThePikachu** [comment]
I am hiding that only because of the use of the S word

**Comment by slarticodefast** [comment]
silly or space?

**Comment by Sarahon** [comment]
> I am hiding that only because of the use of the S word

Well I'm not wrong. Somebody in the discord already mentioned now getting to be "young and stupid as command". Though I guess it can't get any worse than we have now.

**Pull request merged**
