### PR TITLE
structural damage rework / melee damage curve flattening

### PR DESCRIPTION
**Pull request by Emisse**
makes walls almost impervious to weapons
windows are generally weaker
structures now use a new damage container and walls now use a new modifier set to make them strong against weapons
secure crates/lockers are now stronger and will no longer be busted open by crowbars
powercrept melee weapons have been brought down
dblade and syndi fireaxe are now unavailable

🆑 
- tweak: Walls are stronger and windows are weaker.
- tweak: Secure crates and lockers are a lot stronger.
- tweak: Melee weapons are now more balanced within a closer range of damage.
- tweak: Double energy sword and fireaxe are now unavailable in uplink.

### CODE REVIEW

**Comment by HoidC** [comment]
why no fire axe

**Comment by GoodWheatley** [comment]
Have you tested to make sure c4 still works at blowing up reinforced walls?

**Comment by Kadeo64** [comment]
wait, fire axe removed from both syndie and nukie uplink?

**Review by keronshb — CHANGES_REQUESTED** [review]
I'd like to run some test numbers with these on a private server before this is merged. So going to put a request changes on here as a way to do that. I'll post changes or an accepted review once I'm done.

**Comment by UbaserB** [comment]
hooray, a much needed balance!

**Comment by Hmeister-fake** [comment]
Why removed dsword and fire axe from uplink?

**Comment by Kadeo64** [comment]
> Why removed dsword and fire axe from uplink?

dsword is op and fire axe can just space everything

**Comment by asperger-sind** [comment]
Really complex topic, this needs discussion imo, speedmerging this would be detrimental.
I see the scope of this PR but I strongly believe that combat balancing should not be treated in a vacuum, with this PR there should be adjustments for armor and guns as well.

I use the term "melee" a lot during this but I refer to damaging melee in specific, so no stun batons unless explicitly mentioned.

Compiling some points from a discussion that occurred in contributors chat on Discord as of 12/18/2023 2:00-2:20(?) PM UTC+2
Start of discussion for manual reading: https://discord.com/channels/310555209753690112/770682801607278632/1186275351299637288

- De-sword removal looks like its agreed upon.

- Melee weapons being nerfed, specifically the ("powercrept") top performers, makes guns even more strong in relative to melee, which raises:

Ping concerns, players outside the US (as the current populated servers are being hosted there), namely in Europe, and Russia by proxy will be shoehorned out of using high performing melee, as it is much more viable on high ping (100-300ms+), into using guns, which are (from personal experience) horrid to use on high (200-300ms+) ping, because guns will be favored to the point where not using one, or a remaining strong (e.g. stun batons) options will be a huge detriment in combat.

Melee weapons being overall weaker than they should. Melee is good, it feels great and has good skill expression while not having an overly high skill floor or being highly limited by ping. Having melee be a backwater option that you only use when you do not have a gun is not great considering the potential for high performing melee weapons.

It is arguable that the status quo of melee/gun was held up by "powercrept" melee weapons limited to antagonists, they are common good and strong options with counterplay that have made it possible to fight the station crew despite being heavily outnumbered.

Batons remaining a beacon of power creep, now as they are the only weapon that reliably 3-shots someone, batons are in a pretty good place right now until soft stuns and breaking the status quo isn't very good.

- Removal of the *fire* axe is unnecessary: 

Completely removing the fire axe from the uplink has been seen as a bad approach in comparison to leaving it or nerfing it or adding other mali, the weapon is while strong and considered a good purchase by the majority of the playerbase including experienced players, has its counters, namely being magdumped and batons. If it is deemed to be overly strong for its price and capability it should not be outright removed, but nerfed instead, suggestions come as a light speed malus while holding it, higher TC cost, *slightly* less damage, limit it to nukies, etc.

- Antagonist gear should be stronger than station gear:

Why? Because any and all antagonist activity is being held on the crew's ground (the station) and on the crew's rules (80 people and spawning via shuttle, systems like cargo, etc.), it is only fair that antagonists receive stronger gear to make up in quality for the lack of quantity.

Why? Because antagonist gear makes you valid, people YEARN for the blood of antagonists.

Why? Because they were made strong for a reason, e-sword has historically been a laughable uplink purchase until it became relevant through countless buffs until it became a valid and strong purchase.

Now then, this about sums it up, I did toss in a few points here that I got as shower thoughts later - so read the discussion yourself. If there are more discussions on the topic please let me know so I can get another sum-up going.

**Comment by HoidC** [comment]
> > Why removed dsword and fire axe from uplink?
> 
> dsword is op and fire axe can just space everything

nothing stops axe smashing windows so space everything is still a problem

**Comment by HoidC** [comment]
> > > Why removed dsword and fire axe from uplink?
> > 
> > 
> > dsword is op and fire axe can just space everything
> 
> nothing stops axe smashing windows so space everything is still a problem

as in smashing windows in general whoops or

**Comment by keronshb** [comment]
> > > Why removed dsword and fire axe from uplink?
> > 
> > 
> > dsword is op and fire axe can just space everything
> 
> nothing stops axe smashing windows so space everything is still a problem

Fireaxe is made to smash windows, definitely not walls or floors.

**Comment by Aisu9** [comment]
> > > Why removed dsword and fire axe from uplink?
> > 
> > 
> > dsword is op and fire axe can just space everything
> 
> it is 20 tc man

it's not a traitors goal to destroy/cleave station

**Comment by Kadeo64** [comment]
> > > > Why removed dsword and fire axe from uplink?
> > > 
> > > 
> > > dsword is op and fire axe can just space everything
> > 
> > 
> > it is 20 tc man
> 
> it's not a traitors goal to destroy/cleave station

this tbh nobody but nukies should be busting down walls and causing structural damage unless it's to steal something in a locked room

**Review by keronshb — APPROVED** [review]
After discussion on discord, this is mostly fine. ESword damage was reverted Everything else  lines up.

**Comment by JoeHammad1844** [comment]
image
BUT WHEN I-

also, you the throwing damage should match or exceed the melee damage since it embeds

**Pull request merged**
