### PR TITLE
Cull high-velocity ammo

### LINKED ISSUE #10531: Cull high-velocity ammo
It does more damage than regular ammo but it's just extra mapping hassle and never gets used anyway so I think we're better off removing it.

### PR DESCRIPTION
**Pull request by Vordenburg**
Resolves #10531

### CODE REVIEW

**Comment by LankLTE** [comment]
That issue was made before it was Sci research, given it’s used now it feels odd to remove

**Comment by Vordenburg** [comment]
@metalgearsloth Is the issue still relevant?

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
will need sloth to look at but i do agree that hv rounds are probably bloat at this point

**Review by EmoGarbage404 — APPROVED** [review]
hv have always been dumb so i'm for this

**Comment by Partmedia** [comment]
HV can be removed from the vendors, but what if forks use this...

**Comment by deltanedas** [comment]
pretty sure hv ammo can be researched now so that issues a bit outdated, at best maybe unmap it

**Comment by Partmedia** [comment]
> pretty sure hv ammo can be researched now so that issues a bit outdated, at best maybe unmap it

Also yes, this is the Tier 2 "optimized ballistics" technology.

**Comment by metalgearsloth** [comment]
If it's getting researched now I'm indifferent.

**Comment by Vordenburg** [comment]
> HV can be removed from the vendors, but what if forks use this...

This should probably be put somewhere more visible since it's general advice, but: same procedure as if anything is removed or deprecated but someone wants to keep it around. Revert or do not commit, take ownership of the entities in a file not under SS14 source control as to avoid merge conflicts, and now it's yours.

> will need sloth to look at but i do agree that hv rounds are probably bloat at this point

My thinking is that HV accomplishes only more damage not different damage (incendiary, rubber), but that can be done just as well with a different gun of a higher caliber. As it stands, BaseBulletHighVelocity does 3 more Piercing damage than BaseBullet, for comparison's sake.

**Comment by metalgearsloth** [comment]
I'm open to dumping this and seeing how per-gun damage mods go. From https://github.com/space-wizards/space-station-14/pull/18506 I wasn't a huge fan of the AP changes I think we probably need to move away from AP for a bit. This probably also opens the window for a few more guns to be ported again without overcomplicating gun balance.

**Comment by LankLTE** [comment]
> I'm open to dumping this and seeing how per-gun damage mods go. From #18506 I wasn't a huge fan of the AP changes I think we probably need to move away from AP for a bit. This probably also opens the window for a few more guns to be ported again without overcomplicating gun balance.

i think AP ammo is best kept as a syndie / maybe ERT thing. it's kind of OP but that was the point, trying to balance it by lowering the piercing percent tends to make it either a direct upgrade or direct downgrade with how armor works

**Comment by Partmedia** [comment]
What do we want to do about this?

1. Close this and re-open once per-gun damage mods arrive.
2. Remove the "optimized ballistics" technology and merge this, removing high-velocity rounds.

**Comment by Partmedia** [comment]
@Vordenburg the FTL string for optimized ballistics is still there.

**Pull request merged**
