### PR TITLE
Custom solution transfer volume popup and item status panel fix

### LINKED ISSUE #29773: Setting a custom solution transfer volume does not update the item status panel
## Description

We do not see the confirmation popup or the panel status updated if we set a custom amount versus a default/preset amount.

**Reproduction**

1. get a beaker
2. right click > Set Transfer Amount > Custom
3. enter custom value and click Set Amount

Expected: see popup and item panel 'Transfer: xxx' updated
Actual: no popup and item panel shows old value

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/89101928/7e3dd905-2c43-44a2-aeea-65e52d18582b

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR

Fixed confirmation popup not be displayed and item status panel not be updated after setting a custom solution transfer volume.

## Why / Balance

Fixes #29773.

## Technical details

Added ``AutoGenerateComponentState`` attribute to the ``SolutionTransferComponent`` and ``AutoNetworkedField`` to it's ``TransferAmount`` field. Also changed ``PopupClient`` to ``PopupEntity``.

## Media

https://github.com/space-wizards/space-station-14/assets/74284083/468e7895-b965-49f9-8e78-0c897f8d3cd0

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Now confirmation popup is displayed and item panel status is updated after setting a custom solution transfer volume.

### CODE REVIEW

**Comment by Winkarst-cpu** [comment]
Failed check is not related to the PR. The code itself works just fine...

**Review by PJB3005 — APPROVED** [review]
Looks good otherwise

**Comment by Winkarst-cpu** [comment]
> Could you add a `Dirty()` call to the transfer verb code too? This stuff should've been networked synced like this all along and that's another place it's missing. It seems the only reason that isn't visibly broken for now is because of _another_ bug.

I'm not fully sure what do you mean by that... All options except the custom value seem to work just fine.

**Comment by PJB3005** [comment]
> > Could you add a `Dirty()` call to the transfer verb code too? This stuff should've been networked synced like this all along and that's another place it's missing. It seems the only reason that isn't visibly broken for now is because of _another_ bug.
> 
> I'm not fully sure what do you mean by that... All options except the custom value seemed to work just fine.

They'll be broken when prediction is disabled once https://github.com/space-wizards/RobustToolbox/pull/5294 gets merged, and as it currently is it's possible for a misprediction to cause the wrong transfer value to get stuck on the client (change transfer volume right before getting stunned, your client will get stuck with a different value than the server).

**Comment by Winkarst-cpu** [comment]
> > > Could you add a `Dirty()` call to the transfer verb code too? This stuff should've been networked synced like this all along and that's another place it's missing. It seems the only reason that isn't visibly broken for now is because of _another_ bug.
> > 
> > 
> > I'm not fully sure what do you mean by that... All options except the custom value seemed to work just fine.
> 
> They'll be broken when prediction is disabled once [space-wizards/RobustToolbox#5294](https://github.com/space-wizards/RobustToolbox/pull/5294) gets merged, and as it currently is it's possible for a misprediction to cause the wrong transfer value to get stuck on the client (change transfer volume right before getting stunned, your client will get stuck with a different value than the server).

Okay, I will add a ``Dirty()`` call to the transfer verb code.

**Pull request merged**
