### PR TITLE
Remove ranged injection/feeding

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
They make no sense and they were clearly only added because 'it's funny' but I have only seen them used to kill people with lexorin, mercury, etc. If we're going to remove cheap bullshit like tasers these should be next. The pie was literally a ranged hypospray that made no checks and went directly into your bloodstream. I left the component system for that because some specialized shotgun ammo, etc uses it and that seems like a decent use case. I hope no one ports syringe guns though.

**Changelog**

:cl: Rane
- remove: Pneumatic cannons and cream pies no longer can be used to instakill people with hyperoptimized poison mixes.

### CODE REVIEW

**Comment by Elijahrane** [comment]
Arguments for removing:
1. The pie right now is literally just a ranged hypospray that injects directly into your bloodstream with no checks.
2. The pneumatic cannon thing is stupid overpowered. Forcefeed doafters exist for a reason, because it's easy to make a pill that can take you from full health to dead.
3. I have literally never seen anyone use them in a remotely funny way but I have seen people use them to inject instakill poison plenty of times. These don't make logical sense so their justification is supposed to be that they are funny. Instakill poison is not funny.

**Comment by Emisse** [comment]
syringe guns suck, theres no counterplay to it and i dont think we should have ohk projectile weaponry commonly available like that

**Comment by mirrorcult** [comment]
i'm ok with removing this

**Review by mirrorcult — APPROVED** [review]

**Review by Veritius — APPROVED** [review]

**Comment by Veritius** [comment]
> remove: Pneumatic cannons and cream pies no longer can be used to instakill people hyperoptimized poison mixes.

Do you mean

> remove: Pneumatic cannons and cream pies no longer can be used to instakill people with hyperoptimized poison mixes.

**Comment by Elijahrane** [comment]
> > remove: Pneumatic cannons and cream pies no longer can be used to instakill people hyperoptimized poison mixes.
> 
> Do you mean
> 
> > remove: Pneumatic cannons and cream pies no longer can be used to instakill people with hyperoptimized poison mixes.

yeah

**Pull request merged**
