### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by AJCM-git**
I made every prototype name lower case, if there are any that dont have to be lower case (proper nouns and abreviations) leave a review.

Re-Opening #1020

### CODE REVIEW

**Comment by ComicIronic** [comment]
I think you messed up the history, since this is now a +7/-4 change.

**Comment by AJCM-git** [comment]
Oh my god, what happened

**Comment by AJCM-git** [comment]
Oh my god what happened

**Comment by AJCM-git** [comment]
wrong branch

**Pull request closed without merging**
