### PR TITLE
Melee rebalancing

### PR DESCRIPTION
**Pull request by metalgearsloth**
Wide attacks are going to feel undertuned in the meantime and we should buff it to a spot where it's not the go-to option for every single fight.

:cl:
- tweak: Re-balanced melee combat. Windup is removed, heavy attacks cost 15 stamina, stamina damage cooldown reduced from 5s to 3/s, wide attacks provide a 10% damage bonus, and wielding no longer grants immunity to disarms.
- tweak: Reduce desword values to standard fast weapons (left wide-attack angle at 100 degrees instead of the standard 60).

### CODE REVIEW

**Comment by EEASAS** [comment]
i personally do not enjoy this uhh change because many players will hate it and will stop being robust(mainly because of wideswing removal)

**Comment by CrigCrag** [comment]
tony hawk from iron man once said:
"if you're nothing without heavy attacks, then you shouldn't have them"

**Comment by Anzarot121** [comment]
Space Ticks will love this PR.

**Comment by Vordenburg** [comment]
The CL entry claims wielding no longer grants immunity to disarms, but it is my understanding that this behavior stems from this event handler:
https://github.com/space-wizards/space-station-14/blob/501bc4be049ce5112383c132ef836b64b42426b0/Content.Shared/Wieldable/WieldableSystem.cs#L88-L92

This does not appear to be touched in this PR, and I'm unable to find what results in wielding no longer granting immunity to disarms.

**Review by keronshb — DISMISSED** [review]
I like the change to heavy attacks since it gives more balance to them.

Tested this with gloves of the north star too, you run out of stamina before it becomes a problem.

The PR mentions changes to disarms but I don't see anything related to that in the changed files. Can you clarify where this is?

Overall this does act more as a nerf for melee. A syndie who uses a melee weapon heavy attack is going to be at a bigger disadvantage against batons and ranged stun options. Is there anything you can adjust to offset that?

**Comment by deltanedas** [comment]
10% damage boost seems too little compared to the previous up to 100%, makes the boost negligible compared to the only real utility of being wide swing

**Comment by metalgearsloth** [comment]
>The CL entry claims wielding no longer grants immunity to disarms, but it is my understanding that this behavior stems from this event handler:

> The PR mentions changes to disarms but I don't see anything related to that in the changed files. Can you clarify where this is?

I forgor to draft and commit.

**Comment by metalgearsloth** [comment]
Bumped heavy damage to 25% so will see how we go?

**Comment by metalgearsloth** [comment]
talked to keron about it on disc but we can revert if it goes terrible

**Comment by dmnct** [comment]
Can the deployed changelog be edited to correctly state +25% damage instead of the originally planned 10?

**Comment by metalgearsloth** [comment]
oop yeah, could just webedit too if you see it

**Pull request merged**
