### PR TITLE
Tweak dwarf accent

### PR DESCRIPTION
**Pull request by pewter-wiz**
## About the PR
Just a minor quality of life tweak to the Dwarven accent, as these are common stumbling points in communication as a dwarf main.

## Why / Balance

https://discord.com/channels/310555209753690112/1170959598153375815

These phrases are common issues in conversation as a dwarf, as the don't make grammatical sense in many cases, or don't get your meaning across. This will make Dwarves easier to play as communication becomes slightly less of a barrier around these topics.

## Technical details

As such I have removed the following substitutions from the dwarven accent:
| Word                            | Replacement | Reason                                                                                                                                                                                             |
|---------------------------------|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Beer                            | Booze       | Usually when speaking of beer, people mean the specific beverage. Also makes it hard to explain how to mix a manly dorf: "2 parts ale ta 1 part booze"                                             |
| Hey                             | Oye         | It seems like the intention was to turn Hey! -> Oye! But when you say "Hey there friend" it becomes "Oye there friend" which doesn't work grammatically, or seems rude                             |
| Thinking                        | Fer         | I can't find a source for why this exists, nor could anyone vouch for its roots in Scots. (Was it a mistaken entry, as `fer` is already a replacement for `for` elsewhere)                         |
| Antag, Syndie, Syndi, Syndicate | Baddie      | These substitute a very specific organisation/enemy for "baddie" which make sentences often unintelligible                                                                                         |
| Shuttle                         | Molly       | This has no roots in Scottish/Scots, and appears to be a reference to a helpful robot in Deep Rock Galactic. This doesn't relate to a shuttle at all becomes unintelligible to those not familiar. |

I have also removed a duplicate entry for `for -> fer`

## Media

Dwarf Speech Fix
This phrase translates prior to PR as:
> Oye! Ah wis fer abut mixing ae manly dorf aboard tha baddie molly. Tha ingredients be 2 parts ale ta 1 part booze!

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: pewter.wiz
- tweak: dwarven accent no longer uses unintelligible substitutions such as shuttle -> molly and beer -> booze.

### CODE REVIEW

**Comment by deltanedas** [comment]
undo molly or you arent going home

**Comment by EmoGarbage404** [comment]
> undo molly or you arent going home

be nice or you won't either.

**Comment by pewter-wiz** [comment]
> undo molly or you arent going home

I understand the fondness towards "Molly" as it's become part of the space-dorf accent, and I've gotten used to it, but it's unintuitive and from my understanding is not based in Scots, but instead a reference to the robot from Deep Rock Galactic which doesn't bear any resemblance in visuals or use-case to a shuttle, so I don't see the connection that justifies its existence
https://deeprockgalactic.fandom.com/wiki/M.U.L.E.#Nicknames

**Comment by pewter-wiz** [comment]
> > undo molly or you arent going home
> 
> I understand the fondness towards "Molly" as it's become part of the space-dorf accent, and I've gotten used to it, but it's unintuitive and from my understanding is not based in Scots, but instead a reference to the robot from Deep Rock Galactic which doesn't bear any resemblance in visuals or use-case to a shuttle, so I don't see the connection that justifies its existence https://deeprockgalactic.fandom.com/wiki/M.U.L.E.#Nicknames

> As soon as the primary mission goal has been reached, the [Drop Pod](https://deeprockgalactic.fandom.com/wiki/Drop_Pod) can be called using a red button that appears on the back of the M.U.L.E. Once pressed, the Drop Pod will land at a distant location and the M.U.L.E. will begin walking towards it, ignoring any calls from that point onward.

If anything, the shuttle request console might make more sense as "Molly"

**Comment by deltanedas** [comment]
in drg you can jump onto molly to get back to the drop pod do its vaguely like a shuttle

**Comment by CatMagic1** [comment]
I feel like there's a better solution to oye, as it's often big part of dwarf speech and I like it :3

**Comment by pewter-wiz** [comment]
> I feel like there's a better solution to oye, as it's often big part of dwarf speech and I like it :3

Yeah I'm not so certain on this one

What do you suggest for a solution?

If people like Oye I can revert that part of the change

**Comment by CatMagic1** [comment]
> If people like Oye I can revert that part of the change.

I'd say revert it unless someone says it's really bad.

**Comment by TheDarkBox** [comment]
Why "Oye" and not "Oi"?
"Oye" doesn't make any sense in this context.

As someone mentioned in the Discord forum, "Oye" is Spanish.. it is immensely confusing and I always read it out as "O-yeh", which makes dwarves sound Spanish to me:

image

**Comment by Carolyn3114** [comment]
> > undo molly or you arent going home
> 
> be nice or you won't either.

this isn't even that mean of a statement lol

**Pull request merged**
