### PR TITLE
Chemical Synthesis Kit

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

A purchasable antagonist bundle for 4TC that contains:
- Two vials of vestine
- An empty vial
- A Syringe of stimulants
- Two small beakers
- Chemical analysis gogles
- A dropper

This PR helps gate dangerous chemicals behind antagonists for the upcoming chemical rework. The idea i had was that traitors get access to more powerful chems than non-antags. Like, if everyone is making dangerous chems because they can, then putting the effort in as a traitor puts you on the same playing ground as everyone else. Gating the chems means you can gain an advantage. 

It also reintroduces the kit so that non-chemists can gain easy access to harmful chemicals. Nocturine is also removed from the uplink but now has a recipe that requires Vestine. Lexorin is buffed so that there is a meaningful difference compared to the non-antag version (heartbreaker toxin). The chemical recipe changes are as following:

**MUTE TOXIN**
Uranium: 1
Vestine: 2
Space Glue: 2
**To produce 2 mute toxin.** 

**TAZINIDE**
Licoxide: 1
Vestine: 1
**To produce 1 tazinide.** 

**LEXORIN**
Heartbreaker Toxin: 1
Plasma: 1
Vestine: 1
**To produce 2 lexorin.** 

**STIMULANTS**
Ephedrine: 1
Vestine: 1
Oxygen: 2
**To produce 2 stimulants.** 

**NOCTURINE**
Impedrezene: 2
Vestine: 1
**To produce 1 nocturine.** 

This PR also tweaks random pills to contain amatoxin instead of toxin so that not anyone can synthesize a large amount of these compounds.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image
image
image

**Changelog**

:cl: Ubaser
- add: Traitors and Nukies can now purchase a Chemical Synthesis Kit for 4TC which contains Vestine.
- tweak: Nocturine, Tazinide, Stimulants, Lexorin and Mute Toxin are now locked behind Vestine.
- tweak: Lexorin and Heartbreaker toxin are buffed, while Licoxide is nerfed.
- remove: You can no longer purchase Nocturine through the uplink.

### CODE REVIEW

**Comment by deltanedas** [comment]
licoxide is for validhunting nukies, the 0.5s stun is useless for kidnapping compared to nocturine

**Comment by UbaserB** [comment]
> licoxide is for validhunting nukies, the 0.5s stun is useless for kidnapping compared to nocturine

in that case, i can buff licoxide

**Comment by thebadman4662** [comment]
Its not useless at all to keep people in chem foams, especially during revolutions. Bonus points if you have a remote to cut off command/sec.

**Comment by Aisu9** [comment]
so.... strange pills have 20 units of amatoxin right.... you know it's 240 poison damage in a single pill right?

**Comment by UbaserB** [comment]
> so.... strange pills have 20 units of amatoxin right.... you know it's 240 poison damage in a single pill right?

lol.. ok ima fix

**Comment by deltanedas** [comment]
> Its not useless at all to keep people in chem foams, especially during revolutions. Bonus points if you have a remote to cut off command/sec.

revolutionaries dont have uplinks remember

**Comment by Aisu9** [comment]
> > Its not useless at all to keep people in chem foams, especially during revolutions. Bonus points if you have a remote to cut off command/sec.
> 
> revolutionaries dont have uplinks remember

hence why most of these chems should be gather-able at some point in the futtur via different methods, i don't see why salvager/miner shouldn't be able to mine lead from asteroids

**Comment by asperger-sind** [comment]
8TC is way overkill, you spend 8 TC for the ability to make specific compounds, all of which already require a lot of effort to make because of the other ingredients, 2-4 TC is a better price imo.

**Comment by JoeHammad1844** [comment]
why not just have a box of dangerous chemicals instead of needing to make them?

**Comment by JoeHammad1844** [comment]
also, strange pills no longer containing dangerous chemicals removes the entire fun and purpose of strange pills

**Comment by UbaserB** [comment]
> also, strange pills no longer containing dangerous chemicals removes the entire fun and purpose of strange pills

no it replaces it with amatoxin

**Comment by JoeHammad1844** [comment]
oh so JUST toxin? thats fine i think

**Comment by JoeHammad1844** [comment]
id prefer if it wasnt removed because thats a 1 in however many hundreds chance

**Comment by UbaserB** [comment]
> id prefer if it wasnt removed because thats a 1 in however many hundreds chance

its actually a really high chance lol

**Comment by deltanedas** [comment]
for 8tc you can also get an emag and make unlimited quantity of the funny chemicals

**Comment by JoeHammad1844** [comment]
>nocturine removed from uplink

nice job neutering non lethal options for syndicates, nocturine was already 5TC for 30 units and was only useful with the 6TC hypopen, costing 11TC, you want them to now spend fucking 14TC for the PRIVILEGE of spending time clicking away at a chem dispenser to make some, fun, very fun

**Comment by Just-a-Unity-Dev** [comment]
> NOCTURINE
Licoxide: 2
Impedrezene: 1
Nitrogen: 1
Oxygen: 1
To produce 2 nocturine.

rip non-lethal takedowns considering you basically have to be a chemist to make this, not only that but you need 2 lead, 2 zinc and 2 vestine to make 2 licoxide. pretty much not worth it at all

**Comment by JoeHammad1844** [comment]
its fucking boring having most syndicate options being entirely/mostly lethal. i want to be able to kidnap people and make them do SAW puzzles, not just kill them and have to revive them (while being hunted down from gunshots/esword sounds)

this is a step backwards for traitors

**Comment by UbaserB** [comment]
1. the price was reduced to 4tc so nocturine is cheaper than before.
2. i am the worst at balancing which is why this is up for discussion so can you stop being aggressive

**Comment by JoeHammad1844** [comment]
>i am the worst at balancing which is why this is up for discussion so can you stop being aggressive

sorry, man.

anyway, having it be 4TC is a good price but does not make up for nocturine being removed from the uplink due to the requirement of chemistry and time investment, it would be better if nocturine was still up for purchase but the recipe remained

**Comment by UbaserB** [comment]
> sorry, man.
> 
> anyway, having it be 4TC is a good price but does not make up for nocturine being removed from the uplink due to the requirement of chemistry and time investment, it would be better if nocturine was still up for purchase but the recipe remained

ill check this with the maintainers

**Comment by UbaserB** [comment]
> > nocturine removed from uplink
> 
> nice job neutering non lethal options for syndicates, nocturine was already 5TC for 30 units and was only useful with the 6TC hypopen, costing 11TC, you want them to now spend fucking 14TC for the PRIVILEGE of spending time clicking away at a chem dispenser to make some.
> 
> fun, very fun

whats worth mentioning is this is specifically designed for the chem rework in mind; where anyone can get the materials and its not exclusive for chemists. There *literally* wont be a chemmaster for you to use.

**Comment by JoeHammad1844** [comment]
> whats worth mentioning is this is specifically designed for the chem rework in mind; where anyone can get the materials and its not exclusive for chemists. There _literally_ wont be a chemmaster for you to use.

so you're making a change now that will only benefit people in whatever amount of time it takes for it to be made and making things worse in the meantime?

**Comment by JoeHammad1844** [comment]
what i mean is that you shouldn't make a significant change like this if the rework hasn't been implemented

**Comment by UbaserB** [comment]
> > whats worth mentioning is this is specifically designed for the chem rework in mind; where anyone can get the materials and its not exclusive for chemists. There _literally_ wont be a chemmaster for you to use.
> 
> so you're making a change now that will only benefit people in whatever amount of time it takes for it to be made and making things worse in the meantime?

emo said it should be done this weekend so

**Comment by JoeHammad1844** [comment]
just a week away..

**Comment by Kelrak** [comment]
I think you need to update the description of lexorine epi and dex as they no longer interact with each other if I understand this correctly?

**Comment by QuietlyWhisper** [comment]
Can this please be on do not merge until whatever rework is being planned is actually finished and any possible issues with it are resolved, as normally happens with major changes...

**Comment by Kelrak** [comment]
Also a tip that needs updating https://github.com/space-wizards/space-station-14/blob/e1a59ea2841d1b5f7a612bb81a2e2dbb63b5bf01/Resources/Prototypes/Datasets/tips.yml#L25 (apologies for nitpicking :))

**Comment by UbaserB** [comment]
> Also a tip that needs updating
> 
> https://github.com/space-wizards/space-station-14/blob/e1a59ea2841d1b5f7a612bb81a2e2dbb63b5bf01/Resources/Prototypes/Datasets/tips.yml#L25
> 
> (apologies for nitpicking :))

yea i think i updated that already, i noticed myself

**Comment by TK-A369** [comment]
In my opinion, it would be better to change Toxin's name. Currently the name is very generic, but this chemical is something specific. It might be a bit confusing that recipes needing toxin are not working when you use, for example, amatoxin.
I'm not sure if it should be done in that PR, or separate.

**Comment by GoodWheatley** [comment]
I think this would make more sense if the chemicals already came premade instead of requiring chem work to produce. In ss13 the poison kit was useful *because* all the poisons came ready to use, and requiring the poisons to be mixed removes that advantage.

**Comment by Doru991** [comment]
I don't really vibe with this, to me it feels like:
- It unnecessarily nerfs rev chemists
- Nerfing non antag chemists is whatever but kinda makes them even more useless against nukies
- Makes syndie chemists overpowered, considering that they were already one of the best jobs to roll syndie as
- Is very situational for other syndies, since you basically need to go loud or at least visibly greytide in order to make proper use of the chems in the kit.
I think a poisoning kit with premade syndie-exclusive poisons would be a way better solution, since it allows for non-chem/bot syndies to effectively poison people if they spare a bit of TC

**Comment by JoeHammad1844** [comment]
> I think a poisoning kit with premade syndie-exclusive poisons would be a way better solution, since it allows for non-chem/bot syndies to effectively poison people if they spare a bit of TC

hey, cool, thats in 13 aswell!
image

**Comment by LankLTE** [comment]
Lexorin is already the strongest (non-lead) poison in the game- you’re buffing it to be the same strength as lead, which is a chem that intentionally takes almost 30 seconds to kill. I also don’t like arbitrarily making syndies spend TC on something they could formerly (in a difficult manner) make themselves.

**Comment by Doru991** [comment]
> Lexorin is already the strongest (non-lead) poison in the game- you’re buffing it to be the same strength as lead, which is a chem that intentionally takes almost 30 seconds to kill. I also don’t like arbitrarily making syndies spend TC on something they could formerly (in a difficult manner) make themselves. 

In terms of lexorin buffs, please note that its weakness to the epipen is also removed, so there's basically nothing you can do if you get hit with it

**Comment by UbaserB** [comment]
> Lexorin is already the strongest (non-lead) poison in the game- you’re buffing it to be the same strength as lead, which is a chem that intentionally takes almost 30 seconds to kill. I also don’t like arbitrarily making syndies spend TC on something they could formerly (in a difficult manner) make themselves.

makes a lot of sense. emisse told me to buff it.

**Pull request merged**
