### PR TITLE
CuraDrobe + Misc Librarian Stuff

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Added the CuraDrobe from TG. Resprited the librarian jumpsuit sprite and added the librarian jumpskirt. Adds jamjar glasses and the sensuble suit and skirt.

## Why / Balance

The librarian had a pretty bad jumpsuit sprite and needed some variety in their wardrobe.

## Media

gdfs

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Potato1234_x
- add: Added the CuraDrobe.
- add: Added the sensible suit and skirt.
- fix: Fixed the librarian not having their own jumpskirt.
- tweak: Resprited the librarian jumpsuit.

### CODE REVIEW

**Comment by Flareguy** [comment]
Please **do not** use the current /tg/ sprites for this. The current librarian jumpsuit sprite may be in need of a little love, but the /tg/ one is hilariously overshaded and made for a completely different jumpsuit base style.

My suggestion would be to just take the current curator jumpsuit sprite and add shading, assuming you are capable of doing so. If not, you should probably just leave it as-is and leave the curadrobe in - having alternate drobe choices is probably good for a job like this.

**Comment by potato1234x** [comment]
> take the current curator jumpsuit sprite and add shading, assuming you are capable of doing so.

i just took the tg curator clothes sprites and recolored them to match the ss14 librarian sprites. i dont exactly understand what you mean by this, since ss14 does not have a curator jumpsuit (not including this pr)

**Comment by potato1234x** [comment]
i also dont get how these are overshaded since they use the same amount of shades per color as the grey jumpsuit for example 
image

**Comment by potato1234x** [comment]
i could maybe part with the pants being detailed but the shirt looks fine compared to other jumpsuits

**Comment by Flareguy** [comment]
> > take the current curator jumpsuit sprite and add shading, assuming you are capable of doing so.
> 
> i just took the tg curator clothes sprites and recolored them to match the ss14 librarian sprites. i dont exactly understand what you mean by this, since ss14 does not have a curator jumpsuit (not including this pr)

I was referring to the librarian jumpsuit here, my bad. What we know as the librarian here is the curator in /tg/, so I ended up using them interchangably.



> i also dont get how these are overshaded since they use the same amount of shades per color as the grey jumpsuit for example [image]

image

The way the colors are utilized here is completely different, and the color count doesn't really have any bearing on it. The actual shading itself is visibly way more detailed and messy compared to the grey jumpsuit - use of variable outline colors, whatever the hell is going on with the pants, the random outline breaks...
Compare this to the current librarian outfit, which really doesn't have that many things separating it compared to the grey jumpsuit stylistically. All it really needs is (debatably) more shading, less weird noise, and a better outline color.

**Comment by potato1234x** [comment]
is that not what my sprite does? it fixes weird noise and outline colors. if the pants are the main problem i can fix those

**Comment by Flareguy** [comment]
> is that not what my sprite does? it fixes weird noise and outline colors. if the pants are the main problem i can fix those

I outlined all of the problems with your sprite in this block of text (none of these are related to the "current" one:)
> The way the colors are utilized here is completely different, and the color count doesn't really have any bearing on it. The actual shading itself is visibly way more detailed and messy compared to the grey jumpsuit - use of variable outline colors, whatever the hell is going on with the pants, the random outline breaks...

The sprite DOES fix the noise, but the outline is far from fixed - it is arguably worse than what exists now, in fact.
If I haven't made it clear enough - I would *highly* recommend using the current sprite as a base instead of the /tg/ one you're using. I am 99% certain they were literally created with the express purpose of fitting the new /tg/ style jumpsuits.

**Comment by potato1234x** [comment]
alright i'll work on these tommorow

**Comment by potato1234x** [comment]
i lied, how does this look?
image

**Comment by potato1234x** [comment]
image
new sprites

**Comment by potato1234x** [comment]
@Flareguy ?

**Comment by potato1234x** [comment]
media has been updated

**Comment by Flareguy** [comment]
Apologies for the delay.
The meta.json for the clothes need to be updated to state that you edited both of them, the curator one may also need to be updated depending on how you went about editing it.

**Comment by potato1234x** [comment]
i dunno why github didnt notify me but its done

**Pull request merged**
