### PR TITLE
Enable panic bunker by default

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

If someone adds support for custom panic bunker messages set via cvar that'd probably be good.

## Why / Balance

Discussed by admins, they need better tools https://github.com/orgs/space-wizards/projects/8

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Emisse** [comment]
why, we are supposed to be the servers for newer players

**Comment by Emisse** [comment]
what are they supposed to join then lol

**Comment by QuietlyWhisper** [comment]
lizard and leviathan are not enabled by default if that wasn't clear

**Comment by Emisse** [comment]
ok sounds fine

**Comment by LankLTE** [comment]
If you want to set a custom reason globally #23267 now exists.

**Comment by FairlySadPanda** [comment]
How come this is Liz and Levi, btw? That means newbies have to join a higher ping server if they're based in EU.

**Pull request merged**
