### PR TITLE
Removes diona thirst multiplier

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Removes the diona thirst multiplier entirely. I would argue that it is the main reason nobody really plays Diona, since in combination with the slow movement speed it just means you have to fucking _constantly_ ensure you have water on you and refill it every 20 minutes or so, or else you become unable to play the game due to the crippling combination of both status effects. It's just not fun to manage.

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Diona no longer get thirsty quicker than other species.

### CODE REVIEW

**Comment by Stealthbomber16** [comment]
id rather the movement speed be adjusted instead of the thirst

**Comment by GoodWheatley** [comment]
I think it would make more sense for them to be *better* at retaining water than humans. They’re living trees; it makes sense for them to be slow, since trees are not very flexible, but it doesn’t make sense for them to get thirsty so fast since trees are generally very good at retaining water.

**Comment by Froozigiusz** [comment]
I'd rather have a reffilable waterskin as a part of your gear (can be in a place of a tin can, nobody eats them anyway), this way you wouldn't have to hoard tins, glasses and watercups for any water source that you can find on your way.

Also diona being able to slurp/negate thirst counter by standing in a puddle could be an interesting idea. The only problem with that is what would happen if you step on a dangrous chemical, do you also ingest it?

**Comment by metalgearsloth** [comment]
Not a fan, I think one of the above changes would be better.

**Pull request closed without merging**
