### PR TITLE
New plant mutation: Pyrotton

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This "Pyro Cotton" contains 5u of phlogiston by default and is a mutation of the standard cotton plant. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

**Changelog**

:cl: Ubaser
- add: Pyrotton can now be mutated from cotton.

### CODE REVIEW

**Comment by f0x-n3rd** [comment]
this is gonna be too op and basically a pretty quick way to make a flamethrower.

**Comment by Tayrtahn** [comment]
To fix the errors, you'll need to add a stack prototype. See https://github.com/space-wizards/space-station-14/blob/master/Resources%2FPrototypes%2FStacks%2FMaterials%2Fmaterials.yml

**Comment by UbaserB** [comment]
> To fix the errors, you'll need to add a stack prototype. See https://github.com/space-wizards/space-station-14/blob/master/Resources%2FPrototypes%2FStacks%2FMaterials%2Fmaterials.yml

Thank you so much! I was trying to figure out where it was but it seems i totally missed it haha.

**Comment by thebadman4662** [comment]
> this is gonna be too op and basically a pretty quick way to make a flamethrower.

If someone can make phlog flamers work as botanist kudos to them. They have pathetic 0.2 fire per 1u and there are plenty of jobs that will have easier time getting stronger flamethrower weapons and payloads than botanists, both crew and antags.

**Comment by FungiFellow** [comment]
This needs a risk to farming, for example perhaps something like a chance for a weaker version Fire Anom's pulse every once in a while.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> This needs a risk to farming, for example perhaps something like a chance for a weaker version Fire Anom's pulse every once in a while.

a chance to light the person harvesting it on fire could work

**Comment by K-Dynamic** [comment]
> This needs a risk to farming, for example perhaps something like a chance for a weaker version Fire Anom's pulse every once in a while.

Well the reaction to make phlog generates plasma gas, ideally pyrotten should do the same

(Either spew plasma gas or harvesting makes plasma)

**Pull request merged**
