### PR TITLE
Adds casual jumpskirts

### PR DESCRIPTION
**Pull request by nmajask**
## About the PR

Adds three new jumpskirts named casual jumpskirts that are based on clothing from TG that can be found in the ClothesMate. Sprites are made by me but based on sprites by Tokiko and Niknakflan.

## Why / Balance

I loved how they looked in SS13 and how well they go with other clothing, though the original sprites are very outdated and the newer ones uses a greyscale coloring system to display the sprites. I ended up respriting it completely while still keeping the original style of it.

## Technical details

N/A

## Media

Old Sprites
image
image
image
image

New Sprites
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Three new casual jumpskirts can now be found in the ClothesMate.

### CODE REVIEW

**Comment by lzk228** [comment]
i love it

**Comment by EmoGarbage404** [comment]
pull upstream to fix tests first

**Comment by AJCM-git** [comment]
Idk jumpskirts are usually a variant of a uniform, and not standalone like in here, and the sprite could be remade to look better (feel free to ask in the art channel of the discord for help in that)

**Comment by nmajask** [comment]
> Idk jumpskirts are usually a variant of a uniform, and not standalone like in here, and the sprite could be remade to look better (feel free to ask in the art channel of the discord for help in that)

I do have a jumpsuit version of it that I didn't add as I wanted to avoid bloat as adding 3 variants of the same uniform to the clothesmate is already a lot, though I could add it if people want it.

image

As for the sprite quality, I will ask the art channel for feedback as I don't have a ton of experience with pixel art.

**Comment by AJCM-git** [comment]
> > Idk jumpskirts are usually a variant of a uniform, and not standalone like in here, and the sprite could be remade to look better (feel free to ask in the art channel of the discord for help in that)
> 
> I do have a jumpsuit version of it that I didn't add as I wanted to avoid bloat as adding 3 variants of the same uniform to the clothesmate is already a lot, though I could add it if people want it.
> 
> image
> 
> As for the sprite quality, I will ask the art channel for feedback as I don't have a ton of experience with pixel art.

Yeah, please do add it. Also just add one color (white) variant of em as we will soon have a way to recolor them ingame, so its better to avoid unnecesary ones.

**Comment by Partmedia** [comment]
As discussed, please replace the one-sprite-per-color with a single white jumpsuit sprite that can be recolored in YAML so that future color additions or changes do not require sprite updates. Please feel free to reach out here or on Discord if you need help.

**Comment by nmajask** [comment]
> As discussed, please replace the one-sprite-per-color with a single white jumpsuit sprite that can be recolored in YAML so that future color additions or changes do not require sprite updates. Please feel free to reach out here or on Discord if you need help.

Got it working with greyscale sprite. Only issue is that the sprite in the vending machine only shows one layer, though i think thats just an issue with the vending machine as it shows all the layers in the spawn menu (though it doesnt color it). If you want, i can try to fix that in a separate PR, though i make no guarantee i will be able to do so.
image

**Comment by Partmedia** [comment]
Thanks for the changes. We'll take a look at the vendor issue. Could you double check that you've removed the unused sprites with the different colors?

**Comment by nmajask** [comment]
> Thanks for the changes. We'll take a look at the vendor issue. Could you double check that you've removed the unused sprites with the different colors?

My bad, they are gone now. Also, I'm having issues with the monkey sprites as they don't like the different layers, any suggestions on what to do?

**Comment by Partmedia** [comment]
Thank you for your contribution.

**Pull request merged**
