### PR TITLE
red hos cap take 2

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Gives the HOS a red version of the Captain's blue cap and CC's green cap
## Why / Balance

Currently there are three "formal" suits (red, green, and blue) and two matching caps (blue and green), this would add in the missing cap (red) for the HOS.
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The HOS now has a red cap to complement their red formal suit.

### CODE REVIEW

**Comment by deepdarkdepths** [comment]
But HOS's current cap is so drippy!! It hides the eyes, least make it an optional thing

**Comment by MACMAN2003** [comment]
the sheriff hat will still be there

**Comment by EdenTheLiznerd** [comment]
I feel like it would fit with the set better if the cap itself was black instead of red

**Comment by MACMAN2003** [comment]
it's designed to fit with the red formal suit that the HOS gets

**Review by Flareguy — CHANGES_REQUESTED** [review]
I don't really like this conceptually. It hurts the HOS's visual identity (a syndicate agent could easily wear this cap and have it fit,) and doesn't work well with his default drobe.
The HOS also probably has enough stuff in his drobe as-is, though I'm not really as pressed about that.

**Comment by Flareguy** [comment]
Closing due to the review left above. I should have done this earlier instead of leaving this PR in limbo, apologies.

**Pull request closed without merging**
