### PR TITLE
[Dresser] Filling with garbage

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

Now some garbage appears in it, it will be useful for garbage fans to search the entire station in search of something unique, and now it can be found not only in technical tunnels, but also in here, albeit with a much smaller chance.
(even with such a variety, it can be empty, life is a pain when the PRs do not bring chaos.)

**Media**

https://github.com/space-wizards/space-station-14/assets/103608145/fc2f9264-8d7a-469c-a5a4-cb3d19d7782d

Pen.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Review by AJCM-git — COMMENTED** [review]
,

**Review by AJCM-git — CHANGES_REQUESTED** [review]
test fail (contents of the storage are larger than its size limits)

**Comment by PuroSlavKing** [comment]
> test fail (contents of the storage are larger than its size limits)

This is as it should be, the probability that it will be completely filled is too small.
increasing the capacity to 100 is not suitable, reducing the number of things so that their total weight is equal to 50 is also not cool.

**Comment by AJCM-git** [comment]
It doesnt matter if the chance its small or not, containers should never try to get filled over their limit, just use orGroups to never get over the limit

**Comment by Emisse** [comment]
this yml gives me nightmares but weve already been living in darkness since we added dirty water toilet

**Pull request merged**
