### PR TITLE
SS13 Quick examine

### PR DESCRIPTION
**Pull request by Carbonhell**
## About the PR 
Ports the bottom-left text showing the name of the entity the client cursor is hovering. This is useful to quickly understand what exactly an item is without having to examine it. This is especially useful for new players who need to learn all the various items of the game imo.
The check done to display the text is taken from ExamineSystem CanExamine. This means text won't be shown for entities behind walls, which the user can't see and so on, but it will also work correctly for ghosts by showing all the entities in the game window.

TODOs:

- [ ] When the user is flashed, the background white effect also covers the text. It looks wrong, maybe giving the text a background like buttons could work.
- [ ] This is only present on the default UI layout. I need to add it to the BYOND-like one as well.
- [ ] I need to figure out what the predicate parameter of CanExamine is / what it is for, right now I have no idea honestly.
- [ ] On discord, it was said that a past discussion on this topic was made and the result was to implement it, but only make it work when the user is holding the shift key. I don't really like that idea, so I was thinking of making an option to let the user choose between always active, active on a certain keybind hold (like shift), or disabled. Not sure if it's worth it though?
- [ ] I just looked better at the screenshot and I think I need to lower some margin, when the game window is small, the action bar overlaps with the top bar, maybe I can avoid raising the margin of the action bar from 10 to 20 somehow.

**Screenshots**

image

**Changelog**

:cl:
- add: Ports quick examine from ss13 (bottom-left name of the entity the client cursor is hovering).

### CODE REVIEW

**Comment by PJB3005** [comment]
No.

**Comment by PJB3005** [comment]
If you really want this, make it so that holding shift causes a popup next to the cursor instead. Not this garbage. I will veto this.

**Comment by PJB3005** [comment]
After a discussion on Discord we came to the agreement to keep this feature purely as an accessibility feature for people who have trouble with sending many mouse inputs etc. It should not be on by default and not be encouraged for able-bodied gamers.

Having an alternative mode for the examine tooltip, where click-and-holding shift-click makes a "live updating" examine tooltip would be a nicer idea for anything this might be useful for.

**Comment by moonheart08** [comment]
Are you coming back to this?

**Comment by Carbonhell** [comment]
No, if anyone wants to pick it up feel free, right now I'd prefer to focus on something else.

**Pull request closed without merging**
