### PR TITLE
Improved Coloring Layers For Moth Wings

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Allows for two color layers on Dark & Bushy, Death's-Head, Firewatch, Moffra, Plasmafire, and Royal wing moth markings.

**Media**
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl:
- tweak: Changed Dark & Bushy, Death's-Head, Firewatch, Moffra, Plasmafire, and Royal moth wings to now have two separate color layers.

### CODE REVIEW

**Comment by Eden077** [comment]
You are a god amongst men Nair

**Comment by Nairodian** [comment]
_I don't know why the test is failing._

**Comment by Emisse** [comment]
your meta.json is fucked somewhere

**Comment by Nairodian** [comment]
**A!** I see the issue. Had to do some fucky work to restore my files, give me a second.

**Comment by Emisse** [comment]
looks good

**Pull request merged**
