### PR TITLE
surgery real

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
this pull request has merge conflicts

only has organ harvesting/transplanting and amputating/restoring limbs

depends on #13917 to be finished and merged and new surgeries to be added in response

**Media**
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by deltanedas** [comment]
ok i think it is very fucked but whatever

**Comment by Equivocateur** [comment]
> depends on #13917

> pulls the entire pr into his own

based...

**Comment by lzk228** [comment]
god almighty...

**Comment by lzk228** [comment]
real pro

**Comment by deltanedas** [comment]
yeah idk i think i fucked it but whatever

**Comment by deltanedas** [comment]
time to wait 7 months, diff master, pr a single commit with 5k lines

**Comment by lzk228** [comment]
real noob :trollface:

**Comment by kxvvv** [comment]
nt

**Comment by deltanedas** [comment]
nt - nanotrasen

**Comment by Morb0** [comment]
:trollface:

**Comment by Jezithyr** [comment]
@deltanedas is it ok if I bring these changes into the new medical refactor branch?

**Comment by deltanedas** [comment]
go ahead also merge the 2 prs to it first

**Pull request closed without merging**
