### PR TITLE
more balanced constructing and unscrewing for metal objects

### PR DESCRIPTION
**Pull request by iacore**
## About the PR
- computer frame, machine frame, rack and meatspike can be deconstructed while anchored by screwing
- Computer frames now need time to be constructed.
- it now takes a reasonable time (2s) to make a meatspike.

## Why / Balance
If you can assembly something by hand, you shouldn't need to unweld it.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Nanotrasen has added screw holes to some metal constructions. (computer frame, machine frame, rack and meat spike are now deconstructed by screwing, also while unanchored.)

### CODE REVIEW

**Comment by Doru991** [comment]
I don't think the meatspike taking that long was too unreasonable, since it's basically a free gibbing/permakilling machine

**Comment by notquitehadouken** [comment]
how tf you construct a meat spike in 2 seconds

**Comment by NancokPS2** [comment]
> how tf you construct a meat spike in 2 seconds

Same way you construct a table in 1.

**Comment by iacore** [comment]
> I don't think the meatspike taking that long was too unreasonable, since it's basically a free gibbing/permakilling machine

when you can construct a machine frame in 2.5s

**Comment by metalgearsloth** [comment]
@iacore are you coming back to this? test still needs fixing.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
