### PR TITLE
Cluster minor QOL update

### PR DESCRIPTION
**Pull request by OliverOtter**
## About the PR
This PR gives cluster some minor but nice changes. These are:

- Emergency lights in the AI satellite room
- Swapping a command door in the AI airlock for a secure windoor that only command can access.
- 6 New bombing points for the ninja.
      - AI power gen, which affects comms, cams, and crew monitoring
      - Command Bridge
      - Engineering's SMES banks
      - Front desk of Science
      - Armory front doors
      - Clowns room

- Nav beacons for the station map, this is for all the main departments.
- Correctly linking the salvage airlocks to prevent accidental spacing
- Main halls and some departments have dirty flooring, giving Janitors something to do while not cleaning up after the crew/antags.
- Space cleaner dispenser inside the Janitors closet
- Swapped the positions of the Security hardsuit with the table holding some materials for the secfab, making it slightly less annoying to get
- A slightly modified abandoned interrogation room.
- A water cooler for Security (No more wardenloose)
- One defib per departments that lack it. (Science, security, Cargo, engineering)
- Smile in science!

## Why / Balance
At the time of writing, ive been told that cluster currently doesnt have a maintainer. Id like to offer my assistance to the community by helping with some QOL changes for it and potentially listen to feedback from the playerbase on what would be nice to have added/removed. Cluster doesnt get much love, and it should get some more.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Emisse** [comment]
remove the tiny fan you added and just link the airlocks instead to autocycle

**Comment by TsjipTsjip** [comment]
CL also needs to be shortened, general rule of thumb there is: Unless it is a huge change (entire department rework or something along those lines), don't include your changes in CL.

**Comment by UbaserB** [comment]
Small map updates dont usually have a CL

**Comment by OliverOtter** [comment]
Changed some more things, these include:
-Removed the CL
-changed tiny fan for linking the airlocks door correctly.
-Added space cleaner dispenser in Jani closet
-Swappoed position of Sec Suit with table of plastic and metal, that was previously unreachable unless the suit storage was open.
-Modified the abandoned interrogation room slightly to give a small story
-Added water cooler for security
-Added One defib to departments lacking one
-Added smile

**Pull request merged**
