### PR TITLE
Whisper bleed update v3

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR
Current changes: 
- Decreased passive bleed wound clotting by 60% (now 0.33u)
- Decreased all bloodloss damage (as a result of bleeding) by 50%
- Added bleeding message to health analyzers.

As a result:
- it takes ~4 minutes to gain 50 bloodloss damage (sloping down), without ***ANY*** action taken, which would increase the time.
- bleed wounds will need to be treated.
- blood level will need to be regulated.
- shouldn't cause as many deaths as the original implementation and my first change.

for bleed reducing items we have:
- Tourniquet: stops all bleeding, 0.5s doafter
- Suture: stops all bleeding, bruise pack doafter
    - Gauze: same as above
- Cloth:  stops 5u bleeding (2 can be combined into gauze)
- Any heat damage(cauterizer, lasers, lightbulbs): scales 1-1 with bleed reduction, instant
- Tranexamic Acid: stops 6u bleeding per 1u 
- Emergency medipens: contains tranexamic acid, will stop all bleeding on use.
- Inaprovaline: stops 0.25 bleeding per 1u

You take (bloodloss) damage when your blood level (300u) is below 90% (270u) Which scales with how low your blood level is.

Things that increase blood level:
- All mobs, passive: 1u every 3 seconds
- Iron: restores 40u per 1u (except spider) (at 0.1u per second)
    - Copper: Above but for spider
- Saline: restores 12u per 1u (at 0.5u per second)
- Protien (minor)
- Blood packs: 15u per use.

bloodloss is a damage type that collects by having a low blood level.

Things that heal bloodloss damage:
- All mobs, passive: -1 every 3 seconds when above 90% blood level
- Dexalin: 3 damage of combined airloss and bloodloss per 1u
    - Dexalin plus:  13 damage of combined airloss and bloodloss per 1u

## Why / Balance

Bleeding currently has little/no effect in gameplay
- It passively treats itself so fast that bleed reductions are never needed
    - Which results in literally everything else about bleeding never coming into play

## Media

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Will affect any downstream species that inherit.

**Changelog**

:cl: Whisper
- tweak: Bleed wounds will no longer heal so fast they do not need to be treated. Please see the medical guidebook.
- tweak: Decreased passive bleed wound clotting by 60% (now 0.33u per 3 seconds).
- tweak: Decreased all bloodloss damage (as a result of bleeding) by 50%.
- add: Health analyzers will report if your patient is bleeding.

### CODE REVIEW

**Comment by botanySupremist** [comment]
Will be interesting to see where this goes, I have to agree that bleeding does little at the moment

**Comment by UbaserB** [comment]
exciting

**Comment by Hmeister-real** [comment]
would be neat if losing blood made you actually look paler if you're a human, good for downstream. Don't know about how you'd do it with species that have fur or scales, but humans would look neat.

**Comment by QuietlyWhisper** [comment]
Added this
image

**Comment by QuietlyWhisper** [comment]
should be all good now

**Comment by QuietlyWhisper** [comment]
Don't think those test fails are mine, one of them is for Packed.

**Comment by QuietlyWhisper** [comment]
build error is for Packed

**Comment by QuietlyWhisper** [comment]
rerun test pls :(

**Comment by metalgearsloth** [comment]
> rerun test pls :(

merge master

**Comment by QuietlyWhisper** [comment]
Ty for the idea sloth I will remember this for future prs

**Comment by QuietlyWhisper** [comment]
Another unrelated error

**Comment by Emisse** [comment]
whisper mald sesh incoming

**Pull request merged**
