### PR TITLE
Add guidebook for Station AI and Silicons in general

### LINKED ISSUE #31549: AI needs guidebook
wub

### PR DESCRIPTION
**Pull request by dragonryan06**
## About the PR
- Closes #31549

I've never written guidebook stuff before, let me know if anything needs improvement! 😊

## Why / Balance
Gives helpful information on Station AI and silicons in general to new players

## Media
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Station AI now has a guidebook entry

### CODE REVIEW

**Comment by august-sun** [comment]
I was looking for this because I think a couple things are worth mentioning, edit-wise:

1. Some rewording would be beneficial:
a. The AI can interact with MOST electronics, including computers. (The examples included are solid though)
b. It would be best if the AI-internal interfaces were listed out so people knew what each button meant ahead of time, if possible.

2. Also worth mentioning that because the AI has control over electronic equipment, it can (and should) help the station in a variety of ways beyond calling out suspicious or illegal behavior. I know you mention "acting as dispatcher", but giving specific examples (sealing off dangerous atmospheric areas, locating anomalies, ordering things for cargo if they're occupied, etc.) gives players new to AI the idea of versatility. At the moment, a big complaint about AI is how many players skew towards acting as security's "watchtower" because all they're thinking about doing is... Looking at things. Giving them encouragement to be proactive and supporting all the departments not only gives them flexibility, it also makes for interesting gameplay because it creates openings for antagonists to do illegal things/work on their objectives.

This seems more abstract, I realize, but the guidance does make a big difference. In SS13, AI typically requires a lot more playtime, and part of that comes with having versatility in your playing experience across all departments. Just something to keep in mind!

**Comment by dragonryan06** [comment]
Yeah, thank you for the advice! I'm not sure what the standard policy is with guidebooks, but I really opted for just dipping the player's feet in. I figure, if AI requires more hours to play, then the guide for new players should reveal enough information that their ability to learn the rest isn't too hindered, but not so much that all the joy of discovery is spoiled for them. 

Like, if I listed every single lawset or something including the one about squirrels, then that wouldn't be a funny moment of discovery for them later when it inevitably happens in a round they're in. 
Or, if I described in detail the AI-A wire on electronics and that it can be cut, then it wouldn't be an interesting experience for the aspiring young hacker.

And, as part of that, I gave very basic examples to try to avoid telling the player specifically "This is what you SHOULD (tm) do", because it can vary based on server and RP level and laws, and plus it's just fun to explore the sandbox of the game and to develop (within reason) gimmicks of your own, especially when playing a silicon.

I considered doing the internal-AI things, but I thought that was more subject to rapid change so I hesitated and figured it could be added once AI is more stable

But yeah I mean if this doesn't get merged soon it's gonna be so out-of-date so fast anyway, probably should've waited longer to hop in on this. The "Station AI Announcement" thing in chat probably warranted some joke about "delivering PSAs" but that was added after the fact, and who knows what other awesome stuff is coming down the pipe next!

**Comment by Moomoobeef** [comment]
I think I might work on my own AI guidebook for this issue. If/when I make the PR I welcome your feedback.

**Comment by dragonryan06** [comment]
> I think I might work on my own AI guidebook for this issue. If/when I make the PR I welcome your feedback.

Yes! I would definitely say wait a little bit though, it was just stressing me out how outdated this PR was getting, I'd hoped for a faster merge and for it to be a temporary start while we waited on more features but pretty soon I realized I just jumped the gun on documenting something still being worked on loll

Take anything you want from my stuff! Or nothing at all!

**Comment by Festivite** [comment]
This still needs to be done and is a glaring omission from the currently available jobs and roles. Given I've been trying to bring up the wiki up to pace in a lot of ways I felt like this was right up my alley. Mind if I take a stab at doing this - taking what's still relevant here/the basic template - since it's still not represented in the game?

**Comment by dragonryan06** [comment]
> This still needs to be done and is a glaring omission from the currently available jobs and roles. Given I've been trying to bring up the wiki up to pace in a lot of ways I felt like this was right up my alley. Mind if I take a stab at doing this - taking what's still relevant here/the basic template - since it's still not represented in the game?

Absolutely, take whatever you want! That's great you're working on the wiki too salute to you! I need to get back into contributing I just don't feel super excited looking at the almost 900 open PRs rn... Good luck!

**Comment by Festivite** [comment]
That's completely fair haha, and thank you! I really think the wiki and guidebook are underlooked as THE newplayer thing people look at so I am trying to make them have at least the most common basic things. 
Also I really liked the look of this PR!

**Pull request closed without merging**
