### PR TITLE
Printable Special and Empty Mags for Autolathes

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

follow up to #26178 that covers the autolathe emag interaction, replaces printing single ammo with full mags or empty mags + ammo boxes

I removed all the now unused recipes for printing bullets one by one

I also updated the ammo fab to do the same, honestly have no idea what the ammo fab is even used for. But now every lathe/fab is caught up to speed now.

## Why / Balance

printing single bits of ammo sucks, people just dump the default magazine and fill it with the ammo of their preference

## Technical details

just yml changes

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/d2f8b95d-6aea-4873-8063-be9a0c5802fa

## Breaking changes

**Changelog**

:cl:
- add: The emagged autolathe now has recipes for ammunition boxes and pre-filled magazines of every type of ammo.
- add: You can now print empty magazines at the emagged autolathe.

### CODE REVIEW

**Comment by Plykiya** [comment]
god almighty... how do forty nine tests fail for a yml change?

**Comment by Plykiya** [comment]
we gucci

**Comment by Plykiya** [comment]
> Yay, finally I will know which clip have rubbers and which is lethals. :trollface:

rubbers getting removed from the game unironically saved both PRs

**Comment by thebadman4662** [comment]
> > Yay, finally I will know which clip have rubbers and which is lethals. :trollface:
> 
> rubbers getting removed from the game unironically saved both PRs

Yeah, sorry, I thought its the previous PR, not the merge for emag interactions and stuff. 😉

**Comment by Plykiya** [comment]
> > > Yay, finally I will know which clip have rubbers and which is lethals. :trollface:
> > 
> > 
> > rubbers getting removed from the game unironically saved both PRs
> 
> Yeah, sorry, I thought its the previous PR, not the merge for emag interactions and stuff. 😉

speaking of which, I should probably PR a change to the sprites so that the mag colors match the ammo tip colors

**Comment by IProduceWidgets** [comment]
Can you please sort the lists alphabetically

**Comment by Plykiya** [comment]
> Can you please sort the recipes alphabetically

I tried that when I first worked on the PRs and it ends up being a bit less easy to understand than the current sorting of mags then ammunition boxes by type of special ammo (it was sorted like this originally)

**Pull request merged**
