### PR TITLE
Fix sprite of newly-spawned empty power cells

### LINKED ISSUE #14251: powercells use full state when first crafted even though they empty
## Description
title

**Reproduction**
1. research powercells
2. make one at lathe
3. see it has 0% charge but using full state

**Screenshots**

### PR DESCRIPTION
**Pull request by h3half**
## About the PR
Fixes #14251 

Looks to me like `PowerCellHighPrinted` inherits properties from `PowerCellHigh`, which includes this bit which applies the green light to a fully-charged pack. Overriding that seems to fix the issue.

**Media**

Image of admin item spawn panel before this fix:
image

Image of admin item spawn panel after this fix:
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Freshly-printed powercells no longer look like they're fully charged.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Doesn't this mean they won't ever look fully charged if you exclude that layer?

Seems like it should just be invisible by default maybe.

**Comment by h3half** [comment]
You're right, it doesn't update when charging. I just checked master and it _does_ update the sprites once they start charging, but not while they're on the charger. It stays in the "depowered" state when on the charger (you can even put a full cell into the charger and the light will turn off) and you have to remove the cell from the charger to see a blank or yellow light. Not sure if that's intended or not.


I don't see an obvious way to set the `unshaded` layer invisible in the `.yml` file, but I'm new here so maybe there's an easy fix there. There's also this code in `OnPowerCellVisualsChange`:

```
if (_appearance.TryGetData<byte>(uid, PowerCellVisuals.ChargeLevel, out var level, args.Component))
        {
            if (level == 0)
            {
                unshadedLayer.Visible = false;
                return;
            }

            unshadedLayer.Visible = true;
            args.Sprite.LayerSetState(PowerCellVisualLayers.Unshaded, $"o{level}");
        }
```
        
But I think this only runs after an `AppearanceChangeEvent`, so the power cells still spawn with the incorrect sprite. I could make a new function in `OnPowerCellVisualsChange` that just serves to make the `unshaded` layer invisible if the charge level is zero, if that seems like a good idea?

**Comment by h3half** [comment]
Sloth pointed out in discord that I can just make `visible` false right in the `.yml` file 🤷‍♂️

**Review by EmoGarbage404 — APPROVED** [review]
looks good

**Review by Emisse — APPROVED** [review]

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
