### PR TITLE
Tracking & Implanter Crate

### PR DESCRIPTION
**Pull request by luckyshotpictures**
## About the PR

This adds a crate containing mindshield and tracking implanters, locked by security access. The crate contains 4 items of both implanters. The crate is not obtainable through normal means like cargo.

## Why / Balance

This has been requested by some mappers for the mapping requirements in the security department.

## Media

Screenshot_211

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by keronshb** [comment]
Mindshields and Tracking Implants should be 100% to be ordered by cargo and not on station.

Having them already on station is a huge powercreep that I've experienced before and it's toxic for the game.

**Comment by deltanedas** [comment]
mindshields are still mapped in every armoury

**Comment by LordEclipse** [comment]
> Mindshields and Tracking Implants should be 100% to be ordered by cargo and not on station.
> 
> Having them already on station is a huge powercreep that I've experienced before and it's toxic for the game.

Hasn't security always had roundstart mind-shields though? Its not very many, like 3-4, it also helps prevent somewhat rev snowball

**Comment by TsjipTsjip** [comment]
> Mindshields and Tracking Implants should be 100% to be ordered by cargo and not on station.
> 
> Having them already on station is a huge powercreep that I've experienced before and it's toxic for the game.

Preferrably do consult with Emisse, as mindshields and tracking implants being available roundstart to the warden was specifically requested in #cartography by them. This is the reason maps have this. As for this PR, this just combines those requirements into one crate which does really help in terms of mapping, as you now no longer need to map two crates.

**Comment by UbaserB** [comment]
Yeah emisse just pinged us in cartography a little while ago to make sure we have those 2 crates mapping; this PR is a blessing because now it takes up less space

**Comment by Emisse** [comment]
discussed with keron, this is fine 4 naow

**Pull request merged**
