### PR TITLE
add random farting

### PR DESCRIPTION
**Pull request by Slava0135**
## Media

https://github.com/space-wizards/space-station-14/assets/40753025/4a42b01c-4679-4574-abea-4a63148116f0

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Slava0135** [comment]
no idea why mice don't fart until i control them

**Comment by VektorZ1** [comment]
💀

**Comment by brainfood1183** [comment]
hope this is for april fools?

**Comment by lzk228** [comment]
i think firstly its gonna be fun but after some time itll become annoying

**Comment by Krunklehorn** [comment]
Make it trigger on hug with a very, very low percentage. Way more funny when its awkward.

**Comment by Slava0135** [comment]
To make it clear, its pretty rare - every ~15 minutes, for video I set chance much higher

**Comment by deepdarkdepths** [comment]
> To make it clear, its pretty rare - every ~15 minutes, for video I set chance much higher

So you're saying every 15 minutes the entire station will fart en masse within a 1 minute span

**Comment by Slava0135** [comment]
No, its random, every second there is 0.001 (0.1%) chance to fart, on average its about every 15 minutes

**Comment by VasilisThePikachu** [comment]
I'm not a maint so I can't close this... However I will make emo suffer

**Comment by 0x6273** [comment]
> No, its random, every second there is 0.001 (0.1%) chance to fart, on average its about every 15 minutes

I think that's way too frequent. It should be like once per round on average.

**Comment by Slava0135** [comment]
> > No, its random, every second there is 0.001 (0.1%) chance to fart, on average its about every 15 minutes
> 
> I think that's way too frequent. It should be like once per round on average.

Wdym, its just the time of average LRP round on Lizard \s

**Comment by EmoGarbage404** [comment]
for human posterity, there will be no pooping or farting on the SS14 repo.

**Comment by juliangiebel** [comment]
Farting 1984

**Pull request closed without merging**
