### PR TITLE
Rudimentary Spells

### PR DESCRIPTION
**Pull request by ElectroJr**
This adds rudimentary spells to the game. These mostly serve as examples for the actions rework (#6791), which this PR relies on. As a standalone, this PR is pretty bare bones, and the spells are currently unobtainable other than as rare salvage loot. They could easily be added to the traitor uplink or something, but then they probably need to be balanced. Unless people are happy adding them in their current state, or with minor tweaking, this PR will probably just become a derelict, though hopefully serving as a basic template for someone else to add a proper magic/wizard role.

The actual mechanics are extremely simple: there are three spell books, If you wield the book in both both hands (its a big book I guess?) you get access to two spells per book. Each spell has a limited number of uses (per book). There are currently just projectile-spells (which just reuse gun-code), reagent-effect spells (which just hijack the existing reagent effects to work), and a teleport spell.

## Video

https://user-images.githubusercontent.com/60421075/155472692-0fb89763-18b5-4952-9a32-29c50a960609.mp4

## Issues

The existing spells are somewhat incomplete/janky. The existing spells probably need:
- more vocalization/speech when casting them
- Sound effects
- Visual indicators for other players that magic is being cast, 
  - Especially for direct entity targeting magic, currently there is no visual feedback other than maybe speech bubbles.
- Decent visuals for hitscan-projectiles
  - AFAICT hitscan weapons just stretch a single png, which only really supports simple beam weapons like lasers, but not something like lightning where the beam is constructed from a series of lightning-segments. The current lightning bolt looks shit.
  - improved particle / effects system when?
- Better sprites for actions & books. Some are fine, but for others I just pilfered loosely related icons from TG.

Other than adding more speech text, this is all stuff I'm not great at and is probably better left  for someone else to address. If people want to add onto this PR, feel free to do so..

### Balance

If people are fine with adding them more or less as is and just improving the system over time, then until a proper wizard gets added they should probably at least be accessible via the uplink just to that they actually get tested in game. But then they also need to be balanced, which... uhhh.... not sure how to best do that.

If you get something like the teleport spell, and you don't accidentally teleport into a wall it makes many objectives pretty easy. And the fireball spell is sorta like 3 on-collide grenades + nuisance ignite spell. For reference, basic single-use grenade costs 4 tc, so this should probably be 12+ TC? A shitty way to stop pre-planned power gaming is to just randomly select a book, instead of allowing the user to choose. The choice to make the spells bound to the book, and to require the user to wield the book with two hands is another shitty balancing attempt.

## Wishlist

A full spell-system probably needs to support:
- do-after-spells (with chanting + visuals?)
- on-collide projectile magic (i.e., on collision, cast a spell on the colliding body)
- on-collide effects for beam weapons
- nicer visuals for beam weapons (or particle effects in general)
- Innate spells, spell learning/purchasing, spell-recharging, 
  - This should probably be kept separate from the spells-system, as it belongs more to some sort of wizard role/job system.
- Add more effects (either specialized to spells or reagents, or by adding some generalized effect-causing system)
	- E.g., the `Ignite` reagent effect really has nothing to do with reagents, making it a bit weird for the ignite-spell to use reagent effect,  when it should probably be generalised somehow.

### CODE REVIEW

**Comment by mirrorcult** [comment]
finally, a representative from the space wizards federation

**Comment by Peptide90** [comment]
Looks great however that fireball spell looks hella big. I don't have a frame of reference from 13 but 3 grenades surely is like instagib? 

I agree it should be strong and probably knock limbs off but yeah.

**Review by ElectroJr — COMMENTED** [review]
> Looks great however that fireball spell looks hella big. I don't have a frame of reference from 13 but 3 grenades surely is like instagib?

By 3 grenades I didn't mean the force of a single fireball, just that the fireball has three charges. But yeah, all the damage/range values, cooldown, charges were all just picked out of a hat. It had a "devastation" damage bracket, which allowed it to actually deal appreciable damage to walls, but also meant that it instantly killed on a direct hit.

I've lowered the explosion radius so the devastation/heavy/light damage brackets are now 0/2/3.
For reference, the normal 4 tc grenades for sale are 0/2/4.

**Comment by metalgearsloth** [comment]
Re-open when you get time

**Pull request closed without merging**
