### PR TITLE
Flora anom hotfix

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Some nerf flora anom

no more mutated plant, decrease spreading and spawning entities, luminous entities don't leave corpses now.

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by K-Dynamic** [comment]
Yeah but you re-added gatfruit after removing it in the same yml

**Comment by TheShuEd** [comment]
just sorted

**Comment by TheShuEd** [comment]
I'm not gonna take it away :trollface:

**Comment by K-Dynamic** [comment]
> I'm not gonna take it away :trollface:

Based, and now I'm more incentivised as a botanist to give out plant killer near the anomaly

**Comment by deltanedas** [comment]
to not give out*
free guns

**Pull request merged**
