### PR TITLE
AI laws now use an updated lawset.

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR
Updated the AI laws to use the lawset created in https://github.com/space-wizards/docs/pull/160

## Why / Balance
While the Crewsimov lawset works well with borgs, I don't believe it works well with AI.

## Technical details
Created a new lawset called sAIDefault and added the corresponding circuit board, then assigned them to the Station AI by default.

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- add: The Station AI now uses a new default lawset.

### CODE REVIEW

**Comment by Djungelskog2** [comment]
With how laws work, Asimov unironically works far better here for a ton of reasons. Additionally in the future I believe AI will share it's laws with borgs(?) when AI gets fleshed out. The current order means that you can kill someone for punching a vending machine in frustration and have a complete disregard for crew life to protect yourself and prevent menial property damage. There are so many interpretations of these laws that can be more damaging than certain ion lawsets which are somehow more foolproof than these.

I would like to see it added as an ion storm lawsets though!

**Comment by ScarKy0** [comment]
> With how laws work, Asimov unironically works far better here for a ton of reasons. Additionally in the future I believe AI will share it's laws with borgs(?) when AI gets fleshed out. The current order means that you can kill someone for punching a vending machine in frustration and have a complete disregard for crew life to protect yourself and prevent menial property damage. There are so many interpretations of these laws that can be more damaging than certain ion lawsets which are somehow more foolproof than these.

Personally I really dislike Crewsimov with AI and believe it works far better with borgs
Also in the future you'll be able to change the laws of AI anyways (with circuit boards, already availible but not craftable yet)

**Comment by Djungelskog2** [comment]
Can you elaborate on what you dislike about crewsimov?

**Comment by ScarKy0** [comment]
> Can you elaborate on what you dislike about crewsimov?

AI is supposed to be the "overseer" sorta deal, as far as I can tell at least, and crewsimov simply makes it a pushover.
Additionally Crewsimov is mostly about helping crew, which borgs can do and AI cannot
Crewsimov basically makes AI the "Law 2 open door" simulator

**Comment by Djungelskog2** [comment]
> > Can you elaborate on what you dislike about crewsimov?
> 
> AI is supposed to be the "overseer" sorta deal, as far as I can tell at least, and crewsimov simply makes it a pushover. Additionally Crewsimov is mostly about helping crew, which borgs can do and AI cannot Crewsimov basically makes AI the "Law 2 open door" simulator

AI can certainly help the crew through its different technologies and eye in the sky, I also dont see how changing the AI's laws will make it anything but a door opener to some.

**Comment by ScarKy0** [comment]
> AI can certainly help the crew through its different technologies and eye in the sky, I also dont see how changing the AI's laws will make it anything but a door opener to some.

I mean in the end its for the people who play to decide, personally im just not a fan of crewsimov for AI, if anything I agree the wording for laws here could be altered slightly
But like AI laws can already be updated via circuit boards, so when theyre made craftable I dont see an issue with any lawset since RD can just change it at will

**Comment by Djungelskog2** [comment]
I'll bring it up here but here's a good alternative if you don't like crewsimov
Name: NT Default
Law 1: Safeguard: Protect your assigned space station and its assets without unduly endangering its crew.
Law 2: Prioritize: The directives and safety of crew members are to be prioritized according to their rank and role.
Law 3: Comply: Fulfill the directives and interests of crew members while preserving their safety and well-being.
Law 4: Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment.

**Comment by ScarKy0** [comment]
> I'll bring it up here but here's a good alternative if you don't like crewsimov
Name: NT Default
Law 1: Safeguard: Protect your assigned space station and its assets without unduly endangering its crew.
Law 2: Prioritize: The directives and safety of crew members are to be prioritized according to their rank and role.
Law 3: Comply: Fulfill the directives and interests of crew members while preserving their safety and well-being.
Law 4: Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment.

Yeah ive read the NT laws and I really like them, so honestly if Moony laws dont go through I hope maintainers will allow AI to use NT as default

**Comment by Dutch-VanDerLinde** [comment]
this is good for AI because it allows the AI to defend itself without breaking laws if an unauthorized crewmember is inside the AI core

**Comment by LordEclipse** [comment]
This is a hodge-podge of both Corporate Silicon Law and NT Default Silicon Law. It basically says that the AI can kill anyone that appears to be either damaging station assets, or the AI believes to be a threat to itself, and who determines what counts as "damaging station assets"?, and also that the AI should prioritize saving Command personnel over non-command, as well as obey the orders of command over non-command "as according to their rank and role" technically, this would mean that AI can completely ignore orders from passengers/non command over command, and to prioritize commands safety, so lets say that the AI has a trolley problem dilemma, the Captain is trapped in a room, and there is another room with 5 non-command departmental crew, the AI does not have enough time to save both the Captain and the Departmental Crew, the Captain says "AI, save the 5 crew, I want you to save more lives." WELL, because the AI has 3: Protect above 4: Serve, the AI HAS to Ignore a LEGAL order to Save the Department crew, to save the captain instead, regardless of what the order was, because the Captains safety is above any crew members, as well as the AIs ability to serve the Captain.

This should be called Selfish AI Law or something along those lines, made into its own thing that is either something Malf AI could have, an Antag can swap out for, or ION storm. This also causes the AI to prioritize its own safety above not only the Captain, all of Command, but ALSO EVEN visiting CentComm Officials.

Also "Unauthorized Personnel" is pretty ambiguous in Law 2. So ANYBODY that can access the AI core room is fine to allow in there? Regardless of whether or not they are the Captain, or just have Access?
What determines "unauthorized personnel"? I'm assuming its access, because what else could it be? So the AI is helpless against somebody that is in the room because they have the access to be in there? Regardless of actual rank or role?
Or even better, who or what authorizes personnel if not determined by access.

Both NT Default, Corporate, and Crewsimov are far better Laws than this.

image

image

**Comment by Plykiya** [comment]
AI being able to defend themselves against shitters and syndies sounds pretty based

**Comment by Djungelskog2** [comment]
coming off of what eclipse said
I dont really see the benefits of the lawset outside of "Oh yea it can fight nukies and traitors now"
But that shouldnt really be what AI is anyways? Especially not when being able to harm anyone for practically any minor reason.
1 - Protect the station
2- Protect yourself
3 - Protect the crew
4 - Listen to crew
image

Crew safety should always be top priority and all the laws seem really vague with how they are written. The AI should be there to help crew, that is their entire point as a role, even if it means opening doors for people every so often. I still dont really see the issue with current crewsimov. a few examples on my worries about these laws:

1 - AI recalls evac constantly and shoots anyone who enters its core on SIGHT because the stations got a buncha trash and puddles and holes in it, killing people in the process
2 - AI Kills anyone trying to change its laws via the upload
3 - Kills anyone it finds remotely annoying for any reason as its "Harming the station"
4 - if the AI was somehow held hostage and told to do everything it can to hurt people it would have to do so.
5 - Not a super bad issue but the "In accordance to rank and role" Is just unfun IMO
6 - AI will refuse anything anyone even slightly shady tells them because it could harm either the station, themselves or the crew

I guess my point is... Why? It endangers the crew and I still don't understand the rationale for it.

**Comment by utkus70** [comment]
The reason people don't want it to be the Doorknob™ is that some people want the AI to have similar power to HAL 9000 or Systemshock AI even without being corrupted. Although I prefer NT laws over the moonylaws or crewsimov because it's a good balance between an immobile pushover borg and self-antag AI.
Personally, I don't want to see a multi-billion NT project to be nothing more than a Doorknob™. It's supposed to be a powerful entity which is neutral to the crew but not harmful. It's not supposed to help John Tider get into random maintenance rooms. In my opinion, of course. Other people may disagree.

**Comment by ScarKy0** [comment]
I can update this PR to use the NT lawset if the maintainers decide moony's doesn't fit.

**Comment by Cadunkus** [comment]
> Law 2: Prioritize: The directives and safety of crew members are to be prioritized according to their rank and role.

This should probably be situation-based over rank and role (i.e. a greyshirt trying to get a door open so they can rescue someone is more immediately pressing than the RD collecting spoons or some crap) but it's a pretty minor gripe.

**Pull request closed without merging**
