### PR TITLE
Use Door Electronics as the access provider of secure crates

### PR DESCRIPTION
**Pull request by osjarw**
## About the PR
Re-use Door Electronics as the access provider of secure crates. 
I've decided to just use Door Electronics because aren't crates mechanically really similar to doors? Just remove the motor responsible for opening the door and suddenly you've got yourself a crate. 

For now this PR is in an incomplete state, only the constructable form of secure crates uses this behaviour. 
I'm thinking of putting this proposal out there, and upon getting any affirmations of this being an acceptable idea, begin to implement rest of this PR.

## Why / Balance
In order to utilize self-constructed secure crates you need an Access Configurator, and assistance from either HoP or the Captain if you want cross-departmental secure crates. 
With this change, science for example can build secure crates that can only be unlocked by science and cargo, stopping random bystanders from opening the crate during shipment and stealing all your precious plasma. 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/62134478/ade628ff-8ca9-4ceb-8510-030a15db053a

## Breaking changes

**Changelog**

:cl:
- tweak: NT has decided to retrofit secure crates with Door Electronics.

### CODE REVIEW

**Comment by PJB3005** [comment]
> NT has decided to retrofit secure crates with Door Electronics.

No roleplay changelogs.

**Comment by Brandon-Huu** [comment]
Are they able to be hacked?

**Comment by osjarw** [comment]
> Are they able to be hacked?

Currently they can't be hacked. You disassemble them by using an screwdriver, but that is denied if the crate is locked.
So the only way an unauthorized player can open them is by breaking them.

**Comment by metalgearsloth** [comment]
dero

**Pull request closed without merging**
