### PR TITLE
Add kitten pet Chip

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

add pet Chip, he is a kitten
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no fun

### CODE REVIEW

**Comment by Aexxie** [comment]
This is more of a relay than an actual review, but here's what I've heard:

We don't want more pets right now due to the sheer number we already have available. They also all lack gimmicks and are essentially filler content with no actual purpose (minus Ian, maybe, due to them being an objective.)

The main issue with PRs like this is that they don't add any actual content to the game, and instead just bloat it with extra code and sprites that don't actually contribute any gameplay value.

**Comment by lzk228** [comment]
they're not supposed to be on all maps tho

**Comment by Aexxie** [comment]
> they're not supposed to be on all maps tho

The issue stems from them being extra assets - especially those that are unused, or not used frequently - that do not add any new gimmicks or mechanics whatsoever. All it does is add more possible things for people to maintain without changing the gameplay at all.

**Comment by potato1234x** [comment]
> The issue stems from them being extra assets - especially those that are unused, or not used frequently - that do not add any new gimmicks or mechanics whatsoever. All it does is add more possible things for people to maintain without changing the gameplay at all.

does that really matter when we have so many sprites just sitting around not being used

**Comment by lzk228** [comment]
> Add to thief objectives :trollface:

>objective: Chip
>Chip isnt mapped

no lol :trollface:

**Comment by TheShuEd** [comment]
In general, you can set a true variable there to check whether this target exists on the map at all.  I just haven’t checked what works faster: spawning creatures from spawners, or issuing tasks to antagonists.  If the spawners are first, then in one line you can remove from the round the tasks of stealing creatures that were not added to the map

**Comment by Emisse** [comment]
we have too many pets not enough pet mechanics

**Pull request closed without merging**
