### PR TITLE
"Knightship" map - ultra-lowpop intended for ~5 people

### PR DESCRIPTION
**Pull request by 20kdc**
## About the PR

Adds a new map for ultra-low-pop.
Named "knightship" because ~~frankly I couldn't think of a better name~~ one person could run the whole thing and it would function or something IDK.

Intended for possibly 5 people, it's intended to be "compact but functional".

Expected "Standard" Crew (though as always roles are variable):
```
1 Captain (expected to act as cargo, HoP and security)
1 "Chief" Medical Officer (expected to know chemistry)
1 Research Director
1 "Chief" Engineer
1 Chef
```

Features:

+ The map is setup such that an Assistant *should* be able to escalate access to get the whole ship running in a pinch.
+ *There are no SMESes, so setting up an engine is imperative.* This isn't Saltern, the ship will run out of power without someone to setup and maintain the engine.
+ The ship has basic atmos, enough that the ship is refillable but not the endless regenerating atmos of stations.
+ Engineering have something to do: figure out how to expand the ship. Because if they *don't*, the people will get claustrophobic very, very quickly.
+ Mapped out spawns for Suspicion and TraitorDM

TODO:
+ I need to check if this name is already occupied and if so figure out a new name

**Screenshots**
image

**Changelog**

:cl:
- add: Added a new map, "Knightship", meant for very low populations.

### CODE REVIEW

**Comment by 20kdc** [comment]
...I keep hitting the make PR button and I keep forgetting I can't convert them to drafts afterward AAAAAAAAAAAAAaaaaaaaaaaaa

**Comment by 20kdc** [comment]
Made some changes to ensure Kitchen can operate properly, voting for the map is setup, marking as ready for review

**Comment by moonheart08** [comment]
real speedmerge hours.

**Review by moonheart08 — APPROVED** [review]

**Comment by mirrorcult** [comment]
not sure how i feel about this, if this is merged we probably really need support for barring maps from the vote based on populations

**Comment by PaulRitter** [comment]
> 
> 
> ...I keep hitting the make PR button and I keep forgetting I can't convert them to drafts afterward AAAAAAAAAAAAAaaaaaaaaaaaa

hidden af but its there
image

**Comment by PaulRitter** [comment]
> 
> 
> not sure how i feel about this, if this is merged we probably really need support for barring maps from the vote based on populations

yes, but i'd say we wanna add pop-dependent map-voting regardless

**Comment by PaulRitter** [comment]
idunno about putting it into the defaultvotes tbh

**Comment by 20kdc** [comment]
I mean I get the feeling moony wants this merged solely to torture players, and if that's the case I'd rather just close the PR

**Comment by juliangiebel** [comment]
I would still merge it just with it not being voteable. Until pop limits are in

**Comment by moonheart08** [comment]
> I mean I get the feeling moony wants this merged solely to torture players, and if that's the case I'd rather just close the PR

Nah, looks like a really cool lowpop map.

**Comment by 20kdc** [comment]
@juliangiebel I've reverted the commit that makes it votable on the basis of two votes for not-votable

**Review by juliangiebel — APPROVED** [review]

**Comment by PaulRitter** [comment]
ideally i'd like for our tests to try loading *all* maps, not just saltern so we can make sure nothing is broken (#5403)

**Pull request merged**
