### PR TITLE
make mindshields craftable at the secfab

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

made mindshields craftable at the secfab
## Why / Balance

There have been too many rounds where the revs take cargo and make it impossible to order mindshields through either spending money or just straight up destroying the cargo console, and making a counterplay painfully difficult. 

This pr attempts to balance that out by allowing security to make mindshields as a last resort, albeit expensively so they can't spam them.
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Security Techfabs can now print mind-shield implants, expensively.

### CODE REVIEW

**Comment by Aisu9** [comment]
this is great, but wont sec still need cargo for the resources?

**Comment by Rainbeon** [comment]
Where is Sec getting silver and gold from?

**Comment by Aisu9** [comment]
plastic can be easily made using welding fuel and a heat plate, steel can be scavenged from chairs/tables, same for glass. seem a little on the high end if cargo can't provide resources (and cargo will most likely no provide resources knowing the meta of this gamemode)

**Comment by deltanedas** [comment]
indiana jones and the temple of doom

**Comment by Admiral-Obvious-001** [comment]
The issue with that is mostly the silver which is generally just really hard to find on a lot of maps by default, and that assumes science hasn't poached it first.

**Comment by Aisu9** [comment]
> indiana jones and the temple of doom
> 
> (they somehow steal them from vault before sci does)
> 
> or get salv to [work directly with sec](https://tgstation13.org/wiki/Byond_the_impossible)

if cargo is compromised, usually salvager were before cargo techy were converted

**Comment by icekot8** [comment]
dude... sprite... it's not made... make it...
изображение

**Comment by foboscheshir** [comment]
when the miners do his work, sec can make  everyone has a mindshield :trollface:

**Comment by MACMAN2003** [comment]
> Where is Sec getting silver and gold from?

this is intended for emergencies where cargo can't or won't buy mindshields, so the captain would likely steal some from sci or the RD would donate some

> dude... sprite... it's not made... make it... изображение

i have no idea why the implanter sprite isn't showing

**Comment by MACMAN2003** [comment]
i'm for the removal of gold and silver from the recipe i just feel like that'd make it too easy to mass produce them

**Comment by Kadeo64** [comment]
> i'm for the removal of gold and silver from the recipe i just feel like that'd make it too easy to mass produce them

10 steel 5 plastic 3 glass then? Easy to make a few but the steel and plastic will add up over time.

**Comment by Kadeo64** [comment]
> > 10 steel 5 plastic 3 glass then? Easy to make a few but the steel and plastic will add up over time. (assuming cargo isn't working with security, of course.)
> 
> i like this, can make for a war of attrition or of who can deconstruct the most chairs before the other side does

yeah, or a fight over disposals to use the material reclaimer. losing side gets tossed into the recycler.

**Comment by Krunklehorn** [comment]
If gold and silver is involved you know security is going to beeline for the vault every single shift.

They might also be incentivized to bully departments like science or even steal from them if an officer happens to be in the lathe room at some point.

**Comment by keronshb** [comment]
For the moment we're still not going to allow mindshields to be mass produced.

We're highly considering disabling revs until a larger rework is done. If you made a PR that turned their chance to 0 it'd more than likely be merged at this point.

The smaller bandaid PRs, while nice, are still just bandaids not fully addressing the larger problem.

**Pull request closed without merging**
