### PR TITLE
Train map fix

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

- fix train atmos
- return train to rotation

**Changelog**
:cl: The Hands Leader - JoJo cat
- tweak: Train map is back into rotation

### CODE REVIEW

**Comment by Wudanty** [comment]
> we are so back trainbros

So fucking back trainbro

**Comment by thebadman4662** [comment]
Was cryo pod atmos fixed as well or it was just pipestacking stuff? Turning on pump would depressurize distro on whole station before on top of cryo pods not working due to broken setup.

**Comment by Brandon-Huu** [comment]
Was it taken out of rotation just because of atmos?

**Comment by IProduceWidgets** [comment]
Webedit 😱

**Comment by Emisse** [comment]
ill put it back in for sillys but when map list stuffs are all done i intend to scrutinize every map a lot

**Pull request merged**
