### PR TITLE
Species Reworks

### PR DESCRIPTION
**Pull request by LankLTE**
I will re-add and fill in the rest of the details once this is closer to being finished. For the what and why, look at this [design doc](https://hackmd.io/-CnGYVtPQ2CHOJFp_ZYclA#Race-Rework-Proposal), under "Race Rework Proposal." If there's a problem with any of the designs I've outlined, please tell me before I decide to go and code it all.

As for what actually needs to be done (I've gone through and laid this out in the order I intend to do it):

Moths:
- [X] Numerical Changes

Diona: 
- [x] Numerical Changes
- [X] Basic Nymph Mob
- [X] Spawning Nymphs on death
- [x] Transferring mind to allow borging
- [x] Fire stacks from heat damage
- [x] Spawning Nymphs on command
- [x] Action to gib self after death
- [ ] Nymph Reforming

Lizards:
- [x] Numerical Changes
- [x] Dragging with Tail
- [x] Restrict diet to Meat and Fruit

Slimes: 
- [x] Numerical Changes
- [x] Passive Regen
- [ ] Reform from Brain

Final Bit I should do:
- [ ] Admin logs for reforming and spawning nymphs

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by NancokPS2** [comment]
Slimes reviving is just too much. Even if it makes sense.    

The passive regen sounds like very big change too, maybe lower the damage cap to 20 or 15? And rise slime regen cap to 30 instead of having faster regen

**Comment by NancokPS2** [comment]
Reviving after death seems busted overall. Creating more players even more so.  
Not from a balance perspecrive, but because it simply messes with the game's dynamic.  
Also, breathing CO2 kinda ruins some antag strats entirely, but i guess it is fair for a race that is so slow

**Comment by CrigCrag** [comment]
diona can already breath CO2

**Comment by LankLTE** [comment]
> Reviving after death seems busted overall. Creating more players even more so. Not from a balance perspecrive, but because it simply messes with the game's dynamic. Also, breathing CO2 kinda ruins some antag strats entirely, but i guess it is fair for a race that is so slow

Diona breathing CO2 is already a thing. 
Reviving after death is something I'm trying to do in a balanced way. To put it simply gibbing a body or spacing it will still work- all this will really counter is leaving the body in maints and hoping people don't find it before it rots (which is lame anyways in my opinion), especially for a race with that many downsides. Making new players is also gonna be balanced in a way to make it relatively uncommon- I don't want ghost roles being spammed.

**Comment by Anzarot121** [comment]
I've read in your document especially arachnids. Damn it, this is a species created purely for power gaming, they have no cons at all. They are faster without meth than humans under meth, stronger, have 4 arms, feel hunger and thirst less often than humans.

**Comment by NancokPS2** [comment]
> 
> Diona breathing CO2 is already a thing. Reviving after death is something I'm trying to do in a balanced way. To put it simply gibbing a body or spacing it will still work- all this will really counter is leaving the body in maints and hoping people don't find it before it rots (which is lame anyways in my opinion), especially for a race with that many downsides. Making new players is also gonna be balanced in a way to make it relatively uncommon- I don't want ghost roles being spammed.

My bad on Dionas.  
  
But dying should not be this meaningless and this is just busted even if delayed. Getting jumped in maints is part of the maints experience. It is already pretty trivial to revive people.   

Without mentioning that waiting a while is very un-engaging.

**Comment by LankLTE** [comment]
> I've read in your document especially arachnids. Damn it, this is a species created purely for power gaming, they have no cons at all.

They no longer move faster- the document doesn't say they do either. I still think their upsides far outweigh their downsides, however. 

>Getting to revive with your memories ruins a lot of game dynamics.

This is already how reviving works..? Defibbing works like this (and slimes, diona and moths currently don't rot, so they can be ghosted for literally *an hour* just to get revived and keep their memories. Cloning also works like this, and that's *literally* getting a different body. Diona are supposed to be made of several nymphs combined- it only makes sense they would keep memories.

**Comment by LankLTE** [comment]
> But dying should not be this meaningless and this is just busted even if delayed. Getting jumped in maints is part of the maints experience. It is already pretty trivial to revive people.
> 
> Without mentioning that waiting a while is very un-engaging.

If you get jumped in maints the person who jumped you is fully capable of killing a nymph that moves slower than a player and has 30 health when it spawns. Nymphs are also able to move around and say stuff still, so it isn't like you can't do *anything*. Slimes are sort of a different story, since they're technically doing "nothing" while waiting to reform, but you're already perma-dead when gibbed normally anyways so to the idea is you'll chill a bit as a ghost before reforming.

**Comment by NancokPS2** [comment]
I think nymphs are fine since you just create your own ghost role, my issue are slimes.  

Dying is part of the game, no one should get to circumvent that on their own.   
Specially by just selecting a race at round, if this is added slimes should not be eligible as a round start race.

**Comment by Anzarot121** [comment]
> I think nymphs are fine since you just create your own ghost role, my issue are slimes.
> 
> Dying is part of the game, no one should get to circumvent that on their own. Specially not by just selecting a race at round start, if this is added slimes should not be eligible as a round start race.

Then no one other than humans should be the roundstart race.

**Comment by Aisu9** [comment]
is this possible to borg dionas and slimes? because if they cannot i do think the "self" revive mechanic is good, they should tho in a sense be less than what they were and still count as dead for syndicates objectives

**Comment by Interrobang01** [comment]
shouldn't this be split into 1 pr per species change, instead of all of the changes at once?

**Comment by LankLTE** [comment]
> is this possible to borg dionas and slimes? because if they cannot i do think the "self" revive mechanic is good, they should tho in a sense be less than what they were and still count as dead for syndicates objectives

"still count as dead for syndicates objectives" defeats the entire point. This is supposed to be an upside. if cloning doesn't count as dead this shouldn't either. You can very easily throw the slime core into space or just keep it on you, and I've talked before about how Nymphs are easy to kill.

> shouldn't this be split into 1 pr per species change, instead of all of the changes at once? (pr is unfinished obviously but i feel like it might be an issue once done)

Maybe, this just felt fitting since it addresses two issues on github and follows one design doc. If maints wish I can split it pretty easily

**Comment by Aisu9** [comment]
> "still count as dead for syndicates objectives" defeats the entire point. This is supposed to be an upside. if cloning doesn't count as dead this shouldn't either. You can very easily throw the slime core into space or just keep it on you, and I've talked before about how Nymphs are easy to kill.

yeah but if they can't be borged what would be their alternatives for half-revive? other than self revive that can be prevented by PK them by throwing the self regenerative stuff in space? it exist but is frown upon even on Lizard for information. so you just want these two species to be permanently killable very easily but still giving them a false chance to survive?

**Comment by LankLTE** [comment]
> these two species to be permanently killable very easily.

They're just as easy (or difficult) to perma kill as every other species. I don't really see how this is a point. They can still be borged, but people are discouraged from doing it to slimes as they have a way to revive themselves.

**Comment by VasilisThePikachu** [comment]
Im gonna join the argument against self revives, this will just encourage spacing and gibbing bodies which i see as good and bad. 

But being able to self revive gets rid of the reason of med to do that for you. I think its better if it required at least some kind of other player interaction first. This may also feel unfair to species without the revive ability, why can they get to play the game after a bit of timeout while they sit in a locker dead for the rest of the round?

**Comment by BolloTea** [comment]
why do then any features of the races, if they give certain advantages?

**Comment by BolloTea** [comment]
If you are confused by the "indestructibility" of the slime core, then do not forget about cremation.  Besides, I'm more than sure that it will be possible to do other ways of final killing.  To me, this is just a small test for the antagonists, which will make them think more radically.

**Comment by LankLTE** [comment]
> But being able to self revive gets rid of the reason of med to do that for you. 

Med is already fully incapable of reviving gibbed bodies. The slimes rework doesn’t take anything away from them. The diona rework I intend to do in a way that getting revived via Nymph is worse than being revived normally and it’s something you’ll only do if you have to. I don’t see how this is removing med gameplay at all. 

> This may also feel unfair to species without the revive ability, why can they get to play the game after a bit of timeout while they sit in a locker dead for the rest of the round?

Because they picked a different race and they have different upsides? You could make this argument for race upsides that are already in the game. Why do humans get to use emergency suits for a super long time when Lizards die almost instant after using it? Why do other classes have to suffocate so quickly when slimes take forever?

**Comment by LankLTE** [comment]
> To me, this is just a small test for the antagonists, which will make them think more radically.

this is basically how I feel. Worst case antags have to think a little lore and maybe change up their game plants I won’t see that as a huge problem. 

I’d also like if some of the people relentlessly hating on it could give me something they think would work better, because the truth is I don’t have any other ideas and think these reworks will do a good job of making the race more interesting

**Comment by VasilisThePikachu** [comment]
> I’d also appreciate if some of the people hating on it could give me something they think would work better

I never claimed I hated it, maybe I can be convinced otherwise. I'm just giving my opinion on it from what I read. But yeah I got nothing honestly much.

Maybe for Diona their upside can be #17279 once it gets merged but this or something else could be a replacement until then

> Med is already fully incapable of reviving gibbed bodies. The slimes rework doesn’t take anything away from them. The diona rework I intend to do in a way that getting revived via Nymph is worse than being revived normally and it’s something you’ll only do if you have to. I don’t see how this is removing med gameplay at all.

I am not talking about gibbed bodies, from my understanding from your doc this is for bodies that were just left to rot, not for gibbed bodies. How would reviving as a Nymph be worse exactly? And what about slimes? do they get a disadvantage from self reviving?

> Because they picked a different race and they have different upsides? You could make this argument for race upsides that are already in the game. Why do humans get to use emergency suits for a super long time when Lizards die almost instantly after using it? Why do other classes have to suffocate so quickly when slimes take forever?

Here is the thing, yes being unable to wear an emergency suit can be a major disadvantage. But being able to revive yourself out of the blue cause "you waited long enough" just sounds unfair for the lizard watching you even if doing it yourself is worse than getting revived normally. At least you are still playing while in the emergency suit and have time to space walk to a safe spot(also I used a space suit as a lizard fine before it takes long till cold hits you), you have a chance to turn on internals before you suffocate. #19138 is removing the 4 hand slots too from arachnids so they are losing this huge buff of theirs

**Comment by LankLTE** [comment]
> I am not talking about gibbed bodies, from my understanding from your doc this is for bodies that were just left to rot, not for gibbed bodies. How would reviving as a Nymph be worse exactly? And what about slimes? do they get a disadvantage from self reviving?

Slimes cannot self-revive from being left to rot,  only from being gibbed. They also can’t rot, so they just have to hope someone finds them. Diona if left to rot will eventually split and be able to revive themselves, yes, which is part of their upside. It’s worse because all of your things get left behind, you have to stay as a very easy to kill nymph for 5-10 minutes, and then will have to take a “gestation” period after which you respawn with *nothing*.  Slimes don’t have a disadvantage from reforming other than having to wait a long while before doing it, even then there will probably be a long do-after with an alert that can be interrupted (so just carrying around the core would allow you to stop them from reforming). 

Both of these are supposed to be upsides. I don’t think there needs to be a downside on reviving because it *is* their race upside, and they have a lot of other downsides to balance it around this being solely an upside. 


> Maybe for Diona their upside can be #17279 once it gets merged

pretty sure that’s derelict, but either way I don’t think it’s good as their primary upside. A unique radio channel is kind of a gimmick, and it’s effectively useless if nobody else plays the race (like now), and just having a unique radio channel isn’t enough for most people to suffer through playing diona 

> sounds unfair for the lizard watching you even if doing it yourself is worse than getting revived normally

once this PR is finished every different race will have unique mechanical upsides. So every race will have a “I can’t do that” with other races- that’s what makes them unique. Having a unique radio channel (like you suggested) would be the exact same way. I don’t see why races having more unique upsides is a problem.

**Comment by NancokPS2** [comment]
Since you asked for an alternative:  
The major problem right now (ignoring any fairness arguments) is that for a permanent kill you need to space the body
  
They do not rot and recover when gibbed which means they are unkillable outside of that.    
This completely fucks antags if they cannot drag the body to an airlock and open it to space the body, it will eventually regenerate and out them.
  
Here are some toughts:  
  
-Slimes, on death, dissolve into a brain or core over a minute, which can be sped up by hitting them or by using a verb to extract it from the body.
This core can be smashed to permanently kill them.  
  
This core never rots and can be quickly revived with a defibrilator. Meaning that slimes are VERY easy to revive and even bring to medbay. But they are easy to kill for good.  
    
The self reviving sounds way more doable if they are easier to perma than others

**Comment by LankLTE** [comment]
I want to add that slimes already don’t rot and take about twice as long to gib already because of their super high blunt resist, so spacing is already by far the most viable option. With the rework once they are gibbed an antag would be capable of carrying the brain with them to stop it from reforming, so it’s not like spacing is the only option, just the most viable (like now). I don’t think making antags swap up their strategy a bit because of race differences is a bad thing- it allows for unique gameplay whether you’re the one playing the race or not

**Comment by Anzarot121** [comment]
> Since you asked for an alternative: The major problem right now (ignoring any fairness arguments) is that for a permanent kill you need to space the body
> 
> They do not rot and recover when gibbed which means they are unkillable outside of that. This completely fucks antags if they cannot drag the body to an airlock and open it to space the body, it will eventually regenerate and out them.
> 
> Here are some toughts:
> 
> -Slimes, on death, dissolve into a brain or core over a minute, which can be sped up by hitting them or by using a verb to extract it from the body. This core can be smashed to permanently kill them.
> 
> This core never rots and can be quickly revived with a defibrilator. Meaning that slimes are VERY easy to revive and even bring to medbay. But they are easy to kill for good.
> 
> The self reviving sounds way more doable if they are easier to perma than others
> 
> Edit: apparently the no rotting part was a bug? I cannot remember rn. I at least they could be made to not rot with this idea since it would be more than fair.

You can simply hoist the humanoid on the hook and dismantle the hook. To do this, you will need 12 seconds and several sheets of steel.

**Comment by LankLTE** [comment]
I'll be splitting this into separate PRs soonish, so the lizard and moth changes can get thrown in while I figure out what the fuck is happening with reforming.

**Comment by Froozigiusz** [comment]
> I'll be splitting this into separate PRs soonish, so the lizard and moth changes can get thrown in while I figure out what the fuck is happening with reforming.

Good to see #20328 coming out of this project, makes me really hopeful about a fruitful future for dionæ kind.

**Comment by LankLTE** [comment]
Half already in the game, half derelict. Might finish diona eventually but don't get your hopes up.

**Comment by UbaserB** [comment]
I pray 🙏🏻

**Comment by K-Dynamic** [comment]
I pray 🙏🏻

**Pull request closed without merging**
