### PR TITLE
Nuke Now Requires the Disk to be Inserted to Toggle Anchor

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Makes the nuke not be able to have its anchor toggled unless the nuke disk is inserted.
## Why / Balance

Talked about #29553. I decided to make the Nuke disk anchor rather than the stationary station nuke due to giving the nukies the choice of a final battleground rather than forcing it at the vault with a stationary one.
## Technical details

Locks the inventory when not anchored. Adds a check to anchoring for the disk
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/2cc4b052-7bbd-4a41-bf75-d93455a24fa6

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Nuclear bombs now require the Nuclear Authentification Disk to toggle anchor.

### CODE REVIEW

**Comment by Plykiya** [comment]
does it work with tha nukie nuke?

**Comment by Cojoke-dot** [comment]
> does it work with tha nukie nuke? (does their nuke start off anchored?)

their nuke does not start anchored IIRC, I'll double check though

**Comment by IProduceWidgets** [comment]
This will require resolutions to #29567 and #29566

**Comment by Cojoke-dot** [comment]
> This will require resolutions to #29567 and #29566

Why?

**Comment by IProduceWidgets** [comment]
Because this is making it even more confusing how the nuke anchoring works

**Comment by Tayrtahn** [comment]
Trying to toggle anchoring without the disk should at least display a popup saying that the disk is needed.

**Comment by Cojoke-dot** [comment]
> Trying to toggle anchoring without the disk should at least display a popup saying that the disk is needed.

How is this?
image

**Comment by Brandon-Huu** [comment]
Does this apply to both the NT and syndicate nuke?

**Comment by mirrorcult** [comment]
image

**Comment by bruhmogus** [comment]
this doesn't really account for thief objective imo

**Comment by Cojoke-dot** [comment]
> this doesn't really account for thief objective imo

yeah... this was made quite a while ago

**Comment by Emisse** [comment]
fuck the thieves

**Pull request merged**
