### PR TITLE
Aghost sec hud

### PR DESCRIPTION
**Pull request by SoulFN**
## About the PR

Aghost now see job icons and mindshield
## Why / Balance

Good for admins
## Technical details

Added two components to aghost
## Media

- [X] This PR does not require an ingame showcase

## Breaking changes

No
**Changelog**

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Huh, maybe make this togglable like the player info that admins can turn on in their menu?

**Comment by IProduceWidgets** [comment]
> Huh, maybe make this togglable like the player info that admins can turn on in their menu?

I *would* agree because I don't like overlays or huds when I admin, but its just as easy to remove the component myself with a script since admins practically need to run aghost scripts anyway.

That being said, since we run scripts, its also just as easy for us to ass the component....

**Comment by SoulFN** [comment]
I have an idea of adding glasses slot for aghost, so you can wear huds

**Comment by TheDoctor1977** [comment]
This should probably be done like the omni HUD, with medical, sec, and diagnostic HUDs all built into the aghost vision. I’m not sure if that’s its own component or just all of them individually, so if the latter, it might be a bit bloaty.

**Comment by metalgearsloth** [comment]
Would be better to have an admin window with buttons to add and remove common components rather than globally adding it.

**Pull request closed without merging**
