### PR TITLE
Reagent "Fat" and reactions for soapification and meatification

### PR DESCRIPTION
**Pull request by Kit0vras**
### - Added reagent "Fat".

Fat at the moment can be obtained by grinding a mouse, hamster, any raw meat (including cutlets) and body parts in a grinder. ~I talked to Emo, later we will be able to make the lipid extractor producing not meat, but fat directly.~

### - Added a reaction that creates soap. 

15 Fat + 10 Table salt + 10 Water = Soap.

15 Fat + 10 Table salt + 10 Blood = Homemade soap (in the event that you feel sorry for the water)

### - Added a meatification reaction that creates a piece of meat.

25 Fat + 5 Nutriment + 10 Blood + 10 Carbon = Meat.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new reagent: Fat.
- add: Added reactions for creating soap and meat.
- add: Added the ability to get fat from raw meat, cutlets, body parts, mice and hamster using a grinder.

### CODE REVIEW

**Comment by Kit0vras** [comment]
I can add reactions to the remaining types of soap, but I'm not sure if it's necessary

**Comment by deltanedas** [comment]
i will become full time soap factory very good

**Comment by Kit0vras** [comment]
> i will become full time soap factory very good

I also thought about the possibility of eating soap, but it's a very situational application, so I don't even know

**Comment by deltanedas** [comment]
> eating soap

the most based pr of all time???

**Comment by Kit0vras** [comment]
> > eating soap
> 
> the most based pr of all time???

the best ideas come unexpectedly, the main thing is to write them down

**Comment by EmoGarbage404** [comment]
> I talked to Emo, later we will be able to make the lipid extractor producing not meat, but fat directly.

I'll just comment on this and say that, while producing the fat reagent from the extractor is definitely a good idea, it should probably be in addition to the meat entity itself. The machine loses a lot of utility if you're going to need to get additional chemicals just to make meat.

**Comment by Kit0vras** [comment]
> it should probably be in addition to the meat entity itself

Fat is found in any kind of raw meat, but there is not much of it there. I didn't make the option "vomiting when drinking fat" just because of this.
At first I thought about its extraction from organs, but there is no fat in them - it is contained in the tissues surrounding the organs, but not in them, so it is not logical.
In this case, it is probably worth either coming up with an additional method of obtaining, or increasing its amount in meat and mice, what do you think?

**Comment by deltanedas** [comment]
fix conflict and merg i need soap factory

**Pull request merged**
