### PR TITLE
Cog update (Engineering update)

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR
swapped containment and atmos, added AI law boards, mailing units, more cameras. does cog's part of https://github.com/space-wizards/space-station-14/issues/32226

this should solve the issues of
- disposal units break stuff by throwing it
- teg is too far away from atmos
- atmos is too small
- atmos doesn't have enough storages for more then 5 gasses
- atmos doesn't have any miners aside from oxygen and nitrogen
- containment is too small
- containment cant use telsa
- engi is weirdly shaped
- AI has no law boards
- AI has too many blind spots in hallways

in testing the containment was able to use both tesla and singo, and radiation only leaked into PA room at high singo power
## Media

Cog-0

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

no changelog

### CODE REVIEW

**Comment by Spessmann** [comment]
hold on have to make a quick fix

**Comment by thebadman4662** [comment]
Finally chemlab won't have to take Lord of the Rings journey to give botany Muta, Dylo, Cryox, Pha, Dieth and nutrient.

**Comment by Spessmann** [comment]
I will be making changes later today

**Comment by Spessmann** [comment]
updated

**Comment by rabbivole** [comment]
> (Also Tesla was 1000% doable on in the small containment, almost no one makes a Tesla setup where the Tesla has space to move, however I do like your almost ready to go setup for the Tesla)

confirming tesla was fine and is actually the preferred choice for cog on the server i frequent. i've seen people build it super-safe by having emitters fire through the windows, and if you want to build it compact the station starts with 4 grounding rods so you don't even have to bug cargo roundstart. 

i'm a little sad to see the existing atmos/containment get changed; imo the mix pipe from distro to TEG and the non-spaced walkway to atmos fixed a lot of my real problems with the department. i think the current state of engineering has some fun texture to it and a little friction gives a station character. however i am a certified train enjoyer

**Comment by Spessmann** [comment]
Most of these changes were made to better engineering as a department rather then the containment. To put it simply, cog engineering scares people away due to the layout and unfamiliar setup. 

For example in atmos you have two miners for oxygen and nitrogen. If you want anything else? Chem wants carbon? Want to make a nice sauna? Want to fill distro with nitrous oxide? Too bad. You also only had two empty chambers so you would be forced to chose your two favorite gasses or stick to canisters or pipes. The reinforced walls on all sides and cargo on another side doesn't make it easy to make changes either. For main engineering people saw the interior singularity and tiny setup (compared to other maps) and hated it. There are also too many airlocks to the same place and most of the ring is not used for anything really important.

Cog has a reputation has a map people refuse to play engineering on because the department layout is so unfriendly and unfamiliar. If making some changes that will make more people willing play their favorite role on cog at the cost of the map's uniqueness is a price i must pay, so be it.

If you **really** despise this design where atmos and containment are swapped you can send suggested edits for a alternative version (which I will map), but it needs to solve the issues of atmos and containment (and PA room) being too small and cramped, and atmos not having enough storage for most the gasses (which imo are the biggest issues with cog engineering as of now).

**Comment by Spessmann** [comment]
~~besides nobody plays engineer on cog anyway so nobody will notice the changes~~

**Comment by cohanna** [comment]
As a loyal cogger engie I think the changes you made are overall beneficial. while I'm still unsure about the containment, the layout changes near the AME I think helped a lot. Excited to play it.

**Comment by Emisse** [comment]
lets try it

**Pull request merged**
