### PR TITLE
fix combat mode popup

### LINKED ISSUE #10392: Combat mode toggle popup message is incorrect
## Description
Combat mode toggle popup message is incorrect. When you enable combat mode, you get told that you _disabled_ it and vice versa.

**Reproduction**
- Press "1"

**Screenshots**
combat_mode_confusion

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
Closes #10392 

**Screenshots**

**Changelog**

:cl:
- fix: Fixed inverted combat mode toggle.

### CODE REVIEW

**Comment by Visne** [comment]
Why did it get switched up in the first place? Did it impact anything else?

**Comment by EmoGarbage404** [comment]
> Why did it get switched up in the first place? Did it impact anything else?

nfi. maybe something got refactored under the hood, maybe it got changed in some combat update. Reports date back mostly to a few days ago, but i'm not sure that's when the bug originated.

**Comment by Visne** [comment]
Not a fan of merging this until we know what caused it in the first place, as other things might have also been affected and then this would just be a bandaid fix.

**Comment by EmoGarbage404** [comment]
> Not a fan of merging this until we know what caused it in the first place, as other things might have also been affected and then this would just be a bandaid fix.

image
this is the code that handles this. It hasn't been modified in months. It is very possible that it's been like this for ages and no one has noticed/cared.

**Comment by Visne** [comment]
Maybe

**Comment by metalgearsloth** [comment]
> Not a fan of merging this until we know what caused it in the first place, as other things might have also been affected and then this would just be a bandaid fix.

https://github.com/space-wizards/space-station-14/pull/10324

**Comment by ElectroJr** [comment]
> as other things might have also been affected

AFAIK only the combat mode toggle has toggle-state dependent pop-ups, so this should be the only thing affected.

> what caused it in the first place

The problem is/was that the pop-up is displayed by client-side code after the other action logic has been run. If the action-toggling is predicted by the client, then the toggle state will have changed before the pop-up is displayed. If the action isn't predicted, the state will not have been updated, but the client will still display a pop-up. Previously (due to another bug) actions weren't getting properly predicted, which was fixed in #10324. So since that was fixed, the toggle-state & pop-message relationship has the be inverted.

It might be worth adding a comment somewhere that the pop-up suffix assumes that the action toggling is predicted? Or at least that if some older action gets updated & predicted, the messages need to be swapped?

**Comment by Visne** [comment]
Kinda cursed that it depends on that I feel, but I'm not really an expert on networking
Regardless, this can be merged

**Comment by ElectroJr** [comment]
> Kinda cursed that it depends on that

Yeah it is pretty cursed. There should probably just be some option to disable client-side pop-ups altogether.

**Pull request merged**
