### PR TITLE
Ports the /tg/ shotgun sprites

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Ports the /tg/ shotgun sprites for the Kammerer, Enforcer, and Double-Barrel. The sawn-off shotgun has also been updated, and so have the inhands for the improvised shotgun.

## Why / Balance
Besides not really fitting the artstyle due to having weird texturing and way too much hueshifting, all of these have the issue of just being *way* too damn hard to identify at a glance. 
The Kammerer / Double Barrel are really difficult to tell apart from eachother and have difficult-to-read inhands (that also happen to share the same issue of looking too similar to eachother.)
The Enforcer at least fits the artstyle, but it looks *really* similar to the bulldog. So similar, in fact, that it literally shares inhands with it!

## Media
Content Client_wOwzZwEIpw

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Resprited the Kammerer, Double-Barrel, and Enforcer shotguns using sprites courtesy of /tg/station.

### CODE REVIEW

**Comment by UbaserB** [comment]
i like how this looks

**Comment by Emisse** [comment]
ur gun has 2 item components

**Comment by Flareguy** [comment]
I KNEW webediting was going to just magically fuck up god damn it.

**Comment by QuietlyWhisper** [comment]
You might need to update the sprite of the new emergency shotgun wallmount

**Pull request merged**
