### PR TITLE
Kudzu nerf and electric kudzu

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 

- Nerfs kudzu spread speed by increasing the chance it won't spread from 16% to 60% (this mainly affects singular tiles of Kudzu and doesn't do much once it's already took off).
- Adds KudzuPower, an electrified Kudzu as a late game (after 50 minutes, low chance) event. Looks the same except drains APC networks rather fast causing brownouts then blackouts. Will shock if you bump it.

**Screenshots**

ContentClient-8JcDb2r83e

**Changelog**

:cl:
- add: Added a new Kudzu variant that's utterly shocking! It's rare so look out for the unique announcement late game.
- tweak: Made the normal Kudzu spread less often so it should be easier to manage when it's smaller.

### CODE REVIEW

**Comment by efzapa** [comment]
kudzu is already extremely easy to defeat with like 3 guys with welders, dunno why we need to nerf it more

**Comment by metalgearsloth** [comment]
> kudzu is already extremely easy to defeat with like 3 guys with welders, dunno why we need to nerf it more

Kudzu mispredicts real bad so isn't more frequent.

> Adds KudzuPower,

Have you profiled this? Making the entire station 1 big powernet seems like it's not gonna go great.

**Comment by Peptide90** [comment]
> kudzu is already extremely easy to defeat with like 3 guys with welders, dunno why we need to nerf it more

That's contrary to a lot of complaints in Discord saying when it gets down to singular tiles it spawns back too quickly.

> > Adds KudzuPower,
> 
> Have you profiled this? Making the entire station 1 big powernet seems like it's not gonna go great.

Nooooope, I got told as long as it's very late game and unlikely it's cool. Not sure how to profile it tbh I've never done that before.

**Comment by wrexbe** [comment]
My local server didn't seem to care, even when I covered the whole station with it. I agree the way it is implemented looks sus, but it seems to work alright. It's scary, and fun enough that it's probably worth it. It feels like a legitimate threat, unlike most of the events. This new kudzu is very deadly, if you get zapped, it grows over you, and your not getting out. It might be better if you separate the growth rate between the two types of Kudzu. Electric Kudzu grows slower, but is very dangerous, normal Kudzu is annoying, and grows quickly, but is harmless.

**Comment by Peptide90** [comment]
> My local server didn't seem to care, even when I covered the whole station with it. I agree the way it is implemented looks sus, but it seems to work alright. It's scary, and fun enough that it's probably worth it. It feels like a legitimate threat, unlike most of the events. This new kudzu is very deadly, if you get zapped, it grows over you, and your not getting out. It might be better if you separate the growth rate between the two types of Kudzu. Electric Kudzu grows slower, but is very dangerous, normal Kudzu is annoying, and grows quickly, but is harmless.

Thanks, yeah in local testing it didn’t seem to affect much, agreed it is super deadly. If there was a way to limit the amount of shocks that would make it less so but it’s kind of admeme level anyway. I wanted regular kudzu to do asphyxiation damage but don’t think I looked into it too hard and I think Moony wanted to.

I’ll try nerf the speed more when I get a chance.

**Comment by mirrorcult** [comment]
electric kudzu really needs a diff sprite or coloration. not sure how i feel about it in concept either but i suppose its fine

**Comment by Peptide90** [comment]
Closing in favor of #9576 electric kudzu was sort of a gimmick to give it some bite, can reopen if it's actually wanted

**Pull request closed without merging**
