### PR TITLE
Add genetics!!!

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
now that i have your attention,

Greetings everyone!

Today, I'm here to talk to you about why replacing the scream sound with a honk sound is the greatest change in Space Station 14 history. Allow me to explain.

First of all, the honk sound is much more humorous than the scream sound. Imagine how much fun it will be to be able to honk whenever something exciting or strange happens? Not only that, but it's a much more light-hearted noise than a scream, which can be unsettling to some people.

Plus, the honk sound is unique, meaning that it's instantly recognizable compared to other sounds. This means that people can easily recall and associate Space Station 14 with the honk sound, making it a great marketing tool for the station.

Finally, having the honk sound instead of the scream sound is much more cost-effective since it doesn't require a few people to scream whenever something exciting happens. That also means that it's more time-effective since it requires no extra time to record a honk sound as opposed to having people scream repeatedly.

So, overall, I think that changing the scream sound to a honk sound is the greatest change in Space Station 14 history. Not only is it more light-hearted and humorous, it's also easily recognizable and much more cost-effective.

Thank you for your time and consideration.

*obviously revert once april 1th is over*

**Media**

https://user-images.githubusercontent.com/39013340/228526351-a8bf4f94-42cc-4b65-a83f-5cda4fcde0d9.mp4

- [X] I have added a video to this PR showcasing its changes ingame

**Changelog**
:cl:
- tweak: Clown geneticists on SS13 have made a slight error in humanoid vocal chords genetics. Nothing serious of course.

### CODE REVIEW

**Comment by Naive817** [comment]
Is this meant for 4/1

**Comment by potato1234x** [comment]
"obviously revert once april 1th is over"

**Comment by deltanedas** [comment]
yes this is my april 1th pr

**Comment by moonheart08** [comment]
yea but is this
funny?
hold a vote here with github reacts (NOT DISCORD REACTS FFS) if people declare it not funny then it's not being merg

**Comment by deltanedas** [comment]
HONK!!!

**Comment by deltanedas** [comment]
oh moony you goofy goober you made the mistake of forgetting to change branch wouldnt it be so unfunny if this was in master haha

**Pull request merged**
