### PR TITLE
Add justice helm

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Ports the justice helm from SS13 by combining the light sprites from tgstation with our base helmet sprites.

## Why / Balance

I think it's silly fun, and I miss the little police siren from the secway.

The helmet requires a battery, so that will put a time limit on the noise.

I also only added it to the secdrobe and not the loadouts, to help limit the noise.
I can add it to loadouts if desired, but other officers can craft one using their helmets if they wish.

## Media

https://github.com/user-attachments/assets/98337550-2d8c-4ec4-838a-0905009df46d

justice-helm-recipe

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the justice helm to the secdrobe
- add: Added a crafting recipe for the justice helm

### CODE REVIEW

**Comment by Everturning** [comment]
the thing I dislike about this is how small the animation to show the light rotating is. its just a dot appearing on one side, then the other, which doesn't evoke the effect its going for. also, the light surrounds the wearer, but I think it would be fun to make it do the funny red rotating light thing that the nuke does when activated. cool item tho

**Comment by ps3moira** [comment]
Maybe use the lighting system with the emergency lights or sirens to get that spinning cop light

**Comment by Emisse** [comment]
needs spinny light

**Comment by themias** [comment]
I will try to add a spinny light.

**Comment by lzk228** [comment]
i don't really understand why a powercell is required in craft recipe if you still need a cell afterwards

**Comment by themias** [comment]
> i don't really understand why a powercell is required in craft recipe if you still need a cell afterwards

Sorry if I was unclear, I mean it "requires a cell" as in it needs power to function. It spawns with a small power cell.

**Comment by slarticodefast** [comment]
Maybe remove the powercell from the recipe and make it spawn without one when crafted? That way you still need one, but can use any type except only small ones.

**Comment by EmoGarbage404** [comment]
you can just make it so that the cell used for crafting is automatically inserted into the completed entity. that's what mechs do.

**Comment by themias** [comment]
The construction graph 'store' for boards and such seems to only work with regular containers and not container slots, so I just removed the cell from the recipe.

**Comment by EmoGarbage404** [comment]
container slots inherit directly from containers so i imagine it'd work the same?

**Pull request merged**
