### PR TITLE
Add ore plushies

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

add ore plushies
add some missed plushies to different lists

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added ore plushies.

### CODE REVIEW

**Comment by potato1234x** [comment]
why tho

**Comment by UbaserB** [comment]
The plushie kit is kind of getting bloated in sheer amount of plushies. Can you make a "pet rock" crate or "rock plushie crate" instead?

**Comment by TheShuEd** [comment]
I think we have so many useless toys that it's time to delete them rather than add new ones.

**Comment by Simyon264** [comment]
> I think we have so many useless toys that it's time to delete them rather than add new ones.

Nearly every toy is useless, but imho: They add a lot of variety and that's a good thing. Sure it's a bit bloaty, but that doesn't make it bad.

**Comment by lzk228** [comment]
closing till plushie crate will be reworked
(stale label)

**Pull request closed without merging**
