### PR TITLE
New evac shuttle: Sparverius

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Added a new evacuation shuttle (that totally is not the kestrel from FTL you can trust me :trollface:)
This is my first foray into anything remotely related to mapping so if there's anything I need to change let me know.
## Why / Balance

I feel like the current roster of evacuation shuttles is getting a little stale and could use a new addition.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image

## Breaking changes

**Changelog**

:cl:
- add: Added a new evacuation shuttle that has a familiar layout.

### CODE REVIEW

**Comment by Djungelskog2** [comment]
I like it alot but I think med + sec need lockers, the important Engi stuff like the substation, grav gen and gyro need to be behind reinforced glass/windoors are the major ones

QoL I'd put airlocks near/in the windoors in the open area.
Booze vendor against the glass and move the dispenser along the table at the bar, increase the bridges size downwards and add more seats there and do something with or about the weird wing sections the thrusters are on

**Comment by osjarw** [comment]
Consider adding a defib to the medbay, I think people often complain about some evacs missing them. 

This might be a nitpick, but is there a reason as to why the distro buffer thingy has it's windows on adjacent tiles, whereas the waste has it's windows on the same tiles? 
I find it a bit weird that both designs are used right next to eachother.

**Comment by Plykiya** [comment]
Agree with Djungelskog on the missing lockers

**Comment by UbaserB** [comment]
idk about the uranium glass

**Comment by lzk228** [comment]
idk what exactly but something in it looks weird, also CL not really needed, and the shuttle isn't even used anywhere

**Comment by Emisse** [comment]
I dont think this is needed at the moment, I have ideas for supporting alternate evacs for same maps eventually so dont write it off completely yet. Closing for now.

**Pull request closed without merging**
