### PR TITLE
High-capacity welding fuel tank

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds a high-capacity fuel tank with 5000u of welding fuel 

**Media**

prthumb7

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Nanotrasen has supplied engineering departments with high capacity fuel tanks.

### CODE REVIEW

**Comment by potato1234x** [comment]
The explosion size is basically the same and its going to be in engineering resulting in hardly any tiders breaking it to make a mess

**Comment by EmoGarbage404** [comment]
do people even consume 10,000u of welding fuel in a round?

**Comment by potato1234x** [comment]
Im probably going to reduce it tomorrow

**Comment by deltanedas** [comment]
even if you crank out meth like theres no tomorrow i cant see a use for this, you just cant use enough of a standard tank

**Comment by Snowyypanda** [comment]
you can't use that amount of fuel because the game has bare minimum features, if there was more stuff to be fixed/built as an engineer it would be depleted quicker

**Comment by potato1234x** [comment]
> even if you crank out meth like theres no tomorrow i cant see a use for this, you just cant use enough of a standard tank

you could say the same about the high capacity water tank, but ive halved the amount of fuel anyway

**Comment by EmoGarbage404** [comment]
> you could say the same about the high capacity water tank, but ive halved the amount of fuel anyway

at the very least, botany consumes water at a pretty decent rate. Basically only engineers use welding fuel, and rarely enough to even warrant needing a refill. These just seem like giant bomb targets.

**Comment by potato1234x** [comment]
> These just seem like giant bomb targets.

the explosion is about 1 tile larger than the regular fuel tanks

**Comment by deltanedas** [comment]
ive actually seen botany run out of water a few times, but engineers rarely ever refuel let alone run out

**Comment by DawBla** [comment]
> 🆑 Potato1234_x
> 
> * add: Nanotransen has supplied engineering departments with high capacity fuel tanks.

Nanotrasen Mandela effect

**Comment by potato1234x** [comment]
somehow i manage to run out of fuel all the time fixing broken disposals and deconstructing stuff, even if no one uses it, its nice to have for consistency.

**Comment by metalgearsloth** [comment]
> somehow i manage to run out of fuel all the time fixing broken disposals and deconstructing stuff, even if no one uses it, its nice to have for consistency.

Cargo has an order for this. If you run out of 1 welding fuel tank in a round that is a good thing.

**Comment by potato1234x** [comment]
tg has had these for ages and ive not seen a problem with them ever but if this is deemed not to be merged then thats fine by me

**Comment by Emisse** [comment]
merging this purely for future mapping reasons seethe in my inbox

**Pull request merged**
