### PR TITLE
Add poster about the SSD term

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

This PR adds a poster about the term SSD that explains it very basically.

The PR also adds all Safety Moth posters to the random legit poster spawner.

> "Safety Moth - Space Sleep Disorder"
> This informational poster uses Safety Moth™ to tell the viewer about Space Sleep Disorder (SSD), a condition where the person stops reacting to things. "Treat SSD crew with care! They might wake up at any time!"

## Why / Balance

The need for a poster like this was brought up in #32734, as there is currently no ingame explanation for what SSD is, despite being a commonly used in-universe term.

It's a Safety Moth:tm: poster because fitting "Space Sleep Disorder" on a poster was very difficult. also moff cute

Safety Moth:tm: posters are meant to be "legit" posters and provide helpful tips. Therefore they're added to the legit poster spawner.

## Technical details

Easier to just read the code.

## Media

Capture

Capture2

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added a new Safety MothTM poster about being SSD!

### CODE REVIEW

**Comment by averystarbits** [comment]
SAFETY MOTH :+1:

**Review by UbaserB — COMMENTED** [review]
It's sudden sleep disorder, not space sleep disorder

**Comment by SlamBamActionman** [comment]
> It's sudden sleep disorder, not space sleep disorder

Space Sleep Disorder had more results when searching on Discord, and the two seem to be used interchangeably.

**Comment by lzk228** [comment]
> It's sudden sleep disorder, not space sleep disorder

image

**Comment by UbaserB** [comment]
huh...

**Review by Errant-4 — APPROVED** [review]
Looks good

**Pull request merged**
