### PR TITLE
splitstation massive update

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Totally redid the whole bottom half of the station as well as top right.

Notable changes are:

- Science and Salvage are now in the top right.
- Bar is now in the center as one of the bridges.
- Cargo is now top right of bottom station so it's more central.
- Bridge is now in the lower section overlooking a wide park area.
- There's now more outside rock areas to explore. More to come.

Might be some teething issues or complaints about maint but will likely ask Emisse to do a flavor pass in future.
**Screenshots**

Local map renderer borked.
**Changelog**

:cl:
- add: Split Station massive update!

### CODE REVIEW

**Comment by Elijahrane** [comment]
Tested it, 2 extremely small pieces of feedback:
1. Roundstart atmos is wacky, you probably forgot to run the command
2. I'd move the stasis bed where that rollerbed is in the surgery room rather than just throwing it into the middle of the cloning room

**Comment by Peptide90** [comment]
> Tested it, 2 extremely small pieces of feedback:
> 
>     1. Roundstart atmos is wacky, you probably forgot to run the command
> 
>     2. I'd move the stasis bed where that rollerbed is in the surgery room rather than just throwing it into the middle of the cloning room

Yeah was unsure whether it should be there or in a one of the treatment rooms. I'll move it and do some more testing now, thanks.

**Comment by moonheart08** [comment]
splitstation-0

**Comment by Peptide90** [comment]
> 

Thanks for the render. I just added another small section out in the rocks so works for me that it's a secret area and it's not on the render. See who finds it.

**Comment by moonheart08** [comment]
Ian should be secured in the HoP's office, as he's a traitor objective.

**Comment by moonheart08** [comment]
image
These are wired incorrectly and you really just can't put them here as you'd make an infinite loop/short circuit if you did wire them with an input. They only have an output right now.

**Comment by Peptide90** [comment]
- Removed the SMES battery bank as shown above until a later date because rewiring the HV cables one cable at a time is a pain.
- Removed the HV cable lattice connector near Salvage in favor of a docking airlock (for that salvage to cargo shuttle fun).
- Added more firelocks to cargo since it was missing some. Added grilles to the bar back room as was missing as well as airtight flaps to the salvage conveyor.
- Moved Ian to HoPs office and added door remotes to all heads.
- Added some other misc items, carpets and other little bits.

**Comment by moonheart08** [comment]
Well, nothing better to do than give it a spin, it lgtm.

**Pull request merged**
