### PR TITLE
Add blindness, but different

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Adds a trait that gives you complete blindness, but also very good spatial awareness.

You can only see a small area, but holding something like a blind cane increases this range.

Anything you walk close enough to will appear in your vision, but will disappear shortly after if it is not anchored.

You can tell what direction sounds come from, but you cannot tell how far away they are unless they are relatively close.

todo:

ez:
- [x] Fix being able to see through walls
- [x] Make the character movement not extremely jittery
- [x] Fix not being able to see the floor
- [x] Make holding a cane increase the range at which you can see
- [x] Fading out
- [ ] Add being able to see sound
- [ ] Trait (why did it take me so long to add this)
- [ ] Fix the memory leaks

not ez:

- [x] Fix not being able to see walls
- [x] Figure out what is so fundamentally broken about walls that makes them completely invisible
- [X] Fix being able to right click and see things (w/o spritecomp.visible) (nvm there's no reason you can just walk over)
- [ ] Make item throws make sense

## Why / Balance

i think it's cool

## Media

What it looks like right now:

https://github.com/user-attachments/assets/184c8abf-74c2-497a-afa6-cae4efe8c4eb

Funny image of before I figured out how to not memory leak:
memory_leak

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added a new trait for blindness that completely removes your sight, but still lets you see things as long as they're close enough.

### CODE REVIEW

**Comment by 7-62x54r** [comment]
Maybe add a check for noises so those items are permanently visible while in vicinity? Vending machines and such, maybe moving objects as well (those who make footsteps at least, moonboots)
Also, blind cane could light up all items in vicinity for a duration, making it QoL feature for blind people like IRL. But that's probably out of scope of this PR as it has damage iirc

**Comment by notquitehadouken** [comment]
> Maybe add a check for noises so those items are permanently visible while in vicinity? Vending machines and such, maybe moving objects as well (those who make footsteps at least, moonboots exclueded) Also, blind cane could light up all items in vicinity for a duration, making it QoL feature for blind people like IRL. But that's probably out of scope of this PR as it has damage iirc

sounds will Show Up with a certain icon, this will handle vending machines and things that make sound

blind cane will extend the range you can see while you're holding it When I Code It and nothing else

**Comment by southbridge-fur** [comment]
I like this idea. I feel like the blind cane should give you good vision of the ground you're on. Maybe just highlight the nearby tile(s)?

**Comment by notquitehadouken** [comment]
> I like this idea. I feel like the blind cane should give you good vision of the ground you're on. Maybe just highlight the nearby tile(s)?

i have a fix in mind

**Comment by notquitehadouken** [comment]
by the way the way seeing sound will work is leeching off of whatever event fires when a sound plays and using that

**Comment by notquitehadouken** [comment]
crisis averted

**Comment by notquitehadouken** [comment]
as it turns out there is no event that fires when a sound plays
this may be a problem

**Comment by notquitehadouken** [comment]
ok i fixed the problem

**Comment by notquitehadouken** [comment]
yar har

**Comment by notquitehadouken** [comment]
i give up there's too many memory leaks

**Pull request closed without merging**
