### PR TITLE
Haven Orbital

### PR DESCRIPTION
**Pull request by MaloTV**
## About the PR
I've added the biggest map yet called Haven Orbital, a map that took me over 600 hours to create and a lot of sweat, tears and frustration, but I finally decided it's done and it's time to PR it.

Haven Orbital is not just a station, it has a little story that you can see in the video below in the Media field.

Haven Orbital is a 65-80 player map, but I'm pretty sure it could easily hold 200+ players.
It has its own evacuation shuttle called Emergency Bean, also made by me and inspired by the Barratry Shuttle.

- It has a zoo, a reporter's studio and a large green recreation area on the east side of the station.
- Extra Doors
- Around the east and north side of the station you can find some asteroids/debris containing valuable loot
- Medical checkpoints to support paramedics help the injured 
- Darkmode
- Broken down Engineering Shuttle 

## Media
**Lore Video**
[https://www.youtube.com/watch?v=PsucLGNMTIc&t](url)

**Full Map Render**
Haven
Orbital
_Map Render is so big i had slice it in half_

**Asteroids/Debris**

HavenOrbital-10
HavenOrbital-8

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

-->

:cl:MaloTheDuck
- add: Your crew meets the requirements to inhabit Haven Orbital, the most luxurious station NT has built to date consider yourself lucky!

### CODE REVIEW

**Comment by Eden077** [comment]
I'd recommend removing the cult daggers from the lava wreck, they already do a lot of damage and the melee rework makes them significantly more deadly, they are also going to be hugely powergamed so perhaps replacing them with kukri knives is better

**Comment by Interrobang01** [comment]
for anyone wondering why it got closed https://discord.com/channels/310555209753690112/771041304108072961/1142931848729731256 (tldr the map has a few issues like the asteroids existing and the dark tiles, well, existing, so this PR got closed until further notice)

**Comment by potato1234x** [comment]
this map is sick apart from maints which i originally thought was meant to be a maze

**Comment by potato1234x** [comment]
especially the dark mode

**Pull request closed without merging**
