### PR TITLE
Taller and Smaller traits.

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
You can be short now.
image
image

## Issues
- Doesn't preview in the character editor as the editor doesn't apply traits (😔), but the system itself supports it.
- Not mutually exclusive

but this is a micro PR and those don't seem like part of it.

**Changelog**

:cl: moony
- add: Traits for being short and tall.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Thought we were avoiding beneficial traits?

**Comment by Emisse** [comment]
you could scale player zoom with player height if you really want it to have a downside but i dont think it matters that much

**Comment by Veritius** [comment]
Relevant: #10437

**Comment by moonheart08** [comment]
> Thought we were avoiding beneficial traits?
> 
> This is the last time it was discussed and we were against having traits that affected game balancing https://discord.com/channels/310555209753690112/770682801607278632/1006878855673430046

I could fix the fact the sprite is smaller by artifically extending their clickbox if needed (iirc we support this)

**Comment by metalgearsloth** [comment]
Even if we fix player's being able to set their own hitbox their silhouette still puts them at a strict advantage (e.g. hiding) and we shouldn't be giving them control of this tbh.

**Comment by Elijahrane** [comment]
> you could scale player zoom with player height if you really want it to have a downside but i dont think it matters that much

Bigger / smaller mass has downsides too

**Comment by Scribbles0** [comment]
might not be my place to talk but how about adding a do-after to reaching stuff on tables or high ledges if you’re short? i think being tall is a downside itself, so there might not be a need for any changes to that

**Comment by retequizzle** [comment]
honestly don't see any real issue with this, if a player is going to hide as a small person and do it successfully, then they'll also be able to hide as a normal sized player and do it successfully because of how observant our playerbase is

in addition, if we're not going to do any policing over hairstyles being used to hide weapons on a player's back then trying to police this is just arbitrary at best

10/10 addition merge it and let skill issue commence

**Comment by metalgearsloth** [comment]
https://discord.com/channels/310555209753690112/310555209753690112/1023256120313249923

**Comment by Kromabae** [comment]
I wanna chip in and say that, why not just add this. it's legit RP value and the game needs some more visual description.

If it doesn't get added becuase of powergaming you are focusing on the wrong side of things, instead maybe work on how to make it so "ohh you get to be small, but you run slower, have lower stamina and slightly lower Crit/dead cap" and for tall just do like they big so hands are big so they can't hold guns (btw yes this is literally oni from nyano) make tall people weight so much you can barely drag em if you are smaller than them.

Not to sound like an absolute prick but I think traits are avery missed opportunity to really add some fun RP moments to the game, there should be ups and downs with every trait. but most of all the UP side with them should be the RP engagement. Isn't that what we all want in the end anyhow.

Any RP content is value at this stage, just add it. if people dont like it then remove it. Dwarves were a fun species, but was removed "because lack of content" even though content for them were suggested but fell on deaf ears... somepeople legit just want to be short, and some want to be tall. so instead of debating this being powergaming bait and shutting it down that way work on a way to not make it work. You don't seem to realize how desperate some people are for just more character depth.

**Comment by Partmedia** [comment]
It doesn't sound like the minor advantages of being small outweigh the roleplay value that it brings. A couple of "nerfs" were already discussed, including reducing the zoom level for small characters, but even without such a "nerf", I think this would feel fine in the game.

**Comment by Elijahrane** [comment]
Agreed really, although probably want https://github.com/space-wizards/space-station-14/issues/11613 to be fixed before this is merged since it's directly relevant

**Pull request closed without merging**
