### PR TITLE
Remove suspect figurine line

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

Removes a figurine line from the captain about hiding a nuke disk up his ass.

## Why / Balance

This line would likely be against the rules if a player said it. On CD we
already got multiple ahelps about this line.

## Technical details

YAML

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

No changelog needed

### CODE REVIEW

**Comment by lzk228** [comment]
> On CD we
> already got multiple ahelps about this line.

what exactly they complain about?

**Review by deathride58 — APPROVED** [review]

**Comment by dffdff2423** [comment]
Somebody started using a bunch of the figures next to an intercom and when this line was played it was met with "what the fuck" in OOC chat along with an ahelp from somebody who assumed it was a player that said it. Depending on the context, a line like this could easily get somebody banned on CD and I suspect wizden as well.

**Comment by deathride58** [comment]
Speedmerging on tests finish because the removed line is indeed against server rule 1.4, which is a zero-tolerance rule. We're aware that there have been bans in the past for extremely similar lines.

**Comment by Skarletto** [comment]
yes remove this shit

**Pull request merged**
