### PR TITLE
Little rework of existing yaml flatpacks

### PR DESCRIPTION
**Pull request by lzk228**
some id changing and yaml cleaning

### CODE REVIEW

**Review by metalgearsloth — DISMISSED** [review]
Missing some migrations.

**Comment by lzk228** [comment]
all migration in place

**Comment by metalgearsloth** [comment]
AmePartFlatpackStealObjective is missing.

**Comment by metalgearsloth** [comment]
Also CI fail is real.

**Comment by metalgearsloth** [comment]
CI is still failing.

**Comment by lzk228** [comment]
soon tm, i fucked up my local repo

**Pull request merged**
