### PR TITLE
Update Antagonists Guidebook Sections

### PR DESCRIPTION
**Pull request by Ghagliiarghii**
Flesh out the Rat King and Space Dragon subsections of Minor Antagonists section in the guidebook. Rewrite some of the rest of the Antagonist entries in the guidebook, mostly to fix some minor grammatical mistakes from the original entries and to bring content up to date with PRs changing the function of the Antags since the original entries.

## About the PR

I rewrote and expanded the guidebook entries for Rat King and Space Dragon. I plan to go through the guidebook and improve entries I see as lacking important information and detail as a series of PRs during the freeze. I'm open to feedback to improve my writing style, add information I've missed, or make things more clear and concise.

EDIT: I have now touched up most of the other antag entries as well, mostly to fix some minor mistakes and to bring the Guidebook up to speed with the current state of the game.
## Why / Balance

The sections on the Rat King and Space Dragon were a bit lackluster. Especially the Space Dragon was missing any mention of the recently added Fire Breath attack (https://github.com/space-wizards/space-station-14/pull/26746) and important information concerning Carp Rifts, especially the fact that the Space Dragon simply disappears if five minutes pass since the last carp rift (unless you have all three). "I finally get to play this cool ghost role! Wait.. where'd they go?" Isn't fun and should merit at least a mention in the guidebook.

## Media

<details>
<summary>Rat King and Space Dragon</summary>

image
image
</details>
<details>
<summary>Nuclear Operatives</summary>

image
image
</details>
<details>
<summary>Revolutionaries</summary>

image
</details>
<details>
<summary>Space Ninja</summary>

(Note the two instances of 'Threat' are hyperlinks back to the MinorAntagonist entry, which contains both Revenant and Space Dragon.)
image
image
</details>
<details>
<summary>Traitors</summary>

image
image
</details>

## Breaking changes

I wrote numerical values for the dragon's period to open a Carp Rift and similar values and didn't reference the DragonComponent file. If these numbers were tweaked and this guidebook entry not updated, the guidebook would become inaccurate. If there's a way to dynamically generate these numbers please let me know and I'll implement that otherwise these seems like an acceptable risk (other areas of the guidebook have become stale over time and needed to be updated, hence PRs such as this one.)

### CODE REVIEW

**Comment by Ghagliiarghii** [comment]
> I think it would be good to include that the space dragon is immune to the fire from the dragon breath (or just flames in general? never actually tested it.)

I thought about this but was concerned about bloat (too much text = hard to read) and I was similarly unsure. I may add it in after I test to confirm Dragon is actually immune.

**Comment by Ghagliiarghii** [comment]
So after a little testing it looks like dragons are immune to the flame stacks, take a very small amount of Burn damage, and a small amount of Brute damage from the explosion itself. (A little more than 10:1 Brute:Burn) I think I'll just leave the entry as is since you're not _immune_ just very resistant to it and I don't know a way to convey that concisely in a way that's not super confusing.

**Comment by Ghagliiarghii** [comment]
Actually did the det lighter get removed as a steal objective? I was writing that section from the code-base on objectives but maybe that one was somewhere else... It was kinda easy tho sometimes if the det isn't there yet and the det room is mapped in maint or something you could basically just walk up, take it, and leave.

**Comment by TheDoctor1977** [comment]
This is very nitpicky, but the nukie introduction audio that you have as text at the top of their page is clearly saying “Operatives at standby”, not “Autotell on standby”

**Comment by Ghagliiarghii** [comment]
> This is very nitpicky, but the nukie introduction audio that you have as text at the top of their page is clearly saying “Operatives at standby”, not “Autotell on standby” Also, I’m pretty sure that steal objective was not removed.

Nitpicky is fine, trust me a lot of these changes are fixing missing commas and stuff. This was an error from the original entry and it got through because it wasn't formatting or grammar but I listened to the SFX (/Resources/Audio/Ambience/Antag/nukeops_start.ogg) and agree that's definitely Operatives and not Autotell On, so I've updated it for correctness.

Thank you for catching it for me :+1:

**Comment by Ghagliiarghii** [comment]
Oh no the wiki has the same typo ( https://wiki.spacestation14.io/wiki/Antagonist ) 
image

**Comment by Ghagliiarghii** [comment]
> Also, I’m pretty sure that steal objective was not removed.
I've just looked into this, lighter was never a traitor objective it's one of the many things that Thief can want so there aren't objectives missing from the list of possible objectives for traitor in guidebook

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
