### PR TITLE
Remove "uncloneable" trait

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Since we're phasing out cloning and its going for good in the near future, might as well remove the trait since no one uses it anyways.

**Changelog**

:cl: Ubaser
- remove: The uncloneable trait has been removed.

### CODE REVIEW

**Comment by Terraspark4941** [comment]
i literally have this ticked in my char screen and it has in no way affected my gameplay, valid

**Comment by lzk228** [comment]
ive seen that salvagers still can find all circuits and scientists build full clone machine

**Comment by lzk228** [comment]
so im against removing that trait

**Comment by FinnishPaladin** [comment]
> ive seen that salvagers still can find all circuits and scientists build full clone machine

which they never do, when was the last time you've ever seen an actually functional cloning machine? 
the ones at central command / the barratry evac shuttle do not count.

**Comment by lzk228** [comment]
literally yesterday

**Comment by lzk228** [comment]
nuuuuh

**Comment by QuietlyWhisper** [comment]
There was no point in removing this while cloning was still in the game in some way...
Should've been in one collective pr

**Comment by DangerRevolution** [comment]
> There was no point in removing this while cloning was still in the game in some way... Should've been in one collective pr

^ this...

**Comment by Aisu9** [comment]
or and hear me out.
re-introduce cloning as T2 medical research
Make the unclonable trait prevent the cloner scanner from scanning you
when cloned, your a clone with an imperfect and unscanable body(single clone per person).
make the clone scanner able to clone from an entire body or just their brain if it is all that is remaining

**Comment by EmoGarbage404** [comment]
cloningheads stay coping

> There was no point in removing this while cloning was still in the game in some way...
Should've been in one collective pr

i can do that

**Comment by Terraspark4941** [comment]
> re-introduce cloning as T2 medical research

☠️

**Comment by Aisu9** [comment]
> > re-introduce cloning as T2 medical research
> 
> ☠️

hey at least you wont have security taking hostage science only because it's a T3, they will eventually get it(faster than salvagers are able to collect the three legendary shiny)

**Comment by K-Dynamic** [comment]
> > > re-introduce cloning as T2 medical research
> > 
> > 
> > ☠️
> 
> hey at least you wont have security taking hostage science only because it's a T3, they will eventually get it(faster than salvagers are able to collect the three legendary shiny anyway)

Maintainers still detest cloning in its current form

I will probably make a very shitty design doc (a literal microsoft docx) that will at least outline my ideas on cloning, such as not being a bomb magnet or science's forced project

**Pull request merged**
