### PR TITLE
Service Worker Hydro Access

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Adds hydroponics to the service worker's starting access. Because they didn't have it before for some reason.

**Media**
- [X] This PR does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Changed service worker's extended access to include hydro.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i was under the impression the service worker was like a waiter, not just a generic service intern role.

**Comment by Nairodian** [comment]
Rather unsure myself, however during low pop the bartender gets hydro access and vice versa so it makes no sense as to why the service worker wouldn't have it.

**Comment by EmoGarbage404** [comment]
> Rather unsure myself, however during low pop the bartender gets hydro access and vice versa so it makes no sense as to why the service worker wouldn't have it.

maybe just add hydroponics to the extended access?

**Comment by Nairodian** [comment]
> maybe just add hydroponics to the extended access?

If that's the more preferable route I can do that as well.

**Comment by AJCM-git** [comment]
@Nairodian Can you move the access to extended?

**Comment by Nairodian** [comment]
There you go.

**Pull request merged**
