### PR TITLE
Electric grill

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
added electric grill for cooking steaks
has 4 settings: off, low, medium and high.

basically a moveable hob

## Why / Balance
as more things are cookable not with X seconds in microwave but by heating to X temperature, ovens and grills will be more and more useful.
the grill has up to 2.4kW of heating, but doesnt have any timers or anything so you could easily burn food if not careful 

## Technical details
added `EntityHeaterSystem`, similar to hotplate except instead of adding energy to solutions it adds energy to the entity's temperature

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/fb9c5f7e-e9d1-4097-ad85-cf928b899d90

mobs with low mass have less heat capacity...
so minecraft automatic chicken cooker 9000:

science

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Added the Electric Grill for cooking steaks quickly, research food service to make it.

### CODE REVIEW

**Comment by mirrorcult** [comment]
based

**Comment by Partmedia** [comment]
I'm curious why you chose to implement a new system instead of using the existing hotplate system? This implies that you cannot cook on a hotplate. Why can't a hotplate handle both solutions and adding temperature directly?

**Comment by deltanedas** [comment]
> I'm curious why you chose to implement a new system instead of using the existing hotplate system? This implies that you cannot cook on a hotplate. Why can't a hotplate handle both solutions and adding temperature directly?

hotplate turns off and on automatically theyre fundamentally different player wise

**Comment by lzk228** [comment]
sprite is kinda... weird?
and whet meat cooked it should has a crackling sound like SHQSHQKSKSHQKSH

**Comment by brainfood1183** [comment]
very nice, we need the frier which lets us fry anything. Basically adds a fryed preffix to any item you put in it and recolors the objects brownish.

**Comment by deltanedas** [comment]
> sprite is kinda... weird?
> and whet meat cooked it should has a crackling sound like SHQSHQKSKSHQKSH

1. i cant sprite for shit
2. record making a SHQSHQKSKSHQKSH sound then play sound when going to cooked meat step :trollface:

**Comment by deltanedas** [comment]
> very nice, we need the frier which lets us fry anything. Basically adds a fryed preffix to any item you put in it and recolors the objects brownish.

nyano has this

**Comment by brainfood1183** [comment]
> > very nice, we need the frier which lets us fry anything. Basically adds a fryed preffix to any item you put in it and recolors the objects brownish.
> 
> nyano has this

did not know that.

**Comment by deltanedas** [comment]
> First thing people will try is to cook hamlet with it. Can you cook hamlet with the electric grill?

if it has similar mass to a chicken yes

**Comment by brainfood1183** [comment]
> > First thing people will try is to cook hamlet with it. Can you cook hamlet with the electric grill?
> 
> if it has similar mass to a chicken yes

can u put say, a chicken in some sort of container then put that container on the electric cooker?

**Comment by brainfood1183** [comment]
> > > First thing people will try is to cook hamlet with it. Can you cook hamlet with the electric grill?
> > 
> > 
> > if it has similar mass to a chicken yes
> 
> can u put say, a chicken in some sort of container then put that container on the electric cooker? esentially to stop chicken or hamlet moving around

**Comment by deltanedas** [comment]
you can just put directional windows around it to trap small animals

**Comment by brainfood1183** [comment]
> you can just put directional windows around it to trap small animals

i was thinking more along the lines of say a pan so you could add chicken, add water, make chicken soup

**Comment by deltanedas** [comment]
way out of scope and ability

**Pull request merged**
