### PR TITLE
remove directional switches sprite offsets

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
doesnt change any functionality just makes sprite not evil

## Why / Balance
it was evil

## Technical details
no

## Media
which one is directional who could tell...

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by ChilbroBaggins** [comment]
👍

**Comment by brainfood1183** [comment]
i prefered old sprite

**Comment by deltanedas** [comment]
why it was broken

**Comment by ChilbroBaggins** [comment]
I'm fairly impartial between them, but what was broken about it?

**Comment by deltanedas** [comment]
it was offset so it poked off of the wall... see the previous pr screenshot

**Comment by ChilbroBaggins** [comment]
> it was offset so it poked off of the wall... see the previous pr screenshot

No, what was wrong with the old sprite? That's what BrainFood is talking about, I think

**Comment by deltanedas** [comment]
it was not centered it was the inverse just look at the screenshot

**Comment by deltanedas** [comment]
image

**Comment by Emisse** [comment]
> i prefered old sprite

old sprite had perspective which was the issue

**Comment by ChilbroBaggins** [comment]
> it was not centered it was the inverse just look at the screenshot

Ai ai ai...before [this](https://github.com/space-wizards/space-station-14/pull/18712) it wasn't.

> old sprite had perspective which was the issue

Ok, thanks, that was the answer I was looking for. 

Just wondering if it _should_ be centered now though for the non-directional switches?

**Comment by ChilbroBaggins** [comment]
Or perhaps the non-directional just aren't necessary? I left them in for 2 reasons, 1 was so maps didn't end up with wonky button placement, 2 was for some scenarios where you might want 360 access instead of mapping a bunch of buttons on one wall. 🤷‍♂️ I could go either way.

**Pull request merged**
