### PR TITLE
Fix candles (firestack fading)

### PR DESCRIPTION
**Pull request by TheShuEd**
deltanedas broke it in
https://github.com/space-wizards/space-station-14/pull/28034

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
fixes #28100

**Comment by TheShuEd** [comment]
I noticed that it can still spontaneously go out in some other situations, for example, when touching an entity, when spreadFire: true

**Comment by TheShuEd** [comment]
maybe we should do a pr revert?
considering he added several bugs to the game at once.

**Comment by deltanedas** [comment]
its better to have buggy instant extinguish rather than instantly getting round removed by flaming mouse

**Pull request merged**
