### PR TITLE
Boombox

### PR DESCRIPTION
**Pull request by marboww**
## About the PR

The forgotten classics of the streets! A boombox has been added containing 13 presets of different types of instruments. The boombox can be worn on the shoulder.

## Why / Balance

It's fun and convenient.  But when carried on the shoulder your movement speed is 70%. The boombox can be obtained from special instrument collector's crate with a 5% chance. Also, the boombox does not include all musical instruments.

## Media

ezgif-4-d83538bc83

bandicam 2024-02-29 10-59-19-340 (online-video-cutter com)
328a7e1)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: marbow
- add: The forgotten classics of the streets! A boombox has been added containing 13 presets of different types of instruments. The boombox can be worn on the shoulder. May appear in special instrument collector's crate.

### CODE REVIEW

**Comment by TheShuEd** [comment]
Should be rare reward from Lethal company salvage expedition ^-^

**Comment by marboww** [comment]
> Should be rare reward from Lethal company salvage expedition ^-^

Okay

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/24875 ?

**Comment by marboww** [comment]
> https://github.com/space-wizards/space-station-14/pull/24875 ?

And I didn't even notice.

**Comment by marboww** [comment]
ok, I'll close PR for a while, it has better work.  If he closes PR, I will open mine.

**Comment by BeatusCrow** [comment]
I'll finish my PR. But I would be happy to use your textures (and accordingly indicate you as the person who participated in the creation of boombox). Unfortunately, I was forced to disappear for a while, and now I'm finishing the drop for nuclear operatives... But in the near future I will start the forgotten PR

**Pull request closed without merging**
