### PR TITLE
Adds oxygen to chem crate

### PR DESCRIPTION
**Pull request by noudoit**
## About the PR

This adds oxygen to the chem crate.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Oxygen jug to chemistry P crate.

### CODE REVIEW

**Comment by Emisse** [comment]
fix your arbitrage, its gone over from including the oxygen

**Comment by noudoit** [comment]
ahhhh lemme fix

**Comment by LankLTE** [comment]
> ahhhh lemme fix

Not sure if you're still working on this, but you should probably also add Nitrogen since (afaik) that's not in any of them despite being needed for quite a few recipes.

**Comment by metalgearsloth** [comment]
stale

**Pull request closed without merging**
