### PR TITLE
Space Ninja 3: an old enemy in a new environment

### PR DESCRIPTION
**Pull request by Jackal298**
Make Ninja more stable in terms of design

## About the PR

This PR improves the visual style of the ninja to a more unified color palette
## Why / Balance

Today, the ninja style was a hybrid of several styles (new and old TG) and they are very different from each other, which gives me a strong feeling of unfinished work, if this PR is merged then I will start developing new content for the ninja (belt, headset and unique id card)
## Technical details

In general, this is a Port of Sprites from Paradise (these sprites were in the old TG), as well as a resprite of some features of the new TG under the color scheme of the old ninja, there is also a unique sprite by prazat911
## Media

OLD
Nin 3

NEW
Nin 1
Nin 2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by GoodWheatley** [comment]
imo I like the current sprites better but the final decision isn’t really up to me

@deltanedas any thoughts on this

**Comment by deltanedas** [comment]
these sprites look more ninja'y but old ones cooler imo

**Comment by Jackal298** [comment]
> these sprites look more ninja'y but old ones cooler imo
> 
> energy katana one is great tho

Initially, I wanted to make a spacesuit in the style of the new TG, and leave the costume, but it was a lot of work and I didn’t bother, I have sprites in the archive that I’m replacing, and if I return to this idea, then maybe the old ninja spacesuit will come back

**Comment by deltanedas** [comment]
actually use current spacesuit sprites for the jumpsuit then add the old spacesuit sprites on top i think it will look sick

**Comment by lzk228** [comment]
only `- tweak: Ninja equipment sprites updated` in cl would be nice

**Comment by Partmedia** [comment]
This change does not meet the significance requirements to have a Changelog as stated in the [Changelog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog).

**Comment by metalgearsloth** [comment]
Please make your PR titles descriptive as I shouldn't have to open it to know what is changing.

**Comment by UbaserB** [comment]
i like the current sprites, so i dont really want this change.

**Comment by Jackal298** [comment]
> only `- tweak: Ninja equipment sprites updated` in cl would be nice

I fixed everything

**Comment by Jackal298** [comment]
> Please also show a comparison against the old sprites

I'll make comparison screenshots

**Comment by Jackal298** [comment]
I forgot to say that the old ninja suit has a problem with the side sprites (problem with the arms)

**Comment by Jackal298** [comment]
> Please make your PR titles descriptive as I shouldn't have to open it to know what is changing.

Okay, I’ll write in the title what’s changed

**Comment by Jackal298** [comment]
> Please also show a comparison against the old sprites

All added a screenshot of the old design

**Comment by keronshb** [comment]
> > Please also show a comparison against the old sprites
> 
> All added a screenshot of the old design

Thank!

New sprite is really the old ninja TG sprite, where the old sprite is the new one.

I was always a fan of the older sprite, especially the mask, because it stood out more. Seemed like less of a high-tech space ninja and more traditional, but that's how I feel the design works better.

**Pull request merged**
