### PR TITLE
tweak(PULLREQUEST_TEMPLATE): Removed the majority of comments

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Removed the excessive amount of comments from the PR template

## Why / Balance

There's way too much text to have to scroll through every time someone opens a PR.
People who have opened more than a single PR do not need to see all at.

If the information is not already in the Pull requests guide then it should be put there instead since people are already required to read the guide.

Having the information here as well is just clutter.

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). 
- [x] I have read and I am following the [Changelog Guidelines](https://docs.spacestation14.io/en/getting-started/pr-guideline#changelog)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
- [x] I understand that not following the above may get my pr closed at maintainer’s discretion

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
The media section should also be change IMO

**Comment by Brandon-Huu** [comment]
wtf, the changelog guidelines and pr request redirect to the same page?

**Comment by Brandon-Huu** [comment]
Oh, it's meant to redirect to a specific part of the page.
It doesn't work for me.

**Comment by Brandon-Huu** [comment]
The majority of the PR Guidelines is just the changelog guideline

**Comment by Brandon-Huu** [comment]
Should I remove the separate check list item for the changelog?

**Comment by VasilisThePikachu** [comment]
While I agree it may need a cleanup, this is too much. And adds unnecessary checkmarks.

Because you have opened multiple PRs and the comments are not useful to you does not mean that they are not useful to someone still brand new to making prs.

I will be fine with seeing a pr making the comments smaller/removing any duplicates.

**Pull request closed without merging**
