### PR TITLE
Add new jobs to Box Station

### PR DESCRIPTION
**Pull request by FillerVK**
## About the PR
Box Station Update:

- Added a reporter's office with his spawn

- Added a psychologist's office with his spawn

- Boxer spawn added

These roles are exciting, but they are on a small number of maps. I converted an unnecessary office above the cargo hold into a reporter's office, and near the medical center in the former maintences, I made a psychologist's office. The Box Station ring was already there a long time ago, so I just added the Boxer Spawn.

**Media**

image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: A reporter and a psychologist now have their own offices at Box Station

### CODE REVIEW

**Comment by Emisse** [comment]
the map is not meant to have these jobs, they are station specific jobs for marathon and bagel

**Comment by Emisse** [comment]
i think psychologist is fine here but youll want to pull master and use that mapfile since this one is outdated to the most recent box update. i dont want reporter or boxer on box i think itll be a bit too much

**Comment by HoidC** [comment]
> i think psychologist is fine here but youll want to pull master and use that mapfile since this one is outdated to the most recent box update. i dont want reporter or boxer on box i think itll be a bit too much

>box station
>no boxer

**Comment by FillerVK** [comment]
> i think psychologist is fine here but youll want to pull master and use that mapfile since this one is outdated to the most recent box update. i dont want reporter or boxer on box i think itll be a bit too much

Okay, so I need to remove the reporter's and boxer's office?

**Comment by Emisse** [comment]
youll probably just want to start on a fresh up to date map since this one conflicts with the last map update

**Pull request closed without merging**
