### PR TITLE
Updates scripts to make life easy for newbie

### PR DESCRIPTION
**Pull request by Devianartaro**
## About the PR
The scripts that are now have limited functionality and have not been updated for over 2 years, in order to make life easier for people without an IDE, and to make running a server on the local area is much easier will be made a couple of scripts that do not require the opening of the console.
(Click and use) - lets make people life easyer

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by DogZeroX** [comment]
The changelog is not player-facing, remove it.

**Comment by 0x6273** [comment]
There are already some scripts in /Tools. Having 2 different directories with scripts and having to remember which script is in which dir seems kinda bad.

Also, a lot of these scripts seem kinda pointless since it's just a single dotnet command and running the script is actually more typing than just running the command directly.

The script filenames should be snake_case like all the existing scripts.

**Comment by Devianartaro** [comment]
> There are already some scripts in /Tools. Having 2 different directories with scripts and having to remember which script is in which dir seems kinda bad.
> 
> Also, a lot of these scripts seem kinda pointless since it's just a single dotnet command and running the script is actually more typing than just running the command directly.
> 
> The script filenames should be snake_case like all the existing scripts.

These scripts and made for easy use, for some it is much easier to click on the program than to open the console and write each command, as well as here is no purpose to rewrite existing scripts, but simply to make them so easier to use, or every person that want play with friends need to know how to use IDE or make mistake on submodules update and don't know how to fix it? Scripts in is tools doesn't useful and still need to open console also nothing for windows.

**Comment by metalgearsloth** [comment]
> > There are already some scripts in /Tools. Having 2 different directories with scripts and having to remember which script is in which dir seems kinda bad.
> > Also, a lot of these scripts seem kinda pointless since it's just a single dotnet command and running the script is actually more typing than just running the command directly.
> > The script filenames should be snake_case like all the existing scripts.
> 
> These scripts and made for easy use, for some it is much easier to click on the program than to open the console and write each command, as well as here is no purpose to rewrite existing scripts, but simply to make them so easier to use, or every person that want play with friends need to know how to use IDE or make mistake on submodules update and don't know how to fix it? Scripts in is tools doesn't useful and still need to open consoles (also you still need read how they work properly)

If you're hosting a server for friends then building the game doesn't really factor into it, if you have the repo downloaded you 100% should have an IDE.

**Comment by Devianartaro** [comment]
> > > There are already some scripts in /Tools. Having 2 different directories with scripts and having to remember which script is in which dir seems kinda bad.
> > > Also, a lot of these scripts seem kinda pointless since it's just a single dotnet command and running the script is actually more typing than just running the command directly.
> > > The script filenames should be snake_case like all the existing scripts.
> > 
> > 
> > These scripts and made for easy use, for some it is much easier to click on the program than to open the console and write each command, as well as here is no purpose to rewrite existing scripts, but simply to make them so easier to use, or every person that want play with friends need to know how to use IDE or make mistake on submodules update and don't know how to fix it? Scripts in is tools doesn't useful and still need to open consoles (also you still need read how they work properly)
> 
> If you're hosting a server for friends then building the game doesn't really factor into it, if you have the repo downloaded you 100% should have an IDE.

Uh...No? You use "git clone" to get a copy of repo and then build it, next launch server, these scripts are aimed at speeding up the process, only if you want to develop you download a IDE. A lot of servers like from linux didn't use IDE for launch. Yep on linux the main is command line, but some have a graphical shell, where it will be easier to run scripts.

**Comment by metalgearsloth** [comment]
> Uh...No? You use "git clone" to get a copy of repo and then build it, next launch server, these scripts are aimed at speeding up the process, only if you want to develop you download a IDE. A lot of servers like from linux didn't use IDE for launch.

If you're just getting a copy of the repo you should just be using the builds page https://central.spacestation14.io/builds/wizards/

**Comment by Devianartaro** [comment]
> > Uh...No? You use "git clone" to get a copy of repo and then build it, next launch server, these scripts are aimed at speeding up the process, only if you want to develop you download a IDE. A lot of servers like from linux didn't use IDE for launch.
> 
> If you're just getting a copy of the repo you should just be using the builds page https://central.spacestation14.io/builds/wizards/

Uh but that mean i cant make any changes on prototype or textures, that ruin any local mods...

**Comment by SantaGitHub** [comment]
He could not push his scripts into the fork repository, he decided to go through the main repository
[https://github.com/space-syndicate/space-station-14/pull/1098](Origin PR)

**Comment by metalgearsloth** [comment]
Another maint might feel different and re-open but:
1. You don't need to run RUN_THIS.py every time. It just installs hooks and updates the submodule.
2. If you're editing the files you should be using an IDE, they're free, not just doing it manually and running a script.
3. If you're not editing the files you should be using a build.
4. We already have  /Tools/ with scripts for building the game in it (and if you're building the game in debug with a script I would beg you to use an IDE).

**Pull request closed without merging**
