### PR TITLE
Crime Assist PDA program

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR

Ported from the Frontier Station PR and in turn from DeltaV. Thanks to those folks for making the content, hopefully I used git cherry pick correctly so your credits will carry over.

Pretty essential bit of content for security and law players to streamline the brig process.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Peptide90** [comment]
I did it again ffs.

**Comment by deltanedas** [comment]
wont this need lrp space law

**Comment by chromiumboy** [comment]
What's the Crime Assist Program do, out of curiosity?

**Comment by themias** [comment]
> What's the Crime Assist Program do, out of curiosity?

I believe it is a port of this:
https://github.com/DeltaV-Station/Delta-v/pull/464

**Comment by chromiumboy** [comment]
Cheers! Looks interesting

**Comment by deltanedas** [comment]
code before gpl commit is still mit anything after is gpl

**Comment by Master2112** [comment]
The license changed after I originally made this for DeltaV

I don't know much about licenses, but as far as I care you can use this anywhere you like 👍 very glad to see people enjoy it as much as they do

**Pull request closed without merging**
