### PR TITLE
adds barber scissors to hristov bundle

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

[Kadeo64](https://github.com/Kadeo64)
> added barber scissors to hristov bundle

Reopening of #25692
## Why / Balance

[Kadeo64](https://github.com/Kadeo64)
> full hitman outfit but you still have your AWFUL hair. now you get to go bald.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Syndicate is now supplying barber scissors in the Hristov bundle to make your disguises even balde- better.

### CODE REVIEW

**Comment by deltanedas** [comment]
13tc to forcibly make people go bald
1. buy syndie soap
2. buy hristov bundle
3. slip n snip

**Comment by Hmeister-real** [comment]
> 13tc to forcibly make people go bald
> 
> 1. buy syndie soap
> 2. buy hristov bundle
> 3. slip n snip

That would be great, maybe would be cool if there was a separate syndicate razor/shaver that just has really fast hair cutting speed and maybe works as a good slash weapon. Out of scope for this obv, just ideaguys'ing

**Comment by TheShuEd** [comment]
doesn't sound very useful, but ok, thanks

**Comment by deltanedas** [comment]
bald ops is real

**Pull request merged**
