### PR TITLE
Add the Syndicate Raid Suit

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Adds the syndicate raid suit, an 8 TC sidegrade to the blood-red hardsuit which trades space protection for superior armor.
The raid suit has 10% slowdown (like the blood-red) and 65% damage resist in all brute damage types, as well as in heat and explosions. The helmet is slightly better than other helmets at 15% resist and is only obtainable through the raid suit bundle. In total this gives the suit 70.25% damage reduction to brute/heat damages, and a 65% reduction to explosions.

## Why / Balance
Intended to help move away from spacing meta with nukies, now they have a non-spaceproof option for combat and would very much benefit from leaving the windows and floors intact. Also prevents the use of explosives such as the china lake without causing significant damage to the structure of the station, which may kill the operatives if they're not careful.

## Media

https://github.com/space-wizards/space-station-14/assets/140123969/e465e325-d099-47a9-b969-712ac13a00fb

The flashlight is stronger than the one on the blood-red.
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Nuclear operatives are now able to purchase durable armor which is NOT space-proof.

### CODE REVIEW

**Comment by ps3moira** [comment]
Shouldn't have better stats besides less speed slowdown and able to fit in bags easier.

**Comment by thebadman4662** [comment]
Hmmm, feels weird.

You space station to bridge the speed gap between you and crew as usually nukie will have only 90/81% movement speed, especially now with elite black being overpriced sidegrade.

Now you are down to 85/76,5% speed and crew is fine to go full sonic? Thats 17/30% relative penalty so I suppose it will just be used as budget juggernaut if syndie can't otherwise afford it, I really doubt nukies will be buying this once novelty wears off.

**Comment by ninruB** [comment]
Spacing does make catching people with a movespeed disadvantage a lot easier due to firelocks and area denial, which does effectively bridge the gap between movespeeds naturally or by forcing both parties to use slowing hardsuits.

Firelocks also function as cover and group segregating functions, as well as potentially slowing you down. The effect of this and whether or not it cancels out due to both parties experiencing it is debatable, but it has to be noted.
If agreed upon this being false, the "real" effective armor bonus is lessened by a varying amount.

If spacing is utilized, you get complex effective movespeed; if a paid sidegrade to the free EVA hardsuit does not allow for spacing it is affected by an opportunity cost.

Therefore, the "real" effective movespeed malus is greater than 5% by a varying amount.

In an unreinforced, full, nukie party you would have to convince 4/5 (including yourself) to buy this item and stick to a specific set strategies, all of which invalidate most explosives among other things; having to convince the entire party to use your strategy is unreliable and extremely punishing to this item if failed.

Does this really matter though?
70% DR fucks and you're still within >100% MS provided you use MS-related meds and throw away the duffel, -5% EMS is nothing compared to +20% DR and as an item for traitors or lone-ops this is borderline overpowered and wonderful, nukies though? Not very good.

**Comment by Plykiya** [comment]
needs nukeops store whitelist

**Comment by Boaz1111** [comment]
good pr

**Comment by Golinth** [comment]
I like this. Spacing is a nukie’s best tool, and this allows strats that break that meta. I seriously hope this gets merged.

**Pull request merged**
