### PR TITLE
Take-hud-to-Borgs

### PR DESCRIPTION
**Pull request by Strol20**
Added medical hud to medical borg, and diagnostic hud to engineering borg

## About the PR
Now medical and engineering Borg have the necessary hud

## Why / Balance
This makes it easier for borg

## Technical details
I added the hud tag to the Borg components (Sorry if I worded it wrong)

## Media
Screenshot_1
Screenshot_2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
- add: Nanotrasen has updated the drivers for debt scanners, and now some models have an interface Hud

### CODE REVIEW

**Comment by BreadyToad** [comment]
> Point of discussion: should this be an integrated part of chassis, or upgrade parts? (if latter then that can still come in a a future iteration, doesn't conflict with this PR)
> 
> I'd like to see modular damage in the future (some equipment being destroyed / non-functioning as result of damage) so tying fewer features to chassis itself and making cyborgs more modular is the way to go IMO. But like I said this doesn't conflict with the PR and turning HUDs into upgrades can come in a future PR.

I feel like with current cyborg system we can only tie it to a specific module, and this will just feel clunky imo. The idea of making cyborgs more modular is amazing, but it needs a cyborg system rework and something like installing the HUD in the cyborg eyes, etc.

**Comment by Kadeo64** [comment]
I feel like medical hud should be on all borgs to prevent crew harm

**Comment by EmoGarbage404** [comment]
this should really just be a module. Just add some generic code that adds component when the module is inserted and removes them when it's taken out.

**Comment by muburu** [comment]
> this should really just be a module. Just add some generic code that adds component when the module is inserted and removes them when it's taken out.

i don't like the idea of this being a module, there doesn't need to be a bajillion modules for everything especially something like this which doesn't come with any tools, 

i don't foresee any "balance" issues with this just being a built in ability for engiborgs and medborgs, i think it'd be nice if eventually all cyborg chassis got some kind of baseline ability like this, the only borg with kind of an ability is the default one, which can hold one extra module (isn't really significant anyways since most generic modules aren't very useful)

or you can just make this occupy a different type of module slot or something, if this does become just another module then i wouldn't really see much use out of it especially by engiborgs, they typically need a lot of tools anyways and this supposed module definitely wouldn't be a priority to have at all

**Comment by BreadyToad** [comment]
> this should really just be a module. Just add some generic code that adds component when the module is inserted and removes them when it's taken out.

This would only waste a slot, escpecially since now all job related cyborgs have 3 useful job modules, which are all needed. Making a separate HUD module would result in medborg giving up hypo, defib or other useful tools. If it won't be a baseline ability (which I think it should be) it can be a part of a diagnostic module for med borgs and an advanced tools module for engi borgs, however it should remain active at all times if the module is in.

**Comment by EmoGarbage404** [comment]
you could just fold it into another module (medhud in diagnostic module is obvious) so it isn't worthless.

the whole point of a module system is customization. It kinda defeats the point to have abilities not tied into it. Also, job-specific borgs have 4 slots iirc so it's less of a hassle.

**Comment by Kadeo64** [comment]
> the whole point of a module system is customization. It kinda defeats the point to have abilities not tied into it. Also, job-specific borgs have 4 slots iirc so it's less of a hassle.

it's still a hassle but only for engi and service borgs since they have a ton of modules. Med, Mining, and Jani all only have 3 unique modules really (med has 4 but since there's no reason for mediborgs to have tools it doesn't matter)

**Comment by Ilya246** [comment]
i would say to just include the health HUD into the diagnostic module and the diagnostic HUD into the tools or advanced tools module

**Comment by deltanedas** [comment]
tools module is usable by any borg which would be weird

**Comment by Kadeo64** [comment]
> tools module is usable by any borg which would be weird

Any borg can use a welder to heal though, so I feel like it works.

**Comment by Kadeo64** [comment]
> they cant self weld, and have a health indicator anyway

borgs can weld other borgs is what I meant, which, you know, is kind of important when nobody else has a welding tool and/or goggles

**Comment by Ilya246** [comment]
> > borgs can weld other borgs is what I meant
> 
> I feel like this makes borgs a little too "crew independent". I've seen borgs group up and exclusively roll with other borgs to the extent where they are just "doing work out there somewhere without ever being seen". Peak performance - sure - but counter to roleplay/player interaction.
> 
> Now I understand that's already in-game - perhaps something should be done about that (feel free to start a discussion in a separate issue) - but that is not affected by this PR directly. The reason I'm mentioning this here is because I feel that making diagnostic HUD too widely available to borgs will further encourage borgs banding together and avoiding crew, which I don't think we want to encourage.
> 
> IMO it should be part of a more specialized module. One exclusive to engineer chassis maybe?

it's still roleplay/player interaction, just between the borgs
and they don't particularly isolate themselves, they still interact with people sometimes

**Comment by metalgearsloth** [comment]
Is this still being worked on @Strol20

**Comment by Strol20** [comment]
I guess I'd better close this thread. I'll open it later when I have some code

**Pull request closed without merging**
