### PR TITLE
nukies can buy elite hardsuit

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

nukies can now buy the syndicate elite hardsuit, you will remember this from such classics as agent whiskey and agent sierra
10% slowdown added to elite suit
## Why / Balance

1. unused content is CRINGE
2. nukies in ss13 can buy the elite hardsuit, in ss13 the elite hardsuit is 8TC and they have 30 TC, in ss14 we have 40TC, 33% more. 8x1.33 = 10, but i increased the price to 15 due to balance concerns

point 2 is price justification, not this PR existing justification
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: JoeHammad
- add: Nukies can now buy the elite syndicate hardsuit

### CODE REVIEW

**Comment by Yousifb26** [comment]
Maybe it could be like 13 TC or 12 TC, this would make the price similar or the same as the jug suit which is a trade off of speed for tanking. The elite suit is a flat upgrade from the classic blood red with speed and tanking. I could argue it being even higher because of that but at the very least I highly suggest making it slightly similar in price to the jug suit so you could ask yourself if you wanna be fast and slightly more tanky or be slow and significantly more tanky.

**Comment by asperger-sind** [comment]
The hardsuit would be an instabuy option like noslips are right now if placed at a price below like 16TC, this is a really strong item with the following stats:

```SUIT 
    type: ExplosionResistance
    damageCoefficient: 0.3
    
        Blunt: 0.5
        Slash: 0.5
        Piercing: 0.4
        Heat: 0.2
        Radiation: 0.25
        Caustic: 0.5
        
    walkModifier: 1.0
    sprintModifier: 1.0


HELMET
        Blunt: 0.9
        Slash: 0.9
        Piercing: 0.9
        Heat: 0.9
```

If anything, I believe there was a closed PR to add it before, when it was still available for the agen. Imo only make these available if warops is called. (have fun crudding that because i don't think we've the functionality)

**Comment by Yousifb26** [comment]
16 is appropriate imo, it’s not half your TC but it’s still enough to make you wonder if you can afford this

**Comment by EmoGarbage404** [comment]
elite hardsuit should be balanced to something actually reasonable. In 13, it
 specifically protects against fire and caustic damage (distinct from heat). This is just a cracked up suit with no movement penalty or balancing factor.

**Comment by JoeHammad1844** [comment]
hmm ill increase the price to 15

**Comment by JoeHammad1844** [comment]
and ill add some slowdown aswell

**Comment by JoeHammad1844** [comment]
the suit now has a 10% slowdown like the bloodred and it now costs 15TC

**Comment by JoeHammad1844** [comment]
i would love to add the fireproofing but we cant separate the heat from fire and lasers, ill make an issue on that

**Comment by Ilya246** [comment]
i think it could be good if it were to protect very well against explosions specifically so you would buy this to use together with the china-lake

**Comment by JoeHammad1844** [comment]
it already does
image
~sosa ops~

**Comment by Ilya246** [comment]
> it already does image ~sosa ops~

0.2x or even 0.1-0.15x would be better, RDsuit has 0.1x (should be nerfed maybe?)

**Comment by JoeHammad1844** [comment]
how about 0.25?

**Comment by IntegerTempest** [comment]
> how about 0.25?
high explosion resistance will make it really useful. I think 0.15 for more accurate balancing, tests are needed

**Pull request closed without merging**
