### PR TITLE
Created the Schiene Shipyards Reach II

### PR DESCRIPTION
**Pull request by LittleBuilderJane**
## About the PR 
This PR adds a Remaster of the Reach shuttle, known as Reach II ! It is larger, more complex and with more and modernized features.
**Screenshots**

SS Reach II
**Changelog**

:cl: Schiene
- add: The SS Reach II, a successor to the SS Reach shuttle, has been put into service.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Having a maprender to look at would be nice.

Stuff that stands out to me from a broad view:
1. Docking ports look not standard.
2. Laying tiles diagonally like the glass ones doesn't look good. Same with diagonal firelocks.
3. That middle part looks awfully susceptible to being cut off.
4. Map looks too big for lowpop.
5. There doesn't seem to be a lot of maintas areas or anywhere out of the way for traitors?

**Comment by LittleBuilderJane** [comment]
> Having a maprender to look at would be nice.
> 
> Stuff that stands out to me from a broad view:
> 1. Docking ports look not standard.
> 2. Laying tiles diagonally like the glass ones doesn't look good. Same with diagonal firelocks.
> 3. That middle part looks awfully susceptible to being cut off.
> 4. Map looks too big for lowpop.
> 5. There doesn't seem to be a lot of maintas areas or anywhere out of the way for traitors?

I've made the map over two weeks ago. When it was made, and only after I already spent two months on it, was I told we're having a mapping freeze. This map has been unupdated since it was put up. It likely doesn't even work by now regardless of any small issues. 

The middle part is quite a few tiles wide, more than enough to be immune to all but seriously heavy bombing.

Standardized docking ports weren't a thing when I made this.

I was told they work diagonally, so I rolled with it.

It's got 50 named job slots, and infinite passengers. It ain't low-pop.

It has as much maints and little nooks and crannies as I could reasonably put on a ship of that size.

**Comment by LittleBuilderJane** [comment]
> > Having a maprender to look at would be nice.
> > 
> > Stuff that stands out to me from a broad view:
> > 1. Docking ports look not standard.
> > 2. Laying tiles diagonally like the glass ones doesn't look good. Same with diagonal firelocks.
> > 3. That middle part looks awfully susceptible to being cut off.
> > 4. Map looks too big for lowpop.
> > 5. There doesn't seem to be a lot of maintas areas or anywhere out of the way for traitors?
> 
> I've made the map over two weeks ago. When it was made, and only after I already spent two months on it, was I told we're having a mapping freeze. This map has been unupdated since it was put up. It likely doesn't even work by now regardless of any small issues. 
> 
> The middle part is quite a few tiles wide, more than enough to be immune to all but seriously heavy bombing.
> 
> Standardized docking ports weren't a thing when I made this.
> 
> I was told they work diagonally, so I rolled with it.
> 
> It's got 50 named job slots, and infinite passengers. It ain't low-pop.
> 
> It has as much maints and little nooks and crannies as I could reasonably put on a ship of that size.

But just to add, I have felt and still do feel like I just wasted two months on this. It's been fully ignored for a solid two weeks, and I just can't be fucking arsed to work on updating something for no fucked reason.

Besides, It's been made pretty fucking clear my designs ain't welcome anyways, but who cares bout some Junior Contributor anyways, even if they made multiple maps and a lobby song ?!

**Comment by metalgearsloth** [comment]
> But just to add, I have felt and still do feel like I just wasted two months on this. It's been fully ignored for a solid two weeks, and I just can't be fucking arsed to work on updating something for no fucked reason.

> Besides, It's been made pretty fucking clear my designs ain't welcome anyways, but who cares bout some Junior Contributor anyways, even if they made multiple maps and a lobby song ?!

image

I'm the person who made the issue and I was expecting reach 1 to get rotated out for this.

With that being said making a map out of nowhere shouldn't come with the expectation it gets merged in the same way I don't expect a first draft of code to get merged as is. Making a map without prior consult comes with the risk it gets rejected which also applies to https://github.com/space-wizards/space-station-14/pull/9686 and any other code that gets put up without prior consult. I've put lots of work into prs only to have them rejected or reverted and don't take it personally. I spent **dozens** of hours on the box2d port and it got reverted within a day.

Maintainers have lives too. Reviewing a map is a large piece of work. I could review a dozen other, smaller prs in the time I could spend reviewing this. I spend many hours a week just reviewing other people's work when I could be doing other things I enjoy doing. We have maybe 5 active maintainers on content atm: mirrorcult, electrosr, wrexbe, moony, and myself and receive 500-600 prs a month so large ones are going to sit longer than small ones as we donate our free time for this.

Fixing the prototype names would take me 20 minutes to do and I wouldn't expect a mapper to do it.

Considering you don't seem interested in the map getting reviewed further I'm gonna close the PR for now.

**Pull request closed without merging**
