### PR TITLE
Give clown overall and security playtime requirements

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Clown now requires 30 hours of overall playtime and 10 hours of security playtime.

## Why / Balance
Too many clowns just slip everyone non-stop and laugh all alone while the entire crew hates them. Most of the time they also cause problems to security and are in general a huge nuisance.
If you're the only one laughing you've failed as a clown, this pr's purpose is to give them some time on the receiving end of unfunny jokes.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
**Changelog**
:cl:
- tweak: Clown now requires security playtime to make them understand how much of a pain slipping everyone nonstop is.

### CODE REVIEW

**Review by Veritius — APPROVED** [review]
god bless

**Comment by tutoumi** [comment]
i'm not that type of clown but not based, too much time to wait

**Comment by Krunklehorn** [comment]
A new player interested in Clown won't care to play Security Cadet properly just to get to it.

**Comment by GNF54** [comment]
based tbh

**Comment by AjexRose** [comment]
not enough, make the clown more difficult to unlock then the captain /j

**Comment by UbaserB** [comment]
this actually kind of makes sense

**Comment by jessicamaybe** [comment]
Alternatively we could also nerf slipping, like making thrown items not slip people anymore. I mean those objects are in the air how are they ending up beneath peoples feets? I'd like to see some more skillfully performed slips to be honest, throwing is so cheap

**Comment by Krunklehorn** [comment]
That PR already exists #24494

**Comment by potato1234x** [comment]
clowns are gonna do the same thing anyway regardless of how much sec they play

**Comment by asperger-sind** [comment]
Playtimers really won't solve the issue of clowns being a nuisance or going for purely their own entertainment, which is for the record a very subjective concept.
If someone wishes to try and understand, what are they affecting when slipping an officer who is clearly chasing someone, they could do that on their first round of the game; if they don't, then even a playtimer of 1000h won't resolve the issue.

Is a 10h sec playtimer funny? Kind of, it's ironic that you need sec playtime to play someone who is considered to be sec's nemesis.

**Comment by HoidC** [comment]
if they can’t grief as a clown they’ll grief as a passenger

**Comment by EmoGarbage404** [comment]
Service roles intentionally have no role timers to allow new players to easily access low-stakes roleplay roles. Furthermore, clown doesn't have any kind of complex knowledge that justifies needing security playtime, like det or warden. As such, I'm opting to close this PR.

**Comment by musicmanvr** [comment]
clown mains stay winning 💪

**Pull request closed without merging**
