### PR TITLE
water reaction but it's an explosion

### PR DESCRIPTION
**Pull request by Interrobang01**
(this description updated for the most recent commit)

## About the PR

For eons young chemists have realized, when looking at a recipe requiring water, that they have no water. These chemists think "Oh, h2o, I'll just mix hydrogen and oxygen!". They then mix the two elements and face disappointment when absolutely nothing happens. This changes now. Because that infinite water in the form of reactions has been vetoed (see #15451 and #18267), this PR has hydrogen and oxygen make water _vapor_ instead, plus a bunch of energy.

You see, it turns out mixing hydrogen, oxygen, and a bit of heat perfectly completes the Fire Triangle. This fire is so vigorous that many people call it an "explosion". Indeed, this PR makes it so mixing oxygen, hydrogen, and a massive dump of heat creates an explosion similar yet weaker to the potassium explosion, plus one mol of water vapor gas for every unit of reagent that reacted.

Now, chemists shall stop saying "Huh, nothing happened," and start saying "Oh, the humanity!" as they receive a crippling 22.5 damage.

At some point in this game's development someone's probably going to enable water vapor condensation, and when that happens the balance here might change. But that's a problem for the future.

Currently the reaction requires heat so as to not get in the way of existing hydrogen/oxygen reactions. On the other hand, if heat wasn't required it would make hydrogen/oxygen reactions more !!fun!!, and it would make more water-wanting chemists explode which is always nice. Currently the heat requirement is kept so as to reduce the impact of this PR, but if changing that sounds like a good idea tell me.

Many people are opposed to no heat requirement and in fact want the opposite. IRL the combustion temperature is like 700K but nobody wants to sit still for 5 minutes waiting for their water to heat up, so 370 is what will be used.

## Why / Balance

- It's weird to try and make the single most well-known compound and have absolutely nothing happen
- More explosions
- It's funny to watch chemists explode (i don't actually believe this, I'm just saying it to appease Emisse. merge pls)
- It's water vapor and not actual water so game design is preserved

Precise numbers:

- Reaction is 2 parts hydrogen and 1 part oxygen (since 1 unit seems to be volume-based this is actually inaccurate but whatever) plus heating to 360 K (reagents are dispensed at 293 K)
- Creates an explosion similar to potassium explosion but worse
- Also creates 1 mol of water vapor per unit in the reaction
- There are explosion numbers in there, and they are way smaller than potassium explosion

Many people say "but wait, that's an explosion and it's in chemistry, what will happen when bad players get their hands on this??" but fear not, this reaction is far weaker than even that of potassium. 90u of reactants deals like 22.5 damage to people at the epicenter. This explosion is so weak that literally the only people using this purposefully will be rulebreakers using it at bar patrons, since no antagonist with half a powergamer neuron in their brain will ever use such a weak explosion. Plus it takes like 45 seconds to heat to the ignition point.

## Technical details

I do not actually understand explosion code so I've just set the explosion values to random offsets of the potassium explosion reaction.

## Media

(this footage is from the most recent commit, if you want footage from before that then ask me, and if you want footage from after that then just try and use your imagination)

https://github.com/space-wizards/space-station-14/assets/113810873/54428dab-7b13-41cb-a6b7-45a5342f564d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Mixing hydrogen, oxygen, and heat will now create gaseous water plus a large surplus of energy!

### CODE REVIEW

**Comment by deltanedas** [comment]
heat is required for it to not break dexalin recipe which is hydrogen oxygen and plasma catalyst

**Comment by Interrobang01** [comment]
> heat is required for it to not break dexalin recipe which is hydrogen oxygen and plasma catalyst

1. that recipe change got reverted (by me :)) so it's just oxygen and plasma now
2. this reaction has a priority of 20 which is less than the baseline I'm pretty sure, so the dexalin recipe would get priority even if it was made with hydrogen and oxygen

**Comment by mirrorcult** [comment]
this makes zero sense

**Comment by deltanedas** [comment]
hydrogen gas is explosive ([hindenburg](https://en.wikipedia.org/wiki/Hindenburg_disaster))

also none of chem makes sense in any way

**Comment by Interrobang01** [comment]
> also i think for "accuracy" it should have reaction temp of 500C (773K)

The low heat requirement is half ease of use (or ease of unuse I guess), and half to represent the fact that most heat increases are uneven (like, say, a spark), and those uneven heatings would ignite the hydrogen in the hot bits, which creates heat for the cold bits. On the other hand, the only source of heating right now is hotplates, and those are realistically very even. I think I'll keep the low heat threshold for now for gameplay's sake.

**Comment by Partmedia** [comment]
You cannot mix room temperature oxygen and hydrogen gas to get water. This is what any [quick Google search will tell you](https://www.thoughtco.com/making-water-from-hydrogen-and-oxygen-40211010) because this reaction has a minimum activation energy.

Regardless of the realism, my biggest concern with this proposal is the explosion. Search "potassium bombing" if you want to find out more about this discussion.

**Comment by deltanedas** [comment]
> You cannot mix room temperature oxygen and hydrogen gas to get water.

its meant to model the explosion which does make water (vapor) albeit at much higher activation temperature than in this pr which is only like 30C

**Comment by Interrobang01** [comment]
> Regardless of the realism, my biggest concern with this proposal is the explosion.

Potassium and water is about as hard to get as hydrogen & oxygen and a hotplate, so explosions shouldn't be made any more accessible with this PR. Any explosion issues will have been there already, though I suppose people might start making more explosions just because they're reminded of it by this PR.

The hydrogen/oxygen explosion is a tad bit stronger than potassium explosions right now, so if that needs to be toned down let me know.

**Comment by EmoGarbage404** [comment]
in the future hydrogen and oxygen will be extremely common reagents to get. With what little chem balance we have right now, i don't think it's good to give water such an easy infinite supply. 

Furthermore, the reaction doesn't even make sense? you're heating up hydrogen and oxygen *barely* above room temperature and it's creating a giant spurt of gas and an explosion. 

I don't really get the point of this beyond just making shitters more able to get bombs.

**Comment by deltanedas** [comment]
> With what little chem balance we have right now, i don't think it's good to give water such an easy infinite supply.

it makes vapour

**Comment by Interrobang01** [comment]
> in the future hydrogen and oxygen will be extremely common reagents to get. With what little chem balance we have right now, i don't think it's good to give water such an easy infinite supply.

The reaction doesn't even produce water, it produces water vapor. If at some point water vapor is made to be convertible to water, this will have to be reconsidered. Either way, whatever method will be used in that future to convert water vapor to water will probably be complicated enough to be balanced, but if not this PR will have to be reconsidered after then.

> Furthermore, the reaction doesn't even make sense? you're heating up hydrogen and oxygen _barely_ above room temperature and it's creating a giant spurt of gas and an explosion.

The idea is that that tiny amount of heat is concentrated enough in one area to trigger the reaction, but I suppose since everyone wants a higher temperature I'll raise it.

> I don't really get the point of this beyond just making shitters more able to get bombs.

The point is to appease the large amount of "mixing hydrogen and oxygen should make water" people in a balanced way. This reaction is difficult enough with the heating and all that this will be harder to use as a bomb than potassium and water. Just in case, I'll quickly lower the strength of the explosion...

...although that might be counterproductive, if you hypothetically looked at the fraction of shitters who use bombs and the fraction of actual antagonists that use bombs, the fraction of shitters will shoot up if the bombs stop being worth it to use. I'll increase the strength anyway and hope for the best.

**Comment by Interrobang01** [comment]
The commits have been made and the description has been updated to fit this new future. History can be whatever I want. Except for history depicting the reaction happening, because now heating it up takes so long the video surpasses the GH file size limit. Luckily, using modern-day cooking show magic, I can skip the heating process in the demo.

**Comment by GeorgeGimme** [comment]
this looks neat

**Comment by AJCM-git** [comment]
The general consensus that I'm seeing is that this is not really wanted as the heat requirement makes it not fix the "give feedback to the most common reaction people know about" issue, and removing the heat requirement raises previously discussed issues. Personally I don't agree with the "this exaggerates a irl phenomenon" or "this is not realistic" but those weren't the main arguments anyways.

**Pull request closed without merging**
