### PR TITLE
Increase the cost of Emitters

### PR DESCRIPTION
**Pull request by HoofedEar**
## About the PR 

* Emitters are now slightly more expensive for Cargo
  * Credit cost: 1000 -> 3000  

**Screenshots**

**Changelog**

:cl:
- tweak: Emitter crates now cost 3000 credits for Cargo.

### CODE REVIEW

**Comment by Peptide90** [comment]
Funnily enough I changed the damage modifier set already awhile back and people complained secure crates were too hard to get into (it made it so very few weapons had the damage to do damage, was a high flat reduction).

**Comment by HoofedEar** [comment]
> Funnily enough I changed the damage modifier set already awhile back and people complained secure crates were too hard to get into (it made it so very few weapons had the damage to do damage, was a high flat reduction).

I just was thinking about how easy it is for traitor QMs to just arm themselves buy buying sec/armory crates and blasting them open with an emitter. QM/cargo traitors ought to work a bit harder/jump through more hoops

**Comment by Fishfish458** [comment]
> > Funnily enough I changed the damage modifier set already awhile back and people complained secure crates were too hard to get into (it made it so very few weapons had the damage to do damage, was a high flat reduction).
> 
> I just was thinking about how easy it is for traitor QMs to just arm themselves buy buying sec/armory crates and blasting them open with an emitter. QM/cargo traitors ought to work a bit harder/jump through more hoops

In that case they really could just buy an emag to open them.

I think the real issue is that points are pretty worthless so no one really cares how they're spent. If it took effort to get them + the ability to see a history of orders there could be more accountability towards who is ordering what.

**Comment by HoofedEar** [comment]
> > > Funnily enough I changed the damage modifier set already awhile back and people complained secure crates were too hard to get into (it made it so very few weapons had the damage to do damage, was a high flat reduction).
> > 
> > 
> > I just was thinking about how easy it is for traitor QMs to just arm themselves buy buying sec/armory crates and blasting them open with an emitter. QM/cargo traitors ought to work a bit harder/jump through more hoops
> 
> In that case they really could just buy an emag to open them.
> 
> I think the real issue is that points are pretty worthless so no one really cares how they're spent. If it took effort to get them + the ability to see a history of orders there could be more accountability towards who is ordering what.

Yeah that’s a good thing I think, having to use an emag to open it! 
but you’re right about cargo points, I also had the idea of making it so you have to fill out the name and reason before an order can be placed

**Comment by Matz05** [comment]
Please, no indestructible crates. Not _again_...
If you're going to write in such a magic material why not just make the entire station out of it?

**Comment by metalgearsloth** [comment]
> Please, no indestructible crates. Not _again_... If you're going to write in such a magic material why not just make the entire station out of it?

Whole station doesn't try to declare cargonia tho

**Comment by Matz05** [comment]
Just ban people who don't want to play the game and would rather ruin it for other people. Don't gut whole mechanics for fear the people in a different colour uniform are plotting against you, or because a horde of 13-year-olds think they're being funny.
I remember when I tried to play Cargo in the most helpful, friendly, and trusting way possible for a few rounds in a row, people had no chill. I tried to get people the crates they asked for as quickly and efficiently as possible (somewhat hindered by everyone else running away to salvage or whatever), and half the people who didn't totally ignore me at the front desk and speed-hack the doors to wordlessly purchase their own crates constantly were either accusing me of "Cargonia" or actively trying to incite it. The number of times I saw people declaring death on whole departments (usually Cargo, Security, or Science) was out of control. If players can't play anything other than department-v-department or griefing, they should be banned, but don't destroy the simulationist systems interaction that makes Space Station 13/14 special. The gaming world already has too many sterile "theme park experiences", the interaction between multiple mechanics creating a believable cartoon of a world is the core element of the game's charm. Things should 'make sense' according to the world's own internal logic, turning every round into a series of emergent problems and on-the-fly planning to solve them. Fiat-invulnerable materials and the cutting of entire classes of mechanical interaction as a band-aid over playerbase behavior problems is a cardinal sin against this principle, and indicative of a development going in a dangerous direction.

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
actually idk about buffing sec crates again but making emitters more expensive is good

**Comment by HoofedEar** [comment]
> actually idk about buffing sec crates again but making emitters more expensive is good

I'll defer to you on what you'd like me to do, I can remove the crate buff and just keep the emitter cost increase

**Comment by mirrorcult** [comment]
imo just have the emitter price increase, crate change is probably unnecessary with that

emitters might need to cost even more than 2k tbh

**Comment by HoofedEar** [comment]
> imo just have the emitter price increase, crate change is probably unnecessary with that
> 
> emitters might need to cost even more than 2k tbh

changes made, let me know what you think

**Comment by Acruid** [comment]
Why are emitters even purchasable from cargo? Shouldn't they be constructed like every other machine?

**Comment by Peptide90** [comment]
> Why are emitters even purchasable from cargo? Shouldn't they be constructed like every other machine?

This was the suggestion in discord as no matter the cost people will still buy them first to power game.

**Comment by HoofedEar** [comment]
Do we dare remove emitters from Cargo before adding the capability to build it? I say yes 😈

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
