### PR TITLE
Atmos pipes now deal blunt damage

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
*Insert metal pipe sound effect*
Metal atmos pipes now deal DPS around the same as the crowbar, with slight differences between pipes in speed and damage.
Straight pipes are equal to crowbars
Bend pipes deal less damage but can be thrown
T-junction and Fourway pipes are slower but hit harder.

All pipes now also have unique shapes in storage.

## Why / Balance
40% because hitting people with pipes is funny, 40% because I felt having the most obvious blunt weapon be a weapon would be cool, and 20% because I see people talking about it in the discord frequently
To get these pipes which are about equal to crowbars, you need both a crowbar and a wrench. I think this is fine.

## Media
image

https://github.com/space-wizards/space-station-14/assets/140123969/8502a938-e280-4161-a306-f2bbfe0bae34

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Atmos metal pipes now deal blunt damage.

### CODE REVIEW

**Comment by Everturning** [comment]
or you can just have some steel, right??

**Comment by EmoGarbage404** [comment]
i don't really get the arbitrary variations in the attack rate and damage. While they all have roughly equal DPS, i think the higher base damage might pass some flat resistance thresholds in a kinda weird way.

Also, these should all have in-hands if people are going to be using them as weapons.

**Comment by mirrorcult** [comment]
needs inhands if these are going to be decent weapons

**Comment by FairlySadPanda** [comment]
Can it do the funny bonk sound effect please 🥺

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
