### PR TITLE
New Low-Mid Pop Station - Amber Station 

### PR DESCRIPTION
**Pull request by southbridge-fur**
## About the PR

Amber station, an ex-independent amalgamation of various ships cobbled together around some asteroids which has recently come under the ownership of Nanotransen. 

This station is intended for low and medium populations. A lot of things are designed to be easy to set up for skeleton crews but still offer depth for higher amounts of players. 

There is 
- No containment area, the station can be run mostly off of solars + the AME however setting up the TEG is the best source of power.
- Sec is a carved-out nukie ship
- Cargo is a carved-out ATS
- Several other departments feature elements from various ships. 
- Atmosia takes the center of the map
- Plenty of fun secrets to find! 

## Why / Balance

When playing on Wizden servers during low-pop hours it can get a bit boring rotating between only a couple maps. This map is intended to add some more variety to the selection.

## Technical details

I've been keeping this branch up to date with the main branch so I have all the new features like dim lights added as well. 

## Media

Map Render as of [bc18367](https://github.com/space-wizards/space-station-14/pull/33441/commits/bc183671022878a148eb7b2700fc953907f7490f)

Amber-0

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Southbridge, Flipsie27

- add: Added a new low-mid pop map: Amber Station

### CODE REVIEW

**Comment by southbridge-fur** [comment]
I need to do a bit more work but I figured I'd open my PR now so I can collect comments

**Comment by ScarKy0** [comment]
I love the gimmick of this map so much

**Comment by southbridge-fur** [comment]
I've gotten a lot of feedback from Emisse which I'll implement later today.

**Comment by Thatonestomf** [comment]
What's the main gimmick? To me it looks like a normal station with core's tiling.
Not bashing on the station or anything, just asking

**Comment by ScarKy0** [comment]
> What's the main gimmick? To me it looks like a normal station with core's tiling.
Not bashing on the station or anything, just asking

From what ive seen and read on the PR, the gimmick is the fact the station is built from different parts of many shuttles (cargo is partially the ATS, sec is the nukie shuttle, etc)

**Comment by SpaceLizardSky** [comment]
the station looks nice

**Comment by cohanna** [comment]
is it possible to throw in a few thrusters and shuttle parts for salv, since the station is a bunch of reclaimed shuttles i feel there would be some parts left over that cargo might be able to use.

**Comment by GoodWheatley** [comment]
> > What's the main gimmick? To me it looks like a normal station with core's tiling.
> > Not bashing on the station or anything, just asking
> 
> From what ive seen and read on the PR, the gimmick is the fact the station is built from different parts of many shuttles (cargo is partially the ATS, sec is the nukie shuttle, etc)

I feel like this would be more obvious if those departments had different types of flooring that were taken from the shuttle

**Comment by southbridge-fur** [comment]
> > > What's the main gimmick? To me it looks like a normal station with core's tiling.
> > > Not bashing on the station or anything, just asking
> > 
> > 
> > From what ive seen and read on the PR, the gimmick is the fact the station is built from different parts of many shuttles (cargo is partially the ATS, sec is the nukie shuttle, etc)
> 
> I feel like this would be more obvious if those departments had different types of flooring that were taken from the shuttle

This was something I tried to do early on but it made the station a confusing mess to look at. Plus most shuttles have really intricate flooring designs which don't work when recontextualized into a station.

**Comment by saga3152** [comment]
The wastenet looks weird, why does the waste go to tye burn chamber? Also there's something wront with the water puddle in maints under the TEG.

**Comment by K3-1R** [comment]
Map looks great!

**Pull request merged**
