### PR TITLE
Adds the Head of Greytide stamp

### PR DESCRIPTION
**Pull request by ArtisticRoomba**
## About the PR

Adds the Head of Greytide stamp, a cruel stamp made out of a screwdriver and a bar of soap **(you cannot make/handcraft this item)**. Stamps documents with a "Head of Greytide" label. The stamp icon on the paper is a colored in grey version of the HoS stamp.

Added the stamp to the maints lockers lootpool with a 5% chance, on par with the magicarp plushie.

A few notes on this PR:
- I did not want to make the stamp on paper look like it was drawn with a No. 2 pencil. Coding that is a can of worms that I would not like to merge unless it's done right (spoiler alert: I can't do it right the first time, so I won't!)
- The stamp sprite is drawn by yours truly. If you were wondering. But you could probably already tell.

## Why / Balance

Feature requested jokingly on the SS14 discord, I thought I would jokingly make it a reality. It requires no code and I was looking for an excuse to contribute something to SS14, so here it is.
"""discussion""" on the SS14 discord about the HoG stamp: https://discord.com/channels/310555209753690112/900473545040207942/1262352310793797744

## Technical details

Adds respective entries in rubber_stamp.yml, stamps.rsi/meta.json, bureaucracy.rsi/meta.json.
Adds a RubberStampGreytide with prob 0.05 to maints lockers and it's variant in Lockers/misc.yml.

## Media

Content Client_GknJyObOu0
Content Client_SQ4OjgijGi
Content Client_H7lr2DGcoz
https://github.com/user-attachments/assets/a97424be-f4d1-4f9a-a545-965e09b4e0be

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes.

**Changelog**

:cl:
- add: Added the greytide stamp. This stamp can be rarely found in maints lockers.

### CODE REVIEW

**Comment by Catdere** [comment]
Having this as maints loot is cool and all but I think it would be better to have this as a Passenger loadout item

**Comment by Wudanty** [comment]
> Having this as maints loot is cool and all but I think it would be better to have this as a Passenger loadout item

Takes the hype away.

**Comment by SlamBamActionman** [comment]
1k hours prestige loadout item.

If I read the sprite correctly that is a screwdriver stuck in a soap? A fun idea for a tider stamp, though the sprite is a bit hard to read as that.

**Comment by UbaserB** [comment]
> 1k hours prestige loadout item.

i would rather it be 100 hours if that was the case

**Comment by Djungelskog2** [comment]
I think it's a better idea to make them just about as rare as insuls as maints loot, I can imagine people just going around stamping everything they see. It also adds novelty and prestige if there's only very few and you have to go hunting for them

**Comment by Djungelskog2** [comment]
(I think only people actually involved in bureaucracy should be stamping anything and have access to stamps too) 
Also probably change the description to describe what it is accurately

**Comment by Catdere** [comment]
> (I think only people actually involved in bureaucracy should be stamping anything and have access to stamps too) Also probably change the description to describe what it is accurately

Mime, Clown, Warden, Det, Chaps. Lawyer. I think you forget that these jobs also have stamps..

**Comment by IProduceWidgets** [comment]
I think this might cheapen the steal objective a bit.

**Comment by IamVelcroboy** [comment]
It's a fun idea but should definitely be rare. It would be silly to have 15 HoGs running around. Way cooler if there's just one.

**Comment by ArtisticRoomba** [comment]
Hi all! Thanks for the comments.

> Having this as maints loot is cool and all but I think it would be better to have this as a Passenger loadout item

The problem with this is that any passenger with a set amount of hours gets this item. It's something you cannot control. Having this only in maints lockers is something you can control.

> If I read the sprite correctly that is a screwdriver stuck in a soap? A fun idea for a tider stamp, though the sprite is a bit hard to read as that.

Yeah... I know it's a bit hard to read. Not the best sprite, but I have very little space to work with, stamps are a very small sprite.

> I think it's a better idea to make them just about as rare as insuls as maints loot, I can imagine people just going around stamping everything they see. It also adds novelty and prestige if there's only very few and you have to go hunting for them

They ARE as rare as insuls maints loot. Insuls (`ClothingHandsGlovesColorYellow`) have a prob of 0.05 or 5%, on par with the stamp. I used this prob value because I only saw about one magicarp every few rounds, from searching a lot of lockers. Also, the modular receiver, a component in making an improvised gun, is actually a 10% chance, and I only see 1 of those items every few rounds.

If we want, we could reduce the rarity to just 1%. It's no problem for me. But I would like to see this item.

The chances are supposed to make it so 99% of the time there is just 1 in a round. Having it be a passenger prestige makes it so everyone has it. And when everyone's special, no one is.

**Comment by Djungelskog2** [comment]
> > (I think only people actually involved in bureaucracy should be stamping anything and have access to stamps too) Also probably change the description to describe what it is accurately
> 
> Mime, Clown, Warden, Det, Chaps. Lawyer. I think you forget that these jobs also have stamps..

All of those have clear uses for their stamps, even the mime and clown who can use it for fun circus gimmicks and stuff phony paperwork

**Comment by Reese1243** [comment]
its a neat idea, but the sprite looks inconsistent with the other stamps. looks kinda out of place imo.

**Comment by ArtisticRoomba** [comment]
I"m planning to resprite the stamp to make it more in-line and discernable with all other stamps. I'm also thinking about halving the chance for it to appear in lockers, but I might not, we'll see.

**Comment by HelpTheSteak** [comment]
Should probably map it into the greytide churches that are on box and core as well but that's another prs problem

**Comment by ArtisticRoomba** [comment]
Made some new stamp sprites with consistency in mind. Here are two versions compared to Det's stamp.

Let me know which one you guys would like to see merged!

gimp-2 10_2sJy7b4yIK

I'm probably going to make the stamp a little rarer and add some misc stuff.

**Comment by ArtisticRoomba** [comment]
New changes. Halved the chances from `prob: 0.05` (5%) to `prob: 0.025` (2.5%). Resprited to the one that looks more like a screwdriver, not a retextured bulky head. Added a custom description. Let me know if it's too OOC or anything needs to be changed.

Content Client_y5JFh5ij0C
Content Client_9VFUhK7ZiC

**Comment by ilyamikcoder** [comment]
Dear lord this is actually getting developed. You are so true for this :1st_place_medal:

**Comment by ArtisticRoomba** [comment]
Don't merge this yet, I'll redo my shit after #30579 gets merged.

**Comment by ArtisticRoomba** [comment]
I'll redo le shit and change the sprite to one graciously provided by UbaserB (thanks!!!!!!)
as well as changing the stamp to just "greytide" not "head of greytide", I think this fits the best.

**Comment by UbaserB** [comment]
Are you coming back to adding those changes?

**Comment by ArtisticRoomba** [comment]
> Are you coming back to adding those changes?

yep! I told myself "oh i'm going to work on it later" and then never worked on it :)
making my changes now

**Comment by UbaserB** [comment]
tfw force push

**Comment by ArtisticRoomba** [comment]
This PR is now ready to merge, I have no intentions of modifying it further (unless I am told to)

New changes:

Used the sprite provided by @UbaserB because I suck at spriting
Changed the description because it no longer fit, let me know if it needs changing

image
image

**Comment by UbaserB** [comment]
Thanks for contributing!

**Comment by UbaserB** [comment]
WAIT
WAIT HOLD ON

**Comment by ArtisticRoomba** [comment]
Please don't tell me I turbofucked git up and you merged my fuckup

**Comment by UbaserB** [comment]
> Please don't tell me I turbofucked git up and you merged my fuckup

no i just tapped the wrong thing and im new so i have no clue how to fix this

**Comment by KittenColony** [comment]
GOOD JOB DEVI!

**Comment by UbaserB** [comment]
> GOOD JOB DEVI!

THE BUTTONS ARE SO CLOSE TOGETHER

**Comment by lzk228** [comment]
ss14 github 08.25.24 incident

**Comment by Winkarst-cpu** [comment]
UbaserB is now a real maintainer 👍

**Comment by ArtisticRoomba** [comment]
Oooooooooo you want to keep my PR merged oooooo you want to skip maintainer vote oooooooooooo

**Comment by UbaserB** [comment]
> Oooooooooo you want to keep my PR merged oooooo you want to skip maintainer vote oooooooooooo

it did not skip maintainer vote

**Comment by UbaserB** [comment]
good news i was just an idiot and yes it was a mistake, but there are no problems 👍🏻

**Comment by Moomoobeef** [comment]
heh, HoG

**Pull request merged**
