### PR TITLE
Add placing items into storage when Storage UI is clicked with open hand.

### LINKED ISSUE #485: Place items into storage when Storage UI is clicked with item in hand
When a Storage UI of a storage item like the backpack is open, add the ability to click on that UI with an item in hand to place the item into the backpack.

### PR DESCRIPTION
**Pull request by FL-OZ**
fixes #485 (for realsies)
Peek 2020-05-11 18-51

### CODE REVIEW

**Comment by PJB3005** [comment]
There should be some text indicating that you can click that blank space.

**Comment by FL-OZ** [comment]
@PJB3005

**Comment by Zumorica** [comment]
I'm not sure the current color when hovering is ideal. Maybe something just slightly darker than the background would fit better here? And it needs a bit of margin on the left.

**Comment by FL-OZ** [comment]
> I'm not sure the current color when hovering is ideal. Maybe something just slightly darker than the background would fit better here? And it needs a bit of margin on the left.
> And it needs a bit of margin on the left.

Yeah, that's because the list itself isnt centered. (not my fault :slightly_smiling_face: ) will fix.

**Comment by FL-OZ** [comment]
i think the buttons are offset because of the scrollcontainer having a bit of margin on the right for the scrollbar. cant really fix that.

**Pull request merged**
