### PR TITLE
Even spaced hotbar

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

the spacing was awful and terrible and i hated it.

also moves outerclothing to the main hotbar with the rest of clothing because why wasn't it there in the first place???

## Media

before:
image

after: 
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Comment by metalgearsloth** [comment]
Time to fuckup muscle memory.

**Comment by lzk228** [comment]
muscle memory my beloved

**Comment by arimah** [comment]
I don't mind the swapping of outerclothing and the exosuit slot, but the spacing around the hand slots matters to me: it helps guide the eyes to the arguably most important part of that UI. It helps you find your active hand at a glance, etc. Making everything _the same_ is not usually good when not everything is equivalent.

**Comment by UbaserB** [comment]
I dont mind it, just have some way to draw your focus to the hands like arimah mentioned

**Comment by deltanedas** [comment]
alternatively maybe the frame could be thicker on hand slots so they have a bit more importance

**Comment by arimah** [comment]
Spacing is one of the simplest and least intrusive ways of creating visual hierarchy without adding visual noise. If you want the hands to stand out, as I believe is a good idea, a little bit of spacing instantly creates three visual groups (of low cardinality – the human brain can keep track of 3-2-3 without needing to count). Different colours, bolding, and so on _can_ work, but will also make the hand slots stand out visually, which may be intrusive.

**Comment by EmoGarbage404** [comment]
> I don't mind the swapping of outerclothing and the exosuit slot, but the spacing around the hand slots matters to me: it helps guide the eyes to the arguably most important part of that UI. It helps you find your active hand at a glance, etc. Making everything _the same_ is not usually good when not everything is equivalent.

Hud_aligned_small

lots of SS13 servers just use slightly smaller icons which have the benefit of consistent spacing while also better displaying the visual weight.
Flareguy is porting a bunch of ss13 HUD themes with these adjusted sizes so those should probably help a fair bit.

also i feel like the hands are outlined more by the fact that they are centered in the viewport. As for the active hand, it literally has a special highlight for the sole purpose of standing out when selected.

**Comment by Rainbeon** [comment]
Honestly I love the moving of exosuit and exosuit backslot but kinda prefer the 3-2-3 bottom the way it is

**Pull request merged**
