### PR TITLE
Removes hacky behavior from DeviceListSystem

### LINKED ISSUE #11224: Air Alarm "Show" connections doesn't work between sessions.
When mapping air alarms, you can use the Show button for a visual to see already connected entities. 

If you end your mapping session the next time this function is borked. Hitting the Show button flashes the connections for a split second but doesn't maintain the visual.

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR 

Removes hacky behavior from DeviceListSystem, and replaces it with a simple dirty on component initialization. Oops.

Fixes #11224.

### CODE REVIEW

**Comment by ElectroJr** [comment]
Why is a BUI message even updating networked component data? That should just automatically get sent to clients whenever it gets dirtied by the server?

**Comment by vulppine** [comment]
> Why is a BUI message even updating networked component data? That should just automatically get sent to clients whenever it gets dirtied by the server?

one of the issues is that dirty will not work if the component isn't in the MapInit life stage (at least, iirc - i was doing testing against mapping mode and ran into this issue) - which, if you're in mapping mode, no components are in that stage

this entire manual sync really is honestly a dirty hack to get around this limitation

**Comment by ElectroJr** [comment]
Dirty should definitely work even in mapping mode, otherwise mapping wouldn't work and you'd never see the effect of any changes you made to an existing entity.

**Comment by vulppine** [comment]
alright - i'll look through this again and refit this PR to remove that bad hack i made and make it so that data actually syncs properly to the client

**Comment by vulppine** [comment]
yeah, i must've totally misread something when i was doing the visualizer - i may have rushed it and brute forced my way into it making it work, this should make it much more nicer

**Review by ElectroJr — APPROVED** [review]

**Pull request merged**
