### PR TITLE
Ventilation crawl 

### PR DESCRIPTION
**Pull request by VigersRay**
## About the PR

Well, a clear attempt to implement a ventilation crawling system without much bells and whistles. Fun tile movement, what could be better. Here's what I got:
- Gases in pipes completely affect creatures in them.
- While crawling, everyone around hears sounds. I took them from FreeSound, so I hope there will be no problems.
- Ventilation can be welded, it's good that the sprites were already there, I just needed to add a couple of lines.
- When a player is in ventilation he sees pipes.
- Small creatures like slimes, spiders, monkeys can climb there, I hope I haven't forgotten anyone.
- If there is no continuation of the pipe, but there is an exit, the creature will be able to exit.
- if you unscrew the pipe in which the creature is located, it will fall out of it, also with the removal.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Youtube video:
https://youtu.be/MpXd5Tp_srg

**Changelog**

:cl: VigersRay
- add: Many small creatures have learned to climb vents.

### CODE REVIEW

**Comment by hord-brayden** [comment]
This is cool, nice work! I can already hear the rat king banging around in there sayin "fuhgettaboutit, I'm walkin here!"

**Comment by dmnct** [comment]
The ventcrawling player should probably have some sort of indicator about their location, unless busy pipe systems being a nightmare to navigate is considered a feature

**Comment by VigersRay** [comment]
> The ventcrawling player should probably have some sort of indicator about their location, unless busy pipe systems being a nightmare to navigate is considered a feature

In ss13 you didn't see yourself, but in general, of course, you can make a translucent sprite that only the player will see, probably...
Although, to be honest, I did it and uploaded it to my build a couple of days ago, and I had no problems with navigation.

**Comment by dmnct** [comment]
The navigation issue is most apparent when trying to take a side path, especially if multiple forks/sidelines are next to each other. Especially horizontally it's not easy to judge the "center" of your view, since its offset by oldchat. It's not a huge thing, but it feels like a needless annoyance to not being able to make your "offramp exit" on the first try.

**Comment by dmnct** [comment]
The tile movement feels super weird and disjointed from normal movement though, even if I understand why it must have been a lot simpler to code it that way

**Comment by VigersRay** [comment]
> The navigation issue is most apparent when trying to take a side path, especially if multiple forks/sidelines are next to each other. Especially horizontally it's not easy to judge the "center" of your view, since its offset by oldchat. It's not a huge thing, but it feels like a needless annoyance to not being able to make your "offramp exit" on the first try.

I think you should try this movement first, formally you can move gently by pressing the key 1 time approaching the fork. Although, to be honest, when I first started making the system, the movement was terrible and had a lot of bugs. and well, it was also jerky in tiles and not smooth, horror.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
1. Movement code needs to always be in shared.
2. It looks like you copy-pasted disposals code, please don't do that.

**Comment by VigersRay** [comment]
> 1. Movement code needs to always be in shared.
> 2. It looks like you copy-pasted disposals code, please don't do that.

1. Well, I kind of understood about this, but is it normal that I catch it through MoveInputEvent?
2. Do you want me to check if there are pipes in the next direction through the NodeContainer?

**Comment by metalgearsloth** [comment]
1. Well, I kind of understood about this, but is it normal that I catch it through MoveInputEvent?
It should be its own movement controller realistically.

2. Do you want me to check if there are pipes in the next direction through the NodeContainer?

Sure.

**Comment by VigersRay** [comment]
> 1. Well, I kind of understood about this, but is it normal that I catch it through MoveInputEvent?
>    It should be its own movement controller realistically.
> 2. Do you want me to check if there are pipes in the next direction through the NodeContainer?
> 
> Sure.

In the likeness of how the shuttle control is implemented?

**Comment by keronshb** [comment]
vent-among-us

**Comment by brainfood1183** [comment]
Next you need to make ability for small creatures to move below tiles :)

**Comment by potato1234x** [comment]
if you go crit in the vent while moving, you will keep moving in the direction you died in. so if that happens you'll just go careening across the station

**Comment by AJCM-git** [comment]
@VigersRay You coming back to this?

**Comment by Dutch-VanDerLinde** [comment]
@VigersRay Could I port this PR to RMC14?

**Comment by VigersRay** [comment]
> @VigersRay Could I port this PR to RMC14?

Starligth has long since ported this to themselves, so it's better to take the fixed version from there.

**Pull request closed without merging**
