### PR TITLE
freezer prevents nuclear annihilation

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

image

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl since we already had one that says this works, this crate was just an oversight.

### CODE REVIEW

**Comment by UbaserB** [comment]
Why did this get merged when #24844 just got merged

**Comment by EmoGarbage404** [comment]
> Why did this get merged when #24844 just got merged

the values between the two PRs are the same?

**Comment by metalgearsloth** [comment]
It's 2 different entities.

**Comment by metalgearsloth** [comment]
The real crime is not leaving a comment to update the other one so they will probably get out of alignment at some point.

**Comment by UbaserB** [comment]
oh

**Comment by deltanedas** [comment]
or real pro adding a parent for them to share the resistance

**Pull request merged**
