### PR TITLE
Hamletmech

### PR DESCRIPTION
**Pull request by brainfood1183**
## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by deltanedas** [comment]
branch is still fucked do the good old save sprites + git diff + git patch + mv trick

**Comment by brainfood1183** [comment]
> branch is still fucked do the good old save sprites + git diff + git patch + mv trick

dont really know that trick

**Comment by deltanedas** [comment]
no i mean you have 1.5M lines commited go remake it from scratch :skull:

**Comment by deltanedas** [comment]
i think the only way to fix this pr is just to force push

**Comment by brainfood1183** [comment]
> i think the only way to fix this pr is just to force push

i even tried just replacing the whole of the brnach with master manually but this is where i am at with files that have slight differences to master but impossible to actually fix manually.

**Pull request closed without merging**
