### PR TITLE
APC Power cycling

### PR DESCRIPTION
**Pull request by collinlunn**
Adds a "Cycle Power" button to APCs. This feature was created in response to PJB's interest in preventing the crew from connecting every room together with LV wire.

Cycling power disables all APCs on that LV network from providing power for a span of time. After, cycling power goes on cooldown.

This disincentivizes making one large LV network because an antagonist could build an APC on the single network and use it to cycle the entire station's power. The cooldown keeps them from permanently disabling all power in the worst-case scenario.

### CODE REVIEW

**Comment by PJB3005** [comment]
This is a *very* neat solution to the problem, not gonna lie.

**Comment by ike709** [comment]
Why not just have a max output on the APCs?

**Comment by brndd** [comment]
> Why not just have a max output on the APCs?

This, or a maximum distance for LV wires. Combine this with APCs shorting out and powering off if two are connected to the same LV wire network and the problem would be solved without relying on bullying.

**Comment by collinlunn** [comment]
My understanding is that we don't care deeply about preventing the crew from making a single large network, outside of the fact that it can make power nearly un-sabotageable, which we want as an antagonist tool.

**Pull request closed without merging**
