### PR TITLE
No More DMCA over pirate_start

### LINKED ISSUE #25111: pirate_start.ogg samples a part from the Sid Meier's Pirates! official soundtrack
## Description

I don't know how to explain this in detail, it literally samples the music. It's a blatantly obvious copyright violation.
**Reproduction**

listen closely at "55:19" in the video https://youtu.be/FMUJgzMYLqw?t=3319 and then listen to pirate_start.ogg
**Screenshots**

n/a
**Additional context**

n/a

### PR DESCRIPTION
**Pull request by PoorMansDreams**
## About the PR

Avoid DMCA since original pirate_start.ogg ripped straight from sid's pirates
## Why / Balance

Don't want that DMCA strike, 
And it goes hard 🏴‍☠️
fixes #25111
## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
https://soundcloud.com/user-983755196/ss14-pirates-quieter-beeps-more-arrrg?si=75b91620fee3494fa471cc35fd6d8e57&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

https://www.youtube.com/watch?v=LFE-h84JD10
## Breaking changes

**Changelog**

:cl:
- add: New pirate start sound!

### CODE REVIEW

**Comment by PoorMansDreams** [comment]
https://www.youtube.com/watch?v=LFE-h84JD10
video for it just in case

**Comment by PoorMansDreams** [comment]
fixes #25111

**Comment by deltanedas** [comment]
put that in the pr description not a comment

**Comment by notquitehadouken** [comment]
test fail unrelated

**Pull request merged**
