### PR TITLE
Converts all surgery tools to /tg/ and /vg/ sprites (and removes some surgery tools)

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
What it says on the tin - this converts every single surgery tool in the game to use a mix of (edited) /tg/ and /vg/ sprites.
This also removes the ones that were eris-exclusive like the bonesaw. This shouldn't matter at all ingame (surgery tools are obviously largely unused as of now,) outside of some things discussed in the reasoning part of this.
Also also moves the surgery RSI into tools, because surgery tools are... well, exactly that. They're not specific, ambigious medical doohickies.

Jez Approved:tm: (I think? I got the go-ahead for replacing items & sprites, at least.)

## Why / Balance
CEV-Eris sprites bad, yadda yadda you know the drill. It's honestly kind of baffling that this wasn't done earlier considering how hilariously mediocre they are in comparison to the /tg/ ones - beyond not fitting the style, they're also just way harder to identify and have very noticable contrast issues.

The removed tools have mainly just been removed due to lacking equivalents in /tg/ and /vg/, it doesn't really matter in any case since they don't really serve any purpose outside of surgery yet, and are thus basically just paperweights right now (outside of one exception.)

It is worth noting that the removal of the bonesaw will end up changing balance (this is the one exception mentioned above.) Since it's been removed, all surgical bags will now start with the circular saw, which does 15 damage per hit. Lathes can also print them now.
This probably won't be *too* impactful considering it didn't exactly break the game in SS13, as far as I'm aware. Medical is probably one of the least powerful departments combat-wise in SS13 in any case, so giving them a decent melee weapon likely won't end up being a bad thing.

## Media
Not yet:tm: (this is drafted for a reason, I want to resprite some of the stuff in here.)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
ScalpelShiv & ScalpelAdvanced have been replaced with Scalpel. Saw, SawImprov, SawElectric, and SawAdvanced have all been replaced with CircularSaw.
This shouldn't require any changes outside of maybe changing tool usage prototypes downstream, all prototypes have been migrated.

**Changelog**
:cl:
- tweak: All surgery tools now use sprites from /tg/station and /vg/station.
- add: The circular saw now has a unique hitsound.
- remove: Removed all of the CEV-Eris exclusive surgery tools (basically everything that wasn't a basic surgery tool or the Laser Scalpel.) This includes the bonesaw - it has been replaced with the Circular Saw in all instances where it would have shown up.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
gonna be real wit u, these not only look far worse than our current set, but they aren't even internally consistent in visual style. The coloring, palette, and style is all over the place. Plus, the laser scalpel looks especially out of place.

**Comment by Eden077** [comment]
Yeah I agree with Emo, these are super out of the current game style, it just doesn't fit

**Comment by VektorZ1** [comment]
The new sprites don't look good

**Comment by Flareguy** [comment]
Drafted to work on the sprites more - I'm planning on mostly using what exists here as a base, but they should hopefully be a little more consistent after the fact.

**Comment by Partmedia** [comment]
Nit: the changelog is a bit long and excessively wordy, especially considering that surgery tools are currently non-functional.

**Comment by Flareguy** [comment]
Closing until I make these better.

**Pull request closed without merging**
