### PR TITLE
Unlimited markings for humans and slimes.

### PR DESCRIPTION
**Pull request by Adrian16199**
## About the PR

I have deleted the limiter for markings for both human and slime.
## Why / Balance

My main reasoning is the fact that with the beatiful addition of bandages marking, you cant exactly equip all of them, there is also the second point that the lizards do have unlimited markings so i personally think it would make sense to make it bit fair.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- remove: Removes marking limiter for human and slimes.

### CODE REVIEW

**Comment by lzk228** [comment]
bandages should has limit, so you cant make a mumie

**Comment by Adrian16199** [comment]
I mean, it could be done to be just up to 4, I just dont think 2 is enough.

**Comment by Hmeister-fake** [comment]
> bandages should has limit, so you cant make a mumie

What if, i wanna be Joshua Graham from FNV? :godo:

**Comment by Kadeo64** [comment]
> bandages should has limit, so you cant make a mumie

I don't get why this is like, a bad thing (balance wise AND rp wise)
balance wise you're just making yourself MORE identifiable, and RP wise it could lead to some funny moments with super burn victims

**Comment by UbaserB** [comment]
markings my beloved, also i think the person who made the gauze markings is working on a full-body gauze marking in the first place, so i see no reason why not being able to make a mummy at this point in time is bad.

**Comment by EmoGarbage404** [comment]
Marking limits exist to preserve the art style of the game while still allowing customization. While everyone flying around with a million tattoos, horns, and dragon wings would be quite epic, it's to the detriment of the overall art style of the game. Allowing people to have an abundance of non-standard features generally just does not look that good and isn't really something we should allow.

> lizards do have unlimited markings so i personally think it would make sense to make it bit fair.

lizards having unlimited markings in some categories seems to be a bug introduced with the addition of some new markings. It should be fixed.

**Pull request closed without merging**
