### PR TITLE
Testing plantTrait prototypes as concept.

### PR DESCRIPTION
**Pull request by drteaspoon420**
Playing around with idea of plant traits being prototypes.

## About the PR

Current mutation system requires all of the 'fun' featues to be hard coded. This is just my experiment on how they could be expressed with *.yml files.
Current version does not solve the issue of expressing the traits on the growing plant, only the product or 'fruit'.

## Why / Balance

Reduce the amount of hardcoded content that can be expressed in *.yml's declerative manner instead and reduce the barrier for entry to other contributors less familiar with C#

## Technical details

new server prototype 'plantTrait' that contains components declerations and possibly meta data about  whether the trait is expressed on plant, product or both.
Due to dynamic nature of the amount of prototypes the totalbits constant in mutation randomization cannot be `const int`

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Doru991** [comment]
I've been planning on doing something similar too, if you'd like any assistance I'd be happy ti work on this with you.

**Comment by drteaspoon420** [comment]
If @Partmedia gives the concept it's blessing, I would love to get aid in this. But If there is objections to this 'idea' I don't want to pull anyone waste their time on this.

**Comment by drteaspoon420** [comment]
Current things to solve/ponder:
- Logic to add / remove components on plants (not the product) when it gains/losses mutations.
- Allow parameter ranges for the component variables, example re-implementing bioluminecence.
- Conflict resolution between traits that have overlapping components.
- Migrate/Add more stuff to plant traits.

**Comment by Doru991** [comment]
The problem is that the plant is currently not an entity by itself, and the tray itself holds many components that the plant should. If the plant was an independent entity, it'd be trivial to add components to it and removing them wouldn't be an issue

**Comment by Doru991** [comment]
Being prototypes, some complex mutations could also have specific mutation functions bound to them

**Comment by Partmedia** [comment]
Thank you for checking in with your idea. I appreciate you giving me the opportunity to give my two cents :)

In general, I support encoding more fun plant things like traits which add components to be runtime-definable, for all the reasons that you stated. I would also be in favor of defining all "flip a bit and add a few components" type traits for these traits you've identified.

However, I do want to point out that this type of "one-bit flip and add some components" mutation only represents a small fraction of the types of mutations available.

Obviously, the current way that total bits are summed together is not ideal, but this could be turned into a compile-time computation via a source generator. Of course there are some advantages to compile-time static type checking. And I wonder whether or not it's possible to move all of the current functionality into yaml without doubling C# line count :p

**Comment by Doru991** [comment]
> Obviously, the current way that total bits are summed together is not ideal, but this could be turned into a compile-time computation via a source generator. Of course there are some advantages to compile-time static type checking. And I wonder whether or not it's possible to move all of the current functionality into yaml without doubling C# line count :p

While I'm not sure how it'd work for more complex traits, in the case of ones that are a simple bool, couldn't we build a dictionary of traits and their assigned bits based on a yml file, and then calculate the updated amount of total bits at runtime?

**Comment by drteaspoon420** [comment]
Unless we want to have something closer to DNA sequencing of plant traits where one trait can subvert some other etc. (and if that is the case then, Lets go all the way!) the code/idea in this draft assumes the 'trait' is boolean value but the implementation of that is delegated to the component list in yml file instead of hard coding it.

But if there is interest in overhauling the whole mutation and cross breeding system that would require quite a lot of documentation to be kept coherent.

With current systems, turning all of the mutation into yml, would practically just mean `seed` prototypes with less values and overriding all in cross breeding or none at all.

...that might not be bad idea. (except with some corner cases but those can be solved)

**Comment by Partmedia** [comment]
Perhaps you should coordinate with the author of #20602 and discuss how to proceed.

**Comment by deltanedas** [comment]
> Do we actually want to have something closer to DNA sequencing of plant traits where one trait can subvert some other etc. (and if that is the case then, Lets go all the way!)? The code/idea in this draft assumes the 'trait' is boolean value but the implementation of that is delegated to the component list in yml file instead of hard coding it.

sounds like dominant alleles :trollface:
each trait is a 2 bit number, basically 2 alleles, and the recessive behaviour is shown physically when the trait is 0, and the dominant behaviour when 1-3 as the dominant alleles are expressed in the gene :nerd_face:

**Comment by moonheart08** [comment]
This'd likely be dramatically easier if you first rewrote the plants themselves to be entities.

**Comment by deltanedas** [comment]
yes any plant genetics and stuff should be done after plant ecs gaming

**Comment by AJCM-git** [comment]
Closing due to inactivity and this not being the preferred solution

**Pull request closed without merging**
