### PR TITLE
Laser namechange and some buffs

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Renamed all laser "guns" to make it easier to tell what they actually are
We now have laser pistols and rifles (and the "retro laser blaster" which is technically a sidearm/pistol too but blaster just sounded more on-brand for retro)

Changed the practice laser gun/rifle description because terminator reference, and the advanced laser gun/pistol's description to hint that it does higher damage than the common laser weapons

No ids were changed

Captain's pistol and Behonker Eye were reduced to size 10 as other pistols

Laser Crate now contains standard lasers instead of retro lasers

Retro lasers were buffed to the slightly higher damage of premium lasers due to their new rarity and so they are no longer exactly the same as normal laser rifles

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: The various laser guns are now called rifles or pistols.
- tweak: Retro laser blasters now deal 20% more damage. 
- tweak: Laser deliveries now contain 3 laser rifles instead of 3 retro laser blasters.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
>antique laser pistol
>weighs 30

**Comment by Emisse** [comment]
im fine with weight being lowered on caps laser, its high risk afterall

**Comment by Errant-4** [comment]
> im fine with weight being lowered on caps laser, its high risk afterall

Ok I will lower that, should I leave the size at 30 on the advanced laser pistol, though? I assume it was only (just today) fixed to 30 from 50 because the Antique is 30, but there is valid concern that one could carry a pile of advanced laser pistols (then again that's the battery weapon you LEAST need to amass). 
Should the laser pistol be parented to rifle size instead with size 50? Or leave it at 30

**Comment by Emisse** [comment]
leave advanced at 30

**Comment by Errant-4** [comment]
The Behonker Eye is also size 30, it's essentially a faster-firing antique laser pistol but can't readily be acquired once, let alone multiple times. Should that go to 10 too?

**Comment by Errant-4** [comment]
After staring at laser rifle and retro laser blaster for a while and wondering why there are even two of these if they are completely identical, I have changed retro laser damage to the +20% prototype and replaced them with standard rifles in the orderable crate. Now retro blasters are a rare upgrade

**Pull request merged**
