### PR TITLE
Portable Power Monitor

### PR DESCRIPTION
**Pull request by DenisShvalov**
## About the PR
Added portable power monitor as high-risk item to CE
Added traitor objective to steal this item

## Why / Balance
Power monitoring console is cool thing to fix cable sabotage, but there is a problem - you need to drag this console with you if you can't remember map well. So i decided to add this thing for help engineers.

To avoid making sabotage into hell, i decided to add it as limited only-ce item (like CMO's crew monitor). Also second high-risk to CE

## Technical details
Just prototypes

## Media

https://github.com/space-wizards/space-station-14/assets/115770678/b306c83c-0f09-45be-a562-cbf6c10089f0

https://github.com/space-wizards/space-station-14/assets/115770678/76425bb8-47d1-479b-b140-93f6608544d5

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, 

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: New portable power monitor as CE's high-risk

### CODE REVIEW

**Comment by Plykiya** [comment]
I wish pAI maps had your moving marker of their own location....
Looks fun to use.

**Comment by DenisShvalov** [comment]
> op?

A little bit yes, so i added it as high-risk to CE only.

**Comment by TheShuEd** [comment]
All that remains is to do handheld research monitoring to rd

**Comment by keronshb** [comment]
There's no reason to make everything portable, even if it's extremely limited. The console is there to at least promote some sort of cooperation. If you're out in the field and there's no one by the console, you need to use a multitool on wires to figure out where the issue is. Traitors have absolutely no use for this and adds bloat to steal objectives.

**Comment by Jezithyr** [comment]
Second this, while I do see some QOL improvements I do think it's really important that we don't make consoles redundant.

**Pull request closed without merging**
