### PR TITLE
Pink station

### PR DESCRIPTION
**Pull request by Ozzy-Land**
## About the PR
Added many items for the Financial Supervisor and Blue Shield

## Why / Balance
Upcoming jobs

## Media
Credits all by: Vixen

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
- add: Added some clothes for the upcoming Financial Supervisor.
- add: Added some clothes and hardsuit option for the Blue Shield.

### CODE REVIEW

**Comment by LankLTE** [comment]
Wrong repo, I'm assuming.

**Comment by Ozzy-Land** [comment]
yes....

**Comment by Ozzy-Land** [comment]
so sorry..

**Comment by LankLTE** [comment]
Don't apologize, you're good, it happens. Just letting you know since sometimes people miss it.

**Pull request closed without merging**
