### PR TITLE
Let entities attack their outermost container

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Closes https://github.com/space-wizards/space-station-14/issues/13405 and closes https://github.com/space-wizards/space-station-14/issues/13403

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Rane
- fix: Fixed not being able to attack people who picked you up or attack lockers and crates from the inside.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
is this the outermost container or just the first container you're contained in? If you're inside of a bag inside a locker, for instance, should you only be allowed to attack the bag and not the locker?

**Comment by Elijahrane** [comment]
> is this the outermost container or just the first container you're contained in? If you're inside of a bag inside a locker, for instance, should you only be allowed to attack the bag and not the locker?

You can't target anything in between them since context menu for melee got removed...

**Comment by EmoGarbage404** [comment]
> You can't target anything in between them since context menu for melee got removed... You would have to destroy them in reverse order but it's better than being hardstuck because of melee regressions.

Makes sense. In the future, it would be nice to be able to attack the outermost container if you happen to be stuck inside multiple, but this is a good fix for now.

**Comment by Elijahrane** [comment]
hmmm, getting some inconsistent issues here, mostly because it checks CanAttack with no target on client before making an attack? it works for npcs though...

**Comment by Elijahrane** [comment]
ok, local testing seems to indicate that heavy attacks won't leave your container anyway so it's safe to just skip the check on null target.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
