### PR TITLE
Make the security belt contain more useful items by default

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
The security belt no longer contains tear gas or flashbangs by default, instead it contains a holobarrier projector and a handheld security radio.

## Why / Balance
Every time a secoff gets caught in an explosion of any size, it sets off a big annoying smoke cloud and flashes everyone around them. Tear gas and flashbangs are hardly ever useful and most of the time cadets have to be taught to get rid of them roundstart so they don't sabotage the rest of the crew after being hit by a dragon fireball.
Security radios and holobarriers are very useful things that imo don't see enough use. It's quite important for security to carry handheld radios with them, but a lot of the time they either forget or just don't care to use the sectech.

## Media
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Security belts now contain a holobarrier projector and a handheld security radio by default rather than tear gas and a flashbang.

### CODE REVIEW

**Comment by slarticodefast** [comment]
Test fail looks related, but I'm re-running it just to be sure

**Comment by thebadman4662** [comment]
Guaranteed holobarriers?! BLESSED PR.

I will miss my flashbang though, sec often runs out of them and warden/hos is always allergic to printing them. 😭

**Comment by baddiePRO** [comment]
gone are the days of using an exploding vape to teargas check the cadets :mistake:

**Comment by thebadman4662** [comment]
> > I will miss my flashbang though, sec often runs out of them and warden/hos is always allergic to printing them. 😭
> 
> you can get them from the vendor still, same for tear gas.

Security getting SecTech restocks I have seen only when I was cargo tech myself or engineer(back when substations were upgradeable, I would get T3 cells from seclites).

**Comment by Sarahon** [comment]
Them being in the belt helps cadets know they exist at all honestly. And I've had a smoke bomb save me many times just from blowing up and covering the enemies view - gives you a chance basically. I'd like to see the radio and seclite added to the belt and make it full on entry cause you do that every round anything. Rest can stay the same.

**Comment by LankLTE** [comment]
I still think removing at least flashbangs is weird, especially for a handheld radio which I’ve at least never gotten much use from. Holobarrier over tear gas makes sense though.

**Comment by thebadman4662** [comment]
> I still think removing at least flashbangs is weird, especially for a handheld radio which I’ve at least never gotten much use from. Holobarrier over tear gas makes sense though.

You do not use it till comms are down and every single secoff should have one if they can, but there are only 5 go around, though I guess every seccie having guaranteed radio would nerf antags in big sec crews as they no longer need to stay together as much to be in touch with radio communication.

**Comment by LankLTE** [comment]
> You do not use it till comms are down and every single secoff should have one if they can, but there are only 5 go around, though I guess every seccie having guaranteed radio would nerf antags in big sec crews as they no longer need to stay together as much to be in touch with radio communication.

Yeah, but sabotaging / naturally shutting off comms is supposed to be something Antags can capitalize on, though I guess having handheld radios at all kind of makes that irrelevant.

**Comment by superjj18** [comment]
> I still think removing at least flashbangs is weird, especially for a handheld radio which I’ve at least never gotten much use from. 

I would say that not using the radio says more about you than the radio, unless you’ve just never found yourself playing as a seccie when comms go down.

that being said radios still need to be updated with the mic/spot option (and maybe broadcast to headsets)

**Comment by LankLTE** [comment]
> I would say that not using the radio says more about you than the radio

I mean, yeah. It probably does. But I still think comms going down should be of at least some consequence to security.

**Pull request merged**
