### PR TITLE
Adds emote "Buzz" for moth

### PR DESCRIPTION
**Pull request by Wertanchik**
## About the PR
Moths and mothroachs now can use "buzzing" like "scream" emoting (scream can still used)
## Media

https://github.com/space-wizards/space-station-14/assets/48354940/3e57fd42-344a-4623-8f1a-373c807b1c85

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- add: Added "buzzing" emote for Moths and Mothroach

### CODE REVIEW

**Comment by jamessimo** [comment]
I like it as a concept but would really like it if there was another bussing noise like a calm buzz instead of using the "scream" buzz.

**Comment by Wertanchik** [comment]
> might want to include "buzzes" "buzzes!" and "buzzes."

done

**Comment by PokkeTigrex** [comment]
I imagine some audio manipulation of the scream can be done for buzzing. Possibly a shorter and higher pitched sample of it?

**Comment by PokkeTigrex** [comment]
Some examples I made, though, not something I'd use as its pretty scuffed. Likely needs to be played with more to get something nicer and calmer.
https://drive.google.com/drive/folders/1igCSHm__ho6frVKFlRNY60460c_eT7W8?usp=sharing

**Comment by Wertanchik** [comment]
> Some examples I made, though, not something I'd use as its pretty scuffed. Likely needs to be played with more to get something nicer and calmer. https://drive.google.com/drive/folders/1igCSHm__ho6frVKFlRNY60460c_eT7W8?usp=sharing

i tried, but my code just says no
why? idk
image-819
image-1323

**Pull request merged**
