### PR TITLE
Change Syndie Monkey Price 8-6 TC

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I decreased the Price of Monkey reinforcements from 8 to 6,
## Why / Balance

Monkies are awful in combat and anyone can take them out with 1-3 shoves and aren't worth 8TC 90% of the time unless the consience piloting it is robust.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Changed Monkey Reinf Price to 6TC

### CODE REVIEW

**Comment by Ilya246** [comment]
this has been discussed on discord at least one time and we agreed that 6 TC is a good price

**Comment by FungiFellow** [comment]
> So you are saying that they are worth 8TC if controlled by high-skill player?

Even if the person is Robust if they ever attempt to engage in melee they are liable to get disarmed/stunned and killed with their own weapon.

**Comment by asperger-sind** [comment]
> Even if the person is Robust if they ever attempt to engage in melee they are liable to get disarmed/stunned and killed with their own weapon.

Since contest removal you can't obliterate "smaller" mobs with disarms anymore because disarms are a flat 25% chance for 25 stamina damage.

**Comment by metalgearsloth** [comment]
sure whatever

**Pull request merged**
