### PR TITLE
tech disk 1984 (no tier 3)

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

you can no longer use tech disks to spoof t3 techs.
i'm fine with having alternative methods but this just turned into people unlocking everything and then using the printer to bypass the lockout to get le funny stuff.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Tech disks no longer contain exclusive discipline technology.
- tweak: Printing tech disks now costs fewer points.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Worth noting for people that dislike this change, making a new RD server would allow you to get the other t3 research, assuming we can build RD servers (I forgor)

**Comment by deltanedas** [comment]
i think that would be a reasonable bypass since:
- you need to get it from salv i think thats the only way
- you need to max out another tree
- you need to sync servers to use recipes
- you need to do i 3 times

**Comment by Anzarot121** [comment]
> Worth noting for people that dislike this change, making a new RD server would allow you to get the other t3 research, assuming we can build RD servers (I forgor)

THIS is the problem. We can't build them.

**Comment by Anzarot121** [comment]
Please do PR with crafting server RD. Let it require bananaium, plasma, glass, uranium, steel and plastic in huge quantities, but just add crafting to it. I would do it myself, but it would be shitcode.

**Pull request merged**
