### PR TITLE
Change the binary translator key's contraband designation to syndicate contraband + minor sprite change for consistency

### LINKED ISSUE #32173: Binary Key needs syndicate contraband designation + differentiating it from the standard NT binary key
## Description

Had a round where the Detective bought a binary key out of the uplink, so they could bribe the RD to research riot tech in exchange for the key. They then tried to argue that it was not contraband, because the contraband designation said it was restricted to science only.

Since the binary key can now only be obtained through the uplink, and it isn't a stealth item, it needs to be updated to illegal syndicate contraband. It's sprite should also be changed to a syndicate key type sprite to better designate it as illegal syndicate contraband. IIRC it might just be setting a different component in YAML, so no spriting required.

An admin ruling in the wizden discord supports this, stating (https://discord.com/channels/310555209753690112/1125299494066597888/1284472586960502784):

> > [panzervor] So apparently RD had the binary key removed from their locker, making it only accessible via syndicate uplink
> > Is it fair to assume that it is now contraband? I don't think its contra tracker has been updated since its removal

> [.jarmer] Yes, it would be syndicate contraband now, make a GitHub issue or something

**Reproduction**

1. Acquire the binary key though the uplink
2. Marked as science restricted
3. Cry because you can't possibly argue with someone about this when it has this designation

**Screenshots**

No screenies for now, am too lazy.

**Additional context**

### PR DESCRIPTION
**Pull request by ArtisticRoomba**
## About the PR

Gives the binary key a new borg icon and changes it's frame to be syndicate for better differentiation between regular station keys and contraband. Also marks the key as syndicate contraband.

This fixes #32173.

## Why / Balance

Now that AI is here, RD no longer has their binary key. However, you can still purchase the key at an uplink for 1 TC. This key still has the "science and silicon restricted" contraband designation even though the key is only obtainable using an uplink. This has led to some confusion and arguments IC about "whether it's contraband and illegal to use or not".

It now has a new syndie keyframe and contraband designation to make it intuitively obvious that it's contraband.

This was also confirmed in discord that it should now be marked appropriately as syndicate contraband (https://discord.com/channels/310555209753690112/1125299494066597888/1284472586960502784):
image
image

## Technical details
YAML editing lmao.

## Media

Content Client_0Nt8TFKLHS
Content Client_1IiGtGz7Am

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The binary translator key in the syndie uplink is now correctly marked as syndicate contraband.

### CODE REVIEW

**Comment by thebadman4662** [comment]
I wonder, should it be restricted to RD/Sec too? I mean, on same grounds as sec listening on syndicate frequencies should they get their hands on their encryptions.

**Comment by slarticodefast** [comment]
Best make it two separate prototypes, one for the uplink using the new sprite and syndicate contraband, and keep the old one as it was in case we decide to re-add it or an admin needs it for an event.

**Comment by ArtisticRoomba** [comment]
Done.

**Comment by ArtisticRoomba** [comment]
> I wonder, should it be restricted to RD/Sec too? I mean, on same grounds as sec listening on syndicate frequencies should they get their hands on their encryptions.
Not sure. This is more of a maintainer meeting topic if it wants to be discussed further. The reason why I made this PR is because we already got admin approval to do this.

**Comment by slarticodefast** [comment]
The preview icon in the uplink seems to have the crypt layer missing. Not sure if that was a bug before already, but could you fix that as well?
grafik

**Comment by ArtisticRoomba** [comment]
Yep, I looked to see if I could just YAML fix it but it requires more in the relevant code. I might poke at it a bit in another PR if nobody else touches it. Thanks :)

**Pull request merged**
