### PR TITLE
Borgs

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## cooltext440996876972059

Based on the [legendary design doc](https://docs.spacestation14.io/en/design/silicons).

## Major Changes
Adds:
- 6 new borg chassis
- 23 new modules to mix and match
- MMIs and Positronic brains as ways to bring back players from the dead.
- adds silicon laws that borgs must follow (default crewsimov for station)
- added a custom law 0 that appears when borgs are emagged.

## Minor Changes
- PAI system got super generic in order to support posi brains
- battery chargers now support all types of containers
- hands system now orders hands correctly on the client
- allows repairable entities to be disallowed from repairing themselves
- adds an event for getting access on entities
- adds a generic part assembly system that should be used for building mechs in the future.

**Media**

image
image
image
image
image
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added cyborgs. These creations are assembled part by part and can be loaded up with various modules to give them unique abilities. Make sure you charge them at their dedicated charging stations.
- add: Added silicon laws. These are laws that all robotic crew must abide by. This Asimov guy had the right idea.
- add: Added new Mechanized Treatment and Robotic Cleanliness technologies.
- add: The EMAG is now able to force cyborgs to follow your orders. How devious!

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Did you add dogborgs too

**Comment by EmoGarbage404** [comment]
> Did you add dogborgs too

you came all the way up into my heavenly light simply to drag me back down to hell

**Comment by fidso** [comment]
BASED.

**Comment by Mudsson** [comment]
How is a crew members defined by the default law set shown, is it anyone on the crew manifest? How does this relate to antagonists like syndicates or zombies. If a zombie is on the manifesto is it a crewmember?

**Comment by Emisse** [comment]
if they are on the crew manifest they are crew

**Comment by Mudsson** [comment]
> if they are on the crew manifest they are crew

Do zombies and other conversion antagonists still have them count as on the manifest?

**Comment by Emisse** [comment]
yes

**Comment by lzk228** [comment]
i wanna I.A.N.

**Comment by DEATHB4DEFEAT** [comment]
damn

**Comment by Flareguy** [comment]
CL should probably refer to them as "cyborgs" instead of "borgs"

**Comment by JoeHammad1844** [comment]
syndieborg

**Comment by deltanedas** [comment]
IM NOT MALF

**Comment by Xeno4** [comment]
add syndieborgs. do it. right now.

**Comment by dmnct** [comment]
If a traitor has a kill objective, will they additionally have to get rid of/destroy the brain after gibbing the body, or does a cyborg not count as the same person for objectives?

**Comment by SEMoslaw** [comment]
This is awesome great work :D

**Comment by noverd** [comment]
can i help with it PR?

**Comment by EmoGarbage404** [comment]
> can i help with it PR?

it's alright. i'm more of a solo dev kind of gal.

**Comment by VektorZ1** [comment]
Clown borg is the best thing ever.

**Comment by JoeHammad1844** [comment]
I think antagonists such as nukies and zombies should count as non-human

**Comment by JoeHammad1844** [comment]
but syndicate agents should still count as human

**Comment by FacePluslll** [comment]
> I think antagonists such as nukies and zombies should count as non-human

if the laws are bound to crew manifest (which most likely will be), nukies won't count towards crew. Anything else will require a law change so borgs could assist in crew defensive efforts assuming the law wont backfire. Besides law 1 will still greatly hinder any antag tom foolery anyways.

**Comment by ThunderBear2006** [comment]
> How is a crew members defined by the default law set shown, is it anyone on the crew manifest? How does this relate to antagonists like syndicates or zombies. If a zombie is on the manifesto is it a crewmember?

I'm pretty sure on the TG fork the laws say "humans" since nanotrasen is racist I guess, it would make it easier to put it that way since a zombie isn't technically a human, I'm not sure how that would work with nukies but since most nukies already shoot everything they see I don't think a borg would try to help them since they cause/threaten human harm

**Comment by JoeHammad1844** [comment]
> > How is a crew members defined by the default law set shown, is it anyone on the crew manifest? How does this relate to antagonists like syndicates or zombies. If a zombie is on the manifesto is it a crewmember?
> 
> I'm pretty sure on the TG fork the laws say "humans" since nanotrasen is racist I guess, it would make it easier to put it that way since a zombie isn't technically a human, I'm not sure how that would work with nukies but since most nukies already shoot everything they see I don't think a borg would try to help them since they cause/threaten human harm

lizards also count as humans on TG

**Comment by KashRas2** [comment]
Holy fuck you made it

**Comment by deltanedas** [comment]
real

**Comment by lzk228** [comment]
roboticist role?

**Comment by Aisu9** [comment]
roundstart borg jobs?

**Comment by LankLTE** [comment]
borgs jobs have to be mapped so... whenever mappers get to it

**Pull request merged**
