### PR TITLE
New pinpointer sprites

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Solves #22432 and provides two new sprites for nukie pinpointers and ninja pinpointers, while the universal pinpointer utilises an unused sprite in the files.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Ninja:**

image

**Nukie:**

image

**Changelog**

:cl: Ubaser
- add: Ninjas and Nukies now get new sprites for their pinpointers.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
awesome

**Comment by UbaserB** [comment]
yay i fixed it

**Comment by JoeHammad1844** [comment]
#22435
he did not fix it :trollface:

**Comment by UbaserB** [comment]
> #22435 he did not fix it :trollface:

i posted a new issue for it since its being dumb and i cant fix it

**Pull request merged**
