### PR TITLE
Job title localization

### LINKED ISSUE #28791: JobTitle field in IdCardComponent should support locale strings
for localizing ert id cards

### PR DESCRIPTION
**Pull request by chavonadelal**
## About the PR

localizing job title. Replaced all uses of JobTitle with LocalizedJobTitle.

Fixes #28791
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: to4no_fix

### CODE REVIEW

**Comment by beck-thompson** [comment]
Strongest localization warrior 💪 💪 💪

**Comment by chavonadelal** [comment]
> Strongest localization warrior 💪 💪 💪

Start your day with game localization! 🥤

**Comment by chavonadelal** [comment]
Everything is fixed and working

**Comment by lzk228** [comment]
fixes https://github.com/space-wizards/space-station-14/issues/28791

**Review by SlamBamActionman — APPROVED** [review]
Code looks good, tests good. Needs another maintainer's approval to merge, as according to the review guidelines.

**Pull request merged**
