### PR TITLE
Dataset names purge

### PR DESCRIPTION
**Pull request by Peptide90**
More copyright purge with a side of slur purge from the names datasets. Feel free to skim over the remaining ones and suggest further removals as I'm not all knowing on every subject and the few that I did google that remain seem fairly innocuous (and left the odd ambiguous one that is meaningless without the other names for context).

### CODE REVIEW

**Comment by Elijahrane** [comment]
AM is from a copyrighted work, I think that one and Data are probably so generic as to be fine though

**Comment by Elijahrane** [comment]
I don't get Postal as a name for a robot having anything to do with the IP, that one is probably fine

**Comment by Elijahrane** [comment]
Thomas Paine died 200 years ago so I think we're safe

**Comment by Acruid** [comment]
Are there any guidelines on how you decided which names to keep, because there are still a large amount of names referencing characters from copyrighted works.

**Comment by Peptide90** [comment]
> Thomas Paine died 200 years ago so I think we're safe

Also removed as many real life names as possible. And which one is AM?

**Comment by Elijahrane** [comment]
Zero is a number
Ryu is a common Japanese name (and I can think of dozens of people real and fictional with it)
Raiden is the name of a God

ED-209 is from Robocop

**Comment by Peptide90** [comment]
Holograms got nuked so just put some very generic names in for now of mythology + hologramy things. Whoever implements holograms can do their own pass.

AI also needed mostly gutted so tried to add some fake acronym stuff in, changed a few to be not related to anything and generally gutted anything that referenced any other material (goodbye pop culture for now). Also added one or two SS14 related ones

**Pull request merged**
