### PR TITLE
New Game Map: Reach Transport Shuttle

### PR DESCRIPTION
**Pull request by LittleBuilderJane**
## About the PR 
Mapped SS Reach, needs piping and Atmospherics furnished.
**Screenshots**

Reach Screenshot
**Changelog**

:cl: Schiene
- add: Added Shuttle SS Reach, atmospherics not included yet.

### CODE REVIEW

**Comment by DogZeroX** [comment]
There's no need to add a remove changelog, when you're removing nothing, nerd.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
You added another config which shouldn't be there, and also touched the sln

**Comment by LittleBuilderJane** [comment]
> You added another config which shouldn't be there, and also touched the sln. Also, the changelog shows up in game so remove the "remove" entry please

**Review by LittleBuilderJane — COMMENTED** [review]
I am going to delet myself, it put all this stuff here again that wasn't meant to be here, I don't know why, but I will do the same thing I did last time to remove this shit from here.

**Comment by LittleBuilderJane** [comment]
I reverted back a few commits, now it's definitely just the map and it's game.yml. (I've taken the liberty of updating the game.yml so it has the Warden slots in it so it doesn't have to be adjusted as well.)

**Comment by LittleBuilderJane** [comment]
> I reverted back a few commits, now it's definitely just the map and it's game.yml. (I've taken the liberty of updating the game.yml so it has the Warden slots in it so it doesn't have to be adjusted as well.)

Now we're good, everything is good and ready, double-checked. Just need someone to do the Atmospherics once pushed in.

**Review by moonheart08 — APPROVED** [review]

**Comment by SweptWasTaken** [comment]
Any screenshots?

**Comment by LittleBuilderJane** [comment]
> 

Didn't know how to do one when I posted it, but thank you for the reminder, I will do that right now.

**Review by PaulRitter — CHANGES_REQUESTED** [review]
super cool map imo.

- janitor closet needs its lights to be powered
- the hallway outside the janitors closet also needs lights
- cargo department lights seem to be broken
- i'd also bump cargo tech down to 1 max
- i dont like the armory being accessible from the hallway. why not cut off the hallway more up the line, creating some sort of "lobby" for command & sec (see pic, either option 1 or two should be fine, but feel free to come up with your own)
grafik

all in all, i really like the combination of cramped & spacious spaces in this map, super cool!

**Comment by LittleBuilderJane** [comment]
> super cool map imo.
> 
> * janitor closet needs its lights to be powered
> * the hallway outside the janitors closet also needs lights
> * cargo department lights seem to be broken
> * i'd also bump cargo tech down to 1 max
> * i dont like the armory being accessible from the hallway. why not cut off the hallway more up the line, creating some sort of "lobby" for command & sec (see pic, either option 1 or two should be fine, but feel free to come up with your own)
>   grafik
> 
> all in all, i really like the combination of cramped & spacious spaces in this map, super cool!

Lights have been fixed for the first three points and I bumped down the Cargo tech. Security now has a lobby area through the second suggested line, and the Maintenance door is now Engineering locked. Why Engi ? Because it's more secure than Maint access and Engineers need to have access to that hallway.

**Review by PaulRitter — APPROVED** [review]

**Comment by PaulRitter** [comment]
ideally i'd make the main have sec access but its up to you really

**Comment by SweptWasTaken** [comment]
Those glass floors look cool but I didn't intend for people to really build with them like that, they're waiting for tiles to finally be overhauled so we can have smooth tiles.

**Pull request merged**
