### PR TITLE
Juiceable slimeballs

### PR DESCRIPTION
**Pull request by luizwritescode**
## About the PR

Adds extractable component to slimeball prototype.

Now slimeballs can be juiced for 10u slime instead of just grinded for nutriment.

I'm sure there are more items that could be juiced but slimeball always confused me.
## Why / Balance

Slimeball is a child of FoodMeat prototype. You can get protein and nutriment from it but, weirdly, no slime.

This allows to extract slime from the item without removing the original recipe, in turn adding one more blender interaction to the game.
## Technical details

N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None

**Changelog**

Such a small change does it really need cl entry?

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]
Looks good to me 👍

**Comment by thebadman4662** [comment]
Always assumed slimeballs are not juiceable and in ball form in first place because they are condensed and basically dry nutriments(266% nutrition compared to slime) while all that slime otherwise is still nutritious but spills and satiates thirst due to water content you can get out in electrolyze.

**Comment by luizwritescode** [comment]
> Always assumed slimeballs are not juiceable and in ball form in first place because they are condensed and basically dry nutriments

Slimeballs are for slimes what meat is for humans so having nutriment makes sense, but a 'slime'ball not having slime is a bit weird. In practice all this PR really does is allow kitchen to make more slime-based food.

**Comment by chromiumboy** [comment]
Sure, why not?

**Pull request merged**
