### PR TITLE
Add mothroach

### PR DESCRIPTION
**Pull request by Fromoriss**
Simple mob, like a mouse, but moth was added! Enjoy it!

## About the PR
Now the game will have cute fluffy mothroaches.

## Why / Balance
I love moths, both it and anthro. I LOVE IT!

## Technical details
IDK about speed and speech. I can make speed slower if it is too fast. And... I think speech is a good trick, but if not.. I can replace it with mice squik.

## Media

https://github.com/space-wizards/space-station-14/assets/106442259/0a6658b3-5378-49b4-bfb6-368eb9a5a2e2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase.

Changelog
:cl: Fromoriss
- add: Added mothroaches! This fluffy creature will live on the same station with you!

### CODE REVIEW

**Comment by deltanedas** [comment]
https://github.com/space-wizards/space-station-14/pull/19752 already did it and imo better

**Comment by Fromoriss** [comment]
:(

**Comment by deltanedas** [comment]
yes it has mothroach too

**Comment by Fromoriss** [comment]
Okay, so I'm closing it. ||Oh, no, I've been struggling with this all evening...||

**Comment by Fromoriss** [comment]
I want to reopen it... Maybe it is not bad and somebody will merge it...

**Comment by Fromoriss** [comment]
I will try to fix it...

**Comment by UbaserB** [comment]
I want to wear mothroaches on my head

**Comment by Fromoriss** [comment]
CL for last commit: fixed all errors, it can be worn on head and some other tweaks

**Comment by Fromoriss** [comment]
How should I pray to God that this will be merged?

**Comment by Fromoriss** [comment]
5844-boykisser

**Comment by Fromoriss** [comment]
Bruh, now i resolved all. It's passed. Merge?

**Comment by mirrorcult** [comment]
#19752 was merged, are there any changes you want to make to the mothroaches from that branch or should this just be closed

**Comment by Fromoriss** [comment]
All perfect

**Pull request closed without merging**
