### PR TITLE
UpdateSpriteToyShark

### PR DESCRIPTION
**Pull request by 21Melkuu**
## About the PR

Changes the sprites of the shark toy. The character now "hugs" her, from TG.
## Why / Balance

I think this option looks much better.
## Media

screan

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: 21Melkuu
- tweak: sprites toy shark.

### CODE REVIEW

**Comment by UbaserB** [comment]
thats a lot of hueshifting

**Comment by FairlySadPanda** [comment]
The shonk is based off of https://www.ikea.com/gb/en/p/blahaj-soft-toy-shark-30373588/ so its colours need to be based on that, and its overall design needs to be readable as that shonk

This is a decent idea but needs to be more tightly referenced.

**Comment by FairlySadPanda** [comment]
I would advise buying a shonk for reference

they are soft and warm and good for the hugging

**Comment by 21Melkuu** [comment]
> and its overall design needs to be readable as that shonk

Yes, the color should be returned to the old one. I don’t quite understand about the design, but everything seems to be clearly visible?

**Comment by Psychpsyo** [comment]
image
Why does he look like he's in pain?

**Comment by Emisse** [comment]
doesnt match our style im afraid

**Comment by metalgearsloth** [comment]
art-tainer has spoken.

**Pull request closed without merging**
