### PR TITLE
Bump operative reinforcement cost

### PR DESCRIPTION
**Pull request by metalgearsloth**
See https://github.com/tgstation/tgstation/blob/838742297ee2cd692362c42b8bccde8a5e307376/code/modules/uplink/uplink_items/nukeops.dm for tg values

Few issues:
1. I wanted to make borgs cheaper but we don't have as many tools to deal with borgs as in 13 so I left that higher for now until they're more fleshed out and we can balance them better (though they can be super squishy in some situations which is eh).
2. Operatives seem to be getting used frequently as they're easy to arm up and bump nukie numbers where they might've been 3-5 to 5-8.

:cl:
tweak: Bumped nukie operative cost from 16 to 35TC.

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
Woah that's a massive bump. You practically cant get them unless you warops.

**Comment by Dutch-VanDerLinde** [comment]
changelog said 14 but the price is 16

**Comment by metalgearsloth** [comment]
> Woah that's a massive bump. You practically cant get them unless you warops.
> 
> Doesn't TG also have TC earning mechanics?

no idea but considering mechs go up to 100TC seems fine to me.

**Comment by Brandon-Huu** [comment]
This is awful.
35 TC for a suicide bomber

**Comment by metalgearsloth** [comment]
Better PR https://github.com/space-wizards/space-station-14/pull/29557

**Pull request closed without merging**
