### PR TITLE
Vox sign/N2 locker update

### LINKED ISSUE #31840: vox area sign has obvious parallels to real world discriminatory language and signage. Should consider change or removal.
## Description
The wall mount sign "voxcrossing.png" labeled in game as "vox area sign" has several reasons to be changed or removed.

\SS14\Resources\Textures\Structures\Wallmounts\signs.rsi\voxcross.png

Most obviously, it parallels discriminatory treatment, language, and signage in the United States. In particular, the name, "vox area sign" is egregiously similar. The notion that signs need to be put up to indicate where certain species should or could go is an issue in itself. The stations, while not equally accessible to all, should at least avoid language and signage that organizes space by species. "voxcrossing.png" is a dehumanizing name as well, which could be interpreted to indicate that vox are animals or should be treated as animals.

Additionally, the sign is meant to indicate an area of exclusively N2 atmosphere, which is already easily accomplished with atmos_n2.png labeled in game as "N2 warning sign". The addition of a sign to indicate a space for vox is inferior at communicating, especially to new players, that the area has a different atmosphere composition.

There are no "area signs" equivalent for any other species, and they would be unnecessary in almost all cases. Singling the vox out as both different and to be treated different. Signs should indicate what is different about an area not who should go there.

Voxboxes as they've come to be called are also expected to be tacked on to the station as an afterthought, indicating NT did not plan for N2 breathing species. Having signage specifically for them changes the implication from "lacking in planning" to "intentionally inferior", at least to me.

**Additional context**
I could add example of signs that might better explain why I have created this issue, but I think most have seen them. If necessary, I will add them later at request.

I am no expert at communicating on such sensitive matters, but I felt this issue should be brought up immediately. If my wording or format is lacking in some way, please let me know and I apologize ahead of time.

### PR DESCRIPTION
**Pull request by PJB3005**
The "vox area" sign and N2 locker sprite were both taken from /vg/station. These sprites have bad racist connotations as discussed in https://github.com/space-wizards/space-station-14/issues/31840, and do not fit our server culture.

The new N2 locker is not a taped on piece of trash. It now also has a blue stripe to mimic the regular O2 locker and make it more distinct from fire safety closets.

The new "vox area" sign sprite follows the same style as other "area indicator" signs used throughout the blue and isn't an explicit warning sign anymore. It still has "No O2" on it to fill that role though.

Fixes #31840

:cl:
- tweak: Changed the sprites for the N2 locker and "vox area" sign.

### CODE REVIEW

**Comment by PJB3005** [comment]
Content Client_4oPd4JSL9d

In-game of the sprite. emo is going to push a better sprite for the locker.

**Comment by EmoGarbage404** [comment]
image

white stripe on locker and slightly adjusted kerning on vox area sign

**Comment by Golinth** [comment]
Aw I am gonna miss the N2 locker sprite. I thought it was pretty funny when it was first PR'd, especially since they are meant to be used sparingly.

**Comment by lzk228** [comment]
"NO O2" can mean a lot of things, that's why specifying the gas (N2) is good

**Comment by PJB3005** [comment]
> I dunno about the vox sign considering slimepeople can also use them

We don't label accessibility parking spaces as "wider parking space with closest access to the building" on signs, we label them with (one of) the groups of people that *need* them (wheelchair).

"Other species can also use the space" does not detract from the fact that:
1. These map elements are specifically being added for the Vox species.
2. Other species (i.e. specifically slimes) have no *hard need* to use them like Vox do[^1].

Indicating the group of people that they are intended gets the message across far more clearly. This is getting into lore territory but imagine if you're a Vox that doesn't know space English. A sign with a Vox on it is far more clear than "N2 area" or anything less specific like that. This is standard indicator design done in the real world.

[^1]: I'm going to be honest, I think the implementation of "Vox boxes" as I've seen it on some maps is just terrible garbage and another indicator of terrible game quality standards. I would rather just have Vox be able to breathe oxygen for 10 seconds without permanent damage than force them to go to this shithole Nanotrasen repurposes in the fucking laundry room, if they want to eat without having to go to take 1u dylovene afterwards.

**Pull request merged**
