### PR TITLE
Guidebook Update [1/Possibly Many]

### PR DESCRIPTION
**Pull request by Terraspark4941**
## About the PR

Cleaned up the ENTIRE guidebook, now it should be far easier to read and factually accurate (for the most part).
Some features are still missing from the guidebook (Door Hacking, Exp. Anomaly Vessel, Chemical Botany, etc.), so this will remain as a draft until implemented.

My contribution to #13506
## Why / Balance

Nukies are red
Holocarps are blue
I hated reading the old guidebook
And you should hate reading it too (/hj)

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## TODO:
In this PR:
- [X] Fix every grammatical error in the guidebook
- [x] Fix every current factual error in the guidebook
- [X] Implement proper information about the TEG in the guidebook
- [x] Prettyprint the TEG page with entities instead of plaintext
- [x] Make a note about jug chems
- [x] Add extra details about the A.P.E and C.H.I.M.P (maybe give the acronym a real full form?)
- [ ] Add details regarding the Anomaly Synchronizer
- [ ] Change/Implement the (Experimental) Anomaly Vessel page
- [ ] Add details regarding the Artifact Crusher
- [ ] ~Explain how to setup cloning properly~ Cloning is _probably_ going to be removed, so no

In future PRs (ordered by most likely to occur):
- [ ] Change all occurrences of 'Viva la revolución'  to 'Viva la révolution' due to popularity of the latter (only here because of the Revs guidebook entry)
- [ ] Implement a Door hacking page
- [ ] Implement a Chemical Botany details page
- [ ] Explain access levels
- [ ] Add guides to all of command, since basically nowhere is there discrete info about how to command

**Changelog**

:cl:
- fix: Nanotrasen has _finally_ revised their guidebook! Every guidebook page has been spell-checked, fact-checked and updated to modern standards.

### CODE REVIEW

**Comment by Terraspark4941** [comment]
If anyone wishes to add more info that should be in the guidebook but isn't, leave a comment and I'll consider it.

**Comment by EmoGarbage404** [comment]
additional articles should be moved to separate PRs

**Comment by mirrorcult** [comment]
please split this into separate PRs or this is going to be a nightmare to get merged

**Review by mirrorcult — CHANGES_REQUESTED** [review]
above

**Review by Terraspark4941 — COMMENTED** [review]
how much should i split it into? every section (folder) of the guidebook is its own PR?
and if so, should i just revert everything (remote only) and start making new PRs?

**Comment by mirrorcult** [comment]
at the very least each section into its own PR

**Comment by Terraspark4941** [comment]
closing until i can return to this, too many changes to manage with my busy schedule (and lazy ahh) + much new redesigns on the horizon
i will split every department into a seperate PR as stated when the time comes

**Pull request closed without merging**
