### PR TITLE
Station "Reach" changes

### PR DESCRIPTION
**Pull request by Kukutis96513**
## About the PR

- Botany now has a nutrimax and is slightly bigger.
- The station now has an actual waste network
## Why / Balance

- You can't do botany without botany tools, so that's why i added a nutrimax
- No waste system means everything dies after afew hours which is annoying.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Screenshot_1192
bigger botany with a nutrimax included

**Changelog**

no cl because it's a mapping change

### CODE REVIEW

**Comment by Kukutis96513** [comment]
fixes #29613 i think

**Comment by lzk228** [comment]
would be good to map a fax

**Comment by Tayrtahn** [comment]
Test failure is real

**Comment by Kukutis96513** [comment]
> Test failure is real 

Screenshot_1223

i just checked the map file and it didnt have anything with uid 0. any idea what could be causing this?

**Comment by SlamBamActionman** [comment]
> > Test failure is real 
> 
> Screenshot_1223
> 
> i just checked the map file and it didnt have anything with uid 0. any idea what could be causing this?

I think this can also happen if an item is trying to reference a uid that has been deleted. An example of this could be linking a conveyor belt to a lever and then removing the conveyor belt. Sometimes the lever fails to remove the link on its end and it stays there invisibly in the map file, causing the error.

**Comment by Emisse** [comment]
you need to remove invalids from map file

**Comment by Kukutis96513** [comment]
aaa merge conflict.. i'll deal with it

**Comment by Kukutis96513** [comment]
somehow messed up stuff with robusttoolbox aaaa

**Comment by Kukutis96513** [comment]
trying with a second PR

**Pull request closed without merging**
