### PR TITLE
Remove instruments compref

### PR DESCRIPTION
**Pull request by metalgearsloth**
Didn't check ingame yet swapped branches so lemme do that before merg

### CODE REVIEW

**Comment by deltanedas** [comment]
cant you put all the fields in shared and use auto state as before

**Comment by metalgearsloth** [comment]
> cant you put all the fields in shared and use auto state as before

Would require many more changes around ActivatableUIComponent etc and I mainly want to get arch sorted.

**Comment by deltanedas** [comment]
also is that not just resolve false

**Comment by metalgearsloth** [comment]
> also is that not just resolve false

Resolve yourself

**Review by DrSmugleaf — CHANGES_REQUESTED** [review]
Is this going to work with networking since the types are different now?

**Comment by metalgearsloth** [comment]
> Is this going to work with networking since the types are different now?

chur

**Pull request merged**
