### PR TITLE
New chef jumpsuit variant

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

I wanted to add a new clothing sprite so i decided to add a variant to chef; basically the current one with a small tweak and full-on darkmode. You'd typically barely see it anyway, and since its grey greytiders might like to take it from the chef for drip :3

It's literally just semi-casual clothing so i called it chef loungewear.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- add: There is now a new chef jumpsuit variant available in the ChefDrobe!

### CODE REVIEW

**Comment by potato1234x** [comment]
this really doesnt look like the chef at all

**Comment by UbaserB** [comment]
It was originally not going to be chef, but when i posted it literally every assumed it was going to be a chef uniform so i just made it so

**Comment by UbaserB** [comment]
I love breaking github whenever i try fixing stuff :)
for some reason it affected the engine so i need to fix this guh

**Comment by UbaserB** [comment]
OH MY GOD WHAT DID THIS DO EVERYTHING IS BROKEN

**Comment by UbaserB** [comment]
IM SO SORRY LET ME JUST DELETE THIS RFIGUEWGRIUEVR

**Pull request closed without merging**
