### PR TITLE
[Remove] Removes space lube from vents

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

It's just super annoying.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Due to numerous complaints, Centcom has removed space lube from the ventilation system.

### CODE REVIEW

**Comment by mirrorcult** [comment]
yeah its supposed to be annoying?

**Comment by OctoRocket** [comment]
On multiple occasions I have played on servers where the lube was so intrusive that they just called the resupply shuttle.

**Comment by HoidC** [comment]
It’d be fine if it wasn’t 3 or 4 gigantic puddles every single time the event happened 

maybe just drop the chance of lube being a chemical instead?

**Comment by asperger-sind** [comment]
> yeah its supposed to be annoying?

It's basically impossible to clean with current janitor as it spawns like 10 GIANT puddles of space lube that end up being more than the total amount of water you have on-board, so you have to sit through like 30 minutes of janitor """gameplay""" to get rid of this whilst nagging cargo for water tanks.

**Comment by metalgearsloth** [comment]
> > yeah its supposed to be annoying?
> 
> It's basically impossible to clean with current janitor as it spawns like 10 GIANT puddles of space lube that end up being more than the total amount of water you have on-board, so you have to sit through like 30 minutes of janitor """gameplay""" to get rid of this whilst nagging cargo for water tanks.

isn't that a janitor issue

**Comment by deltanedas** [comment]
the lube puddles should just be like 1-2 tiles radius so its not a complete nightmare to try and clean

**Comment by OctoRocket** [comment]
> isn't that a janitor issue

Maybe, but filling the whole of security and more with lube is unreasonable. The puddle size for all the other vent clog substances is fine but for space lube specifically it is way too much.

**Comment by keronshb** [comment]
This is part of the classic ss13 fun, so I don't really see the point of this.

**Comment by OctoRocket** [comment]
It is just really unfun on low pop servers without multiple janitors, and sometime with no janitors at all.

**Comment by keronshb** [comment]
> It is just really unfun on low pop servers without multiple janitors, and sometime with no janitors at all.

I don't feel that's a good enough reason to remove it. You can just grab a mop yourself and clean it up no?

**Comment by HoidC** [comment]
> > It is just really unfun on low pop servers without multiple janitors, and sometime with no janitors at all.
> 
> I don't feel that's a good enough reason to remove it. You can just grab a mop yourself and clean it up no?

not exactly feasible to clean it up with a mop yourself considering

a) how gigantic the puddles are 
b) how long each individual puddle tile takes to mop up

**Comment by OctoRocket** [comment]
It takes even longer considering that you are slipping and dropping the mop all the time.

**Comment by Scribbles0** [comment]
[15626] might've helped deal with the issue at hand, due to puddles never overflowing to water puddles now (and other various QoL tweaks)

**Comment by OctoRocket** [comment]
I had issues with it yesterday on sala so I don't think it did much.

**Comment by Scribbles0** [comment]
> I had issues with it yesterday on sala so I don't think it did much.

it was only merged 10 hours ago (aka the improvements only took effect today)

**Comment by Interrobang01** [comment]
I think the issue of space lube being really annoying is a problem, but I don't think this is the solution.

Maybe add a super-specific counter, like an anti-puddle janitor bomb, or just make lube easier to clean by making the max puddle reagent capacity for lube lower or something.

**Comment by OctoRocket** [comment]
I think the issue might be that there is way too much liquid coming out of everything.

**Comment by potato1234x** [comment]
making lube easier to clean would be a better solution

**Comment by OctoRocket** [comment]
As this is not the best way to fix this issue, I will be closing this PR

**Pull request closed without merging**
