### PR TITLE
Brigmed Jumpsuit sprite improvements

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

Updates Brigmed Jumpsuit and skirt to add more red parts

## Why / Balance

Brigmed jumpsuit was boring and hard to set apart from medical staff on the battlefield 

## Media

Screenshot 2024-05-07 213710

## Breaking changes

**Changelog**

🆑 
  - update brigmed jumpsuit and jumpskirt sprite

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
I like it, I always thought the brigmed clothing did not make much sense. The bottom of the jumpskirt blends in with the floor a bit...

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
currently it looks like an off-white jumpsuit when you are wearing a backpack or something, giving it some red would be a good way to help tell it apart from a tider with drip AND would bring it more in line with the armored medical gown.

**Comment by mirrorcult** [comment]
are these even used

**Comment by Dutch-VanDerLinde** [comment]
they are printable at the uniform printer

**Comment by EmoGarbage404** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Pull request closed without merging**
