### PR TITLE
Chemistry 1984

### PR DESCRIPTION
**Pull request by Veritius**
## About the PR
- Nerfs the Chemical Dispenser by adding a point score mechanic
- Allows basic chems to be purchasable from Cargo

**This PR isn't finished. Other sources for chems need to be created. Like organic materials from botany, metals from salvage, and gases from atmospherics.**

The intent here is making Chemistry and Science have to actually leave their department for resources multiple times over the course of the round, rather than stealing a water and fuel tank then never leaving their department ever again. Additionally, this makes chemistry much more tactile, instead of button clicking simulator 2022. People also have to justify why they need radium and various other extremely toxic chemicals, instead of just magically having it on hand.

The chemistry dispenser is still functional, but issignificantly reduced in capability. This won't apply to the bar dispensers, and can also be changed in the prototype.

**Screenshots**

**Changelog**

:cl:
- add: Basic chems can be bought from Cargo in bulk.
- tweak: The Chemistry Dispenser now has a cooldown.

### CODE REVIEW

**Comment by Veritius** [comment]
whoops that was meant to be a draft

**Comment by Elijahrane** [comment]
based although maybe you should make the crates by group rather than invididual

**Comment by Ablankmann** [comment]
Based, although I personally don't like the idea of forcing Chemists to have to go to cargo every time they want to make something, mainly because all you have to do to completely stop them is to destroy the cargo shuttle console
screw sci though, #ripbozos

**Comment by mirrorcult** [comment]
individual crates+tanks is a bit much

**Comment by mirrorcult** [comment]
overall fine idea though will give my full thoughts and improvement ideas later

**Comment by moonheart08** [comment]
Definitely needs to be groups of chems.

**Comment by mirrorcult** [comment]
no

**Comment by HoidC** [comment]
good in concept but I feel in practise making one department (or subdivision, but chemistry is most of medbay at this stage) literally entirely reliant on another (which is easily sabotaged at that) isn't a great idea + having to order separate bundles of everything to drag it all down to cargo is an L

idk

**Comment by mirrorcult** [comment]
this is a draft PR for a reason

**Comment by mirrorcult** [comment]
if you want actual design discussion go to discord

**Comment by Just-a-Unity-Dev** [comment]
why not a vending machine with limited chemicals and then if you want more you can go to cargo?

> Getting plasma sheets on Barratry for DexalinPlus is already incredibly inconsistent. Shutting down non-clone part of medbay with this... does not look like good idea to me.

**Comment by Veritius** [comment]
> good in concept but I feel in practise making one department (or subdivision, but chemistry is most of medbay at this stage) literally entirely reliant on another (which is easily sabotaged at that) isn't a great idea + having to order separate bundles of everything to drag it all down to cargo is an L

There'll be other sources for all chems. This is just temporary.

**Comment by metalgearsloth** [comment]
I'm fine with the concept (assuming the code is fixed) but you need to fix cargo economy if you want these to be purchaseable because there is not enough income on the station atm.

**Comment by mirrorcult** [comment]
otay

**Comment by metalgearsloth** [comment]
Re-open when it's ready for review

**Pull request closed without merging**
