### PR TITLE
Removes warp point from map beacons

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Title

## Why / Balance
Makes things much cleaner. Currently we have Warp Point markers, Bombing Targets, and Map Beacons all with an overlapping function. (Also Warp points+Beacons markers but I'm ignoring those for this.)

**Why it's messy** 
Standard warp points and bombing targets can be used interchangeably.  You can use a WP where you don't want a target, use a BT where you do. Beacons, on the other hand, don't have BT but double up as a WP. So, you either end up having to choose between a BT/WP or a beacon, or double up a location on the Ghost Warp menu. Additionally, just using beacons bloats the Warp Menu.

Beacons can be moved by players. So, attaching either WP or BT to those is bad. Beacons are really nice, both for mappers and players but as long as they have WP, it causes conflict for mappers and/or bloat in the Ghost Warp menu.

**Solution**
Just use WP and BT to fill the Ghost Warp menu and Beacons for the Navmap. Problem solved/potential griefing, issues, etc. avoided, and no more Warp Menu bloat.
 
## Technical details
Some maps will likely need to be adjusted for this change.

## Media
n/a
- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**
n/a

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Beacons are meant to specifically reduce the overhead of having to place and name warp points. They're more consistent and numerous on maps than warp points ever were. They're moveable and can be modified, but that's part of the strength. Realistically, they don't get moved around much during a game and serve as good markers for where stuff is.

There is a point to be made about the bloat of bombing markers / beacons / warp points, but i would rather all the latter be mostly migrated to beacons rather than be kept as discrete things. Bombing markers aren't even placed on most maps AFAIK and warp points only exist for rare situations like off-station locations.

I hope this clears up why this PR was closed. Thank you for your contribution.

**Comment by deltanedas** [comment]
still should be a way to not have every locker room / bedroom / random thing having an entry in the warp list but still be visible on the map

alternatively warping to locations could be changed to showing a map ui and click to teleport to somewhere

**Comment by EmoGarbage404** [comment]
> still should be a way to not have every locker room / bedroom / random thing having an entry in the warp list but still be visible on the map
> 
> alternatively warping to locations could be changed to showing a map ui and click to teleport to somewhere

i'd rather go for the combo of disabling warp points via VV and a better warping UI than introducing more markers and overhead for mapping.

**Comment by IamVelcroboy** [comment]
Just a couple points that don't add up for me, 

>They're moveable and can be modified, but that's part of the strength. 

When testing these, I unanchored the arrivals and evac beacons and moved them to different locations on the map, ghosted and warped, not to arrival or evac, but the new location. This just seems problematic and abusable to me. 🤷🏼‍♂️

>Bombing markers aren't even placed on most maps AFAIK

Oh, I guess we went all in on DV. All our maps have multiple bomb markers 😅🥷

**Comment by deltanedas** [comment]
for my maps i rarely use the bombing target prototype but add the bombing target component to an existing beacon or something

**Comment by IamVelcroboy** [comment]
> for my maps i rarely use the bombing target prototype but add the bombing target component to an existing beacon or something

Attaching BT to a warp point is fine but to a beacon is not a good idea since it can be moved by players.

**Pull request closed without merging**
