### PR TITLE
Mindshields can be removed with an implanter

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
Mindshields can be removed with an implanter

Command members get an irremovable one since you're supposed to kill or exile them, security does not though so you can remove their shields

## Why / Balance
there should be a way to convert mindshielded people and i dont think you should be killed because you were mindshielded

also allows head revs to still have somewhat of a chance if most of the crew is mindshielded

## Technical details
added new event ImplantRemovedEvent, raised whenever an implant is removed from someone

## Media
https://cdn.discordapp.com/attachments/561607258337706042/1182400319439777884/me.mp4?ex=65848f1c&is=65721a1c&hm=fc51366f895963ce68f2eeffa11fe78b210ee9fece030c1e945d4832772f8644&
(video is above 10 mb)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
shouldn't be any

**Changelog**
:cl:
- tweak: Mindshields are no longer fused to the body and can be removed with an implanter. Command members, however, get a special mindshield that does fuse.

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
> **Changelog** 🆑
> 
>     * tweak: Mindshields are no longer fused to the body and can be removed with an implanter

This is a lie

**Comment by IProduceWidgets** [comment]
I don't super understand why this needs a second component or system and doesn't just reuse the mindshield component and system. Maybe there's a good reason though and I'm not seeing it.

**Comment by IProduceWidgets** [comment]
Right, but just make the commandmindshield entitiy in yml unremovable, but make it still give the mindshieldComponent.

**Comment by deltanedas** [comment]
add commandmember thing to mindshield blacklist problem solved

**Comment by Brandon-Huu** [comment]
Does removing the implant destroy it in the process?

If not, could this be used to "mind-shield" an entire crew with a single mind shield implant?

**Comment by 27alaing** [comment]
> Does removing the implant destroy it in the process?
> 
> If not, could this be used to "mind-shield" an entire crew with a single mind shield implant?

damn it doesnt, you could do it like that but it would take a lot longer than just ordering more mindshields

**Comment by 27alaing** [comment]
> add commandmember thing to mindshield blacklist problem solved

that would work

**Comment by Dragonjspider** [comment]
> **Changelog** 🆑
> ```
> * tweak: Mindshields are no longer fused to the body and can be removed with an implanter
> ```


Maybe change it to mention that command members have fixed implanters? I can see some people getting confused by it.

**Comment by 27alaing** [comment]
> > **Changelog** 🆑
> > ```
> > * tweak: Mindshields are no longer fused to the body and can be removed with an implanter
> > ```
> 
> Maybe change it to mention that command members still have fused implanters? I can see some people getting confused by it.

yeah sure

**Comment by QuietlyWhisper** [comment]
make sure to add the new perm mindshield to ERT and CentComm roles

**Comment by 27alaing** [comment]
> make sure to add the new perm mindshield to ERT and CentComm roles

ERT and centcomm roles i believe dont get a special implant and inside just get the mindshield component on its own, so basically if you tried to remove the implant nothing would happen as if they had no implants

**Comment by QuietlyWhisper** [comment]
> ERT and centcomm roles i believe dont get a special implant and instead just get the mindshield component on its own, so basically if you tried to remove the implant nothing would happen as if they had no implants

they need to be updated to use the unremovable version in this pr since you're changing the original.

**Comment by Dutch-VanDerLinde** [comment]
fixed conflicts

**Comment by metalgearsloth** [comment]
The whole point of a mindshield / implant is to have something that's unremoveable. If you want it removeable then make it an item (though I also don't think it should be that).

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Pull request closed without merging**
