### PR TITLE
Feat/hdr lights

### PR DESCRIPTION
**Pull request by tom-leys**
## About the PR
- Iterative HDR style exposure control to adjust brightness of scene to keep it consistent
- Night vision is possible, but only powerful for ghosts (in this PR) 
- Game looks really nice

The Brightness is adjusted in this loop:

1. Samples a square (about 32x32 pixels, 1/64 screen size) of the screen where the player is to see how bright the lighting is each frame. (This is done in Robust Client, value stored into Eye)
2. Adjusts "Eye.Exposure" to try to make that square 95% brightness in the lighting system (Client's EyeExposureSystem)
3. Exposure moves between limits say 0.8x -> 4.0x for this PR or 0.8x -> 10.0x for the next PR. The rate is quite slow, esp when increasing exposure
4. Exposure increases the power of all lights and also increases the range of all lights (In Robust Client's lighting system)
5. If exposure goes above a threshold (say 1.3x) a point light begins fading in on the player's location - called "NightVision" (Clientside, in Robust Client)
6. Different characters will initialize EyeComponent with different ranges for exposure, different power of night vision, different nightvision color and different adjustment speed.
7. I've set very powerful good looking settings for this on the Observation Ghost.

Requires: https://github.com/space-wizards/RobustToolbox/pull/4106

**Media**

image

A video showcasing the night vision of a regular human, which is quite mild in this PR. A later PR will make it more powerful and add spider / dwarf etc night vision also.

https://github.com/space-wizards/space-station-14/assets/5285589/7b115825-1b7f-47a4-b7d7-7dbec04fd9e0

image

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Your eyes adjust to the gloom or brightness on the station enough to make the lighting really sparkle
- add: Ghosts can see much better in the dark without having to disable lighting.

### CODE REVIEW

**Comment by deltanedas** [comment]
iirc spawning like 100 suppermatter broke lighting, does hdr fix this

**Comment by tom-leys** [comment]
> iirc spawning like 100 suppermatter broke lighting, does hdr fix this

It darkens bright scenes also, though I've currently limited the effect - we can choose how much darkening is allowed.

**Comment by tom-leys** [comment]
> Is it possible to make the point light on the entity that's used for night vision work as a multiplier so that areas with no light are still not possible to see in? Alternatively making it really small could simulate the situational awareness you'd have from physical contact with stuff. It might not be reasonable because we don't have ambient occlusion, but the goal would be for an unlit box with no way for light to enter to always be pitch black for humans, with ghosts and species that don't rely on light to "see" to get some sort of visibility

That's an option in the "NightVision" class and we can tune it per EyeComponent. If we have no point light on the player, I'd like to see the mapping team add some very dim point lights to the corridors because it looks much nicer to have some light.

**Comment by metalgearsloth** [comment]
> Is it possible to make the point light on the entity that's used for night vision work as a multiplier so that areas with no light are still not possible to see in?

Isn't that just hdr.

**Comment by tom-leys** [comment]
> Is it possible to make the point light on the entity that's used for night vision work as a multiplier

Yes, that is possible, but I wanted an option that DID work in pitch black. We might want to add a multiplicative circle to the lighting as an extra effect.

**Comment by tom-leys** [comment]
> > > Is it possible to make the point light on the entity that's used for night vision work as a multiplier so that areas with no light are still not possible to see in?
> > 
> > 
> > Isn't that just hdr.
> 
> yes but I don't think that's how it works currently, I think the current system adds an actual client side light source on the player that can make something pitch black actually have light

Okay, what this does:

1. Samples a square (about 32x32 pixels, 1/64 screen size) of the screen where the player is to see how bright the lighting is each frame. 
2. Adjusts "Exposure" to try to make that square 95% brightness in the lighting system
3. Exposure moves between limits say 0.8x -> 4.0x for this PR or 0.8x -> 10.0x for the next PR. The rate is quite slow, esp when increasing exposure
4. Exposure increases the power of all lights and also increases the range of all lights
5. If exposure goes above a threshold (say 1.3x) a point light begins fading in on the player's location - called "NightVision"
6. Different characters will initialize EyeComponent with different ranges for exposure, different power of night vision, different nightvision color and different adjustment speed.
7. I've set very powerful good looking settings for this on the Observation Ghost.

**Comment by tom-leys** [comment]
> iirc spawning like 100 suppermatter broke lighting, does hdr fix this

I've added a light limit / compression pass that fixes this. It also makes it look much nicer when an area is overbright.

**Comment by tom-leys** [comment]
Drafting this PR in favor of https://github.com/space-wizards/space-station-14/pull/17114

If that PR causes too much controversy I might update and re-open this one instead.

**Pull request closed without merging**
