### PR TITLE
Revert "Add auto map vote cvar"

### PR DESCRIPTION
**Pull request by metalgearsloth**
Reverts space-wizards/space-station-14#27496

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
> Reverts #27496

Why tho

**Comment by mirrorcult** [comment]
its failing every test on every PR

**Comment by Brandon-Huu** [comment]
Because of this line?
https://github.com/space-wizards/space-station-14/pull/27850
https://github.com/space-wizards/space-station-14/pull/27496/files#diff-632df43e165afe9d6ed83e091ddbcd8a6dbbbd0db2b52ea6543947ab3ccae569R333-R338

**Comment by mirrorcult** [comment]
image

**Comment by Tayrtahn** [comment]
This revert is a good idea as a quick fix to get tests working again, but we also need to address the actual source of the problem. 

From my understanding, the PR in question doesn't have any issues, it just exposed a preexisting issue in a way that CI tests could catch.

Namely, the map vote popup UI plays a sound effect by spawning a clientside entity with an audio source component. The automatic map vote at round end added by the PR is triggering this when recycling a test client/server pair and causing the entity to persist into the next test where it then deletes itself and messes up the entity counting done by that test.

The proper fix then would be for the popup to play its sound effect directly without involving ECS.

Mind you, I haven't actually looked through the code myself, this is just what I've gathered from other people's research (props to @ShadowCommander), so I could be off target.

**Comment by mirrorcult** [comment]
#27871

**Pull request merged**
