### PR TITLE
Atmos sign

### PR DESCRIPTION
**Pull request by Emisse**
Atmos sign
changelog
-atmos sign
image
(atmo sign)

### CODE REVIEW

**Comment by wrexbe** [comment]
I think the license you are listing is incorrect. It looks like it's duel licensed under GPL3, and AGPL3. I think GPL3 is the less restrictive of the two, so you could list that as the license.

For the links, the Beestation github looks like the more official source, so just a link to that commit should work.
https://github.com/discordia-space/CEV-Eris/tree/4e0bbe682d0a00192d24708fdb7031008aa03f18
https://github.com/BeeStation/BeeStation-Hornet/tree/13dd5ac712385642574138f6d7b30eea7c2fab9c

I'm not a lawyer, so I might be wrong, but best effort.

**Comment by mirrorcult** [comment]
bee is a tg downstream which uses CC for its licenses

"All assets including icons and sound are under a [Creative Commons 3.0 BY-SA license](https://creativecommons.org/licenses/by-sa/3.0/) unless otherwise indicated." in their readme

**Comment by wrexbe** [comment]
Then the link should be to wherever that is

**Comment by mirrorcult** [comment]
it is, thats in the beestation readme

**Comment by Emisse** [comment]
im confused as to what i need to change here

**Comment by mirrorcult** [comment]
nothing, your meta is fine

**Comment by wrexbe** [comment]
Yeah, don't worry about it.

**Pull request merged**
