### PR TITLE
Cleanup chairs.yml

### PR DESCRIPTION
**Pull request by MACMAN2003**
not sure if i did this correctly

## About the PR

Cleaned up chairs.yml, now there are four new "base chairs" that all the current chairs and future chairs can derive from instead of copying 90% of another chair
## Why / Balance

both sloth and shued wanted me to do this on a separate PR #24673 but since it's outside the bounds of that PR I made this PR
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no player facing change no cl no fun

### CODE REVIEW

**Comment by TheShuEd** [comment]
image
really strange inheritance structure

**Comment by TheShuEd** [comment]
image
i think we dont need this abstract entity

rotatability, achroring and staticity are parameters that can be combined in many different ways on different types of chairs, so they can be adjusted in the chairs themselves.

**Comment by MACMAN2003** [comment]
> image i think we dont need this abstract entity
> 
> rotatability, achroring and staticity are parameters that can be combined in many different ways on different types of chairs, so they can be adjusted in the chairs themselves.

wouldn't that bring back the problem that this PR is trying to solve?

**Comment by TheShuEd** [comment]
Yeah 🤔

**Pull request merged**
