### PR TITLE
cap drip refactor

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR
Updates the Captain's wardrobe with tgstation outfits, and refreshes the other sprites for the sake of consistency.
Also enables the capcap on hamlet.

**Media**

2023-7-28_18 19 2h1

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Skarlet
- tweak: Changed the Captain's wardrobe with a new default outfit, a new carapace and updates older clothing for the sake of consistency.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
doesnt match the current style as much

**Comment by KaiShibaa** [comment]
I think it matches pretty well with the formal outfit the more I look at it

**Comment by Skarletto** [comment]
the formal outfit was literally made by the same spriter as this hat so idk what you're talking about
image

**Comment by JoeHammad1844** [comment]
pretty sure it isnt, the current style is the old TG style

**Comment by Skarletto** [comment]
oh yeah you are right 
i still think it looks pretty good on it

**Comment by Flareguy** [comment]
These are literally made for a completely different artstyle & clothing set for the captain, this seems like a terrible idea.

**Comment by Skarletto** [comment]
I'll give you that the orange I used for the shading absolutely does not fit and I thank you for making me think more about it
Did some digging and looks like there is a very similar hat to the one i PR'd that came along the formal clothing we currently use and looks more in line with our 'current style', I can just use that one
https://github.com/tgstation/tgstation/pull/60414

**Comment by Emisse** [comment]
can you standardize all the gold on our captain gear to match the gold on the carapace/formal cloak we currently have

**Comment by Skarletto** [comment]
I can definitely do that

**Comment by JoeHammad1844** [comment]
these are from a completely different style, they stick out like a sore thumb, why was this merged?

**Comment by Eden077** [comment]
I personally love the new cap drip, freshens it up a bit

**Comment by LankLTE** [comment]
> these are from a completely different style, they stick out like a sore thumb, why was this merged?

nobody is forcing you to wear it

**Comment by JoeHammad1844** [comment]
> nobody is forcing you to wear it

what else do I wear as captain?

**Comment by mirrorcult** [comment]
clown attire

**Comment by JoeHammad1844** [comment]
ok trve..

**Comment by Skarletto** [comment]
This PR does not change the formal attire whatsoever. The biggest change here is the default jumpsuit/skirt, and the carapace, which looks just fine on the formal attire.

**Comment by Skarletto** [comment]
also in an ideal world you'd wait for me to update other drip

**Pull request merged**
