### PR TITLE
Ram

### PR DESCRIPTION
**Pull request by KommissarRed**
## About the PR
Add a hand ram for the Security.

## Why / Balance
This item may allow security to gain quick access to barricaded criminals or other locations where security do not have access. The ram can only be picked up with two hands and is ginormous in size. Can be crafted on Sec Techfab for 10 units steel and 10 seconds.

## Media

https://github.com/user-attachments/assets/dcdcacc8-ae01-49e1-a539-da0de4825e5b

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Add a hand ram for the Security

### CODE REVIEW

**Comment by Strol20** [comment]
I think it should be implemented differently. With this, people can break the walls into space

**Comment by thebadman4662** [comment]
Nukies dream if they rush armory I guess. just wide-swing delete whole departments as rod elemental.

**Comment by gusxyz** [comment]
> Security has all sorts of methods of getting into places they don't have access to. Talking to the AI, captain, getting an engi to hack it, or getting access on their ID from the hop are all viable methods. This addition de-incentivizes player interaction and causes problems for engineering. It also seems very easily abusable, being a cheap and powerful tool for the sole purpose of causing damage to the station, which security should NOT be doing.

Agreed, in real life, corporate security's first and for most goal is to protect the companies assets and employees. Destroying company asset's go against a corporate security officer's training and wouldn't be implemented especially in the case of apprehending a suspect.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
This is really overpowered and cheap to boot and significantly affects balance.

**Comment by SlamBamActionman** [comment]
Considering the changes, I feel that the "overpowered" comment from Sloth wasn't addressed.

100 structural damage is *a lot*. With unlimited uses and effectively unlimited numbers this could tear through stations. Need to get through a door? You got AI, access requests or hacking. Need to get through a wall? Engineers, biting the bullet and going blind yourself, cutting it down with your knife or get equipment from Salvage.

I am having difficulties seeing where this would be appropriate for Security to have, and if they were to have it, how to balance it to not make it just be basically a pickaxe/axe/sledgehammer, which already exists.

**Comment by KommissarRed** [comment]
A battering ram can destroy a station? I imagine officers going to a station and breaking it, funny.  The AI can't open the door because the wire is cut or the camera is broken, the accesses can't be given because the HoP is rotting in the tunnels with Ian, you can't hack the doors because you don't have insulated gloves and it's not certain that they haven't already been stolen by traitors from all over the station. Breaking a wall with a knife or blowing it up with explosives, cool. 

That's what a ram is for when more peaceful and safer ways of getting somewhere have run out. 

If people think that such a ram is OP and officers will have fun breaking down the walls of the station, then I'll just close the PR. Maybe in the future I'll find a more balanced way to get into inaccessible rooms

**Comment by thebadman4662** [comment]
> Some airlock breaking values (based on testing, so they're not exact):
> 
>     * Energy Sword: 20 seconds
> 
>     * Fire Axe: 12 seconds
> 
>     * Ram: 6 seconds
> 
> 
> My concern is less Security breaking in, and more some tider getting their hands on it and deciding that the Captain's room is now theirs.

How does it look vs reinforced walls? Cause they had some high structural resistances, right? Esword can't even scratch it if I recall right and ram will dodge much of penalties that fireaxe would face.

**Comment by inewma0904** [comment]
I have rarely been in a game where a secoff can't catch someone because they go through a locked door, but it does happen. The ram could also be useful in case traitors block off areas - particularly in maints- by building walls. I distinctly remember one game where several tiders barricaded themselves in disposals and harassed security officers, which although quite funny, became frustrating when we had to wait for salvage to show up to break down the 3-layer-thick walls they had erected.

However, I think the ram should not be crafted at the secfab, mostly because the warden or HoS should authorize its usage. It seems odd to let a secoff do major damage to corporate assets without a signoff from one of the security personnel. Maybe the armory could have a ram or two.

**Comment by thebadman4662** [comment]
> I distinctly remember one game where several tiders barricaded themselves in disposals and harassed security officers, which although quite funny, became frustrating when we had to wait for salvage to show up to break down the 3-layer-thick walls they had erected.

I would say its more problem with bulding.

You need no tools and only few seconds if you have mats to make things that take way, WAY longer to deconstruct or destroy. Like electric traps take second or two to make out of rods but to deconstruct you need to weld it and shit. Likewise whole reinforced wall is mere 3 doafters of 2/2/2 resources while deconstructing it requires tools, protection if you do not want to go blind and way more time.

**Comment by chromiumboy** [comment]
Thank you for taking the time to put this together. Unfortunately, after some discussion amongst the maintainers, we have decided to close this PR. The ram is simply too powerful, being a reusable device with extremely high structural damage. This allows the wielder to break down not only doors, but also walls (including reinforced) and other structural elements with great effectiveness, which is well outside the scope of the proposed use of this device

As it currently stands, we do not see a way this PR can move forward without a complete redesign. If you still feel that security needs access to a device capable of breaching doors, you are welcome to submit an alternative proposal; we would encourage you to discuss its design on our Discord with other contributors before you commence work

**Pull request closed without merging**
