### PR TITLE
Meta shuttle

### PR DESCRIPTION
**Pull request by Emisse**
recreated for ss14 by flareguy. i fixed map file to pr it for him

### CODE REVIEW

**Comment by mirrorcult** [comment]
thank you my child

**Comment by JoeHammad1844** [comment]
imag pleaz

**Comment by mirrorcult** [comment]
imagine it

**Comment by Emisse** [comment]
yea its on discord

**Comment by JoeHammad1844** [comment]
> yea its on discord

im banned :trollface:

**Comment by Emisse** [comment]
haha

**Comment by JoeHammad1844** [comment]
IMAG

**Comment by mirrorcult** [comment]
image

**Comment by JoeHammad1844** [comment]
oh shit ss13 shuttle

**Comment by deltanedas** [comment]
this is clearly the box shuttle :trollface:

**Comment by Clostyandr** [comment]
Bro just mapped it in minecraft.

**Pull request merged**
