### PR TITLE
Give Nukies a Hand Labeler

### PR DESCRIPTION
**Pull request by thetolbean**
## About the PR
Adds a hand labeler to the Nukie Planet

## Why / Balance
Makes it much easier to organize the agents medical supplies, and allows other nukies to more easily use meds provided by the agent without mistakes.
I have spectated multiple nukie rounds, and it is not uncommon for the agent to mix up chemicals while under stress.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by UBlueberry** [comment]
probably better to leave it lying on a table, in case the agent doesn't spawn

**Comment by thetolbean** [comment]
> But it being on table is harder to miss as agent might not be aware of one in vend(CMOs still are clueless about chemdrobe ones already!)

The nukie planet does not have a chemdrobe, so they do not have access to one in a vending machine. They only have a syndiejuice, which only has jugs. So it's not really an issue of it being missed, it's an issue of one not being available (for some reason).

**Comment by ArtisticRoomba** [comment]
I would rather have it mapped on the table, that way it's obvious. I'm not sure about including it in the loadout for the agent, it might affect ghost role spawns (unless they're separate). Oops, 500 labelers.

**Comment by pheenty** [comment]
> mix up chemicals

skill issue

The change is still fine tho

**Review by deathride58 — APPROVED** [review]
Rule of fun lets go

**Pull request merged**
