### PR TITLE
Improve Box roundstart TEG

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
Improve the roundstart TEG on Box.

## Why / Balance
Box has a size-1 AME which causes engineering to get an earfull of the station for the first 15-20 minutes. Improve the round-start TEG layout so that more of it can be used to set up a TEG that produces a reasonable amount of power.

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Emisse** [comment]
idk how i feel about removing the hot loop entirely

**Comment by deltanedas** [comment]
a common setup is to pump in fire and then just vent it into a lattice, since gases are mined infinitely

**Comment by metalgearsloth** [comment]
> Why are you yet again
> I feel like you are playing a different game
> You did this exact same thing in https://github.com/space-wizards/space-station-14/pull/20142 and you ignored all feedback that you received there, repeating the same thing here.

**Comment by NancokPS2** [comment]
I think that what they meant is that the last change made the trit burn chamber be the dedicated TEG burn chamber?  
I mean, you can still pipe plasma directly to the TEG chamber, but the layout seems to imply that you should use the atmos chamber for it, which is meant to produce and store trit/frezon

**Comment by Partmedia** [comment]
Because the station is big and has an under-sized AME, I think it's important for the TEG to work (well) out of the box. If people want to set up other stuff like trit, they can do that once there's plenty of power.

> idk how i feel about removing the hot loop entirely

Folks can build a hot loop if they want to. It works fine without a "loop". For various reasons including pumps being rate and pressure limited a TEG with a hot loop can actually generate less power than one without. I can explain more if you'd like.

@AJimmyU Because I played an atmos round on Box last night, and we ended up disassembling the round-start TEG to set up pretty much the same thing that I proposed here.

> It's not going to make the TEG easier to setup if you just make it even more dependent on atmospherics, requiring even more setup and inter department cooperation. Engineers cannot access the atmos burn chamber, you are effectively limiting the amount of people that can setup TEG without ripping out pipes.

TEG depends on atmos from the start, because they need to make the burn mix. This proposed setup requires *less* setup because as soon as the burn is going, you just need to turn a few valves and the TEG is working and working well.

> You don't even have the basest notion of cycling the gas in hot loop, gas miners will be eventually phased out. This setup is plain bad and a trap for new players.

Cycling gas in the hot loop is misguided at best. This setup is significantly better, produces more power, and is harder to get wrong for new players.

Re: gas miners: to reduce gas consumption you pump less fuel into the burn, increasing fuel like a throttle as opposed to maxing out the fuel pump, having leftover superheated gas, and then doing this hot loop cycling dance.

I would encourage you to go try this setup for yourself instead of just saying things.

**Comment by Anzarot121** [comment]
Here is the simplest, most efficient scheme under current conditions, delivering up to 3 MW. Oxygen with plasma is pumped into the chamber in a ratio of 30.6, 69.4 to 9000 kPa, then ignited, burns for 3 minutes and do as shown in the screenshot. At 120 l/s it produces 360 kW. With a 3 by 4 camera, it worked non-stop for 12 hours without refilling. If you are a masochist, you can replace the cold circuit with radiator cooling. Unfortunately, the radiators are limited by a stupid system that has nothing to do with logic or realism.
Please forgive me if this was too active or passive aggressive, the translat
/or does not convey the undertones of the text very wel
image-1

**Comment by JoeHammad1844** [comment]
removing the hot loop and connecting it to the atmos burn chamber instead of the one already in the TEG room just doesn't make sense

**Comment by daerSeebaer** [comment]
This discussion to me looks like a fundamental design discussion on how TEGs should be set up, hampered by the fact that multiple involved components (pumps, radiators) have their own issues and the implied fundamental change of removing gas miners.

This is not a discussion for a PR and more for a design document that at least I haven't found yet for the TEG.

So my suggestion is to take this whole thing and all arguments exchanged here back to the drawing board and have a coordinated discussion about the entire topic instead of starting with "fixing" layouts on individual maps.

**Comment by NancokPS2** [comment]
Being fair, with the rework that will require doing that. These small changes may not even matter.  
  
There's a good chance all of these fixes will be completely undone if that happens.

**Comment by Emisse** [comment]
i am opposed to this still i do not like this as a roundstart setup, please keep fuel line separate and make sure there are loops for both sides since that is the way the machine is supposed to be used/balanced around. if its more efficient to do it this way then something needs to be changed

**Comment by Partmedia** [comment]
That pumps circulate burn mix on the hot loop seems to me like a design flaw; but as you and other commenters point out, that is better fixed elsewhere.

**Pull request closed without merging**
