### PR TITLE
Clothing can change player speech sounds

### PR DESCRIPTION
**Pull request by ActionHorse**
## About the PR

This allows for clothing to change speech sounds, and adds an item that lets you change the sound of your in-game voice.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Screenshot 2023-06-24 113726
Screenshot 2023-06-24 113754
image
**Changelog**

:cl: 
- add: Added Speech Resythesizer.

### CODE REVIEW

**Comment by Nails-n-Tape** [comment]
maybe call it something like "speech resynthesizer"? The name "AI implant" doesn't exactly explain what it does.

**Comment by ActionHorse** [comment]
I'll fix that, as well as adding more voices to the device

**Comment by metalgearsloth** [comment]
@ActionHorse are you still working on this.

**Comment by Vordenburg** [comment]
The forensic scanner can serve as an example of how to setup a bound user interface.

Have a look at the following files:
```
Content.Client/Forensics/ForensicScannerBoundUserInterface.cs
Content.Client/Forensics/ForensicScannerMenu.xaml
Content.Client/Forensics/ForensicScannerMenu.xaml.cs

Content.Shared/Forensics/ForensicScannerEvent.cs

Content.Server/Forensics/Systems/ForensicScannerSystem.cs

Resources/Prototypes/Entities/Objects/Devices/forensic_scanner.yml
```

**Comment by ficcialfaint** [comment]
Ask to re-open when you're back to this

**Pull request closed without merging**
