### PR TITLE
Add more things to hacked vending machines

### PR DESCRIPTION
**Pull request by NoElkaTheGod**
## About the PR
Vending machines now have more additional contents when they are emagged and/or the respective wire is cut. Full list bellow.

List of changes:
Magic candle box. Like candle box, but contains infinite candles. Also magic candles now have "Candle" tag.
Boozeomat contraband inventory: 5 water bottles. Useless, but funny.
PTech contraband inventory: 2 robotics and 1 med-sci encryption keys.
PTech emagged inventory: 2 syndie encryption keys. Too risky to be useful, but can save your team in some situation. Probably.
MrChang contraband inventory: 2 bowls of boiled rice. Someone left "#rice?" in the file, so i did it.
PietyVend contraband inventory: 1 box of magic candles. Let players decorate the station or somtehing.
ChefVend contraband inventory: 3 sticks of cannabis butter. Make funny dishes for your clients.
ChefVend emagged inventory: 3 fly amanitas. Make deadly dishes for your clients.
ChemVend contraband inventory: 1 bottle of lead. Toxic gaming... or some licoxide.
ShadyCigs contraband inventory: 2 joints. When tobacco isn't for you.
Dinnerware contraband inventory: 1 syringe. For more "spicy" foods.
Engivend contraband inventory: 1 pair of conducting gloves. Give them to that particularly annoying tider.
Happyhonk contraband inventory: 2 soap. For clowning stuff.
NanoMedPlus contraband inventory: 1 bottle of mute toxin. Silence your patient.
NanoMedPlus emagged inventory: 1 bottle of toxin. Silence your patient. Forever.
RobotechDeluxe contraband inventory: 1 cardboard cyborg hat. Beep boop.
RobotechDeluxe emagged inventory: 1 toy H.O.N.K. Having an emag as a scientist is already very strong, what did you expect?
MegaSeeds contraband inventory: 1 pack of cannabis seeds. it already had fly amanita seeds on emag, so i think that's fair.

New ideas are welcome!

## Why / Balance
Cool.

## Technical details
YAML changes.

## Media

https://github.com/user-attachments/assets/f18fe6c6-dfb7-430e-b6b2-8ab6af8be282

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Many vending machines now have some new items when hacked.

### CODE REVIEW

**Comment by deltanedas** [comment]
chemvend already has like 4 jugs of ethanol what purpose does an extra bottle serve (when the base jugs are only ever used for breaking down into carbon)

**Comment by thebadman4662** [comment]
> Dinnerware contraband inventory: 1 cryostasis beaker. What is this thing even used for?

Rocket launchers, impact grenades, foam and smoke bombs.

**Comment by NoElkaTheGod** [comment]
> chemvend already has like 4 jugs of ethanol what purpose does an extra bottle serve (when the base jugs are only ever used for breaking down into carbon)

I know, it is more so a joke. If you have better ideas feel free to share.

**Comment by thebadman4662** [comment]
> > chemvend already has like 4 jugs of ethanol what purpose does an extra bottle serve (when the base jugs are only ever used for breaking down into carbon)
> 
> I know, it is more so a joke. If you have better ideas feel free to share.

Lead of course, it got removed from game for crew.

**Comment by NoElkaTheGod** [comment]
> > SalvageVendor contraband inventory: 1 crusher dagger. Not great, not terrible.
> 
> Uh, isn't its dps around esword still?

Um, no? It's 15 slash a hit.

> Lead of course, it got removed from game for crew.

I had considered that, but decided that lead is kinda OP. You can kill someone with, like, 5 units of it, and they won't even notice.

**Comment by pheenty** [comment]
> > > SalvageVendor contraband inventory: 1 crusher dagger. Not great, not terrible.
> > 
> > 
> > Uh, isn't its dps around esword still?
> 
> Um, no? It's 15 slash a hit.
> 

It hits twice a second

**Comment by thebadman4662** [comment]
> I had considered that, but decided that lead is kinda OP. You can kill someone with, like, 5 units of it, and they won't even notice.

Lico potential for revs and sec though. 0.5u of charcoal already deletes loads of lead.

**Comment by NoElkaTheGod** [comment]
Alright, some tweaks arrived:
Removed crusher dagger from salvage vendor contraband inventory (turns out it's a pretty damn good weapon).
Removed ethanol bottle from chemvend (and SyndiJuice) contraband inventory (not funny didn't laugh)
Added 1 bottle of lead to chemvend contraband inventory instead. Too strong? Probably yes, but we'll see.

**Comment by Spessmann** [comment]
Magic candles never go out, so more op than you think. Just use one or two magic candles or switch them out of something else entirely.

**Comment by ps3moira** [comment]
This looks a little not well thought out on what type of items are contraband are in there and could use a lot of tweaking

**Comment by NoElkaTheGod** [comment]
> Magic candles never go out, so more op than you think. Just use one or two magic candles or switch them out of something else entirely.

They can't burn anything, and light radius is rather low, so i think decreasing their amount to one box should do.

> I'd also replace the cryostasis beaker with some syringes (to poison food with).

Good idea, will do.

**Comment by NoElkaTheGod** [comment]
> This looks a little not well thought out on what type of items are contraband are in there and could use a lot of tweaking

Yup, there are definitely some stupid ones. New ideas are appreciated.

**Comment by NoElkaTheGod** [comment]
Closing in favor of https://github.com/space-wizards/space-station-14/pull/32911, basicaly the same thing but better.

**Pull request closed without merging**
