### PR TITLE
Uncooked animal proteins is safe for animal stomachs only

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Simple yaml pr (that I spend too much time on cause I accidentally discovered #26809)

## Why / Balance

Everyone except of humans could eat rats without getting poised. This makes it so only animals stomach can (for species only Lizards and Arachnids)

## Technical details

Check for if you don't have an animal stomach and give you the proper effects otherwise

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Vasilis
- fix: Blood (or anything containing uncooked animal proteins) can only be consumed by animal stomach's instead of all but human. Attempting to due so will poison you as intended.

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
How the fuck did that conflict already I just merged master

**Comment by UbaserB** [comment]
NOOOOOOOOOOOOOOOOOOOOO

**Comment by QuietlyWhisper** [comment]
Make sure this doesn't affect 

- mice / rat king
- slimes
- non humanoid mobs

**Comment by Callmore** [comment]
slimepeople are meant to be able to just consume uncooked protein?

**Comment by VasilisThePikachu** [comment]
> Make sure this doesn't affect
> 
> * mice / rat king
> * slimes
> * non humanoid mobs that may not have "animal" metabolizers

- This does not effect rat king or mice
- Slimes are intended to have be hurt
- If they don't have animal metabolizers then they should not be consuming meat raw. The fix for them is to give them an animal metabolizers

**Comment by QuietlyWhisper** [comment]
> Slimes are intended to be hurt. They are not an animal

They're not necessarily human either, the question is more if slimes should be able to consume it or not.
I do think it allows arachnids and lizards to be more distinct anyways! 👍

**Comment by HelpTheSteak** [comment]
Another slimeperson nerf inbound

**Comment by Clonko** [comment]
Generally speaking slimes being able to drink slightly poisonious stuff is part of the species(14 loko and 20% poison resist). So I'd say that they should be able to drink raw protein.

**Comment by UbaserB** [comment]
oh wait i misunderstood i was messaging at like 2am i thought it stopped humans and other species from drinking blood altogether lol.

**Pull request merged**
