### PR TITLE
Rename Space Heater to Space HVAC Unit.

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Changed the name of the Space Heater.

## Why / Balance

The Space Heater apparently also has a cooling option. I only learned of it today. I think the name should portray the fact it can go both ways a bit more.

## Technical details

Just all name changes. No ID touched.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Space Heater renamed to Space HVAC Unit to show it can also cool rooms.

### CODE REVIEW

**Comment by muburu** [comment]
adding the word space as an adjective is used to clear up any confusion in terms of "how does this work"
oh how does this dragon survive in space? it's a SPACE dragon!? makes perfect sense to me!

**Comment by ScarKy0** [comment]
> adding the word space as an adjective is used to clear up any confusion in terms of "how does this work"
oh how does this dragon survive in space? it's a SPACE dragon!? makes perfect sense to me!

True but space air conditioner sounds all ways of weird

**Comment by UbaserB** [comment]
I agree with the reasoning but not the name

**Review by keronshb — CHANGES_REQUESTED** [review]
Portable/Space HVAC unit is a better name just calling it the opposite.

**Comment by ArtisticRoomba** [comment]
as previously said, the UI is called "temperature control unit" so it would be best to name it somewhat similar to this

people don't know what the full meaning is for HVAC, also "air conditioner" is universally known as cold, "space heater" is universally known as hot, etc.

**Comment by IProduceWidgets** [comment]
Thermojigulator

**Comment by keronshb** [comment]
> as previously said, the UI is called "temperature control unit" so it would be best to name it somewhat similar to this
> 
> people don't know what the full meaning is for HVAC, also "air conditioner" is universally known as cold, "space heater" is universally known as hot, etc.

Could just spell it out. Space Heater is nice because it's very short, but since it can do AC it also doesn't really explain what it is.

Space Heating Ventilation and Air Cooling Unit is a bit too long so Space HVAC makes it better, could always put it in the description.

Temperature Control Unit also works, but by name it doesn't really scream "how is this done" (How does this object control the temperature?) 

I think space or area is important to have in the name somewhere.

**Comment by SaphireLattice** [comment]
I propose "Space Entropy Controller"

**Review by Aeshus — APPROVED** [review]
I approve of the name. 

*I can finally live the dream of being an HVAC repair person!*

I wish we could rename the fluent key/string thing, though.

**Comment by Partmedia** [comment]
I think I want to write a bit at length about why I think "space heater" is the better name:
- For those of you who are not familiar, a "space heater" is an electrical appliance that resistively heats up the environment ("space"). It can be used in a tongue-and-cheek and joking way to refer to a complex device that for stupid reasons ends up being only as useful as a space heater. So if you use your computer to mine Dogecoin, for example, someone could call your computer a "space heater".
- This is a pun because here it means "a heater in space", which is a trope used by a lot of other SS14 item names to convey a sense of magic and suspension of disbelief, setting the tone for a seriously silly fun time in space (one of our core pillars).
- In fact, it would be impossible for a HVAC unit to cool a space without rejecting the heat elsewhere due to the [Second Law of Thermodynamics](https://en.wikipedia.org/wiki/Second_law_of_thermodynamics) because total entropy must always increase, and cooling a space without heating up something else would result in a net decrease or at best zero increase in entropy.
- So the name actually sets the stage to explain why such a device can exist (because of "space magic").
- So "space heater" is a better name than "HVAC" because 1. it is a punny pun and 2. because it sets the tone and expectation for the game and setting we want to create.

**Review by keronshb — CHANGES_REQUESTED** [review]
I got some other maint opinions on this and most of us don't want the name changed from Space Heater. It's a funny pun in itself, even if it isn't directly saying what the appliance in. Space Station's also built on some fun descriptions and puns like this.

**Comment by Aeshus** [comment]
I think it would serve better to change the description. It could be made more clear that even though it's called a "Space Heater", it can also cool? This could also make the pun more obvious.

(The current description is a little too jargon-y for my taste anyways.)

> `A bluespace technology device that alters local temperature. Commonly referred to as a "Space Heater".`

**Comment by Partmedia** [comment]
Thanks for your contribution. As discussed, I think we want to keep the original name. Please feel free to open a new PR with a revision to the description.

**Comment by ArtisticRoomba** [comment]
They can read the guidebook. Space heater is officially funny, it would be best to maybe make the description a little bit more descriptive to compensate but otherwise I agree with Nota whole-heartedly.

**Pull request closed without merging**
