### PR TITLE
Add recipe of beverage jug

### PR DESCRIPTION
**Pull request by ArZarLordOfMango**
## About the PR

Added autolathe recipe for beverage jug. Cost 1 sheet of steel.
## Why / Balance

Sometimes, need more of these jugs, but you can only get empty ones from the restock booze, it's too expensive for two empty jugs. For one steel we get 150u, while a bucket for the same price is 250u.
## Media

craft-jug

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added autolathe recipe for beverage jug.

### CODE REVIEW

**Comment by Kadeo64** [comment]
inb4 maintainers complain

**Comment by Hanzdegloker** [comment]
mfw 1 steel for the plastic drink jug

**Comment by ArZarLordOfMango** [comment]
Wait,  he made of plastic...?

**Comment by Hanzdegloker** [comment]
Indeed it is a plastic jug ( I should know I made it lol )

I based it off the jugs I saw working in the food industry a while

**Comment by Tayrtahn** [comment]
Wait a sec, do we not have fill level sprites for this clear, plastic jug?

**Comment by Hanzdegloker** [comment]
It's uh, not clear

**Comment by Tayrtahn** [comment]
Ah, well okay then. Nevermind!

**Pull request merged**
