### PR TITLE
Monkey PR

### PR DESCRIPTION
**Pull request by TheEliteGojira**
## About the PR

The purpose of this PR is to showcase my changes to the monkey sprite which I find outdated and extremely messy from a pixel-artist perspective, seeing how it was made well over a decade ago. This branch modifies both the monkey and all monkey-related sprites in the game to a new redesign by myself that was inspired by Goonstation. My goal with this modification was to create a much more visually pleasing (and maybe even cuter) sprite for our favorite primate friends!

**Media**

image
(any other screenshots of the sprites from other angles can be requested through my Discord KⱧ₳₦₲ØJł#2673)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the new resprites of the monkey entity and all other monkey related items

### CODE REVIEW

**Comment by DogZeroX** [comment]
This will be SS13 in 2013

**Comment by moonheart08** [comment]
Are you in the discord, or.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
All `meta.json` files need updated copyright.

**If any goonstation assets were used as templates, i.e. traced or modified, this must be disclosed by using their copyright information.**

**Comment by AJCM-git** [comment]
@TheEliteGojira You coming back to this?

**Comment by keronshb** [comment]
No changes in a few weeks and after some discussion, we don't think the sprite would be a good fit.

**Pull request closed without merging**
