### PR TITLE
Rename generic drugs

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

Renamed "Space Drugs" and "Stimulants"

## Why / Balance

Space Drugs and Stimulants often cause quite a bit of confusion. For instance,
space law uses the term "stimulants" to represent the class of drugs and not
the reagent called "stimulants".

## Technical details

Locale change. The names came from a list of ss13 chems.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: Aquif
- tweak: "Space Drugs" have been renamed to "Space Mirage"
- tweak: "Stimulants" have been renamed to "Hyperzine"

### CODE REVIEW

**Comment by UbaserB** [comment]
Hyperzine sounds super cool. You will probably have to rename other things though, like the stim injector and there might even be mentions in the guidebook for example though

**Comment by dffdff2423** [comment]
I will grep through it real quick.

**Comment by thebadman4662** [comment]
Why rename Space Drugs? Now Space Law would need to be updated to outlaw Space Mirage as apparently its SDs specifically being outlawed while weed and stuff are legal.

**Comment by dffdff2423** [comment]
It is just as confusing as stimulants. It is not like it is hard to change one line of space law.

**Comment by UbaserB** [comment]
> Why rename Space Drugs? Now Space Law would need to be updated to outlaw Space Mirage as apparently its SDs specifically being outlawed while weed and stuff are legal.

Space drugs has always been a weird name as it's unclear what it does. "Drugs" is a general term for both illegal (hallucinogenic) and legal (medicinal) drugs

**Comment by EmoGarbage404** [comment]
so zased

**Pull request merged**
