### PR TITLE
Adds Syndie pyjamas

### PR DESCRIPTION
**Pull request by Zymem**
## About the PR 
Adds a syndicate pyjama bundle, it can be found on the misc section inside the uplink and it costs 4 TC.

**Screenshots**

image
**Changelog**

:cl: Zyme
- add: The Syndicate now offers a pyjama bundle! You can find it on your nearest uplink.

### CODE REVIEW

**Comment by mirrorcult** [comment]
why would people buy this

**Comment by Zymem** [comment]
> why would people buy this

To be honest, it is a meme item.
While checking syndicate items on the TG wiki I came across some pyjamas, thought it would be nice to try and add something similar.

**Comment by mirrorcult** [comment]
i'm fine w/ it as a meme item if the cost is lowered a bit i think

**Comment by Fishfish458** [comment]
> i'm fine w/ it as a meme item if the cost is lowered a bit i think

4 would put it on the same cost as the syndie clown and centom costume, so, not really bad. It's supposed to be considered a dumb (I got all my objectives done without TC) item anyhow.

image

**Comment by mirrorcult** [comment]
this has less utility than the centcom uniform imo

**Comment by Zymem** [comment]
> this has less utility than the centcom uniform imo

Makes sense, as these will paint a target on your back. I'll lower the cost to 2TCs.

**Review by Peptide90 — APPROVED** [review]
Lgtm now. For 2TC it’s a bargain duffle bag

**Comment by Zymem** [comment]
(Talking about making the bag a bundle of multiple pyjamas)
image
Just saw this on #ideaguys.
I like the idea of adding a couple more pyjamas to the bag, but this would probably bring another change to the cost of it.
No clue whether to put it back to 4TC or just 3TC. 
Any suggestions welcome.

**Comment by OldDanceJacket** [comment]
4TC. 
One for each jammy, and a bag for free. 
Puts it as the same cost as clown/centcom as pointed out earlier.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
