### PR TITLE
Syndicate Pill of Death

### PR DESCRIPTION
**Pull request by Interrobang01**
## About the PR

"A lethal, unlabeled pill containing lexorin and nocturine which lulls victims into a slumber while the lexorin works away. The victim has around 4 seconds to react before death."

Adds a pill to the uplink containing 10u lexorin and 10u nocturine. This puts the victim to sleep, then deals some damage. The victim wakes up 4 seconds before the lexorin puts them into crit.

This pill is a way for syndies to assassinate victims without using those boring pens or those crappy guns that seem to shoot foam darts instead of lead. Nobody wants to eat an unlabeled pill, so the idea is to gain the trust of the victim, wait for them to be damaged, then feed them this pill, resulting in their swift death.

Costs 4 telecrystals, a price which I decided in half a second, please help me hone this down to a more perfect cost.

**Media**

(the movement glitch near the start is not part of the PR)

https://user-images.githubusercontent.com/113810873/227804491-ff221f82-6785-4982-aa79-b8d62d665996.mp4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The Syndicate has begun mass-producing unlabeled pills filled with nocturine and lexorin. Watch out!

### CODE REVIEW

**Comment by Slava0135** [comment]
you missed one critical detail - you can grind pill and use in hypo

**Comment by Stealthbomber16** [comment]
why does this need to exist

**Comment by Interrobang01** [comment]
> Assassination methods are rather limited right now and I felt a pill that only really works on people who trust you (minus that hypopen thing) would help fill the niche and give some options other than hypopen

**Comment by Interrobang01** [comment]
> you missed one critical detail - you can grind pill and use in hypo

It's definitely less price effective in terms of nocturine, but lexorin is definitely a big issue. Then again, it involves buying the expensive pen which might make it a non-optimal choice. I need to think about it for a bit.

**Comment by Interrobang01** [comment]
After thinking about it for a bit, I think people will be more inclined to buy the nocturine bottle instead, because it's 2.4 times more price-efficient for nocturine and probably more useful; If you're stabbing someone with a hypopen, you want to do it in an isolated place. At that point, you might as well use a toolbox instead of lexorin.

If you still think it's still an issue, I can raise the price, reduce the lexorin, or try to make the pill non-grindable/spikable.

**Comment by EmoGarbage404** [comment]
Selling something which is literally just another uplink item + a chem you can aquire on station seems lame. At the very least, it could be some kind of new, unique chem with a more interesting effect than "it kills you"

I don't really see the appeal when you could just as easily hypo with nocturine and kill someone via any other method.

**Comment by Interrobang01** [comment]
> Selling something which is literally just another uplink item + a chem you can aquire on station seems lame.

There's also the pill the chems are in, which has quite a bit of impact (hiding true nature, easy ingestion, doesn't taste like literal poison), but I do see your point. I think the component parts are hard enough to get that this falls into "unique uplink item" territory.

> At the very least, it could be some kind of new, unique chem with a more interesting effect than "it kills you"

Not really sure what the chem would do other than kill you, but maybe. It would certainly fix the previously mentioned problem.

> I don't really see the appeal when you could just as easily hypo with nocturine and kill someone via any other method.

The entire point is to have a method of murder other than the overused hypo ; this method is cheaper (hypo+noct costs 11tc!), cleaner, and quicker if done right.

**Comment by moonheart08** [comment]
This is lame as fuck.
Add a poisons kit to the uplink instead.

**Pull request closed without merging**
