### PR TITLE
Wall resprites

### PR DESCRIPTION
**Pull request by LudwigVonChesterfield**
## About the PR 

Ported TauCeti Wall Sprites, added ConversionMode for TauCeti wall sprites.

Please do consider this a bundle deal together with https://github.com/space-wizards/space-station-14/pull/8718

**Screenshots**
| PRETTY BEFORE | PRETTIER AFTER |
| ------------- |:-------------:| 
|image  |image|
|image |image |  

Ported from https://github.com/TauCetiStation/TauCetiClassic/pull/3993 by [Theta Community](https://github.com/ThetaStation/ThetaStation)

**Changelog**

:cl: Luduk
- add: Changed the sprite for walls and reinforced walls.

### CODE REVIEW

**Comment by Elijahrane** [comment]
The solid walls look okay, the rwalls look kind of bad IMO

**Comment by moonheart08** [comment]
Please make a separate PR with just the iconsmooth conversion mode. We're not interested in these assets at this time.

**Comment by ike709** [comment]
Those rwalls look... really bad.

**Comment by youarereadingthis** [comment]
Those basic steel walls look good. Like, really good. Wish we had 'em.

The reinforced walls do not repeat well because of the big square in the center. The border patterning looks great though.

**Pull request closed without merging**
