### PR TITLE
welding gas mask

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

adds a combo welding mask / gas mask to salvage tech research.
printable at sci for some steel and glass.

## Why / Balance

I think it's a nifty little item that players can get a lot of casual use out of. It's an easily obtainable form of welding protection plus it's more compact. I think it's a good fit for a science unlock.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the welding gas mask to salvage equipment research.

### CODE REVIEW

**Comment by deltanedas** [comment]
why would le salv powergamer wear this instead of engi goggles which dont remove defense

**Comment by EmoGarbage404** [comment]
> why would le salv powergamer wear this instead of engi goggles which dont remove defense

shrimple i simply do a tactical nerf of salvage mask

**Comment by deltanedas** [comment]
:trollface:

**Comment by EmoGarbage404** [comment]
the average powergamer can simply not understand the tactical advantage of being dripped to the nines

**Comment by UbaserB** [comment]
someone tried to add this in #22780 and it got closed

**Comment by Dutch-VanDerLinde** [comment]
> someone tried to add this in #22780 and it got closed

yeah but this version isn't roundstart

**Comment by EmoGarbage404** [comment]
> someone tried to add this in #22780 and it got closed

this version is neither roundstart nor does it have armor values attached.

**Comment by pigeonpeas** [comment]
i think the sprite could be recolored a little to look more like a gas mask? maybe darken the white a lil bit.

**Comment by ps3moira** [comment]
gas masks should give the blind effect when being worn like in 13, then I can see this being more acceptable.

**Comment by Emisse** [comment]
i think this is fine as a sci unlock, i approve but wont merge incase someone else has opinions

**Comment by Hmeister-real** [comment]
I think this is bad, and powergamery. IMO just make it a little more pricey and maybe have it as a lesser welding protection of sort, like it doesn't damage your eyes but it gives you the flashbang effect when you start welding, and it make it so it doesn't protect from flashes so syndie salvs don't just, avoid half of securities utility because le funny mask

**Comment by deltanedas** [comment]
if it didnt even have full welding protection literally no reason you would use it over actual  goggles you can get from engi or on wrecks

**Comment by metalgearsloth** [comment]
dumbass

**Comment by HelpTheSteak** [comment]
Uhh is it on purpose to not be able to pull it up with a action like every other gas mask

**Pull request merged**
