### PR TITLE
Changed sci and RD icons

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

`!` is lame, helix is new best friend

**Media**

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Changed job icons for scientist and research director.

### CODE REVIEW

**Comment by AlexMorgan3817** [comment]
why? It is more genetics sign than science

**Comment by EmoGarbage404** [comment]
The helix icon is more indicative of a generic science icon than an exclamation point. We also don't plan on having any for of genetics, so the icon isnt being used.

**Comment by AlexMorgan3817** [comment]
> helix

Much more indicative is an atom sign

**Comment by EmoGarbage404** [comment]
An atom is unreadable at the detail level of icons. While science doesn't currently involve any biological research, a double helix/DNA symbol is a well understood shorthand for science/research.

**Review by Emisse — APPROVED** [review]

**Comment by AJCM-git** [comment]
Whats the worse thing that could happen

**Comment by EmoGarbage404** [comment]
checkmate liberals, get de-SOVLed

**Pull request merged**
