### PR TITLE
Adds more monkey compatibility to existing outfits

### PR DESCRIPTION
**Pull request by Mith-randalf**
## About the PR

Added some sprites to allow monkeys to wear the following:
Kimono
Ninja Jumpsuit
NT paramedic Jumpsuit
Web Jumpsuit
Emergency Firesuit
Bomb Suit
Monkey Suit
Emergency EVA Suit

I've also added assets and rsi meta stuff for colored jumpsuits and jumpskirts, including prisoner, but I'm fairly sure those don't display due to how they apply colour (seems to lock in or override species state, so its always human), so only works when they're manually set in varedit. This is something I've tried to fix and can't, but with the assets in, it'll work as soon as someone changes how that works.

## Why / Balance

I'm a monkey main. The main thing was the emergency eva suit which genuinely would be useful for monkies to be able to use. Plus allowing the monkey to wear a monkey suit is conceptually funny.

## Media

V video V
https://www.dropbox.com/scl/fi/6nwzoseytirc5n7z1lh4o/2024-04-30-18-53-23.mp4?rlkey=2o298xioodmxkua2wzj64w7hl&st=7589qzsp&dl=0

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: mith
- add: Following a Species Action Lawsuit, more outfits are now monkey-compatible, including emergency EVA and fire suits.

### CODE REVIEW

**Comment by UbaserB** [comment]
I’m pretty sure this is frozen by #8524

**Comment by Mith-randalf** [comment]
> I’m pretty sure this is frozen by #8524

I guess it comes down to whether this falls under "This freeze wont apply for maintaining current variants (like monkey suits)."

but I'm fine with it going on ice til later

**Comment by Dutch-VanDerLinde** [comment]
also says if the sprite can't be displacement mapped

**Comment by UbaserB** [comment]
> also says if the sprite can't be displacement mapped

from what i heard, all monkey clothing sprites are to be eventually displacement mapped, its just no one has done it yet.

**Comment by Dutch-VanDerLinde** [comment]
> > also says if the sprite can't be displacement mapped
> 
> from what i heard, all monkey clothing sprites are to be eventually displacement mapped, its just no one has done it yet.

it means like if the sprite is impossible to displacement map

**Comment by IProduceWidgets** [comment]
My understanding was that displacement maps were intended to reduce the burden of needing to make lots of sprites for non-standard species, not that it would mean refusing custom sprites for those species provided the custom sprites were better than a displacement map.

**Comment by metalgearsloth** [comment]
This is new variants, not modifications, and maintaining monkeys is already bad enough so.

**Pull request closed without merging**
