### PR TITLE
Tesla is no longer an event horizon

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Tesla no longer eats walls/consumes entities it passes over
Tesla phases through walls harmlessly but is contained by containment field or the generator

## Why / Balance

image

I tested the change locally, imo this is the only thing needed to tone down the tesla

shocking people and exploding electronics is a decent amount of potential damage, without the exploding electronics it feels really lackluster

## Technical details

- LightningSystem no longer defaults to just the base "lightning", since different lightning types don't use the sprite randomizer
- Fixed beams being weird by not having it go through the sprite randomizer logic
- Beams now use static physics bodies as opposed to dynamic static bodies, so they don't get displaced by explosions (you shouldn't be able to split a lightning bolt or a beam into pieces)
- ElectricityAnomaly now specifies what kind of lightning it shoots
- OnHitByLightningEvent now actually causes people to get shocked as a result of the EVENT (them being targeted) rather than just randomly relying on the Electrified collision working out
- Singularity/Tesla Generator now gets deleted after it spawns one rather than randomly relying on the non-existent EventHorizon to eat it
- ParticleProjectiles now check for collision with the tesla and appropriately give it energy or decrease its energy
- Tesla prevents collision with all entities besides the containment field, the containment field generators, or particle projectiles
- Tesla is now electrified to deal contact damage when you try to pet it (why the hell was it not electrified before?)

TODO:
- [ ] Fix chain lightning 
- [ ] Code in getting hit by lightning actually causing damage and storing the damage on a sane component
- [ ] Fix all the recursive lightning shot TODOs
- [x] Make lightning last much shorter (why does it stick around for like five seconds anyways?)
## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/c48d1a23-2054-4ff8-a7f1-58350307f52f

## Breaking changes

TeslaEnergyBallComponent.cs no longer has the "ConsumeStuffEnergy" field, as it cannot consume things anymore

**Changelog**

:cl:
- tweak: Tesla no longer eats entities like walls or people.
- tweak: The tesla is now electrified to the touch.
- tweak: The tesla now has HYPER CHARGED LIGHTNING.

### CODE REVIEW

**Comment by Plykiya** [comment]
you know what, I just realized that the tesla probably only grows to spawn miniballs because it just fucking consumes the PA projectiles like the singulo

I'll have to account for that, one second

**Comment by Plykiya** [comment]
last thing to do is to have it go through walls which I'm kind out of ideas for...

it used to achieve the "goes through wall" thing by just... consuming the damn wall with the event horizon and plowing through it
if I give the tesla no collision then it just ghosts through the containment field and becomes uncontainable

it can get around the station like 99% of the time even without the ability to ghost through walls because it will continuously target doors non-stop until the doors explode every wall around them before destroying the door itself, and then it teleports through the hole

**Comment by EmoGarbage404** [comment]
> if anyone has implementation ideas for this, I'd love to hear it

Could just implement c# logic that cancels the collision if the thing its colliding with has a structure tag or w/e

**Comment by Plykiya** [comment]
> > if anyone has implementation ideas for this, I'd love to hear it
> 
> Could just implement c# logic that cancels the collision if the thing its colliding with has a structure tag or w/e

thanks, works

**Comment by Plykiya** [comment]
something to note
if #28747 gets merged, the tesla dies in two hits of the particle decelerator

**Comment by Plykiya** [comment]
#28797 thank you to this PR for fixing the beam stuff so the tesla could become 3x more dangerous

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/assets/58439124/8bc5bed6-bb0c-45c3-af62-d35beb2152ca

current implementation does not successfully work out for chained lightning hits
god I hate lightning code so much
it's made so much harder by the lightningPrototype being a string and not a component I can access, so I'm just going to change that and make this so much better

**Comment by luizwritescode** [comment]
> the recursive function giving me no access to the actual lightning or source of lightning itself

Well, I'm not sure how to solve this "correctly", but adding a callback to the recursive function as a getter for lighting source might fix this issue.

**Comment by metalgearsloth** [comment]
Is this ready for review or

**Comment by Plykiya** [comment]
> Is this ready for review or

not yet, although I can't really draft the PR for some reason

**Pull request closed without merging**
