### PR TITLE
removed rng sampled bool from plants

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

## Why / Balance
its bullshit and has been replaced by actual sampling mechanics

## Technical details
:bomb: 

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
removed Sampled from PlantHolder

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
What does this even do?

**Comment by deltanedas** [comment]
just makes it so theres a random chance of a sampled plant not being samplable even if its perfectly healthy

**Comment by Partmedia** [comment]
While I've come around and now agree with the substance of the change, your PR description really doesn't meet the decorum expectations of a PR. All PRs need to be appropriately justified.

**Comment by deltanedas** [comment]
justification: #24851 and #25326 have been merged. i dont know why are you god defending this anti-fun bool

**Pull request closed without merging**
