### PR TITLE
Rule amendment -  Remove role abandonment aHelp requirement.

### PR DESCRIPTION
**Pull request by Titian3**
## About the PR
Role abandonment rule.

## Why / Balance
Currently there is a requirement for aHelp if you are going to leave the game. In the past we would sometimes open another slot for this but now with cryosleep it is irrelevant and just pointless noise and aHelp volume in the aHelp relay we currently don't need.

## Technical details
Just rule text edit.

## Media
NA

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
NA

**Changelog**
NA

### CODE REVIEW

**Comment by Chubbicous** [comment]
Important jobs/roles like nukies and AI can't really "cryosleep" though

**Comment by Titian3** [comment]
> Important jobs/roles like nukies and AI can't really "cryosleep" though

Sounds like a easy mechanical/mapping issue to be fixed.

**Review by slarticodefast — APPROVED** [review]
I opened an internal discussion thread to confirm this is ok for the other admins. We will also have to update the wiki server rules page at the same time this is merged into stable.

**Review by nikthechampiongr — APPROVED** [review]
Admin discussion concluded. Admins approve of this rule change.

**Comment by slarticodefast** [comment]
grafik

This datafield should be set to false for all command job prototypes to remove the
`You are playing a job that is important for Game Progression. If you have to disconnect, please notify the admins via ahelp.`
message in the chat at roundstart.

**Review by slarticodefast — APPROVED** [review]

**Review by slarticodefast — APPROVED** [review]

**Comment by SaphireLattice** [comment]
For the record: Count me fixing up this for merging into `stable` as my approval per the hotfix procedure

**Pull request merged**
