### PR TITLE
Added anti zombie turret

### LINKED ISSUE #23507: There should be a type of turret that is hostile to zombies only
## Description

For admin purposes (like zombie checkpoints at nanotrasen), downstream builds or future projects in mind (like custom CBurn shuttle?)

**Screenshots**

You can see in this photo that admins would probably be interested in this.

image

### PR DESCRIPTION
**Pull request by nikthechampiongr**
Resolves #23507

## About the PR

This adds a turret that only targets zombies.
## Why / Balance

#23507
## Technical details

I just made a new faction that is only hostile to zombies. As much as I would like to just override the hostilities of the NT faction or something I don't think I can do that with the current faction system.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Screenshot_20240109_185325

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Wheres the PVZ pea shooter

**Comment by Kadeo64** [comment]
> > Wheres the PVZ pea shooter
> 
> From what I got from the issue this is meant just as an admeme for special events/end of round centcomm events so it did not make sense to chance the appearance. If you want me to make a special plant for botany I could work on that and the stats I'd need although I can't sprite for shit so I'd need someone else for the sprite.

I can make a devsprite of it probably

**Comment by metalgearsloth** [comment]
This belongs in admin repo as it's not in use ingame and is explicitly for admin purposes.

**Comment by UbaserB** [comment]
based

**Comment by nikthechampiongr** [comment]
Is there any actual interest for a botany plant that just shoots at zombies or something similar that will be a part of the game in general instead of just an admeme? If not I'll just close the commit due to what sloth says.

**Comment by UbaserB** [comment]
> Is there any actual interest for a botany plant that just shoots at zombies or something similar that will be a part of the game in general instead of just an admeme? If not I'll just close the commit due to what sloth says.

to be fair that sounds kind of funny

**Comment by Kadeo64** [comment]
> > Is there any actual interest for a botany plant that just shoots at zombies or something similar that will be a part of the game in general instead of just an admeme? If not I'll just close the commit due to what sloth says.
> 
> to be fair that sounds kind of funny

[boy do I have the game for you](https://en.wikipedia.org/wiki/Plants_vs._Zombies)

**Comment by UbaserB** [comment]
> > > Is there any actual interest for a botany plant that just shoots at zombies or something similar that will be a part of the game in general instead of just an admeme? If not I'll just close the commit due to what sloth says.
> > 
> > 
> > to be fair that sounds kind of funny
> 
> [boy do I have the game for you](https://en.wikipedia.org/wiki/Plants_vs._Zombies)

i mean, for ss14 lol

**Comment by K-Dynamic** [comment]
> Is there any actual interest for a botany plant that just shoots at zombies or something similar that will be a part of the game in general instead of just an admeme? If not I'll just close the commit due to what sloth says.

I mean it would mean more content for botany and unexpected defence against zombies

**Comment by nikthechampiongr** [comment]
I guess I'll close this for now. A new plant probably needs more discussion than a half dead comment section on github.

**Pull request closed without merging**
