### PR TITLE
Emergency crowbar sprite

### PR DESCRIPTION
**Pull request by TyAshley**
## About the PR

The emergency crowbar description says they are a pocket crowbar. I added a new sprite that shows it as folded when stored. Because why else are they special?!

## Why / Balance

A folded sprite makes it simple to know why this crowbar is different from other crowbars. I also corrected the description on the yellow/engineering crowbar.

## Technical details

Added new folded sprites for the emergency crowbar and a new version of the unfolded crowbar cover with a hinge.

## Media

image
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Allen
- add: Added a new "folded" sprite to emergency crowbars when stored
- tweak: Corrected the yellow/engineering crowbar description to remove "pocket"

### CODE REVIEW

**Comment by DieselMohawk** [comment]
Looks cool, good work

**Comment by UbaserB** [comment]
the yellow crowbar was never meant to be foldable, it was just me copy pasting the wrong thing. The red crowbar was also edited to no longer be able to be placed in pockets in #30939 but I'll check in with the other maintainers first. In the meanwhile just remove the yellow crowbar part.

**Comment by TyAshley** [comment]
I removed the ability to fold the engineering crowbar and changed the description to remove references to being a pocket crowbar

**Comment by slarticodefast** [comment]
Thank you for your contribution. I discussed this with the other maintainers and we came to the conclusion that all crowbars should be identical. The reason for this is that we have hand-prying for airlocks now, so a pocket variant is no longer needed. The alternative PR #30939 has been merged instead.

**Pull request closed without merging**
