### PR TITLE
Serialization v3 content PR

### PR DESCRIPTION
**Pull request by PaulRitter**
Requires https://github.com/space-wizards/RobustToolbox/pull/1606

[WIP hackmd doc](https://hackmd.io/@ss14/serialization)

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
[WIP hackmd doc](https://hackmd.io/@ss14/serialization)

**Review by Zumorica — APPROVED** [review]
Absolutely flawless.

**Review by SweptWasTaken — APPROVED** [review]

**Comment by SweptWasTaken** [comment]
I can't see a single thing wrong with it!

**Comment by Acruid** [comment]
BUG FREE AND AHEAD OF SCHEDULE

**Review by DrSmugleaf — APPROVED** [review]
The code is hamster.

VPl1P8B (1)

**Pull request merged**
