### PR TITLE
New Spawnable Map: Boarding Shuttle Dart

### PR DESCRIPTION
**Pull request by LittleBuilderJane**
## About the PR 
Made a rather small boarding shuttle called Dart, it has a bridge, tiny medical closet, an armory stocked with weapons and hardsuits and a small Engineering with generators, air tanks and such.
**Screenshots**

Dart Screenshot
**Changelog**

:cl: Schiene
- add: Added a spawnable Boarding Shuttle map called Dart, comes with a small force equipped for Vacuum with heavy weaponry.

### CODE REVIEW

**Comment by Mith-randalf** [comment]
No gravity?

**Comment by LittleBuilderJane** [comment]
> No gravity?

It's small enough that Gravity both doesn't fit and isn't needed, every room is so small you can float around without any issues or getting stuck on. Besides it's meant as a boarding shuttle anyways, the Sec force is meant to board the station. (It's Sec force now because it's more a template for an ERT or the nukies or whatever like that.)

**Comment by SweptWasTaken** [comment]
Embedded Screenshot

Dart Shuttle

**Comment by metalgearsloth** [comment]
Seems unpowered in-game unless I did something wrong?

**Comment by LittleBuilderJane** [comment]
> Seems unpowered in-game unless I did something wrong?

Unless the wiring broke itself between updates, it should absolutely be working, the generators are wired to the SMES, which are wired ot the Subbie, which itself is wired to the rest of the shuttle.

**Review by metalgearsloth — COMMENTED** [review]
One thing I don't like from some of our maps:
image

for 2 reasons:
1. It's hard to discern what is there without right-click
2. These should probably be in boxes in case something explodes and decides to send a few dozen physics bodies flying. This on its own isn't bad but should be avoided where possible.

**Pull request merged**
