### PR TITLE
Command glasses

### PR DESCRIPTION
**Pull request by Ghagliiarghii**
## About the PR

Special sunglasses for command personnel (captain, HoP, visiting centcom people, maybe others). I like the quality of life of being able to see job icons as a Borg / security and think it would be very helpful for captain and HoP (especially with the HoP job revolving around dealing with IDs and therefore in part job icons). However, in recent discussions it's clear that the overwhelming consensus is that Captain and especially HoP should not be validhunting and the wanted status is not job relevant information. After https://github.com/space-wizards/space-station-14/pull/26207 icons can now be separated such that it's possible to provide job icons without criminal status, which I think is a good balance for this item.

To acquire this item, it is a starting item for captain and HoP, but I also added this to the centcom drobe vending machine to be consistent with my adding it to the visiting centcom official, I added it as a very rare item in the cargo bounty crate (although I'm not attached to this and would be willing to remove it as a method of acquisition), and I added it as a 2 steel 3 glass recipe in the Sec Lathe in case Captain loses his since security would need to be consulted to obtain it this way and they already have universal access to the sec glasses, which are a strict mechanical upgrade. (Some captains may like the drip and be willing to forgo a little powergaming this way).

## Why / Balance

Good for quality of life
A fun / stylish item

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added stylish new glasses for the Captain and Head of Personnel! :sunglasses:

### CODE REVIEW

**Comment by KingOnBudget** [comment]
such a cool PR

**Comment by superjj18** [comment]
Good compromise between the "command should be able to see roles and quickly notice suspicious discrepancies" and "command shouldn't hunt for baddies"

**Comment by EmoGarbage404** [comment]
@superjj18 feel free to word future criticism or praise while restraining from being needlessly antagonistic to people that disagree with you.

**Comment by superjj18** [comment]
> @superjj18 feel free to word future criticism or praise while restraining from being needlessly antagonistic to people that disagree with you.

Apologies, edited it out

**Comment by EmoGarbage404** [comment]
The general consensus is to deny this PR.

The produced reason of "quality of life" is not a valid one for adding additional gear and utility to players' base equipment. I'll elaborate a bit more on the rest of it though.

Generally, being able to see the job icon is a pretty dramatic nerf to character's who are attempting to conceal their identity or use someone else's PDA. Being able to so readily identify them with a HUD isn't something that should be extending past security in typical circumstances.

There's also the issue of viewing mindshield status. While this only currently extends to revs, this could very easily apply to numerous gamemodes in the future and is definitely worth looking at. Being able to quickly discount someone from being an antagonist can lead to quickly quelling snowballing antags without good cooperation. The process of distributing sechuds to people on a when-necessary basis is a beneficial one that adds cooperation to antagonist scenarios.

Thank you for your contribution. Due to the reasons stated above, I'm opting to close your PR. Feel free to contribute in the future. 

Thank you.

**Pull request closed without merging**
