### PR TITLE
Add space lube tube

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

**Media**

Peek 2023-06-16 22-48

**Changelog**

:cl:
- add: added space lube tube - use it on items to make them slip out of hands!

### CODE REVIEW

**Comment by Slava0135** [comment]
i am still not sure how to properly add prefix to an item (also see #17381)

**Comment by Yousifb26** [comment]
What about the nuke disk? I’m sure someone will do it at some point

**Comment by Slava0135** [comment]
> What about the nuke disk? I’m sure someone will do it at some point

It will be funny

**Comment by deltanedas** [comment]
new cap meta lube dat fukken disk so nukies cant use it

**Comment by Slava0135** [comment]
Just to make things clear - lubed items will slip next X times you pick them up (X is random but depends on amount of lube)

**Comment by Slava0135** [comment]
changed tube sprite back to white as it was quite awful. Still can't really see contents
image

**Pull request merged**
