### PR TITLE
Intercom buffs and fixes

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

- updates intercoms to work with encryption keys
- makes intercoms not require tcomm servers (handheld radios got fixed too)
- update ui state handling to modern standards (prediction)
- changes sprite to new rotation standards
- fixes the panel being unshaded for some reason

## Why / Balance

Intercoms are basically worthless if they rely on tcomms. The whole tradeoff with a fixed radio is that its always reliable. It being unreliable defeats the point.

## Technical details

adds a new TelecomExempt component that handheld radios and intercoms use.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

If you have custom telecoms, you need to update them to use encryption keys.

**Changelog**

:cl:
- tweak: Intercoms now use encryption keys to determine what channels they can broadcast on.
- fix: Intercoms and handheld radios no longer rely on telecom servers.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
> Isn't the point of intercoms to give people who aren't apart of a department access to that department's channel for things like reporting crimes, calling for med to open the door, or just generally when people aren't at the front desk? 

it can be both. External department radio access is good but not really useful enough to justify mapping them all around. Especially for departments where you already have a front desk.

> Also this could be a problem with that one salvage wreck that has 3 intercoms with all channels, which isn't usually a problem since you can't move intercoms or reconstruct them with more than common channels.

someone should go fix the salvage wreck then.

**Comment by lzk228** [comment]
i think media is required for this pr

**Comment by slarticodefast** [comment]
Can the encryption keys be removed from the intercom? If yes, wouldn't that make stealing keys way too easy? Just walk up to an intercom in front of a department and take it apart with a screwdriver.

**Comment by EmoGarbage404** [comment]
Add support for security panels. You can now weld in a sheet of steel just like you can for airlocks. Security intercoms have this by default.

**Comment by slarticodefast** [comment]
> Add support for security panels. You can now weld in a sheet of steel just like you can for airlocks. Security intercoms have this by default.

Sounds like a good solution. Maybe do the same thing for the command intercom?

**Comment by SlamBamActionman** [comment]
> > Isn't the point of intercoms to give people who aren't apart of a department access to that department's channel for things like reporting crimes, calling for med to open the door, or just generally when people aren't at the front desk?
> 
> it can be both. External department radio access is good but not really useful enough to justify mapping them all around. Especially for departments where you already have a front desk.

Maintainer, meet Front-Desk-Is-Empty.

Stations that lack publicly available intercoms can be such a pain if you're trying to get in touch with e.g. Cargo and the lone Cargo Tech is currently hunting soap on the other side of the station. By all means this PR is good but let's not discount what people actually use intercoms for.

**Pull request merged**
