### PR TITLE
Sec Webbing Icon Resprite and Rename

### PR DESCRIPTION
**Pull request by DieselMohawk**
## About the PR
 Resprited the Icon to support belt overlay and renamed it to Security Rig. Added proper copyright.

## Why / Balance
 Remade this PR to add overlay support since players preferred having overlay than having it be removed. Also the name no longer fits as the sprite was changed.

## Media

image
New sprite with belt overlay.
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Catdere** [comment]
spooky that there's no comments on this

**Comment by DieselMohawk** [comment]
Please don't call my empty PR comment section spooky. It's just like that.

**Comment by MissKay1994** [comment]
I was directed here to this, because I had feedback. The old sec webbing was a load bearing vest, and the new sprite in a load bearing carrier. Really from my knowledge of the various different load bearing equipment, the sec gear with the new sprite should be called "Security Carrier" in my opinion since that's what it is

**Comment by DieselMohawk** [comment]
> I was directed here to this, because I had feedback. The old sec webbing was a load bearing vest, and the new sprite in a load bearing carrier. Really from my knowledge of the various different load bearing equipment, the sec gear with the new sprite should be called "Security Carrier" in my opinion since that's what it is

I'm fine with that, good catch.

**Pull request merged**
