### PR TITLE
Slug shell buff

### PR DESCRIPTION
**Pull request by Jackal298**
Shotgun Ammo .50 Slug Upgrade

## About the PR

I wanted to improve the .50 slug cartridge to be more appreciated, the cartridge now fully justifies the name, this is one bullet with 35 piercing damage

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: .50 slug cartridge now fires one projectile with 35 piercing damage

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This just makes it a revolver? Its not a shotgun shot if its a single pellet with normal spread.

**Comment by Jackal298** [comment]
> Это просто делает его револьвером? Это не выстрел из дробовика, если это одиночная пуля с нормальным разбросом.
add scatter?

**Comment by Jackal298** [comment]
> This just makes it a revolver? Its not a shotgun shot if its a single pellet with normal spread.
i can add a little scatter

**Comment by EmoGarbage404** [comment]
It should still be multiple pellets. Making it four 10 damage pellets instead of four 8 damage pellets would accomplish the same task while retaining the unique aspect of the shotgun.

**Comment by Jackal298** [comment]
> It should still be multiple pellets. Making it four 10 damage pellets instead of four 8 damage pellets would accomplish the same task while retaining the unique aspect of the shotgun.

why then was this cartridge called a slug if it works like a fraction?

**Comment by Emisse** [comment]
slug shells are meant to be solid stop asking to make it pellet
this does a bit too much damage for one shot

**Comment by Jackal298** [comment]
> slug shells are meant to be solid stop asking to make it pellet this does a bit too much damage for one shot

can i do 34 damage?

**Pull request closed without merging**
