### PR TITLE
makes nymphs wearable

### PR DESCRIPTION
**Pull request by Doctor-Cpu**
## About the PR

Diona nymphs can now be picked up and placed on a players head.

## Why / Balance

Makes it more inline with other small creatures and it looking cute.

## Technical details

N/A

## Media

https://github.com/space-wizards/space-station-14/assets/77215380/008a96df-4fe3-4c29-b2b6-e2940ebad87f

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

:cl:
- add: diona nymphs are now able to be picked up and worn

### CODE REVIEW

**Comment by Doctor-Cpu** [comment]
https://github.com/space-wizards/space-station-14/assets/77215380/0ec35621-ed21-4cd8-bc02-335bccd37248

Currently reforming causes you to be parented? Not to sure how to describe it.

Wondering if i should outright disable reforming while held/worn or fix the issue.
Reforming stuns you in place but someone can just pick up the nymph while they are reforming, so I could see this being abused if the diona was a traitor.

**Comment by CatMagic1** [comment]
inevitable

**Comment by Cojoke-dot** [comment]
I like it but I see the issues brought up with it being a player. You could make it take a very short time to escape from the player to counteract the issue of being picked up. Dionia being able to be picked up without the shorter timer is also a good idea. It allows for more syndicate interactions of capturing people rather than just killing the Dionia and stabbing the nymph 3 times.

 I also think that it should go on the... cloak slot? I don't know what its position is called but whatever slot cloaks and ties go. The Dionia itself is resting on your shoulders, so I think it would fit much better in the other slot.

**Comment by IProduceWidgets** [comment]
Unhinged ideaguys solution: Ever seen that movie Mummy? Let them do that awful scarab thing if you pick em up. 

https://youtu.be/GJP8XTzpOCw

**Comment by Doctor-Cpu** [comment]
> I also think that it should go on the... cloak slot? I don't know what its position is called but whatever slot cloaks and ties go. The Dionia itself is resting on your shoulders, so I think it would fit much better in the other slot.

I thought about it but it may seem counter intuitive with all the other animals going on the head, so I could see many first trying the head slot.

> I plan to work on a system that allows pets to be picked up with a short doafter eventually (so it can avoid being picked up if it doesn’t want)
Have you started on this? If not I could have a look at adding such. For now I've just reduced the escape duration.

**Comment by potato1234x** [comment]
make the escape from inventory doafter 0 seconds and this'll be the best pr of 2024

**Comment by metalgearsloth** [comment]
See lank's comment

**Comment by Doctor-Cpu** [comment]
I did start work on implementing the pickup doafter and never updated the pr description but ran into issues with vv and just lack of time.
Unless I'm totally misunderstanding their comment then just ignore this comment.

**Comment by ThanosDeGraf** [comment]
With #39505 merged, could this be re-opnened (with lank's feedback)?

**Pull request closed without merging**
