### PR TITLE
Ninja Dash Attack

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

The ninja dash ability now deals 30 slash(ignores armor) to fulfill all your deepest ninja desires
## Why / Balance

Seems like a fun thing to add. It would function as an entrance or a finisher due to the sword not having many charges and people having to line up in order to hit more than one.
## Technical details

Creates a raycast between the start and finish point that only detects objects that are Opaque(so it does not break windows).
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/556707fd-cee1-4a47-bec0-75ef8ae5cc92

*Note: The character that got crit in the video had damage before the ability was used for cinematic effect
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Ninja dash ability now deals damage to anyone in its path

### CODE REVIEW

**Comment by GroggleG** [comment]
1. gives ninja a free 30 damage at no expense
2. Not faithful to the original
I think its fucking cool but this simply isnt balanced nor accounting for the unadded features.

**Comment by Cojoke-dot** [comment]
> 1. gives ninja a free 30 damage at no expense

Thats how much the ninja sword does... and it costs a movement charge, I could remove the armor pierce if that's too powerful

**Comment by GroggleG** [comment]
> > 1. gives ninja a free 30 damage at no expense
> 
> Thats how much the ninja sword does... and it costs a movement charge, I could remove the armor pierce if that's too powerful

it may cost a movement charge its that its simple too OP, we still dont have the ninjas stim injector, net, and borg convert, this would be too much mate.
Sick ass idea its just not in the cards

**Comment by thebadman4662** [comment]
AOE + stun + damage + armor pierce?

Damn, would be shame if ninja jumped into medbay and in few clicks crit everyone. :trollface:

**Comment by ARMOKS** [comment]
> ## About the PR
> The ninja dash ability now deals 30 slash(ignores armor) to fulfill all your deepest ninja desires
> 
> ## Why / Balance
> Seems like a fun thing to add. It would function as an entrance or a finisher due to the sword not having many charges and people having to line up in order to hit more than one.
> 
> ## Technical details
> Creates a raycast between the start and finish point that only detects objects that are Opaque(so it does not break windows).
> 
> ## Media
>  2024-06-13.18-03-40.mp4 
> 
> *Note: The character that got crit in the video had damage before the ability was used for cinematic effect
> 
> * [x]  I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> **Changelog**
> 
> 🆑
> 
> * tweak: The Ninja dash ability now deals damage to anyone in its path

Absolutely incredible change, more antag content is a great thing. I think the reason people are upset at this is because no one really knows ninjas weaknesses with how rare they are

**Comment by GroggleG** [comment]
> AOE + stun + damage + armor pierce?
> 
> Damn, would be shame if ninja jumped into medbay and in few clicks crit everyone. :trollface:

exactly my point, I love ninja engagement as it is NOT a finished antag but this removes the whole point of being a glasscannon stealth duelist, its just not a good idea in practice but is a SICK ASS idea

**Comment by GroggleG** [comment]
> Absolutely incredible change, more antag content is a great thing. I think the reason people are upset at this is because no one really knows ninjas weaknesses with how rare they are

thing is it is the antithesis of what ninja is supposed to be, I just cant fw this change because
1. goes against the ninja design philosophy
2. a big chunk of ninjas kit is STILL not in the game

**Comment by Cojoke-dot** [comment]
> 1. goes against the ninja design philosophy

How? Its a finisher move for people running away for the ninja, it's even in the ss14 trailer(kinda).

> 2. a big chunk of ninjas kit is STILL not in the game

Then this ability can be balanced when they do get added or the other stuff can be balanced around this

**Comment by GroggleG** [comment]
> How? Its a finisher move for people running away for the ninja, it's even in the ss14 trailer(kinda).

To break ninja down into the most basal archetype they are a Glasscannon Stealth Duelist, They are meant to be squishy with mobility, meant to AVOID combat, and meant to focus on 1v1s, adding an ability that is literally  a hotkey and a toolbelt pull away that as far as I see has AOE and armor piercing goes against this

> Then this ability can be balanced when they do get added or the other stuff can be balanced around this. Balancing stuff around "someone going to add it at some point" is not a valid way to go about combat when ss14 has a different combat system from 13.

You truly dont understand, when I say ninja is unfinished I mean that the amount of abilities are specifically to the point where adding more just makes ninja too powerful, and the arguement of 14 being drastically different is not valid because from experience the translation is smooth enough to where that is trivial
Ninja

**Comment by Cojoke-dot** [comment]
> To break ninja down into the most basal archetype they are a Glasscannon Stealth Duelist, They are meant to be squishy with mobility, meant to AVOID combat, and meant to focus on 1v1s, adding an ability that is literally a hotkey and a toolbelt pull away that as far as I see has AOE and armor piercing goes against this

Hit 2 people instead of one... incredible aoe, its almost like if you stun one person, the other person can just shoot over them to hit you. I'll probably remove the armor piercing, I put it in there so the ninja could end fights faster and get away before engaging again.

> You truly dont understand, when I say ninja is unfinished I mean that the amount of abilities are specifically to the point where adding more just makes ninja too powerful, and the arguement of 14 being drastically different is not valid because from experience the translation is smooth enough to where that is trivial

I mean... they already had one of the items on that list and it got removed, the ninja had a microbomb implant before. You assume that the systems are going to be the same as ss13, but again, its not the same game when it comes to balancing.

**Comment by GroggleG** [comment]
> Hit 2 people instead of one... incredible aoe, its almost like if you stun one person, the other person can just shoot over them to hit you. I'll probably remove the armor piercing, I put it in there so the ninja could end fights faster and get away before engaging again.

That actually is, I literally said that the focus is on ninja being a duelist, I appreciate sarcasm but im trying to explain to you that one of the things that keep ninja going from midround nuisance to murdermachine is his inability to handle anything higher than 1v1s.

> I mean... they already had one of the items on that list and it got removed, the ninja had a microbomb implant before. You assume that the systems are going to be the same as ss13, but again, its not the same game when it comes to balancing.

the game is in EA and is currently playing with things, its not the same game due to heavily leaning into combat due to a tweaked movement system, the simple fact is that of course things arent going to be 1:1 but that doesnt mean things in ss13 werent the way they were for a reason, please consider that ss13 has had 15 years to develop since the first true decompiling and that 14 is still getting its sealegs.

**Comment by mirrorcult** [comment]
> 
> thing is it is the antithesis of what ninja is supposed to be, I just cant fw this change because
> 
>     1. goes against the ninja design philosophy
> 
>     2. a big chunk of ninjas kit is STILL not in the game

largely agree with this, ninja already has the best melee in the game and excels at close combat stuff, it doesnt need to have a pseudo ranged option that just powercreeps even harder, i dont think 'its cool ninja move' is enough justification

**Comment by deltanedas** [comment]
the raycast thing could maybe be reused for a visual effect like a laser from start to end

**Comment by GroggleG** [comment]
> the raycast thing could maybe be reused for a visual effect like a laser from start to end

Honestly want a PR for the Ninja dash trail, would be peak

**Comment by Cojoke-dot** [comment]
> Honestly want a PR for the Ninja Dash trail, would be peak

A friend suggested that to me when I opened the PR. I like the idea, the issue I have with it is that it would make it easier to chase the ninja after they attempt to disengage. Did they have a trail in ss13?

**Comment by GroggleG** [comment]
> > Honestly want a PR for the Ninja Dash trail, would be peak
> 
> A friend suggested that to me when I opened the PR. I like the idea, the issue I have with it is that it would make it easier to chase the ninja after they attempt to disengage. Did they have a trail in ss13?

yes, the point is to make a ninja easier to spot when being risky/being caught escaping, a ninjas stealth is only as good as their tactical stealth, I promise you work on the stuff mentioned earlier in this PR and itll get added gleefully.

**Pull request closed without merging**
