### PR TITLE
New mid pop station: Loop

### PR DESCRIPTION
**Pull request by TytosB**
## About the PR

added a new mid pop map, loop station

features a centrally located medical and security department, so sec and quickly react to a threat anywhere and any injured person is never too far from medical

a fully modular main power set up with only the lattice structure and wires pre-built, all parts as flatpacks to allow engi to quickly and easily set up power however they please

a main 'loop' hallway that wraps around med and sec and connects all other departments

a large open main plaza area directly connected to arrivals and service.

## Why / Balance

i think more variety is always good, as long as maps are maintained, and i have every intention of maintaining this one. beyond that, i've always wanted to make a map that added a lot of what i feel are 'common sense' features, such as a centrally located sec and med, a more flexible power setup, and a map with a single main transit loop that allowed for easy and intuitive understanding of how to get around.

## Technical details

branch is keeping up to date with main branch

## Media

NT-14 Loop Station xnz-87

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: TytosB
- add: added new mid pop map: loop station

you can also message me on discord @tytosblackwood

### CODE REVIEW

**Comment by thebadman4662** [comment]
Nice brigmedbay. me likey. Sec even gets jetpacks! Hallways also look good on airlocks to prevend dumb atmos loss. Bar entrance firelocks could use being moved a back a bit by two tiles or so

Sec:
- Brigmed looks like it lacks fire alarm, unless its all connected to main security one
- Same with interrogation.
- Do cells have distro vents under beds or lockers? Usually tiny rooms at least get distro, often cells have both that and scrubber but basically never air alarm for it to work properly.

Sci: 
- I see scrubber sec checkpoint but no air alarm.

Bridge:
- Vault(?) air alarm seems to be sideways? Or its cap room one? Both? Do you need door open to be able to access it?

Dorms:
- Toilets seem to lack air alarm.

Med, engi, cargo, service, gucci. 

Can't wait to play it, seems like a great map!

**Comment by 1TALERD** [comment]
IMG_20241125_100906_677

**Comment by superjj18** [comment]
Yeah ai is WAAAAAAY too insecure.  It would take a dude with a RCD and wire cutters less than 30 seconds to essentially round end the ai

**Comment by thebadman4662** [comment]
> Yeah ai is WAAAAAAY too insecure. It would take a dude with a RCD and wire cutters less than 30 seconds to essentially round end the ai

I thought its map feature/quirk to have easily removable AI, just like some maps have ridiculously easy to break out permas.

**Comment by TytosB** [comment]
> Yeah ai is WAAAAAAY too insecure. It would take a dude with a RCD and wire cutters less than 30 seconds to essentially round end the ai

as badman said, AI sats being easy to disconnect with an rcd is pretty common in a lot of maps. Bagel, Box, Marathon, Meta, and Omega all share this feature to some extent. and id argue my AI is actually slightly more secure, since its right in front of the bridge, meaning its easier to catch and stop someone doing this before its too late.

**Comment by TytosB** [comment]
> Nice brigmedbay. me likey. Sec even gets jetpacks! Hallways also look good on airlocks to prevent dumb atmos loss. Bar entrance firelocks could use being moved a back a bit by two tiles or so
> 
> Sec:
> 
>     * Brigmed looks like it lacks fire alarm, unless its all connected to main security one
> 
>     * Same with interrogation.
> 
>     * Do cells have distro vents under beds or lockers? Usually tiny rooms at least get distro, often cells have both that and scrubber but basically never air alarm for it to work properly.
> 
> 
> Sci:
> 
>     * I see scrubber sec checkpoint but no air alarm.
> 
> 
> Bridge:
> 
>     * Vault(?) air alarm seems to be sideways? Or its cap room one? Both? Do you need door open to be able to access it?
> 
> 
> Dorms:
> 
>     * Toilets seem to lack air alarm.
> 
> 
> Med, engi, cargo, service, gucci.
> 
> Can't wait to play it, seems like a great map!

fixed most of this today, just having some issues with painting the new map for some reason

**Comment by SlamBamActionman** [comment]
These are all personal thoughts from a person who has only made a single map so take anything I say with a grain of salt. These are just things I got from a first sweep, but overall I think the general shape of the map seems interesting.

image
The middle maints corridor is cool, but it does suffer from being very straight. It's a long sightline you can fire down. Consider not making the medbay wall not be a straight line so that you can introduce some sightline breakers. 

image
This 5-wide area is meant to be Cargo's reception area, but it doesn't feel like such. Consider adding tables or some other things to fill up the space to make it less empty. 

image
This airlock configuration looks strange - I would try to avoid mixing vertical and horizontal lines.

image
Move the AI out from the wall and make it have a secondary containment, the room has space for it. Otherwise you can get in to minibomb it with a single C4.

image
Area doesn't look like it's properly finished here?

image
There's a lot of these long lines of firelocks in several places on the station and I am not a fan. It makes for big walls when they come down and the way this one just seems to cut through Command in particular feels off. Consider breaking up the firelock lines with some walls/windows.

image
Add a cheeky lil airlock from the external entrance into the cult room, otherwise that corridor becomes a boring dead end.

image
Nicer to make this into thin windows/windoors, otherwise the room ends up looking super tiny. 

image
I don't know why but I really like this waiting setup.

image
I'd move this wall up one tile to make the borging room a little bit less cramped.

image
Maints access on these would be nice.

**Comment by TytosB** [comment]
i had some technical issues with the latest push and couldnt figure out how to fix it, so i ended up having to make a new pr, located here: https://github.com/space-wizards/space-station-14/pull/33697

**Pull request closed without merging**
