### PR TITLE
Adds RPG to nukie planet (and syndicate airlocks)

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

an RPG 7 with one spare round was added to the nukie planet, and while I was there I added syndicate airlocks, a military style breath mask to the medical section and accidentally moved the syndicate pAI and fake nuke disk

I may add syndie airlocks to the nukie shuttle in a later PR

## Why / Balance

the RPG only has two shots (one in the weapon at the start and one spare, weighs 60 and does not destroy reinforced walls, so its only good for into areas like cargo or evac or just anywhere that does not have reinforced walls, the maximum it can deal with are reinforced windows.

it's also fun

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: JoeHammad
Add: The nukie planet now has a free rocket launcher for exlosive entry and explosive fun!
Tweak: The nukie planet now has syndicate airlocks

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Remove the gamer gear and don't omit CLs.

**Comment by JoeHammad1844** [comment]
by gamer gear do you mean the rocket launcher?

**Comment by metalgearsloth** [comment]
> by gamer gear do you mean the rocket launcher?

Yes. You should also try to work on more content prs for the game rather than trying to powercreep balance in a bunch of areas e.g. hristov buff prs, access buff prs, extremely cheap borgs, paramedic buff etc, especially when we're still in playtest as it is unnecessary maintainer work.

**Comment by JoeHammad1844** [comment]
> Yes.
The RPG can not destroy reinforced walls, which of course the armory is made out of, the strongest thing it can destroy in one shot are reinforced windows, probably the most powercreepy/gamey way you could use it is using it as a two use china lake. 

the intention for it is to blow open walls from outside the station and use that as an entry point, such as screwing up cargo.

**Comment by JoeHammad1844** [comment]
damn it got closed as I was typing

**Pull request closed without merging**
