### PR TITLE
Removes cockroach/mothroach melee damage

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Reduced their damage to 0

## Why / Balance

I'm sick and fucking tired of mothroaches every other shift coming into med and (previously) spilling the jugs and (now) biting the fuck out of the jugs for absolutely ZERO reason. It is the worst fucking ghost role offender of this shit and cargo just buys so many of them.

This makes them in-line with mouses.

## Technical details

restate MeleeWeapon comp, remove the damage

## Media

https://github.com/user-attachments/assets/fb93c003-5bd7-46ff-8ac3-aa4335cce33b

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Cockroaches and mothroaches can no longer damage things with their bites.

### CODE REVIEW

**Comment by ArtisticRoomba** [comment]
Yeah, I thought they were given the bite with zero damage to begin with, seems not.

Btw this change allowed mothroaches to damage and kill dragons from the inside. They would dismount from the devoured person's head or escape from their bag and just kill the dragon.

**Comment by MilenVolf** [comment]
They were given combat mode just for rotating dancing...just like Hamlet. The author of this change just forgot about setting damage to 0.

**Comment by 7-62x54r** [comment]
just place mousetraps in med or close the chem fridge, jesus, actual skill issue repelling shitters playing as weakest antag

**Comment by ArtisticRoomba** [comment]
They were originally given the damage ability for funny spin but The Mothroach Vs. Space Dragon incident makes it obvious that this is a problem

Also a little gremlin spilling 30+ minutes worth of work really just sours the game for everyone

Medical isn't going to place mousetraps everywhere to get back at that _one_ mothie spilling all the chems and darting between tables damaging patients

**Comment by thebadman4662** [comment]
> just place mousetraps in med or close the chem fridge, jesus, actual skill issue repelling shitters playing as weakest antag

Mothroaches kill whole engineering deparments(sic!) so I would not exactly call them weakest, being able to attack from under stuff while being fairly tanky for lil shit is pretty strong, though if you let someone grab you, you can lose good chunk of that health if not all.

**Comment by slarticodefast** [comment]
Live admin reaction:
dame-da-okay-dame-da-ne-guy

Makes them consistent with mice and prevents griefing. Good PR.

**Pull request merged**
