### PR TITLE
nerf hristov

### PR DESCRIPTION
**Pull request by Emisse**
takes it down from being a taser to a respectable large caliber sniper rifle. still does a lot of stamina damage so it can knock people down or slow them a lot

🆑 
- tweak: Hristov no longer insta stuns and does slightly less damage.

### CODE REVIEW

**Comment by LankLTE** [comment]
Maybe buff the firerate a little since it was made abysmally slow to account for the stun

**Comment by Emisse** [comment]
no because its still a 2 shot kill

**Comment by Emisse** [comment]
2 shots will also stun armored targets

**Comment by LankLTE** [comment]
ok

**Comment by Emisse** [comment]
thats not implemented

**Comment by LankLTE** [comment]
> thats not implemented

Yes it is? .45 AP uses it fine

**Comment by Emisse** [comment]
yes but this ammo doesnt

**Comment by asperger-sind** [comment]
> yes but this ammo doesnt

Either I dont understand how this works or you're wrong and ammo does ignore armor because of the `ignoreResistances: true`

**Comment by Emisse** [comment]
nah im wrong i need to nerf it a bit more

**Pull request merged**
