### PR TITLE
Bagel Update 13

### PR DESCRIPTION
**Pull request by Emisse**
Bagel station was my first map I made for ss14 and it shows in a lot of the design. It has been updated significantly and many parts of the map were deleted and remade from scratch. The general layout and feel will be the same but you'll notice it's very different.

changelog
-the bridge has been remade with a mostly similar layout but with improvements to its shape and overall design.
-security has cannibalized R&D and takes up the entire block now. the prison is based off the 18th century design of the panopticon. perma has been moved into central bagel. 
-science now occupies the westmost quadrant and is fit with R&D, robotics, toxins, artifact research, and a proper office for RD.
-the northern part of the map has been completely redone from scratch. atmos has been separated from engineering and put to the northwest. engineering is now much more spacious but all power sources are a lot closer together. this makes the threat of singulo a lot greater again. supermatter room connects atmos and engi but is unused for now. atmo takes after the marathon atmos design and should feel a lot better and less cramped than old bagel's.
-the chapel and dorms have been shifted southwest of their previous location.
-arrivals now has several connecting maints so people wont be cutoff from the rest of the station if something ahead is spaced
-bar now sports shutters and firelocks so the tenders dont get obliterated from bar bombings
-botany has been reorganized and now has a tool room
-chem has been scrunched up
-medical has received an overall touchup focusing on minimizing the massive lobby and putting more emphasis on patient care and doctor safety.
-cargo has been shortened significantly (sorry i was told to) and salvage now sits above the cargobay. the ore processor sits in the wall between them.
-evac has been modified for evac shuttle
-grav gen is now connected to the main portion of bagel but is in a similar location
-theater has been moved to be right above the bar.
-libraries layout has changed but still sports a DND table
-atmos is fully equipped gas wise. (gotta rip the bandaid off some time)
-hop bedroom has been shrunk and office expanded
-all heads of staff now have a proper desk to talk to employees at
-significantly reduced amounts of lights on map and in maints especially

ill now provide some candid photos
bridge
image
perma
image
the panopticon
image
toxins and R&D
image
cargo lobby
image
engineering
image
atmos front desk
image
botany and chem
image
left half of medbay
image
theater above the bar
image

i hope you guys enjoy the update as much as i did making it

### CODE REVIEW

**Comment by moonheart08** [comment]
bagelstation-0

**Comment by lapatison** [comment]
Window to grav-gen room have no grille.

**Comment by moonheart08** [comment]
Might be a bit too easy to break into gravgen and the HoS office.
Morgue is a bit too thin, little walk room, but it's likely fine.

**Comment by Emisse** [comment]
gravgen is about the same level of fortified as marathon and packed except now its even closer to sec, morgue i can definitely expand rn. i dont see why people would break into hos room personally unless they havent spawned and taken their weapon yet so i dont think thats a big deal in most cases, lemme expand morgue tho

**Comment by moonheart08** [comment]
image
Are these functional. Trit miner doesn't make sense, plasma is questionable but honestly worth a shot I guess?

**Comment by Emisse** [comment]
logic here was that we have to re add these at some point so might as well rip the bandaid off now that we have atmo techs

**Comment by moonheart08** [comment]
Plasma's good. Trit can simply be made.

**Review by moonheart08 — APPROVED** [review]

**Pull request merged**
