### PR TITLE
Toxin damage tweak

### PR DESCRIPTION
**Pull request by ProPandaBear**
Toxin is mostly useless at it currently stands and the mostly useless emag is even more useless in chemistry as several chemicals are equally effective without the use of an emag. This should make toxin slightly more appealing while not being overpowered. At 4 poison per unit, a 20u pill should crit whoever consumes it while still providing ample time to be rescued before death.

Edit: Reverted name change of toxin. After futher review, Toxin has a widespread and multifaceted use that "Cyanide" doesn't fit.
**Media**

* [x]  I have added screenshots/videos to this PR showcasing its changes ingame, or this PR does not require an ingame showcase

**Changelog**

🆑

Tweak: Increased toxin poison damage from 2 to 4.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Please stop re-opening PRs.

**Comment by ProPandaBear** [comment]
Apologies, I'm having an actual stroke over here.

**Comment by Interrobang01** [comment]
Good PR. Might want to change the ID too, for consistency -- correct me if I'm wrong, but the only two places toxin is referenced is in the chemical dispenser when emagged and in the recipe for Plant-B-Gone, so you'd just have to make changes in those two spots.

Also, Cyanide tastes burny, acrid, and bitter, and (if you have the correct genetic trait) smells like almonds (it doesn't taste like almonds, though). It could add some more, ah, flavor, to change the taste and description to accommodate.

You should probably flag this PR as a fix to #15494.

Changelog looks a little off, there's supposed to be a 🆑 emoji at the bottom, plus some formatting. Not really personally sure how the autoCL works, though, so I can't really advise.

Anyways, I think the damage change is right at where it should be.

**Comment by Myakot** [comment]
I honestly think this'd change nothing. Damage is fine and all that, but chemicals really do need "flavour".

How about adding some lines for actual cyanide side-effects? Nothing substantial, just to start making poisons actually unique from one to another.
- "Your chest tightens"
- "You feel dizzy"
- "Your breathing is ragged"
- "You feel wondrous and dead at the same time"
- etc.

**Comment by Interrobang01** [comment]
>but chemicals really do need "flavour".

I mostly agree with all this, although seeing as there are only a half dozen chemicals with popup message effects, I don't think they're needed in this PR. They can get added a later PR by someone else, along with all the other chemicals that are missing popups.

As for alternatives for "flavor" (other than previously mentioned taste): cyanide is known for killing quickly, (minutes for powder ingestion, seconds for gas inhalation). There's a metabolism speed slowing component in the theobromine prototype, it probably works in reverse.

Although, I digress, all of these options probably increase the scope of this PR beyond what is reasonable. They can get added in later; the point of this PR is just to rename+buff toxin, nothing more.

(also, irl cyanide prevents oxygen from getting used by cells, so it would be very slightly more realistic to have it deal airloss damage instead. But whatever, my point about scope stands, nobody knows how cyanide works anyway. Keeping it as poison is fine.)

**Comment by ProPandaBear** [comment]
> Good PR. Might want to change the ID too, for consistency -- correct me if I'm wrong, but the only two places toxin is referenced is in the chemical dispenser when emagged and in the recipe for Plant-B-Gone, so you'd just have to make changes in those two spots. 

> You should probably flag this PR as a fix to #15494.

> Changelog looks a little off, there's supposed to be a 🆑 emoji at the bottom, plus some formatting. Not really personally sure how the autoCL works, though, so I can't really advise.

I'll get working on these changes ASAP. Great points, much appreciated. Super late here so might not get finished until tomorrow.

**Pull request merged**
