### PR TITLE
Fix colornetwork desc and help

### PR DESCRIPTION
**Pull request by lzk228**
title

### CODE REVIEW

**Review by PJB3005 — COMMENTED** [review]
You can make it inherit `LocalizedCommands` instead and get rid of the `Description` and `Help` implementation entirely.

**Review by PJB3005 — APPROVED** [review]

**Comment by PJB3005** [comment]
2slow
image

**Comment by PJB3005** [comment]
CI fail is legit.

**Comment by lzk228** [comment]
@PJB3005 approve again :troll

**Pull request merged**
