### PR TITLE
Make unknown shuttle events trigger an announcement

### LINKED ISSUE #33235: Unknown Shuttle Events don't trigger an announcement
## Description
As easily noticeable in game, mid-round shuttles do not create a station announcement as they should.

**Reproduction**
Join any server and wait until at least the 47 minute mark (or spawn in the event manually in a dev environment)

**Additional context**
Event is defined in YAML in Prototypes/GameRules/unknown_shuttles.yml at line 43

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Makes unknown shuttle events trigger an announcement.

## Why / Balance
Fixes #33235.

## Media

https://github.com/user-attachments/assets/fd2184b3-09aa-4fd3-976a-d023dae2ac22

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- fix: Now unknown shuttle events trigger an announcement.

### CODE REVIEW

**Review by TheShuEd — APPROVED** [review]

**Comment by Winkarst-cpu** [comment]
Failed labels check is wild.

**Comment by SlimmSlamm** [comment]
this seems like it'll be very annoying considering how many shuttle events we get.

**Comment by UbaserB** [comment]
> this seems like it'll be very annoying considering how many shuttle events we get.

It's tuned far too high right now lol, I'm pretty sure we decided on 1 shuttle per round max but the pr that changed this anyway was merged with some.. mistakes because the sheer size made it hard to review.

**Comment by Winkarst-cpu** [comment]
Reducing unknown shuttle events is a thing for another PR ig. Main theme of this one is to just fix the announcements.

**Review by slarticodefast — APPROVED** [review]
Works as intended. Thank you for your contribution!

**Pull request merged**
