### PR TITLE
Mark sawn-off shotgun as a contraband

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Marked sawn-off shotgun as a contraband.

## Why / Balance
See #31047.

## Media

изображение

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Now sawn-off shotgun is marked as a contraband.

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
Is it contraband though? I don't know if there's anything that says a bartender can't saw off their own shotgun.

**Comment by thebadman4662** [comment]
> Is it contraband though? I don't know if there's anything that says a bartender can't saw off their own shotgun.

Bah, there is even in-game tip telling them to do it.

**Comment by UbaserB** [comment]
it should be the same level of the normal bartender shotgun

**Comment by SlamBamActionman** [comment]
Idk I kinda like that the Bartender has a reason to visit medbay and interact with the Medical department for a reason that isn't just normal healing or Tric.

**Comment by Dutch-VanDerLinde** [comment]
> it should be the same level of the normal bartender shotgun

it should be higher level contraband because it is easily concealable while having the same exact power as the double-barrel shotgun

**Comment by Cadunkus** [comment]
> Idk I kinda like that the Bartender has a reason to visit medbay and interact with the Medical department for a reason that isn't just normal healing or Tric.

I wouldn't consider "begging for free crap so you can be robust" as good RP.

**Comment by SlamBamActionman** [comment]
> > Idk I kinda like that the Bartender has a reason to visit medbay and interact with the Medical department for a reason that isn't just normal healing or Tric.
> 
> I wouldn't consider "begging for free crap so you can be robust" as good RP.

If that's how you do it, *that's* FailRP. Anecdotal but I had a round earlier today where me and the other bartender went at the same time (dragon and LoneOp was about) and medbay was pretty busy. We tried to ask for a doctor who said "You folks are standing upright, so I can't prioritize you right now". Since there was a power outage we got to pry open the doors to surgery and take the saw ourselves.

It wasn't much, but a lot more interesting than bunkering down in the bar (which had to do plenty anyways).

**Comment by slarticodefast** [comment]
Are you still working on this?

**Comment by Winkarst-cpu** [comment]
> Are you still working on this?

Nope.

**Pull request closed without merging**
