### PR TITLE
New NT boiler suits

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR

Following an incident where an unnamed employee was sprayed in water and ruined their jumpsuit, the company has ordered a surplus of boiler suits to prevent further damage to company jumpsuits.
## Why / Balance

Passengers don't actually get much choice in what they wear, its either the stock grey jumpsuit or a recolour of it, the boiler suit is an industrial style coverall that can be worn by anyone.
## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
**Changelog**

:cl:
add: Added boiler suit, a corporate emblazoned uniform for passengers and employees
add: Added two boiler suits to clothesmates

### CODE REVIEW

**Comment by lzk228** [comment]
your cl is wrong, you had to change the one what was in comments

**Comment by KittenColony** [comment]
> your cl is wrong, you had to change the one what was in comments

?

**Comment by lzk228** [comment]
good:

```
:cl:
- add: Added fun
```

bad:

```
:cl:
Adedd: Added fun!
```

**Comment by EmoGarbage404** [comment]
We don't really need more basic solid-colored jumpsuits in the clothesmate at this time and the fact that you made this to try and smuggle in bluesec sprites makes me not feel like merging this.

**Pull request closed without merging**
