### PR TITLE
Fix potted plants going over doors

### LINKED ISSUE #11450: Bioluminescent plants like to go thru doors
## Description
Dragging a plant allows it to go thru doors

**Reproduction**
1. Drag a bioluminescent plant
2. Push it into an airlock

**Screenshots**
image

**Additional context**

Discovered on salamander, with (i believe) the tickrate to be 30

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

fixes #11450 
## Media

https://github.com/space-wizards/space-station-14/assets/124214523/4ebea3f5-01d7-4811-871f-2c220dc10b29

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- fix: Potted plants cannot going over doors anymore.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
this doesn't resolve the linked issue, as it only changes the sprite drawdepth, whereas the actual issue is the the plants do not collide with doors.

**Comment by lzk228** [comment]
Fixed for real + video

**Comment by chromiumboy** [comment]
Looks like the base issue has been addressed now

**Comment by SamuelChilcott** [comment]
This has removed the ability for players to hide behind potted plants, and should be revisited

**Pull request merged**
