### PR TITLE
Medical subsect bags retexture

### PR DESCRIPTION
**Pull request by Hanzdegloker**
## About the PR

I found out recently the virology bags use the generic versions as a base which is a tragedy since medical bags are unique and a modified version of that would fit more since virology is a subset of medical. Then I saw the saw problem with the genetics bags... and the chem bags...  and so I redid them all! 

Side note the duffle bags for all the subsects have unique symbols to each represent genetics, virology and chemistry respectively. I found the concept very cool and since every medical bag has the blue cross, now every subsect's bag has their respective symbol on em.

## Why / Balance

Recolored versions of the generic bag is lame when the medical bag base is right there. Also it adds more readability since you can look at it and go, wow it looks like the medical bag but has the colours of genetics and a genetics symbol on it. Genetics is a subset of medical! which its! even if not implemented at all but you know a fella can dream. On a more personal level I very much want these bags to look real nice since after newmed, I am gonna be eyeing up virology with a passion. 

## Technical details

Virology, Chemistry and genetics all now use the medical bags as a base. Each subsect also has a unique symbol emblazoned on the satchels, backpacks and duffle bags.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑
- tweak: Retextured Virology, Chemistry and Genetics bags

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
CHANGELOG...BROKEN...NO 🆑

**Comment by Dutch-VanDerLinde** [comment]
GOOD PR THOUGH IT LOOKS COOL

**Comment by Hanzdegloker** [comment]
> CHANGELOG...BROKEN...NO 🆑

I have gotten like 10 PRs merged, I have finally fumbled the 🆑, its so joever

**Comment by beck-thompson** [comment]
Love the icons! 👍

**Comment by EmoGarbage404** [comment]
i really don't like the changed designs for the backpacks. They hardly even resemble backpacks at all.

The satchels are technically fine but compared to the old sprites they look like downgrades in terms of actual complexity and interest. They're all copy pastes with minor color changes which really is more uninteresting than the various colors present throughout the old ones.

The duffels look quite over-brightened to a point where the shading isn't even visible and the readability of things like the handle is hurt quite significantly.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
^

**Comment by Hanzdegloker** [comment]
> i really don't like the changed designs for the backpacks. They hardly even resemble backpacks at all.
> 

Thats uh, just what the backpacks look like for medical. I just use the already ingame medical pack as a base. As for the brighter bags yes they are brighter because I used the medical duffle bag as a base which is a brighter white overall. The copy paste look is partly intentional to make it seem like a common family of the department medical.

**Comment by EmoGarbage404** [comment]
> Thats uh, just what the backpacks look like for medical

tbh i'd rather it just be resprited to look like a normal backpack instead of the Oblong Storage Ellipse. The lack of straps and the completely flat silhouette really doesn't look very good.

> As for the brighter bags yes they are brighter because I used the medical duffle bag as a base which is a brighter white overall. 

I understand that but the current medical backpack sprite is probably the worst backpack and looks significantly worse than the other sprites so I'd rather just change that one rather than bring everything else in style with it.

> The copy paste look is partly intentional to make it seem like a common family of the department medical.

i'm not bothered by the copy paste so much as the fact that the stripping of most of the secondary colors makes these look pretty generic and bland.

**Comment by Hanzdegloker** [comment]
> > Thats uh, just what the backpacks look like for medical
> 
> tbh i'd rather it just be resprited to look like a normal backpack instead of the Oblong Storage Ellipse. The lack of straps and the completely flat silhouette really doesn't look very good.
> 
> > As for the brighter bags yes they are brighter because I used the medical duffle bag as a base which is a brighter white overall.
> 
> I understand that but the current medical backpack sprite is probably the worst backpack and looks significantly worse than the other sprites so I'd rather just change that one rather than bring everything else in style with it.
> 
> > The copy paste look is partly intentional to make it seem like a common family of the department medical.
> 
> i'm not bothered by the copy paste so much as the fact that the stripping of most of the secondary colors makes these look pretty generic and bland.

Alright so thats easy enough and allot less work. I can do an opposite and make the medical stuff fall into line with the subsects and all that jazz. BUT, can I at least touch up and keep the satchels. They medical satchel unlike the normal generic satchel sits at your side LIKE AN ACTUAL SATCHEL, the only other satchel to do this is the leather satchel. The default one just sits behind you like a sad backpack. Also I would like to keep the unique symbols.

**Comment by UbaserB** [comment]
i don’t like the symbols minus the normal med one, its unclear for what they are and doesn’t sit right

**Comment by Hanzdegloker** [comment]
> i don’t like the symbols minus the normal med one, its unclear for what they are and doesn’t sit right

sadness, they all exist currently on the dufflebags alone

**Pull request closed without merging**
