### PR TITLE
Astro-concrete

### PR DESCRIPTION
**Pull request by NotSoDana**
## About the PR

Added Astro version of concrete tiles, crafts in lathe, tile items

## Why / Balance

* Mapping. On maps with **weather** component concrete tiles has _"weather: true"_, which looks bad in buildings. (example in comments).
* More possibilities for engineers in decor, constructing, etc.
* Makes "Faux Astro Tiles" research a little bit less useless.

## Technical details

* Concrete tile and slab as item
* Astro-tiles concrete with "weather: false"
* Tiles added in "Faux Astro Tiles" of RnD
* Cost of recipes: 0.5 steel and plastic

## Media

Screenshot_68
Screenshot_69
Astro_concrete_vid

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Dezzzix
- add: Added astro-concrete tiles, items, and lathe recipes

### CODE REVIEW

**Comment by NotSoDana** [comment]
:sob:
image
image

**Comment by EmoGarbage404** [comment]
i feel like this should probably just be made to be a non-weather tile until we have proper support for weather tiles and such. Adding an extra "astro" variant for a multitude of tiles just to support an imperfect weather system definitely isn't ideal.

**Comment by SlamBamActionman** [comment]
Considering we can't construct concrete to begin with, I think having astro concrete tiles on its own is a fine addition, even if you disregard the weather feature.

**Comment by NotSoDana** [comment]
> i feel like this should probably just be made to be a non-weather tile until we have proper support for weather tiles and such. Adding an extra "astro" variant for a multitude of tiles just to support an imperfect weather system definitely isn't ideal.

I originally planned to just remove "weather" component from the concrete, but if I did that it would cause even more problems. "Astro" version of this tiles is a golden mean, as i think, which could help mappers and give possibilities for ingame engineers. If you follow this position, then Astro-grass also doesn’t make much sense, but it’s still in the game.

**Comment by EmoGarbage404** [comment]
> If you follow this position, then Astro-grass also doesn’t make much sense, but it’s still in the game.

i mean the reasoning with that at least is that normal grass has dirt under it and can't be pulled up whereas Astro-grass is just like a sheet of turf or w/e. Concrete, astro or not, is just a tile so it doesn't make sense to have an alternate version of it.

**Comment by NotSoDana** [comment]
will be replaced in the cutter machine "soonTM"

**Comment by UbaserB** [comment]
It is the maintainer team's consensus that the weather system should be fixed instead of adding new constructible tiles, especially considering that there is currently no need of them for any planet-side purpose.

**Comment by NotSoDana** [comment]
> especially considering that there is currently no need of them for any planet-side purpose.

So, the only way for now is like Emo said, just turn off `weather` for concrete tiles? Should I make PR for this or just relax and cry about it?

**Comment by UbaserB** [comment]
It’d be best to ask emo himself for the idea he has in mind

**Pull request closed without merging**
