### PR TITLE
T-Ray Goggles

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

adds t-ray goggles that can be turned on by pressing e on the item in the inventory
## Why / Balance

t-rays without taking up pocket space
## Media

https://github.com/space-wizards/space-station-14/assets/79580518/11227eb7-d91f-43fe-9925-3f59b11f9101

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Potato1234_x
- add: Added t-ray goggles.

### CODE REVIEW

**Comment by lzk228** [comment]
it is necessary that the subfloor can only be seen if they are equipped

**Comment by metalgearsloth** [comment]
How does this differ from mesons again

**Comment by potato1234x** [comment]
> How does this differ from mesons again

It can see subfloor things?

**Comment by potato1234x** [comment]
> it is necessary that the subfloor can only be seen if they are equipped

Hnng idk how to code guess i'll have to learn

**Comment by lzk228** [comment]
> > it is necessary that the subfloor can only be seen if they are equipped
> 
> Hnng idk how to code guess i'll have to learn

I didn't check a code yet, but i think that tray work only on specific slots, you should check pr that allows tray works in pockets, after tray "remaking"

**Comment by potato1234x** [comment]
can you link the exact pr? i cant find anything about t ray pockets

**Comment by lzk228** [comment]
nevermind, it works not that i expected
 #15030

**Comment by potato1234x** [comment]
ive been staring at code for the past hour how do i do this

**Comment by potato1234x** [comment]
gonna mark as draft while i learn to code

**Comment by JoeHammad1844** [comment]
please add a sprite for when it's on

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
You copied my system, comments and all, please just use the existing system and extend functionality if you need to. Just add a slots whitelist to it or something.

**Comment by potato1234x** [comment]
i remade the whole pr on a different branch so i'll just make another pr instead of updating this one it'll be easier

**Pull request closed without merging**
