### PR TITLE
traitors can see types of pens when examined

### LINKED ISSUE #15179: Traitors should be able to identify if a pen is of the explosive, hypo, or e-sword variety
## Description
If a traitor buys a surplus crate and gets a pen in it, they will have no way of identifying the pen at first glance. With the addition of exploring pens this can be quite leathal to the traitor. If they attempt to use it to investigate, and its the exploding pen, they will either waste it, or end up blowing themselves up.

**Additional context**
Yes I know this is a skill issue, but we should find a way to remedy this since new players might kill themselves and waste their traitor round unintentionally.

Some ideas:

We can have them spawn with removable labels.
We can allow traitors to be able to identify what variety they are by examining them.
Remove exploding pens from surplus crates.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds TraitorExamine component/system and puts it on the 3 sus pens

only traitors (in detail range) and observers can see the type of pen.

fixes #15179 

**Media**
nothing sus

john syndicate sees all

- [X] I have added screenshots to this PR showcasing its changes ingame

**Changelog**
:cl:
- tweak: The Syndicate has given its operatives retina implants to see what kind of gadgets are hidden inside of pens.

### CODE REVIEW

**Comment by HoidC** [comment]
could you put this on noslips too?

**Comment by lapatison** [comment]
Is this thing localized?

**Comment by deltanedas** [comment]
> could you put this on noslips too?
will do

> Is this thing localized?

nope should i do that, description and stuff dont use loc

**Comment by PJB3005** [comment]
Idk, this just feels like it violates some pretty core design ideas behind SS13 to me. I like that traitors are 100% normal humans besides their up link (which can be taken).

**Comment by Interrobang01** [comment]
One way to fix both the issue pjb brought up and the issue this PR is fixing would be to make the pen clearly identifiable by everyone for a short period after it's bought, before restoring the pen to its unidentifiable self.

The easiest way of doing this would be to put the pen in a labeled wrapper. Make the wrapper unwrap to resemble a mundane candy bar wrapper or similar for extra spess points.

**Comment by deltanedas** [comment]
chocolate bar real

**Comment by deltanedas** [comment]
@Interrobang01 for every pen?

**Comment by Interrobang01** [comment]
@deltanedas giving every syndie pen a wrapper or other identifier would be ideal in my opinion just for consistency, yes.

**Pull request closed without merging**
