### PR TITLE
Adds a new glass-producing plant to botany.

### PR DESCRIPTION
**Pull request by jimmy12or**
## About the PR
Adds a glass producing plant and associated reagent.

## Why / Balance
For a long time I wanted to be able to grow glass for many projects and departments to use.

## Technical details

The Crystalthistle is a mutation of galaxythistle and creates a new reagent called Quartzite. When heated to a high temp 10u of quartzite will become one sheet of glass similar to how plastic can be made with chems. The plant also contains Ethyloxyephedrine since Stellibinin comes from galaxythistle, I thought it would be a good fit and make sure the plant can be grown partly for medical purposes as well since there are a lot of players that enjoy using the narcoleptic trait. Quartzite, if drank also acts as a less potent version of razorium (about 1/3 as painful).

## Media
Screenshot 2024-07-02 231013
Screenshot 2024-07-02 231039
Screenshot 2024-
![Screenshot 2024-07-02 231226
07-02 231106](https://g
Screenshot 2024-07-02 231429
ithub.com/space-wizards/space-station-14/assets/47635328/18091e67-0718-42f2-b9ad-cdeedcd994f5)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None to my knowledge.

**Changelog**

:cl:
- add: A Crystalthistle, A new glass producing plant, and associated reagent, Quartzite!

### CODE REVIEW

**Comment by slarticodefast** [comment]
This PR already adds the same thing: #28993
Welding it to create glass is better than adding an additional reagent only for this in my opinion. That way botany can make the glass without the help of chemistry (like for steelcaps).

**Comment by jimmy12or** [comment]
> This PR already adds the same thing: #28993 Welding it to create glass is better than adding an additional reagent only for this in my opinion. That way botany can make the glass without the help of chemistry (like for steelcaps).

I had made this before i knew that one existed and was shocked to see that it did. I do see the practicality of it, but it requires botany to either get a welding mask as well or oculine to prevent themselves from going permanently blind. The reagent in this one can also be heated up in a microwave which botany can often get use of.

I certainly see the benefits of theirs, and I will be happy to just get a glass growing plant one way or the other. In this case, I mostly made this PR because I had already put the work into it and it's my first one. So i wanted to see what people think of it.

**Comment by Sirionaut** [comment]
iI think there is also a problem with capitalization, which is why IntegrationTests fails

> Error when validating server prototype (EntityPrototype, FoodCrystalthistle). Errors: 
>  - PrototypeID Crystalythistle for type Content.Server.Botany.SeedPrototype at Line: -1, Col: -1 not found

i think thats happening because in "Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml" it's capitalized, `seedId: Crystalythistle.`
but since it starts with a lower case c in seeds.yml it can't find it

**Comment by jimmy12or** [comment]
> I think there is also a problem with capitalization, which is why IntegrationTests fails
> 
> > Error when validating server prototype (EntityPrototype, FoodCrystalthistle). Errors:
> > 
> > * PrototypeID Crystalythistle for type Content.Server.Botany.SeedPrototype at Line: -1, Col: -1 not found
> 
> I think that's happening because in "Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml" it's capitalized, `seedId: Crystalythistle.` but since it starts with a lower case c in seeds.yml it can't find it

Thanks for pointing this out on it's own. even on your snippet of it, it's misspelled. For some odd reason it says "Crystalythistle" with an extra y in there when it's intended to be crystalthistle.

**Comment by slarticodefast** [comment]
#28993
Looks like the other glass thistle PR got merged, making this one redundant.
I still like the artwork you did, so I hope to see other ideas from you in the future.

**Pull request closed without merging**
