### PR TITLE
Remake bottles and syringes names to use labels

### LINKED ISSUE #21533: bottles with reagents should be just labeled
instead of name them `bottle of mutagen` they should have label and be `bottle (mutagen)`

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

instead of `nocturine bottle` it now will be `bottle (nocturine)` and you can even remove this label! so no more meta things
also removed descriptions from some bottles so they wont be recognizable without the label
fixes #21533

some bottles and syringes loose contraband tag

## Why / Balance

better

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Bottle and syringe names are remade into labels.

### CODE REVIEW

**Comment by Plykiya** [comment]
I believe drinks have this kind of problem, like with coffee

**Comment by lzk228** [comment]
> I believe drinks have this kind of problem as well, like with coffee or tea. Once the cup is empty... it's not coffee or tea anymore, y'know?

a little controversial and out the scope of this pr

**Comment by slarticodefast** [comment]
Do they show up correctly in vending machines?

**Comment by lzk228** [comment]
> Do they show up correctly in vending machines?

yes they do #29178

**Comment by ShadowCommander** [comment]
Not sure about removing the descriptions just for consistency and making them non-recognizable when the label is removed.

I'd be more ok with this if it still had an examine text somewhere like attached to the label.

**Comment by themias** [comment]
fixes #29506

**Comment by deltanedas** [comment]
> I'd be more ok with this if it still had an examine text somewhere like attached to the label.

erm why does your bottle say its used to make people sleep KOS

**Comment by lzk228** [comment]
> fixes #29506

nope, i didnt localize pills

**Comment by slarticodefast** [comment]
Fixes #21533

**Comment by lzk228** [comment]
oop

**Review by UbaserB — CHANGES_REQUESTED** [review]
can you do this for vials too

**Comment by lzk228** [comment]
> can you do this for vials too

yeah, done, i just forgot about their existing

**Review by UbaserB — APPROVED** [review]

**Comment by slarticodefast** [comment]
Can do the same for the newly added bottles and vials in this PR?
#31738

**Pull request merged**
