### PR TITLE
New decals for mapping

### PR DESCRIPTION
**Pull request by Ko4ergaPunk**
## About the PR

Adds a simple decals to make life easier for mappers.
Sometimes this can be very useful. Example of use in media

## Media

image
example

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ko4erga
ADMIN:
- add: Added new markup decals.

### CODE REVIEW

**Comment by UbaserB** [comment]
I can actually sort of see where it has use, but it's very niche imo

**Comment by Ko4ergaPunk** [comment]
> I can actually sort of see where it has use, but it's very niche imo

Yep, but when necessary, you have to suffer

**Comment by Ko4ergaPunk** [comment]
What should i write in "license" and "copyright"? 🙃

**Comment by IProduceWidgets** [comment]
My one reservation about this is the shadows will look weird if the tile gets changed / the water entity gets removed. 

Might be better to add a greycale water prototype and then change the color that way.

**Comment by Ko4ergaPunk** [comment]
> My one reservation about this is the shadows will look weird if the tile gets changed / the water entity gets removed.
> 
> Might be better to add a greycale water prototype and then change the color that way.

Well, that's just one example of use image

**Comment by SlamBamActionman** [comment]
I have used a square decal in a custom map I've made to recolor grass. It can look absolutely terrible if misused but I think it has its uses.

**Pull request merged**
