### PR TITLE
make ninja shoes magboots

### LINKED ISSUE #28585: Space ninja shoes' magnetic suction cups aren't magnetic
## Description
It says in the item's description: "A pair of nano-enhanced boots with built-in **magnetic** suction cups."
The shoes are not magnetic however and a ninja has to rob engineering or some other place for magboots when there's no gravity.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds Magboots to ninja shoes (but not ItemToggle) so they always keep you on the floor no matter what

## Why / Balance
fixes #28585

allows ninja to troll grav without being trolled in turn

## Technical details
no

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/b1e0376f-8343-4a3d-a593-af990b435089

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- fix: Fixed ninja shoes not working as magboots.

### CODE REVIEW

**Comment by Plykiya** [comment]
was this PR good to undraft...?

**Comment by deltanedas** [comment]
item toggle rework not merged

**Comment by Plykiya** [comment]
> item toggle rework not merged

item toggle rework got merged

**Comment by deltanedas** [comment]
reeeeal

**Pull request merged**
