### PR TITLE
improved vox laugh

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Improved vox laugh, since the "original replacement" was a bit quiet and sounded muffled. This is still way less harsh than the 1.0 laugh

kinda meant to be a part of #31679 but was not tacked onto the PR in time

## Media

live vs replacement replacement
https://github.com/user-attachments/assets/73a737bd-2a95-46ee-8b08-80701d5a9e00

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by UbaserB** [comment]
me when    me when you take 3 days to update your pr and dont draft it in the meanwhile so we just end up merging it cause we had no idea

**Comment by Errant-4** [comment]
> me when me when you take 3 days to update your pr and dont draft it in the meanwhile so we just end up merging it cause we had no idea

I lost track of time I have been juggling a bunch of PRs recently

**Comment by UbaserB** [comment]
also you should have a cl since publish has already came with your previous pr

**Comment by Errant-4** [comment]
I thought this is a rather minor tweak that wouldn't need one

**Pull request merged**
