### PR TITLE
Added relevant tags to several cakes, and changed chem in Spacemans cake

### PR DESCRIPTION
**Pull request by Catofquestionableethics**
## About the PR
Tweaked numerous Tags in "Cake.yml" for consistency

## Why / Balance
Several cakes were missing relevant tags, and Spaceman's cake, which previously had omnizine, has had its relevant chem Polypyrylium Oligomers added.

## Technical details
Added tags to numerous Cakes, and changed the Chem in Spacemans Cake.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Spacemans cake now contains Polypyrylium Oligomers instead of Omnizine.
- fix: Slime, Brain and Christmas cakes can now be eaten by Lizards.

### CODE REVIEW

**Comment by slarticodefast** [comment]
The vegetable tag is only used for the "get 14 vegetables" cargo bounty, but since cake is blacklisted it does not make any difference for gameplay.
grafik
Burgers, tacos and skewers (or any food sequence) should probably be blacklisted here as well.
The meat tag for brain food makes sense and it allows lizards to eat them.
Slime should not count as meat in my opinion.
Is the christmas cake a fruit cake?
The PolypyryliumOligomers replacement for Omnizine is a good idea.

**Comment by SaphireLattice** [comment]
> Is the christmas cake a fruit cake?

https://en.wikipedia.org/wiki/Christmas_cake - yup, yes


> Slime should not count as meat in my opinion.

Slime balls do have a tag `Meat`

**Comment by Catofquestionableethics** [comment]
Slime is tagged as meat when slimeballs and can be consumed by Lizards already, so I think it's reasonable to assume that lizards would also be able to eat it. Will remove Vegetables tag from carrot cake if it's useless.

**Comment by slarticodefast** [comment]
> Will remove Vegetables tag from carrot cake if it's useless.

I guess you can leave it there if it is consistent with other items tagged as vegetables. Maybe someone will use that tag at some point.

**Comment by Catofquestionableethics** [comment]
Lizards can drink slime as well, which is why I added the tag. If there's a more appropriate tag to add that lets lizards eat it I would add that, but from what I've seen I can't seem to find one is the issue. Can cut it if you don't want it, just making a case for it.

**Comment by slarticodefast** [comment]
You convinced me 😄

**Review by slarticodefast — APPROVED** [review]

**Comment by Catofquestionableethics** [comment]
Updated CL. Haven't mentioned Carrot Cake being changed since it will (currently) have no In game Effect

**Comment by chromiumboy** [comment]
Thank you for your first contribution! I edited the changelog for clarity, I hope you don't mind

Tested it in-game and it all seems fine

**Pull request merged**
