### PR TITLE
Add chameleon voice mask

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR

This PR adds a voice chameleon mask to the syndicate uplink (and removes the normal voice mask), which costs a lot more than previously.
Added for the lulz, coauthored PR on @EmmaFaith's behalf

**Media**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: EmmaFaith, router
- tweak: Voice mask in the uplink now costs 6TC but can also change its appearance to most other masks

### CODE REVIEW

**Comment by deltanedas** [comment]
webedit gaming but good change

**Comment by BasedUser** [comment]
> `Unhandled exception. Robust.Shared.GameObjects.UnknownComponentException: Unknown name: BreathTool`
derp

**Comment by moonheart08** [comment]
This is a webedit, how quickly do you want me to close the PR

**Comment by BasedUser** [comment]
when you forcepush it

(this isn't code, and also not the first webedit PR)

**Comment by deltanedas** [comment]
webedit is all fun and games until 8 commits of bandaids fixing it 1 line at a time

**Pull request merged**
