### PR TITLE
Meatball Salvage

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Adds a version of each flesh anomaly enemy which is spaceproof, these special versions do NOT spawn from the anomaly and can only be mapped. They also use salvage ruleset.
Adds a new salvage wreck using these new flesh enemies which is FULL of meat.

## Why / Balance
I felt like making a flesh salvage.

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by AjexRose** [comment]
morb mobs arent space proof, so you probably want to either make a variant that is for this salvage, or reduce the loot and remove them.

**Comment by HoidC** [comment]
> morb mobs arent space proof, so you probably want to either make a variant that is for this salvage, or reduce the loot and remove them.

image

**Comment by AjexRose** [comment]
> > morb mobs arent space proof, so you probably want to either make a variant that is for this salvage, or reduce the loot and remove them.
> 
> image

damn, my ass cannot read

**Comment by Us3rn4me228** [comment]
Based PR

**Pull request merged**
