### PR TITLE
[RND] Research magboots

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

RND can research magboots.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added research magboots in RND!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I don't know if there's really a purpose for these. I'd just allow science to create magboots on demand rather than creating variants and giving them to every job that could conceivably have a use for them.

**Comment by PuroSlavKing** [comment]
> > > I don't know if there's really a purpose for these. I'd just allow science to create magboots on demand rather than creating variants and giving them to every job that could conceivably have a use for them.
> > 
> > 
> > I can try to create a research technology in RND, to get magboots
> 
> That'd be cool

awaiting revision.

**Comment by PuroSlavKing** [comment]
> regular

I also did a research of regular  magboots. As for me it is logical and not "unbalanced" that RND can investigate them (if HOS asks, scientists don't need them.)

**Comment by deltanedas** [comment]
i think emos point was that since sci can just make magboots, why have special department magboots at all? they can just ask sci to make some

**Comment by PuroSlavKing** [comment]
oh okay, I will remove everything from security and leave only research

**Comment by PuroSlavKing** [comment]
> Apologies for not being clearer.

done, RND be happy.

**Review by EmoGarbage404 — APPROVED** [review]
sci mains booming

**Pull request merged**
