### PR TITLE
fueltanks can explode when shot with lethal bullets/pellets

### PR DESCRIPTION
**Pull request by JustinTrotter**
## About the PR 
~~Probably needs discussion since it somewhat changes the balance of bullets/pellets. What essentially I've done is given each projectile 1 heat damage while taking away 1 blunt. I think this overall maintains the balance of the gun for unarmored targets, but it does change the numbers for how much damage is resisted per armor and may require tweaking.~~

~~I would like to justify the heat damage as minor friction burns as the projectile strikes the object.~~

~~Other downsides would be having to treat both brute and burn wounds for someone gunned down, but the total burn damage shouldn't exceed 20-30 in most gunned down scenarios that I can imagine.~~

~~I've also created a new damage modifier material for explodey things made of metal for the fuel tanks and lowered the damage threshold for heat to 1. Nearly all heat based weapons and tools do more than 5 heat damage which would have ignited the fuel tank anyway. Except for lighters which do 1 heat damage. So.... don't smoke near the welder tanks!~~

Changed to just explode with piercing damage.

**Screenshots**

**Changelog**

:cl:
- add: Welder tanks explode when shot with projectile guns. (Also don't poke them with a spear)

### CODE REVIEW

**Comment by theashtronaut** [comment]
wouldn't a better way to handle this to just have a chance or something to explode when taking piercing damage, or have it explode after taking X piercing damage that scales on how full of fuel the tank is? seems weird to add heat damage to bullets just so you can explode fuel tanks. Similarly, touching a fuel tank with a cigarette wouldn't explode it, that's pretty silly. Welders do it because they are welding torches, so they "punch" through and the flame ignites it.

**Comment by JustinTrotter** [comment]
> wouldn't a better way to handle this to just have a chance or something to explode when taking piercing damage, or have it explode after taking X piercing damage that scales on how full of fuel the tank is? 

The problem with that is other melee weapons like the spear would make it explode.

**Comment by theashtronaut** [comment]
> > wouldn't a better way to handle this to just have a chance or something to explode when taking piercing damage, or have it explode after taking X piercing damage that scales on how full of fuel the tank is?
> 
> The problem with that is other melee weapons like the spear would make it explode.

It could be argued that any weapon that punctures could be capable of triggering the explosion. The weapon pierces the tank, and the friction/sparks of that forceful puncture is the ignition source. I at least feel it makes more sense than bullets doing heat damage, but definitely curious what other people think. I could be in the minority here with my reasoning lol

**Comment by mirrorcult** [comment]
i agree with @theashtronaut here, piercing should have a chance to make it explode. nothing wrong with stabbing it with a spear and exploding

**Comment by GoodWheatley** [comment]
haven't really looked at fuel tank code so it might not be possible, but can't you just add a check for a bullet entity hitting the fuel tank?

**Comment by DummeHytteOst** [comment]
adding heat damage to bullets seems like a bad move, since the heat damage will likely stop any bleeding you recive from getting shot

**Pull request merged**
