### PR TITLE
Senior Collector

### PR DESCRIPTION
**Pull request by KingFroozy**
## About the PR

- This PR adds Senior Collector as an analog to other senior roles for Cargo department.
  - Including his own PDA, ID card, Job Icon and unique clothings, such as jumpsuit/skirt and supplying beret.
  - Keep in mind, that the role isn't mapped to any stations yet.
## Why / Balance

 - Cargo department was deprived of its senior role, which could upset some avid cargo players. I've fixed that.
 - Senior Roles themselves were criticized a lot, allegedly, people who want to learn new things on their own do not need babysitters in form of more experienced players, and that Senior roles have nothing mechanical to introduce to the game. But still not all players are willing or even able to understand everything on their own, in which case Seniors come to help. And as someone stated, not everything has to be mechanical or introduce new mechanics to the game to be a good addition.
 - I agree, that Cargo is certainly not the most difficult department to study and play on, but there are some tricks that an inexperienced player may not understand on themselves e.g. Shuttle driving, ordering system, bounty system, after all, papers on ordered goods with information about the customer.
 - It's also supposed to help in study of some salvage mechanics, such as the wreckage magnet, expeditions, weapons and equipment (fultons, crushers, PKA).
 - Someone may say, that the senior collector can steal the job from the inexperienced salvager by taking their hardsuit or something, but it is very easy to Ahelp in that case, because Senior Collector is not supposed to play as a "more cool" salvager, unless they get a spare hardsuit for him.
 - And is in general, Senior Collector can be a kind of trusted person in the department, as it happens with other Seniors. Quartermaster will have no doubt that the senior collector will do all the needed and requested work, and will be able to safely leave management of the department to him, if he would need to leave it. Only if the senior collector does not become a traitor. And as it is, the role presents more RP interactions within their department, or even outside of it.
 - That is also just a very show-off role, which shows how much you like to play cargo, and that you have mastered this department, which, of course, is very pleasant to feel.
 
 Any proper and constructive discussion about this PR is welcome.
 
## Technical details

[None]
## Media

seniorcollecterpreview

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

[None]
**Changelog**

:cl:
- add: Nanotrasen has started hiring senior collectors to help train newly-employed cargonians. expect them to arrive at the stations soonly.

### CODE REVIEW

**Comment by lzk228** [comment]
First time playing technicians needs only 2-3 shifts to learn all that they need to know

**Comment by Subversionary** [comment]
> First time playing technicians needs only 2-3 shifts to learn all that they need to know and more experienced technicians or even qm can teach them

qm cant replace senior salvie teaching people how 2 robust

**Comment by CatMagic1** [comment]
I feel like this outfit could look really cool if you tweaked it.

**Comment by KingFroozy** [comment]
> I feel like this outfit could look really cool if you tweaked it.

No idea, how it could look better, honestly

**Comment by KingFroozy** [comment]
> First time playing technicians needs only 2-3 shifts to learn all that they need to know and more experienced technicians or even qm can teach them

That's the same issue discussioned in original senior roles PR, heads can teach you, but they almost never do, and making a new role, speciallized on training newbies would make more people do it.

**Comment by lzk228** [comment]
med, sci, eng, sec requires a lot of time to understand the mechanics, when cargo very simple

**Comment by UbaserB** [comment]
I swear there was already a huge discussion on this role and it was shut down ages ago.

**Comment by KingFroozy** [comment]
> I swear there was already a huge discussion on this role and it was shut down ages ago.

Never participated in that discussion, so I have no idea about it being shut down. I swear, I have a better explanation on why it should be in game.

**Comment by KingFroozy** [comment]
> med, sci, eng, sec requires a lot of time to understand the mechanics, when cargo very simple

There are still people, who can't understand even the simpliest things in their lives, and who needs a helping hand from aside. you're underestimating the human stupidity

**Comment by CatMagic1** [comment]
> med, sci, eng, sec requires a lot of time to understand the mechanics, when cargo very simple

I remember trying cargo for the first time and my first 5 rounds were just me asking QM what I should and how to do shit. I swear to this day the QM is the most absent minded head.

**Comment by lzk228** [comment]
> > med, sci, eng, sec requires a lot of time to understand the mechanics, when cargo very simple
> 
> I remember trying cargo for the first time and my first 5 rounds were just me asking QM what I should and how to do shit. I swear to this day the QM is the most absent minded head.

lrp moment
normal qm should appoint a newbie as assistant to experienced technician

**Comment by QuietlyWhisper** [comment]
There's genuinely no downsides to adding this(OH NO MORE SPRITES!!! AND ENTITIES!!!), and can improve the new player experience. I see no issues.

**Comment by EmoGarbage404** [comment]
the point against senior roles have been said at length, and extend to all of them, beyond just this one, but I'd be remiss to say it doesn't feel like a false flag when senior roles were added with the intent of being solely "learning" roles only to be immediately turned into straight up bloat for the purpose of flexing.

Especially with the consideration that QM already frequently LARPs as salvagers, adding in more roles into a frankly pretty barren department for the purpose of 'teaching' what little mechanics exist seems like little more than a will to want to show off on people who have sunk fewer hours into the game.

**Comment by deltanedas** [comment]
bwoink anyone that fucks off salving instead of teaching :trollface:

**Comment by LankLTE** [comment]
I absolutely don't think Cargo needs a senior role.

**Comment by KingFroozy** [comment]
> I absolutely don't think Cargo needs a senior role.

Fair enough, as I've said, the cargo isn't a very difficult department to learn things in, but it's not an excuse to be the uneducateable fool, who needs someone around him to help and teach. And it's just about some minor tricks, like, how to earn more money as a cargo tech, or how to robust as a salv. I've myself was really unaware of what should I do as a techie,  when I first played the role, and I've noticed those papers on ordered goods after, like, 5 or more games as it, And QM just said "go collect stuff, and that's all", and after this I was left on my own, which was mostly confusing.

**Comment by notquitehadouken** [comment]
1. Do not underestimate how dumb people are
2. Completionists sake

**Comment by CatMagic1** [comment]
We're gonna need this even more when cargo get's expanded.

**Comment by Emisse** [comment]
Im not sure this is needed at the moment

**Comment by NeviNovat** [comment]
What's the downside to this? Even if it's like a 5 min training still feels nice to some people and it adds RP. And it's not like abusing access to loot important item would be a new issue. If it's a concern, then remove salvage access from the senior. He can train salvage if he is let in the salvage section.

I had a new player in cargo, they didn't know to pilot shuttle, how bounties work, what to buy and when or even that we need to supply certain departments with mats as fast as possible (for example science with gold, silver and artefact fragments). I was training them until I got picked as a syndicate agent, and I realized no one else could train them since QM was occupied and other cargo techs refused or ignored me. At least with a senior role training new people is a job requirement (unless they get picked as traitors to).

While it's an easy department it's still a critical one, getting new players up and running and working fast is important since without that they might just SSD or not do anything and that means one less cargo tech at work.

Also, seniors act as a backup for HoP to promote in case the head disappears, gets SSD or is demoted!

**Comment by LankLTE** [comment]
Cargo as a whole is extremely simplistic at the moment, and generally senior roles aren’t being used for their main purposes regardless which leads me to believe this will just be used for the salvage access it provides / more job slots. Should cargo ever be expanded this idea can be revisited.

**Pull request closed without merging**
