### PR TITLE
Adds clipboards

### PR DESCRIPTION
**Pull request by nmajask**
## About the PR

Adds clipboards to the game, and gives them to the hop and qm round start. Clipboards work like folders but they have more storage space (10 >20), take up more space (5 > 10), can store a pen by alt clicking, can be worn in the belt slot, and does slightly more damage than a punch (6 blunt).

## Why / Balance

Its a new item you can use for RP. As for storage/damage values, storage and size are doubled over a regular folder though it can also store a pen, does damage, and be stored in a belt slot so it should balance out. Its intended to be like a better folder for someone who does a lot of paperwork.

## Media

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Clipboards are now available to the Head of Personnel and Quartermaster.

### CODE REVIEW

**Comment by moonheart08** [comment]
but can you write using it or do you have to remove the paper

**Comment by nmajask** [comment]
> but can you write using it or do you have to remove the paper

You can open it like a folder and write on the paper inside.

**Comment by Nairodian** [comment]
Put one or two in bureaucracy crates so you can get more.

**Review by Partmedia — APPROVED** [review]
Thank you for your contribution. I've tested this in game.

**Comment by nmajask** [comment]
Agh, I was literally in the middle of updating the PR with the request from nairod.

**Comment by Partmedia** [comment]
> Agh, I was literally in the middle of updating the PR with the request from nairod. I'll just make a separate PR for it. Thanks for the quick merge though.

Thank you for your contribution. You are of course welcome to open another PR with the addition :)

**Comment by nmajask** [comment]
> > Agh, I was literally in the middle of updating the PR with the request from nairod. I'll just make a separate PR for it. Thanks for the quick merge though.
> 
> Thank you for your contribution. You are of course welcome to open another PR with the addition :)

#20736 here is the follow up

**Pull request merged**
