### PR TITLE
Robits and Titanium stuffs

### PR DESCRIPTION
**Pull request by Ablankmann**
## About the PR 
This is a draft PR (don't get your hopes up) hoping to add Titanium sheets, Titanium related items, and a basic form of Robotics. God help my soul

- [x]  Titanium and Co. Sheet stuff
- [x]  Titanium and Co. obtain methods
- [ ]  Titanium-related structures and objects
- [x]  Sprites
- [x]  Technology
- [x] Robotech Deluxe and Robotics Circ. Imprinter
- [x]  Borg and Robot stuff (AI, laws, other stuffs)
- [x]  Locale and Content.Server stuff
- [ ] Robotics job
- [ ] See if laws can be made better
- [ ] Make borg spawn system suck less
- [ ] Merge cleanbot drain with actual drain comp
- [ ]  Iron out conflicts

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
robotics should probably be included in a separate pr, as it's fairly technical and has a lot of debate around implementation.

**Comment by Elijahrane** [comment]
To be clear, two a few things here are very placeholder:
1. The borg spawning system is an awful hack
2. There's more splitting up of drone functionality but I never removed it from drones
3. Laws are kind of shit, moony said they were also working on them and i'll probably end up using hers eventually
4. The innate item system is actually kind of cool but it needs to be able to handle both entity target and map target interactions in the same action, which requires a rewrite of action
5. cleanbots drain thing should probably get merged with the actual drain component
6. medibots could be a bit more modular

**Comment by Elijahrane** [comment]
> robotics should probably be included in a separate pr, as it's fairly technical and has a lot of debate around implementation.

The material was added specifically for construction of robots. If you mean the role, I agree with not adding that. I disabled it on Nyano because it's not like scientists already have a lot to do or that building robots is fun for more than a couple minutes

**Comment by Ablankmann** [comment]
The materials were added specifically for robots, just thought adding the structures and such would make them less useless (since without them they would just be robot food). 
but anyway i'll take that other stuff into consideration and put them on the "things i have to figure out soon" list

**Comment by Elijahrane** [comment]
Also you're missing quite a few things that Nyano already has like AI for the robots and the robotech vendor

**Comment by Just-a-Unity-Dev** [comment]
titanium spear added yet?

**Pull request closed without merging**
