### PR TITLE
Fixed airlock bolting for docks, and deny docking to bolted external airlocks

### LINKED ISSUE #20063: Shuttle docking causes the door status signal to be updated, causing cyclelocks for shuttle airlocks to be impossible
## Description
image

This makes it unfeasible to put cycling airlocks in arrivals and cargo, preventing the proper removal of tiny fans & the existence of all access externals.

### PR DESCRIPTION
**Pull request by TGODiamond**
## About the PR

Disallows docking to bolted externals airlocks
and
fixes #20063

This PR depends on #22521

## Why / Balance

Because tiny fans are being phased out, and this is a replacement.

Docking to a bolted external airlock should not be possible in my mind, but is up for discussion. The emergency shuttle and arrivals shuttle can still dock to bolted airlocks, which may or may not be desired.

(EDIT: AI-shuttles will not dock at bolted airlocks anymore)

## Technical details

Simple code change, since I'm new to C# and this project.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/79604238/d0bbf00c-e179-4782-992d-44b1d2bb3372

https://github.com/space-wizards/space-station-14/assets/79604238/aed72052-2cd1-4762-9114-18686c7bd60d

https://github.com/space-wizards/space-station-14/assets/79604238/586b70f7-8e22-46c1-aa1d-cb9c92dc1f2e

## Breaking changes

None

**Changelog**

:cl:
- tweak: You can no longer dock to bolted external airlocks.
- fix: Airlock bolting for shuttle docks now work properly. Expect to see more realistic airlocks for docks in the future.

### CODE REVIEW

**Comment by NancokPS2** [comment]
Is there any specific reason to prevent docking with a bolted airlock?  
The docking part is the airlocks sticking to each other, it isn't related to the bolts.

**Comment by deltanedas** [comment]
would be nice for frontier to prevent someone straight up docking and boarding

**Comment by TGODiamond** [comment]
Found a bug: Docked shuttles at round-start, like escape pods, aren't actually docked properly. This means that `door.ChangeAirtight = false;` has not been run yet. This will space rooms.

**Comment by metalgearsloth** [comment]
> The emergency shuttle and arrivals shuttle can still dock to bolted airlocks, which may or may not be desired.

The snowflake behaviour for the automatic ones should be kept to a minimum, this should be handled at the shuttle instead rather than having to run to airlocks across an entire grid to accept or deny specific grids.

**Comment by metalgearsloth** [comment]
This is probably going to be phased out in my shuttle rework by changing how docking works.

**Pull request closed without merging**
