### PR TITLE
Regulate minimum allowed output pressure for internals

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
Limit the lowest allowed release pressure of gas tanks to 17.5 kPa, allowing players to still somewhat cheese the presure/duration but not excessively so
I also standardised the Maximum Output Pressure among different tanks rather than have it be derived from the default pressure of each prototype

## Why / Balance
Players can extend the duration a gas tank will last by reducing the output pressure. This is mostly fine at room temperature (although we might want to consider changing the default release pressure to the ~17.5 kPa "meta value" that powergamers already use for a 20% "capacity bonus"), but by using very low temperature gases (such as the easily available Liquid Oxygen) which are more dense, very low pressures can be used to drastically extend the operational capacity of a tank (~15m out of emergency tanks and 2.5 hours out of a normal tank).  While this is only possible because we don't have cold gas damage implemented, and ultimately introducing that will be a better answer, I think this also has merit on its own and can be added faster/with less game design considerations. 
There is no legitimate reason to use such low pressure apart from this cold gas trick. So why would equipment deemed "safe" let you use a pressure setting that would normally suffocate you? 
This works as an interim solution and does not conflict with introducing cold damage later. Players also still get to cheese their gas tanks at the level possible at room temperature (or that can be taken away too by increasing the minimum release pressure to 21.3 kPa)

Changing max pressure was mostly just a consistency thing since previously there was significant difference between the max output pressure of Air and O2/N2 tanks, which doesn't make much sense. This just makes things more consistent but probably doesn't actually matter regarding gameplay, breathing hot gases is undesirable anyway due to their increased density/reduced moles per volume

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: Internals gas tanks can no longer be set to dangerously low output pressures.

### CODE REVIEW

**Comment by Errant-4** [comment]
Potential idea for making this possible AND also making it an actual choice: Tanks could come Safe, only allowing the preset release value. One could use some tool (wrench or screwdriver) on the tank to mess with the safety, allowing lower (and higher) pressures to be used, but this will also disable the pressure warning on the HUD alert due to the safety mechanism having been circumvented

**Comment by Hrosts** [comment]
You forgot an important use case for extremely low output pressures - making internals tanks spin in place

**Comment by Errant-4** [comment]
> You forgot an important use case for extremely low output pressures - making internals tanks spin in place

Does that even work? Opening the release valve on a tank seems to ignore the regular output pressuer setting

**Comment by Hrosts** [comment]
> Does that even work? Opening the release valve on a tank seems to ignore the regular output pressuer setting

Just checked - it does. At the default ~22kPa pressure it flies off like an untied balloon. At 0.1 kPa it spins in place.

**Comment by ninruB** [comment]
What about a compromise?
The pressure will be capped to the new minimum only when internals are toggled (if less than 17.5 set to 17.5), while the setting itself allows for pressure less than 17.5 for the silly :tm:

**Comment by Errant-4** [comment]
I'm setting this to draft until I have preserved spinny gas tank, its so stupid I love it.
Is it ever used for anything other than either "I want to see it spin for as long as possible" and "I want it empty, NOW" ?

**Comment by Plykiya** [comment]
> > You forgot an important use case for extremely low output pressures - making internals tanks spin in place
> 
> Does that even work? Opening the release valve on a tank seems to ignore the regular output pressuer setting

absolutely vital feature

**Comment by ShadowCommander** [comment]
Can you actually survive longer with a lower pressure? The mechanic that's supposed to prevent this is the oxy damage you take for not getting enough air in your lungs.

**Comment by Errant-4** [comment]
> Can you actually survive longer with a lower pressure? The mechanic that's supposed to prevent this is the oxy damage you take for not getting enough air in your lungs.

Respiration only checks if your lung has enough moles of oxygen, not pressure. If the gas is cold, it's more dense. So you get more moles of oxygen at the same volume and pressure. Meaning, you can reduce pressure and use less oxygen per breath to still get just enough oxygen to not gasp

**Comment by Errant-4** [comment]
> > > You forgot an important use case for extremely low output pressures - making internals tanks spin in place
> > 
> > 
> > Does that even work? Opening the release valve on a tank seems to ignore the regular output pressuer setting
> 
> absolutely vital feature
> 
> > There is no legitimate reason to use such low pressure apart from this cold gas trick. So why would equipment deemed "safe" let you use a pressure setting that would normally suffocate you?
> 
> I mean, anyone messing with valves on safety equipment they don't understand is bound to get hurt IRL Do we need to prevent the possibility of it in-game as well?

Do we actually want a noobtrap like that, without any safeties built in? (That could, like I mentioned, be circumvented by a determined player)

**Comment by Golinth** [comment]
> Can you actually survive longer with a lower pressure? The mechanic that's supposed to prevent this is the oxy damage you take for not getting enough air in your lungs.

Yes, with cold enough (dense enough) air, but the real solution to that should be adding temperature changes and damage for breathing super chilled and heated air. Not artificially limiting the air release for the tank

**Pull request closed without merging**
