### PR TITLE
BBQ rib sandwich

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

Changed the name of a certain food item to 'BBQ rib sandwich'.

## Why / Balance

The original name is a registered trademark. We probably shouldn't be using it.

## Technical details

N/A

## Media

bbq-rib-sandwich

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

### CODE REVIEW

**Comment by notquitehadouken** [comment]
make it WcSpine

**Comment by chromiumboy** [comment]
That is a terrible name :P

**Comment by notquitehadouken** [comment]
> That is a terrible name :P

it is a hilarious name

**Comment by Darkenson** [comment]
Availability* - there's a typo in the description.

**Comment by chromiumboy** [comment]
> Availability* - there's a typo in the description.

Sorry, out of scope for this PR

(jk, good catch, I've fixed it)

**Comment by keronshb** [comment]
I feel we can go with a funnier name, but I honestly have nothing.

**Pull request merged**
