### PR TITLE
Resprited carpet sprites

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR
Fully resprited all carpets (except for church carpet).

All fame to the Hqlle, he did a very good job.

## Media
image_2023-12-17_18-09-11

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Hqlle
- add: Resprited carpet sprites.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
hell yeah

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by Flareguy** [comment]
These are pretty damn good! I only have a few complaints:

- The golden border on the black and purple carpets is very overdone looking and the shades need a lot less contrast and/or less shading.
- The pattern on the blue carpet is... strange, especially considering it's normally used in the captain's office if I recall correctly.

Also, no roleplay changelogs please. Just say you resprited carpets.

**Comment by Tunguso4ka** [comment]
> * The golden border on the black and purple carpets is very overdone looking and the shades need a lot less contrast and/or less shading.

I`m gonna disagree with you on that. My opinion is that this two sprites would look beautiful in the game as is. The "overdone" part makes it special.

> * The pattern on the blue carpet is... strange, especially considering it's normally used in the captain's office if I recall correctly.

I found it kinda cute. Yes, it look strange at the first glance, but i think we should give it a chance.

> Also, no roleplay changelogs please. Just say you resprited carpets.

You're breaking my heart. Done.

Thank you for your complaints.

**Comment by lzk228** [comment]
epic

**Comment by IamVelcroboy** [comment]
Yeah, I don't know, I like the gold trim all around and the pattern on the sky blue is nice!

**Comment by UbaserB** [comment]
image 

I really feel that the buttons on this should go.

**Comment by Emisse** [comment]
I like these

**Pull request merged**
