### PR TITLE
Backpacks The Movie

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-duffels bags now hold 120 capacity and give a 10% slowdown
-satchels and backpacks have nothing
-mimes bags are now silent
-clown bags now honk

### CODE REVIEW

**Comment by Peptide90** [comment]
> Not a fan of this whatsoever, backpack type is one of the few things you can actually customize, and making it a non cosmetic change takes away from the freedom of it 

Mechanically it makes sense for the duffel to get more storage but to make it not a meta it needs a drawback. If the drawback was a slightly debuff on speed up to a max, based on total stored / character weight that'd be good but that's a massive scope change.

It'd need testing to make sure hardsuit + duffel etc etc isn't snail pace and crap for gameplay.

**Comment by Emisse** [comment]
its only 10% so its unnoticeable for most of the time

**Comment by ZeroDayDaemon** [comment]
> > Not a fan of this whatsoever, backpack type is one of the few things you can actually customize, and making it a non cosmetic change takes away from the freedom of it
> 
> Mechanically it makes sense for the duffel to get more storage but to make it not a meta it needs a drawback. If the drawback was a slightly debuff on speed up to a max, based on total stored / character weight that'd be good but that's a massive scope change.
> 
> It'd need testing to make sure hardsuit + duffel etc etc isn't snail pace and crap for gameplay.
> 
> Also new UI should enable loadouts so cosmetic customisation

I mostly care about the nerf on satchels since thats what i prefer aesthetically, something like it being quiet just feels entuerly useless to me unless I'm an antag

however im bringing up the argument for the others as well since im most likely not the only person who would prefer for these to stay cosmetic only

**Comment by Emisse** [comment]
satchel thing was brought up as a suggestion by someone else, i could just make them match backpack stats if we want it to 1-1 ss13

**Comment by OldDanceJacket** [comment]
I actually use the satchel for aesthetic purposes as well, I dislike being unable to see my entire drip.


I was also the one who suggested they have a silent noise when moving items to and fro as ideas were being tossed around.
Emisse correctly inferred that the only non-t role that's really effected by this function of the satchel having less room was Engineering. Otherwise if you want to carry a lot of things on your person, it seems cool to go and get a dufflebag and do so, while the much smaller satchel has it's own small benefit.

Realistically it could just be a 1 - 1 with the backpack, but I think a unique function of bag silence is worth exploring.

**Comment by ZeroDayDaemon** [comment]
I'd rather round spawn backpacks be untouched or at least identical to /tg/ and something be expanded with science to start pushing bluespace tech including new types storage or upgraded backpacks

**Comment by BlitzGunner225** [comment]
Yeah if someone pulls out a gun or something you’re gonna see em carrying it and likely shooting it
Also most people don’t even use stealth so almost no one will use it

**Comment by juliangiebel** [comment]
I like slight mechanical changes to the backpacks. It gives them more flavor tbh.
I think satchels should also give a 1% or 2% speed boost to offset the lowered storage capacity.

**Comment by EmoGarbage404** [comment]
This feels very unnecessary. It just provides a bit of meta-gamey flavor to a cosmetic system. It may be interesting, sure, but it adds an unneeded level of complexity. Its like if jumpsuits and jumpskirts had different stats. Not bad, just not needed.

**Comment by ZeroDayDaemon** [comment]
Just gonna say I'm entirely against this PR in every capacity and think backpacks should stay as they are currently, I think this reduces the game rather than adds to it. for the following reasons:

- Currently, there are very very few customization options for purely aesthetic things outside of your actual character's appearance, in fact, I think there's only one, which is backpack type.
- The changes made in this PR just add another layer of ways to power game
- silent storage seems entirely useless to anyone who is not an antag and even then it seems barely useful only in heavily specific situations, also valid hunting people with satchels may happen
- adding armor or stats to backpacks and their variants also just doesn't really make much sense imo, and makes much more sense to apply it to jumpsuits, for department jumpsuits to have protection against common hazards encountered in their department, EX: /tg/ sec jumpsuit has 10% blunt resist
- making you run faster with a satchel since it has less storage, but you would run slower without anything at all since a backpack since it doesn't change anything in terms of movement speed makes no sense.

If you want higher capacity storage items, I think this route should be explored by science and bluespace tech, I know duffles are bigger by default and make you move slower on /tg/ but I'm also against that as well, even if I am normally agreeable to /tg/'s stuff

**Comment by juliangiebel** [comment]
> silent storage seems entirely useless to anyone who is not an antag and even then it seems barely useful only in heavily specific situations, also valid hunting people with satchels may happen

Can you please look at the code changes hello?
Satchels just got made equivalent to backpacks again.

**Comment by ZeroDayDaemon** [comment]
> > silent storage seems entirely useless to anyone who is not an antag and even then it seems barely useful only in heavily specific situations, also valid hunting people with satchels may happen
> 
> Can you please look at the code changes hello? Satchels just got made equivalent to backpacks again.

I started writing it before that was pushed and finished after, its much better to include my reasoning on it anyway in case it were to be brought up again.

**Comment by OldDanceJacket** [comment]
I actually partially agree with what Zero is saying here.

I'd say keep these changes

_-duffels bags now hold 120 capacity and give a 10% slowdown
-mimes bags are now silent
-clown bags now honk_

And then make the other changes suggested here as changes to the jumpsuits.

I otherwise think the changes Emisse has made here are really good, but, making the resists related to the jumpsuit instead of the backpacks could be the way to go overall.

**Comment by Emisse** [comment]
dont test me i will add minute resistances to jumpsuits

**Comment by EmoGarbage404** [comment]
> dont test me i will add minute resistances to jumpsuits

Threatening people with shitty changes that you arent able to merge yourself doesnt seem like a good strategy

**Comment by ZeroDayDaemon** [comment]
I think that was a joke, simmer down, keep this constructive

**Comment by ZeroDayDaemon** [comment]
just because i REALLY hate this pr doesnt mean im gonna be mean to emisse, shes too nice

**Comment by Emisse** [comment]
im just gonna close this pr i think changing things makes too much drama

**Comment by ScalyChimp** [comment]
The mime and clown bag changes should still go through, I don't think anyone's disagreeing with those.

**Pull request closed without merging**
