### PR TITLE
Rubber bullet rebalance

### PR DESCRIPTION
**Pull request by Vaaankas**
Signed-off-by: vanx <vanx#5477>

## About the PR 

Increased the stamina damage on rubber bullets to hopefully make them be used more (also because it was literally impossible to stun someone with the revolver 15*6=90 stam damage lol).

**Media**

- [+] This PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Vaaankas** [comment]
Wait i forgor the vector uses the .45 aswell.... nukies would hate this simple trick

**Comment by Jackrost** [comment]
One of the problems that detective needs to craft these bullets by using fabricator. He doesn't have it from start and I'll be more than happy if someone add speed loader with rubber bullets into detective's locker

**Comment by EmoGarbage404** [comment]
this is a massive balancing issue considering the vector uses these bullets. the vector and revolvers shouldn't be sharing in the first place but oh well. That should be remedied before we get balance tweaks on the bullet.

**Comment by Vaaankas** [comment]
> this is a massive balancing issue considering the vector uses these bullets. the vector and revolvers shouldn't be sharing in the first place but oh well. That should be remedied before we get balance tweaks on the bullet.

Could also be mitigated if we ever add stun resistance to armor.

**Comment by Vaaankas** [comment]
Reopening since vector is removed in #16071

**Pull request merged**
