### PR TITLE
Moose 3.0

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR 
Back by overwhelming popular demand, and after extensive renovations by a dedicated NT crew and long hours invested by multiple teams of elite, wizard-class janitors, Moose Station is ready to be brought back into commission. Featuring a modernized cargo bay and xenoarch lab, along with standards-compliant evacuation and loading docks, this small asteroid station also adds some much needed dormitories and even a state-of-the-art holodeck entertainment room.  Now with almost 2x the maintenance hallways!
**Screenshots**

Moose-0

**Changelog**

:cl: checkraze
- add: Added a renovated Moose Station

### CODE REVIEW

**Comment by mirrorcult** [comment]
image did not uplolad

**Comment by Cheackraze** [comment]
> image did not uplolad

ok its better now

**Comment by Cheackraze** [comment]
issues have been addressed and is ready for another review, changing the screenshot once the maprender is finished

**Comment by moonheart08** [comment]
I think Emisse's review, emo's review, and my review are all good, and you're a trusted mapper. Thus, playtest time.

**Comment by Cheackraze** [comment]
Alr well I won't be around for 12 or so ish hours so make sure to leave feedback here or on discord about it

**Comment by DummeHytteOst** [comment]
missing fire extinguisher cabinets

**Pull request merged**
