### PR TITLE
Security Webbing Resprite

### PR DESCRIPTION
**Pull request by DieselMohawk**
## About the PR
Resprited the Security Webbing to better show off the vest beneath it.

## Why / Balance
I was requested to do this by Flareguy as my first PR.

## Media

Screenshot 2024-06-25 010339
Screenshot 2024-06-25 011305

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

tweak: Resprited the Security Webbing

### CODE REVIEW

**Comment by DieselMohawk** [comment]
I could do a nukie rig resprite, give me some time to think about what it would look like.

**Comment by qrwas** [comment]
why was it accepted?  this is now not security webbing, but some striptease webbing

**Comment by Flareguy** [comment]
> why was it accepted? this is now not security webbing, but some striptease webbing

The PR author forgot to link the issue. #29498

**Comment by qrwas** [comment]
> > чому це було прийнято? це тепер не захисна стрічка, а якась стрічка для стриптиз
> 
> Піарщик забув прив’язати питання. #27334

it doesn't change the fact that it looks like a stripper

**Comment by Agoichi** [comment]
Agree with that

**Comment by Thurtik** [comment]
And I thought that after the security clothes resprite it couldn't get any worse...

**Pull request merged**
