### PR TITLE
Hardsuit balance

### PR DESCRIPTION
**Pull request by Sailzington**
## About the PR

This Pr changes several of the stats for multiple of the hardsuits found in game.

Basic Hardsuit
-Blunt 10% --> 25%
-Slash 10% -->25%
-Heat 0% ----> 25%
-piercing 10% -->25%
-caustic 10% -->25%
-Radiation 0% 
-Shock 0%
-Explosive 10% -->30%

-movement walk 20% slower 
-movement run 20% slower --> 25%

Mime/ Clown Hardsuit (Balancing it as an EVA since it costs an EVA to craft)
-Blunt 10%
-Slash 10%
-Heat 0% --> 10%
-piercing 10%
-caustic 20% --> 0%
-Radiation 0% --> 70%
-Shock 0% --> 20%
-Explosive 10% --> 0%
-movement walk 10% slower
-movement run 10% slower

CE Hardsuit (Balanced around being both good at engineering and atmos)
-Blunt 20%
-Slash 20%
-Heat 60%
-piercing 20%
-caustic 30%
-Radiation 100%
-Shock 0% --> 60%
-Explosive 80% --> 50%
-movement walk 25% slower --> 20%
-movement run 20% slower

Atmos Hardsuit
-Blunt 10% -->20%
-Slash 10% --> 20%
-Heat 80%
-piercing 10% --> 20%
-caustic 50% 
-Radiation 50%
-Shock 0% 
-Explosive 50% -->30%
-movement walk 30% slower
-movement run 30% slower

Engineering Hardsuit (Gave better shock protection since It's an important part of their job)
-Blunt 10% -->20%
-Slash 10% --> 20%
-Heat 0% --> 20%
-piercing 10% --> 20%
-caustic 50% --> 20%
-Radiation 80%
-Shock 20% -->70%
-Explosive 50% --> 30%
-movement walk 30% slower
-movement run 30% slower

Maxim Hardsuit (A very rare suit that you will most likely not find with no slow debuff  Quoted by Lead Devs as "endgame Armor")
-Blunt 40% --> 55%
-Slash 40% --> 55%
-Heat 70% --> 55%
-piercing 50%  -->55%
-Caustic 0% --> 55%
-Radiation 90% --> 55%
-Shock 0% 
-Explosive 80% --> 55%
-movement walk 0% slower
-movement run 0% slower

Luxury Mining Hardsuit (Upgraded Salv suit with more protection and faster movement speed, that is very expensive to purchase)
-Blunt 10% -->35%
-Slash 10% --> 35%
-Heat 0% --> 35%
-piercing 20% --> 35%
-Caustic 20% -->35%
-Radiation 50% 
-Shock 0%
-Explosive 50% -->70%
-movement walk 15% slower
-movement run 15% slower

Salvage Hardsuit (Made the suit faster so they can get more loot from time based expeditions, and nerfed piercing prot)
-Blunt 30%
-Slash 30%
-Heat 30%
-piercing 50% --> 30%
-Caustic 30%
-Radiation 70% --> 50% (They have to deal with rad artifacts and bananium sometimes)
-Shock 0%
-Explosive 70% 
-movement walk 25% slower --> 15%
-movement run 25% slower --> 15%

Spationaut Hardsuit (same stats as the Salvage Hardsuit)
-Blunt 30%
-Slash 30%
-Heat 30%
-piercing 50% --> 30%
-Caustic 30%
-Radiation 70% --> 50% (They have to deal with rad artifacts and bananium sometimes)
-Shock 0%
-Explosive 70% 
-movement walk 25% slower --> 15%
-movement run 25% slower --> 15%

Brigmedic Hardsuit (is designed for being a healer instead of combat so people actually do the role)
-Blunt 20% -->20%
-Slash 20% --> 20%
-Heat 0% -->20%
-piercing 30% --> 20%
-Caustic 0% --> 20%
-Radiation 0%
-Shock 0%
-Explosive 0% --> 30%
-movement walk 35% slower --> 15%
-movement run 35% slower --> 15%

Sec Hardsuit (added much needed heat prot)
-Blunt 40%
-Slash 40%
-Heat 0% --> 30%
-piercing 40%
-Caustic 30%
-Radiation 0%
-Shock 0%
-Explosive 60% 
-movement walk 25% slower 
-movement run 25% slower 

Wardens Hardsuit (Wardens should have a heavily armored slow suit that keeps them in sec where they belong)
-Blunt 50% 
-Slash 40% --> 50%
-Heat 0% --> 40%
-piercing 40% --> 60%
-Caustic 30%
-Radiation 0%
-Shock 0%
-Explosive 60%
-movement walk 30% slower 
-movement run 30% slower --> 40% 

HOS Hardsuit (a better and faster sec hardsuit)
-Blunt 40% 
-Slash 50% --> 40%
-Heat 0% --> 40%
-piercing 50%
-Caustic 40% --> 30%
-Radiation 50% --> 0%
-Shock 0%
-Explosive 40% --> 50%
-movement walk 20% slower
-movement run 20% slower

Captains Hardsuit (gave some shock and rad protection since cap should be able to do all of the heads jobs if they are not in shift)
-Blunt 20%
-Slash 20%
-Heat 50%
-piercing 40%
-Caustic 40%
-Radiation 50% --> 80%
-Shock 0% --> 30%
-Explosive 50%
-movement walk 20% slower
-movement run 20% slower

CMO Hardsuit (Designed to make those chem bombs not as bad)
-Blunt 0%
-Slash 0%
-Heat 0% -->30%
-piercing 0%
-Caustic 90%
-Radiation 0%
-Shock 0%
-Explosive 0% --> 30%
-movement walk 10% slower
-movement run 5% slower

Pirate EVA (Pirates should be designed for quick attacks where they get in and out with loot)
-Blunt 20%  --> 35%
-Slash 20% --> 35%
-Heat 60% --> 50%
-piercing 10% --> 35%
-Caustic 25%
-Radiation 0%
-Shock 0%
-Explosive 30%
-movement walk 40% slower --> 5%
-movement run 40% slower --> 5%

Pirate Captain (there is only one pirate captain and they would be able to afford a good hardsuit)
-Blunt 30% --> 50%
-Slash 20% --> 50%
-Heat 60%
-piercing 15% --> 60%
-Caustic 25% -->30%
-Radiation 0%
-Shock 0%
-Explosive 40% --> 50%
-movement walk 20% slower --> 10%
-movement run 20% slower --> 10%

Wizard Hardsuit (There is only 1 wizard at a time, and they should be extremely powerful so that they actually have a chance)
-Blunt 40% --> 60%
-Slash 40% --> 60%
-piercing 60% --> 80%
-Heat 75% -->80%
-Caustic 25% --> 80%
-Radiation 75% --> 80%
-Explosive 50% --> 70%
-movement walk 20% slower --> 0%
-movement run 20% slower --> 0%

## Why / Balance

I believe these changes will improve, and make gameplay feel much better when it comes to hardsuits. Sec having heat protection will help them a lot when they have to deal with emagged borgs, lazer raptors, behonkers, and every other threat on, and off of the station.

## Technical details

All I changed, and added were stat values.
## Media

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: All Hardsuits have more armor!
- tweak: Sec Hardsuits now have heat protection.
- tweak: Brigmedic Hardsuit is much quicker with less protection.
- tweak: Warden's Hardsuit is much slower with much more protection!
- tweak: Salvage Hardsuits have exchanged armor for quicker mobility!
- tweak: Wizard Hardsuits have much more protection
- tweak: Pirate Hardsuits have more mobility!
- tweak Captains hardsuit is more resistant to radiation, and shock.
- tweak: CMO's Hardsuit has more protection against Chem explosions!

### CODE REVIEW

**Comment by LankLTE** [comment]
CL doesn't need to describe every exact change, just generally "Most hardsuit values have been changed." is enough, players can inspect it in-game themselves.

**Comment by thebadman4662** [comment]
Do clowns/mimes really need that 70% rad resist?

**Comment by metalgearsloth** [comment]
I don't really get the point of balancing 5 - 10 - 15 - 20 - 25 - 30 as different hardsuit values, it just seems like unnecessary changes for the point of change instead of standardising properly and making it much easier to balance well.

**Comment by Sailzington** [comment]
> Do clowns/mimes really need that 70% rad resist?

Both Clowns and Mimes deal and work with Bananium which is a radioactive material, and is the reasoning behind this

**Comment by mirrorcult** [comment]
we do not want hardsuits to have this much armor, the values are the way they are for a reason

**Comment by mirrorcult** [comment]
agree with sloth that most of these 5-10-15 point changes in stuff are really meaningless and arbitrary as well, I just don't really see the point

**Comment by mirrorcult** [comment]
opting to close for the reasons listed above

**Comment by Sailzington** [comment]
The 5% makes it a lot easier to balance the suits around each other. For example the Engineer Hardsuits should have less combat capability than the basic standard Hardsuit, but more environmental protection. When it comes down to movement speed that 5% really does make a noticeable difference. Which changes in general do you not like? just the 5%? All of the suits getting more combat armor? certain ones? etc.

> I don't really get the point of balancing 5 - 10 - 15 - 20 - 25 - 30 as different hardsuit values, it just seems like unnecessary changes for the point of change instead of standardising properly and making it much easier to balance well.



> agree with sloth that most of these 5-10-15 point changes in stuff are really meaningless and arbitrary as well, I just don't really see the point

**Comment by metalgearsloth** [comment]
If I show you a video of 10% vs 15% movespeed you're not going to notice a difference unless it's side-by-side.

**Comment by Sailzington** [comment]
> If I show you a video of 10% vs 15% movespeed you're not going to notice a difference unless it's side-by-side.

I tested them in game, but sure if you want I will check it out.

**Comment by mirrorcult** [comment]
only maybe worthwhile change is making the brigmedic suit faster which I'm not even sure is used right now. if anything most of the values being buffed here should be going down, not up

**Comment by Sailzington** [comment]
> only maybe worthwhile change is making the brigmedic suit faster which I'm not even sure is used right now. if anything most of the values being buffed here should be going down, not up

You think Pirates Hardsuits are in a good place? Sec doesn't deserve any heat protection at all? Salv should have more piecing protection than sec? Engineer and atmos dont deserve any basic combat protection at the cost of 30% slower movement speed? Also yes Brigmedic isnt used currently but it also needs some love, and I'd love to see it get reimplemented into the game one day. Why do you think these value should be going down instead of up a lot of these value are in fact going down with new one going up instead.

**Comment by metalgearsloth** [comment]
Pirates aren't even in the game lmao.

**Comment by Sailzington** [comment]
> Pirates aren't even in the game lmao.

Well yeah they are unbalanced as hell. I see them a lot in admemes which are always fun, and people always really enjoy them.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
they are used for events, and pirates are underpowered as they currently are, a hardsuit buff for them would be nice

**Comment by mirrorcult** [comment]
the issues preventing pirates from being a base rule and being unbalanced do not include "their hardsuit should be slightly faster"

**Comment by mirrorcult** [comment]
> You think Pirates Hardsuits are in a good place?

they are not in the game naturally

 > Sec doesn't deserve any heat protection at all? 

in a hardsuit no they do not

> Salv should have more piecing protection than sec? 
  
i don't think this matters at all

> Engineer and atmos dont deserve any basic combat protection at the cost of 30% slower movement speed?

no they do not 

 > Also yes Brigmedic isnt used currently but it also needs some love, and I'd love to see it get reimplemented into the game one day. 

then it can get rebalanced if they get readded to the game and we can actually see whether it matters or not

**Comment by Sailzington** [comment]
Pirate EVA (Pirates should be designed for quick attacks where they get in and out with loot)
-Blunt 20% --> 35%
-Slash 20% --> 35%
-Heat 60% --> 50%
-piercing 10% --> 35%
-Caustic 25%
-Radiation 0%
-Shock 0%
-Explosive 30%
-movement walk 40% slower --> 5%
-movement run 40% slower --> 5%

Pirate Captain (there is only one pirate captain and they would be able to afford a good hardsuit)
-Blunt 30% --> 50%
-Slash 20% --> 50%
-Heat 60%
-piercing 15% --> 60%
-Caustic 25% -->30%
-Radiation 0%
-Shock 0%
-Explosive 40% --> 50%
-movement walk 20% slower --> 10%
-movement run 20% slower --> 10%

> the issues preventing pirates from being a base rule and being unbalanced do not include "their hardsuit should be slightly faster"

It's not just "slighty faster" I changed a lot of other values as well. Pirates are designed for getting in, stealing loot, and getting out alive. They aren't supposed to be nukies who kill the entire station. And even if they are "just a week away" this would make pirate admemes even more enjoyable for everyone.

**Comment by thebadman4662** [comment]
> If I show you a video of 10% vs 15% movespeed you're not going to notice a difference unless it's side-by-side.

While 0.9 vs 0.85 might not seem like much, relative difference of 0.9 vs 1 and 0.85 vs 1 is way more noticeable and outside of spaced areas it can be a huge deal.

**Pull request closed without merging**
