### PR TITLE
resprite canisters

### PR DESCRIPTION
**Pull request by VictorJob**

### CODE REVIEW

**Comment by deltanedas** [comment]
meh

**Comment by UbaserB** [comment]
good sprites, but why is the PR description empty?

**Comment by JoeHammad1844** [comment]
looks weird

**Comment by CatMagic1** [comment]
glurpy
no need

**Comment by UbaserB** [comment]
> They are the same with some extra shades to make them look more shiny I'm just wondering if this is a better fit for the game's aesthetics than the current ones.

dont forget hueshifting and softening outlines

**Pull request closed without merging**
