### PR TITLE
Fix AME power generation

### LINKED ISSUE #31758: AMEs bigger than two cores produce less power
## Description

If you increase an AME's size to three cores, it will produce less power than an AME with two cores.

**Reproduction**

Build an AME with 2 cores, set injection to 4, note down the power produced (~180 kW).
Add one more core to the AME, making it 3 cores, set the injection to 6, note down the power produced  (~174 kW).
Add one more core to the AME, making it 4 cores, set the injection to 8, note down the power produced (~152 kW).

Notice that **by adding more cores & injecting more fuel, the power produced has gone down**.

**Screenshots**

Here is a graph of the power produced by an AME assuming optimal injection (injecting two fuel for every core).

image

image

`200000f * MathF.Log10(fuel * fuel) * MathF.Pow(0.75f, cores - 1)`

Here is the graph of the power produced before the change made in #29587 assuming optimal injection (injecting two fuel for every core).

image

image

`20000f * fuel * fuel / cores`

**Additional context**

This was introduced in #29587

### PR DESCRIPTION
**Pull request by Golinth**
## About the PR

Adjusted the formula for the AME power generation to not punish larger AMEs. Previously, any AME above 2 core would produce less power, the new formula adjusts it to no longer do that. With the new formula, a 4 core AME (the highest naturally mapped in-game atm) is equivalent to a 2-core AME - 180kW. Additionally, I ensured that having more cores but the same injection amount does lead to decreased power. 

If the AME is returned to cargo for purchase, the realistic cap is around 300kW with ~60 cores, but if you REALLY wanted to and could source 600 cores (and somehow 1200 fuel per injection) you can hit 400kW. 

Check the math [at desmos](https://www.desmos.com/calculator/70hhvmc524) along with some explanatory comments, if you want further proof of this really being an AME nerf in disguise. 

## Why / Balance

Resolves #31758, check it for more details, but at the moment higher core AMEs are less than worthless, as they actively produce less power. This change makes higher core AMEs at least somewhat desireable, as they produce marginally more power, even if they take significantly more fuel.

## Technical details

Adjusted one equation, added some explanatory comments. 
Formula can be messed with and tested [here.](https://www.desmos.com/calculator/70hhvmc524) (leads to desmos). 

## Media

Red line is current formula, Blue line is new one. As shown, at one core the power production is the exact same. 

Y-axis is kW produces, X axis is number of cores, assuming optimal (1:2) core to fuel ratio. 
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: AMEs larger than 2 cores now produce more power, instead of less.

### CODE REVIEW

**Comment by thebadman4662** [comment]
What does it mean for overclocking? If it did not get removed in one of AME rework PRs that is.

**Comment by Golinth** [comment]
When you increase the injection count passed 1:2. So like, making a 1 core AME inject 4 fuel instead of 2 is called overclocking it, as it damages the AME.

**Comment by thebadman4662** [comment]
Yes, but what about the actual important part - extra power. :trollface:

**Comment by Golinth** [comment]
> Yes, but what about the actual important part - extra power. :trollface:

Ah, my b I misunderstood. Overclocking is less powerful, but still increases power gen by a decent amount. Using the same example, a 1:4 AME makes 180kW instead of 240kW.

**Comment by Partmedia** [comment]
Linking the PR whose changes this PR would reverse: https://github.com/space-wizards/space-station-14/pull/29587

As stated in the original PR:

> the AME is meant to be a bootstrapping / emergency power supply. It shouldn't be able to power full-sized stations completely for 30+ minutes.

**Comment by Ilya246** [comment]
> Linking the PR whose changes this PR would reverse: #29587
> 
> As stated in the original PR:
> 
> > the AME is meant to be a bootstrapping / emergency power supply. It shouldn't be able to power full-sized stations completely for 30+ minutes.

this doesn't reverse any changes just makes ame above 2 cores no longer a noobtrap that both makes less power and takes more fuel

**Comment by Golinth** [comment]
> Linking the PR whose changes this PR would reverse: #29587
> 
> As stated in the original PR:
> 
> > the AME is meant to be a bootstrapping / emergency power supply. It shouldn't be able to power full-sized stations completely for 30+ minutes.

This PR does not increase the amount of power current AMEs can produce without admin interference, and in most cases actually decreases it. It does not reverse any of the other changes in that PR. Powering the station with just the AME remains unfeasible, as even if you could source the 60+ cores required somehow, the amount of fuel needed would bankrupt cargo shortly after. 

Since AME cores cannot be ordered from cargo, the maximum size currently obtain is 4 cores. With this PR, a 4 core AME will produce the same as a 2 core AME does currently, and will even produce less when overclocked. All other obtainable core counts are either equal to or less than their current values.

**Comment by scrivoy** [comment]
Hi all,
I've been playing the game for over a year now, with around 500 hours, most of them as an Engineer. From my experience, Engineers already have a hard enough time as it is. It’s always a race against the clock to get everything running before chaos breaks loose. Most of the time when I'm playing, we barely have time to assist other departments or enjoy any roleplaying, like hanging out at the bar. It would be nice if we could just start up the AME and have it generate power reliably while we take our time setting up a more efficient power source, even if that takes 30 minutes.
I don’t understand why there is a need for such a complicated formula for AME power generation. It seems to me that if an AME has 1 core, it generates a certain amount of power, and if it has 6 cores, it should generate 6 times as much power. If it consumes a lot more fuel as a result, that’s just part of the trade-off. If the Chief Engineer decides to use a larger AME, then they need to ensure that Cargo has enough funds to buy the fuel, or later switch to another power source if the fuel costs become too high.
Cheers!

**Review by Partmedia — APPROVED** [review]
Seems reasonable to me.

**Review by SlamBamActionman — APPROVED** [review]
Having a linear formula would make it very difficult to balance the AME for different sizes; this makes all sizes relatively similar, while still having a clear increase in power as one would intuitively expect (as opposed to the current dip).

**Pull request merged**
