### PR TITLE
added Heater Machine Circuit Board to lathe

### PR DESCRIPTION
**Pull request by noudoit**
## About the PR 
this shit doesnt work (: give me 1 day to figure this out..
**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by DummeHytteOst** [comment]
you can already make a heater machine board, by using a screwdriver on a freezer machine board.

**Comment by noudoit** [comment]
this change was wanted for QOL on the discord (:

> you can already make a heater machine board, by using a screwdriver on a freezer machine board.

**Comment by noudoit** [comment]
trying to figure out what i did wrong would like if someone could take a look ily xo.

**Comment by EmoGarbage404** [comment]
is there a reason why this is a draft? It looks done.

**Comment by noudoit** [comment]
> is there a reason why this is a draft? It looks done.

The crafting function was not working in the lathe - might be fine now though honestly so when I'm on tomorrow I'll check (:

**Comment by AJCM-git** [comment]
@noudoit you coming back to this?

**Pull request closed without merging**
