### PR TITLE
Added cows back into cargo

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
After some legal negotiation with Space PETA (SPETA) Nanotrasen finally convinced them they treat their animals with respect and care making animal purchase for cargo accessible for all your ~~penguin scarf~~ corgi petting needs.
**Screenshots**

image

**Changelog**

:cl: Hoolny
- tweak: Readded cows into cargo

### CODE REVIEW

**Comment by mirrorcult** [comment]
this will require discussion on github for sure

**Comment by ElectroJr** [comment]
It's probably good to have #5470 merged before adding more crates to cargo.

Also, I recall the gorilla entity being odd (sprite offset from center & hitbox). Is that fixed? Do all of the animals actually work as expected?

**Comment by mirrorcult** [comment]
> It's probably good to have #5470 merged before adding more crates to cargo.
> 
> Also, I recall the gorilla entity being odd (sprite offset from center & hitbox). Is that fixed? Do all of the animals actually work as expected?

yes, that was fixed in #5132

**Comment by TimrodDX** [comment]
Personally, I'd agree with the cow crate now that cow milking is in (since half the chefs on Packed seem to use their cow for meat instead...) but I'm not sure about the rest. They should probably be added as relevant content (such as eggs from chickens/geese or goat milk) emerges.

**Comment by mirrorcult** [comment]
i agree, most of these just bloat the cargo menu right now

**Comment by SethLafuente** [comment]
I heavily disagree not all animals need a use to be added into cargo the point is to have nice animal NPCs to have like look at my pingüino look at this badass gorilla is fun to have them they aren’t bloat  is already kinda weird that the whole livestock category only has monkeys I ant to have some snakes dammit

**Comment by SethLafuente** [comment]
Alright since it mostly won’t get merged with all those animals might as well add something only cows now and monkeys of course

**Review by ElectroJr — APPROVED** [review]

**Pull request merged**
