### PR TITLE
[HALLOWEEN] Halloween lobby music!!!

### PR DESCRIPTION
**Pull request by AwareFoxy**
## About the PR
Spooky music!

## Why / Balance
Scary Music for everyone!

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added scary halloween music! Be aware of ghosts on the station! :ghost:

### CODE REVIEW

**Comment by AwareFoxy** [comment]
image
huh

**Comment by VasilisThePikachu** [comment]
Are you aware of #8524 ?

**Comment by SaphireLattice** [comment]
Due to the two week release cycle, this is a bit late, and it will not be entirely trivial to undo. Additionally there's a freeze on any extra music due to increasing size of the game, until asset streaming from the server is implemented. Which would go *really* nicely together with seasonal or holiday specific music like this, but I'm not sure there's a system for that as of yet.

**Comment by AwareFoxy** [comment]
> Are you aware of #8524 ?

oh i forgor about it

**Pull request closed without merging**
