### PR TITLE
Fix: Dragging items over atmos pipes is slow.

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

I changed the TileFrictionModifier of the base item to be default friction.  #25430 

## Why / Balance

Dragging items over anchored items like gas pipes is slightly slower than dragging it over regular tiles.

## Technical details

The TileFrictionController changes friction if an ANCHORED entity has the TileFrictionModifierComponent. In this case, the very most base entity in the game, BaseItem, had a TileFrictionModifier of 0.5 instead of 0.3. Meaning that whenever you dragged something over atmos gas pipes, you would experience greater friction than on regular floor tiles because atmos gas pipes are considered an anchored entity, thus influencing friction.

I changed it from 0.5 to 0.3, matching default friction.

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

nothing, it's a yaml change

**Changelog**

:cl:
- fix: Dragging objects over gas pipes no longer slows you down.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Does BaseItem even need this.

**Comment by Plykiya** [comment]
> Does BaseItem even need this.

It feels wholly unnecessary and like you should just be adding the component to whatever item individually...

**Comment by metalgearsloth** [comment]
Yeah but check what TileFrictionController or whatever it's called is doing.

**Comment by Plykiya** [comment]
// If not on a grid then return the map's friction.
            if (!gridQuery.TryGetComponent(xform.GridUid, out var grid))
            {
                return frictionQuery.TryGetComponent(xform.MapUid, out var friction)
                    ? friction.Modifier
                    : DefaultFriction;
            }

            var tile = grid.GetTileRef(xform.Coordinates);

            // If it's a map but on an empty tile then just assume it has gravity.
            if (tile.Tile.IsEmpty &&
                HasComp<MapComponent>(xform.GridUid) &&
                (!TryComp<GravityComponent>(xform.GridUid, out var gravity) || gravity.Enabled))
            {
                return DefaultFriction;
            }

            // If there's an anchored ent that modifies friction then fallback to that instead.
            var anc = grid.GetAnchoredEntitiesEnumerator(tile.GridIndices);

            while (anc.MoveNext(out var tileEnt))
            {
                if (frictionQuery.TryGetComponent(tileEnt, out var friction))
                    return friction.Modifier;
            }

            var tileDef = _tileDefinitionManager[tile.Tile.TypeId];
            return tileDef.Friction;
            
 It just falls back to default friction when the entity has no TileFrictionModifierComponent.

**Comment by Plykiya** [comment]
Woops, fucked up that commit.

**Comment by wafehling** [comment]
Holy shit. I always wondered why dragging bodies or stuff around would randomly get slower...

**Pull request merged**
