### PR TITLE
[Sprite] Stimpack Sprite

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

now it will be immediately clear that this is not an emergency or space medipen.

**Media**

stimpen
stimpen_empty
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added Stimpack sprite

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
you opened a second pr when you could've just undrafted your first one.

**Comment by PuroSlavKing** [comment]
> you opened a second pr when you could've just undrafted your first one.

I will delete it now. I took on too difficult a task there.

**Review by metalgearsloth — DISMISSED** [review]
1. Is the license still valid
2. You don't need to re-state your name in the changelog, it just uses your gh one unless otherwise specified.

**Comment by PuroSlavKing** [comment]
> 1. Is the license still valid
> 2. You don't need to re-state your name in the changelog, it just uses your gh one unless otherwise specified.

I don't know how to enter my license, or do I need to write with a comma that I am the author of sprites? To simplify this issue, I made a separate draft PR, but it turned out to be too complicated, and I made such a simplified one in 5 times.

**Comment by Emisse** [comment]
update the meta.json of the sprite to include your licensing

**Comment by PuroSlavKing** [comment]
> update the meta.json of the sprite to include your licensing

done

**Pull request merged**
