### PR TITLE
UI to edit silicon laws from admin verb

### PR DESCRIPTION
**Pull request by Simyon264**
## About the PR

Adds the ability to easily change a silicons laws without going through VV.

## Why / Balance

commands bad to use and VV also bad

## Technical details

Adds a method inside SiliconLawSystem to change a silicons laws which is used in a new EUI.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**

:cl: Simyon
ADMIN:
- add: You can now view and edit the laws of silicons. Cyborg/Law bound entity -> Admin -> Manage laws

### CODE REVIEW

**Comment by ShadowCommander** [comment]
In addition to @EmoGarbage404's suggestions, I'd put the delete button on the right side of the buttons and checkbox so that it's away from the other buttons and harder to accidentally press.

**Comment by Simyon264** [comment]
@Chief-Engineer Review done

**Comment by Simyon264** [comment]
I've also updated the PRs screenshot to reflect the new UI changes.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
(assuming the media is updated)
There needs to be horizontal separator between the new law/save changes button and the rest of the body, also make those two buttons follow emo's edit above

**Comment by Simyon264** [comment]
I feel like the buttons look best centered. I tried them right aligned and it looked off. The separator I can do.

**Pull request merged**
