### PR TITLE
Make Vox blood able to be used to make space cleaner

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

Make boiling vox blood give Ammonia

## Why / Balance

Given that space cleaner is just water and ammonia I would assume that the
concentration of ammonia in vox blood is enough that it could be used as a
substitute. The other stuff that is found in vox blood is likely to be
irrelevant for it's effectiveness as a space cleaner. It requires two units of
blood to represent that the ammonia concentration is lower then pure ammonia.

## Technical details

YAML change

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Aquif
- add: Boiling Vox blood results in ammonia.

### CODE REVIEW

**Comment by dffdff2423** [comment]
Is that test failure related to my changes?

**Comment by lzk228** [comment]
maybe then give 2 cleaner and 1 blood as the result? or if blood doesn't fit, use something other

**Comment by dffdff2423** [comment]
I opted for nitrogen because Vox blood is intended to have a high nitrogen content and I don't think normal blood would fit very well.

**Comment by Kukutis96513** [comment]
could make vox blood be able to be used in the electrolysis machine for ammonia and nitrogen

**Comment by dffdff2423** [comment]
I don't think that makes sense because their blood is not just nitrogen and ammonia. I assume that whatever else is in vox blood is retained inside of the space cleaner in this reaction.

**Comment by deltanedas** [comment]
require heat for it to work so the non-ammonia boiled away or something

or have vox blood -> ammonia be the reaction and then it just automatically makes space cleaner

**Comment by dffdff2423** [comment]
Good, point. That is a better idea then the one I had.

**Review by Kukutis96513 — APPROVED** [review]
Tested it out in-game, seems good to me.

**Pull request merged**
