### PR TITLE
add cancer mouse for real

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

same as #26132 but tweaked to be less common and dangerous

## Why / Balance

people seem to like them (despite them being toxic)

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: added cancer mouse! (for real this time)

### CODE REVIEW

**Comment by Pangogie** [comment]
but y

**Comment by UbaserB** [comment]
glow needs to be less too

**Comment by VasilisThePikachu** [comment]
Honestly, I would keep this as most an admin spawn max. Just my opinion though.

**Comment by Golinth** [comment]
I think keeping it as  very rare replacement for a normal mouse (like 0.1%) while reducing its wackiness a bit would make it perfect.

**Comment by K-Dynamic** [comment]
Well as long as we get more random station creatures

**Review by mirrorcult — DISMISSED** [review]

**Pull request merged**
