### PR TITLE
Lisa and Old Ian as possible HoP pets

### PR DESCRIPTION
**Pull request by lapatison**
## About the PR

`lan Spawner` now called `HoP Corgi Spawner` (ID didn't changed), and can spawn Lisa or the Old Ian instead of Ian.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Our beloved Ian is getting some days off. Lisa and Old Ian agreed to work as his replacement.

### CODE REVIEW

**Comment by Scribbles0** [comment]
these two don't drop prime corgi meat, unless i'm mistaken
you may want to change that as well so that the traitor obj can be completed

**Comment by Scribbles0** [comment]
oh woops you already did that, ignore my previous comment

**Comment by deltanedas** [comment]
instamerge

**Comment by DawBla** [comment]
Old Ian dropping 1 steel after butchering
I'm going to hell for laughing at it

**Pull request merged**
