### PR TITLE
Mothroaches can now wear hamster-wearable clothes + pet inventory tweaks

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Moths can wear any clothes hamsters can wear. Also fixes not being able equip hammy with ties and changes the layout of pet inventories.

## Why / Balance

They're often treated as pets and you weren't able to put tanks/masks on them, but I'd thought I take it a step further and make displacement maps for hammies existing clothes for moffs.

The inventory change was because usually the tank slot didn't show up for most pets, and since they can't really unequip them anyway, I think it's fine to put them together.

## Technical details

It's all displacement maps

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
mask
moth army
haminventory
petinventory

## Breaking changes

Moved mothroach.rsi to mothroach/mothroach.rsi (so I could put displacement maps in the same folder)
**Changelog**

:cl:
- add: Mothroaches can now wear anything hamlet can wear

### CODE REVIEW

**Comment by lzk228** [comment]
cl should be more like
`- fix: Fixed moths can't eat some clothes

**Review by UbaserB — CHANGES_REQUESTED** [review]
Could you fix the displacement map so that the clown mask as shown in the photo doesn't have the mothroach outline? It should probably be as simple as moving it a pixel forward but I'm not sure how that'd affect the other sprites.

image

**Comment by Vermidia** [comment]
mask
Yeah I think I originally put it inward because I wasn't sure if the mask sprite was supposed to be right on the edge of the face or not. I think it does look better now for most masks though

**Comment by UbaserB** [comment]
also test fail real

**Review by UbaserB — APPROVED** [review]

**Pull request merged**
