### PR TITLE
Refactor actions to be entities with components

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Requires https://github.com/space-wizards/RobustToolbox/pull/4353

For the xeno pr btw

## Technical details
- All action prototypes have been turned into entity prototypes with an action component.
- The 3 different ActionTypes are now 3 components: InstantActionComponent, EntityTargetActionComponent and WorldTargetActionComponent.
- There is now one unified add action API covering almost all cases, which takes in a ref EntityUid and a string action prototype id when creating actions.
- The client still can't predict entity spawning so there are some net manager client checks when actions are spawned.
- In the future the components probably should not be inheriting from each other but that requires separating all the logic of each action type into different subscription handlers.
- Action component data could probably also be split up. Name and description have been moved to the entity prototype already.

## Media
[actionrefactor2.webm](https://github.com/space-wizards/space-station-14/assets/10968691/7b5be702-ea15-429b-9887-961e8e767b04)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
- Action prototypes must be replaced with entity prototypes.
  - This is done by changing `type: ...` with `type: entity`, and moving all data other than the `name`, `description` and new `id` field to an action component such as InstantAction.
  - This means that action names and descriptions are automatically localized.
- Any data fields that previously took in an action mapping data node must now take the id of the action entity prototype instead.
  - This also affects maps, which must be updated to be used.
  - Most of the cases for this are with "toggleAction:" nodes.
- For any downstream custom mapping actions, see the action migrator in https://github.com/space-wizards/space-station-14/commit/ba026a4e4e4b3d0779d6cf20eee6d2c7a9c92277 to automatically map them to the new format.

### CODE REVIEW

**Comment by mirrorcult** [comment]
-1k loc diff GOAT pr

**Comment by DrSmugleaf** [comment]
> -1k loc diff GOAT pr

works exactly the same btw

**Comment by moonheart08** [comment]
god bless

**Comment by deltanedas** [comment]
suddenly 10 conflicting prs :trollface:

**Comment by SinisterSamtaro94** [comment]
https://github.com/space-wizards/space-station-14/issues/19959. there seems to be an issue with this and narcolepsy.

**Pull request merged**
