### PR TITLE
Hitscans can no longer go through airlocks

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR 
I have seen nukies and xenos get fucked over lasers going through airlocks frequently which seems to be kind of the meta. So this solves the issue by preventing hitscans from going through any kind of airlock
**Screenshots**

**Changelog**

:cl:
- tweak: Lasers can no longer go through airlocks.

### CODE REVIEW

**Comment by Elijahrane** [comment]
Lasers are light. If you can see through them, then lasers should be able to go through them.

**Comment by metalgearsloth** [comment]
Being able to shoot nukies through airlocks and firelocks with no recourse is pretty busted.

**Comment by Elijahrane** [comment]
If you want to do this without making the game extremely inconsistent you should do it by adding opaque fixtures to those airlocks, making them harder to see through, too.

**Comment by mirrorcult** [comment]
this seems like a fundamentally different issue. if this is an issue then being able to shoot through windows will be an issue too. just make lasers not hit as hard/less accessible/lower ammo

**Comment by DogZeroX** [comment]
Sure, let me remove the lasers from cargo. I'm pretty sure Salvage players would be okay with it :trollface:

**Comment by DogZeroX** [comment]
Problem is that lasers are basically the perfect weapon against nukies most of the time. Considering they frequently cause breaches and basically free barricades for people that use lasers. I saw people shooting through edge airlocks which makes no sense. Should probably give traitors a laser to buy too.

**Comment by Peptide90** [comment]
Any way to refract the laser and make it tangent off once it goes through, making it less accurate, or just reduce damage.

**Comment by keronshb** [comment]
This is a thing that happens in SS13 too where people will build halls of glass mazes and use lasers to shoot the nukies. Who in turn, at least on some servers, can just plow through the glass/grilles with some weapons (L6 saw). I don't remember if they pass through see-through airlocks on SS13. That would be considerably harder to deal with compared to just regular or reinforced glass.

**Comment by ike709** [comment]
Going through *actual glass airlocks* is fine, going through other airlocks & firelocks is cringe.

**Comment by DogZeroX** [comment]
My repo broke and found out that hitscans go through edgelocks so that needs to be fixed please.

**Pull request closed without merging**
