### PR TITLE
Revert "add breakers to power batteries"

### PR DESCRIPTION
**Pull request by metalgearsloth**
Reverts space-wizards/space-station-14#16903

Resolves https://github.com/space-wizards/space-station-14/issues/17595

### CODE REVIEW

**Comment by deltanedas** [comment]
evil

**Comment by deltanedas** [comment]
i have made better

**Review by Emisse — APPROVED** [review]

**Comment by metalgearsloth** [comment]
> i have made better #17646

Doesn't seem to address the part where it's a huge PITA for legitimate gameplay and makes sabotage very easy.

**Comment by deltanedas** [comment]
@metalgearsloth merg noob

**Pull request merged**
