### PR TITLE
Adds to the ghost the possibility of seeing jobicon and antagonist

### PR DESCRIPTION
**Pull request by Baptr0b0t**
## About the PR

Adds to the ghost a button to see the icons of the players job (like Sec Hud) and nuclear ops and non-head revolutionary after 30min of the roundstart

## Why / Balance

fix https://github.com/space-wizards/space-station-14/issues/22808
On average, after 30 minutes, the nuclear operators, revolutionaries and zombies are mostly discovered and enter the combat game phase, reanimations become rarer. this action will allow the spectator to better enjoy and more easily follow the fights. The antagonist and thief remain hidden throughout the round.
## Technical details

An action is added when the player enters the ghost entity and deleted when he leaves it (like other ghost actions).
This action is directly controlled by the server to switch the state of the components in the ghost allowing the player to see the icons or not.

## Media

image
*Need to be change

- [] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Add class ShowAntagIconsComponent : Component (Content.Shared/Overlays/ShowAntagIconsComponent.cs)
Add class ToggleIconEvent : InstantActionEvent (Content.Shared/Ghost/GhostComponent.cs)

Add EntityUid:  ToggleIconActionEntity (Content.Shared/Ghost/GhostComponent.cs)
Add EntProtoId : ToggleIconAction (Content.Shared/Ghost/GhostComponent.cs)
Add Logtype : MetaGaming (Content.Shared.Database/LogType.cs)

Add Resources: ghost-gui-toggle-icon-visibility-popup (Resources/Locale/en-US/ghost/ghost-gui.ftl)
Add Resources: ghost-gui-toggle-icon-visibility-timer-popup (Resources/Locale/en-US/ghost/ghost-gui.ftl)
Add prototype : ActionToggleIcon (Resources/Prototypes/Entities/Mobs/Player/observer.yml)

**Changelog**

:cl: Baptr0b0t
- add: Added button as a ghost to see non-head revolutionary, nuke ops, zombie and icon job after 30min

### CODE REVIEW

**Comment by Errant-4** [comment]
I think it would be great if this also included the Rev icons, and they were off by default

**Comment by Hmeister-fake** [comment]
This should be disabled when you die for the first 10 minutes or so of being dead, so you can't unintentionally (or intentionally) metagame

**Comment by Errant-4** [comment]
Here is an idea, let ghosts toggle it whenever, but _log it_ when they turn it on, so admins have access to that information during an investigation

**Comment by Baptr0b0t** [comment]
> This should be disabled when you die for the first 10 minutes or so of being dead, so you can't unintentionally (or intentionally) metagame

Did you know how long it take for a corpse to rot, it can be the best moment for activate this action ? Thank for the idea

**Comment by Hmeister-fake** [comment]
> Here is an idea, let ghosts turn it on immediately if they want, but _log it_ if they do, so admins have access to that information during an investigation

Make it a big pop-up aswell that warns the person not to metagame.

**Comment by Doru991** [comment]
Tbh I'm not sure if the average player should be trusted with freely knowing who is syndie or not immediately after dying, on the other hand this will help observers accurately report self-antagging which is something I'd be grateful for.

**Comment by deltanedas** [comment]
should be limited to round removed people, maybe controlled by cvar if you trust players to not metagame

**Comment by Baptr0b0t** [comment]
I think the best thing is to do like “the spirit is gone”, when you want to see this Hud, which makes it harder to transmit the information (because we know that ghost roles can already have plenty of information but there is already a warning). This seems good to me because I miss this function when I die permanently (left in space or gibbed) of someone without really knowing why. Also I will deactivate the revolutionaries view by default and put it behind this hud. Be free to give new idea if you think it can be better.

**Comment by Zap527** [comment]
I really like this as a way to both help observers report self antags and generally have a better time knowing where the action is and who's worth following. This will make ghosting so much more engaging.

However, since revival after ghosting is very possible, this can lead to people accidentally spoiling themselves and seeing who the traitors or headrevs are. Yes, a big "Plz no metagame :)" popup could work (as suggested a bit above), but it's a bandaid fix as once you know the antagonists, you're losing a part of the game and you become unable to engage with investigation in a meaningful way without it being considered metagamey. And that's not even considering the sizeable chunk of players who will just NRP their way into randomly murdering antags.

The easiest way to solve this is to just make it kind of like ghost roles where once you toggle this your soul moves on and you become unrecoverable, but then this raises issues of a bunch of people becoming soulless before the paramedic can even get to them since they wanted to see what's going on.

Perhaps make it still remove your soul, but also so that you need to wait a certain ammount of time for the option to become available, or wait until their body starts rotting? I think this addresses the most major player issues I can see popping up. (though it does still introduce some annoying waiting around but we cant have the cake and eat it too).

**Comment by Emisse** [comment]
in some servers in ss13 it made you unable to be revived if you did, not sure the best way to make that distinction but it does make observer gameplay a lot better

**Comment by metalgearsloth** [comment]
Would rather get admin signoff given the significant implications it has for the memory aspect as is. @Chief-Engineer

**Comment by Baptr0b0t** [comment]
> in some servers in ss13 it made you unable to be revived if you did, not sure the best way to make that distinction but it does make observer gameplay a lot better

> Here is an idea, let ghosts turn it on immediately if they want, but _log it_ when they do, so admins have access to that information during an investigation

image

image

Also, the ability to see rev and zombie icon been removed for entity with ghost component and replaced by ShowAntagIconComponent

**Comment by nikthechampiongr** [comment]
> I think it would be great if ~this also included the Rev icons, and~ they were off by default

A pr to make rev visibility a cvar already exists #22194.

**Pull request closed without merging**
