### PR TITLE
Revert "Buff the AME until somebody fixes engineering"

### PR DESCRIPTION
**Pull request by moonheart08**
Reverts space-wizards/space-station-14#24806

# Why?
After a quick discussion with @EmoGarbage404, apparently the original issue(s) leading to this have been patched.
Power supply issues from rad collection was patched in https://github.com/space-wizards/space-station-14/pull/24978, though I don't think this behavior was changed for Tesla?

**Changelog**

:cl:
- tweak: AME power output is no longer super-buffed. Larger stations will now require multiple engines to stay powered.

### CODE REVIEW

**Comment by Flareguy** [comment]
This should probably have a changelog.

**Comment by moonheart08** [comment]
> This should probably have a changelog.

I completely forgot as reverts don't have the CL template, one sec.

**Comment by EmoGarbage404** [comment]
@Partmedia had concerns but i think it could just use testing? i haven't really heard about reports in game

**Comment by FairlySadPanda** [comment]
@PJB3005

**Comment by thebadman4662** [comment]
We had tesla only yesterday. The flickering drove station mad till they hooked AME back up.

**Comment by moonheart08** [comment]
> We had tesla only yesterday. The flickering drove station mad till they hooked AME back up.

pain, sounds like tesla power sources need the same tweak made (effectively adding smoothing capacitors.)

**Comment by Partmedia** [comment]
> We had tesla only yesterday. The flickering drove station mad till they hooked AME back up.

What map was this on?

**Comment by EmoGarbage404** [comment]
> pain, sounds like tesla power sources need the same tweak made (effectively adding smoothing capacitors.)

tesla coils appear to just charge a battery on hit and then the network draws from that internal battery. they seem to be fine.

**Comment by superjj18** [comment]
has someone made teslooses/singulooses not round ending/unreactable yet?  If not its too soon for this.  I always thought the reason ame was buffed was because teslooses/singulooses were way to common and way too destructive without any meaningful counterplay IE the particle decelerators being absolutely useless

**Comment by EmoGarbage404** [comment]
>  always thought the reason ame was buffed was because teslooses/singulooses were way to common and way too destructive without any meaningful counterplay IE the particle decelerators being absolutely useless

nope that wasnt why it was buffed

**Comment by Partmedia** [comment]
I did some testing on Meta with Tesla and the reverted AME. The problem is that the single-core round-start AME + the Tesla coils that the station is mapped with are not enough to keep the station powered, see attachment:

image

You can see where the lights would blink (the AME charge goes to zero). I suspect this is also true on other large stations. So if we just go revert this now this problem is going to come back.

So my proposed solutions:

1. Ask mappers to go test and fix power, e.g. add more round start AME cores, Tesla coils, etc. so that the station can actually be powered with two correctly set up power sources, for **every single map**
2. Increase Telsa output
3. Increase baseline AME output

(1) is probably the "right" fix but would require a lot of effort. Is someone willing to do this?

**Comment by mirrorcult** [comment]
2 seems like an equally correct fix here

**Comment by EtereohZ** [comment]
I don't know if it's related, but I've experienced the flickering problem with the TEG, even when it's producing enough to power the station.
I could be just some type of setups, as I'ts not always present.

**Comment by Partmedia** [comment]
> 2 seems like an equally correct fix here

Agreed.

> I don't know if it's related, but i've experienced the flickering problem with the TEG, even when it's producing enough to power the station. I could be just some type of setups, as i'ts not always present.

In order for this to be useful, you're going to need to tell us more about the setup, the map you experienced the problem you are, other information, screenshots, reproduction, etc.

**Comment by EtereohZ** [comment]
So, I set up my own server for the TEG, but noticed flickering with the AME in use, which was very weird.
So I decided to wait until I play a normal round, I'll try to record then.

**Comment by EmoGarbage404** [comment]
Tesla has good enough output now. Someone should check and make sure TEG and Singulo also function and that there's not extra issues with SMES ramping.

**Comment by Barrett-S** [comment]
I've had significant power flickering issues from every power source lately (full SMESes too), mainly towards the beginning of the shift. Makes crew that rely on a computer or machine for their job very upset, with seemingly no way to fix it.

**Comment by Partmedia** [comment]
> I've had significant power flickering issues from every power source lately (full SMESes too), mainly towards the beginning of the shift. Makes crew that rely on a computer or machine for their job very upset, with seemingly no way to fix it.

Thanks for letting us know. I believe you and your report and do think there are some other problems lurking around. But if you could recall what map or maps, types of engines were being used, how often/when it happens (you already told us "towards the beginning of the shift"), and any other information you may think could be relevant (even if it's not), that could help us reproduce the issue and get to the bottom of this.

(Of course what would help us the most is if you could come up with a list of steps to do to be able to reproduce this on a single-person server, or a video showing the steps leading up to the issue, or a round number and approximate time stamp, that would be extra appreciated.)

**Comment by moonheart08** [comment]
Did you make sure no SMESes were shorted out? (A SMES connected to itself can cause this behavior.)

**Comment by deltanedas** [comment]
The Flicker definitely happens without shorting as i dont think any map has roundstart shorted smeses

**Comment by Partmedia** [comment]
I reproduced the issue by setting up the AME on Meta and waiting for a bit (the time it takes for AME fuel to go from 1000 to 970). The blink barely registers on the sensor monitoring console but looks like this:

image

It also happens with a debug generator after a little while:

image

So while there's something going on, it's not related to the AME buff.

**Comment by Partmedia** [comment]
Removing "do not merge" since we believe that the root cause of the problem is a bug in the parallel pow3r solver (https://github.com/space-wizards/space-station-14/pull/28488)

**Comment by UbaserB** [comment]
I tried running the station purely off of TEG the other night and crew ended up complaining about power flickers despite it working seemingly fine. Might be related, not sure.

**Comment by Partmedia** [comment]
Thanks for the PR. In the future, please remember to test even these seemingly-simple-looking changes in-game.

**Pull request merged**
