### PR TITLE
hot potato buff

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

- more damage over time
- shorter timer
- bigger boom

## Why / Balance

the hot potato is a meme weapon that is so bad it isn't even worth using for the laughs. you throw away 4TC for the barest chance to crit someone, during which you will immediately out yourself as a syndie so bad you will get obliterated.

At the very least, it should be strong enough to hopefully kill at least one person. 

## Technical details

n/a

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The hot potato now does more damage over time, has a shorter timer, and has a larger explosion.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
maybe it should't do the over time damage to the person who activated it, at least until its passed back to them

**Comment by SpeltIncorrectyl** [comment]
Up the TC price and make it gib.

**Comment by JoeHammad1844** [comment]
that would be pretty honkin funny

**Review by LankLTE — APPROVED** [review]
Worth a shot honestly.

**Pull request merged**
