### PR TITLE
increases pillAmount limit

### PR DESCRIPTION
**Pull request by SirDragooon**
## About the PR
To better help Chemists balance the strength of pills after the new overdose update (#8844), the max pill amount you can make is increased to 50 
**Screenshots**
image

**Changelog**

:cl:
- tweak: The ChemMaster4000 pill limit is increased to 25

### CODE REVIEW

**Review by Peptide90 — COMMENTED** [review]
Code is fine but 50u pills seem potent. Is there a benefit to this beyond being gamed? 15u to match an injection might have been better but I’m no chem main.

**Comment by EmoGarbage404** [comment]
> Code is fine but 50u pills seem potent. Is there a benefit to this beyond being gamed? 15u to match an injection might have been better but I’m no chem main.

I think 50u as an upper limit isn't horrible. It is pretty potent, but i think it's on the part of the chemist players to determine the potency of the pills they put out. Considering most chems have an OD ceiling of around 30u, 50u seems pretty reasonable to me.

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by SirDragooon** [comment]
> Code is fine but 50u pills seem potent. Is there a benefit to this beyond being gamed? 15u to match an injection might have been better but I’m no chem main.

i don't really know to be honest. my main issue with chem at the moment is that you can't really dose your pills all that well, if you're making bulk batches. in my chemist rounds i usually make batches of 600+ u of bicar and with the 10 pill limit i often have difficulties getting below the od threshold.

**Comment by wrexbe** [comment]
Just to clarify, this change makes it so you can create 50 separate pills instead of 10. I think that is too many pills. How about changing it to 25? That will let you make a non-lethal batch of pills.

**Comment by metalgearsloth** [comment]
Is there even a delay to creating 50 pills? Are they being spawned all in the same tick?

**Comment by mirrorcult** [comment]
> I want this merged and top capacity of single pill returned back to 50 units. Chemists making overdosing Bicaridine pills is feature, chemists should be able to fail at dosing pills, either accidentally or on purpose. Capping pill capacity to current 25 units is removal of game mechanic depth.

yeah I'm fine with this I'll do it later

**Comment by wrexbe** [comment]
@metalgearsloth 
It puts them on the floor, and in your hands. The right click menu gets a bit slow in debug.

**Comment by SirDragooon** [comment]
Sorry for not paying any attention to my own pr 😅 I'll try to implement the ideas people have come up with, just give me a little time.

**Comment by wrexbe** [comment]
I'm going to raise it to 25. If someone wants the machine to spit out more then that, a better solution is needed so it doesn't lag the context menu, maybe it can spit out pill bottles or something.

**Pull request merged**
