### PR TITLE
Guaranteed Big Tanks in Emergency Closets

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Got rid of the random chance to have small oxygen/nitrogen tanks in emergency closets and guaranteed the big ones.

## Why / Balance

It feels like emergency supplies shouldn't really be random, and the fire closets already had guaranteed large tanks with no problems so far.

I view the smaller emergency oxygen tanks that people start with as just a stopgap you can use until you make it to an emergency closet.

It's kind of a disappointment when you only end up finding another small tank when there's a tesloose or a singuloose going on. It doesn't really make sense for the huge emergency locker to have a tiny oxygen tank...

## Technical details

yml change to emergency closets

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- tweak: Guaranteed larger oxygen and nitrogen tanks in emergency closets.

### CODE REVIEW

**Comment by thebadman4662** [comment]
Damn, those small ones are useful though, in fact how slimes gonna get small ones now? Mug someone and replace it in nitro cannister?

**Comment by Plykiya** [comment]
> Damn, those small ones are useful though, in fact how slimes gonna get small ones now? Mug someone and replace it in nitro cannister?

I can add them to the emergency O2 medkits that come with the small oxygen tank.

**Comment by thebadman4662** [comment]
Yeah, that would be great.

**Comment by Ghagliiarghii** [comment]
I might support random like 50% small o2, 50% small n2, 10% double small o2, 10% double small n2 independent probability spawns in addition to guaranteed large tanks

**Comment by Plykiya** [comment]
> I might support random like 50% small o2, 50% small n2, 10% double small o2, 10% double small n2 independent probability spawns in addition to guaranteed large tanks so as not to make the small tanks super rare for the instances you need them (for example you have something on your back you need to carry (a gun / jetpack maybe?) so you use a tank in a pocket slot instead)

I'd be willing to add a random chance for the smaller ones with the guaranteed large tank.

**Comment by metalgearsloth** [comment]
> It feels like emergency supplies shouldn't really be random, and the fire closets already had guaranteed large tanks with no problems so far.

If emergency supplies are guaranteed what's the point of having them, the stakes get dropped to the floor when everyone is guaranteed to survive everything.

**Comment by Plykiya** [comment]
(discord continuation)
seems like the conclusion is to... get rid of the chance of large tanks altogether from emergency closets (and fire closets?) in favor of using tank dispensers or crafting it at autolathes, so I'll just close the PR. I'm fine if it's intended to go to specific places to get the larger tanks, it was just really annoying knowing when you got screwed by a 20% chance to get a larger tank from a closet

**Pull request closed without merging**
