### PR TITLE
Decrease AME stability damage

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR
This pr makes it so that overloading the ame doesn't cause as much instability damage.

## Why / Balance
Blowing up the AME can often end entire rounds. All it takes is someone with to press up on the injection button a few time, wait 40 seconds, and the station will often have power issues afterwards. With the current damage values in game, you have less then 50 seconds to turn off the ame before it blows, and unless you're right next to engi it is often hard if not impossible to make it in time. And even if you do make it in time, you run the risk of killing yourself just to turn it off do the 20 damage jumps. With the new values, the person will have to double check the fuel count to see if there's even enough to blow the ame, and may have to stick around to make sure it doesn't get fixed. With these changes engineers have about 3 minutes to fix the problem before it is too late.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Increased the stability of the AME, it now takes about three minutes for the AME to overload.

### CODE REVIEW

**Comment by deltanedas** [comment]
skill issue

**Comment by Equivocateur** [comment]
If engis dont notice AME going red theyre not going to fix it. A better solution is to have the AME tell everyone on engi comms that its taking damage

**Comment by liltenhead** [comment]
I mean that is a solution, but the ame is ungodly loud when it is overloading. I think that's more noticeable than the controller turning red which only happens when the ame is severely damaged. As of right now if you see the controller turn red, you have like 2 injections before its gone.

**Comment by NancokPS2** [comment]
> If engis dont notice AME going red theyre not going to fix it. A better solution is to have the AME tell everyone on engi comms that its taking damage

Those kinds of solutions are boring.  
It means you no longer have to worry about keeping an eye on the AME since you'll be warned.  
Preventing antag play merely reduces the point of the game, limiting how much damage they can cause to the station (proportional to effort) is a better solution.

**Review by Partmedia — APPROVED** [review]
I think an automatic comms warning is too much (without a way to sabotage the alerts computer).

I think this change is reasonable because increasing the time it takes to blow gives a bigger incentive to patrol important parts of engineering, since with 50 seconds unless you're constantly guarding it the station is too big to constantly make rounds back to the AME.

**Comment by NancokPS2** [comment]
With a hackable alerts PC (with this hack being more accessible than having to break into CE room or similar) would be a pretty great balance.  
People would have no reason to constantly go to the AME every minute BUT it would also make people get complacent, making antag play easier to pull out at the cost of more effort.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
