### PR TITLE
Moths can now eat produce

### PR DESCRIPTION
**Pull request by z9ctn4fn**
## About the PR
Moths can now eat produce

## Why / Balance
SS13 parity.

## Technical details
Adds a tag called MothFood to FoodProduceBase and added to moth stomachs.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Moths can now eat produce.

### CODE REVIEW

**Comment by Errant-4** [comment]
For the record, you don't need abort your entire PR and start over with a new branch just because you forgot a few small unrelated changes left in by accident. You can just change those things back to be identical to the master branch, and commit that change to your working branch. It will remove the unwanted changes from the PR

**Comment by SlamBamActionman** [comment]
Let's pretend SS13 doesn't exist for a second, because SS14 is its own game.

I feel letting moths eat produce makes their unique dietary restriction less unique and interesting. Botany being able to grow berries and only berries to solve station hunger makes the choice for them less interesting, and moths needing to raid closets and AutoDrobes for food seems more fun from both a gameplay and thematic sense.

**Comment by NotSoDana** [comment]
Sounds good, cuz real moths can eat fruits, berries, honey or smth like that. Moreover, this tag can be very useful in adding dishes, that only mothpersons can eat.

**Comment by slarticodefast** [comment]
In addition to adding the tag to FoodProduceBase you will also need to add it to any child that overwrites them. Or are they merged automatically?

**Comment by z9ctn4fn** [comment]
> Let's pretend SS13 doesn't exist for a second, because SS14 is its own game.
> 
> I feel letting moths eat produce makes their unique dietary restriction less unique and interesting. Botany being able to grow berries and only berries to solve station hunger makes the choice for them less interesting, and moths needing to raid closets and AutoDrobes for food seems more fun from both a gameplay and thematic sense.
> 
> If moth players feel the diet is currently too restrictive and actively hinders them, sure, then I can see this helping. But that isn't any feedback I've seen so far.

I am a moth player, and it felt restrictive.

**Comment by z9ctn4fn** [comment]
That's why I made the Pr.

> In addition to adding the tag to FoodProduceBase you will also need to add it to any child that overwrites them. Or are they merged automatically?
Every item with the base as FoodProduceBase will inherit all it's properties and tags.

**Comment by z9ctn4fn** [comment]
> For the record, you don't need abort your entire PR and start over with a new branch just because you forgot a few small unrelated changes left in by accident. You can just change those things back to be identical to the master branch, and commit that change to your working branch. It will remove the unwanted changes from the PR

Yeah, my bad.

**Comment by Hrosts** [comment]
> I am a moth player, and it felt restrictive. That's why i made the PR.

As a fellow moth player, I agree that currently there's too little in terms of food options for moths. Still, I think you're approaching it from the wrong angle.

I think the following would be a better option:

- Adding flavors to moth food
- Adding a moth snack vendor, with leather, silk, wool-based food, some of which can also be worn. One of the issue I often feel is that you have to run to the one corner of the station to get food. This can improve the situation.
- Adding moth-consumable food for chef to make, and adding precursors for that food to chef's vendors/lockers.

Your approach, as it was said, just reduces the uniqueness of the diet.

I guess it's also much more simple to add than what I'm proposing.

**Comment by Hrosts** [comment]
Also, can moths eat arachnid's web silk? Seems like a good opportunity to add some arthropod solidarity

**Comment by SlamBamActionman** [comment]
> > I am a moth player, and it felt restrictive. That's why i made the PR.
> 
> As a fellow moth player, I agree that currently there's too little in terms of food options for moths. Still, I think you're approaching it from the wrong angle.

I swear, once my schedule clears up I _will_ add Cotton Candy.

**Comment by LeIronGoat** [comment]
> Let's pretend SS13 doesn't exist for a second, because SS14 is its own game.
> 
> I feel letting moths eat produce makes their unique dietary restriction less unique and interesting. 

Its funny, because a lot of times I want to point to 13 and remind people how open and expansive systems are, why little things do matter, etc. But in this case I agree. I think there's opportunity here to continue this more "unique" diet in theme and flavor.


> * Adding moth-consumable food for chef to make, and adding precursors for that food to chef's vendors/lockers.


Hear me out, it hasn't entirely bloomed in full picture in my head yet, but it could be funny if we went down a route where the chef could replace something like pizza dough with cloth/leather/fabric. Then you could make a "pizza" where its the pizza ingredients atop moth-edible food.

Probably too much effort because than a lot of foods would need double the sprites, but the idea of a moth eating fabric covered in cheese and pizza sauce is funny to me.

**Comment by Boaz1111** [comment]
moth main here, current diet good

**Comment by Brandon-Huu** [comment]
SS14 is not a SS13 clone, at least I hope.

**Comment by z9ctn4fn** [comment]
> SS14 is not a SS13 clone, at least I hope.

It's not, it's already an improvement with gridinv, not being bound by tiles, better combat, and more. I see SS14, in the direction it's going in, to be a improved version of SS13.

**Comment by LankLTE** [comment]
I'd really like to see moth recipes added to the chef (and this was always the intention, it's just something nobody has done). As a whole I think giving them more stuff they can eat is fine but it should follow their current diet.

**Comment by NotSoDana** [comment]
> I'd really like to see moth recipes added to the chef (and this was always the intention, it's just something nobody has done). As a whole I think giving them more stuff they can eat is fine but it should follow their current diet.

Well... i have a list of ideas for some dishes based on moths diet, but not enough time for sprite it. I think this PR and comments are like a call to action lmao.

**Comment by LankLTE** [comment]
For the reasons I said above, maintainers have agreed to close this PR.

**Pull request closed without merging**
