### PR TITLE
Halve moth's heat damage modifier

### PR DESCRIPTION
**Pull request by Vermidia**
## About the PR

Changed the 1.3x modifier for moths from heat damage to a 1.15x modifier.

## Why / Balance

So, moths are a mostly vanilla species, they get to move normal speed when gravity is off, and they are resistant to cold (a rarer damage type) and take 30% more damage from heat.
Thing is, we already have a species that's super heat weak - Dionas. And they have much better boosts, being resistant to blunt and slash, and getting a second chance after death (sort of). Moths being in the same niche while having very few upsides just makes them weaker than most species, which sucks because moths are classics and very cute.

I didn't change how much damage moths take from being on fire (It's 3x the normal amount!!) or that their preferred temperature is lower, since those make sense and are more what I'd imagine the more heat damage was supposed to accomplish anyway, fits their fluffy bugness.

~~Why shock and why buff the damage? Bug zappers are generally what you think of for bug weaknesses (and I stole it from tg). For damage, in general low insignificant modifiers are generally frowned upon, and shock is slightly rarer than heat (with its main sources being the tesla, electric anomalies, and electrified doors/hacking). 50% is a lot more impactful while still not making moths much weaker than other species.~~ The 30% Lizard heat buff was removed because it made them too good for their little downsides, while moths still kept their opposite damage modifiers making them the opposite case of not having much upsides for their existing downsides.

Note the shock argument isn't valid for this change anymore.

## Technical details

N/A
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A
**Changelog**

:cl:
- tweak: Moths only take 15% more damage from heat.

### CODE REVIEW

**Comment by LankLTE** [comment]
Not a fan of this for what I've discussed on discord. Shock as a damage type is basically nonexistent and I think "bug zappers" isn't really valid when that's just, overwhelming amounts of electricity pushed into a small creature. Tone down the fire weakness if its' too much but as far as balancing goes I don't think this is the best way to go about it.

**Comment by Vermidia** [comment]
After some discussion, just decided to halve the current heat damage modifier (30% -> 15%)

**Comment by ps3moira** [comment]
Moths should have some form of direct weakness to balance their speediness in zero-g rather than being slightly power crept.

**Comment by Hanzdegloker** [comment]
Personally I think one nice way to see if a species is in a good spot is how much they're played. Moths in their current form are common enough. The playerbase choose them despite the situational upside. Hell with moonshoes from Sci having been added you can enjoy the speedy no grav buff all the time! Also despite all the work on Dionas I still see 4 moths for every diona, if that.

**Comment by metalgearsloth** [comment]
Discussed internally and opting to close as a 15% modifier is so minor it may as well not exist.

**Pull request closed without merging**
