### PR TITLE
Allow the construction of gas storage canisters.

### PR DESCRIPTION
**Pull request by Vordenburg**
## About the PR 

This PR allows players to make their own gas storage canisters out of plasteel.

**Screenshots**

**Changelog**

:cl:
- add: Gas storage canisters can be made through the construction menu now.

### CODE REVIEW

**Comment by asperger-sind** [comment]
Storage canisters are worth 1,000 credits, this PR allowing you to craft them out of a bit of plasteel might be an issue balance-wise because Cargo could just print money out of essentially thin air.

**Comment by mirrorcult** [comment]
not a fan of these being extremely easy to construct personally

**Comment by Interrobang01** [comment]
You could have these cans be some sort of "makeshift gas canister" that sell for nothing and have very low gas capacity, so normal gas canisters aren't invalidated.

**Comment by moonheart08** [comment]
this is painfully op, canisters should not be constructable. Buy only.

**Pull request closed without merging**
