### PR TITLE
cancelable brig timers

### LINKED ISSUE #25024: Brig timer label display broke
## Description

Brig timers will not display inputted labels unless they were mapped with that label.

If they were mapped with a label, then if a timer is started then the time will display on top of the label which will be unreadable.

Timers additionally refuse to cancel. The only way to cancel them is to input a lower time and start the timer again.

**Reproduction**

- [ ] Scenario a:

1. Start Timer
2. Try to cancel it
3. It doesn't work and now your prisoner is stuck for the next 300 years.

- [x] Scenario b:

1. Input label
2. Label does not update
3. Cry

- [x] Scenario c:

0. Be on atlas where brig timers by default are labelled.
1. Start timer
2. Watch as it remains a garbled mess until it finishes. 

**Screenshots**

image

**Additional context**
 

C.C.TextScreenSystem Seems to not properly handle brig timers.

### PR DESCRIPTION
**Pull request by graevy**
## About the PR

fixes #25024
makes it so clicking the timer button while it's counting down will just end the timer 

## Technical details

in `SignalTimerSystem`, i added a check for `HasComp<ActiveSignalTimerComponent>` in `OnTimerStartMessage`. i made some of the update methods update `TextScreenVisuals.DefaultText` in addition to `ScreenText` so the clientside `TextScreenSystem` would fallback on its ordinary timer finish behavior to write the text after finishing a timer.

i also trimmed some redundant code in `SignalTimerSystem` and `TextScreenSystem` which was essentially a hack around a missing `TextScreenVisuals.ScreenText` write in `ScreenSystem` (which i added).

## Media

dotnet_NGwszCikO6

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: clicking the brig timer button will now cancel its countdown

### CODE REVIEW

**Comment by Terraspark4941** [comment]
🆑 not 💿

**Comment by Terraspark4941** [comment]
Also does this work with client-side prediction disabled?
(Asking because I ran into a problem with the brig timers regarding no-prediction)

**Comment by graevy** [comment]
> 🆑 not 💿

only the finest pull requests at 4:30am

**Comment by graevy** [comment]
> Also does this work with client-side prediction disabled? (Asking because I ran into a problem with the brig timers regarding no-prediction)

i am staring at #26554

**Pull request merged**
