### PR TITLE
New Nukie Song

### PR DESCRIPTION
**Pull request by he1acdvv**
made a new nukie song lel.

## About the PR

I added a new Nuke Detonation Song.

## Why / Balance

I felt like making a nukie song, then i did it. People suggested me i do a PR on it.

## Technical details

none.

## Media

https://github.com/space-wizards/space-station-14/assets/128906677/d8e4adbd-7476-4e06-899e-ee300c1e13e4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: mryikes
- add: New Nuke Detonation Song "Clearly Nuclear".

### CODE REVIEW

**Comment by TheShuEd** [comment]
shouldn't the track be exactly 2 minutes long since it starts 2 minutes before the explosion?

**Comment by metalgearsloth** [comment]
> shouldn't the track be exactly 2 minutes long since it starts 2 minutes before the explosion?

Server can actually get audio file length since audio rework though the code hasn't been updated for it.

**Comment by Ki-wis** [comment]
shit fucking slaps and should be merged asap

**Comment by Dragonjspider** [comment]
I will never complain about more bangers for nukies

**Pull request merged**
