### PR TITLE
Weapon Overhaul (NEED HELP)

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes certain weapon sprites completely or with more consistent inhands.

I REQUIRE AID: The crushers and grenades have inhand variants that I have tried and failed to implement. If anyone could be so kind as to code them for me, that'd be grand.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Centcomm has dishes out factory-new versions of old weaponry. Many melee weapons and bombs have been visually changed or tweaked!
- tweak: Certain weapons have been given straps, enabling them to be equipped on the belt or back. These include the crusher, the crusher glaive, the kitchen knife, the combat knife and the survival knife

### CODE REVIEW

**Comment by Alekshhh** [comment]
talked to it with sloth, but basically crusher line needs lights and the recharge like the PKA has. grenades will just work as always but you can actually see them in your hand while inactive and active

**Comment by Partmedia** [comment]
Could you please separate out the sprite changes that are done from the YAML changes? That way we can merge the work that you already have.

**Comment by JoeHammad1844** [comment]
i dont like these new sprites, they look too detailed and dont match the style of the rest of the game

**Comment by metalgearsloth** [comment]
me like sprites but grug say split pr sorry.

**Pull request closed without merging**
