### PR TITLE
Techfab resprite + department fab sprites

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

ONLY A SPRITE PR.

in the future we'll probably want department fabs so i'm throwing in the sprites now so we don't have to care about it later.
also resprites the existing techfabs because they looked a bit dorky.

## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by AjexRose** [comment]
ammofab my beloved

**Comment by notquitehadouken** [comment]
crrrI s p  y

**Comment by UbaserB** [comment]
crunch

**Comment by EmoGarbage404** [comment]
fuck it we selfmerge

**Pull request merged**
