### PR TITLE
Pickup/drop sounds for items

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## Why / Balance
feels better

## Technical details
``EmitSoundOnDrop`` and ``EmitSoundOnPickup`` existed but were never used

## Media

https://github.com/user-attachments/assets/7899fe98-ef32-44ea-9b2d-fc2be5026db7

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Added pickup/drop sounds for some items.

### CODE REVIEW

**Comment by NotSoDana** [comment]
Earfuck. Pls, no..

**Comment by Hanzdegloker** [comment]
Earfuck. Pls, yes!

**Comment by bruhmogus** [comment]
just no, please, i do not want someone to spam q and click to kill us

**Comment by baddiePRO** [comment]
I wouldn't mind this if the sounds were clientside only

**Comment by bruhmogus** [comment]
> I wouldn't mind this if the sounds were clientside only

they're still LOUD AS FUCK and serve only to make your ears hurt

**Comment by EmoGarbage404** [comment]
kinda feels a bit loud in the video but there's nothing to compare it to. these should probably be a bit on the quiet side tho.

**Comment by TheDoctor1977** [comment]
Some of these, like the paper, are alright, but that clicking sound on the matter bin and igniter is particularly ear-grating. Does this apply to weapons? If so, it would make stealthily getting the drop on someone basically impossible, since people would just remember the sounds and be alerted when they hear them,

**Comment by Dutch-VanDerLinde** [comment]
> Some of these, like the paper, are alright, but that clicking sound on the matter bin and igniter is particularly ear-grating. Does this apply to weapons? If so, it would make stealthily getting the drop on someone basically impossible, since people would just remember the sounds and be alerted when they hear them,

it shouldn't be as ear grating, the video is outdated, I made the sounds quieter for the igniter and stuff

**Comment by Krovotushka** [comment]
Would be cool to have possibility of setting the volume of these sounds cuz some people will still complain about it (not me)

**Comment by bruhmogus** [comment]
it'd be best to just not merge this since it'd be so ungodly loud and i get the feeling the sound applies to EVERY time an item enters a hand, which would mean nukie gets fucken shot because they grabbed their gun

**Review by UbaserB — CHANGES_REQUESTED** [review]
After internal maintainer discussion, we've come to the consensus that the volume should be much quieter, alongside being rate-limited (to prevent sound spam) with a limited radius and only enabled for pickup.

**Pull request closed without merging**
