### PR TITLE
Cosmetic changes for the roboticist

### PR DESCRIPTION
**Pull request by LinkUyx**
## About the PR

**Media**

Content Client_fkk8UW6hDF
Content Client_fpJM080cQs
Content Client_J90FvFoWE4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new items for roboticist.
- tweak: Changed robodrobe sprite and items in it.

### CODE REVIEW

**Comment by Emisse** [comment]
i dont love these they look a bit too syndi moded silly boated boy coded

**Comment by potato1234x** [comment]
sprites look very out of place

**Comment by potato1234x** [comment]
also please dont undo my vend polishes make the vending machine look shinier like this 
image

**Comment by moonheart08** [comment]
this looks like syndicate equipment.

no thanks

**Pull request closed without merging**
