### PR TITLE
Shuttle Assembly Crate

### PR DESCRIPTION
**Pull request by youarereadingthis**
Adds a "shuttle assembly crate" for 2500pts to cargo with the following contents:
- 1 shuttle console board
- 1 wallmount substation board
- 1 shuttle APU board
- 1 handheld GPS
- 1 inflatable door

Also reduced the price of thrusters and gyroscopes since they seem overpriced for their purpose on the station.

As a tortured yet hopeful shuttle enjoyer I feel the process of making a shuttle is just so much more tedious, buggy, time consuming, and risky than it needs to be. It's such an excellent feature that it pains me how impractical and frustrating it can be right now.

Even when you go through the trouble of optimizing your routes and refining the process, there are just so many things that can go wrong and so little time to enjoy it thanks to the constant shuttle recalls that randomly go through at annoying times.

This crate should give anyone knowledgeable and ambitious enough to try making a shuttle more leeway to do so. The shuttle APU generates just enough for a truly rudimentary shuttle to roam around in space, yet not enough to keep 4 thrusters and a gyro going.

The wallmounted utilities cannot be used when placed on walls right now unfortunately, though you can still place them on the floor and walk over them. Certainly better for a cramped shuttle. They fit the theme as well.

## About the PR 

**Screenshots**

image

**Changelog**

:cl: ShuttleEnjoyer
- add: Added a new Cargo crate with a shuttle console board, shuttle power boards, a handheld GPS, and a single inflatable door.
- tweak: Shuttle thrusters and gyroscopes cost less.

### CODE REVIEW

**Comment by moonheart08** [comment]
This is 1) too cheap and 2) makes salvage redundant. I do not feel this is a good idea.

**Comment by youarereadingthis** [comment]
Salvage seems to be mainly useful for thrusters and gyros ime.
If they find other things then they don't seem to bother bringing them even if asked.
Getting the generator, substation, and shuttle board is the truly painful part sadly and this resolves that at least.
Would you approve if I put the thrusters and gyros back or even raised the price?

**Comment by moonheart08** [comment]
> Salvage seems to be mainly useful for thrusters and gyros ime. If they find other things then they don't seem to bother bringing them even if asked. Getting the generator, substation, and shuttle board is the truly painful part sadly and this resolves that at least. Would you approve if I put the thrusters and gyros back or even raised the price?

I do not want to actively encourage cargo to not do their job even more than shuttle building already does.

**Comment by youarereadingthis** [comment]
I see your reasoning now. I have seen them ignore their job to do that before.
Mainly I play as engineer when shuttle building, which is a job that I find is in an easier position to do so.

My main motivation for doing this is that the time it takes for R&D to get to that point and the overall walking around to find the people who you need to help(unless you're an asshole and steal important stuff like a substation) makes shuttle building very impractical for anyone at all.

That's not counting the risk of disasters happening which halt everything, or any places you need just refusing to do their job.
Any ideas for improving this without distracting salvagers too much?

**Comment by Peptide90** [comment]
Can you place the APU then build a wall?

Anyhow relating to the PR. It might be better to just have this as a shuttle power crate with like two APU boards and one or two wall mount substations. Personally I like the idea of science or salvage having to obtain the shuttle board plus the other components can be bought I believe.

**Comment by youarereadingthis** [comment]
> Can you place the APU then build a wall?
Yup. The only limitation is that to interact with it directly you need to remove the wall.
Wallmounted NanoMeds have the same problem last I checked.
> shuttle power crate
Sounds good, and should discourage stealing substations(very mean). I'll give that a try.

**Comment by youarereadingthis** [comment]
Shuttle board removed. Price increased. Only 1 substation + APU still.
Hopefully when/if sensitive items can be locked then the QM will have to approve them first.
In MRP at least I can see QMs easily refusing and telling the salvagers to get back to work.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
