### PR TITLE
Uplink extention: nukie edition

### PR DESCRIPTION
**Pull request by Vaaankas**
## About the PR

Rebalancing the nukie (and some agent) arsenal in the uplink.

This PR is aimed at:
- Raising up the viability of guns and grenades, to try to stay on par with the desword meta.
- Compensating the loss of Nukies' chemical station and subsequent lack of meds.
- Increasing the cost-effectiveness of implants.

Changes made:

- Combat medkits now feature a dermaline syringe instead of 2 tricordrazine pills.
- Combat medkits are now available for purchase for 5 TC.*

- Freedom implants now universally cost 8TK and are available to NukeOps.*
- Microbomb implants are now available to NukeOps for 2 TC.*
- Macrobomb implants are now 20 TC instead of 25.

- New uplink item: Ammo bundle is now available for purchase for 15 TC. Contains 4 magazines for the C-20r, 4 drums for the Bulldog, and 2 ammo boxes for the L6 SAW.
- New uplink item: Grenadier chest rig is now available for purchase for 12 TC. Contains 4 explosive grenades, 2 EMP grenades and 2 minibombs.*
- New uplink item: Combat medipen is now available for purchase for 8 TC. It is a single-use injector containing 25 units of Omnizine and 5 units of Tranexamic Acid.*
- New uplink item: Medical bundle is now available for purchase for 20 TC. Contains a combat medkit, a defibrillator, 3 combat medipens and other minor medical gear.*

- Mosin ammo crate full of AK mags replaced with a 50 round ammo box
- Fixed syndicate dufflebag sprites
- Added Dermaline and Hyronalin syringes
- Nukie Agent now starts with 1 combat medipen in their dufflebag 

*edited since the original post

**Changelog**

:cl: vanx
- add: The Nuclear Operatives have found a reliable supplier of ammunition and medical equipment. Check your uplink for new offers.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
> Compensating the loss of Nukies' chemical station and subsequent lack of meds.

Nukies have a chemvend.

**Comment by LankLTE** [comment]
Honestly, most of this is fine. There's one issue I want to talk about, though.
Making the Freedom Implanter 5TC is, in my opinion, a _really_ bad idea. Ignoring nukies since I don't think it's nearly as problematic on them, getting a freedom implanter makes it near-impossible for Security to arrest a competent syndie. If it's 5TC just about every damn syndie on the station is going to be running around with one, which when combined with the pistols sec were just given, only encourages them to beat or shoot a suspected syndie to death rather than apprehend them. Syndies are *supposed* to be able to be arrested.

**Comment by Equivocateur** [comment]
> getting a freedom implanter makes it near-impossible for Security

Hitting them with a stunbaton *once* immobilizes them good enough to hit them again. And in practice freedom implant is a mark for death upon first use

**Comment by LankLTE** [comment]
> Hitting them with a stunbaton _once_ immobilizes them good enough to hit them again. And in practice freedom implant is a mark for death upon first use

Freedom implanters stim when used, don't they? I've seen people get stunned, cuffed, then tased _three times_ while running and still couldn't be caught because of this. I think it counters security too effectively to be 5 TC.

**Comment by Equivocateur** [comment]
> Freedom implanters stim when used, don't they?

what

**Comment by LankLTE** [comment]
> what

Somehow I've been living a lie. Heard it did that somewhere (and I guess saw someone stim themselves after using it). Ignore me then, I doubt it's as big of an issue as I made it out to be

**Comment by asperger-sind** [comment]
Imo the prices are insanely high for the healing items.

**Comment by Vaaankas** [comment]
> Imo the prices are insanely high for the healing items.

Could you please elaborate? I think the updated combat medkit (with sulture and mesh) is pretty potent, and so is the 25 units of omnizine in a single use hypo. Defib can have a use in some rounds too.

**Comment by Vaaankas** [comment]
Updates:
- Mosin ammo 1984, it is no longer a box full of AK mags, instead it comes as an ammo box with 50 rounds of .30
- Implants prices swap and slight buff, with the microbomb being 4TC (still NukeOps exclusive) and the freedom one being 8 TC

**Comment by Vaaankas** [comment]
On another pass, i think its fine to lower the price for meds, also added a second combat medipen to the meds bundle to justify the price. I dont want to lower the medipen cost tho.
- Combat medkit is now 5 TC
- Medical bundle is now 20 TC and includes two combat medipens

**Comment by Vaaankas** [comment]
- Nukie Agent now starts with 1 combat medipen in their dufflebag (nukies recieving free samples)

**Comment by JoeHammad1844** [comment]
I think the microbomb should be cheaper, 2TC maybe, in ss13 they were free and came implanted by default. looking forward to this getting merged

**Comment by Vaaankas** [comment]
> I think the microbomb should be cheaper, 2TC maybe, in ss13 they were free and came implanted by default. looking forward to this getting merged

I like this

**Comment by JoeHammad1844** [comment]
I think the price of the grenade rig is a little high, compared to the ammo bundle (which is priced perfectly fine by the way) it just has way less use for more TC

 grenades just aren't something you're gonna use in 80% of fights, they can be useful in some cases like throwing it through a door before you go in or spacing areas but that requires map control, if you're having a shoot out in a hallway they just aren't applicable, and having all that for 18TC and not being able to keep ammo in your rig is just too expensive for not all that good of a payoff

I think somewhere less than 10TC would be a good price point

**Comment by Vaaankas** [comment]
> I think the price of the grenade rig is a little high, compared to the ammo bundle (which is priced perfectly fine by the way) it just has way less use for more TC
> 
> grenades just aren't something you're gonna use in 80% of fights, they can be useful in some cases like throwing it through a door before you go in or spacing areas but that requires map control, if you're having a shoot out in a hallway they just aren't applicable, and having all that for 18TC and not being able to keep ammo in your rig is just too expensive for not all that good of a payoff
> 
> I think somewhere less than 10TC would be a good price point

You make a fair point, grenades are definetely a very fun to use yet not too effective (and especially not cost-effective) options in the uplink. The whole point of them being in a bundle is to make them accessible to nukies but without being too underpriced, as it still includes minibombs and EMPs, so i'll try and think of a good price point.

**Comment by JoeHammad1844** [comment]
I think 15TC or less would be a better price for the medical bundle, you cant really keep a combat medkit and defib in your bag and have enough equipment to actually fight. and its basically just buying two combat medpens and getting a free combat medkit, there needs to be some kind of quantity discount there, and if your teammates buy microbomb implants the defib becomes useless.

**Comment by JoeHammad1844** [comment]
also, for those who dont know, microbombs explode instantly on death, destroying your gear so no one you don't like can loot you, it can also be activated at any time, even when stunned or crit

**Comment by Vaaankas** [comment]
> I think 15TC or less would be a better price for the medical bundle, you cant really keep a combat medkit and defib in your bag and have enough equipment to actually fight. and its basically just buying two combat medpens and getting a free combat medkit, there needs to be some kind of quantity discount there, and if your teammates buy microbomb implants the defib becomes useless.

i could add a third medipen in there, but now im a bit concerned of medipen nukies becoming too independent from the agent. I think relying on the medic is good for teamwork.

**Comment by JoeHammad1844** [comment]
you forgot to update the post about the grenade rig cheapening

**Comment by JoeHammad1844** [comment]
> Honestly, most of this is fine. There's one issue I want to talk about, though. Making the Freedom Implanter 5TC is, in my opinion, a _really_ bad idea. Ignoring nukies since I don't think it's nearly as problematic on them, getting a freedom implanter makes it near-impossible for Security to arrest a competent syndie. If it's 5TC just about every damn syndie on the station is going to be running around with one, which when combined with the pistols sec were just given, only encourages them to beat or shoot a suspected syndie to death rather than apprehend them. Syndies are _supposed_ to be able to be arrested.

the freedom implant only has 3 uses, and in ss13 they were availiable for 5TC (I think) but to be fair both sides have far more powerful equipment

**Comment by JoeHammad1844** [comment]
far more powerful compared to ss14, that is

**Comment by Vaaankas** [comment]
I think nukies having more meds overall is good still. 
- Medical bundle now includes 3 combat medipens.
- Changed combat medipen cost 10TC -> 8TC.

**Comment by Vaaankas** [comment]
time to merge beg

**Pull request merged**
