### PR TITLE
Add quantum paper

### PR DESCRIPTION
**Pull request by gardspirito**
## About the PR
This PR introduces a new item to the game, called quantum paper, which can be found in paper bins of the station.
Quantum paper is a paper that manifests superposition, entanglement and bluespace properties, and is designed to speed up communication and small logistics between departments, so there's theoretically less need to constantly yell over the radio, there's less chance for the order to get lost, there's less chance to forget miss order fulfilment, there's less running around involved when you just need to pass a single small item.

**Superposition:** whenever placed on the ground, quantum paper will hop between tables nearby when not directly looked at.

**Entanglement:** a piece of quantum paper can be split into two entangled pieces, called "quanper" and "patum" respectively. Quanper and patum contain the initial text of the paper and cannot be changed with pen (unless cybersun pen is used). However, any stamp placed on one piece of the paper is instantly replicated on the other, no matter the distance. This allows to use the quantum paper to place orders to various departments and treat the stamp as "order fulfilled" flag, with minimal risk of losing the announcement over the radio.

**Bluespace:** when either quanper or patum is lit on fire, a small-scale bluespace teleportation happens, that *explosively* transports up to 4 inventory slots worth of items to the other side, destroying the entanglement. This obvious safety hazard does not completely eliminate walking (or faxing) since you need to already have the copy at the destination first, but could cut some repetitive walking back and forth.

Quantum entangled papers can be faxed, but this halves the amount of slots worth of items bluespaced (4 → 2 → 1 → 0).

## Why / Balance
Personal opinion and reasoning: I was not satisfied with how communication across different departments turns out to be in practice, with orders being forgotten about, missed announcements over the radio, the dread of constantly walking back and forth between same two points (which obviously needs to be present in the game to ensure random bumps, horrible deaths and confusion, but only to some extent). Moreover, I'm a fan of paperwork, and I believe that this PR empowers the paperwork with actual, albeit small, actual gameplay sense and advantages.

Rarity: quantum paper is not specifically rare, but the time spent rummaging through the paper bin could probably be better spent just walking back and forth to the cargo. Moreover, quantum paper is one-shot and needs to be replaced after each use, which limits its applicability.

Quantum paper could be used as a small explosive device. Orders carelessly left on the table (and conveniently teleported to the table closer to maintenance due to the superposition) could be lit on fire by bad actors to ensure a small explosion somewhere across the station.

Quantum paper cannot be used directly as a communication device, but there's still a possibility of communicating information by using stamps or bluespacing a container with an actual note.

As noted earlier, quantum paper can be faxed, so there is an opportunity to "fax a bomb" or teleport two slots worth of items across the station without walking anywhere in the first place.

## Technical details
This PR adds the following systems:
* Superposed: server-side system that tracks SuperposedComponent entities dropped near tables (PlaceableSurfaceComponent) and constantly scans for the MindComponent observers facing the superposed object. Whenever the object stops being observed, it teleports to a random surface from the predefined list.
* PaperQuantumSystem: handles split/disentangle verbs of the paper, listens for new StampedEvent and replicates the stamp on the entangled paper, listens for new IgnitedEvent and teleports nearby items to the destination, applying new TemporaryExplosionResistant to them, and produces an explosion at the destination.
* TemporaryExplosionResistant: server-side system that utilizes existing GetExplosionResistanceEvent to temporarily block all explosion damage on the teleported items, not including fire.

It touches BinSystem, extending paper bins with WeightedRandomEntityPrototype loot table which includes both paper and quantum paper. This PR also touches PaperSystem and FaxSystem and make them aware of the quantum papers, specifically not letting quanper and patum to be edited by non-cybersun pens and preventing problems related to [quantum teleportation](https://en.wikipedia.org/wiki/Quantum_teleportation).

## Media
Quantum paper can be found in paper bins, 15% chance per paper:
bildo

Quantum paper/quanper/patum hop around nearby tables when not directly looked at:

https://github.com/user-attachments/assets/28418204-59f5-4b25-ad9b-2b51fa1dcebf

Quantum paper can be split into quanper/patum, which get stamped simultaneously:

https://github.com/user-attachments/assets/088e5485-d720-4205-a9ac-f75f9f251ec2

bildo

Quanper/patum could be used to teleport up to 4 items:

https://github.com/user-attachments/assets/1da1c5cb-3170-4c80-8575-3819fca4a68f

Hands are considered an item. Unfortunately, since we can't seemingly amputate hands without Newmed, it just deals slash damage.
The destination paper will stay burning forever unless destroyed:
bildo
Unfortunately, this intended behaviour allows for the issue #31992 to thrive.

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Added quantum paper that randomly spawns in the station's paper bins and can be split into two synchronized copies that replicate stamps and can be used to teleport items.

### CODE REVIEW

**Comment by TheShuEd** [comment]
Outer wild reference?
Quantum jumping looks bad without FOV restriction

**Comment by gardspirito** [comment]
> Outer wild reference?

*Oh no, our cover was blown, retreat! retreat!*
> Quantum jumping looks bad without FOV restriction

I initially thought of tying it to PVS, but I'm afraid that PVS is way to big to give the effect a chance to happen, ever.

Tying it to FOV sounds like a better idea, but I guess this will require clients to raise network events on see/unsee? I will have a closer look at how this could be done later.

**Comment by gardspirito** [comment]
> Quantum jumping looks bad without FOV restriction

I looked at the code more closely, and, well, actual render distance is locked behind rendering part of the game:

https://github.com/space-wizards/RobustToolbox/blob/f682fb9cc76e74876121ace2b988a7f3ba307b84/Robust.Client/Graphics/ClientEye/EyeManager.cs#L48

I'm not sure how to approach this.

**Comment by TheShuEd** [comment]
Given the advent of Holopads, I don't see any point in it at all anymore. 

This mechanic is conceptually interesting, but I don't think it solves the problem mentioned in the PR due to intuitiveness issues, and, now, duplication of functionality with Holopads

**Comment by TheShuEd** [comment]
Thanks for the PR, anyway

**Comment by gardspirito** [comment]
Have fun developing the game, I hope to see it grow! I just have a feeling that there should be some better way for discussing small ideas for those who'll want to contribute to SS14 in the future.

**Comment by TheShuEd** [comment]
Yes, I agree that it didn't turn out very nicely with that PR, I apologize

**Comment by TheShuEd** [comment]
Given the ratio of contributors to maintainers, it's best to discuss it periodically in discord to get more attention on PR. As you can see, we are slightly overwhelmed by the amount of PRs

**Pull request closed without merging**
