### PR TITLE
Change wilhelm sound with weh for reptiles

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

instead of wilhelm scream reptiles will weh

## Why / Balance

 funny reptile

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no

### CODE REVIEW

**Comment by SpeltIncorrectyl** [comment]
The point of the wilhelm scream is it can only happen through very rare chance.
You can weh whenever you want.

**Comment by lzk228** [comment]
> You can weh whenever you want.

weh doesn't have a chat trigger
https://github.com/space-wizards/space-station-14/blob/7fefcbc6fb3cfbfb1bb7ba49d58a0f4ab8421181/Resources/Prototypes/Voice/speech_emotes.yml#L401-L407

https://github.com/user-attachments/assets/b75338e1-ca4c-49a4-9853-7fce73eb3285

**Comment by Cojoke-dot** [comment]
> > You can weh whenever you want.
> 
> 
> 
> weh doesn't have a chat trigger

I think they mean with the plushie? As in there is an easy way to cause the noise so it would not be as special to roll or may not even be noticed.

**Comment by regenpower** [comment]
i agree, weh is very common (too common now due to loadouts), either from the plushie making the sound, or from the weh juice, so if you get the 1 in 7.5 trillion chance of doing a wilhelm scream, it will just be another weh, and not as noticable / special

**Pull request closed without merging**
