### PR TITLE
Tweak mixed drink ratios

### PR DESCRIPTION
**Pull request by waylon531**
## About the PR

This PR changes all of the mixed drinks that are a mixer + an alcohol to be more in line with their real-life counterparts. Before this PR most of those drinks had twice as much alcohol as mixer. This is quite boozy, so my PR brings them to an acceptable ratio of half as much alcohol as mixer.

## Why / Balance

This doesn't change balance. It makes drinks taste a little bit different which has a mild effect on RP, and it messes with bartender's current muscle memory which will be kind of a pain. It also makes it a little easier to mix drinks if you've made them in real life before, and you can go more off intuition vs. memorizing the space station recipe for it.

## Technical details

Tweaked some values in drink recipes and in their corresponding reagants.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Centcomm is tired of the crew drunkenly wandering the station and starting brawls. Many mixed drinks now have half as much alcohol.

### CODE REVIEW

**Comment by Partmedia** [comment]
Normally I wouldn't be in favor of changing recipes, but since:

1. Messing up a missed drink recipe doesn't matter, it just adds extra stuff that doesn't make the product undrinkable, and
2. The ratios are closer to what they are in real life

I think this is fine. One concern I have is that it shouldn't be impossible to get the effect, so make sure to double check that you can get that effect after a reasonable number of drinks.

**Comment by waylon531** [comment]
It looks like the amount of ethanol in a drink doesn't actually make much difference because of some bugs(?) in the reagent system. 

 - No matter the amount of ethanol processed in a metabolism tick, the drunk effect will always be increased by the same amount, 2 seconds. This is due to the scale being calculated wrong in `Content.Server/Body/Systems/MetabolizerSystem.cs`. However, in the master branch there's a multiplier in the drunk function to make this effect reasonable again. I'm kind of scared of fixing this though because so much in this game is metabolized ...

- The drunk effect is inconsistent if you're playing a race with both a stomach and a liver. The stomach processes ethanol at a whopping 0.5 units per tick, but vodka only gives 0.2 ethanol per tick. The order that reagents are processed is randomized, so sometimes the liver gets to process the alcohol first, and sometimes the stomach gets to process alcohol first and flushes it out of the player's system before it can make it to the liver and give the drunk effect. This means that you have a 50/50 chance for alcohol to have any effect. However, because of current tuning, the drunk effect continuously extends itself very slightly unless you're very unlucky. I'm not sure if the stomach is supposed to process ethanol in the same way as the liver and give the drunk effect, or if the stomach shouldn't flush ethanol out of the player at all. (I'm leaning towards the second)

I'm looking to fix up these issues but they don't impact the recipe change at all. It does mean that the ethanol amount in mixed drinks is somewhat dubious, but changing the value has exactly zero gameplay effect right now except for on diona, the only race that processes alcohol slowly enough for ethanol to build up. This would lessen the drunk effect for them but they can still get drunk quite easily, the effect will just last a little less now.

**Comment by Partmedia** [comment]
Thank you for doing the investigation and analysis for me :)

Since you have determined that there is little to no in-game impact, I'm merging now.

**Comment by Partmedia** [comment]
Thank you very much for your (first!) contribution. I look forward to seeing your future work on the issues you've uncovered.

**Pull request merged**
