### PR TITLE
Aloe prototype fix

### PR DESCRIPTION
**Pull request by kerisargit**
The prototype of the aloe food does not match the composition of the grown aloe. Now all aloe contains Dermaline.

## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Aisu9** [comment]
don't you need aloe and stelibiline to make siderlac?

**Comment by Korbolaynen** [comment]
Yes, it is, the problem is in the composition of the prototype itself. Aloe contains the substances "aloe" and "dermaline" in space-station-14/Resources/Prototypes/Hydroponics/seeds.yml, that is, which is grown in hydroponics. And here is the aloe food from space-station-14/Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml is already the substances "aloe" and "kelotane". This means spawner aloe or admin spawn aloe will have a different composition than seed grown aloe.

**Comment by Emisse** [comment]
fix your changelog

**Comment by Korbolaynen** [comment]
changelog fixed

**Comment by deltanedas** [comment]
its not fixed

**Comment by Partmedia** [comment]
Thank you for your (first time!) contribution. In the future, please review the [Changelog guidelines](https://docs.spacestation14.io/en/getting-started/pr-guideline#changelog). Since this change was relatively small, and the Changelog was not formatted correctly, I opted to remove the Changelog entry. We appreciate your contribution; thank you again.

**Comment by kerisargit** [comment]
Thanks a lot for the comment and the link! I will study everything you sent me. I'm working with Git for the first time, so not everything is going well so far.

**Pull request merged**
