### PR TITLE
Update Core

### PR DESCRIPTION
**Pull request by HE54Z**
!!ATTENTION!! This is my first proper pull request, so keep that in mind.

## About the PR
Changes 3 main things on the Core map, the nitrogen chamber at the bar, the connection ports to distro in south solars and the disposals system in the bar and evac.

## Why / Balance
The nitrogen chamber that was added recently to the bar was a neat idea in practice, but has some issues. 
For example: The atmos fix nitrogen markers would cause the room to be filled to the absolute limit with nitrogen, and the airlock not bolting would cause the bar to flood with nitrogen. Thus I have built a new nitrogen chamber, which has two linked airlocks and a directional fan underneath both airlocks. 
The connections to distro in south solars have been removed, due to them having two portable scrubbers on top of them, which would cause people to think it was a connection to waste, flooding distro with waste gas if a scrubber was connected. 
Two disposals units in the bar were removed, due to me not finding any good places to move them to. 
And the evac disposals system was changed due to a small detail bugging me.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Core-0

**Changelog**

:cl: HE54
- tweak: Updated Core

### CODE REVIEW

**Comment by HE54Z** [comment]
I realise that the directional windows on the nitrogen chamber may seem inconsistent with the general style,
and I do not know if that will be a major issue.

**Comment by IProduceWidgets** [comment]
I'm 95% certain the lack of tiny fans was intended.

**Comment by HE54Z** [comment]
> I'm 95% certain the lack of tiny fans was intended.

If it truly is intended, I will fix it soon.

**Comment by lzk228** [comment]
@UbaserB

**Comment by UbaserB** [comment]
I was in the middle of working on the PR fixing vox box among other things so please, please ask me first before making any PRs

**Comment by UbaserB** [comment]
> Sorry, I did not think about contacting you before making this PR. I can close it if you wish.

I know this is your first PR and all, congratulations on that, but mapping is something that needs communication :despair:

**Pull request closed without merging**
