### PR TITLE
pettable tesla

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
title

## Why / Balance
for the brave

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by TheShuEd** [comment]
Merg immediately

**Comment by TheShuEd** [comment]
Add hearts particle!

**Comment by Ilya246** [comment]
> Add hearts particle!

done

**Comment by chromiumboy** [comment]
Doesn't do burn damage on petting it, major fail

**Comment by Ilya246** [comment]
> Doesn't do burn damage on petting it, major fail

petting is evil and would require an overhaul to support damage or effects on pet

**Comment by Ilya246** [comment]
test fail highly likely unrelated since this is an yml change

**Comment by K-Dynamic** [comment]
Pet the singulo

Petting either should open ghost role or make you immune to their effects :trollface:

**Comment by Cyber-Finn** [comment]
dew it

**Comment by deltanedas** [comment]
> Petting either should open ghost role or make you immune to their effects :trollface:

just wear insuls and you are 100% safe from tesla, as long as you dont touch it

**Pull request merged**
