### PR TITLE
Give skeletons flash immunity

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Added FlashImmunityComponent to BaseMobSkeleton

## Why / Balance

I'm browsing through issues I can address, https://github.com/space-wizards/space-station-14/issues/28886 exists and I want to get it closed one way or another...? It's sort of flavor for the species but they're already pretty strong so I wouldn't be surprised if it got rejected because they have to "see" somehow

**Changelog**

:cl:
- add: Skeletons are now immune to flashes.

### CODE REVIEW

**Comment by beck-thompson** [comment]
Yeah makes sense to me! I don't think it would be *too* powerful but I mostly play on MRP where skellies are friendly like 80-90% of the time

**Comment by slarticodefast** [comment]
Don't use FlashImmunityComponent. Remove the Flashed status effect from the whitelist instead. It is inherited from somewhere.

**Comment by Plykiya** [comment]
> Don't use FlashImmunityComponent. Remove the Flashed status effect from the whitelist instead. It is inherited from somewhere.

I'd have to redeclare every other status they can take, is that preferred over just adding this component?

**Comment by slarticodefast** [comment]
Previously there was FlashableComponent which I removed when turning it into a status effect. I think redeclaring the list of status effects should be fine, but all of the yaml files for mobs could probably use a cleanup with better inheritance. Using FlashImmunityComponent first allows the status effect, but then cancels it via another event. FlashimmunityComponent is better for protecting equipment.

**Comment by Plykiya** [comment]
> Previously there was FlashableComponent which I removed when turning it into a status effect. I think redeclaring the list of status effects should be fine, but all of the yaml files for mobs could probably use a cleanup with better inheritance. Using FlashImmunityComponent first allows the status effect, but then cancels it via another event. FlashimmunityComponent is better for protecting equipment.
> 
> Edit: Oh, it got merged already. Might need some cleanup. I'll do a PR later.

I would love to see what you do to improve the inheritance situation for mobs

**Pull request merged**
