### PR TITLE
Fix door electronics duplication

### PR DESCRIPTION
**Pull request by ShadowCommander**
## About the PR 
Fixed door electronics duplicating when doors were deconstructed and reconstructed repeatedly.
Added ContainerFill, a component that spawns items in containers. It is now equivalent to StorageFill, but the new one works with multiple containers.

**Changelog**

:cl:
- fix: Fixed door electronics duplication when deconstructing then reconstructing an airlock.

### CODE REVIEW

**Comment by mirrorcult** [comment]
this seems very sussy to me. at the very least, `ContainerFill` should really just be part of `StorageFill`. for example `StorageFill` could just take in a container ID to fill as an override rather than exclusively doing storage/entitystorage

**Comment by ShadowCommander** [comment]
I'll look at it. All Storages are Containers, but not all Containers are Storage.

**Comment by ShadowCommander** [comment]
I also tried to make ContainerFill able to fill multiple containers rather than just one.

**Comment by mirrorcult** [comment]
it'd be nice for them to be merged, in some way. containerfill might be better as a base to start from in that case

**Comment by ShadowCommander** [comment]
Should be equivalent to StorageFillComponent now. Should I do the YAML changes in this PR or a separate one?

**Comment by ShadowCommander** [comment]
Closed in favor of #11772. I will move other changes to a new PR.

**Pull request closed without merging**
