### PR TITLE
Add MIT license support

### PR DESCRIPTION
**Pull request by lzk228**
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
Aint MIT license only for code? and not for images

**Comment by PJB3005** [comment]
Yeah I don't know this makes a lot of sense.

**Comment by nikthechampiongr** [comment]
The MIT license only refers to software, putting it on images would be kinda meaningless.

**Comment by lzk228** [comment]
> Also webedit

even if I made these changes in github desktop, i wouldn't check if it works
because it's affect only on github

**Comment by VasilisThePikachu** [comment]
Still, even then. MIT is not a media license. It can only be used for source code. Is there a reason you want this?

**Comment by metalgearsloth** [comment]
Better off changing the sprite and using one of the other licences yeah.

**Pull request closed without merging**
