### PR TITLE
Clothes mate dyed clothes change

### PR DESCRIPTION
**Pull request by SinisterSamtaro94**
## About the PR
**About:**
#12464 
As per issue request, items have been moved to the hop lathe for printing. these include coloured clothes, scarfs, shoes and hats. This will be temporary but it also gives the hop something to do as now people might wish to request colour clothes.
the cloth required for these civilian clothing has been reduced to 150 cloth. This is due to the fact that now people might mass request prints of specifically coloured clothes ect.
**Future PR plans:**
- Creating a dye machine that might require paint products
- Moving the drip items that were in the clothes mate into spawning as part of maintenance loot tables 
- making any resource requirements for HOP lathe recipes when needed.

**Screenshots**

**Changelog**

:cl: Samtaro
- add: added dyed clothes, scarfs, shoes and hats  to the hop printing lathe
- remove: Removed Drip items like bunny ears from the clothesMate

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
isn't it a uniform printer not a drip printer

**Comment by Just-a-Unity-Dev** [comment]
you also have typos on the bartender uniforms causing the YAML linter to fail

**Comment by SinisterSamtaro94** [comment]
I removed all the drip clothes from the clothes mate and the issue request stated that temporarily leaving dyed clothes in the hop printer was a fine solution.

**Comment by Just-a-Unity-Dev** [comment]
¯\_(ツ)_/¯

**Comment by SinisterSamtaro94** [comment]
i can fix the bartender stuff. one moment

**Comment by SinisterSamtaro94** [comment]
Should be fixed now.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
Yea no, this just makes these items unreasonably hard to obtain on LRP. You need a better solution than "just give it all to the hop lol"

**Comment by SinisterSamtaro94** [comment]
other options i can do an mentioned to sloth were ideas of seperating drip into a drip machine and then also seperating dyed items into a dye machine that requires paints.

**Comment by moonheart08** [comment]
Clothings are not to be moved out of the clothesmate, they're just to be made colorable so there's fewer items clogging the machine.

**Pull request closed without merging**
