### PR TITLE
Several power infrastructure items are more shocking

### PR DESCRIPTION
**Pull request by tom-leys**
## About the PR
- Substations, SMESes, APCs and the AME controller are now shocking. I suggest you don't hit them.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Due to safety cutbacks, electrical devices like substations are more dangerous. Safety protocols demand you do not hit them. We strongly advise you not to bite them either!

### CODE REVIEW

**Comment by potato1234x** [comment]
logically these dont make much sense but gameplay wise this is perfect for rats destroying apcs

**Comment by asperger-sind** [comment]
I'm thinking it'd be nicer if they released an electricity "splash" after being attacked a few times, or just apply electrification not on the first hit; I don't see why hitting an APC once with your fist would make you go wzhzhzhzhwhzwhwzhwzhwhzzhhzhz

**Comment by potato1234x** [comment]
maybe just stun people instead of electrocuting them

**Comment by tom-leys** [comment]
Of course it's possible to reduce the level of shocking. But why are you hitting these things?

**Comment by metalgearsloth** [comment]
> Of course it's possible to reduce the level of shocking. But why are you hitting these things?

Accidentally in harm mode.

**Comment by mirrorcult** [comment]
i feel like these are uncommon enough that if you are hitting them by accident that is on you

**Comment by mirrorcult** [comment]
(and if you are hitting them by accident you are probably insulated anyway)

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
