### PR TITLE
Resprite & hand position correction of Nettle & Death Nettle

### LINKED ISSUE #25052: Nettle sprites need to be improved
## Description

The nettle sprites are really blurry and poorly off-centered in your hands. There's literally transparent pixels on the edges too.

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by MjrLandWhale**
## About the PR

This PR is a resprite of nettle and death nettle. Original sprites were not centered and lacked visual clarity/distinction. R/L hand locations for both plants were also incorrect. EX: some plant right hand sprites were located on a character's left hand depending on character orientation.
PR centers & resprites the main 'produce' sprites. Additionally resprites and corrects the hand locations for both plants.

## Why / Balance

Resolves #25052 
Duplicate of #25420 corrected to pull from a non-master branch
## Technical details

N/A
## Media

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

None

**Changelog**

:cl: landwhale
- tweak: Resprited Nettles & Death Nettles.

### CODE REVIEW

**Comment by Everturning** [comment]
the new ones look skrunkly (insult)
Hand sprites are good but like the item icons are scraggly and look bad

**Comment by EmoGarbage404** [comment]
> the new ones look skrunkly (insult) Hand sprites are good but like the item icons are scraggly and look bad

the new ones look fine. they look far better than the old jpeg'd ones. if you think you can do better than be productive and make some new sprites (insult)

**Comment by Everturning** [comment]
> > the new ones look skrunkly (insult) Hand sprites are good but like the item icons are scraggly and look bad
> 
> the new ones look fine. they look far better than the old jpeg'd ones. if you think you can do better than be productive and make some new sprites (insult)

my main complaint is the skinny-ness of the item icons, the old ones had big leaves and looked kinda fearsome while these look like the christmas tree from charlie brown, just a lil guy, a lil birthday guy on his birthday

**Comment by MjrLandWhale** [comment]
Not sure how you're seeing them as skinnier... All I did was ADD to the existing nettle sprite, replacing a lot of the vague gray pixels with more distinct green colors. Across the board the nettle icon is actually thicker than before. I can understand the issue you're having with the death nettles though. I probably included too much bright red for your liking. The intent was to evoke a clear "this is dangerous" mental image, but if you're getting christmas tree then I might have missed the mark. How does something like this look?
image

**Pull request merged**
