### PR TITLE
Changeling Sting Update

### PR DESCRIPTION
**Pull request by Jackal298**
updated sprite and added to vending machine when hacked by emag

## About the PR

I noticed that this drink has an outdated texture and I wanted to update it, I also added to the cola machine, it appears after applying the emag, you get two cans.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: when you emag a cola machine you will get two cans of Changeling Sting
- tweak: Changeling Sting sprite changed

### CODE REVIEW

**Comment by Jackal298** [comment]
- type: vendingMachineInventory
  id: RobustSoftdrinksInventory
  startingInventory:
    DrinkColaCan: 4
    DrinkGrapeCan: 2
    DrinkRootBeerCan: 2
    DrinkIcedTeaCan: 2
    DrinkLemonLimeCan: 2
    DrinkFourteenLokoCan: 2
  emaggedInventory:
    DrinkNukieCan: 2
    DrinkChangelingStingCan: 2

everything seems to be correct, just like on other machines

**Comment by Jackal298** [comment]
> cl should explicitly say emagging since you could say cutting mgr wire is hacking it too

maybe a problem with the sprite?

**Comment by deltanedas** [comment]
no just change the changelog to say emag not hack

**Comment by Jackal298** [comment]
> no just change the changelog to say emag not hack

I changed the descriptions, but how do I pass the final check?

**Comment by deltanedas** [comment]
ignore it ci is dead rn

**Comment by Jackal298** [comment]
I light a signal fire to attract attention

**Pull request closed without merging**
