### PR TITLE
add Healium and BZ gas

### PR DESCRIPTION
**Pull request by marc-pelletier**
## About the PR
Adds two new atmospheric gases, Healium, and it's precursor BZ. (Primarily restored from whateverusername0's lost BZ pull request)

BZ is created by mixing plasma and nitrous oxide in an explosive exothermic reaction. It's primary use is as a precursor in the generation of more complex gases, though for those seeking enlightenment, it is often used as a cheap substitute to frezon, albeit far more dangerous to consume. 

Healium is created in an exothermic reaction by mixing BZ and frezon at below room temperatures, though highest efficiency is achieved at lower temperatures. Healium is an expensive gas that has healing properties when inhaled, however, will also make you tired and slow. 

## Why / Balance
The addition of these gases is intended to add more variance to the atmos gameplay loop, as well as increase cross department cooperation as Healium generation is most efficient at temperatures achievable by hellfire freezers, and the gas can be used by medical to treat patients. At higher efficiencies, it is economical to sell the gas to cargo as it is worth more than it's parts, though those profits greatly diminish and disappear when generated at higher temperatures.  

## Technical details
[Mainly follows the specifications laid out here for generation](https://i.redd.it/rl46009i1bb61.png)

## 
[healium-production.webm](https://github.com/user-attachments/assets/55857c14-ea6f-41a7-9cfb-effd07ff9924)
[bz-effects.webm](https://github.com/user-attachments/assets/38184619-3cad-44fa-9cc5-27d41f407400)
[bz-slime-effects.webm](https://github.com/user-attachments/assets/95d65ed0-76ad-4f48-a07f-b21f502992ff)
[healium-effects.webm](https://github.com/user-attachments/assets/acfb940e-6d39-47e8-8470-918ee3c3afba)

## Requirements
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
No breaking changes are made

**Changelog**
:cl:
- add: Added BZ - a slime person sleeping agent and overall a toxic gas, which is made by mixing N2O and plasma under low pressures.
- add: Added Healium - a powerful sleeping agent with healing properties when inhaled. Made by mixing BZ and Frezon at low temperatures.

### CODE REVIEW

**Comment by marc-pelletier** [comment]
I'll need a lot of input on balancing them, but figured I would get something workable up that can be played with. Currently also lacking good sprites, particularly on the Healium side.

**Comment by mirrorcult** [comment]
anything but this please

**Comment by mirrorcult** [comment]
atmos needs actual gameplay not just copying TG slop, this changes absolutely nothing about atmos

**Comment by marc-pelletier** [comment]
>atmos needs actual gameplay not just copying TG slop, this changes absolutely nothing about atmos

It would hopefully increase the need for atmos to interact with more of the station and give atmos and the station a reason to hold onto the gases they create rather than sell them all.  I'm definitely not against other mechanics to add variety to atmos gameplay, but I feel like there are a lot of people enjoy atmos as it is now.

**Comment by WhiteGorila** [comment]
Helium flood the station for infinite regen

**Comment by CBozo** [comment]
> atmos needs actual gameplay not just copying TG slop, this changes absolutely nothing about atmos

Some of the most interesting tried and true atmos content we could add is "TG slop." I don't want to fall into the fallacy of tradition, but they've been doing this longer than most of us, so I wouldn't dismiss their content as "slop."

**Comment by cohanna** [comment]
> atmos needs actual gameplay

such as?
Atmos is pretty barebones with the gutting of frezon use now. After distro and waste is setup all atmos can really do is teg. Sure they can do engie stuff but if they wanted to focus on station power and repairs they would have joined the round as an engie...
Adding more gasses with neat effects IS adding atmos gameplay. Especially when these gasses have interplay between departments.

> this changes absolutely nothing about atmos

does every atmos change need to be so large that it changes the way atmos plays? Why cant we add more *stuff* to atmos?

**Comment by Ilya246** [comment]
atmos is already kinda annoying to work with, so i'm not sure people would be able to make any real use of those gases
i believe tg has RPD and pipe stacking, which make atmos actually okay to work with

**Comment by marc-pelletier** [comment]
Those would definitely be helpful, but I was thinking these would be late game gases anyway, as healium would have some pretty strong uses. It would also give atmos techs more of a reason to work together by setting up different parts simultaneously to get healium earlier in a round.

**Comment by saga3152** [comment]
It looks like it heals too slowly, cryo does it much better and easier

**Comment by marc-pelletier** [comment]
>It looks like it heals too slowly, cryo does it much better and easier

So at the moment, it's just tied to how much you're breathing in. If you lower the temperature, increase tank kpa, and breathe close to pure healium, it heals incredibly fast. Maybe too quickly. I might need to add some sort of cap for it.

**Comment by Sarahon** [comment]
Give us actual helium so we can make the station people squeaky!

**Comment by LankLTE** [comment]
Similar to what mirrorcult said- currently we feel that the actual gameplay of making gasses is rather subpar. It largely boils down to just following a setup you found online or made in a previous round and then waiting. We'd rather see atmos' core gameplay improved before (further) encouraging them to spend their entire round inside of atmosia to occasionally give med / other departments some gas.

**Comment by BasedUser** [comment]
> atmos needs actual gameplay not just copying TG slop, this changes absolutely nothing about atmos

> Similar to what mirrorcult said- currently we feel that the actual gameplay of making gasses is rather subpar. It largely boils down to just following a setup you found online or made in a previous round and then waiting. We'd rather see atmos' core gameplay improved before (further) encouraging them to spend their entire round inside of atmosia to occasionally give med / other departments some gas.

maintainer refuses to play on an LRP server and discover round to round external environment consequences, covering live on honk tv

**Pull request closed without merging**
