### PR TITLE
Atmos crab pet: Tropico!

### PR DESCRIPTION
**Pull request by revsys413**
## About the PR

Instead of a couple of maps having an unnamed crab mob, Atmos in every map now has a proper pet crab: Tropico, the noble defender of Atmosia! He is a round-start ghost role, and can be converted to a Revolutionary to honor his namesake.

## Why / Balance

Atmos's pets are in a weird state--sometimes it's Exception, sometimes it's a nameless crab, sometimes it's nothing at all. This PR would add a new, consistent pet for Atmos in the form of Tropico the Crab. Note that Exception hasn't been removed from any of the maps, just had his spawner moved, if anything.
Tropico is a new round-start ghost role, as well. The idea behind this is to give Atmos a new player-controlled companion to keep them company during lonely shifts holed up in Atmos, as well as something to rubberduck ideas off of. Tropico can also be converted into a Revolutionary as a nod to the game Tropico, which gives Atmosian Revolutionaries another dimension to consider. It also is just kind of funny I think.

## Technical details

A new mob and spawner have been added for Tropico, using MobCrab as a parent, and the spawner has been added to the atmos rooms in all current maps. MobCrab has also been edited slightly to facilitate players controlling it. Specifically, mostly for Tropico, a new crab replacement accent has been added, and MobCrab has been given arachnid speaking sounds for when it talks. When successfully petting, crabs will now play an arachnid laugh sound, since it's the most similar sound in the game to sounds that real life crabs make.

## Media

https://youtu.be/_eHYbIYwLx8

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

- add: Added a new pet in the form of Tropico the Crab, the stalwart companion of Atmosia! Viva!

### CODE REVIEW

**Comment by revsys413** [comment]
with the ghost role removed, this should be the CL instead:
- add: Added a new pet in the form of Tropico the Crab, the stalwart companion of Atmosia! Viva!

note: leaving the ability to convert him into a rev even though it doesn't do anything is intentional because it's funny

**Comment by Emisse** [comment]
can you remove the mapping changes, multiple maps being changed in one pr isnt standard we like to atomize them, its easier to just incorporate additions into the normal mapping updates

**Comment by revsys413** [comment]
> can you remove the mapping changes, multiple maps being changed in one pr isnt standard we like to atomize them, its easier to just incorporate additions into the normal mapping updates

oh that makes a lot of sense actually, i’ll fix that in a bit

**Comment by Emisse** [comment]
turn off rev convertible and change the changelog

**Comment by revsys413** [comment]
> turn off rev convertible and change the changelog

do i have to edit the CL in the original PR post for it to work?

**Comment by revsys413** [comment]
also, should i add it to the list for the thief antag or is that out of scope for this PR

**Pull request merged**
