### PR TITLE
Omnizine and donk-pockets

### PR DESCRIPTION
**Pull request by DmitriyRubetskoy**
## About the PR 
Adds Omnizine, a reagent which heals small a small amount of every damage type per tick. A small amount of omnizine can be found in warmed donk pockets. 
Adds dink-pockets, a lizard version of donk-pockets with less nutritional value.
Adds glucose to berry-pockets.

**Screenshots**

**Changelog**

:cl: CrudeWax
- add: Added omnizine. A reagent which heals any type of damage when ingested.
- add: A small amount of Omnizine can be found in warm donk pockets.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
We were originally porting vg as a basis which is why there's dexalin

**Comment by DmitriyRubetskoy** [comment]
I mean would it hurt?

**Comment by metalgearsloth** [comment]
Is it effectively tricord? Been a hot minute since I played

**Comment by mirrorcult** [comment]
omnizine is tricord but it also heals brain damage and such iirc

**Review by SweptWasTaken — APPROVED** [review]

**Pull request merged**
