### PR TITLE
Nerf syndicate minibomb

### PR DESCRIPTION
**Pull request by BulletGrade**
## About the PR 
The current syndicate minibomb is really powerful and can effortlessly ruin the whole station, this PR reduces the devastating radius from 3 to 1 and heavy impact from 5 to 3 and light impact from 7 to 5. Not as powerful as before but can still cause quite some damage.

<strike>This also encourages traitors to be more original and not just spam bombs to win</strike>

**Screenshots**

Before

After

**Changelog**

:cl: Hardly
- tweak: Reduced Syndicate minibomb's radius

### CODE REVIEW

**Review by SweptWasTaken — APPROVED** [review]

**Comment by TimrodDX** [comment]
I think this is a bit too much of a nerf - at 1 tile it's basically a slightly faster single-use RCD. I think a better solution would be to up the TC cost or reduce it from 3 to 2.

**Comment by DmitriyRubetskoy** [comment]
Merge as-is imo because the explosion radius nerf is offset by disruption of the power grid and disposal network, along with anything involving glass being destoyed completely by any explosige damage

**Comment by DmitriyRubetskoy** [comment]
> I think this is a bit too much of a nerf - at 1 tile it's basically a slightly faster single-use RCD. I think a better solution would be to up the TC cost or reduce it from 3 to 2.

RCD does not disrupt disposals or power grids, and also it would not instantly expose any windowed/lowwalled tile to epace

**Review by PaulRitter — APPROVED** [review]
while we can't really balance alot due to the lack of content rn, i think this is a reasonable one.

while the devastation can be compared with a rcd, you are forgetting the potential human harm this can still create. good change imo

**Pull request merged**
