### PR TITLE
Change how popups are displayed

### LINKED ISSUE #18851: Popup lengths are too short
Didn't realise they'd changed. I can read quickly but it's way too fast now and should be like twice as long.

### PR DESCRIPTION
**Pull request by Vordenburg**
Draft, so I can get some feedback and later do some cleanup.

[popup-anim2.webm](https://github.com/space-wizards/space-station-14/assets/114301317/25dd8f81-1186-428c-b82a-716e01713a53)

I decided to try visually stacking the popups instead of the random offset suggested by @metalgearsloth hoping for better legibility. The horizontal travel might be too much, or unnecessary entirely, but I like the stacking.

I can look into the suggestion by @EmoGarbage404 of putting the popup over the top of an entity, though that may not work for all situations.

I haven't tinkered with the game options panel before, but I could look into that too, in order to implement the suggestion by @dmnct for a control slider on how long popups stay around.

I think the legibility could be further improved by giving the engine the ability to draw text with solid outlines, but I haven't looked into how that would work yet.

Resolves #18851

### CODE REVIEW

**Comment by Partmedia** [comment]
Personally, I don't like the fade to the side.

**Comment by PixelTheKermit** [comment]
This looks fun to watch visually. I like it.

**Comment by ChilbroBaggins** [comment]
> This looks fun to watch visually. I like it.

Fun was the first word that popped in my head too.

**Comment by JoeHammad1844** [comment]
I dont like the fade to side either

**Comment by Vordenburg** [comment]
I put some work into making this configurable in the options window today, so I haven't forgotten about this.

**Comment by metalgearsloth** [comment]
Re-open when you're back from break.

**Pull request closed without merging**
