### PR TITLE
Removes Portable Flashers

### PR DESCRIPTION
**Pull request by tsp01**
Removes Portable Flashers from prototypes, removes portable flashers from maps, and removes portable flasher sprites.

## About the PR 
resolves Issue: #11781
Deletes all Portable Flashers from maps
Deletes Portable Flashers from prototypes
Deletes Portable Flasher sprites

**Screenshots**

**Changelog**

:cl:
- remove: Portable Flashers

### CODE REVIEW

**Comment by Cheackraze** [comment]
Why

**Comment by EmoGarbage404** [comment]
I mean a maintainer put an issue up asking for them to be removed. In summary, they're buggy and dont really serve a purpose.

**Comment by Cheackraze** [comment]
They work really well for security, they are great tools and I see them used quite often. Also culling I took to mean that their effect be culled when approached from a wall, since they react to movement beyond walls where they shouldn't.

Otherwise culled does not mean removed.

**Comment by tsp01** [comment]
huh, I tried this again but this time an exception was thrown, im gonna close this till I figure out what is going wrong

**Comment by ElectroJr** [comment]
> huh, I tried this again but this time an exception was thrown, im gonna close this till I figure out what is going wrong

If you mean the windows test fail, thats has nothing to do with this PR. Windows tests are just mysteriously failing atm. As long as the linux tests pass its fine

**Comment by Streaky-Haddock** [comment]
They are great tools for sec. Reason they aren't used at the moment too much is because they flash you 16,000 times a second.

**Comment by Peptide90** [comment]
They’re iconic, I think the real solution is fixing them but if that’s not possible right now then sure.

**Comment by metalgearsloth** [comment]
The issue is just about removing them until they're less buggy.

**Pull request closed without merging**
