### PR TITLE
Spilling liquids no longer exposes true identify

### LINKED ISSUE #18448: spilling reagent on someone reveals their identity
repro steps
spill water on someone
it reveals their real identity and not their assumed one
giga lame strat being utilized by players atm

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Also removes a dependency on batterysystem that i forgot to remove in #16125

Closes #18448

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image

**Changelog**

:cl: Vasilis
- fix: Spilling a liquid will no longer expose the true identity of someone

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Is there a reason you removed the "the" ij the popups? It reads better with it IMO

**Review by mirrorcult — CHANGES_REQUESTED** [review]
put the `THE()` calls back

**Review by mirrorcult — CHANGES_REQUESTED** [review]
also they dont need to be `Identity.Name`, they should be `Identity.Entity`

**Comment by VasilisThePikachu** [comment]
> Is there a reason you removed the "the" ij the popups? It reads better with it IMO
> put the `THE()` calls back

This is why

image
```
[ERRO] loc: "en-US"/"zzzz-the": "System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Robust.Shared.GameObjects.EntityUid'.
   at Robust.Shared.Localization.LocalizationManager.FuncProper(LocArgs args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 286
   at Robust.Shared.Localization.LocalizationManager.CallFunction(LocFunction function, FluentBundle bundle, IList`1 positionalArgs, IDictionary`2 namedArgs) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\L
ocalization\LocalizationManager.Functions.cs:line 328
   at Robust.Shared.Localization.LocalizationManager.<>c__DisplayClass53_0.<AddCtxFunction>b__0(IList`1 args, IDictionary`2 options) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Localization\LocalizationM
anager.Functions.cs:line 306
   at Linguini.Bundle.Resolver.WriterHelpers.Write(IInlineExpression self, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 127
   at Linguini.Bundle.Resolver.WriterHelpers.TryWrite(IExpression expression, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 70
   at Linguini.Bundle.Resolver.ResolverHelpers.Resolve(IInlineExpression self, Scope scope) in /_/Linguini.Bundle/Resolver/ResolverHelpers.cs:line 65
   at Linguini.Bundle.Resolver.WriterHelpers.TryWrite(IExpression expression, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 70
   at Linguini.Bundle.Resolver.WriterHelpers.Write(Pattern pattern, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 17
   at Linguini.Bundle.Resolver.ResolverHelpers.Resolve(Pattern self, Scope scope) in /_/Linguini.Bundle/Resolver/ResolverHelpers.cs:line 18
   at Linguini.Bundle.FluentBundle.FormatPattern(Pattern pattern, IDictionary`2 args, IList`1& errors) in /_/Linguini.Bundle/FluentBundle.cs:line 300
   at Linguini.Bundle.FluentBundle.TryGetMsg(String id, String attribute, IDictionary`2 args, IList`1& errors, String& message) in /_/Linguini.Bundle/FluentBundle.cs:line 233
   at Linguini.Bundle.FluentBundle.TryGetAttrMsg(String msgWithAttr, IDictionary`2 args, IList`1& errors, String& message) in /_/Linguini.Bundle/FluentBundle.cs:line 204
   at Robust.Shared.Localization.LocalizationManager.TryGetString(String messageId, String& value, ValueTuple`2[] keyArgs) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Localization\LocalizationManager.cs:
line 99"
```

**Comment by mirrorcult** [comment]
yes thats because you changed it from `Identity.Entity` to `Identity.Name`

**Comment by VasilisThePikachu** [comment]
> yes thats because you changed it from `Identity.Entity` to `Identity.Name`

Changing it back to `Identity.Entity` is the reason this bug is caused, why should I not use `Identity.Name`? it gets the job done

**Comment by EmoGarbage404** [comment]
Pretty sure the bug was the single popup without an identity call at all?

**Comment by mirrorcult** [comment]
emo is correct

**Comment by mirrorcult** [comment]
> > yes thats because you changed it from `Identity.Entity` to `Identity.Name`
> 
> Changing it back to `Identity.Entity` is the reason this bug is caused, why should I not use `Identity.Name`? it gets the job done

`Identity.Entity` passes the identity-entity rather than just the identity-entity's name, which properly retains grammatical info like gender/proper nouns so that functions like `THE()` work properly

**Comment by VasilisThePikachu** [comment]
dont ask me how reverting everything but one line fixes both... but it does

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by VasilisThePikachu** [comment]
ok so turns out I'm stupid and probably forgot to put the mask on urist. Those 2 lines were not broken

**Pull request merged**
