### PR TITLE
Fix SharedPullable exception

### PR DESCRIPTION
**Pull request by metalgearsloth**
I guess if puller is deleted before client gets the state?

### CODE REVIEW

**Review by Zumorica — APPROVED** [review]

**Comment by DrSmugleaf** [comment]
Won't this fail if the entity is deleted? It just checks that the id is 0, not that the entity still exists.

**Comment by metalgearsloth** [comment]
Yeah I've done it less retarded now.

There's a few other componentstates that cause exceptions on live as well, transform being the main one (I assume parenting or something?). There's one for appearance but I think that's getting fixed with my other appearance PR.

**Review by Zumorica — APPROVED** [review]

**Comment by DrSmugleaf** [comment]
> Yeah I've done it less retarded now.
> 
> There's a few other componentstates that cause exceptions on live as well, transform being the main one (I assume parenting or something?). There's one for appearance but I think that's getting fixed with my other appearance PR.

In that case it would be better to check for entities being deleted before their components get states in a more general place.

**Comment by metalgearsloth** [comment]
> 
> 
> > Yeah I've done it less retarded now.
> > There's a few other componentstates that cause exceptions on live as well, transform being the main one (I assume parenting or something?). There's one for appearance but I think that's getting fixed with my other appearance PR.
> 
> In that case it would be better to check for entities being deleted before their components get states in a more general place.

I agree in general but in this instance isn't it for a different entity in this instance?

**Comment by DrSmugleaf** [comment]
> > > Yeah I've done it less retarded now.
> > > There's a few other componentstates that cause exceptions on live as well, transform being the main one (I assume parenting or something?). There's one for appearance but I think that's getting fixed with my other appearance PR.
> > 
> > 
> > In that case it would be better to check for entities being deleted before their components get states in a more general place.
> 
> I agree in general but in this instance isn't it for a different entity in this instance?

You're right, thoguh do entity deletions run before or after sending component states?

**Comment by metalgearsloth** [comment]
They run after which is kinda suss. Even then I still think it's possible for: Server sends state -> Client deletes entity -> Client gets state maybe?

**Comment by PJB3005** [comment]
Entity deletions are not currently reset correct during reconciliation. Why's the client deleting these entities?

**Comment by metalgearsloth** [comment]
> 
> 
> Entity deletions are not currently reset correct during reconciliation. Why's the client deleting these entities?

That was me spitballing, at any rate that's the exception I was getting on USW yesterday ¯\\_(ツ)_/¯

**Review by Zumorica — APPROVED** [review]

**Pull request merged**
