### PR TITLE
Added warden gas mask!

### PR DESCRIPTION
**Pull request by Stanislav4ix**
## About the PR
Added warden gas mask!

## Why / Balance
HoS has his own gas mask (SWAT gas mask), now warden also has gas mask!

## Technical details
Now SWAT and warden gas mask have "Flash Immunity", that means that you can not wear sun glasses and you won't get flashed. Also warden's suit storage unit has warden gas mask in it. I took a sprite from "Paradise Station" but I didn't like that, so I just resprited that.

## Media
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Stanislav4ix
- add: Added warden gas mask!
- tweak: SWAT and warden gas masks now have flash resistance!

### CODE REVIEW

**Comment by UbaserB** [comment]
How does it look with the suit? Formally, it should have a somewhat matching palette ^^

**Comment by Stanislav4ix** [comment]
Oh wait, something went wrong

**Comment by Stanislav4ix** [comment]
I'll remake that

**Comment by lzk228** [comment]
i dont think warden really need this

**Pull request closed without merging**
