### PR TITLE
Soda water and Vodka recipes 

### PR DESCRIPTION
**Pull request by saga3152**
## About the PR
You can now craft soda water from 5 water and 1 carbon dioxide and vodka from 1 ethanol and 1 water, that's not 40% but more simple, also you need to stir mix to make vodka, and shake respective mix to create soda water to prevent conflicts with other reactions

## Why / Balance

I thought that these recipes were missing so I added them
## Requirements

- [X]  I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: You can now make vodka and soda water.

### CODE REVIEW

**Comment by saga3152** [comment]
Didn't mean to close #32244 and didn't understand how to reopen

**Comment by EthanQix** [comment]
You might want to add the crystal recipe tweak in the CL as well.

**Comment by saga3152** [comment]
> You might want to add the crystal recipe tweak in the CL as well.

I reverted that as I found another solution

**Comment by 7-62x54r** [comment]
Ethanol evaporates at a fast rate, so guess while you mix vodka up it's down to 40% anyways. Cool feature

**Comment by slarticodefast** [comment]
Stirring and shaking is a great solution to fix the recipe conflicts 👍

**Comment by slarticodefast** [comment]
Thank you for your contribution!

**Pull request merged**
