### PR TITLE
Potted plant bb fix.

### LINKED ISSUE #5303: potted plants slightly go inside walls
bb needs to be fixed
grafik
grafik

### PR DESCRIPTION
**Pull request by pointer-to-null**
## About the PR 

Fixes #5303

The center of the bb now is around the pot.

**Screenshots**

изображение
изображение

### CODE REVIEW

**Comment by metalgearsloth** [comment]
The plants are marked as bit of so if we go down this route we probably need to change that.

**Comment by SweptWasTaken** [comment]
> 

I think the better fix would be improving the y-sorting of sprites so that the top of walls go over the bottom of the plant-pots.

This is an issue that encompasses a bunch of different entities anyway, most importantly players.

image

**Comment by metalgearsloth** [comment]
DNM until rotation sorted

**Comment by SweptWasTaken** [comment]
> DNM until rotation sorted

!remindme 9999d

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
We bikeshedded a bit in discord and ideally, due to the noRot situation
A) the shape is a circle instead
B) the sprite is offset so that despite noRot the bounds are still roughly where the base is.

**Comment by pointer-to-null** [comment]
Now it looks like this. But it still have y-sorting issue, and I do not know what to do with it.

изображение

изображение

**Comment by SweptWasTaken** [comment]
> Now it looks like this. But it still have the y-sorting issue, and currently I do not know what to do with it.
> 
> изображение
> 
> изображение

What is the y-sorting issue? Looks fine to me.

**Comment by pointer-to-null** [comment]
Created the basic potted plant component/system and setted the draw depth to overdoors.

изображение

**Comment by mirrorcult** [comment]
..can't you just set the drawdepth in the prototype?

**Review by metalgearsloth — COMMENTED** [review]
Is sprite offset bugged? I would imagine you'd use that to just offset the sprite.

**Comment by pointer-to-null** [comment]
> Is sprite offset bugged? I would imagine you'd use that to just offset the sprite.

Made sprite offset `offset: "0.0,0.3"` (bb around the base) and the outline begins to chop the sprite.
Maybe I missing something?

изображение
изображение
изображение

Without outline the sprites looks fine.
изображение

**Comment by SweptWasTaken** [comment]
> > Is sprite offset bugged? I would imagine you'd use that to just offset the sprite.
> 
> Made sprite offset `offset: "0.0,0.3"` (bb around the base) and the outline begins to chop the sprite. Maybe I missing something?
> 
> изображение изображение изображение
> 
> Without outline the sprites looks fine. изображение

I think the plants should have outlines since they're intractable objects for hiding stuff (and in the future people) in.

**Comment by pointer-to-null** [comment]
> I think the plants should have outlines since they're interactable objects for hiding stuff (and in the future people) in.
Yea, my point was that the sprite itself draws fine, but someting goes wrong with outlining.

**Comment by metalgearsloth** [comment]
Interaction outline is a [known issue](https://github.com/space-wizards/space-station-14/issues/5455) so just ignore it and make sure rotation works okay.

**Comment by pointer-to-null** [comment]
Rotation works fine with the sprite offset. The plant rotates around the center of the bb.
изображение
изображение
изображение

**Review by PaulRitter — APPROVED** [review]

**Pull request merged**
