### PR TITLE
Implant Loader: an experimental tool that makes implants

### PR DESCRIPTION
**Pull request by FairlySadPanda**
Adds the **Implant-O-Matic** _(name subject to change)_, a new device right from the _most recently-graduated_ boffins at Nanotrasen Research Facilities!

The **Implant-O-Matic** is a portable, handheld tool that can manufacture simple implants using reagents found on the space station. The research team assures us that injecting potent chemicals directly into eyeballs and brain stems is at least 96% safe.

Please note that due to the unique chemical, biological and sanitary conditions aboard our fleet of stations, the Implant-O-Matic needs to be precisely calibrated before use during your shift. As such, the Chemistry research must be unlocked to manufacture this tool at the Medical Techfab.

## About the PR
This DRAFT PR is a first pass on the Implant-O-Matic, an unlockable tool that can charge empty implanters with simple implants.

The Implant-O-Matic as demonstrated makes two implants:
1. Light Implant using 100u of Welding Fuel
2. Bike Horn Implant using 30u of Banana Honk. (This might get changed to the Bananium-based Honk reagent)

The Implant-O-Matic is currently locked behind the T1 Biochem research `Chemistry`, because it was the first one I saw that looked appropriate. It's made in the Medical Techfab.

To use the Implant-O-Matic, you load it with a reagent and then click on an implanter. You can empty the tool into a bucket or somesuch if you fill it with something useless. 

This PR is currently lacking:
1. Spritework for the tool
2. Balance feedback - what recipes do folks want, what's appropriate for cost, is this a really stupid idea, etc
3. Unique audio, if desired

## Why / Balance
You can make implanters at the Medical Techfab but they're largely useless at the moment. Implanters for the Crew are 99.9% used for mindshields only, which is a bit sad for a cool feature that is often used by antags.

The intent of this PR is to unlock a few useful implants for medical to hang out, and one based on Mindbreaker Toxin that's used to make revs without flashing. 

## Technical details
Shitcode warning, this is my first go with a LOT of these systems.

Adds an ImplantLoader system and component that controls loading implants into implanters.
Adds some functionality to ImplanterSystem to allow for injecting implants.
Adds ImplantRecipe which defines the reagent needed to make each implant.

## Media
https://github.com/space-wizards/space-station-14/assets/732532/189be9a1-ead6-4c54-a707-e18fcafaddb8

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None as far as I'm aware

**Changelog**
No CL yet because no merge.

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
TODOS
1. Spriting
2. Get good feedback (should this even be a handheld tool?)
3. Define a few more implants and re-balance the recipes
4. Audio
5. Clean up the code because it's probably pretty bad

**Comment by FairlySadPanda** [comment]
Currently only support one reagent but that can change 😈

**Comment by Aisu9** [comment]
please no uplink implant crafting, emag already have a studip value for what its worth don't make standard NT equipment able to make syndicate tech

**Comment by FairlySadPanda** [comment]
Yeah in general I will be avoiding complex implants for this as it is a T1 research, no syndie stuff in general.

**Comment by ike709** [comment]
I would like to propose a rename to the Implantinator

**Comment by FairlySadPanda** [comment]
To be honest I'm leaning to something like "Implant Loader (Experimental)" atm. Implant-O-Matic is very Wallace And Gromit.

There's a suggestion that this should be a new tech. Considering how rubbish the medical techs are now, that's not a bad shout.

**Comment by FairlySadPanda** [comment]
Sprite 
image

**Pull request closed without merging**
