### PR TITLE
Station Shadowlands [WIP]

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

A little experiment. A system that generates an alternative, shadowy underside of the station, full of dangers and loot

## Why / Balance

At the moment I have no idea how to use it, but it looks nice and interesting. I'm doing this PR to discuss the possibilities of using this mechanic.
Here are a few of the ideas considered:
1) The shadow anomaly is a portal to the shadow dimension, and given that anomalies can unstably explode or be removed by scientists, this is a temporary portal. We need to add the ability to return to the normal dimension on its own if the portal has closed. Perhaps in the shadow dimension there are portals in ray places that teleport to the same point on the map in the real dimension. 
2) The shadow anomaly core along with some T2 or T3 technology allows you to create stable portals to the shadow dimension. You get an interesting synergy between RnD and Salvage, where the scientists provide unique gameplay for finding resources.
3) Something more global? A separate game mode where shadowlings live on the shadow side, and having the ability to penetrate the real world through the shadow dimension, must take over the station and plunge it into darkness? 

## Technical details

Currently, the shadow dimension is generated by an asynchronous function, scanning the largest station grid, recreating its shape, and populating it with entities based on the tagged objects in the main station. Thus, for example, all walls in the real station are replaced by chasm in the shadow dimension. And all consoles and machines are replaced with valuable loot.

I'm not sure if it's a good idea to generate another big grid with a bunch of entities at the beginning of the map in parallel with the main station, I'd consult sloth here.

## Media

https://github.com/user-attachments/assets/f69ba4d9-46a7-47c8-985e-c3153e1559e4

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

nothing right now

### CODE REVIEW

**Comment by ScarKy0** [comment]
Should totally be a research that allows entry, this could make for a fun thing antags could travel through to get into places as well as a place for salvage to loot (though, it might need a bit more loot)

**Comment by NoElkaTheGod** [comment]
Z-levels are real!

**Comment by KashRas2** [comment]
No way
Bleach TYBW reference

**Comment by 3nderall** [comment]
chasms in an area that dark seems a bit cruel

**Comment by TheShuEd** [comment]
https://github.com/user-attachments/assets/4bd2be99-4b40-402a-a2bd-f378abcbcde2

**Comment by SlimmSlamm** [comment]
Ed coming in with another banger. Hopefully people will call Salvage to come in these and loot them for people. I pray for any salv buff. We are DYING.

**Comment by SlimmSlamm** [comment]
> Should totally be a research that allows entry, this could make for a fun thing antags could travel through to get into places as well as a place for salvage to loot (though, it might need a bit more loot)

I mean SS13 has Telescience this could be reworked into that instead. It's already extremely close to it as it is now anyway.

**Comment by cohanna** [comment]
What happens if a portion of the station is detached while you are in that portion's shadow realm

**Comment by TheShuEd** [comment]
i reopen a new PR for it

**Comment by TheShuEd** [comment]
> What happens if a portion of the station is detached while you are in that portion's shadow realm

nothing. Shadow Dimension makes a copy of the station from the beginning of the round

**Pull request closed without merging**
