### PR TITLE
Remove CRLF, enforce with workflow

### PR DESCRIPTION
**Pull request by PJB3005**
Make emisse weep

### CODE REVIEW

**Comment by deltanedas** [comment]
this can be trolled by non utf8 files having crlf (and not being utf8) the windows trollage continues

**Comment by PJB3005** [comment]
> this can be trolled by non utf8 files having crlf (and not being utf8) the windows trollage continues

I am not sure what you mean. I'm opening the files with binary mode in the python script.

**Comment by PJB3005** [comment]
I'm gonna resolve all the files in the repo and then merge this after dinner.

**Comment by deltanedas** [comment]
> I am not sure what you mean. I'm opening the files with binary mode in the python script.

nevermind i thought the encoding=utf8 was a grep argument not python thing :trollface:

**Pull request merged**
