### PR TITLE
Added janitoral uniform with miniskirt

### PR DESCRIPTION
**Pull request by ssdaniel24**
## About the PR

Adds janitoral maid uniform with miniskirt.

**Media**

*By Van - [confirmation](https://discord.com/channels/310555209753690112/346743671787356160/1073975662412566648).*

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Van
- add: added janitoral maid uniform with miniskirt

### CODE REVIEW

**Comment by Cheackraze** [comment]
dont we already have the janitorial maid outfit? whats the difference besides a slightly different sprite

**Review by EmoGarbage404 — APPROVED** [review]
flawless execution; the most begrudging approval i've ever given.

**Review by AJCM-git — CHANGES_REQUESTED** [review]
You have to make this obtainable in-game

**Comment by AJCM-git** [comment]
@ssdaniel24 you coming back to this?

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
