### PR TITLE
IconSmooth benches and sofas

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

Adds benches and 2 sofas from TG, for mappers.

## Why / Balance

To make the stations more beautiful.

## Media

изображение

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11

- add: Adds new benches and sofas for mappers.

### CODE REVIEW

**Comment by Yuoko** [comment]
hell yeah!

**Comment by UbaserB** [comment]
YOOO BASED! Though.. the bamboo and rainbow one is a little off-putting

**Comment by lzk228** [comment]
so then delete old awful benches

**Comment by UbaserB** [comment]
tbf these new benches look too white they need to be dulled like old bench colour or current chair colour

**Comment by Nimfar11** [comment]
> so then delete old awful benches

This is a bench for the guilty. It seems normal to me to have a bench with or without a backrest.

**Comment by Flareguy** [comment]
Rainbow benches were meant for the map editor / a random bench spawner. Do not add them.

**Comment by Nimfar11** [comment]
изображение

**Comment by Nimfar11** [comment]
> Does the comfy sofa also uses greyscale for random coloring?

In this case, no, but I think it will be possible to give any color you wish.

**Comment by Emisse** [comment]
benches look out of style

**Comment by Tayrtahn** [comment]
The style does seem a little off, but I love the pews.

**Comment by Nimfar11** [comment]
> benches look out of style

It seems these are the only ones they had. I added the colors to the benches myself. Maybe change the color of the bench frame, making it more “steel”?

**Comment by Tayrtahn** [comment]
The outlines might be a little too dark

**Comment by UbaserB** [comment]
can you make sofas craftable

**Comment by Emisse** [comment]
after looking through this i dont feel like this is the right way to implement these, they should use smoothing instead of different entities for each different part of the sofa/bench

**Comment by Nimfar11** [comment]
> after looking through this i dont feel like this is the right way to implement these, they should use smoothing instead of different entities for each different part of the sofa/bench

Do you suggest removing the colorful benches? Or adjust the colors of the frame and the base of the bench?

**Comment by Emisse** [comment]
every type of bench/sofa should jsut be one entity and use iconsmoothing to make edges/corners

**Comment by SonicHDC** [comment]
> every type of bench/sofa should jsut be one entity and use iconsmoothing to make edges/corners

Icon smooth looks bad with rotateble things, a tested it myself

**Comment by Emisse** [comment]
then the system needs to be updated for it to work properly, having a different entity for every single part of a couch/bench is insane and really bad

**Comment by UbaserB** [comment]
honestly, if the only change was adding the soda i would be happy

**Comment by Nimfar11** [comment]
I will most likely add single benches separately. And I will think about what was asked to be changed here. So far, I have not been able to smooth the sofa properly.

**Comment by Peptide90** [comment]
> I will most likely add single benches separately. And I will think about what was asked to be changed here. So far, I have not been able to smooth the sofa properly.

I had this issue over a year ago. Icon smoothing doesn’t work well with structures like this and crafting.

**Pull request closed without merging**
