### PR TITLE
boarding shuttles for ship v ship

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

adds two shuttles, intended to be used as offensive boarding vessels for ship vs ship
also creates a new folder for all the ship v ship maps and grids to be
## Why / Balance

one step forward to pod wars

## Media

ERTCompact:
image
SyndieRam:
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

-->

**Changelog**
no

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
image
when :trollface:

**Comment by JoeHammad1844** [comment]
minor correction: i have added a gravity generator to the NT ship between the red lines here, the red lines also represent where i have placed reinforced directional windows

**Comment by metalgearsloth** [comment]
These don't have any ship guns?

**Comment by JoeHammad1844** [comment]
they're meant to be for boarding, actually. ill change the title, that should have been clearer

**Pull request closed without merging**
