### PR TITLE
space law book

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Added space law book, which works like other guidebook books
Also added it to different places
reopened #22921

## Why / Balance

Useful to have space law in-game

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Space Law book added to the game.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
I think the the Security 101 book has space law inside

**Comment by Brandon-Huu** [comment]
> I think the the Security 101 book has space law inside

where is this book located?

**Comment by Tayrtahn** [comment]
> I think the the Security 101 book has space law inside

It opens the Security page of the guidebook.

**Comment by Moomoobeef** [comment]
no sprite for the book?

**Comment by lzk228** [comment]
> no sprite for the book?

its already exist

**Pull request merged**
