### PR TITLE
adding a voice changer to the ops mask

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR
just adding a voice changer to the operatives mask.

## Why / Balance

it's just an aesthetic addition for ops. with a hidden game, she will not succeed, since she does not have the properties of a chameleon. This mask will appear on the face of the commander, the medic and the fully assembled syndicate operative, the set in the backpack has not changed. I think that quite a lot of people find it unpleasant to see "Operative Mike" in their name without a choice. it will also save operatives from choosing between banal aesthetics and protection.

it WILL NOT be spawned in techs and bought in the syndicate's EVA set, because technically it is a different item
## Media

изображение
изображение
изображение
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: voice mask property without chameleon only for operatives mask

### CODE REVIEW

**Comment by BolloTea** [comment]
other stealth kits:
image

**Comment by Holinka4ever** [comment]
> it's just an aesthetic addition for ops. with a hidden game, she will not succeed, since she does not have the properties of a chameleon.

I dont think though , what make a diffrence for hidden nuke, because instead of, they just break though armory, thats all the tactic for hidden, cause being hidden in stealth can easy break by peoples in station...

And in my honest opinion, it do absoletly nothing, or even more, it can even metagamed, because everyone can inspect other clothes, and see contraband and funny voice mask.

Even that, its addition not okay, because giving stuff like "It maybe will not work, but i am still adding it". It feels like wrong thing.

**Comment by icekot8** [comment]
> > it's just an aesthetic addition for ops. with a hidden game, she will not succeed, since she does not have the properties of a chameleon.
> 
> I dont think though , what make a diffrence for hidden nuke, because instead of, they just break though armory, thats all the tactic for hidden, cause being hidden in stealth can easy break by peoples in station...
> 
> And in my honest opinion, it do absoletly nothing, or even more, it can even metagamed, because everyone can inspect other clothes, and see contraband and funny voice mask.
> 
> Even that, its addition not okay, because giving stuff like "It maybe will not work, but i am still adding it". It feels like wrong thing.

stealth operatives, if they want, will buy a voice mask so it can't be metadetected. After all, this mask only adds the voice property, not the chameleon. Anyway, if you think it's unacceptable, fine.

**Comment by UbaserB** [comment]
This encourages stealth ops, which happen not NEARLY enough so i want this to go through.

**Comment by BolloTea** [comment]
UbaserB, Is the chameleon set a joke to you?

**Comment by UbaserB** [comment]
> UbaserB, Is the chameleon set a joke to you?

no i love the chameleon set lol, but i thought that was syndicate-only

**Comment by BolloTea** [comment]
actually there is, if I'm not mistaken

**Comment by icekot8** [comment]
[BolloTea](https://github.com/BolloTea), I just checked: yes, the chameleon mask is in the set, but it doesn't have the voice changing property.

**Comment by asperger-sind** [comment]
The mask should probably parent from the basic syndicate gas mask and have a different name/description because it's not communicated that the mask has voice changing capabilities.

Balance-wise this is fine-ish, it allows for a bit more stealth for a nukie without a proper chameleon gas mask, but it does not replace a stealth loadout (e.g. chamsuit or clothes from the vendor, voicechanger, maybe DNA scrambler implant).

If I were to think of a specific scenario where it could be used it'd be "don't shoot, I'm crew!" which previously was metagamed(?) because it was clear that Operative Mike is infact not crew. But this is kind of an edge-case, the standard application for this would probably be setting funny names on the voicechanger to go along with the ID, or a name that sounds like a crewmember's for the previously mentioned edge-case to be more common.

Overall, I'm fine with this, it does make nukies slightly stronger and is innate, but imho it's negligible.

**Comment by Holinka4ever** [comment]
> This encourages stealth ops, which happen not NEARLY enough so i want this to go through.


They can buy stealth kit though
They can buy voice masks though
Giving them ability to change voice for their stadard syndicate gas masks, just game them ability to change voice, do nothing, you are still full armed pep with contraband, naming yourself  "John Nanotrasen" cant help.

**Comment by BolloTea** [comment]
Strange... It seemed to me that I saw a request to add a voice... I think it would be more logical to add a voice to that mask than to the main mask of the syndicate (which can also be obtained for purchasing a suspicious box)

**Comment by asperger-sind** [comment]
> ...main mask of the syndicate (which can also be obtained for purchasing a suspicious box)

This is a new prototype entirely, it doesn't add a voicechanger to the ordinary syndicate gas mask (which is found in susbox, hardsuit bundle(?), etc.)

**Comment by icekot8** [comment]
asperger-sind,thanks for your comment, I really stalled, I'll commit now.....

**Comment by BolloTea** [comment]
https://github.com/space-wizards/space-station-14/pull/14203

**Comment by icekot8** [comment]
> Everyone seems to be completely misunderstanding this pr in the comments This is not a stealth tool This is not a deception tool This is a so you can call yourself something funny like you used to be able to with the default nukie agent ID.

I'm glad to know that at least someone realizes that....

**Comment by TheShuEd** [comment]
Enough arguments have been made above, it really doesn't need to be added to the game. If you add it only as an option to change your starting name... That's a crooked workaround. The correct way would be to implement a name change like a clown.

**Pull request closed without merging**
