### PR TITLE
Sharks Go RAWR!

### PR DESCRIPTION
**Pull request by Deatherd**
## About the PR
I have added a new sound for plushie sharks, it plays when they are used or activated.

## Why / Balance
I really love this sound in 13th station and I will be happy to hear it in the 14th. No balance changes.

## Media
rawr

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Sharks Go RAWR!

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
What sound like?

**Comment by Ghagliiarghii** [comment]
> What sound like?

I just downloaded the .ogg re-encoded it as an .mp4 (GitHub doesn't like to embed audio files for some reason):
https://github.com/user-attachments/assets/00e0352d-fb92-48b6-b351-256f08c0d01b

A bit iffy on this personally, could be good to have a custom sound though.

**Comment by regenpower** [comment]
rawr

**Comment by TheShuEd** [comment]
Rawr

**Comment by murolem** [comment]
rawr

**Pull request merged**
