### PR TITLE
Lizard plushie color and marking variation

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR

Greyscales the lizard plushie and allows them to have up to sixteen different colors for the body and four markings included.
**Media**
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The Weh™ plushies now come with four markings and up to sixteen different colors! Collect around 73.000 of them!

### CODE REVIEW

**Comment by AJCM-git** [comment]
@DogZeroX You coming back to this?

**Comment by DogZeroX** [comment]
Requires another PR (tbd) so yes

**Comment by AJCM-git** [comment]
re-open once the other pr is done

**Comment by Aexxie** [comment]
Is the pr done yet :godo:

**Pull request closed without merging**
