### PR TITLE
Make Hristov Great Again

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Buffs damage values for the .60 projectile so that its not awful.

## Why / Balance

The gun is practically unusable at the moment.
Also, damage values for structural needed adjusting.

Buffs the pierce to 50 from 40 to make it a reliable 2 shot kill on unarmored, and kill sec with 3 shots.
Buffs stamina damage to 65 so it slows you on the first hit, and actually stuns people before it kills them.
Armor points of reference:
- unarmored: 2 shot crit.
- sec vest: 3 shot crit.
- Cap carapace: 3 shot crit after ~ 5 seconds of bleeding.
- bullet proof vest: 5 shot crit.

Buffs structural damage to 80 so it breaks reinforced windows in one shot (plasma in 2)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: .60 material rounds have been buffed.

### CODE REVIEW

**Comment by Admiral-Obvious-001** [comment]
I don't think a long range instant stam crit option is a great idea but I am in favor of buffing the Hristov. What about giving it the ignore resistances flag and buffing it up to 50 peirce? Seems kinda weird that the anti material rifle gets stopped by personal armor.

**Comment by IProduceWidgets** [comment]
I am not opposed to doing that instead. I think the stun was originally added because people didn't like one-shot kills, and this allowed for something that practically one-shot kills, but slowly.

Giving it AP though will mean evaluating how it is compared to the Python instead of as a neat stun weapon with some niche window/wall breaking ability.

It would probably also mean changing wither the TC cost (12) or the extra box mag quantity (10 rounds) you get in the bundle.

**Comment by IProduceWidgets** [comment]
Some numbers on the Python:
for 8 TC you get the Python and 6 rounds of AP at 
- 26 Piercing each for a 4 shot kill on anyone.

**Comment by Emisse** [comment]
lower the stam damage to like 2-3 shot stun and its fine

**Comment by deltanedas** [comment]
2-3 shot stun wont matter if they are already crit

**Comment by Emisse** [comment]
armor be hittin tho

**Comment by metalgearsloth** [comment]
> The gun is practically unusable at the moment.

It has always just needed scopes done instead of cycling around the hristov circle.

**Comment by IProduceWidgets** [comment]
true, scopes would be a big improvement. Also needs some sort of overdamage piercing for the windows and stuff too.

**Comment by K-Dynamic** [comment]
Imagine if Hirstov bullets could penetrate bodies and walls

**Comment by EmoGarbage404** [comment]
We already went through the cycle of buffing and nerfing the hristov over and over. The gun just needs actual sniper mechanics because as it stands people just use it like an even stronger revolver.

**Pull request closed without merging**
