### PR TITLE
moves steak cooking to use construction graphs, new temperature construction graph step

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About the PR 

added new temperature step to construction graph
moved several meat based recipes to this system with a simple graph of just heat up to 305K and it becomes the cooked version

removed plates on these because we should have a separate system to allow for any food being plated without it actually changing the food item (i.e. a cooked steak should be the same entity with or without a plate)

this means that the steaks can be cooked by any source, i.e. a fire will cook raw meat into steaks
currently there's no step for making them into a burned mess but this would be a quick change if it's requested, it's just an extra node where if the temperature goes past a certain point, it turns into a burned mess

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: removed plates from steaks (pending a new plating system)
- add: steaks use construction graphs to be cooked now, requiring a temperature of 305K to be cooked

### CODE REVIEW

**Comment by Carbonhell** [comment]
Thank you for this PR! It's an important step for a decent cooking & food system. Just a thing though: right now the cooking wiki is automatically updated/built based on the recipes file you removed the recipes from. I think the build script should be updated somehow to support loading construction graph based food recipes. Unless we want to remove the wiki page in favor of an ingame solution similar to the crafting menu.

Speaking of the crafting menu, will the recipes you made show up there? I think the menu is hard to navigate as it is already, the idea of also having all food recipes in there as well does not sound pleasant.

Last nitpick, the changelog you made seems more for coders rather than players. I don't think players would care about construction graphs, so i think the first changelog entry can be removed (can a maintainer confirm this?)

**Comment by moonheart08** [comment]
> Thank you for this PR! It's an important step for a decent cooking & food system. Just a thing though: right now the cooking wiki is automatically updated/built based on the recipes file you removed the recipes from. I think the build script should be updated somehow to support loading construction graph based food recipes. Unless we want to remove the wiki page in favor of an ingame solution similar to the crafting menu.
> 
> Speaking of the crafting menu, will the recipes you made show up there? I think the menu is hard to navigate as it is already, the idea of also having all food recipes in there as well does not sound pleasant.
> 
> Last nitpick, the changelog you made seems more for coders rather than players. I don't think players would care about construction graphs, so i think the first changelog entry can be removed (can a maintainer confirm this?)

The script is third party, it's not their responsibility to fix.

**Comment by Elijahrane** [comment]
Closes https://github.com/space-wizards/space-station-14/issues/13084

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
does this work with microwaving right now

**Comment by EmoGarbage404** [comment]
> does this work with microwaving right now

Microwaves heat up things inside of it but only to a certain point. This may make it so you can't cook steak in microwaves, but thats probably fine.

**Comment by Visne** [comment]
Would it be possible at all to write down the construction graph once and have it apply to all meats?

Also, shouldn't the temperature be a lot higher? 305 K is 32 C, so less than (human) body temperature.

**Comment by Peptide90** [comment]
> Would it be possible at all to write down the construction graph once and have it apply to all meats?
> 
> Also, shouldn't the temperature be a lot higher? 305 K is 32 C, so less than (human) body temperature.

Probably if you make the graph just “CookedMeat” and have the step take a tag for anything with RawMeat. Steak is an outlier in my mind since it has different levels of done-ness.

**Comment by Visne** [comment]
Mfw all my meat gets cooked on a particularly hot day

**Pull request merged**
