### PR TITLE
Adds the "advanced" color palette

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

Added the "Advanced" color palette.

## Why / Balance

It adds a lot of the decal color presets that I use very frequently, as well as tweaking some of the original departmental colors. Each color has four shades - light, medium, dark, and black - that can be used in synergy with both the type of tile it is placed on, as well as the shade of decal you are coloring. These color schemes are used in the map I am working on. I initially decided to make them into a palette after I got fed up with changing them by hand.

Will soon be releasing a PR that tweaks some of the greyscale decal sprites (like making them opaque, because, as it is now, the transparency is hard-capped at the decals transparency), as well as adding a few new ones (such as wooden trim.)

I will add on to this palette once those PRs are merged to accompany the new greyscale decals.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

nope

### CODE REVIEW

**Comment by CRISOOOOO** [comment]
Do they have alpha like the departamental palette?

**Comment by Aexxie** [comment]
Nope. That's something I changed every time, its a lot easier to just type in a single number than 3 if you really need it.
I don't really like how a lot of the trims look when transparent, and it looks even worse when above a non-steel-tile type tile.

**Comment by EmoGarbage404** [comment]
they should probably have transparency to match the regular department pattern or else it'll clash when used alongside each other.

**Comment by Aexxie** [comment]
> they should probably have transparency to match the regular department pattern or else it'll clash when used alongside each other.

It's not intended to be used alongside the original, it's more of an alternative to it. Even with transparency, it probably wouldn't look good with the older counterpart due to some hue tweaks.

I used some of the clothing/equipment of each department to tweak the colors. For example, here, engineering is tinted more orange. The cargo and salvage schemes are also based off of their color and equipment.

**Pull request merged**
