### PR TITLE
Security boots new sound

### PR DESCRIPTION
**Pull request by Klaypexx**
## About the PR
Add boot step sound from ss13 to jackboots and combat boots (the sound called suitstep1.ogg and suitstep2.ogg was taken from the root folder of the game)
Volume changed to -10dB on file suitstep1.ogg, suitsetop2.ogg

**Media**

https://user-images.githubusercontent.com/68664576/229507576-deae61b0-42b6-44ad-9cb0-38784b070382.mov

**Changes**

:cl: Klaypexx 
- add: added sound to jackboots and combat boots

### CODE REVIEW

**Comment by SpliTistiC** [comment]
Ima be honest, even though its from SS13, that sound is so damn jarring.

**Comment by Emisse** [comment]
can you dampen the sound a bit

**Comment by Klaypexx** [comment]
> can you dampen the sound a bit

I don't know exactly if it can be done, but I will try to solve it as soon as possible

**Comment by Klaypexx** [comment]
> can you dampen the sound a bit

Reduced the volume by 10 Db. I took the clown's shoes for comparison.

https://user-images.githubusercontent.com/68664576/228495956-543c3922-de51-4fd9-a155-5222c219e237.mov

**Review by Klaypexx — COMMENTED** [review]
Added sound to jackboots and combat boots

**Pull request merged**
