### PR TITLE
Revolver / Python changes. 

### LINKED ISSUE #18274: Revolver issues
1. Give them slightly higher than pistol damage but reduced ammo count, 6 sized chambers probably instead of 7.
2. Give them stamina damage.
3. Remove .357 ammo.
4. Give ERT / Syndicate higher capacities.

### PR DESCRIPTION
**Pull request by LankLTE**
## About the PR

Closes #18274. Reverts #18197, though some of its' minor changes were made here (making the python louder & faster, cap gun sharing stats / sound, small uplink description tweaks).
.357 is removed. Revolvers now properly hold 6. New .45 Armor Piercing that does 28 damage and ignores armor. Uplink has .45 AP Speedloaders, the Python starts with it loaded. .45 High-Velocity was buffed to 44 damage. Zombie bundle now has a python. Python is 8TC and ammo is 2TC each. 

This way we aren't making an ammo type for one gun, and instead have an ammo type that can be usable by other guns (though it isn't currently) while also making the python actually a threat. HV also gets a buff because it was pitiful before (4 extra damage? That amounts to less than one extra shot after you've used all 6). The price buff should've happened anyways so this is just making it happen now. 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

**Changelog**

:cl: Lank
- add: Added .45 AP, which does less damage but ignores armor entirely. 
- remove: Removed .357 ammo and returned the Python and Mateba to .45 Magnum. 
- tweak: The Syndicate now supplies .45 AP rounds for the Python, and sells both the weapon and the ammo at a lower price. 
- tweak: .45 High-Velocity rounds are now significantly more lethal.

### CODE REVIEW

**Comment by Emisse** [comment]
ill leave this one for sloth he has strong opinions on guns

**Comment by metalgearsloth** [comment]
I'd probably make the AP damage reduction 20% not 10% rest seemed okay.

**Comment by LankLTE** [comment]
> I'd probably make the AP damage reduction 20% not 10% rest seemed okay.

it was to make it able to (reasonably) 3 shot people still since I think 4 would be too weak

**Comment by metalgearsloth** [comment]
> It was to make it able to (reasonably) 3 shot people still since I think 4 would be too weak.

The reason to even reduce it by 20% is making AP vs non-AP a conscious trade-off instead of still having the same damage breakpoints.

**Comment by LankLTE** [comment]
> The reason to even reduce it by 20% is making AP vs non-AP a conscious trade-off instead of still having the same damage breakpoints.

I mean, for syndies it isn't a conscious trade-off. I still think it'll be strong at 20% though, so I'll change it.

**Comment by LankLTE** [comment]
It may be a bit overpriced now, but we can always wait and see

**Pull request merged**
