### PR TITLE
Locker fills for EOD, Detective and some theater vendor stuff

### PR DESCRIPTION
**Pull request by Peptide90**
## About the PR 
Adds locker fills for EOD (bomb suit) and detective locker since the content is already there.
Also added some more costumes to the theater vendor since they were there.

Will look to add an autodrobe for each role in a future PR so we can do away with job outfit lockers...

### CODE REVIEW

**Comment by Peptide90** [comment]
100 errors in integration test...non of them mine?

**Comment by SweptWasTaken** [comment]
Pull master and try again? There's 1 thing failing.

**Review by SweptWasTaken — APPROVED** [review]
Looks good, fix conflicts tho.

**Comment by PaulRitter** [comment]
please merge latest master so that the yamllinter runs

**Review by PaulRitter — CHANGES_REQUESTED** [review]
-

**Comment by Peptide90** [comment]
Up to date and all green.

**Review by YakovLya — APPROVED** [review]

**Pull request merged**
