### PR TITLE
You can now pry multiple tiles at once

### PR DESCRIPTION
**Pull request by PJB3005**
:cl:
- tweak: You can now pry multiple tiles at once.

### CODE REVIEW

**Comment by MACMAN2003** [comment]
you're a hero

**Comment by Tayrtahn** [comment]
Heh, that test may need some, uh, adjustment.

**Comment by ninruB** [comment]
holy shit this is what god intended all along before Isch'zklaach-kuk the malevolent came down from the deepest circle of hell and tore the garden of eden apart to cast us away into sansara to rot forever before altering the composition of glue in the hyperschizoid meta-cube causing the revelation of sacred vases containing several duodecillion glass shards of infinite size onto which He stepped on before vanishing to hyperborea leaving a quasi-interludiating ǫ̶͍̦̲̲̖̙͚͇̯̗͝ŕ̴̲̞̫̿b̷͎̜͉̣̺̠̤̲͎͖̣̤͇̦̠̀̑̄̐͊͛̓͆͋͗̎̔̔̆̕͜͠͝for the sinners to forever be rolling pinned under. he then contracted ischias and fucking died, hail be to the pessimistic extremely agile perfectly spherical gharial and his legions of oversized mice contained entirety within the 71th story of Taj Mahal's upper invisible winding staricase looping into a singularity of unfinished households and actively decomposing head surgeons existing entirely within my head contained within the wall of the bowl placed on top of a 71-sided polyhedron forming a false triangle placed vertically onto an odd series of euler's numbers printed in impact font on a piece of tunisian manuscripture from the 16th century currently residing in the mansion of the current premier minister of the city state of oklahoma (flag-ok flag-ok flag-ok) placed on top of a downwards line of grapes with altering colors that do not touch the G value permanently stuck at 71 the three sacred numbers reside within the _ _ and shall not be erected upon by the masonic lodgemen longing for construction of geometrically capable archways in tertiary areas of the royal palace of the 213th french republique below a rosestone of the guide leading to a semicolon missing within the line of 45370 at 19. you failure for the microchip goblins cannot consume underappreciated amounts of semicolon placery within the 45370 at 19 as this is clearly the intended method devised by angry norsemen. stan.

**Comment by WarMechanic** [comment]
this is going to be a massive time saver for engineers that want to adjust the power grid

**Comment by mirrorcult** [comment]
just shouldnt be a doafter at all imo, i think it was made one to avoid people just autoclicker prying entire hallways but it can just be a short (0.5 to 1 sec?) usedelay i feel like

**Comment by PJB3005** [comment]
I would rather have a do after with multiple actions allowed than a cooldown.

**Comment by WarMechanic** [comment]
doafter with multiple actions aligns with any other construction activity in the game, so i would rather the doafter

**Pull request merged**
