### PR TITLE
Space Koi

### PR DESCRIPTION
**Pull request by AlokenMaloken**
## About the PR
Added a friendly version of the carps - space koi. You can buy crate with them in cargo or meet near spawner.

## Why / Balance
A little friendly fauna in an unfriendly outer space. They drop only regular meat, so you'll still have to hunt carps for toxin and teeth.

## Media

Screenshot_68
Screenshot_69

https://github.com/user-attachments/assets/3c66cb15-4f56-4298-b73e-cc3ad5f94ab5

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added friendly animal Space Koi in 5 colors.

### CODE REVIEW

**Comment by thebadman4662** [comment]
Dammit, got baited. Thought we are getting space Koibeans

**Comment by Spessmann** [comment]
Are they space in the same way other space animals are? As in, don't require air & dont take spacing damage etc?

**Comment by AlokenMaloken** [comment]
> Are they space in the same way other space animals are? As in, don't require air & dont take spacing damage etc?
> 
> Also, is there a spawner for them?

Yup

**Comment by Everturning** [comment]
can you make them give fish meat (NOT carp filet) maybe for sushi addition later

**Comment by AlokenMaloken** [comment]
> can you make them give fish meat (NOT carp filet) maybe for sushi addition later

I can, but there's no fish meat in game yet, so I'll have to make it myself and shouldn't sushi have poisoning chance?

**Comment by slarticodefast** [comment]
Yeah, if you can simply order friendly carp gaining carpotoxin for cognizine would be way too easy.
Otherwise I really like how they look.

**Comment by nymhole** [comment]
do the crates always come with the same 5 fish?

**Comment by nymhole** [comment]
>  shouldn't sushi have poisoning chance?

it should rot

**Comment by AlokenMaloken** [comment]
> do the crates always come with the same 5 fish?

Yeah, 5 koi in all colors

**Comment by YehatRebel** [comment]
I like the friendly space fish. I hope to see them in the game alongside more aquatic creatures.

**Comment by AlokenMaloken** [comment]
@UbaserB So, any news on maintainers discussion? It's been 1,5 months now

**Comment by UbaserB** [comment]
Sorry for the late response, this PR kind of got lost when we switched over our PR review system.
Thank you for the contribution, but the general consensus is to close this PR for two reasons;
1. It's bloat currently, with no reason for an entity like this to exist (see "new pets freeze" in #8524)
2. We'd rather wait for the carp migration event from ss13 to add koi into the game

**Pull request closed without merging**
