### PR TITLE
Adding a holy watermelon helmet

### PR DESCRIPTION
**Pull request by ravage123321**
alalalla

## About the PR
I added a version of the watermelon helmet for the holy watermelon

## Why / Balance
Adds a little more functionality to the new mutation and looks cool

## Media
Content client 2024 09 18 - 20 03 49 04 (1)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: You can make a holy helmet from holymelons!

### CODE REVIEW

**Comment by lzk228** [comment]
> Or do worn sprites not support animations?

they do

**Comment by ravage123321** [comment]
> Cool idea. Can you maybe make the halo hover up and down a little like it does on the holymelon? Or do worn sprites not support animations?

done cutie

**Comment by UmnayaSvinka** [comment]
looks great

**Comment by UmnayaEbanushka** [comment]
absolutely fascinating

**Comment by slarticodefast** [comment]
Art directors approve. And very cool idea 👍 
Thank you for your contribution!

**Pull request merged**
