### PR TITLE
Fix defibs resetting rot timer + slimes not having perishable

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Defibs reset rot timer because they force a state change even when it gets reverted immediately. Very sad!
Slimes weren't perishable which i know people pretended like was some cool species trait but was honestly just a really weird niche that invalidates a core part of medical. I'm also 99 percent sure it was a bug.

## Why / Balance

Being able to reset rotting without actually reviving people means that you can stop rotting permanently with no tools. Just zap a person once every 10 minutes and boom no more rot at no cost.

Rotting is pretty important to medical gameplay and revival at a whole and shouldn't be trivially subverted. Slimes being able to subvert rotting by merely existing is really strange and honestly shouldn't be a thing. They're the only player species with this feature and the only thing it enables is for Med to perform a hail mary revival half an hour after they die, which really shouldn't be happening.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Defibrillators no longer reset the rot timer when failing to revive a body.
- tweak: Slimes now rot.

### CODE REVIEW

**Comment by GreyMario** [comment]
isn't slimes not rotting a temporary stand-in for the stockholm syndrome 13 feature of spimes regrowing from their brain

**Comment by Emisse** [comment]
no its a bug that never got fixed

**Comment by EmoGarbage404** [comment]
> isn't slimes not rotting a temporary stand-in for the stockholm syndrome 13 feature of slimes regrowing from their brain

if it is then it still sucks and shouldn't be in the game.

**Comment by deltanedas** [comment]
inb4 someone says they cant revive anyone now because skill issue, morgue exists to prevent rotting as do body bags

**Comment by LankLTE** [comment]
Slimes not rotting is intentional. It was introduced in #12016 and was also intentionally kept when other species (namely diona and moth) were given the component after formerly missing it. I think it’s a good upside for a species that doesn’t have many and also thematically makes sense.

**Comment by EmoGarbage404** [comment]
> I think it’s a good upside for a species that doesn’t have many and also thematically makes sense.

It would be more understandable if they had some other tradeoff for their death mechanics. As it stands, simply having no permadeath is really strange. If someone wants to add that, be my guest, but in the meantime, they shouldn't just have nothing.

**Comment by LankLTE** [comment]
> It would be more understandable if they had some other tradeoff for their death mechanics. As it stands, simply having no permadeath is really strange. 

I mean, they have a tradeoff in that they take more barotrauma damage, take damage from water, and take more cold, slash, and pierce damage. Their only other real upside is breathing less & being immune to nitrous oxide (both of which can be negated incredibly easily) and taking less blunt, so I don't think not rotting is really out of place. They can also still be permakilled through gibbing, though admittedly the very low blunt modifier makes that difficult, wouldn't mind seeing that raised, but the point is that it isn't impossible.

Also the perishable component probably shouldn't be on base species anyways since I could see a new species being implemented that doesn't rot (like plasmamen or something idk)

**Comment by Admiral-Obvious-001** [comment]
I'm not a fan of this change because there's cases where your medic or someone else might find someone stuck in a locker doing maintenance dives that were dead for, say 8 minutes. The defib was able to give medical a chance to save the person (if they stuck around). The proposed change will increase the amount of rotting individuals in cases outside of medical control.

Can this be changed to delay rot by say, 30 seconds instead but keep the timer? It would allow medical to still have a chance to save people close to rot instead of having people rot on the bed while topicals are being applied.

**Comment by Emisse** [comment]
we have bodybags and morgues for this exact use case

**Comment by Admiral-Obvious-001** [comment]
> we have bodybags and morgues for this exact use case

This probably should be explained somewhere then, because I don't believe many medical players use either for that at all.

**Comment by Emisse** [comment]
they dont use it because the defib bug is super overpowered lmao

**Comment by lzk228** [comment]
then make slimes longer time to start rotting

**Comment by Emisse** [comment]
lmao???

**Comment by deltanedas** [comment]
> This probably should be explained somewhere then, because I don't believe many medical players use either for that at all.

this is because people just defib corpses without scanning so they dont rot, if the bugs fixed they have to use the actual rot prevention methods

**Comment by K-Dynamic** [comment]
Two-pronged attack to ensure the rot will consume us all ahhhh

Slimes not rotting is a feature so describing it as a bugfix is odd. Reworking is preferable since rot sucks (see below):

Being able to reset rot timer was a miracle since:
1. Rot timer is way too short at 10 minutes; dragging bodies out of maints may take like 3 minutes on its own, 3 minutes waiting time due to secoff patients meeting spiders, 1 minute to find defib, 5 minutes for intern to find topical meds before they realise you rotted

2. Deadchat gets filled with salt rather than intellectual discussions about mothroaches or clown ODing on meth
2.1. _I_ get salty when interrupted from my bartending button-mashing adventure and rot in medbay, forcing me to either leave server (dishonourable) or wait 30 minutes to round to end (better but bad)

3. Current ghostrole selection is very limited, weak incentive to ghost gang

4. Cloning or the rot-resetting drug aren't in, and borging is its own mess (assuming sci isn't irradiated to hell or cargo isn't poor/throngled)

5. Rot at low temperatures is very finnicky, seems to occur anyways in spaced areas - at least you seem to stop taking barotrauma damage on death

6. Bodybags take up space (4 body bags to one defib), are surprisingly hard to find outside of morgue and medical, and asking for them as non-medical is powergaming - then people forget they exist when they're needed
6.1. Non-perishable containers such as freezer crates and upright fridges are neither marked or replaceable, upright fridges seem to only work when anchored(?)

7. Medical is boring enough as it is without also fighting off inevitable entropy with electric shocks
7.1. It is extremely demoralising to spend 3 stacks of topical meds only for rot to set in because you were 2 seconds too late to defib

8. Your body will be abused and treated like resources after death; forgotten in morgue, or have the chef, cargo tech and scientists brawl for your extremely bloated corpse

**Comment by deltanedas** [comment]
> dragging bodies out of maints may take like 3 minutes on its own

putting them in a body bag takes 5 seconds, and a bodybag is smaller than a defib

>  I get salty when interrupted from my bartending button-mashing adventure and rot in medbay,

this is known as shitmed, if doctors refuse to heal rotting doesnt matter so its not the root cause

> asking for them as non-medical is powergaming

same applies for defibs

> Stasis beds are a fucking noobtrap since they don't stop rot

yes they dont stop rot and never have

your entire argument for why a heavily abused bug shouldnt be fixed is that rotting to death sucks, yeah removing gibbing too since i dont like being round removed

**Comment by K-Dynamic** [comment]
It's so joever

**Comment by K-Dynamic** [comment]
> > dragging bodies out of maints may take like 3 minutes on its own
> 
> putting them in a body bag takes 5 seconds, and a bodybag is smaller than a defib
> 
> > I get salty when interrupted from my bartending button-mashing adventure and rot in medbay,
> 
> this is known as shitmed, if doctors refuse to heal rotting doesnt matter so its not the root cause
> 
> > asking for them as non-medical is powergaming
> 
> same applies for defibs
> 
> > Stasis beds are a fucking noobtrap since they don't stop rot
> 
> yes they dont stop rot and never have
> 
> your entire argument for why a heavily abused bug shouldnt be fixed is that rotting to death sucks, yeah removing gibbing too since i dont like being round removed

Yes my point is that rot sucks and should be reworked - and yet I'm oddly fine with gibbing/other means of round removal. Probably because rot implies negligence.

You still got the problem of actually finding a corpse within to bodybag in 10 minutes (morgue only has 5 bags and risk your patient being dragged off to morgue), low temps not working to pause rot, and non-perishable storage components having to be deduced off github

**Comment by GreyMario** [comment]
print more bags

**Comment by Emisse** [comment]
take bodies that are in bodybags and put them in morgues

**Comment by K-Dynamic** [comment]
Rather than arguing the current state of rot here, I will probably open an issue about it

**Comment by LordEclipse** [comment]
What there really needs to be is a way to reset rot timers. If you find somebody in maints dead, you don't know how long until they rot, and putting them in body bags and morgue only HALTS rot it doesn't reverse it, meaning that when you go around to treat the body, it can very easily rot while you are treating it, which would really fucking suck, being forced to abandon treatment of a body simply because there is no way to reverse rot timer fucking sucks in gameplay. Especially of you HAVE THE BODY in medical.

**Comment by deltanedas** [comment]
there is, its called heal until 194 damage and defib

**Comment by K-Dynamic** [comment]
What I'm really gonna miss was treating patients with 200+ rads as they could metabolise arith briefly before dying again

Again, I'll bring this up in an issue rather than a bugfix pr

**Comment by Aisu9** [comment]
> there is, its called heal until 194 damage and defib

tell this to the two unlucky folks that got zapped ONCE by an electrified door and fence and got 2k and 800 shock damage respectively during the first part of the 24h event on Miros

**Pull request merged**
