### PR TITLE
Changes Voice mask description and lowers TC cost by 1

### LINKED ISSUE #13508: Voice Mask is not working again.
## Description

Voice Mask is not working again.

**Reproduction**

Wear a voice mask and try to change your name.

### PR DESCRIPTION
**Pull request by Mirino97**
## About the PR

After some light discussion in Discord and this issue (fix #13508), I think Voice Masks are in a weird place rn.

I've decided to change their description a little, plus decrease their TC cost by 1, both to help people not get confused with how they work, and trying to entice people to use it more. I'll be playing with them in following antag rounds, to see if they work out of each other well or if we should try the ss13 implementation.

**Media**

- [X] This PR does not require an ingame showcase

**Changelog**

:cl: Mirino
- tweak: Voice mask's description has been updated to inform about the need of an ID over radio. Teir TC cost has been reduced by 1.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
is there a reason it uses the ID for the radio? i feel like it should be the other way around.

**Comment by Mirino97** [comment]
There's no real consensus on this.
Some people say the voice changer mask should change your name over the radio because... you know... VOICE CHANGER.
Others say it shouldn't because if radios have any type of ID over messages, it's gotta read out of your ID, reading over your voice makes no sense.

There was a big discussion about it in the initial PR #10458 , and Flipp summarised them in one of his comments.

I kinda like it requiring the ID, it forces the player to go after IDs in some other way OR AT LEAST purchase the Agent ID card, which also kinda locks them in a more stealthier kit.

But, in the end, this is just personal opinion.

**Comment by othymer** [comment]
This doesn't actually fix that the mask is bugged though? 

Even assuming that the id card for radio thing wins out, using the radio without an id is bugged and says '{age gender} says' instead and really messes with how this logic about id cards and radios are supposed to work.  

And with a fake id or an id with a name that isn't yours you appear as the id on radio but the masked voice in whisper. This just seems like a bugged mechanic.

image
image

**Comment by mirrorcult** [comment]
yeah this is just bugged i think

**Comment by Mirino97** [comment]
I don't think it's bugged at all. I think it's pretty much intended.

You have to micro-manage the two IDs you've set. The one in the mask, and the one your ID represents.

The mask is always local, the radio takes off of your ID.

By what I've understood from the original PR, this is intended.
We can change the functionality of the mask to use IDs as well, which makes more game sense and is not as confusing as this.
I think I'll still decrease the Tc cost tho :D

**Comment by EmoGarbage404** [comment]
i feel like the ID shouldn't impact the radio at all? it should solely be the voice for the radio.

**Comment by Mirino97** [comment]
I think this is as good a place as any to ask and feel the room:

If I were to change functionality, how would you prefer?

1: Mask works alone by setting a name and changing both your local voice and your radio voice. If you change your ID but forget to change your voice in your maks, you're fucked.

2: Mask depends on ID to change radio name but changes your local voice (current)

3: Mask goes off of ID, having no "set name" option and changing your name to your current identity name (your ID name or [age gender] if no ID, like TG in ss13 does)

**Comment by othymer** [comment]
My preference would be 1. Which would make it a lot more viable and intuitive. It would probably need to cost more though. 

If not I would say option 3 but not the age gender part. I just think that age gender doesn't make any sense whatsoever over the radio. Just have it default to unknown or something.

Option 2 just seems the worst of all worlds.

**Comment by deltanedas** [comment]
implemented option 1

**Pull request closed without merging**
