### PR TITLE
refactors adminmenu a timid amount

### LINKED ISSUE #5092: admin overlay doesnt automatically update playerlist
ideally it should update the playerlist when someone leaves/joins

### PR DESCRIPTION
**Pull request by PaulRitter**
fixes #5092

### CODE REVIEW

**Comment by moonheart08** [comment]
does this mean no more refresh button

**Comment by metalgearsloth** [comment]
Can I still have it as a placebo

**Comment by PaulRitter** [comment]
> does this mean no more refresh button

yes



> Can I still have it as a placebo

now that i think of it, i think i never removed it

**Comment by metalgearsloth** [comment]
> now that i think of it, i think i never removed it

image

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Opening menu up crashes my game; I just merged in master so probably related?

**Comment by SweptWasTaken** [comment]
https://github.com/space-wizards/space-station-14/issues/4686 is really annoying would be nice if it was fixed in this PR.

**Pull request merged**
