### PR TITLE
Throw the book at em! The space law book now does 1 blunt projectile damage

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
added one projectile damage to the space law book, so you can literally throw the book at someone in addition to just hitting people with it.

## Why / Balance
Funny, and it already does one blunt, just not as a projectile, so I felt like it was a missed opportunity

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- tweak: Books now do one blunt damage when thrown as a projectile..

### CODE REVIEW

**Comment by Moomoobeef** [comment]
I did not mean to submit this as a draft lmao

**Comment by coolsurf6** [comment]
This is amazing. Can projectiles that don't embed hit multiple people? Lining up 5 security officers to prepare them for the shift with this book would be amazing.

**Comment by Plykiya** [comment]
just make all books do this?

**Comment by Moomoobeef** [comment]
> This is amazing. Can projectiles that don't embed hit multiple people? Lining up 5 security officers to prepare them for the shift with this book would be amazing.

yea, you can infact line up targets and hit them, I saw this while testing.


> just make all books do this?

Well not all books have blunt damage, just the law book. I don't think it would make sense to make all books have projectile damage when this was already the only one to do damage in the first place

**Comment by slarticodefast** [comment]
> just make all books do this?

Brought this up for maintainer discussion and this is preferred for consistency reasons.

**Comment by Froffy025** [comment]
law book does... 2 damage (heavy) :godo:

**Comment by Moomoobeef** [comment]
it does 1 damage, it's just that now it also does damage when thrown and not just when punched with.

**Pull request merged**
