### PR TITLE
C1984 (C4 nerf)

### PR DESCRIPTION
**Pull request by Macoron**
## About the PR 
C4 was way too "fun" (can be digest if stuck on pill or gib basically any mob), so it was nerfed a bit.
 
**Screenshots**

https://user-images.githubusercontent.com/6161335/163714032-1796984f-91d8-4b55-b46c-c06734d6e7c7.mp4

https://user-images.githubusercontent.com/6161335/163714047-ec10e135-7ffe-43bb-8b8b-21f016a5fc17.mp4

**Changelog**

:cl:
- tweak: C4 can't be stuck to any other items (including pills). Mobs and structures are still valid targets for sticking.
- tweak: C4 damage was significantly reduced for all organic mobs. It should be enough to crit a player, not gib them.

### CODE REVIEW

**Comment by mirrorcult** [comment]
changes look good though not sure how i feel about 'structural' damage? maybe its fine but need another opinion

**Review by mirrorcult — APPROVED** [review]

**Comment by Fishfish458** [comment]
> changes look good though not sure how i feel about 'structural' damage? maybe its fine but need another opinion

 Personally haven't seen c4 really used in significant instances enough to nerf it yet. In cases like armory where there is two reinforced walls it should mean it takes at least 30 seconds with an explosion between them to get in.

**Comment by UKNOWH** [comment]
>[C4 now explode when damaged](https://github.com/space-wizards/space-station-14/pull/7612/commits/95dd409f89e201a3e93a720ec03ed941390d0030)
not sure If this is the best change  , since that means the crew cannot simply defuse it by punching it anymore. A new method of defusing should be added (like a pop up panel with several wires) to disarm the bomb.

**Comment by Macoron** [comment]
> > [C4 now explode when damaged](https://github.com/space-wizards/space-station-14/pull/7612/commits/95dd409f89e201a3e93a720ec03ed941390d0030)
> > not sure If this is the best change  , since that means the crew cannot simply defuse it by punching it anymore. A new method of defusing should be added (like a pop up panel with several wires) to disarm the bomb.

Well, defusing C4 by punching it was not intended way to get rid of the bomb. I don't think C4 need way defusing right now, because the safest option is just throw it away and wait for explosion.

Hacking wires for C4 are possible. It could be two randomized wires. One for defusing the bomb, one for activating it. However this out of scope of this PR, can be created as separate issue.

**Comment by UKNOWH** [comment]
Also is it possible for you to apply a damage modifier to the mob that it was attached to ? Since C4 gibbing the body it was attached to kinda makes sense and also is quite helpful

**Comment by moonheart08** [comment]
> Also is it possible for you to apply a damage modifier to the mob that it was attached to ? Since C4 gibbing the body it was attached to kinda makes sense and also is quite helpful

It is not desired behavior in the first place.

**Review by mirrorcult — APPROVED** [review]
i guess we can see how structural damage works out, why not

**Pull request merged**
