### PR TITLE
Aghosts and other powerful beings no longer burn their hands on lights.

### LINKED ISSUE #23856: aghost cant grab lights it burns their hands
idk im they cant grab light it burns ouch

### PR DESCRIPTION
**Pull request by nikthechampiongr**
resolves #23856

## About the PR

Aghosts don't take damage when trying to change light bolbs.

## Why / Balance

I have not heard a "how many admins does it take to change a light bulb" joke yet and I don't want to either.

## Technical details

If the DamageSpecifier is returned as null then you will just continue removing the light bulb. I  cannot think of any scenario where a thing can't take burn damage and has hands shouldn't be able to take out a light bulb.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Aghosts and other powerful beings can now change light bulbs.

### CODE REVIEW

**Comment by notquitehadouken** [comment]
how many admins does it take to change a lightbulb

**Comment by OliverOtter** [comment]
Hopefully one after this change.

**Comment by Kadeo64** [comment]
how many trialmins does it take to crash a server?

**Comment by nikthechampiongr** [comment]
> how many trialmins does it take to crash a server?

None. The server crashes before the trialmin even joins.

**Pull request merged**
