### PR TITLE
Add CVar for customizing round restart time

### PR DESCRIPTION
**Pull request by arimah**
## About the PR

You can now customize the round restart timeout. In other words, you can spend more or less time in the post-game. The default remains at 2 minutes.

**Media**

With `game.round_restart_time = 240`:  
image

With `game.round_restart_time = 10`:  
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

N/A

### CODE REVIEW

**Comment by arimah** [comment]
I discovered this change is slightly incorrect. `EndRound()` is called not just when the shuttle has docked, but also when the game ends for all kinds of reasons. If we want `shuttle.round_restart_time` to apply *only* to post-dock endings, to extend time spent at centcomm, additional code is needed.

**Comment by ficcialfaint** [comment]
also the changelog isn't needed here

**Comment by arimah** [comment]
@ficcialfaint I moved the CVar to `game.round_restart_time` as there was no `round` group and it seemed to fit there. Other than that and a doc comment update, the code is funtionally identical.

**Review by ficcialfaint — APPROVED** [review]
looks good to me, will merge once the tests are passed

**Pull request merged**
