### PR TITLE
Add Instrument Volume Boost option (velocity 127), add Admin MIDI marker, add global MIDI volume setting slider

### PR DESCRIPTION
**Pull request by 20kdc**
## About the PR

The Volume Boost option is available on all instruments.
It doesn't add any capabilities that instruments did not already have.
It's a workaround for MIDI files that have the volume too low.

The Admin MIDI marker is only actually usable by those who have the general admin flag.
It remains placable in Sandbox by regular users but is as useful as placing a piano.
It's basically a super synthesizer with security.

Requires https://github.com/space-wizards/RobustToolbox/pull/2141

**Screenshots**
image

**Changelog**
:cl: 
+ add: Checkbox on instruments to increase effective volume if the MIDI being played is too quiet.

### CODE REVIEW

**Comment by Zumorica** [comment]
While I don't have an alternative, we should still get a better, less confusing name

**Comment by 20kdc** [comment]
I called it volume boost because I figure that's what someone trying to listen to a quiet MIDI would be reaching for.
It forces velocity to 127 because that way it's not any more abusable than the velocity range already was.

**Comment by vulppine** [comment]
> "Volume Boost" is extremely misleading for people not familiar with more technical midi concepts.

is it the equivalent of pressing a piano key really hard

**Comment by Zumorica** [comment]
> > "Volume Boost" is extremely misleading for people not familiar with more technical midi concepts.
> 
> is it the equivalent of pressing a piano key really hard

exactly!

**Comment by 20kdc** [comment]
And in practice it loops back around to effectively being an increase in volume, with pressing it less hard being a decrease in volume.

**Comment by vulppine** [comment]
> > > "Volume Boost" is extremely misleading for people not familiar with more technical midi concepts.
> > 
> > 
> > is it the equivalent of pressing a piano key really hard
> 
> exactly!

> And in practice it loops back around to effectively being an increase in volume, with pressing it less hard being a decrease in volume.

- [x] vote: change 'Volume Boost' to 'PIANO SMASH'

**Comment by 20kdc** [comment]
Is that an acceptable answer?

**Comment by 20kdc** [comment]
Rebase and test IN PROGRESS in preparation for separation of instrument BUI code (as a separate PR or otherwise)

**Comment by 20kdc** [comment]
Rebase and test completed on my end

**Comment by 20kdc** [comment]
Closing this PR as it's in conflict with pretty much everything else, will instead eventually get around to a separate PR for just the global MIDI volume slider.

**Pull request closed without merging**
