### PR TITLE
Split Powernet into Powernet and PowernetPowerManager

### PR DESCRIPTION
**Pull request by 20kdc**
This restructuring allows for arbitrary networks to be built on the powernet wires.
Still uses the same infrastructure, just moves the code around.

(Specifics: Actual power control has gone into PowernetPowerManager, while Powernet is responsible for holding the power networking data and auto-instantiating PowernetManagers.)

This may be a prerequisite of a future solar-panel related PR (for in-dev work, see solar-panels-occlusion-and-tracking, but at time of writing it's not using it *yet*)

### CODE REVIEW

**Comment by PJB3005** [comment]
Isn't this uh, kinda stepping on the toes of #863, like a lot?

**Comment by 20kdc** [comment]
...Wait, there's a PR for that? ...I wasn't aware. Whoops. Sorry.

**Comment by AJCM-git** [comment]
600 loc killed in 5 seconds, devastating

**Comment by 20kdc** [comment]
Not really 600loc, most of it is from the split (hence the -472)

**Pull request closed without merging**
