### PR TITLE
Add "fixrotations" command to fix rotations of walls/windows/low walls

### PR DESCRIPTION
**Pull request by 20kdc**
Essentially, as a mapper, just run fixrotations and your wall rotation issues should go away.
May crash client due to PVS bugs.

Note: I found an issue with Saltern while playing around with this - the window between the airlocks at bridge is rotated the wrong way. This note should probably be moved to a separate issue or just plain fixed, hm

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
> May crash client due to PVS bugs.

Same problem I found when working on this command and why I started working on https://github.com/space-wizards/RobustToolbox/pull/1447
If it helps you any, the exception I was getting was `Failed to apply comp state` for the Transform component under two conditions, one of them pulls a transform component state with NaNs from the client's game state processor's last server states and tries to reset a predicted airlock with it. The second case was unclear to me. The solution that I found to this was to make PVS use nullspace instead of NaNs for entities outside of the bubble (https://github.com/space-wizards/RobustToolbox/issues/1210).

Every day we come closer to giving moony his command.

**Comment by 20kdc** [comment]
Migrated to new command structure, so it won't blow things up like setmind did, hopefully

**Comment by metalgearsloth** [comment]
Might useful to be able to specify an angle in case it needs to change? Apart from that just needs nullable and LGTM.

**Comment by metalgearsloth** [comment]
I need this to save physics so smacking that merge button

**Pull request merged**
