### PR TITLE
Clown goblins (April Fools)

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Small honk.

## Why / Balance

Honk!

## Media

https://github.com/space-wizards/space-station-14/assets/124214523/e16f08c8-576c-4185-a1fd-ce1be38548ed

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added horrific creatures. Clown goblins.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Did it go under and open the door? 

Funny punch should do stamina damage, make funny small boxing glove

**Comment by lzk228** [comment]
> make funny small boxing glove

for sprite?

**Comment by Cojoke-dot** [comment]
As in make its fists work like boxing gloves with a wideswing and stun

**Comment by PolterTzi** [comment]
They should be craftable.

**Comment by lzk228** [comment]
gonna add waddle if it added before 1 april #26338

**Comment by Nopey** [comment]
> gonna add waddle if it added before 1 april

Changes merged into the master branch are not automatically merged into the april fools branch.
Perhaps you should cherry-pick the commits from 26338 into this MR?

**Comment by lzk228** [comment]
> > gonna add waddle if it added before 1 april
> 
> Changes merged into the master branch are not automatically merged into the april fools branch. Perhaps you should cherry-pick the commits from 26338 into this MR?

i hope master will be merged to april fools before 1 april

**Comment by wafehling** [comment]
I want these in the base game

**Comment by ImWeax** [comment]
please god I want them in master branch

**Comment by ThunderBear2006** [comment]
I think this would be great in masterbranch if there was a unique way of making them, or just as an admeme for the time

**Pull request merged**
