### PR TITLE
Fix being able to use chameleon projector on medibot

### PR DESCRIPTION
**Pull request by lzk228**
:cl:
- fix: You can no longer disguise yourself as any NPC entity (e.g. medibot)

### CODE REVIEW

**Comment by Ilya246** [comment]
i think disguising as medibots should be kept in

**Comment by ScarKy0** [comment]
Please leave this in its so funny

**Comment by Ilya246** [comment]
> other bots can't be used for disguising the only reason medibot can is it has AnchorableComponent which is written in whitelist for projector

we should find a way for cleanbot (the other NPC bot) to be chame-able too then and maybe make it not rely on anchorable

**Comment by lzk228** [comment]
yeah, it's possible to just add tag to base bot, i'll make a new pr for this

**Pull request closed without merging**
