### PR TITLE
Glasses And Goggles Visual Change

### PR DESCRIPTION
**Pull request by Alekshhh**
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- tweak: Changed glasses and goggles visually

### CODE REVIEW

**Comment by MACMAN2003** [comment]
does everything need a resprite?

**Comment by Emisse** [comment]
he likes spriting let him cook

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
The connection between the rims and the temples of the glasses is way too high. It looks weird. The goggles also have no outlines at all and thus look pretty odd. Similar issue with the gar glasses: the shading is super uniform across them and lacks the subtle shaping and frames of the original.

These very much feel like oversimplifications and don't look particularly great.

**Comment by Alekshhh** [comment]
I am pretty sure I gave the goggles outlines, they previously did not have any
I didn't realize the orange and super gar had nice shading I swear it was different before, the green gars had nothing subtle about them at all though. I will copy the orange gar's shading on them
I don't get the glasses comment. they're fine
I wouldn't call any of this oversimplifying, not sure how you got to that conclussion

yeah I like to sprite why you being a hater

**Comment by deltanedas** [comment]
gar family are nice

**Comment by Hmeister-real** [comment]
I like the sprites. Emo has a wrong opinion?!?

**Comment by Golinth** [comment]
I don't mind how the three "star" ones look, they always were a bit flat IMO, but I really dont like the glasses or goggles look. The glasses in particular look kinda, off? Like their downwards tilt introduced more problems with the sprite than had they just been flat like the old ones. Cant get into specifics though, I'm not an artist, and certainly no spriter.

**Comment by TheShuEd** [comment]
I also don't like suggested star goggles sprite

**Pull request closed without merging**
