### PR TITLE
Decrease price of radio jammer from 4 tc -> 3 tc

### PR DESCRIPTION
**Pull request by beck-thompson**
## About the PR

Title! Both the base price and the discounted price are now half of their current values.

## Why / Balance

Right now, the radio jammer is still one of the least used uplink items despite the numerous buffs it has received:
#26046 - Blocking suit sensors
#25432 - 3x decrease in power usage
#25912 - Multiple blocking ranges

I think the primary issue is that there are just so many other better items to purchase at the 4tc level. Voice mask, chameleon clothing, agent id, jaws of life, toolbox, or even just a cobra, are all items that in 90% of cases I would rather purchase than the jammer while most are also cheaper.

I think having the jammer be a more common item could introduce a lot of interesting gameplay situations (For example I have never seen a nukie use it even though it could be very beneficial) but with it barely being purchased (And usually thrown away by thieves!) they almost never occur. It being more common could also help with issues like #32385 (Or just yelling on common the moment you get jumped).

**Changelog**

:cl: Beck Thompson
- tweak: The radio jammers price has been decreased from 4 -> 3 TC.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
Is it one of the least used uplink items? its so hard to tell with it. Either way, I think it's in a good spot for how strong it is, if its not used then its not used. Think about half the nades that people have the option of yet never pick. When was the last time someone specifically spent tc on en explosive grenade? Plus its more common to see because thieves have it

**Comment by beck-thompson** [comment]
>Is it one of the least used uplink items? its so hard to tell with it.

I'm basing this off the Delta-V usage rates (This was a little while back) but I don't think they'd change much since then or are noticeably different on upstream.

> Either way, I think it's in a good spot for how strong it is, if its not used then its not used. Think about half the nades that people have the option of yet never pick. When was the last time someone specifically spent tc on en explosive grenade?

Honestly, even with this TC discount, I still expect to almost never see it used! It has a very specific use case and you actively have to manage it and make sure it doesn't run out of battery. I'm really just trying to get it down to a level that actually somewhat makes sense in relation to other items. I'm hoping it will be more like a: "Oh I have 2 tc left, the radio jammer would work great if my plan goes south!". Right now you kind of have to plan around it a lot more because of its high cost. Right now if I have 4 tc burning in my pocket one of those other items is probably going to be the better choice.

If every syndicate starts buying this the yes, it's too low of a cost but I don't think that will happen.

> Plus its more common to see because thieves have it

I personally have never seen a thief use it and from what I've seen they usually just dump it in their stash! I could be wrong here but again, I have never seen a traitor ever buy the jammer in game and only seen it once or twice in a thiefs stash.

**Comment by Cojoke-dot** [comment]
The Radio Jammer in my mind fills a niche for killing heads that usually have tracking implants or a lot of armor and I would not be able to gun down faster than they can radio. It's an option for stealth kills when there is always a louder, quicker, and more effective choice in bombs. I guess it makes sense for it to have a tc drop... I just don't think it's going to be used that much more, it's still just going to be ignored by thieves, and if someone who got it as a bonus item does not want it people still aren't going to spend much tc on it. 🤷

**Comment by ps3moira** [comment]
I think with how easy you can get outted by AI now, this decrease makes sense.

**Comment by thebadman4662** [comment]
> I think with how easy you can get outted by AI now, this decrease makes sense.

Camera jamming buff PR when. :trollface:

**Comment by Sadopeer** [comment]
ive been outed by the ai too many times in the short period it's been added

**Comment by slarticodefast** [comment]
Hey, we had a discussion and vote among maintainers and apparently the radio jammer is very powerful, underrated and I'm just unrobust when it comes to using it properly 😄
But considering how rarely it is bought we decided that lowering the price to 3 TC should be fine. Could you adjust your PR for that?

**Review by slarticodefast — APPROVED** [review]

**Comment by Cojoke-dot** [comment]
3tc means I can get esword, storage implant, radio jammer, and a pair of funny glasses to hide who I am... worth

**Pull request merged**
