### PR TITLE
Remove zombie bundle from nukie uplink

### PR DESCRIPTION
**Pull request by bhenrich**
## About the PR

I removed the possibility to buy the Zombie Bundle from the NukeOps Uplink. The actual entity was left in the game.

## Why / Balance

Zombies are already a big threat to the station, big  enough to get their own gamemode. Realistically not every round has 15 SecOffs available for mass damage controll on two fronts, and dealing with a Zombie Apocalypse on top of NukeOps trying to kill everyone in their path is absolutely overwhelming for the station. It's very overpowered. Yes the zombies can also attack nukies, but they often have their own defenses figured out. Mix in assault borgs who are immune against zombies and the nukies can  stop worrying about security as they make their way to the nuke.

## Technical details

This only removed the listing from the uplink_catalog.yml, as well as related FTl entries. The actual item was left in the game.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: YuNii
- remove: Removed the Zombie Bundle from the NukeOps uplink.

### CODE REVIEW

**Comment by deltanedas** [comment]
zombie bundle is noob bait keep it in (zombie ops is almost always a loss)

**Comment by foob1** [comment]
Is it because you just died to the once in a blue moon successful zombie ops?

**Comment by Everturning** [comment]
spite PR of the year

**Comment by sporekto** [comment]
Almost no one buys it

**Comment by Brandon-Huu** [comment]
false

**Comment by vorkathbruh** [comment]
mald PR my beloved

**Comment by Emisse** [comment]
last time this was discussed it was decided to leave it in

**Pull request closed without merging**
