### PR TITLE
Allow AreaInsert pickups for one item

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Mirror of https://github.com/new-frontiers-14/frontier-station-14/pull/2005

Allows entities with StorageComponent and AreaInsert set to pick up item sets with one item in range by clicking on the floor.

## Why / Balance
Seems odd, comment implies it's a bug.

## Technical details
Spawn trashbag.
Spawn trash.
Stand near the trash, click on the floor.
Trash should be picked up.

## Media

https://github.com/user-attachments/assets/2aa12a85-f6f7-476f-b46d-fae696ddc136

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: whatston3
- fix: Area insert items can pick up single item sets when clicking on the floor.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Do you have evidence of this being relicensed as MIT?

**Comment by lzk228** [comment]
> Do you have evidence of this being relicensed as MIT?

it's literally one-liner (one-symbol, to be precise) that anyone other can come up with from their head
and it wasn't merged into frontier when the same author opened this pr, so this is just stupid to ask such questions

**Comment by metalgearsloth** [comment]
> > Do you have evidence of this being relicensed as MIT?
> 
> it's literally one-liner (one-symbol, to be precise) that anyone other can come up with from their head and it wasn't merged into frontier when the same author opened this pr, so this is just stupid to ask such questions

Frontier has complained about this in the past so this is a valid question and not "stupid" as you insinuate.

**Comment by dvir001** [comment]
We want to have this fixed on upstream so we can have the same logical bug fix to the issue, 
I merged it into Frontier after I opened it here so it can be fixed please.

Bug fixes should never be a "Frontier only" code when they effect everyone.

**Comment by whatston3** [comment]
As the writer of this change, I'm sure relicensing under MIT is fine.  No concerns from my side, at the very least.

**Comment by slarticodefast** [comment]
Thanks for the fix!

**Pull request merged**
