### PR TITLE
Updated cog

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR

Updated cog based on suggestions in discord (including commonly requested features such as a pipe from atmos to teg and a disposal tube from botany to chem)

## Media

Cog-0

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

not needed

### CODE REVIEW

**Comment by UbaserB** [comment]
cog doesn’t seem big enough for 80

**Comment by Spessmann** [comment]
Its almost as big as oasis but idk ill lower back to 70

**Comment by Plykiya** [comment]
It seems big enough for 80 to me? There's a lot of random places to loiter,

**Comment by Spessmann** [comment]
if emisse thinks it can take 80 ill up it back to 80

**Pull request merged**
