### PR TITLE
adds machine upgrades for microwave

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 

**Screenshots**

**Changelog**

:cl:
- add: Added machine upgrades for microwaves.

### CODE REVIEW

**Comment by theashtronaut** [comment]
does this mean better lasers mean you need to use less time for the recipes than you normally would?

**Comment by EmoGarbage404** [comment]
> does this mean better lasers mean you need to use less time for the recipes than you normally would?

You still need to select the same duration for the recipe, but it completes quicker.

**Comment by 0x6273** [comment]
I think power consumption should increase drastically while the microwave is cooking, to give capacitor upgrading more of a point. If the chef wants to have like 3 microwaves running at the same time, they should have to be upgraded to not overload the APC.

**Comment by Peptide90** [comment]
> I think power consumption should increase drastically while the microwave is cooking, to give capacitor upgrading more of a point. If the chef wants to have like 3 microwaves running at the same time, they should have to be upgraded to not overload the APC.

Out of scope. Devices either use power or dont. Someone mentioned working on active and idle power though but that’s a big thing.

**Pull request merged**
