### PR TITLE
Resprites energy sword and double energy sword

### PR DESCRIPTION
**Pull request by RiceMar1244**
## About the PR

This PR adds new inhand sprites for the energy sword and double energy sword to appear longer and more intimidating. This PR also touches up various visual details, like changing the alpha on the blades' flashing animation.

## Why / Balance

I thought the energy swords looked kinda stubby so i wanted to make them more imposing to entertain the scary sith lord fantasies of players using them

## Media

sword
double

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: RiceMar
- tweak: Energy swords and double energy swords now look as long as they seem to be in your hand.

### CODE REVIEW

**Comment by Emisse** [comment]
looks good, making the toy sword the old sprite might irk people who like it for obfuscating it though. im fine with this though approve

**Comment by RiceMar1244** [comment]
I thought making the toy sword the old sprite would be a cute little nod. I figured both that realistically its easy to tell a plasma blade from a plastic blade, and that the toy sword's stubbiness makes someone pulling out the real thing more spooky

**Comment by Emisse** [comment]
yea i think the sound is probably good enough to obfuscate it anyway and if youre in line of sight you can just inspect

**Comment by RiceMar1244** [comment]
Yeah i agree that the toy swords existence is an important obfuscating factor for the threat of an energy sword

**Comment by JoeHammad1844** [comment]
it looks pretty cool but the old sprite is just more iconic

**Comment by CrigCrag** [comment]
this is way better than le old sprite

**Pull request merged**
