### PR TITLE
Enables warden on Packedstation

### PR DESCRIPTION
**Pull request by Mith-randalf**
## About the PR 
Enables one warden job slot on the two maps big enough to justify it. Includes a spawn location in the brig and locker for each map.

This adds a new access group, Armory, which is _not_ enabled for security officers, but is added to HoS, Captain and Warden.

Biggest PR I've done so far by a wide margin, if I fucked anything up please tell me.

**Changelog**

:cl:
- add: Following numerous lawsuits relating to so-called 'shitcurity', Nanotrasen is now actively hiring brig Wardens for its deep-space stations.

### CODE REVIEW

**Comment by DogZeroX** [comment]
Awful PR

**Comment by metalgearsloth** [comment]
Isn't saltern a little small to have a warden

**Comment by Mith-randalf** [comment]
Yeah I had the same thought, I'm still kinda on the fence but I like playing warden so that pushed me towards adding it.

I wouldn't object to removing the slot from the map if thats the consensus.

**Comment by moonheart08** [comment]
I do not believe saltern needs a warden. It already feels quite full.

**Comment by Mith-randalf** [comment]
And he's outta there.

There's still a locker, so the HoS can promote someone if he wants. That seem good?

**Comment by TimrodDX** [comment]
I'd be fine with this for Packed, since Packed canonically has a Warden.

**Comment by Mith-randalf** [comment]
packed has canon?

**Comment by Elijahrane** [comment]
> EDIT: Packed also has canonical armory doors, and I'd like to see those put in if nothing else.
I have those in [5573]

**Review by PaulRitter — APPROVED** [review]

**Pull request merged**
