### PR TITLE
Engineering Locker Fill Change

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changed the contents of engi and atmos lockers

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed engi and atmos locker contents

### CODE REVIEW

**Comment by Anzarot121** [comment]
Does atmos really need a medical kit for burns instead of a kit for lack of air? Their equipment reduces fire damage by 82 percent. I have never needed ointments, but medipene often saved engineers who went where they didn’t ask from damage caused by an ax.

**Comment by Alekshhh** [comment]
felt like it would fit the firefighter sort of thing going for them. also common for an atmos to get burn damage even with their hardsuit so the ointment is handy.

**Comment by Anzarot121** [comment]
Their problem is that they wear hardsuits instead of firesuits. Firesuits have burn resistance similar to the Death Squad. The only time you need a hardsuit is if you don't plan on dying from an Atmos bomb.

**Comment by Alekshhh** [comment]
maybe just having a simple medkit would be a best between both worlds

**Comment by deltanedas** [comment]
why do they have a medkit to begin with

**Comment by Alekshhh** [comment]
fuck if I know

**Comment by Alekshhh** [comment]
you know what good point atmos doesn't deserve good things

**Comment by Anzarot121** [comment]
I agree.

**Comment by metalgearsloth** [comment]
So my reasoning for this:
1. Adding insuls to more lockers is bloaty when it already exists in one locker and atmos techs don't 100% need insuls.
2. Adding small chance plushies is bloat and shouldn't be in lockers; we've removed this elsewhere.
3. Random chance toolboxes is also not great and better off being via vending machine or guaranteed spawns instead of having a 1/4 chance of spawning nothing / 2 toolboxes.

**Pull request closed without merging**
