### PR TITLE
New secure arsenal 

### PR DESCRIPTION
**Pull request by Strol20**
## Why / Balance

It is fun

## Technical details

It is just respriting
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by nikthechampiongr** [comment]
I am sorry but this is completely inappropriate. I will have to remove the media from your pr.

**Comment by CatMagic1** [comment]
what... was it?

**Comment by Carmell0** [comment]
Yeah what was it

**Comment by Strol20** [comment]
April Fool's joke. But everything is broken

**Pull request closed without merging**
