### PR TITLE
Construction formatting to follow PascalCase conventions

### PR DESCRIPTION
**Pull request by Peptide90**
As discussed in discord, I've started with the recipes section in cleaning up our ID names for consistency.

All IDs related to construction are now PascalCase, this includes graph IDs which for 99% of the case before hand were not pascal. They are IDs after all, so this involved updating the graphs in the construction compontent of everything they touched.

Some other cases of entity IDs that were updated include changing all acronym IDs to upper case so BaseApc became BaseAPC etc.

Map changes are in relation to changing SalternApc and SalternSmes which are on every map to SalternSMES and SalternAPC etc.

Will gradually look at all remaining areas to ensure we are consistent with ID and graph naming.
### NOTICE:
When this is merged we need to notify anyone with an open map PR or currently producing maps to do a find and replace on their map file to replace `SalternApc` with `SalternAPC` and `SalternSmes` with `SalternSMES` or they will fail tests.

### CODE REVIEW

**Comment by Peptide90** [comment]
Test passes locally made sure of it. ssreach has had it's `SalternApc`'s replaced with `SalternAPC` so is a non issue...

**Comment by mirrorcult** [comment]
> Test passes locally made sure of it. ssreach has had it's `SalternApc`'s replaced with `SalternAPC` so is a non issue...

have you tested loading in reach locally?

**Comment by Peptide90** [comment]
> > Test passes locally made sure of it. ssreach has had it's `SalternApc`'s replaced with `SalternAPC` so is a non issue...
> 
> have you tested loading in reach locally?

Loading it in game works albeit with odd power issues. Reach is in emergency lighting mode whereas Saltern spawns in the dark but with some areas lit. Will try debug but can't see why if the only thing changing is the APC's and SMES' but all are present.

**Review by mirrorcult — APPROVED** [review]
passes tests and linter so its probably fine

**Review by ShadowCommander — APPROVED** [review]

**Comment by Peptide90** [comment]
Fixed conflicts. Should be good for merge now.

**Pull request merged**
