### PR TITLE
Cog engineering DIY update

### LINKED ISSUE #31995: Double carpet in chapel on Cog
## Description

There is two "chapel's carpet" in the northern part of Cog's chapel which causes a bunch of Z-fighting

**Reproduction**

You find yourself on Cog Station. Go to eastern part of the map with Cog.
Observe Z-fighting whilst playing gmod ragdoll noises in your head.

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by Spessmann**
## General
- fixed #31995
- various changes to maints rooms
- removed some "useless" (not used for decorative or useful purpose) space(ed areas)
- robotics now has a med/sci door to med lobby for futureproofing
- changed the side of windoors on various front desks so people can now place things on the counter
- slight changes to robotics
- changed some of the windows in viro/gene to walls
- added some random grilles to solars that were missing
- added another maint connection to cargo
- added plating under the conveyor belt at salv
- changed station anchor room
## Engineering
- moved superpacman to SMES
- removed radiation protection lockers
- doubled 5->10 the amount of uranium roundstart
### TEG
- TEG no longer starts setup
- gave TEG some maints access
- TEG has been resized
- added another burn chamber to teg, made it bigger
### Containment/PA
- removed northern airlock and substation room from containment
- moved containment storage to where substation and northern airlock was
- increased the size of southern airlock, added third side
- added a maints connection to entrance room
- removed roundstart setup
- removed singularity generator and radiation collectors
- removed radiation shielding and radiation lockers
- added tesla supplies to containment storage
- added 4 emitter flatpacks and 4 containment fields to containment storage
- added more materials to build containment with
## Why / Balance

In testing, with one engineer it took about ~10 minutes from round start to functioning tesla, making use of the AME, SUPERPACMAN, and PACMAN. because the tesla is much smaller than a singularity, its much faster to set up. With multiple engineers it could go even faster. Additional materials (stack of steel and plasteel, two stacks of rods) are provided at containment for engineers to construct meteor shielding, although in practice it took only one stack of rods to make a working setup. If engineers really need more time, they could set up solars, overclock the AME, or just do TEG instead of bothering with tesla. 

Engineers have gotten lazy and use singularity most of the time even when they could do tesla, its time for them to learn :trollface: 

## Media

github hates me and wont let me post a image because its too big, look at the bot's generated image
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

no changelog

### CODE REVIEW

**Comment by Spessmann** [comment]
I think engineering flickers due to being connected to the high-power variable HV instead of the stable SMES hv so im gonna move the engineering substation later

**Comment by Golinth** [comment]
> Engineers have gotten lazy and use singularity most of the time even when they could do tesla, its time for them to learn

This is because the tesla is literally worse in every way, not because of laziness.

**Comment by Spessmann** [comment]
Most maps can take singo roundstart while tesla requires much more time to get running because it's not set up or even partially set up.

**Comment by ArtisticRoomba** [comment]
I gave my opinions on discord not knowing more about this change (I was playing YOMI lmao), but now I have the full encompassing idea of it, here are my thoughts (as someone who religiously plays engineering):

- The TEG at least needs a round-start cold loop off into space or at least have pipes mapped underneath walls to facilitate easily building a cold loop. Otherwise, engineers have to deconstruct walls to add a coldloop. Making the coldloop in one of the burn chambers is not really good enough, it should be it's own thing.
- I am _heavily_ against overclocking the AME in any shape form or fashion to enable a seamless power transition roundstart. It is an unnecessary and dangerous noob-trap. It should not be remotely considered an option to help bridge roundstart battery power to a reliable power source. Maybe another generator should be included. See #31758 for why you can't just increase the core count of the AME to counter this.
- If going the generator route: It would be best to include generator power grid connect spots where engineers can just fire up the generator, instead of having to look for a spot to plop it down. I can't look in game right now so if you already did this, sorry, but you should make it move obvious. Maybe include a mapped note.
- It looks like the AI needs more cameras in the new engineering section you just added.
- I would add a second volumetric pump on the start of the pipe mapped to the TEG and have it labeled so people know where it goes, right now it's just a bare pipe and it would be nice to have confirmation about where it goes.
- AI needs cameras outside their core in space, IMO. It's a highly secure area, and cameras on the outside of AI's core exists on other stations.
- The room before the PA (where the materials, machines, etc. are) needs a visible air scrubber.

My thoughts about the Tesla:

- You should probably map enough plasteel to make a 1-wall thick reinforced wall containment (map enough out to make a _reasonably sized containment_). Otherwise having a bare Tesla out and about, in the way of meteors, is just going to lead to more teslooses. Will also lead to some very easy sabotages.
- I would map 2 more grounding rods to promote safety and increase the odds of a tesloose not happening. I believe some stations do this already.
- I would map an explainer note saying not to put grounding rods and coils next to emitters, and not to put emitters next to the pylons, much like Core's explainer note. That would prevent some noobtraps.

Oh, it just got merged. Nevermind.

**Comment by Spessmann** [comment]
> Oh, it just got merged. 
> Nevermind.
I was going to update it but emisse merged, going to make another update pr

**Comment by cohanna** [comment]
i would hope for at least some kind of shielding for the PA/Tesla chamber, having it DIY is fine-ish but the lack of meteor shielding (or other protections) suck.

**Comment by Sarahon** [comment]
this update is not practical with engineering's current time constraints.

**Comment by ArtisticRoomba** [comment]
engineering always will find a way, whether blowing up the ame or otherwise
that reminds me I need to change the AME curve to PROPERLY follow degenerate strategy because a 2core ame producing less power than a 1 core ame and using less fuel is absurd and invalides mappers giving engineering more of a buffer with mapped multi-core AMEs

**Comment by Sarahon** [comment]
> engineering always will find a way, whether blowing up the ame or otherwise that reminds me I need to change the AME curve to PROPERLY follow degenerate strategy because a 2core ame producing less power than a 1 core ame and using less fuel is absurd and invalides mappers giving engineering more of a buffer with mapped multi-core AMEs

if there's only 1 person in engineering then OCing is not at all practical or easy to manage

**Comment by Sarahon** [comment]
I need to know why it was designed that we are being forced to build Tesla over Singulo. Like who honestly finds building a box every time they play a station fun? The map was in a good place before this update. The superpac is not enough to help along with AME to keep power. The round I played a moment ago was a disaster since there was 1 atmos and a CE. It completely halted the round for ages. Antags were running around wild. 

We've had multiple maps attempt to have no containment and "build it yourself" but it never works because there's firstly, not enough time to do it, and secondly it's tedious as fuck and boring really. Please add it and the TEG pipes back for the love of god.

**Comment by cohanna** [comment]
> Please add it and the TEG pipes back for the love of god.

nah I like the pipeless teg saves me time ripping up whatever garbage is already there.
If the tesla parts are changed to flatpacks (like the emitters and field generators) and has a small meteor shield around it round start it would be significantly more manageable for small teams.

**Comment by superjj18** [comment]
This update was awful and has caused a few terrible grasshopper rounds.  I honestly think this version of cog should not appear on grasshopper

When I first ran into this version of cog I was fucking pissed as AI because I had no idea engineering was nuked into oblivion, I had no idea why the 2 station engineers and 3 TAs couldn't get anything other than the AME working

**Comment by cohanna** [comment]
> This update was awful and has caused a few terrible grasshopper rounds. I honestly think this version of cog should not appear on grasshopper
> 
> When I first ran into this version of cog I was fucking pissed as AI because I had no idea engineering was nuked into oblivion, I had no idea why the 2 station engineers and 3 TAs couldn't get anything other than the AME working

#32875 fixes a lot of the issues i think the current setup has so wait for that to go into the stable release

**Pull request merged**
