### PR TITLE
It's a waffle home. [New Salvage]

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
Adds a new medium sized salvage map, the Waffle Home. Manned by a few bears and chock full of goodies, it should be a nice stop on a Sunday afternoon after church.
**Screenshots**

image

**Changelog**

- N/A

### CODE REVIEW

**Comment by mirrorcult** [comment]
do you have a list of the mob spawns/items contained in this salvage?

**Comment by EmoGarbage404** [comment]
> do you have a list of the mob spawns/items contained in this salvage?

3 space bears
2 75% random salvage spawners
5 salvage crate spawners
Microwave
Dinnerware dispenser 
Cloth stack
Assorted waffles

**Comment by Veritius** [comment]
It has a lot of unnecessary empty space. Maybe that big middle bit in the main area could have some more tables.

**Comment by Peptide90** [comment]
Reminds me of the Fallout broken dreams cafe random encounter

**Review by mirrorcult — APPROVED** [review]

**Comment by ike709** [comment]
> It has a lot of unnecessary empty space. Maybe that big middle bit in the main area could have some more tables.

That's because it's more or less identical to an actual Waffle House.

**Comment by EmoGarbage404** [comment]
> > It has a lot of unnecessary empty space. Maybe that big middle bit in the main area could have some more tables.
> 
> That's because it's more or less identical to an actual Waffle House.

ike is a fellow waffle house connoisseur.

**Pull request merged**
