### PR TITLE
Remove gondola donkpocket & change berry box description

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

Removed Gondola donkpocket and changed Berry donkpocket box description.

## Why / Balance

Gondola donkpocket references [Gondola](https://knowyourmeme.com/memes/gondola), which is visually a derivative of [P*dobear](https://en.wikipedia.org/wiki/Pedobear). In its donkpocket form, there is only the name distinguishing the two. This can become problematic as SS14 reaches a wider audience, [due to the latter being more recognized](https://trends.google.com/trends/explore?date=all&q=Gondola%20meme,Pedobear&hl=en-GB).
Berry donkpocket references "[Operation Iraqi Freedom](https://www.history.navy.mil/browse-by-topic/wars-conflicts-and-operations/middle-east/operation-iraqi-freedom.html#:~:text=On%2020%20March%202003%2C%20Operation,on%20ships%20in%20the%20region.)".

These properties were grandfathered in from SS13 with the large food PR, and has not been touched since. 

## Technical details

Gondola donkpocket boxes are replaced with Pizza donkpockets.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
do not change maps use migration

**Comment by SlamBamActionman** [comment]
> do not change maps use migration

TIL about migration.yml!

Should be fixed now :)

**Review by metalgearsloth — APPROVED** [review]

**Comment by SlamBamActionman** [comment]
Failed check likely false positive.

**Comment by IamVelcroboy** [comment]
I feel like it's wording is kinda weird. My suggestion would be `A relentlessly sweet donk-pocket. Made with 100% artificial flavoring.`

**Comment by SlamBamActionman** [comment]
> I feel like it's wording is kinda weird. My suggestion would be `A relentlessly sweet donk-pocket. Made with 100% artificial flavoring.`

It was meant to be a pun on the "no artificial flavoring", and sorta follow the sentence structure of the other donkpockets. Ngl I like yours better though. I'll change it.

**Comment by potato1234x** [comment]
i never made the connection between pedobear and gondola, very unnecessary change :/

**Comment by Blazeror** [comment]
Personally I don't think nuking all the weird shit from 13 is the right way. It's all part of what gave 13 it's unique charm. Unless it's something very problematic I don't get the point of sanitizing everything, it will only leave things blander.

**Comment by VasilisThePikachu** [comment]
> Personally I don't think nuking all the weird shit from 13 is the right way. It's all part of what gave 13 it's unique charm. Unless it's something very problematic I don't get the point of sanitizing everything, it will only leave things blander.

It's unique charm of having a VERY bad reference IMO? No I'm agreeing to vote this out. It's a damn food item there are other donks you can eat.

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by Blazeror** [comment]
> > Personally I don't think nuking all the weird shit from 13 is the right way. It's all part of what gave 13 it's unique charm. Unless it's something very problematic I don't get the point of sanitizing everything, it will only leave things blander.
> 
> It's unique charm of having a VERY bad reference IMO? No I'm agreeing to vote this out. It's a damn food item there are other donks you can eat.

There are nukes in the game, something several times worse than a reference to a war. Not sure I would say it's a "VERY bad reference".  There's a bunch of stuff that was made because of wars in the game, including weapons from the world wars. Those are also a type of references to a, in my option, much worse war.

I just think it's a description that is more memorable than just a bland pizza flavor.

**Comment by GreyMario** [comment]
> > > Personally I don't think nuking all the weird shit from 13 is the right way. It's all part of what gave 13 it's unique charm. Unless it's something very problematic I don't get the point of sanitizing everything, it will only leave things blander.
> > 
> > 
> > It's unique charm of having a VERY bad reference IMO? No I'm agreeing to vote this out. It's a damn food item there are other donks you can eat.
> 
> There are nukes in the game, something several times worse than a reference to a war. Not sure I would say it's a "VERY bad reference". There's a bunch of stuff that was made because of wars in the game, including weapons from the world wars. Those are also a type of references to a, in my option, much worse war.
> 
> I just think it's a description that is more memorable than just a bland pizza flavor.

Nice job using the less offensive item as a strawman to deflect from the actual problem

**Comment by VasilisThePikachu** [comment]
> > > Personally I don't think nuking all the weird shit from 13 is the right way. It's all part of what gave 13 it's unique charm. Unless it's something very problematic I don't get the point of sanitizing everything, it will only leave things blander.
> > 
> > 
> > It's unique charm of having a VERY bad reference IMO? No I'm agreeing to vote this out. It's a damn food item there are other donks you can eat.
> 
> There are nukes in the game, something several times worse than a reference to a war. Not sure I would say it's a "VERY bad reference". There's a bunch of stuff that was made because of wars in the game, including weapons from the world wars. Those are also a type of references to a, in my option, much worse war.
> 
> I just think it's a description that is more memorable than just a bland pizza flavor.

I was talking about the Gondola one. And even in this case I would prefer not having a reference to a war. No matter if its "in lore" or not. You will live without a piece of text. Trust me

**Comment by Blazeror** [comment]
> I was talking about the Gondola one. And even in this case I would prefer not having a reference to a war. No matter if its "in lore" or not. You will live without a piece of text. Trust me

I don't know anything about Gondola or the meaning behind it so if it's problematic it should go for sure.

My original comment was more about the policy of sanitizing stuff than these items in particular. And I think when you even count the reference to a war as problematic enough to warrant removal it's sort of a slippery slope like I mentioned with other items.

> Nice job using the less offensive item as a strawman to deflect from the actual problem

That's not what a strawman is and I'm not defending Gondola, if it's problematic it can go. I was commenting on sanitizing in general.

**Comment by Tayrtahn** [comment]
For the record (is there some reason we can't explain this?), Gondola is a derivative of the Spurdo Spärde meme character, which is itself derived from P*dobear.

**Comment by GreyMario** [comment]
hey so it turns out content added by 4chan to a video game tends to be pretty offensive by nature of it coming from 4chan and i think we should probably _not_ have that

**Comment by Errant-4** [comment]
How many of those downvote people have ever even _known_ these thing were in the game?

**Comment by Blazeror** [comment]
Having read my first comment again I think I failed to really make my point.

I think removing these things is fine, but they are unique items/descriptions that stand out so I think they should be replaced with something else that is unique rather than just generic stuff like the pizza flavor with no unique look. Have it be some other weird meat with a unique sprite and make it a fictional war for example. I don't think unique to generic is a good way to go.

I do however think that if the reference to Iraqi freedom is too much then what about the Mosin having a reference to the world wars trench warfare? It becomes sort of unclear and arbitrary where to draw the line.

**Comment by GreyMario** [comment]
> How many of those downvote people even _knew_ these thing were in the game?

I'd bet ten spesos someone posted this PR to a SS13 community

**Comment by EmoGarbage404** [comment]
Dont complain about astroturfing when people are just disagreeing with you. Keep discussion on topic, please.

**Comment by DogZeroX** [comment]
Personally, I don't like gondolas in general, wouldn't mind seeing it replaced or removed entirely. Figure it's some 4chan meme I'm not really keen with?

**Comment by EmoGarbage404** [comment]
It'd be nice if the items were replaced with something equally wacky so that they weren't just made less unique

**Comment by Rainbeon** [comment]
We've straight up removed a bunch of things in the past few months with no replacement ready, I'm not really sure why the line on that is drawn on Gondola pockets, anyone can always just PR more wacky pockets later afterall

**Comment by deltanedas** [comment]
wacky pocket #1: carp pockets

**Comment by SlamBamActionman** [comment]
> I do however think that if the reference to Iraqi freedom is too much then what about the Mosin having a reference to the world wars trench warfare? It becomes sort of unclear and arbitrary where to draw the line.

The Mosin does not refer to any specific war:
`A weapon for hunting, or endless trench warfare. Uses .30 rifle ammo.`
`A bolt action service rifle that has seen many wars. Not modern by any standard, hand loaded, and terrible recoil, but it is cheap.`
As written in my longer reply, I am not against references to warfare or other general horribleness (it's a game where you can turn someone into mush with a toolbox, after all). But in a world of fantasy warfare and corporate espionage, I see no reason to reference a specific and tragic real-world event by name. Better to expand the SS14 world instead.

> We've straight up removed a bunch of things in the past few months with no replacement ready, I'm not really sure why the line on that is drawn on Gondola pockets, anyone can always just PR more wacky pockets later afterall

This would be the best option. If someone feels the need to add something new to the line-up of clown, lizard and weed donk-pockets to make up for losing gondola-pocket, then the door's wide open for that. But I don't see why it should be a precursor for this PR removing problematic elements.

**Comment by deltanedas** [comment]
iraq war has nothing to do with berries so no reason to not replace it

**Pull request merged**
