### PR TITLE
Sleep on Stasis Beds

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Made stasis beds heal you at the same rate as normal beds and allows you to sleep on it.
Edit: I have made the healing 100x worse than normal beds.

## Why / Balance

I kinda just wanted to sleep on a stasis bed and was sad I couldn't. I'm open to any arguments for changing the numbers...

## Technical details

.yml component that adds a sleep action

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no changelog cause this feels like it shoulda already been a thing...

### CODE REVIEW

**Comment by K-Dynamic** [comment]
> it definitely shouldn't be healing you, but being able to sleep is nice.

Well why else would you sleep (on a medical bed) if it didn't heal you?

btw stasis beds prevent breathing, sleeping might outheal asphyxiation damage

**Comment by Plykiya** [comment]
> > Well why else would you sleep (on a medical bed) if it didn't heal you?
> > btw stasis beds prevent breathing, sleeping might outheal asphyxiation damage
> 
> medical beds don't heal you for sleeping, they heal you for just being on them. Sleeping is purely an RP thing.

You heal three times faster when sleeping on beds.

**Comment by deepdarkdepths** [comment]
This really conflicts with how stasis beds halt metabolism to a crawl. It doesn't make sense to add healing to it.
If you want some quick heals, sleep on a normal bed.

**Comment by Plykiya** [comment]
> This really conflicts with how stasis beds halt metabolism to a crawl. It doesn't make sense to add healing to it. If you want some quick heals, sleep on a normal bed. You shouldn't be on a stasis bed long term anyway as it asphyxiates you.

Stasis beds halt your metabolism, sure, but I always thought about the healing part as just... like... really comfy bedrest is easier to recover from than the bed actually doing anything to heal you. The asphyxiation is pretty minor, I rested on one for like fifteen minutes while I injected poison directly into my veins nonstop...

**Comment by Terraspark4941** [comment]
Biologically, healing requires cells to perform chemical reactions on itself, which is also called the cell's metabolism.
Thereby, the cell should not be able to heal (very quickly, if at all) if its metabolism is brought to a near-halt.

> You heal three times more effectively when sleeping on beds

Because sleeping is considered a rest-state of the body, in which the body can redirect most of its energy to mental and physical repairs.

**Comment by Plykiya** [comment]
> Biologically, healing requires cells to perform chemical reactions on itself, which is also called the cell's metabolism. In cases of cells being killed, nearby cells reproduce to fill the gap. This requires energy in order to perform the reactions required to properly split apart cells; again, metabolism. Thereby, cells and the body should not be able to heal (very quickly, if at all) if its metabolism is brought to a near-halt.
> 
> > You heal three times more effectively when sleeping on beds
> 
> Because sleeping is considered a rest-state of the body, in which the body can redirect most of its energy to mental and physical repairs.
> 
> In my opinion, being able to sleep on a stasis bed would be an interesting quality of life, but it would make no logical sense to make stasis beds heal as fast as normal beds do while slowing down your metabolism.

I can... I can make it 100 times more pathetic then, to match the theme of stasis beds?

**Comment by thebadman4662** [comment]
> > Biologically, healing requires cells to perform chemical reactions on itself, which is also called the cell's metabolism. In cases of cells being killed, nearby cells reproduce to fill the gap. This requires energy in order to perform the reactions required to properly split apart cells; again, metabolism. Thereby, cells and the body should not be able to heal (very quickly, if at all) if its metabolism is brought to a near-halt.
> > > You heal three times more effectively when sleeping on beds
> > 
> > 
> > Because sleeping is considered a rest-state of the body, in which the body can redirect most of its energy to mental and physical repairs.
> > In my opinion, being able to sleep on a stasis bed would be an interesting quality of life, but it would make no logical sense to make stasis beds heal as fast as normal beds do while slowing down your metabolism.
> 
> I can... I can make it 100 times more pathetic then, to match the theme of stasis beds?

Do not forget to make it 100 times stronger when emagged, as it reverses stasis effects. :trollface:

**Pull request merged**
