### PR TITLE
Solution containers lids to separate class

### PR DESCRIPTION
**Pull request by Macoron**
## About the PR 
Move solution container lid logic from `DrinkComponent` to a new `SolutionContainerCapComponent`.
Add a new visualizer for beakers lids. Also add verbs to close or open a lid

Will be a draft until #3434, though it breaks almost all drinks. Though beakers should work fine.

**Screenshots**

image

**Changelog**

:cl:
- add: Add beakers lids

### CODE REVIEW

**Comment by mirrorcult** [comment]
comp should probably be caleld SolutionContainerLid since 'cap' is a term used elsewhere in solution container code and it might be confusing

**Comment by SweptWasTaken** [comment]
Are you going to come back to this?

**Comment by Macoron** [comment]
> Are you going to come back to this?

Yes, but due to #3434 I can't update drinking glasses.

**Comment by SweptWasTaken** [comment]
> 
> 
> > Are you going to come back to this?
> 
> Yes, but due to #3434 I can't update drinking glasses.

You can go ahead, it should impact me very little.

**Comment by PaulRitter** [comment]
@Macoron are you coming back to this?

im gonna close this for now for being stale

**Pull request closed without merging**
