### PR TITLE
add impersonate traitor objective

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
new objective that requires you to have the same identity as the target for 10 minutes straight before round ends, so id + wear a mask.
presumably youd have to kill them too to avoid any "why is this guy running around with my id pretending to be me"

## Why / Balance
cool new objective to spice up rounds a bit from the boring mostly just stealing and killing.

## Technical details
- impersonate logic requires you to have the same identity as the target for 10 minutes before round ends
- made TargetObjective's Title optional and added description so its more customizable.
- added AntiSocialObjective marker component since it makes it easier to maintain social's blacklist with kill and impersonation and anything else in the future that would fit in.

## Media
silly urist

i am the captain now

le epic greentext

we must wait

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: The Syndicate may now assign operatives the goal of assuming the identity of crewmembers.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Isnt this a ling objective

**Comment by deltanedas** [comment]
yes and the condition could be reused for it, its still a nice objective for traitors (and sometimes is already mandatory e.g. nuke disk impersonating cap is a lot easier than trying to hide from sec in space forever)

**Comment by LankLTE** [comment]
If it’s checking identity wouldn’t an agent ID let you do this for free

**Comment by deltanedas** [comment]
> If it’s checking identity wouldn’t an agent ID let you do this for free

yes and read the comment it explains why thats fine ish
Good Players should still actually replace the person not just be a duplicate
of course if someone does just do this theyll instantly get outed so it isnt a very good strat

**Comment by LankLTE** [comment]
> Good Players should still actually replace the person not just be a duplicate
> 
> of course if someone does just do this theyll instantly get outed so it isnt a very good strat

Saying "good players won't abuse the abusable objective logic" doesn't really make sense. I don't see how just letting someone buy an agent ID on the shuttle for a free greentext is a good or interesting objective

**Comment by deltanedas** [comment]
> Saying "good players won't abuse the abusable objective logic" doesn't really make sense. I don't see how just letting someone buy an agent ID on the shuttle for a free greentext is a good or interesting objective

they can also just hide the real id in their bag then equip it instantly

perhaps it should just be you have to wear it for 10 minutes total then its complete, so you cant do this scumbag strat and theres a little danger. unless you are lew pel then hide in disposal unit with it

**Comment by LankLTE** [comment]
> they can also just hide the real id in their bag then equip it instantly

then they at least need to steal the real ID instead of just spending 3 TC and calling it a day

**Comment by deltanedas** [comment]
> then they at least need to steal the real ID instead of just spending 3 TC and calling it a day

its still not impersonating if you just put an id on last second, agent id or not.

**Comment by deltanedas** [comment]
every shitty tactic is now impossible :trollface:

**Comment by LankLTE** [comment]
you can still just spend 3 TC on an agent ID and then chill in maints for 10 minutes

**Comment by deltanedas** [comment]
its pretty likely that you get caught just doing that, also it has to be 10 minutes before evac so you cant do it 10 minutes roundstart then destroy the agent id

**Comment by deltanedas** [comment]
you arent able to its unique

**Comment by Equivocateur** [comment]
> its pretty likely that you get caught just doing that, also it has to be 10 minutes before evac so you cant do it 10 minutes roundstart then destroy the agent id

I'm maint ratting for 30 minutes with "Literally an agent ID name" as my display name to get a single medical doctor to cry on comms for sec to show up and a single cadet comes after like 10 minutes.


On average.

**Comment by UbaserB** [comment]
I had this idea a while ago myself since its actually REALLY cool, i just never bothered to set the conditions more because of all the conflicts there are with abuses.

**Comment by keronshb** [comment]
This is a ling objective and shouldn't be given to traitor.

It's also exceptionally hard to complete this objective for people who are regulars.

Metagaming between rounds is typically against the rules but people usually know how their friends act. And if you don't act like them at all you'll be sticking out like a sore thumb.

**Comment by UbaserB** [comment]
ive impersonated plenty of times as a syndicate, the objective itself isnt impossible… but i do agree its better for a changeling; no idea if lings are coming to 14 though

**Comment by NancokPS2** [comment]
Does it really matter if the objective is easy or not?  
Syndicate are not forced to complete objectives to begin with, they are just a suggestion.  
  
It's like when you just wait for your kill objective to die on their own or simply keep them out the evac shuttle last minute without even making a move all round.  
Or when you spend all round waiting for the cap to give you an opening to do any objective regarding them.  
  
If people want to wait forever for an objective, they will do so, be it with this one or any other objective.

**Comment by EmoGarbage404** [comment]
i agree with keron that this doesn't really make sense as a traitor objective. For ling, stealth is a primary means to accomplish your goal. Traitors on the other hand have a variety of different methods by which they can choose to complete their objectives: stealth exists primarily as a means to an end, rather than a core trait in and of itself.

**Comment by mirrorcult** [comment]
shouldnt be a traitor obj should be ling or paradox twin

**Comment by CrigCrag** [comment]
who wants to code ling or paradox twin

**Comment by JoeHammad1844** [comment]
> who wants to code ling or paradox twin

image

**Comment by Hmeister-fake** [comment]
> who wants to code ling or paradox twin

Paradox twin is already a thing in Delta V or Parkstation (I forgot which)

**Comment by deltanedas** [comment]
ok no more

**Comment by deltanedas** [comment]
ling objective requires transforming as well

**Comment by keronshb** [comment]
> Can this be modified to keep as unused? For when ling is added

It shouldn't be added unless it has a current use, unless that policy changed.

> ling objective requires transforming as well

Polymorph should take care of this

**Pull request closed without merging**
