### PR TITLE
Adjusted stripping menu size and order

### LINKED ISSUE #10424: Default strip menu vertical size is too small to accomodate right hand button
## Description
Default strip menu vertical size is too small to accomodate right hand button. Bit annoying having to resize it every time.

**Reproduction**
- Open strip menu for mob

**Screenshots**
ghost_buckler

### PR DESCRIPTION
**Pull request by JustinTrotter**
## About the PR 
Closes #10424 

Someone had a PR about this and it got closed for some reason, so I figured I'd pick it up. Comments in the PR said that hard coding a height increase of the window is fine for now. So I did that.

Also I'm adjusting the order of the inventory. Basically flipping everything in the stripping menu so that the equipment is sorted from top to bottom and from inner to outer. This has the side effect of also changing the order inventory interface at the bottom of the screen. This might rub folks the wrong way, but I'm going to take the chance now to include it because I think it's better this way. (I'll change it back if requested).

**Screenshots**

Stripping menu with new default height and reordered
(UPDATE: I moved the ID to below the pockets to preserve the bottom inventory order [pocket 1, pocket 2, id])

New proposed order for inventory

**Changelog**

:cl:
- tweak: Increased stripping menu height and reordered inventory

### CODE REVIEW

**Comment by keronshb** [comment]
> ## About the PR
> 
> Closes #10424
> 
> Someone had a PR about this and it got closed for some reason, so I figured I'd pick it up. Comments in the PR said that hard coding a height increase of the window is fine for now. So I did that.
> 
> Also I'm adjusting the order of the inventory. Basically flipping everything in the stripping menu so that the equipment is sorted from top to bottom and from inner to outer. This has the side effect of also changing the order inventory interface at the bottom of the screen. This might rub folks the wrong way, but I'm going to take the chance now to include it because I think it's better this way. (I'll change it back if requested).
> 
> **Screenshots**
> 
> Stripping menu with new default height and reordered (UPDATE: I moved the ID to below the pockets to preserve the bottom inventory order [pocket 1, pocket 2, id]) 
> 
> New proposed order for inventory 
> 
> **Changelog**
> 
> 🆑
> 
>     * tweak: Increased stripping menu height and reordered inventory

You might want to make it slightly bigger to accommodate for both handcuffs and ensnares (coming soon, PR is open for it)

**Comment by JustinTrotter** [comment]
> You might want to make it slightly bigger to accommodate for both handcuffs and ensnares (coming soon, PR is open for it)

Could you please link me to that PR? I'd like to look at it to accommodate.

**Comment by keronshb** [comment]
> 

#9968

**Comment by EmoGarbage404** [comment]
the last time this pr was opened, it was brought up the it should just automatically scale to fit all of the buttons. Making prs upping the size every time someone adds a new clothing slot is just strange. Additionally, it'll appear weird with entities that don't have as many slots (such as monkeys).

**Comment by mirrorcult** [comment]
im fine with this until it just gets replaced with hud refactor and electro's PR

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
