### PR TITLE
Advanced uniform printer part 1

### PR DESCRIPTION
**Pull request by Yeah-I-listening-Hollywood-undead**
## About the PR
adds an advanced uniform printer that prints clothes faster and has new unique types of clothes to print

## Why / Balance
So far, the balance has not been affected in any way. After that, I want to add new PR recipes with uniforms and equipment that will simplify the work of departments. Making it a little safer. I am write design document for this, don't worry

## Technical details
I failed to make this printer as well as hyper convection machines. It turned out to be more accurate, but new recipes were not added to it

## Media
New technology.
Screenshot_855
New machine
Screenshot_856
The pajamas of the departments exclusive to this machine. The fact that this is a tier II technology of an unpopular discipline will save us from the fact that all departments will only wear pajamas.
Screenshot_858
[Lets get this party started
Lets keep them 40s poppin
So just get buzzed and stay f**ked up]

:cl:
- add: new Advanced uniform printer as tier II service and pajamas departments! You can print it on that new machine

### CODE REVIEW

**Comment by UbaserB** [comment]
some of the pjama sprites look weird

**Comment by Yeah-I-listening-Hollywood-undead** [comment]
> some of the pjama sprites look weird

I spent several hours drawing the same set of sprites, but in different colors. By the end, I wanted to open my veins. Maybe that's why I picked up the wrong colors somewhere. At the same time, it is possible to use chemical light for lighting, it was not a good idea

**Comment by Yeah-I-listening-Hollywood-undead** [comment]
It remains to wait for the boombox. Ask the administrators to download a tape from "HOLLYWOOD UNDEAD - RIOT" And start legendary party

**Comment by Kadeo64** [comment]
I like the concept but I don't think this really has any use, there's no situation where uniforms really need to be printed fast and the pyjamas are hardly a reason to research tier 2 civilian. I think that if science is going to research tier 2 civilian they should be able to print less conventional pieces of clothing. Radiation suits, Bio suits, Bomb suits, maybe even Armor vests? Of course, all these items would require a LOT of durathread.

**Comment by Yeah-I-listening-Hollywood-undead** [comment]
> I like the concept but I don't think this really has any use, there's no situation where uniforms really need to be printed fast and the pyjamas are hardly a reason to research tier 2 civilian. I think that if science is going to research tier 2 civilian they should be able to print less conventional pieces of clothing. Radiation suits, Bio suits, Bomb suits, maybe even Armor vests? Of course, all these items would require a LOT of durathread.

That printer not faster print. And yes. I add more helpful things after. I need discuss about it

**Comment by VektorZ1** [comment]
If he can print cloaks, it would be a beautiful thing.

**Comment by Yeah-I-listening-Hollywood-undead** [comment]
> If it could then print capes, it would be a beautiful thing.

maybe after this i add more things you want

**Comment by potato1234x** [comment]
we need to be able to print all clown clothes and possibly centcom and nt clothes

**Comment by MACMAN2003** [comment]
an emagged uniform printer can make centcom clothes

**Comment by potato1234x** [comment]
> an emagged uniform printer can make centcom clothes

oh shit fr?

**Comment by Yeah-I-listening-Hollywood-undead** [comment]
i also want add all D&D classes clothings in that uniform printer but later

**Comment by TheShuEd** [comment]
you also need to add new uniform printer recipes into advanced version from master branch

**Comment by metalgearsloth** [comment]
1. That copy-paste is unmergeable and needs fixing with parenting.
2. There's no reason for advanced uniform printer to exist currently anyway.

Pajama changes are fine but feel free to pull out the other changes in this PR or another PR when you get time.

**Pull request closed without merging**
