### PR TITLE
Adjust TEG efficiency curve, remove heat transfer limit

### PR DESCRIPTION
**Pull request by Partmedia**
## About the PR
The TEG used to limit hot-cold energy transfer based on actual power drawn, and had maximum efficiency at whatever temperature difference. This PR adjusts the hot-cold energy transfer to be uncapped, "venting" the excess heat that is not used to generate power, and adds an efficiency curve that limits efficiency at low thermal temperatures.

## Why / Balance
People have been cheesing the TEG by hooking up the hot end to the CO2 miner (which produces infinite, room-temperature gas) and the cold end to a space radiator.

With this change, you will actually need to set up a burn chamber in order to get appreciable power out of the TEG (see below).

If you build a gas holding chamber, you will have to throttle the gas flowing into the TEG instead of constantly cycling the gas through over and over again.

Blessed conceptually by @PJB3005 

## Technical details
TEG added efficiency as a function of temperature difference:
image

## Media
The CO2 trick no longer gives you appreciable power:

But setting up the burn chamber like you're supposed to still does:

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: notafet
- tweak: The TEG must now be operated at higher temperatures to generate power.

### CODE REVIEW

**Comment by deltanedas** [comment]
so if i have 1TJ of heat in the hot exchanger will  this essentially waste all the heat under normal loaf

**Review by PJB3005 — APPROVED** [review]
I'm just gonna trust I know your math

**Comment by ninruB** [comment]
>"venting" the excess heat that is not used to generate power

What if the TEG actually vented heat into the room :smug:

**Comment by Partmedia** [comment]
> so if i have 1TJ of heat in the hot exchanger will this essentially waste all the heat under normal loaf

Yep. If you don't want to waste all your heat, throttle down the gases going into the TEG in the first place, or just reduce the fuel flow into your burn chamber.

**Comment by WarMechanic** [comment]
this is good because i've done TEG throttling before but i didn't think that the heat transfer would be hard capped.

**Comment by Terraspark4941** [comment]
lilten's CO2 trick made me irrationally angry, thank you for returning justice to atmos

**Pull request merged**
