### PR TITLE
Add Cyborg screams and set emote pitch to 0.125

### PR DESCRIPTION
**Pull request by Keer-Sar**
## About the PR

Adds 4 screams to cyborgs. They're just edited versions of malescream_1.ogg thru malescream_4.ogg. 
Very crunchy, very cyborg-y! 
Sound files were edited by [@Kezu02](https://github.com/Kezu02)
## Why / Balance

Now cyborgs can scream just like EVERY other normally playable mob in the game.
Discussion here: https://discord.com/channels/310555209753690112/1228890407749025854

Variation was changed to 0.125 to match the other emote variations.
## Technical details

No code change, only .yml editing
## Media

https://github.com/space-wizards/space-station-14/assets/144283718/1284cc46-df24-4fa4-a6ff-2fe993a2731d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Cyborgs can now scream!

### CODE REVIEW

**Comment by UbaserB** [comment]
why does it sound like it's saying "raaauughhh" or "raaawwwrr", its weird. I would prefer it to sound a bit more flat.

**Comment by Golinth** [comment]
why not add the screams from TG? 
Also, these sound like the tubes you flip over that make the sound, if you know, you know

**Comment by Golinth** [comment]
> > why not add the screams from TG? Also, these sound like the tubes you flip over that make the sound, if you know, you know
> 
> I didnt know /tg/ had borg screams. Could you link them in the discord discussion?

Not tg, my bad. They're from goonstation. I see now you linked them in the discussion. They sound much more robotic and fitting for borgs IMO.

**Comment by K-Dynamic** [comment]
I kinda prefer a short version of those goonstation robot screams

**Comment by MilenVolf** [comment]
> I don't like any of these (neither the ones here nor any suggested in the discussion) for the simple reason that cyborgs don't have an inherent gender. Some cyborgs want to be male, some female, others genderless. So any sound used should accommodate that.
> 
> I think if cyborgs get a scream (and they should, it's funny) it needs to be something that perhaps isn't a voice at all but a synthetic sound like the talk sounds already are. I wonder if @MilenVolf has any ideas for a scream, they made some new sounds for #27205.
> 
> Or alternatively, just randomly play one of the male or female sounds in a way that make them sound like it's playing back poorly made recordings of people screaming (noisy, low bandwidth, etc). I came up with this stupid idea of them playing the sounds back from tape:
> recordedscream.webm
> 
> (don't mind that it's webm, GitHub doesn't support ogg for some reason)

I really like the idea of making it like a prerecorded audio tape, sounds really good.

**Comment by superjj18** [comment]
Try this sound filter with the moth screem, there's a chance it'll be way better than the human scream because it's more of a bleat which could be interpreted as a distressed beeping if the sound is modified right, which may be more inline with what a screaming Borg would sound like

(Also genderless, so solves that issue too)

**Comment by DandiIion** [comment]
Really dont like these screams. Prefer those goonstation ones.

**Pull request closed without merging**
