### PR TITLE
disable round start zombies

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

Admins can't form a clear consensus for how to fit round start zombies into current rules and very few people seem to like round start zombies when there's not significant admin intervention. Retains zombies through nukies and the midround event, which are still very janky but not an adminning issue.

https://discord.com/channels/310555209753690112/1129376295365652540/1129970341888921730

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Zombies have been removed as a round start game mode on secret.

### CODE REVIEW

**Comment by Slava0135** [comment]
first they take down survival and now they linched zombies
1984

**Comment by EmoGarbage404** [comment]
Is the greater issue round flow integration, or is it admins handling rules for them? It's very possible to automate something like CBURN to give the round a more natural flow.

If admins are having a hard time handling zombies, maybe it'd be possible to reinforce parts of it mechanically.

I wasn't really aware that any of these issues were present to the extent of warranting removal.

**Comment by EmoGarbage404** [comment]
also could this get a "discussion needed" tag, at least until the actual problems have been identified in a meaningful way so I can work on fixing them.

**Comment by Myakot** [comment]
I remember we had a discussion we had on Corvax Discord about it. One of the suggestions was:
- Remove the ability to turn whenever from patient-zero
- Force patient zero to turn upon a randomized timer running out: 5-30 minutes from roundstart
- Patient zero knows when they are nearing the turning point, so positions themselves accordingly
- Timer randomization is against meta gaming

Just a thought.

**Comment by metalgearsloth** [comment]
> Timer randomization is against meta gaming

What does this mean?

Also I was under timer-gaming was part of the problem, where people will deliberately sabotage their department beforehand if they know when they turn.

**Comment by EmoGarbage404** [comment]
Tfw i guess you don't need to actually justify a pr if you just self-merge it while ignoring potential discussion.

**Comment by deltanedas** [comment]
imo should just be extended with forced infection event at x + y mins in

**Comment by EmoGarbage404** [comment]
> I said I would and was writing out an explanation but if you want me to avoid discussion instead like you're saying I am I can

usually it's customary to give an actual justification before things before you make large changes. Especially if you're going to sight them as being "janky" with no further elaboration and something that "very few people seem to like." I'd be remiss to not point out that merging something because you want it and justifying it afterward seems self-serving.

**Comment by Just-a-Unity-Dev** [comment]
This is a fairly important thing and you shouldn't have self-merged this (it's not even your gamemode) especially without further discussion

**Comment by HoidC** [comment]
is very few people maintainers or is that very few people as in everyone, including players

**Pull request merged**
