### PR TITLE
Fix wire components in admin testing arena

### LINKED ISSUE #14304: Sending yourself to the admin testing arena instantly crashes the server
## Description
What the title says.

**Reproduction**
1. RMB your character > Tricks > Send object to Admin Testing Arena
2. Break space-time
3. Oops

**Additional context**
The crash log says something about an MV cable coil, I think. It's probably related to that.

### PR DESCRIPTION
**Pull request by h3half**
## About the PR
Closes #14304 

Without the rot component on the top-left MV wire (under the substation) the admin arena can load correctly. The substation still works afterwards (when I empty the battery of the APC it's connected to, the APC immediately starts charging so obviously the MV wire is still functioning), and the MV wire visually connects to its neighboring wire correctly.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by ElectroJr** [comment]
Was this actually crashing live servers or was this a no-rotation debug assert?

**Comment by h3half** [comment]
Looks like it doesn't crash on a Release build, only on Debug builds, with

`[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: NoRot entity has a non-zero local rotation. entity: MV power cable (12962, CableMV)`

I suppose I should remove the changelog entry then?

**Comment by moonheart08** [comment]
bors cancel

**Comment by ElectroJr** [comment]
> I suppose I should remove the changelog entry then?

I just removed it, but yes the description was inaccurate and given that the change has no noticeable affect outside of the debug assert it shouldn't have a change log at all. I'm also not sure if admin related changes should even be in the changelogs unless they affect players.

**Pull request merged**
