### PR TITLE
Add 5 hours of hop playtime requirement to captain

### PR DESCRIPTION
**Pull request by bhenrich**
## About the PR

Captain needs five hours of HoP playtime to unlock.

## Why / Balance

Captains sometimes do not know the basics of the HoP's duties, or how to use the ID card computer. This will prevent that. To be more specific, it's the captains duty to know the ins and outs of every department, and the HoP is an integral command role to the station.

## Technical details

Add five hours to the role playtime requirements for the role of Head of Personnel in the captain's prototype.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: YuNii
- tweak: Added five hours of HoP playtime to the Captain's unlock requirements.

### CODE REVIEW

**Comment by deltanedas** [comment]
it doesnt take 5 hours to figure out the id console, and every head has one so why hop specifically

**Comment by thebadman4662** [comment]
Not every and especially not on every map, but they should... 

That said its not rocket science you insert one ID and then another, no need to demote anyone to HoP for 5 hours to figure that one out, you can just tell the cap two simple steps.

**Comment by bhenrich** [comment]
It's not just the ID card computer, but about not knowing the HoP's duties in general. A Captain should be familiar with that, and I think that five hours is a fine amount of time.

**Comment by Rainbeon** [comment]
> it doesnt take 5 hours to figure out the id console, and every head has one so why hop specifically

Most heads do not have to interact with it ever and usually delegate it to HoP when they do, also knowing what HoP actually does seems fairly important for a Captain

**Comment by deltanedas** [comment]
> usually delegate it to HoP when they do

unless someone gives hop aa they cant promote randoms to your department its been like that for a while

**Comment by Eden077** [comment]
I feel like playing HoP for 3 to 4 rounds is pretty reasonable to play the most powerful job on station

**Comment by Rainbeon** [comment]
> > usually delegate it to HoP when they do
> 
> unless someone gives hop aa they cant promote randoms to your department its been like that for a while

Heads always just give you a stamped paper and tell you to talk to HoP, which they very much can do...?

**Comment by metalgearsloth** [comment]
If a person has 60 hours ingame and still doesn't know what a HoP does I fear for that person.

**Comment by deltanedas** [comment]
rather hop cant give head's accesses and armoury so hos promoting a warden has to know how to do that and youd expect cap to figure that out

**Comment by potato1234x** [comment]
it takes like one look at the id console to figure it out, not 5 hours, make it like 1 hour or something

**Comment by deepdarkdepths** [comment]
I've played cap over 15hrs and HOP for only 15min due to late joining. I have figured out the ID console perfectly fine at this rate and I'd rather not be locked behind a role I dont want to play when I already have knowledge of how things operate.

**Comment by potato1234x** [comment]
> I've played cap over 15hrs and HOP for only 15min due to late joining. I have figured out the ID console perfectly fine at this rate and I'd rather not be locked behind a role I dont want to play when I already have knowledge of how things operate.

this, ive played hop ONCE and its never come up

**Comment by thebadman4662** [comment]
I think only thing that might come up is that captain does not have access configurator but HoP does, but if you check their locker once then you pretty much know all you need to.

**Comment by nikthechampiongr** [comment]
> rather hop cant give head's accesses and armoury so hos promoting a warden has to know how to do that and youd expect cap to figure that out

You should start a github discussion on this. It has nothing to do with the pr.

**Comment by metalgearsloth** [comment]
Get some chadmins to rise up in support but I don't think HoP is particularly hard to figure out.

**Pull request closed without merging**
