### PR TITLE
Bring back tippy from april fools last year

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
Unironically good

I think the code is old and doesnt work and I'm not coder so I can't update it
(old demo)

https://private-user-images.githubusercontent.com/60421075/228731344-5ebb0da3-e911-44b8-aec2-ab5e6c241c36.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDMxOTcsIm5iZiI6MTcwODEwMjg5NywicGF0aCI6Ii82MDQyMTA3NS8yMjg3MzEzNDQtNWViYjBkYTMtZTkxMS00NGI4LWFlYzItYWI1ZTZjMjQxYzM2Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE3MDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNWU3NTQ1YmFmOTUzZTJmMjU0YWE5MTY5M2I4ZmE2MzdmMDdkMDJjY2ZmN2Y0MjdhZDI0NjU5NTBjNjI0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XhgHsgCVACVwipeMuWBGN6etb590hyJPh9sMVuiL824

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
He is real

**Comment by LordEclipse** [comment]
Return of the King

**Comment by VektorZ1** [comment]
too good

**Comment by FairlySadPanda** [comment]
This is unironically really great and should be in mainline

With different theming this would be really useful when I write a tutorial game to teach SS14 to newbies

**Comment by deltanedas** [comment]
tipothy

**Comment by Carmell0** [comment]
Imagine a way to make tippy answer questions.

(In game): hey CMO how do I label jugs?

Tippy: use hand labeler

**Comment by notquitehadouken** [comment]
clippy is in the public domain :trollface:

**Comment by CatMagic1** [comment]
i am going to merge this on goob station.
permanently.

**Comment by SlamBamActionman** [comment]
The code for the PR has been fixed to work with the game; it got closed due to a miscommunication between me and the PR author (100% my fault). I'll merge the fix to get Tippy up and running later today.

**Pull request closed without merging**
