### PR TITLE
Revert "Make events generally much more common"

### PR DESCRIPTION
**Pull request by Killerqu00**
This reverts commit f59a4f2a869ae0568727b62e1815262ee8fd82dd.

## Why / Balance

Survival is survival, other gamemodes are other gamemodes. Also, I feel that changes like these should be discussed instead of being self-merged in a span of 10-20 minutes.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Event frequency in gamemodes is back to normal.

### CODE REVIEW

**Comment by muburu** [comment]
did you even play the game while this was merged 
it's nowhere near survival in frequency and the event weights are different

**Comment by Killerqu00** [comment]
> did you even play the game while this was merged it's nowhere near survival in frequency and the event weights are different

I did. It is pretty close to survival.

**Comment by Killerqu00** [comment]
I mean, if this is going to stay, security is going to get even more unplayable. I would suggest to improve events directly instead of making their frequency so high.

**Comment by Hanzdegloker** [comment]
The frequency increase was way too severe, it shouldn't be lowered to pre PR levels, perhaps something in between but yeah I think its too high at the moment.

**Comment by Killerqu00** [comment]
> The frequency increase was way too severe, it shouldn't be lowered to pre PR levels, perhaps something in between but yeah I think its too high at the moment.

The problem is not the frequency, it's the quality. If events "feel non impactful", then making them more frequent won't help.

**Comment by EdenTheLiznerd** [comment]
Alright so from a security and observer standpoint, this is going to be your average round so this has not only made it so security is going to be spread paper thin but also engineering, this practically cripples the departments, maybe if we had less station damaging events that'd be good but yeah no I agree, this needed far more discussion before being self-merged for fun, remember to keep your conversations civil.

**Comment by Killerqu00** [comment]
> Alright so from a security and observer standpoint, this is going to be your average round so this has not only made it so security is going to be spread paper thin but also engineering, this practically cripples the departments, maybe if we had less station damaging events that'd be good but yeah no I agree, this needed far more discussion before being self-merged for fun, remember to keep your conversations civil.

Yeah, no hate towards the merger, I just think that this is not something that should be passed without review.

**Comment by EdenTheLiznerd** [comment]
No no, I agree, just saying for other people around to keep their opinion civil and concise

**Comment by Killerqu00** [comment]
> do you have a replay of a round after this change where it actually felt like anything close to survival

I think the rounds were 52399 and 52404. You can also compare that to 52409, which was I think an actual survival round. All Salamander.

**Comment by mirrorcult** [comment]
for the record
- this change is identical to tg's event frequency, where anecdotally events aren't that overbearing but do feel like they're relevant to the round
- i created survival and also am the one who picked the old frequency
- changing this has been something I've wanted to experiment with for a while now and discussed with other maints beforehand.

 what exactly is a more methodical review of a one line balance PR supposed to look like other than "I think this change will be good" or "I think this change will be bad". at some point you just have to send it and see how it pans out

**Comment by mirrorcult** [comment]
if this is modified as a result of it being too overwhelming compared to TG it absolutely should not just be knee jerk reverted to the levels before which were absolutely ass

**Comment by Killerqu00** [comment]
> if this is modified as a result of it being too overwhelming compared to TG it absolutely should not just be knee jerk reverted to the levels before which were absolutely ass

I agree that events feel underwhelming usually, but simply increasing their frequency leads to more problems instead of solving the root. The better way (imho) is to change the events themselves. 

I think I will close it for now and instead change the frequencies to something in the middle, maybe even changing some things with current existing events.

**Comment by thebadman4662** [comment]
I like more small event so far a lot, not every event needs to be nukie ops and few in a row can put some tension on the crew.

**Pull request closed without merging**
