### PR TITLE
added the pride cloaks to maint spawns

### PR DESCRIPTION
**Pull request by 2013HORSEMEATSCANDAL**
## About the PR

I added the pride cloaks to maints spawn.
## Why / Balance

The trans one was already there, so I added the others.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: 2013HORSEMEATSCANDAL added:
- add: Some new cloaks can be found in maints.

### CODE REVIEW

**Comment by GreyMario** [comment]
i wonder how big the maints loot spawnpool is compared to the average maints loot spawn points now

**Comment by 2013HORSEMEATSCANDAL** [comment]
> i wonder how big the maints loot spawnpool is compared to the average maints loot spawn points now

**Comment by 2013HORSEMEATSCANDAL** [comment]
wrong button lmao

**Comment by 2013HORSEMEATSCANDAL** [comment]
idk im not a mapper, I just wanted a way for these to actually be obtainable

**Comment by Emisse** [comment]
i didnt know these existed so fair enough

**Pull request merged**
