### PR TITLE
magboots autogen state

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
yes

doesnt fix the clothing action networking bug but its not magboot specific so

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Menshin** [comment]
Was going to PR misc fixes for magboots, that can incorporate if you feel like it (if not, i'll PR them once your changes are in) :

* there's an autocomplete typo at :https://github.com/space-wizards/space-station-14/blob/26df4cbf9ec8c0ee97533e97e4528c56735554a1/Content.Shared/Clothing/SharedMagbootsSystem.cs#L50
        ```_appearance.SetData(uid, ToggleVisuals.Toggled, component.On);```

which prevent the sprite from updating when toggled on.

* the toggle verb doesn't nothing, because it should do half the instructions in `OnToggleAction()` instead of just changing the component `On` field.

**Comment by deltanedas** [comment]
yeah if youre gonna do more work on boots just include it in your future pr

**Comment by Menshin** [comment]
Just to be clear, by no means did i suggest to close your PR...

I'll nonetheless gladly incorporate your changes along the current fixes.

**Comment by deltanedas** [comment]
i know but its easier to sneak this inside a bigger pr than deal with 2 similar ones

**Pull request closed without merging**
