### PR TITLE
modern hair revert

### PR DESCRIPTION
**Pull request by Emisse**
## About the PR
abusing my power to change the hair i use back to normal

## Why / Balance
i dont like new hair i like old hair

### CODE REVIEW

**Comment by Kesiath** [comment]
why not have both? 😄

**Comment by nopeingeneer** [comment]
So you screw up ALL spriters work and just revert hair style? 

Go touch some maps

**Comment by metalgearsloth** [comment]
> So you screw up ALL spriters work and just revert hair style?
> 
> Go touch some maps

be civil or don't say anything at all.

**Comment by PixelTheKermit** [comment]
This is going to look out of place when compared to the other hairs.

**Comment by Emisse** [comment]
its really not going to look that out of place and the hair definitely got the short end of the stick in the resprites, it was completely different shape/styling/everything

**Comment by UbaserB** [comment]
We should keep it, it looks great, fits with the style and it’s something that was put a lot of effort into

**Comment by OctoRocket** [comment]
If you revert this hair, what stops everyone else from reverting their preferred hairs?

**Comment by UbaserB** [comment]
This would flood the hair list even more than it is already, maybe there could be a button for switching between old/new hairs?

**Comment by mirrorcult** [comment]
current solution after maintainer discussion is we're just going to readd a select few of the old hairstyles that were changed significantly but not the rest

**Comment by Emisse** [comment]
yea ill do that sometime

**Comment by UbaserB** [comment]
ok

**Comment by Emisse** [comment]
closing for classic hairs pr

**Pull request closed without merging**
