### PR TITLE
Adding an AccessReader to a particle accelerator with engineering access

### PR DESCRIPTION
**Pull request by chavonadelal**
## About the PR

Adding an AccessReader to a particle accelerator with engineering access.
## Why / Balance

Over the years, there have been many cases when scammers ran into the open door of the engineering department and interacted with the particle accelerator. Or some guest of the service suddenly decides to play with a particle accelerator. Such a dangerous thing should not be without access. I also plan to add access to the antimatter engine in the near future.
It can be hacked using EMAG
## Media

View of the menu on behalf of the player without access:
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: to4no_fix
- tweak: Now engineering access is needed to interact with the particle accelerator

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
if you hover over the disabled buttons will it tell you that you are unable to interact with it because you lack access?

**Comment by chavonadelal** [comment]
> Will hovering over the disabled buttons provide a message indicating that interaction is not possible due to insufficient access?
> 
> Alternatively, is there any feedback available to explain to the user why they cannot interact with the Particle Accelerator?

No. Same as the criminal records console, the communications console, and all consoles with access. That's the practice.

**Comment by chavonadelal** [comment]
> Will hovering over the disabled buttons provide a message indicating that interaction is not possible due to insufficient access?
> 
> Is there any feedback available to explain to the user why they cannot interact with the Particle Accelerator?

I understand what you mean, but this option is not implemented for the buttons, and my level of knowledge is too low, and I don’t think this is a problem, since this is already practice and this is in all consoles.

**Comment by osjarw** [comment]
This fix seems to be entirely client-side currently, so outdated clients and malicious actors can still turn on the PA.
Well, I'm not sure how prevalent that is, but it should at least be kept in mind.

**Comment by Cojoke-dot** [comment]
Uh... if it's getting AccessReader it probably needs an access wire right?

**Comment by chavonadelal** [comment]
> if it's getting AccessReader it probably needs an access wire right?

And the criminal records console needs an access cable? And the communication console? And the cargo order console? Well, you get the idea... I just did it like all the consoles do now

**Comment by chavonadelal** [comment]
in all consoles it happens exactly as I implemented in particle accelerators, that's all

**Comment by Cojoke-dot** [comment]
Sure, but the particle accelerator already has wires built into it, which kinda implies that one of them would function for access like every other item that has a wire panel and access locks. It uh... a unique situation I guess, It's the only computer that can has a wire access panel right?

**Comment by chavonadelal** [comment]
> Sure, but the particle accelerator already has wires built into it, which kinda implies that one of them would function for access like every other item that has a wire panel and access locks. It uh... a unique situation I guess, It's the only computer that can has a wire access panel right?

I don't think it's a good idea. Remember the raiders. It would make their lives harder and adding wires would just kill the whole point. Especially since there are almost no real cases where antagonists could use a particle accelerator within the rules - it's an unusual console, it's a very dangerous thing.

**Comment by Cojoke-dot** [comment]
> I don't think it's a good idea. Remember the raiders. It would make their lives harder and adding wires would just kill the whole point.

Is one access level you can get by taking an id from an SSD engineer going to stop anyone? A raider would have already gotten engi access to walk into that room. 

> Especially since there are almost no real cases where antagonists could use a particle accelerator within the rules 

If you're an antag same kinda of situation... unless it's CE access or something higher up it's not going to stop people from doing anything if it's planned. I can see it stopping the niche situations of the sci that came to help out fix power who is a syndicate turning it on while the field is not up, but it's not going to stop someone from just doing it anyway. 

> This is the most inappropriate console for adding wires, especially as an exception.

It already has a wire that you can cut in order to loose the singularity, it would be more for consistency with other wire-paneled machines.

 If it's based on the other consoles then an emag interaction to disable the access lock on the computer should be a part of it. I uh... I like consistency 🙃

**Comment by chavonadelal** [comment]
> > I don't think it's a good idea. Remember the raiders. It would make their lives harder and adding wires would just kill the whole point.
> 
> Is one access level you can get by taking an id from an SSD engineer going to stop anyone? A raider would have already gotten engi access to walk into that room. 
> 
> > Especially since there are almost no real cases where antagonists could use a particle accelerator within the rules 
> 
> If you're an antag same kinda of situation... unless it's CE access or something higher up it's not going to stop people from doing anything if it's planned. I can see it stopping the niche situations of the sci that came to help out fix power who is a syndicate turning it on while the field is not up, but it's not going to stop someone from just doing it anyway. 
> 
> > This is the most inappropriate console for adding wires, especially as an exception.
> 
> It already has a wire that you can cut in order to loose the singularity, it would be more for consistency with other wire-paneled machines.
> 
>  If it's based on the other consoles then an emag interaction to disable the access lock on the computer should be a part of it. I uh... I like consistency 🙃

what? why did someone add wires? Someone makes the raiders' lives easier. Because the antagonist can almost never use it within the rules

**Comment by chavonadelal** [comment]
The raiders a violation of the conditions of the singularity's containment (its escape) in the top 2 after the explosion of the fuel tank

**Comment by Cojoke-dot** [comment]
> what? why did someone add wires? Someone makes the raiders' lives easier. Because the antagonist can almost never use it within the rules

Its uh... always been like that I think(as long as I've played at least). You can set the PA to 4 by snipping one of the wires so it gets big enough to eat out of the cage(it also makes the PA shoot cool purple). Some of the wires also lock functions of the console, like preventing the PA from being turned on or locking the power level iirc. I've seen people use the wires functions to prevent and cause the singularity to loose.

**Comment by chavonadelal** [comment]
> > what? why did someone add wires? Someone makes the raiders' lives easier. Because the antagonist can almost never use it within the rules
> 
> Its uh... always been like that I think(as long as I've played at least). You can set the PA to 4 by snipping one of the wires so it gets big enough to eat out of the cage(it also makes the PA shoot cool purple). Some of the wires also lock functions of the console, like preventing the PA from being turned on or locking the power level iirc. I've seen people use the wires functions to prevent and cause the singularity to loose.

This suicidal feature actually sponsors raiders to ruin the game of the entire station. That's why I want at least access to be unchanged among this.

**Comment by osjarw** [comment]
Are you saying that we should just remove singulooses?
If they can snip the access wire, they should be also able to sabotage the PA in other ways, like cutting the cable powering the containment fields.

**Comment by chavonadelal** [comment]
> Are you saying that we should just remove singulooses?
> If they can snip the access wire, they should be also able to sabotage the PA in other ways, like cutting the cable powering the containment fields.

Why sabotage the singularity? Within the rules, this almost never happens and my addition is to complicate the lives of raiders and random players not from the engineering department who for some reason decided to use this console. In fact, sabotaging the singularity goes beyond the scope of rp and in 95% of cases it is a violation of the rules with the goal of ruining the game for everyone.

**Comment by Cojoke-dot** [comment]
> Why sabotage the singularity? Within the rules, this almost never happens and my addition is to complicate the lives of raiders and random players not from the engineering department who for some reason decided to use this console. In fact, sabotaging the singularity goes beyond the scope of rp and in 95% of cases it is a violation of the rules with the goal of ruining the game for everyone.

Nukies use it as a tactic, not all antags are limited by the same rules(free agents)

**Comment by BombasterDS** [comment]
I think this is good change. Like, why do even need to work with PA if you're not even an engineer? In case, you need to set up power and you're, you'll have engineer access to set up containment field anyway, so that's won't affect them.

Actually, i think that better solution is adding new access (like Engine Room in SS13) that will be responsible for PA, PA room and containment field room and remove this access from TA (most TA are real newbies. If you know how to setup singularity, ask HoP, captain, CE for accesses or just hack into their room. If it's super lowpop, the map probably won't contain any PA).

**Comment by chavonadelal** [comment]
In my opinion, ideally, any sabotage of the singularity should be excluded. As a former admin with more than a year of experience, I can say that out of 100 sabotages of the singularity, a maximum of 5 are within the rules. The rest are raiders.

**Comment by BombasterDS** [comment]
> In my opinion, ideally, any sabotage of the singularity should be excluded. As a former admin with more than a year of experience, I can say that out of 100 sabotages of the singularity, a maximum of 5 are within the rules. The rest are raiders.

Singularity sabotage would be a good option if station had better methods for dealing with singuloose and teslaloose. Like, we have particle decelerators that costs 15000 and barely damage singularity (not damaging tesla at all). Now, singuloose or teslaloose means end of the shift.

**Comment by osjarw** [comment]
> > Sure, but the particle accelerator already has wires built into it, which kinda implies that one of them would function for access like every other item that has a wire panel and access locks. 
> 
> I don't think it's a good idea. Remember the raiders. It would make their lives harder and adding wires would just kill the whole point. 

If adding wires would kill the point of adding access, wouldn't the raiders need tools to cut the wires in order to kill the point of the access? 
If the reason for not adding an access wire is because the raiders can just cut it, then they should also have the capability of cutting a power cable to the containment fields.

**Comment by chavonadelal** [comment]
> > Why sabotage the singularity? Within the rules, this almost never happens and my addition is to complicate the lives of raiders and random players not from the engineering department who for some reason decided to use this console. In fact, sabotaging the singularity goes beyond the scope of rp and in 95% of cases it is a violation of the rules with the goal of ruining the game for everyone.
> 
> Nukies use it as a tactic, not all antags are limited by the same rules(free agents). I want the change, don't get me wrong, I just also want a wire

On 90 percent of Space Station 14 servers, nuclear operatives have been prohibited from manipulating the particle accelerator for many years, which is logical since it causes unnecessary chaos. And on my server, this was also prohibited. That's why I write that in 5 out of 100 cases, this can at least be explained somehow within the framework of the rp.

**Comment by BombasterDS** [comment]
> > > Sure, but the particle accelerator already has wires built into it, which kinda implies that one of them would function for access like every other item that has a wire panel and access locks.
> > 
> > 
> > I don't think it's a good idea. Remember the raiders. It would make their lives harder and adding wires would just kill the whole point.
> 
> If adding wires would kill the point of adding access, wouldn't the raiders need tools to cut the wires in order to kill the point of the access? If the reason for not adding an access wire is because the raiders can just cut it, then they should also have the capability of cutting a power cable to the containment fields.

Consoles don't have wires at all. Why PA need single wire?

**Comment by chavonadelal** [comment]
> > > Sure, but the particle accelerator already has wires built into it, which kinda implies that one of them would function for access like every other item that has a wire panel and access locks. 
> > 
> > I don't think it's a good idea. Remember the raiders. It would make their lives harder and adding wires would just kill the whole point. 
> 
> If adding wires would kill the point of adding access, wouldn't the raiders need tools to cut the wires in order to kill the point of the access? 
> If the reason for not adding an access wire is because the raiders can just cut it, then they should also have the capability of cutting a power cable to the containment fields.

it's still not that simple since all the fields are almost always inside the cells of the walls. Especially since sometimes they collect a particle accelerator specially outside the field so that the singularity definitely hits the station and does not fly off into space, thus ruining everyone's game.

**Comment by chavonadelal** [comment]
> I think this is good change. Like, why do even need to work with PA if you're not even an engineer? In case, you need to set up power and you're, you'll have engineer access to set up containment field anyway, so that's won't affect them.
> 
> Actually, i think that better solution is adding new access (like Engine Room in SS13) that will be responsible for PA, PA room and containment field room and remove this access from TA (most TA are real newbies. If you know how to setup singularity, ask HoP, captain, CE for accesses or just hack into their room. If it's super lowpop, the map probably won't contain any PA).

oh well by the way yes adding separate access for singularity would be a good idea!! So that technical assistants are not assembled without supervision of engineers. And redefine access on other things related to singularity. But I will not do this because I need someone's approval otherwise the work may be in vain.

**Comment by osjarw** [comment]
> Consoles don't have wires at all. Why PA need single wire?

I'm fairly certain that PA already has a few wires

> barely damage singularity (not damaging tesla at all).

Actually it does damage the tesla

And just saying this explicitly, I'm not against merging this PR

**Comment by SlamBamActionman** [comment]
1) We do not design gameplay elements with raiders in mind. Raiders will always find ways to ruin the game and while you definitely should not just put the PA and Singularity into an open access hallway, requiring Engineering access to the console won't hinder raiders in the slightest.

If they can get into the PA room they already have engineering access, either from stealing an ID or, ya know, just picking TA.

2) The PA is already access controlled from being in the depths of Engineering. If you can get to it, you have demonstrated having Engineering access. Adding an additional access requirement is unnecessary.

If service workers are breaking into Engineering to amp the PA, beat them to death.

**Comment by chavonadelal** [comment]
> 1) We do not design gameplay elements with raiders in mind. Raiders will always find ways to ruin the game and while you definitely should not just put the PA and Singularity into an open access hallway, requiring Engineering access to the console won't hinder raiders in the slightest.
>   
>     If they can get into the PA room they already have engineering access, either from stealing an ID or, ya know, just picking TA.
> 
> 2) The PA is already access controlled from being in the depths of Engineering. If you can get to it, you have demonstrated having Engineering access. Adding an additional access requirement is unnecessary.
>   
>     If service workers are breaking into Engineering to amp the PA, beat them to death.

Okay, why do the other consoles have access? Criminal records? Communication console? I have already implemented access, so why not just implement it by merging it.

**Comment by chavonadelal** [comment]
> > 1) We do not design gameplay elements with raiders in mind. Raiders will always find ways to ruin the game and while you definitely should not just put the PA and Singularity into an open access hallway, requiring Engineering access to the console won't hinder raiders in the slightest.
> >   
> >     If they can get into the PA room they already have engineering access, either from stealing an ID or, ya know, just picking TA.
> > 
> > 2) The PA is already access controlled from being in the depths of Engineering. If you can get to it, you have demonstrated having Engineering access. Adding an additional access requirement is unnecessary.
> >   
> >     If service workers are breaking into Engineering to amp the PA, beat them to death.
> 
> Okay, why do the other consoles have access? Criminal records? Communication console? They are also behind the doors! I have already implemented access, so why not just implement it by merging it.

**Comment by chavonadelal** [comment]
> > 1) We do not design gameplay elements with raiders in mind. Raiders will always find ways to ruin the game and while you definitely should not just put the PA and Singularity into an open access hallway, requiring Engineering access to the console won't hinder raiders in the slightest.
> >   
> >     If they can get into the PA room they already have engineering access, either from stealing an ID or, ya know, just picking TA.
> > 
> > 2) The PA is already access controlled from being in the depths of Engineering. If you can get to it, you have demonstrated having Engineering access. Adding an additional access requirement is unnecessary.
> >   
> >     If service workers are breaking into Engineering to amp the PA, beat them to death.
> 
> Okay, why do the other consoles have access? Criminal records? Communication console? They are also behind the doors! I have already implemented access, so why not just implement it by merging it. This feature won't hurt anyone.

**Comment by chavonadelal** [comment]
> > Consoles don't have wires at all. Why PA need single wire?
> 
> I'm fairly certain that PA already has a few wires
> 
> > barely damage singularity (not damaging tesla at all).
> 
> Actually it does damage the tesla
> 
> And just saying this explicitly, I'm not against merging this PR

With the same argument, you can remove access to the specified consoles. Well, if they break in, just kill them. I don't quite see the argumentation in your position.

**Comment by osjarw** [comment]
> With the same argument, you can remove access to the specified consoles. Well, if they break in, just kill them. I don't quite see the argumentation in your position.

To be honest, the idea of removing access from the criminal records and making fake records sounds like a good feature.
And my point was that if you already can bypass the engie access by cutting the wires, surely you must other ways to singuloose.

**Comment by chavonadelal** [comment]
> > With the same argument, you can remove access to the specified consoles. Well, if they break in, just kill them. I don't quite see the argumentation in your position.
> 
> To be honest, the idea of removing access from the criminal records and making fake records sounds like a good feature.
> And my point was that if you already can bypass the engie access by cutting the wires, surely you must other ways to singuloose.

This devalues access too much. There should be a limit to everything and something should not work without access.

**Comment by osjarw** [comment]
Just to make my position clear, I'm not against adding this PR nor adding access to the PA console. 
I think that I'll drop out of this conversation here...

**Comment by chavonadelal** [comment]
> Just to make my position clear, I'm not against adding this PR nor adding access to the PA console. 
> I think that I'll drop out of this conversation here...

I apologize if I offended you, I was just surprised that someone considered adding such a logical and simple function unnecessary.

**Comment by osjarw** [comment]
> I apologize if I offended you, I was just surprised that someone considered adding such a logical and simple function unnecessary.

No need for apologies, I'm not really offended.
And it isn't an unnecessary feature, I just believe that you should be able to bypass almost anything with appropriate amount of effort. 
There probably was some miscommunication between us.

**Comment by BombasterDS** [comment]
> > Consoles don't have wires at all. Why PA need single wire?
> 
> I'm fairly certain that PA already has a few wires
> 
> > barely damage singularity (not damaging tesla at all).
> 
> Actually it does damage the tesla
> 
> And just saying this explicitly, I'm not against merging this PR

PD damages tesla, but it regenerates it's energy much faster. So, practically it won't affect tesla anyway. I think that it would be much cooler if you'll be able to stop tesla from moving with some device and then build containment field around it, but this is just idea unrelated to this PR

**Comment by BombasterDS** [comment]
> 1. We do not design gameplay elements with raiders in mind.

Uh, why? As i heard, good game design should take into account that people find the way to spoil the game of other players.

> The PA is already access controlled from being in the depths of Engineering

If consider box map - raider can pick up insulated gloves and multitool in tech room, open four doors to PA, bring tesla generator to it and activate PA. Yea, engineers can stop him, but what if they don't want to kill someone just because they think is would be bad idea?

**Comment by chavonadelal** [comment]
> > 1. We do not design gameplay elements with raiders in mind.
> 
> Uh, why? As i heard, good game design should take into account that people find the way to spoil the game of other players.
> 
> > The PA is already access controlled from being in the depths of Engineering
> 
> If consider box map - raider can pick up insulated gloves and multitool in tech room, open four doors to PA, bring tesla generator to it and activate PA. Yea, engineers can stop him, but what if they don't want to kill someone just because they think is would be bad idea? 
> 
> It would make an extra barrier for raiders without affecting other players negatively, so I don't see anything wrong with that

I support. Perhaps, as you said, it is worth adding a separate access for the particle accelerator. Doors with new access and redefine the access of emitters and other things to this new access to protect against inexperienced technical assistants.

**Comment by SlamBamActionman** [comment]
> With the same argument, you can remove access to the specified consoles. 

I mean, yeah, let's.

The Criminal Records console is sometimes mapped in Sec outposts and is thus far too easy to access, but personally I think the Announcements console could work without access restrictions. I think an argument could be made that the effects of those consoles are too immediate as opposed to the PA, which can be turned off in time, but it's whatever.

**Comment by chavonadelal** [comment]
> > With the same argument, you can remove access to the specified consoles. 
> 
> I mean, yeah, let's.
> 
> The Criminal Records console is sometimes mapped in Sec outposts and is thus far too easy to access, but personally I think the Announcements console could work without access restrictions. I think an argument could be made that the effects of those consoles are too immediate as opposed to the PA, which can be turned off in time, but it's whatever.

In my opinion, your ideas are involution, no offense.

**Comment by NotSoDana** [comment]
useeeleeeeeess

**Comment by Jezithyr** [comment]
This is a pretty good change tbh. Not only does it raise the bar for greifing but it also makes antags need to work for sabotaging the accelerator, it's no longer a free lunch, they need to hack/steal access.

**Comment by NotSoDana** [comment]
ok, time to full opinion.
Very unbalanced for antags, cuz of more work to sabotage the accelerator. If you can't hack it, or use EMAG - u need to steal access, but more times this is difficult and don't make any sense to the goals. Moreover, the PA computer isn't like typical consoles. Consoles in 90% times don't used by antags, its just useless bruh. But PA computer have different construction, and adding an Access Reader to it, looks very.. strange, nah? Anyway, i think it's don't need it, or should be added with a EMAG/Hack opportunity.

**Comment by Jezithyr** [comment]
> Very unbalanced for antags, cuz of more work to sabotage the accelerator. If you can't hack it, or use EMAG - u need to steal access, but more times this is difficult and don't make any sense to the goals. 

I would argue this makes it far more balanced for antagonists, *now they actually need to put in the work* to trigger a round ending event and not just sneak into engineering and set the funni machine to max and watch the fireworks. I agree that it should definitely be emagable though since that encourages preplanning from antagonists.

**Comment by NotSoDana** [comment]
> I would argue this makes it far more balanced for antagonists, _now they actually need to put in the work_ to trigger a round ending event and not just sneak into engineering and set the funni machine to max and watch the fireworks. I agree that it should definitely be emagable though since that encourages preplanning from antagonists.

_Objection!_ If antag sneaked into the engi and don't get caught by engineers or CE, it's actually not bad work. If they let antag in the PA room, it's only their fault. Moreover, singularity (if there is it) not 100% will _eat_ the station, then syndie needs to place singulo-beacon, which is difficult to hide on big maps, not to mention launching it on time. Without EMAGging or hack (cuz of PA computer has wires out of it lmao) this PR looks incomplete.

**Comment by chavonadelal** [comment]
Access Reader provides the ability to hack using EMAG at the system level

**Comment by Jezithyr** [comment]
> _Objection!_ 
Objection Overruled! (sorry I had to make that joke)

> If antag sneaked into the engi and don't get caught by engineers or CE, it's actually not bad work.

If an antag sneaks into engie after this change gets merged, they'll still be able to sabotage the PA. The only difference is that joke greytider sneaking in won't be able to do the same thing, which is a *considerable improvement*

**Comment by chavonadelal** [comment]
it can be hacked using EMAG

**Comment by SlamBamActionman** [comment]
> In my opinion, your ideas are involution, no offense. Cutting out features.

 
> involution
> noun
> 1.
> PHYSIOLOGY
> the shrinkage of an organ in old age or when inactive, e.g. of the uterus after childbirth.

Ok thanks, my arguments are still up there to be responded to. :)

**Comment by Jezithyr** [comment]
> 1. We do not design gameplay elements with raiders in mind. 

Actually we do. Designing mechanics to not be easily abused by bad-actors is multiplayer game design 101. Unfortunately in a lot of cases this is something that wasn't thought about when some features were originally designed in SS13 and when those mechanics were ported preventing abuse was generally not thought about.

**Comment by NotSoDana** [comment]
> Objection Overruled! (sorry I had to make that joke)

I objection your overrule! 

> The only difference is that joke greytider sneaking in won't be able to do the same thing, which is a _considerable improvement_

Nah, cuz there is a lot of ways to sneak in the engi without **engineering** access: Hack, Emag, Explosion, Deconstruct walls, Jaws of Life, SSD Tech asssistant access. IF GREYTIDER NEEDS - HE WILL SABOTAGES SINGULO, U JUST UNDERRATE HIM.

**Comment by SlamBamActionman** [comment]
> > If antag sneaked into the engi and don't get caught by engineers or CE, it's actually not bad work.
> 
> If an antag sneaks into engie after this change gets merged, they'll still be able to sabotage the PA. The only difference is that joke greytider sneaking in won't be able to do the same thing, which is a _considerable improvement_

A joke greytider is not really any more limited than an actual antag; if you're a person intent on going so far as self-antag singuloosing you won't be stopped by requiring an ID for access (and if you've gotten all the way into the PA room, you've likely gotten that access anyways). The only difference is having access to an EMAG.

**Comment by SlamBamActionman** [comment]
> > 1. We do not design gameplay elements with raiders in mind.
> 
> Actually we do. Designing mechanics to not be easily abused by bad-actors is multiplayer game design 101. Unfortunately in a lot of cases this is something that wasn't thought about when some features were originally designed in SS13 and when those mechanics were then ported to ss14 the focus was on reaching feature parity not making design changes.

My b, I should've added "primarily",as new game features need to be evaluated in the context of fair play as well, and not just in the context of raiders.

**Comment by Jezithyr** [comment]
This change is primarily a "fair play" change and the "nerf" to antags is extremely minimal and in my opinion *actually healthy for the game.* Most of this change is targeted towards raiders to reduce admin workload and improve round quality, but it still has a positive effect on gameplay.

> A joke greytider is not really any more limited than an actual antag; if you're a person intent on going so far as self-antag singuloosing you won't be stopped by requiring an ID for access

I think you are severely overestimating the competence of most raiders, I've watched a raider in RMC-14 miss every single one of their shots when trying to teamkill marines because they didn't wield their gun. Or another raider picking up a gun with a smartscope (Which has an IFF that prevents friendly fire), and trying to teamkill with it. 

Quite simply, the raiders are not sending their best... Is it possible for a competent greifer to bypass the id check? Yeah definitely, but for every competent raider there are 10 incompetent ones that will end up getting stopped by this change. 

In addition to making griefing more difficult, this also adds an extremely minor barrier for antags to overcome if they want to singuloose. Effectively, singuloosing now requires just a tiny bit of pre-planning rather than being a foolproof method that you can fallback on if your attempts to bomb the station failed. This encourages antags to think ahead about what they are going to do instead of falling back on "foolproof" strategies. 

Additionally, the *vast* majority of singulooses are done by raiders not antags. And even then, singuloosing is generally a last resort "panic" move by antags when they don't have other options. I can count on one hand the number of times I've heard of or seen someone actually plan on singuloosing as an antag from the start.

**Comment by PJB3005** [comment]
Automatic access reader checks like this are **really bad**. I would much prefer the more common (in SS13) pattern of access-locked devices requiring an ID card swipe, as it enables leaving the console unlocked (whether intentional or unintentional).

> No. Same as the criminal records console, the communications console, and all consoles with access. That's the practice.

And it's a horrible, atrocious UI design practice that should never have been added to any UI in the first place.

> 1. If they can get into the PA room they already have engineering access, either from stealing an ID or, ya know, just picking TA.

Hacking doors exists

**Comment by chavonadelal** [comment]
> Hacking doors exists

I understand, but that's the practice and I don't have the skills to twist anything. This system works with all the things in the game. Cabinets, consoles, and so on and so on. Therefore, I do not think that this is the problem of my pull request.

**Pull request merged**
