### PR TITLE
Buff emergency toolbox fill

### LINKED ISSUE #23059: Feature Request: buff emergency toolbox contents
## Description
Emergency toolboxes contain a crowbar, two flashlights (sometimes one), two breath masks, and two chocolate. With the addition of water bottles to survival boxes and emergency nitrogen tanks, I think emergency toolboxes should be updated to include said water bottles and emergency tanks. Would make these just a little bit more useful. It feels weird they don't have oxygen tanks when they have two breath masks, and since water bottles are now commonplace it would be a good idea to put them in a place where emergency food is stored as well.

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Resolves #23059. I couldn't figure out how to use orGroup so i kind of gave up there but it still works fine.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

image

### CODE REVIEW

**Comment by lapatison** [comment]
Could you add EmergencyNitrogenTanks as well?

**Comment by UbaserB** [comment]
sure 👍🏻

**Comment by Kadeo64** [comment]
Finally, the emergency toolbox is actually useful during emergencies and not just a free crowbar. In a pinch that water and food will come in handy.

**Comment by UbaserB** [comment]
ok there are nitrogen tanks now, too lazy to update photo 👍🏻

**Comment by metalgearsloth** [comment]
Why is there a bunch of prob spawns on the entities?

**Comment by UbaserB** [comment]
> Why is there a bunch of prob spawns on the entities?

so that theres 1 of a type item and then a chance for a second one.

**Comment by Carmell0** [comment]
Can you make MREs spawn in emergency lockers with this change? (Also make it have a 0.00001% chance to have the Throngler because funi)

**Comment by Kadeo64** [comment]
> Can you make MREs spawn in emergency lockers with this change? (Also make it have a 0.00001% chance to have the Throngler because funi)

MREs spawn in emergency lockers already (as a random chance like the toolbox or flare gun)

**Review by Partmedia — APPROVED** [review]

**Comment by Partmedia** [comment]
Thanks for your contribution. Sorry about the delay getting this in.

**Pull request merged**
