### PR TITLE
ninjas can call lone ops

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

the ninja, when hacking a communications console, has a 1/3 chance of spawning a lone op
## Why / Balance

There is no real middle ground between the antags the ninja can call in, going from 0 (revenant) to 100 (dragon) real fast, a lone op would be like a 75 on the scale, dangerous, but alone. will also provide variety and chaos, which is always fun

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: JoeHammad
- add: Space ninjas have acquired loose ties to the syndicate and may call lone nuclear operators when hacking communication consoles

### CODE REVIEW

**Comment by NancokPS2** [comment]
I think a lone op is potentially more dangerous.  
A space dragon is beefy, but 1 or 2 mags are enough to bring it down and it has a really hard time hiding.  
  
A nukie can not only hide/blend in, but they also have powerful guns at their disposals which are way more dangerous than a dragon.  
  
At least a dragon would take damage from encounters with random crew since they would get hit in return, a good nukie can just gun down an enemy and that's that.

**Comment by deltanedas** [comment]
i think it could be ok if it was changed from a list to weighted random, then weigh loneop down so its rarer (ss13 balancing mechanism)

**Comment by Hmeister-fake** [comment]
it seems way too powerful to be able to summon a robust(?) 40 tc loneop with their own shuttle who has no obligation to listen to you.

**Comment by deltanedas** [comment]
revenant and dragon dont have any obligation either

**Comment by Xeno4** [comment]
syndicate battlecruiser when?

**Comment by JoeHammad1844** [comment]
> i think it could be ok if it was changed from a list to weighted random, then weigh loneop down so its rarer (ss13 balancing mechanism)

I would do that.. if i knew how

**Comment by nopeingeneer** [comment]
now make a chance for ninja to spawn other ninja

**Comment by JoeHammad1844** [comment]
ninja spawns pirates :trollface:

**Review by LankLTE — CHANGES_REQUESTED** [review]
This would need to be weighted in some way to be implemented, a loneop is notably more dangerous than a dragon or revenant are.

**Comment by JoeHammad1844** [comment]
> This would need to be weighted in some way to be implemented, a loneop is notably more dangerous than a dragon or revenant are.

i dont know how to do that :trollface:

**Comment by JoeHammad1844** [comment]
at least its a little offset by the ninja suit only having 20% resistances now

**Comment by deltanedas** [comment]
> i dont know how to do that :trollface:

instead of List<Threat> make it a ProtoId<WeightedRandomPrototype> then make threat a prototype and then you can weight each threat
then use comp.Threats.Pick(_random) and _proto.Index<ThreatPrototype>(picked)

**Comment by JoeHammad1844** [comment]
yeah im not a coder, cant do that

**Comment by deltanedas** [comment]
always a first time for everything :trollface:

**Comment by JoeHammad1844** [comment]
:trollface:

**Comment by deltanedas** [comment]
remake with weighted random entry being less than 1

**Comment by JoeHammad1844** [comment]
nah dude i cant

**Comment by deltanedas** [comment]
see the pr i made...

**Pull request closed without merging**
