### PR TITLE
Meta map: remove arrivals chair, changed maints shotgun to beanbag rounds

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR
- Removed chair in arrivals that would block a firelock
- Maints DB shotgun to be loaded with beanbags instead of lethal shells

## Why / Balance

Chair blocking firelock and causing spacing is bad

Shotgun in secret room now won't let you powergame and ruin an antag run 10 minutes into a shift

This is my first mapping PR, please leave feedback or let me know if my PR will break the map

## Technical details

yml changes only

## Media

image

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**

N/A

### CODE REVIEW

**Comment by lzk228** [comment]
we usually don't do changeligs for maps

**Comment by thebadman4662** [comment]
Weren't contraband secret rooms supposed to get removed in first place? Loot naughty was supposed to be in maints lockers pool, no? Thats whole free set of armor for 0TC guaranteed.

**Comment by Everturning** [comment]
> Weren't contraband secret rooms supposed to get removed in first place? "Naughty" loot was supposed to be in maints lockers pool, no? Thats whole free set of armor for 0TC guaranteed.

its a reference to doom i think so its fine

**Comment by thebadman4662** [comment]
> > Weren't contraband secret rooms supposed to get removed in first place? "Naughty" loot was supposed to be in maints lockers pool, no? Thats whole free set of armor for 0TC guaranteed.
> 
> its a reference to doom i think so its fine

Rip old doom set that was there QQ. Still, anything that gives you an edge in combat like armor or weapons was supposed to get wiped, only truly cosmetic stuff like cat ears, wizzard robes and so on are to be hidden in secret rooms but maybe something changed or people do not care enough.

**Comment by Everturning** [comment]
eh I mean its fun and also can be taken away by sec at any time

**Comment by thebadman4662** [comment]
At least its not bloodred contra like on some maps. :)

**Comment by TurboTrackerss14** [comment]
When I went through almost EVERY map to highlight powergaming issue spots. 

This was brought up there as a direct reference to the ones that are "fine" because they have some lore or reference implication. 
Its 2 lethal shells, it really ain't that deep imo. 
(it should also still be scaf armor but meh)

**Comment by TurboTrackerss14** [comment]
> > This was brought up there as a direct reference to the ones that are "fine" because they have some lore or reference implication. Its 2 lethal shells, it really ain't that deep imo. (it should also still be scaf armor but meh)
> 
> Two is enough to kill an antag and get an admin note as I've learned the hard way

Personal restraint? Nah. Pr it out. 
If we removed things that players used to break the rules we wouldn't have much of a game to begin with.

**Pull request merged**
