### PR TITLE
Sadness Attempt 2

### PR DESCRIPTION
**Pull request by DieselMohawk**
## About the PR
 Redid Sadness in a Dev environment. Sadness is a chem that can be made with Happiness and Copper in a 1:1 ratio. (Hope yall get the joke)

## Why / Balance
 A friend wants to make a plant mutation that includes this.

## Media

image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Sadness

### CODE REVIEW

**Comment by DieselMohawk** [comment]
#32256

**Comment by Ilya246** [comment]
the one time when
- remove: Removed fun!

describes what the pr does

**Comment by G-370** [comment]
I want this, so that I can sneakily inject the clown with sadness when he comes to the medbay, because he is honking too much and giving me headaches

**Comment by Cojoke-dot** [comment]
"It should be radium instead of copper" - John Moth

**Comment by Caketaco** [comment]
I don't get the joke :(

**Comment by DieselMohawk** [comment]
> I don't get the joke :(

What makes the clown sad? The Cops!

**Comment by TheShuEd** [comment]
After discussions, we have decided that adding new fluff reagents is not necessary at this time. Happiness brings almost nothing interesting to the game to make this side interesting to develop.

Thanks for your contribution!

**Pull request closed without merging**
