### PR TITLE
Bartending Content & Bug Fixes

### LINKED ISSUE #818: Booze catastrophe
- [ ] Many drinks are empty (like the changeling sting and beepski smash)
- [ ] The animations should play faster (Ling sting and beepski smash)
- [ ] The drinks cant be made by mixing
- [ ]  The drinks are made of their own chemicals  (This may be a no-issue)
- [ ] You cant drink from beakers
- [ ] Booze-o-Matic is empty
- [ ] The drinks dont update their sprite when they are empty

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## Adding Bartending Content and bug fixes

Partially Fixes  #818
I've added several new reagents, drinks, recipes, and items for bartending
Added said items to the right place, such as booze-o-mat in the case of bottles and cartons
Attempted to alphabetize YML files and clean them up
Fixed empty bottles in the spawn menu as well as the booze-o-mat
Fixed the size of some drink container objects to be on par with most ss13 forks
Changed Thirteen Loko and its sprite to a more fitting Fourteen Loko

**Screenshots**
image

**Changelog**

:cl: Daemon
- tweak: Changed Thirteen Loko to Fourteen Loko
- fix: Fixed some bottles in booze-o-mat and admin spawn panel being empty
- add: Added various new reagents for bartending and added them to dispensers and vending machines
- add: Added many new craft-able mixed drinks, experiment to find out!

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
Alright I'm good to go for another check on this

**Comment by ZeroDayDaemon** [comment]
Typos are the bane of my existence

**Comment by mirrorcult** [comment]
you can run yaml linter locally

**Comment by ZeroDayDaemon** [comment]
I figured I could, but was unable to figure out how

**Comment by mirrorcult** [comment]
dotnet cli - `dotnet run Content.YAMLLinter`
rider/vs - right click on the project and click run

**Review by PaulRitter — APPROVED** [review]
holy fuck man am i lucky for serv3

**Pull request merged**
