### PR TITLE
tweak(atlas): Swap mindshield implant crate with implant crate

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

In the armoury on atlas, swapped the mindshield implant crate with an implanter crate.

## Why / Balance

Maps should have tracking implants.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
I have no idea if my changes actually went through.

**Comment by deltanedas** [comment]
isnt there a crate with both

**Comment by Brandon-Huu** [comment]
> isnt there a crate with both

yeah its the implanter crate, the one i put in instead of mindshield implant crate

**Comment by deltanedas** [comment]
ok well remake it the diff is cringe

**Comment by Brandon-Huu** [comment]
**Reasons for closing:**

- Not able to see changes in testing even after redoing three + times
- Causes merge conflicts with bigger PRs

**Pull request closed without merging**
