### PR TITLE
Bots now make sound when they speak

### LINKED ISSUE #31454: Honkbots should have a sound when speaking
## Description

This probably applies to other bots like medibots/janibots etc.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
Basic silicons like medbots, janibots, honkbots now make sound when speaking.

## Why / Balance
fixes #31454 

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- fix: Silicons like medbots, janibots, and honkbots now make sound when speaking.

### CODE REVIEW

**Comment by Moomoobeef** [comment]
damn that was quick :+1:

**Comment by lzk228** [comment]
hey! i added this in #29949

**Comment by slarticodefast** [comment]
> hey! i added this in https://github.com/space-wizards/space-station-14/pull/29949

no merge conflict then :trollface:

**Comment by Errant-4** [comment]
> hey! i added this in #29949

Weird. It appears that between https://github.com/space-wizards/space-station-14/commit/726589bd66fe148c486f0bc8b27d037bba2c6d98 and https://github.com/space-wizards/space-station-14/commit/a3cbbe745e83d43103ed8c5a7ab10dcf3ffa7112 the line somehow disappeared without any apparent commit

**Comment by lzk228** [comment]
> Weird. It appears that between [726589b](https://github.com/space-wizards/space-station-14/commit/726589bd66fe148c486f0bc8b27d037bba2c6d98) and [a3cbbe7](https://github.com/space-wizards/space-station-14/commit/a3cbbe745e83d43103ed8c5a7ab10dcf3ffa7112) the line somehow disappeared without any apparent commit

my pr isn't merged yet, so actually this pr is a little part of mine that was merged faster
kinda frustrating, but fine

**Comment by slarticodefast** [comment]
>my pr isn't merged yet, so actually this pr is a little part of mine and just was merged faster
kinda frustrating, but fine

Sorry about that, but small bugfixes can be merged without a prior maintainer discussion, different from feature additions like the added emotes in your PR.

**Comment by Moomoobeef** [comment]
Yea I didn't know you were working on that I was just trying to knock out some simple bugs last night

**Pull request merged**
