### PR TITLE
Holographic projectors can be put into respective belts

### PR DESCRIPTION
**Pull request by Interrobang01**
## About the PR 

Now you can put holofan projectors in the toolbelt, and more importantly, you can put both holosigns **_and normal signs_** in the janibelt.

H̶o̶p̶e̶f̶u̶l̶l̶y̶ ̶t̶h̶e̶r̶e̶ ̶a̶r̶e̶ ̶n̶o̶ ̶u̶n̶i̶n̶t̶e̶n̶d̶e̶d̶ ̶c̶o̶n̶s̶e̶q̶u̶e̶n̶c̶e̶s̶ ̶o̶f̶ ̶g̶i̶v̶i̶n̶g̶ ̶t̶h̶e̶ ̶h̶o̶l̶o̶s̶i̶g̶n̶ ̶p̶r̶o̶j̶e̶c̶t̶o̶r̶ ̶t̶h̶e̶ ̶W̶e̶t̶F̶l̶o̶o̶r̶S̶i̶g̶n̶ ̶t̶a̶g̶.̶.̶.̶
Edit: Gave Holosign Projector its own tag (the physical sign still fits in the belt though)
**Screenshots**

image

**Changelog**

:cl:
- tweak: You can now put holofan projectors into the utility belt.
- tweak: You can now put both holosign projectors and wet floor signs into the janibelt.

### CODE REVIEW

**Comment by moonheart08** [comment]
Give the projector it's own new tag instead of reusing one.

**Comment by Interrobang01** [comment]
Gave the sign projector its own tag, but the physical wet floor sign will still be fitting in the janibelt.

**Comment by Interrobang01** [comment]
i *might* resolve the conflict tomorrow

**Comment by Interrobang01** [comment]
well it's done now, for real this time, i think.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
