### PR TITLE
show battery charge when recharger is examined

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title also cleaned it up to not duplicate so much stuff

## Why / Balance
if you are impatient its annoying to take out battery examine it put it back in every few seconds
so you can just examine the charger

## Technical details
no

## Media
cell charger is yes

others are no

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Rehargers can be examined to show the charge of the battery or weapon inside.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
screenshots noob

**Comment by deltanedas** [comment]
yes i had to fix it first noob

**Comment by deltanedas** [comment]
@metalgearsloth noob

**Comment by Partmedia** [comment]
Doesn't the charger blink pretty noticeably when charging is complete?

**Comment by deltanedas** [comment]
its not that i dont know when its done its i dont knot when it will be done

**Comment by EmoGarbage404** [comment]
test fails aren't erroneous

**Pull request merged**
