### PR TITLE
Improved output distribution of RoundToLevels

### PR DESCRIPTION
**Pull request by Tayrtahn**
## About the PR

This changes the math behind ContentHelpers.RoundToLevels to give a more even distribution of outputs.

## Why / Balance

While playing with fill levels, I noticed that the thresholds between sprite changes seemed oddly spaced. I tried graphing the results of the algorithm and found that the distribution was not what I was expecting. This change gives more even spacing between all levels while preserving the behavior of making the zero and max levels require exact matches.

## Technical details

This worked for all the test cases I threw at it, but I'm not a mathematician - if anyone can find an instance where this breaks, please let me know.
This algorithm should actually be a teensy bit faster, as a bonus.

## Media

6 levels, before:
Screenshot 2024-02-07 at 1 56 13 PM
6 levels, after:
Screenshot 2024-02-07 at 1 56 20 PM
5 levels, before:
Screenshot 2024-02-07 at 1 57 29 PM
5 levels, after:
Screenshot 2024-02-07 at 1 57 36 PM

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Tayrtahn** [comment]
Tests are failing because the tests expect the old, bad values as output. Guess I'll update the tests?

**Comment by PJB3005** [comment]
> Tests are failing because the tests expect the old, bad values as output. Guess I'll update the tests?

Yeah that's fine.

Also thank you for taking care of my 5 year old code.

**Comment by Tayrtahn** [comment]
Latest test failure appears unrelated.

**Comment by Tayrtahn** [comment]
To be overly cautious: if there are any bug reports about ammo meters or charge levels, this may require further review.

**Pull request merged**
