### PR TITLE
chore(core): correctly label the fax machines

### PR DESCRIPTION
**Pull request by Brandon-Huu**
# Why
It was wrong

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Draft because, some of the maps are weird

**Comment by Brandon-Huu** [comment]
image
Why is captain's fax machine like that?

**Comment by Brandon-Huu** [comment]
should the name be capitalized or not?

**Comment by Brandon-Huu** [comment]
Why is name defined twice? to uncapitalize it?

**Comment by Brandon-Huu** [comment]
Nah, that doesn't make sense. 
Because the name "Head of Personel" was capitalized

**Comment by UbaserB** [comment]
When i fix the map myself later (due to how map conflicts work, its easier to just redo all of the changes you guys do), can i ask which ones are the problem?

**Comment by Brandon-Huu** [comment]
> can i ask which ones are the problem?

I was just correcting the spelling mistakes for the fax machines at first.
The obvious issues are already committed in this PR.

The other stuff I was commenting about was just about weird stuff and inconsistencies I noticed.

Like on saltern, the hop's office fax machine not having a destinationAddress and still working for some reason.
Why do we need destinationAddresses if they're unneeded?

Minor stuff like this:
HoP's doors being named on some maps and not on others.
Having different names on different maps.
Could probably just be fixed by giving the prototype a metadata component?


image

**Pull request closed without merging**
