### PR TITLE
Pillar Update 5.4

### PR DESCRIPTION
**Pull request by Emisse**
this update was done with peptides permission with the aim to keep visual style as close as possible to how it currently is

the purpose for this update was after playing this map many times on several different jobs there were a lot of specific things i wanted fixed without blowing up peptides DMs because hes been fairly busy lately
i also wanted to decorate the atriums really badly

changelog
	main changes
-atriums now have biodiversity 
-maints have been fully fleshed out with unique rooms and loot providing a better exploration and rp experience
-firelocks have been changed around and put in positions to better allow movement during spacings without spacing the whole station
-line of sights have been changed in many places to accomodate for more visibility for high risk areas. and sight blockers for 'opportunistic' areas
-inner windows have been given the bagel treatment of double reinforcement to prevent spacing of common areas as often
	engineering
-atmos has been redone and a mixing chamber has been added
-supermatter engine room has been setup and is ready for sm
-visual touchups in engineering
-extra QOL in drone closet in engineering 
-CEs room has been upgraded
-extra items around engineering (wires, gloves, fuel, etc)
	security
-security has been visually touched up tile wise to break up visual monotony and better distinguish different sections
-armory now uses armory access doors 
-the sec dorms has been replaced with a shooting range
-perma has firelocks in it so if someone spaces it it wont kill everyone inside it
	cargo
-salvage crates have been changed to salvage lockers
-i havent played much cargo on this station so i mostly left it be 
	medical
-changed medicals color to a more pleasing sterile cyan to match peptides original floor decals
-medical now has glass doors to enter it so it is spaced less easily
-chem now has 3 chem stations and walter
-viro now has all proper viro items
-extra med equipment has been laid around
-CMOs room has been decorated
	service
-firelocks have been changed around so spacing is less lethal
-botany now has 2 seed extractors
-botany has a grinder
-kitchen has a 2nd grinder
-kitchen and botany now have a door between them
-bar now has 2 sets of dispensers to accomodate 2 tenders
-musician now spawns in that stage room 
-room above bar is now a kaiten sushi room 
-janitors room has extra stuff now and a small window to help new players find it easier
-mime and clown rooms now have extra stuff
-library and chapel are mostly untouched just added some flavor items and more bookshelves/figures to library
	command
-bridge has been given several vulnerabilities to make it easier to sneak into
-line of sight changes in bridge
-captains office has been fleshed out
-bridge has had all shuttle consoles removed
-added a 2nd comms console to bridge due to the size of the station necessitating 2
-vault has been fleshed out
-hops room now has stamps and paper
	science
-science has been visually updated to the new style to be less eye searing
-RDs room has been redone
-sci now has a proper toxicology lab
-sci maint hatches now have the proper locks

NOW FOR SOME CANDID PHOTOTS BECAUSE I DONT BE RENDERING
image
the park
image
medbays new color scheme
image
service area
image
new sci
image
atmos
image
image
bridge

### CODE REVIEW

**Comment by moonheart08** [comment]
hey the gravgen physically blocks the doors, you can't get in

**Comment by moonheart08** [comment]
NSSPillar-0

**Comment by Emisse** [comment]
> hey the gravgen physically blocks the doors, you can't get in

yea i didnt touch the grav gen at all but i can move it over real quick

**Comment by Emisse** [comment]
Moved the grav gen over and added janitor trolley since that's in now. Should B good

**Pull request merged**
