### PR TITLE
Fingerprints filter for records station console

### PR DESCRIPTION
**Pull request by Arteben**
## About the PR
Here a filter is added to search for personnel by fingerprints. New functionality is added to the station records console. The most of the new functionality is added to the client side, but some changes has added in server & shared parts. There, the data that was used is expanded with objects included name & fingerprints values. Also I've added new translates for new buttons and input.

**Media**

The list without filter value

The list with filter value

The empty list with filter value

**Changelog**

:cl:
- add: Added filters of fingerprints for the station record computer

### CODE REVIEW

**Comment by vulppine** [comment]
hmm - this is a bit conflicting because this is a client side search of a single value, which is fine - but the real solution here would be something that would allow for searching for arbitrary strings (either all fields of a record, or through a single field per record) through all records in that record type

**Comment by Arteben** [comment]
firstly i wanted to make the new features for a detective RP. I can extended it with new filters for name person and make ability for more future extends but that is all.

**Comment by vulppine** [comment]
i feel like this sets a bad pattern where we're sending over more data per-person than we should to a client, when originally you could just send over a key and then the server would send over the data associated with that key: i think a server-side approach would be better, since it means you can extend it to as many fields as you want and you'd still just be sending over the keys to the client, rather than every single field you want to search through

**Comment by Arteben** [comment]
Well. I'll look how i can improve this. But can you point a place where should make the list of person names for show in left column. Сurrently it makes on server side during opening the console.

**Pull request closed without merging**
