### PR TITLE
Added pink handcuffs!

### PR DESCRIPTION
**Pull request by Stanislav4ix**
^w^

## About the PR
I added pink handcuffs! You can find them in maintenance closets with 10% chance!

## Why / Balance
For good RP process.

## Technical details
Nothing special.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**
:cl: Stanislav4ix
- add: Added pink handcuffs! You can find them in maintenance closets, good luck!

### CODE REVIEW

**Comment by deathride58** [comment]
Not sure wizden's the right place for this

**Comment by Tunguso4ka** [comment]
in protect of author of this PR, i want to say that this handcuffs was on Paradise Station.

**Comment by Eden077** [comment]
I don't believe this has any place on wizden... At all, seems like a huge moderation headache imo

**Comment by asperger-sind** [comment]
close this pr and reopen it as #25000

**Comment by noctyrnal** [comment]
nah

**Comment by VasilisThePikachu** [comment]
🤨

**Comment by CrigCrag** [comment]
🤨

**Comment by Dynexust** [comment]
Hehehe

**Comment by Stanislav4ix** [comment]
Oh.. Ok, you dont like them...

**Comment by Errant-4** [comment]
Apart from 🤨, why are you making a brand new prototype from BaseItem instead of inheriting from handcuff and just changing the sprite

**Comment by VasilisThePikachu** [comment]
I think its funny, just kind of... blursed

**Comment by Hiucko** [comment]
💀

**Comment by Mirino97** [comment]
Hi there!

I'm sorry, but I do not think this belongs in Wizden. We do not need multi colored handcuffs, and the implications a pink, apparently fuzzy handcuff brings is too much con for the pros.

I'm not a maintainer tho, so if you're lucky, maybe one of them will disagree with me and merge this!

**Comment by lzk228** [comment]
🤨 people are like: we dont need fun
i personally really dont see what is the issue in that handcuffs, if someone can give a constructive answer, please, go ahead

**Comment by deathride58** [comment]
Fluffy handcuffs are traditionally associated more with BDSM (a sexual activity) than anything else. Additionally, the PR author's original PR description stated the intent was `For good RP process and for romantic`, with the original item description within the PR itself being `Used to detain "bad" boys and girls.`

The intent is crystal clear, and really doesn't need to be spelled out more explicitly than that. Wizden *really* isn't the place for this.

**Comment by deltanedas** [comment]
the erp update

**Comment by Stanislav4ix** [comment]
> Fluffy handcuffs are traditionally associated more with BDSM (a sexual activity) than anything else. Additionally, the PR author's original PR description stated the intent was `For good RP process and for romantic`, with the original item description within the PR itself being `Used to detain "bad" boys and girls.`
> 
> The intent is crystal clear, and really doesn't need to be spelled out more explicitly than that. Wizden _really_ isn't the place for this.

But now it's just pink handcuffs. I made a bit of a mistake when I wrote this... I apologize

**Comment by Nairodian** [comment]
Just leave it for the maintainers. Discussion about this doesn't really need to be had.

**Comment by Stanislav4ix** [comment]
> the erp update

No! It's just pink handcuffs

**Comment by lzk228** [comment]
> Fluffy handcuffs are traditionally associated more with BDSM (a sexual activity) than anything else. Additionally, the PR author's original PR description stated the intent was `For good RP process and for romantic`, with the original item description within the PR itself being `Used to detain "bad" boys and girls.`
> 
> The intent is crystal clear, and really doesn't need to be spelled out more explicitly than that. Wizden _really_ isn't the place for this.

if first what player will think it's a "ohhh pink handcuffs, i wanna detain and hug mime!" then thats a bad player, not a handcuffs

**Comment by noctyrnal** [comment]
next pr is a phallic shaped object named the "back massager" and anyone who uses it for anything else clearly is a bad person, not the object. the cuffs and their intentions are blatant from their design and trying to chalk it up to acting clueless wont get it added. but im not a maintainer so what I say isn't the words of wizden , but what I can say is that they're clearly bsdm tools and bait erp

**Comment by Nairodian** [comment]
Literally just drop it. Adding on your two cents is unneeded and just comes off as very dog pile-ish. Let the maintainers handle it, enough said.

**Comment by Varen** [comment]
If we can have sexy clown / mime mask, we can have this, honestly.

**Comment by Tunguso4ka** [comment]
> If we can have sexy clown / mime mask, we can have this, honestly.

sexy clown mask
rainbow jumpsuit
pink cuffs
highboots

this is 💞💓💘💖 fashion 💞💘💝💕

**Comment by Emisse** [comment]
good try

**Comment by JoeHammad1844** [comment]
le ERP item

**Comment by Hmeister-fake** [comment]
I like the idea of clowns or mimes having a these, it would be pretty funny as a 1 tc clown syndie item or something you can craft with a clown horn and cuffs lol. Just rename them to Honk Cuffs or Clown Cuffs and replace the handcuff noises with honks, could actually be good for hiding the fact your cuffing someone.

**Comment by Hmeister-fake** [comment]
> I like the idea of clowns or mimes having a these, it would be pretty funny as a 1 tc clown syndie item or something you can craft with a clown horn and cuffs lol. Just rename them to Honk Cuffs or Clown Cuffs and replace the handcuff noises with honks, could actually be good for hiding the fact your cuffing someone.

I should make this a suggestion actually

**Comment by JoeHammad1844** [comment]
> I like the idea of clowns or mimes having a these, it would be pretty funny as a 1 tc clown syndie item or something you can craft with a clown horn and cuffs lol. Just rename them to Honk Cuffs or Clown Cuffs and replace the handcuff noises with honks, could actually be good for hiding the fact your cuffing someone.

that would be really funny actually

**Pull request closed without merging**
