### PR TITLE
HOP glove resprite

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Resprited the HOP gloves to look a little more fancy
## Why / Balance

The HOP is second in command (at least for non security matters), it'd make sense for the HOP's gloves to look fancy like the captain's.
## Technical details

n/a
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
 
image

image

image

## Breaking changes

**Changelog**

:cl: 
- tweak: Re-sprited HOP gloves to match the prestige of being second in command

### CODE REVIEW

**Comment by lzk228** [comment]
i don't like the fact it's matching more to uniform, because that gloves supposed to be only for paperwork and not weared all-time

**Comment by MACMAN2003** [comment]
in this world it's drip or drown and the HOP is too important to drown lol

**Comment by BolloTea** [comment]
You can also make him a hardsuit, like a captain’s🤡

**Comment by BolloTea** [comment]
He's sooo important...

**Comment by UbaserB** [comment]
Literally the next after i make the PR after putting a lot of effort into the sprite, it’s getting replaced? It least give it a chance.

**Comment by EmoGarbage404** [comment]
i think the brown is a nice contrast with the rest of the uniform and it pairs nicely with the shoes. adding even more blue to the outfit just makes it look more generic and indistinct. The current gloves look plenty fancy as-is with their gold trimmings. I don't see why making them look like bulky gauntlets is a better fit for the role.

**Comment by MACMAN2003** [comment]
alright then, i guess.

**Pull request closed without merging**
