### PR TITLE
Prettified human_hair.rsi meta.json

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Made the file look pretty.

## Why / Balance

It was terrible to look at.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by deltanedas** [comment]
pro 4 space indent then 2

**Comment by iacore** [comment]
what is the purpose of this change?????

**Comment by Colin-Tel** [comment]
> what is the purpose of this change?

My apologies, I thought it was obvious.

It makes the `.json` readable and similar to the bulk of the other `meta.json` files that exist for textures.

**Comment by lzk228** [comment]
for what are delays exist?

**Review by EmoGarbage404 — APPROVED** [review]
Would be really cool if you could remove the delay (they are no longer necessary) otherwise pretty epic pr 10/10

**Comment by Colin-Tel** [comment]
> Would be really cool if you could remove the delay (they are no longer necessary) otherwise pretty epic pr 10/10

Thanks! I think it's good now.

**Pull request merged**
