### PR TITLE
Refactor/wounds

### PR DESCRIPTION
**Pull request by Jezithyr**
## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by PixelTheKermit** [comment]
### **Surgery, just a week away!**
**I'm so happy about this information**

**Comment by AJCM-git** [comment]
this code is perfect

**Review by PixelTheKermit — APPROVED** [review]
I approve.

**Comment by OctoRocket** [comment]
I need to see this in action

**Comment by PixelTheKermit** [comment]
> I need to see this in action

You can always try building the branch yourself

**Review by EmoGarbage404 — COMMENTED** [review]
As per the decision at the latest maintainer meeting, new large content features must have guidebook entries and corresponding GuideHelpComponents.

**Comment by Jezithyr** [comment]
Moving this to my personal git

**Comment by DrSmugleaf** [comment]
See https://github.com/space-wizards/space-station-14/pull/13917

**Pull request closed without merging**
