### PR TITLE
Padded ItemStatus Text

### LINKED ISSUE #27756: Itemstatus left side text needs slightly more padding
## Description

image

looks strange right up against the selection border needs like 1 or 2 px of left/bottom padding. looks fine on the right

### PR DESCRIPTION
**Pull request by Willhelm53**
## About the PR

Adds a little margin to the ItemStatus text. Fixes #27756.

## Why / Balance

~~Literally unplayable, WizDen plz fix~~
Minor graphical fix.

## Technical details

"No held item" can have a little margin as a treat.

## Media

(Showcase not needed. Before/After included for ease of review.)

Before:
image

After:
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

n/a

### CODE REVIEW

**Review by ShadowCommander — CHANGES_REQUESTED** [review]
Add this to StyleNano for ItemStatusNotHeld.

**Comment by Willhelm53** [comment]
<details>
  <summary>Thanks! Let me know if I missed anything else.</summary>

image

</details>

**Review by ShadowCommander — DISMISSED** [review]
Do the same for ItemStatus and check if it works if you remove the Margin from the xaml.

If it doesn't work, then just use the margin in the xaml.

Also nice commits.

**Comment by Willhelm53** [comment]
When I tried StyleNano only, it worked for ItemStatusNotHeld but not for ItemStatus. Sticking with the XAML for now because it works for both. Thanks for pointing me towards StyleNano! This one's ready for review any time.

**Comment by ShadowCommander** [comment]
It does work in StyleNano, but you have to convert the ItemStatus one from the old way to the new way. ItemStatusNotHeld is using the new way.

**Comment by Plykiya** [comment]
I don't know how to suggest this as a change, but they want you to do this
`                Element()
                    .Class(StyleClassItemStatusNotHeld)
                    .Prop("font", notoSansItalic10)
                    .Prop("font-color", ItemStatusNotHeldColor)
                    .Prop(nameof(Control.Margin), new Thickness(4, 0, 0, 2)),

                Element()
                    .Class(StyleClassItemStatus)
                    .Prop(nameof(RichTextLabel.LineHeightScale), 0.7f)
                    .Prop(nameof(Control.Margin), new Thickness(4, 0, 0, 2)),`

image

image

**Pull request merged**
