### PR TITLE
Adds Plastitanium, Plastitanium glass, Titanium, Titanium Glass, as well as Titanium and Plastitanium Glass shards

### PR DESCRIPTION
**Pull request by Ablankmann**
## About the PR 

I was looking around and stumbled upon sprites for Plastitanium, and Titanium stuff. Decided there would be no harm to add em. Right now they're sheets used for nothing, but I do intend to add stuff for them to be used on in the future

:cl:
- add: Adds Plastitanium Sheets, Plastitanium Glass Sheets, Titanium Sheets, Titanium Glass Sheets, as well as Titanium and Plastitanium Glass shards.

### CODE REVIEW

**Comment by Zumorica** [comment]
We don't currently accept prototypes that are not actually used for anything, sorry.

**Comment by metalgearsloth** [comment]
If you added the walls themselves so mappers can make the syndie stuff it'd probably get merged.

**Comment by EmoGarbage404** [comment]
Im not sure of the current maintainer stance on new resources, so I cant comment too much on adding more. What i will say is that adding new prototypes with no use and no in-game way of acquiring them almost certainly qualifies bloat content. If anything, the sprites should be removed until decided on whether or not they will be used. The vague promise of "I'll use them soon" doesnt seem to justify their inclusion.

**Comment by Peptide90** [comment]
I’m general are they used for anything unique? Or is it just shuttle walls and floors etc? 

To add to others, a use for shards is construction of spears, otherwise construction graphs for making shuttle walls or plast whatever walls will do it.

**Comment by Peptide90** [comment]
Tests are also failing because you need to create a stack prototype for each new material here:

/[Prototypes](https://github.com/space-wizards/space-station-14/tree/master/Resources/Prototypes)/[Stacks](https://github.com/space-wizards/space-station-14/tree/master/Resources/Prototypes/Stacks)/Materials/

**Pull request closed without merging**
