### PR TITLE
Goliath Nerf

### PR DESCRIPTION
**Pull request by PopGamer45**
## About the PR
Nerfs the goliath, changing its:
DPS from 18.75 to 10.5 (Damage from 25 to 14)
HP from 300 (12 PKA hits) to 150 (6 PKA Hits)
and its tentacle stun time from 5 to 4 seconds

**Drafting this until i ask Emo if the nerf is ok, i dont know, i feel like iam stepping on other's plans**

## Why / Balance
Currently the goliath is too powerful, it can crit you in 4 (counting armor maybe 5) hits and combined with its tentacle attack if it catches you offguard and close enough due to the stun being 5 seconds it can pretty much stunlock you because when you recover from the first stun you are gonna be slowed down from the damage and unable to escape the second one, effectively stunlocking you. Currently the goliath makes mining at the VGroid just not worth it.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: PopGamer46
- tweak: Nerfed the goliath

### CODE REVIEW

**Comment by PopGamer45** [comment]
dont know how that last commit got there, gonna remove it

**Comment by Scruq445** [comment]
We need this merged, I've seen goliathes take down entire Salvage teams because of the stunlocking, It takes about 3 Salvagers to take down a Goliath, and salvagers usually spread apart to cover more ore, and then suddenly getting stunned and beaten to death by a single goliath.

**Comment by Scruq445** [comment]
And even if you do somehow dodge most of it's tentacles, it'll probably slow you down with the damage in order to catch up to you

**Comment by PopGamer45** [comment]
After making this PR i read the salvage design doc and the VGroid is supposed to be a high risk high reward area where salvage will go later in the round when they have upgrades (which are not in yet). Also after playing some rounds its safe to say that with the right strategy they are not that hard, for example if you with another salvage attack it from multiple sides it is pretty easy to defeat since it can focus only on one of you and if one of you gets stunned the other one can distract it

**Pull request closed without merging**
