### PR TITLE
Rename "Syndicate jaws of life" to "Jaws of death"

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

`Syndicate jaws of life` are now called `Jaws of death`
made in hand and belt sprites fit item sprite (darker handle and etc.)

## Why / Balance

I think its a fun pun.
I am planning to make it a better gibbing tool (capable butchering humans / large mobs without too much noise)

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Syndicate re-branded their jaws of life to boost sales.

### CODE REVIEW

**Comment by LankLTE** [comment]
> I am planning to make it a better gibbing tool 

this feels like a bad design idea for the jaws of life, it already has a niche in being cheap and relatively fast way to open doors and I think it does that alright(ish). A better direction would probably be to let it open locked lockers

**Comment by EmoGarbage404** [comment]
Considering that Jaws of Life refers to a [specific real world tool](https://en.m.wikipedia.org/wiki/Hydraulic_rescue_tool), changing it doesn't really make sense? Its kinda like making syndicate wirecutters but naming them wireKILLERS because they're EVIL.

**Comment by deltanedas** [comment]
> Its kinda like making syndicate wirecutters but naming them wireKILLERS because they're EVIL.

good pr idea just need blood-red wirecutter sprite

**Comment by Slava0135** [comment]
> Considering that Jaws of Life refers to a [specific real world tool](https://en.m.wikipedia.org/wiki/Hydraulic_rescue_tool), changing it doesn't really make sense? Its kinda like making syndicate wirecutters but naming them wireKILLERS because they're EVIL.

They are black and deal more damage

**Comment by LankLTE** [comment]
> Its kinda like making syndicate wirecutters but naming them wireKILLERS because they're EVIL.

This sounds badass can we do that.

To be serious I agree, this seems unnecessary

**Comment by HoidC** [comment]
> Considering that Jaws of Life refers to a [specific real world tool](https://en.m.wikipedia.org/wiki/Hydraulic_rescue_tool), changing it doesn't really make sense? Its kinda like making syndicate wirecutters but naming them wireKILLERS because they're EVIL.

you know that's kind of a cool idea though

**Comment by Emisse** [comment]
i like this i think this is funny

**Comment by deltanedas** [comment]
fr someone make wirekillers sprite we need this in sus box on nukie planet etc

**Comment by Slava0135** [comment]
Something like wirekillers would be hard to translate (though we have cow tools)

**Comment by LankLTE** [comment]
To bring the discussion somewhat back to the PR: 

I think renaming it is whatever, but don’t like the proposed rework you'll do later, and without that the name doesn't make a lot of sense, so it should probably just stay as it is.

**Comment by deltanedas** [comment]
if you want to gib someone susbox costs the same and does 20 blunt, very quick gibber

**Comment by keronshb** [comment]
There's a pre-existing gibbing/killing tool already and it's the minibomb.
There's also one that exists in SS13 which is a comedy item called the nutcracker, which is exactly what you think it is. An oversized nutcracker for squishing heads (once a doafter finishes)

**Comment by Equivocateur** [comment]
> Something like wirekillers would be hard to translate (though we have cow tools)

Проводонигилятор

**Comment by Tunguso4ka** [comment]
> the nutcracker, which is exactly what you think it is. An oversized nutcracker
😀

> for squishing heads
😭

**Comment by JoeHammad1844** [comment]
funny, need

**Comment by Partmedia** [comment]
I agree with @EmoGarbage404 , "jaws of life" refers to a real tool. Unless you want to go make killbars, screw-the-station-drivers, wirekillers, etc.

**Comment by Partmedia** [comment]
I've opted to keep the existing name for now. If you have new arguments in favor, or would like to continue discussing this name change, please feel free to re-open.

Regardless of the name change, in the future, there is no need to rename all of the files to match the new name. This causes unnecessary repository churn.

**Pull request closed without merging**
