### PR TITLE
Syndicate pAI for Nukies

### LINKED ISSUE #16802: Nukie pai's have access to common
## Description

Since all pais have by default common access, they get to access it as soon as they reach the station. May be intended? i mean its not like the best channel to have access but knowing if general joe started screaming nukies may be useful
**Reproduction**

1. Activate pai on nukie planet
2. ftl to station
3. talk in common, pai will see it
**Screenshots**

**Additional context**

My only idea was creating a "jailbroken pai" that just parents pai and overwrites the radio section with the syndi channel instead. But i feel like there is another way to do this which would be better.

### PR DESCRIPTION
**Pull request by crazybrain23**
## About the PR

Adds a Syndicate pAI for use with Nuclear Operatives in order to grant them access to the Syndicate channel and revoke the Common channel (resolves #16802). This is a continuation of #17249.

**Media**

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: crazybrain
- add: Added Syndicate pAI.
- tweak: Syndicate pAI's can be found on the Nukie planet.

### CODE REVIEW

**Comment by lzk228** [comment]
add it to pointless catgory in uplink

**Comment by crazybrain23** [comment]
> add it to pointless catgory in uplink

sure, how many TC? 2?

**Comment by Eden077** [comment]
Really even 1 tc sounds good cause some pai's are uh... Pretty shitty and or metagamey

**Comment by lzk228** [comment]
imagine 20 syndi pAIs in captain hq

**Comment by Emisse** [comment]
do the uplink thing in another pr cuz i want to avoid bikeshedding on this one

**Pull request merged**
