### PR TITLE
Space worms

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR

Simple new kudzu type.
- Slippery
- Easy to remove
- Poison contact damage
- Food?
- can randomly spawned via event
- die easily from high temperatures, but are immune to pressure and space

## Why / Balance
more event variety
accidentally found a texture of these worms in the game files and thought "why not add them?"

## Technical details

minor changes in Kudzu rule

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/4fc15b4d-de74-4a51-85de-ef65e620dd2b

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Space worms can could infect the station

### CODE REVIEW

**Comment by TheShuEd** [comment]
looks boring and uninteresting, I don't like it

**Comment by deltanedas** [comment]
this is just tendons that do poison instead of brute + slip you

**Comment by Djungelskog2** [comment]
I don't think we need another kudzu/meatzu

**Comment by EmoGarbage404** [comment]
i dont really see a noticeable enough difference to have this event alongside kudzu and tendons. I like the sprites but it's probably better served as its own cool biohazard or antag or w/e

**Comment by slarticodefast** [comment]
>looks boring and uninteresting, I don't like it
Did you just downvote your own PR? Is this a social experiment?

**Comment by TheShuEd** [comment]
> > looks boring and uninteresting, I don't like it
> 
> Did you just downvote your own PR? Is this a social experiment?

This is self cringe

**Pull request closed without merging**
