### PR TITLE
Cargo Hauler Mech

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds the Hauler APLU, a lightweight variant of the Ripley that is tailored towards speed for efficient cargo work. However, due to the decreased load, it has much worse armor and melee attacks, making it mediocre for melee combat (its punches are roughly equal to that of a crowbar, but slower.)

Intentionally not printable and intended to be mapped in Cargo. Hopefully, this should make moving items like crates and lockers significantly less unbearable, and give cargo themselves a way to make money other than just printing items. 

Also renames the "ripley" to the "Ripley APLU", as the old one was not capitalized (and that's what it was called in SS13.)

**Media**
(I have no clue how the audio got so delayed, but it's not like it matters anyways.)

[Content.Client_z2loJdcT9R.webm](https://user-images.githubusercontent.com/78941145/219926282-0ff66f61-e3a6-4f74-8f59-908b947c3819.webm)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added the Hauler APLU, a special lightweight version of the Ripley that can only be found inside of Cargo.
- tweak: Renamed the "ripley" to "Ripley APLU."

### CODE REVIEW

**Comment by 0x6273** [comment]
I don't understand this. Why would you give cargo a free mech on roundstart, that is much better at cargo work than the mech that requires a ton of research and materials to get? Why would cargo ever want to ask sci for a ripley? Is the ripley just a sci mech now?

**Comment by Flareguy** [comment]
> I don't understand this. Why would you give cargo a free mech on roundstart, that is much better at cargo work than the mech that requires a ton of research and materials to get? Why would cargo ever want to ask sci for a ripley? Is the ripley just a sci mech now?

From what I can tell, the Ripley is actually more of a combat mech than anything in SS14, meaning the Hauler doesn't really step on its shoes. It is slow as fuck, provides pretty decent armor, and has devastating punches that can probably perform breaking & entering on any place you want it to.

 As for the latter part... I don't think they really would, though the Ripley is already basically never used to begin with due to its material cost, so it doesn't really matter. I was thinking about rebalancing it later on to make it not a combat mech, but I wanted to take things one step at a time to avoid bloating the PR.

**Comment by arealbeba** [comment]
do we really need a faster version of ripley?

**Comment by jamessimo** [comment]
> > I don't understand this. Why would you give cargo a free mech on roundstart, that is much better at cargo work than the mech that requires a ton of research and materials to get? Why would cargo ever want to ask sci for a ripley? Is the ripley just a sci mech now?
> 
> From what I can tell, the Ripley is actually more of a combat mech than anything in SS14, meaning the Hauler doesn't really step on its shoes. It is slow as fuck, provides pretty decent armor, and has devastating punches that can probably perform breaking & entering on any place you want it to.
> 
> As for the latter part... I don't think they really would, though the Ripley is already basically never used to begin with due to its material cost, so it doesn't really matter. I was thinking about rebalancing it later on to make it not a combat mech, but I wanted to take things one step at a time to avoid bloating the PR.

Ripley is not really a combat mech. Ripley punch is only slightly better than a human with a crowbar. 

I would be happier to see Ripley maybe get a speed boost. I saw in the discord art channel someone posting an exoskeleton for cargo which would look different, offer almost no protection  but no speed penalties for dragging. 

If this concept was to continue I would want something visually very different (smaller) than rip and defo no round start. 

Maybe ripley can be cheaper and upgrades can make it better at combat?

**Comment by Flareguy** [comment]
> 
> Ripley is not really a combat mech. Ripley punch is only slightly better than a human with a crowbar.
> 
> I would be happier to see Ripley maybe get a speed boost. I saw in the discord art channel someone posting an exoskeleton for cargo which would look different, offer almost no protection but no speed penalties for dragging.
> 
> If this concept was to continue I would want something visually very different (smaller) than rip and defo no round start.
> 
> Maybe ripley can be cheaper and upgrades can make it better at combat?

From what I gleamed, it was. For some god forsaken reason, it has stupid high structural damage (you can break into sec almost effortlessly) & does enough damage with its punches to gib. Either way, I think it's clear I should probably buff the Ripley itself first before continuing with this idea.

**Pull request closed without merging**
