### PR TITLE
TeeGee Event Port

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
## About the PR

Ports some [/tg/ events](https://tgstation13.org/wiki/Random_events) to SS14, since there's only around 15 events already in.

**Screenshots**

(I'm not adding a screenshot for every event I port, so take Gr3y.T1d3)
image

**Todo**

- [x] Gr3yt1dde
- [x] Camera Failure
- [x] Cargo Intruders
- [ ] wormhole event
- [ ] space dust
- [ ] stray cargo & syndicate pod
- [ ] wisdom cow
- [ ] random order
- [x] random cargo balance penalty/buff
- [ ] wall erosion

**Changelog**
:cl: eclips_e
- add: Added multiple new events.

### CODE REVIEW

**Comment by AJCM-git** [comment]
are you coming back to this?

**Comment by Just-a-Unity-Dev** [comment]
tomorrow yes

**Comment by AJCM-git** [comment]
So are you coming back to this?

**Comment by Just-a-Unity-Dev** [comment]
tomorrow decides the fate of this PR

**Comment by Just-a-Unity-Dev** [comment]
no i'm serious i will work on this whenever i can

**Comment by AJCM-git** [comment]
You should close it and reopen once you have time if you think you wont be able to get back to it for a while

**Pull request closed without merging**
