### PR TITLE
Adds TaxiBot

### PR DESCRIPTION
**Pull request by FillerVK**
## About the PR

Added craftable TaxiBot. Its task is to ride around the station and drive the crew to their place of assignment in a few seconds, thanks to its high speed.
Crafting recipe:
 - Proximity Sensor
 - Borg head
 - Borg arm
 - 5 Steel

**Media**

https://github.com/space-wizards/space-station-14/assets/130583174/a12d517a-495e-4c79-bbde-59410f1c6fe2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added craftable TaxiBot. Robotics can now construct autonomous, ghost-powered taxis to drive people around the station at high speed.

### CODE REVIEW

**Comment by lzk228** [comment]
ghost role, bruh

**Comment by Tunguso4ka** [comment]
> ghost role, bruh

more ghost roles to the spessmens.

**Comment by brainfood1183** [comment]
> ghost role, bruh

more ghost roles is a good thing so long as they avoid screwing over station.

**Comment by dmnct** [comment]
This is cool! I unironically wanted to be a Sapiented ATV in the past, just so I could do this

**Comment by moonheart08** [comment]
this is silly and i like it, ship it

**Pull request merged**
