### PR TITLE
Cull weapons and renames prototypes

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR 
I have discussed with some lads about culling weapons, most of them are unused or will be replaced with something else on the maps.
**Screenshots**

**Changelog**

:cl:
- remove: A lot of unused weapons have been removed.
- remove: Pie cannon no longer honks.
- add: Detective now has their trustworthy Inspector revolver.
- tweak: Armory crates now have WT550 instead of Drodz, Kammerer instead of Gladstone.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
It seems like the old suspicion spawners have old guns in them. You'll need to cull those or else all the old maps will error about it because the prototype for the spawner will be invalid.

**Comment by EmoGarbage404** [comment]
> It seems like the old suspicion spawners have old guns in them. You'll need to cull those or else all the old maps will error about it because the prototype for the spawner will be invalid.

actually, it seems like the suspicion spawners have been removed altogether. Some of the real old maps will need all those removed.

**Comment by metalgearsloth** [comment]
I deleted centcomm and moonrise for now to save time because I don't think they're in rotation but they should be brought back when we have proper tools for maintaining it.

**Comment by wrexbe** [comment]
This PR has become a piece in a different PR https://github.com/space-wizards/space-station-14/pull/8301

**Pull request closed without merging**
