### PR TITLE
Wall clicking

### LINKED ISSUE #22742: feature request: wall clicking
saw a server in ss13, where if you click on wall, you heard a sound and message in chat "you click that wall. its motionless" or something like that
dont remember if it was local message or people around could see that youre clicking walls

makes sense when youre checking for fake wall

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Click on the wall and it shows to you "You click the wall, it's motionless."

Resolves #22742

## Media

Screenshot_20240228_075716
Screenshot_20240228_075534

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Clicking on a wall will show appropriate popup message.

### CODE REVIEW

**Comment by botanySupremist** [comment]
Is there a way to disable this? Sounds like it could be annoying.

**Comment by UbaserB** [comment]
> Is there a way to disable this? Sounds like it could be annoying.

maybe shift+left click for both windows and walls?

**Comment by lzk228** [comment]
> Is there a way to disable this? Sounds like it could be annoying.

windows already have this even with annoying sound, so i dont think it would be annoying

**Comment by potato1234x** [comment]
it should be push the wall not click the wall

**Comment by MACMAN2003** [comment]
pushing on a wall should make the doom "unf" noise

**Comment by ps3moira** [comment]
Wouldn't it be "tapping" not "clicking"?

**Comment by Hmeister-real** [comment]
> Wouldn't it be "tapping" not "clicking"?

This, clicking sounds weirder than pressing or tapping

**Comment by TheShuEd** [comment]
It sounds useless and inconvenient.  It makes sense to knock on windows sometimes to attract the attention of the person on the other side.  but knocking on walls?

**Comment by TheShuEd** [comment]
at the very least, an option that requires additional keys should be implemented, either through the verbs menu

if the goal is to make the secret door more secret, I would also make the open button in the verbs menu.

**Pull request closed without merging**
