### PR TITLE
add ied

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
adds improvised explosive device crafting, somewhat similar to modular grenade but not using modular grenade

craft with a soda can, igniter, 30u of welding fuel and 5 lv

not using tg sprite because its incomprehensible and sus

maybe random timer too for funny who knows

depends on #20962

## Why / Balance
adds new way for resourceful syndies and revs to get stuff done (https://youtu.be/q7N78XbDk8o :trollface::trollface::trollface:)
crew might also make them for warops...

inb4 shitters, they already have welderbombing and this is even harder than that

## Technical details
added `MinSolution` and `SolutionEmpty` conditions for ied construction/deconstruction

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/89d4cb0a-ee14-4b63-bc33-251735b6c858

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: IEDs can be crafted in desperate times to make a small explosion.

### CODE REVIEW

**Comment by CatMagic1** [comment]
I knew you were gonna link that video. Kinda hope someone makes a better sprite tho

**Comment by deltanedas** [comment]
yeah still a codersprite but imo better than the mess currently in tg

**Comment by BolloTea** [comment]
This is true.  Someday R&D will give the opportunity to create a limit)

**Comment by Jackal298** [comment]
We need a pipe bomb
Пронин путешественица

**Comment by deltanedas** [comment]
wyci :trollface:

**Comment by JoeHammad1844** [comment]
i think the explosion radius should be increased to 3x3 instead of a plus. VIVAA

**Comment by Hmeister-fake** [comment]
Imo this is a great addition, next thing to add is molotovs.

**Comment by deltanedas** [comment]
> i think the explosion radius should be increased to 3x3 instead of a plus. VIVAA

dont know how to control the size

**Comment by JoeHammad1844** [comment]
> dont know how to control the shape of the explosion

i think you go into a private server, do the explosionui command and then tweak these values until it goes into a 3x3
image

**Comment by deltanedas** [comment]
new explosion values, now anywhere in the 3x3 you basically take the same damage

**Comment by CatMagic1** [comment]
image

**Comment by deltanedas** [comment]
> VIRTUAL ITEM YOU SHOULD NOT SEE THIS

too bad i do see this :trollface:

**Comment by Carolyn3114** [comment]
I'd love to see TTV's

**Comment by deltanedas** [comment]
ttv and single tank bombs out of scope

**Comment by Carolyn3114** [comment]
> ttv and single tank bombs out of scope

yeah I know, just saying it'd be awesome in the future

**Comment by JoeHammad1844** [comment]
>  new explosion values, now anywhere in the 3x3 you basically take the same damage

how much exactly? or is the intensisty the damage?

**Comment by deltanedas** [comment]
intensity affects damage the values visible are intensity

**Comment by deltanedas** [comment]
current damage will almost instantly crit an unarmoured urist

**Comment by JoeHammad1844** [comment]
okay based thats reasonable

**Comment by CatMagic1** [comment]
need this 👀 

right now!!!

**Comment by deltanedas** [comment]
@LankLTE merg

**Review by DrSmugleaf — APPROVED** [review]

**Comment by deltanedas** [comment]
:trollface:

**Pull request merged**
