### PR TITLE
Use hashcode comparison for string equality check

### PR DESCRIPTION
**Pull request by GreaseMonk**
Applies a tiny performance optimization for generation of the parallax generation which will be ran much more often in the future when resizing the game window

### CODE REVIEW

**Comment by PJB3005** [comment]
Doesn't calculating the hash code still have to iterate the string, so it wouldn't really be that much faster?

When I originally wrote this code we did store a CRC instead of a copy of the whole config file. The problem was that Mono ships their own version of `ICSharpCode.SharpZipLib` and it's ABI incompatible with the official one (gee thanks Mono), so I went and just made it a string comparison instead.

b8becf4a56cd7146df7630041c0c5988df9b14e2 is the commit in which I did that.

**Comment by GreaseMonk** [comment]
> Doesn't calculating the hash code still have to iterate the string, so it wouldn't really be that much faster?
> 
> When I originally wrote this code we did store a CRC instead of a copy of the whole config file. The problem was that Mono ships their own version of `ICSharpCode.SharpZipLib` and it's ABI incompatible with the official one (gee thanks Mono), so I went and just made it a string comparison instead.
> 
> [b8becf4](https://github.com/space-wizards/space-station-14/commit/b8becf4a56cd7146df7630041c0c5988df9b14e2) is the commit in which I did that.

You are right, it doesn't really matter, upon further research I found that hashcode may be the same in some cases even when the strings are different.

Closing this PR.

**Comment by PJB3005** [comment]
Oh, I should mention though. We're using .NET Core now so using CRCs should be totally fine now (no more Mono to be an issue).

**Comment by GreaseMonk** [comment]
I'll revert the CRC removal instead, because we do need this to be speedy when resizing the window.

**Pull request closed without merging**
