### PR TITLE
make ore processor craft 1 item instead of full stack

### LINKED ISSUE #10395: Ore processor requires you to mine 30 sheets worth of materials before you get to use any
## Description
Ore processor requires you to mine 30 sheets worth of materials before you get to use any. Let ore processor print individual sheets. I remember being confused by trying to print couple sheets and getting whole stacks instead. And with PR #10347 in effect it gonna take a good while before ore processor gets enough materials for whole stack. What this item count option is for, after all?

**Reproduction**
- Be salv
- Mine
- Enjoy non-clickable ore processor menu entries

**Screenshots**
Pictured: Chemlab needs just _one_ sheet of plasma for DexalinPlus. Yet salv gotta mine 29 extra plasma ore chunks before it's possible to make use of that plasma:
just_one_plasma

**Additional context**
Still dunno whenever mining is balanced now as per issue #8184, yet ore processor not letting you print that single sheet of glass is lame.

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

resolves #10395
## Why / Balance

dunno
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
this isnt an issue, with a single rock you get several stacks of each mat

**Comment by lzk228** [comment]
what

**Comment by deltanedas** [comment]
also this would take 1 billion years to print since its like 1s per item = 30s per stack

**Comment by lzk228** [comment]
ahh k, im done with linter errors so

**Comment by Rainbeon** [comment]
It's already closed but also fairly certain there are Parts upgrades that make the Ore Processor printing ratio/cost much better, which this would invalidate

**Pull request closed without merging**
