### PR TITLE
Animal masks

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

Seven new animal masks. Let the masquerade be more diverse.

**Media**
animal masks

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar

- add: Adds 7 new animal masks.

### CODE REVIEW

**Comment by PuroSlavKing** [comment]
**Hotline Miami 3 confirmed**

**Comment by Emisse** [comment]
can you add these to maint fluff spawner maybe

**Comment by Snowyypanda** [comment]
all what is left are the fursuits and we will have furries in ss14 ( make the animal masks flammable for science )

**Comment by Nimfar11** [comment]
> can you add these to maint fluff spawner maybe

done

**Pull request merged**
