### PR TITLE
Sign Resprite

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Resprites most wall signs to a consistent style + adds a few more that were missing.

## Why / Balance

Signs were sourced from 2 codebases and had wildly different styles. This new set combines the best of both and makes them significantly more legible and thematic.

## Media

sign-export
image
image
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Resprited wall signs.

### CODE REVIEW

**Comment by Hrosts** [comment]
Maybe I'm hallucinating, but the upper and lower margins look weird when it's planted on a wall.

**Comment by IProduceWidgets** [comment]
> Maybe I'm hallucinating, but the upper and lower margins look weird when it's planted on a wall.

I'm pretty sure this is because wall sprites aren't actually centered and have a slight perspective for shading.

**Comment by Emisse** [comment]
can you add one for cryo

**Comment by IamVelcroboy** [comment]
downstream, we made the arrows in the "Space" and " Pods" signs directional. Maybe want to consider that here? These, overall, look really nice though.

**Comment by ps3moira** [comment]
I suggest not removing all the smaller signs. They're used well for corners and a sign that's almost filling up the whole 32x32 wall looks bad.

**Comment by TurboTrackerss14** [comment]
99% of these are bangers but the salon sprite doesn't exactly get much information across due to the limited palette. 
Maybe just a big pair of scissors could work?

**Comment by EmoGarbage404** [comment]
> 99% of these are bangers but the salon sprite doesn't exactly get much information across due to the limited palette. Maybe just a big pair of scissors could work?

i'll lay down and die before you dare knock the glorious pompadour sign.

**Comment by Tayrtahn** [comment]
Maybe give the pompadour guy an eye to help it read as a side view? I have to admit that I found it hard to figure out what I was looking at in that one.

**Comment by EmoGarbage404** [comment]
image
 redone salon sign

**Comment by Tayrtahn** [comment]
Rip pompadour guy, you will be missed.

But yeah, the new sign is better.

**Pull request merged**
