### PR TITLE
Accessibility reprite for the Juggernaut suit, sec suit, and warden suit(Sprites by Gtheglorious)

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

I implemented Gtheglorious' resprites for the juggernaut suit, sec suit, and warden suit, at their request/permission
## Why / Balance

The main reason for this change was accessibilty. It was hard to distinguish sec suits and nukie suits.
https://discord.com/channels/310555209753690112/1183837215743299584
## Technical details

nuh
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Jugsuit
wardensuit
image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
Note your CL is formated wrong, you need the :cl: emoji and to have every tweak in a list

Should look like this
```
:cl:
- tweak: The juggernaut suit, security hardsuit and warden hardsuit have recieved a resprite.
```

**Comment by Boaz1111** [comment]
> Note your CL is formated wrong, you need the 🆑 emoji and to have every changelog in a list
> 
> Should look like this
> 
> ```
> :cl:
> - tweak: The juggernaut suit, security hardsuit and warden hardsuit have recieved a resprite.
> ```

ah, changelog's always confused me, but I see now, thanks!

**Comment by SomeAspy** [comment]
Not sure if you are looking for feedback here, but here goes:
On the first sprite, something that really strikes me as odd is the back. Specifically the green dots on the back, and the, uh, rear end. I think it might benefit from less, "pop"
On the other hand, Perhaps the eyes might look better with that green.

I think the other 2 sprites look really great though.

**Comment by Gtheglorious** [comment]
> Not sure if you are looking for feedback here, but here goes: On the first sprite, something that really strikes me as odd is the back. Specifically the green dots on the back, and the, uh, rear end. I think it might benefit from less, "pop" On the other hand, Perhaps the eyes might look better with that green.
> 
> I think the other 2 sprites look really great though.

The "pop" is intentional (the original was only a tiny bit less pronounced). Cool guys don't look at explosions. Cool guys need protection from back facing explosives.

**Pull request merged**
