### PR TITLE
Latejoin traitors

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Lets latejoiners be traitor. Closes https://github.com/space-wizards/space-station-14/issues/9211. Also fixes a broken objective icon.

**Changelog**

:cl: Rane
- tweak: Latejoiners are now eligible for traitor.
- fix: Fixed missing kill objective icon.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
how to make mirrorcult code dynamic part 1 of 101:

**Comment by Elijahrane** [comment]
Merged, tested locally to verify everything still works. If you are testing locally yourself please be careful to remember https://github.com/space-wizards/space-station-14/issues/8952. ```setgamepreset traitor``` does not work. You need to ```setgamepreset secret``` and restart until it picks traitor.

**Comment by keronshb** [comment]
There should probably also be a way to keep track of people who ghosted (and cannot return from body) to also subtract from the count. Otherwise it looks fine.

**Comment by Elijahrane** [comment]
> There should probably also be a way to keep track of people who ghosted (and cannot return from body) to also subtract from the count. Otherwise it looks fine.

This is intended. Both traitors and non traitors will be removed from the round at roughly the same rate, so we just want to base it off of how many people have joined conventionally total

**Comment by keronshb** [comment]
> > There should probably also be a way to keep track of people who ghosted (and cannot return from body) to also subtract from the count. Otherwise it looks fine.
> 
> This is intended. Both traitors and non traitors will be removed from the round at roughly the same rate, so we just want to base it off of how many people have joined conventionally total

That's fine then, I just remember dynamic had something similar to check when people were removed.

**Comment by Elijahrane** [comment]
Would like to comment that I've had this on nyano for a day now without issues, so it's been tested in an actual server

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
