### PR TITLE
carpsuit and iansuit revival

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
revival of #17346

adds ian onesie and carp suit from tg, but tweaked it a bit
- carp suit is no longer a hardsuit and doesnt have positive/negative defense weird stuff
- carp suit is not as stupidly fast as it was before
- make sprites more consistent and have no holes showing jumpsuit

ian suit is f5 only

carp suit can be bought in uplink for 4tc along with some carp plushies...

## Why / Balance
fishe
doggy

## Technical details
no

## Media

valid

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: The Syndicate is now offering carp suit bundles to its operatives to improve morale.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
test fails are not erroneous

**Comment by Jackal298** [comment]
can make Ian costume spawn in head of staff locker with a certain percentage?

**Comment by lzk228** [comment]
> can make Ian costume spawn in head of personnel locker with a certain percentage?

it would be better to get it in other way
we now have ian backpack, and if it spawns, hop wears only it
maybe make ian costume more affordable

**Comment by deltanedas** [comment]
hops will powergame the 10% speed for sure

**Comment by deltanedas** [comment]
@EmoGarbage404 test pass

**Review by mirrorcult — COMMENTED** [review]
not sure i like the speed modifiers on these, just dont see a reason to have them. inevitable to get powergamed and i dont think it adds much

**Comment by deltanedas** [comment]
yeah i think its too powergamey just had them in from old pr

**Comment by deltanedas** [comment]
@mirrorcult removed speed

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
