### PR TITLE
CMO gets externals access, like paramedic

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

paramedic has externals access, but CMO doesn't, this fixes that

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

No changelog

### CODE REVIEW

**Comment by Emisse** [comment]
cmo doesnt have externals access because thats not part of his job

**Comment by metalgearsloth** [comment]
Even paramedic having it is sussy

**Comment by JoeHammad1844** [comment]
so CMO cant access EVA or any airlocks except the all access ones, even sec gets externals access

**Comment by JoeHammad1844** [comment]
or the cargo shuttle doors

**Pull request closed without merging**
