### PR TITLE
Add rings (Salvage loot real)!

### PR DESCRIPTION
**Pull request by beck-thompson**
## About the PR

Add 6 rings and a ring box to the game. Specifically, gold and silver rings, diamond rings, and gem rings.

The standard rings and the diamond rings are craftable in the autolathe but the gem rings are salvage exclusive.

## Why / Balance

Two main reasons:
1.) People keep having their characters get married and there are no rings. Bad!
2.) New rare salvage loot is fun!

## Media

image
Nukie and capt got married!!

Screenshot 2024-08-23 104117
Ignore the broken texture for the ring box. All box textures are like that I'm going to make a fix soon.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Beck Thompson
- add: Gold and silver ring, gold and silver diamond ring, gold and silver gem ring. They all can be obtained in salvage loot pools.

### CODE REVIEW

**Comment by TurboTrackerss14** [comment]
https://wiki.spacestation14.com/wiki/Server_Rules#No_sexual_content/themes,_including_erotic_roleplay_(ERP)_and_no_shock_content

"In-game romantic relationships should not become the focus of the game for you and anyone else involved. "

**Comment by foob1** [comment]
> https://wiki.spacestation14.com/wiki/Server_Rules#No_sexual_content/themes,_including_erotic_roleplay_(ERP)_and_no_shock_content
> 
> 
> 
> "In-game romantic relationships should not become the focus of the game for you and anyone else involved. "

A marriage ring doesn't focus your gameplay experience on an in-game romantic relation for you or anyone else, it's literally just a cosmetic ring item

**Comment by TurboTrackerss14** [comment]
> > https://wiki.spacestation14.com/wiki/Server_Rules#No_sexual_content/themes,_including_erotic_roleplay_(ERP)_and_no_shock_content
> > "In-game romantic relationships should not become the focus of the game for you and anyone else involved. "
> 
> A marriage ring doesn't focus a significant portion of the round on an in-game romantic relationship for you or anyone else, it's literally just a cosmetic ring item

If the intent of the PR was to add multiple jewelry items for cosmetics I would have no issue with it. 
But the commentary on the pr, especially the PR title and images makes it hard not to see it as "marriage RP bait" which can and has caused administration problems for us. 

Its fine for salvage loot but putting a rulebreak twist in your pr is just asking for that input to be given to you.

**Comment by beck-thompson** [comment]
> If the intent of the PR was to add multiple jewelry items for cosmetics I would have no issue with it.
> But the commentary on the pr, especially the PR title and images makes it hard not to see it as "marriage RP bait" which can and has caused administration problems for us.
> 
> Its fine for salvage loot but putting a rulebreak twist in your pr is just asking for that input to be given to you.

I tried to talk to you about this on discord but you never responded. Do you want me to post my message here?

**Comment by retequizzle** [comment]
only if we add some shitty version of this and force tablevaulting sounds to be the jump sounds from sonic

https://www.youtube.com/watch?v=G-i8HYi1QH0

turbo's already brought up the weird romance implications that we'd like to avoid but conversely i don't think there's a single SS14 branch that's beating the furry allegations so may as well lean into the sonic shitposting a bit while i'm here

**Comment by slarticodefast** [comment]
I brought it up for discussion with the admins.
Could you add an item description to the rings? Currently the examination text is empty.

**Comment by ARMOKS** [comment]
If this gets added I will kill and meatspike married couples in front of each other

**Comment by JIPDawg** [comment]
> If this gets added I will kill and meatspike married couples in front of each other

All the more reason to add it then.

**Comment by coolsurf6** [comment]
I feel like stuff like this should really only be on maaaaaybe MRP but mostly HRP servers. Just doesn't seem fit for upstream.

**Comment by slarticodefast** [comment]
Hey, I brought this up for discussion with the admins and maintainers and we would ask you to remove them from the chapel inventory and the lathe, but keep them as rare salvage loot. The main reason for this is the "In-game romantic relationships should not become the focus of the game for you and anyone else involved" server rule.

Furthermore we have these absolutely vital requests for follow-up PRs:
- A rare cursed ring that turns you invisible, but makes ghosts able to haunt/punch you
- A type of ring that drops from your inventory with a legally ditinct coin sound when you die 
- Have salvage corpses sometimes wear them in their glove slot, possibly with an inscription for the examination text

**Comment by beck-thompson** [comment]
Makes sense! You didn't mention it but I also removed the ring box because it seems like it would also break that rule (And probably more than the rest 😆). Love the suggestions and will definitely make another PR with those ideas!

**Pull request merged**
