### PR TITLE
Disposal Unit Tweak

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changed disposal units

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:Alekshhh
- tweak: Changed disposal units visually

### CODE REVIEW

**Comment by Emisse** [comment]
looks a bit blurry to me

**Comment by CatMagic1** [comment]
The current one is pretty

I don't see why it needs a resprite

**Comment by Alekshhh** [comment]
it's on the "needs resprite" list, so talk to the art directors about it not needing one
I will be editing the contrast as it is low
how are the colors amplified they've been desaturated and even completely greyscaled, unless you're referring to the mailing unit I have no clue what you're on about

**Comment by UbaserB** [comment]
the colour of the yellow is so.. unappealing

**Comment by Alekshhh** [comment]
it's not meant to be flashy, it wouldn't fit the art direction of the game otherwise
unless emo or flare say otherwise

**Comment by UbaserB** [comment]
> it's not meant to be flashy, it wouldn't fit the art direction of the game otherwise unless emo or flare say otherwise

imo its really eyecatching and bright lol... thats why i said that

**Comment by Alekshhh** [comment]
yeah it's a warning line, it should be bright and eyecatching
you can't say it's both unappealing and eyecatching, either or

**Comment by UbaserB** [comment]
IMO i'd keep the hazard line bright, but then everything above it a different colour/more dull/etc

**Comment by Alekshhh** [comment]
what

**Comment by UbaserB** [comment]
image
idk laziest sketch ever

**Comment by Alekshhh** [comment]
I'll play around with it later but I'm not feeling it personally

**Comment by EmoGarbage404** [comment]
tfw people keep dogpiling onto the image posted at the very beginning unaware of the fact that it's being iterated on and changed.

**Comment by deltanedas** [comment]
i saw this while testing stuff god damn the old ones better

**Comment by Buldinn** [comment]
Good effort. Nice try.

**Comment by MACMAN2003** [comment]
i prefer the old ones, they stood out more.

**Comment by UbaserB** [comment]
The idea these disposals bins were going for is great, but i really am not a big fan of the execution.

**Pull request merged**
