### PR TITLE
Reapply "Remove some BUI boilerplate" (#30214)

### PR DESCRIPTION
**Pull request by metalgearsloth**
I added inject dependencies back into PA and gas tank which got killed in master merges. I did not see any other issues raised.

Fixes https://github.com/space-wizards/space-station-14/issues/30201

### CODE REVIEW

**Comment by JIPDawg** [comment]
Think the rcd issue may have also been the result of this.

**Comment by metalgearsloth** [comment]
> Think the rcd issue may have also been the result of this. #30201

Cheers I'll take a look.

**Comment by Brandon-Huu** [comment]
I made these fixes before they even reverted the PR.

You also missed one I think

**Comment by metalgearsloth** [comment]
SC mentioned war declarator also I don't follow.

**Comment by Brandon-Huu** [comment]
https://github.com/space-wizards/space-station-14/pull/30206

**Pull request merged**
