### PR TITLE
magnetize ore box

### PR DESCRIPTION
**Pull request by n00kii**
## About the PR

the ore box now has a magnet in it, so it can pick up ore while being dragged across the ground. artifact fragments have also been added to its whitelist

a toggle is also now available for anything with magnetized pickup. ore boxes default to magnet disabled, for performance 
## Why / Balance

nobody ever uses the ore box. dumping all your ore on the ground takes the same amount of time, and salvs would rather use ore bags to transport ores from ship to station, since you can hold three at a time. 

now, salvs can bring ore boxes on expeds as a sidegrade to their normal ore bags. its only a sidegrade because even though you get a bit more ore space, you lose a hand (or tail) slot, become slower, and have to deal with the awkwardness of lugging the box through mining tunnels, rocks, and trees. because of this, magnet box does not encroach upon the usefulness of the orebag of holding

(considering slightly increasing ore box space as well)

## Technical details

`MagnetizePickupComponent` has a datafield, `slotFlags` that was used for making sure an entity is in the correct inventory slot before enabling magnetism. i just slightly modified the system to consider `SlotFlags.NONE` as a bypass to the inventory check
## Media

https://github.com/space-wizards/space-station-14/assets/57325298/c67406cb-6c01-425a-9cb8-f2431b7df53b

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Magnetized the ore box. Storage magnets can now be toggled.

### CODE REVIEW

**Comment by Golinth** [comment]
> what about making it a T1-T2 box that RnD can research?

The box is rare enough as is, and it’s bad enough now that I don’t think adding a marginally better upgrade (one that comes default in TG station I believe) as a t2 tech is worth it, except to pad science out. (Plus this means it could technically be used for Ripley mining in the future).

maybe in the future, a “box of holding” could be added, but the box has so much storage I really don’t think that it’s necessary

**Comment by osjarw** [comment]
If you're adding fragments to the whitelist in this PR, we might as well add salt as well. 
From what I recall, currently salt doesn't go in ore boxes.

**Comment by EmoGarbage404** [comment]
I think this is a really weird change tbh. I'd rather see the ore bags nerfed in terms of being effective bulk storage options than making the ore box effectively one big ore bag. The primary utility of ore bags should come from the magnet pickup ability, not the simple fact that they let you carry a bunch of stuff.

**Comment by n00kii** [comment]
ore bags of holding are already a t1 tech though. by the time sci has it, salv should already be back with the materials to print them. and if sci is slacking, it would be nice to have another option that doesn't rely on them, even if the best option does rely on them

**Comment by n00kii** [comment]
> If you're adding fragments to the whitelist in this PR, we might as well add salt as well. From what I recall, currently salt doesn't go in ore boxes.

that's weird, the whitelist should fully match ore bags now but i'll check

**Comment by n00kii** [comment]
> I think this is a really weird change tbh. I'd rather see the ore bags nerfed in terms of being effective bulk storage options than making the ore box effectively one big ore bag. The primary utility of ore bags should come from the magnet pickup ability, not the simple fact that they let you carry a bunch of stuff.

this would make mining expeds feel worse than they already do; its not super engaging to click rocks for ten minutes, and forcing players to have to walk back and forth between the shuttle more doesn't help, and it would decrease the effective mining yield from expeds. it also still doesnt incentive ore box usage, since players will just opt for the unlimited floor storage

**Comment by osjarw** [comment]
> > If you're adding fragments to the whitelist in this PR, we might as well add salt as well. From what I recall, currently salt doesn't go in ore boxes.
> 
> that's weird, the whitelist should fully match ore bags now but i'll check

Tested this just now, apparently I was wrong...
I swear there were 2 mineable things that didn't go in some sort of ore container, besides the machine at cargo, can't remember the name right now...

**Review by lzk228 — COMMENTED** [review]
isnt it would be better to set default slotFlags to null?

**Comment by metalgearsloth** [comment]
This needs a profile and also code supporting it or it's going to be too expensive.

**Comment by dvir001** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/711

**Comment by n00kii** [comment]
> isnt it would be better to set default slotFlags to null?

still need the bypass condition code, since the old code has a guard clause that enforces magnetic entity is in an inventory slot

**Comment by n00kii** [comment]
> This needs a profile and also code supporting it or it's going to be too expensive.

new to this codebase, could you elaborate a bit on what you mean by profile? also, are you implying that its any more expensive than players wearing orebags normally? id think the toggle suggested by dvir would be sufficient if performance is a concern

**Comment by RiceMar1244** [comment]
Going to be entirely honest, I don't want to go mining and see my fellow miners casually dragging a massive crate around. Salv drags around enough intended-to-be-stationary equipment anyway

**Comment by n00kii** [comment]
> Going to be entirely honest, I don't want to go mining and see my fellow miners casually dragging a massive crate around. Salv drags around enough intended-to-be-stationary equipment anyway

all this pr intends to do is open up more options. the box isnt't strictly better or worse than just using a bag, just tuned to different priorities. you can always discuss your preferred mining strategies with your partners

**Comment by RiceMar1244** [comment]
> > Going to be entirely honest, I don't want to go mining and see my fellow miners casually dragging a massive crate around. Salv drags around enough intended-to-be-stationary equipment anyway
> 
> all this pr intends to do is open up more options. the box isnt't strictly better or worse than just using a bag, just tuned to different priorities. you can always discuss your preferred mining strategies with your partners

I wont pester you about this, but it doesnt really feel like this needs those kinds of options. If the point of the box is being a stationary deposit that the whole salv team can rely on, then even one of them wanting to drag it around is a problem. Also, if alternatively everybody decides they want to individually do this, then you have three people dragging around three different large crates.
And as far as communication, youll need some luck convincing any of them NOT to unanchor and drag the free stationary gear. They kind of look at you weird if you ask them if we can please just leave the expedition console where it is for once.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
As I said above except now more visible.

**Comment by TheShuEd** [comment]
are you going back to the PR?
I see you asked a question, but considering there's been no progress for three months.....

**Comment by n00kii** [comment]
maybe another time

**Pull request closed without merging**
