### PR TITLE
Add clown emergency oxygen tank

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Updates the clown's emergency oxygen tank for one with 95% oxygen and 5% nitrous oxide.
No nitrogen version since slime people are immune to nitrous oxide effects.

Testing shows that it provides sufficient oxygen, while not providing enough nitrous oxide to fall asleep, only enough to laugh occasionally.

(I forgot that animal tank visuals were a thing, so I have used the standard emergency oxygen tank for those. I can take a crack at those later, or someone else can if they are inclined.)

## Why / Balance

This will guarantee that at least one person will laugh at the clown's antics during evac.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

funny_gas

**Changelog**

:cl:
- add: Added a funny oxygen tank for the clown

### CODE REVIEW

**Comment by CatMagic1** [comment]
> This will guarantee that at least one person will laugh at the clown's antics* during evac.

*War crimes

**Comment by K-Dynamic** [comment]
Output pressure is 21.3 kpa on pure oxygen tanks, it's the same here despite 5% n2o.

Does going below 21.3 kpa oxygen cause suffocation?

**Comment by themias** [comment]
> Output pressure is 21.3 kpa on pure oxygen tanks, it's the same here despite 5% n2o.
> 
> Does going below 21.3 kpa oxygen cause suffocation?

Good catch. I've just tested again, and it looks like there's zero asphyxiation damage after going through a few of these, so it looks like it is enough. I can up the numbers a little bit if we want to be safe.

**Comment by deltanedas** [comment]
at 20C 18kpa is fully breathable on pure oxygen

**Comment by K-Dynamic** [comment]
> at 20C 18kpa is fully breathable on pure oxygen

Interesting, time to tune down the dials on our tanks and get another minute of free air :trollface:

**Comment by deltanedas** [comment]
yes.

**Pull request merged**
