### PR TITLE
Update Snowasis

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Updates Snowasis for the holiday.

- Adds a lighttube box / crate / cargo order for red and green light tubes for the holidays.
image
image
image

- Adds reindeer. They would have better animation states, but the system is slighty borked for AI, so they prance unless someone wants to fix that before crimmas. Also for #30974
reindeer
(Woops the left-going animation was backwards, since fixed))

- Adds a spawner for the gingerbread man, makes it a non-antag crewaligned ai/ghostrole, ~~and also makes it dwarf sized~~.
image

## Why / Balance

Christmas

## Technical details

My apologies for the extra non-mapping changes here, but they're all holiday themed and I needed em mapped as I am going away for a week and may not be able to follow many Prs closely.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Reindeer.
- add: the legally distinct cookie monster.
- add: cargo order for holiday light tubes.

### CODE REVIEW

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
i approve the mapping portion of this pr but dont have time to look at other stuff until tomorrow

**Comment by Flareguy** [comment]
Please do not make gingerbread men dwarf-sized. We don't need more ugly pixel scrunching.

**Comment by IProduceWidgets** [comment]
removed the sprite scaling.

**Review by slarticodefast — APPROVED** [review]
Approving the code part of this PR (I have no knowledge of mapping).
Maybe this can be hotfixed so we get it into the game in time.
Reminder not to use GitHubs rebase function in that case because it will include other commits.

**Pull request merged**
