### PR TITLE
Fix game.role_timers not effecting the antag menu

### LINKED ISSUE #21404: Disable Role TImers CVAR should effect Nuclear Operative Antag Timer Aswell
## Description
There is a cvar dedicated to disabling job/role timers, but this doesn't effect antag role timers that were recently implemented specifically for nuclear operatives. I believe it should, or there should be a new cvar to disable their role timers. Not all servers or forks may want the role timers for nuclear operatives, and it should be possible to disable them easily. Additionally, it seems as though this CVAR should effect them too.

**Reproduction**
1) Have an account with no play time
2) set the cvar game.role_timers to false
3) Be unable to select the nuclear operative positions

**Screenshots**
I don't think this requires a screenshot, but I'll gladly provide one upon request.

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Closes #21404

The server checked this fine and would let you join correctly as the antag. Just the client prevented you.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by PJB3005** [comment]
This doesn't even need to be part of the admin changelog.

**Comment by VasilisThePikachu** [comment]
> This doesn't even need to be part of the admin changelog.

Felt like it should for other servers.

**Comment by PJB3005** [comment]
The admin changelog is meant for game admins, not server operators.

**Comment by VasilisThePikachu** [comment]
> The admin changelog is meant for game admins, not server operators.

okie changed

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Shouldn't you remove the same check in `IsAllowed` now because it's redundant?

**Review by PJB3005 — APPROVED** [review]

**Pull request merged**
