### PR TITLE
Nukies will be able to buy carp

### PR DESCRIPTION
**Pull request by AndrewEyeke**
## About the PR
Nuclear Operatives will be able to buy carps.

## Why / Balance
Nuclear Operatives should be able to buy carps for fishops.

:cl:
- add: Nuclear Operatives will be able to buy carps. They are limited to 10 per operative.

### CODE REVIEW

**Comment by Emisse** [comment]
why

**Comment by AndrewEyeke** [comment]
i feel like we are missing a new nukies strat and fishops might be able to fix that! also i love carps.

**Comment by LankLTE** [comment]
Fish ops used to exist, they were removed for a reason

**Comment by LankLTE** [comment]
Fish ops existed and were broken becuase each nukie getting 20 fish was effectively unstoppable, so they were nerfed to 3 TC but this made them useless for normal syndies as well, so they were reverted to 2 and blacklisted from nukies. Unless you have some other change I don’t think this is a good idea

**Comment by deltanedas** [comment]
they were made 3 tc and blacklisted in the same pr, reverted to 2tc much later

**Comment by LankLTE** [comment]
> they were made 3 tc and blacklisted in the same pr, reverted to 2tc much later

The revert still shows that they don't really work on syndies at 3TC so, and doesn't change the fact that 2TC fishops is broken

**Comment by deltanedas** [comment]
perhaps different listings for syndies and nukies...

**Comment by AndrewEyeke** [comment]
okay i see your point LankLTE, so i reduced the stock to 10 carps for each operative.

**Comment by lzk228** [comment]
what about make a new, expensive carp, that would be available only for nukie

**Comment by deltanedas** [comment]
noob stealing my idea :trollface:

**Comment by LankLTE** [comment]
> okay i see your point LankLTE, so i reduced the stock to 10 carps for each operative.

Honestly this was like the last solution I would’ve thought of- this might still be bad because you have like 40-60 carp with them still having enough to buy guns, but I’m down to try it if nobody has any huge concerns

**Comment by deltanedas** [comment]
if it doesnt work out it can always be made more expensive for nukies specifically so they cant do dragon ops via economy

**Pull request merged**
