### PR TITLE
Funny admin reagents

### PR DESCRIPTION
**Pull request by Veritius**
## About the PR
Funny reagents. One makes you immortal for 10 seconds per unit, the other turns you into a chicken.

## Why / Balance
Game balance is unaffected - these are for admins to have fun with.
I just think it's funny and admins can have a good time with it.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Veritius** [comment]
i don't understand why tests are failing

**Comment by asperger-sind** [comment]
cant the fluid anomaly and things like that potentially spawn ambrosia and give some nerd godmode, same with poltrium but thats funny.


also veritius de-greynamification noooooooooooo

**Comment by deltanedas** [comment]
fluid anom, mutations and strange pill should all be whitelisted

**Comment by Simyon264** [comment]
I think the fluid anomaly already uses a whitelist.

**Comment by Veritius** [comment]
so do strange pills
idfk how mutations work, botany is a mystery to me

**Comment by Veritius** [comment]
FUCK

**Comment by metalgearsloth** [comment]
Is this meant to be on the admin repo.

**Comment by GreyMario** [comment]
you would stash it there and deprive us of the glory of poultrium?

**Comment by Veritius** [comment]
this was funny for like a day

**Pull request closed without merging**
