### PR TITLE
Add water to water tiles.

### PR DESCRIPTION
**Pull request by Froffy025**
## About the PR

You can get water from water tiles just like if you were drawing from a sink. Also, they recharge.
## Why / Balance

I was thirsty. Salv can now fill their water bottles in a new place that seems to make sense.
## Technical details

Adds code from sink to water tiles to allow them to hold, dispense, and regenerate water. 
## Media

image
- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 Froffy
- add:  Water can now be scooped from water tiles, such as planetary rivers.

### CODE REVIEW

**Comment by MACMAN2003** [comment]
could also add trace amounts of things like iron and copper cause real life water streams aren't pure

**Comment by Emisse** [comment]
no thats just confusing game wise

**Comment by metalgearsloth** [comment]
This should really just be infinite water or at least handle the solution's removal rather than an arbitrary number.

**Comment by UbaserB** [comment]
> This should really just be infinite water or at least handle the solution's removal rather than an arbitrary number.

yeah but what about the manually mapped water sources like fland pool

**Comment by deltanedas** [comment]
just dont have them be drainable

if you cant pour water back in a pro can just steal the pool and run with it with no counter

**Comment by Tayrtahn** [comment]
The copy-paste is a little awkward. The solution shouldn't be named "tank", and it definitely doesn't need a SolutionContainerVisualizer.

**Comment by Froffy025** [comment]
the .yml appears to break when i use .inf as suggested online. i'll make it 9,999,999 water. is keeping the solution regeneration a lag concern with so many of these tiles at once..?

**Comment by deltanedas** [comment]
just make it so using a container on the tile fills it with water directly so no regeneration needed

**Comment by Froffy025** [comment]
> just make it so using a container on the tile fills it with water directly so no regeneration needed
ohh. how do i do that

**Comment by f0x-n3rd** [comment]
> could also add trace amounts of things like iron and copper cause real life water streams aren't pure

this could add a potential "gold panning" action hehe. ignore water, get a chance to get minerals.

**Comment by Froffy025** [comment]
redefining the salvage meta into the california gold rush

**Pull request merged**
