### PR TITLE
Addition of the Musician's Hardsuit

### PR DESCRIPTION
**Pull request by iNV3RT3D**
## About the PR

Adds the Musician Hardsuit, a hardsuit capable of playing music.

## Why / Balance

Tired of dragging around a DAW? Don't want an instrument using up valuable item slots? Then the Musician's Hardsuit is for you. Play music wherever you go, without the need for hands.

Now all of theatre has a hardsuit, instead of just clown and mime.

Musician Hardsuit inherits from the Clown Hardsuit, so balance changes to that will apply here.

Musician Hardsuit does take more to craft than the Digital Audio Workstation, so crafting the DAW may not become pointless.

Crafting:
   5x Cloth
   Eva Suit
   Eva Helmet
   DAW machine board
   (from this point on you add it to a physical entity)
   Keyed Instrument
   String Instrument
   Percussion Instrument
   Brass Instrument
   Woodwind Instrument
   5x Plasteel
   Use welder tool
   5x LV Cable
   Use screwdriver

## Technical details

I added a Tag to the DAW machine board, as I couldn't get the prototype construction step to work.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/89747313/489883df-1e4b-4323-9ecd-72f0ff8d8662

## Breaking changes

**Changelog**

:cl:
- add: Musician's Hardsuit can now be found in the crafting menu. Play music to your heart's content!

### CODE REVIEW

**Comment by Emisse** [comment]
we should move the hardsuit crafting to exosuit fabricator but porbably needs discussion

**Comment by K-Dynamic** [comment]
> we should move the hardsuit crafting to exosuit fabricator but porbably needs discussion

You mean like modsuits and crafting hardsuits in general?

**Comment by Kadeo64** [comment]
> we should move the hardsuit crafting to exosuit fabricator but porbably needs discussion

emo's already vetoed crafting hardsuits with science research so good luck

**Comment by brainfood1183** [comment]
Best hardsuit

**Comment by Catdere** [comment]
Based hardsuit

**Comment by LankLTE** [comment]
I think the daft punk helmet is super based, but I'm not really certain we want to start a trend of every service role having a craftable hardsuit- at least clown has the justification of allowing for space clownery.

**Comment by Catdere** [comment]
> I think the daft punk helmet is super based, but I'm not really certain we want to start a trend of every service role having a craftable hardsuit- at least clown has the justification of allowing for space clownery.

I think having theater tied together with hardsuits is a good idea. Their jobs are based around entertainment and entertainment is a job that can be done anywhere. even in space. I think other service jobs shouldn't get a hardsuit because their jobs have no use for them, an example of jobs that don't work is. Botanist, Chef, Bartender, Janitor* Librarian, and Lawyer.  None of these jobs could work in a Zero G external space environment.  

All I'm saying pretty much is the sub department of theater makes a little bit of sense for having suits.

**Comment by mbreton101** [comment]
It would be cool if the RGB helmet lights could change its colors based on the music tone being played. Either by a togglable Hud button, or be effected by an emag/emp. Although its probably pretty difficult to implement, and i wouldn't want someone to have an epilepsy seizures.

**Comment by metalgearsloth** [comment]
agree with emisse, get that moved first otherwise it's just an excess of fluff.

**Comment by Dutch-VanDerLinde** [comment]
@iNV3RT3D hello can i port this to harmony

**Pull request closed without merging**
