### PR TITLE
Revert Exterminator pending newmed/redesign

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

Reverts the Exterminator midround antag #19946, pending newmed and a redesign.

This removes all references and functionality of the Exterminator from the game.

## Why / Balance

1) The Exterminator code is incompatible with newmed due to utilizing non-standard .yaml inheritance. "unironically if I disable/depreciate terminators newmed would come out like 5 days earlier"
https://discord.com/channels/310555209753690112/1008709214006427689/1229307018800795678 

2) Current Exterminator design encourages murderboning, with equipment to take on the entire station. The initial design concept stated the intention was to have little to no crossfire, but the implementation in actual gameplay does not reflect this. 
https://discord.com/channels/310555209753690112/1008709214006427689/1229308591710928936
https://discord.com/channels/310555209753690112/1008709214006427689/1229407444200067092

3) Code directly references the Terminator, failing to utilize a replacement where it would be necessary for copyright reasons.

## Technical details

Reverts #19946, keeping some minor positive changes to spelling and formatting.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed Exterminators pending redesign. 🔥👍🔥

### CODE REVIEW

**Comment by Simyon264** [comment]
I feel like addressing the changes needed would be better than outright removing it.

**Comment by SlamBamActionman** [comment]
> I feel like addressing the changes needed would be better than outright removing it.

There were some design discussion attempts on Discord but the role was ruled as fundamentally flawed in its current design: https://discord.com/channels/310555209753690112/1008709214006427689/1229407699175870514

To list some quotes from Jezithyr's replies:
"They're a terribly designed antag that should have never gotten merged"
"the only reason they are even in the game is because they got yolo merged as a meme on christmas"
"their design is literally what I would do if someone asked me for a checklist to make the ultimate tider/murderbone role"
"fundamentally they are completely broken on the conceptual and design level. Balancing changes or nerfs/buffs will not fix that"
"they either need a complete redesign from scratch or removal IMO"

**Comment by FairlySadPanda** [comment]
Not to overload myself with work but I'd be down for working on this after I'm done with Pizza Delivery Critters. Which are basically exterminators but deliver pizza rather than pain.

**Comment by VasilisThePikachu** [comment]
> I feel like addressing the changes needed would be better than outright removing it.

I'm good with removing them and some other maints like jez also expressed similar interest.

They would need a whole refactor (same with revs not sure why they are even back still)

**Comment by deltanedas** [comment]
the exteriminator yaml is very evil
the internals saying terminator is fixed by an unmerged pr

**Comment by Killerqu00** [comment]
finally, exterminators are extremely metagameable and require lots of work before remerging imho

**Review by deltanedas — APPROVED** [review]

**Review by Brandon-Huu — APPROVED** [review]

**Comment by metalgearsloth** [comment]
I think commenting it out would be better at least as a reference point for when it gets added back in.

**Comment by SlamBamActionman** [comment]
> I think commenting it out would be better at least as a reference point for when it gets added back in.

Wouldn't this just leave unnecessary files and folders? The files & data is still in the repo history.

**Comment by IProduceWidgets** [comment]
I think its weird as a midround as is, but its definitely got utility as a smite. I've been looking at it as ss14's answer to [chrono legionaires. ](https://tgstation13.org/wiki/Chrono_Legionnaire)

**Comment by SlamBamActionman** [comment]
I re-added all Exterminator files, save for the .yml and .ftl files; .yml due to the aforementioned reasons, and .ftl since there's no good way to comment them out.

Since PopupBehavior.cs is usable outside the Exterminator I've added that it should be safe to uncomment, should someone find a use for it.

**Comment by Carmell0** [comment]
Removing terminators isn’t a fix. Keeping them in makes it so there’s pressure to fix them, and people actually care.

**Comment by deltanedas** [comment]
look at the yaml bro

**Comment by metalgearsloth** [comment]
Don't comment out the code files that's even worse, just the yaml, you also commented out a generic popupbehavior.

Just delete the whole thing instead at this point.

**Comment by SlamBamActionman** [comment]
> Don't comment out the code files that's even worse, just the yaml, you also commented out a generic popupbehavior.
> 
> Just delete the whole thing instead at this point.

That's why I asked for clarification (of which none was given). The generic popupbehavior was only used within the Terminator code, but I'll make sure it's re-added.

Just so that we're crystal clear, I'm now working on a commit that:
a) Includes the Terminator files
b) Comments out any .yaml to prevent spawning
c) Comments out .cs code that is used for spawning it (e.g. admin commands)

**Comment by Simyon264** [comment]
I'd keep the admin commands to spawn it. Just disable natural spawning as that is the major issue with murderboning.

**Comment by SlamBamActionman** [comment]
> I'd keep the admin commands to spawn it. Just disable natural spawning as that is the major issue with murderboning.

This was proposed in #27031 , but denied due to the system using a .yaml that will be difficult to port to newmed. This PR is both to get rid of the murderbone-role and prep for newmed.

**Comment by GamaYouNow** [comment]
R.I.P

**Pull request merged**
