### PR TITLE
Station AI

### PR DESCRIPTION
**Pull request by metalgearsloth**
Draft but indicates I'm working on it to avoid stepping on toes and I got over the stencilling hurdle.

image

I also tried a version using lighting to do occlusion but got told to go for tile-based instead so it's sitting on another branch if someone wants it.

image

TODO:
- [x] Doc. I know moony's doc exists but I just want to get a bare minimum MVP first so we can solve the biggest technical hurdles before trying to reinvent the wheel.
- [ ] Test out different static / using navmap as background.
- [x] Interactions. Namely being able to whitelist and handle it remotely. 
- [x] AI wires on doors.
- [x] APC interactions.
- [x] Spawning / loadout yaml setup.
- [x] Holocard (at least for MVP being able to card them to stop them I think is required).
- [x] Optimise the overlay because it's extremely slow atm.

Stuff like cameras / monitoring / laws / announcements / TTS I don't consider as required for an MVP and they're much easier to get through once we get past the initial cliff.

### CODE REVIEW

**Comment by bruhmogus** [comment]
oh dear god it's actually happening, i can confirm this will look sick asf

**Comment by notquitehadouken** [comment]
delicious image compression..,.

**Comment by TheDoctor1977** [comment]
I wonder how many comical camera blind spots this is going to reveal

**Comment by NULL882** [comment]
"AI open"

**Comment by Djungelskog2** [comment]
Can anyone link the moon AI doc? I can't find it

**Comment by Cojoke-dot** [comment]
> Can anyone link the moon AI doc? I can't find it

https://github.com/space-wizards/docs/pull/160

**Comment by Djungelskog2** [comment]
Oh, yea I don't really like that one, is that the one they are planning on going with?

**Comment by lule345** [comment]
ai just a week away

**Comment by TheDoctor1977** [comment]
> Oh, yea I don't really like that one, is that the one they are planning on going with?

Yeah, agree on this, no hate to the author but I really dislike the direction that proposal takes.

**Comment by Minigold07** [comment]
Are you planning to implement the feature that allows you to jump to any person by clicking on their name? I believe it would be a pain to always have to move to everyone who wants you to open a door for them manually.

**Comment by Emisse** [comment]
chat system doesnt support that yet but its doable with more chat refactoring

**Comment by KashRas2** [comment]
no way
Metalgear didnt delete something

**Comment by NakataRin** [comment]
This should have the "Holy Shit" lable in my opinion

**Comment by Djungelskog2** [comment]
What's MVP stand for? (in relation to this doc)

**Comment by coolsurf6** [comment]
> What's MVP stand for? (in relation to this doc)

Minimal Viable Product...?

**Comment by pigeonpeas** [comment]
so can we get Malf AI by qwertyquerty as the nuke theme for AI detonating it

**Comment by RedNiloc** [comment]
I was really hoping we could get that song, probably won't get it until MALF AI is an actual antag.

**Comment by lzk228** [comment]
tested a little
ai loadout window is empty
Screenshot_20240825_164252
after opening airlock action ui, my client just froze without any errors
Screenshot_20240825_164738

**Review by whateverusername0 — APPROVED** [review]

**Comment by Everturning** [comment]
AI loadout
>Screen display animation
>Neck slot

**Comment by TheDoctor1977** [comment]
> Screen display animation

I'm pretty sure in 13 your animation can be changed in-round, so this is probably unnecessary.

**Comment by whateverusername0** [comment]
image

unfathomably based. average self merge W :trollface:

**Comment by metalgearsloth** [comment]
> image
> 
> unfathomably based. another self merge W :trollface:

image

damn that's crazy

**Comment by mirrorcult** [comment]
image

**Comment by DTSpawn** [comment]
Latejoin on Bagel spawns on terminal with only 1 button (View Laws) and "without legs and arms". I can't move or interact

**Comment by lzk228** [comment]
> Latejoin on Bagel spawns on terminal with only 1 button (View Laws) and "without legs and arms". I can't move or interact

already listed in #31543

**Comment by vladkaron14R** [comment]
Cool, but I wanted more interaction with him from the crew and the Syndicate, as well as more features for him, I also wanted him to be updated

**Comment by ArtisticRoomba** [comment]
> Will turrets be added? I have sprites for them. I'll send them here, maybe someone will need them.

We do need turrets, otherwise any tider can hack in and unwrench the AI. The very first AI died in 2 minutes at the hands of them iirc. Which is just classic space station.

**Comment by Co0kie-GG** [comment]
Is there still a branch with no tile-based vision?

**Comment by metalgearsloth** [comment]
> Is there still a branch with no tile-based vision?

Not anymore but just needs to use the lighting shader in the overlay.

**Pull request merged**
