### PR TITLE
Make emitter use guncode

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 

**Media**

https://user-images.githubusercontent.com/98561806/210162327-d98f2db0-dbb7-4fbd-bab1-876357ceea39.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by mirrorcult** [comment]
video

**Comment by moonheart08** [comment]
Does this mean beam weapon emitter

**Comment by EmoGarbage404** [comment]
> Does this mean beam weapon emitter

uhh it means emitter uses code for guns instead of custom throwing shit.

**Review by mirrorcult — APPROVED** [review]

**Comment by metalgearsloth** [comment]
The timers will still need removing in future too.

**Comment by EmoGarbage404** [comment]
> The timers will still need removing in future too.

What would replace them?

**Pull request merged**
