### PR TITLE
Remove spacepens

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

This pr removes spacepens

Some more info here #17840

A bit of discussion here: 
https://discord.com/channels/310555209753690112/770682801607278632/1195274995044192339
https://discord.com/channels/310555209753690112/770682801607278632/1195322989714096148

## Why / Balance

Spacepens were added as a side effect to when spacings were more deadly and instantly vacuumed the air. Now that spacing is slower and less deadly space pens are no longer needed. Players should not use emergency hardsuits and/or evacuate to a safe area.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Due to Nanotrashen's budget cuts, Space pens are no longer supplied on the station.

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
May lord have mercy on my soul about the players reaction.

**Comment by Lomovar** [comment]
but removing spacepens will also remove the only source of barosine

**Comment by VasilisThePikachu** [comment]
> but removing spacepens will also remove the only source of barozine

Exactly!

**Comment by Yeah-I-listening-Hollywood-undead** [comment]
I think we need another way to get barozine. What about liquid anomaly and artifacts?

**Comment by icekot8** [comment]
I think FULLY removing these pens just doesn't seem right. I can see them as a rare or administrative item for various events, but to completely remove them....

**Comment by VasilisThePikachu** [comment]
> I think FULLY removing these pens just doesn't seem right. I can see them as a rare or administrative item for various events, but to completely remove them....

It was pointed out to me on discord. I will decide something soonish

**Comment by juliangiebel** [comment]
Space should be made more deadly again imo. Using your only space pen to survive an otherwise deadly situation is a really cool moment. Though taking one to walk around for more than a minute in space with how it is rn isn't.
This seems to me like the easy way out for a problem that's actually caused by a bigger issue.

**Comment by VasilisThePikachu** [comment]
> Space should be made more deadly again imo. Using your only space pen to survive an otherwise deadly situation is a really cool moment. Though taking one to walk around for more than a minute in space with how it is rn isn't. This seems to me like the easy way out for a problem that's actually caused by a bigger issue.

For anyone not on Discord. There was a discussion of buffing spacing as well. In theory, making space more deadly.

**Comment by TsjipTsjip** [comment]
CL should be one sentence, not two.

**Comment by deltanedas** [comment]
make spacing a threat instead of this

**Comment by VasilisThePikachu** [comment]
> make spacing a threat instead of this

What about both?

Hate to bring the "SS13 does this" card but ss13 does not have space pens. And space is far deadly there as well. We got emergency suits and I bearly see people using them, honestly neither do I see space medipens used much, coming back to the "space is not deadly enough" argument.People also like stacking space medipens to use as an attack weapon by mass injecting someone, which I guess is pretty creative.

**Comment by deltanedas** [comment]
i once got killed by a tider that had 7 spacepens after i stole ian therefore remove

**Comment by HoidC** [comment]
> > make spacing a threat instead of this
> 
> What about both?
> 
> Hate to bring the "SS13 does this" card but ss13 does not have space pens. And space is far deadly there as well. We got emergency suits and I bearly see people using them, honestly neither do I see space medipens used much, coming back to the "space is not deadly enough" argument.People also like stacking space medipens to use as an attack weapon by mass injecting someone, which I guess is pretty creative.
> 
> From what I see in this discussion. I need to buff the speed at which rooms leak air into space to make it more deadly. Which will most likely be a separate PR

we had super powerful space damage a couple years back and it was utterly miserable - anything gets blown up and half of the station dies, being in a spaced area was basically always a death sentence unless you had a bagged hardsuit or speedran a door/unpowered airlock before your death 

we do have emergency suits now

I do think spacing should be a little more dangerous but not to the same degree as it was

**Comment by forgotmyotheraccount** [comment]
this is the wrong conclusion to come to when faced with weak spacing

**Comment by QuietlyWhisper** [comment]
Even without pens spacing is still weak; I only use the pens when I get forcibly put into space either by teleportation etc etc

Buffing spacing/barotrauma is what you actually need to do, removing the pens only takes away a few extra seconds /shrug
People will still walk through spaced hallways

**Comment by VasilisThePikachu** [comment]
> Even without pens spacing is still weak; I only use the pens when I get forcibly put into space either by teleportation etc etc
> 
> Buffing spacing/barotrauma is what you actually need to do, removing the pens only takes away a few extra seconds /shrug People will still walk through spaced hallways / spacewalk if they need to / want to

Personally I think doing both is a good choice. Buffing spacing speed (messed a little with this. 0.15 looked like a good speed)

**Comment by Ilya246** [comment]
the problem about emergency suits is that you can often get out of the spacing in the time it takes you to get a spare emergency suit
they're only useful for being in spacings for prolonged periods of time, escaping large spaced areas, or traversing spaced areas

**Comment by FairlySadPanda** [comment]
This seems like a binary solution to a complicated problem to do with spacing balance. But the solution isn't to buff the deadliness of space (space is deadly due to suffocation and getting blasted by the local star, not exposure as per se - you don't even freeze in space, that's a trope based on a misunderstanding about how thermal radiation works).

If you're out in space and are forced to use a space pen, that should be a trip to medical afterwards etc just to remedy the damage you've endured, but you're not dead. That means the tiers would be

No equipment: you die
Space pen: you live but are incapacitated for a bit
Emergency internals: you live and might need minor treatment
Proper internals : fine

Fumbling to get your emergency internals working before suffocating is a core part of Space Station; it's why internals feature in so much official art for both 13 and 14. Need to move towards that rather than just removing the pen.

**Comment by Ilya246** [comment]
an alternative solution is to just make the pen more annoying to use or have a downside
the pen could stun you when its effect ends or if you overdose on it (pen has, say, 10 barozine, OD effect triggers below 3 and above 10 so you can't just chain them to prevent the stun)
though this would allow tiders to inject pens into people to stun them so might be sus

also to prevent pen spacewalking, and also discourage non-hardsuited people from being in space, we could make people without plating under them take radiation damage (from space) so you have to not go into space or get a hardsuit
this will also prevent salv from just being independent unless they obtain radiation medication

**Comment by juliangiebel** [comment]
What I think people forgot is that temperture damage was a big part of why the pen was needed. If you didn't use the pen but managed to get to safety it was likely that you'd still go into crit and quickly die because your body didn't heat up fast enough. The space pen contains a temperature stabilizing chemical which forces your temperature to normal.

**Comment by themias** [comment]
I know I'm just joining the bikeshed here, but maybe we could just make it harder to get space medipens? (and maybe energency medipens 👀)

tgstation has a Medipen Refiller machine, so maybe medipens could be balanced by Chemistry needing to fill them? (medifab could print empty ones with plastic.)

https://tgstation13.org/wiki/Machines#Medipen_Refiller

**Comment by Ilya246** [comment]
we could add some kind of emergency suit storage and map it on the walls of hallways in addition to random locker suits

**Comment by K-Dynamic** [comment]
> we could add some kind of emergency suit storage and map it on the walls of hallways in addition to random locker suits

Space osha demands (along with many other things) emergency eva at front entrance od every dept, and lockers seperated no more than two zones of firelocks away :trollface:

**Comment by IProduceWidgets** [comment]
I like space pens because (even with slowmos, please return us to fastmos I beg) its totally possible to die to a spacing if you aren't paying attention or moving with a purpose. Quick space pen use is one of the only things in the game you have to actively improve at.

**Comment by FairlySadPanda** [comment]
I'll add an implant that mimics the Pen to my Implant-O-Matic PR. Having to go to Medical to get an implant that does this adds some round interaction. Am thinking the implant would be made using the same reagent chem Space Pens use? And be one-time use.

**Comment by VasilisThePikachu** [comment]
Little findings on how space medipens effect survivability

With a lizard directly going out into space, from going into space and injecting to death with space medipen having:

Armour does not effect time (except hardsuits)

45 seconds crit 1:30 dead both barozine and lipozine
30 seconds crit 1:00 dead no barozine
42 seconds crit 1:25 dead no lipozine
30 seconds crit 1:00 dead nothing (not injecting)

Conclusion: 
Every 10u of barozine gives you 15 more seconds of space immunity
Space is too weak and not cold enough as lipo no effect
Pens with barozine let you survive 25 more seconds.

In my opinion, space needs a buff yes. 
But you are not gonna be dying in the spaced arrivals shuttle before you get a suit or get someone to help you.
You get 5 more seconds with internals on and not injecting

**Comment by asperger-sind** [comment]
I don't think space should be deadlier than it is right now, spacepens included.

Why? SS14 is a videogame first and foremost, death is of course intended, but what is a death that contributes to gameplay or can be considered "fun"?

Spacing and small spaced sections are common right now, despite weak space damage and spacepens being a common consumable, buffing space damage will lead to the relative "strength" of spacing methods increasing, leading to a possible shift in player thinking when it comes to playing antags that have easy spacing methods (see: ninja, traitor, nukie)
In other words, players will space even more.

Death by spacing is, I hope, agreeably one of the least "fun" methods of death, you're not dying in a fight, you're not dying to someone at all, you're not being enveloped by the plasmafire you just unleashed, you're not dying as a part of a joke, your death is caused by a passive gameplay element that something, or someone, caused in hopes of putting themselves into a better "active" gameplay position later on, as an example you'd see nukies spacing everything they can to create:

Spaced areas, constant firelock prying, the need to use hardsuits or emergency suits to traverse without taking passive damage, and more leads to...
1. Movement disruption. Aforementioned antags can extract a lot of value in "active" gameplay from this, the potential chase tailing the antag in question will be slowed, granting you more time and making some actions like relocating from point A to point B easier.
If you've ever played FTL you know why nebula sectors are good; you get more time to act and prepare to act.

2. Dead people don't act and take away time from others. If you kill a crewmember, they're dead until revival, the dead crewmember cannot act against you in any way and if they become alive that has a cost; medical resources and equipment, medical personnel, time from whoever is willing to heal you and or bring you to medbay.
You're taking away time, resources and player-work by racking up spacing kills and spacing damage, speaking of...

3. Spacing damage, you're wasting time and resources of the station by causing a spacing. It's easier to fight injured players as it is easier to steal from people buckled in medbeds, or medical doctors healing the person in a medbed, just as spacing damage denies resources that may eventually run out.

The list is obviously not complete, and there may be variable tactical or strategical advantages that spacing, and space damage grant the hypothetical antagonist, speaking of the list as a whole...

These are some pretty strong advantages already, despite being incomplete. And yet these are all "passive" gameplay factors that come out of spacing, I've intentionally left out tactical (e.g. spacing security before breaking in) and strategical (e.g. nukie plan dictates dedicated nukie goes out to space everything under the sun while avoiding direct combat) use cases of spacing, which is, reminder, extremely common.

Now then, back to dying, how does a death by spacing look like for the completely unprepared? The room they're in, assuming they're alone, gets spaced and they make an attempt to make it out or cry for help, in the end they get taxed for the majority of their health or die assuming they don't have a crowbar, or their room doesn't have an emergency suit, a scenario like this, despite sounding edge-case-y, could easily occur in maint.

Old spacing was brought up a lot here, but even if we had 1:1 old spacing from Packedstation in the modern day it would be miles worse because of the hardsuit nerfs, introduction of easier spacing methods, hardbombs, antagonists that play heavily on spacing (nukies came after spacing nerfs, let alone ninja), larger maps, materials being harder to carry in bulk.
The game not being balanced for low-pop Packed and Saltern to address the elephant in the room.
Old spacing would be a nightmare if it was reintroduced right now.

This doesn't sound way too bad in theory, yet in gameplay practice this unfolds very fast and is nowhere near the level of gameplay a death by fight with an antagonist brings even with our miserably low TTK.

Now then to conclude the spacing portion of this comment, I bring up the point that comes out of previous statements:

Spacing is strong as-is, it doesn't need buffs.

Intermission, I know this is a spacepen PR and all but there's tons of talk regarding space damage in general in the comments, besides the two are intertwined anyway, so? Massive spacing-related text wall. 
(it wont be brought up in the hypothetical spacing damage buff pr lol lmao)

Arguments again de-spacepenning the game:

1. The first bit of damage matters more than the last, if you use a spacepen you prevent a damage snowball from rolling over you because now you're slowed by damage and can't relocate to safety faster or fight as effectively making you die much faster.

2. Spacepens are a singular consumable, you can of course acquire more through looting dismissed survival boxes but for most players you only have one spacepen throughout a round that may last for 2 hours, this makes it valuable in the way that you most likely won't have another when you might need it if you used your granted one carelessly.

3. Callback to my earlier point, spacing is strong as-is, it doesn't need buffs, spacepens are a counterbalance to spacing, so don't upset the balance by removing spacepens.

4. Spacepens take some form of skill to use, it isn't a lot but going from bag > survival box > locating pen > using it > discarding shell during a scenario which invokes panic is a neat form of skill expression. (yes i throw away the box but most players don't)

5. Emergency suits are while common, are typically far from where you want them to be and require map knowledge as well as praying to the lord in hopes of there actually being an emergency suit, these go missing often.

6. Low space damage is fun and leads to better gameplay, you want to do things, not sit there tending to wounds after getting spaced or running back and forth to medbay, or being constantly hindered by a hardsuit, or just not going at all because you're 90% sure you'll die if you try to go through the spaced area. Spacepens strike a good balance where you may use the one-time consumable to temporarily ignore space damage which also leads to decision-making, it's good.

Proper understanding of your capabilities and the ability to act fast in a spaced area also allows for more gameplay opportunities as well leading to great scenarios like a secoff temporarily going outside the station into space to arrest a criminal without having a hardsuit, not having spacepens makes scenarios like these either limited to *exceptionally* good players, which isn't very good, or flat out impossible.

conclusion!!!!!!!!!!!!!!!!!!!!!!!! inb4 this makes zero sense i aint re-reading all'at!!!!!!!!!!!!!!!

**Comment by Admiral-Obvious-001** [comment]
Getting spaced is deadly enough as is if you're one of the unfortunate people to not have access to a crowbar and space pens barely help. The most common case in which spacing are deadly is shuttle bombings in my experience.

If anything I do think spacing should be mildly more dangerous but space pens also probably shouldn't be removed in absence of other changes.

**Comment by deltanedas** [comment]
> constant firelock prying,

solution to this part of spacing is remove firelocks they are so fucking annoying

**Comment by Rainbeon** [comment]
> 45 seconds crit 1:30 dead both barozine and lipozine 30 seconds crit 1:00 dead no barozine 42 seconds crit 1:25 dead no lipozine 30 seconds crit 1:00 dead nothing (not injecting)
> 
> Conclusion: Every 10u of barozine gives you 15 more seconds of space immunity (spacepen has 20u) Space is too weak in terms of damage and not cold enough as lipo no effect Pens with barozine let you survive 25 more seconds.

Why are you testing with Lipozine? Lipozine just makes you hungry, you'd wanna test with Leporazine.

**Comment by VasilisThePikachu** [comment]
> > 45 seconds crit 1:30 dead both barozine and lipozine 30 seconds crit 1:00 dead no barozine 42 seconds crit 1:25 dead no lipozine 30 seconds crit 1:00 dead nothing (not injecting)
> > Conclusion: Every 10u of barozine gives you 15 more seconds of space immunity (spacepen has 20u) Space is too weak in terms of damage and not cold enough as lipo no effect Pens with barozine let you survive 25 more seconds.
> 
> Why are you testing with Lipozine? Lipozine just makes you hungry, you'd wanna test with Leporazine.

Thats what I meant.

**Comment by K-Dynamic** [comment]
> > constant firelock prying,
> 
> solution to this part of spacing is remove firelocks they are so fucking annoying
> 
> other than that yeah good stuff

Unironically replace them with holofan projections

Then watch as power dies and entire station is spaced :trollface:

**Comment by K-Dynamic** [comment]
> I like space pens because (even with slowmos, please return us to fastmos I beg) its totally possible to die to a spacing if you aren't paying attention or moving with a purpose. Quick space pen use is one of the only things in the game you have to actively improve at.

Yes 2.2 blunt dmg/s isn't a lot at first but will kill you since:
A) you've probably taken other damage
B) you don't have bic or bruizine with you
C) you have to quickly get across the room with no guarantee of pressure on the other side
D) your movement speed gets fucked

**Comment by Anzarot121** [comment]
Slimes literally die in 30 seconds from barotrauma without a spacesuit or medipen. Now, you want to remove the most common possibility for them to survive and get to a place where there is at least 80 kPa of pressure in the atmosphere. They are already the most debuffed race in the game after they started to rot.

**Review by juliangiebel — APPROVED** [review]
The medical refactor that is in the works would bulldoze space pens anyway and change up how space damage works.
The one thing I think needs improving regardless is making depressurization a bit faster, but that's not part of this PR.

**Comment by asperger-sind** [comment]
> The medical refactor that is in the works would bulldoze space pens anyway and change up how space damage works. The one thing I think needs improving regardless is making depressurization a bit faster, but that's not part of this PR.

Medical refactor was in the works for a while now, neither is this the first time medical refactor has been rumored to being finished soon, I don't think it's a good thing to rely on the idea of changes being made being bulldozed by something that may come god knows when.

**Comment by VasilisThePikachu** [comment]
> > The medical refactor that is in the works would bulldoze space pens anyway and change up how space damage works. The one thing I think needs improving regardless is making depressurization a bit faster, but that's not part of this PR.
> 
> Medical refactor was in the works for a while now, neither is this the first time medical refactor has been rumored to being finished soon, I don't think it's a good thing to rely on the idea of changes being made being bulldozed by something that may come god knows when.

Medical refactor is in the works, development never stopped and you are welcome to help contribute #1938

It will come soon when people help with implementing it. It's one of the biggest reworks on this project so no shit its gonna take a while. It's all currently done just by one person as of now. Saying its coming "Soon" is a joke.

**Comment by VasilisThePikachu** [comment]
We did it reddit

**Comment by IlyaElDunaev** [comment]
32 votes against and no alternative. It would be nice if you could add an alternative before deleting something. You could just remove the negative effects of medipen...

**Comment by Emisse** [comment]
we dont want an alternative

**Comment by juliangiebel** [comment]
Github reactions on PRs is not a fucking voting system

**Comment by ArchPigeon** [comment]
> Github reactions on PRs is not a fucking voting system

sanest ss14 dev commentary

**Pull request merged**
