### PR TITLE
mug solution level visuals

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
adds solution level visuals to all of the mugs. required minor sprite tweaking.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Mugs now properly display the solutions inside of them.

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
rsis failing

**Comment by EmoGarbage404** [comment]
> rsis failing

Rsis arent from my pr.

**Comment by mirrorcult** [comment]
what da cringe

**Comment by EmoGarbage404** [comment]
> what da cringe

sloff

**Pull request merged**
