### PR TITLE
Lighthouse Station

### PR DESCRIPTION
**Pull request by OldDanceJacket**
## About the PR 
Initially created for the purpose of being an addition for Nyanotrasen, I've spent a considerable amount of time reviewing, discussing, and analyzing our current rotation of maps with players and mappers in preparation at attempting to make my own station. 

Lighthouse is a map with a sharp focus towards RP and stepping away from a heavy maintenance focus found on other maps and instead leaning towards visible side areas to, again, help condone and reinforce roleplay across the entire station. 
Every door is renamed, there is greenery all around, and every head department area is appropriately an office instead of a bedroom. 
There is no extreme gimmick or theme to be found, just less lights than your typical station, a lot more paper, and a few department related items to help give players, again, a more enjoyable roleplay environment.

**Screenshots**
image
image
image
image
image
image

I'd like to thank everyone who assisted in helping make the map, Emisse, Peptide, Schiene, etc... and I hope that there's not an obscene oversight to be found in the map.

I also acknowledge we have a fairly well sized rotation of maps at the moment, but am confident enough that while the station doesn't try to reinvent the wheel, it brings a number of design elements worth testing out.
_(also I absolutely loath trying to get a map render, I just spent an half an hour trying to get that to work)_

**Changelog**

:cl: ODJ
- add: Added Lighthouse, a fairly dimly lit station with a lot of offices and dorms.
- remove: Removed fun!

### CODE REVIEW

**Comment by Emisse** [comment]
screenshots look nice, ill look at it today and see if i can find any bugs

**Comment by OldDanceJacket** [comment]
image
Here's a proper render of the station in full. (thank you Rane)

**Comment by mirrorcult** [comment]
i don't think we should be doing adding more maps right now but if this does get added it should be replacing something in the rotation

**Comment by moonheart08** [comment]
> i don't think we should be adding more maps right now but if this does get added it should be replacing something in the rotation

I think it's perfectly fine for it to be added without replacing something, **under the condition** that more map maintenance tools are written before this happens.

**Comment by Emisse** [comment]
looked through the map to gather various thoughts/bug hunt. send them to jacket already. overall its very polished and unique and i think it would be a shame to reject it off the basis of too many maps

**Comment by Emisse** [comment]
if a map needs to be derotated though i can derotate one of mine for it

**Comment by OldDanceJacket** [comment]
I went through on another polish/update based off what @Emisse sent me, as well as fixing an issue pointed out by Rane. 
Thank you again!

**Comment by OldDanceJacket** [comment]
After over a week of tinkering, feedback from fellow mappers, and even playtesting on the Nyano branch; I've gone and updated this map to be up to and _byond_ our current mapping standards

Since initially putting up the map, more detail has been put into each room(decal work has been applied everywhere), buttons appropriately named to what they interact with, bugs and been hunted down and **dealt with**, access inspected on each and every door, job interactions evaluated and encouraged, roleplay tools and toys scattered about, alternative roleplay prospects(such as a news crew) have been implemented, all the while also including a unique map/game flow to the current rotation.

Currently this map supports alternative docking ports for ERT/Pirates/Nukies/Traders/Cargo Shuttle, and again, encourages interactions of departments outside of their norm, while also not being too tightly packed to be claustrophobic, and also, again, sports every door being named to help assist players in understanding where on the station they currently are.

Aside from needing to update the map to any new content or handling conflicting content changes, it can comfortably sit here for a proper evaluation.

Worth noting:  I don't claim ownership over this map either, I spent time making it but am more than comfortable with any other mapper coming along and editing it however they please. 
This was not a solo endeavor in making this and came from the support of other mappers such as Peptide, Emisse, and Emo, as well as feedback from numerous players. Which, again, I am extremely grateful for; This map is in it's best state.

**Comment by moonheart08** [comment]
lighthouse-0

**Review by Emisse — APPROVED** [review]

**Review by mirrorcult — CHANGES_REQUESTED** [review]
you have a lighthouse file in the root dir, remove that

**Pull request merged**
