### PR TITLE
SMES and substation require power cells as machine parts

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

This PR flags batteries as machine parts and makes the SMES and substation require batteries as part of their construction (instead of just capacitors). Only small, medium, high and hyper density power cells can be used at present (no potato powered devices)

The SMES now requires: 
- 1x Capacitor
- 4x Power Cell
- 10x HV Cable

The substation now requires: 
- 1x Capacitor
- 1x Power cell
- 5x MV Cable
- 5x HV Cable

Upgrading the batteries in the SMES and substation improves battery storage in the same manner that upgrading capacitors did prior. Upgrading the capacitors will now linearly improve the supply ramp rate of these devices instead

## Why / Balance

- It seems reasonable that devices that store can power would use/benefit from upgradable batteries (even if they are chemical-based batteries). This is most obvious use is in the substation, but in the SMES (lore-wise) the batteries could be used to help maintain a smooth power output to the magnetic field that contains the main charge
- It adds more diversity to the pool of parts used to build and upgrade machines
- Batteries are likely easier to upgrade than capacitors, and these devices need a lot of them

## Technical details

Refences to capacitors in the upgradablable battery component/system have been replaced with references to power cells. A new component has been added to handle upgrades to power supply ramping; UpgradePowerSystem handles the logic for this new component

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

- tweak: The SMES and substation now require power cells to construct

### CODE REVIEW

**Comment by Carolyn3114** [comment]
this doesn't make sense, why would APC's not require a cell, but SMES'es and substations do?

**Comment by chromiumboy** [comment]
> this doesn't make sense, why would APC's not require a cell, but SMES'es and substations do?

Adding power cells to APCs is still under discussion. And APCs not having batteries is not a reason that SMESes and substations should not

**Comment by Carolyn3114** [comment]
> > this doesn't make sense, why would APC's not require a cell, but SMES'es and substations do?
> 
> Adding power cells to APCs is still under discussion. And APCs not having batteries is not necessarily a good reason that SMESes and substations should not

currently APC's have no construction costs except a circuit board, which considering it also stores and outputs power, it should use a power cell or capacitor

**Comment by NancokPS2** [comment]
Is this decision due to realism or design concerns?    

Because realism wise, i don't think it makes any sense that a SMES, a device that stores MANY times more than even a hyper battery, needs one to work.  
  
I mean, i'm no electrician, but this makes no sense. A battery would store a Direct Current while something like a SMES would store an Alternate Current.    

  
If this is from a design standpoint, in your "Why" it says that it is "sensible". But why is it sensible exactly? To separate the upgrade of power distribution vs power storage?

**Comment by chromiumboy** [comment]
> Is this decision due to realism or design concerns?
A bit of both, really

> Because realism wise, i don't think it makes any sense that a SMES, a device that stores MANY times more than even a hyper battery, needs one to work.
Power balance is kinda screwy at the moment. Added more battery types have been vetoed, so these are all we have to work with

> I mean, i'm no electrician, but how logical is this? A battery would store a Direct Current while something like a SMES would store an Alternate Current, due to the "volume" of the charge (?).
"Superconducting magnetic energy storage (SMES) systems store energy in a magnetic field. This magnetic field is generated by a DC current traveling through a [superconducting coil](https://www.sciencedirect.com/topics/engineering/superconducting-coil). In a normal wire, as electric current passes through the wire, some energy is lost as heat due to electric resistance. However, in a SMES system, the wire is made from a superconducting material that has been cryogenically cooled below its critical temperature. As a result, electric current can pass through the wire with almost no resistance, allowing energy to be stored in a SMES system for a longer period of time. Common superconducting materials include mercury, vanadium, and niobium-titanium. The energy stored in an SMES system is discharged by connecting an AC power [convertor](https://www.sciencedirect.com/topics/engineering/convertor) to the conductive coil". So you could say the batteries are there to help support the operation of the magnetic containment field...

> If this is from a design standpoint, in your "Why" it says that it is "sensible". But why is it sensible exactly? To separate the upgrade of power distribution vs power storage? Or is there another reason? 
> SMES aren't exactly accessible, few stations start with enough capacitors for more than 1 SMES (which iirc are like 8 capacitors each). And most of the time these will be spent in substations if anything.
Diversifying the required materials will help with being able to source enough parts to upgrade something, and batteries are probably more easily sourced than advanced capacitors

**Comment by chromiumboy** [comment]
> > > this doesn't make sense, why would APC's not require a cell, but SMES'es and substations do?
> > 
> > 
> > Adding power cells to APCs is still under discussion. And APCs not having batteries is not necessarily a good reason that SMESes and substations should not
> 
> currently APC's have no construction costs except a circuit board, which considering it also stores and outputs power, it should use a power cell or capacitor

Sure, but that can be covered by another PR

**Comment by Partmedia** [comment]
Thanks for the contribution. I'm not strongly opposed to this (and would not block this), but personally I think capacitors are more fitting than batteries for the SMES and substation, for primarily two reasons:

1. Capacitors are easier to source (compared to power cells, which are locked behind research). SMES/substation bombing is already pretty destructive and easier parts would make repair a bit more feasible, which is good for the game.
2. I am an electrical engineer, and from a realism perspective power cells (chemical batteries) in SMES and substations feel wrong. Capacitors in something that's supposed to be magnetically superconducting (SMES) also feels wrong, but feels less wrong than having chemical batteries. Real substations *do* have capacitor banks, but they are not really for storage in the same sense as they are used in SS14. And as discussed before, substations and APCs having storage at all was an implementation detail.

**Comment by chromiumboy** [comment]
> Thanks for the contribution. I'm not strongly opposed to this (and would not block this), but personally I think capacitors are more fitting than batteries for the SMES and substation, for primarily two reasons:
> 
> 1. Capacitors are easier to source (compared to power cells, which are locked behind research). SMES/substation bombing is already pretty destructive and easier parts would make repair a bit more feasible, which is good for the game.

Small power cells can be made with an autolathe using glass and steel sheets, just like basic capacitors. So there is no material or research barriers to making the most basic versions of these devices

> 2. I am an electrical engineer, and from a realism perspective power cells (chemical batteries) in SMES and substations feel wrong. Capacitors in something that's supposed to be magnetically superconducting (SMES) also feels wrong, but feels less wrong than having chemical batteries. Real substations _do_ have capacitor banks, but they are not really for storage in the same sense as they are used in SS14. And as discussed before, substations and APCs having storage at all was an implementation detail.

As I mentioned in a above comment, the batteries could explained as being used to help maintain the magnetic containment field in the SMES

I could increase the capacitor count to 2 on the substation (it was originally 3)

Not that it matters much, but tg station uses batteries to build the [SMES](https://tgstation13.org/wiki/Machines#SMES)

**Comment by deltanedas** [comment]
medium capacity powercells are also abundant in maints which makes them nice for upgrading

**Pull request merged**
