### PR TITLE
Power Restructure and New Generators

### PR DESCRIPTION
**Pull request by Peptide90**
### !!Mapping ID changes!!
- SalternAPC > APCBasic
- SalternSMES > SMESBasic
- SalternSubstation > SubstationBasic
- SalternGenerator > GeneratorBasic

There is now also GeneratorPlasma (kW) and GeneratorUranium (15kW) which you may prefer to use instead as they produce a decent amount of power.

## About the PR 
This PR was originally just going to be wallmount stuff for more compact shuttles and escape pods but scope creep. So this PR:

- Adds a wallmount substation at 2MW (half the big substation capacity).
- Adds a wallmount generator at 3kW (same as the existing small generator).
- Adds a 6kW wallmount generator (APU) specifically for shuttles and escape pods. Should power 2 thrusters, console and lights.
- Adds the TG portable generators (plasma and uranium, 5kW and 15kW respectively). Currently no fuel consumption as that's above me.
- Adds the RTG (20kW). Traditionally these were lower power but then they'd be useful for lighting only. This can atleast power an abductor ship or tiny outpost. There's a damaged variant that emits radiation 2 tiles and are intended to be obtained from derelicts only. (In future would be nice to have them only emit rads when open or damaged and to produce fallout when destroyed).
- Renamed all SalternPower stuff to PowerBasic e.g. SalternSMES is now SMESBasic. Also moved each power structure to it's relevant file to get rid of the SalternPower file.
- Added APCs for each of the large power cell states. Also buffed large power cells to match. The existing APC / normal large power cell was actually useless. PRing as a draft as I imagine this will be under discussion whether these are needed. Future PRs that use large cells will just have to adapt their power usage to be balanced.
- All power stuff now has a suffix with it's power supply / capacity so mappers can see at a glance.
- Made generators now blow up with the same values as substations. They don't produce any debris currently.

Currently awaiting some feedback hence draft.

**Screenshots**

Screenshot was prior to changes. Scroll down for improved portagen animation and TEG glow.
generators
Example of the wallmount stuff. The HV cable under them will need to be made before the wall unless cable terminals can be used.
wall
APC sizes. Note the duplicate high was fixed to super. In future each APC will have the correct cell inside.
apc
Damaged RTG
rtg
Improved portagen animation - It now loops properly. The power level going up and down can be attributed to the generator being not so efficient since it's consuming raw sheets of fuel of varying grades (hypothetically for now).
Content Client_lEr7apisQg

**Changelog**

:cl:
- add: Added new generator types: 2x portable generators. Research their boards to build them.
- add: Added the RTG. Find them in a deep space wreck and try not to get burnt...
- add: Added wallmount generator and substation for use in shuttles and escape pods.

### CODE REVIEW

**Comment by Peptide90** [comment]
Not sure what exactly is wrong with the RSI as it's the same as the rest format wise.

I still need to add construction in for the generators and maybe for the different APCs so they can be built (in future it will just be changing out the cell).

These generators will probably end up being a machine frame construction.

**Comment by Peptide90** [comment]
Passes tests but construction graphs don't work on local soooo, interesting.

**Comment by metalgearsloth** [comment]
Probably better to split this pr as:
- it has mapping changes
- it has a bunch of new content that needs checking
- it changes a bunch of existing content that also needs checking

**Comment by Peptide90** [comment]
> Probably better to split this pr as:
> 
> - it has mapping changes
> 
> - it has a bunch of new content that needs checking
> 
> - it changes a bunch of existing content that also needs checking

Good idea. Got bogged down in construction graphs so I'll split this into new stuff in one and changes in the other.

**Pull request closed without merging**
