### PR TITLE
Add contraband component

### LINKED ISSUE #22062: Contraband needs a component
## Description

The docs https://github.com/space-wizards/docs/pull/214 go into detail about what the component should do and be used for.
Basically there needs to be a component for systems and/or players to identify contraband.

### PR DESCRIPTION
**Pull request by crazybrain23**
## About the PR

Resolves #22062. Admins don't like presents giving out contraband. Also, descriptions for contraband.
TODO:
- [ ] Make component
- [ ] Add it to every contraband item
- [ ] Make RandomGiftSystem check for it
- [ ] Test it

## Why / Balance

So players can tell when an item is contraband, and to let systems (like the gift giver) know what items are contraband.

## Technical details

Adds a component that can be used to detect if an item is contraband, and if that contraband is stealthy.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I would like to know the full extent of this PR.

If the goal is just for presents, this feels kind of silly, considering they're a seasonal thing only. I feel like a lot of those could just be resolved IC by sec.

If the intent is any farther than that, it's worth mentioning that this was discussed at [a maintainer meeting](https://docs.spacestation14.com/en/maintainer-meetings/maintainer-meeting-2023-07-29.html) and the decision was that there shouldn't be explicit markers for contraband.

Furthermore, the definition of contraband is pretty fluid and context-dependent.

**Comment by crazybrain23** [comment]
> I would like to know the full extent of this PR.
> 
> If the goal is just for presents, this feels kind of silly, considering they're a seasonal thing only. I feel like a lot of those could just be resolved IC by sec.
> 
> If the intent is any farther than that, it's worth mentioning that this was discussed at [a maintainer meeting](https://docs.spacestation14.com/en/maintainer-meetings/maintainer-meeting-2023-07-29.html) and the decision was that there shouldn't be explicit markers for contraband.
> 
> Furthermore, the definition of contraband is pretty fluid and context-dependent.

The secondary (and more important long-term) reason, is that @Chief-Engineer wants there to be descriptions on contraband items.

**Comment by EmoGarbage404** [comment]
We specifically talked about that during the meeting and the consensus was to have specific item descriptions modified to specify them as syndicate origin and not to go any farther.

**Comment by crazybrain23** [comment]
> We specifically talked about that during the meeting and the consensus was to have specific item descriptions modified to specify them as syndicate origin and not to go any farther.

What about adding a field for faction of origin, so that a description will just say that?

**Comment by JoeHammad1844** [comment]
getting a C20-R in your present is part of the fun

**Pull request closed without merging**
