### PR TITLE
Nuke now toggles emergency access on all doors

### PR DESCRIPTION
**Pull request by ScarKy0**
## About the PR

Attempted revival of #30143
Made this into PR form so I can see stuff I need easier, don't mind me :godo:
I will slowly work on it

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by SlimmSlamm** [comment]
I don't agree with this change at all especially considering it'll nerf the few good lone op strats and generally just make it even harder to win. If nukies managed to get the door remote to bolt doors or antimov AI/kill it then that's crews fault. This isn't a good change.

**Comment by ScarKy0** [comment]
> I don't agree with this change at all especially considering it'll nerf the few good lone op strats and generally just make it even harder to win. If nukies managed to get the door remote to bolt doors or antimov AI/kill it then that's crews fault. This isn't a good change.

It got conceptual approval, I was just asked by the original author to finish it. Feel free to bring it up to them.

**Comment by ps3moira** [comment]
Should be CCVAR optional as downstream MRP and HRP servers don't want people bomb rushing armory to get guns

**Comment by ScarKy0** [comment]
After looking into the code a little more, this is beyond my paygrade :godo:
Unless im severely misunderstanding the code

**Pull request closed without merging**
