### PR TITLE
Cleaners (not janitors) ERT alternative

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

The cleaners are flamethrower wielding nanotrasen affiliated ERT alternatives
**TO DO**
[x] prefilled flamethrower with a bandolier full of incendiary shotgun rounds
[x] cleaner loadout
[ ] make spawnable
[ ] cleaner shuttle (with plenty of fireaxes)
**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- add: Centcom have hired 'The Cleaners', flamethrower wielding maniacs as a situational ERT alternatives

### CODE REVIEW

**Comment by LankLTE** [comment]
Cleaners? We already have those, they're called the ERT Janitors. 
(I beg you do not give them biosuits they're so ugly please)

**Comment by JoeHammad1844** [comment]
Im referencing the cleaners from the division

**Comment by JoeHammad1844** [comment]
maybe I should make the suit more orange..

**Comment by JoeHammad1844** [comment]
image
how does this look? I think it looks more fire-ey, which makes sense because their gimmick is flamethrowers

**Comment by LankLTE** [comment]
> how does this look? I think it looks more fire-ey, which makes sense because their gimmick is flamethrowers

Looks good. In all honesty my main complaint with the biosuits is the hood, I think the current ones look dumb ~and I instantly think less of anyone who wears one~ but that's not really your problem. Does certainly feel more fire-ey anyways

**Comment by potato1234x** [comment]
> > how does this look? I think it looks more fire-ey, which makes sense because their gimmick is flamethrowers
> 
> Looks good. In all honesty my main complaint with the biosuits is the hood, I think the current ones look dumb ~and I instantly think less of anyone who wears one~ but that's not really your problem. Does certainly feel more fire-ey anyways

but the among us hood

**Comment by JoeHammad1844** [comment]
alright, I forgot how to save maps, please remind me

**Comment by JoeHammad1844** [comment]
nevermind

**Comment by JoeHammad1844** [comment]
to be honest, I dont know how to actualy test what ive changed in game :trollface:

**Comment by metalgearsloth** [comment]
Is this still being worked on

**Comment by JoeHammad1844** [comment]
kinda forgor and got a few things going on so i'd have to say no, this isnt being worked on

**Comment by metalgearsloth** [comment]
okey dokey

**Comment by JoeHammad1844** [comment]
ill probably revisit it later, but this makes sense

**Pull request closed without merging**
