### PR TITLE
make status icons unshaded

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

this was my original intent it just was shitty and broke all the time apparently
here's me doing it correctly (wowzers)

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Job icons now ignore lighting.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
wouldn't this make someone with a sechud able to see other people in the dark?

**Comment by Equivocateur** [comment]
> wouldn't this make someone with a sechud able to see other people in the dark?

Sechud wallhacks real

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/issues/18639 ?

**Comment by EmoGarbage404** [comment]
> https://github.com/space-wizards/space-station-14/issues/18639 ?

Cring

**Pull request merged**
