### PR TITLE
Replaces CMO's MedHud with a MedSecHud

### PR DESCRIPTION
**Pull request by Ghagliiarghii**
Replaces the Medical HUD with a MedSec HUD in CMO's locker

## About the PR

CMO now has access to the MedSecHUD
## Why / Balance

I feel department heads should enforce some law/order in their departments. Medical in particular sees a lot of people in and out all shift, and this would aid communication between CMO and command/security to this end. Additionally, it seems to be the best niche for the MedSecHUD in the game ~~since we don't currently have Brigmedics~~.

### CODE REVIEW

**Comment by Plykiya** [comment]
it's not the CMO's job to figure out who is wanted or not though....?

**Comment by Killerqu00** [comment]
giving any non-sec staff security HUD is considered a bad idea

**Comment by deepdarkdepths** [comment]
If command and security are good at relaying information, you don't need this. If you feel someone is suspicious or there's a possible threat in medbay just tell someone.
I would also rather not give certain CMO players more of an excuse to valid hunt

**Comment by rosieposieeee** [comment]
might be worth instead making an ID HUD that shows IDs but not wanted status, for nonsec heads

**Comment by EmoGarbage404** [comment]
non-security staff, including heads, should not be given any real form of security equipment in a formal capacity. CMOs job is to run medbay to the best of their ability, not to play diet cop on the sick.

**Comment by deltanedas** [comment]
officers left you on wanted after you were released, oops enjoy your 30u mutagen courtesy of Hunts-The-Valids, CMO :trollface:

**Pull request closed without merging**
