### PR TITLE
Improve random tip UI

### PR DESCRIPTION
**Pull request by ElectroJr**
After playing the game for a while I've noticed that the random tips that were added by #13509 tend to just get lost in the chat log. This PR slightly tweaks the way the tips are presented and makes them play some sounds so that they stand out a bit more, which should help newer players. I actually started working on this shortly after the tip system was merged but only now found the motivation to finish the PR. This PR is bigger and took longer than it has any right to, and is still quite janky.

This PR also adds a new command that allows admins to trigger a random tip to be sent, as well allowing them to send custom tips to specific players

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

https://user-images.githubusercontent.com/60421075/228731344-5ebb0da3-e911-44b8-aec2-ab5e6c241c36.mp4

:cl:
- tweak: Improved the random-tip UI. Tips should be easier to see and will no longer get lost in the chat log.

### CODE REVIEW

**Comment by AJCM-git** [comment]
If this is gonna be permanent there should be an option to disable non-admin ones in the client, also making them go away after clicking the control would be nice

**Comment by ElectroJr** [comment]
(It is not meant to be permanent... unless people actually want this for some reason)

**Comment by AJCM-git** [comment]
> (It is not meant to be permanent... unless people actually want this for some reason)

i cant lie to myself, i dig it

**Comment by DogZeroX** [comment]
Make it NOT april fools if this gets removed I will be sad

**Comment by Flareguy** [comment]
I think it would be pretty silly if it were permanent, it's intentionally very intrusive.

**Comment by EmoGarbage404** [comment]
If it was a configurable option, i think that'd be nifty.

**Comment by moonheart08** [comment]
oh my god

**Comment by moonheart08** [comment]
@ElectroJr Tippy should play the honk noise (quietly) when they face the screen, for a little extra attention grabbing.

**Comment by deltanedas** [comment]
poor mans bwoink

**Comment by QuietlyWhisper** [comment]
Honestly great

**Comment by Kromabae** [comment]
no cap this should be part of the game :D

**Pull request merged**
