### PR TITLE
Bola 1984

### PR DESCRIPTION
**Pull request by Skarletto**
## About the PR

I hate bolas, literally why doesn't sec use bolas instead of stun batons  and disablers? What about the populace's stunprod? There is no use for the stunprod since bolas are just that much better. Throw two at someone and there you go, you've got a cuffed crew member. It's that easy!
## Why / Balance

This probably most definitely needs discussion but idk why bolas do stamina damage, they're supposed to make you slow, though I can understand the idea of someone tripping on them. I'd love to see stunprods used instead, but everyone just resorts to throwing 2 bolas at you super fast. I was thinking of making them deal like 20 stamina damage instead, but I was also just thinking no stam damage might make sense. Honestly a better fix for this would be to put a cooldown on thrown items but idk how to do that :trollface: 
## Technical details

line change
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
buh
local spessman entangled in a bajillion bolas
## Breaking changes

**Changelog**

:cl: Skarlet
- tweak: Bolas do not deal stamina damage anymore.

### CODE REVIEW

**Review by QuietlyWhisper — COMMENTED** [review]
Seems like a cool idea, the slowdown does come from the ensnaring effect and not from stamina, but that is an added factor

So fuck yeah less stuns!

**Comment by Aisu9** [comment]
maybe because the three metal balls composing the bolas hit your leg at the same time numbing them near instantly?

**Comment by LankLTE** [comment]
Leaving this for discussion by people who know bolas better than I do, but I do wanna say that nobody uses stunprods because they're completely awful. They do 20 stamina damage (you need to hit someone *5* times) and only have 5 charges.

**Comment by Skarletto** [comment]
I don't have an issue with bolas dealing stamina damage (again I'd like to see discussion), what I have an issue with is this.

https://github.com/space-wizards/space-station-14/assets/122584947/761f91ec-447f-43d6-9c0b-fdf3522633dd

**Comment by LankLTE** [comment]
> I don't have an issue with bolas dealing stamina damage (again I'd like to see discussion), what I have an issue with is this.

Pretty sure you can dk the exact same thing with a turned on stun baton. Obviously those are harder to get, but it does seem the underlying issue here is the ability to quickly throw items like that.

**Comment by QuietlyWhisper** [comment]
> Pretty sure you can do the exact same thing with a turned on stun baton. Obviously those are harder to get, but it does seem the underlying issue here is the ability to quickly throw items like that.

Which I brought up in #17226, throwing need a cooldown regardless of the keybinding issue

**Comment by deltanedas** [comment]
you can do that without macros or "macros" just by pressing x to throw 2 in quick succession
bolas should purely be slowdown tho not stun either way

**Comment by TsjipTsjip** [comment]
Comparatively, the stun baton was also already nerfed ( #20970 )because one could easily throw two of them et voila. It would make sense, even if just for parity, to increase the amount of hits you need to three.

Functionally, it would make sense that it deals some stamina damage (see the "tripping" effect), but the slowdown is the main reason I would personally use a bola, as the doafter to remove it is lengthy as well.

Balance-wise, I have nothing to bring to the table as I do not believe I have used bolas enough to bring a significant contribution.

**Comment by Skarletto** [comment]
> Pretty sure you can do the exact same thing with a turned on stun baton. Obviously those are harder to get, but it does seem the underlying issue here is the ability to quickly throw items like that.

True, you can! But you can't craft batons.

**Comment by KompaniLinge** [comment]
Bola damage is le bad, but as of right now they only really work as a defensive tool. THROWING SUCKS.

If you plan to do any offensive use of the bola, might aswell reformat your harddrive because thats both more useful, and more interesting.

I think the bola rework is fine; but this kills any applicability of bolas in offensive scenarios, which SUCKS!!!

**Comment by Skarletto** [comment]
If people were okay with the bolas not dealing stam dmg anymore I could increase the slowdown so it's actually not a shit weapon to use

**Comment by TsjipTsjip** [comment]
> If people were okay with the bolas not dealing stam dmg anymore I could increase the slowdown so it's actually not a shit weapon to use

This would be interesting to try out.

**Comment by QuietlyWhisper** [comment]
We have the power to playtest this with prototype upload if need be, though maybe its just me, I havent seen people using bolas, only throwing batons whicb was fucking painful, so I assume it feels the same

**Comment by Skarletto** [comment]
Bolas are used like every single rev round I've played in/observed. It's CONVENIENT, it's an easy to get stun weapon because it's crafting recipe is so cheap. You just need 5 Lv and 6 steel, which is super easy to acquire. Get two and the head of your department's gone suddenly!?

**Comment by Subversionary** [comment]
grudge pr, nerfing bola's stopping power will not give you an increase in stunprod use as its unironically the worst stun weapon which manages to lose against most mid-tier melee weapons while requiring moderate amount of prep.

> What about the populace's stunprod?
> There is no use for the stunprod since bolas are just that much better.
> I'd love to see stunprods used instead
https://github.com/space-wizards/space-station-14/issues/21197#issuecomment-1776132041


bolas
* Break
* "Weigh" 20 per single bola
* Require to be crafted individually using handcuffs and steel
* Awful at chasing, per current throwing mechanics when the target is running **from** you

but
* Good when being chased
* Debilitating in maint choke points

**Comment by keronshb** [comment]
I'm _somewhat_ against this.

Only somewhat because this is just a bandaid.

Bola's take a lot of space in your bag, they take time & resources to create & they break & people can remove them while moving (intended).

Outside of the bag space maybe being a bit weird, these all are fine counter balances to Bola.

Now the real first fix is #21282

The second real fix is to make sure Bola's can't deal Stamina damage if there's already one attached.

The third real fix is to have an actual knockdown system that isn't reliant on stamina damage or hardstuns.

And the final fix is to have throwing cost a minimal amount of stamina (especially if Fix 1 isn't implemented)

**Comment by Skarletto** [comment]
> Now the real first fix is https://github.com/space-wizards/space-station-14/pull/21282

People can just switch hands, this isn't really about people using hotkeys

>The second real fix is to make sure Bola's can't deal Stamina damage if there's already one attached.

This would be awesome but I'm not well versed enough to implement this or any of the other fixes you suggested

>grudge pr

ok

>Require to be crafted individually using handcuffs and steel

As previously mentioned it's 5 lv cable and 6 steel

**Comment by asperger-sind** [comment]
Having to land two (2) bolas to stun someone puts them at the position of the second-best stun of the game, only surpassed by the T3 tech tasers, this doesn't include chems or slippery objects.

As it stands throwing cooldowns, improvements, key remapping limitations or anything of the like will not solve the issue of bolas being a two hit stun that if you cannot land at medium-long range you can just toss them at the silly individual next to you and K.O. them alike a baton.

**Comment by lexs0sa** [comment]
Removing something from your inventory should have a 1-2 second delay before being able to use it, just like swapping weaponry. Macros and hotkey double-binding has nothing to do with me being able to press C + Q three times in a row, click on handcuffs, then cuff someone.

Bolas should slow and not stun. Calling this a band-aid means you haven't played a rev round recently.

**Comment by keronshb** [comment]
> Removing something from your inventory should have a 1-2 second delay before being able to use it, just like swapping weaponry. Macros and hotkey double-binding has nothing to do with me being able to press C + Q three times in a row, click on handcuffs, then cuff someone.
> 
> Bolas should slow and not stun. Calling this a band-aid means you haven't played a rev round recently.

No, removing/putting into storage should not and **will not** have a do after.

**Comment by UbaserB** [comment]
Finally!

**Comment by deltanedas** [comment]
> No, removing/putting into storage should not and will not have a do after.

delay not doafter

**Comment by Skarletto** [comment]
https://github.com/space-wizards/space-station-14/pull/21340 is pro so i'm closing this, discussion can prob move there

**Pull request closed without merging**
