### PR TITLE
Renault gives 5TC when butchered 

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-Renault drops 5TC when butchered

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Granting TC for various assassinations and goals i planned to be added (i believe) but i think this is not the way to go about implementing it. There should ideally be a system within the uplink which interfaces and automatically deposits it.

**Comment by Emisse** [comment]
this is just to add what renault had in 13

**Comment by moonheart08** [comment]
> Granting TC for various assassinations and goals i planned to be added (i believe) but i think this is not the way to go about implementing it. There should ideally be a system within the uplink which interfaces and automatically deposits it.

No this is exactly how it works in SS13 and I find it kinda funny.

**Review by moonheart08 — APPROVED** [review]

**Comment by Fishfish458** [comment]
If it does have some precedent it should be fine, especially since it also means that they'll need a knife to butcher with which is also suspsect

**Comment by vulppine** [comment]
AAAAAAA

**Comment by UKNOWH** [comment]
Oh this is gonna be funny

**Review by mirrorcult — APPROVED** [review]
this is funny, we can see how it pans out

**Pull request merged**
