### PR TITLE
tweak(Chemical Dispenser): Give the chemical dispenser a hitbox

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Gave the chemical dispenser a hitbox

## Why / Balance

Its supposed to be like this

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Before**
[Screencast from 07-27-2024 10:04:49 AM.webm](https://github.com/user-attachments/assets/4ca5269f-be64-49ad-bd14-31cf6a8af89f)

**After**
[Screencast from 07-27-2024 10:04:49 AM.webm](https://github.com/user-attachments/assets/c579c5e5-1449-4029-8e79-7559b1ac5cb1)

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Plykiya** [comment]
the fake nuke lost this as well, what PR changed it?

**Comment by Brandon-Huu** [comment]
> the fake nuke lost this as well, what PR changed it?

I have no idea, I just noticed the chemical dispenser didn't have a hitbox while playing in game.

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
Unnecessary changelog. Please remove

Also, I noticed you seem to have put in your In game character name as a changelog (also in other prs). Why is that the case?

**Comment by Brandon-Huu** [comment]
> Unnecessary changelog. Please remove
> 
> Also, I noticed you seem to have put in your In game character name as a changelog (also in other prs). Why is that the case?

On a PR Tour, should I not do that?

**Comment by VasilisThePikachu** [comment]
> > Unnecessary changelog. Please remove
> > Also, I noticed you seem to have put in your In game character name as a changelog (also in other prs). Why is that the case?
> 
> On a PR Tour, should I not do that?

I would suggest against it. Changelogs are not meant to be "in character", makes the pr look less professional and makes it a little harder to find the person who made the PR if needed.

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by VasilisThePikachu** [comment]
> Lots of slander admins wont do anything about
> To figure out who should be blocked / reported

Don't mix in game drama with prs. You are just making it harder for us rather then diverting attention to your reports

**Pull request merged**
