### PR TITLE
zumo too quick

### PR DESCRIPTION
**Pull request by PaulRitter**
tested

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
test driven development

**Comment by Zumorica** [comment]
Paul did say "review and merge" so I'm blaming him

**Comment by Zumorica** [comment]
also smug too quick you could've used "default" instead of "new ToggleState()" or whatever

**Comment by DrSmugleaf** [comment]
turbo reviewed and speedily merged

**Comment by DrSmugleaf** [comment]
> also smug too quick you could've used "default" instead of "new ToggleState()" or whatever

out of the scope of the pr

**Comment by RemieRichards** [comment]
that'd be gross
you fools

cos then you'd not know it was intending to send a toggle

**Comment by Zumorica** [comment]
what's gross is creating a new ToggleState for that

**Comment by DrSmugleaf** [comment]
heated 1 line pr

**Comment by RemieRichards** [comment]
but it's an empty struct! it'll be optimised out

(I hope)

**Pull request merged**
