### PR TITLE
Allow the purchase of emitters from cargo.

### PR DESCRIPTION
**Pull request by pigeonpeas**
## About the PR
Allows you to purchase emitters from cargo for 3000 each.

## Why / Balance
Although you can make emitters in science, buying them can often be faster, and more convenient.

## Media
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Adds the ability to purchase emitters in cargo.

### CODE REVIEW

**Comment by Nairodian** [comment]
Good god it was so long back in the day, but I believe there's a reason Cargo can't order them.

I played during the time Cargo was allowed to buy them, and from what I recall it become this stupid fucking meta where they'd order emitters, get some clueless engineer to open the crate for them or they'd just smash through it, then set up the emitter to break open weapon/armor crates extremely quickly.

**Comment by deltanedas** [comment]
bats can break crates open in seconds and sci can still make them

**Comment by Tainakov** [comment]
I understand that this is convenient and I know what it’s like when you wait 2 hours for emitters from scientists, but this ordering option will simply exclude the department from singulo station goal, because at this point you can just buy everything from cargo, which is not healthy for game design IMO

**Comment by deltanedas** [comment]
you could but it costs 6 grand for the emitters which isnt cheap

**Comment by lzk228** [comment]
> I understand that this is convenient and I know what it’s like when you wait 2 hours for emitters from scientists, but this ordering option will simply exclude the department from singulo station goal, because at this point you can just buy everything from cargo, which is not healthy for game design IMO

there are no station goals on wizden

**Comment by PJB3005** [comment]
Ordering emitters and engine parts from cargo is literally how it works in SS13.

**Comment by pigeonpeas** [comment]
I will add, I got this suggestion from Emo
image

and Emisse suggested having the emitters in both cargo and science.
image

**Pull request merged**
