### PR TITLE
Disposal unit is no longer nuke-proof

### PR DESCRIPTION
**Pull request by komunre**
## About the PR

`DisposableUnitBase`'s `DamageTrigger` values changed to closer match desired behaviour. Remember when dev team wasn't political?

## Why / Balance

#24233

## Technical details

DamageTrigger 100 for annihilation,
DamageTrigger 50 for normal destruction.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Disposal units are no longer nuke-proof

### CODE REVIEW

**Comment by deltanedas** [comment]
did you actually test it

**Comment by komunre** [comment]
If by this you want to say "did you test it for being as balanced as I want to", then I don't know how would you truly want it.
However, if by this you mean "did you test if game launches" then yes, it does.

**Comment by deltanedas** [comment]
did you test if a nuke destroys disposal units

**Comment by komunre** [comment]
Gladly would, if nukes wouldn't crash the client in master (lmao). However you can trust the code, since that's (relatively) very little damage required.

**Comment by komunre** [comment]
anyways, since you reminded me of that issue, I tried launching the client outside VS so I can relaunch it without obliterating the server, and yes, it does destroy them. I don't know why I even had to test it, you guys have weird standards.

**Comment by komunre** [comment]
I'll go post an issue of audio crash of client upon nuking now, since it was apparently not reported.

**Comment by komunre** [comment]
#24309

**Comment by Golinth** [comment]
Sad this is gone, honestly. Seeing random crew members and parts of the nukie squad survive because they dove into disposals  was iconic for me.

**Comment by UbaserB** [comment]
You can still survive in the fridge!

**Comment by GreyMario** [comment]
disposal bins surviving nukes is "political"? what's next on the chopping block, fridges?

**Comment by UbaserB** [comment]
> disposal bins surviving nukes is "political"? what's next on the chopping block, fridges?

disposal bins were an unintended bug, fridges were an intended design. Reasoning can be quite different.

**Comment by deltanedas** [comment]
#24309 is a direct indiana jones reference this is just bug

**Comment by metalgearsloth** [comment]
Hi Komunre,

Given the circumstances of you being removed in 2022 we've also applied a repo ban. If you'd like to appeal it you can do so on the forum.

**Pull request closed without merging**
