### PR TITLE
Southern accent

### PR DESCRIPTION
**Pull request by UBlueberry**
## About the PR

Added a new speech trait to sort of replicate Southern accents by replacing "-ing" suffixes with "-in'". It also adds some contractions, like "is not" to "ain't" and "you all" to "y'all".
## Why / Balance

I've seen quite a few people manually do what this trait would do. Not to mention, many players that I have talked to also yearn for more accents.
## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 
-add: Nanotransen is now recruitin' personnel from Southern America.

### CODE REVIEW

**Comment by AjexRose** [comment]
if it can replace "you all" with "yall" then it would be perfect

**Comment by UBlueberry** [comment]
oh crap, the cowboy accent doesn't do that?!?! 
i'll fix this immediately.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Call it southern american to avoid confusion.

**Comment by UBlueberry** [comment]
where should i change it? everywhere?

> Call it southern american to avoid confusion.

**Comment by Kadeo64** [comment]
> if it can replace "you all" with "yall" then it would be perfect

also this

**Comment by thymol-blue** [comment]
I love it! I found this post here ifya would be inclined to add more

https://lets-get-fictional.tumblr.com/post/161633475080/tips-for-writing-a-southern-accent

**Comment by UBlueberry** [comment]
that wasn't intentional but FEAR NOT i will return

**Comment by K-Dynamic** [comment]
We need australian accent too

**Comment by UBlueberry** [comment]
one at a time!

**Comment by UBlueberry** [comment]
let's try this again

**Comment by ike709** [comment]
Now replace "going to" with "fixin' to" for the true Southern idiolect

**Comment by UBlueberry** [comment]
> Now replace "going to" with "fixin' to" for the true Southern experience

I'm not southern myself so I will ask you:
Does "I'm fixin' to medical" sound right?

**Comment by Tynobeard** [comment]
> > Now replace "going to" with "fixin' to" for the true Southern experience
> 
> I'm not southern myself so I will ask you: Does "I'm fixin' to medical" sound right?

No I don’t think that’s right, fixin’ means either you want to do the following or you are about to do the following, depending on the trailing word, so fixin to and fixin for mean different things
like “I’m fixin’ to get a drink” would either mean “I am about to/preparing to go get a drink” but “I’m fixin for a drink” would be “I want to go get a drink”

**Comment by UBlueberry** [comment]
> > I'm not southern myself so I will ask you: Does "I'm fixin' to medical" sound right?
> 
> No I don’t think that’s right, fixin’ means you want to do the following or you are about to do the following

it's hard to make that distinction (for me at least) in code
i'd have to code something that would figure the context

**Comment by Dutch-VanDerLinde** [comment]
Changelog is broken you need 🆑

**Comment by UBlueberry** [comment]
> Changelog is broken you need 🆑

fixed

**Comment by VividPups** [comment]
Hey, is this still active? or the most recent active one?

**Comment by UBlueberry** [comment]
nope! i'm making another one that ISN'T a webedit! i'll link it here when i make it.

**Comment by UBlueberry** [comment]
[26543]

**Pull request closed without merging**
