### PR TITLE
Add a Prisoner job.

### PR DESCRIPTION
**Pull request by nukashimika**
## About the PR

This PR adds a roundstart prisoner job. 

This is also my first PR so reviews very needed.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: CentCom has transferred some prisoners to your brig. Please look after them.

### CODE REVIEW

**Comment by Pangogie** [comment]
Fairly sure that is was decided that upstream would not include prisoner jobs.

**Comment by Emisse** [comment]
might be useful just to have but im not sure it would be used currently

**Comment by nukashimika** [comment]
wait actually this is isn't ready, i'll close for now

**Comment by nukashimika** [comment]
id card sprites are brokey, need to fix them

**Pull request closed without merging**
