### PR TITLE
Added biomass crate orderable from cargo

### PR DESCRIPTION
**Pull request by Easypoller**
## About the PR: Added biomass crate orderable from cargo

**Changelog**
-Added an orderable crate from cargo filled with 3 full biomasses at the fair price of 200

### CODE REVIEW

**Comment by Kromabae** [comment]
200 credits seem pretty low to be honest for 300 biomass.

Seeing how most cargo players are using ways that aren't salvage to make a ton of credits they are normally floating around a massive bank most of the time.

**Comment by mirrorcult** [comment]
not a fan of this, you can already indirectly buy biomass by purchasing animals

**Comment by EmoGarbage404** [comment]
going to just comment on the fact that adding this is far less interesting than ordering animals. Additionally, it invalidates upgrades for the biomass reclaimer by making purchasing biomass extremely viable.

**Comment by Easypoller** [comment]
Fair enough

**Pull request closed without merging**
