### PR TITLE
Shuttle console + FTL rework

### PR DESCRIPTION
**Pull request by metalgearsloth**
It's 90% the console rework and 10% a rework of how FTL is done, mainly so you have some agency on how to FTL.

Draft because it's half-done but I know what I want the design to be. Will update screenshots as I get closer to final design

Fixes https://github.com/space-wizards/space-station-14/issues/21266

Requires https://github.com/space-wizards/RobustToolbox/pull/4851
Requires https://github.com/space-wizards/RobustToolbox/pull/4914
Requires https://github.com/space-wizards/RobustToolbox/pull/4911
Requires https://github.com/space-wizards/RobustToolbox/pull/4910

Tests pass locally it just needs a billion engine PRs.

Video shows all of the functionality, just needs cleanup (edit: I removed half of the new docking stuff for now just to avoid delaying merge and scope-creeping too hard).

https://github.com/space-wizards/space-station-14/assets/31366439/f1df5771-3028-4652-937d-1c8c37fea164

:cl:
- tweak: Reworked shuttle consoles, including: manual FTL jumps, new map screen, fixed performance issues, new docking screen.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
> please tell me this makes it so things off the screen will be displayed based on their direction instead of just gathering in a corner all the time.

You realise the reason they gather in the corner is due to how directions work.

**Comment by PixelTheKermit** [comment]
I wonder if it might look better with a smaller radar. Otherwise looks good so far.

**Comment by metalgearsloth** [comment]
Updated screenshots though still want to tweak it slightly then just need to finish the docking rework.

**Comment by metalgearsloth** [comment]
Okay all the functionality is done but docking still looks like ass so gonna make it pretty and also make the requisite engine prs soonTM.

**Comment by metalgearsloth** [comment]
I ended up cutting the planned docking features short to get it out the door but it still has more docking features than live.

**Comment by K-Dynamic** [comment]
If people fall off shuttle in ftl, could they be picked up with manual FTL targeting?

**Comment by metalgearsloth** [comment]
> If people fall off shuttle in FTL, could they be picked up with manual location picking on your FTL map?

You can't FTL to the FTL map, at least atm.

**Comment by deltanedas** [comment]
> You can't FTL to the FTL map, at least atm.

um actually you can get all the supplies needed to build a shittle ftl somewhere then jump out and build shittle then navigate to wherever. comms server optional to assist with the task

**Comment by DTSpawn** [comment]
Hi Metalgearsloth! I've got a problem with expeditions now. Expedition map simply unavailable in console.

**Comment by DTSpawn** [comment]
More to it - Arrivals shuttle arrives at 2 different spots (one in space one on a planet). and it's just random.

**Comment by Erisfiregamer1** [comment]
> Hi Metalgearsloth! I've got a problem with expeditions now. Expedition map simply unavailable in console.

Yeah, the FTL location is completely missing from the shuttle console now. How am I supposed to do expeditions?

**Pull request merged**
