### PR TITLE
Chill bounties + fixes

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

main gameplay tweaks:
- bounties no longer have time limits
- upped count from 3 to 5
- halved most of the prices to make them even somewhat reasonable.

fixes:
- fixed not being able to complete bounties with living things
- fixed nested containers not getting counted
- fixed duplicate bounties appearing

tweaksies:
- removed a few super rng-heavy bounties
- tweaked the text on one or two
- made IDs have unique prefixes and numbers rather than being sequential

## Why / Balance

High pressure bounties are just really hard and lead to unsatisfying moments where you spend a ton of time getting the supplies only to not be able to sell cuz you took too long. bounties are really underutilized and the time pressure just makes them a bit too hard to be fun for the average player. By slowing it down and letting people choose more and take their time, hopefully cargo techs will enjoy it more.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Cargo Bounties no longer have time limits. There are also more available at once.
- tweak: Adjusted reward amounts for bounties
- fix: Fixed bounties failing to register mobs and items inside containers.

### CODE REVIEW

**Comment by Anzarot121** [comment]
It seems to me that there should be an option to refuse a request. Previously, this was solved by simply waiting until the unprofitable or unfulfillable request expired and a new one appeared.

**Comment by EmoGarbage404** [comment]
test fails are REAL and i'll fix em tomorrow

**Comment by Kadeo64** [comment]
now cargo is no longer the most stressful job on the station (It's still the most important job on the station)

**Comment by EmoGarbage404** [comment]
ok fixed arbitage

**Comment by it-joco** [comment]
Is there a way to reroll/clear tough bounties?  I can see a situation where cargo gets mostly softlocked with five difficult bounties on their plate, if not.

**Pull request merged**
