### PR TITLE
Medical Machinery Research

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
A lot of things to say I guess soooo

Added chem dispenser and chem master board to the protolathe
Made chem dispenser and chem master deconstructible and destructible 
Added a new Medical Machinery technology which includes the cloningpod, scanner, chem master and chem dispenser 
fixed electromagnetic technology Icon being ERROR
Made it so machines will drop their parts when destroyed
**Screenshots**

image
image

**Changelog**

:cl: Hoolny
- add: Added Chem Dispenser and Chem Master into the protolathe 
- add: Chem Master and Chem Dispenser will now drop their parts when destroyed 
- tweak: Fixed machines becoming fully made machine frames after being destroyed

### CODE REVIEW

**Comment by SethLafuente** [comment]
> the way you wrote it now, it will dupe the materials since it still reverts to the finished machineframe, containing parts already. i'd probably just remove the behaviour that makes it return to a machineframe

Im not to sure what you mean since it dosen't duplicate anything it just makes into into a machine frame with wires like it does on ss13

**Comment by PaulRitter** [comment]
> > the way you wrote it now, it will dupe the materials since it still reverts to the finished machineframe, containing parts already. i'd probably just remove the behaviour that makes it return to a machineframe
> 
> Im not to sure what you mean since it dosen't duplicate anything it just makes into into a machine frame with wires like it does on ss13

p sure that machine frame already contains the parts

**Comment by juliangiebel** [comment]
> 
> 
> > > the way you wrote it now, it will dupe the materials since it still reverts to the finished machineframe, containing parts already. i'd probably just remove the behaviour that makes it return to a machineframe
> > 
> > 
> > Im not to sure what you mean since it dosen't duplicate anything it just makes into into a machine frame with wires like it does on ss13
> 
> p sure that machine frame already contains the parts

The one with only the wires in it doesn't

**Comment by PaulRitter** [comment]
> > > > the way you wrote it now, it will dupe the materials since it still reverts to the finished machineframe, containing parts already. i'd probably just remove the behaviour that makes it return to a machineframe
> > > 
> > > 
> > > Im not to sure what you mean since it dosen't duplicate anything it just makes into into a machine frame with wires like it does on ss13
> > 
> > 
> > p sure that machine frame already contains the parts
> 
> The one with only the wires in it doesn't

ight, i will take your word for it

**Comment by Zumorica** [comment]
Looking at this, you clearly don't know how machine deconstruction work. The way you have coded this, instead of letting the graph handle the deconstruction, you duplicate the parts and the worst part is doing that for parts that may have different variations (machine parts such as manipulator) is bad because it won't return the correct part inserted. This PR is really bad.

**Comment by Zumorica** [comment]
Made obsolete by #5125

**Pull request closed without merging**
