### PR TITLE
Captain's energy sabre

### PR DESCRIPTION
**Pull request by dribblydrone**
## About the PR
Replaces the captain's old sabre with a retractable "e" version. It has the same 17 damage as the old one but half is heat. It also has the projectile reflection chance from the energy sword.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://user-images.githubusercontent.com/119393097/236119304-9a9fb904-9d37-4731-a110-a87ecfb973db.mp4

**Changelog**

:cl:
- add: Added the captain's energy sabre as a replacement for the old sabre.

### CODE REVIEW

**Comment by KaiShibaa** [comment]
I personally prefer Captain having a blade styled Sabre instead of an energy one. Then Captain will have something sorta exactly with what the syndicate already has.

**Comment by mirrorcult** [comment]
i dont see the point of changing this. the blade is cool

**Comment by dribblydrone** [comment]
I thought so too, kinds just figuring out prs and stuff.

**Comment by Emisse** [comment]
I'd prefer if this was added but not put in the loot pool yet for loadout, things like this are perfect for loadout unlocks.

**Comment by dribblydrone** [comment]
What’s a losdout unlock?

**Pull request closed without merging**
