### PR TITLE
More lobby art

### PR DESCRIPTION
**Pull request by Veritius**
## About the PR 
Adds some lobby art to the game.

**Screenshots**

image
aaaaaaa

**Changelog**

:cl:
- add: Added new lobby art

### CODE REVIEW

**Comment by Veritius** [comment]
Also, the image file is pretty hefty. Relevant:
image

**Comment by Emisse** [comment]
ok thats a bad ass load screen tho

**Comment by Veritius** [comment]
Also, quickly noting, this PR will stay a draft for a while. I'm going to be adding a few more art pieces and then make it a real PR, but I have to finish those extra pieces first.

**Comment by PaulRitter** [comment]
this is fire

**Comment by Veritius** [comment]
may have burned out on the art. still, got two pieces, I'm happy.

**Review by mirrorcult — APPROVED** [review]
it doesnt really need the rsi but w/e. this is epic, but should wait to merge until contentdb

**Review by moonheart08 — APPROVED** [review]

**Comment by mirrorcult** [comment]
delta time

**Pull request merged**
