### PR TITLE
Added new icons for the emote wheel

### LINKED ISSUE #27467: Need emote icons
## Description

For #26702.

### PR DESCRIPTION
**Pull request by TyAshley**
## About the PR

Added new icons for the emote wheel
## Why / Balance

Differentiate the actions at a glance, and add clarity
Fixes #27467 
## Technical details

Added new icons under Textures/Interface/Emotes, modified yaml files to reference them
## Media

image
image
image
image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Allen
- add: Added new icons for the emote wheel

### CODE REVIEW

**Comment by TyAshley** [comment]
Finished the last of my cleanup, barring any feedback requiring changes, this is good to review

**Comment by ilyamikcoder** [comment]
new icons probably need some kind of attribution data?

**Comment by TyAshley** [comment]
I added an attributions.yml to the emotes folder

**Comment by SonicHDC** [comment]
Looks so weird

**Pull request merged**
