### PR TITLE
paint buttons in dispenser matching reagent color

### PR DESCRIPTION
**Pull request by Slava0135**
## About the PR

Buttons in reagent dispensers are now coloured according to reagent color

**Media**

Screenshot_2023-02-07_20-59-30
Screenshot_2023-02-07_20-59-43
Screenshot_2023-02-07_21-00-08

**Changelog**

:cl:
- tweak: buttons in reagent dispensers are now coloured according to reagent color

### CODE REVIEW

**Comment by moonheart08** [comment]
The contrast on these is terrible.

**Comment by moonheart08** [comment]
If you want this, add an icon with a beaker/vial of the chem to the button, do not modulate the button.

Even then, what's the point? It's very visually noisy and looks like I splattered the UI with paint.

**Comment by Slava0135** [comment]
Plan was to do something like this but I couldn't do it
image
Closest it gets
image

**Comment by moonheart08** [comment]
> Plan was to do something like this but I couldn't do it image Closest it gets image

Push that to this branch and i'll fix it.

**Comment by Slava0135** [comment]
Screenshot_2023-02-08_10-18-54
Screenshot_2023-02-08_10-19-40
Screenshot_2023-02-08_10-19-56
However it doesn't scale properly with UI scaling right now, anything higher than 100% may block first letter

**Comment by Slava0135** [comment]
Screenshot_2023-02-08_10-27-04
reduced width

**Comment by Slava0135** [comment]
Alternative realisation
d1
d2
d3

**Comment by mirrorcult** [comment]
still not really sure i like how this looks visually in concept

**Comment by PixelTheKermit** [comment]
I think giving the buttons a coloured border would work (similar to the last images, but with the corner pieces cut off)

**Comment by Slava0135** [comment]
> The very first concept looked the best imo. Is there some algorithm you can use to make all of the colors of equal visual brightness?

WDYM visual brughtness? Like make sum of RGB components a fixed value?

Also problem with buttons, they have blue-ish color, maybe I should make a new style with white button and black text.

**Comment by deltanedas** [comment]
convert the colour to hsv, set v to 1, convert to rgb
theres also lab but its sussy

**Comment by Slava0135** [comment]
> convert the colour to hsv, set v to 1, convert to rgb theres also lab but its sussy

noted

**Comment by jamessimo** [comment]
Something I thought about was maybe having the color only show after you clicked it on a small info panel with other data like if it’s a gas or liquid and maybe be the color printed out so not to confuse colorblind users.

**Comment by Slava0135** [comment]
this is not going anywhere

**Pull request closed without merging**
