### PR TITLE
Add secure chemistry crates and jugs

### PR DESCRIPTION
**Pull request by HoofedEar**
### Secure chemistry crates
CleanShot 2023-04-05 at 08 28 48
Secure crates for chem department stuffs

### Jugs
CleanShot 2023-04-07 at 13 38 08
Holds 200u of regents, are not made of glass, but cannot be put into dispensers due to their size.

### Other details
I also added premade jug filled with each chemical (noSpawn), and 3 premade crates that contain groups of chemicals. I know eventually we want to add the ability for cargo to order chemicals so this is one step in that direction. I opted not to add these to cargo directly so that more deliberation can be done regarding how that should be handled (groups of chems, individual chems, etc).

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added secure chemicals crates, and jugs for greater chemical storage.

### CODE REVIEW

**Comment by mirrorcult** [comment]
do they need to be secure crates?

**Comment by HoofedEar** [comment]
> do they need to be secure crates?

My first instinct was to make them secure since chemicals can be pretty dangerous/toxic/deadly to the general population or used for nefarious purposes

**Comment by deltanedas** [comment]
john syndicate will just break his radium crate open anyway, just makes it annoying (possibly life threatening) for non chem who need meds asap

**Comment by Emisse** [comment]
> 

yez

**Review by Emisse — APPROVED** [review]

**Pull request merged**
