### PR TITLE
Pen Embeds

### PR DESCRIPTION
**Pull request by Emisse**
makes nonstandard pens embed 
explosive pen
cybersun pen
cap, hop, centcom pens

🆑 
- tweak: Nonstandard pens now embed again. (explosive pen good again)

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
probably should just be limited to cyber and explosive

**Comment by metalgearsloth** [comment]
As long as the standard one doesn't idm.

**Comment by Ilya246** [comment]
> probably should just be limited to cyber and explosive

i think special pens embedding too is good, could make for funny interactions and people stealing them

**Comment by Jezithyr** [comment]
I second that, embedding pens can lead to alot of emergent behaviour. Is there a reason why standard ones don't?

**Comment by Varen** [comment]
I'd like to mention the idea of just checking if any damage was dealt when deciding whether to embed or not, which would likely sort all the issues of the case. The removal of embedding was done for "pens shouldn't embed in metal walls", but resists would take care of that and *just work*.

**Comment by LankLTE** [comment]
For now I think this is fine

**Pull request merged**
