### PR TITLE
Syndi Fireaxe Weight Nerf

### PR DESCRIPTION
**Pull request by Emisse**
light me up in the comments im ready

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Based

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
i "Lit Up" this PR by making it "Purple"

**Comment by liltenhead** [comment]
No complaints here, Probably one of the most used uplink items, maybe the most.

**Comment by EmoGarbage404** [comment]
> Two criticisms I have:
> 
> * No changelog! Evil!
> * I personally did not consider funny axe fitting in backpack a problem, it's not that much stronger than e-sword in combat: victim is very likely to share their fire with you, fire does not even work in vacuum.
> 
> It however did have nice utility of being able to axe down any wall.

Criticisms are kinda moot point considering it was already merged. Also, considering that it literally has identical stats to the normal fireaxe, it weighing less than it was an oversight more than anything.

Also the fire axe is probably the best traitor melee and definitely doesnt need a buff.

**Comment by EmoGarbage404** [comment]
> Given you are author of #9088, I find it odd, explicit size specified being oversight.
> 
> Myself I never wanted to use the axe. Size 20 item that's good only for murder (with victim igniting _you_ caveat) and removing walls (with no fire in vacuum caveat).
> 
> Now with it becoming as large as normal axe while giving away your antag status, I can see popularity of item plummet.

If you actually look at that pr, youll see that the fireaxe weighed the same as the syndicate one at that point. That was the intended balance. The explicit size is only redefined due to it being lumped into the clothing component, of which is no longer needed.

Also im pretty sure fire works in a vacuum as of right now. Its also a pretty standard infiltration tool for nuke ops and syndies.

**Comment by HoidC** [comment]
> Given you are author of #9088, I find it odd, explicit size specified being oversight.
> 
> Myself I never wanted to use the axe. Size 20 item that's good only for murder (with victim igniting _you_ caveat) and removing walls (with no fire in vacuum caveat).
> 
> Now with it becoming as large as normal axe while giving away your antag status, I can see popularity of item plummet.

it is useful for far more than murder 

> > Given you are author of #9088, I find it odd, explicit size specified being oversight.
> > Myself I never wanted to use the axe. Size 20 item that's good only for murder (with victim igniting _you_ caveat) and removing walls (with no fire in vacuum caveat).
> > Now with it becoming as large as normal axe while giving away your antag status, I can see popularity of item plummet.
> 
> If you actually look at that pr, youll see that the fireaxe weighed the same as the syndicate one at that point. That was the intended balance. The explicit size is only redefined due to it being lumped into the clothing component, of which is no longer needed.
> 
> Also im pretty sure fire works in a vacuum as of right now. Its also a pretty standard infiltration tool for nuke ops and syndies.

 doesn't work in a vaccum=-

**Pull request merged**
