### PR TITLE
Add: Obsessed Antag

### PR DESCRIPTION
**Pull request by Cyber-Finn**
## About the PR

I added the base framework for the new Obsessed minor-antagonist. This will add more chaos [huh, Skub] (and with it, more depth) to the game, it's also an OG minor-antag from SS13, so SS13 players should hopefully be hyped.

There's a lot of work to be done to get this antag on par with SS13's concept, but that will require a full overhaul of the hugging system and other systems - which will take time. I've decided to deliver this in incremental phases, because of limited time, and in hopes that it will at least build excitement for the game with the addition of the new minor-antag (even though it's very basic right now!).

## Why / Balance

This will make the game slightly more chaotic, since a (good) obsessed can kill 1~2 other players - therefore reducing the number of crew, but their targets could also be syndies, etc., so it's a numbers game. 
Note: I will, in future, be adding portable cameras and stuff like "quality-time objectives", which would help people spot an Obsessed and take action before crew go missing.

This will add depth to the game, because it adds more chaos and randomness, which SS14 players enjoy, but also adds a challenge (for people like Hugs-The-Void, Aptostitchus Conrad or Sadako Suzuki :P) - since Obsesseds aren't given any special weapons or uplinks, and can be tried as criminals (Shot, KoS or perma'ed) on sight. 
It's probably one of the hardest antags to play, because you have no weapons to start off with and need to kill 2 potentially armed people, while avoiding witnesses and security, all while your targets have comms/headsets.

Just wanted to cover "intention" here as well:
This antag is intended to still be a member of NT. So any Obsessed should - of course - complete their objectives to the best of their ability (for immersion), but they should also do their best to defend NT whenever they have a chance. This means that Obsesseds should not work with Syndies, Nukies, headRevs (unless converted), Zed overlords (IIs) or other antags that are trying to destroy NT.
They may be a murderer, but they are not a traitor.

## Technical details

I've added a new antag system (Starts off at the "ObsessedRuleSystem.cs" code file) which is heavily based on the new & improved (Thanks to @Rainfey's refactor of the) Traitor system. It's a very basic minor-antag, in that it just has 2 (kill) objectives, which have some logic to ensure that the same person isn't chosen for both objectives (for immersion's sake).
This will become a pretty complex system in future, as I build up more of the original SS13 objectives (Which make the obsessed antag special), but it's really basic for now.

## Media
The following screenshot is a close-up of the objectives given to the Obsessed. These 2 kill objectives are completely exclusive - meaning that they can never target the same person (for immersion's sake). later on, we'll be reusing the same "target of affection" for other missions, like "spend x minutes with target" or "hug target x times", to further immersion
Screenshot 2024-03-31 004202

Jealousy isn't always a given, so an Obsessed can sometimes get only 1 objective - which is to kill the target of their affection (As can be seen in one of the client screens in the video below, or the summary in the screenshot above)
The video below shows a quick test I did with 4 clients - 3 of which were obsesseds, and 1 which was not. 
The progress for the kill objectives are tracked in the same way as the Syndicate antag, and a summary displays after the round ends - to show who the Obsesseds were. You are also able to see the exclusive kill-objectives, where the target for both kill objectives are never the same person.
https://github.com/space-wizards/space-station-14/assets/146375585/6fb98adb-f7c3-4089-862c-ae85b8ff5ef0

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

I have tested this locally with a few clients running (as in my video above) simultaneously but I am unable to test this properly on server-scale.

**Changelog**
:cl:
- add: The "Obsessed" Minor-Antagonist has been added. This antag is still a work in progress, but the base framework is now in place for future dev.

### CODE REVIEW

**Comment by UbaserB** [comment]
Isn't this literally re-flavoured terminator? I would think there should be an objective for watching them (while alive) for a certain amount of time; like a stalker.

**Comment by Cyber-Finn** [comment]
> Isn't this literally re-flavoured terminator? I would think there should be an objective for watching them (while alive) for a certain amount of time; like a stalker.

So at present, you're 100% right, but in future there will be a few other objectives, more geared towards literally stalking your target.
The SS13 objectives are along the lines of: "Spend x minutes with target", "hug target x times", "take x photos of target", etc.
The SS13 obsessed is a literal stalker - and there are some really cool intricacies, like being jealous of people the target works with, etc. It's exactly what's excited me to start working on it.
As more content gets added to the game (by everyone), we can start looking at applications of DNA and cloning, etc. - lots of different ways to make the antag crazy!

These are all things I want to add, but the logistics behind it is a bit crazy right now - and they make this a massive task. So I just wanted to get the base framework done, then start overhauling and adding more as I go along.
Feels like a big-bang approach would take forever and eat into my limited personal time.

I dont even play this game anymore, just want to add something that I think OG SS13 players will like.

**Comment by UbaserB** [comment]
Just make sure to PR a design doc, that's the minimum requirement for adding new antags iirc

**Comment by Cyber-Finn** [comment]
> Just make sure to PR a design doc, that's the minimum requirement for adding new antags iirc

Thanks for this! I've got no idea how to just yet, but will look into it. 
Really appreciate your help!

**Comment by FungiFellow** [comment]
I don't think this should be merged until objectives beyond "Kill X" are ready. Otherwise its just some shitter with an antag permit and not a stalker

**Comment by asperger-sind** [comment]
This isn't really challenging or unique as it stands, this is essentially just an uplink-less traitor, since most traitor objectives boil down to "permakill Urist".

This isn't unique because most other antags fill the niche of "kill key target", some have it as objectives, some have it as optimal things to do.

Having to keep the target alive for a period of time before killing them, along with the already mentioned tasks like hugging them or standing next to them or talking to them for X minutes/actions would already make this a much better antagonist.

This isn't challenging (unless you speak purely in relative to other antags) because the game offers a wide variety of tools for non-antags that can be used to kill people, while uplink-less traitor rounds have been common since several years ago and the obsessed objectives aren't too hard on their own.

Having proper objectives would already make the antag better because you can't just steal a stun baton or throw CLF3 cryobeakers at Urist, you actually need to sit through a good chunk of the round interacting with them, which may give rise to suspicion.
Alternatively, some hard-to-metagame debuffs could be applied to the obsessed when they are near their target, occasional laughter, vision debuffs, etc. just piggyback of the yandere genre that's probably what SS13 did anyway.

**Comment by Terraspark4941** [comment]
> This isn't really challenging or unique as it stands

From Cyber-Finn:
> These are all things I want to add, but the logistics behind it is a bit crazy right now - and they make this a massive task. So I just wanted to get the base framework done, then start overhauling and adding more as I go along.

I would recommend drafting this, making a design doc, and working on more draft PRs until all the content is practically ready (just make each PR require the previous base PRs aswell)

**Comment by metalgearsloth** [comment]
Antags are currently frozen and getting reworked so you will probably need to rewrite a lot of this pr when it's done.

**Comment by FairlySadPanda** [comment]
Just to add onto Sloth's note, if you want to iterate on this for the time being you should consider submitting the proposal to Docs. https://github.com/space-wizards/docs

I like this idea as a theme - an antag that isn't just an 80s movie reference? incredible - but as others have said it's a bit thin-on-the-ground atm because murder-the-thing isn't that interesting.

**Comment by mirrorcult** [comment]
unfrozen with emo's selection changes. needs to be updated for that as well as a design doc

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Pull request closed without merging**
