### PR TITLE
Update Core

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Add biogens, fix some minor issues on the map, and revert the glass window changes cause I got a better idea.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by slarticodefast** [comment]
Still some directional windows in cargo
grafik

**Comment by UbaserB** [comment]
oh thanks i missed those

**Comment by UbaserB** [comment]
should be good now

**Comment by Emisse** [comment]
test fail

**Comment by Spessmann** [comment]
smh my head image

**Comment by UbaserB** [comment]
im cursed to oblivion ungngunvngng

**Pull request merged**
