### PR TITLE
Engineering Chunk Salvage

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Adds a single new salvage wreck, a particularly large one at that. It contains various things you would find in an engineering department such as gas canisters, an atmos section, what was once a PA and singulo setup, a CE's office overrun by spiders, multiple generators, fuel for said generators, an assortment of monsters to defend the loot, a big spider nest, and the holy experimental welding tool for all your wall cutting needs. Very dangerous, very valuable, very big.

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Map size looks like it's going to drop ticks?

**Comment by UbaserB** [comment]
Yay you finally PR'd it 🎉

**Comment by JoeHammad1844** [comment]
you should add one or two plasma tanks since plasma is limited now

**Comment by Blackern5000** [comment]
> you should add one or two plasma tanks since plasma is limited now

cargo is probably just gonna sell them and everything else is plenty of cash if you get this.

**Comment by Blackern5000** [comment]
> Map size looks like it's going to drop ticks?

is this a request to shrink it or just a comment on how large it is?

**Comment by Emisse** [comment]
too many generators

**Comment by Blackern5000** [comment]
> too many generators

some have been removed and I shaved off a decent portion of the asteroid to cut down size.

**Pull request merged**
