### PR TITLE
Anuran Species (frog draft)

### PR DESCRIPTION
**Pull request by brainfood1183**
Anuran species draft. Adds a frog/toad race to ss14. Details such as positive and negative traits being discussed and worked on.

https://github.com/space-wizards/space-station-14/assets/113240905/252548f3-f8fd-4dcd-926d-cd1a461e62c9

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
probably should take 10% less slash and move slightly slower

**Comment by deltanedas** [comment]
idk have you ever stabbed a frog they dont take it very well

**Comment by JoeHammad1844** [comment]
erm actually thats piercing damage

**Comment by CatMagic1** [comment]
How about we slap a bunch of resistances on it, make it only be able to eat uhhh... rocks, and call it a day.

**Comment by lzk228** [comment]
another human reskin

**Comment by deltanedas** [comment]
bloated meat/mobs get flies flying around them, froggy can eat them

**Comment by KaiShibaa** [comment]
> another human reskin

Different looking species is a pain in the butt because you have to resprite everything on them (Vox). I don't see what's wrong with this. Especially since it's still in draft.

**Comment by lzk228** [comment]
IMG_20231016_065255

**Comment by metalgearsloth** [comment]
Needs a design doc backing it if someone gets time.

**Pull request closed without merging**
