### PR TITLE
Dehydrate Diona on heat damage, Diona absorb chems

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Rather than Diona igniting every time they're hit by heat damage, heat damage will dehydrate Diona, and when a Diona is at 0 dehydration they will then ignite each time they take heat damage

Dionas will now also absorb chemicals through their feet at a pretty slow rate.

## Why / Balance

Diona are kind of unbalanced in a weak way due to how powerful heat damage is against them, this is kind of an in-flavor way to handle that weakness.

I made Diona absorb chemicals through their feet just for there to be some canonical reasoning for them not wearing shoes. Now they can stand in puddles to get nutrients or whatever.

## Technical details

Adds a PreventedByHydration bool to prevent ignition if properly hydrated
Adds a DehydrationMultiplier float so you can adjust how much heat damage dehydrates

StepTriggeredOffEvent used to be for "Does this entity intersect with the step trigger" and "Did this entity just step off of this"
These kind of completely opposite interactions made the StepTrigger code incompatible with what I needed out of it, so I separated it
- StepTriggeredIntersectEvent is now the default StepTrigger event, "Is this entity intersecting with the step trigger". Updated any use of StepTriggeredOffEvent to use this instead.

StepOn was renamed to HasStepOnOffTriggers, CurrentlySteppedOn's description was updated to be more clear that this only ever contains anything when HasStepOnOffTriggers is true
- StepTriggeredOnEvent changed to have a default speed of 0, used for mines and puddles to figure out if something is currently standing on them. When Dionas stand on a puddle, it adds them to the CurrentlySteppedOn Hashset.
- StepTriggeredOffEvent now only used when entity steps off of thing, puddles were changed to slip on this event

All the logic related to step triggers were updated to reflect these changes. The StepTrigger system now has split checks depending on whether HasStepOnOffTriggers is true, previous assumptions caused the code to do dumb things, like not properly adding people to the CurrentlySteppedOn hashset, or not properly removing them.

A puddle absorption component and system were added, every single tick an entity that has the component and is in a puddle's CurrentlySteppedOn Hashset will begin to absorb some of the puddle's contents into their bloodstream.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Showcase of Diona dehydration

https://github.com/space-wizards/space-station-14/assets/58439124/82ff06ac-43ac-4460-8cfe-7ae41101844f

Showcase of Diona absorbing chems with their roots
https://cdn.discordapp.com/attachments/310555209753690112/1248551466843635753/2024-06-07_01-16-46.mp4?ex=666ca56a&is=666b53ea&hm=aeb6f1c713297edf506de65f4221ccebe5ea4bf86fc5eed27470eba58ba9fafb&

## Breaking Changes
StepTriggeredOffEvent was split into StepTriggeredIntersectEvent and StepTriggeredOffEvent
StepTrigger's StepOn field was renamed to HasStepOnOffTriggers

**Changelog**

:cl:
- add: Diona get dehydrated when they take heat damage, and when they're fully dehydrated they ignite on heat damage.
- add: Diona now absorb chemicals through their roots.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This PR is closed due to the feature freeze from May 10th to June 14th. Comment after the freeze ends to have it re-opened.

**Comment by Plykiya** [comment]
I WOULD LIKE TO HAVE THIS RE-OPENED

**Comment by Plykiya** [comment]
something people have been throwing around is letting Diona just wear shoes
if that happens, the chem absorption will only work if they have their shoes off

**Comment by DieselMohawk** [comment]
I'm worried about what will happen during zombie rounds where the floor is covered in zombie blood half the time. Other than that, it's a neat feature.

**Comment by Clone0401** [comment]
> I'm worried about what will happen during zombie rounds where the floor is covered in zombie blood half the time. Other than that, it's a neat feature.

apply glue to your feet :)

(Another thing i have talked about ALOT is dionae having a slow built in magboots (like 50%speed) and metabolism what they walk over like in this, and yea yea wyci)

**Comment by Plykiya** [comment]
> I'm worried about what will happen during zombie rounds where the floor is covered in zombie blood half the time. Other than that, it's a neat feature.

I was asked to turn this into a toggle-able action, so I guess you can prevent things like that
I'll work on it I guess, but overall doesn't change the functionality of the PR

**Comment by Plykiya** [comment]
gah, EntityEffects

**Comment by Plykiya** [comment]
I'm going to split this PR into two

**Pull request closed without merging**
