### PR TITLE
Added Survival to the secret rotation

### PR DESCRIPTION
**Pull request by wafehling**
## About the PR
I added Survival to the secret rotation list, with a 10% chance of being picked. (Happy to make that chance higher, but don't wanna push my luck.)

## Why / Balance
With Revs still living at the farm upstate, happily riding around on ATVs and injecting themselves with space pens, the secret rotation has become increasingly predictable and easily metagamed with only 3 possible (And purely PvP focused, I might add) options.

I've seen admins manually choose Survival rounds multiple times, and every time it's positively received. And after all, the game is about a "shift on a space station gone horribly wrong", and what fits the spirit better than chaotic events spiraling out of control while the crew tries to keep the holes patched and the lights on?

## Technical details
A tiny YAML change, nothing serious to worry about here.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Only thing it'll break is the predictable meta of possible game modes 😉 

**Changelog**
:cl:

- tweak: Secret mode has become more secret, with the 4th option Survival added to the rotation.

### CODE REVIEW

**Comment by Kadeo64** [comment]
eeeeehhh I feel like survival is a fun admin event but not something you want to play every 10ish rounds. maybe 5% would be better?

**Comment by vorkathbruh** [comment]
5% is good, survival should be pretty rare but having it in rotation makes it harder for individuals to metagame the gamemodes (e.g. "Oh its quiet for 30 mins? Must be nukies!")

**Comment by wafehling** [comment]
> 5% is good, survival should be pretty rare but having it in rotation makes it harder for individuals to metagame the gamemodes (e.g. "Oh its quiet for 30 mins? Must be nukies!")

That'd be 5 nukie rounds or 13(!) traitor rounds for every 1 survival round, it's barely a blip...

**Comment by mirrorcult** [comment]
survival was removed because it was pretty terribly coded (by me) and literally broken in a couple ways and i was actively working on a better version of it

admittedly i have been doing other things with my life than that so i would be Ok with this getting readded at 10-15% for now

**Comment by mirrorcult** [comment]
also changelog is not formatted correctly

**Comment by wafehling** [comment]
> also changelog is not formatted correctly

Fixed!

**Comment by mirrorcult** [comment]
image
should be like this

```
**Changelog**
:cl:
- tweak: (thing)
```

**Review by mirrorcult — APPROVED** [review]

**Comment by K-Dynamic** [comment]
Well this was unexpected

**Comment by deltanedas** [comment]
selfantags keep winning

**Comment by potato1234x** [comment]
do not revert pls and thanks :clueless:

**Comment by Carmell0** [comment]
I like this change!

**Pull request merged**
