### PR TITLE
Add collision sound effects to clown horn and some plushies (#27882)

### LINKED ISSUE #27882: Clown horn just make a thud when hitting walls.
## Description
Items one would expect to have unique wall hit sounds make the same leathery sounding thud as everything else.

**Reproduction**
- Throw clownhorn around expecting it to honk on wall hit
- Disappointing thud :(

**Additional context**
i am unbelievably disappointed that the developers don't think of everything.

**Proposed solution**
For the clownhorn, plushies, and related fluff specifically, maybe allow wall hits to activate the item's effect? This would also require repeating the sound name fewer times than the current EmitSoundOnCollideComponent requires.

Or you could just use the existing solution and solve this in like 5 seconds for easy bugfix cred. (Read: If you're here for the beginner friendly label, do this! It's simple.)

**Items that violate expectations**
- bikehorn (BikeHorn)
- carp plushie (PlushieCarp)
- holocarp plushie (PlushieHolocarp)
- human plushie (PlushieHuman)
- lizard plushie (PlushieLizard)
- honestly just review all the plushies, they all mismatch.
- [looking for more]

### PR DESCRIPTION
**Pull request by taurie**
## About the PR
- Added EmitSoundOnCollide type to clown's bike horn as well as plushies with existing sound effects.

## Why / Balance
Fixes #27882

## Technical details
No code.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
No breaking changes.

**Changelog**

- add: Sound effects to bike horn, plushies when they collide with an object (example: thrown)

### CODE REVIEW

**Comment by slarticodefast** [comment]
I think you forgot to rename it to EmitSoundOnCollide for the two lizard plushies. And you have a capitalization typo for the vox one. This seems to cause the build error.
Fun little change otherwise :)

**Comment by taurie** [comment]
Thank you for the tip. This is my first contribution to any open-source project :) I've fixed the things you had mentioned.

**Comment by taurie** [comment]
I'm still figuring out Git, made an oopsie. I'm going to reopen this when my other PR gets merged or whatever. https://github.com/space-wizards/space-station-14/pull/28169

**Comment by slarticodefast** [comment]
Looks like you made the description changes in the same branch as the sound effect changes. When you pushed that commit to your remote, Github added it to your existing PR. What you should do is make a separate branch (from your master branch, which should contain no local changes) for every PR you intend to make. And if you mess up something by accident and want to revert it, I can recommend looking at https://ohshitgit.com/

**Pull request closed without merging**
