### PR TITLE
Textile crate

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR 
Adds a textiles crate for Cargo to order. Contains 60 cloth and 30 durathread for 1000 space bucks

**Changelog**

:cl: checkraze
- add: Added textiles crate to cargo

### CODE REVIEW

**Review by AJCM-git — APPROVED** [review]

**Comment by AJCM-git** [comment]
rerun tests, also the price is a little high for something kinda useless like cloth, try with 800

**Comment by Cheackraze** [comment]
> rerun tests, also the price is a little high for something kinda useless like cloth, try with 800

my reasoning was the durathread + 1000 is right in line with all other materials crates. But I can lower it, I agree its pricy for some cloth, however its also one of the only sources for cloth.  I'll make sure tests pass and then possibly change the price

**Comment by EmoGarbage404** [comment]
> my reasoning was the durathread + 1000 is right in line with all other materials crates. But I can lower it, I agree its pricy for some cloth, however its also one of the only sources for cloth.  I'll make sure tests pass and then possibly change the price

Just gonna comment that you can butcher jumpsuits for cloth, arguably making it the most available material in the game.

**Review by AJCM-git — APPROVED** [review]
So doing some math i think 1000 is fine since if cargo manufactured uniforms out of a crate of this they can make like 5000 bucks

**Pull request merged**
