### PR TITLE
Add the Zombie, a new cocktail

### PR DESCRIPTION
**Pull request by dragonryan06**
## About the PR

Adds a new cocktail the bartender can make called the Zombie (based on the real-life cocktail of the same name). It is made with 2 parts rum, 1 part grenadine, and 1 part zombie blood. It is rather strong, only slightly weaker than absinthe. (The real life cocktail is said to make you a zombie).

This is the first sprite I've ever made for this game too, I'm fully open to criticism; I tried to make it look different than all the other mixed drinks I could think of but let me know if it needs improving in any way.

## Why / Balance

I heard about this drink for the first time earlier this week and thought it would be funny if, during the zombie apocalypse, the bartender could opt to run around collecting zombie blood for a rare drink.

## Technical details

Added a new drink, metamorphic glass sprites, and the reaction to create it.

## Media

zombiedesc

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: New cocktail: the Zombie.

### CODE REVIEW

**Comment by WhiteGorila** [comment]
They should change zombie antags to instead spawn with a romerol pill so we can make spiked zombie drinks

**Comment by SaphireLattice** [comment]
Not sure on it being possible to make only with zombie blood. Kinda makes it rather unique in an ashtray stressful situation. Which is neat but not the most practical.

**Comment by thetolbean** [comment]
> Not sure on it being possible to make only with zombie blood. Kinda makes it rather unique in a rather stressful situation. Which is neat but not the most practical.

I understand why this could be annoying, but I believe that it's impracticality is what adds to the humor around the drink. I wouldn't be surprised if I saw pun pun or a bartender running around during a zombie apocalypse with a syringe full of zombie blood

**Review by TheShuEd — APPROVED** [review]

**Review by SlamBamActionman — APPROVED** [review]
Graaaahr...

**Pull request merged**
