### PR TITLE
update UpdateVisuals to use Destructible thresholds

### PR DESCRIPTION
**Pull request by bhespiritu**
## About the PR 
Addresses #2959.

It changes it so that window's visual cracking rely on the Destructible component's first destruction threshold

### CODE REVIEW

**Review by PaulRitter — CHANGES_REQUESTED** [review]
you should completely remove `_maxDamage` & refactor the remaining code. you'll also have to adjust the yaml in `windows.yml`.

**Comment by bhespiritu** [comment]
Okay, the changes have been made. I had a feeling that that was what I was supposed to do initially, but I just wanted to make sure.

**Review by PaulRitter — CHANGES_REQUESTED** [review]
you'll also need to add a `DestructibleComponent` with the proper maxdamage to the yaml-prototypes

**Comment by bhespiritu** [comment]
It appears that there already is a Destructible component added to the prototypes with the correct maxDamage values.
yaml-data

This is the case for every window that is defined in the windows.yml file

Is there somewhere else that I need to edit it as well?

**Review by PaulRitter — APPROVED** [review]
looks good, you're correct. my bad :P

**Pull request merged**
