### PR TITLE
New Salvages to explore

### PR DESCRIPTION
**Pull request by retequizzle**
Pretty self-explanatory. Three new salvages for the salvage specialists to work with. I've made them a bit more dangerous than your usual salvages but the rewards balance out the danger on them to compensate. 

Library Wreckage (To be omitted, too many library wrecks as is):
Probably the easiest of the three to access and loot. Variety of scattered papers, a few random books, board game crate behind the desk and some minor drip/fun stuff to take back. No space carp to deal with either, so feel free to come and go from this one as you please. Do mind the artifact in the center... it's totally not responsible for the fact that the library got warped from the station or anything. :^)
https://i.imgur.com/jyToxV8.png
https://i.imgur.com/GteVHy6.png

Pirate/Gambling Barge:
Pretty straightforward. Gambling table in the center with a lot of pirate-themed goodies, some space carp spawners and a fair bit of loot for everyone involved. Also a dead parrot crate in the corner because... well, there's really not a lot of pirate themed stuff I could use. I DID WHAT I COULD ;-;. It's also going to be a decent source for thrusters/gyros so salvage has a reason to try and salvage rather than order these parts. Even has a specific pirate goodie behind the wall (I got permission from Pancake before adding it) and made sure lighting didn't reveal anything. Extra picture with full lighting/shadow/FOV toggles to showcase that.
https://i.imgur.com/PU3hFKW.png
https://i.imgur.com/kTF0p9W.png

EDIT: Updated gambling barge to reduce gold from a full stack down to 6 bars, added 4 more spawners for a total of 10 potential space carp at start, and while I know having specific artifacts is a bad idea, I opted to make it more dangerous by adding in an angry mob artifact. There's enough risk involved with this that they will _have to consider ramifications of dying for once on a salvage, aka skill issue._

Cargo-themed Salvage:
Realized while doing these that there was not a lot of cargo-themed salvages in salvage, so I decided to change that. Has some staples that you'd expect from a cargo department (wardrobe, salvage crates, canisters) and a flare gun with beanbag shells. I also added an artifact to this on the conveyor belts.
https://i.imgur.com/q53hqaa.png
https://i.imgur.com/iroyTam.png

EDIT: Changed artifact to random artifact spawner for more variety.

As these are my first map submissions, please let me know if there's anything you'd like to see in the future, or stuff you'd like to see me not do in the future as well. I had a lot of fun making these, and I look forward to doing more if people like them.

### CODE REVIEW

**Comment by mirrorcult** [comment]
the library one kind of infringes on the already-existing library salvage

pirate/gambling barge needs to have less gold or more danger, probably both

cargo one is good

**Comment by Elijahrane** [comment]
Can you replace the good feeling artifact with a random artifact spawner? That will only be the second salvage map with an artifact so explicitly choosing the type is bad imo

**Comment by retequizzle** [comment]
> the library one kind of infringes on the already-existing library salvage

Completely fine with this one not being used, it was the first one I made and probably the one I'm least attached to as a result. I'll still work on it to try and give it a more organic feel but no worries.

> pirate/gambling barge needs to have less gold or more danger, probably both

I can do both, I wasn't sure what constituted "too much" in terms of asset usage but I can remove the full stack of gold and just put a few bars, then more space carp. I'm also open to suggestions on what else I can do to make this barge dangerous.

> Can you replace the artifacts with random artifact spawners? Right now there's only 1 map with artifacts so I don't think choosing an explicit type is good imo

I'd be happy to, the only reason I didn't was because I saw the ones with proximity effects like cold, radiation, heat, etc and didn't want to risk someone bringing that into the station. I'll set them to random and see what happens, if it ends up being something trolled with I'll roll it back to junk spawner or good/bad feeling artifacts.

**Comment by Elijahrane** [comment]
> I'd be happy to, the only reason I didn't was because I saw the ones with proximity effects like cold, radiation, heat, etc and didn't want to risk someone bringing that into the station. I'll set them to random and see what happens, if it ends up being something trolled with I'll roll it back to junk spawner or good/bad feeling artifacts.

That's kind of the point of artifacts imo, and preferable to people being able to metagame which one it is every time

**Comment by retequizzle** [comment]
> > I'd be happy to, the only reason I didn't was because I saw the ones with proximity effects like cold, radiation, heat, etc and didn't want to risk someone bringing that into the station. I'll set them to random and see what happens, if it ends up being something trolled with I'll roll it back to junk spawner or good/bad feeling artifacts.
> 
> That's kind of the point of artifacts imo, and preferable to people being able to metagame which one it is every time

Valid point. I'll keep the randomized artifacts in mind for future maps unless told to do otherwise. One randomized artifact and one intentionally used as a mob spawner on this rotation should be fine though.

**Comment by mirrorcult** [comment]
- you haven't added salvage prototypes for these, so they'll never actually get loaded
- you have 2 duplicate files in the root directory that need to be removed

**Comment by retequizzle** [comment]
> * you haven't added salvage prototypes for these, so they'll never actually get loaded

How would I go about adding the prototypes in? Sorry if this is a silly question, I'm still learning the basics.

> * you have 2 duplicate files in the root directory that need to be removed

I'll get this corrected asap

**Comment by mirrorcult** [comment]
> > * you haven't added salvage prototypes for these, so they'll never actually get loaded
> 
> How would I go about adding the prototypes in? Sorry if this is a silly question, I'm still learning the basics.

take a look at `Resources/Prototypes/Maps/salvage.yml`, should be fairly easy to figure out from there

**Comment by retequizzle** [comment]
> > > * you haven't added salvage prototypes for these, so they'll never actually get loaded
> > 
> > 
> > How would I go about adding the prototypes in? Sorry if this is a silly question, I'm still learning the basics.
> 
> take a look at `Resources/Prototypes/Maps/salvage.yml`, should be fairly easy to figure out from there

After hitting the dumbest block in the world and not knowing how to merge it, it's added. Let me know if anything's off with it.

**Pull request merged**
