### PR TITLE
Removie Remmie and Hamlet's biting

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR

There's really no point for this other than the role being used for biting lights or random people, or pets.
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Hamlet and remilia cannot bite anymore.

### CODE REVIEW

**Comment by Aisu9** [comment]
no more way to self Defense as Hamlet when crew try to microwave your ass, no? more way to support your Traitor Master as Remi

**Comment by dmnct** [comment]
As someone who never got into trouble as Remi or Hamlet, please dont! Being able to bite gives them character and more ways to interact. (For example Biting the air, biting objects non-destructively, sometimes even biting players just a bit can be appropriate)

Is this a huge issue giving admins frequent work or something?

**Comment by metalgearsloth** [comment]
> no more way to self Defense as Hamlet when crew try to microwave your ass, no? more way to support your Traitor Master as Remi

Why do two pets, both shitter magnets (remi in particular being difficult to hit), get combat mode and not all the others.

**Comment by DogZeroX** [comment]
./me bites the person.

**Comment by EmoGarbage404** [comment]
Hamlet players when they're not the center of the universe.

(Why is hamlet even a ghost role? They're the only pet with that privilege)

**Comment by DogZeroX** [comment]
I dunno, I don't even like remilia.

**Comment by dmnct** [comment]
> ./me bites the person.

Yeah that is nowhere near as expressive, noticeable and impactful as the attack animation+sound

(and a good argument for why more "built-in emotes that actually do something" would be good, but thats a whole other topic)

**Comment by Aisu9** [comment]
and Remi is a ghost role that follow their master's alignment, if they can't break stuff what would be their utility for a traitor? one wide swing and she's dead for reference

**Comment by DogZeroX** [comment]
Remi is a fluff thing, if you want a combat familiar you have cerberus. I don't even want remmie to exist so this is a generous PR.

**Comment by Aisu9** [comment]
i'm not talking about a combat familiar, Remi is only good as "support"
small reminder that absolutely no one can see in the dark, you Remi, Cerberus, Captain, Engi, everyone are slave to light

**Comment by Aisu9** [comment]
so she would be only good at keeping the crew busy for 5 seconds while your storming somewhere else with cerberuses

**Comment by DogZeroX** [comment]
It's not an antag item, not sure what you're going off about.

**Comment by Aisu9** [comment]
Chaplain's familiar is the only familiar that adopt their Master affiliation.
Normal Chaplain, normal Remilia
Traitor Chaplain, Traitor Remilia (she is allowed to commit antagonist activity)
Sure the bible is not an antag item, it's a support tool that is useful for both side.

**Comment by dmnct** [comment]
What if Remilia/pets got electrocuted to death if she destroys a light. Would that be good enough? Is this an issue with other animals that are not nearly as tiny and fast? If there is some other frequent shittery this is supposed to address can you please share?

**Comment by Aisu9** [comment]
Chaplain should just have the option to terminate Remi on command if it's such an issue.
Such problem should be deal without mechanic change

**Comment by QuietlyWhisper** [comment]
I honestly would prefer the chaplain to use cerb for antag shit due to nonantag chaplains telling remilia to attack people from an admin POV personally

**Comment by Emisse** [comment]
i think them being able to bite is fine, they are pretty easy to kill especially since wide swing got implemented, and you can also pick up hampston

**Comment by deltanedas** [comment]
hamptee needs a way to get out of his cage

**Comment by lzk228** [comment]
>griefer
ban griefer? no
change the game code? yes

remmie doesn't need changes, but hamlet just should has less damage

**Comment by metalgearsloth** [comment]
Hamlet being able to bite mice is pretty silly and I've only ever seen remi's combat mode used to grief lights.

**Comment by Anzarot121** [comment]
RIP nukie nubies killed by Remilia.

**Comment by DerbyX** [comment]
I'm all for removing Remi's biting for the multiple times I've seen them break lights, but implementing Errant's idea of electrocuting the animals if they do break the lights is a better solution in my opinion rather than removing biting in general.

**Comment by Myakot** [comment]
The issue with hampter still being the only one with a privileged roundstart ghost role is there too.

**Comment by EmoGarbage404** [comment]
i think if hamlet's ghost role was removed people would lynch me but then again i ain't too partial to my neck anyways.

**Review by metalgearsloth — APPROVED** [review]

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by basyachok** [comment]
another codechange existing only to 1984 normal community and to do admin's work easier.
though i agree they should be removed
but why make useless things more useless

**Comment by dmnct** [comment]
Can we close this now that lightbulbs kill biters?

**Comment by deltanedas** [comment]
remi is hard to hit hampter is not so keep hampter bite:
- needs a way to defend himself against shitters
- needs a way to get out of his cage
- if hampter wants to randomly attack you can pick him up or whack him easily

**Comment by Veritius** [comment]
getting out of his cage is actually pretty significant yeah

**Comment by Tegotia** [comment]
Since it looks like this is about to be merged, I want to make one last plea to reconsider this, at least until a less severe option has been tried and proven not to be enough. For as much as people have dismissed the opinions of people who like playing these roles as "main character syndrome", I think there _is_ some RP value in letting these roles have a bite. It is effectively an emote for these pets, and in my opinion makes them feel like they have so much more life and personality. That is worth at least trying to preserve.

I of course don't know what goes on behind the scenes with ahelps about these roles, but I would like to believe that a less extreme solution like reducing the damage for these pets can reduce the disruption they cause enough to let them keep their bite in some form. Please let those of us who try to use it responsibly not lose something because of people who don't understand how to play a social game.

**Comment by HoidC** [comment]
> Since it looks like this is about to be merged, I want to make one last plea to reconsider this, at least until a less severe option has been tried and proven not to be enough. For as much as people have dismissed the opinions of people who like playing these roles as "main character syndrome", I think there _is_ some RP value in letting these roles have a bite. It is effectively an emote for these pets, and in my opinion makes them feel like they have so much more life and personality. That is worth at least trying to preserve.
> 
> I of course don't know what goes on behind the scenes with ahelps about these roles, but I would like to believe that a less extreme solution like reducing the damage for these pets can reduce the disruption they cause enough to let them keep their bite in some form. Please let those of us who try to use it responsibly not lose something because of people who don't understand how to play a social game.

And the lord said “my child you have access to emotes as an animal press TAB”

**Comment by Tegotia** [comment]
> > Since it looks like this is about to be merged, I want to make one last plea to reconsider this, at least until a less severe option has been tried and proven not to be enough. For as much as people have dismissed the opinions of people who like playing these roles as "main character syndrome", I think there _is_ some RP value in letting these roles have a bite. It is effectively an emote for these pets, and in my opinion makes them feel like they have so much more life and personality. That is worth at least trying to preserve.
> > I of course don't know what goes on behind the scenes with ahelps about these roles, but I would like to believe that a less extreme solution like reducing the damage for these pets can reduce the disruption they cause enough to let them keep their bite in some form. Please let those of us who try to use it responsibly not lose something because of people who don't understand how to play a social game.
> 
> And the lord said “my child you have access to emotes as an animal press TAB”

That's missing the point. It's not just that these animals need _some_ emote, it's that I think this particular action lets players in that role express themselves in a much more active way than you get with some text and maybe a sound effect.

**Comment by Vordenburg** [comment]
You could give them a non-damaging bite action that plays a sound, does a popup, etc.

**Comment by Tegotia** [comment]
> You could give them a non-damaging bite action that plays a sound, does a popup, etc.

If the demand is strictly that these roles not be able to do any damage whatsoever then I think it's worth doing it that way. That would be achievable with just setting their damage values to 0, no? Or would that cause some janky damage math somewhere?

**Comment by dmnct** [comment]
If you remove Remi's bite now, shitters will no longer be able to unwittingly kill themselves breaking a light. Checkmate

**Comment by dmnct** [comment]
> that may sound strange, but you can actually ban shitters

It's way funnier to have them zap themselves and maaybe gives them an opportunity to stop and improve their attitude

**Comment by DogZeroX** [comment]
Reopen when you keep working on it.

**Comment by deltanedas** [comment]
> you

:trollface:

**Comment by Xkallubar** [comment]
Might as well delete the game so admins don't have to do their job anymore.

**Pull request closed without merging**
