### PR TITLE
New sprite for shutle gyroscope

### PR DESCRIPTION
**Pull request by shaeone**
## About the PR 
This is a new sprite for the gyroscope. Nothing has been changed in the code but on the json, so it will work the same way as the original.

**Screenshots**
<a href="https://gyazo.com/57259ac8455f861f7b1df57cb76b3938">Image from Gyazo</a>

**Changelog**

:cl:
- tweak: Modified gyroscope sprite.

### CODE REVIEW

**Comment by mirrorcult** [comment]
sprite is very blurry and the contrast doesn't fit super well with the rest of the sprites in the game

**Comment by ElectroJr** [comment]
The changelog should have a `add`, `remove`, `tweak`, or `fix` prefix, e.g.,

:cl:
- tweak: Modified gyroscope sprite.

**Comment by PaulRitter** [comment]
> sprite is very blurry and the contrast doesn't fit super well with the rest of the sprites in the game

i agree. the sprite as is looks very cool, but it just doesnt fit in well with the other sprites imo.

**Comment by shaeone** [comment]
I will have a look to the sprite to make it clear.

**Comment by shaeone** [comment]
I have changed the sprite. Still working on seeing if it is possible to add some effects, so no PR yet

<a href="https://gyazo.com/5e0b429f5d2ad5423c526489c78c9df4">Image from Gyazo</a>

**Comment by PaulRitter** [comment]
fits in way better already, gj 👍

**Pull request closed without merging**
