### PR TITLE
Juice that makes you Weh! (but real!)

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Adds juice that makes you Weh, a chemical for fun, like space lube and glue.

- Obtainable from the two lizard plushies, 30u.
- Has a 50% chance to make you weh.
- At 50u, polymorphs non-animal mobs into lizards.
	- At 50u, also removes 20u of itself.
- Consumes 0.25u per tick.
- Weh

## Why / Balance

Added by popular demand

## Media
image
[This is an old video that demonstrates the effect.](https://www.youtube.com/watch?v=HXq8_g5_ZGw&ab_channel=Whisper)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Adds new emotes to existing species, may conflict downstream vanilla species if changed

**Changelog**

:cl: Whisper
- add: Added juice that makes you Weh! Juice a lizard plushie today!

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
weh

**Comment by foob1** [comment]
I think a better name for the chemical would be wehzine

**Comment by QuietlyWhisper** [comment]
need to update the LOCALIZATION FILES!!!!

**Comment by MrGreen006** [comment]
Does this imply that the lizard plushies are like water bags and you just hear the juice when you squeeze it. I gotta understand the very important lore implications from the funny weh juice.

**Comment by Krunklehorn** [comment]
Please capitalize the j in the description, it's making me weh.

**Comment by VektorZ1** [comment]
weh

**Comment by UbaserB** [comment]
weh

**Comment by K-Dynamic** [comment]
Polymorph them into weh plush

And polymorph them into lizardpeople permanently at like 200u :trollface:

**Comment by potato1234x** [comment]
me on my way to the secret weh room on core to steal all the plushies (i will spike all the bartenders drinks)

**Comment by IProduceWidgets** [comment]
Love it. Another certified great Whisper idea.

I don't mind the name, it's funny even as a mouthful, but if you're looking for test balloons for it here are a few I thought up.

Wehmium

Lacertilia -- the taxonomical name for lizards.

Lacerta -- the latin word for lizard (also it sounds like a name brand drug lmao)

Squamata / Squamate -- similar to above, a name for animals that have scales. 

Exenatide -- an actual drug originating from Gila Monsters that treats diabetes.

**Comment by Boaz1111** [comment]
OH GOD I REMEMBER WHEN THIS GOT MERGED ON ONE OF THE SERVERS
EVERYONE WAS DRINKING IT EN MASSE

**Comment by Kadeo64** [comment]
is the polymorph effect permanent? funny if it is but I feel like we need some kind of un-polymorph chemical.

**Comment by Kukutis96513** [comment]
question, does it just turn them into a lizard, or a humanoid lizard?

**Comment by LankLTE** [comment]
Turns them into an animal lizard & reverts after 20 seconds

**Comment by Kadeo64** [comment]
would be funny if we could get this for the other plushie species too, moth plushie to turn people into mothroach, arachnid plushie to turn people into tarantula, vox plushie to turn people into vox (unrevertable :trollface:)

**Comment by deltanedas** [comment]
tarantula doorpry meta real

**Comment by Kadeo64** [comment]
> tarantula doorpry meta real

i mean you can spend like 5k spesos per 20 seconds of tarantula time  or you can just get jaws of life from science and do the same thing

**Comment by MouseHatsForAll** [comment]
> would be funny if we could get this for the other plushie species too, moth plushie to turn people into mothroach...

I love this idea. Just the concept of someone with a hypopen able to go  "I don't like you, mothroach time for you."

**Comment by ViceEmargo** [comment]
I am going to OvWEHdose so hard.

**Comment by QuietlyWhisper** [comment]
Finally all tests have passed we are so back

**Comment by K-Dynamic** [comment]
It is time

For foam weh juice grenades

**Comment by felineace** [comment]
> It is time
> 
> For foam weh juice grenades

Wehpons of mass destruction

**Pull request merged**
