### PR TITLE
Standardizes / nerfs material sheets to 10u, no more lead in steel sheets

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Standardizes all material sheets that were 22u (+ byproducts) down to 10u, byproducts included.
Removes lead from steel sheets.
Grinding plastic now gives you oil instead of carbon.
Also, grinding uranium gives you radium now I guess.

This is untested BUT it should probably be fine since these are just numbers changes.

## Why / Balance
22u was WAY too fucking much for a single material sheet, that's half of an entire beaker for something that comes in 30 per stack. 10u is also easier to work with since it's... well, 10. It's just a good "baseline" for a raw material.

I didn't think I could really fit lead in trace amounts without doing some weird shit like making carbon 0.5u so I just opted to remove it for now. That one killchem is probably going to be unobtainable in the meantime, but it wouldn't be out of the question to add it to something else (like the lead-based maint items from /tg/.)

Plastic now gives you oil and phosphorous because carbon was dumb.
Radium is in Uranium because radium needed a source, simple-as.

**Changelog**
:cl:
- tweak: Standardized all material sheets to 10u of total reagents when grinded. Alloys are still worth the sum of their parts.
- tweak: You can now grind plastic into oil and phosphorous.
- tweak: Steel sheets no longer contain trace amounts of lead in them.

### CODE REVIEW

**Comment by Aisu9** [comment]
this also mean you are removing the only way to make battery juice

**Comment by Holinka4ever** [comment]
And also removing option to craft blindless toxin, mute toxin, and emp reagent.
Just why, if you gonna rid off option to make these, why not to change their recipe?
Or maybe, delete these reagents, bad option though.

**Comment by Flareguy** [comment]
> this also mean you are removing the only way to make battery juice

I am aware, but I just wanted to get lead off of steel (as I explained in the PR.) Someone can add it to something else; it's a niche reagent and every reagent in the game probably needs rebalancing anyways with the upcoming chem rework (which this is for.)

**Comment by Holinka4ever** [comment]
Is there any explanation about what gonna happen with 4 reagents that requing uranium? Though, maybe sound weird, but i think it was intented.
Because 3 of their reagents the most exsclusive reagents. Changing theor craft from uranium to radium, will brought a bit of but disaster to balance.

**Comment by EmoGarbage404** [comment]
kid named the required rebalancing that follows most major reworks

**Comment by Flareguy** [comment]
> Is there any explanation about what gonna happen with 4 reagents that requing uranium? Though, maybe sound weird, but i think it was intented. Because 3 of their reagents the most exsclusive reagents. Changing theor craft from uranium to radium, will brought a bit of but disaster to balance.

Uranium isn't gone. The recipe has just been changed to 8u uranium 2u radium.

**Comment by Holinka4ever** [comment]
> > Is there any explanation about what gonna happen with 4 reagents that requing uranium? Though, maybe sound weird, but i think it was intented. Because 3 of their reagents the most exsclusive reagents. Changing theor craft from uranium to radium, will brought a bit of but disaster to balance.
> 
> Uranium isn't gone. The recipe has just been changed to 8u uranium 2u radium.


Sorry then mate, i am were just blind in december morning👍
Chem rework wohoo

**Comment by thebadman4662** [comment]
Steel is the only source of lead in the game, if you remove lead from steel you remove Licoxide from game as well which was the whole point of grinding steel into beaker.

**Comment by LankLTE** [comment]
Lead being gone is a shame- as I've discussed earlier the intention was to make it hard to create in large amounts but not hard to actually get (steel really isn't difficult to get your hands on) and I feel it's currently pretty well balanced. That said it's probably fine if it's added to something else that accomplishes the same effect, I just really don't know what that could be (and I don't think lead-based maint items is going to accomplish that).

**Comment by Aisu9** [comment]
> Lead being gone is a shame- as I've discussed earlier the intention was to make it hard to create in large amounts but not hard to actually get (steel really isn't difficult to get your hands on) and I feel it's currently pretty well balanced. That said it's probably fine if it's added to something else that accomplishes the same effect, I just really don't know what that could be (and I don't think lead-based maint items is going to accomplish that).

what about making smelting "steel" produce a small amount of lead in the ore processing unit and add lead sheets as a result, mixing recipe can always be tweaked in the future

**Pull request merged**
