### PR TITLE
Add external programs to rules

### PR DESCRIPTION
**Pull request by wrexbe**
Add external programs to the rules list, mainly because people have been caught using auto-clickers. I see a gap in the rules with "external programs" when being used to "powergame, slow down, or crash the server", that this can cover.

### CODE REVIEW

**Comment by moonheart08** [comment]
Why?

**Comment by Pangogie** [comment]
> Why?

Autoclickers presumably.

**Comment by moonheart08** [comment]
Please provide a description with all PRs, even if you think the reasoning behind the change is obvious.

**Comment by wrexbe** [comment]
I have updated the description

**Review by DogZeroX — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
