### PR TITLE
Add trench coats

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

uhhh.... trench coats. Sprite taken from paradise station.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes

**Changelog**

:cl: Ubaser
- add: Trench coats can be located in the WinterDrobe.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Wonder if this'll be used to celebrate Paradise being on Open Dream

**Comment by IProduceWidgets** [comment]
If it's not too much to ask, can we get one in Grey, black, and boat captain yellow?

**Comment by UbaserB** [comment]
fix'd

**Comment by Kadeo64** [comment]
trench ops

**Pull request merged**
