### PR TITLE
minor changes to pai

### PR DESCRIPTION
**Pull request by icekot8**
## About the PR

this PR suggests making a neutral color for all off pai. Also, the pai of a syndicate agent is now harder to distinguish from a normal pai.
## Why / Balance

The sPAI used to be a really useless purchase, it was a simple red pai with a syndicate link that any security metagamer could recognize. I believe this is wrong... sPAI is situational as it is because of the human factor. So, I propose to make for **all NT's** pai one gray off interface as well. 
Now the sPAI **at the time** of the search is look like the most normal blue pai. Only when it's on, it's red. This makes stealth play on the agent a bit nicer and adds an advantage when socializing with the ghost role.
uplink ops still has the old, eye-catching version of pai, with the **red** interface. I think it's fair for them to keep their interface. After all, I don't want to get to the point where operatives can't tell the difference between their pai and NT's pai, lol.
If this PR is merged, the demand for PAI ghost roles will increase. I think this is the right thing to do, we need to keep socialization going among players.  Also, after the merge, I plan to develop various pai interfaces to give them a special diversity

Might want to make the search menu in pai gray too 🤔 ...
## Media

изображение

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: PAI has lost its blue interface, which Syndicate engineers cleverly used to make their agents' PAI more stealthy!

### CODE REVIEW

**Comment by deltanedas** [comment]
syndie pai is intentionally a meme item, its in the useless category for a reason

this can still trivially be found out by reading "syndicate" in the name

**Comment by icekot8** [comment]
> syndie pai is intentionally a meme item, its in the useless category for a reason
> 
> this can still trivially be found out by reading "syndicate" in the name

maybe it would be fair to make his name indistinguishable from the regular name, but raise the price? :thinking:

**Comment by icekot8** [comment]
because the PR seems incomplete to me.

**Comment by icekot8** [comment]
I don't want to do this.

**Pull request closed without merging**
