### PR TITLE
Ports-The-Supermatter

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

Added supermatter.
Whenever something damages it it shoots lightning bolts.
Also radiates stuff based on whatever gas it's inhaling.

Also new traitor task - steal a supermatter sliver. Will greatly damage the SM, make an announcement that someone tampered with the crystal and something something.

There's no cascade resonance for now because no hypernob & antinob / destabilizing creestal.

Also when singuloth eats the SM it instantly becomes level 6 because uhhh idk why not. 🤷

## Why / Balance

Screenshot_1

## Technical details

I copied most of the stuff from /tg codebase. A lot of shitshow in a single component. Please don't look at it thank you :3

## Media

none for now because it's a draft

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## TODO
- [ ] Demalination types
- [ ] Sum more announcements tweaks

**Changelog**

🆑
- add: Added supermatter crystal.
- add: Traitors now have a new objective regarding the supermatter crystal.
- tweak: Singularity when eating the supermatter crystal now instantly becomes level 6.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
If you ported this from tg that means the code is GPL and as such cannot be used here.

**Comment by whateverusername0** [comment]
shit

**Comment by deltanedas** [comment]
youd have to redo it regardless even in its current state theres like 20 reviews of stuff to change :trollface:

**Comment by metalgearsloth** [comment]
Just re-open it whenever it's ready for review and not in violation of license.

**Pull request closed without merging**
