### PR TITLE
Major-ish™ armor rebalance, adds basic security armor and removes Kevlar armor

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
This was originally just going to be a simple in-and-out sprite replacement to update the sec backpack and armor to /tg/, but then I realized that the basic sec armor doesn't exist at all and that bulletproof armor is statistically identical. THEN I realized how overpowered helmets were in testing, and now here we are.

This PR does a good few things. To get the most important out of the way: **this PR absolutely GUTS helmets.**
Before, they would often be stacked on top of already really strong armor and make people wearing it insanely tanky. Some hardsuit helmets even straight up _copied their resistances onto the helmet,_ making them ABSURDLY tanky.
Most helmets have been reduced to 10% or less damage resistance now, usually allowing the user to survive one or two more hits from a weapon.
Hardsuit helmet resistances, on the other hand, have been _completely removed,_ aside from combat hardsuits getting the equivilent of what is now a regular security helmet.
Most hardsuits themselves have also been rebalanced slightly. The engi and atmos suits are now slightly more properly tailored to their roles, and most random rad resistances have been removed. All hardsuits have also received minor caustic resistance.
Additionally, winter coats have been moved down to 0.90 heat resistance, because 0.75 heat resistance felt a little excessive.

Second-most-important, and the original purpose of this PR, Security has recieved new all-rounder armor that replaces their boring old Kevlar vests. It's better at resisting melee then before, but nowhere near as good as Kevlar at resisting bullets.
All sec clothing based on Kevlar has also been retrofitted to values similar to the new armor. Hopefully, as a whole, security should no longer be gigantic bullet sponges.

Bulletproof armor is no longer in lockers as it is extremely strong. Mappers should probably map it into the armory if it's not there already.
Also removes Kevlar because bulletproof armor already exists, and its purpose is much more clear. It also looked really weird, and I can't really see any outfit using it well.

Security Cadets also now spawn with armor for reasons that should be obvious, and the bartender now spawns with the regular-old vest as it looks better (and they really didn't need real armor.)

**Media**
Content Client_X96OPGc3Gu

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: All of Security now gets much more well-rounded armor that gives moderate protection against most kinds of damage.
- tweak: Heavily nerfed helmet armor. Expect players in hardsuits and security members to be much less spongey.
- tweak: Slightly rebalanced all hardsuits to have resistances that make more sense.
- tweak: Winter coats no longer as resistant to heat as they once were.
- tweak: The security backpack no longer covers a large portion of the front sprite, allowing you to properly see what kind of armor you are wearing.
- tweak: Bartenders now start with regular, unarmored vests.
- Remove: Removed the kevlar vest for the crime of being ugly. The bulletproof vest is statistically identical.
- remove: Security Officers no longer receive bulletproof armor in their lockers. You can find them in the armory instead.

### CODE REVIEW

**Comment by LankLTE** [comment]
You may want to make the changelog shorter. It’s pretty absurdly long as-is. Also, if you intend to make security less bulletproof you may want to also change the HoS’s and Detective’s coat, both of which have the same bullet resistance as Kevlar currently does iirc.

**Comment by LordEclipse** [comment]
Bulletproof vest and Kevlar vest are mostly for purposes of drip, even if they have similar stats.

**Comment by Flareguy** [comment]
> Bulletproof vest and Kevlar vest are mostly for purposes of drip, even if they have similar stats.

One problem: Kevlar looks awful. In fact, this PR was originally intended to replace the sprite of it, hence the branch name.

**Comment by Flareguy** [comment]
After realizing it was fucking up the hits to kill substansially, I am converting this into a total helmet (and maybe armor) rebalance. This will probably take a while.

**Pull request merged**
