### PR TITLE
Salamander whitelist minimum to 10

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
The quality of salamander has considerably dropped since the whitelist minimum and I think me and a lot of salamander players would like to die on this hill

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I'd rather have a slightly sub-optimal mrp server that has players regularly than the gold standards that's so empty 50% of the time you can't even run a normal shift.

**Comment by mirrorcult** [comment]
i think itll probably be ok pop wise with 10? not opposed to this after seeing admin side

**Comment by EmoGarbage404** [comment]
> i think itll probably be ok pop wise with 10? not opposed to this after seeing admin side

10 pop is still barely functioning for a server, even on a lowpop map

**Comment by mirrorcult** [comment]
sure but the point is to seed pop with un whitelisted players not make all of pop be unwhitelisted

**Comment by moonheart08** [comment]
agreeing with this, salamander's been a bit more of a pain to mod.

**Pull request merged**
