### PR TITLE
Remove Walking out of Containers while You can't Walk

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Prevents players from exiting containers while asleep or stunned
Ie: you can put someone to sleep someone then dump them in a bin without them instantly getting out now
## Why / Balance

Its quite annoying stunning someone or putting them to sleep and being unable to seal them in a locker or disposal bin because they can hold one button to remove themself from the container instantly.
## Technical details

adds a check to see if the player is standing or cuffed when attempting to move to open a locker
## Media

I'm uh... trying to walk while asleep, its kinda hard to show without me setting up a key input overlay or something(I'm lazy)

https://github.com/user-attachments/assets/b501e62d-bfb5-44fa-8c25-8efe67ce018b

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: You can no longer get out of a disposal chute or container while knocked over by trying to walk

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Can handcuffs prevent this too.
It's a chore to kidnap someone, stuff them into a disposal unit and have them just "walk" out while being handcuffed, hog tied, arm bared, triangle choked.... etc

**Comment by Cojoke-dot** [comment]
> Can handcuffs prevent this too. It's a chore to kidnap someone, stuff them into a disposal unit and have them just "walk" out while being handcuffed, hog tied, arm bared, triangle choked.... etc

Sure I guess... I can add it in this pr

**Comment by Brandon-Huu** [comment]
> > Can handcuffs prevent this too. It's a chore to kidnap someone, stuff them into a disposal unit and have them just "walk" out while being handcuffed, hog tied, arm bared, triangle choked.... etc
> 
> Sure I guess... I can add it in this pr

I can do it if you don't want to.

**Comment by Cojoke-dot** [comment]
> > > Can handcuffs prevent this too. It's a chore to kidnap someone, stuff them into a disposal unit and have them just "walk" out while being handcuffed, hog tied, arm bared, triangle choked.... etc
> > 
> > 
> > Sure I guess... I can add it in this pr
> 
> I can do it if you don't want to.

nah, I'm almost done already, its just going to make the pr take longer for maintainers to vote on I think 🙃

**Comment by Plykiya** [comment]
what if this was finally a use case for bola's very specific ensnareable component....

also so true, I hate stun cuffing someone and shoving them into a trash can only for them to crawl out

**Review by keronshb — CHANGES_REQUESTED** [review]
Not for this at all for multiple reasons.

1) Causes a very easy way to Gay Baby Jail people. Aka locking someone in a 1x1 space with them unable to do anything.
2) You're supposed to lock or weld the container they're in. If there's an instance where that's not possible (Disposals) it's up to you to stun them until you can flush them down disposals.
3) Being able to enter disposals while cuffed is by design

**Comment by Cojoke-dot** [comment]
> Not for this at all for multiple reasons.
> 
> 1. Causes a very easy way to Gay Baby Jail people. Aka locking someone in a 1x1 space with them unable to do anything.
> 2. You're supposed to lock or weld the container they're in. If there's an instance where that's not possible (Disposals) it's up to you to stun them until you can flush them down disposals.

Are you asking me to remove the cuff part?

 3. Being able to enter disposals while cuffed is by design
 
 you can't enter disposals if you are wearing cuffs right now anyway, do you mean exit?

**Comment by keronshb** [comment]
> > Not for this at all for multiple reasons.
> > 
> > 1. Causes a very easy way to Gay Baby Jail people. Aka locking someone in a 1x1 space with them unable to do anything.
> > 2. You're supposed to lock or weld the container they're in. If there's an instance where that's not possible (Disposals) it's up to you to stun them until you can flush them down disposals.
> 
> Are you asking me to remove the cuff part?
Yes please.

Also checking for being horizontal isn't the best way to check if someone is stunned.

> 
> > 3. Being able to enter disposals while cuffed is by design
> 
> you can't enter disposals if you are wearing cuffs right now anyway, do you mean exit?

ugh who changed this. I mean both, so thank you for bringing this to my attention.

**Comment by EmoGarbage404** [comment]
>Also checking for being horizontal isn't the best way to check if someone is stunned.

to clarify, use action blocker methods. probably something like "can interact"

**Comment by Cojoke-dot** [comment]
> > Also checking for being horizontal isn't the best way to check if someone is stunned.
> 
> to clarify, use action blocker methods. probably something like "can interact"

alright, thanks, I'll do that

**Comment by keronshb** [comment]
> > Also checking for being horizontal isn't the best way to check if someone is stunned.
> 
> to clarify, use action blocker methods. probably something like "can interact"



> > > Also checking for being horizontal isn't the best way to check if someone is stunned.
> > 
> > 
> > to clarify, use action blocker methods. probably something like "can interact"
> 
> alright, thanks, I'll do that

You should check if they can move instead of can interact.

If you check by can interact then cuffs won't be able to open these

**Pull request merged**
