### PR TITLE
Buff EMP implant and grenade range

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

Buffed the EMP implant range from 1.75 tiles to 2.75 tiles
Buffed EMP grenade range from 4 tiles to 5.5 tiles

## Why / Balance

I often see people missing their EMP implant triggers at point-blank range because the trigger range is pathetically low. The usage range shown in this screenshot failed to depower the baton and the nukie died for it, at no fault of the nukie in question. 

The range is honestly so bad, that for a few months, I was debugging the EMP effect code to see if it was just randomly failing to get the correct entities. It wasn't. The range isn't this low as a result of buffs or nerfs either, it hasn't been touched a single time since first being implemented a year ago.

image

## Technical details

it's just yml

## Media

**Before:**

https://github.com/user-attachments/assets/5ebb434a-1802-456b-bdce-697c568dd4da

**After:**

https://github.com/user-attachments/assets/bcb8e7c8-f08c-4507-9029-e4c7bd8b125c

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Buffed the range of EMP implants from a radius of 1.75 tiles to 2.75 tiles.
- tweak: Buffed the range of EMP grenades from a radius of 4 tiles to 5.5 tiles.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
HOLY SHIT MA!!! LOOK!!! I'M IN THE NEWS!!!

**Comment by sk3iron** [comment]
Watched the example happen live and am in support of this change.

**Comment by Dysh3s** [comment]
Small implant range are offset by low implant cooldown. If you wish to increase its range - compensate with increased cooldown. Also might want to do something about nukies chain EMP'ing crew. Maybe a separate PR though. IMO implant is already strong af and can be used to kill both airlocks and crew's energy reserves without a hassle.

**Comment by Ilya246** [comment]
> Small implant range are offset by low implant cooldown. If you wish to increase its range - compensate with increased cooldown. Also might want to do something about nukies chain EMP'ing crew. Maybe a separate PR though. IMO implant is already strong af and can be used to kill both airlocks and crew's energy reserves without a hassle.

i don't think the cooldown particularly matters
could you provide a reasonable example of a situation in which you would want to spam-use EMP implant?

**Comment by Dysh3s** [comment]
Several crew members trying to go against you, that were smart enough not to get totally depleted in one swoosh, but still can't use disabling against a 3x3 10 sec cooldown EMP. Also consider several EMP users at once. Area of denial and it's uptime would be insane.

**Comment by Ilya246** [comment]
> Several crew members trying to go against you, that were smart enough not to get totally depleted in one swoosh, but still can't use disabling against a 3x3 10 sec cooldown EMP. Also consider several EMP users at once. Area of denial and it's uptime would be insane.

i think it's fair that you lose all your battery-powered stuff if you get that close to an EMP implant user in the first place, we shouldn't make stunmeta even stronger
so yes, i would still advocate for only a low cooldown because i think you should have to counter it by simply not getting close

**Comment by Dysh3s** [comment]
There is no counterplay against getting EMPd, there is counterplay against stuns. Not getting close is not exactly an option, since usually speed is on nukies side. And range doesn't really matter for traitors. So basically, for what, six TC we have unlimited use, low TC and high range EMP plus even bigger range grenades.

**Comment by Ilya246** [comment]
> There is no counterplay against getting EMPd, there is counterplay against stuns. Not getting close is not exactly an option, since usually speed is on nukies side. And range doesn't really matter for traitors. So basically, for what, six TC we have unlimited use, low TC and high range EMP plus even bigger range grenades.

i believe not getting close *is* an option since you have the advantage of being able to prepare fortifications/glass walls/etc, while the nukies don't, so you can just sit behind a barricade and blast nukies with lasers, or kite nukies to behind doors they have no access to, or whatever other traps
stun batons shouldn't ever be a viable weapon against nukies that have prepared for their use, and the EMP implant doesn't really counter anything that isn't stun batons; if you're a ranged-weapon-user as crew and a nukie gets within EMP implant range of you, you're likely just going to die without doing much anyway: it's hard to aim at melee distances if the target is actively dodging, plus reflect can kill you because every reflected bullet will hit

**Pull request merged**
