### PR TITLE
update rules for borgs

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

rules speedrun

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
image
I think this needs an example

**Review by crazybrain23 — APPROVED** [review]
lgtm

**Comment by deltanedas** [comment]
doesnt address law 0 when being put in a new borg which is still a grey area

**Comment by crazybrain23** [comment]
> doesnt address law 0 when being put in a new borg which is still a grey area

What needs addressing about law 0?

**Comment by deltanedas** [comment]
eg. emagger says do not tell anyone about law 0, once mmi/pb is removed does it no longer has to follow it, thus giving up the emagger and basically making law 0 useless

**Comment by deltanedas** [comment]
if a borg has 1 second ping + reaction speed its impossible to react to the doafter, would be better with access locked maint panel

**Comment by mirrorcult** [comment]
dawg if someone has 1 second of ping they're going to be fucked in a lot more than this

**Comment by LankLTE** [comment]
> eg. emagger says do not tell anyone about law 0, once mmi/pb is removed does it no longer has to follow it, thus giving up the emagger and basically making law 0 useless

I don’t see why this is a problem. I think it’s a lot more interesting to have emagging a Borg be risky- they’ll out you if caught. Especially given how strong emagging Borgs is

**Comment by Ilya246** [comment]
couldn't you just order an emagged borg brain to kill itself if it's about to be caught

**Comment by LankLTE** [comment]
> couldn't you just order an emagged borg brain to kill itself via /suicide if it's about to be caught

I one time had someone order me to “wipe my memory when my chassis was about to be destroyed”. No clue if that is allowed but I figured it’d be more fun to follow it, so I did. I imagine other things of that vein are possible.

**Comment by JoeHammad1844** [comment]
> > eg. emagger says do not tell anyone about law 0, once mmi/pb is removed does it no longer has to follow it, thus giving up the emagger and basically making law 0 useless
> 
> I don’t see why this is a problem. I think it’s a lot more interesting to have emagging a Borg be risky- they’ll out you if caught. Especially given how strong emagging Borgs is

its just a lame way of getting caught, it would be like if your syndie reinforcement ratted you out

**Comment by CrigCrag** [comment]
emagging borgs is free forever once you buy the initial emag, and some poor scientist has to pay like 70 sheets of steel for every new one they make.

**Pull request merged**
