### PR TITLE
Carp Plush and Rehydratables can now be put into mop bucket.

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
In addition to the shark plush, the space carp plush and the rehydratable syndicate version can now be put in mop buckets.
(Other rehydratables like monkey cubes can also be dropped in but aren't actually visible since they'll mostly just get hydrated right away)

## Why / Balance
Mostly because it's neat but there could also be some opportunities for syndies to slip a dehydrated carp into a janitors bucket while it has no water so the carp will only pop out once the jani goes to refill the bucket.

## Technical details
Adds a new ReactiveContainerComponent and ReactiveContainerSystem for containers that are also filled with a solution that reactive things should react with when inserted.
Also adds a PlushieCarp tag so the mop bucket can whitelist / display it.
Furthermore the mop bucket shark plush sprites have been moved into janitorial.rsi so that all mop bucket sprites can be in the same place.

## Media
[SS14 carp.webm](https://github.com/space-wizards/space-station-14/assets/60073468/c11b0bce-f1c7-4cd1-960a-f75f7a3e9c07)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- add: Carp plushies can now be placed in mop buckets, along with other rehydratable things like monkey cubes.

### CODE REVIEW

**Comment by hord-brayden** [comment]
Carp rush 2.0

**Comment by deltanedas** [comment]
what is carp rush

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Needs predicting.

**Comment by Psychpsyo** [comment]
> Needs predicting.

Done.

**Review by SlamBamActionman — CHANGES_REQUESTED** [review]
Hello! I've tested out this PR now by merging in the latest stable branch and I have the following comments:

1. It appears the reaction message is spammed 12 or so times whenever it triggers. This is likely due to the prediction. I'm not entirely sure how one solves this but I've seen it happen before, so if you ask in #how-do-i-code on Discord I'm sure someone has the answer.

2. Placing a carp into an empty bucket and then pouring in water does not trigger the reaction; instead it seems to attempt to trigger when removing the carp, but it doesn't. Placing a carp in a filled bucket does work though. 

Let me know once you've investigated these things, I think the PR looks sharp 😄

**Comment by SlamBamActionman** [comment]
Closed due to no response from PR author; has been continued in #33079.

**Pull request closed without merging**
