### PR TITLE
pAI map button sprite change

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

It was really rough, the outlines were too thick and there were transparent pixels. Instead of cleaning the sprite, I decided to replace it with an activate station map sprite since i felt it fit a lot.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

### CODE REVIEW

**Comment by potato1234x** [comment]
just use the station map sprite

**Comment by UbaserB** [comment]
> just use the station map sprite

fair, ill change it soon

**Comment by Dutch-VanDerLinde** [comment]
this messed up the PDA home button sprite too

**Comment by UbaserB** [comment]
> this messed up the PDA home button sprite too

can you explain?

**Comment by Dutch-VanDerLinde** [comment]
> > this messed up the PDA home button sprite too
> 
> can you explain?

image

**Comment by Brandon-Huu** [comment]
Next time use grep to find all the places the image is used

**Pull request merged**
