### PR TITLE
Context Menu appearance change

### PR DESCRIPTION
**Pull request by daniel-cr**
Makes the context menu scrollable and adds stacking of similar items.
Entities are grouped based on their current appearance. For example a weapon without a magazine and a sprite layer showing that state is different from the same weapon with a magazine.

Hovering with the mouse on a menu item makes the outline appear.

pOqHshUmm0

### CODE REVIEW

**Comment by AJCM-git** [comment]
Can you
1- Right clicking the stack of items should open the menu of the first item
2- Make the scrollbar less transparent
And if its possible
3- Make it so lines match up with the side menu when scrolling

**Comment by daniel-cr** [comment]
I don't think that enabling the verb menu for the first element in the stack would be clear from a player perspective. It already lets you pick one element from the stack with left click. Maybe it would be useful for editing multiple similar entities at the same time in the future.  About the color/opacity I don't want to occlude the window more, and the alignment , I may change it if there is an outrage.

**Comment by metalgearsloth** [comment]
> 
> 
> I don't think that enabling the verb menu for the first element in the stack would be clear from a player perspective. 

I agree

**Comment by AJCM-git** [comment]
Fair enough, i wanted the bar to be more occluded/of another color because sometimes it camouflages with the tiles if you have lights turned off, this could be an issue if we let observers toggle lights in the future (right now everyone can but thats for testing purposes).

**Comment by AJCM-git** [comment]
Fair enough. I wanted the bar to be more occluded/of another color because sometimes it camouflages with the tiles if you have lights turned off, this could be an issue if we let observers toggle lights in the future (right now everyone can but thats for testing purposes).

**Review by metalgearsloth — APPROVED** [review]

**Comment by metalgearsloth** [comment]
Would be useful if anything that moved out of the initial context range to be removed from the menu probably, or maybe if it broke if you moved and the initial spot wasn't in range?

Currently I can right-click someone and just hover it to get an outline to see them in the dark which was the same problem I had with the other examine PR. 

Rest seems good.

**Comment by metalgearsloth** [comment]
@daniel-cr I'm happy if you want to out of scope it if you want to get it merged because it's really nice.

**Comment by daniel-cr** [comment]
Deleted entities and entities that move out of initial click location should be removed from the menu. 
There are two modes that can be switched with contextmenug 0 or contextmenug 1. The default mod groups by prototype.id and then groups by sprite states, the other one groups by prototype.id and sprite states at the same time.

**Pull request closed without merging**
