### PR TITLE
New lobby art: TerminalStation

### PR DESCRIPTION
**Pull request by Terraspark4941**
## About the PR

Adds a new lobby art by aserovich:
new2

## Why / Balance

Atleast 3 people requested that their art should be added as a lobby art; I merely motivated them to make the changes needed from the original (https://discord.com/channels/310555209753690112/1194352973640388719/1217086402542702642)

## Media

image
(If the image looks kinda pixelated, that's thanks to discord + robust + webp compression)

Oh also, proof that I have permission to PR this:
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Aserovich
- add: New lobby art!

### CODE REVIEW

**Comment by Terraspark4941** [comment]
For some inexplicable reason my client crashes on trying to enter lobby with this build; maybe something wrong with the attributions or somn???

**Review by VasilisThePikachu — APPROVED** [review]
Love the tailbag on the lizard!

**Comment by VasilisThePikachu** [comment]
Before merging im gonna check why it crashes

**Comment by nikthechampiongr** [comment]
The crashes do not seem related to this pr, git bisect leads to #25452.

**Comment by VasilisThePikachu** [comment]
Crash only happens on debug mode. Release seems fine. Not sure when #26602 will be merged but it's not a requirement for this.

**Pull request merged**
