### PR TITLE
Change range of 10-sided dice

### LINKED ISSUE #22826: ten sided dice go from 1 to 10 and not 0 to 9 like they are supposed to.
its not a big issue, it can wait

### PR DESCRIPTION
**Pull request by Tayrtahn**
## About the PR

10-sided dice (d10s) now roll values from 0 to 9, rather than 1 to 10.
Fixes #22826

## Why / Balance

This reflects real-world d10s, which typically have values from 0 to 9, to make them easier to use for rolling percentiles. This means it can be used for the ones place in combination with the existing "percentile die" (which rolls 00, 10, 20, etc). [Wikipedia](https://en.wikipedia.org/wiki/Pentagonal_trapezohedron#:~:text=Ten%2Dsided%20dice%20are%20commonly,be%20combined%20to%20produce%2070.) has more information about this.

## Technical details

Gave the d10 an offset of 1 in its Dice component, just like how the percentile die works.
Added a sprite for the 0 state.
Modified SharedDiceSystem.OnHandleState to better deal with invalid states.

## Media

Screenshot 2023-12-21 at 4 07 37 PM

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Emisse** [comment]
test fail its tryna do state d10_10 from current value i think

**Comment by Tayrtahn** [comment]
Yeah, I'm thinking it's because there are some dice prespawned on some of the maps, and the game is trying to restore their state when the map loads? Should I edit the maps to change the values, or maybe add a check to the dice system to reset dice that are out of the valid range on init?

**Comment by Tayrtahn** [comment]
Oh wait, I get it. Nothing to do with map data, and everything to do with the fact that I was still setting the default value to 10 in the YAML. Brilliant.

**Comment by Tayrtahn** [comment]
Yep, there we go. Huzzah!

**Pull request merged**
