### PR TITLE
Shoe harm

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR
Adds meleeWeapon component to the base shoes clothing with 3 blunt (not much, but that`s a shoe)

## Why / Balance
Funny feature.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Tunguso4ka
- add: Now you can hit people with your shoes.

### CODE REVIEW

**Comment by lzk228** [comment]
i remember similar pr and it was closed iirc

**Comment by Tunguso4ka** [comment]
> i remember similar pr and it was closed afaik

wish me luck then?

**Comment by Aisu9** [comment]
come on fist inflict 5 damage, it just some silly fun

**Comment by ShadowCommander** [comment]
Is this supposed to make shoes do less damage than punching? Unless there's a really good reason (like plushies doing no damage), then I don't think that the damage on shoes specifically should be lowered from standard punch damage. It'll just end up confusing players if random items have slightly higher or lower damage.

**Comment by ShadowCommander** [comment]
After more discussion with the other maintainers, we decided not to include items that don't increase damage unless they have some other effect like stamina damage. This makes it easier for players to recognize which items are useful weapons.

**Pull request closed without merging**
