### PR TITLE
Remove Arachnid's extra hands

### PR DESCRIPTION
**Pull request by Equivocateur**
## About the PR

Remove secondary hands from arachnids, as they are stupidly oppressive and absurd with semi-auto/slow weapons in combat and easy to use&abuse.

https://github.com/space-wizards/space-station-14/assets/109166122/c975b701-6253-4320-b42c-2ff0b9417cbd

This is by no means a "MERGE IT NOW" pr, as actual testing in-game is required. The potential to kill literally anything with a hristov/python/other slow-firing and/or semiauto weaponry is there.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Arachnids are now at equal playing field with other species and lost their extra hands.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
dude it's been like not even a day

**Comment by Equivocateur** [comment]
> dude it's been like not even a day

its a draft

**Comment by HoidC** [comment]
> > dude it's been like not even a day
> 
> its a draft

have you considered making these super le op semi auto god demon mega weapons 

require wielding? the thing implemented to stop this from happening?

**Comment by deltanedas** [comment]
if dual wielding shotguns is good then why should quad wielding not also be good

**Comment by retequizzle** [comment]
not really seeing an issue here considering not everyone is walking around with hristovs

only real way this becomes a viable scenario is if someone's growing the shit out of some gatfruit, otherwise your average player will probably only have access to 2-3 weapons to do this with, which people already did with 2 hands to begin with

**Comment by HoidC** [comment]
oh yeah where are you even getting four hristovs from lmao they're 12 tc, you can only buy one and with help you can only buy three (and the ammo is limited, and they fire slowly)

**Comment by retequizzle** [comment]
i will admit that there is some viability of this being an option if you use something like the viper or cobra, but with how often they're overlooked to begin with i honestly don't even see that as an issue considering you're limited on extra ammo in those cases as well

**Comment by metalgearsloth** [comment]
Fix UseDelay first.

**Pull request closed without merging**
