### PR TITLE
Normal orders

### PR DESCRIPTION
**Pull request by KeplyDog**
## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Golinth** [comment]
wrong branch?

**Comment by deltanedas** [comment]
wrong repo even

**Comment by Golinth** [comment]
> wrong repo even

That‘s the word, I couldn’t think of it :P

**Comment by KeplyDog** [comment]
Sorry T-T

**Pull request closed without merging**
