### PR TITLE
Gauze recipe in medfab

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Gauze can now be crafted in medical fabricators for 2 cloth.

## Why / Balance
To speed up the production of gauze in the medical department, no more cutting up clothes and crafting bandages by hand.

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: After realizing their employees have been forced to make medical supplies by hand, Centcomm has added a gauze option to their medical fabricators.

### CODE REVIEW

**Comment by Aisu9** [comment]
using the lathe to craft them should at least be more efficient than making them by hand

**Comment by asperger-sind** [comment]
>...wait for someone to say something here.

It should 100% be cheaper to fabricate gauze in the medfab rather than to make it by hand, speed alone will not make this sufficient as a better measure to craft gauze.

**Comment by K-Dynamic** [comment]
Actually speed by itself is good. Cheaper recipe would just be a bonus.

(If you locked someone in a room and gave 30 cloth to make 15 gauze, expect them to log off 2 minutes later)

**Comment by Kadeo64** [comment]
gauze is so fucking slow to make I wish it crafted by the stack instead of by the singular unit

**Comment by K-Dynamic** [comment]
Inb4 gauze nerf (5 slash 10 pierce heal now readily available :trollface: )

**Pull request merged**
