### PR TITLE
Vox Can Tail Pull

### PR DESCRIPTION
**Pull request by Admiral-Obvious-001**
## About the PR

Added the puller, no hands component to Vox.

## Why / Balance

Vox kind of needed something, and they have a tail, so why not?

## Technical details

Copied the puller component from Reptilians to Vox

## Media

https://youtu.be/WX1PweejKLY

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Probably nothing?

**Changelog**

:cl:
- tweak: Vox can now pull with both hands occupied.

### CODE REVIEW

**Comment by Admiral-Obvious-001** [comment]
I don't think the test fail is me, and I screwed up the video linking, but copying the URL text should work.

**Comment by slarticodefast** [comment]
Random test fail I assume. I'm re-running them for you.

**Comment by ps3moira** [comment]
Why would vox's be able to pull with a tail that's up in the air? Plus aren't they more bird than lizard

**Comment by Admiral-Obvious-001** [comment]
> Why would vox's be able to pull with a tail that's up in the air? Plus aren't they more bird than lizard

I see tail, I add 2 lines of YML (I've also been bugged to do it for a week and finally got time off).

If people want to change it after the fact once Vox get a proper design, or if maints want to outright reject it, so be it.

**Comment by Nexeron94** [comment]
Would be a small but nice buff for Vox. I can see them being able to utilize their tails just as lizards do.

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and the decision was not to merge this as this is a feature that makes lizards unique as a species. Thank you for your contribution.

**Comment by superjj18** [comment]
> Hey, I brought this up for maintainer discussion and the decision was not to merge this as this is a feature that makes lizards unique as a species. Thank you for your contribution.

The rare 5% of the time where the maintainers are cringe 😔

**Pull request closed without merging**
