### PR TITLE
Adds full-tile tinted windows.

### PR DESCRIPTION
**Pull request by Lamrr**
## About the PR 
Adds full-tile tinted windows, as well as a construction recipe. Useful for when you want an window but not to see through it. Will also be useful for [future mapping projects](https://affectedarc07.github.io/SS13WebMap/TG/KiloStation/). 

Crafting recipe is essentially the same as the reinforced window. Uses wall-like occluding as the bounding box based occluding didn't work too well for connecting windows. Based on /tg/station sprites.

**Screenshots**

Screenshot from 2022-01-23 22-35-34

**Changelog**

:cl:
- add: You can now find full-tile tinted windows at a crafting menu near you. Useful for keeping the greytide out of your private affairs.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Isn't this functionally a wall?

**Comment by Lamrr** [comment]
> Isn't this functionally a wall?

Almost, except it is much easier to break. So you can use it to 'wall-off' areas while still providing an easy escape like a window does. It's also used as a flavour object for places like the interrogation room...

**Comment by Peptide90** [comment]
Not entirely keen on the idea. I'm used to four thin windows and grille for windows which is possible now. Working one way windows would be nice but I'm told it's hard.

**Comment by metalgearsloth** [comment]
> Not entirely keen on the idea. I'm used to four thin windows and grille for windows which is possible now. Working one way windows would be nice but I'm told it's hard.
> 
> But also can't hurt I guess, just see it as a rare thing to be used?

Arbitrary occlusion is hard (which isn't in this PR), and these also aren't 1way. If I had a choice I'd choose this over 4 thindows and a grille as it seems like a waste of entities.

**Comment by Lamrr** [comment]
> Not entirely keen on the idea. I'm used to four thin windows and grille for windows which is possible now. Working one way windows would be nice but I'm told it's hard.
> 
> But also can't hurt I guess, just see it as a rare thing to be used?

They're used on [a few](https://affectedarc07.github.io/SS13WebMap/TG/DeltaStation/) [SS13 maps](https://affectedarc07.github.io/SS13WebMap/TG/MetaStation/), mostly to softly divide private areas such as interrogation rooms and dorms. Personally I prefer full-time to directional windows, less entities as well as metalgearsloth mentioned.

**Comment by Peptide90** [comment]
Fair enough, in that case go for it if they'll get more use over the thindow variant. 

Thindows are better to me for safety since it's 3 entities to break through instead of 1 (plus you can use them to get out the station without venting).

**Comment by mirrorcult** [comment]
occluding thindows are not possible yet

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
