### PR TITLE
biggest gridinv update OF ALL TIME

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
middle click item to save position, quick inserting (hotkeys or clicking item on bag) will place it in the first saved slot it can find
when holding an item saved positions are highlighted yellow (when not blocked by another item), middle click again to remove it

## Why / Balance
its genius

## Technical details
- renamed _rotation to Direction and made it public to avoid having to change between Angle for no reason (still saved as "_rotation" just incase)
- when looking for a space that fits an item it will first check if the item's name has any saved locations (using name not prototype so 1. labelling things lets you have different saved positions VERY IMPORTANT FOR MED 2. you cant meta a stealth item with bag insertion because its prototype is different 3. non prototype entities work) then put it there. if theres multiple locations itll use the first one that isnt blocked by something

## Media
its real

https://github.com/space-wizards/space-station-14/assets/39013340/fc62e511-69d9-44b3-ae41-6b0995d2094a

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl: deltanedas, notquitehadouken
- tweak: You can now middle click items in storage to save their location. Inserting it later will prefer using a saved location. Middle click again while holding to remove saved positions.

### CODE REVIEW

**Comment by deltanedas** [comment]
> wait isn't shift click also examine

i have it bound to middle mouse i forgor :trollface:

what isnt used

**Comment by notquitehadouken** [comment]
> > wait isn't shift click also examine
> 
> i have it bound to middle mouse i forgor :trollface:
> 
> what isnt used

shift right?

**Comment by deltanedas** [comment]
brings up the verb menu

**Comment by deltanedas** [comment]
only ctrl rmb doesnt bring up verb menu i think

**Comment by mirrorcult** [comment]
in every other game with some 'favoriting items' feature ive played its been on alt+click though that seems not that viable here

**Comment by deltanedas** [comment]
i think factorio has shift click which i why i went for it originally
anyway anything not used and that doesnt bring up verb menu is good

**Comment by notquitehadouken** [comment]
> i think factorio has shift click which i why i went for it originally anyway anything not used and that doesnt bring up verb menu is good

use middle click

**Comment by notquitehadouken** [comment]
image
okay i may be figuring out how to display saved positions

**Comment by notquitehadouken** [comment]
i figured it out

**Comment by notquitehadouken** [comment]
image

image

heheheha

**Comment by deltanedas** [comment]
:trollface:

**Comment by notquitehadouken** [comment]
> :trollface:

:trollface:

**Comment by notquitehadouken** [comment]
> :trollface:

is it fine with you if i just pr it and credit you in the pr (and cl)

**Comment by deltanedas** [comment]
you could pr it to this branch if you want :trollface: but either is fine

**Comment by notquitehadouken** [comment]
https://github.com/deltanedas/space-station-14/pull/3

**Comment by notquitehadouken** [comment]
btw you middle click when an item is in a saved position to unsave it

**Comment by mirrorcult** [comment]
middle click is good yeah

**Comment by notquitehadouken** [comment]
i loving solving 1 problem and indirectly solving the rest of them at the same time

**Comment by deltanedas** [comment]
yellow highlight is very simple and easy to understand compared to my impossible overengineered idea of saving the item's last rendered sprite to a texture then drawing that with transparency, which i would probably have never been able to implement :trollface:

**Comment by notquitehadouken** [comment]
> yellow highlight is very simple and easy to understand compared to my impossible overengineered idea of saving the item's last rendered sprite to a texture then drawing that with transparency, which i would probably have never been able to implement :trollface:

i was going to do this but couldn't figure out how :trollface:

**Comment by notquitehadouken** [comment]
fun fact: the highlight is always going to be colorblind accessible because the
h u e
d o e s n ' t
c h a n g e

**Comment by notquitehadouken** [comment]
i see your media and i raise media but different


https://github.com/space-wizards/space-station-14/assets/45953835/1284a5b4-76e1-446a-9b42-6b155e7209f2

**Comment by notquitehadouken** [comment]
image
hoohoo

**Comment by notquitehadouken** [comment]
probably should tell people how to remove saved points in the cl or else everyone will get extremely confused once they add 8000000 save points and have no idea how to fix their bag

**Comment by UbaserB** [comment]
how does it look with other themes?

**Comment by notquitehadouken** [comment]
> how does it look with other themes?

gridinv supports other themes?

**Comment by UbaserB** [comment]
> > how does it look with other themes?
> 
> gridinv supports other themes?

yes, it does.

**Comment by strO0pwafel** [comment]
#25408 

> > how does it look with other themes?
> 
> gridinv supports other themes?

**Comment by notquitehadouken** [comment]
i'll test later

**Comment by notquitehadouken** [comment]
from top to bottom: default, minimalist, slimecore, plasmafire, clockwork, ashen, retro

all

**Comment by notquitehadouken** [comment]
image

b/w because why not

**Comment by notquitehadouken** [comment]
they're removed by middle clicking while an item is IN a saved spot

**Comment by notquitehadouken** [comment]
maybe one day it'll get merged

**Pull request merged**
