### PR TITLE
Added corn in butter

### PR DESCRIPTION
**Pull request by JustArt1m**
## About the PR
Added corn in butter and increased the cooking time of popcorn.

https://github.com/space-wizards/space-station-14/assets/123451459/a6912bd9-9823-4ad5-93ba-44544b124ac8

## Why / Balance
Just a new dish for a greater variety of dishes.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Just_Art
- add: Added corn in butter.
- tweak: Increased popcorn cooking time.

### CODE REVIEW

**Comment by potato1234x** [comment]
what is corn in butter lol

**Comment by deltanedas** [comment]
freedom :us:

**Comment by deltanedas** [comment]
also you should edit the rsi copyright, dont think this is in tg

**Comment by JustArt1m** [comment]
Local tests are ok
image

**Pull request merged**
