### PR TITLE
Silent Station Events

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
Due to abusive metagaming, events that spawn antags and other various threats are now silent, and do not display an announcement or sound alert. I left in the announcement Locs just in case anyone wanted to revert these easily in the future.

Ties into: #8937 
**Screenshots**

**Changelog**

:cl:
- tweak: Certain station events will no longer be announced.

### CODE REVIEW

**Comment by Emisse** [comment]
i think this would benefit the current state of the game greatly

**Comment by Elijahrane** [comment]
> Maybe give it a chance for all events to be silent when random?

This tbh

**Comment by ike709** [comment]
SS13 also has a chance for any event-specific alert to actually be a "false alarm" event, where it's just the alert.

**Comment by EmoGarbage404** [comment]
There already exists a false alarm event in 14 that picks one of the in game events and plays the announcement.

**Review by mirrorcult — CHANGES_REQUESTED** [review]
the `Announce` virtual function just shouldn't get called if the bool is false rather than all of the events checking for `AnnounceEvent`

**Comment by mirrorcult** [comment]
actually, i guess only 2 of them actually check for it cause they have special code. so this is fine?

**Comment by EmoGarbage404** [comment]
> actually, i guess only 2 of them actually check for it cause they have special code. so this is fine?

This links into the issue of station event announcements being unable to specify a color and having inconsistent implementation.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
