### PR TITLE
Fixed the wrapped nutribricks being 20$ instead of 50

### PR DESCRIPTION
**Pull request by Pixeltheaertist**
## About the PR

The nutribricks are actually supposed to be 50 spacebucks, so i simply increased the price of the wrapped nutribrick to match it.
I already double checked and the price of the MRE crate is still fair, costing 1000 to purchase and 960 to sell.
**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- fix: Fixed the price problem of wrapped nutribricks being worth 20$ instead of 50

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Please don't give things negative prices

**Comment by crazybrain23** [comment]
Duplicate of #13587.

**Comment by crazybrain23** [comment]
Since this has been fixed with #13626, this PR can be closed.

**Comment by AJCM-git** [comment]
> Since this has been fixed with #13626, this PR can be closed.

**Pull request closed without merging**
