### PR TITLE
Adds a salvage jobspawn to reach

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

I added a salvage jobslot + spawn to reach, removed one of the cargo jobslots
## Why / Balance

#31711
## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by 0x6273** [comment]
3 people in cargo department seems a bit much for such a small map.

**Comment by UbaserB** [comment]
probably a good idea to remove a cargo slot too

**Comment by Boaz1111** [comment]
yep, one sec

**Comment by Boaz1111** [comment]
> probably a good idea to remove a cargo slot too

done

**Pull request merged**
