### PR TITLE
Radiation blocker values for directional plasma and uranium windows

### LINKED ISSUE #31972: Directional plasma and uranium window missing radiation blocker vlaues
## Description
Update to Core (#31942) left bar patrons and scientists exposed to radiation from singulo and artifact respectively.

This exposed a bug where directional plasma and uranium windows were missing radiation blocker values, compared to their full and diagonal counterparts.

Bug affects both normal and reinforced directional versions.

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR

Adds missing radiation blocker values for directional plasma and uranium windows.

## Why / Balance

Fixes #31972.

The radiation blocker values were determined by material cost; two glass units are required for a full window, one glass for directional. Thus values are halved.

## Technical details

yml changes only
- plasma.yml
- rplasma.yml
- ruranium.yml
- uranium.yml

## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: added missing missing resistance values for directional plasma and uranium windows

### CODE REVIEW

**Comment by lzk228** [comment]
https://github.com/user-attachments/assets/ed011c6c-b1c1-4830-8484-8eed73785ca2

**Comment by lzk228** [comment]
very well emisse, don't care about bugs, just press merg button

**Comment by Emisse** [comment]
id rather have something work and be bugged than something not work and be bugged

**Comment by lzk228** [comment]
fair

**Pull request merged**
