### PR TITLE
Displacement map prototype

### PR DESCRIPTION
**Pull request by PJB3005**
Requires https://github.com/space-wizards/RobustToolbox/pull/5023

This uses the new engine features (above) to add a displacement map shader. This allows deforming a sprite based on another sprite.

Primary use case is automatically adapting human clothing sprites to different species, something we want to make species like Vox a reality.

A basic example of wiring this up with Vox has been added. The system is however incredibly simple and **will** need more work by a content developer to select and toggle displacement maps when appropriate. I am leaving that to somebody else. For example right now the displacement map is applied even if a species already has custom-fit sprites for a piece of clothing, such as the grey jumpsuit for Vox.

Basic Aseprite plugins to help with authoring displacement maps have also been made.

### CODE REVIEW

**Comment by PJB3005** [comment]
Diff RSI workflow is shit, I'm not renaming the Aseprite file names as they show up directly in its UI.

**Comment by Hanzdegloker** [comment]
I mean like, moths have spindly legs and arms already yeah? Will this be used there and or on any existing species? I know the difference in shape is not nearly as extreme as with the Vox but yeah.

eitherway excellent work

**Comment by brainfood1183** [comment]
> I mean like, moths have spindly legs and arms already yeah? Will this be used there and or on any existing species? I know the difference in shape is not nearly as extreme as with the Vox but yeah.
> 
> eitherway excellent work

Certainly could be used, i think its just a case of will someone step up and make that happen essentially once this is merged.

**Comment by K-Dynamic** [comment]
Surely this means we can get digitigrade legs for lizards

**Comment by TheShuEd** [comment]
Where we can get Aseprite plugin?

**Comment by superjj18** [comment]
For #26577 I created alternate sprites for most of the headsets so they would fit on the Rat King's shape similar to how Hammy's cosmetics work via speciesID.  Would this change remove the need for such alternate sprites?

**Pull request merged**
