### PR TITLE
add interaction success/failure events

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
raises an event when you succeed or fail to pet something

## Why / Balance
needed downstream

### CODE REVIEW

**Comment by Kadeo64** [comment]
>raises an event when you succeed or fail to pet something

i'm gonna take a wild guess and say this pr is rmc14 related :trollface:

**Comment by slarticodefast** [comment]
you forgot to import the namespace

**Comment by deltanedas** [comment]
>  i'm gonna take a wild guess and say this pr is rmc14 related :trollface:

for felenid hunters actually

**Comment by slarticodefast** [comment]
Is this still needed downstream for another fork or useful in general?
It seems like the linked PR was declined.

**Comment by ps3moira** [comment]
> Is this still needed downstream for another fork or useful in general? It seems like the linked PR was declined.

Yes

**Comment by slarticodefast** [comment]
Well then :)

**Pull request merged**
