### PR TITLE
Substation visualisation

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

Substations now visualise when it is dis/charging, full or out of power.

## Why / Balance

Fixes https://github.com/space-wizards/space-station-14/issues/28987
Also if my EMP changes go through then power sabotage will become more common, this change will help inform engineers that a substation is disabled by EMP and not receiving power.

## Technical details

Creates a new SubstationVisualizer component for the server and client, copying and pasting snippets from code use for the Apc or Smes.
This is really just a stopgap solution. Ideally there would be some PowerNetBatteryVisualizer (name too long) that could accept various indicators for charge types, but I'm still learning the codebase. To-do in a separate PR, ideally after EMP changes are merged/closed.

## Media

https://youtu.be/ozq1AjEGn-A
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Substations now display their status.

### CODE REVIEW

**Review by PJB3005 — CHANGES_REQUESTED** [review]
This shit is copy pasted from the SMES code

**Comment by WarMechanic** [comment]
ill give generic `PowerNBVisualiser` a fair go when i can
i can probably have it communicate with `Apc` through events

**Comment by TheShuEd** [comment]
are you going to finish this PR?

**Comment by SlamBamActionman** [comment]
Hello! Due to a lack of updates on this PR it will be closed for the time being. Thank you for your contribution!

**Pull request closed without merging**
