### PR TITLE
Made Security & HOS Hardsuits Emit Yellow Light

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Simple change that makes the sec/hos hardsuits emit yellow light instead of red. It made no sense to be red since the sprites are yellow.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed security and HoS hardsuits lights from red to yellow.

### CODE REVIEW

**Comment by AJCM-git** [comment]
tbh the sprite should be changed rather than the light

**Comment by EmoGarbage404** [comment]
I like the yellow light more. Yes, the red is more thematic, but the yellow is better for visability and actualy seeing.

**Comment by Alekshhh** [comment]
I like the sec hardsuit but hos does really need a resprite. good bandaid for now though

**Comment by Emisse** [comment]
pull master so your tests pass

**Comment by Alekshhh** [comment]
give me roughly 11 hours

**Pull request merged**
