### PR TITLE
LOOC will appear on top of your head

### LINKED ISSUE #17687: [Feature request] LOOC should be visible above your head
## Description
New players are usually unaware of the LOOC feature in game, I say it comes down to cause it's not visible easily, unless you look at the chatbox. Which a new player probably left on the transparent modern layout on small size which makes it harder to see.

A good idea is to make something like a blue chatbox or similar clearing stating it's LOOC, something like

"LOOC: (do this and that)"

I may assign this to myself, making this for suggestions mostly and if I don't manage to do it

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Closes #17687

I had this written down for a while but could not figure out how to change the text color so I will just put this up.

## Why / Balance

Players, specifically new ones. Don't know about LOOC. And since it only appears on the chatbox (which by default can be pretty small) and makes no sound or anything similar. Players can miss it. This will make it much easier to notice someone is talking to you via LOOC and get their attention.

This (now) also adds a feature to allow the font in the chat messages to be colored... it's kinda hard coded tho... i will be honest

It also allows for prefixes now.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

## Breaking changes

**Changelog**

:cl: Vasilis
- add: LOOC messages will appear on top of your head to be more noticeable. 
- add: For anyone who does not like LOOC messages appearing above people's heads, just disable it in settings!

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
My dumbass forgot to tittle the pr

**Comment by UbaserB** [comment]
This is a feature we all needed, however currently it looks like an emote. Is there a way to maybe create a blue, semi-transparent chat box above the head?

**Comment by VasilisThePikachu** [comment]
> This is a feature we all needed, however currently it looks like an emote. Is there a way to maybe create a blue, semi-transparent chat box above the head?

I already said in the pr i could not figure out how to change all that. If someone points me in a good direction sure. Otherwise weh

**Comment by daerSeebaer** [comment]
The style for emoteBox is defined here: https://github.com/space-wizards/space-station-14/blob/b360391795d9392d666b6f9868da0701a3918752/Content.Client/Stylesheets/StyleNano.cs#L904

Maybe you can define an additional style for "loocBox" there?

**Comment by VasilisThePikachu** [comment]
But style nano scary (I tried)

**Comment by VasilisThePikachu** [comment]
Now in light blue color!

**Pull request merged**
