### PR TITLE
Put entity resetting behind command flag

### PR DESCRIPTION
**Pull request by metalgearsloth**
Stops people bandaiding problems

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
Is there a reason this is being compiled for release clients? Could just also make it a tools build command instead

**Comment by deltanedas** [comment]
resetallents is useful for future bugs that arent known yet, for curent bugsit shouldnt be used as a cope for not fixing them

**Comment by metalgearsloth** [comment]
> resetallents is useful for future bugs that arent known yet, for curent bugsit shouldnt be used as a cope for not fixing them

resetallents shouldnt be used as a cope for not reporting bugs either but it is frequently.

**Comment by EmoGarbage404** [comment]
epic reset talents

**Comment by deltanedas** [comment]
talent from fish game

**Pull request merged**
