### PR TITLE
Everyone in sec starts with filled combat boots

### PR DESCRIPTION
**Pull request by asperger-sind**
## About the PR

I remember this being a decently liked idea back when I made the original PR and now I feel like adding this

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: BurninDreamer
- tweak: The NTDDB has received 1,349,418 full shipments of combat knifes and boots, expect every officer to have a knife on them from this point and on.
- tweak: Jackboots can store knives now.

### CODE REVIEW

**Comment by Slava0135** [comment]
ah yes more shitsec killing people can't wait

**Comment by asperger-sind** [comment]
> Why would sec need any sort of lethals at the beginning of a round? Maybe you could have filled combat boots in the armory for red alert

It's as lethal as any melee can get, and is useful for peacekeeping other hazards (like morbs) and it makes logical sense for officers to have some last resort weapon on them at all times.

**Comment by Slava0135** [comment]
seglite does 10 brute damage and it should be enough

**Comment by Equivocateur** [comment]
> seclite does 10 brute damage and it should be enough

That did not convince an average security officer to move away from the 8 brute harmbaton and its application on the xenomorph praetorian sprinting towards them

**Comment by lzk228** [comment]
> ah yes more shitsec killing people can't wait

ah yes lrp moment

**Comment by Flareguy** [comment]
I feel like Jackboots should just be able to have fills like combat boots, then put a fill for them like here. Combat boots look strange on some outfits, and it's likely sec won't be an exception.

**Comment by asperger-sind** [comment]
> I feel like Jackboots should just be able to have fills like combat boots, then put a fill for them like here. Combat boots look strange on some outfits, and it's likely sec won't be an exception.

yea im probably gonna do that when i stop being lazy

**Comment by keronshb** [comment]
> I feel like Jackboots should just be able to have fills like combat boots, then put a fill for them like here. Combat boots look strange on some outfits, and it's likely sec won't be an exception.

I second this, allow jackboots to be filled. Would prefer it for the PR.

**Comment by deltanedas** [comment]
even if they dont start with a knife its good to have a slot anyway

**Comment by asperger-sind** [comment]
requests addressed, CL updated

**Pull request merged**
