### PR TITLE
Space Asshole Gear

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
Added Sledgehammer and space asshole coat. (though they don't show up anywhere in game yet)

## Why / Balance
I made the sprites for these a long while ago and now decided to just PR them as is.
Balance-wise nothing actually changed.

## Technical details
None

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
no

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Idk who you are but I appreciate this random pr I just saw now

**Comment by IamVelcroboy** [comment]
Funny antag role, shows up and just starts smashing 😀
Can be subdued by any crew member but their goal is just to smash

**Comment by QuietlyWhisper** [comment]
I have ran 7 space asshole events since February of this year! It's my own little thing I made up based on the concept of the song, and it's origins!

**Comment by IamVelcroboy** [comment]
> I have ran 7 space asshole events since February of this year! It's my own little thing I made up based on the concept of the song, and it's origins, so I really like the fact that these sprites use the design from that game!

Ha, that's hilariously awesome

**Comment by pharmacreep** [comment]
would look really cool with a custom welders mask, sum resembling cburn's masks

**Comment by Psychpsyo** [comment]
> Funny antag role, shows up and just starts smashing 😀

Comes out of nowhere to destroy...

**Comment by notquitehadouken** [comment]
(obligatory guy tries to make ideas for future antag)
give space asshole 50% movement buff, stun/slip immunity, and barotrauma immunity like a fucking cartoon character :trollface: 
they suddenly die after 10 minutes
if they go crit or die, they get their objectives are tallied up and suddenly disappear, making a pop noise and leaving behind a singular armed nuclear option
literally just ignores doafters
Objectives (pick 3):
- Destroy 40 walls
- Destroy 10 doors
- Destroy 5 external airlocks
- Destroy the grav gen
- Destroy the anom gen
- Destroy the salv magnet
- Hit 20 people
- Kill 3 people
- Kill any head
- Gib 1 person
- Steal someone's liver
- Steal 5 id cards
- Steal the comms board
- Throw the nuke disk into space
- Throw cap's id into space

**Comment by Myakot** [comment]
Destroy the grav gen, but it's still immune challenge.

**Pull request merged**
