### PR TITLE
Spears equippable to suit storage

### PR DESCRIPTION
**Pull request by Hanzdegloker**
## About the PR

All spears can now be equipped to the suit slot, as compensation for this boost in convenience I made it slightly more expensive to make spears.

## Why / Balance

I found spears to be cumbersome and hard to work with when every firearm for instance can be slotted into the suit slot for easy storage, and spear's friends shiv and baseball bat can easily be stored likewise in bags.  This is very much a buff, even if slight, the main purpose being to increase crew survivability. Hopefully making spears more viable for nukie rounds (warops or otherwise) as well as a nice self defense weapon against zombies. As for tider extremes using spears more against sec, the increased portability of a spear will not save a greytide from the stun meta, and of course open carrying a spear very obviously on your back is a quick way to get sussed out and searched. Even with this all in mind, I adjusted the crafting recipe just in case.
The spear recipe now has a bottleneck, of which being LV cables. Two rods is easy as hell, you get 2 per steal, so one spear per steel. Glass shards are PLENTIFUL, and reinforced, uranium and plasma even upgrade the spears, and previously one stack of LV could make up to 15 spears.  Now with my nerf, using 3 LV instead of 2 LV, one full LV stack can only make 10 spears. LV on its own while uncommon, tis not too hard to find, and spears can be quite formidable weapons. You CAN currently equip spears to your back proper sacrificing your backpack, but ain't nobody doin that for a spear, hell its quite hard to get a SS14 player to part with having some form of storage.

## Technical details

All spears can now be equipped to the suit storage slot, and use the already existing backpack slot sprites so it will be visibly on the user's back.

The recipe for all spears except the bone spear have been in turn nerfed, now requiring 3 LV per spear instead of 2 LV.

## Media

Screenshot_1

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Spears can now be quipped to your suit slot and cost slightly more to make.

### CODE REVIEW

**Comment by UbaserB** [comment]
wooooo

**Comment by FairlySadPanda** [comment]
:hunterglee:

**Comment by Hanzdegloker** [comment]
why fail

**Comment by Vermidia** [comment]
Looks like there's a unit test that tried to craft a spear (CraftingTests) wasn't updated. It still expects 8 cable to be left when crafting a spear.

**Comment by Hanzdegloker** [comment]
> Looks like there's a unit test that tried to craft a spear (CraftingTests) wasn't updated. It still expects 8 cable (from a stack of 10) to be left when crafting a spear.

thankyou thankyou thankyou

**Pull request merged**
