### PR TITLE
A syringe with romerol for infected zero patient

### PR DESCRIPTION
**Pull request by IlyaElDunaev**
## About the PR

The initial infected person receives a syringe with romerol in backpack.

## Why / Balance

1. The infected are bioterrorists without bioweapons. All antagonists have something personal, but zombies don't.
2. This will improve the gameplay. Attacks and kidnappings for the purpose of infection. Maybe it will add to the fun?
3. Finally, a syringe with romerol will be used. Nuclear operatives very rarely use a zombie kit.

## Technical details

A code has been added to the ZombieRuleSystem.cs for giving starting items.
The ZombieRuleComponent.cs contains a list of starting items.

## Media

https://github.com/space-wizards/space-station-14/assets/154531074/8679ae9c-33c4-4662-93d4-50fb0dcf02d8

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

The initial infected person receives a syringe with romerol.

:cl: IlyaElDunaev
- add: The initial infected person receives a syringe with romerol in backpack.

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Just spawning it in their inventory is kinda goofy

**Comment by IlyaElDunaev** [comment]
> Just spawning it in their inventory is kinda goofy

A spontaneous decision. The example is taken from a revolutionary and a thief

**Comment by Ki-wis** [comment]
Yeah I think that makes it more interesting than just turning into a zombie. Could also potentially make it a possibility to convert the captain if you manage to kidnap him, though it probably wouldn't be the most efficient decision

**Comment by UbaserB** [comment]
I liked to think the II isnt doing this on purpose, but any sabotage/etc is the effects of the disease on their mind (like rabies or something idk). Like uh, the person being unaware of what is happening since they caught the disease by chance.

This change will reduce opportunities for variety in II roleplay imo.

**Comment by K-Dynamic** [comment]
Finally, bioterrorist zombie lore

I'm more excited in dumping it in random food, med jugs or injecting patients in medbay

I would prefer a hypopen tbh but syringe is more subtle anyways

> I liked to think the II isnt doing this on purpose, but any sabotage/etc is the effects of the disease on their mind (like rabies or something idk). Like uh, the person being unaware of what is happening since they caught the disease by chance.
> 
> This change will reduce opportunities for variety in II roleplay imo.

This would make sense from a hivemind point of view, but unless you give them romerol glands or something then this is the next best thing

Also I don't like the idea that initial infected are 'unwillingly' sabotaging or the fact anyone else infected (via bite) should sabotage by implication

**Comment by QuietlyWhisper** [comment]
I don't recall how much romerol is required to start turning someone, but you need to consider that this would essentially let initial infected convert people stealthily, almost at no risk, for free. This chemical would be able to be injected into foods, water, medicine, anything really. I get the design goal of kidnapping people and infecting them, but I think the first example is more likely to happen.

**Comment by Ki-wis** [comment]
> I don't recall how much romerol is required to start turning someone, but you need to consider that this would essentially let initial infected convert people stealthily, almost at no risk, for free. This chemical would be able to be injected into foods, water, medicine, anything really. I get the design goal of kidnapping people and infecting them, but I think the first example is more likely to happen.

I think giving them enough romerol to convert one person is fine. Their objective is for the zombies to win even if the "initial infected" isn't converted immediately. That way you can't use the romerol on someone and then kill him and be done with the zombies, because you will lose. I think it's fine if they want to waste the syringe in turning someone random at bar, it's just as bad as becoming a zombie in a place where you can be immediately killed.

**Comment by Krunklehorn** [comment]
If you orally consumed more than 5u, say 10u, would the digestion eventually pile up to 5u and get you infected?

You can spike a single person's drink, or go the injection route and try to go for three people. Sounds fine to me?

**Comment by EmoGarbage404** [comment]
This should wait for the larger antag refactor being worked on as it will make adding this behavior significantly easier.

**Comment by wafehling** [comment]
> This should wait for the larger antag refactor being worked on as it will make adding this behavior significantly cleaner.

Do you have a link to this refactor and a time estimate? This change seems like a good, simple one, and is already complete. I don't see why waiting for a large change is needed

**Comment by metalgearsloth** [comment]
Design is okay but the implementation is bad to bake it entirely into the gamerule, just refactor it for antag rework which just needs a review.

**Pull request closed without merging**
