### PR TITLE
tweak(StorageImplant): Allow the UI to be closed using the action

### PR DESCRIPTION
**Pull request by Brandon-Huu**
# Why
having to click the X instead of just pressing the action key is annoying

# Technical Details

Doesn't have a useDelay
might fix the two open issues idk, couldn't reproduce them
should I rename the event from Open to Toggle?

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
image
Tried adding the useDelay and it doesn't work for whatever reason.

Do I even need it?

**Comment by slarticodefast** [comment]
This needs the UseDelay to stop sound spamming. I think to get it working you have to add UseDelayComponent to the implant and then do the same as here
grafik

**Comment by deltanedas** [comment]
should just remove the storage implant sound, people probably metagame it by hearing the rummaging sound and assuming they are using a storage implant to pull out a hypopen or something

**Comment by Brandon-Huu** [comment]
> This needs the UseDelay to stop sound spamming. I think to get it working you have to add UseDelayComponent to the implant prototype and then do the same as here grafik

Already did that, didnt work

**Comment by slarticodefast** [comment]
I finished this PR by adding the use delay in #31381
Thank you for your contribution.

**Pull request closed without merging**
