### PR TITLE
Borg damage modifier sets

### PR DESCRIPTION
**Pull request by SoulFN**
## About the PR

This PR gives all borg 10% resistance to brute and heat traumas
## Why / Balance

Borgs are weak, anyone can kill them with their bare hands, even the assault borg has resistances equal to a normal passanger.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame
## Breaking changes

**Changelog**

:cl:
- add: Added damage modifier sets to all cyborgs

### CODE REVIEW

**Comment by SoulFN** [comment]
Maybe i need to increase syndicate borg repair delay? Or just nerf resistances?

**Comment by muburu** [comment]
you should just make it so repairing doesn't take any longer, but instead just repairs a set amount of damage, so repairing them once doesn't instantly restore them to 100% HP.

**Comment by Golinth** [comment]
I know this is outside the scope of this PR, but I’d like to see different types of repair be needed for different types of damage. Brute still needs welding, but Burn needs an open panel, wire cutters and LV replaced or something.

**Comment by K-Dynamic** [comment]
Don't forget assault borgs get deswords with big 'fuck you' rng to bullets and lasers

If anything, both standard and assault borgs need quick but partial repairs with each weld

**Comment by Callmore** [comment]
> Borgs are already very well armored. They have 200 HP to crit instead of 100 and don't slow down at higher damages. The assault cyborg does NOT need to get tankier.

don't borgs have only 100 until they enter crit (ie fall over) and then if they take another 200 (totalling up to 300) they get destroyed?

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> > Borgs are already very well armored. They have 200 HP to crit instead of 100 and don't slow down at higher damages. The assault cyborg does NOT need to get tankier.
> 
> don't borgs have only 100 until they enter crit (ie fall over) and then if they take another 200 (totalling up to 300) they get destroyed?

yes, but syndie borgs have 200 HP while not in crit. and personally, they should be tougher. the only reason anyone can argue that syndie borgs should not get resist is because of deflect chance from the DEsword (that i think should be replaced)

for normal station borgs, they go down faster than a grey tider, since even a tider gets their hands on some basic body armor.

**Comment by SoulFN** [comment]
If the syndicate borg is too strong, I can raise his price or reduce his resistance, but I think the borg should be very strong, because except for killing he can't do anything, he can't even take the disk and activate the warhead, without the help of operatives he can't even heal himself

**Comment by DandiIion** [comment]
Sidenote what does the "less resistant to shock" mean? Borgs are shock immune (and have to be so they can do repairs since they cant wear insuls.)

**Comment by SoulFN** [comment]
> Sidenote what does the "less resistant to shock" mean? Borgs are shock immune (and have to be so they can do repairs since they cant wear insuls.)

They are still immune to shock like they wearing insuls, but if you can somehow deal shock damage to them, it will be increased.

**Comment by DandiIion** [comment]
Sidenote for those worrying about borg strength, remember Ion Rifles etc are being added at some point so them having bare minimum resistances is pretty justifiable.

**Comment by superjj18** [comment]
2-3 evil Borgs can already easily murderbone a lot of people.  They have effectively infinite health because so long as they have the basic tool module they can repair each other, and good Borgs usually can't engage in combat and are restricted into more of a paramedic/door opener support role

**Comment by osjarw** [comment]
> But they didn't have any good weapons, can be disabled using EMP (Uranuium + Iron) and in future robotics console would be added

We still have the Uranium+Iron EMP?
I recall it being in the guidebook, but I haven't seen it on there lately

**Comment by SoulFN** [comment]
> We still have the Uranium+Iron EMP?
> I recall it being in the guidebook, but I haven't seen it on there lately

#18248 added this, you need iron, uranium and aluminium, not only iron and uranium

**Comment by SoulFN** [comment]
I decided to remove assault borg modifier set and give assault borg regular borg damage modifier set, because he is already op

**Comment by SoulFN** [comment]
I will create a new PR because i fucked up

**Pull request closed without merging**
