### PR TITLE
Zombie is gonna break those cuffs!

### LINKED ISSUE #26060: Players do not lose handcuffs when turning zombie
## Description

The Fix uncuffing for zombies has stopped working (https://github.com/space-wizards/space-station-14/pull/21021).

**Reproduction**

Cuff urist
Control a zombie and bite urist until they zombify
Control urist
Urist is unable to attack now as they are still handcuffed

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/154531074/fe470075-eff6-4b8c-a3c5-991f94084eac

**Additional context**

This probably happened after disabling the damage while trying to remove the handcuffs (https://github.com/space-wizards/space-station-14/pull/25161)

### LINKED ISSUE #30396: Zombie Cuffing Broken Again
## Description
Cannot un cuff once you become a zombie
Could be because I was initial infected and not converted
https://github.com/space-wizards/space-station-14/pull/21021

Could also be with makeshift cuffs Possibly related to https://github.com/space-wizards/space-station-14/issues/30312

### PR DESCRIPTION
**Pull request by IProduceWidgets**
fixes #30396
fixes #26060

## About the PR

Zombies uncuff when they zombify. The alternative is letting them use the uncuff action again, but, I don't really see a compelling reason for that instead of just uncuffing them.

## Why / Balance

Being a cuffed zombie sucks, and not having hands does weird shit.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Zombies will no longer remain cuffed when they turn.

### CODE REVIEW

**Comment by Plykiya** [comment]
Isn't this already handled? https://github.com/space-wizards/space-station-14/pull/30321

**Comment by IProduceWidgets** [comment]
> Isn't this already handled? (just hasn't made it to the servers yet) #30321

uh, maybe! I didn't check publish, I just saw a new issue said it still didn't work. #30396

**Comment by themias** [comment]
Yeah, I just tested on master, and it looks like it is working. I'm guessing it just wasn't published yet.

**Comment by EmoGarbage404** [comment]
this is kinda an imperfect solution considering you shouldn't have to manually handle removing cuffs off of handless entities. since its already fixed i think this PR isn't really needed.

**Pull request closed without merging**
