### PR TITLE
make holoparasites actually holographic

### PR DESCRIPTION
**Pull request by Dutch-VanDerLinde**
## About the PR
title

also makes their melee weapon sounds not silent
normal guardian is punch noise, holoclown is bike horn noise

## Why / Balance
holoparasites are holographic, yet bullets will not phase through them which is strange

## Media

https://github.com/space-wizards/space-station-14/assets/45323883/1a1f03a8-1a21-47d3-8983-c89ef5505263

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- tweak: Holoparasites and holoclowns will now phase through projectiles such as bullets, like a holocarp.

### CODE REVIEW

**Comment by Plykiya** [comment]
TIL you can hit your own holo to hurt yourself

**Comment by B1essedknight** [comment]
If this goes through I don't think the Holo should be priced at its current listing as 14tc for a bodyguard that can't tank some damage for you is agonizing, (plus also praying for a player that knows how to play them).

**Comment by Dutch-VanDerLinde** [comment]
> If this goes through I don't think the Holo should be priced at its current listing as 14tc for a bodyguard that can't tank some damage for you is agonizing, (plus also praying for a player that knows how to play them). 
> 
> 
> 
> Then again i have yet to see many of them honestly in-game as they are a rare purchase. (just my 2 cents)

? This makes it so that bullets can't hit them, it doesn't make their resistances weaker

**Comment by superjj18** [comment]
the sprit may need to be made transparent so the bullet immunity can at very least be visibly seen, rather than new players using their gun, getting gibbed, and immediately making a bug report that bullets phase through holos

**Comment by Emisse** [comment]
they are supposed to be bullet immune it just broke a long time ago

**Pull request merged**
