### PR TITLE
Deluxe soap description change

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
no cl no fun

### CODE REVIEW

**Comment by moonheart08** [comment]
no fun allowed???

**Comment by lzk228** [comment]
noooo!!!

**Comment by PixelTheKermit** [comment]
literally 1984

**Comment by EmoGarbage404** [comment]
At least replace "condom" with something else so it still matches the rest of the item descriptions.

Also if this is over the word "condom" being inappropriate then our baseline maturity is that of a 5th grader.

**Comment by Just-a-Unity-Dev** [comment]
> Also if this is over the word "condom" being inappropriate then our baseline maturity is that of a 5th grader.

i mean i've seen people get banned for immature stupid jokes like this & i feel this is appropriate for the same reason pussy wagon got removed

**Comment by EmoGarbage404** [comment]
at least genitals are something actually explicit. I don't think mentioning something as common as a condom in a non-sexual context in reference to an incredibly popular meme really qualifies.

**Comment by deltanedas** [comment]
lusty xenomorph maid poster:

**Comment by keronshb** [comment]
Do we really have to remove that?

**Pull request closed without merging**
