### PR TITLE
Combat boots, but cool.

### PR DESCRIPTION
**Pull request by asperger-sind**
## About the PR 
This PR adds:
Combat boot unique sprite.
An abstract prototype for storage-boots.
Knife-storing functionality for combat boots.
Some fills here and there.
And more things I forgot about.

For the reviewer:
I'm not sure if I got the tag system right, the combat shoe prototype has a whitelist for knifes in specific, but it might be formatted wrong or some schiz.

**Changelog**

:cl: BurninDreamer
- add: Combat boots can now store knives, HoS, Warden and Nukies get those.
- remove: Knives from Nukies' backpacks, they're in your boots now.

### CODE REVIEW

**Review by Veritius — APPROVED** [review]
if it passes tests it's got my approval

**Comment by asperger-sind** [comment]
tests passe, probably rfm

**Review by Just-a-Unity-Dev — APPROVED** [review]

**Comment by mirrorcult** [comment]
why replace the jackboots sprite?

**Comment by asperger-sind** [comment]
> why replace the jackboots sprite?

Combat boots are a different item with different functionality, having them have the same sprite but different names just felt way too weird.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
