### PR TITLE
Add space debris to salvage magnet

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Removes the underwhelming space debris worldgen and adds it to the salvage magnet.

space debris contains various scrap, equipment, and sellable items alongside small groups of space carp to pose a reasonable threat.

Additionally makes changes to the salvage magnet to make it more random in what it picks rather than always picking 3 asteroids and 3 wrecks. Now it uses a weighted table and randomly selects 5 asteroids, debris chunks, or wrecks.

## Why / Balance

The outer debris in worldgen is basically irrelevant. Underwhelming loot, threats, size, and the distance from the station make it pretty much just dead performance while being at stake of complete irrelevance once the salvage shuttle is gone. 

By integrating it into the salvage magnet with proper procgen, we can create way more varied structures and experiences for players that actually pose a threat.

## Media

image
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The salvage magnet can now pull in large chunks of space debris. Be wary of space carp infestations!
- remove: The small asteroids and pieces of debris that generated around the station have been removed.
- tweak: The salvage magnet now randomly picks what type of pulls will be offered instead of always having a consistent number of each.

### CODE REVIEW

**Comment by sad2284** [comment]
With this update, cargo and RND homeless people

**Comment by TytosB** [comment]
why remove the randomly generated ones? seems like an unncessary trade off, also, adding even these new ruins to the magnet would make getting the actually good magnet ruins even harder since its still only 3 rolls per 5 minutes and the options are going to be even more clogged with underwhelming ruins with a bunch of enemies?

**Comment by SlamBamActionman** [comment]
I really liked the random debris. :( 
It made space feel less empty, and allowed shittle builders to play budget Salvage.

**Comment by sad2284** [comment]
And yes, these fragments are absolutely useless. Judging by the screenshots, the loot there is at the level of ordinary techs, and the opponents are like on an expedition

**Comment by Ilya246** [comment]
yeah, the random debris should be kept, it makes the station not have to rely on salvage as much due to the possibility of budget salvage and makes space not just empty

**Comment by deltanedas** [comment]
i like this being in the magnet but the smaller debris in space should be kept imo

**Comment by Ilya246** [comment]
also, the wrecks in the screenshot feel like they have way too many fish, however, the amount of fish in an open wreck doesn't really matter, as salvage will be able to just bombard said fish with PKAs from their ship

it could be better to make the wrecks have actual rooms with walls and doors perhaps akin to dungeons in exchange for having less fish

**Comment by EmoGarbage404** [comment]
ok so here's an actual breakdown of a magnet with all the loot on it because apparently people didn't bother to look at the generation and just assumed there was literally nothing on them.

image

here's a single space debris pull; notably, it has _multiple sections_ (the screenshots on the PR also depicts a single pull)

For the mob count, we have 12 normally spawning fish and 2 sharkminnow groups. This is obviously a little bit high which is why i have a [pr open right now that decreases the skarkminnow rate](https://github.com/space-wizards/space-station-14/pull/31114/files). I don't really think the number of carp itself is that high considering they're spread on a pretty big area and each one only has 50 health.

In terms of pure sellable items, that being things that you can chuck to cargo and get cash from: there's $8675 worth of traditional "treasure items." There'd also be a decently significant amount of cash to be gained from carp teeth once that PR is merged, as each carp can give you about ~$100 worth of a small item that stacks.

The material amounts are going to be listed as a combo of reclaimed scrap and just sheets spawned on the ground as that's probably the easiest way of doing it. The breakdown by each material type for this single piece of debris is as follows:
- 7.5 stacks of steel
- 4.66 stacks of glass
- 2 stacks of plastic
- 0.33 stacks of plasma

In terms of some misc. things, we also have 3 canisters (one of which being an N2O) that can be sold and a few flashlights which all sell for 140 and contain high capacity batteries inside of them.

The final factor is maints lockers. Though they do contain a lot of low-tier tools, they also can have some high-value sellables, various less-rare items that sell in the 75-150 range, and stacks of materials. It's hard to quantify that because they're kinda spread out but this piece has 15 on it, so there should be a pretty decent spread of stuff.

So as an overview:

In terms of raw materials, it isn't super competitive with magnet asteroids, though it doesn't really need to be. Debris populates with valuable treasure and equipment spawners, meaning you can get tons of high valuable sellable items alongside useful salvaging equipment like hardsuits, weapons, jetpacks, fultons, etc.

On top of that, while there are a decent number of enemies, they are largely low-health and broken up across multiple grids making them unable to effectively swarm in unreasonably high numbers. On top of that, salvage has access to evasive options like fleeing and flanking with jetpacks as well as long ranged options like throwing spears or using the PKA.

I don't really think any of this is unreasonably bad for the value it's giving you, but obviously there are fluctuations in both directions in terms of the things you can get.

**Comment by Ilya246** [comment]
my point with the fish is that they don't really matter, they only act as a way to delay your salvaging of the wreck, not adding anything interesting to the gameplay and serving as a noob trap

it's trivial to kill the fish without taking damage, simply kite them with a jetpack or shoot them all the way from the reclaimer, as the wreck is very open and you can just shoot all the fish from space

a solution could be making the fish target people in space/different grids over more considerable ranges and retaliate the same way if hit by anything, this would make them an actual threat you have to consider and less of a pure noob trap

**Comment by sad2284** [comment]
> Итак, вот реальная поломка магнита со всей добычей на нем, потому что, по-видимому, люди не удосужились посмотреть на поколение и просто предположили, что на них буквально ничего нет.
> 
> image
> 
> Вот одиночное притяжение космического мусора; в частности, он состоит из _нескольких разделов_ (на скриншотах в PR также изображен один пулл)
> 
> Что касается количества мобов, у нас есть 12 обычно нерестящихся рыб и 2 группы акульих минноу. Очевидно, что это немного высоковато, поэтому [у меня сейчас открыт PR, который снижает ставку на скаркминноу](https://github.com/space-wizards/space-station-14/pull/31114/files). Я не думаю, что количество карпов так уж велико, учитывая, что они разбросаны на довольно большой территории, и у каждого из них всего 50 здоровья.
> 
> С точки зрения чисто продаваемых товаров, то есть вещей, которые вы можете бросить на груз и получить наличные: традиционные «сокровища» стоят 8675 долларов. Также будет довольно значительная сумма денег, которую можно будет заработать на зубах карпа, как только этот PR будет объединен, так как каждый карп может дать вам около ~100 долларов небольшого предмета, который складывается.
> 
> Количество материала будет указано в виде комбинации переработанного лома и просто листов, появившихся на земле, поскольку это, вероятно, самый простой способ сделать это. Разбивка по каждому типу материала для этого отдельного куска мусора выглядит следующим образом:
> 
> * 7,5 стопок стали
> * 4.66 стопки стекла
> * 2 стопки пластика
> * 0,33 заряда плазмы
> 
> Что касается некоторых других вещей, у нас также есть 3 канистры (одна из которых N2O), которые можно продать, и несколько фонариков, которые продаются по 140 штук и содержат батареи большой емкости внутри.
> 
> Последний фактор – это бытовые шкафчики. Несмотря на то, что они содержат много низкоуровневых инструментов, они также могут содержать некоторые ценные продаваемые предметы, различные менее редкие предметы, которые продаются в диапазоне 75-150, и стопки материалов. Это трудно измерить, потому что они довольно разбросаны, но на этой части их 15, так что должно быть довольно приличное количество материала.
> 
> Итак, в качестве обзора:
> 
> С точки зрения сырья, он не очень конкурентоспособен с магнитными астероидами, хотя на самом деле это и не нужно. Обломки населены ценными сокровищами и генераторами снаряжения, а это значит, что вы можете получить множество ценных продаваемых предметов наряду с полезным оборудованием, таким как костюмы, оружие, реактивные ранцы, фултоны и т. д.
> 
> Вдобавок ко всему, несмотря на приличное количество врагов, у них в основном мало здоровья и они разбиты на несколько сеток, что делает их неспособными эффективно роиться в неоправданно большом количестве. Вдобавок ко всему, у спасателей есть доступ к вариантам уклонения, таким как бегство и обход с фланга с помощью реактивных ранцев, а также дальнобойные варианты, такие как метание копий или использование PKA.
> 
> Я не думаю, что что-то из этого неоправданно плохо для ценности, которую это вам дает, но очевидно, что есть колебания в обоих направлениях с точки зрения вещей, которые вы можете получить.

I didn't take tech loot out of my head, it's literally judging by your screenshots. Which of these cannot be found in those?   All of these items can be found in those without threatening your ass. And I don't understand why to litter space with this shit.
8000. How long have you been playing for cargo? These are mere pennies. For comparison, you can take out 50000 for one expedition, and this is working there together.
Your updates have literally turned cargo, engineers, and RNDs into homeless people! Now, even if you dig the whole shift, there is not enough ore for everyone!

**Comment by metalgearsloth** [comment]
> my point with the fish is that they don't really matter

this is the debris pr not the fish pr sir.

**Pull request merged**
