### PR TITLE
balance Explosive Technology

### PR DESCRIPTION
**Pull request by takemysoult**
balance ExplosiveTechnology

## About the PR

changed Explosive Technology to tier 2 and made the price higher
## Why / Balance

Explosive Technology is too strong for tier 1 and 8500 price.Due to the fact that this technology is so easy to learn, 30 explosive charges are being crafted each nuke. This is too unbalanced technology for tier 1
## Technical details

changed Explosive Technology to tier 2 and made the price 10000## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
-tweak: Explosive Technology changed to tier 2 arsenal and the cost has increased to 10 000

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
perhaps move the riot control tech down to t1 so that the lower tiers have more items in them. it feels strange to have equal amounts in both.

**Comment by thebadman4662** [comment]
Explosive tech is needed for tier 1 machines, might need more basic grenade tech for igniters instead or actually why not roundstart?

**Comment by takemysoult** [comment]
> perhaps move the riot control tech down to t1 so that the lower tiers have more items in them. it feels strange to have equal amounts in both.
that sounds reasonable.

**Comment by EmoGarbage404** [comment]
> Explosive tech is needed for tier 1 machines, might need more basic grenade tech for igniters instead or actually why not roundstart?

might just make sense at that point to put igniters in autolathe or something with similar parts.

**Comment by takemysoult** [comment]
> perhaps move the riot control tech down to t1 so that the lower tiers have more items in them. it feels strange to have equal amounts in both.

should I make this a separate pr or redo this one?

**Comment by deltanedas** [comment]
just push commits to same branch

**Comment by EmoGarbage404** [comment]
> should I make this a separate pr or redo this one?

same pr is fine

**Comment by Kadeo64** [comment]
honestly explosive technology has a lot of stuff that should really be autolathe. Why the fuck are remote signallers and igniters not autolathe?

also riot control being in tier 1 would be a godsend please

**Comment by takemysoult** [comment]
> > should I make this a separate pr or redo this one?
> 
> same pr is fine

I made the second commit

**Comment by K-Dynamic** [comment]
To clarify, riot control is t1 now? Should be stated in the cl

**Pull request merged**
