### PR TITLE
Updated guidebook, added to AME and Atmos.

### PR DESCRIPTION
**Pull request by Warentan**
## About the PR

Added Tritium and Frezon entries to Atmos guide, as well as added a tip on how to upgrade the AME.

## Why / Balance

Not many know how to make Frezon or Tritium on their own, and this could help newbies get a firm grasp on what they need to do in order to make money or set up the TEG. Also added a tip on how to upgrade the AME, in case power gets a little iffy but Singulo isn't needed yet.

## Technical details

No technical details, simple .yml edit.

## Media

Screenshot from 2023-09-20 18-03-58
Screenshot from 2023-09-20 18-04-13

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Initial PR
Removed a joke
Refreshed branch
Added mix ratios
Changed frezon warning, fixed an image

### CODE REVIEW

**Comment by Partmedia** [comment]
Thanks for your contribution. Two minor issues:

1. The tritium recipe is missing the critical information that the burn mix has to be supersaturated (more than 96%) with oxygen. Otherwise, no tritium is produced.
2. The reason for lowering the temperature is not so that tritium doesn't burn (although that is a legitimate concern), but simply because the freezon reaction won't take place at lower temperatures.

**Comment by Warentan** [comment]
> Thanks for your contribution. Two minor issues:
> 
>     1. The tritium recipe is missing the critical information that the burn mix has to be supersaturated (more than 96%) with oxygen. Otherwise, no tritium is produced.
> 
>     2. The reason for lowering the temperature is not so that tritium doesn't burn (although that is a legitimate concern), but simply because the freezon reaction won't take place at lower temperatures.

On it

**Comment by Warentan** [comment]
Apologies, I have never used git before. This program, even with VisualStudio, is giving me a headache. Please give me a couple hours to find a merge button that doesn't exist.

**Comment by Warentan** [comment]
DO NOT merge until I can figure out how to commit this one fix... The button is still greyed out in VSC because I made a modification, even though that's the point of a commit... I still must fix this.

**Comment by Warentan** [comment]
Finished. PR is an A-OK for pull.

**Review by Partmedia — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
