### PR TITLE
Eyepatches for your other eye

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR
Adds the ability to flip eyepatches over to the other eye! No more having to deal with one eye always being the greedy one who gets to see!

## Why / Balance

Some people want their eyepatch on the other eye
## Technical details

Using FoldableClothing in the same way as the soft hats do but inverts the icon rather than using 2 separate files
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/da666925-8689-483a-b552-b912f7a7455f

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: You can now flip your eyepatches to the other eye! Yarrrrr!

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Can't you just mirror the layer instead

**Comment by Cojoke-dot** [comment]
here is a video of the bug
https://github.com/space-wizards/space-station-14/assets/83733158/c0fa5eb0-fa42-42da-bc9c-c9ebbb47f81c

**Comment by Cojoke-dot** [comment]
> here is a video of the bug... I need some help with this https://github.com/space-wizards/space-station-14/assets/83733158/c0fa5eb0-fa42-42da-bc9c-c9ebbb47f81c

I... uh... did not know that this would not go through and have no idea how to get it to go through. Here is the code I added to SpriteComponent.cs

        [DataField("mirrored")]
        private bool mirrored = false;

        /// <summary>
        ///     Mirrors the layer through a negitive scale.
        /// </summary>
        [Animatable]
        [ViewVariables(VVAccess.ReadWrite)]
        public bool Mirrored
        {
            get => mirrored;
            set
            {
                if (value)
                {
                    Scale = new Vector2(-Scale.X, Scale.Y);
                }
                else
                {
                    Scale = new Vector2(MathF.Abs(Scale.X), Scale.Y);
                }
                mirrored = value;
                UpdateLocalMatrix();
            }
        }

**Comment by metalgearsloth** [comment]
> > here is a video of the bug... I need some help with this [space-wizards/space-station-14/assets/83733158/c0fa5eb0-fa42-42da-bc9c-c9ebbb47f81c](https://github.com/space-wizards/space-station-14/assets/83733158/c0fa5eb0-fa42-42da-bc9c-c9ebbb47f81c)
> 
> I... uh... did not know that this would not go through and have no idea how to get it to go through. Here is the code I added to SpriteComponent.cs
> 
> ```
>     [DataField("mirrored")]
>     private bool mirrored = false;
> 
>     /// <summary>
>     ///     Mirrors the layer through a negitive scale.
>     /// </summary>
>     [Animatable]
>     [ViewVariables(VVAccess.ReadWrite)]
>     public bool Mirrored
>     {
>         get => mirrored;
>         set
>         {
>             if (value)
>             {
>                 Scale = new Vector2(-Scale.X, Scale.Y);
>             }
>             else
>             {
>                 Scale = new Vector2(MathF.Abs(Scale.X), Scale.Y);
>             }
>             mirrored = value;
>             UpdateLocalMatrix();
>         }
>     }
> ```

What's wrong with setting the scale in yaml?

**Comment by Cojoke-dot** [comment]
Yay! I got it! Took me way too long because I forgot to edit the meta files and remove the icon_flipped before testing!

**Pull request closed without merging**
