### PR TITLE
Syndicate Reinforcement Specializations: Medic, Spy, Thief

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

I updated the syndicate reinforcement option for the **traitor uplink**. You can now select between a syndicate medic, a syndicate spy, and a syndicate thief. All choices get the viper and boot knife. These options no longer get the nuclear pinpointer or a death acidifier implant. This does not affect nukie reinforcements.

**Syndicate Medic:**
_"Someone needs reinforcements. Your task is to keep the agent who called you alive."_

- A filled combat medkit

**Syndicate Spy:**
_"Someone needs reinforcements. Your speciality lies in espionage, do not be discovered."_

- A voice mask
- An agent ID

**Syndicate Thief:**
_"Someone needs reinforcements. Your job is to break in and retrieve something valuable for your agent."_

- A suspicious toolbox
- Syndicate jaws of life

## Why / Balance

Syndicate reinforcements are often not used by traitors due to their lack of any particular abilities to help you achieve your goals. At the moment, there's basically no difference between a syndicate monkey and a syndicate reinforcement. To fix this, the reinforcements are now trained in some particular field so that they are more useful from the getgo.

I removed the nuclear pinpointer to further differentiate them from the nuclear reinforcement (just because they're syndies doesn't mean they care about the nuke), and the death acidifier also seemed unnecessary since regular syndicates no longer have access to death acidifiers as of https://github.com/space-wizards/space-station-14/pull/25039

## Technical details

- Splits the ReinforcementRadioSyndicate into an abstract base ReinforcementRadio that all other ReinforcementRadios parent (required so that other radios don't show the new selectablePrototype options)
- Adds the ghost roles, ghost role name, and ghost role description
- Adds three new entities that use the loadout for the respective choice
- Updates the reinforcement radio to select from the three choices
- Created a new base startingGear that just gives syndicate operative clothing, and parented that for each choice to give them their respective gear

RADIAL UI IMPLEMENTATION
- Created `GhostRoleRadioMenu.xaml` and `GhostRoleRadioMenu.xaml.cs`
- `GhostRoleRadioMenu.xaml` has a `RadialMenu` that contains the main `RadialContainer` to put all of the possible ghost role options
- Each `RadialMenuTextureButton` has the `GhostRolePrototype.ID` tied to it, and the image is an `EntityPrototypeView` based on either the `GhostRolePrototype.EntityPrototype` or the newly added `GhostRolePrototype.IconPrototype` field to allow for customizing the image displayed. Clicking the button will send a message with the ID to the `GhostRoleSystem`.
 - A BUI along with the UI key were added, the BUI is set to open centered on the screen. I kind of prefer having it centered on the screen rather than opening wherever your mouse happens to be. Radios were given the `UserInterfaceComponent` and `ActivatableUI` component that make use of the BUI and UI key.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot 2024-07-09 103930

sob, they asked me to change it to be a radial menu on activation, so here we go

https://github.com/user-attachments/assets/2f4d1e74-038a-4a67-a876-2467dcea2747

## Breaking changes

Reinforcement Radios now parent ReinforcementRadio instead of ReinforcementRadioSyndicate
GhostRoleMobSpawnerComponent moved from Content.Server to Content.Shared

**Changelog**

:cl:
- add: Syndicate traitor reinforcements are now specialized to be medics, spies, or thieves.
- tweak: Reinforcement radios with options now have a radial menu, similar to RCDs.

### CODE REVIEW

**Comment by Plykiya** [comment]
Nukie reinforcements need something else entirely, they're nukies after all...

Traitors on the other hand have much more tame goals, I aimed to give them around five TC worth of equipment to work with that was sort of interesting.

**Comment by JIPDawg** [comment]
My guaranteed way of getting a pin pointer for steal the nuke disc obj 😿

**Comment by Plykiya** [comment]
> My guaranteed way of getting a pin pointer for steal the nuke disc obj 😿

if it isn't in the captain's backpack then god bless your soul, the station should be nuked as repentance for their sins

**Comment by beck-thompson** [comment]
Monkeys next 😆

**Comment by deltanedas** [comment]
> My guaranteed way of getting a pin pointer for steal the nuke disc obj 😿

usually if you need to steal the disk the *last* thing you want is more pinpointers for sec to get

**Comment by ElPidor** [comment]
I think noone will use medic and spy because why? Just combat medkit.
https://github.com/space-wizards/space-station-14/pull/29388
this one solves most of reasons why reinfocment sucks 
cobra = more stealth
throwing knife = more cool 
Also pinpointer removement seems a little waky because i saw some players buy reinfocment because they couldnt get a disk. Etc cap gave it to hos, or someone stole, because station have only one pinpointer.

**Comment by Plykiya** [comment]
> I think noone will use medic and spy because why? Just combat medkit. #29388 this one solves most of reasons why reinfocment sucks cobra = more stealth throwing knife = more cool Also pinpointer removement seems a little waky because i saw some players buy reinfocment because they couldnt get a disk. Etc cap gave it to hos, or someone stole, because station have only one pinpointer.

if you REALLY need a pinpointer for the disk you should be able to get a pinpointer for free from the store like  you can get the objective tools for https://github.com/space-wizards/space-station-14/pull/26786 for free, treating reinforcements as a 14 TC pinpointer is just dumb

**Comment by Cojoke-dot** [comment]
> I think noone will use medic and spy because why? Just combat medkit.

Uh… why not? If I'm going into combat it is nice to have a healer with you. Spy if you want they to replace someone else.

> Cobra = more stealth

Cobra is annoying to get ammo for and you are kinda screwed on that front if you run out. You also assume they want the reinforcement to be stealthy…

**Comment by IProduceWidgets** [comment]
The spy far far far outstrips the other options. The main drawback to reinforcement humans is they are incredibly obvious, and a free agent id (plus copying access from whoever summoned you) directly controvenes this.

**Comment by Plykiya** [comment]
> The spy far far far outstrips the other options. The main drawback to reinforcement humans is they are incredibly obvious, and a free agent id (plus copying access from whoever summoned you) directly controvenes this.

I did want one option to be generally all-purpose useful, which is why I made the spy the default option. If the true main benefit that syndicate reinforcements have over holos, monkeys, or syndicats is that you can communicate with them, I wanted to give them the bare minimum tools required to make communication their strongest point. If the agent ID is deemed too powerful despite being an equivalent TC purchase, I can always fallback to giving them a syndicate encryption key box and a passenger headset.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
image

**Comment by Plykiya** [comment]
MY UI CODE IS PERFECT AND WITHOUT FLAW

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
