### PR TITLE
Add coal distribution to progen

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
- Fixes distribution of coal in proceduraly generated environments 
- Fixes [#22753](https://github.com/space-wizards/space-station-14/pull/22753)
- Fixes [#22751](https://github.com/space-wizards/space-station-14/issues/22751)

## Why / Balance
Coal wasn't being generated in most scenarios locking the production of Steel.

## Technical details
I'm 95% sure I found all the instances in the code for this. Do let me know if I missed something.

## Media
n/a
- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
n/a

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.

:cl: Velcroboy
- fix: Fixed coal not generating!

### CODE REVIEW

**Review by metalgearsloth — DISMISSED** [review]
Needs a sprite please

**Comment by IamVelcroboy** [comment]
> Needs a sprite please

😫I was hoping I cold get away without that 🙃

**Comment by metalgearsloth** [comment]
I'm pre sure where the other sprites came from have spare overlays that can be used still.

**Comment by IamVelcroboy** [comment]
I'll check it out. Meanwhile these tests are blowing up

**Comment by IamVelcroboy** [comment]
OK, added the sprite. 
image

**Pull request merged**
