### PR TITLE
Removes funny smug plushie

### PR DESCRIPTION
**Pull request by SweptWasTaken**

### CODE REVIEW

**Comment by DrSmugleaf** [comment]
Good night king

**Comment by Zumorica** [comment]
Sad.

**Comment by metalgearsloth** [comment]
Too pure for this world

**Comment by PJB3005** [comment]
Bring it back.

**Comment by SweptWasTaken** [comment]
> Bring it back.

https://en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy

**Comment by moonheart08** [comment]
> > Bring it back.
> 
> [en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy](https://en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy)

https://github.com/space-wizards/space-station-14/blob/4b76ca68220ef059b0db802d8325a3363b0b1ec0/Resources/Prototypes/Entities/Objects/Fun/toys.yml#L161-L163

**Comment by SweptWasTaken** [comment]
> > > Bring it back.
> > 
> > 
> > [en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy](https://en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy)
> 
> https://github.com/space-wizards/space-station-14/blob/4b76ca68220ef059b0db802d8325a3363b0b1ec0/Resources/Prototypes/Entities/Objects/Fun/toys.yml#L161-L163

The carving sprites are made by Bright, I paid for the snivy sprite as a commission from another spriter.

**Comment by Peptide90** [comment]
> > > > Bring it back.
> 
> > > 
> 
> > > 
> 
> > > [en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy](https://en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy)
> 
> > 
> 
> > https://github.com/space-wizards/space-station-14/blob/4b76ca68220ef059b0db802d8325a3363b0b1ec0/Resources/Prototypes/Entities/Objects/Fun/toys.yml#L161-L163
> 
> 
> 
> The carving sprites are made by Bright, I paid for the snivy sprite as a commission from another spriter.

Carvings should all be gone now, I removed all obvious copyright material the other week. Presumably regardless of origin snivy is nintendos property so up to y'all.

**Comment by SweptWasTaken** [comment]
> 

What PR did you do that in?

**Comment by Peptide90** [comment]
> > > > > > Bring it back.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > [en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy](https://en-americas-support.nintendo.com/app/answers/detail/a_id/50035/~/intellectual-property-policy)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > https://github.com/space-wizards/space-station-14/blob/4b76ca68220ef059b0db802d8325a3363b0b1ec0/Resources/Prototypes/Entities/Objects/Fun/toys.yml#L161-L163
> 
> > > 
> 
> > > 
> 
> > > The carving sprites are made by Bright, I paid for the snivy sprite as a commission from another spriter.
> 
> > 
> 
> > Carvings should all be gone now, I removed all obvious copyright material the other week. Presumably regardless of origin snivy is nintendos property so up to y'all.
> 
> 
> 
> What PR did you do that in?
> 
> 

#5788

**Pull request merged**
