### PR TITLE
Add windows to test targets

### PR DESCRIPTION
**Pull request by Ygg01**
Prevent stuff breaking windows builds, by adding a windows run target.

### CODE REVIEW

**Comment by Zumorica** [comment]
Seems the check doesn't even run?

**Comment by Ygg01** [comment]
Seems so... Not sure why.

**Comment by Erisfiregamer1** [comment]
Hey, its running!

**Comment by Erisfiregamer1** [comment]
Content integration d i e d !

**Comment by Ygg01** [comment]
@Erisfiregamer1 as it should. it's broken on windows

**Comment by PJB3005** [comment]
Mind doing this engine-side as well?

**Comment by Ygg01** [comment]
@PJB3005 sure. Will do.

**Pull request merged**
