### PR TITLE
Adds New Shoes to Sec loadouts

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

Adds the JackBoots to sec loadouts. Adds the ability to put knives/sidearms in Security Winter Boots. Add a pair of High-Heeled Boots to the sec drobe.
## Why / Balance

 - Jackboots  are already an option in the sec drobe
 - Security Winter Boots should not give a disadvantage compared to the other shoes for a different look
## Technical details

yml edits, make a new parent prototype for FilledSecBoots
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: You can now find Jackboots in the security load-outs
- remove: The Sec drobe no longer has a Cowboy hat or boots

### CODE REVIEW

**Comment by K-Dynamic** [comment]
IMO high-heeled boots don't really fit sec's theme other than being inspired by combat boots and knife storage - they're comically long #22382 

Yeah I'm aware secoffs can wear other clothes, I just wouldn't want it as a roundstart uniform.

**Comment by Hanzdegloker** [comment]
Yeah High Heeled boots gotta go, thems some funny maints loot. Not roundstart sec gear.

**Review by EmoGarbage404 — DISMISSED** [review]
the cowboy boots and high heels aren't security uniform so they should be removed. The jackboots are fine however

**Comment by Cojoke-dot** [comment]
> the cowboy boots and high heels aren't security uniform so they should be removed. The jackboots are fine however

I understand the high-heeled boots but why not the black cowboy boots? A pair spawns in the sec drobe implying they are security equipment.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
While i agree with not adding the high-heels, sec has had access to cowboy equipment for the last month or so via the sec-drobe, and it fits the theme of the department well.

**Comment by EmoGarbage404** [comment]
> While i agree with not adding the high-heels, sec has had access to cowboy equipment for the last month or so via the sec-drobe, and it fits the theme of the department well.

requesting an MLA-style 3 paragraph essay about how kitschy cowboy outfits are a thematic match for a space station's local law enforcement division.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> > While i agree with not adding the high-heels, sec has had access to cowboy equipment for the last month or so via the sec-drobe, and it fits the theme of the department well.
> 
> requesting an MLA-style 3 paragraph essay about how kitschy cowboy outfits are a thematic match for a space station's local law enforcement division.

LALALA, CANT HEAR YOU OVER THE SOUND OF MY COWBOY BOOTS GOIN *tinkclink thinkclink*

**Comment by Cojoke-dot** [comment]
I kept the filled boots prototypes for the high-heeled boots and black cowboys in there because I am lazy and why the hell not

> requesting an MLA-style 3 paragraph essay about how kitschy cowboy outfits are a thematic match for a space station's local law enforcement division.

Hos has a cowboy hat as a part of their loadout...

**Comment by ARMOKS** [comment]
> > While i agree with not adding the high-heels, sec has had access to cowboy equipment for the last month or so via the sec-drobe, and it fits the theme of the department well.
> 
> requesting an MLA-style 3 paragraph essay about how kitschy cowboy outfits are a thematic match for a space station's local law enforcement division.

https://en.m.wikipedia.org/wiki/Cowboy_Bebop

Read it and weep

**Comment by ARMOKS** [comment]
Also like cowboy boots are a classic police uniform thing, they are timeless and still used to this day

**Pull request merged**
