### PR TITLE
make dragons breathe fire

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- dragons can shoot out streams of fire (projectile that spams firebomb explosions) with an action
- dragon is fireproof otherwise they can very easily die from it and it makes sense

## Why / Balance
- gives dragons a better way to deal with silly humans, lighting them on fire so they run away and cry
- make dragons less of a meme
- dragons breathe fire
- ss13 parity

## Technical details
added 2 new things `RepeatingTrigger` for the projectile and `ActionGun` for shooting a gun with a world target action

## Media

https://github.com/space-wizards/space-station-14/assets/39013340/3bea721c-6dc1-4671-88cf-3461fb6e806e

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Dragons can now breathe fire.

### CODE REVIEW

**Comment by B1essedknight** [comment]
The almighty dragon ops cometh.  Also, wouldn't le fish have to be careful around their boss not to become grilled fish or will dragon carps have some fire resist as well?

**Comment by deltanedas** [comment]
right now fish will get roasted so dragon should communicate beforehand, maybe dragonbrood fish should get fire resistance too

**Comment by muburu** [comment]
no more getting mobbed by shitters with shards of broken glass!!

**Comment by DogZeroX** [comment]
Need the dragon fire sfx from ashdrake

**Comment by Errant-4** [comment]
I like the idea of dragons getting a ranged attack, but the pre-explosion effect is a bit strange, and I'm not sure what the purpose of that is if it will detonate on impact anyway? Is it mostly just for looks? Or to deal at least some damage on close passes?

**Comment by deltanedas** [comment]
its so theres a line of things that can get caught on fire not just the end, then it would be a fireball and nothing else

the actual explosion does like 5 damage the fire is the real weapon

**Comment by Golinth** [comment]
I haven’t looked at explosion code at all, but is it possible to keep ‘fireball’ active for longer, kind of like how the nuke explosion stays active for multiple seconds? I think the effect would look much better with quicker repeating timer, a 1 tile radius, and a longer persisting flame/explosion. 

Even if it’s not, I absolutely love this, and gives the dragon some much needed attention

**Comment by deltanedas** [comment]
yeah thats what i want basically plasmafire  that doesnt spread, but not sure how to do said effect

**Comment by B1essedknight** [comment]
Outta curiosity, how easy would it be for the dragon to over-pressurize an area with its breath if for whatever reason it decides not to space the place to make the most use of its breath?

**Comment by deltanedas** [comment]
its not actual fire its implemented with explosions so it doesnt overpressurize anything

**Comment by SoulFN** [comment]
I think it should be a right mouse button attack, instead of action

**Comment by deltanedas** [comment]
wyci

**Comment by deltanedas** [comment]
should i make a proper thing for having repeatable explosives to fix test

**Comment by metalgearsloth** [comment]
This doesn't look like the ss13 one I've seen at all.

**Comment by metalgearsloth** [comment]
Which ss13 server is it parity with.

**Comment by deltanedas** [comment]
the mere concept of breathing fire

**Review by mirrorcult — APPROVED** [review]

**Comment by metalgearsloth** [comment]
Spawning an entire fake gun for the action is pretty awful but I'll just fix it later I guess.

**Comment by deltanedas** [comment]
having the dragon itself have gun component is what i tried first, it was bad to control or something + examine dragon showed the funny

**Comment by metalgearsloth** [comment]
Other mobs like xenos also have that problem but I'd rather not just dupe ents across all of them.

**Comment by deltanedas** [comment]
also having gun be on the dragon means not being able to melee which is horrible

**Comment by lzk228** [comment]
cant we just make like showExamile bool for guncomp?

**Comment by deltanedas** [comment]
yes but thats just minor isssue

**Pull request merged**
