### PR TITLE
remove pointing arrow from salvage

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
related to #11097 
**Screenshots**

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by ElectroJr** [comment]
The arrow prototype should also get a `save: false` slapped onto it to prevent this in future.

**Comment by EmoGarbage404** [comment]
> The arrow prototype should also get a `save: false` slapped onto it to prevent this in future.

as of right now, it has that. Perhaps it got added in some point inbetween this maps creation and now.

**Comment by ElectroJr** [comment]
>  Perhaps it got added in some point inbetween this maps creation and now.

#7624 literally 10 days after the maps creation, thanks past me.

**Review by ElectroJr — APPROVED** [review]

**Comment by ElectroJr** [comment]
Ah. There are actually three of them.....

**Pull request merged**
