### PR TITLE
Temp pull spongebox off uplink

### PR DESCRIPTION
**Pull request by Equivocateur**
## About the PR
Pulls sponge off uplink, currently it just destroys rounds since every comedian with an uplink (average of 7) can just spawn 18 mobs that kill most of the station in the first few minutes, and due to the chaos of having an entire zoo of hostile creatures on the station most people start rotting therefore out of the game unless salv miraculously obtains a cloner (byond the impossible, they're dead trying to validhunt as always).

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Removed sponge box from uplink pending rebalance

### CODE REVIEW

**Comment by Equivocateur** [comment]
Woulda coulda shoulda did the change in #17936 but I just pressed the button there to revert.

**Comment by Geekyhobo** [comment]
I see you played the last like three round like me, and were killed by the 30 zoo animals that are sentient and are extremely aggressive. 

Yeah I think its a cool item, but it needs to be nerfed. 

Opened a issue as well #17939

**Comment by Arendian** [comment]
> I see you played the last like three round like me, and were killed by the 30 zoo animals that are sentient and are extremely aggressive.

Only a few of the monsters can be sentient(rat servant/xeno ravager/yellow slime/space spider(30% chance) and space kangaroo(20% chance). For the price of 30 animals people could also have spawned 15 carps that are friendly to themselves. 


It might just be people needing to get used to the existence of the boxes, but since you played shifts with it(and I didn't) you probably know the impact of the item in a real shift better. 
I honestly expected the fact of it being suicide to spawn a lot of them to deter people from spawning too many, and I think the use rate may lower after it's not a "new" item anymore. 
People would also spawn 10 carps every shift when the dried carp was added to the uplink which is now way more uncommon.
Most of the mobs on the list have lower damage per hit than carps(5 pierce/10 slash), some of them also suffer from damage slowdown/are slower than carps(the holocarp is one of the strongest monster you can get from the box).

Rat servant(8: 5 slash, 3 pierce)
Angry bee(3: 2 poison, 1 pierce)
Space Tick (10(only 2 after having done 5 hits): 2 blunt, 1u of toxin(8 poison/u))
Purple Snake (13: 5 pierce, 1u of toxin(8 poison/u)
Space Spider (11: 6 pierce, 2 poison, 3u of chloral hydrate(1 poison/u))
Space Kangaroo (11: 9 blunt, 2 slash)
Angry yellow slime (10: 6 blunt, 1 caustic, 3 cellular)
Holocarp (15: 10 slash, 5 pierce)
SpaceBear (11: 9 blunt, 2 slash)
Xeno Ravager (10: 3.33 pierce, blunt and slash)

3/10 options(rat/bee/tick) die in 1-2 hits of any object you could classify as a weapon. 

If it's determined that it really does need a nerf I think removing 1 or 2 mobs from the pool would already lower it's power a lot since it would drastically increase the amount of rats/bees/ticks spawned from a bunch of cubes.
Someone in the discord also mentioned making it a zookeeper only item, this also sounds like a possible solution. Only one current station has that role though.

**Comment by lzk228** [comment]
LRP moment

**Comment by Equivocateur** [comment]
> For the price of 30 animals people could also have spawned 15 carps that are friendly to themselves.

Space carp are not tanky, however 10 carps at once is still as issue and it has been discussed on discord.

>18 random monsters(out of which 5-6 on average die in 1 hit)

Only the rat servant there dies in one hit from a crowbar or toolbox and that is only if its critted.

> Damage numbers:

>Rat servant(8 damage: 5 slash, 3 pierce)
Angry bee(3 damage: 2 poison, 1 pierce)
Space Tick (10 damage(only 2 after having done 5 hits): 2 blunt, 1u of toxin(8 poison/u))
Purple Snake (13 damage: 5 pierce, 1u of toxin(8 poison/u)
Space Spider (11 damage: 6 pierce, 2 poison, 3u of chloral hydrate(1 poison/u))
Space Kangaroo (11 damage: 9 blunt, 2 slash)
Angry yellow slime (10 damage: 6 blunt, 1 caustic, 3 cellular)
Holocarp (15 damage: 10 slash, 5 pierce)
SpaceBear (11 damage: 9 blunt, 2 slash)
Xeno Ravager (10 damage: 3.33 pierce, blunt and slash)

This is all at once as the mobs spawn from the same tile usually (stacked cubes). This causes you to go from full health to crit in 1-2 seconds.

> I honestly expected the fact of it being suicide to spawn a lot of them to deter people from spawning too many and I think the use rate may lower after it's not a "new" item anymore, people would also spawn 10 carps every shift when the dried carp was added to the uplink which is now way more uncommon.

It's very easy to spawn the mobs in a crowd so that it wouldnt target/kill you and its easier to get away from the mobs if you know they're there or when they're going to show up.
Also, spray bottles have a wide reach




> LRP moment

Cope

**Pull request merged**
