### PR TITLE
Fully Revert Clown Waddling

### PR DESCRIPTION
**Pull request by Golinth**
## About the PR

Fully reverts waddling, revival of #29161

## Why / Balance

- Requested by Sloth [here](https://github.com/space-wizards/space-station-14/issues/29156#issuecomment-2175767921) and further approved of [here](https://github.com/space-wizards/space-station-14/pull/29161#issuecomment-2176043612).  A couple other people in the discord, including a game admin, also requested this.

- The original PR was closed by the creator deleting their head repository, not by any consensus. 

Waddling as implemented is entirely broken, the original creator is no longer working on SS14, and it needs reimplementing according to Sloth's reviews (something entirely above my skill level). I am sad to see it go, but as-is it makes the game look and feel worse as a clown. 

## Technical details

Reverts  #26338, #26965, #26983, and #27628

## Media

clown-neutral-face-white-46962104-2392398420

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking Changes
Removed: 
WaddleAnimationSystem
WaddleWhenWornComponent
WaddleClothingSystem
WaddleAnimationComponent
SharedWaddleAnimationSystem

**Changelog**

:cl:
- remove: Removed clown waddling until implemented properly

### CODE REVIEW

**Comment by regenpower** [comment]
1984

**Comment by slarticodefast** [comment]
Yeah, this is neccessary, waddling has too many bugs.
Could you mention the removed components and systems in the breaking changes section of your PR?

**Comment by deltanedas** [comment]
as said the original author will not work on this, so waddling will be gone for at least a year before anyone cares enough to rework it all

**Comment by Golinth** [comment]
> Yeah, this is necessary, waddling has too many bugs. Could you mention the removed components and systems in the breaking changes section of your PR in case forks use them for something else?

should be good now

**Review by slarticodefast — APPROVED** [review]

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by slarticodefast** [comment]
In case someone wants to work on a proper reimplementation, some of the requirements are mentioned here: #29156

**Pull request merged**
