### PR TITLE
Adds RCD and RCD ammo to all engineer lockers.

### PR DESCRIPTION
**Pull request by Aexxie**
## About the PR

CE, Atmos, and Engineering lockers all start with RCDs and one ammo. 

## Why / Balance

Test PR, discussed in #development on discord. Testing changes with the fireaxe and many structures

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Aexxie
- add: Added RCDs to all engineering lockers.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
i like this idea, good QOL for engineers and matter cartridges are somewhat rare anyways

**Comment by Holinka4ever** [comment]
I was to late to say my opinion,but anyway i will say:
It will encourage griefers to take tech.assistence to use it to make spacing areas/other griefy stuff.

**Comment by deltanedas** [comment]
techies can still smash a window / blow ame up / singuloose

**Comment by JoeHammad1844** [comment]
RCD griefing techie vs passenger with rods, steel and a crowbar in his bag

**Pull request merged**
