### PR TITLE
New foam sprites (edge sprites)

### PR DESCRIPTION
**Pull request by brainfood1183**
Changed - New edge sprites for foam.

https://github.com/space-wizards/space-station-14/assets/113240905/0cfb173b-7ab7-42b0-add8-b2e72bc812b0

- [x] Make sure metal foams are working correctly.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Flareguy** [comment]
This does not contrast well with the environment at all and is really easy to mistake for puddles until inspected more closely, especially considering this doesn't smooth with relation to walls like puddles.

I would probably advise against giving foam a puddle shape like this period, the full tile coverage makes it obvious that it's a tile effect like fire or smoke. Foam icon smoothing probably isn't a bad idea, but I don't think this is the way to go.

**Comment by deltanedas** [comment]
just give it a bubbly edge but dont change overall shape from a full tile

**Comment by brainfood1183** [comment]
> just give it a bubbly edge but dont change overall shape from a full tile

will test it out

**Comment by brainfood1183** [comment]
> just give it a bubbly edge but dont change overall shape from a full tile

like this?


Uploading Desktop 2023.10.28 - 20.01.33.08.mp4…

**Comment by UbaserB** [comment]
I genuinely dont know how to feel about the sprite

**Pull request merged**
