### PR TITLE
Dress everyone up as clowns

### PR DESCRIPTION
**Pull request by Litogin**
## About the PR

The station staff will be dressed as clowns or partially
## Why / Balance

On the first of April
Last attempt: #26245 

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Litogin
- tweak: Now everyone except the mime and the clown are dressed in clown costumes
- add: Added unremovable clown mask.

### CODE REVIEW

**Comment by ImWeax** [comment]
I think the clown should be the only person dressed as a regular passenger on top of this lol

**Comment by potato1234x** [comment]
dont make the mask unremovable how are you gonna wear an oxygen mask

**Comment by Dutch-VanDerLinde** [comment]
> dont make the mask unremovable how are you gonna wear an oxygen mask 

clown masks act as oxygen masks

**Comment by potato1234x** [comment]
they do?

**Comment by Litogin** [comment]
> they do?
> 

Who?

**Comment by Litogin** [comment]
> they do?
> 

nvm

**Comment by VasilisThePikachu** [comment]
I can almost hear it....

**Comment by VasilisThePikachu** [comment]
Thank you for your PR, unfortunately, the maintainer's conscious was to deny it for the reason that it just makes the game more annoying to play due to the constant clown shoe squeaking even if it's just for April fools.  It's also not funny.

**Pull request closed without merging**
