### PR TITLE
Added winddown to space drugs effect

### PR DESCRIPTION
**Pull request by PolterTzi**
## About the PR

The space drugs shader effect now gradually loses intensity as it's nearing its end.

## Why / Balance

Makes for a smoother transition than going from 100% to 0% instantly.

## Media

https://github.com/space-wizards/space-station-14/assets/62557990/1dd19974-1066-4f76-a270-6844f35af042

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by beck-thompson** [comment]
Great change!

**Comment by UbaserB** [comment]
ohhhhh this is really nice. If the transition was even longer than this, i think it’d be perfect.

**Comment by Cojoke-dot** [comment]
Sweet, good change. Space drugs have always been super quick on and off.

**Comment by PolterTzi** [comment]
> ohhhhh this is really nice. If the transition was even longer than this, i think it’d be perfect.

The transition is 1/16 of the duration.
It's still supposed to be quick, just gradual enough to be less jarring.

**Pull request merged**
