### PR TITLE
Change minibomb to be explosion resistant and start timer on damage

### PR DESCRIPTION
**Pull request by SaphireLattice**
## About the PR
Prevents C4+Minibomb combo from being instant and impossible to do anything about without excessive paranoia. Same idea as #32423, but done from the other end. Mutually exclusive with it, unless maintainers will want to go for maximum fun.

For even more fun, see #32428 that makes the container fly into a random direction before the second explosion.

## Why / Balance
See #32423, but without the note about nukies. Instagib throwable shouldn't be near impossible to counterplay *in an RP game full of distractions lasting 5+ seconds*. This isn't a twitch shooter.

## Technical details
Creates a new damage threshold behavior that works on explosives and causes them to start counting down. In combination with extreme explosive resistance, this allows for a bomb that's not deleted and is counting down, after being triggered by another explosive. Current version of this PR only does this to minibomb, though. So no funny business with C4, unless someone requests that. Also it will just disappear without exploding if damaged too much. Gotta be careful!

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Minibomb is now explosion resistant and will start counting down if damaged by a C4

### CODE REVIEW

**Comment by ScarKy0** [comment]
Gasp! A good PR!

**Comment by Ilya246** [comment]
i think #32423 solves the problem better

**Comment by SaphireLattice** [comment]
@Ilya246 
> i think #32423 solves the problem better

Biggest concern I have about that one is that there's just going to be another convenient instant explosive that might need to be patched up later. If you can think of any, will be very glad about it!

**Comment by thebadman4662** [comment]
>Biggest concern I have about that one is that there's just going to be another convenient instant explosive that might need to be patched up later. If you can think of any, will be very glad about it!

IEMs already exist, they have 20s fuse but they make no sound so they are perfect for detonating minibombs. Or chain chemical reactions, though after 50% dmg nerf latter won't gib anyone for 0TC anymore.

**Comment by deltanedas** [comment]
c4 uses blast caps irl to detonate, and theres nothing physically preventing you from rigging any high voltage source to them. this doesnt mean its good for gameplay though, once liltenhead made that video everyone copied a once niche tactic for untelegraphed instant gibs

**Comment by hyphenationc** [comment]
I much prefer this option as opposed to the C4 timer on signal, as this allows for counterplay but still wounds, whereas C4 would still be able to be delivered without much counterplay, instead requiring the deliverer to just cook the C4 (which they can already do without a signaler, can they not?)

**Comment by SaphireLattice** [comment]
> allows for counterplay but still wounds

Instant C4+timed minibomb centered at the same tile as the target person will, unless either the target or the container is moved, ensue gibbing. C4 crits people when exploded at the same tile and they got no armor.

**Comment by hyphenationc** [comment]
forgot to mention that one, yeah the container moving should be merged too if this one is
it's just too funny to have bouncing bombs

**Comment by SlamBamActionman** [comment]
Hello! We've had a discussion and vote among the maintainer team with the following result: Merge, but with changes.

The change the team would like to see is that the bomb still instantly detonates upon very high damage, rather than merely breaking into nothingness. If you get hit by, say, a China Lake point blank it might feel weird if the bomb either disappears or starts just beeping. The threshold should definitely be higher than just a single C4 though. 

The other PRs related to this functionality (#32428 and #32423) have also been discussed and will be merged, pending testing and code review.

**Comment by SaphireLattice** [comment]
> The change the team would like to see is that the bomb still instantly detonates upon very high damage, rather than merely breaking into nothingness. If you get hit by, say, a China Lake point blank it might feel weird if the bomb either disappears or starts just beeping. The threshold should definitely be higher than just a single C4 though.

Sure, can do that. Would appreciate any specific figure beyond "more than one C4" though. Currently I think it takes two to pass the destruction threshold.

Personally I think this sort of "instantly detonate on integrity failure" thing should cause a smaller explosion, rather than a full one. But that would require a bit more code changes I think. Should I try to go for that, or just implement instant detonation on failure for now and throw in the reduce damage on integrity failure later?

**Comment by SlamBamActionman** [comment]
> Sure, can do that. Would appreciate any specific figure beyond "more than one C4" though. Currently I think it takes two to pass the destruction threshold.
> 
> Personally I think this sort of "instantly detonate on integrity failure" thing should cause a smaller explosion, rather than a full one. But that would require a bit more code changes I think. Should I try to go for that, or just implement instant detonation on failure for now and throw in the reduce damage on integrity failure later?

Go for instant detonation on failure for now, it's gonna require a whole new maintainer discussion regardless. @VasilisThePikachu suggested something like 5 C4, so probably around that area. Try it out and see how it feels.

**Comment by SaphireLattice** [comment]
So, changed this to go boom at 45 damage. That's *after* 90% explosion damage reduction to the minibomb.

Making it start a countdown from explosion is pretty easy. Point blank chinalake does it just fine. So does point blank C4. Next tile C4 manages to *not* cook it off. CLF3 gets fucking weird and just the 1+3 mix does 7.5 damage to the bomb (so that's 75 to anyone with no explosion resist... fun! new meta discovered, eh?) and 50+150 preheated in a modular grenade or bluespace beaker manage to do about 35+

So the threshold is tuned so that another minibomb will cause instant detonation, as well as nuke (I think...) but just about anything else will not do it without already killing the target *hard*. And you can't really pre-damage it because the 10 damage threshold is not a huge amount to play with.

And it would have been more of a concern at 40 damage threshold cuz 1+3 and then modular grenade with 50+150 CLF3 would have made it go boom, but at 45 it juuuust barely not enough. And to have CLF3 cause bigger explosion, you need a bluespace beaker. At which point it's a bit difficult to balance against CLF3 without making the damn thing indestructible.

**Comment by thebadman4662** [comment]
> Making it start a countdown from explosion is pretty easy. Point blank chinalake does it just fine. So does point blank C4. Next tile C4 manages to not cook it off. CLF3 gets fucking weird and just the 1+3 mix does 7.5 damage to the bomb (so that's 75 to anyone with no explosion resist... fun! new meta discovered, eh?) and 50+150 preheated in a modular grenade or bluespace beaker manage to do about 35+

Here are some of my old IEM/IEMM/other infernal things notes for CLF3 damage if you want to balance around it. Damage being 50 blunt at start for gibbing and 100 split in other for total of 150. Though I do not remember if damage is after 50% chemical nerf or not, most likely not as it seems "a bit" high: 
> 50(150 total) CLF damage = 3 fluorine, 1 chlorine 💥  1tile
75 = 6 + 2 💥  2tile
100 = 12 + 4
125 = 27 + 9 💥 2.5tile
150 = 51 + 17 💥 3 tile
175 = 84 + 28 💥  3.5 tile
200 = 210+70 💥 4 tile

And here are explosion radius increases without damage increase:
> 2.5 💥 7+ chlorine
3 💥 13+
3.5 💥 24+
4 💥 36+

**Comment by SaphireLattice** [comment]
I think I'm happy with threshold of 45 for now, after my own testing with 50/150 CLF3 mix, unless I hear about anything else ^^

**Pull request merged**
