### PR TITLE
debug armor vest

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

resprited captains carapace that has 100% resistances but is not EVA capable
## Why / Balance

there isnt really a reason for or against this, just a sortof fun thing to have

its also a cruelty squad reference
## Media

image
icon

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
no change log

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
well actually i think i forgot a few damage types

**Comment by JoeHammad1844** [comment]
i didnt add cellular damage but what weapon even does cellular? also this wont help you against death nettle acid

**Comment by JoeHammad1844** [comment]
forgot meta.jason

**Comment by JoeHammad1844** [comment]
i forgot a suffix but if you cant tell that its a debug item by the name debug vest you deserve what comes after

**Comment by Veritius** [comment]
this adds absolutely nothing to the game

**Comment by JoeHammad1844** [comment]
yeah i know

**Comment by JoeHammad1844** [comment]
yeah fair

**Pull request closed without merging**
