### PR TITLE
Resolves that make you flinch

### PR DESCRIPTION
**Pull request by PaulRitter**
i got bored so i decided to get rid of some resolves that could be cached

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Sometimes not-caching can be better if the cached thing is rarely used just to save the mem. I'm kinda suss on the prototype one and the wires component (though caching for the draw is significantly better) but it's not like the world is ending so if you're happy we can just merge it.

**Review by Zumorica — CHANGES_REQUESTED** [review]
To avoid silly C# warnings, assign all dependencies to `default!`.

**Comment by PaulRitter** [comment]
> To avoid silly C# warnings, assign all dependencies to `default!`.

done

**Review by Zumorica — APPROVED** [review]

**Review by ShadowCommander — CHANGES_REQUESTED** [review]
It's probably better not to do the cache for the CargoProductPrototype because it already does a cache type thing for the strings they're fetching.

**Comment by PaulRitter** [comment]
> 
> 
> It's probably better not to do the cache for the CargoProductPrototype because it already does a cache type thing for the strings they're fetching.

done, you're right

**Pull request merged**
