### PR TITLE
Grid inventory fixes

### LINKED ISSUE #22156: Grid inventory borg items stuck
Attemping to place a borgs tools inside a grid inventory will "place" the item inside, after a little testing, it appears impossible for anyone to take out the items, you can as the borg, relocate the items inside.

the items update accordingly to those the borg has, as seen below.

https://github.com/space-wizards/space-station-14/assets/94384139/2be5d10d-65db-4242-bfc4-2461ead899f1

Clip showing how a borg can relocate, and place items in grid inventories. 

https://github.com/space-wizards/space-station-14/assets/94384139/f1b4891c-8007-4c11-85a0-c2618d3a07cf

we attempted to use the "transfer contents" option in the verb menu, or whatever it is called, and was unable to transfer the glitched items into another grid inventory.

we were also completly unable to remove the glitched items from the grid inventory, but i suspect you might be able to remove them, by deleting the original item, either with in game means (singulo, cremator, disposal grinder), or admin means, unsure if this might crash a server if attempted.

@EmoGarbage404

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Fixes #22156

The changes:
- tweaked the hover colors to be more colorblind accessible
- added a toggle to make the storage window opaque
- game tries 20% harder to not let the window go off screen 
- Items that fail to be inserted via InsertAt() no longer remain in the StoredItems dict (#22156)
- CanInsert now actually factors in containerSystem event checks
- inserting an entity into a position no longer auto stacks it, which was creating some angry bugs.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: You can now make the storage window opaque with the "enable opaque storage window" toggle in the graphics menu.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i made some giga mistakes so let me fix those first

**Comment by EmoGarbage404** [comment]
ok now it's good

**Comment by IProduceWidgets** [comment]
Smol thing, but how would you feel about rotating the sprite as well when the inventory area rotates? Would make the oddly shaped items look a little better I think.

**Comment by EmoGarbage404** [comment]
> Smol thing, but how would you feel about rotating the sprite as well when the inventory area rotates? Would make the oddly shaped items look a little better I think.

i'd probably add it in a separate PR because it'd need a fair bit of yaml work

**Pull request merged**
