### PR TITLE
twek(BoxStation): Reorganize atmos TEG room to be more user friendly.

### LINKED ISSUE #30364: Box station TEG is designed to troll players
### The Box Station TEG is designed to troll (especially new) players due to:

1. Burnbox is tiled in floorthat when crowbared turn into in individual steel rods that are very hard to pick up without replacing the floor, and you can often accidentally click on them if you don't pick them up as they leave diagonal jail bars. Additionally this floor hides the pipes to anyone not using a T-Ray, and obscures the fact that the burnbox radiator does absolutely nothing. This is FRUSTRATING.

2. The burnbox radiator does nothing. Nothing at all. Radiators require flow in order to do the temp delta, so a radiator on a random pipe loop doesn't do anything. If you have no experience with radiators you will get very frustrated why the way the game shows you to use them doesn't work.

3. The external cooling loop also does nothing! Did radiators used to work on still gas? This is a trap for new players as they will assume they can just slap radiators on and they will work. They will get frustrated because the game lied to them about how a mechanic functions.

4. Time to setup a functional TEG is extended significantly due to the scutt work of having to crowbar up floor, collect all the tiny rods one by one, unwrench all the bad pipes, weld them all down to bare steel, ghostplace and build your real setup, realize you need more steel and run out and look for it while the whole station yells at engineering for not making power etc. etc. Obviously frustrating.

5. There is a one-click grief valve for your atmosyndie/shitter to open and equalize the hot and cold sides if you don't remove, which is HILARIOUS and therefore should NOT be changed, no cap.

**Reproduction**

1. Go to Box station as an atmos/engi
2. Set up the TEG under time pressure, don't worry the whole station is counting on you
3. Drag the welding fuel in from engilounge just so you can finish welding your hoard of pipes.
4. Realize that it is, indeed, frustrating for literally no reason

**Screenshots**
image
Why

**Additional context**
Honestly this wasn't as troublesome before the AME nerf, but now it's more important to have secondary power running, and important to have it faster. Because of this, the pain of this setup is really obvious and honestly needs rework.

If suggestions are welcome, I would like to present an alternative bare setup that encourages rather than trolls the players:

image

I would be happy to update map with permission from the map-master.

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Reorganized the TEG room

## Why / Balance

Resolves #30364

## Technical details

Please tell me how to fix this and I will.

The changes I made are not 100% the exact same as those suggested in the issue.
The things that are different are:

- Some tiling in burn room are not the same
- The piping in the middle are not the same color

The reasoning they are not the same

- Couldn't find the tiling in the spawn menu
- Didn't know the hexcode for the green pipes because it wasn't on the mapping general guide

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot from 2024-07-25 23-12-08

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deepdarkdepths** [comment]
Why are like 5 maps modified instead of just Box.

**Comment by Brandon-Huu** [comment]
> Why are like 5 maps modified instead of just Box.

Only one map was modified, the box is being a little silly

**Comment by Brandon-Huu** [comment]
:noooo: Forgot to add [RadioAndrea](https://github.com/RadioAndrea) as coauthor. 

Also, we need a better mapping guide with a list of all the pipe colors.

**Comment by RadioAndrea** [comment]
@Brandon-Huu You are my personal hero

**Pull request merged**
