### PR TITLE
More tiles + removing corners from previous ones + fixes (conflict fixed, new problems)

### PR DESCRIPTION
**Pull request by UnderscoreX5**
Starting to add more tiles, will keep updated on the progress.

v0

image

v0.1

image
(removed the ultra bright white checkered floor, added 2 floors and fixed colors on the purple one)

v0.3 (removed corners from previous textures, fixed some textures and added a bunch of new ones)

image
image
image
(yellow-black and yellow-white squared floors are now the same layout, just like in the first pic, other 2 pics are older)

v0.4

image
image

v0.5 (added common checkered floors + renamed the "kitchen one" to a more generic name like the others)

image

### CODE REVIEW

**Comment by moonheart08** [comment]
Happy mapper approved 👍 
However I will note the glass tiles probably should be kept on TODO until actual transparency, and the ability to show subfloors through them, exists.

**Comment by UnderscoreX5** [comment]
> Happy mapper approved 👍
> However I will note the glass tiles probably should be kept on TODO until actual transparency, and the ability to show subfloors through them, exists.

Yeah right, probably would be better if they were 2 divided, gonna remove it temporarely. Thanks for feedback!

**Comment by moonheart08** [comment]
> > Happy mapper approved 👍
> > However I will note the glass tiles probably should be kept on TODO until actual transparency, and the ability to show subfloors through them, exists.
> 
> Yeah right, probably would be better if they were 2 divided, gonna remove it temporarely. Thanks for feedback!

Could probably implement them the same way catwalks are, temporarily. Not sure if there's a way to make them prevent venting tho, so that may not work.

**Comment by UnderscoreX5** [comment]
> > > Happy mapper approved 👍
> > > However I will note the glass tiles probably should be kept on TODO until actual transparency, and the ability to show subfloors through them, exists.
> > 
> > 
> > Yeah right, probably would be better if they were 2 divided, gonna remove it temporarely. Thanks for feedback!
> 
> Could probably implement them the same way catwalks are, temporarily. Not sure if there's a way to make them prevent venting tho, so that may not work.

yeah better waiting for new tech, since they would be useless.

**Comment by UnderscoreX5** [comment]
Moving this to another pull request since gitkraken messed this one badly and i am reorganizing it without ui.

**Pull request closed without merging**
