### PR TITLE
Space about 30% faster, spacing fights fires better

### PR DESCRIPTION
**Pull request by tom-leys**
## About the PR
- 30% faster spacing overall
- 60->40s to clear plasma bombed dev (one plasma canister, full burn, space to 7kPa)
- Faster space cooling for very hot rooms.

Players have been complaining that the new spacing is too slow. This is probably STILL too slow for many but it's a tradeoff for kindness vs speed.

**Media**

I don't think this needs media.
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Space has become 30% more hungry for our precious atmosphere. Keep those airlocks closed people!

### CODE REVIEW

**Comment by deltanedas** [comment]
im still of the opinion that spacing should go back to being ~instant, with this functionality only being in firelocks (which would also make them more than just an incredibly annoying airlock)

**Comment by tom-leys** [comment]
> im still of the opinion that spacing should go back to being ~instant, with this functionality only being in firelocks (which would also make them more than just an incredibly annoying airlock)

Instant spacing is not realistic, but I am sensitive to what you said in the other PR about venting from wrecks while salvaging. I don't like the idea of firelocks magically interacting with atmos beyond closing as it vents.

**Comment by deltanedas** [comment]
by instant i mean everything being dragged out to the spacing in 3-5 seconds

**Comment by tom-leys** [comment]
> by instant i mean everything being dragged out to the spacing in 3-5 seconds

I think we need a consensus on this. Those on Discord liked a slow depressurize to make space easier for underequipped players. Expert players who can handle spacing would prefer speed.

**Comment by metalgearsloth** [comment]
If we want slow spacing shouldn't we just turn the zas side off.

**Comment by Zumorica** [comment]
> If we want slow spacing shouldn't we just turn the zas side off.

yes, that would have been the proper way to do it

**Comment by metalgearsloth** [comment]
I looked back on the original discussion https://discord.com/channels/310555209753690112/770682801607278632/1108277031600398387 @tom-leys what were your results with monstermos equalization turned off.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
I didn't really look at the first PR but this seems to invalidate the ZAS cvars entirely so we should really start with turning those off and going from there.

**Comment by tom-leys** [comment]
> I looked back on the original discussion https://discord.com/channels/310555209753690112/770682801607278632/1108277031600398387 @tom-leys what were your results with monstermos depressurization turned off.

Well, by definition wouldn't that be far slower? This code is adding additional depressurization on top of the normal atmospheric equalization system.

Also, note that the original PR was to slow down `MonstermosDepressurization`. I think we need a magic depressurize that accelerates the process from the standard equalisation system - the wind is just too high for a grid based equalization method to be fast enough.

**Comment by metalgearsloth** [comment]
> > I looked back on the original discussion [discord.com/channels/310555209753690112/770682801607278632/1108277031600398387](https://discord.com/channels/310555209753690112/770682801607278632/1108277031600398387) @tom-leys what were your results with monstermos depressurization turned off.
> 
> Well, by definition wouldn't that be far slower? This code is adding additional depressurization on top of the normal atmospheric equalization system.
> 
> Also, note that the original PR was to slow down `MonstermosDepressurization`. I think we need a magic depressurize that accelerates the process from the standard equalisation system - the wind is just too high for a grid based equalization method to be fast enough.
> 
> So the origional PR made `MonstermosDepressurization` take only about 5% of the air per tick rather than 100%. This PR increases that portion to 7% and adds a few more tweaks.

In 13 there's 3 atmos systems, ZAS, LINDA, and monstermos.

ZAS is zone-based though I don't recall which servers use it.
LINDA is tile-based.
monstermos is LINDA but with zone pressurisation and if you toggle the depressurization / equalization cvars you just get pure LINDA.

Now that depressurisation isn't zone-based leaving the zone-based cvar on makes it pointless so we should turn it off and adjust the updates from there as necessary.

**Comment by tom-leys** [comment]
I'm not sure what to do now with this PR. I thought it was a relatively simple change to tune the depressurization but it seems to have turned into an atmos system discussion that's currently beyond my knowledge. I might be able to deep-dive this if it's useful after getting a few other things off my plate.

I thought that magically subtracting air into space (which is what `ExplosiveDepressurize` still does) is always going to be better than expecting a grid-based system to stabilize over time.

**Comment by metalgearsloth** [comment]
> I'm not sure what to do now with this PR. I thought it was a relatively simple change to tune the depressurization but it seems to have turned into an atmos system discussion that's currently beyond my knowledge. I might be able to deep-dive this if it's useful after getting a few other things off my plate.

We need cvars around depressurization and zas zones need to be reinserted rather than just bypassing it with code changes, same with the original PR.

> Generally just stabilizing into space is going to be far too slow in terms of ticks to space an area.

delta and tstalker complained current spacing taking too long to be practical in-game so idk, at either rate the cvar changes need to happen.

**Comment by keronshb** [comment]
> delta and tstalker complained current spacing taking too long to be practical in-game so idk, at either rate the cvar changes need to happen.

I'll need to do some testing because if spacing is too fast it feels cheap.

**Comment by tom-leys** [comment]
Feel free to reuse my code if you want to contribute with it yourself.

**Pull request closed without merging**
