### PR TITLE
Fix SpawnEntitiesBehavior crash and add test

### LINKED ISSUE #2827: !type:SpawnEntitiesBehavior throws an exception.
Replicate.
Spawn, spawn grenade, detonate it on the ground.

Or, shoot anything.

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Fixes #2827

### CODE REVIEW

**Review by metalgearsloth — APPROVED** [review]

**Review by chairbender — CHANGES_REQUESTED** [review]
This approach seems to just shift the problem into a different place while introducing more complexity and possible confusion. Previously, the behaviors would be called in the order they were listed in the yaml, which is quite straightforward. But now, they will be reordered ONLY according to DeletesEntity, i.e. there is no guarantee what the order will be if 2 behaviors don't delete the entity. So if someone wants the behaviors called in a specific order they can't really do that. This could be quite confusing for someone defining the threshold behaviors. At the very least if you are going to sort on DeletesEntity, you should use the existing order as a secondary sort.

Also, it adds an unknown unknown. Now a dev implementing the behavior must magically know they need to implement DeletesEntity if their Trigger implementation deletes the entity, and the ONLY effect it has is on the order in which the behaviors are resolved. Because DeletesEntity has a default implementation there is no cue to the dev to decide if they need to implement that. They might just forget.

Why not just use the order in which the Behaviors were listed, and fix the order there in the prototype definitions? It seems to me like putting a behavior that deletes the entity before one which doesn't is the real mistake here. 

This solution does prevent someone from accidentally putting things in the wrong order, but it just shifts the potential for mistake into the implementation of the behavior as well as preventing the person defining the threshold from being able to explicitly set the order (despite it being a list, which kind of implies they should be called in that order). So it hasn't really fixed the usability problem, just shifted it around while introducing more sources of confusion.

**Comment by metalgearsloth** [comment]
> Why not just use the order in which the Behaviors were listed, and fix the order there in the prototype definitions? It seems to me like putting a behavior that deletes the entity before one which doesn't is the real mistake here.

IMO everything should be order-agnostic regardless

**Comment by chairbender** [comment]
> > Why not just use the order in which the Behaviors were listed, and fix the order there in the prototype definitions? It seems to me like putting a behavior that deletes the entity before one which doesn't is the real mistake here.
> 
> IMO everything should be order-agnostic regardless

I guess it would make things complicated if there were behaviors which depended on a particular order, and deleting does seem like a special case.

But if deleting an entity is a special case, why not just have a flag like "deleteEntity" that deletes the entity after all the behaviors run, if set to true? That logic would be done outside of the behaviors.

**Comment by DrSmugleaf** [comment]
> > > Why not just use the order in which the Behaviors were listed, and fix the order there in the prototype definitions? It seems to me like putting a behavior that deletes the entity before one which doesn't is the real mistake here.
> > 
> > 
> > IMO everything should be order-agnostic regardless
> 
> I guess it would make things complicated if there were behaviors which depended on a particular order, and deleting does seem like a special case.
> 
> But if deleting an entity is a special case, why not just have a flag like "deleteEntity" that deletes the entity after all the behaviors run, if set to true? That logic would be done outside of the behaviors.

If some side effect of a behavior causes an entity deletion it would still error in that case. I agree that the solution isn't ideal though.

**Comment by Zumorica** [comment]
Btw in construction, behaviors/actions aren't order-agnostic. If an action deletes the entity, the actions after that one aren't ran.

**Comment by DrSmugleaf** [comment]
Superseded by https://github.com/space-wizards/space-station-14/pull/2892

**Pull request closed without merging**
