### PR TITLE
APC Resprite

### PR DESCRIPTION
**Pull request by ps3moira**
## About the PR

Made a new APC sprite.
## Why / Balance

The old one was over stylized, the current one being used doesn't fit the look for the rest of the machines, clashes with most walls and doesn't look like it's apart of the wall but more like it's been slapped on top. This sprite I made was based off of the old one we used to use but remade and colored to fit the rest of the stations electronic equipment.

## Media
APC sprite I made
image
Old APC
Screenshot 2024-06-20 094646
Current APC
Screenshot 2024-06-20 094704

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl:
- add: Added new APC sprites

### CODE REVIEW

**Comment by B1essedknight** [comment]
Wasn't one of the points over the APC resprite to bring all power grid items in line with one another so that one could easily discern the purpose of the machine from a glance?

**Comment by ps3moira** [comment]
> Wasn't one of the points over the APC resprite to bring all power grid items in line with one another so that one could easily discern the purpose of the machine from a glance?

Nope.

**Comment by Thurtik** [comment]
I'm still mourning the old sprites, but i'll take this design over the current one any day (it would also be cool if the substations got a similar resprite aswell, the current white and bulky one sticks out like a sore thumb and doesn't look very nice on it's own either imo)

**Comment by B1essedknight** [comment]
> Yes but I feel as though babyifying all power grid items to look white and be the same sacrifices the overall look of the game and clashes more than it makes it look like it's apart of the wall.

In my personal opinion, I agree with you. 

It would be nice for all of the power equipment to have a similar style so that the original reason the resprite occurred doesn't happen again. That was the main reason for my first comment but I wish you good luck on this PR.

**Comment by ps3moira** [comment]
> > Yes but I feel as though babyifying all power grid items to look white and be the same sacrifices the overall look of the game and clashes more than it makes it look like it's apart of the wall.
> 
> 
> 
> In my personal opinion, I agree with you. 
> 
> 
> 
> It would be nice for all of the power equipment to have a similar style so that the original reason the resprite occurred doesn't happen again. That was the main reason for my first comment but I wish you good luck on this PR. 
> 
> 
> 
> 

I plan to do attempt a resprite tweak for the substation to land on a more consistent overall design if this PR goes through.

**Comment by MACMAN2003** [comment]
can you rotate the apcs so they point away from the wall, like how they were before the resprite?

**Comment by ps3moira** [comment]
> can you rotate the apcs so they point away from the wall, like how they were before the resprite?

Yeah it does that. I've taken the improvements of the current APC sprite and used it as a base for my sprite. So all the benefits are kept

**Comment by Merrokitsune** [comment]
Pretty much better in every way. Even better, considering the directionality.

**Comment by Plykiya** [comment]
reminder to bully art directors

**Review by Plykiya — CHANGES_REQUESTED** [review]
Feedback from art directors is that they don't really like the old screens/old APCs, and that they'd just prefer if the current APC sprites just had a less dark outline.

**Comment by ps3moira** [comment]
> Feedback from art directors is that they don't really like the style of the old screens/old APCs, and that they'd just prefer if the current APC sprites just had a less dark outline around the screen...

Ah nevermind then. I made this because I didn't like the current one but if they have a different vision of what it should be then that's fine.

**Comment by ps3moira** [comment]
Any downstream who liked this PR/Sprite are free to use it if they wish.

**Pull request closed without merging**
