### PR TITLE
Add door electronics access configuration menu (part 2)

### PR DESCRIPTION
**Pull request by c4llv07e**
## About the PR

I could not open the previous PR (#17778 ), so here is a new one.
It's working now. I guess it's ready to be merged.

## Media

https://github.com/space-wizards/space-station-14/assets/38111072/cb9f5e70-02f9-420f-ae78-671e154c3b7f

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: c4llv07e
- add: NT has declassified the documentation for door electronics, now anyone can configure its access using network configurator or multitool!

### CODE REVIEW

**Review by 778b — COMMENTED** [review]
~~imho, but i think u must use proto of airlock electronics in deconstruction graph, cuz now its just silently spawn in ur hand or near u without any default sound, its not a default logic of deconstruction. In this way will be 1 trouble which will cause its reset airlock electronics, i think its not a problem, but imho
In ss13 we had resetting airlock electronics by every deconstruction~~
I think if u resolve problem with not default spawning of airlock electronics its will be best way of implementing mechanic

**Comment by c4llv07e** [comment]
I do not know, it sounds more logical to me that the electronics taken from the door have the configuration of this door.

>its not a default logic of deconstruction
Does it? I thought this was the logic of container deconstruction.

**Comment by chromiumboy** [comment]
How does this interact with the access configurator?

**Comment by c4llv07e** [comment]
My bad, it isn't working right now. I'll fix it.

**Comment by c4llv07e** [comment]
Done, now it's working

**Comment by c4llv07e** [comment]
I think it's ready to merge.

**Comment by metalgearsloth** [comment]
We really need to re-open the old PR so reviews are intact but you also did this from your master which blocks it.

**Pull request closed without merging**
