### PR TITLE
Puddle Visuals: ECS/Refactor and fixes

### LINKED ISSUE #6526: Vomit shouldn't have puddle visualizer
Or at least puddle visualizer has to be updated to not just force the sprite to some hard coded value. Currently it just tries to override the vomit visuals and will error.

```
[ERRO] go.comp.sprite: State 'smear-0' does not exist in set RSI. Trace:
   at System.Environment.get_StackTrace()
   at Robust.Client.GameObjects.SpriteComponent.Layer.SetRsi(RSI rsi) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 1852
   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, RSI rsi) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 918
   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, ResourcePath rsiPath) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 950   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, String rsiPath) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 935
   at Content.Client.Fluids.PuddleVisualizer.UpdateVisual(AppearanceComponent component, SpriteComponent spriteComponent, Single cappedScale, Boolean forceWetFloorSprite) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\Content.Client\Fluids\PuddleVisualizer.cs:line 75
   at Content.Client.Fluids.PuddleVisualizer.OnChangeData(AppearanceComponent component) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\Content.Client\Fluids\PuddleVisualizer.cs:line 5
```

### LINKED ISSUE #9049: Sparkle animation broke at some point
## Description

**Reproduction**

1) Wet mop
2) Mop floor
3) Edit solutions the puddle to be like 3u, or just wait

**Screenshots**
image

**Additional context**

### LINKED ISSUE #11823: Tomato puddles turn white and then become static sparkles
## Description

Tomato puddles are currently jank - will change visuals dramatically as they evaporate.

**Reproduction**

- Throw a tomato on the ground
- Watch as the splat puddle changes to white and then to static sparkle

**Screenshots**

https://user-images.githubusercontent.com/97707302/194954812-aff186f4-5f54-4c29-8c9d-19d7c49cd15f.mp4

**Additional context**

Some of my earlier shitcode is almost certainly to blame. I tried making puddle visuals robuster in #6848 and will do so again. The problem is probably not limited to just tomatoes.

### PR DESCRIPTION
**Pull request by Willhelm53**
## About the PR 

This PR removes `PuddleVisualizer` in favor of `PuddleVisualizerSystem` and `PuddleVisualizerComponent` (all Client-side). Generally makes my code for wet floor sparkle effects less janky. They will now only trigger the sparkle for puddles below a certain volume (WFET = Wet Floor Effect Threshold) that are evaporating. Note that very slow evaporation (such as what currently exists for blood puddles) still counts as evaporation for this purpose.

image

This PR also fixes bugs where tomato and vomit splats would lose their color or their sprite. Additionally, it fixes a bug where the sparkle animation broke and only a static image of it would display.

Fixes #9049
Fixes #11823 
Fixes #6526 (arguably this was fixed by others earlier though)

**Screenshots**

https://user-images.githubusercontent.com/97707302/196008843-c17608dd-e038-45cb-b801-15d53f1fac26.mp4

**Changelog**

:cl:
- fix: Fixed tomato and vomit splats losing their color/sprite.
- fix: Fixed wet floor sparkles getting stuck on one animation frame.
- tweak: Wet floor sparkles are now slightly more opaque and stay invisible for less of their animation cycle.

### CODE REVIEW

**Comment by Willhelm53** [comment]
This PR also replaces my old one, #6848

**Comment by Willhelm53** [comment]
No more Marge Conflict 
image

**Comment by Willhelm53** [comment]
Seeking help on the ubuntu checks failing! This is the same thing that killed my momentum on previous PR months ago 😩

**Comment by mirrorcult** [comment]
image
image

these are the errors

**Comment by Willhelm53** [comment]
Checks passed but somehow it was just by commenting out the logger warning... 
image
This solution obviously sucks so I'm going to tweak a little more based on #8203 which I just noticed.

**Comment by Willhelm53** [comment]
All good now and ready for prelim review. To be clear - the logger warning for missing sprites is still intact and not causing problems. For some reason, the logger warning I added for my own system's `PuddleVisuals` data transfer (e.g. `volumeScale`, `solutionColor`) was causing exceptions to be thrown in the tester. This was true whether `logger.warning` or `logger.debug` was used.

Since it's for my own system's new data transfer, I'm fine with not having that logger warning. So I just removed it. I suspect this is the same thing causing me problems way back in #6848, because at the time I had bundled my `PuddleVisuals` data checks within the existing logger warning for missing sprites.

Seeking feedback now, because the only other thing I plan to add for this PR is a check similar to what I've done for `isEvaporating` but for `isSlippery`: Evaluate the state within Server puddle system, and transfer to Client puddle system for use in determining wet floor sparkle effects.

**Comment by Willhelm53** [comment]
Out of draft, and updated PR description! ✨

**Comment by Willhelm53** [comment]
Somewhat related to the currently-open #11908 but we change different areas. Should be relatively easy to resolve any merge conflicts between the two.

**Comment by Willhelm53** [comment]
After polling in the discord, I'm going to revert my latest commit which made sparkles depend on slippery. Will update that later today along with the PR description.

**Comment by Ygg01** [comment]
It seems my changes broke this.

**Comment by Willhelm53** [comment]
All good @Ygg01 - I was expecting your changes in #11908 to cause some merge conflicts. Just haven't been able to get into fixing them until now. I'm gonna test this PR some more on local to make sure it's all smoothed out, then this one should be ready for review.

**Comment by Willhelm53** [comment]
Marked as draft because something broke the "sparkle animation freezes on a single frame" bug again. I had previously fixed this with a `sprite.LayerSetAutoAnimated(0, true);` and now I intend to go over it again with a fine-toothed comb.

**Comment by Willhelm53** [comment]
Ready for review.

**Review by DrSmugleaf — APPROVED** [review]

**Comment by Willhelm53** [comment]
One thing I still wanna do is incorporate @ElectroJr's comment (via Discord) about making the sparkles rsi into a spritespecifier on the component (currently it's just hardcoded in the system which I agree is a bit jank).

Please hold off on merging until I make this small change. And I'd welcome additional review because (for me at least) this was a pretty substantial refactor 😄

**Comment by Willhelm53** [comment]
oh and now that [this one](https://github.com/space-wizards/RobustToolbox/pull/3574) is merged there's another thing I can try to make cleaner (previously had to flip AutoAnimated off and back on again).

**Comment by Jackrost** [comment]
I wonder, can this PR help to make puddle more look like a puddle and not like splats - when visual for all liquids on floor connected into one and depends on reagent amount ?

**Comment by AJCM-git** [comment]
> I wonder, can this PR help to make puddle more look like a puddle and not like splats - when visually all liquids on floor connected into one big puddle and can change depends on reagent amount ?

Will it make it easier to implement? yes, because not dealing with old code is helpful
does this change puddles visually? no, its just code cleanup

**Comment by Jackrost** [comment]
> Will it make it easier to implement? yes, because not dealing with old code is helpful does this change puddles visually? no, its just code cleanup

For future implementation of course

**Pull request merged**
