### PR TITLE
Add pirates as an UnknownShuttleEvent

### PR DESCRIPTION
**Pull request by DuckManZach**
## About the PR

Pirates were added as one of the potential spawns in the unknown shuttle event.

## Why / Balance

Pirates would be an interesting antagonist for the station to deal with. Additionally the UnknownShuttleEvent provides an opportunity to integrate them into the roundflow seamlessly. 
Adding this will likely make crew-members lives a bit harder, but I would anticipate them to be a minor antagonist a majority of the time. In addition, the non-lethal nature of their objective (to loot) will likely prevent them from becoming a station-level threat.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
The pirates and their ship

image
image
The pirate ghost roles

image
Ghost rules popup
## Breaking changes

**Changelog**

- add: Pirates can now appear via random event. YAAARG!!!

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
This should be a proper antagdef so it can be managed properly.

**Comment by Kadeo64** [comment]
9 PIRATES??
that's literally mini nukies

**Comment by DuckManZach** [comment]
Let me know if additional things need to be done for the antagdef.

**Comment by Djungelskog2** [comment]
I think this would be a fun addition if there were a gamemode similar to dynamic from 13 where antagonists are assigned values and chosen randomly, however in the current state I could see it being chosen as a random event from the round start which then happens later and also prevents other events happening ~10 mins before or after the pirate event actually happens

Although for being a midround enveloped with another gamemode they seems to be really powerful, making crews lives harder is a massive understatement

1: either wait till some dynamic gamemode stuff comes along or
2: nerf them immensely, if the clowns are already a handful while only being 3 non-antags I can only imagine how bad they'd be, maybe 1-2 on a small shuttle?

**Comment by ARMOKS** [comment]
> 9 PIRATES??
> that's literally mini nukies

Their armor and weapons are not good or anywhere near nukies. This is like having 9 reinforcements with scraps and evas

**Review by keronshb — CHANGES_REQUESTED** [review]
Why are there 9 pirate spawners? 3 cause enough havoc on SS13 servers.

**Comment by Boaz1111** [comment]
do they get the cannon?

**Comment by slarticodefast** [comment]
Are you still working on this?

**Comment by slarticodefast** [comment]
If you come back to this, leave a comment and I will re-open the PR.

**Pull request closed without merging**
