### PR TITLE
Nerf mothroaches slightly + make them not able to pull

### PR DESCRIPTION
**Pull request by EEASAS**
## About the PR
Mothroach nerfed because they are annoying

## Why / Balance
Mothroaches are annoying. They can spam chitter and drag things out of tables.

## Technical details
Nerfs their HP and speed(slightly)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**

:cl:
- tweak: Mothroaches have been vaccinated to be weaker and slower. Also, they are more valuable!
- tweak: Mothroaches and rats cannot pull items anymore.

### CODE REVIEW

**Comment by EEASAS** [comment]
fuck i forgot to change the title

**Comment by LankLTE** [comment]
Pretty sure they currently move the same speed as most other simple mobs. I think you should give a better reason for almost halving their speed than “they are annoying”.

**Comment by deltanedas** [comment]
> drag things out of tables.

if they have puller remove it that seems broken

**Comment by EEASAS** [comment]
they dont have puller from what i seen

**Comment by deltanedas** [comment]
then how can they pull things

only broken interaction i am aware of is being able to open a gas canister valve

**Comment by EEASAS** [comment]
i don't know how they pull things but they just do

**Comment by EEASAS** [comment]
> Pretty sure they currently move the same speed as most other simple mobs. I think you should give a better reason for almost halving their speed than “they are annoying”.

they run pretty fast, you cannot chase them, i think they're even the same speed as a human

**Comment by deltanedas** [comment]
why would you need to chase a squeaky hat

**Comment by Aisu9** [comment]
So... instead of FIXING the issue of dragging and interacting, you destroy their stat block?
nerfing their speed and HP into the ground? is that how you FIXE problematic and unintended feature?

**Comment by Aisu9** [comment]
they are at the same seat of mouses, yeah they can "spam" chitterings by talking just like mouse

**Comment by deltanedas** [comment]
remove puller

**Comment by EEASAS** [comment]
> So... instead of FIXING the issue of dragging and interacting, you destroy their stat block? nerfing their speed and HP into the ground? is that how you FIXE problematic and unintended feature?

im gonna try to find why they pull and stuff and then revert the stats

**Comment by EEASAS** [comment]
> 
> 
> remove puller from simplemob also wtf mice can pull things why

is it fine if i set it to respirator

**Comment by deltanedas** [comment]
what

either:
- remove puller from simplemob
- add `- type: Puller needsHands: true` to cockroach

**Comment by EEASAS** [comment]
how do i remove puller thoughfd g dfhdfgh

**Comment by EEASAS** [comment]
image
nevermind

**Pull request merged**
