### PR TITLE
Increase Nuclear Operative playtime requirements

### PR DESCRIPTION
**Pull request by CMDR-Piboy314**
### Significantly increased the playtime requirements for nuclear operatives. 
Check out round 38253 if you want to see _a_ great example of why this should happen (**tldw**, my fellow nukies did not know how to turn on internals, one person microbombed themselves, and the commander somehow did not know how to use harm mode and took off their helmet in space when I explained what wielding an axe is in LOOC chat... oh and the reinforcement used an explosive grenade on me)

## Why / Balance

This will hopefully decrease the level of newkies blowing themselves up and taking 1 hour to arrive at station only to realise they don't know what a helmet is.

The following are the actual changes:

## Regular Nuclear Operative:
- Increased overall playtime from 5 hours to 20.
- Added a 5 hour Security requirement.

## Nuclear Operative Agent:
- Increased overall playtime from 5 hours to 30.
- Increased medical playtime from 5 hours to 10.
- Added a 5 hour Security requirement.

## Nuclear Operative Commander:
- Increased overall playtime from 5 hours to 40. This is on par with the Head Of Security's overall time requirement.
- Increased Security playtime from 5 hours to 30. This is also on par with HoS.

## Technical details

None

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Syndicate has become more selective with Nuclear Operative recruitment.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
We already rejected similar time requirements in the initial proposal of #20109, so I think this is unlikely to be merged. I'll leave this up for more maint opinions.

**Comment by CMDR-Piboy314** [comment]
Just to give people a good point of reference - 5 hours of sec on a regular operative and agent... that's **less than the amount you need to be just a Security Officer** (I would increase this to be the same realising that, but knowing the direction of the push back people have I'll leave it alone). The overall time requirement of 20 hours on operative is, if you somehow played exactly 10 hours in any job, and 10 hours as a cadet how long it would take you to unlock Security Officer. Also, **the requirements for Commander are actually more lax than HoS** as HoS has other requirements that I didn't add for simplicity's sake, Warden and 10h specifically Security _Officer_ playtime.

I want to stress that **these requirements really aren't all that strict.** The point of this is so that people know basic combat and antags, and **I don't think this PR even really makes people 'learn Nuclear Operatives later' because realistically they're just going to be confused if they don't know a lot of game mechanics before they are one**. I would hope a nukie would have been a Syndicate Agent at least once or twice, this is why there is simply a 20 hour overall requirement and 5 hour sec requirement, just to make it so that they've probably been a traitor once or twice, know how harm mode, uplinks, maybe even to know how gun bolting and externals work.

**Comment by HoidC** [comment]
> I doubt this will fix anything. If you want people to get good at nuclear operatives let them play nuclear operatives.
> 
> I have ~90 hours logged in the game and would probably make all of those same mistakes because I've only been on nuke ops once and during that time my entire team killed themselves for whatever reason.

90 hours and you can’t toggle hardsuit internals, helmets, use harm mode or click an axe in hand? Damn..

**Comment by LankLTE** [comment]
Should this be merged, I think specific department playtime should be removed as you’re fully capable of getting knowledge without it. The 5 hours of Security could maybe stay, but 30 hours of security to play commander is honestly a little absurd and I don’t see how that’s relevant in the slightest.

**Comment by metalgearsloth** [comment]
It shouldn't take 20 hours to get to a fun role or 5 hours in a department you may not necessarily enjoy.

**Comment by CMDR-Piboy314** [comment]
20 hours is less than you need to be a secoff. You should know basic game mechanics before being a nukie. Not understanding what the heck is going on and dying because what is internals? Is probably not fun.

**Comment by UbaserB** [comment]
From how much people understand within 20 hours of gameplay, its not much. I teach a lot of my friends and they know very little.. it really should be increased tbh

**Review by PJB3005 — CHANGES_REQUESTED** [review]
I don't even have an opinion on the change itself but:

> tweak: The Syndicate has become more selective with Nuclear Operative recruitment.

Cut the stupid roleplay changelog out.

**Comment by metalgearsloth** [comment]
Maints talked about it, no need to timegate fun so hard.

**Comment by lzk228** [comment]
what about great #7809 ?

**Comment by CMDR-Piboy314** [comment]
guys no need to timegate fun so hard on command roles

**Pull request closed without merging**
