### PR TITLE
Resizable Changelog

### LINKED ISSUE #18798: Lobby changelog window cannot be resized
## Description

Changelog window should be able to be resized.

### PR DESCRIPTION
**Pull request by LerTheGrand**
## About the PR
The changelog is now resizable. 

This PR was heavily based off of PR: #19272 that was aiming to fix the same issue but attempts to implement the changes @metalgearsloth suggested.

## Why / Balance
Resolves #18798

## Technical details
Set the `MinSize` attribute on the ChangeLog class and change the `GetDragModeFor()` method to allow resizing of the changelog window.

## Media

<details>
    <summary>Before</summary>
    BeforeImage
</details>

<details>
    <summary>After</summary>
    After Image
</details>

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- tweak: Made changelog window resizable.

### CODE REVIEW

**Comment by PixelTheKermit** [comment]
> This PR was heavily based off of PR: 19272

Don't think your embed works.

**Comment by LerTheGrand** [comment]
> > This PR was heavily based off of PR: 19272
> 
> Don't think your embed works.

Embarrassing. I fixed that. Good catch.

**Comment by PJB3005** [comment]
Tip: you can embed links to issues/PRs by just putting their number, like so: #19272.

**Comment by PixelTheKermit** [comment]
additionally, to add onto what PJB said, you can add "Resolves #issuenumber" to automatically close that issue once the PR gets merged.

**Comment by LerTheGrand** [comment]
Thanks for the wise words. I've thrown all of the suggestions into the description for this PR.

**Comment by CaptainSqrBeard** [comment]
🤔 
image

**Comment by LerTheGrand** [comment]
> 🤔 image

I can't seem to reproduce that. Do you have more details about it? Are you running on ubuntu or something?

**Comment by CaptainSqrBeard** [comment]
> > 🤔 image
> 
> I can't seem to reproduce that. Do you have more details about it? Are you running on ubuntu or something?

It was on screenshot in PR description. I actually don't know when was screenshot made so maybe it's outdated

**Comment by LerTheGrand** [comment]
LOL. That's embarrassing. Let me try harder to recreate it

**Comment by LerTheGrand** [comment]
Actually, never mind. Looks like 4310V343k came back to his original PR. I'm going to close this one. Look at #19559 for this fix.

**Pull request closed without merging**
