### PR TITLE
Sadness Chemical

### PR DESCRIPTION
**Pull request by DieselMohawk**
## About the PR
 Adds Sadness to the game. Obtainable by mixing Happiness and Copper.

## Why / Balance
 For a new plant and new mutation by a friend

## Technical details
 I think the guidebook is automatic?

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by DieselMohawk** [comment]
Note: This is a draft since I have no fucking clue if it auto-adds to the guidebook AND the rest of the project isn't ready for launch

**Comment by slarticodefast** [comment]
The guidebook entry is automatically generated for each reagent if the prototype has no errors, so you should be able to see it in-game. You are missing the loc strings for the reagent name and description at the moment, they should be added to the corresponding ftl file.

**Comment by slarticodefast** [comment]
If you want to add the reagent to the game without waiting on a plant mutation you could add a chemical reaction for it or add it to the liquid anomaly.

**Comment by DieselMohawk** [comment]
> The guidebook entry is automatically generated for each reagent if the prototype has no errors, so you should be able to see it in-game. You are missing the loc strings for the reagent name and description at the moment, they should be added to the corresponding ftl file.

Whoops, I'll do that right quick

**Comment by DieselMohawk** [comment]
> If you want to add the reagent to the game without waiting on a plant mutation you could add a chemical reaction for it or add it to the liquid anomaly.

Fair, I could make it Happiness + Ethanol or some shit

**Comment by DieselMohawk** [comment]
> > If you want to add the reagent to the game without waiting on a plant mutation you could add a chemical reaction for it or add it to the liquid anomaly.
> 
> Fair, I could make it Happiness + Ethanol or some shit

I cannot find the Liquid Anomaly Chemical Table

**Comment by DieselMohawk** [comment]
I believe this works, time to ask the checks

**Comment by DieselMohawk** [comment]
I don't understand but I'll read up on it and come back later

**Comment by slarticodefast** [comment]
Did you make any webedits or did you use an IDE and git? You seem to have used the wrong new line settings, which should not happen if your git client is configured correctly.

**Comment by DieselMohawk** [comment]
> Did you make any webedits or did you use an IDE and git? You seem to have used the wrong new line settings, which should not happen if your git client is configured correctly.

I did webedits exclusively, I thought it would be easy and quick.

**Comment by dvir001** [comment]
> > Did you make any webedits or did you use an IDE and git? You seem to have used the wrong new line settings, which should not happen if your git client is configured correctly.
> 
> I did webedits exclusively, I thought it would be easy and quick.

You didn't test this in game at all?

**Comment by slarticodefast** [comment]
> I did webedits exclusively, I thought it would be easy and quick.

Yeah, please don't do that. Like mentioned in the [PR guidelines ](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html)they are prone to errors and all changes should be tested in-game.
Have a look at our guides for [setting up your IDE ](https://docs.spacestation14.com/en/general-development/setup/setting-up-a-development-environment.html)and [using git ](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html)to learn how to do this properly. If you need help with any steps, feel free to ask on our discord server.

**Comment by DieselMohawk** [comment]
I'll just redo all of this in my dev environment, I don't like it as much but if I gotta do it that way then so be it.

**Comment by DieselMohawk** [comment]
Alrighty, closing this for another PR.

**Pull request closed without merging**
