### PR TITLE
Price gun cartridge (attempt 2)

### PR DESCRIPTION
**Pull request by Lomcastar**
## About the PR
Added Space Vendors cartridge. When the program is activated, the PDA will work as an appraisal tool and write the result to the program.
The program displays: The name of the item, its price, how many minutes ago the assessment was made.
UI is updated when you enter the program and add new entries.
Installed from the start in the PDA: QuartermasterPDA, CargoPDA, SalvagePDA.
Loaders should always know the price of the goods, even when the assessment tool is not with them. With the help of the program, the loader will be able to compare the results of his work.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**

:cl: Lomcastar
- add: Added new cartridge Space Vendors.
- tweak: NanoTrasen Corporation has equipped all Cargo PDAs with a Space Vendors cartridge!

https://user-images.githubusercontent.com/129697969/235303081-69ce7729-70f8-4486-a3a9-db83c124d4b6.mp4

1Minute

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Just update the old one, don't make new ones please.

**Comment by Lomcastar** [comment]
I don't really understand how to do this?

**Comment by metalgearsloth** [comment]
> I don't really understand how to do this?

Push updates to the PR and it will be updated.

**Comment by metalgearsloth** [comment]
Old one has the reviews on it.

**Pull request closed without merging**
