### PR TITLE
Remove turrets from outside of nukie shuttle

### PR DESCRIPTION
**Pull request by Emisse**
theres now 1 turret inside cock pit and one inside abaft to stern

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
if i make a change to the nukie shuttle and save it as a grid it doesnt spawn on the nukie shuttle and if i save it as map it bricks nukies

**Comment by Emisse** [comment]
save as grid make sure your cvars arent fucked up in testing

**Comment by JoeHammad1844** [comment]
what cvars should i look out for

**Comment by JoeHammad1844** [comment]
actually i dont even know how to check my cvars :trollface:

**Comment by JoeHammad1844** [comment]
it saves like this for some reason
image

**Comment by JoeHammad1844** [comment]
wait im dumb i saved the map number with savegrid lmao

**Comment by JoeHammad1844** [comment]
oh its even worse
image

**Comment by JoeHammad1844** [comment]
HOLY FUCK I HAD TO SAVE IT AS A MAP AND DO CODE SURGERY TO SET PARENT TO INVALID TO GET IT TO WORK

**Pull request merged**
