### PR TITLE
Nerfs and adds the double bladed esword back to traitor uplinks

### PR DESCRIPTION
**Pull request by Thurtik**
## About the PR

This PR nerfs the reflection chance of the double bladed esword and adds it back to uplinks for traitors to purchase again for 20TC.

## Why / Balance

Prior to it's removal, the most oppressive part of the double bladed esword was it's incredibly high reflection chance of 80%. With the recent reflection chances rework it was given a minimal reflect chance of 65%, which was a step in the right direction but probably wasn't quite enough of a nerf. I believe that nerfing the reflect chances further to 60% max. and 45% min. makes it balanced enough for a grand re-introduction into the traitors' arsenal. (THIS IS NO LONGER TRUE, reflection chances have been reverted back to being flat, so now the nerf instead brings it down to 55% at all times)
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Nerfed the double bladed esword's reflection chances and added it back into traitor uplinks.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
changelog is broken, needs 🆑 emoji

**Comment by Cojoke-dot** [comment]
20% less reflection is not going to make this weapon less broken, it just makes it a little more rng.

**Comment by AlexUm418** [comment]
this thing is 20 tc purchase and dual wield, sounds pretty balanced for me

**Comment by Cojoke-dot** [comment]
> this thing is 20 tc purchase and dual wield, sounds pretty balanced for me

that's the state it was in before it got removed because it was too strong.

**Comment by Thurtik** [comment]
> > this thing is 20 tc purchase and dual wield, sounds pretty balanced for me
> 
> that's the state it was in before it got removed because it was too strong.

-you're gonna wanna be moving with it since its a melee weapon so the relfection chance isnt always gonna be 60%
-its two-handed so you cannot just use it for passive protection while firing a gun or healing
-you cant use it to just stand still and cheese reflect since its 20tc so you cannot really buy any additional armor (unless you put in the effort to get it from elsewhere) and 60% reflect chance alone (unlike the previous 80%) isnt gonna keep you alive for long

**Comment by ARMOKS** [comment]
Give him 100% reflect all or nothing melee weapon

**Comment by metalgearsloth** [comment]
IIRC it does >40 DPS so is incredibly strong.

**Comment by Thurtik** [comment]
> IIRC it does >40 DPS so is incredibly strong.

its 36 (12 slash + 12 heat * 1.5 attack rate), which is only 6 higher than the regular esword

**Comment by ps3moira** [comment]
will there be bug fixes to the wielding of the double bladed esword too?

**Comment by Thurtik** [comment]
> will there be bug fixes to the wielding of the double bladed esword too? or was that not one of the reasons the dsword was removed

There weren't any bugs iirc, it was just because 80% reflect at all times was bs. The wielding works just like with any other weapon (and the sword turns on/off automatically when wielded/unwielded)

**Comment by Golinth** [comment]
> will there be bug fixes to the wielding of the double bladed esword too? or was that not one of the reasons the dsword was removed

Iirc the real reason was the structural damage rework, and it doing too much damage against walls and windows. It was removed in that PR along with the Syndie Fire Axe

**Comment by a-person5660** [comment]
Spending all your TC for an esword that has 6 more dps and a little bit more reflect doesn't seem worth it imo.
You get so much more versatility out of getting an esword and having TC to spare.
Reflect is fine where it is but it needs more dps. Maybe bring It to 40-45.

**Comment by ElPidor** [comment]
until game will have melee blocking stuff doubleesword will be "overpowered"

**Comment by slarticodefast** [comment]
We had a vote among the maintainers and admins. The poll options and results were the following:
- merge the PR, adds it back to the uplink for 20TC (8)
- make it surplus crate only (and worth 20TC) (10)
- close the PR, no double esword (5)

The discussion was far to long to completely summarize, but the opinions ranged from "give people their edgdgelord weeabo sticks back!" to "it is a weapon that has historically been used exclusively to murderbone and been designed exactly for that", with everything in between. So I guess we will need some more time to think of an idea how to properly balance it before a second poll can be made. One suggestion was that it should be a sidegrade to the esword, not just a better version of it. If you have any ideas, feel free to let us know either here or on our Discord server.

**Comment by slarticodefast** [comment]
Hey, we had another vote can came to the conclusion to give the new balance a try by making it only available randomly through the surplus crate (and worth 20TC). Could you adjust your PR for that?

**Comment by slarticodefast** [comment]
Closing this as derelict.
Also we got another PR #32414 which replaces the dsword.

**Comment by Boaz1111** [comment]
@slarticodefast would there still be an interest in having this in the surplus crate, or are we going for the replacement?

**Comment by slarticodefast** [comment]
@Boaz1111 
The last maintainer/admin vote on this had the following results:
- merge (10 votes)
- make it suplus crate only and worth 20TC (14 votes)
- close PR (3 votes)

It might be best to wait and see if #32414 gets merged (and with what balance) since it serves as a replacement for the dsword.

**Comment by Boaz1111** [comment]
> @Boaz1111 The last maintainer/admin vote on this had the following results:
> 
> * merge (10 votes)
> * make it suplus crate only and worth 20TC (14 votes)
> * close PR (3 votes)
> 
> It might be best to wait and see if #32414 gets merged (and with what balance) since it serves as a replacement for the dsword.

alrighty! I'll ask again after that PR's resolved!

**Pull request closed without merging**
