### PR TITLE
Added new chemicals

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Added 
Added oil, lye, hydrogen peroxide, acetone, phenol and saltpetre into chemical combinations. Now when people try making chemicals they won't be disappointed because they can't make them they will be disappointed because they don't do anything but a step forwards is a step forwards and we have to start somewhere with new chemicals. 

**Screenshots**

image

**Changelog**

:cl:Seth
- add: Added  Oil, Lye, Hydrogen peroxide, Acetone, Phenol and Saltpetre (Non Functional)

### CODE REVIEW

**Review by SweptWasTaken — APPROVED** [review]
Looks good. I'm not too familiar with the chemist role and i'm not sure if it's fair adding recipes for chems that don't do anything.

@Bright0 do you have any input?

**Comment by SethLafuente** [comment]
> Looks good. I'm not too familiar with the chemist role and i'm not sure if it's fair adding recipes for chems that don't do anything.
> 
> @Bright0 do you have any input?

80% of chemicals right now added to ss14 don't do anything is good to add more so when someone tries to actually give them a use they already have bases to start on

**Comment by SweptWasTaken** [comment]
> 
> 
> > Looks good. I'm not too familiar with the chemist role and i'm not sure if it's fair adding recipes for chems that don't do anything.
> > @Bright0 do you have any input?
> 
> 80% of chemicals right now added to ss14 don't do anything is good to add more so when someone tries to actually give them a use they already have bases to start on

I already don't like the thought of a bunch of dummy chemicals you can mix for "fun".

**Comment by SethLafuente** [comment]
> > > Looks good. I'm not too familiar with the chemist role and i'm not sure if it's fair adding recipes for chems that don't do anything.
> > > @Bright0 do you have any input?
> > 
> > 
> > 80% of chemicals right now added to ss14 don't do anything is good to add more so when someone tries to actually give them a use they already have bases to start on
> 
> I already don't like the thought of a bunch of dummy chemicals you can mix for "fun".

I think is a good thing that they exist then if someone wants to add effects for them they can do it faster their is no bad side effects is just a step forwards

**Comment by Zumorica** [comment]
I agree with Swept here. Having more dummy chemicals that do nothing is not good.

**Comment by SethLafuente** [comment]
> I agree with Swept here. Having more dummy chemicals that do nothing is not good.

I really dont see what's wrong with having more chemicals that don't do anything it makes chemistry have more stuff to work with and when someone wants to add stuff they don't have to go through the trouble of adding this they already have bases to work with saying no to this is like saying no to progressing chemistry because it has more stuff

**Comment by Zumorica** [comment]
> > I agree with Swept here. Having more dummy chemicals that do nothing is not good.
> 
> I really dont see what's wrong with having more chemicals that don't do anything it makes chemistry have more stuff to work with and when someone wants to add stuff they don't have to go through the trouble of adding this they already have bases to work with saying no to this is like saying no to progressing chemistry because it has more stuff

No, when you want to change something fundamental about how reagents or chemistry is represented in prototypes and data, having so many dummy, useless chemicals only makes things more painful. We will add these chemicals when we can implement their behaviors sanely. No point adding them before that. Oh, and this goes for EVERY prototype in the game, too.

**Comment by SethLafuente** [comment]
> > > I agree with Swept here. Having more dummy chemicals that do nothing is not good.
> > 
> > 
> > I really dont see what's wrong with having more chemicals that don't do anything it makes chemistry have more stuff to work with and when someone wants to add stuff they don't have to go through the trouble of adding this they already have bases to work with saying no to this is like saying no to progressing chemistry because it has more stuff
> 
> No, when you want to change something fundamental about how reagents or chemistry is represented in prototypes and data, having so many dummy, useless chemicals only makes things more painful. We will add these chemicals when we can implement their behaviors sanely. No point adding them before that. Oh, and this goes for EVERY prototype in the game, too.

fair

**Comment by Bright0** [comment]
> @Bright0 do you have any input?

I'm late to the party but I think even having placeholder chemicals is still progress towards actually coding what they do. It cuts out the busywork portion, at least in my opinion.

**Comment by SweptWasTaken** [comment]
> 
> 
> > @Bright0 do you have any input?
> 
> I'm late to the party but I think even having placeholder chemicals is still progress towards actually coding what they do. It cuts out the busywork portion, at least in my opinion.

Yeah, even retro-fitting the chemicals when new systems come along wouldn't be more tedious than rewriting them but eh. Someone can just come back to this PR if they really need them.

**Comment by SethLafuente** [comment]
I'm just gona re open it then close it if you want

**Comment by metalgearsloth** [comment]
As a reformed offender I agree on not adding them without the underlying code.

**Comment by mirrorcult** [comment]
if this does get added then the changelog should at least make it clear that they are nonfunctional

**Pull request closed without merging**
