### PR TITLE
Advanced tools technology

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

New technology that gives you access to improved equipment
**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: lzk
- add: NT has granted stations access to research the new technology called 'Advanced Tools'.

### CODE REVIEW

**Comment by lzk228** [comment]
fuck

**Comment by deltanedas** [comment]
typos in cl

**Comment by EmoGarbage404** [comment]
I'd rather keep magboots and advanced tools separate. Magboots are a wanted enough item to justify having unique tech. There's not really a point to bundle them with anything else.

You could just make an "advanced tools" technology and bundle power drill, jaws of life, and experimental welder.

**Comment by lzk228** [comment]
i dont think that jaws of life must be printable, because any sindy scientist can easily print jaws and break any door what he want

**Comment by deltanedas** [comment]
they can already do that with insuls so

**Comment by AJCM-git** [comment]
@lzk228 research freeze is over, you can update this

**Pull request closed without merging**
