### PR TITLE
Added Firebots - Real

### PR DESCRIPTION
**Pull request by Golinth**
## About the PR

Added Fire Bots - helpful little creations that will automatically extinguish any entity on fire. They can be made with a fire extinguisher, any fire helmet, a proximity sensor, and a borg arm. 

It currently IS included in the random sentience ghost role list (I tested, they do work with it), will be removed if #32383 is merged.

## Why / Balance

With the current incredibly deadly nature of fire and the increased potential sources of flames, having a source of automated help to put out flaming crew members. Also SS13 parity. 

**Imagine:**
A fire anom is found, and sci wants to keep it. They make a  firebot or two and place them in the area so any unfortunate souls caught in the pulse aren't immediately burnt to a crisp. This is in-line with other anoms where sci has mitigation techniques, like the shadow anom with flashers, the ice anom with heaters, the meat anom with spacing, etc. 
A trit leak event happened in maints, and a roboticist decides to create some bots for the effected area, to extinguish people on fire and help prevent ashing. 

 I'm 100% open to nerfing its movement or spray rate, pending discussions. Or even buffing it to put out atmos fires. 
Additionally, I have not added the emag interaction (as much as I want to see CLF3 firebots) as they are currently frozen. 

## Technical details

Added the "OnActivateInWorld" subscription to the SpraySystem
Changed SpraySystem to use useDelay instead of its own cooldown system. 
Added a new Consideration for NPCs called "TargetOnFireCon" which checks for the flammable component and if the onFire boolean is true. 
Added a UtilityQuery that checks for that consideration called "NearbyOnFire"
Adds new FireExtinguisher and FireHelmet tags for construction

## Media

https://github.com/user-attachments/assets/9d0625af-2405-4364-ab61-3223990e4284

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Firebots can now be constructed by scientists - the bots wander the station looking for fires to put out with their built-in extinguisher.

### CODE REVIEW

**Comment by Ilya246** [comment]
sad that emag interacts are frozen, would be funny to have it set people on fire

**Comment by Golinth** [comment]
> sad that emag interacts are frozen, would be funny to have it set people on fire

Agreed 😔

**Comment by slarticodefast** [comment]
I love them. We really need ingnitable puddles now.

> sad that emag interacts are frozen, would be funny to have it set people on fire

Make them refillable with any reagent maybe?

**Comment by lzk228** [comment]
do they really wander around the station or as cleanbots barely can move out from a single hallway?

**Comment by Golinth** [comment]
> do they really wander around the station or as cleanbots barely can move out from a single hallway?

Cleanbot style. They have the same idle as every other bot

**Comment by pheenty** [comment]
> sad that emag interacts are frozen, would be funny to have it set people on fire

 funny but too chaotic, maybe keep the behavior of spraying ignited people, but instead of water with welding fuel or even napalm so it only inflames them more?

**Comment by thebadman4662** [comment]
> > sad that emag interacts are frozen, would be funny to have it set people on fire
> 
> funny but too chaotic, maybe keep the behavior of spraying ignited people, but instead of water with welding fuel or even napalm so it only inflames them more?

Tritium, go all the way in. :trollface:

**Comment by Plykiya** [comment]
> If the AI isn't much different from cleanbots then this feels bloaty with how niche of an application this is

considering how often science gets set on fire from artis and anoms, this feels like a normal thing science would develop for themselves

**Comment by 7-62x54r** [comment]
sci moff are eating good tonight if this gets added

**Comment by ps3moira** [comment]
> > If the AI isn't much different from cleanbots then this feels bloaty with how niche of an application this is
> 
> 
> 
> considering how often science gets set on fire from artis and anoms, this feels like a normal thing science would develop for themselves

Don't we have Borg modules and fire extinguishers mapped around though?

**Comment by Golinth** [comment]
Actually respects useDelay now and wont just spam extinguish everyone on fire. Takes a couple seconds to reset after each spray

**Comment by superjj18** [comment]
I gotta be real what game are you playing where fire is a threat?

SS14 fire is pathetic and laughable.  Barely any spread, dies out almost immediately unless there is a constant source of plasma, almost always survivable via stop-drop-and-roll.

Like yeah if you go to lava land and step in lava your gonna burn to death but I just don't see fire as a genuine threat.  Heatflooding will kill and round end people but that's not exactly "fire".

I have zero issues with this PR and hope it gets merged, I'm just peeved at pretending like fire isn't weak af.  Fire needs a massive buff to its ability to spread and cause atmos issues(co2 flooding due to smoke etc) because I can't remember the last time I saw someone actually use the firefighter suit from fire lockers.

**Pull request merged**
