### PR TITLE
The Cratening

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Resprites all of the crates.
The form is loosely based off of old crates + some experimentation to make them wider and less obnoxious
The designs are mostly from /vg/ with a few being the same as before.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: All crates have a brand new look.

### CODE REVIEW

**Comment by potato1234x** [comment]
here before it becomes https://github.com/tgstation/tgstation/pull/75785

**Comment by Vaaankas** [comment]
> here before it becomes [tgstation/tgstation#75785](https://github.com/tgstation/tgstation/pull/75785)

those original tg crates are still better even than this pr ngl

**Comment by EEASAS** [comment]
as a heavy /tg/ player, the cratening was a fucking disaster and i did not enjoy it, neither do i enjoy it now
anyways these new cratesprites(ss14) look much better than the current tg ones

**Comment by JustCone14** [comment]
They look very nice but a part of me does miss the vibrancy. The Engineering crates look a little out of place now as yellow and black are not really Engi colour combinations. They were a lot more fitting when they were yellow and red. I also think the Botany crates look so bland now. I think even if they still had the green stripe across the top they would look better. Honestly think more crates should have the stripe across the top but I get that it might be hard to make them look good.

**Pull request merged**
