### PR TITLE
Adding an AccessReader to a antimatter engine with engineering access

### PR DESCRIPTION
**Pull request by chavonadelal**
## About the PR

Adding an AccessReader to a Antimatter Engine with engineering access
## Why / Balance

By analogy with my last pull request #30394 with the addition of AccessReader  to a particle accelerator , this will make life more difficult for the raiders and also make the antagonists think a little more. Plus, it will protect you from manipulation by random guests of the department. This can be hacked using EMAG
## Media

The view from the player's face without access:
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: to4no_fix
- tweak: Now engineering access is needed to interact with the antimatter engine

### CODE REVIEW

**Comment by deltanedas** [comment]
very bad for getting power going without any engis, now youd need to break ces locker to get an engi id

**Comment by chavonadelal** [comment]
> very bad for getting power going without any engis, now youd need to break ces locker to get an engi id

The same can be said about the presence of doors to the department in this case. It also complicates. I don't think this is worth focusing on.

**Comment by deltanedas** [comment]
doors can be opened freely once power is lost, the same cant be said for this

**Comment by chavonadelal** [comment]
> doors can be opened freely once power is lost, the same cant be said for this

They can be blocked before the light goes out. I say, it is not worth considering in this plane, since if there are really few players, a small map with automatic energy generation is suitable for them. And finding access is not a problem in any case.

**Comment by lzk228** [comment]
ame is not that dangerous as singulo/tesla and it's the easiest power source in case of lack of engineers
without access to ame the only power source is solars what really won't be enough

**Comment by chavonadelal** [comment]
> ame is not that dangerous as singulo/tesla and it's the easiest power source in case of lack of engineers
> without access to ame the only power source is solars what really won't be enough 

If there are few players, a small map with automatic energy generation will suit them, as I said. And if for some reason you chose a large map with a small online, then either the captain or someone from the command will come to the rescue, or you can get into the captain's cabin and get an ID card. And the engine is quite dangerous if you do not make sure that someone has set extreme values. It will explode before the fuel runs out.

**Comment by Doctor-Cpu** [comment]
> > ame is not that dangerous as singulo/tesla and it's the easiest power source in case of lack of engineers
> > without access to ame the only power source is solars what really won't be enough
> 
> If there are few players, a small map with automatic energy generation will suit them, as I said. And if for some reason you chose a large map with a small online, then either the captain or someone from the command will come to the rescue, or you can get into the captain's cabin and get an ID card. And the engine is quite dangerous if you do not make sure that someone has set extreme values. It will explode before the fuel runs out.

Every low pop map with the exception of reach relies on the AME as the sole power source. Atlas can barely do it without an AME.
This just encourages stealing IDs just to setup power.

**Comment by chavonadelal** [comment]
> > > ame is not that dangerous as singulo/tesla and it's the easiest power source in case of lack of engineers
> > > without access to ame the only power source is solars what really won't be enough
> > 
> > If there are few players, a small map with automatic energy generation will suit them, as I said. And if for some reason you chose a large map with a small online, then either the captain or someone from the command will come to the rescue, or you can get into the captain's cabin and get an ID card. And the engine is quite dangerous if you do not make sure that someone has set extreme values. It will explode before the fuel runs out.
> 
> Every low pop map with the exception of reach relies on the AME as the sole power source. Atlas can barely do it without an AME.
> This just encourages stealing IDs just to setup power.

Unfortunately, I don't think so

**Comment by chavonadelal** [comment]
> > > ame is not that dangerous as singulo/tesla and it's the easiest power source in case of lack of engineers
> > > without access to ame the only power source is solars what really won't be enough
> > 
> > If there are few players, a small map with automatic energy generation will suit them, as I said. And if for some reason you chose a large map with a small online, then either the captain or someone from the command will come to the rescue, or you can get into the captain's cabin and get an ID card. And the engine is quite dangerous if you do not make sure that someone has set extreme values. It will explode before the fuel runs out.
> 
> Every low pop map with the exception of reach relies on the AME as the sole power source. Atlas can barely do it without an AME.
> This just encourages stealing IDs just to setup power.

Unfortunately, I don't think so

**Comment by BombasterDS** [comment]
I like the idea of adding access for PA, because if it sabotaged it literally end of the shift.

But this don't work with AME. It's used as the main power supply on lowpop maps, where often engineers are simply absent. So players, in the absence of command, will be forced to break down the captain's or hop's locker to get access for setting up power that sounds not very good. The current situation with syndie when lowpop is already bad, given that they have no one to oppose them on the station, and with the introduction of such an update, players will be obliged to give someone access to install the AME, which will only make antags life easier.

**Comment by BombasterDS** [comment]
Like when i'm playing engi (mostly playing on Goob) i just don't set up AME because it's much faster to start singulo/tesla or TEG.

**Comment by slarticodefast** [comment]
I brought this up for discussion with the maintainers and the agreement was that this is not needed. Adding it to the particle accelerator was an exception due to the high griefing potential. Thank you for your contribution.

**Pull request closed without merging**
