### PR TITLE
Gamma & Epsilon alerts levels

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR 
Add Gamma & Epsilon CentCom only alert levels from Paradise station.

Gamma level is set by CentCom to assist station in form of additional weapon supply, ERT, etc
Epsilon level is set by CentCom to destroy station for their sins.

Here used custom made Epsilon sound, but can bring back boring siren.

**Screenshots**

**Changelog**

:cl:
- add: New NanoTrasen alert levels - Gamma & Epsilon

### CODE REVIEW

**Comment by wrexbe** [comment]
You can't include the siren from the purge movie. Please include the source of any art or sound assets you add, and make sure they have a license that is suitable for this project.

**Review by wrexbe — CHANGES_REQUESTED** [review]
You can't include the siren from the purge movie. Please include the source of any art or sound assets you add, and make sure they have a license that is suitable for this project.

**Comment by Peptide90** [comment]
I had forgot about gamma level armory. These will be handy for admemes. Epsilon can be our deathsquad. Anyhow SOP will need updating.

**Comment by Morb0** [comment]
All sounds from Paradise and they use `CC-BY-SA 3.0` license for assets, so I think all legitimate.

**Comment by wrexbe** [comment]
It is clearly the siren from the purge movie, so even if they have listed that as the copyright, it's invalid, because we can't defend it. If you want the PR to go through you need to remove "purge_siren.ogg", and not refer to the purge anywhere in the commit.

**Review by wrexbe — APPROVED** [review]

**Pull request merged**
