### PR TITLE
Fix saving prefered quick store item locations

### LINKED ISSUE #30740: Save Item Location does not work
## Description

The dearly beloved QoL feature of being able to save your items position in your bag/belt or any other storage container appears to be broken, no matter how many times you try to save an items position it just doesn't save it, i tried changing keybinds thinking its my issue but that didn't help.

**Reproduction**

-Spawn an empty bag
-Place a crowbar in the most bottom right corner of the storage UI
-Save the Crowbars position by pressing middle mouse button on it.
-Take the crowbar out
-Put the Crowbar back in the bag
-Wheep as the item position did not get saved

**Screenshots**

**Additional context**

### LINKED ISSUE #30947: cant save item locations in storage anymore
## Description
simply doesnt do anything, even if rebinding the key to something else

### PR DESCRIPTION
**Pull request by Callmore**
## About the PR

Changed a true to a false

fixes #30740
fixes #30947

## Why / Balance

It's been broken for the better part of two months now, it's been getting annoying and i'm supprised no one's really been talking about it.

## Technical details

`true` -> `false`

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Prefered item quick store locations can be created again.

### CODE REVIEW

**Comment by BramvanZijp** [comment]
Absolute legend (assuming it works), thanks so much.

**Review by slarticodefast — APPROVED** [review]
Works as intended, thanks for the fix!

**Comment by superjj18** [comment]
Is there a way to favorite an item so that it's always pulled out when shift+b or shift+e?  Would be nice for weapons where quick draw is life or death

**Comment by chromiumboy** [comment]
Thanks for the fix, tested in-game and the issue seems to be resolved

**Pull request merged**
