### PR TITLE
Resprite regular glass tile

### PR DESCRIPTION
**Pull request by Vordenburg**
A few players told me that the new glass tile gave them dizziness, so I worked with them to create a version of the glass tile that was more suitable. I'm offering this as an alternative resprite.

image

image

### CODE REVIEW

**Comment by Emisse** [comment]
looking too opaque, the original glass was more transparent than this, im fine with this as a tile variant but feel like this fits different aesthetically for a retexture

**Comment by Vordenburg** [comment]
What would you like done with this?

**Comment by Emisse** [comment]
idk if u remember our original glass texture maybe something like that but more transparent

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Either make the old ones more transparent or make the current ones a little more opaque and "glassy", making em divided with a cross and very blue doesnt really fit with em (since space should still be relatively visible)

**Comment by AJCM-git** [comment]
re-open once you come back to this

**Pull request closed without merging**
