### PR TITLE
Respite and minor changes to mercenary items

### PR DESCRIPTION
**Pull request by Jackal298**
This is try number three, everything should be fine this time

## About the PR

This is the corrected version that I made, in PR #23779 I made a mistake with some files, which is why I deleted it and quickly redid it, Forgive me for such an oversight, I have a cold and my brain is starting to melt

This PR is a remake of PR numbered https://github.com/space-wizards/space-station-14/pull/23616, due to my mistakes with the repositories, I decided to delete and redo this work so that it would be merged

Merc backpack received a complete resprite and now it has become better in terms of design and began to look like a military backpack

Mercenary Jumpsuit received life and coordinate sensors, and now if you die, you have a chance that a paramedic will find you

Mercenary combat gloves and mercenary fingerless gloves received new icon sprites (and in the case of fingerless gloves, the sprites on the player model were updated). The icon sprites were made so that they were not very different from each other when converting combat gloves into fingerless gloves (and yes, sprite icons for fingerless gloves gloves have cut off fingers)

## Media

295174517-e580fe4e-e68a-4177-9cae-63325e6eb5c0
295175236-9b186eed-460b-413a-a73a-4931fa6ff0d1

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Jackal298** [comment]
> (x2) meta.json has a typo (that's whatever, ignorable) but also links to the wrong commit. The latter is actually a problem as this is meant to be an attribution and it makes it harder to trace the original author*.
> 
> * Change `stansion` to `station` in 2 meta.json files
> * Link to correct commit in both files (I believe the correct one is  `https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e`) in 2 meta.json files
> 
> _* - not going to speculate whether this is a big deal or not, but we can easily make it right - so let's make it right._
> 
> PS. There is no need to recreate PR because "it got buried". But I see the branch changed so maybe you had a different reason to recreate it. In any case - FYI.

Thank you for the advice and explanation about the meta, about “it got buried” there was a problem with my repositories because of which I had to delete and redo it, but again I made a mistake and had to redo it 3 times, as I wrote above, the cold is melting my brain why such stupid mistakes happen

**Comment by Jackal298** [comment]
Sorry LordCarve for not understanding you, now I corrected it as you told me, now I corrected the meta file as it should, I inserted the code that you wrote to me

**Comment by Jackal298** [comment]
> It should be `https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e",` not just the `4f6190e2895e09116663ef282d3ce1d8b35c032e`.
> 
> For your convenience I'm including a brief guide to diffs (short for differences a.k.a. what was changed) below.
> 
> 1. At the very top of your PR you will find several tabs. The one that lists all your changes is titled [ Files changed ] - click it.
>    image
> 2. Here you can see all the files that your PR modifies. Highlighted in green are changes that you added to this file. Highlighted in red are changes that you removed from this file. Replacing a text with another text with result in both red and green (red signifies the removal of the original text, green signifies the addition of the new text).
> 3. On the left side there is a list you can use to quickly browse all the modified files. Scroll to `mercfingerless.rsi` folder and click on the `meta.json` file inside.
>    image
> 4. Notice how on the 4th line, there is a text highlighted in green, but nothing is highlighted in red. This means that you added to the line and did not remove anything from it.
> 
> ### This is good. It means you appended the the existing attribution.
> image
> 
> 6. Now use the file browser on the left to navigate to the `mercbattle.rsi` and click on the `meta.json` file inside it.
>    image
> 7. Oops! There is some text highlighted in red here. What does that mean? It means a part of the line **was removed by you**. Since `meta.json` file stores attributions, that's probably not good (as a rule we don't want attributions removed).
> 
> ### This is bad, it means you removed something from the attributiom.
> image
> 
> Can you see what the problem is? Hint: Go to the cog wheel settings at the top of the [ Files changed ] page and select Diff view "Split" to cleanly separate left side (how file was before your changes) from right side (how file is after your changes).
> 
> As a rule of thumb regarding attributions, you want to make sure there is no red highlight in any of the `meta.json` files. So how do you get rid of the red highlight? Easy! Make sure your file only _adds_ to the original file.
> 
> 1. Restore the file to its original contents
> 2. Add the bit that you wanted to add at the end of the line:
> 
> ```
> and paradise station https://github.com/ParadiseSS13/Paradise/blob/master/icons/obj/clothing/gloves.dmi"
> ```
> 
> The end result's 4th line should be this:
> 
> ```
>   "copyright": "modified sprite from Jackal298 based on the sprite from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e and paradise station https://github.com/ParadiseSS13/Paradise/blob/master/icons/obj/clothing/gloves.dmi"
> ```
> 
> (Don't miss the two spaces before "copyright" - those are important!)
> 
> When you do that and push your changes to git - check the [ Files changed ] and confirm that there isn't any red highlight anymore. There shouldn't be.
> 
> In general you should always check the diff of your PR - the [ Files changed ] tab, to confirm that the PR only contains the changes you wanted to do and nothing snuck in by accident. And as you can see - you can also use it to check `meta.json` files to make sure you haven't accidentally removed an attribution.



> It should be `https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e",` not just the `4f6190e2895e09116663ef282d3ce1d8b35c032e`.
> 
> For your convenience I'm including a brief guide to diffs (short for differences a.k.a. what was changed) below.
> 
> 1. At the very top of your PR you will find several tabs. The one that lists all your changes is titled [ Files changed ] - click it.
>    image
> 2. Here you can see all the files that your PR modifies. Highlighted in green are changes that you added to this file. Highlighted in red are changes that you removed from this file. Replacing a text with another text with result in both red and green (red signifies the removal of the original text, green signifies the addition of the new text).
> 3. On the left side there is a list you can use to quickly browse all the modified files. Scroll to `mercfingerless.rsi` folder and click on the `meta.json` file inside.
>    image
> 4. Notice how on the 4th line, there is a text highlighted in green, but nothing is highlighted in red. This means that you added to the line and did not remove anything from it.
> 
> ### This is good. It means you appended the the existing attribution.
> image
> 
> 6. Now use the file browser on the left to navigate to the `mercbattle.rsi` and click on the `meta.json` file inside it.
>    image
> 7. Oops! There is some text highlighted in red here. What does that mean? It means a part of the line **was removed by you**. Since `meta.json` file stores attributions, that's probably not good (as a rule we don't want attributions removed).
> 
> ### This is bad, it means you removed something from the attributiom.
> image
> 
> Can you see what the problem is? Hint: Go to the cog wheel settings at the top of the [ Files changed ] page and select Diff view "Split" to cleanly separate left side (how file was before your changes) from right side (how file is after your changes).
> 
> As a rule of thumb regarding attributions, you want to make sure there is no red highlight in any of the `meta.json` files. So how do you get rid of the red highlight? Easy! Make sure your file only _adds_ to the original file.
> 
> 1. Restore the file to its original contents
> 2. Add the bit that you wanted to add at the end of the line:
> 
> ```
> and paradise station https://github.com/ParadiseSS13/Paradise/blob/master/icons/obj/clothing/gloves.dmi"
> ```
> 
> The end result's 4th line should be this:
> 
> ```
>   "copyright": "modified sprite from Jackal298 based on the sprite from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e and paradise station https://github.com/ParadiseSS13/Paradise/blob/master/icons/obj/clothing/gloves.dmi"
> ```
> 
> (Don't miss the two spaces before "copyright" - those are important!)
> 
> When you do that and push your changes to git - check the [ Files changed ] and confirm that there isn't any red highlight anymore. There shouldn't be.
> 
> In general you should always check the diff of your PR - the [ Files changed ] tab, to confirm that the PR only contains the changes you wanted to do and nothing snuck in by accident. And as you can see - you can also use it to check `meta.json` files to make sure you haven't accidentally removed an attribution.

Thank you for such an extended comment, I have already corrected this, but in the second fix I inserted it as it should have been, but for some reason most of the link was erased for a reason unknown to me, sorry for all the trouble

**Comment by Jackal298** [comment]
> Looks good to me.
> 
> Ran patch locally. No issues.

I have already checked my work on a local server, everything works fine, thanks for your help

**Review by EmoGarbage404 — APPROVED** [review]

**Pull request merged**
