### PR TITLE
Add tethergun lathe recipe

### PR DESCRIPTION
**Pull request by metalgearsloth**
OOp

:cl:
- add: Add lathe recipe for tethergun.

### CODE REVIEW

**Comment by mirrorcult** [comment]
t3 experimental tech perhaps

**Comment by metalgearsloth** [comment]
science boy told me t2 but idm.

**Comment by EmoGarbage404** [comment]
> t3 experimental tech perhaps

i don't know if it's good enough to justify it but t3 experimental is already kinda underwhelming so doubling up might be fine idk.

**Comment by mirrorcult** [comment]
yeah that was my thought

**Pull request merged**
