### PR TITLE
make bullets hurt considerably more

### PR DESCRIPTION
**Pull request by randy10122**
## About the PR

made most of the firearm damage numbers go up
guns currently just feel a bit. underpowered against people with no armour - i shouldnt have to shoot a naked man 6 times to put him into crit
all following statistics assume unarmoured target:
most .35 guns take 4-5 to crit
.20 rifle takes 4 shots
.45 magnum takes 4 shots
.25 caseless takes 5 [most pistols do]
.30 rifle takes 4 shots
.60 antimaterial takes 1 and a few punches
oh and in short range shotguns instacrit against unarmoured

most of the time you have to use a gun, you are against targets with armour so i feel this is balanced - if you have to shoot at someone, theres a high chance they have at *least* kevlar or something

lasers not affected bcos im not sure how to balance them 
lmk if youd make any tweaks

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:randy
- tweak: bullets now hurt a lot more

### CODE REVIEW

**Comment by randy10122** [comment]
> Guns having an extremely low TTK has been a persistent issue for most of the game

methinks guns having low ttk is a good thing. i mean its a Gun

**Comment by EmoGarbage404** [comment]
Having a TTK of around 1 to 2 seconds is boring and feels like shit for the person getting shot at.

"It's a gun" is hardly a good justification.

**Comment by randy10122** [comment]
the thing is usually if you are getting shot at, you are armoured to a degree and take considerably less damage than the listed numbers
if you are shooting someone without armour they should drop fast honestly just for realisms sake - being able to shake off getting shot 5 times through nothing but your jumpsuit is a little fucked

**Comment by juliangiebel** [comment]
I agree with emogarbage.
Realism != Fun

**Comment by EmoGarbage404** [comment]
Even heavily armored players aren't going to have more than 30% armor. Also, there are plenty of situations in which an unarmored player might be under fire. Just because you aren't armored up shouldn't mean that you die near instantly when under fire.

Also, yet again, realism isn't a good justification for balance changes.

**Comment by deltanedas** [comment]
i had similar idea but instead of damaging unarmoured players more, simply stun them
being shot 5 times wouldnt instantly kill you but safe to say you wouldnt be moving

**Comment by metalgearsloth** [comment]
I ported bullet damages as is from Eris which were 50% extra of what it is now and the TTK was too low which is still higher than most of these values. Guns already outclass melee so there's no point being minute until we get shields.

Revolvers I just need to think on what their role is before tweaking further.

**Pull request closed without merging**
