### PR TITLE
Port xeno suit

### PR DESCRIPTION
**Pull request by Tunguso4ka**
## About the PR
Ports xeno suit from the tgstation and adds it to the theatrical performance crate, because there is too many items in the theater drobe.

## Media
зображення

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

#### Changelog
:cl: Tunguso4ka
- add: Added xeno suit. You can find it in the theatrical performance crate.

### CODE REVIEW

**Comment by Pangogie** [comment]
We had this previously and removed it due to possible copyright issues.

**Comment by PJB3005** [comment]
We don't even have xenos

**Comment by Tunguso4ka** [comment]
> We had this previously and removed it due to possible copyright issues.

oh, didn`t know about that..

**Comment by Tunguso4ka** [comment]
Closed due to the possible copyright issues.

**Comment by Kadeo64** [comment]
> We don't even have xenos
we don't have xenos as a gamemode, we have xeno enemies for salvage (although they have no unique abilities)

**Pull request closed without merging**
