### PR TITLE
start of persistence support

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
mini revival of #14740
lets maps be loaded from persistence saves and adds `persistencesave` command

this pr doesnt change any components to reserialize properly nor does it add the save load test as that wouldn't work at all.

more data will be saved in future prs piece by piece until eventually the test can be added and boom persistence can be used live.

## Why / Balance
good

## Technical details
the bool cvar `game.usepersistence` is used as before to control persistence being used at all.
with persistence enabled `game.persistencestartmap` map prototype is loaded.

with persistence `game.map` is no longer a prototype id but a path to a save file in the userdata directory.
if it exists, the MapPath on the start map prototype is replaced with this.

## Media
a modified empty map saved and loaded on a fresh server
a few things are serialized properly :) like ame jar being in the controller, nodegroups probably and the akms bolt being closed.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Review by mirrorcult — APPROVED** [review]

**Comment by bbuske** [comment]
This doesn't seem to work for Oasis. 

[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 13611, component: ContainerContainer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 13612, component: ContainerContainer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 13709, component: ContainerContainer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 24249, component: ContainerContainer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 25286, component: ArtifactAnalyzer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 25286, component: ItemPlacer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 25291, component: ArtifactAnalyzer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 25291, component: ItemPlacer
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 26492, component: StationAiCore
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 85695, component: GatewayGenerator
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 85695, component: GatewayGenerator
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 85695, component: GatewayGenerator
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 85695, component: StationCentcomm
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 85695, component: StationCentcomm
[ERRO] entity_deserializer: Encountered invalid EntityUid reference wile reading entity 85695, component: StationEmergencyShuttle
[ERRO] system.container: Missing entity for container trash cart (26416/n26416, CrateTrashCartFilled). Missing uid: 0
[ERRO] system.container: Missing entity for container captain's locker (68205/n68205, LockerCaptainFilledNoLaser). Missing uid: 0
[ERRO] system.container: Missing entity for container goose crate (26370/n26370, CrateNPCGoose). Missing uid: 0
[ERRO] system.container: Missing entity for container goose crate (26370/n26370, CrateNPCGoose). Missing uid: 0
[ERRO] system.container: Missing entity for container hamster cage (26371/n26371, CrateNPCHamlet). Missing uid: 0
[ERRO] station: The station Oasis in map Empty does not have an associated station config!

The round just keeps restarting.

**Comment by deltanedas** [comment]
my brother in christ this pr is 2 years old

**Comment by bbuske** [comment]
> my brother in christ this pr is 2 years old

I am aware of it but that doesn't necessarily mean it's not working. Especially, since the persistencesave command is still there and no other PR or post regarding this has been made. I'd really love to get this working as I try to save modified maps for our server.

**Comment by LaCumbiaDelCoronavirus** [comment]
> I am aware of it but that doesn't necessarily mean it's not working. Especially, since the persistencesave command is still there and no other PR or post regarding this has been made. I'd really love to get this working as I try to save modified maps for our server.

you'd want to look at https://github.com/space-wizards/RobustToolbox/pull/6166 for that then

**Comment by bbuske** [comment]
> > I am aware of it but that doesn't necessarily mean it's not working. Especially, since the persistencesave command is still there and no other PR or post regarding this has been made. I'd really love to get this working as I try to save modified maps for our server.
> 
> you'd want to look at https://github.com/space-wizards/RobustToolbox/pull/6166 for that then

Thanks 🙏🏽 that's Indeed helpful.

**Pull request merged**
