### PR TITLE
Remove The Throngler from Grand Lottery

### PR DESCRIPTION
**Pull request by EdenTheLiznerd**
## About the PR

Throngler has been removed from grand lottery at the request of Kayek

## Why / Balance

I don't understand how the crew has access to something as absurd and round destroying as the throngler, it quite literally is an admin weapon and shouldn't be given to salvage of all people, I feel this is a good QoL change for the game.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
 :cl:
- tweak: Removed the throngler from the grand lottery

### CODE REVIEW

**Comment by FungiFellow** [comment]
The Throngler either ruins the round for Crew or for Antags.

It's so busted it shouldn't be anything but Admeme

**Comment by EdenTheLiznerd** [comment]
Ok hold on my checks are fucking dying, I need to figure that out first

**Comment by EdenTheLiznerd** [comment]
I am fucking clueless as to where the issue is so assistance would be appreciated, thank you

**Comment by moonheart08** [comment]
Check failure is not your fault, looks to be https://github.com/space-wizards/space-station-14/commit/c94751f2d2c0d3951d1252d2c3955b01cedb543e

**Comment by EdenTheLiznerd** [comment]
Good to know, thank you

**Comment by TsjipTsjip** [comment]
Check failure is actually not caused by anything on this repository. Dotnet pushed a monthly update which changes how dependencies get resolved. Every workflow and every fork's workflows are on the flink right now (even those with patches implemented to minimise this). See https://discord.com/channels/310555209753690112/900426319433728030/1240168896657621033 for more information.

**Comment by ninruB** [comment]
What even is the point of the throngler? I don't think it's meant to be a debug or admin weapon because we have bang ded sticks for that.

**Comment by EdenTheLiznerd** [comment]
> What even is the point of the throngler? I don't think it's meant to be a debug or admin weapon because we have bang ded sticks for that.

I believe the whole point of it for a while was "Haha funy" but it got bad and was abused basically everytime, a department as immature as salvage shouldn't have something like this

**Review by VasilisThePikachu — APPROVED** [review]
I have been wanting to see the throngler removed from the lottery for a while now. Even if it's a very rare to appear, I have found that it's always resulting to encourage bad behavior. It was added to the grand lottery as a haha funny. 

Letting it sit for a bit longer for opinions before deciding on merging,

**Comment by VasilisThePikachu** [comment]
Quick little surgery I did in general. Asking what people would hope out of a grand lottery

3 pretty quickly answered throngler, 1 claimed to want to use it to throngle someone, another claimed they wanted to flex it

**Comment by VasilisThePikachu** [comment]
After some discussion with admin and maintainers, I am making the decision to merge this.

My suspicions were confirmed that the throngler seems to encourage bad behavior. Some ahelps shared seem to encourage this. Along with that. In our current server rules and game design, the throngler is basically useless unless you go out of your way to break the rules/want to ruin the game for other players. Otherwise, it's just a useless flex piece.

**Comment by MACMAN2003** [comment]
r.i.p throngler 2024 - 2024

**Comment by PoorMansDreams** [comment]
no longer will the Throngler plague Cargo's mind

**Comment by UbaserB** [comment]
We will probably need something to substitute it now, since the throngler was one of the biggest reasons why cargo would even gamble the crates imo. Also, you forgot to remove the throngler tip now that this has changed.

**Comment by Hanzdegloker** [comment]
I for one, think, Cargo should not gamble :godo:

**Comment by VasilisThePikachu** [comment]
> We will probably need something to substitute it now, since the throngler was one of the biggest reasons why cargo would even gamble the crates imo. Also, you forgot to remove the throngler tip now that this has changed.

It's alright as it is. I heard it has a pulse rifle in it. Hell, I would consider removing the gable create first before considering subtititing it

**Comment by EdenTheLiznerd** [comment]
It has a pulse carbine, not a rifle.

**Comment by Sailzington** [comment]
What's the point of doing all of those bounties now!

**Comment by deltanedas** [comment]
buy 130 bike horn implants for evac trolling

**Comment by Terraspark4941** [comment]
(can't stack implants no more)
(unless you mean everyone gets a bike horn)

**Pull request merged**
