### PR TITLE
methe

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR 

Nerfed meth. Dylovene won't save you, but now it'll be funnier.

**Changelog**

:cl: router
- tweak: Overhauled desoxyephedrine and ephedrine. Overdose threshold changed from 30 to 20, damage increased way high and movement made funnier.

### CODE REVIEW

**Comment by moonheart08** [comment]
Have you checked that movement doesn't lag people out due to the speed boost? 14 is slightly faster than the admin ghost, which is already excessive.

**Comment by metalgearsloth** [comment]
The reason I told scaly to reduce it to 30% is because you will get significant pop-in above that.

**Comment by BasedUser** [comment]
> Have you checked that movement doesn't lag people out due to the speed boost? 14 is slightly faster than the admin ghost, which is already excessive.

> The reason I told scaly to reduce it to 30% is because you will get significant pop-in above that.

At 40ms, the pop-in is noticeable, but it's not *disastrous*. Then again, this isn't debug lag.
image

**Comment by metalgearsloth** [comment]
Anything that leads to pop-in is a hard no.

**Comment by BasedUser** [comment]
It seems 8 speed only causes popin for extremely short amounts of time at 150ms. (1.6)

**Comment by metalgearsloth** [comment]
So it causes pop-in

**Pull request closed without merging**
