### PR TITLE
Fix borgs not getting names on roundstart

### LINKED ISSUE #33444: Borgs don't get names on roundstart
## Description
When I was correcting dataset prototypes ids in #33352 I found out that `names_borg` has no usages.
Probably was removed in #32586 with `PlayerBorgGeneric` prototype

**Reproduction**
1. Choose borg role
2. Spawn as a borg on the station
3. Has just cyborg name

**Screenshots**

image

**Additional context**
Should be pretty easy to fix by putting `type: RandomMetadata` with chosen name dataset prototype.

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Title.

## Why / Balance
Fixes #33444.

## Media

{DA9E456F-391D-4484-80EE-047AFE9F2203}

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Now borgs get names on roundstart.

### CODE REVIEW

**Comment by SlimmSlamm** [comment]
Couldn't we just add a "Preferred Borg Name" on the pre round starts? like in customization

**Comment by deltanedas** [comment]
should be on the player one, this gives built borgs names too

**Comment by slarticodefast** [comment]
> should be on the player one, this gives built borgs names too

Wasn't it like that before borg type switching?

**Comment by slarticodefast** [comment]
They can still rename it, the question is if a build borg should have a random name by default or not.

**Review by slarticodefast — CHANGES_REQUESTED** [review]
oh, I forgot to send the review
oops

**Comment by Winkarst-cpu** [comment]
@slarticodefast


https://github.com/user-attachments/assets/1c2a5407-e338-400f-9878-6f37382f1787

**Comment by Winkarst-cpu** [comment]
Fuck, wrong branch.

**Review by slarticodefast — APPROVED** [review]
Works as intended.
Thanks for the fix!

**Review by Errant-4 — APPROVED** [review]
Ultimately these should be player-settable, but since this PR restores previously working functionality and can go through right now, I think it's fine. Thank you

**Pull request merged**
