### PR TITLE
Fix Ninja being able to access Nuclear Operative ship

### LINKED ISSUE #22433: the space ninja can access the nukie ship
## Description

since the ninja uses an agent ID, which has syndicate access (importantly, not nuclear access) it can access the ship due to it using syndicate access airlocks

this can be solved in a few ways, both involving changing the doors access to nuclear

1. nukies can buy the nuclear agent ID they spawn with instead of the syndicate agent ID (2TC would be a better price to cut down on the cost for reinforcements)
2. give reinforcements a syndicate ID on spawn (not an agent ID, the one the commander and agent come with in their PDA)

### PR DESCRIPTION
**Pull request by Costyyy**
## About the PR

Changed airlocks on the Nuclear Operative ship to nuclear operative syndicate airlocks.
## Why / Balance

Fix #22433
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Changed nuclear operative shuttle airlocks such that they can no longer be opened with an Agent ID.

### CODE REVIEW

**Comment by Errant-4** [comment]
Not sure if syndicate reinforcements getting a PDA and ID should be combined with this

I'm not sure if the linked issue will be auto-closed if you put a word between the "fix" keyword and the issue number

For the first cl line, I think it could be worded more in terms of what it means for players/gameplay, than what it does mechanically, because in this case it might not be fully clear

**Comment by Costyyy** [comment]
> Not sure if syndicate reinforcements getting a PDA and ID should be combined with this
> 
> I'm not sure if the linked issue will be auto-closed if you put a word between the "fix" keyword and the issue number
> 
> For the first cl line, I think it could be worded more in terms of what it means for players/gameplay, than what it does mechanically, because in this case it might not be fully clear

Should I leave only the shuttle changes here and create a separate issue for the reinforcements getting an ID.

**Comment by Errant-4** [comment]
I don't get to decide that. But my opinion is that the should be in a different PR just so the airlock tweak is not held up if there are any concerns brought up about the ID

**Comment by Costyyy** [comment]
Reverted the change that added a syndicate id to reinforcements. It does indeed seem that it wouldn't fit in this PR.

**Comment by JoeHammad1844** [comment]
the CL is a little misleading because the agent ID that nukies spawn with has nuclear access

**Comment by JoeHammad1844** [comment]
thing is, the one that they can buy doesn't have nuclear access to please make it so nukies can buy the nukie agent ID

**Comment by Brandon-Huu** [comment]
> thing is, the one that they can buy doesn't have nuclear access to please make it so nukies can buy the nukie agent ID

It's an agent ID. Can't they just copy access from another nukie

**Comment by JoeHammad1844** [comment]
yes, but it still adds some friction

**Comment by Emisse** [comment]
im not sure the purpose of this pr

**Comment by Costyyy** [comment]
> the CL is a little misleading because the agent ID that nukies spawn with has nuclear access

They start with a syndicate id

**Comment by JoeHammad1844** [comment]
> They start with a syndicate id

the commander and agent spawn with a syndicate ID, the regular guys have an agent ID with nuclear access, but since the CL says agent ID it'll make them think they need a syndicate ID, do you know what i mean?

**Comment by LankLTE** [comment]
I don't believe this is a necessary change- the ninja already has gloves that allow them to emag their way into the shuttle if needed.

**Pull request closed without merging**
