### PR TITLE
Fix turned off thrusters consume power

### LINKED ISSUE #24468: turned off thrusters still use power

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

title

## Why / Balance

fixes #24468 

## Technical details

just set NeedsPower true and false

## Media

https://github.com/space-wizards/space-station-14/assets/124214523/9ced58ab-8a7f-4772-84d9-863942b72394

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Turning off thrusters and gyroscopes now stop consume power.

### CODE REVIEW

**Comment by lzk228** [comment]
Updated the media

**Comment by Ilya246** [comment]
gyros too

**Comment by lzk228** [comment]
> gyros too

they are using thrustersystem so they are also fixed

**Comment by dvir001** [comment]
@lzk228 This update makes thruster loop turning on and off the moment they loss power since they will try to activate without needing power, yet turn off since the code looking for power anyway, making an infinite loop.

This need to be reverted for a fix.

What can be done to fix it, is set power Load to 0, and then reset it back to prototype (Dont set 1500 hardcoded since it will fuck with forks)

**Comment by deltanedas** [comment]
shouldnt use prototype it should just store the previous load on thruster component and restore from it later

**Comment by dvir001** [comment]
> shouldnt use prototype it should just store the previous load on thruster component and restore from it later
> 
> also why can it not use TogglePower

Honestly the power use storing is probably the most simple of fix for this.

**Comment by lzk228** [comment]
> What can be done to fix it, is set power Load to 0, and then reset it back to prototype (Dont set 1500 hardcoded since it will fuck with forks)

that was my first idea before i discovered NeedsPower in ApcPowerReceiverComponent which used in almost all machines
then i suppose for fix we can move my code part more below or something

**Pull request merged**
