### PR TITLE
Firesuit resprite

### PR DESCRIPTION
**Pull request by Deahaka**
## About the PR 
Changes the current firesuit sprite to the new TG ones (◕‿◕) made by [Mr.Entropy aka Imaginos16](https://github.com/Imaginos16)

**Screenshots**

**Changelog**

:cl: Imaginos16
- add: Added new sprite for firesuit.

### CODE REVIEW

**Review by EmoGarbage404 — COMMENTED** [review]
Lgtm, but just check to make sure this doesn't aesthetically clash with the current in-game fire helmet or the atmos firesuit, as neither of those assets are being changed.

**Comment by moonheart08** [comment]
If you're going to port the firesuit over, please port the full set, and edit the hi-vis stripes into their own sprite layer so they can use emissives.

**Comment by Imaginos16** [comment]
Hi, author of the sprites here! I'm fine with this PR, but I will agree the above comments, I'd ideally want the full set with the fire helmets, since that's my intention as an artist. Having just that mildly defeats the purpose of my resprite I did in the respective PR: ( [#67000](https://github.com/tgstation/tgstation/pull/67000) )

Otherwise, I'm happy to see my work has made through so many corners of the Space Station community!

**Comment by ZeroDayDaemon** [comment]
I don't think this is warranted at all, nor did I really think the fire axe one was either. This is just changing sprites for the sake of changing sprites. Which I don't think we should do. Art style is orientated towards /tg/ for a reason. It's also the most recognizable of any space station 13 variety and makes the most sense for this remake to be based on. If you really want a different art style, fork the game, just like it's done for SS13.

**Comment by moonheart08** [comment]
> I don't think this is warranted at all, nor did I really think the fire axe one was either. This is just changing sprites for the sake of changing sprites. Which I don't think we should do. Art style is orientated towards /tg/ for a reason. It's also the most recognizable of any space station 13 variety and makes the most sense for this remake to be based on. If you really want a different art style, fork the game, just like it's done for SS13.

Read closer, this is a tg sprite by a tg spriter.

**Comment by ZeroDayDaemon** [comment]
Looking deeper into this, apparently these are /tg/ sprites, which I wasnt aware of, I'd assumed this was for another fork, since that's what many of your PRs have been, pushing different styles sprites. And looking at the artists PR, it includes much more than just a firesuit.

**Comment by Imaginos16** [comment]
> Looking deeper into this, apparently these are /tg/ sprites, which I wasnt aware of, I'd assumed this was from another fork, since that's what many of your PRs have been, pushing different styles sprites. And looking at the artists PR, it includes much more than just a firesuit.

Happens! As I alluded to in my previous comment, my work tends to sweep huge categories, so I don't mind people extracting specific parts. I'd just preferentially like fire helmets to be included since that's how the set in its entirety is supposed to look like. I'm sure you guys will figure out your own style for other Engineering things!

**Comment by ZeroDayDaemon** [comment]
> > Looking deeper into this, apparently these are /tg/ sprites, which I wasnt aware of, I'd assumed this was from another fork, since that's what many of your PRs have been, pushing different styles sprites. And looking at the artists PR, it includes much more than just a firesuit.
> 
> Happens! As I alluded to in my previous comment, my work tends to sweep huge categories, so I don't mind people extracting specific parts. I'd just preferentially like fire helmets to be included since that's how the set in its entirety is supposed to look like. I'm sure you guys will figure out your own style for other Engineering things!

I think the sprites are fine when viewed in context to an entire departmental respite, and I think all of your work should be included :)

**Comment by Deahaka** [comment]
hmmm look at

This is done in the same style with an open face, while now in the build the helmets look different.
Atmos:

Without resprited helm:

for me, there is no conflicts. Should resprite helmet when other suits are updated to the new standard.


> edit the hi-vis stripes into their own sprite layer so they can use emissives.

I'm not sure I understood correctly, make them glow in the dark? **_ushaded_** layer?

**Comment by Deahaka** [comment]
i tried add some glowing to stripes by PointLight. Here is the results (if u look closely). My choice is 2 radius



And I still don't know about: should replace the full head helmet by hardhat? [I am not familiar with the history of TG sprites, maybe somewhere there is a helmet corresponding to the costume]

**Comment by Deahaka** [comment]
Oh, I'm sorry. I saw that in the PR there are those very "emissives" for the suit in the form of a grayscale. So far, I don't know of a way to make them reflect light, so I'm hoping for a hint on what to do.

**Pull request closed without merging**
