### PR TITLE
make flashes not slow you down

### LINKED ISSUE #20774: Flashes shouldn't cause slowdown
## Description
Flashes really shouldn't cause slowdown:
1. It's fairly overpowered. Literally an instant, near-free followup for your stunbaton as long as someone doesn't have flash protection; the only reason it's probably not abused or more known is because you can't use it on nukeops.
2. They're intended to be defensive weapons first-and-foremost, not stunning ones - the screen flash lasts several seconds already and is enough to disorient an attacker to a large degree, so the slowdown both muddies this role and also makes them unfit for being more common then sec's other gear (they're given to heads and the like for this reason.)

Should probably not apply to flashbangs, which *are* intended to be stunning weapons.

An alternative to this could entail making the slowdown only apply when flashed while facing another player (like in /tg/,) but I'm not sure how feasible that is.

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Closes #20774 
makes flashes (the instant ones) not slow people down

## Why / Balance

see #20774 
also because sometimes the flashes stun the user which makes them do basically nothing

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Flashes no longer slow you down. Flashbangs still slow you down, though.

### CODE REVIEW

**Comment by Partmedia** [comment]
I disagree with the arguments in the linked issue https://github.com/space-wizards/space-station-14/issues/20774. I'll respond more specifically with arguments in that issue.

**Review by mirrorcult — APPROVED** [review]

**Comment by UbaserB** [comment]
I like less slowdown, but i still want some even if its minor. It adds to the effect of being flashed, otherwise its too shallow.

**Comment by deltanedas** [comment]
not being able to see on its own is very useful

**Comment by JoeHammad1844** [comment]
this makes them useless on simplemobs because they dont need sight to attack

**Comment by notquitehadouken** [comment]
> this makes them useless on simplemobs because they dont need sight to attack

i feel like there are better things to be trying on simplemobs than flashing them

**Comment by commash** [comment]
I disagree with the change to remove the slowdown. The flash is already very short duration. The primary use of flash is to slow people that are running, to allow sec to catch up to them and stun. Removing slowdown makes it straight up useless, as PCs don't need to see to continue running in the same duration they are already running in, and mobs don't need sight because they  are usually AI controlled.

If the intent of this change is to help syndicate, it ignores the fact that it is fairly simple for antagonists to get flash protection, all they need are sunglasses, welder mask, or a syndie gasmask.

If the intent is to help mobs, I would recommend just making them flash immune. Not neutering one of the main ways secoffs can easily deal with low level criminals.

**Comment by deltanedas** [comment]
https://github.com/space-wizards/space-station-14/pull/20784 :trollface:

**Pull request closed without merging**
