### PR TITLE
Suit slot weapon consistency + visuals

### PR DESCRIPTION
**Pull request by Vaaankas**
## About the PR

Changed weapons to be equippable in the suit slot where they weren't for consistency.

Also copied visuals from the backpack and belt slots where appropriate to the suit slot.

## Why / Balance

It makes it easier to recognize when someone is armed and looks cool with a lot of previously almost unused sprites being used.

A byproduct of #26116 discussion and feedback.

## Media

- [+] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot_27
Screenshot_26
Screenshot_25

## Breaking changes

**Changelog**

:cl: vanx
- tweak: You can now wear most guns in the suit slot, and see them on yourself!

### CODE REVIEW

**Comment by Vaaankas** [comment]
Screenshot_28

**Comment by maylokana** [comment]
If nothing comes out of the weapon resize PR, at least this could be a neat change

**Comment by baddiePRO** [comment]
this may be just me, but I think the shoulder holster should go under jackets, everything looks nice as is though :)

**Comment by rosieposieeee** [comment]
great change!!!

**Comment by UbaserB** [comment]
what about stuff like jetpacks and air tanks...

**Comment by Emisse** [comment]
THIS IS FOR WEAPONS DEVI

**Comment by UbaserB** [comment]
> THIS IS FOR WEAPONS DEVI

yeah but if they were doing this for weapons couldnt they have also done it for other suit storage items that really need this change (probably more than weapons do imo)

**Comment by revsys413** [comment]
> > THIS IS FOR WEAPONS DEVI
> 
> yeah but if they were doing this for weapons couldnt they have also done it for other suit storage items that really need this change (probably more than weapons do imo)

sounds out of scope for this PR

**Pull request merged**
