### PR TITLE
add construction for carp statue

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
carp statue made of silver, with diamond eyes and real carp teeth, like the description said

the fixture is also less abusable, it has a normal structure fixture now

## Why / Balance
- lore accurate
- give salv something to do endgame, adorn cargo with carp statues :trollface:

## Technical details
no

## Media

the different stages of building it

deconstruction works too and gives the input materials back

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: You can now build carp statues with luxury materials.

### CODE REVIEW

**Comment by Ilya246** [comment]
what if it actually did something like trolling nearby fish to come closer to it

else i think like 2 people will build it ever total

**Comment by deltanedas** [comment]
wyci

**Comment by slarticodefast** [comment]
Should have `noRot: true`
grafik

**Comment by slarticodefast** [comment]
Art directors say the sprite is cool 👍

**Pull request merged**
