### PR TITLE
Resprite powersink

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

The old one was really hue-shifty and just generally didn't fit the game style so i resprited the powersink. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl: Ubaser
- tweak: New powersink sprite.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I generally think the perspective is really odd on this sprite. It's hard to tell whether or not it's laying down or standing up. The lack of outlines on all of the outer bits and the bottom also make it look really rough.

**Comment by UbaserB** [comment]
> I generally think the perspective is really odd on this sprite. It's hard to tell whether or not it's laying down or standing up. The lack of outlines on all of the outer bits and the bottom also make it look really rough.

I’ll try fix those issues tomorrow

**Comment by UbaserB** [comment]
ok i actually forgot to tap the push for a second lol

**Comment by Emisse** [comment]
update meta.json

**Comment by UbaserB** [comment]
> update meta.json

ok 1 sec

**Pull request merged**
