### PR TITLE
Anomaly Grenade for syndicate scientists

### PR DESCRIPTION
**Pull request by Scribbles0**
## About the PR

This PR adds a new grenade for syndicate scientists to use. The grenade spawns an anomaly upon use and costs 4 TC each. If there's anything I should change or add, LMK. Some initial thoughts: Could use a custom sprite. Also could make it not silent (make it beep when activated).

## Why / Balance

Currently, sabotage via anomalies is not very viable mainly due to the randomness of where the anomaly can spawn. Other factors like resource requirement for the anomaly generator and the anomaly generation broadcast can hinder sabotage via anomalies, but the randomness of anomaly spawning is the main hinderance. This item will change that, allowing you to choose where you want an anomaly to go and only requires the precious TC that syndicates have, alongside being silent. The anomaly is still randomly picked, so syndicates may not get the certain anomaly they want.
 
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/91828755/7b613f8e-5661-4059-8de7-76449e2c193a

**Changelog**

:cl:
- add: A new grenade that creates an anomaly has been added for syndicate scientists.

### CODE REVIEW

**Comment by Emisse** [comment]
i dont like homogenizing effects from special department things for antag abilities if that makes sense, i w

**Comment by chromiumboy** [comment]
Also, traitor scientists can use an experimental CHIMP to force these anomalies into crit very quickly. This seems a bit too much

**Comment by Scribbles0** [comment]
been discussed a bit in general chat, a couple ideas:
- move the price up (balance)
- make the anomaly go critical immediately instead of spawning a non-critical one (solves friendly syndies)
- increase the timer or make the grenade into a syndie bomb type deal (balance)

**Comment by IProduceWidgets** [comment]
Kinda feels like the Omega particles but just way simpler and with no evidence aside from seeing you lob a grenade.

**Comment by Cyber-Finn** [comment]
perhaps another cool (and possibly more peaceful) option could be to do the (I forget the name) blue anom that teleports things?
As a kind of "rip-off RD teleporter", or some gadget that teleports you to a random location - for a quick getaway (or escape from perma, if it's an implant), but has very limited uses.

**Comment by Scribbles0** [comment]
going to close this for now, if anyone has an idea to improve this, they can take the idea for themselves
i might come back to it later if i come up with something before someone else does

**Pull request closed without merging**
