### PR TITLE
Prisoner eva suit added

### PR DESCRIPTION
**Pull request by Peptide90**
Prisoner EVA suit based on the existing EVA suit (same pressure protection, no armour values).
.rsi is based on the emergency suit but edited to look more prisoner related.

Screenshot:
prisoner
Admittedly the P could have been blue like the prison jumpsuit having a blue 14 on the back but I wanted this to be generic enough it can be for any station / shuttle / faction and red fits the prison aesthetic. Will see how it goes.
:cl:
- add: Prisoner EVA suits are being rolled out to a station near you!

### CODE REVIEW

**Comment by mirrorcult** [comment]
how is this intended to be used?

**Comment by Peptide90** [comment]
> how is this intended to be used?

It's sort of unnecessary variant of the EVA suit specifically for prisoner transport etc. Requested by Schiene and used to differentiate prisoners from regulars when on shuttles or doing perma stuff.

Cool if it's not wanted.

**Comment by Mith-randalf** [comment]
Seems sensible for situations where sec have prisoners and they need to move them through an area without atmos (for example to the shuttle). I can see some utility here.

**Comment by ondrej008** [comment]
> > how is this intended to be used?
> 
> It's sort of unnecessary variant of the EVA suit specifically for prisoner transport etc. Requested by Schiene and used to differentiate prisoners from regulars when on shuttles or doing perma stuff.
> 
> Cool if it's not wanted.

Why not just port the emergency shelter box from /vg/station?

**Comment by Peptide90** [comment]
> > > how is this intended to be used?
> > 
> > 
> > It's sort of unnecessary variant of the EVA suit specifically for prisoner transport etc. Requested by Schiene and used to differentiate prisoners from regulars when on shuttles or doing perma stuff.
> > Cool if it's not wanted.
> 
> Why not just port the emergency shelter box from /vg/station?

Sounds like a lot of effort for the same effect. Otherwise a transparent locker of sorts for transporting people like a cryo locker would be nice but again, this aint it.

**Pull request merged**
