### PR TITLE
tweak(medical): Reduce chemist slots

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Lowers the maximum amount of chemists from 3 to 2 on maps that had the  maximum set to three.

## Why / Balance

Too many chemists in the laboratory. 

Currently with the state of CMO and Cargo, chemistry usually does not have enough resources to support three chemists who are actively working towards making things for medbay, botany or clown.

Chems run out super quickly and rarely get restocked.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Brandon-Huu** [comment]
Made a few mistakes, fixing now

**Comment by thebadman4662** [comment]
Chemist job is not only spending chems but also harvesting them, that puts even more pressure on the 2 chems and leaves antag-chemists even less time to be naughty if they want to be stealthy and avoid suspicion.

**Comment by UbaserB** [comment]
i would still keep fland at 3 because fland is meant for like 80-100pop iirc

**Comment by Brandon-Huu** [comment]
Closed this by accident...

**Pull request merged**
