### PR TITLE
Blue Shark Soft Toy! 

### PR DESCRIPTION
**Pull request by Willhelm53**
## About the PR 
Adds a lovable shark plushie in classic blue, pretty pink, and dignified grey.

**Screenshots**

ShonkDemo

https://user-images.githubusercontent.com/97707302/196607604-57320f04-0d4e-4142-a785-de8544e96705.mp4

**Changelog**

:cl:
- add: Added Nanotransen Oceanic Apex Predator Plush Figure - Available in blue, pink, and grey!

### CODE REVIEW

**Review by Mervill — APPROVED** [review]
Consider adding at least one shork friend to the syndicate pyjamas bundle?

**Review by PaulRitter — APPROVED** [review]
good pr

**Comment by Willhelm53** [comment]
Added blue shomk to syndie pyjamas bundle, thanks @Mervill good comment 🙌

**Review by ZeroDayDaemon — APPROVED** [review]

**Review by EmoGarbage404 — APPROVED** [review]
should be added to the plushie spawner. other than that i adore

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
