### PR TITLE
Holy light anomaly infection

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
A fairly simple anomaly that can only appear as an infection - it cannot be in the form of a full-blown stationary anomaly

It's tied into the flash mechanics. Pulsing and supercrit causes the surrounding area to be blinded, as well as creating “glowing sparks” that stalk living creatures, blinding them. Sparks disappear over time, or can be destroyed in melee combat.

## Why / Balance
Become a priest with a holy light anomaly, and set up a battle against a graytider with a shadow anomaly. Fucking epic.

## Media

https://github.com/user-attachments/assets/d8b8b2ce-6a06-43a2-9942-f485b41cf649

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Holy light anomaly added (only infection-type)

### CODE REVIEW

**Comment by ScarKy0** [comment]
Ok having infection-only anomalies sounds so cool!
Are there any other ideas than just a light one?

**Comment by TheShuEd** [comment]
Maybe it's the last one for the near future.

**Comment by Djungelskog2** [comment]
Oh boy another anomaly that rids me of my vision

Feedback, the lights look more like stage/strobe lights more than anything, id recommend giving them an actual sprite

**Comment by thebadman4662** [comment]
> Ok having infection-only anomalies sounds so cool! Are there any other ideas than just a light one?

Anom that makes you release random atmos gases?

**Comment by TheShuEd** [comment]
meh. let's face it, it's lazy, I don't want to finish it.

**Pull request closed without merging**
