### PR TITLE
Ammo boxes now have sprites for being parially filled!

### PR DESCRIPTION
**Pull request by Moomoobeef**
## About the PR
Ammo boxes no longer show up as empty after removing just one bullet.

## Why / Balance
Annoying and ugly.

## Technical details
Added new sprites, modified ammo-box ymls to use the new stages

## Media
ammos

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None (probably)

**Changelog**
:cl:
- fix: Ammo-boxes no longer appear empty when only one bullet is removed.

### CODE REVIEW

**Comment by Moomoobeef** [comment]
Test has again failed for reasons seemingly unrelated to the changes made and completely related to the test being consistently buggy and intermittently broken.

**Review by SlamBamActionman — APPROVED** [review]

**Comment by Errant-4** [comment]
This is nice, thank you for your contribution

**Comment by Errant-4** [comment]
As an aside, I found it weird that some (light_rifle.rsi, magnum.rsi, caseless_rifle.rsi) of these have very clearly "4 quadrants of fill" but go from 1 missing to 3 missing. But it seems this has nothing to do with the configuration in this PR, there isn't even a "2 missing" sprite for those boxes. 
I can only assume it was added like this back in Space station 13 because they did not want those boxes to have so many states of depletion?

**Comment by Everturning** [comment]
danke

**Pull request merged**
