### PR TITLE
artifact extract tweaks

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- make the button green since bozos still think extracting is bad because red
- change every destroy reference to be Extract

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
can you either increase or decrease the distance between the extract button and the other 3? The amount is like right in the middle and it bugs me.

**Comment by deltanedas** [comment]
> can you either increase or decrease the distance between the extract button and the other 3? The amount is like right in the middle and it bugs me.

done

**Comment by deltanedas** [comment]
@EmoGarbage404 i died pls restart

**Review by EmoGarbage404 — APPROVED** [review]
test fails are wrong but your heart is true

**Comment by deltanedas** [comment]
@EmoGarbage404 merg

**Pull request merged**
