### PR TITLE
Gave Chance for Revs to Survival

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I gave the chance for Revs to Survival
## Why / Balance

Revs was removed Pending Rework then put back. I want to obliterate it pending rework and the only way for it is currently to be admeme intervention .
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed Revs From Secret

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Not looking to remove it at this time.

**Comment by FungiFellow** [comment]
> Not looking to remove it at this time.

Can you tell me why?

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/25704 nothing has changed since then.

**Comment by FungiFellow** [comment]
> #25704 nothing has changed since then.

Mind if I make it even rarer then?

**Comment by FungiFellow** [comment]
> beforehand it was almost as prevalent as traitor so a very clear meta was defined

This is what you said on the Reenabling it. A meta is already defined Revs is so dogshit currently. Revs just powergame and kill RD or QM, or just hold ATS and there's just about 0 counter, Exofab can make too many flashes for cheap.

**Pull request closed without merging**
