### PR TITLE
Hydroglycerin, a disease that fills you with Potassium

### PR DESCRIPTION
**Pull request by Interrobang01**
## About the PR 
Decided to play around with the disease system and made this. Maybe it's good enough to go in-game, who knows?
Obtained only via artifacts (and admemes but whatever)

Features of disease include:

- Spaca resistance of 0.15 (really high and i should probably lower it, what do you think?)
- Probability of 0.1 to fill you with 15u of Potassium (faster than you can metabolize)
- Probability of 0.1 to reduce your thirst satiation by 20 points (you get thirstier) (this is a new disease effect i stole from the chemistry one)
- You cough to spread it (probability 0.01)
- It gives you two popups (probability 0.03 each):
- - disease-thirst = You feel unbearably thirsty. (Signify that thirst is draining rapidly)
- - disease-hydrophobia = You panic at the thought of water. (AKA Hydrophobia, there is probably a better sentence to use here)
- Cured by drinking water -- but it only really works if the water doesn't react with the potassium in your stomach...
- Super unbalanced! Yay!

Why: i dunno, felt like it

**Screenshots**

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Needs a way to be acquired in game

**Comment by Interrobang01** [comment]
> Needs a way to be acquired in game

eh, fine, i'll do that in a bit
would letting artifacts give it to you work?

**Comment by Interrobang01** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

:\

**Comment by mirrorcult** [comment]
i kinda like this in concept

**Comment by PixelTheKermit** [comment]
The potassium bombing incidents all over again :mistaken:

**Comment by Interrobang01** [comment]
Closing because tbh this is a low effort PR and I don't want to work on it, revive if you want

**Pull request closed without merging**
