### PR TITLE
Particle Accelerator fixed

### PR DESCRIPTION
**Pull request by VlaDOS1408**
Subdivision of https://github.com/space-wizards/space-station-14/pull/33632 PR

## About the PR

I changed a little bit of everything and now in Russian localization, the menu does not look like after bombing

### Before

image

### After
UIUpdate_PA

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by MilenVolf** [comment]
I don't think it needs Changelog. It's not player facing

**Comment by VlaDOS1408** [comment]
> I don't think it needs Changelog. It's not player facing

Are you sure about this?
image

**Comment by MilenVolf** [comment]
> > I don't think it needs Changelog. It's not player facing
> 
> Are you sure about this? image

Yes, I'm sure about this. We don't have special changelog for this kind of things, so CL is not needed here.
This information will mean nothing to a regular English-speaking player

**Comment by VlaDOS1408** [comment]
> > > I don't think it needs Changelog. It's not player facing
> > 
> > 
> > Are you sure about this? image
> 
> We do not have a Russian playerbase directly. Downstreams, if they are effected by this, can write changelog entries themselves.

ok

**Comment by TheShuEd** [comment]
Due to the author being banned from the repository, we will be closing this PR. Other contributors may continue the work by opening up a new PR. Should the author successfully appeal the ban, the PR may be re-opened.

**Pull request closed without merging**
