### PR TITLE
Station ai features

### PR DESCRIPTION
**Pull request by de0rix**
## About the PR
Station AI gets new features and a little bit more flushed out for the player.

### Features additions/changes:
Added a bunch of features to the station AI:
  - Added door electrification (with animation) and setting emergency access to radial actions menu
  - Added power monitor, crew manifest and announcement console UIs as actions
  - Added admin logging for all door radial actions

Changed action icons of the station AI, as well as station announcement header and color if announcement
made from console UI in actions.

## Why / Balance

Station AI is now can stand for itself, be useful in zombie scenario.
It is now much more convenient to check jobs with manifest.
Emac can be really useful in some scenarios, e.g. providing permanent public access to
some earlier restricted area.

## Technical details

Moved ElectrifiedComponent from Content.Server.Electrocution.Components to
Content.Shared.Electrocution and made its "bool Enabled" field AutoNetworkedField.
Added CrewManifestBUI, made from ground up; server StationAiSystem.Airlock
Changed a lot SharedStationAiSystem.Airlock, client StationAiSystem.Airlock, server CrewManifestSystem
Changed Client DoorSystem to handle overlay animations on doors

## Media
All UIs and changes shown in one picture:
All in one

Small bug with popup message when trying set emac to the door that AI does not have access to:
Small no access bug

New action icon for power monitor:
power_monitor

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
No breaking changes.

**Changelog**
:cl:
- add: Station AI now has power monitor, manifest and announcement console builtin, as well as more actions with doors.
- tweak: Changed station AI actions icons.
ADMIN:
- add: Added logging for station AI door actions.

### CODE REVIEW

**Comment by de0rix** [comment]
OK, I've just found out about this PR: https://github.com/space-wizards/space-station-14/pull/32012, that adds the same  actions with the doors and does it much better! So I probably should remove all my changes to door actions radial menu, right?

**Comment by slarticodefast** [comment]
The announcement console is also being added in this PR #31852

**Comment by de0rix** [comment]
Well, thanks guys for all the feedback! I'm sorry that I didn't check other PRs before making mine... It just took for me too long to get started and write all of that code, so a lot things changed on the repo.

I'll close this PR and make a new one, that will only feature a crew manifest and power monitor actions, i.e. things that others did not do at the time. I would love if someone provided some feedback on my code in general, but I value your time and so don't expect much :3

**Comment by de0rix** [comment]
Well, closing PR. Will make a new one only featuring things that other PRs don't.

**Pull request closed without merging**
