### PR TITLE
BZ gas

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

Added BZ gas. Made by mixing N2O and plasma under low pressures. When inhaled, makes non slimes cough, deals 5 asphyxiation and 2.5 poison (not scalable), also gives short-term seeing rainbows effect (will be gone as soon as you stop inhaling it), acts as a sleeping agent for slimes (basically n2o but for slime people).

## Why / Balance

As a base for future reactions and for putting slimes to sleep, which is useful in an outbreak [(media)](https://github.com/space-wizards/space-station-14/assets/113782077/0c50da44-94cb-4720-b2e2-192d4d3a94df).

## Technical details

Uses [this (first row)](https://i.redd.it/rl46009i1bb61.png) as the main formula for BZ formation.

## Media

**BZ synthesis**
https://github.com/space-wizards/space-station-14/assets/113782077/b9ad1063-67b2-425d-b887-2bcdb0fa8d72
**BZ effects on slimes**
https://github.com/space-wizards/space-station-14/assets/113782077/a065bb47-2db7-4949-a8e5-9a5caaa50ef3
**BS effects on any other race**
https://github.com/space-wizards/space-station-14/assets/113782077/e2bf1fcd-2a5a-4706-9fb4-7e8cb2992a06

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

🆑
- add: Added BZ - a slime person sleeping agent and overall a toxic gas, which is made by mixing N2O and plasma under low pressures.

### CODE REVIEW

**Comment by UbaserB** [comment]
BZ has nearly the same effects as frezon, as in the damage and hallucinogenic properties

**Comment by whateverusername0** [comment]
> BZ has nearly the same effects as frezon, as in the damage and hallucinogenic properties

chinese frezon

**Comment by whateverusername0** [comment]
> BZ has nearly the same effects as frezon, as in the damage and hallucinogenic properties

i want BZ to be the chinese frezon - easier to make, more powerful and deadly.
deadly because then you would consider twice before inhaling it, giving off a better effect since it's more dangerous than frezon.
also dealing with slimes as a bonus, since n2o can't put them to sleep 😀

**Comment by qwerltaz** [comment]
You could make humans cough when inhaling. Makes a lot of sense and a nice touch. And it could just make people drunk for a very short time (if the current drunk system allows that) or something, instead of drunk and hallucinating, something to consider.
Does the max temperature 100000 have a reason in n2o decomposition? Instead of no limit.
And if its easier to make, maybe it should be a little less deadly? Like just the toxin, and maybe something like asphyxiation. Cellular is pretty bad.

**Comment by whateverusername0** [comment]
> You could make humans cough when inhaling.
maybe it should be a little less deadly? Like just the toxin, and maybe something like asphyxiation. Cellular is pretty bad.

Yeah makes sense

> Does the max temperature 100000 have a reason in n2o decomposition? Instead of no limit. And if its easier to make, maybe it should be a little less deadly? Like just the toxin, and maybe something like asphyxiation. Cellular is pretty bad.

I copied it from /tg station, I guess they put it as high as possible to remove the limit

**Comment by deltanedas** [comment]
cl doesnt work and should probably be condensed

**Comment by whateverusername0** [comment]
> cl doesnt work and should probably be condensed

what's cl?

**Comment by deltanedas** [comment]
changelog
you are missing `-` before each add and the :cl: emoji before them all
also nobody reading allat

**Comment by whateverusername0** [comment]
damn

**Comment by Partmedia** [comment]
Hi there, thanks for the PR. This sounds fun and interesting and we can all help take a look at balance once the build is working. Would you be willing to split up the nitrous oxide decomposition into a separate PR? That way we can get that in without having it blocked by BZ balance discussions.

**Comment by mirrorcult** [comment]
not a fan of bz conceptually, its effects are already done better by other gases

**Comment by whateverusername0** [comment]
> Would you be willing to split up the nitrous oxide decomposition into a separate PR?

Sorry, i'm not really strong in git, idk how to make commits switch branches, and there's constants for both n2o n bz defined in a single commit, which i also dunno how to split.

**Comment by whateverusername0** [comment]
oh nice, it now works

**Comment by whateverusername0** [comment]
so?

**Comment by Partmedia** [comment]
> so?

Could you respond to @mirrorcult 's comments? Particularly those about BZ not being distinct enough from frezon to warrant being its own gas. Can you think of other things that BZ could do/be used in so that it is different from frezon?

**Comment by whateverusername0** [comment]
> Can you think of other things that BZ could do/be used in so that it is different from frezon?
It already puts slimes to sleep, which no other gas does, and makes people cough 🤷‍♂️
In ss13 it's also used in freon formation instead of tritium. (actually, lemme make that rq)

**Comment by whateverusername0** [comment]
could also be used in healium production (https://tgstation13.org/wiki/Guide_to_Atmospherics#Healium)

**Comment by Partmedia** [comment]
As you've probably noticed, the functions of BZ have been sort of taken over by tritium and frezon here. I don't think a direct copy would be received well here.

I do like the nitrous decomposition reaction, which is why I asked if you would be willing to split it out into a separate PR or make this PR primarily about nitrous. Perhaps you could also consider adding a nitrous synthesis reaction involving miasma and oxygen forming nitrous and water?

**Comment by whateverusername0** [comment]
> which is why I asked if you would be willing to split it out into a separate PR or make this PR primarily about nitrous

Figured it out and moved to a separate pr https://github.com/space-wizards/space-station-14/pull/22738

> nitrous synthesis reaction involving miasma and oxygen forming nitrous and water

Or use BZ 😆

I don't really see any logic in using miasma and oxygen to form n2o n water.
BZ afaik in ss13 is used as a catalyst or such to produce other gases, so it'd be weird to use anything else, might be just me 🤷‍♂️

**Comment by Partmedia** [comment]
Because if you assume miasma is something vaguely like ammonia:

image

Which is a reaction that happens to really exist, without any catalysts.

It's probably going to take more discussion about what would make BZ *different* from the gases that already exist. But the nitrous changes are very welcome since it would make it synthesizable from existing gases.

**Comment by whateverusername0** [comment]
idk who would actually collect miasma in a tank and use it to produce n2o and water vapor, _would probably_ lead to mass grave miasma factories, but sure why not 😆

**Comment by Partmedia** [comment]
> > involving miasma and oxygen forming nitrous and water
> 
> come to think of it, wouldn't it react automatically with the air and form vapor bath sleeping houses after somebody dies?

I think a minimum temperature requirement for this reaction to happen should alleviate this issue.

**Comment by whateverusername0** [comment]
updated pr. review, any1?

**Comment by Partmedia** [comment]
Sorry for the delay getting feedback to you on this PR. There still remains the issue that BZ gas isn't distinct enough from the gases that already exist to justify adding a new gas. Perhaps you would be willing to discuss this more on Discord for how to proceed?

**Comment by whateverusername0** [comment]
hmu

**Comment by Partmedia** [comment]
Thank you for your PR. Unfortunately, I'm opting to close it because as discussed here and on Discord, BZ is not distinct enough from gases that already exist in game, e.g. frezon. Please feel free to re-open if you want to discuss other changes that could make it a good candidate to add to the upstream game.

**Pull request closed without merging**
