### PR TITLE
Revert "Fix turned off thrusters consume power"

### PR DESCRIPTION
**Pull request by metalgearsloth**
Reverts space-wizards/space-station-14#26690

### CODE REVIEW

**Comment by lzk228** [comment]
i still dont understand what is the problem

**Comment by metalgearsloth** [comment]
> i still dont understand what is the problem

https://github.com/space-wizards/space-station-14/issues/27754

**Comment by lzk228** [comment]
so maybe the problem is they consume too much power, or power flickering issue in general? because i suppose other power receivers can flicker

**Comment by metalgearsloth** [comment]
The better solution is making it handle draw properly and still show the sprite but just full-sending power or not will just cause this.

**Comment by deltanedas** [comment]
it does this if you go from powered to no power at all they keep flickering sound and sprite which is bad, its not just if there isnt enough power theres none at all

**Pull request merged**
