### PR TITLE
Disposable turret for uplink

### PR DESCRIPTION
**Pull request by Arendian**
## About the PR

Adds the disposable turret to the uplink exclusive to engineer, atmos technician and scientist traitors.
The original ballistic turret has 300 health and shoots 6 .30 bullets(19 damage) per second, the disposable one added in this PR has 100 health and shoots 2.5 .35 bullets(16 damage) per second. 

**Media**

https://github.com/space-wizards/space-station-14/assets/137322659/cad535c1-7947-42b5-b086-870f7ecca10b

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- add: The Syndicate has found a way to compress their ballistic turrets into a toolbox, reducing it's performance in the process. Atmos technician, station engineer and scientist traitors can now purchase the disposable turret from the uplink.

### CODE REVIEW

**Comment by Equivocateur** [comment]
20 tc at the least I beg

**Comment by Arendian** [comment]
> 20 tc at the least I beg

it only has 100 health needing only 7 bullets or 5 crowbar wideswings to be destroyed, you can also kill it without it even shooting at you since it's firing range is a bit lower than you can see yourself.

**Comment by Equivocateur** [comment]
> > 20 tc at the least I beg
> 
> it only has 100 health needing only 7 bullets or 5 crowbar wideswings to be destroyed, you can also kill it without it even shooting at you since it's firing range is a bit lower than you can see yourself.

I respect the hustle of turning space station 14 into a nightmarish hellscape but you can just easily plop down multiple layers of railings in the main hallway and turret in the middle and not grayshirt will be able to reach it without seeing god in 2.5 seconds of exposure to the turret. Putting it down necessitates a security officer to get the guns or for hos to show up and blast it and be half-dead in the process of 1v1'ing the turrent.

**Comment by Emisse** [comment]
i think the price point is fine

**Comment by Emisse** [comment]
id maybe increase price for nukies tho

**Comment by Arendian** [comment]
> I respect the hustle of turning space station 14 into a nightmarish hellscape but you can just easily plop down multiple layers of railings in the main hallway and turret in the middle and no grayshirt will be able to reach it without seeing god in 2.5 seconds of exposure to the turret

If people are unable to get close to it they can just walk away, it's not going to chase them or anything. They can then call a security officer to come and dispose of it.

**Comment by Equivocateur** [comment]
> i think the price point is fine

Hey look buddy, I'm an engineer. That means I solve problems, not problems like "What is beauty?" Because that would fall within the purview of your conundrums of philosophy. I solve practical problems, for instance: how am I going to turn half of the station into a killzone? The answer, use a gun, and if that don't work... Use more gun. Take for instance this heavy caliber tripod mounted lil' old number designed by me, built by me, and you best hope... Not pointed at you.

**Comment by Arendian** [comment]
> id maybe increase price for nukies tho

It's exclusive to engineers and atmos technicians so nukies can't buy it.

**Comment by Equivocateur** [comment]
> atmos technicians

I have some [bad news](https://github.com/space-wizards/space-station-14/blob/356b1a597ab61bb54f76aef54c167c1296c08a4f/Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml#L13).

**Comment by Arendian** [comment]
> > atmos technicians
> 
> I have some [bad news](https://github.com/space-wizards/space-station-14/blob/356b1a597ab61bb54f76aef54c167c1296c08a4f/Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml#L13).

Atmos technicians can kill renault if they want the turret

**Comment by deltanedas** [comment]
as if engi syndies werent strong enough, now they have budget version of fishtrap

**Comment by Arendian** [comment]
> as if engi syndies werent strong enough, now they have budget version of fishtrap

6 fish for 12 tc are arguably  still better at fish traps than the turret, the turret has a higher ttk and less effective health. The fish are also stealthier compared to the shooting of a gun.

**Comment by deltanedas** [comment]
,ignores that fishtrap isnt possible since fish will break out of your trap

**Comment by Arendian** [comment]
> ,ignores that fishtrap isnt possible since fish will break out of your trap

From my testing they only try to break out if the room is too small or when they see someone on the other side of the window.

**Comment by lzk228** [comment]
ah yes, a lot more rdm on lrp servers

**Comment by retequizzle** [comment]
would like to see a slightly slower fire rate (2.5) on them and a reduction of the ammo capacity from 150 to like 100 or 120 at most, then the price point would be fine. it'd still take 4-5 rounds to kill an unprotected target after a few seconds of bleedout, and affords them maybe a half second more of reaction time to get out of the way before it becomes skill issue.

also hard no on nukies having any access to this at 12 TC, would prefer no access at all but nukies getting this should be at least double the price if it's being considered.

**Comment by Emisse** [comment]
maybe include sci in the whitelist since they have robotics

**Comment by Arendian** [comment]
> maybe include sci in the whitelist since they have robotics

sounds logical to me

**Comment by Flareguy** [comment]
Considering the nerfed firerate, you'll probably want to make it cost less (8tc, perhaps?)
In SS13 this item was basically never used and afaik had similar stats to what this does now. Take that with a grain of salt though - it's so rare that I honestly don't even know how effective the item is at killing.

**Comment by Interrobang01** [comment]
I don't think this should be job exclusive.

All the other job exclusive items are extremely specific to their jobs, whereas the turret has no relation to any of the jobs within the bounds of the game.

**Comment by Arendian** [comment]
> Considering the nerfed firerate, you'll probably want to make it cost less (8tc, perhaps?) In SS13 this item was basically never used and afaik had similar stats to what this does now. Take that with a grain of salt though - it's so rarely seen that I honestly don't even know how effective the turret actually is.

The turret predicts peoples movement perfectly, so if people just try to dodge it by weaving around it will still hit every shot. Stopping for a short moment after every shot the turret makes will make it miss you since it predicted you to keep running. With the current firerate it will crit an unarmored person in +/- 3 seconds + the time it takes for it to target you(up to 1 second depending on where it was aiming the moment you walked into it's firing area). This is if someone walks into it's targeting area without trying to look for cover or just walking back out of the area, most people will just run back when they notice the turret and get hit by at most 1 or 2 bullets.

Making it 8 tc makes people able to buy  2 (or 3 with renault tc) of them, making their dps almost equal to or even better(if 3) than a normal sentry. With security officers now always having a gun on them they are easily disposed of though so it might still be an option to consider, maybe the health should be lowered more so they are even more fragile if people agree with the lower tc cost.
Currently they are also really only a threat in large open areas because you can just run around any nearby corner/walk through a door and close it behind you to stop it shooting at you, this can be easily done in the time it takes for the turret to kill someone. 
A few additional weakpoints:
- If near a corner you can just walk around the corner and magdump it before it's able to shoot.
- In large open areas you can just snipe it with a gun without it shooting back at you.

Considering all of the above the turret is an item that only kills reliably if the following points are true: 

1. You placed it in a decent spot  
2. The targets decide to stay in the targeting area without looking for cover
3. The targets don't have a gun or armor
4. The targets don't use human wave tactics to rush it down

With it having so many weaknesses I do think that it's currently only viable as a way to keep nosy crew out of a general area until someone with a gun comes around or people rush it down with numbers. I have no idea exactly how viable it is at this in a real situation though.

**Comment by Arendian** [comment]
> I don't think this should be job exclusive.
> 
> All the other job exclusive items are extremely specific to their jobs, whereas the turret has no relation to any of the jobs within the bounds of the game.

You could see it as only engineers and scientists knowing how to build a turret.

**Comment by deltanedas** [comment]
they aren't building a turret, the syndicate is

also if this was available to tiders there would be massive shittery of just turreting the bar roundstart

**Pull request merged**
