### PR TITLE
let borgs wear hat

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

## Why / Balance
its time to get festive

## Technical details
no

## Media
dapper

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Borgs can wear hats now. Time to get festive!

### CODE REVIEW

**Comment by muburu** [comment]
this is the kind of stuff we desperately need

**Comment by deltanedas** [comment]
also this may need a whitelist since it could be bad for powergaming borgs to instantly get helmet for x% resistance

**Comment by MACMAN2003** [comment]
finally, borgs can now participate in tf2 hat economy

**Comment by mirrorcult** [comment]
you can offset by making a new inventory template see how drone does it 
image

**Comment by mirrorcult** [comment]
how does it look on the different borg chassis

**Comment by deltanedas** [comment]
:trollface: edit time

**Comment by deltanedas** [comment]
better

**Comment by mirrorcult** [comment]
looks wonky but whatever. main issue is with borgs wearing helmets and stuff but honestly i dont care that much lol

**Comment by deltanedas** [comment]
would be very bad if batong module existed then validhunter borgs would always wear helmet but rn there isnt much reason to, drip is far better

**Comment by DogZeroX** [comment]
Thing is it has to account for the future alternative skins whenever we have them

**Comment by deltanedas** [comment]
> alternative skins

borg loadout???

**Review by mirrorcult — APPROVED** [review]

**Comment by brainfood1183** [comment]
> you can offset by making a new inventory template see how drone does it image

can we use this to offset the inhand sprites for monkeys?

**Comment by deltanedas** [comment]
doesnt seem to use inventory layout for hand

**Comment by Aexxie** [comment]
DELTAAAAAAAA
image
ITS OFFSET FIX IT

**Comment by deltanedas** [comment]
its because (most) borgs have even width head but humans have odd width

**Comment by Aexxie** [comment]
DELTAAAAAAAA
image
ITS OFFSET FIX IT

**Comment by Aexxie** [comment]
> its because (most) borgs have even width head but humans have odd width

.5 px offset or resprite this is unacceptable

**Comment by deltanedas** [comment]
nfi if half pixel offsets are a thing but wyci

**Pull request merged**
