### PR TITLE
Contraband Review Pass - The Threequel

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

More items getting contra recategorization. I have tested the items that have new BaseParents and they work as expected.

The next thing I would like to tackle are all manners of explosives, but I would REALLY like to get my cluster grenade refactor merged before I do it so I'm not suffering through merge conflict hell for another three months.

## Why / Balance

Incorrect categorization will lead to the downfall of public morals

## Technical details

- ContrabandComponent has AutoGenerateComponentState and AutoNetworkedFields for the sake of making energy pens show as contra when toggled predicted
- Ninja gear is major contraband
- Combat gloves are security/engineering restricted
- Syndie hand flag is syndie contra
- Syndicate codeword papers are syndie contra (eat your damn papers, stop throwing them around)
- CentComm pen is no longer syndicate contra due to better parenting
- Practice laser rifles and disablers are no longer security restricted (laser taggers rejoice)
- AKMS is major contra
- All energy weapons now have a generic abstract parent that they use
- Energy dagger pens only show as contra when toggled on
- All giant ass sword type weapons have been upgraded from minor contra to major contra

## Media

https://github.com/user-attachments/assets/89b96cd7-2249-4180-87ba-ff479108c29a

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by FinnishPaladin** [comment]
What about nukie plushies?
Them being classified as "Highly illegal Syndicate contraband" doesn't feel right to me.



(Picture taken from the Discord server.)

**Comment by Plykiya** [comment]
> What about nukie plushies? Them being classified as "Highly illegal Syndicate contraband" doesn't feel right to me.
> 
> 
> 
> (Picture taken from the Discord server.)

EVIL
KILL IT

**Comment by bruhmogus** [comment]
> What about nukie plushies? Them being classified as "highly illegal Syndicate contraband" doesn't feel right to me.
> 
> 
> 
> (Picture taken from the Discord server.)

yeah, uh, this should definitely be removed from the highly illegal list because it can spawn in the _captain's locker_

**Comment by UbaserB** [comment]
the nukie plushie should definitely not be contraband.

**Comment by Plykiya** [comment]
> the nukie plushie should definitely not be contraband.

the plushie bundle bag is contra, something inside the plushie bundle's gotta be contra as well

**Comment by EmoGarbage404** [comment]
it doesn't make sense for the nukie plush to be contra because it doesn't do anything bad and it's also available on station. If there was a piece of paper in a bundle you wouldn't mark that as contraband either.

**Comment by Plykiya** [comment]
> it doesn't make sense for the nukie plush to be contra because it doesn't do anything bad and it's also available on station. If there was a piece of paper in a bundle you wouldn't mark that as contraband either.

if that's in reference to the syndicate codeword paper, the paper's in-game name is quite literally "syndicate codeword", not even just a generic paper

**Comment by chavonadelal** [comment]
You should be very careful with this signature. Where is the line when there is no need for it? I even found it on a portable flash.... Why?... In my opinion, it should only be added to the things of the antagonists, high-risk items and, possibly, some kind of explosives. That is, potentially HIGHLY illegal things.  Expanding this list will simply lead to confusion and turn this phrase into a noise that players will not attach much importance to. We're not going to add it to conventional weapons, is it clear to everyone that it's illegal?... And if someone doesn't understand this, then I'm afraid this phrase won't help them.

**Comment by HelpTheSteak** [comment]
I'm not sure if this is brought up anywhere but is the syndie fire axe supposed to be stealth like chameleon items since it has the same exact contraband status as the normal fireaxe?

**Review by slarticodefast — APPROVED** [review]

**Pull request merged**
