### PR TITLE
The Fatphobic PR (for real this time)

### PR DESCRIPTION
**Pull request by Ranger6012**
## About the PR 
Cholesterol now exists, the more unhealthy foods have it. If you have too much cholesterol you will suffer a heart attack, dealing asphyxiation damage. Burgers, pizza, donk pockets, and vending machine food all have cholesterol.

**Changelog**

:cl:
- add: Added cholesterol to certain foods. Having too much cholesterol in your system at once will give you a heart attack. 
- remove: Removed everything you love and hold dear because I hate you specifically

### CODE REVIEW

**Comment by Ranger6012** [comment]
> mean, but based

That was my nickname in high school
...
wait no I think it was stupid

**Comment by liltenhead** [comment]
Just gib me on round start, I'm ruined now.

**Review by moonheart08 — CHANGES_REQUESTED** [review]
In the future **please** do not do large PRs with webedit.

**Comment by Elijahrane** [comment]
Can you actually reasonably eat fast enough to reach the reagent threshold? You may want to change the metabolism rate.

**Comment by Just-a-Unity-Dev** [comment]
tfw your dying of hunger so you eat a lot of food and start dying of a heart attack

**Comment by Elijahrane** [comment]
You can just move the metabolism to the something that metabolizes slower, look at what alcohol does

**Pull request closed without merging**
