### PR TITLE
fix gateway destinations

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
apparently gateway was requiring that destinations go into pvs range before showing up

## Why / Balance
bug

## Technical details
it was turning things into entityuids then back into netentities for no reason i think thats why it was being sus, just removed all that made it pure netentities

## Media
work

yep its outside of pvs range

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
@TheShuEd youll need to merge this downstream

**Comment by TheShuEd** [comment]
@deltanedas Thank you very much for the quick fix!

**Comment by TheShuEd** [comment]
@deltanedas 
There is another question about portals. It's not so critical anymore, but we haven't found a way to implement it. The Access Reader component does not work together with the gateway interface, it seems. We tried to limit the possibility of interacting with portals only for command, since ordinary passengers often confuse directions... But, it had no effect.

**Comment by deltanedas** [comment]
the code for selecting destinations doesnt check for access readers guess i can implement checking it too...

**Pull request merged**
