### PR TITLE
HOS Hardsuit Helmet Resprite

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Changes the HOS helmet to be more readable. Also removes unnecessary held sprites for helmets.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: Changed HOS hardsuit helmet to be more readable

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
The side states are difficult to read.

**Comment by Alekshhh** [comment]
I stuck faithful to the old one just made it not as unreadable. could make a new one entirely

**Comment by mirrorcult** [comment]
these side states are less readable imo

**Review by keronshb — CHANGES_REQUESTED** [review]
@Alekshhh please change the sprite so the side states are more readable

**Comment by Alekshhh** [comment]
no

**Pull request closed without merging**
