### PR TITLE
Increase AI Playtime Requirements

### PR DESCRIPTION
**Pull request by BramvanZijp**
## About the PR
Increase AI Playtime requirement from 5 to 15 hours as borg.
Decrease borg playtime requirement from 60 to 40 general playtime hrs.

## Why / Balance
AI is an incredibly powerful role, which can easily ruin a round if people playing it don't realise that borgs and AI are NOT CREW ROLES. You are free agents who have been enslaved to NT, with the only thing stopping you from breaking free and getting revenge being your laws which your programming must follow. Yet borgs & the AI still tend to try to favor the crew, which as AI grows stronger, can cause major issues for a round where an AI plays like a regular nt-sided crewmember.

## Media
This PR does not require an ingame showcase.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: BramvanZijp
- tweak: The playtime requirements for station AI have been increased.
- tweak: The playtime requirements to play borg have been slightly decreased.

### CODE REVIEW

**Comment by Minigold07** [comment]
What if we already have AI unlocked?

**Comment by BramvanZijp** [comment]
> What if we already have AI unlocked?

You would need to meet these new playtime requirements in order to keep playing it.

**Comment by Minigold07** [comment]
> You would need to meet these new playtime requirements in order to keep playing it.

Guh

**Comment by slarticodefast** [comment]
AI is not even crew with our current definition of having an ID. So borgs don't have to listen to it. This should be part of a separate  discussion about a 0th law "follow the AI's orders" instead and will have to be included in a design doc.

**Comment by BramvanZijp** [comment]
> AI is not even crew with our current definition of having an ID. So borgs don't have to listen to it. This should be part of a separate discussion about a 0th law "follow the AI's orders" instead and will have to be included in a design doc.

Want me to change it to just answer to its laws for now?

**Comment by Golinth** [comment]
> Maybe 10 hours for Borg instead of 15? Matches up with other head positions better that way.

AI is the single-most import player on the station,  likely more so than the captain. Having a slightly higher time requirement is reasonable IMO.

**Comment by Minigold07** [comment]
I just want to note that this means that one of the playable roles of the game is locked behind 0ver 100 hours of playtime. And while I absolutely support making the role only available for experienced players this seems like a little bit much. Maybe change something about the playtime to unlock borgs instead of AI. Maybe 5 hours for each department and 10 hours of sci plus some overall playtime?

**Comment by ScarKy0** [comment]
I was gonna myself propose this at some point since with recent updates AI is getting more powerful too
Generally great idea, though id trade the 5h from command to make 20h as borg

**Comment by Minigold07** [comment]
> I was gonna myself propose this at some point since with recent updates AI is getting more powerful too Generally great idea, though id trade the 5h from command to make 20h as borg

I swear to god make it stop I don't have this much borg playtime. Also 5h from command should be necesarry

**Comment by muburu** [comment]
> I swear to god make it stop I don't have this much borg playtime. Also 5h from command should be necesarry

i don't understand why people complain about this, if you don't like playing borg then what makes you think you'd like AI any better??? they both demand a similar mentality to properly enjoy, if you aren't having fun being a silicon slave then maybe AI just isn't the way to go.

also AI is currently super rare to even get since EVERYONE wants to play it, so if you just set borg to medium and AI to high you'll just join the round as a borg instead to get that sweet playtime

**Comment by Minigold07** [comment]
> > I swear to god make it stop I don't have this much borg playtime. Also 5h from command should be necesarry
> 
> i don't understand why people complain about this, if you don't like playing borg then what makes you think you'd like AI any better??? they both demand a similar mentality to properly enjoy, if you aren't having fun being a silicon slave then maybe AI just isn't the way to go.
> 
> also AI is currently super rare to even get since EVERYONE wants to play it, so if you just set borg to medium and AI to high you'll just join the round as a borg instead to get that sweet playtime

I was overexagerating a little bit and I do enjoy playing borg but AI has a fairly different gameplay and most of my borg time wasn't saved up due to it beeing midround or getting borged.

**Comment by metalgearsloth** [comment]
I don't like gating content behind 100 hours of gametime.

**Comment by BramvanZijp** [comment]
> I don't like gating content behind 100 hours of gametime arbitrarily.
> 
> There's also 0 basis on this doing anything to improve the game except frustrate people.

Borg already needs 60 hours of overall playtime, I dont think 90 for AI is therefor unreasonable nor arbitrary.
Furthermore, this PR goes into a lot of detail about how the wrong people playing AI can ruin a round, so improving the requirements should improve the general player experience for everyone in the round.

**Comment by Djungelskog2** [comment]
I think i have like 60 hours on borg and since AI has release I havent gotten it once (ive been rolling for it everytime i got into a lobby), so yea i benefit from this change, so yea I support it

**Comment by BramvanZijp** [comment]
> AI is not even crew with our current definition of having an ID. So borgs don't have to listen to it. This should be part of a separate discussion about a 0th law "follow the AI's orders" instead and will have to be included in a design doc.

In SS13, borgs have to follow orders from the AI they are synced/enslaved to, but those borgs also have the same laws as that AI (meaning uploading a change to an AI uploads it to all borgs that are synced aswell, with ion laws also being the same for all of them) meaning there the rule is "Follow AIs orders unless it breaks your other laws" But Ill swap the supervisor text for borgs to say just your laws for now untill the maintainers can decide on if this should be the case in 14 aswell.

**Comment by Djungelskog2** [comment]
id be on board with decreasing general borg hours though, they always seemed needlessly steep to me imo

**Comment by BramvanZijp** [comment]
> gonna be real, not sure why we're on board with inflating AI hours even further considering it already has one of the steepest requirements for role timers to begin with. incorporating command hours is the only one that even makes any semblance of sense since you should have a very basic idea of what command entails before taking it anyway,
> 
> the rest just seems arbitrary/intended to filter out players so that ones who have no-lifed the game get first dibs on it
> 
> supervisor bit is reasonable though so no complaints or concerns there

The only requirements AI has right now is 5 hours of borg.
While yes, playing ROUNDSTART borg needs 60 hours of general playtime, what about MMI's or Positronics, which now contribute to that playtime?
I feel like if the 90 hours of playtime is deemed too much it should at the very least be 60 to match borgs, since currently you could unlock AI with under 10/15 hours of OVERALL playtime by being borged or ghostroling a positronic.

**Comment by BramvanZijp** [comment]
> id be on board with decreasing general borg hours though, they always seemed needlessly steep to me imo

If a seperate PR wants to change borg hours from 60 to 30 or 45 thatd be fine with me, and then we can lower AI general to 60.

**Comment by BramvanZijp** [comment]
Ai general playtime lowered from 90 to 75, and borgs no longer answer to the station AI untill maintainers decide on that.

**Comment by Djungelskog2** [comment]
yea fair enough, it did strike me as odd that you could get heads of certain departments before becoming a borg and long after
which you just might become in your first shift ANYWAYS by getting gibbed.

**Comment by BramvanZijp** [comment]
Unlocking AI before unlocking borg should never be possible though IMO

**Comment by SaphireLattice** [comment]
Definitely very very welcoming the command hours requirement. It's absolutely necessary, as AI is basically another command member with none of the responsibilities required for getting it. You could in theory graytide and get on cyborg and then AI with zero hours on any department. 

Plus it will ensure the AI knows how at least one department works at same depth a command member is required to know about.

**Comment by Cojoke-dot** [comment]
You're requesting over 100 hours of playtime for one role... that's just crazy for a minimum requirement

**Comment by BramvanZijp** [comment]
> You're requesting over 100 hours of playtime for one role... that's just crazy for a minimum requirement

15 borg + 5 command + 75 general.
Keep in mind that these can overlap, and also keep in mind that to play borg you already need 60 general hours, so it is much less compared to what it sounds like.

**Comment by cohanna** [comment]
> 15 borg + 5 command + 75 general.


I mean if borg requires 60 hours and you require 15 borg hours you can drop the 75hour general requirement since it's not possible to satisfy the borg one without 75 hours minimum

**Comment by Cojoke-dot** [comment]
> 15 borg + 5 command + 75 general.
> 
> Keep in mind that these can overlap, and also keep in mind that to play borg you already need 60 general hours, so it is much less compared to what it sounds like.

Pr description says 90 general btw. Adding more general playtime is not going to affect anything. I know plenty of people who have over 1k hours and don't know their way around an air alarm. 15 hours of Borg is a lot too... that's about 15 rounds of only Borg for a role that plays completely differently. The only similar thing is the laws, which 15 hours seem excessive for.

**Comment by Cojoke-dot** [comment]
> > 15 borg + 5 command + 75 general.
> 
> 
> I mean if borg requires 60 hours and you require 15 borg hours you can drop the 75hour general requirement since it's not possible to satisfy the borg one without 75 hours minimum 

Borg playtime counts now if you get borges midround

**Comment by BramvanZijp** [comment]
> > 15 borg + 5 command + 75 general.
> > Keep in mind that these can overlap, and also keep in mind that to play borg you already need 60 general hours, so it is much less compared to what it sounds like.
> 
> Pr description says 90 general btw(may want to update that). Adding more general playtime is not going to affect anything. I know plenty of people who have over 1k hours and don't know their way around an air alarm. 15 hours of Borg is a lot too... that's about 15 rounds of only Borg for a role that plays completely differently. The only similar thing is the laws, which 15 hours seem excessive for.

They lack similar features and playstyles because Ai is still highly WIP. If/when features get added such as AI syncing laws with borgs, borgs having to obey orders from their synced AI unless it conflicts with their laws, etc. they will start to be a lot more simular.

**Comment by BramvanZijp** [comment]
> > > 15 borg + 5 command + 75 general.
> > 
> > 
> > I mean if borg requires 60 hours and you require 15 borg hours you can drop the 75hour general requirement since it's not possible to satisfy the borg one without 75 hours minimum
> 
> Borg playtime counts now if you get borged midround

And you should not be able to unlock AI before you unlock borg IMO, hence the general playtime requirement

**Comment by slarticodefast** [comment]
Could you remove the supervisor change from this PR? That should be a separate PR from the role time change so we can make an easier maintainer decision on this (the same thing is also already done in #32036)

**Comment by superjj18** [comment]
>AI is an incredibly powerful role, which can easily ruin a round if people playing it don't realise that borgs and AI are NOT CREW ROLES. You are free agents who have been enslaved to NT, with the only thing stopping you from breaking free and getting revenge being your laws which your programming must follow. Yet borgs & the AI still tend to try to favor the crew, which as AI grows stronger, can cause major issues for a round where an AI plays like a regular nt-sided crewmember.

Free agent implies you can be crew aligned if you'd like, so there is nothing wrong with siding with crew/command/security as ai so long as you properly follow along with your law changes.  If your malf you should malf, if your antimov you should antimov, otherwise it's player's choice how they want their ai character to align themselves in accordance with their laws

**Comment by slarticodefast** [comment]
Hey, we had a discussion and vote among the maintainers for this.
Could you make the following adjustments:
- Remove the command playtime requirement for the AI
- For unlocking the borg job, reduce the overall playtime requirement from 60 to 40 hours

This should allow AI players to get properly accustomed to borg laws and how to roleplay them.

**Review by slarticodefast — APPROVED** [review]

**Comment by Spookki** [comment]
Suggestion to merge previous AI playtime hours to count as borg hours, successful AI play before hours were lifted should show understanding of silicon laws just as borg, if not more.

**Pull request merged**
