### PR TITLE
Stimpacks - 100% Webedit Free Edition

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR

@HoidC you can rest now

This PR adds Stimpacks from SS13, as well as 2 new items, Stimkits, and Experimental Stimpacks.

Stimpacks, which cost 8 TC, are a heavily watered down version of the SS13 Stimpack, only granting slight resistance to stuns (3 second reduction, which is barely enough to get back up from a stun baton if the officer is slow with the cuffs), minor movespeed increases (30% increase), and a desperation heal at low health (same amoutn as tricordrazine, minus the poison healing), for 5 minutes. Taking two of them in under 3 minutes causes an overdose, dealing poison damage which the desperation heal does not stop.

Stimkits, which cost 12 TC, are first aid kits with 6 stimulant microinjectors contained inside, which each give 75 seconds of stimulants upon injection. Great for sharing with friends or if you want to control how much stimulant you'll need for a fight.

Experimental Stimpacks, which cost 15 TC and can only be found in nukie uplinks or surplus crates, are an extremely powerful version of Stimpacks that lasts for 200 seconds. The experimental stimulants constantly deal poison damage while metabolizing (1 damage per second), enough to have killed you by poison alone when the timer runs out. If you manage to survive, you'll be faced with 40 seconds of withdrawal where you'll have jitters, stuttering, and random stuns to deal with. But while the chemical is active, you'll have absurdly high runspeed (80% increase, which isn't as bad as it looks since it's impossible to aim a gun while running and you'll occasionally overshoot your melee target), virtual immunity to conventional stun methods (6 second stun reduction, there won't be enought time to cuff you after a stamcrit stun), will rapidly purge lexorin (number one anti nukie poison) and chloral hydrate (bane of tranq shells) from your chemstream, and heal a singificant amount of brute and burn damage every second (4 brute and burn per second, which might seem like a lot but a dedicated assistant with a baseball bat can outpace that healing).

Both types of stimulants will treat narcolepsy and lower hunger and thirst levels while metabolizing.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Stimpacks are now available in the uplink for 8 TC.
- add: Stimkits are now available in the uplink for 12 TC.
- add: Experimental Stimpacks are now available in operative uplinks for 15 TC.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
erroneous test fail is erroneous

**Comment by PixelTheKermit** [comment]
Is this real? I can't believe you wouldn't webedit this!

**Comment by GoodWheatley** [comment]
@moonheart08 the new chems are probably going to break the wiki page in some way, just a heads up

**Comment by AJCM-git** [comment]
lets see if it breaks the wiki

**Pull request merged**
