### PR TITLE
Nerfs the Experimental Research Hardsuit's size

### LINKED ISSUE #27091: RDs hardsuit storage issue
## Description
You can place the RD hardsuit in a tool belt, and its for some reason only 2x2 which is ridiculously small for what it is, it should at the very least be increased to 3x3 or 2x4 just so you can still carry in a bag for that green text

**Reproduction**
Place the RD hardsuit in a belt

**Screenshots**
image
**Additional context**
Too small 🤏

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Nerfs the Experimental Research Hardsuit from Medium (2x2) to Huge (5x5.) This puts it above the blood-red, and is big enough to where it won't fit in anything smaller then a duffelbag.

Fixes #27091

## Why / Balance
This is a steal objective for a reason, and should *not* be piss easy to carry around. It makes the objective a lot more interesting and forces you to either carry around a duffel bag, make massive storage sacrifices, or wear it yourself.

Additionally, at Medium size, RDs can also just carry this around willy nilly with basically no downside, which is probably not good since hardsuits are generally meant to be a commitment.

Less importantly, there is also the logic angle of it: it makes no damn sense for a bombsuit to be *2x2*. The RD's hardsuit is visually the most bulky hardsuit in the game. While this means that maybe the RD's hardsuit should not be storable at *all* like the other hardsuits, it is at least more logical that it is one of the biggest items in the game despite being storable.

## Media
Content Client_NMJUX2c2qS

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: The Research Director's hardsuit is now 5x5 in the inventory instead of 2x2. You'll need a duffelbag to store it now.

### CODE REVIEW

**Comment by deepdarkdepths** [comment]
Why should RD's hardsuit be harder to conceal than a literal blood red hardsuit

**Comment by Dutch-VanDerLinde** [comment]
3x3 would be cool

**Comment by deathride58** [comment]
>Why should the RD's hardsuit be harder to conceal

Just take one good look at it. It's pretty visually bulkier compared to the syndie hardsuit. It does make logical sense for the RD hardsuit, a suit designed to be capable of withstanding direct explosions, to be bulkier than the hardsuit designed to be sleek and unobstructing of dexterity whilst still being space-faring.

**Comment by LordEclipse** [comment]
> > Why should the RD's hardsuit be harder to conceal
> 
> Just take one good look at it. It's pretty visually bulkier compared to the syndie hardsuit. It does make logical sense for the RD hardsuit, a suit designed to be capable of withstanding direct explosions, to be bulkier than the hardsuit designed to be sleek and unobstructing of dexterity whilst still being space-faring.

Its supposed to be compact

**Comment by deepdarkdepths** [comment]
I think it should've just been 4x4 if the size needed to be changed.. RD's hardsuit is good for withstanding explosions and radiation but not much else, while the blood-red has 50% in all categories and is arguably better, yet it's smaller. 
Mfw the suit with mainly explosion resistance and nothing else going for it is more of a pain to carry around than the hardsuit meant for versatile survivability in most situations.

**Comment by QuietlyWhisper** [comment]
Should've edited the description too, looks silly.
image

**Comment by superjj18** [comment]
Damn it really sucks this got merged so quickly with little discussion(maybe I missed it which would be on me).  Literally the only “experimental” part of the experimental hardsuit.  This is lame and just kinda removes any uniqueness from it, I’d rather just remove it from the steal objective list, 5x5 is just malicious towards backpack and satchel RD users.  3x3 I would understand, 4x4 I would be annoyed with but wouldn't argue that much.

such a drastic nerf justified by a mere visual sprite which could be explained as fabric being inflated and thus pressurized.

**Comment by Golinth** [comment]
This is kind of a massive “fuck you” to anyone not using a duffle, and will just further encourage RD players to powergame and keep the suit on 100% of the time. I can see nerfing it, but 5x5 is a bit much, especially when the description explicitly states that it’s compactable.

**Comment by SlamBamActionman** [comment]
I think that making it 5x5 instead of 4x4 makes it _less_ interesting, both for RD and as a thief objective.

> It makes the objective a lot more interesting and forces you to either carry around a duffel bag, **make massive storage sacrifices**, or wear it yourself.

What storage sacrifices? With a 5x5 you are forced to use a duffel bag. This makes it so that, if the RD's suit is reported stolen, Security will know to look for duffel bags specifically, carried or worn. Someone carrying a bag is already a bit of a red flag, this just amplifies it.

A 4x4 suit would be more interesting; then a thief can actually pass without raising suspicion _if they choose to forgo 16 storage spaces_. Not only is this a lot more interesting, but also keeps you from being valid just because you had a duffel.

As pointed out above this also forces RDs to either always wear the suit or take the 10% duffel speed movement penalty. Having it be 4x4 allows the RD to be more flexible in what backpack they wear, plus interfaces more with the gridinv system since you'll have to be more delibrate with what tools you carry around to fit everything.

**Comment by HelpTheSteak** [comment]
> I think that making it 5x5 instead of 4x4 makes it _less_ interesting, both for RD and as a thief objective.
> 
> > It makes the objective a lot more interesting and forces you to either carry around a duffel bag, **make massive storage sacrifices**, or wear it yourself.
> 
> What storage sacrifices? With a 5x5 you are forced to use a duffel bag. This makes it so that, if the RD's suit is reported stolen, Security will know to look for duffel bags specifically, carried or worn. Someone carrying a bag is already a bit of a red flag, this just amplifies it.
> 
> A 4x4 suit would be more interesting; then a thief can actually pass without raising suspicion _if they choose to forgo 16 storage spaces_. Not only is this a lot more interesting, but also keeps you from being valid just because you had a duffel.
> 
> As pointed out above this also forces RDs to either always wear the suit or take the 10% duffel speed movement penalty. Having it be 4x4 allows the RD to be more flexible in what backpack they wear, plus interfaces more with the gridinv system since you'll have to be more delibrate with what tools you carry around to fit everything.

This is exactly my logic towards this nerf. Not to mention that having a hardsuit in sci on hand at all times is a very good thing to have due to how much spacing and explosions happen out of nowhere

**Pull request merged**
