### PR TITLE
Persona Plasma Monosword

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

Added the plasma monosword, renamed the supercompact potato AI chip to a persona core, made you be able to put the persona core into the plasma monosword to create a new ghost role that can attack(can't hit anyone but the person holding it when being held, so the trick is to throw it) You can find the plasma monosword on expeditions.
## Why / Balance

Fun, adds more unique exped loot and ghost roles.
## Technical details

Nope
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

## Breaking changes

Nope
**Changelog**

:cl:
- add: Added the plasma monosword as a salvage expedition reward. You can upgrade this sword into a persona plasma monosword(ghostrole) with a persona core.
- tweak: Renamed the potato ai chip to persona core

### CODE REVIEW

**Comment by MACMAN2003** [comment]
haha rimworld

**Comment by deltanedas** [comment]
surgery next

**Comment by HoidC** [comment]
should be able to attack others while holding it so you can wield it in your offhand as an automatic sword

**Comment by Errant-4** [comment]
What makes this weapon uniquely suited and capable, from a design standpoint, to become autonomous?

**Comment by Boaz1111** [comment]
> What makes this weapon uniquely suited and capable, from a design standpoint, to become autonomous?

what do you mean?

**Comment by Boaz1111** [comment]
> should be able to attack others while holding it so you can wield it in your offhand as an automatic sword 

Too OP

**Comment by Gtheglorious** [comment]
Rimworld reference is silly, but if it gets implemented I’m only going to refer to it as a shardblade in game

**Comment by Ilya246** [comment]
make it an admeme item or sci T3 and need a positeonic brain, then buff it, perhaps the "allow it to attack by itself" idea

**Comment by HoidC** [comment]
> > should be able to attack others while holding it so you can wield it in your offhand as an automatic sword
> 
> Too OP

it’s completely worthless otherwise

**Comment by K-Dynamic** [comment]
Let it be autonomous and slash people on its own for maximum troll

**Comment by Boaz1111** [comment]
It can hit others, just not while it's in your hand, you can throw it and the sword can attack

**Comment by HoidC** [comment]
> It can hit others, just not while it's in your hand, you can throw it and the sword can attack

so people are just going to not walk near it and it’ll hit them once or twice maximum

Don’t get me wrong it’s a cool feature but not necessarily a useful one

Unless you make it embed, then it’d be a big troll

**Comment by K-Dynamic** [comment]
Grav gun with lubed persona sword, watch nukies panic

**Comment by Boaz1111** [comment]
> > It can hit others, just not while it's in your hand, you can throw it and the sword can attack
> 
> 
> 
> so people are just going to not walk near it and it’ll hit them once or twice maximum
> 
> 
> 
> Don’t get me wrong it’s a cool feature but not necessarily a useful one
> 
> 
> 
> Unless you make it embed, then it’d be a big troll 

Mind you, every hit does 10 heat and 15 caustic

**Comment by IProduceWidgets** [comment]
+1 here for embed like spears, that's really funny.

**Comment by icekot8** [comment]
in fact, your PR is quite interesting and original, but 
1) it's worth thinking about reducing damage, subjectively, 10 hits and 15 of the most hated kind of damage per hit-really powerful 
2) I think it's worth finishing it like in rimworld. create a pair of children from this sword, whose damage will depend on the light. 
3) regarding the damage caused only by the carrier, I agree with you, in my opinion, the gravity cannon will not allow damage to be inflicted. if this is the case, it should be fixed somehow, for example, so that the sword sticks into a person when thrown, as in pirate movies. 
Anyway, I'm attracted to the damage on the roll. Also, if I were you, I would add it to the salvages with a low chance

**Comment by FuturisticRUS** [comment]
More ghost roles = better

**Comment by Errant-4** [comment]
Okay so

If the point is to have a cool sword that talks and attacks by itself, why is it required to additionally manually install the AI into it? Why not have that as an inherent feature? If you can install the potato AI into it, that begs the question why can't you do it with another weapon?
It feels kinda jank to introduce that construction recipe for something this specific
Why rename the potato AI for this?
"persona sword" seems like kind of a weird name
Is the plasma part or the monomolecular part dealing the caustic damage?


... how is a sword both plasma and monomolecular?

**Comment by K-Dynamic** [comment]
New plan: apply glue to sword and let someone you want dead to pick it up

**Comment by Boaz1111** [comment]
> Okay, so
> 
> 
> 
> If the point is to have a cool sword that talks and attacks by itself, why is it required to additionally manually install the AI into it? Why not have that as an inherent feature? If you can install the potato AI into it, that begs the question why can't you do it with another weapon?
> 
> It feels kinda jank to introduce that construction recipe for something this specific
> 
> Why rename the potato AI for this?
> 
> "persona sword" seems like a rather strange name
> 
> Is the plasma part or the monomolecular part dealing the caustic damage?
> 
> 
> 
> 
> 
> ... how is a sword both plasma and monomolecular?

To be honest, I was having issues having the ghost role spawn, a toggleable role wouldn't work because the hotkey also toggles the blade, so this was the only option I could figure out.

**Comment by Boaz1111** [comment]
> in fact, your PR is quite interesting and original, but 
> 
> 1) it's worth thinking about reducing damage, subjectively, 10 hits and 15 of the most hated kind of damage per hit-really powerful 
I should probably nerf it, yeah
> 2) I think it's worth finishing it like in rimworld. create a pair of children from this sword, whose damage will depend on the light. 
Light isn't really a thing outside of expeds, but I might add a second persona weapon.
> 3) regarding the damage caused only by the carrier, I agree with you, in my opinion, the gravity cannon will not allow damage to be inflicted. if this is the case, it should be fixed somehow, for example, so that the sword sticks into a person when thrown, as in pirate movies. 
> 
> Anyway, I'm attracted to the damage on the roll. Also, if I were you, I would add it to the salvages with a low chance
> 
> edit:I noticed that you have already added this to the salvages. apologize

**Comment by icekot8** [comment]
> > in fact, your PR is quite interesting and original, but
> > 
> > 1. it's worth thinking about reducing damage, subjectively, 10 hits and 15 of the most hated kind of damage per hit-really powerful
> 
>     * I should probably nerf it, yeah
> 
> 
> > 2. I think it's worth finishing it like in rimworld. create a pair of children from this sword, whose damage will depend on the light.
> 
>     * Light isn't really a thing outside of expeds, but I might add a second persona weapon.
> 
> 
> > 3. regarding the damage caused only by the carrier, I agree with you, in my opinion, the gravity cannon will not allow damage to be inflicted. if this is the case, it should be fixed somehow, for example, so that the sword sticks into a person when thrown, as in pirate movies.
> > 
> > Anyway, I'm attracted to the damage on the roll. Also, if I were you, I would add it to the salvages with a low chance
> > edit:I noticed that you have already added this to the salvages. apologize

yes, I suggest you make several types of plasma monoswords, you got it right.

since I hope you really listened to me, I vote for adding this item to the game.

**Comment by BYONDFuckery** [comment]
if i had a nickel for every rimworld change
id have 10c

**Review by AJCM-git — CHANGES_REQUESTED** [review]
While a cool concept, the implementation is a little barebones, for it to not feel like a PAI-lite at the very least the sword should be VERY weak (since its something obtainable by the crew) but be able to have its own abilities that it (and not the user) can perform (like a circular slash around the user that has low damage but pushes people, and maybe one or two more cool ones like that)

**Comment by AJCM-git** [comment]
@Boaz1111 do you think you are able to handle the requested changes?

**Comment by Boaz1111** [comment]
Hmmm.... not currently. I've got other things to work on. I'll just close the PR for now, and come back to it later.

**Pull request closed without merging**
