### PR TITLE
Ejected casings now look cool as fuck

### LINKED ISSUE #2325: Cartridges spawn in a rather boring stack
GIF 20-Oct-20 12-36-46 PM
they're all so organized and stacked

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Thanks to @mirrorcult for being a chad and fixing this.

Closes #2325.

**Screenshots**

Before

After

**Changelog**

:cl:
- tweak: Ejected casings now have much more variation and look cooler

### CODE REVIEW

**Comment by metalgearsloth** [comment]
which dumbshit coded guns?

**Comment by SweptWasTaken** [comment]
> which dumbshit coded guns?

I think it was candice

**Comment by metalgearsloth** [comment]
who's ligma

**Comment by SweptWasTaken** [comment]
penis balloon

**Pull request merged**
