### PR TITLE
Remove yellow oxygen tank

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

was made in #22354 but requested to splitted, so all main info there

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- remove: Yellow oxygen tank was removed to standardise gas tank colourings.

### CODE REVIEW

**Comment by Hmeister-fake** [comment]
Yellow tank gang rise!

**Comment by Yuoko** [comment]
NO! Plese! Yellow tank is very nice, i love it! Dont merge this...

**Comment by DangerRevolution** [comment]
completely forgot about #22354 LMAO, thanks for this; i'll eventually get around to the rest of the changes i was meant to do :)

**Comment by potato1234x** [comment]
its specifically for firefighter lockers, it fits better with the firefighter color scheme, no merge pls

**Comment by Emisse** [comment]
ive never seen so many people rise up in defense of yellow oxygen tank in my life

**Comment by notquitehadouken** [comment]
ok but why

**Comment by potato1234x** [comment]
why sloth why

**Pull request merged**
