### PR TITLE
Reimplement supplybots as non-vehicles

### PR DESCRIPTION
**Pull request by Plykiya**
## About the PR

SUPPLYBOTS MY BELOVED

They're cute little delivery dumptrucks without all access or laws, they just have storage capacity, the ability to talk, and are intended to assist in the carrying of goods between departments. I re-added them with the same storage and flashlight they used to have, but also gave them access to maints and gave them the same footstep sound that borgs have. When they were in the game I noticed that they often got trapped in maints with no one to help them, so this is just a QoL for them.

## Why / Balance

They were originally removed with all vehicles, so I just re-implemented them to not be a vehicle. They weren't rideable back then, they're more like a honkbot in terms of actual capability. 

## Technical details

Readded supplybots using the same base as all the other bots.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/58439124/af4d526a-7285-4659-94ed-34986f03721e

**Changelog**

:cl:
- add: Re-added supplybots.

### CODE REVIEW

**Comment by TheDoctor1977** [comment]
Do they have the ability to talk on radio? They should probably at least have supply radio so they can be called to pick things up or request assistance if needed.

**Comment by Plykiya** [comment]
> Do they have the ability to talk on radio? They should probably at least have supply radio so they can be called to pick things up or request assistance if needed.

they have binary and common, I guess I can give them supply as well

**Comment by lzk228** [comment]
can you make having them access only if they have mind? like cyborgs
also i thing them having QM access in not necessary

**Comment by Dutch-VanDerLinde** [comment]
comment out MobSupplyBot: null in migrations.yml

**Comment by Plykiya** [comment]
> can you make having them access only if they have mind? like cyborgs also i thing them having QM access in not necessary

it was the access they had before but I can change that
I'll look to see if I can find the mind component thing

**Pull request merged**
