### PR TITLE
syndicate snack box

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
available for 1tc to syndies and nukies

usually contains:
- a toy
- 4 cans of soda
- 4 syndicakes

rare spawns:
- c4 or balloon, same as the robust nukie meal
- 1-2 blood-red brew cans
- valid salads instead of syndicakes

## Why / Balance
- nukies can eat if they forgot to eat at the outpost
- syndies that are wanted can eat instead of risking going out in public
- valid...
- nukies can buy it and fight over who gets the toy

## Technical details
no

## Media
uplink listing:

6 of them i bought:

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: The Syndicate's chefs are now offering snack boxes for only 1 tc. Usually contains a toy, drinks and food.

### CODE REVIEW

**Comment by Yousifb26** [comment]
Image says 4tc but text says 3tc. Which is it?

**Comment by deltanedas** [comment]
4 i did le typo

**Comment by Yousifb26** [comment]
Cl also needs to be changed then

**Comment by deltanedas** [comment]
:trollface:

**Comment by Emisse** [comment]
this should be cheaper i think, like 1 or 2

**Comment by Ilya246** [comment]
make it 1tc, food for the whole crew

**Comment by dvir001** [comment]
1 TC please, I dont see any other time ill use 2+ TC on food items when I need gear, 
+having to destroy a box that in LRP will get my ass "valid hunted", over paying for it will mean its never used.

**Comment by HoidC** [comment]
> i thought it might lead to people just buying it for 1% chance of gamer loot but ok

20tc for a c4 kind of sucks mate idk about you

**Comment by deltanedas** [comment]
:trollface:

**Comment by metalgearsloth** [comment]
snak

**Pull request merged**
