### PR TITLE
suffix additions: Pinpointer, thruster, gyro

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
Thruster: unachored 
Gyro: unanchored
pinpointer: station

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by deltanedas** [comment]
add suffix for PinpointerStation too :trollface:

**Comment by QuietlyWhisper** [comment]
5 minute adventure

**Review by ficcialfaint — COMMENTED** [review]
I think it would be also good to add a suffix for the regular (nuclear authentication disk one) pinpointer, what do you think?

**Comment by QuietlyWhisper** [comment]
> I think it would be also good to add a suffix for the regular (nuclear authentication disk one) pinpointer, what do you think?

It seemed fine to leave it like that since it's the default/base state

**Comment by JoeHammad1844** [comment]
add suffix for the syndicate 80 size briefcase

**Comment by QuietlyWhisper** [comment]
> add suffix for the syndicate 80 size briefcase

image
They were a bit vague in general so I updated a couple

**Pull request merged**
