### PR TITLE
Add LF option into gitattributes

### LINKED ISSUE #16248: a lot of maps use crlf
## Description
@Emisse noob stop editing map in notepad

**Reproduction**
`file Resources/Maps/*.yml`

**Screenshots**
(does not include shuttles wrecks etc)

### PR DESCRIPTION
**Pull request by c4llv07e**
## About the PR
Add an option to the gitattributes to replace the CRLF with the LF in the source files.

Closes #16248 

## Why / Balance
It is annoying to work with files that contain CRLF characters on Linux. It would be great if git would automatically replace these characters on every commit.

## Technical details
I can change every file with CRLF by myself, but it will make a lot of conflicts.

## Media
No CRLF, yay!
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Maybe it will cause more merge conflicts in the future, but I think it will be easy to solve.

**Changelog**
Players don't care.

### CODE REVIEW

**Comment by deltanedas** [comment]
rest in piss dreaded crlf ops

**Comment by PJB3005** [comment]
This should already be done by the `* text=auto` directive in the gitattributes. If the problem is people somehow having their git client horribly misconfigured, this will not solve it and a better fix is a CI check for that.

**Comment by PJB3005** [comment]
In fact this PR doesn't even solve the issue linked: you're not updating the existing files to remove the line terminators, and git is not going to automatically do it for you just by setting these flags.

**Comment by PJB3005** [comment]
I did some testing. The reason these files got in is because GitHub doesn't respect `.gitattributes` when people upload text files via the web interface. This PR does not fix that, and in my testing actually causes Git on Windows to completely explode.

A proper fix for this issue would be:
1. A PR to fix all existing CRLF files in the repo to be LF.
2. A CI check to block future CRLF files.

**Comment by deltanedas** [comment]
> A CI check to block future CRLF files.

this seems very complex would killing webedits work

**Pull request closed without merging**
