### PR TITLE
Psychologist's Stamp

### PR DESCRIPTION
**Pull request by cohanna**
## About the PR

Added psychologist stamp. Spawns in psychologist inventory (similar to clown & mime).
This is my first PR for SS14 and im not an artist so feel free to criticize sprites and anything else.
## Why / Balance

Adds a avenue for psychologists to have impact on RP. Useful for prescribing treatments (anything from chemical acquisition from chem to drip from hop, whatever makes sense to "treat" the patient) 
## Technical details

Adds respective entries in rubber_stamp.yml, stamps.rsi/meta.json, bureaucracy.rsi/meta.json.
## Media

paper_stamp-psychologist
stamp-psych

Screenshot 2024-09-05 223307
Screenshot 2024-09-05 223403
Screenshot 2024-09-05 223431

## Requirements

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion

## Breaking changes

N/A
**Changelog**

:cl: clinux
- add: Added the psychologist's stamp. Prescribe treatments for your less mentally sane crew!

### CODE REVIEW

**Comment by Awlod** [comment]
Not bad

**Comment by TheDoctor1977** [comment]
it looks very centered on the page, how does it look with a centcomm stamp? iirc that would be in basically the same spot

**Comment by ArtisticRoomba** [comment]
> it looks very centered on the page, how does it look with a centcomm stamp? iirc that would be in basically the same spot

On the paper sprite or the stamp "in" the paper? If you're talking about the stamp "in" the paper, it's fine. That's just how the game handles stamping. It just got lucky and chose the middle. Everything else looks fine to me.

**Comment by cohanna** [comment]
> That's just how the game handles stamping. It just got lucky and chose the middle. 

This is correct, I didn't touch the stamp system. Stamps have a color and a name and the rest is handled by a different system, admins can even make custom stamps on the fly.

**Pull request merged**
