### PR TITLE
The training bomb now mirrors the syndicate bomb's wires

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Makes the training bomb mirror the syndicate bomb's wires, like in SS13.

## Why / Balance
The syndicate bomb is clearly overpowered and this sticks out as a large potential culprit - this feature was (presumably) pivotal to preventing the bomb in SS13 but is just flat-out missing here. This may or may not cause the bomb to become useless considering the playerbase differences but it is at least worth a try - we should implement the thing like it is in SS13 before immediately jumping to rebalancing a version of it that was feature-incomplete to begin with.

Besides that, it makes sense for a couple of other reasons - having a 55% chance dice roll for a gigantic explosive like this is probably not good considering it can destroy departments singlehandedly, and this will also be far from a free win as security - not only do they have to remember to do the training bomb in the first place, but they have to actually find & defuse the bomb within 120 seconds, have wirecutters and a screwdriver on them during that time, and also remember the wire after defusing the bomb.
Syndicates will also likely have to be smarter with their bombing targets, probably usually planting them in harder to notice places to get away with defusing it instead of just putting it in the hallway and hoping nobody defuses it.

**Changelog**
:cl:
- tweak: The training bomb's wires now match those on the syndicate bomb.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
in ss13 you had an item that would INSTANTLY detonate any active syndicate bomb on the map, but to be fair it was nukeops exclusive, which is an extra reason for having the training bomb mirror wires, but, obviously, we dont have this

**Comment by JoeHammad1844** [comment]
image
oh nice

**Comment by LankLTE** [comment]
Honestly this seems controversial enough for me to want to leave it for a bit.

**Comment by deltanedas** [comment]
perhaps training bombs and syndicate bombs get different wire layouts roundstart but thats it. if you successfully defuse a bomb you know what the wire is for the rest of the round, and if you hit a boom wire you know to avoid it next time. it would make them a thing thats only effective once or twice to a good crew

**Comment by Partmedia** [comment]
The reactions here show that there is significant opposition to this, but I don't think the current bomb balance as-is is tenable, either. Could those who are opposed please discuss and/or link relevant discussions from Discord?

**Comment by Golinth** [comment]
Had a little think on this, and I think this could work with one change. Implementing this as it is now would completely trivialize dealing with syndicate bombs with even the smallest amount of preparation, but that got me thinking, if sec can prepare, why not traitors to? 

So my idea is this: After buying the bomb, but before arming it, allow the purchaser to randomly scramble a chosen wire, one at a time, as many times as they want with as many wires as they want. You can add a do-after of any length to balance. This adds more risk to the bomb, as the syndie would be sticking around the bomb for longer and provide more opportunity to be caught, but if they somehow get their hands on a training bomb, or manage learn the right wires to swap, they have access to basically the current version of the bomb, where it would be completely random for sec to defuse it.

**Comment by AJCM-git** [comment]
Discussion has stalled and this does not seem like the preferred solution to the problem, making the bomb's wires require manual setup or something else would do the trick

**Pull request closed without merging**
