### PR TITLE
Add auto map vote cvar

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Add cvar that will automatically start map vote after starting new round

## Why / Balance

Nice feature

## Technical details

No

## Media

https://github.com/space-wizards/space-station-14/assets/124214523/3f05af09-e7e2-4f49-9060-541bdb8444f6

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Should it has admin changelog?

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Democracy update is real

**Comment by Killerqu00** [comment]
That might result in a certain pool of maps being picked often/almost never picked.
However, on the other side, it can also point out maps that are lacking in terms of design.

**Comment by mirrorcult** [comment]
default the cvar to false (or at least false in the wizden config) and this can be merged without discussion

**Comment by lzk228** [comment]
@mirrorcult done

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
