### PR TITLE
Add Botanist, Warden, Quartermaster and Chaplain

### PR DESCRIPTION
**Pull request by brndd**
Adds YAML for these missing jobs. Also adds all of the ID card spritework courtesy of @SweptWasTaken and sprites for the chaplain's black jumpsuit from TGStation.

### CODE REVIEW

**Review by Zumorica — APPROVED** [review]

**Comment by Zumorica** [comment]
Does this add the spawn points for these jobs?

**Comment by brndd** [comment]
> Does this add the spawn points for these jobs?

It does now. They're not mapped in though.

**Comment by Zumorica** [comment]
That's okay. Swept can take care of that when he does his next mapping PR

**Comment by PJB3005** [comment]
There literally is no space on the map for QM, Warden or Chaplain.

**Pull request merged**
