### PR TITLE
Makes water not slippery

### PR DESCRIPTION
**Pull request by DogZeroX**
## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Water is no longer slippery.

### CODE REVIEW

**Comment by mirrorcult** [comment]
wut

**Comment by metalgearsloth** [comment]
> wut

It's cancer after mopping up when space lube already exists.

**Comment by mirrorcult** [comment]
water should absolutely be slippery, lube should not be the only slippery chem in existence

**Comment by mirrorcult** [comment]
its supposed to be slippery after you mop--this is why wet floor signs / galoshes / like 20% of janitor content exists

**Comment by EmoGarbage404** [comment]
Speedrevert incoming

**Comment by metalgearsloth** [comment]
Doesn't that mean mopping up blood is bad because you're making the floor worse.

**Comment by mirrorcult** [comment]
wasnt like half the point of the puddle PR that mopping is about moving water around so stuff evaporates faster?

**Comment by metalgearsloth** [comment]
There's no consequences to leaving the majority of puddles around (at least by volume on an average round).

**Comment by DogZeroX** [comment]
That would mean making all big puddles have a CHANCE to slip to make mopping stuff important other than the station not looking dirty i guess, and in some cases where falling on the chems might burn you.

**Comment by mirrorcult** [comment]
whatever problem you have in mind (which probably exists) the solution is not to make water not slippery

**Comment by DogZeroX** [comment]
Blame sloth.

**Pull request merged**
