### PR TITLE
Mop usable as weapon

### PR DESCRIPTION
**Pull request by Easypoller**
**Changelog**
I added wielding sprites.
Mop is now usable as a weapon and is also wieldable.
Damage with one hand is 10 blunt with two hands it's 15 in total.
Im not sure about the numbers but i thought it would be slightly weaker than the baseball bat and based numbers on that.
Screenshots:
Basic damage
basic damage
Health after basic damage
Holding in both hands (right)
holding both hands right 1
holding both hands right 2
holding both hands right 3
holding both hands right 4
Holding in both hands (left)
Base Profile Screenshot 2022 12 05 - 09 24 49 64
Base Profile Screenshot 2022 12 05 - 09 24 51 77
Base Profile Screenshot 2022 12 05 - 09 24 53 71
Base Profile Screenshot 2022 12 05 - 09 24 57 09
Damage with both hands
both hands damage
Health after both damage

### CODE REVIEW

**Comment by Vordenburg** [comment]
You'll need a two-handed sprite for this to work properly. The fireaxe is a good example of what to do.

**Comment by Easypoller** [comment]
> You'll need a two-handed sprite for this to work properly. The fireaxe is a good example of what to do.
ok I'll try

**Comment by Easypoller** [comment]
It should be fine now

**Comment by mirrorcult** [comment]
needs screenshots/video of ingame

**Comment by Easypoller** [comment]
> 

Made some epic screenshots

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
