### PR TITLE
Chem guidebook

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Requires https://github.com/space-wizards/RobustToolbox/pull/4111

Revival of #14060 

Creates some new guidebook tags for displaying reagents:
- `GuideReagentEmbed`: embeds a control displaying a reagent's name, description, recipe, and effects.
- `GuideReagentGroup`: embeds a list of multiple `GuideReagentEmbed`s for a given category.

These are combined to essentially duplicate the [chemistry wiki page](https://wiki.spacestation14.io/wiki/Chemistry) in the guidebook. (The guidebook page is also linked on the Chem Dispenser via `GuideHelpComponent`)

**Media**

image
blurb

image
general entries

image
recipe + effects

image
the long boy

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: moony, EmoGarbage404
- add: The chemistry wiki page is now available in the guidebook. Learn all about the different chemicals today.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Ready for review

**Comment by deltanedas** [comment]
rest in piss wiki

**Comment by forgotmyotheraccount** [comment]
chem has officially been upgraded from a wiki job to an F1 job

**Comment by deltanedas** [comment]
num0*****

**Pull request merged**
