### PR TITLE
Adds empty medkits to medical lathe

### PR DESCRIPTION
**Pull request by nmajask**
## About the PR 

Adds recipes for all the medkits to the medical lathe locked behind biological tech. Wanted to add this so people could make their own medkits to store their meds for better organization. Each cost 300 plastic (3 sheets) and you can craft every kind of medkit.

**Media**

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: added medical lathe recipes for all the medkits, they cost 300 plastic, are locked behind biological tech, and are empty

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Are these filled?

**Comment by nmajask** [comment]
> Are these filled?

No, they are empty

**Comment by Jackrost** [comment]
Maybe add suffix so people would understand that this is just container?

**Comment by nmajask** [comment]
> Maybe add suffix so people would understand that this is just container?

I'll take a look into adding that

**Comment by nmajask** [comment]
> Maybe add suffix so people would understand that this is just container?

I just renamed all the recipes to have "(empty)" at the end, don't know if there is a better way of going about it.

**Comment by Jackrost** [comment]
Nah, this is fine.

**Review by ZoldorfTheWizard — APPROVED** [review]

**Pull request merged**
