### PR TITLE
Sort crew manifest by name and job title

### LINKED ISSUE #12106: Crew manifest should be sorted
I think ideally by job then by name. I'm not sure what's being applied atm but it might just be default.

### PR DESCRIPTION
**Pull request by Theomund**
## About the PR 

This pull request resolves #12106, which describes a problem with the crew manifest not being sorted. It does this by sorting the crew manifest entries by the job title first, and then by the crew member name.

**Media**

Crew Manifest

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Added logic for sorting crew manifest entries by job titles and names.

### CODE REVIEW

**Comment by Carbonhell** [comment]
I don't think it makes much sense for civilians to be listed before heads of staff / other departments imo. The name ordering is good, but I would expect departments to be ordered from most important to least or a similar ordering (for example, heads -> security -> science -> engineering -> medbay -> civilian). Just my two cents though.

**Comment by Theomund** [comment]
> Anyway, this doesn't seem to order _cachedEntries too, is that on purpose?

To my understanding, the `_cachedEntries` variable is a dictionary that maps a station's entity ID to a crew manifest. Since each crew manifest is sorted before being added to the cache, there is no need to perform any additional sorting.

**Comment by Vordenburg** [comment]
Does the name sorting take precedence over the job sorting? I.e. will I be able to read through the crew manifest alphabetically to find someone's job? This is the task that is least optimal right now, because jobs are already sorted per department and have easy-to-recognize icons.

**Comment by Theomund** [comment]
> Does the name sorting take precedence over the job sorting? I.e. will I be able to read through the crew manifest alphabetically to find someone's job? This is the task that is least optimal right now, because jobs are already sorted per department and have easy-to-recognize icons.

Here's an example of what the crew manifest will look like:

Crew Manifest

As you can see, the job titles take precedence over a person's name. This has the benefit that crew members with similar jobs are grouped together in batches. This helps in cases where you know that somebody you're looking for is, for example, a clown.

**Review by EmoGarbage404 — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
