### PR TITLE
Removes space medipens from survival boxes

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
What it says on the tin. Space medipens are a relic of the long-bygone era of hyper lethal spacing. Now that space doesn't murder you instantly, they're really not needed and basically just let you ignore spacing entirely for one use, which is pretty dumb and lets you get out of a lot of situations you probably shouldn't be able to.

Without all-access externals, this may suck balls and just lead to completely and utterly unsurvivable situations, but spacing is hilariously weak right now so it's probably at least worth testing. Pods are also of course intended to counter this exact situation - fingers crossed they'll actually be used now.

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- remove: Due to budget cuts, the survival box no longer includes the space medipen. Nanotrasen suggests using the escape pods in situations where the departures lounge may now be unreachable.

### CODE REVIEW

**Comment by LankLTE** [comment]
I think space medipens should stay. Spacing is still lethal even if not as much as before, and there are a lot of methods that they're still useful (a room gets spaced and you don't have a crowbar, a bluespace anomaly throws you outside, disposals is spaced, space wind throws you out, just to name a few). Letting someone "ignore spacing entirely for one use" is really not a bad thing- it's a _survival_ kit for a reason, and even using it to chase someone down is still using your only spacepen for that entire game. 
But flares and MRE tins can probably be removed, I don't ever see them actually used (or need to be used, even).

**Comment by EmoGarbage404** [comment]
This pr is based and i love it. It might be worthwhile seeing if space medipens spawn in emergency lockers but otherwise good shit.

**Comment by Flareguy** [comment]
No longer removes flares & the MRE tin per popular request.

**Comment by dmnct** [comment]
> No longer removes flares & the MRE tin per popular request.

Wait, what happened here? Popular request doesn't care about the spacepen but wants to hold on to the flare and tinned meat? Those two are the things in the survival kit that always struck me as useless

**Comment by LankLTE** [comment]
> Wait, what happened here? Popular request doesn't care about the spacepen but wants to hold on to the flare and tinned meat? Those two are the things in the survival kit that always struck me as useless

This is per a discord discussion. Honestly I’d rather see space damage buffed again (and I think there’s a lot of positives to that) rather than spacepens removed, but I guess they both have the same end result so whatever

**Comment by OctoRocket** [comment]
I use the flares, the MRE is meh but I rather have it than not.

**Comment by Aisu9** [comment]
i never used the flare because it kills my eyes, i used the MRE tin in every shift i played (it's just nice to have a "full" meal in a small item)

**Comment by moonheart08** [comment]
based

**Comment by EmoGarbage404** [comment]
Flares are entirely useless and the tin is just a crutch (there is so much food you can find it everywhere)

**Comment by Aisu9** [comment]
what about a water bottle? i pray every shift for no one to be diabetic because hell the only drink you have outside of bar/kitchen is 50% sugar

**Comment by Eden077** [comment]
I mean at least to me you describe the biggest issue with removing the space pen in your description, you can die without having having the pen if you can't leave said spacing, and without cloning it could essentially perma kill you for the rest of the round. It's a bad change imo, but maybe nerfing the space-pen so it has a shorter effect time would be more suitable, just a thought

**Comment by Flareguy** [comment]
> I mean at least to me you describe the biggest issue with removing the space pen in your description, you can die without having having the pen if you can't leave said spacing, and without cloning it could essentially perma kill you for the rest of the round. It's a bad change imo, but maybe nerfing the space-pen so it has a shorter effect time would be more suitable, just a thought

Can't you just push the firelock wallmounts? We might have some wack ass mechanic preventing it but that's what they're there for, usually.

**Comment by Eden077** [comment]
If the pressure reaches a point of being too low or high ir the air gets too hot or too cold, it'll lock and need a crowbar, and spacing may take longer but it still kills you quick, for now spacing can definitely kill you or if it's high pressure, you can get hilariously chucked out of the station into space

**Comment by asperger-sind** [comment]
I don't think this solves the issue of space being weak, and the issue itself is probably better left as-is because dying to spacing is wack 9/10 times.

The one real use the spacepen has is probably to combat nukies, because in all other situations you can just walk out willy nilly without the need of using one.

Pods also probably wont be used with how they're mapped and the areas that usually get spaced (bagel med is spaced, the pods are down all the way in maint directly below it after like 7 firelocks and 2 access doors, chances are you'll be out of the spaced area before you get there)

**Comment by Flareguy** [comment]
This will probably have to wait because of #17852, though if enough people want to test it out I would be fine with reopening it.

**Comment by juliangiebel** [comment]
Space should just be more lethal again ngl

**Pull request closed without merging**
