### PR TITLE
Remove QSI from research due to nullspace bug

### PR DESCRIPTION
**Pull request by OliverOtter**
## About the PR

Removes the QSI from normal play (not researchable anymore) but keeps the item in game.
## Why / Balance

Ive had multiple report of it round removing people due to nullspace bugs related with it. Having it gone from normal play until the bugs relating to it are fixed would be nice so people dont accidentally delete themselves/Clone themselves.
## Technical details

N/A
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Nanotrasen has removed the possibility of researching the Quantum Spin Inverter for now due to multiple instances of it breaking the space time continuum.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
you should just fix the bug otherwise this is never gonna get resolved.

**Comment by OliverOtter** [comment]
I have no idea how it works, so there really isnt much i can do in fixing it. I know this is a band-aid solution, and i shouldnt be doing this, but its better than having people randomly deleted because they dont know its game breaking.

I'll try to get in contact to who made it and ask for help.

**Comment by metalgearsloth** [comment]
Provide a detailed bug report and it will get fixed much faster.

**Comment by TheShuEd** [comment]
If you decide to fix this error, please tell and we will reopen this pr

**Pull request closed without merging**
