### PR TITLE
New caliber and buff magnum

### PR DESCRIPTION
**Pull request by Jackal298**
this pr is aimed at increasing the damage of magnum cartridges and reworking the smg vector for a new caliber

## About the PR

Initially, this pr was aimed at changing the damage of .45 magnum, but along the way, a serious problem arose in the face of the smg vector, with an increase in damage, the smg became an annihilator of all living things, so I had an idea for a new caliber with the damage of the old magnum.
.40 heavy is a stronger cartridge than 35 auto but not stronger than .45 magnum.
New caliber can be used for more powerful pistols.
I redid the vector for a new caliber, I also redid the magazines, the safe with the vector (spawn of new magazines), boxes with magazines, the security fab can print and a box of ammo and one bullet, also a new caliber was added to the ammo vending machine.
I didn't remove the old vector stores so nothing would break in the game, I also expect the mergers to check and tell me what I forgot to do.
I could put the weapon on a pistol caliber, but in this case the vector would become meaningless.
I also removed the magnum smg stores from the safe with VT 550 and added his native stores to it.
The .45 magnum cartridge has also been strengthened, now it is many times stronger:
Normal ammo 35 damage
High speed 39 damage
I was also inspired PR by asperger-sind under the number #12538

**Media**

3 mag
2 mag
1 mag

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: added new caliber ".40 heavy" bullets, ammo box, crafting in security tech
- tweak: Due to an incident at one of NT's facilities associated with the SMG Vector and updated cartridges ".45 magnum", NT ordered and began to supply a weakened version chambered in ".40 heavy"
- tweak: After detectives complained about the weakness of the .45 magnum cartridge, NT upgraded the cartridge to a higher lethal force.

### CODE REVIEW

**Comment by Jackal298** [comment]
I already see problems, I will fix it now

**Comment by Jackal298** [comment]
Sorry for the title and description errors, this is my first major PR

**Comment by Mudsson** [comment]
Hopefully revolvers are gonna be fun to use 
I would argue that this doesn't fall under the weapon freeze because 
it is altering existing weapons
And making a syndie gun hopefully not completely outclassed

**Comment by Mudsson** [comment]
> > Hopefully revolvers are gonna be fun to use I would argue that this doesn't fall under the weapon freeze because it is altering existing weapons And making a syndie gun hopefully not completely outclassed
> 
> I strengthened the revolver so that the target without body armor fell into a critical state with 3 shots from the revolver

That makes it worth it imo, as it can kill 2 people for clip. The viper can kill the same amount of people for the same tc if you buy another mag, so the python is more tc efficient the more people you kill. Can it drop a captain or a secoff in all 7 shots?  The captain can only be killed in one mag by the cobra right now.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Please don't add new calibers

**Comment by Jackal298** [comment]
> Please don't add new calibers

I understand you, I will do it only by improving the magnum cartridge

**Pull request closed without merging**
