### PR TITLE
fix a station event weighting bug

### PR DESCRIPTION
**Pull request by IProduceWidgets**
## About the PR

Due to how the weighted event selector works, FindEvent(..), only integer weights resulted in the event ever getting selected.

## Why / Balance

bugfix

## Technical details

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: StationEvents with very low weights will now actually appear.

### CODE REVIEW

**Comment by IProduceWidgets** [comment]
We *could* support floats, but the solution here is kinda elegant, so Id rather just restrict to int in the component so people dont make the mistake.

**Comment by slarticodefast** [comment]
Your changelog is formatted wrong.

**Comment by IProduceWidgets** [comment]
> Your changelog is formatted wrong.

50% of the time it works every time.

**Comment by slarticodefast** [comment]
Why does it cast the weight to an integer anyways?
Weights are already floats.
grafik
And it looks like it FindEvent could be easily changed to use floats.

**Comment by IProduceWidgets** [comment]
> Why does it cast the weight to an integer anyways? Weights are already floats. grafik And it looks like it FindEvent could be easily changed to use floats.

I assume its to avoid a random float and dealing with the bounds.
Consider 5 events with weights 1, 1, .2, .8, 1, and 3 random draws of 2, 3, and 4.

Draw a selects the 2nd event
Draw b selects the 4th event
Draw c selects the 5th event

With integer random draws its not possible to get all the events.

**Comment by slarticodefast** [comment]
Couldn't the random integer just be changed to a random float from 0 to sumOfWeights?
Or is my math wrong here?

**Comment by IProduceWidgets** [comment]
> Couldn't the random integer just be changed to a random float from 0 to sumOfWeights? Or is my math wrong here?

No it can, just a stylistic difference I suppose.
I went ahead and kept floats using NextFloat()

**Review by slarticodefast — APPROVED** [review]

**Comment by slarticodefast** [comment]
Good catch with the bug. We would likely have never noticed and it looks like it affects some other weights as well, for example the Urist swarm.
Thanks for the fix!

**Comment by chromiumboy** [comment]
The math makes sense, thanks for the fix

**Pull request merged**
