### PR TITLE
Biogenerator

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds the biogenerator and some recipes for it.

the biogenerator converts nutriment in plants into biomass, which it then uses to create items.
it can create a bunch of food reagents, botany chems, and some non-standard materials.

## Why / Balance

this serves two purposes:
- it gives botany a sink for plants, letting them exchange discreet entities for reagents or stacks, reducing overall entity count
- it makes botany/chef a bit more independent from chem and cargo, as this enables them to create some common items that they might want.

## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the biogenerator! Botany can use this machine to create various materials, chemicals, and food items out of the

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
also YES im aware the biofab shares the sprite and has a similar name. i'm working on getting a replacement sprite and hopefully in the near future i'll get that swapped out so they're more distinct.

**Comment by TurboTrackerss14** [comment]
Don't half of these (the mob cubes) already exist within the BioFabricator that already exists ingame?
https://github.com/space-wizards/space-station-14/blob/edd17072ae7becc7a39043d9f31652757c4cc768/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L649
image

**Comment by EmoGarbage404** [comment]
> Don't half of these (the mob cubes) already exist within the BioFabricator that already exists ingame?
> 
> https://github.com/space-wizards/space-station-14/blob/edd17072ae7becc7a39043d9f31652757c4cc768/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L649
> 
> image

i mean this literally only overlaps with the monkey and kobold cubes, which are already trivially available from cargo. i don't really see it as an issue.

**Comment by TurboTrackerss14** [comment]
Yeah. but its locked behind science tier 1 MeatManipulation. 
This is not, meaning the only differentiator between them is the emag capabilities. 

regardless this just feels like a botany independence/reduce rp pr. 
>want meatcubes
Sure just print them, don't bother asking cargo just print them with the morbillion plants you can make.
>want more ez nutriment to produce more produce to keep the cycle going?
just print it

Chemists already lack interaction other than mass producing chems and going afk, botany was one of the few people who frequently pesters them for chems. 
Cargo doesn't have enough people frequently asking for small(ish) purchases to slow down their speedrun to 1,000,000 spesos. 

If botany is needing a place to sink their excess produce that just sounds like they are making to much produce to begin with without enough delay or drawbacks. 
Plus everything here is basically selfcontained to sustain the infinite food cycle its trying to stop?

**Comment by ARMOKS** [comment]
Can we just add all the new recipes to the Biofab?

**Comment by Hent798** [comment]
don’t take away the chemists’ jobs, they literally have nothing and no one to make chemicals other than medicines for the medical department.
and why is there flour and milk crafting? to grow these productive cocoa beans, turn them into biomass and make all the other things out of it? This is how they will only grow cocoa beans.

**Comment by Ilya246** [comment]
> also YES im aware the biofab shares the sprite and has a similar name. i'm working on getting a replacement sprite and hopefully in the near future i'll get that swapped out so they're more distinct.

i think there should also be a way of using the biogenerator to supply to biofabricator, just being able to eject the biomass could work

**Comment by deltanedas** [comment]
you can already put plants in a biomass reclaimer so idk if thats needed

**Comment by Ilya246** [comment]
> you can already put plants in a biomass reclaimer so idk if thats needed

currently it's too much of a pain for something too niche for people to actually do it

**Comment by Emisse** [comment]
everything looks fine but i cant speak for the linq functions so i approve

**Review by Emisse — APPROVED** [review]

**Pull request merged**
