### PR TITLE
Removes duplicate fortune cookie

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
Changelog: Removes a duplicate entity. IT DIDN'T EVEN CONTAIN A FORTUNE!

I checked the maps and there was only one instance of it being mapped on Bagel. <s>I replaced it with the other cookie.</s>

### CODE REVIEW

**Comment by deltanedas** [comment]
you should use migration instead of editing map

**Comment by ChilbroBaggins** [comment]
> you should use migration instead of editing map

Oi, I'm sorry. I'm not yet familiar how to do that...?

**Comment by DawBla** [comment]
> > you should use migration instead of editing map
> 
> Oi, I'm sorry. I'm not yet familiar how to do that...?

https://github.com/space-wizards/space-station-14/blob/master/Resources/migration.yml
You just gotta add oldId: newId there and it will swap in all maps

**Comment by ChilbroBaggins** [comment]
Easy enough. Moved to migration then.

**Pull request merged**
