### PR TITLE
Option to delay uplink item purchase

### PR DESCRIPTION
**Pull request by Titian3**
## About the PR
Added a timeout(Out of stock time) for uplink items to delay being purchased to mechanical preventions for massive station damage or for balancing better items to come later in the round.
Mainly right now its to add a delay to the syndicate bomb for 30min from round start.

## Why / Balance
Many discussions about if the syndicate bomb is station sabotage and needs some rule preventions this should be a mechanical way to balance it.
Latest one:
https://forum.spacestation14.io/index.php?/topic/2806-syndicate-bombs-early-into-the-round/

## Technical details
Changes to the client store UI to allow prevent purchase of items before round time has reached timeout defined on listing prototype yml.

## Media

https://github.com/space-wizards/space-station-14/assets/47093363/dd83f346-2296-49bf-b038-74c26bba320a

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Shouldn't be any breaking changes.

**Changelog**
Uplink items can now have a delay set on them in the uplink to mechanically prevent purchases for game balance.

:cl:Repo
- add: Time out for particular uplink items for balancing. Syndicate Bomb can only be purchased after 30min.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
syndie bombs are 11TC so you cant even buy two without a second traitor, and if you have a second traitor you dont have the out of stock time, so this will only really effect syndies who butcher renault

**Comment by LankLTE** [comment]
> syndie bombs are 11TC so you cant even buy two without a second traitor, and if you have a second traitor you dont have the out of stock time, so this will only really effect syndies who butcher renault

The point is to prevent people from buying syndie bombs 5 minutes into a round and causing massive damage. This is a good change.

**Comment by Aisu9** [comment]
this will also prevent players from committing the error of mass sabotage before the 30 minutes mark(because yes spacing a giant area with a 53% probability is still mass sabotage)

**Comment by Titian3** [comment]
I was going to wait a little until I had a better version of this but it is almost every game it negatively affects most roles gameplays and this should fix that for now.
Main issues hadn't fixed yet were that the timer update/refresh on the listing page is manual instead of an auto one and this may affect nukies purchasing it but they get a lot already.

**Review by LankLTE — CHANGES_REQUESTED** [review]
Please update to master to fix the tests failing

**Comment by Titian3** [comment]
> Please update to master to fix the tests failing

Updated to latest master and ran again, it failed but looking at the test it passes on my local for that same test, on window.
image

Flakey test?

**Comment by LankLTE** [comment]
I believe this test fail is a different (unrelated) issue.

**Review by LankLTE — APPROVED** [review]

**Pull request merged**
