### PR TITLE
Remove vent clog event

### PR DESCRIPTION
**Pull request by lzk228**
## Why / Balance

foam reaction was removed while ago

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- remove: Vent clog event was removed.

### CODE REVIEW

**Comment by LordEclipse** [comment]
What? foam still works

**Comment by deltanedas** [comment]
foam and smoke absorbed reagents have been disabled for a while

**Comment by CaptainSqrBeard** [comment]
Reaction was removed because of reagent dupe but event itself doesn't have any reagents that could be abused. I don't think that is a reason to remove event.

https://github.com/space-wizards/space-station-14/blob/3269438ea8c441c51a6638aa2193585974e2e2cb/Content.Server/StationEvents/Components/VentClogRuleComponent.cs#L18

**Comment by deltanedas** [comment]
the only thing the event does is maybe slip people literally nothing else

**Comment by NancokPS2** [comment]
Eh, it's a funny event regardless. Does it have a high performance cost or something that makes it bad to keep?  
Maybe it dilutes chances for other events? idk

**Comment by keronshb** [comment]
Instead of removing the event, improve it.

**Comment by deltanedas** [comment]
keronshb that would require reworking smoke and foam to not be bad

**Comment by EmoGarbage404** [comment]
then do that.

**Comment by deltanedas** [comment]
:trollface:

**Comment by LankLTE** [comment]
> then do that.

i actually tried

it was miserable

**Comment by deltanedas** [comment]
the foam effect

**Pull request closed without merging**
