### PR TITLE
Nerf observer speed

### PR DESCRIPTION
**Pull request by metalgearsloth**
Mainly for streaming reasons over anything else because there's a lot of pop-in.

:cl:
- tweak: Lowered ghost movement speed.

### CODE REVIEW

**Comment by mirrorcult** [comment]
mappers wont like this

**Comment by Lamrr** [comment]
> mappers wont like this

Maybe we could have a different speed for admin ghosts?

**Comment by metalgearsloth** [comment]
I'm fine making aghost higher; realistically I have to wait moving around to observe anyway so going slow or fast is irrelevant. Warp atm also takes several seconds to stream everything in.

Ideally PVS range would be further but as is we probably shouldn't do that atm.

When the player list panel gets cleaned up (click to warp + sorting) I imagine the adminobserver experience would be significantly better.

**Review by mirrorcult — APPROVED** [review]
make aghost higher and this is fine i think

**Comment by ProfanedBane** [comment]
Justice for observer ghosts

**Pull request merged**
