### PR TITLE
move gamerule components to shared

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
the base components GameRule ActiveGameRule etc moved to shared

## Why / Balance
because they were in server the client showed gamerules in spawn menu :trollface:
so this fixes that

also good for future stuff probably

## Technical details
its quite shrimple

## Media
no thief rule

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
- everything from `Content.Server.GameTicking.Components` is now in shared
- `MinMax` of `Content.Server.Destructible.Thresholds` is now in shared

**Changelog**
no cl no fun

### CODE REVIEW

**Review by ElectroJr — APPROVED** [review]
I guess auto categorization doesn't really work with server only comps.
Would probably be nice to support somehow, though I'm not sure how.

**Comment by deltanedas** [comment]
easier way is to refactor refactor refactor :trollface:

**Comment by little-meow-meow** [comment]
image

:trollface:

**Comment by deltanedas** [comment]
what

**Pull request merged**
