### PR TITLE
Fire Axe resprite 45 degrees v3

### PR DESCRIPTION
**Pull request by AndreyCamper**
Fire Axe is now correctly rotated 45 degrees v3

Issue #28847

icon

### CODE REVIEW

**Comment by TheShuEd** [comment]
It's amazing, you replaced 1 sprite, and fucking broke all the tests.

**Comment by nikthechampiongr** [comment]
> It's amazing, you replaced 1 sprite, and fucking broke all the tests.

I think github just had a moment. All the tests failed due to "internal action error"

**Comment by TheShuEd** [comment]
yea

**Comment by Plykiya** [comment]
tests all pass, godspeed

**Pull request merged**
