### PR TITLE
add sprite to vent underpressure lockout

### PR DESCRIPTION
**Pull request by slarticodefast**
## About the PR
Since we had a lot of low pressure events lately I had the idea to add a sprite to the vents to visualize the underpressure lockout.

## Why / Balance
This was already shown on the vent examination text, but nobody really reads those and this should quickly show an atmos tech if they have to override the lockout via the air alarm to refill a room.

## Technical details
Added new sprite I quickly recolored from vent_in.png
I'm not sure if I need to adjust the copyright line in meta.json for this.

## Media
Screenshot (181)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Probably should check if this breaks something in #29493

**Changelog**
:cl:
- add: Air vents now have yellow lights if they are in under-pressure lockout.

### CODE REVIEW

**Comment by deltanedas** [comment]
this will look very similar to the tg passive vent sprite if anyone bothers porting it (currently passive vent just uses the air vent unpowered sprite)

**Comment by slarticodefast** [comment]
> this will look very similar to the tg passive vent sprite if anyone bothers porting it (currently passive vent just uses the air vent unpowered sprite)

If you have any suggestions for another color I can change it. Red is already in use for the siphoning mode of GasVentPump.
Our passive vents currently have no lights and I think it should be fine if they stay that way, feels fitting for the name.
vent_off

**Review by Partmedia — APPROVED** [review]
Thanks for your work on this. The code looks good to me. I'm leaving this open in case anyone wants to chime in or help with the sprites; otherwise I intend to merge this.

**Comment by slarticodefast** [comment]
I had another look at the [tg sprites](https://github.com/tgstation/tgstation/blob/master/icons/obj/machines/atmospherics/unary_devices.dmi) and could not find a similar one in there. Was it maybe another fork? The sprites at the bottom are for the passive vent. I could port them over as well, so we have a visual distinction to the shutoff state.

unary_devices

**Comment by ShadowCommander** [comment]
Yellow looks fine. I'd make it more saturated and maybe a bit brighter though to differentiate it from the vent border.

**Comment by slarticodefast** [comment]
vent_lockout
vent_lockout_copy

Made it slightly more saturated and bright. More than that was looking weird, so this should be enough I hope.

**Comment by PJB3005** [comment]
Shouldn't the fan not be spinning if it's locked out? It's not pushing air.

**Comment by slarticodefast** [comment]
> Shouldn't the fan not be spinning if it's locked out? It's not pushing air.

Good catch. I could change this if wanted. Though technically the vent is still leaking a small amount of air even in lockout mode.

**Comment by Partmedia** [comment]
> Good catch. I can change this if wanted. Though technically the vent is still leaking a small amount of air even in lockout mode. And the fan can still spin in vacuum, the vent is in active mode after all.

Yes, due to #15931 vents under lockout are still "leaking" a bit.

I think this is a minor issue, I'll leave it up to you how you want to fix the sprite (if at all). Both ways are probably fine, and in any case having any sort of indication is better than none.

**Comment by slarticodefast** [comment]
I made a sprite for the lockout lights without the fan moving and will do some ingame testing to see what looks better.

**Comment by slarticodefast** [comment]
Changed the lockout sprite to a version without the fan spinning. Also did a minor code adjustment so that the lockout state and visuals change correctly even if there is no air in the input pipe.

**Review by Partmedia — APPROVED** [review]

**Comment by Partmedia** [comment]
Thanks!

**Pull request merged**
