### PR TITLE
Grey Matter Addition and Slime Organ Tweak

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I added 5u of Grey Matter into Humanoid Brains, it currently does 20 cellular damage total. Prions are scary
GREY MATTER CANNOT BE EXTRACTED FROM THE BRAIN IN ANY WAY. (Except Solutions manager)
Drink:
      effects:
      - !type:SatiateHunger
        factor: 1.5
    Poison:
      effects:
      - !type:HealthChange
        damage:
          types:
            Cellular: 2

Grey Matter: Thought juice, the stuff that leaks out of your ears.

## Why / Balance

Gib to Brain eat Combo is far too easy to round remove someone. You can still grind up, hide or throw away the brain just fine.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image
image
image

## Breaking changes

**Changelog**

- tweak: Humanoid Brains are now stuffed with Grey Matter, not UncookedProteins
- tweak: Slime Organs grind into Slime

### CODE REVIEW

**Comment by FungiFellow** [comment]
Am Retaking Screenshots, but it overall works well.

**Comment by UbaserB** [comment]
uh oh.. people are gonna start grinding brains for this poison lol

**Comment by FungiFellow** [comment]
> uh oh.. people are gonna start grinding brains for this poison lol

I should have stated this in the post, BUT you cannot grind the brain to acquire Grey Matter, it just gives Uncooked Proteins.

**Comment by FungiFellow** [comment]
The whole purpose of this is to disincentivize eating Brains straight out.

**Comment by UbaserB** [comment]
> The whole purpose of this is to disincentivize eating Brains straight out.

ok fair

**Comment by potato1234x** [comment]
most maps have maint kitchens and you can just as easily make a brain burger. good pr.

**Comment by Kadeo64** [comment]
> most maps have maint kitchens and you can just as easily make a brain burger. good pr.

yeah and that takes more effort than playing lizard > gibbing > eating brain > instantly deleted

**Comment by potato1234x** [comment]
> > most maps have maint kitchens and you can just as easily make a brain burger. good pr.
> 
> yeah and that takes more effort than playing lizard/arachnid > gibbing > eating brain > instantly deleted

yeah i said it was good pr im agreeing

**Comment by veprolet** [comment]
Firstly: this is a very nice PR. I like both the idea and the execution. If i were to be nitpicky, I'd suggest to move the slime organ grinding to a different PR so it could be merged independently of the outcome of this PR, but I'm not going to be, because this is already a high quality PR compared to the established standard.

It's however not presently true that "GREY MATTER CANNOT BE EXTRACTED FROM THE BRAIN IN ANY WAY. ". You could:
1. Get a dead mouse.
2. Draw 35u of blood, so there is 15u left.
3. Feed them a brain.
4. Time it just right (I think it's about 20-22s from the time you start feeding to the time you start drawing, but I got the numbers just off the top of my head).
5. Draw 15u blood just as the brain starts metabolizing from the stomach.
6. Separate blood from mixture.
7. Enjoy your yield of 2.5u of gray matter per mouse and brain
I concede that this is a somewhat contrived way to get it and I don't think it's problematic for this chemical. Brains are usually tricky to come by and if you can get them in such a large amount, the access to this chemical probably won't make a difference to you, as it isn't even very lethal, just very inconvenient for the recipient.

**Comment by FungiFellow** [comment]
> I concede that this is a somewhat contrived way to get it and I don't think it's problematic for this chemical. Brains are usually tricky to come by and if you can get them in such a large amount, the access to this chemical probably won't make a difference to you, as it isn't even very lethal, just very inconvenient for the recipient.

So here's the thing, Phalanxamine heals genetic damage and has a full syringe placed in every radiation medkit. 2.5 is only 10 damage per brain. At that point several poisons are more powerful. So I feel that such a roundabout way is incredibly inefficient unless you can reliably acquire and process brains.

**Comment by FungiFellow** [comment]
I'll open up a feedback thread on discord to get opinions on it. Losing 20% of your HP unless you get a specific medicine made is still pretty gnarly

> I think the damage amount should be increased tbh 100% round-removing Urist Mcfeet that fell into disposals and wanted to get borged shouldn't come cheap.

**Comment by deltanedas** [comment]
> Losing 20% of your HP unless you get a specific medicine made is still pretty gnarly

so dont eat brain easy

**Comment by veprolet** [comment]
> I'll open up a feedback thread on discord to get opinions on it. Losing 20% of your HP unless you get a specific medicine made is still pretty gnarly

Link to the discussion for posterity: https://discord.com/channels/310555209753690112/1008709214006427689/1213281663862317187

**Comment by K-Dynamic** [comment]
> I'll open up a feedback thread on discord to get opinions on it. Losing 20% of your HP unless you get a specific medicine made is still pretty gnarly

Don't eat the brain then

Idk about other species but humans really shouldn't be cannibalising - professionals have standards

**Comment by thebadman4662** [comment]
> > Losing 20% of your HP unless you get a specific medicine made is still pretty gnarly
> 
> so dont eat brain easy

Or just implement NLR into LRP borgs and there is no reason to eat brains into first place

**Comment by Kadeo64** [comment]
> Or just implement NLR into LRP borgs and there is no reason to eat brains in first place

syndieshitters will still eat brains because syndieshitters hate fun

**Comment by UbaserB** [comment]
cant wait to eat a brain and then proceed to inject myself with ipecac so i can extract the grey matter through the vomit on the floor

**Pull request merged**
