### PR TITLE
Job species requirements

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR

Rework #17930

Allow setting job requirement to specific list of species or invert that list to restrict.

## Technical details

- Now uses `JobRequirement`
*but JobRequirement sucks because hard linked to timer system*

- Not set any requirements for jobs in this PR

## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Does this handle selecting a job then swapping species afterwards?

**Comment by Morb0** [comment]
> Does this handle selecting a job then swapping species afterwards?

uh, nope...

**Comment by Partmedia** [comment]
What jobs are you proposing to be restricted by species in the future? To me, restricting job by species doesn't seem like the right way to go.

**Comment by mirrorcult** [comment]
this is good behavior to have available for downstreams

(also i need this for ashwalker role for emisse's lavalandstation)

**Comment by Partmedia** [comment]
Thanks for the clarification. This would have been good to have in the PR description :)

**Comment by JoeHammad1844** [comment]
can this make ERT human only?

**Comment by metalgearsloth** [comment]
@Morb0 are you still working on this? (Also tooltips have markup so you can colour the species too if wanted).

**Pull request closed without merging**
