### PR TITLE
hampter join the revolution

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

## Why / Balance
good + he can wear welding mask to protect

## Technical details
flashable

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
Piep!

### CODE REVIEW

**Comment by 27alaing** [comment]
i think hamster can wear glasses too so this is very cool

**Comment by lzk228** [comment]
i think that component should be at some of base mobs

**Comment by deltanedas** [comment]
it was removed at some point to prevent flashing carp

also non-sentient animals dont make sense to be convertable

**Comment by EmoGarbage404** [comment]
General consensus is to deny this pr with the reasoning that standard station ghost roles don't need further senseless interactions with antagonists and and crew, with hamlet being a pretty offensive example. Standard ghost roles, ideally, should just be a simple way for players to get back into the round in a low-impact manner. Station pets don't need to be inducted into revolutions or gain wild random abilities or interactions.

**Pull request closed without merging**
