### PR TITLE
Handheld radio rework

### PR DESCRIPTION
**Pull request by neuromachinery**
## About the PR

I reworked handheld radio item, and made it much more versatile tool. Now it can be tuned to any of dedicated radio channels (currently 10, within 1390-1399 range, but easily expandable), and it now has same mic/speaker functionality of an intercom.
## Why / Balance

Handheld radios were primarily used by cargo miners because of lack of telecom servers on missions, and no one else, because there is only one channel, and it has annoying habit of repeating after you. With this new functionality, radios can be used by sec, command, or even antags as a slightly less secure way of isolated communication.

For example, HoS could issue officers handheld radios so they could work better in group. At the same time, they run the risk of being overheard by someone with bad intentions.
As another example, Quartermaster can tune in to his miners somewhere on a mission, and turn off his mic, so he can give orders, talk, and not spam all of this to the miners, while being able to hear important info.
And even syndicate agents can use those radios to cooperate without wasting precious telecrystals on communication equipment. Not without a tradeoff, of course.

The code is a modified version of intercom's code, with pieces of cargo's request computer's code, all pieced together to a handheld radio item. And, since there are now effectively 10 different handheld channels, and I couldn't find a better solution, I just added them as prototypes to the respective file.
Also in the process of creating this, I fixed this issue (#18022) by accident, since it was tied to intercom code.
## Media

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Changed prototype ID from RadioHandheld to HandheldRadio.
**Changelog**

:cl:
- tweak: Handheld radios can now turn off mic or speaker independently. And they can be tuned to one of dedicated radio channels.
- fix: Fixed intercoms not changing channels correctly.

### CODE REVIEW

**Comment by forgotmyotheraccount** [comment]
Would it be possible to enlarge the Microphone & Speaker buttons? I can imagine "Speak" causing some confusion.

**Comment by deltanedas** [comment]
a solution to the 10 identical prototypes issue could be to separate RadioChannelPrototype's actual data into virtual RadioChannel, similar to silicon laws.
then the handheld radio can generate a RadioChannel based on default handheld prototype and setting requency

**Comment by notquitehadouken** [comment]
bro what happened to aspid

**Comment by neuromachinery** [comment]
> Would it be possible to enlarge the Microphone & Speaker buttons? I can imagine "Speak" causing some confusion.

I'll try to do that

> bro what happened to aspid

I don't really know, probably did something wrong with git while updating to latest version

> a solution to the 10 identical prototypes issue 

I'm not sure I can do this, but I'll try, thank you

**Review by lzk228 — CHANGES_REQUESTED** [review]
use migration.yml instead of manual map editing
also, 10 frequencies it's too few

**Comment by deltanedas** [comment]
allowing more frequencies would be trivial with it rewritten to dynamically create radio channels

**Comment by deltanedas** [comment]
also funny idea is if you select a channel used by an actual radio channel it replaces messages with garbled noise (encryption key = memfrob)

**Comment by neuromachinery** [comment]
@deltanedas, unfortunatly, I can't figure out how to do what you've described, except for having one abstract prototype with all the repeating information, and have all the other ones copy it from it like this:
`- type: radioChannel
  id: Handheld
  name: chat-radio-handheld
  frequency: 1330
  color: "#d39f01"
  # long range since otherwise it'd defeat the point of a handheld radio independent of telecomms
  longRange: true
  abstract: true
- type: radioChannel
  id: Handheld0
  parent: Handheld
  keycode: "0"
  frequency: 1390
- type: radioChannel
  id: Handheld1
  parent: Handheld
  keycode: "1"
  frequency: 1391`
  Also, I couldn't get it working without assinging unique keycodes to each of them.
  
  @lzk228, I thought that it would be best not to go overboard, and start with at least a little bit. And since I'm not using any sophisticated system to make hundreds of channels, but just adding stuff to a file, I thought that adding like 50 would be too much, making the file twice as large

**Comment by deltanedas** [comment]
radio channel isnt parented iirc and either way its ugly
ill try implement virtual RadioChannel at some point

**Comment by lzk228** [comment]
> @lzk228, I thought that it would be best not to go overboard, and start with at least a little bit. And since I'm not using any sophisticated system to make hundreds of channels, but just adding stuff to a file, I thought that adding like 50 would be too much, making the file twice as large

yeah, ok

`radioChannelPrototype` can't has `abstract` and `parent`, it only belongs to `entityPrototype` iirc

**Comment by neuromachinery** [comment]
@lzk228, Oh, I implemented it, ran the game and everything works. But now I'm getting failed checks from YAML Linter, which points to the same problem.
I guess I should undo it.

@deltanedas I would love to try to do it myself, if I knew where to begin

**Comment by neuromachinery** [comment]
@forgotmyotheraccount 
> Would it be possible to enlarge the Microphone & Speaker buttons? I can imagine "Speak" causing some confusion.
image
I hope this works

**Review by lzk228 — CHANGES_REQUESTED** [review]
just put aspid map from master in your branch and merge master

**Comment by neuromachinery** [comment]
@lzk228 I already copied and pasted aspid map from upstream to my branch and then commited&pushed. I can't see what exactly is wrong with aspid? Also, why merge master?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
You've copy-pasted most of this code, please don't do that, make it reuseable.

Also you have a lot of extra commits making breaking changes like dummy files.

**Comment by neuromachinery** [comment]
> Also you have a lot of extra commits making breaking changes like dummy files.

That might be related to my git mistakes.
Can you please point out dummy files and in which commits they were created?

> make it reuseable.
I'll try to do that.

**Comment by neuromachinery** [comment]
@deltanedas Thank you, this will make it much easier, but now I am stuck at trying to make my changes reusable, and at the same time I don't know how to update my PR using your radio rework.

**Comment by deltanedas** [comment]
well first you have to wait for it to be merged :trollface:

**Comment by neuromachinery** [comment]
Well, at least I could try to make the UI reusable, but I am stuck. The thing I made does not work. Should I push it here, unfinished, to get some advice?

**Pull request closed without merging**
