### PR TITLE
Tools resprite

### PR DESCRIPTION
**Pull request by Deahaka**
## About the PR 
That is combination of [2020](https://github.com/TauCetiStation/TauCetiClassic/pull/4832) and [2022](https://github.com/TauCetiStation/TauCetiClassic/pull/9368) sprites from TauCetiStation.
Sponsored by the [Theta Community](https://github.com/ThetaStation/ThetaStation).

**Screenshots**

Before
OLD
After
NEW
and some else tools
ELSE
multitool is optional (recreated by me from not merged PR).

**Changelog**

:cl: LilJard
- add: Added new sprites for tools.

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
look out of place, and a consistent art-style is something ss14 is striving for

**Comment by Peptide90** [comment]
Very shiny and HD. I’d definitely take them for a fallout fork though, good work non the less.

**Comment by moonheart08** [comment]
Too out of place for SS14 upstream.

**Comment by Deahaka** [comment]
no problem

**Pull request closed without merging**
