### PR TITLE
Greatly improve the usability of the Gas Analyzer.

### PR DESCRIPTION
**Pull request by Mervill**
## About the PR

Greatly improve the usability of the Gas Analyzer. **None of the information the Gas Analyzer displays has changed** but I've made actually _using_ the gas analyzer much smoother:

- Fixed a bug where clicking an object with no relevant gas data would still cause the Analyzer window to close when that object went out of range.
- The range of the Gas Analyzer is now equal to the standard interaction range. Previously the range was subtly (and not intentionally) shorter.
- Using the Analyzer in your hand has proper enable/disable behavior.
- The Analyzer now says "The object went out of range." when the analyzed object goes out of range instead of just shutting off with no explanation. 
- The Analyzer no longer shuts down when the analyzed object goes out of range. You'll lose the info about the analyzed object, but the analyzer will simply switch to the environment tab instead of shutting down.
- Don't show an "out of reach" message for objects out of reach. Tools in the game generally don't work like this. Since the range of the Analyzer is equal to the regular interaction range, the standard red outline should be sufficient. 
- If the Analyzer is open to the environment tab and a new object is analyzed, switch the the device tab automatically.

## Media

This before gif shows some of the weird behavior 
analyzer-bad

This gif shows some of the new behavior
analyzer-good

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Gas Analyzer won't spuriously shut down for seemly no reason.
- tweak: The Gas Analyzer will always switch to the device tab when a new object is scanned.
- fix: The Gas Analyzer's interaction range is now equal to the standard interaction range
- fix: Clicking the Gas Analyzer when it's in your hand has proper enable/disable behavior.

### CODE REVIEW

**Comment by lzk228** [comment]
finally🙏

**Comment by maximus-not** [comment]
praise be

**Comment by Boaz1111** [comment]
CL should probably be clearer as to what has been improved

**Comment by Mervill** [comment]
Ok I updated the CL

**Pull request merged**
