### PR TITLE
Add UsedImplicitly to visualizers and entity systems

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Because Rider is annoying sometimes.

### CODE REVIEW

**Comment by Zumorica** [comment]
How about you add `[MeansImplicitUse]` to the base classes instead so we don't have to add the attribute to each inheritor?

**Comment by DrSmugleaf** [comment]
> How about you add `[MeansImplicitUse]` to the base classes instead so we don't have to add the attribute to each inheritor?

I tried and it didn't work for me, only when used with annotations.

**Comment by Zumorica** [comment]
Weird, I tried doing it *before* posting the comment and it worked. Then again I'm on Rider EAP...

**Comment by DrSmugleaf** [comment]
> Weird, I tried doing it _before_ posting the comment and it worked. Then again I'm on Rider EAP...

Now it doesn't even show anything as unused even without any attributes.

**Comment by Zumorica** [comment]
Rider moment

**Pull request merged**
