### PR TITLE
Add movement animations to some animals

### PR DESCRIPTION
**Pull request by ravage123321**
## About the PR
I have added motion animation to the following list of animals: 
Walter, Corgi, Ian, Lisa, puppy, Cat, Cat2, kitten, SpaceCat, Syndicat, Cak, Caracal, McGriff, Breaddog

I slightly adjusted the kitten's sprite, because it had a different size in front and back, also removed the orange pixels on the white corgi fur
Renamed the name of the breaddog images to match the rest
(recreated PR because had problems) 

The only problem I've encountered is that cats are pets, despite the fact that they have a Parent of ordinary cats and they use their sprites, they don't get animation. I can fix this by just adding a component for them, but I guess I'd better wait for comments, maybe I made a mistake.

## Why / Balance
At the moment, the game has motion animations, but a very small list of animals

## Media
https://github.com/user-attachments/assets/7db8c40c-9a91-4eef-871f-fe204ceec60f

https://github.com/user-attachments/assets/cb963e69-3a95-4cc0-bc39-e8e5a76d3d97

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added movement animation to animals!

### CODE REVIEW

**Comment by slarticodefast** [comment]
The test fail seems to be real, something is wrong with the .rsi

**Comment by ravage123321** [comment]
> The test fail seems to be real, something is wrong with the .rsi

yep, because

> Renamed the name of the breaddog images to match the rest

**Comment by ravage123321** [comment]
it's just that all animals (including catcake) have the name of the sprite base from the name of the entity itself, the bread dog is the only one for whom it's just base. But I can remove this

**Comment by ravage123321** [comment]
A breaddog sprites work normally in game

**Comment by slarticodefast** [comment]
You still have the old base.png and dead.png files in the breaddog.rsi folder, but removed them from the meta.json, which is causing the error.

**Comment by ravage123321** [comment]
> You still have the old base.png and dead.png files in the breaddog.rsi folder, but removed them from the meta.json, which is causing the error.

oh yeah my fault sorry haha

**Comment by TheShuEd** [comment]
We discussed and decided to refuse to accept this PR.
The animations look weird, and having them only makes it worse.

If you can improve the animation sprites, send them to any Art Lead in discord for discussion and this PR can be reopened.

**Pull request closed without merging**
