### PR TITLE
Shark plushies now goes rawr on hit.

### PR DESCRIPTION
**Pull request by Minemoder5000**
## About the PR

The shark plushies now rawrs when hitting something, or being thrown
## Why / Balance

Parity with the lizard plushie
## Technical details

A few lines in a .yml file
## Media

https://github.com/user-attachments/assets/c12b7e5a-6580-4c99-a846-136719635de5

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Minemoder
- tweak: The shark plushie now goes rawr when hitting something or being thrown.

### CODE REVIEW

**Comment by TheShuEd** [comment]
P0: Critical

**Review by Errant-4 — APPROVED** [review]
Plushies playing two sounds when thrown should be addressed, although it's a pre-existing issue so I guess we can proceed with this PR regardless

edit: Uuh, re-running failed test but I think it's a heisen

**Comment by Minemoder5000** [comment]
> Plushies playing two sounds when thrown should be addressed, although it's a pre-existing issue so I guess we can proceed with this PR regardless

I think it makes a noise when hitting something, and another noise when landing on the ground

**Review by slarticodefast — APPROVED** [review]
important PR

**Pull request merged**
