### PR TITLE
New workflow to apply the pr approved label

### PR DESCRIPTION
**Pull request by AJCM-git**

### CODE REVIEW

**Comment by 0x6273** [comment]
Github already has `review:approved` search filter, so this seems kinda redundant.

**Comment by AJCM-git** [comment]
> Github already has `review:approved` search filter, so this seems kinda redundant.

The use case is for skimming the pr list and quickly differentiating between whats approved and whats  not, not for searching approved prs

**Review by Tayrtahn — APPROVED** [review]

**Comment by 0x6273** [comment]
> The use case is for skimming the pr list and quickly differentiating between whats approved and whats not, not for searching approved prs

The pr list already shows review status like "approved" or "changes requested."

**Comment by 0x6273** [comment]
This workflow also doesn't seem to remove the label if someone requests changes.

**Comment by Tayrtahn** [comment]
> The pr list already shows review status like "approved" or "changes requested."

Mm, I don't think it does for "approved"

**Comment by AJCM-git** [comment]
> > The use case is for skimming the pr list and quickly differentiating between whats approved and whats not, not for searching approved prs
> 
> The pr list already shows review status like "approved" or "changes requested."

Nah, it only does for requesting changes (i approved this one for example)

image

**Comment by 0x6273** [comment]
> > The pr list already shows review status like "approved" or "changes requested."
> 
> Mm, I don't think it does for "approved"

Somehow this repo seems to have that disabled for the master branch. It shows for PRs targeting different branches like the april fools branch.

image

**Comment by Tayrtahn** [comment]
> This workflow also doesn't seem to remove the label if someone requests changes.

This is a good point though.

**Review by Tayrtahn — APPROVED** [review]

**Comment by AJCM-git** [comment]
> This workflow also doesn't seem to remove the label if someone requests changes.

i mean you have to apply the awaiting changes labels yourself anyways 

> > > The pr list already shows review status like "approved" or "changes requested."
> > 
> > 
> > Mm, I don't think it does for "approved"
> 
> Somehow this repo seems to have that disabled for the master branch. It shows for PRs targeting different branches like the april fools branch.
> 
> image

ah thats cool, gonna ask if there is a way to enable this
For the other thing, we already have to manually remove "Awaiting changes" so you can remove the label when adding that one

**Comment by metalgearsloth** [comment]
failing

**Comment by AJCM-git** [comment]
> failing

AFAIK its failing cuz the action in this pr doesnt have the perms to apply the label in the main repo.

**Comment by slarticodefast** [comment]
Can we get this workflow merged? I think it would be useful with the new maintainer policy since we now need a second maintainer to merge after approval. The label makes it easy to find PRs which are waiting for that.

**Review by VasilisThePikachu — APPROVED** [review]
image

Works on external repo, this is just GitHub protecting us from someone running malicious actions code.

**Comment by VasilisThePikachu** [comment]
Although I would rather we figure out why the ``review:approved`` tag does not work

**Comment by VasilisThePikachu** [comment]
Also for future GitHub actions PRS, please prove your pr works by making a new fork of the repo (probably will need you making a new org) and running your action in there.

**Pull request merged**
