### PR TITLE
Add movement animations to some animals

### PR DESCRIPTION
**Pull request by ravage123321**
## About the PR
I have added motion animation to the following list of animals: 
Walter, Corgi, Ian, Lisa, puppy, Cat, Cat2, kitten, SpaceCat, Syndicat, Cak, Caracal, McGriff, Breaddog

I slightly adjusted the kitten's sprite, because it had a different size in front and back, also removed the orange pixels on the white corgi fur

## Why / Balance
At the moment, the game has motion animations, but a very small list of animals

## Media
https://github.com/user-attachments/assets/7db8c40c-9a91-4eef-871f-fe204ceec60f

https://github.com/user-attachments/assets/cb963e69-3a95-4cc0-bc39-e8e5a76d3d97

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added movement animation to animals!

### CODE REVIEW

**Comment by UmnayaSvinka** [comment]
Very mindful, very demure

**Comment by saga3152** [comment]
https://github.com/user-attachments/assets/f51832ce-3996-40dc-9bf1-e51bc95edbe9

**Comment by saga3152** [comment]
https://github.com/user-attachments/assets/c86b6063-ca39-44c2-9cf3-4c7eace53d39

**Comment by Peptide90** [comment]
Having experimented with movement animations myself, does the animation always play even when idle? Or do the animations only play when controlled by a player?

Ideally the noMovement sprite is used when not moving, but the videos seem to show the animals always moving.

**Comment by ravage123321** [comment]
> Having experimented with movement animations myself, does the animation always play even when idle? Or do the animations only play when controlled by a player?
> 
> Ideally the noMovement sprite is used when not moving, but the videos seem to show the animals always moving.

second one, working only when contolled by a player

on video animals walking because I did a bug (controlled animal, hold button, then ghost by bind, so after this animation working every second)

**Comment by UmnayaSvinka** [comment]
why did you close it?????? 😭

**Pull request closed without merging**
