### PR TITLE
Meta station overhaul

### PR DESCRIPTION
**Pull request by Nox38**
## About the PR

A full upgrade/overhaul of Meta station. Most departments have received a overhaul, and the power and atmos systems have been fixed.

## Why / Balance

Many parts of Meta have not been updated since the original port, and a incredible amount of buttons, air alarms, and APCs are broken or missing. Also, the layout of many of the departments could use improvement.

## Media

Meta-0

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Updates:
11/29/24: Rebuilt salvage, disposals, and their maint area. Moved viro to south of medbay (was this a good choice?), added a escape pod to medbay which can be publicly accessed.
12/4/24: Started sci rebuild
12/9/24: Finished sci rebuild and fixed all (current) issues.
12/11/24: Fixed the issue I was having with the new meta update breaking mine, and updated botany.
12/12/24: Preparing for security/dorms improvements.
12/26/24: Security overhaul is finished!
12/30/24 fixed all bugs, ready for review.

**Changelog**
:cl:
- A overhaul or full lookover for every single tile in the station except engi and dorms (maybe later).
- All APCs, button/switches, air alarms,  vents/scrubbers, firelocks, and other connectables rebuilt to be more sane (No more instant chain-spacing!)
- Ground up rebuild of science (They had it coming).
- Labeled doors!
-->

### CODE REVIEW

**Comment by Nox38** [comment]
god I hope I did this one correctly finally

**Comment by MilenVolf** [comment]
What a big changelog you have. I think these should be moved into description section. Leave a brief summary of the changes in the changelog

**Comment by Nox38** [comment]
@K-Dynamic @MilenVolf ill change all of those things

**Comment by Emisse** [comment]
meteor net on arrivals got removed

**Comment by Nox38** [comment]
I will be rebuilding the entirety of sci and most of medbay, as well as fixing anything that gets commented here.

**Comment by Krovotushka** [comment]
PA room should have reinforced walls since regular ones are still not so good at protecting from radiation

**Comment by Nox38** [comment]
@K-Dynamic I did not know I removed the arrivals evac pod, ill make sure thats working. I removed most maint borg chargers in favor of putting one in every department for players who dont have the maints memorized.

**Comment by Djungelskog2** [comment]
> I like the overall modernisation but some changes I'm not a fan of:
> 
> Disposals:
> 
> * Disposals lacking space exit or belt for dangerous or unrecyclable items
> 
> Sci:
> 
> * Personally preferred old layout, new version has a bit too much space (see the room above RD's office which appears to just host a tech disk terminal and computer, or the 2x4 void of reinforced walls in the locker room)
> * Seems to be two lockers clipping each other in the sci locker room
> * Putting two artifact chambers side-by-side in the same room means xenoarch is fucked after a single explosion
> 
> Eng:
> 
> * Station anchor room could be marked with a poster

agreed, dont really know what the science redesign aims to do and I feel it just makes it worse in general, there also appears to be a massive lack of firedoors near xenoarch which would be a good change.

**Comment by MilenVolf** [comment]
Something really gone wrong, try revert last commit. This commit [083e95b](https://github.com/space-wizards/space-station-14/pull/33506/commits/083e95b0de049f41aa303878a3458653f08098cc)

**Comment by Nox38** [comment]
working on that...

**Comment by Nox38** [comment]
finally fixed.

**Comment by Djungelskog2** [comment]
why is there so much gamerloot

**Pull request merged**
