### PR TITLE
Thief toolbox minor rebalance & description clean-up

### PR DESCRIPTION
**Pull request by K-Dynamic**
## About the PR
Thief toolbox kit descriptions are now flavourful and accurately label items

Minor rebalance and fluff item removal on thief kits

## Why / Balance

Thief kit descriptions were misleading; they already spawned lots of items but also unlisted metagameable fluff.

1. Caught out new thieves who didn't expect extra items to suddenly store or hide

2. Experienced thieves would waste time dumping or hiding them anyway to avoid metagaming by other players
   - master-at-arms hat would be especially egregious as only thieves spawned them
   - knowing a vodka bottle spawns from a chemistry kit meant tracking vodka bottles around maps and scanning them

Subsequently almost all fluff has been removed, as we would otherwise have to list every fluff item in thief kit descriptions. 

Descriptions were made more cryptic and flavourful to reflect the nature of thieves. They are also more accurate, such as removing an erroneous reference to a portable crew monitor in the communicator's kit (#28102).

Some kit were also rebalanced where it 'made sense,' with reasoning stated below.

### Chameleon
- added barber scissors
   - you can now disguise your hair too

### Breacher (formerly bearcatcher)
- removed clown mask
   - fluff
- added remote signaller
   - thief can detonate C4 without drawing attention by being too close or searching for remote signaller to begin with
   - kit could do with another C4 (three in total) and is questionably balanced for engi thieves

### Anatomy (formerly chemistry)
- removed vodka bottle
- added empty shaker
   - supposedly could metagame as no one carries a vodka bottle, and any that were found could be forensically scanned - replaced with empty shaker for chem purposes
- changed name because barely any chems, may change in the future

### Syndie
- removed master-at-arms hat
   - fluff, metagamed - especially bad as only thieves could acquire this
   - supposedly not contraband or valid on MRP so might reconsider, still prone to being tailed or metagamed imo

### Sleeper (formerly sleepwalker)
- removed syndie pyjamas, hat and bedsheet
   - fluff, metagamed - pyjama bag loot does exist but having these three together is risky
- removed a nocturine bottle
   - 90u total nocturine way too much, even 60u is a lot - might add vestine in the future if another or all nocturine bottles are removed
- kit is too highly valuable with nocturine and hypopen, unsure how to balance

### Communicator
- removed thief figurine
   - fluff, metagamed - no one maps figurine
- briefcase overhauled - only kept jensen coat, sunglasses, 20k spesos, replaced combat gloves with black gloves
   - briefcase much less suspicious on search
   - free combat gloves removed, tends to be valid
- portable crew monitor was already removed via #24761 
- kit is weak, especially without chameleon stamp in yaml comment

### Smuggler
- removed void cloak
   - fluff, metagamed

## Technical details

yaml and .ftl changes only

thief_toolbox_sets.yml
briefcases.yml
backpack.ftl

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

:cl: Damn Feds
- tweak: thief toolbox kits now better describe contents

### CODE REVIEW

**Comment by Aexxie** [comment]
Descriptions need grammatical work and tweaking, a lot of them feel confusing.

**Comment by deepdarkdepths** [comment]
Some fluff should not be removed. A thief wearing a master at arms hat is a beacon to syndicates or other antagonists who want to try and work together. If you're wearing a hat and get taken in by security just ahelp..
Make it an option in the kit whether you want fluff items or not instead.

**Comment by deepdarkdepths** [comment]
> > A thief wearing a master at arms hat is a beacon to syndicates or other antagonists
> 
> if security isnt allowed to metagame the stupid hat syndies shouldnt either
> 
> if you want thieves to work with syndies give them codewords when using the syndie kit, maybe even an encryption key. i have seen thieves get metagamed by sec for the valid hat far more than ive seen syndies approach them

Why should syndies not be allowed to "metagame" what the hat means when they have knowledge of basically everything else

**Comment by Aexxie** [comment]
> > > A thief wearing a master at arms hat is a beacon to syndicates or other antagonists
> > 
> > 
> > if security isnt allowed to metagame the stupid hat syndies shouldnt either
> > if you want thieves to work with syndies give them codewords when using the syndie kit, maybe even an encryption key. i have seen thieves get metagamed by sec for the valid hat far more than ive seen syndies approach them
> 
> Why should syndies not be allowed to "metagame" what the hat means when they have knowledge of basically everything else

Mechanically enforce things, not create more admin workload. Just because you aren't supposed to know doesn't mean your actions won't be affected.

**Comment by deltanedas** [comment]
> Why should syndies not be allowed to "metagame" what the hat means when they have knowledge of basically everything else

im not saying that sec shouldnt know the valid hat is valid, the hat just shouldnt exist
if you really want this then just give thieves a hud like nukies so syndies can find them easier without sec metagaming :trollface:

**Comment by Everturning** [comment]
syndie kit is meant to sound like syndicate. it's a pun. syndicate kit doesnt have this.

**Comment by mirrorcult** [comment]
why bother renaming it to set, kit is a more fun word

**Comment by K-Dynamic** [comment]
> Descriptions need grammatical work and tweaking, a lot of them feel confusing. Names feel unappealing and very repetitive. "Kit" worked far better than "set" in this scenario

> why bother renaming it to set, kit is a more fun word

I can easily rename everything from kit to set (especially realising syndie kit was a pun), but can I get some pointers for grammatical issues? I'll just go back to original text if I don't get a response in the next two hours

With regards to thief and syndie cooperation, they literally have a syndie pAI to tap into syndie comms; it's always been on the traitor to tap the thief's shoulder, whether by seeing their MAA hat or getting syndie comms

**Comment by EmoGarbage404** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by K-Dynamic** [comment]
Reopen

**Pull request merged**
