### PR TITLE
Added cursed chair

### PR DESCRIPTION
**Pull request by Zymem**
## About the PR 

**Screenshots**

image

**Changelog**

:cl:Zyme
- add: Added ritual and cursed chair

### CODE REVIEW

**Comment by MeltedPixel** [comment]
How does the cursed chair get built? You should also add further implementation or building recipe for creating the cursed chair.

**Comment by Zymem** [comment]
Added a second chair and made the recipe for the cursed one "hidden". I added another file to Graphs/furnitures in order to make a multi-step recipe, not sure whether it's best to put the contents of it inside seats.yml.

**Review by ShadowCommander — APPROVED** [review]

**Comment by mirrorcult** [comment]
what is the purpose of the cursed chair

**Comment by mirrorcult** [comment]
is it just to look funny

**Comment by Zymem** [comment]
> what is the purpose of the cursed chair

It screams when sat on, basically a meme object.
Saw a comment joking about it and thought it would be a good project to start learning yaml.

**Pull request merged**
