### PR TITLE
no plates from eating food

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- fix: Eating some foods no longer creates a plate out of thin air.

### CODE REVIEW

**Comment by Anzarot121** [comment]
What about supermatter?

**Comment by deltanedas** [comment]
we dont have supermatter in ss14 :trollface:

**Comment by Partmedia** [comment]
All of the foods you have listed have sprites that suggest there is a plate. Therefore, the plates do not come out of thin air.

With respect to matter creation, please fix this properly by adjusting the recipes to require the presence of the plate when the food is first made.

**Comment by deltanedas** [comment]
thats not how plates are meant to work in the long run
if sprite is the issue removing plate layer is fine, but sure immediately close it

**Pull request closed without merging**
