### PR TITLE
New station map Unity

### PR DESCRIPTION
**Pull request by brainfood1183**
Adds a new station map called unity station.

unity-0

The map is comparable in size to bagel at just under 4mb

here are some extra screenshots of the singularity working, the AME working and the atmos working.

Untitled-38
Untitled-39
Untitled-40
Untitled-41

### CODE REVIEW

**Comment by moonheart08** [comment]
Can't use that name.

**Comment by brainfood1183** [comment]
> Can't use that name. You know why.

Well name of the map is just called unity, i dont see why it is a big issue

**Comment by Just-a-Unity-Dev** [comment]
> > Can't use that name. You know why.
> 
> Well name of the map is just called unity, i dont see why it is a big issue

It's confused with the ~~dead~~ remake UnityStation

**Comment by brainfood1183** [comment]
> > > Can't use that name. You know why.
> > 
> > 
> > Well name of the map is just called unity, i dont see why it is a big issue
> 
> It's confused with the ~dead~ remake UnityStation

fair enough i guess i will remove this push request and remake it later

**Comment by EmoGarbage404** [comment]
You can just push changes and then reopen the pull request. You dont need to close it to make minor changes.

**Pull request closed without merging**
