### PR TITLE
apc tweaks/refactor

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- add datafield to everything for saving
- make the access logic cleaner
- add comment about HasAccess since it is evil
- general refactor

## Why / Balance
code

## Technical details
IsAllowed already checks if it has no access reader so no need to do that explicitly in apc

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by Partmedia** [comment]
When the main breaker is toggled, the APC does not update the load label to reflect the new load (0) until the UI is dismissed and re-opened.

**Comment by deltanedas** [comment]
thats an existing thing but should be easy to fix

**Comment by Partmedia** [comment]
> thats an existing thing but should be easy to fix

I suspected as much, but was hoping you might be able to take a look since you went to the trouble of refactoring. If you don't want to do this, that's fine, I'll merge as well. But if you are able to take a look at this issue, you get brownie points from me.

**Comment by deltanedas** [comment]
ok it reuses weird thing it had before for sending new ui state when apc state is updated but charge state is not, now that just updates ui every second so new load is shown shortly after toggling or adding/removing consumers
not sure about performance implications but should be ok

**Comment by Partmedia** [comment]
> ok it reuses weird thing it had before for sending new ui state when apc state is updated but charge state is not, now that just updates ui every second so new load is shown shortly after toggling or adding/removing consumers not sure about performance implications but should be ok

Any reason we can't only update the UI state after adding/removing consumers?

**Comment by deltanedas** [comment]
dont know power well enough also it would not account for power ramping

**Comment by Partmedia** [comment]
I see, that's fine, thanks.

**Review by Partmedia — APPROVED** [review]

**Pull request merged**
