### PR TITLE
More atmos tweaks

### PR DESCRIPTION
**Pull request by CrigCrag**
## About the PR

got called out in the latest status update so im changing stuff again.

Goal of this PR:
Nerf atmos hardsuit helmet
Buff atmos firesuit without making the firesuit helmet abusable.
Remove low pressure protection from the atmos firesuit, give it a bit more high pressure protection and temperature resistance.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Following a lawsuit, some unshielded asbestos was removed from the atmos hardsuit helmet due to health concerns. They are now less heat resistant.
- tweak: Nanotrasen has released a new model of atmos firesuit. This model is very resistant to heat, and has a bit more protection against high pressure. However, it is not rated for low pressure environments and its helmet is notably less sturdy.

### CODE REVIEW

**Comment by CrigCrag** [comment]
ready for review

**Comment by Myakot** [comment]
rip in pepperoni good suit, may you never be equipped again.

**Comment by Anzarot121** [comment]
Thank you for ruining what worked well. Given that you didn't know that it protects against vacuum, you probably have a lot of hours on atmos.

**Comment by naklikal** [comment]
I enjoyed playing the role of atmospheric technician. I have mastered all the available mechanics and follow the changes exclusively in this department with interest.
And I have always used an atmos fire suit. Reduces movement speed less and is airtight.

How is 100 kPa of pressure corrected in this game after a "fire" (plasma only)? vacuum.
And the atmosphere fire suit has just become useless for atmosphere work.
Now, it's anti-laser armor. :(

**Pull request merged**
