### PR TITLE
Add *emotes to the chat sanitizer

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR

incredible technology type * before emote to act it out BRRRRRRRRRRRRRRRT  
probably improves user experience for people coming from ss13

since it *is* the chat sanitizer though, and not a dedicated emotes processor, there might be skill issues stemming from this like not having \*list/\*help but the LOOC sleuth network will eventually tell people about the full list anyway

**Media**

https://user-images.githubusercontent.com/21104932/235436748-7cd0d248-5249-487f-b9bd-ba526a220c41.mp4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: router
- add: Added emotes prefixed in \*, such as \*clap and \*tilt. No cartwheels.
- tweak: All emotes (if not, it's a bug) have proper grammar form by default now. Old emote strings should still work fine.

### CODE REVIEW

**Comment by PixelTheKermit** [comment]
This probably shouldn't be hardcoded

**Comment by mirrorcult** [comment]
this is a really terrible solution, just make both `@` and `*` work for toggling the emote chat

**Review by mirrorcult — CHANGES_REQUESTED** [review]
above

**Comment by BasedUser** [comment]
> this is a really terrible solution, just make both `@` and `*` work for toggling the emote chat

doesnt deal with hardcoded emotes that take longer to type at all
ps i'm pretty sure half of the chat sanitizer entries could be thrown out and unhardcoded, should probably attempt doing that first

**Comment by DawBla** [comment]
Take a look at my awful take #14928 maybe it will give you some ideas (or what to avoid)

**Comment by BasedUser** [comment]
> this is a really terrible solution, just make both `@` and `*` work for toggling the emote chat

this defeats the PR's purpose of adding preset emotes at all though, so i'm closing it until further notice

**Comment by BasedUser** [comment]
mergeable, however incompatible with #15965

**Comment by AJCM-git** [comment]
https://github.com/space-wizards/space-station-14/pull/15965 is preferred

**Pull request closed without merging**
