### PR TITLE
Add FTL destinations

### PR DESCRIPTION
**Pull request by metalgearsloth**
Also renaming hyperspace to FTL because it's cooler.

Gonna add centcomm (that gets unlocked on shuttle countdown) + nukies base for syndicate consoles because tstalker mapped it

:cl: metalgearsloth & tstalker
- add: FTL mechanics have been added allowing you to go (for now, limited) other destinations, ported from Vilous Station 14.
- add: Nukies now start on a nukie planet and have to FTL to the station. No more seeking out their shuttle at roundstart.
- add: Additional shuttles can now travel to Centcomm after the emergency shuttle departs (e.g. cargo)
- fix: Fix autodocking when only 1 port was blocked (woops).
- tweak: IFF labels now show much further away, at the edge of the radar (no more cargo shuttle getting lost).

### CODE REVIEW

**Review by moonheart08 — APPROVED** [review]
Isn't the nukeops base a bit small? How are they leaving it (I couldn't be assed to test ingame sue me)

**Comment by metalgearsloth** [comment]
> Isn't the nukeops base a bit small? How are they leaving it (I couldn't be assed to test ingame sue me)

I'll get a render.

I also realise that I should probably have nukies code grab the infiltrator prototype rather than having it hardcoded into the map so I'll do that.

**Comment by metalgearsloth** [comment]
image

Map renderer doesn't work sooo

**Comment by moonheart08** [comment]
That looks and feels hacky.

**Comment by metalgearsloth** [comment]
> That looks and feels hacky.

whats ur suggestion

**Comment by Emisse** [comment]
i approve of biodome snow sphere

**Pull request merged**
