### PR TITLE
Revert "Syndicate Encryption Key buff"

### PR DESCRIPTION
**Pull request by mirrorcult**
Reverts space-wizards/space-station-14#13849

this is really silly it just makes an entire game mechanic pointless for no reason

:cl:
- remove: The syndicate encryption key no longer allows you to access every radio channel.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
Relevant discussions: #13849 and https://discord.com/channels/310555209753690112/1085189163793535088

**Comment by GoodWheatley** [comment]
Also could you at least give it a chance to let in play out in game it’s been 24 hours

**Comment by mirrorcult** [comment]
no, come up with something better, this is just fundamentally bad design

**Review by metalgearsloth — APPROVED** [review]

**Comment by Emisse** [comment]
i thought i was going crazy arguing against it

**Comment by GoodWheatley** [comment]
I'm tired of constantly arguing about it, I'll stop now

**Pull request merged**
