### PR TITLE
Make audio sliders use gain not volume

### PR DESCRIPTION
**Pull request by metalgearsloth**
Fixes https://github.com/space-wizards/space-station-14/issues/21983
Requires https://github.com/space-wizards/RobustToolbox/pull/4639

:cl:
- fix: Fixed a bug where the audio slider can get saved at 50% audio with no sound. Unfortunately this means your audio sliders will reset.
- fix: Fix crash on options menu while game sim not running.

### CODE REVIEW

**Comment by nok-ko** [comment]
It’s strange that even with this change, setting all the audio sliders to 0% doesn’t actually mute the game.

**Comment by metalgearsloth** [comment]
> It’s strange that even with this change, setting all the audio sliders to 0% doesn’t actually mute the game.

What do you want it to do in OpenAL as this sets gain to 0 which makes it inaudible?

**Comment by nok-ko** [comment]
> What do you want it to do in OpenAL as this sets gain to 0 which makes it inaudible?

Sorry, I’m not sure why it’s happening and don’t know enough about audio code to suggest a fix. I just noticed that I could still hear game audio with the sliders set to 0%.

**Comment by metalgearsloth** [comment]
Is this with the engine PR or without it.

**Comment by nok-ko** [comment]
With it; it doesn’t build without it.

**Comment by metalgearsloth** [comment]
Gonna need more details on platform and what the gain is set to when you set it to 0.

**Comment by nok-ko** [comment]
I’m on macOS. How can I see the gain information?

**Comment by nok-ko** [comment]
I poked at values in the debugger and it looks like the gain _is_ zero, (and so is the mastervolume cvar) but audio still plays. Which is confusing.

image

**Comment by metalgearsloth** [comment]
Talk to me further on discord as sounds like another Mac issue.

**Pull request merged**
