### PR TITLE
Goon Mutator Pill (April Fools)

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Adds a goon human mutator pill to maint lockers, it mutates you into a goonstation human
the clothes dont fit that well but what can you do

## Why / Balance

would be quite funny to see a guy from a completely different codebase just walking around, would create a "kris where the fuck are we" type situation

## Media

https://github.com/space-wizards/space-station-14/assets/79580518/b36ae591-f708-44a6-8504-024fd4ea8e9d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Added the interdimensional pill. It can be found in maint lockers, and turns you into an interdimensional being.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
Welcome to the station, goon human!

**Comment by Hmeister-real** [comment]
does this turn any species into a goon human?

**Comment by potato1234x** [comment]
> does this turn any species into a goon human?

anything that doesnt have an animal stomach

**Comment by potato1234x** [comment]
uhhh test fails unrelated?

**Comment by Terraspark4941** [comment]
make them able to fart and this will be the best PR this fools

**Comment by potato1234x** [comment]
> make them able to fart and this will be the best PR this fools

https://github.com/space-wizards/space-station-14/assets/79580518/d274861b-d0ab-4b3b-9a38-a67fd4581f5c

**Comment by potato1234x** [comment]
shiiit i pred this to wrong branch

**Pull request closed without merging**
