### PR TITLE
Make PKA require wielding

### PR DESCRIPTION
**Pull request by metalgearsloth**
People are just dual-wielding it to get around the firerate.

:cl:
- tweak: PKA requires wielding now.

### CODE REVIEW

**Comment by deltanedas** [comment]
personally id like if the accuracy penalty thing existed so you *can* dual wield for dps, but no more sniping

**Comment by DawBla** [comment]
This nerfs the dual wield PKA scenario but also prevents you from shooting while holding a jetpack
Will just make it useless for actual salvage

**Comment by metalgearsloth** [comment]
> This nerfs the dual wield PKA scenario but also prevents you from shooting while holding a jetpack Will just make it useless for actual salvage

Jetpacks fit on backpack.

**Comment by DawBla** [comment]
> > This nerfs the dual wield PKA scenario but also prevents you from shooting while holding a jetpack Will just make it useless for actual salvage
> 
> Jetpacks fit on backpack.

But then you can't use a backpack which is pretty bad
It just feels like this change prevents PKAs intended use to nerf it's usage as on-station weapon

**Comment by deltanedas** [comment]
pka has gone full circle and is now exclusively for mining
one handed pickaxe combat???

**Comment by metalgearsloth** [comment]
> But if that's intended to force salvs into melee combat or not let them jetpack while shooting easily so ticks/carps/bears have a fighting chance then it's fine

How do you propose balancing it against crusher, pickaxe, and drill if you can jetpack and crusher (which has infinite ammo which no other gun in the game enjoys) easily.

**Comment by DawBla** [comment]
> How do you propose balancing it against crusher, pickaxe, and drill if you can jetpack and crusher (which has infinite ammo which no other gun in the game enjoys) easily.

I actually forgot you can put mini-jetpack in the exo slot. This means you can wear a backpack and a jetpack with both hands free if you use the small air tank in the pocket. This sounds really fun since you would have to manage oxygen and jetpack fuel instead of using the big versions which never run out and also means wielding PKA wouldn't change much.

As for balancing PKA, Crushers, Pickaxe and Drill I have honestly no idea
Maybe PKA shouldn't be able to mine and fit in the backpack? Then you have to pick between a ranged weapon + pickaxe (or drill as its upgrade) and melee crusher

**Comment by Emisse** [comment]
i have some mixed feelings on this, i feel like it should still be useable one handed but to more detriment than wielding. maybe this is a sign we should implement accuracy/?

**Comment by deltanedas** [comment]
yeah i dont see why pka shouldnt have a 15 or 30 ish arc then wield to remove it

**Comment by HerCoyote23** [comment]
Alternatively could decrease fire rate, but increase it when wielded. You'd still be able to use it while jetpacking, but would be better off wielding.

**Comment by metalgearsloth** [comment]
I'm just gonna nerf the shit out of accuracy unwielded, same with L6 in a diff pr, but I might bump the L6 firerate again.

**Comment by Emisse** [comment]
l6 firerate needs reverting it too slow rn

**Comment by metalgearsloth** [comment]
Doneso, L6 change in a diff PR.

**Pull request merged**
