### PR TITLE
Makes brown rocks have a planetmap suffix

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds a "planetmap" suffix to brown rock so that people don't use it on-station.

## Why / Balance
Brown rock just doesn't really fit in well on station maps, especially when visually compared with ironrock and asteroid rock.

This used to change procgen asteroids to use asteroid rock, but sloth is bulldozing those *very* soon.

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Eww, this ugly grey rock is worse. It has no depth and looks more like pavement than a wall of rock.

**Comment by IamVelcroboy** [comment]
Sorry, not to just drop a complaint w/out leaving useful criticism. But, these look too much like the planet grass tile but grey. It's way too flat. 

I'm not a proper spriter but maybe some shadowing or some variance of texture throughout the rock would sell it better. I think the rock type looks better because of that, because the different size ovals throughout give it some actual depth.

**Comment by Flareguy** [comment]
> Sorry, not to just drop a complaint w/out leaving useful criticism. But, these look too much like the planet grass tile but grey. It's way too flat.
> 
> I'm not a proper spriter but maybe some shadowing or some variance of texture throughout the rock would sell it better. I think the rock type looks better because of that, because the different size ovals throughout give it some actual depth.

They look nothing like that ingame, this is a super zoomed-out screenshot with the low-resolution viewport (as you can see by my ghost).

Here's an admittedly kind-of-bad-for-demonstrating-my-point-but-I-don't-care showcase of all of the rock types, taken by someone else in the discord a while back:

image

While they are pretty flat and arguably kind of weird, they look more then defined enough compared to the grass texture and are still more fitting then brown rocks for stations, IMO. They're just too lumpy and uneven looking to make sense there.

**Comment by IamVelcroboy** [comment]
Of the "flat" style rocks, I think the only one that works well is the sand. The snow is probably fine too but wouldn't hurt to have some waves, sort of like the purple(forget what they're called) ones but not as many. 

IMO, the silver one in bottom middle is probably the best of them all. I just really haven't liked the grey ones much since they were implemented. But...🤷‍♂️maybe someday, someone will touch them up a little bit.

**Pull request merged**
