### PR TITLE
Revert "make galoshes obtainable and slowing you"

### PR DESCRIPTION
**Pull request by deltanedas**
## about

reduce jani blood pressure

## why

hrp powergaming heads rushing it roundstart

## media

no

## Changelog

:cl:
- remove: No more raiding the jani vend for galoshes, which are back to normal speed.

### CODE REVIEW

**Comment by Hanzdegloker** [comment]
Blessed PR

**Comment by metalgearsloth** [comment]
Keep the slowdown, they're stronger than magboots which are even slower.

**Comment by VasilisThePikachu** [comment]
Changelog is low effort imo. Conflicts with current pr changelog guidelines

**Comment by EmoGarbage404** [comment]
realistically, being completely unable to promote people into being effective janitors is way more of an issue than Captain or HOP abusing access to steal equipment, which is already against the rules and is a very clear role ban.

**Comment by deltanedas** [comment]
most janitors usually carry mop buckets or carts (i dont but still) which stacks with the galoshes slowdown

**Comment by Hanzdegloker** [comment]
> most janitors usually carry mop buckets or carts (i dont but still) which stacks with the galoshes slowdown

I almost always run mop buckets and the slowdown is quite bad

**Comment by EmoGarbage404** [comment]
why not just reduce the slowdown on pulling mop buckets. they have wheels: they should have next to 0 slowdown.

**Comment by Emisse** [comment]
im not sure why this was merged in the first place, i see galoshes on at least 1 secoff every shift no matter what. this was clearly explained when i removed the extras in the first place. this is still an admin issue and i am reverting it

**Comment by deltanedas** [comment]
powergaming bros its joever...

**Comment by K-Dynamic** [comment]
No one saw this coming :trollface: 

Only scenario janitor needs galoshes is when they are cleaning space lube, in any case (including new hires) they should be getting magboots from sci - and said magboots should auto toggle on puddles or something idk

**Pull request merged**
