### PR TITLE
chemical elements metabolism updates

### PR DESCRIPTION
**Pull request by CrigCrag**
## About the PR

Probably the final PR in the chemical tweaks series... for now.
Makes some elements that should be toxic, toxic. The level of damage is low compared to manufactured poisons, just adds a bit of detail and makes impurities in medicine a bit more dangerous when they occur.

Copper now acts as a very weak, slow-acting poison, kinda like lead but a lot weaker. You'll need to metabolize a TON of it to go critical.
Lithium now metabolizes at 0.1u per second, and very minorly poisons you. While being metabolized, you have a chance to laugh or scream randomly. Someone commented they wanted it to cause brain damage so this is a start.
**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Many basic elements from the periodic table are now mildly toxic or caustic. Watch what you drink!
- tweak: Crewmembers who drink lithium have reported very minor cases of serious brain damage. Doctors should watch out for people who are laughing and screaming at nothing.

### CODE REVIEW

**Comment by CrigCrag** [comment]
i made liquid nitrogen deal a bit of cold, please ensure i did not accidentally make nitrogen gas kill you

**Comment by CrigCrag** [comment]
how do i make the checks not break

**Comment by mirrorcult** [comment]
build fail is not your fault, YAML linter fail is however

**Comment by CrigCrag** [comment]
ah, thank you. i found my mistake (i think) and it should be fixed

**Comment by CrigCrag** [comment]
this and the other two chemical PRs are now ready for review. if you can, please check that I handled the lithium emotes correctly.

**Pull request merged**
