### PR TITLE
GORILLA Gauntlets

### LINKED ISSUE #13560: Anomaly feature request issue
## Description

handheld APE that can be researched
- call it CHIMP or something funny like that
- make it lategame sci anomaly research

Way to move around anomalies
- small amount of movement in exchange for severity and stability
- GORILLA cannon
- mid-game anomaly stuff.

More anomalies
- like 6 good ones would be nice

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

From the [anomaly core proposal](https://docs.spacestation14.com/en/proposals/mirrorcult-anomaly-cores.html).

An advanced technology that manipulates anomalies. When powered, you can punch anything (including anomalies) to send them flying. If powered with an active anomaly core, it has infinite charges. If the core is inert, it's only 5 charges.

Closes #13560

## Why / Balance

Basically the last content addition to round out the arsenal of anomaly crap. Pretty cool that it's finally done.

## Technical details

AnomalyCore was moved to shared and added some generic logic for knockback weapons.

## Media

image
image
image
image

https://github.com/space-wizards/space-station-14/assets/98561806/90f4b752-73ce-469e-9ca5-adb7c65e785f

have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the GORILLA gauntlet. When powered with an anomaly core, a single blow from this is able to send anomalies flying through the air. Just try not to let it out on the clown.
- add: Added Anomaly Core Harnessing technology to the Experimental discipline, which contains the GORILLA gauntlet.

### CODE REVIEW

**Comment by Ilya246** [comment]
it should work if thrown

**Comment by Ilya246** [comment]
tested PR, issue: AI mobs currently in motion are unaffected by the glove knockback
tested: tried punching carp, dragon, spirate, space tick, cow, borg
result: none of the AI mobs got flung while moving due to AI; all of the mobs got flung while not moving or moving due to non-AI reasons

**Comment by Ilya246** [comment]
> tested PR, issue: AI mobs currently in motion are unaffected by the glove knockback

retested, seems like this is unrelated to AI and exclusive to space mobs: all space-moving mobs get pushed very little by it

**Comment by brainfood1183** [comment]
When you punch anomaly does it cause it to pulse?

**Comment by Kadeo64** [comment]
admeme idea using these: two competitors equipped with gorilla gauntlets on a large arena (cleared out centcomm?) chasms at both ends. Whoever punches the other competitor into the chasm first wins

**Comment by Emisse** [comment]
gorillers work fine for me minus the mob thing but lets see if anything else happens

**Pull request merged**
