### PR TITLE
Small Tourniquet Buff

### PR DESCRIPTION
**Pull request by PoorMansDreams**
## About the PR

Tourniquets now heals 1 brute, deals less asphx, also comes in stacks of 5, ~~and now available in the NanoMed vend too.~~
## Why / Balance

With only 5 Tourniquets in the Secvend, and each being single use, they were just a worse emergency medipen. A single use niche item that is overshadowed by touching lightbulbs and carrying welder torches. Hopefully, tourniquets will make sec think twice about snagging weld torches and touching lightbulbs.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Tourniquets now heal a tiny bit, and come in stacks.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
Should be gauze in the medical vending machine instead, Tourniquet is a combat item and I think heat cauterization should be nerfed instead of making other items stronger

**Comment by PoorMansDreams** [comment]
good idea, Ill make a diff PR to put guaze in the medvend, and maybe just tone down the tourni stuff

**Comment by Brandon-Huu** [comment]
> Should be gauze in the medical vending machine instead, Tourniquet is a combat item and I think heat cauterization should be nerfed instead of making other items stronger than already are

Why are Tourniquets a combat item?
Aren't they just used to stop bleeding when direct pressure doesn't work?

**Comment by beck-thompson** [comment]
Also I think the YML error is real!
image

**Comment by QuietlyWhisper** [comment]
> Why are Tourniquets a combat item? Aren't they just used to stop bleeding when direct pressure doesn't work?

They're designed to be the second fastest bleed stopper that isn't a medicine, which is why they were given to the sec vendors.
#23195

**Comment by thebadman4662** [comment]
> Should be gauze in the medical vending machine instead, Tourniquet is a combat item and I think heat cauterization should be nerfed instead of making other items stronger than already are

Frankly both are combat items, one is simply better than other most of the time. Feels weird to have to go to dorms and cut a bunch of clothes just so you do not die after a single magdump in the aftermath if you did not prepare gauze ahead of time. Med teams really dislike of even tradin cloth for gauze to spare secoffs few mins of crafting.

**Comment by QuietlyWhisper** [comment]
> Feels weird to have to go to dorms and cut a bunch of clothes just so you do not die after a single magdump in the aftermath if you did not prepare gauze ahead of time. Med teams really dislike of even tradin cloth for gauze to spare secoffs few mins of crafting.

Which is why I suggested adding gauze to medvend, and why tourniquets are in security vendors, there shouldn't be any reason a secoff would be crafting gauze... the gauze isn't there to be handed out to security, they have the superior tourniquets for that purpose! The gauze is a quickly produced item for medbay to use on many people!

**Comment by QuietlyWhisper** [comment]
On another note, maybe consider just adding a lot more tourniquets since there a lot of security slots, unless you really think they should be a stack item as well. It may still result in only 5 security members having access to tourniquets if you just leave it as a stack without increasing the actual secvend supply.

**Comment by PoorMansDreams** [comment]
> They are looking pretty nice now, yes... But I wonder, perhaps asphyxiation damage should be replaced with bloodloss? Idea is that you stop the supply of blood, yes? If so then bloodloss makes more sense to me than just deciding there is suddenly no oxygen/nitrogen in your blood for a bit.

since bloodloss/aphyx heals after a bit anyways, 2 asphyx and 2 bloodloss damage sound good?

**Comment by QuietlyWhisper** [comment]
Agree

**Comment by superjj18** [comment]
Can we perhaps add them to the standard first aide kit?  Tourniquet is not exactly what one would call “advanced technology”.  It’s just a strip of fabric with a plastic rod to tighten

**Comment by PoorMansDreams** [comment]
add them to too much stuff and gauze becomes brute pack 2

**Comment by superjj18** [comment]
> add tourni's to too much stuff and gauze becomes brute pack 2

Isn’t that exactly what gauze is only for slash/pierce?

**Comment by QuietlyWhisper** [comment]
> Isn’t that exactly what gauze is only for slash/pierce?

Gauze is extremely effective on those damage types but it's main purpose is that it entirely removes bloodloss and is very common item for medical to have and produce, on top of the bleed stopping medicine which is also available

Tourn is very fast bleed stopper for combat use, if they were as available as gauze, bleeding would be too weak again

**Comment by superjj18** [comment]
> > Isn’t that exactly what gauze is only for slash/pierce?
> 
> Gauze is extremely effective on those damage types yes, but it's main purpose is that it entirely removes bloodloss and it is a very common item for medical to have and produce, on top of the bleed stopping medicine which is also available
> 
> Tourn is very fast bleed stopper for combat use, if they were as available as gauze, bleeding would be too weak again

Bleeding is already weak, I’ve never used gauze to stop bleeding because I just use lightbulbs.  The only way tourniquets will ever be useful is if they are relatively common, at very least then they’d have the CHANCE at doing what they are intended for.  

Even after the changes to lightbulb searing, I don’t expect to ever need gauze or tourniquets, simply because lightbulbs are an abundant resource compared to the laughably rare tourniquet and the not-so-rare-but-still-less-convenient gauze.

idk why people are acting like the tourniquet is a “op item” when in reality it is a laughably irrelevant item that only truly saves the amount of time it take to take off one’s gloves and touch a light bulb, so it probably saves about 2.5 seconds and a few points of damage.  Utterly irrelevant and arguably not worth the inventory space

**Comment by thebadman4662** [comment]
Considering the wounds that usually cause bleeding are very much same as gauze its pretty convenient.

**Comment by QuietlyWhisper** [comment]
> Bleeding is already weak, I’ve never used gauze to stop bleeding because I just use lightbulbs. The only way tourniquets will ever be useful is if they are relatively common, at very least then they’d have the CHANCE at doing what they are intended for.

This PR is adding more of them if you didn't notice that already, 10 stacks of 5 per item

**Comment by QuietlyWhisper** [comment]
> Considering the wounds that usually cause bleeding are very much same as gauze its pretty convenient. Frankly even with toruni buffs I would rather have gauze stack as secoff, its that good.

I absolutely agree with this, gauze is a very good healing item for security. The difference is in the use time of the item, where one can be used to both heal damage and stop bleeding, and the other simply stops bleeding fast.

**Comment by superjj18** [comment]
> This PR is adding more of them if you didn't notice that already, 10 stacks of 5 per item

I didn’t notice that no, but at the same time that’s kinda dumb and not at all how tourniquets work.  IRL IFAKs usually only come with one or two.  At that point you should rename the item “pack of tourniquets”.  They are explicitly single use items(though they could potentially be reusable once taken off)

**Comment by QuietlyWhisper** [comment]
> that’s kinda dumb and not at all how tourniquets work. IRL IFAKs usually only come with one or two. At that point you should rename the item “pack of tourniquets”. They are explicitly single use items(though they could potentially be reusable once taken off)

I agree, that's why I mentioned they should just add more of the item in general into the vendor instead of making it a stack as well

It doesn't really look good as a stack, even if you rename it.

 I dunno how much space people typically use as sec, but I haven't had an issue storing extra items if we remove the stack part of this pr... but maybe that's because I also don't hoard healing items on me?

**Comment by PoorMansDreams** [comment]
I could reduce the stack to 2, which seems a lot more reasonable, since having it single use just makes it a 2nd emergency medipen

**Comment by superjj18** [comment]
> I could reduce the stack to 2, which seems a lot more reasonable, since having it single use just makes it a 2nd emergency medipen

A tourniquet is just a small fancy belt, you put it on, you take it off.   Having it stack is just kinda weird, also this is all likely to change with new med.  if you get your hand blown off a tourniquet should be your only option to stop the bleeding, not even gauze or minor cauterization should be able to stop that, but it would also slowly kill the limb over time via restricting the bloodflow.

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Pull request closed without merging**
