### PR TITLE
Pumpkins, jack o' lanterns and pumpkin hat resprite

### PR DESCRIPTION
**Pull request by Doru991**
## About the PR

To celebrate Halloween, this PR adds the following:
- Pumpkins that botanists can grow.
- Pumpkins can be carved and then have a light put inside them to make spooky jack o' lanterns.
- The pumpkin hat will ~~get a new, more fitting sprite, and will also~~ gain the option to have a ~~light~~ battery placed inside of it for a spooooky but not very effective light-providing helmet.
- Not very major but the pumpkin cake will be obtainable since, y'know, we have pumpkins now

*All credits for the carved pumpkin and jack o' lantern sprite edits go to @ps3moira

## Why / Balance

It's spooky time, and more plants for botanists to mess with never hurt.
## Media

pumpkins

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Doru991 & ps3moira
- add: Pumpkin seeds are now available at the MegaSeed servitor.
- add: Pumpkins can be carved up and turned into spooky decorations.
- add: The pumpkin helmet can provide light if you insert a battery.

### CODE REVIEW

**Comment by forgotmyotheraccount** [comment]
Ideally the light source would be candles, but the PR hasn't been merged yet 😭  #21087

**Comment by Doru991** [comment]
I know, I'm using torches as a placeholder, if candles get merged before this I'll change it

**Comment by Flareguy** [comment]
A few thoughts on the sprites:
- The pumpkin itself is too hueshifted, but is probably fine for now (you can leave it as-is and someone else can fix it later.)
- The worn and inhand sprites *must* be changed, the worn ones have big contrast issues that are likely due to the busy shading and detailing. The inhands are also identical for both left and right. If you're not confident in your abilities you can probably just use the pumpkin sprites seen in beestation or similar for now, and forfeit the inhands.

**Comment by Doru991** [comment]
As stated in the PR body the sprites weren't made by me, I discussed with the original author and we decided to add the pumpkin hat resprite along with the pumpkins I was already intending to add as a halloween "package". I believe the intention behind the left/right inhand sprites was for the pumpkin to appear to be held in both hands (I understand that might look wonky as it's not actually a two handed item). As for the color issues, I'm not really an expert on the matter but I'll pass the feedback on to the artist I worked with

**Pull request merged**
