### PR TITLE
nuke actions from map files

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
a lot of maps serialized some actions which is bad and making #27422 fail tests

### CODE REVIEW

**Comment by AJCM-git** [comment]
i mean do they still serialize to the map in the refactor?

**Comment by deltanedas** [comment]
i dont know what causes it but its easy to grep for Action

**Comment by metalgearsloth** [comment]
is there an attached issue for this.

**Comment by Emisse** [comment]
can you do this off master i just merged a bunch of old map updates

**Comment by deltanedas** [comment]
@Emisse still good on master

**Pull request merged**
