### PR TITLE
Adds top surgery scar markings to the character creator

### PR DESCRIPTION
**Pull request by RiceMar1244**
## About the PR

This PR adds new chest markings to the character creator for post-chest-operation scars

## Why / Balance

Improved player expression and identity representation

## Media

short1
long1
short2
long2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: RiceMar
- add: Nanotrasen company healthcare insurance now covers gender-affirming chest surgery

### CODE REVIEW

**Comment by deathride58** [comment]
The kinda rep we needed but didnt even know we wanted

**Comment by mirrorcult** [comment]
based as fuck, they could be more visible or have variations tbh

**Comment by RiceMar1244** [comment]
Ill make a note of that and see what i can do if this isnt merged when I wake up in the morning

**Comment by KittenColony** [comment]
not gonna lie I was thinking about doing something like this myself, good fuckin' work mate 👏

**Pull request merged**
