### PR TITLE
adds Meat Tag to FoodMeatSnake

### PR DESCRIPTION
**Pull request by hyphenationc**
## About the PR

adds the Meat tag to snake meat, so now Lizards can eat raw snake meat. It deals 16 poison damage. Have fun.
## Why / Balance

...Lizards eat meat. Snake meat is still meat, right?
## Technical details

...
## Media

unnecessary
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Snake meat is now properly considered Meat, so Lizards can eat it.

### CODE REVIEW

**Review by slarticodefast — APPROVED** [review]
Thanks for the fix and your first contribution!

**Comment by hyphenationc** [comment]
i tried looking into the foodsequence stuff because admiral asked me to restore the kebab microwave recipes
but i could not for the life of me figure out where the hell the server was pulling "valid" prototypes from so i gave up on that... for now
i'd ask ed but i know they're kinda scarcely available for the future so...

**Comment by slarticodefast** [comment]
> i tried looking into the foodsequence stuff because admiral asked me to restore the kebab microwave recipes
but i could not for the life of me figure out where the hell the server was pulling "valid" prototypes from so i gave up on that... for now

This is off topic here, but instead of re-adding the microwave recipes you should turn them into food metamorphosis recipes:
see #31012

**Comment by chromiumboy** [comment]
Thank you for your first contribution!

**Pull request merged**
