### PR TITLE
Implanter Speed

### PR DESCRIPTION
**Pull request by liltenhead**
## About the PR

Players gib syndicates with implanters instead of removing them. I'd imagine the five minute use time being reduced to one should help this issue. One minute is also still too long for security to do random "implant checks".

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Implanter removal speed increased

### CODE REVIEW

**Comment by keronshb** [comment]
> ## About the PR
> 
> Players gib syndicates with implanters instead of removing them. I'd imagine the five minute use time being reduced to one should help this issue. One minute is also still too long for security to do random "implant checks".
> 
> **Media**
> 
>     * [x]  I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> 
> **Changelog**
> 
> 🆑
> 
>     * tweak: Implanter usage speed increased

Generally players will opt for the easier way. Shouldn't there be a rule about going to an extreme like gibbing vs removal? One minute isn't long enough sadly as if sec wants they can just arrest you then implant check if it's too low. It's only at 5 minutes for the time being until surgery is in, where that will be the preferred way of removing them.

**Comment by liltenhead** [comment]
I mean this was added 6 months ago, and I have never seen it used once cause no one is gonna wait 5 minutes. Yes, there are rules in place for not going to far, but when you know someone has the nuke disk in a storage container. You're asking people to wait 5 minutes or gib them. So by making it 1, people might actually take that as the "easier" route which is significantly better than gibbing.

**Comment by keronshb** [comment]
> I mean this was added 6 months ago, and I have never seen it used once cause no one is gonna wait 5 minutes. Yes, there are rules in place for not going to far, but when you know someone has the nuke disk in a storage container. You're asking people to wait 5 minutes or gib them. So by making it 1, people might actually take that as the "easier" route which is significantly better than gibbing.

Honestly wouldn't hurt to try it at least. If it gets bad it can get bumped up again.

**Comment by Myakot** [comment]
We usually use implanters on our servers if the target is known to have some implants. Precisely because gibbing just destroys the implant, and an implanter actually removes it to be injected in someone else.

**Comment by liltenhead** [comment]
changed cl

**Pull request merged**
