### PR TITLE
Kettle -> Gemini: RnD and Atmos revamp

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

- Gemini's atmos was moved to be next to engineering, giving it a TEG as an additional power source.
- Gemini's science department was moved to where atmos used to be.
- Gemini's old science experienced a tragic plasmafire, it is now a derelict maints area.

Minor fixes:
- Cargo airlocks
- Lawyer can exit their room again
- Even less exterior airlock wire fuckery! (Missed one set of doors in my previous PR.)

This PR was the effort of multiple people (including @luckyshotpictures and @Gotimanga and myself ).

## Why / Balance

A TEG is necessary for the map to continue surviving into the future, however moving atmos out of the center and away from supply means the 'characteristic' of Kettle once having been a gas refinery that was taken into use by NT would be lost. Due to this, the original map maintainer requested the map be renamed if this change goes through.

Gemini was chosen to anchor this, as it is a believable canon that Kettle class stations were developed earlier, with Gemini being a later version of the station class that is a general-purpose station, not focused on gas refining.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

New atmos:
Screenshot from 2023-11-30 10-42-59
Screenshot from 2023-11-30 10-43-18

New sci:
Screenshot from 2023-11-30 10-40-22

Old (now ruined) sci:
Screenshot from 2023-11-30 10-42-40

**Changelog**

:cl: TsjipTsjip & Luckyshotpictures & Deeja
- tweak: (Map) Kettle was renamed to Gemini.
- tweak: Gemini station received a new atmos and RnD department.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
Test failure looks related..... Looking into it.

**Comment by TsjipTsjip** [comment]
Will get accurate pictures for the version currently up tomorrow. This Tsjip is sleepy.

**Comment by TsjipTsjip** [comment]
Test failure is once again related. Tomorrow.

**Comment by TsjipTsjip** [comment]
I'd love to oblige, thank you for notifying me of this. If they wish to speak to me directly, I am available on discord with the same name.

**Comment by TsjipTsjip** [comment]
Conflicting PR: #22009 , I'll mirror these changes in the map file when I get the chance to work on this.

**Comment by TsjipTsjip** [comment]
Map file updated and pictures updated to reflect recent changes. The map name issue has not been resolved thus far and needs additional discussion, keeping on draft.

**Comment by Emisse** [comment]
map name will need changing according to checkraze

**Comment by TsjipTsjip** [comment]
> map name will need changing according to checkraze

I'm aware, I need time to consider potential new names and potentially converse with checkraze to allow them to have a say as well if they want. This is in progress.

**Comment by TsjipTsjip** [comment]
Ready for review. Please please please check my changes thoroughly before merging. I had to edit a test for this and I'm not entirely familiar with how those work. I am not currently capable of running my dev server to check if the updated files actually work.

Some non-obvious changes that I did include:
- Updated BecomesStationComponent to have ID 'Gemini' in `gemini.yml` (map file)
- Copied `kettle.yml`'s proto and replaced references to Kettle by Gemini.
- Kept the original kettle files in, people can still run kettle if they want.

**Comment by lzk228** [comment]
Kettle my beloved... :sob:

**Pull request merged**
