### PR TITLE
lower max firestacks to 10, refactor flammable

### LINKED ISSUE #23963: Admin fire smite is now too deadly
## Description
Currently the admin fire smite is doing way more damage than it used to. Something changed and now the fire smite is a guaranteed kill button. It crits the player in about 5 seconds.

Prieviously the smite was able to be used as a way to In character non-lethaly smite a player. It is now very leathal and will quickly make the corpse unrevivable due to the absurd burn damage it can apply in a quick timeframe.

**Reproduction**
use the "make the burn" admin smite

**Additional context**

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

- might fix #23963
- Lowers max firestacks from 20 > 10
- Uncaps the damage limit of 5 fire stacks
- Lowers heat damage from fire stacks to be the same as before at most
    - Less fire stacks will do less damage however, as the fire stacks go down.

## Why / Balance

https://github.com/space-wizards/space-station-14/pull/27159#issuecomment-2067626476

**Changelog**

:cl: Whisper

- tweak: Fire stack limit reduced from 20 to 10. Fire transfers will be less effective, and fires will not last as long.

### CODE REVIEW

**Comment by deltanedas** [comment]
i think mass scaling is better to fix liltenhead ops

**Comment by deltanedas** [comment]
also damage was capped at 5 firestacks, any more than that just makes it last longer

**Comment by QuietlyWhisper** [comment]
> also damage was capped at 5 firestacks, any more than that just makes it last longer

I see that now, and that's a little weird

**Comment by deltanedas** [comment]
still dont think this is needed:
- if you are aware you are on fire you can stop drop and roll
- if you are dead someone can splash water on you
- if someone wants to burn you to a crisp a single 20 stack wont do it with most armour so theyll still have to go for seconds anyway

**Comment by QuietlyWhisper** [comment]
I'm going to uncap it since the cap is an arbitrary number and reduce fire damage

**Comment by QuietlyWhisper** [comment]
Ok so at the time of writing this comment, a max stack fire burns out at 1471 heat, which would mean armored people do not burn to ash but unarmored are nearly ashed.

Antagonists could ash people still by simply adding more fuel at least once

**Pull request merged**
