### PR TITLE
vault fridge for mapping

### PR DESCRIPTION
**Pull request by Emisse**
vault fridge to standardize vaults
has fun stuff in it for stealing and thieving, vault has never been a super attractive target in either games so i think this should make it at least more fun to rob or command to go to in an emergency

### CODE REVIEW

**Comment by UbaserB** [comment]
the loot is a lot more standard than i was expecting for some reason

**Comment by Emisse** [comment]
we can add more stuff in it later, i want to put a traitor item in it but need to get it in all maps first

**Comment by metalgearsloth** [comment]
Is StorageFill or ContainerFill the good one.

**Comment by Emisse** [comment]
storage i think because its what all the lockers use

**Comment by JoeHammad1844** [comment]
i wonder whos gonna grab the deckard roundstart first?

**Comment by Kadeo64** [comment]
joe it's always HOP

**Pull request merged**
