### PR TITLE
Hardsuit rebalance

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About the PR
A ton of hardsuits (clown, Engi) were pretty unbalanced for their value, so I changed some values. (the deathsquad changes are just so that it makes sense, cause that beefy of a suit should have at least a tiny speed nerf). And for softsuits i made the NRSA suit better speed wise than the paramed suit because it is rarer and the station starts with paramed suits. No helmet changes. Fixes some issues from #25754

## Why / Balance
Fix unbalances in speed compared to value, also change some values here and there. A lot of these changes are here for balance with how the game currently plays, because, for example, most engineers play with their hardsuits on almost all the time since their job calls for it, and they have an unneccesarily nerfed speed, making it feel sluggish to play, and imo Space Station shouldn't feel sluggish. Look for #25754 for more reasons why.

## Technical details
Just value changes

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Hmeister
- tweak: Certain hardsuits are now faster or slower and have stat changes, like the engineer hardsuit. 
- tweak: Certain softsuits are now slightly nerfed to be slower, namely the Clown hardsuit and Paramed hardsuit

### CODE REVIEW

**Comment by HoidC** [comment]
deathsquad suit is designed to be OP

**Comment by Ilya246** [comment]
a fair amount of those don't make sense or seem bad, for example the elite hardsuit one

**Comment by asperger-sind** [comment]
The PR could use justification for these changes and could use a comprehensive table of changed values, and overall values of the changed suits.

**Comment by Hmeister-real** [comment]
> Oh boy let's see what this guy considers "balanced" Here's all stat changes so you don't have to sift through the files yourself
> 
> Engineering Hardsuit
> Spationaut Hardsuit
> Mining Hardsuit
> Brigmedic Hardsuit (the role that was removed for being too strong or something)
> Captain's Armored Spacesuit (the emergencies only suit just so captain isn't left without EVA)
> Syndicate Elite Hardsuit (y'know, the mobility over protection suit with a specialization in heat/rad protection)
> 
> 1. blunt resist from 40% to 55%
> 2. slash resist from 40% to 55%
> 3. piercing resist from 40% to 55%
> 4. heat resist from 80% to 60%
> 
> Syndicate Commander Hardsuit
> Cybersun Juggernaut Suit
> Wizard Hardsuit
> Pirate Captain Hardsuit
> Deathsquad Hardsuit (the suit with a comment on it that literally says "best armor in the game")
> CBURN Exosuit
> Clown Hardsuit
> Prisonder Eva Suit
> NTSRA Voidsuit
> Paramedic Voidsuit

Il change some stats around then, thanks for making this

**Comment by keronshb** [comment]
> Hardsuits running out of power and requiring infrequent recharges could be one of those downsides.

I don't see how this could ever lead to emergent gameplay for hardsuits, especially for the likes of people like Nukies who nearly require them.

No one should be wearing space proofing the entire round (minus special cases, like nukies, ninja, etc), but I don't see them offering _that many benefits_ to warrant a power system.

**Comment by ElPidor** [comment]
> So for most things a huge buff? That's gonna be a nay from me.
> 
> Below is my POV on the topic:
> 
> Hardsuits are a specialized equipment. Use the right tool for the job.
> 
> You are _generally_ not supposed to wear it the whole round.
> 
> **If you are walking in a hardsuit the whole shift - the situation is either:** a) the specific situation that calls for it has been going on the whole shift (i.e. armoring up against likely combat, or the station is full of holes), b) you are working in space the whole shift or part of your job is to anticipate and react to spacing, c) you are roleplaying a greedy/paranoid/doomsayer/etc. character d) purely powergaming reasons e) _this one intentionally left blank because I surely forgotten about that **one case**_
> 
> Point a) covers all antag suits, and the case of nukies declaring war. Point b) is the reason salvage, engineering and paramedics are given a lot of leeway when wearing hardsuits in a lot of situations that don't directly call for it. While c) and d) are self-explanatory.
> 
> On a final note I want to make it clear that I'm not against hardsuits being a way to make humans better humans™ (a.k.a. if you wear it you are straight-up better), but from gameplay POV this **needs** a downside. Hardsuits running out of power and requiring infrequent recharges could be one of those downsides. If that was ever implemented buffing hardsuit movespeed would totally have my approval. Until then - with **the only downside** being move speed penalty - the drawback should be considerable enough to offset the benefits.
> 
> tl;dr: IMO hardsuit balance should be such that people ought to not want to wear one unless the situation forces them to (think EVA - you'd only wear it when you have to).

Are you **dolboeb** my friend? 
Do you consider playing this shit real? At least try **playing** for real as nukies playing with such stats, Your skill issue is so high so you consider Power gaming as a real reason to change suits. Why you didnt think about giving a regular syndicate EVA suit(not nukies) a bullet protection?

**Comment by asperger-sind** [comment]
> No one should be wearing space proofing the entire round (minus special cases, like nukies, ninja, etc), but I don't see them offering _that many benefits_ to warrant a power system.

After spacepen removal they're basically a necessity if you want to combat anyone properly (and competently) utilizing space (ninja, nukies, bloodred tot, space dragon, etc. funnily enough this is the majority of the antags we have)

Imo it would be a 10x better solution to make them utilize an additional mechanic (charge in this example) rather than keep them balanced entirely around slowdowns and resistances, blood-red/ninja/etc. suits could probably just not have a charge mechanic.

**Comment by asperger-sind** [comment]
> the ninja suit is quite literally the only suit in the game with a charge mechanic at the moment.

Not the kind of charge I imply, the ninja suit uses charge for abilities rather than functionality.
By "charge" I mean the hardsuit has to be recharged to stay "functional", so lights, sight, oxygen, move speed, etc. are all affected by charge.

**Comment by keronshb** [comment]
> > the ninja suit is quite literally the only suit in the game with a charge mechanic at the moment.
> 
> Not the kind of charge I imply, the ninja suit uses charge for abilities rather than functionality. By "charge" I mean the hardsuit has to be recharged to stay "functional", so lights, sight, oxygen, move speed, etc. are all affected by charge.

The slowdown is not that bad in comparison to relying on charge.

You don't even need a hardsuit to give yourself oxygen.
Lights you can just use your PDA or some other flashlight

Hardsuits do not need to be that complex.

If anything they should have no slowdown in zero g, unless that already exists.

**Comment by K-Dynamic** [comment]
I would prefer my engi hardsuit (which should have engi abilities to begin with) being penalised for running out of charge as opposed to chronic 30% speed debuff

I *think* there was an issue opened up for hardsuits to have charges and abilities

PR should probably be split up as opposed to changing a whole bunch of suits as once

**Comment by asperger-sind** [comment]
> The slowdown is not that bad in comparison to relying on charge.

Yes, it absolutely is. Slowdowns are a permanent burden on you as soon as you get a hardsuit, especially now with the slowdown being applied on-carry as well as on-wear,
most crew hardsuits are a 30% or 40% move speed reduction which makes them completely useless in almost all combat scenarios to the degree where despite my earlier point
(hardsuits are required to combat a competent space-utilizing antag) you shouldn't use a hardsuit because it makes you almost, if not more, as vulnerable than being in space without a hardsuit unless you have an overwhelming advantage to couple with it.

Charge on the other hand, still achieves what slowdowns intend to do (prevent people from wearing hardsuits 24/7) while keeping them viable enough in combat to still be situational and good solution to the problem of space-utilizing opponents.
Combat viability may seem strange, the consensus on hardsuits is that they shouldn't be strong in combat unless it's a "combat" suit which are few and typically locked to antags (blood-red), but hardsuits really shouldn't be a weaker option than no armor at all, which it currently is because of the slowdowns, which as are as well-known, the most important variable in combat.

> You don't even need a hardsuit to give yourself oxygen. Lights you can just use your PDA or some other flashlight

Provided de-buffs from lack of charge were given as examples to get my point across, a hardsuit should lose its utilities and most of its functionality if it's not charged.

> If engineers need to repair a portion of the station for awhile, but have to stop because they _need_ to recharge their hardsuit, it becomes a chore. Dealing with the slowdown is a lot less worse.

Not really, even long and excessive repairs (syndicate bomb hole repair) do not take very long and are more bottlenecked by materials than anything else, one engineer with several stacks of steel sheets can fix the hole in a couple of minutes provided they're competent.

So why am I saying this? I raise you this: where do engineers get materials typically?
In engineering, from the material stockpile, or they march to cargo and ask for materials there, both departments would have suit chargers as both departments (engi-atmos, cargo-salvage) get hardsuits and interact with space, so when you need to restock you can also recharge, it's not a chore because it's done in couple with restocking.

> If anything they should have no slowdown in zero g, unless that already exists.

It would be appreciated, because right now (unless it got patched) a juggernaut suit in space without any damage is already moving so slowly that you mispredict and can't move at all.

Also, this discourages obnoxious space camping as K-Dynamic pointed out, which is a win in my book.

**Comment by deepdarkdepths** [comment]
Yeah a lot of these values are questionable at best, and no reasoning for them.
Deathsquad hardsuit you are never coming across or obtaining unless it's an admeme round. They are meant to be OP and impossible to kill.
Elite nukie hardsuit should not be touched. It's specialized for heat resistance while sacrificing blunt damage categories for a reason.
Why is the brigmedic, CBURN, wizard, and pirate hardsuit getting buffed when they basically have no place in the gameplay loop.
Clown hardsuit buff, why..? I believe people wanted it nerfed, actually. Could be wrong

Just doesnt make sense. You should've probably asked around if people felt like hardsuits needed adjusting first instead of adding your own arbitrary changes.

**Comment by K-Dynamic** [comment]
Does anyone else agree with the PR in principle but feel it's got too many changes?

I should clarify; engi hardsuit move penalty should be reduced from 30% since it currently hampers any space work (most other hardsuits are not as slow). This is separate to the charging idea, which would be a novel way of balancing it but out of scope.

> Also, this discourages obnoxious space camping as K-Dynamic pointed out, which is a win in my book.

The suit charging idea is just a way to balance hardsuits in general but not currently coded.

**Comment by keronshb** [comment]
What I'm getting from this is that on carry slowdowns should be removed and zero gravity slowdown shouldn't exist, with or without jetpack.

**Comment by keronshb** [comment]
It takes a hand slot. It really doesn't matter how long it takes to put on. You're still vulnerable to slipping or disarming, and still losing a hand slot.

You're not getting any hardsuit benefits unless you're wearing it so that logic doesn't make any sense.

**Comment by K-Dynamic** [comment]
> It takes a hand slot. It really doesn't matter how long it takes to put on. You're still vulnerable to slipping or disarming, and still losing a hand slot.

As someone who used to carry hardsuits in my hand all the time, risk of it being disarmed or slipping with it was low enough that I was comfortable with it

However, the reason I felt compelled to do it to begin with was because of the 30% penalty on engi suits, so it made responding to breaches across the station painfully slow - and I would've done the same across other roles

> You're not getting any hardsuit benefits unless you're wearing it so that logic doesn't make any sense.

I believe they're trying to point out you can equip and unequip hardsuits instantly for the situation and were able to run across the station with it in your hand, nullifying their move speed penalty

This wouldn't work in space but you could basically sprint whole hallways and immediately dress up at the airlock - apparently they didn't like this(?)

**Comment by HoidC** [comment]
> > You're still vulnerable to slipping or disarming
> 
> That's cheesed the same way due to no equip time - you are in full control of disabling that vulnerability on a whim in 0.033 seconds by simply wearing the hardsuit.
> 
> A cautious player will wear the hardsuit whenever there is another character in view, and take it off whenever nobody is around. Purposely and actively avoiding two game mechanics that are used for balancing.
> 
> Granted, there are going to be cases where this will actually have the desired effect (a person actually dropping the hardsuit as a result of them slipping while carrying it in hand) and it's a good thing since that's how it's intended to be, but it's way too easy to avoid it to consider it any significant balancing point.
> 
> Once again, to me, this is an argument to add equip times. Drop on slip is an intended game mechanic (players make a decision whether to carry something in hand and risk dropping it versus putting it somewhere else and deal with other disadvantages). Ability to mitigate that instantly at no cost is IMO cheesing your way around a game mechanic.
> 
> I mean, we're kinda getting offtopic here. But just consider why carry slowdown was added. It wasn't added without a reason. That reason still stands (nothing changed on this matter), so it's still reasonable to keep the carry slowdown a.k.a. it's unreasonable to remove it.

yeah, you could in theory use your reflexes to instantly put the item on when you realise you’re being disarmed but it really isn’t that simple 

This seems to me like a theoretical issue and not one that’s actually seen in practice - I’ve never felt the need to do this, nor have I seen anyone rapidly equip an item to avoid losing it when they’re slipped or disarmed. 

Carrying a hardsuit around all the time is impractical no matter how you spin it. It’s one disarm or slip away from being stolen and that’s always a threat.

**Comment by keronshb** [comment]
> That's cheesed the same way due to no equip time - you are in full control of disabling that vulnerability on a whim in 0.033 seconds by simply wearing the hardsuit.

You won't be able to predict this unless you become so paranoid that anyone approaching you is trying to steal from you.

**Comment by Hmeister-real** [comment]
I think the overall outcome of this discussion is that Hardsuits need an overall overhaul to how they work to be fun/fair to use, rather than simple stat changes. (i would try but im no coder). Im gonna keep this open for now for any further discussion if need be, but im closing this PR on Monday GMT (someone remind me if i don't).

**Comment by K-Dynamic** [comment]
> I think the overall outcome of this discussion is that Hardsuits need an overall overhaul to how they work to be fun/fair to use, rather than simple stat changes. (i would try but im no coder). Im gonna keep this open for now for any further discussion if need be, but im closing this PR on Monday GMT (someone remind me if i don't).

Maybe but a stat buff would be good for the short-term while waiting for any overhauls

I personally think you should split up the pr anyways since there's a lot of suits being touched

**Comment by Hmeister-real** [comment]
> Try closing it now and opening a discord thread, easier to discuss there.

Done https://discord.com/channels/310555209753690112/1216041779355193344

**Comment by Hmeister-real** [comment]
Im happy to re-open this incase people decide this buff can work for short-term

**Pull request closed without merging**
