### PR TITLE
Head coats in their lockers

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Makes it so head's winter coats spawn in their respective locker.
Might make maps like Saltern that have head's coats spawn on their tables a bit strange.

**Changelog**
:cl: Nairod
- add: Added head's winter coats to their lockers

### CODE REVIEW

**Comment by Scribbles0** [comment]
i just put coats in head lockers on cluster earlier :despair:

**Comment by Nairodian** [comment]
Well, the goal of this _was_ to make it so it wasn't on the mappers to do something like that.

**Comment by Scribbles0** [comment]
ik, just saying the timing is funny

**Comment by Peptide90** [comment]
Not sure I agree with this. It is head drip but it’s also locker bloat, especially where some heads already get cloaks or mantles. Probably better keeping them to mappers discretion - up to maintainers though.

**Comment by EmoGarbage404** [comment]
not really super thrilled about this. heads are more than capable of asking hop for the head drip or just wearing the department fit. Plus, do we really need more locker clothing bloat?

**Comment by Nairodian** [comment]
That's perfectly reasonable, I mostly PR'd this due to a few other people talking about how it would be a nice change, and I know I personally dislike having to bother the HoP every shift just because I want a coat, not to mention on MRP at the moment there isn't always a HoP or captain you can speak to. However, I can understand where you wouldn't want locker clutter.

**Comment by mirrorcult** [comment]
this is what the uniform printer is for

**Pull request closed without merging**
