### PR TITLE
Improve HandLabeler and AgentID UI

### PR DESCRIPTION
**Pull request by Vordenburg**
Previously, both UIs required you to hit enter in order for the event to trigger. Now, it sends the message when focus is lost, allowing for both items to update even if the player doesn't hit enter, which tends to be the more natural thing to do. It works even if you directly close the window, as the FocusExit event fires before that one.

The HandLabeler's ActivateInWorld handler was replaced with the more suitable ActivatableUI component used in many other devices.

[handlabeler_ui.webm](https://github.com/space-wizards/space-station-14/assets/114301317/f26a9b44-9fe0-4481-bee4-5eb938cd9f7c)

:cl:
- tweak: The hand labeler and Syndicate agent ID now set their labels without the player needing to hit enter on the input fields.

### CODE REVIEW

**Comment by deltanedas** [comment]
does this change disposal tagger too

**Comment by HerCoyote23** [comment]
If you're doing this, could you please do it for Northstar gloves as well? I adapted the agentID UI for them, so they've got the same issue with hitting enter.

If you don't feel like it that's fine too, I can do a PR for it when I get home.

**Comment by deltanedas** [comment]
also i think the tricks > rename thing has a base dialog all of these should use, move it out of admin dialog stuff

**Review by AJCM-git — CHANGES_REQUESTED** [review]
please add a short video showcasing the new behavior if you can

**Comment by Vordenburg** [comment]
A short video has been added to the original post.

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
