### PR TITLE
Add Command Glasses

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

Adds the Command Glasses, a pair of blue-tinted sun glasses that spawns in Captain's locker. They provide the ability to see job icons, but not criminal records status or mindshield status.

Adds the Command Hud, a blue-tinted HUD that spawns in HoP's locker. They are the same as Command Glasses without the flash protection.

## Why / Balance

Captain and HoP are allowed to get Sec glasses to perform their job duties better (e.g. confirming the job icon is correct on an ID), as stated in the rules and clarified by admins. However, to do so they must go to Security and raid one of the SecOff lockers. Additionally, Sec glasses provide Wanted and Mindshield info, information that is superfluous to Cap's/HoP's job duties and is really only utilized when doing Sec work validhunting. 

Having a pair of custom sun glasses accessible via their respective lockers solves both of these, indicating that they are primarily to be used for their job duties rather than Sec work. 

The glasses/HUD are limited to the lockers and not roundstart equipment to keep the number of them limited. 

_Edit: The initial version of this PR kept the Command Glasses the same as Security Glasses. This has been changed._

## Technical details

The Command Glasses utilize the same flash protection as Security glasses, though forgoes construction and wanted/mindshield icon components.

## Media

image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: SlamBamActionman, Graded
- add: Added administration glasses to Captain and HoP lockers!

### CODE REVIEW

**Comment by SlamBamActionman** [comment]
Test failure appears unrelated to PR.

**Comment by Thurtik** [comment]
This just encourages hops and captains to do security's work even more than before. Their job is managing the station's smooth operation and making important decisions, not monitoring people and enforcing those decisions onto them, and thus they don't need the utility of seeing people's job icons like security does

**Comment by Dutch-VanDerLinde** [comment]
was a pr that was closed before #27181

**Comment by Djungelskog2** [comment]
I think this has just become more of an issue of how lenient spacelaw is or the rules in general, especially silly when players are expected to somewhat improvise or bend it to their will when it's to their detriment. Such as players grabbing stuff like sec glasses seen here, galoshes, guns, weapons, wardens giving exclusively maximum sentences, ect 

Bring back the powergaming rules and possibly add something about uniform

**Comment by SlamBamActionman** [comment]
> This just encourages hops and captains to do security's work even more than before. Their job is managing the station's smooth operation and making important decisions, not monitoring people and enforcing those decisions onto them, and thus they don't need the utility of seeing people's job icons like security does

> i mean the fact of the matter is that the items are seen as powergaming because they are useful security equipment. just retexturing it and giving it to cap/hop doesn't change the fact that they are still just secglasses. The whole reason they aren't supposed to grab them is precisely because they are meant to be sec-only equipment. If we don't want them to be restricted to sec only, just give them the normal secglasses instead.
> 
> this is really more of a discussion about whether HOP and Cap should have access to the sechud at all.

That's just the thing: Admins have repeatedly stated that HoP and Cap have valid non-Security reasons to have job icon info. The issue arises when HoP/Cap uses them to do Security's job, but knowing about IDs is _not_ seen as a Security-only usecase. 

For HoP specifically it is meant to assist in providing IDs (and I've more than once encountered the issue where a HoP incorrectly switched the job icon, later resulting in Security arresting that person). 

https://discord.com/channels/310555209753690112/1125299494066597888/1253767900523790377
https://discord.com/channels/310555209753690112/1125299494066597888/1243288061979132015
https://discord.com/channels/310555209753690112/1125299494066597888/1248933661164965959

**Comment by EdenTheLiznerd** [comment]
Considering powergaming rules are now non-existent and this stops them from stealing securities gear... I genuinely cannot see an issue with it, the argument of "Captain and HoP shouldn't be doing securities job" stopped being an argument when captain's and HoP's were given the ability to take that equipment without consequence.

**Comment by EmoGarbage404** [comment]
i dont know what kind of crack you guys are smoking but powergaming is still very much prohibited as well as doing other people's jobs. in fact, rule 2.13 _SPECIFICALLY STATES_ not to do sec's job as non-sec.

**Comment by Djungelskog2** [comment]
> i dont know what kind of crack you guys are smoking but powergaming is still very much prohibited as well as doing other people's jobs. in fact, rule 2.13 _SPECIFICALLY STATES_ not to do sec's job as non-sec.

You can grab sec glasses, a baton and a gun as hop as long as you stay in your lane and keep doing paperwork and stay in your office as hop

**Comment by Brandon-Huu** [comment]
> It's also not your fault if a wanted criminal happens to run by and you are able to arrest them easily

It is your fault. Don't do that.

**Comment by SlamBamActionman** [comment]
> i dont know what kind of crack you guys are smoking but powergaming is still very much prohibited as well as doing other people's jobs. in fact, rule 2.13 _SPECIFICALLY STATES_ not to do sec's job as non-sec.

Since there's some resistance to checking the links I provided, here are screenshots of the admin rulings regarding wearing sec-glasses as non-sec.

Regarding rules _allowing Command to wear Sec glasses_:
image
image

Regarding HoP taking Sec glasses:
image

**Comment by Djungelskog2** [comment]
> > It's also not your fault if a wanted criminal happens to run by and you are able to arrest them easily
> 
> It is your fault. Don't do that.

Nothing and nobody is stopping you and no part of the rules saying "you probably shouldn't do X" has stopped anyone ever before, see wardens always giving max sentences and this new wave of free-game powergamers

**Comment by EmoGarbage404** [comment]
i think its a bit of wishful thinking to just hand command blatant security equipment (including access to wanted status) and then think that it won't just directly lead to command doing sec's job.

**Comment by Djungelskog2** [comment]
That is exactly what happened in the rules rewrite

This is why lrp can't have nice things

**Comment by Thurtik** [comment]
Im still against command having security huds (as imo you can just inspect people if you really need to know), but a good compromise might be the command glasses only showing job icons, and not wanted, suspicious, detained etc. icons. That way command wouldn't be encouraged to start taking justice into their own hands

**Comment by SlamBamActionman** [comment]
The concern seems to be that non-Sec will do Sec's job if they have Sec glasses. And I agree that non-Sec should not do Sec's job. 

It does however ignore that there are non-Sec usecases for Sec glasses, that those usecases do not constitute powergaming, and that ruleswise it has been made clear those usecases allow picking up Sec glasses. 

---

It's an issue if HoP starts validhunting with their disabler instead of for self-defense, but we still let them have one because the non-validhunting usecase is desirable. 

It's an issue if HoP starts validhunting with their job icon info instead of using it for their job, but we still let them have sec glasses because the non-validhunting usecase is desirable. 

This PR brings those two items in line.

---

> i think its a bit of wishful thinking to just hand command blatant security equipment (including access to wanted status) and then think that it won't just directly lead to command doing sec's job.

This has been in the game for about two months now. I can check with the admins if there has been a spike in validhunting Command because of it, but I have yet to see any such reports.

**Comment by SlamBamActionman** [comment]
> Im still against command having security huds (as imo you can just inspect people if you really need to know), but a good compromise might be the command glasses only showing job icons, and not wanted, suspicious, detained etc. icons. That way command wouldn't be encouraged to start taking justice into their own hands

I'm not opposed to this idea. 👍

**Comment by nikthechampiongr** [comment]
To clarify, players are still able to powergame under the current ruleset.

While powergaming is not directly a rule anymore, it is still enforced as part of other rules.

Specifically these 2:
[Do not abandon your role](https://wiki.spacestation14.com/wiki/Server_Rules#Do_not_abandon_your_role)
[Stick to your role](https://wiki.spacestation14.com/wiki/Server_Rules#Stick_to_your_role)

**Comment by SlamBamActionman** [comment]
> > This has been in the game for about two months now. I can check with the admins if there has been a spike in validhunting Command because of it, but I have yet to see any such reports.
> 
> I can't help but feel as if this is some kind of survivors bias, I imagine there's less reports because it's no longer against the rules or its leaning into grey areas

Validhunting and powergaming is still against the rules. Wearing sec glasses is not. Of course reports against sec glasses will go down if it's no longer against the rules, what I'm concerned about if validhunting reports have gone up.

**Comment by Djungelskog2** [comment]
> > > This has been in the game for about two months now. I can check with the admins if there has been a spike in validhunting Command because of it, but I have yet to see any such reports.
> > 
> > 
> > I can't help but feel as if this is some kind of survivors bias, I imagine there's less reports because it's no longer against the rules or its leaning into grey areas
> 
> Validhunting and powergaming is still against the rules. Wearing sec glasses is not. Of course reports against sec glasses will go down if it's no longer against the rules, what I'm concerned about if validhunting reports have gone up.

Powergaming isn't against the rules, that's the basis of the entire argument, I'm not arguing against your concerns of validhunting but I'm also arguing that validhunters aren't the only reason powergaming *should* be against the rules

**Comment by Killerqu00** [comment]
> To clarify, players are still able to commit violations by powergaming under the current ruleset.
> 
> While powergaming is not directly a rule anymore, it is still enforced as part of other rules.
> 
> Specifically these 2: [Do not abandon your role](https://wiki.spacestation14.com/wiki/Server_Rules#Do_not_abandon_your_role) [Stick to your role](https://wiki.spacestation14.com/wiki/Server_Rules#Stick_to_your_role)

While some of the behavior that is considered powergaming is now covered by other rules, some of the cases are definitely no longer clearly covered, such as this one.

Besides, I can say for a fact that command having secglasses became more frequent as of lately. It's definitely an issue that has to be solved via rules.

And yes, I don't think that simply giving command secglasses is the solution - in fact, it specifically caters to powergaming command members.

**Comment by retequizzle** [comment]
y'all are going to keep it up and i'm just going to remove the flash immunity from all sunglasses period

praise the s(t)un

**Comment by SlamBamActionman** [comment]
> EDIT: Shitposting aside, I will say that including the security HUD functionality is going to earn a hard no from me on this. It's condensing multiple options into one ease-of-use equipment item and we absolutely do not need more of that shit.

This is the same as Security Glasses, an ease-of-use equipment item that already exists.

> While some of the behavior that is considered powergaming is now covered by other rules, some of the cases are definitely no longer clearly covered, such as this one.

It is unambiguously OK with the current ruleset for Command to wear Sec glasses, as listed in the Restricted Items in Space Law.

> Besides, I can say for a fact that command having secglasses became more frequent as of lately. It's definitely an issue that has to be solved via rules.
> 
> And yes, I don't think that simply giving command secglasses is the solution - in fact, it specifically caters to powergaming command members.

It is only powergaming if the admins deem it so; HoP uses Sec glasses to more efficiently process IDs, and admins have stated this is OK and relevant to their main job, making it not powergaming.

**Comment by retequizzle** [comment]
> > EDIT: Shitposting aside, I will say that including the security HUD functionality is going to earn a hard no from me on this. It's condensing multiple options into one ease-of-use equipment item and we absolutely do not need more of that shit.
> 
> This is the same as Security Glasses, an ease-of-use equipment item that already exists.

This brings up a secondary question of why it was ever added to Security Glasses to begin with, because that in itself is also part of the "having too many functions condensed to one item" and should be reevaluated.

**Comment by SlamBamActionman** [comment]
> > This is the same as Security Glasses, an ease-of-use equipment item that already exists.
> 
> This brings up a secondary question of why it was ever added to Security Glasses to begin with, because that in itself is also part of the "having too many functions condensed to one item" and should be reevaluated.

#19904 is the PR that added them. I think the points listed there are still valid and it would be a degredation of the Security gameplay experience to go back.

**Comment by retequizzle** [comment]
> > > This is the same as Security Glasses, an ease-of-use equipment item that already exists.
> > 
> > 
> > This brings up a secondary question of why it was ever added to Security Glasses to begin with, because that in itself is also part of the "having too many functions condensed to one item" and should be reevaluated.
> 
> #19904 is the PR that added them. I think the points listed there are still valid and it would be a degredation of the Security gameplay experience to go back.

Finished reading through the PR, it addresses enough valid points with _security_ having access to them that I'll concede the point for Captain having a pair in his locker. I've partially realized my issue with the PR lies more in how balancing in general is implemented and less with this case in particular.

I still disagree with HoP having a pair though, primarily due to too many instances of having a Head of Personnel wearing a spare CE belt, spare carapace, spare galoshes, and strapped up with a blicky like he's expecting the apocalypse. They can go to security and ask for a pair of sec glasses like a normal department head.

**Comment by Simyon264** [comment]
> a spare CE belt, spare carapace, spare galoshes

Last I checked, there is not spare CE belt unless mappers mapped one extra CE locker. And the only source of galoshes are janitors that spawn in.

**Comment by SlamBamActionman** [comment]
To sum up my points:

- It is not against the rules for Captain/HoP to roundstart get Sec Glasses; in fact the rules explicitly allows it.
- The reason why is because the job hud can be used by those roles to do their role work more efficiently.
- Because of this explicit permission, grabbing the Sec glasses is not powergaming. This is in line with admin clarifications given on Discord.
- Cap/HoP should not use the job hud to perform work outside their role, i.e. Security work. This is against the rules. 
- Admins have shown, by virtue of explicitly permitting Sec glasses, that being able to use Sec glasses for Cap/HoP work is more important than the risk of those roles abusing them for doing Sec work.

You may disagree with these points, but they are what the admins have settled upon, and while there is a discussion to be had whether Cap/HoP should be allowed to pick Sec glasses up at all to do their job more efficiently, that's separate from what this PR is doing. This PR is, in effect, saving Captain and HoP from walking down to Sec to loot the Sec lockers for glasses and instead puts them in their lockers, *complying with current rules.*

The benefit of making them unique is distinguishing them from Security-labeled equipment and, as has been suggested, possibly not including the wanted status.

**Comment by SlamBamActionman** [comment]
The glasses have had the criminal records & mindshield info removed. As outlined in comments above, the primary usecase for Cap/HoP to wear Sec glasses when performing their role work is to see the job icon, not determine wanted status or mindshield affiliation.

**Comment by Golinth** [comment]
While I would personally prefer the mindshield stay (because mindshields are a form of ‘confirmed good’ to most players, and I think status icons look better with the mindshield outline) but I can 100% see how this is the best way to handle it. I can’t see a reason why this would be denied as of now, especially since command are explicitly allowed security huds now.

**Comment by Pumkin69** [comment]
this is a good pr although i also prefer mindshields stay because as for example captain having someone impersonate a head is fairly common and mindshields are a direct way of telling me that they are impersonating but maybe that's not something good.


> In my opinion they should be named "administration glasses" or something a bit more generic so they can be used for more than just command members

i agree

**Review by UbaserB — CHANGES_REQUESTED** [review]
The yellow highlight pixel on the worn sprite is a little bright but otherwise it lgtm.

**Comment by slarticodefast** [comment]
The command glasses will need to be adjusted to be contraband restricted to command. At the same time the security glasses should be changed to be security only instead of security+command.

**Comment by SlamBamActionman** [comment]
Visuals have been updated:
image

The PR now includes the contraband status - Command glasses are restricted to Command (though still only spawn in Captain/HoP lockers) and Security glasses are restricted to Security.

**Comment by SlamBamActionman** [comment]
It was pointed out in Discord discussion that HoP does not spawn with any kind of flash protection (similar to QM, CMO, RD and CE). I was working from sec glasses as a starting point so I had missed this. 

I've added the Command Hud, which spawns in the HoP's locker instead of the Command Glasses. 
image
image

**Comment by UbaserB** [comment]
I'm going to bite the bullet and merge it for now, it can always get reverted when the bugs with the ID console get merged or if this proves to be too powerful against antagonists.

**Review by UbaserB — APPROVED** [review]

**Comment by Cojoke-dot** [comment]
sad, I don't want my sneaky gloves to be seen...

**Pull request merged**
