### PR TITLE
New singulo appearance

### PR DESCRIPTION
**Pull request by qwerltaz**
Requires https://github.com/space-wizards/RobustToolbox/pull/5373
## About the PR

Make singulo look more like a real black hole. Simulate 'mirrored universe lensing', the event horizon, and the photon sphere.

Long ago, the singularity was implemented as a parody of the absurdly difficult idea of stripping a black hole of the "black hole" part and leaving a [naked singularity](https://en.wikipedia.org/wiki/Naked_singularity). The roleplay assumption was that the naked singularity would have some harvestable magic super powerful radiation. This change makes the singularity part of a black hole and shifts the assumption so that in our universe, we are able to generate a special super-decay black hole, or we cause [superradiance](https://en.wikipedia.org/wiki/Superradiance), or that Hawking radiation is much more rapid, and converted into energy by radiation collectors.

## Why / Balance

Real black holes are realistic *and* scary so why not approximate them given we have shaders in ss14? Before, it was a colorful sprite, left over from ss13, but not fitting with a shader.

## Technical details

Add brightness factor to shader, for a smooth event horizon edge. Brightness goes to 0 as deformation increases like in an OG black hole.

Add `hasEventHorizon` bool for when a distorting entity is powerful enough to cause one, otherwise no black region.

Tweak shader deformation for realistic lensing fitting with the dark region, or normal lensing for less gravitational objects.

Remove singulo sound and light casting.

This tinkers with the shader so slightly changes the distortion effect for: supermatter grenade, white hole grenade, gravity anomaly, singularity, singulo toy, and AdminInstantEffectGravityWell. For all of these, it's either fine or adjusted to be fine. See the media section for visuals.

Changed the singulo toy to the new look.

Made singulo not use a sprite. This is a *funny* parody of the undiscoverability of the singularity and also because the distortion would warp the sprite around itself weirdly. Thus, also increased max distortion sources in the shader from 5 to 32 because singulos without distortion are now invisible. The number is 32 because I saw a wizden round requiring around this number once. Seems to work fine 

## Media
Some pictures were taken before the last minor change which affects a small area near the event horizon, the general effect is almost identical.

real

eating the station

https://github.com/user-attachments/assets/c1109539-70c7-49fe-b741-d9115d1319ee

glimpsing infinity

https://github.com/user-attachments/assets/9632b519-530f-4f63-bbfd-8efe96261156

overlay is cursor-friendly

https://github.com/user-attachments/assets/28e1b7f4-5a01-44ca-ac22-2e8ff1a1d36b

other distortion sources

https://github.com/user-attachments/assets/c215fcef-bdd2-4bd7-bce4-5aa5d2c986a5

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Made singularities look a lot more like real black holes.

### CODE REVIEW

**Comment by kel593** [comment]
epic

**Comment by NakataRin** [comment]
Can't say much about the code, but I absolutely love the look

**Comment by Golinth** [comment]
This looks sick, you nailed it out of the park

**Comment by Everturning** [comment]
Honestly kinda lame, I like the colors of the singularity as it is now. I like when space game gets to be unrealistic. I also don't get the joke you're trying to make here. Is it that it's more realistic?

**Comment by Sarahon** [comment]
Pretty damn cool to be honest.

**Comment by qwerltaz** [comment]
> Honestly I think it's really cool, but the current singularity we have is just too iconic. Maybe if you did something like this but with the current singularity sprite?

I tried but it can't really have any sprite as the shader will warp it around a lot and it always looks weird, like the current distortion but worse.
The iconic singulo will certainly live on, for example in ss13. But we can try something new.


> Honestly kinda lame, I like the colors of the singularity as it is now. I like when space game gets to be unrealistic. I also don't get the joke you're trying to make here. Is it that it's more realistic?

No joke here. I just make it scarier and give a new RP explanation. The lack of sprite is because I tried and it's warped around weirdly all the time.

**Comment by Golinth** [comment]
To be completely honest, as iconic as the original sprite may be, this makes the singulo seem much more sinister and interesting. I don’t think preserving the original sprite is worth compromising how good this looks.

**Comment by EmoGarbage404** [comment]
Something not commented on is that this makes the Singularity level significantly harder to distinguish, which is practical and relevant information to observers. Size is still present, but being able to see the distinct colored swirls is an important factor for survivability.

**Comment by Krovotushka** [comment]
> Something not commented on is that this makes the Singularity level significantly harder to distinguish, which is practical and relevant information to observers. Size is still present, but being able to see the distinct colored swirls is an important factor for survivability.

Everything that is below 4th singulo level is easy to differentiate, also in most of the singulooses scenarios player wont get to see level of singulo, cuz every level above 3rd is so deadly and enormous that you just run away or die from it before you even see how the singulo looks

**Comment by qwerltaz** [comment]
About using a sprite, here are some images with sprites included. Now the fact we have to live with is that a real black hole gives us a distorted 360 image of the universe from its view. Unfortunately, we can't render the entire universe every frame so we need to wrap the screen to have enough pixels for the distortion. This is why you can see multiple copies of your screen in the distortion sometimes. It's normally not so bad, but with the sprite you just see copies of it which is weird. We can only distort the bounding box of the screen because it's the only part of the universe our game rendered and that's just the physical bound we can't go over. That's why the only sensible option I think is to not use a sprite. And I think it's a sensible option either way. 

And I think an actuall black hole with the also iconic pitch-black event horizon is so cool, would love to keep it as is. That, and also we use a shader for the distortion, and a shader works after a frame is rendered and works on its pixels so I think we can't add a sprite after it.


2024-08-22_284_Content Client
image

**Comment by slarticodefast** [comment]
Is there a reason the singulo sprite shows up in in the 4 cardinal directions like this in the last picture?
grafik

**Comment by qwerltaz** [comment]
> Is there a reason the singulo sprite shows up in in the 4 cardinal directions like this in the last picture?

Yes as I said the distortion in real life shows a distorted image of a 360-degree view of everything around the black hole. But games render only what is visible in the viewport (the screen). So if a pixel would end up outside the screen (and thus was not rendered by the game) we wrap using a copy of the screen again, which includes the singularity sprite, that's why we can see copies of it. I don't think there's a workaround besides rendering a huge viewport and using its pixels for the distortion but this would kill performance.

**Comment by Everturning** [comment]
well, it's official. A maintainer likes this pr and so it'll get merged no matter what points are brought up against it

**Comment by mirrorcult** [comment]
literally what are you even talking about, the only maintainer review on this PR is making a point against it

> Something not commented on is that this makes the Singularity level significantly harder to distinguish, which is practical and relevant information to observers. Size is still present, but being able to see the distinct colored swirls is an important factor for survivability.

**Comment by Hreno** [comment]
The original, not textured version is way better and more sinister.

As said, if new players cannot recognize a singuloose the first time it doesn't matter as they are probably screwed in any case. But how they wouldn't recognize and run away from it is beyond me, especially when everyone else is doing it.

**Comment by EthanQix** [comment]
The new singulo look makes it pretty hard to know which level it is at, which is not good for gameplay - especially for engineers. Not everything needs to be realistic.

**Comment by Hreno** [comment]
Perhaps the computer could tell the level.

**Comment by Krovotushka** [comment]
> The new singulo look makes it pretty hard to know which level it is at, which is not good for gameplay - especially for engineers. Not everything needs to be realistic.

1x1 tile size=1st level
3x3 tiles size=2nd level
5x5 tiles size=3rd level
7x7 tiles size=4th level 

It is literally that easy, could be added into singulo guidebook

**Comment by qwerltaz** [comment]
Gonna have to disagree on the singulo level and distinguishability. I did singulo a lot and here are situations where I ever needed to asses the singulo level and why the sprite was not helpful:
- Singulo is contained but unexpectedly large: You can probe this by noticing that the distortion stops moving because the singulo is almost as big as the containment field. I learned this quite fast. I don't look at the sprite because I only need to see the stationary distortion from a distance, and this happens from the PA or further, where I don't even see the sprite. I can then confirm whether the PA is below level 4.
- Singulo has breached containment: In this case You want to RUN as far as possible, completely regardless of the singulo's level. At higher levels, You can also see the distortion earlier than the sprite, so you are already running away before seeing the sprite.

I don't recall needing to asses the singulo level in any other case. And regardless, I find the levels easy to distinguish based only on the distortion size, and by the time you can memorize the looks of individual levels, you memorize the distortion sizes just as well.

You also don't needed to know the exact level to play engi effectively. You only need to know not to put PA above 3 and know how it looks when it's loose (pretty simple).

**Comment by UbaserB** [comment]
Thank you for your contribution, however after internal extensive discussion alongside a poll we have come to a consensus to close this PR. There were several issues that came up which neglected the identity of the singularity alongside gameplay problems.
- Being pure black is less identifiable and unique.
- It would be more interesting to make the sprite elements more obvious and impactful rather than removing them.
- The fact that the shader renders itself inside of it several times looks weird.
- The outline around the 'blackhole' in the middle is weirdly bright and feels heavily pixelated.
- It looks a lot better with actual sprites.
- it's difficult to tell which stage it is at.

If you're still interested in changing how the singularity looks, feel free to go ahead with the points above but I'll be closing it.

**Comment by Emisse** [comment]
i think i missed the pr discussion on this

**Comment by Golinth** [comment]
Maaan, I was really looking forward to this one. Super bummed that it’s been closed, it’s such a major improvement over what we have now

**Comment by qwerltaz** [comment]
> The fact that the shader renders itself inside of it several times looks weird.

I was playing with fixing this when making the shader but with no success. It should be fixable with some more work.

> The outline around the 'blackhole' in the middle is weirdly bright and feels heavily pixelated.

Fixing the point above might be enough to fix this. Otherwise I can fix it by extending the gradient between the event horizon and the outside.

The other points I disagree with.

**Pull request closed without merging**
