### PR TITLE
Dan's Soaked Smokes

### PR DESCRIPTION
**Pull request by Tollhouse**
## About the PR

This is an addition that came to me after I saw that you could inject smokes with chemicals. Most of what will be affected is medical. People over doing it on the smokes and coming in with issues. I kept the toxic or exotic chemicals at a low percentile/dosage but without large scale testing, I am not sure how impactful these will be.

Comes with new carton and pack.

Here is a list of all possible reagents that can show up in the cigarettes along with the volume/changes of them ending up in any given pack.

MuteToxin 
      prob: 0.1
      quantity: 2 

Tricordrazine
     prob: 0.1 
     quantity: 10

Iron 
     prob: 0.1 
     quantity: 10

Omnizine
     prob: 0.1 
     quantity: 10

Ipecac
     prob: 0.1 
     quantity: 10

Dylovene
      prob: 0.1
      quantity: 10

Arithrazine
      prob: 0.1
      quantity: 10

Bicaridine
      prob: 0.1
      quantity: 10

Dexalin
      prob: 0.1
      quantity: 10

SpaceDrugs
      prob: 0.5
      quantity: 10

Mold
      prob: 0.5
      quantity: 2

Licoxide
      prob: 0.5
      quantity: 5

WeldingFuel
      prob: 0.5
      quantity: 5

THC
      prob: 0.5
      quantity: 5

BbqSauce
      prob: 0.7
      quantity: 10

BlackPepper
      prob: 0.7
      quantity: 10

CapsaicinOil
      prob: 0.7
      quantity: 10

Nutrient (banana, bread, milk)
      prob: 0.7
      quantity: 10

**Media**

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
SS14propuffs

**Changelog**

:cl:
- add: Discount Dan has finalized a deal with NT chemistry and Shady Smokes to bring you a new smoking sensation.

### CODE REVIEW

**Comment by Emisse** [comment]
seems fun i like it

**Comment by potato1234x** [comment]
good idea not so good sprite

**Comment by deltanedas** [comment]
would be better without the name outing the chemical

**Comment by Tollhouse** [comment]
> good idea not so good sprite

Color or size. I just noticed how big the png is for my sprites not sure how to fix that I am not a pro spriteman. In regards to the color I wanted to have a loud color scheme to at least warn that these things are moderately dangerous.

**Comment by Tollhouse** [comment]
> would be better without the name outing the chemical

Just for being a scamp I agree. I like the name being present just for the fact that you get to pick and choose what you want. Big fan of the idea of maint cigarette doctors as well.

**Comment by potato1234x** [comment]
> > good idea not so good sprite
> 
> Color or size. I just noticed how big the png is for my sprites not sure how to fix that I am not a pro spriteman. In regards to the color I wanted to have a loud color scheme to at least warn that these things are moderately dangerous.

color is a bit in your face

**Comment by UbaserB** [comment]
Id prefer to it be secret, so you have no idea what the hell you’re smoking

**Comment by LankLTE** [comment]
If it’s not secret people will probably buy these and throw away all the non-medical ones

**Comment by Tollhouse** [comment]
I really like the gas station dick pill vibe. Especially since part of the fun is funny cigarette names. I'll take a look into renaming all these after I get the dang things past these checks.

**Comment by deltanedas** [comment]
this is 100% webedit ops real

**Comment by Emisse** [comment]
big fan of the new names

**Comment by mirrorcult** [comment]
extremely good names. it'd be best if the pills names were randomized out of a list so people cant powergame the contents from the names but i wont block it on that

**Comment by LankLTE** [comment]
I do agree it’d be best if it was random, but honestly cigs inject so little so slowly that I doubt it matters if people are “powergaming” it

**Pull request merged**
