### PR TITLE
Steal the McGuffin Thief Objective

### PR DESCRIPTION
**Pull request by Cojoke-dot**
## About the PR

New Thief objective to steal a McGuffin
## Why / Balance

YOU NEED THIS ITEM TO FINISH YOUR QUEST!!!
## Technical details

adds new thief objective
## Media

Screenshot 2024-06-30 043433
Screenshot 2024-06-30 044550

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: New Thief Objective: Steal the McGuffin

### CODE REVIEW

**Comment by Hrosts** [comment]
Won't this turn into "break into kitchen and cook" in like 90% of rounds?

**Comment by baddiePRO** [comment]
or simply ask the chef for it :godo:

**Comment by Cojoke-dot** [comment]
There is already the objective to “steal” a warden hat, which is the difficulty of walking up to a lathe and is less likely to get eaten. Either way, you could steal ingredients, maybe need to steal a pig for bacon or something.

**Comment by deltanedas** [comment]
its funny but it makes the problem of half of thief objectives not being theft bigger

**Comment by EmoGarbage404** [comment]
while the name is funny i agree that this isn't really something you can "steal." it adds onto the problem many thief objectives already have. As such, I'm closing this PR.

**Pull request closed without merging**
