### PR TITLE
add atmos stuff for mapping vox boxes

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- add atmos fix vox box marker for 101kpa nitrogen
- add `[Vox Atmosphere]` suffixed scrubber, vent, air alarm
- gas filters can save their filtered gas so you can have it filter nitrogen roundstart

## Why / Balance
for mapping and persistence

## Technical details
- added datafield to a lot of fields for persistence mapping and prototypes
- because air alarm shitcode has the filter list for each mode hardcoded, auto mode has to be disabled for vox air alarm. since it cant set wide filtering with the air alarms, vox scrubbers have widenet enabled by default

## Media
scrubber filters nitrogen out

air alarm vox thresholds are real

(now widenet and manual)

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by UbaserB** [comment]
you are my saviour

**Comment by Flareguy** [comment]
Minor nitpick, but the prototypes should just be named "Vox Atmosphere" or "N2 Atmosphere" or something. "Vox Box" is too specific and there are more use cases for N2 atmosphere then just that (IE. a vox-based space ruin, or the mining asteroid vox base)

**Comment by engineer-pearl** [comment]
I agree with the nitpick, but also think you deserve a changelog note. I think a lot of people will be made happy by this change.

**Comment by deltanedas** [comment]
theres no ingame change, you can't make these (you just use air alarm settings ingame)

**Comment by Partmedia** [comment]
Per the [pull request guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#content) things like the datafield persistence really need to be in a separate PR.

I'm okay with leaving them here if you clean up your commits and we do a merge (instead of squash commit) to get them into the tree as separate commits.

**Comment by deltanedas** [comment]
> things like the datafield persistence really need to be in a separate PR.

they are needed to be able to map enabled filters with a selected gas, put prototypes etc

also it already IS a separate commit, i have no idea why you think it is combined with the yml, or that it would even matter

**Comment by Partmedia** [comment]
> also it already IS a separate commit, i have no idea why you think it is combined with the yml, or that it would even matter

As you know better than most, the default action here is "squash and merge" which combines any commits you have into one big commit. The datafield changes are obvious "I would merge this now" if not for the fact that it's combined with feature changes that are subject to [maintainer policy](https://docs.spacestation14.com/en/staff/maintainer-policy.html).

The PR guidelines are designed to make it easy for obvious changes to quickly make it in. Of course, we can also wait for the requisite review period to get these changes in.

**Comment by deltanedas** [comment]
ok so review it instead of spouting bureaucracy you reserve exclusively for me

**Comment by IProduceWidgets** [comment]
Ahhh shit, was it not 101kpa? I thought I checked it first, Fuck.

**Comment by deltanedas** [comment]
n2/o2 markers are at miner pressure yes :trollface:

**Comment by deltanedas** [comment]
thanks for combining the marker and devices commits im sure that made something better

**Comment by Emisse** [comment]
> ok so review it instead of spouting bureaucracy you reserve exclusively for me

Cut out the snark Delta he is just following procedure.

**Comment by deltanedas** [comment]
procedure:
- only done for atmos related prs
- not seen on a prs i dont make

**Comment by EmoGarbage404** [comment]
do you have nothing better to do than be a bitch to a person who is literally reviewing, merging, and _working on_ your PR? like, he has done literally nothing but be polite yet you have no better response than being unbelievably hostile for no reason.

**Comment by deltanedas** [comment]
what was the point with the force pushing when it was just squashed in the end...

**Comment by Partmedia** [comment]
What do you mean?
image

**Comment by deltanedas** [comment]
ok my bad i cant read

**Pull request merged**
