### PR TITLE
Add replacement words to Russian accent

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
This adds a few replacement words to the Russian accent, in addition to the character replacements.
It also makes it replace A with Д, which it wasn't doing before.

## Why / Balance
It makes it more Russian

## Technical details
Technically this isn't how Russian works.

## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none

**Changelog**
nah

### CODE REVIEW

**Comment by lzk228** [comment]
yes, that's definitely better than #29620

**Comment by timurjavid** [comment]
I'm not sure if I like the replacement letters, it makes it a bit harder to read and it'll make it hard to ctrl-f search if you need to look at chat logs for some reason. Word replacements are good though

**Comment by Psychpsyo** [comment]
> I'm not sure if I like the replacement letters, it makes it a bit harder to read and it'll make it hard to ctrl-f search if you need to look at chat logs for some reason. Word replacements are good though

The replacement letters have been there for over 2 years and, in my opinion, make this the best accent in the game.

**Comment by metalgearsloth** [comment]
chat logs also has the original text so.

**Pull request merged**
