### PR TITLE
Wizard lightning spell

### PR DESCRIPTION
**Pull request by ActiveMammmoth**
## About the PR

Added Lightning Bolt spell for wizard.
## Why / Balance

More offensive spell options for wizard. Should be roughly equivalent in power to fireball. Numbers may need to be tweaked for proper balance but functionality is there.
## Technical details

Added LightningSpellEvent, listened to in Server MagicSystem cause ShootLightning and its random version are only available to the Server MagicSystem, had to change the Speak and PassesSpellPrerequisites in the Shared MagicSystem from private to protected to use in the Server's MagicSystem.
## Media

https://github.com/user-attachments/assets/f898a35c-f3ec-4d8f-8a10-f009d2e98a89
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

### CODE REVIEW

**Comment by Boaz1111** [comment]
This should not have a changelog. Wizards aren't in the game yet.

**Comment by G-370** [comment]
Holy moly, why tesloose when you can wizloose?

**Comment by ActiveMammmoth** [comment]
In case anyone worries about the PR freeze/restriction for magic/spells/spellbook/wizard, I worked on this with KeronSHB, they're in charge of the freeze.

This is my first PR so apologies for my mistakes. Should I get rid of the changelog..? Since Wizard is 'technically' in the game but just not playable (by default) yet.

**Comment by GoldenCan** [comment]
> This is my first PR so apologies for my mistakes. Should I get rid of the changelog..? Since Wizard is 'technically' in the game but just not playable (by default) yet.

Yes. The changelog is for players, and they won't see this ingame until wizard is fully implemented.

**Comment by Everturning** [comment]
Can you remove it exploding tech? Kinda goes out of scope for wiz

**Comment by ActiveMammmoth** [comment]
> Can you remove it exploding tech? Kinda goes out of scope for wiz

Not without significant rewriting. Random lightning looks for all entities within range that have the 'LightningTarget' component, which is basically anything but the floor. I'd have to either edit the random lightning function to be configurable to only target 'living' entities, hopefully using a pre-existing component on them, or I'd need to create a separate function solely for wizard, or some other third option I can't think of right now.

Also: I'm pretty sure fireball explodes tech. And everything else nearby it. Exploding stuff doesn't feel 'out of scope' to me for wizard.

**Comment by Everturning** [comment]
when i said out of scope i mainly was referring to exploding technology and power sources. you can probably do some kind of blacklist to APCs and consoles i think but im not a coder

**Comment by Boaz1111** [comment]
> when i said out of scope i mainly was referring to exploding technology and power sources. you can probably do some kind of blacklist to APCs and consoles i think but im not a coder

Not without a new tag

**Comment by ActiveMammmoth** [comment]
KeronSHB brought up a good point to me that fireball is dangerous to both caster and everyone else. Currently the lightning bolt won't arc back towards the caster due to the way the lightning is coded, which makes sense for lightning but means that this is safe to use while fireball isn't. So I'm thinking already I need to nerf or change this.

Currently the biggest amplifier of damage is the random bolt count. I'm gonna decrease it from 4 to 3. Then, I'm considering creating new lightning types specifically for the spell, which effectively mimic their counterparts but with decreased damage. This'll make sure it's balanced with fireball, since it's safer (for them) but deals significantly less damage.

The alternative of course is to reconfigure the random lightning for this spell to arc back to its origin point, which means you'll get hit by a bolt if you're too close, making it as dangerous as fireball for both yourself and your target(s). Not sure which way to go here...

**Comment by Everturning** [comment]
I agree with you making a new lighting so then you can add the functionality of not decimating bridge the second you cast it after teleporting there.

**Comment by ActiveMammmoth** [comment]
> I agree with you making a new lighting so then you can add the functionality of not decimating bridge the second you cast it after teleporting there.

https://github.com/user-attachments/assets/60dea537-e5f3-45c5-b318-33c3ffdd8357

**Comment by Aisu9** [comment]
isn't wizard supposed to be a force to be reckon with? also i'm pretty sure spells innately deals less damage to the caster to prevent instantly dying to the one assistant filled with stimulant rushing you.

**Comment by ActiveMammmoth** [comment]
I want to redo this PR.

**Pull request closed without merging**
