### PR TITLE
Chemistry Refactor Pt.1

### PR DESCRIPTION
**Pull request by Jezithyr**
## About the PR

Converts reagent and reaction prototypes into entities and adds the ability to define custom reagents during gameplay. This will allow for the possibility of procedural reagent/reaction generation.
Requires: #31249 

## Why / Balance

Reagents/Reactions being tied to prototypes limits their definition to YAML and doesn't allow for runtime modification or creation of reagent/reactions. To support runtime creation both prototypes are converted to entities/components which allows them to be created/modified/removed at any point.

## Technical details

TODO: outline specifics here

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

TODO: API changes
TODO: Steps for migrating

**Changelog**

### CODE REVIEW

**Comment by shampunj** [comment]
Just a week away

**Comment by whateverusername0** [comment]
Just a week away

**Comment by Agustron24** [comment]
How will this change the way you make chemicals?.

**Comment by Jezithyr** [comment]
> How will this change the way you make chemicals?.

This won't change anything playerfacing, this is purely a technical refactor that makes solutions/reagents much easier to deal with in code.

**Comment by Agustron24** [comment]
Okay thanks

**Comment by a-person5660** [comment]
just a week away....

**Comment by Jezithyr** [comment]
Due to various reasons I have decided to no longer directly be involved 
with the development of wizden, and as such I will be closing this PR. 

**Please do not reopen this PR as I will be continuing work on this PR elsewhere.** 
However I give permission for anyone to upstream these changes when they
are completed. I'd like be clear that this is just to avoid dealing with merge conflicts coming from 
two different versions being developed at the same time, and not a decision made of spite.

A more in depth explanation can be found here: https://discord.com/channels/310555209753690112/770682801607278632/1321967056446554174.

**Pull request closed without merging**
