### PR TITLE
Telecoms fixes

### PR DESCRIPTION
**Pull request by QuietlyWhisper**
## About the PR

Changed passenger key to common key in the name. Doesn't affect code.
Upgraded all headsets to 4 slots, as intended.
Fixed blood-red over-ear headset description to match actual stats. (5 slots)
Added periods to the ends of the descriptions of all machine boards. (Included telecoms, may as well fix them all.)
Adds missing period to telecoms server description.

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Whisper
- add: Upgraded all headsets to 4 slots. Head staff headsets will now have a free slot on their headset.
- fix: Fixed blood-red over-ear headset description to match it's actual stats; 5 key slots.

### CODE REVIEW

**Comment by QuietlyWhisper** [comment]
I'm not going to remove med-sci unless someone can confirm it won't cause mapping issues.

**Review by Emisse — APPROVED** [review]

**Comment by metalgearsloth** [comment]
Needs CI passing.

**Comment by QuietlyWhisper** [comment]
> Needs CI passing.

What does this mean ?

**Comment by QuietlyWhisper** [comment]
All good now?

**Pull request merged**
