### PR TITLE
give nukie reinforcements full operative gear

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
makes nukie reinforcements spawn with full nukie gear minus uplink, also gives them normal operative names

also gives them a free normal toy fish

(additionally removes random double space in uplink catalog)

## Why / Balance
i believe 35 TC is *way* too much for a reinforcement with no gear, the opportunity cost is extreme, so this partially balances it out

discord seemed to agree with me

35 TC reinfs have been in the game for some time now so i would suppose we can use the down/upvotes on this PR as a good metric of what people think about this

why toy fish? absolutely necessary

## Media
see media in https://github.com/Goob-Station/Goob-Station/pull/383

updated uplink preview: https://github.com/space-wizards/space-station-14/pull/30173#issuecomment-2239868364

compiled and tested this PR specifically too

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Nuclear operative reinforcements now come with full nuclear operative gear (and a toy carp) at no additional cost.
- tweak: Nuclear operative reinforcements now get nuclear operative names.

### CODE REVIEW

**Comment by Plykiya** [comment]
Going by the media, it gave them the name Agent Oscar

"Agent" is reserved for the medic
"Operative" is the generic unit

**Comment by Sinis-Boop** [comment]
Will make the 35 tc cost actually worth it

**Comment by Ilya246** [comment]
> Going by the media, it gave them the name Agent Oscar. That needs to be changed.
> 
> "Agent" is reserved for the medic "Operative" is the generic unit
> 
> Update the thumbnail icon that the reinforcement thing uses to better reflect they are fully equipped in a blood-red

loneops can have both agent and operative, i based it off that
thumbnail needs spritework but i guess i will

**Comment by Plykiya** [comment]
> > Going by the media, it gave them the name Agent Oscar. That needs to be changed.
> > "Agent" is reserved for the medic "Operative" is the generic unit
> > Update the thumbnail icon that the reinforcement thing uses to better reflect they are fully equipped in a blood-red
> 
> loneops can have both agent and operative, i based it off that thumbnail needs spritework but i guess i will

Good thing they're not a lone op anymore! Also I'm pretty sure that overriding gear like that doesn't work. I think it'll just cause the regular nukie ops/agents to drop their TC uplinks on spawn because their pocket2 slot is already occupied with a plushie. I ran into this same issue with duplicating backpack slots or starting with multiple pairs of glasses in hand.

**Comment by Ilya246** [comment]
> Good thing they're not a lone op anymore! Also I'm pretty sure that overriding gear like that doesn't work. I think it'll just cause the regular nukie ops/agents to drop their TC uplinks on spawn because their pocket2 slot is already occupied with a plushie. I ran into this same issue with duplicating backpack slots or starting with multiple pairs of glasses in hand.

i've tested it and it does work, though will re-test it later to be absolutely sure
and fine i'll rename them to `Operative`-only since names kinda matter in the actual nukie team

**Comment by Plykiya** [comment]
Thanks, I'll update https://github.com/space-wizards/space-station-14/issues/29899 to reflect it if there is apparently different behavior depending on what slot gets used

**Comment by Ilya246** [comment]
> Thanks, I'll update #29899 to reflect it if there's different behavior depending on what slot gets duplicated. Apparently the behavior is hard to duplicate locally according to Errant, so you may need to try a release build or something like that. Dunno, godspeed.

nothing gets dropped for either outfit

**Comment by Ilya246** [comment]
new preview sprite

old-radio-nukeop
image


meme version holding a fish, will use for real only with maintainer approval as this could be catastrophic for the economy (and potentially misleading about the operative's gear)

old-radio-nukeop-fish

**Comment by Plykiya** [comment]
Kindly looks goofy without the helmet on, it's a bit horrifying how bald they are

**Comment by Ilya246** [comment]
> Kindly looks goofy without the helmet on, it's a bit horrifying how bald they are

they're supposed to look scary in the advertisement*

*product may not look as advertised

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Can you provide a comparison of the price pre-nerf and kitting them up vs with this PR as I don't want to play balance yoyo over this.

**Comment by metalgearsloth** [comment]
Also obviously plykiya's PR is getting merged first.

**Comment by Ilya246** [comment]
> Can you provide a comparison of the price pre-nerf and kitting them up vs with this PR as I don't want to play balance yoyo over this.

gear comparision
image

non-purchasable gear gained:
- syndicate duffel bag
- syndicate PDA with syndie ID and a pen inside
- toy fish

price comparision:
- 8 TC without using nukie lockers
- 11 TC otherwise

> Also obviously plykiya's PR is getting merged first.

why, conflicts? i've looked over it and there should only be a few trivial ones

**Comment by Graded5** [comment]
Putting in my two cents pretty quickly.

The fact that reinforcements *dont* spawn with syndicate comms is crazy. To add insult to injury loneops just straight up cant buy their reinforcements blood-red encryption keys (last I checked at least). Also having them actually be able to access their ship would be a massive QOL, instead of basically forcing at least one member to buy a agent ID and hand-me-down their old ID.

If (for some reason) its decided to not let reinforcements get a free suit then please at least let them keep the other gear.

**Comment by Plykiya** [comment]
> Putting in my two cents pretty quickly.
> 
> The fact that reinforcements _dont_ spawn with syndicate comms is crazy. To add insult to injury loneops just straight up cant buy their reinforcements blood-red encryption keys (last I checked at least). Also having them actually be able to access their ship would be a massive QOL, instead of basically forcing at least one member to buy a agent ID and hand-me-down their old ID.
> 
> If (for some reason) its decided to not let reinforcements get a free suit then please at least let them keep the other gear.

There is a locker room filled with comms and visors for them on the nukie home planet

**Comment by Plykiya** [comment]
> Can you provide a comparison of the price pre-nerf and kitting them up vs with this PR as I don't want to play balance yoyo over this.

TC comparison if the nukies have to buy a bloodred for the reinforcement

- Original cost: 16 TC (reinf) + 8 TC (bloodred) = 24 TC 
- Nerf cost: 35 TC (reinf) + 8 TC (bloodred) = **43 TC**
- Buff cost: 35 TC (reinf) + 0 TC (free bloodred) = 35TC

Best case scenario if someone buys an elite suit and gives the reinforcement their old hardsuit is

- Original cost: 16 TC (reinf) = 16 TC
- Nerf cost: 35 TC (reinf) = 35 TC
- Buff cost: 35 TC (reinf) + 0 TC (free bloodred) = 35TC

The 8 TC saved is enough to buy an esword, which is what nukies will go for a majority of the time. So that's what this buff effectively is, just one more esword on the nukie side. Which I'd say is a pretty fair buff since their total bodycount is still cut in half from what it was originally.

I reviewed all the changes, I'm satisfied with it.

**Review by Plykiya — APPROVED** [review]
lgtm

**Pull request merged**
