### PR TITLE
bagel update

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-external airlocks now cycle
-jr pacmans have been placed around the map
-added unique ninja bombing targets around the map
-nav points added around
-AME engine only starts with 1 reactor crate so it cannot sustain the station
-not adding a training bomb to bagel for now
-skub

### CODE REVIEW

**Comment by deltanedas** [comment]
missed this airlock by the pod

**Comment by Emisse** [comment]
i missed the internal bagel space one too ill get to next time

**Comment by deltanedas** [comment]
also real you didnt set the beacon texts

**Comment by Emisse** [comment]
I set all of them

**Comment by Emisse** [comment]
This looks like a bug

**Comment by deltanedas** [comment]
it uses beacon text not warp point location, presumably to not spam the warp menu

**Comment by Emisse** [comment]
thats dumb

**Comment by Emisse** [comment]
make it use warp point ID not name so I dont have to fill out twice as many warp points

**Comment by Emisse** [comment]
it takes so insanely long to do this

**Comment by deltanedas** [comment]
imo maps shouldnt have 30+ warp points only important stuff

**Pull request merged**
