### PR TITLE
Chef rework

### PR DESCRIPTION
**Pull request by Duddino**
## About the PR 
This reworks chef. Chef is now an antagonist role and its objective is to produce as much food as possible. Everything is allowed (including murder), as long as it goes towards the chef's goal.
The microwave is now chef-only, and a lot of foods like donuts and vending machine foods have had their nutrition removed. Hunger damage has been readded and now is much more strong, so the station can't just arrest the chef.
**Screenshots**

image
image
image
Starvation damage ^

**Changelog**

:cl:
- tweak: Reworked chef. Chef is now an antagonist and their objective is producing as much food as possible. Anything is allowed including murder.
- tweak: The microwave can only be opened by the chef now.
- add: Readded starvation (and thirst) damage, and made it slightly stronger
- remove: Removed nutrition for most non-cookable foods (fruits, snacks, donuts, ...)

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
what the actual fuck

**Comment by moonheart08** [comment]
Are you trying to get repobanned.

**Comment by Duddino** [comment]
Well, time to fork I guess

**Comment by AtlasRules** [comment]
goofball PR

**Comment by Just-a-Unity-Dev** [comment]
willing to add this as 2g2c as a gimmick thing then revert it after a day

**Comment by Captain-Wet-Beard** [comment]
Make it an antagonist variant for traitor mode, with a randomized pool of specific food items to make like a clown burger for instance.

**Pull request closed without merging**
