### PR TITLE
Omega Minor Sec Update

### PR DESCRIPTION
**Pull request by spanky-spanky**
## About the PR
Slight expansion to Omega armory and changes to warden office, solves https://github.com/space-wizards/space-station-14/issues/32406
Also added atmos suit storage lockers (previously missing) and some firelocks in the TEG room.

## Why / Balance
Armory suit storage lockers were warden hardsuits by mistake, also adds an implanter crate by popular request.

## Media
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
No CL

### CODE REVIEW

**Comment by BodenPlfanze** [comment]
finally no more dragging the Crewmonitor from Evac to my Room! :D

**Comment by BramvanZijp** [comment]
Does this also fix the hos office left door access?

**Comment by spanky-spanky** [comment]
> Does this also fix the hos office left door access?

Yes, no longer a command door.

**Comment by BramvanZijp** [comment]
> > Does this also fix the hos office left door access?
> 
> Yes, no longer a command door.

Epic ty

**Comment by spanky-spanky** [comment]
> > > Does this also fix the hos office left door access?
> > 
> > 
> > Yes, no longer a command door.
> 
> Epic ty

image
image

**Pull request merged**
