### PR TITLE
Salvagers get extended capacity survival kits

### PR DESCRIPTION
**Pull request by dmnct**
## About the PR
QoL change for #18288
Since their job involves vac work away from the station, Salvagers will now spawn with the same survival boxes Engineers get, with the Extended Capacity Emergency tank. 

Changed the itemid to BoxSurvivalExtended

Or should I make this a separate prototype in case the two survival boxes might diverge in the future?

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: Nanotrasen has allocated funds from the Incident Compensation Budget to issue extended capacity survival kits to all Salvage Specialists.

### CODE REVIEW

**Comment by Vaaankas** [comment]
This will probably be turned down for the same reason extended tanks in salvage vendor did - its just powercreep and it negates the only real arachnids drawback.

**Comment by dmnct** [comment]
It was double tanks in the salvage vend. This is less of an improvement even if they ALL get one

**Comment by Vaaankas** [comment]
Its still powercreep i see no reason for

**Comment by dmnct** [comment]
Judge it in the context of the linked PR, which is the opposite of power creep

**Comment by dmnct** [comment]
Or to put this another way: if the people working out in space or on hostile planets, away from the station, do not "deserve" the extended capacity survival bottles. Then WHO does, and why do we even have that item? Should it be research only, and taken from Engineers too?

**Comment by moonheart08** [comment]
Salv works fine without this. They can use normal O2 tanks.

**Comment by deltanedas** [comment]
spoders cant use normal o2 tanks so blacklist them from salvage

**Comment by OctoRocket** [comment]
blacklist them from salvage??

**Pull request closed without merging**
