### PR TITLE
box update: vox box edition

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Adds a vox box to box in dorms. In lieu of air alarm prototypes, you'll need to manually set it up, but a paper has been provided to assist.
Also does a bunch of other misc stuff:
- Adds a vox sign for the vox box on box box
- The clothing room bathroom is now dirtier
- Slightly updates signage in cargo and sci (salv sign + server room sign.) A science-colored canister sign has also been added for this since there were 2 toxins signs basically right next to eachother.
- Power sign in engi smes room
- Replaces maint det coat with trenchcoat
- Vox box vox box box vox

## Why / Balance
We want to standardize vox boxes because they are fun and promote crew interaction + fix a design issue vox have. Also, gamer loot reduction

## Media
N/A

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
no cl no fun all vox

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i cannot find the vox box on box box on the box map

**Comment by lzk228** [comment]
this vox box is bruh

**Comment by JustCone14** [comment]
Why not just add a screenshot of the specific area?

**Comment by lzk228** [comment]
image

**Comment by deltanedas** [comment]
yeah its ass, especially if the windoors dont auto bolt. and if they do, theres no button to close the outer one so you can just get locked in

**Comment by Flareguy** [comment]
> yeah its ass, especially if the windoors dont auto bolt. and if they do, theres no button to close the outer one so you can just get locked in

They do in fact auto bolt. Vox also always have nitrogen tanks on them, so it's incredibly unlikely they'd ever get "softlocked" if someone somehow fucked up the cycling doors.

**Comment by deltanedas** [comment]
> if someone somehow fucked up the cycling doors.

windoors dont close automatically if you click to open them, this really needs a button

**Comment by Cojoke-dot** [comment]
Can the Vox box be in a more public place that people would go to? I think that weird little NT room could be replaced, iirc it's not lit at all and I've never seen it get used.

**Pull request merged**
