### PR TITLE
C4 1984

### PR DESCRIPTION
**Pull request by Emisse**
double the price of c4, raise the price of the bundle to 20
server is nigh unplayable due to people running around and speed bombing every substation on station

### CODE REVIEW

**Comment by GoodWheatley** [comment]
If substation bombing is the issue why not just raise the health of the substation

**Comment by deltanedas** [comment]
consider the following:
1. buy sus box
2. hack in and dismantle sub

**Comment by QuietlyWhisper** [comment]
I'd honestly rather them dismantle it than blow up the entire surrounding area as well, honestly

**Comment by deltanedas** [comment]
increasing sub health would help this, maybe to ~3x c4s damage to nerf c4ing subs into the ground but leave our favourite intellectual activity of med bombing alone

**Comment by asperger-sind** [comment]
Nerfing C4 because some dunce wants to bomb power every game without a reason to do so isn't going to fix the issue at large.
UristMcSubstationHater will find a new way to de-power med 30 seconds after they get traitor even if you flat out remove C4.

**Comment by deltanedas** [comment]
also honestly you should be bwoinking shitters that do that since its rarely objective related and just "i can sabotage whatever i want heheheha" or people being new i guess

**Comment by QuietlyWhisper** [comment]
We do but theres *usually* a valid reason

**Comment by Stealthbomber16** [comment]
> also honestly you should be bwoinking shitters that do that since its rarely objective related and just "i can sabotage whatever i want heheheha" or people being new i guess

relying on game administrators to be the antifun police instead of fixing the antifun mechanic is poor game design

**Comment by Flareguy** [comment]
Making the C4 bundle 20 TC is probably going to make it never used, and part of the entire reason C4 is worth a damn in the first place is because it's cheap.
Besides that, though, I would probably take a good look at the power distribution gameplay even if this is an attempt at a temporary stopgap, because it is very unlikely C4 is actually the issue and is moreso just the easiest way to reach the goal of destroying power. Like other have people mentioned, there are a fuckton of ways to eliminate power, such as tools or even just wirecutting.

**Comment by Naive817** [comment]
From who always buys C4 bundle and plant them at random places: C4 already have pitiful damage, they are super annoying when cloner or substations get bombed, but rarely kills people or even space rooms (have to plant it directly on reinforced wall to destroy it).  They are usually only useful as a distraction or forcing the shuttle being called early in the round.
But this also means C4 is just a shitter's weapon, making other players' time hellish while not being able to actually complete their traitor objectives.

**Pull request merged**
