### PR TITLE
Nerf Fire Helmets

### PR DESCRIPTION
**Pull request by Pangogie**
Remove the hardsuit helmet parent.
Fire helmets having hardsuit parent made them space viable with only the helmet.

:cl: Pancake
- fix: High-tech prototype fire helmets have been revoked.

### CODE REVIEW

**Comment by Pangogie** [comment]
I have no idea with the YML linter is failing. The light-on icon should still be in the RSI.

**Comment by ElectroJr** [comment]
I think its icon-flash vs light-icon, they use different states

**Comment by Pangogie** [comment]
Okey, it should be good to go now. Double check please. It's done in kinda a roundabout way, but it should work.

**Comment by Peptide90** [comment]
This is why I parented them to hardsuit helmets - they have pressure and temperature protection and a flashlight.

Whereas hard hats don't have the first two so you'd die to pressure in a fire. They're only viable as space helmets because our pressure protection system is binary instead of a scale.

**Comment by Pangogie** [comment]
Should be closed with #7225

**Pull request closed without merging**
