### PR TITLE
Resprite sec hud icons

### PR DESCRIPTION
**Pull request by lzk228**
## Why / Balance

bad to have letters in icons

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
is the "wanted" icon having an outline on top gonna look weird in game?

**Comment by skypatrol21** [comment]
The parol and discharge icons are extremely unintuitive, and new players will have a hard time understanding their meaning. If this change is to go through, the in-game guide needs to properly explain the Icons and their purpose. The new Parole and Discharge don't really provide any context on their meaning and just look like an hourglass and a checkmark.

**Comment by Brandon-Huu** [comment]
> The parol and discharge icons are extremely unintuitive, and new players will have a hard time understanding their meaning. If this change is to go through, the in-game guide needs to properly explain the Icons and their purpose. The new Parole and Discharge don't really provide any context on their meaning and just look like an hourglass and a checkmark.

New players can solve this by simply asking a senior officer what they mean.

**Comment by lzk228** [comment]
> is the "wanted" icon having an outline on top gonna look weird in game?

here how it looks
if you want i can make upper border straight, but rounded bottom looks cool
Screenshot_20240417_024400
Screenshot_20240417_024403

**Comment by Golinth** [comment]
Im not gonna lie, I think these are less intuitive and look worse than the originals. Especially for the discharge icon, the thin checkmark does not work very well IMO.

**Comment by baddiePRO** [comment]
when the wanted icon is sus

**Comment by lzk228** [comment]
if you dont like current pr icons, then propose new ideas

**Comment by Golinth** [comment]
> if you dont like current pr icons, then propose new ideas

Keep them as-is. If the concern about letters is for non-English repos it would be simple enough them to modify this in their own fork. I’m not sure there is anything that could make the icons clearer than they already are, without having in-game guides or an overhaul of how criminal icons are displayed.

**Comment by thebadman4662** [comment]
Discharged seems confusing to me, its supposed to be for criminal that served their sentence, right? Icon makes it look like "they are okay" guy instead.

**Comment by Hanzdegloker** [comment]
> Discharged seems confusing to me, its supposed to be for criminal that served their sentence, right? Icon makes it look like "they are okay" guy instead.

Truly the SS14 Sec believes all criminals are doomed to be repeat offenders and brand them so all Sec can keep an eye on them

In all seriousness I don't see much of a need for discharged since if you wanna keep an eye on someone parole them or keep them as a suspect.

**Comment by thebadman4662** [comment]
> > Discharged seems confusing to me, its supposed to be for criminal that served their sentence, right? Icon makes it look like "they are okay" guy instead.
> 
> Truly the SS14 Sec believes all criminals are doomed to be repeat offenders and brand them so all Sec can keep an eye on them
> 
> In all seriousness I don't see much of a need for discharged since if you wanna keep an eye on someone parole them or keep them as a suspect.

But if they are a suspect we should search them or ask to come to brig for questioning, it will only make things confusing. Wanted should be reserved for AOS because not every criminal should get flash and disabler in the face, especially if you do not know theya re one yet.

**Comment by Iamgoofball** [comment]
This is a direct reduction in quality over the existing icons. The existing icons are abbreviations of the status. These are just random icons with no connection to the relevant status. W stands for wanted. - communicates nothing.

**Comment by EmoGarbage404** [comment]
I don't really think these icons are great replacements for the existing ones. The symbols used--while i suppose more universal than just letters--aren't really appropriate for what the icons are describing. The variations in shape and line width in the other changed icons also looks strange.

I don't think there's much missing from our current icons visually. I'm not really of the opinion that these changes need to be made at this time.

**Pull request closed without merging**
