### PR TITLE
Paper cups as party hats

### PR DESCRIPTION
**Pull request by Krunklehorn**
## About the PR

Similar to the bucket hat, water cups can now be worn on the head like party hats. If the paper cup contains liquids, they will spill onto the floor.

The hat is also available as a standalone item. The shape is based on the existing party hat by netwy, but with colors from the [water cup](https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/drinks.dmi) instead.

## Why / Balance

Fun idea to get me started with YAML.

## Technical details

N/A

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

icon_water
vlc_xp0NzPFwqI
image

## Breaking changes

N/A

**Changelog**

:cl: Krunk
- add: Paper cups can now be worn as party hats!

### CODE REVIEW

**Comment by Nopey** [comment]
Does the drink interaction take precedence over the equip action when pressing Z with a papercup in hand?
With buckets, the equip action happens, leading to a lot of fledgling botanists dousing themselves in water or mutagen.

**Comment by Emisse** [comment]
yea quick equip should be removed for things like bucket or this

**Comment by Krunklehorn** [comment]
I can fix that first. It might also solve the issue where spam clicking soap into a bucket suddenly equips it.

**Comment by Krunklehorn** [comment]
I've taken a look at this problem twice now and it seems like action precedence isn't the issue.

The server tries to do: open -> drink -> equip, but the client only tries to do open -> equip. Drinking is server sided, but quick equipping is not. Is this correct?

If that's true, and I didn't want to just disable quick equip on buckets, would the alternative be to pull out TryDrink with all of it's events and dependencies into a new, SharedDrinkingComponent?

Also, I know this looks like a wasted effort for a stupid paper cup hat but I'm really just trying to learn.

**Review by metalgearsloth — DISMISSED** [review]
Doesn't need a hamster version.

**Pull request merged**
