### PR TITLE
nukie planet update

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR
the airlocks now use nukeops access
chem goggles in chemistry
two incendiary shotgun shells at the firing range
two teargas grenades where the EMP and flashbangs are
the drop pod now has is now made out of plastitanium and has LOS blocking doors
power monitoring console in gravgen
## Why / Balance

the two shells are good because it requires nukies to give up spacing to use them and incendiary ammo is otherwise unobtainable (perhaps a firestarter bundle with incendiary ammo could be added, but thats off topic)

the tear gas grenades are non lethal and easily counterable with internals
## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:JoeHammad
- tweak: The nukie planet has been slightly updated

### CODE REVIEW

**Comment by Emisse** [comment]
i dont really want this stuff mapped, firestarter bundle would be fine to add to uplink

**Comment by JoeHammad1844** [comment]
> i dont really want this stuff mapped, firestarter bundle would be fine to add to uplink

why not test it out like this first? if it turns out to be awful in practice it can be removed

also, should i add the RCD and water tank updates to the CL?

**Comment by Emisse** [comment]
joe we need to talk about your power creep

**Comment by JoeHammad1844** [comment]
> joe we need to talk about your power creep

image

**Comment by Emisse** [comment]
the solution isnt to elevate the other side, thats literally power creep

**Comment by JoeHammad1844** [comment]
well it doesn't look like the roundstart RCD for engis is going away, and it looks like its going to get better, too #15708

**Comment by Emisse** [comment]
yea thats gonna nerf them

**Comment by Emisse** [comment]
im putting the fireaxe on infiltrator anyway

**Comment by JoeHammad1844** [comment]
> im putting the fireaxe on infiltrator anyway

if thats a joke, based
if it isnt, based

**Comment by Emisse** [comment]
also im closing your infiltrator pr ill put a turret in through

**Comment by asperger-sind** [comment]
Imo kill the incendiary shells, they are stupidly overpowered, and then this'll be fine-ish, it's powercreep yet the items will probably be underused because its just neat gimmick stuff.

**Comment by JoeHammad1844** [comment]
over..

**Comment by JoeHammad1844** [comment]
> Imo kill the incendiary shells, they are stupidly overpowered, and then this'll be fine-ish, it's powercreep yet the items will probably be underused because its just neat gimmick stuff.

there are TWO total

**Comment by JoeHammad1844** [comment]
and nukies need to give up spacing to use them

**Comment by JoeHammad1844** [comment]
half this convo is just things i already explained in the pr :trollface:

**Comment by Emisse** [comment]
how do you think i feel mf

**Comment by JoeHammad1844** [comment]
by the way i'm going to go on a holiday tomorrow so i'm gonna give this PR 30 minutes and after that ill remove anything that'll prevent this from getting merged (and then go to sleep because it's 12:30 right now)

**Comment by asperger-sind** [comment]
> > Imo kill the incendiary shells...

> there are TWO total


One, two or a dozen, giving up spacing or not, incendiaries are stupidly overpowered and having them free like that is just giving nukies 2 shots that fuck any crew congregation (except atmos or some shit but thats edgecasing)

**Comment by Emisse** [comment]
tear gas is fine, chem goggles are fine, power monitor is fine, plastitanium drop pod is fine, incendiary stuff really needs to be in its own bundle

**Comment by JoeHammad1844** [comment]
> One, two or a dozen, giving up spacing or not, incendiaries are stupidly overpowered and having them free like that is just giving nukies 2 shots that fuck any crew congregation (except atmos or some shit but thats edgecasing)

the fire extinguisher in every hallway:

https://github.com/space-wizards/space-station-14/assets/130668733/0e3c3936-f197-4f50-9c0a-c49be91da1b4

what i mean by this is that fire can be completely countered by one singular unit of water splashed on you from a cup

**Comment by JoeHammad1844** [comment]
> tear gas is fine, chem goggles are fine, power monitor is fine, plastitanium drop pod is fine, incendiary stuff really needs to be in its own bundle

mentions drop pod that doesn't do anything but ignored the RCD :trollface:

**Comment by asperger-sind** [comment]
fire extinguishers exist in theoreticals and never exist practically unless its a fire anomaly scientist using one or some shit
people do not carry around water (or think about using it in active combat scenarios)
and neither can you stop drop and roll because you suddenly become a static target next to a man with a shotgun

either way if these are left in ill gladly abuse them so im arguing against myself here

**Comment by Emisse** [comment]
i dont want nukies having an rcd

**Comment by JoeHammad1844** [comment]
> fire extinguishers exist in theoreticals and never exist practically unless its a fire anomaly scientist using one or some shit people do not carry around water (or think about using it in active combat scenarios) and neither can you stop drop and roll because you suddenly become a static target next to a man with a shotgun
> 
> either way if these are left in ill gladly abuse them so im arguing against myself here

"NUKIES AAAHHH THEY HAVE A FLAMETHROWER AAAA"
*calmly grabs a glass of water*

any amount of informed preparation and the fire will only be dangerous when combined with bullets, which it should

**Comment by JoeHammad1844** [comment]
> i dont want nukies having an rcd

they will have ONE against however many engineers.

I guess you do have the fire axe which can space floors and break into windows about as fast but trades the construction feature for high damage

maybe we could have some kindof item that forces you to decide between the axe or the RCD for the team? but id rather not plan around hypotheticals like that

**Comment by metalgearsloth** [comment]
Joe you literally got banned for making powercreep prs despite over a dozen warnings and then you start going back to big powercreep prs, just make new content instead of making everything needlessly stronger.

**Comment by JoeHammad1844** [comment]
I dont think this is powercreep. the station gets more tools (notably the RCD) and this aims to bring nukies up the same amount. the important part of powercreep is things being left underpowered

remember what syndrome said? if everybody's special, nobody's special

**Comment by JoeHammad1844** [comment]
im not a game designer by the way

**Comment by metalgearsloth** [comment]
Game design is about choice, giving people literally every tool they might possibly need for any situation, also completely bypassing TC in the process, is not choice.

**Comment by JoeHammad1844** [comment]
fair point

**Comment by JoeHammad1844** [comment]
nukies get enough c4 already

**Comment by JoeHammad1844** [comment]
anyway, times up. final verdict, emisse, what do i need to remove?

**Comment by JoeHammad1844** [comment]
well i removed the RCD
thinking about it, having this EVERY NUKIE GAME would just be bad

**Comment by JoeHammad1844** [comment]
ive removed the backpack water tank fill but im keeping the two incendiary shells

**Comment by JoeHammad1844** [comment]
changes made

**Comment by JoeHammad1844** [comment]
i dont think sometimes :trollface:

**Comment by JoeHammad1844** [comment]
anyway i go to bed

**Comment by JoeHammad1844** [comment]
> by the way i'm going to go on a holiday tomorrow so i'm gonna give this PR 30 minutes and after that ill remove anything that'll prevent this from getting merged (and then go to sleep because it's 12:30 right now)

i still got some time actually

**Comment by Emisse** [comment]
remove incendiary stuff it should be its own uplink bundle

**Comment by JoeHammad1844** [comment]
i removed the stuff from the tank, are the two shells okay?

**Comment by Emisse** [comment]
no

**Comment by JoeHammad1844** [comment]
zamn

**Comment by JoeHammad1844** [comment]
removed

**Comment by JoeHammad1844** [comment]
alright goodbye for a week

**Pull request merged**
