### PR TITLE
Add effects to Impedrezene, Heartbreaker toxin and Mindbreaker toxin

### PR DESCRIPTION
**Pull request by noverd**
## About the PR 
I added hallucination effects to Impedrezene, Heartbreaker toxin and Mindbreaker toxin

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added effects to Impedrezene, Heartbreaker toxin and Mindbreaker toxin
- remove: None

### CODE REVIEW

**Comment by Cheackraze** [comment]
is this just giving the spacedrugs shader to these chems? because I don't think we need 3 more copies of space drugs. They should have their unique effects coded in instead, like impedrezone giving brain damage etc.

**Comment by Just-a-Unity-Dev** [comment]
> - remove: None

You can remove this line

**Comment by moonheart08** [comment]
Yea this is just turning them into identical copies of space drugs.

**Comment by noverd** [comment]
I can add blindness effect and alcohol effect

**Comment by noverd** [comment]
I add new effect to Impedrezene

**Comment by AJCM-git** [comment]
There is no interest in these if they use already existing effects.

**Comment by noverd** [comment]
okay

**Pull request closed without merging**
