### PR TITLE
objectives ecs rework

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- **objectives are entities now**
- split up condition logic to be more customizable both from other condition components and in yaml
- increased nuke disk difficulty so you dont get stretched out too thin with stealing disk+jordans and escaping on the shuttle which is basically a sosa exclusive to complete
- same for secret documents, hos has wt550 roundstart ce does not, and all cap objectives besides disk
- changed disk requirements to check if you are command, previously it allowed qm for some reason
  personally i think anyone that isnt captain should still be able to get it, but i just exclude qm too for consistency with the rest of the requirements
- renamed KillRandomObjective to KillRandomPersonObjective
- fixed order bug where if you first roll help traitor progress objective, you can then get kill objectives after that. but it didnt work the other way around. now you cant get social and kill objectives ever
- removed a condition data duplication check since it isnt (to my knowledge) possible to reimplement cleanly with components and if you get 2 kill objectives for the same guy hes very unlucky and you REALLY need that person dead

definitely didnt just do all this while doing terminator trust...

## Why / Balance
the gameplay changes have reasons next to them :trollface:

## Technical details
at its core ObjectiveComponent must be on an objective entity
after that add requirements a condition and other stuff then boom a task
the yaml uses ok prototype composition and should be fairly reusable

3 main events added:
- `ObjectiveGetInfoEvent` - gets an objectives progress among other things. condition components have to handle it and set progress or it wont be doable. they can also set title description and icon
- `ObjectiveAssignedEvent` - when an objective is assigned components can set state like randomly picking a kill target. the new version of IObjectiveCondition
- `RequirementCheckEvent` - raised before assigning an objective, makes sure theres no hard conflicts with other objectives or the player etc. the new version of IObjectiveRequirement

## Media
tasks exist

yep got them jordans

kill works too!!!

assassination too

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
- `Objective`, `ObjectivePrototype` and objective condition/requirement interfaces have been removed, objectives are now entities with components.
- multiple objective conditions were unused so they are no longer supported. just use multiple objectives
- `SharedMindSystem.TryAddObjective` now takes an entity prototype id instead of a now removed objective prototype.
- `ConditionInfo` is now `ObjectiveInfo`
- all objective prototypes have been turned into entities which use various parents in base_objectives.yml, use them for any new objectives

**Changelog**
:cl:
- tweak: Some Syndicate objectives have been tweaked to have higher difficulties, notably stealing the nuke disk.

### CODE REVIEW

**Comment by deltanedas** [comment]
new record :trollface:

**Comment by deltanedas** [comment]
@DrSmugleaf problem? :trollface:

**Comment by Partmedia** [comment]
Please reorganize your commits so that they're more reviewable. A bunch of trollface emojis is not descriptive. I'm concerned about the amount of breakage, as well as the unrelated "Some Syndicate objectives have been tweaked to have higher difficulties, notably stealing the nuke disk" content change in the middle of a large refactor.

**Comment by deltanedas** [comment]
trollface usually means i am spam committing a fix for the same thing

**Comment by Partmedia** [comment]
> trollface usually means i am spam committing a fix for the same thing

Then combine them in one commit and make the commit message descriptive.

**Comment by deltanedas** [comment]
afaik that would basically mean redoing the entire pr from scratch...

**Comment by Partmedia** [comment]
> afaik that would basically mean redoing the entire pr from scratch...

Do that, or use interactive rebasing to combine commits logically. I'm not going to review something that's exceptionally difficult to review.

**Pull request closed without merging**
