### PR TITLE
Toys price balanced

### PR DESCRIPTION
**Pull request by Jackrost**
Main problem is that cargo love to abuse Arcade machine from round start. They move it to cargo, hack it and spam toys every 4-5 seconds and get tons of money. This PR account this. Some cool toys have more price now, while others are more cheap.
We can cut prices more or just remove price for toys from Arcade machines. 
## About the PR 

**Screenshots**

**Changelog**

:cl:
- tweak: Now toys made of cotton and cheap plastic. Try to get rare toys!

### CODE REVIEW

**Comment by mirrorcult** [comment]
this doesnt fix the issue of cargo spamming toys if you just made some of them sell for 5-6x much as well. these just shouldnt have a price

**Comment by 0x6273** [comment]
Related: #11477

I think the real fix here is making arcade machines have a limited inventory so they can't spam items.

**Comment by Jackrost** [comment]
> Related: #11477
> 
> I think the real fix here is making arcade machines have a limited inventory so they can't spam items.

This not gonna work because you can just deconstruct it and construct again so vars will reset to default.

**Comment by metalgearsloth** [comment]
Construction should be making an empty prototype.

**Comment by Jackrost** [comment]
Maybe just make so arcade machine spawn price with 0 price?

**Comment by Jackrost** [comment]
> Construction should be making an empty prototype.

I'm a bit lost about what is a good way to do this. Do I need to make empty and filled prototype and let mappers to use filled prototype on maps?

**Comment by Jackrost** [comment]
Convert this to draft. Limiting arcade prizes makes more sense and also fix another problems. This PR stay to correct prices in future

**Pull request closed without merging**
