### PR TITLE
Update of Terminal

### PR DESCRIPTION
**Pull request by FillerVK**
## About the PR
Reworked the Terminal station. Added more activities.

**Media**
Some screenshots

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Departure Terminal update.

### CODE REVIEW

**Comment by UbaserB** [comment]
What are the "activities"?

**Comment by FillerVK** [comment]
> What are the "activities"?

Added a small bar and a small library. Also added more arcades

**Comment by VigersRay** [comment]
Everything is just as dull, I think it would be possible to make a much larger spaceport with a natural area in the center and a cafe and a bar on the sides at least, which is, well, cool, but still the terminal remains somehow "artificial", as if there is only something you would sit there and fly to the station.

**Comment by Emisse** [comment]
revert the seating areas to what they were before, add some plants on either ends of the arcades, remove the clothesmate, redo the decaling/floor in the library area, remove the books/games from the tables since they can be got from the bookshelves or the gamevend, wire the seating area better so those lights turn on

**Comment by FillerVK** [comment]
> revert the seating areas to what they were before, add some plants on either ends of the arcades, remove the clothesmate, redo the decaling/floor in the library area, remove the books/games from the tables since they can be got from the bookshelves or the gamevend, wire the seating area better so those lights turn on

done

image
image
image

**Pull request merged**
