### PR TITLE
Basic silicon lawsets

### PR DESCRIPTION
**Pull request by AsnDen**
## About the PR
Adds lawsets for honkbot (jonkbot), mimebot, supplybot and basic-silicon lawset.
Honk and mime laws are specified for them (honk obeys funny men, mime silent men).
Also gives laws for cleanbot and medibot (as they parent `MobSiliconBase` which has basic silicon laws).
Adds ability to get this laws via ion storm.

## Why / Balance
They are silicons like others, so I guess they can have their own lawsets.
As they are BASIC so they can't define the crew, so I've used "beings" in laws instead.

## Technical details
4 new lawsets for basic silicons.
Make honk, jonk, mime and supply bots affected by ion storm (clean and medi aren't affected because they are NPC).
Mimebot can't talk, so his buttons to say laws are useless.

## Media
(one of the lawsets for honk and jonk bots)
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

- add: added 4 new lawsets for basic silicons: honkbot, jonkbot, mimebot, supplybot, cleanbot, medibot.

### CODE REVIEW

**Comment by ArtisticRoomba** [comment]
Mimebot can still mime out their laws if someone mime-asks them to mime laws, which is hilarious and I can't wait to see this in-game.

**Comment by Everturning** [comment]
these don't need lawsets tbh

**Comment by AsnDen** [comment]
> these don't need lawsets tbh

I think they do that's why this PR exists

**Comment by ArtisticRoomba** [comment]
These laws aren't making these bots boring and mindless per se. They cater to their purpose and IMO it would lead to funnier interactions.

**Comment by Everturning** [comment]
I don't see a reason for them to exist. it just adds more laws and restricts what these basic silicons can do

**Comment by AsnDen** [comment]
> and restricts what these basic silicons can do

They actually can't do a lot. User who takes supplybot takes it to help station, not to entertain crew like honkbot. Mime, honk and jonk bots can still act like free agents (cause their laws don't mention "harm", so they can act like antago). Actually with laws it's harder to make im antago (because they must think that their actions entertain beings and person should be either funny or silent)

**Comment by retequizzle** [comment]
image

>you are a honkbot

>the air is a being

entertain it.

OR

>you are a mimebot

>the wall is a being. it is also silent.

>the walls tell you to kill. there is nothing to disprove this IC.

siding in "beings" in place of "crew" highlights a lot of issues with this.

also not everything needs laws.

**Comment by AsnDen** [comment]
> image

Honestly, I've used being cause drones use it. I thought it was used in "person" meaning (or smth like this)
image

If drone's "being" meant "everything", so I can change it to be "living creature" (or smth with same meaning)

**Comment by AsnDen** [comment]
> If you're not delivering stuff to the crew and instead just following around one person as a backpack it would be breaking your laws. 

Simply add condition if there are any goods to the law (no goods = no delivery)

> Also, Law-basic-silicon(just like law-drone) is a terrible time. Not being able to interact with people as in the funny cleanbot ghost role you took? bleh. In addition, the lawset prevents Medibots from healing people...

As far I know it is impossible to take either clean or medi bot (only via admin help), so no one will be able to see them "legally".
But you are right, maybe it will be better for clean and medi to be able to interract with other (we have game about interractions), so I will remove first law for now.

**Comment by Stealthbomber16** [comment]
I don't understand why these bots need laws. Borgs need laws because they're strong roles with high access, multiple tools, and no environmental hindrances. The laws exist to keep the borgs in check both as a gameplay balancing element and as a roleplay tool. Bots only have the 3rd quality, where they aren't hindered by the environment. Bots are already naturally kept in check by the fact that they can't do anything. Supplybots can't even load or unload cargo. 

This can't be merged as-is with the typo in the basic silicon laws and as its lacking medibot and cleanbot ghost roles (which can now be obtained without admin interference with the reintroduction of the random sentience event). But honestly I don't understand why we need it at all.

**Comment by AsnDen** [comment]
> This can't be merged as-is with the typo in the basic silicon laws and as its lacking medibot and cleanbot ghost role laws (which can now be obtained without admin interference with the reintroduction of the random sentience event). But honestly I don't understand why we need it at all.

Honestly, I don't see any typo in basic silicon laws
Clean and medi get basic silicon laws (it is parented from `MobSiliconBase`)

**Comment by Cojoke-dot** [comment]
> Simply add condition if there are any goods to the law (no goods = no delivery)

Again... it just feels like restricting a role that already can't do anything but walk.

> As far I know it is impossible to take either clean or medi bot (only via admin help), so no one will be able to see them "legally". But you are right, maybe it will be better for clean and medi to be able to interract with other (we have game about interractions), so I will remove first law for now.

There is an open pr for the Medibot at least, no clue about clean bot

**Comment by AsnDen** [comment]
> Again... it just feels like restricting a role that already can't do anything but walk. It just makes it feel like you have a pointless objective/rules you have to follow.

This bot was made to delivery things. Why do we need delivery bot, that may not delivery stuff and can do whatever it wants to? I guess only boredom motivates people to make the supplybot and don't expect him delivering goods.
 
> There is an open pr for the Medibot at least, no clue about clean bot
Yep, I've already changed laws to give clean and medi more freedom.

**Comment by Cojoke-dot** [comment]
> > There is an open pr for the Medibot at least, no clue about clean bot
> 
> Yep, I've already changed laws (removed one) to give clean and medi more freedom.

I guess they also need an emaged lawset so they can harm people. I belive the intent of the emagged janibot is to turn water and other liquids into lube and of course medibot already has stuff

**Comment by engineer-pearl** [comment]
I get that supply bots only walk and talk, but it feels so wrong to lack a prescribed purpose like a janiborg, the ability to be emagged, or a sense of chaos when the ion storm hits. 

While I understand the concern regarding restrictions on a restricted entity... Maybe bot can have a little law? As a treat?

**Comment by Cojoke-dot** [comment]
> I get that supply bots only walk and talk, but it feels so wrong to lack a prescribed purpose like a janiborg, the ability to be emagged, or a sense of chaos when the ion storm hits.

I mean... they aren't gaining anything new, just something that is written that, with the current rules of the game(as I understand them as a non-admin), means you have to do what they. You can't rp with someone and become a personal carrier or become just a robot puppy because your laws tell you that you have to move stuff. 

Ion storm would not affect anything due to bots just not being able to do anything with them. You just have a chance to be unable to talk to anyone and no way to fix it due to how bots work compared to borgs. 

image

Sure I can see funny situations, but people aren't going to take anything they say with weight. They can't talk on coms, they don't have meaningful access, people just ignore them most of the time anyway. Borgs getting emagged is funny because they are forced to beat the clown to death or make the captain complain all shift, bots just don't have the resources to have fun with it.

**Comment by superjj18** [comment]
Good pr, adds just a little more depth to otherwise aimless ghost roles.

**Comment by Everturning** [comment]
> Good pr, adds just a little more depth to otherwise aimless ghost roles.

the ghost roles aren't aimless, medibots heal people, janibots clean stuff, supply bots collect and move stuff, its all very basic and only restricts what you can do

**Comment by superjj18** [comment]
> > Good pr, adds just a little more depth to otherwise aimless ghost roles.
> 
> 
> 
> the ghost roles aren't aimless, medibots heal people, janibots clean stuff, supply bots collect and move stuff, its all very basic and only restricts what you can do

Basic tasks do not make them "not aimless".  That is essentially "what is my purpose? You pass butter. Oh my god", if anything these laws give more things for these roles to do, not less, more interactions, more things to think about, and the ion storm and possible ai interactions in the future only help even more

**Comment by SlamBamActionman** [comment]
I guess my question to this discussion is, have you ever met a bot that hasn't been doing its intended purpose?

I've never met a honkbot that hasn't been trying to slip people and work in cahoots with the clown. Taxi bots deliver people, or drive them around, or kidnap them beep beep. Your actions as a bot are so limited there is little to no room for sabotage to the station by not following your role, and if you've chosen to play a bot you likely wanna do their job anyways.

Add on the fact that making the bots require laws will increase admin burden as the only way to enforce law compliance is getting an ahelp and having an admin review it.

**Comment by mirrorcult** [comment]
these bots absolutely do not need laws, they are already inherently restricted mechanically, if this is supposed to be a 'heres what you should do' for new players then it shouldnt be tied to laws

**Comment by slarticodefast** [comment]
Hey, I brought this up for discussion with the admins and maintainers and the agreement was that bots don't need laws.
Most of the reasons have already been mentioned above: It will increase admin burden as not following them would mean a server rule violation, bots are very restricted in the ways they can interact unlike borgs, and these laws would unessecarily restrict the way players can play them. Thank you for your contribution.

Additionally we decided to add future silicon law changes to the list of PR restrictions, requiring a short design doc including an analysis on how they are to be interpreted to be made beforehand. See #8524 for more information.

**Pull request closed without merging**
