### PR TITLE
Nuke Detonation Sound Reduction

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Reduces the sound of a nuke going off

## Why / Balance
It's fucking LOUD

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Tynobeard** [comment]
The nuclear explosive device within 100 m of me is too woud ;-; (/j it is way too loud, but also a fucking nuke)

**Comment by Alekshhh** [comment]
it's meant to blow up the station not to blow out your eardrums

**Comment by liltenhead** [comment]
Can you make the nuke arming sound quieter too, cause that might be the loudest sound in the game

**Comment by Alekshhh** [comment]
different pr ye

**Comment by Alekshhh** [comment]
2000 spesos

**Comment by JustCone14** [comment]
I love you for this alekshhh, maybe our eardrums will be saved after all

**Review by Partmedia — CHANGES_REQUESTED** [review]
Thank you for your contribution. It seems like this change is very welcome.

I noticed that you're adjusting the volume by adjusting the level in the sound file. Since I anticipate that there will be future tweaks to the sound, I think it would be better for you to adjust the volume in code when this sound gets played. This way, the whole file doesn't need to be written (with an opaque diff) when volume gets tweaked again. And, the history of past volume tweaks and their volume settings can be recorded.

Could you please revert the audio file change an instead update the volume in `NukeSystem.cs` where this is played? If you are not familiar with C#, please let me know and I can make this change for you.

**Comment by ficcialfaint** [comment]
Also shouldn't the changelogs sound like "Changed nuke detonation sound **volume**"?

**Comment by Alekshhh** [comment]
yeah I don't know C# I'd rather you do it

**Comment by Partmedia** [comment]
@Alekshhh What gain factor did you use in the volume reduction?

**Comment by Alekshhh** [comment]
no clue what that means but I deamplified it by around 5 dB if that helps

**Comment by Partmedia** [comment]
> no clue what that means but I deamplified it by around 5 dB if that helps

Yes, that's what I was asking, thanks.

**Comment by Alekshhh** [comment]
since you're doing this can you also do lilten's request, that shit is loud as hell too

**Review by Partmedia — APPROVED** [review]

**Comment by Partmedia** [comment]
> since you're doing this can you also do lilten's request, that shit is loud as hell too

Could you put together a list of the sounds that need adjusting, along with the gain adjustment (in dB) that you suggest?

**Comment by JustCone14** [comment]
I'm sorry I don't know the specific file or adjustments to make but could the sound when the alert level is changed. Specifically Red, Delta and Gamma alerts.

**Comment by liltenhead** [comment]
> Could you put together a list of the sounds that need adjusting, along with the gain adjustment (in dB) that you suggest?

Walking on snow, FTL arriving and departing, FTL flight itself like being on the emergency shuttle going to Centcom. Those are all very loud and jarring basically every time I hear them.

**Comment by Alekshhh** [comment]
clown shoes

**Pull request merged**
