### PR TITLE
Add ghost role whitelist and enables drones for whitelisted players

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR 

Adds role whitelisting from [Nyanotrasen](https://github.com/Nyanotrasen/Nyanotrasen) and reenables drone roles, requiring their players to be whitelisted.

This involves a lot of cherry-picking commits from Nyanotrasen so there's a decent potential for issues. I'm planning on testing it with that in mind but any additional help is apreciated.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Drones are reenabled as ghost roles for players who are whitelisted.

### CODE REVIEW

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Being on MRP shouldn't explicitly give you every whitelisted role, also the code is gonna need cleaning up.

**Comment by Elijahrane** [comment]
As a disclaimer the one thing about Nyano WL that I'm not super happy with is that it's 1 whitelist for everything that requires whitelisting. I didn't want to touch DB stuff.

It works on Nyano because the way the server is administrated is designed with that restriction in mind. I'm not sure if it's a good general solution

**Comment by Elijahrane** [comment]
Also we just disabled drones again today on Nyano because it's clear they need reworks even with the WL restriction

**Comment by AJCM-git** [comment]
@Chief-Engineer you coming back to this?

**Pull request closed without merging**
