### PR TITLE
rotated lighthouse crematorium

### LINKED ISSUE #10160: Lighthouse crematorium is facing wall
## Description
Lighthouse crematorium is facing wall. You gotta remove the wall to use it.

**Reproduction**
- Load Lighthouse
- Check out chapel

**Screenshots**
lighthouse_crematorium

### PR DESCRIPTION
**Pull request by JustinTrotter**
## About the PR 
Fixes #10160
**Screenshots**

Screenshot_2022-07-31_16-25-22

**Changelog**

:cl:
- fix: lighthouse crematorium rotation

### CODE REVIEW

**Comment by JustinTrotter** [comment]
> What is causing "+145,749 −145,643", it is possible to edit map without text editor without causing that?

I don't know, Ive never done a map edit before. I tried to only change the affected entity following https://docs.spacestation14.io/en/content/mapping.

**Comment by Just-a-Unity-Dev** [comment]
I recommend just making an issue and leaving it to the maptainer (in this case @OldDanceJacket) to fix it

**Comment by JustinTrotter** [comment]
> I recommend just making an issue and leaving it to the maptainer (in this case @OldDanceJacket) to fix it

Okay, The issue #10160 already exists. I'll close this PR now.

**Comment by Peptide90** [comment]
For future reference, open the map in a text editor like notepad++, ctrl + f to find the entity ID (Cremator or whatever), then you should see the transform details, just change it 180 degrees or whatever you need. I strongly suggest against using the map editor for changes that can be done in a text editor as you'll get a crazy diff as it rewrites the file.

**Comment by JustinTrotter** [comment]
> For future reference, open the map in a text editor like notepad++, ctrl + f to find the entity ID (Cremator or whatever), then you should see the transform details, just change it 180 degrees or whatever you need. I strongly suggest against using the map editor for changes that can be done in a text editor as you'll get a crazy diff as it rewrites the file.

Thanks, I'll see about doing that today.

**Pull request closed without merging**
