### PR TITLE
Taser mild buff

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-taser starts with 100 charge and fire cost is 50
-weight has been reduced to 10 so it is pocketable
-skub

:cl: Emisse
- add: Taser is 2 shots and can be pocketed

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
um it seems like you somehow obliterated the file diff as well as nuked the captain's antique laser pistol.

**Comment by Emisse** [comment]
sick

**Comment by Emisse** [comment]
file diff is because i cant edit from github anymore so i just have to upload the whole file again. its really annoying

**Review by wrexbe — CHANGES_REQUESTED** [review]
Don't make the whole yml change, that will cause more issues then it's worth.

**Comment by metalgearsloth** [comment]
I'll just roll the changes into https://github.com/space-wizards/space-station-14/pull/8683

**Pull request closed without merging**
