### PR TITLE
Blood Brothers

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

literally the same as in [design doc](https://github.com/space-wizards/docs/pull/212)

## Why / Balance

ss13 content, more antags real shit

## Technical details

I dunno I just shitstormed it by looking at how other antags work.
Also added "factions" to roundend text to separate BBs teams.

## Media

TBD
image
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None (i think)

## TODO
- [ ] actually implement it correctly

**Changelog**

🆑
- add: Added Blood Brothers - traitors with a bit of brotherly love. Complete your tasks with nothing but a random crewmember on your side!

### CODE REVIEW

**Comment by metalgearsloth** [comment]
This needs updating for antag refactor and a design doc.

**Comment by whateverusername0** [comment]
ok [here](https://github.com/space-wizards/docs/pull/212)

**Comment by whateverusername0** [comment]
what?

**Comment by SpeltIncorrectyl** [comment]
> what?

git shenanigans

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Comment by whateverusername0** [comment]
can someone reopen it? it was a draft PR anyways. i can't resolve merge conflicts like that 😨

**Comment by whateverusername0** [comment]
reopen plis... it was a draft...

**Comment by ps3moira** [comment]
any updates?

**Comment by whateverusername0** [comment]
lost any motivation to work on this pr
feel free to take anything if you want to finish it or make something similar

**Pull request closed without merging**
