### PR TITLE
Fixed oxygen tank names

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
Fixed https://github.com/space-wizards/space-station-14/issues/3561
**Screenshots**

**Changelog**

### CODE REVIEW

**Comment by RemieRichards** [comment]
This isn't the solution, the names and descriptions of gas tanks are loaded from localisations, so they deliberately don't have `name:` or `description:` definitions in the YAML.

If the name/desc aren't be assigned then that's its own issue, they should be getting assigned appropriately (and were recently), and the  spawn menu should be using them properly.

**Comment by PJB3005** [comment]
If I had to take a wild guess, serv3 broke name localization loading.

**Comment by RemieRichards** [comment]
Kill serv3

**Comment by DrSmugleaf** [comment]
> Kill serv3

Hamster
VPl1P8B (2)

**Pull request closed without merging**
