### PR TITLE
smartfridge semi functional

### PR DESCRIPTION
**Pull request by Emisse**
this makes it function like a freezer kinda, i want to make this thing into a vending machine that reads whatevers inside of it and uses that as inventory but vending machine code got me seeing different so i just want to push this fo now

### CODE REVIEW

**Comment by UbaserB** [comment]
woooahhh functionality..!

**Comment by UbaserB** [comment]
i just realised, why no CL?

**Comment by Emisse** [comment]
aint nobody give a fuck about no smart fridge dawg if they did wed have had it functional a long time ago... hard life for a mf smartfridge tryna make a liviing

**Comment by SkaldetSkaeg** [comment]
How far have you come? May i join?

**Pull request merged**
