### PR TITLE
Fingerless insulated gloves

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Adds fingerless insulated gloves to the maint locker random loot pool
About as rare as real insuls for increased humor, getting fingerless insuls every three lockers would dilate the funny
**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no changelog for surprise

### CODE REVIEW

**Comment by lzk228** [comment]
even how?

**Review by lzk228 — CHANGES_REQUESTED** [review]
`meta.json` required

**Comment by potato1234x** [comment]
how lmao

**Comment by JoeHammad1844** [comment]
oops yeah forgot the meta.json

**Comment by JoeHammad1844** [comment]
who is jason

**Comment by metalgearsloth** [comment]
1. why does this have a vox variant.
2. This should use the same loot pool as insuls, not increase it if anything.

**Comment by JoeHammad1844** [comment]
> 1. why does this have a vox variant.
> 2. This should use the same loot pool as insuls, not increase it if anything.

1. I removed the vox stuff
2. I dont know a lot about the code, please elaborate

**Comment by metalgearsloth** [comment]
> I dont know a lot about the code, please elaborate

The gloves look identical to insuls which just dilutes information as you can't tell at a glance if something is budget insuls, insuls, or fingerless insuls.

**Comment by JoeHammad1844** [comment]
its a joke item, it's supposed to trick you

**Comment by PJB3005** [comment]
Get better humor.

**Comment by Peptide90** [comment]
> make them visually distinct and cut insuls/budgets to get them

If you can craft them from normal insuls doesn't that defeat the rarity joke?

**Comment by JoeHammad1844** [comment]
> make them visually distinct and cut insuls/budgets to get them

they are different though, 
icon
icon
above are regular insuls
below are fingerless insuls
as you might be able to tell, the fingers were cut off

**Comment by BolloTea** [comment]
they called me madman

**Comment by Equivocateur** [comment]
Loot change not reflected in the wall locker.
All three variants of insuls should be in an orgroup at this point.

**Comment by EmoGarbage404** [comment]
do we really need more fake insul items? we already have budget insuls. This is just a less funny version of that.

**Comment by JoeHammad1844** [comment]
hold on, wheres the butchering code, I might be able to make insuls cuttable

**Comment by Just-a-Unity-Dev** [comment]
> icon
> icon
> above are regular insuls

I had to open the images in another tab, zoom in, and physically move closer to the monitor to see a difference

**Comment by JoeHammad1844** [comment]
you can make the same argument about regular fingerless gloves. also the sprites look bigger in game

**Comment by NancokPS2** [comment]
> you can make the same argument about regular fingerless gloves. also the sprites look bigger in game

I think the difference between fingerless gloves and normal gloves is MUCH less significant than insuls and fingerless insuls.  
  
If you mistake the former you leave prints.  
If you mistake the later you get zapped (and leave prints).

**Comment by Partmedia** [comment]
I think this is funny. Insulated gloves are valuable items and a few useless versions make for an interesting learning experience. The warning from the name and description already make it adequately clear that this is useless.

**Comment by JoeHammad1844** [comment]
> If you mistake the former you leave prints. If you mistake the later you get zapped (and leave prints).

if you mistake them, you deserve it.

**Comment by JoeHammad1844** [comment]
also this isn't a competitive game, taking this as a super serious balancing change is just not how it should be recieved, this is supposed to be a rare joke item. the point is to confuse or make people laugh, not trick them

**Comment by NancokPS2** [comment]
Ofc. The thing is that any reduction to insul availability reduces antag opportunities and by extension chaos (which is literally what the game is about)  
  
Just make sure this does not reduce the chance of acquiring insuls

**Review by Partmedia — APPROVED** [review]

**Comment by JoeHammad1844** [comment]
syndies have plenty of ways to acquire insuls that isn't getting them in maint lockers

**Pull request merged**
