### PR TITLE
Universal Pinpointer to uplink

### PR DESCRIPTION
**Pull request by FillerVK**
## About the PR

Universal pinpointer added to uplink

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Universal pinpointer to uplink!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
this seems like a comically powerful item for only 2 TC.

not only can you track basically any player no matter where they go, but it also has an infinite range and no way to remove the tracker. It would be more interesting if it was a tracking "bug" instead of just having the infinite funny pointing thing.

**Comment by deltanedas** [comment]
a single-use emagged item combined with a highly protected item shouldnt be 2tc

**Comment by deltanedas** [comment]
a single-use emagged item combined with a highly protected item shouldnt be 2tc

**Comment by asperger-sind** [comment]
Having this at 2 TC seems both overly strong and kind of necessary at the same time, I would buy it at 2 TC and use it at 2 TC, but I would regard this item as suboptimal or only usable for gimmicks when at 4 or more TC.

I propose keeping the pricetag and just reworking the pinpointer into placing a "mark" onto any object/person within your FoV (kind of like a remote) and make the mark visible and removable via doafter after like 5 minutes of placing it, not too visible, but maybe like 3-4 pixels + a context menu message saying something along the lines of "This object/person has a tracker on it!" in red text. Optionally give it a range of xyz tiles so it's not infinite, but thats a proposal for a nerf if the item is still too strong, which I believe it wont be.
It'll still be really good, but it wont be as overpowered, kind of like noslips are right now.

**Pull request closed without merging**
