### PR TITLE
Reorganizes Resources/Constructible

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About the PR 

Splitting this into separate PRs because I want feedback on my organization and want it reviewable.

I haven't touched the Power/ folder (much) since Pow3r makes a lot of changes to it.

- Constructible folder renamed to Structures
- Separated most Base prototypes from their main yml files with exceptions for very specific cases
- Made some changes to ID names particularly for closets since there was ambiguity between ID/name/organization
- Will be mirroring organization across the Textures folder

Should I rename Constructible IDs to Structure or should I change Structures back to Constructible?

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Will migrate sprite files to mirror organizational format when I get some feedback on this.

**Comment by mirrorcult** [comment]
organization LGTM, and i agree with changing constructible->structure since that makes more sense in my mind

**Comment by SweptWasTaken** [comment]
Sounds good i'll work on fixing these conflicts then porting the sprite changes over. One question is that a ton of ID names use Constructible still. Should I change those to Structure?

**Comment by SweptWasTaken** [comment]
The beetles are all dead. Will merge in the morning if no protests.

**Comment by mirrorcult** [comment]
> 
> 
> The beetles are all dead.

not true paul mcartey and rungo are still alive

**Pull request merged**
