### PR TITLE
Make the pipe layer of freezers/heaters snaps to cardinals on eye rotation

### LINKED ISSUE #14253: Freezers/heater sprites shouldn't be NoRot
See the last comment in #14225.

Content Client_0GVeaRDDtN

### PR DESCRIPTION
**Pull request by Menshin**
## About the PR

Fixes #14253 (basically the reason behind https://github.com/space-wizards/RobustToolbox/pull/3808)

***Requires https://github.com/space-wizards/RobustToolbox/pull/4033***, hence the failing tests. I'll trigger them once the engine PR is in.

**Media**

*See Electro second video in the comments below.*

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
no cl

### CODE REVIEW

**Comment by AJCM-git** [comment]
I think to solve that issue the freezers would have to looks like this 

image

**Comment by Menshin** [comment]
IIrc, that's not what Electro had in mind when he made that comment : https://github.com/space-wizards/space-station-14/pull/14225#issuecomment-1440991771

**Comment by ElectroJr** [comment]
With the current version of this PR it looks like this

https://github.com/space-wizards/space-station-14/assets/60421075/bf183687-7db0-4c01-9697-ab026632c8fb

I think you should instead use 
```yaml
      noRot: false
      snapCardinals: true
      granularLayersRendering : true
```
for the sprite comp and `renderingStrategy: Default` for the layer, then it should look like this:

https://github.com/space-wizards/space-station-14/assets/60421075/db199d0f-4fea-4178-bfe5-408bee615f59

Note that this combination currently triggers a debug assert which needs to be updated via an engine PR.

**Comment by Menshin** [comment]
Sure, i thought we were going the "always facing south" sprite except for the pipe layer as previously discussed.

Agreed that the second option looks better, i'm testing/updating that.

**Pull request merged**
