### PR TITLE
add type "Puller" for few pets in .yaml file

### PR DESCRIPTION
**Pull request by pofitlo**
add almost all animals ability to pull things

the reason I do this is to add a little more fun, variety and independence to the pets

## About the PR

**Media**

- [X] this PR does not require an ingame showcase

**Changelog**

:cl:
-add: added ability to drag something for animals

### CODE REVIEW

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Add it to the direct `SimpleMobBase` inheritors you want instead

**Comment by pofitlo** [comment]
hmm. I can't figure out what the problem might be. can I take the test again without changing the files? just a beginner in gita and don't know how to do it

**Comment by pofitlo** [comment]
> Add it to the direct SimpleMobBase inheritors you want instead

@AJCM-git maybe I should mention you? well, just in case. I added the puller type to SimpleSpaceMobBase. I also added a limitation of this possibility for creatures such as bees, snakes, etc.

**Comment by pofitlo** [comment]
AAAAAAAAAA

**Pull request merged**
