### PR TITLE
New Race: Rat Peoples

### PR DESCRIPTION
**Pull request by SaveliyM360**
## About the PR

_"Yaaas, now we have-have the Rat-things! We can eat-eat LOOOT of cheese-cheese and rotten meat-meat!"_

### Rat Peoples!

- **Special Race features:** They pretty immune to toxic food, and poison damage (but still can die from it, if they have TOO MUCH toxins), they more fast that humans, and they get less damage from enviroment (cold, heat)

- **Cons:** They are very fraglie, and take 1.3 Slash damage, and 1.2 Blunt damage.

- **Trivia:** They squeak. _Squeak!_

### **EDIT:**

I do some rebalance, based on LankLTE comment, so now Rats have:

- Not so strong immunity to toxins, they took 0.4 damage from it
- Not so fragly, and now they took more damage from Slash, not from Blunt: 1.3 for Slash and 1.2 from Blunt
- Not so fast. THey speed on 4.7

**Media**

https://github.com/space-wizards/space-station-14/assets/142160914/ebfeae7f-dc25-46da-8c05-49573a3ee8a5

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

(For those fellas who will say "Why...?", I will answer "Why not?")

**Changelog**

:cl:
- add: Nanotrasen has launched a recruitment program for Rat-like humanoids. Chefs, hide your cheese…

### CODE REVIEW

**Comment by LordEclipse** [comment]
I support rat people.

**Comment by DogZeroX** [comment]
Furry upstream moment

**Comment by VigersRay** [comment]
Since we are starting to turn the station into a zoo, I think we should not forget about the pigs, I will try to throw a PR with them these days.

**Comment by LankLTE** [comment]
Putting my feedback here so you can look over it:
Ignoring the prospect of adding a new race because that's not my call, the race balance is just all over the place. 
Their movement speed modifier is 5.5, compared to the base of 4.5, which is _abusurdly_ high. Arachnids had balance issues with their movespeed and they were at 5.0. Making them _immune_ to poison also only really serves to fuck over traitors while also causing a myriad of other issues (they can breathe plasma..?). To put it simply their upsides are super unfun for anyone who has to play against them. No roundstart race should have an immunity to any damage type. 
Their downsides are _way_ too drastic. 2x blunt and 1.4x pierce makes them just die like, instantly to melee (I'm pretty sure a fireaxe will 2 shot them, maybe even with armor) while also not making them any weaker in ranged combat (which is dumb given they're fast enough to avoid melee combat in nearly every scenario). 

With Moths I tried to move away from a race's key features being simple mechanical tweaks. I advise you do the same.

**Comment by SaveliyM360** [comment]
> Putting my feedback here so you can look over it: Ignoring the prospect of adding a new race because that's not my call, the race balance is just all over the place. Their movement speed modifier is 5.5, compared to the base of 4.5, which is _absurdly_ high. Arachnids had balance issues with their movespeed and they were at 5.0. Making them _immune_ to poison also only really serves to fuck over traitors while also causing a myriad of other issues (they can breathe plasma..?). To put it simply their upsides are super unfun for anyone who has to play against them. No roundstart race should have an immunity to any damage type. Their downsides are _way_ too drastic. 2x blunt and 1.4x pierce makes them just die like, instantly to melee (I'm pretty sure a fireaxe will 2 shot them, maybe even with armor) while also not making them any weaker in ranged combat (which is dumb given they're fast enough to avoid melee combat in nearly every scenario).
> 
> With Moths I tried to move away from a race's key features being simple mechanical tweaks. I advise you do the same.

Okay, i do some rebalance

**Comment by potato1234x** [comment]
why though, what happened to the freeze on races? almost none of the races that arent from ss13 are basically identical gameplay to humans except with different damage modifiers

**Comment by LankLTE** [comment]
> why though, what happened to the freeze on races? almost none of the races that arent from ss13 are basically identical gameplay to humans except with different damage modifiers

Moths were allowed through because it was a port from 13 and I did a rewrite of species code to help prevent a maintenance burden. The Race freeze still exists.

**Comment by UbaserB** [comment]
i dont like this, its too similar to existing races.

**Comment by Interrobang01** [comment]
What if rat people weren't roundstart but spawned as a ghostrole in maints or something like that? A lot of the unbalanced but unique features could be put back in then.

**Comment by Myakot** [comment]
Make them quadrupedal. Please no more reskinned-furry-human-copy-paste.

Rat people have such potential for fun, don't make them generic. Skavengang

**Comment by KaiShibaa** [comment]
> Make them quadrupedal. Please no more reskinned-furry-human-copy-paste.
> 
> Rat people have such potential for fun, don't make them generic. Skavengang

That'd require an entire respite of everything for them specifically. Hell

**Comment by metalgearsloth** [comment]
These need to offer a technical benefit or have an interesting design behind them, at the moment it's just some numbers tweaks that also make them stronger than humans. This also lacks the significant number of markings ss13 species offer.

**Comment by potato1234x** [comment]
> i dont like this, its too similar to existing races.

agreed, basically the only gameplay this adds is being able to chug poison since rotten food is almost never seen

**Comment by Zaraka** [comment]
I would also hesitate to add them as a standard playable species, I would be more inclined to add them to some game modes/specific situations, or perhaps if they would be really unbalanced why not include them in currently missing genetics?

**Comment by brainfood1183** [comment]
I think race would be fine if we had genetics and could turn humans into rat hybrids, but as an independant playable and selectable race i think they dont have enough unique going for them.

**Comment by Tunguso4ka** [comment]
would be cool to make them have like 4 legs, make them hold things in mouth (so 0 hands), and +-4 slots of pockets that would be there without clothes.

**Comment by NancokPS2** [comment]
> would be cool to make them have like 4 legs, make them hold things in mouth (so 0 hands), and +-4 slots of pockets that would be there without clothes.

I think that wouldn't work too well for an official playable race (unless this is meant to be event only, like Vox).

**Comment by PixelTheKermit** [comment]
Is there a design doc for this?

**Comment by metalgearsloth** [comment]
Discuss it more on discord if you're committed to getting these in @SaveliyM360 please.

**Pull request closed without merging**
