### PR TITLE
Departmental research announcements

### PR DESCRIPTION
**Pull request by tday93**
## About the PR

Allows technologies to specify additional radio channels to announce their unlock on, in addition to the configured channel on the research console.

Additionally made a first pass at identify which technologies would be relevant to which channels.

## Why / Balance

Currently the station is generally only aware of the problems research can cause, this will allow the station to also be aware of the results of that work.

## Technical details

* Added a RadioChannels DataField to the TechnologyPrototype
* Added a step to the ResearchSystem.Console OnConsoleUnlock method to send the same radio message to each channel configured on the technology
* Updated technology prototypes to include relevant radio channels

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: tday
- add: Science is hoarding fewer of their secrets: Unlocked technologies will now be announced on additional relevant radio channels.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I think its really quite messy to be sending radio channels for things that might not be super relevant (science often may lack the materials to make these objects) and it might just make more sense to have a public noticeboard that has new science unlocks written on it. Its not like the average service player would even know what kinds of things are inside each technology.

**Comment by tday93** [comment]
> I think its really quite messy to be sending radio channels for things that might not be super relevant (science often may lack the materials to make these objects) and it might just make more sense to have a public noticeboard that has new science unlocks written on it. Its not like the average service player would even know what kinds of things are inside each technology.

Wasn't thinking about it as an end-all/be-all solution, more a prompt for folks in relevant departments to ask science about it. 

Which as you pointed out could spark the conversation about lack of materials, hopefully sparking a conversation about acquisition of those materials. 

I just know when I'm playing in other departments, most shifts I don't even _think_ to ask science if they've unlocked anything I could use. This is just a notification to prompt those additional thoughts + discussions.

**Comment by tday93** [comment]
> Can't say I like it. Disseminating this information is good, but the form of delivery (spamming radio channels)... suboptimal.
> 
> This is way too spammy and at the same time kinda irrelevant for a lot of players. This should definitely be a per-character opt-in.
> 
> Wanna hear a great idea where putting this would work perfectly? **PDA App.** Call it station science news bulletin or whatever.
> 
> As a PDA App:
> 
>     * Is opt-in for each individual player (not causing unsolicited chat spam for players who aren't interested)
> 
>     * Is persistent + works for latejoins (players can reference and check past research unlocks at any point in the round, regardless when they joined; solution in this PR needs people to memorize and causes wanton chat scrolling to find past announcement)
> 
>     * Powerful tool for antagonists as a way to keep tabs on station research and their defense abilities (potential future mechanic - takes in encryption keys and only shows the unlocks relevant to the departments whose encryption keys you have)
> 
>     * Pulls PDA from the depths of obscurity
> 
>     * One more place for hackers / rogue AI to shine (spoof records to make crew believe they have access to technology they don't, or that they don't have access to technology they do)

If the goal is discoverability, tucking it away the announcements in a PDA app isn't great either.

I agree that a PDA app which displayed station research would be great, but that's a much larger scope.

I also have to question the characterization of this as spamming - its a single additional radio message per technology, only on channels that technology is relevant to. It may look like spamming for those with access to multiple of those channels - but even then its only one or two more messages per technology.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Agreed on the thoughts above, this is too much radio spam.

**Comment by deltanedas** [comment]
this will also mean sci researches anything from arsenal that isnt exclusively available in secfab -> departmental raid in 5s

**Comment by forgotmyotheraccount** [comment]
Might be a headache but what if you could manually ping the relevant department by clicking on it in the Unlocked Technology list? With a cooldown to prevent spamming.

**Comment by tday93** [comment]
> Agreed on the thoughts above, this is too much radio spam.

Where would be the appropriate place for something like this then? Is what science is researching intended to remain secret, or only accessible by those who know a specific way to check?

> this will also mean sci researches anything from arsenal that isn't exclusively available in secfab -> departmental raid in 5s

How so? the channels on which the research is announced is configured per-technology. There is no discipline -> channel relationship.

**Comment by tday93** [comment]
> Agreed on the thoughts above, this is too much radio spam.

Also @metalgearsloth, if there are specific changes you'd like I'll make them, but if the requested change is "all of it", please just close.

**Comment by Kadeo64** [comment]
i've said this before when this gets brought up but sometimes science researches a bunch of shit at once, like say, arsenal tech during nukies or whatever, which can clog important radio channels with useless information. The average service worker doesn't need to know that science has researched lipid extraction, nor does the average engineer need to know science researched all the filler in industrial tier 1.

**Comment by tday93** [comment]
> i've said this before when this gets brought up but sometimes science researches a bunch of shit at once, like say, arsenal tech during nukies or whatever, which can clog important radio channels with useless information. The average service worker doesn't need to know that science has researched lipid extraction, nor does the average engineer need to know science researched all the filler in industrial tier 1.

My apologies if there were previous attempts at something like this -  I tried to look for any and couldn't find any PRs / previous discussions, hence the PR. 

For any future PRs I open, is it appropriate for me to respond to gameplay/design comments/concerns? Or should I just close + move on?

**Comment by tday93** [comment]
Shifting to draft pending possible PDA Notification system.

**Comment by Kadeo64** [comment]
> My apologies if there were previous attempts at something like this - I tried to look for any and couldn't find any PRs / previous discussions, hence the PR.
It was a topic in the discord once or twice.

**Comment by K-Dynamic** [comment]
Bulletin or PDA would be better so researched techs would be permanently visible instead of being fleeting

**Comment by Arendian** [comment]
Letting all fabricator say once that they now have new items to be produced(like how vending machines talk) could be a solution, but it might be easily missed if the fabricator is stowed away somewhere in a corner.

**Comment by mirrorcult** [comment]
i support this even with it going to radio

**Comment by metalgearsloth** [comment]
Sought maintainer opinion again for a final call and majority opinion was dislike on info spam / oversharing in lieu of potentially something else.

**Pull request closed without merging**
