### PR TITLE
Adds a new medication for headache & pain relief 

### PR DESCRIPTION
**Pull request by ElectroJr**
## About the PR
This PR adds a new medication for headache & pain relief 

## Why / Balance
It will reduce nausea for senior citizens, making the ss14 onboarding process easier. I uhh.. I think it also protects them from slipping on hazzards, which is definitely intentional.

## Technical details
I'm fairly sure it won't accidentally save the modified prediction cvar settings to peoples config files.
Requires space-wizards/RobustToolbox/pull/5017 to avoid impassable bananas
## Media

https://github.com/space-wizards/space-station-14/assets/60421075/c637c58c-0feb-4319-a7bd-d1ebf59c4d73

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Added Tilenol injectors to all emergency boxes

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
oh my god this would be beautiful to keep after the april fools as like a module downstreams could toggle or whatever this is amazing

**Comment by K-Dynamic** [comment]
OpenDream looking different

**Comment by ImWeax** [comment]
ss13 drug real

**Comment by deltanedas** [comment]
> as like a module downstreams could toggle or whatever

anyone can just disable prediction, presumably servers can do this too

**Comment by ElectroJr** [comment]
> oh my god this would be beautiful to keep after the april fools as like a module downstreams could toggle or whatever this is amazing

While it works well enough for April fools or as a joke drug effect, it's really not good enough to be an actual tile based movement system, though if someone does actually write a good implementation we did say we'd keep it for downstreams (#5551), its just that no one has written it.

If people actually want to use it for downstreams, note that there are a few issues with the PR's implementation:
- Broken physics interactions, like slipping and probably others. Those interactions either need to be reworked for tile-based movement, or the movement still needs to use velocity & physics instead of just setting an entity's position, which is kind of janky because then entities can still be pushed off-centre, whereas they should probably actually be anchored to the tiles.
- Pulling/dragging is janky
- Going off-grid into space is janky
- No restrictions for having multiple players on the same tile, and no combat-mode blocking
  - Doing combat mode blocking also has issues with client-side prediction, and even just having one player per tile also probably runs into similar issues with mispredicts. So maybe tile-based movement would actually require just having prediction disabled?
- Probably not performant enough. It should probably use some map of traversable/blocked/reserved tiles instead of constantly doing those `InRangeUnobstructed` and `GetAnchoredEntity` calls. Or maybe actually have a look at how ss13/byond handles tile movement, because I have no idea how it works there.

**Comment by grungussuss** [comment]
as a person from ss13, this is really funny

**Pull request merged**
