### PR TITLE
movercontroller namespace

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
No code changes apart from whitespace

Giving these files the Project Zero Warning treatment but I don't want to do the namespace changes on the same PR as the code update

### CODE REVIEW

**Comment by 0x6273** [comment]
> but I don't want to do the namespace changes on the same PR as the code update

Why not just do the namespace change in a separate commit?

**Comment by Errant-4** [comment]
> > but I don't want to do the namespace changes on the same PR as the code update
> 
> Why not just do the namespace change in a separate commit?

I did that the last time, and apparently that still isn't always easy to review or something

**Comment by 0x6273** [comment]
> > > but I don't want to do the namespace changes on the same PR as the code update
> > 
> > 
> > Why not just do the namespace change in a separate commit?
> 
> I did that the last time, and apparently that still isn't always easy to review or something

It's only difficult if you're looking at the entire PR diff instead of the commit diffs.

**Comment by Errant-4** [comment]
> It's only difficult if you're looking at the entire PR diff instead of the commit diffs.

image

**Comment by slarticodefast** [comment]
>Why not just do the namespace change in a separate commit?

We usually squash merge, so the separate commit would get lost when merging a PR into master.
This way we keeps the file history readable.

**Comment by 0x6273** [comment]
> > It's only difficult if you're looking at the entire PR diff instead of the commit diffs.
> 
> ..

That's just skill issue on Sloth's part if he doesn't know how to look at commit diffs.
image

> > Why not just do the namespace change in a separate commit?
> 
> We usually squash merge, so the separate commit would get lost when merging a PR into master. This way we keep the file history readable.

There's no reason why you'd have to squash the entire PR. You can squash all commits except the one with the namespace change, so you end up with 2 commits.

**Pull request merged**
