### PR TITLE
3rd Track Lenght Fix

### PR DESCRIPTION
**Pull request by he1acdvv**
Please merge this either way whether the song length has been fixed, i've made some changes to the mastering and i've done too much work on it anyways.

Fixed the track not being 2 minutes.

## About the PR

Fixed the length of the Nuke Detonation song Clearly Nuclear, so it works properly now,  

## Why / Balance

So it works. 

## Technical details

None.

## Media

https://github.com/space-wizards/space-station-14/assets/128906677/5cc824ec-1445-4861-bc7a-f68031e0c94f

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: mryikes
- fix: Fixed the length of "Clearly Nuclear", so it plays properly now.

### CODE REVIEW

**Comment by he1acdvv** [comment]
sorry, i meant to write 2 minutees. 🤦

**Comment by metalgearsloth** [comment]
We can just update the code to handle it.

**Comment by he1acdvv** [comment]
> We can just update the code to handle it.

well, as of now, i was told it'll be just much easier if i just do it this way. i don't want the audio cutting abruptly.

**Comment by Errant-4** [comment]
I have a different request/consideration for this song, I think the pause between when it ends and when the "nuke is now charging" sound begins is too long. The other two songs have no more than 3 seconds (including the 1.5 seconds wait built-in between the two sound effects), just a dramatic pause. But this one has something like 10 seconds. I think 7-8 seconds could be removed

**Comment by EmoGarbage404** [comment]
Superceded by #25946

**Pull request closed without merging**
