### PR TITLE
Gas tank output pressure limit

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR
All types of gas tanks now have a max output pressure value of 304 kPa, so internals cannot be changed beyond (what would be) a safe range.
Not related to the release pressure of canisters, which is unaffected

Screenshot from 2023-09-06 20-54-33

## Why / Balance
It is currently possible to set gas tanks to any arbitrarily high output pressure, and inhale their entire volume in one breath, only to discover this somehow does not kill you. By limiting the output pressure to a humanoid-safe range (keeping in mind we are painting with broad strokes, don't come at me with scuba diving documentation), this change somewhat masks this missing barotrauma functionality, and in case such code gets added it will prevent inexperienced or malicious crewmembers from setting any standard issue company gas tank to be instantly crippling/lethal. If desired, it will still be possible to include ways to sabotage the safety on specific gas tanks, or have certain prototypes spawn with a higher output limit

Alternatively, this makes it possible to create inferior gas tanks which can't output the required 21 kPa oxygen/nitrogen pressure, so using them causes gasping and a slow gradual buildup of asphyxiation

## Technical details
No prototypes were modified, all current ones inherit a default value ( 3 x atmospheric pressure ) from GasTankComponent

### CODE REVIEW

**Comment by LankLTE** [comment]
> It is currently possible to set gas tanks to any arbitrarily high output pressure, and inhale their entire volume in one breath, only to discover this somehow does not kill you.

This seems like an odd fix to that problem, rather than making it do what you would expect

**Comment by Partmedia** [comment]
> This seems like an odd fix to that problem, rather than making it do what you would expect

Except what do you expect would happen? As we [discussed here](https://discord.com/channels/310555209753690112/770682801607278632/1149035195018780693) people would probably not actually explode.

This also makes fairly reasonable sense since real pressure regulators do have an upper limit, because you can only rotate the spring so much, see [1](https://en.wikipedia.org/wiki/File:Pressure_regulators_schematic.png) and [2](https://www.force-e.com/blogs/blog/scuba-regulators-explained/).

**Comment by LankLTE** [comment]
Eh, I don’t really mind that much. It just seems like it’s trying to solve problems that don’t exist yet and may end up causing problems in the future. Won’t stop it being merged or whatever.

**Review by Partmedia — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
