### PR TITLE
Error on warnings.

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
Forbids warnings.

You can no longer write code with warnings in it.
TODO: Make this tests only if possible but mostly for compromise- I'd rather it be global.

### CODE REVIEW

**Comment by theashtronaut** [comment]
based

**Comment by wrexbe** [comment]
Yeah get this thing working moony, I hate all the warnings.

**Comment by wrexbe** [comment]
Kind of buried in crap, but this is why it failed
```
Error: /home/runner/work/space-station-14/space-station-14/Content.Client/Entry/EntryPoint.cs(40,7): error CS0105: The using directive for 'Robust.Shared.Configuration' appeared previously in this namespace [/home/runner/work/space-station-14/space-station-14/Content.Client/Content.Client.csproj]
```

**Comment by 0x6273** [comment]
I think this should only be set in the workflow yml. When developing it would be annoying to have your build fail due to things like unused variables.

**Comment by wrexbe** [comment]
> I think this should only be set in the workflow yml. When developing it would be annoying to have your build fail due to things like unused variables.

On the other end, the build might fail because you forgot to use the variable you added, and it can end up saving you time.

**Review by PaulRitter — CHANGES_REQUESTED** [review]
this should be workflow/server only, not happen on local development

**Pull request closed without merging**
