### PR TITLE
Changes the signature for Popup params to match Sound

### PR DESCRIPTION
**Pull request by keronshb**
## About the PR 

fixes: #8116

I tested it on a few things (not everything), no errors and popups worked. So I'm assuming everything will work fine.

**Changelog**

### CODE REVIEW

**Comment by Zumorica** [comment]
Not to turn this into a bikeshed, but personally I liked the old way better: actual content before the player filter, easier to read at a glance

**Comment by ElectroJr** [comment]
> Not to turn this into a bikeshed, but personally I liked the old way better: actual content before the player filter, easier to read at a glance

I agree, its probably better to change the sound to match the popup params.

**Comment by keronshb** [comment]
> > Not to turn this into a bikeshed, but personally I liked the old way better: actual content before the player filter, easier to read at a glance
> 
> I agree, its probably better to change the sound to match the popup params.

That's an engine change right?

**Comment by ElectroJr** [comment]
> That's an engine change right?

yeah

**Comment by Zumorica** [comment]
If anything, I'm pretty sure every maintainer agrees that the current sound API is due for a *big, big* refactor

**Pull request closed without merging**
