### PR TITLE
door electronics can be programmed by hop

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
door electronics working like in cheackraze's suggestion in #12424
multitool to inspect accesses like in the base pr

to change access instead of using your id, you go to hop and ~~break in~~ ask them nicely to set the accesses

jobs require *any* of the listed accesses, not all. so sammy salvage / gary graytide example still applies. HoPs should be aware of this before setting job to captain expecting only cap to be able to open, but in reality anyone will be able to.

also only programmed electronics will have accesses, ripping out the bridge doors' electronics and putting them back will make them AA since currently it doesnt make mapped doors copy their accessreaders to their electronics. could be done in the future but it's pretty minor, you can just bolt it open if you want to fuck with the bridge

**Media**

https://user-images.githubusercontent.com/39013340/225238655-35ebbaad-cec4-433a-b16f-451001bafc61.mp4

- [X] I have added a video to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: You can now change door electronics' access requirements in id card consoles.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
engi should be able to do this w/o the need to go to HoP, if you *really* want the access lock then make it CE

**Comment by deltanedas** [comment]
then this needs either:
- reimplementing entire id card console just for ce to use which is silly
- ce to go to hop anyway to get specific access ids to swipe, defeats purpose of not going to hop

**Comment by Just-a-Unity-Dev** [comment]
i thought it was using multi on electronic, not insert electronic into HoP console. i mean this impl. is fine i guess but it's a big inconvenience when engineering has to rely on someone else in order to do their job

**Comment by deltanedas** [comment]
it could be done (and remove listing them on examine at same time) but that would be largely duplicating the id console ui

**Comment by Stealthbomber16** [comment]
good fit with #14699
once both of these get merged i think it makes a lot of sense to start putting id card consoles in head offices and removing the id card console objective

**Comment by deltanedas** [comment]
it would but as i said it would need duplicating 99% of the id console ui and i dont want to do that

**Comment by vulppine** [comment]
this is definitely a departure from the multitool-on-electronics mechanic that SS13 uses

like Just-A-Unity-Dev said above, the reliance on the ID console could make door modification take a lot longer than it would with the SS13 way of doing it (as you'd have to take all the electronics to the HoP or whoever would end up owning an ID console if the HoP is removed)

equally, you could also just separate the access list from the ID console window and just turn it into its own control if you're worried about duplication - and then make a new BUI/window out of that

**Comment by tom-leys** [comment]
Now that  #14699 is merged (Id console only grants limited access) we should revisit your PR @deltanedas . We can also provide these console to the CE and other heads, where they can program door circuitry for their departments.

**Pull request closed without merging**
