### PR TITLE
Made the dank pizza actually dank

### PR DESCRIPTION
**Pull request by JoelZimmerman**
## About the PR
Changed the recipe for the dank pizza to be made with cannabis leaves instead of ambrosia vulgaris. Now the pizza lives up to the name and the hippies will be happy.

## Why / Balance
As the name "dank pizza" suggests one would expect it to be cooked using some dank weed, so that's what I changed the recipe to include, a few cannabis leaves. It only requires two cannabis leaves so the leaves and pizza both has the same amount of THC.

## Technical details
- Changed the cooking recipe to be cooked with 2x cannabis leaves instead of 3x ambrosia vulgaris.
- Changed the solutions to have 30u THC in a whole pizza, or 5u in a slice.

## Media
https://github.com/user-attachments/assets/132558d8-5d44-4642-81cb-0719de04e229

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Dank pizza is now cooked with cannabis leaves instead of ambrosia vulgaris.

### CODE REVIEW

**Comment by deltanedas** [comment]
so dank the base and sauce have no nutritional value

**Comment by Plykiya** [comment]
> so dank the base and sauce have no nutritional value

high and hungry because my pizza didn't even count as food

**Comment by JoelZimmerman** [comment]
> so dank the base and sauce have no nutritional value

Sorry, i had the munchies when i did that, now it has some nutritional value.

**Comment by Admiral-Obvious-001** [comment]
I personally don't fully agree with the complete removal of the Doctors Delight, which was one of the main reasons (I think) to make the pizza. It definitely should make you high though.

**Comment by githubuser508** [comment]
> I personally don't fully agree with the complete removal of the Doctors Delight, which was one of the main reasons (I think) to make the pizza. It definitely should make you high though.

This would require spriting, but maybe keep the current ambrosia pizza as "herbal pizza" to indicate its healing properties and then implement the dank pizza separately?

**Comment by EmoGarbage404** [comment]
yeah... this is dank

**Pull request merged**
