### PR TITLE
Remove kvass

### PR DESCRIPTION
**Pull request by metalgearsloth**
- Tank sprite looks bad.
- Adding region-specific things is cringe.
- I don't think I've ever seen it ordered.
- There's no reason to have one drink in a tank.

:cl:
- remove: Remove kvass.

### CODE REVIEW

**Comment by Emisse** [comment]
i love kvass

**Comment by AruMoon** [comment]
cringe

**Comment by Tupa-Humus** [comment]
oh no. cringe

**Comment by PuroSlavKing** [comment]
cringe

**Comment by Mr0maks** [comment]
~~ultrakill~~ ultracringe

**Comment by PMCMidas** [comment]
cringe, kent

**Pull request merged**
