### PR TITLE
artifact resprite

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Sprites by Flaborized on Goonstation.

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The artifact division has finally remembered to wash alien artifacts before giving them to scientists. They should now look significantly better.

### CODE REVIEW

**Comment by Nails-n-Tape** [comment]
swag

**Comment by forgotmyotheraccount** [comment]
please pay your respects to the weird green pickle rock

**Comment by EmoGarbage404** [comment]
> please pay your respects to the weird green pickle rock

image

**Comment by Nails-n-Tape** [comment]
never forget

> > please pay your respects to the weird green pickle rock
> 
> image

**Pull request merged**
