### PR TITLE
add: spare cap id to cap office

### PR DESCRIPTION
**Pull request by SinisterSamtaro94**
## About the PR 

**Screenshots**

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Elijahrane** [comment]
don't they already have a spare in their locker

**Comment by Mervill** [comment]
Captain's locker already contains a spare id,

https://github.com/space-wizards/space-station-14/blob/4b5df9b0f72e9f0ae8939b26948aab8fff306c00/Resources/Prototypes/Catalog/Fills/Lockers/heads.yml#L28-L61

**Comment by Scribbles0** [comment]
according to the mapping checklist, there also has to be a spare outside of their locker on a desk or something

**Comment by Just-a-Unity-Dev** [comment]
> according to the mapping checklist, there also has to be a spare outside of their locker on a desk or something

isn't the mapping checklist unofficial

**Comment by SinisterSamtaro94** [comment]
I think keeping it in the locker just makes it more annoying for people in salamander to access the id when it is needed for captaincy. If you have to break the cupboard to get the idea, you basically leave anything else that is in that cupboard somewhat compromised. The idea being that we can prevent that issue in the first place just by leaving the spare on the desk for a head to collect in the case that there is now captain.

**Comment by Just-a-Unity-Dev** [comment]
If we map one in the locker and in the map we'll have 3 IDs in total (including the captain)

**Comment by SinisterSamtaro94** [comment]
if you want l can remove the spare from the cupboard and leave the initial on the desk.

**Comment by Scribbles0** [comment]
> If we map one in the locker and in the map we'll have 3 IDs in total (including the captain)

p sure this is how most maps work (mine included)

**Comment by Emisse** [comment]
it is fine to have 3 total, up to mapper

**Comment by Cheackraze** [comment]
Yea kettle has 3 total for pretty much this reason

**Comment by metalgearsloth** [comment]
Map's removed so gottem

**Pull request closed without merging**
