### PR TITLE
New crop: Cotton

### PR DESCRIPTION
**Pull request by DoubleRiceEddiedd**
## About the PR

In this PR, I have added cotton plant and cotton bol as produce. Cotton bol can only be eatten by moth people and mothroach.  Hatchet and knife can chop cotton bol into cotton. Cotton seed can be obtain in MegaSeed Servitor.
## Why / Balance

Botany lack of the ability to supply moth people food in emergency, and make already existant item cotton to have a actual way to obtain in game for the potential future use.
## Media

擷取

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: eddiedd
- add: cotton seeds are now available from the MegaSeed Servitor.

### CODE REVIEW

**Comment by lzk228** [comment]
:trollface:

**Comment by Luxzhv** [comment]
Like, this has no other function other then feeding moths currently?

**Comment by lzk228** [comment]
would be cool to create cloth somehow

**Comment by DoubleRiceEddiedd** [comment]
According to what I saw in #12629 , cotton do should be able use to make cloth in some machine, but i don't know how to make it possible due to my lack of experience. So this PR's goal is just simply make cotton actually obtainable and add something moth can eat, and that is it.

**Pull request merged**
