### PR TITLE
Resprite the equipped gas canister suit slots

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

This PR changes the sprites when generic, nitrogen and oxygen canisters are worn on the back or suit slot. Ideally the sprite should go "underneath" the backpack layer but over the EVA, but I have absolutely no idea on how to do that and it likely requires code, so this will be something for the future.

## Why / Balance

The old sprite went over the backpack and looked bad. This new sprite is inspired by PKA suit storage and how that fits well for salvage.

## Media

image

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Ubaser
- add: Oxygen and nitrogen canisters now have new sprites when worn.

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
How do these look on sec gear? Can we also get side-facing shots of the canisters with backpacks on?

**Comment by UbaserB** [comment]
> How do these look on sec gear? Can we also get side-facing shots of the canisters with backpacks on?

image

image

**Comment by Golinth** [comment]
how does this look with no backpack? It might be a bit odd with a satchel

**Comment by UbaserB** [comment]
> how does this look with no backpack? It might be a bit odd with a satchel

image

**Pull request merged**
