### PR TITLE
Jailbreak Warden PDA

### PR DESCRIPTION
**Pull request by Ghagliiarghii**
## About the PR

Gives the Warden a musical instrument in their PDA
## Why / Balance

Fixes "The OS appears to have been jailbroken" but no additional features.

Warden has lots of downtime, many maps have opted to give warden a guitar to play some tunes during this downtime but not all. The musical instrument is a harmless addition in terms of balance and helps pass the time before things get going. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Jailbroke Warden's PDA! (Adds a music player)

### CODE REVIEW

**Comment by deltanedas** [comment]
where uplink :trollface:

**Comment by Veritable-Calamity** [comment]
This is an innocent enough change, but when it comes down to it the PR itself does already mention there are tools for this in the medical areas in most brigs, and an instrument stowed in the Warden's office on most maps. Making it part of the PDA feels odd, and from a perspective of job encroachment should probably just be left to actually using the physical item.

I can see the use-case, but it opens up a slippery slope of expanding PDA capabilities across many jobs (and thus making less and less people rely on the jobs those changes encroach on) and I don't feel that's a rabbit hole that leads to an improvement in gameplay.

**Comment by Ghagliiarghii** [comment]
> This is an innocent enough change, but when it comes down to it the PR itself does already mention there are tools for this in the medical areas of most brigs, and an instrument stowed in the Warden's office on most maps. Making it part of the PDA feels odd, and from a perspective of job encroachment should probably just be left to actually using the physical item.
> 
> I can see the use-case, but it opens up a slippery slope of expanding PDA capabilities across many jobs (and thus making less and less people rely on the jobs those changes encroach on) and I don't feel that's a rabbit hole that leads to an improvement in gameplay.
> 
> Also, "The OS appears to have been jailbroken" is just a pun on jailbreaks and the warden's job to prevent them.

I hear you about the job identity thing especially. I really just want something to go with the flavor text (yes I know it's a pun we all know). There aren't too many options currently to represent 'jailbroken' so I just went for the most obvious ones without trying to make an entire new module just for this. (Would be cool if he had Nanotrasen Block Game on his PDA or something tho). I'm willing to take suggestions on how to improve this. Maybe the medical scanner can go since I could argue lore wise that's a physical addon and not something all pdas have that's simply software locked out? I'll give it some more thought.

**Comment by Killerqu00** [comment]
just change the flavor OS name in lower left corner if you want it to be actually "jailbroken"

**Comment by Veritable-Calamity** [comment]
> > This is an innocent enough change, but when it comes down to it the PR itself does already mention there are tools for this in the medical areas of most brigs, and an instrument stowed in the Warden's office on most maps. Making it part of the PDA feels odd, and from a perspective of job encroachment should probably just be left to actually using the physical item.
> > I can see the use-case, but it opens up a slippery slope of expanding PDA capabilities across many jobs (and thus making less and less people rely on the jobs those changes encroach on) and I don't feel that's a rabbit hole that leads to an improvement in gameplay.
> > Also, "The OS appears to have been jailbroken" is just a pun on jailbreaks and the warden's job to prevent them.
> 
> I hear you about the job identity thing especially. I really just want something to go with the flavor text (yes I know it's a pun we all know). There aren't too many options currently to represent 'jailbroken' so I just went for the most obvious ones without trying to make an entire new module just for this. (Would be cool if he had Nanotrasen Block Game on his PDA or something tho). I'm willing to take suggestions on how to improve this. Maybe the medical scanner can go since I could argue lore wise that's a physical addon and not something all pdas have that's simply software locked out? I'll give it some more thought.

Yeah if you got rid of the medical scanner and just kept this PR to allowing the warden to play music or something I think that would help out a lot more. This is out of scope of this PR, but in future PDAs may be defined by cartridges loaded in them.

**Comment by Ghagliiarghii** [comment]
I'm electing to revert the medical scanner part of this PR for reasons stated above. I'll want to attempt that NT Block Game thing later but out of scope of this PR for now. I would like the NT Block Game to be part of the PDA cartridge system (not yet implemented) and obtainable also through rare maints loot / salvage / science.

**Comment by metalgearsloth** [comment]
Discussed with other maints, just grab an instrument you don't need to have everything for every situation.

**Pull request closed without merging**
