### PR TITLE
China Lake Buff

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 

**Screenshots**

**Changelog**

:cl:
- tweak: The China Lake's projectiles now have smaller explosions.
- tweak: The China Lake bundle no longer comes with flash grenades.

### CODE REVIEW

**Comment by DogZeroX** [comment]
You mean nerf

**Comment by HoidC** [comment]
> You mean nerf

you weren't able to use them indoors without killing yourself before so

**Comment by DogZeroX** [comment]
Sounds like a skill issue

**Comment by EmoGarbage404** [comment]
Pretty sure higher direct damage and less friendly fire capabilities qualifies as a buff

**Comment by asperger-sind** [comment]
> no flash nades
Life sucks, no more funzies.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
