### PR TITLE
Frezon Canister Tweaks

### LINKED ISSUE #14420: Frezon canisters contain N2O
## Description
What the title says.

**Reproduction**
1. Spawn a canister of frezon
2. Fall asleep instead of tripping out like you anticipated.

**Screenshots**

Content Client_Rm3tZbMaQd

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Fixes #14420. Also gives the canisters a half decent sprite.

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: Changed the sprite of frezon canisters.
- fix: Fixed frezon canisters spawning with N2O in them.

### CODE REVIEW

**Comment by deltanedas** [comment]
much nicer sprite

**Comment by Flareguy** [comment]
The shade of blue on the sprite is much nicer, but I did like the yellow on the old canister. It's very in-your-face and paints frezon as a kind of "quirky" gas, which fits well considering its strange properties.

**Comment by potato1234x** [comment]
> The shade of blue on the sprite is much nicer, but I did like the yellow on the old canister.
Believe me i tried to make it look good, the two colors just look really bad together

**Comment by potato1234x** [comment]
> The shade of blue on the sprite is much nicer, but I did like the yellow on the old canister.

Believe me i tried to make it look good, the two colors just look really bad together

**Pull request merged**
