### PR TITLE
Syndicate Sniper bundle change and rework of the anti-material ammo box

### PR DESCRIPTION
**Pull request by Jackal298**
## About the PR

This PR is aimed at reworking the sniper set, after improving the anti-material cartridge, this weapon became quite formidable, at first they gave it a 5 second delay between shots, but what prevents you from buying 2 for 12 TС and annihilating everything alive? I raised the price to 12 and one set and also reduced the number of cartridges to 10

I also finalized the prototype boxes for anti-material cartridges, it was old and contained an error in which it was impossible to put cartridges back into the box, also now there are two boxes, for 10 and a large one for 30 cartridges

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Raised the price of the sniper bundle from 6 to 12 TC and reduced the ammo supply from 30 to 10
- fix: Fixed the issue of not being able to put the Anti-Material Ammo back into the Anti-Material Ammo Box

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
I originally intended the bundle to be 12TC, but it was merged as 6 because I lowered it and didnt know the ammo buff was nerfed, sorry. but I think it should go back to 30 spare, 15 total is just too little for 12TC, even for what it offers. ill PR that in a moment

**Comment by Jackal298** [comment]
> I originally intended the bundle to be 12TC, but it was merged as 6 because I lowered it and didnt know the ammo buff was nerfed, sorry. but I think it should go back to 30 spare, 15 total is just too little for 12TC, even for what it offers. ill PR that in a moment

Don't anti-material rounds have the ability to ignore armor?

**Comment by Jackal298** [comment]
or am I confused? ok, I think 10 is enough so that people don't shoot everything that moves and save ammo, I will also make a version of the bundle for core supporters, where there will be a box for 30 rounds

**Comment by JoeHammad1844** [comment]
> or am I confused? ok, i think 10 is enough for people not to shoot everything that moves and save ammo, i will also make a version of the bundle for nuclear operatives, where there will be a box for 30 rounds

that makes sense, but I still think it should universally be 30 rounds, with syndies you're basically on your own against the entire station so they need a good amount of ammo, with nukies you are also up against the entire station but you have friends who can heal you and watch your back

so the less advantaged syndie gets less rounds? im not saying nukies should get the small box, though. they both need the full box. there are just so many targets that 15 total isnt enough

**Comment by JoeHammad1844** [comment]
I think the price being 12 is fine, that;s what I originally intended it to be when I brainstormed it, 10 would be acceptable, but mainly I just want the ammo box it comes with to hold 30 again

**Comment by LankLTE** [comment]
> or am I confused? ok, i think 10 is enough for people not to shoot everything that moves and save ammo, i will also make a version of the bundle for nuclear operatives, where there will be a box for 30 rounds

Remember that in its current state it can 2 shot and effectively acts as a taser. I don’t see why only having 15 shots is a problem.

**Comment by JoeHammad1844** [comment]
with 15 bullets you have about 900 damage total, but only enough to kill 7 people because you need to two shot, at maximum, without missing a SINGLE shot. if you buy a viper and 7 mags for 10TC you can kill the same amount of people somewhat easier because its full auto and shoots about 20x faster.

you also cannot buy more ammo for the hristov so you're stuck with 15 unless you buy another (24 total) by either being a nukie or killing renault, and syndies have ONE telecrystal of leeway there

**Comment by JoeHammad1844** [comment]
with two sniper bundles that is 1800 damage, translating to 15 crits. which is still worse than if you just bought a viper and ammo
image

**Comment by JoeHammad1844** [comment]
like yeah it stunlocks people but you need to wait 4 seconds and in that time someone could easily gun you down while you are fucking defenseless

**Comment by LankLTE** [comment]
> like yeah it stunlocks people but you need to wait 4 seconds and in that time someone could easily gun you down while you are fucking defenseless

can’t you just pull out a different gun or cuff them? Just because you can’t fire the hristov again doesn’t mean you’re “fucking defenseless”

**Comment by JoeHammad1844** [comment]
well when I said defenceless I was thinking about if you bought a hristov and hardsuit, my mistake

**Comment by JoeHammad1844** [comment]
you can buy a hristov and webvest, which gives you 5 more TC to play around with, like a medkit or viper and two mags or viper and no slips, but unless youre going up against like 3 people one at a time. and you dont have space protection

**Comment by JoeHammad1844** [comment]
*but thats only good if youre going up against like 3 people one at a time

**Comment by JoeHammad1844** [comment]
if even two officers are up against you and you have everything, hristov, viper, hardsuit and noslips, yeah you can stun one and if you land EVERY viper shot, including the extra one in the chamber, then finish off the other guy with the hristov, you'll win. but thats hard

**Comment by JoeHammad1844** [comment]
you'll win your gunfight but it just isn't sustainable for syndies

**Pull request merged**
