### PR TITLE
Under Toned Tail

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Gives the smooth tail a second coloring layer, to emulate an under tone color.

## Why / Balance
Further customization. Fits well with the underbelly option.

## Media
A few different styles to showcase how it pairs with things.
image
What it looks like when wagging.
https://github.com/space-wizards/space-station-14/assets/110078045/e30863ee-250e-45f1-b5b2-bbb97fc3ae0c
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl:
- tweak: The smooth tail now has a second color layer to customize.

### CODE REVIEW

**Comment by Nairodian** [comment]
Fuck wait hold on I forgot Locle.

**Comment by UbaserB** [comment]
This is so cute omg

**Comment by pigeonpeas** [comment]
if we had this on the thick tail i would.. uhm.. be very happy :)

**Comment by UbaserB** [comment]
> if we had this on the thick tail i would.. uhm.. be very happy :)

very true… the thick tail still needs wag emote too. #24151

**Comment by Nairodian** [comment]
> if we had this on the thick tail i would.. uhm.. be very happy :)

I can try that out on a different PR at some point.

**Pull request merged**
