### PR TITLE
Gas analyzer added to Atmos PDA

### PR DESCRIPTION
**Pull request by pies32**
## About the PR

It adds gas analyzer functionality to the Atmos PDA and CE PDA. You use the PDA like a normal gas analyzer, and can still access the PDA UI using the use key and clicking on it.

The gas analyzer does not close when pocketing or putting the PDA into the PDA slot. This is so Atmos can have their hands free and still have access to information about the environment, or pipes.

**Media**

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

**Changelog**

:cl:
- add: Added gas analyzer to CE PDA
- add: Added gas analyzer to Atmos PDA

### CODE REVIEW

**Comment by deltanedas** [comment]
i think you should make this a cartridge rather than a component on the pda so if you say get promoted to either job you can take old one's cartridge or maybe get one from a vending machine

**Comment by mirrorcult** [comment]
this should use a PDA cartridge and not a component on the PDA

**Review by mirrorcult — CHANGES_REQUESTED** [review]
see above

**Comment by metalgearsloth** [comment]
@pies32 you coming back to this?

**Comment by pies32** [comment]
> @pies32 you coming back to this?

I plan on it. It has been difficult to contribute with school but I graduate soon.

**Comment by metalgearsloth** [comment]
NW just let us know and we'll re-open it.

**Pull request closed without merging**
