### PR TITLE
Make the plant anom more useful to service

### PR DESCRIPTION
**Pull request by shibechef**
## About the PR
Plant anomaly bulbs now have exotic plants (bungo, cannabis, tobacco, etc) at a 2/3 weight, and some mutated plants (lemoons, deus, steel caps, etc) at a 1/3 weight. Rock crabs from rock anoms also have about double the ores dropped on death.

## Why / Balance
Currently anomalies are a nuisance to every member of the station, all but the liquid anomaly, which can bring useful or interesting reagents for chemistry or the bar to use. This is because they have no upside, but making points for science. I recently had botanists help take care of a plant anomaly because they slightly benefited from the plants and were the most capable of destroying the kudzu with their scythes, and thought, maybe this could be a normal thing with worthwhile benefits, as some anomalies are nearly tailored to be handled by a department, but they don't get anything from it. 
An obvious way to make plant anomalies a nice gift for botany would be getting exotic plants that they can only get from cargo ordering, and mutated plants that are easy to get with mutagen, but most are never grown because mutagen is usually limited. The plants previous to these changes were things that botany have an extreme surplus of in their seed vendor. Rock anomalies also currently don't make enough ore for it to be considered a factor in whether to kill the anomaly or not, especially after the ore processor rates were nerfed, and as they produce a single ore type over their lives, might be able to supply a station's need for a single material the entire shift. 

## Technical details
added more items to yaml lists
despite testing it all in game, something might be terribly wrong as this is my second pr

## Media
Screenshot (804)

## Breaking Changes
none

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: The plant anomaly's bulbs now have a chance to drop exotic and mutated plants when harvested.

### CODE REVIEW

**Comment by shibechef** [comment]
Yeah its kinda hard to make anoms more fun/interestinng/useful when the anoms whole thing is that it spawns disjointed flesh creatures. I might remove the animals from the flesh anom and do another pr later that has straight up flesh animals (like fleshy cows) if that doesn't count as part of the pet pr freeze

**Comment by shibechef** [comment]
okay i reverted the flesh anom changes, i really didn't think it fit well but it was funny

**Comment by shibechef** [comment]
> Adding mutations into floral anomaly = kill botanist gameplay

Nae nae, I have 70 hours in botany and this will not ruin botany gameplay by any means. Most experienced botanists go in with a goal of min maxing a single plant for desired traits, as one plant is all you need chemical-wise. Even if you got deus roundstart, you can go SO much further with it. It is entirely possible you could go for omni, poly, and aloe all in one plant, have that plant self harvest 10 crops every 5 minutes, each with the maximum amount of chems per crop. But they also have several other botanists using trays, cargo, kitchen, and chem requests, and with a limited amount of muta so they really won't be making anything but 1 or 2 predetermined mutated plants. Its also VERY unlikely you will get something desired like deus from a plant anom in a shift as plant anoms are 1 in 12 anoms, they make so few bulbs, and its still like 1 in 15 to even have a mutated plant in it. 
The new botanists on the other hand will probably not be using muta and they just make sure the plants stay weeded, hydrated, and satiated. Botanists also usually claim trays and don't let each other mess with each others plants, so even if paired with someone experienced, they are stuck handling their own 2 yield 1 potency bananas the entire shift. 
The experienced botanist is likely busy making optimizing a meta plant and won't ever go for something like mimanas, lemoons, chilly, or meatwheat, and the new botanist is stuck with their shitty boring plants all shift. Its really just gives botany a random mutated plant that would likely not get grown otherwise, and it gives plant anoms a purpose outside of points.

**Review by Admiral-Obvious-001 — APPROVED** [review]
Anything to make anomalies not "kill it now"

**Review by TheShuEd — CHANGES_REQUESTED** [review]
we decided that giving standard mutations to an anomaly is a bad idea. If you want to put mutated produce, you need to add seedless variants of these plants so they can't be re-produced.

a seedless version of all plants in general would be a useful solution

**Comment by shibechef** [comment]
understood, thanks

**Pull request closed without merging**
