### PR TITLE
Spiral station

### PR DESCRIPTION
**Pull request by ChilbroBaggins**
About this PR. 

First, I am aware of the freeze. Although I had about a month of work in the map before I found out, I do understand why it’s in place. There was also an asterisk on the freeze noting that “we're taking maps but they have to be high-effort and distinct.” So, I pushed on and continued mapping because I strongly believe this maps fits those requirements. Also, it felt wrong to just leave it unfinished. 

The map is finished in terms of I’ve done all I can to ensure it’s fully fleshed out, detailed, and contains all required assets. I also know that I need feedback/player testing and that some things will need to be adjusted/edited/removed/added/etc. based on the experience of the maintainers and other experienced mappers. 

I have already received feedback from several experienced mappers in Discord. Most of it very positive and helpful. At this point though, I simply need feedback from those that would eventually approve this PR to make the map available to the server. 

Issues I’m aware of:

1.	Walls in the hotel are made of silver walls. I really want these walls to be beautiful compared to the rest of the map in order to fully embody the wealth/class disparity of the upper level of the map vs. the lower. It is home to the dept. heads though, and therein lies the problem that the walls are indestructible. I understand the problems this creates. So, what are the solutions? Can I PR a construction graph? Is it that simple? Or are you preventing this for some reason I am unaware of? If not, can I PR some pretty walls to put in place of them that do not require silver?

2.	I likely overstocked on supplies in some areas. If some materials need to be culled, let me know. 

3.	I might need to adjust the arrivals arm/shuttle to accommodate the cargo shuttle. Need to test.

4.	For some reason I cannot get a Map Render. Both Peptide and I have tried. We raised the issue to one of the coders in Discord but did not receive a response. Any help here would be appreciated.

5.	I imagine there is going to be at least one person protesting the use of conveyor belts as speed walks in several areas.

**In defense:** I have tested these and they work great. I believe these are central to the design of the map and to giving it an element that sets it apart from other maps. I know that players are asking for this and will enjoy it. Several veteran mappers have backed me up on this inclusion and encouraged me to go forward with it.  I do hope it will at least be given a chance to be player tested before outright dismissing it.

Here is my map description for further context and details:

**Welcome to Spiral Station.**

> Inspired by the world of Expanse, Spiral Station is based on Ceres, one of the first human colonies in the Outer Planets.
> Like Ceres, Spiral Station has grown significantly in a confined space over the years. Older levels (Dock and Medina) have become less maintained while resources are diverted to the Central Command, District, and Plaza levels before trickling down through Midtown, rarely reaching Medina and Dock. 
> 
> Moving through the station, you should feel this socioeconomic divide and resource disparity. Pirates, smugglers, and gangs control the lower levels making it risky for Sec-Officers to travel there without a number of reinforcements. Likewise, several checkpoints are set up in strategic locations to restrict the travel of criminals, as well as to prevent violence and the flow of illicit goods into the upper levels. 
> 
> While life in the slums of Medina is dismal, dark, and cramped, life in the Plaza level is spacious, clean, and secure. Illegal fighting dens and black markets are replaced with upscale restaurants and bars, a luscious park with an amphitheater, and the luxurious Plaza Hotel where department leaders are set up with all the best accommodations.
> 
> Mining on the asteroid is the primary reason the station was set up. Several tunnels lead into the heart of it, opening up many opportunities for exploration, looting, and acquiring essential resources. 
> 
> The Central Line cuts through the middle of the asteroid creating a direct, expedited route from Docking to Command. While it is open access to the citizens of the upper levels it is closed off to only the essential departments on the Dock Level side due to a history of illegal activities and other security concerns. (Of course, where there’s a will…there’s always a way…)  

Please let me know any feedback you have and what I can do to get this map ready for play, (if not now, then when the freeze is lifted. I am open to all suggestions/criticisms. I may defend some of my design choices but ultimately will accommodate what is necessary by the maintainer’s standards. 

**Thank you.** 

*I am attaching some screenshots in place of a render until I am able to get one. They are not the best quality but will give a general idea of the station for now
SS1
SS2
SS3
SS4
.

### CODE REVIEW

**Comment by mirrorcult** [comment]
added guards for `EntityPainter` and the renderer is failing on two arcade machines for some reason, I'll look later.

Full render:

spiralstation-0

**Comment by metalgearsloth** [comment]
An existing map will need to be rotated out for this.

The reason for the map freeze is because right now coders have to maintain every single map (i.e. ~22maps + 24 salvage maps) if changes are made and not the mapmakers.

**Comment by ChilbroBaggins** [comment]
> The reason for the map freeze is because right now coders have to maintain every single map (i.e. ~22maps + 24 salvage maps) if changes are made and not the mapmakers.

Understandable. If/when we get to the point of this map being merged, let me know how I can continue to support it. I am certainly capable of editing yml and I have some capacities with c# as long as I get familiar with the code first.

**Comment by PaulRitter** [comment]
> 1. ...the walls are indestructible. [...] Can I PR a construction graph?

i dont see anything speaking against this. the walls are likely indestructable due to either not being ported correctly or only being used in centcomm in ss13. either or, they should be fine to be made destructable

**Comment by PaulRitter** [comment]
i like this map

**Comment by metalgearsloth** [comment]
Alright I took a look at it:
- This map is very skrunkly
- A lot of the large hallways have no firelocks which means they're very spaceable. Ideally you'd have more full-tiles around as some areas have a long line of edge firelocks.
- The chapel is very ugly.
- You shouldn't map material walls
- The solars in the middle won't work even if fixed because tiles block it.
- There's some weird stuff above the north airlock

I'm fine with it being merged if it's made admin only but it would need some work before making it an active highpop map.

**Comment by ChilbroBaggins** [comment]
Haha, not sure what skrunkly means, but, I can tell you there will be a lot of changes.  I've designed 2 other maps now for Nyano and I've learned a lot since making this one. 

I will take this feedback, along with previous feedback I received and what learned from the other maps and give this a really good overhaul. 

I really liked how the chapel looked🥺but I understand some people are quite averse to diagonal walls.

As for material walls, see the comment from Paul above. The PR for material walls was merged some time ago. So, it shouldn't be an issue now.

The weird stuff is just a render bug. I get it on every map. It;s the random stuff I mapped into lockers.

Otherwise, yeah, firelocks will be re-done along with the other changes. It will likely take me a week or two, depending on my irl work schedule. But I'll get started.

Thanks for reviewing.

**Comment by ps3moira** [comment]
bring back this map PLEASE.

**Pull request closed without merging**
