### PR TITLE
Courser Emergency Evacuation Shuttle

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR 
Introducing the Courser, the latest in rapid evacuation technology fresh out of the NT shipyards.  This expanded emergency evacuation shuttle features a service lounge for guests as well as a security checkpoint to safely secure hostiles en-route to Centcom.  For now, this evac shuttle will service Kettle, Marathon, Box, Pillar, and Bagel stations.
**Screenshots**

courser

**Changelog**

:cl: Checkraze
- add: Added the Courser class evacuation shuttle.

### CODE REVIEW

**Comment by Interrobang01** [comment]
Very nice! I'm exited for this. I should probably give my opinion past the excitement of a new shuttle, though.

The first thing that I notice is that this station is _extremely_ decked out. As more shuttles are added, we need to know if this gonna be the new standard or will this specific shuttle just have way more cool things on it?

Looking off the screenshot, I think the medical dispenser might be a bit too much. Having instant access to epinephrine will make saving people _extremely_ easy. I'm not sure if this is a bad thing, however.

I also see a security dispenser, the locker, and the unsecured flashers. This might also be a bad idea, I can see people breaking in there and causing mayhem. It's probably fine, though

I notice there are no fire lockers in the main area. Fire lockers aren't ever used anyways, so it's probably fine.

This shuttle has a name. Will the original get a name (or does it already have one and I just haven't noticed)?

My main issue is just that this shuttle is clearly far, far better than the original one. Will the original get an upgrade? Will future shuttles be on par with this one or the old one?

Either way, the shuttle isn't that large a component in the game balance.

That bar looks sick though

**Comment by mirrorcult** [comment]
this is a tad oversupplied, im not a fan of the sectech or medical dispenser. the layout is good though

**Comment by Cheackraze** [comment]
> The first thing that I notice is that this station is _extremely_ decked out. As more shuttles are added, we need to know if this gonna be the new standard or will this specific shuttle just have way more cool things on it?
Its a bigger shuttle designed for higher pop stations, and people have commented regularly how they like Nyano's shuttle because it has a bar, so I featured a bar. Stations can now specify custom shuttles easily and I would love to see more unique evac shuttle designs, I might even make a tiny evac shuttle next for the low pop stations like cluster and moose
> Looking off the screenshot, I think the medical dispenser might be a bit too much. Having instant access to epinephrine will make saving people _extremely_ easy. I'm not sure if this is a bad thing, however.
The original evac shuttle has a nanomed so I'm not sure how you think this is worse? 
> I also see a security dispenser, the locker, and the unsecured flashers. This might also be a bad idea, I can see people breaking in there and causing mayhem. It's probably fine, though
that's kind of the point. the locker is just an empty evidence locker, there are zip tie cuffs and 2 flashers and the sec tech vendor's inventory doesn't really have anything that dangerous.
> I notice there are no fire lockers in the main area. Fire lockers aren't ever used anyways, so it's probably fine.
Yea the center area is very vulnerable to bombing I admit
> This shuttle has a name. Will the original get a name (or does it already have one and I just haven't noticed)?
I only really named it because it needs a distinct name from the regular evac shuttle in the files. Ultimately the only people who even know it has a name are going to be people who read this PR and dive into the code. For instance, do you know what the nukie shuttle is named?
> My main issue is just that this shuttle is clearly far, far better than the original one. Will the original get an upgrade? Will future shuttles be on par with this one or the old one?
if there is interest in updating the existing shuttle I can do so and use the new tiles and decals, but as it is I think the existing evac shuttle is fine. Future shuttles well that will be up to the people who make them I suppose
> Either way, the shuttle isn't that large a component in the game balance.
Remember these exist for a grand total of 4 minutes every round

**Comment by Cheackraze** [comment]
> this is a tad oversupplied, im not a fan of the sectech or medical dispenser. the layout is good though

emisse told me to put in sec tech and like I said, the original evac has a med dispenser

**Comment by moonheart08** [comment]
> this is a tad oversupplied, im not a fan of the sectech or medical dispenser. the layout is good though

.

**Comment by Cheackraze** [comment]
Ok i removed the sec tech

**Pull request merged**
