### PR TITLE
Steel tile variantization fix

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Gives steel tiles back their tile variations that were accidentally removed in #21700. This just restores the sprite from the original tile resprite commit.

## Why / Balance
I did this as an experiment to see how variantization affected tiles, and then promptly forgot about it & accidentally committed it to the damaged tiles PR.
...That was almost an entire year ago. Oops!

It should probably go without saying that tile variations are good (I think?) If nothing else, whatever this accidental live experiment did has shown that it didn't really help much in my goal of making the game look & feel more like SS13.

## Media
I am not going to spend 15 minutes starting up my client to display something so minor that almost nobody but me and Emo noticed for an entire year. Sorry.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
no variantization no fun

### CODE REVIEW

**Comment by lzk228** [comment]
does variantization even work

**Comment by Flareguy** [comment]
> does variantization even work

Yes, otherwise damaged steel tiles would all look the same.

**Comment by slarticodefast** [comment]
>does variantization even work

I gave the PR a test and the tiles still look the same to me on the dev map
grafik

Does the randomization happen when mapping or when loading the map?

**Comment by UbaserB** [comment]
its a command

**Comment by slarticodefast** [comment]
Look like I just did it wrong. When placing tiles manually it works as well.
grafik

**Pull request merged**
