### PR TITLE
Add Secret Document

### PR DESCRIPTION
**Pull request by Minty642**
## About the PR

+ Adding NanoTrasen 'Secret' Document

## Why / Balance

+ Adding it as a new syndicate stealing objective, should be mapped inside a vault hidden inside a folder or locker (to prevent accidental burning)

## Technical details

- This item is basically the same weight as a paper, and purpose like a normal paper including can be burned, faxed, hidden in folder, stamped, and edited. with difference being different sprite

## Media

- [X] I have added screenshots to this PR showcasing its changes ingame

## Breaking changes

- Syndicate Agent received new task to steal NT 'secret' document located in station vault. (credits to rikeloldaboss for writing the secret document entry)
Space Station 14 9_28_2023 4_52_21 PM
Space Station 14 9_28_2023 4_48_59 PM
Space Station 14 9_28_2023 4_49_12 PM
Space Station 14 9_28_2023 4_50_33 PM
Space Station 14 9_28_2023 4_51_08 PM
Space Station 14 9_28_2023 4_51_59 PM

### CODE REVIEW

**Comment by deltanedas** [comment]
theres already hos secret documents

also being able to burn or recycle a functionally useless objective would definitely get metagamed

**Comment by BolloTea** [comment]
Maybe make a Blueprint for CE? Sorry for being off topic. I would also like to add that these papers would be useful for mapping.  Can they be made to have the functionality of a disk?  So that they would also give certain research points and they could be found in expeditions or in Gate (someday later)

**Comment by Kelvinlie642** [comment]
> theres already hos secret documents
> 
> also being able to burn or recycle a functionally useless objective would definitely get metagamed

- i meant to add something valuable and give syndicate a reason to raid the vault, and something high-value that syndicate can share it with other syndicate to complete the objective. for the paper burnt away issue, i can try make it immune to burning and give it some value for later repurpose in case if someone want to map it for salvage wreck and expedition.

**Comment by drteaspoon420** [comment]
Or, make burning the document also possible objective. That would solve the metagaming issue also increase the chance with syndicate conflict of interests (I always find that interesting)

**Comment by KingOnBudget** [comment]
> Or, make burning the document also possible objective. That would solve the metagaming issue also increase the chance with syndicate conflict of interests (I always find that interesting)

To be honest this! We already have alot of steal objectives and there are also hos document. I personaly belive instead having to destroy the document instead of stealing it will make it stand out more.

**Comment by IamVelcroboy** [comment]
Probably outside the scope of this PR but, if a camera were added, it could be neither steal/nor destroy but stealthily get a picture of the document and leave it where you found it.

**Comment by Kelvinlie642** [comment]
> Or, make burning the document also possible objective. That would solve the metagaming issue also increase the chance with syndicate conflict of interests (I always find that interesting)

alright, so in order to get this PR merged, i just need to add new objective for syndicate to destroy item by checking if the item no longer located in the station after round end for greentext?

**Comment by deltanedas** [comment]
> checking if the item no longer located in the station after round end for greentext?

that would essentially mean stealing it as if its on evac it wont be on the station

also it would have to be locked or something since just turning apc off or waiting for event, then crowbaring in and using a welder to burn it has no counter

**Comment by Minty642** [comment]
> > checking if the item no longer located in the station after round end for greentext?
> 
> that would essentially mean stealing it as if its on evac it wont be on the station
> 
> also it would have to be locked or something since just turning apc off or waiting for event, then crowbaring in and using a welder to burn it has no counter cool idea is turnkey/emergency shuttle early launch thing where 2 heads have to authorize opening a box with the secret documents, so kill 2 heads or trick them or emag it twice or something

the idea to create a safe to store a single paper might sounds a bit off topic, might be added on different PR. but i do understand your concern about how easy it is to just hack into vault to steal something, since the vault is not that secure in the first place. but we can discuss another solution for this PR to get merged.

**Comment by UbaserB** [comment]
> > > checking if the item no longer located in the station after round end for greentext?
> > 
> > 
> > that would essentially mean stealing it as if its on evac it wont be on the station
> > also it would have to be locked or something since just turning apc off or waiting for event, then crowbaring in and using a welder to burn it has no counter cool idea is turnkey/emergency shuttle early launch thing where 2 heads have to authorize opening a box with the secret documents, so kill 2 heads or trick them or emag it twice or something
> 
> the idea to create a safe to store a single paper might sounds a bit off topic, might be added on different PR. but i do understand your concern about how easy it is to just hack into vault to steal something, since the vault is not that secure in the first place. but we can discuss another solution for this PR to get merged.

the special safe should store the map’s gold/silver and golden toolbox, along with the documents

and the safe should have a special sprite to show it’s special

**Comment by RIKELOLDABOSS** [comment]
as the writer of the documents, PLEASE ADD THIS! this would be so cool!

**Pull request closed without merging**
