### PR TITLE
Libital reagent for improved brute healing

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

adds the libital reagent, heals 4 brute and deals 0.5 poison, with an overdose over 15u dealing 2 airloss and 3 poison
## Why / Balance

bicaridine is mass produce able but having an improved version that's harder to make and has a side effect is more interesting

maybe ill make epinephrine part of the recipe
nukies also need easier access to it, ill probably put it in the brute auto-injector
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: the reagent 'libital' has been discovered, with superior brute healing over bicaridine but with a small side effect of poison damage

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
this isn't even notably harder to make than bicar? All of the reagents are still regularly available in the chem dispenser.

**Comment by JoeHammad1844** [comment]
Lipozine is made with oil, but ill add epinephrine to the recipe

**Comment by CrigCrag** [comment]
wouldn't this heal 8 brute in practice, allowing you to heal 120 brute without overdosing and only dealing 15 poison

**Comment by JoeHammad1844** [comment]
well this is what a draft is for

**Comment by JoeHammad1844** [comment]
im putting this on pause for now

**Pull request closed without merging**
