### PR TITLE
Filtering reagents

### PR DESCRIPTION
**Pull request by Hebiman**
## About the PR

Adds a filter to the guide on Chemicals, Medicine and Botanicals

**Media**

Screenshot 2023-07-22 131340
Screenshot 2023-07-22 131356

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added filter for reagents

### CODE REVIEW

**Review by moonheart08 — APPROVED** [review]
shit i didnt quit being burned out soon enough

**Comment by moonheart08** [comment]
Well, okay

**Comment by moonheart08** [comment]
@Hebiman while this is Okay as is, it should probably be a bit smarter than it currently is. Namely:
Instead of textual search, search for elements that implement an ISearchable, and ask that element "do you fit this pattern". Only hide ISearchable elements, and also make guidebook document generation output a special richtext that's ISearchable.

**Comment by moonheart08** [comment]
```csharp
public interface ISearchable
{
    public bool CheckMatchesSearch(string query);
}
```

the chemical box UI element can then say it's a match if the query is approximately equal (i.e. ignoring capitalization) to the name of the chemical it represents, and in the future could also be made to query properties of the chemical like how much it heals/etc.

**Comment by Hebiman** [comment]
@moonheart08 I'll see what I can do with that. I'm rusty on the C# so mainly did what I found easiest.

From what I understand this would need to go on the GuideReagentEmbed. Going to get around that later.

I see that the RemoveLegsFallTest for some reason, so I need to fix that. Maybe I need to merge in the newest master for that one to fix itself since I don't think I touched anything near that.

**Comment by moonheart08** [comment]
> @moonheart08 I'll see what I can do with that. I'm rusty on the C# so mainly did what I found easiest.
> 
> From what I understand this would need to go on the GuideReagentEmbed. Going to get around that later.
> 
> I see that the RemoveLegsFallTest for some reason, so I need to fix that. Maybe I need to merge in the newest master for that one to fix itself since I don't think I touched anything near that.

It's a spurious fail. And correct, GuideReagentEmbed would implement it.

**Comment by Hebiman** [comment]
@moonheart08 Thanks for the suggestion, looks less jank now with the new interface.

Had to implement a new method for finding the ISearchable interface since the other methods were written to find Control classes and I fell that they should stay that way.

I don't know if the interface is in the right place as I didn't really see a pattern for where you store interfaces in the repo.

Any other suggestions are welcome.

**Comment by moonheart08** [comment]
One last thing @Hebiman, please use file scoped namespaces. We do not use namespace blocks.

**Pull request merged**
