### PR TITLE
Revert "Guidebook can POP OUT YAYYYY"

### LINKED ISSUE #20518: Guidebook doesn't scale correctly ingame
## Description

Before today (or atleast before the pop-out feature was introduced), expanding the guidebook window would also scale the right-tab and its contents correctly. This no longer seems to happen. This occurs both in-game and on the menu screen.

(Also, the left- and right-hand cursor icons for scaling does not seem to work)

**Reproduction**

1. Open guidebook
2. Scale it using the edges
3. Done

**Screenshots**

image
image
image

**Additional context**

### LINKED ISSUE #20519: Popping out the guidebook seems to not work
## Description

Using the pop-out feature results in a blank window, which only seems to update if the game is loaded (this is a fullscreen bug)
Scaling also seems to be broken, scaling the window results in the image being stretched.

**Reproduction**

1. Run the game in fullscreen
2. Pop-out the guidebook window
3. Done

**Screenshots**

image
image

**Additional context**

This bug mostly seems to occur because the game stops rendering if it's not focused.

### PR DESCRIPTION
**Pull request by mirrorcult**
Reverts space-wizards/space-station-14#20268

this doesn't work with steam overlay which we've known forever and which a ton of players are going to be using so i dont know why this was merged

also causing a lot of other issues, closes #20518 closes #20519

### CODE REVIEW

**Comment by mirrorcult** [comment]
@VasilisThePikachu

**Comment by mirrorcult** [comment]
also https://discord.com/channels/310555209753690112/1155529716636340244

**Review by metalgearsloth — APPROVED** [review]

**Comment by NancokPS2** [comment]
Wasn't the consensus that it didn't matter if it worked with Steam? Can't it just be disabled for Steam users?  
Seems dumb to remove a great QoL feature because a third party app doesn't work with it.  
You don't need steam to run the game at all. Only to download it.

**Comment by VasilisThePikachu** [comment]
> Wasn't the consensus that it didn't matter if it worked with Steam? Can't it just be disabled for Steam users? Seems dumb to remove a great QoL feature because a third party app doesn't work with it. You don't even need steam to run the game at all. Only to download it.
> 
> This is like disabling a feature because it breaks discord overlay.

It's not only this. Trying to do it in Fullscreen seemed to have issues... which most people do. And I was not gonna suggest "lol play on windowed" as a suggestion. Borderless window could have fixed this since it's what I was testing with but we are waiting for a refactor of Clyde (handles windows and stuff) and not want to touch adding features to it.

**Comment by NancokPS2** [comment]
Oh, so it had other issues too, my bad.

**Comment by mirrorcult** [comment]
this is fine to bring back with steam overlay disabled, probably after webgpu port so the windowing issues can be properly fixed

**Comment by mirrorcult** [comment]
*fine to bring back with steam overlay disabled if the other problems are fixed, i mean

**Comment by deltanedas** [comment]
clyde using wgpu real?

**Comment by VasilisThePikachu** [comment]
> clyde using wgpu real?

been under a rock?

**Comment by deltanedas** [comment]
yes.

**Comment by mirrorcult** [comment]
> clyde using wgpu real?

yes pjb is in the process of moving from opengl to webgpu

**Comment by DummeHytteOst** [comment]
when this does comeback, i would suggest adding a toggle to turn on steam overlay and disable the pop out, people were using steam overlay to have the wiki open for things like space law, operating procedues etc. 

and not to mention that a lot of people can't even make great use of the popout feature, since most people don't have multiple monitors, thus requiring them to tab out of the game to even use it, which could cause several issues and would just not feel great, compared to the easy use of steam overlay, which you can turn on/off quickly, while still seeing the game in the background

**Comment by VasilisThePikachu** [comment]
> when this does comeback, i would suggest adding a toggle to turn on steam overlay and disable the pop out, people were using steam overlay to have the wiki open for things like space law, operating procedues etc.
> 
> and not to mention that a lot of people can't even make great use of the popout feature, since most people don't have multiple monitors, thus requiring them to tab out of the game to even use it, which could cause several issues and would just not feel great, compared to the easy use of steam overlay, which you can turn on/off quickly, while still seeing the game in the background

The only reason we had to disable steam overlay for popout windows is cause opengl (I think I forgot that we use) has issues with steam or something like that and caused this. Hopefully with webgpu we would not need to even disable the steam overlay

also the popout button was completely optional, no need to press pop out if you don't wanna pop it out and keep it in game. This did not make the window pop out on its own

**Comment by DummeHytteOst** [comment]
> also the popout button was completely optional, no need to press pop out if you don't wanna pop it out and keep it in game. This did not make the window pop out on its own you had to press pop out first.

while the pop out was optional, the steam overlay being disabled was not, which was my main issue and why i suggested a toggle option, so people could choose what they prefered the most. 

i do hope that the webgpu will allow people to use both options.

**Comment by VasilisThePikachu** [comment]
> > also the popout button was completely optional, no need to press pop out if you don't wanna pop it out and keep it in game. This did not make the window pop out on its own you had to press pop out first.
> 
> while the pop out was optional, the steam overlay being disabled was not, which was my main issue and why i suggested a toggle option, so people could choose what they prefered the most.
> 
> i do hope that the webgpu will allow people to use both options.

yeah the problem was that... i had no choice really, and I really thought no one used the steam overlay and many others also thought the same thing

**Pull request merged**
