### PR TITLE
[Sprite + SG] Centcom update 

### PR DESCRIPTION
**Pull request by PuroSlavKing**
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by ficcialfaint** [comment]
`meta.json` has to be updated

**Comment by PuroSlavKing** [comment]
> `meta.json` has to be updated

I made these sprites

**Comment by AJCM-git** [comment]
I think the lime color is intentional since making them a darker green makes them look like botany items, so keep the old color

**Comment by PuroSlavKing** [comment]
> I think the lime color is intentional since making them a darker green makes them look like botany items, so keep the old color

the lime color was chosen because I decided so, in fact, it looks shabby in the game. The handle is still tolerable, but the PDA is too bright, because of this it is out of style.

**Pull request merged**
