### PR TITLE
Add collision for beds

### PR DESCRIPTION
**Pull request by Ady4ik**
## About the PR
In this PR we add collision for beds and remove AnchorableComponent from beds. 

## Why / Balance
We remove AnchorableComponent for beds because it is cause of bugs when u want to pull it. We add collision for beds because it remove possibility to anchore many beds and chemdispensers in one tile. We chose this way to fix it because in our opinion we need to add collision to beds because it unrealistic to go right through.
Removing possibility to unanchor the bed isn't the worst because u can disassemble bed and place in other place if u want it. 

## Technical details
We added check if entity has component Climbable and if it have it we remove collision to entity and give player go through it. We added ClimbableComponent to beds to interact with this check. 
We replaced TabletopMachineLayer to MachineLayer and Mask accordingly to chemdispancer because it isnt logic when this big machine is tabletop (it isnt)

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Ady4
- add: Added collision to beds.
- remove: Remove possibility to unanchor beds.
- fix: Fixed possibility to stack beds and chemdispensers in one tile.

### CODE REVIEW

**Comment by lzk228** [comment]
can mobs go through beds?

leave unchorable as it was, instead of removing things just fix them or make an issue about them

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
1. You shouldn't be leaving a dummy anchorable flag on the bed.
2. There's no reason to not have beds not be anchorable.
3. You shouldn't be forcibly climbing on unbuckle, that's what events are for.
4. You're modifying the chem dispenser when you shouldn't be.

**Comment by IProduceWidgets** [comment]
> There is no reason be anchorable. Also u can just disassemble bed and place whatever you want.

Consistency, almost all structures are Anchorable.

**Comment by metalgearsloth** [comment]
> > You shouldn't be leaving a dummy anchorable flag on the bed.
> 
> Why its dummy? It works fine

Because leaving dummy components on entities is a source of bugs and a waste of performance.

> > There's no reason to not have beds not be anchorable.
> 
> There is no reason be anchorable. Also u can just disassemble bed and place whatever you want.

Disassembling a bed instead of unanchoring it just because is inconvenient.

> > You shouldn't be forcibly climbing on unbuckle, that's what events are for.

> Why if it is broken? The sprite is bigger than soda dispenser and u say it is same?

Because this PR is about beds not the chem dispenser.

**Comment by Ady4ik** [comment]
well we test it in our server and it was cause of many bugs and dont need to be added in all servers.

**Pull request closed without merging**
