### PR TITLE
Blind Event Tone Down

### PR DESCRIPTION
**Pull request by Nairodian**
## About the PR
Blindly tones down and adjusts the event chances _slightly_ from #19803, alongside anything else I felt was out of place.

**Dragon**
Weight: 5 -> 4.5

**Ninja**
Minimum Players: 15 -> 20
Weight: 10 -> 4

**GasLeak**
Weight: 5 -> 6.5

**MeteorSwarm**
Weight: 7.5 -> 6.5

**MouseMigration (The RatKing one)**
Minimum Players: 35 -> 20

**ZombieOutbreak**
Minimum Players: 0 -> 20
Weight: 5 -> 4

**LoneOpsSpawn**
Minimum Players: 10 -> 20
Weight: 5 -> 4

## Why / Balance
_(Entirely filled with confirmation bias as this is just what I observed playing sec rounds on 15-40 pop Salamander. I've got no idea how LRP handles these.)_

Recently security felt like running around from station threat to station threat without a moment's break and no time to actually look into the Syndicate actions. There was a round I remember specially with back to back to back; slimes, dragon, spiders, an hour into the round, with an active Syndicate running around but we literally didn't have TIME to chase them.

As well as it feels like 50% of Salamander rounds end in zombies on top of Syndicates.

## Media
- [X] This PR does not require an ingame showcase

### CODE REVIEW

**Comment by Flareguy** [comment]
I haven't actually played the game recently so I can't really speak on any of these, but tuning down meteors seems dubious. Explosives are currently in a really bad state and engineering rarely has anything to do, so they probably warrant being something that is at least semi-frequent.

**Comment by Nairodian** [comment]
I turned gas leaks up to make up for it, I do like meteors and they don't pose _major_ threats to the station. But dear fuck they always hit evac and usually render it unusable. Willing to turn it back up if that's wanted.

**Comment by deltanedas** [comment]
turning gas leak up is good also glad to hear tweaking dragon made it appear, i havent seen a natural dragon station event in ages

**Comment by Flareguy** [comment]
> I turned gas leaks up to make up for it, I do like meteors and they don't pose _major_ threats to the station. But dear fuck they always hit evac and usually render it unusable. Willing to turn it back up if that's wanted.

That seems fine, people rarely use pods (I would be willing to bet that you may have even forgotten they existed when writing this) & there are plenty of emergency spacesuits to go around. It also usually serves as an important location for engineering to repair & as potentially deadly chokepoint someone might have to scheme up a plan to go through (survival gameplay good.)

**Comment by LankLTE** [comment]
Honestly it’s a 1 weight difference, I’d prefer to see gas leak events more often instead as they give atmos something to do. Meteor events feel like they’re fucking over cargo, evac, or arrivals a majority of the time

**Comment by Nairodian** [comment]
Errrr- fuck, I've got no idea how to handle files being changed.

**Comment by LankLTE** [comment]
> I remember specially with back to back to back; slimes, dragon, spiders, an hour into the round

pretty sure I was there for this round and lucky had given the station RampingStationEvents (or whatever it’s called that effectively enabled survival) so it wasn’t like this just naturally happened, in my experience it’s been (mostly) alright since then. That said I’m fine with it since you’re only really changing them by 1 or so, but:

Ninjas are still new and people wanna play with them. Especially since their abilities are broken I feel it should stay common until the abilities been working for a day or two: that way people get to play them before they become way less common & people get to learn how to play against them / give feedback on balance

**Comment by UbaserB** [comment]
I feel like ZombieOutbreak and LoneOpsSpawn shouldn’t be less common since i feel like they’re pretty sparse as they are. Everything else feels fine imo.

**Comment by EmoGarbage404** [comment]
What do these weight changes even do? Im apprehensive about blindly merging something you self-admit to being unsure about what it does. Does changing the weight by 1 even have a noticeable effect?

**Comment by Nairodian** [comment]
> pretty sure I was there for this round and lucky had given the station RampingStationEvents (or whatever it’s called that effectively enabled survival) so it wasn’t like this just naturally happened, in my experience it’s been (mostly) alright since then. That said I’m fine with it since you’re only really changing them by 1 or so, but:

No this was a different shift, the one I'm referencing was entirely free of admin intervention. It's a slight change in hopes to ever so lightly tone them down.

> Ninjas are still new and people wanna play with them. Especially since their abilities are broken I feel it should stay (somewhat) common until the abilities been working for a day or two: that way people get to play them before they become way less common & people get to learn how to play against them / give feedback on balance Not saying it can’t be nerfed rn but making it less than half of what it was before is a bit much

I understand that and it's fine by me. I don't mind this PR waiting to be merged until the balance gets worked out. The more than half reduction would make sense then, putting it in line with lone ops and zombies, which are all mid round shift enders.

**Comment by Nairodian** [comment]
> I feel like ZombieOutbreak and LoneOpsSpawn shouldn’t be less common since i feel like they’re pretty sparse as they are. Everything else feels fine imo.

They're pretty common in my experience, but yet again, 15-40 player MRP rounds. Both are shift enders which tended to show up a lot after shifts got to 2+ hours, which in my mind is why you'd have a shift ending event, for rounds that go past the usual hour and a half.

**Comment by Nairodian** [comment]
> What do these weight changes even do? Im apprehensive about blindly merging something you self-admit to being unsure about what it does. Does changing the weight by 1 even have a noticeable effect?

Entirely fair, and I don't know. The original PR that upped them didn't know either, but I felt they were slightly overtuned, which is once again entirely my own personal opinion. At the end of the day, I don't actually know, just knew that if someone didn't make a PR for it it'd probably stick like this for a good while.

**Comment by asperger-sind** [comment]
I play on LRP exclusively and have always been of the opinion that there are too few events, I haven't seen half of these in decades.

**Comment by deltanedas** [comment]
> I play on LRP exclusively and have always been of the opinion that there are too few events, I haven't seen half of these in decades.

yeah before the blind overtune i cant say ive seen a non admeme/exped dragon once

**Comment by deltanedas** [comment]
since events for lrp and mrp are so different (rarely happens vs constant round ending) might be worth to support server specific event weights/players/times

**Pull request closed without merging**
