### PR TITLE
Construction PR™ - (Making stuff constructible IC)

### PR DESCRIPTION
**Pull request by Git-Nivrak**
- Floors
  - [x] Lattice
  - [x] Catwalk
  - [x] Underplating
  - [x] Plating
  - [x] ~~Various Floor Tiles~~(Done in another PR)
- Walls
  - [x] ~~Normal Wall~~ (Done in another PR)
  - [x] ~~Reinforced Wall~~ (Done in another PR)
  - [ ] Fake Walls
- Wall Mounts
  - [ ] APC
  - [ ] Air Alarm
  - [ ] Fire Alarm
  - [ ] Security Camera
  - [ ] Light Fixture
  - [ ] Requests Console (?)
  - [ ] Newscaster (?)
  - [ ] Bounty Board (?)
- Other
  - [ ] Grille
  - [ ] Barricade
  - [ ] Windoor
  - [ ] Button
  - [x] Firelock
  - [ ] Reflector
  - [ ] Airlock
  - [ ] Turret
  - [ ] ~~AI Core~~
  - [ ] Solar Panels + Solar Trackers
  - [ ] Disposal related Machinery
  - [x] ~~Computers~~(Done in another PR)
  - [ ] Modular Consoles (?)
  - [ ] ~~Machines~~ (Zumo please)
  - [ ] ~~Robots, Cyborgs and Mechs~~
  - [ ] Mineral Door
  - [ ] Conveyor Belt
  - [ ] Railings
  - [ ] Sink
  - [ ] Shower
- Furniture
  - [ ] Chairs
  - [x] Tables
  - [ ] Closet
  - [ ] Rack
  - [ ] Beds
  - [ ] Bookcase
  - [ ] Drying Rack
  - [ ] ~~Display Case~~

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Update the title of this PR to give it more context. 

Do not include AI Core, Robots, cyborgs or mechs in this PR.

Start with stuff that's already in the game. This is going to be a big PR already with making construction steps for every constructible entity, so don't include stuff that isn't even ingame yet like the display case, turret, reflector etc.

**Comment by Zumorica** [comment]
Agreed. Good PR, but both the description and title need updating to be more accurate.
For example, normal/reinforced wall and computer constructions were already in the game, so adding it to the description here is completely pointless. And as Swept said, you shouldn't include those advanced constructions here either. Those should go in their own individual PRs, if you actually decide to work on them.

(Also, just a nitpick but I personally prefer reviewing & merging a bunch of small, concise PRs than a single big one :P)

**Comment by Git-Nivrak** [comment]
Noted, Just wanted to have everything in one place

**Comment by Zumorica** [comment]
That's what the [roadmap](https://hackmd.io/@ss14/roadmap) is for! :P
Having that list of constructions in the roadmap will very useful

**Comment by SweptWasTaken** [comment]
> Agreed. Good PR, but both the description and title need updating to be more accurate.
> For example, normal/reinforced wall and computer constructions were already in the game, so adding it to the description here is completely pointless. And as Swept said, you shouldn't include those advanced constructions here either. Those should go in their own individual PRs, if you actually decide to work on them.
> 
> (Also, just a nitpick but I personally prefer reviewing & merging a bunch of small, concise PRs than a single big one :P)

Thinkin' bout reviewers

This list might be a good issue though, like a unified construction recipe checklist to go down.

**Comment by Git-Nivrak** [comment]
Will move the list to the roadmap and make the updates in smaller PRs

**Pull request closed without merging**
