### PR TITLE
Secure three substations on saltern

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

Substations on the saltern map are now all behind engineeringlocked doors.

## Why / Balance

Saltern was made before this was a mapping convention.

## Technical details

n/a

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Southwest substation (new vs old): Note that some disposal tubes and wiring were moved around here in order to lead those through doors and under catwalks instead of through walls.
image
image

Chapel substation (new vs old):
image
image

Southeast solars substation (new vs old):
image
image

## Breaking changes

n/a

**Changelog**

n/a, see comments below

### CODE REVIEW

**Comment by juliangiebel** [comment]
Please read our guidelines on change logs an fix your CL
https://docs.spacestation14.io/en/getting-started/pr-guideline#changelog

**Comment by Emisse** [comment]
idk if this needs a changelog, i typically dont do mapping changelogs unless its a large change

**Comment by TsjipTsjip** [comment]
Changelog removed as per above, sorry for the bother!

**Comment by deltanedas** [comment]
pro substations in maints submissive and unanchorable

**Comment by Emisse** [comment]
im gonna ban you off github so you have to use discord

**Comment by deltanedas** [comment]
i will ban you from xbox my dad owns michaelsoft :trollface:

**Pull request merged**
