### PR TITLE
Add skirt of life in contraband medidrobe

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

title

## Why / Balance

drip or drown

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

no cl no fun

**Changelog**

### CODE REVIEW

**Comment by Iamgoofball** [comment]
You need to add a changelog to your pull request or it's going to get denied. This PR description has zero effort.

**Comment by ArtisticRoomba** [comment]
Does he know?

**Comment by KingFroozy** [comment]
I'm doing a resprite for this rn, and I considered it being a reward for paramedic mains, since it's name pretty much gives off "I'm saving lives" vibe. Also the guy above is right, and I don't like it being in hacked medidrobe.

**Comment by ArtisticRoomba** [comment]
Any other ideas to make it obtainable in-game? Right now it's only mapped as gamerloot.

**Comment by Cojoke-dot** [comment]
> Any other ideas to make it obtainable in-game? Right now it's only mapped as gamerloot. 

It's gamerloot and lotto boxes, it's meant to be a fun item that you can find occasionally, like the maid outfit. It seems like a fun place to put it without making everyone have one(everyone is not meant to be be able to have one)

**Comment by TheShuEd** [comment]
> You need to add a changelog to your pull request or it's going to get denied. This PR description has zero effort. You don't even include a justification for the clothing item you're adding to the vendor, or why it's in the contraband section. Why should this require hacking to get? Why do doctors need it in the first place?
> 
> chrome_uDUoDai1Ib
> 
> You didn't even check the requirement boxes or fill out half the fields. C'mon.

Thats funny, because lzk has ~400 PRs to Wizden

**Comment by Iamgoofball** [comment]
>Thats funny, because lzk has ~400 PRs to Wizden

I have thousands of pull requests to /tg/station. Your point?

**Comment by TheShuEd** [comment]
> I have thousands of pull requests to /tg/station. Your point?

You're cool, but I just said it was funny.

**Comment by slarticodefast** [comment]
Should be ok to obtain it this way.

**Pull request merged**
