### PR TITLE
Fix honkbot slipping

### PR DESCRIPTION
**Pull request by Macoron**
## About the PR 
Just copied that from soap prototype

### CODE REVIEW

**Comment by moonheart08** [comment]
This breaks the AI.

**Review by mirrorcult — APPROVED** [review]

**Comment by mirrorcult** [comment]
these dont have AI

**Comment by metalgearsloth** [comment]
> these dont have AI

Players really shouldn't have dynamic physics bodies.

**Comment by Elijahrane** [comment]
> these dont have AI

they had wandering AI when I wrote them, did that break at some point?

**Pull request merged**
