### PR TITLE
Jetpacks on grid without gravity

### PR DESCRIPTION
**Pull request by notquitehadouken**
## About the PR

Allows you to fly with jetpacks on grids that have gravity disabled.
They still turn off when gravity turns back on.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Jetpacks can now work on grids without gravity.

### CODE REVIEW

**Comment by notquitehadouken** [comment]
reasons:
the text that shows up when you try to use a jetpack on any grid is "Can't use jetpacks under gravity"
makes jetpacks useful in gravityless environments that aren't space
makes turning off grav not immediately screw everyone without magboots over
drag racing with jetpacks

**Comment by deltanedas** [comment]
reason 3 is invalid since more people have magboots than jetpacks, plus they can be printed by sci

**Comment by mirrorcult** [comment]
this was an intentional choice by @metalgearsloth, although i dont remember the reasoning and this makes way more sense to me as to how it should work

**Comment by notquitehadouken** [comment]
> this was an intentional choice by @metalgearsloth, although i dont remember the reasoning and this makes way more sense to me as to how it should work

i wasn't thinking about it when i made the pr but i don't think this accounts for magboots

**Comment by notquitehadouken** [comment]
will close and make it disable when magboot

**Comment by notquitehadouken** [comment]
nevermind about that, it gets a fatal error when you turn off the jetpack

**Pull request closed without merging**
