### PR TITLE
Removes chem. and react. from every prototype ID

### PR DESCRIPTION
**Pull request by Zumorica**
Because this went against our naming guidelines.

### CODE REVIEW

**Comment by ike709** [comment]
I feel like if anything the naming guidelines should be amended to allow if not encourage this, rather than removing it. Providing a grouping prefix makes it very clear what the prototype is without going to the definition. Barring a YAML editor that would ideally provide this information, this is a useful and informative naming scheme.

**Comment by Zumorica** [comment]
Disagree, the prefix is completely and absolutely redundant in 99 % of cases (check the changes in this PR and you'll see what I mean)

**Comment by Peptide90** [comment]
> I feel like if anything the naming guidelines should be amended to allow if not encourage this, rather than removing it. Providing a grouping prefix makes it very clear what the prototype is without going to the definition. Barring a YAML editor that would ideally provide this information, this is a useful and informative naming scheme.

I am also of this mind so you can differentiate 3 things with the same name depending on if it's a crate, fill, object or cargo console ID for example. But if we want rid of em all I'll do the cargo console this weekend 😅

**Comment by mirrorcult** [comment]
if you want these prefixes added then at the very least it should be "ChemWater" "ChemHg" instead of "chem.Water"

**Comment by SweptWasTaken** [comment]
> 
> 
> if you want these prefixes added then at the very least it should be "ChemWater" "ChemHg" instead of "chem.Water"

This is a good take do this.

Source: I do lot of yaml

**Comment by Zumorica** [comment]
> "ChemWater" "ChemHg"

absolutely disgusting imo

**Review by PaulRitter — APPROVED** [review]
i am paul and i approve this message

**Comment by mirrorcult** [comment]
conflicts

**Pull request merged**
