### PR TITLE
Remove whitelists from belts

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

- Remove whitelists from all belts
- Since only webbing feature was absence of whitelists, i decided to make webbing storage little wider

## Why / Balance

Screenshot_20240409_121219

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Belts no longer have a whitelists.
- tweak: Webbing storage increased from 8x2 to 9x2.

### CODE REVIEW

**Comment by K-Dynamic** [comment]
I feel webbing is okay with 8x2 storage, belts were just bought up to that standard

Buffed webbing (even just two tiles) means sec will continue grabbing it roundstart as opposed to using their belts

**Comment by deltanedas** [comment]
they already do that right now because no whitelist
and salvage has webbing too that they can find

**Comment by Hanzdegloker** [comment]
Taking this route, maybe add some generic pouch sprites to all belts to just signify "hey something is on the belt" like how crowbars appear on utility belts or batons on security belts.

**Comment by IProduceWidgets** [comment]
My only 2c to this is belts look better, and I think we should encourage their use for sec because of this.

**Comment by Tayrtahn** [comment]
> Taking this route, maybe add some generic pouch sprites to all belts to just signify "hey something is on the belt" like how crowbars appear on utility belts or batons on security belts. 

I think the sprites for specific items on belts would still work, but it would definitely be nice to have something like a pouch visible for items that don't have a specific sprite.

**Comment by keronshb** [comment]
I'd still like to keep this functionality for the future. In case we decide to just keep tools in toolbelts, sec items in sec belts, etc.

**Comment by Tayrtahn** [comment]
I like having items restricted to specific belts. 

If the concern is having to maintain big whitelists for each belt, then the solution might be to flip things around and add a tag for items that fit on each belt (like "FitsOnMedicalBelt"). Shift the responsibility to the items.

**Comment by LankLTE** [comment]
> I like having items restricted to specific belts.

yeah same here, having belts just be extra storage for everything feels odd

**Comment by superjj18** [comment]
separate tool belt from 2x8 to 4 2x2s to prevent large items like shotguns from fitting in a toolbelt.

**Comment by EmoGarbage404** [comment]
> separate tool belt from 2x8 to 4 2x2s to prevent large items like shotguns from fitting in a toolbelt.

you already can't put large items in a belt.

**Comment by Cojoke-dot** [comment]
Hm… I don’t this this is that bad… it could be more annoying for sec to deal with every kind of belt but also it would be nice to not have to get a webvest every week. I would like to point out that this is a buff to the ce’s belt, as its so massive and can now fit enough meds/ammo/weapons/cuffs to supply an army.

**Comment by lzk228** [comment]
ok i dont like it either

**Pull request closed without merging**
