### PR TITLE
Plasma cutter(reworked and updated)

### PR DESCRIPTION
**Pull request by Abobadadada**
New instrument, a plasma cutter.

A plasma cutter is needed for the deconstruction of walls, windows and other structures FAST, according to the idea, only atmospheric technicians and CE should have it. Also, there is a version of the syndicate, which is in the uplink, at a price of 8 TK (cells with plasma, 2 TK each), and that's it.

### CODE REVIEW

**Comment by ike709** [comment]
> A plasma cutter is needed for the deconstruction of walls, windows and other structures FAST,

So you reinvented RCDs?

**Comment by Emisse** [comment]
i kinda like the idea but maybe RCD should be buffed a bit to compensate and limited more

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Same review as last time, do not copy-paste entire components and systems like this, and please don't duplicate prs.

**Comment by mirrorcult** [comment]
there are tons of empty files here, and this is basically just a direct copy paste of the RCD. what is the purpose of this beyond just being an RCD?

**Review by AJCM-git — CHANGES_REQUESTED** [review]
what mirrorcult said

**Comment by metalgearsloth** [comment]
Your branch needs fixing as you're pring from master and the code needs a lot of cleanup.

**Pull request closed without merging**
