### PR TITLE
bloodred RCD sprites

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

i drew a fcked up evil version of the RCD to show you how twisted my mind is and it would just turn any normal person insane heh

just adds sprites for a syndicate RCD

could be a TC purchase in the future or nukies would have to decide between this and the fireaxe with some kind of beacon
## Media
image

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
nah

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
fuck i accidentally deleted the icon definition

**Comment by dvir001** [comment]
The fuck is that pull notes?
image

**Comment by JoeHammad1844** [comment]
something wrong?

**Comment by dvir001** [comment]
> something wrong?

🤨

**Comment by JoeHammad1844** [comment]
> 🤨

thats what im sayin

**Comment by dvir001** [comment]
> > 🤨
> 
> thats what im sayin

https://en.wikipedia.org/wiki/Tomorrow%27s_Pioneers

"
farfour you piece of shit YOU BETRAYED PALESTINE", 
why do you need to make your code comments political.

**Comment by JoeHammad1844** [comment]
its not serious, man

**Comment by JoeHammad1844** [comment]
this is completely off topic

**Comment by Emisse** [comment]
no

**Comment by retequizzle** [comment]
Hi Joe,

You were unbanned from Github recently with the assumption that you would be on good behavior, both in relation to PRs with powercreep as well as general content submitted. Based on this PR (RCD for nukies/traitors would indeed be powercreep), along with some of the commentary made in your commit notes, to say that we are concerned again would be an understatement. Considering the amount of warnings given prior [here](https://github.com/space-wizards/space-station-14/pull/21301#issuecomment-1783746958), the repository ban has been reinstated.

Thanks.

**Pull request closed without merging**
