### PR TITLE
Fixes some high speed item issues

### LINKED ISSUE #7907: Slipping while holding an item in your hand can make that item fly at Mach 2
## Description

If you're holding an item and you slip, that item may be thrown out of your hand at incredible speed. Sometimes you are also thrown unexpectedly fast.

**Screenshots**

https://user-images.githubusercontent.com/45957058/166415801-f8c2a8a2-4e97-4a13-898c-5ced07d74c6f.mp4

**Additional context**

### LINKED ISSUE #7936: DamageOnHighSpeedImpact is a bit extra
I was playing a round and got put into crit in a single hit and died which is just a *little* bit much.

### LINKED ISSUE #8262: Banana cannon
## Description
throw a slippery item at the wall infront of you and be amazed

https://user-images.githubusercontent.com/31836813/169003484-b71899d0-3b6c-43ae-9a1f-02e0a8d59569.mp4

### PR DESCRIPTION
**Pull request by keronshb**
## About the PR 

fixes #8262
fixes #7907 
fixes #7936 
(also I'm not sure if it fixes the third one but just in case)

The basic here is that anything that wasn't a puddle was at 6F velocity or higher, which means items flung out of your hands at mach speed. The only things that weren't 6F were lube and puddles. Hilariously the clown PDA was at 9F.

So to fix this I've just balanced it so the velocities are at 2F or below for most everything except:

Space Lube - I know lube is usually considered the funny slip item so I buffed it to 5F
Traitor Soap - I was 50/50 about lowering this from 9F to match with the other regular soaps, but I'll let the maintainer(s) decide that.
Omega Soap - I wasn't sure if this was admin spawn only so I left it alone.

I also lowered the damage factor by half for DamageOnHighSpeedImpact so maybe nothing super funny should happen anymore with that? At least with testing out slipped items at high speed it was less destructive too.

**Screenshots**

**Changelog**

:cl:
- tweak: Balanced slipping speed so items don't go mach 5.

### CODE REVIEW

**Comment by ike709** [comment]
You need "fixes [issue]" before every single one for github to autoclose them all when this is merged.

**Comment by keronshb** [comment]
> You need "fixes [issue]" before every single one for github to autoclose them all when this is merged.

Like that?

**Comment by EmoGarbage404** [comment]
I believe so. You also should change the changelog part from "add" to "fix" or "tweak". I would personally go with tweak.

**Comment by keronshb** [comment]
> I believe so. You also should change the changelog part from "add" to "fix" or "tweak". I would personally go with tweak.

Cool, changed that too.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
