### PR TITLE
Make explosions take resistances into account

### PR DESCRIPTION
**Pull request by DrSmugleaf**
Fixes https://github.com/space-wizards/space-station-14/issues/20809

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Armor will now protect you against explosions.

### CODE REVIEW

**Comment by Slava0135** [comment]
this is not how it should be fixed, explosion resistance is separate from armor resistances, see `GetExplosionResistanceEvent`

**Comment by Slava0135** [comment]
maybe was introduced in #20274

**Comment by Slava0135** [comment]
it seems like in
```csharp
var ev = new InventoryRelayedEvent<T>(args);
```
`args` struct is copied and all modifications to fields are ignored basically = no coefficient change

image

**Comment by ElectroJr** [comment]
Seems like the thing slava pointed out is the actual issue. Explosions should still ignore normal resistances unless the explosion area calculation is also updated to take them into account.

IIRC I didn't do that initially because its a PITA to figure out how much damage an object needs to take in order to break, using a simple multiplier makes it much easier.

**Pull request closed without merging**
