### PR TITLE
Convert all textures to RGBA (attempt 2)

### LINKED ISSUE #9955: Some textures are in RGB color and some are in Indexed color
## Description

end my fucking suffering.
convert to rgb.
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Winkarst-cpu**
## About the PR
Converted all textures to RGBA.

## Why / Balance
Resolves #9955.

## Technical details
Instead of changing 3525 files by hand, I just created a python script :trollface: 

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

None.

### CODE REVIEW

**Comment by Winkarst-cpu** [comment]
Failed check because PR is too huge :trollface:

**Comment by PJB3005** [comment]
I still don't see the point of this. This just makes all these files bigger for no gain?

**Comment by EmoGarbage404** [comment]
This really isn't necessary and is just going to cause a million conflicts for downstreams for literally 0 benefit. The original issue is just me malding 2 years ago and definitely isn't something we need to act on.

**Comment by Winkarst-cpu** [comment]
> This really isn't necessary and is just going to cause a million conflicts for downstreams for literally 0 benefit. The original issue is just me malding 2 years ago and definitely isn't something we need to act on.

Maintainer joke? :trollface:

**Pull request closed without merging**
