### PR TITLE
Add station/space coords toggle to handheld GPS

### LINKED ISSUE #13468: GPS Coordinates and Crew Monitor Coordinates don’t match
## Description

Noticed this a few days ago while playing medic, GPS coords appear to randomly drift over time while Crew Monitor Coords stay the same. I’m not sure if the coords sent when the nuke is armed are GPS or Crew Monitor coords, but if they’re using the Crew coords this makes it effectively impossible to use those coords to find the nuke.

**Reproduction**

1. Go into test server, spawn Urist with maxed suit sensors
2. Use crew monitor to see Urist’s coordinates
3. Stand next to Urist and look at the coordinates in GPS
4. Wait 10 minutes, observe how the GPS coords are randomly drifting while the crew monitor coords are not

### PR DESCRIPTION
**Pull request by pissdemon**
## About the PR
Fixes #13468.

## Why / Balance
The coordinates in the crew monitor weren't really useable before this change. Now they are.

## Technical details
It's mostly self explanatory.

## Media
image
image

## Breaking changes
None.

**Changelog**
:cl:
- add: The handheld GPS can now toggle between space coordinates and station (crew monitor) coordinates.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
is it really the best solution to just have GPSs display both? The different between the two is extremely finnicky and code-based. The fact that there even is a distinction between the two is probably lost on the average player. I think it makes a lot more sense to just use one across the board over the other, or even doing some kind of unified IC system that's station relative or something.

**Comment by LordEclipse** [comment]
> is it really the best solution to just have GPSs display both? The different between the two is extremely finnicky and code-based. The fact that there even is a distinction between the two is probably lost on the average player. I think it makes a lot more sense to just use one across the board over the other, or even doing some kind of unified IC system that's station relative or something.

Okay, imagine for a moment that the station is hurtling through space itself. If map and grid coordinates were the same, the coordinates on the grid itself would also be ever-changing, not very desirable outcome IMO.

**Comment by FungiFellow** [comment]
What happened to the station anchor PR? Tue one that kept station still?

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Just make it toggle to either grid relative or map relative, with map relative being the fallback as it's never going to be useful unless you're on the map yourself because the rotation will screw your frame of reference.

**Comment by Emisse** [comment]
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

**Pull request closed without merging**
