### PR TITLE
Remove flashes from science and reduce their charges.

### PR DESCRIPTION
**Pull request by Zap527**
## About the PR

Removes flashes from the robotics department.
Reduces flash charges to 3 uses

## Why / Balance

As science currently has an unlimited supply of flashes, the Revolutionary gameplay boils down to converting a scientist and getting them to empty the robotics vendor for you, and then mass produce extra flashes from the exosuit fabricator once those are depleted. The current drawback of these flashes being worth only two conversions is not enough when you can print a virtually infinite supply of them.
This results in the station being overrun by revolutionaries before the heads and security can do anything about it, which causes a number of issues to arise. Security is forced into a position where they need to metagame the revolutionaries and secure cargo almost immediately in order to stand a chance due to the speed at which they can overtake the station, and Heads are incentivized to see any non-mindshielded crew as a revolutionary even if they are not due to how the limitless flash stock allows headrevs to simply overtake departments and flash everyone in loudly.

Removing flashes from science and reducing their effectiveness forces the early revolutionary crew to work together and take down either a head or a security officer in order to acquire more flashes and more power. This will incentivize teamwork amongst the revolutionaries and generally reduce the odds of any peculiar crew being part of the revolution, allowing heads to choose to trust some key members of their departments and encouraging security to use mindshields wisely instead of just jabbing the first tider they see to get information on the revolution.
Once security is breached and taken out, the sectech is still full of flashes which the headrevs can use to convert remaining crew, giving them a concrete goal to work towards.

Reducing flash charges will encourage the head revolutionaries to actually think about who they want on their team instead of simply dumping all their charges as soon as they can for numbers. This also encourages headrevs to work together and either try to overtake a department for headquarters and an easy head takedown or spread the love between different skillsets in order to stage a coup. Balance-wise, three conversions per headrev should be more than enough to convert a whole department or get an initial team going to take down heads.

## Technical details
N/A

## Media

N/A
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
this makes it way too hard on the headrevs

an alternative idea i had was (with flashpen ideally) is make flashes rechargable very slowly so they are *over time* unlimited but you cant run in with 10 flashes and take over a department in seconds

**Comment by Aisu9** [comment]
> this makes it way too hard on the headrevs
> 
> an alternative idea i had was (with flashpen ideally) is make flashes rechargable very slowly so they are _over time_ unlimited but you cant run in with 10 flashes and take over a department in seconds

wasn't the deal of conversion antags to make converting limited and/or a nightmare to pull off? because they always degenerate into a full murderparty or something along the line

**Comment by deathride58** [comment]
All this does is railroad Revs into taking Cargo first instead, as not only is it trivial to get flashes from there, but it also has a *lot* more to offer revs roundstart than any other non-sec department for a variety of reasons.

To be a bit blunt, this doesn't seem particularly well-thought-through.

**Comment by Unbelievable-Salmon** [comment]
So you'd have to talk to sec if you wanted to make a borg?

**Comment by Zap527** [comment]
> this makes it way too hard on the headrevs

I agree that this for sure makes it harder, but I think this is overall healthier for the game. The current climate of sec being practically forced to murderbone the whole crew if they don't secure cargo instantly isn't something I think is peculiarily good.
This might be an overnerf, but better overnerf than overbuff.

> an alternative idea i had was (with flashpen ideally) is make flashes rechargable very slowly so they are _over time_ unlimited but you cant run in with 10 flashes and take over a department in seconds

I toyed with the idea of recharging flashes, but that comes with its own caveats. Instead of encouraging coordination, it encourages headrevs to simply hide until their flash returns to max charge, strike a handful of people and then return to hiding. Basically, it keeps the issues the current iteration of revolutionaries but makes it slower and brings and adds stalling to it as well.

> All this does is railroad Revs into taking Cargo first instead, as not only is it trivial to get flashes from there, but it also has a lot more to offer revs roundstart than any other non-sec department for a variety of reasons.

To be perfectly honest, I didn't even know cargo could order flashes. The goal of this PR was to quell the easy-to-obtain sources of flashes as a whole, not lock easy flashes to cargo. This is something that can easily be fixed.
Though, I do agree that cargo has a lot to offer for revolutionaries... but it also has a lot to offer to sec. We run into similar balance issues here where the department is crucial to security in order to fight back. It's a departemental issue which is very hard to solve.
Also... this doesn't make cargo *more* appealing in my eyes, it's just as appealing as it was before. It's just that science isn't the mostest appealing ever now.

> To be a bit blunt, this doesn't seem particularly well-thought-through.

Ouch

> So you'd have to talk to sec if you wanted to make a borg?

Flashes are removed from borg recipes.

**Comment by EmoGarbage404** [comment]
I don't really think it's an issue that there are ways to get flashes that don't involve sec or heads. It's very easy for those roles to just leave their flashes in secure places if they catch wind of a revolution. Alternative sources of flashes like cargo and sci give HeadRevs a reason to focus those departments, break in, or even steal equipment. Having renewable sources of flashes outside of sec also counters metagaming, as it's far more likely to see a flash somewhere if they can just be produced.

I don't really see an overwhelming reason to remove it at this point. Thank you for your contribution, but I will be closing this PR.

**Comment by northerndakotas** [comment]
> I don't really think it's an issue that there are ways to get flashes that don't involve sec or heads. 

I see a huge issue with it. Perhaps you don't know, but the rules have been changed so that Sec and command can no longer suspect Revs based on the sound of flashes. They are only allowed to suspect Revs under one of two conditions. Either 1. A head of staff is attacked directly or 2. Someone personally witness a conversion with their own eyes. Do you see the problem? Revs attacking a head is the only likely way for Revs to be discovered and you've made attacking heads utterly unnecessary. So now the only possible way for command to discover Revs before they have taken over the whole station is if one of them is stupid enough to convert right out in public. 

You say it gives Headrevs a reason to focus these departments but really you've stripped down what could've been a good game mode into a boring meta slog that goes the same way every single time.

**Pull request closed without merging**
