### PR TITLE
moves explosive tech to T1

### PR DESCRIPTION
**Pull request by Boaz1111**
## About the PR

moves explosive tech to T1 arsenal
## Why / Balance

Was like never getting researched. I have played so many rounds of science, this has been almost never researched, and even if it was researched, it was at the very end, as an afterthought. Modular grenades allow for a lot of fun things, with perhaps more content to come to them in the future. Also, the voice trigger is a requirement for the VIM, so if this gets rejected I might see about changing that. Not once have I seen the flash or explosive payload used. Mainly the chem payload allows for a lot of things. Also might boost interaction between sci and chem? unsure?
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Boaz1111
- tweak: Explosive technology has been moved to T1 arsenal

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
So many other things not getting researched... why one of the techs that gives sci an actual reason to do sec tech past nukies?

**Comment by Kadeo64** [comment]
t2 explosive tech this week
t1 explosive tech the next 
t2 explosive tech the week after that

**Comment by Boaz1111** [comment]
> t2 explosive tech this week t1 explosive tech the next t2 explosive tech the week after that

can you elaborate on why

**Comment by metalgearsloth** [comment]
doesn't really affect anything.

**Pull request merged**
