### PR TITLE
Mineshaft

### PR DESCRIPTION
**Pull request by TheShuEd**
## About the PR
Added Mineshaft dungeon preset to Caves biome, and some prototype tweak.

## Why / Balance
more dungeon preset

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/a0da4082-7df1-4d51-bd33-8613b65ea84e

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: TheShuEd, Vsem
- add: Added new dungeon preset "Mineshaft"

### CODE REVIEW

**Comment by TheShuEd** [comment]
I honestly have no idea how to fix the error. I re-bound the asteroid walls to BaseWall because there was a lot of duplication and now it's swearing.

**Comment by Everturning** [comment]
So we back in the mine
Got our pickaxe swinging from side to side
Side-side to side
This task, a grueling one
Hope to find some diamonds tonight, night, night
Diamonds tonight

**Comment by CyberDuck-Git** [comment]
Bro, I hope you can fix it, ask the wizards on discord

**Comment by CyberDuck-Git** [comment]
Bro, I hope you can fix it, ask the wizards on discord

**Comment by TheShuEd** [comment]
I added noRot to all WallRock because the dungeon procedural rotates them randomly, and this causes various visual bugs with the edges. Now it's also impossible to put these stones crookedly on mapping. But apparently some maps have wrongly rotated stones, which causes the test fails.

I checked, and the maps run without error. I think just re-saving the maps after this PR will fix the problem.

**Comment by TheShuEd** [comment]
expeditions yes, but they will be replaced by gates, which will also use dungeon generation
(hope so)

**Review by metalgearsloth — APPROVED** [review]
Just checked code stuff

**Comment by CyberDuck-Git** [comment]
Will you need to enter your dungeons through a gate?

**Comment by TheShuEd** [comment]
Salvage expeditions

**Pull request merged**
