### PR TITLE
Allows reptilians to eat crayons, as is  their right

### PR DESCRIPTION
**Pull request by FluidRock**
## About the PR

This PR allows lizards to eat crayons. 

## Why / Balance

Why not ?

## Technical details

One line edit, not necessary. 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Lizards rediscovered their hunger for crayons.

### CODE REVIEW

**Comment by mirrorcult** [comment]
based

**Comment by Brandon-Huu** [comment]
I do not think lizards should be allowed to join the military

**Comment by deltanedas** [comment]
dont you mean become engineers

**Comment by crazybrain23** [comment]
Maybe let them eat soap too, why not?

**Comment by EmoGarbage404** [comment]
not as a disparagement on this pr in particular, but it's kind of concerning to have to specialcase in every single edible item into lizard stomachs. It doesn't seem very sustainable long-term.

**Comment by crazybrain23** [comment]
> not as a disparagement on this pr in particular, but it's kind of concerning to have to specialcase in every single edible item into lizard stomachs. It doesn't seem very sustainable long-term.

The alternative that I can think of is to add different reagents to food that have different reactions to different stomachs, but Lank said that would be too hard to do.

**Comment by Emisse** [comment]
out of scope but noting this here for future reference, we need to just murder stomach whitelists at some point and have some sort of generic encompassing digestion thing and let people just attempt to eat whatever they want

**Comment by LankLTE** [comment]
Overall not a huge fan of adding a bunch of "meme" tags to the whitelist- it's just going to cause problems and open the floodgates for a bajillion more. I'd personally rather see the current system improved or removed before this happens, though given it's a pre-existing tab this is more from a worry of making "meme" items edible the norm rather than any burden.

**Comment by FluidRock** [comment]
The stomach is inherently flawed, however that is not something I am capable or willing to fix. I simply want to eat crayons.

**Comment by lzk228** [comment]
i think it should be better to allow them eat like humans, but they will be vomiting from non-meat

**Pull request merged**
