### PR TITLE
Buff/Nerf Gases Cost

### PR DESCRIPTION
**Pull request by sporekto**
## About the PR
Nerf/Buffed Gases Cost

## Why / Balance
 Now there will be at least some interest in playing atmos, playing exactly like atmos, and not an engineer.Before my change, tritium cost 5 per mole, and frezon 0.3. Which looks illogical

## Technical details
Сhanged the values

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
BEFORE
Frezon->0.3
Tritium->5
NitrousOxide->2.5
AFTER
Frezon->3
Tritium->2.5
NitrousOxide->1

### CODE REVIEW

**Comment by sporekto** [comment]
> I think that N2O should still be the price, or even more than frezon, as it’s arguably harder to produce in large quantities

N2O has a recipe, I would even say a simple one.Oxygen+Miasma at a temperature of 50 C, form N2O and water vapor.

**Comment by Golinth** [comment]
> N2O has a recipe, I would even say a simple one.Oxygen+Miasma at a temperature of 50 C, from N2O and water vapor.

Yes, but it is hard or impossible to get enough Miasma to get mass amounts of N2O. The current method of producing mass quantities is by using frezon decomposition with nitrogen and heat, which is “harder” than normal frezon due to the added step.

**Comment by Deminer** [comment]
N2O also has a recipe in the form of frezon + nitrogen, so it is a by-gas in the synthesis of frezon, so the synthesis of N2O is an easy action, unlike the synthesis of tritium first, and after frezon

**Comment by Ilya246** [comment]
this kinda allows atmos to easily make cargo hundreds of thousands of spesos again with frezon
i don't see why this reduces the tritium price either, tritium is hard to produce in high amounts and you need at least 1mol plasma per mol trit, which is expensive, so the price of 5/mol was well-balanced considering much the plasma for making trit costs and how fast you can actually make it

**Comment by slarticodefast** [comment]
I think frezon was so cheap because you can turn 1mol tritium into 50mol frezon. The other ingredients, oxygen and nitrogen are free and unlimited. This buff should be reconsidered.

**Comment by Ilya246** [comment]
> I think frezon was so cheap because you can turn 1mol tritium into 50mol frezon. The other ingredients, oxygen and nitrogen are free and unlimited. This buff should be reconsidered.

i was responsible for the 0.3/mol frezon price but yes, i could agree it is a little cheap, and i could agree with a slight (no lesser price than 4) trit price reduction
also note that frezon production efficiency actually scales from 17 mol/trit to 50 mol/trit and the higher efficiencies require optimisations if you wish to produce meaningful quantities of frezon

**Pull request merged**
