### PR TITLE
infiltrator update

### PR DESCRIPTION
**Pull request by Emisse**
changelog
-tiny fans are gone, all airlocks are now linked
-all airlocks are now syndie access locked
-a turret in the rear and in the cockpit
-syndicate fireaxe is on the vessel
-skub

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
*removes fire axe from uplink*
"noo whyy!! le reasonable counter arguments!!"
*puts the axe in the infiltrator for free*
"nevermind lmao"

**Comment by Emisse** [comment]
those were more towards traitors

**Comment by Emisse** [comment]
this also only gives nukies 1, they cant get more

**Comment by Emisse** [comment]
im gonna kjill you

**Pull request merged**
