### PR TITLE
Nerfs Gatfruit & reduces its spawn probability

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR 
-Yield is about ~30 times lower (combination of loss of repeatable harvest, yield from 2->1, maturation from 6->40)
-Spawn probability reduced 70%

Closes https://github.com/space-wizards/space-station-14/issues/6591

### CODE REVIEW

**Comment by Elijahrane** [comment]
Also you can still get seeds, yes, but you can probably get only 2-3 total harvests over in an average round length.

**Comment by mirrorcult** [comment]
definitely reasonable now with the maturation time

**Comment by Elijahrane** [comment]
ahhh wtf is wrong with my git, just noticed vitamins are in here too

**Comment by Elijahrane** [comment]
Reduced the maturation time just a bit because I'm not sure you'd be reliably able to get 1 harvest off in average round length since this is an item that usually comes mid-round and it'd be pretty lame if the round ended most of the time you were trying to grow one.

**Comment by Elijahrane** [comment]
After an adminbus round brought to us by moony I think the main issue was the repeatable harvest, that change along cuts the number of guns by a huge amount.
I reduced the maturity age to 25, since it'll still take a few generations to get huge production going most rounds just won't be long enough and there will be probably only a couple revolvers average each round a seed packet is discovered.

**Pull request merged**
