### PR TITLE
PA ui cleanup + bugfixes

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

does a few things
- fixes PA control computer sprites being the incorrect value
~~- adds a radio alarm for changing PA power or setting strength~~
- Fixes ui bugs regarding cutting wires on the PA.
- updates all of the UI code to modern standards with XAML

## Why / Balance

These are all meant to be a part of the larger changes to make the PA less griefable and less of a noobtrap.

~~This primarily is on the griefer side. The alarms allow discreet sabotage only with advanced prep (taking out the comms) and without the prep, allow for engineers to react before the PA gets completely out of control.~~

all the other fixes just help make the hacking more straightforward since it'll be used a lot more.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed wires not updating UI on the Particle Accelerator.

### CODE REVIEW

**Comment by deltanedas** [comment]
does radio jammer work with this :trollface:

**Comment by Cojoke-dot** [comment]
Wait… how is this going to stop anything? Can't you just set the pa to for and lock the doors + build walls? If your engi you have access to an rcd and can quickly just build a couple walls to stop people from turning it off, even if not set to 4.

**Comment by BolloTea** [comment]
When will you stop polluting the radio airwaves?  Have you presented a game for the captain?  When the entire radio airwaves are filled with spam from consoles, but here you need to find valuable information from departments among the spam

**Comment by BolloTea** [comment]
This does not solve the problems, but only adds an additional point for griefers to destroy telecoms and only then release the singularity.  Apart from spam and unnecessary actions, there is absolutely nothing useful here.  The administrator already has tools to identify sabotages, please stop or solve the problem in another way

**Comment by BolloTea** [comment]
Place a block on PA at levels 3-4 or higher so that it can only be unlocked with captain and CE access

**Comment by BolloTea** [comment]
And for sabotage there is emag

**Comment by EmoGarbage404** [comment]
> does radio jammer work with this :trollface:

i would imagine yeah

**Comment by EmoGarbage404** [comment]
removed radio alert from the PA and fixed conflicts

**Pull request merged**
