### PR TITLE
Origin Station Update 13.06.2023 (Borg, Trash)

### PR DESCRIPTION
**Pull request by brainfood1183**
Added - Trash bins in maints
Added - borg charging stations (no borg start role)
Added - more decal work to some areas.
Added- Botany chainsaw no more.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by LankLTE** [comment]
why no borg start role i wanna be a borg main

**Comment by JoeHammad1844** [comment]
I dont see a charger in robotics

**Comment by potato1234x** [comment]
why no borg role

**Comment by brainfood1183** [comment]
> why no borg role

fairly sure its not considered exactly reasy yet

**Pull request merged**
