### PR TITLE
Airloss medicine

### PR DESCRIPTION
**Pull request by SethLafuente**
## About the PR 
Added stable plasma into the chem master for recipes like dexalin 
**Screenshots**

image

**Changelog**

:cl: Seth
- add: Added stable plasma into the chem master 
- add: Added Dexalin and Dexalin plus

### CODE REVIEW

**Review by SweptWasTaken — APPROVED** [review]
One more maintainer approval and i'll merge.

**Comment by scaly-chimp** [comment]
> add: Added Dexalin and Dexalin plus
they were already in the game, right? I remeber adding functionality to them in my damage metabolism thing

**Comment by SethLafuente** [comment]
> > add: Added Dexalin and Dexalin plus
> > they were already in the game, right? I remeber adding functionality to them in my damage metabolism thing

yeah but just so people know they are now usable

**Comment by metalgearsloth** [comment]
What?

**Comment by metalgearsloth** [comment]
Also chem dispenser's not supposed to dispense plasma last I checked.

**Comment by mirrorcult** [comment]
he mentioned in the changelog that dexalin and dexalin plus were added despite the fact that they were already in, to make people aware that they now actually have effects

> 
> Also chem dispenser's not supposed to dispense plasma last I checked.

stable plasma and plasma you get from grinding up bars is different

**Comment by metalgearsloth** [comment]
I thought we weren't copying TG?

**Comment by scaly-chimp** [comment]
we aren't, dexalin and dex + are vg, with stable plasma as part of their recipe

**Comment by metalgearsloth** [comment]
I don't see stable plasma on the dispenser unless it's not the one I'm looking at? https://github.com/vgstation-coders/vgstation13/blob/e26cb3a52563cefd412cd6d95c52b53186d45cd3/code/modules/reagents/machinery/chem_dispenser.dm

**Comment by TimrodDX** [comment]
> 
> 
> we aren't, dexalin and dex + are vg, with stable plasma as part of their recipe

Dexalin and Dexalin Plus were originally /tg/ chemistry before they overhauled. In the original /tg/ code, "stable plasma" wasn't a thing. That's why plasma was only a catalyst in those recipes - it was because in /tg/, you started with a limited number of solid plasma sheets that had to be ground down into a liquid to be used in chemistry.

I think /vg/ changed that because they realized that the grinder was basically only ever used to grind down that initial batch of plasma since there were no other chem recipes that called for liquids derived from mining materials. I think the only other thing that used a liquid mining material was the PACMAN generator which also used liquid plasma.

I don't have a strong opinion on it either way, but that's just how it was.

**Comment by metalgearsloth** [comment]
Seems like it'd be better to add plasma grinding if it isn't already in and just giving it roundstart then.

**Comment by SethLafuente** [comment]
should I close this or??? a bunch of servers use stable plasma if we dont want to use stable plasma I can change this into plasma grinding plasma isnt a feature yet

**Comment by SethLafuente** [comment]
also just giving a little of plasma at the start of the round for a medicine that needs to be used a lot is very dumb unless you add plasma to cargo

**Comment by metalgearsloth** [comment]
> that needs to be used a lot is very dumb

It's a catalyst.

Also we are using vg until another maintainer says otherwise as tg is dumb.

**Comment by SethLafuente** [comment]
> > that needs to be used a lot is very dumb
> 
> It's a catalyst.
> 
> Also we are using vg until another maintainer says otherwise as tg is dumb.

o yeah forgot about that so should I close the pull request or change something?

**Comment by metalgearsloth** [comment]
re-use it, it doesn't matter

**Pull request closed without merging**
