### PR TITLE
More Impostor Items

### PR DESCRIPTION
**Pull request by Ablankmannn**
## About the PR 
This PR (hopefully) adds 4 new bundles, and 1 new melee item to the Syndie Uplink. These are:

The High-Tech Axe: A fireaxe that does a little more damage, and looks cooler, but cannot fit in boxes or bags. 16 TC.
Pie Cannon Bundle: A bundle for 10 TC that has 1 Pie Cannon, 5 Banana Cream Pies, and 1 Clown Mask
Python Bundle: A bundle for 15 TC that has 1 Python, 2 .40 Speed Loaders, and 1 High Velocity .40 Speed Loader
AKMS Bundle: A bundle for 30 TC that has 1 AKMS, and two .30 Magazines
Lecter Bundle: A bundle for 35 TC that has 1 Lecter, and 1 Box of .20 Magazines

**Changelog**

:cl: 
- add: Added 4 new Bundles, and 1 new Melee Weapon to the Uplink.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I am hesitant to add AKMS and Lecter. I know a lot of the machine guns have not had a good balance pass and are quite overpowered. It seems like this would just contribute to the overkill gun bundles that nukies seem to eat up.

**Comment by Stealthbomber16** [comment]
There really should be more than five pies in the pie bundle.

**Comment by Just-a-Unity-Dev** [comment]
for 16 TC? make it instagib or some shit didnt know cybersun spends so much on these axes

**Comment by Peptide90** [comment]
I’ve held off commenting but have my thoughts on discord. I don’t know what the balance is with guns so couldn’t care about those. The AK maybe could stay as for Russians only but at the same time this gives it a use and it’s harmless.

The axe however just seems a little like item bloat. Why not a syndicate energy axe or something more badass. It could be it’s own PR, make it do knock back or something.

Also bear in mind traitor and syndie uplinks are being split.

**Pull request closed without merging**
