### PR TITLE
saltern reporter and tvs

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
forgor to push :trollface: :skull:

### CODE REVIEW

**Comment by deltanedas** [comment]
makes news kinda useless if its only on 2 maps just taking up space otherwise

**Comment by Emisse** [comment]
we are seeing how it plays out on those other maps first

**Comment by Emisse** [comment]
join discord pro

**Comment by deltanedas** [comment]
no noob

**Comment by Nairodian** [comment]
> makes news kinda useless if its only on 2 maps just taking up space otherwise

You can make it via science.

**Comment by deltanedas** [comment]
o

**Pull request closed without merging**
