### PR TITLE
New Map: Iris Station

### PR DESCRIPTION
**Pull request by luckyshotpictures**
## About the PR

This introduces a new map into the map pool: Iris. Your love and horrors are all in this map, as it has been built to contain the demon core. This map has been themed and built around it. The map has been named after the look, as the central core looks like an Iris, with the rest of the station being the "eye".

## Why / Balance
 

Key areas include a Psychology Wing, Demon Core Containment as the central focus, a Bridge overseeing the Core Containment, and a Foodcourt with a central Bar. The Science department is split into three sections, while the Supply area is shielded for extra protection against meteors. Security is situated beneath the Core and includes an experimental inmate suppression system, humorously described as "sec is a donut, it is huge". This is because the armory is in the middle of the security department as the center piece. Additionally, there's an abandoned AI Core and a Cargo area with an aesthetically pleasing front. The Chemistry department is placed in the middle of the Medical department, featuring a window to the hallway.

I believe all issues that have been brought to my attention have been fixed.
Discord Feedback Thread: https://discord.com/channels/310555209753690112/1168343942606094377
## Media

Iris-0
Picture slightly outdated; TEG & Science area changed. The map renderer is giving me an error though, it will take a bit until i can figure it out why that is. Help is appreciated!

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: New station map "Iris" with unique features like Demon Core Containment, a Psychology Wing, and an experimental Security system.

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Do those solars work

**Comment by Aexxie** [comment]
Core 3

**Comment by luckyshotpictures** [comment]
> Do those solars work

they do!

**Comment by Aexxie** [comment]
There's a docking port at the top left of the weird core thingy, dunno if that was intentional

**Comment by luckyshotpictures** [comment]
> There's a docking port at the top left of the weird core thingy, dunno if that was intentional

yes, an escape shuttle spawns there.

**Comment by metalgearsloth** [comment]
Solars use the same raycast as lasers but if grilles don't stop it maybe it's fine?

**Comment by Emisse** [comment]
i will be starting review in cartography soon

**Comment by Augul** [comment]
Oh hell yeah! I love the layout!

**Comment by luckyshotpictures** [comment]
> Solars use the same raycast as lasers but if grilles don't stop it maybe it's fine?

i do recall that solars being shielded by lasers is quite common, see e.g. Aspid, Bagel, Barratry, Box, Cluster, Fland, etc.

**Comment by DrMelon** [comment]
Looks like there's a lot for engineering and atmos to get stuck into at the start of a round. Particularly enjoy how much wiring work would be required to set up the tesla, while still having it available as an option. Sometimes it feels like it's too easy to set up quickly on some maps.

**Comment by Sirionaut** [comment]
Janitorial closet needs watertank/sink

**Comment by CatMagic1** [comment]
Touchdemoncore%

**Comment by MemesHodachy** [comment]
look at rnd ksenoarcheology room on evac zone 🤪 i think it's very dangerous

**Comment by snebl** [comment]
Gotta love the 175 tile long commute from engineering to cargo if you don't take maints.

**Comment by UbaserB** [comment]
oh? curious why you closed it

**Comment by luckyshotpictures** [comment]
because github is a child born out of a wedlock and i have no clue what i am doing, going to move this to a branch and not my master, still working on it

**Comment by UbaserB** [comment]
why did you put the map on your master lol

**Comment by luckyshotpictures** [comment]
<-- second time using github, never coded anything before

**Pull request closed without merging**
