### PR TITLE
Capitalizes Locker Names

### PR DESCRIPTION
**Pull request by SweptWasTaken**

### CODE REVIEW

**Comment by ComicIronic** [comment]
Don't agree with this. Names should be lower-cased if they're not proper.

**Comment by PJB3005** [comment]
Right now most of our names do lean towards being all capitalized, while in SS13 it's kind of a mixed bag (but leaning towards lowercase mostly).

Personally I also think using all lower case is probably best.

**Comment by SweptWasTaken** [comment]
90% of the stuff in our entities spawn list is capitalized.

image
These aren't proper nouns...

image
Neither are these...

**Comment by ComicIronic** [comment]
There looks to be lots of inconsistency between capitalised names as well - `Small Light` vs `Solid wall`. There should definitely be some agreed-on naming convention, and then a standardisation of the current names.

**Comment by AJCM-git** [comment]
We agreed in our [guidelines](https://hackmd.io/Awj5TvdXTaOmhU2XZOsdQg?view) to use proper nouns capital initials and improper nouns lowercase initials in the menus

**Comment by SweptWasTaken** [comment]
We also decided in the above thread so i'm closing this.

**Pull request closed without merging**
