### PR TITLE
no more MRP sandbox.

### PR DESCRIPTION
**Pull request by moonheart08**
goobye

:cl: moony
- fix: The fallback gamemode should something happen is now extended, not sandbox.
- remove: Removed fun!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
`Removed fun!` has never rung more true.

**Comment by asperger-sind** [comment]
Fixes #11227

**Comment by Morb0** [comment]
Isn't it useful when someone self hosts a local server for tests?

**Comment by Visne** [comment]
> Isn't it useful when someone self hosts a local server for tests?

Then you can just edit the CVar locally.

**Comment by Morb0** [comment]
Why then MRP server can't edit the CVar locally?

**Comment by Visne** [comment]
Well it can, but sandbox doesn't really make much sense as a default value for this CVar anyways.

**Comment by Illiux** [comment]
It might reasonably be the default fallback in debug builds but I agree.

**Pull request merged**
