### PR TITLE
ERT leaders get a pinpointer and pulse rifle

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

ERT leader gets a nuclear pinpointer and pulse rifle, which has about 400 shots
## Why / Balance

ERT is meant to be powerful and might have to find the nuke. even when like 40 ERT is spawned there is usually only one leader
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by B1essedknight** [comment]
I think that the amount of ammo in the pulse rifle is fine, considering that someone could grab it from the commander if they were stunned or killed, plus the amount of ammo in it would cause the commander to be the only one that could stay in a drawn-out fight. 

Dunno, but I rather the commander retreat with the squad then be the only one that can fight and get ganked by the hostiles.

Pinpointer could just be provided to the commander by the admins or if it is really necessary, but ERT hardly gets called in for nuke ops just because they are already hard enough to deal with.

**Comment by LankLTE** [comment]
Pretty sure the 400 shot pulse rifle is supposed to be an admeme weapon. At the very least it’s insanely unbalanced and if admins want ERT leaders to have one they can give it to them. Otherwise they should stay with just the pulse carbine.

**Comment by RyanStrudfelt** [comment]
the Pulse Rifle is intended to be Admeme as a DeathSquad only weapon. The carbine is the ERT intended variant.

**Comment by JoeHammad1844** [comment]
deathsquad doesn't even spawn with the pulse rifle

**Comment by Ilya246** [comment]
the rifle has half the firerate of a pulse carbine

**Comment by RyanStrudfelt** [comment]
Death squad doesn't spawn without admin intervention, and neither does the rifle.
The carbine exists as an alternative for the ERT as it functionally isnt as broken if lost.

**Comment by JoeHammad1844** [comment]
ERT also does not spawn without admin intervention

**Comment by HoidC** [comment]
> the rifle has half the firerate of a pulse carbine

and does a shitton of damage as well as having what is essentially unlimited ammo

**Comment by JoeHammad1844** [comment]
it does the same ammo as the pulse carbine, but with half the fire rate. the only upside is the ammo count. if a pulse rifle and carbine go head to head, the carbine would only lose if both sides have potato aim

**Comment by RyanStrudfelt** [comment]
And by doing this all you achieve is nothing. Because we will just take it out of their inventory if we spawn them. Or just not spawn them at all.

The reason they spawn without weapons is so we can assign them weapons based on the situation. 
Like an ert should.

**Comment by moonheart08** [comment]
ERT isn't deathsquad, and it's the game staff's responsibility to choose their outfit.

**Comment by moonheart08** [comment]
take your powergame bait elsewhere we're not giving out toys for free

**Pull request closed without merging**
