### PR TITLE
 add maid uniform to service worker loadout

### PR DESCRIPTION
**Pull request by Svetoslav228**
## About the PR
it's just add maid uniform in service worker and janirator loadout.

## Why / Balance
maid uniform it's just a alternative version to bartrender's uniform.

## Technical details
bartrender and service worker now has diferent jumpsuit groups

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- add: maid uniform now in service worker loadout
- add: maid uniform now in janirator loadout

### CODE REVIEW

**Comment by muburu** [comment]
i remember reading somewhere that this is contraband??? it's apart of emagged janidrobe stock i think so it might be a nono for loadouts

**Comment by bruhmogus** [comment]
> i remember reading somewhere that this is contraband??? it's apart of emagged janidrobe stock i think so it might be a nono for loadouts

that, uhm. might have been me
you can get the janitorial maid uniform from expeditions, but the only way to get the uniform w/ skirt is emagging the janidrobe
HOWEVER they aren't counted as contraband via inspect, so it's fine

**Comment by bruhmogus** [comment]
also imo this should be in janitor loadouts instead for... obvious reasons, would fix bartenders having a maid skirt for no reason too

**Comment by Kadeo64** [comment]
you can get one of the janitor costumes in a cargo theatrics crate

**Comment by Svetoslav228** [comment]
what is it? ```  1) SERVER: 0.284s [ERRO] entity: Caught exception while raising event EntityTerminatingEvent on entity Bronte Fisher (84191/n84191, MobHuman)
System.Collections.Generic.KeyNotFoundException: Entity 84190 does not have a component of type Content.Shared.Roles.MindRoleComponent```

**Comment by KingFroozy** [comment]
> what is it? ` 1) SERVER: 0.284s [ERRO] entity: Caught exception while raising event EntityTerminatingEvent on entity Bronte Fisher (84191/n84191, MobHuman) System.Collections.Generic.KeyNotFoundException: Entity 84190 does not have a component of type Content.Shared.Roles.MindRoleComponent`

unrelated test fail, you can ignore it

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and we decided not to merge this since the janitorial maid uniform is a janitor item and does not make sense in the bartender or service worker loadout. Thank you for your contribution.

**Pull request closed without merging**
