### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
**Media**

Ignore colors being different, the screenshots were taken on a different fork.

https://imgur.com/a/LE58sWG

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: DEATHB4DEFEAT
- tweak: Changed the appearance of several UIs

### CODE REVIEW

**Comment by potato1234x** [comment]
I love this but is the crafting window resizable now? its always in my way

**Comment by DEATHB4DEFEAT** [comment]
> I love this but is the crafting window resizable now? its always in my way

I can probably do that

**Comment by EmoGarbage404** [comment]
all of these need screenshots + this pr can definitely be split up into multiple.

**Comment by DEATHB4DEFEAT** [comment]
> all of these need screenshots

theres screenshots, an imgur album link

> this pr can definitely be split up into multiple.

much more work to do that D:

**Comment by metalgearsloth** [comment]
Split the pr.

**Comment by DEATHB4DEFEAT** [comment]
currently workin on splitting it and fixing the merge conflict

**Pull request closed without merging**
