### PR TITLE
Moth accent

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

Added accent for moth
`Z` becomes `ZZZ`
completely like `S` in lizard accent

## Why / Balance

pro

## Technical details

System full copypasted from lizard system

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Content Client_JTIeGH8i9A

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Moth accent added! Buzzz!!!

### CODE REVIEW

**Comment by lzk228** [comment]
it's just like lizard hisses, so what's the problems?

**Comment by lzk228** [comment]
i just thought, what if `th` would change to `z`, like `mozer`
is that good?

**Comment by GoodWheatley** [comment]
> i just thought, what if `th` would change to `z`, like `mozer`
> is that good?

Probably going to be too hard to read, the lisp accent has the same problem.

**Comment by Emisse** [comment]
just fuck my whole life up with accents dawg

**Comment by LankLTE** [comment]
Will add that this wasn’t added to the accentless trait, so it won’t work with this species accent. Fairly easy fix I’ll probably do if I’m home, but if someone else wants an easy change to make that’s there.

**Pull request merged**
