### PR TITLE
Janitorial Bomb Suit

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

There has always been the issue of janitors exploding themselves when cleaning potassium spills, and no one could stop them. Since buying an EOD suit is expensive and annoying just for a minor spill, this suit gives janitors an opportunity to help out too. The suit is weaker than a normal EOD suit as it gives a 20% movement slowdown and has no armor protection.

You can purchase the bomb suit through cargo for 1000 spesos.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image
image

**Changelog**

:cl: Ubaser
- add: Janitors can now buy their own bomb suit for cleaning chemical spills.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This feels like comical amounts of over equiping. Janitor doesn't need a bombsuit lmao. Even sec only gets like 1 in the armory. Plus, you can just order them. Why invalidate one of the few orders that actually has a purpose.

**Comment by asperger-sind** [comment]
balance and game design aside this just looks like a really silly gimmick item, the sort you'd expect in ss13, while this does raise concerns of redundancy and potentially powercreep i still want to see this because like, holy shit janitor bombsuit (audible laugh)

**Comment by IamVelcroboy** [comment]
I love this. If anything, just make it not quite as good as the proper bomb suit.

**Comment by gostt899** [comment]
This being added to cargo would be funny.

**Comment by UbaserB** [comment]
> This feels like comical amounts of over equiping. Janitor doesn't need a bombsuit lmao. Even sec only gets like 1 in the armory. Plus, you can just order them. Why invalidate one of the few orders that actually has a purpose.

i guess you dont understand how often janitors explode themselves stupidly then *sighs*, like literally no one ever orders them from cargo anyway; and its not invalidated as you cant order it from cargo lol. If you want, i can make the locker lockable so only janitors can take it out.

**Comment by UbaserB** [comment]
> I love this. If anything, just make it not quite as good as the proper bomb suit.

its already not as good, but i can also nerf the explosion values to really give it a proper nerf.

**Comment by Emisse** [comment]
looks cute but maybe put it in cargo or something

**Comment by Emisse** [comment]
cargo needs more fun gimmick stuff to order anyway

**Comment by deltanedas** [comment]
potassium explosion got buffed so this might actually get bought

**Review by Emisse — APPROVED** [review]

**Pull request merged**
