### PR TITLE
Revert "Mail resprite"

### PR DESCRIPTION
**Pull request by juliangiebel**
Reverts space-wizards/space-station-14#15832
I don't think the new sprite makes visual sense with the yellow blob behind it and I'm not sure why it was merged without any discussion tbh.
I think the original sprite looks distinct enough. It's intended have the same shape as a disposal unit because it is basically a different version of the disposal unit for sending mail. It uses disposal pipes and all.

### CODE REVIEW

**Comment by Nimfar11** [comment]
The mail is too much like a garbage can. They are literally the same, only in different colors. It shouldn't be like that.

**Comment by metalgearsloth** [comment]
> I'm not sure why it was merged without any discussion tbh.

It was merged 2 days later with no one else commenting?

**Comment by juliangiebel** [comment]
> > I'm not sure why it was merged without any discussion tbh.
> 
> It was merged 2 days later with no one else commenting?

I would've commented but I just now noticed that it was actually changed. Tbh, I thought the sprite layering broke or something every time I saw the new sprite until I saw that It was the actual sprite.

**Comment by juliangiebel** [comment]
> The mail is too much like a garbage can. They are literally the same, only in different colors. It shouldn't be like that.

The mailing unit is literally just a different version of the disposal unit. It makes sense to just have a different color and it's not like the color is only slightly different

**Comment by Nimfar11** [comment]
> The mailing unit is literally just a different version of the disposal unit. It makes sense to just have a different color and it's not like the color is only slightly different

But their functionality is different. Not even a person can get into the mail. And this form of sprite has a more recognizable form of mailboxes.

**Comment by Arteben** [comment]
In the old version, they were very similar to each other, so people threw garbage into the mailbox! In the new version, it became more difficult to confuse them with each other.

**Comment by moonheart08** [comment]
Agreeing with Julian, the new sprite looks *weird*.

**Pull request merged**
