### PR TITLE
Add meat crate to cargo

### PR DESCRIPTION
**Pull request by lapatison**
## About the PR 

**Screenshots**

**Changelog**

:cl:
- add: You can now buy a crate of meat for a barbecue in the cargo department.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Can you not just order animals from cargo? I feel like having to butcher live animals is more interesting than just buying meat in a crate.

**Comment by mirrorcult** [comment]
i dont see why this needs to exist when you can just buy animals yeah

**Comment by moonheart08** [comment]
Just buy a live animal, more interesting.

**Comment by lapatison** [comment]
@moonheart08 
> Just buy a live animal, more interesting.

Although, I agree that livestock crates are more interesting in gameplay and department collaboration terms, I pretty sure that separate meat crate can coexist as alternative, simpler but expensive solution.
Perhaps, price can be increased up to 4k points, simultaneously with chicken (currently 2.5k\4 chickens), duck (3.5k\6 ducks), and cow (3.2k) crate's price decrease.
However, if your decision is final - so be it.

**Pull request closed without merging**
