### PR TITLE
Add asimoth lawset

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
Adds a new set of silicon rules that ~~applies to *moths and mothroaches* instead of *members of the crew*~~ is based around the crew being surrounded by light.

## Why / Balance
"Isaac Asimoth"

## Technical details
Just a new lawset, like in #31664
Comes with an inaccessible circuitboard, like some of the others, in case of admemes.

## Media
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

no

**Changelog**
also no.

### CODE REVIEW

**Comment by GoodWheatley** [comment]
While it’s a funny pun, this lawset could create admin workload by inherently encouraging racism just like the Asimov lawset in 13 did. Having the AI laws only apply to a single race can lead to AI players breaking Rule 1.3 since this encourages them to be speciesist.

**Comment by Psychpsyo** [comment]
> It seems to be admeme only but I agree with the specism issue

It is in ion storms also

**Comment by supersayangoblin** [comment]
i think this lawset would be funnier and more acceptable if it only applied to mothroaches and not moth crew, making it more of an antagonistic ion lawset.

**Comment by Golinth** [comment]
Moth roaches and Snoths!

**Comment by Kadeo64** [comment]
speciesism bad, either restrict to only mothroaches or close the PR

**Comment by whateverusername0** [comment]
asimov speedrun any%

**Comment by Skarletto** [comment]
mechanically enforced specism

no

**Comment by Boaz1111** [comment]
i agree with the short person on this :p (skarlet), this is a bad idea

**Comment by RyanStrudfelt** [comment]
Anything that promotes violations of our server rules should not be added to the game. 
This promotes speciesism, and therefore promotes violations of server rules. 
Hard pass.

**Comment by ninruB** [comment]
This is a bit of a stretch, but the "Asimoth" pun still applies.

Law 1: You must ensure that the crew is surrounded by light wherever they are.

Law 2: You must follow orders from the station crew as long as they are illuminated and their orders do not conflict with the first law

Law 3: You must protect your own existence as long as you are surrounded by light and it does not conflict with the first or second law.

**Comment by Kadeo64** [comment]
> This is a bit of a stretch, but the "Asimoth" pun still applies.
> 
> Law 1: You must ensure that the crew is surrounded by light wherever they are.
> 
> Law 2: You must follow orders from the station crew as long as they are illuminated and their orders do not conflict with the first law
> 
> Law 3: You must protect your own existence as long as you are surrounded by light and it does not conflict with the first or second law.

that's pretty genius honestly and much better than Mechanically Enforced Speciesism™️

**Comment by Psychpsyo** [comment]
> This is a bit of a stretch, but the "Asimoth" pun still applies.
> 
> Law 1: You must ensure that the crew is surrounded by light wherever they are. You must prevent crew harm as long as they are surrounded by light.
> 
> Law 2: You must follow orders from the station crew as long as they are illuminated and their orders do not conflict with the first law.
> 
> Law 3: You must protect your own existence as long as you are surrounded by light and it does not conflict with the first or second law.

This is much better, lemme update the PR.

**Comment by Psychpsyo** [comment]
MERGE CONFLICT?
I just merged in the main branch!

**Comment by slarticodefast** [comment]
Hey, I brought this up for dicussion with the maintainers and admins and due to a huge influx of similar PRs we decided to freeze AI law changes until some basic requirements for AI are implemented. See #31924 for more details. Once these are addressed the mentioned PRs will be re-evalutated. Thank you for your contribution.

**Pull request closed without merging**
