### PR TITLE
Flipped caps real

### PR DESCRIPTION
**Pull request by themias**
## About the PR

Allows soft caps to be flipped backwards using an alt-verb (Flip)

## Why / Balance

Looks cool. :sunglasses:

## Technical details

Uses the FoldableClothing component from the face bandanas PR. It just needed the ability to add an equipped/held prefix.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/89101928/9e08d514-17e9-41de-9841-22f86243bd21

**Changelog**

:cl:
- tweak: Soft caps can be flipped backwards with an alt-verb (Flip)

### CODE REVIEW

**Comment by Hmeister-real** [comment]
based

**Comment by mirrorcult** [comment]
feels like the verb text should be changed

**Comment by Tayrtahn** [comment]
Yeah, I recommend adding a LocId for the verb text to the component, so it can be changed for cases like this.

**Comment by themias** [comment]
> feels like the verb text should be changed

I've added a LocId so that it will be 'Flip' instead of 'Fold' in this case.

**Pull request merged**
