### PR TITLE
Damp rag now looks like damp rag

### PR DESCRIPTION
**Pull request by Slardar0609**
## About the PR

Damp rag Texture now looks like damp rag
## Why / Balance

It was not looking like damp rag
## Technical details

N\A
## Media

rag
before
newrag
after
Снимок экрана 2024-06-01 132209
in game
## Breaking changes

N\A

**Changelog**

- Tweak : changed damp rag texture to look like damp rag

### CODE REVIEW

**Comment by Slardar0609** [comment]
Why do i have these commits like moldy bread here. If i did something wrong, forgive me.

**Comment by deltanedas** [comment]
a wet towel doesnt become bright blue

**Comment by Cojoke-dot** [comment]
Uh... you made it delete all the mixingCategory

**Comment by foboscheshir** [comment]
image

**Comment by Slardar0609** [comment]
> Uh... you made it delete all the mixingCategory

i bad at it

**Pull request closed without merging**
