### PR TITLE
Remove soapy water

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

Resolves ##23431.

### CODE REVIEW

**Comment by lzk228** [comment]
the whole thing about #23431 its to **replace** soapy water on soap functionality, not just removing soapy water

**Comment by UbaserB** [comment]
> the whole thing about #23431 its to **replace** soapy water on soap functionality, not just removing soapy water

no, its about space cleaner replacing soapy water functionality and soap replacing space cleaner with decal cleansing. I simply decided to remove soapy water first as someone else can code the soap thing in later. This does not conflict with the issue as i believe space cleaner already does exactly what soapy water does. If needed, i can try reimplement the functionality into space cleaner.

**Comment by UbaserB** [comment]
I forgor there was a button you could tap to resolve it lols

**Comment by UbaserB** [comment]
Turns out Soapy water is messing with code and i dont know how to remove code so im going to close this PR

**Pull request closed without merging**
