### PR TITLE
Fix filing cabinets id casing + yml cleanup

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

- add abstract BaseFilingCabinet for parenting
- cleanup
- fix id casing for drawers
- random drawers was renamed to filled drawers (why they are even called random)

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

IDs of filing cabinets was changed to PascalCase. All added to migration.yml.
```yaml
filingCabinet: FilingCabinet
filingCabinetTall: FilingCabinetTall
filingCabinetDrawer: FilingCabinetDrawer
filingCabinetRandom: FilingCabinetFilled
filingCabinetTallRandom: FilingCabinetTallFilled
filingCabinetDrawerRandom: FilingCabinetDrawerFilled
```

**Changelog**

no cl

### CODE REVIEW

**Review by Partmedia — CHANGES_REQUESTED** [review]
Please avoid changing entity ID's for cosmetic reasons. Entity ID's are not player-visible, and even though you have a migration, it breaks forks that have translations because the entity Fluent translation string is based on the ID (e.g. `ent-Foo-Name`).

**Comment by lzk228** [comment]
> Please avoid changing entity ID's for cosmetic reasons. Entity ID's are not player-visible, and even though you have a migration, it breaks forks that have translations because the entity Fluent translation string is based on the ID (e.g. `ent-Foo-Name`).

no, casing IS matter, and this casing is worng
there already an example of fixing some IDs to PascalCase #28014

**Comment by Emisse** [comment]
can you please fill out a breaking changes segment in this that we can also post to discord and then its fine

**Comment by lzk228** [comment]
added

**Comment by Partmedia** [comment]
Maintainers have discussed before to not allow these kinds of breaking YAML changes.

**Comment by lzk228** [comment]
if you care so much about forks with localization, i assure you it's VERY easy to fix

**Comment by Partmedia** [comment]
Entity prototype ID's are unique global identifiers for the computer that are yes, among other things, used to generate localization FTL strings. Please feel free to re-open once the breaking name changes are undone.

**Pull request closed without merging**
