### PR TITLE
Atmospheric Technician

### PR DESCRIPTION
**Pull request by Emisse**
The job of the atmospheric technician is simple. Prevent or fix environmental disasters. Ensure air is breathable and pull people dead or alive out of the searing heat of a plasma fire or the cold vacuum of space.
-I feel we are at a point where this job is needed to ween more of the playerbase into atmospherics. We also need dedicated hull breach fixers/disaster response. Many rounds players bodies will sit for a very long time while engis sit and fix power in disaster zones. Atmo techs seal a room and get bodies out while engis work on more repairs. 
-I would also like to make atmospheric technician unable to be a traitor for now. I do not think the majority of the playerbase is capable of deterring an atmospheric sabotage let alone fix it. Atmospheric traitoring is also tiresome and boring for a majority of players. Maybe we can re enable it when we have more interesting gasses in. Anyway...
-The existence of this job will make it easier to add an "atmo" access in the near future when we have air alarms properly configured so that the engineers can't horribly mess with atmos while techs are working on it. It will also be a necessary access for ai and silicons. 
If you'd like me to argue more for the existence of this job in the current state of the game I can however I feel these points are concise enough to cover most of my major pain points. 
-skub?

### CODE REVIEW

**Comment by TimrodDX** [comment]
I just saw this, and while I think it's good, a couple of points I wanted to make:

- This should probably have Atmos airlocks PRed, so that I can update Delta to use them.
- According to the original job manifest I made for Delta, there's 3 Atmos and 4 Engineers. I suppose this could be changed to 3A/5E.

**Comment by Emisse** [comment]
ill add the airlocks and stuff when we do atmos accesses so we can all in one it with air alarms, this is just to get it in initially

**Comment by mirrorcult** [comment]
i don't personally think atmos tech should be added with how it works in tgcode, and instead the engineering delineation should be between 'mechanics'(fixes breaches/damage, does atmos) and 'power engineers' (sets up/maintains engines, fixes wires/apcs/substations)

**Comment by Elijahrane** [comment]
> i don't personally think atmos tech should be added with how it works in tgcode, and instead the engineering delineation should be between 'mechanics'(fixes breaches/damage, does atmos) and 'power engineers' (sets up/maintains engines, fixes wires/apcs/substations)

You have to question why atmos tech was added in the first place; I think it's because it's something with a pretty niche appeal, but it's still essential. Atmos tech helps ensure it's more likely that there are people that understand atmos with access to atmos. Having just 1 engineer job is fine IMO, as is splitting off atmos tech. I think there's a possible problem with that proposal because it merges the easiest job of engineering (fixing structural damage) with the hardest (atmos). I don't think it's an improvement on either of the other two ways of doing it.

**Comment by Fishfish458** [comment]
Considering how often I've seen atmos being sabotaged or down right not worked on,  I think it makes sense to have an atmos tech be a separate job with a separate access level to tighten down responsibility over it or blame.

**Pull request merged**
