### PR TITLE
Map Readability

### PR DESCRIPTION
**Pull request by Errant-4**
## About the PR

- Beacon labels on the map are made shorter. New ones should probably aim for a lenght of 6-10 whenever reasonable.
   Short labels make the map more readable, in some cases even when it's zoomed in (see last comparison)

~~- Command beacons are changed to bright yellow, making them much more readable on the black background~~ Already merged

- "singularity engine" beacon renamed to "PA Control"
   "tesla engine" beacon depreciated

## Media

map_comparison

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
I think shortening "Captain's Room" to just "Captain's" and similar ones is really strange.

**Comment by Errant-4** [comment]
> I think shortening "Captain's Room" to just "Captain's" and similar ones is really strange.

I don't disagree, but what else can they be? Should they just say "Captain" and "Warden" ? I deemed those words too long by themselves to add "'s Room" onto

**Comment by Errant-4** [comment]
I made the CE, CMO and QM labels longer because I did not want the whole thing to be letter salad, Engineering is bad enough already in that respect with the AME TEG SMES

**Comment by Errant-4** [comment]
Wait, I should probably localise the map labels, shouldn't I

**Comment by lzk228** [comment]
#20249

**Comment by Errant-4** [comment]
> Case in point - I cannot say by looking at your screenshot what's under `CMO's Room`. It's probably nothing important, but if that happened to be something I'm looking for? I would see a couple letters of those labels if that was just `CMO`, possibly making it possible for me to figure our the rest of the word.

Fair, I will think about this. Though for the record 
1. this is a VERY zoomed out view, it can't be expected to be always readable without making it so the labels can push each other around (which would create its own issue) and
2. I have already pushed a PR about aspid that makes that specific overlap less of an issue, and will be watching for overlaps more diligently when I touch maps from now. No amount of shortening will resolve poor beacon placement at far zoom levels

**Comment by EmoGarbage404** [comment]
> It's already letter salad, and if you ask me acronyms > overlapping labels any day.

There's gonna be overlap when you zoom out no matter what. When zoomed in, the overlap is very much reduced. The intent behind writing out the names in full is to be more clear, since these are often used by new players who might not be super familiar with the layout of places on a typical station.

> If a player is consulting the map to find out where HOP is, the readability difference between "HOP" and "HOP Office" is zero - you still need to know what a HOP is in order to know what a HOP Office is - the word "office" doesn't add any value.

I mean it's really just a question of technical correctness. HOP is a job: not a location. Furthermore, the inconsistency in the PR between when to omit "room" or "office" is really arbitrary and confusing. Using `HOP's` or something similar as a shorthand is also confusing because it's just grammatically incorrect. HOP's what? 

There's no cost to being slightly more verbose: it's a few characters at worst. I think it's more than acceptable considering that it helps the labels actually communicate what they're supposed to be doing, rather than being vague and potentially being confusing.

**Comment by Aisu9** [comment]
wouldn't having different color of walls and all be more easily readable that 10 text box overlapping each other?

**Comment by Errant-4** [comment]
I have uploaded a screenshot of a different, updated look. I have made the labels even shorter in many places. I welcome outside opinion on whether or not that makes a difference at all, since these labels are now less "clear" and proper-looking, or if the first one was better and just needs to be consistent

**Comment by Errant-4** [comment]
Ok I think it's done. (Almost. if anyone has a better short name for Checkpoint I'm all ears)
Please see new image comparisons/review the list of names under Files Changed

I do agree that in many cases, these short descriptions are not ideal. I would LIKE to have proper descriptions. But superimposed map labels just isn't the place for them, they get in the way of functionality too much. While we have this system as is, I think terse labels are the way to go

Perhaps in the future we could switch to icons, which would always have the same predictable size, with a legend sidebar where the proper names can be listed, or maybe map labels with line breaks so they don't sprawl so much horizontally, and/or labels that can push each other away when zoomed too far out. But for now, this is what we have

**Pull request merged**
