### PR TITLE
combine same-tile explosions in the same tick

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
if multiple explosions happen in the same tick, and theyre within a tile of eachother, they will combine TotalIntensity making a bigger explosion.

## Why / Balance
previously if you set off an entire c4 bundle you get a tiny explosion that instagibs anything inside it due to the stacking of 1 c4 damage x12
now it scales intensity so you get up to MaxIntensity damage

same argument for hot soup, instead of instagib from ied in a tiny radius you get a big fireball that does small damage

it also might help with processing overhead a bit since its just checking (usually) 1 explosion and seeing if it fits instead of having to handle each one individually

it also means less noise spam

## Technical details
changed queued explosions from being a Func<Explosion?> to a new class QueuedExplosion, which is the args of SpawnExplosion (nothing else was used so using Func was unnecessary). there is also a hashset _queuedExplosions which it looks up (i assume a queue cant be non-destructively iterated idk) nearby explosions in this tick

it might be worth also increasing maxIntensity somewhat (though not just adding since that would roughly make stacked explosion sizes the same as before) so it also increases damage not just radius

## Media

clip from livrah's hot soup video real :trollface: (signal ied is vv'd)

https://github.com/space-wizards/space-station-14/assets/39013340/8604a757-8bae-4d39-883a-660648da7176

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
its private so no

**Changelog**
:cl:
- tweak: Multiple bombs exploding at once on a tile now combine to have a larger explosion rather than stacking the same small explosion.

### CODE REVIEW

**Comment by Holinka4ever** [comment]
What if a pep combine it with syndicate bomb?
Wouldnt it will lead to MORE devastatation?

**Comment by deltanedas** [comment]
can only combine same explosion type so c4 bundle and minibomb are separate

**Comment by K-Dynamic** [comment]
God if only some bombs fly out in little clusters and also explode as they cook off

**Comment by notquitehadouken** [comment]
me buying 3 minibombs and destroying half the station:

**Pull request merged**
