### PR TITLE
Hardsuit Fabricator

### PR DESCRIPTION
**Pull request by SpartanKadence**
## About the PR

The hardsuit fabricator is a new machine that can be added to maps, particularly EVA rooms, to allow heads to create extra or spare hardsuits for their workers, allowing for more engineers, salvagers, or security out in space at once. 

**Media**

https://user-images.githubusercontent.com/113391284/236366019-fa42c3c0-b073-4480-8861-67e5d5a3f1d7.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Kade
- add: The hardsuit fabricator is a new machine that can be found within stations that can allow the creation of extra hardsuits for the crew!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Is there a reason this is a separate machine instead of just being part of the exosuit fab?

**Comment by SpartanKadence** [comment]
> Is there a reason this is a separate machine instead of just being part of the exosuit fab?

Well, I thought the exosuit fabricator was more for the mechs. At least that's what I made it out to be.

**Comment by EmoGarbage404** [comment]
> Well, I thought the exosuit fabricator was more for the mechs. At least that's what I made it out to be.

on tg, it's used for mechs, borgs, and modsuits. 

Sci already has a lot of lathes, i don't think there's really a justification for another one.

**Comment by SpartanKadence** [comment]
> on tg, it's used for mechs, borgs, and modsuits.
> 
> Sci already has a lot of lathes, i don't think there's really a justification for another one.

Alright, I'll keep that in mind. Would that be something better to PR then? Probably have it be a new research section to unlock?

**Comment by mirrorcult** [comment]
i really do not want this, if hardsuits are to be available it should be through other means, not a lathe

**Comment by SpartanKadence** [comment]
> i really do not want this, if hardsuits are to be available it should be through other means, not a lathe

Reasonable.

**Comment by EmoGarbage404** [comment]
i would recommend adding tech for these, yeah. Maybe even have a cargo crate for basic EVA, if you intent is making hardsuits more renewable.

**Pull request closed without merging**
