### PR TITLE
Fix: Chameleon Projector no longer instantly reverts a damaged user

### PR DESCRIPTION
**Pull request by thetolbean**
## About the PR
Modifies the chameleon projector to not take into account the users initial health, allowing damaged users to transform into small items.

## Why / Balance
Bug reported in https://discord.com/channels/310555209753690112/1300224084302495827
Simplifies its criteria and prevents user confusion.

## Technical details
Adds a new field to `PolymorphPrototype.cs` in order to determine if the disguise should take the users damage on disguise start.
    - Does not prevent the disguises damage from transferring to the user.
Changes polymorphs revert damage from set to change in order to prevent damage from being deleted.

## Media
https://github.com/user-attachments/assets/d4ff1ab9-050f-466c-b418-872263384b50

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- fix: The chameleon projector no longer instantly reverts damaged users.

### CODE REVIEW

**Comment by JIPDawg** [comment]
The only issue I see with this is that your health status reverts to "Normal" despite actually being "Ok".

**Comment by deltanedas** [comment]
still wild that chameleon projector rewrite hasnt been merged yet

**Comment by thetolbean** [comment]
> The only issue I see with this is that your health status reverts to "Normal" despite actually being "Ok".

Yes, i do agree.
I could scale the users initial damage to an equal percentage of the disguises health, but then I would have to do some trickery when reverting the user

**Review by deathride58 — APPROVED** [review]

**Comment by thetolbean** [comment]
There are a few issues im having with this implementation:
1. The disguises speed is unaffected by the users slowdown caused by damage, and can be used as a "speed boost"
2. The health icon does not represent the users health, but instead only the disguises health
3. When very hurt, you can take enough damage to down or kill yourself depending on what you disguise as (haven't found an item that gibs you)

Not sure if these issues are big enough to be blocks, but I plan on trying to find a solution

**Comment by chromiumboy** [comment]
#27111 resolves the issue that this PR addressed, as well as a few others

**Comment by thetolbean** [comment]
Closing due to #27111 being merged

**Pull request closed without merging**
