### PR TITLE
Modern Hair Tweak

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Tweaks modern hair emisse don't leave me here emisse cough cough emisse slams door

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Alekshhh** [comment]
what does that rsi validator even mean

**Comment by Emisse** [comment]
this doesnt need a changelog

**Comment by Emisse** [comment]
this still has the weird lump hunchback look

**Comment by Alekshhh** [comment]
delusion has enter the bloodstream

**Comment by Emisse** [comment]
rsi validator doesnt like you because you will not bend the knee

**Comment by Alekshhh** [comment]
a god does not fear death

**Comment by Emisse** [comment]
it still sticks out very far

**Comment by Alekshhh** [comment]
I'm gonna stick my thumbs into your eyes

**Comment by Alekshhh** [comment]
image
is this fine

**Comment by Alekshhh** [comment]
image
or this

**Comment by Emisse** [comment]
no it doesnt really follow a natural slope, and the stay pixel sticking out doesnt look like fritz it just looks like a fucked up hat

**Comment by Emisse** [comment]
look at the original hair

**Comment by Alekshhh** [comment]
image

**Comment by Emisse** [comment]
that shape is better

**Pull request merged**
