### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by Psychpsyo**
## About the PR
This just fixes a few of the warnings.

## Why / Balance
Because they should all go away. I don't like how many there are.

## Technical details
I just looked at the compiler warnings and did what Visual Studio / the obsoletion messages said to do.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
No.

### CODE REVIEW

**Comment by mirrorcult** [comment]
a lot of these arent actual compile warnings and just IDE style warnings, which should have a lot lower priority to actually fix (and really dont need to be fixed at all except in refactors touching that code)

**Review by AJCM-git — CHANGES_REQUESTED** [review]
Yeah, the ones that are valids in here are the obsolete methods removal and unused deps removal, get rid of everything else

**Comment by Psychpsyo** [comment]
> Yeah, the ones that are valids in here are the obsolete methods removal and unused deps removal, get rid of everything else

Done.

**Review by DrSmugleaf — APPROVED** [review]

**Comment by AJCM-git** [comment]
@Psychpsyo can you solve conflicts? these changes seem fine (tho do remember to do a do-over after merging master since some patterns have changed)

**Comment by Psychpsyo** [comment]
> @Psychpsyo can you solve conflicts? these changes seem fine (tho do remember to do a do-over after merging master since some patterns have changed)

Probably won't be happening since I'd need to set up a bunch of stuff for that again, sorry.

**Pull request closed without merging**
