### PR TITLE
Update gases.yml

### PR DESCRIPTION
**Pull request by OrangeMoronage9622**
Made frezon worth more to encourage more atmospheric engineers to create it.

## About the PR
Increased the price by 1

## Why / Balance
Frezon is rarely made, we need more encouragement to create it.

## Technical details
Increased an integer by one.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None
This will be posted in #codebase-changes. -->

**Changelog**

### CODE REVIEW

**Comment by ZombieChibiXD** [comment]
Is.. this a joke PR?

**Comment by cdb0499** [comment]
let's get this merged

**Comment by lzk228** [comment]
> Is.. this a joke PR?

if this was a joke PR, they would set price to 99 gazillions or something

**Comment by deltanedas** [comment]
lmao

**Comment by slarticodefast** [comment]
No joke PRs, please. If you got something to say about the balance, do it in the comment here #32407

**Pull request closed without merging**
