### PR TITLE
Remove starvation damage

### PR DESCRIPTION
**Pull request by PJB3005**
Bottom text

:cl:
- remove: Removed starvation damage

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
i hate to do this peanut jutter but you're slammed with the state-mandated DNM label until you provide a bare minimum reasoning for your PR.

**Comment by PJB3005** [comment]
Ok emo told me I actually need to give a reason for my PR so I'm gonna pretend I didn't just open this on a 2-minute YAML edit shitpost and uhhh

Idk starvation damage just doesn't feel like an interesting game mechanic. It feels way too aggressive and other punishments like massive slowdown seem sufficient to incentivize people to not starve themselves. People dying from having to go AFK for 5 minutes sucks.

**Comment by Kadeo64** [comment]
> i hate to do this peanut jutter but you're slammed with the state-mandated DNM label until you provide a bare minimum reasoning for your PR.

reasoning: do you starve to death in 3 hours

**Comment by metalgearsloth** [comment]
> > i hate to do this peanut jutter but you're slammed with the state-mandated DNM label until you provide a bare minimum reasoning for your PR.
> 
> reasoning: do you starve to death in 3 hours

This is a video game don't spout realism.

**Comment by metalgearsloth** [comment]
I think food + drink + hunger + thirst values are still fucked and no chef rework in the near future so it should probably just be agonising but not lethal from an afk.

**Review by metalgearsloth — APPROVED** [review]

**Comment by Rainbeon** [comment]
I would rather the other PR where it's shown on the Health Analyzer get merged over the one where it's just straight up removed, starvation damage only gets to the point that it kills you after like 90 minutes unless you or someone else speeds it up for you

The only real annoying thing about it to me is that chronically SSD people starve all around the same time towards the shift's end

**Comment by Kadeo64** [comment]
starvation/dehydration slowdown is enough of a downside tbh

**Comment by PJB3005** [comment]
> I would rather the other PR where it's shown on the Health Analyzer get merged over the one where it's just straight up removed, starvation damage only gets to the point that it kills you after like 90 minutes unless you or someone else speeds it up for you

I just had the worst experience ever in medbay of having somebody come in that threw up so much they were at 0 hunger. I then shoved like 10 bun cakes in their mouth in the bar and it STILL didn't get them above the threshold to avoid dying.

**Comment by Carolyn3114** [comment]
good change

**Comment by Brandon-Huu** [comment]
Solution: Eat food

**Review by DogZeroX — APPROVED** [review]

**Comment by potato1234x** [comment]
it should just make you lose a capped amound of health then stop

**Comment by DoutorWhite** [comment]
I find it very annoying how quickly you starve to death, and it's always a pain to come back to life, as you're in a loop of alive and crit until someone feeds you properly. I still think being hungry should be debilitating and cause damage, maybe just be slower and have a damage cap.

**Review by Hmeister-real — APPROVED** [review]

**Comment by metalgearsloth** [comment]
She justified, if someone wants it tweak it to not be cancer.

**Pull request merged**
