### PR TITLE
Minimalist Action Bar

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

The action bar has gotten a bit of a minimalist redesign! Instead of a bunch of bulky slots, the actions are automatically added along the top or side of the screen (depending on your HUD layout). The first 10 are assigned hotkeys and the rest can simply be clicked.

The action bar also no longer have backgrounds unless there is actually an action present. Additionally, the background is no longer overlaid on top of the icon texture (how has no one noticed this fml). Dragging actions additionally now swaps the two actions instead of just deleting one.

Chucked action pages because they were honestly peak smelly and unused by everyone. Dear god... why...

also fixes the hotbar shortcuts always showing 1-9+0 instead of the actual keybinds.

## Media

image
image
image

https://github.com/space-wizards/space-station-14/assets/98561806/675cd4bc-0170-4ad5-a20c-eb375f2d3ba1

## Breaking changes

**Changelog**

:cl:
- tweak: The action bar now dynamically expands to the amount of actions present. 
- tweak: The action bar is now positioned along the top of the screen in the separated UI mode.
- fix: Fixed the action bar not displaying the correct hotkeys for actions.

### CODE REVIEW

**Comment by forgotmyotheraccount** [comment]
sayonara, 7 empty action slots filling up the left side of my screen...

**Comment by VasilisThePikachu** [comment]
For separated layout, I would love to see the option to have it either at the top or the side. It kinda looks weird at the top. Why is it different from standard layout?

**Comment by EmoGarbage404** [comment]
> For separated layout, I would love to see the option to have it either at the top or the side. It kinda looks weird at the top. Why is it different from standard layout?

because the standard layer has dead space along the sides of the screen, it made more sense to position the UI to minimize that space. With the separated layout, it made more sense to place them along the top, as the visual space there is frequently unused. 

Additionally, I plan to introduce a corner-inventory HUD in the separated mode, like SS13, and placing the actions along the top better facilitates that.

**Comment by ZeroDayDaemon** [comment]
Does this remove the feature of removing unwanted things from the action bar (PDA Light when you have flashlight/hardsuit)?

**Comment by EmoGarbage404** [comment]
> Does this remove the feature of removing unwanted things from the action bar (PDA Light when you have flashlight/hardsuit)?

Nope. You can still just right click them and the HUD will adjust automatically. You can readd it via the action menu, just like before.

**Comment by notquitehadouken** [comment]
delicious, no more stinky action bar having 95 unused slots

**Comment by Titian3** [comment]
Hey looks really nice! I checked it out to give it a whirl and found a couple of issues. 
- In situations where the hotbar exceeds 9 its no longer paginating, eg items keep going and don't have hotkeys attached:
image
- The missing pagination might also have the added effect of it not scaling on smaller displays too?
On a smaller display, hotbar is overflowing rest of UI scales down.
image
- When you remove an item from the hotbar it looks like there is no way to add it back on to the bar as a new item, only replace existing ones, eg if i remove the pda light from the previous one and i have to drag it back it can only replace.
---
Ok half way through writing that i found there was an invisible box at the bottom it could be added to, maybe it needs a background/ plus to highlight tha'ts where new items come back on to the bar?.
image
image
- The main reason, my largest pet peeve in the game right now, Does this resolve the random assignment of hotbars at round start eg always in this order again?
It seems to but not sure if that is just dev mode...
image

**Review by Emisse — APPROVED** [review]

**Comment by Emisse** [comment]
works for me need someone familiar with ui to look at

**Review by keronshb — APPROVED** [review]
image

**Comment by Vytian** [comment]
Downstream I'm having an issue as a med player with my hotbar restructuring every time I pick up my pda to use as a scanner. Can there be a way to lock slots, or at least make it so when the item in a slot disappears it doesn't shift everything below it up?

For instance, this is my usual hotbar setup...
image
But after putting my pda in my hand to use its med scanner my hotbar restructures to this
image

**Pull request merged**
