### PR TITLE
Boxstation.

### PR DESCRIPTION
**Pull request by SweptWasTaken**
Yes i'm doing it. Yes it's torture.

I know there's a ton of reasons why I should or shouldn't do it but I don't really care. I'm doing it and i'm making this pr so that i'll stick to it.

I'm only doing tiles, airlocks, walls and tables right now so that the general layout is complete. Once that's done i'm hoping to get some help on wiring, atmos and disposals. 

Let me know if you want to help, i'm open to coordinate.

Spotify_2020-09-16_11-45-20

For reference, i'm mixing and matching from Beestation and tgstation's Boxstation layout. https://affectedarc07.github.io/SS13WebMap/BeeStation/BoxStation/ 
https://affectedarc07.github.io/SS13WebMap/TG/BoxStation/

Mapping guide -> https://hackmd.io/@ss14/docs/%2F1CmC4RpnStSAIOKWWa1fyw

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
@Kmc2000

**Comment by Kmc2000** [comment]
Sure, show me how and I'll be happy to help

**Comment by SweptWasTaken** [comment]
Edited the gameticker so you'll load directly into the map from this fork

**Comment by DrSmugleaf** [comment]
> Edited the gameticker so you'll load directly into the map from this fork

This is now done by changing the GameMap CVar default value in https://github.com/space-wizards/space-station-14/pull/2105/commits/6f2c387af79331a8e30b464f5a3092e5ca53c7c8 to boxstation.yml

**Comment by SweptWasTaken** [comment]
Closing as i've completely fucked this PR. I'll make another PR when Boxstation is finished.

**Pull request closed without merging**
