### PR TITLE
Added Role Time Requirements to Ghost Role Reinforcements and Holoparasite/clown.

### PR DESCRIPTION
**Pull request by JIPDawg**
## About the PR

I've added a 10 hour Overall play time requirement and a 5 hour Security playtime requirement to all Ghost role Reinforcements except the Syndicat. The Syndiecat has just a 5 hour overall playtime requirement.

I've also added the 10 and 5 hour requirements to Holoclown and Holoparasite.
## Why / Balance

I recently witnessed a newkie round where the last Operative and Monkey discovered their agent used 0 TC. They then spent **65 TC** on an assault borg. Once the raffle ended the borg wordlessly rolled toward the crew, fumbled around and went down. It was then repaired, but the player either ghosted or closed the game. I can't imagine this was enjoyable for either the syndie borg or the nukies.

This can lead to extremely frustrating moments for both parties (**especially** when you spend ~80% of your TC as a last ditch effort). Hopefully adding a bit of play time required will allow for slightly more enjoyable experiences for both parties.

I elected to use Security as _sometimes_ combat becomes inevitable but it's certainly open for discussion.

I think an argument could be made to extend this to Ninja/Dragon/LoneOp as these are highly coveted ghost roles, but since they rely on themselves and not a team the stress of not disappointing others is lessened. However I do understand how frustrating it is to lose a raffle only to watch the Ninja not know about their station pointer or how to use their jetpack and drift endlessly in space.
## Media

image

## Requirements

- [ x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Added a 10 hour overall and 5 hour security playtime requirement in order to participate in raffles for ghost role reinforcements and Holoparasites/clowns. Syndicats will only require an overall playtime of 5 hours

### CODE REVIEW

**Comment by Everturning** [comment]
make ninja require salv time maybe? plenty of time to learn how to use a jetpack, handle space, and such. might even need to give it nukeop time, since, uh, pinpointers are kinda necessary in that job. kinda.

**Comment by deltanedas** [comment]
add clown time to holoclown :trollface:

**Comment by saga3152** [comment]
I'm not sure you need to have sec time for holoparasite, you only punch and some people don't play security amd forcing people to play roles tgey don't want is a bad thing

**Comment by keronshb** [comment]
We're relying on role timer too much and forcing new players away from the game.

Yes it is frustrating if a new player gets a ghost role, but it's also extremely frustrating to not even give them the chance to play these roles.

**Comment by ArtisticRoomba** [comment]
IMO there shouldn't be playtime requirements for these ghost roles. 

Sometimes extremely funny and memorable things happen when new players win the raffle. Pushing them away from these roles (arguably after a death) just increases the frustration they experience. 

"Man, there's a cool ghost role, but because I'm so new, I don't even get a _chance_ to participate in the raffle."

We already have enough timegates on roles. It would be silly to add these on. I can see this for an MRP market but in general it's quite silly.

**Comment by JIPDawg** [comment]
> We're relying on role timer too much and forcing new players away from the game.
> 
> Yes it is frustrating if a new player gets a ghost role and they don't know how to play, but it's also extremely frustrating to not even give them the chance to play these roles.
> 
> There's so much time sink you have to put in the game already it's ridiculous.

I do want to point out that this is only for holo's and reinforcements, all other mid round antag / free agents have no timers leaving plenty other roles for people to grab. I would argue that reinforcements themselves (aside from ancestry) are pretty costly and if you are spending the TC on them you are desperate enough to need some decent help \ just want them to do your objective while you screw around.

I do agree in regards the game being a massive time sink, but I don't think a minimum of 10 hours (5 overall and 5 cadet) is asking to much, but I personally don't mind lowering the requirements. The purpose of this is to avoid situations described above where someone doesn't bother to RP or speak get frustrated and leave. I would argue winning a raffle with 8 others in the raffle and getting to play for 5 seconds only to die again is equally frustrating for new players. Granted this was a very specific instance and is not what happens every time. Also in this instance I'm sure that borg player received several AHelps so this may also ease admin load.


> I'm not sure you need to have sec time for holoparasite, you only punch and some people don't play security amd forcing people to play roles tgey don't want is a bad thing

That's probably a fair change.

**Comment by beck-thompson** [comment]
> I would argue winning a raffle with 8 others in the raffle and getting to play for 5 seconds only to die again is equally frustrating for new players

I really agree with this! Its not fun to be a new player, joining a raffle (Not *really* knowing whats going on) and then instantly die or mess up. I honestly think it would be stressful and unfun for almost any player. Giving a minor time gate seems fine to me (What time and what department specifically I do not know).

**Comment by cohanna** [comment]
>What time and what department specifically I do not know.

100hours, boxer :godo: 
In all seriousness it should be a general playtime requirement. Like 5-10ish hours maybe?

**Comment by Everturning** [comment]
I've said it in an issue before: there once was a ninja who did not know how to see. their. objectives. they had to ask in LOOC. they saw "complete your objectives", they won the raffle, they got to the station... and they spent all that time not knowing how to view their objectives, a fundamental part of antagonist gameplay. that, that is why I am in support of this.

I'm fine with these staying as they are:
Space Dragon: Simple, objectives are pretty intuitive and easy to accomplish without needing to see them
Revenant: No objectives, and gameplay is also very intuitive.
Skeleton: Basically a crew member, just cant heal by normal heals and has space protection.

I want a timer for these:
Lone op: 4x harder than nukeops. It needs to have an hour or so of nukeop time so that you know how to do the base functions of the detonation. No joke I remember like 3 loneops who each didn't know how to use nuke or nuke disk.
Ninja: See above story's reasoning.
Insert third role here: because of reasoning placed here (I forgot if there was another role I wanted change)

**Comment by ArtisticRoomba** [comment]
Possibly the relevant antagonist guide could open when you first play the role, or have a (?) button next to the ghost role? We have relevant guides for nukies and the Space Ninja.

**Comment by lanse12** [comment]
> 15 hours into Space Station 13, I couldn't even figure out how to put something on the ground without throwing it, or how to not die to lack of oxygen. I don't think baring people who just started SS14 from playing high-difficulty/highly coveted antags is a bad move.

5 hours into ss13 i was soloing megafauna and almost ascending as here

**Comment by deltanedas** [comment]
dragon specifically needs a guidebook to open since its not communicated at all that you get deleted if you dont make a rift

**Comment by JIPDawg** [comment]
> dragon specifically needs a guidebook to open since its not communicated at all that you get deleted if you dont make a rift

I agree. I might look over it later tonight. Also I'm contemplating removing the time requirements for kobold\ monkey. Both are supposed to be inept anyways. They can't even shoot guns.

**Comment by slarticodefast** [comment]
Hey, I brought this up for maintainer discussion and we decided not to merge this PR for the reasons keronshb already mentioned. We rely on role timers a lot at already and the amount of content locked behind them is very high compared to other games.
Thank you for your contribution.

**Pull request closed without merging**
