### PR TITLE
Cursed Mask

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR

Adds the golden mask. This mask, when put on, changes to a random expression:
- Neutral: No effect.
- Joy: 15% movement speed increase
- Despair: Blunt damage resist comparable to a sec vest.
- Anger: Turns evil, taking over the wearer and making them attack anyone nearby. Once removed, the player is returned to their body.

the mask can't be forced onto a player, only willingly worn. It can't be taken off unless the wearer is unconscious.

credit to vgstation for sprite, name, and description

## Why / Balance

i wanted this as salvage treasure for the upcoming rework but i scope creeped is so hard that i figured this item specifically needed to be a separate thing. it'll get

## Media

image

https://github.com/space-wizards/space-station-14/assets/98561806/ed4aa99c-d82b-4114-95d7-b0eb70f54259

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl since not integrated

### CODE REVIEW

**Comment by mirrorcult** [comment]
COME, NEREVAR. FRIEND OR TRAITOR, COME

**Comment by Cojoke-dot** [comment]
>This mask, when put on, has a 25% chance of turning evil

Is this every time you put it on or a 25% chance for a mask you find to be evil?

**Comment by EmoGarbage404** [comment]
> > This mask, when put on, has a 25% chance of turning evil
> 
> Is this every time you put it on or a 25% chance for a mask you find to be evil?

every time you put it on

**Comment by TheShuEd** [comment]
I think this is a controversial item from a game design point of view.  This is literally a one-time round removal experience for a new player, then simply no one will wear it, and the item generally ceases to provide a new gaming experience

**Comment by TheShuEd** [comment]
I would suggest this mask to add some positive effects that might be worth the risk of wearing it.  For example, some useful active ability.  I would make it possible to “convert” not at the moment of putting it on, but conditionally every minute while you are wearing it, and also add the ability to remove it from the wearer by force, returning the player’s sanity.

**Comment by TheShuEd** [comment]
In this scenario, it would work as a risk + reward, and provide an interesting experience of disarming a distraught player and bringing him back to consciousness.

In this variant, it would work as a risk + reward, and would provide an interesting experience of disarming a distraught player, and bringing him back to consciousness. Right now, the scenarios that gameplay with this mask can take are extremely predictable and unreplayable

**Comment by Guestin366** [comment]
What if someone just uses this to "turn" on purpose in the middle of cargo? Is that banable?
Because if not, it's going to be an obvious griefer tool. If it is, it has no point in being an item past being a one time gotcha for new players.

**Comment by BolloTea** [comment]
It might be a stupid idea, but why not make more varieties of such treasures (not necessarily a mask) and give them different effects, where mastery will be one of them.  This way there won’t be a big meta and deliberate use to the detriment of players will also be reduced to a minimum, because the effect of such wonders will be different.  For example, as with artifacts

**Comment by BolloTea** [comment]
If you start to develop this topic a little, then you can have a good time on it.  It is not necessary to dwell on positive or negative effects, because unlike artifacts, such curiosities can have a neutral-stupid character (for example, give a 20% chance of innocence to the player for an n-amount of time or allow you to see ghosts (without communicating with them).  Stupid? Sure. Fun? Maybe. But again, if you don’t like the effect, you can always sell it).

**Comment by beck-thompson** [comment]
> It might be a stupid idea, but why not make more varieties of such treasures (not necessarily a mask) and give them different effects, where mastery will be one of them. This way there won’t be a big meta and deliberate use to the detriment of players will also be reduced to a minimum, because the effect of such wonders will be random. For example, as with artifacts

That seems like a very good idea! Perfect solution to the griefer issue while also being more interesting.

**Comment by bruhmogus** [comment]
holy shit this is like the one time i will agree on emo with anything PLEASE add this i NEED funny golden objects for my trinket room

**Pull request merged**
