### PR TITLE
Engineering techfab.

### PR DESCRIPTION
**Pull request by Adrian16199**
## About the PR

Implements engineering techfab.
Could probably balance the fact that autolathe has just random stuff in it after a discussion.
## Why / Balance

Okay so. Engineering as it currently stands, is uncapable of fixing most basic equipment and if somethin needs to be fixed that isnt just a mere electronic, they pretty much require the help of science to just do basic job which they were hired for.
What I propose is making an engineer techfab and include basic circuits and tools that engineers would find essential to fix.
-Gives engineers somethin to do aka they can make more stuff and can fix the departemental equipment if there would be an explosion instead of a scientist doing it.
-The science would still do the neccesary upgrading because their protolathe would upgrade with science etc while engineers just ensure that the station is intact.
-It could be simply placed where the autolathe was in engineering.
-Could remove some stuff from autolathe to not make it as big of a mess and require engineering to make it instead of science being more of engineers than the engineers themselfs. (This change would require massive mapping so probably a PR after this would be merged [hopefully] to get rid of stuff from the autolathe itself)
Thats pretty much most reasons that I was able to think of as it currently stands.
The PR is a draft to ensure that anyone who comments, I would be able to read and reflect upon or perhaps be reminded that I forgot to add somethin that an engineer could probably need/not need or dare I even say, discuss the matter of adding a techfab for our engineers.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Cojoke-dot** [comment]
This is just the autolathe and circuit imprinted with a couple of things cut out... can you not just go to sci?

**Comment by CyberDuck-Git** [comment]
> This is just the autolathe and circuit imprinted with a couple of things cut out... can you not just go to sci?

Still, it’s better than nothing. In the future, it will be possible to add new items for printing, specifically for engineers

**Comment by Killerqu00** [comment]
finally

science shouldn't produce things

**Comment by Cojoke-dot** [comment]
> finally
> 
> science shouldn't produce things

sci has to have at least one useful function...

**Comment by Killerqu00** [comment]
> > finally
> > 
> > science shouldn't produce things
> 
> sci has to have at least one useful function... 

science has lots of useful functions, what do you mean?

**Comment by CyberDuck-Git** [comment]
> > > finally
> > > 
> > > science shouldn't produce things
> > 
> > sci has to have at least one useful function... 
> 
> science has lots of useful functions, what do you mean?

He probably meant techfab, I hope

**Comment by CyberDuck-Git** [comment]
> > > finally
> > > 
> > > science shouldn't produce things
> > 
> > sci has to have at least one useful function... 
> 
> science has lots of useful functions, what do you mean?

He probably meant techfab, I hope

**Comment by Adrian16199** [comment]
Erm, the point of this is to allow engineers to make basic stuff, not make science *never* make stuff, hence why i didnt include a circuit imprinter or protolathe circuit boards in there, to not allow engineers to just build it themselfs and just do the new stuff themselfs. Of course, I would also want autolathe to not be able to make these stuff because..... why can it? And even with the argument of ask someone, then you will have to ask engineers to make you a tool as an example if i were to make this PR full. Hell I even though about getting rid of some basic research like having to research microwave because.... why do you have to make a microwave when it is basic equipment that is neccesary for a job like chef?

**Comment by Adrian16199** [comment]
I mean, if there is a need for interaction then this could be said that this would be part one and then i would make a second part where autolathe would loose the possibility of making tools and you got interaction right there, everyone needs to ask engineers for tools and scientist/engi is still there because they only get basic stuff and if they wanted an upgrade then they still need to talk to the scientists(nerds)

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
The contents of the engie techfab seem to literally just be a bloat-removed autolathe as well as every static option in the circuit imprinter. I don't see how this necessary addresses engineering repairing when compared to just having an autolathe inside of the department.

this just seems to be a way to circumvent interaction with science for things that aren't really necessary (especially for things like the random machine boards)

**Comment by Adrian16199** [comment]
> Member

If the interaction is the main thing regardin it, how about this.
Takin out tools from autolathe so that every single department that wants tools has to bother with engineering.
Getting rid of the circuit boards from the engi techfab so that they still have to bother with science even to just make the basic equipment of a department (or just let science fix it themselfs)
Get rid of circuits from autolathe and basicly make autolathe be a service/cargo techfab.
Another thing to point out is that i wouldnt be doing this solution in one PR just because there would be no way of obtaining tools without mapping the engi techfabs first.

**Comment by Adrian16199** [comment]
> The contents of the engie techfab seem to literally just be a bloat-removed autolathe as well as every static option in the circuit imprinter. I don't see how this necessary addresses engineering repairing when compared to just having an autolathe inside of the department.
 
> this just seems to be a way to circumvent interaction with science for things that aren't really necessary (especially for things like the random machine boards)
 
If the interaction is the main thing regardin it, how about this. Takin out tools from autolathe so that every single department that wants tools has to bother with engineering. Getting rid of the circuit boards from the engi techfab so that they still have to bother with science even to just make the basic equipment of a department (or just let science fix it themselfs) Get rid of circuits from autolathe and basicly make autolathe be a service/cargo techfab. Another thing to point out is that i wouldnt be doing this solution in one PR just because there would be no way of obtaining tools without mapping the engi techfabs first.

**Comment by Adrian16199** [comment]
Because with that logic, everyone has to bother science and not engineering, there is literly zero reason currently to bother with engineering besides 
-There is a big hole in medical, go do somethin about it.
And thats it.
There is no other reason just because science doesnt have an EVA suits otherwise they would have done it themselfs (again)

**Pull request closed without merging**
