### PR TITLE
Change keybindings for paper

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

Honestly I have no idea What is this code.

Paper now requires you to press [ Shift ] + [ Enter ] to make a new line
Paper now finishes writing when you press [ Enter ].

The old option of [ Ctrl ] + [ Enter ] still works if you're used to that . ( i have no idea why )

## Why / Balance

 [ Ctrl ] + [ Enter ] to finishing writing in unintuitive and is horrible for user experience.
 
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Does this break console or anything like that.

**Comment by Brandon-Huu** [comment]
> Does this break console or anything like that.

image
image

Honestly have no idea. When i grep for the hotkey keyword the only places i see it used is in RobustToolbox and in the paper UI

**Comment by metalgearsloth** [comment]
> > Does this break console or anything like that.
> 
> `grep -Rin "MultilineTextSubmit"` image
> 
> `grep -Rin "TextNewLine` image
> 
> Honestly have no idea. When i grep for the hotkey keyword the only places i see it used is in RobustToolbox and in the paper UI
> 
> I'll test

Just check announcements console + the actual console ingame and good enough.

**Comment by Brandon-Huu** [comment]
Tested it with News Management console. It works fine. 
[ CTRL ] + [ Enter ] Doesn't create a new line unlike how it does with paper

> > > Does this break console or anything like that.
> > 
> > 
> > `grep -Rin "MultilineTextSubmit"` image
> > `grep -Rin "TextNewLine` image
> > Honestly have no idea. When i grep for the hotkey keyword the only places i see it used is in RobustToolbox and in the paper UI
> > I'll test
> 
> Just check announcements console + the actual console ingame and good enough.

Yeah the announcements console and news management console works fine.

**Pull request merged**
