### PR TITLE
Hair Overhaul

### PR DESCRIPTION
**Pull request by Alekshhh**
## About the PR
Resprites every single human hair in the game.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: The legendary John Barber came to Centcomm with a business proposal. All human hairs have been trimmed with love!

### CODE REVIEW

**Review by Peptide90 — APPROVED** [review]
Look great.

Tests failed as you renamed one from coffeehouse to coffeeshop and haven't changed the meta.json. Can just rename it or change the meta 👌

**Comment by lapatison** [comment]
New bald looks extra nice

**Comment by Alekshhh** [comment]
modeled it after yor mom

**Comment by Equivocateur** [comment]
Floorlength bedhead turns skirts into shorts"
image

Also floorlength and long bedhead hairstyles have gaps in them near the neck at the front
image
image

**Comment by Alekshhh** [comment]
I regret to inform you that's a coder issue

**Comment by AJCM-git** [comment]
@Alekshhh you coming back to this?

**Comment by Alekshhh** [comment]
moving this to a released branch that does not have a weird submodule problem

**Pull request closed without merging**
