### PR TITLE
Funny mobile

### PR DESCRIPTION
**Pull request by AJCM-git**
## About the PR
Adds a traitor-only catalog entry for clowns

For nerds, this is implemented with (mostly) one component per feature, the new container components are mostly ready for review, its a draft because i still have to tidy some things (see SharedClowncarSystem TODO list)

**Media**

https://github.com/space-wizards/space-station-14/assets/60196617/e7b01086-6568-4ccd-8d76-00aeb6a6a48f

**Changelog**

:cl:
- add: Added fun!

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
holy honk

**Comment by Vaaankas** [comment]
YESSSSSSSSSSS

**Comment by Equivocateur** [comment]
AI BOLT OPEN SM

**Comment by Yousifb26** [comment]
Why does it have to be syndie item? Why not make it spawn in clown town then keep the emag function. We should have a clown car every round for the pure memes it will achieve

**Comment by Equivocateur** [comment]
> Why does it have to be syndie item? Why not make it spawn in clown town then keep the emag function. We should have a clown car every round for the pure memes it will achieve

What part of "be able to forcefully limit movement and actions of any other player during the round with minimal effort" is not traitor-only worthy?

**Comment by Geekyhobo** [comment]
> AI BOLT OPEN SM

just imagine

**Comment by deltanedas** [comment]
ai bolt clown room and fill it with plasma

**Comment by Grigew** [comment]
the animation on the side looks weird, the car shrinks just. It would be better to make its hull just descend

**Comment by metalgearsloth** [comment]
something something split pr

**Pull request closed without merging**
