### PR TITLE
fix ci probably

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
time to wait 2 minutes

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
test failure is out of scope, will try to fix in timer building if i can

**Comment by metalgearsloth** [comment]
> test failure is out of scope, will try to fix in timer building if i can

It was a fix for the ResPath. I'm working on getting that PR fixed as right now it runs locally but immediately fails sandbox when run via the launcher.

**Comment by deltanedas** [comment]
close this if the old code was fine now that the revert was reverted

**Comment by metalgearsloth** [comment]
> close this if the old code was fine now that the revert was reverted

Last time it spontaneously exploded on live so will see.

**Comment by metalgearsloth** [comment]
we feex

**Pull request closed without merging**
