### PR TITLE
Add admin remarks button to lobby

### PR DESCRIPTION
**Pull request by dffdff2423**
## About the PR

Adds a button that runs the adminremarks command to the lobby.

## Why / Balance

Telling players that they need to run a command to view notes about them from
admins is not exactly good UI design. Players should ideally not have to touch
the console.

## Technical details

Adds a single button to the XAML. I also switched `CharacterSetupGui` from manual dependency injection to automatic dependency injection with `IocManager`.

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Aquif
- tweak: There is now a button to view your admin remarks in the character editor, right next to the stats button.

### CODE REVIEW

**Comment by dffdff2423** [comment]
The YAML linter failure is nuget's fault, not mine.

**Comment by mirrorcult** [comment]
lobby is a strange place for this, how often are people actually going to care about looking at this

**Comment by Errant-4** [comment]
> lobby is a strange place for this, how often are people actually going to care about looking at this

Every single time I looked at my adminremarks (lack thereof), it was in the lobby

**Comment by dffdff2423** [comment]
> lobby is a strange place for this, how often are people actually going to care about looking at this

I can't really think of another place and I expect it will be used more then the Call Vote button which also exists in the same location. I would wager a bunch of players have never checked their admin remarks just because they don't know how.

**Review by lzk228 — CHANGES_REQUESTED** [review]
really should be check for SeeOwnNotes cvar

**Comment by Mervill** [comment]
It might actually be better to put this button in the escape menu (or in a submenu thereof).

**Comment by UbaserB** [comment]
> It might actually be better to put this button in the escape menu (or in a submenu thereof).

I agree

**Comment by dffdff2423** [comment]
> > It might actually be better to put this button in the escape menu (or in a submenu thereof).
> 
> I agree

I was originally going to do that but I am fairly certain that it is not accessible from the lobby which would be the main place people would view them. If I am wrong about this I am happy to change it.

**Comment by Mervill** [comment]
You're correct that the escape menu isn't available in the lobby screen - I never realized that.

**Review by SaphireLattice — APPROVED** [review]
While I completely and fully agree that this functionality needs to be exposed to players, I don’t think this is a good place for it. The UI is already rather tight as is, and this doesn’t help the crowding.

Consider if it can be put either in AHelp, or into the character editor next to the stats. If it stays in lobby, make sure smaller game window sizes don’t break.

Overall, approved as this really needs to be a thing. While this isn’t perfect in terms of placement, it can be changed easily enough later.

**Comment by dffdff2423** [comment]
In the character editor next to stats seems like a better place. If I remember, I will move it tomorrow.

**Comment by dffdff2423** [comment]
PR description updated to current location.

**Review by SaphireLattice — APPROVED** [review]
Looks good on my end. And hooray updating the injections, thanks. Tested in game, didn't explode.

That would be an approval from me

**Comment by chromiumboy** [comment]
Code looks good and it tested fine in-game

**Pull request merged**
