### PR TITLE
Remove requirement research for laser gun

### PR DESCRIPTION
**Pull request by Daseren**
## About the PR

Normal laser gun already too expensive but it's need technology too, while there is advanced laser gun really not need to make normal laser gun, with this changes it's can be use certain situations like zombie infections if arsenal research not improve yet.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Laser gun removed from arsenal discipline

### CODE REVIEW

**Comment by metalgearsloth** [comment]
Move advanced laser gun up a tier or make it cheaper or smth.

**Comment by deltanedas** [comment]
advanced laser is essentially antique laser so it should be harder to get

**Comment by Emisse** [comment]
advanced laser probably should be moved to t3 or removed from research

**Comment by metalgearsloth** [comment]
@Daseren are you coming back to this mate

**Comment by Daseren** [comment]
Already changes came then not need this anymore.

**Pull request closed without merging**
