### PR TITLE
Quiver Crafting Recipe

### PR DESCRIPTION
**Pull request by FungiFellow**
## About the PR

I added plungers to the quiver whitelist and added a Recipe to craft a Quiver. (Was originally going to be part of a trick arrow PR but that needs sprites and this works so I split it off in hopes to get it added sooner).

## Why / Balance

I feel that it is a good item that should not be restricted to only Admeme or Maints loot
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
## Breaking changes

**Changelog**

:cl:
- add: Added Quiver Recipe, go wild Robin Hood.

### CODE REVIEW

**Comment by mirrorcult** [comment]
split the arrow blacklist change from this PR, its not relevant to quiver crafting

**Comment by Hmeister-real** [comment]
wood doesn't make too much sense imo, maybe plastic or just the cloth and wire? Arrows + Bow are already really wood intensive

**Comment by FungiFellow** [comment]
> split the arrow blacklist change from this PR, its not relevant to quiver crafting

I consider it relevant considering how arrows are balanced around the bow

**Comment by FungiFellow** [comment]
> split the arrow blacklist change from this PR, its not relevant to quiver crafting

#27256

**Pull request merged**
