### PR TITLE
Added Among Us reference plushie

### PR DESCRIPTION
**Pull request by Absolute-Potato**
Added a plushie referencing the hit game, Among Us. Added as a rare spawn in the toy spawn marker, and in the corner of the bridge
**Screenshots**
Having some drinks with nuke
sus
texture
plushie_sus
default spawn in bridge
spawnlocation

~~Ignore the clown thing, I was doing the dev tutorial and figuring out github at the same time~~

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
I give this PR my blessing. Good first PR.

**Comment by metalgearsloth** [comment]
No licensed properties please

**Comment by SweptWasTaken** [comment]
> No licensed properties please

Oh yeah forgot about that

**Comment by SweptWasTaken** [comment]
Closing this. If you do somehow get permission from the original devs, let us know.

**Pull request closed without merging**
