### PR TITLE
Remove roundstart powergamer bait from Youtool.

### PR DESCRIPTION
**Pull request by moonheart08**
Why are we handing out utility belts like candy.

:cl:
- remove: Youtool no longer has free utility belts.

### CODE REVIEW

**Comment by deltanedas** [comment]
maybe put it in contraband so dedicated tiders can still get belts while making it annoying and more suspicious for powergaming hops

**Comment by Ablankmann** [comment]
I don't really understand what this changes, besides making people prioritize looting Maints more often, which is what the average Powergamer is doing anyway for their Multitool and Insuls. This won't effect Powergamers. They'll just use their bags, like they always have been, or start using toolboxes, substituting the region for something else useful, like Medical belts, if they can't find one in maints. The only "Bait" the YouTool has are the things the YouTool advertises in the first place. The _Tools_.






> maybe put it in contraband so dedicated tiders can still get belts while making it annoying and more suspicious for powergaming hops

This doesn't really help, either, because again: The Utility Belt is NOT The Problem, it's the easily accessible tools that entice powergamers to flock to the Youtool. Making the Utility Belt harder to obtain doesn't fix anything, and, unfortunately, I don't have an idea that could fix the problem properly, either. I guess removing Tools from the maint locker loot pool and the You _Tool_ could potentially fix the issue, but this solution just adds more problems (The first one, off the top of my head, is making the jobs of anyone in the tri-state area that DON'T spawn with them unnessisarily more difficult, like... Most of R&D).

**Comment by Tunguso4ka** [comment]
as an powergamer i dislike this PR, but doesn't hate. It will just make me go like 5 metres into the maints where i can easily get my toolbelt.

**Comment by deltanedas** [comment]
this combined with emisse's pr will end powergaming forever

**Comment by moonheart08** [comment]
> I don't really understand what this changes, besides making people prioritize looting Maints more often, which is what the average Powergamer is doing anyway for their Multitool and Insuls. This won't effect Powergamers. They'll just use their bags, like they always have been, or start using toolboxes, substituting the region for something else useful, like Medical belts, if they can't find one in maints. The only "Bait" the YouTool has are the things the YouTool advertises in the first place. The _Tools_.
> 
> > maybe put it in contraband so dedicated tiders can still get belts while making it annoying and more suspicious for powergaming hops
> 
> This doesn't really help, either, because again: The Utility Belt is NOT The Problem, it's the easily accessible tools that entice powergamers to flock to the Youtool. Making the Utility Belt harder to obtain doesn't fix anything, and, unfortunately, I don't have an idea that could fix the problem properly, either. I guess removing Tools from the maint locker loot pool and the You _Tool_ could potentially fix the issue, but this solution just adds more problems (The first one, off the top of my head, is making the jobs of anyone in the tri-state area that DON'T spawn with them unnessisarily more difficult, like... Most of R&D).

making the toolbelt harder to get has nothing to do with making people go away from the youtool

it's called "not handing out powerful items (read: a free inventory space expansion that has no drawbacks) to every tider"

**Comment by potato1234x** [comment]
i feel like this would just end in sci being begged to make belts if tiders are lazy

**Comment by EmoGarbage404** [comment]
> i feel like this would just end in sci being begged to make belts if tiders are lazy

i don't mind that tbh. sounds nice

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by moonheart08** [comment]
> i feel like this would just end in sci being begged to make belts if tiders are lazy

sounds like a good deal to me

**Pull request merged**
