### PR TITLE
Uplink hardsuit bundles rework

### PR DESCRIPTION
**Pull request by AlexUmAndXGabriel08X**
## About the PR

We changed some contents of hardsuit bundles. And added new ones, for example: "Syndicate elite hardsuit bundle"

## Why / Balance

There is a normal blood-red hardsuit bundle which costs 8 TC, and there's an elite hardsuit that costs 10 TC.
For 8 TC you get a hardsuit with mask and gloves. And for 10 TC you get only a hardsuit.
Which made us want to change it and balance a little bit. Now all bundles come with oxygen and nitrogen double emergency tanks, and a syndicate gas mask. Only the hardsuit ones come with combat gloves, and the EVA suit comes with only a pair of budget insulated gloves to show it's "budgetness" (if this word even exists).

Also, syndicate elite hardsuit is now Huge instead of Ginormous. 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Up ones were before PR changes.
Down ones are after PR changes.
image

Contents before and after.
image

Huge syndicate elite hardsuit.
image

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
> is that an implanter? why is there an implanter in the bundle?

me when i don't read the changes (there is no implanter)

**Comment by BolloTea** [comment]
Isn't it too strong for its price?

**Comment by AlexUmAndXGabriel08X** [comment]
> is that an implanter? why is there an implanter in the bundle?

sorry for the last screenshot. It was made to show that the elite hardsuit now can fit in the syndicate duffel bag. And i used reinforcement duffel bag which contains a viper, death acidifier, syndicate survival box and a pinpointer.

**Comment by AlexUmAndXGabriel08X** [comment]
> Isn't it too power for its price?

i don't think so, if you have any suggestions, you're free to write them down there

**Pull request merged**
