### PR TITLE
Kobold Visual Change

### PR DESCRIPTION
**Pull request by Alekshhh**
devi asked

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- tweak: Changed kobolds visually

### CODE REVIEW

**Comment by Partmedia** [comment]
Thanks for your contribution. I'm going to wait to see if we can get a sprite maintainer to swing by and take a look. In the meantime, would you mind taking a look at the [Changelog guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#writing-an-effective-changelog)?

**Comment by UbaserB** [comment]
you forgot the hands and feet 

image

**Comment by RumiTiger** [comment]
Dude, they look like slimes

**Comment by Alekshhh** [comment]
I'll probably work with devi on it since he did some fancy opacity thing I was not aware of

**Pull request closed without merging**
