### PR TITLE
Bug fix for solution regenerators

### LINKED ISSUE #19483: Advanced mop no longer functional
## Description
It appears the advanced mop no longer produces water. It effectively behaves like a regular mop now.

**Reproduction**
Hold advanced mop, wait, become sad.

**Additional context**
Have tried putting in reagents to replace with water, have tried not putting in reagents at all, it just seems that it no longer generates water by itself at all. visually it does seem like it may replace reagents with 'dry mop' instead, so it almost seems inverted.

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

Devices with the SolutionRegeneration component will now regenerating their solutions again

This will close #19483. 

## Why / Balance

Bug fix

## Technical details

Solution regenerators were no longer working because the total volume of reagents (Volume) in the Solution component was still zero after reagents were added to the solution. Consequently the while loop in SolutionRegenerationComponent was always exiting at line 36. 

<s>Volume has been made read only, and is recalculated based on the volumes of the reagents currently in the solution when it is read, so it will always be accurate</s>

If the solution volume hasn't been set when it is time to regenerate, the volume will be initialized

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- fix: Devices which are supposed to internally generate their own solutions do so once more. This fixes things like the advanced mop, cleaner bot, and experimental welder

### CODE REVIEW

**Comment by deltanedas** [comment]
putting file scoping in separate commit from the actual fix makes it much easier to review

**Comment by chromiumboy** [comment]
> putting file scoping in separate commit from the actual fix makes it much easier to review

OK, 'tis done

**Comment by TemporalOroboros** [comment]
I am somewhat concerned about the performance impact of doing this. `Solution.Volume` is used rather often and this makes it significantly slower. There's a reason we cache the heat capacity and that's used significantly less often.

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
Fix the caching rather than removing it.

**Comment by chromiumboy** [comment]
> Fix the caching rather than removing it.

OK, I've reverted the changes to Solution, and instead check if the volume hasn't been set yet in SolutionRegnerationComponent. If not, the volume gets initialized

**Review by ElectroJr — CHANGES_REQUESTED** [review]
This doesn't actually fix the root issue. Something somewhere is causing the volume to be invalid. If the solution is just set via yaml, the ISerializationHooks should be handling that (i.e., the `AfterDeserialization()` function in `Solution.cs`). Are those just not getting called anymore after the serialization refactor?

**Comment by chromiumboy** [comment]
All fair points. It likely is an engine issue, as it seems to appeared after changes were made to serialization

I don't think I have the capability to fix this bug, so I'm going to close this request

**Pull request closed without merging**
