### PR TITLE
Character setup in Lobby UI

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR 

This makes it so that character setup is now in lobby, instead of being a separate screen. This branch was made months ago when UI was frozen, but now that UI changes are allowed, this PR can now exist.

**Screenshots**

image

**Changelog**

:cl:
- tweak: The lobby's character setup screen now sits in the lobby, instead of it being its own screen.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
not really a fan of obscuring the lobby art. :/

**Comment by mirrorcult** [comment]
> not really a fan of obscuring the lobby art. :/

the old character setup obscures the lobby art just as much?

**Comment by vulppine** [comment]
> not really a fan of obscuring the lobby art. :/

image

just click close

**Comment by DogZeroX** [comment]
The old one literally blocks all the lobby

**Comment by EmoGarbage404** [comment]
oh i quite literally did not understand what this pr was doing. I thought that it just made the character setup always present as shown in the screenshot. my bad.

**Pull request merged**
