### PR TITLE
Removes Syndicate headset from uplink and changes TC prices around to be slightly viable

### PR DESCRIPTION
**Pull request by EdenTheLiznerd**
Removes the uplink headset as suggested, changes around TC prices to make a few things more viable

## About the PR

Multiple items have had their stock prices changed and the syndicate headset was removed from the uplink as requested, input is desired alongside _helpful_ criticism

## Why / Balance

I've seen many an item on the uplink not be viable or just be too bad to actually use as a syndie or nukie, this hopefully adds viability to certain items and encourages some use (.45 armor piercing was increased due to armor piercing actually being a bit fucked)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

**Changelog**
 :cl:
- tweak: The Syndicate has changed around their stock prices and gotten rid of some old dusty headsets
<!--

### CODE REVIEW

**Comment by LordEclipse** [comment]
Do syndie reinforcements get a headset when they spawn in?

**Comment by EdenTheLiznerd** [comment]
They do iirc, I'll check

**Comment by LordEclipse** [comment]
> They do iirc, I'll check

It would be about the only singular use case for the headset that I can think of, as their name makes them valid anyway so having the valid headset wouldn't make much of a difference

> They do iirc, I'll check

Traitor syndicate reinforcement does not.

**Comment by EdenTheLiznerd** [comment]
Alright so since it's only traitor it's not problematic?

**Comment by EdenTheLiznerd** [comment]
Ah... So that makes them viable for one use only?

**Comment by LordEclipse** [comment]
> Ah... So that makes them viable for one use only?

Basically, I can imagine a situation in which you buy a reinforcement, and want to get them a headset but can't, but I can't think of a situation outside of that that it would be worth the buy.

**Comment by EdenTheLiznerd** [comment]
I'll wait to see if a maintainer wants it or not, thanks Eclipse

**Comment by EdenTheLiznerd** [comment]
If I can, I'll give them the headset, there's no reason for them not to have it

**Comment by Carmell0** [comment]
This removes headsets but not encryption keys, right?

**Comment by EdenTheLiznerd** [comment]
Yes it only removes the headset

**Comment by Hmeister-real** [comment]
Binary encryption key should be 1 tc , it is more than useless otherwise since it doesn't provide much value for its price.

**Pull request merged**
