### PR TITLE
Adds a miniscule item size for pills and cigarettes

### PR DESCRIPTION
**Pull request by Blackern5000**
## About the PR
Added an item size smaller than tiny for items such as pills and cigarettes.
Miniscule is still 1x1, but can fit in containers that can only hold miniscule items.

## Why / Balance
Storing 300u of chems with bottles in a pill canister is not cool, you could do the same with cigarette packs as well.

## Media
https://github.com/space-wizards/space-station-14/assets/140123969/7747ea04-fc31-4d73-b555-723d282866da
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Items can now be miniscule in size, they still take up the same space as tiny items when loosely thrown into your bag but can fit in more compact places.
- tweak: Pill canisters and cigarette packs can now only hold miniscule items.
- tweak: Pills and cigarettes are now miniscule in size.

### CODE REVIEW

**Comment by deltanedas** [comment]
test fail unrelated

**Comment by EmoGarbage404** [comment]
I feel like this is just patching over the fact that some items are tiny when they really should be small. Having a size category that has the same shape as another in inventory is kinda confusing.

**Comment by deltanedas** [comment]
then bottles would be same as beakers and not a single person would use them

same thing applies for filling a pill bottle with 12 pens, physically impossible. make the pen bigger and now its same size as a half liter beaker

**Comment by EmoGarbage404** [comment]
I pondered this some more and i feel like this isnt the way to fix this issue.

This is basically just rolling back whitelisted containers except in a far more confusing way. I think it'd be better to globally increase a lot of sizes so that theres more room to work on the lower end of things. You can't really have meaningful sizes that are smaller than a single grid square.

I'd rather just see a lot of problematic items being made bigger or whatnot. It could also be worthwhile to increase boxes to perhaps a 4x3 interior to better facilitate that.

**Comment by EmoGarbage404** [comment]
i mean you make the point that a small-sized syringe is illogical but a 50u beaker could always be increased. i don't think that introducing a race to the bottom in terms of size is really a great idea considering that a lot of equipment is already really far on the smaller size without really a good reason. 

Lots of items are small-sized for no reason other than simply inheriting it from BaseItem and i think I'd rather make storage more purposeful rather than just having more classifications that highlight disconnect from the grid size system.

**Pull request closed without merging**
