### PR TITLE
CE hardsuit is fireproof again

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About the PR
Made CE suit fireproof.

## Why / Balance
They got nerfed with #29416, no reason they shouldn't be fireproofed if the atmos one is also fireproof
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 Hmeister
- tweak: The CE hardsuit is now fireproof again.

### CODE REVIEW

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
IMO any hardsuit that has a reasonable amount of heat resist should be immune to fire.

**Comment by Hmeister-real** [comment]
> IMO any hardsuit that has a reasonable amount of heat resist should be immune to fire.

dont want to step on Emisses toes since that would essentially just revert their amazing hardsuit balance PR that is so very good.

**Comment by EmoGarbage404** [comment]
74.3% less snark on balance PRs please.

I get the concept behind giving it to the CE suit, but why to the RD as well? they already have high bomb resist and i don't think a single anomaly type and one rare artifact effect justifies needing fire resistance.

**Review by EmoGarbage404 — CHANGES_REQUESTED** [review]
^comment above

**Comment by Hmeister-real** [comment]
> 74.3% less snark on balance PRs please.

So... our opinions now effect the validity of balance PR's?

> they already have high bomb resist and i don't think a single anomaly type and one rare artifact effect justifies needing fire resistance.

My reasoning is that since atmos fire suits, of which there are multiple in a normal round, is special enough to get a fire resist, why shouldnt a an experimental hardsuit get it too? Also with the thought that "only a single anomaly and one rare artifact get it, so theres too few ways to get set on fire for it to be justified" What about Artifacts that need plasma to activate? Also, technically, atmos only has a few flammable gasses (Plasma,Trit) , so by your line of thinking, they have too few reasons to get fire immunity.

**Comment by deltanedas** [comment]
> What about Artifacts that need plasma to activate?

just dont light it on fire

> they have too few reasons to get fire immunity.

due to a bug with fire not spreading, to properly light a burn chamber atmos has to walk around every tile with a welder until everything has hotspots and is burning. atmos does have a very good reason to stand in fire

**Comment by EmoGarbage404** [comment]
>What about Artifacts that need plasma to activate? Also, technically, atmos only has a few flammable gasses (Plasma,Trit) , so by your line of thinking, they have too few reasons to get fire immunity.

1 anomaly and 2 uncommon artifact effects that can randomly appear in a pool of 27+ VS a job specifically built around dealing with fires that is given specialty firefighting equipment. Additionally, atmos techs often directly interact with processes that require high heat / fire such as gas production and TEG hotloops.

**Review by LankLTE — APPROVED** [review]

**Pull request merged**
