### PR TITLE
Lobby music size and volume optimizations

### PR DESCRIPTION
**Pull request by AJCM-git**
Reduces the size and volume of lobby music files (would post samples in here but github doesnt support vorbis, so check out if the files are too compressed/too low yourself)

### CODE REVIEW

**Comment by ShadowCommander** [comment]
The Absconditus compression is really noticeable with my headphones. Much tinnier sounding.
Atomic Amnesia MMX compression removes a lot of the bass and the compression sound is noticable, but if we really need to lower file sizes, this one sounds ok compressed.
I'm kinda used to endless space being compressed, but the strings and cymbals sound a lot better uncompressed.
The quality in Space Asshole is noticeably worse. It removes a lot of the spatial placement of the sounds and the guitar is very muddy.
I'm also kinda used to Thunderdome being compressed, but hearing it at 1:30, it's quite bad with the compression.

Unless we really need to save on download size, I'd rather not compress the songs.

The volume of all the songs in the codebase right now are pretty much the same except for Thunderdome which is a bit loud. Instead of lowering the volume by re-encoding, I think we should just make the default lobby music volume lower in game.

**Comment by AJCM-git** [comment]
Alright after playing around for a bit i think i got the correct settings so that it sounds good and has a decent file size cut.
For posterity, the command is `ffmpeg -i input.ogg -filter:a "volume={volume}" -c:a libvorbis -ab 45k -ar 44100 output.ogg`

**Review by ShadowCommander — APPROVED** [review]
If/when we get partial updates, I'd like to have the uncompressed versions back, but until then, these sound decent enough while being quite a lot smaller.

**Review by SweptWasTaken — CHANGES_REQUESTED** [review]
I listened to Atomic Amnesia MMX and can hear quiet crackling and some weird tones. I already compressed it when I added it, try compressing the original instead of the version that was in the codebase? 

[Atomic Amnesia MMX.zip](https://github.com/space-wizards/space-station-14/files/6529821/Atomic.Amnesia.MMX.zip)

**Comment by AJCM-git** [comment]
alright i just re-encoded from the originals instead of the ones that were already in the folder, so it should be better. The atomicamnesiammx from the licenses file is a little different from the one that was already there but it should be fine.
@SweptWasTaken Hear any crackling/weird tones now?

**Comment by metalgearsloth** [comment]
@SweptWasTaken also probably good to leave an issue around to revert it so someone remembers to do it when we do get deltas.

**Pull request merged**
