### PR TITLE
Resprite conveyors

### PR DESCRIPTION
**Pull request by lzk228**
## About the PR

title

## Why / Balance

i want arrows to distinguish the side it's moving in

## Technical details

no

## Media

(yeah it's hard to see the arrows because of bad video quality, but it really looks good ingame)

Screenshot_20240908_185619

https://github.com/user-attachments/assets/9d903b7f-8bc3-4f6b-b6c0-5b476770e6f7

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
the arrows should be yellow or something. all the details are washed out and so faded in this resprite that it's hard to identify them.

**Comment by lzk228** [comment]
updated with yellow/brown/orange color

**Comment by slarticodefast** [comment]
Factorio station 14

**Comment by slarticodefast** [comment]
Is it possible to get the arrows to connect properly between conveyors?
grafik

**Comment by lzk228** [comment]
looks like sprites just desynchronized

https://github.com/user-attachments/assets/b9535b22-c0d9-4cc5-8c15-30279ad6b375

**Comment by ps3moira** [comment]
doesn't make sense it's yellow, wouldn't it make more sense to be white?

**Comment by lzk228** [comment]
yellow used to attract attention in a lot of games, and it looks cool on grey conveyor

**Comment by saga3152** [comment]
> yellow used to attract attention in a lot of games, and it looks cool on grey conveyor

Just as in factorio

**Comment by ps3moira** [comment]
> [new-frontiers-14/frontier-station-14#1288](https://github.com/new-frontiers-14/frontier-station-14/pull/1288) There is also this look that I think is simpler and fitting to the original.

honestly yeah this looks a lot better

**Comment by slarticodefast** [comment]
Personally I like yellow more. But I also like factorio :)

**Comment by Golinth** [comment]
The factory must grow, no more wondering which direction my damn belts are moving

**Comment by Everturning** [comment]
I think it should be a dot, personally. Makes it less confusing when you have conveyors that move in different directions depending on lever (see: dispos)

**Comment by TheShuEd** [comment]
try add sync sprite component

**Comment by lzk228** [comment]
added

**Review by UbaserB — CHANGES_REQUESTED** [review]
As of currently, adding more detail to an already detailed sprite makes it too visually noisy. To fix this, the current suggestions are to have a look at how /tg/ does it, or make it so that the conveyors would have teg arrow visuals on examine. Personally, I love the approach Factorio took on conveyors so there are a few ways you can solve this.

image

**Comment by lzk228** [comment]
don't want to do something for now, I'll come back later, but if someone want to take it you're welcome

**Pull request closed without merging**
