### PR TITLE
New battery guns and some resprites

### PR DESCRIPTION
**Pull request by TaralGit**
Resprites (for the last time, I swear!) the Cr20, the combat knife and the machete.
Also, my crappy claymore sprite is replaced with the superior tgstation one, the Aks, the Drozd, the Z8 carbine and the Bojevic also get resprites and the PR further adds  two brand new energy weapons for ERT.

Changelog

🆑

   - add: Pulse carbine and pistol for ERT
   - add: Pulse hitscan projectile
   - tweak: The Lamia handgun is now using its own sprite instead of the gyropistol's
   - tweak: A whole bunch of resprites for various guns and melee weapons

Screen:
gun_branch

Update:
A few more things: resprites of Molly, Lamia, STS and Wintermute, replacement of the gyro pistol sprite with the cev one and one minor adjustment to the pk.
gun_branch

Clip:

https://user-images.githubusercontent.com/76408146/152644666-86500de6-b163-44e6-a1ba-c3095d4f9593.mp4

### CODE REVIEW

**Comment by TaralGit** [comment]
It's finished. The telescopic baton and the pulse rifle couldn't make it here because I haven't figured out how to make the baton work and why the rifle couldn't fire.

**Comment by SweptWasTaken** [comment]
AK looks bad

**Comment by TaralGit** [comment]
> AK looks bad. Proportions are way off. Also I think your old machete sprite looked fine, it fit in with the rest of the hydroponic tools.

changed the AK's proportions and made the machete's handle green to be more in line with the rest of the  hydro tools.

**Comment by SweptWasTaken** [comment]
I actually liked your old claymore, I thought it fit better than the tgstation one you replaced it with.

**Comment by Humonitarian** [comment]
Dragonquest claymore

**Comment by zombiemimic** [comment]
c20r feels kinda flat to me

**Comment by Humonitarian** [comment]
> c20r feels kinda flat to me

Same issue with the knife's blade, they lack contrast compared to the other sprites

**Comment by TaralGit** [comment]
Since we have a C20r poster I changed the c20r sprite to look more like the classic one by using the same palette as the clarissa pistol. As for the the knife's blade, it's the same colours as the kitchen knife and honestly it looks better than my old knife sprite.

**Comment by metalgearsloth** [comment]
is this still a wip?

**Comment by TaralGit** [comment]
> is this still a wip?

Nope. This PR is done.

**Comment by TaralGit** [comment]
Ok. All checks are now complete,  no conflicts and I won't anything to this. It's ready for reviewing.

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
