### PR TITLE
Bug fix for unremovable metal plates in airlock doors

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

Fixed a bug that was preventing metal plates being pried from airlock maintenance panels

## Why / Balance

See above

## Technical details

Changed the order interactions are resolved, so that prying interactions are checked with the construction system first before the prying system

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- fix: Fix praying door hacking protections.

### CODE REVIEW

**Comment by Partmedia** [comment]
Thank you for the fix. A video showing that prying now works again would have made this an insta-merge type of fix :)

**Comment by Partmedia** [comment]
What happened to the old message "The powered motors resist your attempt to pry the door?" when prying a powered airlock using a crowbar?

**Comment by Partmedia** [comment]
Did the command airlock always have the extra number of wires? What PR was this changed in?

image

**Comment by chromiumboy** [comment]
> What happened to the old message "The powered motors resist your attempt to pry the door?" when prying a powered airlock using a crowbar?

Hmm, it's issue on my end to, I'll have a look into that

>Did the command airlock always have the extra number of wires? What PR was this changed in?

It's been that way for a while. Unsure when it was PRed though

**Comment by Partmedia** [comment]
> It's been that way for a while. Unsure when it was PRed though

I think this was recently changed. I don't believe this is intended. Please investigate and fix if appropriate, but perhaps under the context of your other door PR.

**Comment by chromiumboy** [comment]
@Partmedia, I just tested on master, and the 'powered motors' is does not appearing for me. Can you confirm? If so, the message not appearing is not related to this PR

**Comment by Partmedia** [comment]
> @Partmedia, I just tested on master, and the 'powered motors' is does not appearing for me. Can you confirm? If so, the message not appearing is not related to this PR

In that case I'm going to go ahead and merge this fix as-is. Please investigate that issue when able. Thanks for the fix.

**Pull request merged**
