### PR TITLE
Initial Infected can see each other

### PR DESCRIPTION
**Pull request by Killerqu00**
## About the PR
Initial Infected now have an icon that is visible to other initial infected. This allows for better communication.
Also, Initial Infected can now see other zombies(just a slight QoL).

## Why / Balance
This is a slight zombie buff and also encourages teamwork between II. Most of the zombie outbreaks are ruined because II turned alone/in a bad situation. With this PR, they will be able to recognise themselves and communicate.

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑
- add: Initial Infected now can see each other.
- add: Initial Infected can now see zombified entities.

### CODE REVIEW

**Comment by Dutch-VanDerLinde** [comment]
changelog is broken you need 🆑

**Comment by wafehling** [comment]
YES. Thank you. This is exactly the kind of buff zombies need.

**Comment by Killerqu00** [comment]
> changelog is broken you need 🆑

thanks, fixed

**Comment by Everturning** [comment]
this will also help people realize they aren't the only one who is the init. infected, which is a major issue with the II text

**Comment by Killerqu00** [comment]
> this will also help people realize they aren't the only one who is the init. infected, which is a major issue with the II text

not sure what you mean. If there is a lore mismatch, it can be changed.

**Comment by Krunklehorn** [comment]
Much better than stat tweaks, thank you! Can't wait to see a harmless cult roleplay end in disaster.

**Pull request merged**
