### PR TITLE
Moves HumanoidAppearanceComponent to ECS

### PR DESCRIPTION
**Pull request by vulppine**
## About the PR 

This moves HumanoidAppearanceComponent to ECS. It wraps around a few existing functions, removes all the functions from HumanoidAppearanceComponent, and instead replaces it with a new EntitySystem, HumanoidAppearanceSystem.

### CODE REVIEW

**Comment by Zumorica** [comment]
Thanks for the PR!
Another thing, the changelog is for user-facing changes (such as... fixing a certain bug, adding an item, etc) so changes such as this which don't change user-facing functionality at all don't need changelogs

**Comment by vulppine** [comment]
got it!

**Comment by Zumorica** [comment]
Seems I caused you even more conflicts by merging your other PR-- My bad, leave a comment when they're fixed and I'll instamerge it :cold_sweat:

**Comment by vulppine** [comment]
yeah, looks like it's OK to merge!

**Pull request merged**
