### PR TITLE
Tiles rework

### PR DESCRIPTION
**Pull request by UnderscoreX5**
## About the PR 

Changed most of the ground tiles with some slight changes that make them look way better. Added 14 variations of tiles for medbay + some warning tiles for both white and steel floors.

**Screenshots**

image
image
(1 pixel error in the blue texture has been fixed but I am too lazy to take another screenshot!!!)

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
I like the way the new tiles look but the warning/variants are typically determined by decals. A robust decal system that is performant is something that we've been talking over for a while now and this PR might conflict with that.

**Comment by UnderscoreX5** [comment]
> I like the way the new tiles look but the warning/variants are typically determined by decals. A robust decal system that is performant is something that we've been talking over for a while now and this PR might conflict with that.

Yes of course, I've already heard about, as I stated on discord, it's really easy for me to convert the warnings to the new decal system in literally seconds. This is more of a test to see how they look since there is no decals system yet.

**Review by SweptWasTaken — APPROVED** [review]
Aight then, nice work.

**Comment by tmtmtl30** [comment]
I personally dislike the "holes" at the corners; I prefer uniform spacing of tiles.

**Review by metalgearsloth — APPROVED** [review]

**Pull request merged**
