### PR TITLE
Initial Infected see each other before the infection

### PR DESCRIPTION
**Pull request by Killerqu00**
## About the PR

Initial Infected can see the zombie icons near other Initials.

## Why / Balance

I feel like zombies need a slight buff after security/command became exempt from II antag role.
If this is not enough, I can also add buffs to zombified Initial Infected in order to make snowballing a bit easier.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Initial Infected can now identify each other before the outbreak.

### CODE REVIEW

**Comment by Killerqu00** [comment]
needs testing, apparently you cannot make someone II through admin menu, only make them zombies immediately
if someone can tell how to grant II antag role in dev environment, I would be glad

**Comment by deltanedas** [comment]
edit the zombies preset to work with 1 player then forcepreset zombies

**Comment by K-Dynamic** [comment]
Can zombies see the initial infected icon? Because this might lead to zombies avoiding biting initial infected

**Comment by Killerqu00** [comment]
> Can zombies see the initial infected icon? Because this might lead to zombies avoiding biting initial infected

There is no II icon, it is the same zombie icon, so the answer is yes.

however, I think this is alright, because II are already irreversibly zombified. Lorewise zombies can probably feel it.

**Comment by lzk228** [comment]
media?

**Comment by vanilia123** [comment]
much needed buff to zombies, after so many bad nerfs

**Comment by Killerqu00** [comment]
> media?

is it needed? It is just the same zombie icon

**Comment by Killerqu00** [comment]
Converted to draft, since it is currently showing **zombies** to II, not other II.
Perhaps a separate icon for II is needed?

**Comment by deltanedas** [comment]
its pretty easy to see zombies and ii would know more than others

**Comment by Fildrance** [comment]
Adding ability to fake zombie icon by washing yourself in zombie blood sounds... awzum... idea for future changes i guess

**Comment by Killerqu00** [comment]
Closing this for now, since my main laptop is now in repairs.
If this won't get inplemented, I will probably reopen with some other zombie tweaks.

**Comment by Krunklehorn** [comment]
Any word on this? People are itching for zombie buffs but they're just throwing out stat tweaks.

**Comment by Killerqu00** [comment]
> Any word on this? People are itching for zombie buffs but they're just throwing out stat tweaks.

Yeah, my laptop is back, planning to remake this PR today/tomorrow

**Pull request closed without merging**
