### PR TITLE
Rename Lizard urist

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
## About the PR

Rename it so i dont have a skill issue any time i need a lizard.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by asperger-sind** [comment]
Wasn't it always Urist McScales, then got changed at some point to the new, current (weird) version?
Imo just rename it to Urist McScales and add a suffix to add a generic "Urist" suffix to all Urists, with non-standard names included.

**Comment by Hanzdegloker** [comment]
funnily enough an issue I was having today, blessed PR

**Comment by 0x6273** [comment]
> Wasn't it always Urist McScales, then got changed at some point to the new, current (weird) version? Imo just rename it to Urist McScales and add a "Urist" suffix to all Urists, those with non-standard names included.

No? It's always been Urisst' Mzhand.
image

I agree adding "Urist" as a suffix to all of them is better, but I think the current name should be kept.

**Comment by VasilisThePikachu** [comment]
All urists have the same formatting for their name (Urist Mc<something>) this ensures that everything is the same. I kept the old name as a suffix more like a "legacy" feature. They all already have "Urist" in their name so there's no point to add a "urist" suffix to all of them.

**Comment by moonheart08** [comment]
> > Wasn't it always Urist McScales, then got changed at some point to the new, current (weird) version? Imo just rename it to Urist McScales and add a "Urist" suffix to all Urists, those with non-standard names included.
> 
> No? It's always been Urisst' Mzhand. image
> 
> I agree adding "Urist" as a suffix to all of them is better, but I think the current name should be kept.

They are ultimately a development tool, developer sanity comes first over a silly accent.

**Review by moonheart08 — APPROVED** [review]

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
