### PR TITLE
Add smoking pipe

### PR DESCRIPTION
**Pull request by themias**
## About the PR 

- Adds a reusable smoking pipe (using already ported animated sprite)
- Retrieves reagents from inserted materials upon lighting
- Currently allows ground tobacco and ground cannabis
- Added to cigarette machine, DIY smokables crate, and detective trench coat

**Screenshots**

pipe_screen

**Changelog**

:cl:
- add: Added a smoking pipe. Get your Sherlock Holmes on!

### CODE REVIEW

**Comment by Emisse** [comment]
looks good

**Comment by Silvertorch5** [comment]
:smoking: :heavy_check_mark:

**Comment by themias** [comment]
I really should have run the tests locally before opening. If I can't fix soon, then I'll close and reopen later.

**Comment by moonheart08** [comment]
optional stretch goal of letting monkeys wear masks in another PR.

**Comment by Visne** [comment]
Most of the stuff in `Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Pipes/pipe.yml` is redundant, and already covered by parenting.

**Comment by themias** [comment]
> Most of the stuff in `Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Pipes/pipe.yml` is redundant, and already covered by parenting.

IIRC if you modify anything in a component in a child entity, you have to define all the fields for that component again, or else they will be returned to default values. So everything in SmokingPipe component has to be written out again or be lost, since we added a startingItem. Although, ItemSlots and Container components could probably be dropped from those two.

**Comment by mirrorcult** [comment]
> IIRC if you modify anything in a component in a child entity, you have to define all the fields for that component again, or else they will be returned to default values.

this is not true

**Comment by Visne** [comment]
Also, don't forget the names and descriptions. Those are also inherited.

**Comment by themias** [comment]
> > IIRC if you modify anything in a component in a child entity, you have to define all the fields for that component again, or else they will be returned to default values.
> 
> this is not true

Ah ok. I remember there was some bug a while back where you could put anything in the HOP/Captain PDA slots since the whitelist got overwritten, but maybe it was due to something else.

**Comment by Visne** [comment]
Because the whitelist on the inheriting entity is the same field as the whitelist on the parent entity. So then the whitelists aren't merged, but the inheriting whitelist overwrites the parent whitelist. But if you specify field2 on the inheriting entity, and the parent entity has field1, then they will both be applied.

**Comment by themias** [comment]
I think I got confused since the bowl_slot field is a component itself, so its nested fields can't draw from the parent (since it is technically defined). All regular (undefined) fields would inherit though.

Thanks for helping me understand!

**Pull request merged**
