### PR TITLE
Ports goliath cloaks from TG

### PR DESCRIPTION
**Pull request by nmajask**
## About the PR 
Ported goliath cloaks from TG with a few differences:
- The cloak is worn in the neck slot
- The cloak and hood doesn't provide armor
- The cloak isn't craftable, ~~so it is only obtainable by admins~~ it is now available in maints, though it is rare

**Media**

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: added goliath cloaks based on the one from TG that can rarely spawn in maints

### CODE REVIEW

**Comment by moonheart08** [comment]
We don't add unused/admin-only content to avoid content bloat. This should at least be in a maint pool.

**Comment by nmajask** [comment]
> We don't add unused/admin-only content to avoid content bloat. This should at least be in a maint pool.

Got it, I look into adding it to the maint pool tomorrow or I might just close this. Manly made this to get used to yml, so I'm not too fussed if it doesn't get added.

**Comment by Emisse** [comment]
image
to add something to maint drop loot pool you just go here and add the prototype id

**Comment by nmajask** [comment]
> image to add something to maint drop loot pool you just go here and add the prototype id

Thanks for the help! I added and tested it and it seems to work.

**Review by Emisse — APPROVED** [review]

**Review by EmoGarbage404 — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Pull request merged**
