### PR TITLE
saltern 4.10

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR

**security**
- replaced duplicate warden locker with seccie locker
- forensic scanner on hos table

**medical**
- each exam room has wall cabinet
- added 2 medicine cabinets
- fixed intercom position

- replaced surgery with cryo

**chapel**
- removed duplicate chaplain wardrobe
- made kitchen much simpler, its a (holy) bread factory not a 5 star kitchen

**engineering**
- replaced grilles with reinforced walls, hopefully blocking radiation from cleansing the animals

also added more stuff to maint

### CODE REVIEW

**Comment by luckyshotpictures** [comment]
I still not understand why there is a kitchen in the chapel in the first place on such a small station.

**Comment by deltanedas** [comment]
- idk EEASAS added
- breab

**Comment by luckyshotpictures** [comment]
I think a place like a study room for e.g. bible study would be a better use than a budget kitchen. i honestly hate it. (the tiles below the table make me despise it even more)

**Comment by Emisse** [comment]
move the medical doors further up, change chaplain room to bible study that sounds funny

**Comment by Emisse** [comment]
sci also needs anomaly vessel

**Comment by deltanedas** [comment]
it has 2

**Comment by deltanedas** [comment]
@Emisse did you mean move this door up (to the wall)?

**Pull request merged**
