### PR TITLE
remove 07 from emote chatsan

### PR DESCRIPTION
**Pull request by lzk228**
## Why / Balance

you cant say numbers that ends at 07

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by Emisse** [comment]
07

**Comment by deltanedas** [comment]
Excellent work 0
@salutes

**Comment by Hmeister-real** [comment]
can you still do o7?

**Comment by Errant-4** [comment]
> can you still do o7?

Yes

**Pull request merged**
