### PR TITLE
Add hats and berets to the uniform printer

### PR DESCRIPTION
**Pull request by MACMAN2003**
## About the PR

Added some hats and berets to the uniform printer
## Why / Balance

Some maps don't have dressers for command roles yet. And if there's a bureaucratic error event that all the new heads can wear the same hat.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
i can't get a screenshot because the project isn't building for some unrelated reason
## Breaking changes

**Changelog**

:cl:
- add: The Uniform Printer can now print hats and berets for command roles!

### CODE REVIEW

**Comment by MACMAN2003** [comment]
what the fuck is a linter and why is it failing

**Comment by ItsMeThom** [comment]
> what the fuck is a linter and why is it failing

Linters are enforced style guides, to ensure all files of a given type follow the same conventions. In this case, something about the YAML file you changed is not matching with the style guide set by the maintainers.

**Comment by GreyMario** [comment]
Syndie pajamas are contraband...

**Comment by UbaserB** [comment]
> Syndie pajamas are contraband...

Its the emagged list lol

**Comment by MACMAN2003** [comment]
branch is fucked gotta make a new pr :(

**Pull request closed without merging**
