### PR TITLE
Windows now take heat damage

### PR DESCRIPTION
**Pull request by GoodWheatley**
## About the PR 

Self-explanatory. If you feel like the modifiers I made are too good, feel free to chime in.

**Changelog**

:cl:
- tweak: Eswords can damage windows now.

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Why not just make eswords do structure damage?

**Comment by GoodWheatley** [comment]
> Why not just make eswords do structure damage?

I'd like it if windows were at least a little vulnerable to heat damage, but that's also a good idea. Should I put it in this PR or open a new one?

**Comment by EmoGarbage404** [comment]
I mean, the fire axe is the objective best melee choice. It wouldn't hurt to increase the viability of some of the other options.

**Comment by GoodWheatley** [comment]
>decide to change flatreduction for Slash from 10 to 7.5
>mfw 1374 warnings

**Comment by asperger-sind** [comment]
> I mean, the fire axe is the objective best melee choice. It wouldn't hurt to increase the viability of some of the other options.

It's not __objectively__ the best, it's good, but it has it's own uses and drawbacks, giving one the main selling points of annihilating structures to a weapon that fits in your pocket and outputs more or so the same DPS is just going to cause balance issues down the line.

If the e-sword should have some trick up against the fireaxe, it shouldn't be structural damage.

**Comment by EmoGarbage404** [comment]
Thats fair. Esword could probably just use a damage buff, sound volume decrease, and maybe functionality as a welder.

**Comment by metalgearsloth** [comment]
> going to cause balance issues down the line.

It costs tc to get an esword...

**Review by mirrorcult — APPROVED** [review]

**Pull request merged**
