### PR TITLE
Fixes issue #9597: Emitter beams are blocked by glass windows

### LINKED ISSUE #9597: Emitter beams are blocked by glass windows
## Description
Emitter beams are blocked by glass windows. This is bound to cause issues when Supermatter engine becomes a thing.

**Reproduction**
Do the picture thing.

**Screenshots**
emitters

**Additional context**
Found it when I wanted to improvise gun on gunship shuttle made out of directional plasmarglass. Had to stick emitter into vacuum to get beams out.
gunship
(also pictured: machines z-fighting with directional windows, but unable to reproduce on current game version)

### PR DESCRIPTION
**Pull request by OctoRocket**
## About the PR

Allows emitter projectiles to go through glass. 
Closes #9597 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Thanks to improved emitter technology, emitter and APE projectiles will now go through glass!

### CODE REVIEW

**Comment by OctoRocket** [comment]
It would be nice if someone with more knowledge of game physics could make sure that I didn't do anything terrible.

**Comment by EmoGarbage404** [comment]
Can you make APE particles go through glass as well.

**Comment by OctoRocket** [comment]
Should disablers also go through glass?

**Comment by EmoGarbage404** [comment]
> Should disablers also go through glass?

Hell no

**Comment by OctoRocket** [comment]
Just making sure

**Comment by Snowyypanda** [comment]
> > Should disablers also go through glass?
> 
> Hell no

why, it's a laser beam? i'm pretty sure in ss13 it does go through glass as any other type of beam weapon does

**Comment by OctoRocket** [comment]
I think it would just be too powerful

**Comment by deltanedas** [comment]
> in ss13 it does go through glass as any other type of beam weapon does

laser gun does heat damage not stun
disabler bolts going through windows would be stupidly op

**Review by DrSmugleaf — APPROVED** [review]

**Pull request merged**
