### PR TITLE
add ability to prevent looc use in crit

### PR DESCRIPTION
**Pull request by Chief-Engineer**
## About the PR

Also punishes the worst offenders. Idk if this is supposed to have a CL bc it's server specific

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: LOOC can now be disabled per-server in crit.
- tweak: LOOC can now be configured to damage players who attempt to use it in crit.

### CODE REVIEW

**Comment by deltanedas** [comment]
> LOOC can now be configured to damage players who attempt to use it in crit.

:trollface:

**Comment by lzk228** [comment]
tougher penalties for players? wtf, no!
make the impact of OOC actions on the IC?? yes!

**Comment by CaptainSqrBeard** [comment]
I like this since I often see when people write something like this:
"LOOC: Urist McCrit: please help me I'm in crit"

I don't think any penalties is needed, but since it's configurable - it's should be okay

**Comment by EmoGarbage404** [comment]
disabling LOOC for crit characters is fine--we already do it for dead characters-- but a silent 20 cellular damage penalty for trying to send a LOOC message in crit (something that isn't always going to be a problem) feels heavy-handed and like it might be confusing for players.

**Comment by asperger-sind** [comment]
Disabling LOOC for crit is good, the 20 genetic damage is overkill and isn't telegraphed well enough.
Also this has issues like typing an LOOC message, getting critted and sending it before the realization of the fact that you're in crit and hop woila you took 20 genetic damage while not falling into "worst offenders"

**Comment by EmoGarbage404** [comment]
also why the overkill punishment if you can just disable it?

**Comment by deltanedas** [comment]
should be brute instead of cellular since if you are dying in medbay with  doctors ignoring you and try to use looc to get someones attention, since doctors are already incompetent and they probably wont know how to fix 20 cellular on a corpse will just morgue you and voila you are removed from the round
at least if its brute maybe bozos will figure out bruise packs

not biased at all btw,

**Comment by EmoGarbage404** [comment]
> should be brute instead of cellular since if you are dying in medbay with doctors ignoring you and try to use looc to get someones attention, since doctors are already incompetent and they probably wont know how to fix 20 cellular on a corpse will just morgue you and voila you are removed from the round at least if its brute maybe bozos will figure out bruise packs
> 
> not biased at all btw,

i mean sure but if the problem is "people use LOOC in crit which is bad", then just disable it and don't bother with being punitive for no reason.

**Comment by Equivocateur** [comment]
> 20 celluar per looc message

Damage on uncuff attempt was a mistake.

People use looc while in crit to say "ggwp" after a fight, not only to scream at other players that appear to have a chimpanzee behind the keyboard playing the game as a medic being unaware how to heal people. A last word system and disabling looc would be way better than this.

**Comment by deltanedas** [comment]
too based for he own good...

**Comment by Emisse** [comment]
this is a good idea so deltanedas becomes uncloneable every round

**Comment by EmoGarbage404** [comment]
beyond "le funny meme" is there any justification for why dealing damage is better than just preventing it?

**Comment by DogZeroX** [comment]
Pro

**Comment by deltanedas** [comment]
real

**Comment by EmoGarbage404** [comment]
> It'll make the people who have been annoyed with others doing it up to now feel a pleasing sense of justice as balance is slowly restored to the universe

so admin spite pr?

**Comment by EmoGarbage404** [comment]
you're not obsoleting admins you're just malding about not having fixed it sooner :P

**Comment by EmoGarbage404** [comment]
> The entire playerbase needs to work together for us to successfully obsolete admins

i mean you can actually acknowledge my design criticism or you do "it's funny haha shitpost." Your pick.

**Comment by Mudsson** [comment]
I feel like it should either be disabled or not. The 20 genetic damage seems like ot will fuck with new players more than "cannot use LOOC whole crit"

**Comment by EmoGarbage404** [comment]
it feels especially punitive considering that, in its current implementation, it still deals the damage even if LOOC in crit is disabled. You're really just punishing players for attempting to do something that is already blocked mechanically.

**Comment by Just-a-Unity-Dev** [comment]
"gg" gains 20 genetic damage

LOOC disabled in crit is fine but the genetic damage is overkill and unnecessary.

**Comment by Ilya246** [comment]
make it heal you out of crit so it isn't LOOC in crit anymore

**Comment by Just-a-Unity-Dev** [comment]
> rain told me I should make it scale exponentially based on the message length. Depending on the exact equation you use, big brains would be able to send a specific length message to overflow and heal

Make it scale exponentially to the second power so that I can just say "gg" and get 4 genetic damage instead of saying "gg" and getting 20 genetic damage. There is a max character limit of 1000 and whoever reaches that limit will just be permadead. Good discussion.

> I have never seen or heard of this happening on WizDen, definitely on on LRP

Either I haven't been playing enough or you haven't seen me online

I'm otherwise convinced that this PR is a brickwall discussion as was the discussion we had earlier. 20 genetic is a stupid amount of damage and I will stand by that opinion.

**Comment by Just-a-Unity-Dev** [comment]
so just disable LOOC? lol? this seems extremely punishing for players and also completely unnecessary

**Comment by EmoGarbage404** [comment]
You've yet to explain why dealing extra damage silently is actually the best of both worlds

**Comment by EmoGarbage404** [comment]
Youre still not answering the question??

**Comment by EmoGarbage404** [comment]
Then thats crappy design based on you being angry at people for breaking rules in the past. It honestly sounds like ypu should reexamine why you're making changes instead of just doing it to spite people.

**Comment by EmoGarbage404** [comment]
Sure, lol, karma.

Idk what kind of "karmic retribution" it is to just punish players harshly for doing something that you've changed to have 0 in-game effects.

Everything you've said just makes this seem like a salty spite pr, and the application to Lizard specifically seems doubly so. If you're mad at players abusing a feature, just fix it and move on. No need to try and restore "balance" to your wounded soul.

**Comment by Just-a-Unity-Dev** [comment]
> It's a karma system that's both incredibly simple and accurate. I don't actually play the game, I'm not the one getting angry at people for breaking the rules, **I'm just the one manually being the karma system**

Isn't the point of admins... exactly that? If you don't like being an admin just resign

**Comment by Equivocateur** [comment]
> > It's a karma system that's both incredibly simple and accurate. I don't actually play the game, I'm not the one getting angry at people for breaking the rules, **I'm just the one manually being the karma system**
> 
> Isn't the point of admins... exactly that? If you don't like being an admin just resign

CE's a headmin now lmao that's not going to happen

**Comment by Just-a-Unity-Dev** [comment]
> CE's a headmin now lmao that's not going to happen

They can still resign? There's nothing saying "as a headmin you are not allowed to leave".

**Comment by Equivocateur** [comment]
> > CE's a headmin now lmao that's not going to happen
> 
> They can still resign? There's nothing saying "as a headmin you are not allowed to leave".

They sure can, will they though?

**Comment by Just-a-Unity-Dev** [comment]
And why is this pointed only to lizard? Why not damage those who do it on Leviathan too? Or the entirety of wizden?

**Comment by Mudsson** [comment]
This is affecting ingame based on an out of character action, it just seems silly to me. Either diaable LOOC while crit or don't. Its much easier for a new player to see :

I send message-> it no send now but sent before -> maybe because I'm critical?

Then to see:

I send message -> depending on length of message I either take a lil bit of damage and the crit screen jumps, or a lot and almost die depending on length -> I am clearly being punished in character for an out of character action, a very easy to reach conclusion for new players.

**Comment by Just-a-Unity-Dev** [comment]
> Ya, having it scale by message length would actually make it be stealth damage some of the time and would be incredibly difficult to figure out because it would be perceived as inconsistent.

Or you could have no damage?

**Comment by metalgearsloth** [comment]
I think this was superceded but without cellular damage.

**Pull request closed without merging**
