### PR TITLE
Add disposals damage

### PR DESCRIPTION
**Pull request by Slava0135**
## Why / Balance

because disposals are abused and it doesn't make sense how you can travel through pipes without a single injury

## Media

https://github.com/space-wizards/space-station-14/assets/40753025/c24a5138-8ea8-4777-b953-ac431332550d

## Breaking changes

**Changelog**

:cl:
- tweak: Traversing through disposal system now deals some blunt damage on every turn. Be advised!
- fix: Fixed clang sound not playing when traversing through disposal system.

### CODE REVIEW

**Comment by deltanedas** [comment]
only bad part is loops are now trivial to make deathtraps

**Comment by Anzarot121** [comment]
RIP Hamlet 🫡

**Comment by IamVelcroboy** [comment]
Can we get a non-damaging tube? Because many maps use these as intentional means of transportation.

**Comment by Slava0135** [comment]
> Can we get a non-damaging tube? Because many maps use these as intentional means of transportation.

damage is configurable, so you can make non-damaging tubes

**Comment by deltanedas** [comment]
also yes this should definitely be proportional to mass in some way, hampter should fly through tube like a regular item unscathed instead of dying after ~5 bends

**Comment by asperger-sind** [comment]
shouldn't this also introduce some map standards for how disposals should be built or will we have maps that have disposals that literally gib you

also raises concerns for silly individuals who push people down disposals, you can realistically kill people with it now

**Comment by deltanedas** [comment]
a loop is literally automatic gibber if it damages past death

**Comment by asperger-sind** [comment]
> a loop is literally automatic gibber if it damages past death

new tot strat: make disposals loop at the end, shove people into disposals :trollface:

**Comment by IamVelcroboy** [comment]
> damage is configurable, so you can make non-damaging tubes

Excellent 👍

**Comment by brainfood1183** [comment]
I think damage is to high, 1 trip through disposals shouldnt put you in crit

**Comment by Hmeister-fake** [comment]
Tone down the damage a little, being punished that hard for just jumping into disposals is too much.

**Comment by GreyMario** [comment]
absolutely not at these values

jumping into disposals is a feature--it shouldn't pose a significant risk of killing the player for doing it, and yes there's a significant problem with disposal loops if this is implemented

not to mention this would severely buff emagging the recycler, especially if the tot works a few more bends into the disposals system

**Comment by Slava0135** [comment]
reduced damage to 1 blunt per turn
also note that armor can reduce damage

**Comment by Hmeister-fake** [comment]
If armor applies I think 1 is a tad too little to matter, maybe 2 or 3? I mean you are literally hurling through a pressurised steel tube

**Comment by forgotmyotheraccount** [comment]
My opinion - only take damage when travelling through bends, and make the bends take structural damage when you do. It makes more sense, is less punishing, and means loop deathtraps will eventually break

**Comment by Slava0135** [comment]
> My opinion - only take damage when travelling through bends, and make the bends take structural damage when you do. It makes more sense, is less punishing, and means loop deathtraps will eventually break

You already only take damage when turning, making pipes take damage too could work (and also give engineers something to do in meanwhile)

**Comment by Aisu9** [comment]
1 blunt isn't too little?

**Comment by notquitehadouken** [comment]
water slide

**Comment by Ilya246** [comment]
it should deal no damage if you wear a hardhat, gives use to them
have some way to give clothing the ability to prevent disposals damage?

**Comment by Aisu9** [comment]
there is other things hitting the disposal conduit than your head

**Comment by Slava0135** [comment]
> it should deal no damage if you wear a hardhat, gives use to them have some way to give clothing the ability to prevent disposals damage?

>wear hardhat
>jump into disposals
>break neck
>:trollface:

**Comment by Ilya246** [comment]
> > it should deal no damage if you wear a hardhat, gives use to them have some way to give clothing the ability to prevent disposals damage?
> 
>     * wear hardhat
> 
>     * jump into disposals
> 
>     * break neck
> 
>     * :trollface:

* wear bulletproof vest
* get shot in the head
* bullet magically teleports into bulletproof vest

**Comment by deltanedas** [comment]
hardsuit full body coverage :trollface:

**Comment by Aisu9** [comment]
_add disposal damage
_look at the damage:
1 damage per turn while propelled at high speed through steel conduits with no safety in the said conduits
_Ah yes... this will surely dissuade people from using disposal units as a mean to fast travel

**Comment by deltanedas** [comment]
as opposed to get flushed and get crit

**Comment by Aisu9** [comment]
isn't there a way to cap the damage? like it wont do more when the crewman in are at X or Y?
sure they wont be crit but it wont also deal _**no**_ damage

**Comment by CaptainSqrBeard** [comment]
I can't understand how disposals are abused and what this PR tries to fix. Being able to travel through disposals is a fun mechanic, even if it's unrealistic. In addition, there are multiple issues with that solution already, like death loops or people who loves to prank people with disposal flushing. I can also mention that this also applies to damageable items and affects mail disposals (but no one probably uses them)

**Comment by EmoGarbage404** [comment]
BANG! BANG! BANG! BANG!

**Comment by GreyMario** [comment]
[I hope you're happy.](https://discord.com/channels/310555209753690112/675078881425752124/1174271476409581618)

From zero to gibs in **40 seconds.** To say that this is problematic in practice is an understatement--and don't say you weren't warned that this would happen.

The shitters have a new toy, and this time you don't have _time_ to save their victims.

**Comment by UbaserB** [comment]
I like damage, but id prefer to half it or tune it down to a quarter so you can make several full trips before dying.

**Comment by deltanedas** [comment]
baseball bat gibs in 10 seconds, and it takes a few seconds to unanchor a pipe

**Comment by EmoGarbage404** [comment]
> I like damage, but id prefer to half it or tune it down to a quarter so you can make several full trips before dying.

It's literally 1 damage per turn. I can't imagine that a smaller number would even be noticeable. I also seriously doubt the average disposal loop has 50+ turns.

**Comment by EmoGarbage404** [comment]
> I like damage, but id prefer to half it or tune it down to a quarter so you can make several full trips before dying.

It's literally 1 damage per turn. I can't imagine that a smaller number would even be noticeable. I also seriously doubt the average disposal loop has 50+ turns.

**Comment by GreyMario** [comment]
> baseball bat gibs in 10 seconds, and it takes a few seconds to unanchor a pipe

challenge: find the person who does not play space station 14

baseball bats are typically wielded by a hostile person whose name you can call out
disposal traps have already critted you by the time you realize you're in one

**Comment by metalgearsloth** [comment]
> To say that this is problematic in practice is an understatement--and don't say you weren't warned that this would happen.

> challenge: find the person who does not play space station 14

Please be helpful on github or refrain from making unnecessarily hostile comments, thanks.

**Comment by Slava0135** [comment]
Gibbing inside pipes has to be fixed though.

**Comment by Holinka4ever** [comment]
> Gibbing inside pipes has to be fixed though.

I thought you will add thing that like, if spessmen stuck in death loop,disposal turn pipes wil eventually broke, we even have sprites for broken disposal pipes!

But seems we would wait it in next patch i guess.

**Comment by Holinka4ever** [comment]
> [I hope you're happy.](https://discord.com/channels/310555209753690112/675078881425752124/1174271476409581618)
> 
> From zero to gibs in **40 seconds.** To say that this is problematic in practice is an understatement--and don't say you weren't warned that this would happen.
> 
> The shitters have a new toy, and this time you don't have _time_ to save their victims.

I mean i understand this whole situation, but thing is that griefers would find any other solution to harm others. In meaing of disposal, they can just space out the entire disposals, or put plasma fire into it.

**Comment by Hmeister-fake** [comment]
I mean, sure disposal gibbing is a problem **in practice**, but if your unlucky enough to be in a situation where a traitor can flush you, then your most likely in a situation they could have killed or attacked you anyway. The only way i can see this being used is to grief disposals, quickly gib people who are already dead or in crit or for self antag. There are just way better and easier options to kill and gib people than setting up a disposals blender. 

But I still think there shyould be a system where if someone hits a pipe like x times in x seconds the pipe breaks. If it's not on a timer then mid round a pipe can just randomly burst and give engi a new problem to fix.

**Comment by IamVelcroboy** [comment]
I think disposals breaking is probably the best way to go. You could then add "padded" disposal corners and "reinforced." Padded would negate dmg and reinforced would withstand large(body shaped) objects passing through

**Pull request merged**
