### PR TITLE
explosion minor rework + fix

### LINKED ISSUE #21717: Lungs breaking as well as metabolism
Description

As a slime this has happened to me twice recently and I heard about this happening from others but rarely. I'm pretty sure when dying via explosions? as a slime and then getting revived your lungs just break as well as your metabolism. When revived you can no longer breath even if everyone else is breathing fine and when you are given meds you metabolize them either super slowly or it just doesn't work. The only fix i've seen for the lung issue was to remove the lungs but you will still have the issue of metabolizing super slowly or not at all meaning that any damage taken will take a lot longer to heal.

Reproduction

I am not sure how to reproduce this issue, all i know is that it happened after dying by a super matter bomb the first time and the second time a grenade pengu and being revived after dying to them.

Additional context

I don't know if this is a slime only issue or if other species have had this issue occur to them, but so far from what i've seen it's only affected me as a slime while i watch other people die the same way and be fine.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- recurison is now whitelisted, fixes #21717
- removed slime bodypart from the steel rod lineage
- whitelisting also prevents machine board/parts being recursed too so beakers dont break
- fixed a broken log that only showed if an exploded entity had MindComponent - mobs have MindContainerComponent!!!

## Why / Balance
bug

## Technical details
added `ExplodedEvent` which does damage + gets Contents to recursively process
various systems add to Contents like inventory and storage

## Media
root body part has no damage after c-4 bundle kills urist

rework works, c4+minibomb in a duffelbag explode gibbing a urist
the organs and bodyparts are intact though

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- fix: Fixed explosions deleting bodyparts and organs inside of people.

### CODE REVIEW

**Review by ElectroJr — CHANGES_REQUESTED** [review]
It shouldn't blacklist components, it should whitelist them. I.e., raise an event directed at the entity, and then have the storage, entity-storage, inventory, and hands systems redirect the explosion damage to entities "contained" by those components.

**Comment by deltanedas** [comment]
would it also be worth using that to do damage by having DamageableComponent subscribe to the event

**Comment by ElectroJr** [comment]
> would it also be worth using that to do damage by having DamageableComponent subscribe to the event

IMO that would make sense.

**Comment by ElectroJr** [comment]
See https://github.com/deltanedas/space-station-14/pull/1

**Review by ElectroJr — APPROVED** [review]

**Pull request merged**
