### PR TITLE
Added Garfield and Lasagna

### PR DESCRIPTION
**Pull request by SweptWasTaken**
image

- Adds a Garf Hardsuit
- Adds a Lasagna to eat
- Adds the rare material Lasagnium (Inedible)
- Added autolathe lasag animation

Main issues I found while actually making this pr is that the material/crafting system is pretty stringent meaning that you can't craft "materials" meaning I can't use Lasagna to create Lasagnium. I also can't put straight up lasagna in the protolathe because stuff with parent: FoodBase aren't accepted by the lathe and you can't add a FoodBase to a material.

I also discovered that on adding the Garf Suit to the lathe recipes yaml I couldn't craft it with the already on-map autolathes due to them not having a database update. I needed to spawn a new protolathe and then I could craft them.

I've submitted an issue for the latter.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
I will probably add a commit to this that means when you torch or weld lasagna it turns into lasagnium.

**Comment by unusualcrow** [comment]
why can't you put effort towards things that aren't shitposts

**Comment by RemieRichards** [comment]
Think about it, the easier it is for him to make shitpost content, the easier it is for everyone else to make genuine content.

He pushes the envelope, drives innovation, he's a _hero_

**Comment by Zumorica** [comment]
speedmerge this pls

Shitposts aside, that's actually some very helpful feedback on lathes so thanks.

**Comment by PrPleGoo** [comment]
> why can't you put effort towards things that aren't shitposts

This is content and that's fine. Don't shame them for putting in work.

**Comment by PKPenguin321** [comment]
Post obscure garf lore
https://youtu.be/ip8HDAi9yMg

**Comment by PJB3005** [comment]
That is cursed.

**Comment by SweptWasTaken** [comment]
Raising the bounty to this to 3000 as it took more  than 2 days to implement

**Comment by Zumorica** [comment]
I still think you should repurpose the Garfield hardsuit as a clown outfit

**Comment by Auri3l** [comment]
Oh god what is this

**Pull request closed without merging**
