### PR TITLE
fix ninja no guns

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
event was raised on the gun but never the user bruh
this just raises it on the user, adding gun as a field for flexibility in the future if anything needs it

## Why / Balance
i saw some pussy using a shotgun then panic

## Technical details
ninja system checks for event on user but gun system raised it on the gun...

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
what does this mean?

**Comment by Equivocateur** [comment]
Ninjas no fire guns

Spider clan no like guns

**Comment by JoeHammad1844** [comment]
guns are dishonorable

**Comment by deltanedas** [comment]
fight like a man or die like a mouse

**Pull request merged**
