### PR TITLE
Nullrod chapel add

### PR DESCRIPTION
**Pull request by Deahaka**
## About the PR 
Added nullrod for priest. Attention, it's heavy and hurts!
In-hands taked from TauCeti by [Theta Community](https://github.com/ThetaStation/ThetaStation).
**Screenshots**

**Changelog**

:cl:
- add: Added nullrod for priest.

### CODE REVIEW

**Comment by mirrorcult** [comment]
these were deliberately not included, so will need some justification as to why it should exist

**Comment by Deahaka** [comment]
> these were deliberately not included, so will need some justification as to why it should exist

I wanted to port the big bell, which you can hit with a nullrod and announce something for the station. https://github.com/TauCetiStation/TauCetiClassic/pull/5548

What do you plan to give the priest from accessories like nullrod? Staffs or swords?

**Comment by Elijahrane** [comment]
> What do you plan to give the priest from accessories like nullrod? Staffs or swords?

Familiars were intended to replace the null rod as something that encourages roleplay more while still being easy to make a bunch of different gimmick ones.

**Comment by moonheart08** [comment]
The Chaplain does not need an overpowered weapon. Find another way to go about things. We're not implementing the rod.

**Pull request closed without merging**
