### PR TITLE
Bwoink fix

### LINKED ISSUE #28895: Ahelp UI shows incorrect title upon filtering to different username
## Description
Admin UI try not to be shit mission impossible 

**Reproduction**
>start ahelp with "user1" 
>search for "user2" 
>see title change to "bwoink-none-selected"

Ahelp messages still send to their intended target, just a ui skill issue.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nikthechampiongr**
## About the PR

This fixes #28895.

The actual loc string for none selected is now used.

You can no longer ahelp a player which you selected before they disappeared from the list.

## Why / Balance

bug
## Technical details

The panel now gets hidden even if the selection is null. I do not see why this needs remain if it's not null, this is probably the correct behavior. I guess alternatively it could get deleted although considering the panel was previously hidden this may not be wanted as it seems to cache them?

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
ADMIN:
- fix: The ahelp panel properly deselects a player when they are no longer on the player list.

### CODE REVIEW

**Comment by nikthechampiongr** [comment]
An alternative is to completely remove the deselect behavior when the player gets removed from the list due to the filter..

**Comment by nikthechampiongr** [comment]
Actually I am gonna get feedback on this.

**Comment by crazybrain23** [comment]
> This fixes https://github.com/space-wizards/space-station-14/pull/28896.

Is that the right ID?

**Comment by nikthechampiongr** [comment]
> > This fixes #28896.
> 
> Is that the right ID?

No I love numbers

**Comment by nikthechampiongr** [comment]
Yea ok most admins seem indifferent to how this is fixed so I'll just proceed with this.

**Comment by ShadowCommander** [comment]
This reveals a deeper issue of why does the selected ahelp deselect when you filter the ahelps?

**Pull request merged**
