### PR TITLE
hyper realistic sandwich 2 electric boogaloo

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

Hyper realistic sandwich

## Why / Balance

funny

## Media

https://github.com/space-wizards/space-station-14/assets/79580518/9dfa2c7c-9143-42e5-af38-47e163bcf39d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- add: Nanotrasen discovered the power of the third axis and is using it to create sandwiches. Chefs rejoice!

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
holy shit an actually funny april fools pr

**Review by metalgearsloth — CHANGES_REQUESTED** [review]
As far as I can tell this isn't licensed properly. On archive.org if the user specifies a license the very first line is "Usage" but the page linked doesn't have any such thing listed which means it's unlicensed (at the very least it's definitely not CC-BY-SA-3.0). I uploaded a test file to check and it defaults to 4.0 so I doubt we can use this gif as funny as it is.

**Comment by potato1234x** [comment]
ive spent around 2 hours uploading every single frame of the gif and the gif itself into every single reverse image searcher i could find and none of which returned any results that i didnt already know about, the dream of a properly licensed high quality spinning sandwich is dead. also i wouldve done this sooner but i had no internet

**Comment by potato1234x** [comment]
sloth please just for this one day :despair:

**Comment by metalgearsloth** [comment]
Not going to break the repo being properly licensed just for funny, sorry.

**Comment by notquitehadouken** [comment]
recreate the gif under CC0-1.0

become ungovernable

**Pull request closed without merging**
