### PR TITLE
Revert Shuttle emag now with CVar

### PR DESCRIPTION
**Pull request by Morb0**
## About the PR

Return shuttle emag with CVar

## Why / Balance

Okay for MRP, like early launch
Required for hijack objective

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
rev can still emag it even if its mrp

**Comment by deltanedas** [comment]
no im saying if an mrp server has it enabled a rev is still able to emag it

**Comment by Emisse** [comment]
i do not think this is good for the game

**Comment by Morb0** [comment]
> i do not think this is good for the game

It's required for shuttle hijack objective

**Comment by deltanedas** [comment]
why would being able to do that objective easily depend on being mrp

**Comment by Emisse** [comment]
shuttle hijack should probably be reworked to work like how it does in 13

**Comment by Morb0** [comment]
> shuttle hijack should probably be reworked to work like how it does in 13

I wanted to make it so that using an emag counts as 1 AA authorization, but the problem is that this is disabled by default in CVar
and implementation of 13 makes antags special, giving the ability of hijack, which is kind of something to avoid

**Review by keronshb — CHANGES_REQUESTED** [review]
I want to remove emag reliance, and would rather have something like traitors getting a context menu to hijack instead

**Comment by Everturning** [comment]
> > shuttle hijack should probably be reworked to work like how it does in 13
> 
> I wanted to make it so that using an emag counts as 1 AA authorization with delay for next, but the problem is that early launch is disabled by default in CVar and implementation of 13 makes antags special, giving the ability of hijack, which is kind of something to avoid

Okay, so antags being special is a bad thing, got it. Hijacking is a bad and special thing for antags to do, even if it's literally the point of a fucking objective, got it.

**Comment by metalgearsloth** [comment]
> > > shuttle hijack should probably be reworked to work like how it does in 13
> > 
> > 
> > I wanted to make it so that using an emag counts as 1 AA authorization with delay for next, but the problem is that early launch is disabled by default in CVar and implementation of 13 makes antags special, giving the ability of hijack, which is kind of something to avoid
> 
> Okay, so antags being special is a bad thing, got it. Hijacking is a bad and special thing for antags to do, even if it's literally the point of a fucking objective, got it.

be civil and make better comments in future.

**Comment by LankLTE** [comment]
As this was entirely removed, I feel it's ideal if this is made as different system, as Keron stated.

**Pull request closed without merging**
