### PR TITLE
[Hardsuits] Disease protection for hardsuit and their helmets

### PR DESCRIPTION
**Pull request by PuroSlavKing**
## About the PR

Isn't it strange that some kind of lizard medic is less likely to get infected with the same zombie virus than an elite NT squad to fight this virus.
This PR is the solution to this problem: https://github.com/space-wizards/space-station-14/issues/14950
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added Disease protection for CBURN, ERT, and Syndie Elite (hardsuits and their helmets)

### CODE REVIEW

**Comment by mirrorcult** [comment]
is the hardsuit disease protected (as the issue claims is the problem)? i feel like these can get even more protection

**Comment by PuroSlavKing** [comment]
> is the hardsuit disease protected (as the issue claims is the problem)? i feel like these can get even more protection

I'm sorry, I didn't receive a notification about this comment, I added not bad virus protection, this time to everyone who needs it, and to the necessary extent.

**Comment by keronshb** [comment]
> > is the hardsuit disease protected (as the issue claims is the problem)? i feel like these can get even more protection
> 
> I'm sorry, I didn't receive a notification about this comment, I added not bad virus protection, this time to everyone who needs it, and to the necessary extent.

I think what she's asking is:

1 - How well do these protect against diseases (vs no/other protection)
2 - The protection values could be bumped up higher depending on 1

**Comment by PuroSlavKing** [comment]
> How well do these protect against diseases (vs no/other protection)

1) Somewhere at the level of bio-suits, in some cases even a little better.
2) I don't see the point in having, for example, 169% protection not to get infected with the same zombie virus when 70-100 is enough.

**Comment by keronshb** [comment]
> > How well do these protect against diseases (vs no/other protection)
> 
>     1. Somewhere at the level of bio-suits, in some cases even a little better.
> 
>     2. I don't see the point in having, for example, 169% protection not to get infected with the same zombie virus when 70-100% is enough.

ehhh sounds good to me? I'll see if I can rerun the tests and then merge.

**Comment by PuroSlavKing** [comment]
> > > How well do these protect against diseases (vs no/other protection)
> > 
> > 
> > ```
> > 1. Somewhere at the level of bio-suits, in some cases even a little better.
> > 
> > 2. I don't see the point in having, for example, 169% protection not to get infected with the same zombie virus when 70-100% is enough.
> > ```
> 
> ehhh sounds good to me? I'll see if I can rerun the tests and then merge.
> 
> EDIT:
> 
> @PuroSlavKing can you merge master to see if the tests fix?

merged

**Pull request merged**
