### PR TITLE
Adding a simple Wooden Closet

### PR DESCRIPTION
**Pull request by Agoichi**
## About the PR

Basically just added wooden cabinet without lock on it

## Why / Balance

It will really look cool as a part of interior and even cooler without those locks on it

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Wooden closet without lock (Wardrobe)

### CODE REVIEW

**Comment by UbaserB** [comment]
can you make it a wardrobe instead?

**Comment by Agoichi** [comment]
> can you make it a wardrobe instead?

Maybe.

**Review by TheShuEd — CHANGES_REQUESTED** [review]
I'm sure there are many duplicates of the locked closet prototype. Add inheritance to avoid repetition

**Comment by potato1234x** [comment]
The lock looks like it was poorly erased, tg has regular wardrobe sprites

**Comment by Hrosts** [comment]
> The lock looks like it was poorly erased, tg has regular wardrobe sprites

Because there's no sprite change, it just reuses the texture of the lockable one.

**Pull request closed without merging**
