### PR TITLE
Golden toilet

### PR DESCRIPTION
**Pull request by Nimfar11**
## About the PR

Added an expensive gold toilet for the captain (or other important person). Is a difficult theft target for a thief, a worthy target.

## Why / Balance

More interesting special targets for the thief. Fun for the captain.

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11
- add: Adds a gold toilet
- add: Adds a target for the Thief to steal the golden toilet
- fix: Corrected the sprite image for the normal toilet.

### CODE REVIEW

**Comment by SoulFN** [comment]
Finally, the best item in the game.

**Comment by beck-thompson** [comment]
Recommendation: Allow the golden toilet to hold larger items in its secret stash (Its fancy and got more room!). Great idea though!

**Comment by Emisse** [comment]
speed merging

**Comment by Olexiy-Lapin** [comment]
А когда золотой батон добавят?))

**Pull request merged**
