### PR TITLE
Removes a bunch of bad-looking walls

### PR DESCRIPTION
**Pull request by Flareguy**
## About the PR
Removes a bunch of walls from the game (at least until they get better sprites.) They are as follows:
- Brick
- Bananium
- Diamond
- Gold
- Plasma
- Silver
- Sandstone
- Plastic
They are all migrated to solid walls.

Untested ingame. Probably should not matter, unless the tests for crafting don't catch some stuff.

## Why / Balance
The sprites for these have sucked for over a decade (or however long they've existed in SS13.) They're in the wrong perspective (top down instead of side perspective) and are generally just really ugly, lacking any kind of shading and being in a completely different style compared to other normal walls. On top of this, walls are extremely non-trivial to sprite most of the time, so just respriting them is really not a good use of time for such niche structures with limited use.
There is really no good reason to have these in the game right now; using them is almost always self-sabotaging and makes wherever they're used look distinctly worse.

It is worth noting that wood and uranium walls suffer from similar problems, but have important & distinct uses that aren't filled very well by just replacing them with solid walls. so they haven't been removed for now.

## Technical details
N/A

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- remove: Removed gold, silver, plasma, and bananium walls.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Why remove things if you don't have replacements ready?

**Comment by Dutch-VanDerLinde** [comment]
this just removes the clown shuttle from the game because the clown shuttle uses bananium

**Comment by deltanedas** [comment]
just dont map them i love blinging everything out in gold

**Comment by metalgearsloth** [comment]
If anyone keeps them they need re-importing because some of the sprite layers are cooked.

**Comment by bruhmogus** [comment]
flareguy, please stop removing random stuff from the game, it's only serving to make it worse
it started with the sec overhaul (it was in your own words too good) and now we're removing walls
just why
if this comment is hidden as irrelevant i will not be surprised

**Comment by TheDoctor1977** [comment]
why are we just removing content because it supposedly sucks instead of improving it

**Comment by mirrorcult** [comment]
calling this "content" is uhh lol

**Comment by mirrorcult** [comment]
bananium one should probably stay since its kinda supposed to look gaudy and shitty and its used by the clown shuttle but the other ones have got to go

**Comment by IProduceWidgets** [comment]
I don't think we should just migrate walls willy nilly, this seems like mapping cancerium. Especially if they're used by any downstream which seems very likely.
I have to agree we should just replace the sprites if the entities themselves are not problematic innconcept.

**Comment by dvir001** [comment]
We use them all downstream, please don't just remove them like this.

**Comment by metalgearsloth** [comment]
> This comment may be hidden but I still have this point to be made.

If you're just going to bully people for no reason on a random PR then comments will get hidden. This is also the reason we discord banned you.

**Comment by Everturning** [comment]
Fair. Wasn't trying to bully.

**Comment by retequizzle** [comment]
only one i disagree with being removed is bananium because a) it's arguable that it's supposed to look bad and b) it has a current active use with the clown shuttle being in rotation, swapping out the walls for solid walls in that case is just drab

i suppose the clown shuttle can be remapped with updated walls (it'd take like 5 mins) but there's also really nothing that would serve as a viable "side-grade" for clown shit

i agree with the rest being removed, no real use for them at the moment and spriting resources can be allocated to more important stuff until this gets revisited

if anyone's upset by the removal of certain assets they can look into spriting themselves to expedite re-adding them to the game

**Comment by NotSoDana** [comment]
Why removing? Go and resprite it or find somebody who will do it. All of this walls are useful sometimes on different situation in mapping. If you are removing it then give the alternative. Just cleaning of "sucks sprites" isn't the way, man

**Comment by SlamBamActionman** [comment]
I am for removing most of them (save for bananium) because they do look kinda not-great. I would however make a GH issue or similar that concerns making new walls. Plasma/diamond/silver and most importantly plastic walls *could* work (seriously, where are my clinically clean white plastic walls?), but these sprites aren't it. By making a GH issue it's clear the problem isn't the conceptual idea to have cosmetic walls, but rather that the sprites are lacking.

**Comment by Ratyyy** [comment]
image

**Comment by Ko4ergaPunk** [comment]
- Grass and dirt — 12.06.2024🕯️
- Brick, Bananium. Diamond, Gold, Plasma, Silver, Sandstone, Plastic — is waiting

Very competent

**Comment by Ko4ergaPunk** [comment]
Dont worry guys! I'm already draw resprite for "our art style"
image

**Comment by Emisse** [comment]
> Very competent

Keep the snark out of here or you will be removed. Provide constructive feedback or don't provide anything at all.

**Comment by Cojoke-dot** [comment]
I think I've only ever seen 3 of these walls and the last time I saw one was on Aspid. Same thing everyone else is saying about bananium and stuff. I also like the plastic walls for some odd reason but yeah they need a new sprite.

Kinda an aside but what happens to maps that use these walls? I know plastic walls are mapped in a couple places and the obvious bananium stuff.

**Comment by mirrorcult** [comment]
from the PR

>  They are all migrated to solid walls.

**Comment by LittleNorthStar** [comment]
The game is just a play test everything doesn't need to be perfect or removed this isn't the cutting room before release, I really think they should just be left as is and have a issue made for them needing a retexture

**Comment by Qsan163** [comment]
image

**Comment by metalgearsloth** [comment]
> We use them all downstream, please don't just remove them like this.

Downstreams can cherry-pick commits and remove ones they don't want.

**Comment by Flareguy** [comment]
Okay, after some internal discussion, I can at least say the way I handled the removals here is pretty needlessly destructive. At minimum, they should probably just be nospawn or some combination of other stuff w/the prototypes still intact.
I will close this PR for now. Not sure I will come back to it soon.

**Comment by dvir001** [comment]
> > We use them all downstream, please don't just remove them like this.
> 
> Downstreams can cherry-pick commits and remove ones they don't want.

True but it was still not needed for full removal for sake of sprites, I can see ED made a new PR to do the re-sprites so all good in the end it seems.

**Pull request closed without merging**
