### PR TITLE
Lizards no longer die from freezers

### PR DESCRIPTION
**Pull request by EmoGarbage404**
## About the PR 
yeah apparently the old lizard cold damage threshold was at 11C or 51F which is uhhh...
this moves it down to -8C or 17F, which means lizards no longer start dying in freezers.

**Screenshots**

**Changelog**

:cl:
- fix: Lizards are more resistant to cold, which means they no longer start dying in freezers.

### CODE REVIEW

**Comment by Pangogie** [comment]
Fairly sure this was done intentionally. Can it be balanced so that winter coats are needed for lizards to not get hurt in a freezer?

**Comment by Elijahrane** [comment]
is it really such a huge issue when a species isn't identical to humans in every way? I just tested current one and without a winter coat you can go in and grab something and leave without taking damage

**Comment by EmoGarbage404** [comment]
image
It seems the issue may just be related to freezer temperatures themselves? This is from bagel.

**Comment by Elijahrane** [comment]
> image It seems the issue may just be related to freezer temperatures themselves? This is from bagel.

just don't afk in the freezer (this advice works in real life too)

**Comment by EmoGarbage404** [comment]
So, after doing some yaml perusing, i've come up with some values.

Firstly, the freezer fixed marker says that it is 235K, which is pretty cold. Additionally, wearing a winter coat will negate cold for any species, as it applies a 0.1 cold coefficient. If anything, changing this value does actually nothing, as the temperature of freezers is still far below the 17F of the threshold. All this realistically does is give lizard cold damage a slight damage penalty.

I personally think most of those values should be looked at and rebalanced.

**Comment by moonheart08** [comment]
> > image It seems the issue may just be related to freezer temperatures themselves? This is from bagel.
> 
> just don't afk in the freezer (this advice works in real life too)

This kills them even if they are only in there briefly. Lizards should not be killed by Normal Station Conditions.

**Comment by EmoGarbage404** [comment]
> 

image
i don't need to worry about freezing in a freezer irl because they're not -15 degrees F

**Comment by Elijahrane** [comment]
> > 
> 
> image i don't need to worry about freezing in a freezer irl because they're not -15 degrees F

Freezers here are only like ~8 degrees fahrenheit colder than the walk-in one somewhere I worked at in real life, mostly because thermomachines are funky and they can't replenish and will slowly heat up.

**Comment by Elijahrane** [comment]
> I personally think most of those values should be looked at and rebalanced.

You should give most of the base clothing some thermal regulation IMO.

**Comment by wrexbe** [comment]
Maybe make them fall asleep if they stay in the freezer for a bit.

**Comment by mirrorcult** [comment]
not sure this has really ever been an actual issue and this solution seems to not be popular

**Pull request closed without merging**
