### PR TITLE
Pizza is not a fruit

### PR DESCRIPTION
**Pull request by Tayrtahn**
## About the PR

Pizza no longer qualifies as fruit.

## Why / Balance

Pizza being considered a fruit has been causing integration test failures because the FoodPizzaLarge cargo order contains 16 random pizzas, and a cargo bounty for fruits was recently added (#26160).

The base pizza has the Fruit tag, so any types of pizza that don't override the Tag component also count as fruit. The ones that do override the tags don't add Fruit back in (but typically add Meat), so they're not considered fruit. Because the cargo order gives a random set of pizzas, _sometimes_ there are enough considered fruit that it triggers the test failure.

The fruit tag was added to pizzas by #20328, to enable lizards to eat pizzas (because tomatoes). I appreciate that lizards need food to eat, but this tag usage feels weird. Maybe there should be a "ContainsFruit" tag?
Edit: Added ReptilianFood tag.

(And yes, go ahead and make jokes about the US ruling that pizza can be considered a vegetable, and the whole "tomatoes are fruit" thing)

## Technical details

Removed the Fruit tag from FoodPizzaBase and FoodPizzaSliceBase. Added ReptilianFood tag to both instead.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Pizza is no longer considered a fruit.

### CODE REVIEW

**Comment by LankLTE** [comment]
The pizza was kind of a long line of me just putting my foot down & saying tomatoes are fruit, then deciding pizza contain tomatoes. Meat-containing pizzas are probably common enough for it to be fine, anyways. I don’t really want to see more tags added to support this mess of a system though.

**Review by VasilisThePikachu — CHANGES_REQUESTED** [review]
FoodPizzaSliceBase right below should probably also not be a fruit

(Also rip lizards eating any pizza that does not include meat)

**Comment by Tayrtahn** [comment]
> FoodPizzaSliceBase right below should probably also not be a fruit

Whoops, thanks for catching that.

**Comment by Tayrtahn** [comment]
Added the ReptilianFood tag to both, so lizardfolk can still eat pizza.

**Comment by deltanedas** [comment]
meat bounty also works for pizza slices not just fruit

**Comment by Tayrtahn** [comment]
> meat bounty also works for pizza slices not just fruit

This one?

Screenshot 2024-03-20 at 2 19 18 PM

Seems like meat pizza fits the description well enough:

`bounty-description-food = After the rat king invasion, a neighboring unathi station was left completely without food. A large meat food shipment is needed.`

**Review by VasilisThePikachu — APPROVED** [review]

**Comment by Luxzhv** [comment]
> > meat bounty also works for pizza slices not just fruit
> 
> This one?
> Image
> 
> Seems like meat pizza fits the description well enough:
> 
> `bounty-description-food = After the rat king invasion, a neighboring unathi station was left completely without food. A large meat food shipment is needed.`

Could have individual slices of meat pizza cost less then a whole pizza, but looking into if the points are proper.

**Pull request merged**
