### PR TITLE
Origin Station Update 03.05.2023 (defibs)

### PR DESCRIPTION
**Pull request by brainfood1183**
- Added Defibrillators to the map.
- Expanded salv slightly to include a docking arm for expeditions.
- Removed the AA airlocks to brig and changed perma access from brig to warden.
- Detective office now has detective only access airlocks.

### CODE REVIEW

**Comment by PuroSlavKing** [comment]
maybe you can put airlocks with detective access in the detective's office?

**Comment by brainfood1183** [comment]
> maybe you can put airlocks with detective access in the detective's office?

they still sec access?

**Comment by PuroSlavKing** [comment]
> > maybe you can put airlocks with detective access in the detective's office?
> 
> they still sec access?

yes.

**Comment by brainfood1183** [comment]
> > > maybe you can put airlocks with detective access in the detective's office?
> > 
> > 
> > they still sec access?
> 
> yes.
its done. Thanks for letting me know. It is hard to keep track of everything mapping wise.

**Pull request merged**
