### PR TITLE
Tweak Kitchen Sign Sprite

### PR DESCRIPTION
**Pull request by ps3moira**
## About the PR

Removed the olive part that was on the kitchen sign.
## Why / Balance

It took me so long to realize it's an olive, and discussed with others and some thought it was a cake and a candle. To clarify it a bit more I removed the olive.

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR

**Changelog**
:cl:
- tweak: Changed kitchen sign sprite

### CODE REVIEW

**Comment by beck-thompson** [comment]
I kind of liked the old one

**Comment by Plykiya** [comment]
if you're going to remove the olive at least re-center the burger in the empty space?

**Comment by Emisse** [comment]
Why remove the soul

**Comment by slarticodefast** [comment]
Hey, we had a maintainer discussion about this PR and we decided that we like the olive and the sprite looks less interesting without it.
Therefore I will be closing this PR. Thank you for your contribution.

**Pull request closed without merging**
