### PR TITLE
Improved Inventory / Hand Slots UI

### PR DESCRIPTION
**Pull request by chairbender**
Part of #272 
Updates the inventory / hand slots UI based on the mockups:

- Use new vector-based icons (I had to create my own for the neck slot since there wasn't one provided, feel free to fix it if you hate it). Removed the old icons as well.
- New bottom UI layout, bringing everything together into the center and adding appropriate padding / separation
- New look for highlighting active hand / item action slot
- Item status flyouts now have borders all around
- All the slots on the bottom UI have transparency (previously, when adding additional hands, the added hands did not have transparency IIRC)

image
image

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Please attach pictures.

**Comment by chairbender** [comment]
added pics

**Review by metalgearsloth — APPROVED** [review]
Hand scaling for items is still needed (though obviously out of scope) but it handles the UI scaling really well.

Having a tooltip on hover (maybe with the item name?) would be useful IMO but out of scope if you want.

LGTM.

**Comment by SweptWasTaken** [comment]
I can't say anything nice about this personally, it just looks terri-bad to me. 

Maybe it's nostalgia talking but the old icons looked fine to me and seeing the pixel sprites on these just drains my soul.

I can't offer any constructive criticism except for revert to the old icons. However the UI around the icons looks very slick and clean.

**Comment by mirrorcult** [comment]
new icons irk me a little bit because it seems like the line thickness is different on some of them (compare the ID, backpack, and gloves outlines). everything else is good

**Comment by AJCM-git** [comment]
I like the style but agree that the inconsistent line thickness is a problem, apart from that looks good and fits the rest of the UI

**Comment by PJB3005** [comment]
Problems like inconsistent line thickness aside I still dislike the style in general. The actual types of items used as slot icons (bike helmet, that kind of boots, weird abstract glasses...) are incredibly inconsistent. Some are also incredibly detailed (backpack) while others are not (bike helmet)

Injazz has admitted they are placeholders for the mockup and not at all final. I'd say we're better off keeping the current icons.

**Comment by SweptWasTaken** [comment]
FYI this was discussed on discord and most maintainers disliked the icons.

**Comment by chairbender** [comment]
NP, though I wish I had known this BEFORE rendering all the SVGs (I DID ask on discord but maybe didn't ping the right people or wait long enough), I'll convert them back to the old images but keep the other layout / styling changes.

**Comment by Zumorica** [comment]
Sorry about that.
Feel free to ping badmins or maintainers next time!

**Comment by SweptWasTaken** [comment]
Definitely would have told you had I known.

**Comment by chairbender** [comment]
Sure, I will reach out ahead of time for future UI design approval! Reverted them, how's this looking?

image

**Comment by SweptWasTaken** [comment]
> 
> 
> Sure, I will reach out ahead of time for future UI design approval! Reverted them, how's this looking?
> 
> image

Looks a little off, did you have your UI scale up on this?

**Comment by AJCM-git** [comment]
The sprites are fine as far as i can see, the off things is because the previous hands/slots rectangles are getting drawn behind the icons, which isnt ideal, that needs to be fixed

**Comment by chairbender** [comment]
alright, how about this? (taken at 100% UI scale)
image

**Comment by AJCM-git** [comment]
Looks better now. Also just noticed that the left item status aligns to the left, is it possible to make it align with the right? (that way looks more consistent because the right item status aligns close to the hands, which are in its opposite direction while the left one aligns further from the hands)

**Comment by chairbender** [comment]
image

**Comment by AJCM-git** [comment]
Yeah now its (in my opinion) perfect, good job

**Pull request merged**
