### PR TITLE
UI improvements for holopads

### PR DESCRIPTION
**Pull request by chromiumboy**
## About the PR

This PR makes some improvements to the holopad UI (see #33954)

## Why / Balance

Changes made:
- A search filter has been added to the holopad contacts list
- Incoming calls now also specify the name of the device that the call is coming from

## Technical details

N/A

## Media

Screen Shot 2024-12-24 at 2 09 27 PM
Screen Shot 2024-12-24 at 2 10 16 PM

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

TelephoneComponent.LastCallerId is now a tuple with three strings; the third string is the name of the device the last called the telephone

**Changelog**

:cl:
- tweak: The holoapd UI has been updated to include a text-based filter for the contacts list, and also to specify the name of the holopad that incoming calls originate from

### CODE REVIEW

**Review by ScarKy0 — APPROVED** [review]
Very good stuff! But I think the call window could be a little reformatted cause it looks off? No clue how though.

**Comment by YotaXP** [comment]
The second half of this change may be bad for future listening post operatives who want to pretend to be someone on-station.

**Comment by chromiumboy** [comment]
> The second half of this change may be bad for future listening post operatives who want to pretend to be someone on-station.

We can probably work something out for that. But it doesnt make much sense designing around something that doesn't exist yet, or even have a design doc

**Review by slarticodefast — APPROVED** [review]
Code looks good and works as intended.
Good stuff 👍

**Comment by chromiumboy** [comment]
> Code looks good and works as intended. Good stuff 👍

Thanks for the merge :) Just as a reminder, I've listed some potentially breaking changes, though noone has likely altered the code yet

**Comment by slarticodefast** [comment]
I put it in the codebase changes channel just to be sure

**Comment by chromiumboy** [comment]
> The second half of this change may be bad for future listening post operatives who want to pretend to be someone on-station.

Having thought about this some more, you have a good point. I've opened a PR (#34137) to remove the device name from the call source. Now people will be able to disguise the source of the call simply by relabelling the holopad they are using, even if using a non-standard holopad. This will be even easier once we have a method for renaming holopads built into its UI

**Pull request merged**
