### PR TITLE
tweak(Core_map_Jobslots): Increase round start chemist slots from 1 to 2

### PR DESCRIPTION
**Pull request by Brandon-Huu**
## About the PR

 Increased round start chemist slots from 1 to 2.

## Why / Balance

This will help in situations where a completely new chemist is put into chemistry alone with no one to help.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by UbaserB** [comment]
Why? There are still two slots, just one roundstart one. I don't see the issue?

**Comment by Brandon-Huu** [comment]
> Why? There are still two slots, just one roundstart one. I don't see the issue?
This will help in situations where a completely new chemist is put into chemistry alone with no one to help.

**Comment by UbaserB** [comment]
> This will help in situations where a completely new chemist is put into chemistry alone with no one to help.

I don't see how increasing the round-start slots when there's a good chance that another chemist will come on later (plus CMO helping teach anyway), will improve what you say, a good amount.

**Comment by Brandon-Huu** [comment]
> Why? There are still two slots, just one roundstart one. I don't see the issue?

Also some people might have chemistry set to high and other roles set to medium / 

> I don't see how increasing the round-start slots when there's a good chance that another chemist will come on later (plus CMO helping teach anyway), will improve what you say, a good amount.

When no CMO?
Waiting on another chemist might not happen. ( the other chemists got filled into other roles )

**Pull request merged**
